### ISSUE TITLE
New (5/23/24) NPR media player not supported

### ISSUE THREAD

**Issue by Davem734** [yt-dlp/yt-dlp#10018]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

world wide

### Example URLs

Single: https://www.npr.org/2024/05/23/nx-s1-4977330/live-nation-ticketmaster-sued
Playlist: https://www.npr.org/programs/all-things-considered/

### Provide a description that is worded well enough to be understood

NPR switched to a new embedded media player that does not work with yt-dlp

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ sudo yt-dlp -U
[sudo] password: 
Available version: stable@2024.04.09, Current version: stable@2023.10.13
Current Build Hash: be5cfb6be8930e1a5f427533ec32f2a481276b3da7b249d0150ce2b740ccf1ce
Updating to stable@2024.04.09 ...
Updated yt-dlp to stable@2024.04.09

$ yt-dlp -f bestaudio -vU https://www.npr.org/2024/05/23/nx-s1-4977330/live-nation-ticketmaster-sued
[debug] Command-line config: ['-f', 'bestaudio', '-vU', 'https://www.npr.org/2024/05/23/nx-s1-4977330/live-nation-ticketmaster-sued']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-35-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs broken
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.npr.org/2024/05/23/nx-s1-4977330/live-nation-ticketmaster-sued
[generic] live-nation-ticketmaster-sued: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] live-nation-ticketmaster-sued: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.npr.org/2024/05/23/nx-s1-4977330/live-nation-ticketmaster-sued
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.npr.org/2024/05/23/nx-s1-4977330/live-nation-ticketmaster-sued
```

**Comment by dirkf** [comment]
The NPR content system seems to be in a migration, of which URLs with non-numeric IDs are one sign. Initially just allowing for that change will work with the problem URL, because the old NPR API apparently still works with the new IDs:
```diff
-    _VALID_URL = r'https?://(?:www\.)?npr\.org/(?:sections/[^/]+/)?\d{4}/\d{2}/\d{2}/(?P<id>\d+)'
+    _VALID_URL = r'https?://(?:www\.)?npr\.org/(?:sections/[^/]+/)?\d{4}/\d{2}/\d{2}/(?P<id>[a-z\d-]+)'
```
Some other test pages in the extractor have changed from audio to video and the media can only be fetched from the page itself, not via the API. The problem page can be processed in a similar way, in case the API should fail to work.
