### ISSUE TITLE
udio.com

### ISSUE THREAD

**Issue by ole-tange** [yt-dlp/yt-dlp#10045]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

DK

### Example URLs

https://www.udio.com/songs/ehJuLz9DuCtVapQMVMcA7N

### Provide a description that is worded well enough to be understood

Udio is AI generated music.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.udio.com/songs/ehJuLz9DuCtVapQMVMcA7N
[debug] Command-line config: ['-vU', 'https://www.udio.com/songs/ehJuLz9DuCtVapQMVMcA7N']
[debug] User config "/home/tange/.config/yt-dlp/config": ['--format', 'bestvideo[height<=1080]+bestaudio/best[height<=1080]']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.26.232731 from yt-dlp/yt-dlp-nightly-builds [ae2194e1d] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-101-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.26.232731 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.26.232731 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.udio.com/songs/ehJuLz9DuCtVapQMVMcA7N
[generic] ehJuLz9DuCtVapQMVMcA7N: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ehJuLz9DuCtVapQMVMcA7N: Extracting information
[debug] Looking for embeds
[debug] Identified a Twitter card
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [generic] Lost%20Love%20%28Preview%29%20ext%20v1.1.2.1.1: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2955, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Lost%20Love%20%28Preview%29%20ext%20v1.1.2.1.1: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by HobbyistDev** [comment]
Without the `--formats` argument works. Here's the log:
```shell
(.venv) D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp>python -m yt_dlp -v "https://www.udio.com/songs/ehJuLz9DuCtVapQMVMcA7N"        
[debug] Command-line config: ['-v', 'https://www.udio.com/songs/ehJuLz9DuCtVapQMVMcA7N']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: a06508664 
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: ffmpeg 7.0.2-full_build-www.gyan.dev (setts), ffprobe 7.0.2-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.39.4, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors 
[generic] Extracting URL: https://www.udio.com/songs/ehJuLz9DuCtVapQMVMcA7N 
[generic] ehJuLz9DuCtVapQMVMcA7N: Downloading webpage
WARNING: [generic] Falling back on generic information extractor 
[generic] ehJuLz9DuCtVapQMVMcA7N: Extracting information 
[debug] Looking for embeds
[debug] Identified a Twitter card 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id    
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Lost%20Love%20%28Preview%29%20ext%20v1.1.2.1.1: Downloading 1 format(s): 0 
[debug] Invoking http downloader on "https://storage.googleapis.com/udio-artifacts-c33fe3ba-3ffe-471f-92c8-5dfef90b3ea3/samples/321db721296347b99e1d92b026053e65/1/Lost%2520Love%2520%2528Preview%2529%2520ext%2520v1.1.2.1.1.mp3"
[debug] File locking is not supported. Proceeding without locking 
[download] Destination: The I Don't Knows - Lost Love ｜ Udio [Lost%20Love%20%28Preview%29%20ext%20v1.1.2.1.1].mp3
[download] 100% of   10.28MiB in 00:00:04 at 2.06MiB/s
```
We can extract the data based on `meta` tag value. Here's the example
```
<meta property="og:title" content="The I Don&#x27;t Knows - Lost Love | Udio" />
    <meta property="og:description" content="Listen to Lost Love by The I Don&#x27;t Knows on Udio. Discover, create, and share music with the world. Use the latest technology to create AI music in seconds." />
    <meta property="og:image" content="https://imagedelivery.net/C9yUr1FL21Q6JwfYYh2ozQ/aed96431-75d6-4153-b7a7-64688cecbc00/public" />
    <meta property="og:image:width" content="240" />
    <meta property="og:image:height" content="240" />
    <meta property="og:image:alt" content="The I Don&#x27;t Knows - Lost Love | Udio" />
    <meta property="og:video:url" content="https://storage.googleapis.com/udio-artifacts-c33fe3ba-3ffe-471f-92c8-5dfef90b3ea3/samples/321db721296347b99e1d92b026053e65/d472d954-2734-439e-b4fe-b219ad7ad610/0.mp4" />
    <meta property="og:video:height" content="240" />
    <meta property="og:video:width" content="240" />
    <meta property="og:video:type" content="video/mp4" />
    <meta property="og:audio:url" content="https://storage.googleapis.com/udio-artifacts-c33fe3ba-3ffe-471f-92c8-5dfef90b3ea3/samples/321db721296347b99e1d92b026053e65/1/Lost%2520Love%2520%2528Preview%2529%2520ext%2520v1.1.2.1.1.mp3" />
    <meta property="og:type" content="music.song" />
    <meta name="twitter:card" content="player" />
    <meta name="twitter:site" content="@udiomusic" />
    <meta name="twitter:title" content="The I Don&#x27;t Knows - Lost Love | Udio" />
    <meta name="twitter:description" content="Listen to Lost Love by The I Don&#x27;t Knows on Udio. Discover, create, and share music with the world. Use the latest technology to create AI music in seconds." />
    <meta name="twitter:image" content="https://imagedelivery.net/C9yUr1FL21Q6JwfYYh2ozQ/aed96431-75d6-4153-b7a7-64688cecbc00/public" />
    <meta name="twitter:player" content="https://www.udio.com/embed/6b9ce459-cfc8-48e2-87a9-581d9deea43a" />
    <meta name="twitter:player:stream" content="https://storage.googleapis.com/udio-artifacts-c33fe3ba-3ffe-471f-92c8-5dfef90b3ea3/samples/321db721296347b99e1d92b026053e65/1/Lost%2520Love%2520%2528Preview%2529%2520ext%2520v1.1.2.1.1.mp3" />
    <meta name="twitter:player:width" content="760" />
    <meta name="twitter:player:height" content="240" />
```

**Comment by y4my4my4m** [comment]
How is this piracy/illegal? (And/or any more than ripping from yt audio since they're selling youtube music subscription?)
This used to work on previous versions of yt-dlp and my fix of @iribeirocampos 's PR is simply an update.

Also I'm not sure about the previous commiter but how does it violate ai-policy? Is it about the site itself being AI related?

**Comment by bashonly** [comment]
>  I'm not sure about the previous commiter but how does it violate ai-policy?

The original PR was LLM-generated code and violates our policy.

> How is this piracy/illegal?

Run a search for "udio legal" or "udio lawsuit" and you'll get the picture, e.g. https://www.artistdirect.com/news/2026-06-27-ai-music-platforms-suno-and-udio-face-major-copyright-lawsuits-spotify-adds-ai-voiceovers-amid-artist-allegations

Supporting this site would be a liability for the project.

**Comment by ole-tange** [comment]
> How is this piracy/illegal?

I fully support @bashonly's decision to play it safe: Udio/Suno is legally uncertain, and it is important that `yt-dlp` stays legal.

If you personally believe Udio/Suno is legal, it is, however, surprisingly easy to use VS Codium + Claude and make a private branch where you ask Claude to make the extractor for the two sites. You keep your version up-to-day by simply merging master into your local branch.

My Makefile looks like this:

~~~
DIR  = privat/2026-ytdlp
VENV        = ~/$(DIR)/venv

binary: venv
        cd yt-dlp && make lazy-extractors
        cd yt-dlp && $(VENV)/bin/python bundle/pyinstaller.py

venv:
        python3 -m venv $(VENV) && $(VENV)/bin/pip install -q -e yt-dlp'[curl-cffi]' pyinstaller

update:
        cd yt-dlp && git checkout master && git pull && git checkout local && git merge -X theirs master

install: yt-dlp/dist/yt-dlp_linux
        rsync yt-dlp/dist/yt-dlp_linux `which yt-dlp`
~~~

2026-ytdlp/yt-dlp contains the git repository.
