### ISSUE TITLE
[Facebook] No video formats found for private /videos/ links

### ISSUE THREAD

**Issue by RABIDYOTE** [yt-dlp/yt-dlp#10058]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

When attempting to download a Facebook video that is non-Public and using the `--cookies-from-browser` command, yt-dlp will throw an error. This issue appeared while I was attempting to figure out a warning I was receiving; it didn't seem to affect the video download, but it kept coming up. I ended up clearing my cookies from Facebook entirely and logging in again, and that's when I started receiving these errors. I can verify that the URL itself works in my browser as well as playing the video itself. Changing my Enhanced Tracking Protection settings, globally or otherwise, does not seem to fix the issue, nor does restarting my browser. I have tried using both of these commands, `--cookies-from-browser firefox` and `--cookies cookies.txt`, which seem to have varying results. The first command doesn't appear to work with either URL format, even if I specify the profile I want to use. The second command initially didn't work until I tried another video, and additionally doesn't work with `mbasic` URLS. I have tried multiple videos as well as multiple URL formats, and alternating commands.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://www.facebook.com/ruby.touchdown/videos/1109948050108075', '-vU']
[debug] Portable config "C:\Users\jprig\Documents\yt-dlp\yt-dlp.conf": ['-o', '${USERPROFILE}/Documents/yt-dlp/output/facebook-%(id)s.%(ext)s', '--ffmpeg-location', '${USERPROFILE}/Documents/yt-dlp/ffmpeg/bin', '--no-mtime']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-115429-gb2b23f353a-20240528 (setts), ffprobe N-115429-gb2b23f353a-20240528
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\jprig\AppData\Roaming\Mozilla\Firefox\Profiles\oelowrnv.default-release\cookies.sqlite"
Extracted 1762 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[facebook] Extracting URL: https://www.facebook.com/ruby.touchdown/videos/1109948050108075
[facebook] 1109948050108075: Downloading webpage
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [facebook] 1109948050108075: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1762, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1821, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2825, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1104, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 1109948050108075: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by HomeStarRunnerTron** [comment]
I don't know if this is useful information, but I found in my Network Activity that you'll get two long URLs, one for video and one for audio, and the relevant part of each is everything before "&bytestart=". Then, it'll download the full MP4 for both video and audio.
