### ISSUE TITLE
Pornmz.com unsupported/supported issues

### ISSUE THREAD

**Issue by Ed3151** [yt-dlp/yt-dlp#10054]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

Single Video:https://pornmz.com/video/id=pm13141808113745 downloading playlist but not working as it should be
Single Video: https://pornmz.com/video/id=pm28144808192745 Unsupported

### Provide a description that is worded well enough to be understood

please add pornmz.com some url working but its downloading playlist some are unsupported same its not unsupported

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
unsupported
[debug] Command-line config: ['-v', 'https://pornmz.com/video/id=pm28144808192745']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.13.232704 from yt-dlp/yt-dlp-nightly-builds [351dc0bc3] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1803 extractors
[generic] Extracting URL: https://pornmz.com/video/id=pm28144808192745
[generic] id=pm28144808192745: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] id=pm28144808192745: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://pornmz.com/video/id=pm28144808192745
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1741, in __extract_info
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2514, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://pornmz.com/video/id=pm28144808192745










supported but not downloading main file
[debug] Command-line config: ['-v', 'https://pornmz.com/video/id=pm13141808113745']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.13.232704 from yt-dlp/yt-dlp-nightly-builds [351dc0bc3] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1803 extractors
[generic] Extracting URL: https://pornmz.com/video/id=pm13141808113745
[generic] id=pm13141808113745: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] id=pm13141808113745: Extracting information
[debug] Looking for embeds
[debug] Identified 10 html5 embeds
[download] Downloading playlist: Big Tits Aussie Angela White Gets Dp
[generic] Playlist Big Tits Aussie Angela White Gets Dp: Downloading 10 items of 10
[download] Downloading item 1 of 10
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] id=pm13141808113745-1: Downloading 1 format(s): 0
[debug] Invoking http downloader on "http://b1.trafficdeposit.com/blog/0/21//vid/618afb5ec39a8/6628093e1d387/vidthumb.mp4"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Big Tits Aussie Angela White Gets Dp (1) [id=pm13141808113745-1].mp4
[download] 100% of  439.28KiB in 00:00:02 at 188.71KiB/s
[download] Downloading item 2 of 10
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] id=pm13141808113745-2: Downloading 1 format(s): 0
[debug] Invoking http downloader on "http://images.momlover.com/videos/putting_in_the_effort/videos/loops/datingmystepson_putting_in_the_effort_loop_480.mp4"
[download] Destination: Big Tits Aussie Angela White Gets Dp (2) [id=pm13141808113745-2].mp4
[download] 100% of    1.70MiB in 00:00:02 at 671.68KiB/s
[download] Downloading item 3 of 10
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] id=pm13141808113745-3: Downloading 1 format(s): 0
[debug] Invoking http downloader on "http://videothumb.gammacdn.com/500x281/246444.mp4"
[download] Destination: Big Tits Aussie Angela White Gets Dp (3) [id=pm13141808113745-3].mp4
[download] 100% of  469.69KiB in 00:00:01 at 424.86KiB/s
[download] Downloading item 4 of 10
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] id=pm13141808113745-4: Downloading 1 format(s): 0
[debug] Invoking http downloader on "http://images.psmcdn.net/dc/tour/pics/dee_williams_and_mira_monroe/bio_small.mp4"
[download] Destination: Big Tits Aussie Angela White Gets Dp (4) [id=pm13141808113745-4].mp4
[download]  68.7% of   75.00MiB at    2.06MiB/s ETA 00:11
```

**Comment by Ed3151** [comment]
problem solved
```
from .common import InfoExtractor
from ..utils import js_to_json, urljoin
   
class PornmzIE(InfoExtractor):
    _VALID_URL =  r'https?://(?:www\\.)?pornmz.com/video/id=(?P<id>[^/?#]+)'
   
    def _real_extract(self, url):
        video_id = self._match_id(url) 
        url = f'https://pornmz.com/video/id={video_id}'
        
        webpage = self._download_webpage(url, video_id)
    
        # url = self._html_search_regex(
            # r'<meta itemprop="contentURL" content="(.*?)"', webpage,
            # 'contentURL', fatal=False)
            
        url = self._html_search_regex(
                r'<div class="responsive-player">\s*<iframe src="(.*?)"', webpage,
                'iframe', default=None)
                        
        title = self._html_search_regex(
            r'<meta property="og:title" content="(.*?)"', webpage,
            'og:title', fatal=False)

        poster = self._html_search_regex(
            r'<meta property="og:image" content="(.*?)"', webpage,
            'og:image', fatal=False)

        description = self._html_search_regex(
            r'<meta property="og:description" content="(.*?)"', webpage,
            'og:description', fatal=False)
        
        webpage = self._download_webpage(url, video_id,headers=headers)
     
        url = self._html_search_regex(
            r'<source\s+src="(.*?)"', webpage,
            'video URL', default=None)     
            
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/66.0',
            'referer': "https://pornmz.net"
        }   
        
    
        return {
            'id': video_id,
            'url': url,
            'title': title,
            'description': description,
            'thumbnail': poster,
            'http_headers': headers,
            'age_limit': 18,
            'ext': 'mp4',
        }
```
