### ISSUE TITLE
cannot fetch information from import for url (“stderr”: “ERROR: [youtube] xxx: Get the best YouTube experience. Sign in to save videos, subscribe, and more”

### ISSUE THREAD

**Issue by Tang9696** [yt-dlp/yt-dlp#10050]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm using the yt-dlp tool in peertube to upload Youtube videos via URL, but it's reporting an error, and I've updated yt-dlp without solving the problem!Now I'm using the latest version of yt-dlp 2024.05.27

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
error[5/28/2024, 6:41:34 AM] An error occurred while importing the video https://www.youtube.com/watch?v=TYtoKCSyWbY.
{
  "err": {
    "stack": "Error: Command failed with exit code 1: /usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=TYtoKCSyWbY\nERROR: [youtube] TYtoKCSyWbY: Get the best YouTube experience. Sign in to save videos, subscribe, and more\n    at makeError (file:///var/www/peertube/versions/peertube-v6.0.4/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (file:///var/www/peertube/versions/peertube-v6.0.4/node_modules/execa/index.js:124:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async YoutubeDLCLI.run (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/helpers/youtube-dl/youtube-dl-cli.js:141:24)\n    at async YoutubeDLCLI.getInfo (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/helpers/youtube-dl/youtube-dl-cli.js:89:22)\n    at async YoutubeDLWrapper.getInfoForDownload (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/helpers/youtube-dl/youtube-dl-wrapper.js:23:22)\n    at async buildYoutubeDLImport (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/lib/video-pre-import.js:104:25)\n    at async handleYoutubeDlImport (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/controllers/api/videos/import.js:113:38)",
    "message": "Cannot fetch information from import for URL https://www.youtube.com/watch?v=TYtoKCSyWbY",
    "code": 0,
    "cause": {
      "stack": "Error: Command failed with exit code 1: /usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=TYtoKCSyWbY\nERROR: [youtube] TYtoKCSyWbY: Get the best YouTube experience. Sign in to save videos, subscribe, and more\n    at makeError (file:///var/www/peertube/versions/peertube-v6.0.4/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (file:///var/www/peertube/versions/peertube-v6.0.4/node_modules/execa/index.js:124:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async YoutubeDLCLI.run (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/helpers/youtube-dl/youtube-dl-cli.js:141:24)\n    at async YoutubeDLCLI.getInfo (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/helpers/youtube-dl/youtube-dl-cli.js:89:22)\n    at async YoutubeDLWrapper.getInfoForDownload (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/helpers/youtube-dl/youtube-dl-wrapper.js:23:22)\n    at async buildYoutubeDLImport (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/lib/video-pre-import.js:104:25)\n    at async handleYoutubeDlImport (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/controllers/api/videos/import.js:113:38)",
      "message": "Command failed with exit code 1: /usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=TYtoKCSyWbY\nERROR: [youtube] TYtoKCSyWbY: Get the best YouTube experience. Sign in to save videos, subscribe, and more",
      "shortMessage": "Command failed with exit code 1: /usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=TYtoKCSyWbY",
      "command": "/usr/bin/python3 /var/www/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=TYtoKCSyWbY",
      "escapedCommand": "\"/usr/bin/python3\" \"/var/www/peertube/storage/bin/yt-dlp\" --dump-json -f \"bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best\" \"https://www.youtube.com/watch?v=TYtoKCSyWbY\"",
      "exitCode": 1,
      "stdout": "",
      "stderr": "ERROR: [youtube] TYtoKCSyWbY: Get the best YouTube experience. Sign in to save videos, subscribe, and more",
      "cwd": "/var/www/peertube/versions/peertube-v6.0.4",
      "failed": true,
      "timedOut": false,
      "isCanceled": false,
      "killed": false
    }
  }
}
error[5/28/2024, 6:41:34 AM] Client log: Backend returned code 400, errorMessage is: Cannot fetch information from import for URL https://www.youtube.com/watch?v=TYtoKCSyWbY
{
  "tags": [
    "client"
  ],
  "username": "root",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
  "url": "https://peertube.pelagia.by/videos/upload#import-url"
}
error[5/28/2024, 6:41:34 AM] Client log: Error: Cannot fetch information from import for URL https://www.youtube.com/watch?v=TYtoKCSyWbY
{
  "tags": [
    "client"
  ],
  "username": "root",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
  "url": "https://peertube.pelagia.by/videos/upload#import-url"
}
```

**Comment by bashonly** [comment]
> - [x] I've checked that all provided URLs are **playable in a browser** with the **same IP** and **same login details**

You checked this. Can you confirm that this is an accurate statement?

**Comment by Tang9696** [comment]
I've tried logging in, playing, and uploading in both Google and Firefox!

> > * [x]  I've checked that all provided URLs are **playable in a browser** with the **same IP** and **same login details**
> 
> You checked this. Can you confirm that this is an accurate statement?

**Comment by bashonly** [comment]
What I mean is can you play the video in browser without being logged in from the same IP? Since I assume you are not passing logged-in cookies to yt-dlp

**Comment by Tang9696** [comment]
The video plays whether logged in or not, I've also tried downloading all the cookies and letting yt-dlp upload using the specified cookies, but it still reports the same problem!

**Comment by Tang9696** [comment]
I didn't have any problems before, everything was after updating nodejs22, but the problem persisted after I would back out of the nodejs version, I tried changing browsers, logging in again, specifying cookies, upgrading yt-dlp all failed to solve the problem!

**Comment by dirkf** [comment]
What about decoupling the _yt-dlp_ command, based on the log?
```
yt-dlp -v --dump-json -f 'bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best' 'https://www.youtube.com/watch?v=TYtoKCSyWbY'
```

**Comment by Tang9696** [comment]
[image: image.png]
It still gives me the same error, I also used the downloaded cookies, and I
get the same error.

dirkf ***@***.***> 于2024年5月28日周二 14:27写道：

**Comment by bashonly** [comment]
Also, please always paste logs AS TEXT

**Comment by Tang9696** [comment]
Thank you very much for your guidance, but for the problem you described, how do I solve it?
--youtube has almost certainly banned your cloud server's IP

**Comment by bashonly** [comment]
You need to change your IP address and/or rotate it regularly

**Comment by satoshinotdead** [comment]
Hello @bashonly, I'm currently using a IPV6 rotator for a YT client but it seems that's not working with Peertube.

May I know where to look to solve this issue?

**Comment by bashonly** [comment]
@satoshinotdead open a new issue
