### ISSUE TITLE
orf.on/tvthek - Livestreams

### ISSUE THREAD

**Issue by hurda** [yt-dlp/yt-dlp#10052]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria

### Example URLs

https://on.orf.at/livestream/14319441/eishockey-wm-semifinale-kanada-schweiz (offline already, listed for the URL-format)

If livestreams are online, they are usually listed here with a red dot next to their title for live streams, or gray for future streams:
https://on.orf.at/sammlung/13870213/exklusiv-in-voller-laenge-nur-im-streaming-auf-orf-on
https://on.orf.at/sammlung/13869249/sport-highlights
These streams might be regionlocked.

### Provide a description that is worded well enough to be understood

yt-dlp supported livestreams from tvthek.orf.at, and it was possible to watch these livestreams in an external mediaplayer like mpc-hc instead of a browser.
Now that ORF relaunched tvthek as orf.on, yt-dlp is missing support for livestreams. Manually extracting the mpd/m3u8 and playing them with mpc-hc still works after the relaunch.
Not to be confused with "ORF Live", which are 24/7 livestreams of their tv-channels.

Video-URL: `https://on.orf.at/livestream/14319441/eishockey-wm-semifinale-kanada-schweiz` (example)
JSON-URL: `https://api-tvthek.orf.at/api/v4.3/public/livestream/encrypted/`{encrypted_id}
Prefix for encrypted_id: `8876324jshjd7293ktd`
This was the JSON for the stream:
[on.orf.at_livestream_14319441_eishockey-wm-semifinale-kanada-schweiz.json](https://github.com/yt-dlp/yt-dlp/files/15466405/on.orf.at_livestream_14319441_eishockey-wm-semifinale-kanada-schweiz.json)

No idea if there are any differences compared to normal on.orf.at streams or past tvthek-livestreams, with regard to downloading, subtitles etc.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vUF', 'https://on.orf.at/livestream/14320204/pressekonferenz-neos-zu-aktuellen-entwicklungen']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.27.232744 from yt-dlp/yt-dlp-nightly-builds [111b61dde] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.27.232744 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.27.232744 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://on.orf.at/livestream/14320204/pressekonferenz-neos-zu-aktuellen-entwicklungen
[generic] pressekonferenz-neos-zu-aktuellen-entwicklungen: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] pressekonferenz-neos-zu-aktuellen-entwicklungen: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://on.orf.at/livestream/14320204/pressekonferenz-neos-zu-aktuellen-entwicklungen
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1741, in __extract_info
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2514, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://on.orf.at/livestream/14320204/pressekonferenz-neos-zu-aktuellen-entwicklungen
```

**Comment by dirkf** [comment]
The same tactics used for the newly updated `ONORFIE` can be adapted for 'https://on.orf.at/livestream/14320204/pressekonferenz-neos-zu-aktuellen-entwicklungen' (though the stream is beendet), but I can't find anything actually live on the site with `/livestream/` today.

The sport-highlights page offers me a lot of "only in Austria" videos with one live stream that is actually the Sports channel's ORF Live link and whose media is DRM-protected.

**Comment by hurda** [comment]
Tested the latest (2024.06.12) youtube-dl nightly with ytdl-org/youtube-dl#32802 merged and the livestream-URLs are working again.
Tested with https://on.orf.at/livestream/14325056/nationalratssitzung-in-voller-laenge (should be regionfree) which will work another 8 hours as of right now.

Thank you very much!

**Comment by arminfuerst** [comment]
I just learned, that on.orf.at supports sharing of links to the live-stream in the past 24 hours. It would be good, if yt-dlp would support such links. An example for such a link is:
https://on.orf.at/live?channel=orf3&timestamp=1718445069000
If I watch the network analyzer, this results in following link:
https://orf3-247.mdn.ors.at/orf/orf3/qxa-247/manifest.mpd?offset=5&begin=20240615T095109&end=20240615T112504
This link can be downloaded with yt-dlp.
Does it make sense to leave this in this issue or shall I create a new one?

**Comment by dirkf** [comment]
[Relevant upstream changes](https://github.com/yt-dlp/yt-dlp/issues/10052#issuecomment-2165063776) are promised to be included in some future release.

**Comment by ds2k5** [comment]
Hi,
is it possible to remove watermark from the video ? ( ORF ON, ORF . AT )

**Comment by arminfuerst** [comment]
> Hi, is it possible to remove watermark from the video ? ( ORF ON, ORF . AT )

In my opinion, this is out of scope of yt-dlp. There are other tools (e.g. Avidemux) providing filters to modify videos.
