### ISSUE TITLE
[SOOP global] Global streaming platform

### ISSUE THREAD

**Issue by hui1601** [yt-dlp/yt-dlp#10066]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Vod(Replay): https://www.sooplive.com/video/607
- Live stream: https://www.sooplive.com/tobbytravel

### Provide a description that is worded well enough to be understood

soop live is a streaming platform created by soop corp in Korea. It is known as Afreeca TV, an existing Korean streaming platform, and is currently launching a global service under the name soop. The currently operating afreeca servers will also be moved to soop in the future.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', 'https://www.sooplive.com/video/607']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (source)
[debug] Git HEAD: 8b46ad4d8
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.8.0-31-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg N-115086-g96449cfeae (fdk,setts), ffprobe N-115086-g96449cfeae
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2024.02.02, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.45.3, urllib3-2.2.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1833 extractors
[generic] Extracting URL: https://www.sooplive.com/video/607
[generic] 607: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 607: Extracting information
[debug] Looking for embeds
ERROR: No module named 'yt_dlp.extractor.cableav'
Traceback (most recent call last):
  File "/data/projects/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/generic.py", line 2509, in _real_extract
    embeds = list(self._extract_embeds(original_url, webpage, urlh=full_response, info_dict=info_dict))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/generic.py", line 2534, in _extract_embeds
    gen = ie.extract_from_webpage(self._downloader, url, webpage)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
                   ^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/utils/_utils.py", line 4992, in __get__
    return self.func(cls)
           ^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 33, in real_class
    cls._real_class = getattr(importlib.import_module(cls._module), cls.__name__)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hibot/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yt_dlp.extractor.cableav'
```

**Comment by NormanMises** [comment]
We need it!!!

**Comment by doe1080** [comment]
https://github.com/yt-dlp/yt-dlp/pull/16436
