### ISSUE TITLE
Unable to download the video list on Nico Nico Douga

### ISSUE THREAD

**Issue by bmg0083dark** [yt-dlp/yt-dlp#10084]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

japan

### Example URLs

https://www.nicovideo.jp/user/92519680/video

### Provide a description that is worded well enough to be understood

downloadable
https://www.nicovideo.jp/user/92519680/mylist/73193091?ref=pc_userpage_mylist
https://www.nicovideo.jp/user/92519680/series/436798?ref=user_series
Not downloadable
https://www.nicovideo.jp/user/92519680/mylist
https://www.nicovideo.jp/user/92519680/series
https://www.nicovideo.jp/user/92519680/video

Simply selecting the ‘Videos/Series’ tab on the recipient’s side does not allow downloading all posted videos. Specifically, I want to download all videos from the ‘Video List’.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--ffmpeg-location', 'F:\\data\\isyoku\\data\\movie\\moviedit\\net\\ytdig\\yt-dlp-gui\\ffmpeg.exe', 'https://www.nicovideo.jp/user/92519680/mylist?ref=pc_userpage_menu', '--download-archive', 'F:\\data\\isyoku\\data\\movie\\moviedit\\net\\ytdig\\yt-dlp-gui\\download-archive.txt', '--output', 'F:\\data\\isyoku\\mad\\mpeg\\mov\\%(playlist_title)s %(uploader)s %(title)s [%(id)s] %(resolution)s %(fps)sfps .%(ext)s', '--format', 'bestvideo+bestaudio/best', '-vU', '--ignore-errors', '--ignore-config', '--no-cache-dir', '--no-overwrites', '--no-mtime', '--add-metadata', '--rm-cache-dir', '--age-limit', '50', '--cookies-from-browser', 'firefox:h895n6li.default', "'verbose':", 'True']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nicolaasjan/yt-dlp@2024.05.31.055336 [2e5a47da4] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-115457-g6de951923b-20240530 (setts), ffprobe N-115457-g6de951923b-20240530, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\testtest\AppData\Roaming\Mozilla\Firefox\Profiles\h895n6li.default\cookies.sqlite"
Extracted 1741 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Loading archive file 'F:\\data\\isyoku\\data\\movie\\moviedit\\net\\ytdig\\yt-dlp-gui\\download-archive.txt'
Cache is disabled (Did you combine --no-cache-dir and --rm-cache-dir?)
[debug] Fetching release info: https://api.github.com/repos/nicolaasjan/yt-dlp/releases/latest
Latest version: nicolaasjan/yt-dlp@2024.05.31.055336
yt-dlp is up to date (nicolaasjan/yt-dlp@2024.05.31.055336)
[generic] Extracting URL: https://www.nicovideo.jp/user/92519680/mylist?ref=pc_userpage_menu
[generic] mylist?ref=pc_userpage_menu: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] mylist?ref=pc_userpage_menu: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.nicovideo.jp/user/92519680/mylist?ref=pc_userpage_menu
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1741, in __extract_info
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2514, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nicovideo.jp/user/92519680/mylist?ref=pc_userpage_menu

[generic] Extracting URL: 'verbose':
ERROR: [generic] "'verbose':" is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:'verbose':" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2349, in _real_extract

[generic] Extracting URL: True
ERROR: [generic] 'True' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:True" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2349, in _real_extract


F:\data\isyoku\data\movie\moviedit\net\ytdig\yt-dlp-gui\log>echo off
```

**Comment by bashonly** [comment]
#11324 will add support for `/user/ID/video` URLs, but PRs still needed for `/user/ID/mylist` and `/user/ID/series` URL support
