### ISSUE TITLE
Site support request: Collab.inc video list (vl.collab.inc)

### ISSUE THREAD

**Issue by OIRNOIR** [yt-dlp/yt-dlp#10080]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

- Single video: https://vl.collab.inc/videos/553891

### Provide a description that is worded well enough to be understood

After examining the site in devtools, the video ID after /videos/ in the URL can be used in a GET request to `https://dashboard.collab.inc/api/public_video_library/<VIDEO_ID_HERE>` with what looks like no custom headers. This GET request returns some JSON, which includes a `hls_stream` key which points to a *watermarked* m3u8 video. The m3u8 links look like this: `https://collab-media-assets.s3-us-west-2.amazonaws.com/watermarked_hls/3fefae2f-3d21-4a6b-bb45-3899023ce0cb/5548610291_collab_clips_mpugc_getting_ducks_out_of_garage.m3u8`. Getting the un-watermarked hls stream link is simple: Replace `watermarked_hls` with `hls` in the URL so that the link reads as follows: `https://collab-media-assets.s3-us-west-2.amazonaws.com/hls/3fefae2f-3d21-4a6b-bb45-3899023ce0cb/5548610291_collab_clips_mpugc_getting_ducks_out_of_garage.m3u8`. Then, simply download the hls stream (like yt-dlp has been doing for millenia) and the video has been downloaded!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vl.collab.inc/videos/553891']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (zip)
[debug] Python 3.10.1 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 1.1.1l  24 Aug 2021)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.02.02, mutagen-1.47.0, sqlite3-3.35.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://vl.collab.inc/videos/553891
[generic] 553891: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 553891: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://vl.collab.inc/videos/553891
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vl.collab.inc/videos/553891
```

**Comment by OIRNOIR** [comment]
I would implement it myself but I'm more of a javascript guy.
