### ISSUE TITLE
sap.com

### ISSUE THREAD

**Issue by meokey** [yt-dlp/yt-dlp#10122]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

https://www.sap.com/events/sapphire/virtual/flow/sap/s24/catalog/page/catalog/session/1713860797693001MLQb

### Provide a description that is worded well enough to be understood

[SAP SE is a German multinational software company based in Walldorf, Baden-Württemberg. It develops enterprise software to manage business operations and customer relations. The company is the world's leading enterprise resource planning (ERP) software vendor.
The company is the largest non-American software company by revenue and the world's third-largest publicly traded software company by revenue. As of December 2023, SAP is the largest German company by market capitalization.](https://en.wikipedia.org/wiki/SAP)

SAP releases educational videos of introduction and HOWTO of their products, which is essential resource for professionals in the area.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies', 'cookies.txt', '-vU', 'https://www.sap.com/events/sapphire/virtual/flow/sap/s24/catalog/page/catalog/session/1713860797693001MLQb']
[debug] Portable config "~/.local/bin/yt-dlp.conf": ['-f', 'bv*+ba/b', '-o', '%(title)s.f%(format_id)s.%(ext)s', '--write-info-json', '--write-playlist-metafiles']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (zip)
[debug] Python 3.8.15 (CPython x86_64 64bit) - Linux-4.4.302+-x86_64-with-glibc2.34 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.1.9
[debug] Optional libraries: certifi-2022.12.07, requests-2.31.0, sqlite3-3.40.0, urllib3-1.26.11
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.sap.com/events/sapphire/virtual/flow/sap/s24/catalog/page/catalog/session/1713860797693001MLQb
[generic] 1713860797693001MLQb: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1713860797693001MLQb: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.sap.com/events/sapphire/virtual/flow/sap/s24/catalog/page/catalog/session/1713860797693001MLQb
Traceback (most recent call last):
  File "~/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "~/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "~/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "~/.local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.sap.com/events/sapphire/virtual/flow/sap/s24/catalog/page/catalog/session/1713860797693001MLQb
```

**Comment by meokey** [comment]
I just realized that it's also using Kaltura player too, so refer to existing thread #4986 

for example, URL= https://learning.sap.com/learning-journeys/learning-to-use-the-leanix-tool-for-successful-enterprise-architecture

```
        <script type="application/ld+json">
            {
                "@context": "https://schema.org",
                "@type": "VideoObject",
                "name": "Teaser.mp4",
                "description": "Join us for this training on Linux Enterprise Architecture Management. Suitable for enterprise architects, CIOs, and IT project managers. Enhance your skills and transform your business.# This description was auto-generated #",
                "thumbnailUrl": [
                    "https://cdnsecakmi.kaltura.com/p/1921661/thumbnail/entry_id/1_rclsqwoe"
                ],
                "uploadDate": "2024-5-14",
                "duration": "PT52S",
                "contentUrl": "https://cdnapisec.kaltura.com/p/1921661/sp/192166100/playManifest/entryId/1_rclsqwoe/format/download/protocol/https/flavorParamIds/0",
                "interactionStatistic": [
                    {
                        "@type": "InteractionCounter",
                        "interactionType": "https://schema.org/WatchAction",
                        "userInteractionCount": 418
                    }
                ],
                "transcript": "Hi, we are happy to have you on board and are delighted that you have decided to join us for this training. My name is Marlene Jung and I will guide you through the certification. However, I won't be the only one. This training will also be facilitated by our team of experts. By completing this certification, you will better understand Linux Enterprise Architecture Management and how it helps our customers bootstrap their business and technology transformation journeys. This certification is geared towards enterprise architects, but is also beneficial for CIOs, application owners, IT project managers, solution architects, or product managers who are closely involved in architecture work or want to upskill themselves in the area of EA. No matter if you are a beginner or an experienced user of Linax who would like to refresh your knowledge, you will surely benefit from this course. So if you are ready, let's dive in."
            }</script>
```

```
                            "videoData": [
                                {
                                    "ID": "eec3208f-13be-4e1b-b30f-30e2171a5dad",
                                    "objId": "1_rclsqwoe",
                                    "objType": "embedded-video",
                                    "videoId": "1_rclsqwoe",
                                    "title": "Teaser.mp4",
                                    "release": "1",
                                    "description": "Join us for this training on Linux Enterprise Architecture Management. Suitable for enterprise architects, CIOs, and IT project managers. Enhance your skills and transform your business.\u003cbr\u003e\u003cbr\u003e# This description was auto-generated #",
                                    "transcript": "Hi, we are happy to have you on board and are delighted that you have decided to join us for this training. My name is Marlene Jung and I will guide you through the certification. However, I won't be the only one. This training will also be facilitated by our team of experts. By completing this certification, you will better understand Linux Enterprise Architecture Management and how it helps our customers bootstrap their business and technology transformation journeys. This certification is geared towards enterprise architects, but is also beneficial for CIOs, application owners, IT project managers, solution architects, or product managers who are closely involved in architecture work or want to upskill themselves in the area of EA. No matter if you are a beginner or an experienced user of Linax who would like to refresh your knowledge, you will surely benefit from this course. So if you are ready, let's dive in.",
                                    "sourceCreatedAt": "1715674288",
                                    "downloadUrl": "https://cdnapisec.kaltura.com/p/1921661/sp/192166100/playManifest/entryId/1_rclsqwoe/format/download/protocol/https/flavorParamIds/0",
                                    "duration": "52",
                                    "thumbnailUrl": "https://cdnsecakmi.kaltura.com/p/1921661/thumbnail/entry_id/1_rclsqwoe",
                                    "views": 418,
                                    "subTextList": [
                                        {
                                            "label": "May 14, 2024"
                                        },
                                        {
                                            "label": "00:52"
                                        },
                                        {
                                            "label": "418 views"
                                        }
                                    ],
                                    "kaltura": {
                                        "ID": "1_rclsqwoe",
                                        "name": "Teaser.mp4"
                                    }
                                }
                            ],
                            "breadcrumbs": [
                                {
                                    "title": "Browse",
                                    "href": "https://learning.sap.com/browse"},
                                    {
                                        "title": "Learning Journeys",
                                        "href": "https://learning.sap.com/learning-journeys"
                                    },
                                    {
                                        "title": "Learning to Use the LeanIX Tool for Successful Enterprise Architecture",
                                        "href": "https://learning.sap.com/learning-journeys/learning-to-use-the-leanix-tool-for-successful-enterprise-architecture"
                                    }
                                ]
                            },
                            "viewMode": "published",
                            "featureFlags": {
                                "fe_ecp_8903": true,
                                "fe_enable_cert_v2": true,
                                "fe_how_to_prepare_aggregation": true,
                                "using_practice_system_check_in_lsc_ecp_8126": true,
                                "fe_enable_new_search": true,
                                "fe_course_translations": true,
                                "fe_ecp_9355": true,
                                "fe_merge_parent_learning_scrolling_tabs": true,
                                "fe_ecp_9354": true,
                                "fe_ecp_9356": true,
                                "fe_ecp_9359": true,
                                "fe_catalog_pages": true,
                                "fe_ecp_9878": true,
                                "fe_faceted_filters": true,
                                "fe_practice_systems_overview": true,
                                "fe_hide_applied_filters": true,
                                "fe_ecp_9003": true,
                                "fe_preview_catalog_pages": true,
                                "fe_use_crs_updated_endpoint_ecp9446": true,
                                "fe_user_notifications_ecp8899": true,
                                "fe_stay_certified_lj_banner": true,
                                "fe_video_progress_tracking": true,
                                "fe_feedback_survey": true,
                                "fe_lart_739": true,
                                "fe_learning_formats_pages": true,
                                "fe_practice_system": true,
                                "fe_login_dialog": true,
                                "fe_enable_catalog_download": true,
                                "fe_ecp_9370": true,
                                "fe_ecp_9694": true,
                                "fe_listing_page_dropdown": true,
                                "using_acceptedtickets_gating": true,
                                "fe_live_sessions_details_page": true,
                                "fe_enable_learning_objects_analytics_ecp8975": true,
                                "fe_video_learning_format": true,
                                "fe_enable_ecp8700": true,
                                "fe_enable_lart_630": true,
                                "fe_send_lesson_started_records": true,
                                "fe_ecp_9700": true,
                                "fe_learning_journey_live_sessions": true
                            },
                            "systemAlerts": null
                        },
                        "__N_SSG": true
                    },
```

**Comment by bashonly** [comment]
as a workaround, that particular video can be downloaded with `yt-dlp kaltura:1921661:1_rclsqwoe`

**Comment by meokey** [comment]
> as a workaround, that particular video can be downloaded with `yt-dlp kaltura:1921661:1_rclsqwoe`

thanks @bashonly , the trick successfully downloaded the cover video 'Teaser.mp4.fmp4-5321.mp4' but eventually failed to download the target video on the page:
```
[debug] Command-line config: ['-vU', 'kaltura:1921661:1_rclsqwoe', 'https://learning.sap.com/learning-journeys/applying-the-rise-with-sap-methodology/exploring-the-clean-core-approach_e096a3e4-3a8c-4a62-9e10-49a478f54cc3']
[debug] Portable config "~/.local/bin/yt-dlp.conf": ['-f', 'bv*+ba/b', '-o', '%(title)s.f%(format_id)s.%(ext)s', '--write-info-json', '--write-playlist-metafiles']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (zip)
[debug] Python 3.8.15 (CPython x86_64 64bit) - Linux-4.4.302+-x86_64-with-glibc2.34 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.1.9
[debug] Optional libraries: certifi-2022.12.07, requests-2.31.0, sqlite3-3.40.0, urllib3-1.26.11
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[Kaltura] Extracting URL: kaltura:1921661:1_rclsqwoe
[Kaltura] 1_rclsqwoe: Downloading video info JSON (Kaltura html5 player)
[Kaltura] 1_rclsqwoe: Checking mp4-5321 URL
[Kaltura] 1_rclsqwoe: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 1_rclsqwoe: Downloading 1 format(s): mp4-5321
[info] Writing video metadata as JSON to: Teaser.mp4.fmp4-5321.info.json
[debug] Invoking http downloader on "http://cdnapi.kaltura.com/p/1921661/sp/192166100/playManifest/entryId/1_rclsqwoe/format/url/protocol/http/flavorId/1_1sb4lhnx"
[download] Destination: Teaser.mp4.fmp4-5321.mp4
[download] 100% of   32.90MiB in 00:00:00 at 37.77MiB/s
[generic] Extracting URL: https://learning.sap.com/learning-journeys/applying-the-rise-with-sap-methodology/exploring-the-clean-core-approach_e096a3e4-3a8c-4a62-9e10-49a478f54cc3
[generic] exploring-the-clean-core-approach_e096a3e4-3a8c-4a62-9e10-49a478f54cc3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] exploring-the-clean-core-approach_e096a3e4-3a8c-4a62-9e10-49a478f54cc3: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://learning.sap.com/learning-journeys/applying-the-rise-with-sap-methodology/exploring-the-clean-core-approach_e096a3e4-3a8c-4a62-9e10-49a478f54cc3
Traceback (most recent call last):
  File "~/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "~/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "~/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "~/.local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://learning.sap.com/learning-journeys/applying-the-rise-with-sap-methodology/exploring-the-clean-core-approach_e096a3e4-3a8c-4a62-9e10-49a478f54cc3
```
