### ISSUE TITLE
Error: "Invalid data found when processing input" on Bilibili after postprocessing when --embed-subs is used

### ISSUE THREAD

**Issue by deldesir** [yt-dlp/yt-dlp#10121]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Downloading Bilibili anthology  with the `--embed-subs` flag appeared successful, but during post-processing of each video by ffmpeg, I received the following error message:

```
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error opening input files: Invalid data found when processing input
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--embed-subs', 'https://www.bilibili.com/video/BV1TK421i72D/?spm_id_from=333.337.search-card.all.click', '-vvv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-31-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1TK421i72D/?spm_id_from=333.337.search-card.all.click
[BiliBili] 1TK421i72D: Downloading webpage
[BiliBili] BV1TK421i72D: Extracting videos in anthology
[BiliBili] Downloading playlist BV1TK421i72D - add --no-playlist to download just the video BV1TK421i72D
[download] Downloading playlist: 【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集）
[BiliBili] Playlist 【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集）: Downloading 85 items of 85
[download] Downloading item 1 of 85
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1TK421i72D?p=1
[BiliBili] 1TK421i72D: Downloading webpage
[BiliBili] BV1TK421i72D: Extracting videos in anthology
[BiliBili] 1702017548: Extracting chapters
[BiliBili] BV1TK421i72D: Extracting subtitle info 1477217701
[BiliBili] Format(s) 1080P 高清, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[info] BV1TK421i72D_p1: Downloading subtitles: danmaku
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BV1TK421i72D_p1: Downloading 1 format(s): 30033+30280
[info] Writing video subtitles to: 【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].danmaku.xml
[debug] Invoking http downloader on "https://comment.bilibili.com/1477217701.xml"
[download] Destination: 【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].danmaku.xml
[download] 100% of    1.74KiB in 00:00:01 at 1.19KiB/s
[debug] Invoking http downloader on "https://upos-hz-mirrorakam.akamaized.net/upgcxcode/01/77/1477217701/1477217701-1-30033.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1717681103&gen=playurlv2&os=akam&oi=1107929280&trid=0c19aef39fbb482fa4008fc7fbdabd3du&mid=0&platform=pc&og=cos&upsig=de71088dd7236fda1fced9e0ebf9918e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&hdnts=exp=1717681103~hmac=f3f74ad136c23ae7dd2e0fee636b14658c3c81068815701a5ff65773b552bbd1&bvc=vod&nettype=0&orderid=0,1&buvid=6CC42E15-4FE8-18A6-FDB8-F516BDEF54ED01083infoc&build=0&f=u_0_0&agrr=0&bw=19569&logo=80000000"
[download] Destination: 【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].f30033.mp4
[download] 100% of    5.92MiB in 00:00:06 at 997.54KiB/s
[debug] Invoking http downloader on "https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/01/77/1477217701/1477217701-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1717681103&gen=playurlv2&os=aliovbv&oi=1107929280&trid=0c19aef39fbb482fa4008fc7fbdabd3du&mid=0&platform=pc&og=cos&upsig=90c33b314dafd8199b485ee0960fb639&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,1&buvid=6CC42E15-4FE8-18A6-FDB8-F516BDEF54ED01083infoc&build=0&f=u_0_0&agrr=0&bw=20885&logo=80000000"
[download] Destination: 【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].f30280.m4a
[download] 100% of    6.31MiB in 00:00:06 at 1016.84KiB/s
[Merger] Merging formats into "【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].f30033.mp4' -i 'file:【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].f30280.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].temp.mp4'
Deleting original file 【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].f30280.m4a (pass -k to keep)
Deleting original file 【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].f30033.mp4 (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].mp4' -i 'file:【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].danmaku.xml' -map 0 -dn -ignore_unknown -c copy -c:s mov_text -map -0:s -map 1:0 -metadata:s:s:0 language=dan -movflags +faststart 'file:【英语达人必 看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].temp.mp4'
[debug] ffmpeg version 6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)
  configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf60.16.100
    description     : Packed by Bilibili XCoder v2.0.2
  Duration: 00:05:17.43, start: 0.000000, bitrate: 328 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, bt709), 852x480, 153 kb/s, 30 fps, 30 tbr, 16k tbn (default)
    Metadata:
      handler_name    : Bento4 Video Handler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 165 kb/s (default)
    Metadata:
      handler_name    : Bento4 Sound Handler
      vendor_id       : [0][0][0][0]
[in#1 @ 0x6047cbfd4700] Error opening input: Invalid data found when processing input
Error opening input file file:【英语达人必看】TED-ED动画全系列：全球人文历史知识大揭秘（1-142集） p01 001-酒精的简史【双语字幕】 [BV1TK421i72D_p1].danmaku.xml.
Error opening input files: Invalid data found when processing input

ERROR: Postprocessing: Error opening input files: Invalid data found when processing input
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3537, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3719, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3701, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3679, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 662, in run
    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 329, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 367, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error opening input files: Invalid data found when processing input
```
```

**Comment by deldesir** [comment]
Ah, I see. So, is there any workaround for this issue? Like converting the danmaku/comments into a compatible subtitle format that ffmpeg can handle?

**Comment by bashonly** [comment]
The yt-dlp plugin looks promising. There's also https://github.com/m13253/danmaku2ass if the plugin doesn't work out

One is GPL3.0-licensed and the other MIT-licensed so neither's code be incorporated into yt-dlp.

**Comment by bxqpxd** [comment]
```
[debug] Command-line config: ['-vU', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]', '--merge-output-format', 'mp4', 'https://www.youtube.com/@dreamwithsatya']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_x86_exe)
[debug] Python 3.8.10 (CPython AMD64 32bit) - Windows-10-10.0.22635-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-03-25-git-ecdc94b97f-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
```
issue eg.
```
[download] Downloading item 3 of 145
[youtube] Extracting URL: https://www.youtube.com/watch?v=YoSdWm2ziEU
[youtube] YoSdWm2ziEU: Downloading webpage
[youtube] YoSdWm2ziEU: Downloading ios player API JSON
[debug] Loading youtube-nsig.d60b0ef9 from cache
[debug] [youtube] Decrypted nsig iIAyhyBKAa3MWxaK => 6FcyyLpaBXzHng
[debug] Loading youtube-nsig.d60b0ef9 from cache
[debug] [youtube] Decrypted nsig XiiCWbRm4-QA6u25 => 3ltOnSTbggclkw
[youtube] YoSdWm2ziEU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] YoSdWm2ziEU: Downloading 1 format(s): 642+140
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1721354545/ei/0HSZZq_kPO_Si9oPypSNgAY/ip/95.160.152.253/id/62849d5a6db38845/itag/642/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D393591918%3Bdur%3D134.700%3Bgir%3Dyes%3Bitag%3D337%3Blmt%3D1721163465611811/rqh/1/hls_chunk_host/rr1---sn-8xjug5oxu-f5fl.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/sB/mm/31,29/mn/sn-8xjug5oxu-f5fl,sn-f5f7lnld/ms/au,rdu/mv/m/mvi/1/pl/20/initcwndbps/2002500/vprv/1/playlist_type/DVR/dover/13/txp/5402434/mt/1721332608/fvip/4/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRgIhAPip8Gcf2Wc335Nf7ujUhO4aFJ6cUesnVyJLC6xRK3TwAiEArcGeLiZXtNXsDo_qXmAyBA3vWMIA79oQ0mOH0yeTrmU%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AHlkHjAwRQIhAKwKF5VAR8sRgUv0TSkhMuT5EiF-FCD6I4BXJlSZRUTlAiBE4vwEAKtzYE44H98Se6SkJHozHRBamX4yFtenNdyN4g%3D%3D/playlist/index.m3u8"
[download] STRETCHING IN MY LIVING ROOM [YoSdWm2ziEU].f642.mp4 has already been downloaded
[download] 100% of  375.38MiB
[debug] Invoking http downloader on "https://rr1---sn-8xjug5oxu-f5fl.googlevideo.com/videoplayback?expire=1721354545&ei=0HSZZq_kPO_Si9oPypSNgAY&ip=95.160.152.253&id=o-AFvLL1sQl4ucvbTLty1ltVlHlee1HDmVtQ30A3Tyfg-w&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=sB&mm=31%2C29&mn=sn-8xjug5oxu-f5fl%2Csn-f5f7lnld&ms=au%2Crdu&mv=m&mvi=1&pl=20&initcwndbps=2002500&vprv=1&svpuc=1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=2181892&dur=134.768&lmt=1721158026461764&mt=1721332608&fvip=4&keepalive=yes&c=IOS&txp=5402434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgIOl_TV5uX4kTNJ8qayT59Dm99jRxm8rmyxtZ_uKeZfkCIQDBAvArrbTELBJvB1uLVRp8bnJRtW4rw3hDcFmlR2kSJw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRAIgegKfF9EPLuG0gnoMf3sb0hWN3G0JqiFRa1JF0I0QnAwCIDuNlgpZ905BRjJnLPmHhpcIFZyxKRyFjPS2OXREjC0X"
[download] STRETCHING IN MY LIVING ROOM [YoSdWm2ziEU].f140.m4a has already been downloaded
[download] 100% of    2.08MiB
[Merger] Merging formats into "STRETCHING IN MY LIVING ROOM [YoSdWm2ziEU].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:STRETCHING IN MY LIVING ROOM [YoSdWm2ziEU].f642.mp4" -i "file:STRETCHING IN MY LIVING ROOM [YoSdWm2ziEU].f140.m4a" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:STRETCHING IN MY LIVING ROOM [YoSdWm2ziEU].temp.mp4"
[debug] ffmpeg version 2024-03-25-git-ecdc94b97f-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59.  6.100 / 59.  6.100
  libavcodec     61.  2.100 / 61.  2.100
  libavformat    61.  0.100 / 61.  0.100
  libavdevice    61.  0.100 / 61.  0.100
  libavfilter    10.  0.100 / 10.  0.100
  libswscale      8.  0.100 /  8.  0.100
  libswresample   5.  0.100 /  5.  0.100
  libpostproc    58.  0.100 / 58.  0.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001b44c2b1380] error reading header
[in#0 @ 000001b44c2b0f80] Error opening input: Invalid data found when processing input
Error opening input file file:STRETCHING IN MY LIVING ROOM [YoSdWm2ziEU].f642.mp4.
Error opening input files: Invalid data found when processing input

ERROR: Postprocessing: Error opening input files: Invalid data found when processing input
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3561, in process_info
  File "yt_dlp\YoutubeDL.py", line 3743, in post_process
  File "yt_dlp\YoutubeDL.py", line 3725, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3703, in run_pp
  File "yt_dlp\postprocessor\common.py", line 23, in run
  File "yt_dlp\postprocessor\common.py", line 128, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 840, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 330, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 368, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error opening input files: Invalid data found when processing input
```
