### ISSUE TITLE
southparkstudios.com is broken

### ISSUE THREAD

**Issue by nrlquaker** [yt-dlp/yt-dlp#10168]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Croatia

### Provide a description that is worded well enough to be understood

Downloading any episode from `www.southparkstudios.com` ends with error `Sorry, this video is not found or no longer available due to date or rights restrictions.` But it can be watch on the site.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.southparkstudios.com/episodes/egyait/south-park-raising-the-bar-season-16-ep-9
[debug] Command-line config: ['-vU', 'https://www.southparkstudios.com/episodes/egyait/south-park-raising-the-bar-season-16-ep-9']
[debug] User config "/Users/username/.config/yt-dlp/config": ['-o', '~/Downloads/%(title)s - %(id)s.%(ext)s', '--extractor-args', 'youtube:player_client=web']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6]
[debug] Python 3.12.3 (CPython arm64 64bit) - macOS-14.4.1-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.2, sqlite3-3.46.0, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[southpark.cc.com] Extracting URL: https://www.southparkstudios.com/episodes/egyait/south-park-raising-the-bar-season-16-ep-9
[southpark.cc.com] south-park-raising-the-bar-season-16-ep-9: Downloading webpage
[southpark.cc.com] c541c989-b10c-4ef8-9dbc-66000eff7bcd: Downloading info
[southpark.cc.com] 4fc3f0ad-97e1-4714-a2a4-504cca017075: Extracting information
[southpark.cc.com] 4fc3f0ad-97e1-4714-a2a4-504cca017075: Downloading video urls
ERROR: [southpark.cc.com] egyait/south-park-raising-the-bar-season-16-ep-9: southpark.cc.com returned error: not_found -
      Sorry, this video is not found or no longer available due to date or rights restrictions.

  File "/opt/homebrew/Cellar/yt-dlp/HEAD-add96eb/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 733, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/HEAD-add96eb/libexec/lib/python3.12/site-packages/yt_dlp/extractor/mtv.py", line 322, in _real_extract
    return self._get_videos_info(mgid, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/HEAD-add96eb/libexec/lib/python3.12/site-packages/yt_dlp/extractor/mtv.py", line 226, in _get_videos_info
    return self._get_videos_info_from_url(info_url, video_id, use_hls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/HEAD-add96eb/libexec/lib/python3.12/site-packages/yt_dlp/extractor/mtv.py", line 238, in _get_videos_info_from_url
    info = self._get_video_info(item, use_hls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/HEAD-add96eb/libexec/lib/python3.12/site-packages/yt_dlp/extractor/mtv.py", line 149, in _get_video_info
    raise ExtractorError(message, expected=True)
```

**Comment by bashonly** [comment]
Related: #2621 (and all of the other MTV services issues)

**Comment by nrlquaker** [comment]
its a new error now:
```
yt-dlp -vU https://www.southparkstudios.com/episodes/vb9a1j/south-park-the-magic-bush-season-18-ep-5
[debug] Command-line config: ['-vU', 'https://www.southparkstudios.com/episodes/vb9a1j/south-park-the-magic-bush-season-18-ep-5']
[debug] User config "/Users/username/.config/yt-dlp/config": ['-o', '~/Downloads/%(title)s - %(id)s.%(ext)s', '--extractor-args', 'youtube:player_client=web']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.06.30 from yt-dlp/yt-dlp [b01878449] (pip)
[debug] Python 3.13.5 (CPython arm64 64bit) - macOS-15.5-arm64-arm-64bit-Mach-O (OpenSSL 3.5.1 1 Jul 2025)
[debug] exe versions: ffmpeg 7.1.1 (setts), ffprobe 7.1.1
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.1.0, certifi-2025.06.15, mutagen-1.47.0, requests-2.32.4, sqlite3-3.50.2, urllib3-2.5.0, websockets-15.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: none
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.06.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.06.30 from yt-dlp/yt-dlp)
[southpark.cc.com] Extracting URL: https://www.southparkstudios.com/episodes/vb9a1j/south-park-the-magic-bush-season-18-ep-5
[southpark.cc.com] south-park-the-magic-bush-season-18-ep-5: Downloading webpage
[southpark.cc.com] b7db1aa6-a2cc-4963-841d-8dc042ee7fd0: Downloading info
ERROR: [southpark.cc.com] vb9a1j/south-park-the-magic-bush-season-18-ep-5: Unable to download XML: (<urllib3.connection.HTTPSConnection object at 0x1060a4410>, 'Connection to origin.partners.paramount.tech timed out. (connect timeout=20.0)') (caused by TransportError("(<urllib3.connection.HTTPSConnection object at 0x1060a4410>, 'Connection to origin.partners.paramount.tech timed out. (connect timeout=20.0)')"))
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 752, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/extractor/mtv.py", line 322, in _real_extract
    return self._get_videos_info(mgid, url=url)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/extractor/mtv.py", line 226, in _get_videos_info
    return self._get_videos_info_from_url(info_url, video_id, use_hls)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/extractor/mtv.py", line 229, in _get_videos_info_from_url
    idoc = self._download_xml(
        url, video_id,
        'Downloading info', transform_source=fix_xml_ampersands)
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1149, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1107, in download_handle
    res = self._download_webpage_handle(
        url_or_request, video_id, note=note, errnote=errnote, fatal=fatal, encoding=encoding,
        data=data, headers=headers, query=query, expected_status=expected_status,
        impersonate=impersonate, require_impersonation=require_impersonation)
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 972, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
                                 headers=headers, query=query, expected_status=expected_status,
                                 impersonate=impersonate, require_impersonation=require_impersonation)
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 921, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/networking/_requests.py", line 331, in _send
    requests_res = session.request(
        method=request.method,
    ...<6 lines>...
        stream=True,
    )
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
                                ^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/requests/sessions.py", line 265, in resolve_redirects
    resp = self.send(
        req,
    ...<6 lines>...
        **adapter_kwargs,
    )
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/util/retry.py", line 449, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
                       ~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
    ...<2 lines>...
    ) from e
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x1060a4410>, 'Connection to origin.partners.paramount.tech timed out. (connect timeout=20.0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 908, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 4197, in urlopen
    return self._request_director.send(req)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/networking/_helper.py", line 194, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/networking/common.py", line 359, in send
    return self._send(request)
           ~~~~~~~~~~^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.6.30/libexec/lib/python3.13/site-packages/yt_dlp/networking/_requests.py", line 359, in _send
    raise TransportError(cause=e) from e
yt_dlp.networking.exceptions.TransportError: (<urllib3.connection.HTTPSConnection object at 0x1060a4410>, 'Connection to origin.partners.paramount.tech timed out. (connect timeout=20.0)')
```
