### ISSUE TITLE
ERROR: Invalid IPv6 URL When Accessing banned.video

### ISSUE THREAD

**Issue by nullagit** [yt-dlp/yt-dlp#10184]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

**What the problem is:**
When attempting to download various videos from banned.video, I received an error: ERROR: Invalid ipv6 URL. Most of the videos I tried to download worked, but a handful of them do not. I am not logged into the site.

**How it could be fixed**
I'm not sure. I run gentoo and have the -ipv6 USE flag defined globally. There are no ipv6 addresses on this machine and the upstream network/LAN does not support ipv6. The configured kernel doesn't even have ipv6 support. I'm not sure why or how ipv6 is being used at all. I think maybe yt-dlp should force ipv4 when ipv6 isn't an option.

**How your proposed solution would look like**
Force yt-dlp to continue using the ipv4 address or provide a USE flag that disables IPv6 all together (-ipv6)?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
sysop@localhost ~ $ yt-dlp -vU https://banned.video/watch?id=5d066d71a90fbc00123c1d34
[debug] Command-line config: ['-vU', 'https://banned.video/watch?id=5d066d71a90fbc00123c1d34']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6]
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.6.30-gentoo-x86_64-x86_64-AMD_Ryzen_Threadripper_7970X_32-Cores-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.20.0, requests-2.32.1, secretstorage-3.3.3, sqlite3-3.45.3, urllib3-2.2.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[BannedVideo] Extracting URL: https://banned.video/watch?id=5d066d71a90fbc00123c1d34
[BannedVideo] 5d066d71a90fbc00123c1d34: Downloading video metadata
[BannedVideo] 5d066d71a90fbc00123c1d34: Downloading m3u8 information
ERROR: Invalid IPv6 URL
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/bannedvideo.py", line 135, in _real_extract
    formats.extend(self._extract_m3u8_formats(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 2014, in _extract_m3u8_formats
    fmts, subs = self._extract_m3u8_formats_and_subtitles(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 2048, in _extract_m3u8_formats_and_subtitles
    return self._parse_m3u8_formats_and_subtitles(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 2197, in _parse_m3u8_formats_and_subtitles
    manifest_url = format_url(line.strip())
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 2063, in format_url
    return url if re.match(r'^https?://', url) else urllib.parse.urljoin(m3u8_url, url)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/parse.py", line 551, in urljoin
    urlparse(url, bscheme, allow_fragments)
  File "/usr/lib/python3.12/urllib/parse.py", line 395, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/parse.py", line 497, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

sysop@localhost ~ $
```

**Comment by october262** [comment]
right click on the word download and select "copy link address"
and retry downloading the video yt-dlp "https://download.assets.video/videos/f76d6efa-4a87-4fd8-8da2-5ff359a98703.mp4?direct=true" the video will now download.

**Comment by nullagit** [comment]
Thanks for sharing, you're right, however that's a direct link to the mp4 file itself, I could just use wget instead of yt-dlp in that instance. The reason I'm using yt-dlp is to download the video based off the video page URL instead of drilling down into each individual video page and obtaining the direct link to the mp4. Using yt-dlp to download based off the video page URL makes it easier to download entire categories. Otherwise I'd have to obtain the mp4 link for each individual video myself making yt-dlp unnecessary, since I could simply use wget after obtaining a list of all the mp4 files I wanted.

**Comment by barsnick** [comment]
> or provide a USE flag that disables IPv6 all together (-ipv6)?

How about:
```
--force-ipv4
```

Too bad we don't see which URL it is actually trying to parse.

**But all that said:**
I can reproduce this on an IPv6-enabled machine. Perhaps this is due to the fact that yp-dlp is trying to extract M3U8 formats from an actual MP4 file. I'm just guessing from what I see with `--write-pages` (also with `--force-ipv4`):
```
[BannedVideo] Extracting URL: https://banned.video/watch?id=5d066d71a90fbc00123c1d34                                                                                                                                                          
[BannedVideo] 5d066d71a90fbc00123c1d34: Downloading video metadata                                                                                                                                                                            
[BannedVideo] Saving request to 5d066d71a90fbc00123c1d34_7c9b57034d37641ffaf59e0436ea904e_https_-_api.infowarsmedia.com_graphql.dump                       
[BannedVideo] 5d066d71a90fbc00123c1d34: Downloading m3u8 information
[BannedVideo] Saving request to 5d066d71a90fbc00123c1d34_https_-_download.assets.video_videos_f76d6efa-4a87-4fd8-8da2-5ff359a98703.mp4.dump
ERROR: Invalid IPv6 URL
```
That last request is an MP4 file, not am M3U8.

**Comment by gamer191** [comment]
> Perhaps this is due to the fact that yt-dlp is trying to extract M3U8 formats from an actual MP4 file

Yeah, this is the issue. "ERROR: Invalid IPv6 URL" is very misleading and seems to indicate a core bug (running `_extract_m3u8_formats` with any mp4 url results in that error)

**Comment by HalvorRaknes** [comment]
Since the issue I opened yesterday, https://github.com/yt-dlp/yt-dlp/issues/13558, has been closed as a duplicate of the present one I should hasten to mention that I was aware of this thread which is 1 year old. I posted as a new issue because downloads from banned.video have been working fine for me up until a couple of days ago.

Also, I just tried again now including the `--force-ipv6` option, log below:

```
$ yt-dlp -vU --force-ipv6 -o "%(title).80s.%(ext)s" https://www.banned.video/watch?id=685c7aef8522d699333a5136
[debug] Command-line config: ['-vU', '--force-ipv6', '-o', '%(title).80s.%(ext)s', 'https://www.banned.video/watch?id=685c7aef8522d699333a5136']
[debug] User config "/home/halvor/.config/yt-dlp/config": ['-o', '(%(upload_date)s) %(title)s (%(uploader)s - %(extractor)s - %(id)s).%(ext)s', '-S', 'res:360']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.06.25 from yt-dlp/yt-dlp [1838a1ce5] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-142-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.1.0, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: none
[debug] Loaded 1860 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (<urllib3.connection.HTTPSConnection object at 0x7fafe5bb8790>: Failed to resolve 'api.github.com' ([Errno -9] Address family for hostname not supported)); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[BannedVideo] Extracting URL: https://www.banned.video/watch?id=685c7aef8522d699333a5136
[BannedVideo] 685c7aef8522d699333a5136: Downloading video metadata
ERROR: [BannedVideo] 685c7aef8522d699333a5136: Unable to download JSON metadata: <urllib3.connection.HTTPSConnection object at 0x7fafe5bbabf0>: Failed to establish a new connection: [Errno 101] Network is unreachable (caused by TransportError('<urllib3.connection.HTTPSConnection object at 0x7fafe5bbabf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 749, in extract
    ie_result = self._real_extract(url)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/extractor/bannedvideo.py", line 123, in _real_extract
    video_json = self._call_api(video_id, video_id, 'GetVideoAndComments', 'Downloading video metadata')
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/extractor/bannedvideo.py", line 88, in _call_api
    return self._download_json(
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1146, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1104, in download_handle
    res = self._download_webpage_handle(
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 969, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 918, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/networking/_requests.py", line 331, in _send
    requests_res = session.request(
  File "/home/halvor/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/halvor/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/halvor/.local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 445, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/halvor/.local/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fafe5bbabf0>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 905, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 4197, in urlopen
    return self._request_director.send(req)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/networking/_helper.py", line 194, in wrapper
    return func(self, *args, **kwargs)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 359, in send
    return self._send(request)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/networking/_requests.py", line 359, in _send
    raise TransportError(cause=e) from e
yt_dlp.networking.exceptions.TransportError: <urllib3.connection.HTTPSConnection object at 0x7fafe5bbabf0>: Failed to establish a new connection: [Errno 101] Network is unreachable
```

**Comment by bashonly** [comment]
It doesn't have anything to do with ipv6. That's a red herring. As gamer191 said above, yt-dlp is trying to parse an mp4 as an m3u8 and running into unexpected errors.

**Comment by HalvorRaknes** [comment]
Perhaps someone could change the title of the thread to reflect this?

(And this website tagged as NSFW'? WTF? )
