### ISSUE TITLE
[crunchyroll] This video is DRM protected

### ISSUE THREAD

**Issue by smile-2023** [yt-dlp/yt-dlp#10207]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

Since 2024.06.18 16:55 i get the message

ERROR: [crunchyroll] <_Partnumber_>: This video is DRM protected

I tried it with other links, but i get only this message.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--user-agent', 'Crunchyroll/1.8.0 Nintendo Switch/12.3.12.0 UE4/4.27', '--username', 'PRIVATE', '--password', 'PRIVATE', '--sub-langs', 'de-DE', '--write-description', '--write-thumbnail', '--write-subs', '--progress', '--extractor-args', 'crunchyrollbeta:hardsub=de-DE', '-vU', 'https://www.crunchyroll.com/de/watch/GK9U3EV5Q/castle-of-sand']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-21-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.5-0 (setts), ffprobe 5.1.5-0, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.46.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[debug] Loading crunchyroll.animal@foobaa.de from cache
[crunchyroll] Extracting URL: https://www.crunchyroll.com/de/watch/GK9U3EV5Q/castle-of-sand
[crunchyroll] Requesting token
[crunchyroll] GK9U3EV5Q: Downloading object info JSON (cms)
[crunchyroll] GK9U3EV5Q: Downloading stream info
[crunchyroll] Available hardsub languages: en-US, de-DE, es-419, es-ES, fr-FR, it-IT, pt-BR, ru-RU, ar-SA
[crunchyroll] To extract formats of a hardsub language, use "--extractor-args crunchyrollbeta:hardsub=<language_code or all>". See https://github.com/yt-dlp/yt-dlp#crunchyrollbeta-crunchyroll for more info
[crunchyroll] GK9U3EV5Q: Downloading hardsub-de-DE MPD manifest
[crunchyroll] GK9U3EV5Q: Invalidating stream token
[crunchyroll] GK9U3EV5Q: Downloading chapter info
[info] GK9U3EV5Q: Downloading subtitles: de-DE
ERROR: [crunchyroll] GK9U3EV5Q: This video is DRM protected
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2825, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1104, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [crunchyroll] GK9U3EV5Q: This video is DRM protected
```

**Comment by smile-2023** [comment]
I tried it with crunch-cl 3.6.6 and it works fine. I can download audio and video:

:: ✔ Logging in                                                                                                                     
:: ✔ Parsed url 1                                                                                                                   
:: ✔ Loaded series information for url 1                                                                                            
:: Unnamed Memory Season 1 (Unnamed Memory)
:: 	1. Ein Schloss aus Sand » S01E11
:: Downloading Ein Schloss aus Sand to 'Unnamed Memory 11 – Ein Schloss aus Sand.mp4'
:: 	Episode: S01E11
:: 	Audio: ja-JP
:: 	Subtitles: de-DE
:: 	Resolution: 1920x1080
:: 	FPS: 23.97
:: Downloading ja-JP audio  22.68 MiB   8.50 MiB/s [#####] 100%
:: Downloading video #1      1.32 GiB  13.42 MiB/s [#####] 100%:: Downloading subtitles    de-DE                                                                                                   :: Generating output file   [####] 100%

It seems like it's not really DRM.

**Comment by bashonly** [comment]
https://github.com/crunchy-labs/crunchy-cli/issues/438

**Comment by DanieleB727** [comment]
is this the end for cr in yt-dlp or is there a chance it will get fixed to work with the new drm?

**Comment by Sipherdrakon** [comment]
> is this the end for cr in yt-dlp or is there a chance it will get fixed to work with the new drm?

so yt-dlp doesn't work with DRM'd content, and never has. CR has a non-drm stream which is what yt-dlp picks up and downloads. At the moment CR has 3 streams, 2 that are DRM and one that is not. Seems yt-dlp is having trouble grabbing that stream.

**Comment by Tama47** [comment]
This could be the end of the Crunchyroll extractor for yt-dlp, unless someone is able to find a new Non-DRM protected endpoints other than the Switch. I really hope it will not result in the removal of the extractor, as downloading subtitles and thumbnails still works with `--ignore-no-formats-error` thanks to bashonly's fix in https://github.com/yt-dlp/yt-dlp/pull/10005.

**Comment by Trit34** [comment]
> This could be the end of the Crunchyroll extractor for yt-dlp, unless someone is able to find a new Non-DRM protected endpoints other than the Switch. I really hope it will not result in the removal of the extractor, as downloading subtitles and thumbnails still works with `--ignore-no-formats-error` thanks to bashonly's fix in #10005.

Circumventing DRM is not in the goals of yt-dlp, so it could be necessary to go with another project. The problem is: there is no other projects (that is not built upon yt-dlp, at least)… :/

**Comment by TaciturnShadow** [comment]
> Circumventing DRM is not in the goals of yt-dlp, so it could be necessary to go with another project. The problem is: there is no other projects (that is not built upon yt-dlp, at least)… :/
https://github.com/stratuma/Crunchyroll-Downloader-v4.0

**Comment by federicorosso1993** [comment]
Personally speaking, I deactivated the crunchyroll subscription renewal last time (although the subscription will remain active until November so I'm still using it until that date). When they asked why I decided to cancel my subscription I actually decided to say the truth that I did not like their DRM policy, probably they don't care but I wanted to be clear about it, I pay for stuff that I can backup.
I don't like DRMs at all, if I can't backup my favorite series (which I had no interest in sharing online anyway and which it seems to me can still be found with all these DRMs) I prefer not to be a subscriber and dedicate myself to other hobbies ( in particular video games on Gog where they are DRM-free and manga/books on Amazon and Kobo (where DRM is easy to be eliminated for now).
A few years ago I stopped buying movies because it had become too complex to remove the DRM from films purchased from iTunes and similar so for me it's not the first time I decided to quit paying for stuff that use a drm that is too strong (even if it seems clear that those who want to remove it at all costs always find a way (those who will share it online)... but I get bored if the method is too complex, for example I took a look at crunchyroll downloader 4.0... and make an android virtual machine just to get the L3 widevine keys (that maybe in the future will only work for low quality videos like on netflix) is not something that I want to do... too much trouble, wasted space on my pc, just for something that I should be able to do by default... crunchyroll don't even sell anime in digital download drm-free so I cannot even decide to pay for that instead of subscriptions).
One thing I've learned over the years is that in these cases it's better not to pirate at all... otherwise companies will take it as an excuse for decreasing revenues and will increase DRMs instead of doing the opposite. For my part, I prefer to give a clear signal "your product is not fundamental, if you use DRM that is too invasive I prefer to ignore the product".

In the meantime, I still want to thank yt-dlp team who for many years have always provided constant updates to this splendid tool. I built a small interface for my personal convenience but the "dirty work" has always been done by yt-dlp (except for a period when crunchyroll was in beta, there I had created a small tool for beta crunchyroll which however I was unable to keep updated).

I am still happy to have the interface to be able to continue using yt-dlp on YouTube and other similar sites where it is still the best tool.
I know that, if there is any not drm stream still on crunchyroll you will find it.
If there is not I suggest to keep the subtitles download part like Tama47 suggested... Even if it's easy to find it by using the developer tools I think using yt-dlp is still more convenient since it will rename it the correct way.

I know that messages like this are slightly offtopic but I hope an exception is made given the particular case. If you want you can delete this message (or ask me to do so).

**Comment by Haldrie** [comment]
> > This could be the end of the Crunchyroll extractor for yt-dlp, unless someone is able to find a new Non-DRM protected endpoints other than the Switch. I really hope it will not result in the removal of the extractor, as downloading subtitles and thumbnails still works with `--ignore-no-formats-error` thanks to bashonly's fix in #10005.
> 
> Circumventing DRM is not in the goals of yt-dlp, so it could be necessary to go with another project. The problem is: there is no other projects (that is not built upon yt-dlp, at least)… :/

I don't think anyone is asking for that (as much as I'm sure many of us secretly want that) but if the metadata and subtitles are still not drm protected it would be nice to at least grab those while we can.

**Comment by Tama47** [comment]
@federicorosso1993 

> I am still happy to have the interface to be able to continue using yt-dlp on YouTube and other similar sites where it is still the best tool.

You can still download anime on YouTube for free from channels like Muse Asia and AniOne Asia. Although the former offers low-quality hardsubbed 720p, the latter does offer 1080p softsubs. BiliBili also works, even their 4K upscaled videos if you prefer. An even better option is to download from ABEMA TV, which offers high-quality DRM-free 1080p downloads. While not as high quality as Crunchyroll (1.5 GB vs ~750 MB), it is the next best thing in terms of quality. Plus, the subscription price is cheaper due to the conversion rate. But you will need a VPN, if you don’t live in Japan.

> If there is not I suggest to keep the subtitles download part like Tama47 suggested... Even if it's easy to find it by using the developer tools I think using yt-dlp is still more convenient since it will rename it the correct way.

I agree. Even though you can easily find the thumbnails and subtitles [through the developer tools](https://www.reddit.com/r/Crunchyroll/s/HxfuEkdNaV), yt-dlp provides a much more convenient interface. With that said… you can now easily pair CR subtitles with other releases like ABEMA and so on.

**Comment by bashonly** [comment]
### README:

This is not the place to air your grievances with DRM or Crunchyroll, and this is **definitely NOT** the place to discuss DRM circumvention or link to DRM circumvention resources. Anyone who does the latter will be **blocked from this repo without further warning.**

The only reason this issue isn't being locked is in case anyone has any info/leads on the availability of non-DRM formats.

**Comment by DexyThePuppy** [comment]
instead of circumventing DRM... cant we just use the browsers (or a device_client_id_blob/device_private_key file which can be converted to a single .wvd file) Videwine license to automatically decrypt it?

**Comment by bashonly** [comment]
No
