### ISSUE TITLE
[crunchyroll] is it possible to only download the audio stream?

### ISSUE THREAD

**Issue by 4nyNoob** [yt-dlp/yt-dlp#10224]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

CR implemented DRM on the current method being used on the extractor, and I'm only using it to get PT-BR dubs for some shows
if the audio stream isn't DRM protected that would be a viable solution/workaround to me 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'ba', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.crunchyroll.com/watch/GYW4WW126/have-you-heard-that-rumor-about-the-magical-girls']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.20.232815 from yt-dlp/yt-dlp-nightly-builds [7aa322c02] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.9.4-200.fc40.x86_64-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (fdk,setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.7.0b4 (unsupported), mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.20.232815 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.20.232815 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: ba
ERROR: [generic] 'ba' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:ba" ) to search YouTube
  File "/home/any/.local/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/any/.local/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2357, in _real_extract
    raise ExtractorError(

[debug] Loading crunchyroll.<<<PRIVATE>>> from cache
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GYW4WW126/have-you-heard-that-rumor-about-the-magical-girls
[crunchyroll] Requesting token
WARNING: [crunchyroll] The extractor is attempting impersonation, but no impersonate target is available; if you encounter errors, then see  https://github.com/yt-dlp/yt-dlp#impersonation  for information on installing the required dependencies
[crunchyroll] GYW4WW126: Downloading object info JSON (cms)
[crunchyroll] GYW4WW126: Downloading stream info
[crunchyroll] Available hardsub languages: en-US, es-419, es-ES, fr-FR, it-IT, pt-BR
[crunchyroll] To extract formats of a hardsub language, use "--extractor-args crunchyrollbeta:hardsub=<language_code or all>". See https://github.com/yt-dlp/yt-dlp#crunchyrollbeta-crunchyroll for more info
[crunchyroll] GYW4WW126: Downloading MPD manifest
[crunchyroll] GYW4WW126: Invalidating stream token
[crunchyroll] GYW4WW126: Downloading chapter info
ERROR: [crunchyroll] GYW4WW126: This video is DRM protected
Traceback (most recent call last):
  File "/home/any/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/any/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/any/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1820, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/any/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2825, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/any/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1103, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [crunchyroll] GYW4WW126: This video is DRM protected
```

**Comment by bashonly** [comment]
Currently the audio streams that are being extracted are DRM protected. Closing, since any progress will be tracked in #10207

**Comment by Tama47** [comment]
Is the audio also DRM protected in the new update?

**Comment by bashonly** [comment]
yes
