### ISSUE TITLE
[EmbedThumbnail] unable to embed using mutagen; None

### ISSUE THREAD

**Issue by infoshare3468** [yt-dlp/yt-dlp#10245]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Possibly a bug in handling/recognizing  ..\  in output filenames. It appears to automatically prepend a \ on to all filenames regardless if the output filename specified includes  \  

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\youtube-DL\APP>yt-dlp.exe -vU --restrict-filenames -o "..\%(title).100s (%(id)s).%(ext)s" --merge-output-format mp4 --postprocessor-args "-strict experimental" -f "bestvideo+bestaudio/best" --embed-thumbnail --add-metadata --cookies-from-browser firefox --cookies tiktok_cookies.txt "https://www.tiktok.com/t/ZTNNef8GN/"
[debug] Command-line config: ['-vU', '--restrict-filenames', '-o', '..\\%(title).100s (%(id)s).%(ext)s', '--merge-output-format', 'mp4', '--postprocessor-args', '-strict experimental', '-f', 'bestvideo+bestaudio/best', '--embed-thumbnail', '--add-metadata', '--cookies-from-browser', 'firefox', '--cookies', 'tiktok_cookies.txt', 'https://www.tiktok.com/t/ZTNNef8GN/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.22.232706 from yt-dlp/yt-dlp-nightly-builds [a8520244b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg git-2020-08-28-ccc7120, ffprobe git-2020-08-28-ccc7120
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Brian\AppData\Roaming\Mozilla\Firefox\Profiles\ebmleyw3.default\cookies.sqlite"
Extracted 2606 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
WARNING: Post-Processor arguments given without specifying name. The arguments will be given to all post-processors
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.22.232706 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.22.232706 from yt-dlp/yt-dlp-nightly-builds)
[vm.tiktok] Extracting URL: https://www.tiktok.com/t/ZTNNef8GN/
[vm.tiktok] ZTNNef8GN: Downloading webpage
[TikTok] Extracting URL: https://www.tiktok.com/@ryanjosephnetwork1/video/7378788729533549866?_t=8nQzVaRgfMM&_r=1
[TikTok] 7378788729533549866: Downloading webpage
[debug] [TikTok] Found universal data for rehydration
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 7378788729533549866: Downloading 1 format(s): bytevc1_1080p_352374-1
Deleting existing file ..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).jpg
[info] Downloading video thumbnail 2 ...
[info] Writing video thumbnail 2 to: ..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).jpg
[debug] Invoking http downloader on "https://v19-webapp-prime.us.tiktok.com/video/tos/useast5/tos-useast5-pve-0068-tx/o0BGy8QSIiZUixMB1uzCmB8AME9bprNfwAnihI/?a=1988&bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C&cv=1&br=688&bt=344&cs=2&ds=4&ft=4KJMyMzm8Zmo0GnD5-4jVBOZdpWrKsd.&mime_type=video_mp4&qs=15&rc=aTY2NDU5NGkzaDo6OmllNEBpM3NscHY5cjZlczMzZzczNEA1M2JjNi0zXmMxYTRfYV8vYSM2am5nMmRjZmdgLS1kMS9zcw%3D%3D&btag=e00098000&expire=1719173845&l=202406231412356A31BFEAC2BC1D36E843&ply_type=2&policy=2&signature=e0a873b476e6b54e9a3dbe74d50be70a&tk=tt_chain_token"
[download] ..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).mp4 has already been downloaded
[download] 100% of   13.54MiB
[Metadata] Adding metadata to "..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).mp4" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=original sound" -metadata "date=20240610" -metadata "description=#usa #cnn #biden #trump #trend #foxnews #trump #trend " -metadata "synopsis=#usa #cnn #biden #trump #trend #foxnews #trump #trend " -metadata "purl=https://www.tiktok.com/@ryanjosephnetwork1/video/7378788729533549866?_t=8nQzVaRgfMM&_r=1" -metadata "comment=https://www.tiktok.com/@ryanjosephnetwork1/video/7378788729533549866?_t=8nQzVaRgfMM&_r=1" -metadata "artist=Ryan Joseph" -movflags +faststart -strict experimental "file:..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).temp.mp4"
[EmbedThumbnail] mutagen: Adding thumbnail to "..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).mp4"
WARNING: unable to embed using mutagen; None
[EmbedThumbnail] mutagen was not found. Falling back to AtomicParsley
[EmbedThumbnail] atomicparsley: Adding thumbnail to "..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).mp4"
[debug] AtomicParsley command line: AtomicParsley "..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).mp4" --artwork "..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).jpg" -o "..\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).temp.mp4" -strict experimental
WARNING: Unable to embed thumbnails using AtomicParsley;
ERROR: [WinError 2] The system cannot find the file specified: '..\\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).temp.mp4' -> '..\\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).mp4'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1605, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1820, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2993, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3537, in process_info
  File "yt_dlp\YoutubeDL.py", line 3719, in post_process
  File "yt_dlp\YoutubeDL.py", line 3701, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3679, in run_pp
  File "yt_dlp\postprocessor\common.py", line 23, in run
  File "yt_dlp\postprocessor\common.py", line 128, in wrapper
  File "yt_dlp\postprocessor\embedthumbnail.py", line 218, in run
FileNotFoundError: [WinError 2] The system cannot find the file specified: '..\\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).temp.mp4' -> '..\\usa_cnn_biden_trump_trend_foxnews_trump_trend (7378788729533549866).mp4'
```

**Comment by Grub4K** [comment]
The `\\` is just the python string representation and expected. Since python allows for escapes like `\n`, an actual `\` gets represented as `\\`, which explains why it is always added. It has nothing to do with the error you are experiencing. See this:
```py
>>> print('..\\%(title).100s (%(id)s).%(ext)s')
..\%(title).100s (%(id)s).%(ext)s
```
---

The failed embedding was a chain of errors that resulted in all embedding attempts failing:

- First `mutagen` embedding is tried. To do this, `compat.imghdr` is invoked to determine the file type. Since that module is not up to date it incorrectly judges the jpeg thumbnail, returning `None` and causing a `KeyError(None)`. `mutagen` is skipped and the cryptic error `WARNING: unable to embed using mutagen; None` output.
- `AtomicParsley` is tried next, however since you passed `--postprocessor-args "-strict experimental"` that command fails as the `-strict experimental` gets passed to all postprocessors, and `AtomicParsley` does not understand that flag
  - Side note: You should use `--postprocessor-args "ffmpeg:-strict experimental"` to only pass it to `ffmpeg` or, preferably, upgrade your `ffmpeg` so the flag is not needed at all
- Now another error comes into play, where after `AtomicParsley` fails with an errorlevel, `success` is not set to `False`, so embedding with `ffmpeg` is not tried next
- The non-existent temporary file will now be moved to overwrite the regular file

The last part ultimately resulted in the error you saw:
```py
>>> os.replace(R"..\file.temp.mp4", R"..\file.mp4")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [WinError 2] The system cannot find the file specified: '..\\file.temp.mp4' -> '..\\file.mp4'
```
---
A PR is about to be opened for all these to be fixed. Make sure to update `ffmpeg` and no longer pass `--postprocessor-args`
