### ISSUE TITLE
[ie/jiocinema] Extractor filters out too many formats

### ISSUE THREAD

**Issue by ETapk** [yt-dlp/yt-dlp#10240]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I found a new issue on jiocinema at another url.
Url:  https://www.jiocinema.com/tv-shows/maa-durga/1/ma-durga-16th-apr-2016/3152389

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Microsoft Windows [Version 10.0.22631.3737]
(c) Microsoft Corporation. All rights reserved.

C:\Users\moder\Downloads\JC>yt-dlp -vU https://www.jiocinema.com/tv-shows/maa-durga/1/ma-durga-16th-apr-2016/3152389
[debug] Command-line config: ['-vU', 'https://www.jiocinema.com/tv-shows/maa-durga/1/ma-durga-16th-apr-2016/3152389']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-02-01-git-94422871fc-essentials_build-www.gyan.dev (setts), ffprobe 2024-02-01-git-94422871fc-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2024.05.27/SHA2-256SUMS
Current version: stable@2023.12.30 from yt-dlp/yt-dlp
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
Current Build Hash: 160b304bef9fa134d523b46cc3647a727e40584338379eb4e0d1047de945fad9
Updating to stable@2024.05.27 from yt-dlp/yt-dlp ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp/releases/download/2024.05.27/yt-dlp.exe
Updated yt-dlp to stable@2024.05.27 from yt-dlp/yt-dlp
[debug] Restarting: yt-dlp -vU "https://www.jiocinema.com/tv-shows/maa-durga/1/ma-durga-16th-apr-2016/3152389"
[debug] Command-line config: ['-vU', 'https://www.jiocinema.com/tv-shows/maa-durga/1/ma-durga-16th-apr-2016/3152389']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-02-01-git-94422871fc-essentials_build-www.gyan.dev (setts), ffprobe 2024-02-01-git-94422871fc-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[jiocinema] Extracting URL: https://www.jiocinema.com/tv-shows/maa-durga/1/ma-durga-16th-apr-2016/3152389
[jiocinema] Downloading guest token
[jiocinema] 3152389: Downloading playback JSON
[jiocinema] 3152389: Downloading JSON metadata
[jiocinema] 3152389: Downloading m3u8 information
ERROR: [jiocinema] 3152389: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1762, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1821, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2825, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1104, in raise_no_formats
yt_dlp.utils.ExtractorError: [jiocinema] 3152389: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by seproDev** [comment]
Okay, the issue here is that the jiocinema extractor filters out too many extractors. https://github.com/yt-dlp/yt-dlp/issues/10144#issuecomment-2156706489
We will use this issue to keep track of that issue specifically.

However, even with that fixed, this video wouldn't download. The DASH stream the browser uses is DRM protected. The HLS stream is corrupted, where the variant URLs return with a 404. So this is another instance of #10225. Sadly, there is nothing yt-dlp can do about the site serving corrupt data.
