### ISSUE TITLE
QloveR.jp

### ISSUE THREAD

**Issue by panam510** [yt-dlp/yt-dlp#10260]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Japan

### Example URLs

- Video: https://qlover.jp/midnightdoublepeek/video/smd8eTFaYqeBvMLNshnV7dUB
- Audio: https://qlover.jp/hige/audio/smS2oaz3UyQfSr2afsmjnGvH
- Live: https://qlover.jp/agplayer/live/smSrNScKrWnjPhRZURctFWid - The example URL shows a simulcast to JoqrAG (uniqueradio.jp/agplayer5/); the URL changes daily.
- Live video archive: https://qlover.jp/onaken/video/smmCp8uhNrojyPHzCk6ZyJbK

### Provide a description that is worded well enough to be understood

The framework of this site looks very similar to NiconicoChannelPlus [nicochannel.jp].
All of the URLs example above are free videos that do not require login, but there are also paid videos that require login, such as NiconicoChannelPlus.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://qlover.jp/midnightdoublepeek/video/smd8eTFaYqeBvMLNshnV7dUB']
[debug] User config "/home/***/.config/yt-dlp/config": ['-o', '%(channel)s_%(upload_date)s_%(title)s_%(id)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds [f3411af12] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-186-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-70388-gaff24c1658-static (setts), ffprobe N-70388-gaff24c1658-static, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, mutagen-1.45.1, pycrypto-3.15.0, requests-2.22.0, secretstorage-2.3.1, sqlite3-3.31.1, urllib3-1.25.8, websockets-8.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://qlover.jp/midnightdoublepeek/video/smd8eTFaYqeBvMLNshnV7dUB
[generic] smd8eTFaYqeBvMLNshnV7dUB: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2383, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4141, in urlopen
    return self._request_director.send(req)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

**Comment by pzhlkj6612** [comment]
Triage: that's a Sheeta site; should be solved with #9541.
