### ISSUE TITLE
Did YouTube remove the file format with ID 22? It was 720p, 30 frames and had both video and audio

### ISSUE THREAD

**Issue by kraithus** [yt-dlp/yt-dlp#10286]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Below is my config which I used to download this [video](https:://youtu.be/PMbPtZkCeMQ) on 2024-06-12. I run the config today on other videos and notice it is not working I get the error "Requested format is not available. Use --list-formats for a list of available formats". I run the config on the same video that I downloaded with it before and same issue. When I run yt-dlp -F it all makes sense now. File Format with ID 22 is no longer there. Even for videos I once used this config on, so I'm wondering did YouTube scrape this file format off there servers?

```
--downloader aria2c
-f 22
--write-subs
--sub-lang en
--write-auto-subs
--sub-lang en
--embed-subs
--embed-metadata
--compat-options no-keep-subs
-o "%(channel)s - %(title)s - %(upload_date)s [%(id)s].%(ext)s"
--no-playlist
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -a m-dl.txt                                          ✔ 
[debug] Command-line config: ['-vU', '-a', 'm-dl.txt']
[debug] Home config "yt-dlp.conf": ['--downloader', 'aria2c', '-f', '22', '--write-subs', '--sub-lang', 'en', '--write-auto-subs', '--sub-lang', 'en', '--embed-subs', '--embed-metadata', '--compat-options', 'no-keep-subs', '-o', '%(channel)s - %(title)s - %(upload_date)s [%(id)s].%(ext)s', '--no-playlist']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=6jxIETSZuAQ', 'https://www.youtube.com/watch?v=Nwl-vQA8cIo', 'https://www.youtube.com/watch?v=v9ph4CZXBtY']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.26 from yt-dlp/yt-dlp [ae2af1104]
[debug] Compatibility options: no-keep-subs
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.1.92-1-MANJARO-x86_64-with-glibc2.39 (OpenSSL 3.3.0 9 Apr 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotlicffi-1.1.0.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.2, secretstorage-3.3.3, sqlite3-3.46.0, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.05.26 from yt-dlp/yt-dlp
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp from a manual build or with a package manager; Use that to update
[youtube] Extracting URL: https://www.youtube.com/watch?v=6jxIETSZuAQ
[youtube] 6jxIETSZuAQ: Downloading webpage
[youtube] 6jxIETSZuAQ: Downloading ios player API JSON
[debug] Loading youtube-nsig.5b22937f from cache
[debug] [youtube] Decrypted nsig iCbsUR7Zp-m63jGC => ET8z4YaBqM9Brw
[debug] Loading youtube-nsig.5b22937f from cache
[debug] [youtube] Decrypted nsig ToZjG8pWUE5SfynB => RUcRxPUOOUcvwg
[youtube] 6jxIETSZuAQ: Downloading m3u8 information
[info] 6jxIETSZuAQ: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] 6jxIETSZuAQ: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2955, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] 6jxIETSZuAQ: Requested format is not available. Use --list-formats for a list of available formats

[youtube] Extracting URL: https://www.youtube.com/watch?v=Nwl-vQA8cIo
[youtube] Nwl-vQA8cIo: Downloading webpage
[youtube] Nwl-vQA8cIo: Downloading ios player API JSON
[debug] [youtube] Extracting signature function js_5b22937f_105
[debug] Loading youtube-sigfuncs.js_5b22937f_105 from cache
[debug] Loading youtube-nsig.5b22937f from cache
[debug] [youtube] Decrypted nsig Mw4nzHjsfOap7226 => 7UzAA9jLGTGCkg
[debug] [youtube] Extracting signature function js_5b22937f_101
[debug] Loading youtube-sigfuncs.js_5b22937f_101 from cache
[debug] Loading youtube-nsig.5b22937f from cache
[debug] [youtube] Decrypted nsig Y7P1DFytihUhdx6g => TwpnBn83JXFewg
[youtube] Nwl-vQA8cIo: Downloading m3u8 information
[info] Nwl-vQA8cIo: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] Nwl-vQA8cIo: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2955, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] Nwl-vQA8cIo: Requested format is not available. Use --list-formats for a list of available formats

[youtube] Extracting URL: https://www.youtube.com/watch?v=v9ph4CZXBtY
[youtube] v9ph4CZXBtY: Downloading webpage
[youtube] v9ph4CZXBtY: Downloading ios player API JSON
[debug] Loading youtube-nsig.5b22937f from cache
[debug] [youtube] Decrypted nsig VK9RH14-pPmT-SgF => 13vniJ5Mye5PvQ
[debug] Loading youtube-nsig.5b22937f from cache
[debug] [youtube] Decrypted nsig kWzEG1OueisW3nPa => sD444o5AzsgSJg
[youtube] v9ph4CZXBtY: Downloading m3u8 information
[info] v9ph4CZXBtY: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] v9ph4CZXBtY: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2955, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] v9ph4CZXBtY: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
Yes, kind of. See #10206 for discussion and workarounds

**Comment by kraithus** [comment]
> Yes, kind of. See #10206 for discussion and workarounds

That was fast. Thank you. I thought I was going crazy
