### ISSUE TITLE
Streaming Service of the European Commission

### ISSUE THREAD

**Issue by wdbm** [yt-dlp/yt-dlp#10295]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Europe

### Example URLs

- Single video: 

### Provide a description that is worded well enough to be understood

This is a site request for the Streaming Service of the European Commission, accessible at webcast.ec.europa.eu.

I have observed that [Video DownloadHelper](https://en.wikipedia.org/wiki/Video_DownloadHelper) can download the media.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://webcast.ec.europa.eu/risk-management-logic-of-the-ai-act-and-related-standards-2024-05-30']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.27.232805 from yt-dlp/yt-dlp-nightly-builds [7a03f88c4] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-41-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.45.1, pyxattr-0.7.2, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.27.232805 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.27.232805 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://webcast.ec.europa.eu/risk-management-logic-of-the-ai-act-and-related-standards-2024-05-30
[generic] risk-management-logic-of-the-ai-act-and-related-standards-2024-05-30: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] risk-management-logic-of-the-ai-act-and-related-standards-2024-05-30: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://webcast.ec.europa.eu/risk-management-logic-of-the-ai-act-and-related-standards-2024-05-30
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1740, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/generic.py", line 2521, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://webcast.ec.europa.eu/risk-management-logic-of-the-ai-act-and-related-standards-2024-05-30
```

**Comment by coletdjnz** [comment]
possibly related: https://github.com/yt-dlp/yt-dlp/issues/4933
