### ISSUE TITLE
add support for telegraph.co.uk

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#10291]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

worldwide

### Example URLs

https://www.telegraph.co.uk/world-news/2024/06/28/biden-trump-first-presidential-debate-cnn-key-moments/

### Provide a description that is worded well enough to be understood

The generic extractor does not work on this site (one of the most important news sites in the UK), as shown below.

This snippet from the page source contains the information necessary to download one of the videos (the page contains several):

```
window.videos = [{"name":"d0941158.mp4","status":"ready","url":"https://cf.eip.telegraph.co.uk/store/vid-media/d0941158/d0941158.mp4","storageFileName":"d0941158.mp4","data":{"streams":[{"index":0,"codec_name":"h264","codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","profile":"Main","codec_type":"video","codec_tag_string":"avc1","codec_tag":"0x31637661","width":1920,"height":1080,"coded_width":1920,"coded_height":1080,"closed_captions":0,"film_grain":0,"has_b_frames":0,"sample_aspect_ratio":"1:1","display_aspect_ratio":"16:9","pix_fmt":"yuv420p","level":41,"color_range":"tv","color_space":"bt709","color_transfer":"bt709","color_primaries":"bt709","chroma_location":"left","field_order":"progressive","refs":1,"is_avc":"true","nal_length_size":4,"id":"0x1","r_frame_rate":"25/1","avg_frame_rate":"25/1","time_base":"1/25000","start_pts":0,"start_time":0,"duration_ts":720000,"duration":28.8,"bit_rate":15767956,"max_bit_rate":"N/A","bits_per_raw_sample":8,"nb_frames":720,"nb_read_frames":"N/A","nb_read_packets":"N/A","extradata_size":46,"tags":{"creation_time":"2024-06-28T03:32:51.000000Z","language":"eng","handler_name":"\u001fMainconcept Video Media Handler","vendor_id":"[0][0][0][0]","encoder":"AVC Coding"},"disposition":{"default":1,"dub":0,"original":0,"comment":0,"lyrics":0,"karaoke":0,"forced":0,"hearing_impaired":0,"visual_impaired":0,"clean_effects":0,"attached_pic":0,"timed_thumbnails":0,"non_diegetic":0,"captions":0,"descriptions":0,"metadata":0,"dependent":0,"still_image":0}},{"index":1,"codec_name":"aac","codec_long_name":"AAC (Advanced Audio Coding)","profile":"LC","codec_type":"audio","codec_tag_string":"mp4a","codec_tag":"0x6134706d","sample_fmt":"fltp","sample_rate":48000,"channels":2,"channel_layout":"stereo","bits_per_sample":0,"initial_padding":0,"id":"0x2","r_frame_rate":"0/0","avg_frame_rate":"0/0","time_base":"1/48000","start_pts":0,"start_time":0,"duration_ts":1382400,"duration":28.8,"bit_rate":317186,"max_bit_rate":"N/A","bits_per_raw_sample":"N/A","nb_frames":1351,"nb_read_frames":"N/A","nb_read_packets":"N/A","extradata_size":2,"tags":{"creation_time":"2024-06-28T03:32:52.000000Z","language":"eng","handler_name":"#Mainconcept MP4 Sound Media Handler","vendor_id":"[0][0][0][0]"},"disposition":{"default":1,"dub":0,"original":0,"comment":0,"lyrics":0,"karaoke":0,"forced":0,"hearing_impaired":0,"visual_impaired":0,"clean_effects":0,"attached_pic":0,"timed_thumbnails":0,"non_diegetic":0,"captions":0,"descriptions":0,"metadata":0,"dependent":0,"still_image":0}}],"format":{"filename":"/tmp/uploads_file-uploader_5304209e-8807-4cd7-ae24-335935b7ad94.mp4","nb_streams":2,"nb_programs":0,"format_name":"mov,mp4,m4a,3gp,3g2,mj2","format_long_name":"QuickTime / MOV","start_time":0,"duration":28.8,"size":57968856,"bit_rate":16102460,"probe_score":100,"tags":{"major_brand":"mp42","minor_version":"0","compatible_brands":"mp42mp41","creation_time":"2024-06-28T03:32:50.000000Z"}},"chapters":[]},"original":true},{"status":"ready","name":"Adaptive Stream","description":"Automatically generated for particle","storageFileName":"hls-adaptive-stream/d0941158.m3u8","id":"adaptive-stream","url":"https://cf.eip.telegraph.co.uk/store/vid-media/d0941158/hls-adaptive-stream/d0941158.m3u8","audio":true,"type":"video","adaptive":true,"data":[{"streamQuality":"vlow","duration":28800,"height":180,"width":320,"averageBitrate":51951},{"streamQuality":"low","duration":28800,"height":270,"width":480,"averageBitrate":120179},{"streamQuality":"medium","duration":28800,"height":406,"width":720,"averageBitrate":421807},{"streamQuality":"high","duration":28800,"height":608,"width":1080,"averageBitrate":1218756}]}]
        window.videoSettings = {"selectedMobileRenditionID":"adaptive-stream","selectedDesktopRenditionID":"adaptive-stream","loop":true,"autoplay":true,"darkProgressBar":false,"showProgressBar":true,"showMuteButton":true,"showPlayButton":true,"credit":"CNN Presidential Debate","thumbnail":"https://cf.eip.telegraph.co.uk/store/vid-media/d0941158/thumbnails/d0941158-adaptive-stream.0000000.jpg"}
```

In particular:

Direct download  of a very high quality file (a whopping 16 Mb/s):
https://cf.eip.telegraph.co.uk/store/vid-media/d0941158/d0941158.mp4

Flie containing information for four lower quality streams:
https://cf.eip.telegraph.co.uk/store/vid-media/d0941158/hls-adaptive-stream/d0941158.m3u8

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=210184,AVERAGE-BANDWIDTH=191598,CODECS="avc1.64000c,mp4a.40.2",RESOLUTION=320x180,FRAME-RATE=25.000
d0941158-vlow.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=310200,AVERAGE-BANDWIDTH=257560,CODECS="avc1.640015,mp4a.40.2",RESOLUTION=480x270,FRAME-RATE=25.000
d0941158-low.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=732072,AVERAGE-BANDWIDTH=562979,CODECS="avc1.64001e,mp4a.40.2",RESOLUTION=720x406,FRAME-RATE=25.000
d0941158-medium.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1734112,AVERAGE-BANDWIDTH=1370036,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=1080x608,FRAME-RATE=25.000
d0941158-high.m3u8
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ /tmp/yt-dlp-2024.06.27.232805 -v 'https://www.telegraph.co.uk/world-news/2024/06/28/biden-trump-first-presidential-debate-cnn-key-moments/'
[debug] Command-line config: ['-v', 'https://www.telegraph.co.uk/world-news/2024/06/28/biden-trump-first-presidential-debate-cnn-key-moments/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.27.232805 from yt-dlp/yt-dlp-nightly-builds [7a03f88c4] (zip)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.1.53-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.20.0, requests-2.32.3, urllib3-2.2.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1823 extractors
[generic] Extracting URL: https://www.telegraph.co.uk/world-news/2024/06/28/biden-trump-first-presidential-debate-cnn-key-moments/
[generic] biden-trump-first-presidential-debate-cnn-key-moments: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] biden-trump-first-presidential-debate-cnn-key-moments: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.telegraph.co.uk/world-news/2024/06/28/biden-trump-first-presidential-debate-cnn-key-moments/
Traceback (most recent call last):
  File "/tmp/yt-dlp-2024.06.27.232805/yt_dlp/YoutubeDL.py", line 1605, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp-2024.06.27.232805/yt_dlp/YoutubeDL.py", line 1740, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp-2024.06.27.232805/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp-2024.06.27.232805/yt_dlp/extractor/generic.py", line 2521, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.telegraph.co.uk/world-news/2024/06/28/biden-trump-first-presidential-debate-cnn-key-moments/
```

**Comment by dirkf** [comment]
The main page has a ld+json block but has no `contentUrl`s. The video links are found in embedded `iframe` pages like that at https://cf-particle-html.eip.telegraph.co.uk/b11c0f86-1511-4be1-8b89-320b49140093.html?direct=true&id=b11c0f86-1511-4be1-8b89-320b49140093&template=articleRendererHTML. There are 7 of these in the problem page: perhaps not all have relevant video links. Bot the main page and the `iframe`s need custom extraction.
