### ISSUE TITLE
Compiling a binary with Nuitka?

### ISSUE THREAD

**Issue by Kukaina** [yt-dlp/yt-dlp#10307]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I tried to use nuitka to convert my code into binary files, but it kept getting stuck. I don't know if it's a problem with yt-dlp or nuitka, but I think it has nothing to do with my computer configuration because it doesn't reach a high usage.
This is the nuitka command I used
It always gets stuck at around 97%, I've looked at Nuitka's #2879 issue but that didn't solve my problem
```shell
nuitka --mingw64  --standalone --show-progress --windows-console=disable --windows-icon-from-ico=./resource/icon.ico app.py
```
This is part of its output
```
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.amadeustv', 58 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.amadeustv'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin_ref,new_constant,new_expression,new_statements
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.alura', 57 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.alura'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_statements
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.altcensored', 56 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.altcensored'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin_ref,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.alsace20tv', 55 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.alsace20tv'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin_ref,new_expression,new_statements
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.alphaporno', 54 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.alphaporno'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: new_builtin_ref,new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.allstar', 53 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.allstar'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,trusted_module_variables,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin_ref,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.allocine', 52 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.allocine'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_expression,new_statements
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_constant
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.aljazeera', 51 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.aljazeera'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.aliexpress', 50 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.aliexpress'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.aitube', 49 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.aitube'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: new_builtin_ref,new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.airtv', 48 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.airtv'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin_ref,new_statements
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.agora', 47 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.agora'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,trusted_module_variables,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin_ref,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_statements,var_usage
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.afreecatv', 46 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.afreecatv'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,trusted_module_variables,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements,var_usage
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.aeonco', 45 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.aeonco'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: new_builtin_ref,new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.aenetworks', 44 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.aenetworks'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.adultswim', 43 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.adultswim'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin_ref,new_expression,new_statements
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,var_usage
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.adobetv', 42 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.adobetv'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,trusted_module_variables,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.adobeconnect', 41 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.adobeconnect'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,var_usage
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.adn', 40 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.adn'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,trusted_module_variables,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_constant,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.acfun', 39 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.acfun'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_statements
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.acast', 38 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.acast'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin_ref,new_expression,new_statements
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.academicearth', 37 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.academicearth'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.abematv', 36 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.abematv'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,trusted_module_variables,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_constant,new_statements,var_usage
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.abcotvs', 35 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.abcotvs'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: new_builtin_ref,new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.abcnews', 34 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.abcnews'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.abc', 33 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.abc'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements,var_usage
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.youtube', 32 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.youtube'.
Nuitka-Progress: Not finished with the module due to following change kinds:
Nuitka-Progress: new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,trusted_module_variables,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.jsinterp', 33 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.jsinterp'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_constant,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'shlex', 32 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'shlex'.
Nuitka-Progress: Not finished with the module due to following change kinds: new_constant,new_expression,new_statements,trusted_module_variables,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,var_usage
Nuitka-Progress: Not finished with the module due to following change kinds: loop_analysis,new_constant,new_expression,new_statements
Nuitka-Progress: Not changed, but retrying one more time.
Nuitka-Progress: Finished with the module.
Nuitka-Progress: Optimizing module 'yt_dlp.extractor.lazy_extractors', 31 more modules to go after that.
Nuitka-Progress: Doing module local optimizations for 'yt_dlp.extractor.lazy_extractors'.
Nuitka-Progress: Not finished with the module due to following change kinds:        
Nuitka-Progress: new_builtin,new_builtin_ref,new_constant,new_expression,new_statements,trusted_module_variables,var_usage
PASS 1: 97.9%|████████████████████████▍| 1458/1490, yt_dlp.extractor.lazy_extractors
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by TheSystemGuy1337** [comment]
Try using a different compiler. I have never heard of nuitka, so chances are it could be a nuitka bug or a compatibility issue.

**Comment by bashonly** [comment]
This does indeed look exactly like https://github.com/Nuitka/Nuitka/issues/2879

What happens if you remove `lazy_extractors.py`?

**Comment by Kukaina** [comment]
> This does indeed look exactly like [Nuitka/Nuitka#2879](https://github.com/Nuitka/Nuitka/issues/2879)
> 
> What happens if you remove `lazy_extractors.py`?

Thanks, I commented out all the contents of this file and it worked smoothly.

**Comment by Kukaina** [comment]
> > This does indeed look exactly like [Nuitka/Nuitka#2879](https://github.com/Nuitka/Nuitka/issues/2879)
> > What happens if you remove `lazy_extractors.py`?
> 
> Thanks, I commented out all the contents of this file and it worked smoothly.

But this seems to cause new problems in the program
```
Traceback (most recent call last):
  File "C:\Users\HUTAO\Desktop\MangoVid\SRC_FL~1\APP~1.DIS\app.py", line 7, in <module>
  File "C:\Users\HUTAO\Desktop\MangoVid\SRC_FL~1\APP~1.DIS\yt_dlp\__init__.py", line 19, in <module yt_dlp>
  File "C:\Users\HUTAO\Desktop\MangoVid\SRC_FL~1\APP~1.DIS\yt_dlp\downloader\__init__.py", line 24, in <module yt_dlp.downloader>
  File "C:\Users\HUTAO\Desktop\MangoVid\SRC_FL~1\APP~1.DIS\yt_dlp\downloader\common.py", line 16, in <module yt_dlp.downloader.common>
  File "C:\Users\HUTAO\Desktop\MangoVid\SRC_FL~1\APP~1.DIS\yt_dlp\compat\compat_utils.py", line 36, in __getattribute__
  File "C:\Users\HUTAO\Desktop\MangoVid\SRC_FL~1\APP~1.DIS\yt_dlp\compat\compat_utils.py", line 54, in __getattr__
  File "C:\Users\HUTAO\Desktop\MangoVid\SRC_FL~1\APP~1.DIS\yt_dlp\compat\compat_utils.py", line 68, in from_child
  File "importlib.py", line 90, in import_module
ModuleNotFoundError: No module named 'yt_dlp.utils._deprecated'
```

**Comment by bashonly** [comment]
Nuitka isn't correctly detecting yt-dlp's imports. Pyinstaller solves this by allowing a package to specify its "hidden imports" (which is done by yt-dlp [here](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/__pyinstaller/hook-yt_dlp.py)). Nuitka does not seem to have an equivalent to this, and therefore yt-dlp can't support building with Nuitka. I think you'll need to open an issue with Nuitka about this

**Comment by bashonly** [comment]
Fixed(?) in https://github.com/Nuitka/Nuitka/commit/5c5f6803d5166f54189e156b242d2423baaecbb3

I'd suggest removing `yt_dlp/extractor/lazy_extractors.py` entirely before trying to compile

**Comment by demon071** [comment]
use --include-module=yt_dlp.utils._deprecated worked for me
