### ISSUE TITLE
[Feature request] knowledge.ca support

### ISSUE THREAD

**Issue by werdahias** [yt-dlp/yt-dlp#10304]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

https://www.knowledge.ca/program/sgaawaay-kuuna-edge-knife

### Provide a description that is worded well enough to be understood

Needs a free account and is geoblocked to Canada.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.knowledge.ca/program/sgaawaay-kuuna-edge-knife
[debug] Command-line config: ['-vU', 'https://www.knowledge.ca/program/sgaawaay-kuuna-edge-knife']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (debian*)
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.8.12-amd64-x86_64-with-glibc2.38 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1-4 (setts), ffprobe 6.1.1-4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.46.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.0, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.knowledge.ca/program/sgaawaay-kuuna-edge-knife
[generic] sgaawaay-kuuna-edge-knife: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] sgaawaay-kuuna-edge-knife: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.knowledge.ca/program/sgaawaay-kuuna-edge-knife
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.knowledge.ca/program/sgaawaay-kuuna-edge-knife
```

**Comment by werdahias** [comment]
I tried my hand at writing the new extractor but the tests didn't work for me; draft:

diff --git a/yt_dlp/extractor/_extractors.py b/yt_dlp/extractor/_extractors.py
index c411efb5a..4b47ed528 100644
--- a/yt_dlp/extractor/_extractors.py
+++ b/yt_dlp/extractor/_extractors.py
@@ -949,6 +949,7 @@
 from .kickstarter import KickStarterIE
 from .kinja import KinjaEmbedIE
 from .kinopoisk import KinoPoiskIE
+from .knowledge-ca import KnowledgeCaIE
 from .kommunetv import KommunetvIE
 from .kompas import KompasVideoIE
 from .koo import KooIE
diff --git a/yt_dlp/extractor/knowledge-ca.py b/yt_dlp/extractor/knowledge-ca.py
new file mode 100644
index 000000000..68f350340
--- /dev/null
+++ b/yt_dlp/extractor/knowledge-ca.py
@@ -0,0 +1,43 @@
+from .common import InfoExtractor
+
+
+class KnowlegdeCaIE(InfoExtractor):
+    IE_NAME = 'knowledge.ca'
+    IE_DESC = 'knowledge.ca videos'
+    _VALID_URL = r'https?://(?:www\.)?knowledge\.ca/program/(?P[^/])'
+    _TESTS = [{
+        'url': 'https://www.knowledge.ca/program/sgaawaay-kuuna-edge-knife',
+        'md5': 'TODO: md5 sum of the first 10241 bytes of the video file (use --test)',
+        'info_dict': {
+            # For videos, only the 'id' and 'ext' fields are required to RUN the test:
+            'id': '42',
+            'ext': 'mp4',
+            # Then if the test run fails, it will output the missing/incorrect fields.
+            # Properties can be added as:
+            # * A value, e.g.
+            #     'title': 'Video title goes here',
+            # * MD5 checksum; start the string with 'md5:', e.g.
+            #     'description': 'md5:098f6bcd4621d373cade4e832627b4f6',
+            # * A regular expression; start the string with 're:', e.g.
+            #     'thumbnail': r're:^https?://.*\.jpg$',
+            # * A count of elements in a list; start the string with 'count:', e.g.
+            #     'tags': 'count:10',
+            # * Any Python type, e.g.
+            #     'view_count': int,
+        }
+    }]
+
+    def _real_extract(self, url):
+        video_id = self._match_id(url)
+        webpage = self._download_webpage(url, video_id)
+
+        # TODO more code goes here, for example ...
+        title = self._html_search_regex(r'<h1>(.+?)</h1>', webpage, 'title')
+
+        return {
+            'id': video_id,
+            'title': title,
+            'description': self._og_search_description(webpage),
+            'uploader': self._search_regex(r'<div[^>]+id="uploader"[^>]*>([^<]+)<', webpage, 'uploader', fatal=False),
+            # TODO more properties (see yt_dlp/extractor/common.py)
+        }

**Comment by pto199** [comment]
Any Progress on this?  Have been wanting to DL from this site for years.  Nobody supports it.

**Comment by werdahias** [comment]
@pto199 Can you share your solution? Which cookie did you use ?

**Comment by pto199** [comment]
You login to the site on your webbrowser, then you save the cookie to a text file with an extension.  You then use the --cookie flag in YT-DLP and point it to your text file.

Ask Chatgpt for detailed steps on how to save a stream with yt-dlp using a cookie.

**Comment by werdahias** [comment]
thanks, works for me too

**Comment by dirkf** [comment]
The original test show has expired. https://www.knowledge.ca/program/lennonyc is a current test URL.

The critical missing part of the [draft code](https://github.com/yt-dlp/yt-dlp/issues/10304#issuecomment-2198328062) is that no `formats` have been extracted. The extractor needs to find the actual video link(s) that the browser will use. A link might be a plain mp4 or manifest URL in the HTML sent to a logged-in user, bearing in mind that the extractor will only see the plain HTML (View Source in the browser) and not the version shown in the browser's web tools Inspect HTML tab, which nowadays is likely to have been modified by site JS; or the wanted URL(s) might be constructed by combining URL patterns seen in the browser's web tools with information from the web page. 

Should the development guidance be more explicit about this?

**Comment by werdahias** [comment]
> The original test show has expired. https://www.knowledge.ca/program/lennonyc is a current test URL.
Ah, thanks.
> The critical missing part of the draft code is that no formats have been extracted. The extractor needs to find the actual video link(s) that the browser will use. A link might be a plain mp4 or manifest URL in the HTML sent to a logged-in user, bearing in mind that the extractor will only see the plain HTML (View Source in the browser) and not the version shown in the browser's web tools Inspect HTML tab, which nowadays is likely to have been modified by site JS; or the wanted URL(s) might be constructed by combining URL patterns seen in the browser's web tools with information from the web page.
Ok, will try to look into it.
> 
> Should the development guidance be more explicit about this?
Yes. As a somewhat seasoned contributor I was able to follow most but I think that some people might have difficulties to start contributing. Imo the  wiki could use improvement.

**Comment by werdahias** [comment]
@dirkf 
I got this from the HTML:


```
 jwplayer('jw_player_vod_755192').setup({"playlist":[{"title":"Broadchurch - S1E1 - Broadchurch","mediaid":"tkChbKEs","link":"https://cdn.jwplayer.com/previews/tkChbKEs",
"image":"https://cdn.jwplayer.com/v2/media/tkChbKEs/poster.jpg?width=720","images":[{"src":"https://cdn.jwplayer.com/v2/media/tkChbKEs/poster.jpg?width=320","width":320,"type":"image/jpeg"}
,{"src":"https://cdn.jwplayer.com/v2/media/tkChbKEs/poster.jpg?width=480","width":480,"type":"image/jpeg"},{"src":"https://cdn.jwplayer.com/v2/media/tkChbKEs/poster.jpg?width=640","width":640,"type":"image/jpeg"},{"src":"https://cdn.jwplayer.com/v2/media/tkChbKEs/poster.jpg?width=720","width":720,"type":"image/jpeg"},{"src":"https://cdn.jwplayer.com/v2/media/tkChbKEs/poster.jpg?width=1280","width":1280,"type":"image/jpeg"},{"src":"https://cdn.jwplayer.com/v2/media/tkChbKEs/poster.jpg?width=1920","width":1920,"type":"image/jpeg"}],"duration":2773,"pubdate":1702426794,"description":"","sources":[{"file":"https://cdn.jwplayer.com/manifests/tkChbKEs.m3u8","type":"hls"},{"file":"https://cdn.jwplayer.com/videos/tkChbKEs-iehAYMoO.mp4","type":"video/mp4","height":1080,"width":1920,"label":"H.264 1920px","bitrate":2962088,"filesize":1026733784,"framerate":30},{"file":"https://cdn.jwplayer.com/videos/tkChbKEs-JzJaSwCH.m4a","type":"audio/mp4","label":"AAC Audio","bitrate":113384,"filesize":39301837},{"file":"https://cdn.jwplayer.com/videos/tkChbKEs-O7SJBKA8.mp4","type":"video/mp4","height":720,"width":1280,"label":"H.264 1280px","bitrate":1264471,"filesize":438297533,"framerate":30},{"file":"https://cdn.jwplayer.com/videos/tkChbKEs-n3WUK5QK.mp4","type":"video/mp4","height":406,"width":720,"label":"H.264 720px","bitrate":571047,"filesize":197939301,"framerate":30},{"file":"https://cdn.jwplayer.com/videos/tkChbKEs-kq4chQPW.mp4","type":"video/mp4","height":270,"width":480,"label":"H.264 480px","bitrate":426316,"filesize":147772117,"framerate":30},{"file":"https://cdn.jwplayer.com/videos/tkChbKEs-3RjfBkOX.mp4","type":"video/mp4","height":180,"width":320,"label":"H.264 320px","bitrate":300093,"filesize":104019763,"framerate":30}],"tracks":[{"file":"https://cdn.jwplayer.com/tracks/A34Zy4hI.vtt","kind":"captions","label":"English","includedInManifest":true},{"file":"https://cdn.jwplayer.com/strips/tkChbKEs-120.vtt","kind":"thumbnails"}],
```
 
This means that the video (broadchurch in this case) is loaded from `https://cdn.jwplayer.com/videos/tkChbKEs-n3WUK5QK.mp4` where `tkChbKEs` is the ID for this video. What I haven't figured out:
Is my _URL the one for the CDN ? if not, how do I tell yt-dlp to grab the video from the CDN ?

**Comment by dirkf** [comment]
The quoted jwplayer JS fragment is not found in the basic not-logged-in, non-JS page that will be fetched from https://www.knowledge.ca/program/broadchurch/s1/e1/broadchurch.

On the positive side, there is a common extraction function for jwplayer pages. If the magic ID 755192 could be useful in some way, it can be found in the basic page, eg from `https://www.knowledge.ca/node/755192` (the short link that aliases to the programme page above).

If the logged-in, non-JS page should contain the jwplayer fragment, it's possible that passing logged-in cookies will enable _yt-dlp_ to extract successfully. This seems likely because https://www.knowledge.ca/program/broadchurch/s1/preview does have a jwplayer block:
```
$ yt-dlp -vF 'https://www.knowledge.ca/program/broadchurch/s1/preview'
[debug] Command-line config: ['-vF', 'https://www.knowledge.ca/program/broadchurch/s1/preview']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (zip)
[debug] Python 3.9.21 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.23)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2019.11.28, requests-2.25.1, secretstorage-3.2.0, sqlite3-3.37.2, urllib3-1.25.11
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[generic] Extracting URL: https://www.knowledge.ca/program/broadchurch/s1/preview
[generic] preview: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] preview: Extracting information
[debug] Looking for embeds
[generic] preview: Downloading m3u8 information
[debug] Identified a JW Player data
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for preview:
ID           EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC      ACODEC     ABR
─────────────────────────────────────────────────────────────────────────────────────
0            m4a audio only     │                  https │ audio only  unknown
120          mp4 audio only     │ ~805.66KiB  120k m3u8  │ audio only  mp4a.40.2 120k
H.264_320px  mp4 320x180        │    2.21MiB  336k https │ unknown     unknown
340          mp4 320x180     30 │ ~  2.23MiB  340k m3u8  │ avc1.42c00d mp4a.40.2
H.264_480px  mp4 480x270        │    3.24MiB  494k https │ unknown     unknown
500          mp4 480x270     30 │ ~  3.28MiB  500k m3u8  │ avc1.42c015 mp4a.40.2
H.264_720px  mp4 720x406        │    4.07MiB  621k https │ unknown     unknown
630          mp4 720x406     30 │ ~  4.13MiB  630k m3u8  │ avc1.4d401e mp4a.40.2
H.264_1280px mp4 1280x720       │    9.34MiB 1424k https │ unknown     unknown
1430         mp4 1280x720    30 │ ~  9.38MiB 1430k m3u8  │ avc1.4d401f mp4a.40.2
H.264_1920px mp4 1920x1080      │   21.43MiB 3268k https │ unknown     unknown
3270         mp4 1920x1080   30 │ ~ 21.44MiB 3270k m3u8  │ avc1.640028 mp4a.40.2
$ 
```

**Comment by werdahias** [comment]
sorry, I don't really understand what you mean by this. Does this mean the jwplayer should be the url to fetch things from ?

**Comment by dirkf** [comment]
Try passing logged-in cookies (FAQ) and forcing the generic extractor at the same time, using the problem URL.

As shown, the latter works with the preview video. My guess was that authenticating (with cookies) as a user who can view the problem video in a browser would cause the non-JS page for the problem video to be populated in the same way and thus allow the generic extractor to work, using its JWPlayer extraction tactic (`a JW Player data.` ?).

**Comment by werdahias** [comment]
```
yt-dlp -vF --cookies ~/Dokumente/cookies.txt 'https://www.knowledge.ca/program/broadchurch/s1/preview'                             
[debug] Command-line config: ['-vF', '--cookies', '/home/werdahias/Dokumente/cookies.txt', 'https://www.knowledge.ca/program/broadchurch/s1/preview']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.01.15 from yt-dlp/yt-dlp [c8541f8b1] (debian*)
[debug] Python 3.13.1 (CPython x86_64 64bit) - Linux-6.12.10-amd64-x86_64-with-glibc2.40 (OpenSSL 3.4.0 22 Oct 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.1-3 (setts), ffprobe 7.1-3
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.12.14, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[generic] Extracting URL: https://www.knowledge.ca/program/broadchurch/s1/preview
[generic] preview: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] preview: Extracting information
[debug] Looking for embeds
[generic] preview: Downloading m3u8 information
[debug] Identified a JW Player data
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for preview:
ID           EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC      ACODEC     ABR
─────────────────────────────────────────────────────────────────────────────────────
0            m4a audio only     │                  https │ audio only  unknown
120          mp4 audio only     │ ~805.66KiB  120k m3u8  │ audio only  mp4a.40.2 120k
H.264_320px  mp4 320x180        │    2.21MiB  336k https │ unknown     unknown
340          mp4 320x180     30 │ ~  2.23MiB  340k m3u8  │ avc1.42c00d mp4a.40.2
H.264_480px  mp4 480x270        │    3.24MiB  494k https │ unknown     unknown
500          mp4 480x270     30 │ ~  3.28MiB  500k m3u8  │ avc1.42c015 mp4a.40.2
H.264_720px  mp4 720x406        │    4.07MiB  621k https │ unknown     unknown
630          mp4 720x406     30 │ ~  4.13MiB  630k m3u8  │ avc1.4d401e mp4a.40.2
H.264_1280px mp4 1280x720       │    9.34MiB 1424k https │ unknown     unknown
1430         mp4 1280x720    30 │ ~  9.38MiB 1430k m3u8  │ avc1.4d401f mp4a.40.2
H.264_1920px mp4 1920x1080      │   21.43MiB 3268k https │ unknown     unknown
3270         mp4 1920x1080   30 │ ~ 21.44MiB 3270k m3u8  │ avc1.640028 mp4a.40.2

```

**Comment by dirkf** [comment]
OK, so the site is probably inserting the JW player stuff with client-side JS; someone with the correct credentials and enough time will have to trace the protocol traffic and/or reverse what the JS does.

**Comment by werdahias** [comment]
how would I go about this ?

**Comment by dirkf** [comment]
You'd spend a lot of time with the Developer Tools of your browser to understand how the media link(s) appear in the webpage, but you'd need to have some understanding of how web pages and JS work together.

There are two possible things to consider:
* maybe the necessary data is in the HTML page, and the page runs JS to insert the media links into the browser's DOM for the page;
* otherwise, the page JS must be fetching the data (typically using XHR) in further network requests after the page has loaded and inserting the media links.

And following Monty Python's Spanish Inquisition rule of enumeration, a third possibility is a combination of those two.

The page for S1E1 has this block of elements that seems to be significant:
```html
<script type="application/json" data-drupal-selector="drupal-settings-json">{"path":{"baseUrl":"\/","pathPrefix":"","currentPath":"node\/755192","currentPathIsAdmin":false,"isFront":false,"currentLanguage":"en"},"pluralDelimiter":"\u0003","suppressDeprecationErrors":true,"dataLayer":{"defaultLang":"en","languages":{"en":{"id":"en","name":"English","direction":"ltr","weight":0}}},"user":{"uid":0,"permissionsHash":"d7fdcc4b53c0330ae8828ed7c0428646a466697c1f3778fa143e764416f2cd51"}}</script>
<script src="/sites/default/files/js/js_WEydnujB1JaJ8YE97DsfO5CPCGez55K4SdOKTkrHngA.js?scope=header&amp;delta=0&amp;language=en&amp;theme=kn5bs&amp;include=eJwlykEOgCAMAMEPgZx8DymhIFhaAyjx90q4bSbroQPBi9U4POBJUps6eXfNRBIHpFt_KXH80eZhr_XmsUINtAUjFOTbBKllG6gn6Ck6VOGO7D_TuCc3"></script>
<script src="//content.jwplatform.com/libraries/THOKNsGF.js"></script>
```
The first `script` provides some possibly useful data that could be used by JS: maybe this `755192` is what will be used to identify the video when generating the links. The second loads what is presumably the site-specific JS. The third loads what says is v8.36.4 of the JW Player library JS, customised to the site, if only through the data defined at the end of the file. As usual the JS is all minimised but searching for text (like `jwplayer`) and pretty-printing relevant sections may help.
