### ISSUE TITLE
Please add ability to download from Russian new Youtube-like video platform Платформа

### ISSUE THREAD

**Issue by communist1917** [yt-dlp/yt-dlp#10311]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Russia

### Example URLs

public: https://plvideo.ru/watch?v=2tER6WkBQafV
authwalled: https://plvideo.ru/watch?v=Cx505HguTyva

### Provide a description that is worded well enough to be understood

В отличии от других сервисов, на которые возлагаются некоторые надежды по "замене" в РФ Ютуба (RuTube, VK Видео), новый сервис предлагает максимально схожие с ютубовскими интерфейс и функционал, где предусмотрена система рекомендаций, инструменты продвижения и аналитики для блогеров, формат коротких видеороликов по примеру Shorts в YouTube, а так же распознавание русского и английского языков в автоматически создаваемых субтитрах. Ну и конечно же система модерации, призванная (это тоже заявлено) выявлять нарушения российского законодательства и "прочий нежелательный контент".

По словам генерального директора Rteam Андрея Талызина, в настоящее время "Платформа" может выдерживать 240 тыс. запросов в секунду, а видеоролики доступны вплоть до 4К.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU 'https://plvideo.ru/watch?v=Cx505HguTyva'
[debug] Command-line config: ['-vU', 'https://plvideo.ru/watch?v=Cx505HguTyva']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6]
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.6.32-1-MANJARO-x86_64-with-glibc2.39 (OpenSSL 3.3.0 9 Apr 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.02.02, requests-2.32.3, sqlite3-3.46.0, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://plvideo.ru/watch?v=Cx505HguTyva
[generic] watch?v=Cx505HguTyva: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] watch?v=Cx505HguTyva: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://plvideo.ru/watch?v=Cx505HguTyva
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://plvideo.ru/watch?v=Cx505HguTyva
```

**Comment by atagmester** [comment]
Until there's no extractor for the site, you can "extract" the link from your browser, then download the "playlist" with yt-dlp...
`yt-dlp https://vod.plvideo.ru/GMPb65uk/KdjvBG9qXH/FP7MRNSCx505HguTyva/ZX`

(In browser's dev tools select network tab, and search for 'ZX' in the filter bar for the current link)

**Comment by krasnh** [comment]
>https://plvideo.ru/watch?v=Cx505HguTyva

_"Войдите, чтобы подтвердить свой возраст
Это видео может быть неприемлимо для некоторых пользователей."_

--------------------------------------------------------------
It is better to use a video that does not require registration,
https://plvideo.ru/watch?v=2tER6WkBQafV.

**Comment by Stalinist1** [comment]
> It is better to use a video that does not require registration, https://plvideo.ru/watch?v=2tER6WkBQafV.

Of course. When I made this post the video wasn't marked as sentitive.

**Comment by artenax** [comment]
You can also get a link to ZX in this extension
https://chromewebstore.google.com/detail/the-stream-detector/iakkmkmhhckcmoiibcfjnooibphlobak

**Comment by krasnh** [comment]
>You can also get a link to ZX in this extension

For firefox, [The Stream Detector](https://addons.mozilla.org/ru/firefox/addon/hls-stream-detector).

**Comment by krasnh** [comment]
I checked https://github.com/yt-dlp/yt-dlp/pull/10657, the working.

```sh
$ ./yt-dlp.sh 'https://plvideo.ru/watch?v=QcIpSAA91j1N'
[PlVideoVideo] Extracting URL: https://plvideo.ru/watch?v=QcIpSAA91j1N
[PlVideoVideo] QcIpSAA91j1N: Downloading video JSON
[info] QcIpSAA91j1N: Downloading 1 format(s): 720p
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 28
[download] Destination: Рождество - Так хочется жить (Official video) [QcIpSAA91j1N].mp4
[download] 100% of   59.28MiB in 00:00:30 at 1.96MiB/s
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Рождество - Так хочется жить (Official video) [QcIpSAA91j1N].mp4"
[Metadata] There isn't any metadata to add

```

**Comment by artenax** [comment]
Thanks to **Sanceilaks** for adding plvideo support. Until the code is officially added to yt-dlp, you can use my build.
https://github.com/artenax/yt-dlp/releases
You must have Python 3 installed on your system.

`python3 yt-dlp-plvideo URL`

**Comment by krasnh** [comment]
The code is already ready (https://github.com/yt-dlp/yt-dlp/pull/10657) and verified ([1](https://github.com/yt-dlp/yt-dlp/issues/10311#issuecomment-2292846408)). Is it left to add to the master?

**Comment by communist1917** [comment]
Still no extractor in yt-dlp. I still have to search for "ZX" line to feed to the app.

**Comment by krasnh** [comment]
It seems to me that "yt-dlp" follows the path of "youtube-dl". There, the main developer left and the project stalled.  So here, too, as @pukkandan began to devote less time to the project.

**Comment by seproDev** [comment]
@krasnh IMO that is a gross mischaracterization. Yes, pukkandan has less time for the project now, however there are still other maintainers (mostly @bashonly and me) actively reviewing PRs and merging them. In the last month, over 60 PRs were merged.
With all the recent changes YouTube made, yt-dlp adapted incredibly quickly and released fixes. Doesn't seem like a dead project to me.

The truth of the matter is that it just takes a lot of effort to review code. It can take hours to bring a PR up to our standard. *Working* is not the bar to meet for PRs; otherwise the codebase would become very quickly unmaintainable.

The issue with https://github.com/yt-dlp/yt-dlp/pull/10657 specifically was that it did not follow the yt-dlp coding conventions. It took me about 40 minutes to rework the extractor. The more complex an extractor, and the more work required, the longer it will take for a maintainer to pick it up. This is not something against the author of that PR. It just takes time to get experienced with the project, and to learn how an extractor should be written.

A fork can not just magically fix the lack of people willing to and having the time to review PRs.
Instead of complaining, I invite you to [contribute something of value yourself](https://github.com/yt-dlp/yt-dlp/pulls/krasnh). :)

**Comment by krasnh** [comment]
@seproDev, thanks for plvideo.

------------------------------------
I want to add a small clarification. In our region, the YouTube analogue is not one host, but split into several - mainly **_vk (vk video), dzen, rutube_**. Well, plus, the new one is still plvideo.

So, the loss of any one 'head' limits access to the desired video via yt-dlp. This is my eyeliner for the not yet closed https://github.com/yt-dlp/yt-dlp/pull/11908.  🙂

**Comment by communist1917** [comment]
> I want to add a small clarification. In our region, the YouTube analogue is not one host, but split into several - mainly **_vk (vkvideo), dzen, rutube_**. Well, plus, the new one is still plvideo.
> 
> So, the loss of any one 'head' limits access to the desired video via yt-dlp. This is my eyeliner for the not yet closed #11908. 🙂

Still I can't download from **dzen** with **yt-dlp**
![изображение](https://github.com/user-attachments/assets/611522c9-bbe0-42a7-abc6-3c4cf52372ab)
