### ISSUE TITLE
yt_dlp Python Download Error

### ISSUE THREAD

**Issue by bktubestamp** [yt-dlp/yt-dlp#10315]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Running latest yt_dlp library in Python3.12, suddenly getting this error. Never faced this issue before, and there has been no code changes. As you can see in the traceback, I am passing in a youtube link as a String list to ydl.download.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Traceback (most recent call last):
  File "/workspace/all_functions/getCaptionsPython.py", line 327, in run_ydl_get_captions
    ydl.download(['https://www.youtube.com/watch?v=KkCXLABwHP0'])
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3583, in download
    self.__download_wrapper(self.extract_info)(
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3558, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1595, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 732, in extract
    self.to_screen('Extracting URL: %s' % (
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1200, in to_screen
    self._downloader.to_screen(f'[{self.IE_NAME}] {msg}', *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 924, in to_screen
    self._write_string(
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 905, in _write_string
    write_string(message, out=out, encoding=self.params.get('encoding'))
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/utils/_utils.py", line 1441, in write_string
    buffer.write(s.encode(enc, 'ignore') if enc else s)
TypeError: string argument expected, got 'bytes'
```

**Comment by bashonly** [comment]
please provide a minimal reproducible example

**Comment by bktubestamp** [comment]
```
from yt_dlp import YoutubeDL

def download_using_ydl():        
    ydl_opts = {
        "writesubtitles": True,
        "writeautomaticsub": True,
        "subtitleslangs": ['en'],
        "skip_download": True,
        "outtmpl": f'/tmp/KkCXLABwHP0.txt'
    }

    with YoutubeDL(ydl_opts) as ydl:
        ydl.download(["https://www.youtube.com/watch?v=KkCXLABwHP0"])
    print("FINISHED DOWNLOAD")

download_using_ydl()``
```

**Comment by bashonly** [comment]
I can't reproduce the issue with that code:
```
[youtube] Extracting URL: https://www.youtube.com/watch?v=KkCXLABwHP0
[youtube] KkCXLABwHP0: Downloading webpage
[youtube] KkCXLABwHP0: Downloading ios player API JSON
[youtube] KkCXLABwHP0: Downloading m3u8 information
[info] KkCXLABwHP0: Downloading subtitles: en
[info] Testing format 616
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 107
[download] Destination: /tmp/tmpqshmsv4o.tmp
[download] 100% of    712.00B in 00:00:00 at 6.05KiB/s
[info] KkCXLABwHP0: Downloading 1 format(s): 616+251-13
[info] Writing video subtitles to: /tmp/KkCXLABwHP0.txt.en.vtt
[download] Destination: /tmp/KkCXLABwHP0.txt.en.vtt
[download] 100% of   17.94KiB in 00:00:00 at 373.31KiB/s
FINISHED DOWNLOAD
```

Please add `'verbose': True` to your `ydl_opts` and share the **complete** verbose output (beginning with `[debug] Encodings:` and ending with the traceback)

Are you running this script on a server/vps/cloud host? Can you reproduce it locally? Please give more details about the environment in which you are running the script

**Comment by bktubestamp** [comment]
I am running the script on a FIrebase Function. Issue is that I have two separate projects running this same script. One of the projects does not have this issuue, but the other does. Maybe I can share the dependency/package versions that are used?

I also tried to reproduce it locally but I could not. I will send the complete verbose output below.

**Comment by bashonly** [comment]
Need more info

> Maybe I can share the dependency/package versions that are used?

yes

**Comment by bktubestamp** [comment]
```
pip (24.1.1)
firebase_functions (0.4.1)
firebase_admin (6.5.0)
google-cloud-pubsub (2.21.3)
openai (1.34.0)
xmltodict (0.13.0)
youtube-transcript-api (0.6.2)
yt_dlp (2024.5.27)
brotli (1.1.0)
certifi (2024.6.2)
mutagen (1.47.0)
pycryptodomex (3.20.0)
requests<3,>=2.31.0 (2.32.3)
urllib3<3,>=1.26.17 (2.2.1)
websockets>=12.0 (12.0)
flask>=2.1.2 (3.0.3)
functions-framework>=3.0.0 (3.7.0)
pyyaml>=6.0 (6.0.1)
typing-extensions>=4.4.0 (4.12.2)
cloudevents==1.9.0 (1.9.0)
flask-cors>=3.0.10 (4.0.1)
pyjwt>=2.5.0 (2.8.0)
google-events>=0.5.0 (0.12.0)
google-cloud-firestore>=2.11.0 (2.16.0)
deprecation<3.0,>=2.0 (2.1.0)
cachecontrol>=0.12.6 (0.14.0)
google-api-python-client>=1.7.8 (2.133.0)
google-cloud-storage>=1.37.1 (2.17.0)
google-api-core<3.0.0dev,>=1.22.1 (1.64.1)
google-auth<3.0.0dev,>=2.14.1 (2.30.0)
proto-plus<2.0.0dev,>=1.22.0 (1.23.0)
protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 (4.25.3)
grpc-google-iam-v1<1.0.0dev,>=0.12.4 (0.13.0)
grpcio-status>=1.33.2 (1.62.2)
anyio<5,>=3.5.0 (4.4.0)
distro<2,>=1.7.0 (1.9.0)
httpx<1,>=0.23.0 (0.27.0)
pydantic<3,>=1.9.0 (2.7.4)
sniffio (1.3.1)
tqdm>4 (4.66.4)
idna>=2.8 (3.7)
msgpack<2.0.0,>=0.5.2 (1.0.8)
Werkzeug>=3.0.0 (3.0.3)
Jinja2>=3.1.2 (3.1.4)
itsdangerous>=2.1.2 (2.2.0)
click>=8.1.3 (8.1.7)
blinker>=1.6.2 (1.8.2)
watchdog>=1.0.0 (4.0.1)
gunicorn>=19.2.0 (22.0.0)
googleapis-common-protos<2.0.dev0,>=1.56.2 (1.63.1)
httplib2<1.dev0,>=0.19.0 (0.22.0)
google-auth-httplib2<1.0.0,>=0.2.0 (0.2.0)
uritemplate<5,>=3.0.1 (4.1.1)
cachetools<6.0,>=2.0.0 (5.3.3)
pyasn1-modules>=0.2.1 (0.4.0)
rsa<5,>=3.1.4 (4.9)
google-cloud-core<3.0.0dev,>=1.4.1 (2.4.1)
google-resumable-media>=2.6.0 (2.7.1)
google-crc32c<2.0dev,>=1.0 (1.5.0)
httpcore==1.* (1.0.5)
h11<0.15,>=0.13 (0.14.0)
annotated-types>=0.4.0 (0.7.0)
pydantic-core==2.18.4 (2.18.4)
cryptography>=3.4.0 (42.0.8)
charset-normalizer<4,>=2 (3.3.2)
cffi>=1.12 (1.16.0)
packaging (24.1)
pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 (3.1.2)
MarkupSafe>=2.0 (2.1.5)
pyasn1<0.7.0,>=0.4.6 (0.6.0)
pycparser (2.22)
```pip (24.1.1)
firebase_functions (0.4.1)
firebase_admin (6.5.0)
google-cloud-pubsub (2.21.3)
openai (1.34.0)
xmltodict (0.13.0)
youtube-transcript-api (0.6.2)
yt_dlp (2024.5.27)
brotli (1.1.0)
certifi (2024.6.2)
mutagen (1.47.0)
pycryptodomex (3.20.0)
requests<3,>=2.31.0 (2.32.3)
urllib3<3,>=1.26.17 (2.2.1)
websockets>=12.0 (12.0)
flask>=2.1.2 (3.0.3)
functions-framework>=3.0.0 (3.7.0)
pyyaml>=6.0 (6.0.1)
typing-extensions>=4.4.0 (4.12.2)
cloudevents==1.9.0 (1.9.0)
flask-cors>=3.0.10 (4.0.1)
pyjwt>=2.5.0 (2.8.0)
google-events>=0.5.0 (0.12.0)
google-cloud-firestore>=2.11.0 (2.16.0)
deprecation<3.0,>=2.0 (2.1.0)
cachecontrol>=0.12.6 (0.14.0)
google-api-python-client>=1.7.8 (2.133.0)
google-cloud-storage>=1.37.1 (2.17.0)
google-api-core<3.0.0dev,>=1.22.1 (1.64.1)
google-auth<3.0.0dev,>=2.14.1 (2.30.0)
proto-plus<2.0.0dev,>=1.22.0 (1.23.0)
protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 (4.25.3)
grpc-google-iam-v1<1.0.0dev,>=0.12.4 (0.13.0)
grpcio-status>=1.33.2 (1.62.2)
anyio<5,>=3.5.0 (4.4.0)
distro<2,>=1.7.0 (1.9.0)
httpx<1,>=0.23.0 (0.27.0)
pydantic<3,>=1.9.0 (2.7.4)
sniffio (1.3.1)
tqdm>4 (4.66.4)
idna>=2.8 (3.7)
msgpack<2.0.0,>=0.5.2 (1.0.8)
Werkzeug>=3.0.0 (3.0.3)
Jinja2>=3.1.2 (3.1.4)
itsdangerous>=2.1.2 (2.2.0)
click>=8.1.3 (8.1.7)
blinker>=1.6.2 (1.8.2)
watchdog>=1.0.0 (4.0.1)
gunicorn>=19.2.0 (22.0.0)
googleapis-common-protos<2.0.dev0,>=1.56.2 (1.63.1)
httplib2<1.dev0,>=0.19.0 (0.22.0)
google-auth-httplib2<1.0.0,>=0.2.0 (0.2.0)
uritemplate<5,>=3.0.1 (4.1.1)
cachetools<6.0,>=2.0.0 (5.3.3)
pyasn1-modules>=0.2.1 (0.4.0)
rsa<5,>=3.1.4 (4.9)
google-cloud-core<3.0.0dev,>=1.4.1 (2.4.1)
google-resumable-media>=2.6.0 (2.7.1)
google-crc32c<2.0dev,>=1.0 (1.5.0)
httpcore==1.* (1.0.5)
h11<0.15,>=0.13 (0.14.0)
annotated-types>=0.4.0 (0.7.0)
pydantic-core==2.18.4 (2.18.4)
cryptography>=3.4.0 (42.0.8)
charset-normalizer<4,>=2 (3.3.2)
cffi>=1.12 (1.16.0)
packaging (24.1)
pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 (3.1.2)
MarkupSafe>=2.0 (2.1.5)
pyasn1<0.7.0,>=0.4.6 (0.6.0)
pycparser (2.22)

**Comment by bktubestamp** [comment]
This issue keeps happening, every time. I tried re-downaloading all packages, re-deploying all functions on Firebase, etc, but nothing seems to fix it. I did suddenly see a different looking error though, with the traceback looking like this:

```
Traceback (most recent call last):
  File "/workspace/all_functions/getCaptionsPython.py", line 322, in run_ydl_get_captions
    with YoutubeDL(ydl_opts) as ydl:
         ^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 700, in __init__
    self.print_debug_header()
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3996, in print_debug_header
    write_string(f'[debug] {encoding_str}\n', encoding=None)
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/yt_dlp/utils/_utils.py", line 1441, in write_string
    buffer.write(s.encode(enc, 'ignore') if enc else s)
TypeError: string argument expected, got 'bytes'
```

**Comment by Grub4K** [comment]
The problem is that googles shim has a `buffer` property which takes string as an argument though. So we see `buffer`, think it must be binary and start writing `bytes` to it eventhough it expects `str`

This will be fixed by the output rework, whevever that happens. It will remove the `write_string` function in favor of a dedicated output stream which will test the arguments beforehand.

A possible workaround with bigger implications would be to cache the mode by writing to it an empty string, and just looking up the buffer objects in a cached dictionary. I think ive presented this before, but i cant seem to find it.

---
It could help if you could show the output of this, as ran by the firebase function:
```python
print(f"{sys.stdout        = }")
print(f"{sys.stderr        = }")
print(f"{sys.stdout.buffer = }")
print(f"{sys.stderr.buffer = }")
```

**Comment by bktubestamp** [comment]
```
sys.stdout = <_io.TextIOWrapper encoding='UTF-8'>
sys.stderr = <_io.TextIOWrapper encoding='UTF-8'>
sys.stdout.buffer = <_io.StringIO object at 0x3e8a23356740>
sys.stderr.buffer = <_io.StringIO object at 0x3e8a23356bc0>
```

^ This is what was printed as a result, I inserted the print statements before the ydl gets called.

**Comment by Grub4K** [comment]
This will be harder to fix on the yt-dlp site. The easiest would be [use a custom logger](<https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#adding-logger-and-progress-hook>), then write to `sys.stdout` and `sys.stderr`. That way you work around the `write_string` limitation.

Alternatively you could replace `sys.stdout` and `sys.stderr` with a wrapper object that writes to the google provided one. That way the `buffer` property will not be detected by `write_string` and will write a string.

---
I will try and come up with a yt-dlp workaround, but it will probably have to wait for output rework

**Comment by dirkf** [comment]
Somewhat related: #8816

**Comment by bktubestamp** [comment]
Great news, adding the custom logger and just calling the Firebase logger as such fixed the issue. Thank you for the support!

```
from firebase_functions import logger

class MyLogger:
    def debug(self, msg):
        # For compatibility with youtube-dl, both debug and info are passed into debug
        # You can distinguish them by the prefix '[debug] '
        if msg.startswith('[debug] '):
            logger.debug(msg)
        else:
            self.info(msg)

    def info(self, msg):
        logger.log(msg)

    def warning(self, msg):
        logger.warn(msg)

    def error(self, msg):
        logger.error(msg)
```

**Comment by MoAfshar** [comment]
I ran into the same issue using Cloud Functions on GCP, @bktubestamp solution worked well here's my snippet for general cloud functions

```python
import yt_dlp
import logging 

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class MyLogger:
    def debug(self, msg):
        if msg.startswith('[debug] '):
            logger.debug(msg)
        else:
            self.info(msg)

    def info(self, msg):
        logger.info(msg)

    def warning(self, msg):
        logger.warning(msg)

    def error(self, msg):
        logger.error(msg)

def yt_dlp_download(url: str, ydl_opts: dict):
    """Download media using yt-dlp and save it to a local file."""
    try:
        ydl_opts['logger'] = MyLogger()
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])
    except Exception as e:
        print(f"Error in yt_dlp_download: {str(e)}")
        raise
```

**Comment by be-nny** [comment]
I had a the same issue when deploying to a cloud function but changing my python version from 3.12 to 3.11 seemed to work. it seems the `write_string()` method is a bug with python version 3.12

**Comment by yccheok** [comment]
I have confirmed this happens in Firebase function, but not re-producible in my local machine.

**Comment by dominicdev** [comment]
is there a fix to this? until now im getting this error randomly in google function
