### ISSUE TITLE
DownloadError: ERROR: [vimeo]: Got HTTP Error 403. If you are using a data center IP or VPN/proxy, your IP may be blocked

### ISSUE THREAD

**Issue by SasaniP** [yt-dlp/yt-dlp#10340]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Sri Lanka

### Provide a description that is worded well enough to be understood

I'm opening this issue after trying to get a solution from issue #5459 but the conversation is limited.

I am using the yt_dlp-2024.7.1-py3-none-any.whl (3.1 MB). 
I am trying to download formats, `worstvideo+worstaudio` and `bestvideo+bestaudio`. the issue is not in any of these formats.

```
yt_dlp_options_worst = {
        "videopassword": password,
        "verbose": True,
        "format": "worstvideo+worstaudio",
        "referer": "https://vimeo.com",
        "external_downloader": "aria2c",
        "external_downloader_args": ["-x", "16", "-s", "16", "-k", "5M", "--max-concurrent-downloads=16"],
        "outtmpl": os.path.join(destination_folder, "%(title)s (%(format_id)s).%(ext)s"),
        "writeinfojson": True,
        "nooverwrites": True,
        "tempdir": tempfile.gettempdir()
    }

    yt_dlp_options_best = {
        "videopassword": password,
        "verbose": True,
        "format": "bestvideo+bestaudio",
        "referer": "https://vimeo.com",
        "external_downloader": "aria2c",
        "external_downloader_args": ["-x", "16", "-s", "16", "-k", "5M", "--max-concurrent-downloads=16"],
        "outtmpl": os.path.join(destination_folder, "%(title)s (%(format_id)s).%(ext)s"),
        "writeinfojson": True,
        "nooverwrites": True,
        "tempdir": tempfile.gettempdir()
    }
```

Before the download is even started, `HTTPError 403: Forbidden` is thrown. I am trying to download the following Vimeo video. And the video is playable in the private tab in chrome.
You can reproduce this error.  `Link: http://vimeo.com/587512620` with the `Password: 123`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (pip) API
[debug] params: {'videopassword': '123', 'verbose': True, 'format': 'worstvideo+worstaudio', 'referer': 'https://vimeo.com/', 'external_downloader': 'aria2c', 'external_downloader_args': ['-x', '16', '-s', '16', '-k', '5M', '--max-concurrent-downloads=16'], 'outtmpl': '/content/output_video_path/%(title)s (%(format_id)s).%(ext)s', 'writeinfojson': True, 'nooverwrites': True, 'tempdir': '/tmp', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.1.85+-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {'colab_language_server': '/usr/colab/bin/language_service'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
[vimeo] Extracting URL: http://vimeo.com/587512620?share=copy
[vimeo] 587512620: Downloading webpage
ERROR: [vimeo] 587512620: Got HTTP Error 403. If you are using a data center IP or VPN/proxy, your IP may be blocked
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/vimeo.py", line 853, in _real_extract
    raise ExtractorError(f'Got HTTP Error {status}. {dcip_msg}', expected=True)

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (pip) API
[debug] params: {'videopassword': '123', 'verbose': True, 'format': 'bestvideo+bestaudio', 'referer': 'https://vimeo.com/', 'external_downloader': 'aria2c', 'external_downloader_args': ['-x', '16', '-s', '16', '-k', '5M', '--max-concurrent-downloads=16'], 'outtmpl': '/content/output_video_path/%(title)s (%(format_id)s).%(ext)s', 'writeinfojson': True, 'nooverwrites': True, 'tempdir': '/tmp', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.1.85+-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {'colab_language_server': '/usr/colab/bin/language_service'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
Error downloading in worst video http://vimeo.com/587512620?share=copy
Video Downloading in best quality
[vimeo] Extracting URL: http://vimeo.com/587512620?share=copy
[vimeo] 587512620: Downloading webpage
ERROR: [vimeo] 587512620: Got HTTP Error 403. If you are using a data center IP or VPN/proxy, your IP may be blocked
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/vimeo.py", line 853, in _real_extract
    raise ExtractorError(f'Got HTTP Error {status}. {dcip_msg}', expected=True)

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py](https://localhost:8080/#) in _request_webpage(self, url_or_request, video_id, note, errnote, fatal, data, headers, query, expected_status, impersonate, require_impersonation)
    895         try:
--> 896             return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
    897         except network_exceptions as err:

39 frames
HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

ExtractorError                            Traceback (most recent call last)
ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

During handling of the above exception, another exception occurred:

ExtractorError                            Traceback (most recent call last)
ExtractorError: [vimeo] 587512620: Got HTTP Error 403. If you are using a data center IP or VPN/proxy, your IP may be blocked

During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)
DownloadError: ERROR: [vimeo] 587512620: Got HTTP Error 403. If you are using a data center IP or VPN/proxy, your IP may be blocked

During handling of the above exception, another exception occurred:

HTTPError                                 Traceback (most recent call last)
HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

ExtractorError                            Traceback (most recent call last)
ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

During handling of the above exception, another exception occurred:

ExtractorError                            Traceback (most recent call last)
ExtractorError: [vimeo] 587512620: Got HTTP Error 403. If you are using a data center IP or VPN/proxy, your IP may be blocked

During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py](https://localhost:8080/#) in trouble(self, message, tb, is_error)
   1025             else:
   1026                 exc_info = sys.exc_info()
-> 1027             raise DownloadError(message, exc_info)
   1028         self._download_retcode = 1
   1029 

DownloadError: ERROR: [vimeo] 587512620: Got HTTP Error 403. If you are using a data center IP or VPN/proxy, your IP may be blocked
```

**Comment by bashonly** [comment]
> [debug] Proxy map: {'colab_language_server': '/usr/colab/bin/language_service'}

You're running this on google colab?

If yes, then this is self-explanatory, no?

> If you are using a data center IP or VPN/proxy, your IP may be blocked

**Comment by SasaniP** [comment]
That makes sense. I have previously download many videos using AWS and Google Colab, and only recently (May 2024) this issue began.

I have run this code locally, and produced `HTTPError 400: Bad Request` error.

`yt_dlp.utils.DownloadError: ERROR: [vimeo] 587512620: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)`

 I shall move on to this issue. Thanks.

**Comment by bashonly** [comment]
See #6603 for workarounds and discussion
