### ISSUE TITLE
Not able to download videos from YouTube, errors show up every now and then

### ISSUE THREAD

**Issue by bondeabhijeet** [yt-dlp/yt-dlp#10350]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

Im trying to download a simple youtube video but the following error keeps showing up:

I have also ensured that I have the latest version.

The Command I'm trying to run is:
`!yt-dlp "https://www.youtube.com/watch?v=pgTBc_x069Y" --extractor-args youtube:player_client=android --throttled-rate 100K`
### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] 4MoYSpE05Ec: Downloading webpage
[youtube] 4MoYSpE05Ec: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] 4MoYSpE05Ec: Downloading android player API JSON (retry #1)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] 4MoYSpE05Ec: Downloading android player API JSON (retry #2)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] 4MoYSpE05Ec: Downloading android player API JSON (retry #3)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = PoCcScll_HJN1V1Rc49 ; player = https://www.youtube.com/s/player/5352eb4f/player_ias.vflset/en_US/base.js
4MoYSpE05Ec: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2519, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2551, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 536, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 256, in interpret_expression
    self.interpret_expression(sub_expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 277, in interpret_expression
    right_val = self.interpret_expression(m.group('expr'), local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 171, in interpret_expression
    name = self._named_object(local_vars, [
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 172, in <listcomp>
    self.interpret_expression(item, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 464, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
yt_dlp.utils.ExtractorError: Unsupported JS expression '"'; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by ExtractorError('Unsupported JS expression \'"\'; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = XNm5Srf7jf0qpSGMCod ; player = https://www.youtube.com/s/player/5352eb4f/player_ias.vflset/en_US/base.js
4MoYSpE05Ec: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2519, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2551, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 536, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 256, in interpret_expression
    self.interpret_expression(sub_expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 277, in interpret_expression
    right_val = self.interpret_expression(m.group('expr'), local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 171, in interpret_expression
    name = self._named_object(local_vars, [
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 172, in <listcomp>
    self.interpret_expression(item, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 464, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
yt_dlp.utils.ExtractorError: Unsupported JS expression '"'; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by ExtractorError('Unsupported JS expression \'"\'; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] 4MoYSpE05Ec: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by seproDev** [comment]
Do not use `--extractor-args youtube:player_client=android`. The android client no longer works due to YouTube adding server-side attestation.
You also seem to be using a very old version of yt-dlp. Please update and if it still doesn't work, share a complete (and not cut off) verbose log.

**Comment by bondeabhijeet** [comment]
Thanks, it was totally my fault and I admit it.

Thanks for the help <3
