### ISSUE TITLE
[FranceTV] Allow extraction of whole season/series

### ISSUE THREAD

**Issue by thuttinpasseron** [yt-dlp/yt-dlp#10353]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Example URLs

https://www.france.tv/france-2/dix-pour-cent/
https://www.france.tv/france-3/wakfu/saison-1/

### Provide a description that is worded well enough to be understood

The given URLs point to complete show or complete season pages where all corresponding videos can then be accessed. I'm perfectly aware that I can paste each video's URL and `yt-dlp` will download each of them, but it would be easier to simply paste one URL instead of a few dozens.

Should this feature request be considered, I would be able to provide some code to implement it.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.france.tv/france-3/wakfu/saison-1/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.07.03.223542 from yt-dlp/yt-dlp-master-builds [6075a029d] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.9.5-200.fc40.x86_64-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Crypto-broken 2.6.1, certifi-2024.06.02, curl_cffi-0.6.4 (unsupported), requests-2.31.0, sqlite3-3.45.1, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.07.03.223542 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.07.03.223542 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://www.france.tv/france-3/wakfu/saison-1/
[generic] saison-1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] saison-1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.france.tv/france-3/wakfu/saison-1/
Traceback (most recent call last):
  File "/home/silver/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/silver/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1757, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/silver/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/silver/.local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2521, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.france.tv/france-3/wakfu/saison-1/
```

**Comment by bashonly** [comment]
> I would be able to provide some code to implement it.

Feel free to open a PR
