### ISSUE TITLE
Rule34Video Bulk Download

### ISSUE THREAD

**Issue by keboto** [yt-dlp/yt-dlp#10364]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Example URLs

Profile:
https://rule34video.com/models/aphy3d/

Search:
https://rule34video.com/search/SFM/

### Provide a description that is worded well enough to be understood

When downloading videos, there’s no issue. However, when attempting to download an entire profile, it doesn’t work. For instance, on platforms like Pornhub, you can download the entire site by navigating to the last page of search results and copying the link, which then downloads all the videos.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://rule34video.com/search/SFM/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.03.232825 from yt-dlp/yt-dlp-nightly-builds [6075a029d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.03.232825 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.03.232825 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://rule34video.com/search/SFM/
[generic] SFM: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] SFM: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://rule34video.com/search/SFM/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1622, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1757, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2521, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://rule34video.com/search/SFM/
```

**Comment by Chr0nicallyT1red** [comment]
Im definitely in support of this, as its functionality I'd really like to have.

I would like to add though, that the provided profile URL: `https://rule34video.com/models/aphy3d/` is specifically an artist profile, which is different from a user profile, which are also used to upload videos

So a technically more "better" / "correct" list would be:

> ### Example URLs
> Artist Profile:
> https://rule34video.com/models/aphy3d/
> 
> User Profile:
> https://rule34video.com/members/98965/
> 
> Search:
> https://rule34video.com/search/SFM/

This is in no way meant as criticism, just something I wanted to point out :)

**Comment by ForxBase** [comment]
Im definitely in support of this, too! Would like to just need the user or tag link to download everything without having to copy each link

https://rule34video.com/categories/mugen/
