### ISSUE TITLE
Receive `ERROR: unable to download video data: HTTP Error 403: Forbidden` only when `ffmpeg` installed

### ISSUE THREAD

**Issue by alex-ibb** [yt-dlp/yt-dlp#10377]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

OS: `Ubuntu 24.04 LTS 64` (Running on a VM on Vultra cloud @ Los Angeles)
The Error: `yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden` (Please ref the `Complete Verbose Output` below)
Steps to replicate the error:
 - Initialize a VM on the cloud, and login in as user `ubuntu`
 - Install `ubuntu-desktop` via `apt` and reboot
 - Open `firefox` and login in to `youtube.com` via remote console
 - Open `https://www.youtube.com/watch?v=sWbUDq4S6Y8` and watch by opening an new table on the `firefox`
 - Download the tools `yt-dlp` and the `ffmpeg` tool-set from the links below and add them to `PATH` (`~/.bashrc`):
    -- https://github.com/yt-dlp/yt-dlp/releases/download/2024.07.02/yt-dlp
    -- https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.0-latest-linux64-gpl-7.0.tar.xz
   Followed by update `yt-dlp` to the `nightly` version.
 - Connect to the VM via `ssh` and execute the command `yt-dlp https://www.youtube.com/watch?v=sWbUDq4S6Y8 --cookies-from-browser firefox -v`

Them, it will print the `Complete Verbose Output`.

However, if remove the `ffmpeg`, it will download the video with very low quality.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=ogOmQ86y0es', '--cookies-from-browser', 'firefox', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.06.232701 from yt-dlp/yt-dlp-nightly-builds [4862a2985] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-36-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg n7.0.1-20-g2df8aaa8c5-20240707 (setts), ffprobe n7.0.1-20-g2df8aaa8c5-20240707
[debug] Optional libraries: certifi-2023.11.17, requests-2.31.0, sqlite3-3.45.1, urllib3-2.0.7
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/ubuntu/snap/firefox/common/.mozilla/firefox/8vyoay9l.default/cookies.sqlite"
Extracted 46 cookies from firefox
[debug] Request Handlers: urllib
[debug] Loaded 1832 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=ogOmQ86y0es
[youtube] ogOmQ86y0es: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] ogOmQ86y0es: Downloading ios player API JSON
[debug] Loading youtube-nsig.5352eb4f from cache
[debug] [youtube] Decrypted nsig gHaFrFKY5BSdE5Oyrlm => lb6pj2McTpgdag
[debug] Loading youtube-nsig.5352eb4f from cache
[debug] [youtube] Decrypted nsig SkmSyYPGJfZi93Ly3C_ => 2lvo7ZuTfmlwhw
[youtube] ogOmQ86y0es: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ogOmQ86y0es: Downloading 1 format(s): 303+251
[debug] Invoking http downloader on "https://rr1---sn-a5msenek.googlevideo.com/videoplayback?expire=1720386193&ei=Ma6KZpT9JbexsfIPxcqS2Ag&ip=2001%3A19f0%3A6001%3A496d%3A5400%3A5ff%3Afe01%3Adb68&id=o-AOh5GMpOoCa0c-d4JBLyyS3i3-<Deleted-by-poster>&itag=303&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Zc&mm=31%2C26&mn=sn-a5msenek%2Csn-n4v7snls&ms=au%2Conr&mv=m&mvi=1&pl=38&initcwndbps=302500&siu=1&bui=<Deleted-by-poster>-7di3mxQ&spc=<Deleted-by-poster>&vprv=1&svpuc=1&mime=video%2Fwebm&ns=n-nbfOnBRjNz_7D-bk1tXq0Q&rqh=1&gir=yes&clen=2061243156&dur=19001.216&lmt=1703250286450204&mt=1720364256&fvip=2&keepalive=yes&c=WEB&sefc=1&txp=5437434&n=2lvo7ZuTfmlwhw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=<Deleted-by-poster>-lvTsP-vhw8iRqDSdcGxUT_NemCM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=<Deleted-by-poster>-<Deleted-by-poster>-<Deleted-by-poster>"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3461, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3199, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4161, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

```

**Comment by bashonly** [comment]
Without ffmpeg you are most likely downloading format 18. This is a legacy format that isn't guarded by some of the restrictions of the rest of the formats (such as 303 and 251). You are getting 403'd with the non-legacy formats most likely because your account has been flagged for automated tool usage. See #10046
