### ISSUE TITLE
Add support for Footballia.eu

### ISSUE THREAD

**Issue by Edwinhr716** [yt-dlp/yt-dlp#10374]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Global

### Example URLs

Single video: https://footballia.eu/matches/west-bromwich-albion-preston-north-end

### Provide a description that is worded well enough to be understood

The website requires login information. I was able to find the link in the `<video x-webkit-airplay="allow" src="https://videos.footballia.net/uploads/video/source_file/46/1953-54_Preston_-_WBA_-_FA_Cup-Final_00_00_23-.mp4"></video>` tag, so could potentially be extracted from there.

The website pages do not make it clear that a video is playing, but after logging in the video player is made accessible. The website uses this player https://jwplayer.com/ to embed the video. 

I was also able to download the video using the link present in the `<video>` tag, so it is possible to download. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://footballia.eu/matches/west-bromwich-albion-preston-north-end', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-28-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://footballia.eu/matches/west-bromwich-albion-preston-north-end
[generic] west-bromwich-albion-preston-north-end: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] west-bromwich-albion-preston-north-end: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://footballia.eu/matches/west-bromwich-albion-preston-north-end
Traceback (most recent call last):
  File "/home/edwin/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
  File "/home/edwin/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1757, in __extract_info
    ie_result = ie.extract(url)
  File "/home/edwin/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/edwin/.local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2521, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://footballia.eu/matches/west-bromwich-albion-preston-north-end
```

**Comment by bashonly** [comment]
Can you add another log where you try [passing cookies to yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) instead of `--username` and `--password`

**Comment by Edwinhr716** [comment]
``` 
[debug] Command-line config: ['--cookies-from-browser', 'chrome', 'https://footballia.eu/matches/west-bromwich-albion-preston-north-end', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-12.3.1-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/edwinhernandez/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
Extracted 2591 cookies from chrome
[debug] cookie version breakdown: {'v10': 2606, 'other': 0, 'unencrypted': 13}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://footballia.eu/matches/west-bromwich-albion-preston-north-end
[generic] west-bromwich-albion-preston-north-end: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] west-bromwich-albion-preston-north-end: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://footballia.eu/matches/west-bromwich-albion-preston-north-end
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.2/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.2/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1757, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.2/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.2/libexec/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2521, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://footballia.eu/matches/west-bromwich-albion-preston-north-end
```

**Comment by oneingan** [comment]
some time later and same error:

```
[debug] Command-line config: ['--cookies', './Downloads/cookies.firefox-private.txt', '-vU', 'https://footballia.eu/matches/west-bromwich-albion-preston-north-end']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.12.08 from yt-dlp/yt-dlp [7a52ff29d]
[debug] Python 3.13.11 (CPython x86_64 64bit) - Linux-6.18.2-x86_64-with-glibc2.40 (OpenSSL 3.6.0 1 Oct 2025, glibc 2.40)
[debug] exe versions: ffmpeg 8.0 (setts), ffprobe 8.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.2.0, certifi-2025.07.14, curl_cffi-0.14.0, mutagen-1.47.0, requests-2.32.5, secretstorage-3.3.3, sqlite3-3.51.1, urllib3-2.6.0, websockets-15.0.1, yt_dlp_ejs-0.3.2
[debug] JS runtimes: deno-2.6.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1854 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.12.08 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.12.08 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://footballia.eu/matches/west-bromwich-albion-preston-north-end
[generic] west-bromwich-albion-preston-north-end: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] west-bromwich-albion-preston-north-end: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://footballia.eu/matches/west-bromwich-albion-preston-north-end
Traceback (most recent call last):
  File "/nix/store/dglq5kjkh039cwmnraf28wizqch9bkiq-yt-dlp-2025.12.08/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1696, in wrapper
    return func(self, *args, **kwargs)
  File "/nix/store/dglq5kjkh039cwmnraf28wizqch9bkiq-yt-dlp-2025.12.08/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1831, in __extract_info
    ie_result = ie.extract(url)
  File "/nix/store/dglq5kjkh039cwmnraf28wizqch9bkiq-yt-dlp-2025.12.08/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 762, in extract
    ie_result = self._real_extract(url)
  File "/nix/store/dglq5kjkh039cwmnraf28wizqch9bkiq-yt-dlp-2025.12.08/lib/python3.13/site-packages/yt_dlp/extractor/generic.py", line 980, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://footballia.eu/matches/west-bromwich-albion-preston-north-end
```
