### ISSUE TITLE
Error on vk.com video

### ISSUE THREAD

**Issue by Tizioincognit0** [yt-dlp/yt-dlp#10387]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Provide a description that is worded well enough to be understood

Hi, when I'm trying to download [this video](https://vk.com/video-45245403_163660666), I get the following error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://vk.com/video-45245403_163660666', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.07 from yt-dlp/yt-dlp [b337d2989] (darwin_exe)
[debug] Python 3.12.4 (CPython x86_64 64bit) - macOS-14.5-x86_64-i386-64bit (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.07 from yt-dlp/yt-dlp)
[vk] Extracting URL: https://vk.com/video-45245403_163660666
[vk] -45245403_163660666: Downloading JSON metadata
ERROR: string indices must be integers, not 'str'
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1622, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1757, in __extract_info
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vk.py", line 439, in _real_extract
TypeError: string indices must be integers, not 'str'
```

**Comment by seproDev** [comment]
Does the video play for you in your browser? For me, it just keeps loading.

**Comment by Tizioincognit0** [comment]
> Does the video play for you in your browser? For me, it just keeps loading.

For me too but I think this can still be considered an issue because the error message is ambiguous. It should be something like "Video unavailable".

**Comment by bashonly** [comment]
> - [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details

Do not lie when filling out the checklist. If the video doesn't play in browser, this is important information to mention in the original post of the issue

**Comment by bashonly** [comment]
Here's a patch to handle vk pages like this, but I don't know how useful it is since the video still can't be downloaded (possibly due to geo-restriction?):

```diff
diff --git a/yt_dlp/extractor/vk.py b/yt_dlp/extractor/vk.py
index 6ccc701a2..1511ac03b 100644
--- a/yt_dlp/extractor/vk.py
+++ b/yt_dlp/extractor/vk.py
@@ -436,6 +436,12 @@ def _real_extract(self, url):
                 return self.url_result(opts_url)
 
         data = player['params'][0]
+
+        if isinstance(data, str):
+            redirect_url = self._proto_relative_url(data)
+            if url_or_none(redirect_url) and not self.suitable(redirect_url):
+                return self.url_result(redirect_url)
+
         title = unescapeHTML(data['md_title'])
 
         # 2 = live
```

**Comment by Tizioincognit0** [comment]
> > * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> 
> Do not lie when filling out the checklist. If the video doesn't play in browser, this is important information to mention in the original post of the issue

Actually I was able to play the video in the moment I opened this issue. Anyway I changed it.
