### ISSUE TITLE
[Broken] cbsnews face the nation

### ISSUE THREAD

**Issue by mindbomb** [yt-dlp/yt-dlp#1039]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running yt-dlp version **2021.09.02**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
With old FFMPEG:
C:\WINDOWS\system32>yt-dlp https://www.cbsnews.com/video/919-collins-gottlieb-sanders/ -v
[debug] User config file: C:\Users\xstre\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['--output', 'F:\\Chrome Downloads\\%(title)s.%(ext)s', '--format-sort', '+vcodec:h264', '--ffmpeg-location', 'C:\\Program Files\\yt-dlp']
[debug] Command-line config: ['https://www.cbsnews.com/video/919-collins-gottlieb-sanders/', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [cbsnews] Extracting URL: https://www.cbsnews.com/video/919-collins-gottlieb-sanders/
[cbsnews] 919-collins-gottlieb-sanders: Downloading webpage
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading XML
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading JSON metadata
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading StreamPack SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading m3u8 information
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading HLS_CLEAR SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading m3u8 information
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading Downloadable SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Checking video URL
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading PDL_MP4 SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Checking video URL
[debug] Sort order given by user: +vcodec:h264
[debug] Formats sorted by: hasvid, ie_pref, +vcodec:h264(7), lang, quality, res, fps, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading 1 format(s): hls-3172+hls-95
[debug] Invoking downloader on "https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2021/09/07/1943091267888/795950_hls/0919_FTN_Full_795950_3000/stream.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 462
[download] Destination: F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-3172.mp4
[download] 100% of 998.21MiB in 02:12
[debug] Invoking downloader on "https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/07/1943091267888/0919_FTN_Full_795958_,2228,4628,3128,1628,848,503,000.mp4.csmil/index_5_a.m3u8?null=0&id=AgBg73mPFyyECYKOSGFJu1CKXnPYme+RmyHT2ZAESThQV2%2fkImrFVtY62zRVD368nKz5tZU04uFBcA%3d%3d&hdntl=exp=1632231426~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2021%2f09%2f07%2f1943091267888%2f0919_FTN_Full_795958_*~data=hdntl~hmac=220aae5744da470ff67979fd487eeb21cbd7ec1996db18244c1d63f999a17b18"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 275
[download] Destination: F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-95.mp4
[download] 100% of 38.99MiB in 00:24
[Merger] Merging formats into "F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.mp4"
[debug] ffmpeg command line: "C:\Program Files\yt-dlp\ffmpeg" -y -loglevel "repeat+info" -i "file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-3172.mp4" -i "file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-95.mp4" -c copy -map "0:v:0" -map "1:a:0" "file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.temp.mp4"
ERROR: ffmpeg version 3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mpegts, from 'file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-3172.mp4':
  Duration: 00:45:54.08, start: 0.100000, bitrate: 3040 kb/s
  Program 1
    Stream #0:0[0x50]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
[mjpeg @ 0000020858dfc240] Changing bps to 8
[aac @ 0000020859913820] Estimating duration from bitrate, this may be inaccurate
Input #1, aac, from 'file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-95.mp4':
  Duration: 00:57:38.55, bitrate: 94 kb/s
    Stream #1:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 94 kb/s
    Stream #1:1: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 576x432 [SAR 72:72 DAR 4:3], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Movie/video screen capture
Output #0, mp4, to 'file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.temp.mp4':
  Metadata:
    encoder         : Lavf57.25.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 94 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 00000208599084e0] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Operation not permitted
frame=    4 fps=0.0 q=-1.0 Lsize=     136kB time=00:00:00.03 bitrate=33468.5kbits/s speed=22.3x
video:136kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.445260%
Conversion failed!
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 776, in main
  File "yt_dlp\__init__.py", line 766, in _real_main
  File "yt_dlp\YoutubeDL.py", line 2894, in download
  File "yt_dlp\YoutubeDL.py", line 1207, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1214, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1252, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1298, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2320, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2864, in process_info
  File "yt_dlp\YoutubeDL.py", line 3015, in post_process
  File "yt_dlp\YoutubeDL.py", line 2964, in run_pp
  File "yt_dlp\postprocessor\common.py", line 83, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 717, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 237, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 274, in real_run_ffmpeg
  File "yt_dlp\postprocessor\common.py", line 56, in report_error
  File "yt_dlp\YoutubeDL.py", line 818, in report_error
  File "yt_dlp\YoutubeDL.py", line 774, in trouble

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2864, in process_info
  File "yt_dlp\YoutubeDL.py", line 3015, in post_process
  File "yt_dlp\YoutubeDL.py", line 2964, in run_pp
  File "yt_dlp\postprocessor\common.py", line 83, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 717, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 237, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 275, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

With New FFMPEG:
C:\WINDOWS\system32>yt-dlp https://www.cbsnews.com/video/919-collins-gottlieb-sanders/ -v
[debug] User config file: C:\Users\xstre\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['--output', 'F:\\Chrome Downloads\\%(title)s.%(ext)s', '--format-sort', '+vcodec:h264', '--ffmpeg-location', 'C:\\Program Files\\yt-dlp']
[debug] Command-line config: ['https://www.cbsnews.com/video/919-collins-gottlieb-sanders/', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-09-20-git-59719a905c-full_build-www.gyan.dev, ffprobe 2021-09-20-git-59719a905c-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [cbsnews] Extracting URL: https://www.cbsnews.com/video/919-collins-gottlieb-sanders/
[cbsnews] 919-collins-gottlieb-sanders: Downloading webpage
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading XML
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading JSON metadata
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading StreamPack SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading m3u8 information
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading HLS_CLEAR SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading m3u8 information
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading Downloadable SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Checking video URL
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading PDL_MP4 SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Checking video URL
[debug] Sort order given by user: +vcodec:h264
[debug] Formats sorted by: hasvid, ie_pref, +vcodec:h264(7), lang, quality, res, fps, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading 1 format(s): hls-3172+hls-95
[debug] Invoking downloader on "https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2021/09/07/1943091267888/795950_hls/0919_FTN_Full_795950_3000/stream.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 462
[download] Destination: F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-3172.mp4
[download] 100% of 998.21MiB in 01:58
[debug] Invoking downloader on "https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/07/1943091267888/0919_FTN_Full_795958_,2228,4628,3128,1628,848,503,000.mp4.csmil/index_5_a.m3u8?null=0&id=AgBg73mPFyyEJ0CSSGEfbA5+qnFEwK1iYUKjRzz7v8PoBn28cC1K2Qc0THB84lC1VeusCXj+em5wLg%3d%3d&hdntl=exp=1632232384~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2021%2f09%2f07%2f1943091267888%2f0919_FTN_Full_795958_*~data=hdntl~hmac=9b2a3666b3cee77c93f00244a4548a4fcb5590df1c00c56c0f39d48aeff7e991"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 275
[download] Destination: F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-95.mp4
[download] 100% of 38.99MiB in 00:20
[Merger] Merging formats into "F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.mp4"
[debug] ffmpeg command line: "C:\Program Files\yt-dlp\ffmpeg" -y -loglevel "repeat+info" -i "file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-3172.mp4" -i "file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-95.mp4" -c copy -map "0:v:0" -map "1:a:0" "file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.temp.mp4"
Deleting original file F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-95.mp4 (pass -k to keep)
Deleting original file F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.fhls-3172.mp4 (pass -k to keep)
[debug] ffmpeg command line: "C:\Program Files\yt-dlp\ffprobe" -show_streams "file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.mp4"
[debug] ffmpeg command line: "C:\Program Files\yt-dlp\ffmpeg" -y -loglevel "repeat+info" -i "file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:F:\Chrome Downloads\9_19 - Collins, Gottlieb, Sanders.temp.mp4"





```

## Description

An issue with this series was previously reported here, https://github.com/yt-dlp/yt-dlp/issues/618,  and downgrading to ffmpeg 3.01 worked for older episodes, but now it results in postprocessing failed. The other thread also mentioned that the latest ffmpeg should work, but that results in a video that eventually becomes unplayable at 5m40s. I've put both logs up. If the issue is with muxing to an mp4 container, I'm wondering if the solution could be to mux to mkv if there are problems detected with the aac audio.

**Comment by Ashish0804** [comment]
Works for me mate
```
C:\Users\Ashish\Desktop> yt-dlp https://www.cbsnews.com/video/919-collins-gottlieb-sanders/ -v
[debug] Command-line config: ['https://www.cbsnews.com/video/919-collins-gottlieb-sanders/', '-v']
[debug] yt-dlp version 2021.09.02
[debug] Python version 3.8.8 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1
[debug] Optional libraries: keyring, mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [cbsnews] Extracting URL: https://www.cbsnews.com/video/919-collins-gottlieb-sanders/
[cbsnews] 919-collins-gottlieb-sanders: Downloading webpage
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading XML
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading JSON metadata
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading StreamPack SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading m3u8 information
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading HLS_CLEAR SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading m3u8 information
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading Downloadable SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Checking video URL
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading PDL_MP4 SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Checking video URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading 1 format(s): hls-3172+hls-95
[debug] Invoking downloader on "https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2021/09/07/1943091267888/795950_hls/0919_FTN_Full_795950_3000/stream.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 462
[download] Destination: 9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].fhls-3172.mp4
[download]   0.9% of ~977.48MiB at  1.72MiB/s ETA 13:46
ERROR: Interrupted by user
C:\Users\Ashish\Desktop> yt-dlp https://www.cbsnews.com/video/919-collins-gottlieb-sanders/ -v --downloader aria2c
[debug] Command-line config: ['https://www.cbsnews.com/video/919-collins-gottlieb-sanders/', '-v', '--downloader', 'aria2c']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02
[debug] Python version 3.8.8 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1
[debug] Optional libraries: keyring, mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [cbsnews] Extracting URL: https://www.cbsnews.com/video/919-collins-gottlieb-sanders/
[cbsnews] 919-collins-gottlieb-sanders: Downloading webpage
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading XML
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading JSON metadata
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading StreamPack SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading m3u8 information
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading HLS_CLEAR SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading m3u8 information
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading Downloadable SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Checking video URL
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading PDL_MP4 SMIL data
[cbsnews] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Checking video URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L: Downloading 1 format(s): hls-3172+hls-95
[debug] Invoking downloader on "https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2021/09/07/1943091267888/795950_hls/0919_FTN_Full_795950_3000/stream.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 462
[download] Destination: 9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].fhls-3172.mp4
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--file-allocation=none" -x16 -j16 -s16 "--allow-overwrite=true" "--allow-piece-length-change=true" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3704.7 Safari/537.36" --header "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Encoding: gzip, deflate" --header "Accept-Language: en-us,en;q=0.5" --header "Cookie: fly_device=desktop; fly_geo={\"countryCode\": \"IN\", \"region\": \"HR\", \"dma\": \"356001\", \"connection\": { \"type\": \"broadband\"}}; CBS_INTERNAL=0" "--check-certificate=true" "--remote-time=true" "--auto-file-renaming=false" "--file-allocation=none" "--uri-selector=inorder" -i "9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].fhls-3172.mp4.part.frag.urls"
[aria2c] Downloaded 1046700528 bytes663KiB]
[download] 100% of 998.21MiB in 02:57
[debug] Invoking downloader on "https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/09/07/1943091267888/0919_FTN_Full_795958_,2228,4628,3128,1628,848,503,000.mp4.csmil/index_5_a.m3u8?null=0&id=AgB6tURQFzpfllyeSGH9SylzQgfGvi0QCqvY+Cb+acPv2FiKIe+mx7lAQYrkvcq9OwcvjBoAMEV4bQ%3d%3d&hdntl=exp=1632235484~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2021%2f09%2f07%2f1943091267888%2f0919_FTN_Full_795958_*~data=hdntl~hmac=67aa91d2f391e8945ecb7b2f88a4dcb72a5845d2535d3a574bea57f77b20faaa"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 275
[download] Destination: 9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].fhls-95.mp4
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--file-allocation=none" -x16 -j16 -s16 "--allow-overwrite=true" "--allow-piece-length-change=true" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3704.7 Safari/537.36" --header "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Encoding: gzip, deflate" --header "Accept-Language: en-us,en;q=0.5" --header "Cookie: _alid_=ZxV/VPNiEDO3K8JXWGqKJQ==; hdntl=exp=1632235484~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2021%2f09%2f07%2f1943091267888%2f0919_FTN_Full_795958_*~data=hdntl~hmac=67aa91d2f391e8945ecb7b2f88a4dcb72a5845d2535d3a574bea57f77b20faaa" "--check-certificate=true" "--remote-time=true" "--auto-file-renaming=false" "--file-allocation=none" "--uri-selector=inorder" -i "9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].fhls-95.mp4.part.frag.urls"
[aria2c] Downloaded 40879264 bytes 0B/0B][#4410d2 0B/0B]
[download] 100% of 38.99MiB in 00:16
[Merger] Merging formats into "9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].fhls-3172.mp4" -i "file:9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].fhls-95.mp4" -c copy -map "0:v:0" -map "1:a:0" "file:9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].temp.mp4"
Deleting original file 9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].fhls-95.mp4 (pass -k to keep)
Deleting original file 9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].fhls-3172.mp4 (pass -k to keep)
[debug] ffmpeg command line: ffprobe -show_streams "file:9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].mp4"[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:9_19 - Collins, Gottlieb, Sanders [pwVOzmDKX_wXlwZAzpN0DPM4VmW2H89L].temp.mp4"
C:\Users\Ashish\Desktop> ffmpeg --version
ffmpeg version 3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
```

**Comment by mindbomb** [comment]
> Works for me mate


Does the video play correctly? I have tried newer versions of ffmpeg 3, and I can get a file created, but my media player can't play it after a few seconds.

**Comment by pukkandan** [comment]
The issue you are getting with ffmpeg 3 will be fixed by https://github.com/yt-dlp/yt-dlp/commit/a21e0ab1a1a03f82517cd8cec4b9a2b4d6b81ac3. This patch is unnecessary for newer versions of ffmpeg. That's probably why it has gone unnoticed so far. As for the issue with latest ffmpeg, we have opened an issue https://trac.ffmpeg.org/ticket/9433. Hopefully we can get to a solution soon

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp/issues/998#issuecomment-928392182
