### ISSUE TITLE
Videos with embedded WebP thumbnails will not be reprocessed correctly with `--embed-metadata`

### ISSUE THREAD

**Issue by 0n-s** [yt-dlp/yt-dlp#10400]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When embedding a video with a WebP thumbnail into MKV format, the `--embed-metadata` pass will fail.

This only seems to happen when the file is already downloaded; I believe this is because when the metadata pass runs on the initial downloaded, the WebP thumbnail is not embedded yet, & is only added after (in the `--embed-thumbnail` pass, which runs after).

The specific error messages (`codec webp is not supported by this format`) seem to be because there is no tag for WebP in the `ff_codec_bmp_tags` array (`libavformat/riff.c` in ffmpeg source). So I strongly suspect this is an upstream bug.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -N2 -vU GzfnpQLPz5c
[debug] Command-line config: ['-N2', '-vU', 'GzfnpQLPz5c']
[debug] User config "/home/sfundt/.config/yt-dlp/config": ['--xattrs', '--embed-metadata', '--embed-chapters', '--embed-info-json', '--embed-subs', '--embed-thumbnail', '--sponsorblock-mark', 'all', '--sub-langs', 'all']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.07.09.1 [bbf84bf55]
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.9.8-ns-vtn-x86_64-Intel-R-_Xeon-R-_CPU_E5-2420_0_@_1.90GHz-with-libc (OpenSSL 3.2.2  1 Jan 1970, libc)
[debug] exe versions: ffmpeg present (needs_adtstoasc,setts), ffprobe present
[debug] Optional libraries: brotli-1.0.9, certifi-3021.03.16, mutagen-1.46.0, pycrypto-3.18.0, requests-2.31.0, sqlite3-3.40.1, urllib3-2.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (local@2024.07.09.1)
[youtube] Extracting URL: GzfnpQLPz5c
[youtube] GzfnpQLPz5c: Downloading webpage
[youtube] GzfnpQLPz5c: Downloading ios player API JSON
[youtube] GzfnpQLPz5c: Downloading player b22ef6e7
[debug] Saving youtube-nsig.b22ef6e7 to cache
[debug] [youtube] Decrypted nsig q2mLz77vTpMp9dvi_ => vPgfwREyk58TTQ
[debug] Loading youtube-nsig.b22ef6e7 from cache
[debug] [youtube] Decrypted nsig _u3K9_KblhcJ2hhG4 => gdPjoHILmkZfOQ
[youtube] GzfnpQLPz5c: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/3a56?service=YouTube&categories=%5B%22music_offtopic%22%2C+%22poi_highlight%22%2C+%22filler%22%2C+%22preview%22%2C+%22intro%22%2C+%22sponsor%22%2C+%22selfpromo%22%2C+%22interaction%22%2C+%22chapter%22%2C+%22outro%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[SponsorBlock] No matching segments were found in the SponsorBlock database
[debug] Default format spec: bestvideo*+bestaudio/best
[info] GzfnpQLPz5c: Downloading 1 format(s): 616+251
[info] There are no subtitles for the requested languages
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: [SFM] Meet The Sasha-GzfnpQLPz5c.webp
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1720567403/ei/C3KNZqOvFZPE0u8PsIGVoAI/ip/XXX/id/1b37e7a502cfcf97/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D14400820%3Bdur%3D94.999%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1716942371906383/rqh/1/hls_chunk_host/rr1---sn-capm-vnae.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/80/mm/31,29/mn/sn-capm-vnae,sn-5hneknee/ms/au,rdu/mv/m/mvi/1/pl/24/initcwndbps/2297500/vprv/1/playlist_type/DVR/dover/13/txp/5432434/mt/1720545448/fvip/5/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRQIgAvtVrbFQnctkm43Ty-KEvVOg96MolEaA3jtDRGglfcQCIQDjbNlxJ3t8pI2DKEB3ujS9W0MAFXg88Q3qFQapEpegSQ%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AHlkHjAwRQIgTAJbv1dQYQ2bEtPLwPnPpPUaQItVE3oXebz13xLoC7ICIQD-ZbxwMm_1AhjSWDCkYnKJyMneYaY-9UQWEbnI1i39ew%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 16
[download] Destination: [SFM] Meet The Sasha-GzfnpQLPz5c.f616.mp4
[download] 100% of   13.75MiB in 00:00:21 at 644.91KiB/s
[debug] Invoking http downloader on "https://rr1---sn-capm-vnae.googlevideo.com/videoplayback?expire=1720567401&ei=CXKNZoPiOvyi0u8Pn96_iA8&ip=XXX&id=o-AKV6Sszh-nU71k3QrlM0NAijh0-8mIdeT51Qu__pdNvs&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=80&mm=31%2C29&mn=sn-capm-vnae%2Csn-5hne6nzs&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=2297500&bui=AXc671L3iPbWxxE6tiKo_MrZtDB07c9qC4Sba_yxHf3vRG2To-eIqvP0dUsU7iyFBYVqPcin2NVYKkh6&spc=NO7bAR3hbBMKMInyb66liFDLRkMQzxZbo184iaakCID8DqsLrKAoEzXtRCBB&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=0tjA89JMlr0dOmlsdrcz6QgQ&rqh=1&gir=yes&clen=1270485&dur=95.041&lmt=1716941999066520&mt=1720545448&fvip=3&keepalive=yes&c=WEB&sefc=1&txp=5432434&n=gdPjoHILmkZfOQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgDVTPETzqz289Ylyj1-hvTeFrgxG9dY5VDYvC6YIwv2oCIGsc7lSiRrIFsk6qUjoZQ-8XzKcgw54JYdf6yzSfvzk8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRgIhANs5WOO7J3PUwnmEJ6iBfCDqW4DoY3QT0qlnI_IWnBCgAiEA0KvylHRy9jN8DLVJDH14LWdF002K8N1O4DMeZp8gVXo%3D"
[download] Destination: [SFM] Meet The Sasha-GzfnpQLPz5c.f251.webm
[download] 100% of    1.21MiB in 00:00:02 at 566.55KiB/s
[Merger] Merging formats into "[SFM] Meet The Sasha-GzfnpQLPz5c.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.f616.mp4' -i 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.temp.mkv'
Deleting original file [SFM] Meet The Sasha-GzfnpQLPz5c.f251.webm (pass -k to keep)
Deleting original file [SFM] Meet The Sasha-GzfnpQLPz5c.f616.mp4 (pass -k to keep)
[VideoRemuxer] Not remuxing media file "[SFM] Meet The Sasha-GzfnpQLPz5c.mkv"; already is in target format mkv
[EmbedSubtitle] There aren't any subtitles to embed
[debug] Writing info-json to: [SFM] Meet The Sasha-GzfnpQLPz5c.info.json.temp
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.mkv'
[Metadata] Adding metadata to "[SFM] Meet The Sasha-GzfnpQLPz5c.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.mkv' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=[SFM] Meet The Sasha' -metadata date=20240522 -metadata 'description=SFM WORKSHOP: https://steamcommunity.com/sharedfiles/filedetails/?id=3252217406

Patreon: https://www.patreon.com/user?u=4622388
Twitter: https://twitter.com/EmperorFaiz
_____________________________________________________________________________
Heavy loves his minigun and she got an unexpected upgrade allowing her to fight alongside her precious Misha-bear with better efficiency and speed and dispense Sandviches to him anytime and anywhere.

Sasha was voiced by yours truly and the AI voice generated by Fakeyou website to change the voice.

🔰MUSIC🔰
⚫️Team Fortress 2 theme song
_____________________________________________________________________________
🥰Patreon supporters🥰
👨‍🌾PEASANT:
⚫️

#tf2 #sfm #fixtf2' -metadata 'synopsis=SFM WORKSHOP: https://steamcommunity.com/sharedfiles/filedetails/?id=3252217406

Patreon: https://www.patreon.com/user?u=4622388
Twitter: https://twitter.com/EmperorFaiz
_____________________________________________________________________________
Heavy loves his minigun and she got an unexpected upgrade allowing her to fight alongside her precious Misha-bear with better efficiency and speed and dispense Sandviches to him anytime and anywhere.

Sasha was voiced by yours truly and the AI voice generated by Fakeyou website to change the voice.

🔰MUSIC🔰
⚫️Team Fortress 2 theme song
_____________________________________________________________________________
🥰Patreon supporters🥰
👨‍🌾PEASANT:
⚫️

#tf2 #sfm #fixtf2' -metadata 'purl=https://www.youtube.com/watch?v=GzfnpQLPz5c' -metadata 'comment=https://www.youtube.com/watch?v=GzfnpQLPz5c' -metadata artist=EmperorFaiz -metadata:s:1 language=eng -attach 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.info.json.temp' -metadata:s:2 mimetype=application/json -metadata:s:2 filename=info.json -movflags +faststart 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.temp.mkv'
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.mkv'
[EmbedThumbnail] ffmpeg: Adding thumbnail to "[SFM] Meet The Sasha-GzfnpQLPz5c.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.mkv' -map 0 -dn -ignore_unknown -c copy -attach 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.webp' -metadata:s:3 mimetype=image/webp -metadata:s:3 filename=cover.webp -movflags +faststart 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.temp.mkv'
[XAttrMetadata] Writing metadata to file's xattrs
$ yt-dlp -N2 -vU GzfnpQLPz5c
[debug] Command-line config: ['-N2', '-vU', 'GzfnpQLPz5c']
[debug] User config "/home/sfundt/.config/yt-dlp/config": ['--xattrs', '--embed-metadata', '--embed-chapters', '--embed-info-json', '--embed-subs', '--embed-thumbnail', '--sponsorblock-mark', 'all', '--sub-langs', 'all']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.07.09.1 [bbf84bf55]
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.9.8-ns-vtn-x86_64-Intel-R-_Xeon-R-_CPU_E5-2420_0_@_1.90GHz-with-libc (OpenSSL 3.2.2  1 Jan 1970, libc)
[debug] exe versions: ffmpeg present (needs_adtstoasc,setts), ffprobe present
[debug] Optional libraries: brotli-1.0.9, certifi-3021.03.16, mutagen-1.46.0, pycrypto-3.18.0, requests-2.31.0, sqlite3-3.40.1, urllib3-2.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (local@2024.07.09.1)
[youtube] Extracting URL: GzfnpQLPz5c
[youtube] GzfnpQLPz5c: Downloading webpage
[youtube] GzfnpQLPz5c: Downloading ios player API JSON
[debug] Loading youtube-nsig.b22ef6e7 from cache
[debug] [youtube] Decrypted nsig aVFIq7VZW5OjRkXyz => Zc2SQ9iuib_6Cw
[debug] Loading youtube-nsig.b22ef6e7 from cache
[debug] [youtube] Decrypted nsig vsjltlaNBnce55HXP => hpvQ-6MSadNydA
[youtube] GzfnpQLPz5c: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/3a56?service=YouTube&categories=%5B%22music_offtopic%22%2C+%22preview%22%2C+%22chapter%22%2C+%22poi_highlight%22%2C+%22interaction%22%2C+%22filler%22%2C+%22outro%22%2C+%22sponsor%22%2C+%22selfpromo%22%2C+%22intro%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[SponsorBlock] No matching segments were found in the SponsorBlock database
[debug] Default format spec: bestvideo*+bestaudio/best
[info] GzfnpQLPz5c: Downloading 1 format(s): 616+251
[info] There are no subtitles for the requested languages
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: [SFM] Meet The Sasha-GzfnpQLPz5c.webp
[download] [SFM] Meet The Sasha-GzfnpQLPz5c.mkv has already been downloaded
[VideoRemuxer] Not remuxing media file "[SFM] Meet The Sasha-GzfnpQLPz5c.mkv"; already is in target format mkv
[EmbedSubtitle] There aren't any subtitles to embed
[debug] Writing info-json to: [SFM] Meet The Sasha-GzfnpQLPz5c.info.json.temp
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.mkv'
[Metadata] Adding metadata to "[SFM] Meet The Sasha-GzfnpQLPz5c.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.mkv' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=[SFM] Meet The Sasha' -metadata date=20240522 -metadata 'description=SFM WORKSHOP: https://steamcommunity.com/sharedfiles/filedetails/?id=3252217406

Patreon: https://www.patreon.com/user?u=4622388
Twitter: https://twitter.com/EmperorFaiz
_____________________________________________________________________________
Heavy loves his minigun and she got an unexpected upgrade allowing her to fight alongside her precious Misha-bear with better efficiency and speed and dispense Sandviches to him anytime and anywhere.

Sasha was voiced by yours truly and the AI voice generated by Fakeyou website to change the voice.

🔰MUSIC🔰
⚫️Team Fortress 2 theme song
_____________________________________________________________________________
🥰Patreon supporters🥰
👨‍🌾PEASANT:
⚫️

#tf2 #sfm #fixtf2' -metadata 'synopsis=SFM WORKSHOP: https://steamcommunity.com/sharedfiles/filedetails/?id=3252217406

Patreon: https://www.patreon.com/user?u=4622388
Twitter: https://twitter.com/EmperorFaiz
_____________________________________________________________________________
Heavy loves his minigun and she got an unexpected upgrade allowing her to fight alongside her precious Misha-bear with better efficiency and speed and dispense Sandviches to him anytime and anywhere.

Sasha was voiced by yours truly and the AI voice generated by Fakeyou website to change the voice.

🔰MUSIC🔰
⚫️Team Fortress 2 theme song
_____________________________________________________________________________
🥰Patreon supporters🥰
👨‍🌾PEASANT:
⚫️

#tf2 #sfm #fixtf2' -metadata 'purl=https://www.youtube.com/watch?v=GzfnpQLPz5c' -metadata 'comment=https://www.youtube.com/watch?v=GzfnpQLPz5c' -metadata artist=EmperorFaiz -metadata:s:1 language=eng -map -0:2 -attach 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.info.json.temp' -metadata:s:3 mimetype=application/json -metadata:s:3 filename=info.json -movflags +faststart 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.temp.mkv'
[debug] [matroska,webm @ 0x5ffd12102280] Could not find codec parameters for stream 2 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from 'file:[SFM] Meet The Sasha-GzfnpQLPz5c.mkv':
  Metadata:
    title           : [SFM] Meet The Sasha
    PURL            : https://www.youtube.com/watch?v=GzfnpQLPz5c
    COMMENT         : https://www.youtube.com/watch?v=GzfnpQLPz5c
    COMPATIBLE_BRANDS: iso6mp41
    MAJOR_BRAND     : dash
    MINOR_VERSION   : 0
    ARTIST          : EmperorFaiz
    DATE            : 20240522
    DESCRIPTION     : SFM WORKSHOP: https://steamcommunity.com/sharedfiles/filedetails/?id=3252217406
                    :
                    : Patreon: https://www.patreon.com/user?u=4622388
                    : Twitter: https://twitter.com/EmperorFaiz
                    : _____________________________________________________________________________
                    : Heavy loves his minigun and she got an unexpected upgrade allowing her to fight alongside her precious Misha-bear with better efficiency and speed and dispense Sandviches to him anytime and anywhere.
                    :
                    : Sasha was voiced by yours truly and the AI voice generated by Fakeyou website to change the voice.
                    :
                    : 🔰MUSIC🔰
                    : ⚫️Team Fortress 2 theme song
                    : _____________________________________________________________________________
                    : 🥰Patreon supporters🥰
                    : 👨‍🌾PEASANT:
                    : ⚫️
                    :
                    : #tf2 #sfm #fixtf2
    SYNOPSIS        : SFM WORKSHOP: https://steamcommunity.com/sharedfiles/filedetails/?id=3252217406
                    :
                    : Patreon: https://www.patreon.com/user?u=4622388
                    : Twitter: https://twitter.com/EmperorFaiz
                    : _____________________________________________________________________________
                    : Heavy loves his minigun and she got an unexpected upgrade allowing her to fight alongside her precious Misha-bear with better efficiency and speed and dispense Sandviches to him anytime and anywhere.
                    :
                    : Sasha was voiced by yours truly and the AI voice generated by Fakeyou website to change the voice.
                    :
                    : 🔰MUSIC🔰
                    : ⚫️Team Fortress 2 theme song
                    : _____________________________________________________________________________
                    : 🥰Patreon supporters🥰
                    : 👨‍🌾PEASANT:
                    : ⚫️
                    :
                    : #tf2 #sfm #fixtf2
    ENCODER         : Lavf60.16.100
  Duration: 00:01:35.05, start: 0.000000, bitrate: 1358 kb/s
  Stream #0:0: Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, 24 fps, 24 tbr, 1k tbn (default)
    Metadata:
      HANDLER_NAME    : ISO Media file produced by Google Inc. Created on: 07/09/2024.
      VENDOR_ID       : [0][0][0][0]
      DURATION        : 00:01:34.999000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:01:35.048000000
  Stream #0:2: Attachment: none
    Metadata:
      filename        : info.json
      mimetype        : application/json
  Stream #0:3: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 1280x720, 90k tbr, 90k tbn (attached pic)
    Metadata:
      filename        : cover.webp
      mimetype        : image/webp
[matroska @ 0x5ffd0dfc2ac0] codec webp is not supported by this format
[matroska @ 0x5ffd0dfc2ac0] No bmp codec tag found for codec webp
[out#0/matroska @ 0x5ffd0e779c20] Could not write header (incorrect codec parameters ?): Invalid argument
Error opening output file file:[SFM] Meet The Sasha-GzfnpQLPz5c.temp.mkv.
Error opening output files: Invalid argument

ERROR: Postprocessing: Error opening output files: Invalid argument
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3552, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3734, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3716, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3694, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 712, in run
    self.run_ffmpeg_multiple_files(
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 330, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 368, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error opening output files: Invalid argument
```

**Comment by 0n-s** [comment]
(just preemptively noting) You might be rightfully suspicious about my ffmpeg log labeling the thumbnail as an `attached pic`; that is this patch:
```
--- a/libavformat/matroskadec.c
+++ b/libavformat/matroskadec.c
@@ -811,6 +811,7 @@ static const CodecMime mkv_image_mime_tags[] = {
     {"image/jpeg"                 , AV_CODEC_ID_MJPEG},
     {"image/png"                  , AV_CODEC_ID_PNG},
     {"image/tiff"                 , AV_CODEC_ID_TIFF},
+    {"image/webp"                 , AV_CODEC_ID_WEBP},

     {""                           , AV_CODEC_ID_NONE}
 };
 ```
 I simply made it to allow thumbnailer programs to recognize them properly. This is the only patch I apply to ffmpeg, otherwise it is completely vanilla. I tested without & it makes no difference.

**Comment by 0n-s** [comment]
I misunderstood some of the details when I made this issue. The issue is that FFmpeg sees the WebP file as an attachment on the initial mux, but on the remux, sees the WebP file as a video track, even though it's an attachment (probably simply because it _can_ decode the WebP file & it can't do the same for e.g. info.json). So it complaining about WebP missing a tag is because it's trying to mux it as a video track, which is definitely **not** the correct behavior.

The difference between attachments & video tracks is clearly specified in the Matroska spec. If you use yt-dlp to download a file with an embedded thumbnail & don't remux it, you can use mkvinfo on it to see that the video/audio tracks are in a different section to the attachments, which are [_mostly_ treated as opaque data](https://www.matroska.org/technical/attachments.html). But FFmpeg doesn't seem to treat them as opaque data in this example. & that's the actually correct summary of the bug, AFAIK.
