### ISSUE TITLE
[YouTube] Requested format is not available

### ISSUE THREAD

**Issue by DesweR** [yt-dlp/yt-dlp#10403]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Format selection has stopped working for filter **"bestvideo[format_id=135]+bestaudio[format_id=140]"**

But if you specify format selection **"135+140"** or **"bestvideo+bestaudio"** - then it works.

I understand that this is not a very suitable format for a request, but it has worked for many years.

I also tried using the sort options, but nothing worked.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', 'bestvideo[format_id=135]+bestaudio[format_id=140]', 'https://www.youtube.com/watch?v=EXm0hs266HE', '-v']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version local@2024.07.09 [7ead7332a] (win_x86_exe)
[debug] Python 3.9.13 (CPython x86 32bit) - Windows-XP-5.1.2600-SP3 (OpenSSL 3.1.0-dev )
[debug] exe versions: ffmpeg N-100546-g2c6f532-Reino (fdk), ffprobe N-98939-g276d86a-Reino
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=EXm0hs266HE
[youtube] EXm0hs266HE: Downloading webpage
[youtube] EXm0hs266HE: Downloading ios player API JSON
[youtube] EXm0hs266HE: Downloading player 9ed4a7e1
[debug] Saving youtube-nsig.9ed4a7e1 to cache
[debug] [youtube] Decrypted nsig ywZy4HeUtyv0KElK => nvj73vUalLUMnQ
[debug] Loading youtube-nsig.9ed4a7e1 from cache
[debug] [youtube] Decrypted nsig CNAVHa1RvKXw04VZ => AzsG9RGuA9rWOg
[youtube] EXm0hs266HE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] EXm0hs266HE: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1622, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1778, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1837, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2973, in process_video_result
yt_dlp.utils.ExtractorError: [youtube] EXm0hs266HE: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
Filtering by `[format_id=NUMERIC_ID]` hasn't worked for a over a year; regression in c3f624ef0a5d7a6ae1c5ffeb243087e9fc7d79dc .

If you pass a numeric ID to the `format_id=` filter, yt-dlp interprets your ID input as a **number** rather than a string, so it is not equivalent when compared with the video's **string** format ID. This issue does not present when there are any non-numeric characters in the format ID.

The workaround is to use inner quotes around the format ID, e.g. `-f "bv[format_id='135']"` (or just use `-f 135`).

This will be fixed when https://github.com/yt-dlp/yt-dlp/issues/4846#issuecomment-1244017668 is implemented. 

For devs, below is the code that handles this case for `--match-filter`, and will fix this issue when it is generalized for `-f`: https://github.com/yt-dlp/yt-dlp/blob/f73c11803579889dc8e1c99e25dba9a22fef39d8/yt_dlp/utils/_utils.py#L3167-L3171
