### ISSUE TITLE
Post Processing Error with Vimeo: Media files fail to merge

### ISSUE THREAD

**Issue by shoxie007** [yt-dlp/yt-dlp#1040]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp --verbose -f "bestvideo[ext=mp4][format_id^=dash]+bestaudio[ext=m4a][format_id^=dash]" "https://vimeo.com/569849135"

[debug] Command-line config: ['--verbose', '-f', 'bestvideo[ext=mp4][format_id^=dash]+bestaudio[ext=m4a][format_id^=dash]', 'https://vimeo.com/569849135']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-93885-gc61d16cf3b, ffprobe N-93885-gc61d16cf3b, phantomjs 2.1.1
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [vimeo] Extracting URL: https://vimeo.com/569849135
[vimeo] 569849135: Downloading webpage
[vimeo] 569849135: Extracting information
[vimeo] 569849135: Downloading JSON metadata
[vimeo] 569849135: Downloading JSON metadata
WARNING: [vimeo] Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 569849135: Downloading jwt token
[vimeo] 569849135: Downloading JSON metadata
[vimeo] 569849135: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 569849135: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 569849135: Downloading fastly_skyfire m3u8 information
[vimeo] 569849135: Downloading fastly_skyfire m3u8 information
[vimeo] 569849135: Downloading akfire_interconnect_quic MPD information
[vimeo] 569849135: Downloading akfire_interconnect_quic MPD information
[vimeo] 569849135: Downloading fastly_skyfire MPD information
[vimeo] 569849135: Downloading fastly_skyfire MPD information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 569849135: Downloading 1 format(s): dash-fastly_skyfire_sep-video-c9371b72+dash-fastly_skyfire_sep-audio-17de3bb9
[debug] Invoking downloader on "https://skyfire.vimeocdn.com/1632169706-0x7e730662ad199ad1e6c58b0d15e0f767f989ed93/de014964-0fa8-4bf4-8d76-fed8fac49d18/sep/video/f7de66db,09f289be,da8b133a,c9371b72,8a2f0a6c/audio/25f24b28,17de3bb9/master.mpd?query_string_ranges=1&base64_init=1"
[download] Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-video-c9371b72.mp4 has already been downloaded
[download] 100% of 135.09MiB
[debug] Invoking downloader on "https://skyfire.vimeocdn.com/1632169706-0x7e730662ad199ad1e6c58b0d15e0f767f989ed93/de014964-0fa8-4bf4-8d76-fed8fac49d18/sep/video/f7de66db,09f289be,da8b133a,c9371b72,8a2f0a6c/audio/25f24b28,17de3bb9/master.mpd?query_string_ranges=1&base64_init=1"
[download] Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-audio-17de3bb9.m4a has already been downloaded
[download] 100% of 2.38MiB
[Merger] Merging formats into "Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-video-c9371b72.mp4" -i "file:Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-audio-17de3bb9.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].temp.mp4"
ERROR: ffmpeg version N-93885-gc61d16cf3b Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 28.100 / 56. 28.100
  libavcodec     58. 52.101 / 58. 52.101
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 53.101 /  7. 53.101
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-video-c9371b72.mp4':
  Metadata:
    major_brand     : iso5
    minor_version   : 512
    compatible_brands: iso5iso6mp41
    encoder         : Lavf59.4.101
  Duration: 00:03:34.00, start: 0.000000, bitrate: 5295 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 5292 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-audio-17de3bb9.m4a':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: dashiso6mp41
    creation_time   : 2021-07-01T13:27:33.000000Z
    encoder         : Lavf58.74.100
  Duration: 00:03:34.01, start: -0.006500, bitrate: 93 kb/s
    Stream #1:0(und): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 91 kb/s (default)
    Metadata:
      creation_time   : 2021-07-01T13:27:33.000000Z
      handler_name    : SoundHandler
[mp4 @ 000001edd3f593c0] track 1: codec frame size is not set
[mp4 @ 000001edd3f593c0] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 776, in main
  File "yt_dlp\__init__.py", line 766, in _real_main
  File "yt_dlp\YoutubeDL.py", line 2894, in download
  File "yt_dlp\YoutubeDL.py", line 1207, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1214, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1252, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1298, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2320, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2864, in process_info
  File "yt_dlp\YoutubeDL.py", line 3015, in post_process
  File "yt_dlp\YoutubeDL.py", line 2964, in run_pp
  File "yt_dlp\postprocessor\common.py", line 83, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 717, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 237, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 274, in real_run_ffmpeg
  File "yt_dlp\postprocessor\common.py", line 56, in report_error
  File "yt_dlp\YoutubeDL.py", line 818, in report_error
  File "yt_dlp\YoutubeDL.py", line 774, in trouble

ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2864, in process_info
  File "yt_dlp\YoutubeDL.py", line 3015, in post_process
  File "yt_dlp\YoutubeDL.py", line 2964, in run_pp
  File "yt_dlp\postprocessor\common.py", line 83, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 717, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 237, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 275, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

```

## Description

As stated in the title, when I download separate video and audio from Vimeo, yt-dlp will download them but will fail to merge them at the end. My command:
`yt-dlp --verbose -f "bestvideo[ext=mp4][format_id^=dash]+bestaudio[ext=m4a][format_id^=dash]" "https://vimeo.com/569849135"`

I tried with several different Vimeo videos. Same result.

**Comment by shoxie007** [comment]
I'd also like to add that format option 
`bestaudio[ext=m4a][format_id^=dash]`
does not yield the best possible audio track. There are other audio tracks with higher bitrates. 

I tried youtube-dl and it works fine, not just to download and merge the files, but also in selecting the best quality files.

**Comment by nyuszika7h** [comment]
You can try `--downloader-args "ffmpeg:-strict -2"` or `--remux-video mkv`.

**Comment by shoxie007** [comment]
> 
> 
> You can try `--downloader-args "ffmpeg:-strict -2"` or `--remux-video mkv`.

Thanks for the suggestion. Didn't work for me. Did it work for you? And I'd rather not remux/re-encode. I want to leave the video/audio streams as is.

**Comment by nyuszika7h** [comment]
Remuxing is different from reencoding and doesn't result in any loss of quality. It's technically already remuxing when it's combining the two formats, just to MP4 instead of MKV.

The first option should in theory keep it as MP4 and enable the experimental support, but I don't know how many players support that if it even works, while MKV supports pretty much every combination.

**Comment by pukkandan** [comment]
> You can try --downloader-args "ffmpeg:-strict -2"

This is wrong. It should be `--ppa "Merger:-strict -2"`

But yeah, the issue is that your ffmpeg version only has experimental support for opus in mp4. You can either use the above workaround, or use a newer version of ffmpeg

```cmd
➤ yt-dlp -v "https://vimeo.com/569849135" -f "dash-fastly_skyfire_sep-video-c9371b72+dash-fastly_skyfire_sep-audio-17de3bb9"
[debug] Command-line config: ['-v', 'https://vimeo.com/569849135', '-f', 'dash-fastly_skyfire_sep-video-c9371b72+dash-fastly_skyfire_sep-audio-17de3bb9']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 5577420b2
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-103655-g1dd3ab4876-20210917, ffprobe N-103655-g1dd3ab4876-20210917, phantomjs 2.1.1
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [vimeo] Extracting URL: https://vimeo.com/569849135
[vimeo] 569849135: Downloading webpage
[vimeo] 569849135: Extracting information
[vimeo] 569849135: Downloading JSON metadata
[vimeo] 569849135: Downloading JSON metadata
WARNING: [vimeo] Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 569849135: Downloading jwt token
[vimeo] 569849135: Downloading JSON metadata
[vimeo] 569849135: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 569849135: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 569849135: Downloading fastly_skyfire m3u8 information
[vimeo] 569849135: Downloading fastly_skyfire m3u8 information
[vimeo] 569849135: Downloading akfire_interconnect_quic MPD information
[vimeo] 569849135: Downloading akfire_interconnect_quic MPD information
[vimeo] 569849135: Downloading fastly_skyfire MPD information
[vimeo] 569849135: Downloading fastly_skyfire MPD information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 569849135: Downloading 1 format(s): dash-fastly_skyfire_sep-video-c9371b72+dash-fastly_skyfire_sep-audio-17de3bb9
[debug] Invoking downloader on "https://skyfire.vimeocdn.com/1632439149-0x2a4123b2bc652cc338a37e9e13730bb7e8819d53/de014964-0fa8-4bf4-8d76-fed8fac49d18/sep/video/f7de66db,09f289be,da8b133a,c9371b72,8a2f0a6c/audio/17de3bb9,25f24b28/master.mpd?query_string_ranges=1&base64_init=1"
[download] Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-video-c9371b72.mp4 has already been downloaded
[download] 100% of 135.09MiB
[debug] Invoking downloader on "https://skyfire.vimeocdn.com/1632439149-0x2a4123b2bc652cc338a37e9e13730bb7e8819d53/de014964-0fa8-4bf4-8d76-fed8fac49d18/sep/video/f7de66db,09f289be,da8b133a,c9371b72,8a2f0a6c/audio/17de3bb9,25f24b28/master.mpd?query_string_ranges=1&base64_init=1"
[download] Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-audio-17de3bb9.m4a has already been downloaded
[download] 100% of 2.38MiB
[debug] ffmpeg command line: ffprobe -show_streams "file:Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-audio-17de3bb9.m4a"
[Merger] Merging formats into "Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-video-c9371b72.mp4" -i "file:Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-audio-17de3bb9.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].temp.mp4"
Deleting original file Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-audio-17de3bb9.m4a (pass -k to keep)
Deleting original file Moby - 'Why Does My Heart Feel So Bad' (Reprise Version) Official Video [569849135].fdash-fastly_skyfire_sep-video-c9371b72.mp4 (pass -k to keep)
```

**Comment by shoxie007** [comment]
> 
> 
> This is wrong. It should be `--ppa "Merger:-strict -2"`
> 
> But yeah, the issue is that your ffmpeg version only has experimental support for opus in mp4. You can either use the above workaround, or use a newer version of ffmpeg
> 
Thanks @pukkandan. I updated my ffmpeg and now it works. Can I suggest a modification to the Vimeo extractor? The DASH audio files should be arranged by order of total bitrate (TBR). At present, the opus-encoded files, which have a lower TBR, take precedence over the mp4a encoded files, which have higher TBR. So when you use option:
`yt-dlp -f bestaudio[ext=m4a][format_id^=dash] ....`
yt-dlp will pick the lower-bitrate opus-encoded files rather than the higher bitrate mp4a-encoded files

Here is an example of bitrates listed by order of preference:

```
yt-dlp -F "https://vimeo.com/569849135"

ID                                                  EXT RESOLUTION FPS |  FILESIZE    TBR PROTO  | VCODEC                           VBR ACODEC     ABR  ASR    MORE INFO
--------------------------------------------------- --- ---------- --- - ---------- ----- ------ - ------------------------------ ----- --------- ---- ------- --------------------
hls-akfire_interconnect_quic_sep-audio-high-audio   mp4 audio only     |                  m3u8_n |                                      unknown                audio
hls-akfire_interconnect_quic_sep-audio-medium-audio mp4 audio only     |                  m3u8_n |                                      unknown                audio
hls-fastly_skyfire_sep-audio-high-audio             mp4 audio only     |                  m3u8_n |                                      unknown                audio
hls-fastly_skyfire_sep-audio-medium-audio           mp4 audio only     |                  m3u8_n |                                      unknown                audio
dash-akfire_interconnect_quic_sep-audio-da8b133a    m4a audio only     |             128k dash   |                                      mp4a.40.2 128k 48000Hz DASH audio, m4a_dash
dash-fastly_skyfire_sep-audio-da8b133a              m4a audio only     |             128k dash   |                                      mp4a.40.2 128k 48000Hz DASH audio, m4a_dash
dash-akfire_interconnect_quic_sep-audio-f7de66db    m4a audio only     |             255k dash   |                                      mp4a.40.2 255k 48000Hz DASH audio, m4a_dash
dash-fastly_skyfire_sep-audio-f7de66db              m4a audio only     |             255k dash   |                                      mp4a.40.2 255k 48000Hz DASH audio, m4a_dash
dash-akfire_interconnect_quic_sep-audio-25f24b28    m4a audio only     |              66k dash   |                                      opus       66k 48000Hz DASH audio, m4a_dash
dash-fastly_skyfire_sep-audio-25f24b28              m4a audio only     |              66k dash   |                                      opus       66k 48000Hz DASH audio, m4a_dash
dash-akfire_interconnect_quic_sep-audio-17de3bb9    m4a audio only     |              99k dash   |                                      opus       99k 48000Hz DASH audio, m4a_dash
dash-fastly_skyfire_sep-audio-17de3bb9              m4a audio only     |              99k dash   |                                      opus       99k 48000Hz DASH audio, m4a_dash
```

I went through the Vimeo extractor and read:
```
 # Bitrates are completely broken. Single m3u8 may contain entries in kbps and bps
 # at the same time without actual units specified. This lead to wrong sorting.
 # But since yt-dlp prefers 'res,fps' anyway, 'field_preference' is not needed
```
Fair enough. But this applies ONLY to the m3u8 protocol files doesn't it? The DASH formats, for which bitrates are available, can still be ordered by TBR. Am I missing something?

**Comment by pukkandan** [comment]
That comment is from youtube-dl. yt-dlp always sorts opus above m4a. Ideally we would sort by some independent measure of quality that the website provides, but I doubt that is available for vimeo. While I could take a look at that, it is better for you to use your custom sorting using `-S`. Something like `-S res,br` should suit your needs. You could also get rid of your `-f` string completely by using something like `-S codec:mp4:m4a,proto:dash`

**Comment by shoxie007** [comment]
> 
> 
> That comment is from youtube-dl. yt-dlp always sorts opus above m4a. Ideally we would sort by some independent measure of quality that the website provides, but I doubt that is available for vimeo. While I could take a look at that, it is better for you to use your custom sorting using `-S`. Something like `-S res,br` should suit your needs. You could also get rid of your `-f` string completely by using something like `-S codec:mp4:m4a,proto:dash`

Thanks pukkandan. You are such a godsend. Always so responsive, and accessible. So glad to have you in my life!
