### ISSUE TITLE
Unable to download X spaces Audio Records

### ISSUE THREAD

**Issue by ondern** [yt-dlp/yt-dlp#10423]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I use v1.7.8 latest version and logged in to X to keep my cookies. I am paid pro member for some channels.

Channel Link:

Prof. Dr. Özgür Demirtaş
https://x.com/ProfDemirtas?t=OYo8Ky8MXPx0DvGScX2UHQ&s=09

Spaces Link for pro members:

Abonelere Özel 13. Canlı Yayın
https://x.com/i/spaces/1dRKZEdbvYgxB

YTDLNis Logs Attached
[logs.txt](https://github.com/user-attachments/files/16172537/logs.txt)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Attached logs
```

**Comment by ondern** [comment]
https://github.com/deniscerri/ytdlnis/issues/523

**Comment by bashonly** [comment]
This looks similar to #9059 but with the added wrinkle of a decryption key failing to download:

```
[hls @ 0xb4000072c8c64270] Opening 'https://x.com/i/live_video_stream/key?stream_name=dOLbK11At1N1HenjjGIfunBHdt2X1RJPfx9H9dWG8B55uJt1VNOm_a86-0irEpbT7FWUIWWG-omhmuTnSJF4WA' for reading
[https @ 0xb400007288c64410] HTTP error 403 Forbidden
[hls @ 0xb4000072c8c64270] Unable to open key file https://x.com/i/live_video_stream/key?stream_name=dOLbK11At1N1HenjjGIfunBHdt2X1RJPfx9H9dWG8B55uJt1VNOm_a86-0irEpbT7FWUIWWG-omhmuTnSJF4WA
[hls @ 0xb4000072c8c64270] Opening 'crypto+https://prod-fastly-eu-central-1.video.pscp.tv/Transcoding/v1/hls/dOLbK11At1N1HenjjGIfunBHdt2X1RJPfx9H9dWG8B55uJt1VNOm_a86-0irEpbT7FWUIWWG-omhmuTnSJF4WA/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/audio-space/k0_chunk_1719511209218933524_0_a.aac' for reading
```

**Comment by angelperezleon** [comment]
Just want to add to this .x.com/i/space download failings

`pi@pi:~ $ .local/bin/yt-dlp -vU "https://x.com/i/spaces/1YpKkljzdnwGj?clipID=58290ee6-6c7d-4f54-a0bd-2a41d16ba2ee" -o "Polaris_Dawn-Post-mission_Space_event_with_crew-17.09.2024.mp4"
[debug] Command-line config: ['-vU', 'https://x.com/i/spaces/1YpKkljzdnwGj?clipID=58290ee6-6c7d-4f54-a0bd-2a41d16ba2ee', '-o', 'Polaris_Dawn-Post-mission_Space_event_with_crew-17.09.2024.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (zip)
[debug] Python 3.9.2 (CPython aarch64 64bit) - Linux-6.6.32-v8+-aarch64-with-glibc2.36 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: certifi-2024.06.02, requests-2.31.0, sqlite3-3.34.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2024.08.06/SHA2-256SUMS
Current version: stable@2024.05.27 from yt-dlp/yt-dlp
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
Current Build Hash: b67769b0d68dbdc59a6d217713a37443b5a12c1d377c27c9946da8a537b995bb
Updating to stable@2024.08.06 from yt-dlp/yt-dlp ...
[debug] Downloading yt-dlp from https://github.com/yt-dlp/yt-dlp/releases/download/2024.08.06/yt-dlp
Updated yt-dlp to stable@2024.08.06 from yt-dlp/yt-dlp
WARNING: Restart yt-dlp to use the updated version
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/bin/yt-dlp/__main__.py", line 17, in <module>
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/__init__.py", line 1072, in main
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/__init__.py", line 1062, in _real_main
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3583, in download
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3558, in wrapper
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1595, in extract_info
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 844, in get_info_extractor
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 37, in __new__
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 4992, in __get__
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 33, in real_class
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 548, in _get_data
zipimport.ZipImportError: bad local file header: '/home/pi/.local/bin/yt-dlp'
`

**Comment by bashonly** [comment]
@angelperezleon that error looks completely unrelated to the twitter extractor, please open a new issue

**Comment by angelperezleon** [comment]
`pi@pi:~ $ .local/bin/yt-dlp -vU "https://x.com/i/spaces/1YpKkljzdnwGj?clipID=58290ee6-6c7d-4f54-a0bd-2a41d16ba2ee" -o "Polaris_Dawn-Post-mission_Space_event_with_crew-17.09.2024.mp4"
[debug] Command-line config: ['-vU', 'https://x.com/i/spaces/1YpKkljzdnwGj?clipID=58290ee6-6c7d-4f54-a0bd-2a41d16ba2ee', '-o', 'Polaris_Dawn-Post-mission_Space_event_with_crew-17.09.2024.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (zip)
[debug] Python 3.9.2 (CPython aarch64 64bit) - Linux-6.6.32-v8+-aarch64-with-glibc2.36 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: certifi-2024.06.02, requests-2.31.0, sqlite3-3.34.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2024.08.06/SHA2-256SUMS
Current version: stable@2024.05.27 from yt-dlp/yt-dlp
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
Current Build Hash: b67769b0d68dbdc59a6d217713a37443b5a12c1d377c27c9946da8a537b995bb
Updating to stable@2024.08.06 from yt-dlp/yt-dlp ...
[debug] Downloading yt-dlp from https://github.com/yt-dlp/yt-dlp/releases/download/2024.08.06/yt-dlp
Updated yt-dlp to stable@2024.08.06 from yt-dlp/yt-dlp
WARNING: Restart yt-dlp to use the updated version
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/bin/yt-dlp/__main__.py", line 17, in <module>
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/__init__.py", line 1072, in main
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/__init__.py", line 1062, in _real_main
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3583, in download
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3558, in wrapper
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1595, in extract_info
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 844, in get_info_extractor
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 37, in __new__
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 4992, in __get__
  File "/home/pi/.local/bin/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 33, in real_class
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 548, in _get_data
zipimport.ZipImportError: bad local file header: '/home/pi/.local/bin/yt-dlp'`
