### ISSUE TITLE
[neteasemusic] Unable to download

### ISSUE THREAD

**Issue by timi137137** [yt-dlp/yt-dlp#10431]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

@bashonly Sorry to bother you, but we only tested the request and not the download. Seems there is a problem with the parser?
I tried all the parameters I could think of, but the problem persisted.
e.g: all best ba b* ba*

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -format best --cookies-from-browser chrome -v 'https://music.163.com/#/song?id=1948825591'
[debug] Command-line config: ['-format', 'best', '--cookies-from-browser', 'chrome', '-v', 'https://music.163.com/#/song?id=1948825591']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110338-g4570ba5d86-20230421 (setts), ffprobe N-110338-g4570ba5d86-20230421
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890', 'ftp': 'http://127.0.0.1:7890'}
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\timi\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\timi\AppData\Local\Google\Chrome\User Data\Local State"
Attempting to unlock cookies
Extracted 3629 cookies from chrome
[debug] cookie version breakdown: {'v10': 4132, 'other': 0, 'unencrypted': 23}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: ['D:\\App\\System\\Other\\YoutudeDownloader\\yt-dlp-plugins\\cookie_unlock\\yt_dlp_plugins', 'C:\\Users\\timi\\AppData\\Roaming\\yt-dlp-plugins\\cookie_unlock\\yt_dlp_plugins']
[debug] Loaded 1834 extractors
[generic] Extracting URL: best
ERROR: [generic] 'best' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:best" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2357, in _real_extract

[netease:song] Extracting URL: https://music.163.com/#/song?id=1948825591
[netease:song] 1948825591: Downloading song info
[netease:song] 1948825591: Downloading song URL info: level standard
[netease:song] 1948825591: Downloading song URL info: level higher
[netease:song] 1948825591: Downloading song URL info: level exhigh
[netease:song] 1948825591: Downloading song URL info: level lossless
[netease:song] 1948825591: Downloading song URL info: level hires
[netease:song] 1948825591: Downloading song URL info: level jyeffect
[netease:song] 1948825591: Downloading song URL info: level jymaster
[netease:song] 1948825591: Downloading song URL info: level sky
[netease:song] 1948825591: Downloading lyrics data
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [netease:song] 1948825591: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1622, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1778, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1837, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2973, in process_video_result
yt_dlp.utils.ExtractorError: [netease:song] 1948825591: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
try `--format` not `-format`

**Comment by timi137137** [comment]
At the command line he was normal.
But that doesn't seem to be an option in my third-party program, so maybe you can help me
thank you.
![QQ_1720721531298](https://github.com/yt-dlp/yt-dlp/assets/36812439/33eb6b4f-7857-4428-bbd7-619b072ebbec)

**Comment by bashonly** [comment]
that looks correct

**Comment by timi137137** [comment]
![QQ_1720721787765](https://github.com/yt-dlp/yt-dlp/assets/36812439/b793667a-68a0-420c-bb85-b82fbf0a4153)
Too bad it looks bad:(
But everyone else is good

**Comment by bashonly** [comment]
add `'verbose': True` to your `ydl_opts` and run it again, copy/paste the full output here please

**Comment by timi137137** [comment]
oh shit，Thank you for reminding me, I ran install yt-dlp today and I thought it had been updated.
Thank you very much. I deleted it for him and it's back to normal. :)
