### ISSUE TITLE
How to extract sig and get final URL from googlevideo.com URL?

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#10469]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Say you've curled the webpage of a youtube video to file.txt

You find the googlevideo.com URL, find the itag, and substitute `\u0026` with `&` ,

Merely doing this used to be enough to get youtube to let you curl that googlevideo.com URL (albeit at a throttled speed).

But now youtube requires you to solve the sig or you get a 403.

I don't know how yt-dlp sig solving works but is there a way to make yt-dlp just solve the sig of a googlevideo URL and give me the final non-403 erroring URL? Ideally offline, without connecting to youtube?

Thanks.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--no-config', '-v', '-g', 'https://rr2---sn-o097znss.googlevideo.com/videoplayback?expire=1720998193&ei=0QSUZom2IvLAsfIPkpSD2Aw&ip=IPADDRESS&id=o-AFdt598m5GnVUm-wazprY5yJ12PqJolKRekiYB8hCZGC&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=CV&mm=31%2C26&mn=sn-o097znss%2Csn-a5msen76&ms=au%2Conr&mv=m&mvi=2&pl=20&initcwndbps=6988750&bui=AXc671KTlhsbxeao8mqCyNNKO6lxLqleCsC5W2Yko8tbwvgfzIQYUC_EyVZs3sCRaLR5GTNHhcfEpVe8&spc=NO7bAdkqxP-3-193Cfg_eE64e8ibHFnVQFZqayQPZdvYjrP2VWn5g5LKDekO&vprv=1&svpuc=1&mime=video%2Fmp4&ns=BeycHqQePLeO-UE0UgRKgk0Q&rqh=1&gir=yes&clen=386236026&dur=2370.617&lmt=1720967673937005&mt=1720976236&fvip=1&keepalive=yes&c=WEB&sefc=1&txp=6319224&n=Cq_EfvS_0oVAsbRDEeH&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgcX_-hLVnicPU3-Op-zX3tHqcJJVsdRb4tIvNoAKZiO8CIQDlE3aPhDTcqkPIkenDcTFxu-azdzv6bP8ClddEs3P27A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRAIgKXjnkvnOlSN_dBwPqVnB8oKNgLUn7kdXIQ1-xuEzyVACIF9eOT8nQ4IL6zdWpnPAp2nWMCzQA7iZze0r2hMPmbXs']
[debug] yt-dlp version nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds [705f5b84d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: AGB (YoutubeIE), Youtube_AgeGateBypassIE
[debug] Loaded 1835 extractors
[generic] Extracting URL: https://rr2---sn-o097znss.googlevideo.com/videoplayback?expire=1720998193&ei=0QSUZom2IvLAsfIPkpSD2Aw&ip=IPADDRESS&id=o-AFdt598m5GnVUm-wazprY5yJ12PqJolKRekiYB8hCZGC&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=CV&mm=31%2C26&mn=sn-o097znss%2Csn-a5msen76&ms=au%2Conr&mv=m&mvi=2&pl=20&initcwndbps=6988750&bui=AXc671KTlhsbxeao8mqCyNNKO6lxLqleCsC5W2Yko8tbwvgfzIQYUC_EyVZs3sCRaLR5GTNHhcfEpVe8&spc=NO7bAdkqxP-3-193Cfg_eE64e8ibHFnVQFZqayQPZdvYjrP2VWn5g5LKDekO&vprv=1&svpuc=1&mime=video%2Fmp4&ns=BeycHqQePLeO-UE0UgRKgk0Q&rqh=1&gir=yes&clen=386236026&dur=2370.617&lmt=1720967673937005&mt=1720976236&fvip=1&keepalive=yes&c=WEB&sefc=1&txp=6319224&n=Cq_EfvS_0oVAsbRDEeH&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgcX_-hLVnicPU3-Op-zX3tHqcJJVsdRb4tIvNoAKZiO8CIQDlE3aPhDTcqkPIkenDcTFxu-azdzv6bP8ClddEs3P27A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRAIgKXjnkvnOlSN_dBwPqVnB8oKNgLUn7kdXIQ1-xuEzyVACIF9eOT8nQ4IL6zdWpnPAp2nWMCzQA7iZze0r2hMPmbXs
[generic] videoplayback?expire=1720998193&ei=0QSUZom2IvLAsfIPkpSD2Aw&ip=IPADDRESS&id=o-AFdt598m5GnVUm-wazprY5yJ12PqJolKRekiYB8hCZGC&itag=137&aitags=133,134,135,136,137,160,242,243,244,247,248,278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ==&mh=CV&mm=31,26&mn=sn-o097znss,sn-a5msen76&ms=au,onr&mv=m&mvi=2&pl=20&initcwndbps=6988750&bui=AXc671KTlhsbxeao8mqCyNNKO6lxLqleCsC5W2Yko8tbwvgfzIQYUC_EyVZs3sCRaLR5GTNHhcfEpVe8&spc=NO7bAdkqxP-3-193Cfg_eE64e8ibHFnVQFZqayQPZdvYjrP2VWn5g5LKDekO&vprv=1&svpuc=1&mime=video/mp4&ns=BeycHqQePLeO-UE0UgRKgk0Q&rqh=1&gir=yes&clen=386236026&dur=2370: Downloading webpage
```

**Comment by seproDev** [comment]
The JavaScript inside the player JS needs to be executed. You can find the relevant code here: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/youtube.py#L3098

As the player needs to be downloaded, this cannot be done offline. yt-dlp caches the player, but YouTube regularly releases new players.

There is no build in functionality in yt-dlp to just solve the nsig. But knowing the functions, you could probably use the extractor internals. Keep in mind that we do not guarantee API compatibility for extractor code.

**Comment by bashonly** [comment]
If you download the player JS (e.g. grep the webpage for `/s/player/[0-9a-f]+/` and download the URL you find with curl), you can use the yt_dlp python library to decode the `n` parameter.

A python script like this should work:

```py
import sys

from yt_dlp import YoutubeDL
from yt_dlp.jsinterp import JSInterpreter
from yt_dlp.extractor.youtube import YoutubeIE
from yt_dlp.utils import parse_qs, update_url_query

url = sys.argv[1]
js_filepath = sys.argv[2]

with open(js_filepath, encoding='utf-8') as js_file:
    jscode = js_file.read()

funcname = YoutubeIE(YoutubeDL())._extract_n_function_name(jscode)
decoded_nsig = JSInterpreter(jscode).call_function(funcname, parse_qs(url)['n'][0])

print(update_url_query(url, {'n': decoded_nsig}))
```

You would pass the stream URL to it as the first argument and the path of the downloaded player JS file as the second argument, e.g.: 
```
python nsig_decoder.py "STREAM_URL" "base.js"
```

**Comment by barkoder** [comment]
@bashonly

    $ python nsig_decoder.py 'https://rr2---sn-o097znss.googlevideo.com/videoplayback?expire=1720998193\\u0026<LONG_URL>' base.js
    
    Traceback (most recent call last):
      File "nsig_decoder.py", line 14, in <module>
        funcname = YoutubeIE(YoutubeDL())._extract_n_function_name(jscode)
      File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\youtube.py",
     line 3132, in _extract_n_function_name
        funcname, idx = self._search_regex(
      File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\common.py",
    line 1333, in _search_regex
        raise RegexNotFoundError(f'Unable to extract {_name}')
    yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue
    on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on
     the latest version using  yt-dlp -U

Also, do I pass the `\u0026` as is(with an additional `\` prefix  of course) or do I substitute  `\u0026` with `&` ?

**Comment by bashonly** [comment]
is your `yt_dlp` up to date?

you'll have to handle the unicode escape decoding in your script

**Comment by barkoder** [comment]
Yep that was the issue. Should've updated yt-dlp

@bashonly Seriously, Thank You so...so VERY Much!

**Comment by barkoder** [comment]
@bashonly or someone else need help. Bit urgent please!

    Traceback (most recent call last):
      File "yt-dlp-nsig_decoder.py", line 15, in <module>
        decoded_nsig = JSInterpreter(jscode).call_function(funcname, parse_qs(url)['n'][0])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\jsinterp.py", line 858, in call_function
        return self.extract_function(funcname)(args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 5045, in __call__
        return self.func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\jsinterp.py", line 868, in resf
        ret, should_abort = self.interpret_statement(code.replace('\n', ' '), var_stack, allow_recursion - 1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\jsinterp.py", line 185, in interpret_statement
        ret, should_ret = f(self, stmt, local_vars, allow_recursion, *args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\jsinterp.py", line 338, in interpret_statement
        ret, should_return = self.interpret_statement(sub_stmt, local_vars, allow_recursion)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\jsinterp.py", line 185, in interpret_statement
        ret, should_ret = f(self, stmt, local_vars, allow_recursion, *args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\jsinterp.py", line 424, in interpret_statement
        if_expr, expr = self._separate_at_paren(expr.lstrip())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\jsinterp.py", line 286, in _separate_at_paren
        delim = expr and _MATCHING_PARENS[expr[0]]
                         ~~~~~~~~~~~~~~~~^^^^^^^^^
    KeyError: 'r'

**Comment by bashonly** [comment]
call `_fixup_n_function_code` on the js function string, see https://github.com/yt-dlp/yt-dlp/commit/a95ee6d8803fca9157adecf63732ab58bf87fd88

**Comment by barkoder** [comment]
Uhh....I tried cargo culting it. Got errors.

Could you post a comment like [your previous one](https://github.com/yt-dlp/yt-dlp/issues/10469#issuecomment-2227445792) with the full script with any additional changes?

Thanks.

**Comment by barkoder** [comment]
@bashonly

    import sys
    
    from yt_dlp import YoutubeDL
    from yt_dlp.jsinterp import JSInterpreter
    from yt_dlp.extractor.youtube import YoutubeIE
    from yt_dlp.utils import parse_qs, update_url_query
    
    url = sys.argv[1]
    js_filepath = sys.argv[2]
    
    with open(js_filepath, encoding='utf-8') as js_file:
        jscode = js_file.read()
    
    def _fixup_n_function_code(self, argnames, code):
        return argnames, re.sub(
            rf';\s*if\s*\(\s*typeof\s+[a-zA-Z0-9_$]+\s*===?\s*(["\'])undefined\1\s*\)\s*return\s+{argnames[0]};',
            ';', code)
    
    funcname = YoutubeIE(YoutubeDL())._extract_n_function_name(jscode)
    decoded_nsig = JSInterpreter(jscode).call_function(funcname, parse_qs(url)['n'][0], _fixup_n_function_code)
    
    print(update_url_query(url, {'n': decoded_nsig}))

Same error as above again.

**Comment by barkoder** [comment]
It would be great if yt-dlp accepted raw googlevideo URLs with a local copy of the player `base.js`

`yt-dlp --raw-googlevideo-url 'https://googlevideo.com/example' --player /PATH/TO/base.js -g`

And it spit out the true URL.

**Comment by barkoder** [comment]
I have ~75 minutes to solve the sig before the link 404s. @bashonly please help.

**Comment by seproDev** [comment]
Do not repeatedly ping. This isn't your personal support chat for how the googlevideo infrastructure works. This is the bug tracker for yt-dlp.

Manually calling part of the yt-dlp internals is not something officially supported. If you must do it, you can, but don't expect us to provide any kind of support for that. All the yt-dlp code is open source. You are free to look at it yourself to understand how things work.

Passing the raw googlevideo URL and player JS to yt-dlp is outside the scope of yt-dlp. You can write a plugin if you want, but don't expect official support.

**Comment by barkoder** [comment]
@seproDev sorry .

This seems to work.

    import sys
    
    from yt_dlp import YoutubeDL
    from yt_dlp.jsinterp import JSInterpreter
    from yt_dlp.extractor.youtube import YoutubeIE
    from yt_dlp.utils import parse_qs, update_url_query
    
    url = sys.argv[1]
    js_filepath = sys.argv[2]
    
    with open(js_filepath, encoding='utf-8') as js_file:
        jscode = js_file.read()
    
    def _fixup_n_function_code(self, argnames, code):
        return argnames, re.sub(
            rf';\s*if\s*\(\s*typeof\s+[a-zA-Z0-9_$]+\s*===?\s*(["\'])undefined\1\s*\)\s*return\s+{argnames[0]};',
            ';', code)
    
    ie = YoutubeIE(YoutubeDL())
    funcname = ie._extract_n_function_name(jscode)
    jsi = JSInterpreter(jscode)
    func = jsi.extract_function_from_code(*ie._fixup_n_function_code(*jsi.extract_function_code(funcname)))
    decoded_nsig = func([parse_qs(url)['n'][0]])
    print(update_url_query(url, {'n': decoded_nsig}))
    
Thanks to @BrenBarn on the [python matrix room](https://app.element.io/#/room/#python:matrix.org)
