### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ipsmile** [yt-dlp/yt-dlp#10478]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Download command failed to retrieve a Youtube video in a playlist which can view normally in a browser.
Expect the command to work as intended.
Verbose command outputs follows.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.youtube.com/watch?v=alEQAsl_Rjo
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=alEQAsl_Rjo']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (zip)
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-5.15.0-113-generic-x86_64-with-glibc2.35 (OpenSSL 1.1.1u  30 May 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: brotli-None, certifi-2023.07.22, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.41.2, urllib3-1.26.16
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.09 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=alEQAsl_Rjo
[youtube] alEQAsl_Rjo: Downloading webpage
[youtube] alEQAsl_Rjo: Downloading ios player API JSON
[debug] Loading youtube-nsig.820bff3b from cache
[debug] [youtube] Decrypted nsig V2yA_gsT7_XVMFhg => 7hNl0XfMoTTCkg
[debug] Loading youtube-nsig.820bff3b from cache
[debug] [youtube] Decrypted nsig yktJgExWiPYBVamK => nqKjI1vBr6K3ww
[youtube] alEQAsl_Rjo: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] alEQAsl_Rjo: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr4---sn-a5mekndl.googlevideo.com/videoplayback?expire=1721106815&ei=H62VZp3vD9qP2_gP0v-loAc&ip=108.207.212.38&id=o-AAYRTGbF88O8BA0586EVnSzs8PU3inBHWJFcrHh0306L&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=_w&mm=31%2C26&mn=sn-a5mekndl%2Csn-o097znze&ms=au%2Conr&mv=m&mvi=4&pl=20&initcwndbps=866250&bui=AXc671J9kyUeKtLmjbWVnbJSNIo8fbMqBNelYmk-9XgG5gOGekbWpwpUGTFxAfXVnzMmoXlUMeD3ixqs&spc=NO7bAXHLOu5QwKqOgtsuhKqzqIm7MjYAzaUCcQZ0Edq-jUNK0pTiBsL7hnv5&vprv=1&svpuc=1&mime=video%2Fwebm&ns=gAZbsdJKijHd331Bb_qUTiMQ&rqh=1&gir=yes&clen=1415937471&dur=21209.833&lmt=1718210506838477&mt=1721084732&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=630F224&n=nqKjI1vBr6K3ww&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAPE3NNdxtTkcGBpRzT8wogenKTIYZ7wlHdfVs_WGjLrXAiBSZRbbEdRhS-bW3QL31IF5mE4rcv9h_ntkPmEHZRjDzw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgMnfgBQKdcwRUhe8nHJJsmGB2RvDL9yC5-CgWX9nbFJkCIQDmuIUWyPK0304Iu9oMr_4rCAnXEXQf5FDglpURw7hv-A%3D%3D"
ERROR: unable to open for writing: [Errno 2] No such file or directory: '【撼龙棺】续集1：我出生的那天，爹生食心脏，爷爷将名字刻在了灵位上......#悬疑灵异#小说#恐怖 [alEQAsl_Rjo].f248.webm.part'
Traceback (most recent call last):
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 591, in sanitize_open
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 1593, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '【撼龙棺】续集1：我出生的那天，爹生食心脏，爷爷将名字刻在了灵位上......#悬疑灵异#小说#恐怖 [alEQAsl_Rjo].f248.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 250, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5212, in report_retry
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 593, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: '【撼龙棺】续集1：我出生的那天，爹生食心脏，爷爷将名字刻在了灵位上......#悬疑灵异#小说#恐怖 [alEQAsl_Rjo].f248.webm.part'


[debug] Invoking http downloader on "https://rr4---sn-a5mekndl.googlevideo.com/videoplayback?expire=1721106815&ei=H62VZp3vD9qP2_gP0v-loAc&ip=108.207.212.38&id=o-AAYRTGbF88O8BA0586EVnSzs8PU3inBHWJFcrHh0306L&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=_w&mm=31%2C26&mn=sn-a5mekndl%2Csn-o097znze&ms=au%2Conr&mv=m&mvi=4&pl=20&initcwndbps=866250&bui=AXc671J9kyUeKtLmjbWVnbJSNIo8fbMqBNelYmk-9XgG5gOGekbWpwpUGTFxAfXVnzMmoXlUMeD3ixqs&spc=NO7bAXHLOu5QwKqOgtsuhKqzqIm7MjYAzaUCcQZ0Edq-jUNK0pTiBsL7hnv5&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=gAZbsdJKijHd331Bb_qUTiMQ&rqh=1&gir=yes&clen=314105753&dur=21209.861&lmt=1718218437445656&mt=1721084732&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=6308224&n=nqKjI1vBr6K3ww&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAIdXR6k4712-OvU41DTFa_4kmkJwAShWJrsicPJVZddVAiEA1Vom2JMROz74aX4nWNKmeW3kmTbM_LQzXSmf4s3M7lc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgMnfgBQKdcwRUhe8nHJJsmGB2RvDL9yC5-CgWX9nbFJkCIQDmuIUWyPK0304Iu9oMr_4rCAnXEXQf5FDglpURw7hv-A%3D%3D"
ERROR: unable to open for writing: [Errno 2] No such file or directory: '【撼龙棺】续集1：我出生的那天，爹生食心脏，爷爷将名字刻在了灵位上......#悬疑灵异#小说#恐怖 [alEQAsl_Rjo].f251.webm.part'
Traceback (most recent call last):
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 591, in sanitize_open
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 1593, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '【撼龙棺】续集1：我出生的那天，爹生食心脏，爷爷将名字刻在了灵位上......#悬疑灵异#小说#恐怖 [alEQAsl_Rjo].f251.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 250, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5212, in report_retry
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 593, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: '【撼龙棺】续集1：我出生的那天，爹生食心脏，爷爷将名字刻在了灵位上......#悬疑灵异#小说#恐怖 [alEQAsl_Rjo].f251.webm.part'


ERROR: Unable to download video: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3484, in process_info
    info_dict['__finaldir'] = os.path.dirname(os.path.abspath(encodeFilename(full_filename)))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 404, in abspath
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1778, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1837, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3011, in process_video_result
    self.process_info(new_info)
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tssoon/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3490, in process_info
    raise UnavailableVideoError(err)
yt_dlp.utils.UnavailableVideoError: Unable to download video: [Errno 2] No such file or directory
```

**Comment by bashonly** [comment]
try adding `-o "%(title).100B [%(id)s].%(ext)s` to your command, or if that fails, change `100B` to `75B` and so forth
