### ISSUE TITLE
How to download the best video but transcode it to h264 in a mov file?

### ISSUE THREAD

**Issue by stephane-archer** [yt-dlp/yt-dlp#10500]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to download the best video (equivalent to `-f bestvideo*+bestaudio/best`) but transcode it to h264 in a mov file.
Here is what I tried:
``` fish
yt-dlp -v --recode-video 'h264>mov' --merge-output mov "https://www.youtube.com/watch?v=PorfLSr3DDI&pp=ygULY3BwIGNvbiBnZGI%3D"
```
but I get the following error:
```
[mov @ 0x7fd4fd804fc0] vp9 only supported in MP4.
[out#0/mov @ 0x7fd4fd804b40] Could not write header (incorrect codec parameters ?): Invalid argument
Conversion failed!
```
but I asked for transcoding from vp9 to h264

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '--recode-video', 'h264>mov', '--merge-output', 'mov', 'https://www.youtube.com/watch?v=PorfLSr3DDI&pp=ygULY3BwIGNvbiBnZGI%3D']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (pip)
[debug] Python 3.12.4 (CPython x86_64 64bit) - macOS-14.5-x86_64-i386-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=PorfLSr3DDI&pp=ygULY3BwIGNvbiBnZGI%3D
[youtube] PorfLSr3DDI: Downloading webpage
[youtube] PorfLSr3DDI: Downloading ios player API JSON
[debug] Loading youtube-nsig.8eff86d5 from cache
[debug] [youtube] Decrypted nsig 5rNmPNeuXuaH4OiovJs => b_d6U1fJsJR0Uw
[debug] Loading youtube-nsig.8eff86d5 from cache
[debug] [youtube] Decrypted nsig 6ymA41DZxqLH4QmClGA => BY3iuPU6auRw3A
[youtube] PorfLSr3DDI: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] PorfLSr3DDI: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr4---sn-25glenld.googlevideo.com/videoplayback?expire=1721342748&ei=vEaZZrC3MKOAp-oPuMSV6Ag&ip=2a01%3Acb00%3Ab1d%3A1400%3A9903%3A61fe%3Aaada%3A9107&id=o-AIKjDj7TNBt9Ku6V6IJS8wDihE6uchPwVFJtaq5veqav&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=__&mm=31%2C29&mn=sn-25glenld%2Csn-25ge7nzr&ms=au%2Crdu&mv=m&mvi=4&pl=43&initcwndbps=1597500&bui=AXc671K2udaK_2vc_peXd6rv7sayGaBTdbpoozkyFOPzhq2vaICdgmABDTdi2w2ffsnv6WVz6MxFSyNX&spc=NO7bAdcUzSi6rzM7yaNI-lbn1v49E79ocSVf1GnYASXwNjLD4KhSdtJ3pNVb&vprv=1&svpuc=1&mime=video%2Fwebm&ns=OhPayzgaX9FqqhB-R4kBTiYQ&rqh=1&gir=yes&clen=128486702&dur=886.052&lmt=1445417381187105&mt=1721320853&fvip=1&keepalive=yes&c=WEB&sefc=1&n=BY3iuPU6auRw3A&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgOuHiGcqQt9iVZ8JfKN7qnhKKbl7as7FojxNWM9mhGyECIQCZs7NsU_5w3wU4U2j5pekK_TyhTnlwQ4ILRaahjOp1ow%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIhAP98CUVM_YpuJKCOBWBmhaYMezXAIDzDN12p2shNWEthAiA3f2RCRZfiOWjTkj75P6CVLhCkeMEbqR5DiyFIwnBLkg%3D%3D"
[download] Destination: CppCon 2015： Greg Law ＂ Give me 15 minutes & I'll change your view of GDB＂ [PorfLSr3DDI].f248.webm

[download]   0.0% of  122.53MiB at  213.66KiB/s ETA 09:49
[download]   0.0% of  122.53MiB at  544.24KiB/s ETA 03:50
[download]   0.0% of  122.53MiB at    1.13MiB/s ETA 01:48
[download]   0.0% of  122.53MiB at    2.25MiB/s ETA 00:54
[download]   0.0% of  122.53MiB at    2.59MiB/s ETA 00:47
[download]   0.1% of  122.53MiB at    2.69MiB/s ETA 00:45
[download]   0.1% of  122.53MiB at    1.60MiB/s ETA 01:16
[download]   0.2% of  122.53MiB at    1.38MiB/s ETA 01:28
[download]   0.4% of  122.53MiB at    1.67MiB/s ETA 01:13
[download]   0.8% of  122.53MiB at    1.99MiB/s ETA 01:00
[download]   1.6% of  122.53MiB at    2.15MiB/s ETA 00:56
[download]   3.3% of  122.53MiB at    2.27MiB/s ETA 00:52
[download]   5.2% of  122.53MiB at    2.31MiB/s ETA 00:50
[download]   7.2% of  122.53MiB at    2.35MiB/s ETA 00:48
[download]   7.8% of  122.53MiB at    2.34MiB/s ETA 00:48
[download]   7.8% of  122.53MiB at  144.47KiB/s ETA 13:22
[download]   7.8% of  122.53MiB at  371.47KiB/s ETA 05:12
[download]   7.8% of  122.53MiB at  826.84KiB/s ETA 02:20
[download]   7.8% of  122.53MiB at    1.66MiB/s ETA 01:08
[download]   7.8% of  122.53MiB at    2.08MiB/s ETA 00:54
[download]   7.8% of  122.53MiB at    2.32MiB/s ETA 00:48
[download]   7.9% of  122.53MiB at    2.44MiB/s ETA 00:46
[download]   8.0% of  122.53MiB at    2.43MiB/s ETA 00:46
[download]   8.2% of  122.53MiB at    2.19MiB/s ETA 00:51
[download]   8.6% of  122.53MiB at    2.20MiB/s ETA 00:51
[download]   9.4% of  122.53MiB at    1.89MiB/s ETA 00:58
[download]  10.8% of  122.53MiB at    2.05MiB/s ETA 00:53
[download]  12.6% of  122.53MiB at    2.19MiB/s ETA 00:48
[download]  14.7% of  122.53MiB at    2.26MiB/s ETA 00:46
[download]  15.6% of  122.53MiB at    2.28MiB/s ETA 00:45
[download]  15.6% of  122.53MiB at  223.07KiB/s ETA 07:55
[download]  15.6% of  122.53MiB at  576.91KiB/s ETA 03:03
[download]  15.6% of  122.53MiB at    1.19MiB/s ETA 01:27
[download]  15.6% of  122.53MiB at    2.33MiB/s ETA 00:44
[download]  15.6% of  122.53MiB at    2.46MiB/s ETA 00:42
[download]  15.6% of  122.53MiB at    2.68MiB/s ETA 00:38
[download]  15.7% of  122.53MiB at    2.57MiB/s ETA 00:40
[download]  15.8% of  122.53MiB at    2.53MiB/s ETA 00:40
[download]  16.0% of  122.53MiB at    2.32MiB/s ETA 00:44
[download]  16.4% of  122.53MiB at    1.96MiB/s ETA 00:52
[download]  17.2% of  122.53MiB at    2.19MiB/s ETA 00:46
[download]  18.8% of  122.53MiB at    2.33MiB/s ETA 00:42
[download]  20.9% of  122.53MiB at    2.38MiB/s ETA 00:40
[download]  22.9% of  122.53MiB at    2.35MiB/s ETA 00:40
[download]  23.5% of  122.53MiB at    2.33MiB/s ETA 00:40
[download]  23.5% of  122.53MiB at  509.70KiB/s ETA 03:09
[download]  23.5% of  122.53MiB at    1.10MiB/s ETA 01:25
[download]  23.5% of  122.53MiB at    2.06MiB/s ETA 00:45
[download]  23.5% of  122.53MiB at    3.98MiB/s ETA 00:23
[download]  23.5% of  122.53MiB at    3.49MiB/s ETA 00:26
[download]  23.5% of  122.53MiB at    2.99MiB/s ETA 00:31
[download]  23.6% of  122.53MiB at    2.75MiB/s ETA 00:34
[download]  23.7% of  122.53MiB at    2.26MiB/s ETA 00:41
[download]  23.9% of  122.53MiB at    2.15MiB/s ETA 00:43
[download]  24.3% of  122.53MiB at    2.31MiB/s ETA 00:40
[download]  25.1% of  122.53MiB at    2.26MiB/s ETA 00:40
[download]  26.7% of  122.53MiB at    2.01MiB/s ETA 00:44
[download]  28.2% of  122.53MiB at    2.04MiB/s ETA 00:43
[download]  29.9% of  122.53MiB at    2.12MiB/s ETA 00:40
[download]  31.6% of  122.53MiB at    2.17MiB/s ETA 00:38
[download]  31.6% of  122.53MiB at  Unknown B/s ETA Unknown
[download]  31.6% of  122.53MiB at    2.67MiB/s ETA 00:31  
[download]  31.6% of  122.53MiB at    4.31MiB/s ETA 00:19
[download]  31.6% of  122.53MiB at    2.30MiB/s ETA 00:36
[download]  31.6% of  122.53MiB at    4.29MiB/s ETA 00:19
[download]  31.7% of  122.53MiB at    8.13MiB/s ETA 00:10
[download]  31.7% of  122.53MiB at   15.15MiB/s ETA 00:05
[download]  31.8% of  122.53MiB at    1.60MiB/s ETA 00:52
[download]  32.0% of  122.53MiB at    2.30MiB/s ETA 00:36
[download]  32.4% of  122.53MiB at    2.01MiB/s ETA 00:41
[download]  33.2% of  122.53MiB at    2.08MiB/s ETA 00:39
[download]  34.9% of  122.53MiB at    1.85MiB/s ETA 00:43
[download]  36.2% of  122.53MiB at    2.00MiB/s ETA 00:39
[download]  38.3% of  122.53MiB at    2.12MiB/s ETA 00:35
[download]  39.6% of  122.53MiB at    2.18MiB/s ETA 00:33
[download]  39.6% of  122.53MiB at  147.52KiB/s ETA 08:34
[download]  39.6% of  122.53MiB at  379.51KiB/s ETA 03:19
[download]  39.6% of  122.53MiB at  822.39KiB/s ETA 01:32
[download]  39.6% of  122.53MiB at    1.64MiB/s ETA 00:45
[download]  39.6% of  122.53MiB at    2.17MiB/s ETA 00:34
[download]  39.7% of  122.53MiB at    2.44MiB/s ETA 00:30
[download]  39.7% of  122.53MiB at    2.53MiB/s ETA 00:29
[download]  39.8% of  122.53MiB at    1.90MiB/s ETA 00:38
[download]  40.0% of  122.53MiB at    1.54MiB/s ETA 00:47
[download]  40.4% of  122.53MiB at    1.82MiB/s ETA 00:40
[download]  41.3% of  122.53MiB at    1.94MiB/s ETA 00:37
[download]  42.9% of  122.53MiB at    1.88MiB/s ETA 00:37
[download]  44.4% of  122.53MiB at    1.94MiB/s ETA 00:35
[download]  46.1% of  122.53MiB at    2.03MiB/s ETA 00:32
[download]  47.4% of  122.53MiB at    2.10MiB/s ETA 00:30
[download]  47.4% of  122.53MiB at  Unknown B/s ETA Unknown
[download]  47.4% of  122.53MiB at  Unknown B/s ETA Unknown
[download]  47.4% of  122.53MiB at    6.22MiB/s ETA 00:10  
[download]  47.4% of  122.53MiB at    9.68MiB/s ETA 00:06
[download]  47.4% of  122.53MiB at   15.50MiB/s ETA 00:04
[download]  47.5% of  122.53MiB at   25.72MiB/s ETA 00:02
[download]  47.5% of  122.53MiB at    7.10MiB/s ETA 00:09
[download]  47.6% of  122.53MiB at    2.73MiB/s ETA 00:23
[download]  47.8% of  122.53MiB at    2.16MiB/s ETA 00:29
[download]  48.2% of  122.53MiB at    2.05MiB/s ETA 00:30
[download]  49.1% of  122.53MiB at    2.15MiB/s ETA 00:29
[download]  50.7% of  122.53MiB at    2.17MiB/s ETA 00:27
[download]  52.5% of  122.53MiB at    2.03MiB/s ETA 00:28
[download]  53.9% of  122.53MiB at    2.12MiB/s ETA 00:26
[download]  55.3% of  122.53MiB at    2.17MiB/s ETA 00:25
[download]  55.3% of  122.53MiB at  Unknown B/s ETA Unknown
[download]  55.3% of  122.53MiB at  Unknown B/s ETA Unknown
[download]  55.3% of  122.53MiB at    6.29MiB/s ETA 00:08  
[download]  55.3% of  122.53MiB at    9.51MiB/s ETA 00:05
[download]  55.3% of  122.53MiB at   13.77MiB/s ETA 00:03
[download]  55.4% of  122.53MiB at   22.04MiB/s ETA 00:02
[download]  55.4% of  122.53MiB at   37.37MiB/s ETA 00:01
[download]  55.5% of  122.53MiB at    2.08MiB/s ETA 00:26
[download]  55.7% of  122.53MiB at    2.27MiB/s ETA 00:23
[download]  56.1% of  122.53MiB at    2.39MiB/s ETA 00:22
[download]  57.0% of  122.53MiB at    2.42MiB/s ETA 00:21
[download]  58.6% of  122.53MiB at    2.45MiB/s ETA 00:20
[download]  60.6% of  122.53MiB at    2.23MiB/s ETA 00:21
[download]  62.2% of  122.53MiB at    2.21MiB/s ETA 00:20
[download]  63.3% of  122.53MiB at    2.22MiB/s ETA 00:20
[download]  63.3% of  122.53MiB at  155.94KiB/s ETA 04:56
[download]  63.3% of  122.53MiB at  419.01KiB/s ETA 01:50
[download]  63.3% of  122.53MiB at  911.38KiB/s ETA 00:50
[download]  63.3% of  122.53MiB at    1.77MiB/s ETA 00:25
[download]  63.3% of  122.53MiB at    2.25MiB/s ETA 00:20
[download]  63.3% of  122.53MiB at    2.38MiB/s ETA 00:18
[download]  63.4% of  122.53MiB at    2.51MiB/s ETA 00:17
[download]  63.5% of  122.53MiB at    1.12MiB/s ETA 00:40
[download]  63.7% of  122.53MiB at    1.11MiB/s ETA 00:40
[download]  64.1% of  122.53MiB at    1.51MiB/s ETA 00:29
[download]  64.9% of  122.53MiB at    1.90MiB/s ETA 00:22
[download]  66.5% of  122.53MiB at    2.10MiB/s ETA 00:19
[download]  68.5% of  122.53MiB at    2.08MiB/s ETA 00:18
[download]  70.1% of  122.53MiB at    1.95MiB/s ETA 00:18
[download]  71.3% of  122.53MiB at    1.97MiB/s ETA 00:17
[download]  71.3% of  122.53MiB at  215.80KiB/s ETA 02:47
[download]  71.4% of  122.53MiB at  524.20KiB/s ETA 01:08
[download]  71.4% of  122.53MiB at    1.09MiB/s ETA 00:32
[download]  71.4% of  122.53MiB at    2.16MiB/s ETA 00:16
[download]  71.4% of  122.53MiB at    3.01MiB/s ETA 00:11
[download]  71.4% of  122.53MiB at    2.50MiB/s ETA 00:14
[download]  71.5% of  122.53MiB at    2.60MiB/s ETA 00:13
[download]  71.6% of  122.53MiB at    1.84MiB/s ETA 00:18
[download]  71.8% of  122.53MiB at    1.78MiB/s ETA 00:19
[download]  72.2% of  122.53MiB at    2.08MiB/s ETA 00:16
[download]  73.0% of  122.53MiB at    2.27MiB/s ETA 00:14
[download]  74.6% of  122.53MiB at    2.28MiB/s ETA 00:13
[download]  76.5% of  122.53MiB at    2.20MiB/s ETA 00:13
[download]  78.2% of  122.53MiB at    2.11MiB/s ETA 00:12
[download]  79.3% of  122.53MiB at    2.16MiB/s ETA 00:11
[download]  79.3% of  122.53MiB at  287.03KiB/s ETA 01:30
[download]  79.3% of  122.53MiB at  690.61KiB/s ETA 00:37
[download]  79.3% of  122.53MiB at    1.45MiB/s ETA 00:17
[download]  79.3% of  122.53MiB at    2.88MiB/s ETA 00:08
[download]  79.3% of  122.53MiB at    2.44MiB/s ETA 00:10
[download]  79.3% of  122.53MiB at  575.65KiB/s ETA 00:45
[download]  79.4% of  122.53MiB at    1.11MiB/s ETA 00:22
[download]  79.5% of  122.53MiB at    1.71MiB/s ETA 00:14
[download]  79.7% of  122.53MiB at    1.85MiB/s ETA 00:13
[download]  80.1% of  122.53MiB at    1.92MiB/s ETA 00:12
[download]  80.9% of  122.53MiB at    2.05MiB/s ETA 00:11
[download]  82.5% of  122.53MiB at    2.04MiB/s ETA 00:10
[download]  84.2% of  122.53MiB at    1.91MiB/s ETA 00:10
[download]  85.6% of  122.53MiB at    2.00MiB/s ETA 00:08
[download]  87.3% of  122.53MiB at    2.08MiB/s ETA 00:07
[download]  87.4% of  122.53MiB at  145.05KiB/s ETA 01:49
[download]  87.4% of  122.53MiB at  384.76KiB/s ETA 00:41
[download]  87.4% of  122.53MiB at  841.34KiB/s ETA 00:18
[download]  87.4% of  122.53MiB at    1.66MiB/s ETA 00:09
[download]  87.4% of  122.53MiB at    2.10MiB/s ETA 00:07
[download]  87.4% of  122.53MiB at    2.39MiB/s ETA 00:06
[download]  87.5% of  122.53MiB at    2.44MiB/s ETA 00:06
[download]  87.6% of  122.53MiB at    2.46MiB/s ETA 00:06
[download]  87.8% of  122.53MiB at    2.47MiB/s ETA 00:06
[download]  88.2% of  122.53MiB at    2.48MiB/s ETA 00:05
[download]  89.0% of  122.53MiB at    2.49MiB/s ETA 00:05
[download]  90.6% of  122.53MiB at    2.50MiB/s ETA 00:04
[download]  92.7% of  122.53MiB at    2.51MiB/s ETA 00:03
[download]  94.7% of  122.53MiB at    2.51MiB/s ETA 00:02
[download]  95.4% of  122.53MiB at    2.52MiB/s ETA 00:02
[download]  95.4% of  122.53MiB at  Unknown B/s ETA Unknown
[download]  95.4% of  122.53MiB at    2.51MiB/s ETA 00:02  
[download]  95.4% of  122.53MiB at    4.14MiB/s ETA 00:01
[download]  95.4% of  122.53MiB at    6.91MiB/s ETA 00:00
[download]  95.4% of  122.53MiB at   11.54MiB/s ETA 00:00
[download]  95.4% of  122.53MiB at   19.19MiB/s ETA 00:00
[download]  95.5% of  122.53MiB at   28.96MiB/s ETA 00:00
[download]  95.6% of  122.53MiB at    2.02MiB/s ETA 00:02
[download]  95.8% of  122.53MiB at    2.88MiB/s ETA 00:01
[download]  96.2% of  122.53MiB at    1.94MiB/s ETA 00:02
[download]  97.0% of  122.53MiB at    1.86MiB/s ETA 00:01
[download]  98.5% of  122.53MiB at    2.13MiB/s ETA 00:00
[download] 100.0% of  122.53MiB at    2.24MiB/s ETA 00:00
[download] 100% of  122.53MiB in 00:00:58 at 2.09MiB/s   
[debug] Invoking http downloader on "https://rr4---sn-25glenld.googlevideo.com/videoplayback?expire=1721342748&ei=vEaZZrC3MKOAp-oPuMSV6Ag&ip=2a01%3Acb00%3Ab1d%3A1400%3A9903%3A61fe%3Aaada%3A9107&id=o-AIKjDj7TNBt9Ku6V6IJS8wDihE6uchPwVFJtaq5veqav&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=__&mm=31%2C29&mn=sn-25glenld%2Csn-25ge7nzr&ms=au%2Crdu&mv=m&mvi=4&pl=43&initcwndbps=1597500&bui=AXc671K2udaK_2vc_peXd6rv7sayGaBTdbpoozkyFOPzhq2vaICdgmABDTdi2w2ffsnv6WVz6MxFSyNX&spc=NO7bAdcUzSi6rzM7yaNI-lbn1v49E79ocSVf1GnYASXwNjLD4KhSdtJ3pNVb&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=OhPayzgaX9FqqhB-R4kBTiYQ&rqh=1&gir=yes&clen=13017178&dur=886.101&lmt=1445417007612292&mt=1721320853&fvip=1&keepalive=yes&c=WEB&sefc=1&n=BY3iuPU6auRw3A&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAIS1IHP1otnWpoPrV2xjh7WkuroWTUXOW6Msa5ZzFNcEAiEAq69e2jRL0_sZvo_Td9250EUOmZkhH5Tb05yjf3f96Cg%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIhAP98CUVM_YpuJKCOBWBmhaYMezXAIDzDN12p2shNWEthAiA3f2RCRZfiOWjTkj75P6CVLhCkeMEbqR5DiyFIwnBLkg%3D%3D"
[download] Destination: CppCon 2015： Greg Law ＂ Give me 15 minutes & I'll change your view of GDB＂ [PorfLSr3DDI].f251.webm

[download]   0.0% of   12.41MiB at  175.35KiB/s ETA 01:12
[download]   0.0% of   12.41MiB at  476.57KiB/s ETA 00:26
[download]   0.1% of   12.41MiB at  987.89KiB/s ETA 00:12
[download]   0.1% of   12.41MiB at    1.91MiB/s ETA 00:06
[download]   0.2% of   12.41MiB at    2.43MiB/s ETA 00:05
[download]   0.5% of   12.41MiB at    1.49MiB/s ETA 00:08
[download]   1.0% of   12.41MiB at    2.49MiB/s ETA 00:04
[download]   2.0% of   12.41MiB at    2.09MiB/s ETA 00:05
[download]   4.0% of   12.41MiB at    1.95MiB/s ETA 00:06
[download]   8.0% of   12.41MiB at    1.97MiB/s ETA 00:05
[download]  16.1% of   12.41MiB at    2.21MiB/s ETA 00:04
[download]  32.2% of   12.41MiB at    2.35MiB/s ETA 00:03
[download]  52.5% of   12.41MiB at    2.41MiB/s ETA 00:02
[download]  72.7% of   12.41MiB at    2.33MiB/s ETA 00:01
[download]  80.3% of   12.41MiB at    2.35MiB/s ETA 00:01
[download]  80.3% of   12.41MiB at  Unknown B/s ETA Unknown
[download]  80.3% of   12.41MiB at  Unknown B/s ETA Unknown
[download]  80.4% of   12.41MiB at    5.49MiB/s ETA 00:00  
[download]  80.4% of   12.41MiB at    8.78MiB/s ETA 00:00
[download]  80.5% of   12.41MiB at   12.99MiB/s ETA 00:00
[download]  80.8% of   12.41MiB at   20.60MiB/s ETA 00:00
[download]  81.3% of   12.41MiB at    7.89MiB/s ETA 00:00
[download]  82.3% of   12.41MiB at    3.03MiB/s ETA 00:00
[download]  84.3% of   12.41MiB at    2.39MiB/s ETA 00:00
[download]  88.4% of   12.41MiB at    2.45MiB/s ETA 00:00
[download]  96.4% of   12.41MiB at    2.48MiB/s ETA 00:00
[download] 100.0% of   12.41MiB at    2.49MiB/s ETA 00:00
[download] 100% of   12.41MiB in 00:00:05 at 2.13MiB/s   
[Merger] Merging formats into "CppCon 2015： Greg Law ＂ Give me 15 minutes & I'll change your view of GDB＂ [PorfLSr3DDI].mov"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:CppCon 2015： Greg Law ＂ Give me 15 minutes & I'"'"'ll change your view of GDB＂ [PorfLSr3DDI].f248.webm' -i 'file:CppCon 2015： Greg Law ＂ Give me 15 minutes & I'"'"'ll change your view of GDB＂ [PorfLSr3DDI].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:CppCon 2015： Greg Law ＂ Give me 15 minutes & I'"'"'ll change your view of GDB＂ [PorfLSr3DDI].temp.mov'
[debug] ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, matroska,webm, from 'file:CppCon 2015： Greg Law ＂ Give me 15 minutes & I'll change your view of GDB＂ [PorfLSr3DDI].f248.webm':
  Metadata:
    encoder         : google
  Duration: 00:14:46.05, start: 0.000000, bitrate: 1160 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv), 1920x1080, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn (default)
Input #1, matroska,webm, from 'file:CppCon 2015： Greg Law ＂ Give me 15 minutes & I'll change your view of GDB＂ [PorfLSr3DDI].f251.webm':
  Metadata:
    encoder         : google
  Duration: 00:14:46.10, start: -0.007000, bitrate: 117 kb/s
  Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
[mov @ 0x7fd4fd804fc0] vp9 only supported in MP4.
[out#0/mov @ 0x7fd4fd804b40] Could not write header (incorrect codec parameters ?): Invalid argument
Conversion failed!

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3556, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3738, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3720, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3698, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 840, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 330, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 368, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by bashonly** [comment]
try only `--recode mov`

**Comment by stephane-archer** [comment]
@bashonly this works perfectly, thank you. 
I would not have found it without you because `--recode` is not in the documentation from what I can see.
Would you be able to add it?

**Comment by bashonly** [comment]
`--recode` is just a shortened version of `--recode-video`; it is the exact same option. You can shorten any option until it becomes ambiguous.

e.g. `--rec` currently also works for `--recode-video`, but passing `--re` will give you this error:

```
yt-dlp: error: ambiguous option: --re (--recode-video, --referer, --reject-title, --remove-chapters, --remux-video, --replace-in-metadata, --resize-buffer, --restrict-filenames, --retries, --retry-sleep?)
```
