### ISSUE TITLE
add support for germanupa.de

### ISSUE THREAD

**Issue by sjjh** [yt-dlp/yt-dlp#10527]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Germany (and probably more)

### Example URLs

https://germanupa.de/mediathek/4-figma-beratung-deine-sprechstunde-fuer-figma-fragen

### Provide a description that is worded well enough to be understood

yt-dlp throws error "website not supported". On https://germanupa.de/mediathek/ more media is included.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU "https://germanupa.de/mediathek/4-figma-beratung-deine-sprechstunde-fuer-figma-fragen"
[debug] Command-line config: ['-vU', 'https://germanupa.de/mediathek/4-figma-beratung-deine-sprechstunde-fuer-figma-fragen']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-44-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://germanupa.de/mediathek/4-figma-beratung-deine-sprechstunde-fuer-figma-fragen
[generic] 4-figma-beratung-deine-sprechstunde-fuer-figma-fragen: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 4-figma-beratung-deine-sprechstunde-fuer-figma-fragen: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://germanupa.de/mediathek/4-figma-beratung-deine-sprechstunde-fuer-figma-fragen
Traceback (most recent call last):
  File "/home/simon/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/simon/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/home/simon/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/simon/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://germanupa.de/mediathek/4-figma-beratung-deine-sprechstunde-fuer-figma-fragen
```
```

**Comment by sjjh** [comment]
> The video above is downloadable with yt-dlp https://player.vimeo.com/video/909179246?app_id=122963 --add-headers "Referer:https://germanupa.de/"

Not sure if this could be automated by yt-dlp.

**Comment by grqz** [comment]
try this patch
```diff
diff --git a/yt_dlp/extractor/_extractors.py b/yt_dlp/extractor/_extractors.py
index d2140bc52..057a01482 100644
--- a/yt_dlp/extractor/_extractors.py
+++ b/yt_dlp/extractor/_extractors.py
@@ -729,6 +729,7 @@
     GeniusIE,
     GeniusLyricsIE,
 )
+from .germanupa import GermanupaIE
 from .getcourseru import (
     GetCourseRuIE,
     GetCourseRuPlayerIE,
diff --git a/yt_dlp/extractor/germanupa.py b/yt_dlp/extractor/germanupa.py
new file mode 100644
index 000000000..6e9279f35
--- /dev/null
+++ b/yt_dlp/extractor/germanupa.py
@@ -0,0 +1,21 @@
+from .common import InfoExtractor
+
+
+class GermanupaIE(InfoExtractor):
+    _EMBED_REGEX = [r'<iframe[^>]+data-src\s*?=\s*?([\'"])(?P<url>[^"]+)\1']
+    _VALID_URL = False
+    _TESTS = [{
+        'url': 'https://germanupa.de/mediathek/4-figma-beratung-deine-sprechstunde-fuer-figma-fragen',
+        'info_dict': {
+            'id': '909179246',
+            'title': 'Tutorial: #4 Figma Beratung - Deine Sprechstunde für Figma-Fragen',
+            'ext': 'mp4',
+        }
+    }, {
+        'url': 'https://germanupa.de/mediathek/live-vom-ux-festival-neuigkeiten-von-figma-jobmarkt-agenturszene-interview-zu-sustainable',
+        'info_dict': {
+            'id': '1867346676',
+            'title': 'Live vom UX Festival: Neuigkeiten von Figma, Jobmarkt, Agenturszene & Interview zu Sustainable UX',
+            'ext': 'opus',
+        },
+    }]
```

**Comment by grqz** [comment]
@sjjh can you access `Nur für Mitglieder` videos?
Please give me the page source of `https://germanupa.de/mediathek/ux-festival-2024-usability-tests-und-ai` if you can watch the video.
i don't need an account. an HTML document is enough

**Comment by sjjh** [comment]
Is this section is enough or do you need the complete page source?
```
<section class="mediathek-item">
    <div class="container">
              <div class="embed-responsive embed-responsive-16by9">
  <iframe data-cookiefirst-category="functional" data-name="functional" data-src="https://germanupa.de/media/oembed?url=https%3A//vimeo.com/986994430/4178248b56%3Fshare%3Dcopy&amp;max_width=0&amp;max_height=0&amp;hash=t5ZHD0HCCS5hhxH0UEDjsqf9n0aCNErid8zPLolpP7k" frameborder="0" allowtransparency="" class="media-oembed-content" title="UX Festival 2024 &quot;Usability Tests und AI&quot; von Lennart Weber" width="426" height="240"></iframe><div class="cookiefirst-disabled-resource">Bitte <button onclick="CookieFirst.acceptCategory('functional')">Funktionale Cookies akzeptieren</button> um dieses Video zu sehen.</div>
</div>

          </div>
  </section>
```
