### ISSUE TITLE
twitch:stream: Rewind or "--live-from-start" not working for live streams that support it

### ISSUE THREAD

**Issue by superbonaci** [yt-dlp/yt-dlp#10520]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://www.twitch.tv/glorious_e

### Provide a description that is worded well enough to be understood

Some live Twitch streams support the "rewind" or "DVR" to replay it from the beginning or seek to any time. By default the Twitch page doesn't offer the slider, but with the Chrome extension [Twitch DVR player](https://chromewebstore.google.com/detail/iaeibhcmabccclfnafahihdndonfgebo) the slider appears always:

![1_e](https://github.com/user-attachments/assets/21d805d0-2ed0-4186-8bd9-464bef31a229)

![2_e](https://github.com/user-attachments/assets/9d9abe16-9de6-4481-bab5-a9e6bd6e2448)

Some streams fail to rewind when seeking, the extension displays the errors:

![novod](https://github.com/user-attachments/assets/eb3ac02c-0e4f-4572-978e-6fe3aef391b0)

![subonly](https://github.com/user-attachments/assets/9cc01652-a548-4b70-a96e-58c630cc82f6)

The feature request is if the twitch plugin could be improved to support these streams, and detect the reason when the stream can't be saved from the start when the option `--live-from-start` is passed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --live-from-start --downloader-args "ffmpeg:-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10" -o "stream_from_start.mp4" "https://www.twitch.tv/glorious_e"
[debug] Command-line config: ['-vU', '--live-from-start', '--downloader-args', 'ffmpeg:-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10', '-o', 'stream_from_start.mp4', 'https://www.twitch.tv/glorious_e']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[twitch:stream] Extracting URL: https://www.twitch.tv/glorious_e
[twitch:stream] glorious_e: Downloading stream GraphQL
[twitch:stream] glorious_e: Downloading stream access token GraphQL
[twitch:stream] glorious_e: Downloading m3u8 information
ERROR: [twitch:stream] 42633192856: --live-from-start is passed, but there are no formats that can be downloaded from the start. If you want to download from the current time, use --no-live-from-start
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2828, in process_video_result
    self.raise_no_formats(info_dict, msg=(
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1123, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [twitch:stream] 42633192856: --live-from-start is passed, but there are no formats that can be downloaded from the start. If you want to download from the current time, use --no-live-from-start
```

**Comment by bashonly** [comment]
Very closely related: #6491, #8754

**Comment by superbonaci** [comment]
The issue https://github.com/yt-dlp/yt-dlp/issues/8754 is old and probably was some ffmpeg bug.

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/issues/13181#issuecomment-2888535999
