### ISSUE TITLE
Updating yt-dlp

### ISSUE THREAD

**Issue by tashimee** [yt-dlp/yt-dlp#10540]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I tried updating yt-dlp and using it. This is the error I got:

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --write-srt --sub-lang en -f mp4 -i -o "/media/tashimee/Extra/current/--%(upload_date)s--%(title)s.%(ext)s" 'https://rumble.com/v57yor7-kamala-harriss-rehearsed-mantra-makes-little-sense-but-she-repeats-it-all-t.html' | tee -a /media/tashimee/Misty/zzzhold/output/20240723.txt
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 14, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 5, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.8 and above are supported by yt-dlp
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 14, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 5, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.8 and above are supported by yt-dlp
tashimee@tashimee:~$ python3 --version
Python 3.8.0
tashimee@tashimee:~$ sudo yt-dlp --version
[sudo] password for tashimee:             
2024.07.16

yt-dlp -vU --write-srt --sub-lang en -uV -f mp4 -i -o "/media/tashimee/Extra/current/--%(upload_date)s--%(title)s.%(ext)s" 'https://rumble.com/v57yor7-kamala-harriss-rehearsed-mantra-makes-little-sense-but-she-repeats-it-all-t.html' | tee -a /media/tashimee/Misty/zzzhold/output/20240723.txt
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 14, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 5, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.8 and above are supported by yt-dlp
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 14, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 5, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.8 and above are supported by yt-dlp
```

**Comment by Grub4K** [comment]
> You are using an unsupported version of Python. Only Python versions 3.8 and above are supported by yt-dlp

Probably related to this?

**Comment by dirkf** [comment]
From the log shown (though not through this
>Run your yt-dlp command with -vU flag added (yt-dlp -vU <your command line>)

which would have provided more information), the _yt-dlp_ command is running under Python 3.7 while typing `python3` in the same shell session uses 3.8.

Presumably this is the situation: 
* _yt-dlp_ was installed with _pip_ or some other package manager into the Python 3.7 library, with a launcher executable on the `PATH` that runs that package under 3.7
* Python 3.8 has subsequently been installed but is not being invoked by the launcher.

**Comment by tashimee** [comment]
So, what should I do?

**Comment by bashonly** [comment]
How have you been installing this stuff? e.g. how did you install yt-dlp? how did you install Python? what linux distro are you using? etc

**Comment by bashonly** [comment]
Closing as incomplete, can reopen if more information is provided

**Comment by tashimee** [comment]
Sorry I've don't have time to look every day. I am using Linux Mint 19.3. I think I installed yt-dlp with pip. I installed python3.8 with apt.

**Comment by tashimee** [comment]
I can't answer if I am having the same problem, I had to roll back with timeshift. Everything works with the old version of yt-dlp. The only thing that doesn't work is I can't download a more than one video.

**Comment by bashonly** [comment]
> `/usr/local/bin/yt-dlp`

That doesn't really look like a pip install.  I would uninstall it entirely and install fresh with Python 3.8

You currently have python 3.7 and python 3.8 both installed on your system. I would say to uninstall python 3.7, but it's possible this could break your system in an unexpected way (since yt-dlp was breaking in an unexpected way.) Without more information I still can't give any better advice

**Comment by tashimee** [comment]
Since I rolled everything back, I've decided to leave things the way they are. Thank you for your help.
