### ISSUE TITLE
TV5Unis "Unable to download JSON metadata" 

### ISSUE THREAD

**Issue by HidingCrab** [yt-dlp/yt-dlp#10558]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

An example URL is https://www.tv5unis.ca/videos/des-hommes-la-nuit

TV5Unis was working about a year ago.
I have a VPN set to the location of Montreal, Canada. The video plays in my Windows Firefox web browser.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-sub', 'https://www.tv5unis.ca/videos/des-hommes-la-nuit']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.25 from yt-dlp/yt-dlp [f0993391e] (pip)
[debug] Python 3.11.9 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.25 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.25 from yt-dlp/yt-dlp)
[debug] Using fake IP 99.254.124.255 (CA) as X-Forwarded-For
[tv5unis] Extracting URL: https://www.tv5unis.ca/videos/des-hommes-la-nuit
[tv5unis] des-hommes-la-nuit: Downloading JSON metadata
[limelight] Extracting URL: limelight:media:58ca90012e0546ed9a3c0d94d0abae2a#__youtubedl_smuggle=%7B%22geo_countries%22%3A+%5B%22CA%22%5D%7D
[debug] Using fake IP 99.231.74.24 (CA) as X-Forwarded-For
[limelight] 58ca90012e0546ed9a3c0d94d0abae2a: Downloading PlaylistService getPlaylistByMediaId JSON
ERROR: [limelight] 58ca90012e0546ed9a3c0d94d0abae2a: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\limelight.py", line 267, in _real_extract
    pc, mobile = self._extract(
                 ^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\limelight.py", line 80, in _extract
    pc = self._call_playlist_service(item_id, pc_method, referer=referer)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\limelight.py", line 67, in _call_playlist_service
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\networking\common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\networking\_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\networking\common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\networking\_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

**Comment by gridlockjoe** [comment]
Sorry, neglected to check the 'account sharing' checkbox.

**Comment by gridlockjoe** [comment]
I don't think my entire debug output pasted. Here is the complete file:

```
[debug] Portable config "C:\Program Files (x86)\YouTube Download\yt-dlp.conf": ['--format', '(bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best)', '--download-archive', 'archive.txt', '--output', '%(uploader)s/%(upload_date)s.%(title)s.%(id)s.%(ext)s', '--merge
-output-format', 'mkv', '--ignore-errors', '--compat-options', 'multistreams']
[debug] Encodings: locale cp1252, fs utf-8, pref UTF-8, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version nightly@2025.03.16.232921 from yt-dlp/yt-dlp-nightly-builds [2ee3a0aff] (win_exe)
[debug] Compatibility options: multistreams
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-118860-g81c50c33b6-20250318 (setts), ffprobe N-118860-g81c50c33b6-20250318, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.22.0, brotli-1.1.0, certifi-2025.01.31, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-15.0.1
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\joe\AppData\Roaming\Mozilla\Firefox\Profiles\ft2cvb34.default-release\cookies.sqlite"
Extracted 2773 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1847 extractors
[debug] Loading archive file 'archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2025.03.16.232921 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2025.03.16.232921 from yt-dlp/yt-dlp-nightly-builds)
[debug] Using fake IP 99.229.123.30 (CA) as X-Forwarded-For
[tv5unis] Extracting URL: https://www.tv5unis.ca/videos/le-coeur-a-ses-raisons/saisons/3/episodes/1
[tv5unis] le-coeur-a-ses-raisons: Downloading JSON metadata
[limelight] Extracting URL: limelight:media:80d2992c5e3044779688fb9e69cfbbed#__youtubedl_smuggle=%7B%22geo_countries%22%3A+%5B%22CA%22%5D%7D
[debug] Using fake IP 99.235.134.26 (CA) as X-Forwarded-For
[limelight] 80d2992c5e3044779688fb9e69cfbbed: Downloading PlaylistService getPlaylistByMediaId JSON
ERROR: [limelight] 80d2992c5e3044779688fb9e69cfbbed: Unable to download JSON metadata: <urllib3.connection.HTTPConnection object at 0x0000019EDC418A30>: Failed to resolve 'production-ps.lvp.llnw.net' ([Errno 11002] getaddrinfo failed) (caused by TransportError("<urllib3.connection.HTTPConnection object at 0x0000019EDC418A30>: Failed to resolve 'production-ps.lvp.llnw.net' ([Errno 11002] getaddrinfo failed)"))
  File "yt_dlp\extractor\common.py", line 747, in extract
  File "yt_dlp\extractor\limelight.py", line 267, in _real_extract
  File "yt_dlp\extractor\limelight.py", line 80, in _extract
  File "yt_dlp\extractor\limelight.py", line 67, in _call_playlist_service
  File "yt_dlp\extractor\common.py", line 1144, in download_content
  File "yt_dlp\extractor\common.py", line 1102, in download_handle
  File "yt_dlp\extractor\common.py", line 967, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 916, in _request_webpage
  File "urllib3\connection.py", line 198, in _new_conn
  File "urllib3\
util\connection.py", line 60, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 332, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 841, in urlopen
  File "urllib3\util\retry.py", line 449, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\connectionpool.py", line 493, in _make_request
  File "urllib3\connection.py", line 445, in request
  File "http\client.py", line 1278, in endheaders
  File "http\client.py", line 1038, in _send_output
  File "http\client.py", line 976, in send
  File "urllib3\connection.py", line 276, in connect
  File "urllib3\connection.
py", line 205, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x0000019EDC418A30>: Failed to resolve 'production-ps.lvp.llnw.net' ([Errno 11002] getaddrinfo failed)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 903, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4184, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 359, in send
  File "yt_dlp\networking\_requests.py", line 360, in _send
yt_dlp.networking.exceptions.TransportError: <urllib3.connection.HTTPConnection object at 0x0000019EDC418A30>: Failed to resolve 'production-ps.lvp.llnw.net' ([Errno 11002] getaddrinfo failed)

[GUI] yt-dlp.exe process has exited
```
