### ISSUE TITLE
A new JS player update (3400486c) breaks video downloading

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [yt-dlp/yt-dlp#10550]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Global

### Provide a description that is worded well enough to be understood

Trying to download the format 18 of the video about the "Love Live! School Idol Festival: All-Stars" side-stories of Honoka Kousaka (along with some of videos, maybe?) now fails with a "requested format is not available" error because of the new JS player update occurred by YouTube:

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', '18', '--rm-cache', '-v', 'ytsearch:side stories of honoka']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-07-07-git-0619138639-full_build-www.gyan.dev (setts), ffprobe 2024-07-07-git-0619138639-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
Removing cache dir C:\Users\User/.cache\yt-dlp ...
[youtube:search] Extracting URL: ytsearch:side stories of honoka
[download] Downloading playlist: side stories of honoka
[youtube:search] query "side stories of honoka": Downloading web client config
[youtube:search] query "side stories of honoka" page 1: Downloading API JSON
[youtube:search] Playlist side stories of honoka: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=gz43h1WKk4o
[youtube] gz43h1WKk4o: Downloading webpage
[youtube] gz43h1WKk4o: Downloading ios player API JSON
[youtube] gz43h1WKk4o: Downloading player 3400486c
WARNING: [youtube] gz43h1WKk4o: nsig extraction failed: Some formats may be missing
         n = SWia92LaX_GnewDhQV ; player = https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] gz43h1WKk4o: nsig extraction failed: Some formats may be missing
         n = 2JhmxGEGqcSbSZaIiN ; player = https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js
[youtube] gz43h1WKk4o: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] gz43h1WKk4o: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1622, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1778, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1837, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2973, in process_video_result
yt_dlp.utils.ExtractorError: [youtube] gz43h1WKk4o: Requested format is not available. Use --list-formats for a list of available formats

[download] Finished downloading playlist: side stories of honoka
```

**Comment by NanaMizukiAnother7** [comment]
Okay. I just saw that pull request #10542 fixes the issue. I'm closing this.

**Comment by bashonly** [comment]
Fixed by 713b4cd18f00556771af8cfdd9cea6cc1a09e948

(just adding this comment for proper tracking)
