### ISSUE TITLE
Unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by myaccountstlee** [yt-dlp/yt-dlp#10562]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Error message generated when copying and pasting YouTube video url with yt-dlp.  Tried multiple YouTube vides and they generate the same message.  yt-dlp was previously working

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.7.6 (CPython x86_64 64bit) - Darwin-23.5.0-x86_64-i386-64bit (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2020.04.05.1, mutagen-1.47.0, requests-2.31.0, sqlite3-3.31.1, urllib3-2.0.7, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[youtube] Extracting URL: https://www.youtube.com/watch?v=zpwK1vhDYyc
[youtube] zpwK1vhDYyc: Downloading webpage
[youtube] zpwK1vhDYyc: Downloading ios player API JSON
[youtube] zpwK1vhDYyc: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] zpwK1vhDYyc: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] zpwK1vhDYyc: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] zpwK1vhDYyc: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] Extracting signature function js_1f8742dc_107
[debug] Loading youtube-sigfuncs.js_1f8742dc_107 from cache
[youtube] zpwK1vhDYyc: Downloading player 1f8742dc
WARNING: [youtube] zpwK1vhDYyc: nsig extraction failed: You may experience throttling for some formats
         n = SSjb53BSicajhhjG5 ; player = https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] zpwK1vhDYyc: nsig extraction failed: You may experience throttling for some formats
         n = GZIBotsA7PBDCvxKW ; player = https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js
[youtube] zpwK1vhDYyc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] zpwK1vhDYyc: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr5---sn-vgqsknek.googlevideo.com/videoplayback?expire=1721950068&ei=FIuiZpbfJ8KM2_gPys-Y0A4&ip=2600%3A1700%3Aa33d%3A1400%3A85a5%3Ad35e%3A11a8%3A6ea9&id=o-ACf-RsIRWh31wpGcYOPlm4KtGzK69RXLbAGnqX7ZCTtr&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=6R&mm=31%2C26&mn=sn-vgqsknek%2Csn-5uaezns7&ms=au%2Conr&mv=m&mvi=5&pl=44&initcwndbps=900000&bui=AXc671L8Y_ujMqXRYbO6ITWEpCPfKVxqPPukzRkvdsO07aeSIlkG_d84iuFWJa4694bLVJlTcUXuua2v&spc=NO7bAew1ajYDmMGh2rXsPDaSIQU3ljaECY-WddGpx2f9TzlmUkY6G-oXkp0P8ns&vprv=1&svpuc=1&mime=video%2Fmp4&ns=UGRfxKe6oWM9Vg9n_nR1BOwQ&rqh=1&cnr=14&ratebypass=yes&dur=277.780&lmt=1719798626943142&mt=1721928089&fvip=2&c=WEB&sefc=1&txp=5319224&n=SSjb53BSicajhhjG5&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Ccnr%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAMKqiuwzxphw70siqmjHIA0-X9NGL6qq9-uO9WOFc9SuAiEA7xL6d5mPo-VODKgSWGrkZvgE_rSNjNvt8YSbIrUL42o%3D&sig=AJfQdSswRgIhAOX74UdscCU_UB2CKEyv65L_mK1kPfd-S-aK6tOY0YAiAiEA2DksX5qbNqx1QASshqVkhqjnMkq2mZ5VMW3Z0Gpf14k="
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 4052, in urlopen
    return self._request_director.send(req)
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/networking/_requests.py", line 341, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3388, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3109, in dl
    return fd.download(name, new_info, subtitle)
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/downloader/http.py", line 364, in real_download
    establish_connection()
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/Users/tourelee/miniconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 4074, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
update yt-dlp

**Comment by WebMechanic** [comment]
same here, Win 10, Germany. 
I get video, subtitles, but no audio track.
it still worked about two weeks ago before my vacation, now I get `ERROR: unable to download video data: HTTP Error 403: Forbidden`
Note that while it says "unable to download **video data**" the video stream is fine, only the audio (f 140) is missing. I used `-f 620+140` before and `140` is an AAC audio stream available for every video.

```
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
```

[ytdlp-403.log](https://github.com/user-attachments/files/16917183/ytdlp-403.log)

**Comment by seproDev** [comment]
@WebMechanic You are forcing the use of the web client, which cannot be used any more due to requiring browser-based integrity checks. Imo. unless you have a really specific reason, don't overwrite the `player_client` default. As things change, we change the default to make as many formats available as possible.

**Comment by WebMechanic** [comment]
> don't overwrite the `player_client` default. As things change, we change the default to make as many formats available as possible.

thanks: removed it, works now.
I had to add this a while back to make things work as most videos didn't download with some "android" error 🤷‍♂️ 

I also just noticed that using the audio streams `233` or `234` did work, which have an "unknown" bit rate. 
None of the other (opus, m4a) streams with "known" bit rates worked, either alone or in combo with a video stream.

**Comment by seproDev** [comment]
> download with some "android" error 

Difficult to tell without a log, but maybe you were still on some old version that used the android client.

> `233` or `234` did work 

Those are the iOS audio formats. The video format in your log also worked, since that was a iOS video stream. If you had downloaded a video stream from the web client, that would have also failed with a 403.
