### ISSUE TITLE
it doesnt work (or i use it badly)

### ISSUE THREAD

**Issue by lm2lm2** [yt-dlp/yt-dlp#10579]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

 yt-dlp --cookies /tmp/cookies.sqlite https://cloudreplay.ftven.fr//ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I0NjhmZmNhNjBlYzdkOTQ3MGRjMmYyOWMzYmFkZjFmY2EzNDJiMmM4YmRj/e47eaf8424a66/1411083441-1722079404_france-domtom_TA.ism/master.m3u8
Traceback (most recent call last):
  File "/usr/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/yt_dlp/__init__.py", line 967, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/lib/python3/dist-packages/yt_dlp/__init__.py", line 927, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 740, in __init__
    self._setup_opener()
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3871, in _setup_opener
    self.cookiejar = load_cookies(opts_cookiefile, opts_cookiesfrombrowser, self)
  File "/usr/lib/python3/dist-packages/yt_dlp/cookies.py", line 108, in load_cookies
    jar.load(ignore_discard=True, ignore_expires=True)
  File "/usr/lib/python3/dist-packages/yt_dlp/utils.py", line 1670, in load
    for line in f:
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte

hope im not doing it wrong
yt-dlp  -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-12-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1k  25 Mar 2021, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-12.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --cookies /tmp/cookies.sqlite https://cloudreplay.ftven.fr//ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I0NjhmZmNhNjBlYzdkOTQ3MGRjMmYyOWMzYmFkZjFmY2EzNDJiMmM4YmRj/e47eaf8424a66/1411083441-1722079404_france-domtom_TA.ism/master.m3u8
[debug] Command-line config: ['-vU', '--cookies', '/tmp/cookies.sqlite', 'https://cloudreplay.ftven.fr//ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I0NjhmZmNhNjBlYzdkOTQ3MGRjMmYyOWMzYmFkZjFmY2EzNDJiMmM4YmRj/e47eaf8424a66/1411083441-1722079404_france-domtom_TA.ism/master.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-12-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1k  25 Mar 2021, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-12.0
Traceback (most recent call last):
  File "/usr/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/yt_dlp/__init__.py", line 967, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/lib/python3/dist-packages/yt_dlp/__init__.py", line 927, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 652, in __init__
    self.print_debug_header()
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3827, in print_debug_header
    self._setup_opener()
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3871, in _setup_opener
    self.cookiejar = load_cookies(opts_cookiefile, opts_cookiesfrombrowser, self)
  File "/usr/lib/python3/dist-packages/yt_dlp/cookies.py", line 108, in load_cookies
    jar.load(ignore_discard=True, ignore_expires=True)
  File "/usr/lib/python3/dist-packages/yt_dlp/utils.py", line 1670, in load
    for line in f:
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte
```

**Comment by bashonly** [comment]
> [debug] yt-dlp version stable@2023.03.04

You are on a severely outdated version. Don't install with yt-dlp with `apt`

https://github.com/yt-dlp/yt-dlp/wiki/Installation

**Comment by seproDev** [comment]
You are also seemingly passing a sqlite file to `--cookies`. The option expects a netscape cookie file. Alternatively use `--cookies-from-browser`

**Comment by lm2lm2** [comment]
> You are also seemingly passing a sqlite file to `--cookies`. The option expects a netscape cookie file. Alternatively use `--cookies-from-browser`

hello
thank you for your answer
i passed the "default"/cookies.sqlite of the right firefox profile (i have several) into the command line.


in addition, here it is, with yt-dlp updated :
yt-dlp --cookies /tmp/cookies.sqlite https://cloudreplay.ftven.fr//ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I0NjhmZmNhNjBlYzdkOTQ3MGRjMmYyOWMzYmFkZjFmY2EzNDJiMmM4YmRj/e47eaf8424a66/1411083441-1722079404_france-domtom_TA.ism/master.m3u8
[generic] Extracting URL: https://cloudreplay.ftven.fr//ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I...m_TA.ism/master.m3u8
[generic] master: Downloading webpage
ERROR: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/__init__.py", line 1081, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/__init__.py", line 1071, in _real_main
    return ydl.download(all_urls)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 992, in __exit__
    self.close()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 995, in close
    self.save_cookies()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 988, in save_cookies
    self.cookiejar.save()
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 4116, in cookiejar
    return load_cookies(
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/cookies.py", line 103, in load_cookies
    jar.load()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/cookies.py", line 1314, in load
    for line in f:
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte
 yt-dlp --version
2024.07.25

**Comment by seproDev** [comment]
`--cookies` expects a text file. Either export the cookies with a browser extension or use `--cookies-from-browser firefox` which will automatically find and read the cookies from firefox.

**Comment by lm2lm2** [comment]
> `--cookies` expects a text file. Either export the cookies with a browser extension or use `--cookies-from-browser firefox` which will automatically find and read the cookies from firefox.

yt-dlp --cookies-from-browser firefox  https://cloudreplay.ftven.fr//ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I0NjhmZmNhNjBlYzdkOTQ3MGRjMmYyOWMzYmFkZjFmY2EzNDJiMmM4YmRj/e47eaf8424a66/1411083441-1722079404_france-domtom_TA.ism/master.m3u8
[generic] Extracting URL: https://cloudreplay.ftven.fr//ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I...m_TA.ism/master.m3u8
[generic] master: Downloading webpage
Extracting cookies from firefox
Extracted 9 cookies from firefox
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

**Comment by bashonly** [comment]
Is this from FranceTV? Have you tried the webpage URL instead of the m3u8 URL?

**Comment by lm2lm2** [comment]
using the direct cookie file :

yt-dlp --cookies /tmp/cookies.sqlite  https://cloudreplay.ftven.fr//ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I0NjhmZmNhNjBlYzdkOTQ3MGRjMmYyOWMzYmFkZjFmY2EzNDJiMmM4YmRj/e47eaf8424a66/1411083441-1722079404_france-domtom_TA.ism/master.m3u8
[generic] Extracting URL: https://cloudreplay.ftven.fr//ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I...m_TA.ism/master.m3u8
[generic] master: Downloading webpage
ERROR: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/__init__.py", line 1081, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/__init__.py", line 1071, in _real_main
    return ydl.download(all_urls)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 992, in __exit__
    self.close()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 995, in close
    self.save_cookies()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 988, in save_cookies
    self.cookiejar.save()
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 4116, in cookiejar
    return load_cookies(
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/cookies.py", line 103, in load_cookies
    jar.load()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/cookies.py", line 1314, in load
    for line in f:
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte

**Comment by lm2lm2** [comment]
just add this :+1: yt-dlp --cookies /tmp/cookies.sqlite  https://www.france.tv/sport/les-jeux-olympiques/6328103-jeux-olympiques-de-paris-2024-ceremonie-d-ouverture.html
[FranceTVSite] Extracting URL: https://www.france.tv/sport/les-jeux-olympiques/6328103-jeux-olympiques-de-paris-2024-ceremonie-d-ouverture.html
[FranceTVSite] 6328103-jeux-olympiques-de-paris-2024-ceremonie-d-ouverture: Downloading webpage
ERROR: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/__init__.py", line 1081, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/__init__.py", line 1071, in _real_main
    return ydl.download(all_urls)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 992, in __exit__
    self.close()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 995, in close
    self.save_cookies()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 988, in save_cookies
    self.cookiejar.save()
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 4116, in cookiejar
    return load_cookies(
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/cookies.py", line 103, in load_cookies
    jar.load()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/cookies.py", line 1314, in load
    for line in f:
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte

and :

yt-dlp --cookies /tmp/cookies.sqlite  https://cloudreplay.ftven.fr/ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I0NjhmZmNhNjBlYzdkOTQ3MGRjMmYyOWMzYmFkZjFmY2EzNDJiMmM4YmRj/e47eaf8424a66/1411083441-1722079404_france-domtom_TA.ism/master.m3u8
[generic] Extracting URL: https://cloudreplay.ftven.fr/ZXhwPTE3MjIxMTYyNzV+YWNsPSUyZip+aG1hYz0xNTJjYjViYjIxYzY3NGZhYTIzN2I0...m_TA.ism/master.m3u8
[generic] master: Downloading webpage
ERROR: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/__init__.py", line 1081, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/__init__.py", line 1071, in _real_main
    return ydl.download(all_urls)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 992, in __exit__
    self.close()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 995, in close
    self.save_cookies()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 988, in save_cookies
    self.cookiejar.save()
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 4116, in cookiejar
    return load_cookies(
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/cookies.py", line 103, in load_cookies
    jar.load()
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/cookies.py", line 1314, in load
    for line in f:
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte

**Comment by bashonly** [comment]
stop passing the sqlite file to `--cookies` option!

**Comment by bashonly** [comment]
just do this:

```
yt-dlp -v "https://www.france.tv/sport/les-jeux-olympiques/6328103-jeux-olympiques-de-paris-2024-ceremonie-d-ouverture.html"
```

**Comment by lm2lm2** [comment]
> just do this:
> 
> ```
> yt-dlp -v "https://www.france.tv/sport/les-jeux-olympiques/6328103-jeux-olympiques-de-paris-2024-ceremonie-d-ouverture.html"
> ```

thank you!
