### ISSUE TITLE
[Twitter/X] "Invalid argument" error when trying to download tweets with Japanese hastags

### ISSUE THREAD

**Issue by iAmaFence** [yt-dlp/yt-dlp#10601]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Recently some tweets with japanese hastags in them won't download, giving an "invalid argument" error.
tried downloading https://x.com/randle0jung/status/1688807782412398592 failed
tested https://x.com/acomu414/status/1817917780811002064 failed
tested https://x.com/McDonaldsJapan/status/1815892150145417591 successfully downloaded
tested tweet with no text https://x.com/shitpost_2077/status/1818096674180317297 successfully downloaded

tried all with quotes same error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
"[debug] Command-line config: ['-vU', 'https://x.com/randle0jung/status/1688807782412398592']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.07.29.220209 from yt-dlp/yt-dlp-master-builds [94a1c5e64] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1828 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.07.29.220209 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.07.29.220209 from yt-dlp/yt-dlp-master-builds)
[twitter] Extracting URL: https://x.com/randle0jung/status/1688807782412398592
[twitter] 1688807782412398592: Downloading guest token
[twitter] 1688807782412398592: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1688807635544670208
[twitter] 1688807782412398592: Downloading m3u8 information
[debug] Sort order given by extractor: res, proto:m3u8, br, size
[debug] Formats sorted by: hasvid, ie_pref, res, proto:m3u8(8), br, size, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1688807635544670208: Downloading 1 format(s): hls-889+hls-audio-128000-Audio
[debug] Invoking hlsnative downloader on "https://video.twimg.com/ext_tw_video/1688807635544670208/pu/pl/720x1280/WGXtOefeHmkuS4Y7.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 40
[download] Destination: Randle - #ブルアカ #BlueArchive 무츠키 귀여워...  고면(@Deadnooodles)님의 이미지... 정말로 귀여 워서 움직임 추가하는 작업 진행했습니다❤ 모바일에서 보기 좋게 만들었습니다...  이미지사용 허락해주셔서 감사합니다😸 [1688807635544670208].fhls-889.mp4
[download] Unable to open file: [Errno 22] Invalid argument: 'Randle - #ブルアカ #BlueArchive 무츠키 귀여워...  고면(@Deadnooodles)님의 이미지... 정말로 귀여워서 움직임 추가하는 작업 진행했습니다❤ 모바일에서 보기 좋게 만들었습니다...  이미 지사용 허락해주셔서 감사합니다😸 [1688807635544670208].fhls-889.mp4.ytdl'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Randle - #ブルアカ #BlueArchive 무츠키 귀여워...  고면(@Deadnooodles)님의 이미지... 정말로 귀여워서 움직임 추가하는 작업 진행했습니다❤ 모바일에서 보기 좋게 만들었습니다...  이미 지사용 허락해주셔서 감사합니다😸 [1688807635544670208].fhls-889.mp4.ytdl'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Randle - #ブルアカ #BlueArchive 무츠키 귀여워...  고면(@Deadnooodles)님의 이미지... 정말로 귀여워서 움직임 추가하는 작업 진행했습니다❤ 모바일에서 보기 좋게 만들었습니다...  이미 지사용 허락해주셔서 감사합니다😸 [1688807635544670208].fhls-889.mp4.ytdl'. Retrying (3/3)...
ERROR: Unable to download video: [Errno 22] Invalid argument: 'Randle - #ブルアカ #BlueArchive 무츠키 귀여워...  고면(@Deadnooodles)님의 이미지... 정말로 귀여워서 움직임 추가하는 작업 진행했습니다❤ 모바일에서 보기 좋게 만들었습니다...  이미지사용 허락해주셔서 감사합니다😸 [1688807635544670208].fhls-889.mp4.ytdl'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 590, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3465, in process_info
  File "yt_dlp\YoutubeDL.py", line 3203, in dl
  File "yt_dlp\downloader\common.py", line 466, in download
  File "yt_dlp\downloader\hls.py", line 158, in real_download
  File "yt_dlp\downloader\fragment.py", line 77, in _prepare_and_start_frag_download
  File "yt_dlp\downloader\fragment.py", line 213, in _prepare_frag_download
  File "yt_dlp\downloader\fragment.py", line 97, in _write_ytdl_file
  File "yt_dlp\downloader\common.py", line 243, in wrapper
  File "yt_dlp\utils\_utils.py", line 5206, in __iter__
  File "yt_dlp\downloader\common.py", line 236, in error_callback
  File "yt_dlp\utils\_utils.py", line 5214, in report_retry
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 256, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 593, in sanitize_open
OSError: [Errno 22] Invalid argument: 'Randle - #ブルアカ #BlueArchive 무츠키 귀여워...  고면(@Deadnooodles)님의 이미지... 정말로 귀여워서 움직임 추가하는 작업 진행했습니다❤ 모바일에서 보기 좋게 만들었습니다...  이미지사용 허락해주셔서 감사합니다😸 [1688807635544670208].fhls-889.mp4.ytdl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 3015, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 179, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3495, in process_info
yt_dlp.utils.UnavailableVideoError: Unable to download video: [Errno 22] Invalid argument: 'Randle - #ブルアカ #BlueArchive 무츠키 귀여워...  고면(@Deadnooodles)님의 이미지... 정말로 귀여워서 움직임 추가하는 작업 진행했습니다❤ 모바일에서 보기 좋게 만들었습니다...  이미지사용 허락해주셔서 감사합니다😸 [1688807635544670208].fhls-889.mp4.ytdl'"
```

**Comment by bashonly** [comment]
The output filename is just too long. Add `-o "%(title).150B [%(id)s].%(ext)s` to your command; or, if that fails, change `150B` to `100B` and continue to decrease the value as needed
