### ISSUE TITLE
yt-dlp on cygwin doesn't complete succesfully, claims provided cookie file argument is inexistent

### ISSUE THREAD

**Issue by olspookishmagus** [yt-dlp/yt-dlp#10637]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am trying to use yt-dlp via cygwin whenever I'm using my Windows 10 installation. I'm using a cookies file that works in Linux and even on PowerShell in Windows. I've seen in the code that there's already some handling of the value `cygwin` of `sys.platform` so it would be nice if there is some more fine tuning that needs to be done. 

Some _platform_ information:
```
$ uname -a
CYGWIN_NT-10.0-19045 win10x64 3.5.3-1.x86_64 2024-04-03 17:25 UTC x86_64 Cygwin
```

Cookies file:
```
$ if [ -f ~/Desktop/cookies-youtube.txt ] ; then head -n2 ~/Desktop/cookies-youtube.txt ; fi 
# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.
$ ls -l ~/Desktop/cookies-youtube.txt
-rw-rw----+ 1 olspookishmagus None 505 Aug  2 18:00 /home/olspookishmagus/Desktop/cookies-youtube.txt
$ stat ~/Desktop/cookies-youtube.txt
  File: /home/olspookishmagus/Desktop/cookies-youtube.txt
  Size: 505             Blocks: 4          IO Block: 65536  regular file
Device: 16449,43973     Inode: 2251799813716697  Links: 1
Access: (0660/-rw-rw----)  Uid: (197609/olspookishmagus)   Gid: (197121/    None)
Access: 2024-08-02 20:07:20.913719600 +0200
Modify: 2024-08-02 18:00:48.130904600 +0200
Change: 2024-08-02 19:42:35.048625000 +0200
 Birth: 2023-07-01 11:44:01.814690600 +0200
$ id -u
197609
```

Python availability (though I think yt-dlp bring in its own Python):
```
$ whereis python
python: /usr/bin/python
$ ls -l /usr/bin/python
lrwxrwxrwx 1 olspookishmagus None 24 Jul 22  2022 /usr/bin/python -> /etc/alternatives/python*
$ ls -l /etc/alternatives/python
lrwxrwxrwx 1 olspookishmagus Administrators 18 Mar 14  2023 /etc/alternatives/python -> /usr/bin/python3.9*
$ ls -l /usr/bin/python3.9.exe
-rwxr-xr-x 1 olspookishmagus Administrators 9.6K Mar  8  2023 /usr/bin/python3.9.exe*
$ sha256sum /usr/bin/python3.9.exe
3981bb8d4117d46712750cb38d3a2d87ae02ca1ca49941533f30f36c7a2729db */usr/bin/python3.9.exe
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', '/home/olspookishmagus/Desktop/cookies-youtube.txt', '--', 'jNQXAC9IVRw']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.01 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.01 from yt-dlp/yt-dlp)
[youtube] Extracting URL: jNQXAC9IVRw
[youtube] jNQXAC9IVRw: Downloading webpage
[youtube] jNQXAC9IVRw: Downloading ios player API JSON
[youtube] jNQXAC9IVRw: Downloading tv player API JSON
[debug] Loading youtube-nsig.d2e656ee from cache
[debug] [youtube] Decrypted nsig 784mWnh-dS52P5Bi => L-hCUXblxe6GgQ
[debug] Loading youtube-nsig.d2e656ee from cache
[debug] [youtube] Decrypted nsig Ihhrd0iWjrCaCkBw => YDJmoY98hF7rRg
[youtube] jNQXAC9IVRw: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] jNQXAC9IVRw: Downloading 1 format(s): 242+251
[debug] Invoking http downloader on "https://rr1---sn-hxapu5-ha5s.googlevideo.com/videoplayback?expire=1722644128&ei=QCKtZrCpFLiy6dsPoJqoyQ0&ip=88.203.23.156&id=o-AF0Rhwwiw5uxcLArn6IIfv3jCqNR-jX948-I9NSHX9zp&itag=242&source=youtube&require
ssl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VD&mm=31%2C29&mn=sn-hxapu5-ha5s%2Csn-hpa7kn76&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1202500&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=293080&dur=18.933&lmt=1680501309294787&mt=1722621451&fvip=5&
keepalive=yes&c=IOS&txp=4530434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAJwLVRXZc2SDtqQ_VDedEzjVGCXm7bwxeXDbRtHxzPc7AiAXlAgkYyWfO5zYpCz0wiG3bBiaP
TM2c60XCj0YLlpTbA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgLT_CiuDa_RJSbE0byzVbqy91JmambCvuR71f6aUBEsUCIEqxbQy7Va9SDltJ8P1tNXjy8Jj-wWssKJN1k1ahi9rz"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Me at the zoo [jNQXAC9IVRw].f242.webm
[download] 100% of  286.21KiB in 00:00:00 at 2.04MiB/s
[debug] Invoking http downloader on "https://rr1---sn-hxapu5-ha5s.googlevideo.com/videoplayback?expire=1722644128&ei=QCKtZovxINWA6dsPpaiD-AE&ip=88.203.23.156&id=o-AKi7ONJCbuakdFZHb6we9kL2S5VvkwOZrts2HFcyACwg&itag=251&source=youtube&require
ssl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VD&mm=31%2C29&mn=sn-hxapu5-ha5s%2Csn-hpa7znzy&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1202500&bui=AXc671L8OYapJWZxteDz-no3mAwCjmHTf9MjSFJlS_HuUz6xWJeSVNHf-9yd8L3KodYSN89ZTacMiX46&vprv=1&svpuc=1&mime=audio%2
Fwebm&ns=_uA1hWtObR6Y9vBs1bsgpeQQ&rqh=1&gir=yes&clen=252182&dur=19.021&lmt=1680501254853292&mt=1722621451&fvip=3&keepalive=yes&lmw=1&c=TVHTML5&sefc=1&txp=4530434&n=YDJmoY98hF7rRg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2
Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgH-Rifg5z4plzIVTLanZemoWX9kyFjNBqba2PIw_tlYMCIHcLKBoO55m6mtITqJXae70-LDD_6hLIXneioAjRa3N7&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGt
xev0wRAIgZwnBBCZW92L35XLw5tmwCR2x0IhfExeH0ns8I_EwQD4CIA9937OOhUtRjo5fipZ8SSnKMFXuibqqhJbUMFmUlVj7"
[download] Destination: Me at the zoo [jNQXAC9IVRw].f251.webm
[download] 100% of  246.27KiB in 00:00:00 at 1.82MiB/s
[Merger] Merging formats into "Me at the zoo [jNQXAC9IVRw].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:Me at the zoo [jNQXAC9IVRw].f242.webm" -i "file:Me at the zoo [jNQXAC9IVRw].f251.webm" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:Me at the zoo [jNQXAC9IVR
w].temp.webm"
Deleting original file Me at the zoo [jNQXAC9IVRw].f251.webm (pass -k to keep)
Deleting original file Me at the zoo [jNQXAC9IVRw].f242.webm (pass -k to keep)
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1081, in main
  File "yt_dlp\__init__.py", line 1071, in _real_main
  File "yt_dlp\YoutubeDL.py", line 992, in __exit__
  File "yt_dlp\YoutubeDL.py", line 995, in close
  File "yt_dlp\YoutubeDL.py", line 988, in save_cookies
  File "yt_dlp\cookies.py", line 1286, in save
  File "contextlib.py", line 113, in __enter__
  File "yt_dlp\cookies.py", line 1241, in open
FileNotFoundError: [Errno 2] No such file or directory: '/home/olspookishmagus/Desktop/cookies-youtube.txt'
[27064] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by olspookishmagus** [comment]
Output from the same box, but executed from within `PowerShell`:

```
[debug] Command-line config: ['-vU', '--cookies', 'C:\\Users\\olspookishmagus\\Desktop\\cookies-youtube.txt', '--', 'jNQXAC9IVRw']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.01 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.01 from yt-dlp/yt-dlp)
[youtube] Extracting URL: jNQXAC9IVRw
[youtube] jNQXAC9IVRw: Downloading webpage
[youtube] jNQXAC9IVRw: Downloading ios player API JSON
[youtube] jNQXAC9IVRw: Downloading tv player API JSON
[youtube] jNQXAC9IVRw: Downloading player d2e656ee
[debug] Saving youtube-nsig.d2e656ee to cache
[debug] [youtube] Decrypted nsig jSQ2avx227MhrhGn => zOcIt0u0meKTYg
[debug] Loading youtube-nsig.d2e656ee from cache
[debug] [youtube] Decrypted nsig Shb6AUYc1B2E3E7Q => iStwvuFVrxxnrQ
[youtube] jNQXAC9IVRw: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] jNQXAC9IVRw: Downloading 1 format(s): 242+251
[debug] Invoking http downloader on "https://rr1---sn-hxapu5-ha5s.googlevideo.com/videoplayback?expire=1722645308&ei=3CatZu7PIoyv6dsPtYCqsAU&ip=88.203.23.156&id=o-AO804aZymDwHHo2271nHNMo0H5hEChCjnlOgXoIhC0xE&itag=242&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VD&mm=31%2C29&mn=sn-hxapu5-ha5s%2Csn-hpa7znzy&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1167500&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=293080&dur=18.933&lmt=1680501309294787&mt=1722623370&fvip=3&keepalive=yes&c=IOS&txp=4530434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhANt0gZnMcP142mwqcHcutJYlixI1YbhEzQJD-vzDE17WAiEA1bprtvM8iw8LTHyJZTfLupjf9h-qljwFUsjj01-JzpY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAMTEe02ahCVEcYjjkiuoFA68y42T06ya-9NOnpGW0Q6jAiEAzqXgaEEUYUTw0XZL8ghoTVA4UQJ65sRsaVDN4TI-Vvs%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Me at the zoo [jNQXAC9IVRw].f242.webm
[download] 100% of  286.21KiB in 00:00:00 at 1.33MiB/s
[debug] Invoking http downloader on "https://rr1---sn-hxapu5-ha5s.googlevideo.com/videoplayback?expire=1722645308&ei=3CatZp2pK9Tl6dsP9-utuA8&ip=88.203.23.156&id=o-AEYZA_l1xpB_kfSIlaGeDZ3nRmvC3i0kFrtkvF59LKhX&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VD&mm=31%2C29&mn=sn-hxapu5-ha5s%2Csn-hpa7kn76&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1167500&bui=AXc671JajWMlcWeQpoBTHWfT4QMYIfULv6qT9JII6JfhX-_TIS1ak40HBAk0G8RgU03wlYLsEAnaYfPL&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=lFvpWywQ2UNzjXiwfxbIoA8Q&rqh=1&gir=yes&clen=252182&dur=19.021&lmt=1680501254853292&mt=1722623370&fvip=5&keepalive=yes&lmw=1&c=TVHTML5&sefc=1&txp=4530434&n=iStwvuFVrxxnrQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgNFAlnb6RaM2N8IKInR9HLYhFKoZI-ZZ8b8F5jFndpQ0CIQCAiy7Am1roFR5UoQZbHyvCKjlOaR9hvbjYVEl-7zEVkg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgQBZ4M5RNRwV2TtuBaTgdQL2P-0sEq_6oyZubDIKHNfACIDUOuQu4OiVDnxTkMGjpn55i4h3_ReA8rV7B1X218Tc8"
[download] Destination: Me at the zoo [jNQXAC9IVRw].f251.webm
[download] 100% of  246.27KiB in 00:00:00 at 1.55MiB/s
[Merger] Merging formats into "Me at the zoo [jNQXAC9IVRw].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:Me at the zoo [jNQXAC9IVRw].f242.webm" -i "file:Me at the zoo [jNQXAC9IVRw].f251.webm" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:Me at the zoo [jNQXAC9IVRw].temp.webm"
Deleting original file Me at the zoo [jNQXAC9IVRw].f251.webm (pass -k to keep)
Deleting original file Me at the zoo [jNQXAC9IVRw].f242.webm (pass -k to keep)
```

**Comment by olspookishmagus** [comment]
Output from the same box, when executing from `cygwin` again but with `--cookies` argument supplied in the `/cygdrive/...` format:

```
[debug] Command-line config: ['-vU', '--cookies', '/cygdrive/c/Users/olspookishmagus/Desktop/cookies-youtube.txt', '--', 'jNQXAC9IVRw']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.01 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.01 from yt-dlp/yt-dlp)
[youtube] Extracting URL: jNQXAC9IVRw
[youtube] jNQXAC9IVRw: Downloading webpage
[youtube] jNQXAC9IVRw: Downloading ios player API JSON
[youtube] jNQXAC9IVRw: Downloading tv player API JSON
[debug] Loading youtube-nsig.d2e656ee from cache
[debug] [youtube] Decrypted nsig SsDZMoVeNx00FnF2 => ixv-AUPnllu55g
[debug] Loading youtube-nsig.d2e656ee from cache
[debug] [youtube] Decrypted nsig SKjznQx4YL1llNKX => iLuAA1YNadKibw
[youtube] jNQXAC9IVRw: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] jNQXAC9IVRw: Downloading 1 format(s): 242+251
[debug] Invoking http downloader on "https://rr1---sn-hxapu5-ha5s.googlevideo.com/videoplayback?expire=1722645853&ei=_SitZqbPBePW6dsP_JmoqAc&ip=88.203.23.156&id=o-AIwGu7-_XQWupWIlBd2iXeGDtl_krN0lH2dCmTmKUdgM&itag=242&source=youtube&require
ssl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VD&mm=31%2C29&mn=sn-hxapu5-ha5s%2Csn-hpa7znzy&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=21&initcwndbps=1213750&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=293080&dur=18.933&lmt=1680501309294787&mt=172262
3844&fvip=3&keepalive=yes&c=IOS&txp=4530434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgLi-AVelfXN7TgM87HNS2ipHJdYKRgSbzfXkcORHEA54CIBAUj3EnUAJ8mrBpn
iUlLPJE9hCPXnLVmeMcBZDkayVS&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgQvR7GrmzR_waOnOdANtkqwwJkp2fbbNNp0-3SDl8OSYCIBr07RwUenADaDzWKxxUcgIPq3BSTYk8MQ4gqsT_P5IK"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Me at the zoo [jNQXAC9IVRw].f242.webm
[download] 100% of  286.21KiB in 00:00:00 at 2.12MiB/s
[debug] Invoking http downloader on "https://rr1---sn-hxapu5-ha5s.googlevideo.com/videoplayback?expire=1722645853&ei=_SitZv38DruI6dsP5Zq38AE&ip=88.203.23.156&id=o-ALnhPOYuWAWZAsHr8yMsjkxUtFaQ72JaJ_RHI_O7wAW1&itag=251&source=youtube&require
ssl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VD&mm=31%2C29&mn=sn-hxapu5-ha5s%2Csn-hpa7kn76&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1213750&bui=AXc671LT6_lfLtiU0NyeQF6-WobgYNhlBuhehtX2fBcJr8-2swE_wuzt2ZcnGLf0C6oSlc1t5hrwoWNT&vprv=1&svpuc=1&mime=audio%2
Fwebm&ns=oADPrDQW55iigghr7WYRuUAQ&rqh=1&gir=yes&clen=252182&dur=19.021&lmt=1680501254853292&mt=1722623844&fvip=5&keepalive=yes&lmw=1&c=TVHTML5&sefc=1&txp=4530434&n=iLuAA1YNadKibw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2
Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAOwfimucCLyFDUeI-HmTY3BefN43zvYOjW5xbaGkeoHpAiEAvKvNIFqB5CtAp6QhjJrZfRCxV9wSLSN5ZOQ5uP1fl5c%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&ls
ig=AGtxev0wRAIgU1bWOZV3vsZMdim9GM_KfKqx8QrfSQk7_Idh4XmVxqUCIGwEb7F7N4iDhrG62L3JwGXTNMx24ZsjwvOKJf_d_lpu"
[download] Destination: Me at the zoo [jNQXAC9IVRw].f251.webm
[download] 100% of  246.27KiB in 00:00:00 at 3.18MiB/s
[Merger] Merging formats into "Me at the zoo [jNQXAC9IVRw].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:Me at the zoo [jNQXAC9IVRw].f242.webm" -i "file:Me at the zoo [jNQXAC9IVRw].f251.webm" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:Me at the zoo [jNQXAC9IVR
w].temp.webm"
Deleting original file Me at the zoo [jNQXAC9IVRw].f251.webm (pass -k to keep)
Deleting original file Me at the zoo [jNQXAC9IVRw].f242.webm (pass -k to keep)
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1081, in main
  File "yt_dlp\__init__.py", line 1071, in _real_main
  File "yt_dlp\YoutubeDL.py", line 992, in __exit__
  File "yt_dlp\YoutubeDL.py", line 995, in close
  File "yt_dlp\YoutubeDL.py", line 988, in save_cookies
  File "yt_dlp\cookies.py", line 1286, in save
  File "contextlib.py", line 113, in __enter__
  File "yt_dlp\cookies.py", line 1241, in open
FileNotFoundError: [Errno 2] No such file or directory: '/cygdrive/c/Users/olspookishmagus/Desktop/cookies-youtube.txt'
[11792] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by bashonly** [comment]
It doesn't matter whether you execute yt-dlp in powershell or in cygwin; it will behave as a Windows program regardless of the shell from which it was launched. You need to pass the Windows path (`C:\directory\file.txt` etc) of the cookiefile.

**Comment by olspookishmagus** [comment]
Thank you @bashonly.

I was wondering if it's possible to have `cygwin` do that for you.

As in, if `yt-dlp` detects a `cygwin` installation (via `sys.platform`) then the following would help:

```
$ cygpath -w ~/Desktop/cookies-youtube.txt
C:\Users\olspookishmagus\Desktop\cookies-youtube.txt
$ cygpath -w /cygdrive/c/Users/olspookishmagus/Desktop/cookies-youtube.txt
C:\Users\olspookishmagus\Desktop\cookies-youtube.txt
```

I'll look some more into it and make a feature request.

**Comment by dirkf** [comment]
Don't you need to run _yt-dlp_ (maybe the bare POSIX version) under the [Cygwin Python package](https://cygwin.com/packages/summary/python3.html) rather than the Windows Python, when pretending to be in a POSIX world?

**Comment by olspookishmagus** [comment]
> Don't you need to run _yt-dlp_ (maybe the bare POSIX version) under the [Cygwin Python package](https://cygwin.com/packages/summary/python3.html) rather than the Windows Python, when pretending to be in a POSIX world?

That could be another approach which I'll try.

I hope there won't be issues handling the `--output` argument that way.

Thank you for the tip, @dirkf.
