### ISSUE TITLE
Postprocessors can't be found but plugins can (KeyError: '<pp>PP')

### ISSUE THREAD

**Issue by Reycko** [yt-dlp/yt-dlp#10633]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Using --use-postprocessor doesn't seem to find any PP plugins, even though it does work on extractor plugins.

The postprocessor name in code is `FixupMtimePP`. I've tried both with and without the `PP` at the end.
My extractor plugins work fine. I've checked if the path was correct (and it is).

I've also tried using a different PP plugin to no avail.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--extract-audio', '--audio-format', 'flac', '--audio-quality', '5', '--output', '%(playlist_index)03d - %(title)s - %(uploader)s.%(ext)s', '--yes-playlist', '--ignore-errors', '--add-metadata', '-vU', '--use-postprocessor', 'FixupMtime:mtime_key=upload_date', 'https://music.youtube.com/playlist?list=PLL2qagGQT-1EhITvFSBKr52gG7YEjBalk']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.01.232808 from yt-dlp/yt-dlp-nightly-builds [919540a96] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-113881-gf7545e90df-20240301 (setts), ffprobe N-113881-gf7545e90df-20240301
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1081, in main
  File "yt_dlp\__init__.py", line 979, in _real_main
  File "yt_dlp\YoutubeDL.py", line 809, in __init__
  File "yt_dlp\postprocessor\__init__.py", line 42, in get_postprocessor
KeyError: 'FixupMtimePP'
[26820] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by bashonly** [comment]
The plugin is not installed correctly, or else it would show up in the debug header

**Comment by Reycko** [comment]
> The plugin is not installed correctly, or else it would show up in the debug header
> 
> https://github.com/yt-dlp/yt-dlp#plugins

I've put it on the right folder, but I'm still having the issue.
New log:
```
[debug] Command-line config: ['--extract-audio', '--audio-format', 'flac', '--audio-quality', '5', '--output', '%(playlist_index)03d - %(title)s - %(uploader)s.%(ext)s', '--yes-playlist', '--ignore-errors', '--add-metadata', '-vU', '--use-postprocessor', 'FixupMtime:mtime_key=upload_date', 'https://music.youtube.com/playlist?list=PLL2qagGQT-1EhITvFSBKr52gG7YEjBalk']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.01.232808 from yt-dlp/yt-dlp-nightly-builds [919540a96] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-113881-gf7545e90df-20240301 (setts), ffprobe N-113881-gf7545e90df-20240301
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: ['C:\\Users\\reycko\\AppData\\Roaming\\yt-dlp\\plugins\\extractor\\yt_dlp_plugins', 'C:\\Users\\reycko\\AppData\\Roaming\\yt-dlp\\plugins\\postprocessor\\yt_dlp_plugins']
[debug] Loaded 1830 extractors
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1081, in main
  File "yt_dlp\__init__.py", line 979, in _real_main
  File "yt_dlp\YoutubeDL.py", line 809, in __init__
  File "yt_dlp\postprocessor\__init__.py", line 42, in get_postprocessor
KeyError: 'FixupMtimePP'
[23888] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by bashonly** [comment]
still looks incorrectly installed

you want your directory tree to look like this:
```
Roaming
└── yt-dlp
    └── plugins
        └── yt-dlp-FixupMtime
            └── yt_dlp_plugins
                └── postprocessor
                    └── fixup_mtime.py
```

**Comment by Reycko** [comment]
> still looks incorrectly installed
> 
> you want your directory tree to look like this:
> 
> ```
> Roaming
> └── yt-dlp
>     └── plugins
>         └── yt-dlp-FixupMtime
>             └── yt_dlp_plugins
>                 └── postprocessor
>                     └── fixup_mtime.py
> ```

My bad. An example should probably be added to the wiki, I personally find it confusing.

**Comment by rkjme** [comment]
@bashonly @Reycko 
Sorry for the mentioning, but I am still suffering from this problem. 
My directory in File Explorer looks like this.
"C:\Users\rkjme\AppData\Roaming\yt-dlp\plugins\yt-dlp-ChromeCookieUnlock\yt_dlp_plugins\postprocessor\chrome_cookie_unlock.py"
But I still got the KeyError: 'PP' on the output.



```
C:\Users\rkjme\yt-dlp>yt-dlp --verbose https://youtu.be/G5L_O8sVJqs?si=DO0C3KW0u-fg5MMC
[debug] Command-line config: ['--verbose', 'https://youtu.be/G5L_O8sVJqs?si=DO0C3KW0u-fg5MMC']
[debug] User config "C:\Users\rkjme\AppData\Roaming\yt-dlp\config.txt": ['-o', 'D:\\OneDrive\\Video\\%(title)s.%(ext)s', '-S', 'ext:mp4:m4a', '--embed-thumbnail', '--embed-metadata', '--embed-info-json', '--embed-subs', '--sub-langs', 'en', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--use-postprocessor', 'ChromeCookieUnlock', '--default-search', 'ytsearch']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22635-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2024-12-23-git-6c9218d748-full_build-www.gyan.dev (setts), ffprobe 2024-12-23-git-6c9218d748-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: ['C:\\Users\\rkjme\\AppData\\Roaming\\yt-dlp\\plugins\\yt-dlp-ChromeCookieUnlock\\yt_dlp_plugins']
[debug] Loaded 1837 extractors
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1093, in main
  File "yt_dlp\__init__.py", line 991, in _real_main
  File "yt_dlp\YoutubeDL.py", line 807, in __init__
  File "yt_dlp\postprocessor\__init__.py", line 42, in get_postprocessor
KeyError: 'ChromeCookieUnlockPP'
[PYI-57704:ERROR] Failed to execute script '__main__' due to unhandled exception!
```
And here is what I have in the config.txt

```
-o "D:\OneDrive\Video\%(title)s.%(ext)s"
-S ext:mp4:m4a
--embed-thumbnail
--embed-metadata
--embed-info-json
--embed-subs
--sub-langs en
-f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best
--use-postprocessor ChromeCookieUnlock
--default-search ytsearch
```

**Comment by bashonly** [comment]
@rkjme https://github.com/yt-dlp/yt-dlp/issues/12042#issuecomment-2585350318
