### ISSUE TITLE
yt-dlp.exe can't run properly

### ISSUE THREAD

**Issue by futamiy** [yt-dlp/yt-dlp#10644]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

when run yt-dlp.exe with external or using command, this execution file stuck for hole minutes until close yt-dlp or show log error below. even i run help command (`yt-dlp -h`)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "yt_dlp\__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "yt_dlp\cookies.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "yt_dlp\aes.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "yt_dlp\dependencies\__init__.py", line 65, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests\__init__.py", line 164, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests\api.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests\sessions.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests\adapters.py", line 77, in <module>
FileNotFoundError: [Errno 2] No such file or directory
[5644] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by bashonly** [comment]
Could you give some information about your system? OS name/version, etc? Also, how much free disk space do you have?

**Comment by futamiy** [comment]
windows 11
![image](https://github.com/user-attachments/assets/bb420899-c206-46a8-9677-75f764011c08)

**Comment by bashonly** [comment]
> Also, how much free disk space do you have?

**Comment by seproDev** [comment]
Are you using one of the new arm-based Snapdragon X CPUs?
I'm asking since 24H2 is still in release preview for x86 CPUs.

**Comment by futamiy** [comment]
> > Also, how much free disk space do you have?

![image](https://github.com/user-attachments/assets/789c1267-4bb1-4c27-b0f3-3f2adce51d21)

**Comment by futamiy** [comment]
> Are you using one of the new arm-based Snapdragon X CPUs? I'm asking since 24H2 (the version of Windows you are running) is still in release preview for x86 CPUs.

i'm using intel i5-3570

**Comment by seproDev** [comment]
Okay, so you installed this preview version of Windows yourself? Your CPU is also 12 years old and both unsupported by Windows 10 and Windows 11. I would assume your issues are related to this.
Testing in my 24H2 VM yt-dlp works fine:
![image](https://github.com/user-attachments/assets/54803db7-8f84-4cf9-b780-1891f639a460)

**Comment by bashonly** [comment]
>```
>   File "requests\adapters.py", line 77, in <module>
> FileNotFoundError: [Errno 2] No such file or directory
> ```

seems possibly related to CA cert bundle / certifi / requests:

https://github.com/psf/requests/blob/v2.32.3/src/requests/adapters.py#L77-L83
