### ISSUE TITLE
yt-dlp on cygwin to parse --cookies argument and convert to Windows path

### ISSUE THREAD

**Issue by olspookishmagus** [yt-dlp/yt-dlp#10641]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As a follow-up to issue #10637:

Since there's already a mechanism to recognize whether `yt-dlp` is being executed within `cygwin` (via `sys.platform`) and taking into consideration that in order for yt-dlp executed within cygwin to be able to parse a giving `--cookies` argument, the argument (a path to a cookies file) has to be in a Windows format otherwise yt-dlp won't execute correctly, why not utilize cygwin's `cygpath` to change to an appropriate path if necessary?

Here is an [example](https://github.com/yt-dlp/yt-dlp/issues/10637#issuecomment-2265995300) of converting two cygwin parseable paths a Windows native format.

Cygwin's cygpath manual can be found here:
https://cygwin.com/cygwin-ug-net/cygpath.html

Since it has no mechanism to parse a given path as input and return the type of path (`dos`, `windows`, ...) I guess one could check either the exit codes of such operations and/or the outputs of such operation run against given paths.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', '/home/olspookishmagus/Desktop/cookies-youtube.txt', '--', 'jNQXAC9IVRw']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.01 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.01 from yt-dlp/yt-dlp)
[youtube] Extracting URL: jNQXAC9IVRw
[youtube] jNQXAC9IVRw: Downloading webpage
[youtube] jNQXAC9IVRw: Downloading ios player API JSON
[youtube] jNQXAC9IVRw: Downloading tv player API JSON
[debug] Loading youtube-nsig.d2e656ee from cache
[debug] [youtube] Decrypted nsig 784mWnh-dS52P5Bi => L-hCUXblxe6GgQ
[debug] Loading youtube-nsig.d2e656ee from cache
[debug] [youtube] Decrypted nsig Ihhrd0iWjrCaCkBw => YDJmoY98hF7rRg
[youtube] jNQXAC9IVRw: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] jNQXAC9IVRw: Downloading 1 format(s): 242+251
[debug] Invoking http downloader on "https://rr1---sn-hxapu5-ha5s.googlevideo.com/videoplayback?expire=1722644128&ei=QCKtZrCpFLiy6dsPoJqoyQ0&ip=88.203.23.156&id=o-AF0Rhwwiw5uxcLArn6IIfv3jCqNR-jX948-I9NSHX9zp&itag=242&source=youtube&require
ssl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VD&mm=31%2C29&mn=sn-hxapu5-ha5s%2Csn-hpa7kn76&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1202500&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=293080&dur=18.933&lmt=1680501309294787&mt=1722621451&fvip=5&
keepalive=yes&c=IOS&txp=4530434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAJwLVRXZc2SDtqQ_VDedEzjVGCXm7bwxeXDbRtHxzPc7AiAXlAgkYyWfO5zYpCz0wiG3bBiaP
TM2c60XCj0YLlpTbA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgLT_CiuDa_RJSbE0byzVbqy91JmambCvuR71f6aUBEsUCIEqxbQy7Va9SDltJ8P1tNXjy8Jj-wWssKJN1k1ahi9rz"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Me at the zoo [jNQXAC9IVRw].f242.webm
[download] 100% of  286.21KiB in 00:00:00 at 2.04MiB/s
[debug] Invoking http downloader on "https://rr1---sn-hxapu5-ha5s.googlevideo.com/videoplayback?expire=1722644128&ei=QCKtZovxINWA6dsPpaiD-AE&ip=88.203.23.156&id=o-AKi7ONJCbuakdFZHb6we9kL2S5VvkwOZrts2HFcyACwg&itag=251&source=youtube&require
ssl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VD&mm=31%2C29&mn=sn-hxapu5-ha5s%2Csn-hpa7znzy&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1202500&bui=AXc671L8OYapJWZxteDz-no3mAwCjmHTf9MjSFJlS_HuUz6xWJeSVNHf-9yd8L3KodYSN89ZTacMiX46&vprv=1&svpuc=1&mime=audio%2
Fwebm&ns=_uA1hWtObR6Y9vBs1bsgpeQQ&rqh=1&gir=yes&clen=252182&dur=19.021&lmt=1680501254853292&mt=1722621451&fvip=3&keepalive=yes&lmw=1&c=TVHTML5&sefc=1&txp=4530434&n=YDJmoY98hF7rRg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2
Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgH-Rifg5z4plzIVTLanZemoWX9kyFjNBqba2PIw_tlYMCIHcLKBoO55m6mtITqJXae70-LDD_6hLIXneioAjRa3N7&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGt
xev0wRAIgZwnBBCZW92L35XLw5tmwCR2x0IhfExeH0ns8I_EwQD4CIA9937OOhUtRjo5fipZ8SSnKMFXuibqqhJbUMFmUlVj7"
[download] Destination: Me at the zoo [jNQXAC9IVRw].f251.webm
[download] 100% of  246.27KiB in 00:00:00 at 1.82MiB/s
[Merger] Merging formats into "Me at the zoo [jNQXAC9IVRw].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:Me at the zoo [jNQXAC9IVRw].f242.webm" -i "file:Me at the zoo [jNQXAC9IVRw].f251.webm" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:Me at the zoo [jNQXAC9IVR
w].temp.webm"
Deleting original file Me at the zoo [jNQXAC9IVRw].f251.webm (pass -k to keep)
Deleting original file Me at the zoo [jNQXAC9IVRw].f242.webm (pass -k to keep)
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1081, in main
  File "yt_dlp\__init__.py", line 1071, in _real_main
  File "yt_dlp\YoutubeDL.py", line 992, in __exit__
  File "yt_dlp\YoutubeDL.py", line 995, in close
  File "yt_dlp\YoutubeDL.py", line 988, in save_cookies
  File "yt_dlp\cookies.py", line 1286, in save
  File "contextlib.py", line 113, in __enter__
  File "yt_dlp\cookies.py", line 1241, in open
FileNotFoundError: [Errno 2] No such file or directory: '/home/olspookishmagus/Desktop/cookies-youtube.txt'
[27064] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by bashonly** [comment]
You are using the Windows executable; you are running Windows Python in Cygwin. yt-dlp has no knowledge of Cygwin at that point
