### ISSUE TITLE
Add +SBT support

### ISSUE THREAD

**Issue by renansimoes** [yt-dlp/yt-dlp#10658]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Brazil

### Example URLs

- Single Video: https://mais.sbt.com.br/vod/6352181512112?t=0

### Provide a description that is worded well enough to be understood

Its UI structure is very similar to Pluto.TV

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\yt-dlp>yt-dlp.exe -vU https://mais.sbt.com.br/vod/6352181512112?t=0
[debug] Command-line config: ['-vU', 'https://mais.sbt.com.br/vod/6352181512112?t=0']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.01 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.01 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://mais.sbt.com.br/vod/6352181512112?t=0
[generic] 6352181512112?t=0: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 6352181512112?t=0: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://mais.sbt.com.br/vod/6352181512112?t=0
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://mais.sbt.com.br/vod/6352181512112?t=0


D:\yt-dlp>
```

**Comment by YoshiTabletopGamer** [comment]
I've figured out some (most) content is DRM locked, some isn't. Your particular example is DRM locked, as is the vast majority of other content.

**Comment by YoshiTabletopGamer** [comment]
We could make an extractor to extract things like the live feed, which doesn't have DRM

**Comment by YoshiTabletopGamer** [comment]
Also, oddly, [this ](https://mais.sbt.com.br/vod/6354530551112?t=0)Sonic series does work without DRM, but it doesn't have any sound

**Comment by renansimoes** [comment]
I didn't know it had DRM. Well, better some than none.

Download the live feed is interesting.

**Comment by renansimoes** [comment]
> Also, oddly, [this ](https://mais.sbt.com.br/vod/6354530551112?t=0)Sonic series does work without DRM, but it doesn't have any sound

This is a new streaming platform and will launch August 18th.

On demand still in the works. Some shows in live feed have portuguese voice over, but On demand has only the original sound option. Probably this Sonic series only have ptbr audio and they didn't set up.

**Comment by allanf181** [comment]
I've been doing some tests and found out how to get the JSON of the videos, there are only 3 json requests, one to generate the session, a second with the session to get the policy key and the third of the video actually using the policy key, with this json you can check if it has DRM or not

**Comment by allanf181** [comment]
It is a competitor of Globoplay, which is supported on yt-dlp, only part of the content has DRM because it is licensed content

**Comment by bashonly** [comment]
Doesn't matter who its competitors are. If almost all of the content is DRM-protected then an extractor won't be added. I'm saying this as a courtesy now so that someone doesn't waste their time working on a PR that will never be merged

**Comment by allanf181** [comment]
It's only a part that has DRM, and the catalog is still small, there's a lot of content to be added, original content, most of which doesn't have DRM, there's a part of the history of Brazilian television in this catalog.

**Comment by bashonly** [comment]
An earlier comment said that the "vast majority" of content was DRM. Maybe they were wrong. Maybe not. You are free to write an extractor if you want, but do so at the risk of wasting your own time
