### ISSUE TITLE
Add support for Cambro.tv [NSFW]

### ISSUE THREAD

**Issue by Omegaplexx** [yt-dlp/yt-dlp#10651]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Russia

### Example URLs

https://www.cambro.tv/889534/foxy-menagerie-verre-cambro-xxx4/
https://www.cambro.tv/1063946/foxy-menagerie-verre-11-porn-video/
https://www.cambro.tv/876020/foxy-menagerie-verre-cambrotv-porn2/

### Provide a description that is worded well enough to be understood

yt-dlp uses generic extractor and fails. Shouldn't be a piracy site (https://www.cambro.tv/dmca/). DRM protected vids are shown as "Private". There's no DRM videos in example URLs.

I didn't found www.cambro.tv in supported sites, so I ask you to add an extractor.

Thank you very much for your hard work!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~ $ yt-dlp -vU https://www.cambro.tv/876020/foxy-menagerie-verre-cambrotv-porn2/

[generic] Extracting URL: https://www.cambro.tv/876020/foxy-menagerie-verre-cambrotv-porn2/
[generic] foxy-menagerie-verre-cambrotv-porn2: Downloading webpage
[debug] Command-line config: ['--config-locations', '/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1722722088978].txt', '--cookies', '/data/user/0/com.deniscerri.ytdl/cache/cookies.txt', '-P', '/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/TERMINAL/121', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~QX7wxSoywRrb8v1FN3sNgw==/com.deniscerri.ytdl-1iJ6jseJ4Y52-J4jXAUs3w==/lib/arm64/libffmpeg.so']
[debug] | Config "/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1722722088978].txt": ['-vU', 'https://www.cambro.tv/876020/foxy-menagerie-verre-cambrotv-porn2/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2024.08.01.232808 from yt-dlp/yt-dlp-nightly-builds [919540a96] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-3.18.140-ga7d7014f0e2e-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
ERROR: [generic] Unable to download webpage: _ssl.c:1091: The handshake operation timed out (caused by TransportError('_ssl.c:1091: The handshake operation timed out'))
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/generic.py", line 2384, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 1317, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1091: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/_urllib.py", line 412, in _send
    handle_response_read_exceptions(cause)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/_urllib.py", line 331, in handle_response_read_exceptions
    raise TransportError(cause=e) from e
yt_dlp.networking.exceptions.TransportError: _ssl.c:1091: The handshake operation timed out
```

**Comment by grqz** [comment]
> I didn't found [www.cambro.tv](http://www.cambro.tv) in supported sites, so I ask you to add an extractor.

An extractor is not required sometimes. The `genericIE` can extract it.
<details><summary>log</summary>

```log
[debug] Command-line config: ['-vF', 'https://www.cambro.tv/889534/foxy-menagerie-verre-cambro-xxx4/', 'https://www.cambro.tv/1063946/foxy-menagerie-verre-11-porn-video/', 'https://www.cambro.tv/876020/foxy-menagerie-verre-cambrotv-porn2/']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.31.232733 from yt-dlp/yt-dlp-nightly-builds [d19fcb934] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-115821-g0060a368b1-20240613 (setts), ffprobe N-115821-g0060a368b1-20240613
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[generic] Extracting URL: https://www.cambro.tv/889534/foxy-menagerie-verre-cambro-xxx4/
[generic] foxy-menagerie-verre-cambro-xxx4: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] foxy-menagerie-verre-cambro-xxx4: Extracting information
[debug] Looking for embeds
[debug] Identified a KVS Player
WARNING: [generic] Untested major version (10.14.10) in player engine - download may fail.
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 889534:
ID        EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
──────────────────────────────────────────────────
video_url mp4 unknown    │ https │ unknown unknown
[generic] Extracting URL: https://www.cambro.tv/1063946/foxy-menagerie-verre-11-porn-video/
[generic] foxy-menagerie-verre-11-porn-video: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] foxy-menagerie-verre-11-porn-video: Extracting information
[debug] Looking for embeds
[debug] Identified a KVS Player
WARNING: [generic] Untested major version (10.14.10) in player engine - download may fail.
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1063946:
ID        EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
──────────────────────────────────────────────────
video_url mp4 unknown    │ https │ unknown unknown
[generic] Extracting URL: https://www.cambro.tv/876020/foxy-menagerie-verre-cambrotv-porn2/
[generic] foxy-menagerie-verre-cambrotv-porn2: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] foxy-menagerie-verre-cambrotv-porn2: Extracting information
[debug] Looking for embeds
[debug] Identified a KVS Player
WARNING: [generic] Untested major version (10.14.10) in player engine - download may fail.
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 876020:
ID        EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
──────────────────────────────────────────────────
video_url mp4 unknown    │ https │ unknown unknown
```

</details>



> ```shell
> yt_dlp.networking.exceptions.TransportError: _ssl.c:1091: The handshake operation timed out
> ```

I cant reproduce that. Can you access the links with your browser?

**Comment by Omegaplexx** [comment]
> Can you access the links with your browser?
Yes, I can play videos without any problems. Just tried to download it in different network but still get this weird handshake timeout

<details><summary>Log</summary>
<p>
~ $ yt-dlp -vUF https://www.cambro.tv/1063946/foxy-menagerie-verre-11-porn-video/

[generic] Extracting URL: https://www.cambro.tv/1063946/foxy-menagerie-verre-11-porn-video/
[generic] foxy-menagerie-verre-11-porn-video: Downloading webpage
[debug] Command-line config: ['--config-locations', '/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1722785745657].txt', '--cookies', '/data/user/0/com.deniscerri.ytdl/cache/cookies.txt', '-P', '/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/TERMINAL/125', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~QX7wxSoywRrb8v1FN3sNgw==/com.deniscerri.ytdl-1iJ6jseJ4Y52-J4jXAUs3w==/lib/arm64/libffmpeg.so']
[debug] | Config "/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1722785745657].txt": ['-vUF', 'https://www.cambro.tv/1063946/foxy-menagerie-verre-11-porn-video/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2024.08.01.232808 from yt-dlp/yt-dlp-nightly-builds [919540a96] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-3.18.140-ga7d7014f0e2e-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
ERROR: [generic] Unable to download webpage: _ssl.c:1091: The handshake operation timed out (caused by TransportError('_ssl.c:1091: The handshake operation timed out'))
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/generic.py", line 2384, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 1317, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1091: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/_urllib.py", line 412, in _send
    handle_response_read_exceptions(cause)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/networking/_urllib.py", line 331, in handle_response_read_exceptions
    raise TransportError(cause=e) from e
yt_dlp.networking.exceptions.TransportError: _ssl.c:1091: The handshake operation timed out
</p>
</details>

**Comment by Omegaplexx** [comment]
Downloading from cambro.tv is supported by yt-dlp
