### ISSUE TITLE
cant download a specific video from twitter

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#10652]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Can't download this specific video for some reason. Tested it on another video post and it worked fine.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://x.com/madnopost/status/17469699967
75858505/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe
)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.
1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3, ffprobe git-2020-06-17-0b3bd00
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04,
 curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.
2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Latest version: stable@2024.08.01 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.01 from yt-dlp/yt-dlp)
[twitter] Extracting URL: https://x.com/madnopost/status/1746969996775858505/
[twitter] 1746969996775858505: Downloading guest token
[twitter] 1746969996775858505: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1746969498719006720
[twitter] 1746969996775858505: Downloading m3u8 information
[debug] Sort order given by extractor: res, proto:m3u8, br, size
[debug] Formats sorted by: hasvid, ie_pref, res, proto:m3u8(8), br, size, lang,
quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, ha
saud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1746969498719006720: Downloading 1 format(s): hls-442+hls-audio-128000-Au
dio
[debug] Invoking hlsnative downloader on "https://video.twimg.com/ext_tw_video/1
746969498719006720/pu/pl/avc1/766x720/cUsy0s7L8EmHx8nY.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 11
[download] Destination: mad ? - "It Means Everything." | | -Audio from the OMORI
 OST | -??do not repost on tiktok or other platforms??- | | | #omori #omoriaubre
y #omorikel #omorisunny #omorifanart #omorianimation #animation [174696949871900
6720].fhls-442.mp4
ERROR: Unable to download video: [Errno 2] No such file or directory: 'mad ? - "
It Means Everything." | | -Audio from the OMORI OST | -??do not repost on tiktok
 or other platforms??- | | | #omori #omoriaubrey #omorikel #omorisunny #omorifan
art #omorianimation #animation [1746969498719006720].fhls-442.mp4.ytdl'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 590, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3465, in process_info
  File "yt_dlp\YoutubeDL.py", line 3203, in dl
  File "yt_dlp\downloader\common.py", line 466, in download
  File "yt_dlp\downloader\hls.py", line 158, in real_download
  File "yt_dlp\downloader\fragment.py", line 77, in _prepare_and_start_frag_down
load
  File "yt_dlp\downloader\fragment.py", line 213, in _prepare_frag_download
  File "yt_dlp\downloader\fragment.py", line 97, in _write_ytdl_file
  File "yt_dlp\downloader\common.py", line 250, in wrapper
  File "yt_dlp\downloader\common.py", line 236, in error_callback
  File "yt_dlp\utils\_utils.py", line 5214, in report_retry
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 256, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 593, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'mad ? - "It Means Every
thing." | | -Audio from the OMORI OST | -??do not repost on tiktok or other plat
forms??- | | | #omori #omoriaubrey #omorikel #omorisunny #omorifanart #omorianim
ation #animation [1746969498719006720].fhls-442.mp4.ytdl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 3015, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 179, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3495, in process_info
yt_dlp.utils.UnavailableVideoError: Unable to download video: [Errno 2] No such
file or directory: 'mad ? - "It Means Everything." | | -Audio from the OMORI OST
 | -??do not repost on tiktok or other platforms??- | | | #omori #omoriaubrey #o
morikel #omorisunny #omorifanart #omorianimation #animation [1746969498719006720
].fhls-442.mp4.ytdl'
```

**Comment by bashonly** [comment]
The output filename is too long. Just need to use an output template that results in a shorter filename, e.g. add `-o "%(title).100B [%(id)s].%(ext)s"` to your command
