### ISSUE TITLE
yt-dlp doesnt works under openBSD

### ISSUE THREAD

**Issue by lm2lm2** [yt-dlp/yt-dlp#10716]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

HTTP Error 403: Forbidden

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --cookies-from-browser firefox https://youtu.be/WfGczM7y7BA -vU 
[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://youtu.be/WfGczM7y7BA', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01]
[debug] Python 3.9.16 (CPython amd64 64bit) - OpenBSD-7.2-amd64-64bit-ELF (LibreSSL 3.6.0, libc 96.2)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: brotli-1.0.9, certifi-2021.10.08, pycrypto-3.15.0, sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/hd/.mozilla/firefox/8z5lv1f0.default-default/cookies.sqlite"
[Cookies] Extracted 0 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2024.08.06, Current version: 2023.02.17
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2024.08.06/_update_spec
ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
[youtube] Extracting URL: https://youtu.be/WfGczM7y7BA
[youtube] WfGczM7y7BA: Downloading webpage
[youtube] WfGczM7y7BA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] WfGczM7y7BA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] WfGczM7y7BA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] WfGczM7y7BA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] WfGczM7y7BA: Downloading player 28fd7348
WARNING: [youtube] WfGczM7y7BA: nsig extraction failed: You may experience throttling for some formats
         n = U3O3Kjnv8bqYwg_DF ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] WfGczM7y7BA: nsig extraction failed: You may experience throttling for some formats
         n = aWbXB7ubFr431II15 ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] WfGczM7y7BA: Downloading 1 format(s): 136+140
[debug] Invoking http downloader on "https://rr5---sn-5hne6nz6.googlevideo.com/videoplayback?expire=1723431775&ei=_ya5Zu36OpiWhcIP78mriQg&ip=185.107.80.83&id=o-AGNYpXp7HI5kSgCK2Ch8ooJ4Mfn_thXzPgtL50bIBTdK&itag=136&aitags=134%2C136%2C160&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=mY&mm=31%2C29&mn=sn-5hne6nz6%2Csn-5hneknes&ms=au%2Crdu&mv=m&mvi=5&pl=25&initcwndbps=445000&bui=AQmm2ewBEtbAPz7QndyMPlfO1H9otjB5uD4l0UfCCM6nQ4Yd4FLzRIH9ppAv300jwE1NaxP_BguSYHbV&spc=Mv1m9jyPD4vkaxJq0LO-Nw0_LNfgBTZ9ddhi_XjSyeqXQiCSPXbDogTCRNAS&vprv=1&svpuc=1&mime=video%2Fmp4&ns=vy6IkLYrBFHSScoDgfNWY-wQ&rqh=1&gir=yes&clen=14397727&dur=59.358&lmt=1545569469554192&mt=1723409823&fvip=2&keepalive=yes&c=WEB&sefc=1&txp=5535432&n=aWbXB7ubFr431II15&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAI2n8QOu1iaFL-hTucnwdKRQwzKx1yHf4wNGjrw35AviAiB9lyVcekJ8caqNl9AX6wbx0ZlXv3VrmgTB78ummFyeYA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAItBPvumMryZ5TEYYhdeKeZb7bKTM9xdVAMB2R0riW91AiEA7wKdV6zPIVo3TN6Rolm95c5j-ZImLejtLT0MJRzSXxk%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3213, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2954, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 376, in real_download
    establish_connection()
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3726, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by Grub4K** [comment]
Outdated version. Update

**Comment by lm2lm2** [comment]
> Outdated version. Update

you're right, but it was something to upgrade to latest version, using pip under openbsd : 
1.  pkg_add py3-pip
2.  pip3.9 install yt-dlp 
took me half an hour to find out on the web the proper commands, especially for pip : 
https://www.mail-archive.com/misc@openbsd.org/msg187669.html

**Comment by bashonly** [comment]
there's also https://github.com/yt-dlp/yt-dlp/wiki/Installation
