### ISSUE TITLE
PBS -> WGBH/Channel 2 (WGBH) extractor doesn't seems to recognize URL

### ISSUE THREAD

**Issue by huibw** [yt-dlp/yt-dlp#10728]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

When trying to download a public video from WGBH Boston ([WGBH video](https://video.wgbh.org/video/episode-1-3fjvai/)), it reverts to a generic extractor, resulting in an error, even though the video FQDN is included in the PBS extractor (currently line 65).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-F', 'https://video.wgbh.org/video/episode-1-3fjvai/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds [a06508664] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://video.wgbh.org/video/episode-1-3fjvai/
[generic] episode-1-3fjvai: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] episode-1-3fjvai: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://video.wgbh.org/video/episode-1-3fjvai/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://video.wgbh.org/video/episode-1-3fjvai/
```

**Comment by huibw** [comment]
Even when using "--use-extractors pbs", it returns "No suitable extractor found"
```
yt-dlp.exe -vU --use-extractors pbs -F https://video.wgbh.org/video/episode-1-3fjvai/
[debug] Command-line config: ['-vU', '--use-extractors', 'pbs', '-F', 'https://video.wgbh.org/video/episode-1-3fjvai/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds [a06508664] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds)
ERROR: No suitable extractor found for URL https://video.wgbh.org/video/episode-1-3fjvai/
```

**Comment by october262** [comment]
down below the video, click embed - click the first line and next to src= is the link to the video "https://player.pbs.org/viralplayer/3072823474/"

**Comment by bashonly** [comment]
This is essentially the same issue as #8703, except with a different PBS affiliate. That issue would be fixed by #9740, which I've been hesitant to merge since I think we need a general solution for all of the known affiliate sites (that would fix both this issue and #8703)

**Comment by huibw** [comment]
@october262 Thanks! Replacing wgbh with pbs is a simple workaround.

@bashonly I did see that issue but the output was different and I didn't know enough to determine if it was related. Thanks for looking at it and considering options for a resolution.

**Comment by dirkf** [comment]
Fixed in #12024?

**Comment by bashonly** [comment]
13825ab77815ee6e1603abbecbb9f3795057b93c
