### ISSUE TITLE
format selector partially broken

### ISSUE THREAD

**Issue by BlackLotus** [yt-dlp/yt-dlp#10727]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Some rules to filter videos are broken on some sites. Here is an example for youtube.
https://www.youtube.com/watch?v=1gUP_43J7wY has avc, vp9 and av1 available. Filtering for a specific video format is done through
`-f '[vcodec=foo]'` if you want to filter for a codec _starting_ with something you can use `^=`
So let's make sure what vcodecs exist
```
$ yt-dlp -F 'https://www.youtube.com/watch?v=1gUP_43J7wY'
[youtube] Extracting URL: https://www.youtube.com/watch?v=1gUP_43J7wY
[youtube] 1gUP_43J7wY: Downloading webpage
[youtube] 1gUP_43J7wY: Downloading ios player API JSON
[youtube] 1gUP_43J7wY: Downloading web creator player API JSON
[youtube] 1gUP_43J7wY: Downloading m3u8 information
[info] Available formats for 1gUP_43J7wY:
ID      EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3     mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb2     mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb1     mhtml 160x90       0    │                  mhtml │ images                                  storyboard
sb0     mhtml 320x180      0    │                  mhtml │ images                                  storyboard
233     mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default
234     mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default
139-drc m4a   audio only      2 │   11.00MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, DRC, m4a_dash
249-drc webm  audio only      2 │   11.26MiB   50k https │ audio only          opus        50k 48k [en] low, DRC, webm_dash
250-drc webm  audio only      2 │   14.04MiB   62k https │ audio only          opus        62k 48k [en] low, DRC, webm_dash
139     m4a   audio only      2 │   11.00MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, m4a_dash
249     webm  audio only      2 │   11.23MiB   50k https │ audio only          opus        50k 48k [en] low, webm_dash
250     webm  audio only      2 │   14.03MiB   62k https │ audio only          opus        62k 48k [en] low, webm_dash
140-drc m4a   audio only      2 │   29.19MiB  129k https │ audio only          mp4a.40.2  129k 44k [en] medium, DRC, m4a_dash
251-drc webm  audio only      2 │   26.57MiB  118k https │ audio only          opus       118k 48k [en] medium, DRC, webm_dash
140     m4a   audio only      2 │   29.19MiB  129k https │ audio only          mp4a.40.2  129k 44k [en] medium, m4a_dash
251     webm  audio only      2 │   26.56MiB  118k https │ audio only          opus       118k 48k [en] medium, webm_dash
602     mp4   256x144     15    │ ~ 19.64MiB   87k m3u8  │ vp09.00.10.08   87k video only
394     mp4   256x144     30    │   12.21MiB   54k https │ av01.0.00M.08   54k video only          144p, mp4_dash
269     mp4   256x144     30    │ ~ 37.42MiB  166k m3u8  │ avc1.4D400C    166k video only
160     mp4   256x144     30    │    8.71MiB   39k https │ avc1.4D400C     39k video only          144p, mp4_dash
603     mp4   256x144     30    │ ~ 35.16MiB  156k m3u8  │ vp09.00.11.08  156k video only
278     webm  256x144     30    │   18.92MiB   84k https │ vp09.00.11.08   84k video only          144p, webm_dash
395     mp4   426x240     30    │   17.08MiB   76k https │ av01.0.00M.08   76k video only          240p, mp4_dash
229     mp4   426x240     30    │ ~ 51.37MiB  228k m3u8  │ avc1.4D4015    228k video only
133     mp4   426x240     30    │   14.27MiB   63k https │ avc1.4D4015     63k video only          240p, mp4_dash
604     mp4   426x240     30    │ ~ 64.95MiB  288k m3u8  │ vp09.00.20.08  288k video only
242     webm  426x240     30    │   20.07MiB   89k https │ vp09.00.20.08   89k video only          240p, webm_dash
396     mp4   640x360     30    │   30.51MiB  135k https │ av01.0.01M.08  135k video only          360p, mp4_dash
230     mp4   640x360     30    │ ~109.98MiB  488k m3u8  │ avc1.4D401E    488k video only
134     mp4   640x360     30    │   24.75MiB  110k https │ avc1.4D401E    110k video only          360p, mp4_dash
18      mp4   640x360     30  2 │   86.71MiB  385k https │ avc1.42001E         mp4a.40.2       44k [en] 360p
605     mp4   640x360     30    │ ~125.81MiB  558k m3u8  │ vp09.00.21.08  558k video only
243     webm  640x360     30    │   35.54MiB  158k https │ vp09.00.21.08  158k video only          360p, webm_dash
397     mp4   854x480     30    │   50.96MiB  226k https │ av01.0.04M.08  226k video only          480p, mp4_dash
231     mp4   854x480     30    │ ~134.06MiB  595k m3u8  │ avc1.4D401F    595k video only
135     mp4   854x480     30    │   36.59MiB  162k https │ avc1.4D401F    162k video only          480p, mp4_dash
606     mp4   854x480     30    │ ~184.03MiB  816k m3u8  │ vp09.00.30.08  816k video only
244     webm  854x480     30    │   50.62MiB  225k https │ vp09.00.30.08  225k video only          480p, webm_dash
398     mp4   1280x720    30    │   89.52MiB  397k https │ av01.0.05M.08  397k video only          720p, mp4_dash
232     mp4   1280x720    30    │ ~210.31MiB  933k m3u8  │ avc1.4D401F    933k video only
136     mp4   1280x720    30    │   68.72MiB  305k https │ avc1.4D401F    305k video only          720p, mp4_dash
609     mp4   1280x720    30    │ ~372.51MiB 1652k m3u8  │ vp09.00.31.08 1652k video only
247     webm  1280x720    30    │  121.07MiB  537k https │ vp09.00.31.08  537k video only          720p, webm_dash
399     mp4   1920x1080   30    │  162.40MiB  720k https │ av01.0.08M.08  720k video only          1080p, mp4_dash
270     mp4   1920x1080   30    │ ~661.89MiB 2936k m3u8  │ avc1.640028   2936k video only
137     mp4   1920x1080   30    │  441.62MiB 1959k https │ avc1.640028   1959k video only          1080p, mp4_dash
614     mp4   1920x1080   30    │ ~613.83MiB 2723k m3u8  │ vp09.00.40.08 2723k video only
248     webm  1920x1080   30    │  240.02MiB 1065k https │ vp09.00.40.08 1065k video only          1080p, webm_dash
616     mp4   1920x1080   30    │ ~  1.20GiB 5469k m3u8  │ vp09.00.40.08 5469k video only          Premium
```
Downloading a h264 version
`yt-dlp -f '[vcodec^=avc]' 'https://www.youtube.com/watch?v=1gUP_43J7wY'`
works
`yt-dlp -f '[vcodec^=vp]' 'https://www.youtube.com/watch?v=1gUP_43J7wY'` and `yt-dlp -f '[vcodec^=av0]' 'https://www.youtube.com/watch?v=1gUP_43J7wY'` don't work.
Here the output from `yt-dlp -f '[vcodec^=av0]' -vU 'https://www.youtube.com/watch?v=1gUP_43J7wY'`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', '[vcodec^=av0]', '-vU', 'https://www.youtube.com/watch?v=1gUP_43J7wY']
[debug] User config "/home/thomas/.config/yt-dlp/config": []
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Python 3.12.5 (CPython x86_64 64bit) - Linux-6.10.2-zen1-2-zen-x86_64-with-glibc2.40 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotlicffi-1.1.0.0, certifi-2024.07.04, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.0, urllib3-1.26.19, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=1gUP_43J7wY
[youtube] 1gUP_43J7wY: Downloading webpage
[youtube] 1gUP_43J7wY: Downloading ios player API JSON
[youtube] 1gUP_43J7wY: Downloading web creator player API JSON
[debug] Loading youtube-nsig.28fd7348 from cache
[debug] [youtube] Decrypted nsig P5F_e-597B2Pm8VGU => phKYFT0pF9YmLg
[debug] Loading youtube-nsig.28fd7348 from cache
[debug] [youtube] Decrypted nsig P5Knj4nesmX2AFRHj => cv61L90mleVAjw
[youtube] 1gUP_43J7wY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] 1gUP_43J7wY: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2977, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] 1gUP_43J7wY: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by grqz** [comment]
please use `-S "vcodec:vp09"` instead.
if you still want to use -f, use `-f "(bv[vcodec^=vp]+ba)/b[vcodec^=vp]"`
I don't think it's broken, maybe your filter only matches `b[vcodec^=vp]`, but in your case, vp09 formats are all `video only`

**Comment by bashonly** [comment]
> I don't think it's broken, seems like your filter only matches `b[vcodec^=vp]`, but in your case, vp09 formats are all `video only`, and so are av01 formats

This is correct, `-f '[vcodec=foo]'` is equivalent to `-f 'best[vcodec=foo]'`, so separate video and audio formats are being excluded. You'd want to use `-f 'bv*[vcodec=foo]+ba/b[vcodec=foo]'`. Or, as grqz pointed out, you can use format sorting (`-S`) instead, which can often achieve the same result while being less cumbersome
