### ISSUE TITLE
[YouTube] Better handling of missing channel tabs, and the videos tab specifically

### ISSUE THREAD

**Issue by cow1337killer3** [yt-dlp/yt-dlp#10804]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

If you download an empty playlist (with 0 videos), yt-dlp doesn't throw an error. I think that makes the most sense and that behavior should also be used for when a channel doesn't have a tab specified in a URL. So when trying to download `<channel URL>/shorts` on a channel that doesn't have a shorts tab, it shouldn't throw an error and just consider it successfully downloaded... since you technically did successfully download all 0 shorts that were available. A warning could optionally be output to console as well.

Another more specific issue is that Topic channels don't have a videos tab, but they still can have uploaded videos. In this instance, I think yt-dlp should instead try to download the channel's uploads playlist. [Here's a comment describing how a playlist of a channel's uploads can be found](https://github.com/yt-dlp/yt-dlp/issues/9673#issuecomment-2298830799). 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
This bug is related to the semantics/behavior of yt-dlp
```

**Comment by bashonly** [comment]
can you give examples please?

**Comment by dirkf** [comment]
For instance, test URL https://www.youtube.com/channel/UCKfVa3S1e4PHvxWcwyMMg8w/channels, which may once have produced at least 75 items, now doesn't in the upstream nightly and causes a failure (that I was just adding code to reproduce upstream) in _yt-dlp_ stable because `This channel does not have a channels tab`:
```console
python3.9 test/test_download.py TestDownload.test_YoutubeTab_11
[debug] Loaded 1830 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/channel/UCKfVa3S1e4PHvxWcwyMMg8w/channels
[youtube:tab] UCKfVa3S1e4PHvxWcwyMMg8w/channels: Downloading webpage
[debug] [youtube:tab] Selected tab: 'featured' (home), Requested tab: 'channels'
ERROR: [youtube:tab] UCKfVa3S1e4PHvxWcwyMMg8w: This channel does not have a channels tab
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/extractor/youtube.py", line 4825, in wrapper
    info_dict = func(self, url, smuggled_data)
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/extractor/youtube.py", line 6818, in _real_extract
    raise ExtractorError(f'This channel does not have a {original_tab_id} tab', expected=True)

E
======================================================================
ERROR: test_YoutubeTab_11 (__main__.TestDownload):
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/extractor/youtube.py", line 4825, in wrapper
    info_dict = func(self, url, smuggled_data)
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/extractor/youtube.py", line 6818, in _real_extract
    raise ExtractorError(f'This channel does not have a {original_tab_id} tab', expected=True)
yt_dlp.utils.ExtractorError: [youtube:tab] UCKfVa3S1e4PHvxWcwyMMg8w: This channel does not have a channels tab

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/df/Documents/src/yt-dlp-new/test/test_download.py", line 168, in test_template
    res_dict = ydl.extract_info(
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/YoutubeDL.py", line 1615, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/YoutubeDL.py", line 1644, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/YoutubeDL.py", line 1092, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/df/Documents/src/yt-dlp-new/yt_dlp/YoutubeDL.py", line 1031, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube:tab] UCKfVa3S1e4PHvxWcwyMMg8w: This channel does not have a channels tab

----------------------------------------------------------------------
Ran 1 test in 0.764s

FAILED (errors=1)
$ 
```
The question is whether this URL should just generate 0 videos, possibly with a warning.

**Comment by pukkandan** [comment]
> So when trying to download `<channel URL>/shorts` on a channel that doesn't have a shorts tab, it shouldn't throw an error and just consider it successfully downloaded...

Won't fix. It is not an empty playlist, but an invalid URL and so should error

> Another more specific issue is that Topic channels don't have a videos tab, but they still can have uploaded videos.

Example?
