### ISSUE TITLE
yt-dlp considers partial files successful downloads

### ISSUE THREAD

**Issue by Hawker2** [yt-dlp/yt-dlp#10808]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Right off the bat, I should say I am using PR #10799 to allow downloading from spankbang. I don't believe this is related to the bug I am reporting, but in full disclosure this is not an unaltered binary (as #6545 blocks using it).

In short, broken downloads (numerous missing fragments) are being treated as successful and added to archive. This means people using yt-dlp could inadvertently end up with partial/broken files and never know it.

**Example**
When downloading "https://spankbang.party/8egjx/video/hmv+all+that+i+need+albinohawk", there are numerous fragments that are not found, yielding:
```
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (10/10)...
[download] fragment not found; Skipping fragment 20 ...
```

This is fine (although odd, as the file plays fine in the browser - but that's a bug for another day); if yt-dlp can't download it, mark it as incomplete for future resuming and move on with life.

Instead, after losing a large number of fragments, it finishes and considers the file "complete", even adding it to the archive file so it won't be attempted again. The final video I downloaded was 2:05, whereas the full video is 3:17.

```
$ yt-dlp --no-config --no-cache-dir -v --download-archive downloaded.txt "https://spankbang.party/8egjx/video/hmv+all+that+i+need+albinohawk"
<snip - verbose output below>
$ cat downloaded.txt 
spankbang 8egjx
$ 
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--no-config', '--no-cache-dir', '-v', '--download-archive', 'downloaded.txt', 'https://spankbang.party/8egjx/video/hmv+all+that+i+need+albinohawk']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-3.10.108-x86_64-with-glibc2.36 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.36)
[debug] exe versions: ffmpeg N-54088-gb0203fa72b-static, ffprobe N-54088-gb0203fa72b-static, phantomjs 2.1.1
[debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, sqlite3-3.42.0, urllib3-2.0.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Loading archive file 'downloaded.txt'
[SpankBang] Extracting URL: https://spankbang.party/8egjx/video/hmv+all+that+i+need+albinohawk
[SpankBang] 8egjx: Downloading webpage
[SpankBang] 8egjx: Downloading stream JSON
[SpankBang] 8egjx: Downloading m3u8 information
[SpankBang] 8egjx: Downloading m3u8 information
[SpankBang] 8egjx: Downloading m3u8 information
[SpankBang] 8egjx: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 8egjx: Downloading 1 format(s): hls-3480-1
[debug] Invoking hlsnative downloader on "https://hls-uranus.sb-cd.com/hls/1/4/14111565-720p.mp4/index-v1-a1.m3u8?_tid=14111565&d=1&m=46&secure=J9W7PXFzYsFOVkfrqj0luw,1724233495"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 35
[download] Destination: Hmv All That I Need albinohawk [8egjx].mp4
[download]   3.8% of ~  42.49MiB at    2.20MiB/s ETA Unknown (frag 2/35)[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 3 (10/10)...
[download] fragment not found; Skipping fragment 3 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4 (10/10)...
[download] fragment not found; Skipping fragment 4 ...
[download]   4.3% of ~  38.81MiB at    1.77MiB/s ETA 00:47 (frag 2/35)Exception ignored in: <ssl.SSLSocket [closed] fd=7, family=2, type=1, proto=6>
Traceback (most recent call last):
  File "/volume1/Apps/bin/yt-dlp-master/yt_dlp/YoutubeDL.py", line 1271, in _traverse_infodict
    return traverse_obj(info_dict, fields, traverse_string=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed <ssl.SSLSocket [closed] fd=7, family=2, type=1, proto=6>
[download]   5.7% of ~  58.35MiB at    1.41MiB/s ETA 00:45 (frag 3/35)[download] Got error: HTTP Error 404: Not Found. Retrying fragment 6 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 6 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 6 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 6 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 6 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 6 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 6 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 6 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 6 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 6 (10/10)...
[download] fragment not found; Skipping fragment 6 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 7 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 7 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 7 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 7 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 7 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 7 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 7 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 7 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 7 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 7 (10/10)...
[download] fragment not found; Skipping fragment 7 ...
[download]   8.1% of ~  69.59MiB at    1.28MiB/s ETA 00:44 (frag 4/35)[download] Got error: HTTP Error 404: Not Found. Retrying fragment 9 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 9 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 9 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 9 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 9 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 9 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 9 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 9 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 9 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 9 (10/10)...
[download] fragment not found; Skipping fragment 9 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 10 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 10 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 10 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 10 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 10 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 10 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 10 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 10 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 10 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 10 (10/10)...
[download] fragment not found; Skipping fragment 10 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 11 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 11 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 11 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 11 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 11 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 11 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 11 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 11 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 11 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 11 (10/10)...
[download] fragment not found; Skipping fragment 11 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 12 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 12 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 12 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 12 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 12 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 12 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 12 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 12 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 12 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 12 (10/10)...
[download] fragment not found; Skipping fragment 12 ...
[download]  10.8% of ~  77.31MiB at    4.79MiB/s ETA 00:14 (frag 5/35)[download] Got error: HTTP Error 404: Not Found. Retrying fragment 14 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 14 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 14 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 14 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 14 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 14 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 14 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 14 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 14 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 14 (10/10)...
[download] fragment not found; Skipping fragment 14 ...
[download]  13.0% of ~  64.39MiB at    4.14MiB/s ETA 00:14 (frag 5/35)Exception ignored in: <ssl.SSLSocket [closed] fd=12, family=2, type=1, proto=6>
Traceback (most recent call last):
  File "/volume1/Apps/bin/yt-dlp-master/yt_dlp/utils/traversal.py", line 89, in traverse_obj
    casefold = lambda k: k.casefold() if isinstance(k, str) else k
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed <ssl.SSLSocket [closed] fd=12, family=2, type=1, proto=6>
[download]  16.6% of ~  83.26MiB at    4.38MiB/s ETA 00:14 (frag 7/35)[download] Got error: HTTP Error 404: Not Found. Retrying fragment 17 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 17 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 17 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 17 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 17 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 17 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 17 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 17 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 17 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 17 (10/10)...
[download] fragment not found; Skipping fragment 17 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 18 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 18 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 18 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 18 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 18 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 18 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 18 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 18 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 18 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 18 (10/10)...
[download] fragment not found; Skipping fragment 18 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19 (10/10)...
[download] fragment not found; Skipping fragment 19 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 20 (10/10)...
[download] fragment not found; Skipping fragment 20 ...
[download]  25.4% of ~  85.97MiB at   10.20MiB/s ETA 00:09 (frag 10/35)[download] Got error: HTTP Error 404: Not Found. Retrying fragment 24 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 24 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 24 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 24 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 24 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 24 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 24 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 24 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 24 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 24 (10/10)...
[download] fragment not found; Skipping fragment 24 ...
[download]  31.0% of ~  87.22MiB at    6.28MiB/s ETA 00:09 (frag 12/35)[download] Got error: HTTP Error 404: Not Found. Retrying fragment 27 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 27 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 27 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 27 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 27 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 27 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 27 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 27 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 27 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 27 (10/10)...
[download] fragment not found; Skipping fragment 27 ...
[download]  51.2% of ~  89.28MiB at    3.54MiB/s ETA 00:45 (frag 19/35)[download] Got error: HTTP Error 404: Not Found. Retrying fragment 35 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 35 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 35 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 35 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 35 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 35 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 35 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 35 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 35 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 35 (10/10)...
[download] fragment not found; Skipping fragment 35 ...
[download] 100% of   45.74MiB in 00:00:24 at 1.91MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Hmv All That I Need albinohawk [8egjx].mp4'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Hmv All That I Need albinohawk [8egjx].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Hmv All That I Need albinohawk [8egjx].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Hmv All That I Need albinohawk [8egjx].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Hmv All That I Need albinohawk [8egjx].temp.mp4'
[debug] Adding to archive: spankbang 8egjx
```

**Comment by bashonly** [comment]
Use `--abort-on-unavailable-fragments`

**Comment by Hawker2** [comment]
Even if it aborts due to missing fragments (odd option, but good to know), it should never consider a partial file "complete" and add to the archive. The expectation is anything added to archive has been downloaded correctly; thus it can be skipped from any future check.

**Comment by bashonly** [comment]
>  it should never consider a partial file "complete" and add to the archive. 

If this is your belief, then add `--abort-on-unavailable-fragments` to your config: problem solved.

As for why it's not the default behavior, see https://github.com/yt-dlp/yt-dlp/issues/6757#issuecomment-1506156337
