### ISSUE TITLE
ZenYandex: broken extractor. Cannot access local variable 'fmts'.

### ISSUE THREAD

**Issue by dr-jagulator** [yt-dlp/yt-dlp#10818]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

Broken yandexvideo info exctraction.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
# yt-dlp -vUF https://dzen.ru/video/watch/65379336b5dfe46d375faa00
[debug] Command-line config: ['-vUF', 'https://dzen.ru/video/watch/65379336b5dfe46d375faa00']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-20-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/65379336b5dfe46d375faa00
[ZenYandex] 65379336b5dfe46d375faa00: Downloading webpage
[ZenYandex] 65379336b5dfe46d375faa00: Redirecting
ERROR: cannot access local variable 'fmts' where it is not associated with a value
Traceback (most recent call last):
  File "/root/whisperx/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/whisperx/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/root/whisperx/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/whisperx/venv/lib/python3.11/site-packages/yt_dlp/extractor/yandexvideo.py", line 276, in _real_extract
    formats.extend(fmts)
                   ^^^^
UnboundLocalError: cannot access local variable 'fmts' where it is not associated with a value
```

**Comment by dirkf** [comment]
This would prevent the crash:
```diff
--- old/yt_dlp/extractor/yandexvideo.py
+++ new/yt_dlp/extractor/yandexvideo.py
@@ -273,6 +273,8 @@
                 fmts, subs = self._extract_mpd_formats_and_subtitles(s_url, video_id, mpd_id='dash')
             elif ext == 'm3u8':
                 fmts, subs = self._extract_m3u8_formats_and_subtitles(s_url, video_id, 'mp4')
+            else:
+                fmts, subs = [], {}
             formats.extend(fmts)
             subtitles = self._merge_subtitles(subtitles, subs)
         return {
```
But really the question is what URL `s_url` and extension is being found that does not match `m3u8` or `mpd`. In this case it's a dash manifest but without an y `mpd`. `urlhandle_detect_ext()` could be used to check the type of the resource behind the URL, but a pragmatic approach, on the assumption that a non-`mpd` format URL will probably yield a DASH manifest is to make DASH the default:
```diff
--- old/yt_dlp/extractor/yandexvideo.py
+++ new/yt_dlp/extractor/yandexvideo.py
@@ -273,6 +273,8 @@
                 fmts, subs = self._extract_mpd_formats_and_subtitles(s_url, video_id, mpd_id='dash')
             elif ext == 'm3u8':
                 fmts, subs = self._extract_m3u8_formats_and_subtitles(s_url, video_id, 'mp4')
+            else:
+                fmts, subs = self._extract_mpd_formats_and_subtitles(s_url, video_id, mpd_id='dash', fatal=False)
             formats.extend(fmts)
             subtitles = self._merge_subtitles(subtitles, subs)
         return {
```
Then we get DASH formats as well as HLS, whereas the first patch omits them:
```console
$ yt-dlp-new -vF https://dzen.ru/video/watch/65379336b5dfe46d375faa00
[debug] Command-line config: ['-vF', 'https://dzen.ru/video/watch/65379336b5dfe46d375faa00']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 49f3741a8
[debug] Python 3.9.19 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.23)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2019.11.28, requests-2.25.1, secretstorage-3.2.0, sqlite3-3.37.2, urllib3-1.25.11
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/65379336b5dfe46d375faa00
[ZenYandex] 65379336b5dfe46d375faa00: Downloading webpage
[ZenYandex] 65379336b5dfe46d375faa00: Redirecting
[ZenYandex] 65379336b5dfe46d375faa00: Downloading MPD manifest
[ZenYandex] 65379336b5dfe46d375faa00: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 65379336b5dfe46d375faa00:
ID      EXT RESOLUTION FPS │    TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────
dash-7  m4a audio only     │    36k https │ audio only         mp4a.40.2   36k 44k DASH audio, m4a_dash
dash-8  m4a audio only     │    52k https │ audio only         mp4a.40.2   52k 44k DASH audio, m4a_dash
dash-9  m4a audio only     │    69k https │ audio only         mp4a.40.2   69k 44k DASH audio, m4a_dash
dash-10 m4a audio only     │   134k https │ audio only         mp4a.40.2  134k 44k DASH audio, m4a_dash
dash-11 m4a audio only     │   265k https │ audio only         mp4a.40.2  265k 44k DASH audio, m4a_dash
219     mp4 256x144     30 │   220k m3u8  │ unknown            unknown
dash-1  mp4 256x144     30 │   103k https │ avc1.64000C   103k video only          DASH video, mp4_dash
454     mp4 426x240     30 │   454k m3u8  │ unknown            unknown
dash-2  mp4 426x240     30 │   349k https │ avc1.640015   349k video only          DASH video, mp4_dash
916     mp4 640x360     30 │   917k m3u8  │ unknown            unknown
dash-3  mp4 640x360     30 │   786k https │ avc1.64001E   786k video only          DASH video, mp4_dash
1425    mp4 852x480     30 │  1426k m3u8  │ unknown            unknown
dash-4  mp4 852x480     30 │  1353k https │ avc1.4D401F  1353k video only          DASH video, mp4_dash
5176    mp4 1280x720    60 │  5177k m3u8  │ unknown            unknown
dash-5  mp4 1280x720    60 │  5180k https │ avc1.4D4028  5180k video only          DASH video, mp4_dash
9691    mp4 1920x1080   60 │  9691k m3u8  │ unknown            unknown
dash-6  mp4 1920x1080   60 │ 10008k https │ avc1.4D402A 10008k video only          DASH video, mp4_dash
$
```
