### ISSUE TITLE
How to download from xiaohongshu.com

### ISSUE THREAD

**Issue by seaklin83546** [yt-dlp/yt-dlp#10814]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi admin and supporter. i want to ask one question. how to download from xiaohongshu.com?

yt-dlp -vU --cookies "cookies.txt" https://www.xiaohongshu.com/explore/66a981250000000009017750
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.xiaohongshu.com/explore/66a981250000000009017750']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds [d2189d3d3] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.08.19.232821/SHA2-256SUMS
Current version: nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: dec09e67683c1f1b019ff09c184234468576f9dc9b9c4d5f1ff992f9f56911f5
Updating to nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.08.19.232821/yt-dlp.exe
Updated yt-dlp to nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds
[debug] Restarting: C:\bin\yt-dlp.exe -vU --cookies cookies.txt https://www.xiaohongshu.com/explore/66a981250000000009017750
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.xiaohongshu.com/explore/66a981250000000009017750']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds [f0bb28504] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds)
[XiaoHongShu] Extracting URL: https://www.xiaohongshu.com/explore/66a981250000000009017750
[XiaoHongShu] 66a981250000000009017750: Downloading webpage
WARNING: Extractor failed to obtain "title". Creating a generic title instead
ERROR: [XiaoHongShu] 66a981250000000009017750: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2847, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1123, in raise_no_formats
yt_dlp.utils.ExtractorError: [XiaoHongShu] 66a981250000000009017750: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --cookies "cookies.txt" https://www.xiaohongshu.com/explore/66a981250000000009017750
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.xiaohongshu.com/explore/66a981250000000009017750']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds [d2189d3d3] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.08.19.232821/SHA2-256SUMS
Current version: nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: dec09e67683c1f1b019ff09c184234468576f9dc9b9c4d5f1ff992f9f56911f5
Updating to nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.08.19.232821/yt-dlp.exe
Updated yt-dlp to nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds
[debug] Restarting: C:\bin\yt-dlp.exe -vU --cookies cookies.txt https://www.xiaohongshu.com/explore/66a981250000000009017750
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.xiaohongshu.com/explore/66a981250000000009017750']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds [f0bb28504] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds)
[XiaoHongShu] Extracting URL: https://www.xiaohongshu.com/explore/66a981250000000009017750
[XiaoHongShu] 66a981250000000009017750: Downloading webpage
WARNING: Extractor failed to obtain "title". Creating a generic title instead
ERROR: [XiaoHongShu] 66a981250000000009017750: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2847, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1123, in raise_no_formats
yt_dlp.utils.ExtractorError: [XiaoHongShu] 66a981250000000009017750: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by travelgirl-fics** [comment]
have seen same error on facebook reels video:

10:34:36.04 - 2024-1009
 ... C:\tools\media\tools\yt-dlp\yt-dlp.exe -U
Current version: stable@2024.08.01 from yt-dlp/yt-dlp
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
Current Build Hash: d0c9ce0a75a46882d321d942426d3e179a702d1659be641d9c7fcbe1c6b779ee
Updating to stable@2024.10.07 from yt-dlp/yt-dlp ...
Updated yt-dlp to stable@2024.10.07 from yt-dlp/yt-dlp

= = = =
10:35:23.43 - 2024-1009
 ... yt-dlp.bat            4   "https://www.facebook.com/reel/888479522746610"
[facebook:reel] Extracting URL: https://www.facebook.com/reel/888479522746610
[facebook] Extracting URL: https://m.facebook.com/watch/?v=888479522746610&_rdr
[facebook] 888479522746610: Downloading webpage
ERROR: [facebook] 888479522746610: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
.

**Comment by domainname** [comment]
@seaklin83546  XHS video url looks like `https://www.xiaohongshu.com/explore/66a981250000000009017750?xsec_token=<token-here>&xsec_source=<source-here>` now. You need to extract a url like this.

**Comment by kekewind** [comment]
> @seaklin83546 XHS 视频网址`https://www.xiaohongshu.com/explore/66a981250000000009017750?xsec_token=<token-here>&xsec_source=<source-here>`现在看起来像这样。您需要提取一个这样的网址。

是的，加了这个认证

**Comment by Bratzmeister** [comment]
from my observation the video file linked to the video player on the webpage does lead to 404 when calling directly. however when you run the video in the player you find a url for the stream in network tab in dev tools.
example page: https://www.xiaohongshu.com/explore/6787924f000000001b0098b5?app_platform=android&ignoreEngage=true&app_version=8.59.2&share_from_user_hidden=true&xsec_source=app_share&type=video&xsec_token=CBhVjf-SLVWvh6-rHJgD1qxBREqbAx35RJ428oQDDh9VE=&author_share=1&xhsshare=CopyLink&shareRedId=OD07OEY6SEs2NzUyOTgwNjZIOThHOTxP&apptime=1738067568&share_id=918d54ad43f746b399fac135d2ba31c3
broken url from video element in html: blob:https://www.xiaohongshu.com/cbf4d901-3a3d-4d73-9014-b8904376090e
working cdn video file after pressing play button: https://sns-video-yc.xhscdn.com/stream/79/110/259/01e787924d7bc323010370039469942844_259.mp4

**Comment by scrutinizer11** [comment]
The issue is back. 

```bash
[debug] Command-line config: ['--proxy', 'localhost:3128', '-Uv', '--no-check-certificates']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.01.26 from yt-dlp/yt-dlp [3b4531934] (darwin_legacy_exe)
[debug] Python 3.10.5 (CPython x86_64 64bit) - macOS-10.9.5-x86_64-i386-64bit (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-101508-ge93403b (setts), ffprobe N-101508-ge93403b
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.3.0, websockets-14.2
[debug] Proxy map: {'all': 'localhost:3128'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.01.26 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.01.26 from yt-dlp/yt-dlp)
```

**Comment by scrutinizer11** [comment]
The issue is back.

```
[debug] Command-line config: ['--proxy', 'localhost:3128', '--update-to', 'nightly', '-v', '--no-check-certificates', '--no-warnings', '--geo-bypass', '-f', 'm4a', '--output', '/Users/iljashebalin/Music/Downloaded From Internet/%(title)s.%(ext)s', '--exec', 'open -R {}', 'https://www.facebook.com/watch?v=632890512531783']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2025.01.30.232843 from yt-dlp/yt-dlp-nightly-builds [03c3d7057] (darwin_legacy_exe)
[debug] Python 3.10.5 (CPython x86_64 64bit) - macOS-10.9.5-x86_64-i386-64bit (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-101508-ge93403b (setts), ffprobe N-101508-ge93403b
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.3.0, websockets-14.2
[debug] Proxy map: {'all': 'localhost:3128'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1840 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2025.01.30.232843 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2025.01.30.232843 from yt-dlp/yt-dlp-nightly-builds)
[facebook] Extracting URL: https://www.facebook.com/watch?v=632890512531783
[facebook] 632890512531783: Downloading webpage
ERROR: [facebook] 632890512531783: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1637, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1793, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1852, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2859, in process_video_result
File "yt_dlp/YoutubeDL.py", line 1126, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 632890512531783: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
