### ISSUE TITLE
support for  JioSaavn artist downloads

### ISSUE THREAD

**Issue by aryanchoudharypro** [yt-dlp/yt-dlp#10823]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.jiosaavn.com/artist/krsna-songs/rYLBEve2z3U_

### Provide a description that is worded well enough to be understood

downloading from JioSaavn supports songs and albums but not artests

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.jiosaavn.com/artist/krsna-songs/rYLBEve2z3U_']
[debug] Portable config "C:\Users\aryan\AppData\Local\WinGet\Packages\yt-dlp.yt-dlp_Microsoft.Winget.Source_8wekyb3d8bbwe\yt-dlp.conf": ['--downloader', 'aria2c', '--output', '%userprofile%\\downloads\\yt-dlp\\%(title)s.%(ext)s', '--extractor-args', 'youtube:player_client=ios,web,mweb']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds [6f9e65374] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.jiosaavn.com/artist/krsna-songs/rYLBEve2z3U_
[generic] rYLBEve2z3U_: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] rYLBEve2z3U_: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.jiosaavn.com/artist/krsna-songs/rYLBEve2z3U_
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.jiosaavn.com/artist/krsna-songs/rYLBEve2z3U_
```

**Comment by aryanchoudharypro** [comment]
hi, i saw a Pull request solveing this issue, was it merged? if not is there a way i can take a build with that cummit and download that build to test?

**Comment by bashonly** [comment]
There has not been a pull request to add support for artist downloads. There was #9612, which extracts the `artists` metadata field for song downloads

**Comment by aryanchoudharypro** [comment]
Sorry, I misunderstood
