### ISSUE TITLE
Unsupported Tiktok URL including photo with sound

### ISSUE THREAD

**Issue by nikalasmd** [yt-dlp/yt-dlp#10870]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I tried to download a link from tiktok witch which is a photo with music and not a normal video and I got an error message.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
c:\>yt-dlp.exe -vU https://www.tiktok.com/@croatian_memes/photo/7406655666472979745?_d=secCgYIASAHKAESPgo8MVFrKEFm1YROLgGqS3uoOc8zwKGbUfXIRJhN05eIKiY6ag6I57DMdCc2w2vmsPhsRrjRujTn6sZCjBxMGgA%3D
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@croatian_memes/photo/7406655666472979745?_d=secCgYIASAHKAESPgo8MVFrKEFm1YROLgGqS3uoOc8zwKGbUfXIRJhN05eIKiY6ag6I57DMdCc2w2vmsPhsRrjRujTn6sZCjBxMGgA%3D']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.tiktok.com/@croatian_memes/photo/7406655666472979745?_d=secCgYIASAHKAESPgo8MVFrKEFm1YROLgGqS3uoOc8zwKGbUfXIRJhN05eIKiY6ag6I57DMdCc2w2vmsPhsRrjRujTn6sZCjBxMGgA%3D
[generic] 7406655666472979745?_d=secCgYIASAHKAESPgo8MVFrKEFm1YROLgGqS3uoOc8zwKGbUfXIRJhN05eIKiY6ag6I57DMdCc2w2vmsPhsRrjRujTn6sZCjBxMGgA=: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 7406655666472979745?_d=secCgYIASAHKAESPgo8MVFrKEFm1YROLgGqS3uoOc8zwKGbUfXIRJhN05eIKiY6ag6I57DMdCc2w2vmsPhsRrjRujTn6sZCjBxMGgA=: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tiktok.com/@croatian_memes/photo/7406655666472979745?_d=secCgYIASAHKAESPgo8MVFrKEFm1YROLgGqS3uoOc8zwKGbUfXIRJhN05eIKiY6ag6I57DMdCc2w2vmsPhsRrjRujTn6sZCjBxMGgA%3D
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@croatian_memes/photo/7406655666472979745?_d=secCgYIASAHKAESPgo8MVFrKEFm1YROLgGqS3uoOc8zwKGbUfXIRJhN05eIKiY6ag6I57DMdCc2w2vmsPhsRrjRujTn6sZCjBxMGgA%3D
```

**Comment by Gabriel29306** [comment]
Is there any news?

**Comment by Gabriel29306** [comment]
Is there any news?

**Comment by InklingGirl** [comment]
Same here.

**Comment by CoolDouble** [comment]
From what I understand it cannot download images. I hope that this feature would be added!

**Comment by CasualYT31** [comment]
My understanding is that downloading images from Tiktok is out of the scope of `yt-dlp`.

Tiktok support in `gallery-dl` was added recently, so you can use that!

**Comment by CasualYT31** [comment]
Additionally, you can still download the audio from `yt-dlp` by replacing `/photo/` with `/video/`, but `gallery-dl` supports downloading audio without `yt-dlp`.
