### ISSUE TITLE
Add support for onsen.ag

### ISSUE THREAD

**Issue by snowykoyuki** [yt-dlp/yt-dlp#10902]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Japan

### Example URLs

- Playlist: https://www.onsen.ag/program/lycoris-recoil
- Playlist: https://www.onsen.ag/program/rezero

### Provide a description that is worded well enough to be understood

The site is not supported and the extractor was not able to find the video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.onsen.ag/program/lycoris-recoil']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (debian*)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-41-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.onsen.ag/program/lycoris-recoil
[generic] lycoris-recoil: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] lycoris-recoil: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.onsen.ag/program/lycoris-recoil
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.onsen.ag/program/lycoris-recoil
```

**Comment by h-takeyeah** [comment]
The extracted JSON contains all data of programs that onsen.ag streams, which make the data so heavy (~18MBytes extracted).

onsen.ag has the web API and the endpoint `https://onsen.ag/web_api/programs/:directory_name` will help to get the information of the specific program. `directory_name` is `lycoris-recoil` in the first post of this issue.
Anyway, utilizing this endpoint would be things more simple than extracting JSON object from the page.
onsen.ag site itself doesn't use this web API and it extracts the embedded JSON string (powered by Nuxt.js). Therefore, to follow this official site behavior, the implementation with extraction may be better choice.

ref <https://github.com/kawaiioverflow/onsen-api-docs>

**Comment by bashonly** [comment]
The linked pull request (which I'll try to review soon) uses that API endpoint except with the specific program ID so that we don't have to download 18MB of JSON to memory

**Comment by h-takeyeah** [comment]
I overlooked that. Sorry for the confusion. Thanks.
