### ISSUE TITLE
Generic site support: Australian Football League (AFL) websites

### ISSUE THREAD

**Issue by pzhlkj6612** [yt-dlp/yt-dlp#10909]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

| URL | Content
|:- |:-
| AFLW | -
| https://www.afl.com.au/aflw/video/all-video | Latest AFLW Videos
| https://www.afl.com.au/aflw/podcasts/workplay | Workplay: Beyond the Game
| https://www.afl.com.au/aflw/matches/match-videos?comp=2 | AFL Preseason § AFLW Match Videos
| AFL | -
| https://www.afl.com.au/video/all-video | Latest AFL Videos
| https://www.afl.com.au/podcasts/afl-daily | AFL Daily
| https://www.afl.com.au/matches/match-videos?comp=16 | Under 18 Boys National Championships § AFL Match Videos
| clubs | -
| https://www.afc.com.au/thecrowsshow | The Crows Show - Radio § Adelaide Crows Football Club
| https://www.afc.com.au/crowsradioshow | The Crows Show - TV § Adelaide Crows Football Club
| https://www.lions.com.au/video/all-video | Latest Videos of the Brisbane Lions Football Club
| https://www.carltonfc.com.au/podcasts/summer-sessions | Summer Sessions § the Carlton Football Club

### Provide a description that is worded well enough to be understood

Extended from #2833.

These websites are built by Telstra [^1][^2] and they seem to be based on the same framework, so we may be able to support all of them.

[^1]: Telstra Group Limited - https://en.wikipedia.org/wiki/Telstra
[^2]: Telstra: Broadband Internet, NBN, 5G, TV & Mobile Phone Services - https://www.telstra.com.au/

<br>

Single videos are downloadable by the `brightcove:new` embed extractor:

```
[generic] Extracting URL: https://www.lions.com.au/video/1644772/ah-chee-we-believe-our-footy-can-beat-the-best?videoId=164...shFrom=172... 
[generic] ah-chee-we-believe-our-footy-can-beat-the-best?videoId=1644772&modal=true&type=video&publishFrom=172...: Downloading webpage
WARNING: [generic] Falling back on generic information extractor 
[generic] ah-chee-we-believe-our-footy-can-beat-the-best?videoId=1644772&modal=true&type=video&publishFrom=172...: Extracting information 
[brightcove:new] 6361371134112: Checking possible brightcove video URL 
WARNING: [MediaStream] None: Failed to parse JSON: Expecting ',' delimiter in 'Ah Chee: "We believe': line 4 column 32 (char 114) 
[brightcove:new] Extracting URL: https://players.brightcove.net/6057984922001/pFcMhmjx5_default/index.html?videoId=6361371134112#_...D172...%22%7D 
[brightcove:new] 6361371134112: Downloading JSON metadata
[brightcove:new] 6361371134112: Downloading m3u8 information 
[info] 6361371134112: Downloading 1 format(s): hls-6190 
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 52 
[download] Destination: Ah Chee： ＂We believe our footy can beat the best＂ [6361371134112].mp4
...

```

.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.afl.com.au/aflw/video/all-video']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.9 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg n6.1.1-7-ga267d4ad4c-20240222 (setts), ffprobe n6.1.1-7-ga267d4ad4c-20240222 
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.1, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp 
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.afl.com.au/aflw/video/all-video 
[generic] all-video: Downloading webpage
WARNING: [generic] Falling back on generic information extractor 
[generic] all-video: Extracting information 
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.afl.com.au/aflw/video/all-video 
Traceback (most recent call last):
  File ".../yt-dlp/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../yt-dlp/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File ".../yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File ".../yt-dlp/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.afl.com.au/aflw/video/all-video
```

**Comment by gamer191** [comment]
> WARNING: [MediaStream] None: Failed to parse JSON: Expecting ',' delimiter in 'Ah Chee: "We believe': line 4 column 32 (char 114)

Off-topic for the request, but I've verified that this is a site bug and not a bug in yt-dlp
This can be verified by running `curl https://www.lions.com.au/video/1644772 --silent|grep '"name": "Ah'` which will output an invalid JSON line (it has an unescaped quote)
