### ISSUE TITLE
[Youtube] Unable to extract initial JS player n function name

### ISSUE THREAD

**Issue by FirewallDaProtogen** [yt-dlp/yt-dlp#10916]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

i dont quite understand what exactly is going wrong but it told me to make an issue

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
\home\nova\Music\MurderDrones> yt-dlp --audio-format mp3 -x --no-flat-playlist --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0" --cookies-from-browser firefox  "https://www.youtube.com/playlist?list=PLwyyUdV4sEKOnT3elPE5d_THK1TDQPnmQ"
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 2259 cookies from firefox
[youtube:tab] PLwyyUdV4sEKOnT3elPE5d_THK1TDQPnmQ: Downloading webpage
[youtube:tab] PLwyyUdV4sEKOnT3elPE5d_THK1TDQPnmQ: Downloading API JSON with unavailable videos
[download] Downloading playlist: Murder drones ost!
[youtube:tab] PLwyyUdV4sEKOnT3elPE5d_THK1TDQPnmQ page 1: Downloading API JSON
[youtube:tab] playlist Murder drones ost!: Downloading 82 videos
[download] Downloading video 1 of 82
[youtube] 2RL2e6cK5DI: Downloading webpage
[youtube] 2RL2e6cK5DI: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] 2RL2e6cK5DI: Downloading android player API JSON (retry #1)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] 2RL2e6cK5DI: Downloading android player API JSON (retry #2)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] 2RL2e6cK5DI: Downloading android player API JSON (retry #3)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 2RL2e6cK5DI: Downloading player 57c75fa4
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = F5Bm2QzmtTzopSk ; player = https://www.youtube.com/s/player/57c75fa4/player_ias.vflset/en_US/base.js
2RL2e6cK5DI: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2517, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2543, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2526, in _extract_n_function_name
    nfunc, idx = self._search_regex(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = ciUwyUzNgC6mCZH ; player = https://www.youtube.com/s/player/57c75fa4/player_ias.vflset/en_US/base.js
2RL2e6cK5DI: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2517, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2543, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2526, in _extract_n_function_name
    nfunc, idx = self._search_regex(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[info] 2RL2e6cK5DI: Downloading 1 format(s): 251
ERROR: unable to download video data: HTTP Error 403: Forbidden
[download] Downloading video 2 of 82
[youtube] AZFvFeTCmOA: Downloading webpage
[youtube] AZFvFeTCmOA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] AZFvFeTCmOA: Downloading android player API JSON (retry #1)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] AZFvFeTCmOA: Downloading android player API JSON (retry #2)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] AZFvFeTCmOA: Downloading android player API JSON (retry #3)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = TusrAj7HQOoXOD3 ; player = https://www.youtube.com/s/player/57c75fa4/player_ias.vflset/en_US/base.js
AZFvFeTCmOA: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2517, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2543, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2526, in _extract_n_function_name
    nfunc, idx = self._search_regex(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = DCZomjFO359Cxap ; player = https://www.youtube.com/s/player/57c75fa4/player_ias.vflset/en_US/base.js
AZFvFeTCmOA: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2517, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2543, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2526, in _extract_n_function_name
    nfunc, idx = self._search_regex(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[info] AZFvFeTCmOA: Downloading 1 format(s): 251
ERROR: unable to download video data: HTTP Error 403: Forbidden
[download] Downloading video 3 of 82
[youtube] NXt4UGm2P84: Downloading webpage
[youtube] NXt4UGm2P84: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] NXt4UGm2P84: Downloading android player API JSON (retry #1)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] NXt4UGm2P84: Downloading android player API JSON (retry #2)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] NXt4UGm2P84: Downloading android player API JSON (retry #3)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = btVeV1t7UElT6HT ; player = https://www.youtube.com/s/player/57c75fa4/player_ias.vflset/en_US/base.js
NXt4UGm2P84: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2517, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2543, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2526, in _extract_n_function_name
    nfunc, idx = self._search_regex(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = 01sT0hB_DGYn8bi ; player = https://www.youtube.com/s/player/57c75fa4/player_ias.vflset/en_US/base.js
NXt4UGm2P84: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2517, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2543, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2526, in _extract_n_function_name
    nfunc, idx = self._search_regex(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[info] NXt4UGm2P84: Downloading 1 format(s): 251
ERROR: unable to download video data: HTTP Error 403: Forbidden
[download] Downloading video 4 of 82
[youtube] j4t4BqMq7P0: Downloading webpage
^C
ERROR: Interrupted by user
\home\nova\Music\MurderDrones>
```

**Comment by seproDev** [comment]
You are running a really old version of yt-dlp.
With how often websites change, it is important for a software like yt-dlp to be updated regularly.

**Comment by FirewallDaProtogen** [comment]
oh weird, this is the version from APT so i assumed it was up to date. thanks for telling me!

**Comment by seproDev** [comment]
We don't maintain the packages in Linux distributions and sadly some distributions ship very out of date versions.
I think Debian/Ubuntu has a backports repo with a newer version, but not sure how up to date that is either.
Alternatively you can directly install yt-dlp with pip/pipx/use the zip import build.
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#the-yt-dlp-in-my-package-manager-is-outdatedbroken
