### ISSUE TITLE
[facebook:reel] Extract full description

### ISSUE THREAD

**Issue by seaklin83546** [yt-dlp/yt-dlp#10918]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How to download video from Facebook Reel with full description by use --extractor-descriptions?
Other social media is not a problem, but Facebook is not full description.
Ex. this link https://www.facebook.com/reel/1184723189500416

- Full: Can't say it enough...YOU GUYS are doing amazing things for Peter. Therapy starts September 7th and goes until September 27th.The fundraiser ends tonight at 12am EST and all future purchases/donations will be set aside for his Spring session.We love you and are incredibly grateful for your support and love for Peter and our family.

 - When i downloaded: Can't say it enough...YOU GUYS are doing amazing things for Peter. Therapy starts September 7th and goes until September 27th.The fundraiser ends tonight...

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --write-description https://www.facebook.com/reel/1184723189500416
[debug] Command-line config: ['-vU', '--write-description', 'https://www.facebook.com/reel/1184723189500416']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds [f0bb28504] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.09.02.232855/SHA2-256SUMS
Current version: nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.09.02.232855 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: 6848bc8023593441d18ac46e1d638ad87b1bb80c14622bbaa66fd8282549243b
Updating to nightly@2024.09.02.232855 from yt-dlp/yt-dlp-nightly-builds ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.09.02.232855/yt-dlp.exe
Updated yt-dlp to nightly@2024.09.02.232855 from yt-dlp/yt-dlp-nightly-builds
[debug] Restarting: C:\bin\yt-dlp.exe -vU --write-description https://www.facebook.com/reel/1184723189500416
[debug] Command-line config: ['-vU', '--write-description', 'https://www.facebook.com/reel/1184723189500416']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.02.232855 from yt-dlp/yt-dlp-nightly-builds [e8e6a982a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.02.232855 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.02.232855 from yt-dlp/yt-dlp-nightly-builds)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1184723189500416
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1184723189500416&_rdr
[facebook] 1184723189500416: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1184723189500416: Downloading 1 format(s): 1675931759859977v+527464266312477a
[info] Writing video description to: 15K views · 995 reactions ｜ Can't say it enough...YOU GUYS are doing amazing things for Peter. Therapy starts September 7th and goes until September 27th.The fundraiser ends tonight at 12am EST and all future purchases⧸donations will be set aside for his Spring session.We love you and are incredibly grateful for your support and love for Peter and our family. ｜ Perfect Peter ｜ Perfect Peter · Original audio [1184723189500416].description
ERROR: Cannot write video description file 15K views · 995 reactions ｜ Can't say it enough...YOU GUYS are doing amazing things for Peter. Therapy starts September 7th and goes until September 27th.The fundraiser ends tonight at 12am EST and all future purchases⧸donations will be set aside for his Spring session.We love you and are incredibly grateful for your support and love for Peter and our family. ｜ Perfect Peter ｜ Perfect Peter · Original audio [1184723189500416].description
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4303, in _write_description
FileNotFoundError: [Errno 2] No such file or directory: "15K views · 995 reactions ｜ Can't say it enough...YOU GUYS are doing amazing things for Peter. Therapy starts September 7th and goes until September 27th.The fundraiser ends tonight at 12am EST and all future purchases⧸donations will be set aside for his Spring session.We love you and are incredibly grateful for your support and love for Peter and our family. ｜ Perfect Peter ｜ Perfect Peter · Original audio [1184723189500416].description"
```

**Comment by barsnick** [comment]
> ```shell
> [info] Writing video description to: 15K views · 995 reactions ｜ Can't say it enough...YOU GUYS are doing amazing things for Peter. Therapy starts September 7th and goes until September 27th.The fundraiser ends tonight at 12am EST and all future purchases⧸donations will be set aside for his Spring session.We love you and are incredibly grateful for your support and love for Peter and our family. ｜ Perfect Peter ｜ Perfect Peter · Original audio [1184723189500416].description
> ERROR: Cannot write video description file 15K views · 995 reactions ｜ Can't say it enough...YOU GUYS are doing amazing things for Peter. Therapy starts September 7th and goes until September 27th.The fundraiser ends tonight at 12am EST and all future purchases⧸donations will be set aside for his Spring session.We love you and are incredibly grateful for your support and love for Peter and our family. ｜ Perfect Peter ｜ Perfect Peter · Original audio [1184723189500416].description
> Traceback (most recent call last):
>   File "yt_dlp\YoutubeDL.py", line 4303, in _write_description
> FileNotFoundError: [Errno 2] No such file or directory: "15K views · 995 reactions ｜ Can't say it enough...YOU GUYS are doing amazing things for Peter. Therapy starts September 7th and goes until September 27th.The fundraiser ends tonight at 12am EST and all future purchases⧸donations will be set aside for his Spring session.We love you and are incredibly grateful for your support and love for Peter and our family. ｜ Perfect Peter ｜ Perfect Peter · Original audio [1184723189500416].description"
> ```

I think that's Windows's error when the file name is too long. Try adding `-o '%(title).200B.%(ext)s'`.

Nevertheless, once the description is actually downloaded, its content is indeed truncated.
