### ISSUE TITLE
EOF occurred in violation of protocol (_ssl.c:1131

### ISSUE THREAD

**Issue by arukateru** [yt-dlp/yt-dlp#10943]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When using https proxy, even when using the "no check certificates" flag, there is still ssl error

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Alcatel\Desktop\NCS>yt-dlp -vU --proxy https://168.158.228.144 --no-check-certificates -f bestaudio --extract-audio --audio-format opus --audio-quality 0 --yes-playlist "https://www.youtube.com/playlist?list=PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW"
[debug] Command-line config: ['-vU', '--proxy', 'https://168.158.228.144', '--no-check-certificates', '-f', 'bestaudio', '--extract-audio', '--audio-format', 'opus', '--audio-quality', '0', '--yes-playlist', 'https://www.youtube.com/playlist?list=PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'all': 'https://168.158.228.144'}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW
[youtube:tab] PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW: Downloading webpage
WARNING: [youtube:tab] ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). Retrying (1/3)...
[youtube:tab] PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW: Downloading webpage
WARNING: [youtube:tab] ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). Retrying (2/3)...
[youtube:tab] PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW: Downloading webpage
WARNING: [youtube:tab] ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). Retrying (3/3)...
[youtube:tab] PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW: Downloading webpage
WARNING: [youtube:tab] Unable to download webpage: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))) (caused by ProxyError("('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[youtube:tab] PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW: Downloading API parameters API JSON
WARNING: [youtube:tab] ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). Retrying (1/3)...
[youtube:tab] PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW: Downloading API parameters API JSON
WARNING: [youtube:tab] ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). Retrying (2/3)...
[youtube:tab] PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW: Downloading API parameters API JSON
WARNING: [youtube:tab] ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))). Retrying (3/3)...
[youtube:tab] PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW: Downloading API parameters API JSON
ERROR: [youtube:tab] PLv1Kobfrv9Wtx2X6OG6pzg4ZEqNfsgCyW: Unable to download API page: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))) (caused by ProxyError("('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\youtube.py", line 4817, in wrapper
  File "yt_dlp\extractor\youtube.py", line 6751, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 5540, in _extract_data
  File "yt_dlp\extractor\youtube.py", line 5545, in _extract_tab_endpoint
  File "yt_dlp\extractor\youtube.py", line 1022, in _extract_response
  File "yt_dlp\utils\_utils.py", line 5206, in __iter__
  File "yt_dlp\extractor\common.py", line 3869, in _error_or_warning
  File "yt_dlp\utils\_utils.py", line 5214, in report_retry
  File "yt_dlp\extractor\youtube.py", line 1012, in _extract_response
  File "yt_dlp\extractor\youtube.py", line 656, in _call_api
  File "yt_dlp\extractor\common.py", line 1139, in download_content
  File "yt_dlp\extractor\common.py", line 1099, in download_handle
  File "yt_dlp\extractor\common.py", line 960, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 909, in _request_webpage


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 449, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 775, in urlopen
  File "urllib3\connectionpool.py", line 1044, in _prepare_proxy
  File "urllib3\connection.py", line 624, in connect
  File "urllib3\connection.py", line 698, in _connect_tls_proxy
  File "urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 328, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 706, in send
requests.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 896, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 349, in _send
yt_dlp.networking.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
```

**Comment by coletdjnz** [comment]
Issue with your proxy
