### ISSUE TITLE
Sen ISS livecam

### ISSUE THREAD

**Issue by Ulmo** [yt-dlp/yt-dlp#10951]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

https://www.sen.com/video/2c22cfd2-d12e-4bb6-a7f7-0b89961a0d9f

### Provide a description that is worded well enough to be understood

This is a public livestream link they released that had interest to the public.  It was a test stream that they found they could give out publicly.  They will go live for production public use sometime this month according to them.

I downloaded and built master but it still outputs stable 2024-08-06 in the debug output below.  I hope that's master.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.sen.com/video/2c22cfd2-d12e-4bb6-a7f7-0b89961a0d9f']
[debug] User config "/home/ulmo/yt-dlp.conf": ['--ffmpeg-location', '/for/my/info/yt-dlp/ffmpeg-binary-get/ffmpeg-master-latest-linux64-gpl/bin']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-1018-lowlatency-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg N-112327-g9078dc0c52-20231005 (setts), ffprobe N-112327-g9078dc0c52-20231005, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.1.0, websockets-12.0, xattr-0.10.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.sen.com/video/2c22cfd2-d12e-4bb6-a7f7-0b89961a0d9f
[generic] 2c22cfd2-d12e-4bb6-a7f7-0b89961a0d9f: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 2c22cfd2-d12e-4bb6-a7f7-0b89961a0d9f: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.sen.com/video/2c22cfd2-d12e-4bb6-a7f7-0b89961a0d9f
Traceback (most recent call last):
  File "/home/ulmo/src/yt-dlp/20240907/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ulmo/src/yt-dlp/20240907/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/home/ulmo/src/yt-dlp/20240907/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/ulmo/src/yt-dlp/20240907/yt-dlp/yt-dlp/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.sen.com/video/2c22cfd2-d12e-4bb6-a7f7-0b89961a0d9f
```

**Comment by Ulmo** [comment]
Here is their public announcement of this:

https://x.com/sen/status/1832423224639918526
https://x.com/sen/status/1832443570642649539
