### ISSUE TITLE
ReverbNation broken: fails with "Unsupported URL"

### ISSUE THREAD

**Issue by H2Swine** [yt-dlp/yt-dlp#10969]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

ReverbNation is in the list at https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md . Trying an artist who has a "Download Free MP3" button (that works with no login), and it still doesn't work. 

Initially tried with `-F`. And `-vU -F`  yields the same output except of course the "Command-line config".

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.reverbnation.com/morganandersson']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds [d1c4d88b2] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 7.0.2-essentials_build-www.gyan.dev (setts), ffprobe 7.0.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.reverbnation.com/morganandersson
[generic] morganandersson: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] morganandersson: Extracting information
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[generic] Extracting URL: https://www.reverbnation.com/widget_code/html_widget/artist_1078497?widget_id=55&client_id=t23vwef5f&pwc[autoplay]=1&pwc[included_songs]=1&context_type=playlist&id_unique=artist_1078497
[generic] artist_1078497?widget_id=55&client_id=t23vwef5f&pwc[autoplay]=1&pwc[included_songs]=1&context_type=playlist&id_unique=artist_1078497: Downloading webpage
[redirect] Following redirect to https://www.reverbnation.com/widget_code/html_widget/artist_1078497?widget_id=55&client_id=t23vwef5f&pwc%5Bautoplay%5D=1&pwc%5Bincluded_songs%5D=1&context_type=playlist&id_unique=artist_1078497
[generic] Extracting URL: https://www.reverbnation.com/widget_code/html_widget/artist_1078497?widget_id=55&client_id=t23vwef5f&pwc%5Bautoplay%5D=1&pwc%5Bincluded_songs%5D=1&context_type=playlist&id_unique=artist_1078497
[generic] artist_1078497?widget_id=55&client_id=t23vwef5f&pwc[autoplay]=1&pwc[included_songs]=1&context_type=playlist&id_unique=artist_1078497: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] artist_1078497?widget_id=55&client_id=t23vwef5f&pwc[autoplay]=1&pwc[included_songs]=1&context_type=playlist&id_unique=artist_1078497: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.reverbnation.com/widget_code/html_widget/artist_1078497?widget_id=55&client_id=t23vwef5f&pwc%5Bautoplay%5D=1&pwc%5Bincluded_songs%5D=1&context_type=playlist&id_unique=artist_1078497
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.reverbnation.com/widget_code/html_widget/artist_1078497?widget_id=55&client_id=t23vwef5f&pwc%5Bautoplay%5D=1&pwc%5Bincluded_songs%5D=1&context_type=playlist&id_unique=artist_1078497
```

**Comment by grqz** [comment]
artists' page/playlist arent supported yet. this should be a site-enhancement request.
if you want to extract them manually, go to the 'view song' page and extract that URL(remember to quote the URL)
like this:
```
yt-dlp.exe -vUF "https://www.reverbnation.com/morganandersson/song/25994670-ngot-nytt-av-gammalt-och-bltt?source=artistProfile"
```

**Comment by H2Swine** [comment]
> this should be a site-enhancement request.

Feel free to alter the labels. (Or teach me how to.)
