### ISSUE TITLE
Add support for Bluesky.app

### ISSUE THREAD

**Issue by HokoraYinphineMPP** [yt-dlp/yt-dlp#10987]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

US

### Example URLs

- Single Video: yt-dlp https://bsky.app/profile/bsky.app/post/3l3vgf77uco2g

### Provide a description that is worded well enough to be understood

Unsupported URL. As of Sep 11, 2024, Bluesky has started rolling out video support on their site. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://bsky.app/profile/bsky.app/post/3l3vgf77uco2g']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Python 3.12.5 (CPython x86_64 64bit) - Linux-6.10.9-arch1-2-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-1.26.20, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://bsky.app/profile/bsky.app/post/3l3vgf77uco2g
[generic] 3l3vgf77uco2g: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 3l3vgf77uco2g: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://bsky.app/profile/bsky.app/post/3l3vgf77uco2g
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://bsky.app/profile/bsky.app/post/3l3vgf77uco2
```

**Comment by grqz** [comment]
>[!NOTE]
> Note for devs: all info is available at `f'https://public.api.bsky.app/xrpc/app.bsky.feed.getPostThread?uri=at%3A%2F%2Fbsky.app%2Fapp.bsky.feed.post%2F{video_id}&depth=0'`
> Example:
```jsonc
{
  "thread": {
    "$type": "app.bsky.feed.defs#threadViewPost",
    "post": {
      "uri": "at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.feed.post/3l3wdzzedvv2y",
      "cid": "bafyreienxdczt4j4ml3gnt36cfhpy6cdfefxyvx7lmrrcryppyysn2yybi",
      "author": {
        "did": "did:plc:z72i7hdynmk6r22z27h6tvur",
        "handle": "bsky.app",
        "displayName": "Bluesky",
        "avatar": "https://cdn.bsky.app/img/avatar/plain/did:plc:z72i7hdynmk6r22z27h6tvur/bafkreihagr2cmvl2jt4mgx3sppwe2it3fwolkrbtjrhcnwjk4jdijhsoze@jpeg",
        "associated": {
          "chat": {
            "allowIncoming": "none"
          }
        },
        "labels": [],
        "createdAt": "2023-04-12T04:53:57.057Z"
      },
      "record": {
        "$type": "app.bsky.feed.post",
        "createdAt": "2024-09-12T02:02:32.974Z",
        "embed": {
          "$type": "app.bsky.embed.video",
          "alt": "Debbie Ryan giving an interview. \"I want to make history. And that's what this is.\"",
          "aspectRatio": {
            "height": 478,
            "width": 884
          },
          "video": {
            "$type": "blob",
            "ref": {
              "$link": "bafkreif2firztfyxoz6krysgmtzhlf5f66e5ettp5rdzbav3zmlzcfk66q"
            },
            "mimeType": "video/mp4",
            "size": 772495
          }
        },
        "langs": [
          "en",
          "pt"
        ],
        "text": "Bluesky, you're setting ANOTHER all-time record for activity here! Novo recorde histórico! 🤯 \n\nRight now, we're already 10% higher than our all-time peak!"
      },
      "embed": {
        "$type": "app.bsky.embed.video#view",
        "cid": "bafkreif2firztfyxoz6krysgmtzhlf5f66e5ettp5rdzbav3zmlzcfk66q",
        "playlist": "https://video.bsky.app/watch/did%3Aplc%3Az72i7hdynmk6r22z27h6tvur/bafkreif2firztfyxoz6krysgmtzhlf5f66e5ettp5rdzbav3zmlzcfk66q/playlist.m3u8",
        "thumbnail": "https://video.bsky.app/watch/did%3Aplc%3Az72i7hdynmk6r22z27h6tvur/bafkreif2firztfyxoz6krysgmtzhlf5f66e5ettp5rdzbav3zmlzcfk66q/thumbnail.jpg",
        "alt": "Debbie Ryan giving an interview. \"I want to make history. And that's what this is.\"",
        "aspectRatio": {
          "height": 478,
          "width": 884
        }
      },
      "replyCount": 543,
      "repostCount": 932,
      "likeCount": 18625,
      "quoteCount": 422,
      "indexedAt": "2024-09-12T02:02:32.974Z",
      "labels": []
    }
  }
}
```
