### ISSUE TITLE
[BiliBili.tv] HTTP Error 403: Forbidden error when download ass subtitle

### ISSUE THREAD

**Issue by Khaoklong51** [yt-dlp/yt-dlp#10996]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Thailand

### Provide a description that is worded well enough to be understood

When trying to download subtitle with `--sub-format ass` the error HTTP Error 403: Forbidden is present the default one which is srt is working fine without issue. The video and audio download is still working fine.
The download subtitle link from degub log can download when open in browser

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-subs', '--embed-sub', '-o', '%(title)s.%(ext)s', '--sub-lang', 'th', '--sub-format', 'ass', 'https://www.bilibili.tv/th/play/2111552/13351814?bstar_from=bstar-web.pgc-video-detail.episode.all']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds [d1c4d88b2] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116993-gf7cf49dbdd-ga15d2fdfd9 (fdk,setts), ffprobe N-116993-gf7cf49dbdd-ga15d2fdfd9, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds)
[BiliIntl] Extracting URL: https://www.bilibili.tv/th/play/2111552/13351814?bstar_from=bstar-web.pgc-video-detail.episode.all
[BiliIntl] 13351814: Downloading JSON metadata
[BiliIntl] 13351814: Downloading webpage
[BiliIntl] 13351814: Downloading JSON metadata
[BiliIntl] 13351814: Downloading video formats
[BiliIntl] 13351814: Downloading subtitles list
[BiliIntl] 13351814: Downloading subtitles for 中文（简体） (zh-Hans)
[BiliIntl] 13351814: Downloading subtitles for English (en)
[BiliIntl] 13351814: Downloading subtitles for ภาษาไทย (th)
[BiliIntl] 13351814: Downloading subtitles for Bahasa Indonesia (id)
[info] 13351814: Downloading subtitles: th
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 13351814: Downloading 1 format(s): 10+2
[info] Writing video subtitles to: E2 - So-called Childhood Pals？.th.ass
[debug] Invoking http downloader on "https://p0.hdslb.com/bfs/intl/subtitle/27d386aef096f48819dd170c6887e3c3.ass"
ERROR: Unable to download video subtitles for 'th': HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4354, in _write_subtitles
  File "yt_dlp\YoutubeDL.py", line 3203, in dl
  File "yt_dlp\downloader\common.py", line 466, in download
  File "yt_dlp\downloader\http.py", line 369, in real_download
  File "yt_dlp\downloader\http.py", line 120, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 3015, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 179, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3271, in process_info
  File "yt_dlp\YoutubeDL.py", line 4362, in _write_subtitles
yt_dlp.utils.DownloadError: Unable to download video subtitles for 'th': HTTP Error 403: Forbidden
```

**Comment by grqz** [comment]
>[!NOTE]
> [geo-blocked]
