### ISSUE TITLE
[orf.at] Unsupported URL and using generic extractor instead of orf.py

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#11014]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

all countries

### Provide a description that is worded well enough to be understood

Hello guys. Got two links for test:
https://oe1.orf.at/programm/20240916/769302/Playgrounds
https://sound.orf.at/collection/2/72427/rattle-dirigiert-6-mahler

Both fail to download. yt-dlp will switch to generic extractor after that giving unsupported url error. 

however audio files can be located manually by this links:
https://loopstream01.apa.at/?channel=oe1&shoutcast=0&player=radiothek_item_v1&referer=oe1.orf.at&id=2024-09-16_1405_tl_51_7DaysMon20_2491805.mp3&_=1726498267358

https://loopstream01.apa.at/playlist.m3u8?channel=oe1&id=2024-09-15_1103_tl_51_7DaysSun14_2491007.mp3&offset=0&offsetende=5271949&shoutcast=0&player=sound_v1&referer=sound.orf.at&userid=9da0d70b-9d2f-415d-9607-38bc356523d8&cb=1726499239020

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -Uv -F "https://sound.orf.at/collection/2/72427/rattle-dirigiert-6-mahler"
/Library/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file './yt-dlp': [Errno 1] Operation not permitted
sy@SYs-MacBook-Air yt-dlp % ./yt-dlp -vU -F "https://sound.orf.at/collection/2/72427/rattle-dirigiert-6-mahler"
[debug] Command-line config: ['-Uv', '-F', 'https://sound.orf.at/collection/2/72427/rattle-dirigiert-6-mahler']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.12.2 (CPython arm64 64bit) - macOS-14.6.1-arm64-arm-64bit (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://sound.orf.at/collection/2/72427/rattle-dirigiert-6-mahler
[generic] rattle-dirigiert-6-mahler: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] rattle-dirigiert-6-mahler: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://sound.orf.at/collection/2/72427/rattle-dirigiert-6-mahler
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://sound.orf.at/collection/2/72427/rattle-dirigiert-6-mahler
```

**Comment by seproDev** [comment]
sound.orf.at is a duplicate of https://github.com/yt-dlp/yt-dlp/issues/9581
For oe1.orf.at it looks like the regex needs to be expanded
```diff
diff --git a/yt_dlp/extractor/orf.py b/yt_dlp/extractor/orf.py
index 9c37a54d6..f156e96fb 100644
--- a/yt_dlp/extractor/orf.py
+++ b/yt_dlp/extractor/orf.py
@@ -44,7 +44,7 @@ class ORFRadioIE(InfoExtractor):
 
     _VALID_URL = rf'''(?x)
         https?://(?:
-            (?P<station>{_STATION_RE})\.orf\.at/player|
+            (?P<station>{_STATION_RE})\.orf\.at/(?:player|programm)|
             radiothek\.orf\.at/(?P<station2>{_STATION_RE})
         )/(?P<date>[0-9]+)/(?P<show>\w+)'''
 ```

**Comment by dirkf** [comment]
In the upstream version of the extractor, the sound.orf.at URL is already handled, and the oe1.orf.at/programm URL works after changing `/player/' in the URL pattern to `/(?:player|programm)/`. As a work-around you can use  https://oe1.orf.at/player/20240916/769302/Playgrounds which appears also to work with _yt-dlp_. 

Where are links like oe1.orf.at/programm found?
