### ISSUE TITLE
Add support for ya.ru domain in yandexvideo extractor

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [yt-dlp/yt-dlp#11025]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://ya.ru/video/preview/12690133459198768623

### Provide a description that is worded well enough to be understood

`ya.ru` domain is not supported in yandexvideo extractor. If I replace `ya.ru` with `yandex.ru` it works.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://ya.ru/video/preview/12690133459198768623']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.14.232748 from yt-dlp/yt-dlp-nightly-builds [a06bb5867] (win_exe)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.14.232748 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.14.232748 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://ya.ru/video/preview/12690133459198768623
[generic] 12690133459198768623: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 12690133459198768623: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://ya.ru/video/preview/12690133459198768623
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://ya.ru/video/preview/12690133459198768623
```

**Comment by dirkf** [comment]
Relaxing the URL pattern for `YandexVideoPreviewIE` like this
```diff
-    _VALID_URL = r'https?://(?:www\.)?yandex\.\w{2,3}(?:\.(?:am|ge|il|tr))?/video/preview(?:/?\?.*?filmId=|/)(?P<id>\d+)'
+    _VALID_URL = r'https?://(?:\w+\.)?ya(?:ndex)?\.\w{2,3}(?:\.(?:am|ge|il|tr))?/video/preview(?:/?\?.*?filmId=|/)(?P<id>\d+)'
```
catches the problem URL and also URLs with an initial domain other than `www`, eg, https://gs.yandex.com.tr/video/preview/7551877453777151169?from_type=vast&text=SHANT%2BTV%2BArmenia.

**Comment by msramalho** [comment]
any issue with adding this patch? this issue is simple and has been open for a while. Happy to open a PR if that helps!

**Comment by bashonly** [comment]
@msramalho go ahead

**Comment by msramalho** [comment]
@bashonly can you give me an example of how to call only the `'only_matching': True` test cases? 

`hatch test YandexVideo`, `hatch test YandexVideo_all` and similar are only capturing the download tests which fail and I really just want to run the only_matching as that's where I'm adding new cases.

EDIT: minor success with `pytest -Werror  --tb=short  -p no:randomly -m 'not download' test/test_all_urls.py` but it still needs to run all URL matching tests

**Comment by bashonly** [comment]
@msramalho `hatch test test/test_all_urls.py`

**Comment by msramalho** [comment]
yes, thanks, maybe worth adding this to the Contributing guide?

**Comment by msramalho** [comment]
@bashonly PR ready https://github.com/yt-dlp/yt-dlp/pull/13645
