### ISSUE TITLE
[ADN] Unable to log in: HTTP Error 403: Forbidden / Requested format is not available. Use --list-formats for a list of available formats

### ISSUE THREAD

**Issue by TheWizard-maker** [yt-dlp/yt-dlp#11038]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

france

### Provide a description that is worded well enough to be understood

Hello,

I am living in France. I am facing issues to download from ADN

here is th list of format available for the video i want to download :

[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', '-F', 'https://animationdigitalnetwork.com/video/647-dragon-quest-the-adventure-of-dai-fly-daibouken/12718-episode-1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen cp1252 (No VT)
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id

Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[ADN] Logging in
[ADN] Extracting URL: https://animationdigitalnetwork.com/video/647-dragon-quest-the-adventure-of-dai-fly-daibouken/12718-episode-1
[ADN] 12718: Downloading player config JSON metadata
[ADN] 12718: Downloading access token
[ADN] 12718: Downloading links JSON metadata
[ADN] 12718: Downloading vf mobile JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vf sd JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vf hd JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vf fhd JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vf auto JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vostf mobile JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vostf sd JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vostf hd JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vostf fhd JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vostf auto JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading additional video metadata
[info] Available formats for 12718:
ID           EXT RESOLUTION |    FILESIZE   TBR PROTO | VCODEC      ACODEC    MORE INFO
---------------------------------------------------------------------------------------
vostf-416    mp4 640x360    | ~  71.51MiB  416k m3u8  | avc1.4d001f mp4a.40.2
vf-768       mp4 640x360    | ~ 132.16MiB  769k m3u8  | avc1.4d001f mp4a.40.2 [fr]
vf-696-0     mp4 853x480    | ~ 119.64MiB  696k m3u8  | avc1.640028 mp4a.40.2 [fr]
vf-696-1     mp4 853x480    | ~ 119.64MiB  696k m3u8  | avc1.640028 mp4a.40.2 [fr]
vostf-696-0  mp4 853x480    | ~ 119.64MiB  696k m3u8  | avc1.640028 mp4a.40.2
vostf-696-1  mp4 853x480    | ~ 119.64MiB  696k m3u8  | avc1.640028 mp4a.40.2
vf-3129-0    mp4 1280x720   | ~ 537.92MiB 3129k m3u8  | avc1.640028 mp4a.40.2 [fr]
vf-3129-1    mp4 1280x720   | ~ 537.92MiB 3129k m3u8  | avc1.640028 mp4a.40.2 [fr]
vostf-3129-0 mp4 1280x720   | ~ 537.92MiB 3129k m3u8  | avc1.640028 mp4a.40.2
vostf-3129-1 mp4 1280x720   | ~ 537.92MiB 3129k m3u8  | avc1.640028 mp4a.40.2
vf-5829-0    mp4 1920x1080  | ~1002.04MiB 5829k m3u8  | avc1.640029 mp4a.40.2 [fr]
vf-5829-1    mp4 1920x1080  | ~1002.04MiB 5829k m3u8  | avc1.640029 mp4a.40.2 [fr]
vostf-5829-0 mp4 1920x1080  | ~1002.04MiB 5829k m3u8  | avc1.640029 mp4a.40.2
vostf-5829-1 mp4 1920x1080  | ~1002.04MiB 5829k m3u8  | avc1.640029 mp4a.40.2

here is when i try donwload : 
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'vostf-5829-1', '--video-multistreams', '--audio-multistreams', '--sub-langs', 'all', '--embed-subs', '--embed-chapters', '--embed-metadata', '--remux-video', 'mkv', '--ffmpeg-location', 'E:\\yt-dlp\\ffmpeg-master-latest-win64-gpl\\bin\\ffmpeg.exe', '-o', 'E:\\ADN\\%(title)s vostf.%(ext)s', 'https://animationdigitalnetwork.com/video/647-dragon-quest-the-adventure-of-dai-fly-daibouken/12718-episode-1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen cp1252 (No VT)
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-117043-g8707c8660d-20240915 (setts), ffprobe N-117043-g8707c8660d-20240915
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
WARNING: [ADN] Unable to log in: HTTP Error 403: Forbidden
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [ADN] 12718: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2977, in process_video_result
yt_dlp.utils.ExtractorError: [ADN] 12718: Requested format is not available. Use --list-formats for a list of available formats

Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[ADN] Logging in
[ADN] Extracting URL: https://animationdigitalnetwork.com/video/647-dragon-quest-the-adventure-of-dai-fly-daibouken/12718-episode-1
[ADN] 12718: Downloading player config JSON metadata
[ADN] 12718: Downloading access token
[ADN] 12718: Downloading links JSON metadata
[ADN] 12718: Downloading vostf mobile JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vostf sd JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading additional video metadata
[ADN] 12718: Downloading subtitles location
[ADN] 12718: Downloading subtitles data
[info] 12718: Downloading subtitles: fr

It seems try to me because if i try several time. 9 times it fails et the 10th time it can work and i can download

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'vostf-5829-1', '--video-multistreams', '--audio-multistreams', '--sub-langs', 'all', '--embed-subs', '--embed-chapters', '--embed-metadata', '--remux-video', 'mkv', '--ffmpeg-location', 'E:\\yt-dlp\\ffmpeg-master-latest-win64-gpl\\bin\\ffmpeg.exe', '-o', 'E:\\ADN\\%(title)s vostf.%(ext)s', 'https://animationdigitalnetwork.com/video/647-dragon-quest-the-adventure-of-dai-fly-daibouken/12718-episode-1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen cp1252 (No VT)
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-117043-g8707c8660d-20240915 (setts), ffprobe N-117043-g8707c8660d-20240915
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
WARNING: [ADN] Unable to log in: HTTP Error 403: Forbidden
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [ADN] 12718: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2977, in process_video_result
yt_dlp.utils.ExtractorError: [ADN] 12718: Requested format is not available. Use --list-formats for a list of available formats


Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[ADN] Logging in
[ADN] Extracting URL: https://animationdigitalnetwork.com/video/647-dragon-quest-the-adventure-of-dai-fly-daibouken/12718-episode-1
[ADN] 12718: Downloading player config JSON metadata
[ADN] 12718: Downloading access token
[ADN] 12718: Downloading links JSON metadata
[ADN] 12718: Downloading vostf mobile JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading vostf sd JSON metadata
[ADN] 12718: Downloading m3u8 information
[ADN] 12718: Downloading additional video metadata
[ADN] 12718: Downloading subtitles location
[ADN] 12718: Downloading subtitles data
[info] 12718: Downloading subtitles: fr
```

**Comment by TheWizard-maker** [comment]
@bashonly I can provide my ADN account. Tell me how I can contact you in private

**Comment by clickbydigital** [comment]
> ADN account

@TheWizard-maker i'm getting error of Sign in to confirm, You are not a Bot when called the API through Server, any way to trespass this  and get the Streaming url.
