### ISSUE TITLE
Error Downloading Video from ARD Mediathek

### ISSUE THREAD

**Issue by nanderer** [yt-dlp/yt-dlp#11040]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

germany

### Provide a description that is worded well enough to be understood

I would like to download a video from ARD Mediathek but i get a 404 error when i use yt-dlp, but i i can play it fine using FIrefox:

https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8
![grafik](https://github.com/user-attachments/assets/fa443d2a-725f-4377-8d25-19bcc99c1b11)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Owner\Videos>yt-dlp https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[ARDBetaMediathek] Extracting URL: https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3...kLVNFTkRVTkdTVklERU8
[ARDBetaMediathek] tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste: Downloading JSON metadata
ERROR: [ARDBetaMediathek] Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\Users\Owner\Videos>yt-dlp https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[ARDBetaMediathek] Extracting URL: https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3...kLVNFTkRVTkdTVklERU8
[ARDBetaMediathek] tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste: Downloading JSON metadata
ERROR: [ARDBetaMediathek] Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\Users\Owner\Videos>yt-dlp --verbose https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8
[debug] Command-line config: ['--verbose', 'https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8']
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.7.9 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg N-117081-g0d5b68c27c-20240919 (setts), ffprobe N-117081-g0d5b68c27c-20240919
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.31.0, sqlite3-3.31.1, urllib3-2.0.7, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Using fake IP 53.75.212.90 (DE) as X-Forwarded-For
[ARDBetaMediathek] Extracting URL: https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8
[ARDBetaMediathek] tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste: Downloading JSON metadata
ERROR: [ARDBetaMediathek] Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\ard.py", line 634, in _real_extract
    'Content-Type': 'application/json'
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 1035, in download_handle
    data=data, headers=headers, query=query, expected_status=expected_status)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\YoutubeDL.py", line 4052, in urlopen
    return self._request_director.send(req)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\networking\common.py", line 114, in send
    response = handler.send(request)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\networking\_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\networking\common.py", line 325, in send
    return self._send(request)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\networking\_requests.py", line 341, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\YoutubeDL.py", line 4074, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found


C:\Users\Owner\Videos>yt-dlp -vU https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8
[debug] Command-line config: ['-vU', 'https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8']
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.7.9 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg N-117081-g0d5b68c27c-20240919 (setts), ffprobe N-117081-g0d5b68c27c-20240919
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.31.0, sqlite3-3.31.1, urllib3-2.0.7, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Using fake IP 53.185.33.145 (DE) as X-Forwarded-For
[ARDBetaMediathek] Extracting URL: https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8
[ARDBetaMediathek] tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste: Downloading JSON metadata
ERROR: [ARDBetaMediathek] Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\ard.py", line 634, in _real_extract
    'Content-Type': 'application/json'
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 1035, in download_handle
    data=data, headers=headers, query=query, expected_status=expected_status)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\YoutubeDL.py", line 4052, in urlopen
    return self._request_director.send(req)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\networking\common.py", line 114, in send
    response = handler.send(request)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\networking\_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\networking\common.py", line 325, in send
    return self._send(request)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\networking\_requests.py", line 341, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\extractor\common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\yt_dlp\YoutubeDL.py", line 4074, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found


C:\Users\Owner\Videos>yt-dlp -vU https://www.ardmediathek.de/video/tagesschau/tagesschau-17-00-uhr-19-09-2024/das-erste/Y3JpZDovL3RhZ2Vzc2NoYXUuZGUvNjUwMGYzZmItZGM0YS00ZmY4LTg2OTMtYjJlN2JhZTU5ZmJkLVNFTkRVTkdTVklERU8

C:\Users\Owner\Videos>

C:\Users\Owner\Videos>yt-dlp -U
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above

C:\Users\Owner\Videos>pip update yt-dlp
ERROR: unknown command "update"

C:\Users\Owner\Videos>pip install -update yt-dlp

Usage:
  C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install [options] [-e] <vcs project url> ...
  C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install [options] [-e] <local project path> ...
  C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install [options] <archive url/path> ...

no such option: -u

C:\Users\Owner\Videos>pip install -u yt-dlp

Usage:
  C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install [options] [-e] <vcs project url> ...
  C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install [options] [-e] <local project path> ...
  C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install [options] <archive url/path> ...

no such option: -u

C:\Users\Owner\Videos>pip install yt-dlp
Requirement already satisfied: yt-dlp in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (2023.11.16)
Requirement already satisfied: mutagen in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from yt-dlp) (1.47.0)
Requirement already satisfied: pycryptodomex in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from yt-dlp) (3.20.0)
Requirement already satisfied: websockets in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from yt-dlp) (11.0.3)
Requirement already satisfied: certifi in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from yt-dlp) (2024.8.30)
Requirement already satisfied: requests<3,>=2.31.0 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from yt-dlp) (2.31.0)
Requirement already satisfied: urllib3<3,>=1.26.17 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from yt-dlp) (2.0.7)
Requirement already satisfied: brotli in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from yt-dlp) (1.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests<3,>=2.31.0->yt-dlp) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests<3,>=2.31.0->yt-dlp) (3.10)

C:\Users\Owner\Videos>
```

**Comment by bashonly** [comment]
you're using an old version of yt-dlp
