### ISSUE TITLE
SponsorBlock unavailable: program exits

### ISSUE THREAD

**Issue by jackloomen** [yt-dlp/yt-dlp#1105]
When using "--sponsorblock-mark all"  if the following error occurs the program exits rather than proceed with download.

```
[youtube] xxxxxxxxxxxxxx: Downloading webpage
[youtube] xxxxxxxxxxxxxx: Downloading android player API JSON
ERROR: Error communicating with SponsorBlock API - HTTP Error 502: Bad Gateway
```

**Comment by pukkandan** [comment]
### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

I am not going to close this since I was able to identify the issue even with the lack of information. However, next time, follow the issue template

**Comment by maaldheefee** [comment]
```
[debug] Command-line config: ['-v', '--no-config', '--sponsorblock-mark', 'all', 'https://www.youtube.com/watch?v=C0DPdy98e4c']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.25
[debug] Python version 3.9.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg n4.4-80-gbf87bdd3f6-20210811, ffprobe n4.4-80-gbf87bdd3f6-20210811, phantomjs 2.1.1, rtmpdump 2.3
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=C0DPdy98e4c
[youtube] C0DPdy98e4c: Downloading webpage
[youtube] C0DPdy98e4c: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[debug] Unable to connect to thumbnail 41 URL "https://i.ytimg.com/vi_webp/C0DPdy98e4c/maxresdefault.webp" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 40
[debug] Unable to connect to thumbnail 40 URL "https://i.ytimg.com/vi/C0DPdy98e4c/maxresdefault.jpg" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 39
[debug] Unable to connect to thumbnail 39 URL "https://i.ytimg.com/vi_webp/C0DPdy98e4c/hq720.webp" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 38
[debug] Unable to connect to thumbnail 38 URL "https://i.ytimg.com/vi/C0DPdy98e4c/hq720.jpg" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 37
[debug] Unable to connect to thumbnail 37 URL "https://i.ytimg.com/vi_webp/C0DPdy98e4c/sddefault.webp" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 36
[debug] Unable to connect to thumbnail 36 URL "https://i.ytimg.com/vi/C0DPdy98e4c/sddefault.jpg" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 35
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/754e?service=YouTube&categories=%5B%22intro%22%2C+%22sponsor%22%2C+%22preview%22%2C+%22outro%22%2C+%22interaction%22%2C+%22music_offtopic%22%2C+%22selfpromo%22%5D
ERROR: Error communicating with SponsorBlock API - HTTP Error 502: Bad Gateway
Traceback (most recent call last):
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\postprocessor\sponsorblock.py", line 90, in _get_json
    rsp = self._downloader.urlopen(sanitized_Request(url))
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3256, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1227, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1265, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1315, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2272, in process_video_result
    info_dict, _ = self.pre_process(info_dict)
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3043, in pre_process
    info = self.run_pp(pp, info)
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2996, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\postprocessor\sponsorblock.py", line 36, in run
    info['sponsorblock_chapters'] = self._get_sponsor_chapters(info, info['duration'])
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\postprocessor\sponsorblock.py", line 40, in _get_sponsor_chapters
    segments = self._get_sponsor_segments(info['id'], self.EXTRACTORS[info['extractor_key']])
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\postprocessor\sponsorblock.py", line 82, in _get_sponsor_segments
    for d in self._get_json(url):
  File "c:\users\hassaan\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\postprocessor\sponsorblock.py", line 94, in _get_json
    raise PostProcessingError(f'Error communicating with SponsorBlock API - {e}')
yt_dlp.utils.PostProcessingError: Error communicating with SponsorBlock API - HTTP Error 502: Bad Gateway

```
