### ISSUE TITLE
can't download a membership only video

### ISSUE THREAD

**Issue by iswjy0801** [yt-dlp/yt-dlp#11088]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Philippines

### Provide a description that is worded well enough to be understood

i hope someone can help. i can't download this membership-locked video. i have the membership and i can watch it. but i can't download it using yt-dlp. it's fine with other videos that is not membership-locked.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://weverse.io/redvelvet/live/0-149700869']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116785-ge758b24396-20240828 (setts), ffprobe N-116785-ge758b24396-20240828
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[Weverse] Checking username
[Weverse] Logging in
[Weverse] Extracting URL: https://weverse.io/redvelvet/live/0-149700869
[Weverse] 0-149700869: Downloading API JSON
[Weverse] 0-149700869: Downloading VOD API key
[Weverse] 0-149700869: Downloading VOD JSON
ERROR: [Weverse] 0-149700869: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2847, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1123, in raise_no_formats
yt_dlp.utils.ExtractorError: [Weverse] 0-149700869: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
I could take a look if you're willing to share your account credentials:

Contact me on [discord](https://discord.gg/H5MNcFW63r), username `bashonly`

or via email, `bashonly ( a t ) proton mail [ d o t ] com`

**Comment by iswjy0801** [comment]
thank you! this is my first time posting here so i'm kind of not comfortable in sharing my account. sorry 🙏 are there any other ways? i can share that when i play the video, it uses .m4s files. i downloaded those files and tried to concatenate them but i can't convert it to mp4. ffmpeg can't convert .m4s to mp4. i tried. when i tried to download the stream.mpd file, it downloaded but the video contains just vertical lines.

**Comment by bashonly** [comment]
can you play the video in your browser [with DRM disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)?

**Comment by iswjy0801** [comment]
oh. first time to do that. the video doesn't play. it says "a network error has occured".

**Comment by bashonly** [comment]
It's most likely DRM-protected content then, and if that's the case, yt-dlp won't support downloading it.

Note to devs: we should find a way to detect this and raise the appropriate error

**Comment by iswjy0801** [comment]
noted on this. and thank you very much
