### ISSUE TITLE
[Broken] Kaltura video download causes error in the extractor

### ISSUE THREAD

**Issue by xmaayy** [yt-dlp/yt-dlp#1108]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.25** (Happens on latest release and master)
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['https://mediaspace.carleton.ca/media/4705_0_2021/1_5hgwu9bi', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.25
[debug] Python version 3.9.2 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: none
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://mediaspace.carleton.ca/media/4705_0_2021/1_5hgwu9bi
[generic] 1_5hgwu9bi: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1_5hgwu9bi: Downloading webpage
[generic] 1_5hgwu9bi: Extracting information
[download] Downloading playlist: 4705_0_2021 - Carleton University Mediaspace
[generic] playlist 4705_0_2021 - Carleton University Mediaspace: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[debug] [Kaltura] Extracting URL: kaltura:2011531:1_5hgwu9bi#__youtubedl_smuggle=%7B%22source_url%22%3A+%22https%3A%2F%2Fmediaspace.carleton.ca%2Fmedia%2F4705_0_2021%2F1_5hgwu9bi%22%2C+%22service_url%22%3A+%22https%3A%2F%2Fcdnapisec.kaltura.com%22%7D
[Kaltura] 1_5hgwu9bi: Downloading video info JSON
ERROR: 1_5hgwu9bi: An extractor error has occurred. (caused by KeyError('dataUrl')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\yt_dlp\extractor\common.py", line 585, in extract
    ie_result = self._real_extract(url)
  File "c:\python39\lib\site-packages\yt_dlp\extractor\kaltura.py", line 298, in _real_extract
    data_url = info['dataUrl']
KeyError: 'dataUrl'
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\yt_dlp\extractor\common.py", line 585, in extract
    ie_result = self._real_extract(url)
  File "c:\python39\lib\site-packages\yt_dlp\extractor\kaltura.py", line 298, in _real_extract
    data_url = info['dataUrl']
KeyError: 'dataUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1234, in wrapper
    return func(self, *args, **kwargs)
  File "c:\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1259, in __extract_info
    ie_result = ie.extract(url)
  File "c:\python39\lib\site-packages\yt_dlp\extractor\common.py", line 606, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e, video_id=self.get_temp_id(url))
yt_dlp.utils.ExtractorError: 1_5hgwu9bi: An extractor error has occurred. (caused by KeyError('dataUrl')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

[download] Finished downloading playlist: 4705_0_2021 - Carleton University Mediaspace

```

## Description

Nothing much else to say, theres an error in the extractor for Kaltura. The video should be freely available, but if it goes down I can check for a new link.

**Comment by HobbyistDev** [comment]
Version `2022.05.18` makes different error. Here's the log :
```
(python_proj2) ~\yt-dlp>python -m yt_dlp -vs "https://mediaspace.carleton.ca/media/4705_0_2021/1_5hgwu9bi"
[debug] Command-line config: ['-vs', 'https://mediaspace.carleton.ca/media/4705_0_2021/1_5hgwu9bi']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: d0266b574
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://mediaspace.carleton.ca/media/4705_0_2021/1_5hgwu9bi
[generic] 1_5hgwu9bi: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1_5hgwu9bi: Downloading webpage
[generic] 1_5hgwu9bi: Extracting information
[debug] Looking for video embeds
[download] Downloading playlist: 4705_0_2021 - Carleton University Mediaspace
[generic] Playlist 4705_0_2021 - Carleton University Mediaspace: Downloading 1 videos of 1
[download] Downloading video 1 of 1
[debug] [Kaltura] Extracting URL: kaltura:2011531:1_5hgwu9bi#__youtubedl_smuggle=%7B%22source_url%22%3A+%22https%3A%2F%2Fmediaspace.carleton.ca%2Fmedia%2F4705_0_2021%2F1_5hgwu9bi%22%2C+%22service_url%22%3A+%22https%3A%2F%2Fcdnapisec.kaltura.com%22%7D
1_5hgwu9bi
[Kaltura] 1_5hgwu9bi: Downloading video info JSON
ERROR: [Kaltura] 1_5hgwu9bi: Kaltura said: Invalid entry id ["1_5hgwu9bi"] (1); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "~\yt-dlp\yt_dlp\extractor\common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "~\yt-dlp\yt_dlp\extractor\kaltura.py", line 245, in _real_extract
    _, info, flavor_assets, captions = self._get_video_info(entry_id, partner_id, smuggled_data.get('service_url'))
  File "~\yt-dlp\yt_dlp\extractor\kaltura.py", line 233, in _get_video_info
    return self._kaltura_api_call(
  File "~\yt-dlp\yt_dlp\extractor\kaltura.py", line 188, in _kaltura_api_call
    raise ExtractorError(

[download] Finished downloading playlist: 4705_0_2021 - Carleton University Mediaspace
```

**Comment by pzhlkj6612** [comment]
Version `2024.08.06`:

```
[debug] Command-line config: ['-vU', 'https://mediaspace.carleton.ca/media/4705_0_2021/1_5hgwu9bi']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.9 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg n6.1.1-7-ga267d4ad4c-20240222 (setts), ffprobe n6.1.1-7-ga267d4ad4c-20240222 
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.1, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp 
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://mediaspace.carleton.ca/media/4705_0_2021/1_5hgwu9bi 
[generic] 1_5hgwu9bi: Downloading webpage
WARNING: [generic] Falling back on generic information extractor 
[generic] 1_5hgwu9bi: Extracting information 
[debug] Looking for embeds
[debug] Identified a Kaltura embed 
[Kaltura] Extracting URL: kaltura:2011531:1_5hgwu9bi#__youtubedl_smuggle=%7B%22service_url%22%3A+%22https%3A%2F%2Fcdnapisec.kaltura.com%22%7D 
[Kaltura] 1_5hgwu9bi: Downloading video info JSON (Kaltura html5 player)
ERROR: [Kaltura] 1_5hgwu9bi: Kaltura said: Invalid entry id ["1_5hgwu9bi"] (1); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File ".../yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File ".../yt-dlp/yt_dlp/extractor/kaltura.py", line 391, in _real_extract
    _, info, flavor_assets, captions = self._get_video_info(entry_id, partner_id, smuggled_data.get('service_url'), player_type=player_type)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../yt-dlp/yt_dlp/extractor/kaltura.py", line 269, in _get_video_info
    return self._get_video_info_html5(video_id, partner_id, service_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../yt-dlp/yt_dlp/extractor/kaltura.py", line 312, in _get_video_info_html5
    return self._kaltura_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File ".../yt-dlp/yt_dlp/extractor/kaltura.py", line 257, in _kaltura_api_call
    raise ExtractorError(

```

.
