### ISSUE TITLE
ERROR: Facebook Video Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F772023541757441&_fb_noscript=1

### ISSUE THREAD

**Issue by kishoreyakkanti** [yt-dlp/yt-dlp#11087]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Unable to Download facebook videos ERROR: Facebook Video Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F772023541757441&_fb_noscript=1

1. first i am checking video duraction of facebook video with below code
info_dict = ydl.extract_info(input_url, download=False)
video_duration_minutes = info_dict.get('duration', 0) / 60
2. second  using below ytdlp opts i am downloading first 2 minutes
ydl_opts = {
        'outtmpl': 'Video/%(id)s.%(ext)s',
        'cookiefile': 'cookies.txt',
        'format': 'mp4',
        'quiet': True
    }
ydl_opts['download_ranges'] = download_range_func(None, [(0, 121)])
ydl_opts['force_keyframes_at_cuts'] = True
y_dlp = yt_dlp.YoutubeDL(ydl_opts)
 y_dlp.download([input_url])

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
WARNING: [generic] Falling back on generic information extractor
WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F772023541757441&_fb_noscript=1
Traceback (most recent call last):
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F772023541757441&_fb_noscript=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/datascience.apis/v3_fb_instream/video_download.py", line 110, in download_video_dl
    info_dict = ydl.extract_info(input_url, download=False)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1615, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1861, in process_ie_result
    return self.extract_info(
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1615, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1861, in process_ie_result
    return self.extract_info(
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1615, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1644, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1092, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1031, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F772023541757441&_fb_noscript=1

$ ERROR ERROR: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F772023541757441&_fb_noscript=1
$ Video download problem 772023541757441
$ First download attempt failed. Retrying...772023541757441
$ Downloading..772023541757441
WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F772023541757441
Traceback (most recent call last):
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F772023541757441

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/datascience.apis/v3_fb_instream/video_download.py", line 110, in download_video_dl
    info_dict = ydl.extract_info(input_url, download=False)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1615, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1861, in process_ie_result
    return self.extract_info(
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1615, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1644, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1092, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/data/data/minicoda2/envs/video/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1031, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F772023541757441

$ ERROR ERROR: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F772023541757441
```

**Comment by seproDev** [comment]
That URL is a login URL, so the unsupported URL is expected. Instead you want to pass the actual video URL: https://www.facebook.com/100089714062809/videos/772023541757441/

You should also not extract the video twice, but re-use the info dict to save on api requests.
