### ISSUE TITLE
There's seems a resource missing at latest ver on master branch

### ISSUE THREAD

**Issue by katfionn** [yt-dlp/yt-dlp#11116]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

the file in ./yt-dlp/extractor/list_extractor_classes.py does not exist.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Traceback (most recent call last):
  File "/home/yt-dlp/yt_dlp/__main__.py", line 14, in <module>
    import yt_dlp
  File "/home/yt-dlp/yt_dlp/__init__.py", line 20, in <module>
    from .extractor import list_extractor_classes
ImportError: cannot import name 'list_extractor_classes' from 'yt_dlp.extractor' (unknown location)
```

**Comment by bashonly** [comment]
how are you running yt-dlp? how did you install yt-dlp? please give more info

**Comment by katfionn** [comment]
> how are you running yt-dlp? how did you install yt-dlp? please give more info

Here's the way how i run yt-dlp, it worked in thte passed:
1. download the latest version of yt-dlp' master branch and unzip it to path `/home`
2. comfirmed there's a path call `/data/disk` exist on my machine
3. run the command, used `{{}}` and `*` to replace domain: `cd /home/yt-dlp/&&./yt-dlp.sh -P /data/disk -f bestvideo*+bestaudio/best https://{{www*youtube*com}}/watch?v=AkMmJkzYrOs`

**Comment by gamer191** [comment]
I wonder if it will work if you run the `cd` command separately
If not, please post a full log with --verbose added to the yt-dlp command

**Comment by bashonly** [comment]
`/home/yt-dlp` ? so `yt-dlp` is your username? Why?

**Comment by bashonly** [comment]
This seems like a `PATH`/`PYTHONPATH` issue due to the unconventional `/home/` dir structure. I'd suggest creating an actual user and installing yt-dlp in its home dir, e.g. `/home/exampleuser/yt-dlp`. Closing due to inactivity, can reopen if the OP has further problems/questions
