### ISSUE TITLE
[YouTube]: ERROR: InfoExtractor._download_json() got an unexpected keyword argument 'cndn'

### ISSUE THREAD

**Issue by BlackMightyRavenDark** [yt-dlp/yt-dlp#11110]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello!
Today i have YT extractor problem.
It's the same output for all videos. It's ok in my browser.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'SO83KQuuZvg', '-F']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: fa2be9a7c
[debug] Python 3.12.0 (CPython AMD64 64bit) - Windows-11-10.0.22621-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg 2024-08-01-git-bcf08c1171-full_build-www.gyan.dev (setts), ffprobe N-90796-ge5ba5fab49
[debug] Optional libraries: sqlite3-3.42.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: SO83KQuuZvg
[youtube] SO83KQuuZvg: Downloading webpage
ERROR: InfoExtractor._download_json() got an unexpected keyword argument 'cndn'
Traceback (most recent call last):
  File "H:\Projects\python\yt-dlp\yt_dlp\YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Projects\python\yt-dlp\yt_dlp\YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "H:\Projects\python\yt-dlp\yt_dlp\extractor\common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Projects\python\yt-dlp\yt_dlp\extractor\youtube.py", line 4369, in _real_extract
    webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Projects\python\yt-dlp\yt_dlp\extractor\youtube.py", line 4333, in _download_player_responses
    player_responses, player_url = self._extract_player_responses(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Projects\python\yt-dlp\yt_dlp\extractor\youtube.py", line 3930, in _extract_player_responses
    pr = pr or self._extract_player_response(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Projects\python\yt-dlp\yt_dlp\extractor\youtube.py", line 3814, in _extract_player_response
    return self._extract_response(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Projects\python\yt-dlp\yt_dlp\extractor\youtube.py", line 1037, in _extract_response
    response = self._call_api(
               ^^^^^^^^^^^^^^^
  File "H:\Projects\python\yt-dlp\yt_dlp\extractor\youtube.py", line 670, in _call_api
    return self._download_json(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: InfoExtractor._download_json() got an unexpected keyword argument 'cndn'
```
```

**Comment by BlackMightyRavenDark** [comment]
I found out what the problem was. My file system was corrupted last night. Cloning the project to another disk solved the problem.
I'm sorry to bother you.
