### ISSUE TITLE
Add support for Podia

### ISSUE THREAD

**Issue by crewshin** [yt-dlp/yt-dlp#11111]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

usa

### Example URLs

- Single video: https://fbabossacademy.podia.com/view/courses/f919ed3c-7e6e-47d0-9fb0-bc6b4f69bdb9/2443053-unit-1-getting-started/8830114-introduction-to-unit-1

### Provide a description that is worded well enough to be understood

Podia is a competitor to teachable. They allow users to upload paid video courses which end up as a list of videos you can watch and track progress.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-vU', 'https://fbabossacademy.podia.com/view/courses/f919ed3c-7e6e-47d0-9fb0-bc6b4f69bdb9/2443053-unit-1-getting-started/8830114-introduction-to-unit-1']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.6 (CPython arm64 64bit) - macOS-15.0-arm64-arm-64bit (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://fbabossacademy.podia.com/view/courses/f919ed3c-7e6e-47d0-9fb0-bc6b4f69bdb9/2443053-unit-1-getting-started/8830114-introduction-to-unit-1
[generic] 8830114-introduction-to-unit-1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 8830114-introduction-to-unit-1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://fbabossacademy.podia.com/view/courses/f919ed3c-7e6e-47d0-9fb0-bc6b4f69bdb9/2443053-unit-1-getting-started/8830114-introduction-to-unit-1
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://fbabossacademy.podia.com/view/courses/f919ed3c-7e6e-47d0-9fb0-bc6b4f69bdb9/2443053-unit-1-getting-started/8830114-introduction-to-unit-1
```

**Comment by bashonly** [comment]
what happens when you try passing cookies to yt-dlp

**Comment by XdekHckr** [comment]
What video player do they even use on website? If it's vimeo or bunny cdn then it can be downloaded in different way...

**Comment by crewshin** [comment]
No idea to both of those questions. But I'll try and test cookies asap.

**Comment by XdekHckr** [comment]
> No idea to both of those questions. But I'll try and test cookies asap.

if you want to download these videos with something else than yt-dlp then try this: https://chromewebstore.google.com/detail/the-stream-detector/iakkmkmhhckcmoiibcfjnooibphlobak

It will automatically get command for you, you need to only paste it into your cmd.
As I am unable to check and debug how these videos are served, because there is no demo video to be played on website that you linked (content locked behind paywall) then I can't help with it.

**Comment by crewshin** [comment]
So the stream detector worked great.

Cookies, not so much...

```shell
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-u', 'PRIVATE', '-vU', 'https://fbabossacademy.podia.com/view/courses/f919ed3c-7e6e-47d0-9fb0-bc6b4f69bdb9/2443053-unit-1-getting-started/7796985-budget-expectations-inventory']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.6 (CPython arm64 64bit) - macOS-15.0-arm64-arm-64bit (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/crewshin/Library/Application Support/Google/Chrome/Profile 2/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
Extracted 1056 cookies from chrome
[debug] cookie version breakdown: {'v10': 1080, 'other': 0, 'unencrypted': 12}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.08.06 from yt-dlp/yt-dlp
Latest version: stable@2024.09.27 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[generic] Extracting URL: https://fbabossacademy.podia.com/view/courses/f919ed3c-7e6e-47d0-9fb0-bc6b4f69bdb9/2443053-unit-1-getting-started/7796985-budget-expectations-inventory
[generic] 7796985-budget-expectations-inventory: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 7796985-budget-expectations-inventory: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://fbabossacademy.podia.com/view/courses/f919ed3c-7e6e-47d0-9fb0-bc6b4f69bdb9/2443053-unit-1-getting-started/7796985-budget-expectations-inventory
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://fbabossacademy.podia.com/view/courses/f919ed3c-7e6e-47d0-9fb0-bc6b4f69bdb9/2443053-unit-1-getting-started/7796985-budget-expectations-inventory
```

**Comment by Omegaplexx** [comment]
> I guess that means the `--cookies-from-browser` makes it work?

Yeah. It automatically looks for cookies in your browser directories and then uses them to download video
