### ISSUE TITLE
Failed to parse JSON (caused by JSONDecodeError...

### ISSUE THREAD

**Issue by bleachgh** [yt-dlp/yt-dlp#11134]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

china

### Provide a description that is worded well enough to be understood

Error while try to download from ixigua.com.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.ixigua.com/7401795461469700634', '--ignore-config', '--ignore-errors', '--cookies', 'e:\\cookies.txt', '--referer', 'https://www.ixigua.com/']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.29.232819 from yt-dlp/yt-dlp-nightly-builds [6328e2e67] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n7.0.2-19-g45ecf80f0e-20240928 (setts), ffprobe 2.7
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.29.232819 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.29.232819 from yt-dlp/yt-dlp-nightly-builds)
[Ixigua] Extracting URL: https://www.ixigua.com/7401795461469700634
[Ixigua] 740179546146970063: Downloading webpage
ERROR: [Ixigua] 740179546146970063: 740179546146970063: Failed to parse JSON (caused by JSONDecodeError('Extra data in \'atedData" = "functio\': line 2 column 37 (char 37)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\ixigua.py", line 67, in _real_extract
  File "yt_dlp\extractor\ixigua.py", line 42, in _get_json_data
  File "yt_dlp\extractor\common.py", line 1093, in _parse_json
  File "yt_dlp\extractor\common.py", line 1076, in __print_error

  File "yt_dlp\utils\_utils.py", line 552, in decode
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 2 column 37 (char 37)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1090, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 560, in decode
json.decoder.JSONDecodeError: Extra data in 'atedData" = "functio': line 2 column 37 (char 37)
```

**Comment by bashonly** [comment]
The extractor uses `get_element_by_id` to extract the JSON, which calls `unescapeHTML` on the string result, unescaping `&quot;` to `"` and breaking JSON parsing. The extractor's `_get_json_data()` method needs to be rewritten with `_search_json()`

**Comment by bleachgh** [comment]
> The extractor uses `get_element_by_id` to extract the JSON, which calls `unescapeHTML` on the string result, unescaping `&quot;` to `"` and breaking JSON parsing. The extractor's `_get_json_data()` method needs to be rewritten with `_search_json()`

Thanks, hope it gets fixed soon, I need to use this site regularly. I don't know how to write _search_json() method

**Comment by dirkf** [comment]
It would be a pity to have to rework the `get_element_...()` code for this case. Maybe:
```diff
-        js_data = get_element_by_id('SSR_HYDRATED_DATA', webpage)
+        js_data = get_element_html_by_id('SSR_HYDRATED_DATA', webpage) or ''
+        js_data = re.sub(r'^<[^>]+>|</[^>]+>$', '', js_data)
```

**Comment by bashonly** [comment]
why is that better than using `_search_json`? it's not hard

```diff
diff --git a/yt_dlp/extractor/ixigua.py b/yt_dlp/extractor/ixigua.py
index 2868c2fc7..28644d284 100644
--- a/yt_dlp/extractor/ixigua.py
+++ b/yt_dlp/extractor/ixigua.py
@@ -33,14 +33,16 @@ class IxiguaIE(InfoExtractor):
     }]
 
     def _get_json_data(self, webpage, video_id):
-        js_data = get_element_by_id('SSR_HYDRATED_DATA', webpage)
-        if not js_data:
-            if self._cookies_passed:
-                raise ExtractorError('Failed to get SSR_HYDRATED_DATA')
-            raise ExtractorError('Cookies (not necessarily logged in) are needed', expected=True)
+        js_data = self._search_json(
+            r'<script [^>]*\bid="SSR_HYDRATED_DATA"[^>]*>\s*window\._SSR_HYDRATED_DATA\s*=',
+            webpage, 'SSR hydrated data', display_id, end_pattern=r'</script>',
+            transform_source=js_to_json, default=None)
+        if js_data:
+            return js_data
 
-        return self._parse_json(
-            js_data.replace('window._SSR_HYDRATED_DATA=', ''), video_id, transform_source=js_to_json)
+        if self._cookies_passed:
+            raise ExtractorError('Failed to get SSR_HYDRATED_DATA')
+        raise ExtractorError('Cookies (not necessarily logged in) are needed', expected=True)
 
     def _media_selector(self, json_data):
         for path, override in (
```

**Comment by dirkf** [comment]
FWIW, this illustrates [the point](https://github.com/yt-dlp/yt-dlp/issues/11134#issuecomment-2392379445):
1. better to have a single source of knowledge for parsing HTML, especially anticipating #5588.

2. ignoring repurposed lines, -1/+2 lines of diff vs -3/+5.

**Comment by bashonly** [comment]
In general I think the `get_element_*` helpers should be avoided for the purpose of extracting JSON; this is something I have been advocating in code reviews for a long time. `_search_json` is the tool to be used here; I don't care if the diff is 2 lines longer

**Comment by seaklin83546** [comment]
> ```diff
> diff --git a/yt_dlp/extractor/ixigua.py b/yt_dlp/extractor/ixigua.py
> index 2868c2fc7..28644d284 100644
> --- a/yt_dlp/extractor/ixigua.py
> +++ b/yt_dlp/extractor/ixigua.py
> @@ -33,14 +33,16 @@ class IxiguaIE(InfoExtractor):
>      }]
>  
>      def _get_json_data(self, webpage, video_id):
> -        js_data = get_element_by_id('SSR_HYDRATED_DATA', webpage)
> -        if not js_data:
> -            if self._cookies_passed:
> -                raise ExtractorError('Failed to get SSR_HYDRATED_DATA')
> -            raise ExtractorError('Cookies (not necessarily logged in) are needed', expected=True)
> +        js_data = self._search_json(
> +            r'<script [^>]*\bid="SSR_HYDRATED_DATA"[^>]*>\s*window\._SSR_HYDRATED_DATA\s*=',
> +            webpage, 'SSR hydrated data', display_id, end_pattern=r'</script>',
> +            transform_source=js_to_json, default=None)
> +        if js_data:
> +            return js_data
>  
> -        return self._parse_json(
> -            js_data.replace('window._SSR_HYDRATED_DATA=', ''), video_id, transform_source=js_to_json)
> +        if self._cookies_passed:
> +            raise ExtractorError('Failed to get SSR_HYDRATED_DATA')
> +        raise ExtractorError('Cookies (not necessarily logged in) are needed', expected=True)
>  
>      def _media_selector(self, json_data):
>          for path, override in (
> ```

When i do it is error


py devscripts/make_lazy_extractors.py
Traceback (most recent call last):
  File "D:\C#\TestLicense_Update2_220524\yt-dlp-master\devscripts\make_lazy_extractors.py", line 132, in <module>
    main()
  File "D:\C#\TestLicense_Update2_220524\yt-dlp-master\devscripts\make_lazy_extractors.py", line 41, in main
    _ALL_CLASSES = get_all_ies()  # Must be before import
  File "D:\C#\TestLicense_Update2_220524\yt-dlp-master\devscripts\make_lazy_extractors.py", line 68, in get_all_ies
    from yt_dlp.extractor.extractors import _ALL_CLASSES
  File "D:\C#\TestLicense_Update2_220524\yt-dlp-master\yt_dlp\extractor\extractors.py", line 17, in <module>
    from ._extractors import *  # noqa: F403
  File "D:\C#\TestLicense_Update2_220524\yt-dlp-master\yt_dlp\extractor\_extractors.py", line 905, in <module>
    from .ixigua import IxiguaIE
  File "D:\C#\TestLicense_Update2_220524\yt-dlp-master\yt_dlp\extractor\ixigua.py", line 39
    +            transform_source=js_to_json, default=None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?

**Comment by grqz** [comment]
i think you need to `git apply` it(ending with EOF, should be Ctrl+Z on windows)

> When i do it is error

**Comment by seaklin83546** [comment]
> you need to `git apply` it(ending with EOF, should be Ctrl+Z on windows)
> 
> > When i do it is error

How to write sir. Please help me

**Comment by seaklin83546** [comment]
> you need to `git apply` it(ending with EOF, should be Ctrl+Z on windows)
> 
> > When i do it is error

diff --git a/yt_dlp/extractor/ixigua.py b/yt_dlp/extractor/ixigua.py
index 2868c2fc7..28644d284 100644
--- a/yt_dlp/extractor/ixigua.py
+++ b/yt_dlp/extractor/ixigua.py
@@ -33,14 +33,16 @@ class IxiguaIE(InfoExtractor):
     }]

     def _get_json_data(self, webpage, video_id):
-        js_data = get_element_by_id('SSR_HYDRATED_DATA', webpage)
-        if not js_data:
-            if self._cookies_passed:
-                raise ExtractorError('Failed to get SSR_HYDRATED_DATA')
-            raise ExtractorError('Cookies (not necessarily logged in) are needed', expected=True)
+        js_data = self._search_json(
+            r'<script [^>]*\bid="SSR_HYDRATED_DATA"[^>]*>\s*window\._SSR_HYDRATED_DATA\s*=',
+            webpage, 'SSR hydrated data', display_id, end_pattern=r'</script>',
+            transform_source=js_to_json, default=None)
+        if js_data:
+            return js_data

-        return self._parse_json(
-            js_data.replace('window._SSR_HYDRATED_DATA=', ''), video_id, transf         for path, override in (son_data):t necessarily logged in) are needed',
diff: unknown option -- git
diff: Try 'diff --help' for more information.
bash: index: command not found
bash: ---: command not found
bash: +++: command not found
bash: syntax error near unexpected token `('
bash: }]: command not found
bash: syntax error near unexpected token `('
bash: syntax error near unexpected token `('
bash: -: command not found
bash: -: command not found
bash: syntax error near unexpected token `('
bash: syntax error near unexpected token `('
bash: syntax error near unexpected token `('
bash: +: command not found
bash: +: command not found
bash: syntax error near unexpected token `)'
bash: +: command not found
bash: +: command not found
bash: syntax error near unexpected token `('
bash: syntax error near unexpected token `('
bash: +: command not found
bash: syntax error near unexpected token `('
bash: syntax error near unexpected token `('
bash: syntax error near unexpected token `('
bash: syntax error near unexpected token `override'
