### ISSUE TITLE
[olympics.com] Wrong audio track format downloading by default. Paris 2024

### ISSUE THREAD

**Issue by Cryosim** [yt-dlp/yt-dlp#11133]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi. then i try downloading just https://olympics.com/en/paris-2024/videos/men-s-play-in-games-basketball-3x3-olympic-games-paris-2024
wrong downloading by defauilt audio track

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\mcmas>python -myt_dlp -vF https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-o
lympic-games-paris-2024
[debug] Command-line config: ['-vF', 'https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.29.232819 from yt-dlp/yt-dlp-nightly-builds [6328e2e67] (pip)
[debug] Python 3.12.1 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.43.1, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[OlympicsReplay] Extracting URL: https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading webpage
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading tokenized m3u8 url
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for ab5abea5-aa23-4ac1-8250-538c420af844:
ID                                EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio-AACL-180-English        mp4 audio only     │       m3u8  │ audio only        unknown    [eng] English
hls-audio-AACL-180-Original_audio mp4 audio only     │       m3u8  │ audio only        unknown    [qaa] Original audio
hls-334                           mp4 320x180     25 │  334k m3u8  │ avc1.4d400c  334k video only
hls-771                           mp4 640x360     25 │  771k m3u8  │ avc1.4d401e  771k video only
hls-1313                          mp4 854x480     25 │ 1313k m3u8  │ avc1.4d401e 1313k video only
hls-2395                          mp4 1280x720    25 │ 2396k m3u8  │ avc1.4d401f 2396k video only
hls-5645                          mp4 1920x1080   25 │ 5645k m3u8  │ avc1.4d4028 5645k video only

C:\Users\mcmas>
```
Then i try downloading audio, downloaded wrong audio format hls-audio-AACL-180-Original_audio
```
C:\Users\mcmas>python -myt_dlp -vfba https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3
-olympic-games-paris-2024
[debug] Command-line config: ['-vfba', 'https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.29.232819 from yt-dlp/yt-dlp-nightly-builds [6328e2e67] (pip)
[debug] Python 3.12.1 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.43.1, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[OlympicsReplay] Extracting URL: https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading webpage
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading tokenized m3u8 url
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] ab5abea5-aa23-4ac1-8250-538c420af844: Downloading 1 format(s): hls-audio-AACL-180-Original_audio
[debug] Invoking hlsnative downloader on "https://ott-l2v.olympicchannel.com/OVP_PRD/PAROVP-198_ch01_56364/hls/hdntl=exp=1727792307~acl=%2f*~data=hdntl~hmac=7fd6447691d40aa945ddcd5a5f9e261b92833affef4d35ea1ba7747dacb9dcf8/par100019800-mp4a_179600_qaa=20001.m3u8?aka_me_session_id=AAAAAAAAAACzBPxmAAAAAD7YKUDvDH+Hbz8NYlUFlJNEXXjOS9rGMwQdFjhwSV0mRGvrcahEDN06e3it%2fF1E%2fWm2AQXPYKga&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1910
[download] Destination: Pool Round - Day 9 - Afternoon ｜ Basketball 3x3 ｜ Olympic Games Paris 2024 [ab5abea5-aa23-4ac1-8250-538c420af844].mp4
[debug] File locking is not supported. Proceeding without locking
[download]   2.4% of ~ 128.72MiB at  203.68KiB/s ETA 09:18 (frag 47/1910)
```
```

**Comment by bashonly** [comment]
You could pass `-f "bv+ba[language^=en]"`

**Comment by Cryosim** [comment]
@bashonly Not working.
```
C:\Users\mcmas>python -myt_dlp -vfba[language^=en] https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024
[debug] Command-line config: ['-vfba[language=en]', 'https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.29.232819 from yt-dlp/yt-dlp-nightly-builds [6328e2e67] (pip)
[debug] Python 3.12.1 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.43.1, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[OlympicsReplay] Extracting URL: https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading webpage
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading tokenized m3u8 url
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [OlympicsReplay] ab5abea5-aa23-4ac1-8250-538c420af844: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2977, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [OlympicsReplay] ab5abea5-aa23-4ac1-8250-538c420af844: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
you need to quote it

**Comment by Cryosim** [comment]
@bashonly Another issue:
```
C:\Users\mcmas>python -myt_dlp -vf"ba[language^=en]" https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024
[debug] Command-line config: ['-vfba[language^=en]', 'https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.29.232819 from yt-dlp/yt-dlp-nightly-builds [6328e2e67] (pip)
[debug] Python 3.12.1 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.43.1, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[OlympicsReplay] Extracting URL: https://olympics.com/en/paris-2024/videos/pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading webpage
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading tokenized m3u8 url
[OlympicsReplay] pool-round-day-9-afternoon-basketball-3x3-olympic-games-paris-2024: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] ab5abea5-aa23-4ac1-8250-538c420af844: Downloading 1 format(s): hls-audio-AACL-180-English
[debug] Invoking hlsnative downloader on "https://ott-l2v.olympicchannel.com/OVP_PRD/PAROVP-198_ch01_56364/hls/hdntl=exp=1727793070~acl=%2f*~data=hdntl~hmac=6ea0b60babd60e74b8601dd9c83ec0e7813f41773d0e5a487b0f6634d504166e/par100019800-mp4a_179600_eng_DESC=20000.m3u8?aka_me_session_id=AAAAAAAAAACuB%2fxmAAAAAEB0JZiLUeCpeJaRDIS2qjSclkFY+QA2A+QAJxGS0RsY3NiqQgZCNN22Z40g%2fYUy92CcfwLTyh3M&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1910
[download] Destination: Pool Round - Day 9 - Afternoon ｜ Basketball 3x3 ｜ Olympic Games Paris 2024 [ab5abea5-aa23-4ac1-8250-538c420af844].mp4
[debug] File locking is not supported. Proceeding without locking
[download]   2.8% of ~ 128.44MiB at   30.57KiB/s ETA Unknown (frag 54/1910)ERROR: Data must be padded to 16 byte boundary in CBC mode
Traceback (most recent call last):
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3015, in process_video_result
    self.process_info(new_info)
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3483, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3203, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\hls.py", line 381, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\fragment.py", line 516, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\fragment.py", line 364, in decrypt_fragment
    return unpad_pkcs7(aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\aes.py", line 11, in aes_cbc_decrypt_bytes
    return Cryptodome.AES.new(key, Cryptodome.AES.MODE_CBC, iv).decrypt(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\Cryptodome\Cipher\_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode
```

**Comment by bashonly** [comment]
Try with `--downloader ffmpeg`
