### ISSUE TITLE
[olympics.com] Data must be padded to 16 byte boundary in CBC mode

### ISSUE THREAD

**Issue by Cryosim** [yt-dlp/yt-dlp#11188]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi. then i try download videos, got error ValueError: Data must be padded to 16 byte boundary in CBC mode/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
python -myt_dlp -v -N 15 https://olympics.com/en/paris-2024/videos/track-and-field-day-10-morning-athletics-olympic-games-paris-2024
[debug] Command-line config: ['-v', '-N', '15', 'https://olympics.com/en/paris-2024/videos/track-and-field-day-10-morning-athletics-olympic-games-paris-2024']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.01.232843 from yt-dlp/yt-dlp-nightly-builds [e59c82a74] (pip)
[debug] Python 3.12.1 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg 2024-09-26-git-f43916e217-full_build-www.gyan.dev (setts), ffprobe 2024-09-26-git-f43916e217-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.43.1, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[OlympicsReplay] Extracting URL: https://olympics.com/en/paris-2024/videos/track-and-field-day-10-morning-athletics-olympic-games-paris-2024
[OlympicsReplay] track-and-field-day-10-morning-athletics-olympic-games-paris-2024: Downloading webpage
[OlympicsReplay] track-and-field-day-10-morning-athletics-olympic-games-paris-2024: Downloading tokenized m3u8 url
[OlympicsReplay] track-and-field-day-10-morning-athletics-olympic-games-paris-2024: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4d6990c7-ee70-48c3-889c-83887ecded41: Downloading 1 format(s): hls-6260+hls-audio_group-ENGLISH
[debug] Invoking hlsnative downloader on "https://vod-b.olympicchannel.com/output/parathletics_22/hdntl=exp=1728415267~acl=%2f*~data=hdntl~hmac=64fb80b5b9be0d507ce341b451592536956cfe704ece808b97d822d9aa4c99d9/video_1920_6000000-1727084147.m3u8?aka_me_session_id=AAAAAAAAAAAjhgVnAAAAAJRZCTdL8qCXY53egxPcrYckULkzuBlgoVy%2fq7db%2fMTet45aN4rq81yIWMjEgcLQyCiURlARsGfh&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3020
[download] Destination: Track and Field - Day 10 - Morning ｜ Athletics ｜ Olympic Games Paris 2024 [4d6990c7-ee70-48c3-889c-83887ecded41].fhls-6260.mp4
[debug] File locking is not supported. Proceeding without locking
[download]  40.3% of ~   8.65GiB at   59.97MiB/s ETA 01:29 (frag 1216/3020)[download] Got error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2559). Retrying (1/10)...
[download]  42.3% of ~   8.64GiB at   47.76MiB/s ETA 01:38 (frag 1279/3020)ERROR: Data must be padded to 16 byte boundary in CBC mode
Traceback (most recent call last):
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3015, in process_video_result
    self.process_info(new_info)
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3465, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3203, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\hls.py", line 381, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\fragment.py", line 501, in download_and_append_fragments
    if not append_fragment(decrypt_fragment(fragment, self._read_fragment(ctx)), frag_index, ctx):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\fragment.py", line 364, in decrypt_fragment
    return unpad_pkcs7(aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\aes.py", line 11, in aes_cbc_decrypt_bytes
    return Cryptodome.AES.new(key, Cryptodome.AES.MODE_CBC, iv).decrypt(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\Cryptodome\Cipher\_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode
```

**Comment by dirkf** [comment]
#1297 again. A possibly truncated or invalid ciphertext that is not a multiple of the AES-CBC blocksize (16 bytes) is being passed to the Crypto API.
