### ISSUE TITLE
[Broken] Douyin

### ISSUE THREAD

**Issue by theoy2** [yt-dlp/yt-dlp#1121]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

[debug] Command-line config: ['-v', 'https://www.douyin.com/video/6961737553342991651']
[debug] Encodings: locale cp1256, fs utf-8, out cp1256, pref cp1256
[debug] yt-dlp version 2021.09.25 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: none
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Douyin] Extracting URL: https://www.douyin.com/video/6961737553342991651
ERROR: [Douyin] 6961737553342991651: Unable to extract render data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 585, in extract
  File "yt_dlp\extractor\douyin.py", line 102, in _real_extract
  File "yt_dlp\extractor\common.py", line 1149, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract render data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 585, in extract
  File "yt_dlp\extractor\douyin.py", line 102, in _real_extract
  File "yt_dlp\extractor\common.py", line 1149, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract render data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1252, in __extract_info
  File "yt_dlp\extractor\common.py", line 601, in extract
yt_dlp.utils.ExtractorError: [Douyin] 6961737553342991651: Unable to extract render data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.



Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 4
Milliseconds      : 613
Ticks             : 46134148
TotalDays         : 5.33960046296296E-05
TotalHours        : 0.00128150411111111
TotalMinutes      : 0.0768902466666667
TotalSeconds      : 4.6134148
TotalMilliseconds : 4613.4148

```

## Description

I have tried even on Linux, however, I got the same returned output.

**Comment by MinePlayersPE** [comment]
Temporary workaround: try with cookies from browser (doesn't have to be logged in)
