### ISSUE TITLE
[site request] https://www.boomplay.com

### ISSUE THREAD

**Issue by solomoncyj** [yt-dlp/yt-dlp#11220]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

*

### Example URLs

https://www.boomplay.com/songs/165481965

### Provide a description that is worded well enough to be understood

genric extractors do not work

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.boomplay.com/songs/165481965', '-vU']
[debug] User config "/home/solomoncyj/.yt-dlp/config.txt": ['-o', './%(playlist_title|)s/%(title)s.%(ext)s', '-N', '50', '-S', 'vcodec:vp9', '--embed-metadata', '--sub-langs', 'all,-live_chat', '--embed-subs', '--live-from-start']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874]
[debug] Lazy loading extractors is disabled
[debug] Python 3.13.0 (CPython x86_64 64bit) - Linux-6.11.2-300.fc41.x86_64-x86_64-with-glibc2.40 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.40)
[debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-1.26.20, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.boomplay.com/songs/165481965
[generic] 165481965: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 165481965: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.boomplay.com/songs/165481965
Traceback (most recent call last):
  File "/home/solomoncyj/.local/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/solomoncyj/.local/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/home/solomoncyj/.local/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/home/solomoncyj/.local/lib/python3.13/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.boomplay.com/songs/165481965
```

**Comment by grqz** [comment]
> https://www.boomplay.com/video/1154892

The videos are actually supported by the generic extractor

```log
$ python3 -m yt_dlp -vF "https://www.boomplay.com/video/1154892" --no-simulate --write-info-json --force-overwrite
[debug] Command-line config: ['-vF', 'https://www.boomplay.com/video/1154892', '--no-simulate', '--write-info-json', '--force-overwrite']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: ceaea731b
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.21.0, certifi-2024.06.02, curl_cffi-0.7.1, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.2
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, curl_cffi
[debug] Plugin directories: ['/home/user/.local/lib/python3.10/site-packages/yt_dlp_plugins']
[debug] Loaded 1838 extractors
[generic] Extracting URL: https://www.boomplay.com/video/1154892
[generic] 1154892: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1154892: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[generic] Extracting URL: https://source.boomplaymusic.com/group10/M00/10/11/937e897acd854255bb82957625b73f3d.mp4#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%221154892%22%2C+%22to_generic%22%3A+true%2C+%22referer%22%3A+%22https%3A%2F%2Fwww.boomplay.com%2Fvideo%2F1154892%22%7D
[generic] 1154892: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1154892:
ID  EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
────────────────────────────────────────────
mp4 mp4 unknown    │ https │ unknown unknown
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1154892: Downloading 1 format(s): mp4
[info] Writing video metadata as JSON to: Autumn blues [1154892].info.json
Deleting existing file Autumn blues [1154892].mp4
[debug] Invoking http downloader on "https://source.boomplaymusic.com/group10/M00/10/11/937e897acd854255bb82957625b73f3d.mp4"
[download] Destination: Autumn blues [1154892].mp4
[download] 100% of  341.75KiB in 00:00:00 at 2.01MiB/s
```

There is another m3u8 format not being extracted though

**Comment by dirkf** [comment]
The web app makes a POST to get (what I suppose must be) the media URL. The parameter sent in the POST data looks like the name part of the preview URL. The JSON returned, apart from country code, is encoded/obfuscated, but any coding is doubtless revealed in the site JS.

**Comment by grqz** [comment]
```py
import base64
import json
import re

from .common import InfoExtractor
from ..aes import aes_cbc_decrypt_bytes, aes_cbc_encrypt_bytes, unpad_pkcs7
from ..utils import get_elements_by_attribute, parse_duration, url_or_none, urlencode_postdata
from ..utils.traversal import traverse_obj


class BoomPlayBaseIE(InfoExtractor):
    # Calculated from const values, see lhx.AESUtils.encrypt, see public.js
    # Note that the real key/iv differs from `lhx.AESUtils.key`/`lhx.AESUtils.iv`
    _KEY = b'boomplayVr3xopAM'
    _IV = b'boomplay8xIsKTn9'

    def _get_playurl(self, _id, item_type='MUSIC'):
        return unpad_pkcs7(aes_cbc_decrypt_bytes(
            base64.b64decode(self._download_json(
                'https://www.boomplay.com/getResourceAddr', _id,
                note='Downloading play URL', errnote='Failed to download play URL',
                data=urlencode_postdata({
                    'param': base64.b64encode(aes_cbc_encrypt_bytes(json.dumps({
                        'itemID': _id,
                        'itemType': item_type,
                    }).encode(), self._KEY, self._IV)).decode(),
                }), headers={
                    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                })['source']), self._KEY, self._IV)).decode()

    def _extract_formats(self, _id, item_type='MUSIC', **kwargs):
        if url := url_or_none(self._get_playurl(_id, item_type)):
            return [{
                'format_id': '0',
                'vcodec': 'none' if item_type == 'MUSIC' else None,
                'url': url,
                'http_headers': {
                    'Origin': 'https://www.boomplay.com',
                    'Referer': 'https://www.boomplay.com',
                    'X-Boomplay-Ref': 'Boomplay_WEBV1',
                },
                **kwargs,
            }]
        else:
            self.raise_no_formats('No formats found')


class BoomPlayMusicIE(BoomPlayBaseIE):
    _VALID_URL = r'https?://(?:www\.)?boomplay\.com/songs/(?P<id>\d+)'

    def _real_extract(self, url):
        song_id = self._match_id(url)
        webpage = self._download_webpage(url, song_id)
        ld_json_meta = next(self._yield_json_ld(webpage, song_id))
        # schema `MusicRecording` not supported by self._json_ld()

        metadata_div = traverse_obj(get_elements_by_attribute(
            'class', r'[^\'"]*(?<=[\'"\s])summary(?=[\'"\s])[^\'"]*', webpage,
            tag='div', escape_value=False), 0) or ''
        title = self._html_search_regex(r'<h1>([^<]+)</h1>', metadata_div, 'title')
        # TODO: fallbacks and more metadata fields
        metadata_entries = re.findall(r'(?s)<strong>(?P<entry>.*?)</strong>', metadata_div) or []

        details_section = traverse_obj(get_elements_by_attribute(
            'class', r'[^\'"]*(?<=[\'"\s])songDetailInfo(?=[\'"\s])[^\'"]*', webpage,
            tag='section', escape_value=False), 0) or ''
        metadata_entries.extend(re.findall(r'(?s)<li>(?P<entry>.*?)</li>', details_section) or [])

        self.write_debug(title)
        self.write_debug(metadata_entries)
        return {
            **traverse_obj(ld_json_meta, {
                'title': 'name',
                'thumbnail': 'image',
                'channel_url': ('byArtist', 0, '@id'),
                'artists': ('byArtist', ..., 'name'),
                # '': ('inAlbum', '@id'),  # no fields for album url yet
                'duration': ('duration', {parse_duration}),
            }),
            'id': song_id,
            'formats': self._extract_formats(song_id, 'MUSIC'),
        }


class BoomPlayVideoIE(BoomPlayBaseIE):
    _VALID_URL = r'https?://(?:www\.)?boomplay\.com/video/(?P<id>\d+)'

    def _real_extract(self, url):
        video_id = self._match_id(url)
        return {
            'id': video_id,
            'formats': self._extract_formats(video_id, 'VIDEO', ext='mp4'),
            **self._search_json_ld(self._download_webpage(url, video_id), video_id),
        }
```

**Comment by dirkf** [comment]
I made an upstream version that succeeds on these tests, except for the file MD5, where IIRC the MD5 is produced differently. Some shimming was needed for missing or differently capable APIs.

1. The site respects XFF, so `_GEO_COUNTRIES = ['NG']`. Detect geo-block by no `source` in the play  URL JSON and `'unavailable in your country'` in its `desc`; also operating in `['GH', 'KE', 'TZ', 'CM', 'CI']` - I made those the `countries` for `raise_geo_restricted()` since `NG` must have failed.
<details><summary>upstream extractor</summary>

2. The ld+json extraction ought to be reworked against the schema.org class hierarchy, but my WIP implementation of that is stalled because it's not always clear where the existing code is doing something non-standard to match real-world exceptions.

```py
# coding: utf-8
from __future__ import unicode_literals

import base64
import functools
import json
import re

from .common import InfoExtractor
from ..aes import aes_cbc_decrypt_bytes, aes_cbc_encrypt_bytes, unpad_pkcs7
from ..compat import compat_b64decode
from ..utils import (
    clean_html,
    extract_attributes,
    ExtractorError,
    get_element_by_class,
    IDENTITY,
    int_or_none,
    JSON_LD_RE,
    merge_dicts,
    NO_DEFAULT,
    parse_duration,
    url_or_none,
    urlencode_postdata,
    variadic,
)
from ..traversal import (
    T,
    traverse_obj,
)


class BoomPlayBaseIE(InfoExtractor):
    # Calculated from const values, see lhx.AESUtils.encrypt, see public.js
    # Note that the real key/iv differs from `lhx.AESUtils.key`/`lhx.AESUtils.iv`
    _KEY = b'boomplayVr3xopAM'
    _IV = b'boomplay8xIsKTn9'
    _GEO_COUNTRIES = ['NG']

    def _yield_json_ld(self, html, video_id, fatal=True, default=NO_DEFAULT):
        """Yield all json ld objects in the html"""
        if default is not NO_DEFAULT:
            fatal = False
        for mobj in re.finditer(JSON_LD_RE, html):
            json_ld_item = self._parse_json(mobj.group('json_ld'), video_id, fatal=fatal)
            for json_ld in variadic(json_ld_item):
                if isinstance(json_ld, dict):
                    yield json_ld

    @staticmethod
    def __yield_elements_by_class_and_tag(class_, tag, html):
        for elt in re.finditer(r'(?si)<{tag}\s[^>]+>.+?</{tag}>'.format(tag=tag), html):
            elt = get_element_by_class(class_, elt.group(0))
            if elt:
                yield elt

    @classmethod
    def _get_elements_by_class_and_tag(cls, class_, tag, html):
        return list(cls.__yield_elements_by_class_and_tag(class_, tag, html))

    @classmethod
    def _get_element_by_class_and_tag(cls, class_, tag, html):
        return next(cls.__yield_elements_by_class_and_tag(class_, tag, html), None)

    def _get_playurl(self, _id, item_type='MUSIC'):
        source_map = self._download_json(
            'https://www.boomplay.com/getResourceAddr', _id,
            note='Downloading play URL', errnote='Failed to download play URL',
            data=urlencode_postdata({
                'param': base64.b64encode(aes_cbc_encrypt_bytes(json.dumps({
                    'itemID': _id,
                    'itemType': item_type,
                }).encode('ascii'), self._KEY, self._IV)).decode('utf-8'),
            }), headers={
                'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            })
        if not traverse_obj(source_map, ((
                ('source',),
                ('desc', T(lambda s: 'unavailable in your country' not in s))))):
            # since NG must have failed ...
            self.raise_geo_restricted(countries=['GH', 'KE', 'TZ', 'CM', 'CI']),
        return unpad_pkcs7(aes_cbc_decrypt_bytes(
            compat_b64decode(source_map['source']),
            self._KEY, self._IV)).decode('utf-8')

    def _extract_formats(self, _id, item_type='MUSIC', **kwargs):
        url = self._get_playurl(_id, item_type)
        all = (None, T(lambda _: None))
        fmts = traverse_obj(url, (
            T(url_or_none), all, {'url': None}, T(lambda f: merge_dicts(f, {
                'format_id': '0',
                'vcodec': 'none' if item_type == 'MUSIC' else None,
                'http_headers': {
                    'Origin': 'https://www.boomplay.com',
                    'Referer': 'https://www.boomplay.com',
                    'X-Boomplay-Ref': 'Boomplay_WEBV1',
                },
            }, kwargs))))
        self._sort_formats(fmts)
        return fmts

    @staticmethod
    def _mung_title(t, fatal=False):
        t = re.sub(r'^\s+|\s+(?:\|\s+Podcast\s+)?\|\s+Boomplay\s*$', '', t or '')
        if fatal and not t:
            raise ExtractorError('No title available')
        return t


class BoomPlayMusicIE(BoomPlayBaseIE):
    _VALID_URL = r'https?://(?:www\.)?boomplay\.com/songs/(?P<id>\d+)'
    _TEST = {
        'url': 'https://www.boomplay.com/songs/165481965',
        'md5': 'c5fb4f23e6aae98064230ef3c39c2178',
        'info_dict': {
            'title': 'Rise of the Fallen Heroes',
            'ext': 'mp3',
            'id': '165481965',
            'artists': ['fatbunny'],
            'thumbnail': 'https://source.boomplaymusic.com/group10/M00/04/29/375ecda38f6f48179a93c72ab909118f_464_464.jpg',
            'channel_url': 'https://www.boomplay.com/artists/52723101',
            'duration': 125.0,
            'release_year': 2024,
            'comment_count': int,
            'like_count': int,
            'repost_count': int,
            'album': 'Legendary Battle',
            'genres': ['Metal'],
        },
    }

    def _real_extract(self, url):
        song_id = self._match_id(url)
        webpage = self._download_webpage(url, song_id)
        ld_json_meta = next(self._yield_json_ld(webpage, song_id), {})
        # schema `MusicRecording` not supported by self._json_ld()
        ld_json_meta.pop('url', None)

        metadata_html = self._get_element_by_class_and_tag('summaryWrap', 'article', webpage) or ''
        metadata_entries = re.findall(r'(?s)<strong>(?P<entry>.*?)</strong>', metadata_html)

        details_section = self._get_element_by_class_and_tag('songDetailInfo', 'section', webpage) or ''
        metadata_entries.extend(re.findall(r'(?is)<li>(?P<entry>.*?)</li>', details_section))
        page_metadata = {
            'title': self._html_search_regex(r'<h1>([^<]+)</h1>', metadata_html, 'title', default=''),
            'thumbnail': self._html_search_meta(['og:image', 'twitter:image'],
                                                webpage, 'thumbnail', default=''),
            'like_count': int_or_none(get_element_by_class('btn_favorite', metadata_html)),
            'repost_count': int_or_none(get_element_by_class('btn_share', metadata_html)),
            'comment_count': int_or_none(get_element_by_class('btn_comment', metadata_html)),
        }

        listify = lambda x: [x]

        def set_page_metadata(k, v):
            setter = {
                'artist': ('artists', listify),
                'album': (None, IDENTITY),
                'genre': ('genres', listify),
                'year of release': ('release_year', int_or_none),
            }.get(k)
            if setter:
                field, setter = setter
                page_metadata[field or k] = setter(v)

        for metadata_entry in traverse_obj(metadata_entries, (
                Ellipsis, T(clean_html), T(lambda s: s.split(':', 1)),
                T(lambda k_v: (k_v[0].lower(), k_v[1].strip())))):
            set_page_metadata(*metadata_entry)

        result = merge_dicts(
            page_metadata,
            traverse_obj(ld_json_meta, {
                'title': 'name',
                'thumbnail': 'image',
                'channel_url': ('byArtist', 0, '@id'),
                'artists': ('byArtist', Ellipsis, 'name'),
                'duration': ('duration', T(parse_duration)),
            }), {
                'id': song_id,
                'formats': self._extract_formats(song_id, 'MUSIC'),
            }, rev=True)
        return merge_dicts({
            'title': result['title'],
        }, result)


class BoomPlayVideoIE(BoomPlayBaseIE):
    _VALID_URL = r'https?://(?:www\.)?boomplay\.com/video/(?P<id>\d+)'
    _TEST = {
        'url': 'https://www.boomplay.com/video/1154892',
        'md5': '1ff0cd88eae37380d69bdff2a146035c',  # was 'd9b67ad333d2292a82922062d065352d',
        'info_dict': {
            'id': '1154892',
            'ext': 'mp4',
            'title': 'Autumn blues',
            'thumbnail': 'https://source.boomplaymusic.com/group10/M00/10/10/2171dee9e1f8452e84021560729edb88.jpg',
            'upload_date': '20241010',
            'timestamp': 1728599214,
            'view_count': int,
            'duration': 177.0,
            'description': 'Autumn blues by Lugo',
        },
        'params': {
            'hls_prefer_native': True,
        },
    }

    def _real_extract(self, url):
        video_id = self._match_id(url)
        webpage = self._download_webpage(url, video_id)
        info = self._search_json_ld(webpage, video_id)
        title = info.pop('title')
        info.pop('url', None)
        return merge_dicts(
            {
                'id': video_id,
                'formats': self._extract_formats(video_id, 'VIDEO', ext='mp4'),
                'title': title,
            }, info,
            rev=True)


class BoomPlayEpisodeIE(BoomPlayBaseIE):
    _VALID_URL = r'https?://(?:www\.)?boomplay\.com/episode/(?P<id>\d+)'
    _TEST = {
        'url': 'https://www.boomplay.com/episode/7132706',
        'md5': 'f26e236b764baa53d7a2cbb7e9ce6dc4',
        'info_dict': {
            'id': '7132706',
            'ext': 'mp3',
            'title': 'Letting Go',
        },
    }

    def _real_extract(self, url):
        ep_id = self._match_id(url)
        webpage = self._download_webpage(url, ep_id)
        return {
            'id': ep_id,
            'formats': self._extract_formats(ep_id, 'EPISODE', vcodec='none'),
            'title': self._mung_title(self._og_search_title(webpage, default=''), fatal=True),
        }


class BoomPlayPodcastIE(BoomPlayBaseIE):
    _VALID_URL = r'https?://(?:www\.)?boomplay\.com/podcasts/(?P<id>\d+)'
    _TEST = {
        'url': 'https://www.boomplay.com/podcasts/5372',
        'playlist_count': 200,
        'info_dict': {
            'id': '5372',
            'title': 'TED Talks Daily',
            'description': 'md5:541182e787ce8fd578c835534c907077',
        },
    }

    def _real_extract(self, url):
        _id = self._match_id(url)
        webpage = self._download_webpage(url, _id)
        song_list = self._get_element_by_class_and_tag('morePart_musics', 'ol', webpage)
        song_list = traverse_obj(re.finditer(
            r'''(?x)
            <(?P<tag>li)
            (?:\s(?:[^>"']|"[^"]*"|'[^']*')*)?
            \sdata-id\s*=\s*(?P<_q>['"]?)(?:(?P<id>\d+))(?P=_q)[^>]*>''',
            song_list),
            (Ellipsis, 0, T(extract_attributes), 'data-id', {
                lambda x: self.url_result(
                    'https://www.boomplay.com/episode/{0}'.format(x), BoomPlayEpisodeIE.ie_key(), x),
            }))
        return self.playlist_result(
            song_list, _id,
            playlist_title=self._mung_title(self._og_search_title(webpage, default='')) or None,
            playlist_description=self._og_search_description(webpage, default=''))


class BoomPlayPlaylistIE(BoomPlayBaseIE):
    _VALID_URL = r'https?://(?:www\.)?boomplay\.com/(?:playlists|artists|albums)/(?P<id>\d+)'
    _TESTS = [{
        'url': 'https://www.boomplay.com/playlists/33792494?from=home',
        'info_dict': {
            'id': '33792494',
        },
        'playlist_count': 10,
    }, {
        'url': 'https://www.boomplay.com/artists/52723101',
        'only_matching': True,
    }]

    def _real_extract(self, url):
        playlist_id = self._match_id(url)
        webpage = self._download_webpage(url, playlist_id)
        json_ld_metadata = next(self._yield_json_ld(webpage, playlist_id), {})
        # schema `MusicGroup` not supported by self._json_ld()
        return self.playlist_result(traverse_obj(
            json_ld_metadata, ('track', Ellipsis, 'url', {
                functools.partial(self.url_result, ie=BoomPlayMusicIE.ie_key()),
            })), playlist_id)
```

</details>
