### ISSUE TITLE
Support Website for https://www.yfsp.tv/play/5l8B13Xfz7B

### ISSUE THREAD

**Issue by jnxyatmjx** [yt-dlp/yt-dlp#11225]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single Video: https://www.yfsp.tv/play/5l8B13Xfz7B

### Provide a description that is worded well enough to be understood

Download from https://www.yfsp.tv/play/5l8B13Xfz7B but site not support. yt-dlp should support this site

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.yfsp.tv/play/5l8B13Xfz7B', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-28-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 6.1-static (setts), ffprobe 6.1-static
[debug] Optional libraries: certifi-2020.06.20, requests-2.25.1, sqlite3-3.34.1, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[generic] Extracting URL: https://www.yfsp.tv/play/5l8B13Xfz7B
[generic] 5l8B13Xfz7B: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 5l8B13Xfz7B: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.yfsp.tv/play/5l8B13Xfz7B
Traceback (most recent call last):
  File "/east/teleg/./yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/east/teleg/./yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "/east/teleg/./yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/east/teleg/./yt-dlp/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.yfsp.tv/play/5l8B13Xfz7B
```

**Comment by grqz** [comment]
![image](https://github.com/user-attachments/assets/d0284a5c-ee60-4f0c-b39c-f5a1da82f00a)
![image](https://github.com/user-attachments/assets/665a0de4-c45a-435e-a26d-e8c9dc8c967f)

it says file not found, am I geo-blocked?

**Comment by jnxyatmjx** [comment]
> ![image](https://private-user-images.githubusercontent.com/173015200/375927090-d0284a5c-ee60-4f0c-b39c-f5a1da82f00a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTAwOTksIm5iZiI6MTcyODcwOTc5OSwicGF0aCI6Ii8xNzMwMTUyMDAvMzc1OTI3MDkwLWQwMjg0YTVjLWVlNjAtNGYwYy1iMzljLWY1YTFkYTgyZjAwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNTA5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGI5Yzk4ZWRhNjY3MWNmNjQyMzBhZTBhMzlmMDU2ZTA0ZmI1YWI3Yzg0Y2M3NDEyYWI2MTkwMGM1N2U5YjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VeEasW1rp0F1iIJQ_UW6zSsA653RdiIAgMLan0cNlRw) ![image](https://private-user-images.githubusercontent.com/173015200/375927139-665a0de4-c45a-435e-a26d-e8c9dc8c967f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTAwOTksIm5iZiI6MTcyODcwOTc5OSwicGF0aCI6Ii8xNzMwMTUyMDAvMzc1OTI3MTM5LTY2NWEwZGU0LWM0NWEtNDM1ZS1hMjZkLWU4YzlkYzhjOTY3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNTA5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjIzMTRlYjkyMDQ5M2M5YmM3YjE1NDcwMDhmNGMwZGQ0NjFhOTIwMjcxYzI3MzQwZjE2MjdhZDYwMjZlNmFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pkIsOx8EVpntharjQISmzMrzoFA-m-JOJQP2KNmr3u0)
> 
> it says file not found, am I geo-blocked?

The above video url maybe always changes, this is the site home page https://www.yfsp.tv

**Comment by Ziyi6** [comment]
> ![image](https://private-user-images.githubusercontent.com/173015200/375927090-d0284a5c-ee60-4f0c-b39c-f5a1da82f00a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5ODg0NTYsIm5iZiI6MTczMTk4ODE1NiwicGF0aCI6Ii8xNzMwMTUyMDAvMzc1OTI3MDkwLWQwMjg0YTVjLWVlNjAtNGYwYy1iMzljLWY1YTFkYTgyZjAwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwMzQ5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWRkYzljODU2MDc1MDgwYTVmYzgwZjk3NGZlZjYyNjc2MzUxM2Y4YTA0ZGFhNjI5ZGE2YjgyZmE5NTk1NjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Rvvlwq07HuIqteWZD5tky2GUzV1wpHNLsTeR64AVvlo) ![image](https://private-user-images.githubusercontent.com/173015200/375927139-665a0de4-c45a-435e-a26d-e8c9dc8c967f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5ODg0NTYsIm5iZiI6MTczMTk4ODE1NiwicGF0aCI6Ii8xNzMwMTUyMDAvMzc1OTI3MTM5LTY2NWEwZGU0LWM0NWEtNDM1ZS1hMjZkLWU4YzlkYzhjOTY3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwMzQ5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDA1YzA2OThmMWMwOTg5MjE1MmIwNWMyMGJhMmE1MzFjY2QxODcyZDhmMTE2MzRjMTY2OGEwOWM3MmIzZTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wCCGbjVVtKhE_eE7x0SSugSScr7JpRhL0INDFTERqDg)
> 
> it says file not found, am I geo-blocked?

An example URL you can find below:
https://www.yfsp.tv/play/ecJJy0t3oOR?id=Spip8DKPFW7

**Comment by dirkf** [comment]
But even https://www.yfsp.tv/ is also showing 404 from the UK. However https://www.iyf.tv/ is not.

**Comment by Ziyi6** [comment]
> But even https://www.yfsp.tv/ is also showing 404 from the UK. However https://www.iyf.tv/ is not.

My first click on the website https://www.yfsp.tv/ is also showing 404, but after pressing F5 to refresh the website, the site goes back to normal, dk the reason

**Comment by dirkf** [comment]
That isn't effective for me.

**Comment by Shchvova** [comment]
Does this work? https://www.yfsp.tv/play/op5OoSphiu4

**Comment by tongyiys1** [comment]
https://www.nezhayy.com

**Comment by gamer191** [comment]
This is definitely a piracy site. Sorry, it won't be supported
