### ISSUE TITLE
https://watch.thechosen.tv/

### ISSUE THREAD

**Issue by chrisarnott86** [yt-dlp/yt-dlp#11246]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://watch.thechosen.tv/video/184683594341

### Provide a description that is worded well enough to be understood

generic extractors do not work

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-F', 'https://watch.thechosen.tv/video/184683594341']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.13.232959 from yt-dlp/yt-dlp-nightly-builds [cba786850] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-45-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.0.7, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.13.232959 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.13.232959 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://watch.thechosen.tv/video/184683594341
[generic] 184683594341: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 184683594341: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://watch.thechosen.tv/video/184683594341
Traceback (most recent call last):
  File "/home/chris/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/chris/.local/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/.local/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2533, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://watch.thechosen.tv/video/184683594341
```

**Comment by bashonly** [comment]
Possibly the same issue as #5478

**Comment by chrisarnott86** [comment]
Definitely a new unique website. The production "The Chosen" is no longer associated with Angel Studios, so the new site "watch.thechosen.tv" is entirely new and separate from any angel studios url.
