### ISSUE TITLE
"[facebook] unable to extract uploader" Can't download video that's Age Restricted

### ISSUE THREAD

**Issue by life777eternal** [yt-dlp/yt-dlp#11278]
Greetings, I have noticed the same problem as #10479. Even after updating it has the same error, and the video is still available to watch on FB. Although it is apparently [age restricted](https://github.com/yt-dlp/yt-dlp/issues/10479#issuecomment-2420543825). When the video is first loaded, it is blurred out and has 

> "Violent or graphic content. This video is covered so people can choose whether they want to see it." 

Didn't actually realize that that means it's age restricted, but it makes sense, it's just that FB doesn't actually spell out there "age restricted" so maybe they use slightly different wordage.

When I tried to open it in a private window, it shows a 'broken link' image, and the following:

> "This Video Isn't Available Anymore
The link may be broken or the video may have been removed. You can explore more videos or try logging into facebook.com and then visiting the link again."

![FB Broken Link](https://github.com/user-attachments/assets/05302d59-04b0-4c51-913b-68485aae6159)

Also I'm not sure if I have the right the right syntax for the `--cookies-from-browser`, when I tried to use it, a pop-over appeared on the screen saying that this app can't run on this PC. 

```
C:\_______>>yt-dlp.exe --cookies-from-browser brave -F https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
Access is denied.
```

```C:\_______>>yt-dlp.exe https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] Extracting URL: https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] 2971407446334915: Downloading webpage
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [facebook] 2971407446334915: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\_______>>yt-dlp.exe -U
Current version: stable@2024.08.06 from yt-dlp/yt-dlp
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
Current Build Hash: 468a6f8bf1d156ad173e000a40f696d4fbd69c5aa7360229329b9063a388e7d0
Updating to stable@2024.10.07 from yt-dlp/yt-dlp ...
Updated yt-dlp to stable@2024.10.07 from yt-dlp/yt-dlp

C:\_______>>yt-dlp.exe https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] Extracting URL: https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] 2971407446334915: Downloading webpage
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [facebook] 2971407446334915: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\_______>>yt-dlp.exe "https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915"
[facebook] Extracting URL: https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] 2971407446334915: Downloading webpage
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [facebook] 2971407446334915: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

Thank you, Shalom. 

```C:\_______>>yt-dlp.exe https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915 --list-formats -v
[debug] Command-line config: ['https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915', '--list-formats', '-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 7.0.2-essentials_build-www.gyan.dev (setts), ffprobe 7.0.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[facebook] Extracting URL: https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] 2971407446334915: Downloading webpage
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [facebook] 2971407446334915: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2847, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1123, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 2971407446334915: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

_Originally posted by @life777eternal in https://github.com/yt-dlp/yt-dlp/issues/10479#issuecomment-2420346587_

**Comment by gamer191** [comment]
> Also I'm not sure if I have the right the right syntax for the --cookies-from-browser, when I tried to use it, a pop-over appeared on the screen saying that this app can't run on this PC.

How strange. Did you run it in the same command prompt window as the other commands?

**Comment by life777eternal** [comment]
Aye @gamer191 it was in the same window as all the others, and not running as administrator, then I opened another as administrator, with the same result.

**Comment by nikalasmd** [comment]
@bashonly 
The same error occurs, but the video is opened in the browser without authorization.
![image](https://github.com/user-attachments/assets/060b705c-498f-4478-b968-d76f3d3c70f1)


yt-dlp -vU https://www.facebook.com/reel/510163451947976/?mibextid=ZZyLBr
[debug] Command-line config: ['-vU', 'https://www.facebook.com/reel/510163451947976/?mibextid=ZZyLBr']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip)
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.32.3, sqlite3-3.39.4, urllib3-2.0.5, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/510163451947976/?mibextid=ZZyLBr
[facebook] Extracting URL: https://m.facebook.com/watch/?v=510163451947976&_rdr
[facebook] 510163451947976: Downloading webpage
ERROR: [facebook] 510163451947976: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2846, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1122, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [facebook] 510163451947976: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by bashonly** [comment]
@nikalasmd unrelated to this issue. you are experiencing:
- https://github.com/yt-dlp/yt-dlp/issues/11337

which has been fixed in master. [see how to update to master with pip](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master)

**Comment by theoratkin** [comment]
Same issue with private videos, despite specifying the `--cookies-from-browser` option.
