### ISSUE TITLE
Add support for palestinefilminstitute.org.

### ISSUE THREAD

**Issue by clusterized** [yt-dlp/yt-dlp#11282]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video: https://www.palestinefilminstitute.org/en/aftermath
- Playlist: https://www.palestinefilminstitute.org/en/provoked-narratives

### Provide a description that is worded well enough to be understood

[Embed link](https://cdn.palestinefilminstitute.org/watch/8a53509aefaf4b34a0f82b15463390cd/)

A downloadable m3u8 URL can be extracted with [_The Stream Detector_](https://addons.mozilla.org/firefox/addon/hls-stream-detector):
https://cdn.palestinefilminstitute.org/share/hls.m3u8?token=8a53509aefaf4b34a0f82b15463390cd

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.palestinefilminstitute.org/en/aftermath']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds [fbc66e3ab] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-8.1-6.3.9600-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3, ffprobe 2022-07-24-git-39a538f430-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.palestinefilminstitute.org/en/aftermath
[generic] aftermath: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] aftermath: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.palestinefilminstitute.org/en/aftermath
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\generic.py", line 2533, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.palestinefilminstitute.org/en/aftermath


# Using the extracted m3u8 URL
[debug] Command-line config: ['-vU', '--ffmpeg-location', 'C:\\Program Files\\ffmpeg-master-latest-win64-gpl\\bin', 'https://cdn.palestinefilminstitute.org/share/hls.m3u8?token=8a53509aefaf4b34a0f82b15463390cd']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds [fbc66e3ab] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-8.1-6.3.9600-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-115155-ge4da96c6b2-20240509 (setts), ffprobe N-115155-ge4da96c6b2-20240509
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://cdn.palestinefilminstitute.org/share/hls.m3u8?token=8a53509aefaf4b34a0f82b15463390cd
[generic] hls: Downloading webpage
[debug] Identified a direct video link
[generic] hls: Downloading m3u8 information
[generic] hls: Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] hls: Downloading 1 format(s): 4580
[debug] Invoking hlsnative downloader on "https://cdn2.palestinefilminstitute.org/share/hls-1080p.m3u8?token=8a53509aefaf4b34a0f82b15463390cd"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 438
[download] Destination: hls [hls].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of  736.03MiB in 00:06:29 at 1.89MiB/s
[debug] ffprobe command line: "C:\Program Files\ffmpeg-master-latest-win64-gpl\bin\ffprobe" -hide_banner -show_format -show_streams -print_format json "file:hls [hls].mp4"
[debug] ffmpeg command line: "C:\Program Files\ffmpeg-master-latest-win64-gpl\bin\ffprobe" -show_streams "file:hls [hls].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "hls [hls].mp4"
[debug] ffmpeg command line: "C:\Program Files\ffmpeg-master-latest-win64-gpl\bin\ffmpeg" -y -loglevel repeat+info -i "file:hls [hls].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart "file:hls [hls].temp.mp4"
```

**Comment by dirkf** [comment]
Tactic for single video:
* find the src of the iframe that matches https://cdn.palestinefilminstitute.org/watch/...
* replace `/watch/' with `/share/hls.m3u8?token=`
* extract formats (subtitles?) from that URL
* return formats together with any other metadata from `og:...` `<meta>` elements and from the `div.sqs-html-content` element (description, or parse it for other data).

For the playlist, set `_EMBED_REGEX` or specialise `_extract_embed_urls()` to extract URLs from the `href` vaklues in the `div.slide a[href]` CSS selector.
