### ISSUE TITLE
Regex for dropbox doesn't support https://dropbox.com/scl/fo URL format

### ISSUE THREAD

**Issue by metronidazole** [yt-dlp/yt-dlp#11283]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

World

### Provide a description that is worded well enough to be understood

The current dropbox extract supports dropbox URLs in the format of "https://www.dropbox.com/scl/fi/"  however dropbox also uses the same video player on urls of the format of "https://www.dropbox.com/scl/fo"

The current regex for dropbox does not match this URL type and falls back to the generic extractor which fails.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.dropbox.com/scl/fo/z1o95jkbbnkmoc9gvirzw/h?e=2&preview=WJBK_12-09-2022_07.44.15.mp4&rlkey=6xx9whg0h81afi1z7cwlunvx8&dl=0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds (linux_exe)
[debug] Python 3.11.10 (CPython x86_64 64bit) - Linux-6.11.2-arch1-1-x86_64-with (OpenSSL 3.1.7 3 Sep 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.dropbox.com/scl/fo/z1o95jkbbnkmoc9gvirzw/h?e=2&preview=WJBK_12-09-2022_07.44.15.mp4&rlkey=6xx9whg0h81afi1z7cwlunvx8&dl=0
[generic] h?e=2&preview=WJBK_12-09-2022_07.44.15: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] h?e=2&preview=WJBK_12-09-2022_07.44.15: Extracting information
[debug] Looking for embeds
[redirect] Following redirect to https://www.dropbox.com/scl/fo/z1o95jkbbnkmoc9gvirzw/h?dl=0&e=2&noscript=1&preview=WJBK_12-09-2022_07.44.15.mp4&rlkey=6xx9whg0h81afi1z7cwlunvx8
[generic] Extracting URL: https://www.dropbox.com/scl/fo/z1o95jkbbnkmoc9gvirzw/h?dl=0&e=2&noscript=1&preview=WJBK_12-09-2022_07.44.15.mp4&rlkey=6xx9whg0h81afi1z7cwlunvx8
[generic] h?dl=0&e=2&noscript=1&preview=WJBK_12-09-2022_07.44.15: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] h?dl=0&e=2&noscript=1&preview=WJBK_12-09-2022_07.44.15: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.dropbox.com/scl/fo/z1o95jkbbnkmoc9gvirzw/h?dl=0&e=2&noscript=1&preview=WJBK_12-09-2022_07.44.15.mp4&rlkey=6xx9whg0h81afi1z7cwlunvx8
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp/extractor/common.py", line 741, in extract
  File "yt_dlp/extractor/generic.py", line 2533, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.dropbox.com/scl/fo/z1o95jkbbnkmoc9gvirzw/h?dl=0&e=2&noscript=1&preview=WJBK_12-09-2022_07.44.15.mp4&rlkey=6xx9whg0h81afi1z7cwlunvx8
```

**Comment by bashonly** [comment]
another workaround is changing `dl=0` to `dl=1` in the url
