### ISSUE TITLE
Add support for Anime Onegai

### ISSUE THREAD

**Issue by Rodrigo-017** [yt-dlp/yt-dlp#11294]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Latin America

### Example URLs

[Anime Onegai (Spanish)](https://www.animeonegai.com/es/landing)
[Anime Onegai (Portuguese)](https://www.animeonegai.com/pt/landing)

### Provide a description that is worded well enough to be understood

A Latin American paid anime streaming site.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.animeonegai.com/pt/watch/vVqDkyopdYybzc8PB?serie=true']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (pip)
[debug] Python 3.12.1 (CPython x86_64 64bit) - macOS-11.7.10-x86_64-i386-64bit (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg N-109963-g912ac82a3c-tessus (setts), ffprobe 5.0.1-tessus, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.43.1, urllib3-2.2.1, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.animeonegai.com/pt/watch/vVqDkyopdYybzc8PB?serie=true
[generic] vVqDkyopdYybzc8PB?serie=true: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2384, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 910, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 897, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 4172, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/networking/_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by grqz** [comment]
That's 403'ed. Can you play the video in your browser _from the same ip_ (use the same machine)?

**Comment by Rodrigo-017** [comment]
> That's 403'ed. Can you play the video in your browser _from the same ip_ (use the same machine)?

Yes, I can.

**Comment by bashonly** [comment]
The 403 is from cloudflare anti-bot. But can confirm that with curl_cffi installed, the generic extractor still does not work on this site

**Comment by Rodrigo-017** [comment]
I finally got around the anti-bot thing.
`[debug] Command-line config: ['-vF', 'https://www.animeonegai.com/pt/watch/vVqDkyopdYybzc8PB?serie=true']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-10-13-git-e347b4ff31-essentials_build-www.gyan.dev (setts), ffprobe 2024-10-13-git-e347b4ff31-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[generic] Extracting URL: https://www.animeonegai.com/pt/watch/vVqDkyopdYybzc8PB?serie=true
[generic] vVqDkyopdYybzc8PB?serie=true: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] vVqDkyopdYybzc8PB?serie=true: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.animeonegai.com/pt/watch/vVqDkyopdYybzc8PB?serie=true
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1760, in __extract_info
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\generic.py", line 2533, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.animeonegai.com/pt/watch/vVqDkyopdYybzc8PB?serie=true`

**Comment by Rodrigo-017** [comment]
I finally got around the anti-bot thing.

```
[debug] Command-line config: ['-vF', 'https://www.animeonegai.com/pt/watch/vVqDkyopdYybzc8PB?serie=true']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-10-13-git-e347b4ff31-essentials_build-www.gyan.dev (setts), ffprobe 2024-10-13-git-e347b4ff31-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[generic] Extracting URL: https://www.animeonegai.com/pt/watch/vVqDkyopdYybzc8PB?serie=true
[generic] vVqDkyopdYybzc8PB?serie=true: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] vVqDkyopdYybzc8PB?serie=true: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.animeonegai.com/pt/watch/vVqDkyopdYybzc8PB?serie=true
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1760, in __extract_info
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\generic.py", line 2533, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.animeonegai.com/pt/watch/vVqDkyopdYybzc8PB?serie=true
```
