### ISSUE TITLE
[NPR] Tiny Desk Concerts, some urls not working

### ISSUE THREAD

**Issue by yroyathon** [yt-dlp/yt-dlp#11299]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Regarding urls found on the page https://www.npr.org/series/tiny-desk-concerts/ ...
This url does not work with yt-dlp ( https://www.npr.org/2024/05/20/1250056328/tiny-desk-concert-bob-james ) nor do similar urls earlier in 2024, going by the date in the url.
As an example, this url does work ( https://www.npr.org/2024/05/24/g-s1-276/tiny-desk-concert-nelly-furtado ) as well as all the urls newer than this on the page all the way to the present.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.npr.org/2024/05/20/1250056328/tiny-desk-concert-bob-james']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.8.0-45-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2024.06.02, mutagen-1.45.1, pyxattr-0.7.2, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.1, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
[Npr] Extracting URL: https://www.npr.org/2024/05/20/1250056328/tiny-desk-concert-bob-james
[Npr] 1250056328: Downloading JSON metadata
ERROR: can only concatenate list (not "dict") to list
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/home/username/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/home/username/.local/lib/python3.10/site-packages/yt_dlp/extractor/npr.py", line 77, in _real_extract
    for media in story.get('audio', []) + story.get('multimedia', []):
TypeError: can only concatenate list (not "dict") to list
```

**Comment by bashonly** [comment]
This should fix it:

```diff
diff --git a/yt_dlp/extractor/npr.py b/yt_dlp/extractor/npr.py
index 06103ff38..a31d2b283 100644
--- a/yt_dlp/extractor/npr.py
+++ b/yt_dlp/extractor/npr.py
@@ -74,11 +74,11 @@ def _real_extract(self, url):
         quality = qualities(KNOWN_FORMATS)
 
         entries = []
-        for media in story.get('audio', []) + story.get('multimedia', []):
+        for media in traverse_obj(story, (('audio', 'multimedia'), all, lambda _, v: v['id'])):
             media_id = media['id']
 
             formats = []
-            for format_id, formats_entry in media.get('format', {}).items():
+            for format_id, formats_entry in traverse_obj(media, ('format', {dict.items}, ...)):
                 if not formats_entry:
                     continue
                 if isinstance(formats_entry, list):
@@ -104,7 +104,7 @@ def _real_extract(self, url):
                             'format_id': format_id,
                             'quality': quality(format_id),
                         })
-            for stream_id, stream_entry in media.get('stream', {}).items():
+            for stream_id, stream_entry in traverse_obj(media, ('stream', {dict.items}, ...)):
                 if not isinstance(stream_entry, dict):
                     continue
                 if stream_id != 'hlsUrl':
@@ -123,10 +123,12 @@ def _real_extract(self, url):
 
             entries.append({
                 'id': media_id,
-                'title': media.get('title', {}).get('$text') or playlist_title,
-                'thumbnail': media.get('altImageUrl', {}).get('$text'),
-                'duration': int_or_none(media.get('duration', {}).get('$text')),
+                'title': playlist_title,
                 'formats': formats,
+                **traverse_obj(media, {
+                    'thumbnail': ('altImageUrl', '$text', {url_or_none}),
+                    'duration': ('duration', '$text', {int_or_none}),
+                }),
             })
 
         return self.playlist_result(entries, playlist_id, playlist_title)

```

**Comment by yroyathon** [comment]
Looks like it works, thank you!

**Comment by AnandCode2004** [comment]
import requests

def check_url(url):
    """Check if a given URL is valid (returns status code 200)."""
    try:
        response = requests.get(url)
        # If status code is 200, URL is working
        if response.status_code == 200:
            print(f"URL works: {url}")
            return True
        else:
            print(f"URL does not work (Status Code: {response.status_code}): {url}")
            return False
    except requests.exceptions.RequestException as e:
        print(f"Error accessing {url}: {e}")
        return False

def fix_broken_urls(url_list):
    """Iterate over the list of URLs, checking each and fixing broken ones."""
    for url in url_list:
        if not check_url(url):
            print(f"Trying to fix broken URL: {url}")
            # Logic to replace or fix the URL (implement based on your patterns)
            # You can use heuristics, backups, or alternative sources to fix the URL
            # Example: if URL has a common pattern or versioning issue, attempt to fix
            fixed_url = try_fixing_url(url)
            if fixed_url and check_url(fixed_url):
                print(f"Fixed URL: {fixed_url}")
            else:
                print(f"Unable to fix URL: {url}")

def try_fixing_url(url):
    """Implement logic to attempt fixing the broken URL."""
    # Example: If URLs follow a common pattern (like version numbers), try replacing parts of it
    # This is a dummy function, customize this according to how URLs might be fixed
    # You can use regex, change parts of the URL, etc.
    new_url = url.replace("version1", "version2")  # Replace this with real logic
    return new_url

# Example list of URLs (some working, some broken)
urls = [
    "https://www.npr.org/working-url",
    "https://www.npr.org/broken-url",
    "https://www.npr.org/another-broken-url"
]

# Run the function to check and fix URLs
fix_broken_urls(urls)

**Comment by alexzapatka** [comment]
the patch works well for me but there are still issue with other url's.  they now give me a "dict" error.

example URL's:
https://www.npr.org/2024/04/26/1246339476/tiny-desk-concert-ne-yo
https://www.npr.org/2024/03/21/1238815351/tiny-desk-concert-chappell-roan
https://www.npr.org/2024/03/15/1238534316/justin-timberlake-tiny-desk-concert

**Comment by bashonly** [comment]
@alexzapatka are you sure you applied the patch completely? I see that error with unpatched yt-dlp master but not with the patch applied

**Comment by alexzapatka** [comment]
> @alexzapatka are you sure you applied the patch completely? I see that error with unpatched yt-dlp master but not with the patch applied. (Don't manually edit the extractor; clone the repo, copy/paste the diff to a file e.g. `npr.patch`, and run `git apply npr.patch`)

it must have been me... i deleted the source tree and reapplied the patch and rebuilt it, and it is working great now.  thanks!!
