### ISSUE TITLE
YouTube: unable to download video data: HTTP Error 403: Forbidden (with Proxy)

### ISSUE THREAD

**Issue by ash-ishh** [yt-dlp/yt-dlp#11304]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Getting `403: Forbidden` in middle of YouTube Download since 16th October 2024 while using proxy (by https://www.zyte.com/).

Getting similar error after switching to `m3u8` protocol instead of `http` and download is super slow.
```shell
[download]   0.2% of ~ 184.67MiB at  102.87KiB/s ETA 09:35 (frag 4/1631)[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 5 (1/10)...
```

Here is the `--print-traffic` log of the failing request
```shell
director: Checking if "requests" supports this request.
director: Sending request via "requests"
requests: Resetting dropped connection: rr5---sn-najern7r.googlevideo.com
requests: Starting new HTTPS connection (3): rr5---sn-najern7r.googlevideo.com:443
send: b'CONNECT rr5---sn-najern7r.googlevideo.com:443 HTTP/1.1\r\nProxy-Authorization: Basic {TOKEN_REDACTED}\r\nHost: rr5---sn-najern7r.googlevideo.com:443\r\n\r\n'
header:

send: b'GET /videoplayback?expire=1729558777&ei=maQWZ4S8F7ia2_gP7OTK0A0&ip=154.16.1.233&id=o-AFt0XCL6ZQojQDYi6kmO2ok_Kn9Rp9Ic1zN4A4VMOgYj&itag=136&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1729537177%2C&mh=yx&mm=31%2C26&mn=sn-najern7r%2Csn-o097znsr&ms=au%2Conr&mv=u&mvi=5&pl=24&rms=au%2Cau&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=190775140&dur=8944.099&lmt=1728946351464353&mt=1729534770&fvip=4&keepalive=yes&fexp=51312688&c=IOS&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgG4GMwAEFAQJPRienCpGNJZvxnNUcWN_xQHeNgUp0bgYCIF0i2iuJlmD4QZJ2jyTsWybOQhTikQqlvt_viVWOMarg&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms&lsig=ACJ0pHgwRQIgW36q1QLPSVp3FuaBPZwlCtjL0NWTNRaUBdQ17BsNqyECIQDRQ7TLsmlULVJow07YJILOYt8NbZvbtMuuZAcwiarzCg%3D%3D HTTP/1.1\r\nHost: rr5---sn-najern7r.googlevideo.com\r\nConnection: keep-alive\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nAccept-Encoding: identity\r\nRange: bytes=9797568-19974536\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Zyte-Request-Id: dc9450ac-0ecb-4d9c-ba82-a4aa05e224c0
header: transfer-encoding: chunked
header: Server: gvs 1.0
header: X-Content-Type-Options: nosniff
header: Vary: Origin
header: Last-Modified: Wed, 02 May 2007 10:26:10 GMT
header: Cross-Origin-Resource-Policy: cross-origin
header: Date: Mon, 21 Oct 2024 19:00:41 GMT
header: Content-Type: text/plain
header: connection: close
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

I checked below similar issues but didn't find the solution:

- https://github.com/yt-dlp/yt-dlp/issues/11204
- https://github.com/yt-dlp/yt-dlp/issues/11169
- https://github.com/yt-dlp/yt-dlp/issues/10961
- https://github.com/yt-dlp/yt-dlp/issues/10790
- https://github.com/yt-dlp/yt-dlp/issues/10599
- https://github.com/yt-dlp/yt-dlp/issues/10562
- https://github.com/yt-dlp/yt-dlp/issues/10397

YouTube DL issue:
- https://github.com/ytdl-org/youtube-dl/issues/32905 (tried suggested mobile UA and m.youtube.com, it didn't work)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --no-check-certificate -S height:720,ext:mp4,protocol:https --proxy http://{REDACTED_PROXY_SERVER}/ https://m.youtube.com/watch?v=oFfVt3S51T4
[debug] Command-line config: ['-vU', '--no-check-certificate', '-S', 'height:720,ext:mp4,protocol:https', '--proxy', '{REDACTED_PROXY_SERVER}', 'https://m.youtube.com/watch?v=oFfVt3S51T4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds [fbc66e3ab] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-1017-aws-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, requests-2.32.3, sqlite3-3.45.1, urllib3-1.26.18, websockets-13.1
[debug] Proxy map: {'all': '{REDACTED_PROXY_SERVER}'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
Current version: nightly@2024.10.16.232911 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.10.20.232914 from yt-dlp/yt-dlp-nightly-builds
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube] Extracting URL: https://m.youtube.com/watch?v=oFfVt3S51T4
[youtube] oFfVt3S51T4: Downloading webpage
[youtube] oFfVt3S51T4: Downloading ios player API JSON
[youtube] oFfVt3S51T4: Downloading mweb player API JSON
[debug] Loading youtube-nsig.606a66b3 from cache
[debug] [youtube] Decrypted nsig F38nbALYuEIg4lR => C-eWEO3uQ7KQxw
[debug] Loading youtube-nsig.606a66b3 from cache
[debug] [youtube] Decrypted nsig lbDqXmysyhpyv22 => p1l61atDyFrieA
[youtube] oFfVt3S51T4: Downloading m3u8 information
        [debug] Sort order given by user: height:720, ext:mp4, protocol:https
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, height:720(720.0), vext:mp4(6), aext, proto:https(10), quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, size, br, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] oFfVt3S51T4: Downloading 1 format(s): 136+140
[debug] Invoking http downloader on "https://rr4---sn-q4fl6n6y.googlevideo.com/videoplayback?expire=1729556442&ei=epsWZ4EMlOjJuA-y1_igDg&ip=84.46.235.54&id=o-AHF78ZVSgv50GoWRKrDpG-EEE4DPyNXvvdMr1SFyK12Q&itag=136&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1729534842%2C&mh=yx&mm=31%2C26&mn=sn-q4fl6n6y%2Csn-p5qlsnd6&ms=au%2Conr&mv=u&mvi=4&pl=24&rms=au%2Cau&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=190775140&dur=8944.099&lmt=1728946351464353&mt=1729533161&fvip=1&keepalive=yes&fexp=51312688&c=IOS&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAPz-c5ypkbsLv1N_uH2minAXZOIjcBQDcP-AW-oK_sqOAiEA-xRhajjwmsSwOxxZKTWtVcasxTsQEHW5MGb_VrXAWCg%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms&lsig=ACJ0pHgwRgIhANC3Q06VBj1HF-KaSsOdA4rErgAcILID8t1C9EBtkFxwAiEA231112yqQRvY733VVMy1fEy2TKKWTVXgGseeJL3fD5k%3D"
[download] Destination: Cursor Team： Future of Programming with AI ｜ Lex Fridman Podcast #447 [oFfVt3S51T4].f136.mp4
[download]   1.8% of  181.94MiB at  115.81KiB/s ETA 26:19ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3465, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3203, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 4177, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/networking/_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
> reply: 'HTTP/1.1 403 Forbidden\r\n'
> header: **Zyte-Request-Id**: dc9450ac-0ecb-4d9c-ba82-a4aa05e224c0

are you sure the 403 isn't coming from the proxy?

**Comment by ash-ishh** [comment]
It might not be coming from the proxy since video download is getting initiated and randomly after some progress (`Range: bytes=9797568-19974536` in above example) 403 is coming which it might be passing from YouTube's response.

I have raised the issue with Zyte too to confirm (will share the finding here once I get the revert)

Can it be the case YouTube is detecting proxy as bot after some time and giving 403?

Any suggetion on how to confirm if 403 is by proxy or googlevideo.com?

**Comment by ash-ishh** [comment]
```bash
yt-dlp -v -S height:720,ext:mp4,protocol:https --compat-options no-certifi --proxy https://{API_KEY}:@api.zyte.com:8014/ https://m.youtube.com/watch?v=oFfVt3S51T4
[debug] Command-line config: ['-v', '-S', 'height:720,ext:mp4,protocol:https', '--compat-options', 'no-certifi', '--proxy', 'https://{API_KEY}:@api.zyte.com:8014/', 'https://m.youtube.com/watch?v=oFfVt3S51T4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip)
[debug] Compatibility options: no-certifi
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-1017-aws-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2024.08.30, curl_cffi-0.7.3 (unsupported), mutagen-1.46.0, requests-2.32.3, sqlite3-3.45.1, urllib3-1.26.18, websockets-13.1
[debug] Proxy map: {'all': 'https://{API_KEY}:@api.zyte.com:8014/'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[youtube] Extracting URL: https://m.youtube.com/watch?v=oFfVt3S51T4
[youtube] oFfVt3S51T4: Downloading webpage
[youtube] oFfVt3S51T4: Downloading ios player API JSON
[youtube] oFfVt3S51T4: Downloading mweb player API JSON
[debug] Loading youtube-nsig.a62d836d from cache
[debug] [youtube] Decrypted nsig Nx_W2TjTIuRUEX7ej => oPfBQDoKgh4eJw
[debug] Loading youtube-nsig.a62d836d from cache
[debug] [youtube] Decrypted nsig C0nq_xzxycxP20Fm0 => R2W7gdGx5Z6BGQ
[youtube] oFfVt3S51T4: Downloading m3u8 information
[debug] Sort order given by user: height:720, ext:mp4, protocol:https
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, height:720(720.0), vext:mp4(6), aext, proto:https(10), quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, size, br, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] oFfVt3S51T4: Downloading 1 format(s): 136+140
[debug] Invoking http downloader on "https://rr3---sn-hp57kndy.googlevideo.com/videoplayback?expire=1729726949&ei=hTUZZ82KHYWfj-8Pysn0gQg&ip=173.46.84.32&id=o-AEVG_cZg5GTm8B2ETkRa9bfkIvImUqQ7aMqOyl2KLWOI&itag=136&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1729705349%2C&mh=yx&mm=31%2C29&mn=sn-hp57kndy%2Csn-hp57ynss&ms=au%2Crdu&mv=u&mvi=3&pl=24&rms=au%2Cau&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=190775140&dur=8944.099&lmt=1728946351464353&mt=1729703775&fvip=2&keepalive=yes&fexp=51312688%2C51326932&c=IOS&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAM2TcELl-wwadvjn3-F5WFDkBEpjDgEDvt6nhf0EJsGgAiAGyiDO6mpKinimaP35xb74Src5-PM6PtT9JcDy1aOUZA%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms&lsig=ACJ0pHgwRgIhAK945mkbSIs6boMVigByvz5-Q_CUxbPjI9L4CGPKcpVaAiEA1wvCo1DK4UuPX4yERaKpoDTn5pGzTDCwUdZLIFPlbgA%3D"
[download] Destination: Cursor Team： Future of Programming with AI ｜ Lex Fridman Podcast #447 [oFfVt3S51T4].f136.mp4
[download]   2.1% of  181.94MiB at  142.98KiB/s ETA 21:16ERROR: unable to download video data: HTTP Error 403: Forbidden

Traceback (most recent call last):
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3464, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3202, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/test/venv/lib/python3.12/site-packages/yt_dlp/networking/_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

@gamer191 verbose log without `--no-check-certificate`

**Comment by ash-ishh** [comment]
Zyte has `Zyte-Session-ID`  header option [1]
```
When sending follow-up requests with the same session ID, the created session will be reused, i.e. all requests will share the same IP address, network stack, cookie jar, etc. [2]
```

This header seems to be working and I haven't faced the same issue again.
Though there are some other errors coming like `detected as bot, please sign in` before starting the download, which is easily resolved by retry.
Which make me think the original error might be because of rotated IP might be being detected as a bot. [needs verification]

Also, I found `Zyte-Geolocation` helpful for setting the region closest to the machine for better speed.

Command with headers: 
```bash
yt-dlp --no-check-certificate --proxy http://{API_KEY}:@api.zyte.com:8011/ --add-headers "Zyte-Geolocation:{REGION}" --add-headers "Zyte-Session-ID:{UUID}" https://www.youtube.com/watch?v=xxxx
```

if the same issue occurs in other proxy providers equivalent of session id can be tried. 

I will observe it for few days and will close the issue if it does not reoccur.

[1] - https://docs.zyte.com/zyte-api/usage/proxy-mode.html#zyte-session-id
[2] - https://docs.zyte.com/zyte-api/usage/features.html#client-managed-sessions
[3] - https://docs.zyte.com/zyte-api/usage/proxy-mode.html#zyte-geolocation
