### ISSUE TITLE
SponsorBlock API; certificate verify failed

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#1130]
## Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Windows\System32>dlp -v https://www.youtube.com/watch?v=eQ_8F4nzyiw
[debug] User config file: C:\Users\Nico\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['-i', '--no-mtime', '-o', '~/Desktop/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--embed-thumbnail', '--add-metadata', '--external-downloader', 'aria2c', '--external-downloader-args', 'aria2c:-x 10 -s 10 -j 10 -k 1M --log-level=info --file-allocation=none', '--sponsorblock-remove', 'all']
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=eQ_8F4nzyiw']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.25 (exe)
[debug] Python version 3.9.3 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-09-22-git-447cf53774-essentials_build-www.gyan.dev, ffprobe 2021-09-22-git-447cf53774-essentials_build-www.gyan.dev
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=eQ_8F4nzyiw
[youtube] eQ_8F4nzyiw: Downloading webpage
[youtube] eQ_8F4nzyiw: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/3cce?service=YouTube&categories=%5B%22sponsor%22%2C+%22intro%22%2C+%22outro%22%2C+%22interaction%22%2C+%22preview%22%2C+%22music_offtopic%22%2C+%22selfpromo%22%5D
ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)>
Traceback (most recent call last):
  File "urllib\request.py", line 1346, in do_open
  File "http\client.py", line 1253, in request
  File "http\client.py", line 1299, in _send_request
  File "http\client.py", line 1248, in endheaders
  File "http\client.py", line 1008, in _send_output
  File "http\client.py", line 948, in send
  File "http\client.py", line 1422, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1265, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1315, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2272, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3043, in pre_process
  File "yt_dlp\YoutubeDL.py", line 2996, in run_pp
  File "yt_dlp\postprocessor\sponsorblock.py", line 36, in run
  File "yt_dlp\postprocessor\sponsorblock.py", line 40, in _get_sponsor_chapters
  File "yt_dlp\postprocessor\sponsorblock.py", line 82, in _get_sponsor_segments
  File "yt_dlp\postprocessor\sponsorblock.py", line 90, in _get_json
  File "yt_dlp\YoutubeDL.py", line 3256, in urlopen
  File "urllib\request.py", line 517, in open
  File "urllib\request.py", line 534, in _open
  File "urllib\request.py", line 494, in _call_chain
  File "yt_dlp\utils.py", line 2834, in https_open
  File "urllib\request.py", line 1349, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)>


```

## Description

In my Windows 10 VM I got the error above.
Don't know if this is somehow related to the other, now closed issues about certificate errors.

I was able to work around it by manually importing the certificate of `https://sponsor.ajay.app/`
(from opening the site in Internet Explorer as admin...)
After that the download and segment skipping succeeded.

However, this certificate expires 20211101.
Do I have to repeat this workaround then?

**Comment by pukkandan** [comment]
Its not related to the other issue and not really related to yt-dlp at all. It's better to ask this in https://github.com/ajayyy/SponsorBlock or https://github.com/ajayyy/SponsorBlockServer.

You can use `--no-check-certificate` as a workaround

**Comment by nicolaasjan** [comment]
> and not really related to yt-dlp at all

Yeah, I was already suspecting that. Sorry.
