### ISSUE TITLE
The album listing data is incomplete

### ISSUE THREAD

**Issue by fukangzhang** [yt-dlp/yt-dlp#11327]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

![ximalaya](https://github.com/user-attachments/assets/69463f7a-e48b-4f98-bb98-534b547e2961)
For each album, the number of downloaded videos is always incomplete. The total number was 915, but only 90 were downloaded

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', '--dump-single-json', 'https://www.ximalaya.com/album/68192729']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip)
[debug] Python 3.12.7 (CPython x86_64 64bit) - Linux-5.4.160-3.el7.x86_64-x86_64-with-glibc2.31 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[debug] Using fake IP 36.175.239.82 (CN) as X-Forwarded-For
[ximalaya:album] Extracting URL: https://www.ximalaya.com/album/68192729
[ximalaya:album] 68192729: Downloading tracks list page 1
[download] Downloading playlist: 秀才家的小娇妻｜甜宠轻松&爆笑宅斗｜免费多人有声剧
[ximalaya:album] 68192729: Downloading tracks list page 2
[ximalaya:album] 68192729: Downloading tracks list page 3
[ximalaya:album] 68192729: Downloading tracks list page 4
[ximalaya:album] Playlist 秀才家的小娇妻｜甜宠轻松&爆笑宅斗｜免费多人有声剧: Downloading 90 items of 90
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 90
```

**Comment by fukangzhang** [comment]
@xingchensong 宋老师可以帮忙解决下这个问题吗？万分感谢

**Comment by 4ft35t** [comment]
The API of get album info `https://www.ximalaya.com/revision/album/v1/getTracksList` is now protected with a custom headers `xm-sign`, can't get playlist.

```bash
yt-dlp -v https://www.ximalaya.com/album/68192729 -j
[debug] Command-line config: ['-v', 'https://www.ximalaya.com/album/68192729', '-j']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539]
[debug] Python 3.12.7 (CPython x86_64 64bit) - Linux-5.15.173-1-MANJARO-x86_64-with-glibc2.40 (OpenSSL 3.4.0 22 Oct 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1, rtmpdump 2.4
[debug] Optional libraries: brotli-1.1.0, certifi-2024.08.30, requests-2.32.3, sqlite3-3.47.2, urllib3-1.26.20
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[debug] Using fake IP 36.183.2.151 (CN) as X-Forwarded-For
[ximalaya:album] Extracting URL: https://www.ximalaya.com/album/68192729
[ximalaya:album] 68192729: Downloading tracks list page 1
ERROR: division by zero
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1759, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/ximalaya.py", line 226, in _real_extract
    page_count = math.ceil(first_page['trackTotalCount'] / first_page['pageSize'])
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

**Comment by 4ft35t** [comment]
According to https://github.com/yt-dlp/yt-dlp/pull/12048#issuecomment-2677101785 
The API of get VIP tracks is broken. `mpay.ximalaya.com` return 
`{"ret":999,"msg":"账号异常，请咨询客服","seed":0}`

`https://www.ximalaya.com/mobile-playpage/track/v3/baseInfo/` can get  VIP track info, but protected by `xm-sign`

**Comment by wwfcnu** [comment]
有相关的更新吗，好像还是不能采集
`(base) yt-dlp "https://www.ximalaya.com/album/47769867"
[ximalaya:album] Extracting URL: https://www.ximalaya.com/album/47769867
[ximalaya:album] 47769867: Downloading tracks list page 1
ERROR: division by zero`

**Comment by 4ft35t** [comment]
> 有相关的更新吗，好像还是不能采集 `(base) yt-dlp "https://www.ximalaya.com/album/47769867" [ximalaya:album] Extracting URL: https://www.ximalaya.com/album/47769867 [ximalaya:album] 47769867: Downloading tracks list page 1 ERROR: division by zero`

try this

```bash
git clone https://github.com/4ft35t/yt-dlp.git && cd yt-dlp && git checkout fix-ximalaya-album
./yt-dlp.sh https://www.ximalaya.com/album/47769867
```

**Comment by wwfcnu** [comment]
> > 有相关的更新吗，好像还是不能采集 `(base) yt-dlp "https://www.ximalaya.com/album/47769867" [ximalaya:album] Extracting URL: https://www.ximalaya.com/album/47769867 [ximalaya:album] 47769867: Downloading tracks list page 1 ERROR: division by zero`
> 
> try this
> 
> git clone https://github.com/4ft35t/yt-dlp.git && cd yt-dlp && git checkout fix-ximalaya-album
> ./yt-dlp.sh https://www.ximalaya.com/album/47769867

可以下载，感谢

**Comment by gongming1982** [comment]
> > 有相关的更新吗，好像还是不能采集 `(base) yt-dlp "https://www.ximalaya.com/album/47769867" [ximalaya:album] Extracting URL: https://www.ximalaya.com/album/47769867 [ximalaya:album] 47769867: Downloading tracks list page 1 ERROR: division by zero`
> 
> try this
> 
> git clone https://github.com/4ft35t/yt-dlp.git && cd yt-dlp && git checkout fix-ximalaya-album
> ./yt-dlp.sh https://www.ximalaya.com/album/47769867

我加上了cookie参数,好像还是没法获取VIP的信息呢,您有尝试下载VIP的资源吗

**Comment by 4ft35t** [comment]
> > > 有相关的更新吗，好像还是不能采集 `(base) yt-dlp "https://www.ximalaya.com/album/47769867" [ximalaya:album] Extracting URL: https://www.ximalaya.com/album/47769867 [ximalaya:album] 47769867: Downloading tracks list page 1 ERROR: division by zero`
> > 
> > 
> > try this
> > git clone https://github.com/4ft35t/yt-dlp.git && cd yt-dlp && git checkout fix-ximalaya-album
> > ./yt-dlp.sh https://www.ximalaya.com/album/47769867
> 
> 我加上了cookie参数,好像还是没法获取VIP的信息呢,您有尝试下载VIP的资源吗

VIP 的不能下载，老 API 失效，新 API 都用了 `xm-sign`。

用 `playwright` 控制浏览器，慢慢抓吧。
