### ISSUE TITLE
Continue downloading file after failed subtitle download

### ISSUE THREAD

**Issue by BrendanoElTaco** [yt-dlp/yt-dlp#1134]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How can I make it so that a video file downloads after a failed subtitle download? When the convert subs argument is present and a subtitle fails to download it skips downloading the video file.

```
[download] Downloading video 2 of 9
[debug] [aenetworks] Extracting URL: http://watch.history.com/shows/billion-doll
ar-wreck/season-1/episode-8
[aenetworks] /shows/billion-dollar-wreck/season-1/episode-8: Downloading JSON me
tadata
[aenetworks] 653570115958: Downloading JSON metadata
[aenetworks] 653570115958: Retrieving Media Token
[aenetworks] 653570115958: Downloading hls_high_ak SMIL data
[aenetworks] 653570115958: Downloading m3u8 information
[aenetworks] 653570115958: Downloading high_video_s3 SMIL data
[aenetworks] 653570115958: Downloading m3u8 information
[aenetworks] 653570115958: Downloading hls_high_fastly SMIL data
[aenetworks] 653570115958: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.
2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasau
d, source, id
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 653570115958: Downloading 1 format(s): hls-2703-2
[info] Writing video subtitles to: Billion Dollar Wreck - S1 E8 - The Lure of th
e Republic.en.scc
[debug] Invoking downloader on "http://aepdaks3.aetndigital.com/THC_BDWR_171968_
GLB_278763_5994_60_21000101_01_fast.scc?__gda__=1633206707_402aa889e6eb969adc019
e2f4d96ae6f"
WARNING: Unable to download subtitle for "en": HTTP Error 403: Forbidden
[SubtitlesConvertor] Converting subtitles
ERROR: 'filepath'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1214, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1252, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1298, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2320, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2655, in process_info
  File "yt_dlp\YoutubeDL.py", line 3005, in pre_process
  File "yt_dlp\YoutubeDL.py", line 2964, in run_pp
  File "yt_dlp\postprocessor\ffmpeg.py", line 833, in run
KeyError: 'filepath'
```

**Comment by pukkandan** [comment]
This purticular failure seems to be a bug, but you can use `-i`

**Comment by AndydeCleyre** [comment]
Thanks, I'll have a look.
