### ISSUE TITLE
No video formats available when try to download video from Facebook

### ISSUE THREAD

**Issue by EugenePerfect** [yt-dlp/yt-dlp#11341]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ukraine

### Provide a description that is worded well enough to be understood

Today I failed to download videos from facebook; yesterday on same computer with similar command lines download works fine. Updating for night buill not fixed the problem. Downloading fron Youtube works without problems.

Platform: Windows 10 Pro version 22H2 build 22H2, no proxy was used. 

Tested URLS:
regular FB video:
https://www.facebook.com/watch/?v=1631413371052366
https://www.facebook.com/watch/?v=1680177679206969

reels videos:
https://www.facebook.com/reel/454241990454273
https://www.facebook.com/reel/462004356815105

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.facebook.com/reel/454241990454273', '-o', 'test.mp4']
[debug] Portable config "S:\exe\yt-dlp.conf": ['--trim-filenames', '128', '--windows-filenames']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.23.232902 from yt-dlp/yt-dlp-nightly-builds [914af9a0c] (win_x86_exe)
[debug] Python 3.10.11 (CPython AMD64 32bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2024-09-22-git-a577d313b2-full_build-www.gyan.dev (setts), ffprobe 2024-09-22-git-a577d313b2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.23.232902 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.23.232902 from yt-dlp/yt-dlp-nightly-builds)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/454241990454273
[facebook] Extracting URL: https://m.facebook.com/watch/?v=454241990454273&_rdr
[facebook] 454241990454273: Downloading webpage
ERROR: [facebook] 454241990454273: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest ver
sion using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1781, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1840, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2846, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1122, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 454241990454273: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you
 are on the latest version using  yt-dlp -U
```

**Comment by EugenePerfect** [comment]
Sorry, erroneously duplicated issue https://github.com/yt-dlp/yt-dlp/issues/11337
