### ISSUE TITLE
 Error: No video formats found & Cannot parse data from Facebook

### ISSUE THREAD

**Issue by Mickekofi** [yt-dlp/yt-dlp#11344]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ghana

## Bug Report: Facebook Video Extraction Issues

I'm encountering two errors while using `yt-dlp` to extract video data from Facebook. The errors are:

### Error 1:

- ERROR: [facebook] 1098761348274281: No video formats found!; please report this issue.

### Error 2:

- ERROR: [facebook] 1275304336730426: Cannot parse data; please report this issue.

Both errors occurred when I used the following Python code to extract video data from Facebook.

### Code:
```python
import yt_dlp
import logging

# Function to fetch and download the Video from Facebook
def download_facebook_video(url):
    ydl_opts = {
        'format': 'best',
        'noplaylist': True,
        'outtmpl': '%(title)s - %(uploader)s - %(upload_date)s.%(ext)s',
        'quiet': True,
        'extract_flat': 'in_playlist',
    }
    
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info_dict = ydl.extract_info(url, download=False)
        if 'entries' in info_dict:
            video_format = info_dict['entries'][0]
        else:
            video_format = info_dict

        download_url = video_format.get('url')
        if not download_url:
            raise ValueError("Could not extract video URL.")
        
        return download_url
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip) API
[debug] params: {'format': 'best', 'noplaylist': True, 'outtmpl': '%(title)s - %(uploader)s - %(upload_date)s.%(ext)s', 'verbose': True, 'extract_flat': 'in_playlist', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.8.0-45-generic-x86_64-with-glibc2.35 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-1.26.20, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1839 extractors
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1098761348274281?mibextid=NpOjYg&s=yWDuG2&fs=e
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1098761348274281&_rdr
[facebook] 1098761348274281: Downloading webpage
ERROR: [facebook] 1098761348274281: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2846, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1122, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [facebook] 1098761348274281: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip) API
[debug] params: {'format': 'best', 'noplaylist': True, 'outtmpl': '%(title)s - %(uploader)s - %(upload_date)s.%(ext)s', 'verbose': True, 'extract_flat': 'in_playlist', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.8.0-45-generic-x86_64-with-glibc2.35 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-1.26.20, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1839 extractors
[generic] Extracting URL: https://www.facebook.com/share/v/DcsPYsXmvQh3SteL/?mibextid=A7sQZp
[generic] ?mibextid=A7sQZp: Downloading webpage
[redirect] Following redirect to https://web.facebook.com/groups/203713510556186/permalink/1275304336730426/?mibextid=A7sQZp&rdid=O6Sd76GNAeCGbfrY&share_url=https%3A%2F%2Fweb.facebook.com%2Fshare%2Fv%2FDcsPYsXmvQh3SteL%2F%3Fmibextid%3DA7sQZp%26_rdc%3D1%26_rdr
[facebook] Extracting URL: https://web.facebook.com/groups/203713510556186/permalink/1275304336730426/?mibextid=A7sQZp&rdid=O6Sd76GNAeCGbfrY&share_url=https%3A%2F%2Fweb.facebook.com%2Fshare%2Fv%2FDcsPYsXmvQh3SteL%2F%3Fmibextid%3DA7sQZp%26_rdc%3D1%26_rdr
[facebook] 1275304336730426: Downloading webpage
[facebook] 1275304336730426: Downloading webpage
ERROR: [facebook] 1275304336730426: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/yt_dlp/extractor/facebook.py", line 866, in _real_extract
    return self._extract_from_url(real_url, video_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/yt_dlp/extractor/facebook.py", line 811, in _extract_from_url
    raise ExtractorError('Cannot parse data')
```

**Comment by bashonly** [comment]
read the pinned issues

https://github.com/yt-dlp/yt-dlp/issues/11337#issuecomment-2435977983
