### ISSUE TITLE
"ERROR: Unable to download video: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-audio-128000-Audio.mp4.ytdl'".

### ISSUE THREAD

**Issue by antdude** [yt-dlp/yt-dlp#11364]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Downloading https://x.com/CFBONFOX/status/1850021908999209027 shows "ERROR: Unable to download video: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-audio-128000-Audio.mp4.ytdl'"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ ~/bin/yt-dlpMasterBuild -vU https://x.com/CFBONFOX/status/1850021908999209027

[debug] Command-line config: ['-vU', 'https://x.com/CFBONFOX/status/1850021908999209027']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.10.26.180244 from yt-dlp/yt-dlp-master-builds [21cdcf03a] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-26-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: brotli-1.0.9, certifi-2022.09.24, pyxattr-0.8.1, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.10.26.180244 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.10.26.180244 from yt-dlp/yt-dlp-master-builds)
[twitter] Extracting URL: https://x.com/CFBONFOX/status/1850021908999209027
[twitter] 1850021908999209027: Downloading guest token
[twitter] 1850021908999209027: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1850021881526538240
[twitter] 1850021908999209027: Downloading m3u8 information
[debug] Sort order given by extractor: res, proto:m3u8, br, size
[debug] Formats sorted by: hasvid, ie_pref, res, proto:m3u8(8), br, size, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1850021881526538240: Downloading 1 format(s): hls-1200+hls-audio-128000-Audio
[debug] Invoking hlsnative downloader on "https://video.twimg.com/amplify_video/1850021881526538240/pl/avc1/1280x720/rtPV5s9oFWW-Vuz5.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 5
[download] Destination: FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4
ERROR: unable to open for writing: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag1.part'
Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 591, in sanitize_open
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 1617, in __init__
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag1.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 250, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 5266, in report_retry
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 593, in sanitize_open
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag1.part'

[download] fragment not found; Skipping fragment 1 ...
ERROR: unable to open for writing: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag2.part'
Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 591, in sanitize_open
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 1617, in __init__
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag2.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 250, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 5266, in report_retry
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 593, in sanitize_open
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag2.part'

[download] fragment not found; Skipping fragment 2 ...
ERROR: unable to open for writing: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag3.part'
Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 591, in sanitize_open
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 1617, in __init__
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag3.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 250, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 5266, in report_retry
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 593, in sanitize_open
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag3.part'

[download] fragment not found; Skipping fragment 3 ...
ERROR: unable to open for writing: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag4.part'
Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 591, in sanitize_open
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 1617, in __init__
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag4.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 250, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 5266, in report_retry
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 593, in sanitize_open
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag4.part'

[download] fragment not found; Skipping fragment 4 ...
ERROR: unable to open for writing: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag5.part'
Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 591, in sanitize_open
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 1617, in __init__
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag5.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 250, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 5266, in report_retry
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 593, in sanitize_open
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag5.part'

[download] fragment not found; Skipping fragment 5 ...
ERROR: unable to open for writing: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag6.part'
Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 591, in sanitize_open
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 1617, in __init__
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag6.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 250, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 5266, in report_retry
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 593, in sanitize_open
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-1200.mp4.part-Frag6.part'

[download] fragment not found; Skipping fragment 6 ...
ERROR: The downloaded file is empty
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ant/bin/yt-dlpMasterBuild/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/__init__.py", line 1092, in main
    _exit(*variadic(_real_main(argv)))
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/__init__.py", line 1082, in _real_main
    return ydl.download(all_urls)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 3608, in download
    self.__download_wrapper(self.extract_info)(
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 3581, in wrapper
    res = func(*args, **kwargs)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 1614, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 3014, in process_video_result
    self.process_info(new_info)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 178, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 3464, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 3202, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/hls.py", line 381, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/fragment.py", line 527, in download_and_append_fragments
    return self._finish_frag_download(ctx, info_dict)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/fragment.py", line 301, in _finish_frag_download
    self.report_error('The downloaded file is empty')
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 1091, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 1019, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


[debug] Invoking hlsnative downloader on "https://video.twimg.com/amplify_video/1850021881526538240/pl/mp4a/128000/ouKR03gcv7QkrAtQ.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 5
[download] Destination: FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-audio-128000-Audio.mp4
ERROR: Unable to download video: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-audio-128000-Audio.mp4.ytdl'
Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 591, in sanitize_open
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 1617, in __init__
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-audio-128000-Audio.mp4.ytdl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 3464, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 3202, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/hls.py", line 158, in real_download
    self._prepare_and_start_frag_download(ctx, info_dict)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/fragment.py", line 77, in _prepare_and_start_frag_download
    self._prepare_frag_download(ctx)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/fragment.py", line 213, in _prepare_frag_download
    self._write_ytdl_file(ctx)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/fragment.py", line 97, in _write_ytdl_file
    frag_index_stream, _ = self.sanitize_open(self.ytdl_filename(ctx['filename']), 'w')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 250, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 5266, in report_retry
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/downloader/common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/utils/_utils.py", line 593, in sanitize_open
OSError: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-audio-128000-Audio.mp4.ytdl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 3014, in process_video_result
    self.process_info(new_info)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 178, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/YoutubeDL.py", line 3494, in process_info
    raise UnavailableVideoError(err)
yt_dlp.utils.UnavailableVideoError: Unable to download video: [Errno 36] File name too long: 'FOX College Football - Simply why we love sports 🫶  Fans watching the final moments of Game 1 of the World Series on their phones as Freddie Freeman walks it off for the @Dodgers just 6 miles away 🔥 [1850021881526538240].fhls-audio-128000-Audio.mp4.ytdl'
```

**Comment by Grub4K** [comment]
See #1136

Use something like `-o "%(title).150B [%(id)s].%(ext)s"` instead.
