### ISSUE TITLE
Long titles and IDs can result in filenames that are too long for the OS

### ISSUE THREAD

**Issue by tylerszabo** [yt-dlp/yt-dlp#1136]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['--verbose', 'https://twitter.com/NASA/status/1443572363757559808', '-o', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.25 (source)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: ad095c428
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg n4.4-80-gbf87bdd3f6-20210811, ffprobe n4.4-80-gbf87bdd3f6-20210811, phantomjs 2.1.1
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [twitter] Extracting URL: https://twitter.com/NASA/status/1443572363757559808
[twitter] 1443572363757559808: Downloading guest token
[twitter] 1443572363757559808: Downloading JSON metadata
[twitter] 1443572363757559808: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1443572363757559808: Downloading 1 format(s): hls-2176
[debug] Invoking downloader on "https://video.twimg.com/amplify_video/1443570535904935945/pl/1280x720/eB7trHC2QS5NrGUL.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 22
[download] Destination: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[download]  40.9% of ~5.05MiB at  9.73MiB/s ETA 00:01 ERROR: unable to open for writing: [Errno 22] Invalid argument: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.part-Frag10.part'
Traceback (most recent call last):
  File "F:\source\repos\yt-dlp\yt_dlp\downloader\http.py", line 262, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "F:\source\repos\yt-dlp\yt_dlp\utils.py", line 2068, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 22] Invalid argument: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.part-Frag10.part'

ERROR: unable to download video data: [Errno 2] No such file or directory: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.part-Frag10'
Traceback (most recent call last):
  File "F:\source\repos\yt-dlp\yt_dlp\YoutubeDL.py", line 2758, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "F:\source\repos\yt-dlp\yt_dlp\YoutubeDL.py", line 2475, in dl
    return fd.download(name, new_info, subtitle)
  File "F:\source\repos\yt-dlp\yt_dlp\downloader\common.py", line 408, in download
    return self.real_download(filename, info_dict), True
  File "F:\source\repos\yt-dlp\yt_dlp\downloader\hls.py", line 350, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "F:\source\repos\yt-dlp\yt_dlp\downloader\fragment.py", line 478, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "F:\source\repos\yt-dlp\yt_dlp\downloader\fragment.py", line 418, in download_fragment
    success, frag_content = self._download_fragment(ctx, fragment['url'], info_dict, headers)
  File "F:\source\repos\yt-dlp\yt_dlp\downloader\fragment.py", line 132, in _download_fragment
    return True, self._read_fragment(ctx)
  File "F:\source\repos\yt-dlp\yt_dlp\downloader\fragment.py", line 135, in _read_fragment
    down, frag_sanitized = sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
  File "F:\source\repos\yt-dlp\yt_dlp\utils.py", line 2068, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
FileNotFoundError: [Errno 2] No such file or directory: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.part-Frag10'

```

## Description

The defaults can result in filenames that are too long and confusingly this can also occur in temporary files. The example here shows a 239 character filename fails when the `.part-Frag10` suffix causes the filename to exceed 255 characters.

The workaround is to explicitly specify an output template that will not become too long even when suffixes are added. The default `%(title)s [%(id)s].%(ext)s` and fallback `%(title)s-%(id)s.%(ext)s` can both exceed 255 characters, especially with videos in long tweets.

In the example provided the output template is explicitly set to a filename that will exactly exceed 255 characters on fragment 10 to better illustrate the issue. However, omitting template or explicitly using the default `%(title)s [%(id)s].%(ext)s` will still result in an immediate failure on fragment 1.

This is related to #1003 and would appear to be cross-platform issue (and depends on the filesystem for the target files rather than the OS or runtime).

Work published by NASA is in the public domain so there are no licensing concerns with testing using this URL.

There are various codepaths that expect to be able to add a suffix to a temporary file and the temporary filename is based on the destination filename. By adding an option to specify tempfile format such as `%(extractor)s-%(id)s.%(ext)s` and altering the default file template to set some high but sane limits this could be mitigated for most users and still allow advanced users to explicitly specify long filenames.

**Comment by pukkandan** [comment]
Are you asking only about the default? or about user-provided templates too? For user provided templates, you can do something like `-o %(title)200s.%(ext)s`

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/pull/29989

**Comment by tylerszabo** [comment]
Improved defaults would be nice but I thought the effects of temp files (since they will always be longer than the main output file) was the more confusing aspect and there is currently no mechanism for specifying a template for temp files (they just inherit the output template).

I experimented with a number of techniques for deterministically shortening but they were not ideal - any format with length limits would ultimately end up being a guess but some limits as you suggested with maybe ~160 characters for title and ~40 for ID might be sensible. Then if temp files could have a different format maybe as high as ~180 for title would be okay without risking a sudden error at chunk 10000.

**Comment by GenericGoose** [comment]
annoyingly, when using yt-dlp Ive had an issue where the filename which was video title + chapter name was too long, which only gave a confusing 'no such file or directory' error. I suppose this is a separate issue

**Comment by wxolp** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30361

**Comment by InconsolableCellist** [comment]
Re: cross-platform compatibility, you can allow the user to specify a maximum file length as a flag. Users can then alias yt-dlp to automatically include that flag at their leisure.

Alternatively, you can determine if the attempted path exceeds the maximum file length by checking to see if the file was successfully created or not. File APIs for all major platforms will provide this information. You can then truncate the requested filename and inform the user. This is how things were handled all the way back in FAT16 with the "FILENA~1.EXT" convention.

I run into this bug all the time when archiving tweets.

**Comment by chapmanjacobd** [comment]
It should also be noted that the limitation is often not 255 characters but 255 _bytes_ so for non-ASCII languages you are limited to a lot fewer than 255 char

**Comment by pukkandan** [comment]
> It should also be noted that the limitation is often not 255 characters but 255 bytes so for non-ASCII languages you are limited to a lot fewer than 255 char.

This is why I added the `B` formatter. Eg: `%(title).200B` to limit to 200 bytes. See "output template" section of readme for a list of the custom formatters yt-dlp provides

**Comment by InconsolableCellist** [comment]
Is there a way to use an output template to limit it to 200 bytes without having to manually specify the title? I'd like to tell yt-dlp to truncate at x bytes but still determine the title based on the metadata retrieved from the video, not passed in on the command line. Then I could alias the `yt-dlp` command to something that includes that template by default, to workaround this issue.

**Comment by chapmanjacobd** [comment]
@InconsolableCellist 

 Is 

```
%(filename).200B
```

valid? that's how gallerydl does it

**Comment by InconsolableCellist** [comment]
@chapmanjacobd Unfortunately that results in: 

```
[download] Destination: NA
```

And it creates a file named "NA"

**Comment by pukkandan** [comment]
@InconsolableCellist Read the comments literally just above your question! https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-1114252397 https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195

**Comment by nick-s-b** [comment]
````
ERROR: unable to open for writing: [Errno 36] File name too long
````

This is THE MOST ANNOYING bug in `yt-dlp` I can think of. Almost every time I try to save a Twitter video, `yt-dlp` fails to save a file. Why can't it just truncate the filename?

**Comment by rebane2001** [comment]
> > It should also be noted that the limitation is often not 255 characters but 255 bytes so for non-ASCII languages you are limited to a lot fewer than 255 char.
> 
> This is why I added the `B` formatter. Eg: `%(title).200B` to limit to 200 bytes. See "output template" section of readme for a list of the custom formatters yt-dlp provides

Thank you for this feature. I figured I'd leave a comment with some things I found unclear myself and had to check so if anybody else comes across this thread they don't need to check it for themselves:

1. The readme states `yt-dlp additionally supports converting to B = Bytes`, but the end result is still a filename with correct unescaped unicode in it, not something like `\xf0\x9f\xa6\x84`. The readme isn't wrong, but the "converts" part can be interpreted in multiple ways.
2. The bytes are truncated up to the last valid byte, so a string such as `🦄🦄` with a formatting of 6B will only take the first emoji (4 bytes) and result in `🦄` without leaving half of the other one like `🦄\xf0\x9f`.

**Comment by erlenmayr** [comment]
This happens with Twitter videos often because it uses the whole tweet as filename. How about just using the Twitter handle plus tweet ID and then crop the Tweet?

**Comment by Asday** [comment]
As far as detecting the issue ahead of time, dropping a `try` on an `open(fname, "w")` would let you see if the filename is too long in reasonable Pythonic "ask for forgiveness rather than permission" style.

If it _is_ too long, I think it'd be acceptable to just name it something 8 characters long (maybe a datestamp and a number counting up from `00`), and also drop a `YYYYMMDDNN.filename` in the same directory containing what the filename was intended to be.  The user can then truncate in whichever way they deem sensible after the fact.

**Comment by pukkandan** [comment]
> As far as detecting the issue ahead of time, dropping a try on an open(fname, "w") would let you see if the filename is too long in reasonable Pythonic "ask for forgiveness rather than permission" style.

https://github.com/ytdl-org/youtube-dl/pull/29989#issuecomment-1025740928

**Comment by rubyFeedback** [comment]
I just ran into this again.

Is there a commandline way to work around this? Something like "--automatically-rename" or "--automatically-shorten".

Right now I don't know how to work around this, so I depend on upstream folks not using too long file names. Perhaps the file name could be downloaded via a short dummy name that is then renamed locally? I believe linux filesystems typically have no problem with long filenames.

**Comment by Asday** [comment]
There's `--exec` which you can wrankle into use for this.  Download all files as just the video ID, then exec some specialised script that knows about the difference between bytes and runes that can read the also-downloaded json info and rename the file appropriately, and even maybe move it to its destination.

**Comment by h-h-h-h** [comment]
#### Regarding the MAX_PATH dilemma on Windows:

In the context of writing the `--write-link` feature, I introduced the function [`to_high_limit_path()`](https://github.com/yt-dlp/yt-dlp/search?q=to_high_limit_path). To this day, it's still only used for internet shortcut files (in a rather hard-to-understand way, if I may add; and what's done with filenames there seemed to me to involve redundancy when I looked at it).

I'd suggest reworking file path handling and using `to_high_limit_path()` in every case, possibly as part of a general file path preparation function or a custom file opening function.

**Comment by ubergarm** [comment]
For anyone invoking from within a python script and not CLI, specifying `"outtmpl"` in the `ydl_opts` dict before beginning downloads seems to have fixed the `Filename too long` issue for me:
```
ydl_opts = {
    # ... your other ydl_opts here,
    "outtmpl": "%(title).200B", # <--- from comments above
}
```

**Comment by Asday** [comment]
Huh!  I didn't know about the `B` truncation formatting specifier, I assume that means bytes?  That'll help with my issue, whereby Japanese multibyte characters (and sometimes emoji) forced an unnecessarily short filename.

**Comment by pukkandan** [comment]
Yes, see https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-1114252397

**Comment by h-h-h-h** [comment]
@pukkandan: But any invalid UTF-8/UCS-2/whatever is shortened further byte by byte to become valid?

**Comment by pukkandan** [comment]
Yes https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-1214832554

**Comment by JediMaster25** [comment]
Here is something I just saw on a script:
```
# Try downloading normally
if ! $youtube_dl $opts -o "${dir}/%(title)s.%(ext)s" "$($paste)"; then
  # If the title is too long, use the id
  $youtube_dl $opts -o "${dir}/%(id)s.%(ext)s" "$($paste)"
fi
```

**Comment by Asday** [comment]
That's a really bad idea because you end up downloading basically every video twice.

**Comment by JediMaster25** [comment]
> That's a really bad idea because you end up downloading basically every video twice.

No, it only executes the inner command if the `if statement` fails.

**Comment by Asday** [comment]
Every video that fails, you know what I meant.

Download to `/tmp/` with a short filename such as the video ID, then use `--exec` to pass the resulting files to a program you write to give them the title you want.

**Comment by alrepin** [comment]
[download] 100% of  104.77MiB in 00:13:27 at 132.86KiB/s
ERROR: unable to download video data: [Errno 2] No such file or directory

**Comment by aslian** [comment]
`youtube-dl` had `--id`, why it isn't there anymore?

```
  Filesystem Options:
    -a, --batch-file FILE                File containing URLs to download ('-'
                                         for stdin), one URL per line. Lines
                                         starting with '#', ';' or ']' are
                                         considered as comments and ignored.
    --id                                 Use only video ID in file name
```

**Comment by rpdelaney** [comment]
Thanks to comments in this thread I got this working:

```console
$ yt-dlp -o '%(title).200B.%(ext)s' '<url>'
```

Hypothetically, if I wanted to be able to tell which files have truncated names, is it possible to add something to indicate that? Could be an `…` (`0x2026`) or w/e, doesn't matter.

**Comment by rpdelaney** [comment]
Awesome. At first I misunderstood you, but this seems to be working great!

```console
yt-dlp --output '%(title).200B%(title.201&…|)s.%(ext)s'
```

**Comment by rpdelaney** [comment]
@chrizilla possibly. Do you have any suggestions?

in #6882 this was suggested but I haven't tried it myself: `-o "%(title).150B [%(id)s].%(ext)s"` I suppose it's unlikely that the id or the extension would have many surprises, though.

**Comment by rpdelaney** [comment]
At least in linux, I know that the filename length limits are counted in raw bytes since there is no enforcement of a specific character encoding for a filesystem. Counting bytes would be safest.

**Comment by rpdelaney** [comment]
@chrizilla How about this then?

```
yt-dlp --output '%(title).200B%(title.201B&…|)s.%(ext)s'
```

**Comment by kenorb** [comment]
Same for <https://twitter.com/BrainStorm_Joe/status/1734386440706953260>.

> ERROR: unable to open for writing: [Errno 36] File name too long

**Comment by kenorb** [comment]
Another example:

```
\yt-dlp https://twitter.com/alillian/status/1754628007191290046
ERROR: unable to open for writing: [Errno 36] File name too long: 'Ashley McAuley - What a weekend!  Somehow in between personal and family time, and with a 7-hour time difference between us, @sraleksandrov and I managed to pull this off!   I am exhausted but thrilled that we were able to finish and submit in time for the @runwayml GEN：48 competition.   We hope… [1754627141377904641].mp4.part'
```

**Comment by keithstellyes** [comment]
Ran into this in the wild with `yt-dlp https://www.tiktok.com/@thequotecollection/video/7347268964566846752`

```
File name too long: 'Never discourage ＂silly＂ questions - Carl Sagan ｜ TheQuoteCollection  • • • Follow for Daily Motivation!  • • •                                                                                                                                                                                         Why Embracing All Questions Nurtures Critical Thinking and Growth! Discover the transformative power of encouraging questions, no matter how seemingly trivial, to cultivate critical thinking skills and foster continuous learning. Learn why creating a supportive environment for curiosity fuels innovation, problem-solving, and personal development. From embracing diverse perspectives to sparking creativity, explore the empowering reasons why valuing every question leads to intellectual growth and progress. Embrace the journey of fostering a culture of inquiry and watch as critical thinking thrives! [7347268964566846752].mp4.part'
```

**Comment by antdude** [comment]
Yes, this is very annoying. It would be nice if yt-dlp have an option to auto rename. Look at old Windows 95 when DOS couldn't handle long file names. They used filename~1.ext filename as an example.

**Comment by Asday** [comment]
> Everyone agrees this is a good idea. The reason this is not implemented is mostly due to technical reasons and partly due to compatibility reasons.

Please open a pull request fixing this if you'd like to contribute.

**Comment by github-account1111** [comment]
Programs can bypass the path length limit: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later

Is there a reason yt-dlp can't be one of such programs? Sounds like the most correct way to approach this.

**Comment by bashonly** [comment]
> Programs can bypass the path length limit: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later

> Is there a reason yt-dlp can't be one of such programs? Sounds like the most correct way to approach this.

Python has done this since version 3.6.

Two problems, though:

- the user needs to add/toggle the registry value on their system

- this only applies to the **full path limit**; it does **not** apply to the **NTFS path component limit** of 255 characters

**Comment by github-account1111** [comment]
Hold up. There are *two* limits, and the setting only takes care of one of them? So I can place the file three folders deep to "lengthen" the filename to 4 * 255 chars, but I can't have an actual filename that's 4 * 255 chars long? That's dumb. But also, I guess that's Microsoft we're talking about...

**Comment by dirkf** [comment]
As was pointed out in linked, possibly duplicate, issue #6974, Linux ext4 has the same per-component limit, and a fixed 4k limit for the whole pathname. So it's not just dumbness at Microsoft, or maybe not dumbness at all. Your file with a super-long pathname may fail to be backed up to your Linux-based consumer NAS. Also, it's interesting to see which Linux programs fail to list or delete a file with a 4k-long path (`rm -r` FTW).

**Comment by fewfw3r32** [comment]
> Are you asking only about the default? or about user-provided templates too? For user provided templates, you can do something like `-o %(title).200B.%(ext)s`

Is there a way to trim only filenames that exceed the length limit, not all of them?

**Comment by dirkf** [comment]
Other than repeatedly running the command with decreasing values of the length (`200` above) until the filename is not too long, no. But do you want a filename that's too long to read in a file manager (etc) anyway?

**Comment by aleksejrs** [comment]
> Other than repeatedly running the command with decreasing values of the length (`200` above) until the filename is not too long, no. But do you want a filename that's too long to read in a file manager (etc) anyway?

It sure is annoying to read it in a file manager, but it is visible to `locate` and a filter in a file manager.

**Comment by microcai** [comment]
why a windows restrict apply to Linux ?

**Comment by bashonly** [comment]
@microcai what do you mean?

**Comment by attila-lendvai** [comment]
> why a windows restrict apply to Linux ?

linux also has a limit somewhere.

AFAIU the problem is that it's not handled at all when the name goes beyond a limit.

**Comment by teika-kazura** [comment]
I created a new [patch](https://gitlab.com/teika/yt-dlp-fix/-/raw/main/too-long-filename.patch?ref_type=heads&inline=false). With it,

1. Temporary files are named `<id>.<ext>`.
2. If the final rename fails, it results in `<id>.<ext`, and the intended filename is saved in `<id>.target_filename`.

This fixes two problems of the current HEAD:

1. When you're downloading multiple files: The process can abort unpredictably at the moment when it encounters one long filename.
2. When downloading the video file took long, and only the audio file is bad. For example in the hls format the intermediate audio filename is long, like this: ` hls-3470-1+hls-ts_AUDIO-0_2-pro_a69fdcaecd6b46e781a9363dfb93006`. In such case you can avoid downloading again by doing some manual fix (with multiple steps), but it's cumbersome.

With my patch, users can handle exceptions programatically.

However my patch has some limitations, and not tested thoroughly. See [this Gentoo forum post](https://forums.gentoo.org/viewtopic.php?p=8882833) for details.

Since no such thing like "the best solution" exists, pragmatism (= what happens in the real world) is the only way to go. Users are encouraged to try it, and report issues.

Practically users should create a branch with my patch alongside the master. Then if they encounter a problem, they can switch back to master temporarily.

*I won't work on this* in the near future. This patch satisfies me ATM.

**Comment by Asday** [comment]
Please consider opening a PR for that, I would LOVE that behaviour.

**Comment by dirkf** [comment]
Before creating such a PR one might review these considerations, as well as related issues and PR attempts linked above.
 
1. There's no guarantee that an extractor will not generate an ID that causes an over-long filename.
2. The ID is only unique when taken with the IE key and not even then if the `GenericIE` is being used.
 
Just as there can be no general method for detecting a computer virus, yet a certain procedure may detect a specific type of virus, concretising the problem makes it tractable.

For YT, use the default output format with a limitation on the `title` length, in bytes or characters depending how your file system's limit is counted in your OS. Examples up-thread.

For some other specific site where IDs could be longer, do something similar but with a lower `title` limit.

The [1s Bandcamp test video](https://7x11x13-testing.bandcamp.com/track/-) has a long title with unnaturally many `U+3042 HIRAGANA LETTER A` characters and would certainly yield to this tactic.

**Comment by Asday** [comment]
Perfect is the enemy of good.  I do not generally download stuff from bandcamp and thus don't care too much about issues with it not having IDs.  I _do_ download stuff from youtube, and have hit this issue multiple times, so that patch being merged would make me very happy.

Also, just to argue, clicking on the "free download" of that bandcamp video gives me the URL `https://bandcamp.com/download?fsig=0bf22f9eec56ef6f5d5de09f45427b17&id=953563459&ts=1775201462.3800460306&type=track` which has a very obvious `id=953563459`.  I don't think enough people are using yt-dlp on 8.3 filesystems, so that ID would do just fine as a temporary-maybe-permanent short form.

And and and, another time I often have to use `-o` is when grabbing videos from X, where the default filename is the ENTIRE CONTENTS of the X post.  Every X post has an ID, and yt-dlp already appends an index if there are multiple pieces of media on a post, so this patch would presumably solve my issue there too.
