### ISSUE TITLE
Why did not download from https://treff.darc.de/playback/presentation ?

### ISSUE THREAD

**Issue by ds2k5** [yt-dlp/yt-dlp#11372]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This was a session from a BigBlueButton Meeting I like to download
it that I can watch it without need Internet Connection.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ ./yt-dlp_linux -vU https://treff.darc.de/playback/presentation/2.3/f2ece695693093a21a64cccaf471eda670b27eb1-1729945679988
[debug] Command-line config: ['-vU', 'https://treff.darc.de/playback/presentation/2.3/f2ece695693093a21a64cccaf471eda670b27eb1-1729945679988']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp (linux_exe)
[debug] Python 3.11.10 (CPython x86_64 64bit) - Linux-6.1.0-26-amd64-x86_64-with (OpenSSL 3.1.7 3 Sep 2024)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://treff.darc.de/playback/presentation/2.3/f2ece695693093a21a64cccaf471eda670b27eb1-1729945679988
[generic] f2ece695693093a21a64cccaf471eda670b27eb1-1729945679988: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] f2ece695693093a21a64cccaf471eda670b27eb1-1729945679988: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://treff.darc.de/playback/presentation/2.3/f2ece695693093a21a64cccaf471eda670b27eb1-1729945679988
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1760, in __extract_info
  File "yt_dlp/extractor/common.py", line 741, in extract
  File "yt_dlp/extractor/generic.py", line 2533, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://treff.darc.de/playback/presentation/2.3/f2ece695693093a21a64cccaf471eda670b27eb1-1729945679988
```

**Comment by seproDev** [comment]
Because the site is not supported. If you wish I can convert this to a site support request.

In general, videos can be downloaded by placing the id in: `https://treff.darc.de/presentation/{video_id}/video/webcams.webm`
So for this particular video, the download URL would be:
```
https://treff.darc.de/presentation/f2ece695693093a21a64cccaf471eda670b27eb1-1729945679988/video/webcams.webm
```

**Comment by ds2k5** [comment]
@seproDev 

Many thanks!

If download the .webm file did not get video only audio

>Because the site is not supported. If you wish I can convert this to a site support request.

I will try

**Comment by seproDev** [comment]
> If download the .webm file did not get video only audio

Yes, it only contains the webcam feed (as there was no webcam, only the audio is recorded). There also exists a deskshare feed, but that doesn't cover the whole video either, but only those portions where a screen was shared. The actual slides are rendered by your web browser and so cannot be easily downloaded in a video format. If you do want the slides downloaded as well, I don't think yt-dlp is the right tool for the job. Maybe you can find look for some other tool specializing in big blue button downloads.

> Could you tell me how please ?

I have changed the issue to be a site request.

**Comment by ds2k5** [comment]
>I have changed the issue to be a site request.

Thank you!
