### ISSUE TITLE
[Broken] Funimation no longer gets correct cookies from --cookies-from-browser

### ISSUE THREAD

**Issue by Sipherdrakon** [yt-dlp/yt-dlp#1142]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ytdl -o "%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL-%(height)s].%(ext)s" -f "best[height>1]"/bv+ba -ic --simulate --newline --cookies-from-browser chrome --console-title --sub-langs en.* --embed-subs --extractor-args "funimation:version=simulcast" --extractor-args "funimation:language=english" "https://www.funimation.com/en/shows/ssssdynazenon/what-are-these-overlapping-emotions" --verbose
[debug] Command-line config: ['-o', '%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL-%(height)s].%(ext)s', '-f', 'best[height>1]/bv+ba', '-ic', '--simulate', '--newline', '--cookies-from-browser', 'chrome', '--console-title', '--sub-langs', 'en.*', '--embed-subs', '--extractor-args', 'funimation:version=simulcast', '--extractor-args', 'funimation:language=english', 'https://www.funimation.com/en/shows/ssssdynazenon/what-are-these-overlapping-emotions', '--verbose']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Sipherdrakon\AppData\Local\Google\Chrome\User Data\Default\Cookies"
[Cookies] Extracted 3042 cookies from chrome
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.25 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [funimation:page] Extracting URL: https://www.funimation.com/en/shows/ssssdynazenon/what-are-these-overlapping-emotions
[funimation:page] ssssdynazenon_what-are-these-overlapping-emotions: Downloading webpage
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/1511227
[Funimation] 1511227: Downloading player webpage for 1511227
[Funimation] what-are-these-overlapping-emotions: Downloading player webpage for Simulcast english (2658857)
[Funimation] what-are-these-overlapping-emotions: Downloading Simulcast english (2658857) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Free Avails for this experience
[debug] Downloading subtitles: en_CC
ERROR: [Funimation] 1396397: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1265, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1315, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2201, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 850, in raise_no_formats
yt_dlp.utils.ExtractorError: [Funimation] 1396397: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

USING OLD YT-DLP 09.02.21 VERSION

ytdl0902 -o "%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL-%(height)s].%(ext)s" -f "best[height>1]"/bv+ba -ic --simulate --newline --cookies-from-browser chrome --console-title --sub-langs en.* --embed-subs --extractor-args "funimation:version=simulcast" --extractor-args "funimation:language=english" "https://www.funimation.com/en/shows/ssssdynazenon/what-are-these-overlapping-emotions" --verbose
[debug] Command-line config: ['-o', '%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL-%(height)s].%(ext)s', '-f', 'best[height>1]/bv+ba', '-ic', '--simulate', '--newline', '--cookies-from-browser', 'chrome', '--console-title', '--sub-langs', 'en.*', '--embed-subs', '--extractor-args', 'funimation:version=simulcast', '--extractor-args', 'funimation:language=english', 'https://www.funimation.com/en/shows/ssssdynazenon/what-are-these-overlapping-emotions', '--verbose']
[Cookies] Extracting cookies from chrome
[debug] extracting from: "C:\Users\Sipherdrakon\AppData\Local\Google\Chrome\User Data\Default\Cookies"
[Cookies] Extracted 3043 cookies from chrome
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [funimation:page] Extracting URL: https://www.funimation.com/en/shows/ssssdynazenon/what-are-these-overlapping-emotions
[funimation:page] ssssdynazenon_what-are-these-overlapping-emotions: Downloading webpage
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/2658857
[Funimation] 2658857: Downloading player webpage for 2658857
[Funimation] what-are-these-overlapping-emotions: Downloading Simulcast english (2658857) JSON
[Funimation] what-are-these-overlapping-emotions: Downloading Simulcast english (2658857) m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en_CC
[info] 1396397: Downloading 1 format(s): 2658857-hls-6291+2658857-hls-audio-aacl-256-English

USING COOKIES.TXT FILE WITH NEW YT-DLP 09.25.21 VERSION

ytdl -o "%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL-%(height)s].%(ext)s" -f "best[height>1]"/bv+ba -ic --simulate --newline --cookies cookies.txt --console-title --sub-langs en.* --embed-subs --extractor-args "funimation:version=simulcast" --extractor-args "funimation:language=english" "https://www.funimation.com/en/shows/ssssdynazenon/what-are-these-overlapping-emotions" --verbose
[debug] Command-line config: ['-o', '%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL-%(height)s].%(ext)s', '-f', 'best[height>1]/bv+ba', '-ic', '--simulate', '--newline', '--cookies', 'cookies.txt', '--console-title', '--sub-langs', 'en.*', '--embed-subs', '--extractor-args', 'funimation:version=simulcast', '--extractor-args', 'funimation:language=english', 'https://www.funimation.com/en/shows/ssssdynazenon/what-are-these-overlapping-emotions', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.25 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [funimation:page] Extracting URL: https://www.funimation.com/en/shows/ssssdynazenon/what-are-these-overlapping-emotions
[funimation:page] ssssdynazenon_what-are-these-overlapping-emotions: Downloading webpage
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/2658857
[Funimation] 2658857: Downloading player webpage for 2658857
[Funimation] what-are-these-overlapping-emotions: Downloading Simulcast english (2658857) JSON
[Funimation] what-are-these-overlapping-emotions: Downloading Simulcast english (2658857) m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en_CC
[info] 1396397: Downloading 1 format(s): 2658857-hls-6291+2658857-hls-audio-aacl-256-English
```

## Description

So I tested a funimation video that requires login to watch. The first trial was with the current version of yt-dlp using `--cookies-from-browser`, the second trial is with the release before the current one also using `--cookies-from-browser` and the third trial is using cookies extracted from chrome and placed in a cookies.txt file using `--cookies`.

As you can see the new release does work if given a cookies file but not when using the argument `--cookies-from-browser`

**Comment by Jules-A** [comment]
I guess it's this: https://github.com/yt-dlp/yt-dlp/commit/ad226b1dc9763fd2840514e7636a9e16ecc31f9d
I never tested using cookies from browser (I'll try now) but I don't know why that should make a difference? I know if you are using something like a VPN to fake your location and the cookies end up having a region that doesn't normally have access to the title then it will fail if you aren't also using that region to dl with YT-DLP.

**Comment by Sipherdrakon** [comment]
Hmm, well now it's working fine. Weird, must have been something up with my chrome not logging the cookies for it. I swear I logged out and back in just to make sure, but oh well. You're good. I'll close this. :-)

**Comment by pukkandan** [comment]
If you just logged in, the cookies may not be in the disk yet. Closing chrome will ensure the cookies are saved in that case
