### ISSUE TITLE
[tangoe.me] Support for live streaming website tango.me

### ISSUE THREAD

**Issue by raaron773** [yt-dlp/yt-dlp#11433]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

- Single video: https://tango.me/stream/NbZIryrYlvvAC01RCV8dcw
- Single video: https://tango.me/immm11

### Provide a description that is worded well enough to be understood

It says unsupoprted URL because it's redirecting to tango.me/stream/noscript.html. I even tried with cookies

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --cookies-from-browser firefox https://tango.me/stream/NbZIryrYlvvAC01RCV8dcw -vU

[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://tango.me/stream/NbZIryrYlvvAC01RCV8dcw', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.7 (CPython x86_64 64bit) - Linux-6.11.5-arch1-1-x86_64-with-glibc2.40 (OpenSSL 3.4.0 22 Oct 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/$USER/.mozilla/firefox/cl8j9z4o.default-release/cookies.sqlite"
Extracted 3071 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.08.06 from yt-dlp/yt-dlp
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[generic] Extracting URL: https://tango.me/stream/NbZIryrYlvvAC01RCV8dcw
[generic] NbZIryrYlvvAC01RCV8dcw: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] NbZIryrYlvvAC01RCV8dcw: Extracting information
[debug] Looking for embeds
[redirect] Following redirect to https://tango.me/stream/noscript.html
[generic] Extracting URL: https://tango.me/stream/noscript.html
[generic] noscript: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] noscript: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://tango.me/stream/noscript.html
Traceback (most recent call last):
  File "/home/$USER/.local/share/pipx/venvs/yt-dlp/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.local/share/pipx/venvs/yt-dlp/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/$USER/.local/share/pipx/venvs/yt-dlp/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/$USER/.local/share/pipx/venvs/yt-dlp/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tango.me/stream/noscript.html
```

**Comment by bashonly** [comment]
> I even tried with cookies too.

does the site require you to be logged in to watch streams?

**Comment by raaron773** [comment]
> > I even tried with cookies too.
> 
> does the site require you to be logged in to watch streams?

Yes it does. The login options are either with google account, apple account or phone number.
I have used google account hence I tried it with using cookies.

**Comment by raaron773** [comment]
Hi, could someone help? Will this require changes in the code or is there a way I can find a way to download using yt-dlp without changes to yt-dlp itself?

**Comment by bashonly** [comment]
I don't have the time to work on this right now. Everything is done on a volunteer basis. Since you log in via Google account, you are likely not willing to share your account with a developer (and understandably so), making this issue difficult to work on. You'll have to be patient and wait for a developer who has their own account (or who has the time and motivation to create their own account) wants to work on this.

In the meantime, you could try sniffing out a m3u8/mpd url from your browser's dev tools and passing that to yt-dlp

**Comment by raaron773** [comment]
> I don't have the time to work on this right now. Everything is done on a volunteer basis. Since you log in via Google account, you are likely not willing to share your account with a developer (and understandably so), making this issue difficult to work on. You'll have to be patient and wait for a developer who has their own account (or who has the time and motivation to create their own account) and wants to work on this.
> 
> In the meantime, you could try sniffing out a m3u8/mpd url from your browser's dev tools and passing that to yt-dlp

I understand. I truly appreciate your efforts too!
I guess I don't mind sharing my google credentials if you're okay with it.

You can use that account whenever or however you feel like it - except deleting / closing it.
 I don't mind even if you take few months to a couple of year for it. I completely understand if you decide on not doing it as well.

**Comment by SlipperySlimes** [comment]
I was poking around and here's what I see so far. There is a `tokenData` fetch that happens every 10 seconds. It gives you values like `token` and `expireAt` in the response, and it sets cookies like `tt`, `ttu`, and `tte`. Those cookies are then part of the `master.m3u8` request when you click on a stream.

There is also a `watch?requestId` request that gives you the first part of the .m3u8 that includes the stream ID. This ID seems to differ from the one that is in the actual webpage URL.

So, in theory, you can make a request to the link from the `watch?requestId` request, with the cookies from the `tokenData` request. Or maybe there is a simpler way.

I hope this information is helpful to someone out there!

> Hi, could someone help? Will this require changes in the code or is there a way I can find a way to download using yt-dlp without changes to yt-dlp itself?

As a workaround, the links you can grab from the Following tab (not For You or Explore) have no extra authentication. So if you look for the `master.m3u8?token=[Really long string]` in your network requests, you can pass that straight into yt-dlp.

**Comment by raaron773** [comment]
> I was poking around and here's what I see so far. There is a `tokenData` fetch that happens every 10 seconds. It gives you values like `token` and `expireAt` in the response, and it sets cookies like `tt`, `ttu`, and `tte`. Those cookies are then part of the `master.m3u8` request when you click on a stream.
> 
> There is also a `watch?requestId` request that gives you the first part of the .m3u8 that includes the stream ID. This ID seems to differ from the one that is in the actual webpage URL.
> 
> So, in theory, you can make a request to the link from the `watch?requestId` request, with the cookies from the `tokenData` request. Or maybe there is a simpler way.
> 
> I hope this information is helpful to someone out there!
> 
> > Hi, could someone help? Will this require changes in the code or is there a way I can find a way to download using yt-dlp without changes to yt-dlp itself?
> 
> As a workaround, the links you can grab from the Following tab (not For You or Explore) have no extra authentication. So if you look for the `master.m3u8?token=[Really long string]` in your network requests, you can pass that straight into yt-dlp.


This is interesting. The `master.m3u8?token=...` only appears when I refresh the "following" page and if my cursor is already on the stream's preview. It works though so thank you.

**Comment by raaron773** [comment]
> > I was poking around and here's what I see so far. There is a `tokenData` fetch that happens every 10 seconds. It gives you values like `token` and `expireAt` in the response, and it sets cookies like `tt`, `ttu`, and `tte`. Those cookies are then part of the `master.m3u8` request when you click on a stream.
> > There is also a `watch?requestId` request that gives you the first part of the .m3u8 that includes the stream ID. This ID seems to differ from the one that is in the actual webpage URL.
> > So, in theory, you can make a request to the link from the `watch?requestId` request, with the cookies from the `tokenData` request. Or maybe there is a simpler way.
> > I hope this information is helpful to someone out there!
> > > Hi, could someone help? Will this require changes in the code or is there a way I can find a way to download using yt-dlp without changes to yt-dlp itself?
> > 
> > 
> > As a workaround, the links you can grab from the Following tab (not For You or Explore) have no extra authentication. So if you look for the `master.m3u8?token=[Really long string]` in your network requests, you can pass that straight into yt-dlp.
> 
> This is interesting. The `master.m3u8?token=...` only appears when I refresh the "following" page and if my cursor is already on the stream's preview or if the first thing I point my cursor to is the stream I want to download.
> 
> It works though so thank you.

This no longer works as expected.. the link stops downloading randomly after 2-3 minutes

**Comment by MrR00tsuz** [comment]
https://github.com/MrR00tsuz/tango.me-live-stream-find
https://github.com/MrR00tsuz/tango.me-live-stream-recorder

**Comment by raaron773** [comment]
> https://github.com/MrR00tsuz/tango.me-live-stream-find https://github.com/MrR00tsuz/tango.me-live-stream-recorder

Says 404

**Comment by Devanagaraj** [comment]
> https://github.com/MrR00tsuz/tango.me-live-stream-find https://github.com/MrR00tsuz/tango.me-live-stream-recorder

It's gives 404, The issue is still there.

**Comment by figma6** [comment]
> I was poking around and here's what I see so far. There is a `tokenData` fetch that happens every 10 seconds. It gives you values like `token` and `expireAt` in the response, and it sets cookies like `tt`, `ttu`, and `tte`. Those cookies are then part of the `master.m3u8` request when you click on a stream.
> 
> There is also a `watch?requestId` request that gives you the first part of the .m3u8 that includes the stream ID. This ID seems to differ from the one that is in the actual webpage URL.
> 
> So, in theory, you can make a request to the link from the `watch?requestId` request, with the cookies from the `tokenData` request. Or maybe there is a simpler way.
> 
> I hope this information is helpful to someone out there!
> 
> > Hi, could someone help? Will this require changes in the code or is there a way I can find a way to download using yt-dlp without changes to yt-dlp itself?
> 
> As a workaround, the links you can grab from the Following tab (not For You or Explore) have no extra authentication. So if you look for the `master.m3u8?token=[Really long string]` in your network requests, you can pass that straight into yt-dlp.

any progress on this website?

**Comment by figma6** [comment]
> https://github.com/MrR00tsuz/tango.me-live-stream-find https://github.com/MrR00tsuz/tango.me-live-stream-recorder

can you upload again

**Comment by Matrimony0065** [comment]
🇹🇷 Türkçe

TANGO LIVE RECORDER ile Tango ve Pulsz platformlarındaki public, private, group ve 1:1 canlı yayınları kolayca kaydedebilirsiniz. TANGO LIVE RECORDER, yüksek kaliteli kayıt, hızlı işlem ve kolay kullanım sunan güçlü bir Telegram botudur. İster herkese açık yayınları ister özel yayınları kaydetmek isteyin, TANGO LIVE RECORDER tüm kayıt ihtiyaçlarınız için güvenilir bir çözümdür. Canlı yayınları kaçırmadan kaydedin, istediğiniz zaman tekrar izleyin ve kayıtlarınızı güvenle saklayın.

👉 TANGO LIVE RECORDER: https://t.me/liveRecordsBot

🇬🇧 English

TANGO LIVE RECORDER lets you record public, private, group, and 1:1 live broadcasts on Tango and Pulsz with ease. Designed for speed, reliability, and high-quality recordings, TANGO LIVE RECORDER is a powerful Telegram bot that helps you save live streams and watch them whenever you want. Whether you want to record public streams or private sessions, TANGO LIVE RECORDER provides a simple and efficient recording experience.

👉 TANGO LIVE RECORDER: https://t.me/liveRecordsBot

🇸🇦 العربية

يتيح لك TANGO LIVE RECORDER تسجيل البثوث العامة، الخاصة، الجماعية، وجلسات 1:1 على منصتي Tango وPulsz بسهولة وجودة عالية. تم تصميم TANGO LIVE RECORDER ليكون سريعًا وموثوقًا وسهل الاستخدام، مما يسمح لك بحفظ البثوث المباشرة ومشاهدتها في أي وقت. سواء كنت ترغب في تسجيل البثوث العامة أو الخاصة، فإن TANGO LIVE RECORDER يوفر لك تجربة تسجيل مميزة.

👉 TANGO LIVE RECORDER: https://t.me/liveRecordsBot
