### ISSUE TITLE
[NicoNico] Unable to fetch data: HTTP Error 400: Bad Request - geo-restriction not being detected by yt-dlp

### ISSUE THREAD

**Issue by Kutsika** [yt-dlp/yt-dlp#11430]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA, Japan

### Provide a description that is worded well enough to be understood

Whenever I try and download any video from NicoNico, it always results in "Unable to fetch data: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)" even if the video isn't blocked behind a login requirement.

I tried a few different videos but none download, opening them in my browser loads and plays them just fine.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--check-formats', '--no-warnings', '--cookies-from-browser', 'firefox', '--no-check-certificate', 'https://www.nicovideo.jp/watch/so44275623']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-117657-gfe21944656-20241026 (setts), ffprobe N-117657-gfe21944656-20241026
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\sunka\AppData\Roaming\Mozilla\Firefox\Profiles\0c2fe4fr.default-release\cookies.sqlite"
Extracted 2534 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[niconico] Extracting URL: https://www.nicovideo.jp/watch/so44275623
[niconico] so44275623: Downloading webpage
[niconico] so44275623: Downloading API JSON
ERROR: [niconico] so44275623: Unable to fetch data: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\niconico.py", line 463, in _real_extract
  File "yt_dlp\extractor\common.py", line 1151, in download_content
  File "yt_dlp\extractor\common.py", line 1111, in download_handle
  File "yt_dlp\extractor\common.py", line 961, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 910, in _request_webpage

  File "yt_dlp\extractor\common.py", line 897, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\niconico.py", line 451, in _real_extract
  File "yt_dlp\extractor\common.py", line 961, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 910, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download webpage: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 897, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request
```

**Comment by Maulmere** [comment]
Nicovideo recently had their guidelines changed to exclude certain videos from being viewable to users outside of Japan.
![image](https://github.com/user-attachments/assets/157a2941-9fc7-42b6-b8a6-7d030b152ec4)

I had the same problem you did, because these new guidelines apparently bricked yt-dlp's ability to download said videos, since the developers don't have any servers based in Japan. (merely speculating on the code, take this with a grain of salt)
![image](https://github.com/user-attachments/assets/a3aa8b1a-4d16-4d2d-b21d-b38062ed9acf)

**Comment by bashonly** [comment]
Some of the extractor test URLs work just fine for me (e.g. `https://www.nicovideo.jp/watch/sm22312215`), but I also get HTTP Error 400 with OP's example URL. When I look at the response, I see `"errorCode":"FORBIDDEN","reasonCode":"DOMESTIC_VIDEO"`, which seems to indicate the above-mentioned geo-restriction. All we can do in this case is catch the unexpected 400 error and raise the appropriate geo-restriction error instead

**Comment by Kutsika** [comment]
Does that mean there's no way to download videos from there without using a VPN or something like since every video is Geo-restricted? At least until NicoNico changes something on their end?

**Comment by bashonly** [comment]
Not every video is geo-restricted. I gave an example URL of one that isn't in my last comment. But if a video is geo-restricted, there's most likely nothing yt-dlp can do about that

**Comment by Kutsika** [comment]
Is there a way to know which videos are Geo-restricted? I looked at the example URL but couldn't find anything indicated that it wasn't Geo-restricted

**Comment by Maulmere** [comment]
I'm not sure I'm man enough to say it, but they're more likely to restrict a video if it has _adult themes_.
Yes, I found that out the hard way. No, I'm not proud of myself.

**Comment by bashonly** [comment]
> since the developers don't have any servers based in Japan.

yt-dlp devs don't have any servers based anywhere. yt-dlp runs locally on your machine sends requests directly to the site you are downloading from. It is entirely dependent on the IP address of your computer.

> Is there a way to know which videos are Geo-restricted? 

Ideally that's what a patch to fix this in yt-dlp would do: properly detect geo-block and error with a more informative message. That's why this issue is being kept open: yt-dlp can't bypass the geo-restriction but it should let the user know that's why the download is failing.

**Comment by toomyzoom** [comment]
> Some of the extractor test URLs work just fine for me (e.g. `https://www.nicovideo.jp/watch/sm22312215`), but I also get HTTP Error 400 with OP's example URL. When I look at the response, I see `"errorCode":"FORBIDDEN","reasonCode":"DOMESTIC_VIDEO"`, which seems to indicate the above-mentioned geo-restriction. All we can do in this case is catch the unexpected 400 error and raise the appropriate geo-restriction error instead

There is also `'errorCode' 'FORBIDDEN', 'reasonCode' 'HIGH_RISK_COUNTRY_VIDEO'`.

I tested a few links with geoblock and realize they don't guard their `delivery.domand.nicovideo.jp` or `nvapi.nicovideo.jp` domain, only `www.nicovideo.jp` to prevent you from grabbing initial valid `server-response`. As long as you're able to get that data, you can get `nvapi.nicovideo.jp` a valid link and stream it from `delivery.domand.nicovideo.jp` without the blocking.

**Comment by fireattack** [comment]
For what it's worth, their geo-restriction IP ranges isn't consistent across the site either. This newly added restriction on certain videos are different from previously existing restriction on certain livestreams (live.nicovideo.jp).

E.g. I can open (but not play, due to not having the membership) OP's link with proxy 1 in JP but not proxy 2 in JP. 
But for a typical livestream that restricts non-Japan IP, e.g. https://live.nicovideo.jp/watch/lv345832886, I can open with proxy 2 but not proxy 1.

**Comment by jojo2833432** [comment]
To an average joe like myself? How would I download videos from niconico? I have a VPN ready, but I cant seem to bulk download from a search page or tag site? How do I download properly?!

**Comment by jojo2833432** [comment]
When I download, it downloads the video and audio separately?! and it wont let me move the video scroll wheel?

**Comment by bashonly** [comment]
> To an average joe like myself? ...I have a VPN ready, but I cant seem to bulk download

@jojo2833432 I didn't know average joes did bulk downloading. Seems more like power user thing. This question has nothing to do with this issue. **Please refrain from off-topic comments or else you will be blocked from the repository.** 

> When I download, it downloads the video and audio separately?! and it wont let me move the video scroll wheel? How do I make so that it doesnt do that?

It sounds like you don't have ffmpeg installed. Install ffmpeg. But again, this is off-topic
