### ISSUE TITLE
Support for Livestream website Parti

### ISSUE THREAD

**Issue by GTAXL** [yt-dlp/yt-dlp#11434]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

Single video: https://parti.com/video/3121
Single video: https://parti.com/video/3160

### Provide a description that is worded well enough to be understood

This is a newer livestream platform for content creators. You can watch past broadcasts as listed above without signing in. When I put the link in yt-dlp, it defaults to the generic extractor which fails.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[gtaxl@jetstream:youtube]./yt-dlp -F -vU https://parti.com/video/3121
[debug] Command-line config: ['-F', '-vU', 'https://parti.com/video/3121']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-32-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.7-0, ffprobe 4.3.7-0
[debug] Optional libraries: certifi-2020.06.20, requests-2.25.1, sqlite3-3.34.1, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://parti.com/video/3121
[generic] 3121: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 3121: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://parti.com/video/3121
Traceback (most recent call last):
  File "/home/gtaxl/youtube/./yt-dlp/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gtaxl/youtube/./yt-dlp/yt_dlp/YoutubeDL.py", line 1760, in __extract_info
    ie_result = ie.extract(url)
  File "/home/gtaxl/youtube/./yt-dlp/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/home/gtaxl/youtube/./yt-dlp/yt_dlp/extractor/generic.py", line 2533, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://parti.com/video/3121

[gtaxl@jetstream:youtube]
```

**Comment by KabirHere** [comment]
Doesn't look like it works or is it just me?

```sh
PS C:\Users\Shahriar Kabir> yt-dlp -vU https://parti.com/video/3121
[debug] Command-line config: ['-vU', 'https://parti.com/video/3121']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.12.08 from yt-dlp/yt-dlp [7a52ff29d] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26200-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-121938-g2456a39581-20251130 (setts), ffprobe N-121938-g2456a39581-20251130
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.2.0, certifi-2025.11.12, curl_cffi-0.13.0, mutagen-1.47.0, requests-2.32.5, sqlite3-3.40.1, urllib3-2.6.0, websockets-15.0.1, yt_dlp_ejs-0.3.2
[debug] JS runtimes: deno-2.6.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1854 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.12.08 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.12.08 from yt-dlp/yt-dlp)
[parti:video] Extracting URL: https://parti.com/video/3121
[parti:video] 3121: Downloading webpage
ERROR: [parti:video] 3121: Unable to download JSON metadata: HTTPSConnection(host='api-backend.parti.com', port=443): Failed to resolve 'api-backend.parti.com' ([Errno 11001] getaddrinfo failed) (caused by TransportError("HTTPSConnection(host='api-backend.parti.com', port=443): Failed to resolve 'api-backend.parti.com' ([Errno 11001] getaddrinfo failed)"))
  File "yt_dlp\extractor\common.py", line 762, in extract
  File "yt_dlp\extractor\parti.py", line 32, in _real_extract
  File "yt_dlp\extractor\parti.py", line 8, in _call_api
  File "yt_dlp\extractor\common.py", line 1150, in download_content
  File "yt_dlp\extractor\common.py", line 1108, in download_handle
  File "yt_dlp\extractor\common.py", line 973, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 922, in _request_webpage

  File "urllib3\connection.py", line 204, in _new_conn
  File "urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 324, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 644, in send
  File "urllib3\connectionpool.py", line 841, in urlopen
  File "urllib3\util\retry.py", line 449, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\connectionpool.py", line 488, in _make_request
  File "urllib3\connectionpool.py", line 464, in _make_request
  File "urllib3\connectionpool.py", line 1093, in _validate_conn
  File "urllib3\connection.py", line 759, in connect
  File "urllib3\connection.py", line 211, in _new_conn
urllib3.exceptions.NameResolutionError: HTTPSConnection(host='api-backend.parti.com', port=443): Failed to resolve 'api-backend.parti.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 909, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4252, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 194, in wrapper
  File "yt_dlp\networking\common.py", line 359, in send
  File "yt_dlp\networking\_requests.py", line 352, in _send
yt_dlp.networking.exceptions.TransportError: HTTPSConnection(host='api-backend.parti.com', port=443): Failed to resolve 'api-backend.parti.com' ([Errno 11001] getaddrinfo failed)

PS C:\Users\Shahriar Kabir>
```

**Comment by seproDev** [comment]
@shahriarkabir-sagor
```
yt-dlp --update-to master
```
Next time, please open a new issue, instead of necroing an old one.

**Comment by KabirHere** [comment]
> [@shahriarkabir-sagor](https://github.com/shahriarkabir-sagor)
> 
> ```
> yt-dlp --update-to master
> ```
> 
> Next time, please open a new issue, instead of necroing an old one.

I wasn't sure if it is really a problem that's why I didn't feel right to create a whole new issue on github
