### ISSUE TITLE
Error downloading videos from X/Twitter

### ISSUE THREAD

**Issue by lkintact** [yt-dlp/yt-dlp#11440]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Yt-dlp doesn't download videos from https://x.com.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://x.com/allreactionvidz/status/1552920481254211585']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out cp1251 (No VT), error cp1251 (No VT), screen cp1251 (No VT)
[debug] yt-dlp version nightly@2024.11.02.232942 from yt-dlp/yt-dlp-nightly-builds [422195ec7] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-117612-gc98810ab47-20241018 (setts), ffprobe N-117612-gc98810ab47-20241018
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.02.232942 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.02.232942 from yt-dlp/yt-dlp-nightly-builds)
[twitter] Extracting URL: https://x.com/allreactionvidz/status/1552920481254211585
[twitter] 1552920481254211585: Downloading guest token
ERROR: [twitter] 1552920481254211585: Unable to download JSON metadata: EOF occurred in violation of protocol (_ssl.c:1007) (caused by SSLError('EOF occurred in violation of protocol (_ssl.c:1007)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\twitter.py", line 1422, in _real_extract
  File "yt_dlp\extractor\twitter.py", line 1400, in _extract_status
  File "yt_dlp\extractor\twitter.py", line 331, in _call_graphql_api
  File "yt_dlp\extractor\twitter.py", line 309, in _call_api
  File "yt_dlp\extractor\twitter.py", line 158, in _fetch_guest_token
  File "yt_dlp\extractor\common.py", line 1152, in download_content
  File "yt_dlp\extractor\common.py", line 1112, in download_handle
  File "yt_dlp\extractor\common.py", line 962, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 911, in _request_webpage

  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 730, in connect
  File "urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 449, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 328, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 711, in send
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 898, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4162, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 346, in _send
yt_dlp.networking.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1007)
```

**Comment by bashonly** [comment]
I can't reproduce the issue.

This may be related to:
- https://github.com/net4people/bbs/issues/106
- https://github.com/net4people/bbs/issues/65
- https://censoredplanet.org/throttling
- https://github.com/net4people/bbs/issues/382
- https://github.com/yt-dlp/yt-dlp/issues/10443

Does the link work in your browser with same internet connection/setup?

**Comment by lkintact** [comment]
Sorry, I've been using a censorship circumvention tool for my browser for so long that I completely forgot that X/Twitter is banned in Russia... I guess the issue can be closed, thank you.
