### ISSUE TITLE
增加网站支持/Enhance website compatibility：http://www.docuchina.cn/

### ISSUE THREAD

**Issue by GH2506** [yt-dlp/yt-dlp#11465]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [x] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

中国China

### Example URLs

http://www.docuchina.cn/
http://www.docuchina.cn/2014/01/21/VIDE1390293257217732.shtml

### Provide a description that is worded well enough to be understood

无法从这个网站下载视频，希望增加对这个网站的支持
Unable to download videos from this website; please consider adding support for it.
http://www.docuchina.cn/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'http://www.docuchina.cn/2014/01/21/VIDE1390293257217732.shtml']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0-full_build-www.gyan.dev (setts), ffprobe 7.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[generic] Extracting URL: http://www.docuchina.cn/2014/01/21/VIDE1390293257217732.shtml
[generic] VIDE1390293257217732: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] VIDE1390293257217732: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: http://www.docuchina.cn/2014/01/21/VIDE1390293257217732.shtml
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1760, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: http://www.docuchina.cn/2014/01/21/VIDE1390293257217732.shtml
```

**Comment by dirkf** [comment]
The problem URL VIDE1390293257217732.shtml can be downloaded by the CCTV extractor with this change:
```diff
--- old/yt-dlp/yt_dlp/extractor/cctv.py
+++ new/yt-dlp/yt_dlp/extractor/cctv.py
@@ -10,7 +10,7 @@
 
 class CCTVIE(InfoExtractor):
     IE_DESC = '央视网'
-    _VALID_URL = r'https?://(?:(?:[^/]+)\.(?:cntv|cctv)\.(?:com|cn)|(?:www\.)?ncpa-classic\.com)/(?:[^/]+/)*?(?P<id>[^/?#&]+?)(?:/index)?(?:\.s?html|[?#&]|$)'
+    _VALID_URL = r'https?://(?:(?:[^/]+)\.(?:cntv|cctv)\.(?:com|cn)|(?:www\.)?(?:ncpa-classic\.com|docuchina\.cn))/(?:[^/]+/)*?(?P<id>[^/?#&]+?)(?:/index)?(?:\.s?html|[?#&]|$)'
     _TESTS = [{
         # fo.addVariable("videoCenterId","id")
         'url': 'http://sports.cntv.cn/2016/02/12/ARTIaBRxv4rTT1yWf1frW2wi160212.shtml',
```
Maybe other pages need more work. Also, only 360p video is found; the browser API response shows several more apparently DRMed resolutions.

**Comment by ShashwatDubey99** [comment]
> The problem URL VIDE1390293257217732.shtml can be downloaded by the CCTV extractor with this change:
> 
> ```diff
> --- old/yt-dlp/yt_dlp/extractor/cctv.py
> +++ new/yt-dlp/yt_dlp/extractor/cctv.py
> @@ -10,7 +10,7 @@
>  
>  class CCTVIE(InfoExtractor):
>      IE_DESC = '央视网'
> -    _VALID_URL = r'https?://(?:(?:[^/]+)\.(?:cntv|cctv)\.(?:com|cn)|(?:www\.)?ncpa-classic\.com)/(?:[^/]+/)*?(?P<id>[^/?#&]+?)(?:/index)?(?:\.s?html|[?#&]|$)'
> +    _VALID_URL = r'https?://(?:(?:[^/]+)\.(?:cntv|cctv)\.(?:com|cn)|(?:www\.)?(?:ncpa-classic\.com|docuchina\.cn))/(?:[^/]+/)*?(?P<id>[^/?#&]+?)(?:/index)?(?:\.s?html|[?#&]|$)'
>      _TESTS = [{
>          # fo.addVariable("videoCenterId","id")
>          'url': 'http://sports.cntv.cn/2016/02/12/ARTIaBRxv4rTT1yWf1frW2wi160212.shtml',
> ```
> 
> Maybe other pages need more work. Also, only 360p video is found; the browser API response shows several more apparently DRMed resolutions.

i have a similar problem with a other site , the site shows many other resolutions available but only 360p option is working for yt-dlp , is there a fix to it

**Comment by ShashwatDubey99** [comment]
no worries that was a apt issue , it fixed when i used bin

**Comment by ShashwatDubey99** [comment]
> > i have a similar problem with a other site , the site shows many other resolutions available but only 360p option is working for yt-dlp , is there a fix to it edit:pytho versio is workig
> 
> > no worries that was a apt issue , it fixed when i used bin
> 
> Could you please elaborate on how you solved the problem that "the website shows many other resolutions available, but only the 360p option works with yt-dlp"?

So i first used the flag --allow-u which which also gives option to download video which aren't available to play , not sure what it does but it gives some extra video urls which are maybe not entirely supported or understood by yt-dlp yet, when i used the apt version of yt-dlp , it didn't got what i need , so later i tried python version after uninstalling the apt version it did worked so i thought it was a bin problem but it was just issue with the apt version of yt-dlp for my ubuntu server .maybe bcz of something i did wrong to my system

**Comment by bashonly** [comment]
`--allow-u` is a developer option and it is not supported for end users.

**Comment by bashonly** [comment]
The original issue where the docuchina domain is not matched by the extractor has not been fixed. Let's keep this open until the patch is applied in yt-dlp

**Comment by ShashwatDubey99** [comment]
> The original issue where the docuchina domain is not matched by the extractor has not been fixed. Let's keep this open until the patch is applied in yt-dlp
So was this same withme , ? or just docuchina
