### ISSUE TITLE
Some crypto error while using in derbian 

### ISSUE THREAD

**Issue by kunani1** [yt-dlp/yt-dlp#11479]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Any body help 

C:\home\user\Desktop> yt-dlp https://www.mxplayer.in/show/watch-and-the-winner-is-love-hindi-dubbed/season-1/episode-1-onlie-0d4ec6dae18c52b35f585f58429106c5?watch=true
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/bin/yt-dlp/__main__.py", line 14, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 18, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/cookies.py", line 23, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/aes.py", line 5, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/dependencies/__init__.py", line 82, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/dependencies/Cryptodome.py", line 19, in <module>
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/__init__.py", line 3, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/_mode_ecb.py", line 34, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 258, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Trying '_raw_ecb.cpython-311-x86_64-linux-gnu.so': /usr/lib/python3/dist-packages/Cryptodome/Util/../Cipher/_raw_ecb.cpython-311-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.abi3.so': /usr/lib/python3/dist-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.so': /usr/lib/python3/dist-packages/Cryptodome/Util/../Cipher/_raw_ecb.so: cannot open shared object file: No such file or directory
C:\home\user\Desktop>

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Any body help 

C:\home\user\Desktop> yt-dlp https://www.mxplayer.in/show/watch-and-the-winner-is-love-hindi-dubbed/season-1/episode-1-onlie-0d4ec6dae18c52b35f585f58429106c5?watch=true
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/bin/yt-dlp/__main__.py", line 14, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 18, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/cookies.py", line 23, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/aes.py", line 5, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/dependencies/__init__.py", line 82, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/dependencies/Cryptodome.py", line 19, in <module>
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/__init__.py", line 3, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/_mode_ecb.py", line 34, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 258, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Trying '_raw_ecb.cpython-311-x86_64-linux-gnu.so': /usr/lib/python3/dist-packages/Cryptodome/Util/../Cipher/_raw_ecb.cpython-311-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.abi3.so': /usr/lib/python3/dist-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.so': /usr/lib/python3/dist-packages/Cryptodome/Util/../Cipher/_raw_ecb.so: cannot open shared object file: No such file or directory
C:\home\user\Desktop>
```

**Comment by kunani1** [comment]
Unable to install Cryptodome

**Comment by seproDev** [comment]
How did you install yt-dlp? How did you attempt to install pycryptodomex? What was the error message?

**Comment by kunani1** [comment]
C:\home\user\Desktop> pip install pycryptodome
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
           ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
C:\home\user\Desktop> 

I used this pip install pycryptodome

**Comment by kunani1** [comment]
After using this sudo apt update
sudo apt install python3-distutils

This error coming 

C:\home\user\Desktop> yt-dlp https://www.mxplayer.in/show/watch-and-the-winner-is-love-hindi-dubbed/season-1/episode-1-online-0d4ec6dae18c52b35f585f58429106c5?watch=true
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/bin/yt-dlp/__main__.py", line 14, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 18, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/cookies.py", line 23, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/aes.py", line 5, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/dependencies/__init__.py", line 82, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/dependencies/Cryptodome.py", line 19, in <module>
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/__init__.py", line 3, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/_mode_ecb.py", line 34, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 258, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Trying '_raw_ecb.cpython-311-x86_64-linux-gnu.so': /usr/lib/python3/dist-packages/Cryptodome/Util/../Cipher/_raw_ecb.cpython-311-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.abi3.so': /usr/lib/python3/dist-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: No such file or directory, Trying '_raw_ecb.so': /usr/lib/python3/dist-packages/Cryptodome/Util/../Cipher/_raw_ecb.so: cannot open shared object file: No such file or directory
C:\home\user\Desktop>

**Comment by seproDev** [comment]
Difficult to say, to me, this looks like a broken Python installation.
I would recommend just using the standalone Linux binary [yt-dlp_linux](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux) until you can figure out what happened to your python install. We cannot provide support for your operating system.

**Comment by bashonly** [comment]
closing in favor of #11506
