### ISSUE TITLE
[rutube] Connection to bl.rutube.ru timed out => No video formats found!

### ISSUE THREAD

**Issue by phpony** [yt-dlp/yt-dlp#11476]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Current yt-dlp doesn't download any videos from rutube.ru at all. 

The errors are `Connection to bl.rutube.ru timed out. (connect timeout=20.0)` followed by `No video formats found!`. With and without VPN. 

Also tried `--user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0" --cookies-from-browser firefox`  with no help. But in Firefox video plays.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://rutube.ru/video/d144161b680dbc3a864c1587632b18f7/', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (zip)
[debug] Python 3.12.6 (CPython x86_64 64bit) - Linux-6.11.2-amd64-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2-3 (setts), ffprobe 7.0.2-3, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[rutube] Extracting URL: https://rutube.ru/video/d144161b680dbc3a864c1587632b18f7/
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading video JSON
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading options JSON
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading m3u8 information
WARNING: [rutube] Failed to download m3u8 information: (<urllib3.connection.HTTPConnection object at 0x7fca20f0ccb0>, 'Connection to bl.rutube.ru timed out. (connect timeout=20.0)')
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading m3u8 information
WARNING: [rutube] Failed to download m3u8 information: (<urllib3.connection.HTTPConnection object at 0x7fca20f0d460>, 'Connection to bl.rutube.ru timed out. (connect timeout=20.0)')
ERROR: [rutube] d144161b680dbc3a864c1587632b18f7: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2846, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1122, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [rutube] d144161b680dbc3a864c1587632b18f7: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by phpony** [comment]
Exactly same behavior for both master and nightly:

```
[...]
Latest version: master@2024.11.06.215904 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.11.06.215904 from yt-dlp/yt-dlp-master-builds)
[...]
WARNING: [rutube] Failed to download m3u8 information: (<urllib3.connection.HTTPConnection object at 0x7fbde7180410>, 'Connection to bl.rutube.ru timed out. (connect timeout=20.0)')
[...]
ERROR: [rutube] d144161b680dbc3a864c1587632b18f7: No video formats found!
```

```
[...]
Latest version: nightly@2024.11.06.232826 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.06.232826 from yt-dlp/yt-dlp-nightly-builds)
[...]
WARNING: [rutube] Failed to download m3u8 information: (<urllib3.connection.HTTPConnection object at 0x7fbde7180410>, 'Connection to bl.rutube.ru timed out. (connect timeout=20.0)')
[...]
ERROR: [rutube] d144161b680dbc3a864c1587632b18f7: No video formats found!
```

**Comment by phpony** [comment]
The Firefox's Developer Tools are stating the browser does connect successfully to bl.rutube.ru:

```
GET https://bl.rutube.ru/route/d144161b680dbc3a864c1587632b18f7.m3u8?... 

HTTP/2 200 
server: QRATOR
date: Fri, 08 Nov 2024 08:05:52 GMT
content-type: text/html; charset=utf-8
temperature: {'short': 2, 'long': 4}
dest-server: river-2-301
client-ip: X.X.X.X
x-frontend-config-version: 3.8.2
access-control-allow-origin: *
access-control-allow-methods: GET, HEAD
access-control-allow-headers: Range
access-control-expose-headers: Range, Content-Length, Accept-Ranges, Date
access-control-allow-credentials: true
content-encoding: br
X-Firefox-Spdy: h2
```

Seems like QRATOR (rutube's anti-ddos service of choice) somehow detects yt-dlp's requests and block them?

**Comment by phpony** [comment]
Just tried to "wget" the m3u8 link directly from console and it works too. So it allows any user-agent, even wget. The problem must be somewhere inside the extractor:

```
$ wget "https://bl.rutube.ru/route/d144161b680dbc3a864c1587632b18f7.m3u8?..."
Resolving bl.rutube.ru (bl.rutube.ru)... 178.248.232.241
Connecting to bl.rutube.ru (bl.rutube.ru)|178.248.232.241|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1642 (1.6K) [text/html]

=> correct m3u8 file.
```

**Comment by seproDev** [comment]
Seems like this fixes it:
```diff
diff --git a/yt_dlp/extractor/rutube.py b/yt_dlp/extractor/rutube.py
index 2c416811a..c77e0bf8a 100644
--- a/yt_dlp/extractor/rutube.py
+++ b/yt_dlp/extractor/rutube.py
@@ -61,7 +61,7 @@ def _download_api_options(self, video_id, query=None):
             query = {}
         query['format'] = 'json'
         return self._download_json(
-            f'http://rutube.ru/api/play/options/{video_id}/',
+            f'https://rutube.ru/api/play/options/{video_id}/',
             video_id, 'Downloading options JSON',
             'Unable to download options JSON',
             headers=self.geo_verification_headers(), query=query)
```

**Comment by phpony** [comment]
Yep, can confirm this patch does the job. It works with it:

```
[debug] Command-line config: ['https://rutube.ru/video/d144161b680dbc3a864c1587632b18f7/', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (linux_exe)
[debug] Python 3.12.6 (CPython x86_64 64bit) - Linux-6.11.2-amd64-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2-3 (setts), ffprobe 7.0.2-3, phantomjs broken
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[rutube] Extracting URL: https://rutube.ru/video/d144161b680dbc3a864c1587632b18f7/
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading video JSON
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading options JSON
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading m3u8 information
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] d144161b680dbc3a864c1587632b18f7: Downloading 1 format(s): m3u8-406-1
[debug] Invoking hlsnative downloader on "https://river-1.rutube.ru/hls-vod/QJgc4k_gFwQXtJK3H3QXaA/1731661417/1944/rutube-ds-origin-118-1/ebb02cbd26b04bf5a83e50c038e49b90.mp4.m3u8?i=1280x720_406"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 45
[download] Destination: yt-dlp, the best youtube-dl alternative with more features [d144161b680dbc3a864c1587632b18f7].mp4
[download] 100% of   12.26MiB in 00:00:08 at 1.50MiB/s
```

**Comment by WlaBo75** [comment]
Additional info: patch is working. Without the patch it's not possible to download any video.

**Comment by m0rtal** [comment]
Strange, but it's not working for me:
```
[debug] Command-line config: ['https://rutube.ru/video/d144161b680dbc3a864c1587632b18f7/', '-vU']
[debug] Home config "yt-dlp.conf": ['--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.06.232826 from yt-dlp/yt-dlp-nightly-builds [be3579aaf] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-48-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, pyxattr-0.8.1, requests-2.32.3, sqlite3-3.45.1, urllib3-2.0.7, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeFeedsInfoExtractor), oauth2 (YoutubeHistoryIE), oauth2 (YoutubeIE), oauth2 (YoutubeLivestreamEmbedIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubePlaylistIE), oauth2 (YoutubeRecommendedIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeShortsAudioPivotIE), oauth2 (YoutubeSubscriptionsIE), oauth2 (YoutubeTabIE), oauth2 (YoutubeTruncatedIDIE), oauth2 (YoutubeTruncatedURLIE), oauth2 (YoutubeWatchLaterIE), oauth2 (YoutubeYtBeIE), oauth2 (YoutubeYtUserIE)
[debug] Plugin directories: ['/home/m0rtal/.local/lib/python3.12/site-packages/yt_dlp_plugins']
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.06.232826 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.06.232826 from yt-dlp/yt-dlp-nightly-builds)
WARNING: [rutube] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[rutube] Extracting URL: https://rutube.ru/video/d144161b680dbc3a864c1587632b18f7/
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading video JSON
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading options JSON
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading m3u8 information
WARNING: [rutube] Failed to download m3u8 information: (<urllib3.connection.HTTPConnection object at 0x7c9202ba05c0>, 'Connection to bl.rutube.ru timed out. (connect timeout=20.0)')
[rutube] d144161b680dbc3a864c1587632b18f7: Downloading m3u8 information
WARNING: [rutube] Failed to download m3u8 information: (<urllib3.connection.HTTPConnection object at 0x7c9202bd2fc0>, 'Connection to bl.rutube.ru timed out. (connect timeout=20.0)')
ERROR: [rutube] d144161b680dbc3a864c1587632b18f7: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/m0rtal/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m0rtal/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m0rtal/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m0rtal/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2846, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/m0rtal/.local/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1122, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [rutube] d144161b680dbc3a864c1587632b18f7: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by efremovmi** [comment]
Hello! Could you create a pull request? I have the same problem. If you can't do it, I can try to do it.

**Comment by seproDev** [comment]
I will create a PR and merge it later today

**Comment by dirkf** [comment]
I confirm that this works from UK. There are several other http: URLs used in the extractor that appear to be unaffected.

**Comment by dirkf** [comment]
Maybe also adopt patch from #11415 ?

**Comment by Black-Semargl** [comment]
Maybe change ALL "http" to "https" in extractor?

**Comment by walll-es** [comment]
Thank you very much for solving the problem! My bots have stopped parsing Rutube into the TG channel for a day and a half! But just adding one character 's' to **\on-dll-master\not in\extractor\rutube.py** solved the problem! By the way, this line looked different for me than in the example: So **'http://rutube.ru/api/play/options/%s /'%video_id,** now so **'https://rutube.ru/api/play/options/%s /' %video_id,** ! I use the unpacked rather old version 2023.12.30! I have already made changes to it for the site https://www.ntv.ru /, downloading from it worked! You can rate and support my channel with your subscription, it's almost 3 years old!**[@LATEST_RUSSIAN_NEWS](https://t.me/LATEST_RUSSIAN_NEWS)**

    Спасибо большое за решение проблемы! У меня мои боты перестали парсить Rutube в TG-канал уже дня полтора! Но всего лишь добавление одного символа **'s'** в **\yt-dlp-master\yt_dlp\extractor\rutube.py** решило проблему! Да, кстати, у меня эта строчка выглядела иначе, чем в примере: так **'http://rutube.ru/api/play/options/%s/' % video_id,** теперь так **'https://rutube.ru/api/play/options/%s/' % video_id,** ! Пользуюсь распакованной довольно старой версией 2023.12.30! Уже ранее в неё вносил изменения для сайта https://www.ntv.ru/, скачивание с него работало! Можете оценить и поддержать мой канал своей подпиской, ему уж почти 3 года! [@LATEST_RUSSIAN_NEWS](https://t.me/LATEST_RUSSIAN_NEWS)

**Comment by walll-es** [comment]
Does Rutube in the UK work for you directly, without a proxy and VPN?

**Comment by dirkf** [comment]
Yes, I was able to watch various items on the site as well as via yt-dl[p].

Maybe some content is being blocked at the whim of the President, as expressed through RKN, but I guess that might be arranged to affect access within Russia more than from other countries, say where Russia wages chemical and radiation warfare, so as to present some sort of democratic facade.
