### ISSUE TITLE
Tele5, not mediathek

### ISSUE THREAD

**Issue by Gloster10** [yt-dlp/yt-dlp#11482]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Germany

### Example URLs

https://tele5.de/the-cold-light-of-day

### Provide a description that is worded well enough to be understood

If the link will be https://tele5.de/mediathek/star-trek-deep-space-nine/tosk-der-gejagte, download will be possible, but if "mediathek" will be miss like as given, download will be no possiblle

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', '%(title)s.%(ext)s', '--cookies', 'cookies.txt', '--no-playlist', '-N', '8', 'https://tele5.de/the-cold-light-of-day']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-48-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: brotli-1.1.0, certifi-2023.11.17, requests-2.31.0, sqlite3-3.45.1, urllib3-2.0.7
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2024.11.04/SHA2-256SUMS
Current version: stable@2024.10.22 from yt-dlp/yt-dlp
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
Current Build Hash: a87033b5686c5512adcd26023c6ac4a56957d736f4653033e36901dbcc8bf7bb
Updating to stable@2024.11.04 from yt-dlp/yt-dlp ...
[debug] Downloading yt-dlp from https://github.com/yt-dlp/yt-dlp/releases/download/2024.11.04/yt-dlp
Updated yt-dlp to stable@2024.11.04 from yt-dlp/yt-dlp
[debug] Restarting: python3 /home/richard/.local/bin/yt-dlp -vU -o '%(title)s.%(ext)s' --cookies cookies.txt --no-playlist -N 8 https://tele5.de/the-cold-light-of-day
[debug] Command-line config: ['-vU', '-o', '%(title)s.%(ext)s', '--cookies', 'cookies.txt', '--no-playlist', '-N', '8', 'https://tele5.de/the-cold-light-of-day']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-48-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: brotli-1.1.0, certifi-2023.11.17, requests-2.31.0, sqlite3-3.45.1, urllib3-2.0.7
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://tele5.de/the-cold-light-of-day
[generic] the-cold-light-of-day: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] the-cold-light-of-day: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://tele5.de/the-cold-light-of-day
Traceback (most recent call last):
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1760, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2553, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tele5.de/the-cold-light-of-day
```

**Comment by Gloster10** [comment]
If net analysis willbe used, master masterm3u8 can be downloaded

**Comment by dirkf** [comment]
What happens if you just insert `/mediathek` at the start of the URL path, like https://tele5.de/mediathek/the-cold-light-of-day ?

**Comment by Gloster10** [comment]
@dirkf : 
Extracting URL: https://tele5.de/mediathek/the-cold-light-of-day
[Tele5] mediathek-the-cold-light-of-day: Downloading JSON metadata
ERROR: [Tele5] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)

I use https://tele5.de/the-cold-light-of-day and start networkanalysis.
Start the video and I will get the download via master.m3u8 : 

![Image](https://github.com/user-attachments/assets/734308c7-7714-4d6e-a496-a05861e84076)

Refer to the picture, get the address of master.m3u8 and make the download as usual with yt-dlp.

**Comment by dirkf** [comment]
Apparently s/t like this should work (also rolling in #10411):
```diff
--- old/yt_dlp/extractor/tele5.py
+++ new/yt_dlp/extractor/tele5.py
@@ -6,7 +6,7 @@
 
 
 class Tele5IE(DiscoveryPlusBaseIE):
-    _VALID_URL = r'https?://(?:www\.)?tele5\.de/(?P<parent_slug>[\w-]+)/(?P<slug_a>[\w-]+)(?:/(?P<slug_b>[\w-]+))?'
+    _VALID_URL = r'https?://(?:www\.)?tele5\.de/(?:(?P<parent_slug>[\w-]+)/)?(?P<slug_a>[\w-]+)(?(parent_slug)/(?P<slug_b>[\w-]+))?'
     _TESTS = [{
         # slug_a and slug_b
         'url': 'https://tele5.de/mediathek/stargate-atlantis/quarantane',
@@ -43,6 +43,22 @@
             'creators': ['Tele5'],
             'tags': [],
         },
+        'skip': 'Not found',
+    }, {
+        # no parent
+        'url': 'https://tele5.de/the-cold-light-of-day',
+        'info_dict': {
+            'id': '7640176',
+            'ext': 'mp4',
+            'title': 'The Cold Light of Day',
+            'description': r're:Eigentlich will der junge .{593} Gedreht wurde ausschließlich in Spanien\.$',
+            'upload_date': '20250520',
+            'timestamp': 1747770600,
+            'duration': 5398,
+            'thumbnail': 'https://eu1-prod-images.disco-api.com/2024/10/22/3cc63b62-64bb-305e-8ff7-06bc4f803bce.jpeg',
+            'creators': ['Tele5'],
+            'tags': [],
+        },
     }, {
         # playlist
         'url': 'https://tele5.de/mediathek/schlefaz',
@@ -59,15 +75,22 @@
         query = {'environment': 'tele5', 'v': '2'}
         if not slug_b:
             endpoint = f'page/{slug_a}'
-            query['parent_slug'] = parent_slug
+            if parent_slug:
+                query['parent_slug'] = parent_slug
         else:
             endpoint = f'videos/{slug_b}'
             query['filter[show.slug]'] = slug_a
         cms_data = self._download_json(f'https://de-api.loma-cms.com/feloma/{endpoint}/', playlist_id, query=query)
 
-        return self.playlist_result(map(
-            functools.partial(self._get_disco_api_info, url, disco_host='eu1-prod.disco-api.com', realm='dmaxde', country='DE'),
-            traverse_obj(cms_data, ('blocks', ..., 'videoId', {str}))), playlist_id)
+        video_ids = traverse_obj(cms_data, ('blocks', ..., 'videoId', {str}))
+
+        get_disco_api_info = functools.partial(
+            self._get_disco_api_info, url, disco_host='eu1-prod.disco-api.com', realm='dmaxde', country='DE')
+
+        if len(video_ids) == 1:
+            return get_disco_api_info(video_ids[0])
+
+        return self.playlist_result(map(get_disco_api_info, video_ids), playlist_id)
 
     def _update_disco_api_headers(self, headers, disco_base, display_id, realm):
         headers.update({
```
I was able to fetch the JSON that gave 404 in the test above using https://de-api.loma-cms.com/feloma/page/the-cold-light-of-day/?environment=tele5&v=2 (UK), including the `'videoId': '7640176',` needed to get the video from Discovery's library.

Otherwise please post the full trace from loading the target page and the request and response details (req/resp headers, query, data, response body) for the `POST` with `videoPlaybackInfo`. Feel free to censor any cookies or other headers that may contain private data.

**Comment by Gloster10** [comment]
@w4grfw, yes it works, thank you.
Tested with the link given by @w4grfw in 16659 : https://github.com/w4grfw/yt-dlp/tree/8e60a436ca338a62528b1d2db7c974f6be967832

**Comment by InvalidUsernameException** [comment]
This should be kept open until the linked PR has been merged.

**Comment by Gloster10** [comment]
The issue itself : Open since [Nov 9, 2024](https://github.com/yt-dlp/yt-dlp/issues/11482#issue-2645786568).
Nobody did before, I can live with  the link given by @w4grfw, :  https://github.com/w4grfw/yt-dlp/tree/8e60a436ca338a62528b1d2db7c974f6be967832
It works, for me , if the integration does fail, I have the link above. There fore I would prefer to still close this issue, it is solved, it does not depend on integration limits. 
And if the SW-SW integration does fail, I have the link, if not, the issue will be
also still solved.
Closed in any way.

**Comment by InvalidUsernameException** [comment]
This is labelled "site-request". So the scope of the issue is to track whether the necessary changes have been merged and integrated into the `master` branch (which means it has made it into a release or will make it into the next release).

For example, anyone coming to the issue tracker searching for this problem should be able to assume they only need to look at issues that are still open to determine if any apply to their situation.

If an issue is labelled "question", it gets completed by the OPs question being answered. If it is anything else, it gets completed by a change being merged into `master`.

**Comment by Gloster10** [comment]
I did open the thread, I confirm all what you say, but please if the SW-SW integration does fail, would you say the respective download of it  is not possible ? 
Therefore the issue must be still open, no result must be indicated ?
We have a solution,  given by @w4grfw. And for me, a SW-SW integration it is for me not a must.

**Comment by InvalidUsernameException** [comment]
That doesn't matter, really. The issue tracker tracks the state of the project first and foremost. And in the context of the project, the problem isn't solved until the pull request is merged, at which point the issue gets closed automatically.

But I'll stop commenting further now, since this discussion is way off-topic at this point and doesn't belong into this issue anymore either.
