### ISSUE TITLE
Facebook video exist but Televzr doesn't find it

### ISSUE THREAD

**Issue by cmozbas** [yt-dlp/yt-dlp#11493]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Switzerland

### Provide a description that is worded well enough to be understood

The video I try to download exist in facebook but Televzr can't find it.
https://fb.watch/vMjOKxg0VN/

Same thing happenned with another video as well. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[10/Nov/2024:11:14:41 +0000] [info] [renderer] search Downloader: YtDl
[10/Nov/2024:11:14:44 +0000] [error] [renderer] app:yt-dlp:processSpawner process exited with code 1
[10/Nov/2024:11:14:44 +0000] [error] [renderer] app:yt-dlp:processSpawner run args: [ '--no-check-certificates', '--no-playlist', '-j', '-s', 'https://fb.watch/vMjOKxg0VN/' ]
[10/Nov/2024:11:14:44 +0000] [error] [renderer] app:yt-dlp:processSpawner stdout:

[10/Nov/2024:11:14:44 +0000] [error] [renderer] app:yt-dlp:processSpawner stderr:
ERROR: [facebook] 783931153564840: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[10/Nov/2024:11:14:44 +0000] [info] [renderer] search try FbDownloader
[10/Nov/2024:11:14:45 +0000] [error] [browser] SearchStore fetchSearch error Error: Media is not found
    at lp (file:///C%3A/Users/xxx/AppData/Roaming/Televzr%20Desktop/fresh/televzr-v4/bundles/2.10.7/bg.js:343:329059)
    at t (file:///C%3A/Users/xxx/AppData/Roaming/Televzr%20Desktop/fresh/televzr-v4/bundles/2.10.7/bg.js:343:331560)
    at async wp.getMetadata (file:///C%3A/Users/xxx/AppData/Roaming/Televzr%20Desktop/fresh/televzr-v4/bundles/2.10.7/bg.js:343:331838) {
  code: 'MEDIA_IS_NOT_FOUND'
}
```

**Comment by seproDev** [comment]
yt-dlp is a free and open-source video downloader. It seems like Televzr is a paid downloader that uses yt-dlp in the background. We do not make Televzr and if you wish to receive support here you will need to use yt-dlp directly.

For this video specifically, it seems like it is not available:
![image](https://github.com/user-attachments/assets/099e5a91-ba53-4c69-823a-9ae775176664)
Potentially, it requires authentication, which you could do with yt-dlp by passing cookies.
