### ISSUE TITLE
[pbs] An extractor error has occurred. (caused by KeyError('title'))

### ISSUE THREAD

**Issue by andlabs** [yt-dlp/yt-dlp#11514]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

New York, United States

### Provide a description that is worded well enough to be understood

Example URL: https://www.pbs.org/wgbh/nova/video/decoding-the-universe-cosmos/

This error occurs after the "Downloading portalplayer page" regardless of yt-dlp arguments. Tested on both git master (with Python 3.11.10 in a venv) and 2024.11.04 (with Python 3.12.7), both on macOS 10.12. The debug output below is from git master.

This is anonymous viewing; I do not have credentials to share.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.pbs.org/wgbh/nova/video/decoding-the-universe-cosmos/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.10 (CPython x86_64 64bit) - macOS-10.12.6-x86_64-i386-64bit (OpenSSL 3.4.0 22 Oct 2024)
[debug] exe versions: ffmpeg 4.4.5 (fdk,setts), ffprobe 4.4.5, rtmpdump 2.4
[debug] Optional libraries: sqlite3-3.47.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[debug] Using fake IP 6.163.93.244 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[pbs] Extracting URL: https://www.pbs.org/wgbh/nova/video/decoding-the-universe-cosmos/
[pbs] decoding-the-universe-cosmos: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: An extractor error has occurred. (caused by KeyError('title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/private/tmp/xytdlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/xytdlp/lib/python3.11/site-packages/yt_dlp/extractor/pbs.py", line 689, in _real_extract
    'title': info['title'],
             ~~~~^^^^^^^^^
KeyError: 'title'
```

**Comment by bashonly** [comment]
The extractor is broken, but also the URL you are passing is for a whole miniseries rather than a single episode of the miniseries. If you click into the "episodes" tab of the webpage, you can get the individual episode URLs:

https://www.pbs.org/wgbh/nova/video/decoding-the-universe-cosmos/
https://www.pbs.org/wgbh/nova/video/decoding-the-universe-quantum/

And those would work with this patch:

```diff
diff --git a/yt_dlp/extractor/pbs.py b/yt_dlp/extractor/pbs.py
index 686796491..4811d72c8 100644
--- a/yt_dlp/extractor/pbs.py
+++ b/yt_dlp/extractor/pbs.py
@@ -491,7 +491,12 @@ def _extract_webpage(self, url):
                     transform_source=strip_jsonp)
                 return getdir['mid'], presumptive_id, upload_date, description
 
-            for iframe in re.findall(r'(?s)<iframe(.+?)></iframe>', webpage):
+            iframes = traverse_obj(self._search_nextjs_data(webpage, display_id, default={}), (
+                'props', 'pageProps', 'video', 'data', 'episodes',
+                lambda _, v: v['slug'] == display_id, 'episode', 'assets',
+                lambda _, v: v['object_type'] == 'full_length', 'player_code', {str}))
+            iframes.extend(re.findall(r'(?s)<iframe(.+?)></iframe>', webpage))
+            for iframe in iframes:
                 url = self._search_regex(
                     r'src=(["\'])(?P<url>.+?partnerplayer.+?)\1', iframe,
                     'player URL', default=None, group='url')
```

**Comment by andlabs** [comment]
Ah cool; I didn't expect that the URL was for the whole miniseries (I was expecting just the "Cosmos" episode).

I tried applying that patch manually but am still getting the same exception (with line numbers adjusted appropriately).

**Comment by andlabs** [comment]
That worked; thanks!

**Comment by ddemarco5** [comment]
I've got a little something to fix this.
I've by no means done any sort of regression on this, an with just a little bit of testing this doesn't work with the `--cookies` arg for pbs passport videos, which used to work iirc (I could be wrong about this)

```diff
diff --git a/yt_dlp/extractor/pbs.py b/yt_dlp/extractor/pbs.py
index 686796491..51213d66c 100644
--- a/yt_dlp/extractor/pbs.py
+++ b/yt_dlp/extractor/pbs.py
@@ -521,7 +521,10 @@ def _extract_webpage(self, url):
                     video_info.get('id') or video_info['contentID'])
         else:
             video_id = mobj.group('id')
-            display_id = video_id
+            if video_id:
+                display_id = video_id
+            else:
+                video_id = display_id

         return video_id, display_id, None, description
```
The else case here assumes video_id is guaranteed to not be `None`, which no longer seems to be true.
Assuming this is due to website changes, but can't be positive, as this is my first time looking at this.

Since the portalplayer website can take either the `display_id` or `video_id` as an argument (example below)
https://player.pbs.org/portalplayer/the-dinosaurs-that-evolution-forgot-ddwc9d/
https://player.pbs.org/portalplayer/3096079193/

I just dropped the `display_id` into the `video_id` in this particular case because it makes the
```python
for page in ('widget/partnerplayer', 'portalplayer'):
```
loop in `_real_extract` play nice again.

A maintainer should definitely give this a once-over and put it into a fix that addresses the larger pbs site changes that no doubt caused this issue.
But for now this small fix has gotten me up and running again, so I figured I'd leave it here for others in the meantime.

**Comment by bashonly** [comment]
We should probably apply both patches, and for the 2nd patch add a check to ensure the display_id is actually the numeric video_id

**Comment by huntergoatley** [comment]
FWIW, I'm still seeing the same error "caused by KeyError('title'))". I tried the patch above, but didn't see how it would address this problem, and, of course, it doesn't.

**Comment by bashonly** [comment]
> I tried the patch above, but didn't see how it would address this problem, and, of course, it doesn't.

The problem is that this same error can occur for many different reasons. The title KeyError is just a symptom of the actual video page not being extracted. Of course we can make `title` extraction non-fatal in a proper PR, but it's irrelevant while we are debugging the video ID extraction.

The link you provided indeed is not fixed by either of the above patches. It looks like it's because that page is using the new major version of NextJS where the hydration "JSON" is actually a bunch of `push` calls in separate script tags, for which our `_search_nextjs_data` method is ineffective.

**Comment by huntergoatley** [comment]
Thanks! I did get the new design when I visited pbs.org this morning (new since the last time I accessed it---I even got a popup window showing me the changes).

Is that something that can be fixed, given time? Thanks!

**Comment by bashonly** [comment]
> Is that something that can be fixed, given time? 

Yes, but the entire PBS extractor will need to be re-assessed in light of the PBS site redesign, and we may want/need to devise a general solution for the new version of NextJS data. It could take a while

**Comment by huntergoatley** [comment]
Thanks! And thanks for yt-dlp. I've found it most useful for a long time now.

**Comment by bashonly** [comment]
Note for devs: 6b43a8d84b881d769b480ba6e20ec691e9d1b92d has a primitive attempt at extracting the new NextJS data

https://github.com/yt-dlp/yt-dlp/blob/6b43a8d84b881d769b480ba6e20ec691e9d1b92d/yt_dlp/extractor/goplay.py#L79-L82

https://github.com/yt-dlp/yt-dlp/blob/6b43a8d84b881d769b480ba6e20ec691e9d1b92d/yt_dlp/extractor/goplay.py#L87-L89

**Comment by da907igy** [comment]
@rando2024 

Huge Thanks!  Your this method worked perfect for me.

` If I want the higher quality video, knowing that there are often multiple audio tracks and English often isn't the default (so I try to get all of the audio tracks), I run a command like this that uses the first URL:

yt-dlp.exe -f "bv*+mergeall[vcodec=none]" --audio-multistreams --merge-output-format "mp4/mkv" -o 1080p_Leonardo_da_Vinci_Part_1.mkv --hls-prefer-ffmpeg "https://urs.pbs.org/redirect/c8b63c97d228496a8dd70e7760934c29/"`


I am working on scripting it it.   Hoping yt-dlp folks will have a re-rewrite in place early in 2025.  

BTW long time user and lurker this is my first post and **I'd like to extend my genuine thanks and appreciation for all efforts + time from everyone involved with this project.**

**Comment by DTrombett** [comment]
Just a FYI, you should use `-o "1080p_Leonardo_da_Vinci_Part_1.%(ext)s"` so that yt-dlp will choose automatically between MP4 and mkv extension

**Comment by huntergoatley** [comment]
@rando2024 

Thanks! I hadn't had time to try looking at the source to find the URLs. Re: the audio tracks, you can also use --list-formats to see what formats are available, and then you can choose which streams to download.

`$ yt-dlp --list-formats "https://urs.pbs.org/redirect/a583a84bec874254b47fc7079972b27b/"
[generic] Extracting URL: https://urs.pbs.org/redirect/a583a84bec874254b47fc7079972b27b/
[generic] a583a84bec874254b47fc7079972b27b: Downloading webpage
[redirect] Following redirect to https://ga.pbs-video.pbs.org/videos/leonardo-da-vinci/24fa7684-f042-4aa5-a111-eb0c4990b281/2000452708/hd-16x9-mezzanine-1080p/ldvi0102-AABR-AVC_981.m3u8
[generic] Extracting URL: https://ga.pbs-video.pbs.org/videos/leonardo-da-vinci/24fa7684-f042-4aa5-a111-eb0c4990b281/200045...02-AABR-AVC_981.m3u8
[generic] ldvi0102-AABR-AVC_981: Downloading webpage
[generic] ldvi0102-AABR-AVC_981: Downloading m3u8 information
[generic] ldvi0102-AABR-AVC_981: Checking m3u8 live status
[info] ldvi0102-AABR-AVC_981: Downloading subtitles: en
[info] Available formats for ldvi0102-AABR-AVC_981:
ID                               EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
multiple_audio_tracks-English    mp4 audio only     │                  m3u8  │ audio only        unknown    [eng] English
multiple_audio_tracks-English_AD mp4 audio only     │                  m3u8  │ audio only        unknown    [eng] English AD
multiple_audio_tracks-Spanish    mp4 audio only     │                  m3u8  │ audio only        unknown    [spa] Spanish
389                              mp4 640x360     30 │ ~296.58MiB  390k m3u8  │ avc1.64001e  390k video only
557                              mp4 768x432     30 │ ~424.38MiB  557k m3u8  │ avc1.64001e  557k video only
1386                             mp4 1280x720    30 │ ~  1.03GiB 1386k m3u8  │ avc1.64001f 1386k video only
2247                             mp4 1600x900    30 │ ~  1.67GiB 2247k m3u8  │ avc1.640028 2247k video only
4136                             mp4 1920x1080   30 │ ~  3.07GiB 4136k m3u8  │ avc1.640028 4136k video only
$ yt-dlp -f 4136+multiple_audio_tracks-English ....
`

Supplying whatever other options you want. I used these for part 2.

`yt-dlp -f 4136+multiple_audio_tracks-English --embed-subs --merge-output-format mkv --remux-video mkv -o "Leo - Part 2.mkv" "https://urs.pbs.org/redirect/a583a84bec874254b47fc7079972b27b/"
`

**Comment by wymakeitph** [comment]
Sorry but can anyone teach me how to apply the patch on a Mac? I tried copy pasting from above to my cmd but it’s not working

**Comment by someziggyman** [comment]
implemented both patches and it seems to work for direct pbs domain links like https://www.pbs.org/video/el-gato-feo-yd5esw/.    at the same time testing this one (https://video.rmpbs.org/video/native-horse-7kmmxx/) failed, but due to unsupported domain error (which is strange cause I see video.rmpbs.org mentioned in pbs.py). That's probably another issue that I'll create a report now.

**Comment by bashonly** [comment]
@someziggyman no need to open a new issue. We can use this one as a blanket issue for the site redesign; the new Next.js version has already been discussed in here, etc. Don't want to splitting info/discussion into multiple threads

**Comment by dirkf** [comment]
There are two problems with the URLs above:

* https://video.rmpbs.org/video/native-horse-7kmmxx/ doesn't match because the extractor expects a numeric ID after `video/`: the first two sub-patterns in the `_VALID_URL` need to be merged;
* https://www.pbs.org/video/el-gato-feo-yd5esw/ doesn't find the numeric video ID which is in strings like `https://player.pbs.org/viralplayer/nnnnnnnnnn` in its webpage, but not found by the existing `MEDIA_ID_REGEXES`.

In both cases the player URL is found in both the `#fixed-iframe-text` and the `#responsive-iframe-text` `<input>` elements as the `src` of the `<iframe>` element encoded as the `value` of each `<input>`. In the el-gato-feo case, there is also a `TVEpisode` ld+json block whose `.video` is a `VideoObject` containing `"contentUrl": "https://player.pbs.org/viralplayer/3092772965"`.

A search of each original page for `r'https?://player\.pbs\.org/[\w-]+player/\d+/'` would find the media link with no more complex page parsing.

Maybe PBS members other than RMPBS have yet further structures, or there are pages with false positive player links, but for these URLs:
```diff
     _VALID_URL = r'''(?x)https?://
         (?:
-           # Direct video URL
-           (?:{})/(?:(?:vir|port)alplayer|video)/(?P<id>[0-9]+)(?:[?/]|$) |
-           # Article with embedded player (or direct video)
-           (?:www\.)?pbs\.org/(?:[^/]+/){{1,5}}(?P<presumptive_id>[^/]+?)(?:\.html)?/?(?:$|[?\#]) |
+           # Direct video URL, or article with embedded player
+           (?:{})/(?:
+              (?:(?:vir|port)alplayer|video)/(?P<id>[0-9]+)(?:[?/]|$) |
+              (?:[^/]+/){1,5}(?P<presumptive_id>[^/]+?)(?:\.html)?/?(?:$|[?\#])
+           ) |
            # Player
            (?:video|player)\.pbs\.org/(?:widget/)?partnerplayer/(?P<player_id>[^/]+)
         )
     '''.format('|'.join(next(zip(*_STATIONS))))
```
and
```diff
             MEDIA_ID_REGEXES = [
+                r'\bhttps?://player\.pbs\.org/[\w-]+player/(\d+)',      # move to end to avoid false +ves?

                 r"div\s*:\s*'videoembed'\s*,\s*mediaid\s*:\s*'(\d+)'",  # frontline video embed
                 r'class="coveplayerid">([^<]+)<',                       # coveplayer
                 r'<section[^>]+data-coveid="(\d+)"',                    # coveplayer from http://www.pbs.org/wgbh/frontline/film/real-csi/
                 r'<input type="hidden" id="pbs_video_id_[0-9]+" value="([0-9]+)"/>',  # jwplayer
                 r"(?s)window\.PBS\.playerConfig\s*=\s*{.*?id\s*:\s*'([0-9]+)',",
                 r'<div[^>]+\bdata-cove-id=["\'](\d+)"',  # http://www.pbs.org/wgbh/roadshow/watch/episode/2105-indianapolis-hour-2/
                 r'<iframe[^>]+\bsrc=["\'](?:https?:)?//video\.pbs\.org/widget/partnerplayer/(\d+)',  # https://www.pbs.org/wgbh/masterpiece/episodes/victoria-s2-e1/
             ]
```

**Comment by huntergoatley** [comment]
Thanks, dirkf!

I tried to apply your patches, but I'm getting this:

`  File "/home/hunter/software/yt-dlp/yt_dlp/extractor/pbs.py", line 196, in PBSIE
    '''.format('|'.join(next(zip(*_STATIONS))))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '1,5'
`

And I can't see why. I've checked it several times---my replacement lines are identical to what you've posted. Ideas?

Thanks!

**Comment by dirkf** [comment]
Oops, the `{1,5}` needs to be escaped with double braces as in the last deleted line.

**Comment by huntergoatley** [comment]
Thanks. I looked at it several times and still missed that. :)

**Comment by dirkf** [comment]
The extractor can fail because both player pages said `We're sorry, but this video is not available.`. Does this always indicate expired content, or may it be a symptom of geo-block or login required?

Examples where this happens with a WIP extractor version:
* WGBH Nova Decoding the Universe - Cosmos as above and also its generic page, /https://www.pbs.org/video/decoding-the-universe-cosmos-pqnkre/
* Test 3, http://www.pbs.org/wnet/gperf/dudamel-conducts-verdi-requiem-hollywood-bowl-full-episode/3374/ (quite impressive if it is still up, 10 years later)
* also from above, https://www.pbs.org/video/leonardo-da-vinci-part-one-the-disciple-of-experience/

Results from in-region and/or subscribed users would be useful.

**Comment by nlurker** [comment]
The 2 patches above by dirkf do fix it for all the most common shows I have tried.  Could these be merged in now to get it working until a more comprehensive update is ready later?

**Comment by bennor675** [comment]
The PBS extractor error is still present in the latest yt-dlp to stable@2024.12.23 on Windows 11. Will have to see about trying the  2 patches by dirkf above.

```
yt-dlp -F https://www.pbs.org/video/lost-tombs-of-notre-dame-ayjw0k/
[pbs] Downloading JSON metadata
[pbs] Extracting URL: https://www.pbs.org/video/lost-tombs-of-notre-dame-ayjw0k/
[pbs] lost-tombs-of-notre-dame-ayjw0k: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: An extractor error has occurred. (caused by KeyError('title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by someziggyman** [comment]
While this one is still open and offered fixes seem to indeed over most of the cases (at least for me). Can the regex be adjusted to support PBSCoCal URLs as well? like here: https://github.com/yt-dlp/yt-dlp/pull/9740/files it's a slight adjustment of regex and new test link added. But it's irrelevant due to the latest offered patches. Regexes are a nightmare in terms of syntax to me. Right now pbssocal.org are for some reason forwarded to general extractor even though PBS.py seems to support it. Test links, just in case: https://www.pbssocal.org/shows/annual-l-county-holiday-celebration/special/65th-annual-la-county-holiday-celebration-yi1mmd    and    https://www.pbssocal.org/shows/newshour/clip/capehart-johnson-1715984001    do not seem to be geo restricted at least in EU and US.

**Comment by dirkf** [comment]
The existing pattern handles `video.pbssocal.org/xxxx/...` for certain words `xxxx` as well as `www.pbs.org/whatever...`. PR #9740 adds support for `www.pbssocal.org/whatever...` as a special case, but it might be better to generalise that for other stations:

```diff
...
         (r'vids\.kvie\.org', 'KVIE Public Television (KVIE)'),  # http://www.kvie.org
-        (r'video\.pbssocal\.org', 'PBS SoCal/KOCE (KOCE)'),  # http://www.pbssocal.org/
+        (r'(?:video\.|www\.)pbssocal\.org', 'PBS SoCal/KOCE (KOCE)'),  # http://www.pbssocal.org/
         (r'video\.valleypbs\.org', 'ValleyPBS (KVPT)'),  # http://www.valleypbs.org/
...
     _VALID_URL = r'''(?x)https?://
         (?:
-           # Direct video URL
-           (?:%s)/(?:(?:vir|port)alplayer|video)/(?P<id>[0-9]+)(?:[?/]|$) |
-           # Article with embedded player (or direct video)
-           (?:www\.)?pbs\.org/(?:[^/]+/){1,5}(?P<presumptive_id>[^/]+?)(?:\.html)?/?(?:$|[?\#]) |
            # Player
-           (?:video|player)\.pbs\.org/(?:widget/)?partnerplayer/(?P<player_id>[^/]+)/
+           (?:video|player)\.pbs\.org/(?:widget/)?partnerplayer/(?P<player_id>[^/]+) |
+           # Direct video URL, or article with embedded player
+           (?:%s)/(?:
+              (?:(?:vir|port)alplayer|video)/(?P<id>[0-9]+)(?:[?/]|$) |
+              (?:[^/]+/){1,5}(?P<presumptive_id>[^/]+?)(?:\.html)?/?(?:$|[?\#])
+           )
         )
-    ''' % '|'.join(list(zip(*_STATIONS))[0])
+    ''' % '|'.join(next(zip(*_STATIONS)))
```

**Comment by bennor675** [comment]
A workaround posted to the #11928 [by user october262](https://github.com/yt-dlp/yt-dlp/issues/11928#issuecomment-2564223844)
> try again with yt-dlp --force-generic-extractor "https://www.pbs.org/video/take-a-chance-wdZQCx/" the video will now download.

Tried it on one PBS Nova video and it worked.

**Comment by ryrrah** [comment]
A couple of days ago, using "--force-generic-extractor" worked for me. But today, I get the following message:
ERROR: Unsupported URL: https://www.pbs.org/video/episode-3-bbtymu

Without the generic extractor, the error message that started this thread appears. 

I'm using nightly build: 2024.12.26.232815

**Comment by bennor675** [comment]
Same. The _yt-dlp --force-generic-extractor_ no longer works on PBS. The following worked last week, today no longer works. Two different URL's tried listed below:

`yt-dlp>yt-dlp --force-generic-extractor -vU https://www.pbs.org/video/lost-tombs-of-notre-dame-ayjw0k/
[debug] Command-line config: ['--force-generic-extractor', '-vU', 'https://www.pbs.org/video/lost-tombs-of-notre-dame-ayjw0k/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0.2-full_build-www.gyan.dev (setts), ffprobe 7.0.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.pbs.org/video/lost-tombs-of-notre-dame-ayjw0k/
[generic] lost-tombs-of-notre-dame-ayjw0k: Downloading webpage
WARNING: [generic] Forcing generic information extractor
[generic] lost-tombs-of-notre-dame-ayjw0k: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.pbs.org/video/lost-tombs-of-notre-dame-ayjw0k/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1634, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1769, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.pbs.org/video/lost-tombs-of-notre-dame-ayjw0k/`

```
yt-dlp>yt-dlp --force-generic-extractor -vU https://www.pbs.org/video/american-experience-the-presidents-jimmy-carter/
[debug] Command-line config: ['--force-generic-extractor', '-vU', 'https://www.pbs.org/video/american-experience-the-presidents-jimmy-carter/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0.2-full_build-www.gyan.dev (setts), ffprobe 7.0.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.pbs.org/video/american-experience-the-presidents-jimmy-carter/
[generic] american-experience-the-presidents-jimmy-carter: Downloading webpage
WARNING: [generic] Forcing generic information extractor
[generic] american-experience-the-presidents-jimmy-carter: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.pbs.org/video/american-experience-the-presidents-jimmy-carter/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1634, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1769, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.pbs.org/video/american-experience-the-presidents-jimmy-carter/
```

**Comment by sanjeevdwivedi** [comment]
Dirkf's patch works. Thanks!!

**Comment by afterconnery** [comment]
Using --force-generic-extractor and not using it provides an unsupported URL error. Running the latest yt-dlp version as well (2025.1.12)

**Comment by ryrrah** [comment]
Same here

> Using --force-generic-extractor and not using it provides an unsupported URL error. Running the latest yt-dlp version as well (2025.1.12)

Same here.

**Comment by bashonly** [comment]
Can reopen if the merged fix is insufficient, since I think there was at least one report of that upthread

**Comment by PacoH** [comment]
This seems to have been fixed. I can now download NOVA episodes again.

**Comment by bennor675** [comment]
> This seems to have been fixed. I can now download NOVA episodes again.

Yes it has been fixed. It was part of the [2024.01.26 release](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.26) that was released on 1/26/2025 (see the release notes for fixes).

**Comment by huntergoatley** [comment]
Thanks for getting the fix implemented!

**Comment by PacoH** [comment]
Thanks. That would explain it. I did use that version.

**Comment by dirkf** [comment]
Is extraction working for the video from https://github.com/yt-dlp/yt-dlp/issues/11514#issuecomment-2488965467 (Masterpiece Theater, Little Women E3, https://www.pbs.org/video/episode-3-r7iod3/) with the current _yt-dlp_ extractor (and so, without processing the new Next.js scripts)?

As with test video https://www.pbs.org/wgbh/masterpiece/episodes/victoria-s2-e1/ (which does not have the new Next.js scripts), this video gives the generic error from this issue from (eg) UK without login or VPN.

Or if that episode is no longer playing for in-region/subscribing users, a similar current episode?

If the new Next.js does have to be processed, a freely available example would be good for testing.

**Comment by bashonly** [comment]
> Is extraction working for the video from https://github.com/yt-dlp/yt-dlp/issues/11514#issuecomment-2488965467 (Masterpiece Theater, Little Women E3, https://www.pbs.org/video/episode-3-r7iod3/) with the current _yt-dlp_ extractor (and so, without processing the new Next.js scripts)?

works for me

**Comment by dirkf** [comment]
So it looks like these test videos are dead from the UK in various ways:
| URL | status | skipped |
|-----|--------|---------|
| http://www.pbs.org/tpt/constitution-usa-peter-sagal/watch/a-more-perfect-union/ | not found. | yes |
| http://www.pbs.org/wnet/gperf/dudamel-conducts-verdi-requiem-hollywood-bowl-full-episode/3374/ | not available | no |
| http://www.pbs.org/wgbh/nova/earth/killer-typhoon.html | no longer available | no |
| http://www.pbs.org/wgbh/americanexperience/films/death/player/ | 404 | no |
| http://www.pbs.org/video/2365245528/ | 404 extinct | no |
| http://www.pbs.org/food/features/a-chefs-life-season-3-episode-5-prickly-business/ | could not be found | no |
| http://www.pbs.org/video/2365641075/ | 404 ... could not be found | no |
| https://www.pbs.org/video/pbs-newshour-full-episode-july-31-2017-1501539057/ | Expired 08/30/2017 | no |
| http://www.pbs.org/wgbh/roadshow/watch/episode/2105-indianapolis-hour-2/ | not available | no |
| https://www.pbs.org/wgbh/masterpiece/episodes/victoria-s2-e1/ | not available | no |

From [above](https://github.com/yt-dlp/yt-dlp/issues/11514#issuecomment-2858943557), videos with status `not available` should be interpreted as "You may need to login or use a VPN to access this content". You can add `_GEO_BYPASS = False` without affecting any test result. So, either geo headers are not being sent in some request where they should be (I couldn't find anywhere that had an effect), or XFF is now not effective for PBS.

http://www.pbs.org/wgbh/americanexperience/films/death/player/ is still available, unrestricted, as below:
```console
yt-dlp -vF 'https://watch.montanapbs.org/video/american-experience-death-and-civil-war-chapter-1/' --no-geo-bypass
[debug] Command-line config: ['-vF', 'https://watch.montanapbs.org/video/american-experience-death-and-civil-war-chapter-1/', '--no-geo-bypass']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.03.31 from yt-dlp/yt-dlp [5e457af57] (zip)
[debug] Python 3.11.2 (CPython i686 32bit) - Linux-6.1.0-34-686-pae-i686-with-glibc2.36 (OpenSSL 3.0.15 3 Sep 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2022.09.24, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12 (unsupported)
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Plugin directories: none
[debug] Loaded 1850 extractors
[pbs] Downloading JSON metadata
[pbs] Extracting URL: https://watch.montanapbs.org/video/american-experience-death-and-civil-war-chapter-1/
[pbs] american-experience-death-and-civil-war-chapter-1: Downloading webpage
[pbs] american-experience-death-and-civil-war-chapter-1: Downloading widget/partnerplayer page
[pbs] american-experience-death-and-civil-war-chapter-1: Downloading portalplayer page
[pbs] american-experience-death-and-civil-war-chapter-1: Downloading 0 video url info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 2276541483:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 unknown    │ https │ unknown unknown
$
```
The relatively ancient show at http://www.pbs.org/food/features/a-chefs-life-season-3-episode-5-prickly-business/ is still available elsewhere under http://www.pbs.org/food/ but now needs a member login.

**Comment by evan6seven** [comment]
I just got this error on this video:

https://www.pbs.org/video/norah-jones-hurray-for-the-riff-raff-lq9ojp/

Version 2025.11.12
