### ISSUE TITLE
AttributeError: module 'ssl' has no attribute 'enum_certificates'

### ISSUE THREAD

**Issue by 2ShedsJackson** [yt-dlp/yt-dlp#1151]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['-v', 'http://www.youtube.com/watch?v=BaW_jenozKc']
Traceback (most recent call last):
  File "C:/bin/yt-dlp-master-new/yt_dlp/__main__.py", line 19, in <module>
    yt_dlp.main()
  File "C:/bin/yt-dlp-master-new/yt_dlp/__init__.py", line 779, in main
    _real_main(argv)
  File "C:/bin/yt-dlp-master-new/yt_dlp/__init__.py", line 740, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "C:/bin/yt-dlp-master-new/yt_dlp/YoutubeDL.py", line 579, in __init__
    self._setup_opener()
  File "C:/bin/yt-dlp-master-new/yt_dlp/YoutubeDL.py", line 3302, in _setup_opener
    https_handler = make_HTTPS_handler(self.params, debuglevel=debuglevel)
  File "C:/bin/yt-dlp-master-new/yt_dlp/utils.py", line 2381, in make_HTTPS_handler
    _ssl_load_windows_store_certs(context, storename)
  File "C:/bin/yt-dlp-master-new/yt_dlp/utils.py", line 2358, in _ssl_load_windows_store_certs
    certs = [cert for cert, encoding, trust in ssl.enum_certificates(storename)
AttributeError: module 'ssl' has no attribute 'enum_certificates'


```

## Description

Running the python (v 3.9.7) code of yt-dlp (v 2021.09.25) in Windows MSYS2 MINGW64 results in the error. The Windows compiled version works fine. Of course, _ssl_load_windows_store_certs in utils.py wasn't in yt-dlp version 2021.09.02 so the older version didn't produce the error.

**Comment by pukkandan** [comment]
It should exist 😕 https://github.com/python/cpython/blob/d5650a1738fe34f6e1db4af5f4c4edb7cae90a36/Lib/ssl.py#L168-L169

Can you check what is the value of `sys.platform` inside mingw?

**Comment by xtkoba** [comment]
This is a natural consequence because MinGW does not define `_MSC_VER`:

https://github.com/python/cpython/blob/main/Modules/_ssl.c#L5304
https://github.com/python/cpython/blob/main/Modules/clinic/_ssl.c.h#L1250

There is already a patch for `Lib/ssl.py` in the wild:

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python/0052-mingw-fix-ssl-dont-use-enum_certificates.patch

**Comment by pukkandan** [comment]
I don't understand. `enum_certificates` would have been called by older versions of yt-dlp too when it uses `ssl.create_default_context`. So why does that not give error?

**Comment by xtkoba** [comment]
I guess not. It should have never been called with patched `Lib/ssl.py`.

BTW, can we "steal" the fix from the patch mentioned above?

**Comment by pukkandan** [comment]
oh, you mean that mingw officially uses that patch? In that case, it would make sense

**Comment by pukkandan** [comment]
what does `sys.version` give with mingw?
