### ISSUE TITLE
Wrong default best audio track selected on gem.cbc.ca

### ISSUE THREAD

**Issue by PacoH** [yt-dlp/yt-dlp#11547]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada and possibly USA

### Provide a description that is worded well enough to be understood

This is the first time I have attempted to download videos from gem.cbc.ca.

I had the same problem on these two shows:

[Heartland | Season 18 | CBC Gem](https://gem.cbc.ca/heartland/s18)
8 items

`yt-dlp --version
2024.11.04`

```
u=https://gem.cbc.ca/heartland/s18
yt-dlp -u $user -p $pw -F "$u"

hls-audio_0-English__Descriptive_ mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English (Descriptive)
hls-audio_1-English__Descriptive_ mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English (Descriptive)
hls-audio_2-English__Descriptive_ mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English (Descriptive)
hls-audio_0-English               mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English
hls-audio_1-English               mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English
hls-audio_2-English               mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English
hls-321                           mp4 416x234     10 │ ~101.46MiB  321k m3u8  │ avc1.42C00C  321k video only
hls-431                           mp4 416x234     15 │ ~136.22MiB  431k m3u8  │ avc1.42C00C  431k video only
hls-651                           mp4 416x234     30 │ ~205.72MiB  651k m3u8  │ avc1.42C00D  651k video only
hls-871                           mp4 640x360     30 │ ~275.22MiB  871k m3u8  │ avc1.42C01E  871k video only
hls-1311                          mp4 640x360     30 │ ~414.22MiB 1311k m3u8  │ avc1.42C01E 1311k video only
hls-2191                          mp4 960x540     30 │ ~692.20MiB 2191k m3u8  │ avc1.4D401F 2191k video only
hls-2961                          mp4 1280x720    30 │ ~935.43MiB 2961k m3u8  │ avc1.4D401F 2961k video only
hls-3951                          mp4 1280x720    30 │ ~  1.22GiB 3951k m3u8  │ avc1.4D401F 3951k video only
hls-6811                          mp4 1920x1080   30 │ ~  2.10GiB 6811k m3u8  │ avc1.640028 6811k video only
```

[Downton Abbey | Season 1 | CBC Gem](https://gem.cbc.ca/downton-abbey/s01)
8 items

```
u=https://gem.cbc.ca/downton-abbey/s01
yt-dlp -u $user -p $pw -F "$u"

hls-audio_0-English__Descriptive_ mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English (Descriptive)
hls-audio_1-English__Descriptive_ mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English (Descriptive)
hls-audio_2-English__Descriptive_ mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English (Descriptive)
hls-audio_0-English               mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English
hls-audio_1-English               mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English
hls-audio_2-English               mp4 audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English
hls-321-0                         mp4 416x234     10 │ ~150.35MiB  321k m3u8  │ avc1.42C00C  321k video only
hls-321-1                         mp4 416x234     10 │ ~150.35MiB  321k m3u8  │ avc1.42C00C  321k video only
hls-431-0                         mp4 416x234     15 │ ~201.86MiB  431k m3u8  │ avc1.42C00C  431k video only
hls-431-1                         mp4 416x234     15 │ ~201.87MiB  431k m3u8  │ avc1.42C00C  431k video only
hls-651                           mp4 416x234     30 │ ~304.87MiB  651k m3u8  │ avc1.42C00D  651k video only
hls-871                           mp4 640x360     30 │ ~407.86MiB  871k m3u8  │ avc1.42C01E  871k video only
hls-1311                          mp4 640x360     30 │ ~613.87MiB 1311k m3u8  │ avc1.42C01E 1311k video only
hls-2191                          mp4 960x540     30 │ ~  1.00GiB 2191k m3u8  │ avc1.4D401F 2191k video only
hls-2961                          mp4 1280x720    30 │ ~  1.35GiB 2961k m3u8  │ avc1.4D401F 2961k video only
hls-3951                          mp4 1280x720    30 │ ~  1.81GiB 3952k m3u8  │ avc1.4D401F 3952k video only
hls-6811                          mp4 1920x1080   30 │ ~  3.11GiB 6812k m3u8  │ avc1.640028 6812k video only
```

Attempted to download playlist item 3:

```
u=https://gem.cbc.ca/downton-abbey/s01
yt-dlp -vU --embed-subs --no-warnings -u $user -p $pw --concurrent-fragments 20 --playlist-items 3 -o "%(playlist_index-1)02d %(title)s - %(id)s - %(resolution)s %(format_id)s.%(ext)s" $u`

I hadn't run the command with the -vU flag before but the debug output doesn't help me in any case. As you can see, the default bestaudio format chosen is `hls-audio_2-English`. Herin lies the problem. Note that both the video and the audio files downloaded without a problem and the intermediary file was created successfully.

Video file:
Downton Abbey/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.fhls-6812.mp4
49 min 41 s

Audio file:
Downton Abbey/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.temp.mp4
35 min 35 s

Intermediary file:
Downton Abbey/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.fhls-audio_2-English.mp4
49 min 46 s

So the problem must be "Error muxing a packet", due to a mismatch in the duration of each file.

When I specified the format `-f hls-6811+hls-audio_1-English`, the second best audio track, the files merged successfully because the duration was the same as the video file.

I don't know why the best audio file would be a shorter duration like that. 

Is there a way to automatically test for this situation before selecting the file to download or would it be difficult to implement?


### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--embed-subs', '--no-warnings', '-u', 'PRIVATE', '-p', 'PRIVATE', '--concurrent-fragments', '20', '--playlist-items', '3', '-o', '/Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/%(playlist_index-1)02d %(title)s - %(id)s - %(resolution)s %(format_id)s.%(ext)s', 'https://gem.cbc.ca/downton-abbey/s01']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.12.232900 from yt-dlp/yt-dlp-nightly-builds [f2a4983df] (darwin_exe)
[debug] Python 3.12.7 (CPython x86_64 64bit) - macOS-13.6.5-x86_64-i386-64bit (OpenSSL 3.0.15 3 Sep 2024)
[debug] exe versions: ffmpeg 7.1-tessus (setts), ffprobe 7.1-tessus, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.12.232900 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.12.232900 from yt-dlp/yt-dlp-nightly-builds)
[gem.cbc.ca:playlist] Extracting URL: https://gem.cbc.ca/downton-abbey/s01
[gem.cbc.ca:playlist] downton-abbey/s01: Downloading JSON metadata
[download] Downloading playlist: Season 1
[gem.cbc.ca:playlist] Playlist Season 1: Downloading 1 items of 8
[download] Downloading item 1 of 1
[debug] Using fake IP 99.229.56.236 (CA) as X-Forwarded-For
[debug] Loading cbcgem.claims_token from cache
[gem.cbc.ca] Extracting URL: https://gem.cbc.ca/media/downton-abbey/s01e02
[gem.cbc.ca] downton-abbey/s01e02: Downloading JSON metadata
[gem.cbc.ca] downton-abbey/s01e02: Downloading JSON metadata
[gem.cbc.ca] downton-abbey/s01e02: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] downton-abbey/s01e02: Downloading 1 format(s): hls-6812+hls-audio_2-English
[info] There are no subtitles for the requested languages
[debug] Invoking hlsnative downloader on "https://cbcrcott-aws-gem.akamaized.net/hdntl=exp=1731718281~acl=%2f*~data=hdntl~hmac=dd35076ac014891b2dc485a3a730f3e8570274413896b24b2c2a2ecc0038a8b1/out/v1/bbff1b20e0c04d71b9dca94fcf62e9d1/026bf27581e640c4b4fb78ae5aaa5021/4992c413374a4be4af23a7b5453f28df/8bfaea6bd68d41f997b3e25192a3b4a4/6baf985d549245c48f39e42930e10a5e/index-aes_1.m3u8?aka_me_session_id=AAAAAAAAAACJ7DdnAAAAAPjEDEC4ICuh1eVFmZezPWo6n0FVJkSkC0lV1MK5TdIHoIz3hKJlKDDiIld7JePYnKl4c58cKqq3&aka_media_format_type=hls&pckgrp=bf5b9c2800b7e86d48330ceb5add54a4"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 993
[download] Destination: /Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.fhls-6812.mp4
[download] 100% of    2.15GiB in 00:02:10 at 16.85MiB/s
[debug] Invoking hlsnative downloader on "https://cbcrcott-aws-gem.akamaized.net/hdntl=exp=1731718281~acl=%2f*~data=hdntl~hmac=dd35076ac014891b2dc485a3a730f3e8570274413896b24b2c2a2ecc0038a8b1/out/v1/bbff1b20e0c04d71b9dca94fcf62e9d1/026bf27581e640c4b4fb78ae5aaa5021/4992c413374a4be4af23a7b5453f28df/8bfaea6bd68d41f997b3e25192a3b4a4/6baf985d549245c48f39e42930e10a5e/index-aes_16_0.m3u8?aka_me_session_id=AAAAAAAAAACJ7DdnAAAAAPjEDEC4ICuh1eVFmZezPWo6n0FVJkSkC0lV1MK5TdIHoIz3hKJlKDDiIld7JePYnKl4c58cKqq3&aka_media_format_type=hls&pckgrp=bf5b9c2800b7e86d48330ceb5add54a4"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 993
[download] Destination: /Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.fhls-audio_2-English.mp4
[download] 100% of   45.57MiB in 00:00:14 at 3.20MiB/s
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.fhls-audio_2-English.mp4'
[Merger] Merging formats into "/Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.fhls-6812.mp4' -i 'file:/Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.fhls-audio_2-English.mp4' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:/Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.temp.mp4'
[debug] ffmpeg version 7.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.3)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libharfbuzz --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mpegts, from 'file:/Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.fhls-6812.mp4':
  Duration: 00:49:41.98, start: 2.095867, bitrate: 6189 kb/s
  Program 1 
  Stream #0:0[0x1e1]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn
[eac3 @ 0x7fab0e904b40] Estimating duration from bitrate, this may be inaccurate
Input #1, eac3, from 'file:/Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.fhls-audio_2-English.mp4':
  Duration: 00:49:46.51, start: 0.000000, bitrate: 128 kb/s
  Stream #1:0: Audio: eac3, 48000 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
[mp4 @ 0x7fab0ea04c80] track 1: codec frame size is not set
Output #0, mp4, to 'file:/Volumes/Storage 11 - Seagate Backup Plus Drive 10/Kodi Downloads 6/TV/Downton Abbey/test/02 Episode 2 - downton-abbey⧸s01e02 - 1920x1080 hls-6812+hls-audio_2-English.temp.mp4':
  Metadata:
    encoder         : Lavf61.7.100
  Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 90k tbn
  Stream #0:1: Audio: eac3 (ec-3 / 0x332D6365), 48000 Hz, stereo, fltp, 128 kb/s
Press [q] to stop, [?] for help
frame= 2584 fps=0.0 q=-1.0 size=   64256KiB time=00:01:26.31 bitrate=6098.1kbits/s speed= 171x    
frame= 5088 fps=5036 q=-1.0 size=  126976KiB time=00:02:49.85 bitrate=6123.9kbits/s speed= 168x    
frame= 6316 fps=4169 q=-1.0 size=  157440KiB time=00:03:30.74 bitrate=6120.0kbits/s speed= 139x    
frame= 7382 fps=3657 q=-1.0 size=  184064KiB time=00:04:06.44 bitrate=6118.4kbits/s speed= 122x    
frame= 8040 fps=3187 q=-1.0 size=  200448KiB time=00:04:28.36 bitrate=6118.7kbits/s speed= 106x    
frame= 9717 fps=3209 q=-1.0 size=  242432KiB time=00:05:24.29 bitrate=6124.1kbits/s speed= 107x    
frame=11073 fps=3135 q=-1.0 size=  276224KiB time=00:06:09.53 bitrate=6123.4kbits/s speed= 105x    
frame=13745 fps=3406 q=-1.0 size=  342784KiB time=00:07:38.72 bitrate=6121.5kbits/s speed= 114x    
frame=14802 fps=3258 q=-1.0 size=  369408KiB time=00:08:13.99 bitrate=6126.0kbits/s speed= 109x    
frame=15498 fps=3071 q=-1.0 size=  386816KiB time=00:08:37.21 bitrate=6126.6kbits/s speed= 103x    
frame=16902 fps=3045 q=-1.0 size=  421632KiB time=00:09:24.03 bitrate=6123.8kbits/s speed= 102x    
frame=18374 fps=3034 q=-1.0 size=  458496KiB time=00:10:13.21 bitrate=6125.1kbits/s speed= 101x    
frame=20299 fps=3090 q=-1.0 size=  506624KiB time=00:11:17.37 bitrate=6127.0kbits/s speed= 103x    
frame=21266 fps=3006 q=-1.0 size=  530688KiB time=00:11:49.57 bitrate=6126.8kbits/s speed= 100x    
frame=23340 fps=3080 q=-1.0 size=  582400KiB time=00:12:58.84 bitrate=6125.8kbits/s speed= 103x    
frame=24902 fps=3078 q=-1.0 size=  621312KiB time=00:13:50.99 bitrate=6124.9kbits/s speed= 103x    
frame=24902 fps=2897 q=-1.0 size=  621312KiB time=00:13:50.99 bitrate=6124.9kbits/s speed=96.7x    
frame=25886 fps=2844 q=-1.0 size=  645888KiB time=00:14:23.82 bitrate=6125.2kbits/s speed=94.9x    
frame=28757 fps=2994 q=-1.0 size=  717568KiB time=00:15:59.62 bitrate=6125.6kbits/s speed=99.9x    
frame=29332 fps=2901 q=-1.0 size=  731904KiB time=00:16:18.77 bitrate=6125.8kbits/s speed=96.8x    
frame=29617 fps=2788 q=-1.0 size=  739072KiB time=00:16:28.28 bitrate=6126.2kbits/s speed=  93x    
frame=31621 fps=2842 q=-1.0 size=  789248KiB time=00:17:35.18 bitrate=6127.4kbits/s speed=94.8x    
frame=33068 fps=2843 q=-1.0 size=  825344KiB time=00:18:23.36 bitrate=6127.8kbits/s speed=94.9x    
frame=33269 fps=2741 q=-1.0 size=  830208KiB time=00:18:30.17 bitrate=6126.1kbits/s speed=91.5x    
frame=34419 fps=2721 q=-1.0 size=  858880KiB time=00:19:08.51 bitrate=6126.1kbits/s speed=90.8x    
frame=36577 fps=2780 q=-1.0 size=  912896KiB time=00:20:20.41 bitrate=6127.8kbits/s speed=92.8x    
frame=38644 fps=2829 q=-1.0 size=  964352KiB time=00:21:29.52 bitrate=6126.3kbits/s speed=94.4x    
frame=39588 fps=2795 q=-1.0 size=  987904KiB time=00:22:01.01 bitrate=6126.3kbits/s speed=93.3x    
frame=40591 fps=2767 q=-1.0 size= 1012992KiB time=00:22:34.48 bitrate=6126.6kbits/s speed=92.3x    
frame=42191 fps=2780 q=-1.0 size= 1052928KiB time=00:23:27.87 bitrate=6126.7kbits/s speed=92.8x    
frame=44326 fps=2827 q=-1.0 size= 1106176KiB time=00:24:39.11 bitrate=6126.5kbits/s speed=94.3x    
frame=46130 fps=2851 q=-1.0 size= 1151232KiB time=00:25:39.30 bitrate=6126.7kbits/s speed=95.1x    
frame=48022 fps=2878 q=-1.0 size= 1198592KiB time=00:26:42.36 bitrate=6127.7kbits/s speed=  96x    
frame=49861 fps=2900 q=-1.0 size= 1244416KiB time=00:27:43.79 bitrate=6127.1kbits/s speed=96.8x    
frame=52116 fps=2944 q=-1.0 size= 1300736KiB time=00:28:59.00 bitrate=6127.4kbits/s speed=98.2x    
frame=53721 fps=2950 q=-1.0 size= 1340672KiB time=00:29:52.59 bitrate=6126.8kbits/s speed=98.4x    
frame=55521 fps=2967 q=-1.0 size= 1385728KiB time=00:30:52.61 bitrate=6127.5kbits/s speed=  99x    
frame=57944 fps=3015 q=-1.0 size= 1446144KiB time=00:32:13.49 bitrate=6127.1kbits/s speed= 101x    
frame=60321 fps=3058 q=-1.0 size= 1505536KiB time=00:33:32.81 bitrate=6127.4kbits/s speed= 102x    
frame=62085 fps=3069 q=-1.0 size= 1549568KiB time=00:34:31.63 bitrate=6127.6kbits/s speed= 102x    
[vost#0:0/copy @ 0x7fab0ea0d780] Error submitting a packet to the muxer: Invalid data found when processing input
[vost#0:0/copy @ 0x7fab0ea0d780] Error submitting a packet to the muxer: Invalid data found when processing input
[out#0/mp4 @ 0x7fab0ea04bc0] Error muxing a packet
[out#0/mp4 @ 0x7fab0ea04bc0] Task finished with error code: -1094995529 (Invalid data found when processing input)
[out#0/mp4 @ 0x7fab0ea04bc0] Terminating thread with return code -1094995529 (Invalid data found when processing input)
[mp4 @ 0x7fab0ea04c80] Starting second pass: moving the moov atom to the beginning of the file
[out#0/mp4 @ 0x7fab0ea04bc0] Error writing trailer: Invalid data found when processing input
[out#0/mp4 @ 0x7fab0ea04bc0] video:1564089KiB audio:33415KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.083344%
frame=63994 fps=1400 q=-1.0 Lsize= 1598835KiB time=00:35:35.29 bitrate=6133.9kbits/s speed=46.7x    
Conversion failed!

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 3557, in process_info
  File "yt_dlp/YoutubeDL.py", line 3741, in post_process
  File "yt_dlp/YoutubeDL.py", line 3723, in run_all_pps
  File "yt_dlp/YoutubeDL.py", line 3701, in run_pp
  File "yt_dlp/postprocessor/common.py", line 23, in run
  File "yt_dlp/postprocessor/common.py", line 128, in wrapper
  File "yt_dlp/postprocessor/ffmpeg.py", line 840, in run
  File "yt_dlp/postprocessor/ffmpeg.py", line 330, in run_ffmpeg_multiple_files
  File "yt_dlp/postprocessor/ffmpeg.py", line 368, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

[download] Finished downloading playlist: Season 1
```

**Comment by dirkf** [comment]
From outside CA we get the trailers with no AD and all the audio tracks are the same length (~40s for Downton E1).

The extractor looks for `descriptive` in the `format_id` and demotes those formats, but that doesn't seem to be effective. A bug in that logic was fixed here some time ago.

**Comment by bashonly** [comment]
This doesn't seem at all like an issue with the default selection. If it's only happening with a couple episodes, it's much more likely that it's a problem on CBC's end, one that we would not be able to detect in advance

**Comment by PacoH** [comment]
Wait a minute. How did you conclude that this is happening with a couple episodes? Did you try it? It happened with all episodes of these two shows. Why did you change MY title to something that is irrelevant to my question?

**Comment by bashonly** [comment]
Calm down. The episodes you provided verbose output for are authwalled. The episodes that I could access were fine. If I have misunderstood the issue, please try to explain where my mistake was

**Comment by bashonly** [comment]
If you're willing to share account credentials I could take a look. DM me on discord (same username) or email me `bashonly [a t ] proton mail (do t) com`

**Comment by kucksdorfs** [comment]
I have gotten around this issue by including the following:

--ppa "FFmpeg:-c:v copy -c:a aac -strict experimental"

I'm not sure about the specifics as to why this is occurring for some episodes and not other, but doing this for "broken" episodes appears to work (not sure about episodes that were not broken before this).

**Comment by Devonavar** [comment]
Switching containers is another workaround (i.e. yt-dlp -t mkv) that doesn't involve transcoding the audio.
