### ISSUE TITLE
[GloboArticle] AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by sreisjr** [yt-dlp/yt-dlp#11541]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

yt-dlp is failed downloading videos from https://g1.globo.com

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose', 'https://g1.globo.com/politica/noticia/2024/11/14/moraes-cita-gabinete-do-odio-e-diz-que-explosoes-no-centro-de-brasilia-nao-sao-um-fato-isolado-do-contexto.ghtml']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-essentials_build-www.gyan.dev (setts), ffprobe 7.1-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[GloboArticle] Extracting URL: https://g1.globo.com/politica/noticia/2024/11/14/moraes-cita-gabinete-do-odio-e-diz-que-explosoes-no-centro-de-brasilia-nao-sao-um-fato-isolado-do-contexto.ghtml
[GloboArticle] moraes-cita-gabinete-do-odio-e-diz-que-explosoes-no-centro-de-brasilia-nao-sao-um-fato-isolado-do-contexto: Downloading webpage
WARNING: [GloboArticle] unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1760, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\globo.py", line 241, in _real_extract
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by bashonly** [comment]
```diff
diff --git a/yt_dlp/extractor/globo.py b/yt_dlp/extractor/globo.py
index d72296be6..76148e0f9 100644
--- a/yt_dlp/extractor/globo.py
+++ b/yt_dlp/extractor/globo.py
@@ -8,11 +8,13 @@
 from ..networking import HEADRequest
 from ..utils import (
     ExtractorError,
+    clean_html,
     float_or_none,
     orderedSet,
     str_or_none,
     try_get,
 )
+from ..utils.traversal import find_element, traverse_obj
 
 
 class GloboIE(InfoExtractor):
@@ -238,6 +240,9 @@ def _real_extract(self, url):
         entries = [
             self.url_result(f'globo:{video_id}', GloboIE.ie_key())
             for video_id in orderedSet(video_ids)]
-        title = self._og_search_title(webpage).strip()
-        description = self._html_search_meta('description', webpage)
-        return self.playlist_result(entries, display_id, title, description)
+
+        return self.playlist_result(
+            entries, display_id, **traverse_obj(webpage, {
+                'title': ({find_element(attr='itemprop', value='headline', tag='h1')}, {clean_html}),
+                'description': ({find_element(attr='itemprop', value='description', tag='p')}, {clean_html}),
+            }))
```
