### ISSUE TITLE
[ApplePodcasts] Download all episodes of a podcast

### ISSUE THREAD

**Issue by UnopposedForce91** [yt-dlp/yt-dlp#11560]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://podcasts.apple.com/us/podcast/dan-carlins-hardcore-history/id173001861

### Provide a description that is worded well enough to be understood

Currently, yt-dlp supports links from Apple podcasts, but only direct links to each episode. When giving yt-dlp the main link of a podcast it'll use the generic extractor, then prints out `Unsupported URL`.

I'd love yt-dlp to handle entire podcasts instead of feeding it each and every episode's URL.

Example:
- When trying to download `https://podcasts.apple.com/us/podcast/mania-for-subjugation/id173001861?i=1000658235879` it downloads successfully, because it's a single episode.
- When trying to download `https://podcasts.apple.com/us/podcast/dan-carlins-hardcore-history/id173001861` it fails with `Unsupported URL`, because it's the entire podcast.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://podcasts.apple.com/us/podcast/dan-carlins-hardcore-history/id173001861
[debug] Command-line config: ['-vU', 'https://podcasts.apple.com/us/podcast/dan-carlins-hardcore-history/id173001861']
[debug] Encodings: locale cp1256, fs utf-8, pref cp1256, out cp1256 (No VT), error cp1256 (No VT), screen cp1256 (No VT)
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (pip)
[debug] Python 3.12.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg N-117671-g562524587e-20241027 (setts), ffprobe N-117671-g562524587e-20241027
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.42.0, urllib3-2.2.2, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: AGB (YoutubeIE)
[debug] Plugin directories: ['C:\\Users\\Winuser\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\yt_dlp_plugins']
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://podcasts.apple.com/us/podcast/dan-carlins-hardcore-history/id173001861
[generic] id173001861: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] id173001861: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://podcasts.apple.com/us/podcast/dan-carlins-hardcore-history/id173001861
Traceback (most recent call last):
  File "C:\Users\Winuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Winuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1760, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\Winuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Winuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\generic.py", line 2553, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://podcasts.apple.com/us/podcast/dan-carlins-hardcore-history/id173001861
```

**Comment by vitaly-zdanevich** [comment]
Any cli alternative?

**Comment by vitaly-zdanevich** [comment]
Is RSS XML file is available on that page?

**Comment by bashonly** [comment]
> it then uses JS to GET them 25 at a time from amp-api.podcasts.apple.com as you scroll down the page. Those endpoints didn't like being curled.

For support to be added to yt-dlp, someone will need to figure out why those endpoints didn't like being curled and how yt-dlp can make requests to them

**Comment by Wowfunhappy** [comment]
> Is RSS XML file is available on that page?

No, not on the page. However, [Apple provides an API](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/LookupExamples.html) you can freely query.

Here's a shell script that will do it (requires `jq`):

```
input="https://podcasts.apple.com/us/podcast/dan-carlins-hardcore-history/id173001861"

id=$(echo "$input" | awk -F '/id' '{print $2}')
curl --silent "https://itunes.apple.com/lookup?id=$id" | jq -r .results[].feedUrl
```

Or in Python:

```
import requests
input = "https://podcasts.apple.com/us/podcast/dan-carlins-hardcore-history/id173001861"

itunes_id = input.split('/id')[1]
itunes_lookup_data = requests.get(f"https://itunes.apple.com/lookup?id={itunes_id}").json()
rss_feed = itunes_lookup_data['results'][0]['feedUrl']
print(rss_feed)
```

Either script will output:

> https://feeds.feedburner.com/dancarlin/history?format=xml

...which you can in turn throw straight into yt-dlp! Less than five lines of code!

It would be cool if yt-dlp handled getting the rss feed automatically, since once you have that everything just works!
