### ISSUE TITLE
Issue with Facebook: "Unable to Open File: [Errno 22] Invalid Argument"

### ISSUE THREAD

**Issue by xiaose** [yt-dlp/yt-dlp#11578]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

I encountered an error while using app to download a Facebook Reel. The command .\yt-dlp.exe -vU https://www.facebook.com/reel/352994937114633 fails with a file writing issue: [Errno 22] Invalid argument. 

It appears that the generated filename contains special characters or symbols that are not valid on my operating system (Windows 10).  The issue persists despite multiple retry attempts

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.facebook.com/reel/352994937114633']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.17.232856 from yt-dlp/yt-dlp-nightly-builds [da252d9d3] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.17.232856 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.17.232856 from yt-dlp/yt-dlp-nightly-builds)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/352994937114633
[facebook] Extracting URL: https://m.facebook.com/watch/?v=352994937114633&_rdr
[facebook] 352994937114633: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 352994937114633: Downloading 1 format(s): 577164268221105v+1094779592371500a
[debug] Invoking http downloader on "https://video-iev1-1.xx.fbcdn.net/v/t39.25447-2/462619592_1202671754131303_8173358216865820257_n.mp4?_nc_cat=107&ccb=1-7&_nc_sid=9a5d50&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdnA5LWJhc2ljLWdlbjJfNzIwcCIsInZpZGVvX2lkIjozNTI5OTQ5MzcxMTQ2MzN9&_nc_e2o=352994937114633&_nc_ohc=P8lq9mXQBl8Q7kNvgH9mqES&_nc_zt=28&_nc_ht=video-iev1-1.xx&_nc_gid=AQNW3dWf-dzdLqGscLla-6O&oh=00_AYAlDL4U4DDlLU2ZI-PZEeep3NjNFgOInTF4TAiZyt-Euw&oe=6741582B"
[download] Unable to open file: [Errno 22] Invalid argument: '22M views · 112K reactions ｜ Had his best night of sleep after I learned this trick from my doula! My baby has been dealing with a lit of indigestion & this has been the best tip for soothin #baby #love #cute #amnily #beautiful #instagood #photography #photooftheday #kids #reels #reels2023 #reelsviral #mom #life #momlife #picoftheday #fyp #toddler #babiesofinstagram #motherhood #babylove #babyfashion #photo #model #Real #smartbaby #eat #eating #toddler #toddlermom ｜ The Vincent Family [352994937114633].f577164268221105v.mp4.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '22M views · 112K reactions ｜ Had his best night of sleep after I learned this trick from my doula! My baby has been dealing with a lit of indigestion & this has been the best tip for soothin #baby #love #cute #amnily #beautiful #instagood #photography #photooftheday #kids #reels #reels2023 #reelsviral #mom #life #momlife #picoftheday #fyp #toddler #babiesofinstagram #motherhood #babylove #babyfashion #photo #model #Real #smartbaby #eat #eating #toddler #toddlermom ｜ The Vincent Family [352994937114633].f577164268221105v.mp4.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '22M views · 112K reactions ｜ Had his best night of sleep after I learned this trick from my doula! My baby has been dealing with a lit of indigestion & this has been the best tip for soothin #baby #love #cute #amnily #beautiful #instagood #photography #photooftheday #kids #reels #reels2023 #reelsviral #mom #life #momlife #picoftheday #fyp #toddler #babiesofinstagram #motherhood #babylove #babyfashion #photo #model #Real #smartbaby #eat #eating #toddler #toddlermom ｜ The Vincent Family [352994937114633].f577164268221105v.mp4.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '22M views · 112K reactions ｜ Had his best night of sleep after I learned this trick from my doula! My baby has been dealing with a lit of indigestion & this has been the best tip for soothin #baby #love #cute #amnily #beautiful #instagood #photography #photooftheday #kids #reels #reels2023 #reelsviral #mom #life #momlife #picoftheday #fyp #toddler #babiesofinstagram #motherhood #babylove #babyfashion #photo #model #Real #smartbaby #eat #eating #toddler #toddlermom ｜ The Vincent Family [352994937114633].f577164268221105v.mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 603, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 263, in download
  File "yt_dlp\downloader\common.py", line 241, in wrapper
  File "yt_dlp\utils\_utils.py", line 5251, in __iter__
  File "yt_dlp\downloader\common.py", line 234, in error_callback
  File "yt_dlp\utils\_utils.py", line 5259, in report_retry
  File "yt_dlp\downloader\common.py", line 243, in wrapper
  File "yt_dlp\downloader\common.py", line 254, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 606, in sanitize_open
OSError: [Errno 22] Invalid argument: '22M views · 112K reactions ｜ Had his best night of sleep after I learned this trick from my doula! My baby has been dealing with a lit of indigestion & this has been the best tip for soothin #baby #love #cute #amnily #beautiful #instagood #photography #photooftheday #kids #reels #reels2023 #reelsviral #mom #life #momlife #picoftheday #fyp #toddler #babiesofinstagram #motherhood #babylove #babyfashion #photo #model #Real #smartbaby #eat #eating #toddler #toddlermom ｜ The Vincent Family [352994937114633].f577164268221105v.mp4.part'


[debug] Invoking http downloader on "https://video-iev1-1.xx.fbcdn.net/v/t39.25447-2/463654610_1647822115801118_3777314692041365901_n.mp4?_nc_cat=105&ccb=1-7&_nc_sid=9a5d50&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfYXVkaW9fYWFjcF80OF9mbm9ybTE0X2ZyYWdfMl9hdWRpbyIsInZpZGVvX2lkIjozNTI5OTQ5MzcxMTQ2MzN9&_nc_e2o=352994937114633&_nc_ohc=89e1Xy9mVnUQ7kNvgEdY3HK&_nc_zt=28&_nc_ht=video-iev1-1.xx&_nc_gid=AQNW3dWf-dzdLqGscLla-6O&oh=00_AYAH6tvdny-3cMZG4E7ytQ1DNYGH3cLuf4hre2S1Po2aOw&oe=67412920"
[download] Unable to open file: [Errno 22] Invalid argument: '22M views · 112K reactions ｜ Had his best night of sleep after I learned this trick from my doula! My baby has been dealing with a lit of indigestion & this has been the best tip for soothin #baby #love #cute #amnily #beautiful #instagood #photography #photooftheday #kids #reels #reels2023 #reelsviral #mom #life #momlife #picoftheday #fyp #toddler #babiesofinstagram #motherhood #babylove #babyfashion #photo #model #Real #smartbaby #eat #eating #toddler #toddlermom ｜ The Vincent Family [352994937114633].f1094779592371500a.m4a.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '22M views · 112K reactions ｜ Had his best night of sleep after I learned this trick from my doula! My baby has been dealing with a lit of indigestion & this has been the best tip for soothin #baby #love #cute #amnily #beautiful #instagood #photography #photooftheday #kids #reels #reels2023 #reelsviral #mom #life #momlife #picoftheday #fyp #toddler #babiesofinstagram #motherhood #babylove #babyfashion #photo #model #Real #smartbaby #eat #eating #toddler #toddlermom ｜ The Vincent Family [352994937114633].f1094779592371500a.m4a.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '22M views · 112K reactions ｜ Had his best night of sleep after I learned this trick from my doula! My baby has been dealing with a lit of indigestion & this has been the best tip for soothin #baby #love #cute #amnily #beautiful #instagood #photography #photooftheday #kids #reels #reels2023 #reelsviral #mom #life #momlife #picoftheday #fyp #toddler #babiesofinstagram #motherhood #babylove #babyfashion #photo #model #Real #smartbaby #eat #eating #toddler #toddlermom ｜ The Vincent Family [352994937114633].f1094779592371500a.m4a.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '22M views · 112K reactions ｜ Had his best night of sleep after I learned this trick from my doula! My baby has been dealing with a lit of indigestion & this has been the best tip for soothin #baby #love #cute #amnily #beautiful #instagood #photography #photooftheday #kids #reels #reels2023 #reelsviral #mom #life #momlife #picoftheday #fyp #toddler #babiesofinstagram #motherhood #babylove #babyfashion #photo #model #Real #smartbaby #eat #eating #toddler #toddlermom ｜ The Vincent Family [352994937114633].f1094779592371500a.m4a.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 603, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 263, in download
  File "yt_dlp\downloader\common.py", line 241, in wrapper
  File "yt_dlp\utils\_utils.py", line 5251, in __iter__
  File "yt_dlp\downloader\common.py", line 234, in error_callback
  File "yt_dlp\utils\_utils.py", line 5259, in report_retry
  File "yt_dlp\downloader\common.py", line 243, in wrapper
  File "yt_dlp\downloader\common.py", line 254, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 606, in sanitize_open
OSError: [Errno 22] Invalid argument: '22M views · 112K reactions ｜ Had his best night of sleep after I learned this trick from my doula! My baby has been dealing with a lit of indigestion & this has been the best tip for soothin #baby #love #cute #amnily #beautiful #instagood #photography #photooftheday #kids #reels #reels2023 #reelsviral #mom #life #momlife #picoftheday #fyp #toddler #babiesofinstagram #motherhood #babylove #babyfashion #photo #model #Real #smartbaby #eat #eating #toddler #toddlermom ｜ The Vincent Family [352994937114633].f1094779592371500a.m4a.part'
```

**Comment by xiaose** [comment]
Despite using --windows-filenames and --restrict-filenames to simplify file naming, yt-dlp fails to open files for writing with [Errno 22] Invalid argument. The error persists even when there are no apparent special symbols in the filename. The issue may be related to filename length restrictions or file system behavior on Windows 10....

**Comment by xiaose** [comment]
Yes! With .\yt-dlp.exe --trim-filenames 66 --windows-filenames --restrict-filenames -vU https://www.facebook.com/reel/352994937114633 it works!

**Comment by bashonly** [comment]
best practice is to use an output template like `-o "%(title).100B [%(id)s].%(ext)s"`
