### ISSUE TITLE
Site support request for www.olevod.com

### ISSUE THREAD

**Issue by Ziyi6** [yt-dlp/yt-dlp#11581]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Unknown

### Example URLs

Single video: https://www.olevod.com/player/vod/2-60812-1.html
But in this website you can choose other episodes, for example the 2nd episode's website is: https://www.olevod.com/player/vod/2-60812-2.html, 3rd: https://www.olevod.com/player/vod/2-60812-3.html

### Provide a description that is worded well enough to be understood

The above site is not supported, could you support it? Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.olevod.com/player/vod/2-60812-1.html
[debug] Command-line config: ['-vU', 'https://www.olevod.com/player/vod/2-60812-1.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.26.232938 from yt-dlp/yt-dlp-nightly-builds [eabb4680f] (pip)
[debug] Python 3.9.17 (CPython x86_64 64bit) - Linux-6.5.0-35-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.9 30 May 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-None, certifi-2023.05.07, mutagen-1.47.0, requests-2.32.3, sqlite3-3.41.2, urllib3-2.2.1, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
Current version: nightly@2024.09.26.232938 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.11.18.232921 from yt-dlp/yt-dlp-nightly-builds
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[generic] Extracting URL: https://www.olevod.com/player/vod/2-60812-1.html
[generic] 2-60812-1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 2-60812-1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.olevod.com/player/vod/2-60812-1.html
Traceback (most recent call last):
  File "/home/devops/miniconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/devops/miniconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/home/devops/miniconda3/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/home/devops/miniconda3/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.olevod.com/player/vod/2-60812-1.html
```

**Comment by dirkf** [comment]
The site thoughtfully sends a 2MB WASM video player _in case some browser that supports WASM can't play videos_.   

It loads media details from https://api.olelive.com/v1/pub/vod/detail/60812/true, but (exercise for the reader) you have to construct and send the `_vv` query parameter to avoid 401.
