### ISSUE TITLE
yt-dlp cmd works, embed script fails on age restricted video

### ISSUE THREAD

**Issue by altCensored** [yt-dlp/yt-dlp#11597]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

age restricted video works with yt-dlp but fails with embed script using the same cookie file:
yt-dlp --cookies /opt/altcen/jose_cookies.txt -s -v "https://www.youtube.com/watch?v=980cWx9wyd8"

ERROR: [youtube] 980cWx9wyd8: Sign in to confirm your age.

i noticed that yt-dlp is able to extract the SAPISID cookie, the embed script does not.
can this be made to work without a PO Token?

txs

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp:

[debug] Command-line config: ['--cookies', '/opt/altcen/jose_cookies.txt', '-s', '-v', 'https://www.youtube.com/watch?v=980cWx9wyd8']
[debug] System config "/etc/yt-dlp.conf": []
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-49-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: sqlite3-3.45.1
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=980cWx9wyd8
[youtube] 980cWx9wyd8: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] 980cWx9wyd8: Downloading ios player API JSON
[youtube] 980cWx9wyd8: Downloading mweb player API JSON
[debug] [youtube] Extracting signature function js_5f315c3d_100
[debug] Loading youtube-sigfuncs.js_5f315c3d_100 from cache
[debug] Loading youtube-nsig.5f315c3d from cache
[debug] [youtube] Decrypted nsig KuNWPqFVdDEdfh0Zi => 3x3PJA7erGnSaw
[debug] [youtube] Extracting signature function js_5f315c3d_104
[debug] Loading youtube-sigfuncs.js_5f315c3d_104 from cache
[debug] Loading youtube-nsig.5f315c3d from cache
[debug] [youtube] Decrypted nsig XCk0dDpH0tdJv73a3 => IXz3MNiHW24m6g
[youtube] 980cWx9wyd8: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 980cWx9wyd8: Downloading 1 format(s): 135+251

embed:

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (pip) API
[debug] params: {'cookies': '/opt/altcen/jose_cookies.txt', 'logtostderr': True, 'quiet': False, 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Saf
ari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-49-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: sqlite3-3.45.1
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=980cWx9wyd8
[youtube] 980cWx9wyd8: Downloading webpage
[youtube] 980cWx9wyd8: Downloading ios player API JSON
[youtube] 980cWx9wyd8: Downloading mweb player API JSON
ERROR: [youtube] 980cWx9wyd8: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually p
ass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4465, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1276, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

Traceback (most recent call last):
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1759, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4465, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1276, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] 980cWx9wyd8: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp 
 for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lc/syncthing/altcen/test/yt_dlp/./video_cookie.py", line 29, in <module>
    vinfo = ydl.extract_info(vURL, download=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1613, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1642, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1090, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/lc/syncthing/altcen/test/yt_dlp/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1029, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] 980cWx9wyd8: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-y
t-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
```

**Comment by bashonly** [comment]
the param is `cookiefile` not `cookies`

**Comment by altCensored** [comment]
doggoneit, txs!
