### ISSUE TITLE
[Broken] YouTube: several channels fail with "Unable to recognize tab page"

### ISSUE THREAD

**Issue by jbruchon** [yt-dlp/yt-dlp#116]
## Verbose log

```
Y:\YouTube Channels\131216>youtube-dl --match-filter "!is_live & !live" --cookies "Y:\cookies.txt" --add-metadata --write-description --write-info-json --write-thumbnail --download-archive "Y:\ytdl_archive.txt" --write-subs --write-auto-subs --sub-lang en,en_US --convert-subs srt -ciw -o "%(title)s.%(ext)s" -v "https://www.youtube.com/channel/UCUBdiAE5sIA9kNYyjU5xUqg"
[debug] Command-line config: ['--match-filter', '!is_live & !live', '--cookies', 'Y:\\cookies.txt', '--add-metadata', '--write-description', '--write-info-json', '--write-thumbnail', '--download-archive', 'Y:\\ytdl_archive.txt', '--write-subs', '--write-auto-subs', '--sub-lang', 'en,en_US', '--convert-subs', 'srt', '-ciw', '-o', '%(title)s.%(ext)s', '-v', 'https://www.youtube.com/channel/UCUBdiAE5sIA9kNYyjU5xUqg']
[debug] Loading archive file 'Y:\\ytdl_archive.txt'
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.02.24 (exe)
[debug] Python version 3.9.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-01-12-git-ca21cb1e36-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
WARNING: A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[youtube:tab] UCUBdiAE5sIA9kNYyjU5xUqg: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1018, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1039, in __extract_info
  File "yt_dlp\extractor\common.py", line 538, in extract
  File "yt_dlp\extractor\youtube.py", line 3030, in _real_extract
yt_dlp.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

## Description

(This is using current master). Several of the channels I archive are failing to download. I've verified everything I can on my end. The failures seem consistent across runs, and other channels are working. The only issue with this same error message was an error due to channel termination, but these are active channels that are failing. A small sample of other URLs that are failing include:

```
https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
https://www.youtube.com/c/ahilltodieon
https://www.youtube.com/user/chilledsanity
```

This may have been happening yesterday as well, and I was on a somewhat older commit until I saw the problem a few minutes ago, so it's probably not a very recent change to the program that's doing this.

**Comment by pukkandan** [comment]
It is working for me. Please give verbose log and the dumps generated by `--write-pages`

```cmd
$ yt-dlp "https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw"
WARNING: A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[youtube:tab] UCYO_jab_esuFRV4b17AJtAw: Downloading webpage
[download] Downloading playlist: 3Blue1Brown - Videos
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] playlist 3Blue1Brown - Videos: Downloading 112 videos
[download] Downloading video 1 of 112
[youtube] lG4VkPoG3ko: Downloading webpage
[info] Downloading format(s) 308+251
ERROR: Interrupted by user

$ yt-dlp "https://www.youtube.com/c/ahilltodieon"
WARNING: A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[youtube:tab] ahilltodieon: Downloading webpage
[download] Downloading playlist: A Hill to Die On - Videos
[youtube:tab] playlist A Hill to Die On - Videos: Downloading 10 videos
[download] Downloading video 1 of 10
[youtube] iBWn8vBOE9E: Downloading webpage
[info] Downloading format(s) 313+251
[download] Destination: Pandas Are a Scam. [iBWn8vBOE9E].f313.webm
[download]   0.4% of 452.28MiB at  2.73MiB/s ETA 02:44
ERROR: Interrupted by user

$ yt-dlp "https://www.youtube.com/user/chilledsanity"
WARNING: A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[youtube:tab] chilledsanity: Downloading webpage
[download] Downloading playlist: Accursed Farms - Videos
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] Downloading page 6
[youtube:tab] Downloading page 7
[youtube:tab] playlist Accursed Farms - Videos: Downloading 215 videos
[download] Downloading video 1 of 215
[youtube] h0_4wVcZhmU: Downloading webpage
[info] Downloading format(s) 247+251
[download] Destination: Videochat February 2021 [h0_4wVcZhmU].f247.webm
[download]   0.1% of 751.11MiB at  3.32MiB/s ETA 03:46
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
Update. I managed to reproduce the issue, but not consistently
```cmd
$ yt-dlp "https://www.youtube.com/channel/UCUBdiAE5sIA9kNYyjU5xUqg"
WARNING: A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[youtube:tab] UCUBdiAE5sIA9kNYyjU5xUqg: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

$ yt-dlp "https://www.youtube.com/channel/UCUBdiAE5sIA9kNYyjU5xUqg"
WARNING: A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[youtube:tab] UCUBdiAE5sIA9kNYyjU5xUqg: Downloading webpage
[download] Downloading playlist: 131216 - Videos
[youtube:tab] playlist 131216 - Videos: Downloading 21 videos
[download] Downloading video 1 of 21
[youtube] wIjb6DzAuPs: Downloading webpage
ERROR: Interrupted by user
```

**Comment by jbruchon** [comment]
Yeah, you're probably right about the A/B testing. Do you still need me to dump pages?

**Comment by pukkandan** [comment]
I created a dump file

**Comment by jbruchon** [comment]
I think there is something wrong at YouTube. I have a computer here that I did a clean Win10 install on that's having trouble loading my own YouTube channel and videos.

**Comment by pukkandan** [comment]
I was investigating the issue, and when the error happens, the page youtube gives does not have any channel/video metadata. So it does seem like it is an issue from youtube's side. In any case, I will push a change to retry few times when encountering partial webpage
