### ISSUE TITLE
Thrivecart Embedded Vimeo Video

### ISSUE THREAD

**Issue by appyface** [yt-dlp/yt-dlp#11650]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/

### Provide a description that is worded well enough to be understood

I tried yt-dlp with URL given above. Got "Unsupported URL" message. Content creator states host is Thrivecart. (I am just user, I don't know how to verify).

Next, on the playing video I right-clicked and chose "open frame in new window". The new URL is Vimeo.  https://player.vimeo.com/video/867026229?h=0bcd10eae4&badge=0&autopause=0&player_id=0&app_id=58479    I tried this URL and yt-dlp successfully downloaded the video.

My credentials may be needed, happy to provide privately.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/
[debug] Command-line config: ['-vU', 'https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/']
[debug] Portable config "C:\Users\home\Downloads\ytdlp_try\yt-dlp.conf": ['-o', '%(title).150B [%(id)s].%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/
[generic] masterclass-video: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] masterclass-video: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1624, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1759, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/
```

**Comment by bashonly** [comment]
If the site requires login, can you add a verbose log where you [pass logged-in cookies to yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) please

**Comment by appyface** [comment]
Yes, how do I mark it private or provide it privately please?

**Comment by bashonly** [comment]
It shouldn't contain any identifying or sensitive information. Cookie values are not recorded in the log

**Comment by bashonly** [comment]
just asking for the output of a command like
```
yt-dlp --cookies cookies.txt -v "https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/"
```

**Comment by appyface** [comment]
Thank you for the assist! Here it is:

yt-dlp --cookies cookies.txt -v "https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/"
[debug] Command-line config: ['--cookies', 'cookies.txt', '-v', 'https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/']
[debug] Portable config "C:\Users\home\Downloads\ytdlp_try\yt-dlp.conf": ['-o', '%(title).150B [%(id)s].%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[generic] Extracting URL: https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/
[generic] masterclass-video: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] masterclass-video: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1624, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1759, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://cart.audreyslittlefarm.com/l/how-to-start-grow-a-raised-bed-garden-masterclass/masterclass-video/
