### ISSUE TITLE
[Youtube] Age-restricted content fails after partial video download

### ISSUE THREAD

**Issue by BarabasFiesta** [yt-dlp/yt-dlp#11686]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

When downloading age-restricted content from Youtube, some videos are failing after partial download with HTTP response code 403 errors. Partially downloaded files all fail between 50 seconds to 1 minute of video download regardless of size or format. Downloading only the audio format fails immediately.

Content plays in Chrome and Firefox browsers with no issues.

Notes:
--extractor-args "youtube:player_client=default,-ios" added as a workaround for [#11640](https://github.com/yt-dlp/yt-dlp/issues/11640)
--cookies-from-browser "firefox" added to access Youtube age-restricted content

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=vX1kfDQik40']
[debug] Portable config "F:\yt-dlp\yt-dlp.conf": ['--download-archive', 'F:\\yt-dlp\\download archive.txt', '--cookies-from-browser', 'firefox', '--extractor-args', 'youtube:player_client=default,-ios', '-f', 'bv*+ba/b', '-P', 'F:\\yt-dlp', '-o', '%(webpage_url_domain)s\\%(uploader)s [%(uploader_id)s]\\%(title)s (%(resolution)s %(vcodec)s %(acodec)s) [%(id)s].%(ext)s', '--retries', '3', '--socket-timeout', '15']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg n7.1-6-g9b061291ad-20241005 (setts), ffprobe n7.1-6-g9b061291ad-20241005
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\********\AppData\Roaming\Mozilla\Firefox\Profiles\71plmmar.default-release\cookies.sqlite"
Extracted 78 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Loading archive file 'F:\\yt-dlp\\download archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=vX1kfDQik40
[youtube] vX1kfDQik40: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] vX1kfDQik40: Downloading mweb player API JSON
[debug] Loading youtube-nsig.b46bb280 from cache
[debug] [youtube] Decrypted nsig kNXDW-fEzlnmJJ03MZO => 18UEKX2O6DWE_A
[debug] Loading youtube-nsig.b46bb280 from cache
[debug] [youtube] Decrypted nsig MJZghSt-kddBERL1xOg => -cAKrg35iLz4Mw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] vX1kfDQik40: Downloading 1 format(s): 308+251
[debug] Invoking http downloader on "https://rr3---sn-8xgp1vo-p5qee.googlevideo.com/videoplayback?expire=1733012370&ei=MldLZ_DJFYWKkucPh-7n0As&ip=96.231.242.109&id=o-ADWgMr39t7F3rCnd5qP4w56Y759WsaRuIRlGhIrtZ47N&itag=308&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1732990770%2C&mh=lh&mm=31%2C26&mn=sn-8xgp1vo-p5qee%2Csn-vgqsrnsd&ms=au%2Conr&mv=m&mvi=3&pl=16&rms=au%2Cau&initcwndbps=1311250&siu=1&bui=AQn3pFTlrHH2s7XJ5ngn2OKVNgFSVvbUhV7f4hvau026Q1ScBDJ-AfaajK1K7gkd8anEqX5qBg&spc=qtApAdCMjxZo5a0PnO0kIuUjCoC3Y2-yQj9hT_EmosxRGslNpSuQCGTtfsH9n4-l-OPZDzpQ87gi&vprv=1&svpuc=1&mime=video%2Fwebm&ns=Yj_5i01MtVsZF7I0UPpk7yoQ&rqh=1&gir=yes&clen=288196514&dur=212.316&lmt=1706529335004079&mt=1732990398&fvip=5&keepalive=yes&fexp=51326932%2C51331020%2C51335594&c=MWEB&sefc=1&txp=6219224&n=-cAKrg35iLz4Mw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAOxfOleRdMVP23VyQ108AoCXpND5JydwAUmohIDasLFcAiEAxUZrkgGzc65stiTXdgd3jAXX8QtJcQ83_JpS6XdOiMc%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRgIhAI0gzfFkjlWeHqOZlQN6q2EiQF7--ImCiYBkrI61IEm6AiEA12h8SeN9XNU56LeJiu_g7LzGbXLKQBKH3uvdshvcOo0%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: F:\yt-dlp\youtube.com\Ginger cat kuon [@Gingercatkuon]\【Furina -  Genshin Impact】ザムザ (2560x1440 vp9 opus) [vX1kfDQik40].f308.webm
[download]  24.9% of  274.85MiB at   21.95MiB/s ETA 00:09ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3460, in process_info
  File "yt_dlp\YoutubeDL.py", line 3198, in dl
  File "yt_dlp\downloader\common.py", line 464, in download
  File "yt_dlp\downloader\http.py", line 367, in real_download
  File "yt_dlp\downloader\http.py", line 118, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 4161, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
Does passing `--extractor-args "youtube:player_client=web_creator"` (instead of your current extractor-arg) help?

**Comment by BarabasFiesta** [comment]
@bashonly That worked! You're a genius!

```
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=vX1kfDQik40']
[debug] Portable config "F:\yt-dlp\yt-dlp.conf": ['--cookies-from-browser', 'firefox', '--extractor-args', 'youtube:player_client=web_creator', '-f', 'bv*+ba/b', '-P', 'F:\\yt-dlp', '-o', '%(webpage_url_domain)s\\%(uploader)s [%(uploader_id)s]\\%(title)s (%(resolution)s %(vcodec)s %(acodec)s) [%(id)s].%(ext)s', '--retries', '3', '--socket-timeout', '15']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg n7.1-6-g9b061291ad-20241005 (setts), ffprobe n7.1-6-g9b061291ad-20241005
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Warren.Wang\AppData\Roaming\Mozilla\Firefox\Profiles\71plmmar.default-release\cookies.sqlite"
Extracted 78 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=vX1kfDQik40
[youtube] vX1kfDQik40: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] vX1kfDQik40: Downloading web creator player API JSON
[debug] Loading youtube-nsig.b46bb280 from cache
[debug] [youtube] Decrypted nsig 31j-KEh-hlDBt3elhZr => 3Z0kJWiNEZhnwQ
[debug] Loading youtube-nsig.b46bb280 from cache
[debug] [youtube] Decrypted nsig 01tk8NPk6MxSU5NIWAU => 76hQJOB2w_Dk9Q
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] vX1kfDQik40: Downloading 1 format(s): 308+251
[debug] Invoking http downloader on "https://rr3---sn-8xgp1vo-p5qee.googlevideo.com/videoplayback?expire=1733013896&ei=KF1LZ7vGMOmnkucPo-KT-A4&ip=96.231.242.109&id=o-AHBnwEo2sVIbAr0HktRxyjtfF206p1bES5-lfjrljyNY&itag=308&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1732992296%2C&mh=lh&mm=31%2C26&mn=sn-8xgp1vo-p5qee%2Csn-vgqsknll&ms=au%2Conr&mv=m&mvi=3&pl=16&rms=au%2Cau&initcwndbps=1173750&siu=1&bui=AQn3pFT4RqzN_bfl9uv8TDckTpyOreXMfQeKGtqtRlI2Vnt2I4XrlwZWBVoZ2FEEfA-ZeRVWuw&spc=qtApAa5ZZg_7mWJ_SKgFIoUK4QdgVa209qGd_oBTo-vdNoIO1kb_ZWUmprSI9PSZ8w&vprv=1&svpuc=1&mime=video%2Fwebm&ns=nexUjZ21B4GXV8TFr-oPB3EQ&rqh=1&gir=yes&clen=288196514&dur=212.316&lmt=1706529335004079&mt=1732991833&fvip=5&keepalive=yes&fexp=51326932%2C51335594&c=WEB_CREATOR&sefc=1&txp=6219224&n=76hQJOB2w_Dk9Q&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgbulKwj4FXArenTdt1PtdDynYPGO_sFvl3iyYCpjtj9kCIARuig6S4G3TfQu2uuvKto1JO8IGJKGp8QhjD497XwxN&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRgIhAPPpe9bWpn-FB7SoXAHvWNY71CDiXGIXSkfBuDcLfqoYAiEA87qPD_AbEIrnq03GLKnNI9eNaflwuTHBS7AMbwuMU34%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: F:\yt-dlp\youtube.com\Ginger cat kuon [@Gingercatkuon]\【Furina -  Genshin Impact】ザムザ (2560x1440 vp9 opus) [vX1kfDQik40].f308.webm
[download] 100% of  274.85MiB in 00:00:10 at 27.40MiB/s
[debug] Invoking http downloader on "https://rr3---sn-8xgp1vo-p5qee.googlevideo.com/videoplayback?expire=1733013896&ei=KF1LZ7vGMOmnkucPo-KT-A4&ip=96.231.242.109&id=o-AHBnwEo2sVIbAr0HktRxyjtfF206p1bES5-lfjrljyNY&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1732992296%2C&mh=lh&mm=31%2C26&mn=sn-8xgp1vo-p5qee%2Csn-vgqsknll&ms=au%2Conr&mv=m&mvi=3&pl=16&rms=au%2Cau&initcwndbps=1173750&siu=1&bui=AQn3pFT4RqzN_bfl9uv8TDckTpyOreXMfQeKGtqtRlI2Vnt2I4XrlwZWBVoZ2FEEfA-ZeRVWuw&spc=qtApAa5ZZg_7mWJ_SKgFIoUK4QdgVa209qGd_oBTo-vdNoIO1kb_ZWUmprSI9PSZ8w&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=nexUjZ21B4GXV8TFr-oPB3EQ&rqh=1&gir=yes&clen=3513468&dur=212.341&lmt=1706529150776519&mt=1732991833&fvip=5&keepalive=yes&fexp=51326932%2C51335594&c=WEB_CREATOR&sefc=1&txp=6218224&n=76hQJOB2w_Dk9Q&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAOpOeAG5SDhxezJ6VqTU0VowbD-ko7Vi-I0o_PgV_sh7AiAGGMN_FtkKmRc02x9BkvKkt884bMbQygxKetCcpkjhHA%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRgIhAPPpe9bWpn-FB7SoXAHvWNY71CDiXGIXSkfBuDcLfqoYAiEA87qPD_AbEIrnq03GLKnNI9eNaflwuTHBS7AMbwuMU34%3D"
[download] Destination: F:\yt-dlp\youtube.com\Ginger cat kuon [@Gingercatkuon]\【Furina -  Genshin Impact】ザムザ (2560x1440 vp9 opus) [vX1kfDQik40].f251.webm
[download] 100% of    3.35MiB in 00:00:00 at 8.19MiB/s
[Merger] Merging formats into "F:\yt-dlp\youtube.com\Ginger cat kuon [@Gingercatkuon]\【Furina -  Genshin Impact】ザムザ (2560x1440 vp9 opus) [vX1kfDQik40].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:F:\yt-dlp\youtube.com\Ginger cat kuon [@Gingercatkuon]\【Furina -  Genshin Impact】ザムザ (2560x1440 vp9 opus) [vX1kfDQik40].f308.webm" -i "file:F:\yt-dlp\youtube.com\Ginger cat kuon [@Gingercatkuon]\【Furina -  Genshin Impact】ザムザ (2560x1440 vp9 opus) [vX1kfDQik40].f251.webm" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:F:\yt-dlp\youtube.com\Ginger cat kuon [@Gingercatkuon]\【Furina -  Genshin Impact】ザムザ (2560x1440 vp9 opus) [vX1kfDQik40].temp.webm"
Deleting original file F:\yt-dlp\youtube.com\Ginger cat kuon [@Gingercatkuon]\【Furina -  Genshin Impact】ザムザ (2560x1440 vp9 opus) [vX1kfDQik40].f308.webm (pass -k to keep)
Deleting original file F:\yt-dlp\youtube.com\Ginger cat kuon [@Gingercatkuon]\【Furina -  Genshin Impact】ザムザ (2560x1440 vp9 opus) [vX1kfDQik40].f251.webm (pass -k to keep)
```

**Comment by bashonly** [comment]
Good to hear that workaround worked. But it seems there's a problem with the `mweb` client now, so keeping this issue open until that can be resolved

**Comment by Yoksven** [comment]
I also had problems with `mweb` giving me 403 even with cookies (only firefox cookies worked, both brave and vivaldi would 403).

`--extractor-args "youtube:player_client=web_creator"` worked like a charm. Still asks to sign in, but no 403 using any cookies.

I am using a VPN though and problems started when I had to jump servers (previous got too crowded and slow), so, not a completely normal use case.

**Comment by bashonly** [comment]
@BarabasFiesta @Yoksven Try updating to nightly (run `yt-dlp --update-to nightly` or else [upgrade with pip](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-nightly)) and see if that solves the issue.

If you want, you could even test the `mweb` client specifically by adding `--extractor-arg "youtube:player_client=mweb"` to your command, and then report back here whether or not you still get 403 errors when passing cookies

**Comment by Yoksven** [comment]
Just tried nightly. All cookies work with `mweb` client (firefox, vivaldi and brave). No 403. Seems good.
