### ISSUE TITLE
Add support for tvmonaco.com

### ISSUE THREAD

**Issue by archie83** [yt-dlp/yt-dlp#11687]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

https://videos.tvmonaco.com/content/la-grande-traversee-des-alpes-ep01-la-premiere-semaine-de-marche-la-region-du-mont-blanc

### Provide a description that is worded well enough to be understood

I can't download videos from tvmonaco.com:
ERROR: Unsupported URL: https://videos.tvmonaco.com/content/la-grande-traversee-des-alpes-ep01-la-premiere-semaine-de-marche-la-region-du-mont-blanc

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://videos.tvmonaco.com/content/la-grande-traversee-des-alpes-ep01-la-premiere-semaine-de-marche-la-region-du-mont-blanc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.11.30 [00dcde728]
[debug] Python 3.12.7 (CPython x86_64 64bit) - Linux-6.6.52-gentoo-x86_64-Intel-R-_Core-TM-_i5-3550_CPU_@_3.30GHz-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: brotli-1.1.0, certifi-3024.7.22, pycrypto-3.21.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (local@2024.11.30)
[generic] Extracting URL: https://videos.tvmonaco.com/content/la-grande-traversee-des-alpes-ep01-la-premiere-semaine-de-marche-la-region-du-mont-blanc
[generic] la-grande-traversee-des-alpes-ep01-la-premiere-semaine-de-marche-la-region-du-mont-blanc: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] la-grande-traversee-des-alpes-ep01-la-premiere-semaine-de-marche-la-region-du-mont-blanc: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://videos.tvmonaco.com/content/la-grande-traversee-des-alpes-ep01-la-premiere-semaine-de-marche-la-region-du-mont-blanc
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1759, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2553, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://videos.tvmonaco.com/content/la-grande-traversee-des-alpes-ep01-la-premiere-semaine-de-marche-la-region-du-mont-blanc
```

**Comment by DavidRogerio** [comment]
I will work on this
