### ISSUE TITLE
[SOLVED] yt-dlp/ffmpeg cannot download from m3u8 but wget/python-requests download works?

### ISSUE THREAD

**Issue by mirkasjim** [yt-dlp/yt-dlp#11696]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have a link to a m3u8 hls2 playlist (sample: https://cdn1016.tnmr.org/hls2/02/00387/vq0v4ym8g2r4_h/master.m3u8?t=hMTfe8Zt9UIpRnrt_zL8jKzIjOzuiU4DsRul4FmKt6c&s=1733060522&e=43200&f=1939854&i=0.3&sp=0 , and https://cdn1025.tnmr.org/hls2/01/00729/izdc9fnmuejz_h/master.m3u8?t=LlLoHh3Czx13ElEcbl7dzpDSrbE7CHz3g5I3fH_Cx_o&s=1733061107&e=43200&f=3648271&i=0.3&sp=0)

These m3u8 links can be downloaded in via python-requests, as well as plain wget 
But trying to download via yt-dlp/ffmpeg/curl gives a 403 forbidden error message

It is possible to download each ts segment separately via wget, but yt-dlp should have been
[master.m3u8.zip](https://github.com/user-attachments/files/17969148/master.m3u8.zip)
 able to access the m3u8 link?

I'm attaching a sample master.m3u8 (downloaded via wget). wget/python-requests can download each chunk, but yt-dlp/ffmpeg/curl can't. 

Any theories as to what might be going wrong?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://cdn1016.tnmr.org/hls2/02/00387/vq0v4ym8g2r4_h/master.m3u8?t=hMTfe8Zt9UIpRnrt_zL8jKzIjOzuiU4DsRul4FmKt6c&s=1733060522&e=43200&f=1939854&i=0.3&sp=0
[generic] master.m3u8?t=hMTfe8Zt9UIpRnrt_zL8jKzIjOzuiU4DsRul4FmKt6c&s=1733060522&e=43200&f=1939854&i=0: Downloading webpage
3200&f=1939854&i=0.3&sp=0']
[debug] User config "/home/ashanaa/.config/yt-dlp/config": ['--cookies=/home/ashanaa/.dotfiles/hashbang/.config/yt-dlp/cookies.txt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.7.12+bpo-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.36)
[debug] exe versions: ffmpeg N-71064-gd5e603ddc0-static (setts), ffprobe N-71064-gd5e603ddc0-static, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2024.07.04, mutagen-1.47.0, requests-2.31.0, sqlite3-3.40.1, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Plugin directories: ['/home/ashanaa/.local/lib/python3.11/site-packages/yt_dlp_plugins']
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "/home/ashanaa/.python_scripts/bin/youtube-dl/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashanaa/.python_scripts/bin/youtube-dl/yt_dlp/extractor/generic.py", line 2393, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashanaa/.python_scripts/bin/youtube-dl/yt_dlp/extractor/common.py", line 911, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/ashanaa/.python_scripts/bin/youtube-dl/yt_dlp/networking/_urllib.py", line 398, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
 File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ashanaa/.python_scripts/bin/youtube-dl/yt_dlp/extractor/common.py", line 898, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashanaa/.python_scripts/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 4161, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashanaa/.python_scripts/bin/youtube-dl/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashanaa/.python_scripts/bin/youtube-dl/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashanaa/.python_scripts/bin/youtube-dl/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ashanaa/.python_scripts/bin/youtube-dl/yt_dlp/networking/_urllib.py", line 403, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
I get a 403 no matter what tool I use, so no idea.
