### ISSUE TITLE
[adobepass] `--ap-mso TWC`: Error when attempting to download video from NBC

### ISSUE THREAD

**Issue by AndyPeterman** [yt-dlp/yt-dlp#11712]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

I'm attempting to download a recent program from www.NBC.com (see debug code full link).   This program plays fine, with lot of commercials, on Chrome, but plays with a black screen on Safari.  

I've tried numerous times with different options, but always end up with a "Unable to extract post url".

yt_dlp was installed on a Mac using HomeBrew.

Thank you. 😀

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ap-mso', 'TWC', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.nbc.com/the-tonight-show/video/jerry-seinfeld-cody-rhodes-billy-strings/9000156840']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (pip)
[debug] Python 3.13.0 (CPython x86_64 64bit) - macOS-15.1.1-x86_64-i386-64bit-Mach-O (OpenSSL 3.4.0 22 Oct 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[NBC] Extracting URL: https://www.nbc.com/the-tonight-show/video/jerry-seinfeld-cody-rhodes-billy-strings/9000156840
[NBC] 9000156840: Downloading JSON metadata
[NBC] 9000156840: Downloading JSON metadata
[NBC] 9000156840: Downloading Provider Redirect Page
ERROR: [NBC] 9000156840: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/nbc.py", line 212, in _real_extract
    query['auth'] = self._extract_mvpd_auth(
                    ~~~~~~~~~~~~~~~~~~~~~~~^
        url, video_id, 'nbcentertainment', resource)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/adobepass.py", line 1712, in _extract_mvpd_auth
    provider_login_page_res = post_form(
        provider_redirect_page_res, self._DOWNLOADING_LOGIN_PAGE)
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/adobepass.py", line 1396, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1382, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1346, in _search_regex
    raise RegexNotFoundError(f'Unable to extract {_name}')
```

**Comment by bashonly** [comment]
It's an issue with adobepass (signing into your MSO provider) rather than NBC

You could try passing `--user-agent "Mozilla/5.0 (Windows NT 10.0; rv:131.0) Gecko/20100101 Firefox/131.0"` with your command and seeing if that helps

**Comment by AndyPeterman** [comment]
I tried it with --user-agent...  and got the exact same results.

BTW, I've also gotten an NBCUniversal Profile login, but haven't quite figured out the use of
 --netrc yet.  Should I give that a try?

**Comment by bashonly** [comment]
> BTW, I've also gotten an NBCUniversal Profile login, but haven't quite figured out the use of --netrc yet. Should I give that a try?

I don't think the NBC extractor supports that.

What you could try is [exporting cookies to a cookiefile and passing it to yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) *along with* your MSO options

**Comment by AndyPeterman** [comment]
OK, I've read about cookies and instead of exporting cookies from Chrome (which didn't do it in the required format) I instead used the option: --cookies-from-browser chrome

Same results.  The output is identical except for the following additional lines (username x'd out):

Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/xxx/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
Extracted 127 cookies from chrome
[debug] cookie version breakdown: {'v10': 127, 'other': 0, 'unencrypted': 0}

I did this just after loading and successfully playing the show in Google Chrome.

What now?

**Comment by bashonly** [comment]
Try exporting cookies. Exported cookies will include session cookies, which `--cookies-from-browser` may not

**Comment by AndyPeterman** [comment]
So now I've successfully exported the cookies using yt-dlp (sorry, I must have missed that trick in the documentation) and now, using the --cookies I get the following (NOTE:  I see there's a new version that just came out - I tried to upgrade, but it must not be available yet):

[debug] Command-line config: ['-vU', '--ap-mso', 'TWC', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; rv:131.0) Gecko/20100101 Firefox/131.0', '--cookies', 'cookies.txt', 'https://www.nbc.com/the-tonight-show/video/jerry-seinfeld-cody-rhodes-billy-strings/9000156840']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (pip)
[debug] Python 3.13.0 (CPython x86_64 64bit) - macOS-15.1.1-x86_64-i386-64bit-Mach-O (OpenSSL 3.4.0 22 Oct 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.11.18 from yt-dlp/yt-dlp
Latest version: stable@2024.12.03 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[NBC] Extracting URL: https://www.nbc.com/the-tonight-show/video/jerry-seinfeld-cody-rhodes-billy-strings/9000156840
[NBC] 9000156840: Downloading JSON metadata
[NBC] 9000156840: Downloading JSON metadata
[NBC] 9000156840: Downloading Provider Redirect Page
ERROR: [NBC] 9000156840: Unable to download webpage: HTTPSConnectionPool(host='www.nbc.com', port=443): Read timed out. (read timeout=20.0) (caused by TransportError("HTTPSConnectionPool(host='www.nbc.com', port=443): Read timed out. (read timeout=20.0)"))
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/nbc.py", line 212, in _real_extract
    query['auth'] = self._extract_mvpd_auth(
                    ~~~~~~~~~~~~~~~~~~~~~~~^
        url, video_id, 'nbcentertainment', resource)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/adobepass.py", line 1449, in _extract_mvpd_auth
    provider_redirect_page_res = self._download_webpage_handle(
        self._SERVICE_PROVIDER_TEMPLATE % 'authenticate/saml', video_id,
    ...<10 lines>...
            'User-Agent': self._MODERN_USER_AGENT,
        } if mso_id == 'Comcast_SSO' else None)
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/adobepass.py", line 1367, in _download_webpage_handle
    return super()._download_webpage_handle(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        *args, **kwargs)
        ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 962, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
                                 headers=headers, query=query, expected_status=expected_status,
                                 impersonate=impersonate, require_impersonation=require_impersonation)
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 911, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1428, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1138, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/urllib3/util/retry.py", line 449, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
        self, url, f"Read timed out. (read timeout={timeout_value})"
    ) from err
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.nbc.com', port=443): Read timed out. (read timeout=20.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/networking/_requests.py", line 328, in _send
    requests_res = session.request(
        method=request.method,
    ...<6 lines>...
        stream=True,
    )
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
                                ^^^
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/requests/sessions.py", line 265, in resolve_redirects
    resp = self.send(
        req,
    ...<6 lines>...
        **adapter_kwargs,
    )
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.nbc.com', port=443): Read timed out. (read timeout=20.0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 898, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 4161, in urlopen
    return self._request_director.send(req)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ~~~~~~~~~~^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2024.11.18/libexec/lib/python3.13/site-packages/yt_dlp/networking/_requests.py", line 352, in _send
    raise TransportError(cause=e) from e
yt_dlp.networking.exceptions.TransportError: HTTPSConnectionPool(host='www.nbc.com', port=443): Read timed out. (read timeout=20.0)

**Comment by bashonly** [comment]
Some kind of network error. Maybe try using the actual user-agent of your browser instead of the one I gave

**Comment by AndyPeterman** [comment]
I tried with my user-agent and got new errors - do you want me to continue posting the entire debug dump here or is there a more direct way to get this to you?

**Comment by bashonly** [comment]
> do you want me to continue posting the entire debug dump here or is there a more direct way to get this to you?

I was just trying to suggest some workarounds that are effective for other MSOs/providers. None of them are effective for TWC, it seems. The adobepass extractor likely needs to be fixed for that MSO. I'm not able to work on this currently, but need to ask this in order to triage the issue: are you willing to share your account credentials with a developer if one is able/willing to work on this?

**Comment by AndyPeterman** [comment]
Sure, I could provide that.  Privately, of course.

**Comment by AndyPeterman** [comment]
I just tried the extraction again using the same command as before without any other changes (still using 2024.12.03) and this time it worked!  I was able to download the entire program.  I have no idea what's changed - perhaps something at NBC.

Thank you for your time and for providing a great program.

**Comment by bashonly** [comment]
Closing this for now then, can reopen if you or anyone else begins experiencing it again
