### ISSUE TITLE
Theater Complex TOWN is not working

### ISSUE THREAD

**Issue by shibage** [yt-dlp/yt-dlp#11718]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

Theater Complex TOWN is not working

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.theater-complex.town/en/live/79akNM7bJeD5Fi9EP39aDp', '--username', 'PRIVATE', 'and', '--password', 'PRIVATE']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (win_x86_exe)
[debug] Python 3.10.11 (CPython AMD64 32bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.theater-complex.town/en/live/79akNM7bJeD5Fi9EP39aDp
[generic] 79akNM7bJeD5Fi9EP39aDp: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 79akNM7bJeD5Fi9EP39aDp: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.theater-complex.town/en/live/79akNM7bJeD5Fi9EP39aDp
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1624, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1759, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.theater-complex.town/en/live/79akNM7bJeD5Fi9EP39aDp

[generic] Extracting URL: and
ERROR: [generic] 'and' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:and" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract
```

**Comment by bashonly** [comment]
If you're willing to share your account details, I could take a look into fixing this

Contact me via [discord](https://discord.gg/H5MNcFW63r) (username `bashonly`) or via email: `bashonly (a t) proton mail [do t ] com`

**Comment by bashonly** [comment]
Based on other similar extractors (`StacommuLiveIE` and `WrestleUniversePPVIE`), I think we need to do this:

```diff
diff --git a/yt_dlp/extractor/stacommu.py b/yt_dlp/extractor/stacommu.py
index d2f207fcc..830018518 100644
--- a/yt_dlp/extractor/stacommu.py
+++ b/yt_dlp/extractor/stacommu.py
@@ -207,7 +207,7 @@ def _real_extract(self, url):
 
 
 class TheaterComplexTownPPVIE(TheaterComplexTownBaseIE):
-    _VALID_URL = r'https?://(?:www\.)?theater-complex\.town/(?:(?:en|ja)/)?ppv/(?P<id>\w+)'
+    _VALID_URL = r'https?://(?:www\.)?theater-complex\.town/(?:(?:en|ja)/)?(?:ppv|live)/(?P<id>\w+)'
     IE_NAME = 'theatercomplextown:ppv'
     _TESTS = [{
         'url': 'https://www.theater-complex.town/ppv/wytW3X7khrjJBUpKuV3jen',
@@ -229,6 +229,9 @@ class TheaterComplexTownPPVIE(TheaterComplexTownBaseIE):
     }, {
         'url': 'https://www.theater-complex.town/ja/ppv/qwUVmLmGEiZ3ZW6it9uGys',
         'only_matching': True,
+    }, {
+        'url': 'https://www.theater-complex.town/en/live/79akNM7bJeD5Fi9EP39aDp',
+        'only_matching': True,
     }]
 
     _API_PATH = 'events'
```

But I can't be sure without testing

**Comment by bashonly** [comment]
If you want to test the above patch yourself, you can run:
```
yt-dlp --update-to bashonly/yt-dlp@theatercomplextown
```
