### ISSUE TITLE
Some Reddit videos fail to download

### ISSUE THREAD

**Issue by TestTimothy** [yt-dlp/yt-dlp#11722]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ireland

### Provide a description that is worded well enough to be understood

Most Reddit videos work fine, but some don't. At a quick glance, the commonality is that it's a GIF image which Reddit has converted to video themselves. This video actually was very easy to download in the browser, because it's a normal <video> tag with a normal src attribute, which seems to point directly to an MP4 file. I didn't try that initially, because yt-dlp usually works better for Reddit videos.

Note: The example I've got is NSFW. Sorry about that.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-Uv', 'https://www.reddit.com/r/gayporndaily/comments/137xou6/anyone_has_seen_this_recently_the_transition_is/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.11.232805 from yt-dlp/yt-dlp-nightly-builds [a9f85670d] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-48-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, certifi-2023.11.17, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.0.7
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.12.02.233010/SHA2-256SUMS
Current version: nightly@2024.11.11.232805 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.12.02.233010 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: 6540c6e222318a85a7f254e6871a0d473b00411aa4f2bb734565dae9be405c7e
Updating to nightly@2024.12.02.233010 from yt-dlp/yt-dlp-nightly-builds ...
[debug] Downloading yt-dlp from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.12.02.233010/yt-dlp
Updated yt-dlp to nightly@2024.12.02.233010 from yt-dlp/yt-dlp-nightly-builds
[debug] Restarting: python3 /usr/local/bin/yt-dlp -Uv https://www.reddit.com/r/gayporndaily/comments/137xou6/anyone_has_seen_this_recently_the_transition_is/
[debug] Command-line config: ['-Uv', 'https://www.reddit.com/r/gayporndaily/comments/137xou6/anyone_has_seen_this_recently_the_transition_is/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.12.02.233010 from yt-dlp/yt-dlp-nightly-builds [d8fb34908] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-48-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, certifi-2023.11.17, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.0.7
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.12.02.233010 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.12.02.233010 from yt-dlp/yt-dlp-nightly-builds)
[Reddit] Extracting URL: https://www.reddit.com/r/gayporndaily/comments/137xou6/anyone_has_seen_this_recently_the_transition_is/
[Reddit] 137xou6: Downloading JSON metadata
[generic] Extracting URL: https://i.redd.it/q7x461z6twxa1.gif
[generic] q7x461z6twxa1: Downloading webpage
[redirect] Following redirect to https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fq7x461z6twxa1.gif&rdt=33670
[generic] Extracting URL: https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fq7x461z6twxa1.gif&rdt=33670
[generic] media?url=https://i.redd.it/q7x461z6twxa1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] media?url=https://i.redd.it/q7x461z6twxa1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fq7x461z6twxa1.gif&rdt=33670
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1759, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2553, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fq7x461z6twxa1.gif&rdt=33670
```

**Comment by TestTimothy** [comment]
I should have checked the preview before posting.

I was trying to say that the video turned out to be easy to download in the browser, because it's a normal `<video>` tag with a normal `src` attribute pointing to an MP4 file, so the browser's context menu allows downloading. I didn't try that initially, because most Reddit videos are not like this, and `yt-dlp` is usually the easiest way to download them.

**Comment by EvilBoi123** [comment]
yup same

**Comment by diamondsw** [comment]
FYI, this is still an issue. I think it's more an issue of idiot redditors treating every animated thing as a "GIF" when it's clearly an MP4 video (you see this nigh constantly on https://www.reddit.com/r/HighQualityGifs/). Reddit then marks it as an image, browsers are lenient and play the video anyway, but yt-dlp stops with "what the hell is this GIF?". Not unreasonable given what the site is telling it, but it makes for an inconsistent user experience when some MP4 videos download and some don't.

More recent example: https://www.reddit.com/r/HighQualityGifs/comments/1ua539k/if_you_wanna_take_the_front_page_you_gotta_bet_big/

**Comment by L1Q** [comment]
I had the download say "Your IP address is unable to access the Reddit API".

after inspecting the script and finding it's trying to do a json dowload at ``https://www.reddit.com/{slug}/.json``:
```python
        try:
            data = self._download_json(
                f'https://www.reddit.com/{slug}/.json', video_id, expected_status=403)
        except ExtractorError as e:
            if isinstance(e.cause, json.JSONDecodeError):
                if self._is_logged_in:
                    raise ExtractorError('Your IP address is unable to access the Reddit API', expected=True)
                self.raise_login_required('Account authentication is required')
            raise
```
I composed the link myself and opened in the browser, same browser I used cookies from, and it totally opened and I could see the json with direct link to the video, viewable and downloadable directly in the browser.

Is yt-dlp doing something meaningfully different?

**Comment by bashonly** [comment]
@L1Q can you provide verbose output?

**Comment by L1Q** [comment]
> [@L1Q](https://github.com/L1Q) can you provide verbose output?

yes, of course, although I did not because I don't belive it particularly informative

```bash
$ yt-dlp -vU --cookies-from-browser chrome https://www.reddit.com/r/CalisthenicsCulture/comments/1uvt1by/6_months_muscleup_progress/
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', 'https://www.reddit.com/r/CalisthenicsCulture/comments/1uvt1by/6_months_muscleup_progress/']
[debug] User config "/home/l1q/.config/yt-dlp/config": ['--remote-components', 'ejs:github']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2026.07.04 from yt-dlp/yt-dlp [997fa1408]
[debug] Python 3.14.6 (CPython x86_64 64bit) - Linux-7.0.14-zen1-1-zen-x86_64-with-glibc2.43 (OpenSSL 3.6.3 9 Jun 2026, glibc 2.43)
[debug] exe versions: ffmpeg 8.1.2 (setts), ffprobe 8.1.2, rtmpdump 2.6
[debug] Optional libraries: brotli-1.2.0, certifi-2026.06.17, curl_cffi-0.15.0, pycrypto-3.23.0, requests-2.34.2, sqlite3-3.53.3, urllib3-2.7.0, yt_dlp_ejs-0.8.0
[debug] JS runtimes: deno-2.9.1
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "/home/l1q/.config/google-chrome/Default/Network/Cookies"
[Cookies] Loading cookie      0/  3824[debug] detected desktop environment: KDE6
[debug] Chosen keyring: KWALLET6
[debug] using kwallet-query to obtain password from KWALLET6
[debug] NetworkWallet = "kdewallet"
[debug] password found
Extracted 3289 cookies from chrome
[debug] cookie version breakdown: {'v10': 0, 'v11': 3824, 'other': 0, 'unencrypted': 0}
[debug] Request Handlers: urllib, requests, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1744 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2026.07.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2026.07.04 from yt-dlp/yt-dlp)
[Reddit] Extracting URL: https://www.reddit.com/r/CalisthenicsCulture/comments/1uvt1by/6_months_muscleup_progress/
[Reddit] 1uvt1by: Downloading JSON metadata
ERROR: [Reddit] 1uvt1by: Your IP address is unable to access the Reddit API
  File "/usr/lib/python3.14/site-packages/yt_dlp/extractor/common.py", line 765, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.14/site-packages/yt_dlp/extractor/reddit.py", line 312, in _real_extract
    raise ExtractorError('Your IP address is unable to access the Reddit API', expected=True)

```

the URL I could open in the browser was:
```https://www.reddit.com/1uvt1by/.json```
which redirects to 
```https://www.reddit.com/r/CalisthenicsCulture/comments/1uvt1by/6_months_muscleup_progress/.json```
and has this content:

[json.json](https://github.com/user-attachments/files/30007535/json.json)

notably, ```"fallback_url": "https://v.redd.it/gucidqt393dh1/CMAF_1080.mp4?source=fallback",```
totally downloadable

**Comment by bashonly** [comment]
@L1Q could you open a new issue please? Seems unrelated to the specific issue being reported in the OP.

**Comment by L1Q** [comment]
> [@L1Q](https://github.com/L1Q) could you open a new issue please? Seems unrelated to the specific issue being reported in the OP.

as I'm filing new issue an go through the checkboxes I realize it's working fine in the latest version. thank you for your time! 🙏
