### ISSUE TITLE
Error Opening File For Writing On Downloading TikTok Video

### ISSUE THREAD

**Issue by jwbats** [yt-dlp/yt-dlp#11775]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Provide a description that is worded well enough to be understood

Downloading a particular TikTok video isn't working. The file can't be opened for writing, even though the disk has plenty of space. Maybe it's something about the filename.

https://www.tiktok.com/@twomoosedesign/video/7392645857180405023

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS D:\Downloads\TikTok\twomoosedesign> yt-dlp -f bytevc1_720p_640807-1 -vU https://www.tiktok.com/@twomoosedesign/video/7392645857180405023
[debug] Command-line config: ['-f', 'bytevc1_720p_640807-1', '-vU', 'https://www.tiktok.com/@twomoosedesign/video/7392645857180405023']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.06 from yt-dlp/yt-dlp)
[TikTok] Extracting URL: https://www.tiktok.com/@twomoosedesign/video/7392645857180405023
[TikTok] 7392645857180405023: Downloading webpage
[debug] [TikTok] Found universal data for rehydration
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 7392645857180405023: Downloading 1 format(s): bytevc1_720p_640807-1
[debug] Invoking http downloader on "https://v19-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/oIzNFSPHDAh2gjlWAQFALuqDJf3waffEIICk7I/?a=1988&bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=1250&bt=625&cs=2&ds=3&ft=4fUEKMkQ8Zmo0Wfh6b4jVJuerpWrKsd.&mime_type=video_mp4&qs=14&rc=OWc6PDY8Mzg6aTw6aDVmaUBpM3JoeHU5cmx5dDMzaTczNEBjLS8yLzZgNi0xLzM1L14yYSMtbnBgMmRjNF9gLS1kMTJzcw%3D%3D&btag=e000b8000&expire=1733774151&l=2024120913552745171D151D244011E328&ply_type=2&policy=2&signature=625e3c2ded22b5eccbf4483e4c2d75c7&tk=tt_chain_token"
[download] Unable to open file: [Errno 22] Invalid argument: 'Bat Cat did accept my gift… but only once. I tried again when he was awake and moving around, and he was like, “Nahhh!” 😂 Now that I have my own Batman mask, I had to remix the old video. 😆 Wonder if one of the dogs will tolerate my nonsense ？  #cat #batman #3dprinting  [7392645857180405023].mp4.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Bat Cat did accept my gift… but only once. I tried again when he was awake and moving around, and he was like, “Nahhh!” 😂 Now that I have my own Batman mask, I had to remix the old video. 😆 Wonder if one of the dogs will tolerate my nonsense ？  #cat #batman #3dprinting  [7392645857180405023].mp4.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Bat Cat did accept my gift… but only once. I tried again when he was awake and moving around, and he was like, “Nahhh!” 😂 Now that I have my own Batman mask, I had to remix the old video. 😆 Wonder if one of the dogs will tolerate my nonsense ？  #cat #batman #3dprinting  [7392645857180405023].mp4.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: 'Bat Cat did accept my gift… but only once. I tried again when he was awake and moving around, and he was like, “Nahhh!” 😂 Now that I have my own Batman mask, I had to remix the old video. 😆 Wonder if one of the dogs will tolerate my nonsense？  #cat #batman #3dprinting  [7392645857180405023].mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 603, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 263, in download
  File "yt_dlp\downloader\common.py", line 241, in wrapper
  File "yt_dlp\utils\_utils.py", line 5251, in __iter__
  File "yt_dlp\downloader\common.py", line 234, in error_callback
  File "yt_dlp\utils\_utils.py", line 5259, in report_retry
  File "yt_dlp\downloader\common.py", line 243, in wrapper
  File "yt_dlp\downloader\common.py", line 254, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 606, in sanitize_open
OSError: [Errno 22] Invalid argument: 'Bat Cat did accept my gift… but only once. I tried again when he was awake and moving around, and he was like, “Nahhh!” 😂 Now that I have my own Batman mask, I had to remix the old video. 😆 Wonder if one of the dogs will tolerate my nonsense？  #cat #batman #3dprinting  [7392645857180405023].mp4.part'
```

**Comment by bashonly** [comment]
The default output filename is too long. Mitigate this with an output template that truncates the title, e.g. by adding `-o "%(title).100B [%(id)s].%(ext)s"` to your command
