### ISSUE TITLE
Animation Digital Network

### ISSUE THREAD

**Issue by AnimeHeaven** [yt-dlp/yt-dlp#11794]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

I have tried to download a video (https://animationdigitalnetwork.com/de/video/1233-loner-life-in-another-world) where it is in Japanese and have German subtitle. The Subtitles would be fine downloaded and mark in the metadata as German. But the audio is shown as ENGLISH, what is completely wrong. 
I have tried some different commands like: 

`Japanese: %(meta_language)s" --embed-metadata -f [language=jap]`
`japanese: %(meta_language)s" --embed-metadata -f [language=jap]`
`Japanese: %(meta_language)s" --embed-metadata -f [language=jpn]`

or

`Japanese: %(meta_language)s" --embed-metadata -f [language=jp]`

but nothing will write the audio metadata correct to japanese ,

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', 'japanese:', '%(meta_language)s --embed-metadata -f [language=jpn] --sub-langs de --write-subs --sub-format ssa -v -a C:\\Users\\Stefan\\Desktop\\adn.txt -o Z:\\Anime', 'Serien\\Loner', 'Life', 'in', 'Another', 'World\\Loner', 'Life', 'in', 'Another', 'WorldS%(season_number)02dE%(episode_number)02d.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: japanese:
[generic] japanese:: Downloading webpage
ERROR: Unable to handle request: Unsupported url scheme: "japanese" (requests, urllib, websockets, curl_cffi)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1624, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1759, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2393, in _real_extract
  File "yt_dlp\extractor\common.py", line 898, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4162, in urlopen
  File "yt_dlp\networking\common.py", line 130, in send
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: "japanese" (requests, urllib, websockets, curl_cffi)

[generic] Extracting URL: %(meta_language)s --embed-metadata -f [language=jpn] --sub-langs de --write-subs --sub-format ssa -v -a C:\Users\Stefan\Desktop\adn.txt -o Z:\Anime
ERROR: [generic] '%(meta_language)s --embed-metadata -f [language=jpn] --sub-langs de --write-subs --sub-format ssa -v -a C:\\Users\\Stefan\\Desktop\\adn.txt -o Z:\\Anime' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:%(meta_language)s --embed-metadata -f [language=jpn] --sub-langs de --write-subs --sub-format ssa -v -a C:\Users\Stefan\Desktop\adn.txt -o Z:\Anime" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract

[generic] Extracting URL: Serien\Loner
ERROR: [generic] 'Serien\\Loner' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:Serien\Loner" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract

[generic] Extracting URL: Life
ERROR: [generic] 'Life' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:Life" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract

[generic] Extracting URL: in
ERROR: [generic] 'in' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:in" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract

[generic] Extracting URL: Another
ERROR: [generic] 'Another' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:Another" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract

[generic] Extracting URL: World\Loner
ERROR: [generic] 'World\\Loner' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:World\Loner" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract

[generic] Extracting URL: Life
ERROR: [generic] 'Life' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:Life" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract

[generic] Extracting URL: in
ERROR: [generic] 'in' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:in" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract

[generic] Extracting URL: Another
ERROR: [generic] 'Another' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:Another" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract

[generic] Extracting URL: WorldS%(season_number)02dE%(episode_number)02d.%(ext)s
ERROR: [generic] 'WorldS%(season_number)02dE%(episode_number)02d.%(ext)s' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:WorldS%(season_number)02dE%(episode_number)02d.%(ext)s" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2361, in _real_extract
```

**Comment by october262** [comment]
does it work if you use yt-dlp -s jp  URL of video

**Comment by bashonly** [comment]
It looks like there's a quoting issue with your arguments

**Comment by AnimeHeaven** [comment]
> It looks like there's a quoting issue with your arguments

Nope it works well with german as language.

**Comment by AnimeHeaven** [comment]
> does it work if you use yt-dlp -s jp URL of video

No, it makes this error: ERROR: [generic] 'jp' is not a valid URL.

**Comment by bashonly** [comment]
Yeah because your quoting is wrong
