### ISSUE TITLE
[VK] add vkvideo.ru links to playlists

### ISSUE THREAD

**Issue by qzmtch** [yt-dlp/yt-dlp#11793]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

russia

### Example URLs

https://vkvideo.ru/playlist/-51890028_-2/video-51890028_456241268

### Provide a description that is worded well enough to be understood

We need to add links to playlists

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://vkvideo.ru/playlist/-51890028_-2/video-51890028_456241268
[debug] Command-line config: ['-vU', 'https://vkvideo.ru/playlist/-51890028_-2/video-51890028_456241268']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-116122-gd241edc2b4-20240703 (setts), ffprobe N-116122-gd241edc2b4-20240703, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://vkvideo.ru/playlist/-51890028_-2/video-51890028_456241268
[generic] video-51890028_456241268: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] video-51890028_456241268: Extracting information
[debug] Looking for embeds
[debug] Identified a Open Graph video info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] video_ext: Downloading 1 format(s): 0
ERROR: The extracted extension ('php') is unusual and will be skipped for safety reasons. If you believe this is an error, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 177, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3475, in process_info
  File "yt_dlp\YoutubeDL.py", line 3367, in existing_video_file
  File "yt_dlp\YoutubeDL.py", line 3366, in <lambda>
  File "yt_dlp\utils\_utils.py", line 2130, in _change_extension
  File "yt_dlp\utils\_utils.py", line 5212, in sanitize_extension
yt_dlp.utils._UnsafeExtensionError: unsafe file extension: 'php'
```

**Comment by Skyofflad** [comment]
Also, if you provide it with only the playlist link, the output slightly differs:
```
yt-dlp -vU https://vkvideo.ru/playlist/-38370503_-4
[debug] Command-line config: ['-vU', 'https://vkvideo.ru/playlist/-38370503_-4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-44-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2024.07.04, mutagen-1.47.0, pyxattr-0.7.2, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.37.2, urllib3-2.2.2, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://vkvideo.ru/playlist/-38370503_-4
[generic] -38370503_-4: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] -38370503_-4: Extracting information
[debug] Looking for embeds
[redirect] Following redirect to https://vkvideo.ru/badbrowser.php
[generic] Extracting URL: https://vkvideo.ru/badbrowser.php
[generic] badbrowser: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] badbrowser: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://vkvideo.ru/badbrowser.php
Traceback (most recent call last):
  File "/home/k/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1634, in wrapper
    return func(self, *args, **kwargs)
  File "/home/k/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1769, in __extract_info
    ie_result = ie.extract(url)
  File "/home/k/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/home/k/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2553, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vkvideo.ru/badbrowser.php
```

**Comment by qzmtch** [comment]
so they still haven't added support? you just need to remove part of the link from these links to get a link to the video
https://vkvideo.ru/**playlist/-51890028_-2/**video-51890028_456241268 does not download
https://vkvideo.ru/video-51890028_456241268 will download
https://vk.com/**playlist/-213802301_5/**video-213802301_456240543 does not download
https://vk.com/video-213802301_456240543 will download

**Comment by bashonly** [comment]
> so they still haven't added support?

You are welcome to open a PR instead of complaining about what "they" have or haven't done

**Comment by qzmtch** [comment]
> > so they still haven't added support?
> 
> You are welcome to open a PR instead of complaining about what "they" have or haven't done

No, I can't. Firstly, I'm not a programmer (I understand JavaScript a little, but definitely not Python). Secondly, I've never sent a PR and it would definitely be wrong.

**Comment by bashonly** [comment]
Then you'll have to be patient

**Comment by CodeWithMa** [comment]
Should it download the complete playlist or just the video?

**Comment by qzmtch** [comment]
No, this is not complete at all. https://github.com/yt-dlp/yt-dlp/pull/14376#issuecomment-3314925777

**Comment by seproDev** [comment]
Reopened to track `--no-playlist` support which was part of the original issue.
