### ISSUE TITLE
ERROR: Remote end closed connection without response

### ISSUE THREAD

**Issue by Botato300** [yt-dlp/yt-dlp#11800]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Argentina

### Provide a description that is worded well enough to be understood

When you try to download a video from this site, you get the error “Remote end closed connection without response”.
Command entered: `yt-dlp https://traducevideos.com/preview.mp4`

The method yt-dlp uses is the generic extractor (I guess), and it's rare that it doesn't work because **it's the direct link, and it can be played perfectly in an incognito tab**.
 **You can even download it with curl!** but with yt-dlp it fails.
Curl command: `curl -O preview.mp4 https://traducevideos.com/preview.mp4` and you will see that it downloads successfully.

So, I guess there is a problem with the generic yt-dlp extractor?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] Extracting URL: https://traducevideos.com/preview.mp4
[generic] preview: Downloading webpage
ERROR: [generic] Unable to download webpage: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) (caused by TransportError("('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"))
PS C:\Users\votati\Desktop> yt-dlp https://traducevideos.com/preview.mp4 --verbose
[debug] Command-line config: ['https://traducevideos.com/preview.mp4', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.12.12.232950 from yt-dlp/yt-dlp-nightly-builds [f6c73aad5] (pip)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0.1-full_build-www.gyan.dev (setts), ffprobe 7.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[generic] Extracting URL: https://traducevideos.com/preview.mp4
[generic] preview: Downloading webpage
ERROR: [generic] Unable to download webpage: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) (caused by TransportError("('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"))
  File "C:\Programacion\tools\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "C:\Programacion\tools\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 2393, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
  File "C:\Programacion\tools\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 911, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\Programacion\tools\Python310\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Programacion\tools\Python310\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Programacion\tools\Python310\lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "C:\Programacion\tools\Python310\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Programacion\tools\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Programacion\tools\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programacion\tools\Python310\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Programacion\tools\Python310\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Programacion\tools\Python310\lib\site-packages\urllib3\util\retry.py", line 449, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Programacion\tools\Python310\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Programacion\tools\Python310\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Programacion\tools\Python310\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Programacion\tools\Python310\lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "C:\Programacion\tools\Python310\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Programacion\tools\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Programacion\tools\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programacion\tools\Python310\lib\site-packages\yt_dlp\networking\_requests.py", line 328, in _send
    requests_res = session.request(
  File "C:\Programacion\tools\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Programacion\tools\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Programacion\tools\Python310\lib\site-packages\requests\adapters.py", line 682, in send                          raise ConnectionError(err, request=request)                                                                         requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))                                                                                                               
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Programacion\tools\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 898, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "C:\Programacion\tools\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 4162, in urlopen
    return self._request_director.send(req)
  File "C:\Programacion\tools\Python310\lib\site-packages\yt_dlp\networking\common.py", line 117, in send
    response = handler.send(request)
  File "C:\Programacion\tools\Python310\lib\site-packages\yt_dlp\networking\_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Programacion\tools\Python310\lib\site-packages\yt_dlp\networking\common.py", line 340, in send
    return self._send(request)
  File "C:\Programacion\tools\Python310\lib\site-packages\yt_dlp\networking\_requests.py", line 352, in _send
    raise TransportError(cause=e) from e
yt_dlp.networking.exceptions.TransportError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by grqz** [comment]
yt-dlp's ua is too old(the site only accepts chrome>=100, haven't not tested firefox/curl). You can pass `--user-agent "curl/8.7.1"` or something like `--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"` to yt-dlp

**Comment by Botato300** [comment]
> yt-dlp's ua is too old(the site only accepts chrome>=100, haven't not tested firefox/curl). You can pass `--user-agent "curl/8.7.1"` or something like `--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"` to yt-dlp

That was it! Thank you very much, problem solved :)
