### ISSUE TITLE
CSPAN video download, direct support or clearer error message

### ISSUE THREAD

**Issue by Utopiah** [yt-dlp/yt-dlp#11839]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Belgium

### Provide a description that is worded well enough to be understood

I tried to download via `yt-dlp https://www.c-span.org/program/book-tv/the-ai-mirror-how-to-reclaim-our-humanity-in-an-age-of-machine-thinking/645280 ` on latest today, namely `2024.12.13` but I got a `ERROR: Unsupported URL`

Yet, if I add a UA and referrer URL with the m3u8, e.g. `yt-dlp https://m3u8-0.c-spanvideo.org/program/program.645280.tsc.m3u8 --referer https://www.c-span.org/program/book-tv/the-ai-mirror-how-to-reclaim-our-humanity-in-an-age-of-machine-thinking/645280 --user-agent "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.117 Safari/537.36"` it does work.

I understand it might not be feasible, or appropriate to fake the UserAgent, as I didn't see anything related to `m3u8` from the source code of the page, to do so automatically but then I would suggest that the error message could help the user still get the content. I found the solution via https://gist.github.com/cemerson/57be14a554d2f94f243189867d11abd2 namely UA with referer URL.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
fabien@debian2080ti:~$ yt-dlp -vU https://www.c-span.org/program/book-tv/the-ai-mirror-how-to-reclaim-our-humanity-in-an-age-of-machine-thinking/645280 
[debug] Command-line config: ['-vU', 'https://www.c-span.org/program/book-tv/the-ai-mirror-how-to-reclaim-our-humanity-in-an-age-of-machine-thinking/645280']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-28-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.15 3 Sep 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: brotli-1.0.9, certifi-2022.09.24, pyxattr-0.8.1, requests-2.28.1, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.c-span.org/program/book-tv/the-ai-mirror-how-to-reclaim-our-humanity-in-an-age-of-machine-thinking/645280
[generic] 645280: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 645280: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.c-span.org/program/book-tv/the-ai-mirror-how-to-reclaim-our-humanity-in-an-age-of-machine-thinking/645280
Traceback (most recent call last):
  File "/home/fabien/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabien/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1759, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/fabien/bin/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabien/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2553, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.c-span.org/program/book-tv/the-ai-mirror-how-to-reclaim-our-humanity-in-an-age-of-machine-thinking/645280

fabien@debian2080ti:~$
```

**Comment by sallymanda** [comment]
@Utopiah thanks for the workaround :-)

I've found another method works as well, and is a little more straightforward. Just grab the embed URL from the C-SPAN page (click the embed icon next to the other social media share icons) and use that along with c-span.org as the referer:

`yt-dlp "https://cdn.jwplayer.com/players/rnTxys6z-xS4RtpB7.html" --referer "https://www.c-span.org/" --add-header "User-Agent:Mozilla/5.0"`

**Comment by cameronj86** [comment]
As an alternative, you can use ffmpeg if you're a daily/weekly listeners:
```service
[Unit]
Description=Script to run C-SPAN recording daily

[Service]
ExecStart=/bin/bash -c 'TMPFILE="/tmp/cspan_$(date +%%Y-%%m-%%d).opus" && OUTFILE="/path/to/folder/OpenForum_$(date +%%Y-%%m-%%d).opus" && ffmpeg -nostdin -i https://playerservices.streamtheworld.com/api/livestream-redirect/CSPANRADIO.mp3 -t 12600 -c:a libopus -b:a 64k "$TMPFILE" && mv "$TMPFILE" "$OUTFILE"'
```
Not shown, but I also have it set up to:
- Automatically place the file in my AudioBookShelf folder that has an RSS feed in it
- auto-delete files older than 4-5 days old
