### ISSUE TITLE
gem.cbc.ca suddenly throwing 'JSONDecodeError: Expecting value in '': line 1 column 1 (char 0'

### ISSUE THREAD

**Issue by dpo007** [yt-dlp/yt-dlp#11848]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

It normal works, but has stopped working. This include videos downloaded as recently as a few days ago (but they now no longer work).

It failing to parse the returned JSON:

json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://gem.cbc.ca/coronation-street/s01e11428']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[debug] Using fake IP 99.246.11.195 (CA) as X-Forwarded-For
[debug] Loading cbcgem.claims_token from cache
[gem.cbc.ca] Extracting URL: https://gem.cbc.ca/coronation-street/s01e11428
[gem.cbc.ca] coronation-street/s01e11428: Downloading JSON metadata
ERROR: [gem.cbc.ca] coronation-street/s01e11428: coronation-street/s01e11428: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\cbc.py", line 638, in _real_extract
  File "yt_dlp\extractor\common.py", line 1152, in download_content
  File "yt_dlp\extractor\common.py", line 1119, in download_handle
  File "yt_dlp\extractor\common.py", line 1107, in parse
  File "yt_dlp\extractor\common.py", line 1094, in _parse_json
  File "yt_dlp\extractor\common.py", line 1077, in __print_error

  File "yt_dlp\utils\_utils.py", line 565, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1091, in _parse_json
  File "json\__init__.py", line 359, in loads
  File "yt_dlp\utils\_utils.py", line 573, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by dirkf** [comment]
This is the same error that occurs when not logged in and/or not in Canada (regardless of geo-bypass). It should be detected.

What happens using logged-in browser cookies instead of `--username ... --password ... `?

Also, is XFF still a valid tactic for this site?

**Comment by bashonly** [comment]
Seems like the API we were using has finally been turned off. IIRC we had patched the extractor earlier this year to expect a status of `426` "Upgrade Required" from the API calls. Looks like the upgrade truly is required now.

**Comment by dirkf** [comment]
Indeed, 404 is its status. No similar API URLs (`.../v3/...`, say) came up in the scripts from the problem page.

<details><summary>Separately, for anyone updating the extractor module,</summary> test_CBC_4 (Keep Rover active...) now needs this patch (import `url_or_none` if needed) to find the playlist:
```diff
         entries.extend([
             self.url_result('cbcplayer:%s' % media_id, 'CBCPlayer', media_id)
             for media_id in orderedSet(media_ids)])
+        json_ld = next(self._yield_json_ld(webpage, display_id, fatal=False), {})
+        entries.extend(
+            self.url_result(video['contentUrl'], video_title=video.get('name'))
+            for video in traverse_obj(json_ld, ('video', lambda _, v: url_or_none(v.get('contentUrl'))))) 
         return self.playlist_result(
             entries, display_id, strip_or_none(title),
             self._og_search_description(webpage))

```

Does `_yield_json_ld()` need its `default` parameter that may have seemed like a good idea but doesn't actually do what it suggests?

</details>

**Comment by Ulmo** [comment]
I get this identical error on Twitter.

`latest-yt-dlp --ffmpeg-location /.../bin --embed-subs --embed-metadata --socket-timeout 5 -k --keep-fragments --sub-langs all --write-subs --write-comments --write-description --write-info-json --embed-info-json -o starship-catch-pin.scottsls.mp4 https://x.com/scottlikedsls/status/1873380039406031191
[twitter] Extracting URL: https://x.com/scottlikedsls/status/1873380039406031191
[twitter] 1873380039406031191: Downloading guest token
[twitter] 1873380039406031191: Downloading GraphQL JSON
ERROR: [twitter] 1873380039406031191: 1873380039406031191: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
`
Reattempted stripping all the flags except --ffmpeg-location and -o, it suddenly worked.

**Comment by RomainLG** [comment]
I'm willing to download from GEM CBC, but as long as this issue is not marked as resolved it is no point trying, right ?

**Comment by lordpengwin** [comment]
Any chance that this will be fixed? I have two seasons of Still Standing the I need to download.

**Comment by bashonly** [comment]
@lordpengwin Of course there is a chance. But a developer with access to an account and a Canadian IP will need to work on this, and nobody fitting that bill has stepped up yet

**Comment by lordpengwin** [comment]
> @lordpengwin Of course there is a chance. But a developer with access to an account and a Canadian IP will need to work on this, and nobody fitting that bill has stepped up yet

I would be happy to help by running experiments and returning results if someone tells me what to do.

**Comment by dirkf** [comment]
The original page is 404, but the page from #12121 is up.

From the UK, this block gets the trailer, which is playable without geo-restriction, subscription or DRM:
```py
        ...
        else:
            headers = {}

        # was: m3u8_info = self._download_json(video_info['playSession']['url'], video_id, headers=headers)
        media_id = traverse_obj(video_info, (
            'content', ..., 'lineups', ..., 'items',
            lambda _, v: v['url'] == video_id, 'idMedia'), get_all=False)
        m3u8_info_url = update_url_query(
            'https://services.radio-canada.ca/media/validation/v2/?appCode=gem&connectionType=hd&deviceType=ipad&multibitrate=true&output=json&tech=hls&manifestVersion=2&manifestType=desktop', {
                'idMedia': media_id,
        })
        m3u8_info = self._download_json(m3u8_info_url, video_id, headers=headers)

        if m3u8_info.get('errorCode') == 1:
        ...
```
An actual episode fails in the expected way, but perhaps would succeed for a logged-in CA user.

<details><summary>Results</summary>
<p>Testing in an old source branch with CBC extractor updated to current, so actually using `get_all=False` vs `any`.</p> 


```console
$ python3 -m yt_dlp -vF 'https://gem.cbc.ca/murdoch-mysteries/s18b01?autoplay=1'
[debug] Command-line config: ['-vF', 'https://gem.cbc.ca/murdoch-mysteries/s18b01?autoplay=1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: de4cf77ec
[debug] Python 3.11.2 (CPython i686 32bit) - Linux-6.1.0-30-686-pae-i686-with-glibc2.36 (OpenSSL 3.0.15 3 Sep 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2022.09.24, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1858 extractors
[debug] Using fake IP 99.235.251.83 (CA) as X-Forwarded-For
[gem.cbc.ca] Extracting URL: https://gem.cbc.ca/murdoch-mysteries/s18b01?autoplay=1
[gem.cbc.ca] murdoch-mysteries/s18b01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s18b01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s18b01: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for murdoch-mysteries/s18b01:
ID                  EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio_0-English mp4 audio only     │       m3u8  │ audio only        mp4a.40.2  [eng] English
hls-audio_1-English mp4 audio only     │       m3u8  │ audio only        mp4a.40.2  [eng] English
hls-audio_2-English mp4 audio only     │       m3u8  │ audio only        mp4a.40.2  [eng] English
hls-321             mp4 416x234     10 │  321k m3u8  │ avc1.42C00C  321k video only
hls-431             mp4 416x234     15 │  431k m3u8  │ avc1.42C00C  431k video only
hls-652             mp4 416x234     30 │  652k m3u8  │ avc1.42C00D  652k video only
hls-872             mp4 640x360     30 │  873k m3u8  │ avc1.42C01E  873k video only
hls-1312            mp4 640x360     30 │ 1313k m3u8  │ avc1.42C01E 1313k video only
hls-2190            mp4 960x540     30 │ 2191k m3u8  │ avc1.4D401F 2191k video only
hls-2961            mp4 1280x720    30 │ 2962k m3u8  │ avc1.4D401F 2962k video only
hls-3951            mp4 1280x720    30 │ 3952k m3u8  │ avc1.4D401F 3952k video only
hls-6809            mp4 1920x1080   30 │ 6809k m3u8  │ avc1.640028 6809k video only
$ # now try an actual episode
$ python3 -m yt_dlp -vF 'https://gem.cbc.ca/murdoch-mysteries/s18e01?autoplay=1'
[debug] Command-line config: ['-vF', 'https://gem.cbc.ca/murdoch-mysteries/s18e01?autoplay=1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: de4cf77ec
[debug] Python 3.11.2 (CPython i686 32bit) - Linux-6.1.0-30-686-pae-i686-with-glibc2.36 (OpenSSL 3.0.15 3 Sep 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2022.09.24, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1858 extractors
[debug] Using fake IP 99.241.163.206 (CA) as X-Forwarded-For
[gem.cbc.ca] Extracting URL: https://gem.cbc.ca/murdoch-mysteries/s18e01?autoplay=1
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading JSON metadata
ERROR: [gem.cbc.ca] murdoch-mysteries/s18e01: This video is only available for registered users. Use --username and --password, --netrc-cmd, or --netrc (cbcgem) to provide account credentials
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 709, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/cbc.py", line 672, in _real_extract
    self.raise_login_required(method='password')
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 1169, in raise_login_required
    raise ExtractorError(msg, expected=True)

$
```

</details> 

I wonder how the King of Canada is supposed to watch this.

**Comment by bashonly** [comment]
@dirkf the JSON parsing error happens with the first API call though, which your code block doesn't change. I can't repro your results at all; for all links I get "failed to parse JSON" for the first request. Why are you running a yt-dlp version from 1.5+ years ago? It's not conducive to collaboration

**Comment by dirkf** [comment]
I thought that the 1st API had been updated already, but it was a WIP on the travel laptop. Here's a full diff to master:
```diff
--- old/yt-dlp/yt_dlp/extractor/cbc.py
+++ new/yt-dlp/yt_dlp/extractor/cbc.py
@@ -21,6 +21,7 @@
     traverse_obj,
     try_get,
     update_url,
+    update_url_query,
     url_basename,
     url_or_none,
 )
@@ -636,8 +637,8 @@
     def _real_extract(self, url):
         video_id = self._match_id(url)
         video_info = self._download_json(
-            f'https://services.radio-canada.ca/ott/cbc-api/v2/assets/{video_id}',
-            video_id, expected_status=426)
+            f'https://services.radio-canada.ca/ott/catalog/v2/gem/show/{video_id}?device=web',
+            video_id)
 
         email, password = self._get_login_info()
         if email and password:
@@ -645,7 +646,15 @@
             headers = {'x-claims-token': claims_token}
         else:
             headers = {}
-        m3u8_info = self._download_json(video_info['playSession']['url'], video_id, headers=headers)
+
+        media_id = traverse_obj(video_info, (
+            'content', ..., 'lineups', ..., 'items',
+            lambda _, v: v['url'] == video_id, 'idMedia', any))
+        m3u8_info_url = update_url_query(
+            'https://services.radio-canada.ca/media/validation/v2/?appCode=gem&connectionType=hd&deviceType=ipad&multibitrate=true&output=json&tech=hls&manifestVersion=2&manifestType=desktop', {
+                'idMedia': media_id,
+        })
+        m3u8_info = self._download_json(m3u8_info_url, video_id, headers=headers)
 
         if m3u8_info.get('errorCode') == 1:
             self.raise_geo_restricted(countries=['CA'])
```
You can see these API URLs in the browser tools with the trailer page (gem.cbc.com and services.radio-canada.ca must be enabled for JS).

Instead of the catalog JSON, one could use the `.props.pageProps.data` member of the `__NEXT_DATA__` in the webpage, which also contains `.content` with the complete series data by season and episode in the same format ... until they switch to the new-style hydration data.

**Comment by dirkf** [comment]
Patch above doesn't address:
1. whether the login procedure with email and password generating the `claims_token` still works, and/or whether logged-in status is saved in browser cookies. 
2. the playlist extractor.

**Comment by OliveiraHermogenes** [comment]
Patch from [above](https://github.com/yt-dlp/yt-dlp/issues/11848#issuecomment-2664460209) applied and tested. It's working with a Canadian IP with and without `--cookies-from-browser`, at least with the following URL:

```
$ yt-dlp --verbose "https://gem.cbc.ca/daniel-tigers-neighbourhood/s01e11"
[debug] Command-line config: ['--verbose', 'https://gem.cbc.ca/daniel-tigers-neighbourhood/s01e11']
[debug] User config "/home/hermogenes/.config/yt-dlp/config": ['--embed-metadata', '--embed-thumbnail', '-o', '%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.01.26 from yt-dlp/yt-dlp [3b4531934] (debian*)
[debug] Python 3.13.2 (CPython x86_64 64bit) - Linux-6.12.13-amd64-x86_64-with-glibc2.40 (OpenSSL 3.4.1 11 Feb 2025, glibc 2.40)
[debug] exe versions: ffmpeg 7.1-3 (setts), ffprobe 7.1-3, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2025.01.31, mutagen-1.47.0, pyxattr-0.8.1, requests-2.32.3, sqlite3-3.46.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Using fake IP 99.247.186.128 (CA) as X-Forwarded-For
[gem.cbc.ca] Extracting URL: https://gem.cbc.ca/daniel-tigers-neighbourhood/s01e11
[gem.cbc.ca] daniel-tigers-neighbourhood/s01e11: Downloading JSON metadata
[gem.cbc.ca] daniel-tigers-neighbourhood/s01e11: Downloading JSON metadata
[gem.cbc.ca] daniel-tigers-neighbourhood/s01e11: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] daniel-tigers-neighbourhood/s01e11: Downloading 1 format(s): hls-6708+hls-audio_2-English
[info] There are no video thumbnails to download
[debug] Invoking hlsnative downloader on "https://cbcrcott-aws-gem.akamaized.net/hdntl=exp=1740009274~acl=%2f*~data=hdntl~hmac=db508e28fa38a5bfb67ed006f170fb75678c174a0514fff24b4c7651e5ab4e78/out/v1/22c30f04f5144add9b855f2f0064f095/026bf27581e640c4b4fb78ae5aaa5021/4992c413374a4be4af23a7b5453f28df/39578817cdc1485bba869c97adac23ce/6baf985d549245c48f39e42930e10a5e/index-aes_3.m3u8?aka_me_session_id=AAAAAAAAAAA6b7ZnAAAAAJS4RwTcA43tIvq%2f2EGGQ5rdUdeFUMGGW9v0ivJ2J8XBpmMIVrfBZ2dtZdddrbWOSCzQvlvJ%2fRTR&aka_media_format_type=hls&pckgrp=bf5b9c2800b7e86d48330ceb5add54a4"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 528
[download] Destination: Daniel Tiger's Neighbourhood.fhls-6708.mp4
```

OS: Debian unstable
Patch applied to version: 2025.01.26 (Debian package)

**Comment by bashonly** [comment]
@OliveiraHermogenes can you test if logging in still works or if that needs to be fixed as well? (I am going to merge dirkf's patch regardless, but would like to know if login support is a lingering problem)

**Comment by OliveiraHermogenes** [comment]
Well, it seems I didn't test this thoroughly enough. That was a kid's show, and I am able to get it even without logging in (without cookies or username/password). I was getting an error with that URL _before_ applying the patch, though. But even _after_ applying the patch, there are some URLs still failing 😕:

```
$ yt-dlp --verbose --cookies-from-browser firefox "https://gem.cbc.ca/allegiance/s02"
[debug] Command-line config: ['--verbose', '--cookies-from-browser', 'firefox', 'https://gem.cbc.ca/allegiance/s02']
[debug] User config "/home/hermogenes/.config/yt-dlp/config": ['--embed-metadata', '--embed-thumbnail', '-o', '%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.01.26 from yt-dlp/yt-dlp [3b4531934] (debian*)
[debug] Python 3.13.2 (CPython x86_64 64bit) - Linux-6.12.13-amd64-x86_64-with-glibc2.40 (OpenSSL 3.4.1 11 Feb 2025, glibc 2.40)
[debug] exe versions: ffmpeg 7.1-3 (setts), ffprobe 7.1-3, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2025.01.31, mutagen-1.47.0, pyxattr-0.8.1, requests-2.32.3, sqlite3-3.46.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/hermogenes/.mozilla/firefox/upxcqt6r.Padrão_2fd8f49f-5603-4b4a-b3e1-4d8c03a8127e/cookies.sqlite"
Extracted 1683 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[gem.cbc.ca:playlist] Extracting URL: https://gem.cbc.ca/allegiance/s02
[gem.cbc.ca:playlist] allegiance/s02: Downloading JSON metadata
ERROR: [gem.cbc.ca:playlist] allegiance/s02: allegiance/s02: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/cbc.py", line 728, in _real_extract
    show_info = self._download_json(self._API_BASE + show, season_id, expected_status=426)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1152, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1119, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
           ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1107, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1094, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1077, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/lib/python3/dist-packages/yt_dlp/utils/_utils.py", line 565, in decode
    return super().decode(s)
           ~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1091, in _parse_json
    return json.loads(
           ~~~~~~~~~~^
        json_string, cls=LenientJSONDecoder, strict=False, transform_source=transform_source, **parser_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/utils/_utils.py", line 573, in decode
    raise type(e)(f'{e.msg} in {s[e.pos - 10:e.pos + 10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by bashonly** [comment]
@OliveiraHermogenes the season/playlist extractor was not touched by that patch. Could you open a new issue about that please? You can include the same log you just posted. I am going to be closing this issue very soon by merging #12404

**Comment by bashonly** [comment]
> Also, is XFF still a valid tactic for this site?

It still works for US IPs

**Comment by bashonly** [comment]
@OliveiraHermogenes actually nevermind I've got it fixed in the same PR. The only thing that isn't being fixed is login support, which is almost certainly broken

**Comment by lordpengwin** [comment]
I can confirm that this does fix the problem but only when using --cookies-from-browser

**Comment by bashonly** [comment]
@lordpengwin broken login support is being tracked in #12406
