### ISSUE TITLE
Donwload facebook video

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [yt-dlp/yt-dlp#11841]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

spain

### Provide a description that is worded well enough to be understood

I cannot download a video from Facebook.
With other videos I have succeeded today.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] Extracting URL: https://fb.watch/wx6IVNMKpy/
[generic] wx6IVNMKpy: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/watch/?v=974159357849080&ref=sharing&share_url=https%3A%2F%2Ffb.watch%2Fwx6IVNMKpy%2F
[facebook] Extracting URL: https://www.facebook.com/watch/?v=974159357849080&ref=sharing&share_url=https%3A%2F%2Ffb.watch%2Fwx6IVNMKpy%2F
[facebook] 974159357849080: Downloading webpage
ERROR: [facebook] 974159357849080: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
❯ yt-dlp -U
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
❯ yt-dlp 'https://fb.watch/wx6IVNMKpy/'
[generic] Extracting URL: https://fb.watch/wx6IVNMKpy/
[generic] wx6IVNMKpy: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/watch/?v=974159357849080&ref=sharing&share_url=https%3A%2F%2Ffb.watch%2Fwx6IVNMKpy%2F
[facebook] Extracting URL: https://www.facebook.com/watch/?v=974159357849080&ref=sharing&share_url=https%3A%2F%2Ffb.watch%2Fwx6IVNMKpy%2F
[facebook] 974159357849080: Downloading webpage
ERROR: [facebook] 974159357849080: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
❯ yt-dlp -vU 'https://fb.watch/wx6IVNMKpy/'
[debug] Command-line config: ['-vU', 'https://fb.watch/wx6IVNMKpy/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962]
[debug] Python 3.12.7 (CPython x86_64 64bit) - Linux-6.12.4-2-cachyos-x86_64-with-glibc2.40 (OpenSSL 3.4.0 22 Oct 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.2, urllib3-1.26.20
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://fb.watch/wx6IVNMKpy/
[generic] wx6IVNMKpy: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/watch/?v=974159357849080&ref=sharing&share_url=https%3A%2F%2Ffb.watch%2Fwx6IVNMKpy%2F
[facebook] Extracting URL: https://www.facebook.com/watch/?v=974159357849080&ref=sharing&share_url=https%3A%2F%2Ffb.watch%2Fwx6IVNMKpy%2F
[facebook] 974159357849080: Downloading webpage
ERROR: [facebook] 974159357849080: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1780, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1839, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2846, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1121, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [facebook] 974159357849080: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by DavidPerezIngeniero** [comment]
I can see the video:
![image](https://github.com/user-attachments/assets/3ed07a55-1e2c-4665-8d49-cd70a04d9af0)

**Comment by kclauhk** [comment]
login required
To download the video, you have to pass cookies to yt-dlp. ( --cookies or --cookies-from-browser )

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

facebook will probably ban your account tho
