### ISSUE TITLE
site request

### ISSUE THREAD

**Issue by panwariojpg** [yt-dlp/yt-dlp#11875]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://prd.motilaloswal.com/edumo/videos/webinar/154

### Provide a description that is worded well enough to be understood

i want to download videos from the website called 360research(link is pasted above with the desired video that i want to download) the website is like you have to make an account pay a certain amount to access the course and watch it online only but i want to download it to i can refer later on and they(360research website doesnt have an download option) i have tried installing yt dlp and tried downloading using "yt-dlp https://prd.motilaloswal.com/edumo/videos/webinar/154" in the terminal and it shows it is an unsupported URL...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'yt-dlp', 'https://prd.motilaloswal.com/edumo/videos/webinar/154']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (pip)
[debug] Python 3.13.1 (CPython x86_64 64bit) - macOS-14.6.1-x86_64-i386-64bit-Mach-O (OpenSSL 3.4.0 22 Oct 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.2, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[CommonMistakes] Extracting URL: yt-dlp
ERROR: [CommonMistakes] You've asked yt-dlp to download the URL "yt-dlp". That doesn't make any sense. Simply remove the parameter in your command or configuration.
  File "/usr/local/Cellar/yt-dlp/2024.12.13/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2024.12.13/libexec/lib/python3.13/site-packages/yt_dlp/extractor/commonmistakes.py", line 25, in _real_extract
    raise ExtractorError(msg, expected=True)

[generic] Extracting URL: https://prd.motilaloswal.com/edumo/videos/webinar/154
[generic] 154: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 154: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://prd.motilaloswal.com/edumo/videos/webinar/154
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2024.12.13/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2024.12.13/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1759, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/2024.12.13/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2024.12.13/libexec/lib/python3.13/site-packages/yt_dlp/extractor/generic.py", line 2553, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://prd.motilaloswal.com/edumo/videos/webinar/154
```

**Comment by panwariojpg** [comment]
use this email " deepapanwar2002@gmail.com " to login you will be needing an OTP to login so i will share here as soon as i get one otp

**Comment by panwariojpg** [comment]
Hey bashonly, are there any updates there?

**Comment by pukkandan** [comment]
The `account-needed` label is just a hint for maintainers and any potential contributors that account is needed to work on the issue; and is not asking you to give account to the maintainer who added the label. If someone is interested in working on this and needs account details for that, they will let you know how to share it privately.

**Comment by panwariojpg** [comment]
Oh okay I see I got misleaded by myself... Sorry I don't know how GitHub works
