### ISSUE TITLE
[RFE] Support visir.is

### ISSUE THREAD

**Issue by africola** [yt-dlp/yt-dlp#11901]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Germany

### Example URLs

- Single video: https://www.visir.is/k/3bb38186-f16d-481f-8608-4c404aab0455-1727694046807/briet-x-birnir-1000-ord

### Provide a description that is worded well enough to be understood

Just what it says on the tin. Visir.is is apparently not currently supported, and the generic fallback does not work. Would appreciate it if support was added. Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.visir.is/k/3bb38186-f16d-481f-8608-4c404aab0455-1727694046807/briet-x-birnir-1000-ord']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-107213-gfed07efcde-20220622 (setts), ffprobe N-107213-gfed07efcde-20220622
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.visir.is/k/3bb38186-f16d-481f-8608-4c404aab0455-1727694046807/briet-x-birnir-1000-ord
[generic] briet-x-birnir-1000-ord: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] briet-x-birnir-1000-ord: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.visir.is/k/3bb38186-f16d-481f-8608-4c404aab0455-1727694046807/briet-x-birnir-1000-ord
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1634, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1769, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.visir.is/k/3bb38186-f16d-481f-8608-4c404aab0455-1727694046807/briet-x-birnir-1000-ord
```

**Comment by error-reporting** [comment]
does the video play with drm in browser disabled

**Comment by dirkf** [comment]
Probably. There is this element in the problem page:
```html
 <script>
        function startPlayer() {
            App.Player.Init({
                Element: 'video-media-player',
                Type: 'video',
                Image: 'https://www.visir.is/mi/880x478/3bb38186-f16d-481f-8608-4c404aab0455/thumbs-1727694046807-00001-c1.5m.png',
                File: '/hls/3bb38186-f16d-481f-8608-4c404aab0455/3bb38186-f16d-481f-8608-4c404aab0455-1727694046807.m3u8',
                Categoryid: 225,
                Subcategoryid: '',
                FileId: '3bb38186-f16d-481f-8608-4c404aab0455-1727694046807',
                Host: 'vod.visir.is',
                SourceVariable: 225,
                Embed: true, AutoStart: true,
                Title: `Bríet x Birnir - 1000 orð`,
                Mediaid: '',
                Channelid: 'VISIR',
                Categoryname: 'tonlist',
                Tags: '',
            })
        }

        ...
    </script>
```
The manifest URL constructed in the obvious way from `Host` and `File` plays in _mpv_ from the UK.

**Comment by africola** [comment]
Hello, and thank you kindly for looking into this RFE.

@error-reporting @dirkf Yes, I can confirm the video plays (in Firefox) with DRM disabled.

**Comment by error-reporting** [comment]
is this website a piracy ones

**Comment by dirkf** [comment]
According to [WP](https://en.wikipedia.org/wiki/V%C3%ADsir.is):
>Vísir.is is an Icelandic online newspaper. ...
>
>According to Gallup, it was the second-most popular website in Iceland as of February 2021.

**Comment by africola** [comment]
Hi, and thanks again. @error-reporting No, of course it is not; this is a news website, and it's no more connected to hijacking ships, robbing their cargo or killing their crew than, say, NBC's website is. And if you're talking about copyright infringement... then no, it's not for that either. :P

**Comment by andri** [comment]
+1

**Comment by africola** [comment]
I just wanted to say thank you VERY much to everyone involved for adding support for this site. Much appreciated!
