### ISSUE TITLE
ytboob.com

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#11906]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

-Single video - https://ytboob.com/full-nude-3/

### Provide a description that is worded well enough to be understood

mp4 is hosted on vidhost.me, and is easily curled.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] yt-dlp version nightly@2024.12.23.232812 from yt-dlp/yt-dlp-nightly-builds [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0-full_build-www.gyan.dev (setts), ffprobe 7.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: AGB (YoutubeIE), Youtube_AgeGateBypassIE
[debug] Loaded 1838 extractors
[generic] Extracting URL: https://ytboob.com/full-nude-3/
[generic] full-nude-3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] full-nude-3: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://ytboob.com/full-nude-3/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1634, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1769, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://ytboob.com/full-nude-3/
```

**Comment by dirkf** [comment]
The HTML5 video in the single video page is found by the upstream Generic extractor but not by the re-factored HTML5 extractor here.

**Comment by bashonly** [comment]
is this site just reposted content from youtube/other video sharing sites?

**Comment by barkoder** [comment]
@bashonly Yes. It is intended as a "mirror" of NSFW videos that are either removed from YT, or almost certainly going to be removed from YT due to the obvious ToS violation. See r/bannedyoutube , r/ytnsfw and some other subreddits to find the u/ytboob bot that's automating this.
