### ISSUE TITLE
UnsupportedError is not an UnsupportedError, ExtractorError is not an ExtractorError

### ISSUE THREAD

**Issue by dark-penguin** [yt-dlp/yt-dlp#11929]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi!
I might be missing something, but I've tried to look around, and I can't find anything about this.
I'm embedding yt-dlp in my script (so this is about the API, not commandline).
No matter how I try, an `UnsupportedError` is not an `UnsupportedError`, and not even a subclass of a `DownloadError` - it is only a `DownloadError` itself.
Here, I'm trying to download a link that is obviously not a video to cause that error:
```python
try:
    with YoutubeDL(dict(options, outtmpl=filename)) as ydl:
        info = ydl.sanitize_info(ydl.extract_info(url, download=True))
except utils.DownloadError as error:
    print(f"\nCaught an '{error}'")
    print(f"It is a '{error.exc_info[0]}'")
    print(f"But is it an UnsupportedError? - {isinstance(error, utils.UnsupportedError)}")
    print(f"Is it a DownloadError then? - {isinstance(error, utils.DownloadError)}")
    continue
```
```
[generic] Extracting URL: http://www.debian.org
[generic] www.debian: Downloading webpage
[redirect] Following redirect to https://www.debian.org/
[generic] Extracting URL: https://www.debian.org/
[generic] www.debian: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] www.debian: Extracting information

Caught an 'ERROR: Unsupported URL: https://www.debian.org/'
It is a '<class 'yt_dlp.utils.UnsupportedError'>'
But is it an UnsupportedError? - False
Is it a DownloadError then? - True
ERROR: Unsupported URL: https://www.debian.org/
```
What gives? Am I dumb and don't understand exceptions' inheritance, or is this really strange?
Because of this, I can't catch an `UnsupportedError` and handle it separately from any other `DownloadError`, because it is literally the same thing. Well, of course I could analyze its `error.exc_info[0]`, but this is not what I am supposed to do, is it?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (pip) API
[debug] params: {'format_sort': ['codec:h265:h264:h263'], 'max_filesize': 52428800, 'subtitleslangs': ['en'], 'writesubtitles': True, 'verbose': True, 'paths': {'temp': '/tmp/ytdlp-bot-downloading', 'home': '/tmp/ytdlp-bot-done'}, 'concurrent_fragment_downloads': 10, 'postprocessors': [{'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': False}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_infojson': False, 'add_metadata': False}], 'retries': 10, 'fragment_retries': 10, 'format': 'best[width>5000][height>5000]', 'outtmpl': '2024-12-28_04:36:17.%(ext)s', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.9.7-1-liquorix-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.15 3 Sep 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: certifi-2024.12.14, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[generic] Extracting URL: http://www.debian.org
[generic] www.debian: Downloading webpage
[redirect] Following redirect to https://www.debian.org/
[generic] Extracting URL: https://www.debian.org/
[generic] www.debian: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[debug] Looking for embeds
[generic] www.debian: Extracting information
ERROR: Unsupported URL: https://www.debian.org/
Traceback (most recent call last):
  File "/home/kami/python/ytdlp-telebot/.venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1634, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kami/python/ytdlp-telebot/.venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1769, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/kami/python/ytdlp-telebot/.venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kami/python/ytdlp-telebot/.venv/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2553, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.debian.org/


Caught an 'ERROR: Unsupported URL: https://www.debian.org/'
It is a '<class 'yt_dlp.utils.UnsupportedError'>'
But is it an UnsupportedError? - False
Is it a DownloadError then? - True
```

**Comment by dark-penguin** [comment]
The same goes for an ExtractorError, I just checked it the same way. So I assume it's true for all subclasses of a DownloadError...

**Comment by Grub4K** [comment]
Look at `YoutubeDL.trouble`. Errors that happen will get re-raised in that function as a `DownloadError`, wrapping the original error. Checking that error will always yield a `DownloadError`, yet other errors might be contained inside.

The checking logic is also sound, and can be explained. Since its a `DownloadError`, it `isinstance(error, DownloadError)`, and not a `UnsupportedError`. You would have to check the "unwrapped" error, so `isinstance(error.exc_info[0], UnsupportedError)` (which would also `not isinstance(error.exc_info[0], DownloadError)`.

**Comment by dark-penguin** [comment]
So I can not check them "normally"
```
try:
    ...
except UnsupportedError:
    ...
except ExtractorError:
    ...
except DownloadError:
    ...(all the other cases)
```
but I can still do it kinda okay-looking:
```
try:
    ...
except DownloadError as error:
    if isinstance(error.exc_info[0], UnsupportedError):
        ...
    elif isinstance(error.exc_info[0], ExtractorError):
        ...
    else:  # General DownloadError - all the other cases
        ...
```
This does not work either:
```
try:
    with YoutubeDL(dict(options, outtmpl=filename)) as ydl:
        info = ydl.sanitize_info(ydl.extract_info(url, download=True))
except utils.DownloadError as error:
    print(f"\nCaught an '{error}'")
    print(f"It is a '{error.exc_info[0]}'")
    print(f"But is it an UnsupportedError? - {isinstance(error.exc_info[0], utils.UnsupportedError)}")
    print(f"Is it a DownloadError then? - {isinstance(error.exc_info[0], utils.DownloadError)}")
    continue
```
```
[generic] Extracting URL: http://www.debian.org
[generic] www.debian: Downloading webpage
[redirect] Following redirect to https://www.debian.org/
[generic] Extracting URL: https://www.debian.org/
[generic] www.debian: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] www.debian: Extracting information

Caught an 'ERROR: Unsupported URL: https://www.debian.org/'
It is a '<class 'yt_dlp.utils.UnsupportedError'>'
But is it an UnsupportedError? - False
Is it a DownloadError then? - False
ERROR: Unsupported URL: https://www.debian.org/
```

**Comment by Grub4K** [comment]
Oh yes, my bad, its `exc_info[1]`. God knows why `type(e)` is the first one

**Comment by dark-penguin** [comment]
So... looks like `UnsupportedError` is a subclass of `ExtractorError`. I guess this is intended. And somehow they are both not DownloadError:
```
[generic] Extracting URL: http://www.debian.org
[generic] www.debian: Downloading webpage
[redirect] Following redirect to https://www.debian.org/
[generic] Extracting URL: https://www.debian.org/
[generic] www.debian: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] www.debian: Extracting information
ERROR: Unsupported URL: https://www.debian.org/

Caught an 'ERROR: Unsupported URL: https://www.debian.org/'
It is a '<class 'yt_dlp.utils.UnsupportedError'>'
Is it an UnsupportedError? - True
Is it an ExtractorError? - True
Is it a DownloadError then? - False
[youtube] Extracting URL: https://youtube.com/shorts/NVsFfHLxexM?si=RKFm5cBAsv7QJ8IX
[youtube] NVsFfHLxexM: Downloading webpage
[youtube] NVsFfHLxexM: Downloading ios player API JSON
[youtube] NVsFfHLxexM: Downloading mweb player API JSON
[youtube] NVsFfHLxexM: Downloading m3u8 information
ERROR: [youtube] NVsFfHLxexM: Requested format is not available. Use --list-formats for a list of available formats

Caught an 'ERROR: [youtube] NVsFfHLxexM: Requested format is not available. Use --list-formats for a list of available formats'
It is a '<class 'yt_dlp.utils.ExtractorError'>'
Is it an UnsupportedError? - False
Is it an ExtractorError? - True
Is it a DownloadError then? - False
```

**Comment by Grub4K** [comment]
Whats the problem here? The type inheritance still checks out...

If `type(error) is ExtractorError` then you can use `error.cause` to determine the source. Please just take some time to familiarize yourself with the error classes through the source

**Comment by dark-penguin** [comment]
Thanks! I'm too scared to "learn by sourcing" in this case, but I understand this now. Maybe I really should try it. :slightly_smiling_face:
