### ISSUE TITLE
[twitter] Intermittent "Failed to parse JSON" errors

### ISSUE THREAD

**Issue by NoneToRoot** [yt-dlp/yt-dlp#11937]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

SA

### Provide a description that is worded well enough to be understood

I have updates yt-dlp to the last version
When i try to download a twitter video i found this error (it is the first time i encounter it)
What is the issue ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: [twitter] 1873063443525501019: 1873063443525501019: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
That is not complete verbose output. Share the full log or else this issue will be closed

Also please confirm this:

> - [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details

**Comment by Idrss1** [comment]
> That is not complete verbose output. Share the full log or else this issue will be closed
> 
> 
> 
> Also please confirm this:
> 
> 
> 
> > - [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details

ERROR: [twitter] 1873063443525501019: 1873063443525501019: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

ERROR: [twitter] 1873063443525501019: 1873063443525501019: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U


This is all the verbose, also i can confirm the url is playable in the browser, and when i return back to the second last version of yt-dlp it has worked without any issues

**Comment by bashonly** [comment]
Share the FULL log and I might reopen the issue

**Comment by 2011** [comment]
Please reopen.

I have started to encounter this propblem a few days ago (where Twitter INTERMITTANTLY fails). When that happens, I just retry (up arrow and return) until it works (usually takes two to four attemps).

The logs of both a failed and successful attempt (less than five seconds later) of the same video. In this case, the attempted download failed three times before succeeding.

```
$ yt-dlp -f b -v 'https://twitter.com/libsoftiktok/status/1871946034336989342'
[debug] Command-line config: ['--restrict-filenames', '-o', '%(title).192s-%(id)s-%(uploader)s.%(ext)s', '-w', '-f', 'b', '-v', 'https://twitter.com/libsoftiktok/status/1871946034336989342']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd]
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.1.53-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.20.0, requests-2.32.3, urllib3-2.2.2
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[twitter] Extracting URL: https://twitter.com/libsoftiktok/status/1871946034336989342
[twitter] 1871946034336989342: Downloading guest token
[twitter] 1871946034336989342: Downloading GraphQL JSON
ERROR: [twitter] 1871946034336989342: 1871946034336989342: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/twitter.py", line 1422, in _real_extract
    status = self._extract_status(twid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/twitter.py", line 1400, in _extract_status
    status = self._graphql_to_legacy(self._call_graphql_api(self._GRAPHQL_ENDPOINT, twid), twid)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/twitter.py", line 331, in _call_graphql_api
    return traverse_obj(self._call_api(endpoint, media_id, query=query, graphql=True), 'data')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/twitter.py", line 312, in _call_api
    result = self._download_json(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1152, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1119, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1107, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1094, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1077, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 565, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1091, in _parse_json
    return json.loads(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 573, in decode
    raise type(e)(f'{e.msg} in {s[e.pos - 10:e.pos + 10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)


$ yt-dlp -f b -v 'https://twitter.com/libsoftiktok/status/1871946034336989342'
[debug] Command-line config: ['--restrict-filenames', '-o', '%(title).192s-%(id)s-%(uploader)s.%(ext)s', '-w', '-f', 'b', '-v', 'https://twitter.com/libsoftiktok/status/1871946034336989342']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd]
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.1.53-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.20.0, requests-2.32.3, urllib3-2.2.2
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[twitter] Extracting URL: https://twitter.com/libsoftiktok/status/1871946034336989342
[twitter] 1871946034336989342: Downloading guest token
[twitter] 1871946034336989342: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1871873052167815168
[twitter] 1871946034336989342: Downloading m3u8 information
[debug] Sort order given by extractor: res, proto:m3u8, br, size
[debug] Formats sorted by: hasvid, ie_pref, res, proto:m3u8(8), br, size, lang, quality, fps, hdr:12(7), vcodec, channels, acodec, asr, vext, aext, hasaud, source, id
[info] 1871873052167815168: Downloading 1 format(s): http-10368
[debug] Invoking http downloader on "https://video.twimg.com/amplify_video/1871873052167815168/vid/avc1/1080x1112/q2PecuvGbiKFqXCi.mp4?tag=16"
[download] Destination: Libs_of_TikTok_-_I_bet_this_couple_wishes_Daniel_Penny_was_there-1871873052167815168-Libs_of_TikTok.mp4
[download] 100% of    4.17MiB in 00:00:00 at 15.22MiB/s
```

**Comment by 2011** [comment]
@bashonly Did you see my reply?

**Comment by bashonly** [comment]
Catching up now. I'll reopen this, but I still can't reproduce the issue on my end

**Comment by DTrombett** [comment]
Maybe the request can be automatically retried if it fails since it seems just an intermittent error?

**Comment by dickychenghk** [comment]
Seems it will trigger when you continues download video from twitter (X) in short period of time. My current solution is just wait for server ban "timeout".

**Comment by exd02** [comment]
@Idrss1 
Just add the option `--cookies-from-browser`
I was getting the same error. If you want to download twitter videos you need to be logged.

@bashonly maybe yt-dlp should check the cookies before trying to download, idk...

Without `--cookies-from-browser`:
```
C:\Users\zzz\Videos>yt-dlp.exe https://x.com/i/status/[HIDDEN]
[twitter] Extracting URL: https://x.com/i/status/[HIDDEN]
[twitter] [HIDDEN]: Downloading guest token
[twitter] [HIDDEN]: Downloading GraphQL JSON
ERROR: [twitter] [HIDDEN]: [HIDDEN]: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
With `--cookies-from-browser`:
```
C:\Users\zzz\Videos>yt-dlp.exe --cookies-from-browser firefox https://x.com/i/status/[HIDDEN]
[twitter] Extracting URL: https://x.com/i/status/[HIDDEN]
Extracting cookies from firefox
Extracted 356 cookies from firefox
[twitter] [HIDDEN]: Downloading GraphQL JSON
[twitter] [HIDDEN]: Downloading m3u8 information
WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
[info] [HIDDEN]: Downloading 1 format(s): http-2176
[download] Destination: [HIDDEN].mp4
[download] 100% of    2.41MiB in 00:00:00 at 9.40MiB/s
```

**Comment by bashonly** [comment]
I still can only repro this in about 1 out of every 100 times I try

**Comment by bashonly** [comment]
Someone who is frequently experiencing this issue could also try `--extractor-arg "twitter:api=syndication"` **instead** of passing cookies. (Make sure you're on the latest version, 2025.02.19 or newer)

**Comment by exd02** [comment]
> Does that require a Twitter / X account (I don't have one)?
Yes, you need to be logged in into the browser that you'll get the cookies from. That worked for me...

**Comment by bashonly** [comment]
If you can't / don't want to pass cookies...

> Someone who is frequently experiencing this issue could also try `--extractor-arg "twitter:api=syndication"` **instead** of passing cookies. (Make sure you're on the latest version, 2025.02.19 or newer)

it would be nice if someone could test that

**Comment by 2011** [comment]
> > Someone who is frequently experiencing this issue could also try `--extractor-arg "twitter:api=syndication"` **instead** of passing cookies. (Make sure you're on the latest version, 2025.02.19 or newer)
> 
> it would be nice if someone could test that

I have added that to my alias, and will report on whether or not that helps in a couple of days.

**Comment by 2011** [comment]
Not off to a good start:

```
$ yt-dlp -f b -v 'https://x.com/TheFigen_/status/1896538948991865214'
[debug] Command-line config: ['--extractor-arg', 'twitter:api=syndication', '--restrict-filenames', '-o', '%(title).192s-%(id)s-%(uploader)s.%(ext)s', '-w', '-f', 'b', '-v', 'https://x.com/TheFigen_/status/1896538948991865214']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.02.19 from yt-dlp/yt-dlp (linux_exe)
[debug] Python 3.11.11 (CPython x86_64 64bit) - Linux-4.4.221-gentoo-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz-with (OpenSSL 3.1.8 11 Feb 2025)
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2025.01.31, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.3.0, websockets-15.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1841 extractors
[twitter] Extracting URL: https://x.com/TheFigen_/status/1896538948991865214
WARNING: [twitter] 1896538948991865214: Not all metadata or media is available via syndication endpoint
ERROR: module 'math' has no attribute 'PI'
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1637, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1772, in __extract_info
  File "yt_dlp/extractor/common.py", line 746, in extract
  File "yt_dlp/extractor/twitter.py", line 1388, in _real_extract
  File "yt_dlp/extractor/twitter.py", line 1382, in _extract_status
  File "yt_dlp/extractor/twitter.py", line 1346, in _call_syndication_api
  File "yt_dlp/extractor/twitter.py", line 1337, in _generate_syndication_token
AttributeError: module 'math' has no attribute 'PI'
```

**Comment by bashonly** [comment]
@2011 oops, bug in the extractor. Update to master and try again (`yt-dlp --update-to master`)

**Comment by 2011** [comment]
Have used the "twitter:api=syndication" option for most of the day (at least a couple of dozen videos) without any problems.

Can you elaborate on the "Not all metadata or media is available via syndication endpoint" warning? It doesn't seem relevant (at least to me), but I wonder if I have missed something.

**Comment by bashonly** [comment]
> Can you elaborate on the "Not all metadata or media is available via syndication endpoint" warning? It doesn't seem relevant (at least to me), but I wonder if I have missed something.

@2011 From the syndication API you can't get:
- `*_count` metadata (e.g. `repost_count` etc)
- age-restricted tweets/videos
- multi-video tweets (only 1 video is returned)

**Comment by epremuz** [comment]
> Let me know if this fixes for you guys. 😙

I thought of trying this after about 30 failures with the release version but before trying to change the line you suggested I tried cloning the repository and it worked fine at the first try with the cloned version as-is
Either I had incredible luck or there's something different enough between both versions.

I'm gonna keep tracking this error as I've been hit by it every single time I tried downloading something from Twitter/X

**Comment by glektarssza** [comment]
Been hit by this today. Looks like it's CloudFlare? The output of the request, with cookies, is base64 encoded when I run with `--dump-pages`. As it should be.

Decoding it yields this:

<img width="1941" height="767" alt="Image" src="https://github.com/user-attachments/assets/ebc6f5f1-114f-42c8-9950-1cb4c47cf309" />

So basically X is just being a massive arse. What's new there? If I try to access the endpoint manually I just get 403'd.

<img width="813" height="629" alt="Image" src="https://github.com/user-attachments/assets/4f809282-f720-42c7-8086-f26f8f29164f" />

Edit: spelling.
