### ISSUE TITLE
[Broken] funimation video download

### ISSUE THREAD

**Issue by federicorosso1993** [yt-dlp/yt-dlp#1195]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
.\yt-dlp.exe "https://www.funimation.com/v/magia-record-puella-magi-madoka-magica-side-story/special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid=" 
[generic] special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid=: Requesting header 
WARNING: [generic] Falling back on generic information extractor. 
[generic] special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid=: Downloading webpage 
[generic] special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid=: Extracting information 
ERROR: [generic] Unsupported URL: https://www.funimation.com/v/magia-record-puella-magi-madoka-magica-side-story/special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid= 
PS C:\Users\liefl\Documents\mini-browser-config-2> .\yt-dlp.exe "https://www.funimation.com/v/magia-record-puella-magi-madoka-magica-side-story/special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid=" -v 
[debug] Command-line config: ['https://www.funimation.com/v/magia-record-puella-magi-madoka-magica-side-story/special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid=', '-v'] 
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252 
[debug] yt-dlp version 2021.09.25 (exe) 
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0 
[debug] exe versions: ffmpeg git-2020-08-02-b48397e, ffprobe git-2020-08-02-b48397e, rtmpdump 2.3 
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets 
[debug] Proxy map: {} 
[debug] [generic] Extracting URL: https://www.funimation.com/v/magia-record-puella-magi-madoka-magica-side-story/special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid= 
[generic] special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid=: Requesting header 
WARNING: [generic] Falling back on generic information extractor. 
[generic] special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid=: Downloading webpage 
[generic] special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid=: Extracting information 
ERROR: [generic] Unsupported URL: https://www.funimation.com/v/magia-record-puella-magi-madoka-magica-side-story/special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid= 
Traceback (most recent call last): 
  File "yt_dlp\extractor\common.py", line 585, in extract 
  File "yt_dlp\extractor\generic.py", line 3712, in _real_extract 
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.funimation.com/v/magia-record-puella-magi-madoka-magica-side-story/special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid= 
Traceback (most recent call last): 
  File "yt_dlp\extractor\common.py", line 585, in extract 
  File "yt_dlp\extractor\generic.py", line 3712, in _real_extract 
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.funimation.com/v/magia-record-puella-magi-madoka-magica-side-story/special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid= 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "yt_dlp\YoutubeDL.py", line 1227, in wrapper 
  File "yt_dlp\YoutubeDL.py", line 1252, in __extract_info 
  File "yt_dlp\extractor\common.py", line 601, in extract 
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.funimation.com/v/magia-record-puella-magi-madoka-magica-side-story/special-episode-b999ec00-1cbf-11ec-9217-0242ac110002?lang=&a=1&qid=

```

## Description

I actually know how to download from funimation without yt-dlp (just go to the link in browser dev mode and you will see the response stream) and it did not change. I think the main problem here is that they changed the way it generate the link (the player changed too, now it is full screen only (or better it fill the browser page), before it was more youtube - like).
It should be an easy fix but (like I said in the site support ticket for crunchyroll beta) I don't know how to program in python.

Funimation is us only (at least for what I know), I used a VPN to access the episode. 
It was working until 2 days ago.

**Comment by Jules-A** [comment]
> Sorry I didn't notice since the first issues is old and it was for a different reason
Next time sort by issues by date modified or search by extractor name. The reason the download isn't working is exactly the same. I submitted a draft PR if you want to try it: https://github.com/yt-dlp/yt-dlp/pull/1196
