### ISSUE TITLE
ERROR: Unable to download video: [Errno 30] Read-only file system: 'output.json'

### ISSUE THREAD

**Issue by fadone** [yt-dlp/yt-dlp#11954]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

```
ydl_opts = {  "proxy": "http://username:password@address:port", 'progress_hooks': [hook], 'overwrites': True, "paths": { "temp": "/tmp/", "home": "/tmp/" }, "verbose": True }
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
  res = ydl.download([URL])
```

I am running on lambda and trying to change the temporary files dir but `output.json` is still saving to read-only file system. How do I change the path of `output.json` to `/tmp/` or skip downloading it completely?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip) API
[debug] params: {'proxy': 'http://username:password@address:port', 'progress_hooks': [<function handler.<locals>.hook at 0x7f3e53dd89d0>], 'overwrites': True, 'paths': {'temp': '/tmp/', 'home': '/tmp/'}, 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.10.15 (CPython x86_64 64bit) - Linux-5.10.227-239.884.amzn2.x86_64-x86_64-with-glibc2.26 (OpenSSL 1.1.1x  30 Jan 2024, glibc 2.26)
[debug] exe versions: ffmpeg 7.0.2-static (setts)
[debug] Optional libraries: Cryptodome-3.21.0, certifi-2024.12.14, mutagen-1.47.0, requests-2.32.3, sqlite3-3.7.17, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {'all': 'http://username:password@address:port'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=BCk1p_h-ewk
[youtube] BCk1p_h-ewk: Downloading webpage
[youtube] BCk1p_h-ewk: Downloading ios player API JSON
[youtube] BCk1p_h-ewk: Downloading mweb player API JSON
[debug] [youtube] Extracting signature function js_03dbdfab_107
[youtube] BCk1p_h-ewk: Downloading player 03dbdfab
WARNING: [youtube] BCk1p_h-ewk: Signature extraction failed: Some formats may be missing
[debug] [youtube] Could not find JS function "decodeURIComponent"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] BCk1p_h-ewk: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BCk1p_h-ewk: Downloading 1 format(s): 136+251
[debug] Invoking http downloader on "https://rr3---sn-n02xgoxufvg3-2gb6.googlevideo.com/videoplayback?expire=1735602155&ei=i9tyZ9P6B63k6dsP3bH_0As&ip=64.137.42.112&id=o-AEij63_bmZHqLsMxrocV1fvFES8mTFny42e-AIh3-lRt&itag=136&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1735580555%2C&mh=4t&mm=31%2C29&mn=sn-n02xgoxufvg3-2gb6%2Csn-4g5edns7&ms=au%2Crdu&mv=m&mvi=3&pl=23&rms=au%2Cau&initcwndbps=1202500&bui=AfMhrI8z2YnPWC7msKKysShMhmJPBc3GfkTKu7cMs8Bpc_WMqForhrntoX78fbA_Hir7LcDixmBBBAeE&spc=x-caUDbBkR9bS9FQXi2asRF2Rlghyi0gmdICZH7RoJzo3qUhtw0I&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=24234706&dur=199.066&lmt=1706945654208638&mt=1735580010&fvip=2&keepalive=yes&fexp=51326932%2C51335594%2C51371294&c=IOS&txp=6219224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgIXOy3JXbb7KAZWNADQpXr7eUKg58ObZpUbPXpNNeqwcCID4lXm_ADWTtVuqDojRXFy_FszTZjdkxFxl5eg0jDY4Q&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhAMl-GaSWRgyh8-fmJ24jRJ7wjZEbOX-xTURpXc0v3f-PAiBRfFVZun323CNu-2Uv0IOlRfi1xLD1nMNyCw0uu64X_w%3D%3D"
[download] Destination: /tmp/Sia x  David Guetta - Let's Love (Music Video) ft. Sia's Moments ：D [BCk1p_h-ewk].f136.mp4
[download]   0.0% of   23.11MiB at   39.22KiB/s ETA 10:03
[download]   0.0% of   23.11MiB at  114.41KiB/s ETA 03:26
[download]   0.0% of   23.11MiB at  261.95KiB/s ETA 01:30
[download]   0.1% of   23.11MiB at  550.74KiB/s ETA 00:42
[download]   0.1% of   23.11MiB at  257.58KiB/s ETA 01:31
[download]   0.3% of   23.11MiB at  325.16KiB/s ETA 01:12
[download]   0.5% of   23.11MiB at  432.32KiB/s ETA 00:54
[download]   1.1% of   23.11MiB at  662.31KiB/s ETA 00:35
[download]   2.2% of   23.11MiB at    1.04MiB/s ETA 00:21
[download]   4.3% of   23.11MiB at    1.73MiB/s ETA 00:12
[download]   8.6% of   23.11MiB at    2.96MiB/s ETA 00:07
[download]  17.3% of   23.11MiB at    4.94MiB/s ETA 00:03
[download]  34.6% of   23.11MiB at    6.72MiB/s ETA 00:02
[download]  41.9% of   23.11MiB at    7.82MiB/s ETA 00:01
[download]  41.9% of   23.11MiB at  Unknown B/s ETA Unknown
[download]  41.9% of   23.11MiB at  Unknown B/s ETA Unknown
[download]  41.9% of   23.11MiB at    4.35MiB/s ETA 00:03  
[download]  41.9% of   23.11MiB at    6.91MiB/s ETA 00:01
[download]  42.0% of   23.11MiB at   10.55MiB/s ETA 00:01
[download]  42.1% of   23.11MiB at   16.68MiB/s ETA 00:00
[download]  42.4% of   23.11MiB at   28.43MiB/s ETA 00:00
[download]  42.9% of   23.11MiB at   48.04MiB/s ETA 00:00
[download]  44.0% of   23.11MiB at    7.76MiB/s ETA 00:01
[download]  46.2% of   23.11MiB at   13.70MiB/s ETA 00:00
[download]  50.5% of   23.11MiB at   21.89MiB/s ETA 00:00
[download]  59.2% of   23.11MiB at   19.56MiB/s ETA 00:00
[download]  76.5% of   23.11MiB at   14.79MiB/s ETA 00:00
[download]  84.5% of   23.11MiB at   11.11MiB/s ETA 00:00
[download]  84.5% of   23.11MiB at  Unknown B/s ETA Unknown
[download]  84.5% of   23.11MiB at  Unknown B/s ETA Unknown
[download]  84.5% of   23.11MiB at    4.62MiB/s ETA 00:00  
[download]  84.5% of   23.11MiB at    7.11MiB/s ETA 00:00
[download]  84.6% of   23.11MiB at   11.00MiB/s ETA 00:00
[download]  84.7% of   23.11MiB at   17.58MiB/s ETA 00:00
[download]  85.0% of   23.11MiB at   28.79MiB/s ETA 00:00
[download]  85.6% of   23.11MiB at   47.55MiB/s ETA 00:00
[download]  86.6% of   23.11MiB at   11.48MiB/s ETA 00:00
[download]  88.8% of   23.11MiB at   18.98MiB/s ETA 00:00
[download]  93.1% of   23.11MiB at   30.92MiB/s ETA 00:00
[download] 100.0% of   23.11MiB at   22.98MiB/s ETA 00:00
[download] 100% of   23.11MiB in 00:00:03 at 6.91MiB/s   ERROR: Unable to download video: [Errno 30] Read-only file system: 'output.json'
Traceback (most recent call last):
File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3464, in process_info
partial_success, real_download = self.dl(fname, new_info)
File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3202, in dl
return fd.download(name, new_info, subtitle)
File "/opt/python/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 466, in download
ret = self.real_download(filename, info_dict)
File "/opt/python/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 370, in real_download
return download()
File "/opt/python/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 356, in download
self._hook_progress({
File "/opt/python/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 481, in _hook_progress
ph(status)
File "/var/task/index.py", line 25, in hook
with open('output.json', 'w') as f:
OSError: [Errno 30] Read-only file system: 'output.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3581, in wrapper
res = func(*args, **kwargs)
File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1614, in extract_info
return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1625, in wrapper
return func(self, *args, **kwargs)
File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1781, in __extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1840, in process_ie_result
ie_result = self.process_video_result(ie_result, download=download)
File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3014, in process_video_result
self.process_info(new_info)
File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 178, in wrapper
return func(self, *args, **kwargs)
File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3494, in process_info
raise UnavailableVideoError(err)
yt_dlp.utils.UnavailableVideoError: Unable to download video: [Errno 30] Read-only file system: 'output.json'

[ERROR] DownloadError: ERROR: Unable to download video: [Errno 30] Read-only file system: 'output.json'
Traceback (most recent call last):
  File "/var/task/index.py", line 33, in handler
    res = ydl.download([body['url']])
  File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3608, in download
    self.__download_wrapper(self.extract_info)(
  File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3585, in wrapper
    self.report_error(e)
  File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1091, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/opt/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1030, in trouble
    raise DownloadError(message, exc_info)
```

**Comment by bashonly** [comment]
> File "/opt/python/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 356, in download
self._hook_progress({
> File "/opt/python/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 481, in _hook_progress
ph(status)
> File "/var/task/index.py", line 25, in hook
> with open('output.json', 'w') as f:
> OSError: [Errno 30] Read-only file system: 'output.json'

It's a problem with your progress  hook, for which you didn't share the code. Dunno how you expect anyone to help you with that

also your yt-dlp is outdated

**Comment by fadone** [comment]
Oh. My mistake. Completely forgot that part. Thanks.

**Comment by ialidigital** [comment]
Adding only for anyone who comes across this later - this error indicates you destination path on your local filesystem is protected or your user doesn't have access rights (write access) to the destination path - solution change the path to one where your user ha rights, or give your user the appropriate write access. Thanks
