### ISSUE TITLE
[bilibili] Space playlist URLs unsupported / ERROR: Unsupported URL: https://space.bilibili.com/ID/lists/

### ISSUE THREAD

**Issue by opkhkh** [yt-dlp/yt-dlp#11959]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

China

### Example URLs

https://space.bilibili.com/290526283/lists/1128088

### Provide a description that is worded well enough to be understood

It used to be possible to download Bilibili playlists, but now it cannot be downloaded. Single videos can still be downloaded normally.

ERROR: Unsupported URL: https://space.bilibili.com/290526283/lists/1128088

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://space.bilibili.com/290526283/lists/1128088']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.12.26.232815 from yt-dlp/yt-dlp-nightly-builds [0b6b7742c] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.12.26.232815 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.12.26.232815 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://space.bilibili.com/290526283/lists/1128088
[generic] 1128088: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1128088: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://space.bilibili.com/290526283/lists/1128088
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1634, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1769, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://space.bilibili.com/290526283/lists/1128088
```

**Comment by october262** [comment]
press the play all button and then copy the URL, it will now download all 766 playlist episodes.

**Comment by c-basalt** [comment]
You can use old `https://space.bilibili.com/290526283/channel/collectiondetail?sid=1128088` before PR merge.

**Comment by marmotadog** [comment]
but yt-dlp --flat-playlist --print "url" https://space.bilibili.com/698029620/lists/254091?type=series still can't use

**Comment by ZekunZh** [comment]
Upgrading to stable@2025.01.26 helps me to solve this problem.
