### ISSUE TITLE
Video unavailable. This video is not available

### ISSUE THREAD

**Issue by KameronJohn** [yt-dlp/yt-dlp#11961]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am not able to download this playlist:
https://music.youtube.com/playlist?list=OLAK5uy_nTX_UcyURUCsI2KNerL9nZi8mpxfshIAA
and some other yt music too, but I cant tell the pattern.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://music.youtube.com/watch?v=iGjbuiZHk5k
[debug] Command-line config: ['-vU', 'https://music.youtube.com/watch?v=iGjbuiZHk5k']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2023-11-09-git-acf63d5350-full_build-www.gyan.dev (setts), ffprobe 2023-11-09-git-acf63d5350-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://music.youtube.com/watch?v=iGjbuiZHk5k
[youtube] iGjbuiZHk5k: Downloading webpage
[youtube] iGjbuiZHk5k: Downloading ios player API JSON
[youtube] iGjbuiZHk5k: Downloading mweb player API JSON
[youtube] iGjbuiZHk5k: Downloading web music client config
[youtube] iGjbuiZHk5k: Downloading player 03dbdfab
[youtube] iGjbuiZHk5k: Downloading web music player API JSON
ERROR: [youtube] iGjbuiZHk5k: Video unavailable. This video is not available
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\youtube.py", line 4541, in _real_extract
  File "yt_dlp\extractor\common.py", line 1276, in raise_no_formats
```

**Comment by bashonly** [comment]
It's due to geo-restriction. Does the link play in your browser on the same machine with the same IP address?

**Comment by KameronJohn** [comment]
Yes, I play it on the same machine and I am not using any VPN

**Comment by bashonly** [comment]
what region are you in?

**Comment by KameronJohn** [comment]
I'm in Canada and I can play those music from the web.

**Comment by gnadenlos** [comment]
Same problem since yesterday with my German Youtube Premium account using Firefox cookies (with the --cookies-from-browser option). Since it happened I also have problems playing some videos through the website. Switching to a different account solves it for the webbrowser.

**Comment by bashonly** [comment]
@gnadenlos that sounds like #10085. OP is not using cookies

**Comment by pukkandan** [comment]
> Yes, I play it on the same machine and I am not using any VPN

Is the browser logged in to youtube? Can you access it without logging in? (use incognito to test)

**Comment by omegaapex128** [comment]
I use a VPN and even with split tunneling, itubego refuses to work when I am connected. Whatever version of the Chromium browser the application uses doesn't even give me a chance to log into my YouTube account like a Firefox private browsing window does to prove I'm not a bot. It's nonsense. I shouldn't have to keep turning off my VPN to use the downloader I paid for.

2025-01-07 20:50:37,955 downloader INFO     start processing
2025-01-07 20:50:37,955 downloader INFO     start load cookies
2025-01-07 20:50:37,956 downloader INFO     start extracting video
2025-01-07 20:52:19,155 downloader ERROR    Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1624, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1759, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\youtube.py", line 4388, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 4352, in _download_player_responses
  File "yt_dlp\extractor\youtube.py", line 4009, in _extract_player_responses
yt_dlp.utils.ExtractorError: [youtube] TWyspcRSsys: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader.py", line 258, in process
  File "downloader.py", line 510, in _ytdl_extract_info
  File "downloader.py", line 507, in extract
  File "downloader.py", line 498, in extract
  File "yt_dlp\YoutubeDL.py", line 1613, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1642, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1090, in report_error
  File "yt_dlp\YoutubeDL.py", line 1029, in trouble
yt_dlp.utils.DownloadError: ERROR: [youtube] TWyspcRSsys: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

2025-01-07 20:52:19,156 downloader INFO     ytdl extract failed, try youget extract info

**Comment by pukkandan** [comment]
@omegaapex128 You're in the wrong place. We are not affiliated with itubego

**Comment by pukkandan** [comment]
> > Yes, I play it on the same machine and I am not using any VPN
> 
> Is the browser logged in to youtube? Can you access it without logging in? (use incognito to test)

Can be reopened if more information is given

**Comment by RazZziel** [comment]
Humm, weird. Today just adding `--cookies-from-browser firefox` works fine with that same video, although it wasn't working last week. 🤷
