### ISSUE TITLE
[Broken] Funimation

### ISSUE THREAD

**Issue by Burve** [yt-dlp/yt-dlp#1198]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
 .\yt-dlp.exe --cookies f.txt -F https://www.funimation.com/en/shows/how-a-realist-hero-rebuilt-the-kingdom/when-you-surround-an-army-leave-an-outlet-free/ -v
[debug] Command-line config: ['--cookies', 'f.txt', '-F', 'https://www.funimation.com/en/shows/how-a-realist-hero-rebuilt-the-kingdom/when-you-surround-an-army-leave-an-outlet-free/', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.25 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg n4.4-155-g44a6aff227-20211002, ffprobe n4.4-155-g44a6aff227-20211002
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [funimation:page] Extracting URL: https://www.funimation.com/en/shows/how-a-realist-hero-rebuilt-the-kingdom/when-you-surround-an-army-leave-an-outlet-free/
[funimation:page] how-a-realist-hero-rebuilt-the-kingdom_when-you-surround-an-army-leave-an-outlet-free: Downloading webpage
WARNING: [funimation:page] how-a-realist-hero-rebuilt-the-kingdom_when-you-surround-an-army-leave-an-outlet-free: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: [funimation:page] how-a-realist-hero-rebuilt-the-kingdom/when-you-surround-an-army-leave-an-outlet-free: Unable to extract al:web:url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 585, in extract
  File "yt_dlp\extractor\funimation.py", line 69, in _real_extract
  File "yt_dlp\extractor\common.py", line 1272, in _html_search_meta
  File "yt_dlp\extractor\common.py", line 1158, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1149, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 585, in extract
  File "yt_dlp\extractor\funimation.py", line 69, in _real_extract
  File "yt_dlp\extractor\common.py", line 1272, in _html_search_meta
  File "yt_dlp\extractor\common.py", line 1158, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1149, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1252, in __extract_info
  File "yt_dlp\extractor\common.py", line 601, in extract
yt_dlp.utils.ExtractorError: [funimation:page] how-a-realist-hero-rebuilt-the-kingdom/when-you-surround-an-army-leave-an-outlet-free: Unable to extract al:web:url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Yesterady (06.10.2021) Funimation was working fine; however, today (07.10.2021) on any link I try I get this error.

**Comment by pukkandan** [comment]
duplicate of #993, #1195

Dont tick options blindly!
> I've searched the bugtracker for similar issues including closed ones
