### ISSUE TITLE
LinkedIn Learning extractor broken? [Broken]

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#1205]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp https://www.linkedin.com/learning/working-remotely-2/the-value-of-working-remotely --verbose
[debug] Command-line config: ['https://www.linkedin.com/learning/working-remotely-2/the-value-of-working-remotely', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.09.25
[debug] Python version 3.7.5 (CPython 64bit) - Linux-4.15.0-135-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Optional libraries: Crypto, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [linkedin:learning] Extracting URL: https://www.linkedin.com/learning/working-remotely-2/the-value-of-working-remotely
ERROR: the-value-of-working-remotely: An extractor error has occurred. (caused by KeyError('JSESSIONID')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 585, in extract
    ie_result = self._real_extract(url)
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/extractor/linkedin.py", line 96, in _real_extract
    course_slug, 'selectedVideo', video_slug, height)['selectedVideo']
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/extractor/linkedin.py", line 36, in _call_api
    'Csrf-Token': self._get_cookies(api_url)['JSESSIONID'].value,
KeyError: 'JSESSIONID'
Traceback (most recent call last):
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 585, in extract
    ie_result = self._real_extract(url)
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/extractor/linkedin.py", line 96, in _real_extract
    course_slug, 'selectedVideo', video_slug, height)['selectedVideo']
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/extractor/linkedin.py", line 36, in _call_api
    'Csrf-Token': self._get_cookies(api_url)['JSESSIONID'].value,
KeyError: 'JSESSIONID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1227, in wrapper
    return func(self, *args, **kwargs)
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1252, in __extract_info
    ie_result = ie.extract(url)
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 606, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e, video_id=self.get_temp_id(url))
yt_dlp.utils.ExtractorError: the-value-of-working-remotely: An extractor error has occurred. (caused by KeyError('JSESSIONID')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Hi,

Is LinkedIn Learning supported? I tried downloading the following free course and it throws an error.

https://www.linkedin.com/learning/working-remotely-2/the-value-of-working-remotely

**Comment by ahm750** [comment]
Seems like it requires a cookie file to download. Closed.
