### ISSUE TITLE
[Broken] youtube live: AttributeError: 'FFmpegFD' object has no attribute '_postprocessor_hooks'

### ISSUE THREAD

**Issue by Crypto90** [yt-dlp/yt-dlp#1211]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.10.09**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones
- [X] I've read the opening an issue section in CONTRIBUTING.md
- [X] I have given an appropriate title to the issue

## Verbose log

```
python3.7 yt-dlp -v http://www.youtube.com/watch?v=THN8ihZ6qy0
[debug] Command-line config: ['-v', 'http://www.youtube.com/watch?v=THN8ihZ6qy0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.10.09 (zip)
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.9.0-9-amd64-x86_64-with-debian-9.13
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Optional libraries: none
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: http://www.youtube.com/watch?v=THN8ihZ6qy0
[youtube] THN8ihZ6qy0: Downloading webpage
[youtube] THN8ihZ6qy0: Downloading android player API JSON
[youtube] THN8ihZ6qy0: Downloading m3u8 information
[youtube] THN8ihZ6qy0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 46
[debug] Default format spec: best/bestvideo+bestaudio
[info] THN8ihZ6qy0: Downloading 1 format(s): 301
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1633831423/ei/nvVhYYfsO4ee1wL25ZzgDQ/ip/5.231.196.154/id/THN8ihZ6qy0.5/itag/301/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D299/hls_chunk_host/rr4---sn-4g5e6nsr.googlevideo.com/playlist_duration/30/manifest_duration/30/vprv/1/playlist_type/DVR/initcwndbps/11580/mh/WP/mm/44/mn/sn-4g5e6nsr/ms/lva/mv/m/mvi/4/pl/18/dover/11/keepalive/yes/fexp/24001373,24007246/mt/1633809396/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,vprv,playlist_type/sig/AOq0QJ8wRAIgaUlV3SsUvaElWkqZ1ZAxzVsuN_ier5CJx4j3eC54SW0CIHNX7c2G6iy-DpS9K_UTLZ1fAVqtfL_Lj9alC-S2CRwn/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRAIgRh8LQUYOe8dholIY0nOrJfm-Ga8yx6oJgn1_cjHge5QCIF48cdeETX-NXTkXE7I8hNe6uNvRo93ZConj6n_8gpQW/playlist/index.m3u8"
[download] Destination: Nightcore Radio 24_7 _ Top Nightcore Songs Of All Time ♪ 2021-10-09 16_03 [THN8ihZ6qy0].mp4
ERROR: 'FFmpegFD' object has no attribute '_postprocessor_hooks'
Traceback (most recent call last):
  File "yt-dlp/yt_dlp/YoutubeDL.py", line 1262, in wrapper
    return func(self, *args, **kwargs)
  File "yt-dlp/yt_dlp/YoutubeDL.py", line 1300, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "yt-dlp/yt_dlp/YoutubeDL.py", line 1350, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "yt-dlp/yt_dlp/YoutubeDL.py", line 2360, in process_video_result
    self.process_info(new_info)
  File "yt-dlp/yt_dlp/YoutubeDL.py", line 2799, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "yt-dlp/yt_dlp/YoutubeDL.py", line 2507, in dl
    return fd.download(name, new_info, subtitle)
  File "yt-dlp/yt_dlp/downloader/common.py", line 398, in download
    ret = self.real_download(filename, info_dict)
  File "yt-dlp/yt_dlp/downloader/external.py", line 40, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
  File "yt-dlp/yt_dlp/downloader/external.py", line 345, in _call_downloader
    ffpp = FFmpegPostProcessor(downloader=self)
  File "yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 62, in __init__
    PostProcessor.__init__(self, downloader)
  File "yt-dlp/yt_dlp/postprocessor/common.py", line 59, in __init__
    self.set_downloader(downloader)
  File "yt-dlp/yt_dlp/postprocessor/common.py", line 95, in set_downloader
    for ph in downloader._postprocessor_hooks:
AttributeError: 'FFmpegFD' object has no attribute '_postprocessor_hooks'

```

## Description

Im currently switching from youtube-dl to yt-dlp. I have upgraded from python 2 to python 3.7.3 as yt-dlp requires at least python 3.6.0.
I got most working, but I run into an issue on all kind of youtube livestreams. Can someone tell me whats wrong here?
Thanks for your help.

**Comment by pukkandan** [comment]
Seems to be a regression in the release that I just made.

Please use the last release while I fix the issue

**Comment by Crypto90** [comment]
Yea I can confirm with the previous version it worked.
So I accidentally run into it while it still was working -> updated -> issue occured and I was not 100% sure I did corrupt something :p 

An other question:
- has yt-dlp a feature to use ytsearch: to search for youtube playlists only?
- is it possible to list the content (video list) of a given youtube playlist id?

I always did patch the currently outdated youtube-dl myself and now Im looking if yt-dlp maybe already supports this.
