### ISSUE TITLE
[Broken] Fox: Issue with JSON

### ISSUE THREAD

**Issue by ischmidt20** [yt-dlp/yt-dlp#1216]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.10.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
yt-dlp -F https://www.fox.com/watch/219b6c82f8e24407076b0122cedd6c2c/ -v
[debug] Command-line config: ['-F', 'https://www.fox.com/watch/219b6c82f8e24407076b0122cedd6c2c/', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.10.09
[debug] Python version 3.7.0 (CPython 64bit) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[FOX] Downloading JSON metadata
[debug] [FOX] Extracting URL: https://www.fox.com/watch/219b6c82f8e24407076b0122cedd6c2c/
[FOX] 219b6c82f8e24407076b0122cedd6c2c: Downloading JSON metadata
ERROR: [FOX] 219b6c82f8e24407076b0122cedd6c2c: This video is only available via cable service provider subscription. You may want to use --cookies.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 698, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/fox.py", line 67, in _call_api
    video_id, data=data, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 964, in _download_json
    expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 942, in _download_json_handle
    expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/adobepass.py", line 1363, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 731, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 716, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 589, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/fox.py", line 96, in _real_extract
    video = self._call_api('vodplayer/' + video_id, video_id)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/fox.py", line 76, in _call_api
    'subscription. You may want to use --cookies.', expected=True)
yt_dlp.utils.ExtractorError: This video is only available via cable service provider subscription. You may want to use --cookies.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 698, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/fox.py", line 67, in _call_api
    video_id, data=data, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 964, in _download_json
    expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 942, in _download_json_handle
    expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/adobepass.py", line 1363, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 731, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 716, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 589, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/fox.py", line 96, in _real_extract
    video = self._call_api('vodplayer/' + video_id, video_id)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/fox.py", line 76, in _call_api
    'subscription. You may want to use --cookies.', expected=True)
yt_dlp.utils.ExtractorError: This video is only available via cable service provider subscription. You may want to use --cookies.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1262, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1287, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 606, in extract
    e.msg, video_id=video_id, ie=self.IE_NAME, tb=e.traceback, expected=e.expected, cause=e.cause)
yt_dlp.utils.ExtractorError: [FOX] 219b6c82f8e24407076b0122cedd6c2c: This video is only available via cable service provider subscription. You may want to use --cookies.

```

## Description

I think the Fox extractor has been broken for a while. Diving into the extractor code, it appears to be some issue with how yt-dlp tries to get the JSON information. I briefly tried giving it a crack myself but I was not familiar enough with the codebase to make much progress.

Another semi-related point is that Fox gives free hour-long previews for any video, even those that require pay cable TV login. Perhaps there can be some way to leverage this so that TV provider details aren't required at all. Should also note that the above link I tried should not require any login (but it will expire in a few days).

WRITE DESCRIPTION HERE

**Comment by BFK-78** [comment]
Hai

**Comment by ischmidt20** [comment]
Bumping this as I've had some time to investigate a little further. This Fox extractor was last updated in 2019, and there is an old [youtube-dl issue](https://github.com/ytdl-org/youtube-dl/issues/27173) which was never addressed.

It appears that the extractor _already_ tries to invoke the trial mode, so that is not an issue. The problem is that it is pointing to the wrong API call. Instead of 

```
video = self._call_api('vodplayer/' + video_id, video_id)
release_url = video['url']
```

we want

```
video = self._call_api('screens/video-detail/' + video_id, video_id)
video = video['panels']['member'][0]['items']['member'][0]
release_url = video['videoRelease']['url']
```

This URL will be something like `http://link.theplatform.com/s/fox-dcg/media/fOImp1i9A6cN`. In the browser, however, the URL is `https://link.theplatform.com/s/fox-dcg/media/fOImp1i9A6cN?_fw_us_privacy=1---&assetTypes=clear:uplynk-clean:uplynk-ivod-national:uplynk-ivod-west:uplynk-ivod-mountain:uplynk-ivod-east:uplynk-ivod&country=US&did=1e108d79-6e99-461f-b8b1-fc59bf5de216&dma=501&extra=%7Cis_lat%7C0&is_lat=0&thumbsray=1&format=redirect&formats=M3U+fairplay,MPEG-DASH+widevine,MPEG-DASH+playready,M3U&mvpd=1bca1f19874e40b3675ef125882715a5&profile=516429:uplynk_foxnow_webdesktop_vod&ptid=foxnow_web_VOD_tve&restriction=186521157&sitesection=foxnow/webdesktop/vod/videopage&vcid2=516429:1e108d79-6e99-461f-b8b1-fc59bf5de216&zipcode=07040&sig=1061d5d9d5a6e908acb4d9cf0d814a65914b9be7844fbe3273466f78435045466f7853706f727473566964656f55524c5369676e`.

Clearly, at least some of these extra parameters are necessary, as if they are left out, a 412 error is returned. Yet if they are included, we are redirected to another JSON file with URL something like: `https://content-fox.uplynk.com/preplay/8feb4dde551b4cfca200e1a73c9a6cb1.json?v=2&rays=gkjihfedcb&ad=fw_prod&ad.flags=:slcb+sltp+qtcb+emcr+fbad+dtrd+exvt&ad.csid=foxnow/webdesktop/vod/videopage&ad.prof=516429:uplynk_foxnow_webdesktop_vod&ad.kvsep=|&ad.kv=fnl-affiliate||fs-affiliate||affwin|none|programtype|unknown|_fw_ae|1bca1f19874e40b3675ef125882715a5|_fw_us_privacy|1---|_fw_did_idfa||_fw_did_google_advertising_id||_fw_did_android_id||_fw_did|1e108d79-6e99-461f-b8b1-fc59bf5de216|_fw_nielsen_app_id||_fw_vcid2|516429:1e108d79-6e99-461f-b8b1-fc59bf5de216|adPackage|dai|kuid||_fw_seg||aap_truex|true|is_lat|0&is_lat=0&thumbsray=1&tc=1&exp=1641405066&rn=699518&ct=a&cid=8feb4dde551b4cfca200e1a73c9a6cb1&sig=baeb52cd2d22f01625909baa326a401d1ec4fd3fcb38f0ef6d10ded13313243c`. From here, we can extract the m3u8 URL with the same line of code that is already there:

```
m3u8_url = self._download_json(release_url, video_id)['playURL']
````

Then, hopefully, the rest of the information extractor would proceed as normal.

However, given that the URL that we would need is a Platform URL, I am wondering if it would be better to somehow let the extractor for ThePlatform handle everything. Yet it still wouldn't resolve the issue of figuring out exactly what parameters are needed to avoid a 412 response.
