### ISSUE TITLE
[Bug] pyinstaller build raises "Cannot load native module 'Cryptodome.Util._strxor'"

### ISSUE THREAD

**Issue by hetman2** [yt-dlp/yt-dlp#1256]
Hi,

I'm coming to this project after using youtube-dl.exe for a long time. So I download the latest release, and I try running it via command line, but I get the following error.

OSError: Cannot load native module 'Cryptodome.Util._strxor': Not found '_strxor.cp38-win_amd64.pyd', Cannot load '_strxor.pyd': Failed to load dynlib/dll

What am I doing wrong?

**Comment by hetman2** [comment]
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "yt_dlp\__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "yt_dlp\options.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "yt_dlp\compat.py", line 154, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "Cryptodome\Cipher\__init__.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "Cryptodome\Cipher\_mode_ccm.py", line 44, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "Cryptodome\Util\strxor.py", line 35, in <module>
  File "Cryptodome\Util\_raw_api.py", line 309, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Cryptodome.Util._strxor': Not found '_strxor.cp38-win_amd64.pyd', Cannot load '_strxor.pyd': Failed to load dynlib/dll 'C:\\Users\\<Redacted>\\AppData\\Local
\\Temp\\_MEI689362\\Cryptodome\\Util\\..\\Util\\_strxor.pyd'. Most probably this dynlib/dll was not found when the application was frozen.
[8412] Failed to execute script '__main__' due to unhandled exception!

**Comment by arakkam** [comment]
Avast detected "_strxor.pyd" as PUP, might go away in day or two.
https://www.virustotal.com/gui/file/e019ca0334e239970a3ba625bbd24c37d8a3c3b5655015471780d4fb7f5a1a98?nocache=1
