### ISSUE TITLE
[Bug] bilibili yt_dlp.utils.DownloadError: ERROR: giving up after 0 retries

### ISSUE THREAD

**Issue by wanghaisheng** [yt-dlp/yt-dlp#1262]
## Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [ ] I've verified that I'm running yt-dlp version **2021.10.10**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] The provided URLs do not contain any DRM to the best of my knowledge
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read the opening an issue section in CONTRIBUTING.md
- [ ] I have given an appropriate title to the issue

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

```
[info] 933553357: Downloading 1 format(s): 0
[download] Destination: 孕妇智斗杀猪盘骗局 新型骗局套路太多 [933553357].flv
[download]  12.7% of 270.71MiB at 91.48KiB/s ETA 44:05ERROR: giving up after 0 retries
Traceback (most recent call last):
  File "videolist.py", line 55, in <module>
    info = ydl.extract_info(item['arcurl'])
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1255, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1263, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1301, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1351, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2361, in process_video_result
    self.process_info(new_info)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2800, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2508, in dl
    return fd.download(name, new_info, subtitle)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 397, in download
    ret = self.real_download(filename, info_dict)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 382, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 174, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 842, in report_error
    self.trouble(f'{self._color_text("ERROR:", "red")} {message}', tb)
  File "/opt/anaconda3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 812, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: giving up after 0 retries
```

https://www.bilibili.com/video/BV1NT4y1o76q

**Comment by wanghaisheng** [comment]
```
import requests
import json

import yt_dlp
import os


results =[]


session = requests.session()


def stringify(obj: dict) -> dict:
    """turn every value in the dictionary to a string"""
    for k, v in obj.items():
        if isinstance(v, dict):
            # if value is a dictionary, stringifiy recursively
            stringify(v)
            continue
        if not isinstance(v, str):
            if isinstance(v, bool):
                # False/True -> false/true
                obj[k] = str(v).lower()
            else:
                obj[k] = str(v)
    return obj


with open('cookies.json') as f:
    cookie_list: list = json.load(f)
    # create the cookie jar from the first cookie
    cookie_jar = requests.utils.cookiejar_from_dict(stringify(cookie_list[0]))
    # append the rest of the cookies
    for cookie in cookie_list[1:]:
        requests.utils.add_dict_to_cookiejar(cookie_jar, stringify(cookie))
    session.cookies = cookie_jar
    idlist=[]    
    for i in range(1,20):
        payload = {'search_type': 'video', 'keyword': '骗局','order':'pubdate','duration':'2','page':i}
        r = session.get('http://api.bilibili.com/x/web-interface/search/type', params=payload)
        # print(r.json().keys())
        results.extend(r.json()["data"]["result"])
        for i,item in enumerate(r.json()["data"]["result"]):


            result={"title":item['title'],
            "tag":item['tag'],
            "description":item['description']+"original video from\r\n"+item['arcurl']}
            if not os.path.exists(str(item['id'])):
                os.makedirs(str(item['id']))
            os.chdir(str(item['id']))
            ydl_opts = {}
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(item['arcurl'])
                        # ydl.download([item['arcurl']])

                with open(str(item['id'])+'.json', 'w') as outfile:
                    json.dump(result, outfile)    
            os.chdir("..")
            idlist.append(item['arcurl'])
    print('found videos numbers',len(idlist))
    with open('videolist.txt', 'w') as outfile:
        json.dump(idlist, outfile)

```

**Comment by wanghaisheng** [comment]
I  dont get what you say about *just add retries to the options.*
