### ISSUE TITLE
[Broken] Instagram: Unable to extract video url

### ISSUE THREAD

**Issue by github-account1111** [yt-dlp/yt-dlp#1264]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
yt-dlp --no-cache-dir -F https://www.instagram.com/p/BlspOaxBdu6/ -v
[debug] Command-line config: ['--no-cache-dir', '-F', 'https://www.instagram.com/p/BlspOaxBdu6/', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.8.5 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 2021-04-28-git-1ab74bc193-full_build-www.gyan.dev, ffprobe 2021-04-28-git-1ab74bc193-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/BlspOaxBdu6/
[Instagram] BlspOaxBdu6: Downloading webpage
ERROR: [Instagram] BlspOaxBdu6: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\common.py", line 589, in extract
    ie_result = self._real_extract(url)
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\instagram.py", line 244, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\common.py", line 1264, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\common.py", line 1159, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\common.py", line 1150, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\common.py", line 589, in extract
    ie_result = self._real_extract(url)
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\instagram.py", line 244, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\common.py", line 1264, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\common.py", line 1159, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\common.py", line 1150, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\YoutubeDL.py", line 1263, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\YoutubeDL.py", line 1288, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\usr\anaconda3\envs\yt_dlp\lib\site-packages\yt_dlp\extractor\common.py", line 605, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [Instagram] BlspOaxBdu6: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Unable to download individual Instagram videos.

**Comment by Ashish0804** [comment]
Are u bulk downloading from IG?
