### ISSUE TITLE
[Bug] YT-DLP not finding the files it just downloaded?

### ISSUE THREAD

**Issue by VXsz** [yt-dlp/yt-dlp#1273]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
[debug] Command-line config: ['-Uv', '--format', '(bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec^=vp9.2][height>=4320][fps>30]/bestvideo[vcodec^=vp9][height>=4320][fps>30]/bestvideo[vcodec^=avc1][height>=4320][fps>30]/bestvideo[height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=4320]/bestvideo[vcodec^=vp9.2][height>=4320]/bestvideo[vcodec^=vp9][height>=4320]/bestvideo[vcodec^=avc1][height>=4320]/bestvideo[height>=4320]/bestvideo[vcodec^=av01][height>=2880][fps>30]/bestvideo[vcodec^=vp9.2][height>=2880][fps>30]/bestvideo[vcodec^=vp9][height>=2880][fps>30]/bestvideo[vcodec^=avc1][height>=2880][fps>30]/bestvideo[height>=2880][fps>30]/bestvideo[vcodec^=av01][height>=2880]/bestvideo[vcodec^=vp9.2][height>=2880]/bestvideo[vcodec^=vp9][height>=2880]/bestvideo[vcodec^=avc1][height>=2880]/bestvideo[height>=2880]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec^=vp9.2][height>=2160][fps>30]/bestvideo[vcodec^=vp9][height>=2160][fps>30]/bestvideo[vcodec^=avc1][height>=2160][fps>30]/bestvideo[height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=2160]/bestvideo[vcodec^=vp9.2][height>=2160]/bestvideo[vcodec^=vp9][height>=2160]/bestvideo[vcodec^=avc1][height>=2160]/bestvideo[height>=2160]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec^=vp9.2][height>=1440][fps>30]/bestvideo[vcodec^=vp9][height>=1440][fps>30]/bestvideo[vcodec^=avc1][height>=1440][fps>30]/bestvideo[height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1440]/bestvideo[vcodec^=vp9.2][height>=1440]/bestvideo[vcodec^=vp9][height>=1440]/bestvideo[vcodec^=avc1][height>=1440]/bestvideo[height>=1440]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec^=vp9.2][height>=1080][fps>30]/bestvideo[vcodec^=vp9][height>=1080][fps>30]/bestvideo[vcodec^=avc1][height>=1080][fps>30]/bestvideo[height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec^=vp9.2][height>=1080]/bestvideo[vcodec^=vp9][height>=1080]/bestvideo[vcodec^=avc1][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec^=vp9.2][height>=720][fps>30]/bestvideo[vcodec^=vp9][height>=720][fps>30]/bestvideo[vcodec^=avc1][height>=720][fps>30]/bestvideo[height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec^=vp9.2][height>=720]/bestvideo[vcodec^=vp9][height>=720]/bestvideo[vcodec^=avc1][height>=720]/bestvideo[height>=720]/bestvideo[vcodec^=av01][height>=480][fps>30]/bestvideo[vcodec^=vp9.2][height>=480][fps>30]/bestvideo[vcodec^=vp9][height>=480][fps>30]/bestvideo[vcodec^=avc1][height>=480][fps>30]/bestvideo[height>=480][fps>30]/bestvideo[vcodec^=av01][height>=480]/bestvideo[vcodec^=vp9.2][height>=480]/bestvideo[vcodec^=vp9][height>=480]/bestvideo[vcodec^=avc1][height>=480]/bestvideo[height>=480]/bestvideo[vcodec^=av01][height>=360][fps>30]/bestvideo[vcodec^=vp9.2][height>=360][fps>30]/bestvideo[vcodec^=vp9][height>=360][fps>30]/bestvideo[vcodec^=avc1][height>=360][fps>30]/bestvideo[height>=360][fps>30]/bestvideo[vcodec^=av01][height>=360]/bestvideo[vcodec^=vp9.2][height>=360]/bestvideo[vcodec^=vp9][height>=360]/bestvideo[vcodec^=avc1][height>=360]/bestvideo[height>=360]/bestvideo[vcodec^=avc1][height>=240][fps>30]/bestvideo[vcodec^=av01][height>=240][fps>30]/bestvideo[vcodec^=vp9.2][height>=240][fps>30]/bestvideo[vcodec^=vp9][height>=240][fps>30]/bestvideo[height>=240][fps>30]/bestvideo[vcodec^=avc1][height>=240]/bestvideo[vcodec^=av01][height>=240]/bestvideo[vcodec^=vp9.2][height>=240]/bestvideo[vcodec^=vp9][height>=240]/bestvideo[height>=240]/bestvideo[vcodec^=avc1][height>=144][fps>30]/bestvideo[vcodec^=av01][height>=144][fps>30]/bestvideo[vcodec^=vp9.2][height>=144][fps>30]/bestvideo[vcodec^=vp9][height>=144][fps>30]/bestvideo[height>=144][fps>30]/bestvideo[vcodec^=avc1][height>=144]/bestvideo[vcodec^=av01][height>=144]/bestvideo[vcodec^=vp9.2][height>=144]/bestvideo[vcodec^=vp9][height>=144]/bestvideo[height>=144]/bestvideo)+(bestaudio[acodec^=opus]/bestaudio)/best', 'LA3NP8SrOBM', '--verbose', '--force-ipv4', '--ignore-errors', '--no-continue', '--no-overwrites', '--download-archive', 'archive.log', '--sponsorblock-mark', 'ALL', '--add-metadata', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '--embed-thumbnail', '--all-subs', '--embed-subs', '--get-comments', '--match-filter', '!is_live & !live', '--output', '%(uploader)s/%(uploader)s - %(upload_date)s - %(title)s/%(uploader)s - %(upload_date)s - %(title)s [%(id)s].%(ext)s', '--merge-output-format', 'mkv']
[debug] Loading archive file 'archive.log'

[debug] Encodings: locale cp1256, fs utf-8, out utf-8, pref cp1256
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.10)
[debug] [youtube] Extracting URL: LA3NP8SrOBM
[youtube] LA3NP8SrOBM: Downloading webpage
[youtube] LA3NP8SrOBM: Downloading android player API JSON
[youtube] LA3NP8SrOBM: Downloading MPD manifest
[youtube] LA3NP8SrOBM: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[debug] Unable to connect to thumbnail 41 URL "https://i.ytimg.com/vi_webp/LA3NP8SrOBM/maxresdefault.webp" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 40
[debug] Unable to connect to thumbnail 40 URL "https://i.ytimg.com/vi/LA3NP8SrOBM/maxresdefault.jpg" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 39
[debug] Unable to connect to thumbnail 39 URL "https://i.ytimg.com/vi_webp/LA3NP8SrOBM/hq720.webp" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 38
[debug] Unable to connect to thumbnail 38 URL "https://i.ytimg.com/vi/LA3NP8SrOBM/hq720.jpg" - HTTP Error 404: Not Found. Skipping...
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/aab4?service=YouTube&categories=%5B%22preview%22%2C+%22sponsor%22%2C+%22interaction%22%2C+%22intro%22%2C+%22selfpromo%22%2C+%22music_offtopic%22%2C+%22outro%22%5D
[SponsorBlock] No segments were found in the SponsorBlock database
[info] LA3NP8SrOBM: Downloading 1 format(s): 244+140
[youtube] Downloading comment section API JSON
[youtube] Downloading ~35 comments
[youtube] Sorting comments by newest first
[youtube] Downloading comment API JSON page 1 (0/35)
[youtube]     Downloading comment API JSON reply thread 1 (4/35)
[youtube]     Downloading comment API JSON reply thread 2 (9/35)
[youtube] Downloading comment API JSON page 2 (23/35)
[youtube] Downloaded 35/35 comments
[info] Video description is already present
[debug] Testing thumbnail 36
[debug] Testing thumbnail 35
[debug] Testing thumbnail 34
[debug] Testing thumbnail 33
[debug] Testing thumbnail 32
[debug] Testing thumbnail 31
[debug] Testing thumbnail 30
[info] Video Thumbnail is already present
[info] Video metadata is already present
WARNING: There are no annotations to write.
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1634175196/ei/fDRnYYDRBr2pxN8Pqo2l6A8/ip/8.21.8.82/id/2c0dcd3fc4ab3813/source/youtube/requiressl/yes/playback_host/r5---sn-25glene6.googlevideo.com/mh/1T/mm/31%2C29/mn/sn-25glene6%2Csn-5hnekn76/ms/au%2Crdu/mv/m/mvi/5/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/500000/vprv/1/mt/1634153335/fvip/5/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhALqH_IP5reKXZuTVPapROh28MZeiH-rq3UgASRklCEbaAiBe2nREwgAXtt3xYe--W1RLmjXjQ-J2FdwyD6ZIyHf3xw%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgPTZiRsEKCAQLNc2m-RW1eJug10YF5Gamt9VEaK3tIIMCIH9_u-JJMeCYGY5xXsedy6_OQRDYt9Bj2PSyq7bAt-mD"
[download] M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].f244.webm has already been downloaded
[download] 100% of 52.85MiB[debug] Invoking downloader on "https://r5---sn-25glene6.googlevideo.com/videoplayback?expire=1634175196&ei=fDRnYc27N-KpmLAPn-K20A4&ip=8.21.8.82&id=o-AJk5MRyFtKeNOiYa4IwSjn2YkMSDP-xSEtHpnf5cLx1O&itag=140&source=youtube&requiressl=yes&mh=1T&mm=31%2C29&mn=sn-25glene6%2Csn-5hne6nsy&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=453750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=11476256&otfp=1&dur=709.067&lmt=1573529074177908&mt=1634153099&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKLcDVu5D6AMIzazk3bRHgNe4lcf2sWdWoW-AS-nlncNAiEA2Rmu6zKumoIWlA2Ynk9bMqbGJ3UU4Bu_17d4fB_lrxs%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTm9iMY3_fwboZL7zxUhiysNoOyF19jGFo6_N6fkwLZ0CIQCw8E3j4ULwzSRVcHN5oT0ndh6Oz_aYiybMsmQH4jFyBA%3D%3D"
[download] M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].f140.m4a has already been downloaded
[download] 100% of 10.94MiB[debug] ffmpeg command line: ffprobe -show_streams "file:M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].f140.m4a"
[Merger] Merging formats into "M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].f244.webm" -i "file:M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].temp.mkv"
[debug] ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
file:M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].f244.webm: No such file or directory
ERROR: file:M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].f244.webm: No such file or directory
Traceback (most recent call last):
  File "c:\<py39_path>\lib\site-packages\yt_dlp\YoutubeDL.py", line 2968, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\postprocessor\common.py", line 21, in run
    ret = func(self, info, *args, **kwargs)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\postprocessor\common.py", line 108, in wrapper
    return func(self, info)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 741, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 255, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "c:\<py39_path>\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 292, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].f244.webm: No such file or directory

[EmbedSubtitle] There aren't any subtitles to embed
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:M7MDXD\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول\M7MDXD - 20121006 - MineCraft The Tomb of Rath Part 1 - كستم ماب  - قبر راث الجزء الاول [LA3NP8SrOBM].mkv"
ERROR: 'streams'
Traceback (most recent call last):
  File "c:\<py39_path>\lib\site-packages\yt_dlp\YoutubeDL.py", line 1263, in wrapper
    return func(self, *args, **kwargs)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\YoutubeDL.py", line 1301, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\YoutubeDL.py", line 1351, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\YoutubeDL.py", line 2361, in process_video_result
    self.process_info(new_info)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\YoutubeDL.py", line 2867, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\YoutubeDL.py", line 3025, in post_process
    info = self.run_pp(pp, info)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\YoutubeDL.py", line 2968, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\postprocessor\common.py", line 21, in run
    ret = func(self, info, *args, **kwargs)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\postprocessor\common.py", line 108, in wrapper
    return func(self, info)
  File "c:\<py39_path>\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 632, in run
    options.extend(self._get_metadata_opts(info))
  File "c:\<py39_path>\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 716, in _get_metadata_opts
    old_stream, new_stream = self.get_stream_number(info['filepath'], ('tags', 'mimetype'), 'application/json')
  File "c:\<py39_path>\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 231, in get_stream_number
    streams = self.get_metadata_object(path)['streams']
KeyError: 'streams'
```

## Description

As far as I can tell, FFProbe isn't finding the the files it was provided by yt-dlp for some reason (not passing the dir correctly?), it worked for the full channel but a few videos had this exact issue

Videos IDs that had this issue for me (not all 28, just some):
```
LA3NP8SrOBM (The one used in the log above)
4qhsDeNH3pI
WccUIyGsMMY
e1yswFq5Xdk
mBX5zscxdcI
```

What I could think happened is some filename encoding issue or something that has to do with Arabic text, but I'm not really sure as other videos worked fine, just a few that kept having this exact issue (not matter how much I tried), and I've verified that the files actually exist and that I'm updated to the latest (10.10.2021 as of now)

There was no mention of this issue anywhere I've looked, I searched with keywords but the only thing that was close was #871 but it was still for an entirely different issue (mine isn't about a problem with muxing tracks... probably)

Hopefully I did the bug reporting right

**Comment by pukkandan** [comment]
The filename is too long. Use a shorter output template

**Comment by VXsz** [comment]
> The filename is too long. Use a shorter output template

is there a way to make a "backup" filename format in case this happens instead of just completely changing the template? as having such an issue could be pretty problematic for bulk archiving like in my case, perhaps I'd miss one video where it errored out without me realizing it and thus having an actually incomplete archive, and this happened for like %3 of the videos... which is  a bit high for such a thing

also, the audio and videos tracks are all being downloaded correctly even through they are the same length... shouldn't the temp file be possible then (it's even one character short than `template.quality(f249.. etc).webm`)? perhaps this is more of an ffmpeg issue of not being able to create as long of a filename in windows
