### ISSUE TITLE
[Broken] MGTOW.TV: Cannot download audio-only version

### ISSUE THREAD

**Issue by csehszlovakze** [yt-dlp/yt-dlp#1282]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

listing formats:

```
$ yt-dlp -vF https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html
[debug] Command-line config: ['-vF', 'https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.10.10 (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-144-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Downloading webpage
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Extracting information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Godgevlamste ~ Ground Zero: Rebuilding Giza
[generic] playlist Godgevlamste ~ Ground Zero: Rebuilding Giza: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[info] Available formats for godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl:
ID   EXT RESOLUTION | PROTO | VCODEC  ACODEC
---- --- ---------- - ----- - ------- -------
mp3  mp4 unknown    | https | unknown unknown
240p mp4 240p       | https | unknown unknown
360p mp4 360p       | https | unknown unknown
480p mp4 480p       | https | unknown unknown
[download] Finished downloading playlist: Godgevlamste ~ Ground Zero: Rebuilding Giza
```

trying to download mp3 file: **ERROR**

```
$ yt-dlp -vf mp3 https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html
[debug] Command-line config: ['-vf', 'mp3', 'https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.10.10 (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-144-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Downloading webpage
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Extracting information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Godgevlamste ~ Ground Zero: Rebuilding Giza
[generic] playlist Godgevlamste ~ Ground Zero: Rebuilding Giza: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
ERROR: [generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Requested format is not available
Traceback (most recent call last):
  File "/home/csehszlovakze/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1263, in wrapper
    return func(self, *args, **kwargs)
  File "/home/csehszlovakze/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1612, in __process_iterable_entry
    entry, download=download, extra_info=extra_info)
  File "/home/csehszlovakze/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1351, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/csehszlovakze/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2346, in process_video_result
    video_id=info_dict['id'], ie=info_dict['extractor'])
yt_dlp.utils.ExtractorError: [generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Requested format is not available

[download] Finished downloading playlist: Godgevlamste ~ Ground Zero: Rebuilding Giza
```

requesting mp3 file URL: **ERROR**

```
$ yt-dlp -vgf mp3 https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html[debug] Command-line config: ['-vgf', 'mp3', 'https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.10.10 (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-144-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Downloading webpage
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Extracting information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Godgevlamste ~ Ground Zero: Rebuilding Giza
[generic] playlist Godgevlamste ~ Ground Zero: Rebuilding Giza: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
ERROR: [generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Requested format is not available
Traceback (most recent call last):
  File "/home/csehszlovakze/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1263, in wrapper
    return func(self, *args, **kwargs)
  File "/home/csehszlovakze/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1612, in __process_iterable_entry
    entry, download=download, extra_info=extra_info)
  File "/home/csehszlovakze/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1351, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/csehszlovakze/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2346, in process_video_result
    video_id=info_dict['id'], ie=info_dict['extractor'])
yt_dlp.utils.ExtractorError: [generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Requested format is not available

[download] Finished downloading playlist: Godgevlamste ~ Ground Zero: Rebuilding Giza
```

trying to download 480p video: success

```
$ yt-dlp -vf 480p https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html
[debug] Command-line config: ['-vf', '480p', 'https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.10.10 (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-144-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Downloading webpage
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Extracting information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Godgevlamste ~ Ground Zero: Rebuilding Giza
[generic] playlist Godgevlamste ~ Ground Zero: Rebuilding Giza: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[info] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Downloading 1 format(s): 480p
[debug] Invoking downloader on "https://cdn.mgtow.tv/upload/videos/2021/10/D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_480p_converted.mp4"
[download] Destination: Godgevlamste ~ Ground Zero - Rebuilding Giza [godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl].mp4
[download] 100% of 44.14MiB in 00:22                 
[download] Finished downloading playlist: Godgevlamste ~ Ground Zero: Rebuilding Giza
```

requesting mp4 (480p) file URL: success

```
$ yt-dlp -vgf 480p https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html
[debug] Command-line config: ['-vgf', '480p', 'https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.10.10 (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-144-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Downloading webpage
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Extracting information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Godgevlamste ~ Ground Zero: Rebuilding Giza
[generic] playlist Godgevlamste ~ Ground Zero: Rebuilding Giza: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[info] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Downloading 1 format(s): 480p
https://cdn.mgtow.tv/upload/videos/2021/10/D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_480p_converted.mp4
[download] Finished downloading playlist: Godgevlamste ~ Ground Zero: Rebuilding Giza

```

HTML5 video element:

```
<video id="my-video_html5" style="width: 799.323px; height: 100%; position: relative;" poster="https://cdn.mgtow.tv/upload/photos/2021/10/da74907a117f1b73f2bbbe60d4a409f194b79d396s2GyeWECW8mRMElx1qm.video_thumb_8452_11.jpeg" preload="none" src="https://cdn.mgtow.tv/upload/videos/2021/10/D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_audio_converted.mp3">
    <source src="https://cdn.mgtow.tv/upload/videos/2021/10/D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_audio_converted.mp3" type="video/mp4" data-quality="mp3" title="mp3" label="mp3" res="mp3">
    <source src="https://cdn.mgtow.tv/upload/videos/2021/10/D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_240p_converted.mp4" type="video/mp4" data-quality="240p" title="240p" label="240p" res="240">
    <source src="https://cdn.mgtow.tv/upload/videos/2021/10/D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_360p_converted.mp4" type="video/mp4" data-quality="360p" title="360p" label="360p" res="360">
    <source src="https://cdn.mgtow.tv/upload/videos/2021/10/D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_480p_converted.mp4" type="video/mp4" data-quality="480p" title="480p" label="480p" res="480">
Your browser does not support HTML5 video.
    <!-- //src="http://www.youtube.com/watch?v=nOEw9iiopwI" type="video/youtube" -->
</video>
```

getting audio manually by URL from element: success

```
$ wget https://cdn.mgtow.tv/upload/videos/2021/10/D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_audio_converted.mp3
--2021-10-15 14:28:12--  https://cdn.mgtow.tv/upload/videos/2021/10/D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_audio_converted.mp3
Resolving cdn.mgtow.tv (cdn.mgtow.tv)... 144.217.69.43
Connecting to cdn.mgtow.tv (cdn.mgtow.tv)|144.217.69.43|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13314853 (13M) [audio/mpeg]
Saving to: ‘D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_audio_converted.mp3’

D3ixuhLVTZwkFC6kKYRM_15_c7c01ec9 100%[=======================================================>]  12.70M  2.73MB/s    in 9.6s    

2021-10-15 14:28:22 (1.33 MB/s) - ‘D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_audio_converted.mp3’ saved [13314853/13314853]

$ file D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_audio_converted.mp3                                        
D3ixuhLVTZwkFC6kKYRM_15_c7c01ec99a37fef92da018e29517fd97_video_audio_converted.mp3: Audio file with ID3 version 2.4.0, contains:MPEG ADTS, layer III, v1,  64 kbps, 44.1 kHz, Stereo    
```

## Description

Cannot download nor stream the audio-only version of any video via yt-dlp (nor old youtube-dl), but getting the file URL manually and downloading with wget works as expected.

Misc info: MGTOW.TV is running on a customized PlayTube CMS instance. (I'm not the owner of either.)

**Comment by Ashish0804** [comment]
```
ID   EXT RESOLUTION | PROTO | VCODEC  ACODEC
---- --- ---------- - ----- - ------- -------
mp3  mp4 unknown    | https | unknown unknown
240p mp4 240p       | https | unknown unknown
360p mp4 360p       | https | unknown unknown
480p mp4 480p       | https | unknown unknown
```
Look carefully, there's no `mp3` format to choose

**Comment by Ashish0804** [comment]
When you use `-f mp3` it assumes that u want mp3 extension and since none of the formats have it, it errors out. (it will choose 480p if u use `-f mp4`)

Therefore you will have to choose it by explicitly mentioning that u want the format_id to be mp3 using this 
` -f best[format_id='mp3']`

```shell
C:\Users\Ashish\Desktop> yt-dlp -f best[format_id='mp3'] 'https://www.mgtow.tv/watch/godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl.html'
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Downloading webpage
[generic] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Extracting information
[download] Downloading playlist: ⁣Godgevlamste ~ Ground Zero: Rebuilding Giza
[generic] playlist ⁣Godgevlamste ~ Ground Zero: Rebuilding Giza: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[info] godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl: Downloading 1 format(s): mp3
[download] Resuming download at byte 325632
[download] Destination: ⁣Godgevlamste ~ Ground Zero - Rebuilding Giza [godgevlamste-ground-zero-rebuilding-giza_AYCGRjVDWRm6Tzl].mp4
[download]   4.4% of 12.70MiB at 179.34KiB/s ETA 01:09
ERROR: Interrupted by user
```
Btw since the site is not supported, it's better to open a site request for this so proper format_id can be given to the formats.

**Comment by pukkandan** [comment]
What we can do is to make sure the `id` and `ext` never conflicts. Would that be an acceptable fix?
