### ISSUE TITLE
Assertion error with patched ffmpeg

### ISSUE THREAD

**Issue by tmczar** [yt-dlp/yt-dlp#1295]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
$ yt-dlp --ffmpeg-location "/home/tmczar/Downloads/ffmpeg-n4.4-179-g3cd95ba078-linux64-gpl-4.4/bin/" --verbose "https://www.youtube.com/watch?v=OFRjZtYs3wY"
[debug] Command-line config: ['--ffmpeg-location', '/home/tmczar/Downloads/ffmpeg-n4.4-179-g3cd95ba078-linux64-gpl-4.4/bin/', '--verbose', 'https://www.youtube.com/watch?v=OFRjZtYs3wY']
[debug] User config file: /home/tmczar/.config/yt-dlp/config
[debug] User config: ['--output=%(title)s_(%(id)s)_[%(resolution)s].%(ext)s', '--sub-lang=en,pl,en-GB,en-US', '--format=bestvideo[height<=?1080]+bestaudio/best[height<=?1080],bestvideo[height>1080]+bestaudio/best[height>1080]', '--prefer-free-formats', '--merge-output-format', 'mkv', '--no-mtime', '--add-metadata', '--embed-subs', '--no-call-home', '--no-overwrites', '--sponsorblock-mark', 'all', '--sponsorblock-remove', 'sponsor', '--concurrent-fragments', '4', '--abort-on-error', '--throttled-rate', '100K']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.10 (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-88-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg n4.4-179-g3cd95ba078-20211015, ffprobe n4.4-179-g3cd95ba078-20211015, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Crypto, keyring, sqlite
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=OFRjZtYs3wY
[youtube] OFRjZtYs3wY: Downloading webpage
[youtube] OFRjZtYs3wY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[debug] Downloading subtitles: en
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/dc8e?service=YouTube&categories=%5B%22intro%22%2C+%22interaction%22%2C+%22preview%22%2C+%22outro%22%2C+%22music_offtopic%22%2C+%22selfpromo%22%2C+%22sponsor%22%5D
[SponsorBlock] Found 2 segments in the SponsorBlock database
[info] OFRjZtYs3wY: Downloading 2 format(s): 248+251, 313+251
[info] Writing video subtitles to: Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=OFRjZtYs3wY&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1634353001&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=EA97BB2633719621950C97172FD78CDF4A34642F.2A2C86C310D2C90742CA08217DD1D817E5E47488&key=yt8&lang=en&fmt=vtt"
[download] Destination: Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].en.vtt
[download] 100% of 15.14KiB in 00:00      
[download] Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].mkv has already been downloaded
[debug] ffprobe command line: /home/tmczar/Downloads/ffmpeg-n4.4-179-g3cd95ba078-linux64-gpl-4.4/bin/ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].mkv'
[EmbedSubtitle] Embedding subtitles in "Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].mkv"
[debug] ffmpeg command line: /home/tmczar/Downloads/ffmpeg-n4.4-179-g3cd95ba078-linux64-gpl-4.4/bin/ffmpeg -y -loglevel repeat+info -i 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].mkv' -i 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].en.vtt' -c copy -map 0 -dn -map -0:s -map -0:d -map 1:0 -metadata:s:s:0 language=eng -metadata:s:s:0 handler_name=English -metadata:s:s:0 title=English 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].temp.mkv'
Deleting original file Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].en.vtt (pass -k to keep)
[ModifyChapters] There are no matching SponsorBlock chapters
[Metadata] Adding metadata to "Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].mkv"
[debug] ffmpeg command line: /home/tmczar/Downloads/ffmpeg-n4.4-179-g3cd95ba078-linux64-gpl-4.4/bin/ffmpeg -y -loglevel repeat+info -i 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].mkv' -i 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].meta' -map 0 -dn -c copy -map_metadata 1 -metadata 'title=Why The Web Is Such A Mess' -metadata date=20201123 -metadata 'description=Tim Berners-Lee envisioned a "universal information system". What went wrong? • MORE BASICS: https://www.youtube.com/playlist?list=PL96C35uN7xGLLeET0dOWaKHkAlPsrkcha

Written with Sean Elliott https://twitter.com/SeanMElliott/ • Camera by Tomek • Graphics by William Marler https://wmad.co.uk

I'"'"'m at https://tomscott.com
on Twitter at https://twitter.com/tomscott
on Facebook at https://facebook.com/tomscott
and on Instagram as tomscottgo' -metadata 'synopsis=Tim Berners-Lee envisioned a "universal information system". What went wrong? • MORE BASICS: https://www.youtube.com/playlist?list=PL96C35uN7xGLLeET0dOWaKHkAlPsrkcha

Written with Sean Elliott https://twitter.com/SeanMElliott/ • Camera by Tomek • Graphics by William Marler https://wmad.co.uk

I'"'"'m at https://tomscott.com
on Twitter at https://twitter.com/tomscott
on Facebook at https://facebook.com/tomscott
and on Instagram as tomscottgo' -metadata 'purl=https://www.youtube.com/watch?v=OFRjZtYs3wY' -metadata 'comment=https://www.youtube.com/watch?v=OFRjZtYs3wY' -metadata 'artist=Tom Scott' 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[1920x1080].temp.mkv'
[info] Writing video subtitles to: Why The Web Is Such A Mess_(OFRjZtYs3wY)_[3840x2160].en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=OFRjZtYs3wY&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1634353001&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=EA97BB2633719621950C97172FD78CDF4A34642F.2A2C86C310D2C90742CA08217DD1D817E5E47488&key=yt8&lang=en&fmt=vtt"
[download] Destination: Why The Web Is Such A Mess_(OFRjZtYs3wY)_[3840x2160].en.vtt
[download] 100% of 15.14KiB in 00:00      
[download] Why The Web Is Such A Mess_(OFRjZtYs3wY)_[3840x2160].mkv has already been downloaded
[debug] ffprobe command line: /home/tmczar/Downloads/ffmpeg-n4.4-179-g3cd95ba078-linux64-gpl-4.4/bin/ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[3840x2160].mkv'
[EmbedSubtitle] Embedding subtitles in "Why The Web Is Such A Mess_(OFRjZtYs3wY)_[3840x2160].mkv"
[debug] ffmpeg command line: /home/tmczar/Downloads/ffmpeg-n4.4-179-g3cd95ba078-linux64-gpl-4.4/bin/ffmpeg -y -loglevel repeat+info -i 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[3840x2160].mkv' -i 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[3840x2160].en.vtt' -c copy -map 0 -dn -map -0:s -map -0:d -map 1:0 -metadata:s:s:0 language=eng -metadata:s:s:0 handler_name=English -metadata:s:s:0 title=English 'file:Why The Web Is Such A Mess_(OFRjZtYs3wY)_[3840x2160].temp.mkv'
Deleting original file Why The Web Is Such A Mess_(OFRjZtYs3wY)_[3840x2160].en.vtt (pass -k to keep)
[ModifyChapters] There are no matching SponsorBlock chapters
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 779, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 769, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2897, in download
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1255, in extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1263, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1301, in __extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1351, in process_ie_result
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2361, in process_video_result
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2867, in process_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3025, in post_process
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2968, in run_pp
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 21, in run
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 108, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/modify_chapters.py", line 42, in run
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/modify_chapters.py", line 231, in _remove_marked_arrange_sponsors
AssertionError

```

## Description

I am aware ffmpeg/sponsorblock situation and using newest patched build of ffmpeg, but i'm getting not really helpful "AssertionError", that i could not find in any issue in this repository, so i think it may be something real.

Error is exactly the same for standard ffmpeg version.

**Comment by xtkoba** [comment]
This can be closed immediately because the template is ignored.

That said, the assertion comes from here: https://github.com/yt-dlp/yt-dlp/blob/8063de51097a7af719c7a8c95b8f7c097573046f/yt_dlp/postprocessor/modify_chapters.py#L231
