### ISSUE TITLE
[Crunchyroll] Data must be padded to 16 byte boundary in CBC mode

### ISSUE THREAD

**Issue by stefanodvx** [yt-dlp/yt-dlp#1297]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
C:\Users\Administrator\Desktop\test>yt-dlp "https://pl.crunchyroll.com/evs1/efca
d1ad1a410c436cdb4e4e75f45e9c/assets/7d8e5fd54383b0dfa1d4494f4f62fd88_4158429.mp4
/index-v1-a1.m3u8?Expires=1634476086&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoi
aHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9lZmNhZDFhZDFhNDEwYzQzNmNkYjRlNGU3NWY0
NWU5Yy9hc3NldHMvN2Q4ZTVmZDU0MzgzYjBkZmExZDQ0OTRmNGY2MmZkODhfKi5tM3U4PyoiLCJDb25k
aXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzQ0NzYwODZ9fX1dfQ__&Sig
nature=HpuOqo5GSRSfF22H8Uh19eVS2OSz5VpqIF0TlLsf1FPzxXyrhuhE1WCKe2ndS4Sj3YrVNyj25
bFs1Vf7Ll~8COchStOdqXtnXsHiUhkJfiVhB49x174iaGnR-w3LG4-pbmgzeEDGl9DFuprGLf6MItVt5
xe0SgUv8CjIAayeo~kcRaptDrIe6z7v-5hqJSgYt0Ms0GYzuRNhKory0EQ6-CPJY6GrfCBIappUw1Iz2
SXoM0sjyKxCOyLVU08Hf50pObXbHCR6wmQUrCpGa5OUDD8u3TH0mDySNeeidMYn-mlkh-0i4mR1cIriF
Vqnb0xQ0pDL-uLaJiayh19eVcwMXQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod" --
downloader aria2c --downloader-args "aria2c:-j 100" -o out.mp4 --verbose
[debug] Command-line config: ['https://pl.crunchyroll.com/evs1/efcad1ad1a410c436
cdb4e4e75f45e9c/assets/7d8e5fd54383b0dfa1d4494f4f62fd88_4158429.mp4/index-v1-a1.
m3u8?Expires=1634476086&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wb
C5jcnVuY2h5cm9sbC5jb20vZXZzMS9lZmNhZDFhZDFhNDEwYzQzNmNkYjRlNGU3NWY0NWU5Yy9hc3Nld
HMvN2Q4ZTVmZDU0MzgzYjBkZmExZDQ0OTRmNGY2MmZkODhfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiR
GF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzQ0NzYwODZ9fX1dfQ__&Signature=HpuOqo
5GSRSfF22H8Uh19eVS2OSz5VpqIF0TlLsf1FPzxXyrhuhE1WCKe2ndS4Sj3YrVNyj25bFs1Vf7Ll~8CO
chStOdqXtnXsHiUhkJfiVhB49x174iaGnR-w3LG4-pbmgzeEDGl9DFuprGLf6MItVt5xe0SgUv8CjIAa
yeo~kcRaptDrIe6z7v-5hqJSgYt0Ms0GYzuRNhKory0EQ6-CPJY6GrfCBIappUw1Iz2SXoM0sjyKxCOy
LVU08Hf50pObXbHCR6wmQUrCpGa5OUDD8u3TH0mDySNeeidMYn-mlkh-0i4mR1cIriFVqnb0xQ0pDL-u
LaJiayh19eVcwMXQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod', '--downloader'
, 'aria2c', '--downloader-args', 'aria2c:-j 100', '-o', 'out.mp4', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.10.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-2012ServerR2-6.3.9600-SP
0
[debug] exe versions: ffmpeg git-2020-04-03-52523b6
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = False, stderr = False
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://pl.crunchyroll.com/evs1/efcad1ad1a410c
436cdb4e4e75f45e9c/assets/7d8e5fd54383b0dfa1d4494f4f62fd88_4158429.mp4/index-v1-
a1.m3u8?Expires=1634476086&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly
9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9lZmNhZDFhZDFhNDEwYzQzNmNkYjRlNGU3NWY0NWU5Yy9hc3
NldHMvN2Q4ZTVmZDU0MzgzYjBkZmExZDQ0OTRmNGY2MmZkODhfKi5tM3U4PyoiLCJDb25kaXRpb24iOn
siRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzQ0NzYwODZ9fX1dfQ__&Signature=Hpu
Oqo5GSRSfF22H8Uh19eVS2OSz5VpqIF0TlLsf1FPzxXyrhuhE1WCKe2ndS4Sj3YrVNyj25bFs1Vf7Ll~
8COchStOdqXtnXsHiUhkJfiVhB49x174iaGnR-w3LG4-pbmgzeEDGl9DFuprGLf6MItVt5xe0SgUv8Cj
IAayeo~kcRaptDrIe6z7v-5hqJSgYt0Ms0GYzuRNhKory0EQ6-CPJY6GrfCBIappUw1Iz2SXoM0sjyKx
COyLVU08Hf50pObXbHCR6wmQUrCpGa5OUDD8u3TH0mDySNeeidMYn-mlkh-0i4mR1cIriFVqnb0xQ0pD
L-uLaJiayh19eVcwMXQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod
[generic] index-v1-a1: Requesting header
[generic] index-v1-a1: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.
2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasau
d, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] index-v1-a1: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://pl.crunchyroll.com/evs1/efcad1ad1a410c43
6cdb4e4e75f45e9c/assets/7d8e5fd54383b0dfa1d4494f4f62fd88_4158429.mp4/index-v1-a1
.m3u8?Expires=1634476086&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9w
bC5jcnVuY2h5cm9sbC5jb20vZXZzMS9lZmNhZDFhZDFhNDEwYzQzNmNkYjRlNGU3NWY0NWU5Yy9hc3Nl
dHMvN2Q4ZTVmZDU0MzgzYjBkZmExZDQ0OTRmNGY2MmZkODhfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsi
RGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzQ0NzYwODZ9fX1dfQ__&Signature=HpuOq
o5GSRSfF22H8Uh19eVS2OSz5VpqIF0TlLsf1FPzxXyrhuhE1WCKe2ndS4Sj3YrVNyj25bFs1Vf7Ll~8C
OchStOdqXtnXsHiUhkJfiVhB49x174iaGnR-w3LG4-pbmgzeEDGl9DFuprGLf6MItVt5xe0SgUv8CjIA
ayeo~kcRaptDrIe6z7v-5hqJSgYt0Ms0GYzuRNhKory0EQ6-CPJY6GrfCBIappUw1Iz2SXoM0sjyKxCO
yLVU08Hf50pObXbHCR6wmQUrCpGa5OUDD8u3TH0mDySNeeidMYn-mlkh-0i4mR1cIriFVqnb0xQ0pDL-
uLaJiayh19eVcwMXQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 748
[download] Destination: out.mp4
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-int
erval=0" "--download-result=hide" "--file-allocation=none" -x16 -j16 -s16 "--all
ow-overwrite=true" "--allow-piece-length-change=true" --header "User-Agent: Mozi
lla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chr
ome/74.0.3729.19 Safari/537.36" --header "Accept-Charset: ISO-8859-1,utf-8;q=0.7
,*;q=0.7" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.
9,*/*;q=0.8" --header "Accept-Encoding: gzip, deflate" --header "Accept-Language
: en-us,en;q=0.5" "--check-certificate=true" "--remote-time=true" -j 100 "--auto
-file-renaming=false" "--file-allocation=none" "--uri-selector=inorder" -i out.m
p4.part.frag.urls
[DL:0B][#e78762 0B/0B][#0c2b39 0B/0B][#1ef225 0B/0B][#aa763a 0B/0B]ERROR: Data m
ust be padded to 16 byte boundary in CBC mode
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1263, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1301, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1351, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2361, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2800, in process_info
  File "yt_dlp\YoutubeDL.py", line 2508, in dl
  File "yt_dlp\downloader\common.py", line 397, in download
  File "yt_dlp\downloader\hls.py", line 254, in real_download
  File "yt_dlp\downloader\external.py", line 40, in real_download
  File "yt_dlp\downloader\external.py", line 154, in _call_downloader
  File "yt_dlp\downloader\fragment.py", line 358, in decrypt_fragment
  File "yt_dlp\aes.py", line 12, in aes_cbc_decrypt_bytes
  File "Cryptodome\Cipher\_mode_cbc.py", line 246, in decrypt
ValueError: Data must be padded to 16 byte boundary in CBC mode

```

## Description

I tried downloading a m3u8 stream using aria2c external download, everything went good, but when the program was about to merge all the fragments, i got this error. If i remove ffmpeg from the dir i dont get any error, otherwise the fragments doesnt merge to the final mp4 file

**Comment by pukkandan** [comment]
@stefanodvx You will get it in the next release

**Comment by stefanodvx** [comment]
> @stefanodvx You will get it in the next release

Ok, i actually installed git version of yt-dlp, so the problem should be fixed, but it isn't. here's the verbose log:

```
C:\Users\Administrator\Desktop\crRipper>yt-dlp "https://pl.crunchyroll.com/evs1/
efcad1ad1a410c436cdb4e4e75f45e9c/assets/7d8e5fd54383b0dfa1d4494f4f62fd88_4158429
.mp4/index-v1-a1.m3u8?Expires=1634557830&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNl
IjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9lZmNhZDFhZDFhNDEwYzQzNmNkYjRlNGU3
NWY0NWU5Yy9hc3NldHMvN2Q4ZTVmZDU0MzgzYjBkZmExZDQ0OTRmNGY2MmZkODhfKi5tM3U4PyoiLCJD
b25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzQ1NTc4MzB9fX1dfQ__
&Signature=VItMuJgb6KwK5r8d1cEyV1Y~dj7tyKTb8JqJBOo5Jas2ctVxp9zs-3iEyFxCe3~5P4zOs
RLAw53GBrwvoIAEMbNaNGRwsbuoyPbc7xD36dcFsxfMIpbFDoTs7CZ0qVljoCU5vxSQKu-jyVmLc54ax
PoEj49s6KvWq4fHlA2deFnljY0cJD1p5zylFR6nE3E1Xf0HhjDX3sJPgLqvw6oRUcocFypogwhzYh-ce
NJLwiJ6TbAtkUEaAeC6BazFSMBM2h-k88MBX7fyInL7I294puCYxsV1RyK6JVBp24~QYql7TXyZ-HnT9
dsTYBglQScIHwi2oEyBwSI0ajgn5KgqDQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod
" --downloader aria2c --downloader-args "aria2c:-j 100" -o out.mp4 --verbose
[debug] Command-line config: ['https://pl.crunchyroll.com/evs1/efcad1ad1a410c436
cdb4e4e75f45e9c/assets/7d8e5fd54383b0dfa1d4494f4f62fd88_4158429.mp4/index-v1-a1.
m3u8?Expires=1634557830&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wb
C5jcnVuY2h5cm9sbC5jb20vZXZzMS9lZmNhZDFhZDFhNDEwYzQzNmNkYjRlNGU3NWY0NWU5Yy9hc3Nld
HMvN2Q4ZTVmZDU0MzgzYjBkZmExZDQ0OTRmNGY2MmZkODhfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiR
GF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzQ1NTc4MzB9fX1dfQ__&Signature=VItMuJ
gb6KwK5r8d1cEyV1Y~dj7tyKTb8JqJBOo5Jas2ctVxp9zs-3iEyFxCe3~5P4zOsRLAw53GBrwvoIAEMb
NaNGRwsbuoyPbc7xD36dcFsxfMIpbFDoTs7CZ0qVljoCU5vxSQKu-jyVmLc54axPoEj49s6KvWq4fHlA
2deFnljY0cJD1p5zylFR6nE3E1Xf0HhjDX3sJPgLqvw6oRUcocFypogwhzYh-ceNJLwiJ6TbAtkUEaAe
C6BazFSMBM2h-k88MBX7fyInL7I294puCYxsV1RyK6JVBp24~QYql7TXyZ-HnT9dsTYBglQScIHwi2oE
yBwSI0ajgn5KgqDQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod', '--downloader'
, 'aria2c', '--downloader-args', 'aria2c:-j 100', '-o', 'out.mp4', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, stdout utf-8, stderr utf-8, pref cp1
252
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.9.7 (CPython 64bit) - Windows-2012ServerR2-6.3.9600-SP0

[debug] exe versions: ffmpeg git-2020-04-03-52523b6
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = False, stderr = False
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://pl.crunchyroll.com/evs1/efcad1ad1a410c
436cdb4e4e75f45e9c/assets/7d8e5fd54383b0dfa1d4494f4f62fd88_4158429.mp4/index-v1-
a1.m3u8?Expires=1634557830&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly
9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9lZmNhZDFhZDFhNDEwYzQzNmNkYjRlNGU3NWY0NWU5Yy9hc3
NldHMvN2Q4ZTVmZDU0MzgzYjBkZmExZDQ0OTRmNGY2MmZkODhfKi5tM3U4PyoiLCJDb25kaXRpb24iOn
siRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzQ1NTc4MzB9fX1dfQ__&Signature=VIt
MuJgb6KwK5r8d1cEyV1Y~dj7tyKTb8JqJBOo5Jas2ctVxp9zs-3iEyFxCe3~5P4zOsRLAw53GBrwvoIA
EMbNaNGRwsbuoyPbc7xD36dcFsxfMIpbFDoTs7CZ0qVljoCU5vxSQKu-jyVmLc54axPoEj49s6KvWq4f
HlA2deFnljY0cJD1p5zylFR6nE3E1Xf0HhjDX3sJPgLqvw6oRUcocFypogwhzYh-ceNJLwiJ6TbAtkUE
aAeC6BazFSMBM2h-k88MBX7fyInL7I294puCYxsV1RyK6JVBp24~QYql7TXyZ-HnT9dsTYBglQScIHwi
2oEyBwSI0ajgn5KgqDQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod
[generic] index-v1-a1: Requesting header
[generic] index-v1-a1: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.
2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasau
d, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] index-v1-a1: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://pl.crunchyroll.com/evs1/efcad1ad1a410c43
6cdb4e4e75f45e9c/assets/7d8e5fd54383b0dfa1d4494f4f62fd88_4158429.mp4/index-v1-a1
.m3u8?Expires=1634557830&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9w
bC5jcnVuY2h5cm9sbC5jb20vZXZzMS9lZmNhZDFhZDFhNDEwYzQzNmNkYjRlNGU3NWY0NWU5Yy9hc3Nl
dHMvN2Q4ZTVmZDU0MzgzYjBkZmExZDQ0OTRmNGY2MmZkODhfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsi
RGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzQ1NTc4MzB9fX1dfQ__&Signature=VItMu
Jgb6KwK5r8d1cEyV1Y~dj7tyKTb8JqJBOo5Jas2ctVxp9zs-3iEyFxCe3~5P4zOsRLAw53GBrwvoIAEM
bNaNGRwsbuoyPbc7xD36dcFsxfMIpbFDoTs7CZ0qVljoCU5vxSQKu-jyVmLc54axPoEj49s6KvWq4fHl
A2deFnljY0cJD1p5zylFR6nE3E1Xf0HhjDX3sJPgLqvw6oRUcocFypogwhzYh-ceNJLwiJ6TbAtkUEaA
eC6BazFSMBM2h-k88MBX7fyInL7I294puCYxsV1RyK6JVBp24~QYql7TXyZ-HnT9dsTYBglQScIHwi2o
EyBwSI0ajgn5KgqDQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 748
[download] Destination: out.mp4
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-int
erval=0" "--download-result=hide" "--file-allocation=none" -x16 -j16 -s16 "--all
ow-overwrite=true" "--allow-piece-length-change=true" --header "User-Agent: Mozi
lla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chr
ome/70.0.3521.2 Safari/537.36" --header "Accept-Charset: ISO-8859-1,utf-8;q=0.7,
*;q=0.7" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9
,*/*;q=0.8" --header "Accept-Encoding: gzip, deflate" --header "Accept-Language:
 en-us,en;q=0.5" "--check-certificate=true" "--remote-time=true" -j 100 "--auto-
file-renaming=false" "--file-allocation=none" "--uri-selector=inorder" -i out.mp
4.part.frag.urls
[DL:13MiB][#e50d1f 1.2MiB/1.6MiB(75%)][#18418c 1.2MiB/1.4MiB(84%)][#6f6e76 1.1ER
ROR: Data must be padded to 16 byte boundary in CBC mode
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\YoutubeDL.py", line 1265, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\YoutubeDL.py", line 1303, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\YoutubeDL.py", line 1353, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\YoutubeDL.py", line 2371, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\YoutubeDL.py", line 2805, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\YoutubeDL.py", line 2518, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\downloader\common.py", line 397, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\downloader\hls.py", line 254, in real_download
    return fd.real_download(filename, info_copy)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\downloader\external.py", line 40, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\downloader\external.py", line 161, in _call_downloader
    dest.write(decrypt_fragment(fragment, src.read()))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\downloader\fragment.py", line 358, in decrypt_fragment
    decrypted_data = aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv
)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\yt_dlp\aes.py", line 12, in aes_cbc_decrypt_bytes
    return compat_pycrypto_AES.new(key, compat_pycrypto_AES.MODE_CBC, iv).decryp
t(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\Cryptodome\Cipher\_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % sel
f.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode
```

The tracebake is different, but the error is the same.

**Comment by Jules-A** [comment]
This issue is not fixed on the Native downloader, network errors cause it but trying to resume the download will keep failing afterwards even if your network is fine (I disabled network adapter to test).

**Comment by dirkf** [comment]
The underlying problem is that the Crypto/Cryptodome `AES.en/de/crypt()` APIs require a full block in CBC mode, where the caller has to provide the padding.

The Python `aes_cbc_encrypt()` implementation in aes.py does apply padding (PKCS7 by default), though not upstream as yet. If that function is optimised in terms of `AES.encrypt()`, the plaintext must be padded.
 
Since ciphertext should have been generated by the above encryption, one might wonder why padding should be necessary for decryption. Maybe the additional padding block of 16 0x10 bytes (PKCS7) is not being added to the last full block from the encoder, or perhaps the padding could be stripped in some way in transmission. But it's plainly necessary to ensure padding for ciphertext too, and none of the decryption implementations does that.

Unlike #1298, which reimplements PKCS7 padding and the block size of AES-CBC, the additional padding should either be implemented in the en/de/cryption function defined in aes.py, or use utility functions exported from there.

**Comment by dirkf** [comment]
See also analysis at https://github.com/yt-dlp/yt-dlp/issues/3578#issuecomment-1134110546 and below.

**Comment by entourage8** [comment]
@stefanodvx @Jules-A
Please try the patch in the PR linked above. If it still doesn't work then please run `yt-dlp` with the `--write-pages` flag and provide the playlist `index-v1-a1.m3u8`.

**Comment by bashonly** [comment]
Closing this since video is no longer downloadable from this site
