### ISSUE TITLE
[Broken] youtube: urlopen error EOF occurred in violation of protocol (_ssl.c:1131)

### ISSUE THREAD

**Issue by alectprasad** [yt-dlp/yt-dlp#1307]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --external-downloader aria2c --external-downloader-args "-j 8 -s 8 -x 8 -k 5M" --cookies youtube.com_cookies.txt -v https://www.youtube.com/watch?v=cvsz6oUAcLI
[debug] Command-line config: ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio', '--merge-output-format', 'mp4', '--external-downloader', 'aria2c', '--external-downloader-args', '-j 8 -s 8 -x 8 -k 5M', '--cookies', 'youtube.com_cookies.txt', '-v', 'https://www.youtube.com/watch?v=cvsz6oUAcLI']
WARNING: --downloader-args given without specifying name. The arguments will be given to all external downloaders
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.8.10 (CPython 64bit) - Linux-4.4.0-22000-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=cvsz6oUAcLI
[youtube] cvsz6oUAcLI: Downloading webpage
[youtube] cvsz6oUAcLI: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] cvsz6oUAcLI: Downloading 1 format(s): 137+140
[debug] Invoking downloader on "https://r3---sn-3jja-jv3s.googlevideo.com/videoplayback?expire=1634419374&ei=Tu5qYeemJPWd4t4P2fqA4AY&ip=103.165.167.93&id=o-ACXI2nF1gs8YTVynqF14yS0icvfi2jw7pzUqirQtgGN8&itag=137&source=youtube&requiressl=yes&mh=v5&mm=31%2C29&mn=sn-3jja-jv3s%2Csn-h5576nee&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=24&pcm2=yes&initcwndbps=667500&vprv=1&mime=video%2Fmp4&gir=yes&clen=585662766&dur=1426.057&lmt=1562783433831447&mt=1634397428&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=2316222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgDGbMAMY9lM_tnzmuAIproPvm-nFt5vWYHenPodHX6msCIQCVqcuKPFXSwcUfhliF7aWkxV8fO8DYwfrNyUGr8dQLiA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANzeGFMbbUennk7pvFBJ2pmWm6_-x0Ot5rb7o81VOE-8AiAUHBc_geU3ODUpE7GlZqE5LkjJdoGQCqMtOB8ZPfBPTw%3D%3D"
[download] Destination: HUNTER HARDEN on HE'S FIT [cvsz6oUAcLI].f137.mp4
[download]   5.2% of 558.53MiB at 656.55KiB/s ETA 13:45ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1421, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2783, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/user/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2508, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/user/.local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 397, in download
    ret = self.real_download(filename, info_dict)
  File "/home/user/.local/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 370, in real_download
    establish_connection()
  File "/home/user/.local/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 120, in establish_connection
    raise err
  File "/home/user/.local/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 114, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/user/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3228, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/user/.local/lib/python3.8/site-packages/yt_dlp/utils.py", line 2849, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>

```

**Comment by alectprasad** [comment]
yes

**Comment by alectprasad** [comment]
same thing

**Comment by alectprasad** [comment]
working with vpn

**Comment by pukkandan** [comment]
Then it's definitely issue with your local CDN. Nothing we can do
