### ISSUE TITLE
[Broken] Website Name: Certificate error when trying to download from Tele5

### ISSUE THREAD

**Issue by arminfuerst** [yt-dlp/yt-dlp#1334]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.10.10**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones
- [X] I've read the opening an issue section in CONTRIBUTING.md
- [X] I have given an appropriate title to the issue

## Verbose log

```
[Tele5] das-zepter: Downloading webpage
[JWPlatform] Kca7WjNI: Downloading JSON metadata
[JWPlatform] Kca7WjNI: Downloading m3u8 information
WARNING: [JWPlatform] Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
ERROR: [JWPlatform] Kca7WjNI: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
armin@armin-pc:~/tmp/RH$ youtube-dl -v https://www.tele5.de/relic-hunter/ganze-folge/das-zepter/
[debug] Command-line config: ['--write-thumbnail', '--write-description', '-v', 'https://www.tele5.de/relic-hunter/ganze-folge/das-zepter/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-9-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] Using fake IP 53.8.135.83 (DE) as X-Forwarded-For
[debug] [Tele5] Extracting URL: https://www.tele5.de/relic-hunter/ganze-folge/das-zepter/
[Tele5] das-zepter: Downloading webpage
[debug] [JWPlatform] Extracting URL: jwplatform:Kca7WjNI#__youtubedl_smuggle=%7B%22geo_countries%22%3A+%5B%22DE%22%5D%7D
[debug] Using fake IP 53.123.131.84 (DE) as X-Forwarded-For
[JWPlatform] Kca7WjNI: Downloading JSON metadata
[JWPlatform] Kca7WjNI: Downloading m3u8 information
WARNING: [JWPlatform] Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
ERROR: [JWPlatform] Kca7WjNI: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1263, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1301, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1351, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2218, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 873, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [JWPlatform] Kca7WjNI: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Downloading from Tele5 seems to be impossible because of a certificate error. When using the parameter `--no-check-certificate`, the download is working properly.
A URL to test this issue is `https://www.tele5.de/relic-hunter/ganze-folge/das-zepter/`. Tele5 has a geoprotection, it is still no problem to use the URL for testing as the certificate error occurs before the geoprotection. If the response 403 is received, this is because of the geoprotection.

**Comment by pukkandan** [comment]
It appears to be connecting to the right server 😕 
```
"sources":[{"file":"https://tele5.akamaized.net/B1012483_c0ee75fc037b12e508e572cf6d411412/manifest.m3u8",
```

**Comment by pukkandan** [comment]
can u open the python3 interpreter and try running this?
```
import socket, ssl
addr = 'tele5.akamaized.net'
ssl.create_default_context().wrap_socket(socket.create_connection((addr, 443), timeout=20), server_hostname=addr).getpeercert()
```

**Comment by arminfuerst** [comment]
> No, as I not in the same country.

For testing, this doesn't matter. If you get a 403 error, the certificate is regarded as valid, so this would be a "good case".

**Comment by marillat** [comment]
OK, got a 403.
I also tested the code from https://github.com/yt-dlp/yt-dlp/issues/1334#issuecomment-946140206  in python3 3.9.2 (Debian bullseye)  and this code works.
```
[Tele5] das-zepter: Downloading webpage
[JWPlatform] Kca7WjNI: Downloading JSON metadata
[JWPlatform] Kca7WjNI: Downloading m3u8 information
WARNING: [JWPlatform] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [JWPlatform] Kca7WjNI: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by arminfuerst** [comment]
In case someone is interested, I found the reason why it was not working:
In `/etc/ssl/certs`, the link `3513523f.0 -> DigiCert_Global_Root_CA.pem` was missing.
Additionally, one of my first tries to fix the issue was to reinstall package `ca-certificates`. This did not solve the issue, because following link existed: `DigiCert_Global_Root_CA.pem -> /usr/share/ca-certificates/mozilla/DigiCert_Global_Root_CA.crt`. After having removed this link and reinstalled the package, the verification is working now.
Thanks for your help!
