### ISSUE TITLE
Rtve.es Play

### ISSUE THREAD

**Issue by Jiriss** [yt-dlp/yt-dlp#1346]
The list of the supported sites say that Rtve Alacarta has supported. This site has replaced with Rtve Play and extractor doesn't work with new site. Please could you add support for Rtve Play? This is example to video https://www.rtve.es/play/videos/comando-actualidad/

**Comment by hansworzt** [comment]
Any video on RTVE Play - geo-restricted or not - can be downloaded with "yt-dlp", but currently requires some additional steps:

> 1) Copy the program URL to https://www.piraminetlab.com/ to generate the video URL.
Example program URL: https://www.rtve.es/play/videos/somos-cine/somos-cine-altamira/5621023/
Results in video URL: https://rtve-mediavod.secure.footprint.net/resources/TE_GLESP/mp4/7/4/1594294885247.mp4?nvb=20211030172651&nva=20211030232651&token=047dbe539d7132ff9bc98

> 2) This geo-restricted video only plays in Spain.
Transform into the non geo-restricted URL:
https://rtve-hlsvod.secure.footprint.net/resources/TE_NGVA/mp4/7/4/1594294885247.mp4/playlist.m3u8?idasset=5621023

> 3) yt-dlp -F ... shows the available formats, etc.

No doubt some Python wizzard could implement this into an extractor.

**Comment by hansworzt** [comment]
> 
> 
> Someone suggested replacing /play/ for /alacarta/ in the URL. After that, I'm getting a "Payment Required" error with this video: https://www.rtve.es/alacarta/videos/la-caza/caza-monteperdido-capitulo-1-deshielo/5092259/

This transformed URL works just fine:
https://rtve-hlsvod.secure.footprint.net/resources/TE_NGVA/mp4/8/9/1553557872798.mp4/playlist.m3u8?idasset=5092259

**Comment by Jiriss** [comment]
When will the yt-dlp project be added this change to the production?

**Comment by Jiriss** [comment]
It isn't work anymore with the latest version 2022.03.08.1 although using workground replacing /play/ for /alacarta/ in the URL. Output listed below

$ yt-dlp --version
2022.03.08.1

$ yt-dlp -F https://www.rtve.es/alacarta/videos/telediario-2/telediario-21-horas-10-03-22/6431098/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 615, in extract
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 523, in initialize
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/rtve.py", line 73, in _real_initialize
KeyError: 'User-Agent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 647, in extract
yt_dlp.utils.ExtractorError: 6431098: An extractor error has occurred. (caused by KeyError('User-Agent')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 864, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 854, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3254, in download
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3227, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1380, in extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1407, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'

**Comment by hansworzt** [comment]
They changed it so new streams can no longer be downloaded. The https://www.piraminetlab.com/ site that used to offer the URLs of RTVE programmes is thus basically dead. To alleviate this never ending cat-and-mouse game, use software that can record played streams. I use TubeDigger (payware) for this. No matter what they change from now on, if it plays in a web browser it will be recorded losslessly with this software.

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl/pull/29816

**Comment by dirkf** [comment]
>... This is example to video https://www.rtve.es/play/videos/comando-actualidad/

But the actual episode that you can play from that page: https://www.rtve.es/play/videos/comando-actualidad/abandonados-bancos/6459510/

The corresponding series page: https://www.rtve.es/play/videos/modulos/capitulos/11332/?currentpage=pf_serie, from which we need to harvest these elements:
`<a class="goto_media" href="https://www.rtve.es/play/videos/comando-actualidad/abandonados-bancos/6459510/" title="Empezar a ver">`.

**Comment by alexanderadam** [comment]
Apart from the `play` vs `alacarta` issue, it's also not possible to fetch/embed the subtitles.
Is this related or should I create a new issue for this?

**Comment by mildsunrise** [comment]
I've tried all links to videos mentioned in this issue (except https://www.rtve.es/play/videos/comando-actualidad/, which as pointed by @dirkf is NOT the link to a video, but to a show's landing page), and I can confirm they all work with https://github.com/ytdl-org/youtube-dl/pull/31241 applied (from a spanish IP)

**Comment by Jiriss** [comment]
Support for rtve.es is still unavailable

$ yt-dlp --version
2022.10.04

Tested with European IP address but outside of Spain.

$ yt-dlp -v -F https://www.rtve.es/play/videos/telediario-2/21-horas-04-10-22/6706793/
[debug] Command-line config: ['-v', '-F', 'https://www.rtve.es/play/videos/telediario-2/21-horas-04-10-22/6706793/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-126-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, pycrypto-2.6.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [generic] Extracting URL: https://www.rtve.es/play/videos/telediario-2/21-horas-04-10-22/6706793/
[generic] 6706793: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 6706793: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.rtve.es/play/videos/telediario-2/21-horas-04-10-22/6706793/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3062, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.rtve.es/play/videos/telediario-2/21-horas-04-10-22/6706793/

Situation is same although replaced /play/ with /alacarta/ in the URL.

$ yt-dlp -v -F https://www.rtve.es/alacarta/videos/telediario-2/21-horas-04-10-22/6706793/
[debug] Command-line config: ['-v', '-F', 'https://www.rtve.es/alacarta/videos/telediario-2/21-horas-04-10-22/6706793/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-126-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, pycrypto-2.6.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[rtve.es:alacarta] Fetching manager info
[debug] [rtve.es:alacarta] Extracting URL: https://www.rtve.es/alacarta/videos/telediario-2/21-horas-04-10-22/6706793/
[rtve.es:alacarta] 6706793: Downloading JSON metadata
[rtve.es:alacarta] 6706793: Downloading url information
ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/rtve.py", line 144, in _real_extract
    formats = self._extract_png_formats(video_id)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/rtve.py", line 118, in _extract_png_formats
    for quality, video_url in self._decrypt_url(png):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/rtve.py", line 81, in _decrypt_url
    quality, url_data = text.split(b'%%')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by dincel** [comment]
I don't know how you apply this to your script codes but I found a manual way of extract rtve.es/play content on Celluloid player;
sample URL: https://www.rtve.es/play/videos/carlos-rey-emperador/carlos-rey-emperador-capitulo-1/3312421/

1. While playing the media, goto devtools (F12) > Network tab and search for ".m3u8" (refresh with F5 if necessary)
there will be two results:
https://rtvehlsvodlote7.rtve.es/mediavodv2/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4/video.m3u8?hls_no_audio_only=true&idasset=3312421
https://rtvehlsvodlote7.rtve.es/mediavodv2/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4/1641318615695-audio=192975-video=2759000.m3u8?idasset=3312421
2. take either one and remove the part after .mp4
3. change the URL's "https://rtvehlsvodlote7.rtve.es/mediavodv2/" part to "https://mediavod-lvlt.rtve.es/" (domain at the download links for radio RNE content) resulting the final working URL: https://mediavod-lvlt.rtve.es/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4
4. Now the subtitles. As in step (1) this time search for ".vtt" and directly copy the link "https://www.rtve.es/resources/vtt/0/3/1648225256930.vtt" (you don't have to download it)
add both links to your in your text editor and save as .m3u playlist (e.g. play.m3u) . Like this;
...
https://mediavod-lvlt.rtve.es/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4
https://www.rtve.es/resources/vtt/0/3/1648225256930.vtt
...
5. When you open Celluloid player it only plays .mp4 file. And you can copy the .vtt link address from the playlist items (F9) and open it wiht Ctrl + L shortcut. This will activate while playing, subtitles too.

This seems a bit player specific in the and but at least I found a way to retrieve both video and subs.
But manually it takes too long. It is up to you programmers to apply this workaround to yt-dlp API and allow us to watch shows directly from the visible URLs like https://www.rtve.es/play/videos/carlos-rey-emperador/carlos-rey-emperador-capitulo-1/3312421/

**Comment by hansworzt** [comment]
There's a simpler manual method that maybe automated:

1) Copy the page URL: https://www.rtve.es/play/videos/carlos-rey-emperador/carlos-rey-emperador-capitulo-1/3312421/

2) Put this into https://www.descargavideos.tv/ and hit the search button.

3) Hit "Descargar (opción 1, supuestamente sin geobloqueo".
This displays the video and shows the direct URL :
https://mediavod-lvlt.rtve.es/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4
A shorter URL that doesn't bother with certificates is:
http://www.rtve.es/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4
This can be downloaded with:
yt-dlp -f mp4 http://www.rtve.es/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4
Or with:
wget http://www.rtve.es/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4
There's another button on the "Descargar" page that gives you the direct subtitles link.

**Comment by pabgan** [comment]
@hansworzt I thought I might give that a try and came up with https://gitlab.com/pabgan/rtve-dl

You can dowload specific videos 

```
./rtve-dl  https://www.rtve.es/play/videos/la-corona-magica/corona-magica-cristal-hansto/2663281/
```

or complete series:

```
./rtve-dl  --coleccion https://www.rtve.es/play/videos/la-corona-magica/
```

When I have time I might try to include this functionality into yt-dlp itself, but right now I really wanted this and it was quicker to create this script from scratch.

**Comment by Lol274** [comment]
Maybe this is a bit of off-topic, but I got this link from rtve with a bunch more that played the videos but now it does not due to a IP issue

https://rtve-hlsvod.secure.footprint.net/resources/TE_GLESP/mp4/3/0/1479563027703.mp4/playlist.m3u8

Maybe this now probably doesn't have any solution, but if there is, how I can fix it? Thank you

**Comment by Jiriss** [comment]
@pabgan These links doesn't work outside Spain

**Comment by pabgan** [comment]
hmm you mean the ones I pasted in my previous comment or those that the script I created generates?

Because if you mean those in my comment there is not much I can do about it, if you can't access those probably you will not want to use that script. The other problem might be workaroundable.

**Comment by Jiriss** [comment]
@pabgan Sorry for the misunderstanding. Earlier I tested the links via www.descargavideos.tv and links behind the "Opción 1 (Sin geobloqueo. No funciona)" didn't work. I continued testing and noticed that links behind the  "Opción 3 (Sin geobloqueo. No funciona)" ja "Opción 4 (Sin geobloqueo. No funciona)" also work outside Spain.

The newest version of the yt-dlp can't show direct video links from RTVE Play at least outside Spain.

**Comment by pabgan** [comment]
OK, I can make the script try those links in order until one works... But I can not tell you when :)

**Comment by VinceLeone** [comment]
@pabgan : Could you add to your script the possibility to download the subtitles?
With this line I could extract the vtt url subtitle:

`curl --silent --data "web=${link}" 'https://www.descargavideos.tv' | grep vtt | cut --delimiter='"' --fields=6`

Thanks for your work.

**Comment by meGAmeS1** [comment]
By the way, I worked on an extractor a while ago that solves this issue and adds RTVE Play in yt-dlp (supports multiple audio tracks and subtitles, and it doesn't need an external service like descargavideos.tv, though you need to have access to the video in case it is geo-restricted so you may have to use a VPN if you're outside Spain). Sadly it hasn't been merged already (you may support it by putting 👍 or ❤️ on it) : https://github.com/yt-dlp/yt-dlp/pull/10388.

The only thing is it doesn't support collection (yet) but I may add it as I already reversed engineer their API

**Comment by meGAmeS1** [comment]
> @meGAmeS1 : I just tried to get a video with multiaudio (it's available only with movies) but I only get the same id types that in my post earlier but it's in fact the same audio language. Have you found a solution with that?
> 
> P.S. By the way, thanks for your work. It's now integrated in the stable version.

Hi. Glad my work helps people! The video you're trying to download is [this one](https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/)? I'm currently on my phone but I can't take look tonight or tomorrow

**Comment by VinceLeone** [comment]
No I tried a movie that has 2 audios (original english and spanish dub) like this : https://www.rtve.es/play/videos/cine-internacional/aisha/15972529/
The series, live shows, tv programs are only in spanish audio.

> ```
>[rtve.es:alacarta] Extracting URL: https://www.rtve.es/play/videos/cine-internacional/aisha/15972529/
>[rtve.es:alacarta] 15972529: Downloading JSON metadata
>[rtve.es:alacarta] 15972529: Downloading url information
>[rtve.es:alacarta] 15972529: Downloading m3u8 information
>[rtve.es:alacarta] 15972529: Downloading MPD manifest
>[rtve.es:alacarta] 15972529: Downloading url information
>[rtve.es:alacarta] 15972529: Downloading m3u8 information
>[rtve.es:alacarta] 15972529: Downloading MPD manifest
>[info] Available formats for 15972529:
>ID                  EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
>────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>dash-audio=193341-0 m4a audio only     │ ~125.02MiB  193k dash  │ audio only        mp4a.40.2  193k 48k DASH audio, m4a_dash
>dash-audio=193341-1 m4a audio only     │ ~125.02MiB  193k dash  │ audio only        mp4a.40.2  193k 48k DASH audio, m4a_dash
>2                   mp4 unknown        │                  http  │ unknown           unknown
>3                   mp4 unknown        │                  http  │ unknown           unknown
>dash-video=2750000  mp4 1280x720    25 │ ~  1.74GiB 2750k dash  │ avc1.640029 2750k video only          DASH video, mp4_dash
>hls-3120            mp4 1280x720    25 │ ~  1.97GiB 3120k m3u8  │ avc1.640029 2750k mp4a.40.2  193k
>dash-video=4500000  mp4 1920x1080   25 │ ~  2.84GiB 4500k dash  │ avc1.640029 4500k video only          DASH video, mp4_dash
>hls-4975            mp4 1920x1080   25 │ ~  3.14GiB 4975k m3u8  │ avc1.640029 4500k mp4a.40.2  193k

the dash audio 193341-0 and 193341-1 are exactly the same spanish dub audio. But in the web RTVE Play when watching the video you can select the original english audio.

**Comment by meGAmeS1** [comment]
@VinceLeone So, I've managed to have time to look into your issue and as I supposed, this is the same stuff that happened to an other member that wanted to download both audio tracks with different languages: the content you see in the browser is DRM protected, the content retrieved by yt-dlp isn't.

First of all, and sadly, the code that was recently merged won't allow you to download both languages, and only Spanish will be available (and we're kinda lucky that is available). The reason is that what yt-dlp allows you to download isn't exactly the same content you see in the RTVE webpage. What you see in your browser is DRM protected, and as yt-dlp cannot be used to infringe copyright ([as written in its guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy)) we only retrieve non encrypted content through RTVE APIs. The fact that RTVE decides to distribute DRM protected content also via its non protected APIs is kinda lucky I guess and might change in the future. Also it's up to RTVE to decide which content should be protected or not (mainly their content from their own programs isn't protected, and that content they buy from elsewhere is DRM protected).

Second of all, "DRM protected" doesn't mean that the protection isn't removable. They use Widevine, and there are many ways to retrieve the keys that protect the content but we won't discuss about it here 🙃

**Comment by VinceLeone** [comment]
Ok thanks for the response. I didn't think about that some parts of the content was DRM and others don't.
Thanks to clarify it.
