### ISSUE TITLE
Live stream TF1.FR not detected (with solution)

### ISSUE THREAD

**Issue by loby66** [yt-dlp/yt-dlp#1381]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.10.10**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

- live stream not detected  with https://www.tf1.fr/tf1/direct

### Description

live stream not detected  with https://www.tf1.fr/tf1/direct 

**Solution in Perl to get the MPD url :**

> $ua->get("https://mediainfo.tf1.fr/mediainfocombo/L_TF1?context=MYTF1&pver=4001000");
> 	$content=$response->content;
> 
> 	($url)=$content=~/\,\"url\"\:\"([^\"]+\.mpd)\"/mi;

### Verbose log

```shell
yt-dlp -U
yt-dlp is up to date (2021.10.10)

yt-dlp -Uv "https://www.tf1.fr/tf1/direct"
[debug] Command-line config: ['-Uv', 'https://www.tf1.fr/tf1/direct']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.7.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-09-16-git-8f92a1862a-essentials_build-www.gyan.dev, ffprobe 2021-09-16-git-8f92a1862a-essentials_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.10)
[debug] [generic] Extracting URL: https://www.tf1.fr/tf1/direct
[generic] direct: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] direct: Downloading webpage
[generic] direct: Extracting information
ERROR: [generic] Unsupported URL: https://www.tf1.fr/tf1/direct
Traceback (most recent call last):
  File "C:\Users\mezodia\AppData\Roaming\Python\Python37\site-packages\yt_dlp\extractor\common.py", line 589, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\mezodia\AppData\Roaming\Python\Python37\site-packages\yt_dlp\extractor\generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tf1.fr/tf1/direct
Traceback (most recent call last):
  File "C:\Users\mezodia\AppData\Roaming\Python\Python37\site-packages\yt_dlp\extractor\common.py", line 589, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\mezodia\AppData\Roaming\Python\Python37\site-packages\yt_dlp\extractor\generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tf1.fr/tf1/direct

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mezodia\AppData\Roaming\Python\Python37\site-packages\yt_dlp\YoutubeDL.py", line 1263, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\mezodia\AppData\Roaming\Python\Python37\site-packages\yt_dlp\YoutubeDL.py", line 1288, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\mezodia\AppData\Roaming\Python\Python37\site-packages\yt_dlp\extractor\common.py", line 606, in extract
    e.msg, video_id=video_id, ie=self.IE_NAME, tb=e.traceback, expected=e.expected, cause=e.cause)
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.tf1.fr/tf1/direct
```

**Comment by MarwenDallel** [comment]
I plan on fixing some of the issues related to TF1.FR and I found that the extractor for WAT.TV, with some minor modifications, works perfectly to get the live feed. WAT has also been shutdown in favor of MY TF1. Should I add a new InfoExtractor in tf1.py and make the necessary changes to remove all references to WAT.TV from the code?

**Comment by pukkandan** [comment]
Yes, and you can delete wat.py if the service is shutdown

**Comment by MarwenDallel** [comment]
So I've worked on this for a bit and it turns out that whenever someone is geo-blocked, the `geoList` returned by https://mediainfo.tf1.fr/mediainfocombo/L_TF1?context=MYTF1 contains [FX](https://www.iso.org/obp/ui/#iso:code:3166:FX) which is an "exceptionally reserved" country code. It is still part of the ISO3166 standard as you can see here: [Country Codes Collection](https://www.iso.org/obp/ui/#iso:pub:PUB500001:en), more specifically ISO3166-3 which is a list of country codes that have been removed from ISO3166-1. In this case, `FX` was merged into the more commonly used `FR`.

The country map in `ISO3166Utils` only takes into account officially assigned code elements. Whenever I invoke `raise_geo_restricted` with the aforementioned geoList, I get the following error:
 `TypeError: sequence item 2: expected str instance, NoneType found`

Should the country map be extended to include codes from the ISO3166-3 standard or should I just manually replace FX with FR for this case as it is the only reserved code in geoList (at least for now)?

**Comment by pukkandan** [comment]
You can extend the list

**Comment by MarwenDallel** [comment]
Turns out some ISO3166-1 and ISO3166-3 alpha-2 codes overlap but can refer to a completely different territory (e.g. [SK](https://www.iso.org/obp/ui/#iso:code:3166:SK) used to refer to Sikkim and is now used for Slovakia). 
I was thinking of using two maps instead of one. The second one is a historic country map that acts as a fallback lookup table for whenever the code is not found in `_country_map`.

```py
@classmethod
def short2full(cls, code):
    """Convert an ISO 3166-2 country code to the corresponding full name"""
    return cls._country_map.get(code.upper()) or cls._historic_country_map.get(code.upper())
```

For now I'm getting the iso codes from [pycountry ](https://github.com/flyingcircusio/pycountry/tree/master/src/pycountry/databases) since it's surprisingly difficult to find a reliable source for ISO3166-3 codes.

**Comment by pukkandan** [comment]
> The second one is a historic country map that acts as a fallback lookup table for whenever the code is not found in _country_map.

That is effectively the same adding codes to the dict iff they have no conflict with existing codes

**Comment by MarwenDallel** [comment]
Indeed, I just wanted to create one map for each part of the ISO3166 standard (ISO3166-1 and ISO3166-3) so that it is easier to tell which one conforms to which standard for future developers.
I guess I will just add a comment to clarify and I will merge both by giving priority to alpha-2 codes from ISO3166-1.
I appreciate the quick responses!

**Comment by Totorrr** [comment]
Hello @MarwenDallel, and thank you for working on this. I was about to open the issue myself when I saw yours. :)

Would you please include the TMC live stream also (https://www.tf1.fr/tmc/direct) in your work? I suppose, because it is from the same tf1.fr website, that it can be included pretty easily. 

Thanks!

**Comment by MarwenDallel** [comment]
Hey @Totorrr, I've looked into it and added support for all live streams (tf1, tfx, tmc, lci and tf1 series films).
My only issue is that FFmpeg is acting up and throwing several errors. 
It starts by throwing errors related to the stream_index
![image](https://user-images.githubusercontent.com/71770363/164793911-c32dca9e-44ff-4402-bda2-54db42354f1a.png)
Followed by DTS errors once it gets past the first few seconds of the live stream.
![image](https://user-images.githubusercontent.com/71770363/164794029-6fadc0c0-3dd6-4ef3-8b10-f1c0232ad008.png)

I have tested several versions of FFmpeg (4.2.1, 5.0.1 and n5.0.1-4) with the same results. I have also tried different parameters (including `-copytb 1` and `-fflags +igndts`) with no success. This happens even if I download the audio only or the video only and results in a corrupt (but playable) output file. 

You can reproduce the error by calling FFmpeg with the MPD file returned by [https://mediainfo.tf1.fr/mediainfocombo/L_TF1?context=MYTF1](https://mediainfo.tf1.fr/mediainfocombo/L_TF1?context=MYTF1).

Since this issue seems to be unrelated to yt-dlp, I am not sure if I should make a PR or not.
