### ISSUE TITLE
peer.tv site request

### ISSUE THREAD

**Issue by nobruinfo** [yt-dlp/yt-dlp#1388]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

europe

### Example URLs

- Single video: https://www.peer.tv/de/841

### Description

Thank you for considering adding this site. And thank you again for this fantastic tool with its thousands of useful uses.

### Verbose log

```Batchfile
D:\portable programmes\Tools\FFMPEG>yt-dlp.exe -Uv --no-check-certificate https://www.peer.tv/de/841
[debug] Command-line config: ['-Uv', '--no-check-certificate', 'https://www.peer.tv/de/841']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev (setts), ffprobe 4.4-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [generic] Extracting URL: https://www.peer.tv/de/841
[generic] 841: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 841: Downloading webpage
[generic] 841: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.peer.tv/de/841
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1336, in __extract_info
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\generic.py", line 3766, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.peer.tv/de/841
```

**Comment by nobruinfo** [comment]
Updated verbose output to match current version 2021.11.10.1
