### ISSUE TITLE
Mail.ru not support --downloader *

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#1406]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://my.mail.ru/v/fresh_movie/video/_groupvideo/244.html

### Description

Hello, i tried many way and apps downloader can support but can't use it for hoster mail.ru. I have already aria2c in same location of yt-dlp. Can you check it?

```
C:\Users\Administrator>yt-dlp -Uv "https://my.mail.ru/v/fresh_movie/video/_groupvideo/244.html" --downloader aria2c
[debug] Command-line config: ['-Uv', 'https://my.mail.ru/v/fresh_movie/video/_groupvideo/244.html', '--downloader', 'aria2c']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [mailru] Extracting URL: https://my.mail.ru/v/fresh_movie/video/_groupvideo/244.html
[mailru] v/fresh_movie/_groupvideo/244: Downloading webpage
[mailru] v/fresh_movie/_groupvideo/244: Downloading video meta JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 55437080_244: Downloading 1 format(s): 720p
[debug] Invoking downloader on "http://cdn64.my.mail.ru/hv/55437080.mp4?slave[]=s%3Ahttp%3A%2F%2Fvideo-cephgw1.i%3A8002%2Frados2%2F55437080-hv&p=f&expire_at=1635112800&touch=1439554794&reg=243&sign=102aec87037305002a1320a4d282abe90d8d698a"
[download] Resuming download at byte 673792143
[download] Destination: Контрабанда [55437080_244].mp4
[download]  47.7% of 1.48GiB at 664.72KiB/s ETA 20:20
```

**Comment by swayll** [comment]
Download Error. [Video is public](https://my.mail.ru/mail/ael.grei/video/_myvideo/365.html).
```
 yt-dlp -vU --cookies /Volumes/VIDEOS/mailru.txt https://my.mail.ru/mail/ael.grei/video/_myvideo/365.html
[debug] Command-line config: ['-vU', '--cookies', '/Volumes/VIDEOS/mailru.txt', 'https://my.mail.ru/mail/ael.grei/video/_myvideo/365.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (darwin_legacy_exe)
[debug] Python 3.10.5 (CPython 64bit) - macOS-10.13.6-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-tessus (setts), ffprobe 5.0.1-tessus
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [mailru] Extracting URL: https://my.mail.ru/mail/ael.grei/video/_myvideo/365.html
[mailru] mail/ael.grei/_myvideo/365: Downloading webpage
[mailru] mail/ael.grei/_myvideo/365: Downloading video meta JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 73793349_365: Downloading 1 format(s): 720p
[debug] Invoking http downloader on "http://cdn18.my.mail.ru/v/73793349.mp4?slave[]=s%3Ahttp%3A%2F%2Fvideo-cephgw2.i%3A8002%2Frados2%2F73793349-v&p=f&expire_at=1660006800&touch=1642556696&reg=188&sign=5a0dc669c44ed1ea9be79b1a1080ba19f6b1d462"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 3160, in process_info
  File "yt_dlp/YoutubeDL.py", line 2860, in dl
  File "yt_dlp/downloader/common.py", line 444, in download
  File "yt_dlp/downloader/http.py", line 375, in real_download
  File "yt_dlp/downloader/http.py", line 131, in establish_connection
  File "yt_dlp/YoutubeDL.py", line 3639, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 634, in http_response
  File "urllib/request.py", line 563, in error
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Change HTTP to HTTPS
`http://cdn18.my.mail.ru/v/73793349.mp4?slave[]=s%3Ahttp%3A%2F%2Fvideo-cephgw2.i%3A8002%2Frados2%2F73793349-v&p=f&expire_at=1660006800&touch=1642556696&reg=188&sign=5a0dc669c44ed1ea9be79b1a1080ba19f6b1d462` -> `https://cdn18.my.mail.ru/v/73793349.mp4?slave[]=s%3Ahttp%3A%2F%2Fvideo-cephgw2.i%3A8002%2Frados2%2F73793349-v&p=f&expire_at=1660006800&touch=1642556696&reg=188&sign=5a0dc669c44ed1ea9be79b1a1080ba19f6b1d462`
Work fine.
