### ISSUE TITLE
https://mediaklikk.hu

### ISSUE THREAD

**Issue by sk8ordi3** [yt-dlp/yt-dlp#1409]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Hungary

### Example URLs

https://mediaklikk.hu/cikk/a-hasonmas (**date limit**, sometimes couple days and remove the video)
https://mediaklikk.hu/musor/filmtar/
https://mediaklikk.hu/cikk/2017/12/21/maria-terezia-2-resz/ 

### Description

could these sections perhaps be added?
https://mediaklikk.hu/cikk/a-hasonmas
https://mediaklikk.hu/musor/filmtar/
https://mediaklikk.hu/cikk/
https://mediaklikk.hu/cikk/YYYY/MM/DD/
https://mediaklikk.hu/cikk/2017/12/21/maria-terezia-2-resz/ 

now available extractor at https://mediaklikk.hu
there are some videos which are in the article "cikk" e.g:
https://mediaklikk.hu/cikk/a-hasonmas

available here also
https://mediaklikk.hu/musor/filmtar/

or from the main page in the FILMTÁR section (about the bottom of the page)
https://mediaklikk.hu/

opened the page and download the video using m3u8 with no problem (so its looks like no drm protected)
https://mediaklikk.hu/cikk/2017/12/21/maria-terezia-2-resz/ 
(badly this is not direkt link to the video this is an article with embed the video)
https://c401-node62-cdn.connectmedia.hu/4501/vod/_definst_/r/mtva/2018/01/06/2017-027434-M0002-02/index.smil/playlist.m3u8

### Versbose log

```
[debug] Command-line config: ['-v', '--no-progress', 'https://mediaklikk.hu/cikk/a-hasonmas']
[debug] Encodings: locale cp1250, fs utf-8, out cp1250 (No ANSI), err cp1250 (No ANSI), pref cp1250[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://mediaklikk.hu/cikk/a-hasonmas
[generic] a-hasonmas: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] a-hasonmas: Downloading webpage
[generic] a-hasonmas: Extracting information
ERROR: [generic] Unsupported URL: https://mediaklikk.hu/cikk/a-hasonmas
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 593, in extract
  File "yt_dlp\extractor\generic.py", line 3706, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://mediaklikk.hu/cikk/a-hasonmas
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 593, in extract
  File "yt_dlp\extractor\generic.py", line 3706, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://mediaklikk.hu/cikk/a-hasonmas

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1280, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1305, in __extract_info
  File "yt_dlp\extractor\common.py", line 609, in extract
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://mediaklikk.hu/cikk/a-hasonmas
```

```
[debug] Command-line config: ['-v', '--no-progress', 'https://c201-node62-cdn.connectmedia.hu/4501/vod/_definst_/r/mtva/2021/10/16/2018-060574-M0000-02/index.smil/playlist.m3u8']
[debug] Encodings: locale cp1250, fs utf-8, out cp1250 (No ANSI), err cp1250 (No ANSI), pref cp1250[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://c201-node62-cdn.connectmedia.hu/4501/vod/_definst_/r/mtva/2021/10/16/2018-060574-M0000-02/index.smil/playlist.m3u8
[generic] playlist: Requesting header
[generic] playlist: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] playlist: Downloading 1 format(s): 3000
[debug] Invoking downloader on "https://c201-node62-cdn.connectmedia.hu/4501/vod/_definst_/r/mtva/2021/10/16/2018-060574-M0000-02/index.smil/chunklist_w1967350318_b3000000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 534
[download] Destination: playlist [playlist].mp4

ERROR: Interrupted by user
```

since it has been deleted I have added another link which is **still available**:

```
[debug] Command-line config: ['-v', '--no-progress', 'https://mediaklikk.hu/cikk/2017/12/21/maria-terezia-2-resz/']
[debug] Encodings: locale cp1250, fs utf-8, out cp1250 (No ANSI), err cp1250 (No ANSI), pref cp1250[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://mediaklikk.hu/cikk/2017/12/21/maria-terezia-2-resz/
[generic] maria-terezia-2-resz: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] maria-terezia-2-resz: Downloading webpage
[generic] maria-terezia-2-resz: Extracting information
ERROR: [generic] Unsupported URL: https://mediaklikk.hu/cikk/2017/12/21/maria-terezia-2-resz/
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 593, in extract
  File "yt_dlp\extractor\generic.py", line 3706, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://mediaklikk.hu/cikk/2017/12/21/maria-terezia-2-resz/
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 593, in extract
  File "yt_dlp\extractor\generic.py", line 3706, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://mediaklikk.hu/cikk/2017/12/21/maria-terezia-2-resz/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1280, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1305, in __extract_info
  File "yt_dlp\extractor\common.py", line 609, in extract
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://mediaklikk.hu/cikk/2017/12/21/maria-terezia-2-resz/
```

```
[debug] Command-line config: ['-v', '--no-progress', 'https://c401-node62-cdn.connectmedia.hu/4501/vod/_definst_/r/mtva/2018/01/06/2017-027434-M0002-02/index.smil/playlist.m3u8']
[debug] Encodings: locale cp1250, fs utf-8, out cp1250 (No ANSI), err cp1250 (No ANSI), pref cp1250[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://c401-node62-cdn.connectmedia.hu/4501/vod/_definst_/r/mtva/2018/01/06/2017-027434-M0002-02/index.smil/playlist.m3u8
[generic] playlist: Requesting header
[generic] playlist: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] playlist: Downloading 1 format(s): 3000
[debug] Invoking downloader on "https://c401-node62-cdn.connectmedia.hu/4501/vod/_definst_/r/mtva/2018/01/06/2017-027434-M0002-02/index.smil/chunklist_w191256544_b3000000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 614
[download] Destination: playlist [playlist].mp4

ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
There are three cases that are requested:
1. Article with video embed Eg: mediaklikk.hu/cikk/2017/12/21/maria-terezia-2-resz
2. Multi-page article that mat have video embed. Eg: mediaklikk.hu/cikk/a-hasonmas
3. Playlist page. Eg: mediaklikk.hu/musor/filmtar

Of these, only (1) has been added
