### ISSUE TITLE
Unsupported URL error for nationalgeographic.com

### ISSUE THREAD

**Issue by Sorerien** [yt-dlp/yt-dlp#1419]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

I am trying to pass a URL from nationalgeographic.com, but I am recieveing an Unsupported URL error.  The video will play just fine in my browser.  

Here is the URL in question:
https://www.nationalgeographic.com/tv/shows/the-incredible-dr-pol/episode-guide/season-19/episode-01-the-magic-touch/vdka23842525

### Verbose log

```shell
Microsoft Windows [Version 10.0.19042.1288]
(c) Microsoft Corporation. All rights reserved.

F:\Youtube>yt-dlp -Uv https://www.nationalgeographic.com/tv/shows/the-incredible-dr-pol/episode-guide/season-19/episode-01-the-magic-touch/vdka23842525

[debug] Command-line config: ['-Uv', 'https://www.nationalgeographic.com/tv/shows/the-incredible-dr-pol/episode-guide/season-19/episode-01-the-magic-touch/vdka23842525']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2020-10-11-git-7ea4bcff7b-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [generic] Extracting URL: https://www.nationalgeographic.com/tv/shows/the-incredible-dr-pol/episode-guide/season-19/episode-01-the-magic-touch/vdka23842525
[generic] vdka23842525: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] vdka23842525: Downloading webpage
[generic] vdka23842525: Extracting information
ERROR: [generic] Unsupported URL: https://www.nationalgeographic.com/tv/shows/the-incredible-dr-pol/episode-guide/season-19/episode-01-the-magic-touch/vdka23842525
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 593, in extract
  File "yt_dlp\extractor\generic.py", line 3706, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nationalgeographic.com/tv/shows/the-incredible-dr-pol/episode-guide/season-19/episode-01-the-magic-touch/vdka23842525
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 593, in extract
  File "yt_dlp\extractor\generic.py", line 3706, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nationalgeographic.com/tv/shows/the-incredible-dr-pol/episode-guide/season-19/episode-01-the-magic-touch/vdka23842525

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1280, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1305, in __extract_info
  File "yt_dlp\extractor\common.py", line 609, in extract
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.nationalgeographic.com/tv/shows/the-incredible-dr-pol/episode-guide/season-19/episode-01-the-magic-touch/vdka23842525


F:\Youtube>
```

**Comment by pzhlkj6612** [comment]
> https://www.nationalgeographic.com/tv/shows/the-incredible-dr-pol/episode-guide/season-19/episode-01-the-magic-touch/vdka23842525

This link does not work. I've found the "The Incredible Dr. Pol" TV show [^1] on it, though. The site has changed their URL syntax, so for now we need to support the following links:

[^1]: Watch The Incredible Dr. Pol TV Show - Streaming Online | Nat Geo TV https://www.nationalgeographic.com/tv/show/2ef66f46-ce14-412b-83c6-8336ef738fd6

- https://www.nationalgeographic.com/tv/episode/4d4f151b-b8e2-4e56-93dc-637afa14d55f/playlist/PL553044961
- https://www.nationalgeographic.com/tv/episode/97459697-9b6d-4b99-93d7-090724817a06

<br>

In addition, "nationalgeographic" appears to be geo-locked, account required and behind the paywall. Can someone living in the United States watch the above two videos without a valid account? I constantly get this error:

> 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.

.
