### ISSUE TITLE
Chaturbate.com downloads broken

### ISSUE THREAD

**Issue by zulaport** [yt-dlp/yt-dlp#1438]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

Chaturbate seems to have stopped working a few hours ago.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://chaturbate.com/carolina_blush']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.22 (zip)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.7 (CPython 64bit) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.3-tessus, ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [Chaturbate] Extracting URL: https://chaturbate.com/carolina_blush
[Chaturbate] carolina_blush: Downloading webpage
[Chaturbate] carolina_blush: Downloading m3u8 information
WARNING: [Chaturbate] Failed to download m3u8 information: Remote end closed connection without response
ERROR: [Chaturbate] carolina_blush: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/mark/Documents/Development/Github/yt-dlp/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 1310, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/mark/Documents/Development/Github/yt-dlp/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 1348, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/mark/Documents/Development/Github/yt-dlp/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 1398, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/mark/Documents/Development/Github/yt-dlp/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 2272, in process_video_result
    self.raise_no_formats(info_dict)
  File "/Users/mark/Documents/Development/Github/yt-dlp/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 912, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Chaturbate] carolina_blush: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by zulaport** [comment]
Closing: haven't seen any issues in the last day.

**Comment by anoncookie37** [comment]
For anyone else coming across this error, you need to log in to Chaturbate and then pass in those cookies
