### ISSUE TITLE
[Broken] Odysee not working on a video with multiple formats

### ISSUE THREAD

**Issue by GUUser91** [yt-dlp/yt-dlp#146]
## Checklist

- [✓] I'm reporting a broken site support
- [✓] I've verified that I'm running yt-dlp version **2021.03.03.2**
- [✓] I've checked that all provided URLs are alive and playable in a browser
- [✓] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [✓] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```


yt-dlp -v -f 0 https://odysee.com/@NaomiBrockwell:4/Odysee-is-great:a
[debug] Command-line config: ['-v', '-f', '0', 'https://odysee.com/@NaomiBrockwell:4/Odysee-is-great:a']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.03.03.2 
[debug] Python version 3.8.5 (CPython 64bit) - Linux-5.8.0-44-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[lbry] @NaomiBrockwell#4/Odysee-is-great#a: Downloading stream JSON metadata
[lbry] acda1b42a44781285e31c0c8e2a5eb6fc4dc5925: Downloading streaming url JSON metadata
[info] Downloading format(s) 0
[debug] Invoking downloader on 'https://cdn.lbryplayer.xyz/api/v4/streams/free/Odysee-is-great/acda1b42a44781285e31c0c8e2a5eb6fc4dc5925/bc26de'
ERROR: unable to download video data: HTTP Error 308: Permanent Redirect
Traceback (most recent call last):
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2381, in process_info
    success, real_download = dl(temp_filename, info_dict)
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2142, in dl
    return fd.download(name, info, subtitle)
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 375, in download
    return self.real_download(filename, info_dict), True
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 352, in real_download
    establish_connection()
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 117, in establish_connection
    raise err
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 111, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2784, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

yt-dlp -v -F https://odysee.com/@NaomiBrockwell:4/Odysee-is-great:a
[debug] Command-line config: ['-v', '-F', 'https://odysee.com/@NaomiBrockwell:4/Odysee-is-great:a']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.03.03.2 
[debug] Python version 3.8.5 (CPython 64bit) - Linux-5.8.0-44-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[lbry] @NaomiBrockwell#4/Odysee-is-great#a: Downloading stream JSON metadata
[lbry] acda1b42a44781285e31c0c8e2a5eb6fc4dc5925: Downloading streaming url JSON metadata
[info] Available formats for acda1b42a44781285e31c0c8e2a5eb6fc4dc5925:
ID EXT RESOLUTION |  FILESIZE  PROTO | VCODEC  ACODEC
-- --- ---------- - ---------- ----- - ------- -------
0  mp4 1920x1080  |  100.73MiB https | unknown unknown

```

## Description

WRITE DESCRIPTION HERE

**Comment by pukkandan** [comment]
Works for me

```
$ yt-dlp.cmd -v -f 0 https://odysee.com/@NaomiBrockwell:4/Odysee-is-great:a
[debug] Command-line config: ['-v', '-f', '0', 'https://odysee.com/@NaomiBrockwell:4/Odysee-is-great:a']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.03.1 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: a8278abab
[debug] Python version 3.9.2 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[lbry] @NaomiBrockwell#4/Odysee-is-great#a: Downloading stream JSON metadata
[lbry] acda1b42a44781285e31c0c8e2a5eb6fc4dc5925: Downloading streaming url JSON metadata
[info] Downloading format(s) 0
[debug] Invoking downloader on 'https://cdn.lbryplayer.xyz/api/v4/streams/free/Odysee-is-great/acda1b42a44781285e31c0c8e2a5eb6fc4dc5925/bc26de'
[download] Destination: The YouTube Alternative [acda1b42a44781285e31c0c8e2a5eb6fc4dc5925].mp4
[download]   1.0% of 100.73MiB at 981.75KiB/s ETA 01:44
ERROR: Interrupted by user
```

```
$ ./yt-dlp.sh -v -f 0 https://odysee.com/@NaomiBrockwell:4/Odysee-is-great:a
[debug] Command-line config: ['-v', '-f', '0', 'https://odysee.com/@NaomiBrockwell:4/Odysee-is-great:a\r']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.03.03.1 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: a8278abab
[debug] Python version 3.8.5 (CPython 64bit) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[lbry] @NaomiBrockwell#4/Odysee-is-great#a: Downloading stream JSON metadata
[lbry] acda1b42a44781285e31c0c8e2a5eb6fc4dc5925: Downloading streaming url JSON metadata
[info] Downloading format(s) 0
[debug] Invoking downloader on 'https://cdn.lbryplayer.xyz/api/v4/streams/free/Odysee-is-great/acda1b42a44781285e31c0c8e2a5eb6fc4dc5925/bc26de'
[download] Resuming download at byte 1795213
[download] Destination: The YouTube Alternative [acda1b42a44781285e31c0c8e2a5eb6fc4dc5925].mp4
[download]   3.7% of 100.73MiB at  1.08MiB/s ETA 01:29^C
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
@GUUser91 was it just a temporary issue for you, or does the issue still persist?

**Comment by pukkandan** [comment]
Closing due to inactivity
