### ISSUE TITLE
independent.co.uk

### ISSUE THREAD

**Issue by RingoTheDog** [yt-dlp/yt-dlp#1475]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

- Single video: https://www.independent.co.uk/arts-entertainment/music/news/snoop-dogg-olympics-kevin-hart-b1894970.html
- 
- Single video: https://www.independent.co.uk/tv/editors-picks/netflix-dating-show-sexy-beasts-has-nothing-below-the-surface-v0b982027

### Description

[The Independent is a British online newspaper.](https://en.wikipedia.org/wiki/The_Independent) It was established in 1986 as a national morning printed paper. Nicknamed the Indy, it began as a broadsheet and changed to tabloid format in 2003.[4] The last printed edition was published on Saturday 26 March 2016, leaving only the online edition.

### Verbose log

```shell
yt-dlp.py -v "https://www.independent.co.uk/arts-entertainment/music/news/snoop-dogg-olympics-kevin-hart-b1894970.html"
[debug] Command-line config: ['-v', 'https://www.independent.co.uk/arts-entertainment/music/news/snoop-dogg-olympics-kevin-hart-b1894970.html']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.6.6 (CPython 64bit) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.independent.co.uk/arts-entertainment/music/news/snoop-dogg-olympics-kevin-hart-b1894970.html
[generic] snoop-dogg-olympics-kevin-hart-b1894970: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] snoop-dogg-olympics-kevin-hart-b1894970: Downloading webpage
[generic] snoop-dogg-olympics-kevin-hart-b1894970: Extracting information
ERROR: [generic] Unsupported URL: https://www.independent.co.uk/arts-entertainment/music/news/snoop-dogg-olympics-kevin-hart-b1894970.html
Traceback (most recent call last):
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.independent.co.uk/arts-entertainment/music/news/snoop-dogg-olympics-kevin-hart-b1894970.html
Traceback (most recent call last):
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.independent.co.uk/arts-entertainment/music/news/snoop-dogg-olympics-kevin-hart-b1894970.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 610, in extract
    e.msg, video_id=video_id, ie=self.IE_NAME, tb=e.traceback, expected=e.expected, cause=e.cause)
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.independent.co.uk/arts-entertainment/music/news/snoop-dogg-olympics-kevin-hart-b1894970.html
```

**Comment by RingoTheDog** [comment]
thank you!
