### ISSUE TITLE
ServusTV not working

### ISSUE THREAD

**Issue by azteca1337** [yt-dlp/yt-dlp#1490]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria/Europe

### Description

Hey, guys!

According to --list-extractors, Servus is included in the list, but does unfortunately not work properly.
I've been trying to download this documentary:
https://www.servustv.com/volkskultur/v/aa-28jq9b51h1w11/
yt-dlp does download and convert an audio-stream, but **no video**, and then it puts it into a .mp4 file-format all the same.
**VLC**, however, does the exact opposite; it opens a video-stream, but with **no audio**, when I enter the very same link, that I have extracted from the site, and that I also used for yt-dlp.
The latter is pretty odd, since the link contains a folder "audio".
https://dms.redbull.tv/v4/dms/resource/stv/audio/fmp4/AA-28JQ9B51H1W11/de/personal_computer/chrome/at/playlist.m3u8
So, obviously a link to a play-list.

Depending on what download-helper I use with yt-dlp, I do or don't get to see all play-list items during download, which are around a thousand for an end-product of a 53,7MB sized audio-file, but named Play-List.mp4.

Since VLC does get a video stream under this link, both formats, audio and video, should actually be available, but somehow, they don't seem to be accessible to yt-dlp.

Since you're the pros, you will certainly figure it out.
And since this site does broadcast pretty decent documentaries, I'd appreciate it very much, if you'd undergo the effort to fix it!

Thanks in advance, and yours, azteca

### Verbose log

```shell
[debug] Command-line config: ['-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-17-rt-amd64-x86_64-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
```

**Comment by pukkandan** [comment]
The instructions say to add -Uv to **your command**

Run ` yt-dlp -v https://www.servustv.com/videos/aa-28jq9b51h1w11` and show us the output

**Comment by azteca1337** [comment]
That would be:

yt-dlp -v https://www.servustv.com/videos/aa-28jq9b51h1w11
[debug] Command-line config: ['-v', 'https://www.servustv.com/videos/aa-28jq9b51h1w11']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-17-rt-amd64-x86_64-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite
[debug] Proxy map: {}
[debug] [Servus] Extracting URL: https://www.servustv.com/videos/aa-28jq9b51h1w11
[Servus] AA-28JQ9B51H1W11: Downloading token
ERROR: [Servus] aa-28jq9b51h1w11: Unable to download JSON metadata: HTTP Error 401:  (caused by <HTTPError 401: ''>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 702, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3252, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by azteca1337** [comment]
And if I take the original link, that I pasted above, that would be:

yt-dlp -v https://www.servustv.com/volkskultur/v/aa-28jq9b51h1w11/
[debug] Command-line config: ['-v', 'https://www.servustv.com/volkskultur/v/aa-28jq9b51h1w11/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-17-rt-amd64-x86_64-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.servustv.com/volkskultur/v/aa-28jq9b51h1w11/
[generic] aa-28jq9b51h1w11: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] aa-28jq9b51h1w11: Downloading webpage
[generic] aa-28jq9b51h1w11: Extracting information
ERROR: [generic] Unsupported URL: https://www.servustv.com/volkskultur/v/aa-28jq9b51h1w11/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/volkskultur/v/aa-28jq9b51h1w11/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/volkskultur/v/aa-28jq9b51h1w11/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 610, in extract
    e.msg, video_id=video_id, ie=self.IE_NAME, tb=e.traceback, expected=e.expected, cause=e.cause)
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.servustv.com/volkskultur/v/aa-28jq9b51h1w11/

**Comment by chrizilla** [comment]
probably duplicate of #1076 ?

**Comment by pukkandan** [comment]
Thanks. Since there is more info available here, I'll close #1076 instead

**Comment by azteca1337** [comment]
Ok, guys, now further up you said, that this is a duplicate of #1070, and since there is more here, you wanted to close the other one.
But now from the looks of it, this one is closed too?
Wasn't that this one too many, then?

Oh, and I really appreciate it, that after the long time you are still willing to fix it!
Thanks!

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
