### ISSUE TITLE
"Invalid format sort string" when using format_sort in Python program

### ISSUE THREAD

**Issue by xnaas** [yt-dlp/yt-dlp#1492]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

**Describe the bug**
`+` and `:` are not accepted in `format_sort`.

**To Reproduce**
1. Run the below script:
```py
import re
import yt_dlp as youtube_dl


# Download MP4-compatible formats for MP4 container
ytdl_opts = {
    "verbose": True,
    "format": "bestvideo[height<=?1080]+bestaudio/best",
    "format_sort": "+codec:avc:m4a",
    "merge_output_format": "mp4",
    "noplaylist": True,
    "forcejson": True,
    "outtmpl": "./%(id)s.%(ext)s"
}


url = "https://vm.tiktok.com/ZM8mDTq66"


with youtube_dl.YoutubeDL(ytdl_opts) as ytdl:
    print("Processing...")
    meta = ytdl.extract_info(url, download=False)
    id = meta["id"]
    ext = meta["ext"]
    print("Downloading...")
    ytdl.download([url])
    print("{}.{}".format(id, ext))
```
2. Try the above, but with `+` removed. The error simply changes to complaining about `:` instead of `+`.

Note: This is a heavy modification of https://github.com/xnaas/custom-sopel-plugins/blob/master/ytdl.py — but this is enough to show the error.

**Expected behavior**
The above should work the same as running:

```bash
yt-dlp -f "bestvideo[height<=?1080]+bestaudio/best" \
-S "+codec:avc:m4a" https://vm.tiktok.com/ZM8mDTq66
```

**Screenshots**
N/A

### Verbose log

```shell
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-9-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg N-104393-ga59f8ea2a9, ffprobe N-104393-ga59f8ea2a9
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Processing...
[debug] [generic] Extracting URL: https://vm.tiktok.com/ZM8mDTq66
[generic] ZM8mDTq66: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@tk.california/video/7024706090743123247?_d=secCgwIARCbDRjEFSACKAESPgo8ciT80aJoQWprMn8dg38ECwY%2BvPNCa9BCR7uOUra88eoGiI6wHKU9y3us4811RWdot%2FSNdimj6PXUSFEmGgA%3D&language=en&preview_pb=0&sec_user_id=MS4wLjABAAAAi4GjW7K4QMMmhqViyz5YKiC19JEMmn8lXAEwqqq9-e1dOm1o4pv9AX8Nb28HfHS8&share_app_id=1233&share_item_id=7024706090743123247&share_link_id=02cd8f2f-716f-4fd7-86be-57501e00d5c1&source=h5_m&timestamp=1635570881&u_code=e13m01744cc88&user_id=307921461166485504&utm_campaign=client_share&utm_medium=android&utm_source=copy&_r=1
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@tk.california/video/7024706090743123247?_d=secCgwIARCbDRjEFSACKAESPgo8ciT80aJoQWprMn8dg38ECwY%2BvPNCa9BCR7uOUra88eoGiI6wHKU9y3us4811RWdot%2FSNdimj6PXUSFEmGgA%3D&language=en&preview_pb=0&sec_user_id=MS4wLjABAAAAi4GjW7K4QMMmhqViyz5YKiC19JEMmn8lXAEwqqq9-e1dOm1o4pv9AX8Nb28HfHS8&share_app_id=1233&share_item_id=7024706090743123247&share_link_id=02cd8f2f-716f-4fd7-86be-57501e00d5c1&source=h5_m&timestamp=1635570881&u_code=e13m01744cc88&user_id=307921461166485504&utm_campaign=client_share&utm_medium=android&utm_source=copy&_r=1
[TikTok] 7024706090743123247: Downloading video details
WARNING: [TikTok] Invalid format sort string "+" given by extractor; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage
[TikTok] 7024706090743123247: Downloading webpage
[TikTok] 7024706090743123247: Downloading video webpage
ERROR: [TikTok] 7024706090743123247: Invalid format sort string "+" given by extractor; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 365, in _real_extract
    return self._parse_aweme_video_web(props_data['pageProps']['itemInfo']['itemStruct'], url)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 249, in _parse_aweme_video_web
    self._sort_formats(formats)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1783, in _sort_formats
    format_sort.evaluate_params(self._downloader.params, field_preference)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1673, in evaluate_params
    raise ExtractorError('Invalid format sort string "%s" given by extractor' % item)
yt_dlp.utils.ExtractorError: Invalid format sort string "+" given by extractor; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 365, in _real_extract
    return self._parse_aweme_video_web(props_data['pageProps']['itemInfo']['itemStruct'], url)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 249, in _parse_aweme_video_web
    self._sort_formats(formats)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1783, in _sort_formats
    format_sort.evaluate_params(self._downloader.params, field_preference)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1673, in evaluate_params
    raise ExtractorError('Invalid format sort string "%s" given by extractor' % item)
yt_dlp.utils.ExtractorError: Invalid format sort string "+" given by extractor; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 609, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [TikTok] 7024706090743123247: Invalid format sort string "+" given by extractor; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 365, in _real_extract
    return self._parse_aweme_video_web(props_data['pageProps']['itemInfo']['itemStruct'], url)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 249, in _parse_aweme_video_web
    self._sort_formats(formats)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1783, in _sort_formats
    format_sort.evaluate_params(self._downloader.params, field_preference)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1673, in evaluate_params
    raise ExtractorError('Invalid format sort string "%s" given by extractor' % item)
yt_dlp.utils.ExtractorError: Invalid format sort string "+" given by extractor; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 609, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [TikTok] 7024706090743123247: Invalid format sort string "+" given by extractor; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xnaas/sackbot2/tmp/test.py", line 22, in <module>
    meta = ytdl.extract_info(url, download=False)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1272, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1318, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1387, in process_ie_result
    return self.extract_info(
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1272, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1289, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 851, in report_error
    self.trouble(f'{self._color_text("ERROR:", "red")} {message}', tb)
  File "/home/xnaas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 821, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [TikTok] 7024706090743123247: Invalid format sort string "+" given by extractor; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
It should be `"format_sort": ["+codec:avc:m4a"]`

yes, I know the docs arent clear on this. I will update it

**Comment by xnaas** [comment]
Thanks, @pukkandan! :)

**Comment by GeTechG** [comment]
Update for those looking, still need to split now
`"format_sort": ["+codec","avc:m4a"]`

**Comment by pukkandan** [comment]
> Update for those looking, still need to split now `"format_sort": ["+codec","avc:m4a"]`

No. https://github.com/yt-dlp/yt-dlp/issues/1492#issuecomment-955651535 is still correct
