### ISSUE TITLE
tubepornclassic.com

### ISSUE THREAD

**Issue by SuBra98** [yt-dlp/yt-dlp#1500]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Europe

### Example URLs

- Single video: https://tubepornclassic.com/videos/1039643/tarzan-x-shame-of-jane-hd/

### Description

According to a siterequest open on yt-dl github site is using m3u8, not sure though

### Verbose log

```shell
@MacNuc Downloads % yt-dlp --no-check-certificate -Uv https://tubepornclassic.com/videos/1039643/tarzan-x-shame-of-jane-hd
[debug] Command-line config: ['--no-check-certificate', '-Uv', 'https://tubepornclassic.com/videos/1039643/tarzan-x-shame-of-jane-hd']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.9.5 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4-tessus, ffprobe 4.4-tessus
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [generic] Extracting URL: https://tubepornclassic.com/videos/1039643/tarzan-x-shame-of-jane-hd
[generic] tarzan-x-shame-of-jane-hd: Requesting header
[redirect] Following redirect to https://tubepornclassic.com/videos/1039643/tarzan-x-shame-of-jane-hd/
[debug] [generic] Extracting URL: https://tubepornclassic.com/videos/1039643/tarzan-x-shame-of-jane-hd/
[generic] tarzan-x-shame-of-jane-hd: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] tarzan-x-shame-of-jane-hd: Downloading webpage
[generic] tarzan-x-shame-of-jane-hd: Extracting information
ERROR: [generic] Unsupported URL: https://tubepornclassic.com/videos/1039643/tarzan-x-shame-of-jane-hd/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tubepornclassic.com/videos/1039643/tarzan-x-shame-of-jane-hd/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tubepornclassic.com/videos/1039643/tarzan-x-shame-of-jane-hd/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 609, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://tubepornclassic.com/videos/1039643/tarzan-x-shame-of-jane-hd/
```

**Comment by pukkandan** [comment]
> According to a siterequest open on yt-dl github

Please provide link to the request for reference

**Comment by SuBra98** [comment]
Hi, 

here it is: https://github.com/ytdl-org/youtube-dl/issues/18190

**Comment by 0xvd** [comment]
This is fixed by https://github.com/yt-dlp/yt-dlp/commit/389896df85ed14eaf74f72531da6c4491d6b73b0

EDIT - It is currently broken it is a different problem
