### ISSUE TITLE
Please add support for crowdcast.io videos

### ISSUE THREAD

**Issue by DrHyde** [yt-dlp/yt-dlp#1511]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

UK (or maybe global)

### Example URLs

- Single video: https://www.crowdcast.io/e/gresham-numbers-cultures

### Description

You will need to register an email address to watch the video, which will be shared with the content creator.

I have previously raised this to no avail on youtube-dl's github: https://github.com/ytdl-org/youtube-dl/issues/26850

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '-u', 'PRIVATE', '--list-formats', 'https://www.crowdcast.io/e/gresham-numbers-cultures']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Python version 3.10.0 (CPython 64bit) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [generic] Extracting URL: https://www.crowdcast.io/e/gresham-numbers-cultures
[generic] gresham-numbers-cultures: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] gresham-numbers-cultures: Downloading webpage
[generic] gresham-numbers-cultures: Extracting information
ERROR: [generic] Unsupported URL: https://www.crowdcast.io/e/gresham-numbers-cultures
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.crowdcast.io/e/gresham-numbers-cultures
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.crowdcast.io/e/gresham-numbers-cultures

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 609, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.crowdcast.io/e/gresham-numbers-cultures
```

**Comment by slavakurilyak** [comment]
+1 for **crowdcast.io** support

**Comment by jchook** [comment]
I would also like to see crowdcast support
