### ISSUE TITLE
[jsinterp] Unsupported JS expression

### ISSUE THREAD

**Issue by flashdagger** [yt-dlp/yt-dlp#1552]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

while executing:
`yt-dlp oWm-Qcp9GmE -sv`

Nevertheless the video could be downloaded...

### Verbose log

```shell
[debug] Command-line config: ['oWm-Qcp9GmE', '-sv']
[debug] User config file: yt-dlp.conf
[debug] User config: ['--output', '/mnt/c/Users/marcel/Videos/Captures/%(title)s.%(ext)s', '--no-part', '--no-mtime', '--console-title', '--no-call-home', '--audio-format', 'mp3']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2021.10.22
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.0 (CPython 64bit) - Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: oWm-Qcp9GmE
[youtube] oWm-Qcp9GmE: Downloading webpage
[youtube] oWm-Qcp9GmE: Downloading android player API JSON
[debug] Loading youtube-nsig.f8cb7a3b from cache
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
Traceback (most recent call last):
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 1861, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 1888, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 532, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 182, in interpret_expression
    ret, should_abort = self.interpret_statement(try_expr, local_vars, allow_recursion - 1)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 252, in interpret_expression
    self.interpret_expression(sub_expr, local_vars, allow_recursion)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 445, in interpret_expression
    return eval_method()
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 438, in eval_method
    return obj[member](argvals)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 532, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 214, in interpret_expression
    ret, should_abort = self.interpret_statement(body, local_vars, allow_recursion - 1)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 241, in interpret_expression
    ret, should_abort = self.interpret_statement(stmt, local_vars, allow_recursion - 1)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 127, in interpret_statement
    ret, should_abort = self.interpret_statement(sub_stmt, local_vars, allow_recursion - 1)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File ".virtualenvs/youtube/lib/python3.10/site-packages/yt_dlp/jsinterp.py", line 460, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
yt_dlp.utils.ExtractorError: Unsupported JS expression 'case 94:case 95:case 96:break'; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression 'case 94:case 95:case 96:break'; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.")); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] oWm-Qcp9GmE: Downloading 1 format(s): 303+251
```

**Comment by pukkandan** [comment]
I can see you are not using the release. Which commit are you on?

**Comment by pukkandan** [comment]
This looks like the issue that should have been fixed in https://github.com/yt-dlp/yt-dlp/commit/a1fc7ca0743c8df06416e68ee74b64e07dfe7135

**Comment by flashdagger** [comment]
True. Works with last release and with current head. Apparently I head a version in between...
