### ISSUE TITLE
vrtnu "only available for registered users" error

### ISSUE THREAD

**Issue by pgaig** [yt-dlp/yt-dlp#1557]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Belgium

### Description

vrtnu support behind logon is suddenly broken. Stops with `yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password, or --netrc to provide account credentials` 

Credentials are OK and video works in the browser

### Verbose log

```shell
python3 -m yt_dlp https://www.vrt.be/vrtnu/a-z/sabena/1/sabena-s1a1-het-grote-avontuur/ --netrc -Uv
[debug] Command-line config: ['https://www.vrt.be/vrtnu/a-z/sabena/1/sabena-s1a1-het-grote-avontuur/', '--netrc', '-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.22 (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: a9d4da606
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.13.0-19-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[VrtNU] Login data
[VrtNU] Requesting XSRF Token
[VrtNU] Requesting a token
[debug] [VrtNU] Extracting URL: https://www.vrt.be/vrtnu/a-z/sabena/1/sabena-s1a1-het-grote-avontuur/
[VrtNU] sabena-s1a1-het-grote-avontuur: Downloading webpage
[debug] [Canvas] Extracting URL: https://mediazone.vrt.be/api/v1/vrtvideo/assets/pbs-pub-620288a6-12e6-4b1b-b62f-92247118a571$vid-7d68557f-66b2-470f-be47-4317ca7da227
[Canvas] pbs-pub-620288a6-12e6-4b1b-b62f-92247118a571$vid-7d68557f-66b2-470f-be47-4317ca7da227: Downloading token
[Canvas] pbs-pub-620288a6-12e6-4b1b-b62f-92247118a571$vid-7d68557f-66b2-470f-be47-4317ca7da227: Downloading video JSON
ERROR: [Canvas] pbs-pub-620288a6-12e6-4b1b-b62f-92247118a571$vid-7d68557f-66b2-470f-be47-4317ca7da227: This video is only available for registered users. Use --cookies, --username and --password, or --netrc to provide account credentials
Traceback (most recent call last):
  File "/home/user/Development/yt-dlp/yt_dlp/extractor/common.py", line 594, in extract
    ie_result = self._real_extract(url)
  File "/home/user/Development/yt-dlp/yt_dlp/extractor/canvas.py", line 76, in _real_extract
    self.raise_login_required()
  File "/home/user/Development/yt-dlp/yt_dlp/extractor/common.py", line 1083, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password, or --netrc to provide account credentials
Traceback (most recent call last):
  File "/home/user/Development/yt-dlp/yt_dlp/extractor/common.py", line 594, in extract
    ie_result = self._real_extract(url)
  File "/home/user/Development/yt-dlp/yt_dlp/extractor/canvas.py", line 76, in _real_extract
    self.raise_login_required()
  File "/home/user/Development/yt-dlp/yt_dlp/extractor/common.py", line 1083, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password, or --netrc to provide account credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Development/yt-dlp/yt_dlp/YoutubeDL.py", line 1310, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/Development/yt-dlp/yt_dlp/YoutubeDL.py", line 1335, in __extract_info
    ie_result = ie.extract(url)
  File "/home/user/Development/yt-dlp/yt_dlp/extractor/common.py", line 620, in extract
    raise type(e)(e.msg, **kwargs)
yt_dlp.utils.ExtractorError: [Canvas] pbs-pub-620288a6-12e6-4b1b-b62f-92247118a571$vid-7d68557f-66b2-470f-be47-4317ca7da227: This video is only available for registered users. Use --cookies, --username and --password, or --netrc to provide account credentials
```

**Comment by beantje** [comment]
this also broke down the subtitels, as for now subtitels is not downloaded
