### ISSUE TITLE
Site support request: gumroad.com

### ISSUE THREAD

**Issue by Gelob** [yt-dlp/yt-dlp#1565]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

- Single video: https://gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==

### Description

In this example it is 1 single mp4 file if I inspect in my browser. In other cases it the file loads in chunked .ts and if I inspect browser I see a network request for something like https://gumroad.com/r/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==/index.m3u8 (FYI this will 404 on this specific video but other real videos work this way).

If i pass the m3u8 URL to youtube-dl it downloads the video fine, but I'd like to avoid having to inspect element and pass the URL like above.

### Verbose log

```shell
$ yt-dlp https://gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==
[generic] kSlnXCva3zW8Ryu-u5hT4g==: Requesting header
[redirect] Following redirect to https://app.gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==
[generic] kSlnXCva3zW8Ryu-u5hT4g==: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] kSlnXCva3zW8Ryu-u5hT4g==: Downloading webpage
[generic] kSlnXCva3zW8Ryu-u5hT4g==: Extracting information
ERROR: [generic] Unsupported URL: https://app.gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==
Ryans-MacBook-Pro:Downloads ryan$ yt-dlp -Uv https://gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==
[debug] Command-line config: ['-Uv', 'https://gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.9.6 (CPython 64bit) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [generic] Extracting URL: https://gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==
[generic] kSlnXCva3zW8Ryu-u5hT4g==: Requesting header
[redirect] Following redirect to https://app.gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==
[debug] [generic] Extracting URL: https://app.gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==
[generic] kSlnXCva3zW8Ryu-u5hT4g==: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] kSlnXCva3zW8Ryu-u5hT4g==: Downloading webpage
[generic] kSlnXCva3zW8Ryu-u5hT4g==: Extracting information
ERROR: [generic] Unsupported URL: https://app.gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://app.gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://app.gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 609, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://app.gumroad.com/s/59bd0a45c6b12585318c698c03e4752d/kSlnXCva3zW8Ryu-u5hT4g==
```

**Comment by pukkandan** [comment]
The example URL gives me this both with and without a US VPN

![image](https://user-images.githubusercontent.com/6623388/140579173-79db0747-aecf-4d2a-af9d-94bc001f38ab.png)

**Comment by Gelob** [comment]
@pukkandan that is odd

What about this? https://app.gumroad.com/s/ec29d5713ee9600be3f2d43a71e25300/kSlnXCva3zW8Ryu-u5hT4g==

If not go to https://gelob.gumroad.com/l/ZDyDjM/test. Click I want this! enter any email address (can be bogus, just cant have purchased the product before) and press Get. Then click View Content, then click Watch.

Gumroad also has a feature that disables the download button after purchase and says it implements expiring streaming videos. I've generated such one here https://gelob.gumroad.com/l/RzxDc/test (follow the same process as above).

https://help.gumroad.com/article/43-streaming-videos
