### ISSUE TITLE
[Funimation] User+pass login broken

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#1569]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Description

I am trying to download Demon Slayer: Mugen Train ([LINK](https://www.funimation.com/v/demon-slayer-kimetsu-no-yaiba/demon-slayer-kimetsu-no-yaiba-the-movie-mugen-train)) from Funimation, but when trying to download the JSON data, it errors.

### Verbose log

```shell
[debug] Command-line config: ['--netrc', 'https://www.funimation.com/v/demon-slayer-kimetsu-no-yaiba/demon-slayer-kimetsu-no-yaiba-the-movie-mugen-train', '-F', '-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Python version 3.10.0 (CPython 64bit) - macOS-12.1-x86_64-i386-64bit
[debug] exe versions: avconv present, avprobe present, ffmpeg N-104454-gd92fdc7144, ffprobe N-104454-gd92fdc7144, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[funimation:page] Checking geo-location
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: https://www.funimation.com/v/demon-slayer-kimetsu-no-yaiba/demon-slayer-kimetsu-no-yaiba-the-movie-mugen-train
[funimation:page] demon-slayer-kimetsu-no-yaiba_demon-slayer-kimetsu-no-yaiba-the-movie-mugen-train: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/1621628
[Funimation] 1621628: Downloading player webpage for 1621628
[Funimation] demon-slayer-kimetsu-no-yaiba-the-movie-mugen-train: Downloading Uncut japanese (1751780) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Free Avails for this experience
[Funimation] demon-slayer-kimetsu-no-yaiba-the-movie-mugen-train: Downloading Uncut english (1621628) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Free Avails for this experience
ERROR: [Funimation] 1621627: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1318, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1368, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2237, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 882, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Funimation] 1621627: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by Jules-A** [comment]
Funimation requires cookies to extract properly from my experience, it's been like that as long as I can remember though.

**Comment by TheCoderProYT** [comment]
so netrc doesn't work yet?

**Comment by TheCoderProYT** [comment]
nope, downloaing cookies and using them doesn't work

**Comment by Jules-A** [comment]
> so netrc doesn't work yet?
netrc is working and it does log in, the problem I think is Funimation considering ytdlp as another device if cookies aren't supplied and free accounts are limited to just 1 device so if your web session is still active you won't be able to download anything without cookies. I think the base sub is limited to 2 devices so it can still happen sometimes.
> nope, downloaing cookies and using them doesn't work
Works for me, I'm using manually extracted cookies rather than the cookies from browser option though.

**Comment by pukkandan** [comment]
> netrc is working and it does log in

oh, I thought login had broken. Hence why this is being kept open

@Jules-A can u try to download the same video as OP and confirm whether you can reproduce the issue

**Comment by TheCoderProYT** [comment]
> Do you have a Funimation sub?
AnimeLab account, which is equivalent to Premium Plus Yearly

**Comment by TheCoderProYT** [comment]
btw i downloaded the video specified using the raw m3u8 stream with cookies supplied, if that's any help

**Comment by Jules-A** [comment]
> @Jules-A can u try to download the same video as OP and confirm whether you can reproduce the issue

I already said that it was working for me and I can not reproduce, well with cookies supplied that is. If I don't supply cookies then I get the same error as OP.

>AnimeLab account, which is equivalent to Premium Plus Yearly

Hmm same here.

**Comment by pukkandan** [comment]
Can confirm the issue exists. Unless cookies are used, [incapsula](https://en.wikipedia.org/wiki/Incapsula) silently voids the login causing the "No free experience" error
