### ISSUE TITLE
[Broken] Funimation

### ISSUE THREAD

**Issue by CHJ85** [yt-dlp/yt-dlp#157]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.03.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

I can not make sense of this error.

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.funimation.com/shows/cop-craft/cop-show-witch-craft/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.02.22
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-44-generic-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] Logging in
[Funimation] cop-show-witch-craft: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/utils.py", line 2734, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)


```

**Comment by shirt-dev** [comment]
See https://github.com/ytdl-org/youtube-dl/pull/13515#issuecomment-489892303

**Comment by CHJ85** [comment]
Thank you. Hopefully someone will be able to fix this soon.
I found this substitute though: https://github.com/anidl/funimation-downloader-nx .
Not sure if this source code can be used to recreate the extractor.

**Comment by pukkandan** [comment]
> See ytdl-org/youtube-dl#13515 (comment), it may be an issue with the Incapsula JS challenge.

@CHJ85 The linked comment contains a solution. Did you try it?

**Comment by CHJ85** [comment]
Nope. The cookies workaround didn't work.
And besides. It's a very lengthy and clumsy workaround. The cookies need to be updated regularly and same with the user agent. I wouldn't call this a viable solution. Most people are not gonna have any idea what any of those instructions mean.

**Comment by pukkandan** [comment]
@CHJ85 Give verbose output of:

    yt-dlp -v --no-check-certificate -u USER -p PASS --cookies COOKIESFILE --user-agent USERAGENT -- URL

**Comment by CHJ85** [comment]
@pukkandan sure.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/funimation.py", line 96, in _real_extract
    player_url = self._html_search_meta([
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1138, in _html_search_meta
    return self._html_search_regex(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1019, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by pukkandan** [comment]
@CHJ85 That is just the error. Show full output

**Comment by pukkandan** [comment]
> [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

There is some issue with the certificate. `--no-check-certificate` ignores that issue.

If its working for you now, I think it will work without giving user agent too. Probably only cookies are needed

**Comment by CHJ85** [comment]
Actually without the user-agent, I get errors (RegexNotFoundError):
```
debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', '/home/chris/funimation-cookies.txt', 'https://www.funimation.com/shows/cop-craft/cop-show-witch-craft/', '-v', '--no-check-certificate']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.03.07 
[debug] Python version 3.8.6 (CPython 64bit) - Linux-5.8.0-44-generic-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] Logging in
[Funimation] cop-show-witch-craft: Downloading webpage
WARNING: [Funimation] cop-show-witch-craft: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1024, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1045, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 546, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/funimation.py", line 96, in _real_extract
    player_url = self._html_search_meta([
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1161, in _html_search_meta
    return self._html_search_regex(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1042, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1033, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.


```

**Comment by CHJ85** [comment]
@pukkandan Scratch that. It stopped working completely.
I'm getting this same error each time now and I had to update the cookies file in order for it to work again.
So this is not a viable option.
