### ISSUE TITLE
Add support for italian Discovery+ (discoveryplus.it)

### ISSUE THREAD

**Issue by rgabbo** [yt-dlp/yt-dlp#1574]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Italy

### Example URLs

- Playlist: https://www.discoveryplus.it/programmi/deal-with-it-stai-al-gioco

### Description

It seems not possible to find single video links for the shows. However, is possible to download single episodes finding the `.m3u8` link in browser Network tool. For example I downloaded first episode of the above show with
`yt-dlp "https://dplaysouth-vod.akamaized.net/dplaydni/209185/0/hls/10131929004/playlist.m3u8?hdnts=st=1636223626~exp=1636310026~acl=/dplaydni/209185/0/hls/10131929004/*~hmac=8095972e8a26bfc94795117593ab0450e82bb6b16ebd5c46e7c351b4f2455036"`

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.discoveryplus.it/programmi/deal-with-it-stai-al-gioco']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-04-20-git-718e03e5f2-essentials_build-www.gyan.dev, ffprobe 2021-04-20-git-718e03e5f2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [generic] Extracting URL: https://www.discoveryplus.it/programmi/deal-with-it-stai-al-gioco
[generic] deal-with-it-stai-al-gioco: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] deal-with-it-stai-al-gioco: Downloading webpage
[generic] deal-with-it-stai-al-gioco: Extracting information
ERROR: [generic] Unsupported URL: https://www.discoveryplus.it/programmi/deal-with-it-stai-al-gioco
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 593, in extract
  File "yt_dlp\extractor\generic.py", line 3706, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.discoveryplus.it/programmi/deal-with-it-stai-al-gioco
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 593, in extract
  File "yt_dlp\extractor\generic.py", line 3706, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.discoveryplus.it/programmi/deal-with-it-stai-al-gioco

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1280, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1305, in __extract_info
  File "yt_dlp\extractor\common.py", line 609, in extract
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.discoveryplus.it/programmi/deal-with-it-stai-al-gioco
```

**Comment by pukkandan** [comment]
Single videos are already supported. You can just pass the video URL (not show URL)

**Comment by pukkandan** [comment]
For devs: the `DiscoveryPlusIndiaShowIE` may be a good starting point

**Comment by Ashish0804** [comment]
I'll close this along with #1742
