### ISSUE TITLE
VrtNu Subtitels not working

### ISSUE THREAD

**Issue by beantje** [yt-dlp/yt-dlp#1622]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

belgium

### Description

I can't download subtitels from vrtnu, what worked before

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.vrt.be/vrtnu/a-z/de-5e-boog/1/de-5e-boog-s1a1/', '--username', 'PRIVATE', '--password', 'PRIVATE', '--sub-format', 'vtt', '--write-subs']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-100688-ga423bc9dc2, ffprobe N-100688-ga423bc9dc2
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[VrtNU] Logging in
[VrtNU] Requesting XSRF Token
[VrtNU] Performing login
[debug] [VrtNU] Extracting URL: https://www.vrt.be/vrtnu/a-z/de-5e-boog/1/de-5e-boog-s1a1/
[VrtNU] de-5e-boog-s1a1: Downloading webpage
[debug] [Canvas] Extracting URL: https://mediazone.vrt.be/api/v1/vrtvideo/assets/pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff
[Canvas] pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff: refreshtoken: Retrieve vrtnutoken
[Canvas] pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff: Downloading token
[Canvas] pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff: Downloading video JSON
[Canvas] pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff: Downloading m3u8 information
[Canvas] pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff: Downloading m3u8 information
[Canvas] pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: nl
[debug] Default format spec: bestvideo*+bestaudio/best
[info] pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff: Downloading 1 format(s): HLS_AES-1282
[info] Writing video subtitles to: De 5e boog - Aflevering 1 (Seizoen 1) [pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff].nl.vtt
[debug] Invoking downloader on "https://remix-cf.lwc.vrtcdn.be/remix/eef630ee-06c0-4608-81e4-9f1cbcd309ee/remix_aes.ism/remix_aes-textstream_dut=1000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 27
[download] Destination: De 5e boog - Aflevering 1 (Seizoen 1) [pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff].nl.vtt
[download] De 5e boog - Aflevering 1 (Seizoen 1) [pbs-pub-37e680b6-702d-44fb-aed5-1ad5344d76cc$vid-939f91e1-b5b3-4396-ba9b-c57f74d383ff].nl.vtt.part-Frag3 has already been downloaded
[download]  11.1% of ~16.23KiB at 447.85KiB/s ETA Unknown ETA (frag 3/27)ERROR: Parse error at position 344 (near 'Ik denk dat ik die r')
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1349, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1451, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1399, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2430, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2627, in process_info
  File "yt_dlp\YoutubeDL.py", line 3552, in _write_subtitles
  File "yt_dlp\YoutubeDL.py", line 2578, in dl
  File "yt_dlp\downloader\common.py", line 399, in download
  File "yt_dlp\downloader\hls.py", line 346, in real_download
  File "yt_dlp\downloader\fragment.py", line 488, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 464, in append_fragment
  File "yt_dlp\downloader\hls.py", line 261, in pack_fragment
  File "yt_dlp\webvtt.py", line 398, in parse_fragment
yt_dlp.webvtt.ParseError: Parse error at position 344 (near 'Ik denk dat ik die r')
```

**Comment by pukkandan** [comment]
@fstirlitz could u have a look at what causes the parsing error

**Comment by fstirlitz** [comment]
Blank line in the middle of a cue text in <https://remix-cf.lwc.vrtcdn.be/remix/eef630ee-06c0-4608-81e4-9f1cbcd309ee/remix_aes.ism/remix_aes-textstream_dut=1000-21.vtt>. Those are not allowed according to the WebVTT spec. Maybe this is what #591 and #592 were about.

Now that we have an actual example, we can perhaps merge that workaround in, while limiting its applicability. Perhaps we could scan for `## Created with Unified Streaming Platform(version=1.9.5)` in the m3u8 segment list (as was found in <https://remix-cf.lwc.vrtcdn.be/remix/eef630ee-06c0-4608-81e4-9f1cbcd309ee/remix_aes.ism/remix_aes-textstream_dut=1000.m3u8>), or have the extractor activate the workaround via an option, or have the user apply it with a command-line option.

The standalone subtitle file <https://remix-cf.lwc.vrtcdn.be/remix/eef630ee-06c0-4608-81e4-9f1cbcd309ee/remix_aes.ism/remix_aes-textstream_dut=1000.vtt> linked by the reporter contains the same syntax error.

**Comment by pukkandan** [comment]
> (Either way, shame on them for generating broken subtitles!)

true that. But we can't go ask the website "can u fix your subtitles so that I can download them?". It's similar issue with broken VP9 streams youtube provides. youtube wont fix it coz they don't care and ffmpeg wont fix its parsing coz its out of spec - leaving us with the only choice to use a custom patched ffmpeg.

Anyway, my rambling aside, the issue with #592 is that it can erroneously capture `NOTE` blocks, correct? Perhaps we can look ahead (match without consuming) for a note block and only allow this exception otherwise

**Comment by fstirlitz** [comment]
Yes, I know the game theory doesn’t really bear this out. (Though I imagine the broken subtitles may also cause problems for playback in browsers, which stream providers are more likely to care about. But either way, if anyone has to handle this brokenness, it better be us.)

Right now NOTE blocks are basically the only source of ambiguity, but I imagine the spec has been defined the way it has so that other kinds of blocks may be defined in the future, and we’d better have some feedback when we fail to parse those. Having a strict parser already saved us once (#637). So I still think it better not to make the parser lenient unless yt-dlp detect it’s likely necessary.

**Comment by beantje** [comment]
> Blank line in the middle of a cue text in https://remix-cf.lwc.vrtcdn.be/remix/eef630ee-06c0-4608-81e4-9f1cbcd309ee/remix_aes.ism/remix_aes-textstream_dut=1000-21.vtt. Those are not allowed according to the WebVTT spec. Maybe this is what #591 and #592 were about.
> 
> Now that we have an actual example, we can perhaps merge that workaround in, while limiting its applicability. Perhaps we could scan for `## Created with Unified Streaming Platform(version=1.9.5)` in the m3u8 segment list (as was found in https://remix-cf.lwc.vrtcdn.be/remix/eef630ee-06c0-4608-81e4-9f1cbcd309ee/remix_aes.ism/remix_aes-textstream_dut=1000.m3u8), or have the extractor activate the workaround via an option, or have the user apply it with a command-line option.
> 
> The standalone subtitle file https://remix-cf.lwc.vrtcdn.be/remix/eef630ee-06c0-4608-81e4-9f1cbcd309ee/remix_aes.ism/remix_aes-textstream_dut=1000.vtt linked by the reporter contains the same syntax error.
> 
> (Either way, shame on them for generating broken subtitles!)

i like the idea to have an option, because atm i let the script change the .m3u8 to .vtt and then convert it to srt and add it to the videofile

**Comment by pukkandan** [comment]
I don't think adding a user-facing option for this is really useful. Looking for the `## Created with` comment makes much more sense to me. Would you be willing/able to make a PR for this? @fstirlitz

**Comment by fstirlitz** [comment]
Not at the moment, I'm away from my main development machine. (Typing this from OctoDroid.)

On second thought, maybe it would make more sense to have the extractor enable the workaround, given that the ‘standalone’ subtitle file found by the reporter is corrupted in the same way. And a user-facing option in addition to (not instead of) automatic heuristics might be useful if more such examples pop up.

Last but not least: even if the workaround is enabled, we should at least place a space character between the newlines when assembling the output file, so that nobody further down the line has to deal with this breakage.

**Comment by pgaig** [comment]
@beantje the link is not working anymore https://www.vrt.be/vrtnu/a-z/de-5e-boog/1/de-5e-boog-s1a1/ . Any new case with this issue?
