### ISSUE TITLE
No video formats found: DailyMotion video x2qpwum

### ISSUE THREAD

**Issue by ks202005** [yt-dlp/yt-dlp#1632]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

Upon trying to download this video: https://www.dailymotion.com/video/x2qpwum
yt-dlp is unable to find any formats for the video, despite it playing fine on all my web browsers. The video doesn't require you to be logged in to watch it. 

### Verbose log

```shell
$ yt-dlp -Uv https://www.dailymotion.com/video/x2qpwum
[debug] Command-line config: ['-Uv', 'https://www.dailymotion.com/video/x2qpwum']
[debug] User config file: C:\Users\User\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['-i', '--add-header', 'Referer: https://play.vidyard.com/', '--hls-prefer-native', '--format', 'bestvideo+bestaudio/best', '--merge-output-format', 'mkv', '--youtube-skip-dash-manifest', '--add-metadata', '--embed-subs', '--sub-lang', 'en', '--write-auto-sub', '--convert-subtitles', 'srt', '--write-info-json', '-o', 'I:\\Videos\\YouTube\\%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-8.1-6.3.9600-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [dailymotion] Extracting URL: https://www.dailymotion.com/video/x2qpwum
[dailymotion] Downloading Access Token
[dailymotion] x2qpwum: Downloading media JSON metadata
[dailymotion] x2qpwum: Downloading metadata JSON
[dailymotion] x2qpwum: Downloading m3u8 information
WARNING: [dailymotion] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [dailymotion] x2qpwum: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1349, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1399, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2273, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 912, in raise_no_formats
yt_dlp.utils.ExtractorError: [dailymotion] x2qpwum: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by Ashish0804** [comment]
```
[info] Available formats for x2qpwum:
ID         EXT RESOLUTION │  FILESIZE   TBR PROTO  │ VCODEC        VBR ACODEC     ABR
──────────────────────────────────────────────────────────────────────────────────────
hls-144-0  mp4 192x144    │ ~3.53MiB  105k  m3u8_n │ avc1.42000b 105k  mp4a.40.5 0k
hls-144-1  mp4 192x144    │ ~3.53MiB  105k  m3u8_n │ avc1.42000b 105k  mp4a.40.5 0k
http-144-0 mp4 192x144    │ ~3.53MiB  105k  http   │ avc1.42000b 105k  mp4a.40.5 0k
http-144-1 mp4 192x144    │ ~3.53MiB  105k  http   │ avc1.42000b 105k  mp4a.40.5 0k
hls-240-0  mp4 320x240    │ ~8.27MiB  246k  m3u8_n │ avc1.42000d 246k  mp4a.40.5 0k
hls-240-1  mp4 320x240    │ ~8.27MiB  246k  m3u8_n │ avc1.42000d 246k  mp4a.40.5 0k
http-240-0 mp4 320x240    │ ~8.27MiB  246k  http   │ avc1.42000d 246k  mp4a.40.5 0k
http-240-1 mp4 320x240    │ ~8.27MiB  246k  http   │ avc1.42000d 246k  mp4a.40.5 0k
hls-380-0  mp4 480x360    │ ~15.46MiB 460k  m3u8_n │ avc1.420016 460k  mp4a.40.5 0k
hls-380-1  mp4 480x360    │ ~15.46MiB 460k  m3u8_n │ avc1.420016 460k  mp4a.40.5 0k
http-380-0 mp4 480x360    │ ~15.46MiB 460k  http   │ avc1.420016 460k  mp4a.40.5 0k
http-380-1 mp4 480x360    │ ~15.46MiB 460k  http   │ avc1.420016 460k  mp4a.40.5 0k
```
Can you play it in the browser?
