### ISSUE TITLE
Generate playlist

### ISSUE THREAD

**Issue by QuAzI** [yt-dlp/yt-dlp#1633]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Please add param to append list of result files into playlist file (m3u, pls or similar). Because file manager have other order of files

**Comment by chrizilla** [comment]
> Because file manager have other order of files

also very helpful when each playlist item is downloaded into its own subdir via `-o`

**Comment by pukkandan** [comment]
m3u8 is a very simple format. So something like `--print-to-file "after_move:%(filepath)s" "%(playlist)s.m3u8"` is sufficient to create a valid m3u8 file

PS: `--print-to-file` option didn't exist when this feature was originally requested

**Comment by Goldmaster** [comment]
Hi there, what if you want a playlist file for each individual playlist downloaded?

**Comment by pukkandan** [comment]
Did you try the above command?

**Comment by Goldmaster** [comment]
yes I did, it works but creates 1 playlist for every video downloaded.

Iam working on modifying @thefrenchghosty script here https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/blob/master/scripts/Archivist%20Scripts/Archivist%20Scripts/Playlists/Playlists.sh

to create a playlist file for each individual playlist downloaded.

**Comment by pukkandan** [comment]
Show verbose log

**Comment by Goldmaster** [comment]
[output.log](https://github.com/yt-dlp/yt-dlp/files/9127612/output.log)

Hi there, this is the output log

I also dont know why I get `urllib.error.HTTPError: HTTP Error 429: Too Many Requests`. is there a way to wait and retry again?

**Comment by pukkandan** [comment]
> `'--print-to-file', 'after_move:%(filepath)s', '(playlist)s.m3u'`

The `%` is missing. See https://github.com/yt-dlp/yt-dlp#output-template-and-windows-batch-files

> I also dont know why I get urllib.error.HTTPError: HTTP Error 429: Too Many Requests. is there a way to wait and retry again?

Because you downloaded too many subtitles too fast. Use `--sleep-subtitles`

**Comment by Goldmaster** [comment]
ok well, I'm not getting much downloaded even with using --sleep-subtitles.

later on I get
`ERROR: Unable to download video subtitles for 'af': HTTP Error 429: Too Many Requests
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3854, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2829, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 372, in real_download
    establish_connection()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 131, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3596, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1504, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1561, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2630, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2888, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3862, in _write_subtitles
    raise DownloadError(msg)
yt_dlp.utils.DownloadError: Unable to download video subtitles for 'af': HTTP Error 429: Too Many Requests

[info] Writing updated playlist metadata as JSON to: Goldmaster [UC35fsKHvM-YmfReY-sE5usQ]/Best Desk Setups [PLgHfPTg19OLr8BJcDcNXTr4XTF-Q7PjKN]/0. NA - Best Desk Setups [PLgHfPTg19OLr8BJcDcNXTr4XTF-Q7PjKN].info.json
[download] Finished downloading playlist: Best Desk Setups`

what is going on?

do i just need to set the subtitles to say 10 seconds sleep or something?
