### ISSUE TITLE
funk.net does not work (AssertionError in nexx.py)

### ISSUE THREAD

**Issue by tastytea** [yt-dlp/yt-dlp#1637]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

I can't download any video from funk.net. I always get an AssertionError. I have also tested with the test-URLs from `funk.py`, <https://www.funk.net/channel/ba-793/die-lustigsten-instrumente-aus-dem-internet-teil-2-1155821> and <https://www.funk.net/playlist/neuesteVideos/kameras-auf-dem-fusion-festival-1618699>. Same error.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://funk.net/playlist/trending-4647/attila-hildmann-was-verraet-sein-datenleak-interview-strgf-1774156']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.10.61-gentoo-x86_64-x86_64-AMD_A10-9700_RADEON_R7,_10_COMPUTE_CORES_4C+6G-with-glibc2.33
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Crypto, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [Funk] Extracting URL: https://funk.net/playlist/trending-4647/attila-hildmann-was-verraet-sein-datenleak-interview-strgf-1774156
[Funk] 1774156: Downloading JSON metadata
[debug] [Nexx] Extracting URL: nexx:741:1774156
[Nexx] 1774156: Downloading JSON metadata
ERROR:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1336, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/nexx.py", line 389, in _real_extract
    assert False
AssertionError
```

**Comment by andreaswilli** [comment]
I just ran into this 😕
Any plans to support funk in the future?

**Comment by andreaswilli** [comment]
I can confirm it works now, thanks for the fix!

**Comment by disrupted** [comment]
me too, thanks for the PR!
