### ISSUE TITLE
SBS Australia extractor not recognising "movie" or live stream URLs

### ISSUE THREAD

**Issue by section83** [yt-dlp/yt-dlp#1640]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Description

The SBS extractor does not recognise SBS OnDemand URLs used for movies. For example:

>https://www.sbs.com.au/ondemand/movie/coherence/1469404227931

This is probably because SBS have changed how they serve videos.  Other URLs are recognised e.e.:

>https://www.sbs.com.au/ondemand/video/1973390915633/sayers-talks-about-his-path-to-the-zwift-academy-finals

There is also a problem with SBS live streams. For example

>ps://www.sbs.com.au/ondemand/video/1726824003663/sbs-24x7-live-stream-nsw

See the second verbose log for the result of trying to DL that stream.

Note: I'm using the macOS version of YT-DLP from 22/10/21 because the 2021.11.10.1 version is not available.

### Verbose log

```shell
yt-dlp -v https://www.sbs.com.au/ondemand/movie/coherence/1469404227931
[debug] Command-line config: ['-v', 'https://www.sbs.com.au/ondemand/movie/coherence/1469404227931']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (mac_exe)
[debug] Python version 3.8.9 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1-tessus, ffprobe 4.4.1-tessus
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.sbs.com.au/ondemand/movie/coherence/1469404227931
[generic] 1469404227931: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1469404227931: Downloading webpage
[generic] 1469404227931: Extracting information
ERROR: [generic] Unsupported URL: https://www.sbs.com.au/ondemand/movie/coherence/1469404227931
Traceback (most recent call last):
  File "yt_dlp/extractor/common.py", line 593, in extract
  File "yt_dlp/extractor/generic.py", line 3706, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.sbs.com.au/ondemand/movie/coherence/1469404227931
Traceback (most recent call last):
  File "yt_dlp/extractor/common.py", line 593, in extract
  File "yt_dlp/extractor/generic.py", line 3706, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.sbs.com.au/ondemand/movie/coherence/1469404227931

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1280, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1305, in __extract_info
  File "yt_dlp/extractor/common.py", line 609, in extract
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.sbs.com.au/ondemand/movie/coherence/1469404227931



Live Stream issue:

yt-dlp -v https://www.sbs.com.au/ondemand/video/1726824003663/sbs-24x7-live-stream-nsw
[debug] Command-line config: ['-v', 'https://www.sbs.com.au/ondemand/video/1726824003663/sbs-24x7-live-stream-nsw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (mac_exe)
[debug] Python version 3.8.9 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1-tessus, ffprobe 4.4.1-tessus
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [SBS] Extracting URL: https://www.sbs.com.au/ondemand/video/1726824003663/sbs-24x7-live-stream-nsw
[SBS] 1726824003663: Downloading JSON metadata
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/Bgtm9B/LA8bCeXVGLVU?feed=Video%20-%20Single&mbr=true&manifest=m3u&ord=9511511&policy=11929623&dfptag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.livestream.sbs.com.au%2Flivestreamhtmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast3%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dpreroll%26ad_rule%3D0%26cmsid%3D531%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1726824003663%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1726824003663&dfpmidtag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.livestream.sbs.com.au%2Flivestreamhtmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast3%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dpreroll%26ad_rule%3D0%26cmsid%3D531%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1726824003663%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1726824003663#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] LA8bCeXVGLVU: Downloading SMIL data
[ThePlatform] LA8bCeXVGLVU: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] LA8bCeXVGLVU: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] LA8bCeXVGLVU: Downloading 1 format(s): hls-2890-1
[debug] Invoking downloader on "https://sbs-live.akamaized.net/hls/live/2002827-b/channel1/geo/master_2500K.m3u8?aka_me_session_id=AAAAAAAAAACLUY9hAAAAAFYqiEAZ%2fl90JgBQFMPT2kCaARRWbG+2JRTthEKhYjFFOM5BJzmQeFF5mWQp8gyxgbz%2fv66JRKZQ&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 10
[download] Destination: SBS - 24x7 Live Stream (NSW) [LA8bCeXVGLVU].mp4
[download] 100% of 17.07MiB in 00:04                  
[debug] ffmpeg command line: ffprobe -show_streams 'file:SBS - 24x7 Live Stream (NSW) [LA8bCeXVGLVU].mp4'
[FixupM3u8] Fixing malformed AAC bitstream of "SBS - 24x7 Live Stream (NSW) [LA8bCeXVGLVU].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:SBS - 24x7 Live Stream (NSW) [LA8bCeXVGLVU].mp4' -c copy -map 0 -dn -f mp4 -bsf:a aac_adtstoasc 'file:SBS - 24x7 Live Stream (NSW) [LA8bCeXVGLVU].temp.mp4'
```

**Comment by section83** [comment]
There is a work around for the problem with "movie" URLs. But, it's not intuitive. That is for the user to copy the URL behind the "Play" button on the movie web page. that URL is in the form of:

> https://www.sbs.com.au/ondemand/watch/1962368067637

That form is recognised by the extractor and downloads the movie.

**Comment by Vangelis66** [comment]
For the **VOD** issue, it's probably a **regex** case, as the sbsIE now expects to locate the videoID numeric string (**1469404227931** for your "movie") according to this pattern, 

`*www.sbs.com.au/ondemand/(video|watch)/videoID/*`

in the **third** subdir, not at the end of the URI; should be easily fixable by a coder expert in RegExp 😉 ... 

For your **LIVE** TV stream, I've had success recording **more than a minute's worth** by delegating the download to `ffmpeg` rather than `hlsnative`; use something like ` --downloader "m3u8:ffmpeg"` (equivalent to old flag ` --hls-prefer-ffmpeg`) and, to suppress voluminous `ffmpeg` output, also add ` --downloader-args "ffmpeg:-v 8 -stats"`; successful test command (720p variant) on Windows (with an AU proxy): 
```
yt-dlp_x86 --proxy "proxyhost:proxyport" --downloader "m3u8:ffmpeg" --downloader-args "ffmpeg:-v 8 -stats" -f hls-2120-0 "https://www.sbs.com.au/ondemand/video/1726824003663/sbs-24x7-live-stream-nsw" --no-part
```
=> 
```
[SBS] 1726824003663: Downloading JSON metadata
[ThePlatform] LA8bCeXVGLVU: Downloading SMIL data
[ThePlatform] LA8bCeXVGLVU: Downloading m3u8 information
[ThePlatform] LA8bCeXVGLVU: Downloading JSON metadata
[info] LA8bCeXVGLVU: Downloading 1 format(s): hls-2120-0
[download] Destination: SBS - 24x7 Live Stream (NSW) [LA8bCeXVGLVU].mp4
frame=    1 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=34909.1kbits/s speed=3.67x    
frame=   61 fps= 51 q=-1.0 size=       0kB time=00:00:02.40 bitrate=   0.2kbits/s speed=1.99x    
frame=   73 fps= 39 q=-1.0 size=       0kB time=00:00:02.88 bitrate=   0.1kbits/s speed=1.53x    
frame=   74 fps= 28 q=-1.0 size=       0kB time=00:00:02.92 bitrate=   0.1kbits/s speed=1.09x    
frame=   87 fps= 26 q=-1.0 size=       0kB time=00:00:03.44 bitrate=   0.1kbits/s speed=1.03x    
frame=  124 fps= 32 q=-1.0 size=     256kB time=00:00:04.92 bitrate= 426.3kbits/s speed=1.27x    
frame=  148 fps= 15 q=-1.0 size=     512kB time=00:00:05.98 bitrate= 700.7kbits/s speed= 0.6x    
frame=  151 fps= 13 q=-1.0 size=     512kB time=00:00:06.00 bitrate= 699.1kbits/s speed=0.518x    
frame=  176 fps= 14 q=-1.0 size=     512kB time=00:00:07.00 bitrate= 599.2kbits/s speed=0.573x    
frame=  209 fps= 16 q=-1.0 size=     512kB time=00:00:08.32 bitrate= 504.2kbits/s speed=0.648x    
frame=  220 fps= 16 q=-1.0 size=     512kB time=00:00:08.76 bitrate= 478.8kbits/s speed=0.656x    
frame=  251 fps= 18 q=-1.0 size=     512kB time=00:00:10.00 bitrate= 419.5kbits/s speed=0.714x
(redacted for brevity)
frame= 1426 fps= 17 q=-1.0 size=    4608kB time=00:00:57.00 bitrate= 662.3kbits/s speed=0.663x    
frame= 1440 fps= 17 q=-1.0 size=    4608kB time=00:00:57.56 bitrate= 655.8kbits/s speed=0.663x    
frame= 1466 fps= 17 q=-1.0 size=    4608kB time=00:00:58.60 bitrate= 644.2kbits/s speed=0.67x    
frame= 1498 fps= 16 q=-1.0 size=    5120kB time=00:00:59.97 bitrate= 699.4kbits/s speed=0.654x    
frame= 1501 fps= 16 q=-1.0 size=    5120kB time=00:01:00.00 bitrate= 699.1kbits/s speed=0.645x    
frame= 1509 fps= 16 q=-1.0 size=    5120kB time=00:01:00.32 bitrate= 695.3kbits/s speed=0.643x    
frame= 1536 fps= 16 q=-1.0 size=    5120kB time=00:01:01.40 bitrate= 683.1kbits/s speed=0.649x    
frame= 1542 fps= 16 q=-1.0 size=    5120kB time=00:01:01.64 bitrate= 680.5kbits/s speed=0.647x    
frame= 1574 fps= 16 q=-1.0 size=    5376kB time=00:01:02.92 bitrate= 699.9kbits/s speed=0.656x    
frame= 1608 fps= 17 q=-1.0 size=    5376kB time=00:01:04.28 bitrate= 685.1kbits/s speed=0.665x    
frame= 1621 fps= 17 q=-1.0 size=    5376kB time=00:01:04.80 bitrate= 679.6kbits/s speed=0.666x    
frame= 1648 fps= 16 q=-1.0 size=    5888kB time=00:01:05.98 bitrate= 731.0kbits/s speed=0.648x    
frame= 1651 fps= 16 q=-1.0 size=    5888kB time=00:01:06.00 bitrate= 730.8kbits/s speed=0.64x
(redacted for brevity)
frame= 2076 fps= 16 q=-1.0 size=    6912kB time=00:01:35.00 bitrate= 596.0kbits/s speed=0.748x    
frame= 2098 fps= 16 q=-1.0 size=    7168kB time=00:01:35.98 bitrate= 611.8kbits/s speed=0.733x    
frame= 2101 fps= 16 q=-1.0 size=    7168kB time=00:01:36.00 bitrate= 611.7kbits/s speed=0.729x    
frame= 2107 fps= 16 q=-1.0 size=    7168kB time=00:01:36.24 bitrate= 610.1kbits/s speed=0.728x    
frame= 2143 fps= 16 q=-1.0 size=    7168kB time=00:01:37.68 bitrate= 601.2kbits/s speed=0.734x    
frame= 2174 fps= 16 q=-1.0 size=    7168kB time=00:01:38.92 bitrate= 593.6kbits/s speed=0.739x    
frame= 2174 fps= 16 q=-1.0 size=    7168kB time=00:01:38.92 bitrate= 593.6kbits/s speed=0.735x    
frame= 2248 fps= 16 q=-1.0 Lsize=    7687kB time=00:01:41.95 bitrate= 617.6kbits/s speed=0.736x    

ERROR: Interrupted by user
```
Kill (CTRL+C on Windows) the download at the desired time, you'll end up with file "SBS - 24x7 Live Stream (NSW) [LA8bCeXVGLVU].mp4"

Hope I've helped... :smile:
