### ISSUE TITLE
pbs.org 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Mennaruuk** [yt-dlp/yt-dlp#1643]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

'NoneType' object has no attribute 'get' error when downloading a PBS Nova video.

### Verbose log

```shell
yt-dlp https://www.pbs.org/wgbh/nova/video/nova-universe-revealed-milky-way/ -Uv
[debug] Command-line config: ['https://www.pbs.org/wgbh/nova/video/nova-universe-revealed-milky-way/', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] Using fake IP 6.128.15.128 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[debug] [pbs] Extracting URL: https://www.pbs.org/wgbh/nova/video/nova-universe-revealed-milky-way/
[pbs] nova-universe-revealed-milky-way: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1336, in __extract_info
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\pbs.py", line 665, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/27605

**Comment by Vangelis66** [comment]
Mysteriously though, the equivalent, **non-NOVA**, URI appears to work (via a sanctioned **US tunnel**, as I'm "geographically challenged"): 

`https://www.pbs.org/wgbh/nova/video/nova-universe-revealed-milky-way/` => 

`https://www.pbs.org/video/nova-universe-revealed-milky-way-4io957/`
```
yt-dlp --proxy localhost:xxxx -F "https://www.pbs.org/video/nova-universe-revealed-milky-way-4io957/" => 

[pbs] Downloading JSON metadata
[pbs] nova-universe-revealed-milky-way-4io957: Downloading webpage
[pbs] nova-universe-revealed-milky-way-4io957: Downloading widget/partnerplayer
page
[pbs] nova-universe-revealed-milky-way-4io957: Downloading portalplayer page
[pbs] nova-universe-revealed-milky-way-4io957: Downloading 0 video url info
[pbs] nova-universe-revealed-milky-way-4io957: Downloading m3u8 information
[pbs] nova-universe-revealed-milky-way-4io957: Downloading 1 video url info
[info] Available formats for 3060574923:
ID                                   EXT RESOLUTION |  FILESIZE    TBR PROTO  |VCODEC        VBR ACODEC  MORE INFO
----------------------------------------------------------------------------------------------------------------------------
hls-multiple_audio_tracks-English    mp4 audio only |                  m3u8_n |                  unknown [eng], English
hls-multiple_audio_tracks-English_AD mp4 audio only |                  m3u8_n |                  unknown [eng], English AD
2                                    mp4 unknown    |                  https  |unknown           unknown
hls-334                              mp4 416x234    | ~130.94MiB  334k m3u8_n |avc1.4d400c  334k
hls-565                              mp4 480x270    | ~221.46MiB  565k m3u8_n |avc1.4d4015  565k
hls-959                              mp4 640x360    | ~375.67MiB  959k m3u8_n |avc1.64001e  959k
hls-1342                             mp4 768x432    | ~525.25MiB 1342k m3u8_n |avc1.64001e 1342k
hls-2271                             mp4 960x540    | ~888.99MiB 2271k m3u8_n |avc1.64001f 2271k
hls-3304                             mp4 1280x720   | ~1.26GiB   3304k m3u8_n |avc1.64001f 3304k
hls-4851                             mp4 1280x720   | ~1.85GiB   4851k m3u8_n |avc1.64001f 4851k
hls-6917                             mp4 1920x1080  | ~2.64GiB   6917k m3u8_n |avc1.640028 6917k
```
I think I should also note that if I try that second URI from my **non-US** location, I also **get the message OP (in the US) gets**: 
```
yt-dlp -F "https://www.pbs.org/video/nova-universe-revealed-milky-way-4io957/" =>

[pbs] Downloading JSON metadata
[pbs] nova-universe-revealed-milky-way-4io957: Downloading webpage
[pbs] nova-universe-revealed-milky-way-4io957: Downloading widget/partnerplayer
page
[pbs] nova-universe-revealed-milky-way-4io957: Downloading portalplayer page
ERROR: 'NoneType' object has no attribute 'get'
```
In my case, I would've expected something else, along the lines of 

https://github.com/yt-dlp/yt-dlp/blob/5ad28e7ffd41deccba33776c1609aa7855601739/yt_dlp/extractor/pbs.py#L424

**PS**
A note to devs: 

If the **pbsIE** is going to get revisited due to this, might I also point out 2 things (probably the subject of a separate issue report, after this one has been fixed?): 

1. Currenty the pbsIE has 
```py
(...)
 _GEO_COUNTRIES = ['US']
(...)
 None, headers=self.geo_verification_headers(), fatal=False) or {}).get('cookie')
```
to fool the Playlist API and make it cough up media streams from a non-US originating location, see log: 
```
[debug] Using fake IP 6.128.15.128 (US) as X-Forwarded-For
```
Sadly this trick, that used to work in the past, **no longer does** 😭 ; as posted, I have to use a US proxy now to get the streams...

2. Interestingly, the **HLS stream CDN** doesn't currently geo-fence, so perhaps the pbsIE be given the ` --geo-verification-proxy` "treatment" now, a la cbsIE/[paramountplus](https://github.com/yt-dlp/yt-dlp/pull/711/commits/cfc17c3f89b1183ed5157ac3d57b7b7e4b13fc7e)IE ?

Thanks for everything you do on this fine app ❤️
