### ISSUE TITLE
[Broken] Nickelodeon.be

### ISSUE THREAD

**Issue by hazcod** [yt-dlp/yt-dlp#169]
Hi! Seems nickelodeon.be is broken.
Playback works in browser.

## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.03.07**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
% python3 -m yt_dlp https://www.nickelodeon.nl/episodes/1dzmf6/spongebob-sandy-s-gekke-nichtjes-onbeveiligingsagenten-seizoen-seasonnumber-12-afl-8 --no-check-certificate --verbose -f best -r 5m -c -w --add-metadata -i
[debug] Command-line config: ['https://www.nickelodeon.nl/episodes/1dzmf6/spongebob-sandy-s-gekke-nichtjes-onbeveiligingsagenten-seizoen-seasonnumber-12-afl-8', '--no-check-certificate', '--verbose', '-f', 'best', '-r', '5m', '-c', '-w', '--add-metadata', '-i']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.03.07 (source)
[debug] Python version 3.7.3 (CPython 64bit) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[nick.de] spongebob-sandy-s-gekke-nichtjes-onbeveiligingsagenten-seizoen-seasonnumber-12-afl-8: Downloading webpage
[nick.de] 212f8019-824f-11e9-a442-0e40cf2fc285: Downloading JSON metadata
[nick.de] 212f8019-824f-11e9-a442-0e40cf2fc285: Downloading info
ERROR: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/Users/niels/Library/Python/3.7/lib/python/site-packages/yt_dlp/extractor/common.py", line 654, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/niels/Library/Python/3.7/lib/python/site-packages/yt_dlp/YoutubeDL.py", line 2784, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by CHJ85** [comment]
For starters, you're requesting Nickelodeon BE (Belgium), but as you can see from the output, yt-dlp is trying to download from Nickelodeon Deutschland (Germany). And besides, Nick becomes part of Paramount+ as soon as they launch in Europe. Not sure exactly when. They just recently released in America, with the Nordic countries following on the 25th of this month. 
My point is, looking into this now would be a waste of time.

**Comment by hazcod** [comment]
Hmm, I'm a bit confused, since Belgium doesn't have anything to do with Germany.
Do you think nickelodeon will be impossible to scrape starting from the 25th? :(

**Comment by CHJ85** [comment]
What I'm saying is that Paramount+ comes to the Nordic countries on the 25th. Not sure about the Benelux countries.
And I thought Germany was like a second language to you guys. Sorry. I suggested Nick Germany because the Nick extractor doesn't support any of the Benelux countries.

**Comment by pukkandan** [comment]
Can someone explain to me what is the situation with nick and paramount now? Does this issue still need addressing, or has everything moved to paramount?

**Comment by CHJ85** [comment]
@pukkandan They haven't launched in your country yet. As soon as they do, the Nick shows will stream exclusively on that streaming service. They've already launched in America, some European countries and they're about to launch in Australia. 
That's all I know. I suggest you contact them yourself.

**Comment by hazcod** [comment]
Looping in, the episodes are still on nickelodeon.nl FYI.

**Comment by hazcod** [comment]
Checking here again since the episodes are still available. Any plans to fix?
```
[nick.de] 9db34b6e-b6e3-11e0-8fe5-0026b9414f30: Downloading info
ERROR: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: '-' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:-" ) to search YouTube
Downloading https://www.nickelodeon.nl/episodes/nvqlxw/avatar-de-legende-van-aang-de-krijgers-van-kyoshi-seizoen-seasonnumber-1-afl-4
```

**Comment by hazcod** [comment]
FWIW it seems they are moving over to `rtmpe`, following script e.g. returns `rtmpe://cp5290.edgefcs.net/ondemand/mtviestor/_!/intlod/won-intl/spongebob_squarepants/spongebob_squarepants_11/233_spongebob_squarepants_233/ABC742414/ABC742414_nl-NL_1920x1080_5000.mp4`:

```shell
#!/usr/bin/env bash

SHOWSLUG="76ypv4/spongebob"

echo "Downloading show ${SHOWSLUG}"

showContent=$(curl -s https://www.nickelodeon.nl/shows/"${SHOWSLUG}")

episodeIDs=$(echo "${showContent}" | grep -Eo '"id":"([A-Za-z0-9-]+)"' | cut -d '"' -f 4)
SAVEIFS=$IFS   # Save current IFS
IFS=$'\n'      # Change IFS to new line
episodeIDs=($episodeIDs) # split to array $names
IFS=$SAVEIFS   # Restore IFS

episodeURLs=$(echo "${showContent}" | grep -Eo '\<a href="(\/episodes\/[A-Za-z0-9]+\/[A-Za-z0-9-]+)"' | cut -d '"' -f 2)\\
SAVEIFS=$IFS   # Save current IFS
IFS=$'\n'      # Change IFS to new line
episodeURLs=($episodeURLs) # split to array $names
IFS=$SAVEIFS   # Restore IFS

for i in ${!episodeIDs[@]}; do

	episodeID="${episodeIDs[$i]}"
	episodeURL="${episodeURLs[$i]}"

	echo "-- Downloading episode ${episodeID} -> ${episodeURL}"

	episodeInfo=$(curl -H 'Accept: application/json' -s "https://media.mtvnservices.com/pmt/e1/access/index.html?uri=mgid:arc:episode:nick.intl:${episodeID}&configType=edge&ref=https://www.nickelodeon.nl${episodeURL}")

	feedURL=$(echo "${episodeInfo}" | jq -r '.config.feed')
	echo "--- feed URL: ${feedURL}"

	epiMGID=$(echo "${episodeInfo}" | jq -r '.config.uri')	
	echo "--- MGID: ${epiMGID}"

	mediaGenURL=$(echo "${episodeInfo}" | jq -r '.config.mediaGen')
	echo "--- mediaGenURL: ${mediaGenURL}"

	downloadURL=$(echo "${feedURL}" | sed "s/{uri}/${epiMGID}/")
	echo "--- fetching episode feed from ${downloadURL}" 
	epiFeed=$(curl -s -H 'Accept: application/xml' "${downloadURL}")
	
	epiDownloadURL=$(echo "$epiFeed" | grep -Eo '\"(https\:\/\/media\-utils.*)\"' | cut -d '"' -f 2 | sed 's/\&amp\;/\&/g')
	epiDownloadFeed=$(curl -s "${epiDownloadURL}" | grep -Eo '<src>(.*)</src>' | cut -d '>' -f 2 | cut -d '<' -f 1 | tail -n1)

	echo ${epiDownloadFeed}

	break
done
```

**Comment by Scrooge200FES** [comment]
Nickelodeon.nl still isn't working for me.
```
C:\[...]>yt-dlp -vU https://www.nickelodeon.nl/episodes/zvoqjg/spongebob-rog-man-keert-terug-leendert-de-manager-seizoen-seasonnumber-2-afl-4
[debug] Command-line config: ['-vU', 'https://www.nickelodeon.nl/episodes/zvoqjg/spongebob-rog-man-keert-terug-leendert-de-manager-seizoen-seasonnumber-2-afl-4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev (setts), ffprobe 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.07.18/_update_spec
Latest version: 2022.07.18, Current version: 2022.06.29
Current Build Hash 579d8f37a2d2e2fb8f100890f585462c8566e91f6890728c18bd741417478b08
Updating to version 2022.07.18 ...
ERROR: Unable to remove the old version
Traceback (most recent call last):
  File "yt_dlp\update.py", line 192, in update
PermissionError: [WinError 5] Access is denied: 'C:\\Windows\\yt-dlp.exe.old'

[debug] [nick.de] Extracting URL: https://www.nickelodeon.nl/episodes/zvoqjg/spongebob-rog-man-keert-terug-leendert-de-manager-seizoen-seasonnumber-2-afl-4
[nick.de] spongebob-rog-man-keert-terug-leendert-de-manager-seizoen-seasonnumber-2-afl-4: Downloading webpage
[nick.de] 2321549c-8e1e-4bd4-b5fe-d1927217fdd6: Downloading JSON metadata
[nick.de] 2321549c-8e1e-4bd4-b5fe-d1927217fdd6: Downloading info
ERROR: [nick.de] spongebob-rog-man-keert-terug-leendert-de-manager-seizoen-seasonnumber-2-afl-4: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 640, in extract
  File "yt_dlp\extractor\mtv.py", line 327, in _real_extract
  File "yt_dlp\extractor\mtv.py", line 231, in _get_videos_info
  File "yt_dlp\extractor\mtv.py", line 234, in _get_videos_info_from_url
  File "yt_dlp\extractor\common.py", line 1002, in download_content
  File "yt_dlp\extractor\common.py", line 966, in download_handle
  File "yt_dlp\extractor\common.py", line 834, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 791, in _request_webpage

  File "yt_dlp\extractor\common.py", line 773, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by Scrooge200FES** [comment]
Episodes are still being added, so I tried one on Nick.de, and I got the same error. The video is region locked.
`C:\[...]>yt-dlp -vU https://www.nick.de/episodes/sev72v/die-patrick-star-show-perlas-grosse-chance-die-superbabys-staffel-1-ep-12
[debug] Command-line config: ['-vU', 'https://www.nick.de/episodes/sev72v/die-patrick-star-show-perlas-grosse-chance-die-superbabys-staffel-1-ep-12']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev (setts), ffprobe 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [nick.de] Extracting URL: https://www.nick.de/episodes/sev72v/die-patrick-star-show-perlas-grosse-chance-die-superbabys-staffel-1-ep-12
[nick.de] die-patrick-star-show-perlas-grosse-chance-die-superbabys-staffel-1-ep-12: Downloading webpage
[nick.de] b481c9a8-3c12-4c07-9615-63cdcbed3658: Downloading JSON metadata
[nick.de] b481c9a8-3c12-4c07-9615-63cdcbed3658: Downloading info
ERROR: [nick.de] die-patrick-star-show-perlas-grosse-chance-die-superbabys-staffel-1-ep-12: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\mtv.py", line 327, in _real_extract
  File "yt_dlp\extractor\mtv.py", line 231, in _get_videos_info
  File "yt_dlp\extractor\mtv.py", line 234, in _get_videos_info_from_url
  File "yt_dlp\extractor\common.py", line 1004, in download_content
  File "yt_dlp\extractor\common.py", line 968, in download_handle
  File "yt_dlp\extractor\common.py", line 838, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 795, in _request_webpage

  File "yt_dlp\extractor\common.py", line 777, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3639, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error`

**Comment by CHJ85** [comment]
I just took a look at the nick extractor, and I saw the problem right away.
The example url for nickelodeon.be is invalid.
http://www.nickelodeon.be/afspeellijst/4530-top-videos/videos/episode/73917-inval-broodschapper-lariekoek-arie
See. They're now sharing website with NIck Netherlands (nickelodeon.nl).

@Scrooge200FES Removing the following from the nick.py file will resolve the issue.
```

    }, {
        'url': 'http://www.nickelodeon.be/afspeellijst/4530-top-videos/videos/episode/73917-inval-broodschapper-lariekoek-arie',
        'only_matching': True,
```

**Comment by Scrooge200FES** [comment]
I tried this again, using a Python installation of yt-dlp that would let me edit the files directly, since I'm on Windows and I usually run it with yt-dlp.exe in my C:/Windows folder. I made sure I removed those specific lines, but I'm still getting an error.
```
C:\Users\...\Python\Python310>py -m yt_dlp -vU https://www.nickelodeon.nl/episodes/zvoqjg/spongebob-rog-man-keert-terug-leendert-de-manager-seizoen-seasonnumber-2-afl-4
[debug] Command-line config: ['-vU', 'https://www.nickelodeon.nl/episodes/zvoqjg/spongebob-rog-man-keert-terug-leendert-de-manager-seizoen-seasonnumber-2-afl-4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.3 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev (setts), ffprobe 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [nick.de] Extracting URL: https://www.nickelodeon.nl/episodes/zvoqjg/spongebob-rog-man-keert-terug-leendert-de-manager-seizoen-seasonnumber-2-afl-4
[nick.de] spongebob-rog-man-keert-terug-leendert-de-manager-seizoen-seasonnumber-2-afl-4: Downloading webpage
[nick.de] 2321549c-8e1e-4bd4-b5fe-d1927217fdd6: Downloading JSON metadata
[nick.de] 2321549c-8e1e-4bd4-b5fe-d1927217fdd6: Downloading info
ERROR: [nick.de] spongebob-rog-man-keert-terug-leendert-de-manager-seizoen-seasonnumber-2-afl-4: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\...\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\...\Python\Python310\lib\site-packages\yt_dlp\extractor\mtv.py", line 327, in _real_extract
    videos_info = self._get_videos_info(mgid, url=url)
  File "C:\Users\...\Python\Python310\lib\site-packages\yt_dlp\extractor\mtv.py", line 231, in _get_videos_info
    return self._get_videos_info_from_url(info_url, video_id, use_hls)
  File "C:\Users\...\Python\Python310\lib\site-packages\yt_dlp\extractor\mtv.py", line 234, in _get_videos_info_from_url
    idoc = self._download_xml(
  File "C:\Users\...\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 1004, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "C:\Users\...\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 968, in download_handle
    res = self._download_webpage_handle(
  File "C:\Users\...\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 838, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "C:\Users\...\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 795, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\Users\...\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 777, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "C:\Users\...\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3639, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\...\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\...\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\...\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\...\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\...\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by Scrooge200FES** [comment]
If this fix works, can it be added to the next release?

**Comment by pukkandan** [comment]
What fix?

**Comment by hazcod** [comment]
> I just took a look at the nick extractor, and I saw the problem right away. The example url for nickelodeon.be is invalid. http://www.nickelodeon.be/afspeellijst/4530-top-videos/videos/episode/73917-inval-broodschapper-lariekoek-arie See. They're now sharing website with NIck Netherlands (nickelodeon.nl).
> 
> @Scrooge200FES Removing the following from the nick.py file will resolve the issue.
> 
> ```
> 
>     }, {
>         'url': 'http://www.nickelodeon.be/afspeellijst/4530-top-videos/videos/episode/73917-inval-broodschapper-lariekoek-arie',
>         'only_matching': True,
> ```

That doesn't do anything at all? That just removes a test case.
Nobody has a working version currently.

**Comment by CHJ85** [comment]
@hazcod worked for me just fine.
By removing the example domain, you're preventing YT-dlp from seeing the wrong domain thus going straight to the .nl domain.

**Comment by hazcod** [comment]
@CHJ85 You were completely right, sorry for that. I've opened https://github.com/yt-dlp/yt-dlp/pull/4705 to fix
