### ISSUE TITLE
Amazon product review videos broken with 2021.11.10.1

### ISSUE THREAD

**Issue by TT1** [yt-dlp/yt-dlp#1698]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Amazon product review videos broken with 2021.11.10.1 but worked with 2021.10.10
Example:
yt-dlp -v "https://www.amazon.com/vdp/0f87b0dd88614efa9727e7218e0c4f0d"

### Verbose log

```shell
[debug] Command-line config: ['--verbose', 'https://www.amazon.com/vdp/0f87b0dd88614efa9727e7218e0c4f0d']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-18-amd64-x86_64-with-MX-19.4-patito_feo
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [AmazonStore] Extracting URL: https://www.amazon.com/vdp/0f87b0dd88614efa9727e7218e0c4f0d
[AmazonStore] 0f87b0dd88614efa9727e7218e0c4f0d: Downloading webpage
ERROR: [AmazonStore] 0f87b0dd88614efa9727e7218e0c4f0d: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/amazon.py", line 43, in _real_extract
    data_json = self._parse_json(self._html_search_regex(r'var\s?obj\s?=\s?jQuery\.parseJSON\(\'(.*)\'\)', webpage, 'data'), id)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1175, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1166, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/amazon.py", line 43, in _real_extract
    data_json = self._parse_json(self._html_search_regex(r'var\s?obj\s?=\s?jQuery\.parseJSON\(\'(.*)\'\)', webpage, 'data'), id)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1175, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1166, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1336, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 621, in extract
    raise type(e)(e.msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [AmazonStore] 0f87b0dd88614efa9727e7218e0c4f0d: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
Use `--force-generic-extractor` as a workaround

@Ashish0804 The amazon store extractor needs to either be able to handle this, or return a `url_result(..., ie_key='Generic')` when it fails

**Comment by Ashish0804** [comment]
> Use `--force-generic-extractor` as a workaround
> 
> @Ashish0804 The amazon store extractor needs to either be able to handle this, or return a `url_result(..., ie_key='Generic')` when it fails

Changing the regex to this should fix this
`(?:https?://)(?:www\.)?amazon\.(?:[a-z]{2,3})(?:\.[a-z]{2})?/?[^/]*/(?:dp|gp/product)/(?P<id>[^/&#$?]+)`
Do you have a better idea to fix the regex instead?
Here's the current (broken) one
`(?:https?://)(?:www\.)?amazon\.(?:[a-z]{2,3})(?:\.[a-z]{2})?/[^/]*/?(?:dp|gp/product)/(?P<id>[^/&#$?]+)`
Basically assert that there's a `/` before `dp`

**Comment by TT1** [comment]
I seems that using --force-generic-extractor breaks Google Drive.
