### ISSUE TITLE
[BetIE] Broken extractor

### ISSUE THREAD

**Issue by Sipherdrakon** [yt-dlp/yt-dlp#1711]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

BET.com is only showing super small unknown-video files available for download, older versions showed the urls as unsupported. So it's nice to see it not showing that but these are not viable video files. Was messing around to get them to be recognized but I either get a 500 error or a 404 error depending on where i point the mrss feed url.

### Verbose log

```shell
ytdl "https://www.bet.com/episodes/a2h873/tyler-perry-s-sistas-burning-taboo-season-3-ep-17" --verbose
[debug] Command-line config: ['https://www.bet.com/episodes/a2h873/tyler-perry-s-sistas-burning-taboo-season-3-ep-17', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.bet.com/episodes/a2h873/tyler-perry-s-sistas-burning-taboo-season-3-ep-17
[generic] tyler-perry-s-sistas-burning-taboo-season-3-ep-17: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] tyler-perry-s-sistas-burning-taboo-season-3-ep-17: Downloading webpage
[generic] tyler-perry-s-sistas-burning-taboo-season-3-ep-17: Extracting information
[debug] Looking for video embeds
[debug] Identified a JSON LD
[debug] Default format spec: bestvideo*+bestaudio/best
[info] tyler-perry-s-sistas-burning-taboo-season-3-ep-17: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://www.bet.com/episodes/a2h873/tyler-perry-s-sistas-burning-taboo-season-3-ep-17"
[download] Destination: Burning Taboo [tyler-perry-s-sistas-burning-taboo-season-3-ep-17].unknown_video
[download] 100% of 304.62KiB in 00:00
```

**Comment by Ashish0804** [comment]
This is not a broken site. Broken site issues are when they have their own dedi extractor and it's broken. This is more of a site support request.

**Comment by Sipherdrakon** [comment]
It does.....bet.py, but since none of the urls are supported within it, it fell back to the general extractor. Am I wrong in this assumption?

**Comment by Ashish0804** [comment]
Yes you are correct. This url doesn't match the one in bet.py bcoz of no `.html` at the end.
I am not sure i'm erroring out bcoz of geo restrictions or bcoz the site changed so can u paste the output of this command?
`yt-dlp "https://www.bet.com/episodes/a2h873/tyler-perry-s-sistas-burning-taboo-season-3-ep-17.html" -v`

**Comment by Sipherdrakon** [comment]
ytdl "https://www.bet.com/episodes/a2h873/tyler-perry-s-sistas-burning-taboo-season-3-ep-17.html" -v
[debug] Command-line config: ['https://www.bet.com/episodes/a2h873/tyler-perry-s-sistas-burning-taboo-season-3-ep-17.html', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Bet] Extracting URL: https://www.bet.com/episodes/a2h873/tyler-perry-s-sistas-burning-taboo-season-3-ep-17.html
[Bet] tyler-perry-s-sistas-burning-taboo-season-3-ep-17: Downloading webpage
ERROR: [Bet] tyler-perry-s-sistas-burning-taboo-season-3-ep-17: Unable to extract mgid; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\bet.py", line 68, in _real_extract
  File "yt_dlp\extractor\bet.py", line 62, in _extract_mgid
  File "yt_dlp\extractor\common.py", line 1166, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract mgid; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\bet.py", line 68, in _real_extract
  File "yt_dlp\extractor\bet.py", line 62, in _extract_mgid
  File "yt_dlp\extractor\common.py", line 1166, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract mgid; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1336, in __extract_info
  File "yt_dlp\extractor\common.py", line 621, in extract
yt_dlp.utils.RegexNotFoundError: [Bet] tyler-perry-s-sistas-burning-taboo-season-3-ep-17: Unable to extract mgid; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

**Comment by Ashish0804** [comment]
Yeah looks like the site changed and it's behind some sort of paywall.
Can your provide a URL that is free to watch?

**Comment by Sipherdrakon** [comment]
Sure, while I was testing the MTV Extractor I made sure to grab up a link that required signin, one that didn't, and a video-clip.

Signin Not Required - ```https://www.bet.com/episodes/k021g2/celebrity-stash-yandy-smith-harris-gets-sentimental-in-her-atlanta-closet-season-1-ep-8```
Video-Clip - ```https://www.bet.com/video-clips/98zsfc/sisterhood-is-the-cure-in-the-waiting-room```

**Comment by blizzardcldasl** [comment]
Any luck getting this to work? Issue still present.
