### ISSUE TITLE
Nick.com video-clips are showing as unsupported url

### ISSUE THREAD

**Issue by Sipherdrakon** [yt-dlp/yt-dlp#1712]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

Nick.com works great except for video-clips. The url seems to have changed as is now unsupported by yt-dlp.

### Verbose log

```shell
ytdl -F "https://www.nick.com/video/nhihgv/rugrats-night-howl" --verbose
[debug] Command-line config: ['-F', 'https://www.nick.com/video/nhihgv/rugrats-night-howl', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.nick.com/video/nhihgv/rugrats-night-howl
[generic] rugrats-night-howl: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] rugrats-night-howl: Downloading webpage
[generic] rugrats-night-howl: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.nick.com/video/nhihgv/rugrats-night-howl
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1336, in __extract_info
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\generic.py", line 3766, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nick.com/video/nhihgv/rugrats-night-howl
```

**Comment by Ashish0804** [comment]
From valid_url regex, this provided url is supposed to be of type `videos/clip`?

` _VALID_URL = r'https?://(?P<domain>(?:www\.)?nick(?:jr)?\.com)/(?:[^/]+/)?(?P<type>videos/clip|[^/]+/videos|episodes/[^/]+)/(?P<id>[^/?#.]+)'`

**Comment by Sipherdrakon** [comment]
Yeah, it's a video clip from the new 3d rugrats series. I can get it to recognize the url if I change it to ```_VALID_URL = r'https?://(?P<domain>(?:www\.)?nick(?:jr)?\.com)/(?:[^/]+/)?(?P<type>videos/clip|[^/]+/videos|video/[^/]+|episodes/[^/]+)/(?P<id>[^/?#.]+)'

But it still doesn't download anything.

**Comment by Scrooge200FES** [comment]
Bumping this, since I get the error too. I'm trying to download a SpongeBob short:
`C:\[...]>yt-dlp -vU https://www.nick.com/video/zbqlft
[debug] Command-line config: ['-vU', 'https://www.nick.com/video/zbqlft']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev (setts), ffprobe 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.02, Current version: 2022.11.11
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.01.02/_update_spec
Current Build Hash 3e73e80d5b29be0a6bd47cb8636d281ce8a53ba11533f3441ea7d12433165b41
Updating to version 2023.01.02 ...
ERROR: Unable to remove the old version
Traceback (most recent call last):
  File "yt_dlp\update.py", line 229, in update
PermissionError: [WinError 5] Access is denied: 'C:\\Windows\\yt-dlp.exe.old'

[debug] [generic] Extracting URL: https://www.nick.com/video/zbqlft
[generic] zbqlft: Downloading webpage
[redirect] Following redirect to https://www.nick.com/video/zbqlft/spongebob-squarepants-spongebob-squarepants-minis-how-to-use-a-frozen-krabby-patty
[debug] [generic] Extracting URL: https://www.nick.com/video/zbqlft/spongebob-squarepants-spongebob-squarepants-minis-how-to-use-a-frozen-krabby-patty
[generic] spongebob-squarepants-spongebob-squarepants-minis-how-to-use-a-frozen-krabby-patty: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] spongebob-squarepants-spongebob-squarepants-minis-how-to-use-a-frozen-krabby-patty: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.nick.com/video/zbqlft/spongebob-squarepants-spongebob-squarepants-minis-how-to-use-a-frozen-krabby-patty
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nick.com/video/zbqlft/spongebob-squarepants-spongebob-squarepants-minis-how-to-use-a-frozen-krabby-patty`
