### ISSUE TITLE
SPIEGEL Daily podcast

### ISSUE THREAD

**Issue by gobbblin** [yt-dlp/yt-dlp#1728]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Description

Can't load SPIEGEL Daily podcast.

### Verbose log

```shell
$ yt-dlp --verbose https://www.spiegel.de/politik/deutschland/wochenrueckblick-afghanistan-unter-den-taliban-hoffnung-booster-anthroposophie-und-corona-podcast-a-5a903dd9-fa98-4457-a3f5-f6c1e8f882d7
[debug] Command-line config: ['--verbose', 'https://www.spiegel.de/politik/deutschland/wochenrueckblick-afghanistan-unter-den-taliban-hoffnung-booster-anthroposophie-und-corona-podcast-a-5a903dd9-fa98-4457-a3f5-f6c1e8f882d7']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.15.2-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Spiegel] Extracting URL: https://www.spiegel.de/politik/deutschland/wochenrueckblick-afghanistan-unter-den-taliban-hoffnung-booster-anthroposophie-und-corona-podcast-a-5a903dd9-fa98-4457-a3f5-f6c1e8f882d7
[Spiegel] 5a903dd9-fa98-4457-a3f5-f6c1e8f882d7: Downloading webpage
ERROR: [Spiegel] 5a903dd9-fa98-4457-a3f5-f6c1e8f882d7: Unable to extract media id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/spiegel.py", line 44, in _real_extract
    media_id = self._html_search_regex(
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1175, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1166, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract media id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/spiegel.py", line 44, in _real_extract
    media_id = self._html_search_regex(
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1175, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1166, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract media id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1336, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 621, in extract
    raise type(e)(e.msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [Spiegel] 5a903dd9-fa98-4457-a3f5-f6c1e8f882d7: Unable to extract media id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by gobbblin** [comment]
The podcast used above went behind a paywall 1h after the post here. Unusual for a "Die Woche". You can find more SPIEGEL Daily podcasts here:
https://www.spiegel.de/thema/spiegel-daily/

**Comment by pukkandan** [comment]
All the podcasts in the list seems to take me to a paywall

Eg:
https://www.spiegel.de/politik/deutschland/wochenrueckblick-afghanistan-unter-den-taliban-hoffnung-booster-anthroposophie-und-corona-podcast-a-5a903dd9-fa98-4457-a3f5-f6c1e8f882d7
https://www.spiegel.de/kultur/warum-spielen-immer-mehr-menschen-schach-podcast-a-c1cf837d-9bda-4d4a-959a-29324665f050

Free *videos* on the other hand does work correctly

Eg: https://www.spiegel.de/video/vulkan-tungurahua-in-ecuador-ist-wieder-aktiv-video-1259285.html

**Comment by gobbblin** [comment]
sorry for this, you're right.
The ones that are for money now, where open yesterday morning, playable in Firefox.
The others timed out 48h (or 7 days for "Die Woche").

**Comment by gobbblin** [comment]
ok, here is a new podcast:
https://www.spiegel.de/geschichte/mythen-und-wahrheit-ueber-die-hexenverfolgung-podcast-a-37e8e17f-a94e-4f13-9d17-61c759d1675f

**Comment by bashonly** [comment]
see https://github.com/yt-dlp/yt-dlp/issues/7333#issuecomment-1595808384 for patch and non-paywalled link
