### ISSUE TITLE
Youtube extractor fails with a TypeError

### ISSUE THREAD

**Issue by Mm2PL** [yt-dlp/yt-dlp#1767]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Description

Looks like Youtube changed their signature checks again? They did so in such a way that the yt_dlp js interpreter breaks. I run yt_dlp under a debugger; it turns out that `index` is `42.0` (a float) instead of an int which `range()` expects. Also I'm not sure about the reproducability of this bug.

### Verbose log

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=WSSnD8vnJ7Q', '-f', '298+521', '-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-80-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=WSSnD8vnJ7Q
[youtube] WSSnD8vnJ7Q: Downloading webpage
[youtube] WSSnD8vnJ7Q: Downloading android player API JSON
[debug] Loading youtube-nsig.f1ca6900 from cache
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = cu3wyu6LQn2hse ; player = https://www.youtube.com/s/player/f1ca6900/player_ias.vflset/en_US/base.js
WSSnD8vnJ7Q: Traceback (most recent call last):
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 1863, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 1890, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 536, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 182, in interpret_expression
    ret, should_abort = self.interpret_statement(try_expr, local_vars, allow_recursion - 1)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 256, in interpret_expression
    self.interpret_expression(sub_expr, local_vars, allow_recursion)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 449, in interpret_expression
    return eval_method()
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 442, in eval_method
    return obj[member](argvals)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 536, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 449, in interpret_expression
    return eval_method()
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 371, in eval_method
    argvals = [
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 372, in <listcomp>
    self.interpret_expression(v, local_vars, allow_recursion)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 446, in interpret_expression
    self._named_object(local_vars, eval_method()) + remaining,
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/jsinterp.py", line 405, in eval_method
    for i in range(index, min(index + howMany, len(obj))):
TypeError: 'float' object cannot be interpreted as an integer
 (caused by TypeError("'float' object cannot be interpreted as an integer")); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] WSSnD8vnJ7Q: Requested format is not available
Traceback (most recent call last):
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1349, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1399, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/mm2pl/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2414, in process_video_result
    raise ExtractorError('Requested format is not available', expected=True,
yt_dlp.utils.ExtractorError: [youtube] WSSnD8vnJ7Q: Requested format is not available
```

**Comment by CetaceanNation** [comment]
Reproduced on my side, up to date using Python 3.9.5.

**Comment by pukkandan** [comment]
Thanks for reporting. It should be reproducible with same player URL. I'll take a look.

Although, the jsinterp failing is actually a non-fatal error. The actual error shown in the verbose is due to you providing a wrong format code

**Comment by Mm2PL** [comment]
Oh yeah this doesn't crash when given a correct format. Thanks for pointing out the typo!
