### ISSUE TITLE
abc.com "0070-We updated our app."

### ISSUE THREAD

**Issue by TheQuiz03** [yt-dlp/yt-dlp#1770]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

receiving "0070-We updated our app.  Just sign out and sign back into AT&T TV or AT&T WatchTV or DirecTV this one time, and you'll be all set!" error on ABC.com.  Same error with or without ap-username/ap-password; also tried with --cookies function as well.

### Verbose log

```shell
[debug] Command-line config: ['https://abc.com/shows/dancing-with-the-stars/episode-guide/season-30/11-finale', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-89409-g4678339e74, ffprobe N-89409-g4678339e74
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Go] Extracting URL: https://abc.com/shows/dancing-with-the-stars/episode-guide/season-30/11-finale
[Go] 11-finale: Downloading webpage
[Go] VDKA25377261: Downloading JSON metadata
[debug] Loading ap-mvpd.ABC from cache
[Go] VDKA25377261: Retrieving Authorization Token
ERROR: [Go] 0070-We updated our app.  Just sign out and sign back into AT&T TV or AT&T WatchTV or DirecTV this one time, and you'll be all set!
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\go.py", line 238, in _real_extract
  File "yt_dlp\extractor\adobepass.py", line 1693, in _extract_mvpd_auth
yt_dlp.utils.ExtractorError: 0070-We updated our app.  Just sign out and sign back into AT&T TV or AT&T WatchTV or DirecTV this one time, and you'll be all set!
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\go.py", line 238, in _real_extract
  File "yt_dlp\extractor\adobepass.py", line 1693, in _extract_mvpd_auth
yt_dlp.utils.ExtractorError: 0070-We updated our app.  Just sign out and sign back into AT&T TV or AT&T WatchTV or DirecTV this one time, and you'll be all set!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1336, in __extract_info
  File "yt_dlp\extractor\common.py", line 621, in extract
yt_dlp.utils.ExtractorError: [Go] 0070-We updated our app.  Just sign out and sign back into AT&T TV or AT&T WatchTV or DirecTV this one time, and you'll be all set!
```

**Comment by NipLars** [comment]
Same thing here. I just updated with -U on one on previous version gave KiB/s throttling.
Download succeded, but this range of messages.
Url was this: https://www.youtube.com/watch?v=YB-g8LOIgcw

[youtube] YB-g8LOIgcw: Downloading android player API JSON
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = tbEX3mAcTTj-8t ; player = https://www.youtube.com/s/player/f1ca6900/player_ias.vflset/en_US/base.js
YB-g8LOIgcw: Traceback (most recent call last):
  File "yt_dlp\extractor\youtube.py", line 1863, in _decrypt_nsig
  File "yt_dlp\extractor\youtube.py", line 1890, in <lambda>
  File "yt_dlp\jsinterp.py", line 536, in resf
  File "yt_dlp\jsinterp.py", line 145, in interpret_statement
  File "yt_dlp\jsinterp.py", line 182, in interpret_expression
  File "yt_dlp\jsinterp.py", line 145, in interpret_statement
  File "yt_dlp\jsinterp.py", line 256, in interpret_expression
  File "yt_dlp\jsinterp.py", line 449, in interpret_expression
  File "yt_dlp\jsinterp.py", line 442, in eval_method
  File "yt_dlp\jsinterp.py", line 536, in resf
  File "yt_dlp\jsinterp.py", line 145, in interpret_statement
  File "yt_dlp\jsinterp.py", line 449, in interpret_expression
  File "yt_dlp\jsinterp.py", line 371, in eval_method
  File "yt_dlp\jsinterp.py", line 372, in <listcomp>
  File "yt_dlp\jsinterp.py", line 446, in interpret_expression
  File "yt_dlp\jsinterp.py", line 405, in eval_method
TypeError: 'float' object cannot be interpreted as an integer
 (caused by TypeError("'float' object cannot be interpreted as an integer")); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[info] YB-g8LOIgcw: Downloading 1 format(s): 18
[download] Destination: Allt du behöver veta inför den stora budgetomröstningen [YB-g8LOIgcw].mp4
[download] 100% of 13.58MiB in 00:01

**Comment by dare2** [comment]
The previous week's episodes still download (outside of the AP credentials 7-day window for ABC). It'll be interesting to see if this episode will download when it is no longer provider locked, or if all episodes going forward will encounter this.

**Comment by jiangjiangflies** [comment]
I came across the same issue.

**Comment by nobodyspecial** [comment]
same here

**Comment by meganip90** [comment]
DisneyNow has the same problem. I think it's something to do with DTV.

**Comment by dare2** [comment]
The episode referenced in this ticket can be downloaded now that it's outside of the 7-day ABC provider lock.
