### ISSUE TITLE
[youtube] jsinterp.py type error

### ISSUE THREAD

**Issue by k3ns1n** [yt-dlp/yt-dlp#1773]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Error occurs for https://youtu.be/_AJ6lIcgAgY link, but yt-dlp successfully end

### Verbose log

```shell
yt-dlp -vg https://youtu.be/_AJ6lIcgAgY
[debug] Command-line config: ['-vg', 'https://youtu.be/_AJ6lIcgAgY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.9.8 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://youtu.be/_AJ6lIcgAgY
[youtube] _AJ6lIcgAgY: Downloading webpage
[youtube] _AJ6lIcgAgY: Downloading android player API JSON
[debug] Loading youtube-nsig.f1ca6900 from cache
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = 3-AevQb88X_a-- ; player = https://www.youtube.com/s/player/f1ca6900/player_ias.vflset/en_US/base.js
_AJ6lIcgAgY: Traceback (most recent call last):
  File "./lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 1863, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File "./lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 1890, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 536, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 182, in interpret_expression
    ret, should_abort = self.interpret_statement(try_expr, local_vars, allow_recursion - 1)
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 256, in interpret_expression
    self.interpret_expression(sub_expr, local_vars, allow_recursion)
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 449, in interpret_expression
    return eval_method()
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 442, in eval_method
    return obj[member](argvals)
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 536, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 449, in interpret_expression
    return eval_method()
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 371, in eval_method
    argvals = [
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 372, in <listcomp>
    self.interpret_expression(v, local_vars, allow_recursion)
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 446, in interpret_expression
    self._named_object(local_vars, eval_method()) + remaining,
  File "./lib/python3.9/site-packages/yt_dlp/jsinterp.py", line 405, in eval_method
    for i in range(index, min(index + howMany, len(obj))):
TypeError: 'float' object cannot be interpreted as an integer
 (caused by TypeError("'float' object cannot be interpreted as an integer")); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] _AJ6lIcgAgY: Downloading 1 format(s): 272+251
```

**Comment by coletdjnz** [comment]
Already fixed in master: https://github.com/yt-dlp/yt-dlp/issues/1767, https://github.com/yt-dlp/yt-dlp/commit/57dbe8077f8d00e0fffac53669f40cd7d584474f

Note this error is non-fatal and yt-dlp will still work like normal in most cases.

**Comment by k3ns1n** [comment]
ok, thanks
