### ISSUE TITLE
Myfreecams

### ISSUE THREAD

**Issue by vividuzv** [yt-dlp/yt-dlp#1784]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://myfreecams.com/models
https://app.myfreecams.com/room/erikasmagic
https://www.myfreecams.com/#erikasmagic

### Description

hello. pls add this site.

right now i extract m3u8 and use ffmpeg to download videos.
is it possible to add it ?

thanks.

### Verbose log

```shell
[debug] Command-line config: ['-F', 'https://www.myfreecams.com/#erikasmagic', '-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-29-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [generic] Extracting URL: https://www.myfreecams.com/#erikasmagic
[generic] #erikasmagic: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] #erikasmagic: Downloading webpage
[generic] #erikasmagic: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.myfreecams.com/#erikasmagic
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1336, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/generic.py", line 3766, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.myfreecams.com/#erikasmagic
```

**Comment by iLeeaal** [comment]
Any news about this? MFC has more than 50M views per month, it is not possible that there is no interest in putting it on the list

**Comment by pukkandan** [comment]
There is no "list". Sites are added when someone volunteers a PR for it

**Comment by florty2** [comment]
I've had #12562 open for almost a year now, would be good to get it merged.
