### ISSUE TITLE
Errno 36, name too long when the filename isn't actually too long.

### ISSUE THREAD

**Issue by Ceynou** [yt-dlp/yt-dlp#1786]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I use linux but I'm not that knowledgable about computing and stuff:
OS: EndeavourOS

> getconf -a | grep -i name_max
NAME_MAX                           255
_POSIX_NAME_MAX                    255
LOGNAME_MAX                        256
TTY_NAME_MAX                       32
TZNAME_MAX                         
_POSIX_TZNAME_MAX                  
CHARCLASS_NAME_MAX                 2048
HOST_NAME_MAX                      64
LOGIN_NAME_MAX                     256

I grabbed 280k links of Japanese videos and I'm running a script that download the subs of each video if there are any, I got an error with this link, the script continued nonetheless but I don't understand why I get this error [errno 36], at most, the entier path length wouldn't be bigger than 122 characters.
Happens with that simple command too since it's the same:

`youtube-dl "https://www.youtube.com/watch?v=Hl6i4Bcq8U0"  --verbose  -o '%(title)s.%(ext)s' --write-sub --sub-format best --sub-lang ja`

### Verbose log

```shell
yt-dlp https://www.youtube.com/watch?v=Hl6i4Bcq8U0  --verbose  -o '%(title)s.%(ext)s' --write-subs --sub-format best --sub-langs ja
[debug] Command-line config: ['https://www.youtube.com/watch?v=Hl6i4Bcq8U0', '--verbose', '-o', '%(title)s.%(ext)s', '--write-subs', '--sub-format', 'best', '--sub-langs', 'ja']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.14.16-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Hl6i4Bcq8U0
[youtube] Hl6i4Bcq8U0: Downloading webpage
[youtube] Hl6i4Bcq8U0: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Downloading subtitles: ja
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Hl6i4Bcq8U0: Downloading 1 format(s): 248+251
[info] Writing video subtitles to: 【クリスマスコフレ2019購入品紹介🎄第１弾】ジルスチュアート,スック,コスメデコルテのコフレを元美容部員が徹底レビュー!使い方と似ているプチプラコスメも一緒にご紹介します♪.ja.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=Hl6i4Bcq8U0&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1637820271&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=6A7AD6E910944A1960E8A4BFBA0918FA2C655178.1E492C867785E695BC30023ACFBAF717BE958B80&key=yt8&lang=ja&fmt=vtt"
ERROR: unable to open for writing: [Errno 36] File name too long: '【クリスマスコフレ2019購入品紹介🎄第１弾】ジルスチュアート,スック,コスメデコルテのコフレを元美容部員が徹底レビュー!使い方と似ているプチプラコスメも一緒にご紹介します♪.ja.vtt.part'
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 266, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 2068, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 36] File name too long: '【クリスマスコフレ2019購入品紹介🎄第１弾】ジルスチュアート,スック,コスメデコルテのコフレを元美容部員が徹底レビュー!使い方と似ているプチプラコスメも一緒にご紹介します♪.ja.vtt.part'


[debug] Invoking downloader on "https://r1---sn-25ge7nsd.googlevideo.com/videoplayback?expire=1637816672&ei=AMWeYaekD8-yxN8PiOKq8AY&ip=46.193.67.246&id=o-ABx1mkm5n5SO9GmuypcHFJpqoN41Yq0UC5IPW7tF84Cq&itag=248&source=youtube&requiressl=yes&mh=uT&mm=31%2C29&mn=sn-25ge7nsd%2Csn-25glene7&ms=au%2Crdu&mv=m&mvi=1&pl=23&initcwndbps=1002500&vprv=1&mime=video%2Fwebm&gir=yes&clen=465523165&dur=1867.032&lmt=1573181355487768&mt=1637794620&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgWTCFn0_gNX5h7URcp3iHO73TeIJ3qrwuhZZAE_1sgOsCIFwyltUw_Ixzm7AjdjSiOuvc2u9sj9mF70u70Ny2ti4h&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKaLAYBPDqvYEXvva642U6qAJxlWuntHBlZ_mNFcHA8BAiATV3qjCiyc30rT9aNyGBRnkBCYpkJGG6YXRtbZqnH7Ww%3D%3D"
ERROR: unable to open for writing: [Errno 36] File name too long: '【クリスマスコフレ2019購入品紹介🎄第１弾】ジルスチュアート,スック,コスメデコルテのコフレを元美容部員が徹底レビュー!使い方と似ているプチプラコスメも一緒にご紹介します♪.f248.webm.part'
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 266, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 2068, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 36] File name too long: '【クリスマスコフレ2019購入品紹介🎄第１弾】ジルスチュアート,スック,コスメデコルテのコフレを元美容部員が徹底レビュー!使い方と似ているプチプラコスメも一緒にご紹介します♪.f248.webm.part'


[debug] Invoking downloader on "https://r1---sn-25ge7nsd.googlevideo.com/videoplayback?expire=1637816672&ei=AMWeYaekD8-yxN8PiOKq8AY&ip=46.193.67.246&id=o-ABx1mkm5n5SO9GmuypcHFJpqoN41Yq0UC5IPW7tF84Cq&itag=251&source=youtube&requiressl=yes&mh=uT&mm=31%2C29&mn=sn-25ge7nsd%2Csn-25glene7&ms=au%2Crdu&mv=m&mvi=1&pl=23&initcwndbps=1002500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=28501886&dur=1867.061&lmt=1616758421367867&mt=1637794620&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPMEVrW5tZ2gYQ779cAP6Yde388ukQstKcsthYcZLMtvAiEAh3dryWSuoTDoRM4H-5AaJXCAITcLMhIZsqPuVJwyAl0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKaLAYBPDqvYEXvva642U6qAJxlWuntHBlZ_mNFcHA8BAiATV3qjCiyc30rT9aNyGBRnkBCYpkJGG6YXRtbZqnH7Ww%3D%3D"
ERROR: unable to open for writing: [Errno 36] File name too long: '【クリスマスコフレ2019購入品紹介🎄第１弾】ジルスチュアート,スック,コスメデコルテのコフレを元美容部員が徹底レビュー!使い方と似ているプチプラコスメも一緒にご紹介します♪.f251.webm.part'
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 266, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 2068, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 36] File name too long: '【クリスマスコフレ2019購入品紹介🎄第１弾】ジルスチュアート,スック,コスメデコルテのコフレを元美容部員が徹底レビュー!使い方と似ているプチプラコスメも一緒にご紹介します♪.f251.webm.part'
```

**Comment by Ceynou** [comment]
Okay nevermind, just saw that 255 bytes length limit and tested it... inconvenient but I'll use the id instead I guess.

**Comment by yutayu** [comment]
How to download those videos?

**Comment by bashonly** [comment]
@yutayu see pinned issues/FAQ for workarounds
