### ISSUE TITLE
Incomplete Data Recieved

### ISSUE THREAD

**Issue by antsareflying** [yt-dlp/yt-dlp#1787]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

--get-comments has a incomplete data received error for 1 specific video. I know its a duplicate of #507 and it says its solved but that was a few months ago.

### Verbose log

```shell
[debug] Command-line config: ['--write-description', '--write-info-json', '--write-annotations', '--write-sub', '--sub-langs', 'en', '--write-thumbnail', '--write-comments', '--no-playlist', '--verbose', '--download-archive', 'C:/users/seong/archive/public/videos/downloadedarchive.txt', '-f', 'mp4', '-o', 'C:/users/seong/archive/public/videos/%(upload_date)s-%(title)s-%(id)s.%(ext)s', 'https://www.youtube.com/c/PomplamooseMusic']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'C:/users/seong/archive/public/videos/downloadedarchive.txt'
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/c/PomplamooseMusic
.
.
.
[youtube]     Downloading comment API JSON reply thread 1 (961/2044)
[youtube]     Downloading comment API JSON reply thread 2 (963/2044)
[youtube]     Downloading comment API JSON reply thread 3 (970/2044)
[youtube]     Downloading comment API JSON reply thread 4 (973/2044)
[youtube]     Downloading comment API JSON reply thread 5 (977/2044)
[youtube] Downloading comment API JSON page 42 (986/2044)
[youtube]     Downloading comment API JSON reply thread 1 (994/2044)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube]     Downloading comment API JSON reply thread 1 (994/2044) (retry #1)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube]     Downloading comment API JSON reply thread 1 (994/2044) (retry #2)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube]     Downloading comment API JSON reply thread 1 (994/2044) (retry #3)
ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1349, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1399, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2430, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2599, in process_info
  File "yt_dlp\YoutubeDL.py", line 3063, in post_extract
  File "yt_dlp\YoutubeDL.py", line 3055, in actual_post_extract
  File "yt_dlp\extractor\common.py", line 3533, in extractor
  File "yt_dlp\extractor\youtube.py", line 2279, in _real_comment_extract
  File "yt_dlp\extractor\youtube.py", line 2223, in _comment_entries
  File "yt_dlp\extractor\youtube.py", line 2153, in extract_thread
  File "yt_dlp\extractor\youtube.py", line 2193, in _comment_entries
  File "yt_dlp\extractor\youtube.py", line 726, in _extract_response
yt_dlp.utils.ExtractorError: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
.
.
.

```
```

**Comment by coletdjnz** [comment]
Would you be able to provide the video id/link of the video this is occurring on? Appears to have been cut out of your logs

**Comment by antsareflying** [comment]
```
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=wZNYDzNGB-Q
```

**Comment by coletdjnz** [comment]
Can reproduce, but looks to be a server side issue. Though is rare, I have seen similar thing happen before (but not with comments). It happens in top sorting too.

Best is to wait it out and hopefully YouTube fixes it, or if you still want the comments up to that point you can download that video separately with `--extractor-args youtube:max_comments=990`

**Comment by pukkandan** [comment]
@coletdjnz We could make it so that the extracted comments are returned if user passes `--ignore-errors` even if there was some error. What do u think?

**Comment by RadicalGDPRist** [comment]
Another one: https://www.youtube.com/watch?v=QpPfabmu_Yk

    [youtube] Downloading comment API JSON page 21 (433/1193)
    [youtube]     Downloading comment API JSON reply thread 1 (437/1193)
    WARNING: [youtube] Incomplete data received. Retrying ...
    [youtube]     Downloading comment API JSON reply thread 1 (437/1193) (retry #1)
    WARNING: [youtube] Incomplete data received. Retrying ...
    [youtube]     Downloading comment API JSON reply thread 1 (437/1193) (retry #2)
    WARNING: [youtube] Incomplete data received. Retrying ...
    [youtube]     Downloading comment API JSON reply thread 1 (437/1193) (retry #3)
    ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[Latest master](https://github.com/yt-dlp/yt-dlp/commit/79c318937bd3d2bdd348b94465101925b146d14d)

**Comment by jdasjfdpgij** [comment]
Sorry to say, I've also found another one on version **2022.07.18**: https://www.youtube.com/watch?v=0NKUpo_xKyQ
```[youtube] Downloading comment API JSON page 1147 (35062/85112)
[youtube] Downloading comment API JSON page 1148 (35082/85112)
[youtube]     Downloading comment API JSON reply thread 1 (35092/85112)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube]     Downloading comment API JSON reply thread 1 (35092/85112) (retry #1)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube]     Downloading comment API JSON reply thread 1 (35092/85112) (retry #2)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube]     Downloading comment API JSON reply thread 1 (35092/85112) (retry #3)
ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1521, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1578, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2569, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3360, in post_extract
  File "yt_dlp\YoutubeDL.py", line 3358, in actual_post_extract
  File "yt_dlp\extractor\common.py", line 3699, in extractor
  File "yt_dlp\extractor\youtube.py", line 2980, in _real_comment_extract
  File "yt_dlp\extractor\youtube.py", line 2954, in _comment_entries
  File "yt_dlp\extractor\youtube.py", line 2880, in extract_thread
  File "yt_dlp\extractor\youtube.py", line 2933, in _comment_entries
  File "yt_dlp\extractor\youtube.py", line 828, in _extract_response
yt_dlp.utils.ExtractorError: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U```

**Comment by pukkandan** [comment]
The issue is from Youtube's side as mentioned already. If you want to ignore this error, use `-i`. Providing more examples isn't helping anyone
