### ISSUE TITLE
Using --split-chapters option crashes | Error opening input files: Invalid argument

### ISSUE THREAD

**Issue by Mazamazine** [yt-dlp/yt-dlp#180]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.03.15**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
...@...:~$ .local/bin/yt-dlp --extract-audio --audio-format mp3 --split-chapters -v https://www.youtube.com/watch?v=0HbnqjGirFg
[debug] Command-line config: [u'--extract-audio', u'--audio-format', u'mp3', u'--split-chapters', u'-v', u'https://www.youtube.com/watch?v=0HbnqjGirFg']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.03.15 
[debug] Python version 2.7.17 (CPython 64bit) - Linux-5.4.0-67-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube] 0HbnqjGirFg: Downloading webpage
[debug] Sort order given by user: 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Downloading format(s) 251
[debug] Invoking downloader on u'https://r1---sn-8qu-t0ay.googlevideo.com/videoplayback?expire=1616125001&ei=6cdTYOilKpLohgblu4rQCw&ip=96.22.137.140&id=o-AFqc9cPE05-aKpUfrhJvnsGZTP3N8flcdzpHm-puIRMa&itag=251&source=youtube&requiressl=yes&mh=uk&mm=31%2C29&mn=sn-8qu-t0ay%2Csn-t0a7sn7d&ms=au%2Crdu&mv=m&mvi=1&pl=18&initcwndbps=1633750&vprv=1&mime=audio%2Fwebm&ns=ZRXHAfcuIkF3czU0URJPofwF&gir=yes&clen=71145566&dur=4056.441&lmt=1612599122284797&mt=1616103159&fvip=1&keepalive=yes&fexp=24001374%2C24007246&c=WEB&txp=5431432&n=OCnWfbTvx58evtY-Pz&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALusYeZSeG9V4pig2jh2JNThlLvJ4ajzKP-MeImH1CbPAiAaM16hERIft2DRHd2lwSTec2533mStSSbbDYGhrl_OEw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgfWokS44XPK5Vzoxw0doRD2Qd1w2_CzbFI95hASlDpmECIQDkt_5L0VU3drnpjDNO7L50VLOfwz3PV6mZ1pj7ACoDgA%3D%3D'
[download] Destination: Hollow Knight Official Soundtrack (Full Album) [0HbnqjGirFg].webm
[download] 100% of 67.85MiB in 00:18
[debug] ffmpeg command line: ffprobe -show_streams 'file:Hollow Knight Official Soundtrack (Full Album) [0HbnqjGirFg].webm'
[ExtractAudio] Destination: Hollow Knight Official Soundtrack (Full Album) [0HbnqjGirFg].mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:Hollow Knight Official Soundtrack (Full Album) [0HbnqjGirFg].webm' -vn -acodec libmp3lame '-q:a' 5 'file:Hollow Knight Official Soundtrack (Full Album) [0HbnqjGirFg].mp3'
Deleting original file Hollow Knight Official Soundtrack (Full Album) [0HbnqjGirFg].webm (pass -k to keep)
[SplitChapters] Splitting video by chapters; 26 chapters found
[SplitChapters] Chapter 001; Destination: Hollow Knight Official Soundtrack (Full Album) - 001 1.).Enter Hallownest [0HbnqjGirFg].mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -ss 0.0 -to 90.0 -i 'file:Hollow Knight Official Soundtrack (Full Album) [0HbnqjGirFg].mp3' -c copy 'file:Hollow Knight Official Soundtrack (Full Album) - 001 1.).Enter Hallownest [0HbnqjGirFg].mp3'
ERROR: ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Option to (record or transcode stop time) cannot be applied to input url file:Hollow Knight Official Soundtrack (Full Album) [0HbnqjGirFg].mp3 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file file:Hollow Knight Official Soundtrack (Full Album) [0HbnqjGirFg].mp3.
Error opening input files: Invalid argument
  File ".local/bin/yt-dlp", line 11, in <module>
    sys.exit(main())
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/__init__.py", line 615, in main
    _real_main(argv)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/__init__.py", line 605, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 2489, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 1017, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process, info_dict)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 1024, in wrapper
    return func(self, *args, **kwargs)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 1061, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 1093, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 1967, in process_video_result
    self.process_info(new_info)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 2458, in process_info
    self.post_process(dl_filename, info_dict, files_to_move)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 2583, in post_process
    files_to_move, info = self.run_pp(pp, info, files_to_move)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 2534, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 808, in run
    self.real_run_ffmpeg([(info['filepath'], opts)], [(destination, ['-c', 'copy'])])
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 274, in real_run_ffmpeg
    self.report_error(stderr)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/postprocessor/common.py", line 55, in report_error
    return self._downloader.report_error(text, *args, **kwargs)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 743, in report_error
    self.trouble(error_message, tb)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 705, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: Postprocessing: Error opening input files: Invalid argument
Traceback (most recent call last):
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 2458, in process_info
    self.post_process(dl_filename, info_dict, files_to_move)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 2583, in post_process
    files_to_move, info = self.run_pp(pp, info, files_to_move)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 2534, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 808, in run
    self.real_run_ffmpeg([(info['filepath'], opts)], [(destination, ['-c', 'copy'])])
  File "/home/.../.local/lib/python2.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 275, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
FFmpegPostProcessorError: Error opening input files: Invalid argument

```

## Description

Using the split-chapters option throws an error and stops after trying to run real_run_ffmpeg in ffmpeg.py
Downloading and extracting the audio works, it crashes right after.

`Option to (record or transcode stop time) cannot be applied to input url file:Hollow Knight Official Soundtrack (Full Album) [0HbnqjGirFg].mp3 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.`

I've tested a simple download / extract as follow to check if it's working as expected on my system, no problem there:
`...@...:~$ .local/bin/yt-dlp --extract-audio --audio-format mp3 https://www.youtube.com/watch?v=0HbnqjGirFg`

I've also tested without `--extract-audio --audio-format mp3`, same errors.

It seems to have been merged recently (thanks!), maybe no one came upon this, or it's a problem at my side?

Thanks for reading + for maintaining this!

Have a good day

**Comment by pukkandan** [comment]
I am aware of the issue. It happens for mp4, m4a and mp3, but not for webm, mkv etc afaik. I have no idea why it happens - googling the error message doesnt give any usefull results. The only solution I know of rn is to re-encode the video when splitting the chapters. I need to investigate further before pushing a solution.

**Comment by pukkandan** [comment]
nvm, found the problem. Update your ffmpeg. I was also using an older version, lol. I will try to make a patch to make it work with older ffmpeg, but no guarantees

**Comment by Mazamazine** [comment]
Mmmh, I already have the latest version for Ubuntu 18.4

```
...@...:~$ apt update
...@...:~$ apt-cache policy ffmpeg 
ffmpeg:
  Installé : 7:3.4.8-0ubuntu0.2
  Candidat : 7:3.4.8-0ubuntu0.2
 Table de version :
 *** 7:3.4.8-0ubuntu0.2 500
        500 http://ca.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
        100 /var/lib/dpkg/status
     7:3.4.2-2 500
        500 http://ca.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

What version of ffmpeg are you now using? Is it 4.2.2 from 20.4 repos?

**Comment by pukkandan** [comment]
Any 4.x.x version should work. Older versions of ffmpeg doesn't have `-to` as an input option. I'll patch it for older versions anyway

**Comment by Mazamazine** [comment]
Awesome, thanks for that super fast fix!
