### ISSUE TITLE
Throttled YT download issue workaround

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#1804]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I have begun using https://www.cutyt.com/ instead of yt-dlp to download videos from YouTube. For some reason this website can download YT videos without being throttled.

Is there any possibility of adopting their approach to implement the fix with yt-dlp?

### Verbose log

```shell
-
```

**Comment by pukkandan** [comment]
What? NO!
And if you have some throttling issue, explain it first

**Comment by HalvorRaknes** [comment]
I'm sorry! I thought the throttling issue was universal and has been since about 6 months ago. I believe I have read reports from others on several platforms, this forum included. If it has been fixed, it certainly persists for me. I still keep getting downloaing rates never exceeding 50-70kB/s.

**Comment by HalvorRaknes** [comment]
```
$ yt-dlp -Uv --newline https://www.youtube.com/watch?v=Y_3Qx4eoc6M
[debug] Command-line config: [u'-Uv', u'--newline', u'https://www.youtube.com/watch?v=Y_3Qx4eoc6M']
WARNING: Support for Python version 2.7 have been deprecated and will break in future versions of yt-dlp! Update to Python 3.6 or above
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.06.01 
[debug] Python version 2.7.17 (CPython 64bit) - Linux-5.4.0-90-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
ERROR: It looks like you installed yt-dlp with a package manager, pip, setup.py or a tarball. Please use that to update
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Y_3Qx4eoc6M
[youtube] Y_3Qx4eoc6M: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Y_3Qx4eoc6M: Downloading 1 format(s): 247+251
[debug] Invoking downloader on "https://r2---sn-uxaxovg-vnae7.googlevideo.com/videoplayback?expire=1637962507&ei=q_6gYc3WCcWvyAWZgYPQBg&ip=171.23.6.112&id=o-AExrECulzNvelmQNj1NOnttXoQZd2Uh56M6FIT3yAXLl&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=Nc&mm=31%2C29&mn=sn-uxaxovg-vnae7%2Csn-5goeen7y&ms=au%2Crdu&mv=m&mvi=2&pl=16&initcwndbps=892500&vprv=1&mime=video%2Fwebm&ns=VtjN9bgel_bUEg5xlnwj5EsG&gir=yes&clen=220261150&dur=2197.033&lmt=1637812905453462&mt=1637940553&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5316224&n=X03Zx5562amsadE0&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgfkxHtH9JmiYLO50G0nW_4k4bnbRI3vhWJzwex2nrwIsCIFwW6_nnaj0LZEG_GQg-ktbmzXVG1HP2Je8Yax-iBu8y&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMIWgSB-KUk3jQC7qxEOGKo5mxuyB5lNZhv7HFc1oFuTAiEA2433CCgY9T15pRg45LD7UtHmVWGxiyg-daOZOVHWr_4%3D"
[download] Destination: Here Come The Camps! Paying Attention Yet [Y_3Qx4eoc6M].f247.webm
[download]   0.0% of 210.06MiB at  5.04KiB/s ETA 11:50:52
[download]   0.0% of 210.06MiB at 15.10KiB/s ETA 03:57:26
[download]   0.0% of 210.06MiB at 35.11KiB/s ETA 01:42:06
[download]   0.0% of 210.06MiB at 74.94KiB/s ETA 47:50
[download]   0.0% of 210.06MiB at 66.41KiB/s ETA 53:58
[download]   0.0% of 210.06MiB at 63.22KiB/s ETA 56:41
[download]   0.1% of 210.06MiB at 59.41KiB/s ETA 01:00:18
[download]   0.1% of 210.06MiB at 56.77KiB/s ETA 01:03:05
[download]   0.1% of 210.06MiB at 58.16KiB/s ETA 01:01:34
[download]   0.1% of 210.06MiB at 58.30KiB/s ETA 01:01:24
[download]   0.2% of 210.06MiB at 57.63KiB/s ETA 01:02:06
[download]   0.2% of 210.06MiB at 58.71KiB/s ETA 01:00:57
[download]   0.2% of 210.06MiB at 59.13KiB/s ETA 01:00:29
[download]   0.2% of 210.06MiB at 58.92KiB/s ETA 01:00:41
[download]   0.3% of 210.06MiB at 58.30KiB/s ETA 01:01:19
[download]   0.3% of 210.06MiB at 58.92KiB/s ETA 01:00:40
[download]   0.3% of 210.06MiB at 59.17KiB/s ETA 01:00:23
[download]   0.4% of 210.06MiB at 58.89KiB/s ETA 01:00:39
[download]   0.4% of 210.06MiB at 59.45KiB/s ETA 01:00:04
^C
ERROR: Interrupted by user

```

**Comment by pukkandan** [comment]
You are using an extremely old version. Update it

**Comment by pukkandan** [comment]
> ERROR: It looks like you installed yt-dlp with a package manager, pip, setup.py or a tarball. Please use that to update

**Comment by HalvorRaknes** [comment]
I have tried, and it says I am updated!

```
$ pip install yt-dlp -U
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: yt-dlp in /usr/local/lib/python2.7/dist-packages (2021.6.1)
Requirement already satisfied, skipping upgrade: pycryptodome in /usr/local/lib/python2.7/dist-packages (from yt-dlp) (3.10.1)
Requirement already satisfied, skipping upgrade: mutagen in /usr/local/lib/python2.7/dist-packages (from yt-dlp) (1.43.1)
```

**Comment by pukkandan** [comment]
You are using python 2. Newer versions of yt-dlp only supports python 3

**Comment by HalvorRaknes** [comment]
OK. I have upgraded python 2 but it somehow still uses the older version. For some reason I seem to have several version installed simultaneously!

Can you suggest what I should do?

**Comment by pukkandan** [comment]
first uninstall current yt-dlp `pip uninstall yt-dlp`. Then try `python3 -m pip install -U yt-dlp`

**Comment by HalvorRaknes** [comment]
```
pip uninstall yt-dlp
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Found existing installation: yt-dlp 2021.6.1
Uninstalling yt-dlp-2021.6.1:
  Would remove:
    /usr/local/bin/yt-dlp
    /usr/local/lib/python2.7/dist-packages/yt_dlp-2021.6.1.dist-info/*
    /usr/local/lib/python2.7/dist-packages/yt_dlp/*
    /usr/local/share/bash-completion/completions/yt-dlp
    /usr/local/share/doc/yt_dlp/README.txt
    /usr/local/share/fish/vendor_completions.d/yt-dlp.fish
    /usr/local/share/man/man1/yt-dlp.1
    /usr/local/share/zsh/site-functions/_yt-dlp
Proceed (y/n)? 
Your response ('') was not one of the expected responses: y, n
Proceed (y/n)? y
ERROR: Exception:
Traceback (most recent call last):
  File "/home/halvor/.local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/home/halvor/.local/lib/python2.7/site-packages/pip/_internal/commands/uninstall.py", line 90, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/home/halvor/.local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 686, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/home/halvor/.local/lib/python2.7/site-packages/pip/_internal/req/req_uninstall.py", line 403, in remove
    moved.stash(path)
  File "/home/halvor/.local/lib/python2.7/site-packages/pip/_internal/req/req_uninstall.py", line 292, in stash
    renames(path, new_path)
  File "/home/halvor/.local/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 355, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 326, in move
    os.unlink(src)
OSError: [Errno 13] Ikke tilgang: '/usr/local/bin/yt-dlp'
```

**Comment by pukkandan** [comment]
did u install with sudo? then do the same for uninstalling ofc

**Comment by HalvorRaknes** [comment]
```
$ sudo python3 -m pip install -U yt-dlp
/usr/bin/python3: No module named pip

```

**Comment by pukkandan** [comment]
If u dont have pip, install with the release binary. All instructions are in https://github.com/yt-dlp/yt-dlp#installation

But you have obviously already read it

> - [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))

The issue template is not there for fun. You are supposed to actually follow it!

**Comment by HalvorRaknes** [comment]
I'm sorry. I did notice the discrepancy, but since my attempt at installing stated that I didn't need to upgrade, I figured (being a newbie9 that the issue was something esoteric that I wouldn't have to address. I agree I am being stupid…

**Comment by HalvorRaknes** [comment]
And I abviously DO have pip installed since I am using pip already! I explained that above.

**Comment by pukkandan** [comment]
As per your above log, you dont have pip installed for python **3**. You cannot use python 2's pip to install py3 packages

**Comment by HalvorRaknes** [comment]
OK. That's what I tried to explain above. I did install pip anew, Somehow it still goes back to the older version.

I am completely nonplussed here…

**Comment by HalvorRaknes** [comment]
Corrected. I meant python, not pip. I have attempted to install python 3 previously, and it seemed to work.

**Comment by pukkandan** [comment]
Modern python3 versions already comes with pip. Idk why you don't have it. Btw, what is your python3 version? Check with `python3 --version`. It should be above 3.6 for yt-dlp to work

Anyhow, how u install up-to-date python and pip depends on your distro/pm. Better to ask in related communities

Besides, as I mentioned above, you don't need pip for yt-dlp, just follow the installation instructions

If you actually have any issues regarding yt-dlp, we can continue this thread. This is not the place to help you figure out how to install python/pip

**Comment by HalvorRaknes** [comment]
```
$ python3 --version
Python 3.6.9

```

But I'll try the other way that you suggested.
