### ISSUE TITLE
TikTok User Downloader is broken.

### ISSUE THREAD

**Issue by Theoneflop** [yt-dlp/yt-dlp#1832]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Everywhere

### Description

Downloading a profile on tiktok is not working anymore.

### Verbose log

```shell
[starshine@fedora Documents]$ yt-dlp --verbose --write-pages https://vm.tiktok.com/ZSeS3XPNF/ 
[debug] Command-line config: ['--verbose', '--write-pages', 'https://vm.tiktok.com/ZSeS3XPNF/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.11.12-300.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://vm.tiktok.com/ZSeS3XPNF/
[generic] ZSeS3XPNF: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@yoleendadong?_d=secCgwIARCbDRjEFSADKAESPgo86dEAh3Z%2Fn77L39WI3Uw5iXYilTYBvihD6Kwq5t4m7W2nW6sxvq%2BlQUXyoIDSvKz2O0N13sGgRnzQO20VGgA%3D&language=en&sec_uid=MS4wLjABAAAAB5eD4nYSVXUm-EenMG1lv61JF4RiHlM-wP04GZa5rzvgBVo8QRcNSagAGLtW-HCx&sec_user_id=MS4wLjABAAAAOkLgiKnZIBqD1c5ZIUaRfpOfVgv2Rps_-JgoEV197JSpXx_bt3-aUbAmir-jFo0q&share_app_id=1233&share_author_id=6621187864221384710&share_link_id=4c1bf44b-1d24-4640-9428-ea21569080e4&timestamp=1637932859&u_code=dlegb2cfck6b3g&user_id=7026701991499318278&utm_campaign=client_share&utm_medium=android&utm_source=copy&source=h5_m&_r=1
[debug] [tiktok:user] Extracting URL: https://www.tiktok.com/@yoleendadong?_d=secCgwIARCbDRjEFSADKAESPgo86dEAh3Z%2Fn77L39WI3Uw5iXYilTYBvihD6Kwq5t4m7W2nW6sxvq%2BlQUXyoIDSvKz2O0N13sGgRnzQO20VGgA%3D&language=en&sec_uid=MS4wLjABAAAAB5eD4nYSVXUm-EenMG1lv61JF4RiHlM-wP04GZa5rzvgBVo8QRcNSagAGLtW-HCx&sec_user_id=MS4wLjABAAAAOkLgiKnZIBqD1c5ZIUaRfpOfVgv2Rps_-JgoEV197JSpXx_bt3-aUbAmir-jFo0q&share_app_id=1233&share_author_id=6621187864221384710&share_link_id=4c1bf44b-1d24-4640-9428-ea21569080e4&timestamp=1637932859&u_code=dlegb2cfck6b3g&user_id=7026701991499318278&utm_campaign=client_share&utm_medium=android&utm_source=copy&source=h5_m&_r=1
[tiktok:user] yoleendadong: Downloading webpage
[tiktok:user] Saving request to yoleendadong_https_-_www.tiktok.com_@yoleendadong_d=secCgwIARCbDRjEFSADKAESPgo86dEAh3Z%2Fn77L39WI3Uw5iXYilTYBvihD6Kwq5t4m7W2nW6sxvq%2BlQUXyoIDSvKz2O0N13sGgRnzQO20VGgA%3D_language=en_sec_uid=MS4wLjABAAAAB5_38d1eb355a3098cb264ec6ce05913510.dump
[download] Downloading playlist: yoleendadong
[tiktok:user] yoleendadong: Downloading user video list page 1
[tiktok:user] Saving request to yoleendadong_https_-_api-t2.tiktokv.com_aweme_v1_aweme_post_user_id=6621187864221384710_count=21_max_cursor=0_min_cursor=0_retry_type=no_retry_device_id=1641026827630030711_version_name=20.9.3_version_cod_e99ac00921ad2119c6c52b8c3243b05b.dump
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] yoleendadong: Downloading user video list page 1 (attempt 1)
[tiktok:user] Saving request to yoleendadong_https_-_api-t2.tiktokv.com_aweme_v1_aweme_post_user_id=6621187864221384710_count=21_max_cursor=0_min_cursor=0_retry_type=no_retry_device_id=1641026827630030711_version_name=20.9.3_version_cod_c39ef3447684b83de68cc169062ba245.dump
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] yoleendadong: Downloading user video list page 1 (attempt 2)
[tiktok:user] Saving request to yoleendadong_https_-_api-t2.tiktokv.com_aweme_v1_aweme_post_user_id=6621187864221384710_count=21_max_cursor=0_min_cursor=0_retry_type=no_retry_device_id=1641026827630030711_version_name=20.9.3_version_cod_0aedcb3c912daf71338ef6175c55e1b5.dump
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] yoleendadong: Downloading user video list page 1 (attempt 3)
[tiktok:user] Saving request to yoleendadong_https_-_api-t2.tiktokv.com_aweme_v1_aweme_post_user_id=6621187864221384710_count=21_max_cursor=0_min_cursor=0_retry_type=no_retry_device_id=1641026827630030711_version_name=20.9.3_version_cod_9516b2fd46e8122ff7256f5830720ab0.dump
ERROR: yoleendadong: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/starshine/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 988, in _parse_json
    return json.loads(json_string)
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/starshine/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 988, in _parse_json
    return json.loads(json_string)
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/starshine/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1318, in wrapper
    return func(self, *args, **kwargs)
  File "/home/starshine/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1556, in <lambda>
    lambda self, i: ie_entries[i - 1]
  File "/home/starshine/.local/lib/python3.9/site-packages/yt_dlp/utils.py", line 4141, in __getitem__
    self.__cache.extend(itertools.islice(self.__iterable, n))
  File "/home/starshine/.local/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 460, in _entries_api
    post_list = self._call_api('aweme/post', query, username,
  File "/home/starshine/.local/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 73, in _call_api
    return self._download_json(
  File "/home/starshine/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 977, in _download_json
    res = self._download_json_handle(
  File "/home/starshine/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 963, in _download_json_handle
    return self._parse_json(
  File "/home/starshine/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 992, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
yt_dlp.utils.ExtractorError: yoleendadong: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

[tiktok:user] playlist yoleendadong: Downloading 0 videos
[download] Finished downloading playlist: yoleendadong
```
Extra logs: [logs.zip](https://github.com/yt-dlp/yt-dlp/files/7618905/logs.zip)

**Comment by MinePlayersPE** [comment]
It just went up again, can you try again?

**Comment by Theoneflop** [comment]
> It just went up again, can you try again?

Sure.

**Comment by pukkandan** [comment]
Tiktok API has been going down frequently. If you see this message in the future, your best bet is to increase the reties or try again after some time

```
[tiktok:user] yoleendadong: Downloading user video list page 1 (attempt 3)
ERROR: yoleendadong: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by makeworld-the-better-one** [comment]
Experiencing this now. So this is TikTok's mobile API servers going down? Does that mean that TikTok is actually broken at this time, like using the app wouldn't work? Because the website still works for me.

It would be helpful if the error message for this was improved.
