### ISSUE TITLE
error in postprocessing when file extension missing

### ISSUE THREAD

**Issue by porjo** [yt-dlp/yt-dlp#1844]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

postprocessing doesn't work when specifying an output filename which does not include a file extension. It appears ffmpeg is unable to work out what output file type to use. Could yt-dlp be modified to pass the output file type to ffmpeg for the postprocessing stage?

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--sponsorblock-remove', 'sponsor', '-f', 'worstaudio', '-o', 'blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2', 'https://www.youtube.com/watch?v=LP5z2Fkk95M']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.0 (CPython 64bit) - Linux-5.15.4-201.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=LP5z2Fkk95M
[youtube] LP5z2Fkk95M: Downloading webpage
[youtube] LP5z2Fkk95M: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/9ff4?service=YouTube&categories=%5B%22sponsor%22%5D
[SponsorBlock] Found 2 segments in the SponsorBlock database
[info] LP5z2Fkk95M: Downloading 1 format(s): 139
[debug] Invoking downloader on "https://r1---sn-n02xgavv250-ntqe.googlevideo.com/videoplayback?expire=1638332767&ei=_6SmYfvvKrLB1AaQm6mACg&ip=2401%3Ad002%3A4b02%3Ae00%3A%3A36b&id=o-AK-qc9cp_sJ_q2xtyETEyKuyHzKz158AamWWcip7aAu_&itag=139&source=youtube&requiressl=yes&mh=AV&mm=31%2C29&mn=sn-n02xgavv250-ntqe%2Csn-hxa7zn7s&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=40&initcwndbps=1613750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=35119145&dur=5759.245&lmt=1637800674427396&mt=1638310874&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgZX4Whrzjusx-uFWcH5jwjcNWZGZheA-8L1QQHnN2H5QCIQDoSa06Rz667vEQHB_mpr-6QwuZX2a2aDIIbaaDhNV19w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTiT81Q-PWwU5kllLlKXuXSQoleI4wTjOyiCaAQ9MI80CIAd5QLNn1Ls30ehyim-ebZzwVfwI8ztadRKs63eUPp5j"
[download] Destination: blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2
[download] 100% of 33.49MiB in 00:13                 
[FixupM4a] Correcting container of "blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2 -c copy -map 0 -dn -f mp4 file:blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2.temp
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json file:blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2
[ModifyChapters] Removing chapters from blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2
[debug] Writing concat spec to blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2.temp.concat
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -hide_banner -nostdin -f concat -safe 0 -i file:blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2.temp.concat -c copy file:blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2.temp
[debug] Input #0, concat, from 'file:blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2.temp.concat':
  Duration: N/A, start: 0.000000, bitrate: 48 kb/s
  Stream #0:0(eng): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
[NULL @ 0x5631f2e52080] Unable to find a suitable output format for 'file:blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2.temp'
file:blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2.temp: Invalid argument
ERROR: Postprocessing: file:blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2.temp: Invalid argument
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2919, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3078, in post_process
    info = self.run_pp(pp, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3021, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 112, in wrapper
    return func(self, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/modify_chapters.py", line 64, in run
    in_out_files = [remove_chapters(info['filepath'], False)]
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/modify_chapters.py", line 62, in remove_chapters
    return file, self.remove_chapters(file, cuts, concat_opts, self._force_keyframes and not is_sub)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/modify_chapters.py", line 321, in remove_chapters
    self.concat_files([in_file] * len(concat_opts), out_file, concat_opts)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 364, in concat_files
    self.real_run_ffmpeg(
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 307, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:blah/ytdl-21d3ebf6b5cdefa815234a825abf0cf2.temp: Invalid argument
```

**Comment by pukkandan** [comment]
A more sensible solution is imo to force the correct file extension irrespective of user-provided one. This is what is already done in Merger

**Comment by porjo** [comment]
I worked around my issue by adding `.%(ext)s` to the output filename. @pukkandan as you say it might be better to force correct file extension sent to ffmpeg.

**Comment by tpikonen** [comment]
I had this problem with the `FFmpegEmbedSubtitle` postprocessor.

Using the file extension to communicate the output container type sure is an interesting design choice. I fixed this by setting the `container` field in the `format` dict to the detected output ext (or container format). This is then used to set the ffmpeg `-f`  argument, so that the format does not depend on the output file name.

Here's a patch:

```
diff --git a/yt_dlp/YoutubeDL.py b/yt_dlp/YoutubeDL.py
index 7ba6441e1..2cd212e30 100644
--- a/yt_dlp/YoutubeDL.py
+++ b/yt_dlp/YoutubeDL.py
@@ -2550,6 +2550,8 @@ def is_wellformed(f):
                     format['format_id'] = '%s-%d' % (format_id, i)
                 if format.get('ext') is None:
                     format['ext'] = determine_ext(format['url']).lower()
+                if format.get('container') is None:
+                        format['container'] = format.get('ext')
                 # Ensure there is no conflict between id and ext in format selection
                 # See https://github.com/yt-dlp/yt-dlp/issues/1282
                 if format['format_id'] != format['ext'] and format['format_id'] in common_exts:
diff --git a/yt_dlp/postprocessor/ffmpeg.py b/yt_dlp/postprocessor/ffmpeg.py
index a726a962f..c8bd3fc2f 100644
--- a/yt_dlp/postprocessor/ffmpeg.py
+++ b/yt_dlp/postprocessor/ffmpeg.py
@@ -579,7 +579,9 @@ def __init__(self, downloader=None, already_have_subtitle=False):
 
     @PostProcessor._restrict_to(images=False)
     def run(self, info):
-        if info['ext'] not in self.SUPPORTED_EXTS:
+        # TODO: Any other container format string fixes necessary?
+        cont = info['container'].replace('_dash', '')
+        if cont not in self.SUPPORTED_EXTS:
             self.to_screen(f'Subtitles can only be embedded in {", ".join(self.SUPPORTED_EXTS)} files')
             return [], info
         subtitles = info.get('requested_subtitles')
@@ -599,7 +601,6 @@ def run(self, info):
             return [], info
         '''
 
-        ext = info['ext']
         sub_langs, sub_names, sub_filenames = [], [], []
         webm_vtt_warn = False
         mp4_ass_warn = False
@@ -611,15 +612,15 @@ def run(self, info):
             sub_ext = sub_info['ext']
             if sub_ext == 'json':
                 self.report_warning('JSON subtitles cannot be embedded')
-            elif ext != 'webm' or ext == 'webm' and sub_ext == 'vtt':
+            elif cont != 'webm' or (cont == 'webm' and sub_ext == 'vtt'):
                 sub_langs.append(lang)
                 sub_names.append(sub_info.get('name'))
                 sub_filenames.append(sub_info['filepath'])
             else:
-                if not webm_vtt_warn and ext == 'webm' and sub_ext != 'vtt':
+                if not webm_vtt_warn and cont == 'webm' and sub_ext != 'vtt':
                     webm_vtt_warn = True
                     self.report_warning('Only WebVTT subtitles can be embedded in webm files')
-            if not mp4_ass_warn and ext == 'mp4' and sub_ext == 'ass':
+            if not mp4_ass_warn and cont == 'mp4' and sub_ext == 'ass':
                 mp4_ass_warn = True
                 self.report_warning('ASS subtitles cannot be properly embedded in mp4 files; expect issues')
 
@@ -629,10 +630,11 @@ def run(self, info):
         input_files = [filename] + sub_filenames
 
         opts = [
-            *self.stream_copy_opts(ext=info['ext']),
+            *self.stream_copy_opts(ext=cont),
             # Don't copy the existing subtitles, we may be running the
             # postprocessor a second time
             '-map', '-0:s',
+            '-f', EXT_TO_OUT_FORMATS.get(cont, cont),
         ]
         for i, (lang, name) in enumerate(zip(sub_langs, sub_names)):
             opts.extend(['-map', '%d:0' % (i + 1)])
```

Something like this could probably be used to fix the other ffmpeg postprocessors as well. Should I make a PR, or are there any problems with this approach?

**Comment by pukkandan** [comment]
We want to avoid the use of `-f` and let ffmpeg determine it automatically where possible

**Comment by tpikonen** [comment]
In the case of user supplied file name it obviously does not work automatically. At least in the case where `ext` is not a known format, using `-f` would be useful as a fallback.

**Comment by pukkandan** [comment]
`ext` is not the user-provided file extension though. It is the extension as determined by the extractor. Not sure what you are trying to achieve by copying it into `container`

**Comment by pukkandan** [comment]
```diff
+            '-f', EXT_TO_OUT_FORMATS.get(info['ext'], info['ext']),
```
I got that. My point is that only this part your patch is needed to fix it. The rest is redundant.

But anyway, why are you hardcoding extension in `outtmpl` instead of just using `%(ext)s`?

**Comment by tpikonen** [comment]
Let's say that my output file name is hardcoded (or it would be a pain to change it). [This line](https://github.com/yt-dlp/yt-dlp/blob/145c5a83a80536b781fd043016bd27c91c760667/yt_dlp/YoutubeDL.py#L3058) makes the `ext` non-sensical, if the file name in `outtmpl`  does not have a (sane) extension and the output file exists and `overwrites` is False. I happened to have this situation (the file is created before ytdl call to monitor it during download).

I'm thinking how (and if) this should be fixed, and I would appreciate your input.

This patch fixes `FFmpegEmbedSubtitlePP` if using `-f` is not recommended:
```
diff --git a/yt_dlp/postprocessor/ffmpeg.py b/yt_dlp/postprocessor/ffmpeg.py
index d490f13a4..335f1dc72 100644
--- a/yt_dlp/postprocessor/ffmpeg.py
+++ b/yt_dlp/postprocessor/ffmpeg.py
@@ -644,7 +644,7 @@ def run(self, info):
                 opts.extend(['-metadata:s:s:%d' % i, 'handler_name=%s' % name,
                              '-metadata:s:s:%d' % i, 'title=%s' % name])
 
-        temp_filename = prepend_extension(filename, 'temp')
+        temp_filename = prepend_extension(filename, 'temp') + '.' + ext
         self.to_screen('Embedding subtitles in "%s"' % filename)
         self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
         os.replace(temp_filename, filename)

```

**Comment by harrypotterIUP** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/7aaf4cd2a8fd8ecf2123b981782c3d12dce80d78, there is now a note in the docs about the filename specified by `-o` being possibly altered by post-processing. I still view it as surprising that `-o` output filename is maybe not the actual output filename and I am not aware of any other command line tool that behaves like this. However, with the added note to the docs, I think it's fair play. :+1: 

For completeness, I want to include an idea for a possible future option, from #5471, that I don't see mentioned here in this issue thread, yet:

> Option `--force-filename` which renames the file after post-processing to whatever `-o` said in the first place (because if the user wants to have an output filename without extension or a wrong extension, why not allow it?)

This could be implemented by a simple file rename/move from whatever the filepath currently is (after post-processing, what `--print after_move:filepath` would print) to whatever filepath has been originally specified by `-o`.
