### ISSUE TITLE
volleyballworld.tv request

### ISSUE THREAD

**Issue by proppetto** [yt-dlp/yt-dlp#1846]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Italy

### Example URLs

- Home: https://www.volleyballworld.tv
- Single video: https://www.volleyballworld.tv/video/98372/mens-world-cup-japan-v-canada-full-match-replay
- Single video: https://www.volleyballworld.tv/purchase?from=/video/271778/kioene-padova-v-sir-safety-conad-perugia-round-9-highlights

### Description

Nothing to add.

### Verbose log

```shell
yt-dlp.exe -Uv https://www.volleyballworld.tv/video/98372/mens-world-cup-japan-v-canada-full-match-replay
[debug] Command-line config: ['-Uv', 'https://www.volleyballworld.tv/video/98372/mens-world-cup-japan-v-canada-full-match-replay']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://www.volleyballworld.tv/video/98372/mens-world-cup-japan-v-canada-full-match-replay
[generic] mens-world-cup-japan-v-canada-full-match-replay: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] mens-world-cup-japan-v-canada-full-match-replay: Downloading webpage
[generic] mens-world-cup-japan-v-canada-full-match-replay: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.volleyballworld.tv/video/98372/mens-world-cup-japan-v-canada-full-match-replay
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\generic.py", line 3813, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.volleyballworld.tv/video/98372/mens-world-cup-japan-v-canada-full-match-replay
```

**Comment by HobbyistDev** [comment]
This site require account

**Comment by IcantDoAnythingWithoutGithub** [comment]
I have an account if anyone wants to work on this.

**Comment by Air-w0lf** [comment]
I can also share an account if someone could help. I have gotten as far as identifying the master .m3u8 file but I get a 403 error when passing it into yt-dlp. I have tried passing cookies and also all the headers I can find, but no luck.

**Comment by Air-w0lf** [comment]
Ok I can identify the video .m3u8 file and the audio stream (they are separate) but still battling 403 errors unless I use something like VideoDownloadHelper.
