### ISSUE TITLE
[Twitch] 120fps VoD causes ERROR: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by voltagex** [yt-dlp/yt-dlp#1848]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

All?

### Description

You will note that Twitch itself doesn't see the correct framerate, but it seems to be there if you check -F formats:

![image](https://user-images.githubusercontent.com/83080728/144200585-d582ccdd-3ae4-4d0d-aad0-53cc1db6b57a.png)

```
Broken: https://www.twitch.tv/videos/121711674

[info] Available formats for v1217116741:
ID         EXT RESOLUTION FPS │   FILESIZE   TBR PROTO  │ VCODEC        VBR ACODEC     ABR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────
Audio_Only mp4                │ ~ 33.39MiB  356k m3u8_n │ audio only        mp4a.40.2 356k
160p       mp4 284x160     29 │ ~ 26.81MiB  286k m3u8_n │ avc1.4D000C  286k mp4a.40.2   0k
360p       mp4 640x360     29 │ ~ 65.91MiB  703k m3u8_n │ avc1.4D001E  703k mp4a.40.2   0k
480p       mp4 852x480     29 │ ~149.07MiB 1590k m3u8_n │ avc1.4D001F 1590k mp4a.40.2   0k
720p60     mp4 1280x720    59 │ ~334.62MiB 3569k m3u8_n │ avc1.4D0020 3569k mp4a.40.2   0k
1080p60    mp4 1920x1080  119 │ ~680.92MiB 7263k m3u8_n │ avc1.640033 7263k mp4a.40.2   0k Source
```

A working 60fps stream is in in the verbose log box

### Verbose log

```shell
yt-dlp.exe -f1080p60 https://www.twitch.tv/videos/121711674
[twitch:vod] 121711674: Downloading stream metadata GraphQL
ERROR: 'NoneType' object does not support item assignment
PS C:\temp> yt-dlp.exe -Uv -f1080p60 https://www.twitch.tv/videos/121711674
[debug] Command-line config: ['-Uv', '-f1080p60', 'https://www.twitch.tv/videos/121711674']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-103120-g5b62544dee-gc50f5460d2 (setts,fdk), ffprobe N-103120-g5b62544dee-gc50f5460d2, rtmpdump 2.4-20210219-gf1b83c1-GnuTLS_3.6.13-x86_64-static
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/121711674
[twitch:vod] 121711674: Downloading stream metadata GraphQL
ERROR: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\twitch.py", line 399, in _real_extract
  File "yt_dlp\extractor\twitch.py", line 307, in _download_info
TypeError: 'NoneType' object does not support item assignment

yt-dlp.exe -Uv https://www.twitch.tv/videos/1219809643
[debug] Command-line config: ['-Uv', 'https://www.twitch.tv/videos/1219809643']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-103120-g5b62544dee-gc50f5460d2 (fdk,setts), ffprobe N-103120-g5b62544dee-gc50f5460d2, rtmpdump 2.4-20210219-gf1b83c1-GnuTLS_3.6.13-x86_64-static
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1219809643
[twitch:vod] 1219809643: Downloading stream metadata GraphQL
[twitch:vod] 1219809643: Downloading video access token GraphQL
[twitch:vod] 1219809643: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] v1219809643: Downloading 1 format(s): 1080p60
[debug] Invoking downloader on "https://d1m7jfoe9zdc1j.cloudfront.net/df57ce0cae05b474923e_eposvox_44619855053_1638241714/chunked/index-dvr.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 903
[download] Destination: I don't even know [v1219809643].mp4
[download]   0.3% of ~9.79GiB at 12.46MiB/s ETA 24:35 (frag 3/903)

```
```

**Comment by voltagex** [comment]
Incorrect URL, closing.
