### ISSUE TITLE
Failed merging of webm audio and video ("ERROR: Postprocessing: Conversion failed!")

### ISSUE THREAD

**Issue by jberq** [yt-dlp/yt-dlp#1852]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### [webm @ 000001eadb81e740] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5350 >= 5333

There seems to be some trouble merging the audio and video tracks of [this YouTube video](https://www.youtube.com/watch?v=6acY-lsxi6w). 

What's leftover are two .webm files of the entire audio and video tracks. There's also is the .temp.webm file, which is only 322 frames (and less than 322 frames are playable in VLC). 5333 appears in the error, and it also appears in the Mediainfo of the temp file under 'extra'. That may or may not be relevant— just something I noticed. 

Here's the Mediainfo of the corrupted temp file:

```
@type                    : General
VideoCount               : 1
AudioCount               : 1
FileExtension            : webm
Format                   : WebM
Format_Version           : 4
FileSize                 : 1174152
Duration                 : 5.381
OverallBitRate           : 1745626
FrameRate                : 60.000
FrameCount               : 322
IsStreamable             : Yes
File_Created_Date        : UTC 2021-12-01 11:44:16.935
File_Created_Date_Local  : 2021-12-01 05:44:16.935
File_Modified_Date       : UTC 2021-12-01 11:47:20.735
File_Modified_Date_Local : 2021-12-01 05:47:20.735
Encoded_Application      : Lavf58.29.100
Encoded_Library          : Lavf58.29.100
extra                    : @{HTTP___YOUTUBE_COM_STREAMING_OTF_DURATIONS_112015=Segment-Count: 4 /
                           Segment-Durations-Ms: 5333,5334,5333,1050, / }
@type                             : Video
StreamOrder                       : 0
ID                                : 1
UniqueID                          : 1
Format                            : VP9
CodecID                           : V_VP9
Duration                          : 5.366000000
Width                             : 910
Height                            : 720
PixelAspectRatio                  : 1.000
DisplayAspectRatio                : 1.264
FrameRate_Mode                    : CFR
FrameRate                         : 60.000
FrameCount                        : 322
ColorSpace                        : YUV
Language                          : en
Default                           : Yes
Forced                            : No
colour_description_present        : Yes
colour_description_present_Source : Container
colour_range                      : Limited
colour_range_Source               : Container
matrix_coefficients               : BT.709
matrix_coefficients_Source        : Container

@type            : Audio
StreamOrder      : 1
ID               : 2
UniqueID         : 2
Format           : Opus
CodecID          : A_OPUS
Duration         : 5.381000000
Channels         : 2
ChannelPositions : Front: L R
ChannelLayout    : L R
SamplingRate     : 48000
SamplingCount    : 258288
BitDepth         : 32
Compression_Mode : Lossy
Delay            : 0.000
Delay_Source     : Container
Language         : en
Default          : Yes
Forced           : No
```

### Verbose log

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=6acY-lsxi6w', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=6acY-lsxi6w
[youtube] 6acY-lsxi6w: Downloading webpage
[youtube] 6acY-lsxi6w: Downloading android player API JSON
[youtube] 6acY-lsxi6w: Downloading MPD manifest
[youtube] 6acY-lsxi6w: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 6acY-lsxi6w: Downloading 1 format(s): 302+251
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1638381973/ei/NWWnYZCqCIOBtQfrgqTYCg/ip/99.116.9.108/id/e9a718fa5b318bac/source/youtube/requiressl/yes/playback_host/r3---sn-q4flrnel.googlevideo.com/mh/f_/mm/31%2C26/mn/sn-q4flrnel%2Csn-5uaezn6k/ms/au%2Conr/mv/m/mvi/3/pl/21/tx/24114338/txs/24114336%2C24114337%2C24114338/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1321250/vprv/1/mt/1638360074/fvip/3/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgCzk00Cej08l2VtY9wV4VGTMP5nvGxPQHalQlF8ePet4CIQDlcEZAXPxFKpCoOFH2ulR9s_h8VAQbNgRC-jXnTFhLuQ%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAMT7-YCHLjwrNSpsF_xfWUtN41OYZ30K8W-ySV9UOkM6AiBj8SGSanRAC9v65z4qyF1E3wAofIEpfeZTUzCVj_gEow%3D%3D"
[dashsegments] Total fragments: 5
[download] Destination: Super Metroid -- Impulse Mockball [6acY-lsxi6w].f302.webm
[download] 100% of 2.74MiB in 00:00
[debug] Invoking downloader on "https://r3---sn-q4fl6ns7.googlevideo.com/videoplayback?expire=1638381973&ei=NWWnYae3I4qiir4P1bmPwAk&ip=99.116.9.108&id=o-AGUUJSYtZODZm1zV87mMINO2b87DYYh1DtgIfrvAft2o&itag=251&source=youtube&requiressl=yes&mh=f_&mm=31%2C26&mn=sn-q4fl6ns7%2Csn-5ualdnls&ms=au%2Conr&mv=m&mvi=3&pl=21&initcwndbps=1280000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=256900&otfp=1&dur=17.101&lmt=1597278512602833&mt=1638360074&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgHK439NBJrjt3UV9gaTqDzoJylJXmjFx-VReNijJ6Fq0CIQCxvmMWSKZBCVNenI3SDPNsFkogAQnfA7rxQOd_V6C7Mg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgAsPNHNPc0BypJefTSldsHbQAXKdal0C13j_Xtin-LPMCIQDq9BDXEf2sYwZzordDgue-dF5x1vVqrQ7mlb-Qr5v8Ug%3D%3D"
[download] Destination: Super Metroid -- Impulse Mockball [6acY-lsxi6w].f251.webm
[download] 100% of 250.88KiB in 00:00
[Merger] Merging formats into "Super Metroid -- Impulse Mockball [6acY-lsxi6w].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Super Metroid -- Impulse Mockball [6acY-lsxi6w].f302.webm" -i "file:Super Metroid -- Impulse Mockball [6acY-lsxi6w].f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Super Metroid -- Impulse Mockball [6acY-lsxi6w].temp.webm"
[debug] ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'file:Super Metroid -- Impulse Mockball [6acY-lsxi6w].f302.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 4
                    : Segment-Durations-Ms: 5333,5334,5333,1050,
                    :
                    :
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 910x720, SAR 1:1 DAR 91:72, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:Super Metroid -- Impulse Mockball [6acY-lsxi6w].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:00:17.10, start: -0.007000, bitrate: 120 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, webm, to 'file:Super Metroid -- Impulse Mockball [6acY-lsxi6w].temp.webm':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 4
                    : Segment-Durations-Ms: 5333,5334,5333,1050,
                    :
                    :
    encoder         : Lavf58.29.100
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 910x720 [SAR 1:1 DAR 91:72], q=2-31, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[webm @ 00000157c79ae740] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5350 >= 5333
av_interleaved_write_frame(): Invalid argument
frame=  323 fps=0.0 q=-1.0 Lsize=    1147kB time=00:00:05.36 bitrate=1752.1kbits/s speed=1.77e+03x
video:1113kB audio:52kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3001, in process_info
  File "yt_dlp\YoutubeDL.py", line 3165, in post_process
  File "yt_dlp\YoutubeDL.py", line 3108, in run_pp
  File "yt_dlp\postprocessor\common.py", line 23, in run
  File "yt_dlp\postprocessor\common.py", line 118, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 815, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 280, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 317, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by DerBunteBall** [comment]
Check this: https://github.com/yt-dlp/FFmpeg-Builds

User --ffmpeg-location to tell yt-dlp where it is.

Best Regards

**Comment by pukkandan** [comment]
> * [x] I've searched the bugtracker for similar issues including closed ones. DO NOT post duplicates

The least you can do is see the pinned issues
