### ISSUE TITLE
fox.com.tr which airsTurkey series, news, shows [not fox.com]

### ISSUE THREAD

**Issue by yashoswalyo** [yt-dlp/yt-dlp#1856]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Global

### Example URLs

- Single video: https://www.fox.com.tr/Ask-Mantik-Intikam/bolum/22
- Playlist: https://www.fox.com.tr/Ask-Mantik-Intikam/bolumler

### Description

This website airs new episodes of Turkish dramas,News, Programs

### Verbose log

```shell
$ yt-dlp -Uv https://www.fox.com.tr/Ask-Mantik-Intikam/bolum/22
[debug] Command-line config: ['-Uv', 'https://www.fox.com.tr/Ask-Mantik-Intikam/bolum/22']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.13.0-22-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://www.fox.com.tr/Ask-Mantik-Intikam/bolum/22
[generic] 22: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 22: Downloading webpage
[generic] 22: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.fox.com.tr/Ask-Mantik-Intikam/bolum/22
Traceback (most recent call last):
  File "/home/yashoswal/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yashoswal/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "/home/yashoswal/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/home/yashoswal/.local/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3813, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.fox.com.tr/Ask-Mantik-Intikam/bolum/22
```

**Comment by yashoswalyo** [comment]
When this site will be added? any eta's

**Comment by Ashish0804** [comment]
> When this site will be added?

It will be added whenever a contributor has free time and wants to work on it.
If u need urgently, u can try hiring python developers from Freelance sites like fiverr and ask them to either make a plugin just for you or make a PR here

see https://github.com/yt-dlp/yt-dlp#plugins on info regarding plugins

**Comment by yashoswalyo** [comment]
Ok I'll wait

**Comment by coletdjnz** [comment]
For devs, for single video:

streaming data and some episode metadata is under `options = {` js code in player setup. `js_to_json` should be able to parse this.

There is also a JSON LD TVEpisode object with some more metadata

Title may need to be extracted from the HTML

**Comment by fenopa** [comment]
@coletdjnz are you able to implement this? nobody else seems to have any interest.

**Comment by coletdjnz** [comment]
> @coletdjnz are you able to implement this? nobody else seems to have any interest.

I don't have time to work on extractors these days sorry

**Comment by doe1080** [comment]
FOX has rebranded as [NOW](https://www.nowtv.com.tr/)
https://en.wikipedia.org/wiki/Now_(Turkish_TV_channel)
