### ISSUE TITLE
Network is unreachable 

### ISSUE THREAD

**Issue by TheOnlineRando** [yt-dlp/yt-dlp#1860]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi, im trying to download the following video:
https://www.youtube.com/watch?v=CmWFL4w4Fnw
My full command was the following:
"yt-dlp --remux-video mp4 "https://www.youtube.com/watch?v=CmWFL4w4Fnw" -Uv
The video will download for a little bit, and at some point it will fail and get an "[Errno 101] Network is not reachable"
I dont see any issues with my internet connection, I can consistently ping and load websites.

### Verbose log

```shell
user@hostname:~/Videos$ yt-dlp --remux-video mp4 https://www.youtube.com/watch?v=CmWFL4w4Fnw -Uv
[debug] Command-line config: ['--remux-video', 'mp4', 'https://www.youtube.com/watch?v=CmWFL4w4Fnw', '-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.10.0 (CPython 64bit) - Linux-5.15.5-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Crypto, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=CmWFL4w4Fnw
[youtube] CmWFL4w4Fnw: Downloading webpage
[youtube] CmWFL4w4Fnw: Downloading android player API JSON
[debug] Loading youtube-nsig.3ce4f9b8 from cache
[debug] [youtube] Decrypted nsig _8od89qhr3R3MVc_Z => pqQqmpb3r9ur6Q
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] CmWFL4w4Fnw: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://r6---sn-tt1eln7l.googlevideo.com/videoplayback?expire=1638400319&ei=36ynYbKSBobQlu8PwIWJ2AY&ip=206.174.179.230&id=o-AN_SScn7we1I2SLFBpyDVCCf9N9GjF-6th8BweJd1zGY&itag=303&source=youtube&requiressl=yes&mh=Of&mm=31%2C26&mn=sn-tt1eln7l%2Csn-vgqsrns6&ms=au%2Conr&mv=m&mvi=6&pl=20&initcwndbps=1727500&vprv=1&mime=video%2Fwebm&gir=yes&clen=1277005348&dur=8352.299&lmt=1638376522359130&mt=1638378305&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=3316222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgTMRP10XQdCkfGAFduzeVJXr3d4B_DFSUDwyX2nyN9OsCIQDZWu2JkUQpDuJNNkAu-ZW60eVd0TkMh3w8q0sqfk7_lg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKSAfxR4fBcC4nF3mWsUhXDb_Cmodzj2ev7F5cU16C61AiBQBHpDWKmOE66wMHfL-UST8BRLf71ya9hVDWHwW815kg%3D%3D"
[download] Resuming download at byte 583443910
[download] Destination: Message To My Ex-Girlfriend REUPLOAD (3rd upload) [CmWFL4w4Fnw].f303.webm
[download]  69.3% of 1.19GiB at  1.23MiB/s ETA 05:04
[download]  82.6% of 1.19GiB at  1.93MiB/s ETA 01:50
[download]  82.6% of 1.19GiB at  1.33MiB/s ETA 02:38
[download]  92.9% of 1.19GiB at  1.22MiB/s ETA 01:10ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/usr/lib64/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib64/python3.10/http/client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.10/http/client.py", line 1322, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.10/http/client.py", line 1271, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.10/http/client.py", line 1031, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.10/http/client.py", line 969, in send
    self.connect()
  File "/usr/lib64/python3.10/http/client.py", line 1441, in connect
    super().connect()
  File "/usr/lib64/python3.10/http/client.py", line 940, in connect
    self.sock = self._create_connection(
  File "/usr/lib64/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib64/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2916, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2654, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 421, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 372, in real_download
    establish_connection()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    raise err
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 114, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3385, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 2929, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib64/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
```

**Comment by pukkandan** [comment]
> OSError: [Errno 101] Network is unreachable

That means your internet disconnected. Make sure you have a stable connection and try again
