### ISSUE TITLE
add support for salto.fr

### ISSUE THREAD

**Issue by MarcMush** [yt-dlp/yt-dlp#1885]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

- Single video: https://www.salto.fr/les-petits-meurtres-dagatha-christie-p_47900/s3-e3-c_384948
- Multiple videos: https://www.salto.fr/les-petits-meurtres-dagatha-christie-p_47900

### Description

account must be created in France, once created it should be available in EU. 1 month free trial

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--cookies', '.\\salto.fr_cookies.txt', 'https://www.salto.fr/les-petits-meurtres-dagatha-christie-p_47900/s3-e3-c_384948']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://www.salto.fr/les-petits-meurtres-dagatha-christie-p_47900/s3-e3-c_384948
[generic] s3-e3-c_384948: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] s3-e3-c_384948: Downloading webpage
[generic] s3-e3-c_384948: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.salto.fr/les-petits-meurtres-dagatha-christie-p_47900/s3-e3-c_384948
Traceback (most recent call last):
  File "C:\Users\Marc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Marc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Marc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\extractor\common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Marc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\extractor\generic.py", line 3813, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.salto.fr/les-petits-meurtres-dagatha-christie-p_47900/s3-e3-c_384948
```

**Comment by kissifrot** [comment]
Hello, any news on this?
