### ISSUE TITLE
ceskatelevize ivysilani

### ISSUE THREAD

**Issue by jirih** [yt-dlp/yt-dlp#1899]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

The Czech TV has changed its frontend today.
domains: *.ceskatelevize.cz  and redirects from ivysilani.cz and ceskatelevize.cz

Examples:
https://www.ceskatelevize.cz/porady/10117034229-168-hodin/221452801101205/
https://www.ceskatelevize.cz/porady/10606368873-abecede-s-michalem/214543111100023/
https://www.ceskatelevize.cz/porady/899022-sanitka/284310910140011/
https://edu.ceskatelevize.cz/video/5248-proc-padaji-listy?vsrc=predmet&vsrcid=dle-rocnich-obdobi-a-svatku%7Epredskolni

Unfortunately, some parts of the web has a different form, for example: https://decko.ceskatelevize.cz/africka-abeceda (no direct links to each episode is visible). I guess, support for the https://www.ceskatelevize.cz/porady/* would be sufficient at this point.

The backend should not change much. However, I tried to use directly mpd files to download videos, but unsuccessfully. It ends with ERROR: [generic] 61924494877969676-pc: Requested format is not available

It does not seem that the used urls would contain DRMed videos (even when the Czech television uses DRM every now and then). All mentioned urls are playable from abroad.

Please note that the mpd files are quickly expiring. Trying to call the same command I present lower, will produce 403.
Please ignore my ffmpeg misconfiguration, it isn't relevant.

### Verbose log

```shell
$ yt-dlp -Uv https://www.ceskatelevize.cz/porady/10117034229-168-hodin/221452801101205/
[debug] Command-line config: ['-Uv', 'https://www.ceskatelevize.cz/porady/10117034229-168-hodin/221452801101205/']
[debug] User config file: /home/pi/.config/yt-dlp/config
[debug] User config: ['--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', '--no-check-certificate', '-o', '~/Elements/temp/youtube-dl/%(autonumber)03d_%(title)s.%(ext)s', '--no-mtime', '--format', 'bestvideo[ext=mp4][height<=1080][fps<=30]+bestaudio[ext=m4a]/best[ext=mp4][height<=1080][fps<=30]/best[height<=1080][fps<=30]/best', '--merge-output-format', 'mp4', '--ffmpeg-location', '/data/data/com.termux/files/usr/bin/ffmpeg', '--all-subs', '-i', '--add-metadata', '--merge-output-format', 'mkv']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.7.3 (CPython 32bit) - Linux-5.10.63-v7l+-armv7l-with-debian-10.11
WARNING: ffmpeg-location /data/data/com.termux/files/usr/bin/ffmpeg does not exist! Continuing without ffmpeg.
[debug] exe versions: phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
WARNING: ffmpeg-location /data/data/com.termux/files/usr/bin/ffmpeg does not exist! Continuing without ffmpeg.
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [CeskaTelevize] Extracting URL: https://www.ceskatelevize.cz/porady/10117034229-168-hodin/221452801101205/
[CeskaTelevize] 221452801101205: Downloading webpage
ERROR: [CeskaTelevize] 221452801101205: Unable to extract iframe player url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/extractor/ceskatelevize.py", line 105, in _real_extract
    webpage, 'iframe player url', group='url')), query={'autoStart': 'true'})
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 1171, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract iframe player url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/extractor/ceskatelevize.py", line 105, in _real_extract
    webpage, 'iframe player url', group='url')), query={'autoStart': 'true'})
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 1171, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract iframe player url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 623, in extract
    raise type(e)(e.msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [CeskaTelevize] 221452801101205: Unable to extract iframe player url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.


$ yt-dlp -Uv "https://ivys-vst13-6.o2tv.cz/atip/a1af54eee76502860e1c58517f3bc35e/1638791782795/61924494
877969676-pc.mpd?userId=6deab226-9bd8-47a1-a237-5dd411e0c2bb"
[debug] Command-line config: ['-Uv', 'https://ivys-vst13-6.o2tv.cz/atip/a1af54eee76502860e1c58517f3bc35e/1638791782795/61924494877969676-pc.mpd?userId=6deab226-9bd8-47a1-a237-5dd411e0c2bb']
[debug] User config file: /home/pi/.config/yt-dlp/config
[debug] User config: ['--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', '--no-check-certificate', '-o', '~/Elements/temp/youtube-dl/%(autonumber)03d_%(title)s.%(ext)s', '--no-mtime', '--format', 'bestvideo[ext=mp4][height<=1080][fps<=30]+bestaudio[ext=m4a]/best[ext=mp4][height<=1080][fps<=30]/best[height<=1080][fps<=30]/best', '--merge-output-format', 'mp4', '--ffmpeg-location', '/data/data/com.termux/files/usr/bin/ffmpeg', '--all-subs', '-i', '--add-metadata', '--merge-output-format', 'mkv']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.7.3 (CPython 32bit) - Linux-5.10.63-v7l+-armv7l-with-debian-10.11
WARNING: ffmpeg-location /data/data/com.termux/files/usr/bin/ffmpeg does not exist! Continuing without ffmpeg.
[debug] exe versions: phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
WARNING: ffmpeg-location /data/data/com.termux/files/usr/bin/ffmpeg does not exist! Continuing without ffmpeg.
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://ivys-vst13-6.o2tv.cz/atip/a1af54eee76502860e1c58517f3bc35e/1638791782795/61924494877969676-pc.mpd?userId=6deab226-9bd8-47a1-a237-5dd411e0c2bb
[generic] 61924494877969676-pc: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 61924494877969676-pc: Downloading webpage
[generic] 61924494877969676-pc: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [generic] 61924494877969676-pc: Requested format is not available
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1412, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1462, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2491, in process_video_result
    video_id=info_dict['id'], ie=info_dict['extractor'])
yt_dlp.utils.ExtractorError: [generic] 61924494877969676-pc: Requested format is not available
```

**Comment by mkubecek** [comment]
As part of the new, "improved", iVysílání, they added a new layer of obfuscation: the iframe with player is no longer included in the page from the start and is only created after clicking the "play" button.

**Comment by mkubecek** [comment]
Tentative extractor update: https://github.com/mkubecek/yt-dlp/commit/5c531b32c1b2

**Comment by zippy2** [comment]
I'm sorry, but I think that the extractor is still broken. For instance:

```
$ yt-dlp --verbose "https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217/"
[debug] Command-line config: ['--verbose', 'https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.5-gentoo-x86_64-x86_64-AMD_Ryzen_9_3900X_12-Core_Processor-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Crypto, sqlite
[debug] Proxy map: {}
[debug] [CeskaTelevize] Extracting URL: https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217/
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading MPD manifest
WARNING: [CeskaTelevize] Failed to download MPD manifest: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1145)>
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading m3u8 information
WARNING: [CeskaTelevize] Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1145)>
[download] Downloading playlist: 17. prosinec - Interview ČT24 | Česká televize
[CeskaTelevize] playlist 17. prosinec - Interview ČT24 | Česká televize: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
ERROR: [CeskaTelevize] 61924494877975106: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
@zippy2 seems to be separate issue than what OP reported. So I've created #2043
