### ISSUE TITLE
[Funimation] Error download fragment

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#1910]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I tried to download some chapters of this series but at some point there are fragments that do not download or simply does not even start the download and automatically gives me error.

[](https://www.funimation.com/v/banished-from-the-heros-party-i-decided-to-live-a-quiet-life-in-the-countryside/youre-not-a-true-comrade)

### Verbose log

```shell
C:\youtube-dl>yt-dlp --config-location funimation.conf https://www.funimation.com/v/banished-from-the-heros-party-i-decided-to-live-a-quiet-life-in-the-countryside/youre-not-a-true-comrade
[debug] Command-line config: ['--config-location', 'funimation.conf', 'https://www.funimation.com/v/banished-from-the-heros-party-i-decided-to-live-a-quiet-life-in-the-countryside/youre-not-a-true-comrade']
[debug] Custom config file: funimation.conf
[debug] Custom config: ['-f', '(bv[height<=720]+ba/b[height<=720])[format_note*=Uncut]/\n(bv[height<=720]+ba/b[height<=720])[format_note*=Simulcast]', '--sub-lang', 'all,-en_Uncut_CC,-en_CC,-pt,-pt_Uncut', '--embed-subs', '--sub-format', 'srt', '-o', '%(extractor_key)s/%(series)s/%(series)s S%(season_number)sE%(episode_number)s - %(episode)s.%(ext)s', '--cookies', 'cookies-funimation-com.txt', '-n', '--extractor-args', 'funimation:language=japanese', '--add-metadata', '-v', '--embed-chapters']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071af6] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 99148c6a3
[debug] Python version 3.9.7 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg n4.4.1-1-gb5b784d5ad-20211031 (setts), ffprobe n4.4.1-1-gb5b784d5ad-20211031
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: https://www.funimation.com/v/banished-from-the-heros-party-i-decided-to-live-a-quiet-life-in-the-countryside/youre-not-a-true-comrade
[funimation:page] banished-from-the-heros-party-i-decided-to-live-a-quiet-life-in-the-countryside_youre-not-a-true-comrade: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/3619422
[Funimation] 3619422: Downloading player webpage for 3619422
[Funimation] youre-not-a-true-comrade: Downloading player webpage for Simulcast japanese (2774956)
[Funimation] youre-not-a-true-comrade: Downloading Simulcast japanese (2774956) JSON
[Funimation] youre-not-a-true-comrade: Downloading Simulcast japanese (2774956) m3u8 information
[debug] Sort order given by extractor: lang, source
[debug] Formats sorted by: hasvid, ie_pref, lang, source, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Downloading subtitles: en, es
[info] 2774660: Downloading 1 format(s): 2774956-hls-3811+2774956-hls-audio-aacl-256-Japanese
[info] Writing video subtitles to: Funimation\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside S1E1 - You're Not a True Comrade.en.srt
[debug] Invoking downloader on "https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2597764/ee12735e-01eb-4d88-81d2-7be68724f314_english_full.srt"
[download] Destination: Funimation\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside S1E1 - You're Not a True Comrade.en.srt
[download] 100% of 25.41KiB in 00:00
[info] Writing video subtitles to: Funimation\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside S1E1 - You're Not a True Comrade.es.srt
[debug] Invoking downloader on "https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2597764/ee12735e-01eb-4d88-81d2-7be68724f314_spanishlatinamerica_full.srt"
[download] Destination: Funimation\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside S1E1 - You're Not a True Comrade.es.srt
[download] 100% of 25.33KiB in 00:00
[debug] Invoking downloader on "https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2597764/ee12735e-01eb-4d88-81d2-7be68724f314strnv-hl152_streaming_video_1280_720_4500000_index.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjU5Nzc2NC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjM4NDgwODk0fX19XX0_&Signature=Z-Ka87o~64NcqS9QOiLCDnXlJFEJwxitQp8ujI4bL95wUSNfHDn4jL3ta-DlD57GWcsVek3oAUPUdqC5xk9clHLYpSrtAAkPX1cwSiP3qTQwqNbKlTkgh8-4t~D-wXIvdpimHcyvAJbeO6OT6yA17HeVM-q-nahHREhp2GBk8vCYyJ8ybLlfGx9tUft7xZiGWCrw2ApUt1O3Az-rHmJunzTbfDjh6uPi6X5TXbJkBRHuw4anyrdPkmbEgntgj-VHSriR~gZuWHRayI~lLJNPBhg-m-JFMuYwQoUmysPZww6WakDgpywbRlukRJkyUmnwaHTEMQSMk5aq4W9rCfrj8g__&rt=1420044"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 714
[download] Destination: Funimation\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside S1E1 - You're Not a True Comrade.f2774956-hls-3811.mp4
[download]   1.3% of ~606.99MiB at 144.38KiB/s ETA 44:01 (frag 9/714)ERROR: unable to open for writing: [Errno 2] No such file or directory: "Funimation\\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside\\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside S1E1 - You're Not a True Comrade.f2774956-hls-3811.mp4.part-Frag10.part"
Traceback (most recent call last):
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\downloader\http.py", line 266, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\utils.py", line 2094, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
FileNotFoundError: [Errno 2] No such file or directory: "Funimation\\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside\\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside S1E1 - You're Not a True Comrade.f2774956-hls-3811.mp4.part-Frag10.part"

ERROR: unable to download video data: [Errno 2] No such file or directory: "Funimation\\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside\\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside S1E1 - You're Not a True Comrade.f2774956-hls-3811.mp4.part-Frag10"
Traceback (most recent call last):
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 2918, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 2656, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\downloader\common.py", line 421, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\downloader\hls.py", line 358, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\downloader\fragment.py", line 487, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\downloader\fragment.py", line 427, in download_fragment
    success, frag_content = self._download_fragment(ctx, fragment['url'], info_dict, headers)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\downloader\fragment.py", line 138, in _download_fragment
    return True, self._read_fragment(ctx)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\downloader\fragment.py", line 141, in _read_fragment
    down, frag_sanitized = sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\utils.py", line 2094, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
FileNotFoundError: [Errno 2] No such file or directory: "Funimation\\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside\\Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside S1E1 - You're Not a True Comrade.f2774956-hls-3811.mp4.part-Frag10"
```

**Comment by pukkandan** [comment]
Use a smaller filename

**Comment by CZeil** [comment]
What is the reason for this?
I just tried a different output template and it worked.

by default I use this one
`-o "%(extractor_key)s/%(series)s/%(series)s S%(season_number)sE%(episode_number)s - %(episode)s.%(ext)s"`

and I replaced it this way and it is downloading the file.
`-o "%(extractor_key)s/%(series)s/S%(season_number)sE%(episode_number)s - %(episode)s.%(ext)s"`

**Comment by pukkandan** [comment]
Your filesystem cannot handle filenames that are so long

**Comment by CZeil** [comment]
dang, windows is always crashing on me xD

**Comment by pukkandan** [comment]
Not really windows' fault. Most UNIX systems also cannot handle filenames with each path segment > 255 chars

**Comment by Jules-A** [comment]
> Edit: Actually, in your case, each segment is < 255 chars. So yeah, windows' fault

Doesn't help all this >.f2774956-hls-3811.mp4.part-Frag10.part

gets appended to the name though... Really needs to be a better way of handling this imo.

**Comment by CZeil** [comment]
> 

Maybe if you could add an alias ID for example I download a video + audio from funimation and the video has this ID 2774956-hls-3811 and the audio this 2774956-hls-audio-aacl-256-Japanese. Then to avoid that the name of the file to be downloaded is added the Alias ID

The video file would not show this ID 2774956-hls-3811 but the Alias ID could be something like (1v) and the audio file would not show this 2774956-hls-audio-aacl-256-Japanese but this (1a).

It's an idea that I came up with, maybe the coding part is more difficult to do.

**Comment by pukkandan** [comment]
The id must be at the end of the filename. It is there for a reason. If someone wants to instead shorten the format ids of funimation extractor, that can be considered

**Comment by pukkandan** [comment]
Related: https://github.com/yt-dlp/yt-dlp/issues/1136 https://github.com/yt-dlp/yt-dlp/issues/334

**Comment by CZeil** [comment]
> The format_id must be at the end of the filename. It is there for a reason. If someone wants to instead shorten the format ids of funimation extractor, that can be considered

I say this so that these problems do not occur as it happened to me, and as I do not know programming report this as a bug because I did not know what it was due. But I do consider that the ids in the files to download should be shortened.
