### ISSUE TITLE
[crunchyroll:beta] No cookies support

### ISSUE THREAD

**Issue by SamusAranX** [yt-dlp/yt-dlp#1911]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

I noticed some episodes (apparently only ones that require a login) can't be downloaded. Trying to run yt-dlp without the cookies file results in this error:
> ERROR: [crunchyroll] 821202: This is a sample clip. To watch the full video, start a free trial today!

*With* the cookies file taken from a valid login, I get the behavior demonstrated in the log.

I'm using a self-hosted VPN on a US server and I can confirm the episode in question (https://beta.crunchyroll.com/watch/G9DUEP2JW/pressure) is watchable in my browser.

Let me know if you need more info. Short of actual CR credentials, I'll try my best to provide it.

### Verbose log

```shell
$ yt-dlp "https://beta.crunchyroll.com/watch/G9DUEP2JW/pressure" --all-subs --cookies ../crunchyroll.com_cookies.txt --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36" --verbose
[debug] Command-line config: ['https://beta.crunchyroll.com/watch/G9DUEP2JW/pressure', '--all-subs', '--cookies', '../crunchyroll.com_cookies.txt', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.10.0 (CPython 64bit) - macOS-12.0.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/G9DUEP2JW/pressure
[crunchyroll:beta] pressure: Downloading webpage
[debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/blade-runner-black-lotus/pressure-821202
[crunchyroll] 821202: Downloading webpage
[crunchyroll] 821202: Downloading media info for 360p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 821202: Downloading stream info for 360p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 821202: Downloading media info for 480p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 821202: Downloading stream info for 480p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 821202: Downloading media info for 720p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 821202: Downloading stream info for 720p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 821202: Downloading media info for 1080p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 821202: Downloading stream info for 1080p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 821202: Downloading media info
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
WARNING: [crunchyroll] unable to extract series; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: [crunchyroll] 821202: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1412, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1462, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2346, in process_video_result
    self.raise_no_formats(info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 933, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [crunchyroll] 821202: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by CZeil** [comment]
I would recommend that you re-extract the cookie information from your browser, I just tried with my user's cookies and it does give me video information.

I tell you to check the cookies because this has also happened to me and the problem ends up being the cookies, sometimes we are the end users who fail.

```
~ $ yt-dlp -F https://beta.crunchyroll.com/watch/G9DUEP2JW/pressure --cookies storage/shared/anime-dl/cookies-crunchyroll-com.txt
[crunchyroll:beta] pressure: Downloading webpage
[crunchyroll] 821202: Downloading webpage
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP-hardsub-frFR information
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP-hardsub-ptBR information
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP-hardsub-deDE information
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP information
WARNING: [crunchyroll] Failed to download m3u8 information: The read operation timed out
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP-hardsub-itIT information
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
[crunchyroll] 821202: Downloading media info
WARNING: [crunchyroll] Unable to download XML: The read operation timed out
[info] Available formats for 821202:
ID                                          EXT RESOLUTION FPS │   TBR PROTO  │ VCODEC        VBR ACODEC    ABR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
adaptive_hls-audio-jaJP-hardsub-ptBR-562-0  mp4 428x240     23 │  562k m3u8_n │ avc1.42c015  562k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-ptBR-562-1  mp4 428x240     23 │  562k m3u8_n │ avc1.42c015  562k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-frFR-563-0  mp4 428x240     23 │  563k m3u8_n │ avc1.42c015  563k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-frFR-563-1  mp4 428x240     23 │  563k m3u8_n │ avc1.42c015  563k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-itIT-563-0  mp4 428x240     23 │  563k m3u8_n │ avc1.42c015  563k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-itIT-563-1  mp4 428x240     23 │  563k m3u8_n │ avc1.42c015  563k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-deDE-563-0  mp4 428x240     23 │  563k m3u8_n │ avc1.42c015  563k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-deDE-563-1  mp4 428x240     23 │  563k m3u8_n │ avc1.42c015  563k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-frFR-1094-0 mp4 640x360     23 │ 1094k m3u8_n │ avc1.4d401e 1094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-frFR-1094-1 mp4 640x360     23 │ 1094k m3u8_n │ avc1.4d401e 1094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-deDE-1094-0 mp4 640x360     23 │ 1094k m3u8_n │ avc1.4d401e 1094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-deDE-1094-1 mp4 640x360     23 │ 1094k m3u8_n │ avc1.4d401e 1094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-ptBR-1094-0 mp4 640x360     23 │ 1094k m3u8_n │ avc1.4d401e 1094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-ptBR-1094-1 mp4 640x360     23 │ 1094k m3u8_n │ avc1.4d401e 1094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-itIT-1094-0 mp4 640x360     23 │ 1094k m3u8_n │ avc1.4d401e 1094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-itIT-1094-1 mp4 640x360     23 │ 1094k m3u8_n │ avc1.4d401e 1094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-ptBR-2093-0 mp4 848x480     23 │ 2093k m3u8_n │ avc1.4d401f 2093k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-ptBR-2093-1 mp4 848x480     23 │ 2093k m3u8_n │ avc1.4d401f 2093k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-itIT-2093-0 mp4 848x480     23 │ 2093k m3u8_n │ avc1.4d401f 2093k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-itIT-2093-1 mp4 848x480     23 │ 2093k m3u8_n │ avc1.4d401f 2093k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-deDE-2094-0 mp4 848x480     23 │ 2094k m3u8_n │ avc1.4d401f 2094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-deDE-2094-1 mp4 848x480     23 │ 2094k m3u8_n │ avc1.4d401f 2094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-frFR-2094-0 mp4 848x480     23 │ 2094k m3u8_n │ avc1.4d401f 2094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-frFR-2094-1 mp4 848x480     23 │ 2094k m3u8_n │ avc1.4d401f 2094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-ptBR-4112-0 mp4 1280x720    23 │ 4112k m3u8_n │ avc1.640028 4112k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-ptBR-4112-1 mp4 1280x720    23 │ 4112k m3u8_n │ avc1.640028 4112k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-frFR-4112-0 mp4 1280x720    23 │ 4112k m3u8_n │ avc1.640028 4112k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-frFR-4112-1 mp4 1280x720    23 │ 4112k m3u8_n │ avc1.640028 4112k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-deDE-4112-0 mp4 1280x720    23 │ 4112k m3u8_n │ avc1.640028 4112k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-deDE-4112-1 mp4 1280x720    23 │ 4112k m3u8_n │ avc1.640028 4112k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-itIT-4113-0 mp4 1280x720    23 │ 4113k m3u8_n │ avc1.640028 4113k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-itIT-4113-1 mp4 1280x720    23 │ 4113k m3u8_n │ avc1.640028 4113k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-frFR-8104-0 mp4 1920x1080   23 │ 8104k m3u8_n │ avc1.640028 8104k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-frFR-8104-1 mp4 1920x1080   23 │ 8104k m3u8_n │ avc1.640028 8104k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-itIT-8104-0 mp4 1920x1080   23 │ 8104k m3u8_n │ avc1.640028 8104k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-itIT-8104-1 mp4 1920x1080   23 │ 8104k m3u8_n │ avc1.640028 8104k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-ptBR-8104-0 mp4 1920x1080   23 │ 8104k m3u8_n │ avc1.640028 8104k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-ptBR-8104-1 mp4 1920x1080   23 │ 8104k m3u8_n │ avc1.640028 8104k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-deDE-8104-0 mp4 1920x1080   23 │ 8104k m3u8_n │ avc1.640028 8104k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-deDE-8104-1 mp4 1920x1080   23 │ 8104k m3u8_n │ avc1.640028 8104k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-enUS-562-0  mp4 428x240     23 │  562k m3u8_n │ avc1.42c015  562k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-enUS-562-1  mp4 428x240     23 │  562k m3u8_n │ avc1.42c015  562k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-enUS-1094-0 mp4 640x360     23 │ 1094k m3u8_n │ avc1.4d401e 1094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-enUS-1094-1 mp4 640x360     23 │ 1094k m3u8_n │ avc1.4d401e 1094k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-enUS-2093-0 mp4 848x480     23 │ 2093k m3u8_n │ avc1.4d401f 2093k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-enUS-2093-1 mp4 848x480     23 │ 2093k m3u8_n │ avc1.4d401f 2093k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-enUS-4112-0 mp4 1280x720    23 │ 4112k m3u8_n │ avc1.640028 4112k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-enUS-4112-1 mp4 1280x720    23 │ 4112k m3u8_n │ avc1.640028 4112k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-enUS-8105-0 mp4 1920x1080   23 │ 8105k m3u8_n │ avc1.640028 8105k mp4a.40.2  0k [jaJP]
adaptive_hls-audio-jaJP-hardsub-enUS-8105-1 mp4 1920x1080   23 │ 8105k m3u8_n │ avc1.640028 8105k mp4a.40.2  0k [jaJP]
~ $ yt-dlp --list-subs https://beta.crunchyroll.com/watch/G9DUEP2JW/pressure --cookies storage/shared/anime-dl/cookies-crunchyroll-com.txt
[crunchyroll:beta] pressure: Downloading webpage
[crunchyroll] 821202: Downloading webpage
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP-hardsub-frFR information
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP-hardsub-ptBR information
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP-hardsub-deDE information
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP information
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP-hardsub-itIT information
[crunchyroll] 821202: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
[crunchyroll] 821202: Downloading media info
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
Available subtitles for 821202:
Language Formats
enUS     ass
frFR     ass
ptBR     ass
itIT     ass
deDE     ass
ruRU     ass
arME     ass
esLA     ass
esES     ass
```

**Comment by SamusAranX** [comment]
I tried that and it's not working. I wouldn't have filed this issue if the fix was that easy.

**Comment by SamusAranX** [comment]
Actually, something I just now noticed is that it's in fact *all* episodes that fail if I use a cookies.txt.

```
yt-dlp "https://beta.crunchyroll.com/watch/G7PU4VDEG/the-doll-hunt" -F
```
works, but
```
yt-dlp "https://beta.crunchyroll.com/watch/G7PU4VDEG/the-doll-hunt" -F --cookies ../crunchyroll.com_cookies.txt
```
does not.

I'm using this extension (https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) to generate a cookies.txt and in every other context that requires cookies, the files generated by the extension do work. What's happening here?

**Comment by CZeil** [comment]
Yes indeed as you mention, the problem here is generating the cookies of the beta version, unfortunately there is the problem that US users this will be the new default site.

I was telling you that it is easily solved because I can go back to the classic page and extract the cookies and that's why it works normally.

**Comment by pukkandan** [comment]
If you are unable to extract cookies of `crunchyroll.com` specifically (not beta), try exporting ALL cookies in the browser or with `--cookies-from-browser`

**Comment by meap98** [comment]
so this might be off topic but I can't find many post about Crunchyroll Beta and I want to know what's going on
![unknown-3](https://user-images.githubusercontent.com/47130959/145935129-eebe6294-e3a4-400c-9d65-bdf0e363db32.png)

**Comment by tejing1** [comment]
I'm having exactly the same issue. I've tried it with both a `cookies.txt` file exported via the 'Get cookies.txt' extension and with `--cookies-from-browser brave` (I wasn't aware of that option before I read this issue, so thanks for that! :smile:) and get the same result either way. I've also checked that I can play this fine in the browser from which I'm grabbing the cookies.

I've used the `cookies.txt` method successfully before on funimation.com to get around age restrictions (though I don't have a paid membership there), but I'm at a loss about what to do here.
```
$ nix run nixpkgs-unstable\#yt-dlp -- -F https://beta.crunchyroll.com/watch/GVWU0PMWX/valley-of-despair --cookies-from-browser brave --verbose
[debug] Command-line config: ['-F', 'https://beta.crunchyroll.com/watch/GVWU0PMWX/valley-of-despair', '--cookies-from-browser', 'brave', '--verbose']
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "/home/tejing/.config/BraveSoftware/Brave-Browser/Default/Cookies"
[Cookies] Extracted 1756 cookies from brave
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.25 [87e049962]
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.10.81-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/GVWU0PMWX/valley-of-despair
[crunchyroll:beta] valley-of-despair: Downloading webpage
[debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/the-faraway-paladin/valley-of-despair-819831
[crunchyroll] 819831: Downloading webpage
[crunchyroll] 819831: Downloading media info for 360p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 819831: Downloading stream info for 360p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 819831: Downloading media info for 480p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 819831: Downloading stream info for 480p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 819831: Downloading media info for 720p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 819831: Downloading stream info for 720p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 819831: Downloading media info for 1080p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 819831: Downloading stream info for 1080p
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[crunchyroll] 819831: Downloading media info
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
WARNING: [crunchyroll] unable to extract series; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: [crunchyroll] 819831: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/nix/store/h9m08qdn56jxh9nkys1jgw07p29cpykb-python3.9-yt-dlp-2021.12.25/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1352, in wrapper
    return func(self, *args, **kwargs)
  File "/nix/store/h9m08qdn56jxh9nkys1jgw07p29cpykb-python3.9-yt-dlp-2021.12.25/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1435, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/nix/store/h9m08qdn56jxh9nkys1jgw07p29cpykb-python3.9-yt-dlp-2021.12.25/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1487, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/nix/store/h9m08qdn56jxh9nkys1jgw07p29cpykb-python3.9-yt-dlp-2021.12.25/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2376, in process_video_result
    self.raise_no_formats(info_dict)
  File "/nix/store/h9m08qdn56jxh9nkys1jgw07p29cpykb-python3.9-yt-dlp-2021.12.25/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 943, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [crunchyroll] 819831: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```
Also, in case it's useful, this is the `cookies.txt` I using with everything but the cookie content field:
```
$ egrep -v '^(#|$)' crunchyroll.com_cookies.txt | cut -f1-6
www.crunchyroll.com	FALSE	/welcome-to-demon-school-iruma-kun	FALSE	1644138795	initial_referrer
www.crunchyroll.com	FALSE	/so-im-a-spider-so-what	FALSE	1644138792	initial_referrer
.www.crunchyroll.com	TRUE	/	FALSE	0	usprivacy
www.crunchyroll.com	FALSE	/	FALSE	1656448759	initial_referrer
.beta.crunchyroll.com	TRUE	/	FALSE	0	usprivacy
.www.crunchyroll.com	TRUE	/	FALSE	1642133082	OptanonControl
.crunchyroll.com	TRUE	/	FALSE	1642133082	c_visitor
store.crunchyroll.com	FALSE	/	TRUE	1654859157	secure_customer_sig
.crunchyroll.com	TRUE	/	FALSE	1654859157	_y
.crunchyroll.com	TRUE	/	FALSE	1654859157	_shopify_y
store.crunchyroll.com	FALSE	/	TRUE	1654859158	ssUserId
store.crunchyroll.com	FALSE	/	TRUE	0	ssSessionIdNamespace
store.crunchyroll.com	FALSE	/	TRUE	1654859083	_isuid
.store.crunchyroll.com	TRUE	/	TRUE	1654859158	swym-pid
.store.crunchyroll.com	TRUE	/	TRUE	1654859158	swym-swymRegid
.store.crunchyroll.com	TRUE	/	TRUE	1654859083	swym-email
.store.crunchyroll.com	TRUE	/	TRUE	1654859158	swym-cu_ct
.store.crunchyroll.com	TRUE	/	FALSE	1654859105	OptanonAlertBoxClosed
store.crunchyroll.com	FALSE	/	TRUE	1654859105	ssViewedProducts
.store.crunchyroll.com	TRUE	/	TRUE	1654859158	swym-instrumentMap
store.crunchyroll.com	FALSE	/	FALSE	1654859158	__kla_id
.store.crunchyroll.com	TRUE	/	FALSE	1654859158	OptanonConsent
.crunchyroll.com	TRUE	/	FALSE	1656450721	ajs_anonymous_id
www.crunchyroll.com	FALSE	/	FALSE	1640976227	cf_can_cache
.crunchyroll.com	TRUE	/	TRUE	1642108320	etp_rt
.crunchyroll.com	TRUE	/	FALSE	0	session_id
.crunchyroll.com	TRUE	/	FALSE	1656450721	ajs_user_id
.beta.crunchyroll.com	TRUE	/	FALSE	1656448788	OptanonControl
.crunchyroll.com	TRUE	/	TRUE	1640900515	__cf_bm
.beta.crunchyroll.com	TRUE	/	TRUE	1656450716	OptanonConsent
.www.crunchyroll.com	TRUE	/	TRUE	1656450721	OptanonConsent
```

**Comment by tejing1** [comment]
I expect it does happen for US free accounts as well.

If I understand the code correctly, the beta crunchyroll code merely extracts enough information from the beta page to find the correct non-beta page, then invokes a normal non-beta download. This works fine without logging in, or for those outside the US, but for a logged in user in the US, the non-beta pages just forcibly redirect you to the beta pages, so the non-beta code fails to understand the page it gets back.

If I'm correct, then to fix this someone's going to have to write the code to actually parse the beta pages.

**Comment by tejing1** [comment]
I wrote a bash script to download from beta crunchyroll premium, based heavily on kamyroll. It doesn't do any metadata handling, but it'll get you a video file with english subtitles. Edit to taste.

I'm not a python programmer, and don't know how yt-dlp works internally either, so I'm not confident implementing this in yt-dlp, but hopefully the shell script makes that easier for whoever decides to do it. It's well commented and should be pretty easy to follow.
```bash
#! /usr/bin/env bash

cookie_file="cookies.txt"

# returns a "username=foo&password=bar"-style string with values from pass
getcreds() {
    pass show crunchyroll.com | jq -sRr \
      'capture("\\nusername: (?<user>.+?)\\n";"m")+capture("\\A(?<pass>.+?)\\n";"m")|"username=\(.user)&password=\(.pass)"'
}

# base url of the api
api_base="https://beta-api.crunchyroll.com"

# copied from kamyroll. don't know where it comes from
initial_authorization="Authorization: Basic aHJobzlxM2F3dnNrMjJ1LXRzNWE6cHROOURteXRBU2Z6QjZvbXVsSzh6cUxzYTczVE1TY1k="

# parse $1 with jq. all further arguments are passed through to jq
parse() {
    local json="$1"
    shift
    jq "$@" <<<"$json"
}

# make an api call to endpoint $1, any further arguments are passed to jq to filter the result
api_call() {
    # test if endpoint is a relative path
    if [ "${1#/}" == "$1" ]; then
        # relative. place in api dir
        local endpoint="$api_dir/$1"
    else
        # already absolute. leave it be
        local endpoint="$1"
    fi
    # remove endpoint argument, leaving any remaining arguments for jq
    shift

    # accumulate arguments in an array variable
    local -a curl_args=()

    # silent, but still show errors, and follow redirects
    curl_args+=(-sSL)

    # send previous cookies, if available
    [ -e "$cookie_file" ] && curl_args+=(-b "$cookie_file")

    # save new cookies
    curl_args+=(-c "$cookie_file")

    # use authorization header
    curl_args+=(-H "$authorization")

    # send credentials if aimed at the auth endpoint
    if [ "$endpoint" == "/auth/v1/token" ]; then
        # set POST content
        curl_args+=(-d "$(getcreds)&grant_type=password&scope=offline_access")
    fi

    # send params, if available (after ? in GET)
    [ -n "$params" ] && curl_args+=(-Gd "$params")

    # url to access
    curl_args+=("$api_base$endpoint")

    # call curl, with parsing if there are further args
    if [ "$#" -gt 0 ]; then
        curl "${curl_args[@]}" | jq "$@"
    else
        curl "${curl_args[@]}"
    fi
}

api_login() {
    # (re)initialize session information
    authorization="$initial_authorization"
    unset params api_dir
    [ -e "$cookie_file" ] && rm "$cookie_file"

    # present credentials, get authentication token
    # this token expires quickly (5 minutes), but it should be fine for this script
    authorization="$(api_call "/auth/v1/token" -r '"Authorization: \(.token_type) \(.access_token)"')"

    # get universal url parameters
    local resp="$(api_call "/index/v2")"
    api_dir="/cms/v2$(parse "$resp" -r '.cms.bucket')"
    params="$(parse "$resp" -r '.cms | "Policy=\(.policy)&Signature=\(.signature)&Key-Pair-Id=\(.key_pair_id)"')"
}

# parse argument for episode id (badly)
episode_id="${1#https://beta.crunchyroll.com/watch/}"
episode_id="${episode_id%%/**}"
[ -z "$episode_id" ] && exit 1

# login
api_login

# get stream description
streams="$(api_call "$(api_call "episodes/$episode_id" -r '."__links__".streams.href')")"

# parse stream description for appropriate urls
vidurl="$(parse "$streams" -r '.streams.adaptive_hls."".url')"
suburl="$(parse "$streams" -r '.subtitles."en-US".url')"
subext="$(parse "$streams" -r '.subtitles."en-US".format')"

# download subtitles
curl "$suburl" -o "video.$subext"

# download video stream
yt-dlp "$vidurl" -o video.mp4

# marge subtitles with video
mkvmerge -o video.mkv "video.$subext" video.mp4

# cleanup
rm "$cookie_file" "video.$subext" video.mp4
```

**Comment by tejing1** [comment]
Well, no one took up the baton, so I went ahead and did it. Writing in a new language was interesting :smile:.
