### ISSUE TITLE
Unable to use yt-dlp past version 2021.10.22

### ISSUE THREAD

**Issue by RandomNewUser** [yt-dlp/yt-dlp#1932]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi, 

I'm using the Windows standalone x64 binary and the ffmpeg latest autobuild. I had no issues with using yt-dlp up to version 2021.10.22, but all releases after it return an error message. I'm unable to put a proper verbose log since I can't even execute yt-dlp, but here is what I get.
I've checked "I've verified that I'm running yt-dlp version 2021.12.01." because I can't report my issue if I don't.

Thanks for your time :)

### Verbose log

```shell
Output with version 2021.12.01:

C:\Users\RandomNewUser>yt-dlp https://www.youtube.com/watch?v=ZqZ20kqRVDI
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 823, in main
  File "yt_dlp\__init__.py", line 784, in _real_main
  File "yt_dlp\YoutubeDL.py", line 536, in __init__
  File "yt_dlp\compat.py", line 168, in windows_enable_vt_mode
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
[10712] Failed to execute script '__main__' due to unhandled exception!

Normal output with version 2021.10.22:

C:\Users\RandomNewUser>yt-dlp https://www.youtube.com/watch?v=ZqZ20kqRVDI
[youtube] ZqZ20kqRVDI: Downloading webpage
[youtube] ZqZ20kqRVDI: Downloading android player API JSON
[info] ZqZ20kqRVDI: Downloading 1 format(s): 248+251
[download] Destination: Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f248.webm
[download] 100% of 10.30MiB in 00:01
[download] Destination: Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f251.webm
[download] 100% of 1.24MiB in 00:00
[Merger] Merging formats into "Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].webm"
Deleting original file Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f248.webm (pass -k to keep)
Deleting original file Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f251.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
Can u show the verbose of the older version so that I can see your windows version and other details

**Comment by RandomNewUser** [comment]
Here it is. It says Windows-10-10.0.19041-SP0 but my config panel displays .19043.1348

```shell
C:\Users\RandomNewUser>yt-dlp -v https://www.youtube.com/watch?v=ZqZ20kqRVDI
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=ZqZ20kqRVDI']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-104783-gb5ba74053c-20211206, ffprobe N-104783-gb5ba74053c-20211206
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=ZqZ20kqRVDI
[youtube] ZqZ20kqRVDI: Downloading webpage
[youtube] ZqZ20kqRVDI: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ZqZ20kqRVDI: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://r3---sn-hgn7yn7l.googlevideo.com/videoplayback?expire=1638992557&ei=TbawYZmVOOuFvdIP8LiM0AI&ip=86.221.216.10&id=o-ALmwmyHlpIUcYT1qTK7x_r0uaHQ6JjvS8seTvB-pyMbk&itag=248&source=youtube&requiressl=yes&mh=8H&mm=31%2C29&mn=sn-hgn7yn7l%2Csn-hgn7rn7r&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1118750&vprv=1&mime=video%2Fwebm&gir=yes&clen=10799135&dur=84.080&lmt=1638780921283714&mt=1638970636&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6316224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAK_QzVExvx5C-eO_hHQF8RcliXKTKPcQ1ymh_ocku_rVAiA6Nxpimj7ZcOt6ktidzCmiKSdUXGkpUdk2OQDxUcAu3A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOiMlIEgQI91TxloGeU5bdXrb12L4I-1xENjAoSiveGCAiEAtdrtJ5G2CL-neRgyA1veURX0dpTFjn-GJiLz-XJd_GY%3D"
[download] Destination: Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f248.webm
[download] 100% of 10.30MiB in 00:01
[debug] Invoking downloader on "https://r3---sn-hgn7yn7l.googlevideo.com/videoplayback?expire=1638992557&ei=TbawYZmVOOuFvdIP8LiM0AI&ip=86.221.216.10&id=o-ALmwmyHlpIUcYT1qTK7x_r0uaHQ6JjvS8seTvB-pyMbk&itag=251&source=youtube&requiressl=yes&mh=8H&mm=31%2C29&mn=sn-hgn7yn7l%2Csn-hgn7rn7r&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1118750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=1298940&dur=84.121&lmt=1638780894532386&mt=1638970636&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMtDpK6CIFeczVBwpbks3zHjA2BYDBq0dV2CNTGmtobJAiBjyKsEz2Hfo9xjbX7ahMFh-92fWSJWVYwRWYNLmiaxpg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOiMlIEgQI91TxloGeU5bdXrb12L4I-1xENjAoSiveGCAiEAtdrtJ5G2CL-neRgyA1veURX0dpTFjn-GJiLz-XJd_GY%3D"
[download] Destination: Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f251.webm
[download] 100% of 1.24MiB in 00:00
[Merger] Merging formats into "Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f248.webm" -i "file:Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].temp.webm"
Deleting original file Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f248.webm (pass -k to keep)
Deleting original file Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f251.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
My windows version is the same (except it displays correctly in log as well). I'm not sure what is happening here, but I'll be able to make that error non-fatal. The only issue will be that colors wont display

**Comment by pukkandan** [comment]
Try this and let me know if it solves the issue https://github.com/pukkandan/yt-dlp-dev/releases/tag/2021.12.08.141622

**Comment by RandomNewUser** [comment]
It works perfectly, thanks a lot! :)

**Comment by pukkandan** [comment]
can u show verbose log from it? I want to check something

**Comment by RandomNewUser** [comment]
Here you go:

```shell
C:\Users\RandomNewUser>yt-dlp -v https://www.youtube.com/watch?v=ZqZ20kqRVDI
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=ZqZ20kqRVDI']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No VT), err utf-8 (No VT), pref cp1252
[debug] yt-dlp version 2021.12.08.141622 [47b7e38] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-104783-gb5ba74053c-20211206 (setts), ffprobe N-104783-gb5ba74053c-20211206
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=ZqZ20kqRVDI
[youtube] ZqZ20kqRVDI: Downloading webpage
[youtube] ZqZ20kqRVDI: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ZqZ20kqRVDI: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://r3---sn-hgn7rn7r.googlevideo.com/videoplayback?expire=1638995201&ei=ocCwYdPmMZCw0wWXvIeQDQ&ip=86.221.216.10&id=o-ADB38taIlj0pelOvV7OSywdyVNDuRxW_JNJb-XH0YaTV&itag=248&source=youtube&requiressl=yes&mh=8H&mm=31%2C29&mn=sn-hgn7rn7r%2Csn-hgn7yn7l&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1162500&vprv=1&mime=video%2Fwebm&gir=yes&clen=10799135&dur=84.080&lmt=1638780921283714&mt=1638973270&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6316224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALBagLahwBBiILZByTQn9nAfJCO0O6SM08P5ULcVsB6RAiADxTA9p5VTvVvSmCgMR7o8orG6UyJFu1c_Ovs-rCRAYg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMIhVEq4hqJNAKga1PpAWHhqF3hZIFvadjfoaf88w82GAiEAi53II50qEmJqOe0Zz7NwsgmYU88gzwgKP386CFeqbzA%3D"
[download] Destination: Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f248.webm
[download] 100% of 10.30MiB in 00:01
[debug] Invoking downloader on "https://r3---sn-hgn7rn7r.googlevideo.com/videoplayback?expire=1638995201&ei=ocCwYdPmMZCw0wWXvIeQDQ&ip=86.221.216.10&id=o-ADB38taIlj0pelOvV7OSywdyVNDuRxW_JNJb-XH0YaTV&itag=251&source=youtube&requiressl=yes&mh=8H&mm=31%2C29&mn=sn-hgn7rn7r%2Csn-hgn7yn7l&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1162500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=1298940&dur=84.121&lmt=1638780894532386&mt=1638973270&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgeaDQYi0Cy7JuFZd5Rb9NRI11YOEJqmpxZvGvcE0WDSkCIQDUO9qqmZjPBK0MnRP51WmpL4RyG5T0svVoIeWSP3AlgA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMIhVEq4hqJNAKga1PpAWHhqF3hZIFvadjfoaf88w82GAiEAi53II50qEmJqOe0Zz7NwsgmYU88gzwgKP386CFeqbzA%3D"
[download] Destination: Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f251.webm
[download] 100% of 1.24MiB in 00:00
[Merger] Merging formats into "Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f248.webm" -i "file:Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].temp.webm"
Deleting original file Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f248.webm (pass -k to keep)
Deleting original file Official Trailer - Thief Heroine _ 盗圣一枝梅 _ iQiyi [ZqZ20kqRVDI].f251.webm (pass -k to keep)
```
