### ISSUE TITLE
NHL Video - fails back to Generic - ERROR: Unsupported URL

### ISSUE THREAD

**Issue by RingoTheDog** [yt-dlp/yt-dlp#1933]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

URL: https://www.nhl.com/blackhawks/video/t-277437096 

NOTE: For NHL video I often need to use --no-check-certificate to avoid [SSL: CERTIFICATE_VERIFY_FAILED]
...however in this case it never gets that far.

### Verbose log

```shell
>yt-dlp.py -v "https://www.nhl.com/blackhawks/video/t-277437096"
[debug] Command-line config: ['-v', 'https://www.nhl.com/blackhawks/video/t-277437096']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.6.6 (CPython 64bit) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.nhl.com/blackhawks/video/t-277437096
[generic] t-277437096: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] t-277437096: Downloading webpage
[generic] t-277437096: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.nhl.com/blackhawks/video/t-277437096
Traceback (most recent call last):
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\generic.py", line 3813, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nhl.com/blackhawks/video/t-277437096
```

**Comment by pukkandan** [comment]
Only the full URL like https://www.nhl.com/blackhawks/video/king-on-kurashev-seth-jones/t-277437096/c-9835166 is currently supported
