### ISSUE TITLE
【Ceskatelevize.CZ】Is it possible to download a ČT video which from within the Android app?

### ISSUE THREAD

**Issue by NiesmialyGosc** [yt-dlp/yt-dlp#1952]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Example URLs

https://www.ceskatelevize.cz/porady/10111864738-hercule-poirot/211381467540023/

### Description

Is it possible to download a video directly from the ČeskáTelevize (ČT) app instead of from its website?

This video "[Hercule Poirot - Plymouthský expres](https://www.ceskatelevize.cz/porady/10111864738-hercule-poirot/211381467540023/)" is marked as unavailable/unplayable for license reasons on the ČT website, however, it is still playable in the CeskaTelevize app (see screenshot: https://app.box.com/file/894306132462?s=xucnudi0hk5cz3nkdlpbp5b9vqwf4tn0) with my VPN turned on.

Even though I've applied [mkubecek's patch in the thread #1899](https://github.com/yt-dlp/yt-dlp/issues/1899#issuecomment-987030947), I can't download  even if it's perfectly playable 

~/video/TEST1/yt-dlp-master $ yt-dlp -Uv --write-subs --convert-subs srt --retries 20000 https://www.ceskatelevize.cz/porady/10111864738-hercule-poirot/211381467540023/
[debug] Command-line config: ['-Uv', '--write-subs', '--convert-subs', 'srt', '--retries', '20000', 'https://www.ceskatelevize.cz/porady/10111864738-hercule-poirot/211381467540023/']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2021.12.01 [91f071af6] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.9 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg N-89508-g1f1207145a, ffprobe N-89508-g1f1207145a
[debug] Optional libraries: sqlite
[debug] Proxy map: {'http': 'http://192.168.1.4:8080', 'https': 'https://192.168.1.4:8080', 'ftp': 'ftp://192.168.1.4:8080'}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [CeskaTelevize] Extracting URL: https://www.ceskatelevize.cz/porady/10111864738-hercule-poirot/211381467540023/
[CeskaTelevize] 211381467540023: Downloading webpage
[CeskaTelevize] 211381467540023: Downloading webpage
[CeskaTelevize] 211381467540023: Downloading webpage
ERROR: [CeskaTelevize] 211381467540023: Unable to extract type; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\extractor\common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\extractor\ceskatelevize.py", line 126, in _real_extract
    type_ = self._html_search_regex(
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\extractor\common.py", line 1182, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\extractor\common.py", line 1173, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract type; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\extractor\common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\extractor\ceskatelevize.py", line 126, in _real_extract
    type_ = self._html_search_regex(
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\extractor\common.py", line 1182, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\extractor\common.py", line 1173, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract type; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\YoutubeDL.py", line 1331, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\YoutubeDL.py", line 1400, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\DELL\video\TEST1\yt-dlp-master\yt_dlp\extractor\common.py", line 625, in extract
    raise type(e)(e.msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [CeskaTelevize] 211381467540023: Unable to extract type; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

~/video/TEST1/yt-dlp-master $

**Comment by Ashish0804** [comment]
If your phone is rooted, then install burp certificate and log the api requests.
It's normal for sites to have a diff api for the mobile version.

If the app has SSL pinning then u can decompile the apk, and then look for api endpoints.

I don't have a Chinese VPN so I can't try myself

**Comment by nao20010128nao** [comment]
Isn't it Czech VPN?

**Comment by Ashish0804** [comment]
> Region
> China

**Comment by NiesmialyGosc** [comment]
> 

Thanks Ashish0804, but Im

**Comment by NiesmialyGosc** [comment]
> > 
> 
Thanks Ashish0804, but I'm using a Czech VPN even though I'm located in China. Is it possible for me to download the video without rooting? Many thanks

**Comment by NiesmialyGosc** [comment]
> If your phone is rooted, then install burp certificate and log the api requests. It's normal for sites to have a diff api for the mobile version.
> 
> If the app has SSL pinning then u can decompile the apk, and then look for api endpoints.
> 
> I don't have a Chinese VPN so I can't try myself

Thanks @Ashish0804, but I'm using a Czech VPN even though I'm located in China. Is it possible for me to download the video without rooting? Many thanks

**Comment by Ashish0804** [comment]
If it's cz then I can work on this when I get some free time. 

This is the app, right?
https://play.google.com/store/apps/details?id=cz.motion.ivysilani

**Comment by NiesmialyGosc** [comment]
> If it's cz then I can work on this when I get some free time.
> 
> This is the app, right? https://play.google.com/store/apps/details?id=cz.motion.ivysilani

CORRECT

**Comment by Ashish0804** [comment]
>Is it possible for us to get a fix ASAP..?
Nope
Proly in late jan or early feb

**Comment by NiesmialyGosc** [comment]
> > Is it possible for us to get a fix ASAP..?
> 
> Nope Proly in late jan or early feb

OK noted, thanks @Ashish0804 !

One more question though..
