### ISSUE TITLE
Apple podcasts broken

### ISSUE THREAD

**Issue by sefabey** [yt-dlp/yt-dlp#1989]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Description

Apple podcasts seems to be not working either for individual episodes or as at podcast (channel) level. Attached is the verbose log for an individual episode but `yt-dlp` does not work for the podcast at channel level on https://podcasts.apple.com/us/podcast/up-first/id1222114325. 

### Verbose log

```shell
[debug] Command-line config: ['--verbose', 'https://podcasts.apple.com/us/podcast/monday-december-13-2021/id1222114325?i=1000544795004']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.11.0-38-generic-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [ApplePodcasts] Extracting URL: https://podcasts.apple.com/us/podcast/monday-december-13-2021/id1222114325?i=1000544795004
[ApplePodcasts] 1000544795004: Downloading webpage
ERROR: [ApplePodcasts] 1000544795004: Unable to extract ember data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/applepodcasts.py", line 42, in _real_extract
    ember_data = self._parse_json(self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1171, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract ember data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/applepodcasts.py", line 42, in _real_extract
    ember_data = self._parse_json(self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1171, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract ember data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 623, in extract
    raise type(e)(e.msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [ApplePodcasts] 1000544795004: Unable to extract ember data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output
```

**Comment by duivesteyn** [comment]
Any idea when this will be fixed?
Looks like the Fix has been sitting in youtube-dl for weeks. waiting for the pull request.

https://github.com/ytdl-org/youtube-dl/pull/30340

**Comment by sefabey** [comment]
Seems to be merged now: https://github.com/ytdl-org/youtube-dl/commit/584715a803eef68f68fbbb8b72a022a699983197

**Comment by pukkandan** [comment]
I'll port it before next release

**Comment by pukkandan** [comment]
50e93e03a7ca6ae35a319ea310104f7d6d91eee3

**Comment by bashonly** [comment]
@fidodido48 open a new issue please
