### ISSUE TITLE
ffmpeg cannot find file that is there

### ISSUE THREAD

**Issue by antsareflying** [yt-dlp/yt-dlp#1995]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

ffmpeg cannot turn webm files into mkv because it cant find the files but they're there. this is for some videos only, noticed with youtube videos: https://www.youtube.com/watch?v=e50Bj7jn9IQ , https://www.youtube.com/watch?v=mH0oCDa74tE

ls output:
```
PS C:\Users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ> ls


    Directory: C:\Users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick
    trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        14/12/2021  02:26 PM           1748 20210507-A quick trick for computing eigenvalues _ Chapter 15,
                                                  Essence of linear algebra-e50Bj7jn9IQ.description
-a----        14/12/2021  01:40 PM          17245 20210507-A quick trick for computing eigenvalues _ Chapter 15,
                                                  Essence of linear algebra-e50Bj7jn9IQ.en.vtt
-a----        10/05/2021  08:04 AM       11804798 20210507-A quick trick for computing eigenvalues _ Chapter 15,
                                                  Essence of linear algebra-e50Bj7jn9IQ.f251.webm
-a----        10/05/2021  12:28 PM      333986573 20210507-A quick trick for computing eigenvalues _ Chapter 15,
                                                  Essence of linear algebra-e50Bj7jn9IQ.f315.webm
-a----        14/12/2021  02:26 PM        1274391 20210507-A quick trick for computing eigenvalues _ Chapter 15,
                                                  Essence of linear algebra-e50Bj7jn9IQ.info.json
-a----        14/12/2021  02:26 PM          26398 20210507-A quick trick for computing eigenvalues _ Chapter 15,
                                                  Essence of linear algebra-e50Bj7jn9IQ.webp

```

### Verbose log

```shell
[debug] Command-line config: ['--write-description', '--write-info-json', '--write-annotations', '--write-sub', '--sub-langs', 'en', '--write-thumbnail', '--write-comments', '--no-playlist', '--verbose', '--download-archive', 'C:/users/seong/archive/public/videos/downloadedarchive.txt', '-a', 'C:/users/seong/archive/public/videos/downloadlinks.txt', '-f', 'bv*+ba/b', '--merge-output-format', 'mkv', '-o', 'C:/users/seong/archive/public/videos/NA-%(playlist_title)s-%(playlist_id)s/%(upload_date)s-%(title)s-%(id)s/%(upload_date)s-%(title)s-%(id)s.%(ext)s']
[debug] Batch file urls: ['https://www.youtube.com/c/3blue1brown', 'https://www.youtube.com/c/AcousticTrench', 'https://www.youtube.com/c/ActiveAtom', 'https://www.youtube.com/channel/UC1ui-Uaj8XTilJhhIKBP8FQ', 'https://www.youtube.com/c/AppliedScience', 'https://www.youtube.com/c/Clickspring', 'https://www.youtube.com/c/ClickspringClips', 'https://www.youtube.com/c/doddleoddle', 'https://www.youtube.com/c/JPPalmer', 'https://www.youtube.com/c/inanutshell', 'https://www.youtube.com/c/machinethinking', 'https://www.youtube.com/c/NewMind', 'https://www.youtube.com/c/PomplamooseMusic', 'https://www.youtube.com/c/ReubenSchoots', 'https://www.youtube.com/c/ROBRENZ', 'https://www.youtube.com/user/rwsmithwatches', 'https://www.youtube.com/c/SamZeloof', 'https://www.youtube.com/c/ScaryPockets', 'https://www.youtube.com/c/StefanGotteswinter', 'https://www.youtube.com/c/tarkka', 'https://www.youtube.com/c/TerraMaterOfficial', 'https://www.youtube.com/c/TheEfficientEngineer', 'https://www.youtube.com/c/ThisOldTony', 'https://www.youtube.com/user/Computerphile', 'https://www.youtube.com/user/dgelbart', 'https://www.youtube.com/c/TechnologyConnections', 'https://www.youtube.com/playlist?list=PLWHSXBcUHlGTpecAvW--wwP_QFTcGLK48', 'https://www.youtube.com/c/InTheMetal']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-12-12-git-996b13fac4-full_build-www.gyan.dev (setts), ffprobe 2021-12-12-git-996b13fac4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'C:/users/seong/archive/public/videos/downloadedarchive.txt'
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/c/3blue1brown
WARNING: [youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[youtube:tab] 3blue1brown: Downloading webpage

.
.
.
.

[youtube] Extracted 1172 comments
[info] Writing video description to: C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.description
[info] Writing video subtitles to: C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=e50Bj7jn9IQ&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1639488349&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=1616793DC7BE9912EC3C067D455F146DA4ECB99F.E7D619407F485828DBD67668BE11624C70FDBEA5&key=yt8&lang=en&fmt=vtt"
[download] C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.en.vtt has already been downloaded
[download] 100% of 16.84KiB[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.webp
[info] Writing video metadata as JSON to: C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.info.json
WARNING: There are no annotations to write.
[debug] Invoking downloader on "https://rr1---sn-nu5gi0c-npoe7.googlevideo.com/videoplayback?expire=1639484750&ei=7ji4YeCHL8LQogP084GoBw&ip=58.182.173.19&id=o-AAm0PDePiV54C3kpK1no9A0PR3wTROM8dzI2UtVkw0gS&itag=315&source=youtube&requiressl=yes&mh=9P&mm=31%2C29&mn=sn-nu5gi0c-npoe7%2Csn-npoe7n7z&ms=au%2Crdu&mv=m&mvi=1&pl=19&initcwndbps=1976250&vprv=1&mime=video%2Fwebm&gir=yes&clen=333986573&dur=791.966&lmt=1620620911671164&mt=1639462848&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgL0hHat9ozcodMjtXaGGOXXrB51OjF4zyY-TMzyC-pIYCIQCfMeNvIuvXI8qxr25e7wnfkqB_Zz-lGNTR05QymjgmTQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAN9bWgkmKp1DDXkxA9g0Uq2HBcLwvx9yff4s0_hK-mc1AiAmKEA-s8Bkck2JC3K-RymoflfWD023uWEGuTqnMS2amg%3D%3D"
[download] C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.f315.webm has already been downloaded
[download] 100% of 318.51MiB[debug] Invoking downloader on "https://rr1---sn-nu5gi0c-npoe7.googlevideo.com/videoplayback?expire=1639484750&ei=7ji4YeCHL8LQogP084GoBw&ip=58.182.173.19&id=o-AAm0PDePiV54C3kpK1no9A0PR3wTROM8dzI2UtVkw0gS&itag=251&source=youtube&requiressl=yes&mh=9P&mm=31%2C29&mn=sn-nu5gi0c-npoe7%2Csn-npoe7n7z&ms=au%2Crdu&mv=m&mvi=1&pl=19&initcwndbps=1976250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=11804798&dur=792.001&lmt=1620605065860729&mt=1639462848&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIYSZ-k-XpNJfV4ugh25tXEVc5IJY_nbdNDvmy-o5lBnAiAxwZzWriDpXVKQ6DfGq8gLSjLznuk8mK_COPFPUu--dQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAN9bWgkmKp1DDXkxA9g0Uq2HBcLwvx9yff4s0_hK-mc1AiAmKEA-s8Bkck2JC3K-RymoflfWD023uWEGuTqnMS2amg%3D%3D"
[download] C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.f251.webm has already been downloaded
[download] 100% of 11.26MiB[Merger] Merging formats into "C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.f315.webm" -i "file:C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.temp.mkv"
[debug] ffmpeg version 2021-12-12-git-996b13fac4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.2.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 11.100 / 57. 11.100
  libavcodec     59. 14.100 / 59. 14.100
  libavformat    59. 10.100 / 59. 10.100
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8. 20.100 /  8. 20.100
  libswscale      6.  1.101 /  6.  1.101
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
file:C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.f315.webm: No such file or directory
ERROR: Postprocessing: file:C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.f315.webm: No such file or directory
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3001, in process_info
  File "yt_dlp\YoutubeDL.py", line 3165, in post_process
  File "yt_dlp\YoutubeDL.py", line 3108, in run_pp
  File "yt_dlp\postprocessor\common.py", line 23, in run
  File "yt_dlp\postprocessor\common.py", line 118, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 815, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 280, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 317, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:C:\users\seong\archive\public\videos\NA-3Blue1Brown - Videos-UCYO_jab_esuFRV4b17AJtAw\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ\20210507-A quick trick for computing eigenvalues _ Chapter 15, Essence of linear algebra-e50Bj7jn9IQ.f315.webm: No such file or directory

[download] Downloading video 6 of 118
[download] How (and why) to raise e to the power of a matrix | DE6 has already been recorded in the archive
[download] Downloading video 7 of 118
[download] The medical test paradox, and redesigning Bayes' rule has already been recorded in the archive
```

**Comment by antsareflying** [comment]
i just tried it individually, it works properly.

**Comment by pukkandan** [comment]
The filepath is too long. Use a smaller output template

**Comment by antsareflying** [comment]
seems like that was the problem. do you know what the length limit is so i don't hit it again?

**Comment by pukkandan** [comment]
255 bytes in windows. Windows 10 has a way to bypass this. While yt-dlp uses that bypass, ffmpeg does not, causing this issue

There is also another limit of 255bytes for each path segment that applies for most OSes (including windows)
