### ISSUE TITLE
Request Support for VIU Indonesia

### ISSUE THREAD

**Issue by namia1** [yt-dlp/yt-dlp#1996]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Indonesia

### Example URLs

- Single video: https://www.viu.com/ott/id/en/all/video-korean-drama-tv_shows-lovers_of_the_red_sky_episode_1-1165922078?containerId=playlist-26271545
- Single video: https://www.viu.com/ott/id/en/all/video-korean-drama-tv_shows-lovers_of_the_red_sky_episode_2-1165921609?containerId=playlist-26271545
- Playlist: https://www.viu.com/ott/id/en/all/playlist-lovers_of_the_red_sky-playlist-26271545

### Description

yt-dlp (tested 2021.12.01 and some previous version) would treat VIU Indonesia links as generic.
After using VPN i see that Indonesian VIU account is not usable in other country, i assume VIU is restricted per country. Also, each country website is a bit different from each other.
Would it be possible to also support VIU Indonesia? Hopefully it would be easy, since VIU from other country is already supported. I can provide premium account if needed (VIU Indonesia also got ad supported free tier). Thanks.

### Verbose log

```shell
[debug] Command-line config: ['https://www.viu.com/ott/id/id/all/playlist-my_lawyer_mr_joe-playlist-22129246', '--cookies-from-browser', 'chrome', '--list-formats', '-Uv']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "f:\Users\Arifin Chundana\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[Cookies] Extracted 3825 cookies from chrome
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-03-28-git-8b2bde0494-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://www.viu.com/ott/id/id/all/playlist-my_lawyer_mr_joe-playlist-22129246
[generic] playlist-my_lawyer_mr_joe-playlist-22129246: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] playlist-my_lawyer_mr_joe-playlist-22129246: Downloading webpage
[generic] playlist-my_lawyer_mr_joe-playlist-22129246: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.viu.com/ott/id/id/all/playlist-my_lawyer_mr_joe-playlist-22129246
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\generic.py", line 3813, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.viu.com/ott/id/id/all/playlist-my_lawyer_mr_joe-playlist-22129246
```

**Comment by pukkandan** [comment]
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1757
