### ISSUE TITLE
Support for mega.nz?

### ISSUE THREAD

**Issue by mesb1** [yt-dlp/yt-dlp#2004]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Russia

### Example URLs

- Single: https://mega.nz/folder/jjJRGCwS#TawrhF6DslhH5oOb7kLecw/file/bnwmwZ7K
- Single: https://mega.nz/file/uv5UEaqK#PPE-izTodDP0vqYwMgzkJ1vjUnLLjsJ-pqe_jJ8Rr7c
- Folder: https://mega.nz/folder/jjJRGCwS#TawrhF6DslhH5oOb7kLecw

### Description

Hi.
It would be nice to add mega.nz support.
For now it looks like only jdownloaderis doing it.

### Verbose log

```shell
C:\tmp>yt-dlp.exe --verbose https://mega.nz/folder/jjJRGCwS#TawrhF6DslhH5oOb7kLecw/file/bnwmwZ7K
[debug] Command-line config: ['--verbose', 'https://mega.nz/folder/jjJRGCwS#TawrhF6DslhH5oOb7kLecw/file/bnwmwZ7K']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://mega.nz/folder/jjJRGCwS#TawrhF6DslhH5oOb7kLecw/file/bnwmwZ7K
[generic] bnwmwZ7K: Requesting header
WARNING: [generic] Could not send HEAD request to https://mega.nz/folder/jjJRGCwS#TawrhF6DslhH5oOb7kLecw/file/bnwmwZ7K: The read operation timed out
[generic] bnwmwZ7K: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] bnwmwZ7K: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://mega.nz/folder/jjJRGCwS#TawrhF6DslhH5oOb7kLecw/file/bnwmwZ7K
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\generic.py", line 3813, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://mega.nz/folder/jjJRGCwS#TawrhF6DslhH5oOb7kLecw/file/bnwmwZ7K
```

**Comment by fstirlitz** [comment]
Try <https://github.com/megous/megatools>.

**Comment by nao20010128nao** [comment]
Why don't use `megatools`?

**Comment by shirt-dev** [comment]
Mega.nz is a file hosting site, I don't believe that mega encodes videos for web streaming, so I really don't see a reason for this to be added.

**Comment by nyuszika7h** [comment]
They do have a web player for MP4 videos at least, but I don't think they reencode them.

**Comment by pukkandan** [comment]
There is no fundamental reason not to support this, except that it will be a massive pain to add due to needing an custom downloader

**Comment by afterdelight** [comment]
does megatools have an archive support so i can only download new files added to the mega folder?? its a pain to verify each file every new download with mega sync.

**Comment by nyuszika7h** [comment]
You can use rclone with the `--ignore-existing` option.

**Comment by afterdelight** [comment]
whats rclone ?

**Comment by nyuszika7h** [comment]
yt-dlp's issue tracker is not your personal Google. Since you already mentioned another tool (megatools), I assumed you'd be smart enough to just look up what rclone is.

**Comment by afterdelight** [comment]
i dont know what are you talking about. megatools page is too confusing too read

**Comment by pukkandan** [comment]
Unless your question is related to yt-dlp, post it elsewhere

**Comment by afterdelight** [comment]
i only asked about rclone. i thought it was part of yt-dlp

**Comment by Lesmiscore** [comment]
No and it's an unrelated project

**Comment by pukkandan** [comment]
> i only asked about rclone. i thought it was part of yt-dlp

Everything from https://github.com/yt-dlp/yt-dlp/issues/2004#issuecomment-1114229653 is offtopic

**Comment by HobbyistDev** [comment]
Related upstream: https://github.com/ytdl-org/youtube-dl/issues/30907

**Comment by DTrombett** [comment]
Bumping this after 2 years... is there are a reason this was discarded?

**Comment by bt4ibwem8** [comment]
Would be possible to borrow the code from Megatools and implement it?

**Comment by DTrombett** [comment]
May I ask why?

**Comment by bashonly** [comment]
mega.nz has been classified as a "notorious market" by some governments and as such it is too risky to add support for
