### ISSUE TITLE
6play not working

### ISSUE THREAD

**Issue by davacker** [yt-dlp/yt-dlp#2005]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description

I try to download an M6 (french TV channel) replay but it doesn't seem to work. I also tried with `--cookie-from-browser`.
I let you check the logs.

I think you need an account to view this kind of content. I created this one :
User : kejiwoh698@swsguide.com
Passwd : `xZ(L5SJlV-Et?xY`

Thank you in advance

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--cookies-from-browser', 'firefox', 'https://www.6play.fr/66-minutes-p_825/cadeaux-louez-vos-jouets-chauffeur-si-tes-champion-noel-coup-de-chaud-chez-le-roi-du-froid-c_12912864']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/Users/ackermannd/Library/Application Support/Firefox/Profiles/low04f7u.default-release/cookies.sqlite"
[Cookies] Extracted 1352 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.10.1 (CPython 64bit) - macOS-12.0.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [6play] Extracting URL: https://www.6play.fr/66-minutes-p_825/cadeaux-louez-vos-jouets-chauffeur-si-tes-champion-noel-coup-de-chaud-chez-le-roi-du-froid-c_12912864
[6play] 12912864: Downloading JSON metadata
ERROR: [6play] 12912864: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1412, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1462, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2346, in process_video_result
    self.raise_no_formats(info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 933, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [6play] 12912864: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by sourcehutman** [comment]
It seems to be protected by fairplay DRM (hlsfp) or dashcenc DRM

There is a kodi plugin that supports 6play but I haven't looked at the code too much:
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/e4a15971152cc23e1902aa535ed36023417aca34/resources/lib/channels/fr/6play.py

It might be possible to port this to yt-dlp

**Comment by Zulgrib** [comment]
Hello, any update on this ?

**Comment by kapouer** [comment]
IMO it's more something like Widevine DRM.

**Comment by SailingDad** [comment]
Hello.
I have the same issue.
Here is the verbose log.
Best regards

`[debug] Command-line config: ['-v', 'https://www.6play.fr/le-1245-p_1056/le-1245-du-20-09-2022-c_12966333']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.10.6 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] [6play] Extracting URL: https://www.6play.fr/le-1245-p_1056/le-1245-du-20-09-2022-c_12966333
[6play] 12966333: Downloading JSON metadata
ERROR: [6play] 12966333: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1556, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1614, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2546, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1025, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [6play] 12966333: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
`

**Comment by gamer191** [comment]
originally posted in #5237 by @dirkf:

> Apparently the extractor only gets DRM formats for this show from the API URL that it uses. Also, it only gets one of them because it doesn't look for the DASH/mpd case.
> ```
>
>...
>                          'type': 'usp_dashcenc_h264',
>...
>                          'type': 'usp_hlsfp_h264',
>
>```
>The yt-dlp 6Play extractor is essentially identical to the yt-dl version and doesn't understand any special processing for DRM formats.

**Comment by dirkf** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/24967
