### ISSUE TITLE
ABC "video may no longer be valid or has expired" but plays in browser

### ISSUE THREAD

**Issue by TheGrimKeeper** [yt-dlp/yt-dlp#2022]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

All episodes of this show are open with no login needed.  The other episodes I've tried of this show work fine (so far) but this one returns an error, even though it is playable in the browser.

### Verbose log

```shell
[debug] Command-line config: ['-v', 'https://abc.com/shows/the-secret-life-of-the-american-teenager/episode-guide/season-01/04-caught']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg n4.4-78-g031c0cb0b4-20210714 (setts), ffprobe n4.4-78-g031c0cb0b4-20210714
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Go] Extracting URL: https://abc.com/shows/the-secret-life-of-the-american-teenager/episode-guide/season-01/04-caught
[Go] 04-caught: Downloading webpage
[Go] VDKA51502: Downloading JSON metadata
[debug] Using fake IP 6.39.80.131 (US) as X-Forwarded-For
[Go] VDKA51502: Downloading JSON metadata
ERROR: [Go] Go said: 1022:This video may no longer be valid or has expired. Please try fully quitting the app and then try again.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\go.py", line 257, in _real_extract
yt_dlp.utils.ExtractorError: Go said: 1022:This video may no longer be valid or has expired. Please try fully quitting the app and then try again.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\go.py", line 257, in _real_extract
yt_dlp.utils.ExtractorError: Go said: 1022:This video may no longer be valid or has expired. Please try fully quitting the app and then try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 623, in extract
yt_dlp.utils.ExtractorError: [Go] Go said: 1022:This video may no longer be valid or has expired. Please try fully quitting the app and then try again.
```

**Comment by TheGrimKeeper** [comment]
Started working as soon as I submitted this ticket.  Closing...
