### ISSUE TITLE
[SonyLiv]  An extractor error has occurred. (caused by KeyError('videoURL'));

### ISSUE THREAD

**Issue by kr-v** [yt-dlp/yt-dlp#2026]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Description

Trying to download this file on the latest version ( login supported extractor).
Getting Extractor error.

URL : 'https://www.sonyliv.com/shows/taarak-mehta-ka-ooltah-chashmah-1700000084/gungun-s-father-faints-1000150049?watch=true'

### Verbose log

```shell
[debug] Command-line config: ['https://www.sonyliv.com/shows/taarak-mehta-ka-ooltah-chashmah-1700000084/gungun-s-father-faints-1000150049?watch=true', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.7 (CPython 64bit) - macOS-12.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 117.237.35.89 (IN) as X-Forwarded-For
[SonyLIV] Downloading JSON metadata
[debug] [SonyLIV] Extracting URL: https://www.sonyliv.com/shows/taarak-mehta-ka-ooltah-chashmah-1700000084/gungun-s-father-faints-1000150049?watch=true
[SonyLIV] 1000150049: Downloading JSON metadata
ERROR: 1000150049: An extractor error has occurred. (caused by KeyError('videoURL')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 598, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/sonyliv.py", line 141, in _real_extract
    dash_url = content['videoURL']
KeyError: 'videoURL'
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 598, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/sonyliv.py", line 141, in _real_extract
    dash_url = content['videoURL']
KeyError: 'videoURL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1335, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1404, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 628, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e, video_id=self.get_temp_id(url))
yt_dlp.utils.ExtractorError: 1000150049: An extractor error has occurred. (caused by KeyError('videoURL')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
You are not passing login details to it
