### ISSUE TITLE
[Linux] Error when compiling

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#2060]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I wanted to test the new function `--live-from-start`, so i tried to compile from the current `master`.
Then this error was thrown:

### Verbose log

```shell
git clone https://github.com/yt-dlp/yt-dlp.git &&\
> cd yt-dlp &&\
> make
Cloning into 'yt-dlp'...
remote: Enumerating objects: 103087, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 103087 (delta 79), reused 78 (delta 43), pack-reused 102942
Receiving objects: 100% (103087/103087), 31.31 MiB | 9.09 MiB/s, done.
Resolving deltas: 100% (79895/79895), done.
/usr/bin/env python3 devscripts/make_lazy_extractors.py yt_dlp/extractor/lazy_extractors.py
mkdir -p zip
for d in yt_dlp yt_dlp/downloader yt_dlp/extractor yt_dlp/postprocessor ; do \
  mkdir -p zip/$d ;\
  cp -pPR $d/*.py zip/$d/ ;\
done
touch -t 200001010101 zip/yt_dlp/*.py zip/yt_dlp/*/*.py
mv zip/yt_dlp/__main__.py zip/
cd zip ; zip -q ../yt-dlp yt_dlp/*.py yt_dlp/*/*.py __main__.py
rm -rf zip
echo '#!/usr/bin/env python3' > yt-dlp
cat yt-dlp.zip >> yt-dlp
rm yt-dlp.zip
chmod a+x yt-dlp
COLUMNS=80 /usr/bin/env python3 yt_dlp/__main__.py --help | /usr/bin/env python3 devscripts/make_readme.py
/usr/bin/env python3 devscripts/make_contributing.py README.md CONTRIBUTING.md
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/1_broken_site.yml .github/ISSUE_TEMPLATE/1_broken_site.yml
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/2_site_support_request.yml .github/ISSUE_TEMPLATE/2_site_support_request.yml
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/3_site_feature_request.yml .github/ISSUE_TEMPLATE/3_site_feature_request.yml
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/4_bug_report.yml .github/ISSUE_TEMPLATE/4_bug_report.yml
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/5_feature_request.yml .github/ISSUE_TEMPLATE/5_feature_request.yml
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/6_question.yml .github/ISSUE_TEMPLATE/6_question.yml
/usr/bin/env python3 devscripts/make_supportedsites.py supportedsites.md
git shortlog -s -e -n | awk '!(out[$NF]++) { $1="";sub(/^[ \t]+/,""); print}' > .mailmap
git shortlog -s -n | cut -f2 | sort > AUTHORS
pandoc -f markdown -t plain README.md -o README.txt
mkdir -p completions/bash
/usr/bin/env python3 devscripts/bash-completion.py
mkdir -p completions/fish
/usr/bin/env python3 devscripts/fish-completion.py
mkdir -p completions/zsh
/usr/bin/env python3 devscripts/zsh-completion.py
/usr/bin/env python3 devscripts/prepare_manpage.py yt-dlp.1.temp.md
Traceback (most recent call last):
  File "devscripts/prepare_manpage.py", line 97, in <module>
    main()
  File "devscripts/prepare_manpage.py", line 39, in main
    readme = move_sections(readme)
  File "devscripts/prepare_manpage.py", line 56, in move_sections
    sections = re.findall(rf'(?m)^{re.escape(MOVE_TAG_TEMPLATE) % "(.+)"}$', readme)
  File "/usr/lib/python3.6/re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 869, in parse
    raise source.error("unbalanced parenthesis")
sre_constants.error: unbalanced parenthesis at position 38
Makefile:97: recipe for target 'yt-dlp.1' failed
make: *** [yt-dlp.1] Error 1
```

**Comment by nicolaasjan** [comment]
Thanks! 👍
