### ISSUE TITLE
Showroom live download fails s

### ISSUE THREAD

**Issue by dfgyuri** [yt-dlp/yt-dlp#2072]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Attempting to download certain streams from showroom results in an error saying the stream is offline despite it being online and accessible through the browser.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'showroom-live.com/tetorateto']
[debug] Encodings: locale cp932, fs utf-8, out utf-8, err utf-8, pref cp932
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-20-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: showroom-live.com/tetorateto
WARNING: [generic] The url doesn't specify the protocol, trying with http
[debug] [ShowRoomLive] Extracting URL: http://showroom-live.com/tetorateto
[ShowRoomLive] tetorateto: Downloading webpage
[ShowRoomLive] tetorateto: Downloading JSON metadata
ERROR: [ShowRoomLive] tetorateto: tetorateto is offline
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\showroomlive.py", line 35, in _real_extract
yt_dlp.utils.ExtractorError: tetorateto is offline
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\showroomlive.py", line 35, in _real_extract
yt_dlp.utils.ExtractorError: tetorateto is offline

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 623, in extract
yt_dlp.utils.ExtractorError: [ShowRoomLive] tetorateto: tetorateto is offline
```

**Comment by dfgyuri** [comment]
I've found that the rooms that have this issue end up downloading the wrong streams when they do work. for instance showroom-live.com/tetorateto ends up downloading the stream showroom-live.com/minaseyuki and would error out with "[ShowRoomLive] tetorateto: tetorateto is offline" if minaseyuki is offline regardless of the status ofthe input room. Logs attached of trying to download from the room but the 2nd room is online.

```shell
[debug] Command-line config: ['-Uv', 'showroom-live.com/tetorateto']
[debug] Encodings: locale cp932, fs utf-8, out utf-8, err utf-8, pref cp932
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-20-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: showroom-live.com/tetorateto
WARNING: [generic] The url doesn't specify the protocol, trying with http
[debug] [ShowRoomLive] Extracting URL: http://showroom-live.com/tetorateto
[ShowRoomLive] tetorateto: Downloading webpage
[ShowRoomLive] tetorateto: Downloading JSON metadata
[ShowRoomLive] tetorateto: Downloading JSON metadata
[ShowRoomLive] tetorateto: Downloading m3u8 information
[ShowRoomLive] tetorateto: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 14531622: Downloading 1 format(s): hls-1
[debug] Invoking downloader on "https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/chunklist.m3u8"
[download] Destination: 水無瀬ゆき 2021-12-22 21_15 [14531622].mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.73 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
" -i "https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/chunklist.m3u8" -c copy -f mpegts "file:水無瀬ゆき 2021-12-22 21_15 [14531622].mp4.part"
ffmpeg version 4.3.2-2021-02-20-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[tcp @ 000002cfea3b1900] Starting connection attempt to 18.65.229.92 port 443
[tcp @ 000002cfea3b1900] Successfully connected to 18.65.229.92 port 443
[hls @ 000002cfea3adcc0] Skip ('#EXT-X-VERSION:3')
[hls @ 000002cfea3adcc0] Skip ('#EXT-X-PROGRAM-DATE-TIME:2021-12-23T14:15:08.298+09:00')
[hls @ 000002cfea3adcc0] HLS request for url 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4052.ts', offset 0, playlist 0
[hls @ 000002cfea3adcc0] Opening 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4052.ts' for reading
[tcp @ 000002cfea5dc140] Starting connection attempt to 18.65.229.92 port 443
[tcp @ 000002cfea5dc140] Successfully connected to 18.65.229.92 port 443
[hls @ 000002cfea3adcc0] HLS request for url 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4053.ts', offset 0, playlist 0
[hls @ 000002cfea3adcc0] Opening 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4053.ts' for reading
[tcp @ 000002cfea7d9500] Starting connection attempt to 18.65.229.92 port 443
[tcp @ 000002cfea7d9500] Successfully connected to 18.65.229.92 port 443
[mpegts @ 000002cfea3b7b80] parser not found for codec timed_id3, packets or times may be invalid.
[h264 @ 000002cfea9aa380] Reinit context to 640x368, pix_fmt: yuv420p
Input #0, hls, from 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/chunklist.m3u8':
  Duration: N/A, start: 8103.194000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (Baseline), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, center), 640x360 (640x368), 24.92 tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, mono, fltp
    Metadata:
      variant_bitrate : 0
[mpegts @ 000002cfeaa6e980] service 1 using PCR in pid=256, pcr_period=0ms
[mpegts @ 000002cfeaa6e980] muxrate VBR, sdt every 500 ms, pat/pmt every 100 ms
Output #0, mpegts, to 'file:水無瀬ゆき 2021-12-22 21_15 [14531622].mp4.part':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (Baseline), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, center), 640x360 (0x0), q=2-31, 24.92 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, mono, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls @ 000002cfea3adcc0] HLS request for url 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4054.ts', offset 0, playlist 0
[https @ 000002cfea5c1a00] Opening 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4054.ts' for reading
[tcp @ 000002cfeaa46c00] Starting connection attempt to 18.65.229.92 port 443ts/s speed=6.39x
[tcp @ 000002cfeaa46c00] Successfully connected to 18.65.229.92 port 443
[hls @ 000002cfea3adcc0] Skip ('#EXT-X-VERSION:3')
[hls @ 000002cfea3adcc0] Skip ('#EXT-X-PROGRAM-DATE-TIME:2021-12-23T14:15:12.272+09:00')
[hls @ 000002cfea3adcc0] HLS request for url 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4055.ts', offset 0, playlist 0
[https @ 000002cfea5c1a00] Opening 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4055.ts' for reading
[hls @ 000002cfea3adcc0] HLS request for url 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4056.ts', offset 0, playlist 0
[https @ 000002cfea82d180] Opening 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4056.ts' for reading
[https @ 000002cfead49740] Opening 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/chunklist.m3u8' for reading
[hls @ 000002cfea3adcc0] Skip ('#EXT-X-VERSION:3')
[hls @ 000002cfea3adcc0] Skip ('#EXT-X-PROGRAM-DATE-TIME:2021-12-23T14:15:14.279+09:00')
[hls @ 000002cfea3adcc0] HLS request for url 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4057.ts', offset 0, playlist 0
[https @ 000002cfea82d180] Opening 'https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/media_4057.ts' for reading
frame=  248 fps= 59 q=-1.0 Lsize=    1479kB time=00:00:09.96 bitrate=1216.3kbits/s speed=2.37x
video:1226kB audio:155kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 7.151341%
Input file #0 (https://hls-origin244.showroom-cdn.com/liveedge/36e392a5e0c7fd9258fef0f1781846fba034f21da33813c8eec92e92cb87b940_source/chunklist.m3u8):
  Input stream #0:0 (data): 6 packets read (372 bytes);
  Input stream #0:1 (video): 248 packets read (1255379 bytes);
  Input stream #0:2 (audio): 468 packets read (158244 bytes);
  Total: 722 packets (1413995 bytes) demuxed
Output file #0 (file:水無瀬ゆき 2021-12-22 21_15 [14531622].mp4.part):
  Output stream #0:0 (video): 248 packets muxed (1255379 bytes);
  Output stream #0:1 (audio): 468 packets muxed (158244 bytes);
  Total: 716 packets (1413623 bytes) muxed
[AVIOContext @ 000002cfea9ffbc0] Statistics: 0 seeks, 6 writeouts
[AVIOContext @ 000002cfea954740] Statistics: 638629 bytes read, 0 seeks
[AVIOContext @ 000002cfea66b540] Statistics: 892060 bytes read, 0 seeks
[AVIOContext @ 000002cfead20340] Statistics: 552 bytes read, 0 seeks
[AVIOContext @ 000002cfea45ec00] Statistics: 276 bytes read, 0 seeks
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user
[ffmpeg] Downloaded 1514716 bytes
[download] 100% of 1.44MiB in 00:05

```

**Comment by TriHard7777** [comment]
🤔
