### ISSUE TITLE
TVN24 EXTRACTOR FAILS

### ISSUE THREAD

**Issue by fidodido-48** [yt-dlp/yt-dlp#2109]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

TVN24 extractor not working. 
Direct video link expected:
 **_https://r.dcs.redcdn.pl/https/o2/tvn/web-content/m/p107/v/350db081a661525235354dd3e19b8c05/cacb6004-738b-4165-a380-a49018aa502c-720p.mp4_**

### Verbose log

```shell
debug] Command-line config: ['https://fakty.tvn24.pl/ogladaj-online,60/fakty-z-22-grudnia,1089253.html', '-iUvc']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [TVN24] Extracting URL: https://fakty.tvn24.pl/ogladaj-online,60/fakty-z-22-grudnia,1089253.html
[TVN24] fakty-z-22-grudnia,1089253.html: Downloading webpage
ERROR: [TVN24] fakty-z-22-grudnia,1089253.html: Unable to extract formats; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\tvn24.py", line 67, in _real_extract
  File "yt_dlp\extractor\tvn24.py", line 62, in extract_json
  File "yt_dlp\extractor\common.py", line 1171, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract formats; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\tvn24.py", line 67, in _real_extract
  File "yt_dlp\extractor\tvn24.py", line 62, in extract_json
  File "yt_dlp\extractor\common.py", line 1171, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract formats; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 623, in extract
yt_dlp.utils.RegexNotFoundError: [TVN24] fakty-z-22-grudnia,1089253.html: Unable to extract formats; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by selfisekai** [comment]
haruhi-dl extractor for reference: https://git.sakamoto.pl/laudom/haruhi-dl/-/blob/master/haruhi_dl/extractor/tvn24.py

**Comment by RGitHub2022** [comment]
Any chance of solving the problem for TVN24?

**Comment by dirkf** [comment]
Using the framework of the "patch-available" code from haruhi-dl, `https://fakty.tvn24.pl/zobacz-fakty/najnowsze-wydanie/` redirects, today, to `/zobacz-fakty/wydanie-z-29-stycznia-ep8283878`. If the `_VALID_URL` is adjusted to support patterns where the ID is optionally preceded by two letters after a hyphen, the page is correctly detected and processed by extracting the data for the site's React NuviPlayer (unknown to the web, apparently) from the (traditional) NextJS hydration data. However the tactic of appending `/nuviArticle?playlist&id={video["id"]}&r={route_name}` to the URL no longer produces a player page, but redirects back to the URL without `/nuviArticle...`. Looking at the network traffic, the extractor needs to use [`https://tvn24.pl/api/{video_token}/plst?sources=all`](https://tvn24.pl/api/BYFxAcGcC4HpZANwHYCYAsA6cAbW4B7HSAawENZIB3ASwFMQyBaAWzICtmAjATwGMmVOpCJ0mAExxkQdAOYEmOAK7iAXjVLMqkVT0h8eTQuKbs6LGqKYAnMgHYADBlQAORZADMqBw4CMdj1hkJUQaAEFrEBo+HDoAflwyHhwNEAAyMnAAXl80mnEcgFYATjsANkK7NL4+LMJicgBSVABhZA5kAm1VOjTs+s0AfWp6RkG2TkHePkGhEVjByWk5AkHlNQ1yWZ09A0HjQbMLUUHbR2cXNc9vPwC0sCz1OhwCZB572pICLlGyZpa2O1ZHRrP8WHRVHxdKp2n0QFkSDROlR3mxsiBrEpetYskg0OgjERNIo5GQDJAQARrO9wEouLiUBg0mwkQAFYAESlZUAQSCNDxhZoAMWFeIw2Bwwva7GROjowr44mQTFU4jMfHoxT4XGKqDoqEKHmKvi4qHEZAAZnY7OhfKUyKhUBb0FxXR43FS6BsxGRIkpbEwyMhxJjIMx0KgKsVCqhhWQcDJrO0ZHzUEKADJhAByABEAMotMKsgCig3QLgczKUAA9i8hEFkHHx0OB9eAWC4aOgCC4yuIAI4eMjiYrAXzseRV6t5sgsXB0ABKy0bmAchSAA/plst?sources=all) to get the video sources, but that requires reversing the generation of the gigantic `video_token` (as linked).

Some other extraction tactics from the "patch-available" code still work, with minor tweaks.

**Comment by selfisekai** [comment]
Yeah, the Fakty page used to be one of the legacy pages, I see it got migrated since.

The `/nuviArticle` tactic is probably specific to article pages (see e.g. https://tvn24.pl/swiat/usa-waszyngton-katastrofa-samolotu-zderzyl-sie-ze-smiglowcem-i-spadl-do-rzeki-st8284144), but Fakty shows a VOD-like details page. I believe they existed at the time only as part of TVN24 Go, which only contains DRM-locked videos.

If I recall correctly, this "video_token" was actually a lot of query params getting compressed with some weird algorithm we couldn't identify. There was a way to send a request with an uncompressed URL, but only if some of these params were removed, because the server rejected all URLs above some amount of characters.

**Comment by dirkf** [comment]
In my tests, `/nuviArticle?...` didn't work for article pages yesterday, nor for 8284144 appending `/nuviArticle?playlist&id=8284144&r=tvn24-swiat-story` just now, but maybe I'm doing it wrong, or from the wrong place ...
```
...
[TVN24] 8284144: Downloading webpage
[download] Downloading playlist: Samolot zderzył się ze śmigłowcem i wpadł do rzeki w Waszyngtonie
[TVN24] playlist Samolot zderzył się ze śmigłowcem i wpadł do rzeki w Waszyngtonie: Collected 3 video ids (downloading 3 of them)
[download] Downloading video 1 of 3
[TVN24] 8284343: Downloading JSON metadata
ERROR: 8284343: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')) ...
```
That's the line where the `nuviArticle` URL is passed into `_download_json()`

**Comment by selfisekai** [comment]
Yet newer frontend got deployed recently, and URLs are no longer compressed. TVN24 GO rebranded into TVN24+, Fakty are now behind the paywall, probably DRM-only. Carousel below videos in articles is gone, but the bait-and-switch attention-keeping part is still there
