### ISSUE TITLE
postprocessor-arg error with ffmpeg

### ISSUE THREAD

**Issue by HashLiver** [yt-dlp/yt-dlp#2112]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.25**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

This problem did not appear in v2021.12.01

I want to remove redundant metadata, config:

`--postprocessor-args 'ffmpeg:-metadata synopsis=\"\"`

I know where the problem is, `-metadata` should not be in front of `-i` !

Wrong commandlie (in debug): 

`ffmpeg -y -loglevel repeat+info -metadata 'synopsis=""' -i 'file:/sdcard/Music/test.m4a' -vn -acodec libmp3lame -b:a 128.0k -movflags +faststart 'file:/sdcard/Music/test.mp3'`

Output: `Invalid argument`

_______

Right commandline:

`ffmpeg -y -loglevel repeat+info -i 'file:/sdcard/Music/test.m4a' -metadata 'synopsis=""' -vn -acodec libmp3lame -b:a 128.0k -movflags +faststart 'file:/sdcard/Music/test.mp3'`

### Verbose log

```shell
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -metadata 'synopsis=""' -i 'file:/sdcard/Music/test.m4a' -vn -acodec libmp3lame -b:a 128.0k -movflags +faststart 'file:/sdcard/Music/test.mp3'
[debug] ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with Android (7714059, based on r416183c1) clang version 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee)
  configuration: --arch=aarch64 --as=aarch64-linux-android-clang --cc=aarch64-linux-android-clang --cxx=aarch64-linux-android-clang++ --nm=llvm-nm --pkg-config=/home/builder/.termux-build/_cache/android-r23b-api-24-v1/bin/pkg-config --strip=llvm-strip --cross-prefix=aarch64-linux-android- --disable-indevs --disable-outdevs --enable-indev=lavfi --disable-static --disable-symver --enable-cross-compile --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libdav1d --enable-libmp3lame --enable-libfreetype --enable-libvorbis --enable-libopus --enable-librav1e --enable-libsoxr --enable-libx264 --enable-libx265 --enable-libxvid --enable-libvidstab --enable-libvpx --enable-libwebp --enable-libxml2 --enable-shared --prefix=/data/data/com.termux/files/usr --target-os=android --extra-libs=-landroid-glob --enable-neon
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Option metadata (add metadata) cannot be applied to input url file:/sdcard/Music/test.m4a -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file file:/sdcard/Music/test.m4a.
Error opening input files: Invalid argument
ERROR: Postprocessing: audio conversion failed: Error opening input files: Invalid argument
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 434, in run_ffmpeg
    FFmpegPostProcessor.run_ffmpeg(self, path, out_path, opts)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 326, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 280, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 319, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error opening input files: Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 508, in run
    self.run_ffmpeg(path, temp_path, acodec, more_opts)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 436, in run_ffmpeg
    raise AudioConversionError(err.msg)
yt_dlp.postprocessor.common.AudioConversionError: Error opening input files: Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3062, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3233, in post_process
    info = self.run_pp(pp, info)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3176, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 117, in wrapper
    return func(self, info)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 510, in run
    raise PostProcessingError(
yt_dlp.utils.PostProcessingError: audio conversion failed: Error opening input files: Invalid argument
```

**Comment by pukkandan** [comment]
Fixed in https://github.com/yt-dlp/yt-dlp/commit/8eb4b1bb8ee1d04112a031f3f28bfd545cab0e8e

Or, you can work around the issue using `ffmpeg_o:` instead of `ffmpeg:`

**Comment by joon612** [comment]
Hi @pukkandan, I tried your suggest ,but get nothing by below cmd:
```
> yt-dlp "https://metro.co.uk/video/toddler-waves-loaded-gun-unattended-scary-surveillance-video-2856841/" --output "D:\path\videos\raw\7f39\968f\7f39968f3d7291f4922b82131a824156.mp4" -r 25M --merge-output-format mp4 --match-filters !is_live --force-ipv4 --sleep-requests 1 --embed-metadata --force-overwrites -S res:360,hasaud  --postprocessor-args "ExtractAudio+ffmpeg_i: -i D:/path/videos/raw/7f39/968f/7f39968f3d7291f4922b82131a824156.mp4 -ss 00:00:00 -vn -y -f wav D:/path/audios/wav/7f39/968f/7f39968f3d7291f4922b82131a824156.wav" --verbose
[debug] Command-line config: ['https://metro.co.uk/video/toddler-waves-loaded-gun-unattended-scary-surveillance-video-2856841/', '--output', 'D:\\path\\videos\\raw\\7f39\\968f\\7f39968f3d7291f4922b82131a824156.mp4', '-r', '25M', '--merge-output-format', 'mp4', '--match-filters', '!is_live', '--force-ipv4', '--sleep-requests', '1', '--embed-metadata', '--force-overwrites', '-S', 'res:360,hasaud', '--postprocessor-args', 'ExtractAudio+ffmpeg_i: -i D:/path/videos/raw/7f39/968f/7f39968f3d7291f4922b82131a824156.mp4 -ss 00:00:00 -vn -y -f wav D:/path/audios/wav/7f39/968f/7f39968f3d7291f4922b82131a824156.wav', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.9.16 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-None, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[generic] Extracting URL: https://metro.co.uk/video/toddler-waves-loaded-gun-unattended-scary-surveillance-video-2856841/
[generic] toddler-waves-loaded-gun-unattended-scary-surveillance-video-2856841: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] toddler-waves-loaded-gun-unattended-scary-surveillance-video-2856841: Extracting information
[debug] Looking for embeds
[debug] Identified a html5 embed
[debug] Sort order given by user: res:360, hasaud
[debug] Formats sorted by: hasvid, ie_pref, res:360(360.0), hasaud, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] toddler-waves-loaded-gun-unattended-scary-surveillance-video-2856841-1: Downloading 1 format(s): 0
Deleting existing file D:\path\videos\raw\7f39\968f\7f39968f3d7291f4922b82131a824156.mp4
[debug] Invoking http downloader on "https://videos.metro.co.uk/video/met/2023/01/17/2746256487619867853/480x270_MP4_2746256487619867853.mp4"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: D:\path\videos\raw\7f39\968f\7f39968f3d7291f4922b82131a824156.mp4
[download] 100% of    2.90MiB in 00:00:01 at 1.64MiB/s
[Metadata] Adding metadata to "D:\path\videos\raw\7f39\968f\7f39968f3d7291f4922b82131a824156.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\path\videos\raw\7f39\968f\7f39968f3d7291f4922b82131a824156.mp4" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=Toddler waves around loaded gun unattended in scary surveillance video (1)" -metadata "description=Footage from On Patrol: Live shows a toddler playing with a loaded gun in an apartment building hallway, even turning the weapon towards himself." -metadata "synopsis=Footage from On Patrol: Live shows a toddler playing with a loaded gun in an apartment building hallway, even turning the weapon towards himself." -metadata "purl=https://metro.co.uk/video/toddler-waves-loaded-gun-unattended-scary-surveillance-video-2856841/" -metadata "comment=https://metro.co.uk/video/toddler-waves-loaded-gun-unattended-scary-surveillance-video-2856841/" -movflags "+faststart" "file:D:\path\videos\raw\7f39\968f\7f39968f3d7291f4922b82131a824156.temp.mp4"
```
