### ISSUE TITLE
Add DouyinUserIE

### ISSUE THREAD

**Issue by Ashish0804** [yt-dlp/yt-dlp#2120]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.25**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Global

### Example URLs

User1: https://www.douyin.com/user/MS4wLjABAAAA8U_l6rBzmy7bcy6xOJel4v0RzoR_wfAubGPeJimN__4

User2: https://www.douyin.com/user/MS4wLjABAAAAHOuLcjQuyCh-R811OV_uL3Hdl--MjwPr-u_85pnGiEmpnlzwcAfYnCLIaP50_HJl

### Description

Endpoints are kinda like TT, but the site uses the same signature method which i wasn't able to rev eng, and the app uses aggressive SSL pinning and some sort of sign signing which i wasn't able to rev eng either.

Judging from how TT was rev eng'd, I'd say this will have to done via the app on ios too.

### Verbose log

```shell
C:\Users\Ashish> ytf 'https://www.douyin.com/user/MS4wLjABAAAAHOuLcjQuyCh-R811OV_uL3Hdl--MjwPr-u_85pnGiEmpnlzwcAfYnCLIaP50_HJl'
[debug] Command-line config: ['-F', '--list-subs', '-v', 'https://www.douyin.com/user/MS4wLjABAAAAHOuLcjQuyCh-R811OV_uL3Hdl--MjwPr-u_85pnGiEmpnlzwcAfYnCLIaP50_HJl']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.25 [87e049962]
[debug] Python version 3.8.8 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.0.1 (needs_adtstoasc), ffprobe 3.0.1
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.douyin.com/user/MS4wLjABAAAAHOuLcjQuyCh-R811OV_uL3Hdl--MjwPr-u_85pnGiEmpnlzwcAfYnCLIaP50_HJl
[generic] MS4wLjABAAAAHOuLcjQuyCh-R811OV_uL3Hdl--MjwPr-u_85pnGiEmpnlzwcAfYnCLIaP50_HJl: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] MS4wLjABAAAAHOuLcjQuyCh-R811OV_uL3Hdl--MjwPr-u_85pnGiEmpnlzwcAfYnCLIaP50_HJl: Downloading webpage
[generic] MS4wLjABAAAAHOuLcjQuyCh-R811OV_uL3Hdl--MjwPr-u_85pnGiEmpnlzwcAfYnCLIaP50_HJl: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.douyin.com/user/MS4wLjABAAAAHOuLcjQuyCh-R811OV_uL3Hdl--MjwPr-u_85pnGiEmpnlzwcAfYnCLIaP50_HJl
Traceback (most recent call last):
  File "c:\users\ashish\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1352, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\ashish\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1421, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\ashish\anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "c:\users\ashish\anaconda3\lib\site-packages\yt_dlp\extractor\generic.py", line 3817, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.douyin.com/user/MS4wLjABAAAAHOuLcjQuyCh-R811OV_uL3Hdl--MjwPr-u_85pnGiEmpnlzwcAfYnCLIaP50_HJl
```

**Comment by purple5pumpkin235** [comment]
looks like individual video links aren't even working for this extractor

**Comment by purple5pumpkin235** [comment]
Was the douyin extractor working for individual videos when posted this? Seems to be broken ATM.

**Comment by Ashish0804** [comment]
yes
even if it's broken then open a new proper issue

**Comment by MinePlayersPE** [comment]
https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid=ID_HERE&count=21&max_cursor=0

**Comment by atsushi2965** [comment]
I'd also like to ask for your all help.
User3: https://www.douyin.com/user/MS4wLjABAAAAgjKXcEongvGo7Gg6neyzng0G8CemLlMvVV9_W2FG2ww

**Comment by chengnan049** [comment]
So can we solve it?
