### ISSUE TITLE
[ZEE5] Needs change in valid url format 

### ISSUE THREAD

**Issue by kr-v** [yt-dlp/yt-dlp#2127]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.25**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Description

ZEE5 has changed URL structure.
"tvshows" needs to be changed to "tv-shows" 

### Verbose log

```shell
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: ec2e44fc5
[debug] Python version 3.9.7 (CPython 64bit) - macOS-12.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.zee5.com/tv-shows/details/sa-re-ga-ma-pa-2021/0-6-3497/sa-re-ga-ma-pa-2021-december-25-2021/0-1-6z563724
[generic] 0-1-6z563724: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 0-1-6z563724: Downloading webpage
[generic] 0-1-6z563724: Extracting information
[debug] Looking for video embeds
ERROR: 
Traceback (most recent call last):
  File "/Users/mogambo/Desktop/yt-dlp/yt_dlp/YoutubeDL.py", line 1335, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/mogambo/Desktop/yt-dlp/yt_dlp/YoutubeDL.py", line 1404, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/mogambo/Desktop/yt-dlp/yt_dlp/extractor/common.py", line 598, in extract
    ie_result = self._real_extract(url)
  File "/Users/mogambo/Desktop/yt-dlp/yt_dlp/extractor/generic.py", line 3653, in _real_extract
    json_ld = self._search_json_ld(webpage, video_id, default={})
  File "/Users/mogambo/Desktop/yt-dlp/yt_dlp/extractor/common.py", line 1364, in _search_json_ld
    json_ld = self._json_ld(json_ld, video_id, fatal=fatal, expected_type=expected_type)
  File "/Users/mogambo/Desktop/yt-dlp/yt_dlp/extractor/common.py", line 1511, in _json_ld
    traverse_json_ld(json_ld)
  File "/Users/mogambo/Desktop/yt-dlp/yt_dlp/extractor/common.py", line 1499, in traverse_json_ld
    extract_video_object(e)
  File "/Users/mogambo/Desktop/yt-dlp/yt_dlp/extractor/common.py", line 1436, in extract_video_object
    'title': unescapeHTML(e.get('name')),
  File "/Users/mogambo/Desktop/yt-dlp/yt_dlp/utils.py", line 2276, in unescapeHTML
    assert type(s) == compat_str
AssertionError
```

**Comment by Ashish0804** [comment]
fixed in https://github.com/yt-dlp/yt-dlp/commit/ee7b9bdf5d7d5f9a4716aa193b0b1887a229d2ea
