### ISSUE TITLE
[Funimation] --extractor-args funimation:language Support Chinese language

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#2152]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Example URLs

https://www.funimation.com/shows/link-click/

### Description

In my configuration file I have the option --extractor-args funimation:language=japanese,chinese.
But when I tried to download the anime with chinese language apparently they were not supported by the extractor-args. 
Or maybe it has it implemented but maybe I didn't put it in the right way.

My config file
```
#Download configuration file - Funimation / Compatibility -yt-dlp=2021.12.01-

#Video Filtering Options
-f "(bv[height<=1080]+ba/b[height<=1080])[format_note*=Uncut]/
(bv[height<=1080]+ba/b[height<=1080])[format_note*=Simulcast]"

#Subtitles Options
--sub-lang all,-en_Uncut_CC,-en_CC,-pt,-pt_Uncut --embed-subs --sub-format srt

#Output Template
-o "%(extractor_key)s/%(series)s/%(series)s S%(season_number)sE%(episode_number)s - %(episode)s.%(ext)s"

#User Login Credentials
--cookies cookies-funimation-com.txt -n

#Extractor Options
--extractor-args funimation:language=japanese,chinese

#Downloader Options
#------------------------hlsnative---------------------
-N 3
#-------------------external-downloader----------------
--downloader "m3u8:aria2c" --downloader-args aria2c:-j3

#Additional yt-dlp options
--add-metadata -v --rm-cache-dir --no-check-certificates -R 1 --keep-fragments -w

#------------------------------------------End of configuration file---------------------------------------
```

### Verbose log

```shell
C:\youtube-dl>yt-dlp --config-location funimation.conf https://www.funimation.com/shows/link-click/
[debug] Command-line config: ['--config-location', 'funimation.conf', 'https://www.funimation.com/shows/link-click/']
[debug] Custom config file: funimation.conf
[debug] Custom config: ['-f', '(bv[height<=1080]+ba/b[height<=1080])[format_note*=Uncut]/\n(bv[height<=1080]+ba/b[height<=1080])[format_note*=Simulcast]', '--sub-lang', 'all,-en_Uncut_CC,-en_CC,-pt,-pt_Uncut', '--embed-subs', '--sub-format', 'srt', '-o', '%(extractor_key)s/%(series)s/%(series)s S%(season_number)sE%(episode_number)s - %(episode)s.%(ext)s', '--cookies', 'cookies-funimation-com.txt', '-n', '--extractor-args', 'funimation:language=japanese,chinese', '-N', '3', '--downloader', 'm3u8:aria2c', '--downloader-args', 'aria2c:-j3', '--add-metadata', '-v', '--rm-cache-dir', '--no-check-certificates', '-R', '1', '--keep-fragments', '-w']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 1e5c83b26
[debug] Python version 3.9.7 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-105035-g617452ce2c-20211227 (setts), ffprobe N-105035-g617452ce2c-20211227
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Removing cache dir C:\Users\ElviaPC/.cache\yt-dlp ..
[debug] [funimation:show] Extracting URL: https://www.funimation.com/shows/link-click/
[funimation:show] link-click: Downloading JSON metadata
[funimation:show] link-click: Downloading JSON metadata
[download] Downloading playlist: LINK CLICK
[funimation:show] playlist LINK CLICK: Collected 16 videos; downloading 16 of them
[download] Downloading video 1 of 16
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: https://www.funimation.com/shows/link-click/emma
[funimation:page] link-click_emma: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/1587506
[Funimation] 1587506: Downloading player webpage for 1587506
ERROR: [Funimation] 1456798: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1437, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1489, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 2378, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 943, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Funimation] 1456798: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
What does `yt-dlp -F https://www.funimation.com/shows/link-click/emma` give you?

**Comment by CZeil** [comment]
> What does `yt-dlp -vF https://www.funimation.com/shows/link-click/emma` give you?

```
C:\youtube-dl>yt-dlp -vF https://www.funimation.com/shows/link-click/emma
[debug] Command-line config: ['-vF', 'https://www.funimation.com/shows/link-click/emma']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 1e5c83b26
[debug] Python version 3.9.7 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-105035-g617452ce2c-20211227 (setts), ffprobe N-105035-g617452ce2c-20211227
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[funimation:page] Checking geo-location
[debug] [funimation:page] Extracting URL: https://www.funimation.com/shows/link-click/emma
[funimation:page] link-click_emma: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/1587506
[Funimation] 1587506: Downloading player webpage for 1587506
[Funimation] emma: Downloading Simulcast chinese (mandarin, prc) (1587506) JSON
[Funimation] emma: Downloading Simulcast chinese (mandarin, prc) (1587506) m3u8 information
[debug] Sort order given by extractor: lang, source
[debug] Formats sorted by: hasvid, ie_pref, lang, source, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] Available formats for 1456798:
ID                             EXT RESOLUTION FPS │   FILESIZE   TBR PROTO  │ VCODEC        VBR ACODEC     MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
1587506-hls-audio-aacl-256-cmn mp4                │                  m3u8_n │ audio only        unknown    [chinese (mandarin, prc)] Simulcast
1587506-mp4                    mp4 unknown        │                  https  │ unknown           unknown    [chinese (mandarin, prc)] Simulcast
1587506-hls-416                mp4 416x234     24 │ ~ 70.89MiB  416k m3u8_n │ avc1.4D4028  416k video only [chinese (mandarin, prc)] Simulcast
1587506-hls-575                mp4 640x360     24 │ ~ 97.99MiB  575k m3u8_n │ avc1.4D4028  575k video only [chinese (mandarin, prc)] Simulcast
1587506-hls-863                mp4 768x432     24 │ ~147.06MiB  863k m3u8_n │ avc1.4D4028  863k video only [chinese (mandarin, prc)] Simulcast
1587506-hls-1168               mp4 768x432     24 │ ~199.04MiB 1168k m3u8_n │ avc1.4D4028 1168k video only [chinese (mandarin, prc)] Simulcast
1587506-hls-1872               mp4 960x540     24 │ ~319.01MiB 1872k m3u8_n │ avc1.4D4028 1872k video only [chinese (mandarin, prc)] Simulcast
1587506-hls-2626               mp4 1280x720    24 │ ~447.50MiB 2626k m3u8_n │ avc1.640028 2626k video only [chinese (mandarin, prc)] Simulcast
1587506-hls-3843               mp4 1280x720    24 │ ~654.89MiB 3843k m3u8_n │ avc1.640028 3843k video only [chinese (mandarin, prc)] Simulcast
1587506-hls-4900               mp4 1920x1080   24 │ ~835.01MiB 4900k m3u8_n │ avc1.640028 4900k video only [chinese (mandarin, prc)] Simulcast
1587506-hls-6329               mp4 1920x1080   24 │ ~  1.05GiB 6329k m3u8_n │ avc1.640028 6329k video only [chinese (mandarin, prc)] Simulcast

```

**Comment by pukkandan** [comment]
hm.. the language code is `chinese (mandarin, prc)`. But you can't pass it to extractor args becase `,` has special meaning

**Comment by pukkandan** [comment]
With 042931a50733d621c02d3e7127195bef574df213, you can use `chinese (mandarin\, prc)` as the language

**Comment by CZeil** [comment]
> With [042931a](https://github.com/yt-dlp/yt-dlp/commit/042931a50733d621c02d3e7127195bef574df213), you can use `chinese (mandarin\, prc)` as the language

Ok, I try it.

**Comment by CZeil** [comment]
I got this @pukkandan 

```
C:\youtube-dl>yt-dlp --config-location funimation.conf https://www.funimation.com/shows/link-click/ --playlist-item 1
[debug] Command-line config: ['--config-location', 'funimation.conf', 'https://www.funimation.com/shows/link-click/', '--playlist-item', '1']
[debug] Custom config file: funimation.conf
[debug] Custom config: ['-f', '(bv[height<=1080]+ba/b[height<=1080])[format_note*=Uncut]/\n(bv[height<=1080]+ba/b[height<=1080])[format_note*=Simulcast]', '--sub-lang', 'all,-en_Uncut_CC,-en_CC,-pt,-pt_Uncut', '--embed-subs', '--sub-format', 'srt', '-o', '%(extractor_key)s/%(series)s/%(series)s S%(season_number)sE%(episode_number)s - %(episode)s.%(ext)s', '--cookies', 'cookies-funimation-com.txt', '-n', '--extractor-args', 'funimation:language=chinese', '(mandarin,', 'prc)', '-N', '2', '--downloader', 'm3u8:aria2c', '--downloader-args', 'aria2c:-j2', '--add-metadata', '-v', '--rm-cache-dir', '--no-check-certificates', '-R', '0', '--keep-fragments', '-w']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 11aa91a12
[debug] Python version 3.9.7 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-105035-g617452ce2c-20211227 (setts), ffprobe N-105035-g617452ce2c-20211227
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Removing cache dir C:\Users\ElviaPC/.cache\yt-dlp ..
[debug] [generic] Extracting URL: (mandarin,
ERROR: [generic] '(mandarin,' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:(mandarin," ) to search YouTube
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\extractor\common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\extractor\generic.py", line 2558, in _real_extract
    raise ExtractorError(

[debug] [generic] Extracting URL: prc)
ERROR: [generic] 'prc)' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:prc)" ) to search YouTube
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\extractor\common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\extractor\generic.py", line 2558, in _real_extract
    raise ExtractorError(

[debug] [funimation:show] Extracting URL: https://www.funimation.com/shows/link-click/
[funimation:show] link-click: Downloading JSON metadata
[funimation:show] link-click: Downloading JSON metadata
[download] Downloading playlist: LINK CLICK
[funimation:show] playlist LINK CLICK: Collected 16 videos; downloading 1 of them
[download] Downloading video 1 of 1
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: https://www.funimation.com/shows/link-click/emma
[funimation:page] link-click_emma: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/1587506
[Funimation] 1587506: Downloading player webpage for 1587506
ERROR: [Funimation] 1456798: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1355, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1439, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1491, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 2380, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 943, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Funimation] 1456798: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

[download] Finished downloading playlist: LINK CLICK
```

**Comment by pukkandan** [comment]
--extractor-args "funimation:language=chinese (mandarin \,prc)"

**Comment by CZeil** [comment]
```
C:\youtube-dl>yt-dlp --config-location funimation.conf https://www.funimation.com/shows/link-click/ --playlist-item 1
[debug] Command-line config: ['--config-location', 'funimation.conf', 'https://www.funimation.com/shows/link-click/', '--playlist-item', '1']
[debug] Custom config file: funimation.conf
[debug] Custom config: ['-f', '(bv[height<=1080]+ba/b[height<=1080])[format_note*=Uncut]/\n(bv[height<=1080]+ba/b[height<=1080])[format_note*=Simulcast]', '--sub-lang', 'all,-en_Uncut_CC,-en_CC,-pt,-pt_Uncut', '--embed-subs', '--sub-format', 'srt', '-o', '%(extractor_key)s/%(series)s/%(series)s S%(season_number)sE%(episode_number)s - %(episode)s.%(ext)s', '--cookies', 'cookies-funimation-com.txt', '-n', '--extractor-args', 'funimation:language=chinese (mandarin \\,prc)', '-N', '3', '--downloader', 'm3u8:aria2c', '--downloader-args', 'aria2c:-j3', '--add-metadata', '-v', '--rm-cache-dir', '--no-check-certificates', '-R', '0', '--keep-fragments', '-w']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 11aa91a12
[debug] Python version 3.9.7 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-105035-g617452ce2c-20211227 (setts), ffprobe N-105035-g617452ce2c-20211227
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Removing cache dir C:\Users\ElviaPC/.cache\yt-dlp ..
[debug] [funimation:show] Extracting URL: https://www.funimation.com/shows/link-click/
[funimation:show] link-click: Downloading JSON metadata
[funimation:show] link-click: Downloading JSON metadata
[download] Downloading playlist: LINK CLICK
[funimation:show] playlist LINK CLICK: Collected 16 videos; downloading 1 of them
[download] Downloading video 1 of 1
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: https://www.funimation.com/shows/link-click/emma
[funimation:page] link-click_emma: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/1587506
[Funimation] 1587506: Downloading player webpage for 1587506
ERROR: [Funimation] 1456798: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1355, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1439, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1491, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 2380, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 943, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Funimation] 1456798: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

[download] Finished downloading playlist: LINK CLICK
```

**Comment by pukkandan** [comment]
typo in the command I gave. It should be `mandarin\, prc`, nor `mandarin \,prc`. Corrected above
