### ISSUE TITLE
TennisTV extractor broken

### ISSUE THREAD

**Issue by beta2k** [yt-dlp/yt-dlp#2177]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Everywhere

### Description

In the last few days the website was relaunched and the whole design changed. Therefore, as expected, the extractor doesn't work anymore. The login seems to be broken and maybe the fetching of the m3u8 is also different. I tested manually and the `a.m3u8` is relevant now.

### Verbose log

```shell
D:\>yt-dlp -Uv -F -p PASSWORD -u USERNAME https://www.tennistv.com/videos/2351668/melbourne-two-murray-river-open-2021-r2-bourchier-kyrgios
[debug] Command-line config: ['-Uv', '-F', '-p', 'PRIVATE', '-u', 'PRIVATE', 'https://www.tennistv.com/videos/2351668/melbourne-two-murray-river-open-2021-r2-bourchier-kyrgios']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg n4.4-19-g8d172d9409 (setts), ffprobe n4.4-19-g8d172d9409
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[TennisTV] Logging in
ERROR: [TennisTV] 2351668: Login failed (wrong password?): HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 717, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3458, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by Bricio** [comment]
pukkadan, i have only free account but still getting error in a free video

```
D:\ytdlp\yt-dlp-tennistv>yt-dlp.cmd -v -u PRIVATE -p PRIVATE https://www.tennistv.com/videos/2650480/best-matches-of-2022-part-5 --no-config
[debug] Command-line config: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.tennistv.com/videos/2650480/best-matches-of-2022-part-5', '--no-config']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2022.06.22.1 [a86e01e74]
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, certifi-2021.10.08, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[TennisTV] None: Downloading webpage
ERROR: 'TennisTVIE' object has no attribute 'headers'
Traceback (most recent call last):
  File "D:\ytdlp\yt-dlp-tennistv\yt_dlp\YoutubeDL.py", line 1427, in wrapper
    return func(self, *args, **kwargs)
  File "D:\ytdlp\yt-dlp-tennistv\yt_dlp\YoutubeDL.py", line 1497, in __extract_info
    ie_result = ie.extract(url)
  File "D:\ytdlp\yt-dlp-tennistv\yt_dlp\extractor\common.py", line 645, in extract
    self.initialize()
  File "D:\ytdlp\yt-dlp-tennistv\yt_dlp\extractor\common.py", line 551, in initialize
    self._perform_login(username, password)
  File "D:\ytdlp\yt-dlp-tennistv\yt_dlp\extractor\tennistv.py", line 49, in _perform_login
    headers=self.headers, data=urlencode_postdata({
AttributeError: 'TennisTVIE' object has no attribute 'headers'
```

**Comment by pukkandan** [comment]
should be fixed now

**Comment by pukkandan** [comment]
could you share the account details with me? It is difficult to write code that I cannot run

**Comment by Bricio** [comment]
i just sent it in discord
