### ISSUE TITLE
[Broken] Viu Singapore not working

### ISSUE THREAD

**Issue by shivsah** [yt-dlp/yt-dlp#219]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.04.03**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-F', 'https://www.viu.com/ott/sg/en-us/vod/304335/Moon-Lovers-Scarlet-Heart-Ryeo', '--verbose']                                          [debug] Loading archive file None                       [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8                                                [debug] yt-dlp version 2021.04.03                       [debug] Python version 3.9.2 (CPython 64bit) - Linux-4.14.113-21054248-aarch64-with-libc                        [debug] exe versions: none                              [debug] Proxy map: {}                                   [viu:ott] 304335: Downloading video info                [viu:ott] 304335: Downloading stream info               ERROR: An extractor error has occurred. (caused by KeyError('data')); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/yt_dlp/extractor/viu.py", line 226, in _real_extract
    stream_data = self._download_json(
KeyError: 'data'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/yt_dlp/extractor/viu.py", line 226, in _real_extract
    stream_data = self._download_json(
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1026, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1047, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 571, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
yt_dlp.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('data')); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Viu Singapore seems to be broken

**Comment by zackmark29** [comment]
I already fixed this with C#, I don't know much about python. But I will try if I have time.

**Comment by pukkandan** [comment]
> I already fixed this with C#

@zackmark29 Fixed what? The URL in this issue was fixed by https://github.com/yt-dlp/yt-dlp/commit/baa58739429cd04eb250036d90a7339b640aa932

```
$ yt-dlp https://www.viu.com/ott/sg/en-us/vod/304335/Moon-Lovers-Scarlet-Heart-Ryeo
[viu:ott] 304335: Downloading video info
[viu:ott] Downloading playlist 15237 - add --no-playlist to just download video
[download] Downloading playlist: Moon Lovers: Scarlet Heart Ryeo
[viu:ott] playlist Moon Lovers: Scarlet Heart Ryeo: Collected 20 videos; downloading 20 of them
[download] Downloading video 1 of 20
[viu:ott] 304335: Downloading video info
[viu:ott] 304335: Downloading stream info
[info] 304335: Downloading format(s) s1080p
[download] Destination: Traveling Back to Goryeo [304335].mp4
ffmpeg version 3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[h264 @ 000002379e63e1c0] non-existing SPS 0 referenced in buffering period
    Last message repeated 1 times
[h264 @ 000002379e455440] non-existing SPS 0 referenced in buffering period
Input #0, hls,applehttp, from 'https://d1k2us671qcoau.cloudfront.net/vodapi/viu_aws.m3u8?vid=76527ba3176f1d17db37afff62be49a1&layer=Layer4&ts=202104261848&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMWsydXM2NzFxY29hdS5jbG91ZGZyb250Lm5ldC92b2RhcGkvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYxOTQ0ODQ4NH19fV19&Signature=iTUBJeu3uO0XAqsGffiYNh-J1GhnriW740gmK4U8p5hOfcGOpAW1KCTe8tMKbbg~DzzESRu9p0NHcdPkrWqrr-N3E9ijMvnl2PLSjjJWMNoWCDiEA~MHLFkCpvQBdfaf45MufFuoP73kxKwj8QG5g55xuIacfc~yN-VTNIfkjITWWVis6mRyaeYdh2-28fN1O6dM3XgYuiTN3thWTw43xo0pK7VJiQFryjTdISPakwHoaIxbrZosJQns4mYDzcCOKTXAOlbWLeCFEydaJGtQYMxQvxTwZ1U8AXVpR5FFngOm8IfuMI1SKKxyKraW3wRSJv5gjehW5oewsjyUigu-1w__&Key-Pair-Id=APKAJ6Z4RF5IYK7Y3SQQ':
  Duration: 00:59:45.08, start: 1.437344, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 98 kb/s
Output #0, mp4, to 'file:Traveling Back to Goryeo [304335].mp4.part':
  Metadata:
    encoder         : Lavf57.25.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x1080, q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 98 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  116 fps=0.0 q=-1.0 Lsize=    2270kB time=00:00:04.56 bitrate=4075.2kbits/s speed=5.67x
video:2212kB audio:54kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.187210%
Exiting normally, received signal 2.

ERROR: Interrupted by user
```
