### ISSUE TITLE
NHL.com Videos Started Throwing a 'urlopen error' on all videos

### ISSUE THREAD

**Issue by feerlessleadr** [yt-dlp/yt-dlp#2192]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

First off, thanks for this awesome program. I've been running dlp on a headless ubuntuserver without issue since the initial fork way back when. 

I have a bash script that's been running to automatically download videos from various NHL teams' websites. Up until a few days ago, it's been working without issue. However, I only realized today that it looks like the scritps are erroring out and failing to download. I haven't made any changes to my script or config files, so I'm assuming something changed on the NHL's end (or I'm making a fairly obvious mistake that I'm missing). 

I can't quite tell what's happening, since sometimes it seems like the video will error out and fail, and sometimes the video will download, however the download will take EXTREMEMLY long (like 30 - 45 minutes for a a 5 - 6 minute video on a gigabit connection).

In the log below, I tried to download this video multiple times, and eventually it did download, but it took a REALLY long time. 

### Verbose log

```shell
kevin@linuxserver:~/youtube-dl/scripts$ ./ytdl-devilsnhldotcomrecaps https://www.nhl.com/devils/video/recap-njd-4-buf-3/t-277443724/c-10044702
[debug] Command-line config: ['--config-location', '/home/kevin/youtube-dl/configs/config.txt', '-o', '/home/kevin/youtube-dl/temp-downloads/devils-recaps-tmp/20211231 - %(title)s.%(ext)s', '--match-title', '(?=.*Recap)', '-v', 'https://www.nhl.com/devils/video/recap-njd-4-buf-3/t-277443724/c-10044702']
[debug] Custom config file: /home/kevin/youtube-dl/configs/config.txt
[debug] Custom config: ['-S', 'res,codec:vp9.2:opus,br,fps', '--merge-output-format', 'mkv', '--extractor-args', 'youtube:player_client=android', '--write-info-json', '--write-thumbnail', '--convert-thumbnails', 'jpg', '--write-sub', '--add-metadata', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--sponsorblock-remove', 'all', '--ignore-errors', '--proxy', '', '--throttled-rate', '100K', '--download-archive', '/home/kevin/youtube-dl/archives/downloaded.txt', '--no-check-certificate']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.3.2-0york0, ffprobe 4.3.2-0york0
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file '/home/kevin/youtube-dl/archives/downloaded.txt'
[debug] [nhl.com] Extracting URL: https://www.nhl.com/devils/video/recap-njd-4-buf-3/t-277443724/c-10044702
[nhl.com] 10044702: Downloading JSON metadata
[nhl.com] 10044702: Downloading m3u8 information
WARNING: [nhl.com] Failed to download m3u8 information: <urlopen error [Errno 0] Error>
[nhl.com] 10044702: Downloading m3u8 information
WARNING: [nhl.com] Failed to download m3u8 information: <urlopen error [Errno 0] Error>
[nhl.com] 10044702: Downloading m3u8 information
WARNING: [nhl.com] Failed to download m3u8 information: <urlopen error [Errno 111] Connection refused>
[nhl.com] 10044702: Downloading m3u8 information
WARNING: [nhl.com] Failed to download m3u8 information: <urlopen error [Errno 111] Connection refused>
[nhl.com] 10044702: Downloading m3u8 information
WARNING: [nhl.com] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_60-552 video format URL
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_60-966 video format URL
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_60-1360 video format URL
[nhl.com] 10044702: HTTP_CLOUD_WIRED_60-1360 video format URL is invalid, skipping: <urlopen error _ssl.c:835: The handshake operation timed out>
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_60-2001 video format URL
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_60-2770 video format URL
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_60-3897 video format URL
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_60-6159 video format URL
[nhl.com] 10044702: Downloading m3u8 information
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_WEB-552 video format URL
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_WEB-966 video format URL
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_WEB-1360 video format URL
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_WEB-2001 video format URL
[nhl.com] 10044702: HTTP_CLOUD_WIRED_WEB-2001 video format URL is invalid, skipping: <urlopen error _ssl.c:835: The handshake operation timed out>
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_WEB-2770 video format URL
[nhl.com] 10044702: Checking HTTP_CLOUD_WIRED_WEB-3897 video format URL
[nhl.com] 10044702: HTTP_CLOUD_WIRED_WEB-3897 video format URL is invalid, skipping: <urlopen error [Errno 0] Error>
[debug] Sort order given by user: res, codec:vp9.2:opus, br, fps
[debug] Formats sorted by: hasvid, ie_pref, res, vcodec:vp9.2(10), acodec:opus(11), tbr, vbr, abr, fps, lang, quality, hdr:12(7), filesize, fs_approx, asr, proto, vext, aext, hasaud, source, id
[SponsorBlock] SponsorBlock is not supported for NHL
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 10044702: Downloading 1 format(s): HTTP_CLOUD_WIRED_60-6159
[info] Downloading video thumbnail 12 ...
[info] Writing video thumbnail 12 to: /home/kevin/youtube-dl/temp-downloads/devils-recaps-tmp/20211231 - Recap - NJD 4, BUF 3.jpg
[info] Writing video metadata as JSON to: /home/kevin/youtube-dl/temp-downloads/devils-recaps-tmp/20211231 - Recap - NJD 4, BUF 3.info.json
[ThumbnailsConvertor] Thumbnail "/home/kevin/youtube-dl/temp-downloads/devils-recaps-tmp/20211231 - Recap - NJD 4, BUF 3.jpg" is already in the requested format
[debug] Invoking downloader on "https://hlslive-wsczoominwestus.med.nhl.com/publish-hls/4098739/5598866/game.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 76
[download] Destination: /home/kevin/youtube-dl/temp-downloads/devils-recaps-tmp/20211231 - Recap - NJD 4, BUF 3.mp4
[download]   2.6% of ~233.56MiB at 67.31KiB/s ETA 34:02 (frag 2/76)ERROR: unable to download video data: <urlopen error [Errno 0] Error>
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1446, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 2991, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 2701, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/downloader/hls.py", line 358, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/downloader/fragment.py", line 515, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/downloader/fragment.py", line 449, in download_fragment
    success, frag_content = self._download_fragment(ctx, fragment['url'], info_dict, headers)
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/downloader/fragment.py", line 133, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/downloader/http.py", line 119, in establish_connection
    raise err
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/downloader/http.py", line 113, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 3458, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/kevin/.local/lib/python3.6/site-packages/yt_dlp/utils.py", line 1394, in https_open
    req, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 0] Error>
```

**Comment by feerlessleadr** [comment]
Turns out that it was an issue with my upstream dns provider on my 2 piholes. I updated my piholes, changed upstream dns providers, and now the issues seemed to have gone away. Apologies.
