### ISSUE TITLE
Game Show Network stream request

### ISSUE THREAD

**Issue by dare2** [yt-dlp/yt-dlp#2241]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://watch.gameshownetwork.com/channels/c6f0faf0-6555-11ea-b686-2f0e735e3aab/play

### Description

Game Show Network (GSN) just recently made available an online stream of their channel. It is obviously MSO locked.

### Verbose log

```shell
yt-dlp https://watch.gameshownetwork.com/channels/c6f0faf0-6555-11ea-b686-2f0e735e3aab/play --verbose
[debug] Command-line config: ['https://watch.gameshownetwork.com/channels/c6f0faf0-6555-11ea-b686-2f0e735e3aab/play', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-81707-g11777eb (needs_adtstoasc), ffprobe N-81707-g11777eb, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://watch.gameshownetwork.com/channels/c6f0faf0-6555-11ea-b686-2f0e735e3aab/play
[generic] play: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] play: Downloading webpage
[generic] play: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://watch.gameshownetwork.com/channels/c6f0faf0-6555-11ea-b686-2f0e735e3aab/play
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3829, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://watch.gameshownetwork.com/channels/c6f0faf0-6555-11ea-b686-2f0e735e3aab/play
```

**Comment by dare2** [comment]
I'm willing to share my account credentials. Who do I send them to?

**Comment by dare2** [comment]
Actually, with the DYV MSO not working, I guess I can't help after all. That is still an issue right?

**Comment by doe1080** [comment]
this subdomain is no longer available, and videos are now available via YouTube
