### ISSUE TITLE
improve the generic extractor to look for brightcove

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#2258]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://nypost.com/video/meet-ameca-the-humanoid-robot-that-is-terrifyingly-realistic/

### Description

I don't know if this really belongs in "Site support request," but...

I frequently encounter this annoyance on many sites, where yt-dlp checks some "generic" extractor, but not other obvious ones.

In this case, the source of the example page contains (removing the backslash escaping characters) `https://players.brightcove.net/4137224153001/ed38fae1-4db1-4308-8095-399a04010bc1_default/index.html?videoId=6290479995001` which one can easily use (after finding it) to download the video. I (and others) would certainly appreciate it if the generic extractor could find brightcove links (a platform used by a large number of sites) and download the associated videos without having to dig through the source.

### Verbose log

```shell
$ yt-dlp-2021.12.27 -v 'https://nypost.com/video/meet-ameca-the-humanoid-robot-that-is-terrifyingly-realistic/'
[debug] Command-line config: ['-v', 'https://nypost.com/video/meet-ameca-the-humanoid-robot-that-is-terrifyingly-realistic/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.11-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Crypto
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://nypost.com/video/meet-ameca-the-humanoid-robot-that-is-terrifyingly-realistic/
[generic] meet-ameca-the-humanoid-robot-that-is-terrifyingly-realistic: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] meet-ameca-the-humanoid-robot-that-is-terrifyingly-realistic: Downloading webpage
[generic] meet-ameca-the-humanoid-robot-that-is-terrifyingly-realistic: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://nypost.com/video/meet-ameca-the-humanoid-robot-that-is-terrifyingly-realistic/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp-2021.12.27/yt_dlp/YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp-2021.12.27/yt_dlp/YoutubeDL.py", line 1423, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp-2021.12.27/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp-2021.12.27/yt_dlp/extractor/generic.py", line 3829, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://nypost.com/video/meet-ameca-the-humanoid-robot-that-is-terrifyingly-realistic/
```

**Comment by pukkandan** [comment]
The generic extractor has some code to detect brightcove embeds, it just isnt working in this case (probably coz of the escaped URL)

**Comment by dirkf** [comment]
This seems like a problem with the `_json_ld()` IE method together with a bit of a tweak to the generic extractor.

The page has a `<script type="application/ld+json">` element containing a `NewsArticle` object whose `video` member is a `VideoObject` .

The generic extractor calls `_search_json_ld()` (l.3665) and this should find the video (not with yt-dl, because it doesn't traverse the JSON structure to find a `VideoObject` -- so far).

But the video URL is the value of the `embedURL` while the `extract_video_object()` routine only checks `contentURL`, whereas it could look for `dict_get(e, ('contentUrl', 'embedUrl'))`.

Also, if the Brightcove player URL is returned by making that change, the format listing is unsatisfactory, because only m3u8 URLs are parsed in this context. The default should probably be to pass the URL to `self.url_result()`.
