### ISSUE TITLE
error EOF occurred in violation of protocol (_ssl.c:997)

### ISSUE THREAD

**Issue by 8RATH** [yt-dlp/yt-dlp#2261]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

As the title says, it will report this ERROR every time I try to download a video, no matter from Youtube or PornHub or Vimeo. 
Now I have to state that there is a workaround that once it stop at there, reporting this error, I can continue downloading by simply repeat the same command, usually without an issue, except the same 'unexpected EOF'.

My internet access is enough to watch videos in browsers without an issue. 

What I want yt-dlp to do is automatically retry, for example, 10 times, before it gives up. Because 'manual retry' as described above almost always work. I'm wondering why it won't do auto retry currently. 

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.youtube.com/watch?v=njX2bu-_Vw4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=njX2bu-_Vw4
[youtube] njX2bu-_Vw4: Downloading webpage
[youtube] njX2bu-_Vw4: Downloading android player API JSON
[debug] Loading youtube-nsig.edff9f99 from cache
[debug] [youtube] Decrypted nsig vlS1RKBMxtL1o4 => Hlpqjv1tu8jqXA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] njX2bu-_Vw4: Downloading 1 format(s): 337+258
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking downloader on "https://rr1---sn-i3belnls.googlevideo.com/videoplayback?expire=1641646078&ei=njPZYeeDHITikgbFjo-gCw&ip=218.102.202.52&id=o-AK1w_il0NkTQfp2xpEnivotvZanGq_FjeE56bslAD9ob&itag=337&source=youtube&requiressl=yes&mh=zf&mm=31%2C29&mn=sn-i3belnls%2Csn-i3b7knsl&ms=au%2Crdu&mv=m&mvi=1&pl=26&initcwndbps=1475000&vprv=1&mime=video%2Fwebm&gir=yes&clen=440038438&dur=126.526&lmt=1628137690394493&mt=1641624286&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5411222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgQ77ri19I99jYKQOjRH7rnxdrUOhQKsywtIA0sNATkmMCIGhQWGFvUhBxn0a3K_8G-PT3MzQO_X0lrzhibRxH0tz0&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIge4RqnJ6P4wDSVNnJP_GOUofaVe5pKNj46HYCYknZ5mACIQDHvQXWNiGPC18j-Nsj9zG7fOQIg2FcUNzOjYUYsbKF8w%3D%3D"
[download] Destination: 2020 LG OLED l  The Black 4K HDR 60fps [njX2bu-_Vw4].f337.webm
[download]  51.2% of 419.65MiB at 14.50MiB/s ETA 00:14ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2973, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2701, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 119, in establish_connection
    raise err
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 113, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3458, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/utils.py", line 1392, in https_open
    return self.do_open(functools.partial(
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>
```

**Comment by pukkandan** [comment]
Try adding `-4` to the command and let us know if it helps. If not, also try using a VPN. It is likely the issue is with your local CDN
