### ISSUE TITLE
ERROR: 'int' object has no attribute 'get' when downloading free videos from tvp

### ISSUE THREAD

**Issue by Pretzelek** [yt-dlp/yt-dlp#2263]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Description

When downloading video which does not require logging in, error appears.

E:\YT>yt-dlp.exe "https://vod.tvp.pl/video/kolo-fortuny,odc-1182,57420860"
[tvp] 57420860: Downloading webpage
[tvp:embed] 57420860: Downloading webpage
ERROR: 'int' object has no attribute 'get'

### Verbose log

```shell
E:\YT>yt-dlp.exe -Uv "https://vod.tvp.pl/video/kolo-fortuny,odc-1182,57420860"
[debug] Command-line config: ['-Uv', 'https://vod.tvp.pl/video/kolo-fortuny,odc-1182,57420860']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [tvp] Extracting URL: https://vod.tvp.pl/video/kolo-fortuny,odc-1182,57420860
[tvp] 57420860: Downloading webpage
[debug] [tvp:embed] Extracting URL: tvp:57420860
[tvp:embed] 57420860: Downloading webpage
ERROR: 'int' object has no attribute 'get'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\tvp.py", line 402, in _real_extract
AttributeError: 'int' object has no attribute 'get'
```

**Comment by dirkf** [comment]
WFM from the UK, although I don't believe the ABR:
```
[info] Available formats for 57420860:
ID     EXT RESOLUTION │      TBR PROTO │ VCODEC       VBR ACODEC  ABR
──────────────────────────────────────────────────────────────────────
direct mp4 unknown    │ 1750000k https │ unknown 1750000k unknown  0k
```
The extractor doesn't seem to have changed for several months, but apparently in the posted log the `quality` at l.397 was an `int` and not a `dict`. Maybe the site is sending either a JSON object with members `fps`, `bitrate`, `width`, `height`, or just some number like the `height`, depending some unknown. Until someone works out what that number might be, the existing `file.get('quality', {})` could become `try_get(file, lambda x: x['quality'], dict) or {}` to avoid the crash in the posted log.

**Comment by dirkf** [comment]
Problem URL gone `ERROR: [tvp:vod] 334780: Woronicza said: ITEM_NOT_AVAILABLE (HTTP 404)`

**Comment by Pretzelek** [comment]
True, looks like that video has been removed somewhere in the past three years.

Currently, downloading on this site works, however a lot content on this site became DRM protected. That's a whole different problem; I guess this issue can be closed.

**Comment by bashonly** [comment]
Fixed by 728f4b5c2ef914f3b45d160883469502366d8eac
