### ISSUE TITLE
facebook Nonetype object has no attribute get

### ISSUE THREAD

**Issue by wankio** [yt-dlp/yt-dlp#2264]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

 private group, i'm used to download those video with cookies but in this week i can't download any videos in private group

use` --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"` still get, both youtube-dl and yt-dlp have problem
```
[facebook] 4743714749016405: Downloading webpage
ERROR: 'NoneType' object has no attribute 'get'
```

youtube-dl
```
[facebook] 4743714749016405: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyc", line 475, in main
  File "youtube_dl\__init__.pyc", line 465, in _real_main
  File "youtube_dl\YoutubeDL.pyc", line 2068, in download
  File "youtube_dl\YoutubeDL.pyc", line 808, in extract_info
  File "youtube_dl\YoutubeDL.pyc", line 815, in wrapper
  File "youtube_dl\YoutubeDL.pyc", line 836, in __extract_info
  File "youtube_dl\extractor\common.pyc", line 534, in extract
  File "youtube_dl\extractor\facebook.pyc", line 680, in _real_extract
  File "youtube_dl\extractor\facebook.pyc", line 499, in _extract_from_url
  File "youtube_dl\extractor\facebook.pyc", line 480, in parse_attachment
AttributeError: 'NoneType' object has no attribute 'get'
```

even public group is not working
yt-dlp https://www.facebook.com/rhyan.fernandez.1/videos/893150181367366

### Verbose log

```shell
[debug] Command-line config: ['https://www.facebook.com/rhyan.fernandez.1/videos/893150181367366/', '--verbose']
[debug] User config file: C:\Users\GEN32UC\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['-o', 'I:/youtube-dl/%(extractor)s/%(title)s-%(uploader)s-%(channel_id)s-%(channel)s-%(id)s.%(ext)s', '-f', 'bestvideo[height<=?1080]+bestaudio/best', '--write-thumbnail', '--cookies', 'C:/Users/GEN32UC/AppData/Roaming/youtube-dl/cookies.txt', '--write-sub', '--write-auto-sub', '--sub-lang', 'en-GB']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.8.2 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-92966-gd52a1be4e3, ffprobe N-92966-gd52a1be4e3
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/rhyan.fernandez.1/videos/893150181367366/
[facebook] 893150181367366: Downloading webpage
[facebook] 893150181367366: Downloading webpage
ERROR: [facebook] 893150181367366: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\facebook.py", line 721, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "c:\users\gen32uc\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\facebook.py", line 667, in _extract_from_url
    raise ExtractorError('Cannot parse data')
```

**Comment by doxatotheo** [comment]
I have a similar error specificly with Facebook in the same context (public or private). Perhaps due to the way the video is shared by the guy ? :
*** Using yt-dlp :**
`yt-dlp https://www.facebook.com/groups/dossiersfrancereinfo/permalink/1434142093648577
[facebook] 1434142093648577: Downloading webpage
[facebook] 1434142093648577: Downloading webpage
ERROR: [facebook] 1434142093648577: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.`

***Using youtube-dl :**
youtube-dl https://www.facebook.com/groups/dossiersfrancereinfo/permalink/1434142093648577
[facebook] 1434142093648577: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2068, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 680, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 499, in _extract_from_url
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 480, in parse_attachment
AttributeError: 'NoneType' object has no attribute 'get'
