### ISSUE TITLE
Unable to Download Patreon Videos

### ISSUE THREAD

**Issue by Mysterio3002** [yt-dlp/yt-dlp#2277]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Tried to download a Patreon video that's uploaded straight to the site, ones I've downloaded before were embedded into the site with Vimeo but this one is fully uploaded to Patreon, and it just refuses to download.

### Verbose log

```shell
G:\Cold Ones>"D:\New folder\Files\youtube-dl\yt-dlp.exe" -vU --cookies patreon.com_cookies.txt https://www.patreon.com/posts/we-were-tricked-59857679
[debug] Command-line config: ['-vU', '--cookies', 'patreon.com_cookies.txt', 'https://www.patreon.com/posts/we-were-tricked-59857679']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [Patreon] Extracting URL: https://www.patreon.com/posts/we-were-tricked-59857679
[Patreon] 59857679: Downloading JSON metadata
WARNING: "url" field is missing or empty - skipping format, there is an error in extractor
[debug] Default format spec: best/bestvideo+bestaudio
ERROR: [Patreon] 59857679: Requested format is not available
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1489, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2535, in process_video_result
yt_dlp.utils.ExtractorError: [Patreon] 59857679: Requested format is not available
```

**Comment by github-userx** [comment]
Just curious can VideoDownloadHelper Firefox Addon detect/download it? Or is it DRM protected by Patreon?

**Comment by Mysterio3002** [comment]
> Just curious can VideoDownloadHelper Firefox Addon detect/download it? Or is it DRM protected by Patreon?

Yes, that works :)

**Comment by davidchalifoux** [comment]
I'm experiencing the same error.
When did Patreon roll out their own video hosting?

**Comment by LoaneShark** [comment]
Experiencing an "Error 403: Forbidden" when trying to parse site metadata on Patreon, also specifically for embedded videos in patreon feeds. I'm a subscriber and have proper access allegedly (gallery-dl is able to parse the posts and download thumbnail images for the same users/posts successfully with the same cookies). I'm on the latest version of yt-dlp as well.

```
C:\Videos>yt-dlp --cookies-from-browser firefox "https://www.patreon.com/XXX/posts" -v
[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://www.patreon.com/XXX/posts', '-v']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\temp\AppData\Roaming\Mozilla\Firefox\Profiles\xsw24k31.default-1572046729019\cookies.sqlite"
[Cookies] Extracted 1113 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.8.6 (CPython 64bit) - Windows-8.1-6.3.9600-SP0
[debug] exe versions: none
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [PatreonUser] Extracting URL: https://www.patreon.com/XXX/posts
[PatreonUser] XXX: Downloading webpage
ERROR: [PatreonUser] XXX: Unable to download webpage: HTTP Error 403: Forbidden
(caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\patreon.py", line 240, in _real_extract
    webpage = self._download_webpage(url, user_id, headers={'Cookie': '.'})
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\common.py", line 900, in _download_webpage
    res = self._download_webpage_handle(
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\common.py", line 753, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\common.py", line 735, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 3591, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\temp\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
(XXX is a placeholder, this happens with any patreon creator)

**Comment by ofifoto** [comment]
Seeing the same issue here, with a creator that produces mainly audio content

**Comment by LoaneShark** [comment]
To update, this doesn't happen if I provide a direct link to a single post with an embedded video; it will parse and download that correctly if I provide each page individually. The above problem only happens if I try to download an entire page or feed of posts.
