### ISSUE TITLE
Suddenly I got this error "Unable to extract json_string"

### ISSUE THREAD

**Issue by divsbhalala** [yt-dlp/yt-dlp#2287]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

This works perfectly over the weekend. Now, when attempting to access any tiktok video I'm receiving the "unable to extract json_string" error. I had a friend try this from their location as well and received the same error response, so this does not appear to be a block on my end by tiktok.

### Verbose log

```shell
LC_ALL=en_US.UTF-8 yt-dlp --no-continue --no-cache-dir --verbose -o "./upload/Test_1641793190465_02.mp4" "https://www.tiktok.com/@repurpose_test/video/7031212954733268230"


[debug] Command-line config: ['--no-continue', '--no-cache-dir', '--verbose', '-o', './upload/Test_1641793190465_02.mp4', 'https://www.tiktok.com/@repurpose_test/video/7031212954733268230']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.10.10 (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.2.2-0york0, ffprobe 4.2.2-0york0
[debug] Optional libraries: sqlite
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@repurpose_test/video/7031212954733268230
[TikTok] 7031212954733268230: Downloading video details
WARNING: [TikTok] 7031212954733268230: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage
[TikTok] 7031212954733268230: Downloading webpage
[TikTok] 7031212954733268230: Downloading video webpage
ERROR: [TikTok] 7031212954733268230: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 589, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/tiktok.py", line 358, in _real_extract
    webpage, 'json_string', group='json_string_ld')
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1150, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 589, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/tiktok.py", line 358, in _real_extract
    webpage, 'json_string', group='json_string_ld')
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1150, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1263, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1288, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 606, in extract
    e.msg, video_id=video_id, ie=self.IE_NAME, tb=e.traceback, expected=e.expected, cause=e.cause)
yt_dlp.utils.ExtractorError: [TikTok] 7031212954733268230: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by MinePlayersPE** [comment]
Quote from @pukkandan:
> Duplicate of #2282, #2282, #2250, #2250, #2246, #2246, #2243, #2183, #2183, #2165, #2159, #2159, #2150, #2150, #2135, #2133( and now #2286)
> 
> Is it so hard to search before opening an issue!!
