### ISSUE TITLE
PlutoTV live channels support

### ISSUE THREAD

**Issue by rgabbo** [yt-dlp/yt-dlp#2301]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Example URLs

https://pluto.tv/it/live-tv/pluto-tv-film-it
https://pluto.tv/it/live-tv/pluto-tv-film-azione-it

### Description

While VOD is supported, live channels are not supported yet.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://pluto.tv/it/live-tv/il-banco-dei-pugni-it']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://pluto.tv/it/live-tv/il-banco-dei-pugni-it
[generic] il-banco-dei-pugni-it: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] il-banco-dei-pugni-it: Downloading webpage
[generic] il-banco-dei-pugni-it: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://pluto.tv/it/live-tv/il-banco-dei-pugni-it
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3829, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://pluto.tv/it/live-tv/il-banco-dei-pugni-it
```

**Comment by meshstyles** [comment]
theoretically this shouldn't be too hard if ffmpeg is used, i recently added it to one of my download bash scripts.

for anyone who is capable to write python code looking at the start.json at `.EPG[0].stitched.path` would be were the live master stream lives

but the thing is sorta actually live and ideally functionality would be added to detect video playing is also available as on demand so one would actually obtain the full content for archival purposes.
