### ISSUE TITLE
--trim-filenames fails to clip file name properly when there is a dot in a video title

### ISSUE THREAD

**Issue by letalvoj** [yt-dlp/yt-dlp#2314]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

This procedure:
https://github.com/yt-dlp/yt-dlp/blob/e04938ab88fc1fb4560f6cceb32525ef6e7f47a4/yt_dlp/YoutubeDL.py#L1221-L1225

Assumes that there is at most 2 extensions appended to the current filename. This fails when there is a dot in a video title. Yeah, that happens.

*Proposed fixes*
a. assuming there is only one extension => using `os.path.splitext()` to split the filename before trimming
b. trimming the file name _before_ appending the ext.
  - might cause artefacts (trimming `foo-bar-foo.mp4` to 14 chars would produce `foo-bar-foo.mp.mp4`)
  
c. _let me know if you have some other idea_

I am happy to fix that, just let me know which (a-c) would the maintainers prefer.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--trim-filenames', '30', 'https://www.dvtv.cz/video/slavme-odchod-delty-a-prichod-omikronu-ockovat-se-kvuli-byrokracii-a-ne-kvuli-zdravi-je-ulet-rika-hostomsky']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://www.dvtv.cz/video/slavme-odchod-delty-a-prichod-omikronu-ockovat-se-kvuli-byrokracii-a-ne-kvuli-zdravi-je-ulet-rika-hostomsky
[generic] slavme-odchod-delty-a-prichod-omikronu-ockovat-se-kvuli-byrokracii-a-ne-kvuli-zdravi-je-ulet-rika-hostomsky: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] slavme-odchod-delty-a-prichod-omikronu-ockovat-se-kvuli-byrokracii-a-ne-kvuli-zdravi-je-ulet-rika-hostomsky: Downloading webpage
[generic] slavme-odchod-delty-a-prichod-omikronu-ockovat-se-kvuli-byrokracii-a-ne-kvuli-zdravi-je-ulet-rika-hostomsky: Extracting information
[debug] Looking for video embeds
[debug] Identified a HTML5 media
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Slavme odchod delty a příchod omikronu. Očkovat se kvůli byrokracii a ne kvůli zdraví je úlet, říká Hostomský | DVTV - první internetová televize
[generic] playlist Slavme odchod delty a příchod omikronu. Očkovat se kvůli byrokracii a ne kvůli zdraví je úlet, říká Hostomský | DVTV - první internetová televize: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo*+bestaudio/best
[info] slavme-odchod-delty-a-prichod-omikronu-ockovat-se-kvuli-byrokracii-a-ne-kvuli-zdravi-je-ulet-rika-hostomsky: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://www.dvtv.cz/uploads/videa-fotky/2022-01-10-dvtv-mr-hostomsky.mp3"
ERROR: unable to open for writing: [Errno 63] File name too long: 'Slavme odchod delty a příchod . Očkovat se kvůli byrokracii a ne kvůli zdraví je úlet, říká Hostomský _ DVTV - první internetová televize [slavme-odchod-delty-a-prichod-omikronu-ockovat-se-kvuli-byrokracii-a-ne-kvuli-zdravi-je-ulet-rika-hostomsky].mp3.part'
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 218, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/utils.py", line 557, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 63] File name too long: 'Slavme odchod delty a příchod . Očkovat se kvůli byrokracii a ne kvůli zdraví je úlet, říká Hostomský _ DVTV - první internetová televize [slavme-odchod-delty-a-prichod-omikronu-ockovat-se-kvuli-byrokracii-a-ne-kvuli-zdravi-je-ulet-rika-hostomsky].mp3.part'


[download] Finished downloading playlist: Slavme odchod delty a příchod omikronu. Očkovat se kvůli byrokracii a ne kvůli zdraví je úlet, říká Hostomský | DVTV - první internetová televize
```

**Comment by pukkandan** [comment]
I am aware of this issue 😓. The --trim-filename option is just overall poorly implemented, making this tricky to fix. I honestly suggest using something like `%(title).30s.%(ext)s` instead

**Comment by pukkandan** [comment]
Related: https://github.com/yt-dlp/yt-dlp/issues/1837

**Comment by letalvoj** [comment]
> I honestly suggest using something like `%(title).30s.%(ext)s` instead

Why does not it use the sanitized id too name the file. Like `%(id)s.%(ext)`? Or similar. I made a bash alias which includes the `-o` parameter by default such that I do not need to rename the files all the time.

**Comment by ssokolow** [comment]
A *lot* of Twitter videos fail to download because of this bug, since they use the contents of the tweet as the title.

**Comment by JoakimCh** [comment]
> I am aware of this issue sweat. The --trim-filename option is just overall poorly implemented, making this tricky to fix. I honestly suggest using something like `%(title).30s.%(ext)s` instead

Very nice, but does it also have a syntax to limit the byte-length of the string? Because if the string has several unicode characters then it will in my case often exceed the 255 bytes ext4 limit even if I make the maximum character length well below 255.

**Comment by pukkandan** [comment]
@JoakimCh Yes, and the answer is even pinned! https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195

**Comment by ssokolow** [comment]
@pukkandan Not in my experience. I find that, if I'm `yt-dlp`-ing videos off Twitter, I have to manually specify something like `200s` for latin tweets and something like `50s` for CJK tweets to minimize truncation while also avoiding getting a fatal error over the filename being too long.

I'd suggest a Python equivalent to how I implemented [this Rust tool](https://github.com/ssokolow/trunc_filenames/) I wrote to truncate filenames to within what rclone's filename encryption requires.

(Feel free to read the code and port the algorithm to Python without complying with the MIT license if it helps. I don't currently have time to contribute a fix to yt-dlp or I'd do so.)

**Comment by pukkandan** [comment]
> @pukkandan Not in my experience

What are you replying to?

**Comment by ssokolow** [comment]
@pukkandan This exchange:

> Very nice, but does it also have a syntax to limit the byte-length of the string? Because if the string has several unicode characters then it will in my case often exceed the 255 bytes ext4 limit even if I make the maximum character length well below 255.

>  @JoakimCh Yes, and the answer is even pinned! https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195

**Comment by pukkandan** [comment]
I suggest you read the discussion under the linked comment.

This issue is about the bug in `--trim-filenames`, and there's not a single on-topic comment here! I'm locking the issue.

For reference, here's a potential solution for the actual issue https://github.com/yt-dlp/yt-dlp/issues/5526#issuecomment-1312783517
