### ISSUE TITLE
Request to add The Roku Channel

### ISSUE THREAD

**Issue by mstrswrd06** [yt-dlp/yt-dlp#2326]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

Single video (Movie): https://therokuchannel.roku.com/watch/04b6c521c7175303aeade7bd01ed15aa
Single video (Movie): https://therokuchannel.roku.com/watch/597a64a4a25c5bf6af4a8c7053049a6f
Single video (TV): https://therokuchannel.roku.com/watch/d9106b15cab25a2c80804d64f6dc33e4

### Description

Roku is a brand of hardware digital media players manufactured by American company Roku, Inc. They offer access to streaming media content from various online services, including their own streaming service "The Roku Channel" which allows content streaming from its own offerings free of charge (with ads). Neither youtube-dl or yt-dlp supports fetching content from The Roku Channel as of this writing.

### Verbose log

```shell
C:\Users\myusername\Desktop\youtube-dl>yt-dlp -Uv -F https://therokuchannel.roku.com/watch/597a64a4a25c5bf6af4a8c7053049a6f
[debug] Command-line config: ['-Uv', '-F', 'https://therokuchannel.roku.com/watch/597a64a4a25c5bf6af4a8c7053049a6f']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://therokuchannel.roku.com/watch/597a64a4a25c5bf6af4a8c7053049a6f
[generic] 597a64a4a25c5bf6af4a8c7053049a6f: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 597a64a4a25c5bf6af4a8c7053049a6f: Downloading webpage
[generic] 597a64a4a25c5bf6af4a8c7053049a6f: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://therokuchannel.roku.com/watch/597a64a4a25c5bf6af4a8c7053049a6f
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3829, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://therokuchannel.roku.com/watch/597a64a4a25c5bf6af4a8c7053049a6f
```

**Comment by nyuszika7h** [comment]
This site uses Widevine DRM.

**Comment by wxolp** [comment]
Issue should be reopened, not all items require DRM:

https://therokuchannel.roku.com/watch/105c41ea75775968b670fbb26978ed76

**Comment by pukkandan** [comment]
Can confirm

**Comment by MacarioPatrick** [comment]
@pukkandan Why re-open if the website uses DRM?

**Comment by pukkandan** [comment]
> Issue should be reopened, not all items require DRM:
> https://therokuchannel.roku.com/watch/105c41ea75775968b670fbb26978ed76

by @wxolp - message was deleted by them

**Comment by Sipherdrakon** [comment]
100% correct, there is still a lot of content that is not DRM protected on the site, don't assume because you found a hand-full of examples that use DRM and say all items are DRM so let's move on.

Example: https://therokuchannel.roku.com/watch/a9474f67937c5986aa1ac0747f5bb615

**Comment by dirkf** [comment]
Is there content on TRC that is not at (`smeAs` in the ld+json) https://www.youtube.com/roku ?

**Comment by xFaultx** [comment]
https://github.com/yt-dlp/yt-dlp/issues/9935#issuecomment-2408582820

I reported this issue yesterday and it got closed, this thread someone has updated it a few months ago and got it working again

**Comment by bashonly** [comment]
CWTV is completely unrelated to the Roku channel

**Comment by xFaultx** [comment]
Your right sorry, just copied the previous thread email. I think I'm
conflating two separate issues I was having around the same time. It's just
weird because I did have the Roku channel working only a few months ago for
videos from the same show
