### ISSUE TITLE
add support : learn.justdjango.com

### ISSUE THREAD

**Issue by Ex-Communicad0** [yt-dlp/yt-dlp#2327]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

https://learn.justdjango.com/courses/django-ecommerce/
https://learn.justdjango.com/courses/django-ecommerce/project-setup

### Description

please add support for this site/url

it provides playlist video 

video hosted on vimeo

### Verbose log

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-Uv', 'https://learn.justdjango.com/courses/django-ecommerce/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.24 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-102564-g2261cc6d8a, ffprobe N-102564-g2261cc6d8a
[debug] Proxy map: {}
Current Build Hash 917f7ada880ca33728e445567e6ae96022cd2ffa22cd7befe1f80e0a7fb3bbf7
Updating to version 2021.12.27 ...
Updated yt-dlp to version 2021.12.27
ERROR: The program must exit for the update to complete
```

**Comment by pukkandan** [comment]
Try passing cookies

**Comment by Ex-Communicad0** [comment]
how to share cookies? can you please provide any email

> Try passing cookies (and show its verbose)

**Comment by pukkandan** [comment]
I meant, pass cookies to yt-dlp, not to share with us


    --cookies FILE                   Netscape formatted file to read cookies
                                     from and dump cookie jar in
    --cookies-from-browser BROWSER[+KEYRING][:PROFILE]
                                     The name of the browser and (optionally)
                                     the name/path of the profile to load
                                     cookies from, separated by a ":". Currently
                                     supported browsers are: brave, chrome,
                                     chromium, edge, firefox, opera, safari,
                                     vivaldi. ...

**Comment by Ex-Communicad0** [comment]
> [debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-Uv', '--cookies', "'justdjango_cookies.txt'", 'https://learn.justdjango.com/courses/django-crash-course/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-102564-g2261cc6d8a (setts), ffprobe N-102564-g2261cc6d8a
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://learn.justdjango.com/courses/django-crash-course/
[generic] django-crash-course: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] django-crash-course: Downloading webpage
[generic] django-crash-course: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://learn.justdjango.com/courses/django-crash-course/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3829, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://learn.justdjango.com/courses/django-crash-course/

Here is the output

**Comment by Ashish0804** [comment]
@Ex-Communicad0 I can't guarantee that I will be able to add this but if u want me to take a look then fell free to email me the details.
`Ashish08@protonmail.com`
