### ISSUE TITLE
--fragment-retries does nothing

### ISSUE THREAD

**Issue by Silejonu** [yt-dlp/yt-dlp#2347]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Setting --fragment-retries infinite or --fragment-retries 100 for instance does nothing, and yt-dlp always retries the default amount of times (10).

### Verbose log

```shell
yt-dlp -Uv https://www.youtube.com/watch?v=q-1cNj4TxeE -f 248+251 --fragment-retries infinite
[debug] Command-line config: ['-Uv', 'https://www.youtube.com/watch?v=q-1cNj4TxeE', '-f', '248+251', '--fragment-retries', 'infinite']
[debug] System config file: /etc/yt-dlp.conf
[debug] System config: ['--sub-langs', 'all,-live_chat', '--embed-subs', '--merge-output-format', 'mkv', '--output=~/Downloads/%(title).245s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.16.0-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=q-1cNj4TxeE
[youtube] q-1cNj4TxeE: Downloading webpage
[youtube] q-1cNj4TxeE: Downloading android player API JSON
[youtube] q-1cNj4TxeE: Downloading MPD manifest
[youtube] q-1cNj4TxeE: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en
[info] q-1cNj4TxeE: Downloading 1 format(s): 248+251
[info] Writing video subtitles to: /home/silejonu/Downloads/Apprendre à choper - Le Myriapode S1E10.en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=q-1cNj4TxeE&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xoaf=4&hl=en&ip=0.0.0.0&ipbits=0&expire=1642271934&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=44B419242F096B4CCFBAB33F50DA9241C7C7971B.64144C2DC03E0C900928AEF413A4C22C3017CAA1&key=yt8&lang=en&fmt=vtt"
[download] Destination: /home/silejonu/Downloads/Apprendre à choper - Le Myriapode S1E10.en.vtt
[download] 100% of 4.58KiB in 00:00
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1642268334/ei/TrLiYfTuHKSuxN8PgsmhkAM/ip/2a01%3Acb19%3A8f39%3A4f00%3A7452%3Ad07d%3Ad04e%3Aedb6/id/abed5c363e13c5e1/source/youtube/requiressl/yes/playback_host/rr3---sn-25ge7nzs.googlevideo.com/mh/xb/mm/31%2C29/mn/sn-25ge7nzs%2Csn-25glene7/ms/au%2Crdu/mv/m/mvi/3/pl/38/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1012500/vprv/1/mt/1642246390/fvip/3/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRgIhAImNHJAmi41cuEz_qmY69MTr_cCIfHHkZPGrvomhNER4AiEA54VpkgymX99bNMNAP6aCdyjJpYdR6Vi1Ia1RiIqOM1E%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgPIlSo3lNsBnvxdKbus7bqHYVGsVjnpzIWgPttoziFNMCIEfXNsRdLgoY8NDxT7I5inw-Ys-hQ6epCO1LkZcS6Mla"
[dashsegments] Total fragments: 48
[download] Destination: /home/silejonu/Downloads/Apprendre à choper - Le Myriapode S1E10.f248.webm
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10) ...
ERROR: giving up after 10 retries
  File "/usr/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2021.12.27', 'console_scripts', 'yt-dlp')())
  File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 842, in main
    _real_main(argv)
  File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 832, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3113, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3086, in wrapper
    res = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1344, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1437, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1489, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2551, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2973, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2701, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/dash.py", line 56, in real_download
    return self.download_and_append_fragments_multiple(*args)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 382, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], pack_func=pack_func, finish_func=finish_func)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 515, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 449, in download_fragment
    success, frag_content = self._download_fragment(ctx, fragment['url'], info_dict, headers)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 133, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 385, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 177, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 912, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 842, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: unable to download video data: [Errno 2] No such file or directory: '/home/silejonu/Downloads/Apprendre à choper - Le Myriapode S1E10.f248.webm.part-Frag1'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2973, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2701, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/dash.py", line 56, in real_download
    return self.download_and_append_fragments_multiple(*args)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 382, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], pack_func=pack_func, finish_func=finish_func)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 515, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 449, in download_fragment
    success, frag_content = self._download_fragment(ctx, fragment['url'], info_dict, headers)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 139, in _download_fragment
    return True, self._read_fragment(ctx)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 142, in _read_fragment
    down, frag_sanitized = self.sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 218, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 557, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/silejonu/Downloads/Apprendre à choper - Le Myriapode S1E10.f248.webm.part-Frag1'
```

**Comment by Jules-A** [comment]
It's not failing on the fragments, it's failing on the connection in general so you want ```-R, --retries RETRIES            Number of retries (default is 10), or
                                 "infinite"``` instead.

**Comment by Silejonu** [comment]
> It's not failing on the fragments, it's failing on the connection in general so you want `-R, --retries RETRIES Number of retries (default is 10), or "infinite"` instead.

My bad, thank you!
This same exact video has been failing on fragments for weeks, so I assumed it was still the case.

**Comment by mhadidg** [comment]
A combination of a `while` loop with `--continue` flag did the trick for me:

```
$ while ! yt-dlp (...) --continue; do sleep 1; done
```
