### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by atom-smasher** [yt-dlp/yt-dlp#2391]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

yt-dlp exits with return code 1 and message:
`ERROR: unable to download video data: HTTP Error 400: Bad Request`

Running:
`yt-dlp  -Uv https://youtu.be/bc53aHWi3bU`

I've tried a few different ways of specifying different formats and qualities, but the outcome is essentially the same.

Other videos from that site are working as expected, and this video is playing fine in a browser at different qualities.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://youtu.be/bc53aHWi3bU']
[debug] User config file: /home/atom/.config/yt-dlp/config
[debug] User config: ['-o', '%(title)s-%(id)s-%(height)sp.%(ext)s', '--restrict-filenames', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36', '-f', 'bestvideo[height<=?1080]+bestaudio/best']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-94-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Crypto, secretstorage, mutagen, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [youtube] Extracting URL: https://youtu.be/bc53aHWi3bU
[youtube] bc53aHWi3bU: Downloading webpage
[youtube] bc53aHWi3bU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] bc53aHWi3bU: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr1---sn-uo1-fabl.googlevideo.com/videoplayback?expire=1642605829&ei=pdjnYer0IPaA9fwPt_Gw-A0&ip=122.58.94.63&id=o-APYE1TT5N9TlNydwAMiS-_l4zlQnUrwX5t_cuUbBmrsy&itag=248&source=youtube&requiressl=yes&mh=ZZ&mm=31%2C29&mn=sn-uo1-fabl%2Csn-ntqe6nez&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=23&initcwndbps=1272500&vprv=1&mime=video%2Fwebm&gir=yes&clen=73774592&dur=1767.760&lmt=1642562828992737&mt=1642583812&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgRNa0K537e_zeWOV1NiTfhCGzMDLGnMJHzf6CPkAEH8ACIFpuGVrNKWytqlglBYJ0LDMbfnWsYKr0TTOKTHDLhL4Q&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAI-dQzhzNoMhNy48g5IlHD27dY953qaXGqtVk1CIKiN9AiB0bGZwvII4kFLMz70uMcpnhUKgpLGVM34HcO1O00M1vQ%3D%3D"
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/home/atom/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2973, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/atom/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2701, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/atom/bin/yt-dlp/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/home/atom/bin/yt-dlp/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/home/atom/bin/yt-dlp/yt_dlp/downloader/http.py", line 119, in establish_connection
    raise err
  File "/home/atom/bin/yt-dlp/yt_dlp/downloader/http.py", line 113, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/atom/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3458, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by pukkandan** [comment]
```
➤ yt-dlp -v https://youtu.be/bc53aHWi3bU
[debug] Command-line config: ['-v', 'https://youtu.be/bc53aHWi3bU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 6ea4d15a3
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg n5.0-1-ga66b58d61c-20220116 (fdk,setts), ffprobe n5.0-1-ga66b58d61c-20220116, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://youtu.be/bc53aHWi3bU
[youtube] bc53aHWi3bU: Downloading webpage
[youtube] bc53aHWi3bU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] bc53aHWi3bU: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr8---sn-gwpa-cagk.googlevideo.com/videoplayback?expire=1642608313&ei=WeLnYcnWGsWBjuMPmoK68A8&ip=49.37.182.54&id=o-AOP9hwQLy1mXgUeLKvolIGA1Zu4FmM0ErRJ_huGXdGWg&itag=248&source=youtube&requiressl=yes&mh=ZZ&mm=31%2C29&mn=sn-gwpa-cagk%2Csn-gwpa-h55r&ms=au%2Crdu&mv=m&mvi=8&pl=20&initcwndbps=315000&vprv=1&mime=video%2Fwebm&gir=yes&clen=73774592&dur=1767.760&lmt=1642562828992737&mt=1642586228&fvip=8&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAM83fDesyfwIsYoB15WjHMm2Gknyrmdn8P1NDoBhINm5AiEAsaNEiD4f0GVYthoVI9lGXbPi8CnZDlQFf48rjQa1Lpc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZScOSVjbEck1YouOPi8CHoOd98p8SpyWLCw4m1rVSgsCIE22vn9AQZDT58FJpujPtuZMiJFUin0i4snnwmpcfl20"
[download] Resuming download at byte 2096128
[download] Destination: Silver Price Prediction 2022 - David Morgan [bc53aHWi3bU].f248.webm
[download] 100% of 70.36MiB in 00:20
[debug] Invoking downloader on "https://rr8---sn-gwpa-cagk.googlevideo.com/videoplayback?expire=1642608313&ei=WeLnYcnWGsWBjuMPmoK68A8&ip=49.37.182.54&id=o-AOP9hwQLy1mXgUeLKvolIGA1Zu4FmM0ErRJ_huGXdGWg&itag=251&source=youtube&requiressl=yes&mh=ZZ&mm=31%2C29&mn=sn-gwpa-cagk%2Csn-gwpa-h55r&ms=au%2Crdu&mv=m&mvi=8&pl=20&initcwndbps=315000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=23178509&dur=1767.781&lmt=1642561419465495&mt=1642586228&fvip=8&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOlrPCkXcev6mRnCovcIEWeR5d2KndmoCJKvOqhavlfHAiALVP3g7KaexTUcLMsc5hLlB9BZJ-A4Eka2gshhQPDhBw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZScOSVjbEck1YouOPi8CHoOd98p8SpyWLCw4m1rVSgsCIE22vn9AQZDT58FJpujPtuZMiJFUin0i4snnwmpcfl20"
[download] Destination: Silver Price Prediction 2022 - David Morgan [bc53aHWi3bU].f251.webm
[download] 100% of 22.10MiB in 00:07
[Merger] Merging formats into "Silver Price Prediction 2022 - David Morgan [bc53aHWi3bU].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Silver Price Prediction 2022 - David Morgan [bc53aHWi3bU].f248.webm" -i "file:Silver Price Prediction 2022 - David Morgan [bc53aHWi3bU].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Silver Price Prediction 2022 - David Morgan [bc53aHWi3bU].temp.webm"
Deleting original file Silver Price Prediction 2022 - David Morgan [bc53aHWi3bU].f248.webm (pass -k to keep)
Deleting original file Silver Price Prediction 2022 - David Morgan [bc53aHWi3bU].f251.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
Can you try from a VPN/different network?

**Comment by atom-smasher** [comment]
A few hours later, and it's working fine.

I don't know.

**Comment by pukkandan** [comment]
Was probably a youtube side issue then
