### ISSUE TITLE
idollive

### ISSUE THREAD

**Issue by shimiaoyerin** [yt-dlp/yt-dlp#2429]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

South Korea

### Example URLs

Single:https://idollive.tv/watch?id=M0121CN063PPV00
Playlist:https://idollive.tv/category?id=C000258340

### Description

Restricted access to South Korea

### Verbose log

```shell
C:\Users\yerin>yt-dlp https://idollive.tv/watch?id=M0121CN063PPV00 --verbose
[debug] Command-line config: ['https://idollive.tv/watch?id=M0121CN063PPV00', '--verbose']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg n4.4-177-gc989427c16-20211008 (setts), ffprobe n4.4-177-gc989427c16-20211008
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'https': 'http://127.0.0.1:10081', 'http': 'http://127.0.0.1:10081'}
[debug] [generic] Extracting URL: https://idollive.tv/watch?id=M0121CN063PPV00
[generic] watch?id=M0121CN063PPV00: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] watch?id=M0121CN063PPV00: Downloading webpage
[generic] watch?id=M0121CN063PPV00: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://idollive.tv/watch?id=M0121CN063PPV00
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3966, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://idollive.tv/watch?id=M0121CN063PPV00
```

**Comment by trassshhub** [comment]
I have looked at the site, videos and playlist info can be extracted through an api. However I need some guidance before working on an extractor for it:
1. There are videos that can only be accessed from their app, how should this kind of error be handled?
2. Some videos have a main video and multiple secondary videos (user selectable angles), should this be treated as a playlist with multiple videos?

**Comment by pukkandan** [comment]
> There are videos that can only be accessed from their app, how should this kind of error be handled?

`raise ExtractorError(..., expected=True)`

> Some videos have a main video and multiple secondary videos (user selectable angles), should this be treated as a playlist with multiple videos?

Assuming they don't have separate URLs, that makes sense. Only the main video should be downloaded when providing `--no-playlist`

**Comment by trassshhub** [comment]
What title shall i give for the secondary videos?
main_title - singer_name?

I downloaded a sample of the secondary video and it is rotated 90 degrees, does this need to be processed?

**Comment by pukkandan** [comment]
is it also rotated in the website? Either way, I doubt there is anything we can do (without re-encoding)

**Comment by pukkandan** [comment]
> What title shall i give for the secondary videos?
> main_title - singer_name?

I dont use the site and so don't know the context. Use what you think is appropriate

**Comment by trassshhub** [comment]
I think I might hold off continuing on this extractor, just found that the main-secondary json is more complex than I expected.
Currently don't have time to investigate further.

Here are the links I found for whoever would like to take this up.
main video api: https://api.idollive.tv/web/vod/content/detail?albumId=[ID]
secondary video api: https://api.idollive.tv/web/vod/content/cuesheet?albumId=[ID]
playlist api: https://api.idollive.tv/web/vod/content/hotvod?categoryId=[ID]&page=[PageNumber]&pageCount=50

**Comment by shimiaoyerin** [comment]
> I have looked at the site, videos and playlist info can be extracted through an api. However I need some guidance before working on an extractor for it:
> 
> 1. There are videos that can only be accessed from their app, how should this kind of error be handled?
> 2. Some videos have a main video and multiple secondary videos (user selectable angles), should this be treated as a playlist with multiple videos?

He belongs to an APP called "u+idol". This APP can only be used in the Korean region in the Google App Store. This link belongs to the official website. I suspect that the website indexes the links in the APP.
1: For the main video and auxiliary video, there is indeed a main video, and then each individual member has a video, so the naming should be based on the member's name
2: The auxiliary video is generally rotated by 90 degrees, and the video rotated by 90 degrees does not need to be processed, because it is the full-body video of the singer.

In fact, I have always wanted to collect their videos, just because they were exclusive to the APP before and not online on the website. I also tried to grab the APP link before, but it seems to be encrypted.

**Comment by shimiaoyerin** [comment]
> I have looked at the site, videos and playlist info can be extracted through an api. However I need some guidance before working on an extractor for it:
> 
> 1. There are videos that can only be accessed from their app, how should this kind of error be handled?
> 2. Some videos have a main video and multiple secondary videos (user selectable angles), should this be treated as a playlist with multiple videos?

Some videos can only be viewed in the app. It is estimated that this is an official restriction. Before this official website did not plan to launch a web video service, and these contents are currently limited, that is, only the latest information is provided, and the past has not been launched.

**Comment by doe1080** [comment]
Service ended June 30, 2024
https://en.namu.wiki/w/%EC%95%84%EC%9D%B4%EB%8F%8C%ED%94%8C%EB%9F%AC%EC%8A%A4
https://play.google.com/store/apps/details?id=com.uplus.musicshow&hl=en
