### ISSUE TITLE
[RTnews] incorrect fields

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2464]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

worldwide

### Description

Thanks to Ashish0804, pukkandan and nixxo for the new extractor. Seems to work fine so far.

There seems to be a problem with some fields though:
- `playlist` or `playlist_title` is doubled: "The plot to assassinate Julian AssangeThe plot to assassinate Julian Assange"
- `title` is empty and/or gets is value from `id` instead

```log
[debug] Command-line config: ['https://www.rt.com/shows/in-question/535980-plot-to-assassinate-julian-assange', '-v']
[debug] Portable config "C:\hp\-\setups\+downloaders\yt-dlp\appdir\yt-dlp.conf": ['-o', '.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [RTNews] Extracting URL: https://www.rt.com/shows/in-question/535980-plot-to-assassinate-julian-assange
[RTNews] 535980: Downloading webpage
[download] Downloading playlist: The plot to assassinate Julian Assange
[RTNews] playlist The plot to assassinate Julian Assange: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 6152271d85f5400464496162: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://cdnv.rt.com/files/2021.09/6152271d85f5400464496162.mp4"
[download] Destination: The plot to assassinate Julian AssangeThe plot to assassinate Julian Assange\01 = #nodate# 6152271d85f5400464496162\6152271d85f5400464496162 [RTNews.RTNews.6152271d85f5400464496162] [0].mp4
[download]   2.3% of 227.19MiB at 236.00KiB/s ETA 16:02
```

Something seems to be amiss, because I cannot print the field names:

```
yt-dlp https://www.rt.com/shows/in-question/535980-plot-to-assassinate-julian-assange --ignore-config --print "%(title)s"
ERROR: 'NoneType' object is not iterable

yt-dlp https://www.rt.com/shows/in-question/535980-plot-to-assassinate-julian-assange --ignore-config --print "%(playlist)s"
ERROR: 'NoneType' object is not iterable

yt-dlp https://www.rt.com/shows/in-question/535980-plot-to-assassinate-julian-assange --ignore-config --print "%(playlist_title)s"
ERROR: 'NoneType' object is not iterable
```

When I use my standard config file, I get this error:

```
[debug] Command-line config: ['https://www.rt.com/shows/in-question/535980-plot-to-assassinate-julian-assange/']
[debug] Portable config "C:\hp\-\setups\+downloaders\yt-dlp\appdir\yt-dlp.conf": ['--verbose', '--format-sort', 'hasvid,ie_pref,quality,res,hdr,codec,size,br,asr,ext,fps,hasaud,lang,source,proto,id', '-f', 'bestvideo*+bestaudio*/best', '--paths', 'c:\\Users\\User\\Downloads\\yt', '-o', '.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'thumbnail:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\thumbs\\thumb.%(ext)s', '-o', 'subtitle:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\subs\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'infojson:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\!nfo\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'link:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\!nfo\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'description:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\!nfo\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'annotation:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\!nfo\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'pl_infojson:.\\%(playlist|)s%(playlist_title|)s\\playlist.%(ext)s', '-o', 'pl_thumbnail:.\\%(playlist|)s%(playlist_title|)s\\folder.%(ext)s', '-o', 'pl_description:.\\%(playlist|)s%(playlist_title|)s\\playlist.%(ext)s', '--print', '----------------------------------------------------', '--print', 'title:                %(title)s', '--print', 'alt_title:            %(alt_title)s', '--print', 'playlist_index:       %(playlist_index)s', '--print', 'playlist_autonumber:  %(playlist_autonumber)s', '--print', 'webpage_url:          %(webpage_url)s', '--print', '', '--print', 'format_id:            %(format_id)s', '--print', 'format:               %(format)s', '--print', 'format_note:          %(format_note)s', '--print', '', '--print', 'duration:             %(duration>%H:%M:%S)s', '--print', 'release_date:         %(release_date>%Y-%m-%d)s', '--print', 'release_timestamp:    %(release_timestamp>%Y-%m-%d)s', '--print', 'upload_date:          %(upload_date>%Y-%m-%d)s', '--print', 'timestamp:            %(timestamp>%Y-%m-%d)s', '--print', 'epoch:                %(epoch>%Y-%m-%d)s', '--print', '', '--print', 'creator:              %(creator)s', '--print', '', '--print', 'playlist:             %(playlist)s', '--print', 'playlist_id:          %(playlist_id)s', '--print', 'playlist_title:       %(playlist_title)s', '--print', 'playlist_uploader:    %(playlist_uploader)s', '--print', 'playlist_uploader_id: %(playlist_uploader_id)s', '--print', '----------------------------------------------------', '--print', '', '--print', '', '--output-na-placeholder', '~~~', '--write-info-json', '--write-description', '--write-annotations', '--no-overwrites', '--no-post-overwrites', '--merge-output-format', 'mkv', '--remux-video', 'mkv', '--write-subs', '--write-auto-subs', '--all-subs', '--sub-langs', 'all', '--sub-format', 'all/ttml/vtt/best', '--write-thumbnail', '--write-all-thumbnails', '--add-metadata', '--embed-chapters', '--add-chapters', '--write-link', '--write-url-link', '--write-desktop-link', '--no-check-certificate', '--retries', 'infinite', '--geo-bypass', '--no-clean-infojson', '--write-comments', '--audio-multistreams', '--no-playlist']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [RTNews] Extracting URL: https://www.rt.com/shows/in-question/535980-plot-to-assassinate-julian-assange/
[RTNews] 535980: Downloading webpage
[download] Downloading playlist: The plot to assassinate Julian Assange
[RTNews] playlist The plot to assassinate Julian Assange: Downloading 1 videos
[download] Downloading video 1 of 1
[info] 6152271d85f5400464496162: Downloading 1 format(s): 0
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1789, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1503, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2589, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2803, in process_info
  File "yt_dlp\YoutubeDL.py", line 2721, in __forced_printings
  File "yt_dlp\YoutubeDL.py", line 2691, in _forceprint
  File "yt_dlp\YoutubeDL.py", line 3484, in render_thumbnails_table
TypeError: 'NoneType' object is not iterable

             ~~~
[download] Finished downloading playlist: The plot to assassinate Julian Assange
```

However, the very same config file does produce a nice print output for youtube links (or other extractors):

```
[debug] Command-line config: ['-v', '5qBjFZV19p0']
[debug] Portable config "C:\hp\-\setups\+downloaders\yt-dlp\appdir\yt-dlp.conf": ['--format-sort', 'hasvid,ie_pref,quality,res,hdr,codec,size,br,asr,ext,fps,hasaud,lang,source,proto,id', '-f', 'bestvideo*+bestaudio*/best', '--paths', 'c:\\Users\\User\\Downloads\\yt', '-o', '.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'thumbnail:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\thumbs\\thumb.%(ext)s', '-o', 'subtitle:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\subs\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'infojson:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\!nfo\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'link:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\!nfo\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'description:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\!nfo\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'annotation:.\\%(playlist|)s%(playlist_title|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(title)s\\!nfo\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'pl_infojson:.\\%(playlist|)s%(playlist_title|)s\\playlist.%(ext)s', '-o', 'pl_thumbnail:.\\%(playlist|)s%(playlist_title|)s\\folder.%(ext)s', '-o', 'pl_description:.\\%(playlist|)s%(playlist_title|)s\\playlist.%(ext)s', '--print', '----------------------------------------------------', '--print', 'title:                %(title)s', '--print', 'alt_title:            %(alt_title)s', '--print', 'playlist_index:       %(playlist_index)s', '--print', 'playlist_autonumber:  %(playlist_autonumber)s', '--print', 'webpage_url:          %(webpage_url)s', '--print', '', '--print', 'format_id:            %(format_id)s', '--print', 'format:               %(format)s', '--print', 'format_note:          %(format_note)s', '--print', '', '--print', 'duration:             %(duration>%H:%M:%S)s', '--print', 'release_date:         %(release_date>%Y-%m-%d)s', '--print', 'release_timestamp:    %(release_timestamp>%Y-%m-%d)s', '--print', 'upload_date:          %(upload_date>%Y-%m-%d)s', '--print', 'timestamp:            %(timestamp>%Y-%m-%d)s', '--print', 'epoch:                %(epoch>%Y-%m-%d)s', '--print', '', '--print', 'creator:              %(creator)s', '--print', '', '--print', 'playlist:             %(playlist)s', '--print', 'playlist_id:          %(playlist_id)s', '--print', 'playlist_title:       %(playlist_title)s', '--print', 'playlist_uploader:    %(playlist_uploader)s', '--print', 'playlist_uploader_id: %(playlist_uploader_id)s', '--print', '----------------------------------------------------', '--print', '', '--print', '', '--output-na-placeholder', '~~~', '--write-info-json', '--write-description', '--write-annotations', '--no-overwrites', '--no-post-overwrites', '--merge-output-format', 'mkv', '--remux-video', 'mkv', '--write-subs', '--write-auto-subs', '--all-subs', '--sub-langs', 'all', '--sub-format', 'all/ttml/vtt/best', '--write-thumbnail', '--write-all-thumbnails', '--add-metadata', '--embed-chapters', '--add-chapters', '--write-link', '--write-url-link', '--write-desktop-link', '--no-check-certificate', '--retries', 'infinite', '--geo-bypass', '--no-clean-infojson', '--write-comments', '--audio-multistreams', '--no-playlist']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: 5qBjFZV19p0
[youtube] 5qBjFZV19p0: Downloading webpage
[youtube] 5qBjFZV19p0: Downloading android player API JSON
[debug] Sort order given by user: hasvid, ie_pref, quality, res, hdr, codec, size, br, asr, ext, fps, hasaud, lang, source, proto, id
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, hdr, vcodec, acodec, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, fps, hasaud, lang, source, proto, id
[debug] Downloading subtitles: fr, pt, sr, es, af, sq, am, ar, hy, az, bn, eu, be, bs, bg, my, ca, ceb, zh-Hans, zh-Hant, co, hr, cs, da, nl, en, eo, et, fil, fi, gl, ka, de, el, gu, ht, ha, haw, iw, hi, hmn, hu, is, ig, id, ga, it, ja, jv, kn, kk, km, rw, ko, ku, ky, lo, la, lv, lt, lb, mk, mg, ms, ml, mt, mi, mr, mn, ne, no, ny, or, ps, fa, pl, pa, ro, ru, sm, gd, sn, sd, si, sk, sl, so, st, su, sw, sv, tg, ta, tt, te, th, tr, tk, uk, ur, ug, uz, vi, cy, fy, xh, yi, yo, zu, af-fr, sq-fr, am-fr, ar-fr, hy-fr, az-fr, bn-fr, eu-fr, be-fr, bs-fr, bg-fr, my-fr, ca-fr, ceb-fr, zh-Hans-fr, zh-Hant-fr, co-fr, hr-fr, cs-fr, da-fr, nl-fr, en-fr, eo-fr, et-fr, fil-fr, fi-fr, fr-fr, gl-fr, ka-fr, de-fr, el-fr, gu-fr, ht-fr, ha-fr, haw-fr, iw-fr, hi-fr, hmn-fr, hu-fr, is-fr, ig-fr, id-fr, ga-fr, it-fr, ja-fr, jv-fr, kn-fr, kk-fr, km-fr, rw-fr, ko-fr, ku-fr, ky-fr, lo-fr, la-fr, lv-fr, lt-fr, lb-fr, mk-fr, mg-fr, ms-fr, ml-fr, mt-fr, mi-fr, mr-fr, mn-fr, ne-fr, no-fr, ny-fr, or-fr, ps-fr, fa-fr, pl-fr, pt-fr, pa-fr, ro-fr, ru-fr, sm-fr, gd-fr, sr-fr, sn-fr, sd-fr, si-fr, sk-fr, sl-fr, so-fr, st-fr, es-fr, su-fr, sw-fr, sv-fr, tg-fr, ta-fr, tt-fr, te-fr, th-fr, tr-fr, tk-fr, uk-fr, ur-fr, ug-fr, uz-fr, vi-fr, cy-fr, fy-fr, xh-fr, yi-fr, yo-fr, zu-fr, af-pt, sq-pt, am-pt, ar-pt, hy-pt, az-pt, bn-pt, eu-pt, be-pt, bs-pt, bg-pt, my-pt, ca-pt, ceb-pt, zh-Hans-pt, zh-Hant-pt, co-pt, hr-pt, cs-pt, da-pt, nl-pt, en-pt, eo-pt, et-pt, fil-pt, fi-pt, fr-pt, gl-pt, ka-pt, de-pt, el-pt, gu-pt, ht-pt, ha-pt, haw-pt, iw-pt, hi-pt, hmn-pt, hu-pt, is-pt, ig-pt, id-pt, ga-pt, it-pt, ja-pt, jv-pt, kn-pt, kk-pt, km-pt, rw-pt, ko-pt, ku-pt, ky-pt, lo-pt, la-pt, lv-pt, lt-pt, lb-pt, mk-pt, mg-pt, ms-pt, ml-pt, mt-pt, mi-pt, mr-pt, mn-pt, ne-pt, no-pt, ny-pt, or-pt, ps-pt, fa-pt, pl-pt, pt-pt, pa-pt, ro-pt, ru-pt, sm-pt, gd-pt, sr-pt, sn-pt, sd-pt, si-pt, sk-pt, sl-pt, so-pt, st-pt, es-pt, su-pt, sw-pt, sv-pt, tg-pt, ta-pt, tt-pt, te-pt, th-pt, tr-pt, tk-pt, uk-pt, ur-pt, ug-pt, uz-pt, vi-pt, cy-pt, fy-pt, xh-pt, yi-pt, yo-pt, zu-pt, af-sr, sq-sr, am-sr, ar-sr, hy-sr, az-sr, bn-sr, eu-sr, be-sr, bs-sr, bg-sr, my-sr, ca-sr, ceb-sr, zh-Hans-sr, zh-Hant-sr, co-sr, hr-sr, cs-sr, da-sr, nl-sr, en-sr, eo-sr, et-sr, fil-sr, fi-sr, fr-sr, gl-sr, ka-sr, de-sr, el-sr, gu-sr, ht-sr, ha-sr, haw-sr, iw-sr, hi-sr, hmn-sr, hu-sr, is-sr, ig-sr, id-sr, ga-sr, it-sr, ja-sr, jv-sr, kn-sr, kk-sr, km-sr, rw-sr, ko-sr, ku-sr, ky-sr, lo-sr, la-sr, lv-sr, lt-sr, lb-sr, mk-sr, mg-sr, ms-sr, ml-sr, mt-sr, mi-sr, mr-sr, mn-sr, ne-sr, no-sr, ny-sr, or-sr, ps-sr, fa-sr, pl-sr, pt-sr, pa-sr, ro-sr, ru-sr, sm-sr, gd-sr, sr-sr, sn-sr, sd-sr, si-sr, sk-sr, sl-sr, so-sr, st-sr, es-sr, su-sr, sw-sr, sv-sr, tg-sr, ta-sr, tt-sr, te-sr, th-sr, tr-sr, tk-sr, uk-sr, ur-sr, ug-sr, uz-sr, vi-sr, cy-sr, fy-sr, xh-sr, yi-sr, yo-sr, zu-sr, af-es, sq-es, am-es, ar-es, hy-es, az-es, bn-es, eu-es, be-es, bs-es, bg-es, my-es, ca-es, ceb-es, zh-Hans-es, zh-Hant-es, co-es, hr-es, cs-es, da-es, nl-es, en-es, eo-es, et-es, fil-es, fi-es, fr-es, gl-es, ka-es, de-es, el-es, gu-es, ht-es, ha-es, haw-es, iw-es, hi-es, hmn-es, hu-es, is-es, ig-es, id-es, ga-es, it-es, ja-es, jv-es, kn-es, kk-es, km-es, rw-es, ko-es, ku-es, ky-es, lo-es, la-es, lv-es, lt-es, lb-es, mk-es, mg-es, ms-es, ml-es, mt-es, mi-es, mr-es, mn-es, ne-es, no-es, ny-es, or-es, ps-es, fa-es, pl-es, pt-es, pa-es, ro-es, ru-es, sm-es, gd-es, sr-es, sn-es, sd-es, si-es, sk-es, sl-es, so-es, st-es, es-es, su-es, sw-es, sv-es, tg-es, ta-es, tt-es, te-es, th-es, tr-es, tk-es, uk-es, ur-es, ug-es, uz-es, vi-es, cy-es, fy-es, xh-es, yi-es, yo-es, zu-es
[info] 5qBjFZV19p0: Downloading 1 format(s): 248
[youtube] Downloading comment section API JSON
[youtube] Downloading ~5968 comments
[youtube] Sorting comments by newest first
[youtube] Downloading comment API JSON page 1 (0/5968)
[youtube] Downloading comment API JSON page 2 (20/5968)
[youtube]     Downloading comment API JSON reply thread 1 (31/5968)
[youtube] Downloading comment API JSON page 3 (41/5968)
[youtube] Downloading comment API JSON page 4 (61/5968)
[youtube]     Downloading comment API JSON reply thread 1 (70/5968)
[youtube] Downloading comment API JSON page 5 (82/5968)
[youtube]     Downloading comment API JSON reply thread 1 (88/5968)
[youtube] Interrupted by user
[youtube] Extracted 88 comments
----------------------------------------------------
title:                The Dawn of Killer Robots (Full Length)
alt_title:            ~~~
playlist_index:       ~~~
playlist_autonumber:  ~~~
webpage_url:          https://www.youtube.com/watch?v=5qBjFZV19p0

format_id:            248
format:               248 - 1920x1080 (1080p)
format_note:          1080p

duration:             00:28:40
release_date:         ~~~
release_timestamp:    ~~~
upload_date:          2015-04-16
timestamp:            ~~~
epoch:                2022-01-23

creator:              ~~~

playlist_id:          ~~~
playlist_title:       ~~~
playlist_uploader:    ~~~
playlist_uploader_id: ~~~
----------------------------------------------------
```

I therefore assume, there is some issue with the RT extractor. Sorry that I am unable to further pinpoint the issue. I hope this helps as a starting point for your investigation.

### Verbose log

```shell
----------------------------------------------------
title:                The Dawn of Killer Robots (Full Length)
alt_title:            ~~~
playlist_index:       ~~~
playlist_autonumber:  ~~~
webpage_url:          https://www.youtube.com/watch?v=5qBjFZV19p0

format_id:            248
format:               248 - 1920x1080 (1080p)
format_note:          1080p

duration:             00:28:40
release_date:         ~~~
release_timestamp:    ~~~
upload_date:          2015-04-16
timestamp:            ~~~
epoch:                2022-01-23

creator:              ~~~

playlist_id:          ~~~
playlist_title:       ~~~
playlist_uploader:    ~~~
playlist_uploader_id: ~~~
----------------------------------------------------
```

**Comment by pukkandan** [comment]
The printing bug has been fixed in https://github.com/yt-dlp/yt-dlp/commit/88f23a18e0a0f5f18ed167b6a319c54255c5dd13

**Comment by pukkandan** [comment]
A single page may have multiple videos. That is why it returns a playlist. There is not really any reasonable title that can be given to the individual videos in that case. Eg: https://www.rt.com/sport/546301-djokovic-arrives-belgrade-crowds

**Comment by pukkandan** [comment]
> playlist or playlist_title is doubled: "The plot to assassinate Julian AssangeThe plot to assassinate Julian Assange"

`playlist` and `playlist_title` ae same here. This is normal

**Comment by chrizilla** [comment]
> A single page may have multiple videos. That is why it returns a playlist. There is not really any reasonable title that can be given to the individual videos in that case. Eg: https://www.rt.com/sport/546301-djokovic-arrives-belgrade-crowds

could we distinguish as follows ?

#### if page has >1 videos:
playlist = "Crowds gather to greet deported Djokovic as he returns to Serbia"
title video 1 =
title video 2 = 

#### if page has 1 video:
playlist = ""
video title = "Crowds gather to greet deported Djokovic as he returns to Serbia"

**Comment by chrizilla** [comment]
> `playlist` and `playlist_title` are the same here. This is normal. You are doubling it in your output template

sorry for my fault. Is there some trick to check in the output template `if playlist == playlist_title` ?
My idea was to have both playlist and playlist_title in the folder name, in case they differ (so as to not lose any information).
Or is this stupid, because it never occurs ?

from README:
```
playlist (string): Name or id of the playlist that contains the video
playlist_id (string): Playlist identifier
playlist_title (string): Playlist title
```
Does this in fact mean:
* `playlist` = either name or id of the playlist that contains the video, **BUT** if it's a name, it **can** be a different name than `playlist_title`
or
* `playlist` = either `playlist_id` or `playlist_title`
?

If it's the latter, it could be written like this in the README to clarify.
(If it's the former, it could use a little clarification as well :-).

**Comment by pukkandan** [comment]
> playlist = either playlist_id or playlist_title

This

> My idea was to have both playlist and playlist_title in the folder name, in case they differ (so as to not lose any information).
Or is this stupid, because it never occurs ?

You can use `playlist_id` and `playlist_title`

**Comment by chrizilla** [comment]
just to check if I got you right:
if `playlist` contains a name, it is **always** the same name as `playlist_title`
because
`playlist` = either `playlist_id` or `playlist_title`
right ?

So it's not possible to encounter a scenario such as:
`playlist` = "this is my playlist"
`playlist_title` = "this is my playlist for running"

**Comment by pukkandan** [comment]
> just to check if I got you right:
if playlist contains a name, it is always the same name as playlist_title
because
playlist = either playlist_id or playlist_title
right ?

Yes. Relevant code https://github.com/yt-dlp/yt-dlp/blob/88f23a18e0a0f5f18ed167b6a319c54255c5dd13/yt_dlp/YoutubeDL.py#L1612-L1614

**Comment by chrizilla** [comment]
ah!!! that explains it all 👍
