### ISSUE TITLE
Handeling 403 error exceptions

### ISSUE THREAD

**Issue by ScribbleGhost** [yt-dlp/yt-dlp#2471]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I seem to get a couple of 403 errors, but they happen after a file has been downloading for a while. If I restart the download it will usually complete successfully.

I am using `'retries': 20`, but it does not seem like yt-dlp is actually retrying the download. 

```
ydl_opts = {
	'ignore-config': True,
	'overwrites': False,
	'trim_file_name': 200,
	'verbose': True,
	'retries': 20,
}
with YoutubeDL(ydl_opts) as ydl:
	ydl.download([link])
```

Is there any option to restart the download if it fails from a 403 error?

### Verbose log

```shell
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-100606-gf797009778 (fdk), ffprobe N-100606-gf797009778, rtmpdump 2.3
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://example.com/video.mp4
[generic] video: Requesting header
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] video: Downloading 1 format(s): mp4
[debug] Invoking downloader on "https://example.com/video.mp4"
[download] Destination: test\video.mp4
[download]  93.6% of 2.31GiB at 528.10KiB/s ETA 04:52[download] Got server HTTP error: Downloaded 2320633768 bytes, expected 2478545149 bytes. Retrying (attempt 1 of 20) ...
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3054, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2769, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\http.py", line 371, in real_download
    establish_connection()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\http.py", line 119, in establish_connection
    raise err
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\http.py", line 113, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3526, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
`retries` only retries the actual download process (do not re-extract). There is no point in retrying for a 403

> Got server HTTP error: Downloaded 2320633768 bytes, expected 2478545149 bytes.

From your logs, first you got this error and yt-dlp did retry. But then it got a 403 and aborted

**Comment by abhranil26** [comment]
@pukkandan if i am using a rotating proxy, how do I get the extractor to retry? any inbuilt options in yt-dlp?
