### ISSUE TITLE
[instagram:user] Can't print json information

### ISSUE THREAD

**Issue by hbtalha** [yt-dlp/yt-dlp#2473]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

I am trying to get the json dump from the instagram user and I am getting this error:
```
ERROR: porsche: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)'));
```

### Verbose log

```shell
D:\Downloads\yt-dlp>yt-dlp.exe "https://www.instagram.com/porsche/" --print "%()j" > j.json -v
[debug] Command-line config: ['https://www.instagram.com/porsche/', '--print', '%()j', '-v']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8 (No ANSI), err utf-8, pref cp65001
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n4.4-179-g57e39b7a0f-20211009 (setts), ffprobe n4.4-179-g57e39b7a0f-20211009, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [instagram:user] Extracting URL: https://www.instagram.com/porsche/
[instagram:user] porsche: Downloading webpage
[download] Downloading playlist: porsche
[instagram:user] porsche: Downloading JSON page 1
ERROR: porsche: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1003, in _parse_json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1003, in _parse_json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1668, in <lambda>
  File "yt_dlp\utils.py", line 2736, in __getitem__
  File "yt_dlp\extractor\instagram.py", line 437, in _extract_graphql
  File "yt_dlp\extractor\common.py", line 992, in _download_json
  File "yt_dlp\extractor\common.py", line 978, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 1007, in _parse_json
yt_dlp.utils.ExtractorError: porsche: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

[instagram:user] playlist porsche: Downloading 0 videos
[download] Finished downloading playlist: porsche
```

**Comment by pukkandan** [comment]
Related: https://github.com/yt-dlp/yt-dlp/issues/2473

**Comment by pukkandan** [comment]
Superseeded by #4394
