### ISSUE TITLE
[orf:fm4:story] RemoteDisconnected

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2477]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria

### Description

As [discussed](https://github.com/yt-dlp/yt-dlp/issues/2411#issuecomment-1019566008), the `orf:fm4:story` extractor doesn't seem to work anymore.
error: _"Remote end closed connection without response"_

example URL: https://fm4.orf.at/stories/3021295

I looked into [orf.py](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/orf.py) but I am of no help yet, sorry.

### Verbose log

```shell
[debug] Command-line config: ['https://fm4.orf.at/stories/3021295', '--ignore-config', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [orf:fm4:story] Extracting URL: https://fm4.orf.at/stories/3021295
[orf:fm4:story] 3021295: Downloading webpage
[orf:fm4:story] 885473: Downloading JSON metadata
[orf:fm4:story] 885473: Downloading JSON metadata
ERROR: [orf:fm4:story] 3021295: Unable to download JSON metadata: Remote end closed connection without response (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 730, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3526, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1348, in http_open
  File "urllib\request.py", line 1358, in do_open
  File "http\client.py", line 1344, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 276, in _read_status
```

**Comment by schumar** [comment]
With `2022.03.08.1`, I get a 502:

```
$ yt-dlp https://fm4.orf.at/stories/3021929/
[orf:fm4:story] 3021929: Downloading webpage
[orf:fm4:story] 890753: Downloading JSON metadata
[orf:fm4:story] 890753: Downloading JSON metadata
Traceback (most recent call last):
  File "/home/martin/bin/yt-dlp/yt_dlp/extractor/common.py", line 735, in _request_webpage
  File "/home/martin/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3591, in urlopen
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/bin/yt-dlp/yt_dlp/extractor/common.py", line 617, in extract
  File "/home/martin/bin/yt-dlp/yt_dlp/extractor/orf.py", line 565, in _real_extract
  File "/home/martin/bin/yt-dlp/yt_dlp/extractor/common.py", line 997, in _download_json
  File "/home/martin/bin/yt-dlp/yt_dlp/extractor/common.py", line 976, in _download_json_handle
  File "/home/martin/bin/yt-dlp/yt_dlp/extractor/common.py", line 768, in _download_webpage_handle
  File "/home/martin/bin/yt-dlp/yt_dlp/extractor/common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 502: Bad Gateway (caused by <HTTPError 502: 'Bad Gateway'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
  File "/home/martin/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
  File "/home/martin/bin/yt-dlp/yt_dlp/extractor/common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [orf:fm4:story] 3021929: Unable to download JSON metadata: HTTP Error 502: Bad Gateway (caused by <HTTPError 502: 'Bad Gateway'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/martin/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/home/martin/bin/yt-dlp/yt_dlp/__init__.py", line 864, in main
  File "/home/martin/bin/yt-dlp/yt_dlp/__init__.py", line 854, in _real_main
  File "/home/martin/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3254, in download
  File "/home/martin/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3227, in wrapper
  File "/home/martin/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1380, in extract_info
  File "/home/martin/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1407, in wrapper
  File "/home/martin/bin/yt-dlp/yt_dlp/utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
```

**Comment by schumar** [comment]
In case someone needs a quick work-around: Visit the page in your browser, open the Network monitor, search for the `manifest.mpd` URL, and pass that to `yt-dlp`, e.g.
```
yt-dlp https://apasfiis.sf.apa.at/filehandler_nas/_definst_/nas/filehandler/online/890753_fh_20220212-psc-komplett-v1.smil/manifest.mpd
```
