### ISSUE TITLE
Dailymotion corrupted subtitles

### ISSUE THREAD

**Issue by kamiTT** [yt-dlp/yt-dlp#2502]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When downloading subtitles from dailymotion, the resulting file is corrupt. It cannot be played on a video player or converted to another subtitle format during post-processing. 

### Verbose log

```shell
[dailymotion] Downloading Access Token
[dailymotion] x6vwb4j: Downloading media JSON metadata
[dailymotion] x6vwb4j: Downloading metadata JSON
[dailymotion] x6vwb4j: Downloading m3u8 information
[info] x6vwb4j: Downloading 1 format(s): http-720-1
Deleting existing file /Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt
[info] Writing video subtitles to: /Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt
[download] Destination: Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt
[aria2c] Downloaded 16976 bytes
[download] 100% of 16.58KiB in 00:00
[SubtitlesConvertor] Converting subtitles
ERROR: Preprocessing: file: /Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt: Invalid data found when processing input
kamitt@kamitt-MacBook-Air x643nc % yt-dlp --version
2022.01.21
kamitt@kamitt-MacBook-Air x643nc % yt-dlp --skip-download --all-subs --write-subs https://www.dailymotion.com/video/x6vwb4j --convert-subs ass --verbose
[debug] Command-line config: ['--skip-download', '--all-subs', '--write-subs', 'https://www.dailymotion.com/video/x6vwb4j', '--convert-subs', 'ass', '--verbose']
[debug] User config "/.config/yt-dlp/config": ['--embed-chapters', '--sub-lang', 'en.*,EN.*', '--compat-options', 'no-live-chat', '--convert-subs', 'srt', '--embed-subs', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '--downloader', 'aria2c', '--downloader', 'dash,m3u8:native', '-f', '(bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best', '-o', '~/Movies/video/youtube-dl/%(playlist)s/%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Compatibility options: no-live-chat
[debug] Python version 3.9.10 (CPython 64bit) - macOS-11.6.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [dailymotion] Extracting URL: https://www.dailymotion.com/video/x6vwb4j
[dailymotion] Downloading Access Token
[dailymotion] x6vwb4j: Downloading media JSON metadata
[dailymotion] x6vwb4j: Downloading metadata JSON
[dailymotion] x6vwb4j: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en
[info] x6vwb4j: Downloading 1 format(s): http-720-1
[info] Writing video subtitles to: Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt
[debug] Invoking downloader on "https://static2.dmcdn.net/static/video/365/273/416372563_subtitle_en.srt?rev=0"
[download] Destination: Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --file-allocation=none -x16 -j16 -s16 --min-split-size 1M --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Encoding: gzip, deflate' --header 'Accept-Language: en-us,en;q=0.5' --header 'Sec-Fetch-Mode: navigate' --header 'Cookie: v1st=2FAF9E290F13DDAC5418334BA0BA69AE; ts=41602; dmvk=61f1951a6e76f' --check-certificate=true --remote-time=true --show-console-readout=true --dir /Movies/video/youtube-dl/NA/ --out './ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt.part' --auto-file-renaming=false -- 'https://static2.dmcdn.net/static/video/365/273/416372563_subtitle_en.srt?rev=0'
[aria2c] Downloaded 16976 bytes
[download] 100% of 16.58KiB in 00:00
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt' -f ass -movflags +faststart 'file:/Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.ass'
[debug] ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.3)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4.1_5 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
file:/Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt: Invalid data found when processing input
ERROR: Preprocessing: file: /Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt: Invalid data found when processing input
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.1.21/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2909, in process_info
    new_info, files_to_move = self.pre_process(info_dict, 'before_dl', files_to_move)
  File "/usr/local/Cellar/yt-dlp/2022.1.21/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3297, in pre_process
    info = self.run_all_pps(key, info)
  File "/usr/local/Cellar/yt-dlp/2022.1.21/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3291, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/Cellar/yt-dlp/2022.1.21/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3263, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/Cellar/yt-dlp/2022.1.21/libexec/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2022.1.21/libexec/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 998, in run
    self.run_ffmpeg(old_file, new_file, ['-f', new_format])
  File "/usr/local/Cellar/yt-dlp/2022.1.21/libexec/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 340, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2022.1.21/libexec/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 294, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/Cellar/yt-dlp/2022.1.21/libexec/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 333, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file: /Movies/video/youtube-dl/NA/ซีรีส์รักนะเป็ดโง่ Ugly duckling _ Perfect Match _ EP.1.en.srt: Invalid data found when processing input
```

**Comment by kamiTT** [comment]
Issue was coming from the external downloader, not the native client.
