### ISSUE TITLE
How to place archive file inside playlist folder? 

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#2503]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

When using `-o` with `%(playlist_title)s` and `--download-archive`, how can I place the archive file inside the playlist name? 

Specifically, with this combination it doesn't seem to work: `"%(playlist_title)s/%(upload_date)s - %(title)s" --download-archive "%(playlist_title)s/archive.txt"`

Please see the verbose log for details - thank you for reading. 

### Verbose log

```shell
yt-dlp -vU -i ... -o "%(playlist_title)s/%(upload_date)s - %(title)s" --download-archive "%(playlist_title)s/archive.txt" --merge-output mp4 --add-metadata 
[debug] Command-line config: ['-vU', '-i', 'https://www.youtube.com/playlist?list=PLW--L_tD2yC8cNfisXew66bJIOAM8AAEC', '-o', '%(playlist_title)s/%(upload_date)s - %(title)s', '--download-archive', '%(playlist_title)s/archive.txt', '--merge-output', 'mp4', '--add-metadata']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.15.15-76051515-generic-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file '%(playlist_title)s/archive.txt'
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLW--L_tD2yC8cNfisXew66bJIOAM8AAEC
[youtube:tab] PLW--L_tD2yC8cNfisXew66bJIOAM8AAEC: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLW--L_tD2yC8cNfisXew66bJIOAM8AAEC
[youtube:tab] PLW--L_tD2yC8cNfisXew66bJIOAM8AAEC: Downloading API JSON with unavailable videos
[download] Downloading playlist: [Work] BWF Product Sample
[youtube:tab] playlist [Work] BWF Product Sample: Downloading 19 videos
[download] Downloading video 1 of 19
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=n8XvTQl9Thg
[youtube] n8XvTQl9Thg: Downloading webpage
[youtube] n8XvTQl9Thg: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] n8XvTQl9Thg: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr8---sn-qpnugpc0uxa-tu1l.googlevideo.com/videoplayback?expire=1643255816&ei=p8PxYZGbOuWsir4PmZiv-A4&ip=216.58.16.107&id=o-ALRgh8RP7rV9XrgKIJiMJo848rStjjRDGCP3iYWXWlbT&itag=248&source=youtube&requiressl=yes&mh=2G&mm=31%2C29&mn=sn-qpnugpc0uxa-tu1l%2Csn-tt1eln7l&ms=au%2Crdu&mv=m&mvi=8&pl=17&gcr=ca&initcwndbps=1165000&vprv=1&mime=video%2Fwebm&gir=yes&clen=673781526&dur=3835.000&lmt=1642165894863697&mt=1643233967&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=7316222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALnJ9lrmdNtd-BmLSxMfayQIHU9_xOuA91UsiOEoe4f2AiEAxMd4j5XKwVwx8alOopK46LZ0aT1yq6dAM1Kw5DZjZjw%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgV97x7tWPZmy3uQ8oWIX_AjX4c7PehiqPOR3KZLHZYuICIQCsSLGwDKuEjQpn_YWfbpnzCG7T_tYkB1MQ8JtHr6Migg%3D%3D"
[download] Resuming download at byte 329738868
[download] Destination: [Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.f248.webm
[download] 100% of 642.57MiB in 00:37
[debug] Invoking downloader on "https://rr8---sn-qpnugpc0uxa-tu1l.googlevideo.com/videoplayback?expire=1643255816&ei=p8PxYZGbOuWsir4PmZiv-A4&ip=216.58.16.107&id=o-ALRgh8RP7rV9XrgKIJiMJo848rStjjRDGCP3iYWXWlbT&itag=251&source=youtube&requiressl=yes&mh=2G&mm=31%2C29&mn=sn-qpnugpc0uxa-tu1l%2Csn-tt1eln7l&ms=au%2Crdu&mv=m&mvi=8&pl=17&gcr=ca&initcwndbps=1165000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=61272501&dur=3835.021&lmt=1642165817031622&mt=1643233967&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=7311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPbE2-gqbQjNwxPvZlYapXCZpTtGLaSs8SK6OrASg17AAiEAmTBvlyCbDxHHmI38XfT3z9wAgWLXwazSSqbtW0-gUBs%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgV97x7tWPZmy3uQ8oWIX_AjX4c7PehiqPOR3KZLHZYuICIQCsSLGwDKuEjQpn_YWfbpnzCG7T_tYkB1MQ8JtHr6Migg%3D%3D"
[download] Destination: [Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.f251.webm
[download] 100% of 58.43MiB in 00:07
[Merger] Merging formats into "[Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:[Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.f248.webm' -i 'file:[Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:[Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.temp.mp4'
[debug] ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'file:[Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.f248.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 01:03:55.00, start: 0.000000, bitrate: 1405 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:[Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 01:03:55.02, start: -0.007000, bitrate: 127 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
[mp4 @ 0x55a34a74f700] track 1: codec frame size is not set
[mp4 @ 0x55a34a74f700] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3263, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 117, in wrapper
    return func(self, info)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 830, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 294, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 333, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

[Metadata] Adding metadata to "[Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.mp4"
ERROR: [Errno 2] No such file or directory: '[Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.mp4'
Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1367, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1503, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2589, in process_video_result
    self.process_info(new_info)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3127, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3304, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3291, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3263, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 117, in wrapper
    return func(self, info)
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 711, in run
    self.run_ffmpeg_multiple_files(
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 294, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 301, in real_run_ffmpeg
    oldest_mtime = min(
  File "/home/wilsonchan/anaconda3/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 302, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path, _ in input_path_opts if path)
FileNotFoundError: [Errno 2] No such file or directory: '[Work] BWF Product Sample/20220114 - YONEX-SUNRISE India Open 2022 _ Kim Bruun (DEN) vs Brian Yang (CAN) _ QF.mp4'
```

**Comment by pukkandan** [comment]
Archive is a single file and not an output template. See https://github.com/yt-dlp/yt-dlp/issues/953

**Comment by afterdelight** [comment]
add this pls
