### ISSUE TITLE
ok.ru can't download all videos

### ISSUE THREAD

**Issue by on1razor** [yt-dlp/yt-dlp#2527]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://ok.ru/profile/567991501309/video

### Description

Please add to the extractor the ability to download all videos from user pages from the ok.ru site, it will make my life much easier. Thank you

### Verbose log

```shell
yt-dlp -v --proxy socks5://91.121.6.84:2114 https://ok.ru/profile/567991501309/video
[debug] Command-line config: ['-v', '--proxy', 'socks5://91.121.6.84:2114', 'https://ok.ru/profile/567991501309/video']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-104250-g05c1f78a72-20211007 (setts), ffprobe N-104250-g05c1f78a72-20211007
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'socks5://91.121.6.84:2114', 'https': 'socks5://91.121.6.84:2114'}
[debug] [generic] Extracting URL: https://ok.ru/profile/567991501309/video
[generic] video: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://ok.ru/profile/567991501309/video
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3966, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://ok.ru/profile/567991501309/video
```

**Comment by chapmanjacobd** [comment]
One thing that I have discovered is that some playlist URLs have different access rules based on how you request it. 

For example:

```
https://ok.ru/fleurrinna.guta/video/c1955438
```

only lists 2 videos. however, if you delete the `/fleurrinna.guta` component of the URL you get access to the full playlist (same playlist ID) without needing to login:

```
https://ok.ru/video/c1955438
```

On the first request you can then read the first 24 video ids, but I'm not sure how to fetch the next page

```
xidel -e '//div[@data-id]/join(
       (
         div[@class="video-card_img-w"]/a/resolve-uri(substring-before(@href,"?")),
         div[@class="video-card_n-w"]/a
       ),
       " # "
     )
   ' -s https://ok.ru/video/c1955438 | pee 'xclip -sel clip' 'wc -l'
24
```

**Comment by Reqrefusion** [comment]
Hopefully an easier method will come in the future. For now @chapmanjacobd 's method seems like the best. I wrote a userscript script to make it even easier. It makes things easier, but I still prefer yt-dlp to have such a feature.
```
// ==UserScript==
// @name         Download ok.ru video URLs
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Download ok.ru video URLs
// @match        https://ok.ru/*
// @grant        none
// ==/UserScript==


function scrollAndCheck() {
    var previousScroll = window.pageYOffset;
    window.scrollBy(0, 1000);

    var currentScroll = window.pageYOffset;
    var maxScroll = document.body.scrollHeight - window.innerHeight;

    if (currentScroll + 10 >= maxScroll && previousScroll == currentScroll) {
        clearInterval(scrollInterval);
        downloadURLs();
    }
}

function downloadURLs() {
    var elements = document.getElementsByClassName("video-card_img-w");

    if (elements.length === 0) {
        return;
    }

    var urls = [];

    for (var i = 0; i < elements.length; i++) {
        var element = elements[i];

        if (element.id) {
            var id = element.id.replace("video-card_img_", "");

            var url = "https://ok.ru/video/" + id;

            url = url.slice(0, -1);

            urls.push(url);
        }
    }

    var text = urls.join("\n");
    var blob = new Blob([text], {type: "text/plain"});

    var link = document.createElement("a");
    link.href = URL.createObjectURL(blob);

    var pageID = window.location.pathname.split("/").pop();

    link.download = pageID + ".txt";

    document.body.appendChild(link);
    link.click();

    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);
}

var scrollInterval = setInterval(scrollAndCheck, 1000);
```

**Comment by nova2moon** [comment]
Was this ever released in any format ? test/build how does one "apply" this fix to an existing yt-dlp (on windows or linux)?

**Comment by InvalidUsernameException** [comment]
@nova2moon The posted code is a user script for a for a user script manager addon in a web browser. There is no code yet that can be applied to yt-dlp.
