### ISSUE TITLE
Amazon Prime Video trailers

### ISSUE THREAD

**Issue by redoXiD** [yt-dlp/yt-dlp#2544]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

Site with trailer: 
https://www.amazon.com/dp/B07RK3CBNQ/
https://www.amazon.com/Mission-Impossible-Fallout-4K-UHD/dp/B07RK3CBNQ/

Manifest file: 
https://pop-iad-2.cf.dash.row.aiv-cdn.net/dm/2$O2I7YyMfsiZnMWVzSIOZdM40UxA~/87f5/ba0e/0bc1/4322-96bf-0e7f5f024e37/91f332c9-d66a-4321-9966-eeab0c0f7c81_corrected.mpd?amznDtid=AOAGZA014O5RE&encoding=segmentBase

### Description

[Amazon Prime Video](https://www.amazon.com/Prime-Video/b?node=2676882011) allows users to watch trailers, which are not protected by DRM and therefore downloadable.
For now, with the normal site only product videos seem to work but not trailers. --> _[AmazonStore] B07RK3CBNQ: Unable to extract data_
Applies on all regional Amazon stores. 

An example with the manifest file is shown below.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-f', 'bestvideo+audio_en-US_4=640000', 'https://pop-iad-2.cf.dash.row.aiv-cdn.net/dm/2~/87f5/ba0e/0bc1/4322-96bf-0e7f5f024e37/91f332c9-d66a-4321-9966-eeab0c0f7c81_corrected.mpd?amznDtid=AOAGZA014O5RE&encoding=segmentBase']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-08-18-git-dbe40478e2-full_build-www.gyan.dev (setts), ffprobe 2021-03-28-git-8b2bde0494-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [generic] Extracting URL: https://pop-iad-2.cf.dash.row.aiv-cdn.net/dm/2~/87f5/ba0e/0bc1/4322-96bf-0e7f5f024e37/91f332c9-d66a-4321-9966-eeab0c0f7c81_corrected.mpd?amznDtid=AOAGZA014O5RE&encoding=segmentBase
[generic] 91f332c9-d66a-4321-9966-eeab0c0f7c81_corrected: Requesting header
WARNING: [generic] Could not send HEAD request to https://pop-iad-2.cf.dash.row.aiv-cdn.net/dm/2~/87f5/ba0e/0bc1/4322-96bf-0e7f5f024e37/91f332c9-d66a-4321-9966-eeab0c0f7c81_corrected.mpd?amznDtid=AOAGZA014O5RE&encoding=segmentBase: HTTP Error 403: Forbidden
[generic] 91f332c9-d66a-4321-9966-eeab0c0f7c81_corrected: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 91f332c9-d66a-4321-9966-eeab0c0f7c81_corrected: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 91f332c9-d66a-4321-9966-eeab0c0f7c81_corrected: Downloading 1 format(s): video=15000000+audio_en-US_4=640000
[debug] Invoking downloader on "https://pop-iad-2.cf.dash.row.aiv-cdn.net/dm/2~/87f5/ba0e/0bc1/4322-96bf-0e7f5f024e37/91f332c9-d66a-4321-9966-eeab0c0f7c81_video_12.mp4"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3036, in process_info
  File "yt_dlp\YoutubeDL.py", line 2769, in dl
  File "yt_dlp\downloader\common.py", line 440, in download
  File "yt_dlp\downloader\http.py", line 371, in real_download
  File "yt_dlp\downloader\http.py", line 119, in establish_connection
  File "yt_dlp\downloader\http.py", line 113, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3526, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by redoXiD** [comment]
I discovered a few interesting things: 

In Windows Terminal (PowerShell) this part is ignored, leading to the 403 errors:

https://pop-iad-2.cf.dash.row.aiv-cdn.net/dm/2 **_$NBOu0pbEtX2hhRKLDQ9nBRdaLwE_** ~/87f5/ba0e/0bc1/4322-96bf-0e7f5f024e37/91f332c9-d66a-4321-9966-eeab0c0f7c81_corrected.mpd?amznDtid=AOAGZA014O5RE&encoding=segmentBase

But because it is ignored (resulting in a different manifest file), more audio formats (e-ac-3) become available:

![image](https://user-images.githubusercontent.com/44555835/151708395-cbe23f6f-15b6-4890-8faa-660a0fdf96d4.png)

vs CMD (does not ignore the part between "2" and "~" /original link)

![image](https://user-images.githubusercontent.com/44555835/151708423-42060c00-9e06-4c53-8ef6-91dadfaa1825.png)

The better E-AC-3 audio and the video files only become available to download using the original link (with "$NBOu0pbEtX2hhRKLDQ9nBRdaLwE").
Example: https://pop-iad-2.cf.dash.row.aiv-cdn.net/dm/2$NBOu0pbEtX2hhRKLDQ9nBRdaLwE~/87f5/ba0e/0bc1/4322-96bf-0e7f5f024e37/91f332c9-d66a-4321-9966-eeab0c0f7c81_audio_9.mp4?amznDtid=AOAGZA014O5RE&encoding=segmentBase

Would it be possible to get the available formats from the new manifest file and then download the desired formats with the original link?

**Comment by trassshhub** [comment]
I don't have an Amazon Prime account, but have you tried actually downloading through the manifest with "better" audio?
I am getting error 403 with it while the original link works with its best audio.

**Comment by redoXiD** [comment]
I also tried to shorten the link of the manifest a bit with **positive results**, this is the shortest link which worked in yt-dlp:

`yt-dlp -f audio_en-US_4=640000 "https://pop-iad-2.cf.dash.row.aiv-cdn.net/dm/87f5/ba0e/0bc1/4322-96bf-0e7f5f024e37/91f332c9-d66a-4321-9966-eeab0c0f7c81_corrected.mpd?encoding=segmentBase"`
--> deleting "**2$O2I7YyMfsiZnMWVzSIOZdM40UxA~/**" from the original link does the trick. You can shorten it even further, to keep it working in yt-dlp, you have to at least keep "?encoding=segmentBase" at the end of the link.

So what remains is the way from the normal page to the manifest file

**Comment by Bricio** [comment]
I am on final phase of coding a first version of this.

![image](https://user-images.githubusercontent.com/216170/152555121-45c4b3d7-6e87-44a6-b8c6-9fa6af704407.png)

Right now to identify trailer or film, it need full url of the trailer (with ?autoplay=trailer)
https://www.amazon.com/gp/video/detail/B07RK3CBNQ/ref=atv_dp_watch_trailer?autoplay=trailer 
or 
https://www.amazon.com/gp/video/detail/B00AZNSLQM/ref=atv_dp_watch_trailer?autoplay=trailer
Just right click on trailer button and copy link.
![image](https://user-images.githubusercontent.com/216170/152556175-0ecfe4a1-c444-40b7-9795-24f339e33ce0.png)

What do you think about this solution?

**Comment by pukkandan** [comment]
It is fine if the normal URL downloads trailer too. But show a warning informing user what is happening. I just dont want to get issues like "amazon is only downloading trailers"

Something like:

```
WARNING: Amazon Prime videos use DRM and will not be supported. Downloading the trailer instead
```

**Comment by redoXiD** [comment]
Looks good so far!
Would it be possible to also include e-ac-3 audio by modifying the URL (as described in my post above)?

**Comment by Bricio** [comment]
@redoXiD 
I dont understand the modifying url part. 
If you removed the "2$O2I7YyMfsiZnMWVzSIOZdM40UxA~/" part you got 403 error, so what is the point of that?
Now the URL is recovered from JSON returned from GetPlaybackResources POST.
I dont need to generate or modify it. It is pretty much useless to short this URL.


I just notice that primevideo have almost the same code of amazon. That makes sense...
So, I coded that too in the same extractor.

![image](https://user-images.githubusercontent.com/216170/152630019-40b039a3-5344-4616-8baa-605d6dc2f3a1.png)

@pukkandan 
I put the warning message. 
I use print() instead of report_warning(), because report_warning triggers multiples errors on tests.

One thing i notice is amazon uses multiple sources of MPD manifests, each one with a different video host.
If I list video formats I get multiple repeated formats. Even using _remove_duplicate_formats.

![image](https://user-images.githubusercontent.com/216170/152630304-a01cac2f-b6e2-4843-a65c-ace7c4b3b3c3.png)

Is there a way to have same format with multiples urls?




On monday I will create a draft pull request to share the code.

**Comment by redoXiD** [comment]
@Bricio The 403 errors existed because of an error in PowerShell, where the "$" caused to ignore a part of the URL. But if you remove the _whole_ part (/dm/**2 $NBOu0pbEtX2hhRKLDQ9nBRdaLwE ~/** 87f5/ba0e/0bc1/) and effectively shorten the URL, it works perfectly and even includes additional audio formats. It's great to see that you found another way, but does this method also include e-ac-3 audio for the trailers?

**Comment by redoXiD** [comment]
@Bricio The 403 errors existed because of an error in PowerShell, where the "$" caused to ignore a part of the URL. But if you remove the _whole_ part (.../dm/**2 $NBOu0pbEtX2hhRKLDQ9nBRdaLwE ~/** 87f5/ba0e/0bc1/...) and effectively shorten the URL, it works perfectly fine and even includes additional audio formats. It's great to see that you found another way, but would this method also include e-ac-3 audio for trailers?

**Comment by Bricio** [comment]
redoXiD

ec-3 audio added. 

![image](https://user-images.githubusercontent.com/216170/153106631-c50f72ee-8516-4cfb-bd7e-7f49badcb258.png)




I need help in a point. 
Amazon store and Amazon prime have the same url format.
https://www.amazon.com/dp/B07YNLBS7R/
https://www.amazon.com/dp/B07RK3CBNQ/

I don't think valid URL regex can differentiate them.

How can I code to catch the extraction error in amazon store and call amazon trailer extractor?

**Comment by HobbyistDev** [comment]
How about `suitable` method ?
