### ISSUE TITLE
Instagram: 'NoneType' object is not a mapping

### ISSUE THREAD

**Issue by wxolp** [yt-dlp/yt-dlp#2552]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

Using `master`

### Verbose log

```shell
[debug] Command-line config: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.instagram.com/p/CZVEugIPkVn/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.9 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-06-30-git-de8e6e67e7-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[Instagram] Downloading login webpage
[Instagram] Logging in
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CZVEugIPkVn/
[Instagram] CZVEugIPkVn: Downloading webpage
ERROR: 'NoneType' object is not a mapping
Traceback (most recent call last):
  File "C:\python\lib\site-packages\yt_dlp\YoutubeDL.py", line 1374, in wrapper
    return func(self, *args, **kwargs)
  File "C:\python\lib\site-packages\yt_dlp\YoutubeDL.py", line 1444, in __extract_info
    ie_result = ie.extract(url)
  File "C:\python\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\python\lib\site-packages\yt_dlp\extractor\instagram.py", line 396, in _real_extract
    return self._extract_product(product_item)
  File "C:\python\lib\site-packages\yt_dlp\extractor\instagram.py", line 194, in _extract_product
    return {
TypeError: 'NoneType' object is not a mapping
```

**Comment by pukkandan** [comment]
Could you check if this fixes it?
```diff
diff --git a/yt_dlp/extractor/instagram.py b/yt_dlp/extractor/instagram.py
index 9db318223..a2cc9f748 100644
--- a/yt_dlp/extractor/instagram.py
+++ b/yt_dlp/extractor/instagram.py
@@ -134,7 +134,7 @@ class InstagramBaseIE(InfoExtractor):
         dash_manifest_raw = product_media.get('video_dash_manifest')
         videos_list = product_media.get('video_versions')
         if not (dash_manifest_raw or videos_list):
-            return None
+            return {}

         formats = [{
             'format_id': format.get('id'),
```
