### ISSUE TITLE
[YouTube] nsig extraction now fails

### ISSUE THREAD

**Issue by TheMCNerd2017** [yt-dlp/yt-dlp#2569]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Starting sometime today (as of posting this), yt-dlp now throws an error about nsig extraction failing when downloading YouTube videos. I don't know what caused this as earlier today no error would come up when downloading videos (perhaps Google changed something on their end). I don't use an account for downloading videos either. I canceled the download shortly after the error comes up as it would take too long to actually download the video (my phone ISP throttles YouTube to 300KB/s). If you want me to attempt to download the video completely to see if something else happens please let me know.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=fCucjL2SmLE']                                   [debug] User config "/data/data/com.termux/files/home/.config/yt-dlp/config": ['--no-mtime', '--ignore-errors', '--min-sleep-interval', '4', '--max-sleep-interval', '20', '-o', '/data/data/com.termux/files/home/storage/shared/Youtube/%(playlist_index)s-%(title)s-%(id)s.%(ext)s', '-f', 'bv*+ba/b', '--remux-video', 'mp4/mkv']                             [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]              [debug] Python version 3.10.1 (CPython 64bit) - Linux-4.14.243-gb26579d061ac-aarch64-with-libc
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21    yt-dlp is up to date (2022.01.21)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=fCucjL2SmLE
[youtube] fCucjL2SmLE: Downloading webpage
[youtube] fCucjL2SmLE: Downloading android player API JSON
[youtube] fCucjL2SmLE: Downloading player e06dea74
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = SrIafPCsV8qC_dqlxb ; player = https://www.youtube.com/s/player/e06dea74/player_ias.vflset/en_US/base.js
fCucjL2SmLE: Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2421, in _extract_n_function_name
    return self._search_regex(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] fCucjL2SmLE: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://rr3---sn-uhvcpax0n5-jaxe.googlevideo.com/videoplayback?expire=1643708580&ei=Q6z4YZLtO9qG_9EP1qGQqAY&ip=2607%3Afb90%3Ab44a%3A86d0%3A2712%3Aece0%3A81de%3Afccc&id=o-ALYlukkQbrVn0GLFpxySaVPS-7J6aAvt2WWkXvhEMJW9&itag=303&source=youtube&requiressl=yes&mh=gV&mm=31%2C29&mn=sn-uhvcpax0n5-jaxe%2Csn-vgqsknee&ms=au%2Crdu&mv=m&mvi=3&pl=40&initcwndbps=372500&vprv=1&mime=video%2Fwebm&gir=yes&clen=291319771&dur=1595.993&lmt=1602424298587367&mt=1643686600&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQsEO4Y5mW0o6w77DN6i_XWvz8cDxzpCMDl-dSmYVNg0CIQCX6Evlhshum9IiDu3j5lJ3Q_DBNRhLtJcs8zZuA_unIw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKaxI9rfL6RwLY6CHhfxjVMHcDC2rAxq5lYLqYOynyTxAiAsR8sXawG_gyI29U1ziLOI25Fd1x9vuzsuisV0zDn_wA%3D%3D"
[download] Sleeping 12.34 seconds ...
^C
```

**Comment by pukkandan** [comment]
Already fixed 😃 https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8

**Comment by TheMCNerd2017** [comment]
> Already fixed smiley [48416bc](https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8)

Cool it was fixed that quick. Sorry I posted a bug report without knowing it was fixed.

**Comment by pukkandan** [comment]
It's fine. I dont expect users to look at commit history before opening issues. Today we just happened to notice (and fix) it immediately. If this happens again, don't hesitate to report

**Comment by TheMCNerd2017** [comment]
> It's fine. I dont expect users to look at commit history before opening issues. Today we just happened to notice (and fix) it immediately. If this happens again, don't hesitate to report

Oh OK.

**Comment by Logarithmus** [comment]
@pukkandan please, make a new release so ordinary users could watch YouTube again in mpv.

**Comment by pukkandan** [comment]
Does it actually throttle (without this patch)? For most videos, the fallbacks should already handle this

**Comment by Logarithmus** [comment]
@pukkandan funnily enough, just after your comment this video started downloading at full speed https://youtube.com/watch?v=LR9FtWVjk2c

**Comment by pukkandan** [comment]
See the `THROTTLED` in `MORE INFO`. The other formats don't get throttled
```
[info] Available formats for LR9FtWVjk2c:
ID  EXT   RESOLUTION FPS │   FILESIZE    TBR PROTO │ VCODEC         VBR ACODEC      ABR     ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27          │                   mhtml │ images                                     storyboard
sb1 mhtml 80x45          │                   mhtml │ images                                     storyboard
sb0 mhtml 160x90         │                   mhtml │ images                                     storyboard
139 m4a   audio only     │    4.44MiB    48k https │ audio only         mp4a.40.5   48k 22050Hz low, m4a_dash
249 webm  audio only     │    4.48MiB    49k https │ audio only         opus        49k 48000Hz low, webm_dash
250 webm  audio only     │    4.96MiB    54k https │ audio only         opus        54k 48000Hz low, webm_dash
140 m4a   audio only     │   11.78MiB   129k https │ audio only         mp4a.40.2  129k 44100Hz medium, m4a_dash
251 webm  audio only     │    9.46MiB   104k https │ audio only         opus       104k 48000Hz medium, webm_dash
17  3gp   176x144      8 │    6.89MiB    75k https │ mp4v.20.3      75k mp4a.40.2    0k 22050Hz 144p
160 mp4   256x144     30 │    6.55MiB    72k https │ avc1.4d400c    72k video only              144p, mp4_dash
278 webm  256x144     30 │    7.04MiB    77k https │ vp9            77k video only              144p, webm_dash
133 mp4   426x240     30 │   14.52MiB   159k https │ avc1.4d4015   159k video only              240p, mp4_dash
242 webm  426x240     30 │   12.93MiB   142k https │ vp9           142k video only              240p, webm_dash
134 mp4   640x360     30 │   29.82MiB   327k https │ avc1.4d401e   327k video only              360p, mp4_dash
18  mp4   640x360     30 │   62.19MiB   683k https │ avc1.42001E   683k mp4a.40.2    0k 44100Hz 360p
243 webm  640x360     30 │   32.25MiB   354k https │ vp9           354k video only              360p, webm_dash
135 mp4   854x480     30 │   49.10MiB   539k https │ avc1.4d401f   539k video only              480p, mp4_dash
244 webm  854x480     30 │   46.03MiB   506k https │ vp9           506k video only              480p, webm_dash
136 mp4   1280x720    30 │  153.29MiB  1685k https │ avc1.4d401f  1685k video only              720p, THROTTLED, mp4_dash
247 webm  1280x720    30 │   92.34MiB  1015k https │ vp9          1015k video only              720p, THROTTLED, webm_dash
22  mp4   1280x720    30 │ ~168.99MiB  1814k https │ avc1.64001F  1814k mp4a.40.2    0k 44100Hz 720p
298 mp4   1280x720    60 │  257.47MiB  2830k https │ avc1.4d4020  2830k video only              720p60, mp4_dash
302 webm  1280x720    60 │  200.00MiB  2199k https │ vp9          2199k video only              720p60, webm_dash
299 mp4   1920x1080   60 │  466.62MiB  5130k https │ avc1.64002a  5130k video only              1080p60, mp4_dash
303 webm  1920x1080   60 │  357.91MiB  3935k https │ vp9          3935k video only              1080p60, webm_dash
308 webm  2560x1440   60 │    1.03GiB 11573k https │ vp9         11573k video only              1440p60, webm_dash
315 webm  3840x2160   60 │    2.32GiB 26119k https │ vp9         26119k video only              2160p60, webm_dash
```

**Comment by Logarithmus** [comment]
@pukkandan are the formats being throttled the same for all videos or differ?

**Comment by pukkandan** [comment]
Depends on video

**Comment by Logarithmus** [comment]
@pukkandan why would YouTube throttle only specific formats?

**Comment by pukkandan** [comment]
Youtube is throttling all formats. But our android fallback "unthrottles" most

**Comment by Gomam0n-afk** [comment]
> Already fixed 😃 [48416bc](https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8)

The problem persists for me. latest version (2022.01.21), video still downloads but in 720p only.

**Comment by pukkandan** [comment]
The fix is not released

>  video still downloads but in 720p only.

Sounds like you just dont have ffmpeg and not related to this issue

**Comment by dirkf** [comment]
And again (but problem video was extracted in yt-dlp master using the Android client with no diagnostic):
https://github.com/ytdl-org/youtube-dl/commit/187a48aee29847664e0c4cd80fe90c32e1fb334b

**Comment by pukkandan** [comment]
Can't reproduce
```
❯ yt-dlp --extractor-args youtube:player-client=web -v --force-over :ytrec --playlist-items 2
[debug] Command-line config: ['--ignore-config', '--extractor-args', 'youtube:player-client=web', '-v', '--force-over', ':ytrec', '--playlist-items', '2']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: dead84892
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [youtube:recommended] Extracting URL: :ytrec
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/feed/recommended
[youtube:tab] recommended: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/feed/recommended
[download] Downloading playlist: recommended
[youtube:tab] playlist recommended: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=5Eqb_-j3FDA
[youtube] 5Eqb_-j3FDA: Downloading webpage
[debug] Loading youtube-sigfuncs.js_c5a4daa1_105 from cache
[debug] Loading youtube-nsig.c5a4daa1 from cache
[debug] [youtube] Decrypted nsig J1dzlkuADD4NEkfZUaB => iBuihU54d9Fk_w
[debug] [youtube] Decrypted nsig ZeoMNuprobc07RgikXZ => s-g_vkgIK--P8g
[debug] Loading youtube-sigfuncs.js_c5a4daa1_101 from cache
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 5Eqb_-j3FDA: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr1---sn-gwpa-jv36.googlevideo.com/videoplayback?expire=1653435370&ei=iheNYq3aMMGTmgfjt5DACw&ip=49.37.231.138&id=o-AHifSl8ZdhVX16j3_tl3p3MSvY1o1IwSHVaSBXDnbNPm&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=AX&mm=31%2C29&mn=sn-gwpa-jv36%2Csn-gwpa-h55d&ms=au%2Crdu&mv=m&mvi=1&pl=20&initcwndbps=217500&spc=4ocVC-xt6UpLNWCPIoBFC9TwFNUV&vprv=1&mime=video%2Fwebm&ns=9KoKOAiaBw-EfUO3VHPU3DkG&gir=yes&clen=62312695&dur=276.360&lmt=1651335704129474&mt=1653413102&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5535434&n=s-g_vkgIK--P8g&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgHAIj8jbQUIq0Y0VfCEiQX8SFaIwJ4qqzgQQFcWrbYvwCIQCsC4zRkgwHhk7hbyB0V8QC6siAuUOd9Pk2LUd5r8urCQ%3D%3D&sig=AOq0QJ8wRQIgSZdAiVxUiBUaBxEXUs_7TxempiOZxi3SRF9_7yuIO3UCIQCIdCAqr8TuH1uFPQHlNOxgDUUdoWPJXP54tmdqPco4PA%3D%3D"
[debug] File locking is not supported on this platform. Proceeding without locking
[download] Destination: Coke Studio _ Season 14 _ Pasoori _ Ali Sethi x Shae Gill [5Eqb_-j3FDA].f248.webm
[download]  12.4% of 59.43MiB at    3.57MiB/s ETA 00:14Exception ignored in: <_io.FileIO name='Coke Studio _ Season 14 _ Pasoori _ Ali Sethi x Shae Gill [5Eqb_-j3FDA].f248.webm.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='Coke Studio _ Season 14 _ Pasoori _ Ali Sethi x Shae Gill [5Eqb_-j3FDA].f248.webm.part'>

ERROR: Interrupted by user
```

**Comment by dirkf** [comment]
No, apologies for the false alarm.

yt-dlp's `js_to_json()` returns a valid JSON string, presumably thanks to an improvement where `$` is added to the regexes for variables:
```
(Pdb) p js_to_json('[$o]')
'["$o"]'
(Pdb) p json.loads('["$o"]')
['$o']
```
yt-dl's version gets `'[$"o"]'` at the first step and then fails.

The new `js_to_json()` looks like a prime candidate for back-port, especially for nuxt.js hydration where the JSON is actually the value of a trivial function:
```
(function(/* long arg list */) { return {/* object with arg references */} })(/* long arg binding list */)
```
