### ISSUE TITLE
Can't --print "duration" for videos less than 1 second long.

### ISSUE THREAD

**Issue by dsluo** [yt-dlp/yt-dlp#2594]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I tested this with the following video, and also a reupload to gfycat. `ffprobe` reports that it's 0.3 seconds long.

* https://www.youtube.com/watch?v=GZ9ZBjtLoTg
* https://gfycat.com/liquidmajestichairstreakbutterfly

Interestingly, there's two different errors for gfycat and YouTube. 

Additionally, using `--print-json` works fine and the duration info is there and correct.

### Verbose log

```shell
$ yt-dlp https://www.youtube.com/watch?v=GZ9ZBjtLoTg --print duration -vU                       

[debug] Command-line config: ['https://www.youtube.com/watch?v=GZ9ZBjtLoTg', '--print', 'duration', '-vU'][debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0[debug] exe versions: ffmpeg 2022-01-30-git-1530b3f566-full_build-www.gyan.dev (setts), ffprobe 2022-01-30-git-1530b3f566-full_build-www.gyan.dev[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=GZ9ZBjtLoTg
[youtube] GZ9ZBjtLoTg: Downloading webpage
[youtube] GZ9ZBjtLoTg: Downloading android player API JSON
[youtube] GZ9ZBjtLoTg: Downloading player e06dea74
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = 0qScoCzPpdzAPhB7Ex ; player = https://www.youtube.com/s/player/e06dea74/player_ias.vflset/en_US/base.js
GZ9ZBjtLoTg: Traceback (most recent call last):
  File "yt_dlp\extractor\youtube.py", line 2412, in _decrypt_nsig
  File "yt_dlp\extractor\youtube.py", line 2433, in _extract_n_function
  File "yt_dlp\extractor\youtube.py", line 2421, in _extract_n_function_name
  File "yt_dlp\extractor\common.py", line 1186, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] GZ9ZBjtLoTg: Downloading 1 format(s): 315+251
1
```

```shell
$ yt-dlp https://gfycat.com/liquidmajestichairstreakbutterfly --print duration -vU  

[debug] Command-line config: ['https://gfycat.com/liquidmajestichairstreakbutterfly', '--print', 'duration', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2022-01-30-git-1530b3f566-full_build-www.gyan.dev (setts), ffprobe 2022-01-30-git-1530b3f566-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [Gfycat] Extracting URL: https://gfycat.com/liquidmajestichairstreakbutterfly
[Gfycat] liquidmajestichairstreakbutterfly: Downloading video info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] liquidmajestichairstreakbutterfly: Downloading 1 format(s): mp4
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1503, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2589, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2803, in process_info
  File "yt_dlp\YoutubeDL.py", line 2721, in __forced_printings
  File "yt_dlp\YoutubeDL.py", line 2691, in _forceprint
  File "yt_dlp\YoutubeDL.py", line 3484, in render_thumbnails_table
TypeError: 'NoneType' object is not iterable
```

**Comment by pukkandan** [comment]
Fixed in 88f23a18e0a0f5f18ed167b6a319c54255c5dd13
