### ISSUE TITLE
Support for https://telewebion.com/

### ISSUE THREAD

**Issue by ualaa1** [yt-dlp/yt-dlp#2598]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Iran

### Example URLs

Video: https://telewebion.com/episode/2752005

### Description

Most videos on the site are region-locked to Iran, but a few, such as this one, can be accessed internationally.
Yt-dlp download URL via Chrome's Inspect's Network tab is
https://sdma.telewebion.com/vod/_definst_//media_c/telewebion/salamat/2022-02-01/normalProgram/173854/file.mp4/chunk.m3u8?wmsAuthSign=aXNfZnJlZT0xJnNlcnZlcl90aW1lPTIvMi8yMDIyIDQ6NTI6MTAgQU0maGFzaF92YWx1ZT1zYlRaUDFObVJTOFMwek9vMUxEdGhnPT0mdmFsaWRtaW51dGVzPTYwMDA=&origin=st3.telewebion.com

### Verbose log

```shell
yt-dlp -vU "https://telewebion.com/episode/2752005"
[debug] Command-line config: ['-vU', 'https://telewebion.com/episode/2752005']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.9.0 (CPython 64bit) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [generic] Extracting URL: https://telewebion.com/episode/2752005
[generic] 2752005: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 2752005: Downloading webpage
[generic] 2752005: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://telewebion.com/episode/2752005
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1367, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1437, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3966, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://telewebion.com/episode/2752005
```

**Comment by HobbyistDev** [comment]
As far i can see from OP link, the OP link redirect to new episode id in https://telewebion.com/episode/0x1bec698. The episode detail we can get from `https://graph.telewebion.com/graphql?queryid=<queryId>` with POST method. Here's the requests data from the graphql url:
```json
{
  "operationName": "getEpisodeDetail",
  "variables": {
    "EpisodeId": "0x28e0ab5",
    "Copyright": false
  },
  "query": "query getEpisodeDetail($EpisodeId: [ID!]) @cacheControl(maxAge: 60) {\n  queryEpisode(filter: {EpisodeID: $EpisodeId}, first: 1) {\n    title\n    enable\n    program {\n      ProgramID\n      title\n      copyright\n      ProgramID\n      title\n      cover\n      id\n      enable\n      is_singleton\n      tags {\n        __typename\n        TagID\n        name\n      }\n    }\n    EpisodeID\n    image\n    id\n    view_count\n    show_time\n    description\n    page_description\n    is_clip\n    is_hot\n    duration\n    title\n    cover\n    file_path\n    file_size\n    started_at\n    ended_at\n    created_at\n    thumbnail_time\n    copyright\n    enable\n    downloadable\n    download_count\n    exclude_periods {\n      start_at\n      end_at\n    }\n    channel {\n      ChannelID\n      name\n      descriptor\n      image_name\n    }\n    tags {\n      __typename\n      TagID\n      name\n    }\n    episode_files {\n      EpisodeFileID\n      size\n      variant\n    }\n  }\n}\n"
}
```
And here's the response (some field reformatted to `????` because non ascii) :
```json
{
  "data": {
    "queryEpisode": [
      {
        "title": "???? ????? ???????",
        "enable": true,
        "program": {
          "ProgramID": "0x1b27330",
          "title": "?????? ???? ?????",
          "copyright": false,
          "cover": null,
          "id": 54304,
          "enable": true,
          "is_singleton": false,
          "tags": [
            {
              "__typename": "Tag",
              "TagID": "0x1b1fb48",
              "name": "??????"
            }
          ]
        },
        "EpisodeID": "0x1bec698",
        "image": "MzNiYWE3M2ViNDJjZThiMjYzYTIzNzk3MTMxMzgxMzIyZmJiYWI2ZThjMDcyNzJiNjJlNjMwMWIyZmVhNWViNQ",
        "id": 2752005,
        "view_count": 1025,
        "show_time": "2022-02-01T17:38:00Z",
        "description": "",
        "page_description": null,
        "is_clip": false,
        "is_hot": "false",
        "duration": 3840,
        "cover": null,
        "file_path": "/telewebion/salamat/2022-02-01/normalProgram/173854/file.mp4",
        "file_size": "14.7",
        "started_at": "2022-02-01T17:38:00Z",
        "ended_at": "2022-02-01T18:42:00Z",
        "created_at": "2022-02-01T09:31:43Z",
        "thumbnail_time": null,
        "copyright": false,
        "downloadable": null,
        "download_count": null,
        "exclude_periods": [],
        "channel": {
          "ChannelID": "0x1b1a721",
          "name": "?????",
          "descriptor": "salamat",
          "image_name": "b24edd34-d2ef-4c18-9f95-7978c719ead6"
        },
        "tags": [
          {
            "__typename": "Tag",
            "TagID": "0x1b1fb48",
            "name": "??????"
          }
        ],
        "episode_files": []
      }
    ]
  }
}
```
And the we can request to `https://cdna.telewebion.com/<channel_descriptor>/episode/<episode_id>/playlist.m3u8`

From https://telewebion.com/main.502f4af227d30605.js, i found the query id seems related sha1. The `queryId` will be different from one episode to another. Here's the snippet i found that related to `queryId`:
```js
handleBodyIn(o) {
	if ("https://graph.telewebion.com/graphql" === (null == o ? void 0 : o.url)) {
	    const g = Oe("sha1").update(JSON.stringify(o.body)).digest("hex");
	    let A = null;
	    const k = "isUserLikeEpisode" === o.body.operationName || "LikeEpisode" === o.body.operationName || "UnLikeEpisode" === o.body.operationName;
	    this.generalService.isPlatformBrowser && (A = this.generalService.getCookieValue(this.generalService.configs.variableNames.accessToken) !== this.generalService.configs.variableNames.nullCookie ? this.generalService.getCookieValue(this.generalService.configs.variableNames.accessToken) : null), o = o.clone({
	    headers: k && A ? o.headers.append("X-Auth-Token", A) : o.headers,
	    params: o.params.set("queryid", g)
				})
			}
	    return o
```

Here's the log of yt-dlp downloading the m3u8:
```
> yt-dlp -vU "https://cdna.telewebion.com/salamat/episode/0x1bec698/playlist.m3u8"
[debug] Command-line config: ['-vU', 'https://cdna.telewebion.com/salamat/episode/0x1bec698/playlist.m3u8']
[debug] Portable config "~\yt-dlp\yt-dlp.conf": ['-v', '--netrc-location', '~\yt-dlp.netrc', '-f', 'bv+ba/b', '--compat-options', 'format-sort', '--embed-metadata', '--embed-subs', '--sub-langs', 'all', '--console-title', '--downloader', 'aria2c']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Compatibility options: format-sort
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://cdna.telewebion.com/salamat/episode/0x1bec698/playlist.m3u8
[generic] playlist: Requesting header
[debug] Identified a direct video link
[generic] playlist: Downloading m3u8 information
[debug] Sort order given by user: hasaud, lang, quality, tbr, filesize, vbr, height, width, proto, vext, abr, aext, fps, fs_approx, source, id
[debug] Formats sorted by: hasvid, ie_pref, hasaud, lang, quality, tbr, filesize, vbr, height, width, proto, vext, abr, aext, fps, fs_approx, source, id, res, hdr:12(7), vcodec:vp9.2(10), acodec, asr
[info] playlist: Downloading 1 format(s): 0
[debug] Invoking hlsnative downloader on "https://cdna.telewebion.com/salamat/episode/0x1bec698/playlist.m3u8"
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 25
[download] Destination: playlist [playlist].mp4
[debug] File locking is not supported. Proceeding without locking
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--http-accept-gzip=true" "--file-allocation=none" -x16 -j16 -s16 "--allow-overwrite=true" "--allow-piece-length-change=true" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" "--auto-file-renaming=false" "--file-allocation=none" "--uri-selector=inorder" -i "playlist [playlist].mp4.part.frag.urls"
[aria2c] Downloaded 16529336 bytes :199KiB]
[download] 100% of 15.76MiB in 00:14
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:playlist [playlist].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "playlist [playlist].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:playlist [playlist].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:playlist [playlist].temp.mp4"
[EmbedSubtitle] There aren't any subtitles to embed
[Metadata] Adding metadata to "playlist [playlist].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:playlist [playlist].mp4" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=playlist" -metadata "purl=https://cdna.telewebion.com/salamat/episode/0x1bec698/playlist.m3u8" -metadata "comment=https://cdna.telewebion.com/salamat/episode/0x1bec698/playlist.m3u8" -movflags "+faststart" "file:playlist [playlist].temp.mp4"
```

**Comment by afsharsafavi** [comment]
Hello
Is it possible to support this site (telewebion.com)?

`yt-dlp https://telewebion.com/episode/0x285dc1c -v
[debug] Command-line config: ['https://telewebion.com/episode/0x285dc1c', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://telewebion.com/episode/0x285dc1c
[generic] 0x285dc1c: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 0x285dc1c: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://telewebion.com/episode/0x285dc1c
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1442, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3077, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://telewebion.com/episode/0x285dc1c

`

**Comment by rezad1393** [comment]
I think the telewebion extractor has a wrong wildcard for urls.
it is :
`     _VALID_URL = r'https?://(?:www\.)?telewebion\.com/**#!**/episode/(?P<id>\d+)'`

but that bold part is not needed.
so maybe just deleting that fixes this?

**Comment by bashonly** [comment]
> so maybe just deleting that fixes this?

The `_VALID_URL` should be updated to support the new URL format, but this alone won't fix it since the API has completely changed and the API hostnames used by the extractor no longer exist. [HobbyistDev's comment](https://github.com/yt-dlp/yt-dlp/issues/2598#issuecomment-1186002910) is an outline of what else needs to be done to fix the extractor

**Comment by mimvahedi** [comment]
Fixed in youtube-dl

**Comment by rezad1393** [comment]
> Fixed in youtube-dl

where?

**Comment by bashonly** [comment]
https://github.com/ytdl-org/youtube-dl/commit/c62936a5f20d941e67d566e74a7c3fc8d8188f7a
