### ISSUE TITLE
Downloading from Philo

### ISSUE THREAD

**Issue by YoshQ** [yt-dlp/yt-dlp#2603]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

_What the problem is_
- Unable to download from MyLifetime.com using Philo cable provider login for locked videos, but able to download unlocked videos requiring no login. Also I did not receive a new auth code in my email when it was requested from the command line, so I used the last auth code I had chronologically received while using the website. This may be part of the problem. I will say also that when simply specifying the MSO with --ap-mso Philo with no --ap-username, I get the message "This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials." as if I had specified no MSO at all. 
_How it could be fixed_
 - Maybe instead of asking for a password when Philo is the selected MSO, skip right to the part about asking for the auth code. Maybe when specifying Philo as the MSO, the username and auth code are asked for by prompt instead of informing the user that a cable login is required.

### Verbose log

```shell
yt-dlp.exe --embed-subs --ap-mso Philo --ap-username yoshq0@gmail.com --verbose -vU "https://play.mylifetime.com/shows/married-at-first-sight-second-chances/season-1/episode-1"
[debug] Command-line config: ['--embed-subs', '--ap-mso', 'Philo', '--ap-username', 'PRIVATE', '--verbose', '-vU', 'https://play.mylifetime.com/shows/married-at-first-sight-second-chances/season-1/episode-1']
Type TV provider account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg n4.3.1-26-gca55240b8c, ffprobe n4.3.1-26-gca55240b8c
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [aenetworks] Extracting URL: https://play.mylifetime.com/shows/married-at-first-sight-second-chances/season-1/episode-1
[aenetworks] /shows/married-at-first-sight-second-chances/season-1/episode-1: Downloading JSON metadata
[aenetworks] 930297411795: Downloading JSON metadata
[aenetworks] 930297411795: Downloading Provider Redirect Page
[aenetworks] 930297411795: Requesting auth code
Type auth code you have received [Return]:
[aenetworks] 930297411795: Submitting token
[aenetworks] 930297411795: Confirming Philo Login
ERROR: [aenetworks] shows/married-at-first-sight-second-chances/season-1/episode-1: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\aenetworks.py", line 173, in _real_extract
  File "yt_dlp\extractor\aenetworks.py", line 90, in _extract_aetn_info
  File "yt_dlp\extractor\adobepass.py", line 1511, in _extract_mvpd_auth
  File "yt_dlp\extractor\adobepass.py", line 1391, in post_form
  File "yt_dlp\extractor\common.py", line 1195, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1186, in _search_regex
```

**Comment by pukkandan** [comment]
> Maybe instead of asking for a password when Philo is the selected MSO, skip right to the part about asking for the auth code. (I just entered the auth code for both since Philo doesn't use passwords)

You can just pass an empty password in the cmd. Eg: `--ap-password ""`

> Maybe when specifying Philo as the MSO, the username and auth code are asked for by prompt instead of informing the user that a cable login is required.

Usename must always be given in cmd and not by prompt. Password and auth code will be asked by prompt

> Also I did not receive a new auth code in my email when it was requested from the command line, so I used the last auth code I had chronologically received while using the website. This may be part of the problem.

Does this issue reproducibly happen?

**Comment by YoshQ** [comment]
> > Maybe instead of asking for a password when Philo is the selected MSO, skip right to the part about asking for the auth code. (I just entered the auth code for both since Philo doesn't use passwords)
> 
> You can just pass an empty password in the cmd. Eg: `--ap-password ""`
Okay, I just tried doing that and it had the same error of requiring a cable login.
> > Also I did not receive a new auth code in my email when it was requested from the command line, so I used the last auth code I had chronologically received while using the website. This may be part of the problem.
> 
> Does this issue reproducibly happen?
Yes, and I should note that the auth code prompt is coming after the password prompt, to which I entered the auth code as well (one I had received previously and not as part of this process).

**Comment by franzenel** [comment]
I am trying to download a locked video from History.com using my Philo account. I never get an email with the PIN to log in. 

C:\Users\Erik\Downloads>yt-dlp --ap-mso Philo --ap-username Private --ap-password test https://play.history.com/shows/theodore-roosevelt/season-1/episode-2
[aenetworks] /shows/theodore-roosevelt/season-1/episode-2: Downloading JSON metadata
[aenetworks] 2036469315764: Downloading JSON metadata
[aenetworks] 2036469315764: Downloading Provider Redirect Page
[aenetworks] 2036469315764: Requesting auth code
Type auth code you have received [Return]:
[aenetworks] 2036469315764: Submitting token
[aenetworks] 2036469315764: Confirming Philo Login
ERROR: [aenetworks] shows/theodore-roosevelt/season-1/episode-2: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by Aniruddh-J** [comment]
I'll look into it this weekend.

**Comment by scarng63** [comment]
I tried today with username as my phone number (can be either phone or email).  Here are my logs:
`D:\My Video\yt_dlp>yt-dlp --ap-mso Philo --ap-username ########## --ap-password "" --verbose https://www.philo.com/player/player/recording/UmVjb3JkaW5nOjYwODU0ODg5OTg5NTE0OTMzNQ
[debug] Command-line config: ['--ap-mso', 'Philo', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--verbose', 'https://www.philo.com/player/player/recording/UmVjb3JkaW5nOjYwODU0ODg5OTg5NTE0OTMzNQ']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version **2022.07.18** [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev (setts), ffprobe 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.philo.com/player/player/recording/UmVjb3JkaW5nOjYwODU0ODg5OTg5NTE0OTMzNQ
[generic] UmVjb3JkaW5nOjYwODU0ODg5OTg5NTE0OTMzNQ: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] UmVjb3JkaW5nOjYwODU0ODg5OTg5NTE0OTMzNQ: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.philo.com/player/player/recording/UmVjb3JkaW5nOjYwODU0ODg5OTg5NTE0OTMzNQ
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
    raise
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
    additional_urls = [additional_urls]
  File "yt_dlp\extractor\common.py", line 644, in extract
    and self._GEO_BYPASS
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.philo.com/player/player/recording/UmVjb3JkaW5nOjYwODU0ODg5OTg5NTE0OTMzNQ`

**Comment by Aniruddh-J** [comment]
This is not the extractor for Philo. It adds support to authenticate on the website that supports Philo MSO. Philo's player uses DRM-protected content, so extracting videos from Philo's website would be impossible.

**Comment by Aniruddh-J** [comment]
@jlick Is this MSO still working for you?

**Comment by scarng63** [comment]
No not working I was just providing my log.

**Comment by jlick** [comment]
> @jlick Is this MSO still working for you?

No, something stopped working maybe 2 months ago.

**Comment by TheGrimKeeper** [comment]
I was able to download something from this site about 2 weeks ago, and I'm almost certain I used --cookies-from-browser (I definitely didn't use --ap-mso as this hasn't worked for me in a while with Philo).  But I tried to grab a couple of things over the weekend and --cookies-from-browser no longer functioned.  So something with this site may have changed recently.

**Comment by apassiou** [comment]
Its been 2 years, still no way to download with Philo credentials?

**Comment by exeljb** [comment]
I'm guessing not...I'm not able to get it to work.
```
Temp Files % yt-dlp -S 'res:720' "https://watch.history.com/shows/in-search-of-aliens/season-1/episode-1"  --ap-mso Philo --ap-username #########  --verbose -vU           
[debug] Command-line config: ['-S', 'res:720', 'https://watch.history.com/shows/in-search-of-aliens/season-1/episode-1', '--ap-mso', 'Philo', '--ap-username', 'PRIVATE', '--verbose', '-vU']
Type TV provider account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (pip)
[debug] Python 3.12.6 (CPython arm64 64bit) - macOS-15.0.1-arm64-arm-64bit (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.09.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.09.27 from yt-dlp/yt-dlp)
[aenetworks] Extracting URL: https://watch.history.com/shows/in-search-of-aliens/season-1/episode-1
[aenetworks] /shows/in-search-of-aliens/season-1/episode-1: Downloading JSON metadata
[aenetworks] 312126531636: Downloading JSON metadata
ERROR: [aenetworks] shows/in-search-of-aliens/season-1/episode-1: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
  File "/opt/homebrew/Cellar/yt-dlp/2024.9.27/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.9.27/libexec/lib/python3.12/site-packages/yt_dlp/extractor/aenetworks.py", line 200, in _real_extract
    return self._extract_aetn_info(domain, 'canonical', '/' + canonical, url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.9.27/libexec/lib/python3.12/site-packages/yt_dlp/extractor/aenetworks.py", line 97, in _extract_aetn_info
    auth = self._extract_mvpd_auth(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.9.27/libexec/lib/python3.12/site-packages/yt_dlp/extractor/adobepass.py", line 1445, in _extract_mvpd_auth
    raise_mvpd_required()
  File "/opt/homebrew/Cellar/yt-dlp/2024.9.27/libexec/lib/python3.12/site-packages/yt_dlp/extractor/adobepass.py", line 1406, in raise_mvpd_required
    raise ExtractorError(

**Comment by Aniruddh-J** [comment]
Unfortunately, I don't have access to Philo anymore.

**Comment by Sipherdrakon** [comment]
Maybe best to change the title as this is confusing people that you are trying to specifically download content from philo instead of an issue with the adobepass mso. But either way it won't even load up the redirect anymore with a 451 error. so might be time to either recode philo's mso or scrap it.

**Comment by Aniruddh-J** [comment]
Thanks @Sipherdrakon, you made it work again. I recently signed up for Philo again yesterday, planning to work on this, and it turned out you already pushed a working fork.
