### ISSUE TITLE
[Broken] Francetvinfo.tv RegexNotFoundError: Unable to extract video id

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#261]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
./yt-dlp -v -F https://www.francetvinfo.fr/sante/maladie/coronavirus/covid-19-en-inde-une-situation-catastrophique-a-new-dehli_4381095.html 
[debug] Command-line config: ['-v', '-F', 'https://www.francetvinfo.fr/sante/maladie/coronavirus/covid-19-en-inde-une-situation-catastrophique-a-new-dehli_4381095.html']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.22 (zip)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.9.1 (CPython 64bit) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[francetvinfo.fr] covid-19-en-inde-une-situation-catastrophique-a-new-dehli_4381095: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/sy/Downloads/yt-dlp-master/./yt-dlp/yt_dlp/YoutubeDL.py", line 1059, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sy/Downloads/yt-dlp-master/./yt-dlp/yt_dlp/YoutubeDL.py", line 1080, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/sy/Downloads/yt-dlp-master/./yt-dlp/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/Users/sy/Downloads/yt-dlp-master/./yt-dlp/yt_dlp/extractor/francetv.py", line 400, in _real_extract
    video_id = self._search_regex(
  File "/Users/sy/Downloads/yt-dlp-master/./yt-dlp/yt_dlp/extractor/common.py", line 1057, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Dear @pukkandan,
I've recently noticed your project and found some amazing and invaluable features! Great job!
For over a month, I'm struggling with Francetvinfo videos and spent countless hours to fix the regex (not much of a programmer here, can manage some scripts)... Posted this issue in the original ytdl rep, but does not seem to get any feedback.. https://github.com/ytdl-org/youtube-dl/issues/28792 
Maybe you can help with this. Maybe solution is something similar to this fix https://github.com/ytdl-org/youtube-dl/commit/287e50b56b4c71da8fd0c3ffdeca9bff5ab0b005

That fix works for links like this:
https://france3-regions.francetvinfo.fr/nouvelle-aquitaine/gironde/ampute-apres-un-accident-un-viticulteur-du-medoc-en-litige-contre-un-assureur-pour-sauver-son-domaine-1982857.html

Here are a couple test links:
https://www.francetvinfo.fr/sante/maladie/coronavirus/vaccin/covid-19-la-guyane-touchee-de-plein-fouet-par-le-variant-bresilien_4373671.html

If there's anything I can help with, please let me know. Appreciate your time and help.

**Comment by someziggyman** [comment]
Confirmed it works! You are brilliant! thank you so much!
