### ISSUE TITLE
Unable to download video with Chinese characters from YouTube

### ISSUE THREAD

**Issue by Dr-Noob** [yt-dlp/yt-dlp#2617]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Downloading a video with Chinese characters (or some strange characters, I'm not sure) from YouTube fails. You can find the problematic video link in the log.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=u-xS-dkz3a0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.15.11-arch2-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=u-xS-dkz3a0
[youtube] u-xS-dkz3a0: Downloading webpage
[youtube] u-xS-dkz3a0: Downloading android player API JSON
[youtube] u-xS-dkz3a0: Downloading player cdb8d439
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = KvJpc7mSaprOLqR ; player = https://www.youtube.com/s/player/cdb8d439/player_ias.vflset/en_US/base.js
u-xS-dkz3a0: Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2421, in _extract_n_function_name
    return self._search_regex(
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] u-xS-dkz3a0: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://rr2---sn-jxnj5-cjol.googlevideo.com/videoplayback?expire=1643903189&ei=daT7YZe1I92CvdIPhYu00Ao&ip=155.54.205.72&id=o-AHXFR1e5xP5ehOvDnAewPHkJzCxNF_R9cggWx2B7jAt0&itag=303&source=youtube&requiressl=yes&mh=bz&mm=31%2C29&mn=sn-jxnj5-cjol%2Csn-h5q7kned&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=16&pcm2=no&initcwndbps=56250&vprv=1&mime=video%2Fwebm&gir=yes&clen=333851441&dur=1079.640&lmt=1626976503827261&mt=1643881260&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALv9p3448H8BgA9CpjOaYj-hZMzz8zGhcKLzIPHuG3nZAiEAw4jftcxpHiJaRmvjgb6AWpuOZe74mlSX04yUg4db7aM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALMckkYLZiaEa5eZX1qvvIMHLmnOdXZEMojiV8jz-MyrAiApwrexCwFLV2eaH52LkfJWQ42z0KtA3te9WvNIL9ZtHw%3D%3D"
[download] Got file access error. Retrying (attempt 1 of 10) ...
[download] Got file access error. Retrying (attempt 2 of 10) ...
[download] Got file access error. Retrying (attempt 3 of 10) ...
[download] Got file access error. Retrying (attempt 4 of 10) ...
[download] Got file access error. Retrying (attempt 5 of 10) ...
[download] Got file access error. Retrying (attempt 6 of 10) ...
[download] Got file access error. Retrying (attempt 7 of 10) ...
[download] Got file access error. Retrying (attempt 8 of 10) ...
[download] Got file access error. Retrying (attempt 9 of 10) ...
[download] Got file access error. Retrying (attempt 10 of 10) ...
ERROR: unable to open for writing: [Errno 13] Permission denied: '我们中国人的开门七件事，柴米油盐酱醋茶 Firewood, rice, oil, salt, soy sauce, vinegar, and tea丨Liziqi Channel [u-xS-dkz3a0].f303.webm.part'
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 218, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 669, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: '我们中国人的开门七件事，柴米油盐酱醋茶 Firewood, rice, oil, salt, soy sauce, vinegar, and tea丨Liziqi Channel [u-xS-dkz3a0].f303.webm.part'


[debug] Invoking downloader on "https://rr2---sn-jxnj5-cjol.googlevideo.com/videoplayback?expire=1643903189&ei=daT7YZe1I92CvdIPhYu00Ao&ip=155.54.205.72&id=o-AHXFR1e5xP5ehOvDnAewPHkJzCxNF_R9cggWx2B7jAt0&itag=251&source=youtube&requiressl=yes&mh=bz&mm=31%2C29&mn=sn-jxnj5-cjol%2Csn-h5q7kned&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=16&pcm2=no&initcwndbps=56250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=17608088&dur=1079.681&lmt=1626535160207483&mt=1643881260&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAP49htbGDvzixHwc00P8PD46tmfvee0vBrARUk_Wvdz_AiAFt45YV3fy7bb1BqQxZjik71mjRLaiDCBq0gHQdpOa8w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALMckkYLZiaEa5eZX1qvvIMHLmnOdXZEMojiV8jz-MyrAiApwrexCwFLV2eaH52LkfJWQ42z0KtA3te9WvNIL9ZtHw%3D%3D"
[download] Got file access error. Retrying (attempt 1 of 10) ...
[download] Got file access error. Retrying (attempt 2 of 10) ...
[download] Got file access error. Retrying (attempt 3 of 10) ...
[download] Got file access error. Retrying (attempt 4 of 10) ...
[download] Got file access error. Retrying (attempt 5 of 10) ...
[download] Got file access error. Retrying (attempt 6 of 10) ...
[download] Got file access error. Retrying (attempt 7 of 10) ...
[download] Got file access error. Retrying (attempt 8 of 10) ...
[download] Got file access error. Retrying (attempt 9 of 10) ...
[download] Got file access error. Retrying (attempt 10 of 10) ...
ERROR: unable to open for writing: [Errno 13] Permission denied: '我们中国人的开门七件事，柴米油盐酱醋茶 Firewood, rice, oil, salt, soy sauce, vinegar, and tea丨Liziqi Channel [u-xS-dkz3a0].f251.webm.part'
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 218, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 669, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: '我们中国人的开门七件事，柴米油盐酱醋茶 Firewood, rice, oil, salt, soy sauce, vinegar, and tea丨Liziqi Channel [u-xS-dkz3a0].f251.webm.part'
```
```

**Comment by dirkf** [comment]
WFM Linux x86:
*  yt-dlp HEAD, Python 3.9
*  yt-dl HEAD, Python 3.5
*  yt-dl HEAD, Python 2.7.

Can you write other files/ yt-dlp other links to that location?

**Comment by Dr-Noob** [comment]
Yeah, my bad, it was just a permissions problem. 

The first part of the message asking to post the output in the issues webpage got me. But maybe this warning message (`RegexNotFoundError: Unable to extract Initial JS player n function name`) is relevant because there is something wrong?

**Comment by dirkf** [comment]
Yes, but already reported and fixed.
