### ISSUE TITLE
RegexNotFoundError: Unable to extract JS player n function (link still generates)

### ISSUE THREAD

**Issue by WeezyVR** [yt-dlp/yt-dlp#2618]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

 yt-dlp throws the following error: `yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name`
 
 A link still generates.

### Verbose log

```shell
[debug] Command-line config: ['q0IOUfvp6ws', '--user-agent', '', '--extractor-args', 'youtube:player-client=web', '-S', 'vcodec:h264', '-f', 'bestvideo[height<=1440][ext=mp4]', '--get-url', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-4.15.0-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: q0IOUfvp6ws
[youtube] q0IOUfvp6ws: Downloading webpage
[youtube] q0IOUfvp6ws: Downloading player cdb8d439
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = 8KuiZdtUtFr-bBQ ; player = https://www.youtube.com/s/player/cdb8d439/player_ias.vflset/en_US/base.js
q0IOUfvp6ws: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 2421, in _extract_n_function_name
    return self._search_regex(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = slznSjIpxG2IY6l ; player = https://www.youtube.com/s/player/cdb8d439/player_ias.vflset/en_US/base.js
q0IOUfvp6ws: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 2421, in _extract_n_function_name
    return self._search_regex(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by user: vcodec:h264
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vcodec:h264(7), quality, res, fps, hdr:12(7), source, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] q0IOUfvp6ws: Downloading 1 format(s): 299
```

**Comment by polyspastos** [comment]
duplicate of which one? thanks

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues?q=%22Unable+to+extract+JS+player+n+function
