### ISSUE TITLE
Unable to download YouTube video

### ISSUE THREAD

**Issue by locriacyber** [yt-dlp/yt-dlp#2619]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

I haven't used yt-dlp in a while. I was trying to download subtitle of a video from YouTube, but yt-dlp is not working.

### Verbose log

```shell
> ~/Downloads/yt-dlp --verbose --sub-langs all "https://www.youtube.com/watch?v=ZYj4NkeGPdM" --skip-download
[debug] Command-line config: ['--verbose', '--sub-langs', 'all', 'https://www.youtube.com/watch?v=ZYj4NkeGPdM', '--skip-download']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0] (zip)
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.4.156-1.fc25.qubes.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=ZYj4NkeGPdM
[youtube] ZYj4NkeGPdM: Downloading webpage
[youtube] ZYj4NkeGPdM: Downloading android player API JSON
[youtube] ZYj4NkeGPdM: Downloading player cdb8d439
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = 4jC6LjCHZTgVrux ; player = https://www.youtube.com/s/player/cdb8d439/player_ias.vflset/en_US/base.js
ZYj4NkeGPdM: Traceback (most recent call last):
  File "/home/user/Downloads/yt-dlp/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/user/Downloads/yt-dlp/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/home/user/Downloads/yt-dlp/yt_dlp/extractor/youtube.py", line 2421, in _extract_n_function_name
    return self._search_regex(
  File "/home/user/Downloads/yt-dlp/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ZYj4NkeGPdM: Downloading 1 format(s): 303+251


==============================
```

**Comment by Lesmiscore** [comment]
> I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=sort%3Aupdated-desc) for similar issues including closed ones. DO NOT post duplicates

You didn't. Also you can still download.
