### ISSUE TITLE
[Broken] YouTube - Unable to extract yt initial data

### ISSUE THREAD

**Issue by Zirro** [yt-dlp/yt-dlp#263]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

ERROR: Unable to extract yt initial data; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1059, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1080, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 3506, in _real_extract
    webpage, data = self._extract_webpage(url, item_id)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 3465, in _extract_webpage
    data = self._extract_yt_initial_data(item_id, webpage)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 322, in _extract_yt_initial_data
    self._search_regex(
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1057, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

[This URL](https://www.youtube.com/c/OkonomiyakiVtuberSUBEspañol/videos) results in the error "Unable to extract yt initial data". It seems to happen specifically for URLs containing the username - not with the `/channel/` URL - presumably due to the special character it contains.

**Comment by colethedj** [comment]
Works for me?
```
yt-dlp https://www.youtube.com/c/OkonomiyakiVtuberSUBEspa%C3%B1ol/videos --verbose --flat-playlist                                                                              
[debug] Command-line config: ['https://www.youtube.com/c/OkonomiyakiVtuberSUBEspa%C3%B1ol/videos', '--verbose', '--flat-playlist']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.22 
[debug] Python version 3.9.3 (CPython 64bit) - Linux-5.10.30-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] OkonomiyakiVtuberSUBEspa%C3%B1ol: Downloading webpage
[download] Downloading playlist: Aiko Okonomiyaki [ Vtuber SUB Español ] - Videos
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 1: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 2: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 3: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 4: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 5: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 6: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 7: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 8: Downloading API JSON
```
Can you post complete verbose output

**Comment by Zirro** [comment]
The URL in your prompt has already been encoded (`%C3%B1`). The problem occurs when the "ñ" character is present in the URL.

**Comment by pukkandan** [comment]
Give the ENTIRE verbose output. Don't cherrypick

**Comment by Zirro** [comment]
```
yt-dlp 'https://www.youtube.com/c/OkonomiyakiVtuberSUBEspañol/videos' --verbose
[debug] Command-line config: ['https://www.youtube.com/c/OkonomiyakiVtuberSUBEspañol/videos', '--verbose']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.22
[debug] Python version 3.9.4 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] OkonomiyakiVtuberSUBEspañol: Downloading webpage
ERROR: Unable to extract yt initial data; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1059, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1080, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 3506, in _real_extract
    webpage, data = self._extract_webpage(url, item_id)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 3465, in _extract_webpage
    data = self._extract_yt_initial_data(item_id, webpage)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 322, in _extract_yt_initial_data
    self._search_regex(
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1057, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
I am unable to reproduce the issue. Can you attach the `.dump` file(s) created when using `--write-pages`

```
$ yt-dlp "https://www.youtube.com/c/OkonomiyakiVtuberSUBEspañol/videos" -v
[debug] Command-line config: ['https://www.youtube.com/c/OkonomiyakiVtuberSUBEspañol/videos', '-v']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.04.22 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: bbed5763f1
[debug] Python version 3.9.2 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.0.1, ffprobe N-101553-g434b626b7a
[debug] Proxy map: {}
[youtube:tab] OkonomiyakiVtuberSUBEspañol: Downloading webpage
[download] Downloading playlist: Aiko Okonomiyaki [ Vtuber SUB Español ] - Videos
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 1: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 2: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 3: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 4: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 5: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 6: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 7: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 8: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 9: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 10: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 11: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 12: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 13: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 14: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 15: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 16: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 17: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 18: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 19: Downloading API JSON
[youtube:tab] UCPH715EHo1FhZcneh383m4A page 20: Downloading API JSON
[youtube:tab] playlist Aiko Okonomiyaki [ Vtuber SUB Español ] - Videos: Downloading 612 videos
[download] Downloading video 1 of 612
[youtube] D5gfeLyjaqg: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] D5gfeLyjaqg: Downloading format(s) 247+251
[debug] Invoking downloader on 'https://r2---sn-gwpa-cagk.googlevideo.com/videoplayback?expire=1619228301&ei=LSKDYJ-MGb-AjuMPkIeZyA0&ip=49.37.189.14&id=o-ACg0Jqd3iRpMluZT8D9KeAqXUmimA_ETU99ffBW0BOKT&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=Vw&mm=31%2C29&mn=sn-gwpa-cagk%2Csn-gwpa-h55l&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=20&initcwndbps=380000&vprv=1&mime=video%2Fwebm&ns=TVxczMbid1O8k8Toh4iEeWMF&gir=yes&clen=15683454&dur=129.493&lmt=1619196970982484&mt=1619206369&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5432434&n=rFd2WDfBXdDUHTltw9&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANpu3dXvfaq-mvT-9A0Sivv8q4V0oaosXz54M_KLeYizAiAJAaNmtEqPeKTxU0imV9XvjY8zaX5GkCde_XdX28I30g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgZx2lLY4R_s0erUrSibIHDsIFPlzS3STWRfl8wMIoSaQCIQC9xByvZPaSFpN8k0D48-pmVTpkB1678ElYwGGa73419w%3D%3D'
[download] Resuming download at byte 4193280

ERROR: Interrupted by user
```

**Comment by Zirro** [comment]
[OkonomiyakiVtuberSUBEspanol_https_-_consent.youtube.com_mcontinue=https%3A%2F%2Fwww.youtube.com%2Fc%2FOkonomiyakiVtuberSUBEspa%25C3%25B1ol%2Fvideos_gl=RO_m=0_pc=yt_uxe=23983172_hl=en_src=1.log](https://github.com/yt-dlp/yt-dlp/files/6368707/OkonomiyakiVtuberSUBEspanol_https_-_consent.youtube.com_mcontinue.https.3A.2F.2Fwww.youtube.com.2Fc.2FOkonomiyakiVtuberSUBEspa.25C3.25B1ol.2Fvideos_gl.RO_m.0_pc.yt_uxe.23983172_hl.en_src.1.log)

It looks like it gets stuck on the privacy/cookie consent page (which is EU-specific I think - my current VPN address puts me in Romania) when attempting to redirect to this particular URL. I can confirm that the latest youtube-dl version also has the same problem when given this URL, though it seems to work fine in browsers. Providing my own cookies with the `--cookies` flag also makes no difference.

I decided to include `--print-traffic` as well since the issue could potentially be found within the headers:

```
yt-dlp 'https://www.youtube.com/c/OkonomiyakiVtuberSUBEspañol/videos' --verbose --write-pages --print-traffic
[debug] Command-line config: ['https://www.youtube.com/c/OkonomiyakiVtuberSUBEspañol/videos', '--verbose', '--write-pages', '--print-traffic']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.22
[debug] Python version 3.9.4 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] OkonomiyakiVtuberSUBEspañol: Downloading webpage
send: b'GET /c/OkonomiyakiVtuberSUBEspa%C3%B1ol/videos HTTP/1.1\r\nHost: www.youtube.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3528.0 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 302 Found\r\n'
header: Content-Type: application/binary
header: X-Content-Type-Options: nosniff
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Fri, 23 Apr 2021 21:57:36 GMT
header: Location: https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fc%2FOkonomiyakiVtuberSUBEspa%25C3%25B1ol%2Fvideos&gl=RO&m=0&pc=yt&uxe=23983172&hl=en&src=1
header: X-Frame-Options: SAMEORIGIN
header: Strict-Transport-Security: max-age=31536000
header: permissions-policy: ch-ua-full-version=*, ch-ua-platform=*, ch-ua-platform-version=*, ch-ua-arch=*, ch-ua-model=*
header: Server: ESF
header: Content-Length: 0
header: X-XSS-Protection: 0
header: Set-Cookie: CONSENT=PENDING+270; expires=Fri, 01-Jan-2038 00:00:00 GMT; path=/; domain=.youtube.com
header: P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
header: Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
send: b'GET /m?continue=https%3A%2F%2Fwww.youtube.com%2Fc%2FOkonomiyakiVtuberSUBEspa%25C3%25B1ol%2Fvideos&gl=RO&m=0&pc=yt&uxe=23983172&hl=en&src=1 HTTP/1.1\r\nHost: consent.youtube.com\r\nCookie: CONSENT=PENDING+270\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3528.0 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html; charset=utf-8
header: Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site
header: x-ua-compatible: IE=edge
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: Mon, 01 Jan 1990 00:00:00 GMT
header: Date: Fri, 23 Apr 2021 21:57:37 GMT
header: Content-Security-Policy: script-src 'report-sample' 'nonce-QufKxFSRpYBHJ2Pl/Xp73w' 'unsafe-inline';object-src 'none';base-uri 'self';report-uri /_/ConsentUi/cspreport;worker-src 'self'
header: Content-Security-Policy: script-src 'nonce-QufKxFSRpYBHJ2Pl/Xp73w' 'self' https://apis.google.com https://ssl.gstatic.com https://www.google.com https://www.gstatic.com https://www.google-analytics.com;report-uri /_/ConsentUi/cspreport
header: Cross-Origin-Resource-Policy: same-site
header: Content-Encoding: gzip
header: Server: ESF
header: X-XSS-Protection: 0
header: X-Frame-Options: SAMEORIGIN
header: X-Content-Type-Options: nosniff
header: Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube:tab] Saving request to OkonomiyakiVtuberSUBEspanol_https_-_consent.youtube.com_mcontinue=https%3A%2F%2Fwww.youtube.com%2Fc%2FOkonomiyakiVtuberSUBEspa%25C3%25B1ol%2Fvideos_gl=RO_m=0_pc=yt_uxe=23983172_hl=en_src=1.dump
ERROR: Unable to extract yt initial data; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1059, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1080, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 3506, in _real_extract
    webpage, data = self._extract_webpage(url, item_id)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 3465, in _extract_webpage
    data = self._extract_yt_initial_data(item_id, webpage)
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 322, in _extract_yt_initial_data
    self._search_regex(
  File "/usr/local/Cellar/yt-dlp/HEAD-ca0b91b/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1057, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract yt initial data; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by colethedj** [comment]
That's strange. On first look it doesn't seem to be applying the consent yes cookie for the first request?

**Comment by colethedj** [comment]
Can confirm I can reproduce this with this particular channel with VPN to Romania. But other channels seem to be working?

In my browser the cookie is `YES+cb.20210420-15-p1.en+FX+181`. Looks like the date present has been updated?

**Comment by llacb47** [comment]
Most likely a bug on YouTube's side that they need to fix.

**Comment by pukkandan** [comment]
The cookie is being added correctly by `YoutubeDLCookieJar`, but by the time request gets to `YoutubeDLHTTPSHandler`, the cookie is somehow lost. It could potentially be an error of `urllib` itself. The solution would be to encode the url correctly before it makes its way to `url_open`

**Comment by colethedj** [comment]
https://github.com/ytdl-org/youtube-dl/issues/28871

Reopening as the current fix breaks Youtube comment extraction and possibly other unknowns.
