### ISSUE TITLE
Throws error for some daftsex videos

### ISSUE THREAD

**Issue by Soebb** [yt-dlp/yt-dlp#2637]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Throws error only for some daftsex.com videos.

### Verbose log

```shell
2022-02-04T11:46:42.715643+00:00 app[worker.1]: [debug] [Daftsex] Extracting URL: https://daftsex.com/watch/-145958185_456243473
2022-02-04T11:46:42.715796+00:00 app[worker.1]: [Daftsex] -145958185_456243473: Downloading webpage
2022-02-04T11:46:43.004399+00:00 app[worker.1]: [Daftsex] -145958185_456243473: Downloading webpage
2022-02-04T11:46:43.241976+00:00 app[worker.1]: ERROR: -145958185_456243473: An extractor error has occurred. (caused by KeyError('cdn_files')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
2022-02-04T11:46:43.243485+00:00 app[worker.1]: Traceback (most recent call last):
2022-02-04T11:46:43.243487+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 612, in extract
2022-02-04T11:46:43.243487+00:00 app[worker.1]:     ie_result = self._real_extract(url)
2022-02-04T11:46:43.243488+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/daftsex.py", line 56, in _real_extract
2022-02-04T11:46:43.243488+00:00 app[worker.1]:     for format_id, format_data in video_params['video']['cdn_files'].items():
2022-02-04T11:46:43.243489+00:00 app[worker.1]: KeyError: 'cdn_files'
2022-02-04T11:46:43.243489+00:00 app[worker.1]: Traceback (most recent call last):
2022-02-04T11:46:43.243489+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 612, in extract
2022-02-04T11:46:43.243489+00:00 app[worker.1]:     ie_result = self._real_extract(url)
2022-02-04T11:46:43.243490+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/daftsex.py", line 56, in _real_extract
2022-02-04T11:46:43.243490+00:00 app[worker.1]:     for format_id, format_data in video_params['video']['cdn_files'].items():
2022-02-04T11:46:43.243490+00:00 app[worker.1]: KeyError: 'cdn_files'
2022-02-04T11:46:43.243491+00:00 app[worker.1]: 
2022-02-04T11:46:43.243491+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2022-02-04T11:46:43.243491+00:00 app[worker.1]: 
2022-02-04T11:46:43.243491+00:00 app[worker.1]: Traceback (most recent call last):
2022-02-04T11:46:43.243491+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
2022-02-04T11:46:43.243492+00:00 app[worker.1]:     return func(self, *args, **kwargs)
2022-02-04T11:46:43.243492+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
2022-02-04T11:46:43.243492+00:00 app[worker.1]:     ie_result = ie.extract(url)
2022-02-04T11:46:43.243492+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 642, in extract
2022-02-04T11:46:43.243492+00:00 app[worker.1]:     raise ExtractorError('An extractor error has occurred.', cause=e, video_id=self.get_temp_id(url))
2022-02-04T11:46:43.243493+00:00 app[worker.1]: yt_dlp.utils.ExtractorError: -145958185_456243473: An extractor error has occurred. (caused by KeyError('cdn_files')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
2022-02-04T11:46:43.243493+00:00 app[worker.1]: 
2022-02-04T11:46:42.433307+00:00 app[worker.1]: [debug] Command-line config: ['-vU', '--geo-bypass', '--no-check-certificate', '-o', 'v.mp4', 'https://daftsex.com/watch/-145958185_456243473']
2022-02-04T11:46:42.437312+00:00 app[worker.1]: [debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
2022-02-04T11:46:42.437337+00:00 app[worker.1]: [debug] yt-dlp version 2022.02.04 [c1653e9ef]
2022-02-04T11:46:42.449292+00:00 app[worker.1]: [debug] Python version 3.9.10 (CPython 64bit) - Linux-4.4.0-1097-aws-x86_64-with-glibc2.31
2022-02-04T11:46:42.496598+00:00 app[worker.1]: [debug] exe versions: ffmpeg N-60236-gffb000fff8-static (setts), ffprobe N-60236-gffb000fff8-static
2022-02-04T11:46:42.496800+00:00 app[worker.1]: [debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
2022-02-04T11:46:42.496801+00:00 app[worker.1]: [debug] Proxy map: {}
2022-02-04T11:46:42.631436+00:00 app[worker.1]: Latest version: 2022.02.04, Current version: 2022.02.04
2022-02-04T11:46:42.631440+00:00 app[worker.1]: yt-dlp is up to date (2022.02.04)
```

**Comment by pukkandan** [comment]
@k3ns1n
