### ISSUE TITLE
[YouTube] embed-thumbnail postprocessing failes in badly encoded mp4 from vp9 stream

### ISSUE THREAD

**Issue by bbilly1** [yt-dlp/yt-dlp#2644]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

I know there have been a few issues with vp9 and this might be very specific and not affecting many people. The command below fails to embed the thumbnail into a malformed mp4 file. I wonder if there is anything that could be done with the post processor to fix this? As far as I can tell, this only fails at the embed-thumbnail stage, without that, the mp4 file looks fine.

This is with using the nightly [ffmpeg builds](https://github.com/yt-dlp/FFmpeg-Builds) from yt-dlp. 

### Verbose log

```shell
yt-dlp -vU "https://www.youtube.com/watch?v=1QMXBXDISUs" \
    --merge-output-format mp4 \
    --embed-thumbnail --embed-metadata

[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=1QMXBXDISUs', '--merge-output-format', 'mp4', '--embed-thumbnail', '--embed-metadata']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-96-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg n4.4.1-49-g3e539d11e4-20220126 (setts), ffprobe n4.4.1-49-g3e539d11e4-20220126
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=1QMXBXDISUs
[youtube] 1QMXBXDISUs: Downloading webpage
[youtube] 1QMXBXDISUs: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1QMXBXDISUs: Downloading 1 format(s): 313+251
[info] Downloading video thumbnail 45 ...
[info] Writing video thumbnail 45 to: Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].webp
[debug] Invoking downloader on "https://rr1---sn-4g5e6nss.googlevideo.com/videoplayback?expire=1644090163&ei=037-YZOEHcGfgQem57-oBw&ip=165.22.74.59&id=o-AOu2PnmG8jmYDdJRYvlFUPidEJ3eZFs575toyKNE_z9s&itag=313&source=youtube&requiressl=yes&mh=RX&mm=31%2C26&mn=sn-4g5e6nss%2Csn-5hnekn7s&ms=au%2Conr&mv=m&mvi=1&pl=23&initcwndbps=711250&vprv=1&mime=video%2Fwebm&gir=yes&clen=4250671062&dur=2446.693&lmt=1640131142986622&mt=1644068228&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgZ8iARsdhIdxeO8I2eu959i0c_l9DVuLI7LukVKUasG8CIQDHEyhn5nLeuagpXQkwoOl6mMgV0uos7OBf6JQYVavP6A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgepiIiHDhKjPySX_wIZ5MZuVVISWzMhNTes9TZNJKOWoCIQDlyKM6lR2NT97n95wA4PU-8kSbgkBYI5JIjH4H5ryDLQ%3D%3D"
[download] Destination: Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].f313.webm
[download] 100% of 3.96GiB in 01:38
[debug] Invoking downloader on "https://rr1---sn-4g5e6nss.googlevideo.com/videoplayback?expire=1644090163&ei=037-YZOEHcGfgQem57-oBw&ip=165.22.74.59&id=o-AOu2PnmG8jmYDdJRYvlFUPidEJ3eZFs575toyKNE_z9s&itag=251&source=youtube&requiressl=yes&mh=RX&mm=31%2C26&mn=sn-4g5e6nss%2Csn-5hnekn7s&ms=au%2Conr&mv=m&mvi=1&pl=23&initcwndbps=711250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=42590139&dur=2446.721&lmt=1640128546803009&mt=1644068228&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANsMHsd5yZUfq4bia0zIliWkgcUVgDEhoL2Vl_fRt-TPAiEA3K-vn4Zg4gMzrWD316itLXm2g9lq-K4dnUQwdfOAKgE%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgepiIiHDhKjPySX_wIZ5MZuVVISWzMhNTes9TZNJKOWoCIQDlyKM6lR2NT97n95wA4PU-8kSbgkBYI5JIjH4H5ryDLQ%3D%3D"
[download] Destination: Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].f251.webm
[download] 100% of 40.62MiB in 00:00
[Merger] Merging formats into "Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].f313.webm' -i 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].temp.mp4'
Deleting original file Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].f251.webm (pass -k to keep)
Deleting original file Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].f313.webm (pass -k to keep)
[Metadata] Adding metadata to "Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].mp4' -map 0 -dn -ignore_unknown -c copy -metadata 'title=Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2)' -metadata date=20190803 -metadata 'description=Sam Raimi had to top Spider-Man 1 with Spider-Man 2.  So I felt that I needed to top Sam Raimi’s Spider-Man - The Perfect Origin (Part 1). So I locked myself in the HiTop Films office until I completed Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2). Only one more Spider-Man Video Essay left and that’s Spider-Man 3. I hope you guys enjoy this as much as I loved making it. This one is for Sam Raimi and for everyone who was inspired and continues to be inspired by The Raimi Trilogy.

Much love and thank you for the constant support.  

🔶SUPPORT US ON PATREON🔶
https://www.patreon.com/HiTopFilms
🐦@hitopfilms 🐦

🖥 DISCORD LINK 🖥
https://discord.gg/V94ykwn

Business Inquiries: hitopfilms@ellifyagency.com

#hitopfilms #spiderman 

I Am a Man Who Will Fight for Your Honor by Chris Zabriskie is licensed under a Creative Commons Attribution license (https://creativecommons.org/licenses/by/4.0/)
Source: http://chriszabriskie.com/honor/
Artist: http://chriszabriskie.com/' -metadata 'synopsis=Sam Raimi had to top Spider-Man 1 with Spider-Man 2.  So I felt that I needed to top Sam Raimi’s Spider-Man - The Perfect Origin (Part 1). So I locked myself in the HiTop Films office until I completed Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2). Only one more Spider-Man Video Essay left and that’s Spider-Man 3. I hope you guys enjoy this as much as I loved making it. This one is for Sam Raimi and for everyone who was inspired and continues to be inspired by The Raimi Trilogy.

Much love and thank you for the constant support.  

🔶SUPPORT US ON PATREON🔶
https://www.patreon.com/HiTopFilms
🐦@hitopfilms 🐦

🖥 DISCORD LINK 🖥
https://discord.gg/V94ykwn

Business Inquiries: hitopfilms@ellifyagency.com

#hitopfilms #spiderman 

I Am a Man Who Will Fight for Your Honor by Chris Zabriskie is licensed under a Creative Commons Attribution license (https://creativecommons.org/licenses/by/4.0/)
Source: http://chriszabriskie.com/honor/
Artist: http://chriszabriskie.com/' -metadata 'purl=https://www.youtube.com/watch?v=1QMXBXDISUs' -metadata 'comment=https://www.youtube.com/watch?v=1QMXBXDISUs' -metadata 'artist=HiTop Films' -movflags +faststart 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].temp.mp4'
[ThumbnailsConvertor] Converting thumbnail "Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].webp' -movflags +faststart 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].png'
[EmbedThumbnail] mutagen: Adding thumbnail to "Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].mp4"
WARNING: unable to embed using mutagen; 'I' format requires 0 <= number <= 4294967295
[EmbedThumbnail] Neither mutagen nor AtomicParsley was found. Falling back to ffmpeg
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].mp4'
[EmbedThumbnail] ffmpeg: Adding thumbnail to "Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].mp4' -i 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].png' -map 0 -dn -ignore_unknown -c copy -map 1 -map -0:2 -disposition:2 attached_pic -movflags +faststart 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].temp.mp4'
[debug] ffmpeg version n4.4.1-49-g3e539d11e4-20220126 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.498_5075e1f)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --disable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --disable-vulkan --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220126
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f3faeca980] stream 0, timescale not set
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Not all references are available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid sync code
[vp9 @ 0x55f3faeccb40] Requested reference 6 not available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid sync code
[vp9 @ 0x55f3faeccb40] Requested reference 3 not available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Requested reference 7 not available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Requested reference 5 not available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Requested reference 1 not available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Requested reference 5 not available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Profile 4 is not yet supported
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Not all references are available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid sync code
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Not all references are available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Requested reference 7 not available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Requested reference 2 not available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid sync code
[vp9 @ 0x55f3faeccb40] Requested reference 0 not available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Requested reference 2 not available
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[vp9 @ 0x55f3faeccb40] Invalid frame marker
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f3faeca980] Stream #2: not enough frames to estimate rate; consider increasing probesize
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f3faeca980] decoding for stream 0 failed
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f3faeca980] Could not find codec parameters for stream 0 (Video: vp9 (Profile 0) (vp09 / 0x39307076), none(tv, bt709), 3840x2160, 13896 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2)
    artist          : HiTop Films
    date            : 20190803
    encoder         : Lavf58.76.100
    comment         : https://www.youtube.com/watch?v=1QMXBXDISUs
    description     : Sam Raimi had to top Spider-Man 1 with Spider-Man 2.  So I felt that I needed to top Sam Raimi’s Spider-Man - The Perfect Origin (Part 1). So I locked myself in the HiTop Films office until I completed Sam Raimi’s Spider-Man 2 - The Perfect Superhero 
                    : 
                    : Much love and thank you for the constant support.  
                    : 
                    : 🔶SUPPORT US ON PATREON🔶
                    : https://www.patreon.com/HiTopFilms
                    : 🐦@hitopfilms 🐦
                    : 
                    : 🖥 DISCORD LINK 🖥
                    : https://discord.gg/V94ykwn
                    : 
                    : Business Inquiries: hitopfilms@ellifyagency.com
                    : 
                    : #hitopfilms #spiderman 
                    : 
                    : I Am a Man Who Will Fight for Your Honor by Chris Zabriskie is licensed under a Creative Commons Attribution license (https://creativecommons.org/licenses/by/4.0/)
                    : Source: http://chriszabriskie.com/honor/
                    : Artist: http://chriszabriskie.com/
    synopsis        : Sam Raimi had to top Spider-Man 1 with Spider-Man 2.  So I felt that I needed to top Sam Raimi’s Spider-Man - The Perfect Origin (Part 1). So I locked myself in the HiTop Films office until I completed Sam Raimi’s Spider-Man 2 - The Perfect Superhero 
                    : 
                    : Much love and thank you for the constant support.  
                    : 
                    : 🔶SUPPORT US ON PATREON🔶
                    : https://www.patreon.com/HiTopFilms
                    : 🐦@hitopfilms 🐦
                    : 
                    : 🖥 DISCORD LINK 🖥
                    : https://discord.gg/V94ykwn
                    : 
                    : Business Inquiries: hitopfilms@ellifyagency.com
                    : 
                    : #hitopfilms #spiderman 
                    : 
                    : I Am a Man Who Will Fight for Your Honor by Chris Zabriskie is licensed under a Creative Commons Attribution license (https://creativecommons.org/licenses/by/4.0/)
                    : Source: http://chriszabriskie.com/honor/
                    : Artist: http://chriszabriskie.com/
  Duration: 00:40:46.72, start: 0.000000, bitrate: 14056 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), none(tv, bt709), 3840x2160, 13896 kb/s, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 16k tbn, 16k tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 136 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:2: Video: png, rgb24(pc), 1280x720, 90k tbr, 90k tbn, 90k tbc (attached pic)
Input #1, png_pipe, from 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].png':
  Duration: N/A, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 1280x720, 25 fps, 25 tbr, 25 tbn, 25 tbc
[mp4 @ 0x55f3faf01dc0] track 1: codec frame size is not set
Output #0, mp4, to 'file:Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2) [1QMXBXDISUs].temp.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : Sam Raimi’s Spider-Man 2 - The Perfect Superhero Movie (Part 2)
    artist          : HiTop Films
    date            : 20190803
    synopsis        : Sam Raimi had to top Spider-Man 1 with Spider-Man 2.  So I felt that I needed to top Sam Raimi’s Spider-Man - The Perfect Origin (Part 1). So I locked myself in the HiTop Films office until I completed Sam Raimi’s Spider-Man 2 - The Perfect Superhero 
                    : 
                    : Much love and thank you for the constant support.  
                    : 
                    : 🔶SUPPORT US ON PATREON🔶
                    : https://www.patreon.com/HiTopFilms
                    : 🐦@hitopfilms 🐦
                    : 
                    : 🖥 DISCORD LINK 🖥
                    : https://discord.gg/V94ykwn
                    : 
                    : Business Inquiries: hitopfilms@ellifyagency.com
                    : 
                    : #hitopfilms #spiderman 
                    : 
                    : I Am a Man Who Will Fight for Your Honor by Chris Zabriskie is licensed under a Creative Commons Attribution license (https://creativecommons.org/licenses/by/4.0/)
                    : Source: http://chriszabriskie.com/honor/
                    : Artist: http://chriszabriskie.com/
    comment         : https://www.youtube.com/watch?v=1QMXBXDISUs
    description     : Sam Raimi had to top Spider-Man 1 with Spider-Man 2.  So I felt that I needed to top Sam Raimi’s Spider-Man - The Perfect Origin (Part 1). So I locked myself in the HiTop Films office until I completed Sam Raimi’s Spider-Man 2 - The Perfect Superhero 
                    : 
                    : Much love and thank you for the constant support.  
                    : 
                    : 🔶SUPPORT US ON PATREON🔶
                    : https://www.patreon.com/HiTopFilms
                    : 🐦@hitopfilms 🐦
                    : 
                    : 🖥 DISCORD LINK 🖥
                    : https://discord.gg/V94ykwn
                    : 
                    : Business Inquiries: hitopfilms@ellifyagency.com
                    : 
                    : #hitopfilms #spiderman 
                    : 
                    : I Am a Man Who Will Fight for Your Honor by Chris Zabriskie is licensed under a Creative Commons Attribution license (https://creativecommons.org/licenses/by/4.0/)
                    : Source: http://chriszabriskie.com/honor/
                    : Artist: http://chriszabriskie.com/
    encoder         : Lavf58.76.100
  Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), none(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 13896 kb/s, 23.98 fps, 23.98 tbr, 16k tbn, 16k tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 136 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:2: Video: png (mp4v / 0x7634706D), rgb24(pc), 1280x720, q=2-31, 25 fps, 25 tbr, 12800 tbn, 25 tbc (attached pic)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #1:0 -> #0:2 (copy)
Press [q] to stop, [?] for help
[vp9_superframe @ 0x55f3faf2cd40] Too many invisible frames0:00.00 bitrate=N/A speed=   0x    
[mp4 @ 0x55f3faf01dc0] Error applying bitstream filters to an output packet for stream #0: Invalid data found when processing input
av_interleaved_write_frame(): Invalid data found when processing input
[mp4 @ 0x55f3faf01dc0] Starting second pass: moving the moov atom to the beginning of the file
[mp4 @ 0x55f3faf01dc0] Unsupported pixel format (-1)
[mp4 @ 0x55f3faf01dc0] Unsupported pixel format (-1)
[mp4 @ 0x55f3faf01dc0] Unsupported pixel format (-1)
[mp4 @ 0x55f3faf01dc0] Unsupported pixel format (-1)
[mp4 @ 0x55f3faf01dc0] Unsupported pixel format (-1)
[mp4 @ 0x55f3faf01dc0] Unsupported pixel format (-1)
frame=   77 fps=0.0 q=-1.0 Lq=-1.0 size=    2796kB time=00:00:03.16 bitrate=7246.0kbits/s speed= 203x    
video:3402kB audio:46kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
ERROR: Postprocessing: Unable to embed using ffprobe & ffmpeg; Conversion failed!
Traceback (most recent call last):
  File "/home/simon/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/embedthumbnail.py", line 197, in run
    self.run_ffmpeg_multiple_files([filename, thumbnail_filename], temp_filename, options)
  File "/home/simon/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 294, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/simon/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 333, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3159, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/simon/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3336, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/simon/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3323, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/simon/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3296, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/simon/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/simon/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 117, in wrapper
    return func(self, info)
  File "/home/simon/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/embedthumbnail.py", line 200, in run
    raise EmbedThumbnailPPError(f'Unable to embed using ffprobe & ffmpeg; {err}')
yt_dlp.postprocessor.embedthumbnail.EmbedThumbnailPPError: Unable to embed using ffprobe & ffmpeg; Conversion failed!
```

**Comment by N72826** [comment]
thank you for creating this for me man, I highly appreciate it!

**Comment by pukkandan** [comment]
Can you try with atomicparsley?

**Comment by bbilly1** [comment]
Thanks for looking into it.

And yes, atomicparsley is embedding the thumbnail correctly. Sorry, I should have thought of that. First video after all these years where ffmpeg failed.

Thanks, closing this issue.
