### ISSUE TITLE
EMPFlix is broken

### ISSUE THREAD

**Issue by nindogo** [yt-dlp/yt-dlp#2652]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Kenya

### Description

Unable to download videos from [EMPFlix](https://www.empflix.com/) like [this one](https://www.empflix.com/blowjobs-porn/ebony-teen-with-big-black-ass-adriana-maya-sucked-stepdads-big-white-dick/video3130427).

### Verbose log

```shell
emp>yt-dlp -vU  https://www.empflix.com/blowjobs-porn/ebony-teen-with-big-black-ass-adriana-maya-sucked-stepdads-big-white-dick/video3130427
[debug] Command-line config: ['-vU', 'https://www.empflix.com/blowjobs-porn/ebony-teen-with-big-black-ass-adriana-maya-sucked-stepdads-big-white-dick/video3130427']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.2 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-12-02-git-4a6aece703-full_build-www.gyan.dev (setts), ffprobe 2021-12-02-git-4a6aece703-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [EMPFlix] Extracting URL: https://www.empflix.com/blowjobs-porn/ebony-teen-with-big-black-ass-adriana-maya-sucked-stepdads-big-white-dick/video3130427
[EMPFlix] ebony-teen-with-big-black-ass-adriana-maya-sucked-stepdads-big-white-dick: Downloading webpage
ERROR: 3130427: An extractor error has occurred. (caused by KeyError('vkey')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "C:\Users\[snip]\Python\venv3.10\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\[snip]\Python\venv3.10\lib\site-packages\yt_dlp\extractor\tnaflix.py", line 95, in _real_extract
    % (self._HOST, self._HOST, inputs['vkey'], self._VKEY_SUFFIX, inputs['nkey'], video_id))
KeyError: 'vkey'
Traceback (most recent call last):
  File "C:\Users\[snip]\Python\venv3.10\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\[snip]\Python\venv3.10\lib\site-packages\yt_dlp\extractor\tnaflix.py", line 95, in _real_extract
    % (self._HOST, self._HOST, inputs['vkey'], self._VKEY_SUFFIX, inputs['nkey'], video_id))
KeyError: 'vkey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[snip]\Python\venv3.10\lib\site-packages\yt_dlp\YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\[snip]\Python\venv3.10\lib\site-packages\yt_dlp\YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\[snip]\Python\venv3.10\lib\site-packages\yt_dlp\extractor\common.py", line 642, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e, video_id=self.get_temp_id(url))
yt_dlp.utils.ExtractorError: 3130427: An extractor error has occurred. (caused by KeyError('vkey')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
```

**Comment by Stephan972** [comment]
@yt-dlp devs, do you need more information to fix the extractor? If so, what are you missing?

**Comment by Stephan972** [comment]
see also: https://github.com/ytdl-org/youtube-dl/issues/30937
