### ISSUE TITLE
[Broken] Tubi errors

### ISSUE THREAD

**Issue by YungEff** [yt-dlp/yt-dlp#266]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\SUPERMAN> yt-dlp -v 'https://tubitv.com/tv-shows/573735/s01-e01-the-fearful-force-phantom?start=true'
[debug] Command-line config: ['-v', 'https://tubitv.com/tv-shows/573735/s01-e01-the-fearful-force-phantom?start=true']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.04.22
[debug] Python version 3.8.3 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Proxy map: {}
[debug] Using fake IP 6.12.177.208 (US) as X-Forwarded-For.
[TubiTv] 573735: Downloading JSON metadata
[TubiTv] 573735: Downloading m3u8 information
ERROR: unknown url type: ''
Traceback (most recent call last):
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 1059, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 1080, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\extractor\common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\extractor\tubitv.py", line 84, in _real_extract
    formats = self._extract_m3u8_formats(
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\extractor\common.py", line 1887, in _extract_m3u8_formats
    res = self._download_webpage_handle(
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\extractor\common.py", line 699, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\extractor\common.py", line 661, in _request_webpage
    url_or_request = sanitized_Request(url_or_request, data, headers)
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\utils.py", line 2173, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\urllib\request.py", line 328, in __init__
    self.full_url = url
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\urllib\request.py", line 354, in full_url
    self._parse()
  File "c:\users\our plex server\appdata\local\programs\python\python38-32\lib\urllib\request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''

```

## Description

Most Tubi videos I try work but then there are some that produce this issue. I was wondering if there was a way around it.

**Comment by pukkandan** [comment]
The given video is DRM protected. It is possible to patch the extractor to fetch the manifests, but unless you can provide a non-DRM video where the current method doesn't work, there is no point in implementing it
