### ISSUE TITLE
Support media.un.org

### ISSUE THREAD

**Issue by pascaldaniela** [yt-dlp/yt-dlp#2675]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

https://media.un.org/en/asset/k1r/k1r3vy9ikk
https://media.un.org/en/asset/k1r/k1r5enfiwb

### Description

The site at media.un.org uses Kaltura, but yt-dlp doesn't recognize it and is unable to extract/construct the URL. This is the main UN Media Site containing recordings of UN meetings and events. Would be great to be able to download these recordings for offline viewing/listening. Thanks!

### Verbose log

```shell
[debug] Command-line config: ['--verbose', 'https://media.un.org/en/asset/k1r/k1r3vy9ikk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.9.10 (CPython 64bit) - Linux-5.15.0-3-amd64-x86_64-with-glibc2.33
[debug] exe versions: avconv 4.4.1, avprobe 4.4.1, ffmpeg 4.4.1 (setts,fdk), ffprobe 4.4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://media.un.org/en/asset/k1r/k1r3vy9ikk
[generic] k1r3vy9ikk: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] k1r3vy9ikk: Downloading webpage
[generic] k1r3vy9ikk: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://media.un.org/en/asset/k1r/k1r3vy9ikk
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://media.un.org/en/asset/k1r/k1r3vy9ikk
```

**Comment by dirkf** [comment]
See https://github.com/ytdl-org/youtube-dl/pull/30615.

**Comment by HobbyistDev** [comment]
it's work for me. Here's the log:
```
(python_proj2) ~\yt-dlp>python -m yt_dlp -v "https://media.un.org/en/asset/k1r/k1r3vy9ikk"
[debug] Command-line config: ['-v', 'https://media.un.org/en/asset/k1r/k1r3vy9ikk']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 67db96e5a
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://media.un.org/en/asset/k1r/k1r3vy9ikk
[generic] k1r3vy9ikk: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] k1r3vy9ikk: Extracting information
[debug] Looking for video embeds
[download] Downloading playlist: (8th meeting) United Nations Permanent Forum on Indigenous Issues (UNPFII, Twentieth Session: 19-30 April 2021) - Closing ceremony.
[generic] Playlist (8th meeting) United Nations Permanent Forum on Indigenous Issues (UNPFII, Twentieth Session: 19-30 April 2021) - Closing ceremony.: Downloading 1 videos of 1
[download] Downloading video 1 of 1
[debug] [Kaltura] Extracting URL: kaltura:2503451:1_r3vy9ikk#__youtubedl_smuggle=%7B%22source_url%22%3A+%22https%3A%2F%2Fmedia.un.org%2Fen%2Fasset%2Fk1r%2Fk1r3vy9ikk%22%7D
[Kaltura] 1_r3vy9ikk: Downloading video info JSON
[Kaltura] 1_r3vy9ikk: Checking mp4-4207 URL
[Kaltura] 1_r3vy9ikk: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1_r3vy9ikk: Downloading 1 format(s): mp4-4207
[debug] Invoking http downloader on "http://cdnapi.kaltura.com/p/2503451/sp/250345100/playManifest/entryId/1_r3vy9ikk/format/url/protocol/http/flavorId/1_tc7ce1e0?referrer=aHR0cHM6Ly9tZWRpYS51bi5vcmc="
[debug] File locking is not supported. Proceeding without locking
[download] Destination: (8th meeting) United Nations Permanent Forum on Indigenous Issues (UNPFII, Twentieth Session -  19-30 April 2021) - Closing ceremony. [1_r3vy9ikk].mp4
[download]   0.2% of 2.83GiB at  893.83KiB/s ETA 55:09
ERROR: Interrupted by user
```

**Comment by pascaldaniela** [comment]
> it's work for me. Here's the log:
> 
> ```
> (python_proj2) ~\yt-dlp>python -m yt_dlp -v "https://media.un.org/en/asset/k1r/k1r3vy9ikk"
> [debug] Command-line config: ['-v', 'https://media.un.org/en/asset/k1r/k1r3vy9ikk']
> [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.06.29 [9d339c41e] (source)
> [debug] Lazy loading extractors is disabled
> [debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
> [debug] Git HEAD: 67db96e5a
> [debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.19044-SP0
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
> [debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
> [debug] Proxy map: {}
> [debug] [generic] Extracting URL: https://media.un.org/en/asset/k1r/k1r3vy9ikk
> [generic] k1r3vy9ikk: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor.
> [generic] k1r3vy9ikk: Extracting information
> [debug] Looking for video embeds
> [download] Downloading playlist: (8th meeting) United Nations Permanent Forum on Indigenous Issues (UNPFII, Twentieth Session: 19-30 April 2021) - Closing ceremony.
> [generic] Playlist (8th meeting) United Nations Permanent Forum on Indigenous Issues (UNPFII, Twentieth Session: 19-30 April 2021) - Closing ceremony.: Downloading 1 videos of 1
> [download] Downloading video 1 of 1
> [debug] [Kaltura] Extracting URL: kaltura:2503451:1_r3vy9ikk#__youtubedl_smuggle=%7B%22source_url%22%3A+%22https%3A%2F%2Fmedia.un.org%2Fen%2Fasset%2Fk1r%2Fk1r3vy9ikk%22%7D
> [Kaltura] 1_r3vy9ikk: Downloading video info JSON
> [Kaltura] 1_r3vy9ikk: Checking mp4-4207 URL
> [Kaltura] 1_r3vy9ikk: Downloading m3u8 information
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] 1_r3vy9ikk: Downloading 1 format(s): mp4-4207
> [debug] Invoking http downloader on "http://cdnapi.kaltura.com/p/2503451/sp/250345100/playManifest/entryId/1_r3vy9ikk/format/url/protocol/http/flavorId/1_tc7ce1e0?referrer=aHR0cHM6Ly9tZWRpYS51bi5vcmc="
> [debug] File locking is not supported. Proceeding without locking
> [download] Destination: (8th meeting) United Nations Permanent Forum on Indigenous Issues (UNPFII, Twentieth Session -  19-30 April 2021) - Closing ceremony. [1_r3vy9ikk].mp4
> [download]   0.2% of 2.83GiB at  893.83KiB/s ETA 55:09
> ERROR: Interrupted by user
> ```

That's interesting. I just tried it again on a recent UN meeting, and this time yt-dlp worked, but it downloaded only audio mp4 for all meeting URLs, e.g.:
$ yt-dlp -v https://media.un.org/en/asset/k1v/k1vg3x43ih
[debug] Command-line config: ['-v', 'https://media.un.org/en/asset/k1v/k1vg3x43ih']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.0-2-amd64-x86_64-with-glibc2.33 (glibc 2.33)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (fdk,setts), ffprobe 5.0.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.2, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://media.un.org/en/asset/k1v/k1vg3x43ih
[generic] k1vg3x43ih: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] k1vg3x43ih: Downloading webpage
[generic] k1vg3x43ih: Extracting information
[debug] Looking for video embeds
[download] Downloading playlist: 3rd Meeting, 15th Session, Expert Mechanism on the Rights of Indigenous Peoples (EMRIP)
[generic] Playlist 3rd Meeting, 15th Session, Expert Mechanism on the Rights of Indigenous Peoples (EMRIP): Downloading 1 videos of 1
[download] Downloading video 1 of 1
[debug] [Kaltura] Extracting URL: kaltura:2503451:1_vg3x43ih#__youtubedl_smuggle=%7B%22source_url%22%3A+%22https%3A%2F%2Fmedia.un.org%2Fen%2Fasset%2Fk1v%2Fk1vg3x43ih%22%7D
[Kaltura] 1_vg3x43ih: Downloading video info JSON
[Kaltura] 1_vg3x43ih: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1_vg3x43ih: Downloading 1 format(s): mp4-2728
[debug] Invoking http downloader on "http://cdnapi.kaltura.com/p/2503451/sp/0/playManifest/entryId/1_5jo4p0tt/format/url/protocol/http/flavorId/1_c9osu2oi?referrer=aHR0cHM6Ly9tZWRpYS51bi5vcmc="
[download] Destination: 3rd Meeting, 15th Session, Expert Mechanism on the Rights of Indigenous Peoples (EMRIP) [1_vg3x43ih].mp4
[download] 100% of 42.13MiB in 00:06
[download] Finished downloading playlist: 3rd Meeting, 15th Session, Expert Mechanism on the Rights of Indigenous Peoples (EMRIP)

**Comment by vasyugan** [comment]
> it's work for me. Here's the log:
 
The problem is that the resulting file is audio only. I did a download yesterday, see https://gist.github.com/vasyugan/772442d65c6ec24faaeac2fa947fc95b
The file should have been around 3 Gb, but it was 257 only and there was no video, only sound. The Firefox addon Video Download Helper managed to download the entire file, but took almost an hour for it.
