### ISSUE TITLE
[prosiebenmaxx.de] Error 404 and malfunction in drm-protection-check

### ISSUE THREAD

**Issue by Shithappenz** [yt-dlp/yt-dlp#2679]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

I founded two bugs / errors on prosiebenmaxx.de: There is a Error 404 and a mafunction in the drm-protection-check. I posted both logs above. Maybe you need the geo-bypass-function to confirm these bugs.
Last month the extractor worked fine.
There are some clips, where I get the 404 Error (e.g. the link in the verbose log). I tryed to download it serveral times, but yt-dlp answered the same 404 Error. Maybe in the extractor there are some lines, that are not working anymore?
Futhermore the drm-protection check is not working. For example yt-dlp answered, that the clip is drm protected. In the header of the side, one can read, that there is no drm protection:
meta data-react-helmet="true" property="video:drm" content="0"
I downloded the clip manually and vlc can play that clip.
I am sorry, that I can't do more than to report the bug. I hope, we can fix it :D

### Verbose log

```shell
404 Error verbose log:
c:\Download>yt-dlp.exe -U
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
c:\Download>yt-dlp.exe "https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge" -F -v
[debug] Command-line config: ['https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge', '-F', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [prosiebensat1] Extracting URL: https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge
[prosiebensat1] anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge: Downloading webpage
[prosiebensat1] 6595537: Downloading videos JSON
[prosiebensat1] 6595537: Downloading protocols JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not Found
[prosiebensat1] 6595537: Downloading sources JSON
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not found
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not found
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not found
ERROR: [prosiebensat1] 6595537: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2431, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
yt_dlp.utils.ExtractorError: [prosiebensat1] 6595537: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U

bug in drm-protection-check log:
c:\Download>yt-dlp.exe "https://www.prosiebenmaxx.de/anime/attack-on-titan/video/38-die-aussenmauer-von-bezirk-orvud-ganze-folge" -F -v
[debug] Command-line config: ['https://www.prosiebenmaxx.de/anime/attack-on-titan/video/38-die-aussenmauer-von-bezirk-orvud-ganze-folge', '-F', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [prosiebensat1] Extracting URL: https://www.prosiebenmaxx.de/anime/attack-on-titan/video/38-die-aussenmauer-von-bezirk-orvud-ganze-folge
[prosiebensat1] anime/attack-on-titan/video/38-die-aussenmauer-von-bezirk-orvud-ganze-folge: Downloading webpage
[prosiebensat1] 5584131: Downloading videos JSON
ERROR: [prosiebensat1] 5584131: 5584131: This video is DRM protected
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\prosiebensat1.py", line 495, in _real_extract
  File "yt_dlp\extractor\prosiebensat1.py", line 440, in _extract_clip
  File "yt_dlp\extractor\prosiebensat1.py", line 38, in _extract_video_info
  File "yt_dlp\extractor\common.py", line 1076, in report_drm
  File "yt_dlp\extractor\common.py", line 1120, in raise_no_formats
```

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/30598 https://github.com/ytdl-org/youtube-dl/issues/30624

**Comment by pukkandan** [comment]
Both linked videos asks for registration in browser. Check with cookies

**Comment by Shithappenz** [comment]
Hello @pukkandan! Thank you for your response and your input.
Since half of a year the prosiebenmaxx-videos are only playable in the browser with a registration. BUT the download / extraction worked without a registration (until a few weeks ago).
I tried it with your advice. I logged in and saved the cookies via firefox-addoon cookies.txt. The result was the same 404-Error and malfunction in drm-protection-check in both cases (youtube-dl and youtube-dlp).
```
c:\Download>yt-dlp.exe -U
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)

c:\Download>youtube-dl.exe -U
youtube-dl is up-to-date (2021.12.17)

c:\Download>youtube-dl.exe "https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge" -F --cookies "C:\Download\cookies.txt" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge', '-F', '--cookies', 'C:\\Download\\cookies.txt', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[prosiebensat1] anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge: Downloading webpage
[prosiebensat1] 6595537: Downloading videos JSON
[prosiebensat1] 6595537: Downloading protocols JSON
WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
[prosiebensat1] 6595537: Downloading sources JSON
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: Unable to download JSON metadata: HTTP Error 404: Not found
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: Unable to download JSON metadata: HTTP Error 404: Not found
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: Unable to download JSON metadata: HTTP Error 404: Not found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\prosiebensat1.py", line 495, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\prosiebensat1.py", line 440, in _extract_clip
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\prosiebensat1.py", line 162, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


c:\Download>yt-dlp.exe "https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge" -F --cookies "C:\Download\cookies.txt" --verbose
[debug] Command-line config: ['https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge', '-F', '--cookies', 'C:\\Download\\cookies.txt', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [prosiebensat1] Extracting URL: https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge
[prosiebensat1] anime/shakugan-no-shana/video/11-alles-endete-etwas-neues-begann-ganze-folge: Downloading webpage
[prosiebensat1] 6595537: Downloading videos JSON
[prosiebensat1] 6595537: Downloading protocols JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not Found
[prosiebensat1] 6595537: Downloading sources JSON
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not found
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not found
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not found
ERROR: [prosiebensat1] 6595537: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2431, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
yt_dlp.utils.ExtractorError: [prosiebensat1] 6595537: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
```
On prosiebenmaxx there are some videos, that don’t require a registration / login. The preview clips can be played in the browser without registration. They (youtube-dl and yotube-dlp) produce the same 404-Error. For example https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/115-preview-folge-15-eine-neue-flame-haze-clip :
```
c:\Download>youtube-dl.exe "https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/115-preview-folge-15-eine-neue-flame-haze-clip" -F --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/115-preview-folge-15-eine-neue-flame-haze-clip', '-F', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[prosiebensat1] anime/shakugan-no-shana/video/115-preview-folge-15-eine-neue-flame-haze-clip: Downloading webpage
[prosiebensat1] 6595537: Downloading videos JSON
[prosiebensat1] 6595537: Downloading protocols JSON
WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
[prosiebensat1] 6595537: Downloading sources JSON
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: Unable to download JSON metadata: HTTP Error 404: Not found
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: Unable to download JSON metadata: HTTP Error 404: Not found
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: Unable to download JSON metadata: HTTP Error 404: Not found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\prosiebensat1.py", line 495, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\prosiebensat1.py", line 440, in _extract_clip
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\prosiebensat1.py", line 162, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

c:\Download>yt-dlp.exe "https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/115-preview-folge-15-eine-neue-flame-haze-clip" -F --verbose
[debug] Command-line config: ['https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/115-preview-folge-15-eine-neue-flame-haze-clip', '-F', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [prosiebensat1] Extracting URL: https://www.prosiebenmaxx.de/anime/shakugan-no-shana/video/115-preview-folge-15-eine-neue-flame-haze-clip
[prosiebensat1] anime/shakugan-no-shana/video/115-preview-folge-15-eine-neue-flame-haze-clip: Downloading webpage
[prosiebensat1] 6595537: Downloading videos JSON
[prosiebensat1] 6595537: Downloading protocols JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not Found
[prosiebensat1] 6595537: Downloading sources JSON
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not found
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not found
[prosiebensat1] 6595537: Downloading urls JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not found
ERROR: [prosiebensat1] 6595537: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2431, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
yt_dlp.utils.ExtractorError: [prosiebensat1] 6595537: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U

```

**Comment by dirkf** [comment]
>... The json-file has a token https://vas-v4.p7s1video.net/4.0/getsources?token= , but I have no idea, how the site create this token...

Perhaps [this TypeScript](https://gist.github.com/dirkf/35ffc6c1d1f3adf30fabacf11619f8b8#file-p7-source-fetcher-ts) which also shows (through a TypeScript glass darkly) how the quoted URL is accessed:
```
const getJWT = ({ encryption_key, access_id }: Config, payload: VasSourcesPayload): string =>
  jwt.sign(payload, encryption_key, {
    algorithm: 'HS256',
    header: { kid: access_id },
    expiresIn: '5m',
    notBefore: '-5m',
  });
```
JWT = jsonwebtoken

I guess that the blank result with `'is_protected': True` results from calling the wrong API for the show. Apparently some P7 shows are being handled correctly, but not the maxx nor the [newly revised related sites](https://github.com/ytdl-org/youtube-dl/issues/30624).

**Comment by Shithappenz** [comment]
Hi @dirkf !
Maybe we can solve the issue together.

> Unfortunately the geo-restriction policies of the various sites make debugging difficult without a local presence.

If you need further specific information or I should test some code on prosiebenmaxx, I will try to help @dirkf !

**Comment by H852ing** [comment]
Hi,...
I have the same Problem with the DRM check on ProsiebenMaxx.de
For test reasons, I had disabled the DRM functionality on Firefox, and it was still possible to watch the Video on the Site.
But with "yt-dlp or youtube-dl" I get the message "DRM protected stream".

I tried it with the "cookies-from-browser" Option as well.
But same result.
