### ISSUE TITLE
--convert-thumbnails  "Unable to find a suitable output format" "Invalid argument"

### ISSUE THREAD

**Issue by timothylarson** [yt-dlp/yt-dlp#2695]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I am having issues with the "--convert-thumbnails jpg" command. I keep getting an "Invalid argument" and "Unable to find a suitable output format" when trying to convert webp thumbnails to jpg.

I have tried this with multiple videos on many channels and cannot get a jpg thumbnail.

/usr/local/bin/yt-dlp -i -o "%(uploader)s/%(uploader)s - %(title)s.%(ext)s"  --convert-thumbnails jpg --write-thumbnail "https://www.youtube.com/watch?v=2J7xlDH4QkA" -vU

### Verbose log

```shell
[debug] Command-line config: ['-i', '-o', '%(uploader)s/%(uploader)s - %(title)s.%(ext)s', '--convert-thumbnails', 'jpg', '--write-thumbnail', 'https://www.youtube.com/watch?v=2J7xlDH4QkA', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.8.8 (CPython 64bit) - Linux-3.10.108-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.1.6
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=2J7xlDH4QkA
[youtube] 2J7xlDH4QkA: Downloading webpage
[youtube] 2J7xlDH4QkA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2J7xlDH4QkA: Downloading 1 format(s): 337+258
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).webp
[ThumbnailsConvertor] Converting thumbnail "HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).webp" to jpg
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).webp' -bsf:v mjpeg2jpeg -movflags +faststart 'file:HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).jpg'
[debug] ffmpeg version 4.1.6 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7.5.0 (GCC)
  configuration: --prefix=/usr --incdir='${prefix}/include/ffmpeg' --arch=i686 --target-os=linux --cross-prefix=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-shared --disable-static --disable-stripping --enable-version3 --enable-encoders --enable-pthreads --disable-protocols --disable-protocol=rtp --enable-protocol=file --enable-protocol=pipe --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffplay --disable-ffprobe --disable-doc --disable-devices --disable-bzlib --disable-altivec --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --disable-vaapi --disable-cuvid --disable-nvenc --disable-decoder=amrnb --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-encoder=zmbv --disable-encoder=dca --disable-decoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=eac3 --disable-encoder=truehd --disable-decoder=truehd --disable-encoder=hevc_vaapi --disable-decoder=hevc --disable-muxer=hevc --disable-demuxer=hevc --disable-parser=hevc --disable-bsf=hevc_mp4toannexb --x86asmexe=yasm --cc=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-wrap-gcc --enable-yasm --enable-libx264 --enable-encoder=libx264
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, image2, from 'file:HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).webp':
  Duration: 00:00:00.04, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 1280x720, 25 tbr, 25 tbn, 25 tbc
[NULL @ 0x14bb440] Unable to find a suitable output format for 'file:HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).jpg'
file:HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).jpg: Invalid argument
ERROR: file:HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).jpg: Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3296, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 1118, in run
    thumbnail_dict['filepath'] = self.convert_thumbnail(original_thumbnail, self.format)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 1095, in convert_thumbnail
    self.real_run_ffmpeg(
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 333, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).jpg: Invalid argument

WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking downloader on "https://rr1---sn-jxou0gtapo3-2ime.googlevideo.com/videoplayback?expire=1644375925&ei=FdsCYrL6HP2ZsfIPqpOLuAw&ip=174.26.193.177&id=o-AKMrMFpq2azY3eJyr0VnnFzZnFALGI7S1d1jBJL5zAC1&itag=337&source=youtube&requiressl=yes&mh=ds&mm=31%2C29&mn=sn-jxou0gtapo3-2ime%2Csn-a5mlrn7z&ms=au%2Crdu&mv=m&mvi=1&pl=16&initcwndbps=1095000&vprv=1&mime=video%2Fwebm&gir=yes&clen=429896839&dur=188.133&lmt=1634155011373372&mt=1644354059&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLIqtUNPPPR8Nu0hkQmq55oJgUuZL4zoePXEdINHRDUYCIHy5JUFfAooCxwdFErqR3hzmSc8gHoX9CxREbWfPWEHz&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgN49g757u7-TDoIrclzOzXoBEyfj1QQFnUeXXueahd1ECIQCLJv2i7xocFuxJNoDsgg5Z-EpOx6Nyn0pySQJOYMhKvw%3D%3D"
[download] Destination: HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).f337.webm
[download] 100% of 409.98MiB in 01:25
[debug] Invoking downloader on "https://rr1---sn-jxou0gtapo3-2ime.googlevideo.com/videoplayback?expire=1644375925&ei=FdsCYrL6HP2ZsfIPqpOLuAw&ip=174.26.193.177&id=o-AKMrMFpq2azY3eJyr0VnnFzZnFALGI7S1d1jBJL5zAC1&itag=258&source=youtube&requiressl=yes&mh=ds&mm=31%2C29&mn=sn-jxou0gtapo3-2ime%2Csn-a5mlrn7z&ms=au%2Crdu&mv=m&mvi=1&pl=16&initcwndbps=1095000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=9127111&dur=188.224&lmt=1634253807944981&mt=1644354059&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5531222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAK9cNIbVfqTGk0TDK5XSSzDmNjAoXXAheMDOvZrBRy6qAiBFF_SRBxS9P6LGf-6Zx4CZxvwp4xaDeAaY6RHFLVT_1w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgN49g757u7-TDoIrclzOzXoBEyfj1QQFnUeXXueahd1ECIQCLJv2i7xocFuxJNoDsgg5Z-EpOx6Nyn0pySQJOYMhKvw%3D%3D"
[download] Destination: HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).f258.m4a
[download] 100% of 8.70MiB in 00:01
[Merger] Merging formats into "HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).f337.webm' -i 'file:HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).f258.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).temp.mkv'
Deleting original file HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).f258.m4a (pass -k to keep)
Deleting original file HDR Content/HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).f337.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
```
❯ yt-dlp -i -o "%(uploader)s/%(uploader)s - %(title)s.%(ext)s" --convert-thumbnails jpg --write-thumbnail "youtube.com/watch?v=2J7xlDH4QkA" -vU
[debug] Command-line config: ['-i', '-o', '%(uploader)s/%(uploader)s - %(title)s.%(ext)s', '--convert-thumbnails', 'jpg', '--write-thumbnail', 'youtube.com/watch?v=2J7xlDH4QkA', '-vU']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: cc5031097
[debug] Python version 3.10.2 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg N-105465-gbedb4bac1c-20220206 (fdk,setts), ffprobe N-105465-gbedb4bac1c-20220206
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: youtube.com/watch?v=2J7xlDH4QkA
WARNING: [generic] The url doesn't specify the protocol, trying with http
[debug] [youtube] Extracting URL: http://youtube.com/watch?v=2J7xlDH4QkA
[youtube] 2J7xlDH4QkA: Downloading webpage
[youtube] 2J7xlDH4QkA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2J7xlDH4QkA: Downloading 1 format(s): 337+258
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: HDR Content\HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).webp
[ThumbnailsConvertor] Converting thumbnail "HDR Content\HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).webp" to jpg
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -f image2 -pattern_type none -i "file:HDR Content\HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).webp" "-bsf:v" mjpeg2jpeg -movflags "+faststart" "file:HDR Content\HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).jpg"
Deleting original file HDR Content\HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).webp (pass -k to keep)
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking downloader on "https://rr1---sn-gwpa-jjwe.googlevideo.com/videoplayback?expire=1644531658&ei=ajsFYqXnOMik4t4PpL6EqAY&ip=2405%3A201%3Af003%3Ab2d0%3A7183%3Ad56b%3Ad576%3A93e2&id=o-APvw3fIyTRVexaDN5CFstF6_H_eb0tjRTYu5nPL6iO99&itag=337&source=youtube&requiressl=yes&mh=ds&mm=31%2C29&mn=sn-gwpa-jjwe%2Csn-gwpa-jwce&ms=au%2Crdu&mv=m&mvi=1&pl=48&initcwndbps=193750&vprv=1&mime=video%2Fwebm&gir=yes&clen=429896839&dur=188.133&lmt=1634155011373372&mt=1644509856&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgKv-hLp2CfTt0r7utDHyynXJXGnVabDxsf0agOnRWO38CIH7TjTJnooqeMS_lrmR4_i7ghbVlLzqq333_uoSONjZD&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIfN664zRZfs4H2WDnNRAx7fXEB9vZw8PmZSjECUCKIjAiEA903X-Nbm9SGncACq31gMz1BqCpwQkuh-Vh8nwIQ6BEM%3D"
[download] Destination: HDR Content\HDR Content - Real 4K HDR Dolby Test ultrahd movie for 4k oled tv (ULTRAHD HDR 10BIT Dolby Atmos).f337.webm
[download]   5.0% of 409.98MiB at  6.31MiB/s ETA 01:01
ERROR: Interrupted by user
Terminate batch job (Y/N)? y
```

**Comment by pukkandan** [comment]
The issue is that your ffmpeg is built with `--disable-muxer=image2`
