### ISSUE TITLE
brandnewtube.com extractor/downloader

### ISSUE THREAD

**Issue by progonkpa** [yt-dlp/yt-dlp#2715]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

World

### Example URLs

Single video: https://brandnewtube.com/watch/it-039-s-time-to-be-terrified_SQO8773gPTABngN.html

# channel
Playlist: https://brandnewtube.com/@DrVernonColeman

### Description

Support for downloading single videos and channels on brandnewtube.com

### Verbose log

```shell
[debug] Command-line config: ['--dump-single-json', '--verbose', 'https://brandnewtube.com/@DrVernonColeman']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.19-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://brandnewtube.com/@DrVernonColeman
[generic] @DrVernonColeman: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] @DrVernonColeman: Downloading webpage
[generic] @DrVernonColeman: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://brandnewtube.com/@DrVernonColeman
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://brandnewtube.com/@DrVernonColeman
```

**Comment by HobbyistDev** [comment]
It's work for single video in version `2022.05.18 [b14d523]`

Here's the log :
```
C:\Users\USER\Downloads>yt-dlp -v -s "https://brandnewtube.com/watch/it-039-s-time-to-be-terrified_SQO8773gPTABngN.html"
[debug] Command-line config: ['-v', '-s', 'https://brandnewtube.com/watch/it-039-s-time-to-be-terrified_SQO8773gPTABngN.html']
[debug] Portable config "C:\Users\USER\Downloads\yt-dlp\yt-dlp.conf": ['-v', '--netrc-location', 'C:UsersUSERDownloadsyt-dlp.netrc', '-f', 'bv+ba/b', '--compat-options', 'format-sort', '--embed-metadata', '--embed-subs', '--sub-langs', 'all', '--console-title', '--downloader', 'aria2c']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Compatibility options: format-sort
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://brandnewtube.com/watch/it-039-s-time-to-be-terrified_SQO8773gPTABngN.html
[generic] it-039-s-time-to-be-terrified_SQO8773gPTABngN: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] it-039-s-time-to-be-terrified_SQO8773gPTABngN: Downloading webpage
[generic] it-039-s-time-to-be-terrified_SQO8773gPTABngN: Extracting information
[debug] Looking for video embeds
[debug] Identified a HTML5 media
[debug] Sort order given by user: hasaud, lang, quality, tbr, filesize, vbr, height, width, proto, vext, abr, aext, fps, fs_approx, source, id
[debug] Formats sorted by: hasvid, ie_pref, hasaud, lang, quality, tbr, filesize, vbr, height, width, proto, vext, abr, aext, fps, fs_approx, source, id, res, hdr:12(7), vcodec:vp9.2(10), acodec, asr
[download] Downloading playlist: It's Time to be Terrified
[generic] playlist It's Time to be Terrified: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[info] it-039-s-time-to-be-terrified_SQO8773gPTABngN: Downloading 1 format(s): 1080p
[download] Finished downloading playlist: It's Time to be Terrified
```

But it still not work for playlist video
