### ISSUE TITLE
Funimation Error 4 No premium avails, but videos are available on website

### ISSUE THREAD

**Issue by Mindstorm1750** [yt-dlp/yt-dlp#2723]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Description

I was doing a batch series download when I noticed that some episodes in the same series and season were missing. Went back through the console and found issues with the English dub format not being available, Japanese is fine just English on particular episodes.
![image](https://user-images.githubusercontent.com/78426901/153483725-5a429bb9-e575-4b13-bbe6-0224ad62c169.png)
Video runs fine on the actual website.
I do have a premium account and have had this same error with different episodes from this series and others.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-o', '%(series)s-S%(season_number)sE%(episode_number)s-%(episode)s.%(ext)s', '--no-check-certificate', '--netrc', '--cookies', 'funimation.com_cookies.txt', 'http://www.funimation.com/v/a-certain-magical-index/remnant-wreckage', '--extractor-args', 'funimation:language=english']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.7.3 (CPython 32bit) - Linux-5.10.63-v7l+-armv7l-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: http://www.funimation.com/v/a-certain-magical-index/remnant-wreckage
[funimation:page] a-certain-magical-index_remnant-wreckage: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/609825
[Funimation] 609825: Downloading player webpage for 609825
[Funimation] remnant-wreckage: Downloading Uncut english (609825) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Premium Avails for this experience
ERROR: [Funimation] 93545: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1517, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2431, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/pi/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 962, in raise_no_formats
    expected=has_drm or expected)
yt_dlp.utils.ExtractorError: [Funimation] 93545: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
```
EDIT: Forgot to add, when i do --list formats i get this:

[debug] Command-line config: ['-vU', '-o', '%(series)s-S%(season_number)sE%(episode_number)s-%(episode)s.%(ext)s', '--no-check-certificate', '--netrc', '--cookies', 'funimation.com_cookies.txt', 'http://www.funimation.com/v/a-certain-magical-index/remnant-wreckage', '--list-formats']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [https://github.com/yt-dlp/yt-dlp/commit/c1653e9efba2768910e6a5f62c88c7a95317b431]
[debug] Python version 3.7.3 (CPython 32bit) - Linux-5.10.63-v7l+-armv7l-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: http://www.funimation.com/v/a-certain-magical-index/remnant-wreckage
[funimation:page] a-certain-magical-index_remnant-wreckage: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/609825
[Funimation] 609825: Downloading player webpage for 609825
[Funimation] remnant-wreckage: Downloading Uncut japanese (982216) JSON
[Funimation] remnant-wreckage: Downloading Uncut japanese (982216) m3u8 information
[Funimation] remnant-wreckage: Downloading Uncut english (609825) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Premium Avails for this experience
[debug] Sort order given by extractor: lang, source
[debug] Formats sorted by: hasvid, ie_pref, lang, source, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] Available formats for 93545:
ID EXT RESOLUTION FPS │ FILESIZE TBR PROTO │ VCODEC VBR ACODEC MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
982216-hls-audio-aacl-256-Japanese mp4 audio only │ m3u8_n │ audio only unknown [japanese] Uncut
982216-mp4 mp4 unknown │ https │ unknown unknown [japanese] Uncut
982216-hls-416 mp4 416x234 23 │ ~ 73.68MiB 416k m3u8_n │ avc1.4D4028 416k video only [japanese] Uncut
982216-hls-574 mp4 640x360 23 │ ~101.67MiB 574k m3u8_n │ avc1.4D4028 574k video only [japanese] Uncut
982216-hls-849 mp4 768x432 23 │ ~150.38MiB 849k m3u8_n │ avc1.4D4028 849k video only [japanese] Uncut
982216-hls-1157 mp4 768x432 23 │ ~204.93MiB 1157k m3u8_n │ avc1.4D4028 1157k video only [japanese] Uncut
982216-hls-1825 mp4 960x540 23 │ ~323.25MiB 1825k m3u8_n │ avc1.4D4028 1825k video only [japanese] Uncut
982216-hls-2553 mp4 1280x720 23 │ ~452.20MiB 2553k m3u8_n │ avc1.640028 2553k video only [japanese] Uncut
982216-hls-3842 mp4 1280x720 23 │ ~680.51MiB 3842k m3u8_n │ avc1.640028 3842k video only [japanese] Uncut
982216-hls-4919 mp4 1920x1080 23 │ ~871.27MiB 4919k m3u8_n │ avc1.640028 4919k video only [japanese] Uncut
982216-hls-6497 mp4 1920x1080 23 │ ~ 1.12GiB 6497k m3u8_n │ avc1.640028 6497k video only [japanese] Uncut

**Comment by Mindstorm1750** [comment]
Forgot to add, when i do --list formats i get this:
[debug] Command-line config: ['-vU', '-o', '%(series)s-S%(season_number)sE%(episode_number)s-%(episode)s.%(ext)s', '--no-check-certificate', '--netrc', '--cookies', 'funimation.com_cookies.txt', 'http://www.funimation.com/v/a-certain-magical-index/remnant-wreckage', '--list-formats']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.7.3 (CPython 32bit) - Linux-5.10.63-v7l+-armv7l-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: http://www.funimation.com/v/a-certain-magical-index/remnant-wreckage
[funimation:page] a-certain-magical-index_remnant-wreckage: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/609825
[Funimation] 609825: Downloading player webpage for 609825
[Funimation] remnant-wreckage: Downloading Uncut japanese (982216) JSON
[Funimation] remnant-wreckage: Downloading Uncut japanese (982216) m3u8 information
[Funimation] remnant-wreckage: Downloading Uncut english (609825) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Premium Avails for this experience
[debug] Sort order given by extractor: lang, source
[debug] Formats sorted by: hasvid, ie_pref, lang, source, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] Available formats for 93545:
ID                                 EXT RESOLUTION FPS │   FILESIZE   TBR PROTO  │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
982216-hls-audio-aacl-256-Japanese mp4 audio only     │                  m3u8_n │ audio only        unknown    [japanese] Uncut
982216-mp4                         mp4 unknown        │                  https  │ unknown           unknown    [japanese] Uncut
982216-hls-416                     mp4 416x234     23 │ ~ 73.68MiB  416k m3u8_n │ avc1.4D4028  416k video only [japanese] Uncut
982216-hls-574                     mp4 640x360     23 │ ~101.67MiB  574k m3u8_n │ avc1.4D4028  574k video only [japanese] Uncut
982216-hls-849                     mp4 768x432     23 │ ~150.38MiB  849k m3u8_n │ avc1.4D4028  849k video only [japanese] Uncut
982216-hls-1157                    mp4 768x432     23 │ ~204.93MiB 1157k m3u8_n │ avc1.4D4028 1157k video only [japanese] Uncut
982216-hls-1825                    mp4 960x540     23 │ ~323.25MiB 1825k m3u8_n │ avc1.4D4028 1825k video only [japanese] Uncut
982216-hls-2553                    mp4 1280x720    23 │ ~452.20MiB 2553k m3u8_n │ avc1.640028 2553k video only [japanese] Uncut
982216-hls-3842                    mp4 1280x720    23 │ ~680.51MiB 3842k m3u8_n │ avc1.640028 3842k video only [japanese] Uncut
982216-hls-4919                    mp4 1920x1080   23 │ ~871.27MiB 4919k m3u8_n │ avc1.640028 4919k video only [japanese] Uncut
982216-hls-6497                    mp4 1920x1080   23 │ ~  1.12GiB 6497k m3u8_n │ avc1.640028 6497k video only [japanese] Uncut

**Comment by nmills3** [comment]
I'm unsure if my issue is related but i'm currently having issues downloading the correct language of a show where that language required premium (i do have a premium membership) it happened at around 9pm yesterday when i was in the middle of downloaing a show. got the forst 3 episodes in English and the rest in Japanese and now i can only get JP to work

**Comment by pukkandan** [comment]
Try with only cookies and no netrc

Related: https://github.com/yt-dlp/yt-dlp/issues/1569

**Comment by Mindstorm1750** [comment]
Follow up, logged into funimation with my account and accessed the player page directly with this: https://www.funimation.com/player/609825
which resulted in the following screen
![image](https://user-images.githubusercontent.com/78426901/153633670-00d1eb35-5128-43ae-84ba-6139a7f53fda.png)
So this may be an issue on funimations end, but i have no idea really. 
The weird thing is, is that the video plays fine on the funimation website without hitting the player page directly.
Any thoughts?

**Comment by pukkandan** [comment]
Most likely same underlying issue as https://github.com/yt-dlp/yt-dlp/issues/2255

The whole extractor looks like it needs rewriting

**Comment by Mindstorm1750** [comment]
Seems like the problem has kind of resolved its self:
It Looks like funimation are currently re-jiggling their database, note the player ids are different this time compared to last. So my advice to others with similar issues, give it 3-4 days it seems to have worked for me

[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.7.3 (CPython 32bit) - Linux-5.10.63-v7l+-armv7l-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [funimation:page] Extracting URL: https://www.funimation.com/en/shows/a-certain-magical-index/remnant-wreckage/
[funimation:page] a-certain-magical-index_remnant-wreckage: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/982250
[Funimation] 982250: Downloading player webpage for 982250
[Funimation] remnant-wreckage: Downloading Uncut english (982250) JSON
[Funimation] remnant-wreckage: Downloading Uncut english (982250) m3u8 information
[debug] Sort order given by extractor: lang, source
[debug] Formats sorted by: hasvid, ie_pref, lang, source, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] Available formats for 93545:
ID                                EXT RESOLUTION FPS │   FILESIZE   TBR PROTO  │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
982250-hls-audio-aacl-256-English mp4 audio only     │                  m3u8_n │ audio only        unknown    [english] Uncut
982250-mp4                        mp4 unknown        │                  https  │ unknown           unknown    [english] Uncut
982250-hls-416                    mp4 416x234     23 │ ~ 73.68MiB  416k m3u8_n │ avc1.4D4028  416k video only [english] Uncut
982250-hls-577                    mp4 640x360     23 │ ~102.20MiB  577k m3u8_n │ avc1.4D4028  577k video only [english] Uncut
982250-hls-848                    mp4 768x432     23 │ ~150.20MiB  848k m3u8_n │ avc1.4D4028  848k video only [english] Uncut
982250-hls-1154                   mp4 768x432     23 │ ~204.40MiB 1154k m3u8_n │ avc1.4D4028 1154k video only [english] Uncut
982250-hls-1830                   mp4 960x540     23 │ ~324.14MiB 1830k m3u8_n │ avc1.4D4028 1830k video only [english] Uncut
982250-hls-2539                   mp4 1280x720    23 │ ~449.72MiB 2539k m3u8_n │ avc1.640028 2539k video only [english] Uncut
982250-hls-3814                   mp4 1280x720    23 │ ~675.55MiB 3814k m3u8_n │ avc1.640028 3814k video only [english] Uncut
982250-hls-4756                   mp4 1920x1080   23 │ ~842.40MiB 4756k m3u8_n │ avc1.640028 4756k video only [english] Uncut
982250-hls-6461                   mp4 1920x1080   23 │ ~  1.12GiB 6461k m3u8_n │ avc1.640028 6461k video only [english] Uncut

**Comment by Jules-A** [comment]
> Seems like the problem has kind of resolved its self: It Looks like funimation are currently re-jiggling their database, note the player ids are different this time compared to last.

Doubt it, it's more likely that since you were using outdated cookies it was trying to serve you simulcast (since Uncut is usually members only) before, once you retried with fresh cookies it was able to serve you uncut (and hence a different player url).

**Comment by Mindstorm1750** [comment]
> > Seems like the problem has kind of resolved its self: It Looks like funimation are currently re-jiggling their database, note the player ids are different this time compared to last.
> 
> Doubt it, it's more likely that since you were using outdated cookies it was trying to serve you simulcast (since Uncut is usually members only) before, once you retried with fresh cookies it was able to serve you uncut (and hence a different player url).

When i first did it i did refresh the cookies and im still using the same ones from last time. in addition the problem still arises with other episodes from this series and others its just 4 (out of 7) of the ones on this series are working for me now

**Comment by LustWolf** [comment]
Similar issues here. Happened out of nowhere. Refreshing cookies doesn't matter.

**Comment by gw711** [comment]
Trying to show my brother how to use mpv+yt-dlp to watch funimation. I can do yt-dlp commands against funi successfully, but when he runs the exact same commands he gets this result:
`[funimation:page] kaguya-sama-love-is-war_miko-iino-wants-to-be-soothed-kaguya-doesnt-realize-chika-fujiwara-wants-to-battle: Downloading JSON metadata
[Funimation] 4184947: Downloading player webpage for 4184947
[Funimation] miko-iino-wants-to-be-soothed-kaguya-doesnt-realize-chika-fujiwara-wants-to-battle: Downloading Simulcast japanese (4167943) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Free Avails for this experience
[Funimation] miko-iino-wants-to-be-soothed-kaguya-doesnt-realize-chika-fujiwara-wants-to-battle: Downloading Simulcast english (4184947) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Free Avails for this experience
ERROR: [Funimation] 4167941: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

**Comment by Lesmiscore** [comment]
You have to pass cookies to watch such episodes (as it says `Error 4 - No valid Free Avails for this experience`).

**Comment by gw711** [comment]
> @gw711 You have to pass cookies to watch such episodes (as it says `Error 4 - No valid Free Avails for this experience`).

But I can do it successfully without cookies, as this episode doesn't even require a login:
`C:\Users\gw>yt-dlp -F https://www.funimation.com/v/kaguya-sama-love-is-war/ai-hayasaka-wants-to-stave-them-off-the-student-council-has-not-achieved-nirvana-kaguya-wants-to-get-
married-kaguya-wants-to-celebrate
[funimation:page] Checking geo-location
[funimation:page] kaguya-sama-love-is-war_ai-hayasaka-wants-to-stave-them-off-the-student-council-has-not-achieved-nirvana-kaguya-wants-to-get-married-kaguya-wants-to-celebrate: Do
wnloading JSON metadata
[Funimation] 1136851: Downloading player webpage for 1136851
[Funimation] ai-hayasaka-wants-to-stave-them-off-the-student-council-has-not-achieved-nirvana-kaguya-wants-to-get-married-kaguya-wants-to-celebrate: Downloading Simulcast japanese
(1079007) JSON
[Funimation] ai-hayasaka-wants-to-stave-them-off-the-student-council-has-not-achieved-nirvana-kaguya-wants-to-get-married-kaguya-wants-to-celebrate: Downloading Simulcast japanese
(1079007) m3u8 information
[Funimation] ai-hayasaka-wants-to-stave-them-off-the-student-council-has-not-achieved-nirvana-kaguya-wants-to-get-married-kaguya-wants-to-celebrate: Downloading Simulcast english (
1136851) JSON
[Funimation] ai-hayasaka-wants-to-stave-them-off-the-student-council-has-not-achieved-nirvana-kaguya-wants-to-get-married-kaguya-wants-to-celebrate: Downloading Simulcast english (
1136851) m3u8 information
[info] Available formats for 1079003:
ID                                  EXT RESOLUTION FPS |   FILESIZE   TBR PROTO  | VCODEC        VBR ACODEC     MORE INFO
------------------------------------------------------------------------------------------------------------------------------------
1079007-hls-audio-aacl-256-Japanese mp4 audio only     |                  m3u8_n | audio only        unknown    [japanese] Simulcast
1136851-hls-audio-aacl-256-English  mp4 audio only     |                  m3u8_n | audio only        unknown    [english] Simulcast
1079007-mp4                         mp4 unknown        |                  https  | unknown           unknown    [japanese] Simulcast
1136851-mp4                         mp4 unknown        |                  https  | unknown           unknown    [english] Simulcast
1079007-hls-415                     mp4 416x234     23 | ~ 76.60MiB  415k m3u8_n | avc1.4D4028  415k video only [japanese] Simulcast
1136851-hls-416                     mp4 416x234     23 | ~ 76.78MiB  416k m3u8_n | avc1.4D4028  416k video only [english] Simulcast
1079007-hls-574                     mp4 640x360     23 | ~105.94MiB  574k m3u8_n | avc1.4D4028  574k video only [japanese] Simulcast
1136851-hls-577                     mp4 640x360     23 | ~106.50MiB  577k m3u8_n | avc1.4D4028  577k video only [english] Simulcast
1079007-hls-848                     mp4 768x432     23 | ~156.52MiB  848k m3u8_n | avc1.4D4028  848k video only [japanese] Simulcast
1136851-hls-848                     mp4 768x432     23 | ~156.52MiB  848k m3u8_n | avc1.4D4028  848k video only [english] Simulcast
1136851-hls-1146                    mp4 768x432     23 | ~211.52MiB 1146k m3u8_n | avc1.4D4028 1146k video only [english] Simulcast
1079007-hls-1148                    mp4 768x432     23 | ~211.89MiB 1148k m3u8_n | avc1.4D4028 1148k video only [japanese] Simulcast
1079007-hls-1810                    mp4 960x540     23 | ~334.07MiB 1810k m3u8_n | avc1.4D4028 1810k video only [japanese] Simulcast
1136851-hls-1811                    mp4 960x540     23 | ~334.26MiB 1811k m3u8_n | avc1.4D4028 1811k video only [english] Simulcast
1136851-hls-2497                    mp4 1280x720    23 | ~460.87MiB 2497k m3u8_n | avc1.640028 2497k video only [english] Simulcast
1079007-hls-2506                    mp4 1280x720    23 | ~462.53MiB 2506k m3u8_n | avc1.640028 2506k video only [japanese] Simulcast
1136851-hls-3722                    mp4 1280x720    23 | ~686.97MiB 3722k m3u8_n | avc1.640028 3722k video only [english] Simulcast
1079007-hls-3742                    mp4 1280x720    23 | ~690.66MiB 3742k m3u8_n | avc1.640028 3742k video only [japanese] Simulcast
1136851-hls-4834                    mp4 1920x1080   23 | ~892.21MiB 4834k m3u8_n | avc1.640028 4834k video only [english] Simulcast
1079007-hls-4955                    mp4 1920x1080   23 | ~914.55MiB 4955k m3u8_n | avc1.640028 4955k video only [japanese] Simulcast
1136851-hls-6365                    mp4 1920x1080   23 | ~  1.15GiB 6365k m3u8_n | avc1.640028 6365k video only [english] Simulcast
1079007-hls-6523                    mp4 1920x1080   23 | ~  1.18GiB 6523k m3u8_n | avc1.640028 6523k video only [japanese] Simulcast

C:\Users\gw>`
I have a config that passes --no-check-certificate to get around another issue, but anyway I don't need cookies for this. It's just my brother that gets the Error 4 issue.

**Comment by Mindstorm1750** [comment]
@gw711 can we see the full command for starters?
