### ISSUE TITLE
error writing the internet shortcut files 

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2724]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Sorry, probably my mistake somehow, but I can't figure out what's wrong.

`yt-dlp https://www.srf.ch/play/tv/nano/video/nano?urn=urn:srf:video:53fc3711-4e59-48cc-94bf-8102ceadd333 --ignore-config` works for me

but without `--ignore-config` I get an error.

So the logical explanation would be that there is an error in my config file.
However, I don't get any errors with my config file on any other site.
So I don't know what the problem is.

Here is the log:

### Verbose log

```shell
[debug] Command-line config: ['https://www.srf.ch/play/tv/nano/video/nano?urn=urn:srf:video:53fc3711-4e59-48cc-94bf-8102ceadd333', '-f', 'best']
[debug] Portable config "C:\hp\-\setups\+downloaders\yt-dlp\appdir\yt-dlp.conf": ['--verbose', '--format-sort', 'hasvid,ie_pref,quality,res,hdr,codec,size,br,asr,ext,fps,hasaud,lang,source,proto,id', '-f', 'bestvideo*+bestaudio/best', '--paths', 'c:\\Users\\User\\Downloads\\yt', '-o', '.\\%(playlist|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'thumbnail:.\\%(playlist|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\\thumbs\\thumb.%(ext)s', '-o', 'subtitle:.\\%(playlist|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\\subs\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'infojson:.\\%(playlist|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\\!nfo\\%(alt_title,title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'link:.\\%(playlist|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\\!nfo\\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'description:.\\%(playlist|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\\!nfo\\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'annotation:.\\%(playlist|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\\!nfo\\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].%(ext)s', '-o', 'pl_infojson:.\\%(playlist|)s\\playlist.%(ext)s', '-o', 'pl_thumbnail:.\\%(playlist|)s\\folder.%(ext)s', '-o', 'pl_description:.\\%(playlist|)s\\playlist description.%(ext)s', '--output-na-placeholder', '~~~', '--write-info-json', '--write-description', '--write-annotations', '--no-overwrites', '--no-post-overwrites', '--merge-output-format', 'mkv', '--remux-video', 'mkv', '--write-subs', '--write-auto-subs', '--all-subs', '--sub-langs', 'all', '--sub-format', 'all/ttml/vtt/best', '--write-thumbnail', '--write-all-thumbnails', '--add-metadata', '--embed-chapters', '--add-chapters', '--write-link', '--write-url-link', '--write-desktop-link', '--no-check-certificate', '--retries', 'infinite', '--geo-bypass', '--geo-bypass-country', 'DE', '--no-clean-infojson', '--write-comments', '--audio-multistreams', '--no-playlist']
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 53.37.198.146 (DE) as X-Forwarded-For
[debug] [SRGSSRPlay] Extracting URL: https://www.srf.ch/play/tv/nano/video/nano?urn=urn:srf:video:53fc3711-4e59-48cc-94bf-8102ceadd333
[debug] Using fake IP 53.144.36.234 (DE) as X-Forwarded-For
[debug] [SRGSSR] Extracting URL: srgssr:srf:video:53fc3711-4e59-48cc-94bf-8102ceadd333
[SRGSSR] 53fc3711-4e59-48cc-94bf-8102ceadd333: Downloading JSON metadata
[SRGSSR] 53fc3711-4e59-48cc-94bf-8102ceadd333: Downloading HLS-H264-HD token
[SRGSSR] 53fc3711-4e59-48cc-94bf-8102ceadd333: Downloading f4m manifest
[SRGSSR] 53fc3711-4e59-48cc-94bf-8102ceadd333: Downloading m3u8 information
[SRGSSR] 53fc3711-4e59-48cc-94bf-8102ceadd333: Downloading HLS-H264-SD token
[SRGSSR] 53fc3711-4e59-48cc-94bf-8102ceadd333: Downloading f4m manifest
[SRGSSR] 53fc3711-4e59-48cc-94bf-8102ceadd333: Downloading m3u8 information
[debug] Sort order given by user: hasvid, ie_pref, quality, res, hdr, codec, size, br, asr, ext, fps, hasaud, lang, source, proto, id
[debug] Formats sorted by: hasvid, ie_pref, quality, res, hdr, vcodec, acodec, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, fps, hasaud, lang, source, proto, id
[info] 53fc3711-4e59-48cc-94bf-8102ceadd333: Downloading 1 format(s): hls-3625
[info] Writing video description to: c:\Users\User\Downloads\yt\2022-02-10 nano\!nfo\nano [SRGSSR.SRGSSR.53fc3711-4e59-48cc-94bf-8102ceadd333] [hls-3625].description
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: c:\Users\User\Downloads\yt\2022-02-10 nano\nano [SRGSSR.SRGSSR.53fc3711-4e59-48cc-94bf-8102ceadd333] [hls-3625].png
[info] Writing video metadata as JSON to: c:\Users\User\Downloads\yt\2022-02-10 nano\!nfo\nano [SRGSSR.SRGSSR.53fc3711-4e59-48cc-94bf-8102ceadd333] [hls-3625].info.json
WARNING: There are no annotations to write.
[info] Writing internet shortcut (.url) to: c:\Users\User\Downloads\yt\2022-02-10 nano\!nfo\nano [SRGSSR.SRGSSR.53fc3711-4e59-48cc-94bf-8102ceadd333] [hls-3625].url
ERROR: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2607, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2929, in process_info
  File "yt_dlp\YoutubeDL.py", line 2929, in <genexpr>
  File "yt_dlp\YoutubeDL.py", line 2909, in _write_link_file
  File "yt_dlp\utils.py", line 4940, in iri_to_uri
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by coletdjnz** [comment]
Seems to be a bug with writing the internet shortcut files (`--write-link, --write-url-link, --write-desktop-link', --write-webloc-link`). I think it has something to do when using the URL provided to the extractor that is not a valid URI. Happens with `ytarchive:dWW7qP423y8` too. 

(on another note, `--force-overwrites` doesn't work with these options either)
