### ISSUE TITLE
[Broken] Patreon's Vimeo embeds

### ISSUE THREAD

**Issue by TheFrenchGhosty** [yt-dlp/yt-dlp#274]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ yt-dlp --verbose --cookies patreon.com_cookies.txt [REDACTED]
[debug] Command-line config: ['--verbose', '--cookies', 'patreon.com_cookies.txt', '[REDACTED]']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.11 
[debug] Python version 3.9.3 (CPython 64bit) - Linux-5.11.16-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[Patreon] [REDACTED]: Downloading JSON metadata
[vimeo] [REDACTED]: Downloading webpage
[vimeo] [REDACTED]: Extracting information
ERROR: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/vimeo.py", line 723, in _real_extract
    page_config = self._parse_json(self._search_regex(
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1057, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/vimeo.py", line 746, in _real_extract
    config = json.loads(config)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/vimeo.py", line 723, in _real_extract
    page_config = self._parse_json(self._search_regex(
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1057, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract page config; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/vimeo.py", line 746, in _real_extract
    config = json.loads(config)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1059, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1080, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/yt_dlp/extractor/vimeo.py", line 761, in _real_extract
    raise ExtractorError('Unable to extract info section',
yt_dlp.utils.ExtractorError: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Patreon's Vimeo embeds can't be downloaded, this is also an issue on youtube-dl itself

**Comment by pukkandan** [comment]
Can't do anything without URL and account details. You can PM me on discord/reddit
