### ISSUE TITLE
go.tlc.com Broken

### ISSUE THREAD

**Issue by CplPwnies** [yt-dlp/yt-dlp#2752]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

As the title states, https://go.tlc.com is broken. It always returns with the error: 
> This video is only available for registered users. You may want to use --cookies.

I believe part of the issue to be is when you export a cookie from the site to feed into yt-dlp (using EditThisCookie), it does not export the `st` cookie. (token). And then the override method [here ](https://github.com/yt-dlp/yt-dlp/blob/29448350808619262d6a9ddd393a2c28df1720fe/yt_dlp/extractor/dplay.py#L351) for the base class does not allow it to use the [_get_auth method](https://github.com/yt-dlp/yt-dlp/blob/29448350808619262d6a9ddd393a2c28df1720fe/yt_dlp/extractor/dplay.py#L24) to grab a new token programmatically.

Even after playing with the source myself to allow it to grab a new token programmatically so it grabs the `st` cookie, it returns a `404: not found'`.

And since I didn't run it originally with the -U command, here is output proving I am on the latest version:
```
> python -m yt_dlp -U
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
```

### Verbose log

```shell
Without "st" cookie token:

> python -m yt_dlp 'https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins' --verbose --cookies ..\tCookie.txt
[debug] Command-line config: ['https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins', '--verbose', '--cookies', '..\\tCookie.txt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.8.2 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-94563-g3aeb681f07, ffprobe N-94563-g3aeb681f07
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [TLC] Extracting URL: https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins
[debug] Using fake IP 6.150.51.161 (US) as X-Forwarded-For
[TLC] cake-boss-tlc-atve-us/creeps-carvings-and-coffins: Downloading JSON metadata
ERROR: [TLC] cake-boss-tlc-atve-us/creeps-carvings-and-coffins: This video is only available for registered users. You may want to use --cookies.
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 369, in _real_extract
    return self._get_disco_api_info(url, self._match_id(url), **self._DISCO_API_PARAMS)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 92, in _get_disco_api_info
    self._process_errors(e, geo_countries)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 50, in _process_errors
    raise ExtractorError(

After playing with the source to allow it to grab a new token:
> python -m yt_dlp 'https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins' --verbose --cookies ..\tCookie.txt
[debug] Command-line config: ['https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins', '--verbose', '--cookies', '..\\tCookie.txt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.8.2 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-94563-g3aeb681f07, ffprobe N-94563-g3aeb681f07
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [TLC] Extracting URL: https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins
[debug] Using fake IP 6.232.106.196 (US) as X-Forwarded-For
[TLC] cake-boss-tlc-atve-us/creeps-carvings-and-coffins: Downloading JSON metadata
ERROR: [TLC] cake-boss-tlc-atve-us/creeps-carvings-and-coffins: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\common.py", line 730, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\YoutubeDL.py", line 3558, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\Vash\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Vash\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\Vash\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Vash\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Vash\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by Mr-Jake** [comment]
I also got the TLC 404 error, but was able to get it to work thanks to this comment in the pull request. It is a simple one line edit to dplay.py

https://github.com/yt-dlp/yt-dlp/pull/2401#issuecomment-1018904716

**Comment by pukkandan** [comment]
@Sipherdrakon can u confirm this?

**Comment by Sipherdrakon** [comment]
It works fine for me...

```[debug] Command-line config: ['-o', '%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL-%(height)s].%(ext)s', '-f', 'best', '-ic', '--newline', '--extractor-retries', 'infinite', '--downloader', 'dash,m3u8:ffmpeg', '--no-skip-unavailable-fragments', '--ffmpeg-location', 'D:\\ffmpeg301', '--no-part', '-N50', '--cookies-from-browser', 'chrome', '--download-archive', 'done.txt', '--console-title', '--all-subs', '--embed-subs', '-a', 'ytdlready.txt', '-v']
[debug] Batch file urls: ['https://go.tlc.com/video/90-day-fiance-tlc-atve-us/i-think-youre-my-future-wife']
[0;33mWARNING:[0m "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Sipherdrakon\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[Cookies] Extracted 2988 cookies from chrome
[debug] cookie version breakdown: {'v10': 2988, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8] (win_exe)
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.4 (CPython 64bit) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 3.0.1 (needs_adtstoasc), ffprobe 3.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'done.txt'
[debug] [TLC] Extracting URL: https://go.tlc.com/video/90-day-fiance-tlc-atve-us/i-think-youre-my-future-wife
[debug] Using fake IP 6.211.249.102 (US) as X-Forwarded-For
[TLC] 90-day-fiance-tlc-atve-us/i-think-youre-my-future-wife: Downloading JSON metadata
[TLC] 2236678: Downloading JSON metadata
[TLC] 90-day-fiance-tlc-atve-us/i-think-youre-my-future-wife: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 2236678: Downloading 1 format(s): hls-5281
[debug] Invoking downloader on "https://content-ausw2-ur-discovery1.uplynk.com/22bc319c0e974b58abcc2fb86b4f3371/f.m3u8?pbs=75e7cbb2776c4a45b163aa09ac3a159d"
[download] Destination: 90 Day Fiancé - 08x01 - I Think You're My Future Wife [WEBDL-1080].mp4
[debug] ffmpeg command line: "D:\ffmpeg301\ffmpeg" -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.32 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
referer:
X-Forwarded-For: 6.211.249.102
" -i "https://content-ausw2-ur-discovery1.uplynk.com/22bc319c0e974b58abcc2fb86b4f3371/f.m3u8?pbs=75e7cbb2776c4a45b163aa09ac3a159d" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:90 Day Fiancé - 08x01 - I Think You're My Future Wife [WEBDL-1080].mp4"
ffmpeg version 3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[hls,applehttp @ 000001fbc9aab8a0] HLS request for url 'https://content-ausw2-ur-discovery1.uplynk.com/vodredir4/22bc319c0e974b58abcc2fb86b4f3371/F00000000.ts?seq=0&pbs=75e7cbb2776c4a45b163aa09ac3a159d&ptime=4.096&atomic=1&ohash=aHR0cHM6Ly94LWRlZmF1bHQtc3RnZWMudXBseW5rLmNvbS9hdXN3L3NsaWNlcy8yMmIvZTZjZjBjNTVkYWMyNDlmMGEwZjcyZTdjNzJlNmY2Y2IvMjJiYzMxOWMwZTk3NGI1OGFiY2MyZmI4NmI0ZjMzNzEvRjAwMDAwMDAwLnRzP3Bicz03NWU3Y2JiMjc3NmM0YTQ1YjE2M2FhMDlhYzNhMTU5ZCZjbG91ZD1hd3MmY2RuPWVjaSZzaT0wJmQ9NC4wOTY=', offset 0, playlist 0
```

**Comment by Sipherdrakon** [comment]
It works fine for me...

```
[debug] Command-line config: ['-o', '%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL-%(height)s].%(ext)s', '-f', 'best', '-ic', '--newline', '--extractor-retries', 'infinite', '--downloader', 'dash,m3u8:ffmpeg', '--no-skip-unavailable-fragments', '--ffmpeg-location', 'D:\\ffmpeg301', '--no-part', '-N50', '--cookies-from-browser', 'chrome', '--download-archive', 'done.txt', '--console-title', '--all-subs', '--embed-subs', '-a', 'ytdlready.txt', '-v']
[debug] Batch file urls: ['https://go.tlc.com/video/90-day-fiance-tlc-atve-us/i-think-youre-my-future-wife']
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Sipherdrakon\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[Cookies] Extracted 2982 cookies from chrome
[debug] cookie version breakdown: {'v10': 2982, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 3.0.1 (needs_adtstoasc), ffprobe 3.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'done.txt'
[debug] [TLC] Extracting URL: https://go.tlc.com/video/90-day-fiance-tlc-atve-us/i-think-youre-my-future-wife
[debug] Using fake IP 6.134.122.137 (US) as X-Forwarded-For
[TLC] 90-day-fiance-tlc-atve-us/i-think-youre-my-future-wife: Downloading JSON metadata
[TLC] 2236678: Downloading JSON metadata
[TLC] 90-day-fiance-tlc-atve-us/i-think-youre-my-future-wife: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 2236678: Downloading 1 format(s): hls-5281
[download] I Think You're My Future Wife has already been recorded in the archive
```

**Comment by CplPwnies** [comment]
So I tried adding the line that @Mr-Jake mentioned above and I still am encountering the same issue:
```
[debug] Command-line config: ['https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins', '-vU', '--cookies', '..\\tCookie.txt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.8.2 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-94563-g3aeb681f07, ffprobe N-94563-g3aeb681f07
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [TLC] Extracting URL: https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins
[debug] Using fake IP 6.65.26.22 (US) as X-Forwarded-For
[TLC] cake-boss-tlc-atve-us/creeps-carvings-and-coffins: Downloading JSON metadata
ERROR: [TLC] cake-boss-tlc-atve-us/creeps-carvings-and-coffins: This video is only available for registered users. You may want to use --cookies.
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 370, in _real_extract
    return self._get_disco_api_info(url, self._match_id(url), **self._DISCO_API_PARAMS)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 92, in _get_disco_api_info
    self._process_errors(e, geo_countries)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 50, in _process_errors
    raise ExtractorError(
```

**Comment by CplPwnies** [comment]
Another Update:

I updated the  `_update_disco_api_headers` method to:
```
def _update_disco_api_headers(self, headers, disco_base, display_id, realm):
        headers['x-disco-client'] = f'WEB:UNKNOWN:{self._PRODUCT}:25.2.6'
        headers['X-disco-params'] = 'realm=go,siteLookupKey=%s,features=ar' % self._PRODUCT
        headers['Authorization'] = self._get_auth(disco_base, display_id, realm, False)
```

And now I am getting a `DeviceId Missing` error:
```
[debug] Command-line config: ['https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins', '-vU', '--cookies', '..\\tCookie.txt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.8.2 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-94563-g3aeb681f07, ffprobe N-94563-g3aeb681f07
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [TLC] Extracting URL: https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins
[debug] Using fake IP 6.117.115.189 (US) as X-Forwarded-For
[TLC] cake-boss-tlc-atve-us/creeps-carvings-and-coffins: Downloading JSON metadata
[TLC] 2158260: Downloading JSON metadata
ERROR: [TLC] cake-boss-tlc-atve-us/creeps-carvings-and-coffins: DeviceId missing
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 371, in _real_extract
    return self._get_disco_api_info(url, self._match_id(url), **self._DISCO_API_PARAMS)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 104, in _get_disco_api_info
    self._process_errors(e, geo_countries)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 52, in _process_errors
    raise ExtractorError(info['errors'][0]['detail'], expected=True)
```

**Comment by CplPwnies** [comment]
Another update - I got this working, but I had to do a few things:

1) I had to update the `_update_disco_api_headers` the same as mentioned above:
```
def _update_disco_api_headers(self, headers, disco_base, display_id, realm):
        headers['x-disco-client'] = f'WEB:UNKNOWN:{self._PRODUCT}:25.2.6'
        headers['X-disco-params'] = 'realm=go,siteLookupKey=%s,features=ar' % self._PRODUCT
```

2) Based on @Sipherdrakon 's command line above, I had to explicitly use `--cookies-from-browser 'chrome'`. An exported cookie file (using EditThisCookie plugin) or using `--cookies-from-browser 'edge'` (specifically my case) Did not work at all

3) I also had to use `--no-geo-bypass` based on issue #1623

Additionally, I noticed it also does not attempt an mvpd login even though go.tlc.com supports this.

Based from testing above where I ran into the `DeviceId missing` error. When I add in the `--no-geo-bypass` option to the same command line, I end up back at `This video is only available for registered users`:
```
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.8.2 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-94563-g3aeb681f07, ffprobe N-94563-g3aeb681f07
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [TLC] Extracting URL: https://go.tlc.com/video/cake-boss-tlc-atve-us/creeps-carvings-and-coffins
[TLC] cake-boss-tlc-atve-us/creeps-carvings-and-coffins: Downloading JSON metadata
[TLC] 2158260: Downloading JSON metadata
ERROR: [TLC] cake-boss-tlc-atve-us/creeps-carvings-and-coffins: This video is only available for registered users. You may want to use --cookies.
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 375, in _real_extract
    return self._get_disco_api_info(url, self._match_id(url), **self._DISCO_API_PARAMS)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 105, in _get_disco_api_info
    self._process_errors(e, geo_countries)
  File "C:\NeverFindMe\yt-dlp-2022.02.04\yt_dlp\extractor\dplay.py", line 51, in _process_errors
    raise ExtractorError(
```

So, I think there's still some tweaking for this extractor.

**Comment by jajajaime** [comment]
I was getting this same response from a TLC video, but instead using `--cookies`, I used `--cookies-from-browser chrome` and it work without issues.

**Comment by EagleScreech** [comment]
> I was getting this same response from a TLC video, but instead using `--cookies`, I used `--cookies-from-browser chrome` and it work without issues.

This worked for me. However, it would be nice if `--cookies` would work instead of a workaround.

**Comment by CplPwnies** [comment]
> > I was getting this same response from a TLC video, but instead using `--cookies`, I used `--cookies-from-browser chrome` and it work without issues.
> 
> This worked for me. However, it would be nice if `--cookies` would work instead of a workaround.

So, as an update  - I have tried with more recent versions and I don't think any updates have been done on the yt-dlp, but using `--cookies-from-browser` works for me now out of the box.

I think `--cookies` doesn't work (at least for me) because I'm using the EditThisCookie extension to export it to a file, but there are certain cookie values that is does not grab if you look at your cookies in dev tools. This is my best theory based on observations while troubleshooting.

Regardless, I will close this issue since it's working now without the additional workarounds I mentioned above.

**Comment by gianpaj** [comment]
doesn't work at the moment

```
yt-dlp https://go.tlc.com/video/2204994 --no-geo-bypass --verbose
[debug] Command-line config: ['https://go.tlc.com/video/2204994', '--no-geo-bypass', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.05.22 from yt-dlp/yt-dlp [7977b329e] (pip)
[debug] Python 3.13.3 (CPython arm64 64bit) - macOS-14.7.6-arm64-arm-64bit-Mach-O (OpenSSL 3.5.0 8 Apr 2025)
[debug] exe versions: ffmpeg 7.1.1 (setts), ffprobe 7.1.1
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.1.0, certifi-2025.04.26, mutagen-1.47.0, requests-2.32.3, sqlite3-3.49.2, urllib3-2.4.0, websockets-15.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: none
[debug] Loaded 1859 extractors
[generic] Extracting URL: https://go.tlc.com/video/2204994
[generic] 2204994: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 2204994: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://go.tlc.com/video/2204994
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2025.5.22/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1662, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2025.5.22/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1797, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2025.5.22/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 748, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2025.5.22/libexec/lib/python3.13/site-packages/yt_dlp/extractor/generic.py", line 2579, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://go.tlc.com/video/2204994
```

But this URL works `https://go.tlc.com/video/skin-tight-tlc/lauana-and-tim`

By logging in to the website with an iOS user agent, it redirected me to that URL

**Comment by bashonly** [comment]
@gianpaj could you open a new issue about this, please?
