### ISSUE TITLE
--live-from-start seems not supported ("No video formats found") for Vimeo live streams

### ISSUE THREAD

**Issue by ohhai** [yt-dlp/yt-dlp#2771]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ukraine

### Description

I can't download Vimeo live stream with --live-from-start
Without this option everything works fine, but not downloading from start of course:

```
$ yt-dlp -U
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)

$ yt-dlp -F --referer https://app.sli.do/event/7qR9QcdpiAwsLyRqSLjhMt 'https://player.vimeo.com/video/677150458?h=204bbd5d75' 
[vimeo] 677150458: Downloading webpage
[vimeo] 677150458: Downloading akamai_live m3u8 information
[vimeo] 677150458: Downloading fastly_live m3u8 information
[info] Available formats for 677150458:
ID                                   EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC     ABR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akamai_live-audio_128000-English mp4 audio only     │       m3u8  │ audio only        unknown        [en] English
hls-akamai_live-audio_256000-English mp4 audio only     │       m3u8  │ audio only        unknown        [en] English
hls-akamai_live-audio_56000-English  mp4 audio only     │       m3u8  │ audio only        unknown        [en] English
hls-akamai_live-327                  mp4 426x240     30 │  327k m3u8  │ avc1.640015  327k video only
hls-fastly_live-378                  mp4 426x240     30 │  378k m3u8  │ avc1.640015  378k mp4a.40.5   0k
hls-akamai_live-545                  mp4 640x360     30 │  545k m3u8  │ avc1.64001e  545k video only
hls-fastly_live-661                  mp4 640x360     30 │  661k m3u8  │ avc1.64001e  661k mp4a.40.2   0k
hls-akamai_live-1636                 mp4 960x540     30 │ 1636k m3u8  │ avc1.64001f 1636k video only
hls-fastly_live-1869                 mp4 960x540     30 │ 1869k m3u8  │ avc1.64001f 1869k mp4a.40.2   0k
hls-akamai_live-2727                 mp4 1280x720    30 │ 2727k m3u8  │ avc1.640020 2727k video only
hls-fastly_live-2959                 mp4 1280x720    30 │ 2959k m3u8  │ avc1.640020 2959k mp4a.40.2   0k
hls-akamai_live-5454                 mp4 1920x1080   30 │ 5454k m3u8  │ avc1.64002a 5454k video only
hls-fastly_live-5687                 mp4 1920x1080   30 │ 5687k m3u8  │ avc1.64002a 5687k mp4a.40.2   0k

$ yt-dlp -f worstaudio --referer https://app.sli.do/event/7qR9QcdpiAwsLyRqSLjhMt 'https://player.vimeo.com/video/677150458?h=204bbd5d75'
[vimeo] 677150458: Downloading webpage
[vimeo] 677150458: Downloading akamai_live m3u8 information
[vimeo] 677150458: Downloading fastly_live m3u8 information
[info] 677150458: Downloading 1 format(s): hls-akamai_live-audio_128000-English
[download] Destination: Резистентні депресії 2022-02-14 17_07 [677150458].mp4
[https @ 0x5654bbd55940] Stream ends prematurely at 449, should be 18446744073709551615
[hls @ 0x5654bbd54900] Skip ('#EXT-X-VERSION:6')
<... actual download goes next>
```

### Verbose log

```shell
$ yt-dlp -Uv --live-from-start --referer https://app.sli.do/event/7qR9QcdpiAwsLyRqSLjhMt 'https://player.vimeo.com/video/677150458?h=204bbd5d75'
[debug] Command-line config: ['-Uv', '--live-from-start', '--referer', 'https://app.sli.do/event/7qR9QcdpiAwsLyRqSLjhMt', 'https://player.vimeo.com/video/677150458?h=204bbd5d75']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.7-200.fc35.x86_64+debug-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/677150458?h=204bbd5d75
[vimeo] 677150458: Downloading webpage
[vimeo] 677150458: Downloading akamai_live m3u8 information
[vimeo] 677150458: Downloading fastly_live m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
ERROR: [vimeo] 677150458: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1517, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2431, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 961, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [vimeo] 677150458: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
```

**Comment by pukkandan** [comment]
```
--live-from-start                Download livestreams from the start.
                                 Currently only supported for YouTube
                                 (Experimental)
```

**Comment by robd003** [comment]
It'd be great to support other platforms than just YouTube
