### ISSUE TITLE
Loco.gg Downloader

### ISSUE THREAD

**Issue by transferlucif3rhun1** [yt-dlp/yt-dlp#2797]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Example URLs

https://loco.gg/stream/e2d319b4-f2f9-430f-a830-4ef76cf6c161

### Description

I confirm that i am on latest yt-dlp and this url is not supported!

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://loco.gg/stream/e2d319b4-f2f9-430f-a830-4ef76cf6c161']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.1 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2022-02-03-git-e1a14479a8-full_build-www.gyan.dev (setts), ffprobe 2022-02-03-git-e1a14479a8-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://loco.gg/stream/e2d319b4-f2f9-430f-a830-4ef76cf6c161
[generic] e2d319b4-f2f9-430f-a830-4ef76cf6c161: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] e2d319b4-f2f9-430f-a830-4ef76cf6c161: Downloading webpage
[generic] e2d319b4-f2f9-430f-a830-4ef76cf6c161: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://loco.gg/stream/e2d319b4-f2f9-430f-a830-4ef76cf6c161
Traceback (most recent call last):
  File "C:\Users\lucigendu\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\lucigendu\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\lucigendu\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\lucigendu\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://loco.gg/stream/e2d319b4-f2f9-430f-a830-4ef76cf6c161
```

**Comment by AG4lyf** [comment]
Any updates on this ?

**Comment by doe1080** [comment]
currently supported at its redirect endpoint, [loco.com](https://loco.com/)
Related https://github.com/yt-dlp/yt-dlp/pull/12667
