### ISSUE TITLE
[Question] How can I build a exe file from yt-dlp source.....?

### ISSUE THREAD

**Issue by had0103** [yt-dlp/yt-dlp#281]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

How can I build a exe executable file from yt-dlp source... I have tried this command `python3 setup.py py2exe` but i am getting the bellow error:

python3 setup.py py2exe
inv
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    **params
NameError: name 'params' is not defined

I have tried the same command with youtube-dl and it works fine but not working with yt-dlp....? 

Can anyone give me a solution....??

**Comment by pukkandan** [comment]
Compiling with `py2exe` is not officially supported. You must use `pyinstaller`

See https://github.com/yt-dlp/yt-dlp#compile

**Comment by pukkandan** [comment]
Looking at youtube-dl's setup.py, it seems easy enough to add py2exe support. But I'd still recommend pyinstaller

**Comment by had0103** [comment]
pyinstaller yt_dlp\__main__.py --onefile --name yt-dlp
95 INFO: PyInstaller: 4.3
95 INFO: Python: 3.8.9
96 INFO: Platform: Windows-10-10.0.19041-SP0
97 INFO: wrote C:\Users\ACT\OneDrive\Desktop\yt-dlp-master\yt-dlp.spec
103 INFO: UPX is not available.
112 INFO: Extending PYTHONPATH with paths
['C:\\Users\\ACT\\OneDrive\\Desktop\\yt-dlp-master',
 'C:\\Users\\ACT\\OneDrive\\Desktop\\yt-dlp-master']
134 INFO: checking Analysis
134 INFO: Building Analysis because Analysis-00.toc is non existent
134 INFO: Initializing module dependency graph...
139 INFO: Caching module graph hooks...
152 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
160 INFO: Analyzing base_library.zip ...
4068 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\ACT\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
4069 INFO: distutils: retargeting to non-venv dir 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\\lib'
5992 INFO: Caching module dependency graph...
6214 INFO: running Analysis Analysis-00.toc
Traceback (most recent call last):
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\win32ctypes\core\cffi\_dll.py", line 23, in _LoadLibraryEx
    result = check_null(
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\win32ctypes\core\cffi\_util.py", line 81, in __call__
    self._raise_error(function_name)
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\win32ctypes\core\cffi\_util.py", line 92, in _raise_error
    raise exception
OSError: [WinError 1920] The file cannot be accessed by the system

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ACT\OneDrive\Desktop\yt-dlp-master\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\building\build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\building\build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "C:\Users\ACT\OneDrive\Desktop\yt-dlp-master\yt-dlp.spec", line 7, in <module>
    a = Analysis(['yt_dlp\\__main__.py'],
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\building\build_main.py", line 391, in assemble
    self.binaries.extend(bindepend.Dependencies([('', python, '')],
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\depend\bindepend.py", line 224, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\depend\bindepend.py", line 403, in getAssemblyFiles
    for assembly in getAssemblies(pth):
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\depend\bindepend.py", line 354, in getAssemblies
    res = GetManifestResources(pth)
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1016, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PyInstaller\utils\win32\winresource.py", line 170, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\ACT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1920, 'LoadLibraryEx', 'The file cannot be accessed by the system')


i have tried but i am getting this error can you please help me to solve this

**Comment by pukkandan** [comment]
https://stackoverflow.com/a/63310595

**Comment by Jules-A** [comment]
> https://stackoverflow.com/a/63310595

Needs to be added to documentation.

**Comment by pukkandan** [comment]
> > https://stackoverflow.com/a/63310595
> 
> Needs to be added to documentation.

It is `Pyinstaller` that does not run on windows Store version of python without venv. This is documented in the pyinstaller's documentation.I don't see any reason to document it here. Instead,it is probably better to create a wiki to answer these kind of issues.

---

Closing this since OP has not responded

**Comment by Jules-A** [comment]
Well, since most people will probably install pyinstaller by the given command line, they most likely won't see any warnings about pyinstaller requiring non-Windows store version. 
```For Windows: To build the Windows executable, you must have pyinstaller (and optionally mutagen and pycryptodome)```

Could just be changed to something like: ```For Windows: To build the Windows executable, you must have pyinstaller (and optionally mutagen and pycryptodome). You will need a non-Windows Store version of Python as it is incompatible with pyinstaller.```
