### ISSUE TITLE
[iq.com - VIP Video]rtmofhja3o: No video formats found!

### ISSUE THREAD

**Issue by cx410** [yt-dlp/yt-dlp#2813]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Unable to download VIP videos. I've used cookies and it's still the same.

But for non VIP videos, no problem.

> [iq.com] rtmofhja3o: Downloading webpage
[iq.com] rtmofhja3o: Downloading VIP data
[iq.com] rtmofhja3o: Executing signature code
[iq.com] rtmofhja3o: Downloading initial video format info
ERROR: [iq.com] rtmofhja3o: No video formats found!; please report this issue on https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-f', 'bestvideo+bestaudio/best', '-P', '\\
Downloads', '--external-downloader', 'aria2c', '--cookies', 'iq.com_cookies.txt'
, '--sub-langs', 'all', '--write-subs', '--embed-subs', '--compat-options', 'no-
keep-subs', '--no-keep-video', '--embed-thumbnail', '--embed-chapters', '--remux
-video', 'mkv', 'https://www.iq.com/play/nothing-but-you-episode-3-25fvnqzcq8o?l
ang=en_us', '-o', 'example - %(episode_number)02d (%(height)sp)']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Compatibility options: no-keep-subs
[debug] Python version 3.8.10 (CPython 64bit) - Windows-2012ServerR2-6.3.9600-SP
0
[debug] exe versions: ffmpeg 2021-04-18-git-d43b26b30d-essentials_build-www.gyan
.dev (setts), ffprobe 2021-04-18-git-d43b26b30d-essentials_build-www.gyan.dev, p
hantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [iq.com] Extracting URL: https://www.iq.com/play/nothing-but-you-episode
-3-25fvnqzcq8o?lang=en_us
[iq.com] 25fvnqzcq8o: Downloading webpage
[debug] Loading iq.player_js from cache
[iq.com] 25fvnqzcq8o: Downloading VIP data
[debug] Loading iq.player_js from cache
[iq.com] 25fvnqzcq8o: Executing signature code
[iq.com] 25fvnqzcq8o: Downloading initial video format info
ERROR: [iq.com] 25fvnqzcq8o: No video formats found!; please report this issue o
n  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue templa
te properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2431, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
yt_dlp.utils.ExtractorError: [iq.com] 25fvnqzcq8o: No video formats found!; plea
se report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Bro
ken site" issue template properly. Confirm you are on the latest version using -
U

ECHO is off.
Press any key to continue . . .
```

**Comment by bashonly** [comment]
Currently this issue seems to manifest itself intermittently with VIP content. See also: https://github.com/yt-dlp/yt-dlp/issues/5702#issuecomment-1357398442

**Comment by bashonly** [comment]
From https://github.com/yt-dlp/yt-dlp/issues/5702#issuecomment-1384245060 :

>>> Iqiyi appears to check if the simultaneous stream limit is hit periodically. If it senses it's been hit, it will block the entire account from streaming until a stream has been closed + 10 minute penalty. Users can see the 10 minute message if they try to stream something on a browser. Downloading full videos minutes within each other apparently counts as a simultaneous stream.

>>> The standard account allows 2 simultaneous streams, and the premium one allows for 4. ... I hit [this] problem after 4 downloads, and I have the premium one.

>>> I set my script to put a 15 minute interval between every 4 downloads(so the penalty time expires before it tries to download new episodes), but it's not a great solution. Would probably be better if yt-dlp could detect the error message and set the timeout internally.

I think the extractor could at least output a more descriptive/accurate error message

**Comment by whitedragon92** [comment]
Any update on this issue?

**Comment by whitedragon92** [comment]
any update on this issue?
