### ISSUE TITLE
ZEE5 Broken site for few videos [No video formats found!]

### ISSUE THREAD

**Issue by kr-v** [yt-dlp/yt-dlp#2821]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Video URL : https://www.zee5.com/tv-shows/details/sa-re-ga-ma-pa-2021/0-6-3497/sa-re-ga-ma-pa-2021-auditions-round-1/0-1-6z526594

Few videos are giving broken site issue.

### Verbose log

```shell
[debug] Command-line config: ['https://www.zee5.com/tv-shows/details/sa-re-ga-ma-pa-2021/0-6-3497/sa-re-ga-ma-pa-2021-auditions-round-1/0-1-6z526594', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.10 (CPython 64bit) - macOS-12.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe N-105035-g617452ce2c-tessus
[debug] Optional libraries: Cryptodome, sqlite
[debug] Proxy map: {}
[debug] Using fake IP 117.246.132.25 (IN) as X-Forwarded-For
[debug] [Zee5] Extracting URL: https://www.zee5.com/tv-shows/details/sa-re-ga-ma-pa-2021/0-6-3497/sa-re-ga-ma-pa-2021-auditions-round-1/0-1-6z526594
[Zee5] 0-1-6z526594: Downloading access token
[Zee5] 0-1-6z526594: Downloading JSON metadata
[Zee5] 0-1-6z526594: Downloading m3u8 information
WARNING: [Zee5] Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: [Zee5] 0-1-6z526594: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1521, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2441, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 961, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Zee5] 0-1-6z526594: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
```

**Comment by Ashish0804** [comment]
Umm technically DRM is not the issue here @pukkandan 
The issue is non-DRM url not working for unknown reasons.

**Comment by freezboltz** [comment]
```sh
yt-dlp --concurrent-fragments 10 "https://www.zee5.com/news/details/russia-ukraine-war-russia-bombs-drama-theater-in-mariupol-over-1000-feared-trapped/0-0-newsauto_3o2svtunol20"
[generic] 0-0-newsauto_3o2svtunol20: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 0-0-newsauto_3o2svtunol20: Downloading webpage
[generic] 0-0-newsauto_3o2svtunol20: Extracting information
ERROR:
```

**Comment by m4tu4g** [comment]
> Umm technically DRM is not the issue here @pukkandan The issue is non-DRM url not working for unknown reasons.

There are no non-DRM urls in zee5
which url are you referring about "non-DRM url not working for unknown reasons"

**Comment by devenu85** [comment]
> > Umm technically DRM is not the issue here @pukkandan The issue is non-DRM url not working for unknown reasons.
> 
> There are no non-DRM urls in zee5 which url are you referring about "non-DRM url not working for unknown reasons"

Every free content video in zee5 has a non-drm hls url, and we take advantage of it.

**Comment by JunkFood02** [comment]
Any update on this issue? [This link](https://www.zee5.com/global/tv-shows/details/sa-re-ga-ma-pa-2021/0-6-3497/sa-re-ga-ma-pa-2021-auditions-round-1/0-1-6z526594) is playable in a browser but shows the same error

**Comment by pukkandan** [comment]
> Any update on this issue? [This link](https://www.zee5.com/global/tv-shows/details/sa-re-ga-ma-pa-2021/0-6-3497/sa-re-ga-ma-pa-2021-auditions-round-1/0-1-6z526594) is playable in a browser but shows the same error

But it is not playable for me **without DRM**. See https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056 for how to check
