### ISSUE TITLE
[Spiegel] Unsupported URL

### ISSUE THREAD

**Issue by spookyahell** [yt-dlp/yt-dlp#2842]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
~~I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required~~ (not required, video is available free of charge, without login)
### Region

Germany (possibly worldwide)

### Description

The link I tried is

https://www.spiegel.de/panorama/sturm-ylenia-in-hamburg-welle-trifft-elb-faehre-und-kracht-durchs-fenster-video-a-e3febb1c-6b95-4b51-9823-b6c99ed10fa0?jwsource=cl

And the produced error is this: ERROR: Unsupported URL

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.spiegel.de/panorama/sturm-ylenia-in-hamburg-welle-trifft-elb-faehre-und-kracht-durchs-fenster-video-a-e3febb1c-6b95-4b51-9823-b6c99ed10fa0?jwsource=cl']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-4.19.113-22501868-aarch64-with-libc
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://www.spiegel.de/panorama/sturm-ylenia-in-hamburg-welle-trifft-elb-faehre-und-kracht-durchs-fenster-video-a-e3febb1c-6b95-4b51-9823-b6c99ed10fa0?jwsource=cl
[generic] sturm-ylenia-in-hamburg-welle-trifft-elb-faehre-und-kracht-durchs-fenster-video-a-e3febb1c-6b95-4b51-9823-b6c99ed10fa0?jwsource=cl: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] sturm-ylenia-in-hamburg-welle-trifft-elb-faehre-und-kracht-durchs-fenster-video-a-e3febb1c-6b95-4b51-9823-b6c99ed10fa0?jwsource=cl: Downloading webpage
[generic] sturm-ylenia-in-hamburg-welle-trifft-elb-faehre-und-kracht-durchs-fenster-video-a-e3febb1c-6b95-4b51-9823-b6c99ed10fa0?jwsource=cl: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.spiegel.de/panorama/sturm-ylenia-in-hamburg-welle-trifft-elb-faehre-und-kracht-durchs-fenster-video-a-e3febb1c-6b95-4b51-9823-b6c99ed10fa0?jwsource=cl
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.spiegel.de/panorama/sturm-ylenia-in-hamburg-welle-trifft-elb-faehre-und-kracht-durchs-fenster-video-a-e3febb1c-6b95-4b51-9823-b6c99ed10fa0?jwsource=cl
```

**Comment by nicolaasjan** [comment]
Until this can be supported, try this:
`yt-dlp https://vcdn01.spiegel.de/manifests/GtWVAsBS.m3u8`

```bash
dlp -v https://vcdn01.spiegel.de/manifests/GtWVAsBS.m3u8
[debug] Command-line config: ['-v', '--ignore-config', 'https://vcdn01.spiegel.de/manifests/GtWVAsBS.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.18 [c1653e9ef] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-100-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg N-105256-g6c4074e423-Nico-20220110-with-non-monotonous-DTS-Fix (fdk,setts), ffprobe N-105256-g6c4074e423-Nico-20220110-with-non-monotonous-DTS-Fix, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://vcdn01.spiegel.de/manifests/GtWVAsBS.m3u8
[generic] GtWVAsBS: Requesting header
[debug] Identified a direct video link
[generic] GtWVAsBS: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] GtWVAsBS: Downloading 1 format(s): 4650
[debug] Invoking downloader on "https://videos-fms.jwpsrv.com/0_62130a10_0xca31361cc11efb81f087832d1b5142b6f5823ce1/content/conversions/TU3g8fgU/videos/OHQcrDpB-32438811.mp4.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 27
[download] Destination: GtWVAsBS [GtWVAsBS].mp4
[download] 100% of 59.78MiB in 00:08
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:GtWVAsBS [GtWVAsBS].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "GtWVAsBS [GtWVAsBS].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:GtWVAsBS [GtWVAsBS].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:GtWVAsBS [GtWVAsBS].temp.mp4'

```
