### ISSUE TITLE
United Nations (UN) Web TV site request

### ISSUE THREAD

**Issue by choc96208** [yt-dlp/yt-dlp#2855]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

https://media.un.org/en/webtv
https://klive.kaltura.com/s/env/cluster-1-a.live.nvp1/live/hls/p/2503451/e/1_epflppn0/tl/main/st/0/t/9gDv12C6Tbr_lEkRHJEqrA/index-s100.m3u8?__hdnea__=st=1645497690~exp=1645584090~acl=/s/env/cluster-1-a.live.nvp1/live/hls/p/2503451/e/1_epflppn0/tl/main/st/0/t/9gDv12C6Tbr_lEkRHJEqrA/index-s*~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5

### Description

I'd like to request the United Nations Web TV support be added to yt-dlp. The streaming site streams the live proceedings of the intergovernmental organisation in the languages of English, Spanish, French, Chinese, Arabic, Russian and Interlingua (without live translation). 

### Verbose log

```shell
yt-dlp -vU https://media.un.org/en/webtv
[debug] Command-line config: ['-vU', 'https://media.un.org/en/webtv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.2 (CPython 64bit) - macOS-12.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://media.un.org/en/webtv
[generic] webtv: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] webtv: Downloading webpage
[generic] webtv: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://media.un.org/en/webtv
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://media.un.org/en/webtv

yt-dlp -vU "https://klive.kaltura.com/s/env/cluster-1-a.live.nvp1/live/hls/p/2503451/e/1_epflppn0/tl/main/st/0/t/9gDv12C6Tbr_lEkRHJEqrA/index-s100.m3u8?__hdnea__=st=1645497690~exp=1645584090~acl=/s/env/cluster-1-a.live.nvp1/live/hls/p/2503451/e/1_epflppn0/tl/main/st/0/t/9gDv12C6Tbr_lEkRHJEqrA/index-s*~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5"
[debug] Command-line config: ['-vU', 'https://klive.kaltura.com/s/env/cluster-1-a.live.nvp1/live/hls/p/2503451/e/1_epflppn0/tl/main/st/0/t/9gDv12C6Tbr_lEkRHJEqrA/index-s100.m3u8?__hdnea__=st=1645497690~exp=1645584090~acl=/s/env/cluster-1-a.live.nvp1/live/hls/p/2503451/e/1_epflppn0/tl/main/st/0/t/9gDv12C6Tbr_lEkRHJEqrA/index-s*~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.2 (CPython 64bit) - macOS-12.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://klive.kaltura.com/s/env/cluster-1-a.live.nvp1/live/hls/p/2503451/e/1_epflppn0/tl/main/st/0/t/9gDv12C6Tbr_lEkRHJEqrA/index-s100.m3u8?__hdnea__=st=1645497690~exp=1645584090~acl=/s/env/cluster-1-a.live.nvp1/live/hls/p/2503451/e/1_epflppn0/tl/main/st/0/t/9gDv12C6Tbr_lEkRHJEqrA/index-s*~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5
[generic] index-s*~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5: Requesting header
[debug] Identified a direct video link
[generic] index-s*~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] index-s*~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://klive.kaltura.com/s/env/cluster-1-a.live.nvp1/live/hls/p/2503451/e/1_epflppn0/tl/main/st/0/t/9gDv12C6Tbr_lEkRHJEqrA/index-s100.m3u8?__hdnea__=st=1645497690~exp=1645584090~acl=/s/env/cluster-1-a.live.nvp1/live/hls/p/2503451/e/1_epflppn0/tl/main/st/0/t/9gDv12C6Tbr_lEkRHJEqrA/index-s*~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 5
[download] Destination: index-s100 [index-s_~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5].mp4
[download] 100% of 267.13KiB in 00:01
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:index-s100 [index-s_~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "index-s100 [index-s_~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:index-s100 [index-s_~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:index-s100 [index-s_~hmac=14601f99913787bfb6c5360483937bccfd2e5a9962018675165132c2ac655df5].temp.mp4'
```

**Comment by coletdjnz** [comment]
Upstream PR: https://github.com/ytdl-org/youtube-dl/pull/30615

**Comment by coletdjnz** [comment]
Reopening as the other request was for the recordings, whereas this is for the live streams

**Comment by choc96208** [comment]
Thanks the updates coletdjnz. I found today that the UN also broadcasts live on YouTube but only in native and dubbed English. The live is here: https://www.youtube.com/watch?v=9CdY7t5VKIY. To watch it live in Arabic, Chinese, French, Russian, Spanish and the original undubbed language it is only available at https://media.un.org/en/webtv as far as I know. Adding this comment in case anyone else is looking to stream the proceedings live.
