### ISSUE TITLE
[discoveryplus] Subtitle parsing broken: Parse error at position 56 (near '')

### ISSUE THREAD

**Issue by Bricio** [yt-dlp/yt-dlp#2867]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When downloading a video and yt-dlt got a parse error downloading subtitle all video/audio is not downloaded. 
It should skip only this sub title error.

```
D:\ytdlp>yt-dlp -vU --cookies-from-browser firefox --no-geo-bypass "https://www.discoveryplus.com/br/video/absurdos-da-engenharia-discovery-br/arranha-ceu-e-o-raio-da-morte" -f hls-3105 -o video.mp4 --write-subs --sub-langs all
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', '--no-geo-bypass', 'https://www.discoveryplus.com/br/video/absurdos-da-engenharia-discovery-br/arranha-ceu-e-o-raio-da-morte', '-f', 'hls-3105', '-o', 'video.mp4', '--write-subs', '--sub-langs', 'all']
[debug] Portable config "D:\ytdlp\yt-dlp.conf": ['--ffmpeg-location', '.\\ffmpeg\\bin', '--ignore-config']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\User\AppData\Roaming\Mozilla\Firefox\Profiles\qd7vi5fr.default\cookies.sqlite"
[Cookies] Extracted 2115 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-105453-gcc5eb2e662-20220204 (setts), ffprobe N-105453-gcc5eb2e662-20220204
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/br/video/absurdos-da-engenharia-discovery-br/arranha-ceu-e-o-raio-da-morte
[DiscoveryPlus] absurdos-da-engenharia-discovery-br/arranha-ceu-e-o-raio-da-morte: Downloading JSON metadata
[DiscoveryPlus] 2290980: Downloading JSON metadata
[DiscoveryPlus] absurdos-da-engenharia-discovery-br/arranha-ceu-e-o-raio-da-morte: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: pt
[info] 2290980: Downloading 1 format(s): hls-3105
[info] Writing video subtitles to: video.pt.vtt
[debug] Invoking downloader on "https://dplus-br-prod-vod.akamaized.net/b797/e1ea/1329/03698b40-aca3-413d-88d7-319b4a5642ae/ts-raw/hdntl=exp=1645662057~acl=/b797/e1ea/1329/03698b40-aca3-413d-88d7-319b4a5642ae/ts-raw/*~data=hdntl~hmac=f2a7b443dd081a3d1aa9b57451101afd7b5f5cd0be24cc706cc7d1040a967133/caption-pt/subs.m3u8?hdntl=exp=1645662057~acl=/b797/e1ea/1329/03698b40-aca3-413d-88d7-319b4a5642ae/ts-raw/*~data=hdntl~hmac=f2a7b443dd081a3d1aa9b57451101afd7b5f5cd0be24cc706cc7d1040a967133&hdntl=exp=1645662057~acl=/b797/e1ea/1329/03698b40-aca3-413d-88d7-319b4a5642ae/ts-raw/*~data=hdntl~hmac=f2a7b443dd081a3d1aa9b57451101afd7b5f5cd0be24cc706cc7d1040a967133"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 6
[download] Destination: video.pt.vtt
[download] video.pt.vtt.part-Frag1 has already been downloaded
[download]  16.7% of ~336.00B at Unknown speed ETA Unknown (frag 1/6)ERROR: Parse error at position 56 (near '')
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2607, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2852, in process_info
  File "yt_dlp\YoutubeDL.py", line 3825, in _write_subtitles
  File "yt_dlp\YoutubeDL.py", line 2801, in dl
  File "yt_dlp\downloader\common.py", line 440, in download
  File "yt_dlp\downloader\hls.py", line 355, in real_download
  File "yt_dlp\downloader\fragment.py", line 515, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 486, in append_fragment
  File "yt_dlp\downloader\hls.py", line 270, in pack_fragment
  File "yt_dlp\webvtt.py", line 364, in parse_fragment
  File "yt_dlp\webvtt.py", line 220, in parse
yt_dlp.webvtt.ParseError: Parse error at position 56 (near '')
```

This specific site is geo-blocked and account is needed.

If someone help me I can try to fix it.

**Comment by pukkandan** [comment]
There are 2 issues here.
1. There is something wrong with the subtitle parsing. @fstirlitz Any ideas?
1. Failure to parse subs should not block the video download. (Related: #2875). I'll deal with this

**Comment by fstirlitz** [comment]
‘near ''’ suggests a premature EOF. Without seeing the fragment file contents, I can't say much more. @Bricio, can you retry with `--keep-fragments` and post them here?

**Comment by fstirlitz** [comment]
Yup, missing newline. Exactly as I thought.

**Comment by pukkandan** [comment]
Can you add a patch for it to #2175? Or do you think this should be patched even in strict mode?

**Comment by fstirlitz** [comment]
I think it’s harmless to enable unconditionally. If it’s empty, it’s empty.

**Comment by Extarys** [comment]
I think I'm having the same issue and want to make sure, instead of directly opening a duplicate.

I tried downloading a subtitle (vtt) file from Nebula and got the following:
```
[download]   0.5% of ~2.91KiB at  2.91KiB/s ETA Unknown (frag 1/186)ERROR: Parse error at position 11 (near '1\r\n')
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1394, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1582, in process_ie_result
    return self.process_ie_result(
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1534, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2639, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2891, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3861, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2837, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 445, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/hls.py", line 345, in real_download
    self.download_and_append_fragments(
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 521, in download_and_append_fragments
    result = append_fragment(
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 488, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/hls.py", line 260, in pack_fragment
    for block in webvtt.parse_fragment(frag_content):
  File "/usr/lib/python3.10/site-packages/yt_dlp/webvtt.py", line 385, in parse_fragment
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 11 (near '1\r\n')
```

Content of video.vtt.part-Frag1:
```
WEBVTT

1

```

I'm guessing it's similar, but if not I can open a new issue with more details. If it is, I'll just wait patiently for the parser to be fixed :smile:

**Comment by fstirlitz** [comment]
A duplicate is better than off-topic comments under an unrelated issue.

No, that looks like an *actual* corrupt download. When you file this separately, can you use `--print-traffic` and attach at least the final 100 lines or so?

**Comment by Extarys** [comment]
@fstirlitz Well, each repo have different preferences.

> No, that looks like an actual corrupt download. When you file this separately, can you use --print-traffic and attach at least the final 100 lines or so?

Duly noted, thanks for the tip. I'll create a new issue.

**Comment by DHandspikerWade** [comment]
Newer Nebula videos seem to be displaying a similar corrupt webvtt issue as Discovery. Patching the current master branch with https://github.com/yt-dlp/yt-dlp/pull/2175 does not seem to help. 

URL: https://nebula.app/videos/jetlag-ep-2-we-played-tag-across-europe

```
[debug] Command-line config: ['--cookies', '/cookies.txt', '--all-subs', '--username', 'PRIVATE', '-v', '--password', 'PRIVATE', 'https://nebula.app/videos/jetlag-ep-2-we-played-tag-across-europe']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.09.01 [5d7c7d656]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.10.0-16-amd64-x86_64-with
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[Nebula] Authenticating to Nebula with token from cookie jar
[Nebula] Authorizing to Nebula
[Nebula] Retrieving Zype access token
[debug] [Nebula] Extracting URL: https://nebula.app/videos/jetlag-ep-2-we-played-tag-across-europe
[Nebula] jetlag-ep-2-we-played-tag-across-europe: Fetching video meta data
WARNING: [Zype] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [Zype] Extracting URL: https://player.zype.com/embed/6321d931e87181000147666e.html?access_token=SG3PxdiETwn42EVqc_wW04uNhVOXWgeMUmyklYDjFKk
[Zype] 6321d931e87181000147666e: Downloading JSON metadata
[Zype] 6321d931e87181000147666e: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 6321d931e87181000147666e: Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 6321d931e87181000147666e: Downloading 1 format(s): hls-25006
[debug] Invoking hlsnative downloader on "https://storage.googleapis.com/zype-subtitles-prod/5c182d06649f0f134a001703/6321d931e87181000147666e/subtitles/en.m3u8"
[info] Writing video subtitles to: Ep 2 — We Played Tag Across Europe [6321d931e87181000147666e].en.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 172
[download] Destination: Ep 2 — We Played Tag Across Europe [6321d931e87181000147666e].en.vtt
[download]   0.6% of ~164.44KiB at    7.43KiB/s ETA    00:20 (frag 1/172)ERROR: Parse error at position 135 (near 'Style:\r\n::cue(v[voic')
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1574, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1685, in process_ie_result
    return self.process_ie_result(
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1632, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2730, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2976, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3930, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2917, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 443, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/hls.py", line 360, in real_download
    self.download_and_append_fragments(
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 518, in download_and_append_fragments
    result = append_fragment(
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 477, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/hls.py", line 275, in pack_fragment
    for block in webvtt.parse_fragment(frag_content, lenient=lenient):
  File "/usr/lib/python3.10/site-packages/yt_dlp/webvtt.py", line 373, in parse_fragment
    yield Magic.parse(parser)
  File "/usr/lib/python3.10/site-packages/yt_dlp/webvtt.py", line 218, in parse
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 135 (near 'Style:\r\n::cue(v[voic')

```

**Comment by fstirlitz** [comment]
To quote a certain handsome genius:

> A duplicate is better than off-topic comments under an unrelated issue.

This is actually <https://github.com/yt-dlp/yt-dlp/issues/4130#issuecomment-1162716327>. Except worse, because multi-line metadata is completely nonstandard. YouTube serves merely obsolete syntax; this, however, seems to have never been standardised at all. No standard draft includes this syntax.

**Comment by jzysl423** [comment]
a similar corrupt webvtt issue   
https://pluto.tv/en/on-demand/movies/horrorvision-2001-1-1

`C:\Users\Administrator\Desktop>yt-dlp -vU --proxy 127.0.0.1:7890 --write-subs --skip-download https://pluto.tv/en/on-dem
and/movies/horrorvision-2001-1-1
[debug] Command-line config: ['-vU', '--proxy', '127.0.0.1:7890', '--write-subs', '--skip-download', 'https://pluto.tv/e
n/on-demand/movies/horrorvision-2001-1-1']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2022.09.01 [5d7c7d656]
[debug] Lazy loading extractors is disabled
[debug] Python 3.8.10 (CPython 32bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-100466-g29cef1bcd6, ffprobe N-100466-g29cef1bcd6
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websocke
ts-10.3
[debug] Proxy map: {'http': '127.0.0.1:7890', 'https': '127.0.0.1:7890'}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [PlutoTV] Extracting URL: https://pluto.tv/en/on-demand/movies/horrorvision-2001-1-1
[PlutoTV] horrorvision-2001-1-1: Downloading JSON metadata
[PlutoTV] 630fffdbd1f9a40013b7afba: Downloading m3u8 information
[PlutoTV] 630fffdbd1f9a40013b7afba: Downloading m3u8 playlist
[PlutoTV] 630fffdbd1f9a40013b7afba: Downloading m3u8 playlist
[PlutoTV] 630fffdbd1f9a40013b7afba: Downloading m3u8 playlist
[PlutoTV] 630fffdbd1f9a40013b7afba: Downloading m3u8 playlist
[PlutoTV] 630fffdbd1f9a40013b7afba: Downloading m3u8 playlist
[PlutoTV] 630fffdbd1f9a40013b7afba: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, file
size, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 630fffdbd1f9a40013b7afba: Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 630fffdbd1f9a40013b7afba: Downloading 1 format(s): hls-2377
[info] Writing video subtitles to: HorrorVision [630fffdbd1f9a40013b7afba].en.vtt
[debug] Invoking hlsnative downloader on "https://siloh-fs.plutotv.net/587_pluto/clip/630fffd8d1f9a40013b7afb4_HorrorVis
ion/720p/20220831_174200/hls/0-end/en.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1083
[download] Destination: HorrorVision [630fffdbd1f9a40013b7afba].en.vtt
[debug] File locking is not supported. Proceeding without locking
[download]   0.1% of ~109.99KiB at    155.68B/s ETA    11:57 (frag 1/1083)ERROR: Parse error at position 57 (near '00:00
:00.602 --> 00:')
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 1574, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 1632, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 2730, in process_video_result
    self.process_info(new_info)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 2976, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 3930, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 2917, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\downloader\common.py", line 443, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\downloader\hls.py", line 351, in real_download
    self.download_and_append_fragments(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\downloader\fragment.py", line 518, in download_and_a
ppend_fragments
    result = append_fragment(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\downloader\fragment.py", line 477, in append_fragmen
t
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\downloader\hls.py", line 266, in pack_fragment
    for block in webvtt.parse_fragment(frag_content):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\yt_dlp\webvtt.py", line 398, in parse_fragment
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 57 (near '00:00:00.602 --> 00:')
`

**Comment by JustArion** [comment]
I've got a similar issue

```
ERROR: Parse error at position 57 (near '1\n00:00:00.010 --> 0')
```
It's somewhat different from the original issue but still similar enough.

The .vtt file here that causes the error is in `LF` format instead of `CRLF`

**Comment by pukkandan** [comment]
Pls open a new issue with verbose log
