### ISSUE TITLE
[youtube] ERROR: 'generator already executing' with --live-from-start

### ISSUE THREAD

**Issue by krichbanana** [yt-dlp/yt-dlp#2881]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

The command used was:
`./yt-dlp.sh -v --write-thumbnail --write-description --write-info-json  --live-from-start --wait-for-video=2-3 -N4 B-zkB2i-qeg`

The program was running the HEAD git commit, trialing the changes introduced with the merge of https://github.com/yt-dlp/yt-dlp/pull/2870 .

The program no longer hangs for hours while eating memory as was the old behavior, but now quickly ends with an error. A ValueError is raised with the message "generator already executing".

Output files of the command:
```
$ ls -l
'【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].description'
'【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].f140.mp4.part'
'【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].f140.mp4.ytdl'
'【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].f299.mp4'
'【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].f299.mp4.part-Frag3692.part'
'【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].info.json'
'【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].webp'
```

Apologies if this bug report is premature.

### Verbose log

```shell
$ ./yt-dlp.sh -v --write-thumbnail --write-description --write-info-json  --live-from-start --wait-for-video=2-3 -N4 B-zkB2i-qeg
[debug] Command-line config: ['-v', '--write-thumbnail', '--write-description', '--write-info-json', '--live-from-start', '--wait-for-video=2-3', '-N4', 'B-zkB2i-qeg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: a539f0657
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.24-2-lts-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
WARNING: [youtube] This live event will begin in a few moments.
WARNING: Release time of video is not known
[wait] Waiting for 00:00:02 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[debug] [youtube] Extracting URL: B-zkB2i-qeg
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
[youtube] B-zkB2i-qeg: Downloading MPD manifest
[youtube] B-zkB2i-qeg: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] B-zkB2i-qeg: Downloading 1 format(s): 299+140
[info] Writing video description to: 【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].description
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: 【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].webp
[info] Writing video metadata as JSON to: 【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].info.json
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1645761645/ei/DQAYYv7iIoHlhwaznImwAw/ip/<IP_ADDR>/id/B-zkB2i-qeg.1/source/yt_live_broadcast/requiressl/yes/tx/24177077/txs/24177077%2C24177078/hfr/1/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24001373%2C24007246/itag/0/playlist_type/LIVE/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRgIhALBdv9DVl64WgFL61A5qCOl9nfxLBt1pDKT1iWb2fmTfAiEAvTm1cgqfvS4TSCn-igBFKjGAzHndxd63dnK_-2_Nd-o%3D", "https://manifest.googlevideo.com/api/manifest/dash/expire/1645761645/ei/DQAYYv7iIoHlhwaznImwAw/ip/<IP_ADDR>/id/B-zkB2i-qeg.1/source/yt_live_broadcast/requiressl/yes/tx/24177077/txs/24177077%2C24177078/hfr/1/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24001373%2C24007246/itag/0/playlist_type/LIVE/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRgIhALBdv9DVl64WgFL61A5qCOl9nfxLBt1pDKT1iWb2fmTfAiEAvTm1cgqfvS4TSCn-igBFKjGAzHndxd63dnK_-2_Nd-o%3D"
[dashsegments] Total fragments: unknown (live)
[download] Destination: 【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].f299.mp4
[dashsegments] Total fragments: unknown (live)
[download] Destination: 【朝こよ#25】第一回台詞大賞が決まるよ～！！【博衣こより_ホロライブ】 [B-zkB2i-qeg].f140.mp4
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download] Got server HTTP error: IncompleteRead(39 bytes read). Retrying fragment 3692 (attempt 1 of 10) ...
[youtube] B-zkB2i-qeg: Downloading webpage
[youtube] B-zkB2i-qeg: Downloading android player API JSON
[youtube] B-zkB2i-qeg: Downloading m3u8 information
[youtube] B-zkB2i-qeg: Downloading MPD manifest
[youtube] B-zkB2i-qeg: Downloading m3u8 information
[youtube] B-zkB2i-qeg: Downloading MPD manifest
[download] Got server HTTP error: IncompleteRead(39 bytes read). Retrying fragment 3692 (attempt 2 of 10) ...
[download] Got server HTTP error: The read operation timed out. Retrying (attempt 1 of 10) ...
[download] Got server HTTP error: IncompleteRead(39 bytes read). Retrying fragment 3692 (attempt 3 of 10) ...
[download] Got server HTTP error: IncompleteRead(39 bytes read). Retrying fragment 3692 (attempt 4 of 10) ...
[download] Got server HTTP error: IncompleteRead(39 bytes read). Retrying fragment 3692 (attempt 5 of 10) ...
[download] Got server HTTP error: IncompleteRead(39 bytes read). Retrying fragment 3692 (attempt 6 of 10) ...
[download] Got server HTTP error: IncompleteRead(39 bytes read). Retrying fragment 3692 (attempt 7 of 10) ...
[download] Got server HTTP error: IncompleteRead(39 bytes read). Retrying fragment 3692 (attempt 8 of 10) ...
[download] Got server HTTP error: IncompleteRead(39 bytes read). Retrying fragment 3692 (attempt 9 of 10) ...
[download] Got server HTTP error: IncompleteRead(39 bytes read). Retrying fragment 3692 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 3692 ...
[download] 100% of 148.95MiB in 02:04:23ERROR: generator already executing
Traceback (most recent call last):
  File "$DIR/yt-dlp/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "$DIR/yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "$DIR/yt-dlp/yt_dlp/YoutubeDL.py", line 1521, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "$DIR/yt-dlp/yt_dlp/YoutubeDL.py", line 2626, in process_video_result
    self.process_info(new_info)
  File "$DIR/yt-dlp/yt_dlp/YoutubeDL.py", line 3063, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "$DIR/yt-dlp/yt_dlp/YoutubeDL.py", line 2823, in dl
    return fd.download(name, new_info, subtitle)
  File "$DIR/yt-dlp/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "$DIR/yt-dlp/yt_dlp/downloader/dash.py", line 56, in real_download
    return self.download_and_append_fragments_multiple(*args)
  File "$DIR/yt-dlp/yt_dlp/downloader/fragment.py", line 429, in download_and_append_fragments_multiple
    result = result and bindoj_result(job)
  File "$DIR/yt-dlp/yt_dlp/downloader/fragment.py", line 411, in bindoj_result
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "$DIR/yt-dlp/yt_dlp/downloader/fragment.py", line 391, in thread_func
    return self.download_and_append_fragments(
  File "$DIR/yt-dlp/yt_dlp/downloader/fragment.py", line 524, in download_and_append_fragments
    for fragment, frag_content, frag_index, frag_filename in pool.map(_download_fragment, fragments):
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 598, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 598, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "$DIR/yt-dlp/yt_dlp/downloader/fragment.py", line 418, in interrupt_trigger_iter
    for f in fragments:
ValueError: generator already executing

$ ytdlp -U
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
```

**Comment by coletdjnz** [comment]
Can also reproduce the same error by running -N 16 and ctrl+c when you get 401 unauthorized.

```
$ yt-dlp https://www.youtube.com/watch\?v\=jgL0mA2SeGs --live-from-start -v --force-over -N 16
[debug] Command-line config: ['https://www.youtube.com/watch?v=jgL0mA2SeGs', '--live-from-start', '-v', '--force-over', '-N', '16']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.21-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=jgL0mA2SeGs
[youtube] jgL0mA2SeGs: Downloading webpage
[youtube] jgL0mA2SeGs: Downloading android player API JSON
[youtube] jgL0mA2SeGs: Downloading MPD manifest
[youtube] jgL0mA2SeGs: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] jgL0mA2SeGs: Downloading 1 format(s): 248+140
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/REDACTED"
[dashsegments] Total fragments: unknown (live)
[download] Destination: LIVE - View of Maidan square in Kyiv, Ukraine, after Russian invasion [jgL0mA2SeGs].f248.mkv
[dashsegments] Total fragments: unknown (live)
[download] Destination: LIVE - View of Maidan square in Kyiv, Ukraine, after Russian invasion [jgL0mA2SeGs].f140.mkv
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome

[download] 1.00KiB at  688.49B/s (00:01)
[download] 3.00KiB at  2.01KiB/s (00:01)
[...]
[download] 7.69MiB at  3.44MiB/s (00:02) (frag 98)
[download] 7.69MiB at  3.36MiB/s (00:02) (frag 98)
[download] Got server HTTP error: HTTP Error 401: Unauthorized. Retrying fragment 102 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 401: Unauthorized. Retrying fragment 103 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 401: Unauthorized. Retrying fragment 105 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 401: Unauthorized. Retrying fragment 104 (attempt 1 of 10) ...
[...]
[download] Got server HTTP error: HTTP Error 401: Unauthorized. Retrying fragment 178 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 102 ...
[download] fragment not found; Skipping fragment 103 ...
[download] fragment not found; Skipping fragment 104 ...
[...]
[download] fragment not found; Skipping fragment 8187 ...
[download] fragment not found; Skipping fragment 8188 ...

1: [download] 100% of 7.90MiB in 00:06               
ERROR: generator already executing
Traceback (most recent call last):
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1521, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2626, in process_video_result
    self.process_info(new_info)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3063, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2823, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/downloader/dash.py", line 56, in real_download
    return self.download_and_append_fragments_multiple(*args)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 429, in download_and_append_fragments_multiple
    result = result and bindoj_result(job)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 411, in bindoj_result
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 391, in thread_func
    return self.download_and_append_fragments(
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 524, in download_and_append_fragments
    for fragment, frag_content, frag_index, frag_filename in pool.map(_download_fragment, fragments):
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 598, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 598, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 418, in interrupt_trigger_iter
    for f in fragments:
ValueError: generator already executing
```

**Comment by Lesmiscore** [comment]
This is mysterious behavior since the generator is being consumed by only one, non-async function, running in an Executor. However, I can reproduce this.
ref. https://anandology.com/blog/using-iterators-and-generators/

Even iterator with lock can't counter this bug. Very strange.

```diff
diff --git a/yt_dlp/downloader/fragment.py b/yt_dlp/downloader/fragment.py
index e7224e27b..36e5a488e 100644
--- a/yt_dlp/downloader/fragment.py
+++ b/yt_dlp/downloader/fragment.py
@@ -4,6 +4,7 @@ import http.client
 import json
 import math
 import time
+import threading
 
 try:
     import concurrent.futures
@@ -418,13 +419,20 @@ class FragmentFD(FileDownloader):
         for idx, (ctx, fragments, info_dict) in enumerate(args):
             tpe = FTPE(math.ceil(max_workers / max_progress))
 
-            def interrupt_trigger_iter():
-                for f in fragments:
-                    if not interrupt_trigger[0]:
-                        break
-                    yield f
+            class InterruptTriggerIter():
+                def __init__(self) -> None:
+                    self.lock = threading.Lock()
+
+                def __iter__(self):
+                    return self
+
+                def __next__(self):
+                    with self.lock:
+                        if not interrupt_trigger[0]:
+                            raise StopIteration()
+                        return next(fragments)
 
-            job = tpe.submit(thread_func, idx, ctx, interrupt_trigger_iter(), info_dict, tpe)
+            job = tpe.submit(thread_func, idx, ctx, InterruptTriggerIter(), info_dict, tpe)
             spins.append((tpe, job))
 
         result = True
```

```
  File "/home/lesmi/youtube-dl/yt_dlp/YoutubeDL.py", line 3212, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/lesmi/youtube-dl/yt_dlp/YoutubeDL.py", line 2936, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/lesmi/youtube-dl/yt_dlp/downloader/common.py", line 273, in download
    return self.real_download(filename, info_dict), True
  File "/home/lesmi/youtube-dl/yt_dlp/downloader/dash.py", line 56, in real_download
    return self.download_and_append_fragments_multiple(*args)
  File "/home/lesmi/youtube-dl/yt_dlp/downloader/fragment.py", line 441, in download_and_append_fragments_multiple
    result = result and bindoj_result(job)
  File "/home/lesmi/youtube-dl/yt_dlp/downloader/fragment.py", line 416, in bindoj_result
    return future.result()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.10/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.10/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.10/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lesmi/youtube-dl/yt_dlp/downloader/fragment.py", line 396, in thread_func
    return self.download_and_append_fragments(
  File "/home/lesmi/youtube-dl/yt_dlp/downloader/fragment.py", line 546, in download_and_append_fragments
    for fragment in fragments:
  File "/home/lesmi/youtube-dl/yt_dlp/downloader/fragment.py", line 433, in __next__
    return next(fragments)
ValueError: generator already executing
```

**Comment by Lesmiscore** [comment]
Here's my clarification and apologies:
I thought Python will also capture all variables like Kotlin does, hence I omit a parameter to pass iterator to `interrupt_trigger_iter`. Lack of it lets multiple threads to share one iterator, so "ValueError: generator already executing" is raised ~~sometimes~~ most of the time.
It was my fault. Thanks for reporting and I apologies for my mistakes.
