### ISSUE TITLE
Daystar support

### ISSUE THREAD

**Issue by sebma** [yt-dlp/yt-dlp#2887]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

- Single Video : https://player.daystar.tv/0MTO2ITM

### Description

Hi,
I'd love to be able to download some videos from daystar.com.
Daystar seems to be using the LightCast.com player (seen when you right click on the video).

### Verbose log

```python
yt-dlp -v https://player.daystar.tv/0MTO2ITM
[debug] Command-line config: ['-v', 'https://player.daystar.tv/0MTO2ITM']
[debug] User config "/home/sebastien/.config/yt-dlp.conf": ['--format-sort', '+proto', '--ignore-errors', '--prefer-ffmpeg', '--no-warnings', '--restrict-filenames', '--add-metadata', '--write-auto-sub', '--embed-subs', '--embed-thumbnail', '--embed-metadata', '--sub-lang', 'en,fr,es,de', '--format', 'mp4[height<=?480]/mp4/best', '--output', '%(title)s__%(format_id)s__%(id)s__%(extractor)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-30-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.4.1-static (setts), ffprobe 4.4-1ppa1, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://player.daystar.tv/0MTO2ITM
[generic] 0MTO2ITM: Requesting header
[generic] 0MTO2ITM: Downloading webpage
[generic] 0MTO2ITM: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://player.daystar.tv/0MTO2ITM
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://player.daystar.tv/0MTO2ITM
```

**Comment by sebma** [comment]
@pukkandan @hatienl0i261299 Thanks :+1:
