### ISSUE TITLE
IHeartRadio does not work

### ISSUE THREAD

**Issue by AMTitan** [yt-dlp/yt-dlp#2890]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

I was trying to get [https://www.iheart.com/live/b985-5887/](https://www.iheart.com/live/b985-5887/) but when I tried it, it said that it was not supported. I looked at your supported website list and it was there. If you need any other information I am willing to give it just ask for what you need.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.iheart.com/live/b985-5887/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.10-arch1-1-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://www.iheart.com/live/b985-5887/
[generic] b985-5887: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] b985-5887: Downloading webpage
[generic] b985-5887: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.iheart.com/live/b985-5887/
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.iheart.com/live/b985-5887/
```

**Comment by Ashish0804** [comment]
Only podcasts are supported now.

**Comment by HobbyistDev** [comment]
Does `/live/` url stil exists ? Link that you gave redirect me to `/podcast` url
