### ISSUE TITLE
rockstargames.com

### ISSUE THREAD

**Issue by 07416** [yt-dlp/yt-dlp#2909]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- single video: https://www.rockstargames.com/videos/4861
- playlist: https://www.rockstargames.com/videos?type=game&gameId=912

- frontpage: https://www.rockstargames.com/videos

### Description

[Rockstar Games'](https://en.wikipedia.org/wiki/Rockstar_Games) streaming video platform. Has a local age verification.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.rockstargames.com/videos/4861']
[debug] System config "/etc/yt-dlp.conf": ['-o', '/home/user/Videos/youtube-dl/%(title)s [%(id)s].%(ext)s', '--sponsorblock-remove', 'all', '--embed-metadata', '--embed-subs', '--restrict-filenames', '--compat-options', 'no-live-chat', '--no-write-comments']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Lazy loading extractors is disabled
[debug] Compatibility options: no-live-chat
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.11-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://www.rockstargames.com/videos/4861
[generic] 4861: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 4861: Downloading webpage
[generic] 4861: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.rockstargames.com/videos/4861
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1380, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1450, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.rockstargames.com/videos/4861
```

**Comment by 07416** [comment]
An account is not needed to view videos (any, to my knowledge).

**Comment by pukkandan** [comment]
I wonder why I marked it as such 🤔

**Comment by HobbyistDev** [comment]
From your single url example( https://www.rockstargames.com/videos/4861 ), the video can be found either in webpage or json api call. In the webpage, the video is in `video` tag. For that link i found the api is `https://graph.rockstargames.com/?origin=https://www.rockstargames.com&operationName=Video&variables=%7B%22withTranslations%22%3Afalse%2C%22id%22%3A4861%2C%22locale%22%3A%22en_us%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%22c9a04a2dc4c9336a32f5ae4ed9e2077bcbc954cbee1e3db87fbc35eecdf5c627%22%7D%7D`. From there, we can get video from `['data']['video']`

**Comment by HobbyistDev** [comment]
I think this one should changed from `site-requests`, actually this one supported by yt-dlp ( see `yt_dlp/extractor`). The current extractor didn't detect this url (maybe because regex) and it seems the api url needed to change
