### ISSUE TITLE
Requesting specific format gives error in bash script but works fine on command line

### ISSUE THREAD

**Issue by merlinpatt** [yt-dlp/yt-dlp#2928]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

While this is similar to #714, it is different because the command works outside of a script, but not in a script.

When I run the below command on the command line, I am able to successfully download videos.

Command
```
yt-dlp -o '%(title)s.%(ext)s' --playlist-end 2 --dateafter now-7days -f 'best[height<=720]' https://www.youtube.com/user/LastWeekTonight
```

When I run this same command inside of a script, I get `ERROR: [youtube] -gd8yUptg0Q: Requested format is not available`.

And if I remove the format options, it works in the script.

Script
```
DAYS=7
YOUTUBE_DL_FORMAT="-f 'best[filesize<=150M]'"
YOUTUBE_DL_PARAMS="-o '%(title)s.%(ext)s' --playlist-end 2 --dateafter now-${DAYS}days $YOUTUBE_DL_FORMAT"
YOUTUBE_URL="https://www.youtube.com/user/LastWeekTonight"

# Download latest episode within last 7 days (assuming script is run every Monday)                                                                                      
  echo "yt-dlp $YOUTUBE_DL_PARAMS $YOUTUBE_URL"
  yt-dlp $YOUTUBE_DL_PARAMS $YOUTUBE_URL
```

OS: MacOS Monterey
Version: 12.2.1

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-o', "'%(title)s.%(ext)s'", '--playlist-end', '2', '--dateafter', 'now-7days', '-f', "'best[filesize<=150M]'", 'https://www.youtube.com/user/LastWeekTonight']
[debug] Portable config "/usr/local/bin/yt-dlp.conf": ['--embed-subs']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.9.7 (CPython 64bit) - macOS-12.2.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2-tessus, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/user/LastWeekTonight
[youtube:tab] LastWeekTonight: Downloading webpage
[youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[debug] [youtube:tab] Final URL: https://www.youtube.com/user/LastWeekTonight/videos
[download] Downloading playlist: LastWeekTonight - Videos
[youtube:tab] playlist LastWeekTonight - Videos: Downloading 2 videos
[download] Downloading video 1 of 2
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=-gd8yUptg0Q
[youtube] -gd8yUptg0Q: Downloading webpage
[youtube] -gd8yUptg0Q: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] -gd8yUptg0Q: Requested format is not available
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1517, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2588, in process_video_result
    raise ExtractorError('Requested format is not available', expected=True,
yt_dlp.utils.ExtractorError: [youtube] -gd8yUptg0Q: Requested format is not available

[download] Downloading video 2 of 2
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=EICp1vGlh_U
[youtube] EICp1vGlh_U: Downloading webpage
[youtube] EICp1vGlh_U: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] EICp1vGlh_U: Requested format is not available
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1517, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2588, in process_video_result
    raise ExtractorError('Requested format is not available', expected=True,
yt_dlp.utils.ExtractorError: [youtube] EICp1vGlh_U: Requested format is not available

[download] Finished downloading playlist: LastWeekTonight - Videos
```

**Comment by pukkandan** [comment]
That is not how you quote in bash scripts. Remove all the single quotes from your script and it should work
