### ISSUE TITLE
frontendmaster TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by Ex-Communicad0** [yt-dlp/yt-dlp#2946]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

There is a Error >> TypeError: 'bool' object is not subscriptable

is it possible to fix this? I am willing to share credentials for check personally

### Verbose log

```shell
yt-dlp -vU --cookies front_cookies.txt https://frontendmasters.com/courses/pwas/
[debug] Command-line config: ['-vU', '--cookies', 'front_cookies.txt', 'https://frontendmasters.com/courses/pwas/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-102564-g2261cc6d8a (setts), ffprobe N-102564-g2261cc6d8a
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [FrontendMastersCourse] Extracting URL: https://frontendmasters.com/courses/pwas/
[FrontendMastersCourse] pwas: Downloading course JSON
[download] Downloading playlist: Build Progressive Web Apps (PWAs) from Scratch
[FrontendMastersCourse] playlist Build Progressive Web Apps (PWAs) from Scratch: Collected 25 videos; downloading 25 of them
[download] Downloading video 1 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:QUXnPXJfxU
[FrontendMasters] QUXnPXJfxU: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 2 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:UVONSCEypL
[FrontendMasters] UVONSCEypL: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 3 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:eSBorVOaPE
[FrontendMasters] eSBorVOaPE: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 4 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:WxlFcnmOeU
[FrontendMasters] WxlFcnmOeU: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 5 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:qORLTmcDtd
[FrontendMasters] qORLTmcDtd: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 6 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:DVREpgZBwJ
[FrontendMasters] DVREpgZBwJ: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 7 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:FntpztFAcv
[FrontendMasters] FntpztFAcv: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 8 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:OAxSMTKdAH
[FrontendMasters] OAxSMTKdAH: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 9 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:vZYoOqysxN
[FrontendMasters] vZYoOqysxN: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 10 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:CJvBakTMuI
[FrontendMasters] CJvBakTMuI: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 11 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:vfjIwWXykk
[FrontendMasters] vfjIwWXykk: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 12 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:JDQRunQocw
[FrontendMasters] JDQRunQocw: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 13 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:uKNhwTsOVu
[FrontendMasters] uKNhwTsOVu: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 14 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:KkNmWodNwJ
[FrontendMasters] KkNmWodNwJ: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 15 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:iZeWrnJAES
[FrontendMasters] iZeWrnJAES: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 16 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:jwLlsuXVsI
[FrontendMasters] jwLlsuXVsI: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 17 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:IlEvZfAmDx
[FrontendMasters] IlEvZfAmDx: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 18 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:PaJNGvzHKy
[FrontendMasters] PaJNGvzHKy: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 19 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:weVAOdCbXw
[FrontendMasters] weVAOdCbXw: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 20 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:VZJiJmMmMt
[FrontendMasters] VZJiJmMmMt: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 21 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:WSzuSlYkHC
[FrontendMasters] WSzuSlYkHC: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 22 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:NvZNPdzExe
[FrontendMasters] NvZNPdzExe: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 23 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:fNRkEwdHBJ
[FrontendMasters] fNRkEwdHBJ: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 24 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:DQnZlFSDjF
[FrontendMasters] DQnZlFSDjF: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 429: Too Many Requests
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Downloading video 25 of 25
[debug] [FrontendMasters] Extracting URL: frontendmasters:mWEnVYTSRJ
[FrontendMasters] mWEnVYTSRJ: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 429: Too Many Requests
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\frontendmasters.py", line 154, in _real_extract
TypeError: 'bool' object is not subscriptable

[download] Finished downloading playlist: Build Progressive Web Apps (PWAs) from Scratch
```

**Comment by Ex-Communicad0** [comment]
yt-dlp --cookies cookies.txt https://stream.frontendmasters.com/2022/01/11/Wx****FH/QU****/index_1080_Q8_7mbps.m3u8
[generic] index_1080_Q8_7mbps: Requesting header
[generic] index_1080_Q8_7mbps: Downloading m3u8 information
[info] index_1080_Q8_7mbps: Downloading 1 format(s): 0
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 136
[download] Destination: index_1080_Q8_7mbps [index_1080_Q8_7mbps].mp4
[download] 100% of 21.68MiB in 01:17
[FixupM3u8] Fixing MPEG-TS in MP4 container of "index_1080_Q8_7mbps [index_1080_Q8_7mbps].mp4"

I am able to dl single video but need to download all playlist

**Comment by Ex-Communicad0** [comment]
Bump

**Comment by suds-sky** [comment]
Is there any update on this issue, I am also facing the same issue

**Comment by temp192000** [comment]
> 

Hey, Hi. I was using "get cookies.txt" to get cookies and i ran same way you'd commented. But, i get a 403. 
Did try with user, pass, still same. any idea why do auth fails?

**Comment by HobbyistDev** [comment]
I think this one make the bug:
https://github.com/yt-dlp/yt-dlp/blob/1ac4fd80c87d4e566ae680076e788a63d187199b/yt_dlp/extractor/frontendmasters.py#L140-L151

This is the log after applying `print('format_url')`:
```
(python_proj2) ~\yt-dlp>python -m yt_dlp -v -s ""https://frontendmasters.com/courses/pwas/""
[debug] Command-line config: ['-v', '-s', 'https://frontendmasters.com/courses/pwas/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e74] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: b8a9acdb0
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [FrontendMastersCourse] Extracting URL: https://frontendmasters.com/courses/pwas/
[FrontendMastersCourse] pwas: Downloading course JSON
[download] Downloading playlist: Build Progressive Web Apps (PWAs) from Scratch
[FrontendMastersCourse] Playlist Build Progressive Web Apps (PWAs) from Scratch: Downloading 5 videos of 5
[download] Downloading video 1 of 5
[debug] [FrontendMasters] Extracting URL: frontendmasters:QUXnPXJfxU
[FrontendMasters] QUXnPXJfxU: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 401: Unauthorized
print(format_url) : False
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "~\yt-dlp\yt_dlp\YoutubeDL.py", line 1427, in wrapper
    return func(self, *args, **kwargs)
  File "~\yt-dlp\yt_dlp\YoutubeDL.py", line 1497, in __extract_info
    ie_result = ie.extract(url)
  File "~\yt-dlp\yt_dlp\extractor\common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "~\yt-dlp\yt_dlp\extractor\frontendmasters.py", line 153, in _real_extract
    print(f"print(format_url['url']) : {format_url['url']}")
TypeError: 'bool' object is not subscriptable

[download] Downloading video 2 of 5
[debug] [FrontendMasters] Extracting URL: frontendmasters:qORLTmcDtd
[FrontendMasters] qORLTmcDtd: Downloading webm-low source JSON
WARNING: [FrontendMasters] Unable to download JSON metadata: HTTP Error 401: Unauthorized
print(format_url) : False
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "~\yt-dlp\yt_dlp\YoutubeDL.py", line 1427, in wrapper
    return func(self, *args, **kwargs)
  File "~\yt-dlp\yt_dlp\YoutubeDL.py", line 1497, in __extract_info
    ie_result = ie.extract(url)
  File "~\yt-dlp\yt_dlp\extractor\common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "~\yt-dlp\yt_dlp\extractor\frontendmasters.py", line 153, in _real_extract
    print(f"print(format_url['url']) : {format_url['url']}")
TypeError: 'bool' object is not subscriptable
```

I think the api changed, from the [url](https://frontendmasters.com/courses/pwas/), i found the video base url is in `video` tag with `data-fmp` attribute and we can get the video with `<data-fmp>/hls/index.m3u8`. However, i didn't know any api call and i didn't check other url. Hope this can help

**Comment by nbili** [comment]
Is there any update on this issue?

**Comment by sudofix** [comment]
any updates on this?

**Comment by sudokar** [comment]
Any update on this? Has anyone looked into it?

**Comment by GarfieldDeepClone** [comment]
What's the status here? I can't even download a single file from FrontendMasters.com
