### ISSUE TITLE
BBC.co.uk Not downloaded with the tag "Signed"

### ISSUE THREAD

**Issue by ttonych** [yt-dlp/yt-dlp#2979]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The problem with the video is marked on the site as "This is a Signed version of this program. In the browser this program is playing normally. Other programs without the "Signed" mark are downloading without any problems.

### Verbose log

```shell
[debug] Command-line config: ['--cookies-from-browser', 'firefox:1q9pamb6.TunnelBears', '--add-metadata', '--add-chapters', '--extractor-retries', '1000', '-R', '1000', '--write-subs', '--sub-format', 'ttml', 'https://www.bbc.co.uk/iplayer/episode/m000slpt/gardeners-world-winter-specials-episode-3', '-vU']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\glock\AppData\Roaming\Mozilla\Firefox\Profiles\1q9pamb6.TunnelBears\cookies.sqlite"
[Cookies] Extracted 655 cookies from firefox
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2022-02-17-git-2812508086-full_build-www.gyan.dev (setts), ffprobe 2022-02-17-git-2812508086-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/m000slpt/gardeners-world-winter-specials-episode-3
[bbc.co.uk] m000slpt: Downloading video page
[bbc.co.uk] m000slpt: Downloading playlist JSON
ERROR: local variable 'programme_id' referenced before assignment
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\bbc.py", line 580, in _real_extract
  File "yt_dlp\extractor\bbc.py", line 477, in _download_playlist
UnboundLocalError: local variable 'programme_id' referenced before assignment
```

**Comment by chapmanjacobd** [comment]
I also get an error for BBC World Service (I don't know if it is the same thing)

```
/m/d/82_Audiobooks [1] 🃅 yt.ogg -v https://www.bbc.co.uk/programmes/p01rcrn6/episodes/downloads
[debug] Command-line config: ['-i', '--youtube-skip-dash-manifest', '--download-archive', '/home/xk/.local/share/yt_archive.txt', '--retries', 'infinite', '--extractor-retries', 'infinite', '-f', 'bestaudio', '--extract-audio', '-v', 'https://www.bbc.co.uk/programmes/p01rcrn6/episodes/downloads', '--exec', 'ffmpeg -hide_banner -loglevel panic -y -i {} -c:a libopus -ac 2 -b:a 128k -vbr constrained -filter:a loudnorm=i=-18:lra=17 "`echo {} | cut -f 1 -d \'.\' | sed \'s/$/n.opus/\'`" && rm {} ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.11-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file '/home/xk/.local/share/yt_archive.txt'
[debug] [bbc.co.uk:playlist] Extracting URL: https://www.bbc.co.uk/programmes/p01rcrn6/episodes/downloads
[bbc.co.uk:playlist] p01rcrn6: Downloading webpage
[download] Downloading playlist: BBC World Service - Elements - Downloads
[bbc.co.uk:playlist] playlist BBC World Service - Elements - Downloads: Downloading 31 videos
[download] Downloading video 1 of 31
[debug] [bbc.co.uk] Extracting URL: http://www.bbc.co.uk/programmes/p02rqfk1
[bbc.co.uk] p02rqfk1: Downloading video page
[bbc.co.uk] p02rqfk1: Downloading playlist JSON
ERROR: local variable 'programme_id' referenced before assignment
Traceback (most recent call last):
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/extractor/bbc.py", line 580, in _real_extract
    programme_id, title, description, duration, formats, subtitles = self._download_playlist(group_id)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/extractor/bbc.py", line 477, in _download_playlist
    return programme_id, title, description, duration, formats, subtitles
UnboundLocalError: local variable 'programme_id' referenced before assignment
```

**Comment by dirkf** [comment]
These both occur because `http://www.bbc.co.uk/programmes/%s/playlist.json' % playlist_id` is returning a JSON object whose `allAvailableVersions` member is an empty list. Apparently this didn't happen before but the code is obviously unsafe in assuming that the list must be populated. Unfortunately the existing fallback doesn't help in getting the desired playlist data (404), so the extraction would crash anyway.

yt-dl goes for the `defaultAvailableVersion` member, instead of trying each of `allAvailableVersions`, but that's null, so the result is equally bad.

**Comment by nyuszika7h** [comment]
Yeah, that was my change, since sometimes BBC messes up and `defaultAvailableVersion` ends up being an SD-only audio-described version.

**Comment by dirkf** [comment]
https://www.bbc.co.uk/iplayer/episode/m000slpt/gardeners-world-winter-specials-episode-3 has expired on iPlayer (last shown a year ago).

https://www.bbc.co.uk/programmes/p01rcrn6/episodes/downloads is more interesting. It seems to be a WS Podcast page with embedded links like this https://open.live.bbc.co.uk/mediaselector/6/redir/version/2.0/mediaset/audio-nondrm-download/proto/https/vpid/p02rqfk4.mp3. These items can't be found with the [Media Availability Tool](http://media-availability.tools.bbc.co.uk/) because the Mediaset `audio-nondrm-download` is not in the pull-down, and doesn't appear to work when pasted into the URL query parameters.

Looking at `p01rcrn6`, it has a [programmes page](https://www.bbc.co.uk/programmes/p01rcrn6/) and the 58 episodes can be found by going to https://www.bbc.co.uk/programmes/p01rcrn6/episodes/player and paging through the list until the 'Next>' element `<li class="pagination__next">...</li>` contains no link. Unlike `p01rcrn6`, each episode (eg "Iron" https://www.bbc.co.uk/programmes/p036q92j) has a `playlist.json`. However there are no version details, causing the error as reported. Instead, there are two not necessarily exclusive tactics:
* the metadata can be extracted from the page (probably the best target is the ld+json element of type `RadioEpisode`) and the media URL (mp3) can pulled from the 'Podcast' link https://www.bbc.co.uk/programmes/p01rcrn6/episodes/downloads (but this is a playlist -- perhaps just use special knowledge to construct the open.live mp3 link);
* the metadata and media URLs (m4a) can be collected using the 'Listen now' Sounds link https://www.bbc.co.uk/sounds/play/p036q92j.

Currently, for both yt-dl and yt-dlp:
* https://www.bbc.co.uk/programmes/p01rcrn6/ fails 'unable to download XML';
* the pagination isn't working on https://www.bbc.co.uk/programmes/p01rcrn6/episodes/player, but the episodes on the actual page are found;
* an episode (eg "Iron" https://www.bbc.co.uk/programmes/p036q92j) is found;
* a Sounds link (eg https://www.bbc.co.uk/sounds/play/p036q92j) works;
* the podcast playlist link https://www.bbc.co.uk/programmes/p01rcrn6/episodes/downloads fails, as reported.

**Comment by bashonly** [comment]
see also https://github.com/yt-dlp/yt-dlp/issues/6965#issuecomment-1529938381
