### ISSUE TITLE
Site Request: Pornzog (NSFW)

### ISSUE THREAD

**Issue by ButtM0nkey** [yt-dlp/yt-dlp#2982]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

- Single Video: https://pornzog.com/video/11952345/adina-arbour-cumshot-compilation-with-8-cumshots/

### Description

Opening this request for pornzog.com to be added as a supported site. Ideally, this site would have the same downloading functionality as any of the other supported sites.

### Verbose log

```shell
G:\ytdlp>yt-dlp -vU https://pornzog.com/video/11952345/adina-arbour-cumshot-compilation-with-8-cumshots/
[debug] Command-line config: ['-vU', 'https://pornzog.com/video/11952345/adina-arbour-cumshot-compilation-with-8-cumshots/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 5.0-full_build-www.gyan.dev (setts), ffprobe 5.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://pornzog.com/video/11952345/adina-arbour-cumshot-compilation-with-8-cumshots/
[generic] adina-arbour-cumshot-compilation-with-8-cumshots: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] adina-arbour-cumshot-compilation-with-8-cumshots: Downloading webpage
[generic] adina-arbour-cumshot-compilation-with-8-cumshots: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://pornzog.com/video/11952345/adina-arbour-cumshot-compilation-with-8-cumshots/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3986, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://pornzog.com/video/11952345/adina-arbour-cumshot-compilation-with-8-cumshots/
```

**Comment by cerealXDD** [comment]
Bump
