### ISSUE TITLE
Postprocessing: Decoder (codec none) not found for input stream #0:0 error when trying to embed GIF thumbnail

### ISSUE THREAD

**Issue by revolter** [yt-dlp/yt-dlp#2988]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

```
yt-dlp https://www.mixcloud.com/zonalibera/zona-libera-468-aired-31-martie-2015-happy-aur/
```

works correctly.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--embed-thumbnail', 'https://www.mixcloud.com/zonalibera/zona-libera-468-aired-31-martie-2015-happy-aur/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.2 (CPython 64bit) - macOS-12.2.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [mixcloud] Extracting URL: https://www.mixcloud.com/zonalibera/zona-libera-468-aired-31-martie-2015-happy-aur/
[mixcloud] zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur: Downloading JSON metadata
[mixcloud] zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur: Downloading m3u8 information
[mixcloud] zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur: Downloading 1 format(s): http
Deleting existing file Zona Libera 468 _ aired 31 martie 2015_ ''Happy Aur'' [zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur].gif
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: Zona Libera 468 _ aired 31 martie 2015_ ''Happy Aur'' [zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur].gif
[debug] Invoking downloader on "https://stream11.mixcloud.com/secure/c/m4a/64/6/5/f/8/6acb-8698-4429-bd8d-f1e5faca4a1d.m4a?sig=L0ZtYxFFlQuqmwx3WLEArg"
[download] Zona Libera 468 _ aired 31 martie 2015_ ''Happy Aur'' [zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur].m4a has already been downloaded

[download] 100% of 59.52MiB
[ThumbnailsConvertor] Converting thumbnail "Zona Libera 468 _ aired 31 martie 2015_ ''Happy Aur'' [zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur].gif" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:Zona Libera 468 _ aired 31 martie 2015_ '"'"''"'"'Happy Aur'"'"''"'"' [zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur].gif' -movflags +faststart 'file:Zona Libera 468 _ aired 31 martie 2015_ '"'"''"'"'Happy Aur'"'"''"'"' [zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur].png'
[debug] ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.3)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[image2 @ 0x13fe04a90] Could not find codec parameters for stream 0 (Video: none, none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, image2, from 'file:Zona Libera 468 _ aired 31 martie 2015_ ''Happy Aur'' [zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur].gif':
  Duration: 00:00:00.04, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: none, none, 25 fps, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (? (?) -> png (native))
Decoder (codec none) not found for input stream #0:0
ERROR: Postprocessing: Decoder (codec none) not found for input stream #0:0
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3159, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/opt/homebrew/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3336, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/opt/homebrew/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3323, in run_all_pps
    info = self.run_pp(pp, info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3296, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/opt/homebrew/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 117, in wrapper
    return func(self, info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/postprocessor/embedthumbnail.py", line 96, in run
    thumbnail_filename = convertor.convert_thumbnail(thumbnail_filename, 'png')
  File "/opt/homebrew/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 1095, in convert_thumbnail
    self.real_run_ffmpeg(
  File "/opt/homebrew/Cellar/yt-dlp/2022.2.4/libexec/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 333, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Decoder (codec none) not found for input stream #0:0
```

**Comment by revolter** [comment]
Looking again through the output, I now understood that this command fails:
```sh
ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:Zona Libera 468 _ aired 31 martie 2015_ '"'"''"'"'Happy Aur'"'"''"'"' [zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur].gif' -movflags +faststart 'file:Zona Libera 468 _ aired 31 martie 2015_ '"'"''"'"'Happy Aur'"'"''"'"' [zonalibera_zona-libera-468-aired-31-martie-2015-happy-aur].png'
```
BTW, I didn't even know that `ffmpeg` can convert images too, I always used ImageMagick for images, and ffmpeg for audios and videos.

**Comment by revolter** [comment]
Using the [Music app](https://support.apple.com/en-gb/guide/music/welcome/mac), I successfully added the GIF file as artwork. But I don't know if they're converting it behind scenes or not.
