### ISSUE TITLE
Error reporting fails on Python<3.10

### ISSUE THREAD

**Issue by flashdagger** [yt-dlp/yt-dlp#2993]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

see log

### Verbose log

```shell
[debug] Command-line config: ['https://vimeo.com/123/123', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.6.15 (CPython 64bit) - Linux-4.19.104-microsoft-standard-x86_64-with-debian-bullseye-sid
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [vimeo] Extracting URL: https://vimeo.com/123/123
Traceback (most recent call last):
  File "~/lib/python3.6/site-packages/yt_dlp/extractor/common.py", line 735, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "~/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 3591, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "~/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "~/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "~/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "~/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "~/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/lib/python3.6/site-packages/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "~/lib/python3.6/site-packages/yt_dlp/extractor/vimeo.py", line 805, in _real_extract
    url, video_id, headers=headers)
  File "~/lib/python3.6/site-packages/yt_dlp/extractor/common.py", line 768, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "~/lib/python3.6/site-packages/yt_dlp/extractor/common.py", line 753, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "~/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
    ie_result = ie.extract(url)
  File "~/lib/python3.6/site-packages/yt_dlp/extractor/common.py", line 643, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.ExtractorError: [vimeo] 123: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "~/lib/python3.6/site-packages/yt_dlp/__init__.py", line 864, in main
    _real_main(argv)
  File "~/lib/python3.6/site-packages/yt_dlp/__init__.py", line 854, in _real_main
    retcode = ydl.download(all_urls)
  File "~/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 3255, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "~/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 3227, in wrapper
    res = func(*args, **kwargs)
  File "~/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 1380, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "~/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 1407, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "~/lib/python3.6/site-packages/yt_dlp/utils.py", line 1088, in format_traceback
    self.cause and ''.join(traceback.format_exception(self.cause)[1:]),
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
```

**Comment by pukkandan** [comment]
I marked this as high priority coz I initially though the original stacktrace was being obscured by this issue. But on closer inspection, I can see the original tb is still visible. So a hotfix release should not be needed for this

**Comment by coletdjnz** [comment]
> But on closer inspection, I can see the original tb is still visible. So a hotfix release should not be needed for this

Wouldn't this potentially cause issues for existing scripts when using yt-dlp embedded? Since catching ExtractorError wouldn't work?
