### ISSUE TITLE
VHX Site - Les Mills on Demand

### ISSUE THREAD

**Issue by spoonys** [yt-dlp/yt-dlp#2998]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Description

A while ago I used to be able to download from lesmills on demand using the embedded VHX URL: 

yt-dlp "https://embed.vhx.tv/videos/130503?api=1&referrer=https%3A%2F%2Fwatch.lesmillsondemand.com&vimeo=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0MjExMTEyOCwiZXhwIjoxNjQ2NzUyNzkzfQ.TthAS9lC-lR-
rVRNcLPMgFGUNgHbyZtaSAva4Sz9sVQ" 

Above is an example. After much messing around last night I managed to get one to DL but struggling to see why it won't do any others. Verbose is below for the success and failure this morning.

### Verbose log

```shell
yt-dlp --verbose "https://embed.vhx.tv/videos/278741?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0MjExMTEyOCwiZXhwIjoxNjQ2Nzc4ODU1fQ.kkoAentbYVfXrM_IZ7PP9ACYQNi5cJS9ua4HlxYVg8o&autoplay=1&back=BODYBALANCE%20-%20All&collection_id=69599&color=696969&context=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodybalance%2Fseason%3A1&is_trailer=false&live=0&locale=en&playsinline=1&product_id=29964&referrer=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodybalance&sharing=1&title=0&vimeo=1"
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
[debug] Command-line config: ['--verbose', 'https://embed.vhx.tv/videos/278741?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0MjExMTEyOCwiZXhwIjoxNjQ2Nzc4ODU1fQ.kkoAentbYVfXrM_IZ7PP9ACYQNi5cJS9ua4HlxYVg8o&autoplay=1&back=BODYBALANCE%20-%20All&collection_id=69599&color=696969&context=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodybalance%2Fseason%3A1&is_trailer=false&live=0&locale=en&playsinline=1&product_id=29964&referrer=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodybalance&sharing=1&title=0&vimeo=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-167-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [vhx:embed] Extracting URL: https://embed.vhx.tv/videos/278741?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0MjExMTEyOCwiZXhwIjoxNjQ2Nzc4ODU1fQ.kkoAentbYVfXrM_IZ7PP9ACYQNi5cJS9ua4HlxYVg8o&autoplay=1&back=BODYBALANCE%20-%20All&collection_id=69599&color=696969&context=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodybalance%2Fseason%3A1&is_trailer=false&live=0&locale=en&playsinline=1&product_id=29964&referrer=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodybalance&sharing=1&title=0&vimeo=1
[vhx:embed] 278741: Downloading webpage
[vhx:embed] 278741: Downloading JSON metadata
[vhx:embed] 278741: Downloading akfire_interconnect_quic m3u8 information
[vhx:embed] 278741: Downloading akfire_interconnect_quic m3u8 information
[vhx:embed] 278741: Downloading fastly_skyfire m3u8 information
[vhx:embed] 278741: Downloading fastly_skyfire m3u8 information
[vhx:embed] 278741: Downloading akfire_interconnect_quic MPD information
[vhx:embed] 278741: Downloading akfire_interconnect_quic MPD information
[vhx:embed] 278741: Downloading fastly_skyfire MPD information
[vhx:embed] 278741: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 278741: Downloading 1 format(s): http-1080p
[debug] Invoking downloader on "https://vod-progressive.akamaized.net/exp=1646775623~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F956%2F27%2F679781558%2F3133593232.mp4~hmac=34c0db937da210415d9c42439dd559d9cfee0ffd020861a0efe1e712584e9e3e/vimeo-prod-skyfire-std-us/01/956/27/679781558/3133593232.mp4"
[download] Destination: Untitled [278741].mp4
[download] 100% of 43.82MiB in 00:11

yt-dlp "https://embed.vhx.tv/videos/1748143?api=1&amp;auth-user-token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ2YmZlZmMzNGIyNTdhYTE4Y2E2NDUzNDE2ZTlmZmRjNjk4MDAxMDdhZTQ2ZWJhODg0YTU2ZDBjOGQ4NTYzMzgifQ.eyJhcHBfaWQiOjQ3NTgzLCJleHAiOjE2NDY4MjMwOTgsIm5vbmNlIjoiMmVjODlkNzJmYjExM2YyOCIsInNlc3Npb25faWQiOiI0OFpERXBOaWFCZ0NDTjZsNmFnclNRPT0iLCJzaXRlX2lkIjozODA4MSwidXNlcl9pZCI6NDIxMTExMjh9.G2jXyW4s1jH7QGjigXzlpsGRCKjdfCfphAmRbjp6rfLNOMFPWgFVbcaYhx0Km3LQMx0uPWW9VlSO9b_it4Kk4wvLRnEcTFrTDS9MER0I0VIHd1rh3k0HHDLXXrWGVG592DxwmNii_3TitygS712-mPssJej7HY9Iz5SsqPhnHRm_gjfsHEAAaswPmArKh3sKdetBBB8Gis1ix4R0z7H1EQ4Wq3pGZftj8HKjwTKtK4xIfI158lHSMhJLBJu1bc4CHDYg2yt-mgjLXuB4iA5UpTUyt5JxhAsvaeMOTTo9Fdyz8qN3UgRMXCMfjHV88qzcmQz0s9wwaWR-jrWs-2BttfqI7mChQFRtpK9Xu9e6_UfUU3CiDsQzkVO1wrHIjMXYf7vt6j7QN4D0vLHiALWRhpHnqleGiU9zAnn5Aq3gLpfWhGfx-tSy2X0G-tJMIm5PfwVFw2oubjAPNO3wEMW1J1DLU_Uxy4TKJkESHnrEHpTeK5zI9NFzP4oekcVDAy6Km5vhC_1EbgSkAZmqKZBN7VunhWfN1QZ8WdyP6GFrOkSUa0az_ffpK4TzW4lSp3V0bW4NWFyiq7DpSDfkZultpBvuoJMg7IZ26ZrCMsyesZzXpiYg8P3bXC0oDUpcYX7W81d_OpWA4dqs-kHf4Hjpjn2Wff12QTMFTHxk1kk_TWY&amp;autoplay=1&amp;back=Six-week%20quick%20fitness%20blast&amp;collection_id=670179&amp;color=696969&amp;context=https%3A%2F%2Fwatch.lesmillsondemand.com%2Ffast-blast-challenge&amp;is_trailer=false&amp;live=0&amp;locale=en&amp;playsinline=1&amp;product_id=29964&amp;referrer=https%3A%2F%2Fwatch.lesmillsondemand.com%2Ffast-blast-challenge&amp;sharing=1&amp;title=0&amp;vimeo=1"
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
[vhx:embed] 1748143: Downloading webpage
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 735, in _request_webpage
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3591, in urlopen
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 617, in extract
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/vimeo.py", line 1329, in _real_extract
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 903, in _download_webpage
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 768, in _download_webpage_handle
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [vhx:embed] 1748143: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 864, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 854, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3255, in download
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3227, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1380, in extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1407, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
```

**Comment by dirkf** [comment]
Same success+failure with yt-dl

**Comment by spoonys** [comment]
> Same success+failure with yt-dl. This site, not directly requested, may need its own extractor like DropoutTV?

Maybe it does actually, it did used to work with a basic link - perhaps something has changed. A little over my head.

**Comment by pukkandan** [comment]
> - [X] I've checked that all provided URLs are alive and playable in a browser

The URL you gave is NOT accessible in browser. Provide the actual webpage URL

**Comment by spoonys** [comment]
It worked initially until the token expired. Site here: https://watch.lesmillsondemand.com/fast-blast-challenge/videos/bodycombat-87-30-min 

Requires login which I can share.

**Comment by pukkandan** [comment]
Can you share the new embed URL so I can check?

**Comment by spoonys** [comment]
https://embed.vhx.tv/videos/278741?api=1&auth-user-token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ2YmZlZmMzNGIyNTdhYTE4Y2E2NDUzNDE2ZTlmZmRjNjk4MDAxMDdhZTQ2ZWJhODg0YTU2ZDBjOGQ4NTYzMzgifQ.eyJhcHBfaWQiOjQ3NTgzLCJleHAiOjE2NDY4NjgyODksIm5vbmNlIjoiN2E5ZGUxNTQ3ZjdlMzAxYSIsInNlc3Npb25faWQiOiJUajJaY1NNT2xVOFBXV0hkUTdJUFd3PT0iLCJzaXRlX2lkIjozODA4MSwidXNlcl9pZCI6NDIxMTExMjh9.mY7YjKSSlbP6-wk9gO9VRKz0CpAcqe18qaQW-cU8v7grzR7sETZ8lGRIf3Vw-iiDFErz4gmWnEEot8zDDU5xeR9BJl9Pzy_IFoSxzuJCCoqQzqINB4Zaefy70Y5J1ZiZAnDWrqhMHdrsRRn73TICpoff5d-Pw_SmEMN9Rrkp2s2RnbtoLpnVoV2XHTRD7EqSPA6Khbuedz9NlCsNgMVefWjgYdTyCUjdMg18spkPplPKTL3zqzMQET0JIwcO8cbkLzfstTOyUkHzyUHsahdPYE64JWZbHwtz5Zao0lBfelxi2-22Rm9ZqCSGE3aw7-c5hpgwwxulIesaUZXhCluWOhecNDi31JtWAXIv6WSy_Srcpy4aUu9fWTUA68FMXIBOFYqr6O-ykC3Vmf9k9yhyQJPx9WJ2RMfh7ThqQHIsLTz_fnICqIJ_IDhbzNzCIRpEcyOieuUvcFs7pAr-UeG_6BLvb4PUy5BaM6V8hxDW-JD_2jw36plPdeR1OGo6RJhr8cKX7vCdxzxGk6W9T3ISVLZ1rFZX4QjNJAEYVpMIr77LXoLUjmDNPQNYUyQCz75vROHmLvjFJTOljRkut6WIPcFmoeDk_NdjjN9bGMEMw-AhoE_gMPP7C_TUevSQOYkbZQWhNaDzUNn4uS-GplcHADsMa7eEMRKyEx4Ab06ibI8&autoplay=1&back=BODYBALANCE%20-%20All&collection_id=69599&color=696969&context=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodybalance%2Fseason%3A1&is_trailer=false&live=0&locale=en&playsinline=1&product_id=29964&referrer=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodybalance&sharing=1&title=0&vimeo=1"

**Comment by pukkandan** [comment]
That downloads:
```
❯ yt-dlp "https://embed.vhx.tv/videos/278741?api=1&auth-user-token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ2YmZlZmMzNGIyNTdhYTE4Y2E2NDUzNDE2ZTlmZmRjNjk4MDAxMDdhZTQ2ZWJhODg0YTU2ZDBjOGQ4NTYzMzgifQ.eyJhcHBfaWQiOjQ3NT
gzLCJleHAiOjE2NDY4NjgyODksIm5vbmNlIjoiN2E5ZGUxNTQ3ZjdlMzAxYSIsInNlc3Npb25faWQiOiJUajJaY1NNT2xVOFBXV0hkUTdJUFd3PT0iLCJzaXRlX2lkIjozODA4MSwidXNlcl9pZCI6NDIxMTExMjh9.mY7YjKSSlbP6-wk9gO9VRKz0CpAcqe18qaQW-cU8v
7grzR7sETZ8lGRIf3Vw-iiDFErz4gmWnEEot8zDDU5xeR9BJl9Pzy_IFoSxzuJCCoqQzqINB4Zaefy70Y5J1ZiZAnDWrqhMHdrsRRn73TICpoff5d-Pw_SmEMN9Rrkp2s2RnbtoLpnVoV2XHTRD7EqSPA6Khbuedz9NlCsNgMVefWjgYdTyCUjdMg18spkPplPKTL3zqzMQE
T0JIwcO8cbkLzfstTOyUkHzyUHsahdPYE64JWZbHwtz5Zao0lBfelxi2-22Rm9ZqCSGE3aw7-c5hpgwwxulIesaUZXhCluWOhecNDi31JtWAXIv6WSy_Srcpy4aUu9fWTUA68FMXIBOFYqr6O-ykC3Vmf9k9yhyQJPx9WJ2RMfh7ThqQHIsLTz_fnICqIJ_IDhbzNzCIRpEc
yOieuUvcFs7pAr-UeG_6BLvb4PUy5BaM6V8hxDW-JD_2jw36plPdeR1OGo6RJhr8cKX7vCdxzxGk6W9T3ISVLZ1rFZX4QjNJAEYVpMIr77LXoLUjmDNPQNYUyQCz75vROHmLvjFJTOljRkut6WIPcFmoeDk_NdjjN9bGMEMw-AhoE_gMPP7C_TUevSQOYkbZQWhNaDzUNn4u
S-GplcHADsMa7eEMRKyEx4Ab06ibI8&autoplay=1&back=BODYBALANCE%20-%20All&collection_id=69599&color=696969&context=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodybalance%2Fseason%3A1&is_trailer=false&live=0&lo
cale=en&playsinline=1&product_id=29964&referrer=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodybalance&sharing=1&title=0&vimeo=1"
[vhx:embed] 278741: Downloading webpage
[vhx:embed] 278741: Downloading JSON metadata
[vhx:embed] 278741: Downloading akfire_interconnect_quic m3u8 information
[vhx:embed] 278741: Downloading akfire_interconnect_quic m3u8 information
[vhx:embed] 278741: Downloading akfire_interconnect_quic MPD information
[vhx:embed] 278741: Downloading akfire_interconnect_quic MPD information
[info] 278741: Downloading 1 format(s): http-1080p
[download] Destination: Untitled [278741].mp4
[download]  14.9% of 43.82MiB at  2.85MiB/s ETA 00:13
ERROR: Interrupted by user
```

**Comment by spoonys** [comment]
It does... yet others don't. I need to figure the difference.

**Comment by pukkandan** [comment]
Just add referer:
```
❯ yt-dlp "embed.vhx.tv/videos/1925794?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0MjExMTEyOCwiZXhwIjoxNjQ2ODY4NTE2fQ.vTGLrT6aQzZvwZGXA7z8t4hRS9yV_qgHYm1x4RG8DWY&autoplay=1&back=BODYPUMP%20-%20All&collection_id=68132&color=696969&context=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodypump%2Fseason%3A1&is_trailer=false&live=0&locale=en&playsinline=1&product_id=29964&referrer=https%3A%2F%2Fwatch.lesmillsondemand.com%2Fbodypump%2Fseason%3A1&sharing=1&title=0&vimeo=1" --referer https://watch.lesmillsondemand.com/fast-blast-challenge/videos/bodycombat-87-30-min
WARNING: [generic] The url doesn't specify the protocol, trying with http
[vhx:embed] 1925794: Downloading webpage
[vhx:embed] 1925794: Downloading JSON metadata
[vhx:embed] 1925794: Downloading akfire_interconnect_quic m3u8 information
[vhx:embed] 1925794: Downloading akfire_interconnect_quic m3u8 information
[vhx:embed] 1925794: Downloading akfire_interconnect_quic MPD information
[vhx:embed] 1925794: Downloading akfire_interconnect_quic MPD information
[info] 1925794: Downloading 1 format(s): http-1080p
[download] Resuming download at byte 1047552
[download] Destination: Untitled [1925794].mp4
[download]   0.2% of 924.43MiB at  3.20MiB/s ETA 04:48
ERROR: Interrupted by user
```

**Comment by spoonys** [comment]
Thank you, seems to work.

**Comment by dirkf** [comment]
That was indeed the issue with VHX embed videos from DropoutTV, no?

**Comment by brownkidnumber2** [comment]
Hi I'm trying a similar thing
youtube-dl.exe "https://embed.criterionchannel.com/videos/2353371?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1MDIzNDExMiwiZXhwIjoxNjcwNjQ0MTE5fQ.5giKLYJ06R45-ls6BQwo6AkpSdUdhAKK1yaqkN8kZ7o&autoplay=1&back=Cure&collection_id=95721&color=b9bcc7&context=https%3A%2F%2Fwww.criterionchannel.com%2Fcure&is_trailer=false&live=0&locale=en&playsinline=1&product_id=39621&referrer=https%3A%2F%2Fwww.criterionchannel.com%2Fcure%3F&sharing=1&title=0&vimeo=1" --referer https://www.criterionchannel.com/cure/videos/cure --no-check-certificate
but it is giving unsupported url

**Comment by brownkidnumber2** [comment]
> Hi I'm trying a similar thing youtube-dl.exe "https://embed.criterionchannel.com/videos/2353371?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1MDIzNDExMiwiZXhwIjoxNjcwNjQ0MTE5fQ.5giKLYJ06R45-ls6BQwo6AkpSdUdhAKK1yaqkN8kZ7o&autoplay=1&back=Cure&collection_id=95721&color=b9bcc7&context=https%3A%2F%2Fwww.criterionchannel.com%2Fcure&is_trailer=false&live=0&locale=en&playsinline=1&product_id=39621&referrer=https%3A%2F%2Fwww.criterionchannel.com%2Fcure%3F&sharing=1&title=0&vimeo=1" --referer https://www.criterionchannel.com/cure/videos/cure --no-check-certificate but it is giving unsupported url

oop I changed the url to embed.vhx.tv instead of the criterion and now it seems to be working (after installing ffmpeg)

**Comment by brownkidnumber2** [comment]
hi I am attempting to do: youtube-dl "https://embed.criterionchannel.com/videos/2353371?api=1&auth-user-token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1MDIzNDExMiwiZXhwIjoxNjcwNjUyNTcyfQ.iiObY2YNZfMWmyzLJM5nSiiL4g_rwFdjswsMFUZdmjk&autoplay=1&back=Cure&collection_id=95721&color=b9bcc7&context=https%3A%2F%2Fwww.criterionchannel.com%2Fcure&is_trailer=false&live=0&locale=en&playsinline=1&product_id=39621&referrer=&sharing=1&title=0&vimeo=1" --referer https://www.criterionchannel.com/cure/videos/cure --no-check-certificate 

but the site isn't supported so I use criterionchannel.vhx.tv but then there is a sslv3 handshake error
Is there anything else I can do?
