### ISSUE TITLE
Instragram stories - multiple exceptions

### ISSUE THREAD

**Issue by turkeyphant** [yt-dlp/yt-dlp#3002]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Description

Can't download instragram stories on lastest version

### Verbose log

```shell
yt-dlp https://www.instagram.com/stories/highlights/17941152226024129/ -vU
[debug] Command-line config: ['-i', '--format', '((571/272/402/337/315/313/401/336/308/400/271/335/303/299/399/137/248/334/302/298/398/247/136/333/244/135/397/332/243/134/396/331/242/133/395/330/160/394/278)[protocol!=http_dash_segments])+(bestaudio[acodec=opus]/bestaudio[protocol!=http_dash_segments])/best', 'https://www.instagram.com/stories/highlights/17941152226024129/', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.9.0 (CPython 64bit) - Linux-5.10.28-Unraid-x86_64-Intel-R-_Xeon-R-_CPU_E5-2650_v2_@_2.60GHz-with-glibc2.30
[debug] exe versions: ffmpeg N-54690-g682990a849-static
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [instagram:story] Extracting URL: https://www.instagram.com/stories/highlights/17941152226024129/
[instagram:story] 17941152226024129: Downloading JSON metadata
[instagram:story] 17941152226024129: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/common.py", line 1008, in _parse_json
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/common.py", line 617, in extract
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/instagram.py", line 651, in _real_extract
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/common.py", line 997, in _download_json
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/common.py", line 983, in _download_json_handle
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/common.py", line 1012, in _parse_json
yt_dlp.utils.ExtractorError: 17941152226024129: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1389, in wrapper
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [instagram:story] 17941152226024129: 17941152226024129: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/yt_dlp/__init__.py", line 864, in main
  File "/usr/local/bin/youtube-dl/yt_dlp/__init__.py", line 854, in _real_main
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 3254, in download
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 3227, in wrapper
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1380, in extract_info
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1407, in wrapper
  File "/usr/local/bin/youtube-dl/yt_dlp/utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
```

**Comment by pukkandan** [comment]
Related: https://github.com/yt-dlp/yt-dlp/issues/2473

**Comment by mehq** [comment]
I think reels API requires authentication. You should try with an account

**Comment by turkeyphant** [comment]
> I think reels API requires authentication. You should try with an account

Confirmed that using cookies it works.

```
[debug] Command-line config: ['-i', '--format', '((571/272/402/337/315/313/401/336/308/400/271/335/303/299/399/137/248/334/302/298/398/247/136/333/244/135/397/332/243/134/396/331/242/133/395/330/160/394/278)[protocol!=http_dash_segments])+(bestaudio[acodec=opus]/bestaudio[protocol!=http_dash_segments])/best', 'https://www.instagram.com/stories/highlights/17941152226024129/', '-vU', '--cookies', 'insta.txt']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.9.0 (CPython 64bit) - Linux-5.10.28-Unraid-x86_64-Intel-R-_Xeon-R-_CPU_E5-2650_v2_@_2.60GHz-with-glibc2.30
[debug] exe versions: ffmpeg N-54690-g682990a849-static
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [instagram:story] Extracting URL: https://www.instagram.com/stories/highlights/17941152226024129/
[instagram:story] 17941152226024129: Downloading JSON metadata
[instagram:story] 17941152226024129: Downloading JSON metadata
[instagram:story] 17941152226024129: Downloading user info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: QUERO ÁLCOOL!!
[instagram:story] playlist QUERO ÁLCOOL!!: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[info] Bg_3AoABOm_: Downloading 1 format(s): 2209878009031415-2
[debug] Invoking downloader on "https://scontent-man2-1.cdninstagram.com/v/t50.12441-16/29903639_155022511836498_7169897397533802496_n.mp4?efg=eyJxZV9ncm91cHMiOiJbXCJpZ19wcm9ncmVzc2l2ZV91cmxnZW4ucHJvZHVjdF90eXBlLnN0b3J5XCJdIn0&_nc_ht=scontent-man2-1.cdninstagram.com&_nc_cat=106&_nc_ohc=Ol8Nw6mlcL0AX_uQ930&edm=ANmP7GQBAAAA&ccb=7-4&oe=622C05BF&oh=00_AT-CDI_5waWl8OsqbGedjc1UUnNkOWCBqzuhpDPswpVQ5w&_nc_sid=276363"
[download] Destination: Story by gui_fer983 [Bg_3AoABOm_].mp4
[download] 100% of 1.23MiB in 00:00
[download] Finished downloading playlist: QUERO ÁLCOOL!!

```

So now the bug is incorrect error messaging.

**Comment by pukkandan** [comment]
Related: #2736

**Comment by bifa2** [comment]
I'm getting an error private **stories** too:

```
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
```

Running either:
`.\yt-dlp.exe "https://www.instagram.com/stories/username/" "--cookies-from-browser chrome"`
`.\yt-dlp.exe "https://www.instagram.com/stories/username/389748922343434892374/" "--cookies-from-browser chrome"`

... both result in:

```
[instagram:story] 389748922343434892374: Downloading JSON metadata
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1008, in _parse_json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\instagram.py", line 640, in _real_extract
  File "yt_dlp\extractor\common.py", line 997, in _download_json
  File "yt_dlp\extractor\common.py", line 983, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 1012, in _parse_json
yt_dlp.utils.ExtractorError: 389748922343434892374: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [instagram:story] 389748922343434892374: 389748922343434892374: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[26632] Failed to execute script '__main__' due to unhandled exception!
```

If I visit the URL directly in a browser, the page is rendered but asks if I want to view the story as my own account (I have a few different accounts, but no others are signed in).

**Comment by bifa2** [comment]
Actually, I'm getting this for highlights too.

**Comment by ahm750** [comment]
I can confirm that I'm facing the same issue, even when using cookies.

**Comment by HobbyistDev** [comment]
> I can confirm that I'm facing the same issue, even when using cookies.

Possible fix : #4074
