### ISSUE TITLE
Can't extract from sportdeutschland.tv

### ISSUE THREAD

**Issue by owenjoey** [yt-dlp/yt-dlp#3005]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Example URLs

https://sportdeutschland.tv/deutscherbadmintonverband/bwf-tour-1-runde-feld-1-yonex-gainward-german-open-2022-0

### Description

Can't extract from this link:

https://sportdeutschland.tv/deutscherbadmintonverband/bwf-tour-1-runde-feld-1-yonex-gainward-german-open-2022-0

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://sportdeutschland.tv/deutscherbadmintonverband/bwf-tour-1-runde-feld-1-yonex-gainward-german-open-2022-0', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2022-01-10-git-f37e66b393-full_build-www.gyan.dev (setts), ffprobe 2022-01-10-git-f37e66b393-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [SportDeutschland] Extracting URL: https://sportdeutschland.tv/deutscherbadmintonverband/bwf-tour-1-runde-feld-1-yonex-gainward-german-open-2022-0
[SportDeutschland] deutscherbadmintonverband/bwf-tour-1-runde-feld-1-yonex-gainward-german-open-2022-0: Downloading JSON metadata
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\sportdeutschland.py", line 47, in _real_extract
  File "yt_dlp\extractor\common.py", line 997, in _download_json
  File "yt_dlp\extractor\common.py", line 976, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template
properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [SportDeutschland] deutscherbadmintonverband/bwf-tour-1-runde-feld-1-yonex-gainward-german-open-2022-0: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[31380] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by HobbyistDev** [comment]
I think the api url changed. At my computer, the website give geo-block warning but the video is playing even without VPN.
I got the api url in https://api.sportdeutschland.tv/api/stateless/frontend/assets/deutscherbadmintonverband/bwf-tour-1-runde-feld-1-yonex-gainward-german-open-2022-0. In there, we can get video (likely the OP want, not sure though) from `[video][0][src]`.
In the context of the OP url, the media url i found is https://chess.dosbnewmedia.de//mediafiles/89052def9adf41c9b910a6abd23d7adb.smil

Here's the log of yt-dlp when this url given as input:
```
~\test_download>yt-dlp -v "https://chess.dosbnewmedia.de//mediafiles/89052def9adf41c9b910a6abd23d7adb.smil" --no-check-certificate --downloader native
[debug] Command-line config: ['-v', 'https://chess.dosbnewmedia.de//mediafiles/89052def9adf41c9b910a6abd23d7adb.smil', '--no-check-certificate', '--downloader', 'native']
[debug] Portable config "~\yt-dlp\yt-dlp.conf": ['-v', '--netrc-location', '~yt-dlp.netrc', '-f', 'bv+ba/b', '--compat-options', 'format-sort', '--embed-metadata', '--embed-subs', '--sub-langs', 'all', '--console-title', '--downloader', 'aria2c']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Compatibility options: format-sort
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://chess.dosbnewmedia.de//mediafiles/89052def9adf41c9b910a6abd23d7adb.smil
[generic] 89052def9adf41c9b910a6abd23d7adb: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 89052def9adf41c9b910a6abd23d7adb: Downloading webpage
[generic] 89052def9adf41c9b910a6abd23d7adb: Extracting information
[generic] 89052def9adf41c9b910a6abd23d7adb: Downloading m3u8 information
[debug] Identified a SMIL file
[debug] Sort order given by user: hasaud, lang, quality, tbr, filesize, vbr, height, width, proto, vext, abr, aext, fps, fs_approx, source, id
[debug] Formats sorted by: hasvid, ie_pref, hasaud, lang, quality, tbr, filesize, vbr, height, width, proto, vext, abr, aext, fps, fs_approx, source, id, res, hdr:12(7), vcodec:vp9.2(10), acodec, asr
[info] 89052def9adf41c9b910a6abd23d7adb: Downloading 1 format(s): hls-1
[debug] Invoking hlsnative downloader on "https://cloudvodstreamer4.dosbnewmedia.de/newhls/148054.json/index-v1-a1.m3u8"
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Total fragments: 4110
[download] Destination: 89052def9adf41c9b910a6abd23d7adb [89052def9adf41c9b910a6abd23d7adb].mp4
[debug] File locking is not supported. Proceeding without locking
[download]   0.0% of ~27.63GiB at  742.02KiB/s ETA 10:49:37 (frag 1/4110)
ERROR: Interrupted by user
```
I don't download this file on my computer though, but when i tried play it in ffplay or mpv, it works, so i assume it would be the same as yt-dlp
