### ISSUE TITLE
Invalid exit code when metadata parser fails

### ISSUE THREAD

**Issue by eexit** [yt-dlp/yt-dlp#3015]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi there,

While troubleshooting my command, I realized that yt-dlp is not returning a proper exit code when the metadata format is broken. Command returns 0 while it fails.

Offending arg is: `--parse-metadata', '%(artist|[re:jazz] feat. Lisa Bassenge)s:%(meta_artist)s`
It should be: `--parse-metadata', '%(artist|[re\:jazz] feat. Lisa Bassenge)s:%(meta_artist)s`

Am I missing something else that prevents proper exit code?
Thanks!

### Verbose log

```shell
> /opt/homebrew/bin/yt-dlp -vU --format bestaudio --extract-audio --audio-format best --abort-on-error --ignore-config --audio-quality 0 --no-mtime --cookies "./youtube.com_cookies.txt" --parse-metadata "%(artist|[re:jazz] feat. Lisa Bassenge)s:%(meta_artist)s" --embed-metadata --embed-thumbnail --output "./downloads/A3lefsXi1vI.%(ext)s" https://music.youtube.com/watch?v=A3lefsXi1vI&list=RDAMVMA3lefsXi1vI
[1] 33699

> [debug] Command-line config: ['-vU', '--format', 'bestaudio', '--extract-audio', '--audio-format', 'best', '--abort-on-error', '--ignore-config', '--audio-quality', '0', '--no-mtime', '--cookies', './youtube.com_cookies.txt', '--parse-metadata', '%(artist|[re:jazz] feat. Lisa Bassenge)s:%(meta_artist)s', '--embed-metadata', '--embed-thumbnail', '--output', './downloads/A3lefsXi1vI.%(ext)s', 'https://music.youtube.com/watch?v=A3lefsXi1vI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.10.2 (CPython 64bit) - macOS-12.2.1-arm64-64bit
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.2
yt-dlp is up to date (2022.03.08.2)
[debug] [youtube] Extracting URL: https://music.youtube.com/watch?v=A3lefsXi1vI
[youtube] A3lefsXi1vI: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] A3lefsXi1vI: Downloading android player API JSON
[youtube] A3lefsXi1vI: Downloading android music player API JSON
[youtube] A3lefsXi1vI: Downloading web music config
[youtube] A3lefsXi1vI: Downloading player 6d3a4914
[youtube] A3lefsXi1vI: Downloading web music player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
Traceback (most recent call last):
  File "/opt/homebrew/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2022.3.8.2', 'console_scripts', 'yt-dlp')())
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/__init__.py", line 864, in main
    _real_main(argv)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/__init__.py", line 854, in _real_main
    retcode = ydl.download(all_urls)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3254, in download
    self.__download_wrapper(self.extract_info)(
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3227, in wrapper
    res = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1380, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2543, in process_video_result
    info_dict, _ = self.pre_process(info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3362, in pre_process
    info = self.run_all_pps(key, info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3356, in run_all_pps
    info = self.run_pp(pp, info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3329, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/postprocessor/metadataparser.py", line 60, in run
    f(info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/postprocessor/metadataparser.py", line 65, in f
    data_to_parse = self._downloader.evaluate_outtmpl(template, info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1227, in evaluate_outtmpl
    return self.escape_outtmpl(outtmpl) % info_dict
ValueError: incomplete format key

[1]  + exit 1     /opt/homebrew/bin/yt-dlp -vU --format bestaudio --extract-audio --audio-forma

> echo $?
0
```

**Comment by pukkandan** [comment]
> [1]  + exit 1     /opt/homebrew/bin/yt-dlp -vU --format bestaudio --extract-audio --audio-forma

The exit code is correct. It does not reflect `$?` because you pushed the process to the background by not escaping the URL

**Comment by eexit** [comment]
Gotcha, thanks a lot!
