### ISSUE TITLE
No locks available on NFS filesystem

### ISSUE THREAD

**Issue by sanpii** [yt-dlp/yt-dlp#3022]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Since the last version, when I try to download a video on a NFS filesystem, I have an error.

I don’t have this error when I download the video on an ext4 filesystem, then moving it to the NFS FS with `mv`.

### Verbose log

```shell
$ yt-dlp -vU https://www.youtube.com/watch?v=BaW_jenozKc
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=BaW_jenozKc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.13-arch1-1-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: brotlicffi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BaW_jenozKc: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr3---sn-n4g-ouxs.googlevideo.com/videoplayback?expire=1646955035&ei=uzUqYtqnEMSXvdIPwZCeiAo&ip=77.201.194.164&id=o-AEOMSTRbnz2DoolXl4RvHVG2aZH_bUUqs2GWJlUAIhbZ&itag=248&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-n4g-ouxs%2Csn-n4g-jqbe6&ms=au%2Crdu&mv=m&mvi=3&pl=23&initcwndbps=1832500&vprv=1&mime=video%2Fwebm&gir=yes&clen=988479&dur=9.833&lmt=1544741703689523&mt=1646933097&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPzRbbfYO_7FNwXwBW2azGJr6IOVoyKSR4e8qTNWytvvAiA4hDzvK-gvGPe5r0Q7zYiM5tKa3zrXjmj_fIbAuvBLTw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgLOhih97SPFzdVoFQk0Td4-QF_B88fyd7aCkHOKTAwGQCIQCaQ-r5_PujKmshHctCBB2Rps0-R_8JsVNok6sGc4xP0g%3D%3D"
ERROR: unable to open for writing: [Errno 37] No locks available
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2169, in _lock_file
    fcntl.flock(f,
OSError: [Errno 37] No locks available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 277, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 220, in inner
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 237, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 678, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).open()
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2236, in open
    return self.__enter__()
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2209, in __enter__
    _lock_file(self.f, exclusive, self.block)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2176, in _lock_file
    fcntl.lockf(f,
OSError: [Errno 37] No locks available


[debug] Invoking downloader on "https://rr3---sn-n4g-ouxs.googlevideo.com/videoplayback?expire=1646955035&ei=uzUqYtqnEMSXvdIPwZCeiAo&ip=77.201.194.164&id=o-AEOMSTRbnz2DoolXl4RvHVG2aZH_bUUqs2GWJlUAIhbZ&itag=251&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-n4g-ouxs%2Csn-n4g-jqbe6&ms=au%2Crdu&mv=m&mvi=3&pl=23&initcwndbps=1832500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=142292&dur=9.841&lmt=1506055557712479&mt=1646933097&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOc-HOwi-iDH4fOJY7NTZdat-OI55SysvVtBne5HMbgRAiEAqCePlCDfEqdCCzJjOqYcCQZsCAUHGvcogRWSL5tBj1U%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgLOhih97SPFzdVoFQk0Td4-QF_B88fyd7aCkHOKTAwGQCIQCaQ-r5_PujKmshHctCBB2Rps0-R_8JsVNok6sGc4xP0g%3D%3D"
ERROR: unable to open for writing: [Errno 37] No locks available
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2169, in _lock_file
    fcntl.flock(f,
OSError: [Errno 37] No locks available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 277, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 220, in inner
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 237, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 678, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).open()
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2236, in open
    return self.__enter__()
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2209, in __enter__
    _lock_file(self.f, exclusive, self.block)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2176, in _lock_file
    fcntl.lockf(f,
OSError: [Errno 37] No locks available
```

**Comment by pukkandan** [comment]
@jakeogh

**Comment by Lesmiscore** [comment]
Disclaimer: I'm not here to add `cant-reproduce` label. It should be reproduced by anyone.

I also have a NFS mount which may help debugging, but it doesn't appear to reproduce. The backend (server-side filesystem) is btrfs.
```
$ yt-dlp 4WzR_G7NVqo -v --download-archive archive.txt
[debug] Command-line config: ['4WzR_G7NVqo', '-v', '--download-archive', 'archive.txt']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.9.10 (CPython 64bit) - Linux-5.13.0-30-generic-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg n4.4.1-3-ge16ff82624-20211127 (setts), ffprobe n4.4.1-3-ge16ff82624-20211127, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'archive.txt'
[debug] [youtube] Extracting URL: 4WzR_G7NVqo
[youtube] 4WzR_G7NVqo: Downloading webpage
[youtube] 4WzR_G7NVqo: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4WzR_G7NVqo: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr2---sn-nvoxu-ioqr.googlevideo.com/videoplayback?expire=1647014563&ei=Qx4rYuCIGfSQ1d8PiIuasA4&ip=118.238.237.85&id=o-ACx-PLqwpWiMUgcCbSI8uPXbqCQ3kMwO3mp7VjMH_pE3&itag=248&source=youtube&requiressl=yes&mh=HB&mm=31%2C29&mn=sn-nvoxu-ioqr%2Csn-ogul7nel&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=19&initcwndbps=2326250&vprv=1&mime=video%2Fwebm&gir=yes&clen=486982416&dur=2406.170&lmt=1642915060056522&mt=1646992610&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgY6Yfh0TxYTFqAAqHZ-4YFc-0cEQvrdVfhKxMqZmRwMwCIQD-d_yEYixir2rCNxmOH5KofWy7BqhhRzZRWzH2hikLEg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIZCpuz-ISFdwG_YDKpyjgc_bkpO7lpx8O_TjUf-3OmWAiEA1JzHuBPKH8xkS7XFmlonvBIEZ5SXzSOCqNHLIb0_Sh0%3D"
[download] Destination: 【大阪→九州】安すぎるフェリーの相部屋で12時間の移動をした結果... [4WzR_G7NVqo].f248.webm
[download] 100% of 464.42MiB in 02:00
[debug] Invoking downloader on "https://rr2---sn-nvoxu-ioqr.googlevideo.com/videoplayback?expire=1647014563&ei=Qx4rYuCIGfSQ1d8PiIuasA4&ip=118.238.237.85&id=o-ACx-PLqwpWiMUgcCbSI8uPXbqCQ3kMwO3mp7VjMH_pE3&itag=251&source=youtube&requiressl=yes&mh=HB&mm=31%2C29&mn=sn-nvoxu-ioqr%2Csn-ogul7nel&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=19&initcwndbps=2326250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=33253958&dur=2406.201&lmt=1642909935106609&mt=1646992610&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgNdyHJ3C2MZD9sYc2ZZ1OVFSDmJ6pajcJgldCXDWEjccCIQDnSjZ0W-NDvY8DFfMDlT8kxgmjkMI70-67QbDuJKqXmA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIZCpuz-ISFdwG_YDKpyjgc_bkpO7lpx8O_TjUf-3OmWAiEA1JzHuBPKH8xkS7XFmlonvBIEZ5SXzSOCqNHLIb0_Sh0%3D"
[download] Destination: 【大阪→九州】安すぎるフェリーの相部屋で12時間の移動をした結果... [4WzR_G7NVqo].f251.webm
[download] 100% of 31.71MiB in 00:16
[Merger] Merging formats into "【大阪→九州】安すぎるフェリーの相部屋で12時間の移動をした結果... [4WzR_G7NVqo].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:【大阪→九州】安すぎるフェリーの相部屋で12時間の移動をした結果... [4WzR_G7NVqo].f248.webm' -i 'file:【大阪→九州】安すぎるフェリーの相部屋で12時間の移動をした結果... [4WzR_G7NVqo].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:【大阪→九州】安すぎるフェリーの相部屋で12時間の移動をした結果... [4WzR_G7NVqo].temp.webm'
Deleting original file 【大阪→九州】安すぎるフェリーの相部屋で12時間の移動をした結果... [4WzR_G7NVqo].f251.webm (pass -k to keep)
Deleting original file 【大阪→九州】安すぎるフェリーの相部屋で12時間の移動をした結果... [4WzR_G7NVqo].f248.webm (pass -k to keep)
[debug] Adding to archive: youtube 4WzR_G7NVqo
```

fstab entry (IP addresses are redacted):
```
xxx.xxx.xxx.xxx:/mnt/extra-storage/ /mnt/extra-storage/ nfs defaults,rw,_netdev 0 0 
```

`mount | grep nfs`:
```
xxx.xxx.xxx.xxx:/mnt/extra-storage on /mnt/extra-storage type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=xxx.xxx.xxx.xxx,local_lock=none,addr=xxx.xxx.xxx.xxx,_netdev)
```

**Comment by pukkandan** [comment]
Irrespective of whether we can reproduce, the solution is to catch and ignore (with warning?) OSError when locking. I had mentioned the possibility of this issue appearing in the previous related PR

**Comment by dirkf** [comment]
NFS should support locking, using the supplementary NLM protocol. According to the Web, this can fail if the mounted NFS volume is full or if the _rpc-statd_ daemon is not running (eg, not started by _systemd_) -- probably not an exhaustive list.

Regardless, locking failure still needs to be handled.

**Comment by mcarlton00** [comment]
fwiw, I'm seeing this as well.  The NFS side is mergerfs with ext4 filesystems.  Personally, I've had plenty of weird seemingly unrelated issues caused by file locking in the past so typically don't enable it on my NFS mounts unless absolutely required.

**Comment by sanpii** [comment]
I think I found the source of my problem:
> … type nfs (rw,relatime,vers=3,…)

https://docstore.mik.ua/orelly/networking_2ndEd/nfs/ch11_02.htm
> The NFS (Versions 2 and 3) protocol does not support file locking

**Comment by dirkf** [comment]
Which is why the daemon that handles NLM has to be running (as in your linked reference), as in my comment above.

**Comment by ohnonot** [comment]
I can confirm the above comment; a simple `systemctl start rpc-statd.service` was enough to solve the problem.
Make sure to enable the service if that helps.

**Comment by wolandmaster** [comment]
I have had the same problem since version 2022-03-08: 
```
$ ./yt-dlp-2022-03-08 -v https://www.youtube.com/watch?v=BaW_jenozKc
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=BaW_jenozKc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.03.08 [535eb16a4] (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-5.4.0-104-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: Crypto, secretstorage, sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BaW_jenozKc: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr1---sn-qpbpu8-9bte.googlevideo.com/videoplayback?expire=1647657747&ei=s-40YqrUCMuQv_IP-ryw-AY&ip=188.143.58.212&id=o-AITAKRO0Ihkwk9K4lchrrbnuh5A5Bi4PdRMoiiEXP-a3&itag=248&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-qpbpu8-9bte%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=22&initcwndbps=870000&vprv=1&mime=video%2Fwebm&gir=yes&clen=988479&dur=9.833&lmt=1544741703689523&mt=1647635818&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgawqXvoyotm0_puCCojagpdldybjAb9cav1EwsGujWvECIQDq1J9tPMoyptMCEC7EdNGuXjYs1Au8CxBa-70RQr_n2g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOAqZNz5aDEbmEPTkwaor1y9_xe7Mc01bv-VEGILdvlkAiEAzvCIm4ONJD-MGgiWTrqOYp_4xDTQWA3VOf7ZfPPRjPU%3D"
ERROR: unable to open for writing: [Errno 37] No locks available
Traceback (most recent call last):
  File "./yt-dlp-2022-03-08/yt_dlp/utils.py", line 2172, in _lock_file
    else fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 37] No locks available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./yt-dlp-2022-03-08/yt_dlp/downloader/http.py", line 278, in download
    ctx.tmpfilename, ctx.open_mode)
  File "./yt-dlp-2022-03-08/yt_dlp/downloader/common.py", line 220, in inner
    return func(self, *args, **kwargs)
  File "./yt-dlp-2022-03-08/yt_dlp/downloader/common.py", line 237, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "./yt-dlp-2022-03-08/yt_dlp/utils.py", line 678, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).open()
  File "./yt-dlp-2022-03-08/yt_dlp/utils.py", line 2236, in open
    return self.__enter__()
  File "./yt-dlp-2022-03-08/yt_dlp/utils.py", line 2209, in __enter__
    _lock_file(self.f, exclusive, self.block)
  File "./yt-dlp-2022-03-08/yt_dlp/utils.py", line 2179, in _lock_file
    else fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 37] No locks available


[debug] Invoking downloader on "https://rr1---sn-qpbpu8-9bte.googlevideo.com/videoplayback?expire=1647657747&ei=s-40YqrUCMuQv_IP-ryw-AY&ip=188.143.58.212&id=o-AITAKRO0Ihkwk9K4lchrrbnuh5A5Bi4PdRMoiiEXP-a3&itag=251&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-qpbpu8-9bte%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=22&initcwndbps=870000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=142292&dur=9.841&lmt=1506055557712479&mt=1647635818&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgD36CyiYPFDkOxZKpykPiE6SMy8Cv3MrrbCtJU27gBbwCIE1xENN_bjdmtpO7ezsEYIUUUOM0RMiI2B1onWBv7bXF&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOAqZNz5aDEbmEPTkwaor1y9_xe7Mc01bv-VEGILdvlkAiEAzvCIm4ONJD-MGgiWTrqOYp_4xDTQWA3VOf7ZfPPRjPU%3D"
ERROR: unable to open for writing: [Errno 37] No locks available
Traceback (most recent call last):
  File "./yt-dlp-2022-03-08/yt_dlp/utils.py", line 2172, in _lock_file
    else fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 37] No locks available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./yt-dlp-2022-03-08/yt_dlp/downloader/http.py", line 278, in download
    ctx.tmpfilename, ctx.open_mode)
  File "./yt-dlp-2022-03-08/yt_dlp/downloader/common.py", line 220, in inner
    return func(self, *args, **kwargs)
  File "./yt-dlp-2022-03-08/yt_dlp/downloader/common.py", line 237, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "./yt-dlp-2022-03-08/yt_dlp/utils.py", line 678, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).open()
  File "./yt-dlp-2022-03-08/yt_dlp/utils.py", line 2236, in open
    return self.__enter__()
  File "./yt-dlp-2022-03-08/yt_dlp/utils.py", line 2209, in __enter__
    _lock_file(self.f, exclusive, self.block)
  File "./yt-dlp-2022-03-08/yt_dlp/utils.py", line 2179, in _lock_file
    else fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 37] No locks available
```
However, the previous version (2022-02-04) is working well:
```
$ ./yt-dlp-2022-02-04 -v https://www.youtube.com/watch?v=BaW_jenozKc
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=BaW_jenozKc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-5.4.0-104-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: Crypto, secretstorage, sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BaW_jenozKc: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr1---sn-qpbpu8-9bte.googlevideo.com/videoplayback?expire=1647657986&ei=ou80Yt2hC9LV7gTFv47YAQ&ip=188.143.58.212&id=o-AF7EGxGXH35z292uQtiIsvHUTkUE1C5au1CSpGH9mq1e&itag=248&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-qpbpu8-9bte%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=1&pl=22&initcwndbps=857500&vprv=1&mime=video%2Fwebm&gir=yes&clen=988479&dur=9.833&lmt=1544741703689523&mt=1647636057&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALsmytkRfhPNGr9h4VgZ1asiapiGl4WHMvu9obZuHZ3CAiEA_rxJXJSUO3h1s_oC-AMh5nzSIYdCKmSRs-ImxFe_SGE%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgG8wcFqCN9vugd1vseqx8VBuJrM9bu3nUjlqNZpB_HDACIQCS4g77RCNQQdy8EwNDbs-UmRqg0f8bpd8MunDSj4f9ig%3D%3D"
[download] Destination: youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].f248.webm
[download] 100% of 965.31KiB in 00:00
[debug] Invoking downloader on "https://rr1---sn-qpbpu8-9bte.googlevideo.com/videoplayback?expire=1647657986&ei=ou80Yt2hC9LV7gTFv47YAQ&ip=188.143.58.212&id=o-AF7EGxGXH35z292uQtiIsvHUTkUE1C5au1CSpGH9mq1e&itag=251&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-qpbpu8-9bte%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=1&pl=22&initcwndbps=857500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=142292&dur=9.841&lmt=1506055557712479&mt=1647636057&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPHD_IaV_WJLP0c49V9nRS_9-smtLe80VYVG1bBJBOexAiAcPO2kl5BMEzp9dqe0zWu2Q1c05GnevRjF0RKd0NcLrw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgG8wcFqCN9vugd1vseqx8VBuJrM9bu3nUjlqNZpB_HDACIQCS4g77RCNQQdy8EwNDbs-UmRqg0f8bpd8MunDSj4f9ig%3D%3D"
[download] Destination: youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].f251.webm
[download] 100% of 138.96KiB in 00:00
[Merger] Merging formats into "youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:youtube-dl test video '"'"''"'"'_ä↭𝕐 [BaW_jenozKc].f248.webm' -i 'file:youtube-dl test video '"'"''"'"'_ä↭𝕐 [BaW_jenozKc].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:youtube-dl test video '"'"''"'"'_ä↭𝕐 [BaW_jenozKc].temp.webm'
Deleting original file youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].f251.webm (pass -k to keep)
Deleting original file youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].f248.webm (pass -k to keep)
```

**Comment by jakeogh** [comment]
I'm sorry, just found this. Github 101 here.

flock is unsupported on NFS, I'll send a pull to use lockf when necessary.

**Comment by noconnor29** [comment]
I have the same issue on yt-dlp-2022.3.8.2 (installed via pip) and downgraded to 2022.02.04 which works fine. Tried installing 2022.3.8.1 and 2022.3.8 and got the same 'no locks' error.

**Comment by jakeogh** [comment]
@noconnor29 this is a bug, and I intend to submit a patch soon. As a workaround, you may be able to enable NFS locking if you are using version 3+ and start the rpc-statd service.

**Comment by noconnor29** [comment]
Thanks for letting me know, wasn't quite sure from the exchange above. I was just checking the nfs version and it is 3. Since the Feb release is working I'll just stay there until the next set of release notes and go from there.

**Comment by Miusaky** [comment]
This still occurs for me on 2022.06.29. 

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2046, in _lock_file
    fcntl.flock(f, flags)
OSError: [Errno 37] No locks available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2022.6.29', 'console_scripts', 'yt-dlp')())
  File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 921, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 883, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 717, in __init__
    preload_download_archive(self.params.get('download_archive'))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 707, in preload_download_archive
    with locked_file(fn, 'r', encoding='utf-8') as archive_file:
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2092, in __enter__
    _lock_file(self.f, exclusive, self.block)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2050, in _lock_file
    fcntl.lockf(f, flags)
OSError: [Errno 37] No locks available
```

Was working for the first two downloads then this started occurring each attempt.

**Comment by pukkandan** [comment]
It is not the same issue. `--download-archive` does not work without locking

**Comment by Miusaky** [comment]
> It is not the same issue. `--download-archive` does not work without locking

Good to know.
