### ISSUE TITLE
SBS.com.au error

### ISSUE THREAD

**Issue by jaftest** [yt-dlp/yt-dlp#3025]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Keep getting data blocks error from entire season of show on SBS.com.au, first and second season downloaded fine.

Reoccurring error
ERROR: Did not get any data blocks
ERROR: unable to download video data: [Errno 2] No such file or directory: "Hamilton's Pharmacopeia S3 Ep1 - Synthetic Toad Venom Machine [7yFbtgk_cLOP].mp4.part-Frag##"

There's a thread that was open last year about movies and live streams on SBS, the solution does not work and only gives a website broken error.
Edit: using youtube-dl worked, but not yt-dlp.

### Verbose log

```shell
F:\SBS Rip>yt-dlp -vu --merge-output-format mp4 --write-subs https://www.sbs.com.au/ondemand/video/1864449603714/hamiltons-pharmacopeia-s3-ep1-synthetic-toad-venom-machine
[debug] Command-line config: ['-vu', '--merge-output-format', 'mp4', '--write-subs', 'https://www.sbs.com.au/ondemand/video/1864449603714/hamiltons-pharmacopeia-s3-ep1-synthetic-toad-venom-machine']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-11-03-git-08a501946f-full_build-www.gyan.dev (setts), ffprobe 2021-11-03-git-08a501946f-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: mp4
ERROR: [generic] 'mp4' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:mp4" ) to search YouTube
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 2686, in _real_extract
    raise ExtractorError(

[debug] [SBS] Extracting URL: https://www.sbs.com.au/ondemand/video/1864449603714/hamiltons-pharmacopeia-s3-ep1-synthetic-toad-venom-machine
[SBS] 1864449603714: Downloading JSON metadata
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/Bgtm9B/7yFbtgk_cLOP?feed=Video%20-%20Single&mbr=true&manifest=m3u&ord=3589695&policy=11929623&dfptag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.factual.sbs.com.au%2Fsec30htmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dpreroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1864449603714%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1864449603714&dfpmidtag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.factual.sbs.com.au%2Fsec30midrollhtmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dmidroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1864449603714%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1864449603714#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 7yFbtgk_cLOP: Downloading SMIL data
[ThePlatform] 7yFbtgk_cLOP: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 7yFbtgk_cLOP: Downloading JSON metadata
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7yFbtgk_cLOP: Downloading 1 format(s): hls-1363
[info] Writing video subtitles to: Hamilton's Pharmacopeia S3 Ep1 - Synthetic Toad Venom Machine [7yFbtgk_cLOP].en.srt
[debug] Invoking downloader on "http://videocdn.sbs.com.au/u/video/SBS/managed/closedcaptions/2021/03/11/690856.SRT"
[download] Destination: Hamilton's Pharmacopeia S3 Ep1 - Synthetic Toad Venom Machine [7yFbtgk_cLOP].en.srt
[download] 100% of 50.00KiB in 00:02
[debug] Invoking downloader on "https://sbsvodns-vh.akamaihd.net/i/svod/SBS/managed/2021/03/11/690856_,512,1500,1000,128,K.mp4.csmil/index_1_av.m3u8?set-akamai-hls-revision=5&id=AgABeHvalYdShf6eKmKnndnTfw1BARIRnVepbXRurq3q0%2fmHxA8qdLtvLN8VBObepqU7wyobKNIHqQ%3d%3d&hdntl=exp=1647046782~acl=%2fi%2fsvod%2fSBS%2fmanaged%2f2021%2f03%2f11%2f690856_*~data=hdntl~hmac=5f701029a8104a636fb6d71ba32bc24fef9d3dd2ce4139de3d029e7a06af86a4"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 423
[download] Destination: Hamilton's Pharmacopeia S3 Ep1 - Synthetic Toad Venom Machine [7yFbtgk_cLOP].mp4
[download]   3.3% of ~519.40MiB at 27.77KiB/s ETA 01:15:45 (frag 14/423)[download] Got server HTTP error: The read operation timed out. Retrying (attempt 1 of 10) ...
[download]   3.8% of ~519.21MiB at 226.76KiB/s ETA 01:26:14 (frag 15/423)[download] Got server HTTP error: Downloaded 1274632 bytes, expected 1279728 bytes. Retrying (attempt 1 of 10) ...


ERROR: Did not get any data blocks
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\__init__.py", line 864, in main
    _real_main(argv)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\__init__.py", line 854, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3254, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3227, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1380, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1581, in process_ie_result
    return self.process_ie_result(
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2638, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3128, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2835, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\hls.py", line 358, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\fragment.py", line 538, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\fragment.py", line 474, in download_fragment
    success, frag_content = self._download_fragment(ctx, fragment['url'], info_dict, headers)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\fragment.py", line 134, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\http.py", line 384, in real_download
    return download()
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\http.py", line 353, in download
    self.report_error('Did not get any data blocks')
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 177, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 939, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 868, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: unable to download video data: [Errno 2] No such file or directory: "Hamilton's Pharmacopeia S3 Ep1 - Synthetic Toad Venom Machine [7yFbtgk_cLOP].mp4.part-Frag16"
Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3128, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2835, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\hls.py", line 358, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\fragment.py", line 538, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\fragment.py", line 474, in download_fragment
    success, frag_content = self._download_fragment(ctx, fragment['url'], info_dict, headers)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\fragment.py", line 141, in _download_fragment
    return True, self._read_fragment(ctx)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\fragment.py", line 148, in _read_fragment
    down, frag_sanitized = self.sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 220, in inner
    return func(self, *args, **kwargs)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 237, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\utils.py", line 678, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).open()
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\utils.py", line 2202, in __init__
    self.f = io.open(filename, mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: "Hamilton's Pharmacopeia S3 Ep1 - Synthetic Toad Venom Machine [7yFbtgk_cLOP].mp4.part-Frag16"
```

**Comment by pukkandan** [comment]
For devs: Only available in Australia

**Comment by pukkandan** [comment]
It should have been `-vU`, not `-vu`. Doesn't really matter for this issue, but just fyi

**Comment by section83** [comment]
Tested with 2022.11.11. No errors.

> ~ % yt-dlp -v "https://www.sbs.com.au/ondemand/video/1864449603714/hamiltons-pharmacopeia-s3-ep1-synthetic-toad-venom-machine"
[debug] Command-line config: ['-v', 'https://www.sbs.com.au/ondemand/video/1864449603714/hamiltons-pharmacopeia-s3-ep1-synthetic-toad-venom-machine']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (darwin_exe)
[debug] Python 3.8.9 (CPython arm64 64bit) - macOS-13.0.1-arm64-arm-64bit (LibreSSL 2.8.3)
[debug] exe versions: ffmpeg 5.1.2-https (setts), ffprobe 5.1.2-https
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [SBS] Extracting URL: https://www.sbs.com.au/ondemand/video/1864449603714/hamiltons-pharmacopeia-s3-ep1-synthetic-toad-venom-machine
[SBS] 1864449603714: Downloading JSON metadata
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/Bgtm9B/7yFbtgk_cLOP?feed=Video%20-%20Single&mbr=true&manifest=m3u&ord=8042233&policy=11929623&dfptag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.factual.sbs.com.au%2Fsec30htmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dpreroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1864449603714%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1864449603714&dfpmidtag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.factual.sbs.com.au%2Fsec30midrollhtmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dmidroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1864449603714%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1864449603714#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 7yFbtgk_cLOP: Downloading SMIL data
[ThePlatform] 7yFbtgk_cLOP: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 7yFbtgk_cLOP: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7yFbtgk_cLOP: Downloading 1 format(s): hls-1363
[debug] Invoking hlsnative downloader on "https://sbsvodns-vh.akamaihd.net/i/svod/SBS/managed/2021/03/11/690856_,512,1500,1000,128,K.mp4.csmil/index_1_av.m3u8?set-akamai-hls-revision=5&id=AgCfxKNZe%2f2UJhs9fGMfkiNcNyv2fzpSPceA4sExTVO4G4h3XQcAF6mVGJRqyDEewbJ4tYCxbK5Q8A%3d%3d&hdntl=exp=1669172891~acl=%2fi%2fsvod%2fSBS%2fmanaged%2f2021%2f03%2f11%2f690856_*~data=hdntl~hmac=26eb4c02877779a9269a12ef2c86df315f32ffcca4ac2f22955ab247abdf0581"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 423
[download] Destination: Hamilton's Pharmacopeia S3 Ep1 - Synthetic Toad Venom Machine [7yFbtgk_cLOP].mp4
[download]   1.5% of ~ 527.00MiB at    2.50MiB/s ETA 02:23 (frag 6/423)^C

**Comment by pukkandan** [comment]
There has been no relevant changes in code. The issue was probably transient. Pls confirm @jaftest
