### ISSUE TITLE
DailyMotion failed to download, status 403: Forbidden

### ISSUE THREAD

**Issue by iqbalme** [yt-dlp/yt-dlp#3032]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Singapore

### Description

I cannot download dailymotion video, it always returns error.

### Verbose log

```shell
[dailymotion] Downloading Access Token
[dailymotion] x88gsas: Downloading media JSON metadata
[dailymotion] x88gsas: Downloading metadata JSON
[dailymotion] x88gsas: Downloading m3u8 information
WARNING: [dailymotion] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [dailymotion] x88gsas: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
root@lamp-ubuntu-s-1vcpu-1gb-sgp1-01:~# yt-dlp "https://dailymotion.com/video/x88gsas" --referer "https://dltools.xyz"
[dailymotion] Downloading Access Token
[dailymotion] x88gsas: Downloading media JSON metadata
[dailymotion] x88gsas: Downloading metadata JSON
[dailymotion] x88gsas: Downloading m3u8 information
WARNING: [dailymotion] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [dailymotion] x88gsas: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
root@lamp-ubuntu-s-1vcpu-1gb-sgp1-01:~# yt-dlp -U
Latest version: 2022.03.08.1, Current version: 2022.03.08.2
yt-dlp is up to date (2022.03.08.2)
root@lamp-ubuntu-s-1vcpu-1gb-sgp1-01:~# yt-dlp "https://dailymotion.com/video/x88gsas" --referer "https://dltools.xyz"
[dailymotion] Downloading Access Token
[dailymotion] x88gsas: Downloading media JSON metadata
[dailymotion] x88gsas: Downloading metadata JSON
[dailymotion] x88gsas: Downloading m3u8 information
WARNING: [dailymotion] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [dailymotion] x88gsas: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
root@lamp-ubuntu-s-1vcpu-1gb-sgp1-01:~# ^C
root@lamp-ubuntu-s-1vcpu-1gb-sgp1-01:~# yt-dlp "https://dailymotion.com/video/x88gsas" -v
[debug] Command-line config: ['https://dailymotion.com/video/x88gsas', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-104-generic-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [dailymotion] Extracting URL: https://dailymotion.com/video/x88gsas
[dailymotion] Downloading Access Token
[dailymotion] x88gsas: Downloading media JSON metadata
[dailymotion] x88gsas: Downloading metadata JSON
[dailymotion] x88gsas: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] x88gsas: Downloading 1 format(s): http-480-1
[debug] Invoking downloader on "https://proxy-22.sg1.dailymotion.com/sec(Pj8huTPntLvN5DLY1ppIsoq2pCKIRsy5I7hzAfJNzhOPTtCLBsHnvdFiGoWq6jhnIAQ_Uhn2_8wxntkYRBmqYA)/video/805/949/497949508_mp4_h264_aac_hq.mp4"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3128, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 2835, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/downloader/common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/downloader/http.py", line 383, in real_download
    establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/downloader/http.py", line 135, in establish_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3591, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by werid** [comment]
dailymotion blocks some known server hosts. 

from hetzner: 

```
weird@one:~/test % yt-dlp https://dailymotion.com/video/x88gsas
[dailymotion] Downloading Access Token
[dailymotion] x88gsas: Downloading media JSON metadata
[dailymotion] x88gsas: Downloading metadata JSON
[dailymotion] x88gsas: Downloading m3u8 information
[info] x88gsas: Downloading 1 format(s): http-480-1
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

from my home:

```
weird@vc65:~$ yt-dlp https://dailymotion.com/video/x88gsas
[dailymotion] Downloading Access Token
[dailymotion] x88gsas: Downloading media JSON metadata
[dailymotion] x88gsas: Downloading metadata JSON
[dailymotion] x88gsas: Downloading m3u8 information
[info] x88gsas: Downloading 1 format(s): http-480-1
[download] Destination: Liverpool 2-1 - Norwich City - Reds move into FA Cup quarter-finals [x88gsas].mp4
[download]   4.1% of 12.25MiB at  2.49MiB/s ETA 00:04^C
ERROR: Interrupted by user
```

**Comment by iqbalme** [comment]
so how to fix it from my side? I got that mentioned error.

**Comment by werid** [comment]
given that it's a server error due to them blocking you, not a yt-dlp error, your only option is to attempt to download from another IP-address, but at least in that regards you have multiple options:

1. use your own connection 
2. use a proxy
3. use a vpn
4. use another hosting service (can also be useful to setup a proxy on, once you find one that's not blocked)

**Comment by pukkandan** [comment]
Confirm whether you are able to view the same video in an incognito browser with same IP. If not, nothing we can do
