### ISSUE TITLE
403 error when trying to download m3u8 from WRC+

### ISSUE THREAD

**Issue by MJ26gaming** [yt-dlp/yt-dlp#3039]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

403 error when trying to download m3u8 from WRCplus. I am trying to download a stream of the WRC livestream of Rally Sweden. I keep getting a 403 error, even when I run the script with cookies. I ran it both in the python terminal and through the EXE. It can't send the "HEAD request"

### Verbose log

```shell
C:\Users\jackc\Downloads>yt-dlp --cookies-from-browser chrome -v "https://spottwrcplus.akamaized.net/hls/live/2030976/wrc_alllive_sweden/master-archive.m3u8?cid=29128&mid=&ecid=2025689&pid=5&dtid=1&ident=361408379320&hdnea=exp=1647020049~acl=/hls/live/2030976/wrc_alllive_sweden/*~hmac=e0711f1e3ff433df0e76fe7051beb14ac944b6a6873ff56e7d7bc030670f9390&startTime=1645779300&endTime=1645782060&partnerid=1&content=1259569&path=2030976%2Fwrc_alllive_sweden%2Fmaster.m3u8"
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-v', 'https://spottwrcplus.akamaized.net/hls/live/2030976/wrc_alllive_sweden/master-archive.m3u8?cid=29128&mid=&ecid=2025689&pid=5&dtid=1&ident=361408379320&hdnea=exp=1647020049~acl=/hls/live/2030976/wrc_alllive_sweden/*~hmac=e0711f1e3ff433df0e76fe7051beb14ac944b6a6873ff56e7d7bc030670f9390&startTime=1645779300&endTime=1645782060&partnerid=1&content=1259569&path=2030976%2Fwrc_alllive_sweden%2Fmaster.m3u8']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\jackc\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[Cookies] Extracted 751 cookies from chrome
[debug] cookie version breakdown: {'v10': 751, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://spottwrcplus.akamaized.net/hls/live/2030976/wrc_alllive_sweden/master-archive.m3u8?cid=29128&mid=&ecid=2025689&pid=5&dtid=1&ident=361408379320&hdnea=exp=1647020049~acl=/hls/live/2030976/wrc_alllive_sweden/*~hmac=e0711f1e3ff433df0e76fe7051beb14ac944b6a6873ff56e7d7bc030670f9390&startTime=1645779300&endTime=1645782060&partnerid=1&content=1259569&path=2030976%2Fwrc_alllive_sweden%2Fmaster.m3u8
[generic] *~hmac=e0711f1e3ff433df0e76fe7051beb14ac944b6a6873ff56e7d7bc030670f9390&startTime=1645779300&endTime=1645782060&partnerid=1&content=1259569&path=2030976/wrc_alllive_sweden/master: Requesting header
WARNING: [generic] Could not send HEAD request to https://spottwrcplus.akamaized.net/hls/live/2030976/wrc_alllive_sweden/master-archive.m3u8?cid=29128&mid=&ecid=2025689&pid=5&dtid=1&ident=361408379320&hdnea=exp=1647020049~acl=/hls/live/2030976/wrc_alllive_sweden/*~hmac=e0711f1e3ff433df0e76fe7051beb14ac944b6a6873ff56e7d7bc030670f9390&startTime=1645779300&endTime=1645782060&partnerid=1&content=1259569&path=2030976%2Fwrc_alllive_sweden%2Fmaster.m3u8: HTTP Error 403: Forbidden
[generic] *~hmac=e0711f1e3ff433df0e76fe7051beb14ac944b6a6873ff56e7d7bc030670f9390&startTime=1645779300&endTime=1645782060&partnerid=1&content=1259569&path=2030976/wrc_alllive_sweden/master: Downloading webpage
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 2716, in _real_extract
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[18584] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by pukkandan** [comment]
Can you open that URL in browser? If not, you are missing some headers/query. Nothing yt-dlp can do about it

**Comment by MJ26gaming** [comment]
Alright, good to know. What type of headers or queries would I be looking for? I'm not good with networking and such

**Comment by bashonly** [comment]
you'll probably need one or more of Origin, Cookie, or Authorization headers

you can use the network tab in Firefox dev tools to copy the http request for the m3u8 as a curl command which will have the same headers that your browser is sending with its request

**Comment by MJ26gaming** [comment]
Okay, so how do i insert that curl i copied into my yt-dlp command?

**Comment by bashonly** [comment]
you'll want to look at the headers (the arguments following the `-H` parameters) in the curl command line. 

e.g. if there is `-H "Origin: https://blahblahblah"` you can pass it to yt-dlp like:

`yt-dlp --add-header "Origin:https://blahblahblah"`

as per the yt-dlp manual you can use the `--add-header` option multiple times

`yt-dlp --add-header "Origin:https://blahblahblah" --add-header "Authorization:Bearer blahblahblah"` etc etc

this will probably require some trial and error, and the problem could even possibly be something else, such as the `Range` and icy metadata headers that ffmpeg sends with its requests by default
