### ISSUE TITLE
[Broken] svtplay.se (only some url:s)

### ISSUE THREAD

**Issue by dkv** [yt-dlp/yt-dlp#305]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ yt-dlp --verbose "https://www.svtplay.se/video/30869842/vetenskapens-varld/vetenskapens-varld-sasong-34-tradens-superkrafter?id=jbrNb3r"
[debug] Command-line config: ['--verbose', 'https://www.svtplay.se/video/30869842/vetenskapens-varld/vetenskapens-varld-sasong-34-tradens-superkrafter?id=jbrNb3r']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.22 (zip)
[debug] Python version 3.9.4 (CPython 64bit) - Linux-5.11.17-300.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[debug] Using fake IP 78.72.111.75 (SE) as X-Forwarded-For.
[SVTPlay] 30869842: Downloading webpage
[SVTPlay] jnDnWRW: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1059, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1080, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/svt.py", line 270, in _real_extract
    info_dict = self._extract_by_video_id(svt_id, webpage)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/svt.py", line 212, in _extract_by_video_id
    info_dict = self._extract_video(data, video_id)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/svt.py", line 53, in _extract_video
    self._sort_formats(formats)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1687, in _sort_formats
    raise ExtractorError('No video formats found')
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

## Description

The other episodes I've tried does indeed download without problems. This one does not though.

**Comment by pukkandan** [comment]
closing due to inactivity
