### ISSUE TITLE
[BlockingIOError: [Errno 11] Resource temporarily unavailable] YouTube can't merge into mp4 

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#3061]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

I'm expecting this command to download the best quality video into a `.mp4` file 

This results in 3 files:
- YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].f248.webm
- YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].f251.webm
- YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].temp.mp4
- YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].webp

Notes: 
- `yt-dlp --version` outputs `2022.03.08.2` insteat of `2022.03.08.1`
- I'm on Ubuntu 20.04 LTS (I've run the same command in MacOS and can confirm it works as I expected)
- File `download_configs.txt` is: 
```
--match-filter "!is_live & title~=vs & duration > 600"
--no-progress
--add-metadata
--merge-output-format mp4
--embed-thumbnail
```

### Verbose log

```shell
yt-dlp -i "https://www.youtube.com/watch?v=R7Rv643zh1s" --config-location download_configs.txt --verbose
[debug] Command-line config: ['-i', 'https://www.youtube.com/watch?v=R7Rv643zh1s', '--config-location', 'download_configs.txt', '--verbose']
[debug] | Config "download_configs.txt": ['--match-filter', '!is_live & title~=vs & duration > 600', '--no-progress', '--add-metadata', '--merge-output-format', 'mp4', '--embed-thumbnail']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.8.11 (CPython 64bit) - Linux-5.15.15-76051515-generic-x86_64-with-glibc2.17
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=R7Rv643zh1s
[youtube] R7Rv643zh1s: Downloading webpage
[youtube] R7Rv643zh1s: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] R7Rv643zh1s: Downloading 1 format(s): 248+251
Deleting existing file YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].webp
[info] Downloading video thumbnail 44 ...
[info] Writing video thumbnail 44 to: YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].webp
[debug] Invoking downloader on "https://rr8---sn-qpnugpc0uxa-tu1l.googlevideo.com/videoplayback?expire=1647223403&ei=C04uYpK-B4OPiwS03ZyACw&ip=216.58.16.107&id=o-APjMRSbi8O_Ht-HXWUE7g_Y6fc7Bxxw1nJM6W5hC03Ay&itag=248&source=youtube&requiressl=yes&mh=5d&mm=31%2C29&mn=sn-qpnugpc0uxa-tu1l%2Csn-tt1e7n7e&ms=au%2Crdu&mv=m&mvi=8&pl=17&gcr=ca&initcwndbps=1023750&vprv=1&mime=video%2Fwebm&gir=yes&clen=663192475&dur=4660.000&lmt=1647105128990791&mt=1647201422&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=7310224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgYPdXIcUNyYz_MFtYBctABB8zxubIzp8AhE-mvt-ChekCIHLvoNkvU7Ra9I8njGg-4VFGiGA74SW1WQqThuRR2qHn&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJZXcx21WmlZfS6Q34hTqOXRYlq09RaLW7MVkdBNq3Y-AiABUTz1AFJ16MQ_nSR6aQZmNMd5Ug0qWrQsH3ekoQ88Mw%3D%3D"
[download] Resuming download at byte 290634603
[download] Destination: YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].f248.webm
[download] Download completed
[debug] Invoking downloader on "https://rr8---sn-qpnugpc0uxa-tu1l.googlevideo.com/videoplayback?expire=1647223403&ei=C04uYpK-B4OPiwS03ZyACw&ip=216.58.16.107&id=o-APjMRSbi8O_Ht-HXWUE7g_Y6fc7Bxxw1nJM6W5hC03Ay&itag=251&source=youtube&requiressl=yes&mh=5d&mm=31%2C29&mn=sn-qpnugpc0uxa-tu1l%2Csn-tt1e7n7e&ms=au%2Crdu&mv=m&mvi=8&pl=17&gcr=ca&initcwndbps=1023750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=57822345&dur=4660.021&lmt=1647105063705863&mt=1647201422&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=7310224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAP2V5PaGMRcqPV6wS3abKaXw9qZDeHrEPWbv9qM-KDflAiEAr9nb3BHXnIj8zdpvGJd7V0tvotAfwolP8GSW3kbZGxY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJZXcx21WmlZfS6Q34hTqOXRYlq09RaLW7MVkdBNq3Y-AiABUTz1AFJ16MQ_nSR6aQZmNMd5Ug0qWrQsH3ekoQ88Mw%3D%3D"
[download] Destination: YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].f251.webm
[download] Download completed
[Merger] Merging formats into "YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].f248.webm' -i 'file:YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].temp.mp4'
[debug] ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'file:YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].f248.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 01:17:40.00, start: 0.000000, bitrate: 1138 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 01:17:40.02, start: -0.007000, bitrate: 99 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
[mp4 @ 0x5608667aaa00] track 1: codec frame size is not set
[mp4 @ 0x5608667aaa00] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3329, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 119, in wrapper
    return func(self, info)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 828, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 294, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 333, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

[Metadata] Adding metadata to "YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].mp4"
ERROR: [Errno 2] No such file or directory: 'YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].mp4'
Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2638, in process_video_result
    self.process_info(new_info)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3201, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3369, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3356, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3329, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 119, in wrapper
    return func(self, info)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 709, in run
    self.run_ffmpeg_multiple_files(
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 294, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 301, in real_run_ffmpeg
    oldest_mtime = min(
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 302, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path, _ in input_path_opts if path)
FileNotFoundError: [Errno 2] No such file or directory: 'YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].mp4'
```

**Comment by pukkandan** [comment]
There is no `BlockingIOError` in the provided log. The only issue is that you tried to put formats in mp4 that ffmpeg can't put in mp4 by default

> [mp4 @ 0x5608667aaa00] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature

I believe this is no longer experimental in newer ffmpeg versions, so updating is also an option

**Comment by Wilann** [comment]
Appologies for being inconsistent - I editted the verbose log because I ran it again and it came out with a new output 

This was the initial log:
```
yt-dlp -i "https://www.youtube.com/watch?v=R7Rv643zh1s" --config-location download_configs.txt --verbose
[debug] Command-line config: ['-i', 'https://www.youtube.com/watch?v=R7Rv643zh1s', '--config-location', 'download_configs.txt', '--verbose']
[debug] | Config "download_configs.txt": ['--match-filter', '!is_live & title~=vs & duration > 600', '--no-progress', '--add-metadata', '--merge-output-format', 'mp4', '--embed-thumbnail']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.8.11 (CPython 64bit) - Linux-5.15.15-76051515-generic-x86_64-with-glibc2.17
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=R7Rv643zh1s
[youtube] R7Rv643zh1s: Downloading webpage
[youtube] R7Rv643zh1s: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] R7Rv643zh1s: Downloading 1 format(s): 248+251
Deleting existing file YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].webp
[info] Downloading video thumbnail 44 ...
[info] Writing video thumbnail 44 to: YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].webp
[debug] Invoking downloader on "https://rr8---sn-qpnugpc0uxa-tu1l.googlevideo.com/videoplayback?expire=1647222203&ei=W0kuYonVMZigir4P4JCfmAc&ip=216.58.16.107&id=o-AAe7P4aJYSExm8VDQWCIJNeqXuC9hUy2yPaA6iqmyz7A&itag=248&source=youtube&requiressl=yes&mh=5d&mm=31%2C29&mn=sn-qpnugpc0uxa-tu1l%2Csn-tt1e7n7e&ms=au%2Crdu&mv=m&mvi=8&pcm2cms=yes&pl=17&pcm2=yes&gcr=ca&initcwndbps=1046250&vprv=1&mime=video%2Fwebm&gir=yes&clen=663192475&dur=4660.000&lmt=1647105128990791&mt=1647200458&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=7310224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgApucsD3l2kai-IoigAiOFVThwGnAgMoZ9-a_D6qjQjUCIQDVQZGAq7SDMp5jVNVa8TlA_0e4mg9Ff7FPkYv20H4Wew%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKHMwuSvNwaD4mhbHkPEXjtlnFhaQro5wiLEh_4lr7LcAiBmpx9el9lAyLJULsECiX5ZOQ2zp7MVL9J26j2w_13-mQ%3D%3D"
[download] Resuming download at byte 586618445
ERROR: unable to open for writing: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 277, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 220, in inner
    return func(self, *args, **kwargs)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 237, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/utils.py", line 678, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).open()
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/utils.py", line 2236, in open
    return self.__enter__()
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/utils.py", line 2209, in __enter__
    _lock_file(self.f, exclusive, self.block)
  File "/home/wilsonchan/anaconda3/envs/AceOne-AI/lib/python3.8/site-packages/yt_dlp/utils.py", line 2169, in _lock_file
    fcntl.flock(f,
BlockingIOError: [Errno 11] Resource temporarily unavailable

[debug] Invoking downloader on "https://rr8---sn-qpnugpc0uxa-tu1l.googlevideo.com/videoplayback?expire=1647222203&ei=W0kuYonVMZigir4P4JCfmAc&ip=216.58.16.107&id=o-AAe7P4aJYSExm8VDQWCIJNeqXuC9hUy2yPaA6iqmyz7A&itag=251&source=youtube&requiressl=yes&mh=5d&mm=31%2C29&mn=sn-qpnugpc0uxa-tu1l%2Csn-tt1e7n7e&ms=au%2Crdu&mv=m&mvi=8&pcm2cms=yes&pl=17&pcm2=yes&gcr=ca&initcwndbps=1046250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=57822345&dur=4660.021&lmt=1647105063705863&mt=1647200458&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=7310224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKjsR3IJLkIKT0iB0HpEcZUupLpCeNm938fQWb32HvRbAiAxlJ286ENHzFLbLN-Yl-nF3tk4ZkJlx2z595iN1Dh3Uw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKHMwuSvNwaD4mhbHkPEXjtlnFhaQro5wiLEh_4lr7LcAiBmpx9el9lAyLJULsECiX5ZOQ2zp7MVL9J26j2w_13-mQ%3D%3D"
[download] YONEX GAINWARD German Open 2022 _ Viktor Axelsen (DEN) [1] vs Lakshya Sen (IND) _ SF [R7Rv643zh1s].f251.webm has already been downloaded
[download] Download completed
```

I tried updating ffmpeg with `sudo apt install ffmpeg` but it seems 4.2.4 is the newest version

**Comment by pukkandan** [comment]
Where you trying to run 2 yt-dlp instances on the same file?

> but it seems 4.2.4 is the newest version

No, ffmpeg 5 has been out for a bit. It's just apt being slow to update stuff

**Comment by Wilann** [comment]
Actually, I might've on accident now that I think of it

After debugging, I managed to download the best mp4 video by adding `--format "bestvideo+bestaudio[ext=m4a]/best"` to my config file

You pointed out the error message mentioned opus, and it seemed yt-dlp was picking the best audio as the one with opus format (?) - forcing it to use the best m4a format fixed the merging issue 

Thank you for pointing that out - it helped me figure out the issue in the end
