### ISSUE TITLE
File extends beyond end of segment - yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

### ISSUE THREAD

**Issue by turkeyphant** [yt-dlp/yt-dlp#3064]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Merging with ffmpeg fails for several videos. Some examples:

6BtI4E0iIzU
Y5BlBowdGYY 
f2kesmAO8VU
gd3fjchHGEI

### Verbose log

```shell
yt-dlp 6BtI4E0iIzU --verbose
[debug] Command-line config: ['6BtI4E0iIzU', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.2, ffprobe 4.1.1
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: 6BtI4E0iIzU
[youtube] 6BtI4E0iIzU: Downloading webpage
[youtube] 6BtI4E0iIzU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 6BtI4E0iIzU: Downloading 1 format(s): 247+251
[debug] Invoking downloader on "https://rr2---sn-8pgbpohxqp5-aigr.googlevideo.com/videoplayback?expire=1647240009&ei=6Y4uYqWQIZ-D1gKDsq-4Bw&ip=82.27.147.9&id=o-AIKz7vAYT-myenz3XjqiWZrCZO3j58I3BB-r_iwoXYyT&itag=247&source=youtube&requiressl=yes&mh=Nx&mm=31%2C26&mn=sn-8pgbpohxqp5-aigr%2Csn-5hne6nzs&ms=au%2Conr&mv=m&mvi=2&pl=22&initcwndbps=1308750&vprv=1&mime=video%2Fwebm&gir=yes&clen=45955189&dur=265.632&lmt=1544701524241871&mt=1647217979&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIo-AI0NKW0x6efM53QynMHn1tFloIrJGZJ3c_fc820IAiA2SZXxW9TItzx39XXLOBs6GZM4hG_ok1PA2zZ89_R__A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgPDkfqWE701i2_5Sgq2WXWF6D8cUauiv79xX_gHPy8u0CIQD0kv_69Kg_wNNGLdDFyQyfR2PvaZH3MyQjaflD3iOF9Q%3D%3D"
[download] Daniels PromPosal [6BtI4E0iIzU].f247.webm has already been downloaded
[download] 100% of 52.14MiB
[debug] Invoking downloader on "https://rr2---sn-8pgbpohxqp5-aigr.googlevideo.com/videoplayback?expire=1647240009&ei=6Y4uYqWQIZ-D1gKDsq-4Bw&ip=82.27.147.9&id=o-AIKz7vAYT-myenz3XjqiWZrCZO3j58I3BB-r_iwoXYyT&itag=251&source=youtube&requiressl=yes&mh=Nx&mm=31%2C26&mn=sn-8pgbpohxqp5-aigr%2Csn-5hne6nzs&ms=au%2Conr&mv=m&mvi=2&pl=22&initcwndbps=1308750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=3164819&dur=265.661&lmt=1544702331521488&mt=1647217979&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5411222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMj217H5QYk9mO4kZJK4Hg2jqlnQaS7xmJCGj9QqzPiXAiEA_ZksGnXEsDpFywm4sfah6DSwZctrm_hOGGzRZX5vFpI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgPDkfqWE701i2_5Sgq2WXWF6D8cUauiv79xX_gHPy8u0CIQD0kv_69Kg_wNNGLdDFyQyfR2PvaZH3MyQjaflD3iOF9Q%3D%3D"
[download] Daniels PromPosal [6BtI4E0iIzU].f251.webm has already been downloaded
[download] 100% of 3.02MiB
[Merger] Merging formats into "Daniels PromPosal [6BtI4E0iIzU].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Daniels PromPosal [6BtI4E0iIzU].f247.webm" -i "file:Daniels PromPosal [6BtI4E0iIzU].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Daniels PromPosal [6BtI4E0iIzU].temp.webm"
[debug] ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'file:Daniels PromPosal [6BtI4E0iIzU].f247.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:04:25.63, start: 0.000000, bitrate: 1646 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1280x720, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:Daniels PromPosal [6BtI4E0iIzU].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:04:25.66, start: -0.007000, bitrate: 95 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, webm, to 'file:Daniels PromPosal [6BtI4E0iIzU].temp.webm':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska,webm @ 0000019c2df8ae00] File extends beyond end of segment.72.8kbits/s speed=29.2x
[webm @ 0000019c2df90dc0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 265599 >= 217818
av_interleaved_write_frame(): Invalid argument
frame= 7962 fps=873 q=-1.0 Lsize=   47968kB time=00:04:25.60 bitrate=1479.5kbits/s speed=29.1x
video:44867kB audio:2998kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.214369%
Conversion failed!
ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3201, in process_info
  File "yt_dlp\YoutubeDL.py", line 3369, in post_process
  File "yt_dlp\YoutubeDL.py", line 3356, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3329, in run_pp
  File "yt_dlp\postprocessor\common.py", line 22, in run
  File "yt_dlp\postprocessor\common.py", line 119, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 828, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 294, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 333, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!


yt-dlp Y5BlBowdGYY --verbose
[debug] Command-line config: ['Y5BlBowdGYY', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.2, ffprobe 4.1.1
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: Y5BlBowdGYY
[youtube] Y5BlBowdGYY: Downloading webpage
[youtube] Y5BlBowdGYY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Y5BlBowdGYY: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr1---sn-8pgbpohxqp5-aigr.googlevideo.com/videoplayback?expire=1647240091&ei=O48uYsehI5b01wKYr7agDw&ip=82.27.147.9&id=o-AH9uve38v_NrLkqq4mtvO1Q5uUYg2odQBrIfCX3NSih8&itag=248&source=youtube&requiressl=yes&mh=XM&mm=31%2C26&mn=sn-8pgbpohxqp5-aigr%2Csn-5hne6nsd&ms=au%2Conr&mv=m&mvi=1&pl=22&pcm2=no&initcwndbps=1347500&vprv=1&mime=video%2Fwebm&gir=yes&clen=122956027&dur=498.131&lmt=1455077679564056&mt=1647218215&fvip=3&keepalive=yes&fexp=24001373%2C24007246&beids=23886208&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgWilwhQzVHKkrZ3GOeobHRxJy5ZPS4qmxVgBQz2N_YHsCIEUQnCCSpNg63D9FpfPh1hN_9XQuLFVd_X4h6BlNxcz2&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTHAtKYWVa-dYuApxX4twByNpV3FwppwWmoevNTucZKYCIHOHB44RJdocI6oEIOtyk0pb5o4ZHuXnWhtKzv_pttD1"
[download] Wedge Cull Card Control Tutorial [HD] - 52Kards [Y5BlBowdGYY].f248.webm has already been downloaded
[download] 100% of 125.48MiB
[debug] Invoking downloader on "https://rr1---sn-8pgbpohxqp5-aigr.googlevideo.com/videoplayback?expire=1647240091&ei=O48uYsehI5b01wKYr7agDw&ip=82.27.147.9&id=o-AH9uve38v_NrLkqq4mtvO1Q5uUYg2odQBrIfCX3NSih8&itag=251&source=youtube&requiressl=yes&mh=XM&mm=31%2C26&mn=sn-8pgbpohxqp5-aigr%2Csn-5hne6nsd&ms=au%2Conr&mv=m&mvi=1&pl=22&pcm2=no&initcwndbps=1347500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=7667426&dur=498.161&lmt=1455076964512616&mt=1647218215&fvip=3&keepalive=yes&fexp=24001373%2C24007246&beids=23886208&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgJO0lgc1-vCNHQ4K9QDOj6w4WsG5vw24xVD41uDaxprcCIQCFlFK7TfxsxKv1vqTxa-cChkflNflQLTtctoemL59ICQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTHAtKYWVa-dYuApxX4twByNpV3FwppwWmoevNTucZKYCIHOHB44RJdocI6oEIOtyk0pb5o4ZHuXnWhtKzv_pttD1"
[download] Wedge Cull Card Control Tutorial [HD] - 52Kards [Y5BlBowdGYY].f251.webm has already been downloaded
[download] 100% of 13.88MiB
[Merger] Merging formats into "Wedge Cull Card Control Tutorial [HD] - 52Kards [Y5BlBowdGYY].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Wedge Cull Card Control Tutorial [HD] - 52Kards [Y5BlBowdGYY].f248.webm" -i "file:Wedge Cull Card Control Tutorial [HD] - 52Kards [Y5BlBowdGYY].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Wedge Cull Card Control Tutorial [HD] - 52Kards [Y5BlBowdGYY].temp.webm"
[debug] ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'file:Wedge Cull Card Control Tutorial [HD] - 52Kards [Y5BlBowdGYY].f248.webm':
  Metadata:
    encoder         : google
  Duration: 00:08:18.13, start: 0.000000, bitrate: 2113 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:Wedge Cull Card Control Tutorial [HD] - 52Kards [Y5BlBowdGYY].f251.webm':
  Metadata:
    encoder         : google
  Duration: 00:08:18.16, start: -0.007000, bitrate: 233 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, webm, to 'file:Wedge Cull Card Control Tutorial [HD] - 52Kards [Y5BlBowdGYY].temp.webm':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska,webm @ 000002225a91ae00] File extends beyond end of segment.22.2kbits/s speed=15.6x
[matroska,webm @ 000002225a9edb00] File extends beyond end of segment.
[webm @ 000002225a9e6300] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 498131 >= 464464
av_interleaved_write_frame(): Invalid argument
frame=14931 fps=473 q=-1.0 Lsize=  127562kB time=00:08:18.14 bitrate=2097.8kbits/s speed=15.8x
video:120000kB audio:7316kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.193288%
Conversion failed!
ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3201, in process_info
  File "yt_dlp\YoutubeDL.py", line 3369, in post_process
  File "yt_dlp\YoutubeDL.py", line 3356, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3329, in run_pp
  File "yt_dlp\postprocessor\common.py", line 22, in run
  File "yt_dlp\postprocessor\common.py", line 119, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 828, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 294, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 333, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by NanaMizukiAnother7** [comment]
This issue looks like a duplicate of #871.
