### ISSUE TITLE
[instagram] Error when using cookies: "unable to extract username/video url"

### ISSUE THREAD

**Issue by tucomel** [yt-dlp/yt-dlp#3077]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

error while trying to download private or public instagram videos using cookies option

### Verbose log

```shell
arthur@blackpower Season 1 % yt-dlp "https://www.instagram.com/p/CaZ9f0JplRO/" --cookies ~/instagram.com_cookies.txt -vU
[debug] Command-line config: ['https://www.instagram.com/p/CaZ9f0JplRO/', '--cookies', '/Users/arthur/instagram.com_cookies.txt', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.10.2 (CPython 64bit) - macOS-11.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.2
yt-dlp is up to date (2022.03.08.2)
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CaZ9f0JplRO/
[Instagram] CaZ9f0JplRO: Downloading webpage
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CaZ9f0JplRO: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/extractor/instagram.py", line 421, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1307, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1201, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1192, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by tucomel** [comment]
any info?

**Comment by tucomel** [comment]
still not solved?

**Comment by pamplinas1** [comment]
I have a very similar issue. Is there a way to circumvent this?

**Comment by pukkandan** [comment]
It will be fixed when someone fixes it! Bombarding with duplicate issues/pointless comments is not helping

**Comment by pritam20ps05** [comment]
yeah same for me
### Description

Getting RegexNotFoundError with instagtam while downloading https://www.instagram.com/p/CeDdG5TOldD/ . Using cookies and verified that they are still valid.

### Verbose log

```shell
[Instagram] CeDdG5TOldD: Downloading webpage
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CeDdG5TOldD: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/instagram.py", line 415, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1340, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1235, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1226, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 668, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [Instagram] CeDdG5TOldD: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/bot.py", line 725, in dl_yt
    await in_dl_instance.downloadVideo(ctx, url, copt, usrcreds)
  File "/app/NeodiumUtils/download.py", line 203, in downloadVideo
    raise e
  File "/app/NeodiumUtils/download.py", line 195, in downloadVideo
    info = await ydl_async(url, ops, False)
  File "/app/NeodiumUtils/download.py", line 51, in ydl_async
    result = await loop.run_in_executor(pool, y_dl, url, ytops, d)
  File "/app/.heroku/python/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/NeodiumUtils/download.py", line 47, in y_dl
    info = ydl.extract_info(url, download=d)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1386, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1413, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 936, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 879, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [Instagram] CeDdG5TOldD: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by MinePlayersPE** [comment]
IG turned to using their mobile API for logged in users (`https://i.instagram.com/api/v1/media/MEDIA_ID/info/`, media ID can be gotten either from the IOS meta link tag `instagram://media?id=MEDIA_ID`, the ServerJS SSR JSON, or presumably by reversing the code used for the IOS meta link extractor), although the structure seems relatively the same as one used last time (https://github.com/yt-dlp/yt-dlp/commit/013322a95e396ab21c8febc3e560d8a177c87f4a)

**Comment by pritam20ps05** [comment]
Yea this problem is only with logged in users also the __a=1 get attribute which used to give a json dump now became __a=1&__d=dis but today only I checked it and now it does not return a json data but rather a obscure data. You can also check the [instagrapi](https://github.com/adw0rd/instagrapi) Python API wrapper for current IG graph API for the implementations. Instagrapi is totally operational and I guess it's built on the official api which makes it more resilient to minor changes to IG.

**Comment by Tatsh** [comment]
Instagram has removed the `sharedData` variable. You can get most of the same data from the `XIG_SHAREDDATA` value, which is necessary to make requests with the correct CSRF token, but this is not important for the `/info` call for videos. The username and everything else can come from the `/info` call.

A fixed extractor which uses Node to parse the JS: https://github.com/Tatsh/instagram-archiver/blob/master/instagram_archiver/extractor.py

This parses the video information from the `https://i.instagram.com/api/v1/media/{media_id}/info/` API and then converts it to the formerly used `shared_data` object format.

In order to get something merge-able, you need to parse the JavaScript with the parser in yt-dlp.

**Comment by pritam20ps05** [comment]
@Tatsh It seems like `https://i.instagram.com/api/v1/media/{media_id}/info/` always returns 400 bad request. Also it requires headers like `x-asbd-id` `x-csrftoken` `x-ig-app-id` `x-ig-www-claim`. see the code i used
```python
def _real_extract(self, url):
    video_id, url = self._match_valid_url(url).group('id', 'url')
    webpage, urlh = self._download_webpage_handle(url, video_id)
    if 'www.instagram.com/accounts/login' in urlh.geturl():
        self.report_warning(
            'Main webpage is locked behind the login page. '
            'Retrying with embed webpage (Note that some metadata might '
            'be missing)')
        webpage = self._download_webpage(
            f'https://www.instagram.com/p/{video_id}/embed/',
            video_id,
            note='Downloading embed webpage')

    media_id = self._search_regex(r'media\?id=(\S{19})', webpage, 'media id')
    print(media_id)
    info = self._download_json(
        ('https://i.instagram.com/api/v1/media/'
            f'{media_id}/info/'), video_id)['items'][0]
    username = traverse_obj(
        info,
        ('user', 'username'),
        expected_type=str,
    )
    formats = [{
        'url': x['url'],
        'width': x['width'],
        'height': x['height'],
    } for x in info['video_versions']]
    dash = info.get('video_dash_manifest')
    if dash:
        formats.extend(
            self._parse_mpd_formats(self._parse_xml(dash, video_id),
                                    mpd_id='dash'))
    self._sort_formats(formats)
    return {
        'id':
        video_id,
        'formats':
        formats,
        'title':
        f'Video by {username}',
        'description':
        traverse_obj(info, ('caption', 'text'), expected_type=str),
        'duration':
        float_or_none(info.get('video_duration')),
        'timestamp':
        traverse_obj(info, 'taken_at', expected_type=int_or_none),
        'uploader_id':
        str(traverse_obj(info, ('user', 'pk'), expected_type=int)),
        'uploader':
        traverse_obj(info, ('user', 'full_name'), expected_type=str),
        'channel':
        username,
        'like_count':
        traverse_obj(info, 'like_count', expected_type=int_or_none),
        'comment_count':
        traverse_obj(info, 'comment_count', expected_type=int_or_none),
        'thumbnails': [{
            'url': thumbnail['url'],
            'width': thumbnail.get('width'),
            'height': thumbnail.get('height'),
        } for thumbnail in info.get('image_versions2', {}).get(
            'candidates', []) if thumbnail.get('url')],
        'http_headers': {
            'Referer': 'https://www.instagram.com/',
        }
    }
```

**Comment by Tatsh** [comment]
Yes. I was wrong about saying it doesn't need the headers. I didn't realise my code was keeping them on.

Now your code just has to get comments back to match up to current functionality. 😸

**Comment by MinePlayersPE** [comment]
@pritam20ps05 Does `_extract_product` not work with the returned info?

**Comment by pritam20ps05** [comment]
Nah as its returning nothing but anyhow raises an exception midways. Still searching for better ways for extraction. BTW I found a function that converts short code like `B1LbfVPlwIA` to media_id like `2110901750722920960`.
```python
ENCODING_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
def decode(shortcode, alphabet=ENCODING_CHARS):
    """Covert a shortcode to a numeric value."""
    base = len(alphabet)
    strlen = len(shortcode)
    num = 0
    idx = 0
    for char in shortcode:
        power = strlen - (idx + 1)
        num += alphabet.index(char) * (base ** power)
        idx += 1
    return num
```
And for getting a shortcode from media_id
```python
ENCODING_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
def encode(num, alphabet=ENCODING_CHARS):
    """Covert a numeric value to a shortcode."""
    num = int(num)
    if num == 0:
        return alphabet[0]
    arr = []
    base = len(alphabet)
    while num:
        rem = num % base
        num //= base
        arr.append(alphabet[rem])
    arr.reverse()
    return "".join(arr)
```

**Comment by Tatsh** [comment]
Very Interesting find! I will definitely add this to my archiver.

In your extractor, you should be able to find the `csrf_token` necessary for the header. There are 2 of them on the page. The second one is usually the one you want (maybe both work?). For the `/info` call you should only need `x-csrftoken` and `x-ig-app-id` (`936619743392459`).

**Comment by Tatsh** [comment]
Regarding stories, I guess at some point in the past, Instagram returned JSON for the `stories/<username or highlights>/id` URL.

https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/instagram.py#L634=

This is where it fails now. It should just not do this step and skip to the `reels_media` API call. The user ID can be grabbed from that response just like `full_name` is. Same for the title of the reel.

**Comment by pritam20ps05** [comment]
It seems like `/info` call is the best thing to go with as the `x-asbd-id x-ig-app-id x-ig-www-claim` headers can be static and predefined. And for `x-csrftoken` we can get it from cookies. Have you guys found any better solution?

**Comment by Tatsh** [comment]
No that is fine. Who is going to make a PR?

**Comment by pritam20ps05** [comment]
IDK but has anyone writen the working extractor, atleast some part of it. For opening PR you both discuss @MinePlayersPE and @Tatsh

**Comment by Tatsh** [comment]
I have a working extractor and I plan to take out the parts involving Node. I have not yet made a working Story extractor but this should be easy.

**Comment by pritam20ps05** [comment]
Is the code public then please paste the link let me have a look.

**Comment by Tatsh** [comment]
https://github.com/Tatsh/instagram-archiver I am making a general purpose tool but it uses yt-dlp for videos. I thought it would be easier for now to just extend off yt-dlp to fix the Instagram extractor.

**Comment by SwapnilSoni1999** [comment]
Same issue though
