### ISSUE TITLE
Paramount+/CBS url formats have changed.

### ISSUE THREAD

**Issue by napgiver** [yt-dlp/yt-dlp#3096]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Example URLs

https://www.paramountplus.com/shows/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/

### Description

They have removed the series title and the episode title from the url...

Old url -> https://www.paramountplus.com/shows/star-trek-picard/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/star-trek-picard-penance/

New url -> https://www.paramountplus.com/shows/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/

The old version of the url still works. Adding _"star-trek-picard/"_ back in after _show/_ and _"star-trek-picard-penance/"_ at the end the the new url format works.

Both Paramound+ and CBS URLs are affected. I don't fill these thing out vary often. I hope I did this one correctly.

### Verbose log

```shell
New url format not working...

F:\zyt-dlp>yt-dlp.exe -vU "https://www.paramountplus.com/shows/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/" -F
[debug] Command-line config: ['-vU', 'https://www.paramountplus.com/shows/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2022-02-14-git-59c647bcf3-full_build-www.gyan.dev (setts), ffprobe 2022-02-14-git-59c647bcf3-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://www.paramountplus.com/shows/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/
[generic] k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl: Downloading webpage
[generic] k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.paramountplus.com/shows/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.paramountplus.com/shows/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/

================================================================================

   Old url format still works after editing to add the series title and episode title back into the url...

F:\zyt-dlp>yt-dlp.exe -vU "https://www.paramountplus.com/shows/star-trek-picard/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/star-trek-picard-penance/" -F
[debug] Command-line config: ['-vU', 'https://www.paramountplus.com/shows/star-trek-picard/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/star-trek-picard-penance/', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2022-02-14-git-59c647bcf3-full_build-www.gyan.dev (setts), ffprobe 2022-02-14-git-59c647bcf3-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/star-trek-picard/video/k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl/star-trek-picard-penance/
[ParamountPlus] k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl: Downloading JSON metadata
[ParamountPlus] k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl: Downloading JSON metadata
[ParamountPlus] k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl: Downloading DASH_CENC_PRECON SMIL data
[ParamountPlus] k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for k8ebkarVRm5YBcIfTi7lr_VIweb0wxpl:
ID       EXT RESOLUTION │   FILESIZE   TBR PROTO  │ VCODEC        VBR ACODEC    ABR
───────────────────────────────────────────────────────────────────────────────────
hls-93   mp4 audio only │ ~ 37.01MiB   93k m3u8_n │ audio only        mp4a.40.2 93k
hls-495  mp4 640x360    │ ~196.98MiB  495k m3u8_n │ avc1.640028  495k mp4a.40.2  0k
hls-834  mp4 768x432    │ ~331.89MiB  834k m3u8_n │ avc1.640028  834k mp4a.40.2  0k
hls-1603 mp4 960x540    │ ~637.91MiB 1603k m3u8_n │ avc1.640028 1603k mp4a.40.2  0k
hls-2194 mp4 1024x576   │ ~873.10MiB 2194k m3u8_n │ avc1.640028 2194k mp4a.40.2  0k
hls-3069 mp4 1280x720   │ ~  1.19GiB 3069k m3u8_n │ avc1.640028 3069k mp4a.40.2  0k
hls-4539 mp4 1920x1080  │ ~  1.76GiB 4539k m3u8_n │ avc1.640028 4539k mp4a.40.2  0k
```

**Comment by covertspartan** [comment]
This can be fixed by modifying the regex in the cbs extractor here: https://github.com/yt-dlp/yt-dlp/blob/e4b98809cffd285c41cf938706e54596d9ba54b2/yt_dlp/extractor/cbs.py#L76-L82

Removing the `[^/]+/` on line 80 fixed the issue for me.
