### ISSUE TITLE
[doodstream] support for all links

### ISSUE THREAD

**Issue by etmatrix** [yt-dlp/yt-dlp#3120]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Not all links are supported.
I maked a pull request for support domain .so and works, but some links does't work, for example this link 
https://dood.so/d/obx2lizzns385sm6gvbxwn56iu9maael

report always `Unable to extract token`

### Verbose log

```shell
./yt-dlp -vU https://dood.so/d/obx2lizzns385sm6gvbxwn56iu9maael
[debug] Command-line config: ['-vU', 'https://dood.so/d/obx2lizzns385sm6gvbxwn56iu9maael']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-12-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [DoodStream] Extracting URL: https://dood.so/d/obx2lizzns385sm6gvbxwn56iu9maael
[DoodStream] obx2lizzns385sm6gvbxwn56iu9maael: Downloading webpage
ERROR: [DoodStream] obx2lizzns385sm6gvbxwn56iu9maael: Unable to extract token; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/projects/yt-dlp/./yt-dlp/yt_dlp/extractor/common.py", line 637, in extract
    ie_result = self._real_extract(url)
  File "/home/projects/yt-dlp/./yt-dlp/yt_dlp/extractor/doodstream.py", line 52, in _real_extract
    token = self._html_search_regex(r'[?&]token=([a-z0-9]+)[&\']', webpage, 'token')
  File "/home/projects/yt-dlp/./yt-dlp/yt_dlp/extractor/common.py", line 1232, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/projects/yt-dlp/./yt-dlp/yt_dlp/extractor/common.py", line 1223, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by mradalbert** [comment]
```
yt-dlp -vU https://dood.ws/e/7ww50jzayzfv
[debug] Command-line config: ['-vU', 'https://dood.ws/e/7ww50jzayzfv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.28-1-MANJARO-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://dood.ws/e/7ww50jzayzfv
[generic] 7ww50jzayzfv: Requesting header
WARNING: [generic] Could not send HEAD request to https://dood.ws/e/7ww50jzayzfv: HTTP Error 403: Forbidden
[generic] 7ww50jzayzfv: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 7ww50jzayzfv: Extracting information
[debug] Looking for video embeds
WARNING: [generic] 7ww50jzayzfv: Failed to parse JSON Expecting ',' delimiter: line 1 column 36 (char 35)
ERROR: Unsupported URL: https://dood.ws/e/7ww50jzayzfv
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3985, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://dood.ws/e/7ww50jzayzfv

```

**Comment by bobwatcherx** [comment]
how to download dood video with yt-dlp
