### ISSUE TITLE
[BiliIntlSeries] ERROR: 'from'

### ISSUE THREAD

**Issue by Ciara-Aa** [yt-dlp/yt-dlp#3123]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Việt Nam

### Description

No Description

### Verbose log

```shell
yt-dlp -vU https://www.bilibili.tv/en/play/35692              [debug] Command-line config: ['-vU', 'https://www.bilibili.tv/en/play/35692']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.2 (CPython 64bit) - Linux-4.14.180-perf-gad2f9ca-aarch64-with-libc
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [BiliIntlSeries] Extracting URL: https://www.bilibili.tv/en/play/35692
[BiliIntlSeries] 35692: Downloading JSON metadata
[download] Downloading playlist: Katekyo Hitman Reborn!
[BiliIntlSeries] 35692: Downloading JSON metadata
[BiliIntlSeries] 361396: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 361396: Downloading JSON metadata
[BiliIntlSeries] 361396: Downloading subtitles for English
[BiliIntlSeries] 361396: Downloading subtitles for ภาษาไทย
[BiliIntlSeries] 361396: Downloading subtitles for Tiếng Việt
[BiliIntlSeries] 361396: Downloading subtitles for Bahasa Indonesia
[BiliIntlSeries] 361396: Downloading subtitles for 中文（简体）
[BiliIntlSeries] 361397: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 361397: Downloading JSON metadata
[BiliIntlSeries] 361397: Downloading subtitles for English
ERROR: 'from'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1387, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1696, in <lambda>
    lambda self, i: ie_entries[i - 1]
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2793, in __getitem__
    self.__cache.extend(itertools.islice(self.__iterable, n))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/bilibili.py", line 944, in _entries
    yield self._extract_ep_info(episode, episode_id)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/bilibili.py", line 820, in _extract_ep_info
    'subtitles': self._get_subtitles(ep_id),
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/bilibili.py", line 772, in _get_subtitles
    'data': self.json2srt(sub_data)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/bilibili.py", line 753, in json2srt
    data = '\n\n'.join(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/bilibili.py", line 754, in <genexpr>
    f'{i + 1}\n{srt_subtitles_timecode(line["from"])} --> {srt_subtitles_timecode(line["to"])}\n{line["content"]}'
KeyError: 'from'
```

**Comment by HobbyistDev** [comment]
I think this one make the problem:
https://github.com/yt-dlp/yt-dlp/blob/44a6fcff397e98b4aa7e3bb1da7425b3cca05a71/yt_dlp/extractor/bilibili.py#L784-L788

The json didn't always give `from` key when `content` exists. 
This is the sample of subtitle i get (i've been set print at code):
```
debug] Command-line config: ['-v', '-s', 'https://www.bilibili.tv/en/play/35692']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 11e1a6a25
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [BiliIntlSeries] Extracting URL: https://www.bilibili.tv/en/play/35692
[BiliIntlSeries] 35692: Downloading JSON metadata
[download] Downloading playlist: Katekyo Hitman Reborn!
[BiliIntlSeries] 35692: Downloading JSON metadata
[BiliIntlSeries] 361396: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 361396: Downloading subtitles list
[BiliIntlSeries] 361396: Downloading subtitles for English
0 {'from': 5.79, 'to': 9.96, 'location': 2, 'content': '<Italy - Island of Sicily>'}
... More subtitle_json ..
```
And then after hundred of lines
```
[BiliIntlSeries] 361397: Downloading subtitles for English
0 {'location': 2, 'content': '-'}
1 {'from': 91.47, 'to': 93.2, 'location': 2, 'content': 'Tsunayoshi Sawada.'}
```

**Comment by pukkandan** [comment]
So this should fix?
```diff
-          for i, line in enumerate(json['body']) if line.get('content')) 
+          for i, line in enumerate(traverse_obj(json, (
+              'body', lambda _, l: l['content'] and l['from'] and l['to']))))
```

**Comment by HobbyistDev** [comment]
> So this should fix?
> 
> ```diff
> -          for i, line in enumerate(json['body']) if line.get('content')) 
> +          for i, line in enumerate(traverse_obj(json, (
> +              'body', lambda _, l: l['content'] and l['from'] and l['to']))))
> ```

Yes, it works with your patch.
Here's the log (i didn't post full log as it too long) :
```
(python_proj2) D:\USER\Computer\python_proj\python_proj2\yt-dlp>python -m yt_dlp -v -s "https://www.bilibili.tv/en/play/35692"
[debug] Command-line config: ['-v', '-s', 'https://www.bilibili.tv/en/play/35692']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 6ebabad1b
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [BiliIntlSeries] Extracting URL: https://www.bilibili.tv/en/play/35692
[BiliIntlSeries] 35692: Downloading JSON metadata
[download] Downloading playlist: Katekyo Hitman Reborn!
[BiliIntlSeries] 35692: Downloading JSON metadata
[BiliIntlSeries] 361396: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 361396: Downloading subtitles list
[BiliIntlSeries] 361396: Downloading subtitles for English
[BiliIntlSeries] 361396: Downloading subtitles for ภาษาไทย
[BiliIntlSeries] 361396: Downloading subtitles for Tiếng Việt
[BiliIntlSeries] 361396: Downloading subtitles for Bahasa Indonesia
[BiliIntlSeries] 361396: Downloading subtitles for 中文（简体）
[BiliIntlSeries] 361397: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 361397: Downloading subtitles list
[BiliIntlSeries] 361397: Downloading subtitles for English
[BiliIntlSeries] 361397: Downloading subtitles for ภาษาไทย
[BiliIntlSeries] 361397: Downloading subtitles for Tiếng Việt
[BiliIntlSeries] 361397: Downloading subtitles for Bahasa Indonesia
[BiliIntlSeries] 361397: Downloading subtitles for 中文（简体）
[BiliIntlSeries] 361398: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 361398: Downloading subtitles list
[BiliIntlSeries] 361398: Downloading subtitles for English
[BiliIntlSeries] 361398: Downloading subtitles for ภาษาไทย
[BiliIntlSeries] 361398: Downloading subtitles for Tiếng Việt
[BiliIntlSeries] 361398: Downloading subtitles for Bahasa Indonesia
[BiliIntlSeries] 361398: Downloading subtitles for 中文（简体）
[BiliIntlSeries] 361399: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 361399: Downloading subtitles list
[BiliIntlSeries] 361399: Downloading subtitles for English
[BiliIntlSeries] 361399: Downloading subtitles for ภาษาไทย
[BiliIntlSeries] 361399: Downloading subtitles for Tiếng Việt
[BiliIntlSeries] 361399: Downloading subtitles for Bahasa Indonesia
[BiliIntlSeries] 361399: Downloading subtitles for 中文（简体）
[BiliIntlSeries] 361400: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
... and this is still going on
```
