### ISSUE TITLE
[Broken] hbo site won't work mpd 

### ISSUE THREAD

**Issue by apt42541** [yt-dlp/yt-dlp#313]
"yt-dlp --external-downloader aria2c --allow-unplayable-formats --verbose -f  --add-header "Referer: https://www.hbogo.co.th/" %video%+%audio% "%stream%" -o "encrypted.%%(ext)s""

ERROR: 'video_avc1_1+audio_THA_mp4a_1' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:video_avc1_1+audio_THA_mp4a_1" ) to search YouTube
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1059, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1080, in __extract_info
  File "yt_dlp\extractor\common.py", line 558, in extract
  File "yt_dlp\extractor\generic.py", line 2393, in _real_extract
yt_dlp.utils.ExtractorError: 'video_avc1_1+audio_THA_mp4a_1' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:video_avc1_1+audio_THA_mp4a_1" ) to search YouTube

[generic] THA_index: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] THA_index: Downloading webpage
[generic] THA_index: Extracting information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: Requested format is not available
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1059, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1096, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1128, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2033, in process_video_result
yt_dlp.utils.ExtractorError: Requested format is not available

**Comment by pukkandan** [comment]
1. Obey the issue template
2. Your command is wrong
3. You didnt post the vebose

Run `yt-dlp --allow-unplayable-formats --v --add-header "Referer: https://www.hbogo.co.th/" -F -- URL` and post the entire output in a new issue and DON'T skip the template
