### ISSUE TITLE
Postprocessing: Conversion failed!

### ISSUE THREAD

**Issue by Atulin** [yt-dlp/yt-dlp#3138]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Downloading [a video](https://www.youtube.com/watch?v=cI9fJMhGK0Q) fails with `Postprocessing: Conversion failed!` error, and results in two `.webm` files"
1. Video with the duration of 0.05, size 1.6 MB, with sound
2. Video with the correct duration of 57:52, size 1.0 GB, with **no sound**

### Verbose log

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=cI9fJMhGK0Q', '-vU']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 3.4, ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=cI9fJMhGK0Q
[youtube] cI9fJMhGK0Q: Downloading webpage
[youtube] cI9fJMhGK0Q: Downloading android player API JSON
[youtube] cI9fJMhGK0Q: Downloading MPD manifest
[youtube] cI9fJMhGK0Q: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] cI9fJMhGK0Q: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1647854185/ei/Ce43YpPmAYWs7QSA2K2IBQ/ip/178.43.217.138/id/708f5f24c8462b44/source/youtube/requiressl/yes/playback_host/rr2---sn-u2oxu-fgvl.googlevideo.com/mh/P3/mm/31%2C29/mn/sn-u2oxu-fgvl%2Csn-f5f7kn7e/ms/au%2Crdu/mv/m/mvi/2/pl/24/tx/24027686/txs/24027683%2C24027684%2C24027685%2C24027686%2C24067850/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/977500/vprv/1/mt/1647831643/fvip/1/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgWtPX3XBRExVuWdd5ZS0hrg4Vap5SzIhiPQrnShADBs4CIAG9WGBQjhwn5Sk4PdDux2c0uezHwml3UloppHQ0ZBMZ/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgXpM0GaffM9udSduvXO7K9ugM2mvBKx7nSKFCe0GIskYCIQDw91mlHrvXTIdEiV2tQ-da1s-08mIqygm5FJsjjZfPrQ%3D%3D"
[dashsegments] Total fragments: 735
[download] Destination: Tokyo 24-ku — episode 2 — Questions, Answers, Cartoon Villains [cI9fJMhGK0Q].f303.webm
[download] 100% of 973.99MiB in 00:36
[debug] Invoking downloader on "https://rr2---sn-u2oxu-fgvl.googlevideo.com/videoplayback?expire=1647854185&ei=Ce43Ys6XF8KF8gPd0r2YBw&ip=178.43.217.138&id=o-ALVMktWCX3MplllTCxYdhl4Ws_n2zOVmMKAfg62OnF0Y&itag=251&source=youtube&requiressl=yes&mh=P3&mm=31%2C29&mn=sn-u2oxu-fgvl%2Csn-f5f7lnl7&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=977500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=37941633&otfp=1&dur=3910.041&lmt=1642043249396935&mt=1647831643&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIjC12fVDLUVU-W1SWCkYeqUJbDWF8_FDf6ZlH__w79UAiEA9Sc4pjd-TNHrHamIyWdTk1NKEHBoBum3qcRbb_DXyBg%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgZSJ2zye9Rty5LHCY7_oOpoFbRoRgW6TFT_a0I7U6t8ACIQCY5_0QK2s9GXnojTtm5AhmGsu6lvqzhi8jIzLS35GbtA%3D%3D"
[download] Tokyo 24-ku — episode 2 — Questions, Answers, Cartoon Villains [cI9fJMhGK0Q].f251.webm has already been downloaded
[download] 100% of 36.18MiB
[Merger] Merging formats into "Tokyo 24-ku — episode 2 — Questions, Answers, Cartoon Villains [cI9fJMhGK0Q].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Tokyo 24-ku — episode 2 — Questions, Answers, Cartoon Villains [cI9fJMhGK0Q].f303.webm" -i "file:Tokyo 24-ku — episode 2 — Questions, Answers, Cartoon Villains [cI9fJMhGK0Q].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Tokyo 24-ku — episode 2 — Questions, Answers, Cartoon Villains [cI9fJMhGK0Q].temp.webm"
[debug] ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, matroska,webm, from 'file:Tokyo 24-ku — episode 2 — Questions, Answers, Cartoon Villains [cI9fJMhGK0Q].f303.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 734
                    : Segment-Durations-Ms: 5333,5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),533
                    :
                    :
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:Tokyo 24-ku — episode 2 — Questions, Answers, Cartoon Villains [cI9fJMhGK0Q].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 01:05:10.04, start: -0.007000, bitrate: 77 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, webm, to 'file:Tokyo 24-ku — episode 2 — Questions, Answers, Cartoon Villains [cI9fJMhGK0Q].temp.webm':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 734
                    : Segment-Durations-Ms: 5333,5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),533
                    :
                    :
    encoder         : Lavf57.83.100
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[webm @ 000001f028562080] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5350 >= 5333
av_interleaved_write_frame(): Invalid argument
frame=  387 fps=0.0 q=-1.0 Lsize=    1574kB time=00:00:05.36 bitrate=2405.7kbits/s speed= 499x
video:1537kB audio:67kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3201, in process_info
  File "yt_dlp\YoutubeDL.py", line 3369, in post_process
  File "yt_dlp\YoutubeDL.py", line 3356, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3329, in run_pp
  File "yt_dlp\postprocessor\common.py", line 22, in run
  File "yt_dlp\postprocessor\common.py", line 119, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 828, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 294, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 333, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by Atulin** [comment]
Curiously, I have YTDL version 2021.06.06 installed, and it produced a 1.4 GB `.mp4` file of the correct lenght, with sound and all.

**Comment by pukkandan** [comment]
See pinned issue!

**Comment by Atulin** [comment]
Ah, my bad, it seems like #871 is indeed the same issue. The issue dating back to September 2021 made me think it's already fixed, but alas.
