### ISSUE TITLE
[Extractor] Afreecatv.com support for new URL request

### ISSUE THREAD

**Issue by eviljust** [yt-dlp/yt-dlp#3151]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Singapore

### Example URLs

Old: https://vod.afreecatv.com/PLAYER/STATION/84689851
New: https://vod.afreecatv.com/player/84689851

### Description

Afreecatv updated their player URL from https://vod.afreecatv.com/PLAYER/STATION/xxxxxxxxxxx to https://vod.afreecatv.com/player/xxxxxxxxxxxx. Therefore when using the command "yt-dlp.exe --get-url https://vod.afreecatv.com/player/85299905", it will not work for the new URL.

### Verbose log

```shell
Working:
[debug] Command-line config: ['--verbose', '--get-url', 'https://vod.afreecatv.com/PLAYER/STATION/84689851']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n5.0-4-g911d7f167c-20220306 (setts), ffprobe n5.0-4-g911d7f167c-20220306
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [afreecatv] Extracting URL: https://vod.afreecatv.com/PLAYER/STATION/84689851
[afreecatv] 84689851: Downloading webpage
[afreecatv] 84689851: Downloading video info XML
[afreecatv] 84689851: Downloading m3u8 information
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 84689851: Downloading 1 format(s): hls-original
http://vod-normal-global-cdn-z02.afreecatv.com/v101/hls/save/afreeca/station/2022/0307/09/1646613620468637.smil/original/both/playlist.m3u8


Not working
[debug] Command-line config: ['--verbose', '--get-url', 'https://vod.afreecatv.com/player/84689851']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n5.0-4-g911d7f167c-20220306 (setts), ffprobe n5.0-4-g911d7f167c-20220306
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://vod.afreecatv.com/player/84689851
[generic] 84689851: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 84689851: Downloading webpage
[generic] 84689851: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://vod.afreecatv.com/player/84689851
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vod.afreecatv.com/player/84689851
```

**Comment by wlritchi** [comment]
Fixed by #3097, which is merged but not yet released.
