### ISSUE TITLE
[downloader/external] HttpieFD doesn't work

### ISSUE THREAD

**Issue by coletdjnz** [yt-dlp/yt-dlp#3154]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

reposting from discord for tracking

`--downloader httpie`,` --downloader http`, `--downloader /usr/bin/http` all don't work in yt-dlp

`--external-downloader httpie` works in youtube-dl

seems to be caused by https://github.com/yt-dlp/yt-dlp/commit/9e631877f8011a21967577c0044afca163010fe2 and/or https://github.com/yt-dlp/yt-dlp/commit/7f7de7f94dfeacb0eb78cb9487dfcaf5707da381

potentially related: https://github.com/yt-dlp/yt-dlp/issues/2330

### Verbose log

```shell
$ http --version
2.6.0

$ yt-dlp --downloader httpie spGxWRw4GHw -v                                              
[debug] Command-line config: ['--downloader', 'httpie', 'spGxWRw4GHw', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.25-1-MANJARO-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: spGxWRw4GHw
[youtube] spGxWRw4GHw: Downloading webpage
[youtube] spGxWRw4GHw: Downloading android player API JSON
[debug] Loading youtube-nsig.293baa5d from cache
[debug] [youtube] Decrypted nsig nTbej523zp4T0wDsl => dUi53r-7T1lcfw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] spGxWRw4GHw: Downloading 1 format(s): 315+251
[debug] Invoking downloader on "https://rr3---sn-8vq54voxo1-53az.googlevideo.com/videoplayback?REDACTED"
[download] Destination: 'Stay hydrated' is deep state propaganda [spGxWRw4GHw].f315.webm
[download]  41.5% of 47.95MiB at 37.43MiB/s ETA 00:00^C
ERROR: Interrupted by user

$ youtube-dl --external-downloader httpie spGxWRw4GHw -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--external-downloader', 'httpie', 'spGxWRw4GHw', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.2 (CPython) - Linux-5.15.25-1-MANJARO-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] spGxWRw4GHw: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://rr3---sn-8vq54voxo1-53az.googlevideo.com/videoplayback?REDACTED'
[download] Destination: 'Stay hydrated' is deep state propaganda-spGxWRw4GHw.f315.webm
[debug] http command line: http --download --output ''"'"'Stay hydrated'"'"' is deep state propaganda-spGxWRw4GHw.f315.webm.part' 'https://rr3---sn-8vq54voxo1-53az.googlevideo.com/videoplayback?REDACTED' 'User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.22 Safari/537.36' 'Accept-Charset:ISO-8859-1,utf-8;q=0.7,*;q=0.7' 'Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' 'Accept-Encoding:gzip, deflate' 'Accept-Language:en-us,en;q=0.5'
^C
ERROR: Interrupted by user

$ yt-dlp --downloader http spGxWRw4GHw -v
[debug] Command-line config: ['--downloader', 'http', 'spGxWRw4GHw', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.25-1-MANJARO-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: spGxWRw4GHw
[youtube] spGxWRw4GHw: Downloading webpage
[youtube] spGxWRw4GHw: Downloading android player API JSON
[debug] Loading youtube-nsig.293baa5d from cache
[debug] [youtube] Decrypted nsig 0OtbPDsrs-rye4wPn => 2oELSZyIOew1og
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] spGxWRw4GHw: Downloading 1 format(s): 315+251
ERROR: 'NoneType' object has no attribute 'can_download'
Traceback (most recent call last):
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1471, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1527, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2636, in process_video_result
    self.process_info(new_info)
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3062, in process_info
    fd = get_suitable_downloader(info_dict, self.params, to_stdout=temp_filename == '-')
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/downloader/__init__.py", line 16, in get_suitable_downloader
    downloaders = [_get_suitable_downloader(info_copy, proto, params, default) for proto in protocols]
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/downloader/__init__.py", line 16, in <listcomp>
    downloaders = [_get_suitable_downloader(info_copy, proto, params, default) for proto in protocols]
  File "/home/coletdev/.local/lib/python3.10/site-packages/yt_dlp/downloader/__init__.py", line 110, in _get_suitable_downloader
    if ed.can_download(info_dict, external_downloader):
AttributeError: 'NoneType' object has no attribute 'can_download'
```

**Comment by afterdelight** [comment]
is there any simple documentation and commands to download with yt-dlp?
