### ISSUE TITLE
bstation/biliintl/bilibili.tv

### ISSUE THREAD

**Issue by lynxnexy** [yt-dlp/yt-dlp#3157]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

HTTP Error 403: Forbidden

### Verbose log

```shell
yt-dlp -f 5+2  --write-subs --sub-langs "id" --cookies "/root/cookies/cookies.txt" -P "/mnt/sda1/Videos/Anime/Boruto.Naruto.Next.Generations/01-50" -o "%(title)s.%(ext)s" https://www.bilibili.tv/en/play/1005426/10226626
[BiliIntl] 10226626: Downloading webpage
[BiliIntl] 10226626: Downloading JSON metadata
[BiliIntl] 10226626: Downloading video formats
[BiliIntl] 10226626: Downloading JSON metadata
[BiliIntl] 10226626: Downloading subtitles for English
[BiliIntl] 10226626: Downloading subtitles for ภาษาไทย
[BiliIntl] 10226626: Downloading subtitles for Tiếng Việt
[BiliIntl] 10226626: Downloading subtitles for Bahasa Indonesia
[info] 10226626: Downloading 1 format(s): 5+2
Deleting existing file /mnt/sda1/Videos/Anime/Boruto.Naruto.Next.Generations/01-50/E1 - Boruto Uzumaki!.id.srt
[info] Writing video subtitles to: /mnt/sda1/Videos/Anime/Boruto.Naruto.Next.Generations/01-50/E1 - Boruto Uzumaki!.id.srt
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

**Comment by lynxnexy** [comment]
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntl] 10226758: Downloading JSON metadata
[BiliIntl] 10226758: Downloading subtitles for English
[BiliIntl] 10226758: Downloading subtitles for ภาษาไทย
[BiliIntl] 10226758: Downloading subtitles for Tiếng Việt
[BiliIntl] 10226758: Downloading subtitles for Bahasa Indonesia
[debug] Downloading subtitles: id
[info] 10226758: Downloading 1 format(s): 5+2
[info] Writing video subtitles to: /mnt/sda1/Videos/Anime/Boruto.Naruto.Next.Generations/01-50/E2 - The Hokage's Son!.id.srt
[debug] Invoking downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/aa/2v/m210907a225gkutrjdkexp1hqle52vaa-1-231210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1647992112&gen=playurlv2&os=akam&oi=1920814460&trid=8a4a8b24bbe443cbb235cd1c8926ab25i&platform=pc&upsig=2691e4391389195be9aecdc2cd6282d0&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1647992112~hmac=f810df37ae47449b02463ed957599277ca41deb8ca218f8d5475fabfe7ac9ba1&mid=1492158992&bvc=vod&nettype=0&orderid=0,2&logo=00000000"
[download] Destination: /mnt/sda1/Videos/Anime/Boruto.Naruto.Next.Generations/01-50/E2 - The Hokage's Son!.f5.mp4
[download] 100% of 41.30MiB in 00:47
[debug] Invoking downloader on "https://upos-sz-mirrorcosbstar1.bilivideo.com/iupxcodeboss/aa/2v/m210907a225gkutrjdkexp1hqle52vaa-1-2c1301000022.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1647992112&gen=playurlv2&os=cosbstar1bv&oi=1920814460&trid=8a4a8b24bbe443cbb235cd1c8926ab25i&platform=pc&upsig=31982ce2c850c77c5d15e40ec4eae114&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=1492158992&bvc=vod&nettype=0&orderid=0,2&logo=00000000"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3107, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2833, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/bin/yt-dlp/yt_dlp/downloader/common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/bin/yt-dlp/yt_dlp/downloader/http.py", line 378, in real_download
    establish_connection()
  File "/usr/bin/yt-dlp/yt_dlp/downloader/http.py", line 137, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3588, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
