### ISSUE TITLE
Site request: xala.cat

### ISSUE THREAD

**Issue by JoseAngelB** [yt-dlp/yt-dlp#3162]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Spain

### Example URLs

https://xala.cat/details/_6098449965001

### Description

The site has movies, sports, events... The only thing I found without login needed are the trailers (accounts are free anyway), and the structure is always the same.
I found a request the site makes to something like https://edge.api.brightcove.com/playback/v1/accounts/5779379807001/videos/6098449965001 where the response is a json object with all the data.

### Verbose log

```shell
[debug] Command-line config: ['https://xala.cat/details/_6098449965001', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-04-20-cacdac8, ffprobe git-2020-04-20-cacdac8
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://xala.cat/details/_6098449965001
[generic] _6098449965001: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] _6098449965001: Downloading webpage
[generic] _6098449965001: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://xala.cat/details/_6098449965001
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://xala.cat/details/_6098449965001
```

**Comment by doe1080** [comment]
XALA! is now [La Xarxa+](https://laxarxames.cat/home)
https://ca.wikipedia.org/wiki/La_Xarxa%2B
