### ISSUE TITLE
Problems downloading from BBC Iplayer.

### ISSUE THREAD

**Issue by BlueHippo73** [yt-dlp/yt-dlp#3186]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Description

I'm using a VPN to access the BBC Iplayer. Videos from the site will work in Firefox on every single UK location on said VPN.
However, when I go to use yt-dlp to download a video, all but one UK location won't work and returns either output 1 or 2.
The one UK location that does work will give outputs 3 or 4 sometimes before working. When it does finally work and I request a format to download, I sometimes get output 5. Frustratingly, when the download does start, it goes extremely slow, usually somewhere between 20 to 200kb a second and often just hangs doing nothing for several seconds or minutes before moving again or just stops randomly and I need to run the command again for the download to continue where it left off.
If anyone knows what the problem here is or can help, it would be greatly appreciated.

I hope I've formatted everything properly. The preview function only lets me preview the description field for some reason.

### Verbose log

Output 1
```
yt-dlp.exe -F https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard -vU
[debug] Command-line config: ['-F', 'https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-94421-gb3b7523feb, ffprobe N-94421-gb3b7523feb
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard
[bbc.co.uk] b070p5yw: Downloading video page
[bbc.co.uk] b070p5yw: Downloading playlist JSON
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\bbc.py", line 589, in _real_extract
  File "yt_dlp\extractor\bbc.py", line 460, in _download_playlist
  File "yt_dlp\extractor\common.py", line 997, in _download_json
  File "yt_dlp\extractor\common.py", line 976, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 502: Bad Gateway (caused by <HTTPError 502: 'Bad Gateway'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [bbc.co.uk] b070p5yw: Unable to download JSON metadata: HTTP Error 502: Bad Gateway (caused by <HTTPError 502: 'Bad Gateway'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[2128] Failed to execute script '__main__' due to unhandled exception!
```

Output 2
```
yt-dlp.exe -F https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard -vU
[debug] Command-line config: ['-F', 'https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-94421-gb3b7523feb, ffprobe N-94421-gb3b7523feb
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard
[bbc.co.uk] b070p5yw: Downloading video page
Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1524, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\bbc.py", line 553, in _real_extract
  File "yt_dlp\extractor\common.py", line 900, in _download_webpage
  File "yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [bbc.co.uk] b070p5yw: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[11808] Failed to execute script '__main__' due to unhandled exception!
```

Output 3
```
yt-dlp.exe -F https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard -vU
[debug] Command-line config: ['-F', 'https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-94421-gb3b7523feb, ffprobe N-94421-gb3b7523feb
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard
[bbc.co.uk] b070p5yw: Downloading video page
[bbc.co.uk] b070p5yw: Downloading playlist JSON
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1524, in https_open
  File "urllib\request.py", line 1358, in do_open
  File "http\client.py", line 1344, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 268, in _read_status
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\bbc.py", line 589, in _real_extract
  File "yt_dlp\extractor\bbc.py", line 460, in _download_playlist
  File "yt_dlp\extractor\common.py", line 997, in _download_json
  File "yt_dlp\extractor\common.py", line 976, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: The read operation timed out (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [bbc.co.uk] b070p5yw: Unable to download JSON metadata: The read operation timed out (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[18216] Failed to execute script '__main__' due to unhandled exception!
```

Output 4
```
yt-dlp.exe -F https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard -vU
[debug] Command-line config: ['-F', 'https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-94421-gb3b7523feb, ffprobe N-94421-gb3b7523feb
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard
[bbc.co.uk] b070p5yw: Downloading video page
[bbc.co.uk] b070p5yw: Downloading playlist JSON
Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
socket.timeout: _ssl.c:1114: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1524, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error _ssl.c:1114: The handshake operation timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\bbc.py", line 589, in _real_extract
  File "yt_dlp\extractor\bbc.py", line 460, in _download_playlist
  File "yt_dlp\extractor\common.py", line 997, in _download_json
  File "yt_dlp\extractor\common.py", line 976, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: <urlopen error _ssl.c:1114: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1114: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [bbc.co.uk] b070p5yw: Unable to download JSON metadata: <urlopen error _ssl.c:1114: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1114: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[17840] Failed to execute script '__main__' due to unhandled exception!
```

Output 5
```
yt-dlp.exe -f mf_cloudfront-5510-1  https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard -vU
[debug] Command-line config: ['-f', 'mf_cloudfront-5510-1', 'https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-94421-gb3b7523feb, ffprobe N-94421-gb3b7523feb
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/b070p5yw/earths-greatest-spectacles-2-svalbard
[bbc.co.uk] b070p5yw: Downloading video page
[bbc.co.uk] b070p5yw: Downloading playlist JSON
[bbc.co.uk] b070p5w2: Downloading media selection JSON
[bbc.co.uk] b070p5w2: Downloading MPD manifest
[bbc.co.uk] b070p5w2: Downloading MPD manifest
[bbc.co.uk] b070p5w2: Downloading MPD manifest
[bbc.co.uk] b070p5w2: Downloading MPD manifest
[bbc.co.uk] b070p5w2: Downloading MPD manifest
[bbc.co.uk] b070p5w2: Downloading MPD manifest
[bbc.co.uk] b070p5w2: Downloading m3u8 information
[bbc.co.uk] b070p5w2: Downloading m3u8 information
[bbc.co.uk] b070p5w2: Downloading m3u8 information
WARNING: [bbc.co.uk] Failed to download m3u8 information: timed out
[bbc.co.uk] b070p5w2: Downloading m3u8 information
[bbc.co.uk] b070p5w2: Downloading m3u8 information
WARNING: [bbc.co.uk] Failed to download m3u8 information: timed out
[bbc.co.uk] b070p5w2: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [bbc.co.uk] b070p5w2: Requested format is not available
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1473, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1529, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2621, in process_video_result
yt_dlp.utils.ExtractorError: [bbc.co.uk] b070p5w2: Requested format is not available
```

**Comment by dirkf** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/30757
