### ISSUE TITLE
Can't download best quality 480p video from YouTube

### ISSUE THREAD

**Issue by holygamer** [yt-dlp/yt-dlp#3199]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I don't know if this is a bug or not. Normally I download 720p or above content and it will download as VP9 or AVC and the picture quality looks the same as each other but at different filesizes. No problems there.

However with this 854 x 480p video, the downloaded VP9 video looks pixellated when playing it back in full screen in my MPC-HC media player, as does H264 if I try to download the video in that format instead. The YouTube video playing on YouTube doesn't look pixellated in full screen. How can I download it in that quality where it doesn't look pixellated?:

https://www.youtube.com/watch?v=hn1VxaMEjRU

### Verbose log

```shell
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
Paste the video link to download: https://www.youtube.com/watch?v=hn1VxaMEjRU
[debug] Command-line config: ['-vU', '-f', '(bestvideo[width>=1920]/bestvideo)+b
estaudio/best', '--embed-subs', '--sub-lang', 'en', '--write-auto-sub', '--write
-sub', '--convert-subs', 'srt', '--ignore-errors', '--write-description', '--wri
te-thumbnail', '--embed-thumbnail', '--merge-output-format', 'mkv', '--no-playli
st', '--output', 'L:/VideoSharingSites/0=Unsorted/%(upload_date)s  %(uploader)s
   %(title)s    %(view_count)s Views %(id)s UK YouTube %(height)sp %(vcodec)s %(
acodec)s FPS %(fps)s.%(ext)s', 'https://www.youtube.com/watch?v=hn1VxaMEjRU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-65018-gad91bf8 (needs_adtstoasc), ffprobe N-65018
-gad91bf8
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=hn1VxaMEjRU
[youtube] hn1VxaMEjRU: Downloading webpage
[youtube] hn1VxaMEjRU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:
vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source
, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr
, vext, aext, hasaud, id
[debug] Downloading subtitles: en
[info] hn1VxaMEjRU: Downloading 1 format(s): 244+251
[info] Writing video description to: L:\VideoSharingSites\0=Unsorted\20120207  r
ootsrockbelgium    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7
253768 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.description
[info] Writing video subtitles to: L:\VideoSharingSites\0=Unsorted\20120207  roo
tsrockbelgium    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    725
3768 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=hn1VxaME
jRU&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&cap
s=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1648283872&sparams=ip%2Cipbits%2Ce
xpire%2Cv%2Casr_langs%2Ccaps%2Cxoaf&signature=C4314303521A81D038CB42125B075118C8
B41AA9.20F2DE86F1EB0F973B191120398CD96F42049883&key=yt8&kind=asr&lang=en&fmt=vtt
"
[download] Destination: L:\VideoSharingSites\0=Unsorted\20120207  rootsrockbelgi
um    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 Views
hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.en.vtt
[download] 100% of 15.27KiB in 00:00
[info] Downloading video thumbnail 41 ...
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
[info] Downloading video thumbnail 40 ...
WARNING: Unable to download video thumbnail 40: HTTP Error 404: Not Found
[info] Downloading video thumbnail 39 ...
WARNING: Unable to download video thumbnail 39: HTTP Error 404: Not Found
[info] Downloading video thumbnail 38 ...
WARNING: Unable to download video thumbnail 38: HTTP Error 404: Not Found
[info] Downloading video thumbnail 37 ...
[info] Writing video thumbnail 37 to: L:\VideoSharingSites\0=Unsorted\20120207
rootsrockbelgium    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch
7253768 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.webp
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:L:\Video
SharingSites\0=Unsorted\20120207  rootsrockbelgium    'Are we the Baddies' Mitch
ell and Webb Funny Nazi Scetch    7253768 Views hn1VxaMEjRU UK YouTube 480p vp9
opus FPS 30.en.vtt" -f srt -movflags "+faststart" "file:L:\VideoSharingSites\0=U
nsorted\20120207  rootsrockbelgium    'Are we the Baddies' Mitchell and Webb Fun
ny Nazi Scetch    7253768 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.en.s
rt"
Deleting original file L:\VideoSharingSites\0=Unsorted\20120207  rootsrockbelgiu
m    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 Views h
n1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.en.vtt (pass -k to keep)
[debug] Invoking downloader on "https://rr2---sn-cu-ba5e.googlevideo.com/videopl
ayback?expire=1648280273&ei=cW4-YufXEtWJ6dsPh_SDwAY&ip=2a00%3A23c5%3A2c0a%3A4e01
%3Aa812%3A71ff%3A79f9%3Ae2a3&id=o-AIZGNBT2lmbqRh_3ibNcLPWaDqwNqbvcD5mTFk4nHeac&i
tag=244&source=youtube&requiressl=yes&mh=vD&mm=31%2C29&mn=sn-cu-ba5e%2Csn-cu-auo
s&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=41&initcwndbps=1813750&vprv=1&mime=video
%2Fwebm&gir=yes&clen=8616885&dur=168.602&lmt=1524841720814318&mt=1648258371&fvip
=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Ci
d%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ
8wRQIgeZJqGXyXA_Bh65Gs6PfjxD7birCBHK-01IKAN1pjMRwCIQDvJPlvfaiFFzENPdznGgCaomTorp
oCl2mij-zdCezPiA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cin
itcwndbps&lsig=AG3C_xAwRgIhAN01U-TgvAHQ2BEE0MAHun7Ipl0RwAvvfNOECfpau6g5AiEAj1B_1
cXgAZTnJIq1uyBGZgM3CHFmw2-D2cbrQVyXy10%3D"
[download] Destination: L:\VideoSharingSites\0=Unsorted\20120207  rootsrockbelgi
um    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 Views
hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.f244.webm
[download] 100% of 8.22MiB in 00:09
[debug] Invoking downloader on "https://rr2---sn-cu-ba5e.googlevideo.com/videopl
ayback?expire=1648280273&ei=cW4-YufXEtWJ6dsPh_SDwAY&ip=2a00%3A23c5%3A2c0a%3A4e01
%3Aa812%3A71ff%3A79f9%3Ae2a3&id=o-AIZGNBT2lmbqRh_3ibNcLPWaDqwNqbvcD5mTFk4nHeac&i
tag=251&source=youtube&requiressl=yes&mh=vD&mm=31%2C29&mn=sn-cu-ba5e%2Csn-cu-auo
s&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=41&initcwndbps=1813750&vprv=1&mime=audio
%2Fwebm&gir=yes&clen=2801572&dur=168.621&lmt=1524841350981797&mt=1648258371&fvip
=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Ci
d%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ
8wRQIgfnlmNw-5TMTVeBxl9tKPkp02UF65-xbaHMbfKD4UOdYCIQC2pFxLdeSpI6HKZgbcx6sEu1To01
0qmxrFaZDokcOfoA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cin
itcwndbps&lsig=AG3C_xAwRgIhAN01U-TgvAHQ2BEE0MAHun7Ipl0RwAvvfNOECfpau6g5AiEAj1B_1
cXgAZTnJIq1uyBGZgM3CHFmw2-D2cbrQVyXy10%3D"
[download] Destination: L:\VideoSharingSites\0=Unsorted\20120207  rootsrockbelgi
um    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 Views
hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.f251.webm
[download] 100% of 2.67MiB in 00:02
[Merger] Merging formats into "L:\VideoSharingSites\0=Unsorted\20120207  rootsro
ckbelgium    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768
 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:L:\Video
SharingSites\0=Unsorted\20120207  rootsrockbelgium    'Are we the Baddies' Mitch
ell and Webb Funny Nazi Scetch    7253768 Views hn1VxaMEjRU UK YouTube 480p vp9
opus FPS 30.f244.webm" -i "file:L:\VideoSharingSites\0=Unsorted\20120207  rootsr
ockbelgium    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    725376
8 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.f251.webm" -c copy -map "0:v
:0" -map "1:a:0" -movflags "+faststart" "file:L:\VideoSharingSites\0=Unsorted\20
120207  rootsrockbelgium    'Are we the Baddies' Mitchell and Webb Funny Nazi Sc
etch    7253768 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.temp.mkv"
Deleting original file L:\VideoSharingSites\0=Unsorted\20120207  rootsrockbelgiu
m    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 Views h
n1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.f251.webm (pass -k to keep)
Deleting original file L:\VideoSharingSites\0=Unsorted\20120207  rootsrockbelgiu
m    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 Views h
n1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.f244.webm (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "L:\VideoSharingSites\0=Unsorted\20120207
  rootsrockbelgium    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch
  7253768 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:L:\Video
SharingSites\0=Unsorted\20120207  rootsrockbelgium    'Are we the Baddies' Mitch
ell and Webb Funny Nazi Scetch    7253768 Views hn1VxaMEjRU UK YouTube 480p vp9
opus FPS 30.mkv" -i "file:L:\VideoSharingSites\0=Unsorted\20120207  rootsrockbel
gium    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 View
s hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.en.srt" -map 0 -dn -ignore_unknown
 -c copy -map "-0:s" -map "1:0" "-metadata:s:s:0" "language=eng" -movflags "+fas
tstart" "file:L:\VideoSharingSites\0=Unsorted\20120207  rootsrockbelgium    'Are
 we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 Views hn1VxaMEjR
U UK YouTube 480p vp9 opus FPS 30.temp.mkv"
[debug] ffmpeg version N-65018-gad91bf8 Copyright (c) 2000-2014 the FFmpeg devel
opers
  built on Jul 26 2014 22:09:15 with gcc 4.8.3 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-lib
modplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrw
b --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinge
r --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --en
able-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis
 --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-
libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
  libavutil      52. 92.101 / 52. 92.101
  libavcodec     55. 69.100 / 55. 69.100
  libavformat    55. 49.100 / 55. 49.100
  libavdevice    55. 13.102 / 55. 13.102
  libavfilter     4. 11.102 /  4. 11.102
  libswscale      2.  6.100 /  2.  6.100
  libswresample   0. 19.100 /  0. 19.100
  libpostproc    52.  3.100 / 52.  3.100
Unrecognized option 'ignore_unknown'.
Error splitting the argument list: Option not found
ERROR: Error splitting the argument list: Option not found
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3329, in run_pp
  File "yt_dlp\postprocessor\common.py", line 22, in run
  File "yt_dlp\postprocessor\common.py", line 119, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 661, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 294, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 333, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error splitting the argume
nt list: Option not found

[ThumbnailsConvertor] Converting thumbnail "L:\VideoSharingSites\0=Unsorted\2012
0207  rootsrockbelgium    'Are we the Baddies' Mitchell and Webb Funny Nazi Scet
ch    7253768 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -f image2 -patter
n_type none -i "file:L:\VideoSharingSites\0=Unsorted\20120207  rootsrockbelgium
   'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 Views hn1
VxaMEjRU UK YouTube 480p vp9 opus FPS 30.webp" -movflags "+faststart" "file:L:\V
ideoSharingSites\0=Unsorted\20120207  rootsrockbelgium    'Are we the Baddies' M
itchell and Webb Funny Nazi Scetch    7253768 Views hn1VxaMEjRU UK YouTube 480p
vp9 opus FPS 30.png"
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -p
rint_format json "file:L:\VideoSharingSites\0=Unsorted\20120207  rootsrockbelgiu
m    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 Views h
n1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.mkv"
[EmbedThumbnail] ffmpeg: Adding thumbnail to "L:\VideoSharingSites\0=Unsorted\20
120207  rootsrockbelgium    'Are we the Baddies' Mitchell and Webb Funny Nazi Sc
etch    7253768 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:L:\Video
SharingSites\0=Unsorted\20120207  rootsrockbelgium    'Are we the Baddies' Mitch
ell and Webb Funny Nazi Scetch    7253768 Views hn1VxaMEjRU UK YouTube 480p vp9
opus FPS 30.mkv" -map 0 -dn -ignore_unknown -c copy -attach "L:\VideoSharingSite
s\0=Unsorted\20120207  rootsrockbelgium    'Are we the Baddies' Mitchell and Web
b Funny Nazi Scetch    7253768 Views hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30
.png" "-metadata:s:2" "mimetype=image/png" "-metadata:s:2" "filename=cover.png"
-movflags "+faststart" "file:L:\VideoSharingSites\0=Unsorted\20120207  rootsrock
belgium    'Are we the Baddies' Mitchell and Webb Funny Nazi Scetch    7253768 V
iews hn1VxaMEjRU UK YouTube 480p vp9 opus FPS 30.temp.mkv"
[debug] ffmpeg version N-65018-gad91bf8 Copyright (c) 2000-2014 the FFmpeg devel
opers
  built on Jul 26 2014 22:09:15 with gcc 4.8.3 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-lib
modplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrw
b --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinge
r --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --en
able-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis
 --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-
libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
  libavutil      52. 92.101 / 52. 92.101
  libavcodec     55. 69.100 / 55. 69.100
  libavformat    55. 49.100 / 55. 49.100
  libavdevice    55. 13.102 / 55. 13.102
  libavfilter     4. 11.102 /  4. 11.102
  libswscale      2.  6.100 /  2.  6.100
  libswresample   0. 19.100 /  0. 19.100
  libpostproc    52.  3.100 / 52.  3.100
Unrecognized option 'ignore_unknown'.
Error splitting the argument list: Option not found
ERROR: Error splitting the argument list: Option not found
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3329, in run_pp
  File "yt_dlp\postprocessor\common.py", line 22, in run
  File "yt_dlp\postprocessor\common.py", line 119, in wrapper
  File "yt_dlp\postprocessor\embedthumbnail.py", line 125, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 340, in run_ffmpeg
  File "yt_dlp\postprocessor\ffmpeg.py", line 294, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 333, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error splitting the argume
nt list: Option not found

Press any key to continue . . .
```

**Comment by pukkandan** [comment]
yt-dlp downloads the video as-is from youtube and does not make any modifications. If the video looks differently in your player as compared to browser, it may be that the player decodes/processes it differently.

It is also possible that the format shown in browser is not the same as the one you are downloading (you can check what browser is playing in "stats for nerds"). There are three 480p formats for this video. You can try selecting a different one that the one you are currently downloading.
```
❯ yt-dlp -F hn1VxaMEjRU
[youtube:AGB] hn1VxaMEjRU: Downloading webpage
[youtube:AGB] hn1VxaMEjRU: Downloading android player API JSON
[info] Available formats for hn1VxaMEjRU:
ID  EXT   RESOLUTION FPS │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR     ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3 mhtml 48x27          │                 mhtml │ images                                     storyboard
sb2 mhtml 80x45          │                 mhtml │ images                                     storyboard
sb1 mhtml 160x90         │                 mhtml │ images                                     storyboard
sb0 mhtml 320x180        │                 mhtml │ images                                     storyboard
139 m4a   audio only     │  980.73KiB  47k https │ audio only         mp4a.40.5   47k 22050Hz low, m4a_dash
249 webm  audio only     │    1.03MiB  51k https │ audio only         opus        51k 48000Hz low, webm_dash
250 webm  audio only     │    1.33MiB  65k https │ audio only         opus        65k 48000Hz low, webm_dash
140 m4a   audio only     │    2.56MiB 127k https │ audio only         mp4a.40.2  127k 44100Hz medium, m4a_dash
251 webm  audio only     │    2.67MiB 132k https │ audio only         opus       132k 48000Hz medium, webm_dash
17  3gp   176x144     10 │    1.62MiB  80k https │ mp4v.20.3      80k mp4a.40.2    0k 22050Hz 144p
394 mp4   256x144     30 │    1.31MiB  65k https │ av01.0.00M.08  65k video only              144p, mp4_dash
160 mp4   256x144     30 │  945.45KiB  45k https │ avc1.4d400c    45k video only              144p, mp4_dash
278 webm  256x144     30 │    1.83MiB  90k https │ vp9            90k video only              144p, webm_dash
395 mp4   426x240     30 │    2.34MiB 116k https │ av01.0.00M.08 116k video only              240p, mp4_dash
133 mp4   426x240     30 │    1.57MiB  78k https │ avc1.4d4015    78k video only              240p, mp4_dash
242 webm  426x240     30 │    2.92MiB 145k https │ vp9           145k video only              240p, webm_dash
396 mp4   640x360     30 │    4.18MiB 207k https │ av01.0.01M.08 207k video only              360p, mp4_dash
134 mp4   640x360     30 │    3.55MiB 176k https │ avc1.4d401e   176k video only              360p, mp4_dash
18  mp4   640x360     30 │    7.71MiB 383k https │ avc1.42001E   383k mp4a.40.2    0k 44100Hz 360p
243 webm  640x360     30 │    5.05MiB 251k https │ vp9           251k video only              360p, webm_dash
397 mp4   854x480     30 │    7.03MiB 349k https │ av01.0.04M.08 349k video only              480p, mp4_dash
135 mp4   854x480     30 │    7.15MiB 355k https │ avc1.4d401f   355k video only              480p, mp4_dash
244 webm  854x480     30 │    8.22MiB 408k https │ vp9           408k video only              480p, webm_dash
```
