### ISSUE TITLE
[imgur:album] imgur video can't be downloaded (404)

### ISSUE THREAD

**Issue by groszdaniel** [yt-dlp/yt-dlp#3228]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Description

Trying to download this video on imgur gives error messages: https://imgur.com/a/evNez8e

Imgur URLs that don't work seem to be ones beginning with https://imgur.com/a/ , referring to a single video.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://imgur.com/a/evNez8e']
[debug] User config "/home/gd/.config/yt-dlp/config": ['--compat-options', 'filename', '--default-search', 'auto_warning', '--ignore-errors', '--add-metadata', '--all-subs', '--convert-subs=srt', '--embed-subs', '--no-clean-infojson']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Compatibility options: filename
[debug] Python version 3.8.12 (CPython 64bit) - Linux-5.16.8-1-default-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1 (fdk,setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: brotlicffi, Crypto, mutagen, sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [imgur:album] Extracting URL: https://imgur.com/a/evNez8e
[imgur:album] evNez8e: Downloading JSON metadata
Traceback (most recent call last):
  File "/bin/yt-dlp/yt_dlp/extractor/common.py", line 735, in _request_webpage
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3591, in urlopen
  File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/yt-dlp/yt_dlp/extractor/common.py", line 617, in extract
  File "/bin/yt-dlp/yt_dlp/extractor/imgur.py", line 130, in _real_extract
  File "/bin/yt-dlp/yt_dlp/extractor/common.py", line 997, in _download_json
  File "/bin/yt-dlp/yt_dlp/extractor/common.py", line 976, in _download_json_handle
  File "/bin/yt-dlp/yt_dlp/extractor/common.py", line 768, in _download_webpage_handle
  File "/bin/yt-dlp/yt_dlp/extractor/common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
  File "/bin/yt-dlp/yt_dlp/extractor/common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [imgur:album] evNez8e: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/bin/yt-dlp/yt_dlp/__init__.py", line 864, in main
  File "/bin/yt-dlp/yt_dlp/__init__.py", line 854, in _real_main
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3254, in download
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3227, in wrapper
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1380, in extract_info
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1407, in wrapper
  File "/bin/yt-dlp/yt_dlp/utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
```

**Comment by ndren** [comment]
It seems that you need https://api.imgur.com/post/v1/posts/ as per https://codeberg.org/rimgo/rimgo/src/branch/main/api/album.go. It's nice that rimgo has code that works for albums.

**Comment by ndren** [comment]
If someone more familiar with yt-dlp code can take a look, please do! It would be nice to have this option when rimgo instances get rate limited.

**Comment by dirkf** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/25351
