### ISSUE TITLE
Add channel support for xvideos

### ISSUE THREAD

**Issue by afterdelight** [yt-dlp/yt-dlp#3236]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Indonesia

### Example URLs

https://www.xvideos.com/channels/girlfriendsfilmsofficial#_tabVideos

### Description

Merge this commit from pull request:

https://github.com/ytdl-org/youtube-dl/pull/30774
https://github.com/dirkf/youtube-dl/commit/3ec2a3d4ead26e014f4d187e79bd53cb6c894104

ty

### Verbose log

```shell
[debug] Command-line config: ['https://www.xvideos.com/channels/girlfriendsfilmsofficial#_tabVideos', '-v', '-o', '%(uploader)s\\[%(upload_date)s] %(title)s [%(id)s].%(ext)s', '--embed-thumbnail', '--download-archive', 'downloaded.txt']
[debug] User config "C:\Users\X\AppData\Roaming\yt-dlp\config": ['--continue', '--format-sort', 'vbr,abr', '--http-chunk-size', '1M', '--buffer-size', '16K', '--sub-lang', 'english', '--embed-metadata', '--abort-on-unavailable-fragment', '-o', '%(title)s [%(id)s].%(ext)s', '--ffmpeg-location', 'D:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.4 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: "D:\Program Files\ffmpeg\bin\ffmpeg.exe" -bsfs
[debug] Checking exe version: "D:\Program Files\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 2022-03-28-git-5ee198f9aa-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-28-git-5ee198f9aa-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'downloaded.txt'
[debug] [generic] Extracting URL: https://www.xvideos.com/channels/girlfriendsfilmsofficial#_tabVideos
[generic] girlfriendsfilmsofficial#_tabVideos: Requesting header
[generic] [debug] Fetching webpage from https://www.xvideos.com/channels/girlfriendsfilmsofficial#_tabVideos
WARNING: [generic] Falling back on generic information extractor.
[generic] girlfriendsfilmsofficial#_tabVideos: Downloading webpage
[generic] [debug] Fetching webpage from https://www.xvideos.com/channels/girlfriendsfilmsofficial#_tabVideos
[generic] girlfriendsfilmsofficial#_tabVideos: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.xvideos.com/channels/girlfriendsfilmsofficial#_tabVideos
Traceback (most recent call last):
  File "c:\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "c:\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1539, in __extract_info
    ie_result = ie.extract(url)
  File "c:\python\python39\lib\site-packages\yt_dlp\extractor\common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "c:\python\python39\lib\site-packages\yt_dlp\extractor\generic.py", line 4127, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.xvideos.com/channels/girlfriendsfilmsofficial#_tabVideos
```

**Comment by afterdelight** [comment]
could you make a PR out of the available patch

**Comment by xniravx** [comment]
I am trying to fetch video URL from channels but getting error.

<img width="1894" height="247" alt="Image" src="https://github.com/user-attachments/assets/f059a3ba-0fe4-4798-aee0-79ab598a72cb" />

**Comment by arisboch** [comment]
yt-dlp 2026.02.21

Still throws an error when I try to download an XVideos user profile:

```
 % yt-dlp https://www.xvideos.com/college-fuck-fest\#_tabVideos --verbose
[debug] Command-line config: ['https://www.xvideos.com/college-fuck-fest#_tabVideos', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2026.02.21 from yt-dlp/yt-dlp [646bb31f3]
[debug] Python 3.13.7 (CPython x86_64 64bit) - Linux-6.17.0-14-generic-x86_64-with-glibc2.42 (OpenSSL 3.5.3 16 Sep 2025, glibc 2.42)
[debug] exe versions: ffmpeg 7.1.1 (setts), ffprobe 7.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.23.0, brotlicffi-1.2.0.0, certifi-2026.01.04, curl_cffi-0.13.0, mutagen-1.47.0, pyxattr-0.8.1, requests-2.32.5, sqlite3-3.46.1, urllib3-2.6.3, websockets-15.0.1, yt_dlp_ejs-0.4.0
[debug] JS runtimes: deno-2.5.6
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1844 extractors
[generic] Extracting URL: https://www.xvideos.com/college-fuck-fest#_tabVideos
[generic] college-fuck-fest#_tabVideos: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] college-fuck-fest#_tabVideos: Extracting information
[debug] Looking for embeds
WARNING: Falling back to normal extractor since lazy extractor YoutubeSearchDateIE does not have attribute real_class; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/davydt/.local/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1698, in wrapper
    return func(self, *args, **kwargs)
  File "/home/davydt/.local/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1833, in __extract_info
    ie_result = ie.extract(url)
  File "/home/davydt/.local/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 765, in extract
    ie_result = self._real_extract(url)
  File "/home/davydt/.local/lib/python3.13/site-packages/yt_dlp/extractor/generic.py", line 979, in _real_extract
    embeds = list(self._extract_embeds(original_url, webpage, urlh=full_response, info_dict=info_dict))
                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davydt/.local/lib/python3.13/site-packages/yt_dlp/extractor/generic.py", line 1004, in _extract_embeds
    gen = ie.extract_from_webpage(self._downloader, url, webpage)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davydt/.local/lib/python3.13/site-packages/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
                   ^^^^^^^^^^^^^^
  File "/home/davydt/.local/lib/python3.13/site-packages/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
                   ^^^^^^^^^^^^^^
  File "/home/davydt/.local/lib/python3.13/site-packages/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
                   ^^^^^^^^^^^^^^
  [Previous line repeated 982 more times]
  File "/home/davydt/.local/lib/python3.13/site-packages/yt_dlp/utils/_utils.py", line 5056, in __get__
    return self.func(cls)
           ~~~~~~~~~^^^^^
  File "/home/davydt/.local/lib/python3.13/site-packages/yt_dlp/extractor/lazy_extractors.py", line 33, in real_class
    cls._real_class = getattr(importlib.import_module(cls._module), cls.__name__)
                              ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1384, in _gcd_import
RecursionError: maximum recursion depth exceeded
```
