### ISSUE TITLE
--prefer-ffmpeg causes KeyError: "ffmpeg" since revision 8a7f68d

### ISSUE THREAD

**Issue by Wiiplay123** [yt-dlp/yt-dlp#3241]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I've tested this on the release version of 2022.03.08.1 and it works fine, but the latest yt-dlp git version as of 2022-03-29 (revision e787011, the one with the new age gate bypass) doesn't work when --prefer-ffmpeg is used.

Replacing my working copy of ffmpeg.py with the previous version (revision 4a3175f) fixes it.

The bug was introduced in revision 8a7f68d when ffmpeg version data caching was added.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--ffmpeg-location', 'F:\\ffmpeg-2022-03-28-git-5ee198f9aa-full_build\\bin', '--prefer-ffmpeg', '-i', '--write-sub', '--all-subs', '--embed-subs', '--write-annotations', '--add-metadata', '--embed-thumbnail', '--write-info', '--no-check-certificate', '--write-description', '-f', 'bestvideo+bestaudio/best', '-o', 'E:/HD Videos/Youtube Videos/%(title)s (%(uploader)s - %(id)s).%(ext)s', 'https://www.youtube.com/watch?v=vYXJoiZriMQ']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: e7870111e
[debug] Python version 3.10.2 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: "F:\ffmpeg-2022-03-28-git-5ee198f9aa-full_build\bin\ffmpeg" -bsfs
[debug] Checking exe version: "F:\ffmpeg-2022-03-28-git-5ee198f9aa-full_build\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 2022-03-28-git-5ee198f9aa-full_build-www.gyan.dev (setts), ffprobe 2022-03-28-git-5ee198f9aa-full_build-www.gyan.dev
[debug] Optional libraries: certifi, sqlite
[debug] Proxy map: {'no': '192.168.99.100'}
Traceback (most recent call last):
  File "E:\GitHub\yt-dlp\yt_dlp\__main__.py", line 19, in <module>
    yt_dlp.main()
  File "E:\GitHub\yt-dlp\yt_dlp\__init__.py", line 869, in main
    _real_main(argv)
  File "E:\GitHub\yt-dlp\yt_dlp\__init__.py", line 830, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "E:\GitHub\yt-dlp\yt_dlp\YoutubeDL.py", line 687, in __init__
    get_postprocessor(pp_def.pop('key'))(self, **compat_kwargs(pp_def)),
  File "E:\GitHub\yt-dlp\yt_dlp\postprocessor\ffmpeg.py", line 585, in __init__
    super(FFmpegEmbedSubtitlePP, self).__init__(downloader)
  File "E:\GitHub\yt-dlp\yt_dlp\postprocessor\ffmpeg.py", line 69, in __init__
    self._determine_executables()
  File "E:\GitHub\yt-dlp\yt_dlp\postprocessor\ffmpeg.py", line 162, in _determine_executables
    if self._versions[p]:
KeyError: 'ffmpeg'
```

**Comment by taco82** [comment]
Seeing the same error when using --ffmpeg-location
```

yt-dlp -v -o '/root/videos/S%(season_number)sE%(episode_number)s-%(title)s.%(ext)s' --ffmpeg-location /usr/bin/ffmpeg -N 5 "https://www.abc.com/shows/the-good-doctor/episode-guide/season-05/11-the-family"
[debug] Command-line config: ['-v', '-o', '/root/videos/S%(season_number)sE%(episode_number)s-%(title)s.%(ext)s', '--ffmpeg-location', '/usr/bin/ffmpeg', '-N', '5', 'https://www.abc.com/shows/the-good-doctor/episode-guide/season-05/11-the-family']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-105-generic-x86_64-with-glibc2.29
[debug] Checking exe version: /usr/bin/ffmpeg -bsfs
[debug] Checking exe version: /usr/bin/ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome, sqlite
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/yt-dlp/yt-dlp/__main__.py", line 19, in <module>
  File "/root/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 869, in main
  File "/root/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 830, in _real_main
  File "/root/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 687, in __init__
  File "/root/yt-dlp/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 1123, in __init__
  File "/root/yt-dlp/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 69, in __init__
  File "/root/yt-dlp/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 162, in _determine_executables
KeyError: 'ffmpeg'
```

Running the same command without specifying the ffmpeg location (it still finds it in the same place), results in a successful download.

**Comment by Lesmiscore** [comment]
Related: https://github.com/ytdl-patched/ytdl-patched/commit/06a93c95ffaf28a778332895859d200e5c3c4a78 (ytdl-patched/ytdl-patched#20)

**Comment by pukkandan** [comment]
I am aware of the issue, and it's an easy fix. But I can't push any code rn. Will fix it soon

**Comment by afterdelight** [comment]
me too got this
