### ISSUE TITLE
Paramount Plus (Unable to download)

### ISSUE THREAD

**Issue by Stonga2** [yt-dlp/yt-dlp#3248]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hey,

I'm trying to download from Paramount Plus, but I'm getting (HTTP Error 403: Forbidden)

Here's the commands I've tried with these 2 URLs:

https://www.paramountplus.com/shows/star-trek-discovery/video/SrUH6PeP2V_jPl1qvSs9ZGFxU6D_czdI/star-trek-discovery-but-to-connect/
https://www.paramountplus.com/shows/video/SrUH6PeP2V_jPl1qvSs9ZGFxU6D_czdI/

yt-dpl
yt-dpl --username xxx --password xxx
yt-dpl --cookies cookies.txt (cookies.txt in same folder as yt-dpl.exe)
yt-dpl --cookies-from-browser chrome

If I try to use the latter link without the cookies command, it tries to redirect to the signin URL and still fails.

I'm in Norway and the show in question is availble for me on the streaming service. if that helps. I do have an account.

Log  with the --cookies command attached.

```shell

F:\>yt-dlp -vU --cookies cookies.txt "https://www.paramountplus.com/shows/star-trek-discovery/video/SrUH6PeP2V_jPl1qvSs9ZGFxU6D_czdI/star-trek-discovery-but-to-connect/"
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.paramountplus.com/shows/star-trek-discovery/video/SrUH6PeP2V_jPl1qvSs9ZGFxU6D_czdI/star-trek-discovery-but-to-connect/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2022-02-03-git-e1a14479a8-full_build-www.gyan.dev (setts)
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/star-trek-discovery/video/SrUH6PeP2V_jPl1qvSs9ZGFxU6D_czdI/star-trek-discovery-but-to-connect/
[ParamountPlus] SrUH6PeP2V_jPl1qvSs9ZGFxU6D_czdI: Downloading JSON metadata
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\cbs.py", line 72, in _real_extract
  File "yt_dlp\extractor\paramountplus.py", line 89, in _extract_video_info
  File "yt_dlp\extractor\common.py", line 997, in _download_json
  File "yt_dlp\extractor\common.py", line 976, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [ParamountPlus] SrUH6PeP2V_jPl1qvSs9ZGFxU6D_czdI: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[700] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by pukkandan** [comment]
> - [X] I'm asking a question and **not** reporting a bug/feature request

**Comment by pukkandan** [comment]
Are you able to watch the video on browser with the given URL with same cookies?

**Comment by kopout** [comment]
> I figured out how to download the episodes using the stream.mpd, but the mpd file provided with the browser only goes up to 1080p. Any suggestions for that?

how do you download steam.mpd?

**Comment by nyuszika7h** [comment]
AFAIK Paramount+'s non-DRM streams max out at 1080p SDR, no 4K or HDR/DV.
