### ISSUE TITLE
Zee5 Site Browken Error

### ISSUE THREAD

**Issue by IAMMADHACKER** [yt-dlp/yt-dlp#3285]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

wen isee supported sites of yt-dlp it shows zee5 too but when run to download any video of zee5 it shows errors same always
please fix this error the owner of yt-dlp 

### Verbose log

```shell
yt-dlp https://www.zee5.com/tv-shows/details/brahmarakshas-2/0-6-3006/tantric-jwala-becomes-brahmarakshas-brahmarakshas-2/0-1-manual_4jh6k2mhrri0 -F
[Zee5] 0-1-manual_4jh6k2mhrri0: Downloading access token
[Zee5] 0-1-manual_4jh6k2mhrri0: Downloading JSON metadata
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\zee5.py", line 136, in _real_extract
  File "yt_dlp\extractor\common.py", line 997, in _download_json
  File "yt_dlp\extractor\common.py", line 976, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [Zee5] 0-1-manual_4jh6k2mhrri0: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[19000] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by NanaMizukiAnother7** [comment]
You can keep tracking on #3105.
