### ISSUE TITLE
Support for two websites: "BrandXMusic.net" AND "Audiomachine.com" (Both possibly owned by the same company.)

### ISSUE THREAD

**Issue by AustinMemeLord** [yt-dlp/yt-dlp#3304]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

All (I think)

### Example URLs

the website in question: https://www.brandxmusic.net

list of all albums: https://www.brandxmusic.net/albums

album example: https://www.brandxmusic.net/albums/bxmt17

track link example https://www.brandxmusic.net/tracks/?tracks=bxm018-10

list of all tracks: https://www.brandxmusic.net/tracks

---

the second website in question: https://www.audiomachine.com

track link example: https://search.audiomachine.com/tracks/?tracks=am08-68

album example: https://search.audiomachine.com/albums/am82

list of all albums: https://search.audiomachine.com/albums/

### Description

**Both websites have the availability to have the music/songs be played in the browser without creating an account.**

The only way you can download the audio (as far as I am aware) is by doing one at a time via opening inspect element, switching to network tab, media tab, and clicking play. Then you double click on the string of numbers and letters that shows up in the box, it will take you to a URL with only the audio, then right clicking it and click "save audio as".

I would like to request this as a supported sites for the following reasons: 

1. They make good music + you can use it in YouTube videos.
2. It's a pain when someone (me) has to search through the entirety of both website's (and wait for it to load, buffer, etc) trying to find one song used in a YT video that only credited the music source as "Audiomachine/BrandXMusic". (It would be alot eaiser to have them be able to download in bulk rather than doing it one at a time using inspect element.)
3. nearly 75% of all songs that on the websites (Audiomachine And BrandXMusic) aren't available anywhere else. 

(Like I said in the title, I'm 95% sure both these websites owned by the same company. I can tell because of the near identical website layout, same artists are in both websites, although no songs are carried over from one to the other. Plus when I did some digging I found auto-generated link by YouTube in the "music in this video" section in someones video description, which led me to a BrandXMusic upload, and it said in description in that upload said "Provided to YouTube by audiomachine.com")

### Verbose log

```shell
BrandXMusic track:

yt-dlp -vU https://www.brandxmusic.net/tracks/?tracks=bxm018-10
[debug] Command-line config: ['-vU', 'https://www.brandxmusic.net/tracks/?tracks=bxm018-10']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://www.brandxmusic.net/tracks/?tracks=bxm018-10
[generic] ?tracks=bxm018-10: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] ?tracks=bxm018-10: Downloading webpage
[generic] ?tracks=bxm018-10: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.brandxmusic.net/tracks/?tracks=bxm018-10
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.brandxmusic.net/tracks/?tracks=bxm018-10

BrandXMusic Album:

yt-dlp -vU https://www.brandxmusic.net/albums/bxmt17
[debug] Command-line config: ['-vU', 'https://www.brandxmusic.net/albums/bxmt17']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://www.brandxmusic.net/albums/bxmt17
[generic] bxmt17: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] bxmt17: Downloading webpage
[generic] bxmt17: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.brandxmusic.net/albums/bxmt17
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.brandxmusic.net/albums/bxmt17

----

Audiomachine track:

yt-dlp -vU https://search.audiomachine.com/tracks?tracks=am08-68
[debug] Command-line config: ['-vU', 'https://search.audiomachine.com/tracks?tracks=am08-68']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://search.audiomachine.com/tracks?tracks=am08-68
[generic] tracks?tracks=am08-68: Requesting header
[redirect] Following redirect to https://search.audiomachine.com/tracks/?tracks=am08-68
[debug] [generic] Extracting URL: https://search.audiomachine.com/tracks/?tracks=am08-68
[generic] ?tracks=am08-68: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] ?tracks=am08-68: Downloading webpage
[generic] ?tracks=am08-68: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://search.audiomachine.com/tracks/?tracks=am08-68
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://search.audiomachine.com/tracks/?tracks=am08-68

Audiomachine album:

yt-dlp -vU https://search.audiomachine.com/albums/am82
[debug] Command-line config: ['-vU', 'https://search.audiomachine.com/albums/am82']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://search.audiomachine.com/albums/am82
[generic] am82: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] am82: Downloading webpage
[generic] am82: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://search.audiomachine.com/albums/am82
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://search.audiomachine.com/albums/am82
```

**Comment by HobbyistDev** [comment]
From this url (https://search.audiomachine.com/tracks/?tracks=am08-68), the audio is in `https://api.cadenzabox.com/tracks?slug=am08-68` and we can get the audio in `['data'][0]['webAudio']`
