### ISSUE TITLE
YouTube video `EgAtw4DeVxg` cannot be downloaded, but it plays in the browser

### ISSUE THREAD

**Issue by danielyli** [yt-dlp/yt-dlp#3308]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

U.S.

### Description

The video `EgAtw4DeVxg` is playable in the browser, but yt-dlp gives 503s when attempting to download. See verbose log below.

### Verbose log

```shell
$ yt-dlp -vU EgAtw4DeVxg
[debug] Command-line config: ['--format-sort=lang,quality,res,fps,hdr,codec,size,br,asr,proto,ext,hasaud,source,id', '--restrict-filenames', '--output=%(id)s.%(ext)s', '-vU', 'EgAtw4DeVxg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.10.2 (CPython 64bit) - macOS-12.2.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.2
yt-dlp is up to date (2022.03.08.2)
[debug] [youtube] Extracting URL: EgAtw4DeVxg
[youtube] EgAtw4DeVxg: Downloading webpage
[youtube] EgAtw4DeVxg: Downloading android player API JSON
[youtube] EgAtw4DeVxg: Downloading MPD manifest
[youtube] EgAtw4DeVxg: Downloading MPD manifest
[debug] Sort order given by user: lang, quality, res, fps, hdr, codec, size, br, asr, proto, ext, hasaud, source, id
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr, vcodec, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] EgAtw4DeVxg: Downloading 1 format(s): 135+251-dash
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1649157021/ei/Pc9LYsbAJsXZkgbPmLewAw/ip/135.180.24.110/id/12002dc380de5718/source/youtube/requiressl/yes/playback_host/rr1---sn-nvopjoxu-25ve.googlevideo.com/mh/2w/mm/31%2C29/mn/sn-nvopjoxu-25ve%2Csn-o097znsr/ms/au%2Crdu/mv/m/mvi/1/pl/20/tx/24129501/txs/24129500%2C24129501%2C24129502%2C24129503%2C24129504%2C24129505/hfr/1/as/fmp4_audio_clear%2Cfmp4_sd_hd_clear/initcwndbps/1865000/vprv/1/mt/1649135091/fvip/5/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRgIhALtTIBhxcfTIEo_WMb8Epvb8t3_o-z8fd9noXwPMOWCuAiEAl4s3lwjVBj7Fzg1NYvAuijzRdqlI7R6XZiNXTbAMM0I%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAKYDJztsyHPW9fBzTusQ-Th3PZv_stXTZ6_vBG82lxvkAiEAod9ZorDTDm3cR3r_BGYuQFzU7AR2VTM6Xt-gl1_U0FI%3D"
[dashsegments] Total fragments: 5
[download] Destination: EgAtw4DeVxg.f135.mp4
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10) ...
ERROR: giving up after 10 retries
  File "/opt/homebrew/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2022.3.8.2', 'console_scripts', 'yt-dlp')())
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/__init__.py", line 864, in main
    _real_main(argv)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/__init__.py", line 854, in _real_main
    retcode = ydl.download(all_urls)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3254, in download
    self.__download_wrapper(self.extract_info)(
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3227, in wrapper
    res = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1380, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2638, in process_video_result
    self.process_info(new_info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3110, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2835, in dl
    return fd.download(name, new_info, subtitle)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/dash.py", line 56, in real_download
    return self.download_and_append_fragments_multiple(*args)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 387, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], pack_func=pack_func, finish_func=finish_func)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 538, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 474, in download_fragment
    success, frag_content = self._download_fragment(ctx, fragment['url'], info_dict, headers)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 134, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 397, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 177, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 939, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 868, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: unable to download video data: [Errno 2] No such file or directory: 'EgAtw4DeVxg.f135.mp4.part-Frag1'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3110, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2835, in dl
    return fd.download(name, new_info, subtitle)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/dash.py", line 56, in real_download
    return self.download_and_append_fragments_multiple(*args)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 387, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], pack_func=pack_func, finish_func=finish_func)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 538, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 474, in download_fragment
    success, frag_content = self._download_fragment(ctx, fragment['url'], info_dict, headers)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 141, in _download_fragment
    return True, self._read_fragment(ctx)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 148, in _read_fragment
    down, frag_sanitized = self.sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 220, in inner
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 237, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/utils.py", line 678, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).open()
  File "/opt/homebrew/Cellar/yt-dlp/2022.3.8.2/libexec/lib/python3.10/site-packages/yt_dlp/utils.py", line 2202, in __init__
    self.f = io.open(filename, mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'EgAtw4DeVxg.f135.mp4.part-Frag1'
```

**Comment by coletdjnz** [comment]
try `--check-formats`

prob a server side issue with that format.

**Comment by danielyli** [comment]
Thanks @coletdjnz. Looks like that worked:

```
$ yt-dlp --check-formats EgAtw4DeVxg
[youtube] EgAtw4DeVxg: Downloading webpage
[youtube] EgAtw4DeVxg: Downloading android player API JSON
[youtube] EgAtw4DeVxg: Downloading MPD manifest
[youtube] EgAtw4DeVxg: Downloading MPD manifest
[info] Testing format 135
ERROR: giving up after 0 retries
[info] Unable to download format 135. Skipping...
[info] Testing format 18
[info] Testing format 251-dash
[info] EgAtw4DeVxg: Downloading 1 format(s): 18
[download] Destination: EgAtw4DeVxg.mp4
[download] 100% of 874.53KiB in 00:00
```

**Comment by danielyli** [comment]
Looks like `--check-formats` goes down the list from best to worst formats and picks the first available one. Is that right?

If so, can the man page be updated to clarify this behavior? Currently it just says the following, which sounds like using the option causes yt-dlp to only check the existence of the formats and not actually download anything:

```
--check-formats
    Check that the selected formats are actually downloadable
```
