### ISSUE TITLE
"ERROR: '<' not supported between instances of 'float' and 'str'" when passing --throttled-rate for YouTube downloads

### ISSUE THREAD

**Issue by funknapkin** [yt-dlp/yt-dlp#3346]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

I recently updated yt-dlp on my system and all downloads are suddenly aborting. I narrowed it down to the "--throttled-rate" parameter. Removing it from my call to yt-dlp allows downloads to succeed. When I leave that parameter, the downloads start successfully but abort almost immediately with the following message:

> ERROR: '<' not supported between instances of 'float' and 'str'

In the log below, I included the call to yt-dlp with and without "--throttled-rate".

### Verbose log

```shell
PS C:\Users\misc> yt-dlp --version
2022.03.08.1
PS C:\Users\misc> yt-dlp -vU --no-config --throttled-rate 100K "https://www.youtube.com/watch?v=rrLkr8DJXcY"
[debug] Command-line config: ['-vU', '--no-config', '--throttled-rate', '100K', 'https://www.youtube.com/watch?v=rrLkr8DJXcY']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=rrLkr8DJXcY
[youtube] rrLkr8DJXcY: Downloading webpage
[youtube] rrLkr8DJXcY: Downloading android player API JSON
[youtube] rrLkr8DJXcY: Downloading player 3b5d5649
[debug] Saving youtube-nsig.3b5d5649 to cache
[debug] [youtube] Decrypted nsig 01a5D6L6O-_EvXFzFG => aVV-TSEM0N399Q
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] rrLkr8DJXcY: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://rr2---sn-cxaaj5o5q5-t9ce.googlevideo.com/videoplayback?expire=1649395132&ei=XHFPYqXHC43U8wSy-ayADA&ip=174.93.107.56&id=o-APnDiz-zMAjnJg3qqiMXhahip8phtK0DNKH58NAzeOUt&itag=303&source=youtube&requiressl=yes&mh=kb&mm=31%2C29&mn=sn-cxaaj5o5q5-t9ce%2Csn-cxaaj5o5q5-tt1ee&ms=au%2Crdu&mv=m&mvi=2&pl=25&initcwndbps=2220000&vprv=1&mime=video%2Fwebm&gir=yes&clen=821520709&dur=3161.949&lmt=1649218381038152&mt=1649373177&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=3310224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgUP1-fnwZEOUlpZar1RxEQglEuz4GwGq8UwkZrou1qygCIQDRQNKlMM3lLV4wd9hhspdOfxria0QgxCH1-2J8Upn1tA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKUAndMFZRJj41UHqnyRt6YscUTScYAEsyk797DfH6ChAiEAumhyrPbKtAFSJuk1ekIiII4SlmkLQM7zOQTOd30STN8%3D"
[download] Resuming download at byte 1024
[download] Destination: Believers, this one is for you (GeoGuessr Duels) [rrLkr8DJXcY].f303.webm
[download]   0.0% of 783.46MiB at 90.58KiB/s ETA 02:27:37ERROR: '<' not supported between instances of 'float' and 'str'Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1473, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1529, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2638, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3110, in process_info
  File "yt_dlp\YoutubeDL.py", line 2835, in dl
  File "yt_dlp\downloader\common.py", line 453, in download
  File "yt_dlp\downloader\http.py", line 384, in real_download
  File "yt_dlp\downloader\http.py", line 334, in download
TypeError: '<' not supported between instances of 'float' and 'str'

PS C:\Users\misc> yt-dlp -vU --no-config "https://www.youtube.com/watch?v=rrLkr8DJXcY"
[debug] Command-line config: ['-vU', '--no-config', 'https://www.youtube.com/watch?v=rrLkr8DJXcY']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=rrLkr8DJXcY
[youtube] rrLkr8DJXcY: Downloading webpage
[youtube] rrLkr8DJXcY: Downloading android player API JSON
[debug] Loading youtube-nsig.3b5d5649 from cache
[debug] [youtube] Decrypted nsig 8J5_8qb6HJC_13v4Ws => HPQ8KE0IBhB-qQ
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] rrLkr8DJXcY: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://rr2---sn-cxaaj5o5q5-t9ce.googlevideo.com/videoplayback?expire=1649395212&ei=rHFPYsiEKobo8wSY1Zy4Ag&ip=174.93.107.56&id=o-ABZnM7TxSXKBLyNZBHKXOyZ9HbOLCLvEOG_SWNOjCYvy&itag=303&source=youtube&requiressl=yes&mh=kb&mm=31%2C29&mn=sn-cxaaj5o5q5-t9ce%2Csn-cxaaj5o5q5-tt1ee&ms=au%2Crdu&mv=m&mvi=2&pl=25&initcwndbps=2220000&vprv=1&mime=video%2Fwebm&gir=yes&clen=821520709&dur=3161.949&lmt=1649218381038152&mt=1649373177&fvip=1&keepalive=yes&fexp=24001373%2C24007246&beids=23886208&c=ANDROID&txp=3310224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgRegsdyf6KiNUleZjBtqwx8wLCg8Qo-ZBtN1ifRWWAwECIFStakKB3T3asNlyxlGV-q2OBb9PIUFBBcIdmGxmysOt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANDyqmlyHjT3RGQ3o34MRJQjOOVZTGG-nDgRq03mnpiQAiEAhfg_wleAXPYkmG86X5LcL_QdoXJvZActQAjtg644BxE%3D"
[download] Resuming download at byte 2048
[download] Destination: Believers, this one is for you (GeoGuessr Duels) [rrLkr8DJXcY].f303.webm
[download] 100% of 783.46MiB in 01:18
[debug] Invoking downloader on "https://rr2---sn-cxaaj5o5q5-t9ce.googlevideo.com/videoplayback?expire=1649395212&ei=rHFPYsiEKobo8wSY1Zy4Ag&ip=174.93.107.56&id=o-ABZnM7TxSXKBLyNZBHKXOyZ9HbOLCLvEOG_SWNOjCYvy&itag=251&source=youtube&requiressl=yes&mh=kb&mm=31%2C29&mn=sn-cxaaj5o5q5-t9ce%2Csn-cxaaj5o5q5-tt1ee&ms=au%2Crdu&mv=m&mvi=2&pl=25&initcwndbps=2220000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=50538573&dur=3162.001&lmt=1649218494947534&mt=1649373177&fvip=1&keepalive=yes&fexp=24001373%2C24007246&beids=23886208&c=ANDROID&txp=3310224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAI_y5XJbbxkWtmSCTVLfZoCRW8CjnK6AfTmAHTQZibpSAiAAkwWZYV-Cz1EdnMfJ0kECehW6wuBLZuFQYvf6OF_JEg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANDyqmlyHjT3RGQ3o34MRJQjOOVZTGG-nDgRq03mnpiQAiEAhfg_wleAXPYkmG86X5LcL_QdoXJvZActQAjtg644BxE%3D"
[download] Destination: Believers, this one is for you (GeoGuessr Duels) [rrLkr8DJXcY].f251.webm
[download] 100% of 48.20MiB in 00:04
[Merger] Merging formats into "Believers, this one is for you (GeoGuessr Duels) [rrLkr8DJXcY].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Believers, this one is for you (GeoGuessr Duels) [rrLkr8DJXcY].f303.webm" -i "file:Believers, this one is for you (GeoGuessr Duels) [rrLkr8DJXcY].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Believers, this one is for you (GeoGuessr Duels) [rrLkr8DJXcY].temp.webm"
Deleting original file Believers, this one is for you (GeoGuessr Duels) [rrLkr8DJXcY].f303.webm (pass -k to keep)
Deleting original file Believers, this one is for you (GeoGuessr Duels) [rrLkr8DJXcY].f251.webm (pass -k to keep)
PS C:\Users\misc>
```

**Comment by NanaMizukiAnother7** [comment]
It was already fixed! See #2996
