### ISSUE TITLE
yt-dlp_min.exe v2022.04.08: FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by awei78** [yt-dlp/yt-dlp#3353]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

D:\>yt-dlp_min.exe
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "yt_dlp\__init__.pyc", line 869, in main
  File "yt_dlp\__init__.pyc", line 830, in _real_main
  File "yt_dlp\YoutubeDL.pyc", line 667, in __init__
  File "yt_dlp\YoutubeDL.pyc", line 3743, in _setup_opener
  File "yt_dlp\utils.pyc", line 1027, in make_HTTPS_handler
FileNotFoundError: [Errno 2] No such file or directory
This problem does not appear in yt-dlp.

### Verbose log

```shell
FileNotFoundError: [Errno 2] No such file or directory.
```

**Comment by pukkandan** [comment]
Use `--compat-options no-certifi` as a workaround

**Comment by pukkandan** [comment]
Another workaround is to download https://raw.githubusercontent.com/certifi/python-certifi/master/certifi/cacert.pem as `cacert.pem` to the same folder as yt-dlp

**Comment by awei78** [comment]
see, thanks!
