### ISSUE TITLE
Please add support for www.vix.com

### ISSUE THREAD

**Issue by fredlkrue** [yt-dlp/yt-dlp#3366]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Ecuador

### Example URLs

https://www.vix.com/es-es/detail/series-2979
https://www.vix.com/es-es/video/video-4158939

### Description

An account is not required to access any content .

### Verbose log

```shell
E:\>yt-dlp.exe -vU https://www.vix.com/es-es/video/video-4158939
[debug] Command-line config: ['-vU', 'https://www.vix.com/es-es/video/video-4158
939']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websoc
kets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://www.vix.com/es-es/video/video-4158939
[generic] video-4158939: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] video-4158939: Downloading webpage
[generic] video-4158939: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.vix.com/es-es/video/video-4158939
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.vix.com/es-es/video/
video-4158939
```

**Comment by hatienl0i261299** [comment]
Geo blocked

**Comment by tripod3d** [comment]
I was about to open an issue for ViX. Thank you you opened before.

**Comment by denaunistic** [comment]
someone check if this is still geo blocked because recently vix expanded to other countries

**Comment by hatienl0i261299** [comment]
![image](https://user-images.githubusercontent.com/36532499/221365518-e1229a13-091c-4691-8ab0-0e307a920f23.png)

Still blocked.

**Comment by ajibarra** [comment]
Using a VPN no any latinamerican country like Panama, Ecuador, Mexico, etc will work. It would be great being able to download free content from this site.

**Comment by germancecch** [comment]
+1

**Comment by camadog** [comment]
First of all, sorry about my english... 

I discover that vix is supported, with generic information extractor, you just need to find an xml file named manifest.mpd. 

Example: 
yt-dlp https://dcs4-vod.mp.lura.live/vod/p/manifest.mpd\?encp\=binary-garbage

(the binary thing is super long...)

**Comment by garret1317** [comment]
> I discover that vix is supported, with generic information extractor, you just need to find an xml file named manifest.mpd.

that's what a dedicated extractor is for, it would find the mpd and metadata automatically

**Comment by bashonly** [comment]
> Example: 
> `yt-dlp https://dcs4-vod.mp.lura.live/vod/p/manifest.mpd\?encp\=binary-garbage`

This type of URL can be handled by `AnvatoIE`, but vix itself will need a dedicated extractor to get the anvato ID / access key / token
