### ISSUE TITLE
Add support for VK audio/music playlist

### ISSUE THREAD

**Issue by ImVantexHD** [yt-dlp/yt-dlp#3375]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Example URLs

https://vk.com/audios-173441691
https://vk.com/music/playlist/-173441691_44
https://vk.com/music/playlist/573558507_20 (playlist with more than 10 tracks and without "-" in the playlist id)
https://vk.com/audio?z=audio_playlist573558507_20 (list all the tracks in the playlist)
https://vk.com/wall-173441691_5559 (wall post with only 1 track)

### Description

yt-dlp supports only videos for vk.com, but not audio or music playlist, would it be hard to integrate this feature?

The website can get segmented m3u8 links in this form: https://cs6-7v4.vkuseraudio.net/s/v1/ac/aplEWFsFqiAPcv_H1t1XMQhoYqfkQlkrk6WpSSs85YjskBAweNRNjbvxmZ5pUxKOxfeNo_2ncQ-ousLIO3JLb3PAls0BRnnw3ckixHcVpuyViABEMyXjsG0CdGLra2ouyu1FZLCdvg/index.m3u8

im not sure if the app can grab the mp3 directly but this is the API address: https://api.vk.com/method/-method-name
and the methods: https://vk.com/dev/methods (i can give my account if needed)

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://vk.com/audios-173441691', '--extract-audio']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106544-g58b07ecb3f-20220409 (setts), ffprobe N-106544-g58b07ecb3f-20220409
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://vk.com/audios-173441691
[generic] audios-173441691: Requesting header
WARNING: [generic] Could not send HEAD request to https://vk.com/audios-173441691: HTTP Error 418:
[generic] audios-173441691: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] audios-173441691: Extracting information
[debug] Looking for video embeds
[redirect] Following redirect to https://vk.com/badbrowser.php
[debug] [generic] Extracting URL: https://vk.com/badbrowser.php
[generic] badbrowser: Requesting header
WARNING: [generic] Could not send HEAD request to https://vk.com/badbrowser.php: HTTP Error 418:
[generic] badbrowser: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] badbrowser: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://vk.com/badbrowser.php
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vk.com/badbrowser.php
```

**Comment by sergeevabc** [comment]
Version: 2022.04.27

```
$ yt-dlp https://vk.com/wall-3482921_7273
[vk:wallpost] -3482921_7273: Downloading JSON metadata
[download] Downloading playlist: Ultimae Records - Wall post -3482921_7273
[vk:wallpost] playlist Ultimae Records - Wall post -3482921_7273: Collected 0 videos; downloading 0 of them
[download] Finished downloading playlist: Ultimae Records - Wall post -3482921_7273
```

**Comment by ImVantexHD** [comment]
> any update on this? when cloning my browsers user agent in \yt_dlp\utils_utils.py and passing cookies i still get the error above. for https://vk.com/audios-29029940

no, but you can use [Meridius](https://github.com/PurpleHorrorRus/Meridius) to download music playlist from VK
i haven't found a better option to download audio in batch from vk other than that. the extractor for vk can only do video :/

**Comment by nextgearslab** [comment]
2 years later and nothing, what the hell

**Comment by bashonly** [comment]
@NickWinston123 you should get to work on it

**Comment by flawrist** [comment]
VK is the great source of music, because a lot or ex-USSR users, the major part of that social network, are avid music listeners and they like to share. It's a true media ark. Thus, IT specialists who can use their intelligence to add the feature to YT-DLP to extract music from VK will be remembered as heroes. We need such IT specialists here! Hello?

![](https://slimger.com/wp-content/uploads/2021/04/shutterstock_1915493305.jpg)

**Comment by ImVantexHD** [comment]
remember opening this in 2022 thinking surely someone will have added audio playlist support by now, oh well...

thanks @sergeevabc for still dropping by every year
you ever find a CLI solution? besides the program i mentioned way back (not CLI)

**Comment by nektorom** [comment]
As I see, vk music now supports links to separate audio files, the pattern is the same as for video. It maybe easier to parse them now.
example:
https://vk.com/audio422157162_456242347

**Comment by DimucaTheDev** [comment]
Any updates?
