### ISSUE TITLE
[Bug] Unexpected error when using protocol downloaders

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [yt-dlp/yt-dlp#3384]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Using '--downloader "https:ffmpeg"' will result in error and fails to start downloading.

### Verbose log

```shell
C:\Users\User>yt-dlp --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36" -v --rm-cache-dir --no-mtime --prefer-insecure --extractor-args "youtube:player-client=default,tv_embedded" -o "D:\Google Drive & YouTube Video Downloads and more\%(title)s.%(ext)s" "ytsearch:The dylan and patricia's eternal love" --downloader-args "ffmpeg:map_metadata -1" --downloader "https:ffmpeg" -f 18
[debug] Command-line config: ['--user-agent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 S
afari/537.36', '-v', '--rm-cache-dir', '--no-mtime', '--prefer-insecure', '--extractor-args', 'youtube:player-client=default,tv_embedded', '
-o', 'D:\\Google Drive & YouTube Video Downloads and more\\%(title)s.%(ext)s', "ytsearch:The dylan and patricia's eternal love", '--download
er-args', 'ffmpeg:-map_metadata -1', '--downloader', 'https:ffmpeg', '-f', '18']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-03-31-git-e301a24fa1-full_build-www.gyan.dev (setts), ffprobe N-105038-g30322ebe3c-sherpya
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Removing cache dir C:\Users\User/.cache\yt-dlp ..
[debug] [youtube:search] Extracting URL: ytsearch:The dylan and patricia's eternal love
[download] Downloading playlist: The dylan and patricia's eternal love
[youtube:search] query "The dylan and patricia's eternal love" page 1: Downloading API JSON
[youtube:search] playlist The dylan and patricia's eternal love: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Lhv0qyip46o
[youtube] Lhv0qyip46o: Downloading webpage
[youtube] Lhv0qyip46o: Downloading android player API JSON
[youtube] Lhv0qyip46o: Downloading tv embedded player API JSON
[youtube] Lhv0qyip46o: Downloading MPD manifest
[youtube] Lhv0qyip46o: Downloading MPD manifest
[youtube] Lhv0qyip46o: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx
, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Lhv0qyip46o: Downloading 1 format(s): 18
ERROR: 'NoneType' object has no attribute 'can_download'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2648, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3138, in process_info
  File "yt_dlp\YoutubeDL.py", line 2832, in dl
  File "yt_dlp\downloader\__init__.py", line 16, in get_suitable_downloader
  File "yt_dlp\downloader\__init__.py", line 16, in <listcomp>
  File "yt_dlp\downloader\__init__.py", line 110, in _get_suitable_downloader
AttributeError: 'NoneType' object has no attribute 'can_download'

[download] Finished downloading playlist: The dylan and patricia's eternal love
```

**Comment by pukkandan** [comment]
It should be `http:ffmpeg`

**Comment by NanaMizukiAnother7** [comment]
This worked! Thank you!:

```
[debug] Command-line config: ['--user-agent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 S
afari/537.36', '-v', '--rm-cache-dir', '--no-mtime', '--prefer-insecure', '--extractor-args', 'youtube:player-client=default,tv_embedded', '
-o', 'D:\\Google Drive & YouTube Video Downloads and more\\%(title)s OK.%(ext)s', "ytsearch:The dylan and patricia's eternal love", '--downl
oader-args', 'ffmpeg:-map_metadata -1', '--downloader', 'http:ffmpeg', '-f', '18']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev (setts), ffprobe N-106528-g4fbf3c828b-sherpya
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Removing cache dir C:\Users\User/.cache\yt-dlp ..
[debug] [youtube:search] Extracting URL: ytsearch:The dylan and patricia's eternal love
[download] Downloading playlist: The dylan and patricia's eternal love
[youtube:search] query "The dylan and patricia's eternal love" page 1: Downloading API JSON
[youtube:search] playlist The dylan and patricia's eternal love: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Lhv0qyip46o
[youtube] Lhv0qyip46o: Downloading webpage
[youtube] Lhv0qyip46o: Downloading android player API JSON
[youtube] Lhv0qyip46o: Downloading tv embedded player API JSON
[youtube] Lhv0qyip46o: Downloading MPD manifest
[youtube] Lhv0qyip46o: Downloading MPD manifest
[youtube] Lhv0qyip46o: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx
, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Lhv0qyip46o: Downloading 1 format(s): 18
[debug] Invoking downloader on "https://rr3---sn-5fo-0u2e.googlevideo.com/videoplayback?expire=1649686251&ei=i-JTYp6DHvn84-EPkveE8Ac&ip=184.
22.138.46&id=o-AKldULUnDRIgsqYTX_3XsgMEQw50HT_PscmTn9K2J3pQ&itag=18&source=youtube&requiressl=yes&mh=88&mm=31%2C29&mn=sn-5fo-0u2e%2Csn-5fo-c
33z&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=22&initcwndbps=1936250&vprv=1&xtags=heaudio%3Dtrue&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1169
.449&lmt=1638225612922986&mt=1649664292&fvip=4&fexp=24001373%2C24007246&c=ANDROID&txp=6218224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%
2Crequiressl%2Cvprv%2Cxtags%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAK5AYLYsuLFa_tmCyHrEFp5BeyYxnwTWPPJ6OytC3cKAAiBMbC7k7USAzS
giIGseudcneHiCEpSEqQDw-8HatDaqlQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgBHu4LjmrchpVFYq-Y
_0VMggsbe9X0zQvjTqI2rYyH4UCICD3OntTnE263geqW8444yMSHwqTx2hjnLlUvUmUhy0m"
[download] Destination: D:\Google Drive & YouTube Video Downloads and more\The Dylan and Patricia's Eternal Love (2019) - Full Movie (Teleci
ne) OK.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, li
ke Gecko) Chrome/100.0.4896.75 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
" -i "https://rr3---sn-5fo-0u2e.googlevideo.com/videoplayback?expire=1649686251&ei=i-JTYp6DHvn84-EPkveE8Ac&ip=184.22.138.46&id=o-AKldULUnDRI
gsqYTX_3XsgMEQw50HT_PscmTn9K2J3pQ&itag=18&source=youtube&requiressl=yes&mh=88&mm=31%2C29&mn=sn-5fo-0u2e%2Csn-5fo-c33z&ms=au%2Crdu&mv=m&mvi=3
&pcm2cms=yes&pl=22&initcwndbps=1936250&vprv=1&xtags=heaudio%3Dtrue&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1169.449&lmt=1638225612922986&
mt=1649664292&fvip=4&fexp=24001373%2C24007246&c=ANDROID&txp=6218224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cxtag
s%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAK5AYLYsuLFa_tmCyHrEFp5BeyYxnwTWPPJ6OytC3cKAAiBMbC7k7USAzSgiIGseudcneHiCEpSEqQDw-8Ha
tDaqlQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgBHu4LjmrchpVFYq-Y_0VMggsbe9X0zQvjTqI2rYyH4U
CICD3OntTnE263geqW8444yMSHwqTx2hjnLlUvUmUhy0m" -c copy -f mp4 -map_metadata -1 "file:D:\Google Drive & YouTube Video Downloads and more\The
Dylan and Patricia's Eternal Love (2019) - Full Movie (Telecine) OK.mp4.part"
ffmpeg version 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv
 --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsr
t --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --
enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2
--enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libf
reetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enab
le-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulka
n --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --
enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable
-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmyso
fa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.101 / 59. 25.101
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 30.100 /  8. 30.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[tcp @ 0000000000485f80] Starting connection attempt to 58.64.54.110 port 443
[tcp @ 0000000000485f80] Successfully connected to 58.64.54.110 port 443
[h264 @ 000000000378fb80] Reinit context to 640x368, pix_fmt: yuv420p
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://rr3---sn-5fo-0u2e.googlevideo.com/videoplayback?expire=1649686251&ei=i-JTYp6DHvn84-EPkveE8A
c&ip=184.22.138.46&id=o-AKldULUnDRIgsqYTX_3XsgMEQw50HT_PscmTn9K2J3pQ&itag=18&source=youtube&requiressl=yes&mh=88&mm=31%2C29&mn=sn-5fo-0u2e%2
Csn-5fo-c33z&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=22&initcwndbps=1936250&vprv=1&xtags=heaudio%3Dtrue&mime=video%2Fmp4&cnr=14&ratebypass=yes
&dur=1169.449&lmt=1638225612922986&mt=1649664292&fvip=4&fexp=24001373%2C24007246&c=ANDROID&txp=6218224&sparams=expire%2Cei%2Cip%2Cid%2Citag%
2Csource%2Crequiressl%2Cvprv%2Cxtags%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAK5AYLYsuLFa_tmCyHrEFp5BeyYxnwTWPPJ6OytC3cKAAiBMb
C7k7USAzSgiIGseudcneHiCEpSEqQDw-8HatDaqlQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgBHu4Ljmr
chpVFYq-Y_0VMggsbe9X0zQvjTqI2rYyH4UCICD3OntTnE263geqW8444yMSHwqTx2hjnLlUvUmUhy0m':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2021-08-10T21:52:05.000000Z
  Duration: 00:19:29.26, start: 0.000000, bitrate: 256 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main), 1 reference frame (avc1 / 0x31637661), yuv420p(tv, bt709, progressive, left), 640x360 (640x368)
 [SAR 1:1 DAR 16:9], 205 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      creation_time   : 2021-08-10T21:52:05.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 08/10/2021.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 47 kb/s (default)
    Metadata:
      creation_time   : 2021-08-10T21:52:05.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 08/10/2021.
      vendor_id       : [0][0][0][0]
Output #0, mp4, to 'file:D:\Google Drive & YouTube Video Downloads and more\The Dylan and Patricia's Eternal Love (2019) - Full Movie (Telec
ine) OK.mp4.part':
  Metadata:
    encoder         : Lavf59.20.101
  Stream #0:0: Video: h264 (Main), 1 reference frame (avc1 / 0x31637661), yuv420p(tv, bt709, progressive, left), 640x360 (0x0) [SAR 1:1 DAR
16:9], q=2-31, 205 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
  Stream #0:1: Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 47 kb/s (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
No more output streams to write to, finishing.me=00:17:29.00 bitrate= 253.9kbits/s speed= 349x
frame=29232 fps=8832 q=-1.0 Lsize=   36883kB time=00:19:29.26 bitrate= 258.4kbits/s speed= 353x
video:29356kB audio:6851kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.866931%
Input file #0 (https://rr3---sn-5fo-0u2e.googlevideo.com/videoplayback?expire=1649686251&ei=i-JTYp6DHvn84-EPkveE8Ac&ip=184.22.138.46&id=o-AK
ldULUnDRIgsqYTX_3XsgMEQw50HT_PscmTn9K2J3pQ&itag=18&source=youtube&requiressl=yes&mh=88&mm=31%2C29&mn=sn-5fo-0u2e%2Csn-5fo-c33z&ms=au%2Crdu&m
v=m&mvi=3&pcm2cms=yes&pl=22&initcwndbps=1936250&vprv=1&xtags=heaudio%3Dtrue&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1169.449&lmt=16382256
12922986&mt=1649664292&fvip=4&fexp=24001373%2C24007246&c=ANDROID&txp=6218224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvp
rv%2Cxtags%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAK5AYLYsuLFa_tmCyHrEFp5BeyYxnwTWPPJ6OytC3cKAAiBMbC7k7USAzSgiIGseudcneHiCEpS
EqQDw-8HatDaqlQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgBHu4LjmrchpVFYq-Y_0VMggsbe9X0zQvjT
qI2rYyH4UCICD3OntTnE263geqW8444yMSHwqTx2hjnLlUvUmUhy0m):
  Input stream #0:0 (video): 29232 packets read (30060285 bytes);
  Input stream #0:1 (audio): 25178 packets read (7015584 bytes);
  Total: 54410 packets (37075869 bytes) demuxed
Output file #0 (file:D:\Google Drive & YouTube Video Downloads and more\The Dylan and Patricia's Eternal Love (2019) - Full Movie (Telecine)
 OK.mp4.part):
  Output stream #0:0 (video): 29232 packets muxed (30060285 bytes);
  Output stream #0:1 (audio): 25178 packets muxed (7015584 bytes);
  Total: 54410 packets (37075869 bytes) muxed
[AVIOContext @ 00000000036dfa00] Statistics: 37768082 bytes written, 16 seeks, 155 writeouts
[AVIOContext @ 00000000035dac00] Statistics: 37496396 bytes read, 0 seeks
[ffmpeg] Downloaded 37768050 bytes
[download] 100% of 36.02MiB in 00:04
[download] Finished downloading playlist: The dylan and patricia's eternal love
```
