### ISSUE TITLE
Funimation: No valid Free Avails for this experience

### ISSUE THREAD

**Issue by AldaronLau** [yt-dlp/yt-dlp#3387]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

Some funimation videos fail download with "No valid Free Avails for this experience" despite being available to watch for free on the site.

**edit**: After some further testing, I have found that this occurs randomly - rather than for specific videos.

**edit 2**: Appears to fails consistently for:
 - https://www.funimation.com/v/steinsgate/steinsgate-the-movie-load-region-of-deja-vu
 - https://www.funimation.com/v/steinsgate/23-divide-by-zero

Apparently anything that requires the subscription always fails, and free content sometimes fails.

### Verbose log

```shell
$ yt-dlp https://www.funimation.com/v/steinsgate/physically-necrosis --extractor-args "funimation:version=uncut" --extractor-args="funimation:language=english" --no-check-certificate -f b -vU
[debug] Command-line config: ['https://www.funimation.com/v/steinsgate/physically-necrosis', '--extractor-args', 'funimation:version=uncut', '--extractor-args=funimation:language=english', '--no-check-certificate', '-f', 'b', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.9.10 (CPython 64bit) - Linux-5.16.18-200.fc35.x86_64-x86_64-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: certifi, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[funimation:page] Checking geo-location
[debug] [funimation:page] Extracting URL: https://www.funimation.com/v/steinsgate/physically-necrosis
[funimation:page] steinsgate_physically-necrosis: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/728694
[Funimation] 728694: Downloading player webpage for 728694
[Funimation] physically-necrosis: Downloading Uncut english (728694) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Free Avails for this experience
ERROR: [Funimation] 78840: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2487, in process_video_result
    self.raise_no_formats(info_dict)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 981, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Funimation] 78840: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Jules-A** [comment]
It's because you are forcing uncut, you should do something like this instead ``-f '(bv*+ba/b)[format_note=Uncut] / (bv*+ba/b)'`` to fall back to simulcast. Uncut episodes are almost never free to watch so you were likely watching simulcast free on the website.

**Comment by AldaronLau** [comment]
@Jules-A simulcast fails as well (with paid subscription):

```shell
yt-dlp https://www.funimation.com/v/steinsgate/steinsgate-the-movie-load-region-of-deja-vu --extractor-args "funimation:version=simulcast" --extractor-args="funimation:language=english" --no-check-certificate -vU -u $USERNAME -p $PASSWORD
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.9.10 (CPython 64bit) - Linux-5.16.18-200.fc35.x86_64-x86_64-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: certifi, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[funimation:page] Logging in
[funimation:page] Checking geo-location
[debug] [funimation:page] Extracting URL: https://www.funimation.com/v/steinsgate/steinsgate-the-movie-load-region-of-deja-vu
[funimation:page] steinsgate_steinsgate-the-movie-load-region-of-deja-vu: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/1102569
[Funimation] 1102569: Downloading player webpage for 1102569
[Funimation] steinsgate-the-movie-load-region-of-deja-vu: Downloading Uncut english (1102569) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Free Avails for this experience
ERROR: [Funimation] 300929: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2487, in process_video_result
    self.raise_no_formats(info_dict)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 981, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Funimation] 300929: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
Try without any `--extractor-args`

**Comment by AldaronLau** [comment]
@pukkandan Still getting the same error

```
$ yt-dlp https://www.funimation.com/v/steinsgate/steinsgate-the-movie-load-region-of-deja-vu --no-check-certificate -vU -u $USERNAME -p $PASSWORD
[debug] Command-line config: ['https://www.funimation.com/v/steinsgate/steinsgate-the-movie-load-region-of-deja-vu', '--no-check-certificate', '-vU', '-u', 'PRIVATE', '-p', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.9.10 (CPython 64bit) - Linux-5.16.18-200.fc35.x86_64-x86_64-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: certifi, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[funimation:page] Logging in
[funimation:page] Checking geo-location
[debug] [funimation:page] Extracting URL: https://www.funimation.com/v/steinsgate/steinsgate-the-movie-load-region-of-deja-vu
[funimation:page] steinsgate_steinsgate-the-movie-load-region-of-deja-vu: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/1102569
[Funimation] 1102569: Downloading player webpage for 1102569
[Funimation] steinsgate-the-movie-load-region-of-deja-vu: Downloading Uncut japanese (300967) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Free Avails for this experience
[Funimation] steinsgate-the-movie-load-region-of-deja-vu: Downloading Uncut english (1102569) JSON
WARNING: [Funimation] Funimation said: Error 4 - No valid Free Avails for this experience
ERROR: [Funimation] 300929: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2487, in process_video_result
    self.raise_no_formats(info_dict)
  File "/var/home/jeron/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 981, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Funimation] 300929: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Jules-A** [comment]
> @Jules-A simulcast fails as well (with paid subscription):

Don't think multiple --extractor-args work, if you are doing multiple you need to do --extractor-args "funimation:version=simulcast;language=english" if I can recall.
That said I just realised that video is uncut only, don't know why they would offer it for free, I know it's not in Australia.
I can also reproduce the no free avails without cookies, but works fine with cookies. The Funimation extractor has always had issues when you don't use cookies so best to make sure you do. If I can recall it had something to do with the broken login requiring encapsule codes or something.

**Comment by AldaronLau** [comment]
@Jules-A Thanks, cookies fixed it!  I'll close this since it ended up being a duplicate.
