### ISSUE TITLE
https://kinescope.io/

### ISSUE THREAD

**Issue by svarkaoptiki** [yt-dlp/yt-dlp#3391]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Russia

### Example URLs

https://kinescope.io/200597093/
https://kinescope.io/200597096/

### Description

https://kinescope.io/200597096/1080p after loading, you can download it with the right mouse button in mp4 but without sound.

### Verbose log

```shell
yt-dlp -vU https://kinescope.io/200597093/ --no-check-certificate
[debug] Command-line config: ['-vU', 'https://kinescope.io/200597093/', '--no-check-certificate']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: certifi, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://kinescope.io/200597093/
[generic] 200597093: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 200597093: Downloading webpage
[generic] 200597093: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://kinescope.io/200597093/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://kinescope.io/200597093/
```

**Comment by pukkandan** [comment]
All needed info is in the ld+json and `playerOptions` object in the webpage

**Comment by TyroSpy** [comment]
`yt-dlp.exe -vU --ffmpeg-location "c:\run\ffmpeg" --no-check-certificates https://kinescope.io/201130050/master.m3u8
[debug] Command-line config: ['-vU', '--ffmpeg-location', 'c:\\run\\ffmpeg', '--no-check-certificates', 'https://kinescope.io/201130050/master.m3u8']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: "c:\run\ffmpeg\ffmpeg" -bsfs
[debug] Checking exe version: "c:\run\ffmpeg\ffprobe" -bsfs
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://kinescope.io/201130050/master.m3u8
[generic] master: Requesting header
WARNING: [generic] Could not send HEAD request to https://kinescope.io/201130050/master.m3u8: HTTP Error 405: Method Not Allowed
[generic] master: Downloading webpage
[debug] Identified a direct video link
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] master: Downloading 1 format(s): 5161+audio_mp4a-Unknown
[debug] Invoking downloader on "https://kinescope.io/201130050/media.m3u8?quality=1080&type=video"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 800
[download] Destination: master [master].f5161.mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[download]   0.0% of ~1.46TiB at 28.80MiB/s ETA 14:45:18[download] Got server HTTP error: Downloaded 78643200 bytes, expected 2005523523 bytes. Retrying (attempt 1 of 10) ...
[download] 100% of 1.97GiB in 02:12
[debug] Invoking downloader on "https://kinescope.io/201130050/media.m3u8?quality=1080&type=audio&lang=und"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 799
[download] Destination: master [master].faudio_mp4a-Unknown.mp4
[download] 100% of 107.63MiB in 00:58
[debug] ffmpeg command line: "c:\run\ffmpeg\ffprobe" -show_streams "file:master [master].faudio_mp4a-Unknown.mp4"
[Merger] Merging formats into "master [master].mp4"
[debug] ffmpeg command line: "c:\run\ffmpeg\ffmpeg" -y -loglevel "repeat+info" -i "file:master [master].f5161.mp4" -i "file:master [master].faudio_mp4a-Unknown.mp4" -c copy -map "0:v:0" -map "1:a:0" "-bsf:a:0" aac_adtstoasc -movflags "+faststart" "file:master [master].temp.mp4"
Deleting original file master [master].f5161.mp4 (pass -k to keep)
Deleting original file master [master].faudio_mp4a-Unknown.mp4 (pass -k to keep)`
But after merging i get unplayable file master [master].mp4 with strange size 209MB

**Comment by pukkandan** [comment]
Are the files before merger (Use `-k`) playable?

**Comment by TyroSpy** [comment]
with -k option video file is worst playable, don't work rewind, audio file play fine.
`General
Complete name                            : D:\Program\yt-dlp\master [master].f5161.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41/iso5)
File size                                : 1.97 GiB
Duration                                 : 4 min 16 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 65.9 Mb/s
IsTruncated                              : Yes

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Format settings, GOP                     : M=4, N=60
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 4 min 16 s
Bit rate mode                            : Variable
Bit rate                                 : 3 333 kb/s
Maximum bit rate                         : 6 750 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.054
Stream size                              : 102 MiB (5%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC`
-------------------------------------------------------
`General
Complete name                            : D:\Program\yt-dlp\master [master].faudio_mp4a-Unknown.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41/iso5)
File size                                : 108 MiB
Duration                                 : 1 h 46 min
Overall bit rate mode                    : Constant
Overall bit rate                         : 141 kb/s

Audio
ID                                       : 1
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 1 h 46 min
Bit rate mode                            : Constant
Bit rate                                 : 140 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 106 MiB (99%)
Default                                  : Yes
Alternate group                          : 1`

**Comment by pukkandan** [comment]
While many sites like to pretend clearkey is DRM, it can hardly be called one - and is supported by yt-dlp. Other DRMs will not be supported. I have verified that atleast the given example URL does not contain any real DRM

**Comment by TyroSpy** [comment]
Now, with latest version yt-dlp, the video downloads well, after merging I get the true file size and there are no problems with playback. I can't know this was be a developer fix or it changes were made in the resource itself

**Comment by Mefisst** [comment]
Tell me how to download step by step? I have a video embedded in the site, but I don’t understand how to download it. How to get a link to a video on a website page and then how to download it?

**Comment by svarkaoptiki** [comment]
> Tell me how to download step by step? I have a video embedded in the site, but I don’t understand how to download it. How to get a link to a video on a website page and then how to download it?

Hi, can you give link to video?

**Comment by soaska** [comment]
> Save web page and then find in the html file with link .m3u8 extension. But protected content placed directly on kinescope.io nevertheless does not possible to download.

It worked very well with no additional steps. But using "View Page Source" is quicker :)
Thank you

**Comment by 0xvd** [comment]
> > Save web page and then find in the html file with link .m3u8 extension. But protected content placed directly on kinescope.io nevertheless does not possible to download.
> 
> It worked very well with no additional steps. But using "View Page Source" is quicker :) Thank you

The site is working in yt-dlp not supported yet but working without supporting

```
[debug] Command-line config: ['https://kinescope.io/200597093', '-vF']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.12.08 from yt-dlp/yt-dlp [7a52ff29d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.0 (CPython AMD64 64bit) - Windows-11-10.0.26200-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg 2025-12-28-git-9ab2a437a1-full_build-www.gyan.dev (setts), ffprobe 2025-12-28-git-9ab2a437a1-full_build-www.gyan.dev
[debug] Optional libraries: brotli-1.2.0, certifi-2026.01.04, curl_cffi-0.13.0, sqlite3-3.42.0
[debug] JS runtimes: deno-2.6.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1852 extractors
[generic] Extracting URL: https://kinescope.io/200597093
[generic] 200597093: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 200597093: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[generic] Extracting URL: https://kinescope.io/7c89acb3-2d4a-4827-8579-e234c0f7229c/master.m3u8?expires=1767677124&amp;token=#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22200597093%22%2C+%22to_generic%22%3A+true%2C+%22referer%22%3A+%22https%3A%2F%2Fkinescope.io%2F200597093%22%7D
[generic] 200597093: Downloading webpage
[debug] Identified a direct video link
[generic] 200597093: Downloading m3u8 information
[generic] 200597093: Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 200597093:
ID                 EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────
audio_mp4a-English mp4 audio only     │                  m3u8  │ audio only        unknown    [en] English
459                mp4 640x360     25 │ ~ 25.06MiB  460k m3u8  │ avc1.4D401E  460k video only
687                mp4 852x480     25 │ ~ 37.47MiB  688k m3u8  │ avc1.4D401F  688k video only
1338               mp4 1280x720    25 │ ~ 72.95MiB 1339k m3u8  │ avc1.4D401F 1339k video only
2710               mp4 1920x1080   25 │ ~147.64MiB 2710k m3u8  │ avc1.640028 2710k video only
```
