### ISSUE TITLE
[Broken] Downloading playlist with --write-all-thumbnails

### ISSUE THREAD

**Issue by Zirro** [yt-dlp/yt-dlp#341]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ yt-dlp --write-all-thumbnails --verbose 'https://www.youtube.com/playlist?list=PLi0SM524ylKWAherfvcgRbAX3AI5el43M'
[debug] Command-line config: ['--write-all-thumbnails', '--verbose', 'https://www.youtube.com/playlist?list=PLi0SM524ylKWAherfvcgRbAX3AI5el43M']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.05.20 (zip)
[debug] Python version 3.9.5 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLi0SM524ylKWAherfvcgRbAX3AI5el43M
[youtube:tab] PLi0SM524ylKWAherfvcgRbAX3AI5el43M: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLi0SM524ylKWAherfvcgRbAX3AI5el43M
[youtube:tab] PLi0SM524ylKWAherfvcgRbAX3AI5el43M: Downloading API JSON with unavailable videos
[download] Downloading playlist: REAL ATC (No emergency)
[youtube:tab] PLi0SM524ylKWAherfvcgRbAX3AI5el43M page 1: Downloading API JSON
[youtube:tab] PLi0SM524ylKWAherfvcgRbAX3AI5el43M page 2: Downloading API JSON
ERROR: 'id'
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1127, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1159, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1258, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1399, in __process_playlist
    self._write_thumbnails(ie_copy, self.prepare_filename(ie_copy, 'pl_thumbnail'))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3237, in _write_thumbnails
    suffix = '%s.' % t['id'] if multiple else ''
KeyError: 'id'

```

## Description

Downloading a playlist while providing `--write-all-thumbnails` results in `ERROR: 'id'`. I believe this might have started with https://github.com/yt-dlp/yt-dlp/commit/ff2751ac9cc7d4150797d3207da9b566396bc796 or the commits surrounding it.

**Comment by pukkandan** [comment]
I've patched it, but if you are using the last release, use `--compat-options no-playlist-metafiles` as a workaround
