### ISSUE TITLE
GabTV channel_name error download

### ISSUE THREAD

**Issue by hbbernardo** [yt-dlp/yt-dlp#3416]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Description

When I try to use yt-dlp on GabTV an error is given: unable to extract channel_name 

### Verbose log

```shell
yt-dlp -vU https://tv.gab.com/channel/davecullen/view/three-experiments-that-explain-conformity-and-6254454f4c1b91f9610e8aa1
[debug] Command-line config: ['-vU', 'https://tv.gab.com/channel/davecullen/view/three-experiments-that-explain-conformity-and-6254454f4c1b91f9610e8aa1'][debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-151-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Crypto, secretstorage, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [GabTV] Extracting URL: https://tv.gab.com/channel/davecullen/view/three-experiments-that-explain-conformity-and-6254454f4c1b91f9610e8aa1
[GabTV] 6254454f4c1b91f9610e8aa1: Downloading webpage
ERROR: [GabTV] three-experiments-that-explain-conformity-and-6254454f4c1b91f9610e8aa1: Unable to extract channel_name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "./yt-dlp/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/gab.py", line 36, in _real_extract
    channel_name = self._search_regex(r'data-channel-name=\"(?P<channel_id>[^\"]+)', webpage, 'channel_name')
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name
```

**Comment by HalvorRaknes** [comment]
This is what I get. I don't know if this provides additional information for solving this issue:

```
 yt-dlp -vU -f 'bv[height<=720]+ba/b[height<=720]' --datebefore 20220331 --dateafter 20220307 https://tv.gab.com/channel/realredelephants
[debug] Command-line config: ['-vU', '-f', 'bv[height<=720]+ba/b[height<=720]', '--datebefore', '20220331', '--dateafter', '20220307', 'https://tv.gab.com/channel/realredelephants']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (pip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-122-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [generic] Extracting URL: https://tv.gab.com/channel/realredelephants
[generic] realredelephants: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] realredelephants: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://tv.gab.com/channel/realredelephants
Traceback (most recent call last):
  File "/home/halvor/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1441, in wrapper
    return func(self, *args, **kwargs)
  File "/home/halvor/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1517, in __extract_info
    ie_result = ie.extract(url)
  File "/home/halvor/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/home/halvor/.local/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 3077, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tv.gab.com/channel/realredelephants

```
