### ISSUE TITLE
downloading subtitles from the website iQIYI

### ISSUE THREAD

**Issue by D-LUFFY89** [yt-dlp/yt-dlp#346]
Please support downloading subtitles from the website  iQIYI 
https://www.iq.com/movie
The site is free. You can watch videos for free 

C:\Users\ydl\youtube-dl\youtube-dl.exe : [debug] Command-line config: ['-F', '-v', 
'https://www.iq.com/play/11x8q7uvti8']
At line:1 char:1
C:\Users\ydl\youtube-dl\youtube-dl.exe -F -v  https: ...
CategoryInfo          : NotSpecified: ([debug] Command...y/11x8q7uvti8']:String) [], RemoteException
FullyQualifiedErrorId : NativeCommandError
 
[debug] Encodings: locale cp1256, fs utf-8, out cp1256, pref cp1256
[debug] yt-dlp version 2021.05.20 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-101352-g0e645b98c6
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.iq.com/play/11x8q7uvti8
[generic] 11x8q7uvti8: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 11x8q7uvti8: Downloading webpage
[generic] 11x8q7uvti8: Extracting information
ERROR: Unsupported URL: https://www.iq.com/play/11x8q7uvti8
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1126, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1147, in __extract_info
  File "yt_dlp\extractor\common.py", line 564, in extract
  File "yt_dlp\extractor\generic.py", line 3573, in _real_extract

## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running yt-dlp version **2021.05.20**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

WRITE DESCRIPTION HERE

**Comment by Ashish0804** [comment]
1. Do not skip the template.
2. The title implies downloading video works but not subtitles which is wrong since this site doesn't have an extractor yet.

Open a Site support request for this.

**Comment by pukkandan** [comment]
closing due to inactivity
