### ISSUE TITLE
[feature] '-f b' doesn't work with reddit videos

### ISSUE THREAD

**Issue by JabSYsEmb** [yt-dlp/yt-dlp#3464]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Turkey

### Example URLs

https://www.reddit.com/r/Unexpected/comments/u5oboc/measure_twice_cut_once/
https://www.reddit.com/r/PublicFreakout/comments/u5ih0u/palestinian_child_panics_while_israeli_forces_are/

### Description

`yt-dlp -f b www.reddit.com/*` isn't able find the best video resolution and download it neither `yt-dlp -f best www.reddit.com` works.

### Verbose log

```shell
➜  yt-dlp -F https://www.reddit.com/r/Unexpected/comments/u5oboc/measure_twice_cut_once/
[Reddit] u5oboc: Downloading JSON metadata
[Reddit] u5oboc: Downloading m3u8 information
[Reddit] u5oboc: Downloading MPD manifest
[info] Available formats for ugpuw6cro3u81:
ID                  EXT RESOLUTION FPS │   FILESIZE  TBR PROTO  │ VCODEC       VBR ACODEC      ABR     ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-0-audio_0       mp4 audio only     │                 m3u8_n │ audio only       unknown                 audio 0
hls-1-audio_0       mp4 audio only     │                 m3u8_n │ audio only       unknown                 audio 0
dash-audio_0_131733 m4a audio only     │ ~477.53KiB 131k https  │ audio only       mp4a.40.2  131k 48000Hz DASH audio, m4a_dash
hls-349             mp4 400x226        │ ~  1.24MiB 349k m3u8_n │ avc1.42001e 349k video only
hls-445             mp4 400x226        │ ~  1.58MiB 445k m3u8_n │ avc1.42001e 445k video only
dash-video_602929   mp4 424x240     30 │ ~  2.13MiB 602k https  │ avc1.4D401E 602k video only              DASH video, mp4_dash
hls-549             mp4 480x272        │ ~  1.94MiB 549k m3u8_n │ avc1.42001e 549k video only
hls-645             mp4 480x272        │ ~  2.28MiB 645k m3u8_n │ avc1.42001e 645k video only
dash-video_793564   mp4 636x360     30 │ ~  2.81MiB 793k https  │ avc1.4D401E 793k video only              DASH video, mp4_dash
➜  yt-dlp -vU -f b https://www.reddit.com/r/Unexpected/comments/u5oboc/measure_twice_cut_once/
[debug] Command-line config: ['-vU', '-f', 'b', 'https://www.reddit.com/r/Unexpected/comments/u5oboc/measure_twice_cut_once/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.9.8 (CPython 64bit) - macOS-12.3.1-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [Reddit] Extracting URL: https://www.reddit.com/r/Unexpected/comments/u5oboc/measure_twice_cut_once/
[Reddit] u5oboc: Downloading JSON metadata
[Reddit] u5oboc: Downloading m3u8 information
[Reddit] u5oboc: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [Reddit] ugpuw6cro3u81: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/Users/$USER/Downloads/./yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/$USER/Downloads/./yt-dlp/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/$USER/Downloads/./yt-dlp/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/$USER/Downloads/./yt-dlp/yt_dlp/YoutubeDL.py", line 2630, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [Reddit] ugpuw6cro3u81: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by pukkandan** [comment]
```
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         ...
```
