### ISSUE TITLE
Error since commit 43cc91a

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#3467]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

After commit 43cc91a, I get the error shown in the verbose log.

### Verbose log

```shell
yt-dlp -Uv
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 13, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 12, in <module>
ModuleNotFoundError: No module named 'yt_dlp.compat'
```

**Comment by nicolaasjan** [comment]
Or:

```
python __init__.py -Uv
Traceback (most recent call last):
  File "__init__.py", line 12, in <module>
    from .compat import compat_getpass, compat_os_name, compat_shlex_quote
ImportError: attempted relative import with no known parent package
```

**Comment by pukkandan** [comment]
This works, but is ugly and hard to maintain in future. Can anyone who's better at `sh` help?
```diff
diff --git a/Makefile b/Makefile
index b030dc3b5..777dced65 100644
--- a/Makefile
+++ b/Makefile
@@ -61,7 +61,7 @@ offlinetest: codetest

 yt-dlp: yt_dlp/*.py yt_dlp/*/*.py
        mkdir -p zip
-       for d in yt_dlp yt_dlp/downloader yt_dlp/extractor yt_dlp/postprocessor ; do \
+       for d in yt_dlp yt_dlp/downloader yt_dlp/extractor yt_dlp/postprocessor yt_dlp/compat yt_dlp/compat/asyncio ; do \
          mkdir -p zip/$$d ;\
          cp -pPR $$d/*.py zip/$$d/ ;\
        done
```

**Comment by pukkandan** [comment]
There is some issue in the make file. I thought this would work, but it doesnt. I have no clue why and need help

```diff
diff --git a/Makefile b/Makefile
index b030dc3b5..777dced65 100644
--- a/Makefile
+++ b/Makefile
@@ -61,7 +61,7 @@ offlinetest: codetest

 yt-dlp: yt_dlp/*.py yt_dlp/*/*.py
        mkdir -p zip
-       for d in yt_dlp yt_dlp/downloader yt_dlp/extractor yt_dlp/postprocessor ; do \
+       for d in yt_dlp yt_dlp/downloader yt_dlp/extractor yt_dlp/postprocessor yt_dlp/compat yt_dlp/compat/asyncio ; do \
          mkdir -p zip/$$d ;\
          cp -pPR $$d/*.py zip/$$d/ ;\
        done
```

**Comment by putnam** [comment]
The Makefile kind of looks like it needs a total rewrite, but this will fix it:

```diff
diff --git a/Makefile b/Makefile
index b6cb27bb0..8ae580473 100644
--- a/Makefile
+++ b/Makefile
@@ -59,15 +59,15 @@ test:
 offlinetest: codetest
        $(PYTHON) -m pytest -k "not download"
 
-yt-dlp: yt_dlp/*.py yt_dlp/*/*.py
+yt-dlp: yt_dlp/*.py yt_dlp/*/*.py yt_dlp/*/*/*.py
        mkdir -p zip
-       for d in yt_dlp yt_dlp/downloader yt_dlp/extractor yt_dlp/postprocessor ; do \
+       for d in yt_dlp yt_dlp/downloader yt_dlp/extractor yt_dlp/postprocessor yt_dlp/compat yt_dlp/compat/asyncio ; do \
          mkdir -p zip/$$d ;\
          cp -pPR $$d/*.py zip/$$d/ ;\
        done
        touch -t 200001010101 zip/yt_dlp/*.py zip/yt_dlp/*/*.py
        mv zip/yt_dlp/__main__.py zip/
-       cd zip ; zip -q ../yt-dlp yt_dlp/*.py yt_dlp/*/*.py __main__.py
+       cd zip ; zip -q ../yt-dlp yt_dlp/*.py yt_dlp/*/*.py yt_dlp/*/*/*.py __main__.py
        rm -rf zip
        echo '#!$(PYTHON)' > yt-dlp
        cat yt-dlp.zip >> yt-dlp
```

**Comment by pukkandan** [comment]
> The Makefile kind of looks like it needs a total rewrite, 

A PR would be welcome
