### ISSUE TITLE
[openrec] cannot download limited (paid) movie

### ISSUE THREAD

**Issue by fireattack** [yt-dlp/yt-dlp#3474]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Global

### Description

Downloading for archived live (`/live/`) works (fixed by @Lesmiscore at #3252), but it seems it doesn't work for limited (ones that need sub) `/movie/`s.

I'm trying to download `https://www.openrec.tv/movie/lv81dn0o289`.
The return value of `https://apiv5.openrec.tv/api/v5/movies/lv81dn0o289/detail` is attached below. 
If an account is needed for investigation, please let me know. I can provide one.

```json
{
    "status": 0,
    "data": {
        "type": "movie_detail",
        "items": [
            {
                "media": {
                    "url": "https://dco4urblvsasc.cloudfront.net/25471/2547093_EWXTEoUl/game/index.m3u8",
                    "url_source": null,
                    "url_public": null,
                    "url_low_latency": null,
                    "url_ull": null,
                    "url_dvr": null,
                    "url_trailer": null,
                    "url_audio": "https://dco4urblvsasc.cloudfront.net/25471/2547093_EWXTEoUl/game/aac.m3u8",
                    "url_dvr_audio": null
                },
                "subs_trial_media": {
                    "url": null,
                    "url_low_latency": null,
                    "url_ull": null,
                    "url_dvr": null,
                    "url_audio": null,
                    "url_dvr_audio": null
                },
                "membership": {
                    ...
                },
                "exceeds_device_limit": false,
                "casts": [],
                "test_component_extensions": [],
                "test_overlay_extensions": [],
                "test_panel_extensions": [],
                "test_mobile_component_extensions": []
            }
        ]
    }
}
```

### Verbose log

```shell
E:\!DL\openrec>yt-dlp --cookies-from-browser "chrome:profile 3" https://www.openrec.tv/movie/lv81dn0o289 -vU --ignore-config
[debug] Command-line config: ['--cookies-from-browser', 'chrome:profile 3', 'https://www.openrec.tv/movie/lv81dn0o289', '-vU', '--ignore-config']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\***\AppData\Local\Google\Chrome\User Data\profile 3\Network\Cookies"
[Cookies] Extracted 1312 cookies from chrome
[debug] cookie version breakdown: {'v10': 1312, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp936, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp936
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-01-17-git-dcc9454ab9-full_build-www.gyan.dev (setts), ffprobe 2022-01-17-git-dcc9454ab9-full_build-www.gyan.dev, rtmpdump 2.3
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [openrec:movie] Extracting URL: https://www.openrec.tv/movie/lv81dn0o289
[openrec:movie] lv81dn0o289: Downloading webpage
ERROR: [openrec:movie] lv81dn0o289: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2487, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 981, in raise_no_formats
yt_dlp.utils.ExtractorError: [openrec:movie] lv81dn0o289: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by fireattack** [comment]
Yeah, it works!

```
G:\_temp\yt-dlp>py -m yt_dlp --cookies-from-browser "chrome:profile 3" https://www.openrec.tv/movie/lv81dn0o289 -vU --ignore-config
[debug] Command-line config: ['--cookies-from-browser', 'chrome:profile 3', 'https://www.openrec.tv/movie/lv81dn0o289', '-vU', '--ignore-config']
[debug] Encodings: locale cp936, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp936
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 43cc91ad7
[debug] Python version 3.8.7 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-01-17-git-dcc9454ab9-full_build-www.gyan.dev (setts), ffprobe 2022-01-17-git-dcc9454ab9-full_build-www.gyan.dev, rtmpdump 2.3
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\***\AppData\Local\Google\Chrome\User Data\profile 3\Network\Cookies"
[debug] Found local state file at "C:\Users\***\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 1311 cookies from chrome
[debug] cookie version breakdown: {'v10': 1311, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [openrec:movie] Extracting URL: https://www.openrec.tv/movie/lv81dn0o289
[openrec:movie] lv81dn0o289: Downloading webpage
[openrec:movie] lv81dn0o289: Downloading JSON metadata
[openrec:movie] lv81dn0o289: Downloading m3u8 information
[openrec:movie] lv81dn0o289: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] lv81dn0o289: Downloading 1 format(s): url_audio-2691
[debug] Invoking downloader on "https://dco4urblvsasc.cloudfront.net/25471/2547093_EWXTEoUl/game/96kbps.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 143
[download] Destination: セカショゲーム部#1「DbD」後編 [lv81dn0o289].mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[download]   0.7% of ~290.28MiB at  1.17MiB/s ETA 04:05 (frag 1/143)
ERROR: Interrupted by user
```
