### ISSUE TITLE
FreeTV (freetv.com)

### ISSUE THREAD

**Issue by tripod3d** [yt-dlp/yt-dlp#3486]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Estados Unidos, Puerto Rico, Argentina, Bolivia, Chile, Colombia, Costa Rica, Ecuador, El Salvador, Guatemala, Honduras, México, Nicaragua, Panamá, Paraguay, Perú, República Dominicana, Uruguay, Venezuela

### Example URLs

- Single video: https://www.freetv.com/peliculas/atrapame-si-puedes/

### Description

Site uses WordPress as CMS for the entire site, but player is an iframe.

### Verbose log

```shell
% yt-dlp -vU https://www.freetv.com/peliculas/atrapame-si-puedes/
[debug] Command-line config: ['-vU', 'https://www.freetv.com/peliculas/atrapame-si-puedes/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.10.87-1-lts-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://www.freetv.com/peliculas/atrapame-si-puedes/
[generic] atrapame-si-puedes: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] atrapame-si-puedes: Downloading webpage
[generic] atrapame-si-puedes: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.freetv.com/peliculas/atrapame-si-puedes/
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.freetv.com/peliculas/atrapame-si-puedes/
```

**Comment by elyse0** [comment]
I've looked into this and it seems like we need HTTP/2 but we only have support for HTTP1.1. 

I tried changing the User-Agent, as this [comment](https://github.com/yt-dlp/yt-dlp/issues/2396#issuecomment-1024693628) suggested, but it didn't work.

### Request

```http
POST /wordpress/wp-admin/admin-ajax.php HTTP/2
Host: www.freetv.com
Cookie: _ga=GA1.2.1514958466.1651120367; _gid=GA1.2.1719359073.1651120367; dnt=0; uniqueID=2PcJB1fsRxMjI0wINQL0lyYfYtYaro3x; bitmovin_analytics_uuid=aa995e28-4cbc-4152-886e-0114ae438100; _gat_gtag_UA_85535093_2=1; _gat_gtag_UA_138579418_3=1
Content-Length: 116
Sec-Ch-Ua: "(Not(A:Brand";v="8", "Chromium";v="100"
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Sec-Ch-Ua-Platform: "Linux"
Origin: https://www.freetv.com
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://www.freetv.com/peliculas/atrapame-si-puedes/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

action=olyott_video_play&contentID=428021&videoType=video&data%5BcontentID%5D=428021&data%5BeventType%5D=video_start
```

### Response

```http
HTTP/2 200 OK
Date: Thu, 28 Apr 2022 04:38:24 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 6902
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Robots-Tag: noindex
X-Content-Type-Options: nosniff
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
X-Frame-Options: SAMEORIGIN
Referrer-Policy: no-referrer-when-downgrade
Vary: Accept-Encoding
X-Xss-Protection: 1; mode=block
Content-Security-Policy: default-src 'self' 'unsafe-eval' 'unsafe-inline' data: blob: *
Feature-Policy: autoplay 'self';sync-xhr 'self'

{
   "success":true,
   "data":{
      "displayMeta":{
         "contentID":"428021",
         "contentType":"Video",
         "title":"Atr\u00e1pame Si Puedes",
         "titleCode":"MASPUE1",
         "desc":"Basada en una historia real. La fascinante historia de Frank Abagnale Jr., un joven y escurridizo delincuente que adoptaba diversas...",
         "isParentalControlled":false,
         "ads":{
            "client":"vast",
            "schedule":[
               {
                  "timestamp":"",
                  "seconds":"",
                  "tag":"https:\/\/pod.bfmio.com\/adpod\/af17ccaa-4c76-4a18-8a32-be0d5a7112c6?w=1920&h=1080&cb=1651120704626a1a4045e3a&boxing=1&ua=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F100.0.4896.127%20Safari%2F537.36&ip=189.189.149.125&type=pre&coppa=0&page=https%3A%2F%2Fwww.freetv.com%2Fpeliculas%2Fatrapame-si-puedes%2F&app=FreeTV&c_id=MASPUE1&c_title=Atr%C3%A1pame%20Si%20Puedes&c_category=IAB324,IAB640&c_genre=Drama,Suspenso,Comedia&c_duration=8160&c_lang=es&c_live=0&pod_duration=33&max_slots=1",
                  "position":"preroll"
               },
               {
                  "timestamp":"00:14:01",
                  "seconds":841,
                  "tag":"https:\/\/pod.bfmio.com\/adpod\/af17ccaa-4c76-4a18-8a32-be0d5a7112c6?w=1920&h=1080&cb=1651120704626a1a4045f44&boxing=1&ua=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F100.0.4896.127%20Safari%2F537.36&ip=189.189.149.125&type=mid&coppa=0&page=https%3A%2F%2Fwww.freetv.com%2Fpeliculas%2Fatrapame-si-puedes%2F&app=FreeTV&c_id=MASPUE1&c_title=Atr%C3%A1pame%20Si%20Puedes&c_category=IAB324,IAB640&c_genre=Drama,Suspenso,Comedia&c_duration=8160&c_lang=es&c_live=0",
                  "position":"midroll"
               },
               {
                  "timestamp":"00:28:53",
                  "seconds":1733,
                  "tag":"https:\/\/pod.bfmio.com\/adpod\/af17ccaa-4c76-4a18-8a32-be0d5a7112c6?w=1920&h=1080&cb=1651120704626a1a404601b&boxing=1&ua=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F100.0.4896.127%20Safari%2F537.36&ip=189.189.149.125&type=mid&coppa=0&page=https%3A%2F%2Fwww.freetv.com%2Fpeliculas%2Fatrapame-si-puedes%2F&app=FreeTV&c_id=MASPUE1&c_title=Atr%C3%A1pame%20Si%20Puedes&c_category=IAB324,IAB640&c_genre=Drama,Suspenso,Comedia&c_duration=8160&c_lang=es&c_live=0",
                  "position":"midroll"
               },
               {
                  "timestamp":"00:42:37",
                  "seconds":2557,
                  "tag":"https:\/\/pod.bfmio.com\/adpod\/af17ccaa-4c76-4a18-8a32-be0d5a7112c6?w=1920&h=1080&cb=1651120704626a1a40460f2&boxing=1&ua=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F100.0.4896.127%20Safari%2F537.36&ip=189.189.149.125&type=mid&coppa=0&page=https%3A%2F%2Fwww.freetv.com%2Fpeliculas%2Fatrapame-si-puedes%2F&app=FreeTV&c_id=MASPUE1&c_title=Atr%C3%A1pame%20Si%20Puedes&c_category=IAB324,IAB640&c_genre=Drama,Suspenso,Comedia&c_duration=8160&c_lang=es&c_live=0",
                  "position":"midroll"
               },
               {
                  "timestamp":"00:55:46",
                  "seconds":3346,
                  "tag":"https:\/\/pod.bfmio.com\/adpod\/af17ccaa-4c76-4a18-8a32-be0d5a7112c6?w=1920&h=1080&cb=1651120704626a1a40461be&boxing=1&ua=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F100.0.4896.127%20Safari%2F537.36&ip=189.189.149.125&type=mid&coppa=0&page=https%3A%2F%2Fwww.freetv.com%2Fpeliculas%2Fatrapame-si-puedes%2F&app=FreeTV&c_id=MASPUE1&c_title=Atr%C3%A1pame%20Si%20Puedes&c_category=IAB324,IAB640&c_genre=Drama,Suspenso,Comedia&c_duration=8160&c_lang=es&c_live=0",
                  "position":"midroll"
               },
               {
                  "timestamp":"01:09:58",
                  "seconds":4198,
                  "tag":"https:\/\/pod.bfmio.com\/adpod\/af17ccaa-4c76-4a18-8a32-be0d5a7112c6?w=1920&h=1080&cb=1651120704626a1a4046292&boxing=1&ua=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F100.0.4896.127%20Safari%2F537.36&ip=189.189.149.125&type=mid&coppa=0&page=https%3A%2F%2Fwww.freetv.com%2Fpeliculas%2Fatrapame-si-puedes%2F&app=FreeTV&c_id=MASPUE1&c_title=Atr%C3%A1pame%20Si%20Puedes&c_category=IAB324,IAB640&c_genre=Drama,Suspenso,Comedia&c_duration=8160&c_lang=es&c_live=0",
                  "position":"midroll"
               },
               {
                  "timestamp":"01:25:02",
                  "seconds":5102,
                  "tag":"https:\/\/pod.bfmio.com\/adpod\/af17ccaa-4c76-4a18-8a32-be0d5a7112c6?w=1920&h=1080&cb=1651120704626a1a4046361&boxing=1&ua=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F100.0.4896.127%20Safari%2F537.36&ip=189.189.149.125&type=mid&coppa=0&page=https%3A%2F%2Fwww.freetv.com%2Fpeliculas%2Fatrapame-si-puedes%2F&app=FreeTV&c_id=MASPUE1&c_title=Atr%C3%A1pame%20Si%20Puedes&c_category=IAB324,IAB640&c_genre=Drama,Suspenso,Comedia&c_duration=8160&c_lang=es&c_live=0",
                  "position":"midroll"
               },
               {
                  "timestamp":"01:38:17",
                  "seconds":5897,
                  "tag":"https:\/\/pod.bfmio.com\/adpod\/af17ccaa-4c76-4a18-8a32-be0d5a7112c6?w=1920&h=1080&cb=1651120704626a1a404642b&boxing=1&ua=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F100.0.4896.127%20Safari%2F537.36&ip=189.189.149.125&type=mid&coppa=0&page=https%3A%2F%2Fwww.freetv.com%2Fpeliculas%2Fatrapame-si-puedes%2F&app=FreeTV&c_id=MASPUE1&c_title=Atr%C3%A1pame%20Si%20Puedes&c_category=IAB324,IAB640&c_genre=Drama,Suspenso,Comedia&c_duration=8160&c_lang=es&c_live=0",
                  "position":"midroll"
               },
               {
                  "timestamp":"01:51:10",
                  "seconds":6670,
                  "tag":"https:\/\/pod.bfmio.com\/adpod\/af17ccaa-4c76-4a18-8a32-be0d5a7112c6?w=1920&h=1080&cb=1651120704626a1a40464f1&boxing=1&ua=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F100.0.4896.127%20Safari%2F537.36&ip=189.189.149.125&type=mid&coppa=0&page=https%3A%2F%2Fwww.freetv.com%2Fpeliculas%2Fatrapame-si-puedes%2F&app=FreeTV&c_id=MASPUE1&c_title=Atr%C3%A1pame%20Si%20Puedes&c_category=IAB324,IAB640&c_genre=Drama,Suspenso,Comedia&c_duration=8160&c_lang=es&c_live=0",
                  "position":"midroll"
               },
               {
                  "timestamp":"02:03:50",
                  "seconds":7430,
                  "tag":"https:\/\/pod.bfmio.com\/adpod\/af17ccaa-4c76-4a18-8a32-be0d5a7112c6?w=1920&h=1080&cb=1651120704626a1a40465cf&boxing=1&ua=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F100.0.4896.127%20Safari%2F537.36&ip=189.189.149.125&type=mid&coppa=0&page=https%3A%2F%2Fwww.freetv.com%2Fpeliculas%2Fatrapame-si-puedes%2F&app=FreeTV&c_id=MASPUE1&c_title=Atr%C3%A1pame%20Si%20Puedes&c_category=IAB324,IAB640&c_genre=Drama,Suspenso,Comedia&c_duration=8160&c_lang=es&c_live=0",
                  "position":"midroll"
               }
            ]
         },
         "hasAdsEnabled":true,
         "hasReachedStreamLimit":false,
         "fullTitle":"Atr\u00e1pame Si Puedes",
         "drm":"{}",
         "closedCaptions":false,
         "streamURLVideo":"https:\/\/olympusato-mmd-cust.lldns.net\/stream.ismd\/manifest.m3u8?stream=\/XH\/N5ehbEFW48KQLMK_NpF0IDTM90KQ0jiWAD_3uuQZI\/maspue1;\/zk\/XwXuxt7Jfz391mYRtP-9_biMKBgkgM4IL1uzEsXzQ\/maspue1;\/dE\/C1IDEBbZu6A2iYezyLhGL-WGPXTWhKof0MxsaNSQw\/maspue1;\/pc\/Na16bSbb-syDxvGQVlBD6XOcNY5Agbote_3rLh11M\/maspue1"
      }
   }
}
```

**Comment by coletdjnz** [comment]
I disabled HTTP/2 in Firefox and it works on HTTP/1.1 :confused: 

If we really need HTTP/2 for extractor requests then it'll prob require #2861 with a httpx adapter.

**Comment by elyse0** [comment]
😮 😮  you're right

I was testing it with Postman and it really didn't work. Now I've tried another program, and it works o-O

![image](https://user-images.githubusercontent.com/26639800/165698651-856b7902-0370-4153-85eb-e6701d362d47.png)

Forgive me 😅
