### ISSUE TITLE
[Broken] Thumbnail error if both playlist title and video title contains a "%". 

### ISSUE THREAD

**Issue by Punpki** [yt-dlp/yt-dlp#352]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.05.20**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp --verbose --abort-on-error --embed-thumbnail --output "%(playlist_title)s/%(playlist_index)02d - %(title)s [%(id)s]" https://www.youtube.com/playlist?list=PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF
[debug] Command-line config: ['--verbose', '--abort-on-error', '--embed-thumbnail', '--output', '%(playlist_title)s/%(playlist_index)02d - %(title)s [%(id)s]', 'https://www.youtube.com/playlist?list=PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.05.20 (zip)
[debug] Python version 3.8.6 (CPython 64bit) - Linux-5.11.0-7614-generic-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF
[youtube:tab] PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF
[youtube:tab] PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF: Downloading API JSON with unavailable videos
[download] Downloading playlist: Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD
[youtube:tab] PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF: Downloading thumbnail  ...
WARNING: Unable to download thumbnail "https://i.ytimg.com/vi/vcZNjSw5Sf4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDRAvpoTYg7ybBkTVP6VD06S2nLWQ": [Errno 2] No such file or directory: 'Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/00 - Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD [PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF].jpg'
[youtube:tab] PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF: Downloading thumbnail  ...
WARNING: Unable to download thumbnail "https://i.ytimg.com/vi/vcZNjSw5Sf4/hqdefault.jpg?sqp=-oaymwEXCPYBEIoBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCmcPXWjw4Kej6dEZeRFpkBgXkyog": [Errno 2] No such file or directory: 'Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/00 - Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD [PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF].jpg'
[youtube:tab] PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF: Downloading thumbnail  ...
WARNING: Unable to download thumbnail "https://i.ytimg.com/vi/vcZNjSw5Sf4/hqdefault.jpg?sqp=-oaymwEWCMQBEG5IWvKriqkDCQgBFQAAiEIYAQ==&rs=AOn4CLDjV_TtgtyGjFPOXhGgHhX757TDQA": [Errno 2] No such file or directory: 'Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/00 - Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD [PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF].jpg'
[youtube:tab] PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF: Downloading thumbnail  ...
WARNING: Unable to download thumbnail "https://i.ytimg.com/vi/vcZNjSw5Sf4/hqdefault.jpg?sqp=-oaymwEWCKgBEF5IWvKriqkDCQgBFQAAiEIYAQ==&rs=AOn4CLB2pfwAfP_8GCQ1gjoxmTC2GjI_GA": [Errno 2] No such file or directory: 'Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/00 - Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD [PLkBK2hrDcB5se4k7r7716jphBFWNXTaNF].jpg'
[youtube:tab] playlist Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD: Downloading 27 videos
[download] Downloading video 1 of 27
[debug] [youtube] Extracting URL: vcZNjSw5Sf4
[youtube] vcZNjSw5Sf4: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] vcZNjSw5Sf4: Downloading 1 format(s): 308+251
[youtube] vcZNjSw5Sf4: Downloading thumbnail  ...
[youtube] vcZNjSw5Sf4: Writing thumbnail to: Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100% Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].webp
WARNING: webm doesn't support embedding a thumbnail, mkv will be used.
[debug] Invoking downloader on 'https://r4---sn-uxap5nvoxg5-j2is.googlevideo.com/videoplayback?expire=1622219498&ei=isawYJqvE4LpyQX_ypw4&ip=&id=o-ABOfTg2V6o3wviKJysY_9aGAMLA1LungbMfLv8lb-fRy&itag=308&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308&source=youtube&requiressl=yes&mh=ig&mm=31%2C29&mn=sn-uxap5nvoxg5-j2is%2Csn-5goeen7r&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=24&initcwndbps=1691250&vprv=1&mime=video%2Fwebm&ns=dbcLqD_xrzlHEHTthUJCbOIF&gir=yes&clen=594279302&dur=532.183&lmt=1602630713339620&mt=1622197724&fvip=4&keepalive=yes&fexp=24001373%2C24007246&beids=9466585&c=WEB&txp=6316222&n=mpNJwpdQlaE8pKHv0I&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgChRtsbzvRFYbYrAF0LRSXaOw_yioiAaNUzM6qGb4NqACIQDIGjqajXZaJ9VqsUheseKXh4PXPqvX9mhJPCxISes9sg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXos4Yr8EukEDVgvDmihPXDW4ilTRI3Tp04GZngnGe6UCIHhi6rdkbyP1pnamE_Xlc5Gr2njPoKXtyCsxeEVhARVM'
[download] Destination: Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100% Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].f308
[download] 100% of 566.75MiB in 01:10
[debug] Invoking downloader on 'https://r4---sn-uxap5nvoxg5-j2is.googlevideo.com/videoplayback?expire=1622219498&ei=isawYJqvE4LpyQX_ypw4&ip=&id=o-ABOfTg2V6o3wviKJysY_9aGAMLA1LungbMfLv8lb-fRy&itag=251&source=youtube&requiressl=yes&mh=ig&mm=31%2C29&mn=sn-uxap5nvoxg5-j2is%2Csn-5goeen7r&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=24&initcwndbps=1691250&vprv=1&mime=audio%2Fwebm&ns=dbcLqD_xrzlHEHTthUJCbOIF&gir=yes&clen=8084751&dur=532.201&lmt=1602630713334675&mt=1622197724&fvip=4&keepalive=yes&fexp=24001373%2C24007246&beids=9466585&c=WEB&txp=6311222&n=mpNJwpdQlaE8pKHv0I&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgO2jHuTrcKeZlIlEfqnpaYUywBcIwLD3_4dmNvjnNS3ACIQCpUU_FwVkj45g1JDIk4mvpGG2dQx5riP4lJxTZffy34A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXos4Yr8EukEDVgvDmihPXDW4ilTRI3Tp04GZngnGe6UCIHhi6rdkbyP1pnamE_Xlc5Gr2njPoKXtyCsxeEVhARVM'
[download] Destination: Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100% Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].f251
[download] 100% of 7.71MiB in 00:00
[Merger] Merging formats into "Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100% Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100% Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].f308' -i 'file:Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100% Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].f251' -c copy -map 0:v:0 -map 1:a:0 'file:Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100% Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].temp.mkv'
Deleting original file Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100% Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].f251 (pass -k to keep)
Deleting original file Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100% Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].f308 (pass -k to keep)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 689, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 679, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2725, in download
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1119, in extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1126, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1158, in __extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1257, in process_ie_result
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1460, in __process_playlist
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1126, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1475, in __process_iterable_entry
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1209, in process_ie_result
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1119, in extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1126, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1158, in __extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1190, in process_ie_result
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2165, in process_video_result
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2695, in process_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2834, in post_process
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2783, in run_pp
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/embedthumbnail.py", line 83, in run
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 857, in convert_thumbnail
FileNotFoundError: [Errno 2] No such file or directory: 'Zelda Twilight Princess HD Longplay Walkthrough 100% No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100% Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].webp' -> 'Zelda Twilight Princess HD Longplay Walkthrough 100# No Commentary 60FPS No-HUD/01 - Zelda Twilight Princess HD No Hud 60fps - 100# Walkthrough Longplay - Part 1 - Introduction [vcZNjSw5Sf4].webp'


```

## Description

Downloading playlists that have a "%" in both the playlist title and video title makes the program fail to embed the thumbnail. 
When I chose a custom name for the playlist without "%", it worked perfectly. 

Is there any way to escape the percent sign automatically?
I want to keep the output template like it is for easier sorting.

**Comment by pukkandan** [comment]
The `%` is converted to `#` by https://github.com/ytdl-org/youtube-dl/commit/bff857a8af696e701482208617bf0b7564951326. The issue is that when it does, `folder with %/file with %.ext` is renamed to `folder with #/file with #.ext`, but `folder with #` doesn't exist causing the `OSError`

**Comment by Punpki** [comment]
Oh, I see. In that case, would it be possible to maybe replace the "%" with an underscore directly?  For example, writing the output field like this: "%(playlist_title/%)s" would result in replacing every "%" in the title with an underscore. Would that be possible?

**Comment by Punpki** [comment]
Thank you for the fix! Fantastic work
