### ISSUE TITLE
ResourceWarning: unclosed file

### ISSUE THREAD

**Issue by P-reducible** [yt-dlp/yt-dlp#3531]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

A timeout seems to be causing this. See the first line in the log.

### Verbose log

```shell
ERROR: unable to download video data: The read operation timed out
Exception ignored in: <_io.FileIO name=7 mode='wb' closefd=True>
Traceback (most recent call last):
  File "YoutubeDL.py", line 3123, in process_info
    return
ResourceWarning: unclosed file <_io.BufferedWriter name=7>
Exception ignored in: <_io.FileIO name=3 mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name=3>
```

**Comment by pukkandan** [comment]
Show ENTIRE verbose log!

**Comment by P-reducible** [comment]
The bug has a sporadic nature, so it's not easily reproducible. Unfortunately, I didn't have `--verbose` enabled. The way to try to reproduce the bug is by running `>=10` `yt-dlp` sessions in parallel in the hope that some of them time out.

**Comment by pukkandan** [comment]
Atleast tell us what command you are running, and show the verbose head

**Comment by P-reducible** [comment]
E.g.

```
yt-dlp.sh --verbose --socket-timeout 300 -N 2 -s https://rokfin.com/post/82706/Sanctions--the-End-of-a-Financial-Era-with-John-Titus 
[debug] Command-line config: ['--verbose', '--socket-timeout', '300', '-N', '2', '-s', 'https://rokfin.com/post/82706/Sanctions--the-End-of-a-Financial-Era-with-John-Titus']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 4e56ac336
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.26-gentoo-x86_64-Intel-R-_Core-TM-_i7-4710MQ_CPU_@_2.50GHz-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: certifi, sqlite3
[debug] Proxy map: {}
[debug] [Rokfin] Extracting URL: https://rokfin.com/post/82706/Sanctions--the-End-of-a-Financial-Era-with-John-Titus
[Rokfin] post/82706: Downloading webpage
[Rokfin] post/82706: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] post/82706: Downloading 1 format(s): 298
```

**Comment by pukkandan** [comment]
Unable to reproduce. Can re-open if you are able to provide verbose log of the failure

**Comment by captn3m0** [comment]
Here's the same failure with a verbose log, albeit with a WIP extractor:

```
./yt-dlp.sh --verbose "https://gaana.com/song/mera-dil-bhi-kitna-pagal-hai-1" -f best
[debug] Command-line config: ['--verbose', 'https://gaana.com/song/mera-dil-bhi-kitna-pagal-hai-1', '-f', 'best']
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: c7ef3b450
[debug] Python version 3.10.5 (CPython 64bit) - Linux-5.17.9-arch1-1-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2021.10.08, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [gaana] Extracting URL: https://gaana.com/song/mera-dil-bhi-kitna-pagal-hai-1
[gaana:song] mera-dil-bhi-kitna-pagal-hai-1: Downloading webpage
[gaana:song] 14776067: Downloading webpage
[gaana:song] 14776067: Downloading webpage
[gaana:song] 14776067: Downloading webpage
{'id': '14776067', 'title': 'Mera Dil Bhi Kitna Pagal Hai', 'duration': 326, 'formats': [{'url': 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_16.mp4/index.m3u8?sign=1655284573-znGumJK0BN-0-af5f0a87232dd704c3da52c930a8adef', 'format_id': 'normal', 'ext': 'm4a', 'abr': None, 'format_note': 'mp4-aac'}, {'url': 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_64.mp4/index.m3u8?sign=1655284573-Z7zCX2jmpq-0-35d6363de4a48455eb603e68cae38354', 'format_id': 'medium', 'ext': 'm4a', 'abr': 64, 'format_note': 'mp4-aac'}, {'url': 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/index.m3u8?sign=1655284573-8LuwR9fKIw-0-5b1116e7d74fb08cc7f21b275d01b244', 'format_id': 'high', 'ext': 'm4a', 'abr': 96, 'format_note': 'mp4-aac'}], 'album': 'Saajan', 'thumbnail': 'https://a10.gaanacdn.com/gn_img/albums/a7LWBaz3zX/7LWBexGR3z/size_l.jpg', 'artist': 'Kumar Sanu, Alka Yagnik', 'release_date': '1993-06-20', 'language': 'Hindi'}
[info] 14776067: Downloading 1 format(s): high
[debug] Invoking f_fmpeg downloader on "https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/index.m3u8?sign=1655284573-8LuwR9fKIw-0-5b1116e7d74fb08cc7f21b275d01b244"
[download] Destination: Mera Dil Bhi Kitna Pagal Hai [14776067].m4a
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.43 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -i 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/index.m3u8?sign=1655284573-8LuwR9fKIw-0-5b1116e7d74fb08cc7f21b275d01b244' -c copy -f mp4 'file:Mera Dil Bhi Kitna Pagal Hai [14776067].m4a.part'
ffmpeg version n5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[tcp @ 0x555937c575c0] Starting connection attempt to 23.248.167.90 port 443
[tcp @ 0x555937c575c0] Starting connection attempt to 23.248.167.151 port 443
[tcp @ 0x555937c575c0] Successfully connected to 23.248.167.90 port 443
[hls @ 0x555937c53640] Skip ('#EXT-X-VERSION:3')
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/0.ts?sign=1655284573-8LuwR9fKIw-0-21164f0698acf9adbde4d92fbaee14a6', offset 0, playlist 0
[hls @ 0x555937c53640] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/0.ts?sign=1655284573-8LuwR9fKIw-0-21164f0698acf9adbde4d92fbaee14a6' for reading
[tcp @ 0x555937f64cc0] Starting connection attempt to 23.248.167.151 port 443
[tcp @ 0x555937f64cc0] Starting connection attempt to 23.248.167.90 port 443
[tcp @ 0x555937f64cc0] Successfully connected to 23.248.167.151 port 443
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/1.ts?sign=1655284573-8LuwR9fKIw-0-9fe9c8222c90af04568107fe2480665b', offset 0, playlist 0
[hls @ 0x555937c53640] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/1.ts?sign=1655284573-8LuwR9fKIw-0-9fe9c8222c90af04568107fe2480665b' for reading
[tcp @ 0x555938227ac0] Starting connection attempt to 23.248.167.151 port 443
[tcp @ 0x555938227ac0] Starting connection attempt to 23.248.167.90 port 443
[tcp @ 0x555938227ac0] Successfully connected to 23.248.167.151 port 443
[hls @ 0x555937c53640] max_analyze_duration 5000000 reached at 5013600 microseconds st:0
Input #0, hls, from 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/index.m3u8?sign=1655284573-8LuwR9fKIw-0-5b1116e7d74fb08cc7f21b275d01b244':
  Duration: 00:05:24.96, start: 1.400000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Mera Dil Bhi Kitna Pagal Hai [14776067].m4a.part':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
Automatically inserted bitstream filter 'aac_adtstoasc'; args=''
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/2.ts?sign=1655284573-8LuwR9fKIw-0-092ebbc4018d6aee8bb4b711f04330be', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/2.ts?sign=1655284573-8LuwR9fKIw-0-092ebbc4018d6aee8bb4b711f04330be' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/3.ts?sign=1655284573-8LuwR9fKIw-0-e959b6fcc9a04d8412b637150832e32f', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/3.ts?sign=1655284573-8LuwR9fKIw-0-e959b6fcc9a04d8412b637150832e32f' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/4.ts?sign=1655284573-8LuwR9fKIw-0-3921bd62ae02424d41447f8dd3bed0eb', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/4.ts?sign=1655284573-8LuwR9fKIw-0-3921bd62ae02424d41447f8dd3bed0eb' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/5.ts?sign=1655284573-8LuwR9fKIw-0-5cba48090b27a4eafd66e8eb8e4a4921', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/5.ts?sign=1655284573-8LuwR9fKIw-0-5cba48090b27a4eafd66e8eb8e4a4921' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/6.ts?sign=1655284573-8LuwR9fKIw-0-a3929aac1b61141e48733a950295e422', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/6.ts?sign=1655284573-8LuwR9fKIw-0-a3929aac1b61141e48733a950295e422' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/7.ts?sign=1655284573-8LuwR9fKIw-0-5db130724040be0c3f07edf93902b5eb', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/7.ts?sign=1655284573-8LuwR9fKIw-0-5db130724040be0c3f07edf93902b5eb' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/8.ts?sign=1655284573-8LuwR9fKIw-0-cc310edc85ce4e1c8117e92e4c4c111e', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/8.ts?sign=1655284573-8LuwR9fKIw-0-cc310edc85ce4e1c8117e92e4c4c111e' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/9.ts?sign=1655284573-8LuwR9fKIw-0-6c3c287f6f16b43acbd4dcce8d21c1a1', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/9.ts?sign=1655284573-8LuwR9fKIw-0-6c3c287f6f16b43acbd4dcce8d21c1a1' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/10.ts?sign=1655284573-8LuwR9fKIw-0-d479e81ddea9d2056c392d75b6430981', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/10.ts?sign=1655284573-8LuwR9fKIw-0-d479e81ddea9d2056c392d75b6430981' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/11.ts?sign=1655284573-8LuwR9fKIw-0-8a7b398ea7cd77de5604ea6b5f960a38', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/11.ts?sign=1655284573-8LuwR9fKIw-0-8a7b398ea7cd77de5604ea6b5f960a38' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/12.ts?sign=1655284573-8LuwR9fKIw-0-4f57d45cf3894b2ed88589d08a807514', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/12.ts?sign=1655284573-8LuwR9fKIw-0-4f57d45cf3894b2ed88589d08a807514' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/13.ts?sign=1655284573-8LuwR9fKIw-0-a2275305567bffc7b2e6736541b73347', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/13.ts?sign=1655284573-8LuwR9fKIw-0-a2275305567bffc7b2e6736541b73347' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/14.ts?sign=1655284573-8LuwR9fKIw-0-e93862163748979f8adbbe1469b058cc', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/14.ts?sign=1655284573-8LuwR9fKIw-0-e93862163748979f8adbbe1469b058cc' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/15.ts?sign=1655284573-8LuwR9fKIw-0-88eed6172e48d2abd0bb3facb8697863', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/15.ts?sign=1655284573-8LuwR9fKIw-0-88eed6172e48d2abd0bb3facb8697863' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/16.ts?sign=1655284573-8LuwR9fKIw-0-1ed995cdaa5ab12373fdd3591f152f02', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/16.ts?sign=1655284573-8LuwR9fKIw-0-1ed995cdaa5ab12373fdd3591f152f02' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/17.ts?sign=1655284573-8LuwR9fKIw-0-12aa77a6ab99996d09b91d400b9e2b92', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/17.ts?sign=1655284573-8LuwR9fKIw-0-12aa77a6ab99996d09b91d400b9e2b92' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/18.ts?sign=1655284573-8LuwR9fKIw-0-da98d930bb2c1fdb1573f7e8af67f3d8', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/18.ts?sign=1655284573-8LuwR9fKIw-0-da98d930bb2c1fdb1573f7e8af67f3d8' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/19.ts?sign=1655284573-8LuwR9fKIw-0-80c4de3e2d8de521ae349e5cf1b68b42', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/19.ts?sign=1655284573-8LuwR9fKIw-0-80c4de3e2d8de521ae349e5cf1b68b42' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/20.ts?sign=1655284573-8LuwR9fKIw-0-12561870ff307c3ed81444a666f9283d', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/20.ts?sign=1655284573-8LuwR9fKIw-0-12561870ff307c3ed81444a666f9283d' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/21.ts?sign=1655284573-8LuwR9fKIw-0-06a949f8581a3999822ac5883b47ed5c', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/21.ts?sign=1655284573-8LuwR9fKIw-0-06a949f8581a3999822ac5883b47ed5c' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/22.ts?sign=1655284573-8LuwR9fKIw-0-f7826a1c637a05629467abe2080755e8', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/22.ts?sign=1655284573-8LuwR9fKIw-0-f7826a1c637a05629467abe2080755e8' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/23.ts?sign=1655284573-8LuwR9fKIw-0-de617d8d6f116e16e01961fc500744f4', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/23.ts?sign=1655284573-8LuwR9fKIw-0-de617d8d6f116e16e01961fc500744f4' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/24.ts?sign=1655284573-8LuwR9fKIw-0-136d582611f3aae88d58325536147c3b', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/24.ts?sign=1655284573-8LuwR9fKIw-0-136d582611f3aae88d58325536147c3b' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/25.ts?sign=1655284573-8LuwR9fKIw-0-80821bfbc4ae7754e1e3087e14540617', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/25.ts?sign=1655284573-8LuwR9fKIw-0-80821bfbc4ae7754e1e3087e14540617' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/26.ts?sign=1655284573-8LuwR9fKIw-0-9ae5c95abc5031aa429afc64e8bb3324', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/26.ts?sign=1655284573-8LuwR9fKIw-0-9ae5c95abc5031aa429afc64e8bb3324' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/27.ts?sign=1655284573-8LuwR9fKIw-0-b568a29c55ee41b99416ad218f395acc', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/27.ts?sign=1655284573-8LuwR9fKIw-0-b568a29c55ee41b99416ad218f395acc' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/28.ts?sign=1655284573-8LuwR9fKIw-0-38d4bd79c7cd7f0ef4eaf3edc67ba7a0', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/28.ts?sign=1655284573-8LuwR9fKIw-0-38d4bd79c7cd7f0ef4eaf3edc67ba7a0' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/29.ts?sign=1655284573-8LuwR9fKIw-0-b6d76493d8f5bf2ac4c21a3563059e87', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/29.ts?sign=1655284573-8LuwR9fKIw-0-b6d76493d8f5bf2ac4c21a3563059e87' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/30.ts?sign=1655284573-8LuwR9fKIw-0-a845b70fcd63b74e0d0aad305135699c', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/30.ts?sign=1655284573-8LuwR9fKIw-0-a845b70fcd63b74e0d0aad305135699c' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/31.ts?sign=1655284573-8LuwR9fKIw-0-c2f570b51d61209441288bd3dd37c3ed', offset 0, playlist 0
[https @ 0x55593824f300] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/31.ts?sign=1655284573-8LuwR9fKIw-0-c2f570b51d61209441288bd3dd37c3ed' for reading
[hls @ 0x555937c53640] HLS request for url 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/32.ts?sign=1655284573-8LuwR9fKIw-0-12b14cc993a8aa4bcbcc39b258e67610', offset 0, playlist 0
[https @ 0x555938228480] Opening 'https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/32.ts?sign=1655284573-8LuwR9fKIw-0-12b14cc993a8aa4bcbcc39b258e67610' for reading
No more output streams to write to, finishing.7kbits/s speed=31.7x
size=    4012kB time=00:05:24.96 bitrate= 101.1kbits/s speed=32.6x
video:0kB audio:4044kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Input file #0 (https://stream-cdn.gaana.com/songs/97/1411297/14776067/14776067_96.mp4/index.m3u8?sign=1655284573-8LuwR9fKIw-0-5b1116e7d74fb08cc7f21b275d01b244):
  Input stream #0:0 (audio): 13995 packets read (4141544 bytes);
  Total: 13995 packets (4141544 bytes) demuxed
Output file #0 (file:Mera Dil Bhi Kitna Pagal Hai [14776067].m4a.part):
  Output stream #0:0 (audio): 13995 packets muxed (4141544 bytes);
  Total: 13995 packets (4141544 bytes) muxed
[AVIOContext @ 0x5559382acb40] Statistics: 4108331 bytes written, 2 seeks, 19 writeouts
[AVIOContext @ 0x555937c5bf80] Statistics: 2225356 bytes read, 0 seeks
[AVIOContext @ 0x55593822dec0] Statistics: 2189072 bytes read, 0 seeks
[AVIOContext @ 0x55593821f440] Statistics: 2939 bytes read, 0 seeks
Exception ignored in: <_io.FileIO name=4 mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/nemo/projects/github/yt-dlp/yt_dlp/downloader/external.py", line 44, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
ResourceWarning: unclosed file <_io.BufferedWriter name=4>
[ffmpeg] Downloaded 4108327 bytes
[download] 100% of 3.92MiB in 00:13```

**Comment by pukkandan** [comment]
I'll fix that warning, but upon further inspection, that is not what OP was trying to report in this issue
