### ISSUE TITLE
[Broken] Twitch Clips: ERROR unable to download video data HTTP Error 404

### ISSUE THREAD

**Issue by ibex-are-goats** [yt-dlp/yt-dlp#357]
Download any:

> ERROR: unable to download video data: HTTP Error 404:

-F:

> ID EXT RESOLUTION FPS | PROTO | VCODEC ACODEC
> 360 mp4 360p 30 | https | unknown unknown
> 480 mp4 480p 30 | https | unknown unknown
> 720 mp4 720p 60 | https | unknown unknown
> 1080 mp4 1080p 60 | https | unknown unknown

Reference to external discussion 1 with a proposed fix: https://github.com/ytdl-org/youtube-dl/issues/29136
Reference to that fix: https://github.com/ytdl-org/youtube-dl/pull/29149
Reference to external discussion 2 with another proposed fix: https://github.com/ihabunek/twitch-dl/issues/64

**Comment by pukkandan** [comment]
### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

But since you linked other relevent issues, I'll keep this open just this once

```
$ yt-dlp https://clips.twitch.tv/ShyAltruisticCheeseTooSpicy-T9tbKcc01auwU1a0 -v
[debug] Command-line config: ['https://clips.twitch.tv/ShyAltruisticCheeseTooSpicy-T9tbKcc01auwU1a0', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.20 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 37a3bb66a7
[debug] Python version 3.9.2 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [twitch:clips] Extracting URL: https://clips.twitch.tv/ShyAltruisticCheeseTooSpicy-T9tbKcc01auwU1a0
[twitch:clips] ShyAltruisticCheeseTooSpicy-T9tbKcc01auwU1a0: Downloading clip GraphQL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1190085627: Downloading 1 format(s): 1080
[debug] Invoking downloader on "https://production.assets.clips.twitchcdn.net/AT-cm%7C1190085627.mp4"
ERROR: unable to download video data: HTTP Error 404:
Traceback (most recent call last):
  File "D:\AKJ\Progs\yt-dlc\yt_dlp\YoutubeDL.py", line 2635, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "D:\AKJ\Progs\yt-dlc\yt_dlp\YoutubeDL.py", line 2298, in dl
    return fd.download(name, new_info, subtitle)
  File "D:\AKJ\Progs\yt-dlc\yt_dlp\downloader\common.py", line 384, in download
    return self.real_download(filename, info_dict), True
  File "D:\AKJ\Progs\yt-dlc\yt_dlp\downloader\http.py", line 352, in real_download
    establish_connection()
  File "D:\AKJ\Progs\yt-dlc\yt_dlp\downloader\http.py", line 117, in establish_connection
    raise err
  File "D:\AKJ\Progs\yt-dlc\yt_dlp\downloader\http.py", line 111, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "D:\AKJ\Progs\yt-dlc\yt_dlp\YoutubeDL.py", line 3062, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404:
```

**Comment by colethedj** [comment]
Seems to have been fixed upstream: https://github.com/ytdl-org/youtube-dl/commit/e13a01061d149f4fac7db1a50124c4745a11c16e & https://github.com/ytdl-org/youtube-dl/commit/f3cd1d9cec91943a459a0662cbcffe3b2e1f6675.

Should be fixed here in the next upstream merge.

```
youtube-dl https://clips.twitch.tv/ShyAltruisticCheeseTooSpicy-T9tbKcc01auwU1a0
[twitch:clips] ShyAltruisticCheeseTooSpicy-T9tbKcc01auwU1a0: Downloading clip access token GraphQL
[twitch:clips] ShyAltruisticCheeseTooSpicy-T9tbKcc01auwU1a0: Downloading clip GraphQL
[download] Destination: OFF le missile de MACRON-1190085627.mp4
[download] 100% of 17.35MiB in 00:02
```
