### ISSUE TITLE
tenyek.hu (https://tenyek.hu) 

### ISSUE THREAD

**Issue by sk8ordi3** [yt-dlp/yt-dlp#3570]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Hungary

### Example URLs

https://tenyek.hu/video/tenyek-plusz-adas-2022-aprilis-7-csutortok
https://tenyek.hu/video/tenyek-este-teljes-adas-2022-aprilis-26-kedd
https://tenyek.hu/video/vilagraszolo-sikert-erhetnek-el-ujra

### Description

site is 3 sub link can reach the videos
https://tenyek.hu/teljes-adasok
https://tenyek.hu/tenyek-plusz
https://tenyek.hu/osszes-video

### Verbose log

```shell
https://tenyek.hu/teljes-adasok

https://tenyek.hu/video/tenyek-plusz-adas-2022-aprilis-7-csutortok

yt-dlp -v "https://tenyek.hu/video/tenyek-plusz-adas-2022-aprilis-7-csutortok"
[debug] Command-line config: ['-v', 'https://tenyek.hu/video/tenyek-plusz-adas-2022-aprilis-7-csutortok']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://tenyek.hu/video/tenyek-plusz-adas-2022-aprilis-7-csutortok
[generic] tenyek-plusz-adas-2022-aprilis-7-csutortok: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] tenyek-plusz-adas-2022-aprilis-7-csutortok: Downloading webpage
[generic] tenyek-plusz-adas-2022-aprilis-7-csutortok: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://tenyek.hu/video/tenyek-plusz-adas-2022-aprilis-7-csutortok
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tenyek.hu/video/tenyek-plusz-adas-2022-aprilis-7-csutortok

----------------------------------------------------------------------------------------------------------------------------------

manifest.m3u8 
(non drm)

[debug] Command-line config: ['-S', 'res:1080,ext:mkv:m4a', '--no-check-certificates', '-v', '--downloader', 'm3u8,dash:yt-dlp-files\\aria2c', '-N', '16', '--fixup', 'never', '-o', 'yt-dlp-files\\Debug\\%(extractor)s\\%(title)s - 775.%(ext)s', '-P', 'temp:yt-dlp-files\\Temp', 'https://pstream8.tv2.hu/vod10/csVazHJvcq6YNx-bf-L5Uw/1651159078/amlst:10/20220407/576904/std/manifest.m3u8']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://pstream8.tv2.hu/vod10/csVazHJvcq6YNx-bf-L5Uw/1651159078/amlst:10/20220407/576904/std/manifest.m3u8
[generic] manifest: Requesting header
[debug] Identified a direct video link
[generic] manifest: Downloading m3u8 information
[debug] Sort order given by user: res:1080, ext:mkv:m4a
[debug] Formats sorted by: hasvid, ie_pref, res:1080(1080.0), vext:mkv(2), aext:m4a(8), lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] manifest: Downloading 1 format(s): 4160
[debug] Invoking downloader on "https://pstream8.tv2.hu/vod10/csVazHJvcq6YNx-bf-L5Uw/1651159078/amlst:10/20220407/576904/std/chunklist_b4160000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 290
[download] Destination: yt-dlp-files\Temp\yt-dlp-files\Debug\generic\manifest - 775.mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[debug] aria2c command line: "yt-dlp-files\aria2c" -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--http-accept-gzip=true" "--file-allocation=none" -x16 -j16 -s16 "--allow-overwrite=true" "--allow-piece-length-change=true" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.41 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=false" "--remote-time=true" "--show-console-readout=true" --dir ".\yt-dlp-files\Temp\yt-dlp-files\Debug\generic\" "--auto-file-renaming=false" "--file-allocation=none" "--uri-selector=inorder" -i "yt-dlp-files\Temp\yt-dlp-files\Debug\generic\manifest - 775.mp4.part.frag.urls"
[aria2c] Downloaded 975607764 bytes%)][#2e614b 2.5MiB/3.2MiB(79%)]
[download] 100% of 930.41MiB in 00:41
[MoveFiles] Moving file "yt-dlp-files\Temp\yt-dlp-files\Debug\generic\manifest - 775.mp4" to "i:\yt-dlp\yt-dlp-files\Debug\generic\manifest - 775.mp4"

----------------------------------------------------------------------------------------------------------------------------------

tenyek.hu sub-site
https://tenyek.hu/osszes-video
(all videos, but just short versions)

this is the short one video:
https://tenyek.hu/video/vilagraszolo-sikert-erhetnek-el-ujra

yt-dlp -v "https://tenyek.hu/video/vilagraszolo-sikert-erhetnek-el-ujra"
[debug] Command-line config: ['-v', 'https://tenyek.hu/video/vilagraszolo-sikert-erhetnek-el-ujra']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://tenyek.hu/video/vilagraszolo-sikert-erhetnek-el-ujra
[generic] vilagraszolo-sikert-erhetnek-el-ujra: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] vilagraszolo-sikert-erhetnek-el-ujra: Downloading webpage
[generic] vilagraszolo-sikert-erhetnek-el-ujra: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://tenyek.hu/video/vilagraszolo-sikert-erhetnek-el-ujra
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tenyek.hu/video/vilagraszolo-sikert-erhetnek-el-ujra

----------------------------------------------------------------------------------------------------------------------------------

manifest.m3u8 
(non drm)

[debug] Command-line config: ['-S', 'res:1080,ext:mkv:m4a', '--no-check-certificates', '-v', '--downloader', 'm3u8,dash:yt-dlp-files\\aria2c', '-N', '16', '--fixup', 'never', '-o', 'yt-dlp-files\\Debug\\%(extractor)s\\%(title)s - 304.%(ext)s', '-P', 'temp:yt-dlp-files\\Temp', 'https://pstream9.tv2.hu/vod10/jJC-fj_Mv_mcrHQuEsBHbw/1651160210/amlst:10/20220425/580488/std/manifest.m3u8']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://pstream9.tv2.hu/vod10/jJC-fj_Mv_mcrHQuEsBHbw/1651160210/amlst:10/20220425/580488/std/manifest.m3u8
[generic] manifest: Requesting header
[debug] Identified a direct video link
[generic] manifest: Downloading m3u8 information
[debug] Sort order given by user: res:1080, ext:mkv:m4a
[debug] Formats sorted by: hasvid, ie_pref, res:1080(1080.0), vext:mkv(2), aext:m4a(8), lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] manifest: Downloading 1 format(s): 4160
[debug] Invoking downloader on "https://pstream9.tv2.hu/vod10/jJC-fj_Mv_mcrHQuEsBHbw/1651160210/amlst:10/20220425/580488/std/chunklist_b4160000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 37
[download] Destination: yt-dlp-files\Temp\yt-dlp-files\Debug\generic\manifest - 304.mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[debug] aria2c command line: "yt-dlp-files\aria2c" -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--http-accept-gzip=true" "--file-allocation=none" -x16 -j16 -s16 "--allow-overwrite=true" "--allow-piece-length-change=true" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=false" "--remote-time=true" "--show-console-readout=true" --dir ".\yt-dlp-files\Temp\yt-dlp-files\Debug\generic\" "--auto-file-renaming=false" "--file-allocation=none" "--uri-selector=inorder" -i "yt-dlp-files\Temp\yt-dlp-files\Debug\generic\manifest - 304.mp4.part.frag.urls"
[aria2c] Downloaded 110123820 bytes%)][#6fc59c 3.1MiB/4.3MiB(72%)][#452c68 2.7MiB/3.1MiB(88%)][#edbeea 2.4Mi
[download] 100% of 105.02MiB in 00:05
[MoveFiles] Moving file "yt-dlp-files\Temp\yt-dlp-files\Debug\generic\manifest - 304.mp4" to "i:\yt-dlp\yt-dlp-files\Debug\generic\manifest - 304.mp4"
```

**Comment by HobbyistDev** [comment]
From [first url](https://tenyek.hu/video/tenyek-plusz-adas-2022-aprilis-7-csutortok), i found the json data in this tag
`<script id="my-app-state" type="application/json"> ... G.http://tenyek. ... :`. However it's encoded ( at least for me). If we replace `&q;` to `"` and `&a;` to `&`, we can parse this json. The video json url is in ```json['body']['data']['latestLiveProgramVod']```. Here's the example of the video json (unformatted) :
`https://streamctl.tv2.hu/vod/20220716/id_595588?st=Ja1FJsmz58Ibur2dpxXDyw&a;e=1658087312&a;type=json`
From this link we can get m3u8 url in `... ['hls']`

**Comment by sk8ordi3** [comment]
it is possible that what you wrote is the right solution
I only got this far with my beginner python skills

`import re
import json
import requests

print('\ntest links:\n\n https://tenyek.hu/video/vilagraszolo-sikert-erhetnek-el-ujra\n https://tenyek.hu/video/tenyek-plusz-adas-2022-aprilis-7-csutortok \n https://tenyek.hu/video/tenyek-este-teljes-adas-2022-aprilis-26-kedd \n')

link = input('link: ')
#tested link
#https://tenyek.hu/video/vilagraszolo-sikert-erhetnek-el-ujra

link1 = re.findall("https://tenyek.hu/video/(.*)", link)[0].strip()

print(link1)
#print output:
#vilagraszolo-sikert-erhetnek-el-ujra

resp = requests.get('https://tenyek.hu/publicapi/hu/content/VideoPage/'+link1+'/view').text

print(resp, file=open("get_json.json", "w+", encoding="utf-8"))

f = open('get_json.json')
json_file = json.load(f)

title = json_file['data']['meta'][0]['fields'][0]['value']

id = json_file['data']['meta'][0]['fields'][0]['id']

items = json_file['data']['meta'][5]['fields'][0]['vodInfo']['originalUrl']

print('\n'+title)
print('\n'+id)
print('\n'+items)
#print output:
#Világraszóló sikert érhetnek el újra
#538592
#https://streamctl.tv2.hu/vod/20220425/id_580488?st=xP6a0qvUbQoDQmHjR1GYJA&e=1658113382&type=json

hls = requests.get(items).text

print(hls, file=open("hls.json", "w+", encoding="utf-8"))

fg = open('hls.json')
json_file2 = json.load(fg)

items_hls = json_file2['bitrates']['hls']

print('\nhttps:'+items_hls)
#print output:
#https://pstream7.tv2.hu/vod10/XdKCA1KVtlKXmUNILbEthQ/1658156734/amlst:10/20220425/580488/std/manifest.m3u8`

**Comment by HobbyistDev** [comment]
Yours is more correct than mine. My [comment](https://github.com/yt-dlp/yt-dlp/issues/3570#issuecomment-1186464120) only can download latestLiveProgramVod. 
Btw, you can use `request.get(<url>).json()` to get the json value

**Comment by sk8ordi3** [comment]
thanks for the tip 
edited it, using .json()
