### ISSUE TITLE
[olympics.com] Data must be padded to 16 byte boundary in CBC mode

### ISSUE THREAD

**Issue by btwood** [yt-dlp/yt-dlp#3578]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Trying to download an olympics replay using the native downloader. I'm getting the same 16 byte padding error as in #1297 

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-o', '%(upload_date)s %(title)s [%(id)s].%(ext)s', '--write-info-json', 'https://olympics.com/en/video/women-s-heat-1-2-skeleton-beijing-2022-replays']
[debug] System config "/etc/yt-dlp.conf": []
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.162-1-pve-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [OlympicsReplay] Extracting URL: https://olympics.com/en/video/women-s-heat-1-2-skeleton-beijing-2022-replays
[OlympicsReplay] women-s-heat-1-2-skeleton-beijing-2022-replays: Downloading webpage
[OlympicsReplay] bd56bbb2-545d-472f-97b0-72261ff43cc6: Downloading m3u8 url
[OlympicsReplay] bd56bbb2-545d-472f-97b0-72261ff43cc6: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] bd56bbb2-545d-472f-97b0-72261ff43cc6: Downloading 1 format(s): hls-6321+hls-audio_group-ENGLISH
[info] Writing video metadata as JSON to: 20220211 Women's Heat 1 & 2 - Skeleton _ Beijing 2022 Replays [bd56bbb2-545d-472f-97b0-72261ff43cc6].info.json
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking downloader on "https://vod-b.olympicchannel.com/output/bei1000234/hdntl=exp=1651208831~acl=%2f*~data=hdntl~hmac=b61c289241dc78ff269e4bf009f33a0e7d183c3cd74c94fb5411bd50a6fe493c/video_1920_6000000-1644750005.m3u8?aka_me_session_id=AAAAAAAAAAB%2fcmtiAAAAALga06PYRdjS8WBqGVmWAMcWSD232RBUvTRVjjtMdEpwR5jiQBy3vz+RqWOiVaXxf+f%2fSVdbHitZ&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1887
[download] Destination: 20220211 Women's Heat 1 & 2 - Skeleton _ Beijing 2022 Replays [bd56bbb2-545d-472f-97b0-72261ff43cc6].fhls-6321.mp4
[download] 20220211 Women's Heat 1 & 2 - Skeleton _ Beijing 2022 Replays [bd56bbb2-545d-472f-97b0-72261ff43cc6].fhls-6321.mp4.part-Frag321 has already been downloaded
[download]  17.0% of ~5.39GiB at 98.23MiB/s ETA Unknown (frag 321/1887)ERROR: Data must be padded to 16 byte boundary in CBC mode
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2648, in process_video_result
    self.process_info(new_info)
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3120, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2846, in dl
    return fd.download(name, new_info, subtitle)
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/downloader/hls.py", line 358, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 531, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 375, in decrypt_fragment
    return unpad_pkcs7(aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv))
  File "/root/.local/lib/python3.8/site-packages/yt_dlp/aes.py", line 19, in aes_cbc_decrypt_bytes
    return compat_pycrypto_AES.new(key, compat_pycrypto_AES.MODE_CBC, iv).decrypt(data)
  File "/root/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode
```

**Comment by pukkandan** [comment]
Possibly same issue as https://github.com/yt-dlp/yt-dlp/issues/1297

**Comment by pukkandan** [comment]
@shirt-dev Did you ever figure out what the issue in #1297 actually is?

**Comment by btwood** [comment]
If I had to guess, it's the same issue. It looks like the solution padding to 16 bytes in this PR, https://github.com/yt-dlp/yt-dlp/pull/1298 may have been overwritten or taken out for some reason. Possibly because of the chance of variability in key lengths, and not always being 16 bytes.

A better place to check for data length might be in aes.py where CBC is being used for pycryptodome. But I would need to get more familiar with AES and CBC first to know if that's actually a good idea. If I remember properly, the data length must be evenly divisible by the key length. If the data isn't evenly divided, then data should be padded out. It is also possible pycryptodome will do that padding. It has been a long time since I've done any development, so I'm not sure.

Thanks for taking the time to look at it.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/pull/1298 never actually fixed the issue and instead broke other downloads. So it was reverted

**Comment by elyse0** [comment]
In my experience from working on #4330, I can say that you can only ever pad the 'plaintex', not the 'ciphertext'

AES is a block cipher that works only on 16-byte blocks; if the plaintext that we're trying to encrypt is not an exact multiple of 16, then we pad/fill the remaining bytes.

As a result of the encryption, we get a 'ciphertext' that is the 'result' of combining all the previous blocks, the round keys (key schedule) and its initialization vector (IV). [AES Diagram](https://nevonprojects.com/wp-content/uploads/2015/06/aes-image.png). Modifying this ciphertext is like modifying a hash; if you add/remove even one bit, it won't correspond to the same plaintext.

In short, the problem comes down to a malformed ciphertext, as it must be already padded and probably these issues are origin fault or network related? (tcp should take care of integrity 🤔 ). From my point of view, there's nothing we can do.


### Usual encryption-decryption process using AES CBC

```python
    def test_aes_padding(self):
        plaintext = "Hello yt-dlp!"

        key = "6150645367566B59703273357638792F"
        iv = "397A24432646294A404E635266556A58"

        message_int_array = bytes_to_intlist(bytes(plaintext, 'utf-8'))
        print(message_int_array)  # [72, 101, 108, 108, 111, 32, 121, 116, 45, 100, 108, 112, 33]

        ciphertext = aes_cbc_encrypt(
            message_int_array,
            bytes_to_intlist(bytearray.fromhex(key)),
            bytes_to_intlist(bytearray.fromhex(iv)),
        )

        print(ciphertext)  # [96, 160, 106, 166, 149, 142, 131, 165, 79, 72, 67, 205, 217, 108, 23, 202]

        original_message_int_array = aes_cbc_decrypt(
            ciphertext,
            bytes_to_intlist(bytearray.fromhex(key)),
            bytes_to_intlist(bytearray.fromhex(iv)),
        )
        
        # It contains pkcs7 padding
        print(original_message_int_array)  # [72, 101, 108, 108, 111, 32, 121, 116, 45, 100, 108, 112, 33, 3, 3, 3]

        print(''.join([chr(x) for x in original_message_int_array]))  # Hello yt-dlp!
```

### Trying to fix 'padding' issues

```python
    def test_fix_padding(self):
        plaintext = "Hello yt-dlp!"

        key = "6150645367566B59703273357638792F"
        iv = "397A24432646294A404E635266556A58"

        message_int_array = bytes_to_intlist(bytes(plaintext, 'utf-8'))
        print(message_int_array)  # [72, 101, 108, 108, 111, 32, 121, 116, 45, 100, 108, 112, 33]

        ciphertext = aes_cbc_encrypt(
            message_int_array,
            bytes_to_intlist(bytearray.fromhex(key)),
            bytes_to_intlist(bytearray.fromhex(iv)),
        )

        # Simulate it's not correctly padded, and we add zeros
        ciphertext.pop()
        ciphertext.pop()
        ciphertext.append(0)
        ciphertext.append(0)

        print(ciphertext)  # [96, 160, 106, 166, 149, 142, 131, 165, 79, 72, 67, 205, 217, 108, 0, 0]

        original_message_int_array = aes_cbc_decrypt(
            ciphertext,
            bytes_to_intlist(bytearray.fromhex(key)),
            bytes_to_intlist(bytearray.fromhex(iv)),
        )

        print(original_message_int_array)  # [16, 193, 37, 112, 43, 20, 50, 200, 138, 138, 208, 105, 187, 111, 117, 221]

        print(''.join([chr(x) for x in original_message_int_array]))  # Á%p+2ÈÐi»ouÝ
```

**Comment by elyse0** [comment]
I was looking at the previous try to fix this https://github.com/yt-dlp/yt-dlp/pull/1298/commits/e2783b3f3e45f17084fd797927dbbd84c778c38c


### Original code
```python
if self.params.get('test', False):
   return frag_content
decrypted_data = aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv)
padding_len = 16 - (len(frag_content) % 16)
decrypted_data = aes_cbc_decrypt_bytes(frag_content + bytes([padding_len] * padding_len), decrypt_info['KEY'], iv)
return decrypted_data[:-decrypted_data[-1]]
```
I think the problem comes from when the block is already 16 bytes


### Problem
```python
if self.params.get('test', False):
   return frag_content
decrypted_data = aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv)

# Let's suppose len(frag_content) = 16

padding_len = 16 - (len(frag_content) % 16)  # 16 - (16 % 16) = 16     <-- Wrong, it's already 16 bytes!
frag_content + bytes([padding_len] * padding_len)  # frag_content + [16, 16, ..., 16]  # We added bytes we didn't even need

decrypted_data = aes_cbc_decrypt_bytes(frag_content + bytes([padding_len] * padding_len), decrypt_info['KEY'], iv)
return decrypted_data[:-decrypted_data[-1]]
```

If skipping malformed fragments is not an option, and we don't care about decrypting non-sense data, we could pad it as 

### Possible solution

```python
if self.params.get('test', False):
   return frag_content
decrypted_data = aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv)

# Let's suppose len(frag_content) = 16

padding_len = len(frag_content) % 16  # 16 % 16 = 0
frag_content + bytes([padding_len] * padding_len)  # frag_content + [[0] * 0]  = frag_content

decrypted_data = aes_cbc_decrypt_bytes(frag_content + bytes([padding_len] * padding_len), decrypt_info['KEY'], iv)
return decrypted_data[:-decrypted_data[-1]]
```

**Comment by btwood** [comment]
Excellent work! Nice spotting the math/logic bug. I bet that's why it was removed.

I think anything that results in a continued download is much more preferable than failing and moving on. Especially in this case where the problem was so easily repeatable. It was consistently the same fragment. Logic being, I'd rather have all the video missing a few fragments, than an unplayable partial file.

Personally, I would prefer an attempt to include the fragment, though I'm not sure what the result in video would look like. It may not even be feasible/correct to do this. However, we can only do best effort when we know the source is giving garbage.

Skipping the faulty fragment seems fine, but I'd have to wonder what was missed and if it could have been saved.

**Comment by btwood** [comment]
There is an assumption of a bad fragment. I wonder if we should also be thinking about a "partial" fragment. I don't know how to test for this, but is it possible the incomplete fragment might be joined with the next part of the data to form a completed fragment? I agree the network stack should be taking care of this, but sometimes weird stuff happens to IP frames.

That doesn't explain why it was consistently the same fragment though. It would be more likely an "origin fault", as you put it. Otherwise you'd expect that rerunning the download would result in continued progress instead of immediate failure on the same part.

**Comment by entourage8** [comment]
@btwood
Please try the patch in the PR linked above. If it still doesn't work then please run yt-dlp with the --write-pages flag and provide the playlist `video_1920_6000000-1644750005.m3u8`.

**Comment by bashonly** [comment]
see https://github.com/yt-dlp/yt-dlp/issues/3810#issuecomment-2645953585

**Comment by bashonly** [comment]
see https://github.com/yt-dlp/yt-dlp/issues/3810#issuecomment-2667400746

can reopen if anyone experiences this error with olympics.com using version 2025.02.19 or newer
