### ISSUE TITLE
Dailymotion repeatable 404 at 23.7% of the way through a particular video

### ISSUE THREAD

**Issue by rwmjones** [yt-dlp/yt-dlp#3586]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Description

This is a download link on dailymotion: https://www.dailymotion.com/video/x1qulcx

For this particular video, I am able to play it fully through the website.  But yt-dlp (at commit 492272fed630e3cd4e7649afc03f4084e58df174)  reliably hits a 404 error at 23.7% of the way through the download:

```
$ youtube-dl https://www.dailymotion.com/video/x1qulcx
WARNING: external downloader arguments given without specifying name. The arguments will be given to all external downloaders
[dailymotion] Downloading Access Token
[dailymotion] x1qulcx: Downloading media JSON metadata
[dailymotion] x1qulcx: Downloading metadata JSON
[dailymotion] x1qulcx: Downloading m3u8 information
[info] x1qulcx: Downloading 1 format(s): http-480-1
[download] Destination: The Uncanny (1977) [x1qulcx].mp4
[download]  23.7% of 506.08MiB at 125.19KiB/s ETA 52:37[download] Got server HTTP error: Downloaded 125829120 bytes, expected 530661530 bytes. Retrying (attempt 1 of 10) ...
ERROR: unable to download video data: HTTP Error 404: Not Found
```

I've tried both continuing the download and restarting completely, and it hits the same error in the same place.

### Verbose log

```shell
[debug] Command-line config: ['--write-sub', '--external-downloader-args', '-loglevel 16', '-vU', 'https://www.dailymotion.com/video/x1qulcx']
WARNING: external downloader arguments given without specifying name. The arguments will be given to all external downloaders
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.5-200.fc35.x86_64-x86_64-with-glibc2.35
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Crypto, sqlite3
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [dailymotion] Extracting URL: https://www.dailymotion.com/video/x1qulcx
[dailymotion] Downloading Access Token
[dailymotion] x1qulcx: Downloading media JSON metadata
[dailymotion] x1qulcx: Downloading metadata JSON
[dailymotion] x1qulcx: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] x1qulcx: Downloading 1 format(s): http-480-1
[debug] Invoking downloader on "https://proxy-016.dc3.dailymotion.com/sec(TiQWjwW6SCZBKZi7EhN1SQQfDAduT_EcqW4dNVlp8myPV3QcbpCiPV-kDj3mREzsAdmq52rfoRZet9Cw9pNl-g)/video/355/365/105563553_mp4_h264_aac_hq.mp4"
[download] Resuming download at byte 125829120
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/rjones/d/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3124, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/rjones/d/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2832, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/rjones/d/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 439, in download
    ret = self.real_download(filename, info_dict)
  File "/home/rjones/d/yt-dlp/yt-dlp/yt_dlp/downloader/http.py", line 366, in real_download
    establish_connection()
  File "/home/rjones/d/yt-dlp/yt-dlp/yt_dlp/downloader/http.py", line 123, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/rjones/d/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3587, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib64/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by rwmjones** [comment]
I tried it again without `--write-sub --external-downloader-args -loglevel 16` and that didn't make a difference.

**Comment by flashdagger** [comment]
The video file is corrupted at around 20:23
```
>>  ffmpeg -ss 20:00 -i $(yt-dlp https://www.dailymotion.com/video/x1qulcx -g) -c copy out.mp4

https://proxy-016.dc3.dailymotion.com/sec(TiQWjwW6SCZBKZi7EhN1Sd6-mltPj-XHKfMeX6_BbbQ5-YCcUrckO8jpWS-Pnws7Xb9-iYo2kpCVKH54xsPhUA)/video/355/365/105563553_mp4_h264_aac_hq.mp4: corrupt input packet in stream 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x562a0f0b13c0] stream 1, offset 0x7800110: partial file
https://proxy-016.dc3.dailymotion.com/sec(TiQWjwW6SCZBKZi7EhN1Sd6-mltPj-XHKfMeX6_BbbQ5-YCcUrckO8jpWS-Pnws7Xb9-iYo2kpCVKH54xsPhUA)/video/355/365/105563553_mp4_h264_aac_hq.mp4: Invalid data found when processing input
frame=  598 fps=113 q=-1.0 Lsize=    2098kB time=00:00:23.93 bitrate= 717.9kbits/s speed=4.52x
video:1701kB audio:377kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.973760%
```

**Comment by pukkandan** [comment]
The video doesn't play fully in browser either if you lock the quality to 480p
![image](https://user-images.githubusercontent.com/6623388/170662645-3deca870-c33f-430a-8911-c6c35183d818.png)
