### ISSUE TITLE
HTTP Eroor 403 when downloading from mhzchoice.com (vimeo)

### ISSUE THREAD

**Issue by makmende001** [yt-dlp/yt-dlp#3602]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Not sure if the site is broken or I am using an incomplete command.

Any help is appreciated.

### Verbose log

```shell
MBP ~ % yt-dlp --cookies "mhzchoice.com_cookies.txt" -F "https://watch.mhzchoice.com/meraviglie-a-tour-of-italy-s-wonders/videos/meraviglie-a-tour-of-italy-s-wonders-episode-04-sn-2-ep-4" --no-check-certificates -vU
[debug] Command-line config: ['--cookies', 'mhzchoice.com_cookies.txt', '-F', 'https://watch.mhzchoice.com/meraviglie-a-tour-of-italy-s-wonders/videos/meraviglie-a-tour-of-italy-s-wonders-episode-04-sn-2-ep-4', '--no-check-certificates', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.12 (CPython 64bit) - macOS-12.3.1-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: certifi, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://watch.mhzchoice.com/meraviglie-a-tour-of-italy-s-wonders/videos/meraviglie-a-tour-of-italy-s-wonders-episode-04-sn-2-ep-4
[generic] meraviglie-a-tour-of-italy-s-wonders-episode-04-sn-2-ep-4: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] meraviglie-a-tour-of-italy-s-wonders-episode-04-sn-2-ep-4: Downloading webpage
[generic] meraviglie-a-tour-of-italy-s-wonders-episode-04-sn-2-ep-4: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://watch.mhzchoice.com/meraviglie-a-tour-of-italy-s-wonders/videos/meraviglie-a-tour-of-italy-s-wonders-episode-04-sn-2-ep-4
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://watch.mhzchoice.com/meraviglie-a-tour-of-italy-s-wonders/videos/meraviglie-a-tour-of-italy-s-wonders-episode-04-sn-2-ep-4
```

**Comment by makmende001** [comment]
@pukkandan How do I share the credentials?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/commit/aedaa455d9874f14662023f21b254168ecd55579 may have fixed this. First check if it did.

If not, share account details with me via discord (pukkandan#4207) / reddit (/u/pukkandan) / email (pukkandan.ytdlp@gmail.com)

**Comment by pukkandan** [comment]
I'm assuming this is fixed

**Comment by makmende001** [comment]
@pukkandan apologies, just saw the message,  I will test this in the next couple of days, if that's ok with you.

**Comment by pukkandan** [comment]
@Ron-s The URL+account you gave works for me with cookies. Provide verbose logs if it doesn't for you
