### ISSUE TITLE
Encoding errors continue to occur

### ISSUE THREAD

**Issue by Offert4324** [yt-dlp/yt-dlp#3608]
### Checklist

- [x] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Encoding errors continue to occur each time I try to download from Cuetv. 

What I have tried:
 `--encoding=UTF-8`
 `--restrict-filenames`
Replacing cookies.txt with new one

How can solve it? I only know a little about programming, so please give me instructions in detail.

+) I found that modifying line 1228 of client.py to `values[i] = one_value.encode('UTF-8')` works (In fact, another error occurs, but let's solve this problem first.), but I'm afraid it will cause other errors. Is it OK to change the line? If there's a way to solve this without modifying client.py, please let me know.

### Verbose log

```shell
[debug] Command-line config: ['--cookies=cuetv.online_cookies.txt', '-F', 'https://www.cuetv.online/opera-ariane-et-barbe-bleue-p-dukas-theatre-du-capitole-2019/videos/opera-ariane-et-barbe-bleue-p-dukas-theatre-du-capitole-2019', '-vU']
[debug] Encodings: locale cp949, fs utf-8, out utf-8, err utf-8, pref cp949
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://www.cuetv.online/opera-ariane-et-barbe-bleue-p-dukas-theatre-du-capitole-2019/videos/opera-ariane-et-barbe-bleue-p-dukas-theatre-du-capitole-2019
[generic] opera-ariane-et-barbe-bleue-p-dukas-theatre-du-capitole-2019: Requesting header
ERROR: 'latin-1' codec can't encode characters in position 1714-1715: ordinal not in range(256)
Traceback (most recent call last):
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 2728, in _real_extract
    head_response = self._request_webpage(
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 767, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\utils.py", line 1543, in https_open
    return self.do_open(functools.partial(
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1255, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1714-1715: ordinal not in range(256)
```

**Comment by pukkandan** [comment]
> I found that modifying line 1228 of client.py to values[i] = one_value.encode('UTF-8') works (In fact, another error occurs, but let's solve this problem first.), but I'm afraid it will cause other errors. Is it OK to change the line? 

No! You are modifying code in the python standard library

**Comment by pukkandan** [comment]
> If your question contains "isn't working" or "can you add", this is most likely the wrong template.
> If you are in doubt if this is the right template, use another template!

Is it so difficult to pick the right template despite all these notes!?

**Comment by Offert4324** [comment]
I'm sorry. I thought that Broken site referred to a site with an error in itself, not a site that doesn't work in yt-dlp, and I only saw the case of "can you add" by reading the line roughly. By the way, the checklist of the Broken site template is different, so should I edit this or write a new one?

**Comment by pukkandan** [comment]
The most important part is verbose log, which you have provided. So not much point in editing it now. The only missing question relevant to this issue at this point is:

> * [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

If you are willing, send it to me via discord (pukkandan#4207) / reddit (/u/pukkandan) / email (pukkandan.ytdlp@gmail.com)

**Comment by Offert4324** [comment]
I sent you an email.

**Comment by sulyi** [comment]
Error occurs when encoding request header, `--restrict-filenames` is irrelevant, but `--encoding` should fix this. (But obliviously it's not doing that atm.)

Adding `-X utf8` to interpreter options or using `PYTHONUTF8=1` environment variable might help for the time being.

**Comment by pukkandan** [comment]
I can't reproduce, even after setting my codepage to `949`. Output of `--print-traffic` may be helpful (it contains sensitive info - only send it privately)

> Adding -X utf8 to interpreter options or using PYTHONUTF8=1 environment variable might help for the time being.

check if this works around the issue. Also try `chcp 65001`

**Comment by Offert4324** [comment]
I'm sorry for replying late. All three methods didn't work, so I sent you the log file by email.

**Comment by Offert4324** [comment]
I'm sorry for replying late. All the three method didn't work, so I sent you the log file by email.

**Comment by Lesmiscore** [comment]
My suspicion is that your cookies file contains non-latin characters.

Given the following cookies file: (notice the file has non-latin characters)
```
# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.google.com	TRUE	/	TRUE	1710313553	tracking-id	日本語テスト
```

I was able to reproduce:
```
$ yt-dlp --cookies japanese.txt https://google.com --verbose
[debug] Command-line config: ['--cookies', 'japanese.txt', 'https://google.com', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.0-40-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://google.com
[generic] google: Requesting header
ERROR: 'latin-1' codec can't encode characters in position 12-17: ordinal not in range(256)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 2728, in _real_extract
    head_response = self._request_webpage(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 767, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3/dist-packages/yt_dlp/utils.py", line 1543, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.10/http/client.py", line 1255, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 12-17: ordinal not in range(256)
```

I don't know how it should be encoded for transfer (or it was supposed to be exist from the first place)

Can you check it? (no need to send or paste here)

**Comment by Offert4324** [comment]
> My suspicion is that your cookies file contains non-latin characters.
Oh, you're right! Hangul was included in my cookie file.
The line is about the current time, so it doesn't seem necessary.
So I tried without the line, and it said that it's an unsupported URL.
Then what do you guys think is the problem?
Should I restore the cookie file or request for the site support?

**Comment by Lesmiscore** [comment]
> Should I restore the cookie file or request site support?

Should open site support request

**Comment by Offert4324** [comment]
#4306

**Comment by Offert4324** [comment]
[https://github.com/yt-dlp/yt-dlp/issues/4306](url)

**Comment by Offert4324** [comment]
I opened the site support request. #4306

**Comment by eladkarako** [comment]
- cookie (file too) should always be ASCII-safe. whatever wrote the cookie and didn't escaped its value, has a bug.  
- workarounds such as `LC_ALL=en_US.UTF-8` before yt-dlp,  
or UTF-8 encoding the text (`your_string_variable.encode('utf-8')`),  
or passing a charset parameter in the content-type header of the payload of your `requests` object (`headers={'Content-type': 'text/plain; charset=utf-8'}`)  
should not be needed.

**Comment by AnthonyRKing** [comment]
Hey. This has been an issue with yt-dlp from day 1 in my experience but not so with youtube-dl. What do you tell your user to do to avoid this problem?

**Comment by pukkandan** [comment]
> but not so with youtube-dl.

Show logs of both programs with same options adding `-Uv --print-traffic`
