### ISSUE TITLE
[bandcamp.com] Free tracks with multiple formats cannot be downloaded

### ISSUE THREAD

**Issue by joshqou** [yt-dlp/yt-dlp#3619]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Songs listed on KSLV's bandcamp that provide multiple formats cannot be downloaded without `--format mp3-128`. Songs that only provide mp3 as an available format download successfully. Working tracks attempt to download from `bcbits.com` whereas failing tracks attempt to download from `popplers5.bandcamp.com`

This is not an issue with non-mp3 formats, [other bandcamp tracks which list multiple formats](https://perturbator.bandcamp.com/track/cult-of-luna-julie-christmas-cygnus-perturbator-remix) work fine.

Working Tracks:
- https://kslv.bandcamp.com/track/delirium
- https://kslv.bandcamp.com/track/voyage-feat-vincce

Failing Tracks:
- https://kslv.bandcamp.com/track/cold
- https://kslv.bandcamp.com/track/override

Failing tracks are free, working tracks aren't.

### Verbose log

```shell
[debug] Command-line config: ['https://kslv.bandcamp.com/track/cold', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.4-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Bandcamp] Extracting URL: https://kslv.bandcamp.com/track/cold
[Bandcamp] cold: Downloading webpage
[Bandcamp] 3752483426: Downloading free downloads page
[Bandcamp] 3752483426: Downloading mp3-320 JSON
[Bandcamp] 3752483426: Downloading vorbis JSON
[Bandcamp] 3752483426: Downloading alac JSON
[Bandcamp] 3752483426: Downloading aac-hi JSON
[Bandcamp] 3752483426: Downloading aiff-lossless JSON
[Bandcamp] 3752483426: Downloading wav JSON
[Bandcamp] 3752483426: Downloading flac JSON
[Bandcamp] 3752483426: Downloading mp3-v0 JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3752483426: Downloading 1 format(s): alac
[debug] Invoking downloader on "https://popplers5.bandcamp.com/download/track?enc=alac&fsig=....&id=3752483426&ts=1651495229.4132516260"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3137, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2845, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 128, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3600, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib64/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by joshqou** [comment]
This might actually be a bandcamp issue. Going through the free download process on bandcamp's website results in a "Download Expired" page.

**Comment by joshqou** [comment]
Been close to a week with no response from Bandcamp, should a temporary fix be put in place to allow yt-dlp to fallback to mp3-128 if the originally selected format fails to download?

**Comment by pukkandan** [comment]
Does `--check-formats` not work?

**Comment by joshqou** [comment]
@pukkandan Yes, however mp3-128 is the only format that passes.

**Comment by joshqou** [comment]
Bandcamp may have resolved the issue on their end. The failing songs now download successfully

```
$ yt-dl 'https://kslv.bandcamp.com/track/override'
[Bandcamp] override: Downloading webpage
[Bandcamp] 236615842: Downloading free downloads page
[Bandcamp] 236615842: Downloading vorbis JSON
[Bandcamp] 236615842: Downloading wav JSON
[Bandcamp] 236615842: Downloading mp3-320 JSON
[Bandcamp] 236615842: Downloading alac JSON
[Bandcamp] 236615842: Downloading flac JSON
[Bandcamp] 236615842: Downloading aiff-lossless JSON
[Bandcamp] 236615842: Downloading aac-hi JSON
[Bandcamp] 236615842: Downloading mp3-v0 JSON
[info] 236615842: Downloading 1 format(s): alac
[download] Destination: KSLV - Override [236615842].m4a
[download] 100% of 21.42MiB in 00:08
```

```
$ yt-dl 'https://kslv.bandcamp.com/track/cold'
[Bandcamp] cold: Downloading webpage
[Bandcamp] 3752483426: Downloading free downloads page
[Bandcamp] 3752483426: Downloading mp3-v0 JSON
[Bandcamp] 3752483426: Downloading mp3-320 JSON
[Bandcamp] 3752483426: Downloading alac JSON
[Bandcamp] 3752483426: Downloading aiff-lossless JSON
[Bandcamp] 3752483426: Downloading wav JSON
[Bandcamp] 3752483426: Downloading vorbis JSON
[Bandcamp] 3752483426: Downloading aac-hi JSON
[Bandcamp] 3752483426: Downloading flac JSON
[info] 3752483426: Downloading 1 format(s): alac
[download] Destination: KSLV - Cold [3752483426].m4a
[download] 100% of 25.10MiB in 00:07
```
