### ISSUE TITLE
ERROR: 'fragment_filename_sanitized

### ISSUE THREAD

**Issue by guy-teube** [yt-dlp/yt-dlp#3630]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description

I got an error 'fragment-filename-sanitized' when I try to download TF1 videos (french TV channel).
The concerned addresses : 
- https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-le-bebe-dauphin-70553180.html
- https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-la-nappe-dhuile-10861998.html
- See the verbose command/logs below

I don't know if it's a bug form yt-dlp or the streming video service (watching the video directly in the web browser is ok).

### Verbose log

```shell
guy@ubuntu:~$ yt-dlp -vU https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-le-bebe-dauphin-70553180.html
[debug] Command-line config: ['-vU', 'https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-le-bebe-dauphin-70553180.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-109-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: certifi, Cryptodome, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [TF1] Extracting URL: https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-le-bebe-dauphin-70553180.html
[TF1] paw-patrol-la-patpatrouille-le-bebe-dauphin-70553180: Downloading JSON metadata
[debug] [wat.tv] Extracting URL: wat:13877573
[wat.tv] 13877573: Downloading JSON metadata
[wat.tv] 13877573: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 13877573: Downloading 1 format(s): dash-video=2506251+dash-audio_fra=128000
[debug] Invoking downloader on "https://das-q1-ssl.tf1.fr/2/USP-0x0/75/73/13877573/ssm/13877573.ism/13877573.mpd?e=1651606964&max_bitrate=2700000&st=lABEEIo5QJc7GxbtGYdmJg"
[dashsegments] Total fragments: 90
[download] Destination: Paw Patrol, la Pat'Patrouille - Le bébé dauphin [13877573].fdash-video=2506251.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 10 of 10) ...
ERROR: 'fragment_filename_sanitized'
Traceback (most recent call last):
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1596, in process_ie_result
    return self.process_ie_result(
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2648, in process_video_result
    self.process_info(new_info)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3120, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2846, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/downloader/dash.py", line 56, in real_download
    return self.download_and_append_fragments_multiple(*args)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/downloader/fragment.py", line 387, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], pack_func=pack_func, finish_func=finish_func)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/downloader/fragment.py", line 531, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/downloader/fragment.py", line 144, in _read_fragment
    down, frag_sanitized = self.sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
```

**Comment by NanaMizukiAnother7** [comment]
#3437

**Comment by guy-teube** [comment]
Hi,
Is there a release date? The video is only available for 7 days on the replay, and it was played last friday.

**Comment by pukkandan** [comment]
Try the unofficial daily releases https://github.com/ytdl-patched/yt-dlp

**Comment by guy-teube** [comment]
I have the same error with the unofficial.

**Comment by pukkandan** [comment]
Provide verbose log

**Comment by guy-teube** [comment]
```
guy@ubuntu:~$ yt-dlp-daily -vU https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-le-bebe-dauphin-70553180.html
[debug] Command-line config: ['-vU', 'https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-le-bebe-dauphin-70553180.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.05.04.19419 [58d5f7fab] (zip)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-109-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.6.1, certifi-2019.11.28, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.04.19419, Current version: 2022.05.04.19419
yt-dlp is up to date (2022.05.04.19419)
[debug] [TF1] Extracting URL: https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-le-bebe-dauphin-70553180.html
[TF1] paw-patrol-la-patpatrouille-le-bebe-dauphin-70553180: Downloading JSON metadata
[debug] [wat.tv] Extracting URL: wat:13877573
[wat.tv] 13877573: Downloading JSON metadata
[wat.tv] 13877573: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 13877573: Downloading 1 format(s): dash-video=2506251+dash-audio_fra=128000
[debug] Invoking downloader on "https://das-q1-ssl.tf1.fr/2/USP-0x0/75/73/13877573/ssm/13877573.ism/13877573.mpd?e=1651704249&max_bitrate=2700000&st=B9coe1xK2qmqUy_2Ke34Tw"
[dashsegments] Total fragments: 90
[download] Destination: Paw Patrol, la Pat'Patrouille - Le bébé dauphin [13877573].fdash-video=2506251.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 90 ...
[download] 100% of 210.46MiB in 00:41
[debug] Invoking downloader on "https://das-q1-ssl.tf1.fr/2/USP-0x0/75/73/13877573/ssm/13877573.ism/13877573.mpd?e=1651704249&max_bitrate=2700000&st=B9coe1xK2qmqUy_2Ke34Tw"
[dashsegments] Total fragments: 90
[download] Destination: Paw Patrol, la Pat'Patrouille - Le bébé dauphin [13877573].fdash-audio_fra=128000.m4a
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 90 ...
[download] 100% of 10.89MiB in 00:14
[Merger] Merging formats into "Paw Patrol, la Pat'Patrouille - Le bébé dauphin [13877573].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Paw Patrol, la Pat'"'"'Patrouille - Le bébé dauphin [13877573].fdash-video=2506251.mp4' -i 'file:Paw Patrol, la Pat'"'"'Patrouille - Le bébé dauphin [13877573].fdash-audio_fra=128000.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Paw Patrol, la Pat'"'"'Patrouille - Le bébé dauphin [13877573].temp.mp4'
Deleting original file Paw Patrol, la Pat'Patrouille - Le bébé dauphin [13877573].fdash-audio_fra=128000.m4a (pass -k to keep)
Deleting original file Paw Patrol, la Pat'Patrouille - Le bébé dauphin [13877573].fdash-video=2506251.mp4 (pass -k to keep)
guy@ubuntu:~$
```

**Comment by guy-teube** [comment]
Other video:
```
guy@ubuntu:~$ yt-dlp-daily -vU https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-la-nappe-dhuile-10861998.html
[debug] Command-line config: ['-vU', 'https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-la-nappe-dhuile-10861998.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.05.04.19419 [58d5f7fab] (zip)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-109-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.6.1, certifi-2019.11.28, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.04.19419, Current version: 2022.05.04.19419
yt-dlp is up to date (2022.05.04.19419)
[debug] [TF1] Extracting URL: https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-la-nappe-dhuile-10861998.html
[TF1] paw-patrol-la-patpatrouille-la-nappe-dhuile-10861998: Downloading JSON metadata
[debug] [wat.tv] Extracting URL: wat:13877525
[wat.tv] 13877525: Downloading JSON metadata
[wat.tv] 13877525: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 13877525: Downloading 1 format(s): dash-video=2506317+dash-audio_fra=128000
[debug] Invoking downloader on "https://das-q1-ssl.tf1.fr/2/USP-0x0/75/25/13877525/ssm/13877525.ism/13877525.mpd?e=1651704513&max_bitrate=2700000&st=Q4H0FszlWvtn0ZnM-1kmbg"
[dashsegments] Total fragments: 90
[download] Destination: Paw Patrol, la Pat'Patrouille - La nappe d'huile [13877525].fdash-video=2506317.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 90 ...
[download] 100% of 210.44MiB in 00:36
[debug] Invoking downloader on "https://das-q1-ssl.tf1.fr/2/USP-0x0/75/25/13877525/ssm/13877525.ism/13877525.mpd?e=1651704513&max_bitrate=2700000&st=Q4H0FszlWvtn0ZnM-1kmbg"
[dashsegments] Total fragments: 90
[download] Destination: Paw Patrol, la Pat'Patrouille - La nappe d'huile [13877525].fdash-audio_fra=128000.m4a
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 90 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 90 ...
[download] 100% of 10.88MiB in 00:14
[Merger] Merging formats into "Paw Patrol, la Pat'Patrouille - La nappe d'huile [13877525].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Paw Patrol, la Pat'"'"'Patrouille - La nappe d'"'"'huile [13877525].fdash-video=2506317.mp4' -i 'file:Paw Patrol, la Pat'"'"'Patrouille - La nappe d'"'"'huile [13877525].fdash-audio_fra=128000.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Paw Patrol, la Pat'"'"'Patrouille - La nappe d'"'"'huile [13877525].temp.mp4'
Deleting original file Paw Patrol, la Pat'Patrouille - La nappe d'huile [13877525].fdash-video=2506317.mp4 (pass -k to keep)
Deleting original file Paw Patrol, la Pat'Patrouille - La nappe d'huile [13877525].fdash-audio_fra=128000.m4a (pass -k to keep)
guy@ubuntu:~$
```

**Comment by pukkandan** [comment]
Now it is correctly skipping the unavailable fragments. What is the issue?

**Comment by guy-teube** [comment]
How to be sure my file is complete (video + audio), if there are 404 errors during the download?

**Comment by pukkandan** [comment]
Compare playback b/w the file you got and the playback in browser. If you can confirm there is missing data, we can re-open this. Otherwise, there is nothing to be done

**Comment by guy-teube** [comment]
Hello,
The downloaded file is not complete, I just got a mp4.part file, and a .mp4.ytdl file.
So it is unreadable, I cannot read it to compare with the streaming one.
I still get the same error, today with this link: https://www.tf1.fr/tf1/pawpatrol/videos/paw-patrol-la-patpatrouille-le-match-de-basketball-76466908.html
(error is the same as the others ones already logged above).
