### ISSUE TITLE
[Broken] Mediaset [ITALY]

### ISSUE THREAD

**Issue by winoni71** [yt-dlp/yt-dlp#365]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.05.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\TEMP\YDL\YDLP>yt-dlp -v -F https://www.mediasetplay.mediaset.it/video/loveisintheair/episodio-1_F310769301000104
[debug] Command-line config: ['-v', '-F', 'https://www.mediasetplay.mediaset.it/video/loveisintheair/episodio-1_F310769301000104']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.20 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-91266-g8c20ea8ee0, ffprobe N-91266-g8c20ea8ee0
[debug] Proxy map: {}
[debug] [Mediaset] Extracting URL: https://www.mediasetplay.mediaset.it/video/loveisintheair/episodio-1_F310769301000104
[Mediaset] F310769301000104: Downloading JSON metadata
[Mediaset] F310769301000104: Downloading MPEG4 SD SMIL data
[Mediaset] F310769301000104: Downloading MPEG4 HD SMIL data
ERROR: This content is not available in your location.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1126, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1147, in __extract_info
  File "yt_dlp\extractor\common.py", line 564, in extract
  File "yt_dlp\extractor\mediaset.py", line 157, in _real_extract
  File "yt_dlp\extractor\mediaset.py", line 142, in _real_extract
  File "yt_dlp\extractor\theplatform.py", line 47, in _extract_theplatform_smil
  File "yt_dlp\extractor\common.py", line 1001, in raise_geo_restricted
yt_dlp.utils.GeoRestrictedError: This content is not available in your location.

```

## Description

Trying to download a video from mediaset.it results in a "Geo Restricted Error" even though I'm attempting the download from Italy, so without the use of a VPN or proxy.

This does not occur with all videos, for example this works right now (https://www.mediasetplay.mediaset.it/video/mrwronglezionidamore/episodio-1_F310575103000102), but it also seem to work fine if the video is not brand new, but not always.

In all cases, videos can be downloaded using the mpd urls instead.

**Comment by colethedj** [comment]
Note for devs: they seem to block VPNs/proxies.

**Comment by winoni71** [comment]
> 
> 
> Note for devs: they seem to block VPNs/proxies.

VPN (Nord) works for me, both viewing and downloading.

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/29218

**Comment by superclarkk** [comment]
I have the same issue, connecting via Nord Italy servers.

https://www.mediasetplay.mediaset.it/video/masantoniosezionescomparsi/pt1--cap1_F309911301001C01

All episodes of the above show can be played in the browser, but youtube-dl version 2021.06.06 can only download episodes 2, 3, 4, 7, 9 and 10.  Episodes 1, 5, 6 and 8 cannot be downloaded.

I'd be very grateful if a dev could look at this.

**Comment by pukkandan** [comment]
@nixxo may be interested

**Comment by nixxo** [comment]
ok, got it.

I think I fixed it. I'll do some more tests to see if it works on other links as well.

**Comment by NicKoehler** [comment]
Extraction is quirky, is working for the most part, but I have some exampe where is not.

For example:
```
yt-dlp.exe -v "https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-69-pezzo-di-luna_F303843101017801"
```

Returns:

```
[debug] Command-line config: ['-v', 'https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-69-pezzo-di-luna_F303843101017801']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.9.1 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [Mediaset] Extracting URL: https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-69-pezzo-di-luna_F303843101017801
[Mediaset] F303843101017801: Downloading JSON metadata
[Mediaset] F303843101017801: Downloading MPEG4 SMIL data
ERROR: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
Traceback (most recent call last):
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1224, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\common.py", line 575, in extract
    ie_result = self._real_extract(url)
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\mediaset.py", line 155, in _real_extract
    raise first_e
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\mediaset.py", line 142, in _real_extract
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\theplatform.py", line 51, in _extract_theplatform_smil
    raise ExtractorError(
yt_dlp.utils.ExtractorError: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
```

Meanwhile this is working fine:

```
yt-dlp.exe -v "https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-1-cestinismo_F303843107006401"
```

**Comment by nixxo** [comment]
Nicola, non funziona neppure nel browser
![x2scrap](https://user-images.githubusercontent.com/426049/131710514-53af8c78-97ac-406f-983d-ca724da9c9a7.png)

**Comment by pukkandan** [comment]
@nixxo See #849, #850, #851
