### ISSUE TITLE
radiko.jp　403error

### ISSUE THREAD

**Issue by NKS0131** [yt-dlp/yt-dlp#3652]
### Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

It used to work fine, but suddenly it started spitting out 403 errors.

It seems to be totally unsupported.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://radiko.jp/#!/ts/INT/20220505000000']
[debug] Encodings: locale cp932, fs utf-8, out utf-8, err utf-8, pref cp932
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-105030-g0c8741f819-20211226 (setts), ffprobe N-105030-g0c8741f819-20211226
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [Radiko] Extracting URL: https://radiko.jp/#!/ts/INT/20220505000000
[debug] Loading radiko.auth_data from cache
[Radiko] 20220505000000: Downloading radio program for INT station
[Radiko] 20220505000000: Downloading m3u8 information
[Radiko] 20220505000000: Downloading m3u8 information
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20220505000000: Downloading m3u8 information
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20220505000000: Downloading m3u8 information
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20220505000000: Downloading m3u8 information
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20220505000000: Downloading m3u8 information
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20220505000000: Downloading m3u8 information
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20220505000000: Downloading m3u8 information
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 401: Unauthorized
[Radiko] 20220505000000: Downloading m3u8 information
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20220505000000: Downloading m3u8 information
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [Radiko] 20220505000000: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2487, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 981, in raise_no_formats
yt_dlp.utils.ExtractorError: [Radiko] 20220505000000: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Lesmiscore** [comment]
Try clearing cache by using `yt-dlp --clear-cache`.

@pukkandan Is there any way to direct users to clear cache? (I might make a PR for small fixes anyways)

**Comment by NKS0131** [comment]
Sorry, it shows no such option. Is there another solution?

**Comment by Lesmiscore** [comment]
Oops it was from different command, use `yt-dlp --rm-cache-dir` instead

**Comment by NKS0131** [comment]
Thanks for the reply. It worked as I wanted it to. I appreciate it. Thank you.

**Comment by Lesmiscore** [comment]
Glad to head. I'll add a feature to force reauthentication to Radiko later.
