### ISSUE TITLE
FileNotFoundError terminating yt-dlp early

### ISSUE THREAD

**Issue by cpurules** [yt-dlp/yt-dlp#3663]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When downloading a video using the below command line, I am getting an error at the end of the script that appears to be related to yt-dlp not being able to find a file it downloaded.  I have tried passing in the `-k` flag to be sure that all files were kept and not deleted, but the error persists regardless.

I do still appear to get a complete .mkv file with no issues despite the error.  But I'm not sure if there's any post-processing yt-dlp should be doing since the program terminates early.

I am on Windows 10 and installed via the binary in the repo description.  I have tried this on both an actual TV episode (from OutTV) and also from a Twitter video and they both result in the same error.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/5330942435001/558a1ff1-dce4-4239-ba78-44b5b3edf51c/10s/master.m3u8?fastly_token=NjI3ODQyZGNfMWE0NjRlNmEzYzUwNGNkZWY2ODNlMTFjYmRkYTc4M2Y2ODkyNDE1NGVkY2ViZDgwZGU0MDJiNjQ2MDkxMDM1Yg%3D%3D', '--cookies', '', '-f', 'bestvideo[height=1080]+bestaudio/best', '--convert-subs', 'srt', '--embed-subs', '--remux-video', 'mkv', '--compat-options', 'no-attach-info-json', '-o', '%(title).200s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Compatibility options: no-attach-info-json
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg 4.2.3
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/5330942435001/558a1ff1-dce4-4239-ba78-44b5b3edf51c/10s/master.m3u8?fastly_token=NjI3ODQyZGNfMWE0NjRlNmEzYzUwNGNkZWY2ODNlMTFjYmRkYTc4M2Y2ODkyNDE1NGVkY2ViZDgwZGU0MDJiNjQ2MDkxMDM1Yg%3D%3D
[generic] master: Requesting header
[debug] Identified a direct video link
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en-CA
[info] master: Downloading 1 format(s): 4279+audio-3-en__Main_
[info] Writing video subtitles to: master.en-CA.vtt
[debug] Invoking downloader on "https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/5330942435001/558a1ff1-dce4-4239-ba78-44b5b3edf51c/b684919c-71f1-4385-aaaf-9fe9ecaa4a10/rendition.m3u8?fastly_token=NjI3NzQ3MzNfYzg2ZjNjNGMxZjVjYmRkOWRiM2Y3YTY1MDU5NjY4ZTU4NjU5NmRlMGFlOGUzZTJiZjBhZTIyOTEwODNkNjljYQ%3D%3D"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 45
[download] Destination: master.en-CA.vtt
[debug] File locking is not supported on this platform. Proceeding without locking
[download] 100% of 53.38KiB in 00:01
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:master.en-CA.vtt" -f srt -movflags "+faststart" "file:master.en-CA.srt"
Deleting original file master.en-CA.vtt (pass -k to keep)
[debug] Invoking downloader on "https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/5330942435001/558a1ff1-dce4-4239-ba78-44b5b3edf51c/4dd88f44-6222-4a03-a47e-01a24e888bd6/10s/rendition.m3u8?fastly_token=NjI3NzQ3MzNfYzU0NTkxMWI2OTc4YTBlZjAxOTg3MzkwYjg1MGFkODY1MDM0ZjczYzA5NDgwZTQ1Y2I1YzBmZGVmNThhZGYyMg%3D%3D"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 133
[download] Destination: master.f4279.mp4
[download] 100% of 599.40MiB in 00:51
[debug] Invoking downloader on "https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/5330942435001/558a1ff1-dce4-4239-ba78-44b5b3edf51c/307c5afa-26c2-4443-a535-214ecb3b7aee/10s/rendition.m3u8?fastly_token=NjI3NzQ3MzNfZWI4ZmM2MTg4MDUxMTg4NDlmZTJmODk3ODVjNGM2Mzc4MDFlMjk0ZDAzNDA5Y2U3ZTNkODA1NTZiY2ZhNmFiMg%3D%3D"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 134
[download] Destination: master.faudio-3-en__Main_.mp4
[download] 100% of 36.49MiB in 00:15
[debug] ffmpeg command line: ffmpeg -i "file:master.faudio-3-en__Main_.mp4"
[Merger] Merging formats into "master.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:master.f4279.mp4" -i "file:master.faudio-3-en__Main_.mp4" -c copy -map "0:v:0" -map "1:a:0" "-bsf:a:0" aac_adtstoasc -movflags "+faststart" "file:master.temp.mp4"
Deleting original file master.f4279.mp4 (pass -k to keep)
Deleting original file master.faudio-3-en__Main_.mp4 (pass -k to keep)
[VideoRemuxer] Remuxing video from mp4 to mkv; Destination: master.mkv
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:master.mp4" -map 0 -dn -ignore_unknown -c copy -movflags "+faststart" "file:master.mkv"
Deleting original file master.mp4 (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "master.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:master.mkv" -i "file:master.en-CA.srt" -map 0 -dn -ignore_unknown -c copy -map "-0:s" -map "1:0" "-metadata:s:s:0" "language=eng" -movflags "+faststart" "file:master.temp.mkv"
Deleting original file master.en-CA.srt (pass -k to keep)
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 869, in main
  File "yt_dlp\__init__.py", line 862, in _real_main
  File "yt_dlp\YoutubeDL.py", line 862, in __exit__
  File "yt_dlp\utils.py", line 1583, in save
FileNotFoundError: [Errno 2] No such file or directory: ''
[16404] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by sulyi** [comment]
Filname `''` was given in command as the location of cookie jar, see: `--cookies ''`.

**Comment by cpurules** [comment]
Well that'll do it :) Thanks!

**Comment by j-ktz** [comment]
Did you ever get OutTV to work?  I get unsupported URL
