### ISSUE TITLE
Wonderwall.kr: Music Artists and their behind the scenes

### ISSUE THREAD

**Issue by Thorbenl** [yt-dlp/yt-dlp#3687]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

- https://wonderwall.kr/artlab/episode/103
- https://wonderwall.kr/artlab/episode/104
- https://wonderwall.kr/artlab/episode/55

### Description

I want to save my Artists Video about n album process. 
Seems to request `.ts` files. Also needs login to work.

Some examples:
```curl
curl 'https://api.wonderwall.kr/v2/artlab/videos/episodes/104/video' \
  -H 'authority: api.wonderwall.kr' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7,da;q=0.6,sv;q=0.5,pl;q=0.4' \
  -H 'authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE4ODYxOSwidXNlckxldmVsIjoxLCJpYXQiOjE2NTIwNzgwNzEsImV4cCI6MTY1MjA4MTY3MX0.neU0WPOIrUy_GkROkNl3RSiCYYdgpvSKFlBg5zYvn4A' \
  -H 'country: DK' \
  -H 'currency: USD' \
  -H 'lang: en' \
  -H 'origin: https://wonderwall.kr' \
  -H 'referer: https://wonderwall.kr/' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'timezone: Europe/Copenhagen' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Mobile Safari/537.36' \
  -H 'uuid: 2b670753-ed80-44b0-a831-a2d89f3c6f61' \
  --compressed
```

Returns:
```json
{
    "code": 200,
    "data": "https://media.wonderwall.kr/artlab_video_episode/video/104/6_1650511511585.m3u8?CloudFront-Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9tZWRpYS53b25kZXJ3YWxsLmtyL2FydGxhYl92aWRlb19lcGlzb2RlL3ZpZGVvLzEwNC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjUyMTIxODc3fX19XX0_&CloudFront-Signature=VNufA3U~YupQKAJKiBTA0y5Y1j8BjGaRcQfAXwIndnI-7Rdh6mcaqmtFNj1UvLAFyquMO5mHn3G1bcFLwdgLRHUVSKQbcSCC5Qtrn3wDLClrA6wAbyq019IiRKglGewwko47ru3PMBO0GtveCIncAyR76xvl9nOClx-CYX8AxRyiboGF8h0FG4mSrMy75TVcdq-VclEQsKcAAlHoLGctsFd-7MVTwtjFD8W7kHaN7m8Nc68RWF8glpjiH~7fXlIYd29mOi7GTYtQjAsXDwVT4JSq8udS3zCd-G3Fs-wgT2uZO1ZgDsi7MYnTIVi5a4puRbNPRE~n27VwKFko2kaTCQ__&CloudFront-Key-Pair-Id=APKAJVBJWMTTIVCBTEKQ"
}
```

Subtitles seem to come from a sep endpoint on `https://api.wonderwall.kr/v2/artlab/videos/episodes/video-id/subtitles`
```curl
curl 'https://api.wonderwall.kr/v2/artlab/videos/episodes/104/subtitles' \
  -H 'authority: api.wonderwall.kr' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7,da;q=0.6,sv;q=0.5,pl;q=0.4' \
  -H 'authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE4ODYxOSwidXNlckxldmVsIjoxLCJpYXQiOjE2NTIwNzgwNzEsImV4cCI6MTY1MjA4MTY3MX0.neU0WPOIrUy_GkROkNl3RSiCYYdgpvSKFlBg5zYvn4A' \
  -H 'country: DK' \
  -H 'currency: USD' \
  -H 'lang: en' \
  -H 'origin: https://wonderwall.kr' \
  -H 'referer: https://wonderwall.kr/' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'timezone: Europe/Copenhagen' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Mobile Safari/537.36' \
  -H 'uuid: 2b670753-ed80-44b0-a831-a2d89f3c6f61' \
  --compressed
```

### Verbose log

```shell
~  yt-dlp -vU https://wonderwall.kr/artlab/episode/103
[debug] Command-line config: ['-vU', 'https://wonderwall.kr/artlab/episode/103']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.2 (CPython 64bit) - macOS-12.4-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://wonderwall.kr/artlab/episode/103
[generic] 103: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 103: Downloading webpage
[generic] 103: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://wonderwall.kr/artlab/episode/103
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://wonderwall.kr/artlab/episode/103
```

**Comment by Thorbenl** [comment]
Credentials can be found here: https://share.1password.com/s#POKDKYZqKNoGi5xzVJlMy039n2ZK1NYNEFXX1vmU4AY 
Its only active for 14 days, please let me know if it expires.

@pukkandan or whoever needs to know
