### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by jaffakke** [yt-dlp/yt-dlp#3692]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

UK

### Example URLs

https://www.youtube.com/watch?v=9wkQ0h_4Ec8&t=31s

### Description

When attempting to download the video (https://www.youtube.com/watch?v=9wkQ0h_4Ec8&t=31s) I get a consistent 400 Bad Request.

I've tried all formats without success.

### Verbose log

```shell
[debug] Command-line config: ['-f', '22', '--cookies', 'cookies_slim.txt', '-vU', 'https://www.youtube.com/watch?v=9wkQ0h_4Ec8&t=31s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.10.0-14-amd64-x86_64-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2-1 (setts), ffprobe 4.4.2-1
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=9wkQ0h_4Ec8&t=31s
[youtube] 9wkQ0h_4Ec8: Downloading webpage
[youtube] 9wkQ0h_4Ec8: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] 9wkQ0h_4Ec8: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr5---sn-cu-cgnl.googlevideo.com/videoplayback?expire=1652151307&ei=q395Yrv1D6u2mLAPwo6miA4&ip=217.42.154.47&id=o-ANz6-uzwGx7FXX2qg8BvlukhzcTwOssKLTN2Fi0FO4tq&itag=22&source=youtube&requiressl=yes&mh=nP&mm=31%2C29&mn=sn-cu-cgnl%2Csn-cu-auol&ms=au%2Crdu&mv=m&mvi=5&pl=25&initcwndbps=1890000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1293.839&lmt=1652112554413160&mt=1652129332&fvip=2&fexp=24001373%2C24007246&beids=24153466&c=ANDROID&txp=3318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgNw90iohn3WySEne9Qpux3PPFqizN1nLGizyFVwpJPVgCIA4TWCTxPKJQjamLECgA_An1f_HYG8FUbyaIPecx6Fjv&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgX26r21uMxztRAUqC1mIkw6fmpTKub4jMe9euehW-ZZYCIQCVgSsVZFQXZNJqaabYHvuaHec4ouZs2FkWn11VDoZ4ZA%3D%3D"
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3138, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2846, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 128, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by pukkandan** [comment]
Most likely, your cookies file is bad. Try without cookies and let us know if the issue persists

**Comment by jaffakke** [comment]
Tried with and without cookies.txt and I get the exact same issue.

However it must be network related; connecting to a surfshark vpn and running again resolves the issue and I don’t get any 400 responses.

**Comment by gamer191** [comment]
Can you please disable your VPN and then ping each of the following 2 websites:
```
rr5---sn-cu-cgnl.googlevideo.com
rr5---sn-cu-auol.googlevideo.com
```
Please let me know which ones pinged successfully.
Also, can you please retry the download now that a few days have passed and send me the verbose logs?

**Comment by gamer191** [comment]
PS: please do not close this issue, even if the video downloads successfully

**Comment by jaffakke** [comment]
No problems pinging the 2 domains.

I still get the same issue (repeated 400 Bad Request) when trying to download the same video (not connected to the VPN)

I've also tried to ping rr8---sn-cn3tc-ciml.googlevideo.com and that is succesful

[debug] Command-line config: ['--cookies', 'cookies_slim.txt', '-vU', '-f', '22', 'https://www.youtube.com/watch?v=9wkQ0h_4Ec8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.10.0-14-amd64-x86_64-with-glibc2.33
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.2-1 (setts), ffprobe 4.4.2-1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=9wkQ0h_4Ec8
[youtube] 9wkQ0h_4Ec8: Downloading webpage
[youtube] 9wkQ0h_4Ec8: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] 9wkQ0h_4Ec8: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr8---sn-cn3tc-ciml.googlevideo.com/videoplayback?expire=1653173212&ei=fBeJYpL1DOXyxgKM1ajgDQ&ip=94.195.183.223&id=o-ABTwX7xnLlTkmsrJ5w61jpQXV2sX50CoErrU2VaTGEfU&itag=22&source=youtube&requiressl=yes&mh=nP&mm=31%2C29&mn=sn-cn3tc-ciml%2Csn-aigl6nsr&ms=au%2Crdu&mv=m&mvi=8&pl=22&pcm2=yes&initcwndbps=1682500&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1293.862&lmt=1652252234609210&mt=1653151266&fvip=3&fexp=24001373%2C24007246&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgZBH2E7ej2Wx2HxgigGe_M9bjM8Y3pKXC_4M5ZA6l1rQCIEj8NyicYlVE8uJ88WakR2F5zPhyz5n4opEqi0rS_0zh&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgLVq7oURO-bK0hP1nFNTzZF9xzsBF2H8VXkMKooYvmfICIDHK0nm0Bt0W31vOGUhtuFL3n3ldeS1jGPgdHAlegOV8"
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3130, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2838, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 445, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 373, in real_download
    establish_connection()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 130, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3596, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by dirkf** [comment]
Format 22 is also prone to fail (4xx) during download (#3372), possibly due to bad YT caching/CDN replication.

[Anecdotally](https://github.com/ytdl-org/youtube-dl/issues/30990), long and controversial videos that were created as live streams are most likely to be affected.

#1986 fix doesn't help (ie, the fallback seems to be broken if its source URL fails).
