### ISSUE TITLE
IBM Ustream no video formats found.

### ISSUE THREAD

**Issue by vinaykapadia** [yt-dlp/yt-dlp#3702]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

Trying to download using this command `.\yt-dlp.exe -vU https://video.ibm.com/recorded/131744579`

Says no video format found. If I view console in browser, I'm able to grab a .m3u link and use that, but by the time it finishes, it needs to read another URL and the token expires so it returns a 403 error, and I'm left with a 2 minute choppy file (the actual video is 1 hour 22 minutes).

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://video.ibm.com/recorded/131744579']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08 [535eb16] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08, Current version: 2022.03.08
yt-dlp is up to date (2022.03.08)
[debug] [ustream] Extracting URL: https://video.ibm.com/recorded/131744579
[ustream] 131744579: Downloading JSON metadata
[ustream] 131744579: Downloading connection info
[ustream] 131744579: Downloading stream info
[ustream] 131744579: Downloading connection info (try 2)
[ustream] 131744579: Downloading stream info (try 2)
[ustream] 131744579: Downloading connection info (try 3)
[ustream] 131744579: Downloading stream info (try 3)
ERROR: [ustream] 131744579: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1473, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1529, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2460, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 970, in raise_no_formats
yt_dlp.utils.ExtractorError: [ustream] 131744579: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by vinaykapadia** [comment]
Oh and I think the checklist has a typo, it says to make sure I'm on version 2022.04.08 but the latest release on the right of this page shows 2022.03.08 which is the one I'm using.

**Comment by coletdjnz** [comment]
> Oh and I think the checklist has a typo, it says to make sure I'm on version 2022.04.08 but the latest release on the right of this page shows 2022.03.08 which is the one I'm using.

2022.04.08 is the latest but GitHub is having issues :pensive:  https://github.com/yt-dlp/yt-dlp/issues/3653

**Comment by vinaykapadia** [comment]
@coletdjnz thanks for verifying.

**Comment by vinaykapadia** [comment]
https://video.ibm.com/recorded/131752865 works fine. the original one i linked in the report still doesn't.

**Comment by m4tu4g** [comment]
> https://video.ibm.com/recorded/131752865 works fine.

Can you confirm if it's working or not now?

**Comment by vinaykapadia** [comment]
Just tried. Updated to version 2022.05.18, still no good.

**Comment by vinaykapadia** [comment]
These are the three links I want to download:

https://video.ibm.com/recorded/131744579 - no video formats found.
https://video.ibm.com/recorded/131752865 - this one worked before, but when i tried it again, no video formats found.
https://video.ibm.com/recorded/131758972 - no video formats found.
