### ISSUE TITLE
Video Selection date filter "today" or "now" throws error.

### ISSUE THREAD

**Issue by AJ-AllTheMods** [yt-dlp/yt-dlp#3704]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

From here: https://github.com/yt-dlp/yt-dlp/blob/master/README.md

```
--date DATE              Download only videos uploaded on this date.
                                 The date can be "YYYYMMDD" or in the format
                                 "(now|today)[+-][0-9](day|week|month|year)(s)?"
```
                                 
As of version 2022.03.08 using the keywords "now" or "today" throws an error.
However "today-0day" is a functionaly identical workaround which does correctly select videos from "today".

The verbose log contains 4 example snippets:

- yt-dlp_2022.02.04.exe
- yt-dlp_2022.03.08.exe
- yt-dlp_2022.04.08.exe
- today-0day workaround

### Verbose log

```shell
============================================================

D:\>yt-dlp_2022.02.04.exe -v --date today https://www.youtube.com/c/thesun/videos
[debug] Command-line config: ['-v', '--date', 'today', 'https://www.youtube.com/c/thesun/videos']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2022-05-08-git-f77ac5131c-essentials_build-www.gyan.dev (setts), ffprobe 2022-05-08-git-f77ac5131c-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/c/thesun/videos
[youtube:tab] thesun: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/c/thesun/videos
[download] Downloading playlist: The Sun - Videos
[youtube:tab] UCIzXayRP7-P0ANpq-nD-h5g page 1: Downloading API JSON

============================================================

D:\>yt-dlp_2022.03.08.exe -v --date today https://www.youtube.com/c/thesun/videos
[debug] Command-line config: ['-v', '--date', 'today', 'https://www.youtube.com/c/thesun/videos']
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 854, in main
  File "yt_dlp\__init__.py", line 289, in _real_main
  File "yt_dlp\utils.py", line 1967, in day
  File "yt_dlp\utils.py", line 1954, in __init__
  File "yt_dlp\utils.py", line 1907, in date_from_str
ValueError: Invalid date format today
[34108] Failed to execute script '__main__' due to unhandled exception!

============================================================

D:\>yt-dlp_2022.04.08.exe -v --date today https://www.youtube.com/c/thesun/videos
[debug] Command-line config: ['-v', '--date', 'today', 'https://www.youtube.com/c/thesun/videos']
Usage: yt-dlp_2022.04.08.exe [OPTIONS] URL [URL...]

yt-dlp_2022.04.08.exe: error: Invalid date format today

============================================================

D:\>yt-dlp_2022.04.08.exe -v --date today-0day https://www.youtube.com/watch?v=f57ElAo219c
[debug] Command-line config: ['-v', '--date', 'today-0day', 'https://www.youtube.com/watch?v=f57ElAo219c']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-05-08-git-f77ac5131c-essentials_build-www.gyan.dev (setts), ffprobe 2022-05-08-git-f77ac5131c-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=f57ElAo219c
[youtube] f57ElAo219c: Downloading webpage
[youtube] f57ElAo219c: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr                                                         , vext, aext, hasaud, id
[download] 2011-08-04 upload date is not in range 2022-05-10 - 2022-05-10

============================================================
```

**Comment by coletdjnz** [comment]
This is technically expected, `--date today` is not a valid format going by the docs:

```
--date DATE              Download only videos uploaded on this date.
                                 The date can be "YYYYMMDD" or in the format
                                 "(now|today)[+-][0-9](day|week|month|year)(s)?"
```
(the format here is in regex. the only optional thing is the `s` at the end)


Internally there is support for passing just `(now|today|yesterday)` so not sure why that isn't exposed.

seems to have been made unnecessary strict by https://github.com/yt-dlp/yt-dlp/pull/2641
