### ISSUE TITLE
MX Player

### ISSUE THREAD

**Issue by spideyboyaman** [yt-dlp/yt-dlp#3705]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Description

Unable to download MX Player videos.

**Command I used :** `yt-dlp https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e`

**Current Version :**  (Output for `yt-dlp -U`)

```
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
```

### Verbose log

```shell
[Mxplayer] notice-for-bhide-online: Downloading JSON metadata
ERROR: 41a998c0e0dabc4cbc1b75778056849e: An extractor error has occurred. (caused by KeyError('profile')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
Can't reproduce.
```
❯ yt-dlp -v https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e
[debug] Command-line config: ['--ignore-config', '-v', 'https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: f2606bc44
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [Mxplayer] Extracting URL: https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e
[Mxplayer] notice-for-bhide-online: Downloading JSON metadata
[Mxplayer] notice-for-bhide-online: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 41a998c0e0dabc4cbc1b75778056849e: Downloading 1 format(s): 5235+program_audio-Hindi
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking hlsnative downloader on "https://sonylivmx.sonyliv.com/HLS/51ab673a-f21b-43c2-adb0-2f2df48f9c7b/hdntl=exp=1652330434~acl=%2f*~id=1556784382mxef450c232a6594410b8~data=hdntl~hmac=a0f8d14db2c93bf4a8ab1ea368238cc3fb3a20c6912284e9dcaec6c2be15e735/liv_show_sab_tarraakmehta_ep3454_20220510T060603_5500k.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 329
[download] Destination: Notice For Bhide [41a998c0e0dabc4cbc1b75778056849e].f5235.mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[download]   1.1% of ~499.22MiB at  2.37MiB/s ETA 01:43 (frag 4/329)

ERROR: Interrupted by user
```

---

> - [X] I've checked that all provided URLs are alive and playable in a browser

First double check this (from same IP).

Then, run this, share the new verbose log, and attach the `.dump` file(s) generated
```
yt-dlp -v --write-pages https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e
```

**Comment by spideyboyaman** [comment]
> yt-dlp -v --write-pages https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e

**output is same again :**

```
[debug] Command-line config: ['-v', '--write-pages', 'https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.11 (CPython 64bit) - Linux-4.4.0-1101-aws-x86_64-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Mxplayer] Extracting URL: https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e
[Mxplayer] notice-for-bhide-online: Downloading JSON metadata
[Mxplayer] Saving request to notice-for-bhide-online_https_-_androidapi.mxplay.com_v1_detail_tvshow_episode_41a998c0e0dabc4cbc1b75778056849e.dump
ERROR: 41a998c0e0dabc4cbc1b75778056849e: An extractor error has occurred. (caused by KeyError('profile')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/app/.conda/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/app/.conda/lib/python3.9/site-packages/yt_dlp/extractor/mxplayer.py", line 138, in _real_extract
    data_json = self._download_json(f'{API_URL}{type}/{video_id}', display_id, headers=headers)['profile']
KeyError: 'profile'
```

**.dump file:**

https://file.io/K9vsCZVuoXNq

**Comment by spideyboyaman** [comment]
Hii I have tried using 

```
yt-dlp --geo-bypass-country IN -v --write-pages https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e
```

**and the output was :**

```shell
[debug] Command-line config: ['--geo-bypass-country', 'IN', '-v', '--write-pages', 'https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.11 (CPython 64bit) - Linux-4.4.0-1101-aws-x86_64-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 117.212.26.85 (IN) as X-Forwarded-For
[debug] [Mxplayer] Extracting URL: https://www.mxplayer.in/show/watch-taarak-mehta-ka-ooltah-chashmah/34013500/notice-for-bhide-online-41a998c0e0dabc4cbc1b75778056849e
[Mxplayer] notice-for-bhide-online: Downloading JSON metadata
[Mxplayer] Saving request to notice-for-bhide-online_https_-_androidapi.mxplay.com_v1_detail_tvshow_episode_41a998c0e0dabc4cbc1b75778056849e.dump
[Mxplayer] notice-for-bhide-online: Downloading m3u8 information
WARNING: [Mxplayer] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [Mxplayer] 41a998c0e0dabc4cbc1b75778056849e: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/app/.conda/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/app/.conda/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/app/.conda/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/app/.conda/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2487, in process_video_result
    self.raise_no_formats(info_dict)
  File "/app/.conda/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 981, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Mxplayer] 41a998c0e0dabc4cbc1b75778056849e: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**and the .dump file was:**

https://easyupload.io/qh4qc3

**Comment by pukkandan** [comment]
> > I've checked that all provided URLs are alive and playable in a browser

> First double check this (from same IP).

**Comment by spideyboyaman** [comment]
ya now using `--geo-bypass-country IN`  make it a step further but didn't started download ended with a new error

**Comment by spideyboyaman** [comment]
but i don't know why before it was not downloading

**Comment by pukkandan** [comment]
The errors you are getting is consistent with the behavior if you are geo-blocked. That would be weird if you CAN play it in browser. Are you logged in to the browser? Try in an incognito window (without login)

**Comment by spideyboyaman** [comment]
> The errors you are getting is consistent with the behavior if you are geo-blocked. That would be weird if you CAN play it in browser. Are you logged in to the browser? Try in an incognito window (without login)

no i am not logged in in my browser.

**Comment by spideyboyaman** [comment]
> The errors you are getting is consistent with the behavior if you are geo-blocked. That would be weird if you CAN play it in browser. Are you logged in to the browser? Try in an incognito window (without login)

and also in incognito window it is playing.
