### ISSUE TITLE
Vimeo videos no longer downloading forbidden 403

### ISSUE THREAD

**Issue by qb128552** [yt-dlp/yt-dlp#3712]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Vimeo protected files master.mpd is no longer working. tried all suggestions from reddit https://www.reddit.com/r/youtubedl/wiki/errors-403forbidden

still forbidden

### Verbose log

```shell
yt-dlp.exe "https://162vod-adaptive.akamaized.net/exp=*****/master.mpd" --no-check-certificate --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" --add-header "Origin: https://player.vimeo.com" --cookies-from-browser chrome --referer "https://player.vimeo.com" --verbose
[debug] Command-line config: ['https://162vod-adaptive.akamaized.net/exp=*******/master.mpd', '--no-check-certificate', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36', '--add-header', 'Origin: https://player.vimeo.com', '--cookies-from-browser', 'chrome', '--referer', 'https://player.vimeo.com', '--verbose']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\CLL\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[Cookies] Extracted 3209 cookies from chrome
[debug] cookie version breakdown: {'v10': 3209, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2020-12-06-git-2aab42bc40-full_build-www.gyan.dev, ffprobe 2020-12-06-git-2aab42bc40-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://162vod-adaptive.akamaized.net/exp=******/master.mpd
[generic] master: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] master: Downloading 1 format(s): video-044c65e1+audio-bb7f1b15
[debug] Invoking downloader on "https://162vod-adaptive.akamaized.net/exp=*****/044c65e1.mp4?r=dXM%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3120, in process_info
  File "yt_dlp\YoutubeDL.py", line 2846, in dl
  File "yt_dlp\downloader\common.py", line 457, in download
  File "yt_dlp\downloader\http.py", line 369, in real_download
  File "yt_dlp\downloader\http.py", line 128, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
Pass the actual vimeo URL, or if it is an embedded player, pass the embedding page's URL. Then share with us the UNREDACTED log
