### ISSUE TITLE
Thisvid member page

### ISSUE THREAD

**Issue by afterdelight** [yt-dlp/yt-dlp#3716]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Indonesia

### Example URLs

https://thisvid.com/members/2003629/

### Description

add support for downloading public videos of a user page.
for now its only supported by a generic KVS player extractor
and cant pull videos from a members page

### Verbose log

```shell
F:\downloader\thisvid>ytdl-patched https://thisvid.com/members/2003629/ -v
[debug] Command-line config: ['https://thisvid.com/members/2003629/', '-v']
[debug] User config "C:\Users\X\AppData\Roaming\yt-dlp\config": ['--continue', '--format-sort', 'vbr,abr', '--http-chunk-size', '1M', '--buffer-size', '16K', '--sub-lang', 'english', '--embed-metadata', '--abort-on-unavailable-fragment', '-o', '%(title)s [%(id)s].%(ext)s', '--ffmpeg-location', 'D:\\Program Files\\ffmpeg\\bin', '--no-lock']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] ytdl-patched version 2022.04.08
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: "D:\Program Files\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: "D:\Program Files\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 2022-03-28-git-5ee198f9aa-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-28-git-5ee198f9aa-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://thisvid.com/members/2003629/
[generic] 2003629: Requesting header
[generic] [debug] Fetching webpage from https://thisvid.com/members/2003629/
WARNING: [generic] Falling back on generic information extractor.
[generic] 2003629: Downloading webpage
[generic] [debug] Fetching webpage from https://thisvid.com/members/2003629/
[generic] 2003629: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://thisvid.com/members/2003629/
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1437, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1517, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 664, in extract
    ie_result = self._real_extract(url)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 4139, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://thisvid.com/members/2003629/

[debug] Cleaning up 1 streams
```

**Comment by afterdelight** [comment]
you can resume it from this pull
https://github.com/yt-dlp/yt-dlp/pull/3491

**Comment by master-leonardo** [comment]
It was added to [youtube-dl](https://github.com/ytdl-org/youtube-dl/commit/1a4fbe8462f5e531a891aeac7db6c0bde49c5536), but i got no idea how to use that, as there are no new releases.  
Let's hope they merge it here.
