### ISSUE TITLE
[ZDF] 500: Internal Server Error, but youtube-dl works

### ISSUE THREAD

**Issue by leoarnold** [yt-dlp/yt-dlp#3718]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Up to date `yt-dlp` runs into an HTTP error while "newest" `youtube-dl` (i.e. 2021.12.17) can download video:

```
  youtube-dl -vU https://www.zdf.de/politik/auslandsjournal/die-sendung-vom-11-mai-2022-102.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vU', 'https://www.zdf.de/politik/auslandsjournal/die-sendung-vom-11-mai-2022-102.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.13.0-41-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.12.17)
[debug] Using fake IP 53.220.228.168 (DE) as X-Forwarded-For.
[ZDF] die-sendung-vom-11-mai-2022-102: Downloading webpage
[ZDF] die-sendung-vom-11-mai-2022-102: Downloading JSON content
[ZDF] die-sendung-vom-11-mai-2022-102: Downloading JSON metadata
[ZDF] 220511_sendung_ajo: Downloading m3u8 information
[ZDF] 220511_sendung_ajo: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://zdfvod-rwrtr.akamaized.net/i/,/mp4/none/zdf/22/05/220511_sendung_ajo/1/220511_sendung_ajo,_508k_p9,_808k_p11,_1628k_p13,_3328k_p15,v15.mp4.csmil/index-f4-v1-a1.m3u8'
[download] Die Sendung vom 11. Mai 2022-220511_sendung_ajo.mp4 has already been downloaded
[download] 100% of 532.26MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Die Sendung vom 11. Mai 2022-220511_sendung_ajo.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Die Sendung vom 11. Mai 2022-220511_sendung_ajo.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Die Sendung vom 11. Mai 2022-220511_sendung_ajo.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Die Sendung vom 11. Mai 2022-220511_sendung_ajo.temp.mp4'
```

### Verbose log

```shell
$  yt-dlp -vU https://www.zdf.de/politik/auslandsjournal/die-sendung-vom-11-mai-2022-102.html
[debug] Command-line config: ['-vU', 'https://www.zdf.de/politik/auslandsjournal/die-sendung-vom-11-mai-2022-102.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-41-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: certifi, Crypto, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] Using fake IP 53.204.182.70 (DE) as X-Forwarded-For
[debug] [ZDF] Extracting URL: https://www.zdf.de/politik/auslandsjournal/die-sendung-vom-11-mai-2022-102.html
[ZDF] die-sendung-vom-11-mai-2022-102: Downloading webpage
[ZDF] die-sendung-vom-11-mai-2022-102: Downloading JSON content
[ZDF] die-sendung-vom-11-mai-2022-102: Downloading JSON metadata
[ZDF] 220511_sendung_ajo: Downloading m3u8 information
[ZDF] 220511_sendung_ajo: Downloading m3u8 information
[debug] Sort order given by extractor: hasaud, res, quality, language_preference
[debug] Formats sorted by: hasvid, ie_pref, hasaud, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 220511_sendung_ajo: Downloading 1 format(s): hls-2607
[debug] Invoking downloader on "https://zdfvod-rwrtr.akamaized.net/i/,/mp4/none/zdf/22/05/220511_sendung_ajo/1/220511_sendung_ajo,_508k_p9,_808k_p11,_1628k_p13,_3328k_p15,v15.mp4.csmil/index-f4-v1-a1.m3u8"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/home/leoarnold/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3138, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/leoarnold/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2846, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/leoarnold/bin/yt-dlp/yt_dlp/downloader/common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "/home/leoarnold/bin/yt-dlp/yt_dlp/downloader/hls.py", line 68, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/home/leoarnold/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by leoarnold** [comment]
Works now. Maybe just due to temporary outage at ZDF.
