### ISSUE TITLE
yt-dlp stopped downloading incompleted file.

### ISSUE THREAD

**Issue by lowprofileusername** [yt-dlp/yt-dlp#3721]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

The command I used is yt-dlp --batch-file=7.txt -N 16 -R infinite --file-access-retries infinite --fragment-retries infinite --merge-output-format mkv -o "D:\AAA%(autonumber)s" --autonumber-start 1

So I have a text document contain 20 lines of url. But I have only sucessfully downloaded 11 of 20 files. some of them are partial downloaded. also the final output 00018.mkv are actually the file of line 20 instead of 18.  I've tried added every possible parameter I found into the command. (-R infinite --file-access-retries infinite --fragment-retries infinite) and it still skipping files due to network issue. 
<a href="https://imgtu.com/i/ODzYdK"><img src="https://s1.ax1x.com/2022/05/13/ODzYdK.png" alt="ODzYdK.png" border="0" /></a>

how can I make yt-dlp keep retries untill it success? as you can see from the screenshot it skipping download 00008 maybe due to the error I posted in verbose log.  and its most likely caused by unstable networks. after manualy retry I can fix this problem.
Thank you.

Actually my main issue were how to make autonumber more fit my need. in my case I would simply want line 18 filename stick to 00018 no matter what happend before starting download this file.

### Verbose log

```shell
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3120, in process_info
  File "yt_dlp\YoutubeDL.py", line 2846, in dl
  File "yt_dlp\downloader\common.py", line 457, in download
  File "yt_dlp\downloader\hls.py", line 68, in real_download
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1543, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
this is the verbose log for 00006. 
[download]  71.8% of ~13.67MiB at  8.45KiB/s ETA 00:19 (frag 214/298)ERROR: unable to download video data: The read operation timed out
```

**Comment by pukkandan** [comment]
> Actually my main issue were how to make autonumber more fit my need. in my case I would simply want line 18 filename stick to 00018 no matter what happend before starting download this file.

Use `video_autonumber`. See the differnce b/w the two in the readme

**Comment by lowprofileusername** [comment]
> matter

Thank you. But does video_autonumber suppprt autonumber-start ? I would like to have number started other than 1

**Comment by lowprofileusername** [comment]
in my case video_autonumber doesn't help. this time I occured error white download first video.
ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
[generic] index: Requesting header

and it started numbering line 2 file as 01 instead of 02

**Comment by lowprofileusername** [comment]
The command I use is 
yt-dlp --batch-file=7.txt -N 16 -R infinite --file-access-retries infinite --fragment-retries infinite -v --socket-timeout 100 --extractor-retries infinite --merge-output-format mkv -o "D:\video%(video_autonumber+10)d"
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.04.08 [7884ade] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-04-14-git-ea84eb2db1-essentials_build-www.gyan.dev (setts), ffprobe 2022-04-14-git-ea84eb2db1-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'socks5://127.0.0.1:7890', 'https': 'socks5://127.0.0.1:7890'}
[debug] [generic] Extracting URL: https://url1
[generic] index: Requesting header
[debug] Identified a direct video link
[generic] index: Downloading m3u8 information
ERROR: [generic] Failed to download m3u8 information: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 2764, in _real_extract
  File "yt_dlp\extractor\common.py", line 2140, in _extract_m3u8_formats_and_subtitles
  File "yt_dlp\extractor\common.py", line 800, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 785, in _request_webpage

  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "yt_dlp\utils.py", line 1515, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 767, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1543, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>

[debug] [generic] Extracting URL: https://url2
[generic] index: Requesting header
[debug] Identified a direct video link
[generic] index: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] index: Downloading 1 format(s): 6101+audio-AACL-129-Chinese+audio-AACL-194-Japanese
[debug] Invoking downloader on "https://url2"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 298
[download] Destination: D:\video11.f6101.mp4\

as you can see from the log it start numbering from the first sucessfully url which is in line 2

**Comment by pukkandan** [comment]
The error in your original post was a "download error". The solution I gave should work for those. But the error in this log in an extraction error. 

Only way I can think of to ensure consistent numbers across those is to do `--abort-on-error` and retry
