### ISSUE TITLE
ERROR: [Errno 2] No such file or directory: 'Schwärze [-b2w6fKq-ls].f247.webm' after successful DL 

### ISSUE THREAD

**Issue by entropie** [yt-dlp/yt-dlp#3725]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I try to download audiobooks from youtube which mostly works fine. Some dont work. For example

    https://www.youtube.com/watch?v=-b2w6fKq-ls

Its most probably related to german umlauts ( "ä" ), but it seems thats not always a problem. Also I sometimes have the "same" file in the directory two times (it must be a encoding issue, but iam not sure how to debug that proper).

I fiddled around alot. Tried passing LC_ALL with different values. Same with youtube-dl btw.

### Verbose log

```shell
Θ yt-dlp -v https://www.youtube.com/watch\?v\=-b2w6fKq-ls
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=-b2w6fKq-ls']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.12 (CPython 64bit) - Linux-5.10.52-gentoo-nyx-x86_64-Intel-R-_Core-TM-_i5-3570_CPU_@_3.40GHz-with-glibc2.34
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: certifi, Crypto, sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=-b2w6fKq-ls
[youtube] -b2w6fKq-ls: Downloading webpage
[youtube] -b2w6fKq-ls: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -b2w6fKq-ls: Downloading 1 format(s): 247+251
[debug] Invoking downloader on "https://rr4---sn-4g5lzned.googlevideo.com/videoplayback?expire=1652486713&ei=2Z1-YvnQMuKI6dsPuPeDoAI&ip=95.89.149.19&id=o-AI3XBwKw4tIxapH9N_e2XPFeemzQBP8O1Ql-wvA4Ybvh&itag=247&source=youtube&requiressl=yes&mh=dj&mm=31%2C26&mn=sn-4g5lzned%2Csn-f5f7lnee&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=1593750&vprv=1&mime=video%2Fwebm&gir=yes&clen=840256021&dur=34822.495&lmt=1646006663446241&mt=1652464866&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgMbfkIKOB0kC0u6W0pfxcr3LeOTl1UVPukUpkdVTOhggCIC7AurQ-_rc5Cvq_4ST8XRdRid_oBFZSVFeqWmf-SuHJ&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIaZV4iwRBDJnt1gbSDAWqmaEhd9aXnnT8hZBPx1yP0cAiBOSZCsRnqMioUN1V8YJ8Bk15fGThZ0UqiAHAZKCBeH5g%3D%3D"
[download] Destination: Schwärze [-b2w6fKq-ls].f247.webm
[download] 100% of 801.33MiB in 01:55
[debug] Invoking downloader on "https://rr4---sn-4g5lzned.googlevideo.com/videoplayback?expire=1652486713&ei=2Z1-YvnQMuKI6dsPuPeDoAI&ip=95.89.149.19&id=o-AI3XBwKw4tIxapH9N_e2XPFeemzQBP8O1Ql-wvA4Ybvh&itag=251&source=youtube&requiressl=yes&mh=dj&mm=31%2C26&mn=sn-4g5lzned%2Csn-f5f7lnee&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=1593750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=451879189&dur=34822.521&lmt=1646010978429248&mt=1652464866&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANMRuLRi0fvXgyGa2Dz3Le_5557WMdAa3dkgc5j9-n_MAiB2c2_-_pbRRqJ3dESRHD4s-wY_iZuaUs6Tfiu1qgvR3A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIaZV4iwRBDJnt1gbSDAWqmaEhd9aXnnT8hZBPx1yP0cAiBOSZCsRnqMioUN1V8YJ8Bk15fGThZ0UqiAHAZKCBeH5g%3D%3D"
[download] Destination: Schwärze [-b2w6fKq-ls].f251.webm
[download] 100% of 430.95MiB in 01:03
[Merger] Merging formats into "Schwärze [-b2w6fKq-ls].webm"
ERROR: [Errno 2] No such file or directory: 'Schwärze [-b2w6fKq-ls].f247.webm'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2648, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3211, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3379, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3366, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3339, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 27, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 124, in wrapper
    return func(self, info)
  File "/usr/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 828, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 288, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 295, in real_run_ffmpeg
    oldest_mtime = min(
  File "/usr/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 296, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path, _ in input_path_opts if path)
FileNotFoundError: [Errno 2] No such file or directory: 'Schwärze [-b2w6fKq-ls].f247.webm'

 Θ file Schwärze\ \[-b2w6fKq-ls\].f247.webm
Schwärze [-b2w6fKq-ls].f247.webm: WebM
```

**Comment by emphoeller** [comment]
It works for me (both with the latest release and the previous one that you used):

```
$ python3 yt-dlp_2022.05.18/yt-dlp/yt_dlp/__main__.py -v 'https://www.youtube.com/watch?v=-b2w6fKq-ls'
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=-b2w6fKq-ls']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-41-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: certifi-2019.11.28, pycrypto-2.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=-b2w6fKq-ls
[youtube] -b2w6fKq-ls: Downloading webpage
[youtube] -b2w6fKq-ls: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -b2w6fKq-ls: Downloading 1 format(s): 247+251
[debug] Invoking http downloader on "https://rr1---sn-i5h7lnls.googlevideo.com/videoplayback?expire=1653094740&ei=9OSHYqK6IP6xx_AP78mBwAM&ip=2a02%3A8109%3A1a40%3A3595%3A6944%3A239c%3A34f6%3A7718&id=o-AGTOIs60fXilsEt5AD7lGmxS0gGrR2ABg52cZBdyJE9Q&itag=247&source=youtube&requiressl=yes&mh=dj&mm=31%2C26&mn=sn-i5h7lnls%2Csn-5hneknek&ms=au%2Conr&mv=m&mvi=1&pl=40&initcwndbps=1540000&vprv=1&mime=video%2Fwebm&gir=yes&clen=840256021&dur=34822.495&lmt=1646006663446241&mt=1653072540&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIu-nDa4AWAH5bQ1mc93QvVoZJbQuq_Nj7tg78wD0TlfAiEAoOW0ZmIb6x-BDhZZGKc9O35Miohv8Yj0o9Z8g9aC73Q%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKlieQsINFKyiO4QicPz1D6MhqFmFnFOYRI48nJSxveUAiEA_8hwCeKWV46Iw4R4WTmiAHZjxRIA_A6rm_vuGEOtf9c%3D"
[download] Destination: Schwärze [-b2w6fKq-ls].f247.webm
[download] 100% of 801.33MiB in 01:12
[debug] Invoking http downloader on "https://rr1---sn-i5h7lnls.googlevideo.com/videoplayback?expire=1653094740&ei=9OSHYqK6IP6xx_AP78mBwAM&ip=2a02%3A8109%3A1a40%3A3595%3A6944%3A239c%3A34f6%3A7718&id=o-AGTOIs60fXilsEt5AD7lGmxS0gGrR2ABg52cZBdyJE9Q&itag=251&source=youtube&requiressl=yes&mh=dj&mm=31%2C26&mn=sn-i5h7lnls%2Csn-5hneknek&ms=au%2Conr&mv=m&mvi=1&pl=40&initcwndbps=1540000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=451879189&dur=34822.521&lmt=1646010978429248&mt=1653072540&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgGsLpccLP2wYDTfEqYdGigDp1AnVf8j4bchD6ReRQuC4CIQC8XoYkGvPtSJbahkxRMN-6j9R-FUqPo_E_Gw1En_xuLA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKlieQsINFKyiO4QicPz1D6MhqFmFnFOYRI48nJSxveUAiEA_8hwCeKWV46Iw4R4WTmiAHZjxRIA_A6rm_vuGEOtf9c%3D"
[download] Destination: Schwärze [-b2w6fKq-ls].f251.webm
[download] 100% of 430.95MiB in 00:38
[Merger] Merging formats into "Schwärze [-b2w6fKq-ls].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Schwärze [-b2w6fKq-ls].f247.webm' -i 'file:Schwärze [-b2w6fKq-ls].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Schwärze [-b2w6fKq-ls].temp.webm'
Deleting original file Schwärze [-b2w6fKq-ls].f251.webm (pass -k to keep)
Deleting original file Schwärze [-b2w6fKq-ls].f247.webm (pass -k to keep)
```

As a quick fix, you can specify e.g. `-o '{Title} [%(id)s].%(ext)s'` to keep the title out of the filenames and then edit the names manually.

Interestingly, the “ä” used in this title is not the standard [U+00E4](https://util.unicode.org/UnicodeJsps/character.jsp?a=00e4), but a regular “a” followed by the [U+0308 “COMBINING DIAERESIS”](https://util.unicode.org/UnicodeJsps/character.jsp?a=0308) – though I don’t know why that would cause problems.

After deleting the files you got from experimenting with `LC_ALL` and retrying without modified locale variables, what does the following print for you?

```
ls *'[-b2w6fKq-ls]'* | hexdump -C
```

Also try copypasting the filename out of the error message into a file and hexdumping it. If the binary representations differ, we know that somewhere in the code, the filename is encoded wrongly.

And in case this is indeed caused by your locale settings, what does `locale` print for you? On my system (where it works), I get:

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

**Comment by entropie** [comment]
Tanks for your time and reply.

```
 Θ ls *'[-b2w6fKq-ls]'* | hexdump -C
00000000  53 63 68 77 c3 a4 72 7a  65 20 5b 2d 62 32 77 36  |Schw..rze [-b2w6|
00000010  66 4b 71 2d 6c 73 5d 2e  66 32 34 37 2e 77 65 62  |fKq-ls].f247.web|
00000020  6d 0a 53 63 68 77 c3 a4  72 7a 65 20 5b 2d 62 32  |m.Schw..rze [-b2|
00000030  77 36 66 4b 71 2d 6c 73  5d 2e 66 32 34 37 2e 77  |w6fKq-ls].f247.w|
00000040  65 62 6d 2e 70 61 72 74  0a 53 63 68 77 61 cc 88  |ebm.part.Schwa..|
00000050  72 7a 65 20 5b 2d 62 32  77 36 66 4b 71 2d 6c 73  |rze [-b2w6fKq-ls|
00000060  5d 2e 66 32 35 31 2e 77  65 62 6d 0a 53 63 68 77  |].f251.webm.Schw|
00000070  c3 a4 72 7a 65 20 5b 2d  62 32 77 36 66 4b 71 2d  |..rze [-b2w6fKq-|
00000080  6c 73 5d 2e 66 32 35 31  2e 77 65 62 6d 0a        |ls].f251.webm.|
0000008e
```

```
 Θ locale
LANG=en_US.utf8
LC_CTYPE=en_GB.utf8
LC_NUMERIC="en_US.utf8"
LC_TIME=en_GB.utf8
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```


> And in case this is indeed caused by your locale settings,

I thought that already. Also I connect via ssh with the kitty terminal which might also cause some problems. Thanks for confirming its on my end.

**Comment by emphoeller** [comment]
Your locale settings seem fine to me.

This is kind of difficult to debug without being able to reproduce it on my system. I have been looking through the source code, but so far I found nothing.

If you update yt-dlp and remove the files again or go to a different directory, what does the following print for you?

```
yt-dlp -v https://www.youtube.com/watch\?v\=-b2w6fKq-ls -f 133,160,278 -o '%(title)s [%(id)s].f%(format_id)s.%(ext)s' ; ls -ash *'[-b2w6fKq-ls]'* ; ls -a *'[-b2w6fKq-ls]'* | hexdump -C ; python3 -c 'import sys; print(sys.platform)'
```

**Comment by entropie** [comment]
I actually dont want to install different versions. I use the one in my packet manager (portage/gentoo). 

The problem is probably somewhere rooted in my setup (I use node red to watch a telegram bot for messages from my mother so she can download audiobooks from youtube and play it from my home server via jellyfin. 

You helped my to get a workaround. I pretty much try it again if it fails on renaming with -o. I can later rename.

    youtube-dl -v -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 "$var" ||
        youtube-dl -v -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o '---%(id)s].%(ext)s' "$var"

Not pretty, but working.
