### ISSUE TITLE
myclip

### ISSUE THREAD

**Issue by zeref-dragneel** [yt-dlp/yt-dlp#3756]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Vietnam

### Example URLs

- Single Video: http://myclip.vn/video/8723097
- Playlist: http://myclip.vn/playlist/xem-toan-bo-playlist/159715

### Description

myclip

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'http://myclip.vn/video/8723097']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: http://myclip.vn/video/8723097
[generic] 8723097: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 8723097: Downloading webpage
[generic] 8723097: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: http://myclip.vn/video/8723097
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: http://myclip.vn/video/8723097
```

**Comment by HobbyistDev** [comment]
From your url, i found the m3u8 is in `input` tag that have `id="url"` and `name="url"`
Here's the html tag that i described:
```
<input type="hidden" id="url" name="url" value="https://s3zen.myclip.vn/video1/2022/03/10/17/78c41507/78c41507-9c26-49b3-97a4-e29dda01c0db_m.m3u8?timestamp=1656911837&amp;token=fe4539a7d15457ed3be0f681490e59f2&amp;smctrack=/index.php/video/8723097?"/>
```
As we can see, we can grab the value of `value` and then input this to `yt-dlp`.
Here's the log of yt-dlp:
```
~\test_download>yt-dlp -v "https://s3zen.myclip.vn/video1/2022/03/10/17/78c41507/78c41507-9c26-49b3-97a4-e29dda01c0db_m.m3u8?timestamp=1656911837&amp" --ignore-config
[debug] Command-line config: ['-v', 'https://s3zen.myclip.vn/video1/2022/03/10/17/78c41507/78c41507-9c26-49b3-97a4-e29dda01c0db_m.m3u8?timestamp=1656911837&amp', '--ignore-config']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://s3zen.myclip.vn/video1/2022/03/10/17/78c41507/78c41507-9c26-49b3-97a4-e29dda01c0db_m.m3u8?timestamp=1656911837&amp
[generic] 78c41507-9c26-49b3-97a4-e29dda01c0db_m: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 78c41507-9c26-49b3-97a4-e29dda01c0db_m: Downloading webpage
[debug] Identified a M3U playlist
[generic] 78c41507-9c26-49b3-97a4-e29dda01c0db_m: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 78c41507-9c26-49b3-97a4-e29dda01c0db_m: Downloading 1 format(s): 4322
[debug] Invoking hlsnative downloader on "https://s3zen.myclip.vn/video1/2022/03/10/17/78c41507/78c41507-9c26-49b3-97a4-e29dda01c0db_5_.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 314
[download] Destination: 78c41507-9c26-49b3-97a4-e29dda01c0db_m [78c41507-9c26-49b3-97a4-e29dda01c0db_m].mp4
[debug] File locking is not supported. Proceeding without locking
[download]   1.0% of ~766.58MiB at  915.22KiB/s ETA 09:18 (frag 3/314)
ERROR: Interrupted by user
```
