### ISSUE TITLE
DMAX (ITALY) unsupported URL

### ISSUE THREAD

**Issue by fedepr** [yt-dlp/yt-dlp#3757]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

italy

### Description

Hi, i wanted to download this one "https://dmax.it/programmi-dmax/uomini-di-pietra/stagione-2-episodio-1-cambio-al-vertice" but it says "unsupported URL". Some time ago i downloaded successfully this similar one "https://dmax.it/programmi-dmax/uomini-di-pietra/stagione-1-episodio-1-le-cave-di-marmo" but now it's either not working the same.
What's wrong?

### Verbose log

```shell
yt-dlp.exe -vU -F "https://dmax.it/program
mi-dmax/uomini-di-pietra/stagione-2-episodio-1-cambio-al-vertice"
[debug] Command-line config: ['-vU', '-F', 'https://dmax.it/programmi-dmax/uomin
i-di-pietra/stagione-2-episodio-1-cambio-al-vertice']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websoc
kets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://dmax.it/programmi-dmax/uomini-di-pietr
a/stagione-2-episodio-1-cambio-al-vertice
[generic] stagione-2-episodio-1-cambio-al-vertice: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] stagione-2-episodio-1-cambio-al-vertice: Downloading webpage
[generic] stagione-2-episodio-1-cambio-al-vertice: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://dmax.it/programmi-dmax/uomini-di-pietra/stagione
-2-episodio-1-cambio-al-vertice
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://dmax.it/programmi-dmax/u
omini-di-pietra/stagione-2-episodio-1-cambio-al-vertice
```

**Comment by fedepr** [comment]
hi, thanks, probably the last time i downloaded from discovery plus (https://www.discoveryplus.com/it/video/uomini-di-pietra/stagione-1-episodio-1-le-cave-di-marmo and similars) - but now it's not working anymore (it says only available for registered users but the video is marked as "free" and i can't proceed - #2073 - do you want me to reopen it?)

**Comment by fedepr** [comment]
hi! you're right, but as i mentioned on the previous post, i tried to download from https://www.discoveryplus.com/it/video/uomini-di-pietra/stagione-1-episodio-1-le-cave-di-marmo it says "only available for registered users" but the video is marked as "free" and i can't proceed (seems similar to #2073 that was workarounded on last Christmas)

**Comment by dirkf** [comment]
What happens with https://www.discoveryplus.it/video/uomini-di-pietra/stagione-1-episodio-1-le-cave-di-marmo ?

I get a better result, in that the metadata JSON is fetched but the manifest URLs give 400 Bad Request (and the same with my yt-dl branch), but that appeared to give actual formats in #2073.

**Comment by fedepr** [comment]
how do you reach this poins? with some parameters? is this  #2361 or #2950 maybe?

**Comment by dirkf** [comment]
More debugging required ... (but no, 400 != 404). Have you got a verbose log for the [quoted .it URL](https://github.com/yt-dlp/yt-dlp/issues/3757#issuecomment-1128994025)?

**Comment by fedepr** [comment]
here it is

yt-dlp.exe -Uv -F "https://www.discoveryplus.com/it/video/uomini-di-pietra/stagione-1-episodio-1-le-cave-di-marmo"
[debug] Command-line config: ['-Uv', '-F', 'https://www.discoveryplus.com/it/video/uomini-di-pietra/stagione-1-episodio-1-le-cave-di-marmo']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-12-23-git-60ead5cd68-essentials_build-www.gyan.dev (setts), ffprobe 2021-12-23-git-60ead5cd68-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [DiscoveryPlusItaly] Extracting URL: https://www.discoveryplus.com/it/video/uomini-di-pietra/stagione-1-episodio-1-le-cave-di-marmo
[debug] Using fake IP 79.58.79.103 (IT) as X-Forwarded-For
[DiscoveryPlusItaly] uomini-di-pietra/stagione-1-episodio-1-le-cave-di-marmo: Downloading JSON metadata
ERROR: [DiscoveryPlusItaly] uomini-di-pietra/stagione-1-episodio-1-le-cave-di-marmo: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\dplay.py", line 369, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 92, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.py", line 50, in _process_errors

**Comment by dirkf** [comment]
So basically, if we get the metadata from disco-api.discoveryplus.it, we can fetch the video metadata containing what look like valid DASH and HLS manifest links, but they give 400 Bad Request, whereas, if we get the metadata from eu1-prod-direct.discoveryplus.com, it gives 400 Bad Request directly.

A trace of the problem video being played in a browser might reveal which header, API URL, query param, cookie, etc needs to be modified.

The message '...only available for registered users...' occurs when the error code from the failed request is `access.denied.missingpackage` or `invalid.token`. The debugger says it's the latter when failing to fetch the metadata.

No token is sent when using `DiscoveryPlusBaseIE`. If its `_update_disco_api_headers()` method also calls the superclass method, we have a token and get valid metadata. Then we get 403 on fetching the video data.

**Comment by si70so15** [comment]
Hi,
I have the same problem too, sometime after a lot of retries the download start.

Thank you.
Simon
