### ISSUE TITLE
[Broken] Bitchute: No video formats found

### ISSUE THREAD

**Issue by MagicalDrizzle** [yt-dlp/yt-dlp#376]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.06.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['--prefer-ffmpeg', '--ffmpeg-location', './ffmpeg.exe', '-v', '--merge-output-format', 'mkv', 'https://www.bitchute.com/video/cPS1x9c9vmVG']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.01 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffprobe 2021-05-19-git-2261cc6d8a-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/cPS1x9c9vmVG
[BitChute] cPS1x9c9vmVG: Downloading webpage
[BitChute] cPS1x9c9vmVG: Checking video URL
[BitChute] cPS1x9c9vmVG: video URL is invalid, skipping: HTTP Error 401: Unauthorized
ERROR: No video formats found; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1128, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1149, in __extract_info
  File "yt_dlp\extractor\common.py", line 564, in extract
  File "yt_dlp\extractor\bitchute.py", line 82, in _real_extract
  File "yt_dlp\extractor\common.py", line 1743, in _sort_formats
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

**Comment by pukkandan** [comment]
For me, this video doesn't play in browser either. Other videos work fine

**Comment by jasonkhanlar** [comment]
## Checklist



- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ


## Verbose log



```
PASTE VERBOSE LOG HERE
[debug] Command-line config: ['--verbose', 'https://www.bitchute.com/video/VARIOUS/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.06.23 
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.12.14-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/VARIOUS/
[BitChute] VARIOUS: Downloading webpage
[BitChute] VARIOUS: Checking video URL
[BitChute] VARIOUS: video URL is invalid, skipping: HTTP Error 401: Unauthorized
ERROR: No video formats found; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "~/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1138, in wrapper
    return func(self, *args, **kwargs)
  File "~/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1163, in __extract_info
    ie_result = ie.extract(url)
  File "~/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 568, in extract
    ie_result = self._real_extract(url)
  File "~/.local/lib/python3.9/site-packages/yt_dlp/extractor/bitchute.py", line 82, in _real_extract
    self._sort_formats(formats)
  File "~/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1748, in _sort_formats
    raise ExtractorError('No video formats found')
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.


```



## Description



WRITE DESCRIPTION HERE

[Broken] Bitchute: No video formats found #376

ERROR: No video formats found; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

**Comment by HalvorRaknes** [comment]
This video plays for me.
