### ISSUE TITLE
yt-dlp does not retry after a socket read timeout

### ISSUE THREAD

**Issue by ion1** [yt-dlp/yt-dlp#3771]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Global

### Description

I am trying to download [a video](https://youtu.be/8o0U4NFcsxg) with which YouTube seems to be having some problems at the moment. It is buffering constantly in the browser as well, so it is understandable that yt-dlp is downloading it slowly and encountering timeouts. (Other videos work fine.) The issue is that yt-dlp seems to give up when encountering a timeout rather than retrying. Restarting yt-dlp manually resumes downloading and makes progress until the next timeout.

I don't know whether this is a site-specific issue.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-R', 'inf', '--file-access-retries', 'inf', '--fragment-retries', 'inf', 'https://youtu.be/8o0U4NFcsxg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.2-static, ffprobe 4.2.2-static
[debug] Optional libraries: certifi, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://youtu.be/8o0U4NFcsxg
[youtube] 8o0U4NFcsxg: Downloading webpage
[youtube] 8o0U4NFcsxg: Downloading android player API JSON
[youtube] 8o0U4NFcsxg: Downloading m3u8 information
[youtube] 8o0U4NFcsxg: Downloading MPD manifest
[youtube] 8o0U4NFcsxg: Downloading m3u8 information
[youtube] 8o0U4NFcsxg: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 8o0U4NFcsxg: Downloading 1 format(s): 247+140
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1652836176/ei/.../ip/.../id/8o0U4NFcsxg.1/source/yt_live_broadcast/requiressl/yes/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/force_finished/1/vprv/1/pacing/0/itag_bl/.../keepalive/yes/fexp/.../itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cas%2Cforce_finished%2Cvprv%2Citag%2Cplaylist_type/sig/..."
[download] DSCOVR Live Investigations [8o0U4NFcsxg].f247.webm has already been downloaded
[download] 100% of 333.01MiB
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1652836176/ei/.../ip/.../id/8o0U4NFcsxg.1/source/yt_live_broadcast/requiressl/yes/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/force_finished/1/vprv/1/pacing/0/itag_bl/.../keepalive/yes/fexp/.../itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cas%2Cforce_finished%2Cvprv%2Citag%2Cplaylist_type/sig/..."
[dashsegments] Total fragments: 2456
[download] Destination: DSCOVR Live Investigations [8o0U4NFcsxg].f140.m4a
[download]  61.6% of ~99.07MiB at  3.43KiB/s ETA 01:35:24 (frag 1514/2456)ERROR: unable to download video data: The read operation timed out
Traceback (most recent call last):
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3120, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2846, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/downloader/dash.py", line 56, in real_download
    return self.download_and_append_fragments_multiple(*args)
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 387, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], pack_func=pack_func, finish_func=finish_func)
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 530, in download_and_append_fragments
    download_fragment(fragment, ctx)
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 473, in download_fragment
    if self._download_fragment(ctx, fragment['url'], info_dict, headers):
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 134, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/downloader/http.py", line 128, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/ion/.local/bin/yt-dlp/yt_dlp/utils.py", line 1543, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by coletdjnz** [comment]
Yeah this was a minor regression from https://github.com/yt-dlp/yt-dlp/commit/a2e77303e3385da640a0904cd6cb76235fa9691b

Should be fixed by https://github.com/yt-dlp/yt-dlp/commit/5faf6528fb701724ac32e0a487f92281c7800bda
