### ISSUE TITLE
South Park downloader gets video parts but does not combine them

### ISSUE THREAD

**Issue by Scrooge200FES** [yt-dlp/yt-dlp#3774]
### Checklist

- [X] I'm reporting a broken site
- [x] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

#1465 is similar, but this seems to have stopped working since then (it's been four months). I'm still having this issue on the latest version (2022.04.08). I tested with https://southpark.cc.com/es/episodios/46s8wh/south-park-bajalo-temporada-21-ep-2 and https://www.southpark.de/full-episodes/s21e02-put-it-down.

I end up with five separate video files, with the ad breaks splitting them up (named "Put It Down S1 [7c45fe5a-ca13-467e-b17f-8d59b220f00c]", "Put It Down S2 [66560acc-b72e-4f06-be62-4a98f0c2cda1]", etc.)

If I run this with a "--concat-playlist always" parameter, it downloads them as normal, but towards the end:

> [download] Destination: Put It Down S5 [a0270ab5-fbe7-495c-a305-eea9374b0205].mp4
[download] 100% of 2.65MiB in 00:03
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Put It Down S5 [a0270ab5-fbe7-495c-a305-eea9374b0205].mp4"
ERROR: Concatenation is not supported when downloading multiple separate formats

It doesn't merge them, and keeps them separate. Is there a way I can have it merge after downloading?

### Verbose log

```shell
Microsoft Windows [Version 10.0.19043.1706]
(c) Microsoft Corporation. All rights reserved.

C:\[REMOVED]>yt-dlp -vU --concat-playlist always https://southpark.cc.com/es/episodios/46s8wh/south-park-bajalo-temporada-21-ep-2
[debug] Command-line config: ['-vU', '--concat-playlist', 'always', 'https://southpark.cc.com/es/episodios/46s8wh/south-park-bajalo-temporada-21-ep-2']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev (setts), ffprobe 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [southpark.cc.com:español] Extracting URL: https://southpark.cc.com/es/episodios/46s8wh/south-park-bajalo-temporada-21-ep-2
[southpark.cc.com:español] south-park-bajalo-temporada-21-ep-2: Downloading webpage
[southpark.cc.com:español] 60d791a0-157b-4a82-a099-15503be03b56: Downloading info
[southpark.cc.com:español] 7c45fe5a-ca13-467e-b17f-8d59b220f00c: Extracting information
[southpark.cc.com:español] 7c45fe5a-ca13-467e-b17f-8d59b220f00c: Downloading video urls
[southpark.cc.com:español] 7c45fe5a-ca13-467e-b17f-8d59b220f00c: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.cc.com:español] 66560acc-b72e-4f06-be62-4a98f0c2cda1: Extracting information
[southpark.cc.com:español] 66560acc-b72e-4f06-be62-4a98f0c2cda1: Downloading video urls
[southpark.cc.com:español] 66560acc-b72e-4f06-be62-4a98f0c2cda1: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.cc.com:español] 2660946e-bc07-4f41-b049-6766ae7b51fd: Extracting information
[southpark.cc.com:español] 2660946e-bc07-4f41-b049-6766ae7b51fd: Downloading video urls
[southpark.cc.com:español] 2660946e-bc07-4f41-b049-6766ae7b51fd: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.cc.com:español] 7c904af4-5fd6-43ec-a2ce-0b3402130b2f: Extracting information
[southpark.cc.com:español] 7c904af4-5fd6-43ec-a2ce-0b3402130b2f: Downloading video urls
[southpark.cc.com:español] 7c904af4-5fd6-43ec-a2ce-0b3402130b2f: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.cc.com:español] a0270ab5-fbe7-495c-a305-eea9374b0205: Extracting information
[southpark.cc.com:español] a0270ab5-fbe7-495c-a305-eea9374b0205: Downloading video urls
[southpark.cc.com:español] a0270ab5-fbe7-495c-a305-eea9374b0205: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Put It Down
[southpark.cc.com:español] playlist Put It Down: Collected 5 videos; downloading 5 of them
[download] Downloading video 1 of 5
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7c45fe5a-ca13-467e-b17f-8d59b220f00c: Downloading 1 format(s): hls-4430
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/02/04/54/17/44bde07f8bcb4dd59d9d37edabfb807c/1798292/0/stream_1920x1080_4285612_3424389292.m3u8?tk=st=1652839717~exp=1652854117~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/02/04/54/17/44bde07f8bcb4dd59d9d37edabfb807c/1798292/0/stream_1920x1080_4285612_3424389292.m3u8*~hmac=0bf4677c39512579dad62ae90dc29b1a4d4659dc603b3cdda313eef7ca29bd82&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 6
[download] Destination: Put It Down S1 [7c45fe5a-ca13-467e-b17f-8d59b220f00c].mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[download] 100% of 16.85MiB in 00:01
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Put It Down S1 [7c45fe5a-ca13-467e-b17f-8d59b220f00c].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Put It Down S1 [7c45fe5a-ca13-467e-b17f-8d59b220f00c].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Put It Down S1 [7c45fe5a-ca13-467e-b17f-8d59b220f00c].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Put It Down S1 [7c45fe5a-ca13-467e-b17f-8d59b220f00c].temp.mp4"
[download] Downloading video 2 of 5
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 66560acc-b72e-4f06-be62-4a98f0c2cda1: Downloading 1 format(s): hls-2556
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/02/04/54/30/b82662fb3e654310b7cce8ed9f1878af/1798293/0/stream_1920x1080_2454303_2371761952.m3u8?tk=st=1652839734~exp=1652854134~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/02/04/54/30/b82662fb3e654310b7cce8ed9f1878af/1798293/0/stream_1920x1080_2454303_2371761952.m3u8*~hmac=1cdf7a3ae7048777e4496cf7d5af72165c057a46045711ac84d6481696e05f27&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 98
[download] Destination: Put It Down S2 [66560acc-b72e-4f06-be62-4a98f0c2cda1].mp4
[download] 100% of 178.03MiB in 00:38
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Put It Down S2 [66560acc-b72e-4f06-be62-4a98f0c2cda1].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Put It Down S2 [66560acc-b72e-4f06-be62-4a98f0c2cda1].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Put It Down S2 [66560acc-b72e-4f06-be62-4a98f0c2cda1].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Put It Down S2 [66560acc-b72e-4f06-be62-4a98f0c2cda1].temp.mp4"
[download] Downloading video 3 of 5
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2660946e-bc07-4f41-b049-6766ae7b51fd: Downloading 1 format(s): hls-3008
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/02/04/54/36/d0f69b96dbd2499aafd419f72bb8bab7/1798295/0/stream_1920x1080_2895674_3934235010.m3u8?tk=st=1652840343~exp=1652854743~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/02/04/54/36/d0f69b96dbd2499aafd419f72bb8bab7/1798295/0/stream_1920x1080_2895674_3934235010.m3u8*~hmac=3d86079f201bebe310a0d9bed90d75de3a1f35321393fadb255e0f6952134895&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 64
[download] Destination: Put It Down S3 [2660946e-bc07-4f41-b049-6766ae7b51fd].mp4
[download] 100% of 136.19MiB in 00:24
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Put It Down S3 [2660946e-bc07-4f41-b049-6766ae7b51fd].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Put It Down S3 [2660946e-bc07-4f41-b049-6766ae7b51fd].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Put It Down S3 [2660946e-bc07-4f41-b049-6766ae7b51fd].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Put It Down S3 [2660946e-bc07-4f41-b049-6766ae7b51fd].temp.mp4"
[download] Downloading video 4 of 5
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7c904af4-5fd6-43ec-a2ce-0b3402130b2f: Downloading 1 format(s): hls-2503
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/02/04/54/36/460e9871dbe04c5d9282631489bb5e47/1798296/0/stream_1920x1080_2402022_1637006584.m3u8?tk=st=1652840645~exp=1652855045~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/02/04/54/36/460e9871dbe04c5d9282631489bb5e47/1798296/0/stream_1920x1080_2402022_1637006584.m3u8*~hmac=060510a36fc1634aaf2d3d0b349d9e90115fbf10ee606d4ca070bbc17324e195&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 52
[download] Destination: Put It Down S4 [7c904af4-5fd6-43ec-a2ce-0b3402130b2f].mp4
[download] 100% of 92.18MiB in 00:54
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Put It Down S4 [7c904af4-5fd6-43ec-a2ce-0b3402130b2f].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Put It Down S4 [7c904af4-5fd6-43ec-a2ce-0b3402130b2f].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Put It Down S4 [7c904af4-5fd6-43ec-a2ce-0b3402130b2f].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Put It Down S4 [7c904af4-5fd6-43ec-a2ce-0b3402130b2f].temp.mp4"
[download] Downloading video 5 of 5
[debug] Default format spec: bestvideo*+bestaudio/best
[info] a0270ab5-fbe7-495c-a305-eea9374b0205: Downloading 1 format(s): hls-1490
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/02/04/54/43/35a82ee5c9ec4addbf8b2770ded46fee/1798297/0/stream_1920x1080_1408781_2740622666.m3u8?tk=st=1652844738~exp=1652859138~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/02/04/54/43/35a82ee5c9ec4addbf8b2770ded46fee/1798297/0/stream_1920x1080_1408781_2740622666.m3u8*~hmac=017bb6110dd91f05b5e5a74dc1189cbad9a6d7e21dd1e31666f3a86c77334605&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: Put It Down S5 [a0270ab5-fbe7-495c-a305-eea9374b0205].mp4
[download] 100% of 2.65MiB in 00:00
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Put It Down S5 [a0270ab5-fbe7-495c-a305-eea9374b0205].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Put It Down S5 [a0270ab5-fbe7-495c-a305-eea9374b0205].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Put It Down S5 [a0270ab5-fbe7-495c-a305-eea9374b0205].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Put It Down S5 [a0270ab5-fbe7-495c-a305-eea9374b0205].temp.mp4"
ERROR: Concatenation is not supported when downloading multiple separate formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1613, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1828, in __process_playlist
  File "yt_dlp\YoutubeDL.py", line 3366, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3339, in run_pp
  File "yt_dlp\postprocessor\common.py", line 27, in run
  File "yt_dlp\postprocessor\common.py", line 124, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 1160, in run
yt_dlp.utils.PostProcessingError: Concatenation is not supported when downloading multiple separate formats
```

**Comment by pukkandan** [comment]
1e9969f4f517eab4077f0b03eee9ef3afa493486 should have fixed it. Check with the new release

**Comment by Scrooge200FES** [comment]
I tried running it again normally and it split up the parts, but when I added "--concat-playlist always", that fixed it. Thank you!
