### ISSUE TITLE
in a for loop, from a Batch script, '--verbose' output doesn't produce an STDERR error. And for some reasons need redirectors.

### ISSUE THREAD

**Issue by Illegal-Services** [yt-dlp/yt-dlp#3792]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I guess to understand my issue you need to know a bit of Batch, I don't really know how to explain differently, if you have questions, feel free to ask me.
```bat
@echo off

::Not working, displaying the full '-v' output outside of the 'do' statemennt:
for /f "delims=" %%A in ('yt-dlp.exe -f "CREATE_AN_STDERR" -v "https://www.youtube.com/watch?v=dQw4w9WgXcQ"') do (
    echo 1.%%A
)

::using the redirectors: '2>&1' kindda makes it working:
::Work-around, displaying the full '-v' output inside the 'do' statemennt, BUT colored STDERR doesn't happen outside of the 'do' statemennt:
for /f "delims=" %%A in ('2^>^&1 yt-dlp.exe -f "CREATE_AN_STDERR" -v "https://www.youtube.com/watch?v=dQw4w9WgXcQ"') do (
    echo 2.%%A
)

pause
exit /b 0
```

### Verbose log

```shell
[debug] Command-line config: ['-f', 'CREATE_AN_STDERR', '-v', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error utf-8, screen cp1252 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1479, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1535, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2622, in process_video_result
yt_dlp.utils.ExtractorError: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats

1.[youtube] dQw4w9WgXcQ: Downloading webpage
1.[youtube] dQw4w9WgXcQ: Downloading android player API JSON
2.[debug] Command-line config: ['-f', 'CREATE_AN_STDERR', '-v', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ']
2.[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
2.[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
2.[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
2.[debug] Checking exe version: ffprobe -bsfs
2.[debug] Checking exe version: avprobe -bsfs
2.[debug] Checking exe version: ffmpeg -bsfs
2.[debug] Checking exe version: avconv -bsfs
2.[debug] exe versions: none
2.[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
2.[debug] Proxy map: {}
2.[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
2.[youtube] dQw4w9WgXcQ: Downloading webpage
2.[youtube] dQw4w9WgXcQ: Downloading android player API JSON
2.[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
2.[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
2.ERROR: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats
2.Traceback (most recent call last):
2.  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
2.  File "yt_dlp\YoutubeDL.py", line 1479, in __extract_info
2.  File "yt_dlp\YoutubeDL.py", line 1535, in process_ie_result
2.  File "yt_dlp\YoutubeDL.py", line 2622, in process_video_result
2.yt_dlp.utils.ExtractorError: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats
Appuyez sur une touche pour continuer...
```
```

**Comment by pukkandan** [comment]
Verbose log is always written to `stderr` and for loop does not capture stderr by default.

As for the color, there is a feature request for forcing it #3643

**Comment by Illegal-Services** [comment]
Would you be able to add a setting where we can choose where we want to write the verbose log please?

**Comment by pukkandan** [comment]
Verbose log is printed to stderr for a long time (since the start?). I don't see much point in adding an option to change where it goes since we are pigeon-holed to printing info, --print, verbose, warning and error into just 2 streams (stdout/err) anyway.

Why not just look for the `[verbose] ` prefix to distinguish them?

**Comment by Illegal-Services** [comment]
i will do that then, thank you for the suggestion. I didn't think about it before.
