### ISSUE TITLE
Cannot recode video when using sponsorblock-remove

### ISSUE THREAD

**Issue by Ryhon0** [yt-dlp/yt-dlp#3846]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Using the `--recode-video` option with the `--sponsorblock-remove` option on a video that has blocked segments results in an error

### Verbose log

```shell
[ryhon@amd-arch ~]$ yt-dlp -vU --sponsorblock-remove=music_offtopic -f worstaudio --recode-video ogg https://youtu.be/_Yhyp-_hX2s
[debug] Command-line config: ['-vU', '--sponsorblock-remove=music_offtopic', '-f', 'worstaudio', '--recode-video', 'ogg', 'https://youtu.be/_Yhyp-_hX2s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.9-zen1-1-zen-x86_64-with-glibc2.35
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube] Extracting URL: https://youtu.be/_Yhyp-_hX2s
[youtube] _Yhyp-_hX2s: Downloading webpage
[youtube] _Yhyp-_hX2s: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/201c?service=YouTube&categories=%5B%22music_offtopic%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%5D
[SponsorBlock] Found 1 segments in the SponsorBlock database
[info] _Yhyp-_hX2s: Downloading 1 format(s): 139
[download] Eminem - Lose Yourself [HD] [_Yhyp-_hX2s].ogg has already been downloaded
[VideoConvertor] Not converting media file "Eminem - Lose Yourself [HD] [_Yhyp-_hX2s].ogg"; already is in target format ogg
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Eminem - Lose Yourself [HD] [_Yhyp-_hX2s].ogg'
ERROR: Postprocessing: Cannot cut video since the real and expected durations mismatch. Different chapters may have already been removed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3204, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3374, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3361, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3340, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/modify_chapters.py", line 46, in run
    raise PostProcessingError('Cannot cut video since the real and expected durations mismatch. '
yt_dlp.utils.PostProcessingError: Cannot cut video since the real and expected durations mismatch. Different chapters may have already been removed
```

**Comment by pukkandan** [comment]
This happened because the command was run multiple times on the same video file. Despite the checks yt-dlp to account for this case, it got cut twice resulting in the final file having mismatching durations. I have made the test stricter to avoid this as much as possible
