### ISSUE TITLE
Requesting support for javsubbed.net NSFW

### ISSUE THREAD

**Issue by teijiIshida** [yt-dlp/yt-dlp#3862]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

US

### Example URLs

http://javsubbed.net/ipx-850-there-was-a-record-breaking-downpour-during-the-business-trip-so-i-ended-up-sharing-a-room-with-my-subordinate/

### Description

I would like to request support for downloading both video AND subtitle file for javsubbed.net. Currently, I can get the download link by holding SHIFT+Right click -> Copy Video Link but it cannot extract/download the subtitle. Please add support for extracting/downloading the subtitle file. The link provided is NSFW. 

Thank you.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-f', 'bestvideo*+bestaudio/best', '--embed-subs', 'http://javsubbed.net/ipx-850-there-was-a-record-breaking-downpour-during-the-business-trip-so-i-ended-up-sharing-a-room-with-my-subordinate/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n5.0.1-5-gc935240586-20220505 (setts), ffprobe n5.0.1-5-gc935240586-20220505
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: http://javsubbed.net/ipx-850-there-was-a-record-breaking-downpour-during-the-business-trip-so-i-ended-up-sharing-a-room-with-my-subordinate/
[generic] ipx-850-there-was-a-record-breaking-downpour-during-the-business-trip-so-i-ended-up-sharing-a-room-with-my-subordinate: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] ipx-850-there-was-a-record-breaking-downpour-during-the-business-trip-so-i-ended-up-sharing-a-room-with-my-subordinate: Downloading webpage
[generic] ipx-850-there-was-a-record-breaking-downpour-during-the-business-trip-so-i-ended-up-sharing-a-room-with-my-subordinate: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: http://javsubbed.net/ipx-850-there-was-a-record-breaking-downpour-during-the-business-trip-so-i-ended-up-sharing-a-room-with-my-subordinate/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\generic.py", line 4031, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: http://javsubbed.net/ipx-850-there-was-a-record-breaking-downpour-during-the-business-trip-so-i-ended-up-sharing-a-room-with-my-subordinate/
```

**Comment by Lesmiscore** [comment]
> I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge

We woN7 add support for piracy websites.
