### ISSUE TITLE
[Viki] I can't download from viki

### ISSUE THREAD

**Issue by bladeosen** [yt-dlp/yt-dlp#3863]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Description

I can't download viki's videos. It shows error of DRM

### Verbose log

```shell
C:\Users\chris\Desktop\pro>yt-dlp.exe -vU --all-subs --embed-subs --hls-prefer-ffmpeg https://www.viki.com/videos/1122160v-melo-holic-episode-1
[debug] Command-line config: ['-vU', '--all-subs', '--embed-subs', '--hls-prefer-ffmpeg', 'https://www.viki.com/videos/1122160v-melo-holic-episode-1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [viki] Extracting URL: https://www.viki.com/videos/1122160v-melo-holic-episode-1
[viki] 1122160v: Downloading video JSON
[viki] 1122160v: Downloading video streams JSON
[viki] 1122160v: Downloading initial MPD manifest
[viki] 1122160v: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: ar, bg, de, el, en, es, fi, fr, hu, id, it, ja, ko, nl, pl, pt, ro, sr, tl, vi
WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [viki] 1122160v: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1479, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1535, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2622, in process_video_result
yt_dlp.utils.ExtractorError: [viki] 1122160v: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by NanaMizukiAnother7** [comment]
The link you received is DRM-protected:
> WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them

**Comment by wxolp** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29502

**Comment by wxolp** [comment]
You can use this command to download:

~~~
ffmpeg -cenc_decryption_key 73bc8a2b4c46adfb2ac73da2feb788e9 `
-i 'https://manifest-viki.viki.io/v1/1122160v/limelight/main/mpd/normal/viki/high/sd/ww/dt2_dt3/manifest.mpd?h_timestamp=1654798555&tag=mpdhd%3Ahigh%3Aww%3AsourceVIKI%3Ampd%3Acached%3Adt2_dt3&app=100000a&h_country=us&h_data_center=iowa-2&h_host=playback-streams-fd6b99684-68x5p&sig=eac61d03e2ade3599207efa7332467cf026c785b' `
-c copy -map 0:0 dec.mp4
~~~
