### ISSUE TITLE
Funimation: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>

### ISSUE THREAD

**Issue by DarkHorse-APP2** [yt-dlp/yt-dlp#3868]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Mexico

### Description

I was trying to download from Funimation using this command: _**yt-dlp.exe -N 16 -P "LOVE IS WAR" -u "unknow@outlook.com" -p "quesrtus." -r 720p -v -i https://www.funimation.com/v/kaguya-sama-love-is-war/miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk**_ and I got this error **_urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)_**

Then I added this command --no-check-certificate and it only worked for video tracks but not audio.

### Verbose log

```shell
C:\Users\kArL\Desktop\WDL Encrypted Files\YouTube Dowloader>yt-dlp.exe -N 16 -P "LOVE IS WAR" -u "unknow@outlook.com" -p "quesrtus." -r 720p -v -i https://www.funimation.com/v/kaguya-sama-love-is-war/miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk
[debug] Command-line config: ['-N', '16', '-P', 'LOVE IS WAR', '-u', 'PRIVATE', '-p', 'PRIVATE', '-r', '720p', '-v', '-i', 'https://www.funimation.com/v/kaguya-sama-love-is-war/miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.7.9 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg git-2019-10-31-7c872df, ffprobe git-2019-10-31-7c872df
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[funimation:page] Logging in
[funimation:page] Checking geo-location
[debug] [funimation:page] Extracting URL: https://www.funimation.com/v/kaguya-sama-love-is-war/miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk
[funimation:page] kaguya-sama-love-is-war_miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/811879
[Funimation] 811879: Downloading player webpage for 811879
ERROR: [Funimation] 811879: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\funimation.py", line 185, in _real_extract
  File "yt_dlp\extractor\common.py", line 935, in _download_webpage
  File "yt_dlp\extractor\common.py", line 800, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 785, in _request_webpage

  File "urllib\request.py", line 1350, in do_open
  File "http\client.py", line 1277, in request
  File "http\client.py", line 1323, in _send_request
  File "http\client.py", line 1272, in endheaders
  File "http\client.py", line 1032, in _send_output
  File "http\client.py", line 972, in send
  File "http\client.py", line 1447, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 767, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "yt_dlp\utils.py", line 1545, in https_open
  File "urllib\request.py", line 1352, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
```

**Comment by pukkandan** [comment]
Check if `--no-check-certificate` works

**Comment by DarkHorse-APP2** [comment]
> Check if `--no-check-certificate` works

I have added this command --no-check-certificate and it only worked for video tracks but not audio.

**Comment by pukkandan** [comment]
log?

**Comment by coletdjnz** [comment]
> [debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)

also update your yt-dlp

**Comment by DarkHorse-APP2** [comment]
> > [debug] yt-dlp version 2022.04.08 [[7884ade](https://github.com/yt-dlp/yt-dlp/commit/7884ade65e6599e53d1a449e6548f87b09668e0d)] (win_exe)
> 
> also update your yt-dlp

Now speed is extremely slow.

**Comment by DarkHorse-APP2** [comment]
> @DarkHorse-APP2 Please redact your password from the original message (unless a maintainer redacts it first)
> 
> Please make sure to also delete it from your comment's edit history
> 
> Note for maintainers: please delete it from #github on Discord

Here's my username and password: sevij24572@nifect.com Github.2022
Actually I tried to download a free video in japanese, I'm not premium on it.

**Comment by gamer191** [comment]
Um, I asked you to redact your password, not to share it. If a developer is willing to work on it, they will ask you to email (or discord DM etc) your password. You don't need to share it publically

note for maintainers: please add the `can-share-account` label

**Comment by DarkHorse-APP2** [comment]
> Um, I asked you to redact your password, not to share it. If a developer is willing to work on it, they will ask you to email (or discord DM etc) your password. You don't need to share it publically
> 
> note for maintainers: please add the `can-share-account` label

It's just a free account so it doesnt matter, whoever wanna help with it, would it be ok.

**Comment by gamer191** [comment]
> It's just a free account so it doesnt matter

Fair enough. I guess it's up to the maintainers whether to allow it or not (I'm not a maintainer)

**Comment by october262** [comment]
> 

this works -  yt-dlp --no-check-certificate "https://www.funimation.com/v/kaguya-sama-love-is-war/miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk"

**Comment by DarkHorse-APP2** [comment]
> this works - yt-dlp --no-check-certificate "https://www.funimation.com/v/kaguya-sama-love-is-war/miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk"

I have added this command --no-check-certificate and it only worked for video tracks but not audio and speed is extremely slow.

**Comment by october262** [comment]
> > this works - yt-dlp --no-check-certificate "https://www.funimation.com/v/kaguya-sama-love-is-war/miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk"
> 
> I have added this command --no-check-certificate and it only worked for video tracks but not audio and speed is extremely slow.

the episode plays back ok for me. both the audio & video.
are you not getting audio with yours ??

**Comment by DarkHorse-APP2** [comment]
> > > this works - yt-dlp --no-check-certificate "https://www.funimation.com/v/kaguya-sama-love-is-war/miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk"
> > 
> > 
> > I have added this command --no-check-certificate and it only worked for video tracks but not audio and speed is extremely slow.
> 
> the episode plays back ok for me. both the audio & video. are you not getting audio with yours ??

No it doesn’t work for me, it only download video track.

**Comment by coletdjnz** [comment]
Even without an account and latest certifi I can reproduce the SSL certificate failed message.

The SSL error occurs on https://www.funimation.com

wget, curl, etc. all fail on it too.

Possibly duplicate of https://github.com/yt-dlp/yt-dlp/issues/157

**Comment by october262** [comment]
> > > > this works - yt-dlp --no-check-certificate "https://www.funimation.com/v/kaguya-sama-love-is-war/miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk"
> > > 
> > > 
> > > I have added this command --no-check-certificate and it only worked for video tracks but not audio and speed is extremely slow.
> > 
> > 
> > the episode plays back ok for me. both the audio & video. are you not getting audio with yours ??
> 
> No it doesn’t work for me, it only download video track.

are you trying to get the English audio ?? because when i downloaded the episode
i got the Japanese audio, if i try selecting the English DUB language version
it has a lock on it and wants you to upgrade your subscription.

**Comment by DarkHorse-APP2** [comment]
> > > > > this works - yt-dlp --no-check-certificate "https://www.funimation.com/v/kaguya-sama-love-is-war/miyuki-shirogane-still-hasnt-done-it-kaguya-wants-to-be-figured-out-kaguya-wants-to-walk"
> > > > 
> > > > 
> > > > I have added this command --no-check-certificate and it only worked for video tracks but not audio and speed is extremely slow.
> > > 
> > > 
> > > the episode plays back ok for me. both the audio & video. are you not getting audio with yours ??
> > 
> > 
> > No it doesn’t work for me, it only download video track.
> 
> are you trying to get the English audio ?? because when i downloaded the episode i got the Japanese audio, if i try selecting the English DUB language version it has a lock on it and wants you to upgrade your subscription.

No I just wanted to watch it in its original language which is Japanese, other languages are blocked due type of subscription I mean only available for premium users.

**Comment by coletdjnz** [comment]
I have a feeling this may be due to lack of AIA fetching in python - https://bugs.python.org/issue18617

Testing with https://pypi.org/project/aia/ it works

I'm not entirely sure how this works so correct me if I'm wrong

Also please take off-topic discussion elsewhere (e.g. in the discord). This is for discussion regarding the SSL issue.

**Comment by DarkHorse-APP2** [comment]
> I have a feeling this may be due to lack of AIA fetching in python - https://bugs.python.org/issue18617
> 
> Testing with https://pypi.org/project/aia/ it works
> 
> I'm not entirely sure how this works so correct me if I'm wrong
> 
> Also please take off-topic discussion elsewhere (e.g. in the discord or open a new issue). This is for discussion regarding the SSL issue.

SSL issue it’s fixed by adding —no-check-certificate command, but it only work for video tracks and the speed it’s extremely slow.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/3868#issuecomment-1137884796

**Comment by Lesmiscore** [comment]
Certificates are checked before cookies are being sent...

**Comment by Jules-A** [comment]
> Certificates are checked before cookies are being sent...

Oh, didn't know that... Maybe it's because I'm using the latest version of Python/dependencies? :/

**Comment by CZeil** [comment]
From my point of view I think the Funimation extractor should be rewritten, as it has several problems that I have experienced (and that other users have reported).
