### ISSUE TITLE
Amazon Prime  / FreeVee fail

### ISSUE THREAD

**Issue by arnstein99** [yt-dlp/yt-dlp#3870]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

This is my first attempt to download a video from Amazon Prime. If yt-dlp does not support this site, then here is my proposed solution: in the documentation, mention that "Amazon Prime" is NOT a part of the supported site "AmazonStore". I suspect that even trying to yt-dlp from "Amazon Prime" is a user error.

My platform is an Apple iMac using the most recent operating system (Monterey) from Apple.

I logged into my Amazon account and watched a few seconds of episode 4, "Bosch Legacy." This provided me with a URL. I immediately fed this URL to yt-dlp.

### Verbose log

```shell
imac3 530> sudo yt-dlp -vU 'https://www.amazon.com/Bosch-Legacy-Season-Official-Trailer/dp/B09PQKKS8F/ref=sr_1_1?crid=HNPJ99DJ2FE1&keywords=bosch+legacy&qid=1653508136&s=instant-video&sprefix=bosch+legacy%2Cinstant-video%2C197&sr=1-1'
Password:
[debug] Command-line config: ['-vU', 'https://www.amazon.com/Bosch-Legacy-Season-Official-Trailer/dp/B09PQKKS8F/ref=sr_1_1?crid=HNPJ99DJ2FE1&keywords=bosch+legacy&qid=1653508136&s=instant-video&sprefix=bosch+legacy%2Cinstant-video%2C197&sr=1-1']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.8.0 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: certifi, sqlite
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.04.08
Current Build Hash 5f011b97e0bc12b61f3b5f49776e66f2eaf534b98b60ee12b3d8c0a15780cc9f
Updating to version 2022.05.18 ...
Updated yt-dlp to version 2022.05.18; Restart yt-dlp to use the new version
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 869, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 859, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3264, in download
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3237, in wrapper
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1399, in extract_info
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 749, in get_info_extractor
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 28, in __new__
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 23, in _get_real_class
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 548, in _get_data
zipimport.ZipImportError: bad local file header: '/usr/local/bin/yt-dlp'
```

**Comment by pukkandan** [comment]
Amazon Prime videos have DRM and so cannot be downloaded with yt-dlp
