### ISSUE TITLE
Merging to MKV fails: ffmpeg reports "non monotonically increasing dts"

### ISSUE THREAD

**Issue by africola** [yt-dlp/yt-dlp#3877]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

## First things first 

I'm unsure whether it is appropriate to post this as a yt-dlp bug here, as a ffmpeg bug elsewhere, or as a general yt-dlp/ffmpeg question on SX or so. However, at the end of day it's yt-dlp that's failing to work as intended, so from a user perspective this is arguably a bug in yt-dlp.

## The issue

In short, when downloading certain Youtube videos where the best video and audio stream are incompatible, merging to MKV may fail, with ffmpeg returning an error and complaining about "non monotonically increasing dts". A full debug log is below.

I don't know what this means, other than that perhaps the MKV specs make MKV unable to hold the video stream in question

FWIW: the issue also arises when invoking ffmpeg manually, with the same ffmpeg command line that yt-dlp uses. Leaving out the audio stream as an input file and leaving out the audio stream mapping produces the same error, so it's something about the video stream.

Perhaps there are options that could be passed to ffmpeg to work around this; in that case, it would be great if yt-dlp could be tweaked accordingly. Perhaps it's a bug in ffmpeg, or at least in the (somewhat older) version I'm using; in that case, please let me know and close this bug (in that order, ideally). Perhaps it's something else.

### System info

Windows + Cygwin (x86_64, in case it matters), current yt-dlp (2022.05.18), older ffmpeg (4.2.3).

### An example URL

https://www.youtube.com/watch?v=d1bYwC2kM7Q (safe for work)

I don't know if this affects other sites; when I download videos it's almost always from Youtube. It's not _directly_ site-specific, so I'm filing this as a generic bug.

## Finally
Thank you - for looking into the bug, but more importantly, for all your work on yt-dlp. 

### Verbose log

```shell
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=d1bYwC2kM7Q']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit)
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.2.3
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=d1bYwC2kM7Q
[youtube] d1bYwC2kM7Q: Downloading webpage
[youtube] d1bYwC2kM7Q: Downloading android player API JSON
[youtube] d1bYwC2kM7Q: Downloading MPD manifest
[youtube] d1bYwC2kM7Q: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] d1bYwC2kM7Q: Downloading 1 format(s): 303+251
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1653612339/ei/0sqPYoKsPNOn1gLBl4mYBg/ip/188.108.178.144/id/7756d8c02da433b4/source/youtube/requiressl/yes/playback_host/rr2---sn-i5heen7z.googlevideo.com/mh/KY/mm/31%2C26/mn/sn-i5heen7z%2Csn-5goeen7d/ms/au%2Conr/mv/m/mvi/2/pl/21/tx/24200495/txs/24200493%2C24200494%2C24200495%2C24201799%2C24201800/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/885000/spc/4ocVC0xa5N-R3vumQaoG9fTbhmTP/vprv/1/mt/1653590466/fvip/6/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cspc%2Cvprv%2Citag/sig/AOq0QJ8wRQIgYrGL9TqLhq7whANNlSjGemjRc4wGbWw4inIayMW1WCsCIQDm1vwFmQ_SHpEYPW6u1LcGYoIg9OAVAm_Li_TYCKz1iw%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhALY1MXpGYE6KnqsfMU53TpBorFtvA_Xgm0aUsd8XRVKKAiBwOSWByW6JmuRQn3rKJu_YSrVl3FO0aO8FRwZae0ZsLA%3D%3D"
[download] Allianz Ladies Slovak Open Highlights [d1bYwC2kM7Q].f303.webm has already been downloaded
[download] 100% of 200.22MiB
[debug] Invoking http downloader on "https://rr2---sn-i5heen7z.googlevideo.com/videoplayback?expire=1653612339&ei=08qPYtniIeinx_APu62BsAo&ip=188.108.178.144&id=o-AE8w20VX6XBpG2wSrsp8NwH5gvngQhneh6Bw6LIwPpvA&itag=251&source=youtube&requiressl=yes&mh=KY&mm=31%2C26&mn=sn-i5heen7z%2Csn-5go7yne6&ms=au%2Conr&mv=m&mvi=2&pl=21&initcwndbps=885000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=9193873&otfp=1&dur=644.981&lmt=1564977913923873&mt=1653590466&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALnk4B1l-fWol8OCMBHZR-LtpCrxeigh4MADiInyuAK7AiALuRR6xJDzq6kWtZUsGF4EwMjrd4huV_srPYWpmP1bMA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANwKWBvWXSKXr_Y_MffSndnWh0AYSIhOT8kuw1jnlmJ1AiEA_7PpN5XdlFdgCuycZOHhMezfijOLyqx2uJ5aKc_RA3s%3D"
[download] Allianz Ladies Slovak Open Highlights [d1bYwC2kM7Q].f251.webm has already been downloaded
[download] 100% of 8.77MiB
[Merger] Merging formats into "Allianz Ladies Slovak Open Highlights [d1bYwC2kM7Q].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Allianz Ladies Slovak Open Highlights [d1bYwC2kM7Q].f303.webm" -i "file:Allianz Ladies Slovak Open Highlights [d1bYwC2kM7Q].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Allianz Ladies Slovak Open Highlights [d1bYwC2kM7Q].temp.webm"
[debug] ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'file:Allianz Ladies Slovak Open Highlights [d1bYwC2kM7Q].f303.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 116
                    : Segment-Durations-Ms: 5140,5000,5060,5600(r=57),5460,5740,5600(r=1),5020,5380,5600(r=47),3300,
                    :
                    :
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 50 fps, 50 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:Allianz Ladies Slovak Open Highlights [d1bYwC2kM7Q].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:10:44.98, start: -0.007000, bitrate: 114 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, webm, to 'file:Allianz Ladies Slovak Open Highlights [d1bYwC2kM7Q].temp.webm':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 116
                    : Segment-Durations-Ms: 5140,5000,5060,5600(r=57),5460,5740,5600(r=1),5020,5380,5600(r=47),3300,
                    :
                    :
    encoder         : Lavf58.29.100
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 50 fps, 50 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[webm @ 00000000003ee1c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5160 >= 5140
av_interleaved_write_frame(): Invalid argument
frame=  260 fps=0.0 q=-1.0 Lsize=    2272kB time=00:00:05.16 bitrate=3605.8kbits/s speed=54.9x
video:2228kB audio:80kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3204, in process_info
  File "yt_dlp\YoutubeDL.py", line 3374, in post_process
  File "yt_dlp\YoutubeDL.py", line 3361, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3340, in run_pp
  File "yt_dlp\postprocessor\common.py", line 25, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 827, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 282, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 321, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by pukkandan** [comment]
See pinned issue

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/871

**Comment by africola** [comment]
Thanks for the pointer, & sorry for the noise!
