### ISSUE TITLE
[REQ] onedrive.com

### ISSUE THREAD

**Issue by jazz1611** [yt-dlp/yt-dlp#3895]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://1drv.ms/v/s!Anyis2jII3eKhAaXhk2KeJwqIzo4?e=fYBCSQ
https://1drv.ms/v/s!Anyis2jII3eKhAfovC1RLG6ghuE8?e=o4fgiw
https://argunostudio-my.sharepoint.com/:v:/g/personal/subteam_arguno_com/EZDwqlrNllJOleTXJTc5U7gBaOehw4xfW33PItKYDn42eQ?e=hhfo7l

### Description

hello, can you support "onedrive" in yt-dlp? there link is example for testing.

### Verbose log

```shell
C:\Users\Administrator>youtube-dl -UvF "https://1drv.ms/v/s!Anyis2jII3eKhAaXhk2KeJwqIzo4?e=fYBCSQ"
[debug] Command-line config: ['-UvF', 'https://1drv.ms/v/s!Anyis2jII3eKhAaXhk2KeJwqIzo4?e=fYBCSQ']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0-full_build-www.gyan.dev (setts), ffprobe 5.0-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://1drv.ms/v/s!Anyis2jII3eKhAaXhk2KeJwqIzo4?e=fYBCSQ
[generic] s!Anyis2jII3eKhAaXhk2KeJwqIzo4?e=fYBCSQ: Requesting header
WARNING: [generic] Could not send HEAD request to https://1drv.ms/v/s!Anyis2jII3eKhAaXhk2KeJwqIzo4?e=fYBCSQ: HTTP Error 404: Not Found
[generic] s!Anyis2jII3eKhAaXhk2KeJwqIzo4?e=fYBCSQ: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] s!Anyis2jII3eKhAaXhk2KeJwqIzo4?e=fYBCSQ: Extracting information
[debug] Looking for video embeds
[redirect] Following redirect to https://onedrive.live.com/?cid=8a7723c868b3a27c&id=8A7723C868B3A27C%21518&ithint=video,mp4&authkey=!AJeGTYp4nCojOjg
[debug] [generic] Extracting URL: https://onedrive.live.com/?cid=8a7723c868b3a27c&id=8A7723C868B3A27C%21518&ithint=video,mp4&authkey=!AJeGTYp4nCojOjg
[generic] ?cid=8a7723c868b3a27c&id=8A7723C868B3A27C!518&ithint=video,mp4&authkey=!AJeGTYp4nCojOjg: Requesting header
WARNING: [generic] Could not send HEAD request to https://onedrive.live.com/?cid=8a7723c868b3a27c&id=8A7723C868B3A27C%21518&ithint=video,mp4&authkey=!AJeGTYp4nCojOjg: HTTP Error 404: Not Found
[generic] ?cid=8a7723c868b3a27c&id=8A7723C868B3A27C!518&ithint=video,mp4&authkey=!AJeGTYp4nCojOjg: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] ?cid=8a7723c868b3a27c&id=8A7723C868B3A27C!518&ithint=video,mp4&authkey=!AJeGTYp4nCojOjg: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://onedrive.live.com/?cid=8a7723c868b3a27c&id=8A7723C868B3A27C%21518&ithint=video,mp4&authkey=!AJeGTYp4nCojOjg
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\generic.py", line 4031, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://onedrive.live.com/?cid=8a7723c868b3a27c&id=8A7723C868B3A27C%21518&ithint=video,mp4&authkey=!AJeGTYp4nCojOjg
```

**Comment by C0D3D3V** [comment]
Your last link is a sharepoint link and not a onedrive link. You are requesting here two extractors at once. Onedrive and sharepoint. There APIs are not the same. I currently looking into the sharepoint API and probably will implement the extractor

**Comment by C0D3D3V** [comment]
btw. your last link is not copyright free... please provide a better example.

**Comment by pukkandan** [comment]
None of the examples are valid anymore

**Comment by jazz1611** [comment]
hello,
there is new link valid with copyright free
https://1drv.ms/u/s!AtOM4nXMml6LhVj4W7QN8Is0mkMS?e=bdvw8H
https://api.onedrive.com/v1.0/shares/s!AtOM4nXMml6LhVj4W7QN8Is0mkMS/root/content (download original file)

i will find other sharepoint link at soon
