### ISSUE TITLE
[HBO] Support whole shows

### ISSUE THREAD

**Issue by PotterProgrammer** [yt-dlp/yt-dlp#3898]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

Attempting to download "Last Week Tonight with John Oliver" from HBO gives an "Unsupported URL" error.  I can watch the show in the browser (no account required).  Previously this (and youtube-dl) were able to download episodes.  Now neither does. Here is an example:
```
yt-dlp -vU  https://www.hbo.com/last-week-tonight-with-john-oliver
[debug] Command-line config: ['-vU', 'https://www.hbo.com/last-week-tonight-with-john-oliver']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-110-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, pycrypto-2.6.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.hbo.com/last-week-tonight-with-john-oliver
[generic] last-week-tonight-with-john-oliver: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] last-week-tonight-with-john-oliver: Downloading webpage
[generic] last-week-tonight-with-john-oliver: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.hbo.com/last-week-tonight-with-john-oliver
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.hbo.com/last-week-tonight-with-john-oliver
```

### Verbose log

```shell
yt-dlp -vU  https://www.hbo.com/last-week-tonight-with-john-oliver
[debug] Command-line config: ['-vU', 'https://www.hbo.com/last-week-tonight-with-john-oliver']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-110-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, pycrypto-2.6.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.hbo.com/last-week-tonight-with-john-oliver
[generic] last-week-tonight-with-john-oliver: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] last-week-tonight-with-john-oliver: Downloading webpage
[generic] last-week-tonight-with-john-oliver: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.hbo.com/last-week-tonight-with-john-oliver
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.hbo.com/last-week-tonight-with-john-oliver
```

**Comment by gamer191** [comment]
Can I please clarify, is the link you are trying to download a 2-minute trailer?

**Comment by october262** [comment]
i was able to download the "subway" episode but sadly
the episode(s) are DRM protected.

**Comment by gamer191** [comment]
> the episode(s) are DRM protected.

They work for me, and I have DRM disabled. Are you sure you aren't thinking of hbomax.com (as opposed to hbo.com)

**Comment by PotterProgrammer** [comment]
I was wanting to download the free episodes (like "Subway").

**Comment by october262** [comment]
> I was wanting to download the free episodes (like "Subway").

you can download the episodes but they will not play correctly.
i just get green pictures  freezes  & static.
tried with both DRM enabled (firefox) & DRM disabled (Brave)
same result on both browsers.

**Comment by PotterProgrammer** [comment]
All I know is that in 2021, I could download episodes, and now yt-dlp says that it is an unsupported URL and I am getting nothing at all.

**Comment by gamer191** [comment]
> tried with both DRM enabled (firefox) & DRM disabled (Brave)

If you want to test if something is drm protected, the easiest way is to visit the url in a drm disabled browser. Testing the video file in both browsers won't achieve anything.

Anyway, I just tested it and the website is not drm protected

**Comment by pukkandan** [comment]
> I was wanting to download the free episodes (like "Subway").

Pass the URL of the episode. The provided link only contains a trailer

@gamer191 Are you just saying the trailer is DRM-free?

**Comment by ischmidt20** [comment]
I can download the "Subway" video by snooping for m3u8 and passing that in directly. I think it is simply an  extractor/website issue as when you click on the video, the URL doesn't update so yt-dlp can't find a video

**Comment by gamer191** [comment]
> Pass the URL of the episode. The provided link only contains a trailer

You have to scroll down. Admittedly, it will be annoying for yt-dlp that there are no episode specific links (as far as I can see). But I guess the url is a series url, so it could download the entire series, unless `--no-playlist` is passed (which could download the trailer instead).



> @gamer191 Are you just saying the trailer is DRM-free?

I was talking about the episodes, but the trailer is also drm free

> I can download the "Subway" video by snooping for m3u8 and passing that in directly. I think it is simply an extractor/website issue as when you click on the video, the URL doesn't update so yt-dlp can't find a video

yt-dlp fails on most websites which haven't been specifically added to yt-dlp. If you want a downloader that works on all websites, use a combination of https://www.downthemall.net/ and https://addons.mozilla.org/en-US/firefox/addon/hls-stream-detector/ (I can't vouch for the safety of either, and personally I would only run the stream detector in a separate profile, but it's up to you; Also, you'll have to find your own stream snooper if you use chrome).

You'll pretty quickly realise that you're much better off with yt-dlp, at long as your website is supported

**Comment by pukkandan** [comment]
> Previously this (and youtube-dl) were able to download episodes. Now neither does. Here is an example:

If OP meant to download the whole show, this makes no sense. In any case, I will treat this as a request for HBO playlist support for now

**Comment by gamer191** [comment]
> If OP meant to download the whole show, this makes no sense. In any case, I will treat this as a request for HBO playlist support for now

Well, OP said this:
> I was wanting to download the free episodes (like "Subway").

And I can't see how to download this without downloading the whole show. OP could use `--playlist-items` if they want to download only one episode. Now that I think about it, that actually bring up another issue, because the playlist should include the trailer and web exclusives, but where in the list should they go. Perhaps an extractor argument will be required
