### ISSUE TITLE
Certain TikTok videos are 'not available' despite most videos working fine

### ISSUE THREAD

**Issue by tim-ufer** [yt-dlp/yt-dlp#3914]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Description

I'm using yt-dlp to scrape TikTok metadata and despite the ongoing profile download issue, it's working quite well overall.
However, I've discovered a few rare videos which trigger yt-dlp's `Video not available` error. This consistently happens to 1-3 posts out of hundreds that I'm scraping while looking all the same in the web browser.
**To emphasize, this is not a general problem with all of TikTok but only a few select videos like [this one](https://www.tiktok.com/@marijnkuipers/video/7097568903169150213)**

I'm using the latest version of the Python pip package and use the following code to produce the error:
```py
ydl_opts = {
    'paths': {"home": "/data/videos/",
              "temp": "/data/tmp/"},
}
headers = {
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36',
}
url = "https://www.tiktok.com/@marijnkuipers/video/7097568903169150213"
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(url, download=False)
```

### Verbose log

```shell
[TikTok] 7097568903169150213: Downloading video details
[TikTok] 7097568903169150213: Downloading video feed
WARNING: [TikTok] 7097568903169150213: Video not available; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; Retrying with feed workaround
WARNING: [TikTok] 7097568903169150213: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; Retrying with webpage
[TikTok] 7097568903169150213: Downloading webpage
ERROR: [TikTok] 7097568903169150213: Unable to download webpage: The read operation timed out (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\extractor\common.py", line 768, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 3596, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\appst\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\appst\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\appst\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\utils.py", line 1420, in https_open
    functools.partial(_create_http_connection, self, conn_class, True), req, **kwargs)
  File "C:\Users\appst\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1353, in do_open
    r = h.getresponse()
  File "C:\Users\appst\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1369, in getresponse
    response.begin()
  File "C:\Users\appst\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "C:\Users\appst\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\appst\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\appst\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\appst\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\extractor\common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\extractor\tiktok.py", line 517, in _real_extract
    self._download_webpage(url, video_id)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\extractor\common.py", line 936, in _download_webpage
    expected_status=expected_status)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\extractor\common.py", line 801, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\extractor\common.py", line 786, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: Unable to download webpage: The read operation timed out (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\extractor\common.py", line 668, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.ExtractorError: [TikTok] 7097568903169150213: Unable to download webpage: The read operation timed out (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Medienlager/DEUS/src-tiktok-scraper/testing.py", line 44, in <module>
    info = ydl.extract_info(url, download=False)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1386, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1413, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 936, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "D:\Medienlager\DEUS\src-tiktok-scraper\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 879, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [TikTok] 7097568903169150213: Unable to download webpage: The read operation timed out (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Menard01** [comment]
Right click on the video and chose download

**Comment by Bricio** [comment]
The video is not available in browser too.
![image](https://user-images.githubusercontent.com/216170/171020091-cba517f3-d12f-4dd5-8388-971610bcb506.png)

yt-dlp cant download what are unavailable.

remember, 
if you need to have an account to see the video you need to pass this info to yt-dlp. otherwise you will not be logged-in.

**Comment by tim-ufer** [comment]
@Bricio That seems to be the common reason for this error but I can view it just fine in my browser without even logging in :s
![image](https://user-images.githubusercontent.com/60989861/171022483-c5ef7b92-ecc9-4a22-a132-f61662b7b332.png)

**Comment by Bricio** [comment]
Probably is this issue #3551 then? for me both links returns unavailable.
