### ISSUE TITLE
Subtitle parse error on DockerCon streams

### ISSUE THREAD

**Issue by Smankusors** [yt-dlp/yt-dlp#3930]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I tried to download one of the DockerCon 2022 streams, with the subtitles. But because for some reason the stream contains blank webvtt fragment, the yt-dlp fails to parse it. Here's the command line I used,
```
yt-dlp --write-subs https://stream.mux.com/xviYRr5fyaLGKH55iGjAizsdQmtfDNsF.m3u8
```

And here's the contents of Frag28

```
WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:900000

```

I thought this would be a simple fix, so I decided to try open the PR to fix this, but confused on this line

https://github.com/yt-dlp/yt-dlp/blob/4a2f19abbd61274358211c2e3b1d9658cfbdcdde/yt_dlp/webvtt.py#L219-L220

Maybe that line should be changed to return empty instead of raising error? wdyt?

Btw I used the yt-dlp from 9c0412cf6b2257b314a6e1cc5ac07edc03f6d6ea

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--write-subs', 'https://stream.mux.com/xviYRr5fyaLGKH55iGjAizsdQmtfDNsF.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version 2022.05.18 [b14d52355] (source) 
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 9c0412cf6 
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0 
[debug] Checking exe version: ffmpeg -bsfs 
[debug] Checking exe version: ffprobe -bsfs 
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev 
[debug] Optional libraries: Crypto-3.10.4, certifi-2021.05.30, sqlite3-2.6.0 
[debug] Proxy map: {} 
Latest version: 2022.05.18, Current version: 2022.05.18 
yt-dlp is up to date (2022.05.18) 
[debug] [generic] Extracting URL: https://stream.mux.com/xviYRr5fyaLGKH55iGjAizsdQmtfDNsF.m3u8 
[generic] xviYRr5fyaLGKH55iGjAizsdQmtfDNsF: Requesting header 
WARNING: [generic] Could not send HEAD request to https://stream.mux.com/xviYRr5fyaLGKH55iGjAizsdQmtfDNsF.m3u8: HTTP Error 405: Method Not 
Allowed
[generic] xviYRr5fyaLGKH55iGjAizsdQmtfDNsF: Downloading webpage 
[debug] Identified a direct video link 
[generic] xviYRr5fyaLGKH55iGjAizsdQmtfDNsF: Downloading m3u8 information 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en 
[debug] Default format spec: bestvideo*+bestaudio/best 
[info] xviYRr5fyaLGKH55iGjAizsdQmtfDNsF: Downloading 1 format(s): 4755 
[info] Writing video subtitles to: xviYRr5fyaLGKH55iGjAizsdQmtfDNsF [xviYRr5fyaLGKH55iGjAizsdQmtfDNsF].en.vtt 
[debug] Invoking hlsnative downloader on "https://manifest-gce-us-east1-production.cfcdn.mux.com/tLNTEJQIesPUbn6JY02id7Zfx33GKM01uuny01FwFAEF2R6Lpu02gyoMGAqDKIiPmzQZmXFHQ74hdX4/subtitles.m3u8?expires=1654624800&signature=NjI5ZjkyMjBfZTcxZmJkNDAwYTA2NjJkNzE4NjkxNGRiOWNjZTA2ZjhkMmI5ODE0OWMyZTM2ZmNhYzZkYzdmMWQxZGUxMzAzZg=="
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 321 
[download] Destination: xviYRr5fyaLGKH55iGjAizsdQmtfDNsF [xviYRr5fyaLGKH55iGjAizsdQmtfDNsF].en.vtt 
[debug] File locking is not supported on this platform. Proceeding without locking
[download] xviYRr5fyaLGKH55iGjAizsdQmtfDNsF [xviYRr5fyaLGKH55iGjAizsdQmtfDNsF].en.vtt.part-Frag28 has already been downloaded
[download]   8.7% of ~245.27KiB at    7.81KiB/s ETA  Unknown (frag 28/321)ERROR: Parse error at position 56 (near '') 
Traceback (most recent call last):
  File "W:\GitHub\yt-dlp\yt_dlp\YoutubeDL.py", line 1403, in wrapper
    return func(self, *args, **kwargs)
  File "W:\GitHub\yt-dlp\yt_dlp\YoutubeDL.py", line 1487, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "W:\GitHub\yt-dlp\yt_dlp\YoutubeDL.py", line 1544, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "W:\GitHub\yt-dlp\yt_dlp\YoutubeDL.py", line 2655, in process_video_result
    self.process_info(new_info)
  File "W:\GitHub\yt-dlp\yt_dlp\YoutubeDL.py", line 2913, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "W:\GitHub\yt-dlp\yt_dlp\YoutubeDL.py", line 3880, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "W:\GitHub\yt-dlp\yt_dlp\YoutubeDL.py", line 2854, in dl
    return fd.download(name, new_info, subtitle)
  File "W:\GitHub\yt-dlp\yt_dlp\downloader\common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "W:\GitHub\yt-dlp\yt_dlp\downloader\hls.py", line 345, in real_download
    self.download_and_append_fragments(
  File "W:\GitHub\yt-dlp\yt_dlp\downloader\fragment.py", line 511, in download_and_append_fragments
    result = append_fragment(
  File "W:\GitHub\yt-dlp\yt_dlp\downloader\fragment.py", line 478, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "W:\GitHub\yt-dlp\yt_dlp\downloader\hls.py", line 260, in pack_fragment
    for block in webvtt.parse_fragment(frag_content):
  File "W:\GitHub\yt-dlp\yt_dlp\webvtt.py", line 351, in parse_fragment
    yield Magic.parse(parser)
  File "W:\GitHub\yt-dlp\yt_dlp\webvtt.py", line 207, in parse
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 56 (near '')

Exception ignored in: <_io.FileIO name='xviYRr5fyaLGKH55iGjAizsdQmtfDNsF [xviYRr5fyaLGKH55iGjAizsdQmtfDNsF].en.vtt.part' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name='xviYRr5fyaLGKH55iGjAizsdQmtfDNsF [xviYRr5fyaLGKH55iGjAizsdQmtfDNsF].en.vtt.part' mode='ab' closefd=True>
```

**Comment by fstirlitz** [comment]
Seems to be same underlying cause as #2867.

**Comment by Smankusors** [comment]
> Seems to be same underlying cause as #2867.

ouch sorry, seems like I'm using wrong keywords when searching existing issues 😢
