### ISSUE TITLE
[nitter] unable to extract OpenGraph description;

### ISSUE THREAD

**Issue by Thespikedballofdoom** [yt-dlp/yt-dlp#394]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running yt-dlp version **2021.06.09**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
C:\Users\itsab>"C:\Users\itsab\Videos\ow my pussy\yt-dlp.exe" https://nitter.actionsack.com/muffinqtbutt/status/1389089557186965506#m --verbose
[debug] Command-line config: ['https://nitter.actionsack.com/muffinqtbutt/status/1389089557186965506#m', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.09 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-04-14-git-c5ca18fd1b-full_build-www.gyan.dev, ffprobe 2021-04-14-git-c5ca18fd1b-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [Nitter] Extracting URL: https://nitter.actionsack.com/muffinqtbutt/status/1389089557186965506#m
[Nitter] 1389089557186965506: Downloading webpage
[Nitter] 1389089557186965506: Downloading m3u8 information
WARNING: [Nitter] unable to extract OpenGraph description; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: Unable to extract title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1133, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1154, in __extract_info
  File "yt_dlp\extractor\common.py", line 567, in extract
  File "yt_dlp\extractor\nitter.py", line 173, in _real_extract
  File "yt_dlp\extractor\common.py", line 1128, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1119, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Nitter videos can't download no matter what domain

**Comment by pukkandan** [comment]
@B0pol since you are the author of nitter extractor

**Comment by Thespikedballofdoom** [comment]
me being stupid with my script actually i think it seems to work now
