### ISSUE TITLE
BoundHub

### ISSUE THREAD

**Issue by komijadslot7** [yt-dlp/yt-dlp#3940]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Netherlands

### Example URLs

Single video: https://www.boundhub.com/videos/169268/sahara-rain-extreme/
Playlist: https://www.boundhub.com/playlists/15864/wrist-cage/
Single private video: https://www.boundhub.com/videos/222627/lovely-isobel-wren-in-bondage-4/
Playlist private: https://www.boundhub.com/playlists/17351/ballgags5/

### Description

Backend: KVS Player v6
Would like to download private and public videos and playlists.
Looks like single videos sometimes work with the generic type.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.boundhub.com/playlists/15864/wrist-cage/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.boundhub.com/playlists/15864/wrist-cage/
[generic] wrist-cage: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] wrist-cage: Downloading webpage
[generic] wrist-cage: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.boundhub.com/playlists/15864/wrist-cage/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\generic.py", line 4031, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.boundhub.com/playlists/15864/wrist-cage/
```

**Comment by jhwgh1968** [comment]
The example provided uses a dynamic Flowplayer embed generated by javascript. It is too complex for the generic extractor to detect.

**Comment by Hindiakter** [comment]
Follow in this link now
[[]](https://paintwandering.com/hutrs3fcau?key=be81961ad7abd736b010f4c5401eac71)(https://paintwandering.com/hutrs3fcau?key=be81961ad7abd736b010f4c5401eac71)

**Comment by cheese1218** [comment]
I am offering a bounty here for anyone who can create an extractor for this website, the owner of the website has made it clear that it won't be around for much longer and therefore time is of the essence and I wanted to download all my favorites from the site, [https://www.webimagedownloader.com/templates/597-boundhub.com-video-downloader/](url) this might help in figuring things out. If anyone is interested please tag or dm me in the discord server cheesylasagna._

**Comment by cheese1218** [comment]
Also couple things to note - the generic extractor does work but it won't download playlists or private videos since the cookies aren't carried over and it only works if using --impersonate chrome command.

**Comment by hrgitb** [comment]
@cheese1218 implemented and tested.
For the bounty you can send me an amazon giftcard code:
frankW719@proton.me
