### ISSUE TITLE
xVideos Playlist

### ISSUE THREAD

**Issue by komijadslot7** [yt-dlp/yt-dlp#3941]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Example URLs

Playlist: https://www.xvideos.com/favorite/49496063/wristwatches
Playlist private: https://www.xvideos.com/favorite/49497987/redheads

### Description

Would like to download private and public playlists.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.xvideos.com/favorite/49496063/wristwatches']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.xvideos.com/favorite/49496063/wristwatches
[generic] wristwatches: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] wristwatches: Downloading webpage
[generic] wristwatches: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.xvideos.com/favorite/49496063/wristwatches
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\generic.py", line 4031, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.xvideos.com/favorite/49496063/wristwatches
```

**Comment by reverse123** [comment]
You can use this userscript for the playlist page. It will record all video urls onto the current page into the localstorage variable "my_vid_urls". You have to clear this variable if it exists and then open every page of the playlist you want to download. Do not click too fast, wait for the page to load completely, otherwise some pages will not have time to record. Then copy variable "my_vid_urls" from Chrome Devtools to new file list.txt, and pass to yt-dlp like this: "yt-dlp -a list.txt"
It can be easily modified for any lists with pagination.

```// ==UserScript==
// @name         url recorder for xvideos playlists
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.xvideos.com/favorite/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=xvideos.com
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    $('#content div.thumb-under > p.title > a').each(function() {
        let was = localStorage.getItem("my_vid_urls");
        //console.log(this.href);
        localStorage.setItem("my_vid_urls", was+"\n"+this.href);
    });
    let arr = localStorage.getItem("my_vid_urls").split("\n");

    var index = arr.indexOf('null');
    if (index !== -1) {
        arr.splice(index, 1);
    }

    let uniqueArr = [...new Set(arr)];
    localStorage.setItem("my_vid_urls", uniqueArr.join("\n"));
    console.log(uniqueArr);
})();
