### ISSUE TITLE
[Instagram] RegexNotFoundError while downloading a reel

### ISSUE THREAD

**Issue by pritam20ps05** [yt-dlp/yt-dlp#3945]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Description

Getting RegexNotFoundError with instagtam while downloading https://www.instagram.com/p/CeDdG5TOldD/ . Using cookies and verified that they are still valid.

### Verbose log

```shell
[Instagram] CeDdG5TOldD: Downloading webpage
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CeDdG5TOldD: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/instagram.py", line 415, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1340, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1235, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1226, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 668, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [Instagram] CeDdG5TOldD: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pritam20ps05** [comment]
probably a duplicate but can't verify if its same as #3077
