### ISSUE TITLE
Termux | yt-dlp

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#3974]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

I tried to store a Youtube video, basically the problem is that I don't have permission to host files on the SD, but when I try to download from Crunchyroll I don't get this problem.

Ps: I tried all the external downloader options and they all ended up with the same error.

### Verbose log

```shell
YOUTUBE

[debug] Command-line config: ['--config-location', 'bin/1080.conf', 'https://youtu.be/AhQGw7I96JY']
[debug] | Config "bin/1080.conf": ['-f', '(bv[height<=1080][fps<=60]+ba)[ext*=web]', '--embed-subs', '--sub-lang', 'es,es-419,ja,en', '--sub-format', 'vtt', '--convert-subs', 'srt', '-o', '~/storage/sdcard0/%(extractor_key)s/%(title)s_(%(height)sp*%(fps)sfps)_.%(ext)s', '--downloader', 'native', '--add-metadata', '--embed-chapters', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 32bit) - Linux-4.19.127-armv7l-with-libc
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://youtu.be/AhQGw7I96JY
[youtube] AhQGw7I96JY: Downloading webpage
[youtube] AhQGw7I96JY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: ja, en
[info] AhQGw7I96JY: Downloading 1 format(s): 248+251
[info] Writing video subtitles to: /data/data/com.termux/files/home/storage/sdcard0/Youtube/Ya Boy Kongming! OP「Chitty Chitty Bang Bang」Full Ver. & High Speed Ver. Piano Cover _ Ru's Piano_(1080p*30fps)_.ja.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=AhQGw7I96JY&caps=asr&xoaf=1&xoadf=4&xosf=1&hl=en&ip=0.0.0.0&ipbits=0&expire=1654477849&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf%2Cxoadf&signature=3D82203B0FEB5FF181E062FBC0AAAE57203EC041.236DA88664110C94EC3716F0BCC3CD66D915475F&key=yt8&lang=ja&fmt=vtt"
ERROR: unable to open for writing: [Errno 1] Operation not permitted: "/data/data/com.termux/files/home/storage/sdcard0/Youtube/Ya Boy Kongming! OP「Chitty Chitty Bang Bang」Full Ver. & High Speed Ver. Piano Cover _ Ru's Piano_(1080p*30fps)_.ja.vtt.part"
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 267, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 224, in inner
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 241, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 621, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2040, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
PermissionError: [Errno 1] Operation not permitted: "/data/data/com.termux/files/home/storage/sdcard0/Youtube/Ya Boy Kongming! OP「Chitty Chitty Bang Bang」Full Ver. & High Speed Ver. Piano Cover _ Ru's Piano_(1080p*30fps)_.ja.vtt.part"


[info] Writing video subtitles to: /data/data/com.termux/files/home/storage/sdcard0/Youtube/Ya Boy Kongming! OP「Chitty Chitty Bang Bang」Full Ver. & High Speed Ver. Piano Cover _ Ru's Piano_(1080p*30fps)_.en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=AhQGw7I96JY&caps=asr&xoaf=1&xoadf=4&xosf=1&hl=en&ip=0.0.0.0&ipbits=0&expire=1654477849&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf%2Cxoadf&signature=3D82203B0FEB5FF181E062FBC0AAAE57203EC041.236DA88664110C94EC3716F0BCC3CD66D915475F&key=yt8&lang=en&fmt=vtt"
ERROR: unable to open for writing: [Errno 1] Operation not permitted: "/data/data/com.termux/files/home/storage/sdcard0/Youtube/Ya Boy Kongming! OP「Chitty Chitty Bang Bang」Full Ver. & High Speed Ver. Piano Cover _ Ru's Piano_(1080p*30fps)_.en.vtt.part"
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 267, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 224, in inner
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 241, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 621, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2040, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
PermissionError: [Errno 1] Operation not permitted: "/data/data/com.termux/files/home/storage/sdcard0/Youtube/Ya Boy Kongming! OP「Chitty Chitty Bang Bang」Full Ver. & High Speed Ver. Piano Cover _ Ru's Piano_(1080p*30fps)_.en.vtt.part"


[SubtitlesConvertor] Converting subtitles
WARNING: Skipping embedding ja subtitle because the file is missing
WARNING: Skipping embedding en subtitle because the file is missing
[debug] Invoking http downloader on "https://rr1---sn-uxab05-b05d.googlevideo.com/videoplayback?expire=1654474250&ei=qfGcYsXzPIPN4QSFpoCYBg&ip=186.151.40.157&id=o-AAD6ekPvchMluEcKsUTnJbQopWUMfynYYehlpe8bxpSd&itag=248&source=youtube&requiressl=yes&mh=4o&mm=31%2C29&mn=sn-uxab05-b05d%2Csn-hp57ynl6&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=360000&vprv=1&mime=video%2Fwebm&gir=yes&clen=45392521&dur=276.742&lmt=1653744551788735&mt=1654452301&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJcgu3SxzcMC-SAL8upw7ZDtJHzTDzZR2Q-bKgOev4QVAiBTVRKkiAuNAEi--r8ZC-B29RYiJDIGJLu1QDjze82X3w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANdApjnXu3MhRLaiiYuV1fjwE0PUtVjnI0nLmjJ78-QIAiEAkW_nt-GFMoMsYgGw82qgzRe80FvQ9aiI903O3MtSOvc%3D"
ERROR: unable to open for writing: [Errno 1] Operation not permitted: "/data/data/com.termux/files/home/storage/sdcard0/Youtube/Ya Boy Kongming! OP「Chitty Chitty Bang Bang」Full Ver. & High Speed Ver. Piano Cover _ Ru's Piano_(1080p*30fps)_.f248.webm.part"
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 267, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 224, in inner
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 241, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 621, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2040, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
PermissionError: [Errno 1] Operation not permitted: "/data/data/com.termux/files/home/storage/sdcard0/Youtube/Ya Boy Kongming! OP「Chitty Chitty Bang Bang」Full Ver. & High Speed Ver. Piano Cover _ Ru's Piano_(1080p*30fps)_.f248.webm.part"


[debug] Invoking http downloader on "https://rr1---sn-uxab05-b05d.googlevideo.com/videoplayback?expire=1654474250&ei=qfGcYsXzPIPN4QSFpoCYBg&ip=186.151.40.157&id=o-AAD6ekPvchMluEcKsUTnJbQopWUMfynYYehlpe8bxpSd&itag=251&source=youtube&requiressl=yes&mh=4o&mm=31%2C29&mn=sn-uxab05-b05d%2Csn-hp57ynl6&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=360000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=5049289&dur=276.761&lmt=1653742617823176&mt=1654452301&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgZgzNheeMSHuoJA2XNmvDWjIWkw8GY_J0KWg4rFEQK8YCIAg2zR4JtPegsoCE9QsSj1tun8Za7z9p0mNhXH0Wt15n&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANdApjnXu3MhRLaiiYuV1fjwE0PUtVjnI0nLmjJ78-QIAiEAkW_nt-GFMoMsYgGw82qgzRe80FvQ9aiI903O3MtSOvc%3D"
ERROR: unable to open for writing: [Errno 1] Operation not permitted: "/data/data/com.termux/files/home/storage/sdcard0/Youtube/Ya Boy Kongming! OP「Chitty Chitty Bang Bang」Full Ver. & High Speed Ver. Piano Cover _ Ru's Piano_(1080p*30fps)_.f251.webm.part"
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 267, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 224, in inner
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 241, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 621, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2040, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
PermissionError: [Errno 1] Operation not permitted: "/data/data/com.termux/files/home/storage/sdcard0/Youtube/Ya Boy Kongming! OP「Chitty Chitty Bang Bang」Full Ver. & High Speed Ver. Piano Cover _ Ru's Piano_(1080p*30fps)_.f251.webm.part"

CRUNCHYROLL
[debug] Command-line config: ['--config-location', 'bin/crunchyroll.conf', 'https://www.crunchyroll.com/es/dont-hurt-me-my-healer/episode-9-this-episode-features-even-more-female-guest-characters-hot-on-the-heels-842989']
[debug] | Config "bin/crunchyroll.conf": ['-f', '(b[height<=1080])[language*=ja]/[language*=zh]', '--extractor-args', 'crunchyroll:hardsub=esLA', '-o', 'storage/sdcard0/%(extractor_key)s/%(uploader)s/%(series)s (S%(season_number)sE%(episode_number)s) - %(episode)s.%(ext)s', '-n', '--downloader', 'm3u8:aria2c', '--downloader-args', 'aria2c:-j8', '--trim-filenames', '200', '--add-metadata', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 32bit) - Linux-4.19.127-armv7l-with-libc
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[crunchyroll] Getting session id
[crunchyroll] Logging in
[debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/es/dont-hurt-me-my-healer/episode-9-this-episode-features-even-more-female-guest-characters-hot-on-the-heels-842989
[crunchyroll] 842989: Downloading webpage
[crunchyroll] 842989: Downloading adaptive_hls-audio-jaJP-hardsub-esLA information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[crunchyroll] 842989: Downloading media info
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[info] 842989: Downloading 1 format(s): adaptive_hls-audio-jaJP-hardsub-esLA-8107-1
[debug] Invoking hlsnative downloader on "https://pl.crunchyroll.com/evs3/0772628fd0b828f367fdc43efb6a880c/assets/8d6afb1706cb938e63593ae9812e6de8_4519893.mp4/index-v1-a1.m3u8?Expires=1654626650&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy8wNzcyNjI4ZmQwYjgyOGYzNjdmZGM0M2VmYjZhODgwYy9hc3NldHMvOGQ2YWZiMTcwNmNiOTM4ZTYzNTkzYWU5ODEyZTZkZThfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NTQ2MjY2NTB9fX1dfQ__&Signature=bGisGdDF2ES5M4rvoLnVwYOzGbYQTgR03CbYDGmJEl-HpCDASV3HH1nWmGThYjCeWWQCTgyi1YcZphTOWm2FjV8Gx5Bfn9zmr41Z5DZ0c47OpB5-XqU~35k1xkfti5Rhyo208ZXuAAuo7QyXh5CTVoPOC8qvPD-sQqG3vMvjXA5JlDxyY3uTzhOSuGyGAlybv7eJYIdbbllUlw-3MlQubeJVubUrwftlLFQu2ppU96aiBdW9WVNeX1ZVUVZjWTEwMhW01T5uvk0QnAiZq~Av-Q18gr-jCpgxmYm8m26wXn4xfy9iHVYE6vDfN5m75EVCiDpM82xCsKkXD~RTbdA-RQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=fy-prod"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 355
[download] Destination: storage/sdcard0/Crunchyroll/Kadokawa Pictures Inc./Don't Hurt Me, My Healer! (S0E9) - Este episodio cuenta.mp4
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --http-accept-gzip=true --file-allocation=none -x16 -j16 -s16 --allow-overwrite=true --allow-piece-length-change=true --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-us,en;q=0.5' --header 'Sec-Fetch-Mode: navigate' --header 'Cookie: session_id=aa7aa7fd58829783721485aae859e241; __cf_bm=0ZhPW9wsmth1vnHnfeIKCzvzdw4tJDVVFAAMMEIYHQc-1654453848-0-AbwGlQuhCor8zz90gXsKTimnct8DZ1dZYwRpHdCuXpBNC3RO7uQaWhprv386hsPmgMLfHUdkbhS+avZD3sBEQefsWetJo7wtA1iEihLk6VSz; etp_rt=1e116b8e-295a-43a7-869c-ba538fea3784; __cfruid=f99664663a603df4490c9a46e8426d18c27087a4-1654453847; c_visitor=7a4dca66-f9d7-4643-9a2d-32e6074407e0' --check-certificate=true --remote-time=true --show-console-readout=true -j8 --dir './storage/sdcard0/Crunchyroll/Kadokawa Pictures Inc./' --auto-file-renaming=false --file-allocation=none --uri-selector=inorder -i 'storage/sdcard0/Crunchyroll/Kadokawa Pictures Inc./Don'"'"'t Hurt Me, My Healer! (S0E9) - Este episodio cuenta.mp4.part.frag.urls'
```

**Comment by fstirlitz** [comment]
> `%(height)sp*%(fps)sfps`

SD cards are usually (ex)FAT-formatted, and `*` is a forbidden character on FAT file systems.

**Comment by CZeil** [comment]
Excellent, thanks for the clarification. It is indeed as you say I removed the character from my output template and if you can download the video.
Thanks  @fstirlitz
