### ISSUE TITLE
Youtube extractor fails on playlists

### ISSUE THREAD

**Issue by mauricioquintela** [yt-dlp/yt-dlp#3997]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm running yt-dlp (git version, updated through aur) on manjaro linux. 

After updating today (06/06 - 5 commits), i noticed that playlists never loaded on mpv. Testing with yt-dlp by itself provides the same error. Regular youtube downloads work fine. Tried with several playlists, all error out in the same way. Current version on my machine is
```
 ~> paru -Q yt-dlp-git
yt-dlp-git 2022.05.18.r62.gdec30912a-1
```

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/playlist?list=PLtWyX5YeBQtN6I_CWi3AYUq-y0NWgk9xg']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.12-1-MANJARO-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLtWyX5YeBQtN6I_CWi3AYUq-y0NWgk9xg
[youtube:tab] PLtWyX5YeBQtN6I_CWi3AYUq-y0NWgk9xg: Downloading webpage
ERROR: YoutubeBaseInfoExtractor.extract_yt_initial_data() got an unexpected keyword argument 'fatal'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1490, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 3860, in wrapper
    info_dict = func(self, url, smuggled_data)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 5338, in _real_extract
    data, ytcfg = self._extract_data(url, item_id)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 4511, in _extract_data
    webpage, data = self._extract_webpage(url, item_id, fatal=webpage_fatal)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 4464, in _extract_webpage
    data = self.extract_yt_initial_data(item_id, webpage or '', fatal=fatal) or {}
TypeError: YoutubeBaseInfoExtractor.extract_yt_initial_data() got an unexpected keyword argument 'fatal'
```

**Comment by mauricioquintela** [comment]
Issue is fixed. Thanks for being so fast! Have a good one
