### ISSUE TITLE
[NSFW] erocast.me

### ISSUE THREAD

**Issue by lightninghydra24** [yt-dlp/yt-dlp#4001]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

https://erocast.me/track/3212/conversational-audio-6-6-22

### Description

Hi there, I found eroshare.me for audio tracks but it seems yt-dlp doesn't support this site at this time. I'd love if support could be added :) Thanks all!

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://erocast.me/track/3212/conversational-audio-6-6-22']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - macOS-12.4-arm64-arm-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://erocast.me/track/3212/conversational-audio-6-6-22
[generic] conversational-audio-6-6-22: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] conversational-audio-6-6-22: Downloading webpage
[generic] conversational-audio-6-6-22: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://erocast.me/track/3212/conversational-audio-6-6-22
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://erocast.me/track/3212/conversational-audio-6-6-22
```

**Comment by eladkarako** [comment]
`https://erocast.me/track/3212/conversational-audio-6-6-22`  
» `https://erocast.me/stream/hls/3212`  
» `track.m3u8`
» `ffmpeg -i "file:track.m3u8" -codec copy "file:track.mkv"`.

CloudFlare protects it with XSRF-TOKEN or "not a robot". it whitelists the IP half and hour or so.
(how to work around cloudflare..?)

**Comment by Bricio** [comment]
> `https://erocast.me/track/3212/conversational-audio-6-6-22` » `https://erocast.me/stream/hls/3212` » `track.m3u8` » `ffmpeg -i "file:track.m3u8" -codec copy "file:track.mkv"`.
> 
> CloudFlare protects it with XSRF-TOKEN or "not a robot". it whitelists the IP half and hour or so. (how to work around cloudflare..?)

Did you try cookies?

```
$ ./yt-dlp.exe -v --cookies cookies.firefox-private.txt "https://erocast.me/stream/hls/3212"
[debug] Command-line config: ['-v', '--cookies', 'cookies.firefox-private.txt', 'https://erocast.me/stream/hls/3212']
[debug] Portable config "D:\ytdlp\yt-dlp.conf": ['--ffmpeg-location', '.\\ffmpeg\\bin', '--ignore-config']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ".\ffmpeg\bin\ffprobe" -bsfs
[debug] Checking exe version: ".\ffmpeg\bin\ffmpeg" -bsfs
[debug] exe versions: ffmpeg N-105453-gcc5eb2e662-20220204 (setts), ffprobe N-105453-gcc5eb2e662-20220204
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://erocast.me/stream/hls/3212
[generic] 3212: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 3212: Downloading webpage
[debug] Identified a M3U playlist
[generic] 3212: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3212: Downloading 1 format(s): 0
[debug] Invoking hlsnative downloader on "https://erocast.me/stream/hls/3212"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 71
[download] Destination: 3212 [3212].mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[download]   1.9% of ~24.00MiB at 216.71KiB/s ETA 01:32 (frag 1/71)
ERROR: Interrupted by user

```

**Comment by eladkarako** [comment]
btw. those `ts` are mp3.  
and yt-dlp breaks down because of this.
not related to here. will open a new clean bug.

it seems the cause is an invalid ffprobe call (or parse from the json).

```txt
.............
.................
......................
.........................
download] 100% of 18.25MiB in 02:51                               
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:3212 [3212].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "3212 [3212].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:3212 [3212].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:3212 [3212].temp.mp4"
[debug] ffmpeg version N-106943-g41a558fea0-2022-05-19-nonfree Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20220324
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=i686-w64-mingw32- --arch=i686 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-doc --enable-nonfree --extra-version=2022-05-19-nonfree --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --disable-libdavs2 --enable-decklink --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --disable-libbluray --enable-libfdk-aac --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --disable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --disable-libsvtav1 --enable-libtwolame --disable-libuavs3d --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 28.100 / 59. 28.100
  libavformat    59. 24.100 / 59. 24.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 38.100 /  8. 38.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Input #0, mpegts, from 'file:3212 [3212].mp4':
  Duration: 00:18:59.86, start: 1.400000, bitrate: 134 kb/s
  Program 1 
    Metadata:
      service_name    : Conversational Audio 6/6/22
      service_provider: FFmpeg
  Stream #0:0[0x100]: Audio: mp3 ([3][0][0][0] / 0x0003), 48000 Hz, mono, fltp, 128 kb/s
[aac_adtstoasc @ 01528500] Codec 'mp3' (86017) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018) 
Error initializing bitstream filter: aac_adtstoasc
Error initializing output stream 0:0 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
ERROR: Postprocessing:   Stream #0:0 -> #0:0 (copy)
Traceback (most recent call last):
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 3204, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 3374, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 3361, in run_all_pps
    info = self.run_pp(pp, info)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 3340, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\common.py", line 129, in wrapper
    return func(self, info)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 891, in run
    self._fixup('Fixing MPEG-TS in MP4 container', info['filepath'], [
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 853, in _fixup
    self.run_ffmpeg(filename, temp_filename, options)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 328, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 282, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 321, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:0 -> #0:0 (copy)


EXIT_CODE=1

```
