### ISSUE TITLE
[Wistia] Embedded links improvement

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4016]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Anywhere

### Example URLs

Test link1:
https://www.spotlightapp.io/events/get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r

Embedded video URL:
https://fast.wistia.com/embed/medias/lojg2xjxvn.json?callback=wistiajson1
OR
https://fast.wistia.com/embed/medias/lojg2xjxvn.m3u8?quality_min=360&quality_max=2160

Test link 2:
https://lpm.gevestor-verlag.de/1/669/Tesla-Tempo/?campaignId=51623&banner=Z1_A159063_M388793549367_T65_G2_HV&sys=230&utm_source=297803009715&utm_medium=email&opt_mandator=295944300433&tags=_DO-cat1_gier-cat2_nachhaltig_&opt_domain=newsletter.gevestor.de&SYS=230&SCID=YnJlbmRlbEBjb21wdXNlcnZlLmNvbQ%3D%3D&utm_campaign=388793549367&bmMailId=4YM49V85-4YLXN2NR-C1LHSQ&bmMailId=4YM49V85-4YLXN2NR-C1LHSQ&scid=YnJlbmRlbEBjb21wdXNlcnZlLmNvbQ%3D%3D

Embedded video URL:
https://fast.wistia.com/embed/medias/to03pgfcvv.json?callback=wistiajson1
OR
https://fast.wistia.com/embed/medias/to03pgfcvv.m3u8?quality_min=360&quality_max=2160

### Description

Is there a way to maybe improve Wistia extractor to detect a wider scope of embedded links? 
Or maybe generic extractor could do this. If possible, that'd be a great improvement.  

### Verbose log

```shell
./yt-dlp -v -F "https://www.spotlightapp.io/events/get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r"
[debug] Command-line config: ['-v', '-F', 'https://www.spotlightapp.io/events/get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.spotlightapp.io/events/get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r
[generic] get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r: Downloading webpage
[generic] get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.spotlightapp.io/events/get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1490, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/generic.py", line 4037, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.spotlightapp.io/events/get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r
```

**Comment by dirkf** [comment]
URL 1 has Wistia embed URLs inside its hydration JSON. Even if the generic extractor got to see the rehydrated page, the search patterns in `WistiaIE._extract_urls()` wouldn't find them because they have no `/embed/`. Eg:
```
{"id":"28YvHJz8e8jQbKHbgq8fAV",...,"intro_video_url":"https://ankurnagpal.wistia.com/medias/mrzxb2bole","join_url":"https://youtu.be/9j0JWx_iLQg","replay_video_url":"https://ankurnagpal.wistia.com/medias/lojg2xjxvn",...}

This pattern would find these:
```py
`r'''_video_url['"]\s*:\s*['"]https?://(?:fast\.)?wistia\.(?:net|com)/(?:embed/)?(?:iframe|medias)/''' + WistiaBaseIE(InfoExtractor._VALID_ID_REGEX)
```
In URL 2 the embedded video is mentioned in HTML
```HTML
<div id="wistia_to03pgfcvv" class="wistia_embed" ... >
```
and also in JS:
```js
            (new evp.Wistia({
                playerId: '5de2a230-3aec-4ab1-8301-99301bc4b46f',
                videoId: 'to03pgfcvv',
                htmlId: 'wistia_to03pgfcvv',
                ...
            })).embed()
```
In yt-dl, the generic extractor matches the HTML like this `id="wistia_(to03pgfcvv)`:
```shellsession
$ python -m youtube_dl -v -F 'https://lpm.gevestor-verlag.de/1/669/Tesla-Tempo/?campaignId=51623&banner=Z1_A159063_M388793549367_T65_G2_HV&sys=230&utm_source=297803009715&utm_medium=email&opt_mandator=295944300433&tags=_DO-cat1_gier-cat2_nachhaltig_&opt_domain=newsletter.gevestor.de&SYS=230&SCID=YnJlbmRlbEBjb21wdXNlcnZlLmNvbQ%3D%3D&utm_campaign=388793549367&bmMailId=4YM49V85-4YLXN2NR-C1LHSQ&bmMailId=4YM49V85-4YLXN2NR-C1LHSQ&scid=YnJlbmRlbEBjb21wdXNlcnZlLmNvbQ%3D%3D'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://lpm.gevestor-verlag.de/1/669/Tesla-Tempo/?campaignId=51623&banner=Z1_A159063_M388793549367_T65_G2_HV&sys=230&utm_source=297803009715&utm_medium=email&opt_mandator=295944300433&tags=_DO-cat1_gier-cat2_nachhaltig_&opt_domain=newsletter.gevestor.de&SYS=230&SCID=YnJlbmRlbEBjb21wdXNlcnZlLmNvbQ%3D%3D&utm_campaign=388793549367&bmMailId=4YM49V85-4YLXN2NR-C1LHSQ&bmMailId=4YM49V85-4YLXN2NR-C1LHSQ&scid=YnJlbmRlbEBjb21wdXNlcnZlLmNvbQ%3D%3D']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 14a087ec6
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[generic] ?campaignId=51623&banner=Z1_A159063_M388793549367_T65_G2_HV&sys=230&utm_source=297803009715&utm_medium=email&opt_mandator=295944300433&tags=_DO-cat1_gier-cat2_nachhaltig_&opt_domain=newsletter.gevestor: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?campaignId=51623&banner=Z1_A159063_M388793549367_T65_G2_HV&sys=230&utm_source=297803009715&utm_medium=email&opt_mandator=295944300433&tags=_DO-cat1_gier-cat2_nachhaltig_&opt_domain=newsletter.gevestor: Downloading webpage
[generic] ?campaignId=51623&banner=Z1_A159063_M388793549367_T65_G2_HV&sys=230&utm_source=297803009715&utm_medium=email&opt_mandator=295944300433&tags=_DO-cat1_gier-cat2_nachhaltig_&opt_domain=newsletter.gevestor: Extracting information
[download] Downloading playlist: Zeitenwende
[generic] playlist Zeitenwende: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Wistia] to03pgfcvv: Downloading JSON metadata
[info] Available formats for to03pgfcvv:
format code  extension  resolution note
mp4-224p     mp4        400x224     201k , mp4 container, h264, 37.69MiB
iphone-360p  mp4        640x360     278k , mp4 container, h264, 52.18MiB
md_mp4-540p  mp4        960x540     382k , mp4 container, h264, 71.70MiB
hd_mp4-720p  mp4        1280x720    535k , mp4 container, h264, 100.27MiB
original     bin        1280x720   2206k , 413.07MiB (best)
[download] Finished downloading playlist: Zeitenwende
$
```

**Comment by pukkandan** [comment]
spotlightapp.io will need a separate extractor. The other one is a minor bug in yt-dlp. I'll push a fix to it asap

**Comment by HobbyistDev** [comment]
From this [link](https://www.spotlightapp.io/events/get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r), we can a lot source to extract the video

The webpage have a `id=__NEXT_DATA__` that can be extracted with `_search_nextjs_`.
Here's the `__NEXT_DATA__` of the page:
```
{
	"props": {
		"pageProps": {
			"event": {
				"id": "28YvHJz8e8jQbKHbgq8fAV",
				"created_at": "2022-06-03T17:26:41.389000+00:00",
				"updated_at": "2022-06-07T20:55:30.680000+00:00",
				"title": "Get More Sales With Content That Stands Out",
				"url_slug": "get-more-sales-with-content-that-stands-out",
				"start_dt": "2022-06-07T12:00:00-05:00",
				"duration": 60,
				"status": "completed",
				"intro_video_url": "https://ankurnagpal.wistia.com/medias/mrzxb2bole",
				"join_url": "https://youtu.be/9j0JWx_iLQg",
				"replay_video_url": "https://ankurnagpal.wistia.com/medias/lojg2xjxvn",
				"description": "Standing out among the wealth of other products and creators can be a difficult task when you’re beginning to build you brand. And if you don’t have a team of designers at your disposal, it can feel almost insurmountable. If you’ve ever had that feeling, this event is for you! In this event, we’ll be walking through Canva, a free design software that has everything you need to build content for your brand that not only stands out, but appeals to your target audience and is authentic to who you are. We’ll walk through how you can get started using Canva for free and the endless potential hidden within it’s easy to use platform. ",
				"hosts": [{
					"id": "6y7E7QQdHc2mFG61eXibp7",
					"created_at": "2022-03-16T18:06:43.829000+00:00",
					"updated_at": "2022-03-16T18:06:43.829000+00:00",
					"full_name": "Jonah Cohen",
					"first_name": "Jonah",
					"last_name": "Cohen",
					"image": {
						"id": "5PSBuUnhwpzmWY607uYFaU",
						"created_at": "2022-03-16T18:03:07.657000+00:00",
						"updated_at": "2022-06-02T19:35:18.493000+00:00",
						"title": "Jonah Headshot",
						"description": "",
						"file": {
							"url": "//images.ctfassets.net/71cx1gwcghn0/5PSBuUnhwpzmWY607uYFaU/ecbb3ee183e82a1966bf213622601960/Profile_Pic.png",
							"details": {
								"size": 142691,
								"image": {
									"width": 350,
									"height": 350
								}
							},
							"fileName": "Profile Pic.png",
							"contentType": "image/png"
						}
					},
					"bio": {
						"nodeType": "document",
						"data": {},
						"content": [{
							"nodeType": "paragraph",
							"content": [{
								"nodeType": "text",
								"value": "Jonah is the host of Spotlight by Teachable and a content and course creator himself. He's spent the last year working with Teachable creators to help them host live events that provide students value and help drive sales to their courses.",
								"marks": [],
								"data": {}
							}],
							"data": {}
						}, {
							"nodeType": "paragraph",
							"content": [{
								"nodeType": "text",
								"value": "Jonah has been working in the content production industry for over a decade. He has toured with such talents as Mary Lambert and Benjamin Francis Leftwitch and worked with a wealth of creators such as Tori Dunlap (Her First $100k), Damon Dominique, and Teri Ijeoma. Starting as a studio and live sound engineer, he honed his skills in content production including working on episodes of Good Morning America, VH1 Big Morning Buzz, and Spotlight by Teachable. ",
								"marks": [],
								"data": {}
							}],
							"data": {}
						}, {
							"nodeType": "paragraph",
							"content": [{
								"nodeType": "text",
								"value": "His unique skill set has provided him with the tools to help creatives realize their visions and bring them to fruition. He thrives on the output of creative media and nothing brings him more joy than helping an idea reach its full potential. ",
								"marks": [],
								"data": {}
							}],
							"data": {}
						}]
					}
				}],
				"promoted_courses": [{
					"id": "qyS8yw1pXfRJjhEsDPhav",
					"created_at": "2022-04-23T16:49:02.284000+00:00",
					"updated_at": "2022-04-24T14:02:59.502000+00:00",
					"title": "Establish Your Internet Home Base on Teachable (5 Day Challenge)",
					"url_slug": "establish-your-internet-home-base-on-teachable-5-day-challenge",
					"video_url": "https://ankurnagpal.wistia.com/medias/9tns3xg8im",
					"summary": "Showcase your business and start collecting leads in 5 days!",
					"deliverables": ["Day by day actionable steps to build your homepage", "Videos for every lesson giving easy to follow instructions", "Built for the busy creator with only 10-15min of work a day", "A wealth of additional resources for building and selling online coaching and course products"],
					"description": {
						"data": {},
						"content": [{
							"data": {},
							"content": [{
								"data": {},
								"marks": [],
								"value": "We built this free mini course specifically for the busy creator.",
								"nodeType": "text"
							}],
							"nodeType": "paragraph"
						}, {
							"data": {},
							"content": [{
								"data": {},
								"marks": [],
								"value": "Each day should take no more than 15 minutes of your time and includes actionable and easy steps to get your internet home base up and running.",
								"nodeType": "text"
							}],
							"nodeType": "paragraph"
						}, {
							"data": {},
							"content": [{
								"data": {},
								"marks": [],
								"value": "Creating a website, building a lead capture form, and establishing an internet home base to start growing your audience and selling products is easy with Teachable!",
								"nodeType": "text"
							}],
							"nodeType": "paragraph"
						}, {
							"data": {},
							"content": [{
								"data": {},
								"marks": [],
								"value": "The course is 100% free, you can go at your own pace (although c'mon... 5 days... you can do it!), and help is available along the way should you need it!",
								"nodeType": "text"
							}],
							"nodeType": "paragraph"
						}],
						"nodeType": "document"
					},
					"fedora_id": "1737791",
					"creators": [{
						"id": "6y7E7QQdHc2mFG61eXibp7",
						"created_at": "2022-03-16T18:06:43.829000+00:00",
						"updated_at": "2022-03-16T18:06:43.829000+00:00",
						"full_name": "Jonah Cohen",
						"first_name": "Jonah",
						"last_name": "Cohen",
						"image": {
							"id": "5PSBuUnhwpzmWY607uYFaU",
							"created_at": "2022-03-16T18:03:07.657000+00:00",
							"updated_at": "2022-06-02T19:35:18.493000+00:00",
							"title": "Jonah Headshot",
							"description": "",
							"file": {
								"url": "//images.ctfassets.net/71cx1gwcghn0/5PSBuUnhwpzmWY607uYFaU/ecbb3ee183e82a1966bf213622601960/Profile_Pic.png",
								"details": {
									"size": 142691,
									"image": {
										"width": 350,
										"height": 350
									}
								},
								"fileName": "Profile Pic.png",
								"contentType": "image/png"
							}
						},
						"bio": {
							"nodeType": "document",
							"data": {},
							"content": [{
								"nodeType": "paragraph",
								"content": [{
									"nodeType": "text",
									"value": "Jonah is the host of Spotlight by Teachable and a content and course creator himself. He's spent the last year working with Teachable creators to help them host live events that provide students value and help drive sales to their courses.",
									"marks": [],
									"data": {}
								}],
								"data": {}
							}, {
								"nodeType": "paragraph",
								"content": [{
									"nodeType": "text",
									"value": "Jonah has been working in the content production industry for over a decade. He has toured with such talents as Mary Lambert and Benjamin Francis Leftwitch and worked with a wealth of creators such as Tori Dunlap (Her First $100k), Damon Dominique, and Teri Ijeoma. Starting as a studio and live sound engineer, he honed his skills in content production including working on episodes of Good Morning America, VH1 Big Morning Buzz, and Spotlight by Teachable. ",
									"marks": [],
									"data": {}
								}],
								"data": {}
							}, {
								"nodeType": "paragraph",
								"content": [{
									"nodeType": "text",
									"value": "His unique skill set has provided him with the tools to help creatives realize their visions and bring them to fruition. He thrives on the output of creative media and nothing brings him more joy than helping an idea reach its full potential. ",
									"marks": [],
									"data": {}
								}],
								"data": {}
							}]
						}
					}],
					"pricing": {
						"options": [{
							"id": "3958674",
							"price": 0,
							"school_id": "1264689",
							"slug": "establish-your-internet-home-base-on-teachable-7-day-challenge",
							"type": "free"
						}]
					},
					"thumbnail_image": {
						"id": "1rWkNwlrdlpUbOY6Sk7Inc",
						"created_at": "2022-04-22T20:28:07.043000+00:00",
						"updated_at": "2022-04-22T20:28:07.043000+00:00",
						"title": "Establish Your Internet Home Base on Teachable (5 Day Challenge) Thumbnail",
						"description": "",
						"file": {
							"url": "//images.ctfassets.net/71cx1gwcghn0/1rWkNwlrdlpUbOY6Sk7Inc/a9f59047f485a568ab501166ff0bdcbb/Spotlight_Mini_Course_Thumbnail.png",
							"details": {
								"size": 130329,
								"image": {
									"width": 1280,
									"height": 669
								}
							},
							"fileName": "Spotlight Mini Course Thumbnail.png",
							"contentType": "image/png"
						}
					}
				}],
				"resources": [{
					"id": "3iIxWSBDG8O1ELTcHeFDp3",
					"created_at": "2022-03-25T14:20:11.303000+00:00",
					"updated_at": "2022-03-29T17:15:54.196000+00:00",
					"name": "How to Sell an Online Course PDF",
					"url": "https://downloads.ctfassets.net/71cx1gwcghn0/1McqzKERLKhIx8oebRLzGE/8811073d531c6abe58382e2942223e08/How_To_Sell_An_Online_Course_-_Spotlight_Creator_Tips.pdf"
				}],
				"thumbnail_image": {
					"id": "4M95Cpzp6LyswmgF0Jkbpd",
					"created_at": "2022-06-02T19:44:17.222000+00:00",
					"updated_at": "2022-06-02T19:44:17.222000+00:00",
					"title": "Get More Sales With Content That Stands Out Thumbnail",
					"description": "",
					"file": {
						"url": "//images.ctfassets.net/71cx1gwcghn0/4M95Cpzp6LyswmgF0Jkbpd/a995b674760ccd97101680bda4d043b4/8e622651a6dcd7943cebcd23a4be86ea6ee4abc2.png",
						"details": {
							"size": 503117,
							"image": {
								"width": 1920,
								"height": 1080
							}
						},
						"fileName": "8e622651a6dcd7943cebcd23a4be86ea6ee4abc2.png",
						"contentType": "image/png"
					}
				}
			}
		},
		"__N_SSP": true
	},
	"page": "/events/[urlSlug]",
	"query": {
		"utm_content": "get-more-sales-with-content-that-stands-out",
		"urlSlug": "get-more-sales-with-content-that-stands-out",
		"utm_campaign": "Spotlight-Events",
		"utm_medium": "Drip-news-9",
		"utm_source": "Email-3-REG-2",
		"__s": "g9t1u8g9g2lpv3413e8r"
	},
	"buildId": "wmbtqLUswbSgELlZ4a278",
	"isFallback": false,
	"gssp": true,
	"scriptLoader": []
}
```
It seems the webpage specify link for wistia(https://ankurnagpal.wistia.com/medias/lojg2xjxvn)  and youtube link (https://youtu.be/9j0JWx_iLQg)

The webpage has four `json/ld`. We can extract video from this too.
Here one of three `json/ld` that i get:
```
{
	"@context": "http://schema.org/",
	"@id": "https://fast.wistia.net/embed/iframe/lojg2xjxvn",
	"@type": "VideoObject",
	"duration": "PT1H4M11S",
	"name": "Get More Sales With Content That Stands Out",
	"thumbnailUrl": "https://embed-ssl.wistia.com/deliveries/ccfbc31376b1f268bc12808102dde11c.jpg?image_crop_resized=1280x720",
	"embedUrl": "https://fast.wistia.net/embed/iframe/lojg2xjxvn",
	"uploadDate": "2022-06-08",
	"description": "a Spotlight video",
	"contentUrl": "https://embed-ssl.wistia.com/deliveries/b8197735009fcf1b4ebd37ec3b33497bbb7c58f2.m3u8",
	"potentialAction": {
		"@type": "SeekToAction",
		"target": "https://www.spotlightapp.io/events/get-more-sales-with-content-that-stands-out?utm_source=Email-3-REG-2&utm_medium=Drip-news-9&utm_campaign=Spotlight-Events&utm_content=get-more-sales-with-content-that-stands-out&__s=g9t1u8g9g2lpv3413e8r?wtime={seek_to_second_number}",
		"startOffset-input": "required name=seek_to_second_number"
	}
}
```
As we can see, we can extract video from `contentUrl` or `embedUrl` from here

**Comment by dirkf** [comment]
>The webpage have a id=__NEXT_DATA__ ...

That is, the "hydration JSON" that I mentioned above.

**Comment by pukkandan** [comment]
> As we can see, we can extract video from contentUrl or embedUrl from here

Note that our `_search_json_ld` does not support `embedURL`. If you want to extract that field, you have to do this: https://github.com/yt-dlp/yt-dlp/blob/0c36dc00d7b9f43238bacb0e03730f31117d0b38/yt_dlp/extractor/npr.py#L120-L121

**Comment by dirkf** [comment]
Shouldn't we be pulling the `embedURL` too, either in a `formats` list or as a fallback when there's no `contentUrl`?

IIRC @kikuyan had a PR open on yt-dl for this before disappearing (which hasn't yet been reached in my ongoing trawl of open PRs).

**Comment by pukkandan** [comment]
I reverted it since it was causing false positives in the generic extractor #4141. Idk if ytdl will have same issue, since yt-dlp's json/ld extraction in Generic is more ambitious

Since only one extractor uses that field atm, it was easier to just manually `traverse_obj` than trying to fix the issue in Generic

**Comment by dirkf** [comment]
(Sorry for slight OT) So the problem page in #4141 had `embedURL` in a `ld+json` block, with an unsupported URL format, which was extracted in preference to the desired `twitter:player` format (or at least before it, if yt-dlp's generic is pulling all known URLs now)?

But wasn't that actually a problem with the Mediaset extractor which didn't like a URL format with a player version `.../player/v2/index.html` (ie, the URL pattern needed to have `.../player(?:/v\d+)?/...`?

**Comment by HobbyistDev** [comment]
> > As we can see, we can extract video from contentUrl or embedUrl from here
> 
> Note that our `_search_json_ld` does not support `embedURL`. If you want to extract that field, you have to do this:
> 
> https://github.com/yt-dlp/yt-dlp/blob/0c36dc00d7b9f43238bacb0e03730f31117d0b38/yt_dlp/extractor/npr.py#L120-L121

`_yield_json_ld` and `_search_json_ld` didn't work for me. I think the regex is different in webpage with `JSON_LD_RE`. I need only the first one in `json_ld` because the other `json+ld` didn't contain any video link

Here's the `script` tag that contain `ld+json` (the first `json+ld` that i mentioned):
`<script class="w-json-ld" type="application/ld+json" id="w-json-ldwistia_40">...</script>`

**Comment by pukkandan** [comment]
Looking at the page source, I don't see any json+ld. Are you sure you weren't looking at the webpage after hydration?

**Comment by HobbyistDev** [comment]
Yeah, i think it's appeared after hydration

**Comment by doe1080** [comment]
The domain name `spotlightapp.io` is for [sale!](https://forsale.godaddy.com/forsale/spotlightapp.io)
