### ISSUE TITLE
yt-dlp breaks when it tries fix hls result with ffmpeg and aac_adtstoasc, even if the stream is mp3 (ffmpeg exit code 1)

### ISSUE THREAD

**Issue by eladkarako** [yt-dlp/yt-dlp#4021]
### Description

1. yt-dlp mux `.ts` into mp4.
2. something is wrong with the check of the audio <strong>codec</strong>, it uses ffmpeg with bitstream filter to fix `aac` stream, regardless (current codec is `mp3`, container `mp4` but the container does not matter here..)

```txt
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:hls_playlist [hls_playlist].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "hls_playlist [hls_playlist].mp4"
```

3. `mp3` audio will cause ffmpeg to return exit code different than `0` (failure).

```txt
[aac_adtstoasc @ 01143dc0] Codec 'mp3' (86017) 
is not supported by the bitstream filter 'aac_adtstoasc'. 
Supported codecs are: aac (86018) 
```

4. yt-dlp breaks with an error.
(next actions such as muxing into mkv, thumbnail embedding, etc.. would fail.)

note:
if you run it again, 
yt-dlp would see a mp4 already ready in the folder,  
and will continue the next steps.. 
(skipping the fix, this is also not optimal..)  

solution: fix `ffprobe` to provide proper audio fixing,  
it will fix the bug (not break when audio is mp3), 
and it is also a nice opportunity to checkout other bitstream filters
https://www.ffmpeg.org/ffmpeg-bitstream-filters.html#mp3decomp (..and h265 and AV1).  

<hr/>

the following zip contains  

<img width="543" alt="2022-06-08_185727" src="https://user-images.githubusercontent.com/415238/172663035-521eff5b-b81f-44a9-b3a7-8ea83c8b4466.png">

<a download="testing_ytdlp_with_hls_ts_mp3.zip" href="https://github.com/yt-dlp/yt-dlp/files/8863247/testing_ytdlp_with_hls_ts_mp3.zip">testing_ytdlp_with_hls_ts_mp3.zip</a> (2.7MB)

it was a result of this ffmpeg command:

```cmd
ffmpeg -i "file:input.mp3" -c:a copy -f segment -segment_format mpegts -segment_time 70 -segment_list hls_playlist.m3u8 "audio_segment%05d.ts"
```

if ran from windows batch file you need to add another `%` to escape the existing `%`.

audio is public domain (Beethoven - Fur Elise)
<a download="input.mp3.zip" href="https://github.com/yt-dlp/yt-dlp/files/8863275/input.mp3.zip">input.mp3.zip</a> (2.6MB)

I've noticed this issue while debugging https://github.com/yt-dlp/yt-dlp/issues/4001#issuecomment-1150038615

<hr/>

you'll need to put the `.ts` files and `.m3u8` in a server for testing,  
you can use https://sourceforge.net/projects/miniserver/files/Uniform%20Server%20ZeroXIV/14_0_5_ZeroXIV/ , or wamp, or tmp. github pages..

<details><summary>Verbose log</summary>

```shell
D:\dos\yt-dlp_kit>call "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\python.exe" "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\Lib\site-packages\yt_dlp" "http://www.localhost.com/testing_ytdlp_with_hls_ts_mp3/hls_playlist.m3u8" --ignore-config --config-location "D:\DOS\YT-DLP~1\yt-dlp_conf_base.conf" --merge-output-format mkv --remux-video mkv 
[debug] Command-line config: ['http://www.localhost.com/testing_ytdlp_with_hls_ts_mp3/hls_playlist.m3u8', '--ignore-config', '--config-location', 'D:\\DOS\\YT-DLP~1\\yt-dlp_conf_base.conf', '--merge-output-format', 'mkv', '--remux-video', 'mkv']
[debug] | Config "D:\DOS\YT-DLP~1\yt-dlp_conf_base.conf": ['--force-ipv4', '--windows-filenames', '--sleep-requests', '1', '--sleep-interval', '1', '--sleep-subtitles', '2', '--max-sleep-interval', '3', '--console-title', '--no-check-certificates', '--prefer-insecure', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4599.0 Safari/537.36', '--concurrent-fragments', '3', '--skip-unavailable-fragments', '--embed-subs', '--write-subs', '--write-auto-subs', '--sub-langs', 'en,iw,iw-en,ja,ko', '--embed-metadata', '--embed-chapters', '--embed-thumbnail', '--convert-thumbnails', 'jpg', '--sponsorblock-mark', 'intro,outro,poi_highlight', '--sponsorblock-remove', 'sponsor,selfpromo,interaction,filler,music_offtopic', '--sponsorblock-api', 'https://sponsor.ajay.app', '--no-abort-on-error', '--skip-unavailable-fragments', '--verbose', '--print-traffic']
[debug] Encodings: locale cp1255, fs utf-8, pref cp1255, out cp1255 (No ANSI), error cp1255 (No ANSI), screen cp1255 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.2 (CPython 32bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-106943-g41a558fea0-2022-05-19-nonfree (fdk,setts), ffprobe N-106943-g41a558fea0-2022-05-19-nonfree, phantomjs 2.5.0, rtmpdump 2.3
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] [generic] Extracting URL: http://www.localhost.com/testing_ytdlp_with_hls_ts_mp3/hls_playlist.m3u8
[generic] hls_playlist: Requesting header
[debug] Identified a direct video link
[generic] Sleeping 1.0 seconds ...
send: b'HEAD /testing_ytdlp_with_hls_ts_mp3/hls_playlist.m3u8 HTTP/1.1\r\nHost: www.localhost.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4599.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 08 Jun 2022 15:40:41 GMT
header: Server: Apache
header: Last-Modified: Wed, 08 Jun 2022 15:39:33 GMT
header: ETag: "eb-5e0f18303013a-gzip"
header: Accept-Ranges: bytes
header: Vary: Accept-Encoding,User-Agent
header: Content-Encoding: gzip
header: Content-Length: 156
header: Connection: close
header: Content-Type: application/vnd.apple.mpegurl
[generic] hls_playlist: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[SponsorBlock] SponsorBlock is not supported for Generic
send: b'GET /testing_ytdlp_with_hls_ts_mp3/hls_playlist.m3u8 HTTP/1.1\r\nHost: www.localhost.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4599.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 08 Jun 2022 15:40:42 GMT
header: Server: Apache
header: Last-Modified: Wed, 08 Jun 2022 15:39:33 GMT
header: ETag: "eb-5e0f18303013a-gzip"
header: Accept-Ranges: bytes
header: Vary: Accept-Encoding,User-Agent
header: Content-Encoding: gzip
header: Content-Length: 156
header: Connection: close
header: Content-Type: application/vnd.apple.mpegurl
[debug] Default format spec: bestvideo*+bestaudio/best
[info] hls_playlist: Downloading 1 format(s): 0
[ThumbnailsConvertor] There aren't any thumbnails to convert
[debug] Invoking hlsnative downloader on "http://www.localhost.com/testing_ytdlp_with_hls_ts_mp3/hls_playlist.m3u8"
[download] Sleeping 2.66 seconds ...
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
send: b'GET /testing_ytdlp_with_hls_ts_mp3/hls_playlist.m3u8 HTTP/1.1\r\nHost: www.localhost.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4599.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 08 Jun 2022 15:40:45 GMT
header: Server: Apache
header: Last-Modified: Wed, 08 Jun 2022 15:39:33 GMT
header: ETag: "eb-5e0f18303013a-gzip"
header: Accept-Ranges: bytes
header: Vary: Accept-Encoding,User-Agent
header: Content-Encoding: gzip
header: Content-Length: 156
header: Connection: close
header: Content-Type: application/vnd.apple.mpegurl
[download] Destination: hls_playlist [hls_playlist].mp4
[debug] File locking is not supported on this platform. Proceeding without locking
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome

[download]   0.0% of ~2.07MiB at 48.69KiB/s ETA 00:43send: b'GET /testing_ytdlp_with_hls_ts_mp3/audio_segment00000.ts HTTP/1.1\r\nHost: www.localhost.com\r\nAccept-Encoding: identity\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4599.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nConnection: close\r\n\r\n'
send: b'GET /testing_ytdlp_with_hls_ts_mp3/audio_segment00002.ts HTTP/1.1\r\nHost: www.localhost.com\r\nAccept-Encoding: identity\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4599.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 08 Jun 2022 15:40:45 GMT
header: Server: Apache
header: Last-Modified: Wed, 08 Jun 2022 15:39:33 GMT
header: ETag: "b0400-5e0f18303013a"
header: Accept-Ranges: bytes
header: Content-Length: 721920
header: Vary: Accept-Encoding,User-Agent
header: Connection: close
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 08 Jun 2022 15:40:45 GMT
header: Server: Apache
header: Last-Modified: Wed, 08 Jun 2022 15:39:33 GMT
header: ETag: "14b920-5e0f18302ac9a"
header: Accept-Ranges: bytes
header: Content-Length: 1358112
header: Vary: Accept-Encoding,User-Agent
header: Connection: close

[download]   0.0% of ~3.89MiB at 48.69KiB/s ETA 01:21send: b'GET /testing_ytdlp_with_hls_ts_mp3/audio_segment00001.ts HTTP/1.1\r\nHost: www.localhost.com\r\nAccept-Encoding: identity\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4599.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 08 Jun 2022 15:40:45 GMT
header: Server: Apache
header: Last-Modified: Wed, 08 Jun 2022 15:39:33 GMT
header: ETag: "14b920-5e0f18302ae8b"
header: Accept-Ranges: bytes
header: Content-Length: 1358112
header: Vary: Accept-Encoding,User-Agent
header: Connection: close

[download]   0.1% of ~2.07MiB at 96.31KiB/s ETA 00:21
[download]   0.0% of ~3.89MiB at 27.29KiB/s ETA 02:25
[download]   0.1% of ~3.89MiB at 64.28KiB/s ETA 01:01
[download]   0.3% of ~2.07MiB at 118.87KiB/s ETA 00:17
[download]   0.1% of ~3.89MiB at 42.07KiB/s ETA 01:34 
[download]   0.2% of ~3.89MiB at 85.92KiB/s ETA 00:46
[download]   0.7% of ~2.07MiB at 160.58KiB/s ETA 00:13
[download]   0.2% of ~3.89MiB at 67.02KiB/s ETA 00:59 
[download]   0.4% of ~3.89MiB at 129.99KiB/s ETA 00:30
[download]   1.5% of ~2.07MiB at 245.80KiB/s ETA 00:08
[download]   0.4% of ~3.89MiB at 109.79KiB/s ETA 00:36
[download]   0.8% of ~3.89MiB at 210.08KiB/s ETA 00:18
[download]   3.0% of ~2.07MiB at 396.71KiB/s ETA 00:05
[download]   0.8% of ~3.89MiB at 182.68KiB/s ETA 00:21
[download]   1.6% of ~3.89MiB at 349.68KiB/s ETA 00:11
[download]   6.0% of ~2.07MiB at 661.48KiB/s ETA 00:03
[download]   1.6% of ~3.89MiB at 310.81KiB/s ETA 00:12
[download]   3.2% of ~3.89MiB at 593.30KiB/s ETA 00:06
[download]  12.1% of ~2.07MiB at  1.11MiB/s ETA 00:01 
[download]   3.2% of ~3.89MiB at 538.86KiB/s ETA 00:07
[download]   6.4% of ~3.89MiB at  1.01MiB/s ETA 00:03 
[download]  24.2% of ~2.07MiB at  1.94MiB/s ETA 00:00
[download]   6.4% of ~3.89MiB at 953.85KiB/s ETA 00:03
[download]  12.8% of ~3.89MiB at  1.80MiB/s ETA 00:01 
[download]  33.3% of ~2.07MiB at  2.39MiB/s ETA 00:00
[download]  12.8% of ~3.89MiB at  1.68MiB/s ETA 00:02
[download]  25.7% of ~3.89MiB at  3.26MiB/s ETA 00:00
[download]  33.3% of ~2.07MiB at  2.16MiB/s ETA 00:00 (frag 1/3)
[download]  56.7% of ~2.98MiB at 124.57MiB/s ETA 00:00 (frag 1/3)
[download]  66.7% of ~2.98MiB at 73.29MiB/s ETA 00:00 (frag 1/3) 
[download]  66.7% of ~2.98MiB at 33.91MiB/s ETA 00:00 (frag 1/3)
[download]  66.7% of ~2.98MiB at 27.28MiB/s ETA 00:00 (frag 2/3)
[download] 100% of ~3.28MiB at 125.06MiB/s ETA 00:00 (frag 3/3) 
[download] 100% of 3.28MiB in 00:00                            
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:hls_playlist [hls_playlist].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "hls_playlist [hls_playlist].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:hls_playlist [hls_playlist].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:hls_playlist [hls_playlist].temp.mp4"
[debug] ffmpeg version N-106943-g41a558fea0-2022-05-19-nonfree Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20220324
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=i686-w64-mingw32- --arch=i686 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-doc --enable-nonfree --extra-version=2022-05-19-nonfree --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --disable-libdavs2 --enable-decklink --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --disable-libbluray --enable-libfdk-aac --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --disable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --disable-libsvtav1 --enable-libtwolame --disable-libuavs3d --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 28.100 / 59. 28.100
  libavformat    59. 24.100 / 59. 24.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 38.100 /  8. 38.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Input #0, mpegts, from 'file:hls_playlist [hls_playlist].mp4':
  Duration: 00:02:57.17, start: 1.400000, bitrate: 155 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Audio: mp3 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 128 kb/s
[aac_adtstoasc @ 01143dc0] Codec 'mp3' (86017) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018) 
Error initializing bitstream filter: aac_adtstoasc
Error initializing output stream 0:0 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
ERROR: Postprocessing:   Stream #0:0 -> #0:0 (copy)
Traceback (most recent call last):
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 3204, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 3374, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 3361, in run_all_pps
    info = self.run_pp(pp, info)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 3340, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\common.py", line 129, in wrapper
    return func(self, info)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 891, in run
    self._fixup('Fixing MPEG-TS in MP4 container', info['filepath'], [
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 853, in _fixup
    self.run_ffmpeg(filename, temp_filename, options)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 328, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 282, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "D:\DOS\YT-DLP~1\resources\WPy32\python-3.10.2\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 321, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:0 -> #0:0 (copy)


D:\dos\yt-dlp_kit>set "EXIT_CODE=1"
```

</details>

<details><summary>Checklist</summary>

note: I'm moving the checklist to the bottom,  
so you can enjoy github mouse hover over issue for a quick preview.
when the checklist is on top,  
it just preview this unhelpful junk!

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

</details>

**Comment by pukkandan** [comment]
I don't think there is any need to address this issue. When writing the extractor, just set the `ext` correctly to `mp3`

**Comment by eladkarako** [comment]
the extractor uses mp4 by default, which is part of the problem. the user does not need to know the extension or container, it can be derived from ffprobe.

the second part of the problem is that changing the container is done as an additional step at the end, even if such argument has provided (mkv, for example). I guess this is by design.

**Comment by Lesmiscore** [comment]
The MPEG-TS container has MP3 as its audio stream. In this case, it should internally be `ext=ts` & `acodec=mp3` to avoid the fixup. Since it's not so-called MP3 file. (also MPEG-TS and MP4 are actually different thing)
