### ISSUE TITLE
NHK recent On Demand episodes - ERROR: list index out of range

### ISSUE THREAD

**Issue by MikeSamy** [yt-dlp/yt-dlp#4066]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

It appears a change in NHK VODs from this week results in a `list index out of range` error. Trying with episodes from more than a week ago still work fine. Attached is the log for shows from the last few days.

### Verbose log

```shell
me@localmachine ~ % yt-dlp -vU https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2066047/ 
[debug] Command-line config: ['-vU', 'https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2066047/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [NhkVod] Extracting URL: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2066047/
[NhkVod] 2066-047: Downloading JSON metadata
ERROR: list index out of range
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
	return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
	ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 642, in extract
	ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.9/site-packages/yt_dlp/extractor/nhk.py", line 135, in _real_extract
	return self._extract_episode_info(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.9/site-packages/yt_dlp/extractor/nhk.py", line 35, in _extract_episode_info
	episode = self._call_api(
IndexError: list index out of range
```

**Comment by dirkf** [comment]
NHK is using a new API URL:
```diff
--- old/yt-dlp/yt_dlp/extractor/nhk.py
+++ new/yt-dlp/yt_dlp/extractor/nhk.py
@@ -11,7 +11,7 @@
 
 
 class NhkBaseIE(InfoExtractor):
-    _API_URL_TEMPLATE = 'https://api.nhk.or.jp/nhkworld/%sod%slist/v7a/%s/%s/%s/all%s.json'
+    _API_URL_TEMPLATE = 'https://nwapi.nhk.jp/nhkworld/%sod%slist/v7b/%s/%s/%s/all%s.json'
     _BASE_URL_REGEX = r'https?://www3\.nhk\.or\.jp/nhkworld/(?P<lang>[a-z]{2})/ondemand'
     _TYPE_REGEX = r'/(?P<type>video|audio)/'
```
yt-dl needs the same patch (different line numbers). The authorisation token remains the same.

**Comment by HobbyistDev** [comment]
This work in `2022.06.29`. Here's the log:
```
(python_proj2) ~\yt-dlp>python -m yt_dlp -v "https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2066047/ "
[debug] Command-line config: ['-v', 'https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2066047/ ']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 67db96e5a
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [NhkVod] Extracting URL: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2066047/
[NhkVod] 2066-047: Downloading JSON metadata
[debug] [Piksel] Extracting URL: https://player.piksel.com/v/refid/nhkworld/prefid/nw_vod_v_en_2066_047_20220611111000_01_1654917066
[Piksel] nw_vod_v_en_2066_047_20220611111000_01_1654917066: Downloading webpage
[Piksel] nw_vod_v_en_2066_047_20220611111000_01_1654917066: Downloading JSON metadata
[Piksel] nw_vod_v_en_2066_047_20220611111000_01_1654917066: Downloading JSON metadata
[Piksel] p8c86lg2: Downloading m3u8 information
[Piksel] p8c86lg2: Downloading SMIL file
[debug] Sort order given by extractor: tbr
[debug] Formats sorted by: hasvid, ie_pref, tbr, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] p8c86lg2: Downloading 1 format(s): http-10268
[debug] Invoking http downloader on "https://mz-nhk10.mzpf.webcdn.stream.ne.jp/www60/mz-nhk10/media/mm/flvmedia/5905/m/F/m/mF_mp4file10516841-3979244.mp4?cid=5905&aid=3979244&afid=8396160&assetid=3979244"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: CYCLE AROUND JAPAN - Gunma - An Unstoppable Energy [p8c86lg2].mp4
[download]   1.2% of 3.60GiB at    2.57MiB/s ETA 23:39
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
Patch for this was merged, I forgot to close the issue
