### ISSUE TITLE
Danish Radio4

### ISSUE THREAD

**Issue by ole-tange** [yt-dlp/yt-dlp#4076]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Denmark

### Example URLs

https://www.radio4.dk/program/morgen-r4dio/?gid=37214&title=radio4-morgen-13-juni-kl-6-7

### Description

It should download https://traffic.omny.fm/d/clips/414edbb4-4b91-4960-8650-ad4000dbc027/bd5a9b30-6d36-4dc7-bb2b-ad4a0088d655/a44b5db4-b5c7-426b-a24f-aeb30057f864/audio.mp3?utm_source=CustomPlayer1&id=radio4web?utm_source=CustomPlayer5

### Verbose log

```shell
~~~
$ yt-dlp -vU 'https://www.radio4.dk/program/morgen-r4dio/?gid=37214&title=radio4-morgen-13-juni-kl-6-7'
[debug] Command-line config: ['-vU', 'https://www.radio4.dk/program/morgen-r4dio/?gid=37214&title=radio4-morgen-13-juni-kl-6-7']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.0-33-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: brotli-1.0.9, certifi-2020.06.20, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.radio4.dk/program/morgen-r4dio/?gid=37214&title=radio4-morgen-13-juni-kl-6-7
[generic] ?gid=37214&title=radio4-morgen-13-juni-kl-6-7: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] ?gid=37214&title=radio4-morgen-13-juni-kl-6-7: Downloading webpage
[generic] ?gid=37214&title=radio4-morgen-13-juni-kl-6-7: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.radio4.dk/program/morgen-r4dio/?gid=37214&title=radio4-morgen-13-juni-kl-6-7
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.radio4.dk/program/morgen-r4dio/?gid=37214&title=radio4-morgen-13-juni-kl-6-7
```

**Comment by dirkf** [comment]
The target is in this element:
```html
<a href="https://traffic.omny.fm/d/clips/414edbb4-4b91-4960-8650-ad4000dbc027/bd5a9b30-6d36-4dc7-bb2b-ad4a0088d655/0cfdd7cd-cbb1-4a88-a6e3-aeb5007510e4/audio.mp3?utm_source=CustomPlayer1&amp;id=radio4web" data="radio4_morgen" class="play_archive open_player no-barba">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90" class="play_svg">...</svg>
                                        </a>
```

**Comment by barsnick** [comment]
> The target is in this element:
> 
> ```
> <a href="https://traffic.omny.fm/d/clips/414edbb4-4b91-4960-8650-ad4000dbc027/bd5a9b30-6d36-4dc7-bb2b-ad4a0088d655/0cfdd7cd-cbb1-4a88-a6e3-aeb5007510e4/audio.mp3?utm_source=CustomPlayer1&amp;id=radio4web" data="radio4_morgen" class="play_archive open_player no-barba">
>                                             <svg xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90" class="play_svg">...</svg>
>                                         </a>
> ```

Actually no, that element is available multiple times in the page, and probably constitutes for a playlist/series.

The actual element for the linked show (the one that "pops up") has a `data-gid="{id}"` attribute. And also provides the title:
```
<a href="https://traffic.omny.fm/d/clips/414edbb4-4b91-4960-8650-ad4000dbc027/bd5a9b30-6d36-4dc7-bb2b-ad4a0088d655/a44b5db4-b5c7-426b-a24f-aeb30057f864/audio.mp3" data-date = '13_06_22' data-podcast="d" class='embed no-barba' data-gid="37214" data-title="Radio4 Morgen - 13. juni kl. 6-7">
```

**Comment by barsnick** [comment]
I have created a simple extractor, will post a PR soon.

Generally question: Do we really still need to manually parse HTML with regexes? The only proper helper I can identify is `extract_attributes()`.

**Comment by dirkf** [comment]
OP's link doesn't actually bring up a page for the DR4 morning show from 06:00 to to 07:00 as you would hope. The non-JS page (seen by yt-dl[p]) changes over time. It's blanked in a browser using site CSS but is clearly an episode playlist when you disable the CSS.

You can extract the `gid` (37214) from the URL and then find the `<div class="episode_block_js...>...</div>` episode element in which `<span class="gid" hidden>37214</span>` is nested  (and later the element that you quoted).

yt-dlp uses its own `HTMLBreakOnClosingTagParser` in its `get_element_text_and_html_by_tag()` and related utility functions (to answer your question).

Iterating the `(tag_content, tag_html)` returned from `get_elements_text_and_html_by_attribute('class', r'''[\s"']episode_block_js[\s'"]''', webpage, escape_value=False)` and selecting the one whose `tag_content` contains `>32714<` should give the correct `<div>` block. In yt-dl one would (currently) use `re.finditer()` with a regex ending in `(?:</div>\s*){5}` instead of the utility function.

Then inside the episode element, there is:
* `<input ... class='full_episode_description' ...>` whose `value` is the episode description
* `<p class="beskrivelse_format" ...>...</p>` whose inner text is the same
* `<span class="programDate...>...</span>` whose inner text is the episode date, but easier to get from the `data-date` of the link element
* `<span class='specific_time ep_length_js'>...</span>` whose inner text is the episode duration (needs a da-dk version of `parse_duration()` that understands `minutter`)
* and the `<a ... data-gid="37214" ...>` link element as quoted, with `href`, `data-title` and `data-date` attributes.

There's a `ld+json` block that's of no real use.

But no doubt this is similar to what you've already done.

**Comment by barsnick** [comment]
Thanks for the hints. I'll have a look at those methods. I was trying to peek at other extractors doing similar stuff, but there's _so_ much to discover. ;) 

I'll also check whether what I have written so far (close to some of your hints, minus the iteration and following `<div>`s) always returns the expected episode.

**Comment by Vangelis66** [comment]
... Well, the OP (@ole-tange) requested the creation of a new, specific, **Danish Radio InfoExtractor**, that would download an MP3 audio file (**AOD**/podcast) of the first part (0605-0700 CEST) of the episode broadcast on 20220613 and streamed on below URI:  

https://www.radio4.dk/program/morgen-r4dio/?gid=37214&title=radio4-morgen-13-juni-kl-6-7

I suspect he must have **automation** in mind, because the DR site does indeed provide built-in **downloading functionality** for the episode: 

![DR4](https://user-images.githubusercontent.com/9669492/192118934-c9284cff-1616-4d6b-b349-73eb1aa7999c.JPG)

The download button will fetch the file from the **exact same link** referenced in the "description" of this issue... 
And for more automation, DR4 do provide a **Podcast Feed** of the Radio4 Morgen show at below URI: 
```
https://www.omnycontent.com/d/playlist/414edbb4-4b91-4960-8650-ad4000dbc027/bd5a9b30-6d36-4dc7-bb2b-ad4a0088d655/fe9f5271-aa6e-4135-a3cd-ad4a0088d663/podcast.rss
```
which should be compatible with any RSS Reader (BTW, the feed goes all the way back to **Nov 1st 2019**! Each day's Radio4 Morgen show is split into 3 ca. 1hr long segments) ...

**Comment by ole-tange** [comment]
There is some (perfectly reasonably) confusion whether Radio4 has any connection to DR (Danish Broadcasting Corporation). It does not: DR and Radio4 are two completely separate companies.

In Denmark they go by the names: Radio4 and DR/Danmarks Radio. To increase the confusion DR also makes television.

I would find it unlikely if dr.dk's download links were formatted like radio4.dk's. Thus putting those in the same InfoExtractor is probably not a good idea.

May I suggest names like: "Danish Radio4.dk InfoExtractor" for the Radio4 one, and "DR.dk (Danmarks Radio/Danish Broadcasting Corporation) InfoExtractor" for the other? Those names would at least not confuse Danes (whereas DR4 definitely would).

**Comment by dirkf** [comment]
This:
* About Radio4: https://www.radio4.dk/om-radio4/

And not this:
* Hør DR P4 København, direkte og gratis: https://www.radio-danmark.dk/p4-kobenhavn

**Comment by pzhlkj6612** [comment]
Now the link should be https://radio4.dk/podcasts/radio4-morgen/radio4-morgen-13-juni-kl-6-7.

```diff
-https://www.radio4.dk/program/morgen-r4dio/?gid=37214&title=radio4-morgen-13-juni-kl-6-7
+https://www.radio4.dk/podcasts/radio4-morgen/radio4-morgen-13-juni-kl-6-7

```

.

**Comment by pzhlkj6612** [comment]
Do we really need an extractor for this site? I can see the "download" button (↓) between the "share" and "embed" buttons. 

Link: https://radio4.dk/podcasts/radio4-morgen/radio4-morgen-13-juni-kl-6-7

![screenshot of the "Radio4 Morgen" channel on radio4.dk](https://github.com/user-attachments/assets/2b607e56-33d8-4e38-b953-cabb0734cc81)

That button directly points to an informative mp3 file:

```console
$ ffprobe -hide_banner Radio4_Morgen_-_13_juni_kl_6-7.mp3
Input #0, mp3, from 'Radio4_Morgen_-_13_juni_kl_6-7.mp3':
  Metadata:
    title           : Radio4 Morgen - 13. juni kl. 6-7
    album_artist    : Radio4
    artist          : Radio4
    album           : RADIO4 MORGEN
    copyright       : Radio4
    date            : 2022
    genre           : Podcast
    TLEN            : 3300540
  Duration: 00:55:00.60, start: 0.000000, bitrate: 128 kb/s
  Stream #0:0: Audio: mp3 (mp3float), 44100 Hz, stereo, fltp, 128 kb/s
  Stream #0:1: Video: mjpeg (Progressive), yuvj444p(pc, bt470bg/unknown/unknown), 600x600 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn (attached pic)
      Metadata:
        comment         : Cover (front)

```

.
