### ISSUE TITLE
help(yt_dlp.YoutubeDL) result in KeyError: '__objclass__' on Python

### ISSUE THREAD

**Issue by fxavierho123** [yt-dlp/yt-dlp#4086]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

My code:
```
import json
import yt_dlp

URL = 'https://www.youtube.com/watch?v=BaW_jenozKc'

# ℹ️ See help(yt_dlp.YoutubeDL) for a list of available options and public functions
ydl_opts = {}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(URL, download=False)

    # ℹ️ ydl.sanitize_info makes the info json-serializable
    print(json.dumps(ydl.sanitize_info(info)))

help(yt_dlp.YoutubeDL)
```
My output:
```
$ python -u "c:\Users\user\Desktop\youtube_playlist_downloader\playlist_dowloader.py"
[youtube] BaW_jenozKc: Downloading webpage 
[youtube] BaW_jenozKc: Downloading android player API JSON 
{"id": "BaW_jenozKc", "title": "youtube-dl test video \"'/\\\u00e4\u21ad\ud835\udd50", "formats": [{"asr": 22050, "filesize": 59999, "format_id": "139", "format_note": "low", "source_preference": -1, "fps": null, "height": null, "quality": 2, "has_drm": false, "tbr": 48.071, "url": "https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1655386080&ei=gNuqYtiXN4O44gLfzo-QBQ&ip=42.200.184.162&id=o-AP99DoTlNbSTUj3XjQuWQIAI5Fz8xPwMhLwm-XHUI_n9&itag=139&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-i3b7knsd%2Csn-i3bssn7e&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=1293750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=59999&dur=9.984&lmt=1387961817987635&mt=1655364297&fvip=5&keepalive=yes&fexp=24001373%2C24007246%2C24208265&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAI_actCS2VvIoCuPYLIkEGHDIsUSrVYV_EaUMqQvFdeoAiAVh9zu-_LkDWGN7IAB_w10hG5Sf2smK3Omgvplrx0kUw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIhrnLbREtbR1waDFD3LfnBf-T5CKofSlKfvr9R5SqcTAiAD1ZkPt_12Bgm3AKynvjxxJPi1vZ18LB86OaGoYedA6g%3D%3D", "width": null, "language": "", "language_preference": -1, "preference": null, "ext": "m4a", "vcodec": "none", "acodec": "mp4a.40.5", "dynamic_range": null, "abr": 48.071, "downloader_options": {"http_chunk_size": 10485760}, "container": "m4a_dash", "protocol": "https", "audio_ext": "m4a", "video_ext": "none", "format": "139 - audio only (low)", "resolution": "audio only", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate"}}, {"asr": 48000, "filesize": 59570, "format_id": "249", "format_note": "low", "source_preference": -1, "fps": null, "height": null, "quality": 2, "has_drm": false, "tbr": 48.425, "url": "https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1655386080&ei=gNuqYtiXN4O44gLfzo-QBQ&ip=42.200.184.162&id=o-AP99DoTlNbSTUj3XjQuWQIAI5Fz8xPwMhLwm-XHUI_n9&itag=249&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-i3b7knsd%2Csn-i3bssn7e&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=1293750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=59570&dur=9.841&lmt=1506055615351916&mt=1655364297&fvip=5&keepalive=yes&fexp=24001373%2C24007246%2C24208265&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgNeuOQM57wrixIaZB7LrWWZz6wz8GYuYY1j0hcVmPN7YCIQDOoWOHKDnLPy0JfOD34q3djqRlg_jaKRA_YpJsU1BXTw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIhrnLbREtbR1waDFD3LfnBf-T5CKofSlKfvr9R5SqcTAiAD1ZkPt_12Bgm3AKynvjxxJPi1vZ18LB86OaGoYedA6g%3D%3D", "width": null, "language": "", "language_preference": -1, "preference": null, "ext": "webm", "vcodec": "none", "acodec": "opus", "dynamic_range": null, "abr": 48.425, "downloader_options": {"http_chunk_size": 10485760}, "container": "webm_dash", "protocol": "https", "audio_ext": "webm", "video_ext": "none", "format": "249 - audio only (low)", "resolution": "audio only", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate"}}, {"asr": 48000, "filesize": 77899, "format_id": "250", "format_note": "low", "source_preference": -1, "fps": null, "height": null, "quality": 2, "has_drm": false, "tbr": 63.326, "url": 
"https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1655386080&ei=gNuqYtiXN4O44gLfzo-QBQ&ip=42.200.184.162&id=o-AP99DoTlNbSTUj3XjQuWQIAI5Fz8xPwMhLwm-XHUI_n9&itag=250&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-i3b7knsd%2Csn-i3bssn7e&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=1293750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=77899&dur=9.841&lmt=1506055555143599&mt=1655364297&fvip=5&keepalive=yes&fexp=24001373%2C24007246%2C24208265&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgeOERJQWdgfKw0UK0cwrSu9QxEAc-_-8dR6JiXV-KRC8CIQDqx2qyK8H_rJevEBmb0D1oIkF393nqJgGLbbwZzfKb6Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIhrnLbREtbR1waDFD3LfnBf-T5CKofSlKfvr9R5SqcTAiAD1ZkPt_12Bgm3AKynvjxxJPi1vZ18LB86OaGoYedA6g%3D%3D", "width": null, "language": "", "language_preference": -1, "preference": null, "ext": "webm", "vcodec": "none", "acodec": "opus", "dynamic_range": null, "abr": 
63.326, "downloader_options": {"http_chunk_size": 10485760}, "container": "webm_dash", "protocol": "https", "audio_ext": "webm", "video_ext": "none", "format": "250 - 
audio only (low)", "resolution": "audio only", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate"}}, {"asr": 44100, "filesize": 157753, "format_id": "140", "format_note": "medium", "source_preference": -1, "fps": null, "height": null, "quality": 3, "has_drm": 
false, "tbr": 127.58, "url": "https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1655386080&ei=gNuqYtiXN4O44gLfzo-QBQ&ip=42.200.184.162&id=o-AP99DoTlNbSTUj3XjQuWQIAI5Fz8xPwMhLwm-XHUI_n9&itag=140&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-i3b7knsd%2Csn-i3bssn7e&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=1293750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=157753&dur=9.891&lmt=1387961817989105&mt=1655364297&fvip=5&keepalive=yes&fexp=24001373%2C24007246%2C24208265&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgZ0pJJXdLxjl9l59QmfENu3V11Jj3DXAzFgcb8PZVi0kCIFvnq-6O8IowIGgTTTAeaA-4eTwjNhREkdRwSsCmkQcH&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIhrnLbREtbR1waDFD3LfnBf-T5CKofSlKfvr9R5SqcTAiAD1ZkPt_12Bgm3AKynvjxxJPi1vZ18LB86OaGoYedA6g%3D%3D", "width": null, "language": "", "language_preference": -1, "preference": null, "ext": "m4a", "vcodec": "none", "acodec": "mp4a.40.2", "dynamic_range": null, "abr": 127.58, "downloader_options": {"http_chunk_size": 10485760}, "container": "m4a_dash", "protocol": "https", "audio_ext": "m4a", "video_ext": "none", "format": "140 - audio only (medium)", "resolution": "audio only", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate"}}, {"asr": 48000, "filesize": 142292, "format_id": "251", "format_note": "medium", "source_preference": -1, "fps": null, "height": null, "quality": 3, "has_drm": false, "tbr": 115.672, "url": "https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1655386080&ei=gNuqYtiXN4O44gLfzo-QBQ&ip=42.200.184.162&id=o-AP99DoTlNbSTUj3XjQuWQIAI5Fz8xPwMhLwm-XHUI_n9&itag=251&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-i3b7knsd%2Csn-i3bssn7e&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=1293750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=142292&dur=9.841&lmt=1506055557712479&mt=1655364297&fvip=5&keepalive=yes&fexp=24001373%2C24007246%2C24208265&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgRBnTYQxG8QQhbC9lY-9DBg4PuDt_MSLY_NSwqAPP8PgCIQD52a9YKPbqgtw8WxsbGaw5zZhPGcfKYDou8oBZ3oUJeA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIhrnLbREtbR1waDFD3LfnBf-T5CKofSlKfvr9R5SqcTAiAD1ZkPt_12Bgm3AKynvjxxJPi1vZ18LB86OaGoYedA6g%3D%3D", "width": null, "language": "", "language_preference": -1, "preference": null, "ext": "webm", "vcodec": "none", "acodec": "opus", "dynamic_range": null, "abr": 115.672, "downloader_options": {"http_chunk_size": 10485760}, "container": "webm_dash", "protocol": "https", "audio_ext": "webm", "video_ext": "none", "format": "251 - audio only (medium)", "resolution": "audio only", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
"Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate"}}, {"asr": 22050, "filesize": 57125, "format_id": "17", "format_note": "144p", "source_preference": -1, "fps": 12, "height": 144,
Traceback (most recent call last):
  File "c:\Users\user\Desktop\youtube_playlist_downloader\playlist_dowloader.py", line 18, in <module>
    help(yt_dlp.YoutubeDL)
  File "C:\Python310\lib\_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "C:\Python310\lib\pydoc.py", line 2006, in __call__
    self.help(request)
  File "C:\Python310\lib\pydoc.py", line 2065, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "C:\Python310\lib\pydoc.py", line 1785, in doc
    pager(render_doc(thing, title, forceload))
  File "C:\Python310\lib\pydoc.py", line 1778, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "C:\Python310\lib\pydoc.py", line 477, in document
    if _isclass(object): return self.docclass(*args)
  File "C:\Python310\lib\pydoc.py", line 1415, in docclass
    for name, kind, cls, value in classify_class_attrs(object)
  File "C:\Python310\lib\pydoc.py", line 300, in classify_class_attrs
    for (name, kind, cls, value) in inspect.classify_class_attrs(object):
  File "C:\Python310\lib\inspect.py", line 554, in classify_class_attrs
    homecls = getattr(get_obj, "__objclass__", homecls)
  File "C:\Python310\lib\site-packages\yt_dlp\utils.py", line 5333, in __getattr__
    return self._dict[attr]
KeyError: '__objclass__'
```

### Verbose log

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 2022-06-12-git-4d45f5acbd-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
```

**Comment by pukkandan** [comment]
Doesn't look like a yt-dlp issue, but something wrong with your Python installation. But to confirm, pls show the output of `python -VV`

**Comment by lionderful** [comment]
me too, why? any one can run help(yt_dlp.YoutubeDL) or help(yt_dlp.postprocessor) but help(yt_dlp.postprocessor.PostProcessor)?

win 11, python 3.9  KeyError: '__objclass__'
win 10, python 3.10 KeyError: '__objclass__'

**Comment by fstirlitz** [comment]
> [debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)

```sh-session
$ git show b14d523:yt_dlp/utils.py | cat -n | sed -ne '5325,5343p'
  5325	
  5326	class Namespace:
  5327	    """Immutable namespace"""
  5328	
  5329	    def __init__(self, **kwargs):
  5330	        self._dict = kwargs
  5331	
  5332	    def __getattr__(self, attr):
  5333	        return self._dict[attr]
  5334	
  5335	    def __contains__(self, item):
  5336	        return item in self._dict.values()
  5337	
  5338	    def __iter__(self):
  5339	        return iter(self._dict.items())
  5340	
  5341	    def __repr__(self):
  5342	        return f'{type(self).__name__}({", ".join(f"{k}={v}" for k, v in self)})'
  5343	
```

This is why I never bother with silly fluff like `Namespace`.

**Comment by pukkandan** [comment]
nvm, I see what happened. It's already been fixed in master

**Comment by dirkf** [comment]
The class `Namespace` has a `__getattr__()` method that raises `KeyError` when an unknown attribute is requested, but the system library `getattr()` function expects only `AttributeError`. This breaks when the inspector called by `help()` looks for the `__objclass__` attribute.

This fixes the crash:
```py
    def __getattr__(self, attr):
        if attr not in self._dict:
            raise AttributeError()
        return self._dict[attr]
```
This should too:
```py
    def __getattr__(self, attr):
        try:
            return self._dict[attr]
        except KeyError:
            raise AttributeError()
```
`locked_file.__getattr__()` is fine because it just redirects to `getattr()` on another object _ -- unless it could be called before `__init__()`_ that sets the object.

**Comment by fxavierho123** [comment]
To everyone want to solve this issue, just update your yt-dlp to the master bench version:
`python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz`
