### ISSUE TITLE
[facebook] `-u`/`-p` support for private groups

### ISSUE THREAD

**Issue by RozvM** [yt-dlp/yt-dlp#4101]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.facebook.com/groups/255784935605179/posts/767673811082953/

### Description

Can't download from private Facebook groups, however this function worked a while ago with login credentials/cookies from the browser.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-f', 'bestvideo+bestaudio', 'https://www.facebook.com/groups/255784935605179/posts/767673811082953/']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-102754-g604924a069 (setts), ffprobe N-102754-g604924a069
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.facebook.com/groups/255784935605179/posts/767673811082953/
[generic] 767673811082953: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 767673811082953: Downloading webpage
[generic] 767673811082953: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.facebook.com/groups/255784935605179/posts/767673811082953/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\generic.py", line 4031, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/groups/255784935605179/posts/767673811082953/
```

**Comment by pukkandan** [comment]
You are not passing any credentials in the given log

**Comment by RozvM** [comment]
Correct me if I'm wrong but `yt-dlp` should try to get the login info automatically from the browser or try to ask me for it.

Anyway I tried to force it but turned out the same way:
```shell
[debug] Command-line config: ['-vU', '-f', 'bestvideo+bestaudio', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.facebook.com/groups/255784935605179/posts/767673811082953/']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-102754-g604924a069 (setts), ffprobe N-102754-g604924a069
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.facebook.com/groups/255784935605179/posts/767673811082953/
[generic] 767673811082953: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 767673811082953: Downloading webpage
[generic] 767673811082953: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.facebook.com/groups/255784935605179/posts/767673811082953/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\generic.py", line 4031, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/groups/255784935605179/posts/767673811082953/
```

**Comment by pukkandan** [comment]
> Correct me if I'm wrong but yt-dlp should try to get the login info automatically from the browser or try to ask me for it.

No it doesn't

**Comment by pukkandan** [comment]
> Anyway I tried to force it but turned out the same way:

Could you try with cookies instead?

**Comment by RozvM** [comment]
Ok, that works, many thanks for your help.

I double checked the login credentials from the Firefox password manager and it is the same that I entered into the `cmd`. I'm fine with cookies too but isn't this a bug then?

```shell
[debug] Command-line config: ['-vU', '-f', 'bestvideo+bestaudio', '--cookies-from-browser', 'firefox', 'https://www.facebook.com/groups/255784935605179/posts/767673811082953/']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-102754-g604924a069 (setts), ffprobe N-102754-g604924a069
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\RozvM\AppData\Roaming\Mozilla\Firefox\Profiles\j2afhtsr.default-release\cookies.sqlite"
[Cookies] Extracted 3240 cookies from firefox
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.facebook.com/groups/255784935605179/posts/767673811082953/
[generic] 767673811082953: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 767673811082953: Downloading webpage
[generic] 767673811082953: Extracting information
[debug] Looking for video embeds
[debug] Identified a twitter:player iframe
[debug] [FacebookPluginsVideo] Extracting URL: https://www.facebook.com/plugins/video.php?height=346&width=426&href=https://www.facebook.com/ace.frantz.3/videos/4756016474500314/
[debug] [facebook] Extracting URL: https://www.facebook.com/ace.frantz.3/videos/4756016474500314/
[facebook] 4756016474500314: Downloading webpage
[facebook] 4756016474500314: Downloading MPD manifest
[debug] Sort order given by extractor: res, quality
[debug] Formats sorted by: hasvid, ie_pref, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 4756016474500314: Downloading 1 format(s): 3288118771512139v+789598919113729a
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking http downloader on "https://video-vie1-1.xx.fbcdn.net/v/t39.25447-2/289005674_760498081612556_138915120320823054_n.webm?_nc_cat=100&ccb=1-7&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdnA5XzVzZWNnb3BfbWlucmVzX2hhbG9fNDAwa19mcmFnXzJfdmlkZW8ifQ==&_nc_ohc=ZPj9TM75Sw4AX9sCZaW&_nc_ht=video-vie1-1.xx&oh=00_AT8Aev5sEia_M19_XLVovw112lRoQTzo6Wc0hJU9I1VMpw&oe=62B1ED12"
[debug] File locking is not supported on this platform. Proceeding without locking
[download] Destination: ThEy ShOuLd ReStOrE It AnD rUn It On ThE mAiN liNe [4756016474500314].f3288118771512139v.webm
[download] 100% of 719.62KiB in 00:00
[debug] Invoking http downloader on "https://video-vie1-1.xx.fbcdn.net/v/t42.1790-2/288542738_5334232709953341_3423460842470891338_n.mp4?_nc_cat=111&ccb=1-7&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfYXVkaW9fYWFjcF82NF9mcmFnXzJfYXVkaW8ifQ==&_nc_ohc=QYKXEo0tA68AX83lGtW&_nc_ht=video-vie1-1.xx&oh=00_AT_3VsiGW53dHRYca9IXxYZJsW0m9x8bd7lLf72aogMLJg&oe=62AE10D2"
[download] Destination: ThEy ShOuLd ReStOrE It AnD rUn It On ThE mAiN liNe [4756016474500314].f789598919113729a.m4a
[download] 100% of 123.39KiB in 00:00
[Merger] Merging formats into "ThEy ShOuLd ReStOrE It AnD rUn It On ThE mAiN liNe [4756016474500314].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:ThEy ShOuLd ReStOrE It AnD rUn It On ThE mAiN liNe [4756016474500314].f3288118771512139v.webm" -i "file:ThEy ShOuLd ReStOrE It AnD rUn It On ThE mAiN liNe [4756016474500314].f789598919113729a.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:ThEy ShOuLd ReStOrE It AnD rUn It On ThE mAiN liNe [4756016474500314].temp.mkv"
Deleting original file ThEy ShOuLd ReStOrE It AnD rUn It On ThE mAiN liNe [4756016474500314].f789598919113729a.m4a (pass -k to keep)
Deleting original file ThEy ShOuLd ReStOrE It AnD rUn It On ThE mAiN liNe [4756016474500314].f3288118771512139v.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
Not all sites work with -u/-p

**Comment by bashonly** [comment]
This URL is supported now. `-u`/`-p` will not be supported. Use cookies.
