### ISSUE TITLE
Download entire Dropbox folders

### ISSUE THREAD

**Issue by aero1313** [yt-dlp/yt-dlp#4121]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://www.dropbox.com/sh/r1ixvh1b5g6y2bv/AACT02V10ghtPXQprxU3h0Lqa?dl=0 

### Description

Currently the ability to download folders on Dropbox is not supported. Only the downloading of videos is. Adding this feature would allow the download of the entire folder structure starting from the top.

### Verbose log

```shell
C:\Users\chris>yt-dlp -vU --video-password password link?dl=0
[debug] Command-line config: ['-vU', '--video-password', 'PRIVATE', link?dl=0]
[debug] Home config "yt-dlp.conf": ['-o', 'C:\\Users\\Chris\\Documents\\YouTube\\%(title)s [%(id)s].%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 2021-07-11-git-79ebdbb9b9-full_build-www.gyan.dev (setts), ffprobe 2021-07-11-git-79ebdbb9b9-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [Dropbox] Extracting URL: link?dl=0
[Dropbox] r1ixvh1b5g6y2bv: Downloading webpage
[Dropbox] r1ixvh1b5g6y2bv: POSTing video password
[Dropbox] r1ixvh1b5g6y2bv: Downloading webpage
[Dropbox] r1ixvh1b5g6y2bv: Downloading m3u8 information
ERROR: 'NoneType' object has no attribute 'timeout'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\dropbox.py", line 59, in _real_extract
  File "yt_dlp\extractor\common.py", line 2139, in _extract_m3u8_formats_and_subtitles
  File "yt_dlp\extractor\common.py", line 801, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 768, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 515, in open
AttributeError: 'NoneType' object has no attribute 'timeout'
```

**Comment by snan** [comment]
@aero1313 Today I found out that you can download it with wget if you change the final 0 to a 1!
