### ISSUE TITLE
ABC (Go)

### ISSUE THREAD

**Issue by remlap** [yt-dlp/yt-dlp#4148]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

Video plays fine within browser using VPN but get warning of:

`[Go] 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.`

Tried `no-geo-bypass` without success.

https://abc.com/shows/good-morning-america/episode-guide/2022-05/16-monday-may-16-2022

Thanks for any help.

### Verbose log

```shell
[debug] Command-line config: ['--proxy=redacted', 'https://abc.com/shows/good-morning-america/episode-guide/2022-05/16-monday-may-16-2022', '--no-geo-bypass', '-v']
[debug] User config "/home/remlap/.config/yt-dlp.conf": ['--hls-prefer-native', '--add-metadata', '--sub-langs', 'all', '--embed-subs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.06.22.1 [a86e01e]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.0-40-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-9.1
[debug] Proxy map: {'http': 'redacted'}
[debug] [Go] Extracting URL: https://abc.com/shows/good-morning-america/episode-guide/2022-05/16-monday-may-16-2022
ERROR: [Go] 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.
This video is available in United States.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/home/remlap/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "/home/remlap/.local/lib/python3.10/site-packages/yt_dlp/extractor/go.py", line 252, in _real_extract
    self.raise_geo_restricted(
  File "/home/remlap/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1114, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
yt_dlp.utils.GeoRestrictedError: 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/remlap/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1427, in wrapper
    return func(self, *args, **kwargs)
  File "/home/remlap/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1497, in __extract_info
    ie_result = ie.extract(url)
  File "/home/remlap/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 673, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.GeoRestrictedError: [Go] 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories
```

**Comment by remlap** [comment]
Closing it must be my vpn or something works on another.
