### ISSUE TITLE
Daily Wire Not Working TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by jcschmidt31** [yt-dlp/yt-dlp#4154]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

I'm excited about the new Daily Wire Extractor but I have not been able to get it to work. I tried both without and with cookies and I get a TypeError: 'NoneType' object is not iterable.  Let me know if I'm doing something wrong.  Thank you!

### Verbose log

```shell
PS C:\Users\jcsch> yt-dlp https://www.dailywire.com/episode/ep-1520-the-return-of-religious-freedom-bonus-hour-2 --verbose
[debug] Command-line config: ['https://www.dailywire.com/episode/ep-1520-the-return-of-religious-freedom-bonus-hour-2', '--verbose']
[debug] Portable config "G:\yt-dlp\yt-dlp.conf": ['-o', 'G:/YoutubeDL/%(title)s.%(ext)s', '--external-downloader', 'aria2c']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (win32_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-03-24-git-28d011516b-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-24-git-28d011516b-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [DailyWire] Extracting URL: https://www.dailywire.com/episode/ep-1520-the-return-of-religious-freedom-bonus-hour-2
[DailyWire] ep-1520-the-return-of-religious-freedom-bonus-hour-2: Downloading webpage
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1427, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1497, in __extract_info
  File "yt_dlp\extractor\common.py", line 647, in extract
  File "yt_dlp\extractor\dailywire.py", line 63, in _real_extract
TypeError: 'NoneType' object is not iterable

PS C:\Users\jcsch> yt-dlp https://www.dailywire.com/episode/ep-1520-the-return-of-religious-freedom-bonus-hour-2 --cookies G:\yt-dlp\dw.txt --verbose
[debug] Command-line config: ['https://www.dailywire.com/episode/ep-1520-the-return-of-religious-freedom-bonus-hour-2', '--cookies', 'G:\\yt-dlp\\dw.txt', '--verbose']
[debug] Portable config "G:\yt-dlp\yt-dlp.conf": ['-o', 'G:/YoutubeDL/%(title)s.%(ext)s', '--external-downloader', 'aria2c']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (win32_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-03-24-git-28d011516b-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-24-git-28d011516b-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [DailyWire] Extracting URL: https://www.dailywire.com/episode/ep-1520-the-return-of-religious-freedom-bonus-hour-2
[DailyWire] ep-1520-the-return-of-religious-freedom-bonus-hour-2: Downloading webpage
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1427, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1497, in __extract_info
  File "yt_dlp\extractor\common.py", line 647, in extract
  File "yt_dlp\extractor\dailywire.py", line 63, in _real_extract
TypeError: 'NoneType' object is not iterable
```

**Comment by pukkandan** [comment]
Those videos appear to need login. Pass cookies

@HobbyistDev Can we add a better error message when login is needed?

**Comment by jcschmidt31** [comment]
As I mentioned I tried it with and without cookies.  Neither worked and I received the same error both times.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HobbyistDev** [comment]
> @HobbyistDev Can we add a better error message when login is needed?
For simple fix, i think this is sufficient
```python
        for url in urls or []:
```
But, this fix didn't actually detect login, just throw error if the media is not found

**Comment by pukkandan** [comment]
> As I mentioned I tried it with and without cookies.  Neither worked and I received the same error both times.


ah, sorry. I didn't notice cookies in the second log

**Comment by HobbyistDev** [comment]
Can you share your crendential in Discord (HobbyistDev#3257) or in email (tesutonihon4@gmail.com) ?

**Comment by HobbyistDev** [comment]
Note to self: 
It seems whole extractor can be rewrite to use `graphql` json. Login function add `authorization` header with `Bearer` token. The return json looks identical with `__NEXT_ID__` in webpage

**Comment by HobbyistDev** [comment]
I have implemented grapql api in DailyWire (not pushed yet) but have some issue for login.
DailyWire use Oauth2 for authorization, here's some steps that i monitored in dev tools:

1. The login page is in 'https://authorize.dailywire.com/usernamepassword/login' with `POST` method and have `request_data` like this
```
{
            'client_id': '<client_id>',
            'redirect_uri': 'https://www.dailywire.com/callback',
            'tenant': 'dailywire',
            'response_type': 'code',
            'scope': 'openid profile email',
            'state': <state>,
            'nonce': '<nonce>',
            'connection': 'Username-Password-Authentication',
            'username': f'{username}',
            'password': f"{password}",
            'popup_options': {},
            'sso': True,
            'response_mode': 'query',
            '_intstate': 'deprecated',
            '_csrf': <_csrf>, # always change
            'audience': 'https://api.dailywire.com/',
            'code_challenge_method': 'S256',
            'code_challenge':'<code_challenge>',
            'auth0Client': '<auth0Client>',
            "protocol":"oauth2"
        } 
```
The return of this requests is `html` for successful login and `json` for failed login. If this request return `html` they contain something like `result` and then the url request to something like `<redirect_url>?code=<code>` with `HTTP code 302`. 

2. The code from <code> is requested to `https://authorize.dailywire.com/oauth/token` with POST method and have `request_data` like this:
```
{
            'client_id': <client_id>,
            'code_verifier': <code_verifier>, # always change
            'grant_type': 'authorization_code',
            'code': <code>, # always change
            'redirect_uri': 'https://www.dailywire.com/callback',
            }
```
and then from this we can get the token from `access_token` and set `Authorization` Header to something like this:
`Authorization: <token_type> <access_token>`

The issues are :
> The return of this requests is `html` for successful login and `json` for failed login.

1. How to handle the return like this ? should i set something like `self._parse_json(..., fatal=False)` ?

> then the url request to something like `<redirect_url>?code=<code>` with `HTTP code 302`

2. How to get this url as the <code> is not found in api call or in html ? can't this redirected automatically ?

Anyway, i'm not too familiar too Oauth2, please correct me if i'm wrong

**Comment by pukkandan** [comment]
> > The return of this requests is `html` for successful login and `json` for failed login.
> 
> 1. How to handle the return like this ? should i set something like `self._parse_json(..., fatal=False)` ?

```py
try:
    webpage = _download_webpage(url, video_id)
except ExtractorError as e:
    if not isinstance(e.cause, urllib.error.HTTPError):
        raise
    error = self._parse_json(e.cause.read(), video_id)
```



> 1. 
> 
> > then the url request to something like `<redirect_url>?code=<code>` with `HTTP code 302`
> 
> 2. How to get this url as the ` is not found in api call or in html ? can't this redirected automatically ?`

I believe we currently have no mechanism to get the intermediate URL of the redirect 🤔. Any ideas @coletdjnz

**Comment by HobbyistDev** [comment]
Thanks for solution (1)

**Comment by coletdjnz** [comment]
> > > The return of this requests is `html` for successful login and `json` for failed login.
> > 
> > 
> > 
> > 1. How to handle the return like this ? should i set something like `self._parse_json(..., fatal=False)` ?
> 
> ```python
> try:
>     webpage = _download_webpage(url, video_id)
> except ExtractorError as e:
>     if not isinstance(e.cause, urllib.error.HTTPError):
>         raise
>     error = self._parse_json(e.cause.read(), video_id)
> ```
> 
> > > then the url request to something like `<redirect_url>?code=<code>` with `HTTP code 302`
> > 
> > 
> > 
> > 2. How to get this url as the ` is not found in api call or in html ? can't this redirected automatically ?`
> 
> I believe we currently have no mechanism to get the intermediate URL of the redirect thinking. Any ideas @coletdjnz

I don't quite understand what is going on here.

Is this doing something like:
POST /login
This returns a 302 response with a Location header for the redirect, but this response also contains JSON data we need to extract?

or are we doing POST /login, which returns a 200 OK response with a JSON data. the JSON data contains a "redirect url" which we are to request?


If we really need to it should be possible to disable redirects, but might require #2861

**Comment by pukkandan** [comment]
> I don't quite understand what is going on here.
> 
> Is this doing something like: POST /login This returns a 302 response with a Location header for the redirect, but this response also contains JSON data we need to extract?
> 
> or are we doing POST /login, which returns a 200 OK response with a JSON data. the JSON data contains a "redirect url" which we are to request?

We want to get the Location header in the direct response of the POST. We can't use `urlh.geturl()` since it redirects multiple times

**Comment by HobbyistDev** [comment]
The login page is requesting like this:
```
Request Header:
POST /usernamepassword/login HTTP/1.1
Host: authorize.dailywire.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
Accept: */*
Accept-Language: id,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://authorize.dailywire.com/login?state=<state>&client=<client_id>&protocol=oauth2&audience=https%3A%2F%2Fapi.dailywire.com%2F&redirect_uri=https%3A%2F%2Fwww.dailywire.com%2Fcallback&scope=openid%20profile%20email&response_type=code&response_mode=query&nonce=<nonce>&code_challenge=<code_challenge>&code_challenge_method=S256&auth0Client=<auth0Client>
Content-Type: application/json
Auth0-Client: <auth0Client>
Content-Length: 890
Origin: https://authorize.dailywire.com
DNT: 1
Connection: keep-alive
Cookie: _csrf=<_csrf>
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Sec-GPC: 1

Response Header:
HTTP/3 200 OK
date: Mon, 27 Jun 2022 00:39:41 GMT
content-type: text/html; charset=utf-8
cf-ray: 721a20823e0a879d-SIN
cache-control: private, no-store, no-cache, must-revalidate, post-check=0, pre-check=0, no-transform
etag: W/"7dc-FnmExTq+m3Ik6DzPpJEIW86OawM"
strict-transport-security: max-age=31536000
vary: Accept-Encoding
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
ot-baggage-auth0-request-id: 721a20823e0a879d
ot-tracer-sampled: true
ot-tracer-spanid: 764161b849a62105
ot-tracer-traceid: 14319fd741f13af0
traceparent: 00-764161b849a62105-000000000000000014319fd741f13af0-01
tracestate: auth0-request-id=721a20823e0a879d
x-auth0-requestid: af7851cd0f4a80613ba7
x-content-type-options: nosniff
x-ratelimit-limit: 100
x-ratelimit-remaining: 99
x-ratelimit-reset: 1656291246
server: cloudflare
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

Response:
<form method="post" name="hiddenform" action="https://authorize.dailywire.com/login/callback">
    <input type="hidden" name="wa" value="wsignin1.0">
    <input type="hidden" 
           name="wresult" 
           value=<wresult>>
    <input type="hidden" name="wctx" value=<wctx>
    <noscript>
        <p>
            Script is disabled. Click Submit to continue.
        </p><input type="submit" value="Submit">
    </noscript>
</form>

**Comment by coletdjnz** [comment]
> The login page is requesting like this:
> 
> ```
> Request Header:
> POST /usernamepassword/login HTTP/1.1
> Host: authorize.dailywire.com
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
> Accept: */*
> Accept-Language: id,en-US;q=0.7,en;q=0.3
> Accept-Encoding: gzip, deflate, br
> Referer: https://authorize.dailywire.com/login?state=<state>&client=<client_id>&protocol=oauth2&audience=https%3A%2F%2Fapi.dailywire.com%2F&redirect_uri=https%3A%2F%2Fwww.dailywire.com%2Fcallback&scope=openid%20profile%20email&response_type=code&response_mode=query&nonce=<nonce>&code_challenge=<code_challenge>&code_challenge_method=S256&auth0Client=<auth0Client>
> Content-Type: application/json
> Auth0-Client: <auth0Client>
> Content-Length: 890
> Origin: https://authorize.dailywire.com
> DNT: 1
> Connection: keep-alive
> Cookie: _csrf=<_csrf>
> Sec-Fetch-Dest: empty
> Sec-Fetch-Mode: cors
> Sec-Fetch-Site: same-origin
> Sec-GPC: 1
> 
> Response Header:
> HTTP/3 200 OK
> date: Mon, 27 Jun 2022 00:39:41 GMT
> content-type: text/html; charset=utf-8
> cf-ray: 721a20823e0a879d-SIN
> cache-control: private, no-store, no-cache, must-revalidate, post-check=0, pre-check=0, no-transform
> etag: W/"7dc-FnmExTq+m3Ik6DzPpJEIW86OawM"
> strict-transport-security: max-age=31536000
> vary: Accept-Encoding
> cf-cache-status: DYNAMIC
> expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> ot-baggage-auth0-request-id: 721a20823e0a879d
> ot-tracer-sampled: true
> ot-tracer-spanid: 764161b849a62105
> ot-tracer-traceid: 14319fd741f13af0
> traceparent: 00-764161b849a62105-000000000000000014319fd741f13af0-01
> tracestate: auth0-request-id=721a20823e0a879d
> x-auth0-requestid: af7851cd0f4a80613ba7
> x-content-type-options: nosniff
> x-ratelimit-limit: 100
> x-ratelimit-remaining: 99
> x-ratelimit-reset: 1656291246
> server: cloudflare
> alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
> 
> Response:
> <form method="post" name="hiddenform" action="https://authorize.dailywire.com/login/callback">
>     <input type="hidden" name="wa" value="wsignin1.0">
>     <input type="hidden" 
>            name="wresult" 
>            value=<wresult>>
>     <input type="hidden" name="wctx" value=<wctx>
>     <noscript>
>         <p>
>             Script is disabled. Click Submit to continue.
>         </p><input type="submit" value="Submit">
>     </noscript>
> </form>
> ```

that isn't a redirect :confused: 

you'd need to handle that callback url yourself in the extractor

**Comment by HobbyistDev** [comment]
The requests flow itself quite similar to this (https://developer.okta.com/blog/2017/06/21/what-the-heck-is-oauth#oauth-tokens)

**Comment by coletdjnz** [comment]
> > > The return of this requests is `html` for successful login and `json` for failed login.
> > 
> > 
> > 
> > 1. How to handle the return like this ? should i set something like `self._parse_json(..., fatal=False)` ?
> 
> ```python
> try:
>     webpage = _download_webpage(url, video_id)
> except ExtractorError as e:
>     if not isinstance(e.cause, urllib.error.HTTPError):
>         raise
>     error = self._parse_json(e.cause.read(), video_id)
> ```
> 
> > > then the url request to something like `<redirect_url>?code=<code>` with `HTTP code 302`
> > 
> > 
> > 
> > 2. How to get this url as the ` is not found in api call or in html ? can't this redirected automatically ?`
> 
> I believe we currently have no mechanism to get the intermediate URL of the redirect thinking. Any ideas @coletdjnz

I don't think this has anything to do with getting the intermediate URL between redirects.

> 

    then the url request to something like <redirect_url>?code=<code> with HTTP code 302

    How to get this url as the <code> is not found in api call or in html ? can't this redirected automatically ?


Use `self._request_webpage` which gives you the http response instance (not just the webpage data), which you can do `.geturl()` on. This will give you the final url in the *HTTP redirect* chain.

**Comment by pukkandan** [comment]
👍 I thought they were asking for https://github.com/yt-dlp/yt-dlp/issues/4154#issuecomment-1166700181

**Comment by HobbyistDev** [comment]
> Use self._request_webpage which gives you the http response instance (not just the webpage data), which you can do .geturl() on. This will give you the final url in the HTTP redirect chain.

Thank you for your suggestion

**Comment by HobbyistDev** [comment]
Is there any way to get response cookie from `_request_webpage`  ?

**Comment by pukkandan** [comment]
`self._get_cookies(url).get(cookie_name)`

**Comment by HobbyistDev** [comment]
Sorry to bother you again. I want to get a key-value of cookie to be set on header, is there anyway to do this ?

**Comment by pukkandan** [comment]
I don't understand

**Comment by HobbyistDev** [comment]
i mean the `url/<slug>` request cookie like this:
```Cookie: _dd_s=logs=<dd_logs>&created=<created>; spotim_visitId=<spotim_visitId>; _legacy_auth0.<state>.is.authenticated=<bool>; auth0.<client_id>.is.authenticated=<bool>; accessToken=<access_token>```
As we can see, the `accessToken` is inside the cookie.
However, in the next request after that, `accessToken` is set in header. It's looks like this:
`Authorization: Bearer <access_token>`

**Comment by pukkandan** [comment]
`token = self._get_cookies(url).get('access_token')` doesn't work?

**Comment by HobbyistDev** [comment]
> `token = self._get_cookies(url).get('access_token')` doesn't work?

No, it doesn't work, it always return `None`. I mean the cookies not neccessary from the url as the cookies can 'supplied' from user too. I think `_get_cookies` supposed to return **response** cookie not the **request** cookie, am i right ?

**Comment by pukkandan** [comment]
It returns all the cookies currently associated with the `url`. Are you sure you are using the correct URL? If you can push your code to GH, it would be much easier than sharing snippets back and forth

**Comment by HobbyistDev** [comment]
Sorry for slow response, here's my branch for this fix https://github.com/HobbyistDev/yt-dlp/tree/dailywire-fix

**Comment by emayzing** [comment]
Hi, is this still being worked? I have a login to test.

**Comment by pukkandan** [comment]
> Sorry for slow response, here's my branch for this fix [HobbyistDev/yt-dlp@`dailywire-fix`](https://github.com/HobbyistDev/yt-dlp/tree/dailywire-fix?rgh-link-date=2022-06-28T09%3A54%3A12Z). Should i make draft PR to this repo ?

orry, it seems I completely missed this message. What do you get when you do `elf._get_cookies('https://www.dailywire.com)`. It should have the `accessToken` if it is being set correctly. Can you see it being set in `--print-trafic`?
