### ISSUE TITLE
[Freesound] Downloaded Audios

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#4161]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Southern California, USA (not telling the exact town I'm living in for privacy reasons unless required)

### Example URLs

https://freesound.org/people/C418/downloaded_sounds/

### Description

Putting the url gives an error. I would like to download all audios made by C418 used in the MINECRAFT video game.

### Verbose log

```shell
Run ia configure --username="$IA_EMAIL" --***
10
Config saved to: /home/runner/.config/internetarchive/ia.ini
11
[generic] Falling back on generic information extractor.
12
ERROR: Unsupported URL: https://freesound.org/people/C418/downloaded_sounds/
13
Traceback (most recent call last):
14
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1427, in wrapper
15
    return func(self, *args, **kwargs)
16
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1497, in __extract_info
17
    ie_result = ie.extract(url)
18
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 647, in extract
19
    ie_result = self._real_extract(url)
20
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4136, in _real_extract
21
    raise UnsupportedError(url)
22
yt_dlp.utils.UnsupportedError: Unsupported URL: https://freesound.org/people/C418/downloaded_sounds/
23
24
Traceback (most recent call last):
25
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/tubeup/__main__.py", line 103, in main
26
    for identifier, meta in tu.archive_urls(URLs, metadata,
27
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/tubeup/TubeUp.py", line 415, in archive_urls
28
    downloaded_file_basenames = self.get_resource_basenames(
29
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/tubeup/TubeUp.py", line 178, in get_resource_basenames
30
    if info_dict.get('_type', 'video') == 'playlist':
31
AttributeError: 'NoneType' object has no attribute 'get'
32
33
An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
```

**Comment by HobbyistDev** [comment]
Hello, this is not yt-dlp log (this is `tubeup` log). If you use yt-dlp, please prove log from `yt-dlp -v "your_url"`.

**Comment by dirkf** [comment]
Regardless, your URL is a playlist-type page and the extractor only supports individual sound pages, so this is a site enhancement request.

A playlist IE would need to enumerate the links inside the `<div class="sound_filename">...</div>` elements on the page, or on each page of the linked results.

As this seems to be required so often in slightly different ways, perhaps we should have a `PlaylistBaseIE` as an abstract framework for it, similar to `SearchInfoExtractor`?

**Comment by pukkandan** [comment]
> As this seems to be required so often in slightly different ways, perhaps we should have a PlaylistBaseIE as an abstract framework for it, similar to SearchInfoExtractor?

Do you mean this pattern?
```py
playlist_id, ... = self._match_valid_url(url).group(...)
webpage = self._download_webpage(url, video_id)
...
return self._playlist_from_matches(VideoIE._extract_urls(...), ...)
```
For this, the video IE just needs to implement the `_extract_urls` (and add some boilerplate in Generic)

The reason many PlaylistIEs often need to be even created for this code is because they extract some additional metadata. Not sure how that can be generalized

**Comment by dirkf** [comment]
Was thinking more of the paginated list pattern, where one might loop: start with a webpage, or have to download it, `yield from re.finditer(...)`, then find or calculate the next page, or quit.

Variations if the entry list is a fancier type, if you want a fancier getter than lambda m: m.group('url'), etc.

**Comment by dirkf** [comment]
Example: the Freesound playlist extractor:
```py
from .playlistbase import PlaylistBaseIE

class FreesoundPlaylistIE(PlaylistBaseIE):
    _VALID_URL = r'https?://(?:www\.)?freesound\.org/people/(?P<person>[^/]+)/(?P<type>downloaded_sounds|packs)/(?P<id>[^/]*)'

    _ITEM_RE = r'''(?s)<div\b[^>]+\bclass\s*=\s*("|')sound_filename\1[^>]*>\s*<a\b[^>]+\bclass\s*=\s*("|')title\2[^>]+\bhref\s*=\s*("|')(?P<url>(?:(?!\3).)+)'''
    _NEXT_RE = r'''<a\b[^>]+\bhref\s*=\s*("|')(?P<url>(?:(?!\1).)+)[^>]+\btitle\s*=\s*["']Next\s+Page'''
    _ITEM_IE = 'Freesound'
```
And `playlistbase.py` (using olde worlde yt-dl conventions):
```py
# coding: utf-8
from __future__ import unicode_literals

import itertools
import re

from .common import InfoExtractor

from ..compat import (
    compat_kwargs,
)
from ..utils import (
    urljoin,
)


class PlaylistBaseIE(InfoExtractor):

    @property
    def _ITEM_RE(self):
        """
           Regex to match items
        """
        raise NotImplementedError('This attribute must be implemented by subclasses')

    @property
    def _NEXT_RE(self):
        """
           Regex to match next page URL
        """
        raise NotImplementedError('This attribute must be implemented by subclasses')

    @property
    def _ITEM_IE(self):
        """
           IE_KEY for items
           Specialise as required
        """
        return None

    def _next_page(self, pl_id, html, this_url=None, page_num=None):
        """
           Return URL of next page to be downloaded, or None
        """
        next_page = self._search_regex(self._NEXT_RE, html, 'next page link', group='url', default=None)
        return next_page and urljoin(this_url, next_page)

    def _item_get(self, match_obj):
        """
            Return item matched in match_obj
        """
        return match_obj.group('url')

    def _entries(self, url, pl_id, webpage=None):
        """
           Generate items to be downloaded, or None
        """
        page_url = url
        for page in itertools.count(1 if webpage else 0):
            if not webpage:
                kwargs = {} if page < 2 else {'note': 'Downloading page %d' % (page, )}
                webpage = self._download_webpage(
                    page_url, pl_id, fatal=False, **compat_kwargs(kwargs))
            if not webpage:
                break
            for m in re.finditer(self._ITEM_RE, webpage):
                yield m
            next_page = self._next_page(pl_id, webpage, page_url, page)
            if not next_page or next_page == page_url:
                break
            page_url, webpage = next_page, None

    def _playlist_page_extract(self, url, pl_id, webpage):
        """
            Return playlist metadata: specialise as required
        """
        return {}

    def _real_extract(self, url):
        pl_id = self._match_id(url)
        webpage = self._download_webpage(url, pl_id)

        result = self.playlist_from_matches(
            self._entries(url, pl_id, webpage),
            playlist_id=pl_id, getter=lambda m: urljoin(url, self._item_get(m)), ie=self._ITEM_IE)
        result.update(self._playlist_page_extract(url, pl_id, webpage))
        return result
```

**Comment by godofgrunts** [comment]
Not sure how the patching pipeline works here, but I see that "patch-available" tag and `yt-dlp` still doesn't work on freesound so I assume that means that this patch hasn't been merged yet correct?

Just in case, here is my `-v` output:

```
yt-dlp -v https://freesound.org/people/Eelke/sounds/462613/
[debug] Command-line config: ['-v', 'https://freesound.org/people/Eelke/sounds/462613/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.6.2-arch1-1-x86_64-with-glibc2.38 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1 (setts), ffprobe 6.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.1.0.0, certifi-2023.11.17, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[Freesound] Extracting URL: https://freesound.org/people/Eelke/sounds/462613/
[Freesound] 462613: Downloading webpage
ERROR: [Freesound] 462613: Unable to extract song url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/freesound.py", line 34, in _real_extract
    audio_url = self._og_search_property('audio', webpage, 'song url')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1388, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```
