### ISSUE TITLE
Clubhouse Voice Social App Support

### ISSUE THREAD

**Issue by codenamedpkt** [yt-dlp/yt-dlp#4172]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required
- [x] I updated the code for previous comment.

### Region

Global, except countries that blocked from national firewall

### Example URLs

- Single Audio:
https://www.clubhouse.com/room/PN50O4GG?utm_medium=ch_room_xerc&utm_campaign=MNCJrc7UGsjhsqjZi3ZqJQ-248223
- Example Thumbnails Related for the Audio:
https://www.clubhouse.com/og/room/PN50O4GG.png?utm_medium=ch_room_xerc&utm_campaign=MNCJrc7UGsjhsqjZi3ZqJQ-248223
- Metadata Script for the Clubhouse App:
https://static-assets.clubhouseapi.com/static/web_client/js/build.dddd417c0e2e.js
- The App Source Code of this Example Page:
<br /> Please copy, paste only and do not click the link below
<br />view-source:https://www.clubhouse.com/room/PN50O4GG?utm_medium=ch_room_xerc&utm_campaign=MNCJrc7UGsjhsqjZi3ZqJQ-248223

### Description

Introduction to Clubhouse Mobile App:
https://en.m.wikipedia.org/wiki/Clubhouse_(app)

Their offical site:
https://www.clubhouse.com/

### Verbose log

```shell
yt-dlp -vUcw --user-agent "Mozilla/5.0 (Windows NT 10.0.22623; Win64; arm64) HTTP/3.0 Chrome/107.0.5300.0 Edg/107.0.1379.1 yt-dlp/$VERSION aria2/$VERSION wget/$VERSION Transmission/3.00 IPTV Pro/$VERSION" --referer "%(referer)s" -N 4294967295 -f mergeall --video-multistreams --audio-multistreams --embed-subs --sub-langs all --sub-format best --embed-thumbnail --embed-chapters --downloader aria2c "https://www.clubhouse.com/room/PN50O4GG?utm_medium=ch_room_xerc&utm_campaign=MNCJrc7UGsjhsqjZi3ZqJQ-248223"                                                            [debug] Command-line config: ['-vUcw', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0.22623; Win64; arm64) HTTP/3.0 Chrome/107.0.5300.0 Edg/107.0.1379.1 yt-dlp/ aria2/ wget/ Transmission/3.00 IPTV Pro/', '--referer', '%(referer)s', '-N', '4294967295', '-f', 'mergeall', '--video-multistreams', '--audio-multistreams', '--embed-subs', '--sub-langs', 'all', '--sub-format', 'best', '--embed-thumbnail', '--embed-chapters', '--downloader', 'aria2c', 'https://www.clubhouse.com/room/PN50O4GG?utm_medium=ch_room_xerc&utm_campaign=MNCJrc7UGsjhsqjZi3ZqJQ-248223']                                   [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8                           [debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API                                                                 [debug] Python 3.10.8 (CPython 64bit) - Linux-4.9.186-22986754-aarch64-with-libc (libc)                               [debug] Checking exe version: ffmpeg -bsfs                                                                            [debug] Checking exe version: ffprobe -bsfs                                                                           [debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2                                                             [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3                                                                                                             [debug] Proxy map: {}                                                                                                 [debug] Loaded 1690 extractors                                                                                        [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest                             Latest version: 2022.10.04, Current version: 2022.10.04                                                               yt-dlp is up to date (2022.10.04)                                                                                     [debug] [generic] Extracting URL: https://www.clubhouse.com/room/PN50O4GG?utm_medium=ch_room_xerc&utm_campaign=MNCJrc7UGsjhsqjZi3ZqJQ-248223                                                                                                [generic] PN50O4GG?utm_medium=ch_room_xerc&utm_campaign=MNCJrc7UGsjhsqjZi3ZqJQ-248223: Downloading webpage            WARNING: [generic] Falling back on generic information extractor                                                      [generic] PN50O4GG?utm_medium=ch_room_xerc&utm_campaign=MNCJrc7UGsjhsqjZi3ZqJQ-248223: Extracting information         [debug] Looking for Brightcove embeds                                                                                 [debug] Looking for embeds                                                                                            ERROR: Unsupported URL: https://www.clubhouse.com/room/PN50O4GG?utm_medium=ch_room_xerc&utm_campaign=MNCJrc7UGsjhsqjZi3ZqJQ-248223                                                                                                          Traceback (most recent call last):                                                                                      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper          return func(self, *args, **kwargs)                                                                                  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1553, in __extract_info                                                                                                                         ie_result = ie.extract(url)                                                                                         File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract    ie_result = self._real_extract(url)                                                                                 File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3062, in _real_extract                                                                                                                  raise UnsupportedError(url)                                                                                       yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.clubhouse.com/room/PN50O4GG?utm_medium=ch_room_xerc&utm_campaign=MNCJrc7UGsjhsqjZi3ZqJQ-248223
```

### Note
As 6 November 2022 tested with Mr. Poon's Studio, we haven't seen fixes and improvements of this issue mentioned.

**Comment by Ashish0804** [comment]
I'm taking this up and will be treating this as a podcast extractor (no fancy parsing of when a guy joined or who is speaking etc)
