### ISSUE TITLE
Cannot download videos from HKET.

### ISSUE THREAD

**Issue by codenamedpkt** [yt-dlp/yt-dlp#4173]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've updated details and verbose output as reflect the changes of host and yt-dlp
### Description

There is a video here in https://video.hket.com/article/3278159?r=cpstna but having an errors. Err. Code: SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED
I use openssl 3.0.5 instead legacy 1.x. This video seem downloadable here.

Source code:

(Please do not click the link and do copy contents below.)

view-source:https://video.hket.com/article/3278159?r=cpstna

### Verbose log

```shell
Single video:

yt-dlp -vUcw --user-agent "Mozilla/5.0 (Windows NT 10.0.22623; Win64; arm64) HTTP/3.0 Chrome/107.0.5300.0 Edg/107.0.1379.1 yt-dlp/$VERSION aria2/$VERSION wget/$VERSION Transmission/3.00 IPTV Pro/$VERSION" --referer "%(referer)s" -N 4294967295 -f mergeall --video-multistreams --audio-multistreams --embed-subs --sub-langs all --sub-format best --embed-thumbnail --embed-chapters --downloader aria2c "https://video.hket.com/video/3388102?r=cpstna"   [debug] Command-line config: ['-vUcw', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0.22623; Win64; arm64) HTTP/3.0 Chrome/107.0.5300.0 Edg/107.0.1379.1 yt-dlp/ aria2/ wget/ Transmission/3.00 IPTV Pro/', '--referer', '%(referer)s', '-N', '4294967295', '-f', 'mergeall', '--video-multistreams', '--audio-multistreams', '--embed-subs', '--sub-langs', 'all', '--sub-format', 'best', '--embed-thumbnail', '--embed-chapters', '--downloader', 'aria2c', 'https://video.hket.com/video/3388102?r=cpstna']                                                                                                [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8                           [debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API                                                                 [debug] Python 3.10.8 (CPython 64bit) - Linux-4.9.186-22986754-aarch64-with-libc (libc)                               [debug] Checking exe version: ffmpeg -bsfs                                                                            [debug] Checking exe version: ffprobe -bsfs                                                                           [debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2                                                             [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3                                                                                                             [debug] Proxy map: {}                                                                                                 [debug] Loaded 1690 extractors                                                                                        [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest                             Latest version: 2022.10.04, Current version: 2022.10.04                                                               yt-dlp is up to date (2022.10.04)                                                                                     [debug] [generic] Extracting URL: https://video.hket.com/video/3388102?r=cpstna                                       [generic] 3388102?r=cpstna: Downloading webpage                                                                       ERROR: [generic] Unable to download webpage: <urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)> (caused by URLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))                                                                       File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract    ie_result = self._real_extract(url)                                                                                 File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2614, in _real_extract                                                                                                                  full_response = self._request_webpage(url, video_id, headers={                                                      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 823, in _request_webpage                                                                                                                 raise ExtractorError(errmsg, cause=err)                                                                                                                                                                                                   File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 1348, in do_open                          h.request(req.get_method(), req.selector, req.data, headers,                                                        File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 1282, in request                             self._send_request(method, url, body, headers, encode_chunked)                                                      File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 1328, in _send_request                       self.endheaders(body, encode_chunked=encode_chunked)                                                                File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 1277, in endheaders                          self._send_output(message_body, encode_chunked=encode_chunked)                                                      File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 1037, in _send_output                        self.send(msg)                                                                                                      File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 975, in send                                 self.connect()                                                                                                      File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 1454, in connect                             self.sock = self._context.wrap_socket(self.sock,                                                                    File "/data/data/com.termux/files/usr/lib/python3.10/ssl.py", line 513, in wrap_socket                                  return self.sslsocket_class._create(                                                                                File "/data/data/com.termux/files/usr/lib/python3.10/ssl.py", line 1071, in _create                                     self.do_handshake()                                                                                                 File "/data/data/com.termux/files/usr/lib/python3.10/ssl.py", line 1342, in do_handshake                                self._sslobj.do_handshake()                                                                                       ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)                                                                                                                                 During handling of the above exception, another exception occurred:                                                                                                                                                                         Traceback (most recent call last):                                                                                      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 805, in _request_webpage                                                                                                                 return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))                         File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3682, in urlopen          return self._opener.open(req, timeout=self._socket_timeout)                                                         File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 519, in open                              response = self._open(req, data)                                                                                    File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 536, in _open                             result = self._call_chain(self.handle_open, protocol, protocol +                                                    File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain                       result = func(*args)                                                                                                File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 1498, in https_open           return self.do_open(                                                                                                File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 1351, in do_open                          raise URLError(err)                                                                                               urllib.error.URLError: <urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)>

Playlist:
yt-dlp -vUcw --user-agent "Mozilla/5.0 (Windows NT 10.0.22623; Win64; arm64) HTTP/3.0 Chrome/107.0.5300.0 Edg/107.0.1379.1 yt-dlp/$VERSION aria2/$VERSION wget/$VERSION Transmission/3.00 IPTV Pro/$VERSION" --referer "%(referer)s" -N 4294967295 -f mergeall --video-multistreams --audio-multistreams --embed-subs --sub-langs all --sub-format best --embed-thumbnail --embed-chapters --downloader aria2c "https://video.hket.com/srvv023-12/%E9%9D%92%E5%A7%90%E8%A9%B1?mtc=a0002" --yes-playlist                                                                                [debug] Command-line config: ['-vUcw', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0.22623; Win64; arm64) HTTP/3.0 Chrome/107.0.5300.0 Edg/107.0.1379.1 yt-dlp/ aria2/ wget/ Transmission/3.00 IPTV Pro/', '--referer', '%(referer)s', '-N', '4294967295', '-f', 'mergeall', '--video-multistreams', '--audio-multistreams', '--embed-subs', '--sub-langs', 'all', '--sub-format', 'best', '--embed-thumbnail', '--embed-chapters', '--downloader', 'aria2c', 'https://video.hket.com/srvv023-12/%E9%9D%92%E5%A7%90%E8%A9%B1?mtc=a0002', '--yes-playlist']                                                    [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8                           [debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API                                                                 [debug] Python 3.10.8 (CPython 64bit) - Linux-4.9.186-22986754-aarch64-with-libc (libc)                               [debug] Checking exe version: ffmpeg -bsfs                                                                            [debug] Checking exe version: ffprobe -bsfs                                                                           [debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2                                                             [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3                                                                                                             [debug] Proxy map: {}                                                                                                 [debug] Loaded 1690 extractors                                                                                        [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest                             Latest version: 2022.10.04, Current version: 2022.10.04                                                               yt-dlp is up to date (2022.10.04)                                                                                     [debug] [generic] Extracting URL: https://video.hket.com/srvv023-12/%E9%9D%92%E5%A7%90%E8%A9%B1?mtc=a0002             [generic] 青姐話?mtc=a0002: Downloading webpage                                                                       ERROR: [generic] Unable to download webpage: <urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)> (caused by URLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))                                                                       File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract    ie_result = self._real_extract(url)                                                                                 File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2614, in _real_extract                                                                                                                  full_response = self._request_webpage(url, video_id, headers={                                                      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 823, in _request_webpage                                                                                                                 raise ExtractorError(errmsg, cause=err)                                                                                                                                                                                                   File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 1348, in do_open                          h.request(req.get_method(), req.selector, req.data, headers,                                                        File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 1282, in request                             self._send_request(method, url, body, headers, encode_chunked)                                                      File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 1328, in _send_request                       self.endheaders(body, encode_chunked=encode_chunked)                                                                File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 1277, in endheaders                          self._send_output(message_body, encode_chunked=encode_chunked)                                                      File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 1037, in _send_output                        self.send(msg)                                                                                                      File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 975, in send                                 self.connect()                                                                                                      File "/data/data/com.termux/files/usr/lib/python3.10/http/client.py", line 1454, in connect                             self.sock = self._context.wrap_socket(self.sock,                                                                    File "/data/data/com.termux/files/usr/lib/python3.10/ssl.py", line 513, in wrap_socket                                  return self.sslsocket_class._create(                                                                                File "/data/data/com.termux/files/usr/lib/python3.10/ssl.py", line 1071, in _create                                     self.do_handshake()                                                                                                 File "/data/data/com.termux/files/usr/lib/python3.10/ssl.py", line 1342, in do_handshake                                self._sslobj.do_handshake()                                                                                       ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)                                                                                                                                 During handling of the above exception, another exception occurred:                                                                                                                                                                         Traceback (most recent call last):                                                                                      File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 805, in _request_webpage                                                                                                                 return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))                         File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3682, in urlopen          return self._opener.open(req, timeout=self._socket_timeout)                                                         File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 519, in open                              response = self._open(req, data)                                                                                    File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 536, in _open                             result = self._call_chain(self.handle_open, protocol, protocol +                                                    File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain                       result = func(*args)                                                                                                File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 1498, in https_open           return self.do_open(                                                                                                File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 1351, in do_open                          raise URLError(err)                                                                                               urllib.error.URLError: <urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)>
```

**Comment by coletdjnz** [comment]
try `--legacy-server-connect`

**Comment by Ashish0804** [comment]
the m3u8 generation is very poorly written -_-

src: "https://" + t.domain + "/" + t.sourceDir + "/" + r + "/" + e.videoId + "/" + a[1] + ".m3u8",
        
Will be taking up this extractor regardless.

**Comment by Ashish0804** [comment]
@codenamedpkt update ur request with the url format in the site-request template:
Single video:
single video:
playlist/series:
