### ISSUE TITLE
Download of Viki subtitles fails

### ISSUE THREAD

**Issue by donnekgit** [yt-dlp/yt-dlp#4175]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm trying to download Korean subtitles (example below), but getting the error:
`ERROR: 'NoneType' object has no attribute 'items'`

### Verbose log

```shell
python3 ~/data/downloads/multimedia/yt-dlp/yt-dlp -vu --write-sub --sub-format srt --sub-lang ko --skip-download https://www.viki.com/videos/1116023v-defendant-episode-1
[debug] Command-line config: ['-vu', '--write-sub', '--sub-format', 'srt', '--sub-lang', 'ko', '--skip-download', 'https://www.viki.com/videos/1116023v-defendant-episode-1']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-51-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: certifi-2019.11.28, pycrypto-2.6.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[viki] Logging in
WARNING: [viki] Unable to download JSON metadata: HTTP Error 404: Not Found
WARNING: [viki] Login Failed: Unable to get session token
[debug] [viki] Extracting URL: https://www.viki.com/videos/1116023v-defendant-episode-1
[viki] 1116023v: Downloading video JSON
ERROR: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1427, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1497, in __extract_info
    ie_result = ie.extract(url)
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/extractor/viki.py", line 230, in _real_extract
    video = self._call_api(f'videos/{video_id}.json', video_id, 'Downloading video JSON', query={})
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/extractor/viki.py", line 69, in _call_api
    resp = self._download_json(
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 1001, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 965, in download_handle
    res = self._download_webpage_handle(
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 833, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 772, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 738, in _create_request
    return sanitized_Request(url_or_request, data, headers)
  File "/home/kevin/data/downloads/multimedia/yt-dlp/yt-dlp/yt_dlp/utils.py", line 766, in sanitized_Request
    return compat_urllib_request.Request(url, *args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 334, in __init__
    for key, value in headers.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by pukkandan** [comment]
Same underlying issue as #4164
