### ISSUE TITLE
ERTFlix extractor not working, and messed subtitles come as mp4 file

### ISSUE THREAD

**Issue by jaydomas** [yt-dlp/yt-dlp#4180]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

World

### Description

While there is a built-in ERTFlix extractor, it's not working without linking directly to the mpd file. Also, the subs come only as mp4 with messed timings and double or triple lines.

Hopefully, it can be fixed.

### Verbose log

```shell
yt-dlp>yt-dlp.exe -vU https://www.ertflix.gr/en/vod/vod.127652-ta-kalytera-mas-chronia-ep1-mia-volta-sto-feggari
[debug] Command-line config: ['-vU', 'https://www.ertflix.gr/en/vod/vod.127652-ta-kalytera-mas-chronia-ep1-mia-volta-sto-feggari']
[debug] Encodings: locale cp1257, fs utf-8, pref cp1257, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (win32_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg N-107228-g9fdfc74877-20220624 (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.22.1, Current version: 2022.06.22.1
yt-dlp is up to date (2022.06.22.1)
[debug] [generic] Extracting URL: https://www.ertflix.gr/en/vod/vod.127652-ta-kalytera-mas-chronia-ep1-mia-volta-sto-feggari
[generic] vod: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] vod: Downloading webpage
[generic] vod: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.ertflix.gr/en/vod/vod.127652-ta-kalytera-mas-chronia-ep1-mia-volta-sto-feggari
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1427, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1497, in __extract_info
  File "yt_dlp\extractor\common.py", line 647, in extract
  File "yt_dlp\extractor\generic.py", line 4136, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.ertflix.gr/en/vod/vod.127652-ta-kalytera-mas-chronia-ep1-mia-volta-sto-feggari


yt-dlp>yt-dlp.exe -vU https://mediaserve.ert.gr/bpk-vod/vodext/default/ta-kalytera-mas-hronia-s01-ep01-subs/ta-kalytera-mas-hronia-s01-ep01-subs/index.mpd
[debug] Command-line config: ['-vU', 'https://mediaserve.ert.gr/bpk-vod/vodext/default/ta-kalytera-mas-hronia-s01-ep01-subs/ta-kalytera-mas-hronia-s01-ep01-subs/index.mpd']
[debug] Encodings: locale cp1257, fs utf-8, pref cp1257, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (win32_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg N-107228-g9fdfc74877-20220624 (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.22.1, Current version: 2022.06.22.1
yt-dlp is up to date (2022.06.22.1)
[debug] [generic] Extracting URL: https://mediaserve.ert.gr/bpk-vod/vodext/default/ta-kalytera-mas-hronia-s01-ep01-subs/ta-kalytera-mas-hronia-s01-ep01-subs/index.mpd
[generic] index: Requesting header
[redirect] Following redirect to https://ert-vod2.siliconweb.com/bpk-vod/vodext/default/ta-kalytera-mas-hronia-s01-ep01-subs/ta-kalytera-mas-hronia-s01-ep01-subs/index.mpd
[debug] [generic] Extracting URL: https://ert-vod2.siliconweb.com/bpk-vod/vodext/default/ta-kalytera-mas-hronia-s01-ep01-subs/ta-kalytera-mas-hronia-s01-ep01-subs/index.mpd
[generic] index: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] index: Downloading 1 format(s): video=4000684+audio=128000
[debug] Invoking dashsegments downloader on "https://ert-vod2.siliconweb.com/bpk-vod/vodext/default/ta-kalytera-mas-hronia-s01-ep01-subs/ta-kalytera-mas-hronia-s01-ep01-subs/index.mpd"
[dashsegments] Total fragments: 274
[download] Destination: index [index].fvideo=4000684.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of 1.27GiB in 05:13
[debug] Invoking dashsegments downloader on "https://ert-vod2.siliconweb.com/bpk-vod/vodext/default/ta-kalytera-mas-hronia-s01-ep01-subs/ta-kalytera-mas-hronia-s01-ep01-subs/index.mpd"
[dashsegments] Total fragments: 274
[download] Destination: index [index].faudio=128000.m4a
[download] 100% of 42.15MiB in 02:00
[Merger] Merging formats into "index [index].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:index [index].fvideo=4000684.mp4" -i "file:index [index].faudio=128000.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:index [index].temp.mp4"
Deleting original file index [index].faudio=128000.m4a (pass -k to keep)
Deleting original file index [index].fvideo=4000684.mp4 (pass -k to keep)
```

**Comment by pukkandan** [comment]
> While there is a built-in ERTFlix extractor, it's not working without linking directly to the mpd file. 

Provide verbose log!

> Also, the subs come only as mp4 with messed timings and double or triple lines.

See https://github.com/yt-dlp/yt-dlp/pull/247#issuecomment-827628350 https://github.com/yt-dlp/yt-dlp/issues/631#issuecomment-893329480

**Comment by jaydomas** [comment]
Extractor failing:
yt-dlp.exe --verbose https://www.ertflix.gr/en/vod/vod.127652-ta-kalytera-mas-chronia-ep1-mia-volta-sto-feggari

Subtitle issue:
yt-dlp.exe --verbose https://mediaserve.ert.gr/bpk-vod/vodext/default/ta-kalytera-mas-hronia-s01-ep01-subs/ta-kalytera-mas-hronia-s01-ep01-subs/index.mpd

**Comment by HobbyistDev** [comment]
What pukkandan trying to say is you must run the command and post the result not just post what command you type

**Comment by jaydomas** [comment]
Is this one? Sorry, I am new to this.
WARNING: [generic] Falling back on generic information extractor.

I've edited the main Verbose log, too.
