### ISSUE TITLE
"Cannot allocate memory" with `--embed-metadata` on CW

### ISSUE THREAD

**Issue by ischmidt20** [yt-dlp/yt-dlp#4182]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When using `--embed-metadata`, I see a "Cannot allocate memory" error. While I have only seen this with videos downloaded from the CW, I am not reporting it as an extractor error because it is raised by the postprocessor. Verbose log included below, example video is freely available, but is probably geolocked to US.

I certainly have enough space and memory on my machine, as I can download other videos using yt-dlp just fine, and do other tasks unrelated to yt-dlp. I should also note that after this error, I still see the `.meta` files on my machine, so I can provide those if necessary.

### Verbose log

```shell
yt-dlp -f 'worst[height=1080]' 'https://www.cwtv.com/shows/legends-of-the-hidden-temple/the-maya-legend-of-the-hero-twins/?play=c70d460a-a3ac-4048-b941-769eb511b91e' -N 4 --embed-metadata --fixup force -vU
[debug] Command-line config: ['-f', 'worst[height=1080]', 'https://www.cwtv.com/shows/legends-of-the-hidden-temple/the-maya-legend-of-the-hero-twins/?play=c70d460a-a3ac-4048-b941-769eb511b91e', '-N', '4', '--embed-metadata', '--fixup', 'force', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e]
[debug] Python version 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.22.1, Current version: 2022.06.22.1
yt-dlp is up to date (2022.06.22.1)
[debug] [CWTV] Extracting URL: https://www.cwtv.com/shows/legends-of-the-hidden-temple/the-maya-legend-of-the-hero-twins/?play=c70d460a-a3ac-4048-b941-769eb511b91e
[CWTV] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading JSON metadata
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/cwtv/media/guid/2703454149/c70d460a-a3ac-4048-b941-769eb511b91e?format=SMIL&formats=M3U&tracking=true&mbr=false#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading SMIL data
[ThePlatform] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading m3u8 information
WARNING: [ThePlatform] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ThePlatform] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading JSON metadata
[info] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading 1 format(s): hls-5264-0
[debug] Invoking hlsnative downloader on "https://62-on-3aa37dc0e8bb47e08042e0ebb25acb34.vip6-iad1.dlvr1.net/9c6905a2-f4d3-11ec-a07e-a9e968188580/nosec/The_CW/613/717/123049029948/LegendsOfTheHiddenTemple-101-HeroTwins-P1005-CW_123051077522_m3u8_video_1920x1080_5000000_primary_audio_eng_7.m3u8"
[download] The Maya Legend of the Hero Twins [c70d460a-a3ac-4048-b941-769eb511b91e].mp4 has already been downloaded
[download] 100% of 1.52GiB
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:The Maya Legend of the Hero Twins [c70d460a-a3ac-4048-b941-769eb511b91e].mp4'
[Metadata] Adding metadata to "The Maya Legend of the Hero Twins [c70d460a-a3ac-4048-b941-769eb511b91e].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:The Maya Legend of the Hero Twins [c70d460a-a3ac-4048-b941-769eb511b91e].mp4' -i 'file:The Maya Legend of the Hero Twins [c70d460a-a3ac-4048-b941-769eb511b91e].meta' -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -write_id3v1 1 -metadata 'title=The Maya Legend of the Hero Twins' -metadata date=20211011 -metadata 'description=Hosted by Cristela Alonzo, "Legends of the Hidden Temple" is taken out of a studio and into a "jungle," and scaled up with tougher challenges and a much bigger prize on the line.' -metadata 'synopsis=Hosted by Cristela Alonzo, "Legends of the Hidden Temple" is taken out of a studio and into a "jungle," and scaled up with tougher challenges and a much bigger prize on the line.' -metadata 'purl=https://www.cwtv.com/shows/legends-of-the-hidden-temple/the-maya-legend-of-the-hero-twins/?play=c70d460a-a3ac-4048-b941-769eb511b91e' -metadata 'comment=https://www.cwtv.com/shows/legends-of-the-hidden-temple/the-maya-legend-of-the-hero-twins/?play=c70d460a-a3ac-4048-b941-769eb511b91e' -metadata artist=CWTV -metadata 'show=Legends of The Hidden Temple' -metadata season_number=1 -metadata 'episode_id=Episode 1' -metadata episode_sort=1 -movflags +faststart 'file:The Maya Legend of the Hero Twins [c70d460a-a3ac-4048-b941-769eb511b91e].temp.mp4'
ERROR: Postprocessing: file:The Maya Legend of the Hero Twins [c70d460a-a3ac-4048-b941-769eb511b91e].meta: Cannot allocate memory
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3202, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3372, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3354, in run_all_pps
    info = self.run_pp(pp, info)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3333, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 126, in wrapper
    return func(self, info)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 691, in run
    self.run_ffmpeg_multiple_files(
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 313, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 350, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:The Maya Legend of the Hero Twins [c70d460a-a3ac-4048-b941-769eb511b91e].meta: Cannot allocate memory
```

**Comment by pukkandan** [comment]
Possibly similar issue as https://github.com/yt-dlp/yt-dlp/issues/520

**Comment by pukkandan** [comment]
I am unable to access the video over a VPN. Can you share the `.meta` file?

**Comment by ischmidt20** [comment]
```
;FFMETADATA1
[CHAPTER]
TIMEBASE=1/1000
START=0
END=614000
[CHAPTER]
TIMEBASE=1/1000
START=614000
END=992000
[CHAPTER]
TIMEBASE=1/1000
START=992000
END=1379000
[CHAPTER]
TIMEBASE=1/1000
START=1379000
END=1917000
[CHAPTER]
TIMEBASE=1/1000
START=1917000
END=2332000
[CHAPTER]
TIMEBASE=1/1000
START=2332000
END=0
```

**Comment by pukkandan** [comment]
ah, this is the issue!

> START=2332000
> END=0

Pls run `yt-dlp -vs --write-page "URL"` and attch the `.dump` files here along with it's log

**Comment by ischmidt20** [comment]
```
yt-dlp -vs --write-page 'https://www.cwtv.com/shows/legends-of-the-hidden-temple/the-maya-legend-of-the-hero-twins/?play=c70d460a-a3ac-4048-b941-769eb511b91e'
[debug] Command-line config: ['-vs', '--write-page', 'https://www.cwtv.com/shows/legends-of-the-hidden-temple/the-maya-legend-of-the-hero-twins/?play=c70d460a-a3ac-4048-b941-769eb511b91e']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e]
[debug] Python version 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [CWTV] Extracting URL: https://www.cwtv.com/shows/legends-of-the-hidden-temple/the-maya-legend-of-the-hero-twins/?play=c70d460a-a3ac-4048-b941-769eb511b91e
[CWTV] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading JSON metadata
[CWTV] Saving request to c70d460a-a3ac-4048-b941-769eb511b91e_http_-_images.cwtv.com_feed_mobileapp_video-meta_apiversion_8_guid_c70d460a-a3ac-4048-b941-769eb511b91e.dump
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/cwtv/media/guid/2703454149/c70d460a-a3ac-4048-b941-769eb511b91e?format=SMIL&formats=M3U&tracking=true&mbr=false#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading SMIL data
[ThePlatform] Saving request to c70d460a-a3ac-4048-b941-769eb511b91e_http_-_link.theplatform.com_s_cwtv_media_guid_2703454149_c70d460a-a3ac-4048-b941-769eb511b91eformat=SMIL_formats=M3U_tracking=true_mbr=false.dump
[ThePlatform] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading m3u8 information
[ThePlatform] Saving request to c70d460a-a3ac-4048-b941-769eb511b91e_https_-_3aa37dc0e8bb47e08042e0ebb25acb34.dlvr1.net_nosec_The_CW_613_717_123049029948_LegendsOfTheHiddenTemple-101-HeroTwins-P1005-CW.m3u8.dump
WARNING: [ThePlatform] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ThePlatform] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading m3u8 information
[ThePlatform] Saving request to c70d460a-a3ac-4048-b941-769eb511b91e_https_-_stream-hls.cwtv.com_nosec_The_CW_613_717_123049029948_LegendsOfTheHiddenTemple-101-HeroTwins-P1005-CW.m3u8.dump
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading JSON metadata
[ThePlatform] Saving request to c70d460a-a3ac-4048-b941-769eb511b91e_http_-_link.theplatform.com_s_cwtv_media_guid_2703454149_c70d460a-a3ac-4048-b941-769eb511b91eformat=preview.dump
[debug] Default format spec: bestvideo*+bestaudio/best
[info] c70d460a-a3ac-4048-b941-769eb511b91e: Downloading 1 format(s): hls-8328-3
```
[c70d460a-a3ac-4048-b941-769eb511b91e_http_-_images.cwtv.com_feed_mobileapp_video-meta_apiversion_8_guid_c70d460a-a3ac-4048-b941-769eb511b91e.dump.txt](https://github.com/yt-dlp/yt-dlp/files/8985683/c70d460a-a3ac-4048-b941-769eb511b91e_http_-_images.cwtv.com_feed_mobileapp_video-meta_apiversion_8_guid_c70d460a-a3ac-4048-b941-769eb511b91e.dump.txt)
[c70d460a-a3ac-4048-b941-769eb511b91e_http_-_link.theplatform.com_s_cwtv_media_guid_2703454149_c70d460a-a3ac-4048-b941-769eb511b91eformat=preview.dump.txt](https://github.com/yt-dlp/yt-dlp/files/8985684/c70d460a-a3ac-4048-b941-769eb511b91e_http_-_link.theplatform.com_s_cwtv_media_guid_2703454149_c70d460a-a3ac-4048-b941-769eb511b91eformat.preview.dump.txt)
[c70d460a-a3ac-4048-b941-769eb511b91e_http_-_link.theplatform.com_s_cwtv_media_guid_2703454149_c70d460a-a3ac-4048-b941-769eb511b91eformat=SMIL_formats=M3U_tracking=true_mbr=false.dump.txt](https://github.com/yt-dlp/yt-dlp/files/8985685/c70d460a-a3ac-4048-b941-769eb511b91e_http_-_link.theplatform.com_s_cwtv_media_guid_2703454149_c70d460a-a3ac-4048-b941-769eb511b91eformat.SMIL_formats.M3U_tracking.true_mbr.false.dump.txt)
[c70d460a-a3ac-4048-b941-769eb511b91e_https_-_3aa37dc0e8bb47e08042e0ebb25acb34.dlvr1.net_nosec_The_CW_613_717_123049029948_LegendsOfTheHiddenTemple-101-HeroTwins-P1005-CW.m3u8.dump.txt](https://github.com/yt-dlp/yt-dlp/files/8985686/c70d460a-a3ac-4048-b941-769eb511b91e_https_-_3aa37dc0e8bb47e08042e0ebb25acb34.dlvr1.net_nosec_The_CW_613_717_123049029948_LegendsOfTheHiddenTemple-101-HeroTwins-P1005-CW.m3u8.dump.txt)
[c70d460a-a3ac-4048-b941-769eb511b91e_https_-_stream-hls.cwtv.com_nosec_The_CW_613_717_123049029948_LegendsOfTheHiddenTemple-101-HeroTwins-P1005-CW.m3u8.dump.txt](https://github.com/yt-dlp/yt-dlp/files/8985687/c70d460a-a3ac-4048-b941-769eb511b91e_https_-_stream-hls.cwtv.com_nosec_The_CW_613_717_123049029948_LegendsOfTheHiddenTemple-101-HeroTwins-P1005-CW.m3u8.dump.txt)

**Comment by ischmidt20** [comment]
Thanks for the quick turnaround! I will pull the master branch and check to confirm now

**Comment by ischmidt20** [comment]
Yup, that worked, thanks again!
