### ISSUE TITLE
_extract_m3u8_formats improperly handles #EXT-X-MEDIA if it's also in m3u8?

### ISSUE THREAD

**Issue by MinePlayersPE** [yt-dlp/yt-dlp#421]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.06.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

Parsed directly to yt-dlp:
```
yt-dlp -v https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8
[debug] Command-line config: ['-v', 'https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.09 (exe)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-06-09-git-e01bf559df-full_build-www.gyan.dev, ffprobe 2021-06-09-git-e01bf559df-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8
[generic] upin_ipin_anevia_s01e01: Requesting header
[generic] upin_ipin_anevia_s01e01: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] upin_ipin_anevia_s01e01: Downloading 1 format(s): 2184+audio-AACL-64-English
[debug] Invoking downloader on "https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01-avc1_2000000=2.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 151
[download] Destination: upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].f2184.mp4
[download] 100% of 70.50MiB in 00:48
[debug] Invoking downloader on "https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01-mp4a_64000_eng=1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 151
[download] Destination: upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].faudio-AACL-64-English.mp4
[download] 100% of 4.84MiB in 00:16
[Merger] Merging formats into "upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].f2184.mp4" -i "file:upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].faudio-AACL-64-English.mp4" -c copy -map "0:v:0" -map "1:a:0" "file:upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].temp.mp4"
Deleting original file upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].f2184.mp4 (pass -k to keep)
Deleting original file upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].faudio-AACL-64-English.mp4 (pass -k to keep)
[debug] ffmpeg command line: ffprobe -show_streams "file:upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].mp4"
[FixupM3u8] Fixing malformed AAC bitstream in "upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:upin_ipin_anevia_s01e01 [upin_ipin_anevia_s01e01].temp.mp4"
```
Parsed from _extract_m3u8_formats:
```
yt-dlp -v sampleplugin:https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8
[debug] Command-line config: ['-v', 'sampleplugin:https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.09 (exe)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-06-09-git-e01bf559df-full_build-www.gyan.dev, ffprobe 2021-06-09-git-e01bf559df-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [SamplePlugin] Extracting URL: sampleplugin:https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8
[SamplePlugin] https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8: Downloading 1 format(s): 2184+audio-AACL-64-English
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on "https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01-avc1_2000000=2.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 151
[download] Destination: https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8 [https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8].f2184.mp4
[download] 100% of 70.50MiB in 00:48
[debug] Invoking downloader on "https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01-mp4a_64000_eng=1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 151
[download] Destination: https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8 [https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8].faudio-AACL-64-English.m3u8
[download] 100% of 4.84MiB in 00:16
[Merger] Merging formats into "https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8 [https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8 [https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8].f2184.mp4" -i "file:https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8 [https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8].faudio-AACL-64-English.m3u8" -c copy -map "0:v:0" -map "1:a:0" "file:https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8 [https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8].temp.mkv"
ERROR: ffmpeg version 2021-06-09-git-e01bf559df-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  1.101 / 59.  1.101
  libavformat    59.  2.102 / 59.  2.102
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.101 /  8.  0.101
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, mpegts, from 'file:https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8 [https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8].f2184.mp4':
  Duration: 00:05:01.00, start: 1.000000, bitrate: 1964 kb/s
  Program 16727
  Stream #0:0[0x21]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg, progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
Input #1, mpegts, from 'file:https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8 [https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8].faudio-AACL-64-English.m3u8':
  Duration: 00:05:00.91, start: 1.021333, bitrate: 135 kb/s
  Program 16727
  Stream #1:0[0x22](eng): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 63 kb/s
Output #0, matroska, to 'file:https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8 [https -_vcdn.rctiplus.id_vod_eds_upin_ipin_anevia_s01e01_sa_hls_upin_ipin_anevia_s01e01.m3u8].temp.mkv':
  Metadata:
    encoder         : Lavf59.2.102
  Stream #0:0: Video: h264 (High) (H264 / 0x34363248), yuv420p(tv, bt470bg, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn
  Stream #0:1(eng): Audio: aac (LC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp, 63 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska @ 000001b9908f9900] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 000001b9908f9900] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
frame=    2 fps=0.0 q=-1.0 Lsize=      20kB time=00:00:00.02 bitrate=7688.4kbits/s speed=27.1x
video:33kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 706, in main
  File "yt_dlp\__init__.py", line 696, in _real_main
  File "yt_dlp\YoutubeDL.py", line 2751, in download
  File "yt_dlp\YoutubeDL.py", line 1126, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1133, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1165, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1202, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2171, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2721, in process_info
  File "yt_dlp\YoutubeDL.py", line 2861, in post_process
  File "yt_dlp\YoutubeDL.py", line 2810, in run_pp
  File "yt_dlp\postprocessor\ffmpeg.py", line 638, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 237, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 273, in real_run_ffmpeg
  File "yt_dlp\postprocessor\common.py", line 55, in report_error
  File "yt_dlp\YoutubeDL.py", line 776, in report_error
  File "yt_dlp\YoutubeDL.py", line 732, in trouble

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2721, in process_info
  File "yt_dlp\YoutubeDL.py", line 2861, in post_process
  File "yt_dlp\YoutubeDL.py", line 2810, in run_pp
  File "yt_dlp\postprocessor\ffmpeg.py", line 638, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 237, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 274, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

## Description

_extract_m3u8_formats seems to improperly handles audio formats (#EXT-X-MEDIA) which in and of itself is an m3u8 format (not sure how to explain it better) and returns the m3u8 file instead of the actual mp4 media.
Sample (janky) test plugin:
```py
# coding: utf-8

from __future__ import unicode_literals
import re

# ⚠ Don't use relative imports
from yt_dlp.extractor.common import InfoExtractor


# ℹ️ Instructions on making extractors can be found at:
# 🔗 https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site

class SamplePluginIE(InfoExtractor):
    _WORKING = True
    IE_DESC = False
    _VALID_URL = r'^sampleplugin:(?P<m3u8>.+)'

    def _real_extract(self, url):
        m3u8_link = re.match(self._VALID_URL, url).groups()[0]
        formats = self._extract_m3u8_formats(m3u8_link, m3u8_link)
        self._sort_formats(formats)
        return {'formats': formats, 'id': m3u8_link, 'title': m3u8_link}
```
-F test:
```
yt-dlp -F sampleplugin:https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8
[SamplePlugin] https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8: Downloading m3u8 information
[info] Available formats for https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8:
ID                    EXT  RESOLUTION FPS |   TBR PROTO  | VCODEC        VBR ACODEC  NOTE
--------------------- ---- ---------- --- - ----- ------ - ----------- ----- ------- ----
audio-AACL-64-English m3u8 audio only     |       m3u8_n |                   unknown [en]
382                   mp4  320x180    25  |  382k m3u8_n | avc1.64000c  382k
700                   mp4  480x270    25  |  700k m3u8_n | avc1.640015  700k
1124                  mp4  960x540    25  | 1124k m3u8_n | avc1.64001f 1124k
2184                  mp4  1280x720   25  | 2184k m3u8_n | avc1.64001f 2184k
```
```
yt-dlp -F https://vcdn.rctiplus.id/vod/eds/upin_ipin_anevia_s01e01/_/sa_hls/upin_ipin_anevia_s01e01.m3u8
[generic] upin_ipin_anevia_s01e01: Requesting header
[generic] upin_ipin_anevia_s01e01: Downloading m3u8 information
[info] Available formats for upin_ipin_anevia_s01e01:
ID                    EXT RESOLUTION FPS |   TBR PROTO  | VCODEC        VBR ACODEC  NOTE
--------------------- --- ---------- --- - ----- ------ - ----------- ----- ------- ----
audio-AACL-64-English mp4 audio only     |       m3u8_n |                   unknown [en]
382                   mp4 320x180    25  |  382k m3u8_n | avc1.64000c  382k
700                   mp4 480x270    25  |  700k m3u8_n | avc1.640015  700k
1124                  mp4 960x540    25  | 1124k m3u8_n | avc1.64001f 1124k
2184                  mp4 1280x720   25  | 2184k m3u8_n | avc1.64001f 2184k
```

**Comment by pukkandan** [comment]
I don't quite understand the issue and cannot access the example URL you have given. Do you mean that:
1. The audio is downloaded correctly, but has the extension `m3u8` OR
2. An actual m3u8 file is being downloaded instead of the audio.

For (1), you just need to pass the correct ext to the parse function
If it is (2), could you attach both the master and downloaded m3u8 files so that I can investigate

**Comment by pukkandan** [comment]
> [download] 100% of 4.84MiB in 00:16

actually, on a more thorough inspection of the log, it does seem the issue is case 1

**Comment by MinePlayersPE** [comment]
> For (1), you just need to pass the correct ext to the parse function

Thanks, I'm dumb
