### ISSUE TITLE
Using   --external-downloader aria2c --external-downloader-args has issues...it's looking for a password which isn't needed

### ISSUE THREAD

**Issue by stillpointx** [yt-dlp/yt-dlp#4215]
### Checklist

- [] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Using   --external-downloader aria2c --external-downloader-args has issues...it's looking for a password which isn't needed but it wants a user to hit the **RETURN** key  

**Note:  No login or password is needed with the url.**

I used the command sequence below which fails **(but it use to work)**

yt-dlp -f 'bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio' --merge-output-format mp4 --output "%(title)s_%(resolution)s.%(ext)s" --external-downloader aria2c --external-downloader-args '-d ./ -x 10' https://www.youtube.com/watch?v=gshStnuK1vA

**Errors below:**

```

rt@sty: /tmp/0/tesla turbine$ yt-dlp -f 'bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio' --merge-output-format mp4 --output "%(title)s_%(resolution)s.%(ext)s" --external-downloader aria2c --external-downloader-args '-d ./ -x 10' https://www.youtube.com/watch?v=gshStnuK1vA
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 2205, in build_format_selector
    tokens = list(_remove_unused_ops(tokenize.tokenize(stream.readline)))
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1939, in _remove_unused_ops
    for type, string, start, end, line in tokens:
  File "/usr/lib/python3.8/tokenize.py", line 521, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (2, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/__init__.py", line 919, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/__init__.py", line 881, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 684, in __init__
    else self.build_format_selector(self.params['format']))
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 2207, in build_format_selector
    raise syntax_error('Missing closing/opening brackets or parenthesis', (0, len(format_spec)))
SyntaxError: Invalid format specification: Missing closing/opening brackets or parenthesis
	bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio
	                                                                              ^
```

**When I use the debug version it works but found out why it's failing for some strange reason it wants a password....**
**Note:  No login or password is needed with the url.**

```

yt-dlp -vuf 'bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio' --merge-output-format mp4 --output "%(title)s_%(resolution)s.%(ext)s" --external-downloader aria2c --external-downloader-args '-d ./ -x 10' https://www.youtube.com/watch?v=gshStnuK1vA

[debug] Command-line config: ['-vuf', 'bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio', '--merge-output-format', 'mp4', '--output', '%(title)s_%(resolution)s.%(ext)s', '--external-downloader', 'aria2c', '--external-downloader-args', '-d ./ -x 10', 'https://www.youtube.com/watch?v=gshStnuK1vA']
**Type account password and press [Return]:** 

WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-51-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [generic] Extracting URL: bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio

**ERROR**: [generic] 'bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio" ) to search YouTube
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/generic.py", line 2796, in _real_extract
    raise ExtractorError(

WARNING: [youtube] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl  for how to manually pass cookies

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=gshStnuK1vA
[youtube] gshStnuK1vA: Downloading webpage
[youtube] gshStnuK1vA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] gshStnuK1vA: Downloading 1 format(s): 248+251
[debug] Invoking aria2c downloader on "https://rr4---sn-hp57ynlr.googlevideo.com/videoplayback?expire=1656447237&ei=pQy7YtCUI_-n0_wP2v6pgAQ&ip=107.77.216.108&id=o-AMiO5y7oT8TEg7XT-SK1b79dE2LooGbeLyRiuFjHh1cO&itag=248&source=youtube&requiressl=yes&mh=0d&mm=31%2C29&mn=sn-hp57ynlr%2Csn-hp57kn6y&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=356250&vprv=1&mime=video%2Fwebm&gir=yes&clen=156649056&dur=665.122&lmt=1606909458529461&mt=1656425354&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANCWdnHSpZ8vqrvslU0LRkC6EQEdcuDWvWwopJ5QxSYBAiEA6PE0g6uXs5pscec4_VvdfcdMUgaQf_mdqmS3QCrElsM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANVJAZk3bF7oeaLr3KJo4o_xW1PLlh2gDvoL1Kjrb4VhAiA2-RqOFKLCceSOeOyWORXc20T29yomLCakBg_5Yq9Dqg%3D%3D"
[download] Destination: Tesla Turbine As An Air Pump In A Gasifier_1920x1080.f248.webm
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --http-accept-gzip=true --file-allocation=none -x16 -j16 -s16 --min-split-size 1M --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-us,en;q=0.5' --header 'Sec-Fetch-Mode: navigate' --check-certificate=true --remote-time=true --show-console-readout=true -d ./ -x 10 --out './Tesla Turbine As An Air Pump In A Gasifier_1920x1080.f248.webm.part' --auto-file-renaming=false -- 'https://rr4---sn-hp57ynlr.googlevideo.com/videoplayback?expire=1656447237&ei=pQy7YtCUI_-n0_wP2v6pgAQ&ip=107.77.216.108&id=o-AMiO5y7oT8TEg7XT-SK1b79dE2LooGbeLyRiuFjHh1cO&itag=248&source=youtube&requiressl=yes&mh=0d&mm=31%2C29&mn=sn-hp57ynlr%2Csn-hp57kn6y&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=356250&vprv=1&mime=video%2Fwebm&gir=yes&clen=156649056&dur=665.122&lmt=1606909458529461&mt=1656425354&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANCWdnHSpZ8vqrvslU0LRkC6EQEdcuDWvWwopJ5QxSYBAiEA6PE0g6uXs5pscec4_VvdfcdMUgaQf_mdqmS3QCrElsM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANVJAZk3bF7oeaLr3KJo4o_xW1PLlh2gDvoL1Kjrb4VhAiA2-RqOFKLCceSOeOyWORXc20T29yomLCakBg_5Yq9Dqg%3D%3D'


```

### Verbose log

```shell
[debug] Command-line config: ['-vuf', 'bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio', '--merge-output-format', 'mp4', '--output', '%(title)s_%(resolution)s.%(ext)s', '--external-downloader', 'aria2c', '--external-downloader-args', '-d ./ -x 10', 'https://www.youtube.com/watch?v=gshStnuK1vA']
**Type account password and press [Return]:** 

WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-51-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [generic] Extracting URL: bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio

**ERROR**: [generic] 'bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480/bestvideo+bestaudio" ) to search YouTube
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/generic.py", line 2796, in _real_extract
    raise ExtractorError(

WARNING: [youtube] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl  for how to manually pass cookies

[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=gshStnuK1vA
[youtube] gshStnuK1vA: Downloading webpage
[youtube] gshStnuK1vA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] gshStnuK1vA: Downloading 1 format(s): 248+251
[debug] Invoking aria2c downloader on "https://rr4---sn-hp57ynlr.googlevideo.com/videoplayback?expire=1656447237&ei=pQy7YtCUI_-n0_wP2v6pgAQ&ip=107.77.216.108&id=o-AMiO5y7oT8TEg7XT-SK1b79dE2LooGbeLyRiuFjHh1cO&itag=248&source=youtube&requiressl=yes&mh=0d&mm=31%2C29&mn=sn-hp57ynlr%2Csn-hp57kn6y&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=356250&vprv=1&mime=video%2Fwebm&gir=yes&clen=156649056&dur=665.122&lmt=1606909458529461&mt=1656425354&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANCWdnHSpZ8vqrvslU0LRkC6EQEdcuDWvWwopJ5QxSYBAiEA6PE0g6uXs5pscec4_VvdfcdMUgaQf_mdqmS3QCrElsM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANVJAZk3bF7oeaLr3KJo4o_xW1PLlh2gDvoL1Kjrb4VhAiA2-RqOFKLCceSOeOyWORXc20T29yomLCakBg_5Yq9Dqg%3D%3D"
[download] Destination: Tesla Turbine As An Air Pump In A Gasifier_1920x1080.f248.webm
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --http-accept-gzip=true --file-allocation=none -x16 -j16 -s16 --min-split-size 1M --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-us,en;q=0.5' --header 'Sec-Fetch-Mode: navigate' --check-certificate=true --remote-time=true --show-console-readout=true -d ./ -x 10 --out './Tesla Turbine As An Air Pump In A Gasifier_1920x1080.f248.webm.part' --auto-file-renaming=false -- 'https://rr4---sn-hp57ynlr.googlevideo.com/videoplayback?expire=1656447237&ei=pQy7YtCUI_-n0_wP2v6pgAQ&ip=107.77.216.108&id=o-AMiO5y7oT8TEg7XT-SK1b79dE2LooGbeLyRiuFjHh1cO&itag=248&source=youtube&requiressl=yes&mh=0d&mm=31%2C29&mn=sn-hp57ynlr%2Csn-hp57kn6y&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=356250&vprv=1&mime=video%2Fwebm&gir=yes&clen=156649056&dur=665.122&lmt=1606909458529461&mt=1656425354&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANCWdnHSpZ8vqrvslU0LRkC6EQEdcuDWvWwopJ5QxSYBAiEA6PE0g6uXs5pscec4_VvdfcdMUgaQf_mdqmS3QCrElsM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANVJAZk3bF7oeaLr3KJo4o_xW1PLlh2gDvoL1Kjrb4VhAiA2-RqOFKLCceSOeOyWORXc20T29yomLCakBg_5Yq9Dqg%3D%3D'
```

**Comment by Lesmiscore** [comment]
1. You are missing `]` after `height<=480`. `bestvideo[height<=480]+bestaudio[ext=m4a]/best[height<=480]/bestvideo+bestaudio`
2. Options are case-sensitive. `-u` stands for `--username`, so you're setting username `f`. use `-vU -f`

**Comment by stillpointx** [comment]
Thanks, one little thing...
