### ISSUE TITLE
match-filter & not working after 2022.05

### ISSUE THREAD

**Issue by chapmanjacobd** [yt-dlp/yt-dlp#4263]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

```
pip install yt-dlp==2022.05.18
```

This works on version 05.18

```
yt-dlp --match-filter  '59 < duration & duration < 10800' $url
```

but it fails on 06.22, 06.22.1, and 06.29

```
ERROR: Invalid filter part '59 < duration '
```

with `yt-dlp --match-filter  '59 < duration \& duration < 10800' $url` (this is probably incorrect syntax)

```
ERROR: Invalid filter part '59 < duration & duration < 10800'
```

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'firefox', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0', '-i', '-o', '%(uploader)s/%(title).200B [%(id)s].%(ext)s', '--restrict-filenames', '--download-archive', '/home/xk/.local/share/yt_archive.txt', '--retries', '13', '--extractor-retries', '13', '--match-filter', '59 < duration & duration < 10800', '--extractor-args', 'youtubetab:skip=authcheck', '--reject-title', 'Trailer |Sneak Peek| Preview | Teaser | Promo | Live Stream | Twitch | Crypto | Meetup | Montage | Bitcoin | Makeup | Apology |Clip|Top 10|Top Ten| Panel ', '--youtube-skip-dash-manifest', '--youtube-skip-hls-manifest', '-f', 'bestaudio[ext=webm]/bestaudio/best', '-v', 'https://www.youtube.com/watch?v=f-VBpZ2XvEs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.17.12-300.fc36.x86_64-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/xk/.mozilla/firefox/lka4ht7r.xxx/cookies.sqlite"
[Cookies] Extracted 1331 cookies from firefox
[debug] Proxy map: {}
[debug] Loading archive file '/home/xk/.local/share/yt_archive.txt'
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=f-VBpZ2XvEs
[youtube] f-VBpZ2XvEs: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] f-VBpZ2XvEs: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: Invalid filter part '59 < duration '
Traceback (most recent call last):
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1504, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1561, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2535, in process_video_result
    if self._match_entry(info_dict, incomplete=self._format_fields) is not None:
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1354, in _match_entry
    reason = check_filter()
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1333, in check_filter
    ret = match_filter(info_dict, incomplete=incomplete)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 3655, in _match_func
    if not filters or any(match_str(f, info_dict, incomplete) for f in filters):
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 3655, in <genexpr>
    if not filters or any(match_str(f, info_dict, incomplete) for f in filters):
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 3640, in match_str
    return all(
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 3641, in <genexpr>
    _match_one(filter_part.replace(r'\&', '&'), dct, incomplete)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 3630, in _match_one
    raise ValueError('Invalid filter part %r' % filter_part)
ValueError: Invalid filter part '59 < duration '
```

**Comment by Lesmiscore** [comment]
The field name (`duration` in this case) must go to LHS for `--match-filter`.
`59 < duration` doesn't makes sense, as it is interpreted to compare field `59` (not number!) and the number `duration`.
The correct string is `duration > 59 & duration < 10800` on whatever version, just the checks are more stricter.

See https://github.com/yt-dlp/yt-dlp#filtering-formats

**Comment by chapmanjacobd** [comment]
thanks. I'll update the documentation
