### ISSUE TITLE
Errors on [adult swim]

### ISSUE THREAD

**Issue by I-Go-By-Em** [yt-dlp/yt-dlp#4295]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Hey now,

I've been having trouble accessing [adultswim] with SVPTube. The SVP devs suggested I try plain yt-dlp, and after downloading the latest version, it produced the same error. Plain YouTube still works fine, so I'd think it's something with [as]. Below is my verbose output when trying to access a free episode of Black Jesus.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.adultswim.com/videos/black-jesus/tasty-tudis']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [AdultSwim] Extracting URL: https://www.adultswim.com/videos/black-jesus/tasty-tudis
[AdultSwim] tasty-tudis: Downloading JSON metadata
[AdultSwim] c9c6408ca2e8d17435d8bde0309c97ce972ac2a6: Downloading JSON metadata
[AdultSwim] c9c6408ca2e8d17435d8bde0309c97ce972ac2a6: Downloading XML
[AdultSwim] c9c6408ca2e8d17435d8bde0309c97ce972ac2a6: Downloading m3u8 information
WARNING: [AdultSwim] Failed to download m3u8 information: <urlopen error [Errno 11001] getaddrinfo failed>
[AdultSwim] 292LqJ1IRZ21jtEDXgmLWw: Downloading JSON metadata
[AdultSwim] 292LqJ1IRZ21jtEDXgmLWw: Downloading m3u8 information
WARNING: [AdultSwim] Failed to download m3u8 information: <urlopen error [Errno 11001] getaddrinfo failed>
ERROR: [AdultSwim] 292LqJ1IRZ21jtEDXgmLWw: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1420, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1504, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1561, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2450, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 993, in raise_no_formats
yt_dlp.utils.ExtractorError: [AdultSwim] 292LqJ1IRZ21jtEDXgmLWw: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by I-Go-By-Em** [comment]
Nevermind I found the issue -- this was caused by an unrelated issue with my DNS resolving being a little slow. Haven't tested it with the MSOs, but I'll open another issue if I need more help :)
