### ISSUE TITLE
[youtube] Issue fetching the list of playlist IDs for a channel

### ISSUE THREAD

**Issue by za3k** [yt-dlp/yt-dlp#4301]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I'm fetching the playlist IDs for a channel. It works great much of the time. Here's a faillure case.

    yt-dlp --flat-playlist --print id "https://www.youtube.com/c/NikAndIsaac/playlists"

The output is

    WARNING: [youtube:tab] Incomplete data received. Retrying ...
    WARNING: [youtube:tab] Incomplete data received. Retrying ...
    WARNING: [youtube:tab] Incomplete data received. Retrying ...
    ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
    PLH6M8ugywDvj0DhgvjlJLqwUebWkM_oS2
    PLH6M8ugywDvgF3w6KtCYcAoprM7z2kNTb
    [...]
    PLH6M8ugywDvhZZrx-6Tr2NCafL2n1dyr9

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--flat-playlist', '--print', 'id', '-vU', 'https://www.youtube.com/c/NikAndIsaac/playlists']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.06.29 [9d339c4]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.7-arch1-1-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, phantomjs 18, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.06.15, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/c/NikAndIsaac/playlists
[youtube:tab] NikAndIsaac: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/c/NikAndIsaac/playlists
[download] Downloading playlist: Nik & Isaac - Playlists
[youtube:tab] UCpeVmd1LUaVtak-l-DAoL0A page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] UCpeVmd1LUaVtak-l-DAoL0A page 1: Downloading API JSON (retry #1)
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] UCpeVmd1LUaVtak-l-DAoL0A page 1: Downloading API JSON (retry #2)
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] UCpeVmd1LUaVtak-l-DAoL0A page 1: Downloading API JSON (retry #3)
ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2917, in <lambda>
    return type(self.ydl)._handle_extraction_exceptions(lambda _, i: self._entries[i])(self.ydl, i)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2687, in __getitem__
    self._cache.extend(itertools.islice(self._iterable, n))
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 4157, in _entries
    response = self._extract_response(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 828, in _extract_response
    raise ExtractorError(last_error)
yt_dlp.utils.ExtractorError: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[youtube:tab] Playlist Nik & Isaac - Playlists: Downloading 27 videos of 26
[download] Downloading video 1 of 27
PLH6M8ugywDvj0DhgvjlJLqwUebWkM_oS2
[download] Downloading video 2 of 27
PLH6M8ugywDvgF3w6KtCYcAoprM7z2kNTb
[download] Downloading video 3 of 27
PLH6M8ugywDvisnfteZneDoOxwJbv6RILa
[download] Downloading video 4 of 27
PLH6M8ugywDvjxoEiEjnUN7nsySa0ZiNJM
[download] Downloading video 5 of 27
PLH6M8ugywDvjVRqmEnPDbFAQLJQstdX9K
[download] Downloading video 6 of 27
PLH6M8ugywDvhIlO4SlB9bmRDdBfVS7MqS
[download] Downloading video 7 of 27
PLH6M8ugywDvjmzul0cznZwZi2BEQ2cmi5
[download] Downloading video 8 of 27
PLH6M8ugywDvjpWxdgAiK6ux_iDYbq7fst
[download] Downloading video 9 of 27
PLH6M8ugywDvgaah7EFsjBio2skKi2ARf-
[download] Downloading video 10 of 27
PLH6M8ugywDviwr8qMVbkUc89dNsu0waKL
[download] Downloading video 11 of 27
PLH6M8ugywDvg2IHF6uH6bFq0FZphI-LwW
[download] Downloading video 12 of 27
PLH6M8ugywDvgzN50SarxmLXMDEu7Y8hAZ
[download] Downloading video 13 of 27
PLH6M8ugywDvjsaY-LyCL5DYCYp4AmZnGx
[download] Downloading video 14 of 27
PLH6M8ugywDvh9ctP2YOYk3UmPwAvZ-MRl
[download] Downloading video 15 of 27
PLH6M8ugywDvhNLmyeXCcuIaLYzanjo-3f
[download] Downloading video 16 of 27
PLH6M8ugywDviKv9SIoXQPyAaGZFvRzrum
[download] Downloading video 17 of 27
PLH6M8ugywDvjjL4nwzTnH-rfeKTxqCxaY
[download] Downloading video 18 of 27
PLH6M8ugywDvgczBIg4-4LOjXzwgw6OuOJ
[download] Downloading video 19 of 27
PLH6M8ugywDvj2aY-Yh13dzQwLcroA509H
[download] Downloading video 20 of 27
PLH6M8ugywDvjoe1eS2O4PNPRPz1RhPlPP
[download] Downloading video 21 of 27
PLH6M8ugywDvh-GzyOfAgMDsyKTguvjfNH
[download] Downloading video 22 of 27
PLH6M8ugywDviBh0FQa_-EdmlvB-3yhE5u
[download] Downloading video 23 of 27
PLH6M8ugywDviyi9atMgWUipW_jnCv6Iph
[download] Downloading video 24 of 27
PLH6M8ugywDvhGF70P6TEvYtQ8ugSX11sx
[download] Downloading video 25 of 27
PLH6M8ugywDvhWzvAaGHSfqacBMLhVC2HR
[download] Downloading video 26 of 27
PLH6M8ugywDvhZZrx-6Tr2NCafL2n1dyr9
[download] Finished downloading playlist: Nik & Isaac - Playlists
```

**Comment by za3k** [comment]
When I visit the page I see 26 playlists (not 27) and a loading icon at the bottom. I think this is actually a youtube issue. Closing.

**Comment by coletdjnz** [comment]
Yeah it's a youtube issue, hopefully temporary.
