### ISSUE TITLE
[CueTV] Add support for cuetv.online

### ISSUE THREAD

**Issue by Offert4324** [yt-dlp/yt-dlp#4306]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

 - Single video: https://www.cuetv.online/opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006/videos/opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006

### Provide a description that is worded well enough to be understood

yt-dlp can't download any type of video from the website.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', 'bestvideo+bestaudio/best', '--write-sub', '--sub-langs', 'all', '--cookies=cuetv.online_cookies.txt', 'https://www.cuetv.online/opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006/videos/opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006', '-vU']
[debug] Encodings: locale cp949, fs utf-8, pref cp949, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4]
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://www.cuetv.online/opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006/videos/opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006
[generic] opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006: Downloading webpage
[generic] opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.cuetv.online/opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006/videos/opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006
Traceback (most recent call last):
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1490, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 4130, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.cuetv.online/opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006/videos/opera-ariadne-auf-naxos-r-strauss-opernhaus-zurich-2006
```

**Comment by doe1080** [comment]
[CueTV](https://cuetv.online) has been integrated into [STAGE+](https://www.stage-plus.com) and is already supported
Related https://github.com/yt-dlp/yt-dlp/pull/6838 https://github.com/yt-dlp/yt-dlp/issues/3608
