### ISSUE TITLE
[BBC] Error: JSON object must be str, bytes or bytearray, not dict

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4313]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Provide a description that is worded well enough to be understood

ERROR: the JSON object must be str, bytes or bytearray, not dict

Guess the structure of the response changed or something. 
Video is located at this link:
https://vod-dash-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_sd/0b8189-p065hw19/vf_p065hw19_48490131-03e6-4f47-8a06-6e90f10bfe2c.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1657378563_1d46032da1fe3a0a011f341958d191b5

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -F "https://www.bbc.co.uk/teach/school-radio/assemblies-the-good-samaritan-modern-setting-ks2/zjsx2v4"
[debug] Command-line config: ['-vU', '-F', 'https://www.bbc.co.uk/teach/school-radio/assemblies-the-good-samaritan-modern-setting-ks2/zjsx2v4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [bbc] Extracting URL: https://www.bbc.co.uk/teach/school-radio/assemblies-the-good-samaritan-modern-setting-ks2/zjsx2v4
[bbc] zjsx2v4: Downloading webpage
ERROR: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1425, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1495, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/bbc.py", line 1189, in _real_extract
    initial_data = self._parse_json(initial_data, playlist_id, fatal=False)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 942, in _parse_json
    return json.loads(
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

**Comment by dirkf** [comment]
The extractor fails when looking for an assignment to `__INITIAL_DATA__` but these pages have the Morph structure, where the needed hydration data is the second parameter of one of several calls to `Morph.setPayload()`. In this case, the first parameter is `/data/bbc-morph-blocks-data/preview/false/projectName/blocks-school-radio/timestamp/0/version/2.95.0/zid/zm3ptrd` where `zm3ptrd` is the `id` of the `<div>` that contains the video. The second is this (prettified):
```json
{
  'meta': {
    'responseCode': 200,
    'errorMessage': null,
    'headers': {
      'content-type': 'application/json'
    }
  },
  'body': {
    'type': 'video-block',
    'id': 'zm3ptrd',
    'title': '',
    'caption': '',
    'pid': 'p065hw17',
    'transcript': '',
    'video': {
      'title': 'The Good Samaritan',
      'holdingImage': 'https://ichef.bbci.co.uk/images/ic/$recipe/p065hxv2.jpg',
      'duration': 'PT5M22S',
      'vpid': 'p065hw19',
      'guidance': null,
      'mediaType': 'video',
      'aspectRatio': '16:9'
    }
  }
});
}
```
And then the PID will lead you to the desired content from  https://www.bbc.co.uk/programmes/p065hw17.

**Comment by dirkf** [comment]
In https://github.com/ytdl-org/youtube-dl/pull/28577, the extractor looked for just `asset-data`, `page-component-data`, `asset-with-media` or `guide-data` in the first parameter. Probably we should parse all the payloads and extract media from any that have known structures. In this case we have `payload['body']['type'] == 'video-block` which may be a hint, but unfortunately also produces other matches (`p08r2q32`, `p07q3hln`, `p09cydh5`). OTOH the page does appear to have 4 video blocks.

One issue that stymied the PR was the deficient semantics of `--no/yes-playlist`, whereby it was impossible to make the extractor target the main video by default, with `--yes-playlist` targeting all the page videos as a playlist, because `ydl.params['no_playlist']` is truthy/falsy and the extractor can't tell whether the user said `--yes-playlist` or just didn't say `--no-playlist`. It would be easy to  the semantics of `--no/yes-playlist` like this, with a three valued logic for `ydl.params['no_playlist']`:
* no `--x-playlist`, or `--yes-playlist ... --no-playlist`: `ydl.params['no_playlist'] is None`
* `--yes-playlist`: `ydl.params['no_playlist'] is False`
* `--no-playlist` otherwise: `ydl.params['no_playlist'] is True`

There was a concern that people may be testing `if ydl.params['no_playlist'] is not None:` instead of just `if ydl.params['no_playlist']:` and would get the wrong value in case 3. I would say they might deserve to.

**Comment by someziggyman** [comment]
Here's another test link with the same error message:
https://www.bbc.com/reel/embed/p08bl6tl
Log:
./yt-dlp -vU -F "https://www.bbc.com/reel/embed/p08bl6tl"
[debug] Command-line config: ['-vU', '-F', 'https://www.bbc.com/reel/embed/p08bl6tl']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [55937202b] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.5-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [bbc] Extracting URL: https://www.bbc.com/reel/embed/p08bl6tl
[bbc] p08bl6tl: Downloading webpage
ERROR: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1441, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1517, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/bbc.py", line 1190, in _real_extract
    initial_data = self._parse_json(initial_data, playlist_id, fatal=False)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 970, in _parse_json
    return json.loads(
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

--------------------------------------



With this fix https://github.com/ajj8/yt-dlp/commit/04b3418f2633ef76352a621765b743fff6d1b243 the error is: ERROR: [bbc] p08bl6tl: Unable to extract playlist data

Log below:
./yt-dlp -vU -F "https://www.bbc.com/reel/embed/p08bl6tl"
[debug] Command-line config: ['-vU', '-F', 'https://www.bbc.com/reel/embed/p08bl6tl']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [55937202b] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.5-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [bbc] Extracting URL: https://www.bbc.com/reel/embed/p08bl6tl
[bbc] p08bl6tl: Downloading webpage
ERROR: [bbc] p08bl6tl: Unable to extract playlist data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "./yt-dlp/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/bbc.py", line 1289, in _real_extract
    self._search_regex(
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1218, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

**Comment by JimmyCarlos** [comment]
Hi, rather than opening a new ticket - I'm going to post my error into this topic as it's almost identical to the previous posts, just a different part of the BBC website. I'm running the most recent version of yt-dlp through yt-dlg.

url = "https://www.bbc.co.uk/newsround/62587298"

LOG:
2022-08-19 08:22:40,568-DEBUG-Worker_1-[debug] Command-line config: ['--newline', '-i', '-o', '#####\\%(title)s.%(ext)s', '-f', 'mp4', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.bbc.co.uk/newsround/62587298']
2022-08-19 08:22:40,568-DEBUG-Worker_1-[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
2022-08-19 08:22:40,568-DEBUG-Worker_1-[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
2022-08-19 08:22:40,568-DEBUG-Worker_1-[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
2022-08-19 08:22:40,568-DEBUG-Worker_1-[debug] Checking exe version: ffmpeg -bsfs
2022-08-19 08:22:40,568-DEBUG-Worker_1-[debug] Checking exe version: ffprobe -bsfs
2022-08-19 08:22:40,568-DEBUG-Worker_1-[debug] exe versions: ffmpeg 2022-08-03-git-d3f48e68b3-essentials_build-www.gyan.dev (setts), ffprobe 2022-08-03-git-d3f48e68b3-essentials_build-www.gyan.dev
2022-08-19 08:22:40,568-DEBUG-Worker_1-[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
2022-08-19 08:22:40,568-DEBUG-Worker_1-[debug] Proxy map: {}
2022-08-19 08:22:40,568-DEBUG-Worker_1-[debug] [bbc] Extracting URL: https://www.bbc.co.uk/newsround/62587298
2022-08-19 08:22:40,568-DEBUG-Worker_1-ERROR: the JSON object must be str, bytes or bytearray, not dict
2022-08-19 08:22:40,568-DEBUG-Worker_1-Traceback (most recent call last):
2022-08-19 08:22:40,568-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 1442, in wrapper
2022-08-19 08:22:40,568-DEBUG-Worker_1-  File "yt_dlp\YoutubeDL.py", line 1518, in __extract_info
2022-08-19 08:22:40,568-DEBUG-Worker_1-  File "yt_dlp\extractor\common.py", line 666, in extract
2022-08-19 08:22:40,568-DEBUG-Worker_1-  File "yt_dlp\extractor\bbc.py", line 1190, in _real_extract
2022-08-19 08:22:40,568-DEBUG-Worker_1-  File "yt_dlp\extractor\common.py", line 970, in _parse_json
2022-08-19 08:22:40,568-DEBUG-Worker_1-  File "json\__init__.py", line 341, in loads
2022-08-19 08:22:40,568-DEBUG-Worker_1-TypeError: the JSON object must be str, bytes or bytearray, not dict
2022-08-19 08:22:40,568-DEBUG-Worker_1-Child process exited with non-zero code: 1

**Comment by designium** [comment]
Is @ajj8 fix working or still have that issue? How can I test his code?

**Comment by dirkf** [comment]
https://www.bbc.com/reel/embed/p08bl6tl: as with previous Reel pages, this has hydration data in the `data-json` attribute of the `script` element with `id="initial-data"`, but the video data is in the root of the `.initData` member instead of in a list `.initData.items`.

https://www.bbc.co.uk/newsround/62587298: this is a Morph page but, instead of a `vpid` in the `.body.video` member of one of the payloads, it has a `pid` in the `.body.media` member of one of the payloads, but no `vpid`, so it has to be passed through `url_result()` as `http://www.bbc.co.uk/programmes/{pid}`.

I've added the fixes for these and the corresponding tests to my refactored BBC extractor that will be coming to a yt-dl PR soon (including code taken from ajj8's PR here, as well as outstanding PRs from yt-dl). It should be a drop-in to yt-dlp apart from time machine cosmetics.

My solution to the Morph playlist vs video problem is this: when the page has a playlist (not like https://www.bbc.co.uk/newsround/62587298),
* if a video is found for which `/{pid}/` is in the URL, return that video (eg, https://www.bbc.com/reel/video/p07c6sb6/how-positive-thinking-is-harming-your-happiness);
* otherwise, return the playlist (eg https://www.bbc.com/reel/playlist/rethink).

**Comment by rpdelaney** [comment]
One more repro for the heap:
```console
$ yt-dlp -vv 'https://www.bbc.com/news/world-us-canada-49667778'
[debug] Command-line config: ['-vv', 'https://www.bbc.com/news/world-us-canada-49667778']
[debug] User config "/home/ryan/.config/yt-dlp.conf": ['--rate-limit', '2000K', '--output', '%(title).200B%(title.201B&…|)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.6.7-zen1-1-zen-x86_64-with-glibc2.38 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1 (setts), ffprobe 6.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1797 extractors
[bbc] Extracting URL: https://www.bbc.com/news/world-us-canada-49667778
[bbc] world-us-canada-49667778: Downloading webpage
ERROR: [bbc] world-us-canada-49667778: Unable to extract playlist data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/ryan/src/other/yt-dlp/.venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/src/other/yt-dlp/.venv/lib/python3.11/site-packages/yt_dlp/extractor/bbc.py", line 1291, in _real_extract
    self._search_regex(
  File "/home/ryan/src/other/yt-dlp/.venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1266, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
$
```

**Comment by bashonly** [comment]
OP's issue was partially addressed by 19741ab8a401ec64d5e84fdbfcfb141d105e7bc8

**Comment by Vangelis66** [comment]
@rpdelaney posted: 

 >```console
>[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]
>[debug] Lazy loading extractors is disabled
>[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.6.7-zen1-1-zen-x86_64-with-glibc2.38 (OpenSSL 3.2.0 23 >Nov 2023, glibc 2.38)
>```

... My OS (**Vista SP2 x86**) is no longer officially supported by `yt-dlp`, but using the 32-bit binary (py**3.7**-based) of the `2023.11.16` stable release (like you, basically :wink: ), I get different, **successful**, results with _the very same BBC URL_:

<details>
<summary>yt-dlp_x86 -vF "https://www.bbc.com/news/world-us-canada-49667778"</summary>

```console
[debug] Command-line config: ['-vF', 'https://www.bbc.com/news/world-us-canada-49667778']
Deprecated Feature: Support for Windows Vista/Server 2008 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_x86_exe)
[debug] Python 3.7.9 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.31.1, urllib3-2.0.7, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[bbc] Extracting URL: https://www.bbc.com/news/world-us-canada-49667778
[bbc] world-us-canada-49667778: Downloading webpage
[bbc] p07mf88w: Downloading media selection JSON
[bbc] p07mf88w: Downloading m3u8 information
[bbc] p07mf88w: Downloading m3u8 information
[bbc] p07mf88w: Downloading m3u8 information
[bbc] p07mf88w: Downloading m3u8 information
[bbc] p07mf88w: Downloading MPD manifest
[bbc] p07mf88w: Downloading MPD manifest
[bbc] p07mf88w: Downloading MPD manifest
[bbc] p07mf88w: Downloading MPD manifest
[download] Downloading playlist: Aaron Persky: Brock Turner judge fired from coaching girls
[bbc] Playlist Aaron Persky: Brock Turner judge fired from coaching girls: Downloading 1 items of 1
[download] Downloading item 1 of 1
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for p07mf88w:
ID                              EXT RESOLUTION FPS |   TBR PROTO | VCODEC VBR ACODEC     ABR ASR MORE INFO
---------------------------------------------------------------------------------------------------------------------------------
mf_akamai-audio_eng=96000-0     m4a audio only     |   96k dash  | audio only     mp4a.40.5  96k 48k [en] DASH audio, m4a_dash
mf_akamai-audio_eng=96000-1     m4a audio only     |   96k dash  | audio only     mp4a.40.5  96k 48k [en] DASH audio, m4a_dash
mf_cloudfront-audio_eng=96000-0 m4a audio only     |   96k dash  | audio only     mp4a.40.5  96k 48k [en] DASH audio, m4a_dash
mf_cloudfront-audio_eng=96000-1 m4a audio only     |   96k dash  | audio only     mp4a.40.5  96k 48k [en] DASH audio, m4a_dash
mf_akamai-video=281000-0        mp4 384x216     25 |  281k dash  | avc3.42C015  281k video only         DASH video, mp4_dash
mf_akamai-video=281000-1        mp4 384x216     25 |  281k dash  | avc3.42C015  281k video only         DASH video, mp4_dash
mf_cloudfront-video=281000-0    mp4 384x216     25 |  281k dash  | avc3.42C015  281k video only         DASH video, mp4_dash
mf_cloudfront-video=281000-1    mp4 384x216     25 |  281k dash  | avc3.42C015  281k video only         DASH video, mp4_dash
mf_akamai-400-0                 mp4 384x216     25 |  400k m3u8  | avc1.42C015  281k mp4a.40.5  96k
mf_akamai-400-1                 mp4 384x216     25 |  400k m3u8  | avc1.42C015  281k mp4a.40.5  96k
mf_cloudfront-400-0             mp4 384x216     25 |  400k m3u8  | avc1.42C015  281k mp4a.40.5  96k
mf_cloudfront-400-1             mp4 384x216     25 |  400k m3u8  | avc1.42C015  281k mp4a.40.5  96k
mf_akamai-video=437000-0        mp4 512x288     25 |  437k dash  | avc3.4D401E  437k video only         DASH video, mp4_dash
mf_akamai-video=437000-1        mp4 512x288     25 |  437k dash  | avc3.4D401E  437k video only         DASH video, mp4_dash
mf_cloudfront-video=437000-0    mp4 512x288     25 |  437k dash  | avc3.4D401E  437k video only         DASH video, mp4_dash
mf_cloudfront-video=437000-1    mp4 512x288     25 |  437k dash  | avc3.4D401E  437k video only         DASH video, mp4_dash
mf_akamai-565-0                 mp4 512x288     25 |  565k m3u8  | avc1.4D401E  437k mp4a.40.5  96k
mf_akamai-565-1                 mp4 512x288     25 |  565k m3u8  | avc1.4D401E  437k mp4a.40.5  96k
mf_cloudfront-565-0             mp4 512x288     25 |  565k m3u8  | avc1.4D401E  437k mp4a.40.5  96k
mf_cloudfront-565-1             mp4 512x288     25 |  565k m3u8  | avc1.4D401E  437k mp4a.40.5  96k
mf_akamai-video=827000-0        mp4 704x396     25 |  827k dash  | avc3.4D401E  827k video only         DASH video, mp4_dash
mf_akamai-video=827000-1        mp4 704x396     25 |  827k dash  | avc3.4D401E  827k video only         DASH video, mp4_dash
mf_cloudfront-video=827000-0    mp4 704x396     25 |  827k dash  | avc3.4D401E  827k video only         DASH video, mp4_dash
mf_cloudfront-video=827000-1    mp4 704x396     25 |  827k dash  | avc3.4D401E  827k video only         DASH video, mp4_dash
mf_akamai-979-0                 mp4 704x396     25 |  979k m3u8  | avc1.4D401E  827k mp4a.40.5  96k
mf_akamai-979-1                 mp4 704x396     25 |  979k m3u8  | avc1.4D401E  827k mp4a.40.5  96k
mf_cloudfront-979-0             mp4 704x396     25 |  979k m3u8  | avc1.4D401E  827k mp4a.40.5  96k
mf_cloudfront-979-1             mp4 704x396     25 |  979k m3u8  | avc1.4D401E  827k mp4a.40.5  96k
mf_akamai-video=1604000-0       mp4 960x540     25 | 1604k dash  | avc3.4D401F 1604k video only         DASH video, mp4_dash
mf_akamai-video=1604000-1       mp4 960x540     25 | 1604k dash  | avc3.4D401F 1604k video only         DASH video, mp4_dash
mf_cloudfront-video=1604000-0   mp4 960x540     25 | 1604k dash  | avc3.4D401F 1604k video only         DASH video, mp4_dash
mf_cloudfront-video=1604000-1   mp4 960x540     25 | 1604k dash  | avc3.4D401F 1604k video only         DASH video, mp4_dash
mf_akamai-1802-0                mp4 960x540     25 | 1802k m3u8  | avc1.4D401F 1604k mp4a.40.5  96k
mf_akamai-1802-1                mp4 960x540     25 | 1802k m3u8  | avc1.4D401F 1604k mp4a.40.5  96k
mf_cloudfront-1802-0            mp4 960x540     25 | 1802k m3u8  | avc1.4D401F 1604k mp4a.40.5  96k
mf_cloudfront-1802-1            mp4 960x540     25 | 1802k m3u8  | avc1.4D401F 1604k mp4a.40.5  96k
[download] Finished downloading playlist: Aaron Persky: Brock Turner judge fired from coaching girls
```

</details>

So, what's going on differently in your case? ...

**Comment by bashonly** [comment]
> So, what's going on differently in your case? ...

I get the same error as rpdelaney due to geo-restriction

**Comment by Vangelis66** [comment]
> I get the same error as rpdelaney **due to geo-restriction**

My physical location is **Southern Europe** :wink: (not the **UK**); I was under the impression `www.bbc.com` offerings (and, certainly, **news** items/clips) were **globally available** (from overseas), as opposed to many `www.bbc.co.uk` offerings reserved for just within the **UK**; in any case, if it's geo-restriction the reason **rpdelaney** fails to access that videoclip, is this still relevant to this issue? 
From experience, when "I" try to access geo-fenced BBC content (e.g on `iPlayer`), I usually end-up with a `403 forbidden` and/or `geolocation` error, which is indicative enough; wouldn't it be better if `yt-dlp` raised a similar error/notification in the case of 
https://www.bbc.com/news/world-us-canada-49667778
too? (`Unable to extract playlist data` sounds pretty vague/generic to me...)

**Comment by bashonly** [comment]
ah my bad, it's not geo-restriction. but the html that is served to my region seems completely different than anything the extractor is expecting. all the useful info is in a nextjs `__NEXT_DATA__` block

**Comment by Vangelis66** [comment]
> it's **not geo-restriction**. but the html that is served to my region seems completely different than anything the extractor is expecting

Spot on! :+1: **Europe** and **The Americas** are being served different pages/embedded players; only the "European" version is compatible with the extractor: 

European IP: 

![Europe](https://github.com/yt-dlp/yt-dlp/assets/9669492/f998bc07-f5fb-4428-898f-9bcb31481a26)

US IP: 

![America](https://github.com/yt-dlp/yt-dlp/assets/9669492/3de5e63c-9596-4e9f-ab6e-71426e008852)

In both cases, the content _does play back_ inside the browser...

**Comment by dirkf** [comment]
With the last BBC PR, and probably for some time before:
* https://www.bbc.co.uk/newsround/62587298 works for me from UK and with MX VPN (in case non-UK location is getting different pages)
* Ditto https://www.bbc.com/news/world-us-canada-49667778
* https://www.bbc.com/reel/embed/p08bl6tl gives 500, as in the browser.

But the original problem URL is still not properly handled (`vpid` of the main video and supporting videos is in `__INITIAL_DATA__` objects with `type: "video-block"`).
