### ISSUE TITLE
Pluto.tv Extractor claiming no videos for some On-Demand Content

### ISSUE THREAD

**Issue by RedPenguin2** [yt-dlp/yt-dlp#432]
## Checklist

- [ X] I'm reporting a broken site support issue
- [ X] I've verified that I'm running yt-dlp version **2021.06.09**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

yt-dlp --verbose --write-subs "https://pluto.tv/on-demand/series/cold-case-files-classic/season/1/episode/investreportscold-case-files-through-the-eyes-of-a-childkiller-next-door-1-6"
[debug] Command-line config: ['--verbose', '--write-subs', 'https://pluto.tv/on-demand/series/cold-case-files-classic/season/1/episode/investreportscold-case-files-through-the-eyes-of-a-childkiller-next-door-1-6']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.04.22 (exe)
[debug] Python version 3.8.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-101416-g3065532a0e-ffmpeg-windows-build-helpers, ffprobe N-101416-g3065532a0e-ffmpeg-windows-build-helpers, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[PlutoTV] cold-case-files-classic: Downloading JSON metadata
[PlutoTV] 5c37f769394025ecbfc20431: Downloading m3u8 information
[PlutoTV] 5c37f769394025ecbfc20431: Downloading m3u8 playlist
[PlutoTV] 5c37f769394025ecbfc20431: Downloading m3u8 playlist
[PlutoTV] 5c37f769394025ecbfc20431: Downloading m3u8 playlist
[PlutoTV] 5c37f769394025ecbfc20431: Downloading m3u8 playlist
[PlutoTV] 5c37f769394025ecbfc20431: Downloading m3u8 playlist
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1059, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1080, in __extract_info
  File "yt_dlp\extractor\common.py", line 558, in extract
  File "yt_dlp\extractor\plutotv.py", line 153, in _real_extract
  File "yt_dlp\extractor\plutotv.py", line 119, in _get_video_info
  File "yt_dlp\extractor\plutotv.py", line 103, in _to_ad_free_formats
  File "yt_dlp\extractor\common.py", line 1687, in _sort_formats
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

------AND----

yt-dlp --verbose "https://pluto.tv/on-demand/series/cold-case-files-classic/season/1/episode/traces-of-murderthe-bathtub-killer-1-9"
[debug] Command-line config: ['--verbose', 'https://pluto.tv/on-demand/series/cold-case-files-classic/season/1/episode/traces-of-murderthe-bathtub-killer-1-9']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.04.22 (exe)
[debug] Python version 3.8.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-101416-g3065532a0e-ffmpeg-windows-build-helpers, ffprobe N-101416-g3065532a0e-ffmpeg-windows-build-helpers, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[PlutoTV] cold-case-files-classic: Downloading JSON metadata
[PlutoTV] 5ca7faa88bac49de092da330: Downloading m3u8 information
[PlutoTV] 5ca7faa88bac49de092da330: Downloading m3u8 playlist
[PlutoTV] 5ca7faa88bac49de092da330: Downloading m3u8 playlist
[PlutoTV] 5ca7faa88bac49de092da330: Downloading m3u8 playlist
[PlutoTV] 5ca7faa88bac49de092da330: Downloading m3u8 playlist
[PlutoTV] 5ca7faa88bac49de092da330: Downloading m3u8 playlist
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1059, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1080, in __extract_info
  File "yt_dlp\extractor\common.py", line 558, in extract
  File "yt_dlp\extractor\plutotv.py", line 153, in _real_extract
  File "yt_dlp\extractor\plutotv.py", line 119, in _get_video_info
  File "yt_dlp\extractor\plutotv.py", line 103, in _to_ad_free_formats
  File "yt_dlp\extractor\common.py", line 1687, in _sort_formats
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

I am trying to get these episodes, yet they both won't down even though others will from the same Season.

I can clearly see the m3u8 in my browser and can even download it with other tools but I don't completely understand the trick to getting them ad-free like yt-dlp does it. Even changing "serverSideAds" to False, keeps giving me downloads with ads in them.

**Comment by pukkandan** [comment]
what does `yt-dlp --allow-unplayable-formats -F -- URL` give?

**Comment by RedPenguin2** [comment]
It gives:

ID       EXT RESOLUTION FPS |   TBR PROTO  | VCODEC        VBR ACODEC     ABR
-------- --- ---------- --- - ----- ------ - ----------- ----- --------- ----
hls-434  mp4 426x240    30  |  434k m3u8_n | avc1.64001f  434k mp4a.40.2   0k
hls-736  mp4 640x360    30  |  736k m3u8_n | avc1.64001f  736k mp4a.40.2   0k
hls-1138 mp4 854x480    30  | 1138k m3u8_n | avc1.64001f 1138k mp4a.40.2   0k
hls-1742 mp4 854x480    30  | 1742k m3u8_n | avc1.64001f 1742k mp4a.40.2   0k
hls-2542 mp4 1280x720   30  | 2542k m3u8_n | avc1.64001f 2542k mp4a.40.2   0k

For some reason if I do "https://pluto.tv/on-demand/series/cold-case-files-classic/season/1/", it downloads every episode no problem.

**Comment by RedPenguin2** [comment]
I now have a new problem though.

For some reason, some subtitles download perfectly while random other ones give:

[download] Destination: Cold Case Files Classics [5c37f769394025ecbfc20431].en.vtt
[download]   1.0% of ~23.67KiB at Unknown speed ETA Unknown ETAERROR: Parse error at position 57 (near '00:00:22.367 --> 00:')

It's always that same error "Parse error at position 57".

**Comment by pukkandan** [comment]
> It gives:
> 
> ID EXT RESOLUTION FPS | TBR PROTO | VCODEC VBR ACODEC ABR
> 
> hls-434 mp4 426x240 30 | 434k m3u8_n | avc1.64001f 434k mp4a.40.2 0k
> hls-736 mp4 640x360 30 | 736k m3u8_n | avc1.64001f 736k mp4a.40.2 0k
> hls-1138 mp4 854x480 30 | 1138k m3u8_n | avc1.64001f 1138k mp4a.40.2 0k
> hls-1742 mp4 854x480 30 | 1742k m3u8_n | avc1.64001f 1742k mp4a.40.2 0k
> hls-2542 mp4 1280x720 30 | 2542k m3u8_n | avc1.64001f 2542k mp4a.40.2 0k
> 

If the formats ae listed with `--allow-unplayable-formats` but not without it, then the video is DRM protected
