### ISSUE TITLE
vixbrasiltv

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#4320]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Brazil

### Example URLs

- Single video: https://www.vixbrasiltv.com/tv/watch/series/jaspion_jp/1/1 (Season 1, episode 1)
- Single video: https://www.vixbrasiltv.com/tv/watch/series/jaspion_jp/1/2 (Season 1, episode 2)

Websites:
https://www.vixbrasiltv.com

### Provide a description that is worded well enough to be understood

Website doesn't need login/password. They are completely free.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.vixbrasiltv.com/tv/watch/series/jaspion_jp/1/1                                     ─╯
[debug] Command-line config: ['-vU', 'https://www.vixbrasiltv.com/tv/watch/series/jaspion_jp/1/1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (zip)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.16.0-12parrot1-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: certifi-2021.05.30, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://www.vixbrasiltv.com/tv/watch/series/jaspion_jp/1/1
[generic] 1: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1: Downloading webpage
[generic] 1: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.vixbrasiltv.com/tv/watch/series/jaspion_jp/1/1
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1490, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4130, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.vixbrasiltv.com/tv/watch/series/jaspion_jp/1/1
```

**Comment by gamer191** [comment]
note for devs: the example url is geo-blocked

**Comment by doe1080** [comment]
no longer available
