### ISSUE TITLE
[AbemaTV] site broken

### ISSUE THREAD

**Issue by zica87** [yt-dlp/yt-dlp#4321]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

2022.6.29 version has the error.
Then I used 2022.5.18 version, no error, downloaded successfully.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://abema.tv/video/episode/19-98_s3_p1']
[debug] Portable config "G:\Video\DL\yt-dlp\yt-dlp.conf": ['--ffmpeg-location', 'G:/Video/DL/ffmpeg-2021-04-25-git-d98884be41-full_build/bin/', '--console-title', '-o', 'G:/Video/Anime/%(title)s.%(ext)s', '--no-playlist', '--embed-thumbnail', '--convert-thumbnails', 'webp>png']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: "G:/Video/DL/ffmpeg-2021-04-25-git-d98884be41-full_build/bin/ffmpeg" -bsfs
[debug] Checking exe version: "G:/Video/DL/ffmpeg-2021-04-25-git-d98884be41-full_build/bin/ffprobe" -bsfs
[debug] exe versions: ffmpeg 2021-04-25-git-d98884be41-full_build-www.gyan.dev (setts), ffprobe 2021-04-25-git-d98884be41-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [AbemaTV] Extracting URL: https://abema.tv/video/episode/19-98_s3_p1
[AbemaTV] Authorizing
[AbemaTV] 19-98_s3_p1: Downloading webpage
[AbemaTV] 19-98_s3_p1: Checking playability
[AbemaTV] 19-98_s3_p1: Downloading m3u8 information
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 19-98_s3_p1: Downloading 1 format(s): 5300
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: G:\Video\Anime\第1話 ハルマゲドンかるたX.jpg
[ThumbnailsConvertor] Not converting thumbnail "G:\Video\Anime\第1話 ハルマゲドンかるたX.jpg"; could not find a mapping for jpg
[debug] Invoking hlsnative downloader on "https://vod-abematv.akamaized.net/program/19-98_s3_p1/1080/playlist.m3u8?aver=1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 237
[download] Destination: G:\Video\Anime\第1話 ハルマゲドンかるたX.mp4
[debug] File locking is not supported. Proceeding without locking
[download]   0.4% of ~518.10MiB at  509.50KiB/s ETA 17:15 (frag 1/237)[AbemaTV] Fetching media token
[AbemaTV] Requesting playback license
ERROR: base None exceeds table length 58
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1420, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1504, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1561, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2630, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3129, in process_info
  File "yt_dlp\YoutubeDL.py", line 2829, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\hls.py", line 354, in real_download
  File "yt_dlp\downloader\fragment.py", line 526, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 354, in decrypt_fragment
  File "yt_dlp\downloader\fragment.py", line 346, in _get_key
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\extractor\abematv.py", line 141, in abematv_license_open
  File "yt_dlp\extractor\abematv.py", line 127, in _get_videokey_from_ticket
  File "yt_dlp\utils.py", line 4778, in decode_base_n
  File "yt_dlp\utils.py", line 4759, in _base_n_table
ValueError: base None exceeds table length 58
```

**Comment by xtkoba** [comment]
Should be fixed in master HEAD (by commit 44f14eb43e1601342955bbb4f34cee523cb8a874).
