### ISSUE TITLE
[Globo] ERROR: local variable 'received_time' referenced before assignment

### ISSUE THREAD

**Issue by mwt** [yt-dlp/yt-dlp#4328]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I am trying to download from Globoplay (eg. https://globoplay.globo.com/v/7355852/). I know that a relatively new authentication method was added to make this work. I am able to download from YouTube and other sites, but not this one. The error seems to be in the globo extractor anyway. I do not know why `received_time` is undefined.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', '/home/matthew/Downloads/cookies.txt', 'https://globoplay.globo.com/v/7355852/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (zip)
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.17.15-76051715-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-9.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [Globo] Extracting URL: https://globoplay.globo.com/v/7355852/
[Globo] 7355852: Getting cookies
[Globo] 7355852: Downloading JSON metadata
[Globo] 7355852: Downloading security hash for 7355852
[Globo] 7355852: Getting locksession cookie
ERROR: local variable 'received_time' referenced before assignment
Traceback (most recent call last):
  File "/home/matthew/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "/home/matthew/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1490, in __extract_info
    ie_result = ie.extract(url)
  File "/home/matthew/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/home/matthew/.local/bin/yt-dlp/yt_dlp/extractor/globo.py", line 131, in _real_extract
    padded_sign_time = compat_str(int(received_time) + 86400) + padding
UnboundLocalError: local variable 'received_time' referenced before assignment
```

**Comment by dirkf** [comment]
The extractor fetches a security hash and only sets `received_time` for (presumably, the known) 6 cases of the possible 100 pairs of initial digits, assuming that it's always numeric. This needs a login or cookies to debug.

Although the extractor doesn't know what to do, this would have provided a more useful diagnostic: 

```diff
--- old/yt_dlp/extractor/globo.py
+++ new/yt_dlp/extractor/globo.py
@@ -127,6 +127,9 @@
             received_md5 = security_hash[22:]
             padding += '1'
             hash_prefix = '05' + security_hash[:22]
+        else:
+            raise ExtractorError(
+                '%s: unexpected hash code %s' % (self.IE_NAME, hash_code))
 
         padded_sign_time = compat_str(int(received_time) + 86400) + padding
         md5_data = (received_md5 + padded_sign_time + '0xAC10FD').encode()
```
Perhaps, as apparently the `received_time` is embedded in the security hash as a Unix epoch value, the extractor could try to assign the received hash to one of the existing cases by looking for a significant prefix (eg, `[:6]`) of the current epoch in the hash.

**Comment by renatobusatto** [comment]
I also can provide login credentials if needed.

**Comment by jessicaione101** [comment]
I was having the same problem and, after analyzing the downloaded JSON file, I changed [this line](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/globo.py#L112) in **globo.py** to the following.

```python
security_hash = security['sources'][1]['token']
``` 
It's working for me and I was able to download many videos behind a login in batch, but I don't know if this is enough testing for deployment.

**Comment by bashonly** [comment]
f8d0161455f00add65585ca1a476a7b5d56f5f96
