### ISSUE TITLE
[Youtube] 

### ISSUE THREAD

**Issue by b4imetu** [yt-dlp/yt-dlp#4335]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Singapore

### Provide a description that is worded well enough to be understood

When I use [yt-dlp from scoop](https://github.com/ScoopInstaller/Main/blob/master/bucket/yt-dlp.json), I am unable to download some YouTube videos.
But if I manually download yt-dlp.exe in a new path and run `./yt-dlp`, this problem does not occur.
I don't know if it's the `yt-dlp.conf` that causes the problem.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
> yt-dlp -vU -f 299+140 https://www.youtube.com/watch?v=LAVEKwkijLE
[debug] Command-line config: ['-vU', '-f', '299+140', 'https://www.youtube.com/watch?v=LAVEKwkijLE']
[debug] Portable config "D:\Scoop\apps\yt-dlp\current\yt-dlp.conf": []
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22621-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'https://127.0.0.1:10809', 'ftp': 'ftp://127.0.0.1:10809'}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=LAVEKwkijLE
[youtube] LAVEKwkijLE: Downloading webpage
[youtube] LAVEKwkijLE: Downloading android player API JSON
[debug] Loading youtube-nsig.0e7373c2 from cache
[debug] [youtube] Decrypted nsig fZcOi9i_C-Lae3Bju => CMaN4GAEhK9ZXA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] LAVEKwkijLE: Downloading 1 format(s): 299+140
[debug] Invoking http downloader on "https://rr1---sn-npoeenly.googlevideo.com/videoplayback?expire=1657613370&ei=2tfMYseHKJWc4t4P5qKykAw&ip=149.129.44.144&id=o-APErmBa2ty0oxAtUIP7KvsU8S3bJDquiGXaqsUggdFe4&itag=299&source=youtube&requiressl=yes&mh=S9&mm=31%2C29&mn=sn-npoeenly%2Csn-npoe7nsl&ms=au%2Crdu&mv=m&mvi=1&pl=19&initcwndbps=980000&vprv=1&mime=video%2Fmp4&gir=yes&clen=984237091&dur=1403.985&lmt=1594890109044637&mt=1657591502&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgRniykcAxBC8-1A96B9Rfpi2sLGVXK795E4N_GUmEjmECIF450UgYd_Mx_5pwA-TCCKiO5z6LZdb6OOJhZdYCtUsf&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOWmuHT0kUEn32fbsiQxXULDIWvInRvBldYtkNg7Ia3HAiB2iTBV_-EoPGgjz_uOWNo89mXbB9StQGfgPLvOeaadkA%3D%3D"
[download] Unable to open file due to file access error. Retrying (attempt 1 of 3) ...
[download] Unable to open file due to file access error. Retrying (attempt 2 of 3) ...
[download] Unable to open file due to file access error. Retrying (attempt 3 of 3) ...
ERROR: unable to open for writing: [Errno 13] Permission denied: 'Review - 2020 Honda Civic Si Coupe HPT [LAVEKwkijLE].f299.mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils.py", line 625, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 266, in download
  File "yt_dlp\downloader\common.py", line 224, in inner
  File "yt_dlp\downloader\common.py", line 242, in sanitize_open
  File "yt_dlp\utils.py", line 628, in sanitize_open
PermissionError: [Errno 13] Permission denied: 'Review - 2020 Honda Civic Si Coupe HPT [LAVEKwkijLE].f299.mp4.part'


[debug] Invoking http downloader on "https://rr1---sn-npoeenly.googlevideo.com/videoplayback?expire=1657613370&ei=2tfMYseHKJWc4t4P5qKykAw&ip=149.129.44.144&id=o-APErmBa2ty0oxAtUIP7KvsU8S3bJDquiGXaqsUggdFe4&itag=140&source=youtube&requiressl=yes&mh=S9&mm=31%2C29&mn=sn-npoeenly%2Csn-npoe7nsl&ms=au%2Crdu&mv=m&mvi=1&pl=19&initcwndbps=980000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=22723964&dur=1404.040&lmt=1594889230931004&mt=1657591502&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgDznj56yirTCi8UIgu6kwypmzFQCv2w7RD0ksWuxipB0CIQCPiWLo_-qTmZyNTx4rf1SEn1MgH_MuBB9r8OdEDipcIw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOWmuHT0kUEn32fbsiQxXULDIWvInRvBldYtkNg7Ia3HAiB2iTBV_-EoPGgjz_uOWNo89mXbB9StQGfgPLvOeaadkA%3D%3D"
[download] Unable to open file due to file access error. Retrying (attempt 1 of 3) ...
[download] Unable to open file due to file access error. Retrying (attempt 2 of 3) ...
[download] Unable to open file due to file access error. Retrying (attempt 3 of 3) ...
ERROR: unable to open for writing: [Errno 13] Permission denied: 'Review - 2020 Honda Civic Si Coupe HPT [LAVEKwkijLE].f140.m4a.part'
Traceback (most recent call last):
  File "yt_dlp\utils.py", line 625, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 266, in download
  File "yt_dlp\downloader\common.py", line 224, in inner
  File "yt_dlp\downloader\common.py", line 242, in sanitize_open
  File "yt_dlp\utils.py", line 628, in sanitize_open
PermissionError: [Errno 13] Permission denied: 'Review - 2020 Honda Civic Si Coupe HPT [LAVEKwkijLE].f140.m4a.part'
```

**Comment by Lesmiscore** [comment]
Scoop installation is not officially supported. [Download from releases of this repository](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.06.29) and try with it.

**Comment by pukkandan** [comment]
Check that you have write access to your current directory (`cd`). Being a scoop install should not be relevant

**Comment by rashil2000** [comment]
@b4imetu as @pukkandan said, being a Scoop install should not matter. Scoop just downloads the archive and places the binary in place for use. 

I ran the command you've used and it starts video download normally.

It looks like you don't have write access in the location you're trying to download in.

**Comment by b4imetu** [comment]
> Check that you have write access to your current directory (`cd`). Being a scoop install should not be relevant

> It looks like you don't have write access in the location you're trying to download in.

Thank you guys. I unchecked `Read-only` for `yt-dlp` folder, but it didn't start downloading normally. Didn't know how to fix it.
![Snipaste_2022-07-12_16-00-57](https://user-images.githubusercontent.com/41535001/178440321-758095be-2f4b-4fa3-aa02-750db1892f0a.jpg)

**Comment by b4imetu** [comment]
@pukkandan Sorry about bothering you, I thought yt-dlp would download by default in the folder where `yt-dlp.exe` is located, but it turns out it's a `current directory (cd)` problem. I'm so stupid ^^!
