### ISSUE TITLE
Pluto TV download entire seasons

### ISSUE THREAD

**Issue by moom0o** [yt-dlp/yt-dlp#4337]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://pluto.tv/en/search/details/series/crime-investigation-australia/season/1

### Provide a description that is worded well enough to be understood

I am able to download individual episodes (example: https://pluto.tv/en/on-demand/series/crime-investigation-australia/season/1/episode/no-more-grannies-the-granny-killer-2005-1-1) but am unable to download entire seasons. It would be great if it could download the entire season.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp https://pluto.tv/en/search/details/series/crime-investigation-australia/season/1 -vU
[debug] Command-line config: ['https://pluto.tv/en/search/details/series/crime-investigation-australia/season/1', '-vU'][debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (zip)
[debug] Python 3.7.3 (CPython 64bit) - Linux-4.4.0-19041-Microsoft-x86_64-with-debian-10.10 (glibc 2.28)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg N-60236-gffb000fff8-static (setts)
[debug] Optional libraries: Cryptodome-3.14.1, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://pluto.tv/en/search/details/series/crime-investigation-australia/season/1
[generic] 1: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1: Downloading webpage
[generic] 1: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://pluto.tv/en/search/details/series/crime-investigation-australia/season/1
Traceback (most recent call last):
  File "/home/debian/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "/home/debian/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1490, in __extract_info
    ie_result = ie.extract(url)
  File "/home/debian/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/home/debian/.local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4130, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://pluto.tv/en/search/details/series/crime-investigation-australia/season/1
```

**Comment by moom0o** [comment]
Nevermind, got it working by using https://pluto.tv/en/on-demand/series/crime-investigation-australia/season/1/

Nonetheless, the requests with /search should probably redirect you too.
