### ISSUE TITLE
[gotowebinar] 

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4348]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

global

### Example URLs

https://register.gotowebinar.com/recording/viewRecording/3820737359913857806/8942545096850977295/dwusa@mac.com?registrantKey=553718877925384203&type=ABSENTEEEMAILRECORDINGLINK

### Provide a description that is worded well enough to be understood

Link can be extracted by looking into page source:
https://cdn.recordingassets.logmeininc.com/200000000000989880/200000000001048408/56c764b6-9550-4942-94e2-4c99208ff771/recording/6208122350734847746/transcode/6208122350734847746.mp4?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLnJlY29yZGluZ2Fzc2V0cy5sb2dtZWluaW5jLmNvbS8yMDAwMDAwMDAwMDA5ODk4ODAvMjAwMDAwMDAwMDAxMDQ4NDA4LzU2Yzc2NGI2LTk1NTAtNDk0Mi05NGUyLTRjOTkyMDhmZjc3MS8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjU3ODI1NjE1fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=070Er8ZdElNyVHgkWosrQ2-Pze6vB8EqsdYUcM7~t0dn~9rjMQi0rWGte0zKlprbesuwMqXPl2MaHov5HgLLlh9tARjPwh-1qaHtgaHOUUB19YwwAX-YisxewkW6j5OCsJNOlOOB428UVv~reQta0AxBZN2pi8q6fEXu0~aLi355gP458REUoF-M9eyCQ5J1i65IQHxpN9wnbqtr-qEWvB-khXNPAfY-ZcAKYjiJW8XGpLa4lebyB3DeDv249J7pSlXC~Pfqj5ekaPTztO8yc94QeGUSbz2Wj66~GoHiaBmC-Wt4SaYOa1NcCRSGcbcEMjT9KpG06ehymQ86cqrA7Q__&Key-Pair-Id=APKAI2Z3PWL3BWDDZ5IA&response-content-disposition=attachment

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -F "https://register.gotowebinar.com/recording/viewRecording/3820737359913857806/8942545096850977295/dwusa@mac.com?registrantKey=553718877925384203&type=ABSENTEEEMAILRECORDINGLINK"
[generic] dwusa@mac: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] dwusa@mac: Extracting information
ERROR: Unsupported URL: https://register.gotowebinar.com/recording/viewRecording/3820737359913857806/8942545096850977295/dwusa@mac.com?registrantKey=553718877925384203&type=ABSENTEEEMAILRECORDINGLINK
sy@SYs-MacBook-Air yt-dlp % ./yt-dlp -vU -F "https://register.gotowebinar.com/recording/viewRecording/3820737359913857806/8942545096850977295/dwusa@mac.com?registrantKey=553718877925384203&type=ABSENTEEEMAILRECORDINGLINK"
[debug] Command-line config: ['-vU', '-F', 'https://register.gotowebinar.com/recording/viewRecording/3820737359913857806/8942545096850977295/dwusa@mac.com?registrantKey=553718877925384203&type=ABSENTEEEMAILRECORDINGLINK']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://register.gotowebinar.com/recording/viewRecording/3820737359913857806/8942545096850977295/dwusa@mac.com?registrantKey=553718877925384203&type=ABSENTEEEMAILRECORDINGLINK
[generic] dwusa@mac: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] dwusa@mac: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://register.gotowebinar.com/recording/viewRecording/3820737359913857806/8942545096850977295/dwusa@mac.com?registrantKey=553718877925384203&type=ABSENTEEEMAILRECORDINGLINK
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1433, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1503, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://register.gotowebinar.com/recording/viewRecording/3820737359913857806/8942545096850977295/dwusa@mac.com?registrantKey=553718877925384203&type=ABSENTEEEMAILRECORDINGLINK
```

**Comment by HobbyistDev** [comment]
From your link, i found the api call in `https://api.services.gotomeeting.com/registrationservice/api/v1/webinars/3820737359913857806/registrants/553718877925384203/recordingAssets?type=ABSENTEEEMAILRECORDINGLINK&client=spa`. Here's the output:
```json
{
  "webinarKey": "3820737359913857806",
  "registrantKey": "553718877925384203",
  "recordingAsset": "https://api.recordingassets.logmeininc.com/assetfleet/recording/als/api/v1/assets/56c764b6-9550-4942-94e2-4c99208ff771",
  "cdnLocation": "https://cdn.recordingassets.logmeininc.com/200000000000989880/200000000001048408/56c764b6-9550-4942-94e2-4c99208ff771/recording/6208122350734847746/transcode/6208122350734847746.mp4?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLnJlY29yZGluZ2Fzc2V0cy5sb2dtZWluaW5jLmNvbS8yMDAwMDAwMDAwMDA5ODk4ODAvMjAwMDAwMDAwMDAxMDQ4NDA4LzU2Yzc2NGI2LTk1NTAtNDk0Mi05NGUyLTRjOTkyMDhmZjc3MS8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjU3ODY0NjI1fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=wKYH4J-SX75iFzC0mUR3u~7U6FY-2eux6Hy6pKH7bZWiSGzkW6j-eMRA3bcQ8jD6RaDKWD-FeEJzPcQUf~sm~Xvhyfkl7UPceWoovyUi~hC1JNdgHmqg0WEvakn3elRqDZH3p0iSvWo7178PZzA2vkUxCnyzDjinlRbd0H-mhBImJvRfhF91JdKYQUwz14ZU4gLWYml8A1mzOgMWWbC-v506o4B57dWyXheKNKw3VxAaMXSo5Oxfi2t5snHTLp4xTnypojZy-3POjsT~F9g2-gn4tvjMmfl~h6QUE8xRBtK3R2HhvEi~yn4k8MQVoNGHZVNZlEVC60DrI1xvLCZhgQ__&Key-Pair-Id=APKAI2Z3PWL3BWDDZ5IA&response-content-disposition=attachment",
  "recordingKey": "8942545096850977295",
  "_links": {
    "self": {
      "href": "https://api.services.gotomeeting.com/registrationservice/api/v1/webinars/3820737359913857806/registrants/553718877925384203/recordingAssets?type=ABSENTEEEMAILRECORDINGLINK{&registrationService}",
      "templated": true
    }
  }
}
```
We can get the video in `json['cdnLocation']`

**Comment by grandmastermarco** [comment]
Any chance this can get implemented? I don't know how this would work. But seems like all the info is there already? Or is something kissing still?

**Comment by pukkandan** [comment]
> Any chance this can get implemented? 

Who exactly are you asking? We are all volunteers here and it will be added when someone implements it, makes a PR, and then deemed satisfactory by reviews...

Don't expect maintainers to deal with the thousands of supported sites by ourselves, much less address site requests. Maintainers and other frequent contributors usually have a few sites each of us maintain, and support for everything else is dependent on more volunteer contributors.

If you want to get it done quickly, consider (1) implementing yourself, (2) hiring someone to do it, or (3) putting a bounty.
