### ISSUE TITLE
plus.globalcyclingnetwork.com

### ISSUE THREAD

**Issue by fogelsong** [yt-dlp/yt-dlp#4377]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

https://plus.globalcyclingnetwork.com/watch/the-weight-of-the-peloton
https://plus.globalcyclingnetwork.com/watch/tirreno-adriatico-stage-07-extended-highlights
https://plus.globalcyclingnetwork.com/watch/legend-fabian-cancellara

### Provide a description that is worded well enough to be understood

I am unable to download the videos using yt-dlp.
One does have to login with a paid subscription to view most videos.

I am able to, with the Firefox add-ons "The Stream Detector" and "Video DownloadHelper", determine the m3u8 URLs which I can utilize with yt-dlp. 

Unfortunately, there are separate audio m3u8 URLs and video m3u8 URLs. The URLs all have a base URL of https://eurosport-vod.akamai.prod-live.h264.io/

If it would help, for example, for the video located at https://plus.globalcyclingnetwork.com/watch/legend-fabian-cancellara these two URLs would be the audio and video URLs I would use in two separate yt-dlp commands:

audio: https://eurosport-vod.akamai.prod-live.h264.io/primary/1/6f27a1b955034966aa0d094492d292e6/427051a04d284358842dcb49e42ea001/hdntl=exp=1658177509~acl=/primary/1/6f27a1b955034966aa0d094492d292e6/427051a04d284358842dcb49e42ea001/*~data=hdntl~hmac=aea60ad078be4c9dbd4446ea3bb0b3980961994b6596b294434fda1ca4c24eb6/12d8ab60c6794f568d0400db820972af/de0a0b41d4ea49668bf250f961fd2bdd/a827330efde24aa09fa26dc362a1d41c/index_9_0.m3u8

video: https://eurosport-vod.akamai.prod-live.h264.io/primary/1/6f27a1b955034966aa0d094492d292e6/427051a04d284358842dcb49e42ea001/hdntl=exp=1658177509~acl=/primary/1/6f27a1b955034966aa0d094492d292e6/427051a04d284358842dcb49e42ea001/*~data=hdntl~hmac=aea60ad078be4c9dbd4446ea3bb0b3980961994b6596b294434fda1ca4c24eb6/12d8ab60c6794f568d0400db820972af/de0a0b41d4ea49668bf250f961fd2bdd/a827330efde24aa09fa26dc362a1d41c/index_7.m3u8

It would be lovely if yt-dlp were able to, provided the https://plus.globalcyclingnetwork.com/etcetcetc URL, download and combine the audio and video streams like it does with many other sites.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://plus.globalcyclingnetwork.com/watch/the-weight-of-the-peloton', '-vU', '--cookies', '%cookie%', '-f', 'bv+ba/b', '--convert-subs', 'srt', '--embed-subs', '--remux-video', 'mkv', '--compat-options', 'no-attach-info-json', '-o', 'C:\\yt-dlp\\%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Compatibility options: no-attach-info-json
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://plus.globalcyclingnetwork.com/watch/the-weight-of-the-peloton
[generic] the-weight-of-the-peloton: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] the-weight-of-the-peloton: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://plus.globalcyclingnetwork.com/watch/the-weight-of-the-peloton
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://plus.globalcyclingnetwork.com/watch/the-weight-of-the-peloton
```

**Comment by doe1080** [comment]
URL has changed to https://www.globalcyclingnetwork.com
all videos have been replaced with YouTube content, individual video pages no longer exist, and each topic page merely lists multiple URLs, so creating ie is no longer meaningful
