### ISSUE TITLE
[YouTube] ERROR: Postprocessing: Conversion failed!

### ISSUE THREAD

**Issue by CorentinB** [yt-dlp/yt-dlp#4379]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

I've found many videos with which yt-dlp is failing to do conversions when post processing happen.
Many videos of the user https://www.youtube.com/c/AlmightyDJChiszle for example.

Example with one of his videos:

```
yt-dlp --format "(bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec^=vp9.2][height>=4320][fps>30]/bestvideo[vcodec^=vp9][height>=4320][fps>30]/bestvideo[vcodec^=avc1][height>=4320][fps>30]/bestvideo[height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=4320]/bestvideo[vcodec^=vp9.2][height>=4320]/bestvideo[vcodec^=vp9][height>=4320]/bestvideo[vcodec^=avc1][height>=4320]/bestvideo[height>=4320]/bestvideo[vcodec^=av01][height>=2880][fps>30]/bestvideo[vcodec^=vp9.2][height>=2880][fps>30]/bestvideo[vcodec^=vp9][height>=2880][fps>30]/bestvideo[vcodec^=avc1][height>=2880][fps>30]/bestvideo[height>=2880][fps>30]/bestvideo[vcodec^=av01][height>=2880]/bestvideo[vcodec^=vp9.2][height>=2880]/bestvideo[vcodec^=vp9][height>=2880]/bestvideo[vcodec^=avc1][height>=2880]/bestvideo[height>=2880]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec^=vp9.2][height>=2160][fps>30]/bestvideo[vcodec^=vp9][height>=2160][fps>30]/bestvideo[vcodec^=avc1][height>=2160][fps>30]/bestvideo[height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=2160]/bestvideo[vcodec^=vp9.2][height>=2160]/bestvideo[vcodec^=vp9][height>=2160]/bestvideo[vcodec^=avc1][height>=2160]/bestvideo[height>=2160]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec^=vp9.2][height>=1440][fps>30]/bestvideo[vcodec^=vp9][height>=1440][fps>30]/bestvideo[vcodec^=avc1][height>=1440][fps>30]/bestvideo[height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1440]/bestvideo[vcodec^=vp9.2][height>=1440]/bestvideo[vcodec^=vp9][height>=1440]/bestvideo[vcodec^=avc1][height>=1440]/bestvideo[height>=1440]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec^=vp9.2][height>=1080][fps>30]/bestvideo[vcodec^=vp9][height>=1080][fps>30]/bestvideo[vcodec^=avc1][height>=1080][fps>30]/bestvideo[height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec^=vp9.2][height>=1080]/bestvideo[vcodec^=vp9][height>=1080]/bestvideo[vcodec^=avc1][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec^=vp9.2][height>=720][fps>30]/bestvideo[vcodec^=vp9][height>=720][fps>30]/bestvideo[vcodec^=avc1][height>=720][fps>30]/bestvideo[height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec^=vp9.2][height>=720]/bestvideo[vcodec^=vp9][height>=720]/bestvideo[vcodec^=avc1][height>=720]/bestvideo[height>=720]/bestvideo[vcodec^=av01][height>=480][fps>30]/bestvideo[vcodec^=vp9.2][height>=480][fps>30]/bestvideo[vcodec^=vp9][height>=480][fps>30]/bestvideo[vcodec^=avc1][height>=480][fps>30]/bestvideo[height>=480][fps>30]/bestvideo[vcodec^=av01][height>=480]/bestvideo[vcodec^=vp9.2][height>=480]/bestvideo[vcodec^=vp9][height>=480]/bestvideo[vcodec^=avc1][height>=480]/bestvideo[height>=480]/bestvideo[vcodec^=av01][height>=360][fps>30]/bestvideo[vcodec^=vp9.2][height>=360][fps>30]/bestvideo[vcodec^=vp9][height>=360][fps>30]/bestvideo[vcodec^=avc1][height>=360][fps>30]/bestvideo[height>=360][fps>30]/bestvideo[vcodec^=av01][height>=360]/bestvideo[vcodec^=vp9.2][height>=360]/bestvideo[vcodec^=vp9][height>=360]/bestvideo[vcodec^=avc1][height>=360]/bestvideo[height>=360]/bestvideo[vcodec^=avc1][height>=240][fps>30]/bestvideo[vcodec^=av01][height>=240][fps>30]/bestvideo[vcodec^=vp9.2][height>=240][fps>30]/bestvideo[vcodec^=vp9][height>=240][fps>30]/bestvideo[height>=240][fps>30]/bestvideo[vcodec^=avc1][height>=240]/bestvideo[vcodec^=av01][height>=240]/bestvideo[vcodec^=vp9.2][height>=240]/bestvideo[vcodec^=vp9][height>=240]/bestvideo[height>=240]/bestvideo[vcodec^=avc1][height>=144][fps>30]/bestvideo[vcodec^=av01][height>=144][fps>30]/bestvideo[vcodec^=vp9.2][height>=144][fps>30]/bestvideo[vcodec^=vp9][height>=144][fps>30]/bestvideo[height>=144][fps>30]/bestvideo[vcodec^=avc1][height>=144]/bestvideo[vcodec^=av01][height>=144]/bestvideo[vcodec^=vp9.2][height>=144]/bestvideo[vcodec^=vp9][height>=144]/bestvideo[height>=144]/bestvideo)+(bestaudio[acodec^=opus]/bestaudio)/best" --add-metadata --parse-metadata "%(title)s:%(meta_title)s" --parse-metadata "%(uploader)s:%(meta_artist)s" --write-description --write-info-json --write-annotations --write-thumbnail --embed-thumbnail --all-subs --embed-subs --check-formats -N 5 -P "temp:$TMPDIR/yt" -P "home:./" --output "%(uploader)s/%(upload_date)s - %(title)s - [%(id)s]/%(title)s - %(uploader)s - %(upload_date)s [%(id)s].%(ext)s" --merge-output-format "mkv" --write-comments https://www.youtube.com/watch\?v\=KIQASNa-4Og
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--format', '(bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec^=vp9.2][height>=4320][fps>30]/bestvideo[vcodec^=vp9][height>=4320][fps>30]/bestvideo[vcodec^=avc1][height>=4320][fps>30]/bestvideo[height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=4320]/bestvideo[vcodec^=vp9.2][height>=4320]/bestvideo[vcodec^=vp9][height>=4320]/bestvideo[vcodec^=avc1][height>=4320]/bestvideo[height>=4320]/bestvideo[vcodec^=av01][height>=2880][fps>30]/bestvideo[vcodec^=vp9.2][height>=2880][fps>30]/bestvideo[vcodec^=vp9][height>=2880][fps>30]/bestvideo[vcodec^=avc1][height>=2880][fps>30]/bestvideo[height>=2880][fps>30]/bestvideo[vcodec^=av01][height>=2880]/bestvideo[vcodec^=vp9.2][height>=2880]/bestvideo[vcodec^=vp9][height>=2880]/bestvideo[vcodec^=avc1][height>=2880]/bestvideo[height>=2880]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec^=vp9.2][height>=2160][fps>30]/bestvideo[vcodec^=vp9][height>=2160][fps>30]/bestvideo[vcodec^=avc1][height>=2160][fps>30]/bestvideo[height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=2160]/bestvideo[vcodec^=vp9.2][height>=2160]/bestvideo[vcodec^=vp9][height>=2160]/bestvideo[vcodec^=avc1][height>=2160]/bestvideo[height>=2160]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec^=vp9.2][height>=1440][fps>30]/bestvideo[vcodec^=vp9][height>=1440][fps>30]/bestvideo[vcodec^=avc1][height>=1440][fps>30]/bestvideo[height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1440]/bestvideo[vcodec^=vp9.2][height>=1440]/bestvideo[vcodec^=vp9][height>=1440]/bestvideo[vcodec^=avc1][height>=1440]/bestvideo[height>=1440]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec^=vp9.2][height>=1080][fps>30]/bestvideo[vcodec^=vp9][height>=1080][fps>30]/bestvideo[vcodec^=avc1][height>=1080][fps>30]/bestvideo[height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec^=vp9.2][height>=1080]/bestvideo[vcodec^=vp9][height>=1080]/bestvideo[vcodec^=avc1][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec^=vp9.2][height>=720][fps>30]/bestvideo[vcodec^=vp9][height>=720][fps>30]/bestvideo[vcodec^=avc1][height>=720][fps>30]/bestvideo[height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec^=vp9.2][height>=720]/bestvideo[vcodec^=vp9][height>=720]/bestvideo[vcodec^=avc1][height>=720]/bestvideo[height>=720]/bestvideo[vcodec^=av01][height>=480][fps>30]/bestvideo[vcodec^=vp9.2][height>=480][fps>30]/bestvideo[vcodec^=vp9][height>=480][fps>30]/bestvideo[vcodec^=avc1][height>=480][fps>30]/bestvideo[height>=480][fps>30]/bestvideo[vcodec^=av01][height>=480]/bestvideo[vcodec^=vp9.2][height>=480]/bestvideo[vcodec^=vp9][height>=480]/bestvideo[vcodec^=avc1][height>=480]/bestvideo[height>=480]/bestvideo[vcodec^=av01][height>=360][fps>30]/bestvideo[vcodec^=vp9.2][height>=360][fps>30]/bestvideo[vcodec^=vp9][height>=360][fps>30]/bestvideo[vcodec^=avc1][height>=360][fps>30]/bestvideo[height>=360][fps>30]/bestvideo[vcodec^=av01][height>=360]/bestvideo[vcodec^=vp9.2][height>=360]/bestvideo[vcodec^=vp9][height>=360]/bestvideo[vcodec^=avc1][height>=360]/bestvideo[height>=360]/bestvideo[vcodec^=avc1][height>=240][fps>30]/bestvideo[vcodec^=av01][height>=240][fps>30]/bestvideo[vcodec^=vp9.2][height>=240][fps>30]/bestvideo[vcodec^=vp9][height>=240][fps>30]/bestvideo[height>=240][fps>30]/bestvideo[vcodec^=avc1][height>=240]/bestvideo[vcodec^=av01][height>=240]/bestvideo[vcodec^=vp9.2][height>=240]/bestvideo[vcodec^=vp9][height>=240]/bestvideo[height>=240]/bestvideo[vcodec^=avc1][height>=144][fps>30]/bestvideo[vcodec^=av01][height>=144][fps>30]/bestvideo[vcodec^=vp9.2][height>=144][fps>30]/bestvideo[vcodec^=vp9][height>=144][fps>30]/bestvideo[height>=144][fps>30]/bestvideo[vcodec^=avc1][height>=144]/bestvideo[vcodec^=av01][height>=144]/bestvideo[vcodec^=vp9.2][height>=144]/bestvideo[vcodec^=vp9][height>=144]/bestvideo[height>=144]/bestvideo)+(bestaudio[acodec^=opus]/bestaudio)/best', '--add-metadata', '--parse-metadata', '%(title)s:%(meta_title)s', '--parse-metadata', '%(uploader)s:%(meta_artist)s', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '--embed-thumbnail', '--all-subs', '--embed-subs', '--check-formats', '-N', '5', '-P', 'temp:/tmp/yt', '-P', 'home:./', '--output', '%(uploader)s/%(upload_date)s - %(title)s - [%(id)s]/%(title)s - %(uploader)s - %(upload_date)s [%(id)s].%(ext)s', '--merge-output-format', 'mkv', '--write-comments', 'https://www.youtube.com/watch?v=KIQASNa-4Og']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-13-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=KIQASNa-4Og
[youtube] KIQASNa-4Og: Downloading webpage
[youtube] KIQASNa-4Og: Downloading android player API JSON
[youtube] KIQASNa-4Og: Downloading MPD manifest
[youtube] KIQASNa-4Og: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Searching for '(?P<meta_title>.+)' in '%(title)s'
[MetadataParser] Parsed meta_title from '%(title)s': 'DJ Many - Anyway (Official Music Video) | Chopped & Screwed'
[debug] Searching for '(?P<meta_artist>.+)' in '%(uploader)s'
[MetadataParser] Parsed meta_artist from '%(uploader)s': 'Almighty DJ Chiszle'
[youtube] Downloading comment section API JSON
[youtube] Downloading ~4 comments
[youtube] Sorting comments by newest first
[youtube] Downloading comment API JSON page 1 (0/4)
[youtube] Extracted 4 comments
[info] Testing format 302
[dashsegments] Total fragments: 1
[download] Destination: /tmp/yt/tmpjps3vvdg.tmp
[download] 100% of 704.00B in 00:00
[info] Testing format 251
[download] Destination: /tmp/yt/tmpauuzb3kf.tmp
[download] 100% of 10.00KiB in 00:00
[info] KIQASNa-4Og: Downloading 1 format(s): 302+251
[info] Writing video description to: ./Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].description
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: /tmp/yt/Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].webp
[info] Writing video metadata as JSON to: ./Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].info.json
WARNING: There are no annotations to write.
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1658168509/ei/XVDVYtfvC-m1xN8PpvG3kAw/ip/2a01%3Ae0a%3A44e%3A5a60%3A3e7c%3A3fff%3Afef3%3A7005/id/28840048d6bee0e8/source/youtube/requiressl/yes/playback_host/rr6---sn-25glen7l.googlevideo.com/mh/wC/mm/31%2C29/mn/sn-25glen7l%2Csn-25ge7nz6/ms/au%2Crdu/mv/m/mvi/6/pl/52/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1121250/spc/lT-Khgx222wWXNmcThvGzAUmUJb0838/vprv/1/mt/1658146614/fvip/4/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cspc%2Cvprv%2Citag/sig/AOq0QJ8wRAIgN6Z_6MXc-ct_yVmvjShgImN_woB4Jw_H71ojrrRKfDwCICgC5Ee-oL60ccT4L13Ib9VMiQa2YE_1b1AEE7aGvuvv/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgEAdq7nrh5GdRRKv14tAK0bDWHpeiOL1t6gDYlIFVnlUCIQC4-sx0uZ9H_XgMMHaSZaC3_ltadffAqCar7xx9bF4_oA%3D%3D"
[dashsegments] Total fragments: 89
[download] Destination: /tmp/yt/Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].f302.webm
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download] 100% of 107.55MiB in 00:03
[debug] Invoking http downloader on "https://rr4---sn-25ge7nz6.googlevideo.com/videoplayback?expire=1658168509&ei=XVDVYsfoIcWixN8PpKOJkAw&ip=2a01%3Ae0a%3A44e%3A5a60%3A3e7c%3A3fff%3Afef3%3A7005&id=o-ABf7FtZ4gpQD-NfT6lW2DqxVLofHOd2EN_w_Mksw9Dw0&itag=251&source=youtube&requiressl=yes&mh=wC&mm=31%2C29&mn=sn-25ge7nz6%2Csn-25glen7l&ms=au%2Crdu&mv=m&mvi=4&pl=52&initcwndbps=1121250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=8299071&otfp=1&dur=464.621&lmt=1563231904089267&mt=1658146614&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgE47H3sV0j0UvwgpQJuI_tDzEFMVunPdf8pFcPaZNW-ICIBBC-kmaFjKc6WxZZ0mLirL9VVaF1UnKmvAwWORzZ-cl&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgCoB_Syqr7_V1IfgZ3sdThFP350_v-2ugGlj5FHwUUKcCIQDoxWXeIxrd_DHfwCeIhfB2ABJHNL9PAUJgDkyGTMZaaQ%3D%3D"
[download] Destination: /tmp/yt/Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].f251.webm
[download] 100% of 7.91MiB in 00:00
[Merger] Merging formats into "/tmp/yt/Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/tmp/yt/Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].f302.webm' -i 'file:/tmp/yt/Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:/tmp/yt/Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].temp.mkv'
[debug] ffmpeg version 4.3.4-0+deb11u1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, matroska,webm, from 'file:/tmp/yt/Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].f302.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 88 
                    : Segment-Durations-Ms: 5333,5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),533 
                    :  
                    : 
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1280x720, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:/tmp/yt/Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:07:44.62, start: -0.007000, bitrate: 142 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, matroska, to 'file:/tmp/yt/Almighty DJ Chiszle/20180131 - DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - [KIQASNa-4Og]/DJ Many - Anyway (Official Music Video) _ Chopped & Screwed - Almighty DJ Chiszle - 20180131 [KIQASNa-4Og].temp.mkv':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 88 
                    : Segment-Durations-Ms: 5333,5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),533 
                    :  
                    : 
    encoder         : Lavf58.45.100
    Stream #0:0(eng): Video: vp9 (Profile 0) (VP90 / 0x30395056), yuv420p(tv, bt709/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus ([255][255][255][255] / 0xFFFFFFFF), 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska @ 0x55d574221480] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5350 >= 5333
av_interleaved_write_frame(): Invalid argument
frame=  323 fps=0.0 q=-1.0 Lsize=    1320kB time=00:00:05.36 bitrate=2016.5kbits/s speed=1.64e+03x    
video:1239kB audio:96kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "/home/corentin/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3236, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/corentin/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3406, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/corentin/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3388, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/corentin/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3367, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/corentin/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/corentin/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 126, in wrapper
    return func(self, info)
  File "/home/corentin/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 816, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/corentin/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 313, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/corentin/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 351, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by Lesmiscore** [comment]
Try using ffmpeg from https://github.com/BtbN/FFmpeg-Builds

**Comment by CorentinB** [comment]
> Try using ffmpeg from https://github.com/BtbN/FFmpeg-Builds

Thanks! It is indeed fixing the issue. I guess it's purely an ffmpeg thing then.
Closing.

**Comment by 96312** [comment]
@CorentinB Hi, I faced a similar problem. Which version did you download from the builds page? There's a lot of options there, I use Windows.
