### ISSUE TITLE
music.163.com is broken

### ISSUE THREAD

**Issue by eniraa** [yt-dlp/yt-dlp#4388]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA (Los Angeles)

### Provide a description that is worded well enough to be understood

`yt-dlp` claims that there is no version of the video available. Since it is playable on the browser, there should be a way to download it; I am not using any account or VPN to access this. 

It could be fixed by fixing the extractor. For instance, the extractor should get `http://m8.music.126.net/20220719122521/8e9f1fee5fd0f87069933704bb744f5e/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/11952787098/b0e1/e9ad/e935/de90f6452478358e9eb06b165ff8f823.mp3` from `https://music.163.com/#/program?id=2495371686`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-x', '-vU', 'https://music.163.com/#/program?id=2495371686']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.9.12 (CPython 64bit) - macOS-12.3.1-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [netease:program] Extracting URL: https://music.163.com/#/program?id=2495371686
[netease:program] 2495371686: Downloading program info
[netease:program] 1901037857: Checking song URL
[netease:program] 1901037857: song URL is invalid, skipping: <urlopen error timed out>
[netease:program] 1901037857: Checking song URL
[netease:program] 1901037857: song URL is invalid, skipping: <urlopen error timed out>
[netease:program] 1901037857: Checking song URL
[netease:program] 1901037857: song URL is invalid, skipping: <urlopen error timed out>
[netease:program] 1901037857: Checking song URL
[netease:program] 1901037857: song URL is invalid, skipping: <urlopen error timed out>
WARNING: "id" field is not a string - forcing string conversion, there is an error in extractor
ERROR: [netease:program] 1901037857: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2481, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1002, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [netease:program] 1901037857: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by lockmatrix** [comment]
I can reproduce this, I think this extractor is broken now

**Comment by lockmatrix** [comment]
The url fetching api is encrypted
```
curl 'https://music.163.com/weapi/song/enhance/player/url/v1?csrf_token=' \
  -H 'authority: music.163.com' \
  -H 'accept: */*' \
  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'origin: https://music.163.com' \
  -H 'referer: https://music.163.com/' \
  --data-raw 'params=NaDg8IJv3w0n%2BBUqNqAaW7BCbJtYiTn7PbZwn7g4gB19embQCYz%2BprLh6MTeP70FjSUtJ%2FNOa%2FSm3wKzogdIWGY0YSXBNDvvirNk2g4W%2B%2FtuLxA90UE%2FGeekxn%2BpJGCWw7tbDkVc8497i8kr0LQf%2FQ%3D%3D&encSecKey=366ab2599fd1ac049cab25166bd82933fd9562b2d3039fac5ca68d87f03efe9d6fee4ab4ad5b795cc516aa6730cdd522df472c475a1d6a1013f81f728435ed84dda3f0da11ac4186f7838eb802ae2d3e507317c2743c1b5e2b6b686958c2a711c0f431d8847f2825c49d3e79273f7378d002d59c31604fdeec5981b4298eaa65' \
  --compressed
```

return
```
{"data":[{"id":1901037857,"url":"http://m10.music.126.net/20220719144536/482beeeb0288b9f937c6d67bbb9d8be2/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/11952787098/b0e1/e9ad/e935/de90f6452478358e9eb06b165ff8f823.mp3","br":128000,"size":4572099,"md5":"de90f6452478358e9eb06b165ff8f823","code":200,"expi":1200,"type":"mp3","gain":0.0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":null,"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0}],"code":200}
```

**Comment by slowthgt** [comment]
Issue is also present on the album extractor:

```yt-dlp -x -vU https://music.163.com/#/album?id=121309021
[debug] Command-line config: ['-x', '-vU', 'https://music.163.com/#/album?id=121309021']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [netease:album] Extracting URL: https://music.163.com/#/album?id=121309021
[netease:album] 121309021: Downloading album data
ERROR: 121309021: An extractor error has occurred. (caused by KeyError('album')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\neteasemusic.py", line 196, in _real_extract
KeyError: 'album'

**Comment by qq516249940** [comment]
me too.
```bash
yt-dlp https://music.163.com/\#/song\?id\=488249475
[netease:song] 488249475: Downloading song info
[netease:song] 488249475: Checking song URL
[netease:song] 488249475: song URL is invalid, skipping: <urlopen error timed out>
[netease:song] 488249475: Checking song URL
[netease:song] 488249475: song URL is invalid, skipping: <urlopen error timed out>
[netease:song] 488249475: Checking song URL
[netease:song] 488249475: song URL is invalid, skipping: <urlopen error timed out>
[netease:song] 488249475: Checking song URL
[netease:song] 488249475: song URL is invalid, skipping: <urlopen error timed out>
[netease:song] 488249475: Checking song URL
[netease:song] 488249475: song URL is invalid, skipping: <urlopen error timed out>
[netease:song] 488249475: Checking song URL
[netease:song] 488249475: song URL is invalid, skipping: <urlopen error timed out>
[netease:song] 488249475: Checking song URL
[netease:song] 488249475: song URL is invalid, skipping: <urlopen error timed out>

```

**Comment by mochaaP** [comment]
<https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/netease.py> This still works for me. Maybe someone can port it to `yt-dlp`?
