### ISSUE TITLE
BBC Rewind

### ISSUE THREAD

**Issue by DavidCWGA** [yt-dlp/yt-dlp#4389]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United Kingdom

### Example URLs

Single video: https://www.bbcrewind.co.uk/asset/5acb6b2bdae8bd001aa0c3f2?categories=scienceAndTechnology

Playlist: https://www.bbcrewind.co.uk/search?categories=scienceAndTechnology

### Provide a description that is worded well enough to be understood

BBC Rewind is a new site from the BBC containing archive documentary footage. It probably uses the same player as other BBC sites, but it has a new domain.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.bbcrewind.co.uk/asset/5acb6b2bdae8bd001aa0c3f2?categories=scienceAndTechnology']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-16-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://www.bbcrewind.co.uk/asset/5acb6b2bdae8bd001aa0c3f2?categories=scienceAndTechnology
[generic] 5acb6b2bdae8bd001aa0c3f2?categories=scienceAndTechnology: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 5acb6b2bdae8bd001aa0c3f2?categories=scienceAndTechnology: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.bbcrewind.co.uk/asset/5acb6b2bdae8bd001aa0c3f2?categories=scienceAndTechnology
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.bbcrewind.co.uk/asset/5acb6b2bdae8bd001aa0c3f2?categories=scienceAndTechnology
```

**Comment by dirkf** [comment]
No, it's totally different ... The people responsible plainly see HTML as a bit of a hindrance in the process of sending information to viewers, so it's all API-based.

The metadata for https://www.bbcrewind.co.uk/asset/5acb6b2bdae8bd001aa0c3f2 comes from https://www.bbcrewind.co.uk/api/svc/api/v2/assets/5acb6b2bdae8bd001aa0c3f2, including a video URL.

The metadata for the search URL comes from https://www.bbcrewind.co.uk/api/svc/api/v2/assets/search?categories=scienceAndTechnology, or, for full results, https://www.bbcrewind.co.uk/_next/data/0eJEpo-5CI4kfkT5EziVV/en/search.json?categories=scienceAndTechnology&includedGLFilters=distress,violence,sex,language.

**Comment by gaussey** [comment]
Could this be looked at again? The current url is : https://discover.bbcrewind.co.uk/
