### ISSUE TITLE
[Question] Youtube video with lots of comments (list has no attribute get)

### ISSUE THREAD

**Issue by JamoDevNich** [yt-dlp/yt-dlp#439]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to download [this video](https://www.youtube.com/watch?v=m6pJd6O_NT0) with comments, using yt-dlp version 2021.06.23 installed with pip, python 3.8.5.  

The comment extractor fails on the last few thousand comments with `'list' object has no attribute 'get'`. I did notice a similar issue reported where an urllib error was the cause, however I'm doubtful that's related to this error.    

I'm assuming this error might have something to do with new comments being added to the video during the fetching process, but I haven't looked at the comment extraction code so this is just speculation. At time of writing the comments have gone from 30428 to 30512.  

Would I be better off leaving behind the comments, or is there another method I could consider to grab them?  

Log excerpt and cli args are below  

```
app_1  | [youtube] Downloading comment page 729 (28329/30428)
app_1  | [youtube]     Downloading comment reply thread 1 (28338/30428)
app_1  | [youtube]     Downloading comment reply thread 2 (28342/30428)
app_1  | [youtube]     Downloading comment reply thread 3 (28346/30428)
app_1  | [youtube]        Downloading comment replies page 1 (28356/30428)
app_1  | [youtube]     Downloading comment reply thread 4 (28359/30428)
app_1  | [youtube]     Downloading comment reply thread 5 (28361/30428)
app_1  | [youtube]        Downloading comment replies page 1 (28371/30428)
app_1  | [youtube] Downloading comment page 730 (28382/30428)
app_1  | [youtube]     Downloading comment reply thread 1 (28386/30428)
app_1  | [youtube]     Downloading comment reply thread 2 (28392/30428)
app_1  | [youtube]     Downloading comment reply thread 3 (28395/30428)
app_1  | [youtube]     Downloading comment reply thread 4 (28402/30428)
app_1  | [youtube]     Downloading comment reply thread 5 (28407/30428)
app_1  | [youtube]     Downloading comment reply thread 6 (28411/30428)
app_1  | [youtube]     Downloading comment reply thread 7 (28413/30428)
app_1  | [youtube]     Downloading comment reply thread 8 (28415/30428)
app_1  | [youtube]     Downloading comment reply thread 9 (28417/30428)
app_1  | ERROR: 'list' object has no attribute 'get'
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1138, in wrapper
app_1  |     return func(self, *args, **kwargs)
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1174, in __extract_info
app_1  |     return self.process_ie_result(ie_result, download, extra_info)
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1211, in process_ie_result
app_1  |     ie_result = self.process_video_result(ie_result, download=download)
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2198, in process_video_result
app_1  |     self.process_info(new_info)
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2358, in process_info
app_1  |     self.post_extract(info_dict)
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2860, in post_extract
app_1  |     actual_post_extract(info_dict or {})
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2852, in actual_post_extract
app_1  |     extra = post_extractor().items()
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 2550, in <lambda>
app_1  |     info['__post_extractor'] = lambda: self._extract_comments(ytcfg, video_id, contents, webpage, xsrf_token)
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 1874, in _extract_comments
app_1  |     for comment in comment_iter:
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 1849, in _comment_entries
app_1  |     for entry in known_continuation_renderers[key](continuation_renderer):
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 1701, in extract_thread
app_1  |     for reply_comment in comment_entries_iter:
app_1  |   File "/usr/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 1785, in _comment_entries
app_1  |     if browse.get('reload'):
app_1  | AttributeError: 'list' object has no attribute 'get'
```  

CLI args set by the downloader interface:  
```
--exec
--write-info-json
--prefer-ffmpeg
--ffmpeg-location 
--output
--format
--extract-audio
--download-archive
--cache-dir
```  
  
CLI args set by myself:  
```
--write-description
--write-annotations
--write-all-thumbnails
--get-comments
--all-subs
--sub-format srt
--merge-output-format mkv
--add-metadata
--xattrs
--xattr-set-filesize
--no-overwrites
--no-continue
--ignore-errors
```

**Comment by JamoDevNich** [comment]
Video downloaded successfully on the third try! It still didn't get all the comments but it at least was successful this time: `Downloaded 30418/30512 comments`  

Closing this as to not clutter up the issues tab. Would be nice to find out what caused this but I'm doubtful as to how reproducible this is.

**Comment by pukkandan** [comment]
> Downloaded 30418/30512 comments

The number on the right is the estimate youtube provides. It may be slightly off

---

I am re-opening the issue so that I remember to investigate
