### ISSUE TITLE
yt-dlp automatically puts 'eng' in Language field even for non-english music.

### ISSUE THREAD

**Issue by Rexadev** [yt-dlp/yt-dlp#4392]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

S

### Provide a description that is worded well enough to be understood

Example German - `https://www.youtube.com/watch?v=yAKhzYT7K_U`

It must be related to yt-dlp automatically parsing metadata from description.

My config file

```
-f 251
--audio-format "opus" -x

--output "Downloads/Music/%(title)s.%(ext)s"

--write-sub --write-auto-sub --sub-lang en --convert-subs lrc

--embed-sub
--embed-thumbnail

--embed-metadata
--xattrs
--embed-chapters
--parse-metadata "webpage_url:%(meta_SOURCE)s"
--parse-metadata ":(?P<meta_purl>)"

--geo-bypass-country US
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--config-location', 'D:\\PATH*\\youtube-dl\\youtubedl/config/music.conf', 'URL*']
[debug] | Config "D:\PATH*\youtube-dl\youtubedl/config/music.conf": ['--verbose', '-f', '251', '--audio-format', 'opus', '-x', '--output', 'Downloads/Music/%(artist)s/%(title)s.%(ext)s', '--write-sub', '--write-auto-sub', '--sub-lang', 'en', '--convert-subs', 'lrc', '--embed-sub', '--embed-thumbnail', '--embed-metadata', '--embed-chapters', '--parse-metadata', 'webpage_url:%(meta_SOURCE)s', '--parse-metadata', ':(?P<meta_purl>)', '--compat-options', 'abort-on-error', '--no-overwrites', '--geo-bypass-country', 'US', '--no-overwrites', '--no-playlist']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Compatibility options: abort-on-error
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Using fake IP 6.15.209.139 (US) as X-Forwarded-For
[debug] [youtube] Extracting URL: URL*
[youtube] TUVcZfQe-Kw: Downloading webpage
[youtube] TUVcZfQe-Kw: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Searching for '(?P<meta_SOURCE>.+)' in '%(webpage_url)s'
[MetadataParser] Parsed meta_SOURCE from '%(webpage_url)s': 'URL*'
[debug] Searching for '(?P<meta_purl>)' in ''
[MetadataParser] Parsed meta_purl from '': ''
[info] TUVcZfQe-Kw: Downloading 1 format(s): 251
[info] Downloading video thumbnail 45 ...
WARNING: Unable to download video thumbnail 45: HTTP Error 404: Not Found
[info] Downloading video thumbnail 44 ...
WARNING: Unable to download video thumbnail 44: HTTP Error 404: Not Found
[info] Downloading video thumbnail 43 ...
WARNING: Unable to download video thumbnail 43: HTTP Error 404: Not Found
[info] Downloading video thumbnail 42 ...
WARNING: Unable to download video thumbnail 42: HTTP Error 404: Not Found
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: Downloads\Music\NA\Dua Lipa - Levitating Featuring DaBaby (Official Music Video).webp
[SubtitlesConvertor] Converting subtitles
[download] Downloads\Music\NA\Dua Lipa - Levitating Featuring DaBaby (Official Music Video).opus has already been downloaded
[debug] ffmpeg command line: ffprobe -show_streams "file:Downloads\Music\NA\Dua Lipa - Levitating Featuring DaBaby (Official Music Video).opus"
[ExtractAudio] Not converting audio Downloads\Music\NA\Dua Lipa - Levitating Featuring DaBaby (Official Music Video).opus; file is already in target format opus
[EmbedSubtitle] Subtitles can only be embedded in mp4, mov, m4a, webm, mkv, mka files
[Metadata] Adding metadata to "Downloads\Music\NA\Dua Lipa - Levitating Featuring DaBaby (Official Music Video).opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Downloads\Music\NA\Dua Lipa - Levitating Featuring DaBaby (Official Music Video).opus" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=Dua Lipa - Levitating Featuring DaBaby (Official Music Video)" -metadata "date=20201002" -metadata "description=The official music video for Dua Lipa - Levitating featuring @DaBaby

DESCRIPTION*

#DuaLipa #Levitating #DaBaby #FutureNostalgia" -metadata "purl=" -metadata "comment=URL*" -metadata "artist=Dua Lipa" -metadata "SOURCE=URL*" -movflags "+faststart" "file:Downloads\Music\NA\Dua Lipa - Levitating Featuring DaBaby (Official Music Video).temp.opus"
[debug] ffmpeg version 5.0.1-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[ogg @ 0000014cc38488c0] 4692 bytes of comment header remain
Input #0, ogg, from 'file:Downloads\Music\NA\Dua Lipa - Levitating Featuring DaBaby (Official Music Video).opus':
  Duration: 00:03:50.12, start: 0.000000, bitrate: 142 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavf59.16.100
      title           : Dua Lipa - Levitating Featuring DaBaby (Official Music Video)
      date            : 20201002
      synopsis        : The official music video for Dua Lipa - Levitating featuring @DaBaby
                      :
                      : Taken from her second studio album 'Future Nostalgia' released in 2020, which featured the hit singles 'Don't Start Now', 'Physical', 'Break My Heart', 'Hallucinate' & 'Levitating'
                      :
                      : Get the album Future Nostalgia : https://dualipa.co/futurenostalgia
                      :
                      : Subscribe to the Dua Lipa channel for all the best and latest official music videos, behind the scenes and live performances.
                      : https://www.youtube.com/channel/UC-J-KZfRV8c13fOCkhXdLiQ?sub_confirmation=1
                      :
                      : See more official videos from Dua Lipa here:
                      : https://www.youtube.com/playlist?list=PLNrotoZZ8BaoXT_LJuwEyESQlctWNDCwD
                      :
                      : Listen to more from the album 'Future Nostalgia' :
                      : https://www.youtube.com/playlist?list=PLNrotoZZ8BaouNABcO_A9Xkn_Nkz0PT11
                      :
                      : Follow Dua Lipa:
                      : Instagram:  https://dualipa.co/instagram
                      : Facebook: http://dualipa.co/facebook
                      : TikTok: https://www.tiktok.com/@dualipaofficial
                      : Twitter: http://dualipa.co/twitter
                      : YouTube: https://dualipa.co/youtube
                      :
                      : About Dua Lipa:
                      : Born and raised in London to Kosovar-Albanian parents Dua Lipa signed to Warner Records in 2015, releasing her self titled debut in 2017 which featured the hit singles, 'Be The One', 'IDGAF', 'Hotter Than Hell' & her first UK #1 hit 'New Rules'.
                      :
                      : Critical success soon followed as Dua Lipa picked up Brit Awards for 'Best Female Solo Artist' and 'Best British Breakthrough Act' as well as Grammy Awards for 'Best New Artist' and 'Best Dance Recording' for the track 'Electricity' in collaboration with
                      :
                      : Her second internationally acclaimed studio album 'Future Nostalgia' was released in 2020 and included the hit singles 'Don't Start Now, 'Break My Heart', 'Hallucinate' and 'Levitating', with the remix album 'Club Future Nostalgia' following shortly after
                      :
                      : #DuaLipa #Levitating #DaBaby #FutureNostalgia
      comment         : URL*
      artist          : Dua Lipa
      SOURCE          : URL*
  Stream #0:1: Video: png, rgb24(pc), 640x480, 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
[opus @ 0000014cc384c180] Unsupported codec id in stream 1
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 --
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)


ERROR: Postprocessing:   Stream #0:1 -> #0:1 (copy)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3236, in process_info
  File "yt_dlp\YoutubeDL.py", line 3406, in post_process
  File "yt_dlp\YoutubeDL.py", line 3388, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3367, in run_pp
  File "yt_dlp\postprocessor\common.py", line 25, in run
  File "yt_dlp\postprocessor\common.py", line 126, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 692, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 313, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 351, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:1 -> #0:1 (copy)
```

**Comment by pukkandan** [comment]
You seem to be using some other program and not yt-dlp since the verbose log came out as NA

**Comment by pukkandan** [comment]
Why do you think yt-dlp is setting language? It doesnt look like it from the log
