### ISSUE TITLE
[Question] YouTube says playlist does not exist?

### ISSUE THREAD

**Issue by schmitmd** [yt-dlp/yt-dlp#440]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I feel like I've got to be doing something wrong that's very simple, but I'm getting a "The playlist does not exist" error and I'm not sure where to go from here.  Can anyone point me in the right direction?
```
[www@yt-down ~]$ yt-dlp --verbose --cookies ~/.cookies.txt "https://www.youtube.com/playlist?list=PLh08BsEKXQyvCx1UuFQFlBMtTjP0dVwtB"
[debug] User config file: /media/Nextcloud/.config/yt-dlp/config
[debug] User config: ['--add-metadata', '--ignore-errors', '--write-thumbnail', '--recode-video', 'mkv', '--autonumber-start', '0001', '--no-overwrites', '-o', '/media/Nextcloud/files/yt-dlp/%(title)s.%(ext)s']
[debug] Command-line config: ['--verbose', '--cookies', '/media/Nextcloud/.cookies.txt', 'https://www.youtube.com/playlist?list=PLh08BsEKXQyvCx1UuFQFlBMtTjP0dVwtB']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.06.23
[debug] Python version 3.7.9 (CPython 64bit) - FreeBSD-13.0-RELEASE-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLh08BsEKXQyvCx1UuFQFlBMtTjP0dVwtB
[youtube:tab] PLh08BsEKXQyvCx1UuFQFlBMtTjP0dVwtB: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLh08BsEKXQyvCx1UuFQFlBMtTjP0dVwtB
[youtube:tab] PLh08BsEKXQyvCx1UuFQFlBMtTjP0dVwtB: Downloading API JSON with unavailable videos
WARNING: [youtube:tab] YouTube said: The playlist does not exist.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
[download] Downloading playlist: Poly Extras
[youtube:tab] PLh08BsEKXQyvCx1UuFQFlBMtTjP0dVwtB page 1: Downloading API JSON
ERROR: YouTube said: The playlist does not exist.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yt_dlp-2021.6.23-py3.7.egg/yt_dlp/YoutubeDL.py", line 1138, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp-2021.6.23-py3.7.egg/yt_dlp/YoutubeDL.py", line 1174, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp-2021.6.23-py3.7.egg/yt_dlp/YoutubeDL.py", line 1279, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp-2021.6.23-py3.7.egg/yt_dlp/YoutubeDL.py", line 1361, in __process_playlist
    entry = ie_entries[i - 1]
  File "/usr/local/lib/python3.7/site-packages/yt_dlp-2021.6.23-py3.7.egg/yt_dlp/utils.py", line 4017, in __getitem__
    self.__cache.extend(itertools.islice(self.__iterable, n))
  File "/usr/local/lib/python3.7/site-packages/yt_dlp-2021.6.23-py3.7.egg/yt_dlp/extractor/youtube.py", line 3659, in _smuggle_data
    for entry in entries:
  File "/usr/local/lib/python3.7/site-packages/yt_dlp-2021.6.23-py3.7.egg/yt_dlp/extractor/youtube.py", line 3287, in _entries
    check_get_keys=('continuationContents', 'onResponseReceivedActions', 'onResponseReceivedEndpoints'))
  File "/usr/local/lib/python3.7/site-packages/yt_dlp-2021.6.23-py3.7.egg/yt_dlp/extractor/youtube.py", line 3616, in _extract_response
    self._extract_and_report_alerts(response, expected=False)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp-2021.6.23-py3.7.egg/yt_dlp/extractor/youtube.py", line 3535, in _extract_and_report_alerts
    return self._report_alerts(self._extract_alerts(data), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp-2021.6.23-py3.7.egg/yt_dlp/extractor/youtube.py", line 3532, in _report_alerts
    raise ExtractorError('YouTube said: %s' % errors[-1][1], expected=expected)
yt_dlp.utils.ExtractorError: YouTube said: The playlist does not exist.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
![image](https://user-images.githubusercontent.com/6623388/123169547-0c831700-d497-11eb-83c8-b2cab37a85b8.png)

**Comment by pukkandan** [comment]
I see you are using cookies. Is this a private PL? If so, try with new cookies and let me know what happens

**Comment by schmitmd** [comment]
It is indeed a private PL, and I thought I'd _just_ downloaded new cookies, but it looks like the ones I grabbed were for a different signed-in Google account.  Incognito tab and a fresh login did the trick.  Thank you so much for the guidance.  Terribly sorry to have taken your time.
