### ISSUE TITLE
here.xxx support

### ISSUE THREAD

**Issue by chriscjcj** [yt-dlp/yt-dlp#4403]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://here.xxx/index.php?video=2439416
https://here.xxx/index.php?video=4160489&clid=2327788
https://here.xxx/?cl=0
https://here.xxx/?cl=2327788
https://here.xxx/index.php?q=blondes
https://here.xxx/?act=favorites
https://here.xxx/index.php?mode=user_profile&act=history
https://here.xxx/?s=1
https://here.xxx/?s=8
https://here.xxx/?s=9
https://here.xxx/?s=11

### Provide a description that is worded well enough to be understood

**### Warning: NSFW**

yt-dlp 2022.07.18 doesn't seem to be effective on any urls at https://here.xxx/ 

A note to the kind developers of yt-dlp and the greater community: 
While it would be great to have support for this site in yt-dlp, (there are a couple of videos that would be great to save for posterity,) I fully acknowledge that that this is just yet another adult website among many. If this one isn't deemed worthy of the effort, I understand. And I continue to be grateful for all the work that's been done on the multitude of sites that _do_ function beautifully. Cheers and best wishes!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://here.xxx/index.php?video=2781821']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - macOS-12.4-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://here.xxx/index.php?video=2781821
[generic] index: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] index: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://here.xxx/index.php?video=2781821
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://here.xxx/index.php?video=2781821
```

**Comment by Bricio** [comment]
lol, for "posterity"
if anyone want to code this, it is an easy regex extract.

playlists: 
> search videos urls with `<a[^>]+\bhref=["']([^"']+video=[^"']+)["']`

video:
> get script url inside video page `<script[^>]+\bsrc=["']([^"']+embed_cdn[^"']+)["']`
> get m3u8 url inside script `sourceURL_HLS = ["']([^"']+)["']`

**Comment by pukkandan** [comment]
> A note to the kind developers of yt-dlp and the greater community:
While it would be great to have support for this site in yt-dlp, (there are a couple of videos that would be great to save for posterity,) I fully acknowledge that that this is just yet another adult website among many. If this one isn't deemed worthy of the effort, I understand. And I continue to be grateful for all the work that's been done on the multitude of sites that do function beautifully. Cheers and best wishes!

You can request for any site that contains playable videos and does not fall under https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy. However, I almost never work on site requests myself and if/when it will actually be supported depends on how much interest other devs have in implementing the extractor
