### ISSUE TITLE
Error when extracting subtitles from PlutoTV

### ISSUE THREAD

**Issue by heliosyne** [yt-dlp/yt-dlp#4413]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA and many others

### Provide a description that is worded well enough to be understood

When trying to extract either of these videos:

https://pluto.tv/en/on-demand/series/stargate-atlantis/season/2/episode/the-long-goodbye-2006-2-16
https://pluto.tv/en/on-demand/series/stargate-atlantis/season/3/episode/irresistible-2006-3-3

The video and audio extract fine, but I get this error when trying to extract the subs using --embed-subs or --write-subs:

ERROR: Parse error at position 23 (near 'MPEGTS:-6000,LOCAL:0')

That line from the .vtt.part-Frag1 file:

X-TIMESTAMP-MAP=MPEGTS:-6000,LOCAL:00:00:00.000

Compared to the same line from .vtt.part-Frag1 of an episode where the subs extract without error:

X-TIMESTAMP-MAP=MPEGTS:16000,LOCAL:00:00:00.000

Does the webvtt parser not like a negative value?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--check-formats', '--embed-subs', '--remux-video', 'mkv', 'https://pluto.tv/en/on-demand/series/stargate-atlantis/season/2/episode/the-long-goodbye-2006-2-16']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.8.13 (CPython 64bit) - FreeBSD-12.3-RELEASE-p5-amd64-64bit-ELF (libc 7)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [PlutoTV] Extracting URL: https://pluto.tv/en/on-demand/series/stargate-atlantis/season/2/episode/the-long-goodbye-2006-2-16
[PlutoTV] stargate-atlantis: Downloading JSON metadata
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 information
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 playlist
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 playlist
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 playlist
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 playlist
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 playlist
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Testing format hls-2327
[hlsnative] Downloading m3u8 manifest
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
  File "/home/melissa/.local/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/__init__.py", line 940, in main
    _exit(*variadic(_real_main(argv)))
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/__init__.py", line 932, in _real_main
    return ydl.download(all_urls)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3281, in download
    self.__download_wrapper(self.extract_info)(
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3257, in wrapper
    res = func(*args, **kwargs)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1422, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2608, in process_video_result
    formats_to_download = list(format_selector({
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2120, in selector_function
    yield from f(ctx)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2219, in final_selector
    return selector_function(ctx_copy)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2131, in selector_function
    picked_formats = list(f(ctx))
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2140, in selector_function
    for pair in itertools.product(selector_1(ctx), selector_2(ctx)):
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2209, in selector_function
    yield matches[format_idx - 1]
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/utils.py", line 2696, in __getitem__
    self._cache.extend(itertools.islice(self._iterable, n))
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2112, in _check_formats
    yield from self._check_formats(formats)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1883, in _check_formats
    success, _ = self.dl(temp_file.name, f, test=True)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2860, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/downloader/hls.py", line 82, in real_download
    self.report_error(
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 971, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 903, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


[info] Unable to download format hls-2327. Skipping...
[info] Testing format hls-2339
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 523
[download] Destination: /tmp/tmp9vynwfat.tmp
[download] 100% of 1.38MiB in 00:00
[info] Testing format hls-2327
[hlsnative] Downloading m3u8 manifest
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
  File "/home/melissa/.local/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/__init__.py", line 940, in main
    _exit(*variadic(_real_main(argv)))
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/__init__.py", line 932, in _real_main
    return ydl.download(all_urls)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3281, in download
    self.__download_wrapper(self.extract_info)(
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3257, in wrapper
    res = func(*args, **kwargs)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1422, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2608, in process_video_result
    formats_to_download = list(format_selector({
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2120, in selector_function
    yield from f(ctx)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2219, in final_selector
    return selector_function(ctx_copy)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2131, in selector_function
    picked_formats = list(f(ctx))
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2120, in selector_function
    yield from f(ctx)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2209, in selector_function
    yield matches[format_idx - 1]
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/utils.py", line 2696, in __getitem__
    self._cache.extend(itertools.islice(self._iterable, n))
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2112, in _check_formats
    yield from self._check_formats(formats)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1883, in _check_formats
    success, _ = self.dl(temp_file.name, f, test=True)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2860, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/downloader/hls.py", line 82, in real_download
    self.report_error(
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 971, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 903, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


[info] Unable to download format hls-2327. Skipping...
[info] Testing format hls-2339
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 523
[download] Destination: /tmp/tmp4679xtkt.tmp
[download] 100% of 1.38MiB in 00:00
[info] 6254221adb330c001409511c: Downloading 1 format(s): hls-2339
[info] Writing video subtitles to: The Long Goodbye [6254221adb330c001409511c].en.vtt
[debug] Invoking hlsnative downloader on "https://siloh-aka.plutotv.net/989_MGM_Studios/clip/62542218db330c0014095117_The_Long_Goodbye/720pDRM/20220411_075134/hls/0-end/fp/en.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 515
[download] Destination: The Long Goodbye [6254221adb330c001409511c].en.vtt
[download]   0.2% of ~67.90KiB at    1.37KiB/s ETA 00:48 (frag 1/515)ERROR: Parse error at position 23 (near 'MPEGTS:-6000,LOCAL:0')
Traceback (most recent call last):
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2661, in process_video_result
    self.process_info(new_info)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2919, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3897, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2860, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/downloader/hls.py", line 351, in real_download
    self.download_and_append_fragments(
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 525, in download_and_append_fragments
    result = append_fragment(
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 484, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/downloader/hls.py", line 266, in pack_fragment
    for block in webvtt.parse_fragment(frag_content):
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/webvtt.py", line 351, in parse_fragment
    yield Magic.parse(parser)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/webvtt.py", line 205, in parse
    local, mpegts = cls.__parse_tsmap(parser)
  File "/home/melissa/.local/lib/python3.8/site-packages/yt_dlp/webvtt.py", line 184, in __parse_tsmap
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 23 (near 'MPEGTS:-6000,LOCAL:0')
```

**Comment by dirkf** [comment]
Indeed, the parser doesn't expect a negative value:
```
    _REGEX_TSMAP_MPEGTS = re.compile(r'MPEGTS:([0-9]+)')
```
If this is a PES value, it should be a 33-bit unsigned integer. Possibly, some site code is getting this [nightmare calculation](https://chromium.googlesource.com/chromium/src/media/+/refs/heads/main/formats/mp2t/timestamp_unroller.cc) wrong (see also [SO](https://stackoverflow.com/questions/44242815/how-to-handle-overflow-case-of-pts-dts-scr-values-in-program-stream)).

[RFC8216 s3.5](https://tools.ietf.org/html/rfc8216#section-3.5) says
>   When synchronizing WebVTT with PES timestamps, clients SHOULD account
   for cases where the 33-bit PES timestamps have wrapped and the WebVTT
   cue times have not.

Surely these shows are much less than 26 hours, or can the timestamps start from a value >0?

Options to deal with this include assuming that the `-` is wrong, or just skipping the failing `X-TIMESTAMP-MAP` and keeping the previous cue offset, or 0.

**Comment by pukkandan** [comment]
We are supposed to be handling this. I believe the only the regex is buggy
https://github.com/yt-dlp/yt-dlp/blob/81bf0943eaa04069125dc683c418b65c2dbb7e25/yt_dlp/downloader/hls.py#L305-L314

**Comment by pukkandan** [comment]
cc @fstirlitz

**Comment by fstirlitz** [comment]
> If this is a PES timestamp value, it should be a 33-bit unsigned integer

Do the MPEG specifications actually say it is unsigned?

**Comment by dirkf** [comment]
That would be too easy. The values are counts, modulo 2^33, of the 90kHz clock, relative to some encoder-specified value, 0 or perhaps `(start - midnight) * 90000`, which corresponds to the beginning of the transport stream. Note the phrasing below which says that the values are "times" and not time differences.

ISO/IEC 13818-1:1996 (E) | ITU-T Rec. H.222.0 (1995 E) says, in 2.4.3.7 Semantic definition of fields in PES packet:
>PTS (presentation time stamp) – Presentation times shall be related to decoding times as follows: The PTS is a 33-bit number coded in three separate fields. It indicates the time of presentation, tpn(k), in the system target decoder of a presentation unit k of elementary stream n. The value of PTS is specified in units of the period of the system clock frequency divided by 300 (yielding 90 kHz). The presentation time is derived from the PTS according to equation 2-11 below. Refer to 2.7.4 for constraints on the frequency of coding presentation timestamps.
PTS(k)=((system_clock_frequency×tpn(k)) DIV 300) % 2^33     (2-11)
where tpn(k) is the presentation time of presentation unit Pn(k). 
...
DTS (decoding time stamp) – The DTS is a 33-bit number coded in three separate fields. It indicates the decoding time, tdn(j), in the system target decoder of an access unit j of elementary stream n. The value of DTS is specified in units of the period of the system clock frequency divided by 300 (yielding 90 kHz). The decoding time derived from the DTS according to equation 2-12 below:
DTS(j)=((system_clock_frequency×tdn(j)) DIV 300) % 2^33    (2-12)
where tdn(j) is the decoding time of access unit An(j).
...

**Comment by fstirlitz** [comment]
I guess we should accept signed values then and normalize them to unsigned ones.

This looks like a good opportunity to check if our overflow-handling code works.

**Comment by dirkf** [comment]
Isn't this an unlikely mapping (converted to seconds) for `LOCAL:00:00:00.000`, given that a good mapping is ~0.2s:
```
>>> (-6000 % (1 << 33))/90000.0
95443.65102222223
```
The show (eg, Irresistible) is less than 45 min., ~2700s.

Although this (keeping the new regex) would exercise the HLS rollover code, it would (from inspection) result in a similar surprisingly large offset:
```diff
                         raise ParseError(parser)
+                    mpegts = mpegts % (1 << 33) if mpegts > 0 else -(-mpegts % (1 << 33))
```
Instead (ignore sign):
```diff
-    _REGEX_TSMAP_MPEGTS = re.compile(r'MPEGTS:([0-9]+)')
+    _REGEX_TSMAP_MPEGTS = re.compile(r'MPEGTS:-?([0-9]+)')
```
Or, keeping the new regex (same result):
```diff
                         raise ParseError(parser)
+                    mpegts = abs(mpegts) % (1 << 33)
```
Or, keeping the new regex (default to 0 if -ve):
```diff
                         raise ParseError(parser)
+                    mpegts = max(0, mpegts) % (1 << 33)
```
If there were a show with **playable AV** and downloadable VTT having the same problem, one could test which is the best heuristic. The problem shows are offered [elsewhere](https://www.google.com/search?num=30&gl=us&hl=en&ucbcb=1&gbv=1&tbs=li%3A1&q=stargate+atlantis+s3+irresistible&oq=&aqs=): if the subtitle issue is in the original material, it may also be present in those versions; or, as previously hypothesised, it may be a Pluto site issue.

**Comment by fstirlitz** [comment]
The way I read the spec, the starting point of PES timestamps is arbitrary; they just have to increase monotonically at a specific rate. Absent other considerations, I think we should accept the timestamp as given. Why ignore the sign? Why would be a subtitle fragment encoded with a negative sign where it should be positive, with the exact same magnitude? Why would it be encoded with a small negative value where it should have been zero?

**Comment by fstirlitz** [comment]
The following change also seems necessary:

```diff
--- i/yt_dlp/webvtt.py
+++ w/yt_dlp/webvtt.py
@@ -270,7 +271,7 @@ class CueBlock(Block):
 
     _REGEX_ID = re.compile(r'((?:(?!-->)[^\r\n])+)(?:\r\n|[\r\n])')
     _REGEX_ARROW = re.compile(r'[ \t]+-->[ \t]+')
-    _REGEX_SETTINGS = re.compile(r'[ \t]+((?:(?!-->)[^\r\n])+)')
+    _REGEX_SETTINGS = re.compile(r'[ \t]+((?:(?!-->)[^\r\n])*)')
     _REGEX_PAYLOAD = re.compile(r'[^\r\n]+(?:\r\n|[\r\n])?')
 
     @classmethod
```

**Comment by heliosyne** [comment]
> If there were a show with **playable AV** and downloadable VTT having the same problem, one could test which is the best heuristic. The problem shows are offered [elsewhere](https://www.google.com/search?num=30&gl=us&hl=en&ucbcb=1&gbv=1&tbs=li%3A1&q=stargate+atlantis+s3+irresistible&oq=&aqs=): if the subtitle issue is in the original material, it may also be present in those versions; or, as previously hypothesised, it may be a Pluto site issue.

I'm not entirely sure what "playable AV and downloadable VTT" means, but I am very familiar with the show and have it in other formats, so I can compare it to another reference if it's a matter of judging timing changes.

**Comment by dirkf** [comment]
OP's example had DRMed AV. Once there is a downloader that doesn't crash, if you were to download the VTT for that example (The Long Goodbye) and associate it with one of your other copies, it could be interesting to know if the combination plays correctly, without VTT parser errors and without any sync error at the point of the potentially negative MPEGTS value, which is in the second fragment, before ~10s of the start. Also the same after editing the VTT to switch the MPEGTS value between -6000 <-> 8589928592.

In other parsers:
* xbmc/kodi uses a regex with no `-?` to parse the `MPEGTS:...` expression in the `X-TIMESTAMP-MAP` line
* similarly Android TV
* _hls.js_ parses the tail of the substring `MPEGTS:...` with `parseInt()` so -ve values are OK
* _ffmpeg_ uses `strtoll()` in a similar way and should also accept -ve values
* _AAMP_ uses `atoll()` in a similar way and should also accept -ve values
* _VLC_ uses `Integer<uint64_t>()` applied to a digit string, so doesn't understand -ve values
* _gstreamer_'s `adaptivedemux2` plugin expects a non-negative value MPEGTS value.

[This article](https://bitmovin.com/docs/encoding/faqs/why-is-an-timestamp-offset-for-ts-muxings-applied-by-default) proposes a rationale (best practice 10s PTS offset to avoid DTS underflow) for the often seen `MPGEGTS:900000` value.

Uncertainty about negative values follows from the RFC's decision to use two time values to represent what is actually a time difference. But, if negative values were acceptable, why have two fields instead of just one?

This uncertainty leads to the probable defect in the toolchain that generated the Pluto stream and which would resolve the "Whys" above: software that ignored the bit of the RFC that says the timestamp values are PES timestamps might naively subtract the timecode from both sides of the mapping to get a `00:00:00.000` timecode, giving a negative value if `timecode(k)` is greater in fractional seconds scaled by 90000 than `tpn(k) - tpn(0)` (using the terminology of the MPEG2 standard).

In yt-dlp, the (possibly negative) value is parsed when downloading the HLS stream and then used to generate new `X-TIMESTAMP-MAP` lines when writing the VTT subtitle file. Already, the parser allows whitespace between the parameters and the parameters in reverse order, so it could legitimately either ignore a line with a negative MPEGTS, or parse the value and pass it on, or parse it and pass on its 33-bit signed representation as a large unsigned value. 

* If the negative value is passed as-is to the HLS code, it should hit the [overflow code](https://github.com/yt-dlp/yt-dlp/blob/81bf0943eaa04069125dc683c418b65c2dbb7e25/yt_dlp/downloader/hls.py#L311-L313), generating the large unsigned value.

* If the large unsigned value is passed, that would be recorded directly.

In either case, unless players are shown to know about large values (ie, treat the numbers as 33-bit signed), should the value be sanitised, say in `[Magic.write_into()](https://github.com/yt-dlp/yt-dlp/blob/81bf0943eaa04069125dc683c418b65c2dbb7e25/yt_dlp/webvtt.py#L217-L218)`?
```diff
             stream.write('X-TIMESTAMP-MAP=LOCAL:')
+            if self.mpegts >= 1<<32:
+               self.local = (1<<33) - self.mpegts + (self.local or 0)
+               self.mpegts = 0
             stream.write(_format_ts(self.local if self.local is not None else 0))
```

**Comment by fstirlitz** [comment]
> should the value be sanitised, say in `Magic.write_into()`?

‘Sanitising’ what you don’t understand is how you end up with messes like <https://www.biphelps.com/blog/The-Fastest-GIF-Does-Not-Exist>. **Leave it alone.** (Or reject it entirely.)

**Comment by dirkf** [comment]
The code in yt-dlp "understands" the LOCAL and MPEGTS values. Since the two values define an offset, subtracting the same time value from (or adding it to) both values defines the same offset. Players have been shown to fail (reasonably IMO) on actual negative MPEGTS values. If players also fail with the 33-bit signed representation of the negative value, which needs to be checked, it would be prudent to write a pair of values that is semantically equivalent but with MPEGTS < 2^32.

For example, consider VLC with this line, where 8589928592 has been used instead of -6000 (= 8589928592 mod 2^33):
```
X-TIMESTAMP-MAP=MPEGTS:8589928592,LOCAL:00:00:00.000
```
VLC parses the MPEGTS value 8589928592 literally, calling 
```
setMetadataTimeMapping(VLC_TS_0 + mpegts * 100/9, VLC_TS_0 + local);
```
This eventually sets an offset of type `mtime_t` (µs in `int64_t`) as `mpegts * 100/9 - local`, but `8589928592 * 100/9 - 0 != -6000 * 100/9 - 0`. Unless there's a sanity check later in the processing, subtitles will be shown more than a day out of sync.

Whereas with the semantically equivalent line (apart from rounding),
```
X-TIMESTAMP-MAP=MPEGTS:0,LOCAL:00:00:00.067
```
the offset would be more correctly rendered as -67000µs; actually we wanted -66667, but a sub-millisecond difference is not significant for subtitling.

**Comment by heliosyne** [comment]
Is there progress with this? It's still an issue with v2022.8.19.

**Comment by heliosyne** [comment]
Is there a fix on the way for this? It's still happening with v2022.9.1, and I'm running into more and more content I can't grab because of negative offsets.

**Comment by pishposhmcgee** [comment]
This issue is still open, possibly pending a URL with useable audio and video. The original URL works for me now, but I'm getting a different parsing error.
````
[debug] Command-line config: ['https://pluto.tv/en/on-demand/seri
es/stargate-atlantis/season/2/episode/the-long-goodbye-2006-2-16'
, '--embed-subs', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8,
 error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.10.7 (CPython x86_64 64bit) - Linux-5.19.0-31-ge
neric-x86_64-with-glibc2.36 (OpenSSL 3.0.5 5 Jul 2022, glibc 2.36
)
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, rtmpdu
mp 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, cert
ifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.
0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[PlutoTV] Extracting URL: https://pluto.tv/en/on-demand/series/st
argate-atlantis/season/2/episode/the-long-goodbye-2006-2-16
[PlutoTV] stargate-atlantis: Downloading JSON metadata
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 information
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 playlist
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 playlist
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 playlist
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 playlist
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 playlist
[PlutoTV] 6254221adb330c001409511c: Downloading m3u8 information
WARNING: [PlutoTV] Failed to download m3u8 information: HTTP Erro
r 403: Forbidden
WARNING: [PlutoTV] Unable to find ad-free formats
[info] 6254221adb330c001409511c: Downloading subtitles: en
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, f
ps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_a
pprox, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 6254221adb330c001409511c: Downloading 1 format(s): hls-306
3
[info] Writing video subtitles to: The Long Goodbye [6254221adb33
0c001409511c].en.vtt
[debug] Invoking hlsnative downloader on "https://service-stitche
r-ipv4.clusters.pluto.tv/stitch/hls/episode/6254221adb330c0014095
11c/subtitle/en/playlist.m3u8?terminate=false&sid=38332a4f-ef42-1
1ed-99c2-a1a650f2b838&deviceDNT=0&deviceLat=43.2878&deviceLon=-96
.1965&deviceModel=web&deviceVersion=unknown&includeExtendedEvents
=false&appName=web&deviceId=unknown&appVersion=na&deviceType=web&
deviceMake=unknown"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 529
[download] Destination: The Long Goodbye [6254221adb330c001409511
c].en.vtt
[download] The Long Goodbye [6254221adb330c001409511c].en.vtt.par
t-Frag1 has already been downloaded
[download]   0.2% of ~  70.26KiB at   15.62KiB/s ETA Unknown (fra
g 1/529)ERROR: Parse error at position 57 (near '1\n00:00:03.770
--> 0')
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in
 wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1615, in
 __extract_info
    return self.process_ie_result(ie_result, download, extra_info
)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1674, in
 process_ie_result
    ie_result = self.process_video_result(ie_result, download=dow
nload)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2779, in
 process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3037, in
 process_info
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3037, in
 process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4021, in
 _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2970, in
 dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line
444, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/hls.py", line 362
, in real_download
    self.download_and_append_fragments(
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", lin
e 522, in download_and_append_fragments
    result = append_fragment(
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", lin
e 481, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index
))
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/hls.py", line 277
, in pack_fragment
    for block in webvtt.parse_fragment(frag_content):
  File "/usr/local/bin/yt-dlp/yt_dlp/webvtt.py", line 397, in par
se_fragment
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 57 (near '1\n00
:00:03.770 --> 0')
````

I downloaded all of the VTT fragments and none included negative MPEGTS offsets. What I did notice was that some other PlutoTV streams have parsable subs, but the MPEGTS offsets are unreliable.

For example `https://pluto.tv/on-demand/series/star-trek-picard-p/season/2/episode/the-star-gazer-2022-2-1`) serves subtitles where every WEBVTT fragment has an MPEGTS of `90000`, but the stream is broken up into parts that correspond to ad breaks, at which point the implied offset is reset and the timestamps in the VTT fragments start again from `00:00:00.000`. A more reliable offset can be derived from the '#EXT-X-PROGRAM-DATE-TIME' blocks that follow '#EXT-X-DISCONTINUITY ` in the .m3u8 container file.
