### ISSUE TITLE
Dropbox Replay Support

### ISSUE THREAD

**Issue by hansbergren** [yt-dlp/yt-dlp#4429]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

- Single video: https://replay.dropbox.com/share/u8d4G0g3Cc0sSswy?video_version_id=pid_rvv%3AAAAAAJJPuon-ZWgXXEb3oQQ3fsJPgEeXr8rZySdnl1g9VAEA

### Provide a description that is worded well enough to be understood

Dropbox now provides a streaming like service. While some videos do require login / cookies / authentication, there are other videos like the one above that are publicly accessible if you have the link. I would like to be able to download these videos with `yt-dlp`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
❯ yt-dlp 'https://replay.dropbox.com/share/u8d4G0g3Cc0sSswy?video_version_id=pid_rvv%3AAAAAAJJPuon-ZWgXXEb3oQQ3fsJPgEeXr8rZySdnl1g9VAEA' -vU
[debug] Command-line config: ['https://replay.dropbox.com/share/u8d4G0g3Cc0sSswy?video_version_id=pid_rvv%3AAAAAAJJPuon-ZWgXXEb3oQQ3fsJPgEeXr8rZySdnl1g9VAEA', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.9.13 (CPython 64bit) - macOS-11.6-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://replay.dropbox.com/share/u8d4G0g3Cc0sSswy?video_version_id=pid_rvv%3AAAAAAJJPuon-ZWgXXEb3oQQ3fsJPgEeXr8rZySdnl1g9VAEA
[generic] u8d4G0g3Cc0sSswy?video_version_id=pid_rvv:AAAAAJJPuon-ZWgXXEb3oQQ3fsJPgEeXr8rZySdnl1g9VAEA: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] u8d4G0g3Cc0sSswy?video_version_id=pid_rvv:AAAAAJJPuon-ZWgXXEb3oQQ3fsJPgEeXr8rZySdnl1g9VAEA: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://replay.dropbox.com/share/u8d4G0g3Cc0sSswy?video_version_id=pid_rvv%3AAAAAAJJPuon-ZWgXXEb3oQQ3fsJPgEeXr8rZySdnl1g9VAEA
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://replay.dropbox.com/share/u8d4G0g3Cc0sSswy?video_version_id=pid_rvv%3AAAAAAJJPuon-ZWgXXEb3oQQ3fsJPgEeXr8rZySdnl1g9VAEA
```
```

**Comment by HobbyistDev** [comment]
To get the video we can request to `https://api.dropboxapi.com/2/reel/get_with_shared_link` with POST method with requests body like this:
```
{
  "entity_type": {
    ".tag": "shared_video"
  },
  "share_token": <share_token>,
  "video_version_id": <video_version_id>,
  "only_max_resolution": false,
  "common": {
    "replay_session_id": "28df0dd0c697924b"
  }
}
```
And then we can get the response like this:
```
{
  "downloads_enabled": false,
  "entity_type": {
    ".tag": "shared_video"
  },
  "shared_entity": {
    ".tag": "shared_video",
    "access_level": {
      ".tag": "none"
    },
    "captions_tracks": [],
    "file_id": "id:JrxSFyFHclAAAAAAAAAAyQ",
    "file_name": "",
    "file_size_bytes": 187428852,
    "folder_id": "",
    "id": "pid_rvv:AAAAAJJPuon-ZWgXXEb3oQQ3fsJPgEeXr8rZySdnl1g9VAEA",
    "is_audio_only": false,
    "is_demo": true,
    "media_type": {
      ".tag": "video"
    },
    "name": "Replay Demo",
    "ns_id": 2759534225,
    "owner_uid": "3198308256",
    "poster_url": "https://uc4ee1f44e421c2614e0bd15f9ae.previews.dropboxusercontent.com/p/pdf_img/ABmhJIEf70N9AVlqxgQKS-WSpbOfN70t6fwADiOtHThQuWGVEngNHg-AAv0V4QPWLHbu1ckLPEU_778npC61zc1Fj1gR4YZj7LCwSF6k8_X5hnFYABzCuvEtQhvxZvBUx58quPsKRiaj7u4cgGdHxoj5XvlCzqs3NZpuUPNdZN_FBc85ix3b6W3DCFJK1Gm72y2xBcUj-fGI3SLBVP56jtMgC407oXW0loBD8a0Wo1R1YQ/p.png",
    "project_id": "pid_rp:AAAAAKojiyS2mqmdm8sxII_2zGpscv6FQkqmHVNiodpAFgLz",
    "project_name": "Replay Demo",
    "requires_password": false,
    "shared_link_url": "",
    "sj_id": 1658672264699855,
    "status": 0,
    "thumb_scrubber_vtt_url": "https://uc4ee1f44e421c2614e0bd15f9ae.previews.dropboxusercontent.com/p/scrubber_thumb_vtt/ABlivJ4xDQj2wMqaPkNU-45T5tAwFkpkmtYARU3L6iZpFh-PgIfpK7JY5cWWkHDDZcJFyQNYslAhwtJrBVZ3jYn-zBNs9Lb4gCDSRfySbs8d4yIdH2J3NMKQgqJNQcSL6yEDllbWinERbuaIvVFlmnZxtFMZ0Erqldl4jhpGcX5crLJZi_hJ96ZZBjAKtFnMnmsT2zddb_Qpal5vC-67Q0wjT7KPgRJB_iO77-djAuhzC4q7jOd8UkyY5mb52jdhu3A/p.vtt",
    "thumbnail_url": "https://uc4ee1f44e421c2614e0bd15f9ae.previews.dropboxusercontent.com/p/pdf_img/ABmhJIEf70N9AVlqxgQKS-WSpbOfN70t6fwADiOtHThQuWGVEngNHg-AAv0V4QPWLHbu1ckLPEU_778npC61zc1Fj1gR4YZj7LCwSF6k8_X5hnFYABzCuvEtQhvxZvBUx58quPsKRiaj7u4cgGdHxoj5XvlCzqs3NZpuUPNdZN_FBc85ix3b6W3DCFJK1Gm72y2xBcUj-fGI3SLBVP56jtMgC407oXW0loBD8a0Wo1R1YQ/p.png",
    "transcode_url": "https://uc4ee1f44e421c2614e0bd15f9ae.previews.dropboxusercontent.com/p/hls_master_playlist/ABkrYaBSMponEFmpNFGRd12mTP51IA5-4-VQoy0FhIT1MqThcDZOhiREe4JyRhnCVdbPyQoSGaHVxxCSRIiBoaSIqcInSGHO1UvroLXgb3_oOh_0Z6T_G8Cf_QF1Z3s5G4x3FgyqB3SwS7_KU2mWSKgBvLJevU-VO_IGAJooR7ALKviGXaQ_99VW_UPhWAjtLA_NadH6ztxqdzNujuUU9O6xAAmsk3Ss3aiiFuTcAy7EGctvavzvzGw2HYsWbZfnZhZo1Z5FGdaP590DE9KT9knB/p.m3u8?use_highest_audio_bitrate=1",
    "upload_timestamp": "2022-07-24T14:17:43Z",
    "version_num": 1,
    "version_summaries": [],
    "video_id": "pid_rv:AAAAAMte3d66Y6p1K8h25U2jCGPA0jz8JBrVAPG5kBCbDJOh",
    "video_id_for_amplitude": "safe_for_amplitude:AABYE2HivVNYcYWAr9p8MrkBIXYdimJfdWUR9Pg_xZ3jXw",
    "video_metadata": {
      "aspect_ratio": "16:9",
      "audio_chan_layout": "stereo",
      "audio_freq": 48000,
      "bit_rate": 24607123,
      "capture_date": "2021-05-20T21:11:40Z",
      "codec": "h264",
      "color_space": "bt709",
      "container_format": "mp4",
      "device": "",
      "duration": 61,
      "duration_precise": 60.101707,
      "frame_rate": 24,
      "frame_rate_precise": 23.976025,
      "resolution_height": 1080,
      "resolution_width": 1920,
      "stream_metadata": [
        {
          "bitrate_bps": 24607123,
          "channel_layout": "",
          "channels": 0,
          "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
          "codec_name": "h264",
          "codec_tag_string": "avc1",
          "codec_type": "video",
          "color_space": "bt709",
          "creation_time": "Thu, 20 May 2021 21:11:40 +0000",
          "device": "",
          "display_aspect_ratio": "16:9",
          "duration_s": 60.101707,
          "frames_per_second": 23.976025,
          "height": 1080,
          "is_default": true,
          "rotation": 0,
          "sample_aspect_ratio": "1:1",
          "sample_rate_s": 0,
          "stream_index": 0,
          "width": 1920
        },
        {
          "bitrate_bps": 317375,
          "channel_layout": "stereo",
          "channels": 2,
          "codec_long_name": "AAC (Advanced Audio Coding)",
          "codec_name": "aac",
          "codec_tag_string": "mp4a",
          "codec_type": "audio",
          "color_space": "",
          "creation_time": "Thu, 20 May 2021 21:11:40 +0000",
          "device": "",
          "display_aspect_ratio": "",
          "duration_s": 60.101707,
          "frames_per_second": 0,
          "height": 0,
          "is_default": true,
          "rotation": 0,
          "sample_aspect_ratio": "",
          "sample_rate_s": 48000,
          "stream_index": 1,
          "width": 0
        }
      ]
    },
    "video_token": "",
    "viewer_count": 0,
    "waveform_url": ""
  },
  "show_comments": false
}
```
And then we can get video from `transcode_url`. I didn't know where `replay_session_id` came from and this requests have `Authorization` header ( with basic token)

**Comment by someziggyman** [comment]
Just in case adding another link for testing this case:
https://replay.dropbox.com/share/V0qi0BdJMGhZvuCO

**Comment by ndyanx** [comment]
@bashonly 
url test = https://replay.dropbox.com/share/u8d4G0g3Cc0sSswy?video_version_id=pid_rvv%3AAAAAAJJPuon-ZWgXXEb3oQQ3fsJPgEeXr8rZySdnl1g9VAEA , https://replay.dropbox.com/share/PDsoeMJB00aNaQfI?video_version_id=pid_rvv:AAAAALtSaFYo6zhtz8NbnYEhtVFP5p8Ukd-2V9Z4EhE8jYJi, https://replay.dropbox.com/share/AplVQ0SGGyYCO3fG?fbclid=IwY2xjawFlVPlleHRuA2FlbQIxMAABHcxDt28WwVvB324OqCO0n1uMv1rgbL4zen6q9IijEmi4AgDQIbdw9mgkcA_aem_XWoSrHo-wDvRqzT9O3wHBQ

`_DOMAIN = 'https://replay.dropbox.com'
        video_id = url_basename(url) # error: self._match_id(url)
        video_version_id = self._search_regex(
            r'video_version_id\=(.*)(&|)', url, 'video_version_id', fatal=False)
        
        webpage = self._download_webpage(url, video_id)
        part_js = self._search_regex(r'<script defer="defer" src="/static/main\.(.*)"></script>', webpage, 'id')
        webpage_js = self._download_webpage(
            'https://replay.dropbox.com/static/main.' + part_js, video_id, headers={'referer': url})
        # long string - search_regex - error EOL
        part = webpage_js.split('endsWith("corp.dropbox.com")')[1].split(',d=window.location.origin')[0]
        devboxreplaykey = self._search_regex(r'\"devboxreplaykey\":\"(.*)\",c', part, 'replay_key')
        devboxreplaysecret = self._search_regex(r'\"devboxreplaysecret\":\"(.*)\",u', part, 'replay_secret')
        token = base64.b64encode(f'{devboxreplaykey}:{devboxreplaysecret}'.encode()).decode()

        json_data = {
            'entity_type': {
                '.tag': 'shared_video',
            },
            'share_token': video_id,
            'only_max_resolution': False,
            'common': {
                'replay_session_id': 'a1389d8f4b%s' % str(random.randint(10000, 99999)),
            },
        }
        if video_version_id:
            json_data['video_version_id'] = video_version_id.replace('%3A', ':')
        data = self._download_json(
            'https://api.dropboxapi.com/2/reel/get_with_shared_link', video_id, 'POSTing video json',
            headers={
                'authorization': f'Basic {token}',
                'content-type': 'application/json',
                'origin': _DOMAIN,
                'referer': _DOMAIN,
                'sec-fetch-mode': 'cors'},
            data=dumps(json_data).encode('utf-8')
        )

        transcode_url = traverse_obj(data, ('shared_entity', 'transcode_url'))
        formats = self._extract_m3u8_formats(
            transcode_url, video_id, 'mp4', headers={'Referer': _DOMAIN})

        subtitles = {}
        for caption_track in traverse_obj(data, ('shared_entity', 'captions_tracks'), default=[]):
            subtitles.setdefault(caption_track.get('filename'), []).append({
                'url': caption_track.get('url'),
                'name': caption_track.get('filename')})

        upload_date = traverse_obj(
            data, ('shared_entity', 'video_metadata', 'stream_metadata', 0, 'creation_time'))
        if upload_date:
            try:
                upload_date_obj = datetime.strptime(upload_date, '%a, %d %b %Y %H:%M:%S %z')
                upload_date = upload_date_obj.strftime('%Y%m%d')
            except:
                upload_date = None

        return {
            'id': video_id,
            'title': traverse_obj(data, ('shared_entity', 'name')),
            'thumbnail': traverse_obj(data, ('shared_entity', 'poster_url')),
            'upload_date': upload_date,
            'uploader': traverse_obj(data, ('shared_entity', 'owner_name')),
            'uploader_id': traverse_obj(data, ('shared_entity', 'owner_uid')),
            'filesize': traverse_obj(data, ('shared_entity', 'file_size_bytes'), expected_type=int),
            'duration': traverse_obj(data, ('shared_entity', 'video_metadata', 'duration')),
            'formats': formats,
            'subtitles': subtitles,
            'http_headers': {'Referer': _DOMAIN},
        }`

**Comment by bashonly** [comment]
@ndyanx do you want to open a PR?

**Comment by ndyanx** [comment]
> ¿Quieres abrir un PR?
yes, although it lacks coding conventions
