### ISSUE TITLE
`argument of type 'bool' is not iterable` after calling `_download_webpage_handle`

### ISSUE THREAD

**Issue by mvoidex** [yt-dlp/yt-dlp#4432]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

While downloading large Yandex Music playlist I get error `argument of type 'bool' is not iterable`

The reason is that:
- `InfoExtractor._download_webpage_handle` [can](https://github.com/yt-dlp/yt-dlp/blob/14f25df2b6233553e968df023430ca96c0b1df9f/yt_dlp/extractor/common.py#L836) return `False`
- Derived class tests for some string within result:
  - Yandex Music affected: [link](https://github.com/yt-dlp/yt-dlp/blob/66cf3e1001b6d9a2829fe834c3f9103b0890918e/yt_dlp/extractor/yandexmusic.py#L39)
  - Also Xiaomi may be affected: [link](https://github.com/yt-dlp/yt-dlp/blob/66cf3e1001b6d9a2829fe834c3f9103b0890918e/yt_dlp/extractor/xiami.py#L11)
  - And Adobe possibly too: [link](https://github.com/yt-dlp/yt-dlp/blob/14f25df2b6233553e968df023430ca96c0b1df9f/yt_dlp/extractor/adobepass.py#L1461), unpacks result of `_download_webpage_handle`, which [calls](https://github.com/yt-dlp/yt-dlp/blob/14f25df2b6233553e968df023430ca96c0b1df9f/yt_dlp/extractor/adobepass.py#L1361) base version

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --cookies ..\..\yandex.music.txt https://music.yandex.ru/users/VoidEx/playlists/1031 -vU
[debug] Command-line config: ['--cookies', '..\\..\\yandex.music.txt', 'https://music.yandex.ru/users/VoidEx/playlists/1031', '-vU']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [yandexmusic:playlist] Extracting URL: https://music.yandex.ru/users/VoidEx/playlists/1031
[yandexmusic:playlist] 1031: Downloading playlist JSON
[yandexmusic:playlist] 1031: Downloading missing tracks JSON chunk 1
WARNING: [yandexmusic:playlist] Unable to download JSON metadata: HTTP Error 431: Request Header Fields Too Large
ERROR: argument of type 'bool' is not iterable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\yandexmusic.py", line 356, in _real_extract
  File "yt_dlp\extractor\yandexmusic.py", line 217, in _extract_tracks
  File "yt_dlp\extractor\yandexmusic.py", line 49, in _call_api
  File "yt_dlp\extractor\yandexmusic.py", line 44, in _download_json
  File "yt_dlp\extractor\common.py", line 1004, in download_content
  File "yt_dlp\extractor\common.py", line 968, in download_handle
  File "yt_dlp\extractor\yandexmusic.py", line 39, in _download_webpage_handle
TypeError: argument of type 'bool' is not iterable
```

**Comment by mvoidex** [comment]
However, problem that causing this issue is "HTTP Error 431: Request Header Fields Too Large", and i don't know how to workaround it :(

**Comment by pukkandan** [comment]
It is likely an issue either with cookies or with how yt-dlp is processing them. First try by re-exporting the cookies. If that doesn't help, I can take a look if you are willing to share login details with me

**Comment by pukkandan** [comment]
nvm, issue seems related to https://github.com/ytdl-org/youtube-dl/issues/27355

**Comment by mvoidex** [comment]
> nvm, issue seems related to https://github.com/ytdl-org/youtube-dl/issues/27355

Yes, but as I can see, it's fixed there and also this commit merged here as long as there's message about chunks while reading playlist

**Comment by mvoidex** [comment]
> It is likely an issue either with cookies or with how yt-dlp is processing them. First try by re-exporting the cookies. If that doesn't help, I can take a look if you are willing to share login details with me

I've tried reexporting cookies and it didn't help. I can share login details, if it helps, where I can do it?

**Comment by pukkandan** [comment]
Contact: discord (pukkandan#4207) / reddit (/u/pukkandan) / email (pukkandan.ytdlp@gmail.com)

**Comment by mvoidex** [comment]
Let's try discord, I'm voidex#9676

**Comment by dirkf** [comment]
The issue is twofold:
* `_call_api()` has `_download_json(..., fatal=False, ...)`, which can cause `_download_webpage_handle()` to return `False` instead of raising
* the specialisation of `_download_webpage_handle()` doesn't take account of that, but just obscures the error, and in any case doesn't actually understand **what the normal return value should be** (ie the original captcha check never worked).
```diff
     def _download_webpage_handle(self, *args, **kwargs):
         webpage = super()._download_webpage_handle(*args, **kwargs)
+        if not webpage:
+            return None
+        webpage = webpage[1]
         if 'Нам очень жаль, но&nbsp;запросы, поступившие с&nbsp;вашего IP-адреса, похожи на&nbsp;автоматические.' in webpage:
            self._raise_captcha()
        return webpage
```

**Comment by bashonly** [comment]
> ```diff
>      def _download_webpage_handle(self, *args, **kwargs):
>          webpage = super()._download_webpage_handle(*args, **kwargs)
> +        if not webpage:
> +            return None
> +        webpage = webpage[0]
>          if 'Нам очень жаль, но&nbsp;запросы, поступившие с&nbsp;вашего IP-адреса, похожи на&nbsp;автоматические.' in webpage:
>             self._raise_captcha()
>         return webpage
> ```

This would still be wrong, since the expected result from a successful `_download_webpage_handle` call is a tuple, `(webpage, urlh)`

It seems like the mistake is the decision to redefine `_download_webpage_handle()` instead of `_download_webpage()`

**Comment by dirkf** [comment]
The result is only a tuple if the webpage was fetched. When `fatal` is falsy, `False` can be returned if the request failed.

If it was only intended to affect webpage downloads rather than JSON as well, `_download_webpage()` would have been the right target and the method suite might have been correct.

**Comment by bashonly** [comment]
> The result is only a tuple if the webpage was fetched. When `fatal` is falsy, `False` can be returned if the request failed.

That's what I was going for with "successful call." Your patch only returns the 1st character of the webpage (`res[0]`) if the fetching is successful

> If it was only intended to affect webpage downloads rather than JSON as well, `_download_webpage()` would have been the right target and the method suite might have been correct.

True, making this `_download_webpage()` instead wouldn't work either. I guess we'd have to do this:

```py
    def _download_webpage_handle(self, *args, **kwargs):
        res = super()._download_webpage_handle(*args, **kwargs)
        if res is False:
            return False
        if 'Нам очень жаль, но&nbsp;запросы, поступившие с&nbsp;вашего IP-адреса, похожи на&nbsp;автоматические.' in res[0]:
            self._raise_captcha()
        return res
```

**Comment by dirkf** [comment]
That's equivalent to the patch that I posted, given that `res` (called `webpage` in the original code) is guaranteed to be either `False` or a tuple whose head is the webpage. As they say, "ask me how I know".

It was perhaps a poor design decision to do that rather than returning `(None, None)`.

Fancier:
```py
class HandleResult(collections.namedtuple(['webpage', 'urlh']):
    def __bool__(self):
        return self.urlh is not None

    __nonzero__ = __bool__  # Python 2.7
```
Then:
```console
>>> x = HandleResult(None, None)
>>> not x
True
>>> bool(x)
False
>>> x or 42
42
>>> 42 and x
HandleResult(webpage=None, urlh=None)
>>> 
```
Not crashing on the patched code would reveal whether the underlying issue, which was made a warning by `fatal=False`, was recoverable:
```console
WARNING: [yandexmusic:playlist] Unable to download JSON metadata: HTTP Error 431: Request Header Fields Too Large
```

**Comment by bashonly** [comment]
> That's equivalent to the patch that I posted, given that `res` (called `webpage` in the original code) is guaranteed to be either `False` or a tuple whose head is the webpage. As they say, "ask me how I know".

No, it's not. Your patch only returns the 1st character of a webpage upon a successful request

**Comment by dirkf** [comment]
Oh sure, edited.

**Comment by f1ow03** [comment]
Still no solution in 2026?

**Comment by DosanTeuze** [comment]
I’ve tried all the methods described here and in other issues to download a playlist from Yandex.Music, but I keep getting an error. After I replaced the old code with:
```
 def _download_webpage_handle(self, *args, **kwargs):
        res = super()._download_webpage_handle(*args, **kwargs)
        if res is False:
            return False
        if 'Нам очень жаль, но&nbsp;запросы, поступившие с&nbsp;вашего IP-адреса, похожи на&nbsp;автоматические.' in res[0]:
            self._raise_captcha()
        return res
```    
the old error disappeared, but a new one appeared:

<details>
<summary>Click to expand the error log (Log Output)</summary>

```text
[debug] Command-line config: ['-vU', '--cookies', 'C:\\Users\\asdasd\\Desktop\\yandex.music.txt', '-f', 'ba/b', '--audio-quality', '0', '-o', '%%(title)s.%%(ext)s', '--proxy=', 'https://music.yandex.ru/users/van4ik05/playlists/1003']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2026.06.16.000106 from yt-dlp/yt-dlp-nightly-builds [8902f6ba8] (pip)
[debug] Python 3.13.12 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.18 30 Sep 2025)
[debug] exe versions: ffmpeg N-123034-g47e87ed722-20260226 (setts), ffprobe N-123034-g47e87ed722-20260226
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.2.0, certifi-2026.02.25, mutagen-1.47.0, requests-2.32.5, sqlite3-3.50.4, urllib3-2.6.3, websockets-16.0, yt_dlp_ejs-0.8.0
[debug] JS runtimes: deno-2.8.3
[debug] Proxy map: {'all': '__noproxy__'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: C:\Users\asdasd\AppData\Roaming\yt-dlp\plugins\yt-dlp-ChromeCookieUnlock.zip\yt_dlp_plugins
[debug] Loaded 1739 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2026.06.16.000106 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2026.06.16.000106 from yt-dlp/yt-dlp-nightly-builds)
[yandexmusic:playlist] Extracting URL: https://music.yandex.ru/users/van4ik05/playlists/1003
[yandexmusic:playlist] 1003: Downloading playlist JSON
WARNING: [yandexmusic:playlist] Unable to download JSON metadata: HTTP Error 404: Not found
ERROR: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "G:\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1726, in wrapper
    return func(self, *args, **kwargs)
  File "G:\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1861, in __extract_info
    ie_result = ie.extract(url)
  File "G:\Programs\Python\Python313\Lib\site-packages\yt_dlp\extractor\common.py", line 763, in extract
    ie_result = self._real_extract(url)
  File "G:\Programs\Python\Python313\Lib\site-packages\yt_dlp\extractor\yandexmusic.py", line 348, in _real_extract
    playlist = self._call_api(
               ~~~~~~~~~~~~~~~
    ...<6 lines>...
            'overembed': 'false',
            ~~~~~~~~~~~~~~~~~~~~~
        })['playlist']
        ~~^^^^^^^^^^^^
TypeError: 'bool' object is not subscriptable
```

</details>

I’ve also tried completely clearing my Firefox history to remove all cookies and everything associated with them, and I’ve tried switching the proxy on and off for different countries again, but to no avail – nothing works. Will there ever be a solution? I use Firefox because it’s great for extracting cookie files via any add-ons and via the argument

**Comment by DesSolo** [comment]
https://github.com/DesSolo/yt-dlp/blob/master/yt_dlp/extractor/yandexmusic.py
Клод справился, PR к сожалению не будет.

Авторизацию переделали на oAuth
Токен можно получить тут https://oauth.yandex.ru/authorize?response_type=token&client_id=23cabbbdc6cd418abb4b39c32c41195d

23cabbbdc6cd418abb4b39c32c41195d - это официальный client_id приложения Яндекс.Музыки (публично известный)
```
./yt-dlp.sh --extractor-args "yandexmusic:token=<TOKEN>"
```

**Comment by DosanTeuze** [comment]
@DesSolo блин, спасибо тебе большое. Сильно выручил на самом-то деле. Клод фри версия у тебя или с подпиской какой-то?
