### ISSUE TITLE
tiktok following

### ISSUE THREAD

**Issue by Butterfly-Dragon** [yt-dlp/yt-dlp#4441]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Example URLs

https://www.tiktok.com/following

### Provide a description that is worded well enough to be understood

From the outside i do not know what is wrong with this, it just looks like it is not "understanding" the url and therefore does not seem to know what to do with it.

Rather than asking it to download every single person i follow i would just like to point it at the baseline URL

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--config-location', 'D://Downloads//Downloader///!Downloader//youtube-dl.cfg', '--cookies', 'D://Downloads//Downloader///!Downloader//cookies-youtube.txt', '--output', 'D://Downloads//Downloader///!Freerapid Download//%(playlist)s - %(playlist_index)s - %(title)s.%(ext)s', '-vU', 'https://www.tiktok.com/following']
[debug] | Config "D://Downloads//Downloader///!Downloader//youtube-dl.cfg": ['--cache-dir', 'd://downloads//downloader///!downloader//tmp', '--download-archive', 'd://downloads//downloader///!downloader//youtube-dl-history.txt', '--sub-lang', 'en,it,-live_chat', '--write-automatic-subs', '--sub-format', 'best', '--embed-subs', '--embed-chapters', '--ignore-errors', '--ignore-no-formats-error', '--no-warnings', '--mark-watched', '--match-filter', '!is_live & !was_live', '--mtime', '--format', 'bestvideo[height<=?720]+bestaudio/best[height<=?720]/best[height<=?480]', '--prefer-ffmpeg', '--prefer-free-formats', '--restrict-filenames', '--merge-output-format', 'mp4', '--output', 'd://downloads//downloader///!freerapid download//%(uploader)s %(title)s.%(ext)s', '--playlist-reverse', '--skip-unavailable-fragments', '--socket-timeout', '30', '--extractor-retries', 'infinite', '--fragment-retries', 'infinite', '--retries', 'infinite', '--continue', '--yes-playlist']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg 2022-02-24-git-8ef03c2ff1-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loading archive file 'd://downloads//downloader///!downloader//youtube-dl-history.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://www.tiktok.com/following
[generic] following: Downloading webpage
[generic] following: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.tiktok.com/following
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/following
```

**Comment by Butterfly-Dragon** [comment]
to note:

• Currently tiktok has a strange behaviour where each page gets tried multiple times per second and it feels like it is not even trying to wait for the site to respond, since my connection is not that great, and it is either flooding the remote site with pings without paiting for a response or something, because it just cannot be that fast. we are talking about 10s or even 100s of times/sec. I don't know if you guys all got terabyte connections or something but i have 100 MB/sec when downhill and with favourable wind and that happens rarely. Most of the times i have 20/40 MB/sec with pings in the order of 300ms

• Also if a page fails the page itself and all the following get skipped, which is just weird. If it's the first the whole channel got skipped.
