### ISSUE TITLE
[Harpodeon] Add support for harpodeon.com.

### ISSUE THREAD

**Issue by clusterized** [yt-dlp/yt-dlp#4450]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://www.harpodeon.com/video/The_Smoking_Out_of_Bella_Butts/268068288

### Provide a description that is worded well enough to be understood

Download link can be extracted with _Inspect Element_: https://www.harpodeon.com/G40G5FG/DFSFFUW/CC5GQF5/G04G17AG05/stream_B_268068288_720.mp4

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ffmpeg-location', 'C:\\Program Files\\ffmpeg-master-latest-win64-gpl\\bin', 'https://www.harpodeon.com/video/The_Smoking_Out_of_Bella_Butts/268068288']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-8.1-6.3.9600-SP0
[debug] Checking exe version: "C:\Program Files\ffmpeg-master-latest-win64-gpl\bin\ffmpeg" -bsfs
[debug] Checking exe version: "C:\Program Files\ffmpeg-master-latest-win64-gpl\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg N-106989-gb033913d1c-20220524 (setts), ffprobe N-106989-gb033913d1c-20220524
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://www.harpodeon.com/video/The_Smoking_Out_of_Bella_Butts/268068288
[generic] 268068288: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 268068288: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.harpodeon.com/video/The_Smoking_Out_of_Bella_Butts/268068288
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.harpodeon.com/video/The_Smoking_Out_of_Bella_Butts/268068288
```

**Comment by HobbyistDev** [comment]
From webpage source: i found the video in this tag:
```html
<script type="text/javascript">
hpBase('https://www.harpodeon.com/5FQG5FG/GFUFFUW/FC5GQF5/G04G17DG04/stream_B_');
hpInjectVideo('268068288','480',0);
hpToggleSize('480');
```
We can construct the url like this `<hpBase>/<hpInjectVideo[0]>_<hpInjectVideo[1]>.mp4` with referrer header <url>
here's yt-dlp log:
```shell
> yt-dlp -v "https://www.harpodeon.com/5FQG5FG/GFUFFUW/FC5GQF5/G04G17AG04/stream_B_268068288_480.mp4" --add-header "Referer: https://www.harpodeon.com/video/The_Smoking_Out_of_Bella_Butts/268068288" --ignore-config
[debug] Command-line config: ['-v', 'https://www.harpodeon.com/5FQG5FG/GFUFFUW/FC5GQF5/G04G17AG04/stream_B_268068288_480.mp4', '--add-header', 'Referer: https://www.harpodeon.com/video/The_Smoking_Out_of_Bella_Butts/268068288', '--ignore-config']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.harpodeon.com/5FQG5FG/GFUFFUW/FC5GQF5/G04G17AG04/stream_B_268068288_480.mp4
[generic] stream_B_268068288_480: Requesting header
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] stream_B_268068288_480: Downloading 1 format(s): mp4
[debug] Invoking http downloader on "https://www.harpodeon.com/5FQG5FG/GFUFFUW/FC5GQF5/G04G17AG04/stream_B_268068288_480.mp4"
[download] Resuming download at byte 10823582
[debug] File locking is not supported. Proceeding without locking
[download] Destination: stream_B_268068288_480 [stream_B_268068288_480].mp4
[download]  34.7% of 84.37MiB at    1.32MiB/s ETA 00:41
ERROR: Interrupted by user
```

**Comment by eren-kemer** [comment]
I'd like to work on this if it's still open. Curently got the download working and looking to get metadata implemented now.
