### ISSUE TITLE
[FanCode] video downloading fails

### ISSUE THREAD

**Issue by m3jorri** [yt-dlp/yt-dlp#4459]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

FanCode extractor for yt-dlp seems to fail for videos with error "Unsupported URL"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --verbose -F "https://www.fancode.com/cricket/videos/thriller-india-fightback-to-clinch-2wicket-win/35441"
[debug] Command-line config: ['--verbose', '-F', 'https://www.fancode.com/cricket/videos/thriller-india-fightback-to-clinch-2wicket-win/35441']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.15.32-v8+-aarch64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-62110-g4d45f5acbd-static (setts), ffprobe N-62110-g4d45f5acbd-static
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.fancode.com/cricket/videos/thriller-india-fightback-to-clinch-2wicket-win/35441
[generic] 35441: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 35441: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.fancode.com/cricket/videos/thriller-india-fightback-to-clinch-2wicket-win/35441
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.fancode.com/cricket/videos/thriller-india-fightback-to-clinch-2wicket-win/35441
```

**Comment by dirkf** [comment]
It doesn't seem to be enough to extend `FancodeVodIE._VALID_URL`:
```
[debug] [fancode:vod] Extracting URL: https://www.fancode.com/cricket/videos/thriller-india-fightback-to-clinch-2wicket-win/35441
[fancode:vod] 35441: Downloading metadata
ERROR: [fancode:vod] 35441: Unable to extract brightcove Video ID; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/fancode.py", line 108, in _real_extract
    raise ExtractorError('Unable to extract brightcove Video ID')
```
---
Plainly not related, but with a minimal Py 3.9 installation (where `brotli is None`) I get this Brotli decompression error rather than OP's:
```
$ python3.9 -m yt_dlp -v -F 'https://www.fancode.com/cricket/videos/thriller-india-fightback-to-clinch-2wicket-win/35441'
[debug] Command-line config: ['-v', '-F', 'https://www.fancode.com/cricket/videos/thriller-india-fightback-to-clinch-2wicket-win/35441']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 4e7f375c9
[debug] Python 3.9.13 (CPython 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (glibc 2.23)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: certifi-2019.11.28, secretstorage-3.2.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.fancode.com/cricket/videos/thriller-india-fightback-to-clinch-2wicket-win/35441
[generic] 35441: Downloading webpage
ERROR: 'NoneType' object has no attribute 'decompress'
Traceback (most recent call last):
  File "/home/df/Documents/src/yt-dlp/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/YoutubeDL.py", line 1501, in __extract_info
    ie_result = ie.extract(url)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/generic.py", line 2816, in _real_extract
    full_response = self._request_webpage(url, video_id, headers={'Accept-Encoding': '*'})
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 773, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/df/Documents/src/yt-dlp/yt_dlp/YoutubeDL.py", line 3634, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/utils.py", line 1371, in http_response
    io.BytesIO(self.brotli(resp.read())), old_resp.headers, old_resp.url, old_resp.code)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/utils.py", line 1308, in brotli
    return brotli.decompress(data)
AttributeError: 'NoneType' object has no attribute 'decompress'
```
Apparently although only `SUPPORTED_ENCODINGS` are supposed to be sent in the   `Accept-encoding` header and `br` shouldn't be in that list if there's no `brotli` module, the site is sending `Content-encoding: br` regardless. Should this be trapped separately? If the br-encoded page is returned as-is, the generic extractor guesses that it's actually a video, so that's no help. And the code structure in `YoutubeDLHandler.http_respon se()` doesn't seem to match RFC9111 which says that multiple Content-encodings are listed in order of application and therefore should be popped from the end of a comma-separated list when decoding. Since the RFC expects a server to fail to Identity encoding if it doesn't support anything proposed in `Accept-encoding` rather using some random other encoding, it doesn't say what the client should do if the server does that. Perhaps just raise 415, like this?
```
[debug] [generic] Extracting URL: https://www.fancode.com/cricket/videos/thriller-india-fightback-to-clinch-2wicket-win/35441
[generic] 35441: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 415: Server sent unacceptable encoding br (caused by <HTTPError 415: 'Server sent unacceptable encoding br'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by m3jorri** [comment]
Would it be possible to merge the above pull request @pukkandan

**Comment by seproDev** [comment]
@m3jorri The pull request above has pending fixes (i.e. changes were requested, but the author of the PR did not fix them).
In its current state the pull request can not be merged. Since the PR has been marked as stale due to the author seemingly no longer being interested, you are free to open a new PR and fix any outstanding issues.

**Comment by m3jorri** [comment]
Unfortunately don't have the expertise to fix this myself. Here's a log with the error (shown only while downloading some livestreams) for @zenerdi0de and others to refer

`[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.03.31 from yt-dlp/yt-dlp (linux_exe)
[debug] Python 3.11.11 (CPython x86_64 64bit) - Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with (OpenSSL 3.1.8 11 Feb 2025)
[debug] exe versions: ffmpeg N-115572-g9576a00527-20240604 (setts), ffprobe N-115572-g9576a00527-20240604
[debug] Optional libraries: Cryptodome-3.22.0, brotli-1.1.0, certifi-2025.01.31, curl_cffi-0.10.0, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.3.0, websockets-15.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1850 extractors
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[fancode:live] Logging in
[fancode:live] refresh token: Getting the Access token
[fancode:live] Extracting URL: https://fancode.com/match/123495/
[fancode:live] 123495: Info json
ERROR: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1653, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1788, in __extract_info
  File "yt_dlp/extractor/common.py", line 748, in extract
  File "yt_dlp/extractor/fancode.py", line 170, in _real_extract
  File "yt_dlp/extractor/common.py", line 3344, in _extract_akamai_formats
  File "yt_dlp/extractor/common.py", line 3350, in _extract_akamai_formats_and_subtitles
TypeError: argument of type 'NoneType' is not iterable`
