### ISSUE TITLE
Postprocessing crashed after downloading vimeo link

### ISSUE THREAD

**Issue by carlosagh96** [yt-dlp/yt-dlp#4476]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I was downloading a vimeo link and the postprocessing failed, it's not really a problem with vimeo itself, atl east for the downloading part as far as i know, but it's the first time i've had this problem

This is the code that i was running:

file: test.py
```
#!/usr/bin/python3.9

from yt_dlp import YoutubeDL
import sys

try:
	url=sys.argv[1]
	print(sys.argv)
except Exception as e:
	print(e)
	exit()

def get(url):
	with YoutubeDL({"verbose":True}) as yyy:
		yyy.download(url)

get(url)
```
then i ran
```
$ python3 test.py https://player.vimeo.com/video/733024860?h=4bbad08d7a
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
STDOUT
[vimeo] 733024860: Downloading webpage
['./1449424315/run_this.py', 'https://player.vimeo.com/video/733024860?h=4bbad08d7a']
[vimeo] 733024860: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 733024860: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 733024860: Downloading akfire_interconnect_quic MPD information
[vimeo] 733024860: Downloading akfire_interconnect_quic MPD information
[info] 733024860: Downloading 1 format(s): dash-akfire_interconnect_quic_sep-video-0df34847+dash-akfire_interconnect_quic_sep-audio-1fed0a50
[dashsegments] Total fragments: 1443
[download] Destination: Soz 51.mp4 [733024860].fdash-akfire_interconnect_quic_sep-video-0df34847.mp4

[download]   0.1% of ~1.14MiB at    9.19KiB/s ETA 02:07 (frag 0/1443)
[download]   0.1% of ~1.14MiB at    9.13KiB/s ETA 02:07 (frag 1/1443)
...
...
[download] 100.0% of ~101.16MiB at  148.39KiB/s ETA 00:00 (frag 1442/1443)
[download] 100.0% of ~101.16MiB at  212.27KiB/s ETA 00:00 (frag 1442/1443)
[download] 100.0% of ~101.16MiB at  211.25KiB/s ETA 00:00 (frag 1443/1443)
[download] 100% of 101.16MiB in 01:32                                     
[Merger] Merging formats into "Soz 51.mp4 [733024860].mp4"

STDERR
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.9.6 (CPython 64bit) - Linux-4.4.0-1104-aws-x86_64-with-glibc2.28 (glibc 2.28)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.1.9-0, ffprobe 4.1.9-0
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-9.1
[debug] Proxy map: {}
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/733024860?h=4bbad08d7a
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking dashsegments downloader on "https://77vod-adaptive.akamaized.net/exp=1659058745~acl=%2F0618ede3-20a2-4a52-a32e-44c4a96b416c%2F%2A~hmac=a6a4dda07993e9683e0c7c88c6b17aef1158cd48a261a2f2f5fa67157931d790/0618ede3-20a2-4a52-a32e-44c4a96b416c/sep/video/b5087da1,da35f3fd,90005495,0df34847/audio/c6a7f28c,e20cda7c,1fed0a50/master.mpd?query_string_ranges=1&base64_init=1"
[debug] Invoking dashsegments downloader on "https://77vod-adaptive.akamaized.net/exp=1659058745~acl=%2F0618ede3-20a2-4a52-a32e-44c4a96b416c%2F%2A~hmac=a6a4dda07993e9683e0c7c88c6b17aef1158cd48a261a2f2f5fa67157931d790/0618ede3-20a2-4a52-a32e-44c4a96b416c/sep/video/b5087da1,da35f3fd,90005495,0df34847/audio/c6a7f28c,e20cda7c,1fed0a50/master.mpd?query_string_ranges=1&base64_init=1"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Soz 51.mp4 [733024860].fdash-akfire_interconnect_quic_sep-video-0df34847.mp4' -i 'file:Soz 51.mp4 [733024860].fdash-akfire_interconnect_quic_sep-audio-1fed0a50.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Soz 51.mp4 [733024860].temp.mp4'
[debug] ffmpeg version 4.1.9-0+deb10u1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version=0+deb10u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Soz 51.mp4 [733024860].fdash-akfire_interconnect_quic_sep-video-0df34847.mp4':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: dashmp42mp41iso6
    creation_time   : 2022-07-24T20:16:39.000000Z
  Duration: 02:24:09.96, start: 0.000000, bitrate: 1527 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 1525 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2022-07-24T20:16:39.000000Z
      handler_name    : L-SMASH Video Handler
      encoder         : AVC Coding
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Soz 51.mp4 [733024860].fdash-akfire_interconnect_quic_sep-audio-1fed0a50.m4a':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: dashiso6mp41
    creation_time   : 2022-07-24T20:16:19.000000Z
    encoder         : Lavf59.17.101
  Duration: 02:24:10.01, start: -0.006500, bitrate: 98 kb/s
    Stream #1:0(und): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 96 kb/s (default)
    Metadata:
      creation_time   : 2022-07-24T20:16:19.000000Z
      handler_name    : SoundHandler
[mp4 @ 0x55887ce71e40] track 1: codec frame size is not set
[mp4 @ 0x55887ce71e40] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)


ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3236, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3406, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3388, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3367, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 126, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 816, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 313, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 351, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3236, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3406, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3388, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3367, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 126, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 816, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 313, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 351, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bot/./1449424315/run_this.py", line 17, in <module>
    get(url)
  File "/bot/./1449424315/run_this.py", line 15, in get
    yyy.download(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3281, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3257, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1422, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2661, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3238, in process_info
    self.report_error('Postprocessing: %s' % str(err))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 971, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 914, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
```

**Comment by pukkandan** [comment]
Update your ffmpeg

**Comment by carlosagh96** [comment]
It worked
