### ISSUE TITLE
[utils:sanitize_open] Empty value is replaced by placeholder

### ISSUE THREAD

**Issue by chapmanjacobd** [yt-dlp/yt-dlp#4485]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

yt-dlp tries to save to root directory `/`

```
-o '%(uploader)s/%(id)s.%(ext)s' => /id.ext
```

```
-o '%(uploader|NA)s/%(id)s.%(ext)s' => /id.ext
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -v -o '%(uploader)s/%(title).200B [%(id)s].%(ext)s' https://www.manyvids.com/Video/2868895/ASMR-Facetiming-Your-Naughty-Girlfriend/
[debug] Command-line config: ['-v', '-o', '%(uploader)s/%(title).200B [%(id)s].%(ext)s', 'https://www.manyvids.com/Video/2868895/ASMR-Facetiming-Your-Naughty-Girlfriend/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.13-200.fc36.x86_64-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [ManyVids] Extracting URL: https://www.manyvids.com/Video/2868895/ASMR-Facetiming-Your-Naughty-Girlfriend/
[ManyVids] 2868895: Downloading webpage
[ManyVids] 2868895: Downloading webpage
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2868895: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://d3373orltkomw3.cloudfront.net/1003142343/o1f9uc2qmlqvrb8n10o11m9u1eb8b.mp4?response-content-disposition=filename%3D%22o1f9uc2qmlqvrb8n10o11m9u1eb8b.mp4%22&response-content-type=mp4&Expires=1659117874&Signature=ijPGVrr9-0o6ye0Ar2TS0iKjJ-Ypp7SRn64Yd7OhNB3w1gw52bKKBgQjgZZnzJKUZQJZ6hUXAMMi6E6oFf8r--ShKUnfD5a8Oqe~Vjd6ulGriukN~l9cQvTVXf9BXq26~z~PRCfvGA6kaF16QjL-nucGYB6xoQxYjmKRqu6~QQfY3cO6TS-1mMlfIhQnA-CKvQI1oGCW78cU5PbufDbVgB5ukfCMjSTNlsdXOsY0LCFDXAgGOTxnbq-xHF-fKfXmX0Tp0Hp0KG0MJWB2oYkh1Y8WAbFyvt3zqNcvUOR9bAtXfdOJsfELY~-yx1DdnM~KxOlqYQNuRWI3cMCIP2yPsg__&Key-Pair-Id=APKAJK7FTSUZNXWC7PRA"
[download] Unable to open file due to file access error. Retrying (attempt 1 of 3) ...
[download] Unable to open file due to file access error. Retrying (attempt 2 of 3) ...
[download] Unable to open file due to file access error. Retrying (attempt 3 of 3) ...
ERROR: unable to open for writing: [Errno 13] Permission denied: '/Facetime Your Naughty Asian GF- ASMR [2868895].mp4.part'
Traceback (most recent call last):
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 626, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 2092, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
PermissionError: [Errno 13] Permission denied: '/Facetime Your Naughty Asian GF- ASMR [2868895].mp4.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 269, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 224, in inner
    return func(self, *args, **kwargs)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 242, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 628, in sanitize_open
    stream = open(filename, open_mode)
PermissionError: [Errno 13] Permission denied: '/Facetime Your Naughty Asian GF- ASMR [2868895].mp4.part'
```

**Comment by chapmanjacobd** [comment]
huh... this issue also effects some YT URLs

https://www.youtube.com/watch?v=x2-AjhE3H00

strange I never encountered this behavior until the past couple days--or maybe I never noticed because it doesn't happen often

**Comment by dirkf** [comment]
yt-dl renders such a filename (where `uploader` is an empty string and the output template begins with `%(uploader)s/`) as `_/...`.

**Comment by chapmanjacobd** [comment]
have you tried it? that is not the case for this specific video. Yes, for most videos I have seen either an `_` or an `NA` folder be created but this is something else:

```
yt-dlp -v -o '%(uploader)s/%(title).200B [%(id)s].%(ext)s' https://www.youtube.com/watch?v=x2-AjhE3H00
[debug] Command-line config: ['-v', '-o', '%(uploader)s/%(title).200B [%(id)s].%(ext)s', 'https://www.youtube.com/watch?v=x2-AjhE3H00']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.13-200.fc36.x86_64-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=x2-AjhE3H00
[youtube] x2-AjhE3H00: Downloading webpage
[youtube] x2-AjhE3H00: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] x2-AjhE3H00: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr3---sn-vgqsknly.googlevideo.com/videoplayback?expire=1659177284&ei=5LTkYsvyH4TuigTg1Zy4CA&ip=2601%3A245%3A0%3Ae%3Aaaa1%3A59ff%3Afe29%3A1ec6&id=o-AOSQ7u-w9N0axpKQoX2ykN-oRkHpykuNHSNfk8MqNbSC&itag=248&source=youtube&requiressl=yes&mh=tP&mm=31%2C29&mn=sn-vgqsknly%2Csn-vgqsrnl6&ms=au%2Crdu&mv=m&mvi=3&pl=32&initcwndbps=1966250&vprv=1&mime=video%2Fwebm&gir=yes&clen=2838759&dur=264.898&lmt=1657171060319866&mt=1659155333&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJt0_-iRW3AVZquIaEjXtul7F5Hs9bS272jBM5sQtRNICIAMfhFnfMy52EZO8i6w5yINeBHgizgVP6g4X3S6CRizg&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgMGgSEyI2wmPMSBn1WUlpd_V-58zRO_3jZ6mRA1YApxkCICTVMU9Kf2aCz6zOH6EFuI8trL6j0FuVwc8YKk00NMuv"
[download] Unable to open file due to file access error. Retrying (attempt 1 of 3) ...
[download] Unable to open file due to file access error. Retrying (attempt 2 of 3) ...
[download] Unable to open file due to file access error. Retrying (attempt 3 of 3) ...
ERROR: unable to open for writing: [Errno 13] Permission denied: "/Me You Us Them - 'Humilitarian' [x2-AjhE3H00].f248.webm.part"
Traceback (most recent call last):
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 626, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 2092, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
PermissionError: [Errno 13] Permission denied: "/Me You Us Them - 'Humilitarian' [x2-AjhE3H00].f248.webm.part"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 269, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 224, in inner
    return func(self, *args, **kwargs)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 242, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/home/xk/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 628, in sanitize_open
    stream = open(filename, open_mode)
PermissionError: [Errno 13] Permission denied: "/Me You Us Them - 'Humilitarian' [x2-AjhE3H00].f248.webm.part"
```

**Comment by pukkandan** [comment]
dirkf is saying that this works correctly in `youtube-dl`

**Comment by pukkandan** [comment]
youtube-dl's handling of this is also a bit problematic:

```
❯ youtube-dl x2-AjhE3H00 --get-filename -o "%(uploader)s %(title)s"
_ Me You Us Them - 'Humilitarian'

❯ yt-dlp x2-AjhE3H00 --get-filename -o "%(uploader)s %(title)s"
 Me You Us Them - 'Humilitarian'
```
imo, What is needed is to instead convert empty fields into `None`

**Comment by chapmanjacobd** [comment]
something like this?

```
@>>> not ''
True

list(filter(bool, field))
```

not sure where this code needs to go though

**Comment by pukkandan** [comment]
It is easy enough to make yt-dlp behave like youtube-dl for this case

> imo, What is needed is to instead convert empty fields into None

Alternately, this is also easy to implement

```diff
diff --git a/yt_dlp/YoutubeDL.py b/yt_dlp/YoutubeDL.py
index e9a51cba4..2b7639d9e 100644
--- a/yt_dlp/YoutubeDL.py
+++ b/yt_dlp/YoutubeDL.py
@@ -1162,6 +1162,8 @@ def get_value(mdict):
             if mdict['strf_format']:
                 value = strftime_or_none(value, mdict['strf_format'].replace('\\,', ','))

+            if sanitize and not value:
+                value = None
             return value

         na = self.params.get('outtmpl_na_placeholder', 'NA')
```

But I am not convinced that either of these is the best way to go.

Eg: `yt-dlp x2-AjhE3H00 --get-filename -o "%(uploader)s\%(uploader)s\%(uploader)s %(title)s"`
Current: `/Me You Us Them - 'Humilitarian'`
With above patch: `NA/NA/Me You Us Them - 'Humilitarian'`
youtube-dl: `_/_/_ Me You Us Them - 'Humilitarian'`

Imo, the "correct" filename in this case should be `_/_/ Me You Us Them - 'Humilitarian'`. But this is actually quite tricky to implement correctly while accounting for Windows, UNIX and UNC paths

But the current situation is the worst of the options, so I'll implement it as `NA/NA/Me You Us Them - 'Humilitarian'` for the time being while we discuss other ideas

**Comment by chapmanjacobd** [comment]
I don't see the difference between

```
NA/NA/Me You Us Them - 'Humilitarian'
```

and 

```
_/_/ Me You Us Them - 'Humilitarian'
```

To me the bad behavior is already fixed. If someone will create a PR they can reference this closed ticket if they want or if a maintainer wants this to stay open they can re-open it
