### ISSUE TITLE
Enforce `--merge-output-format` values

### ISSUE THREAD

**Issue by WillPittenger** [yt-dlp/yt-dlp#4489]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I accidentally passed `--merge-output-format ` with the value `mpv` when I intended `mkv`.  yt-dlp accepted that as valid, but when it came time to merge my videos, ffmpeg reported an invalid command line.  I investigated by running ffmpeg manually and found it complaining about an unsupported audio format.  I think options like `--merge-output-format` should require the value found to be a known value unless something like `--ignore-format-errors` is passed.  (That would allow testing of yt-dlp with versions of ffmpeg that add more supported formats.)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/shorts/bc9-etZuONY', '-f', 'bv+ba', '--merge-output-format', 'mpv', '-v']
[debug] User config "C:\Users\willp\AppData\Roaming\yt-dlp\config.txt": ['--cookies-from-browser', 'firefox', '-o', 'c:\\users\\willp\\videos\\%(title)s.%(ext)s', '--recode-video', 'mp4', '--ffmpeg-location', 'c:\\Program Files\\ffmpeg\\bin', '-f', 'bestvideo+bestaudio/137+bestaudio[height<=1080]', '--no-abort-on-error', '--default-search', 'ytsearch', '--sponsorblock-mark', 'all', '--sponsorblock-remove', 'selfpromo,sponsor', '--embed-chapters', '-N', '10', '--live-from-start', '--wait-for-video', '3600']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\willp\AppData\Roaming\Mozilla\Firefox\Profiles\cjweyqzj.Default\cookies.sqlite"
[Cookies] Extracted 1311 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, out cp1252 (No ANSI), err cp1252 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: "c:\Program Files\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: "c:\Program Files\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg n4.4-4-gacb339bb88 (setts), ffprobe n4.4-4-gacb339bb88, rtmpdump 2.3
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/shorts/bc9-etZuONY
[youtube] bc9-etZuONY: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] bc9-etZuONY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/7ffa?service=YouTube&categories=%5B%22sponsor%22%2C+%22filler%22%2C+%22outro%22%2C+%22intro%22%2C+%22interaction%22%2C+%22poi_highlight%22%2C+%22preview%22%2C+%22selfpromo%22%2C+%22music_offtopic%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%5D
[SponsorBlock] Found 3 segments in the SponsorBlock database
[info] bc9-etZuONY: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr5---sn-vgqskn76.googlevideo.com/videoplayback?expire=1659182091&ei=q8fkYrufKrmGir4P7ruiiAM&ip=96.74.211.146&id=o-AAsEYrTb7iHW_vaZn8pPIs5majoRoh8JP0Jfv8kHOHt3&itag=248&source=youtube&requiressl=yes&mh=rF&mm=31%2C29&mn=sn-vgqskn76%2Csn-vgqsrnl6&ms=au%2Crdu&mv=m&mvi=5&pl=17&initcwndbps=2052500&vprv=1&mime=video%2Fwebm&gir=yes&clen=9133840&dur=59.726&lmt=1658851810629913&mt=1659160134&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5430434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJYVWWjjhaxjFSUpktfax1Z2uKVoQ1n2vEEoim6SbaGFAiEAyn4wml0cfzYRWJUEfjyqdH_0_biXlkyzYXUkHWOt5zM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANDErk2R_O31sbtVOjCZ8KDGBZzTmx9aTZ33zk7vjSWLAiB5uEff4gpKBMSbu_QO8wkz_KFJV7Ur7BPFQiroCtsWqA%3D%3D"
[debug] File locking is not supported on this platform. Proceeding without locking
[download] Destination: c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.f248.webm

[download]   0.0% of 8.71MiB at 333.65KiB/s ETA 00:26
[download]   0.0% of 8.71MiB at 750.59KiB/s ETA 00:11
[download]   0.1% of 8.71MiB at  1.37MiB/s ETA 00:06 
[download]   0.2% of 8.71MiB at  2.44MiB/s ETA 00:03
[download]   0.3% of 8.71MiB at 484.45KiB/s ETA 00:18
[download]   0.7% of 8.71MiB at 611.69KiB/s ETA 00:14
[download]   1.4% of 8.71MiB at 835.58KiB/s ETA 00:10
[download]   2.9% of 8.71MiB at  1.15MiB/s ETA 00:07 
[download]   5.7% of 8.71MiB at  1.54MiB/s ETA 00:05
[download]  11.5% of 8.71MiB at  1.44MiB/s ETA 00:05
[download]  22.9% of 8.71MiB at  1.54MiB/s ETA 00:04
[download]  41.9% of 8.71MiB at  1.08MiB/s ETA 00:04
[download]  51.3% of 8.71MiB at  1.12MiB/s ETA 00:03
[download]  66.8% of 8.71MiB at 977.23KiB/s ETA 00:03
[download]  74.5% of 8.71MiB at 997.84KiB/s ETA 00:02
[download]  88.2% of 8.71MiB at 1019.57KiB/s ETA 00:01
[download] 100% of 8.71MiB at  1.06MiB/s ETA 00:00    
[download] 100% of 8.71MiB in 00:08               
[debug] Invoking downloader on "https://rr5---sn-vgqskn76.googlevideo.com/videoplayback?expire=1659182091&ei=q8fkYrufKrmGir4P7ruiiAM&ip=96.74.211.146&id=o-AAsEYrTb7iHW_vaZn8pPIs5majoRoh8JP0Jfv8kHOHt3&itag=251&source=youtube&requiressl=yes&mh=rF&mm=31%2C29&mn=sn-vgqskn76%2Csn-vgqsrnl6&ms=au%2Crdu&mv=m&mvi=5&pl=17&initcwndbps=2052500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=1016064&dur=59.741&lmt=1658850490101272&mt=1659160134&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALUkSd5i5_Nl_Nn0YgT0_U1TZNbr9kQvAQ_neheIJL8eAiEAqNps2S0GA1675rcIVy94nWt-ueIwUTj-wxze6J9o6d0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANDErk2R_O31sbtVOjCZ8KDGBZzTmx9aTZ33zk7vjSWLAiB5uEff4gpKBMSbu_QO8wkz_KFJV7Ur7BPFQiroCtsWqA%3D%3D"
[download] Destination: c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.f251.webm

[download]   0.1% of 992.25KiB at 102.04KiB/s ETA 00:09
[download]   0.3% of 992.25KiB at 279.17KiB/s ETA 00:03
[download]   0.7% of 992.25KiB at 593.03KiB/s ETA 00:01
[download]   1.5% of 992.25KiB at  1.15MiB/s ETA 00:00 
[download]   3.1% of 992.25KiB at 1008.28KiB/s ETA 00:00
[download]   6.3% of 992.25KiB at  1.01MiB/s ETA 00:00  
[download]  12.8% of 992.25KiB at  1.22MiB/s ETA 00:00
[download]  25.7% of 992.25KiB at  1.59MiB/s ETA 00:00
[download]  51.5% of 992.25KiB at  2.06MiB/s ETA 00:00
[download] 100% of 992.25KiB at  2.17MiB/s ETA 00:00  
[download] 100% of 992.25KiB in 00:00               
[Merger] Merging formats into "c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.mpv"
[debug] ffmpeg command line: "c:\Program Files\ffmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.f248.webm" -i "file:c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.temp.mpv"
[debug] ffmpeg version n4.4-4-gacb339bb88 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-vulkan --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --enable-libglslang --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from 'file:c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.f248.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:00:59.73, start: 0.000000, bitrate: 1223 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1080x1920, SAR 1:1 DAR 9:16, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:00:59.74, start: -0.007000, bitrate: 136 kb/s
  Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
[NULL @ 000001e40dc3ca40] Unable to find a suitable output format for 'file:c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.temp.mpv'
file:c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.temp.mpv: Invalid argument
ERROR: Postprocessing: file:c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.temp.mpv: Invalid argument
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3211, in process_info
  File "yt_dlp\YoutubeDL.py", line 3379, in post_process
  File "yt_dlp\YoutubeDL.py", line 3366, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3339, in run_pp
  File "yt_dlp\postprocessor\common.py", line 27, in run
  File "yt_dlp\postprocessor\common.py", line 124, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 828, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 288, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 327, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:c:\users\willp\videos\Name That Infrastructure (Ep. 10) #shorts.temp.mpv: Invalid argument
```
```

**Comment by pukkandan** [comment]
While we are at this, I should also consolidate the list of "known extensions". Currently different parts of the code have different subsets of this.

https://github.com/yt-dlp/yt-dlp/blob/f640e42ffa4049aa702f707be8a6c4472af9cbeb/yt_dlp/postprocessor/ffmpeg.py#L34-L57
https://github.com/yt-dlp/yt-dlp/blob/f640e42ffa4049aa702f707be8a6c4472af9cbeb/yt_dlp/postprocessor/ffmpeg.py#L423-L425
https://github.com/yt-dlp/yt-dlp/blob/f640e42ffa4049aa702f707be8a6c4472af9cbeb/yt_dlp/postprocessor/ffmpeg.py#L530-L531
https://github.com/yt-dlp/yt-dlp/blob/f640e42ffa4049aa702f707be8a6c4472af9cbeb/yt_dlp/postprocessor/ffmpeg.py#L570-L571
https://github.com/yt-dlp/yt-dlp/blob/f640e42ffa4049aa702f707be8a6c4472af9cbeb/yt_dlp/postprocessor/ffmpeg.py#L1045-L1046
https://github.com/yt-dlp/yt-dlp/blob/f640e42ffa4049aa702f707be8a6c4472af9cbeb/yt_dlp/YoutubeDL.py#L545-L549
https://github.com/yt-dlp/yt-dlp/blob/f640e42ffa4049aa702f707be8a6c4472af9cbeb/yt_dlp/utils.py#L153-L166
