### ISSUE TITLE
Number each chapter from 1

### ISSUE THREAD

**Issue by blueray453** [yt-dlp/yt-dlp#4492]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I currently use

    -o '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s'

It download video like

```
Playlist1/1 - Chapter1/1 - Video1.mp4
Playlist1/1 - Chapter1/2 - Video2.mp4
Playlist1/1 - Chapter1/3 - Video3.mp4

Playlist1/2 - Chapter2/4 - Video4.mp4
Playlist1/2 - Chapter2/5 - Video5.mp4
Playlist1/2 - Chapter2/6 - Video6.mp4
```

But I want to be like:

```
Playlist1/1 - Chapter1/1 - Video1.mp4
Playlist1/1 - Chapter1/2 - Video2.mp4
Playlist1/1 - Chapter1/3 - Video3.mp4

Playlist1/2 - Chapter2/1 - Video4.mp4
Playlist1/2 - Chapter2/2 - Video5.mp4
Playlist1/2 - Chapter2/3 - Video6.mp4
```
I mean I want to number video from each chapter starting with 1.

How can I do that?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by blueray453** [comment]
I mean what should i use instead of `%(playlist_index)s`

**Comment by pukkandan** [comment]
Provide verbose log with example URL

**Comment by blueray453** [comment]
```
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', '-o', '%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', '-S', 'height:480', 'https://www.udemy.com/java-tutorial/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.15.0-41-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/ismail/.mozilla/firefox/flhbe79l.default-release/cookies.sqlite"
[Cookies] Extracted 2158 cookies from firefox
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [udemy:course] Extracting URL: https://www.udemy.com/java-tutorial/
[udemy:course] java-tutorial: Downloading webpage
[udemy:course] 24823: Downloading course curriculum
[download] Downloading playlist: 24823
[udemy:course] Playlist 24823: Downloading 70 videos of 70
[download] Downloading video 1 of 70
[debug] [udemy] Extracting URL: https://www.udemy.com/java-tutorial/learn/v4/t/lecture/172757
[udemy] 172757: Downloading webpage
[udemy] 172757: Downloading lecture JSON
[udemy] 160614: Downloading m3u8 information
[debug] Sort order given by user: height:480
[debug] Formats sorted by: hasvid, ie_pref, height:480(480.0), lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 160614: Downloading 1 format(s): hls-506
[debug] Invoking hlsnative downloader on "https://www.udemy.com/assets/160614/files/24823/160614/2012-11-23_04-49-02-f6c41c3371410cb1cc8e4a7d82d938c3/1/hls/AVC_768x432_600k_AAC-HE_64k/aa002c77eaf6f4b3fb873eb5d8ef237c6a6a.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjQ4MjMvMTYwNjE0LzIwMTItMTEtMjNfMDQtNDktMDItZjZjNDFjMzM3MTQxMGNiMWNjOGU0YTdkODJkOTM4YzMvMS8iLCJleHAiOjE2NTkxOTY4Mzh9.Co07xK75r-_-W8AWwq85mCRffXhmaPyUtCEXZW9rlpk&v=1"
[download] 1 - Introduction/01-Introduction and Installation.mp4 has already been downloaded
[download] 100% of 6.31MiB
[download] Downloading video 2 of 70
[debug] [udemy] Extracting URL: https://www.udemy.com/java-tutorial/learn/v4/t/lecture/172760
[udemy] 172760: Downloading webpage
[udemy] 172760: Downloading lecture JSON
ERROR: [udemy] 160617: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1804, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1631, in process_ie_result
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2481, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1002, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [udemy] 160617: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading video 3 of 70
[debug] [udemy] Extracting URL: https://www.udemy.com/java-tutorial/learn/v4/t/lecture/172762
[udemy] 172762: Downloading webpage
[udemy] 172762: Downloading lecture JSON
ERROR: [udemy] 160620: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1804, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1631, in process_ie_result
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2481, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1002, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [udemy] 160620: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading video 4 of 70
[debug] [udemy] Extracting URL: https://www.udemy.com/java-tutorial/learn/v4/t/lecture/262683
[udemy] 262683: Downloading webpage
[udemy] 262683: Downloading lecture JSON
ERROR: [udemy] 278943: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1804, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1631, in process_ie_result
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2481, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1002, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [udemy] 278943: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading video 5 of 70
[debug] [udemy] Extracting URL: https://www.udemy.com/java-tutorial/learn/v4/t/lecture/131404
[udemy] 131404: Downloading webpage
[udemy] 131404: Downloading lecture JSON
ERROR: [udemy] 129980: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1804, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1631, in process_ie_result
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2481, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1002, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [udemy] 129980: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading video 6 of 70
[debug] [udemy] Extracting URL: https://www.udemy.com/java-tutorial/learn/v4/t/lecture/131409
[udemy] 131409: Downloading webpage
[udemy] 131409: Downloading lecture JSON
ERROR: [udemy] 129985: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1804, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1631, in process_ie_result
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2481, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1002, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [udemy] 129985: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading video 7 of 70
[debug] [udemy] Extracting URL: https://www.udemy.com/java-tutorial/learn/v4/t/lecture/131416
[udemy] 131416: Downloading webpage
[udemy] 131416: Downloading lecture JSON
[udemy] 129992: Downloading m3u8 information
[debug] Sort order given by user: height:480
[debug] Formats sorted by: hasvid, ie_pref, height:480(480.0), lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 129992: Downloading 1 format(s): hls-221
[debug] Invoking hlsnative downloader on "https://www.udemy.com/assets/129992/files/24823/129992/2012-09-29_15-59-50-a4f6c07bbb15c48c883eb95c667a5b9d/1/hls/AVC_768x432_150k_AAC-HE_64k/aa006b90104b590114fcae195d949db16f4a.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjQ4MjMvMTI5OTkyLzIwMTItMDktMjlfMTUtNTktNTAtYTRmNmMwN2JiYjE1YzQ4Yzg4M2ViOTVjNjY3YTViOWQvMS8iLCJleHAiOjE2NTkxOTY4NTN9.R-qmSTUWLTvxgdC4NGs-HCSmBTR9yl6E-ZJt9_uTY2U&v=1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 94
[download] Destination: 2 - Programming Core Java/07-Strings - Working With Text.mp4
[download] 100% of 14.84MiB in 00:42
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:2 - Programming Core Java/07-Strings - Working With Text.mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "2 - Programming Core Java/07-Strings - Working With Text.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:2 - Programming Core Java/07-Strings - Working With Text.mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:2 - Programming Core Java/07-Strings - Working With Text.temp.mp4'
[download] Downloading video 8 of 70
[debug] [udemy] Extracting URL: https://www.udemy.com/java-tutorial/learn/v4/t/lecture/131490
[udemy] 131490: Downloading webpage
[udemy] 131490: Downloading lecture JSON
ERROR: [udemy] 130071: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1804, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1631, in process_ie_result
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2481, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1002, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [udemy] 130071: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading video 9 of 70
[debug] [udemy] Extracting URL: https://www.udemy.com/java-tutorial/learn/v4/t/lecture/131596
[udemy] 131596: Downloading webpage
[udemy] 131596: Downloading lecture JSON
[udemy] 130179: Downloading m3u8 information
[debug] Sort order given by user: height:480
[debug] Formats sorted by: hasvid, ie_pref, height:480(480.0), lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 130179: Downloading 1 format(s): hls-219
[debug] Invoking hlsnative downloader on "https://www.udemy.com/assets/130179/files/24823/130179/2012-09-30_12-50-09-c7522b45f69f038998bc730634989b19/1/hls/AVC_768x432_150k_AAC-HE_64k/aa0028c6a6cc6f80505d985eefa708d13e4c.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjQ4MjMvMTMwMTc5LzIwMTItMDktMzBfMTItNTAtMDktYzc1MjJiNDVmNjlmMDM4OTk4YmM3MzA2MzQ5ODliMTkvMS8iLCJleHAiOjE2NTkxOTY5MDF9.YGu7MFdngSIY_TYD3GkLGRAnxGVBYgwSrP7CWc6nx9s&v=1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 95
[download] Destination: 2 - Programming Core Java/09-For Loops.mp4
[download] 100% of 14.89MiB in 00:42
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:2 - Programming Core Java/09-For Loops.mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "2 - Programming Core Java/09-For Loops.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:2 - Programming Core Java/09-For Loops.mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:2 - Programming Core Java/09-For Loops.temp.mp4'
[download] Downloading video 10 of 70
[debug] [udemy] Extracting URL: https://www.udemy.com/java-tutorial/learn/v4/t/lecture/135211
[udemy] 135211: Downloading webpage
^Q
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
hm.. I hoped the example URL will be something I can test with. But I can't help much here. Try looking inside the infojson (-j) for any field that has the information you need. season_number/episode_number are likely candidates. If there is no usefull field, this will need to be added to the extractor

**Comment by blueray453** [comment]
Oh so there is no generic solutions like `%(chapter_index)s`? You have to work on specific extractors. 

In that case I would try to come up with a shell script to rename those files.

**Comment by pukkandan** [comment]
Generally, a "chapter" is a single video, so that doesn't make sense. This is the first time I'm seeing a chapter consisting of multiple videos. Perhaps season/episode might have been better fields for this

**Comment by blueray453** [comment]
Linkedin Learning also follow the same pattern.

**Comment by pukkandan** [comment]
Even if a new field is added, it will need to be set by the extractor
