### ISSUE TITLE
Youtube: unable to download video data: HTTP Error 404

### ISSUE THREAD

**Issue by serpro69** [yt-dlp/yt-dlp#4497]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

EU

### Provide a description that is worded well enough to be understood

Getting `ERROR: unable to download video data: HTTP Error 404: Not Found` on _some_ youtube videos (see video link in the output)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=WQJQl-lA9wQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.15.0-41-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=WQJQl-lA9wQ
[youtube] WQJQl-lA9wQ: Downloading webpage
[youtube] WQJQl-lA9wQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] WQJQl-lA9wQ: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr6---sn-5aupcvm-vnaz.googlevideo.com/videoplayback?expire=1659227580&ei=XHnlYtazL87UyAXs6pKABA&ip=51.175.128.141&id=o-AAX8yYwtAo46R70rCWrXO-r8sg7gx815J_wE_GBTEiuR&itag=22&source=youtube&requiressl=yes&mh=-L&mm=31%2C29&mn=sn-5aupcvm-vnaz%2Csn-5goeen7r&ms=au%2Crdu&mv=m&mvi=6&pl=20&initcwndbps=1847500&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=4296.806&lmt=1657829904414046&mt=1659205736&fvip=1&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgQBBnjaLH2jCrrMRFcZ_cgZsvJYnQ9nOYe3WncFt0WkwCIA0Uhl5PEUqqGT89ZYL1Eq5_eThlhjqkORQKCIRGzsXC&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANY7Ysn92fcy7Vbn20B5wPUmIQAXqEWqcyUmwtyKjtEtAiApqYZC-NCSURHeRJIT1OkQx6WC_gb-Ftq1pzRFv7BRJA%3D%3D"
[download] Resuming download at byte 1780890
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/sergio/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3160, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/sergio/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2860, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/sergio/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/home/sergio/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 375, in real_download
    establish_connection()
  File "/home/sergio/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 131, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/sergio/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3639, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
Same issue as https://github.com/yt-dlp/yt-dlp/issues/3372
