### ISSUE TITLE
[New extractor] Add support for player.fm

### ISSUE THREAD

**Issue by denaunistic** [yt-dlp/yt-dlp#4518]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United states

### Example URLs

https://player.fm/series/soccer-101/ep-109-its-kicking-off-how-have-the-rules-for-kickoff-changed-what-are-the-best-approaches-to-getting-the-game-underway-and-how-could-we-improve-on-the-present-system
https://player.fm/series/soccer-101/ep-108-what-is-a-front-office-and-how-does-it-work
https://player.fm/series/soccer-101

### Provide a description that is worded well enough to be understood

Currently yt-dlp cannot extract the audio from the website even using the generic extractor. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://player.fm/series/soccer-101/ep-109-its-kicking-off-how-have-the-rules-for-kickoff-changed-what-are-the-best-approaches-to-getting-the-game-underway-and-how-could-we-improve-on-the-present-system']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-14-git-882aac99d2-essentials_build-www.gyan.dev (setts), ffprobe 2022-07-14-git-882aac99d2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://player.fm/series/soccer-101/ep-109-its-kicking-off-how-have-the-rules-for-kickoff-changed-what-are-the-best-approaches-to-getting-the-game-underway-and-how-could-we-improve-on-the-present-system
[generic] ep-109-its-kicking-off-how-have-the-rules-for-kickoff-changed-what-are-the-best-approaches-to-getting-the-game-underway-and-how-could-we-improve-on-the-present-system: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] ep-109-its-kicking-off-how-have-the-rules-for-kickoff-changed-what-are-the-best-approaches-to-getting-the-game-underway-and-how-could-we-improve-on-the-present-system: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://player.fm/series/soccer-101/ep-109-its-kicking-off-how-have-the-rules-for-kickoff-changed-what-are-the-best-approaches-to-getting-the-game-underway-and-how-could-we-improve-on-the-present-system
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://player.fm/series/soccer-101/ep-109-its-kicking-off-how-have-the-rules-for-kickoff-changed-what-are-the-best-approaches-to-getting-the-game-underway-and-how-could-we-improve-on-the-present-system
```

**Comment by dirkf** [comment]
megaphone.fm, but the extractor doesn't match the URLs and wouldn't find the traffic.megaphone.fm link in plain sight, eg:
```
<a class="blatant" href="https://traffic.megaphone.fm/TAMC1098066258.mp3?updated=1659102129">MP3</a>
```
Problem URLs 1 and 3 fail.

Problem URL is found as HTML5 by yt-dlp (and yt-dl).

**Comment by coletdjnz** [comment]
> megaphone.fm, but the extractor doesn't match the URLs and wouldn't find the traffic.megaphone.fm link in plain sight, eg:
> 
> ```
> <a class="blatant" href="https://traffic.megaphone.fm/TAMC1098066258.mp3?updated=1659102129">MP3</a>
> ```
> 
> Problem URLs 1 and 3 fail.
> 
> Problem URL is found as HTML5 by yt-dlp (and yt-dl).

Hm, so this is a megaphone extractor format url.  We could either use it as a format directly without sending to megaphone or extract the id and let megaphone take care of the rest. Given the JSON metadata (see below) and the fact megaphone doesn't extract any extra formats, the former is probably better imo.

As for metadata, you can add `.json` on to the end of the url to get JSON data of the episode or series. There are further options you can configure to. Be careful of url params.

https://player.fm/series/soccer-101/ep-109-its-kicking-off-how-have-the-rules-for-kickoff-changed-what-are-the-best-approaches-to-getting-the-game-underway-and-how-could-we-improve-on-the-present-system.json
https://player.fm/series/soccer-101/ep-108-what-is-a-front-office-and-how-does-it-work.json

https://player.fm/series/soccer-101.json (equivalent to https://player.fm/series/2525539.json)
Include episode metadata: https://player.fm/series/soccer-101.json?detail=minimal&episode_detail=full&episode_offset=0&episode_order=newest&episode_limit=15

**Comment by pukkandan** [comment]
> Given the JSON metadata (see below) and the fact megaphone doesn't extract any extra formats, the former is probably better imo.

This could be problematic for archive. I'd suggest using url_transparent instead
