### ISSUE TITLE
ORF has changed the URLs for the Radiothek.

### ISSUE THREAD

**Issue by jogitgl** [yt-dlp/yt-dlp#4522]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria/Europe

### Provide a description that is worded well enough to be understood

ORF has changed the URLs for the Radiothek.
I have tested the new URLs in the file "orf.py" and the downloads are working now without problems.
ORF iptv I have never used and so I cannot say, if it is working.
The ORF Radiothek are active only for seven days and so it can be, that the links in the „TEST“ sections are not working, if you try.
I run a diff between „orf.py.orig“ (original file yt-dlp version 2022.07.18) and „orf.py“ (new file) .

```diff
diff orf.py.orig orf.py
==================================
209c209
<             'http://audioapi.orf.at/%s/api/json/current/broadcast/%s/%s'
---
>             'https://audioapi.orf.at/%s/api/json/current/broadcast/%s/%s'
246c246
<     _VALID_URL = r'https?://(?P<station>fm4)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>4\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>fm4)/(?P<date>[0-9]+)/(?P<show>4\w+)'
251,261c251
<         'url': 'http://fm4.orf.at/player/20170107/4CC',
<         'md5': '2b0be47375432a7ef104453432a19212',
<         'info_dict': {
<             'id': '2017-01-07_2100_tl_54_7DaysSat18_31295',
<             'ext': 'mp3',
<             'title': 'Solid Steel Radioshow',
<             'description': 'Die Mixshow von Coldcut und Ninja Tune.',
<             'duration': 3599,
<             'timestamp': 1483819257,
<             'upload_date': '20170107',
<         },
---
>         'url': 'https://radiothek.orf.at/fm4/20220801/4MO',
270c260
<     _VALID_URL = r'https?://(?P<station>noe)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>noe)/(?P<date>[0-9]+)/(?P<show>\w+)'
275c265
<         'url': 'https://noe.orf.at/player/20200423/NGM',
---
>         'url': 'https://radiothek.orf.at/noe/20220801/NGM',
283c273
<     _VALID_URL = r'https?://(?P<station>wien)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>wie)/(?P<date>[0-9]+)/(?P<show>\w+)'
288c278
<         'url': 'https://wien.orf.at/player/20200423/WGUM',
---
>         'url': 'https://radiothek.orf.at/wie/20220801/WGUM',
296c286
<     _VALID_URL = r'https?://(?P<station>burgenland)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>bgl)/(?P<date>[0-9]+)/(?P<show>\w+)'
301c291
<         'url': 'https://burgenland.orf.at/player/20200423/BGM',
---
>         'url': 'https://radiothek.orf.at/bgl/20220801/BGM',
309c299
<     _VALID_URL = r'https?://(?P<station>ooe)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>ooe)/(?P<date>[0-9]+)/(?P<show>\w+)'
314c304
<         'url': 'https://ooe.orf.at/player/20200423/OGMO',
---
>         'url': 'https://radiothek.orf.at/ooe/20220801/OGMO',
322c312
<     _VALID_URL = r'https?://(?P<station>steiermark)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>stm)/(?P<date>[0-9]+)/(?P<show>\w+)'
327c317
<         'url': 'https://steiermark.orf.at/player/20200423/STGMS',
---
>         'url': 'https://radiothek.orf.at/stm/20220801/STGMS',
335c325
<     _VALID_URL = r'https?://(?P<station>kaernten)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>ktn)/(?P<date>[0-9]+)/(?P<show>\w+)'
340c330
<         'url': 'https://kaernten.orf.at/player/20200423/KGUMO',
---
>         'url': 'https://radiothek.orf.at/ktn/20220801/KGUMO',
348c338
<     _VALID_URL = r'https?://(?P<station>salzburg)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>sbg)/(?P<date>[0-9]+)/(?P<show>\w+)'
353c343
<         'url': 'https://salzburg.orf.at/player/20200423/SGUM',
---
>         'url': 'https://radiothek.orf.at/sbg/20220801/SGUM',
361c351
<     _VALID_URL = r'https?://(?P<station>tirol)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>tir)/(?P<date>[0-9]+)/(?P<show>\w+)'
366c356
<         'url': 'https://tirol.orf.at/player/20200423/TGUMO',
---
>         'url': 'https://radiothek.orf.at/tir/20220801/TGUMO',
374c364
<     _VALID_URL = r'https?://(?P<station>vorarlberg)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>vbg)/(?P<date>[0-9]+)/(?P<show>\w+)'
379c369
<         'url': 'https://vorarlberg.orf.at/player/20200423/VGUM',
---
>         'url': 'https://radiothek.orf.at/vbg/20220801/VGUM',
387c377
<     _VALID_URL = r'https?://(?P<station>oe3)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>oe3)/(?P<date>[0-9]+)/(?P<show>\w+)'
392c382
<         'url': 'https://oe3.orf.at/player/20200424/3WEK',
---
>         'url': 'https://radiothek.orf.at/oe3/20220801/3WEK',
400c390
<     _VALID_URL = r'https?://(?P<station>oe1)\.orf\.at/player/(?P<date>[0-9]+)/(?P<show>\w+)'
---
>     _VALID_URL = r'https?://radiothek.orf.at/(?P<station>oe1)/(?P<date>[0-9]+)/(?P<show>\w+)'
405,414c395
<         'url': 'http://oe1.orf.at/player/20170108/456544',
<         'md5': '34d8a6e67ea888293741c86a099b745b',
<         'info_dict': {
<             'id': '2017-01-08_0759_tl_51_7DaysSun6_256141',
<             'ext': 'mp3',
<             'title': 'Morgenjournal',
<             'duration': 609,
<             'timestamp': 1483858796,
<             'upload_date': '20170108',
<         },
---
>         'url': 'https://radiothek.orf.at/oe1/20220801/686325',
============================================
```
I will add my new orf.py file as orf.py.zip

[orf.zip](https://github.com/yt-dlp/yt-dlp/files/9233130/orf.zip)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU  https://radiothek.orf.at/oe1/20220801/686325
[debug] Command-line config: ['-vU', 'https://radiothek.orf.at/oe1/20220801/686325']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0-full_build-www.gyan.dev (setts), ffprobe 5.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://radiothek.orf.at/oe1/20220801/686325
[generic] 686325: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 686325: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://radiothek.orf.at/oe1/20220801/686325
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://radiothek.orf.at/oe1/20220801/686325
```

**Comment by pukkandan** [comment]
The old URL patterns still seem to work, so the VALID_URL must handle both. I think the easiest way to add a new extractor that redirects the new URL patterns to the old one

**Comment by jogitgl** [comment]
> The old URL patterns still seem to work, so the VALID_URL must handle both. I think the easiest way to add a new extractor that redirects the new URL patterns to the old one

I have now created an ORF-URL in the old format and this URL also worked.
But on the ORF website I could find only URLs in the new format.

Where did you find the ORF-URLs in the old format?

**Comment by pukkandan** [comment]
Just tried out the test URLs

**Comment by jogitgl** [comment]
> Just tried out the test URLs

Since I can find only the new URL format on the ORF website, my opinion is, that an extractor only for the new URL format is sufficient.
Thanks a lot

**Comment by pukkandan** [comment]
> Since I can find only the new URL format on the ORF website, my opinion is, that an extractor only for the new URL format is sufficient.

No! since the URL works in browser, and support for it already exists, it will not be removed

**Comment by dirkf** [comment]
This?
```
     _VALID_URL = r'https?://(?P<new>radiothek\.orf\.at/)?(?P<station>\w+)(?(new)|\.orf\.at/player)/(?P<date>[0-9]+)/(?P<show>4\w+)'
```
