### ISSUE TITLE
Add 153news.net Support

### ISSUE THREAD

**Issue by CharlesRayburn** [yt-dlp/yt-dlp#4523]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States of America

### Example URLs

Channel: https://153news.net/view_channel.php?user=MattyD%204Truth

### Provide a description that is worded well enough to be understood

While single video work to an extent, there is no dedicated way to download a whole channel in one swoop.  While possible to individually add videos and do it manually, this is an issue for anyone trying to download channels with 50+ videos.  Downloading 1000+ video channels could very well wind up taking a week or more, which isn't time efficient by any stretch.  For those of us who see the imminent downfall of the site and wish to preserve the videos, support for full downloading of entire channels must be added.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://153news.net/view_channel.php?user=Bye%20Mouse']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://153news.net/view_channel.php?user=Bye%20Mouse
[generic] view_channel: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] view_channel: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://153news.net/view_channel.php?user=Bye%20Mouse
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://153news.net/view_channel.php?user=Bye%20Mouse
```

**Comment by pukkandan** [comment]
```py
import re
import urllib.parse

from yt_dlp.extractor.common import InfoExtractor


class OneFiveThreeNewsChannelIE(InfoExtractor):
    IE_NAME = '153news.net:channel'
    _VALID_URL = r'https?://153news\.net/view_channel\.php\?user=(?P<id>[^&#]+)'

    def _real_extract(self, url):
        channel_name = urllib.parse.unquote(self._match_id(url))
        webpage = self._download_webpage(url, channel_name)
        channel_id = self._search_regex(r'var\s+channelId\s*=\s*[\'"](\d+)', webpage, 'channel id')

        videos = self._download_webpage(
            f'https://153news.net/ajax/home.php', channel_name, note='Downloading list of videos',
            data=f'load_type=video&load_mode=user_videos&load_limit=999999&userid={channel_id}&load_hit=1'.encode())

        return self.playlist_from_matches(
            re.findall(r'<a\s[^>]*\bclass="video_link"[^>]+\bhref="([^">]+)', videos),
            channel_id, channel_name, ie='Generic')
```

Here's a plugin I quickly wrote. Hopefully someone can turn this to a proper extractor

TODO:
* add tests
* Add video IE with atleast `video_id` extraction
* Extract more metadata - thumbnail, duration, title are easily available in playlist page

**Comment by kgpjay** [comment]
Hi, I want to work on this issue  :)

**Comment by Arc8ne** [comment]
Hi @pukkandan and @kgpjay, sorry to necro this thread haha, just wanted to check if anyone is still working on this issue? If not, I was wondering if it could be assigned to me?

**Comment by raman118** [comment]
can i work on this issue if not resolved
