### ISSUE TITLE
`WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them` despite `--list-formats` being passed

### ISSUE THREAD

**Issue by gamer191** [yt-dlp/yt-dlp#4534]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

`WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them` is being output, despite me passing `--list-formats`. I suspect that this is reproducible on ever website that has drm protected content

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://www.youtube.com/watch?v=lNWJpl3U6UY --list-formats --verbose
[debug] Command-line config: ['https://www.youtube.com/watch?v=lNWJpl3U6UY', '--list-formats', '--verbose']
[debug] User config "C:\Users\redacted\AppData\Roaming\yt-dlp\config.txt": ['--ffmpeg-location', 'C:\\Users\\redacted\\ffmpeg\\bin', '-P', 'C:\\Users\\redacted\\youtube.dl', '--update', '--audio-quality', '0', '--write-subs', '--write-auto-subs', '--embed-subs', '--compat-options', 'no-keep-subs,no-live-chat']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Compatibility options: no-keep-subs, no-live-chat
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: "C:\Users\redacted\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: "C:\Users\redacted\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg N-106498-g854615adf2-20220405 (setts), ffprobe N-106498-g854615adf2-20220405
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=lNWJpl3U6UY
[youtube] lNWJpl3U6UY: Downloading webpage
[youtube] lNWJpl3U6UY: Downloading android player API JSON
[youtube] lNWJpl3U6UY: Downloading tv embedded player API JSON
[youtube] lNWJpl3U6UY: Downloading web embedded client config
[youtube] lNWJpl3U6UY: Downloading player 7a7465f5
[youtube] lNWJpl3U6UY: Downloading web embedded player API JSON
[debug] Loading youtube-nsig.7a7465f5 from cache
[debug] [youtube] Decrypted nsig fDRR89DXC67YpnXgT => RScpsqxSQ5M0lA
[youtube] lNWJpl3U6UY: Downloading MPD manifest
WARNING: [youtube] Failed to download MPD manifest: HTTP Error 404: Not Found
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them
ERROR: [youtube] lNWJpl3U6UY: This video is DRM protected
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1521, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1578, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2481, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1002, in raise_no_formats
yt_dlp.utils.ExtractorError: [youtube] lNWJpl3U6UY: This video is DRM protected


yt-dlp https://7plus.com.au/the-good-doctor?episode-id=GOOD05-018 --list-formats --verbose
[debug] Command-line config: ['https://7plus.com.au/the-good-doctor?episode-id=GOOD05-018', '--list-formats', '--verbose']
[debug] User config "C:\Users\redacted\AppData\Roaming\yt-dlp\config.txt": ['--ffmpeg-location', 'C:\\Users\\redacted\\ffmpeg\\bin', '-P', 'C:\\Users\\redacted\\youtube.dl', '--update', '--audio-quality', '0', '--write-subs', '--write-auto-subs', '--embed-subs', '--compat-options', 'no-keep-subs,no-live-chat']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Compatibility options: no-live-chat, no-keep-subs
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: "C:\Users\redacted\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: "C:\Users\redacted\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg N-106498-g854615adf2-20220405 (setts), ffprobe N-106498-g854615adf2-20220405
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [7plus] Extracting URL: https://7plus.com.au/the-good-doctor?episode-id=GOOD05-018
[7plus] GOOD05-018: Downloading JSON metadata
[7plus] GOOD05-018: Downloading m3u8 information
[7plus] GOOD05-018: Downloading MPD manifest
[7plus] GOOD05-018: Downloading MPD manifest
[7plus] GOOD05-018: Downloading MPD manifest
[7plus] GOOD05-018: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[7plus] GOOD05-018: Downloading JSON metadata
[debug] Downloading subtitles: en
WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them
ERROR: [7plus] GOOD05-018: This video is DRM protected
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1521, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1578, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2481, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1002, in raise_no_formats
yt_dlp.utils.ExtractorError: [7plus] GOOD05-018: This video is DRM protected
```

**Comment by pukkandan** [comment]
The video is geo-restricted. Could you show me the output of `yt-dlp -vUF --allow-unplayable-formats "URL"`

**Comment by pukkandan** [comment]
nvm; I didn't see the second log

**Comment by pukkandan** [comment]
There is actually no images available for it. The warning is wrong

**Comment by Vangelis66** [comment]
> The (youtube) video is geo-restricted

> nvm; I didn't see the second log

For clarity, the second video (in the **second log** by OP) is also geo-fenced here, but (unlike the **YT** one) the block can be circumvented  via ` --geo-bypass-country AU` 😜 ...
