### ISSUE TITLE
Support for SouthParkStudios.nu

### ISSUE THREAD

**Issue by RogueND** [yt-dlp/yt-dlp#4552]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Sweden

### Example URLs

- Single Video: https://www.southparkstudios.nu/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1

### Provide a description that is worded well enough to be understood

www.southparkstudios.nu is not currently supported, but other extensions of the site are supported. My request is to extend support to this additional extension.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\ytdl>yt-dlp -vU "https://www.southparkstudios.nu/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1"
[debug] Command-line config: ['-vU', 'https://www.southparkstudios.nu/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107627-g8e6759f10c-20220801 (setts), ffprobe N-107627-g8e6759f10c-20220801
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://www.southparkstudios.nu/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1
[generic] south-park-mexican-joker-season-23-ep-1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] south-park-mexican-joker-season-23-ep-1: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.southparkstudios.nu/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.southparkstudios.nu/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1
```

**Comment by coletdjnz** [comment]
Changing the domain to southpark.com works. Should simple to add in a SP NU extractor following same pattern as the others (see southpark.py)

**Comment by enrique-zarate** [comment]
I would like to do this! How can I test if the code works?

**Comment by bashonly** [comment]
This might not be such an easy fix. The SouthPark extractor is currently broken (because the MTVServices extractor is broken):

```
$ yt_dlp -v -F https://southpark.cc.com/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1
[debug] Command-line config: ['-v', '-F', 'https://southpark.cc.com/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656]
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.19.8-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.06.15.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1681 extractors
[debug] [southpark.cc.com] Extracting URL: https://southpark.cc.com/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1
[southpark.cc.com] south-park-mexican-joker-season-23-ep-1: Downloading webpage
ERROR: [southpark.cc.com] fi4nmu/south-park-mexican-joker-season-23-ep-1: Could not extract mgid; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/coop/git/yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/home/coop/git/yt-dlp/yt_dlp/extractor/mtv.py", line 326, in _real_extract
    mgid = self._extract_mgid(webpage)
  File "/home/coop/git/yt-dlp/yt_dlp/extractor/mtv.py", line 319, in _extract_mgid
    raise ExtractorError('Could not extract mgid')
 ```

**Comment by enrique-zarate** [comment]
Not sure if it's something related to geolocalization but I have this result:
```
[debug] Command-line config: ['-vU', 'https://www.southparkstudios.nu/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://www.southparkstudios.nu/episodes/fi4nmu/south-park-mexican-joker-season-23-ep-1
[generic] south-park-mexican-joker-season-23-ep-1: Downloading webpage
[redirect] Following redirect to https://www.southpark.lat/episodios/fi4nmu/south-park-guason-mexicano-temporada-23-ep-1[debug] [southpark.lat] Extracting URL: https://www.southpark.lat/episodios/fi4nmu/south-park-guason-mexicano-temporada-23-ep-1
[southpark.lat] south-park-guason-mexicano-temporada-23-ep-1: Downloading webpage
[download] 100% of 2.74MiB in 00:02 at 1.26MiB/s```

**Comment by bashonly** [comment]
Yeah, I think it's redirecting based on location. The `southparkstudios.nu` link redirects me to `southpark.cc.com`. And using the `www.southpark.lat` link from your log gives me a 404

**Comment by enrique-zarate** [comment]
Thanks. Can I be assigned to the issue or just PR?

**Comment by bashonly** [comment]
> Thanks. Can I be assigned to the issue or just PR?

PR

see https://github.com/yt-dlp/yt-dlp/issues/4928#issuecomment-1264540725
