### ISSUE TITLE
https://goostream.net/embed-8hyadbpi7k9m.html

### ISSUE THREAD

**Issue by thevoy** [yt-dlp/yt-dlp#4557]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Philippines

### Example URLs

https://goostream.net/embed-rn83ozs6pkyc.html

### Provide a description that is worded well enough to be understood

Looking to download from goostream.net

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\windows\Desktop\New folder (3)\yt-dlp>yt-dlp -vU https://goostream.net/embed-rn83ozs6pkyc.html
[debug] Command-line config: ['-vU', 'https://goostream.net/embed-rn83ozs6pkyc.html']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107627-g8e6759f10c-20220801 (setts), ffprobe N-107627-g8e6759f10c-20220801
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://goostream.net/embed-rn83ozs6pkyc.html
[generic] embed-rn83ozs6pkyc: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] embed-rn83ozs6pkyc: Extracting information
[debug] Looking for video embeds
[debug] Identified a HTML5 media
[download] Downloading playlist: video
[generic] Playlist video: Downloading 1 videos of 1
[download] Downloading video 1 of 1
ERROR: [generic] embed-rn83ozs6pkyc: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1804, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1578, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2481, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1002, in raise_no_formats
yt_dlp.utils.ExtractorError: [generic] embed-rn83ozs6pkyc: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Finished downloading playlist: video
```

**Comment by doe1080** [comment]
no longer available
