### ISSUE TITLE
GLIBCXX_3.4.30 not found even though it's installed

### ISSUE THREAD

**Issue by ghost573** [yt-dlp/yt-dlp#4573]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I get an error regarding "GLIBCXX_3.4.30" not found but when I ran `strings /usr/lib/libstdc++.so.6 |grep GLIBCXX |less` GLIBCXX_3.4.30 is installed on my system.

```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30

```
Here's my system information.
Linux anarchy 5.18.16-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000 x86_64 GNU/Linux

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=T549VoLca_Q', '-f', '244+251', '--merge-output-format=mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (linux_exe)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.16-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg present (needs_adtstoasc), ffprobe present
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=T549VoLca_Q
[youtube] T549VoLca_Q: Downloading webpage
[youtube] T549VoLca_Q: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] T549VoLca_Q: Downloading 1 format(s): 244+251
[debug] Invoking http downloader on "https://rr8---sn-v2u0n-hxad.googlevideo.com/videoplayback?expire=1659775961&ei=edftYsChLs-UvQTvormICw&ip=49.193.100.171&id=o-AMM2DnoUva9yCkZYtNj0odZUZdUS8tKe9mbm3lugzNnz&itag=244&source=youtube&requiressl=yes&mh=EL&mm=31%2C29&mn=sn-v2u0n-hxad%2Csn-v2u0n-ntqd&ms=au%2Crdu&mv=m&mvi=8&pl=17&initcwndbps=1383750&vprv=1&mime=video%2Fwebm&gir=yes&clen=1030051&dur=30.067&lmt=1496695355272880&mt=1659753891&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALu-TQ9lfD8dn4gBUI80v5yXWzB8DnyLIcnEe4j-8UObAiAFbkx6Gcu6a2UDmhbUefngCEU1sIyyIJMEjhqCyOTp8A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAP6sr4CvzUOwRcyp6mJEGAwPYARiYgOqFt0BX-fIqO9fAiEAxmrw7NX21gv3LqNvWV2BvsMk2gzqA8GmIRXZr265Hgg%3D"
[download] Not Acceptable R-word PSA [T549VoLca_Q].f244.webm has already been downloaded
[download] 100% of 1005.91KiB
[debug] Invoking http downloader on "https://rr8---sn-v2u0n-hxad.googlevideo.com/videoplayback?expire=1659775961&ei=edftYsChLs-UvQTvormICw&ip=49.193.100.171&id=o-AMM2DnoUva9yCkZYtNj0odZUZdUS8tKe9mbm3lugzNnz&itag=251&source=youtube&requiressl=yes&mh=EL&mm=31%2C29&mn=sn-v2u0n-hxad%2Csn-v2u0n-ntqd&ms=au%2Crdu&mv=m&mvi=8&pl=17&initcwndbps=1383750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=543900&dur=30.141&lmt=1496695282236205&mt=1659753891&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgc4X4PMJmMT2YKoD7_PCSCUlEGs-VyLGMGkI0JgqkLw8CIFA1dcBMVFILtPv1LlALtTcmXWiRQ_clkByE-_4O-Av1&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAP6sr4CvzUOwRcyp6mJEGAwPYARiYgOqFt0BX-fIqO9fAiEAxmrw7NX21gv3LqNvWV2BvsMk2gzqA8GmIRXZr265Hgg%3D"
[download] Not Acceptable R-word PSA [T549VoLca_Q].f251.webm has already been downloaded
[download] 100% of 531.15KiB
[Merger] Merging formats into "Not Acceptable R-word PSA [T549VoLca_Q].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Not Acceptable R-word PSA [T549VoLca_Q].f244.webm' -i 'file:Not Acceptable R-word PSA [T549VoLca_Q].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Not Acceptable R-word PSA [T549VoLca_Q].temp.mkv'
[debug] ffmpeg: /tmp/_MEIwV8WQp/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libzimg.so.2)
ffmpeg: /tmp/_MEIwV8WQp/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libsrt.so.1.5)

ERROR: Postprocessing: ffmpeg: /tmp/_MEIwV8WQp/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libsrt.so.1.5)
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 3236, in process_info
  File "yt_dlp/YoutubeDL.py", line 3406, in post_process
  File "yt_dlp/YoutubeDL.py", line 3388, in run_all_pps
  File "yt_dlp/YoutubeDL.py", line 3367, in run_pp
  File "yt_dlp/postprocessor/common.py", line 25, in run
  File "yt_dlp/postprocessor/common.py", line 126, in wrapper
  File "yt_dlp/postprocessor/ffmpeg.py", line 816, in run
  File "yt_dlp/postprocessor/ffmpeg.py", line 313, in run_ffmpeg_multiple_files
  File "yt_dlp/postprocessor/ffmpeg.py", line 351, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg: /tmp/_MEIwV8WQp/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libsrt.so.1.5)
```

**Comment by pukkandan** [comment]
Try running `ffmpeg` by itself. The error is coming from ffmpeg. You should report to them

**Comment by ghost573** [comment]
I'm using your custom build of ffmpeg so I wasn't sure if I should report it to them.

**Comment by pukkandan** [comment]
oh, do you also get the issue with official ffmpeg?

**Comment by ghost573** [comment]
Haven't tested it, will do it now.

**Comment by Lesmiscore** [comment]
I think the bundled libstdc++.so is too old, apart from the one in the system.
Have you tried to run it by itself?

**Comment by ghost573** [comment]
I do get the same error when I use the official ffmpeg, I'll try running it by itself to see if it works.

**Comment by pukkandan** [comment]
I have a guess

> [debug] ffmpeg: /tmp/_MEIwV8WQp/libstdc++.so.6: version `GLIBCXX_3.4.30' not found

ffmpeg is trying to use the glibc that is inside yt-dlp.exe

---

Can you reproduce the issue when using other variants of yt-dlp? (PIP/zipimport)

**Comment by ghost573** [comment]
>Can you reproduce the issue when using other variants of yt-dlp? (PIP/zipimport)

Yes, I can. I tried the normal linux binary and the zip folder with the same result.

```
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=OtvKUrJnKfQ', '-f', '136+251', '--merge-output-format=mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (linux_dir)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.16-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg present (needs_adtstoasc), ffprobe present
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=OtvKUrJnKfQ
[youtube] OtvKUrJnKfQ: Downloading webpage
[youtube] OtvKUrJnKfQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] OtvKUrJnKfQ: Downloading 1 format(s): 136+251
[debug] Invoking http downloader on "https://rr3---sn-v2u0n-hxa6.googlevideo.com/videoplayback?expire=1659877020&ei=PGLvYsTfHZacvQSQzLigAg&ip=49.193.100.171&id=o-AAqfUx0VwBrVHjLiKfZAZCF0xepLHqSL-eKCfl1BlYLM&itag=136&source=youtube&requiressl=yes&mh=hK&mm=31%2C29&mn=sn-v2u0n-hxa6%2Csn-v2u0n-ntqk&ms=au%2Crdu&mv=m&mvi=3&pl=17&initcwndbps=1432500&vprv=1&mime=video%2Fmp4&gir=yes&clen=9506021&dur=101.434&lmt=1640349293744512&mt=1659854927&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgT6vXI2oQF9nZyERUWhY0u0RxCL0afBPJepYnAwGKzWECIHY-ltd54YvmiPnLtSBVFuZIGtS65-gib1w_Dr-VCrez&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMXerd7jbCNh-LS9bwM07FU8ytwkjB0ioFo5wBq1_uB_AiAern-o9QOjmFffJo1Nj0-8RRB8z-kYMy4RBZC50Ythxw%3D%3D"
[download] Destination: 仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].f136.mp4
[download] 100% of 9.07MiB in 00:03
[debug] Invoking http downloader on "https://rr3---sn-v2u0n-hxa6.googlevideo.com/videoplayback?expire=1659877020&ei=PGLvYsTfHZacvQSQzLigAg&ip=49.193.100.171&id=o-AAqfUx0VwBrVHjLiKfZAZCF0xepLHqSL-eKCfl1BlYLM&itag=251&source=youtube&requiressl=yes&mh=hK&mm=31%2C29&mn=sn-v2u0n-hxa6%2Csn-v2u0n-ntqk&ms=au%2Crdu&mv=m&mvi=3&pl=17&initcwndbps=1432500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=1317384&dur=101.461&lmt=1640348603571017&mt=1659854927&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALKpHZLikotMRea-WLl4zABAtoGbCd8I759EDB_YdZieAiALp32Di5tq4qg1RdHnpB04w7h3twibL-TydVk5fgxcLg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMXerd7jbCNh-LS9bwM07FU8ytwkjB0ioFo5wBq1_uB_AiAern-o9QOjmFffJo1Nj0-8RRB8z-kYMy4RBZC50Ythxw%3D%3D"
[download] Destination: 仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].f251.webm
[download] 100% of 1.26MiB in 00:00
[Merger] Merging formats into "仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].f136.mp4' -i 'file:仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].temp.mkv'
[debug] ffmpeg: /home/metabox/Downloads/yt-dlp_linux/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libzimg.so.2)
ffmpeg: /home/metabox/Downloads/yt-dlp_linux/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libsrt.so.1.5)

ERROR: Postprocessing: ffmpeg: /home/metabox/Downloads/yt-dlp_linux/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libsrt.so.1.5)
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 3236, in process_info
  File "yt_dlp/YoutubeDL.py", line 3406, in post_process
  File "yt_dlp/YoutubeDL.py", line 3388, in run_all_pps
  File "yt_dlp/YoutubeDL.py", line 3367, in run_pp
  File "yt_dlp/postprocessor/common.py", line 25, in run
  File "yt_dlp/postprocessor/common.py", line 126, in wrapper
  File "yt_dlp/postprocessor/ffmpeg.py", line 816, in run
  File "yt_dlp/postprocessor/ffmpeg.py", line 313, in run_ffmpeg_multiple_files
  File "yt_dlp/postprocessor/ffmpeg.py", line 351, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg: /home/metabox/Downloads/yt-dlp_linux/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libsrt.so.1.5)
```

**Comment by pukkandan** [comment]
That is not the on I meant. This: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp

**Comment by ghost573** [comment]
Sorry about that, wasn't sure which I had to download.
Python version works correctly.

```
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=OtvKUrJnKfQ', '-f', '136+251', '--merge-output-format=mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.16-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=OtvKUrJnKfQ
[youtube] OtvKUrJnKfQ: Downloading webpage
[youtube] OtvKUrJnKfQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] OtvKUrJnKfQ: Downloading 1 format(s): 136+251
[debug] Invoking http downloader on "https://rr3---sn-v2u0n-hxa6.googlevideo.com/videoplayback?expire=1659901879&ei=V8PvYviBLJTBrtoPwvGFmAk&ip=49.193.100.171&id=o-ADNDj7Kbv6100CXH93orAztGrV5qA3MDhKX3FasgtM15&itag=136&source=youtube&requiressl=yes&mh=hK&mm=31%2C29&mn=sn-v2u0n-hxa6%2Csn-v2u0n-ntqk&ms=au%2Crdu&mv=m&mvi=3&pl=17&initcwndbps=1382500&vprv=1&mime=video%2Fmp4&gir=yes&clen=9506021&dur=101.434&lmt=1640349293744512&mt=1659879894&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJZb4czwnBan-7FMMVW1jr3z42N9aeyX8Rh9H2VxdUs4CIF732bFSGMjqk7pnscfKGjRVOeVqMfz3Qo9LPfRFOxOO&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMlOv1ppBfSPgUmuhTJP2EPP3wazSsblu24H441SRJGMAiBEDht9p5Oy136eANLVBTUKWLAQVWIFF3mJRguj8EnVBg%3D%3D"
[download] Destination: 仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].f136.mp4
[download] 100% of 9.07MiB in 00:01
[debug] Invoking http downloader on "https://rr3---sn-v2u0n-hxa6.googlevideo.com/videoplayback?expire=1659901879&ei=V8PvYviBLJTBrtoPwvGFmAk&ip=49.193.100.171&id=o-ADNDj7Kbv6100CXH93orAztGrV5qA3MDhKX3FasgtM15&itag=251&source=youtube&requiressl=yes&mh=hK&mm=31%2C29&mn=sn-v2u0n-hxa6%2Csn-v2u0n-ntqk&ms=au%2Crdu&mv=m&mvi=3&pl=17&initcwndbps=1382500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=1317384&dur=101.461&lmt=1640348603571017&mt=1659879894&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgWRXAk7lLfZuz4MJulLWY1VcrSBCKR4027hpZPTObg5sCIDpywD9ylong9qgZjU8XZDfdXNBnMrFYR3rsBDGpyNAc&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMlOv1ppBfSPgUmuhTJP2EPP3wazSsblu24H441SRJGMAiBEDht9p5Oy136eANLVBTUKWLAQVWIFF3mJRguj8EnVBg%3D%3D"
[download] Destination: 仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].f251.webm
[download] 100% of 1.26MiB in 00:00
[Merger] Merging formats into "仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].f136.mp4' -i 'file:仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].temp.mkv'
Deleting original file 仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].f136.mp4 (pass -k to keep)
Deleting original file 仮面ライダー50周年、昭和ライダー変身集+α [OtvKUrJnKfQ].f251.webm (pass -k to keep)
```

**Comment by Lesmiscore** [comment]
I suppose unsetting `LD_LIBRARY_PATH` at the start of process (or at Popen) fixes this problem, no matter what build/host system is

```
$ ./yt-dlp_linux --exec 'env ; true' test:Youtube_2 | grep LD
LD_LIBRARY_PATH=/tmp/_MEI4S63Fk
```

**Comment by pukkandan** [comment]
@Lesmiscore Want to make a PR?

**Comment by Lesmiscore** [comment]
Sure
