### ISSUE TITLE
VK downloading error

### ISSUE THREAD

**Issue by finn1199** [yt-dlp/yt-dlp#4581]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I upgraded yt-dlp for today and it didn't work for any VK-URLs at all now.
I used May version before and it worked fine.

Youtube downloading works fine...

Ubuntu 22.04 OS

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -f b --merge-output-format mp4 -o Видео/'%(title)s.%(ext)s' https://vk.com/video-173637871_456242073
[vk] -173637871_456242073: Downloading JSON metadata
ERROR: 'generator' object is not subscriptable



$ yt-dlp -vU https://vk.com/video-173637871_456242073
[debug] Command-line config: ['-vU', 'https://vk.com/video-173637871_456242073']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05ef6]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.15.0-33-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [vk] Extracting URL: https://vk.com/video-173637871_456242073
[vk] -173637871_456242073: Downloading JSON metadata
ERROR: 'generator' object is not subscriptable
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1440, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1516, in __extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 665, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/vk.py", line 452, in _real_extract
    return self.url_result(dailymotion_urls[0], DailymotionIE.ie_key())
TypeError: 'generator' object is not subscriptable
```

**Comment by krasnh** [comment]
>Work with:
--cookies
--cookies-from-browser
https://github.com/yt-dlp/yt-dlp/pull/4128#issuecomment-1203546033

```
$ yt-dlp  https://vk.com/video-173637871_456242073 
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 496 cookies from firefox
[vk] -173637871_456242073: Downloading JSON metadata
[vk] -173637871_456242073: Downloading m3u8 information
[info] -173637871_456242073: Downloading 1 format(s): hls-3467
[download] Необычный освежитель воздуха [-173637871_456242073].mp4 has already been downloaded
[download] 100% of 5.26MiB

$ lh *.mp4                                        
-rw-r--r-- 1 live live 5,3M авг  6 17:33 'Необычный освежитель воздуха [-173637871_456242073].mp4'


```

**Comment by krasnh** [comment]
Must be compiled no later than Jul 27, 2022.
https://github.com/yt-dlp/yt-dlp/commit/59f63c8f0facb71208c8c131935fc4317e96f8b4

**Comment by krasnh** [comment]
full exhaust:
```
$ yt-dlp -vU https://vk.com/video-173637871_456242073
[debug] Command-line config: ['-vU', 'https://vk.com/video-173637871_456242073']
[debug] User config "/home/live/.config/yt-dlp/config": ['--cookies-from-browser=firefox:jvjddxlz.default-1626613399792']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05ef6] (linux_exe)
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.0-pf3-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: certifi-2022.06.15, sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/live/.mozilla/firefox/jvjddxlz.default-1626613399792/cookies.sqlite"
[Cookies] Extracted 498 cookies from firefox
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [vk] Extracting URL: https://vk.com/video-173637871_456242073
[vk] -173637871_456242073: Downloading JSON metadata
[vk] -173637871_456242073: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -173637871_456242073: Downloading 1 format(s): hls-3467
[debug] Invoking hlsnative downloader on "https://vk9-3.vkuser.net/expires/1660058016821/srcIp/188.64.133.156/pr/40/srcAg/CHROME/ms/87.240.184.194/type/3/sig/XF5ZN06Bxxo/ct/8/urls/45.136.20.180%3B45.136.21.149/clientType/13/zs/12/id/2113275169400/video/"
[download] Необычный освежитель воздуха [-173637871_456242073].mp4 has already been downloaded
[download] 100% of 5.26MiB

```

**Comment by krasnh** [comment]
> ERROR: 'generator' object is not subscriptable

Compiled yt-dlp, today's git slice. Got the same error.

```
$ ./yt-dlp -vU https://vk.com/video-173637871_456242073
[debug] Command-line config: ['-vU', 'https://vk.com/video-173637871_456242073']
[debug] User config "/home/live/.config/yt-dlp/config": ['--cookies-from-browser=firefox:jvjddxlz.default-1626613399792']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05ef6] (zip)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.0-pf3-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/live/.mozilla/firefox/jvjddxlz.default-1626613399792/cookies.sqlite"
[Cookies] Extracted 502 cookies from firefox
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [vk] Extracting URL: https://vk.com/video-173637871_456242073
[vk] -173637871_456242073: Downloading JSON metadata
ERROR: 'generator' object is not subscriptable
Traceback (most recent call last):
  File "/mnt/sda3/GIT/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 1440, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/sda3/GIT/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 1516, in __extract_info
    ie_result = ie.extract(url)
  File "/mnt/sda3/GIT/yt-dlp/./yt-dlp/yt_dlp/extractor/common.py", line 665, in extract
    ie_result = self._real_extract(url)
  File "/mnt/sda3/GIT/yt-dlp/./yt-dlp/yt_dlp/extractor/vk.py", line 452, in _real_extract
    return self.url_result(dailymotion_urls[0], DailymotionIE.ie_key())
TypeError: 'generator' object is not subscriptable

**Comment by krasnh** [comment]
Works:
```
$ git describe --long --tags
2022.07.18-26-gedebb6517
```
Does not work:
```
$ git describe --long --tags
2022.07.18-78-g061a17abd
```

**Comment by krasnh** [comment]
```
git clone https://github.com/yt-dlp/yt-dlp.git
cd yt-dlp
git checkout 59f63c8f0facb71208c8c131935fc4317e96f8b4
make yt-dlp

$ ./yt-dlp https://vk.com/video-173637871_456242073
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 508 cookies from firefox
[vk] -173637871_456242073: Downloading JSON metadata
[vk] -173637871_456242073: Downloading m3u8 information
[info] -173637871_456242073: Downloading 1 format(s): hls-3467
[download] Необычный освежитель воздуха [-173637871_456242073].mp4 has already been downloaded
[download] 100% of 5.26MiB

**Comment by pukkandan** [comment]
I wish you had mentioned in OP that you are on the master branch

**Comment by krasnh** [comment]
```
$ git checkout master

$ git pull
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 8 (delta 7), reused 8 (delta 7), pack-reused 0
Распаковка объектов: 100% (8/8), 1.46 КиБ | 373.00 КиБ/с, готово.
Из https://github.com/yt-dlp/yt-dlp
   061a17abd..43aebb7db  master     -> origin/master
Обновление 061a17abd..43aebb7db
Fast-forward
 yt_dlp/extractor/foxnews.py  |  9 ++++-----
 yt_dlp/extractor/francetv.py |  2 +-
 yt_dlp/extractor/heise.py    |  2 +-
 yt_dlp/extractor/vk.py       | 12 ++++++------
 4 files changed, 12 insertions(+), 13 deletions(-)

$ make yt-dlp

$ ./yt-dlp https://vk.com/video-173637871_456242073
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 509 cookies from firefox
[vk] -173637871_456242073: Downloading JSON metadata
[vk] -173637871_456242073: Downloading m3u8 information
[info] -173637871_456242073: Downloading 1 format(s): hls-3467
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2
[download] Destination: Необычный освежитель воздуха [-173637871_456242073].mp4
[download] 100% of 5.53MiB in 00:02 at 1.97MiB/s
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Необычный освежитель воздуха [-173637871_456242073].mp4"

$ lh *.mp4
-rw-r--r-- 1 live live 5,3M авг  7 01:12 'Необычный освежитель воздуха [-173637871_456242073].mp4'


```

**Comment by krasnh** [comment]
Checked in LiveCD Mint 20.2 to exclude my settings. Works without cookies. )

**Comment by finn1199** [comment]
> git clone https://github.com/yt-dlp/yt-dlp.git
> cd yt-dlp
> git checkout 59f63c8f0facb71208c8c131935fc4317e96f8b4
> make yt-dlp

Works great!!!

`$ ./yt-dlp https://vk.com/video-173637871_456242073
[vk] -173637871_456242073: Downloading JSON metadata
[vk] -173637871_456242073: Downloading m3u8 information
[info] -173637871_456242073: Downloading 1 format(s): hls-3467
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2
[download] Destination: Необычный освежитель воздуха [-173637871_456242073].mp4
[download] 100% of 5.53MiB in 00:00 at 10.99MiB/s
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Необычный освежитель воздуха [-173637871_456242073].mp4"
`

**Comment by krasnh** [comment]
> git checkout 59f63c8f0facb71208c8c131935fc4317e96f8b4

It was fixed yesterday. There is no need to revert to an old commit.

**Comment by finn1199** [comment]
> Master is now working

Ok.
Great job!
Tanks!
