### ISSUE TITLE
[Broken] "past live streams" playlist for specific Youtube channel fails to download as incomplete.

### ISSUE THREAD

**Issue by krichbanana** [yt-dlp/yt-dlp#459]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.06.23**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-s', '-q', '--verbose', '--max-downloads', '2', 'https://www.youtube.com/channel/UCIeSUTOTkF9Hs7q3SGcO-Ow/videos?view=2&sort=dd&live_view=503&shelf_id=0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.06.23 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 109dd3b23
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.13.0-rc5-1-mainline-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCIeSUTOTkF9Hs7q3SGcO-Ow/videos?view=2&sort=dd&live_view=503&shelf_id=0
[youtube:tab] UCIeSUTOTkF9Hs7q3SGcO-Ow: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCIeSUTOTkF9Hs7q3SGcO-Ow/videos?view=2&sort=dd&live_view=503&shelf_id=0
[download] Downloading playlist: Elira Pendora 【NIJISANJI EN】 - Videos
[youtube:tab] UCIeSUTOTkF9Hs7q3SGcO-Ow page 1: Downloading API JSON
[youtube:tab] UCIeSUTOTkF9Hs7q3SGcO-Ow page 2: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] UCIeSUTOTkF9Hs7q3SGcO-Ow page 2: Downloading API JSON (retry #1)
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] UCIeSUTOTkF9Hs7q3SGcO-Ow page 2: Downloading API JSON (retry #2)
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] UCIeSUTOTkF9Hs7q3SGcO-Ow page 2: Downloading API JSON (retry #3)
ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "$CWD/yt-dlp/yt_dlp/YoutubeDL.py", line 1144, in wrapper
    return func(self, *args, **kwargs)
  File "$CWD/yt-dlp/yt_dlp/YoutubeDL.py", line 1180, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "$CWD/yt-dlp/yt_dlp/YoutubeDL.py", line 1289, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "$CWD/yt-dlp/yt_dlp/YoutubeDL.py", line 1371, in __process_playlist
    entry = ie_entries[i - 1]
  File "$CWD/yt-dlp/yt_dlp/utils.py", line 4016, in __getitem__
    self.__cache.extend(itertools.islice(self.__iterable, n))
  File "$CWD/yt-dlp/yt_dlp/extractor/youtube.py", line 3947, in _smuggle_data
    for entry in entries:
  File "$CWD/yt-dlp/yt_dlp/extractor/youtube.py", line 3660, in _entries
    response = self._extract_response(
  File "$CWD/yt-dlp/yt_dlp/extractor/youtube.py", line 620, in _extract_response
    raise ExtractorError(last_error)
yt_dlp.utils.ExtractorError: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

I discovered that a particular playlist URL was causing an extractor error consistently, likely starting around Jun 30th 3AM EDT. The playlist is a synthetic one generated by Youtube with the tab title "Past live streams", and only affects this particular channel. I'm reporting this per the error's advise.

The URL in question is `https://www.youtube.com/channel/UCIeSUTOTkF9Hs7q3SGcO-Ow/videos?view=2&sort=dd&live_view=503&shelf_id=0
`

Visiting the URL you will see Youtube still spinning when you scroll to the bottom (which seems to be specific to this channel), but the list of videos appears complete.

**Comment by colethedj** [comment]
> Visiting the URL you will see Youtube still spinning when you scroll to the bottom

I'll have a check later, but likely this is an issue with YouTube. I have seen this happen to a few channels.

**Comment by pukkandan** [comment]
This seems to have gotten fixed now. Please confirm

**Comment by krichbanana** [comment]
That channel has fixed itself, but I found another active case: https://www.youtube.com/channel/UCP4nMSTdwU1KqYWu3UH5DHQ/videos?view=2&live_view=503 .

**Comment by pukkandan** [comment]
Its happening in browser as well. Defenitely a bug from youtube's side
