### ISSUE TITLE
Rutube.ru/video streams can be opened only after those are finished

### ISSUE THREAD

**Issue by VFomich** [yt-dlp/yt-dlp#4594]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Apparently the live stream video links that can be found in the section https://rutube.ru/feeds/stream/ can be opened only after those are no longer live. Opening that type of stream link while it is still ongoing results in a "No video formats found!" error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://rutube.ru/video/dca682c495a09cd0d127075a5589942b/']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg git-2022-07-31-e725c5e24 (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [rutube] Extracting URL: https://rutube.ru/video/dca682c495a09cd0d127075a5589942b/
[rutube] dca682c495a09cd0d127075a5589942b: Downloading video JSON
[rutube] dca682c495a09cd0d127075a5589942b: Downloading options JSON
ERROR: [rutube] dca682c495a09cd0d127075a5589942b: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1521, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1578, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2481, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1002, in raise_no_formats
yt_dlp.utils.ExtractorError: [rutube] dca682c495a09cd0d127075a5589942b: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pzhlkj6612** [comment]
The version 2024.08.06 seems to work fine with the given URL:

```
[rutube] Extracting URL: https://rutube.ru/video/dca682c495a09cd0d127075a5589942b/ 
[rutube] dca682c495a09cd0d127075a5589942b: Downloading video JSON 
[rutube] dca682c495a09cd0d127075a5589942b: Downloading options JSON 
[rutube] dca682c495a09cd0d127075a5589942b: Downloading m3u8 information 
[rutube] dca682c495a09cd0d127075a5589942b: Downloading m3u8 information 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id 
[info] Available thumbnails for dca682c495a09cd0d127075a5589942b: 
ID Width   Height  URL 
0  unknown unknown http://pic.rutubelist.ru/video/e7/a9/e7a9dc974f8e391efd25b9ee33136f84.jpg 
dca682c495a09cd0d127075a5589942b has no subtitles 
[info] Available formats for dca682c495a09cd0d127075a5589942b: 
ID             EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC      ACODEC 
────────────────────────────────────────────────────────────────────────────────── 
default-295-0  mp4 256x144     25 │ ~383.46MiB  295k m3u8  │ avc1.4d400c mp4a.40.2 
default-295-1  mp4 256x144     25 │ ~383.46MiB  295k m3u8  │ avc1.4d400c mp4a.40.2 
m3u8-295-0     mp4 256x144     25 │ ~383.46MiB  295k m3u8  │ avc1.4d400c mp4a.40.2
m3u8-295-1     mp4 256x144     25 │ ~383.46MiB  295k m3u8  │ avc1.4d400c mp4a.40.2
default-537-0  mp4 416x240     25 │ ~698.02MiB  537k m3u8  │ avc1.4d400d mp4a.40.2
default-537-1  mp4 416x240     25 │ ~698.02MiB  537k m3u8  │ avc1.4d400d mp4a.40.2
m3u8-537-0     mp4 416x240     25 │ ~698.02MiB  537k m3u8  │ avc1.4d400d mp4a.40.2
m3u8-537-1     mp4 416x240     25 │ ~698.02MiB  537k m3u8  │ avc1.4d400d mp4a.40.2
default-1126-0 mp4 640x360     25 │ ~  1.43GiB 1126k m3u8  │ avc1.4d401e mp4a.40.2
default-1126-1 mp4 640x360     25 │ ~  1.43GiB 1126k m3u8  │ avc1.4d401e mp4a.40.2
m3u8-1126-0    mp4 640x360     25 │ ~  1.43GiB 1126k m3u8  │ avc1.4d401e mp4a.40.2
m3u8-1126-1    mp4 640x360     25 │ ~  1.43GiB 1126k m3u8  │ avc1.4d401e mp4a.40.2
default-4085-0 mp4 1280x720    25 │ ~  5.19GiB 4085k m3u8  │ avc1.64001f mp4a.40.2
default-4085-1 mp4 1280x720    25 │ ~  5.19GiB 4085k m3u8  │ avc1.64001f mp4a.40.2
m3u8-4085-0    mp4 1280x720    25 │ ~  5.19GiB 4085k m3u8  │ avc1.64001f mp4a.40.2
m3u8-4085-1    mp4 1280x720    25 │ ~  5.19GiB 4085k m3u8  │ avc1.64001f mp4a.40.2
default-6846-0 mp4 1920x1080   25 │ ~  8.69GiB 6846k m3u8  │ avc1.640028 mp4a.40.2
default-6846-1 mp4 1920x1080   25 │ ~  8.69GiB 6846k m3u8  │ avc1.640028 mp4a.40.2
m3u8-6846-0    mp4 1920x1080   25 │ ~  8.69GiB 6846k m3u8  │ avc1.640028 mp4a.40.2
m3u8-6846-1    mp4 1920x1080   25 │ ~  8.69GiB 6846k m3u8  │ avc1.640028 mp4a.40.2
[debug] Default format spec: bestvideo*+bestaudio/best
[info] dca682c495a09cd0d127075a5589942b: Downloading 1 format(s): m3u8-6846-1
[info] Writing video metadata as JSON to: Просто катам качаем танки фарм серебра WOT учусь играть World of Tanks [dca682c495a09cd0d127075a5589942b] [m3u8-6846-1].info.json 

```

.
