### ISSUE TITLE
https://www.rtlnieuws.nl/nieuws/video

### ISSUE THREAD

**Issue by M1Aston** [yt-dlp/yt-dlp#4599]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Provide a description that is worded well enough to be understood

These videos (the pages) are reported as Unsupported URL

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.rtlnieuws.nl/nieuws/video/video/5325594/de-heetste-plek-ter-wereld-nu-staat-death-valley-onder-water']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.7.9 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://www.rtlnieuws.nl/nieuws/video/video/5325594/de-heetste-plek-ter-wereld-nu-staat-death-valley-onder-water
[generic] de-heetste-plek-ter-wereld-nu-staat-death-valley-onder-water: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] de-heetste-plek-ter-wereld-nu-staat-death-valley-onder-water: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.rtlnieuws.nl/nieuws/video/video/5325594/de-heetste-plek-ter-wereld-nu-staat-death-valley-onder-water
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.rtlnieuws.nl/nieuws/video/video/5325594/de-heetste-plek-ter-wereld-nu-staat-death-valley-onder-water
```

**Comment by pukkandan** [comment]
For devs:

There are 2 issues here. 

1. the embed is not getting detected. This can be fixed easily by changing the embed regex
2. The embedded video doesn't actually download. ie, the extractor is broken

```
❯ yt-dlp https://www.rtlxl.nl/programma/rtl-nieuws/bae19c6d-77da-4f08-8784-76c455cc458c -v
[debug] Command-line config: ['--ignore-config', 'https://www.rtlxl.nl/programma/rtl-nieuws/bae19c6d-77da-4f08-8784-76c455cc458c', '-v']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05ef6] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: a41662343
[debug] Python 3.10.5 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [rtl.nl] Extracting URL: https://www.rtlxl.nl/programma/rtl-nieuws/bae19c6d-77da-4f08-8784-76c455cc458c
[rtl.nl] bae19c6d-77da-4f08-8784-76c455cc458c: Downloading JSON metadata
[rtl.nl] bae19c6d-77da-4f08-8784-76c455cc458c: Downloading m3u8 information
WARNING: [rtl.nl] Failed to download m3u8 information: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
ERROR: [rtl.nl] bae19c6d-77da-4f08-8784-76c455cc458c: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1441, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1538, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1596, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 2511, in process_video_result
    self.raise_no_formats(info_dict)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1009, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [rtl.nl] bae19c6d-77da-4f08-8784-76c455cc458c: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
