### ISSUE TITLE
[Broken] Canalplus

### ISSUE THREAD

**Issue by girod2033** [yt-dlp/yt-dlp#461]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.06.23**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp.exe --cookies cookies.txt --allow-unplayable-formats -F --v
erbose "https://www.canalplus.com/charme/max-portrait-d-un-serial-niqueur/h/3246
941_40099"
[debug] Command-line config: ['--cookies', 'cookies.txt', '--allow-unplayable-fo
rmats', '-F', '--verbose', 'https://www.canalplus.com/charme/max-portrait-d-un-s
erial-niqueur/h/3246941_40099']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] yt-dlp version 2021.06.23 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.canalplus.com/charme/max-portrait-
d-un-serial-niqueur/h/3246941_40099
[generic] 3246941_40099: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 3246941_40099: Downloading webpage
[generic] 3246941_40099: Extracting information
ERROR: Unsupported URL: https://www.canalplus.com/charme/max-portrait-d-un-seria
l-niqueur/h/3246941_40099
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1138, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1163, in __extract_info
  File "yt_dlp\extractor\common.py", line 568, in extract
  File "yt_dlp\extractor\generic.py", line 3542, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.canalplus.com/charme
/max-portrait-d-un-serial-niqueur/h/3246941_40099

```

## Description

Hello.
Does not work. I will provide cookies upon request.

**Comment by pukkandan** [comment]
Could you check if `https://www.mycanal.fr/charme/max-portrait-d-un-serial-niqueur/h/3246941_40099` points to the same video? If so, does this URL download correctly?

**Comment by girod2033** [comment]
Yes, but link redirects.

yt-dlp.exe --cookies cookies.txt --allow-unplayable-formats -F --v
erbose "https://www.mycanal.fr/charme/max-portrait-d-un-serial-niqueur/h/3246941
_40099"
[debug] Command-line config: ['--cookies', 'cookies.txt', '--allow-unplayable-fo
rmats', '-F', '--verbose', 'https://www.mycanal.fr/charme/max-portrait-d-un-seri
al-niqueur/h/3246941_40099']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] yt-dlp version 2021.06.23 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.mycanal.fr/charme/max-portrait-d-u
n-serial-niqueur/h/3246941_40099
[generic] 3246941_40099: Requesting header
[redirect] Following redirect to https://www.canalplus.com/charme/max-portrait-d
-un-serial-niqueur/h/3246941_40099
[debug] [generic] Extracting URL: https://www.canalplus.com/charme/max-portrait-
d-un-serial-niqueur/h/3246941_40099
[generic] 3246941_40099: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 3246941_40099: Downloading webpage
[generic] 3246941_40099: Extracting information
ERROR: Unsupported URL: https://www.canalplus.com/charme/max-portrait-d-un-seria
l-niqueur/h/3246941_40099
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1138, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1163, in __extract_info
  File "yt_dlp\extractor\common.py", line 568, in extract
  File "yt_dlp\extractor\generic.py", line 3542, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.canalplus.com/charme
/max-portrait-d-un-serial-niqueur/h/3246941_40099

**Comment by drzraf** [comment]
Tested with the latest version on a public video, still fails:

```
$ yt-dlp -F -v  https://www.canalplus.com/decouverte/sur-les-pas-de-marie/h/20404135_50013
[debug] Command-line config: ['-F', '-v', 'https://www.canalplus.com/decouverte/sur-les-pas-de-marie/h/20404135_50013']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-56-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.06.15.1, mutagen-1.46.0, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [generic] Extracting URL: https://www.canalplus.com/decouverte/sur-les-pas-de-marie/h/20404135_50013
[generic] 20404135_50013: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 20404135_50013: Extracting information
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[debug] [generic] Extracting URL: https://static.canalplus.com/player-embed/index.html?contentId=20404135_50013&offerZone=cpfra&origin=twitter.com
[generic] index.html?contentId=20404135_50013&offerZone=cpfra&origin=twitter: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] index.html?contentId=20404135_50013&offerZone=cpfra&origin=twitter: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://static.canalplus.com/player-embed/index.html?contentId=20404135_50013&offerZone=cpfra&origin=twitter.com
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2721, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://static.canalplus.com/player-embed/index.html?contentId=20404135_50013&offerZone=cpfra&origin=twitter.com
```

**Comment by jarredou** [comment]
Any update on this issue ?!
