### ISSUE TITLE
[Zee5] HTTP Error 404 Issue.

### ISSUE THREAD

**Issue by angentanewbe** [yt-dlp/yt-dlp#4612]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello
I am trying to download from zee5 and I got HTTP Error 404 on this video link "https://www.zee5.com/kids/kids-shows/cinderella/0-6-2784/cindrella/0-1-manual_3osolr76hd4g"

Although some links are working and are downloadable for eg : "https://www.zee5.com/tv-shows/details/mithai/0-6-3121/mithai-july-17-2022/0-1-6z5177450"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -v https://www.zee5.com/kids/kids-shows/cinderella/0-6-2784/cindrella/0-1-manual_3osolr76hd4g
[debug] Command-line config: ['-v', 'https://www.zee5.com/kids/kids-shows/cinderella/0-6-2784/cindrella/0-1-manual_3osolr76hd4g']
[debug] User config "C:\Users\user\AppData\Roaming\yt-dlp\config.txt": ['--all-subs', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--write-annotations', '--download-archive=All Youtube History.txt', '--write-annotations', '--write-description', '--write-info-json', '--write-thumbnail', '-f', 'bv+ba/best', '--merge-output-format', 'mp4', '-ciw', '--retries', 'infinite', '-o', '%(title)s-%(id)s-%(format_id)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loading archive file 'All Youtube History.txt'
[debug] Using fake IP 117.227.126.177 (IN) as X-Forwarded-For
[debug] [Zee5] Extracting URL: https://www.zee5.com/kids/kids-shows/cinderella/0-6-2784/cindrella/0-1-manual_3osolr76hd4g
[Zee5] 0-1-manual_3osolr76hd4g: Downloading access token
[Zee5] 0-1-manual_3osolr76hd4g: Downloading JSON metadata
[Zee5] 0-1-manual_3osolr76hd4g: Downloading m3u8 information
WARNING: [Zee5] Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: [Zee5] 0-1-manual_3osolr76hd4g: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1441, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1538, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1596, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2514, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1009, in raise_no_formats
yt_dlp.utils.ExtractorError: [Zee5] 0-1-manual_3osolr76hd4g: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by m4tu4g** [comment]
Extractor working fine, non-drm'ed m3u8 is 404 from zee5's side for this particular one.

Any other links you can provide that happen to be same 404?

**Comment by angentanewbe** [comment]
This link is giving error 404

https://www.zee5.com/kids/kids-shows/the-jungle-book/0-6-2645/the-jungle-book/0-1-manual_34a4sn36c7m0

here is the verbose : 



yt-dlp -vU https://www.zee5.com/kids/kids-shows/the-jungle-book/0-6-2645/the-jungle-book/0-1-manual_34a4sn36c7m0
[debug] Command-line config: ['-vU', 'https://www.zee5.com/kids/kids-shows/the-jungle-book/0-6-2645/the-jungle-book/0-1-manual_34a4sn36c7m0']
[debug] User config "C:\Users\user\AppData\Roaming\yt-dlp\config.txt": ['--all-subs', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--write-annotations', '--download-archive=All Youtube History.txt', '--write-annotations', '--write-description', '--write-info-json', '--write-thumbnail', '-f', 'bv+ba/best', '--merge-output-format', 'mp4', '-ciw', '--retries', 'infinite', '-o', '%(title)s-%(id)s-%(format_id)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loading archive file 'All Youtube History.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] Using fake IP 117.238.237.80 (IN) as X-Forwarded-For
[debug] [Zee5] Extracting URL: https://www.zee5.com/kids/kids-shows/the-jungle-book/0-6-2645/the-jungle-book/0-1-manual_34a4sn36c7m0
[Zee5] 0-1-manual_34a4sn36c7m0: Downloading access token
[Zee5] 0-1-manual_34a4sn36c7m0: Downloading JSON metadata
[Zee5] 0-1-manual_34a4sn36c7m0: Downloading m3u8 information
WARNING: [Zee5] Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: [Zee5] 0-1-manual_34a4sn36c7m0: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1442, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1539, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1597, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2515, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1010, in raise_no_formats
yt_dlp.utils.ExtractorError: [Zee5] 0-1-manual_34a4sn36c7m0: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U









These links are not downloading the video or audio but not giving any error:

https://www.zee5.com/kids/kids-movies/cinderella-and-the-prince-charles/0-0-140019

https://www.zee5.com/kids/kids-movies/hua-mulan/0-0-103537

https://www.zee5.com/kids/kids-movies/christophers-dreams/0-0-140044

https://www.zee5.com/kids/kids-movies/hercules/0-0-160133



I believe the site maybe having some problems with these show.

here is the verbose : 

 
yt-dlp -vU https://www.zee5.com/kids/kids-movies/cinderella-and-the-prince-charles/0-0-140019
[debug] Command-line config: ['-vU', 'https://www.zee5.com/kids/kids-movies/cinderella-and-the-prince-charles/0-0-140019']
[debug] User config "C:\Users\user\AppData\Roaming\yt-dlp\config.txt": ['--all-subs', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--write-annotations', '--download-archive=All Youtube History.txt', '--write-annotations', '--write-description', '--write-info-json', '--write-thumbnail', '-f', 'bv+ba/best', '--merge-output-format', 'mp4', '-ciw', '--retries', 'infinite', '-o', '%(title)s-%(id)s-%(format_id)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loading archive file 'All Youtube History.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [zee5:series] Extracting URL: https://www.zee5.com/kids/kids-movies/cinderella-and-the-prince-charles/0-0-140019
[download] Downloading playlist: 0-0-140019
[zee5:series] 0-0-140019: Downloading access token
[zee5:series] 0-0-140019: Downloading JSON metadata
[info] Playlist metadata is already present
WARNING: There's no playlist description to write
[zee5:series] Playlist 0-0-140019: Downloading 0 videos of 0
[download] Finished downloading playlist: 0-0-140019






yt-dlp -vU https://www.zee5.com/kids/kids-movies/hua-mulan/0-0-103537
[debug] Command-line config: ['-vU', 'https://www.zee5.com/kids/kids-movies/hua-mulan/0-0-103537']
[debug] User config "C:\Users\user\AppData\Roaming\yt-dlp\config.txt": ['--all-subs', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--write-annotations', '--download-archive=All Youtube History.txt', '--write-annotations', '--write-description', '--write-info-json', '--write-thumbnail', '-f', 'bv+ba/best', '--merge-output-format', 'mp4', '-ciw', '--retries', 'infinite', '-o', '%(title)s-%(id)s-%(format_id)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loading archive file 'All Youtube History.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [zee5:series] Extracting URL: https://www.zee5.com/kids/kids-movies/hua-mulan/0-0-103537
[download] Downloading playlist: 0-0-103537
[zee5:series] 0-0-103537: Downloading access token
[zee5:series] 0-0-103537: Downloading JSON metadata
[info] Playlist metadata is already present
WARNING: There's no playlist description to write
[zee5:series] Playlist 0-0-103537: Downloading 0 videos of 0
[download] Finished downloading playlist: 0-0-103537









yt-dlp -vU https://www.zee5.com/kids/kids-movies/christophers-dreams/0-0-140044
[debug] Command-line config: ['-vU', 'https://www.zee5.com/kids/kids-movies/christophers-dreams/0-0-140044']
[debug] User config "C:\Users\user\AppData\Roaming\yt-dlp\config.txt": ['--all-subs', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--write-annotations', '--download-archive=All Youtube History.txt', '--write-annotations', '--write-description', '--write-info-json', '--write-thumbnail', '-f', 'bv+ba/best', '--merge-output-format', 'mp4', '-ciw', '--retries', 'infinite', '-o', '%(title)s-%(id)s-%(format_id)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loading archive file 'All Youtube History.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [zee5:series] Extracting URL: https://www.zee5.com/kids/kids-movies/christophers-dreams/0-0-140044
[download] Downloading playlist: 0-0-140044
[zee5:series] 0-0-140044: Downloading access token
[zee5:series] 0-0-140044: Downloading JSON metadata
[info] Playlist metadata is already present
WARNING: There's no playlist description to write
[zee5:series] Playlist 0-0-140044: Downloading 0 videos of 0
[download] Finished downloading playlist: 0-0-140044







yt-dlp -vU https://www.zee5.com/kids/kids-movies/hercules/0-0-160133
[debug] Command-line config: ['-vU', 'https://www.zee5.com/kids/kids-movies/hercules/0-0-160133']
[debug] User config "C:\Users\user\AppData\Roaming\yt-dlp\config.txt": ['--all-subs', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--write-annotations', '--download-archive=All Youtube History.txt', '--write-annotations', '--write-description', '--write-info-json', '--write-thumbnail', '-f', 'bv+ba/best', '--merge-output-format', 'mp4', '-ciw', '--retries', 'infinite', '-o', '%(title)s-%(id)s-%(format_id)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loading archive file 'All Youtube History.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [zee5:series] Extracting URL: https://www.zee5.com/kids/kids-movies/hercules/0-0-160133
[download] Downloading playlist: 0-0-160133
[zee5:series] 0-0-160133: Downloading access token
[zee5:series] 0-0-160133: Downloading JSON metadata
[info] Playlist metadata is already present
WARNING: There's no playlist description to write
[zee5:series] Playlist 0-0-160133: Downloading 0 videos of 0
[download] Finished downloading playlist: 0-0-160133

**Comment by pukkandan** [comment]
Some, but not all of the given examples are DRM protected

**Comment by pukkandan** [comment]
@m4tu4g

**Comment by daakuji** [comment]
yt-dlp.exe https://www.zee5.com/videos/details/practical-geometry/0-0-2z516052
[generic] 0-0-2z516052: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 0-0-2z516052: Extracting information



not working for me
