### ISSUE TITLE
OUT.TV Handshake Operation Timeout

### ISSUE THREAD

**Issue by j-ktz** [yt-dlp/yt-dlp#4626]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I'm trying  to download a video from https://outtv.ca. I'm a subscriber and  pay for my membership.  When I enter in the URL, I get `Unable to download webpage: <urlopen error _ssl.c:1106: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1106: The handshake operation timed out')))`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Johns-MacBook-Pro:~ johnkatez$ yt-dlp --cookies outtv.txt https://outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001&season=61eb00bba6f547001a11fb67
[1] 15347
Johns-MacBook-Pro:~ johnkatez$ [generic] 61eb00181de1c4001617af66?clip=_6290507057001: Downloading webpage
ERROR: [generic] Unable to download webpage: <urlopen error _ssl.c:1106: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1106: The handshake operation timed out')))
ason=61eb00bba6f547001a11fb67 -vU//outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001&se 
[2] 15371
-bash: -vU: command not found
[1]   Exit 1                  yt-dlp --cookies outtv.txt https://outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001
Johns-MacBook-Pro:~ johnkatez$ [generic] 61eb00181de1c4001617af66?clip=_6290507057001: Downloading webpage
1&season=61eb00bba6f547001a11fb67 ps://outtvgo.com/page/61eb00181de1c4001617af66?clip=_629050705700 
[3] 15377
Johns-MacBook-Pro:~ johnkatez$ [debug] Command-line config: ['--cookies', 'outtv.txt', '-vU', 'https://outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (pip)
[debug] Python 3.9.2 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs

Johns-MacBook-Pro:~ johnkatez$ [debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [generic] Extracting URL: https://outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001
[generic] 61eb00181de1c4001617af66?clip=_6290507057001: Downloading webpage
Johns-MacBook-Pro:~ johnkatez$ ERROR: [generic] Unable to download webpage: <urlopen error _ssl.c:1106: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1106: The handshake operation timed out')))
```

**Comment by bashonly** [comment]
you need to put the URL in quotes. any argument with `&` needs to be quoted. your terminal/bash is splitting the command at the `&`. get in the habit of always quoting the URL arg. if you still have an issue after quoting the URL, post a new verbose log.

**Comment by j-ktz** [comment]
@bashonly Thanks for responding! This is what I get when I quote then URL:

```
Johns-MacBook-Pro:~ johnkatez$ yt-dlp --cookies outtv.txt -vU “https://outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001&season=61eb00bba6f547001a11fb67”
[1] 27492
Johns-MacBook-Pro:~ johnkatez$ [debug] Command-line config: ['--cookies', 'outtv.txt', '-vU', '“https://outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (pip)
[debug] Python 3.9.2 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [generic] Extracting URL: “https://outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001
ERROR: [generic] '“https://outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:“https://outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001" ) to search YouTube
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 2615, in _real_extract
    raise ExtractorError(
```

**Comment by pukkandan** [comment]
Don't use fancy quotes!

Also, any reason why you think this is even a supported site?

**Comment by j-ktz** [comment]
I've tried both single and double quotes (non curly/fancy) and it still doesn't work. I searched the issues for "OutTV" and someone else said they were successful in downloading some videos. I posted on that thread too  but didn't hear back.

**Comment by pukkandan** [comment]
> - [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details

The website doesn't open in browser for me

**Comment by j-ktz** [comment]
@pukkandan Sorry about that. I was testing with ca.outtv and without the ca. to see if it would make a difference. Just ran a fresh test, but no dice. 

```
Johns-MacBook-Pro:~ johnkatez$ yt-dlp --cookies outtv.txt -vU "https://ca.outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001&season=61eb00bba6f547001a11fb67"
[debug] Command-line config: ['--cookies', 'outtv.txt', '-vU', 'https://ca.outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001&season=61eb00bba6f547001a11fb67']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (pip)
[debug] Python 3.9.2 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [generic] Extracting URL: https://ca.outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001&season=61eb00bba6f547001a11fb67
[generic] 61eb00181de1c4001617af66?clip=_6290507057001&season=61eb00bba6f547001a11fb67: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 61eb00181de1c4001617af66?clip=_6290507057001&season=61eb00bba6f547001a11fb67: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://ca.outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001&season=61eb00bba6f547001a11fb67
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1441, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1517, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3077, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://ca.outtvgo.com/page/61eb00181de1c4001617af66?clip=_6290507057001&season=61eb00bba6f547001a11fb67
```
