### ISSUE TITLE
`://live.house.gov`

### ISSUE THREAD

**Issue by c4lliope** [yt-dlp/yt-dlp#4642]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Global

### Example URLs

```bash
grace@chesapeake:~/place/house.camera$ ~/src/yt-dlp/yt-dlp https://live.house.gov
[generic] live.house: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] live.house: Extracting information
ERROR: Unsupported URL: https://live.house.gov
```

### Provide a description that is worded well enough to be understood

US House chamber shares a camera signal based in the chamber,
recording speeches and proceedings and running a sum of each roll call.

You can see such recording copied and shared publicly on [c-span.org](https://c-span.org).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://live.house.gov']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.15.0-43-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2020.06.20, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [generic] Extracting URL: https://live.house.gov
[generic] live.house: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] live.house: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://live.house.gov
Traceback (most recent call last):
  File "/home/grace/src/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1441, in wrapper
    return func(self, *args, **kwargs)
  File "/home/grace/src/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1517, in __extract_info
    ie_result = ie.extract(url)
  File "/home/grace/src/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/home/grace/src/yt-dlp/yt-dlp/yt_dlp/extractor/generic.py", line 3077, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://live.house.gov
```

**Comment by jhwgh1968** [comment]
This appears to be a video.js player embed. The site has simply disguised the player with their javascript so it is not recognized as such.

**Comment by coletdjnz** [comment]
> This appears to be a video.js player embed. The site has simply disguised the player with their javascript so it is not recognized as such.

It may use a video.js embed but it's the logic that the website uses to build it is what we care about. In this case it does not appear to be generic.

For devs: Seems to call some azure api to get streaming data. Some details such as the API domain appear to be contained in app.js, if hard-coding is not feasible:
> `<script type="text/javascript" src="https://live.house.gov/js/app.a113b136ebdce01cf16d-1.js"></script>`

**Comment by c4lliope** [comment]
I learned you can go back to chosen days on https://c-span.org, by clicking the calendar here:

https://www.c-span.org/congress/?chamber=house
<img width="549" alt="Screenshot 2023-01-04 at 1 03 59 PM" src="https://user-images.githubusercontent.com/30454698/210620385-8d831c6c-f34b-4689-9cfa-52be32bf894a.png">

I'd like to be able to transcribe the audio and encode timestamp links to the congressional record for each day.
C-Span is good for prior days, though the watermark is undesirable and perhaps un-publishable.
Someday I plan to record `live.house.gov` directly and publish a running accessible log of the speeches,
perhaps including mobile pings once chosen keyphrases are used.

**Comment by c4lliope** [comment]
The page is using Azure Media Player.
https://learn.microsoft.com/en-us/azure/media-services/azure-media-player/azure-media-player-overview
