### ISSUE TITLE
https://nos.nl/

### ISSUE THREAD

**Issue by M1Aston** [yt-dlp/yt-dlp#4649]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Provide a description that is worded well enough to be understood

https://nos.nl/
Videos from this website (the Dutch BBC) don't work: Unsupported URL..

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [generic] Extracting URL: https://nos.nl/nieuwsuur/artikel/2440353-verzakking-door-droogte-dreigt-tot-een-miljoen-kwetsbare-huizen
[generic] 2440353-verzakking-door-droogte-dreigt-tot-een-miljoen-kwetsbare-huizen: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 2440353-verzakking-door-droogte-dreigt-tot-een-miljoen-kwetsbare-huizen: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://nos.nl/nieuwsuur/artikel/2440353-verzakking-door-droogte-dreigt-tot-een-miljoen-kwetsbare-huizen
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1441, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1517, in __extract_info
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 3077, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://nos.nl/nieuwsuur/artikel/2440353-verzakking-door-droogte-dreigt-tot-een-miljoen-kwetsbare-huizen
```

**Comment by nicolaasjan** [comment]
In theory it should be possible to write an extractor for this.
I was able to find the exact link to the video with "[The Stream Detector](https://github.com/rowrawer/stream-detector)" and yt-dlp was able to download the video when given that link.

**Comment by HobbyistDev** [comment]
From your url. i got the video url from nextjs data. We can extract many information from there. We can extract the video from `nextjs_json['props']['pageProps']['data']` with `type` equal to `"video"` then get video url from `source['url']`.
Here's the sample of `nextjs_json['props']['pageProps']['data']` with type equal to `video`:
<details><summary> Json sample </summary>

```json
{
                "id": "2440340",
                "hasCoreId": true,
                "type": "video",
                "title": "'We hebben een huis vol met scheuren'",
                "geoprotection": false,
                "description": "Door de aanhoudende droogte verzakken honderdduizenden huizen in Nederland. Zo ook die van Jan Bergmans en Francien van Hulten in Zevenaar. ",
                "imagesByRatio": {
                  "16:9": [{
                    "width": 128,
                    "height": 72,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/128x72a.jpg"
                    }
                  }, {
                    "width": 256,
                    "height": 144,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/256x144a.jpg"
                    }
                  }, {
                    "width": 384,
                    "height": 216,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/384x216a.jpg"
                    }
                  }, {
                    "width": 512,
                    "height": 288,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/512x288a.jpg"
                    }
                  }, {
                    "width": 640,
                    "height": 360,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/640x360a.jpg"
                    }
                  }, {
                    "width": 768,
                    "height": 432,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/768x432a.jpg"
                    }
                  }, {
                    "width": 1024,
                    "height": 576,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/1024x576a.jpg"
                    }
                  }, {
                    "width": 1280,
                    "height": 720,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/1280x720a.jpg"
                    }
                  }, {
                    "width": 1536,
                    "height": 864,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/1536x864a.jpg"
                    }
                  }, {
                    "width": 1920,
                    "height": 1080,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/1920x1080a.jpg"
                    }
                  }, {
                    "width": 2560,
                    "height": 1440,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/2560x1440a.jpg"
                    }
                  }, {
                    "width": 3200,
                    "height": 1800,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/3200x1800a.jpg"
                    }
                  }, {
                    "width": 3840,
                    "height": 2160,
                    "url": {
                      "jpg": "https://cdn.nos.nl/image/2022/08/12/887149/3840x2160a.jpg"
                    }
                  }]
                },
                "source": {
                  "aspectRatio": "16:9",
                  "url": "https://resolver.streaming.api.nos.nl/stream?stream=NOSC_28d7e138_b91d_4149_ba23_caa84a992ce3\u0026profile=hls_unencrypted\u0026policy=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb3JlLm5vcy5ubCIsInN1YiI6Ik5PU0NfMjhkN2UxMzhfYjkxZF80MTQ5X2JhMjNfY2FhODRhOTkyY2UzIiwiYXVkIjpbInJlc29sdmVyLnN0cmVhbWluZy5hcGkubm9zLm5sIl0sImlhdCI6MTY2MDM5Nzg3NywiYWxsb3dlZEFyZWFzIjpbXSwiaXNHZW9wcm90ZWN0ZWQiOmZhbHNlfQ.uvcvIsNVY2F7Uv6PGNrFy083TnLOwqVdodApgJwuuF0",
                  "mimetype": "application/vnd.apple.mpegurl"
                },
                "adConfig": "https://oxmvifnvqu.nl/pwidjie/[identifier]?ncc=[noCommercialCookies]\u0026cust_params=omroep%3Dnos%26genre%3Dnieuwsuur%26video_duur%3D95%26afleverings_titel%3Dwehebbeneenhuisvolmetscheuren%26programma_titel%3Dnieuwsuur",
                "duration": "1:35"
              }
```
</details>
