### ISSUE TITLE
Raise a PostProcessingError no more cancel downloading

### ISSUE THREAD

**Issue by nastia-diaphan** [yt-dlp/yt-dlp#4651]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When the video is already downloaded (with the same format), I use `raise PostProcessingError` to abort process.
If not the process continue 
- with deleting subtitle file then download it again 
- copy the existing video file to add one more time the metadata to it.
I use `raise PostProcessingError` since 9 Nov 2021 with satisfaction. cf. #1604

I just made a upgrade and now  `raise PostProcessingError` do not cancel downloading anymore.
This is probably an old modification of the code dating from 24 Feb. and related to #2875 

In my download options I have:
   `'ignoreerrors': False,`
I tried but in vain:
   `'abort-on-error': True,`
   `'only_download': False,`

Any help is welcome.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~$ /home/lg/python3/yt-dlp/dn4.py PkbJOhnbbRA
python.3.8.10
yt_dlp 2022.08.08
dn4
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (pip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-122-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.0
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=PkbJOhnbbRA
[youtube] PkbJOhnbbRA: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] PkbJOhnbbRA: Downloading android player API JSON
[youtube] PkbJOhnbbRA: Downloading MPD manifest
[youtube] PkbJOhnbbRA: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, channels, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), channels, source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: id-orig
[pre_process] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.txt exist 
[pre_process] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.txt updated 
[pre_process] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.maxresdefault.jpg exist
[pre_process] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA*.f137.*
ERROR: Preprocessing: [pre_process] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.mp4 already exist 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3404, in pre_process
    info = self.run_all_pps(key, info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3397, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3376, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/lg/python3/yt-dlp/dn4.py", line 485, in run
    raise PostProcessingError(f'[pre_process] {f}\u001b[40;32;1m already exist \x1b[0m')
yt_dlp.utils.PostProcessingError: [pre_process] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.mp4 already exist 

[info] PkbJOhnbbRA: Downloading 1 format(s): 137+139
Deleting existing file /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.id-orig.ttml
[info] Writing video subtitles to: /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.id-orig.ttml
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=PkbJOhnbbRA&caps=asr&xoaf=5&xosf=1&hl=en&ip=0.0.0.0&ipbits=0&expire=1660450217&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=EECBA023EA9841A28939C714623DC495551E0A24.304419E6AF46984A195E486E7A8CE194F820D1E7&key=yt8&kind=asr&lang=id&fmt=ttml"
[download] Destination: /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.id-orig.ttml
[download] 100% of 1008.00B in 00:00 at 12.30KiB/s
[before_dl] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.txt updated
[download] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.mp4 has already been downloaded
[Metadata] Adding metadata to "/home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:/home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.mp4 -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=Zoom na Galáxia Cartwheel pelo telescópio James Webb' -metadata date=20220813 -metadata 'description=Zoom na Galáxia Cartwheel pelo telescópio James Webb

Link do vídeo
https://youtu.be/PkbJOhnbbRA' -metadata 'synopsis=Zoom na Galáxia Cartwheel pelo telescópio James Webb

Link do vídeo
https://youtu.be/PkbJOhnbbRA' -metadata 'purl=https://www.youtube.com/watch?v=PkbJOhnbbRA' -metadata 'comment=https://www.youtube.com/watch?v=PkbJOhnbbRA' -metadata 'artist=Canal World Space' -movflags +faststart file:/home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.temp.mp4
[post_process] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.mp4 downloaded
ERROR: Preprocessing: [pre_process] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.mp4 already exist 
ERROR: /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.txt updated
ERROR: Preprocessing: [pre_process] /home/lg/youtube/UCitR8NKddLJqH1heJER9RFw.=cartwheel=============DEL/20220813.PkbJOhnbbRA.f137.mp4 already exist 
finished with PkbJOhnbbRA
```

**Comment by pukkandan** [comment]
As I said in that issue, the **proper** way to do this is to pass a `match_filter`. But if you want a quick fix, just change the error to any other type

**Comment by nastia-diaphan** [comment]
Thank you @pukkandan. I have chosen `DownloadCancelled` type.
