### ISSUE TITLE
site xnxx works but xnxx gold returns unsupported url

### ISSUE THREAD

**Issue by guesswho123123** [yt-dlp/yt-dlp#4652]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

usa

### Provide a description that is worded well enough to be understood

video downloads from xnxxx.com [no payment required] work just fine

video downloads from premium site xnxx.gold returns 'unsupported url" error on all videos

and yes, i have a paid subscription to xnxx.gold

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.xnxx.gold/video-v90a51d/watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-08-10-git-8fc7f0fdec-essentials_build-www.gyan.dev (setts), ffprobe 2022-08-10-git-8fc7f0fdec-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [generic] Extracting URL: https://www.xnxx.gold/video-v90a51d/watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass
[generic] watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.xnxx.gold/video-v90a51d/watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1441, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1517, in __extract_info
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 3077, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.xnxx.gold/video-v90a51d/watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass
```

**Comment by october262** [comment]
> 



> ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
> * [x]  I understand that I will be **blocked** if I remove or skip any mandatory* field
> 
> ### Checklist
> * [x]  I'm reporting a broken site
> * [x]  I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> * [x]  I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> * [x]  I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required
> 
> ### Region
> usa
> 
> ### Provide a description that is worded well enough to be understood
> video downloads from xnxxx.com [no payment required] work just fine
> 
> video downloads from premium site xnxx.gold returns 'unsupported url" error on all videos
> 
> and yes, i have a paid subscription to xnxx.gold
> 
> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> ```shell
> [debug] Command-line config: ['-vU', 'https://www.xnxx.gold/video-v90a51d/watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass', '--username', 'PRIVATE', '--password', 'PRIVATE']
> [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.08.08 [3157158] (win32_exe)
> [debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg 2022-08-10-git-8fc7f0fdec-essentials_build-www.gyan.dev (setts), ffprobe 2022-08-10-git-8fc7f0fdec-essentials_build-www.gyan.dev
> [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
> [debug] Proxy map: {}
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Latest version: 2022.08.08, Current version: 2022.08.08
> yt-dlp is up to date (2022.08.08)
> [debug] [generic] Extracting URL: https://www.xnxx.gold/video-v90a51d/watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass
> [generic] watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> [generic] watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass: Extracting information
> [debug] Looking for Brightcove embeds
> [debug] Looking for embeds
> ERROR: Unsupported URL: https://www.xnxx.gold/video-v90a51d/watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass
> Traceback (most recent call last):
>   File "yt_dlp\YoutubeDL.py", line 1441, in wrapper
>   File "yt_dlp\YoutubeDL.py", line 1517, in __extract_info
>   File "yt_dlp\extractor\common.py", line 666, in extract
>   File "yt_dlp\extractor\generic.py", line 3077, in _real_extract
> yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.xnxx.gold/video-v90a51d/watch_sexy_babe_nancy_a_s_solo_striptease_and_enjoy_her_shaved_teen_pussy_and_ass
> ```

instead of using the username & password option, try again using the cookies.txt file option.

**Comment by guesswho123123** [comment]
THAT WORKED!  Thank you

**Comment by guesswho123123** [comment]
i was incorrect... i tested with link to regular/non-pay xnx.com

gold link sill got error 'unsupported url'

**Comment by fillwithjoy1** [comment]
💀💀💀💀
