### ISSUE TITLE
Site request for tokinosora-fc.com

### ISSUE THREAD

**Issue by yyppiyt** [yt-dlp/yt-dlp#4655]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Global

### Example URLs

- Single video: https://tokinosora-fc.com/video/smcZ6Ezx4mQcgHAMRkHX4rMj
- Single video: https://tokinosora-fc.com/video/smYYioKjMmT8Fp6iUo7CmvfJ

### Provide a description that is worded well enough to be understood

yt-dlp unable to find any videos on this site and return HTTP error 404, same result for youtube-dl.

I found the m3u8 file by using "video downloadhelper":
https://hls-auth.cloud.stream.co.jp/mediaplaylist/smcZ6Ezx4mQcgHAMRkHX4rMj/transcoded/2ygcv8ot08plcvwp_rm8z3rkz9noqpd7o_xcUumN2H5tSFfpEbY8HqvV_1_20220729-19-50-10_0_1080p.m3u8?session_id=126b67ca-95a9-4fe6-9331-aa7b74dc3ab7&media_view_id=AfeEhz2HuD04j7rAepv2Q4OgmhuOEozk

https://hls-auth.cloud.stream.co.jp/mediaplaylist/smYYioKjMmT8Fp6iUo7CmvfJ/transcoded/ygs9xpn71u90wjjj_p3oqzn12ej3yv58d_geUwdoo5hyWeh8LJrhCBRD_1_20220518-19-50-05_0_1080p.m3u8?session_id=d3a94aed-f004-49f4-bfae-9169afb75883&media_view_id=XEqY9kSMlVKZ45ju2u8GyUQk37IVax9M

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
For video "https://tokinosora-fc.com/video/smcZ6Ezx4mQcgHAMRkHX4rMj":
[debug] Command-line config: ['-vU', 'https://tokinosora-fc.com/video/smcZ6Ezx4mQcgHAMRkHX4rMj']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-06-git-03d81a044a-full_build-www.gyan.dev (setts), ffprobe 2022-07-06-git-03d81a044a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [generic] Extracting URL: https://tokinosora-fc.com/video/smcZ6Ezx4mQcgHAMRkHX4rMj
[generic] smcZ6Ezx4mQcgHAMRkHX4rMj: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 2641, in _real_extract
  File "yt_dlp\extractor\common.py", line 817, in _request_webpage

  File "yt_dlp\extractor\common.py", line 799, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3647, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

For video "https://tokinosora-fc.com/video/smYYioKjMmT8Fp6iUo7CmvfJ":
[debug] Command-line config: ['-vU', 'https://tokinosora-fc.com/video/smYYioKjMmT8Fp6iUo7CmvfJ']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-06-git-03d81a044a-full_build-www.gyan.dev (setts), ffprobe 2022-07-06-git-03d81a044a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [generic] Extracting URL: https://tokinosora-fc.com/video/smYYioKjMmT8Fp6iUo7CmvfJ
[generic] smYYioKjMmT8Fp6iUo7CmvfJ: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 2641, in _real_extract
  File "yt_dlp\extractor\common.py", line 817, in _request_webpage

  File "yt_dlp\extractor\common.py", line 799, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3647, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

Using youtube-dl for video "https://tokinosora-fc.com/video/smcZ6Ezx4mQcgHAMRkHX4rMj":
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vU', 'https://tokinosora-fc.com/video/smcZ6Ezx4mQcgHAMRkHX4rMj']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: ffmpeg 2022-07-06-git-03d81a044a-full_build-www.gyan.dev, ffprobe 2022-07-06-git-03d81a044a-full_build-www.gyan.dev
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.12.17)
[generic] smcZ6Ezx4mQcgHAMRkHX4rMj: Requesting header
WARNING: Could not send HEAD request to https://tokinosora-fc.com/video/smcZ6Ezx4mQcgHAMRkHX4rMj: HTTP Error 404: Not Found
[generic] smcZ6Ezx4mQcgHAMRkHX4rMj: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

**Comment by krichbanana** [comment]
The page metadata can be fetched from https://nfc-api.tokinosora-fc.com/fc/video_pages/<video_id>, which is a json file that holds description, duration, free part duration, etc. (video_id here is actually "content_code" in the result.)

The session key is obtained with a POST request to https://nfc-api.tokinosora-fc.com/fc/video_pages/<video_id>/session_ids, which returns a guest? session id.

The master playlist (m3u8) can be downloaded from https://hls-auth.cloud.stream.co.jp/auth/index.m3u8?session_id=<session_id>. This can be parsed by ffmpeg. Each quality format refers to an "AES-128"-encrypted stream which fetches a key stored as a URL in the manifest (automatically handled by ffmpeg). In order for the playlist and AES key to be downloaded, the user-agent must match that used to obtain the session key. The session key only seems to be able to be associated with one media_view_id (used to fetch the AES key), which changes if you were to refetch the master playlist.

This concerningly works with fully members-only content like https://tokinosora-fc.com/video/smCF8Dny5ujcYeVpWA6ANGpC or https://hololive-fc.com/video/smfkZqDv29saMTZKcq6HYoDZ; the guest session key is sufficient to get the playlist and encryption key for the entire VOD... (don't rely on client-side authentication, everyone.) It should be possible to have yt-dlp (and ffmpeg) enforce the "free portion", however.

**Comment by y3kcjd5** [comment]
I'd like to piggyback a request for hololive-fc.com support onto this ticket, given that the two websites are functionally identical; they even use the same login credentials.

Additional info:
There seems to be something fundamental going wrong with yt-dlp's initial loading of the webpages, and I suspect something server-side may be detecting and rejecting yt-dlp as an automated tool (anti-DDoS measure?), because only the top-level domain will actually return anything:
Attempt with video page URL (browser redirects to login page if not logged in):
```
>yt-dlp -vU --cookies-from-browser firefox "https://hololive-fc.com/video/smjcawP5YjVPbNTXkQuc3Hj8"
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://hololive-fc.com/video/smjcawP5YjVPbNTXkQuc3Hj8']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-21-git-f7d510b33f-full_build-www.gyan.dev (setts), ffprobe 2022-07-21-git-f7d510b33f-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\[redacted]\AppData\Roaming\Mozilla\Firefox\Profiles\[redacted].default-release\cookies.sqlite"
[Cookies] Extracted 270 cookies from firefox
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [generic] Extracting URL: https://hololive-fc.com/video/smjcawP5YjVPbNTXkQuc3Hj8
[generic] smjcawP5YjVPbNTXkQuc3Hj8: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 2641, in _real_extract
  File "yt_dlp\extractor\common.py", line 817, in _request_webpage

  File "yt_dlp\extractor\common.py", line 799, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3648, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```
Attempt with video list page (viewable in browser without login):
```
>yt-dlp -vU --cookies-from-browser firefox "https://hololive-fc.com/videos"
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://hololive-fc.com/videos']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-21-git-f7d510b33f-full_build-www.gyan.dev (setts), ffprobe 2022-07-21-git-f7d510b33f-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\[redacted]\AppData\Roaming\Mozilla\Firefox\Profiles\[redacted].default-release\cookies.sqlite"
[Cookies] Extracted 270 cookies from firefox
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [generic] Extracting URL: https://hololive-fc.com/videos
[generic] videos: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 2641, in _real_extract
  File "yt_dlp\extractor\common.py", line 817, in _request_webpage

  File "yt_dlp\extractor\common.py", line 799, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3648, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```
Attempt with site top domain (viewable in browser without login):
```
>yt-dlp -vU --cookies-from-browser firefox "https://hololive-fc.com"
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://hololive-fc.com']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-21-git-f7d510b33f-full_build-www.gyan.dev (setts), ffprobe 2022-07-21-git-f7d510b33f-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\[redacted]\AppData\Roaming\Mozilla\Firefox\Profiles\[redacted].default-release\cookies.sqlite"
[Cookies] Extracted 270 cookies from firefox
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [generic] Extracting URL: https://hololive-fc.com
[generic] hololive-fc: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] hololive-fc: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://hololive-fc.com
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1442, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1518, in __extract_info
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 3077, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://hololive-fc.com
```

**Comment by HobbyistDev** [comment]
> There seems to be something fundamental going wrong with yt-dlp's initial loading of the webpages, and I suspect something server-side may be detecting and rejecting yt-dlp as an automated tool (anti-DDoS measure?), because only the top-level domain will actually return anything

I don't think so, curl also give 404 error. When you check the network tab in browser, it also give 404 error at first. I don't know why it can be processed in browser.
![image](https://user-images.githubusercontent.com/105957301/188031749-4b5e7084-82c8-4b27-b67f-265c659c686f.png)

**Comment by krichbanana** [comment]
The page returns a small javascript page, which loads the rest of the content. All the relevant data is returned via JSON. Doesn't matter that the server returned a 404, the javascript runs all the same.

**Comment by DDDespair** [comment]
so is there no workaround? hololive-fc will end new membership registration on 2026年3月31日(火)16:00 although it appears the content will remain until 2027年3月31日(水)16:00
