### ISSUE TITLE
Fix RTP Play support as of Aug 2021

### ISSUE THREAD

**Issue by Generator** [yt-dlp/yt-dlp#4661]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Portugal

### Provide a description that is worded well enough to be understood

This issue is related to #3537

Currently RTP Play is broken, but there's a pull request on youtube-dl fixing the issue https://github.com/ytdl-org/youtube-dl/pull/29824

Tested the patch, and seems to be working
```
./youtube-dl -vF https://www.rtp.pt/play/p10551/e633968/por-do-sol 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vF', 'https://www.rtp.pt/play/p10551/e633968/por-do-sol']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.10.5 (CPython) - Linux-5.15.60-1-MANJARO-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.0.1, ffprobe 5.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[RTP] por-do-sol: Downloading webpage
[RTP] por-do-sol: Downloading MPD manifest
[info] Available formats for por-do-sol:
format code  extension  resolution note
a1-x3        m4a        audio only DASH audio  109k , m4a_dash container, mp4a.40.2 (48000Hz)
v1-x3        mp4        1920x1080  DASH video 2000k , mp4_dash container, avc1.64001f, 25fps, video only (best)
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.rtp.pt/play/p10551/e633968/por-do-sol  
[debug] Command-line config: ['-vU', 'https://www.rtp.pt/play/p10551/e633968/por-do-sol']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.15.60-1-MANJARO-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.07.18
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.08.08/_update_spec
ERROR: It looks like you installed yt-dlp with a package manager, pip or setup.py; Use that to update
[debug] [RTP] Extracting URL: https://www.rtp.pt/play/p10551/e633968/por-do-sol
[RTP] e633968: Downloading webpage
[RTP] e633968: Downloading MPD manifest
WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them
ERROR: [RTP] e633968: This video is DRM protected
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2481, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1002, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [RTP] e633968: This video is DRM protected
```

**Comment by somini** [comment]
`yt-dlp` complains about DRM, but if you download the files, they don't have it. Is there a way to force download the files?

**Comment by seproDev** [comment]
For `https://www.rtp.pt/play/p10551/e633968/por-do-sol ` yt-dlp correctly detects that the video is DRM protected. Only the first segment isn't encrypted to allow for quicker playback. Can you provide the URL where the yt-dlp DRM detection is wrong?

Either way, the way to fix it is by modifying the URL from:
```
https://streaming-vod.rtp.pt/drm-dash/nas2.share,/h264/512x384/p10551/p10551_1_202208059285.mp4,.urlset/manifest.mpd
```
to
```
https://streaming-vod.rtp.pt/dash/nas2.share,/h264/512x384/p10551/p10551_1_202208059285.mp4,.urlset/manifest.mpd
```

**Comment by somini** [comment]
Sorry, you are correct, I was running https://github.com/ytdl-org/youtube-dl/pull/29824 with an alias by accident.

I ported that MR to `yt-dlp`, see #10393
