### ISSUE TITLE
[Site Request] feetporno

### ISSUE THREAD

**Issue by DHYTFG** [yt-dlp/yt-dlp#4665]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

Single video: https://www.feetporno.com/videos/14632/silvia-saige-feet-the-ex-babysitter/

### Provide a description that is worded well enough to be understood

I can't give recommendations on this issue

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.feetporno.com/videos/14632/silvia-saige-feet-the-ex-babysitter/']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [5593720] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107703-g68e017c487-20220808 (setts), ffprobe N-107703-g68e017c487-20220808
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [generic] Extracting URL: https://www.feetporno.com/videos/14632/silvia-saige-feet-the-ex-babysitter/
[generic] silvia-saige-feet-the-ex-babysitter: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] silvia-saige-feet-the-ex-babysitter: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.feetporno.com/videos/14632/silvia-saige-feet-the-ex-babysitter/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1441, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1517, in __extract_info
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 3077, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.feetporno.com/videos/14632/silvia-saige-feet-the-ex-babysitter/
```

**Comment by jhwgh1968** [comment]
It appears to be a site with KVS player, but the current master version does not detect it.

This is because the KVS player regex on line 2956 of the generic extractor looks for a full URL, but this site uses a relative URI for the script: `<script type="text/javascript" src="/player/kt_player.js?v=5.5.1">`. This does not match. Once this is fixed by hand, downloading works.

P.S. while @DHYTFG did technically follow the rules and provide a link that is not pirated, the video fetched in the terminal output begins with an FBI anti-piracy warning. I will let the core team decide if this is worthy of removal, editing, or something else.
