### ISSUE TITLE
Yet another `--write-comments` fail for YouTube, suspecting bugs in `utils/traverse_obj`

### ISSUE THREAD

**Issue by ReeseWang** [yt-dlp/yt-dlp#4669]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Hong Kong

### Provide a description that is worded well enough to be understood

Comment downloading fails with `Incomplete data received` for YouTube video ID `NOsFLzpfRpU`.
Further digging revealed that the cause is `utils/traverse_obj` (which is called from `extractor/youtube.py:812`) returned `None` for this response:
```
{'responseContext': {'serviceTrackingParams': [{'service': 'CSI', 'params': [{'key': 'c', 'value': 'WEB'}, {'key': 'cver', 'value': '2.20220809.02.00'}, {'key': 'yt_li', 'value': '0'}, {'key': 'GetWatchPageWebCommentReplies_rid', 'value': '0x2484fdfdc51c1551'}]}, {'service': 'GFEEDBACK', 'params': [{'key': 'logged_in', 'value': '0'}, {'key': 'e', 'value': '24245609,24002025,24235348,24245799,24230625,23795882,24077266,23744176,24253521,24227844,24114244,24245746,24198739,24166867,24092063,24077241,24222379,24169501,24080738,24001373,24225483,24260441,24261927,23918597,23986023,24220089,23946420,23966208,23882502,24199774,24246430,24181174,24034168,24219713,23804281,24002022,24224025,24174780,24140247,24161116,24111977,24227406,24235237,24263053,24260844,23983296,24120820,24187043,24226335,24199724,24199710,24248385,24037231,24215196,24238983,24004644,24264860,24164186,24110315,24191629,24229161,39321934,24650771,24185614,1714241,23998056,24239633,24036947,24187377,23934970,24231054,24261244,24007246,24085811,24135310,24238478,24230001,24211178,24152443'}]}, {'service': 'GUIDED_HELP', 'params': [{'key': 'logged_in', 'value': '0'}]}, {'service': 'ECATCHER', 'params': [{'key': 'client.version', 'value': '2.20220809'}, {'key': 'client.name', 'value': 'WEB'}, {'key': 'client.fexp', 'value': '24245609,24002025,24235348,24245799,24230625,23795882,24077266,23744176,24253521,24227844,24114244,24245746,24198739,24166867,24092063,24077241,24222379,24169501,24080738,24001373,24225483,24260441,24261927,23918597,23986023,24220089,23946420,23966208,23882502,24199774,24246430,24181174,24034168,24219713,23804281,24002022,24224025,24174780,24140247,24161116,24111977,24227406,24235237,24263053,24260844,23983296,24120820,24187043,24226335,24199724,24199710,24248385,24037231,24215196,24238983,24004644,24264860,24164186,24110315,24191629,24229161,39321934,24650771,24185614,1714241,23998056,24239633,24036947,24187377,23934970,24231054,24261244,24007246,24085811,24135310,24238478,24230001,24211178,24152443'}]}], 'mainAppWebResponseContext': {'loggedOut': True}, 'webResponseContextExtensionData': {'hasDecorated': True}}, 'trackingParams': 'CAAQg2ciEwiOwLHsqsj5AhVUFn0KHT0GC_-CARUiEwjPxt3lqsj5AhWNvsQKHTOPC0I='}
```

Is this the expected behavior? The response is valid json after replacing `'` with `"` and `True` with `true`.

Command line to reproduce the error:
```
./yt-dlp.sh -vU --write-comments NOsFLzpfRpU
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-comments', 'NOsFLzpfRpU']
[debug] User config "/home/[redacted]/yt-dlp.conf": ['--no-mtime', '--embed-subs', '--merge-output-format', 'mp4', '--audio-format', 'aac', '--write-sub', '--write-auto-sub', '--sub-lang', 'en', '--no-embed-thumbnail', '--write-thumbnail']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [55937202b] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 4dc2b3304
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.19.1-arch2-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [youtube] Extracting URL: NOsFLzpfRpU
[youtube] NOsFLzpfRpU: Downloading webpage
[youtube] NOsFLzpfRpU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en
[youtube] Downloading comment section API JSON
[youtube] Downloading ~102 comments
[youtube] Sorting comments by newest first
[youtube] Downloading comment API JSON page 1 (0/102)
[youtube]     Downloading comment API JSON reply thread 1 (12/102)
[youtube] Downloading comment API JSON page 2 (21/102)
[youtube]     Downloading comment API JSON reply thread 1 (27/102)
[youtube]     Downloading comment API JSON reply thread 2 (32/102)
[youtube]     Downloading comment API JSON reply thread 3 (38/102)
[youtube]     Downloading comment API JSON reply thread 4 (44/102)
[youtube]     Downloading comment API JSON reply thread 5 (47/102)
[youtube] Downloading comment API JSON page 3 (53/102)
[youtube]     Downloading comment API JSON reply thread 1 (67/102)
[youtube]     Downloading comment API JSON reply thread 2 (70/102)
[youtube]     Downloading comment API JSON reply thread 3 (73/102)
[youtube]     Downloading comment API JSON reply thread 4 (77/102)
WARNING: [youtube] None. Retrying (1/3)...
[youtube]     Downloading comment API JSON reply thread 4 (77/102)
WARNING: [youtube] None. Retrying (2/3)...
[youtube]     Downloading comment API JSON reply thread 4 (77/102)
WARNING: [youtube] None. Retrying (3/3)...
[youtube]     Downloading comment API JSON reply thread 4 (77/102)
ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/[redacted]/yt-dlp/yt_dlp/YoutubeDL.py", line 1441, in wrapper
    return func(self, *args, **kwargs)
  File "/home/[redacted]/yt-dlp/yt_dlp/YoutubeDL.py", line 1538, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/[redacted]/yt-dlp/yt_dlp/YoutubeDL.py", line 1596, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/[redacted]/yt-dlp/yt_dlp/YoutubeDL.py", line 2602, in process_video_result
    self.post_extract(info_dict)
  File "/home/[redacted]/yt-dlp/yt_dlp/YoutubeDL.py", line 3369, in post_extract
    actual_post_extract(info_dict or {})
  File "/home/[redacted]/yt-dlp/yt_dlp/YoutubeDL.py", line 3367, in actual_post_extract
    info_dict.update(post_extractor())
  File "/home/[redacted]/yt-dlp/yt_dlp/extractor/common.py", line 3735, in extractor
    comments.append(next(generator))
  File "/home/[redacted]/yt-dlp/yt_dlp/extractor/youtube.py", line 3004, in _real_comment_extract
    yield from self._comment_entries(renderer, ytcfg, video_id)
  File "/home/[redacted]/yt-dlp/yt_dlp/extractor/youtube.py", line 2978, in _comment_entries
    for entry in extract_thread(continuation_items):
  File "/home/[redacted]/yt-dlp/yt_dlp/extractor/youtube.py", line 2904, in extract_thread
    yield from itertools.islice(comment_entries_iter, min(
  File "/home/[redacted]/yt-dlp/yt_dlp/extractor/youtube.py", line 2957, in _comment_entries
    response = self._extract_response(
  File "/home/[redacted]/yt-dlp/yt_dlp/extractor/youtube.py", line 768, in _extract_response
    for retry in self.RetryManager():
  File "/home/[redacted]/yt-dlp/yt_dlp/utils.py", line 5754, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/home/[redacted]/yt-dlp/yt_dlp/extractor/common.py", line 3856, in _error_or_warning
    RetryManager.report_retry(err, _count or int(fatal), _retries, info=self.to_screen, warn=self.report_warning,
  File "/home/[redacted]/yt-dlp/yt_dlp/utils.py", line 5762, in report_retry
    raise e
yt_dlp.utils.ExtractorError: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by coletdjnz** [comment]
It's a YouTube issue. You can use `--ignore-errors` to ignore.


Though thinking about it, we should really have some more fine grained controls available over the incomplete data issue. 

This one is occurring in the replies, so I'm assuming the rest of comment extraction would technically work.

Also there are cases where you want to ignore this error for comment extraction but not any other errors (e.g. network)
