### ISSUE TITLE
Unable to extract title on twitcasting

### ISSUE THREAD

**Issue by yk6** [yt-dlp/yt-dlp#467]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running yt-dlp version **2021.06.23**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
 yt-dlp https://twitcasting.tv/quon01tama/movie/688324697 --verbose
[debug] Command-line config: ['https://twitcasting.tv/quon01tama/movie/688324697', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.06.23
[debug] Python version 3.6.9 (CPython 64bit) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] [TwitCasting] Extracting URL: https://twitcasting.tv/quon01tama/movie/688324697
[TwitCasting] 688324697: Downloading webpage
ERROR: Unable to extract og:title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/yk6/.local/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 1138, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yk6/.local/lib/python3.6/site-packages/yt_dlp/YoutubeDL.py", line 1163, in __extract_info
    ie_result = ie.extract(url)
  File "/home/yk6/.local/lib/python3.6/site-packages/yt_dlp/extractor/common.py", line 568, in extract
    ie_result = self._real_extract(url)
  File "/home/yk6/.local/lib/python3.6/site-packages/yt_dlp/extractor/twitcasting.py", line 79, in _real_extract
    or self._html_search_meta(['og:title', 'twitter:title'], webpage, fatal=True))
  File "/home/yk6/.local/lib/python3.6/site-packages/yt_dlp/extractor/common.py", line 1244, in _html_search_meta
    html, display_name, fatal=fatal, group='content', **kwargs)
  File "/home/yk6/.local/lib/python3.6/site-packages/yt_dlp/extractor/common.py", line 1129, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/yk6/.local/lib/python3.6/site-packages/yt_dlp/extractor/common.py", line 1120, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract og:title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE
Seems like the / in the title is not escaped properly and casuing issue?

**Comment by pukkandan** [comment]
You need to provide `--video-password`. If it still doesn't work, send me the password (either on discord, or via email) so that I can test

![image](https://user-images.githubusercontent.com/6623388/125214031-82c6ac80-e2d2-11eb-91ef-7c111800d5f1.png)

**Comment by pukkandan** [comment]
Closed due to inactivity
