### ISSUE TITLE
Add support for VinteraTV.com links

### ISSUE THREAD

**Issue by VFomich** [yt-dlp/yt-dlp#4677]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Russia

### Example URLs

https://www.vinteratv.com/?channel=641
https://www.vinteratv.com/?channel=506

### Provide a description that is worded well enough to be understood

VinteraTV.com is a platform that does re-streaming of various free TV channels (apparently legally), so I'd like to have an opportunity to open their streams in a yt-dlp base external player. However currently that type of links are not supported and the .m3u8 links don't seem to be static long-term there, so it would be good if the direct support for this site's streams would be added.

Example links (working, no account needed, apparently no geoblock too):
https://www.vinteratv.com/?channel=641
https://www.vinteratv.com/?channel=506

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.vinteratv.com/?channel=641']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [5593720] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg git-2022-07-31-e725c5e24 (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [generic] Extracting URL: https://www.vinteratv.com/?channel=641
[generic] ?channel=641: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?channel=641: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.vinteratv.com/?channel=641
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1441, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1517, in __extract_info
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 3077, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.vinteratv.com/?channel=641
```

**Comment by pukkandan** [comment]
This is extremely suspicious. Why do you think they are redistributing it legally?

**Comment by VFomich** [comment]
> This is extremely suspicious. Why do you think they are redistributing it legally?

Main reason is that they are an official media company licenced in Russia (licence information in Russian can be found here: https://rkn.gov.ru/mass-communications/reestr/media/?id=633455&page=, the information is about vintera.tv company though, but vinteratv.com is the subsite that this company uses and has links to vintera.tv and vice versa, not to mention the [site info on who.is](https://who.is/whois/vinteratv.com)) and at least currently that type of companies are not allowed into piracy there. 

Another reason is that their service is available both in google play (https://play.google.com/store/apps/details?id=tv.vintera.smarttv.v2) and in apple store (https://apps.apple.com/us/app/vintera-tv/id1570577786) and as far as I know they don't tolerate piracy much. 

Finally as an indirect evidence I see that they have a lot of geoblocks on their channels, illegal sites usually are just removing those.

**Comment by pukkandan** [comment]
`vintara.tv` and `vintaratv.com` are the same?

**Comment by pukkandan** [comment]
I didn't realize vintara.tv and vintaratv.com are the same
