### ISSUE TITLE
[BitChute] No video formats found

### ISSUE THREAD

**Issue by progonkpa** [yt-dlp/yt-dlp#4685]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Belgium

### Provide a description that is worded well enough to be understood

While downloading a channel's metadata with `--dump-single-json / -J`, is see errors in the log.

'video URL is invalid, skipping: HTTP Error 400: Bad Request', though the URL looks fine a few lines up in the log.

'yt_dlp.utils.ExtractorError: [BitChute] kcOsd2tUgAA: No video formats found!'.

When I try to download such a link without -J the result is the same, no formats.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--dump-single-json', '--verbose', 'https://www.bitchute.com/channel/corbettreport/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.16.20-2-MANJARO-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [BitChuteChannel] Extracting URL: https://www.bitchute.com/channel/corbettreport/
[download] Downloading playlist: corbettreport
[BitChuteChannel] corbettreport: Downloading channel page 1
[BitChuteChannel] corbettreport: Downloading channel page 2
[BitChuteChannel] corbettreport: Downloading channel page 3
[BitChuteChannel] corbettreport: Downloading channel page 4
[BitChuteChannel] corbettreport: Downloading channel page 5
[BitChuteChannel] corbettreport: Downloading channel page 6
[BitChuteChannel] corbettreport: Downloading channel page 7
[BitChuteChannel] corbettreport: Downloading channel page 8
[BitChuteChannel] corbettreport: Downloading channel page 9
[BitChuteChannel] corbettreport: Downloading channel page 10
[BitChuteChannel] corbettreport: Downloading channel page 11
[BitChuteChannel] corbettreport: Downloading channel page 12
[BitChuteChannel] corbettreport: Downloading channel page 13
[BitChuteChannel] corbettreport: Downloading channel page 14
[BitChuteChannel] corbettreport: Downloading channel page 15
[BitChuteChannel] corbettreport: Downloading channel page 16
[BitChuteChannel] corbettreport: Downloading channel page 17
[BitChuteChannel] corbettreport: Downloading channel page 18
[BitChuteChannel] corbettreport: Downloading channel page 19
[BitChuteChannel] corbettreport: Downloading channel page 20
[BitChuteChannel] corbettreport: Downloading channel page 21
[BitChuteChannel] corbettreport: Downloading channel page 22
[BitChuteChannel] corbettreport: Downloading channel page 23
[BitChuteChannel] corbettreport: Downloading channel page 24
[BitChuteChannel] corbettreport: Downloading channel page 25
[BitChuteChannel] corbettreport: Downloading channel page 26
[BitChuteChannel] corbettreport: Downloading channel page 27
[BitChuteChannel] corbettreport: Downloading channel page 28
[BitChuteChannel] corbettreport: Downloading channel page 29
[BitChuteChannel] Playlist corbettreport: Downloading 695 videos of 695
[debug] The information of all playlist entries will be held in memory
[download] Downloading video 1 of 695
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/IiVjmN9QLAlS
[BitChute] IiVjmN9QLAlS: Downloading webpage
[BitChute] IiVjmN9QLAlS: Checking video URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] IiVjmN9QLAlS: Downloading 1 format(s): 0
[download] Downloading video 2 of 695
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/i4pa4yQnjq7f
[BitChute] i4pa4yQnjq7f: Downloading webpage
[BitChute] i4pa4yQnjq7f: Checking video URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] i4pa4yQnjq7f: Downloading 1 format(s): 0
...
[download] Downloading video 433 of 695
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/FzVd7XCTu28
[BitChute] FzVd7XCTu28: Downloading webpage
[BitChute] FzVd7XCTu28: Checking video URL
[BitChute] FzVd7XCTu28: video URL is invalid, skipping: HTTP Error 404: Not Found
ERROR: [BitChute] FzVd7XCTu28: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/freetalk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/home/freetalk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/freetalk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/freetalk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2481, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/freetalk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1002, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [BitChute] FzVd7XCTu28: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by csehszlovakze** [comment]
Checking the video in question:

```
$ yt-dlp -vF https://www.bitchute.com/video/FzVd7XCTu28
[debug] Command-line config: ['-vF', 'https://www.bitchute.com/video/FzVd7XCTu28']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [5593720] (linux_exe)
[debug] Python 3.10.5 (CPython 64bit) - Linux-4.15.0-144-generic-x86_64-with-glibc2.27 (glibc 2.27)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/FzVd7XCTu28
[BitChute] FzVd7XCTu28: Downloading webpage
[BitChute] FzVd7XCTu28: Checking video URL
[BitChute] FzVd7XCTu28: video URL is invalid, skipping: HTTP Error 404: Not Found
ERROR: [BitChute] FzVd7XCTu28: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U                                                                                                               
Traceback (most recent call last):                                                                               
  File "yt_dlp/YoutubeDL.py", line 1441, in wrapper                                                              
  File "yt_dlp/YoutubeDL.py", line 1538, in __extract_info                                                       
  File "yt_dlp/YoutubeDL.py", line 1596, in process_ie_result                                                    
  File "yt_dlp/YoutubeDL.py", line 2514, in process_video_result                                                 
  File "yt_dlp/YoutubeDL.py", line 1009, in raise_no_formats                                                     
yt_dlp.utils.ExtractorError: [BitChute] FzVd7XCTu28: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U     
```

Opening it up in the browser, it doesn't play. When I hit F12 for DevTools, go to the Network tab, filter by Media and reload the page, the video file itself throws a 404 error.  **Contact BitChute support to fix the error!** 

The only thing yt-dlp needs to do is better error management.

**Comment by pukkandan** [comment]
> - [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details

---

> The only thing yt-dlp needs to do is better error management.

How can yt-dlp give better error when even the webpage does not? If you have suggestions, let me know. Otherwise nothing to be done

**Comment by progonkpa** [comment]
> Opening it up in the browser, it doesn't play. When I hit F12 for DevTools, go to the Network tab, filter by Media and reload the page, the video file itself throws a 404 error. **Contact BitChute support to fix the error!**
> 
> The only thing yt-dlp needs to do is better error management.

I double checked, for me `https://www.bitchute.com/video/FzVd7XCTu28/` opens in the browser while via yt-dlp I get said errors.

BitChute has country specific censorship rules so if you try the URL again in Tor, you might find the video does play.

**Comment by pukkandan** [comment]
The video doesn't play for me on a Belgium IP. ig I'll have to take your word for it

**Comment by progonkpa** [comment]
In the browser the page opens and I too quickly assumed the video works while in fact the video keeps loading and there are 404's as @csehszlovakze said so I'll go ahead and close it.

**Comment by csehszlovakze** [comment]
In this case, the direct video URL is https://seedp29xb.bitchute.com/GwPziiQZrVT3/FzVd7XCTu28.mp4 and you'll get a 404 error when trying to access it. It's a known bug among the BitChute team but I have no idea what their plans are to fix it (if any).

**Comment by csehszlovakze** [comment]
@pukkandan
>How can yt-dlp give better error when even the webpage does not? If you have suggestions, let me know. Otherwise nothing to be done

I assumed that this error was a show-stopper for --dump-json, but after trying it on my own channel, I see it's clearly not the case. On the other hand, the error message itself calls the user to submit a bug report, which is totally unnecessary in BitChute's case, so tweaking the error message might be enough. As far as I can tell, every time you get a 404 error for the video file itself the issue is that the file is actually missing, not that yt-dlp failed to find it.

p.s. I'll forward this ticket to the staff so they can look into it on their end.

**Comment by csehszlovakze** [comment]
Reproducing my edit above:

```
$ yt-dlp -q --dump-single-json https://bitchute.com/channel/csehszlovakze | jq -M '.' >muhchute.json
ERROR: [BitChute] mXZ7caXpKgNT: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] zLCoKyq9YixC: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] bisWJ9VLjCvb: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] bCEObO5P4dh0: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] PzHrMIAQXqc6: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] LzlFuHq5xfAy: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] vDOJgM7wZmVg: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] LbOyU6gI7NYD: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] EvLO8bPutwrR: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] LyGAsbs8jpU7: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] bBCkm8TkRA35: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] H79fIb3pBHUG: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] dijzsQcYVmYf: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] F6gDVg7lxa53: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] F6j9qG4nLrsl: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BitChute] CrMUgbaSSBg9: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
the output file https://pastebin.com/A0LWiRpQ (weird, can't attach json files on github)

**Comment by pukkandan** [comment]
The issue template also asks you to "check that all provided URLs are playable in a browser with the same IP and same login details"...

**Comment by csehszlovakze** [comment]
That's a fair point when one's trying to _download_ videos. In my opinion, a mass *metadata* fetch could be an exception :) provided it's not too much of a hassle of course.
