### ISSUE TITLE
please report this issue on ... filling out the broken site issue template

### ISSUE THREAD

**Issue by bigmizell** [yt-dlp/yt-dlp#4699]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

us

### Provide a description that is worded well enough to be understood

Weird long python parsing errors running this command

yt-dlp --extract-audio --audio-format mp3 --audio-quality 0 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=BgE3YbQv1dc

It actually finished and the song appears to be working fine.  But the list of errors is below.  Pretty long.

The site says there is a new version released 8/14/2022, but my version says 8/3/2022.  However it will not update from apt.  Ran apt update already.  Running on ubuntu mate

sudo apt install yt-dlp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
yt-dlp is already the newest version (2022.03.08.1-1~bpo20.04.1).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y

using the -vU flag it wont complete it says update and exits

yt-dlp -vU --extract-audio --audio-format mp3 --audio-quality 0 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=BgE3YbQv1dc
[debug] Command-line config: ['-vU', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', '-o', '%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=BgE3YbQv1dc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-122-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: yt-dlp's self-update mechanism is disabled on Debian.
Please update yt-dlp using apt(8).
See https://packages.debian.org/sid/yt-dlp for the latest packaged version.

Seems to only cause a problem with this particular url so far knock on wood.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
armel@tibet:~/nfs_tibet/youtube.delos.music$ yt-dlp --extract-audio --audio-format mp3 --audio-quality 0 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=BgE3YbQv1dc
[youtube] BgE3YbQv1dc: Downloading webpage
[youtube] BgE3YbQv1dc: Downloading android player API JSON
[youtube] BgE3YbQv1dc: Downloading player 1f7d5369
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = 366YYdt_ONayot ; player = https://www.youtube.com/s/player/1f7d5369/player_ias.vflset/en_US/base.js
BgE3YbQv1dc: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2498, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2530, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 536, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 277, in interpret_expression
    right_val = self.interpret_expression(m.group('expr'), local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 170, in interpret_expression
    inner, outer = self._separate_at_paren(expr, ']')
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 117, in _separate_at_paren
    raise ExtractorError(f'No terminating paren {delim} in {expr}')
yt_dlp.utils.ExtractorError: No terminating paren ] in [1637657201,-990522961,-903445535,-193926786,-419211961,916534104,3,"10JuT",-1785813920,0,249972989,-1730853410,__yt_dlp_jsinterp_obj2,6,620231209,120801802,__yt_dlp_jsinterp_obj3,__yt_dlp_jsinterp_obj4,874287527,__yt_dlp_jsinterp_obj5,__yt_dlp_jsinterp_obj6,__yt_dlp_jsinterp_obj7,null,__yt_dlp_jsinterp_obj8,__yt_dlp_jsinterp_obj9,"QexGvrB",__yt_dlp_jsinterp_obj10,706907296,1755053660,578623715,b,b,"0_BCXVv",-1653236833,"4PMy",1926628773,-1874691788,null,1881963208,-275438258,"4PMy",5,-1233501026,1316224455,-404405336,1839430453,492774233,__yt_dlp_jsinterp_obj11,"mfZru","cfYAzm",1897615910,414154674,"IluoVc5",null,1,"XsmT",-659785013,577478260,-419211961,1087899650,/,,[/,913,/](,)}/,-1108361946,__yt_dlp_jsinterp_obj12,"5JW2N",__yt_dlp_jsinterp_obj13,__yt_dlp_jsinterp_obj14,"m_uNxqw",-1525817632,117140678,-558750762,4,"NBJWI-w",2,549412047,__yt_dlp_jsinterp_obj16,"IxP3jU",-1745398519,-1653236833,__yt_dlp_jsinterp_obj17,"split",676914311,120801802,969695751,b,"},{][,'",__yt_dlp_jsinterp_obj18,1222617660,__yt_dlp_jsinterp_obj19,179618702,9,-310126674,2027719642,-1573330244,1643986405,__yt_dlp_jsinterp_obj20,917600364,-1259506412,-1973718311,__yt_dlp_jsinterp_obj21,1715552419];c[22]=c;c[37]=c;c[53]=c;try{try{5>=c[41]&&(0,c[85])((0,c[16])(c[53]),c[5],c[69],c[81]),(0,c[76])(),(0,c[83])(c[new Date("December 31 1969 18:00:16 CST")/1E3]),(0,c[37])(c[77])}catch(d){(0>=c[27]||((0,c[14])((0,c[34])(c[77],c[new Date("Wednesday December 31 1969 16:00:43 PST")/1E3]),c[79],c[89],c[62])|(0,c[72])(c[57]),null))&&((0,c[68])(c[92],c[57]),(0,c[89])(c[5],c[46-Math.pow(6,1)%496],(0,c[1])()),c[14])(c[0],c[57])}finally{4<c[47]&&(0,c[3])((0,c[94])(c[57],c[73]),c[-454- -156*Math.pow(3,1)],c[38],c[5])}try{(7<c[Math.pow(1,4)%438- -81]||((0,c[68])(c[8],c[35]),0))&&(0,c[37])(c[16]),(0,c[25])(c[68],c[2]),(0,c[73])(c[69],c[61])%(0,c[133+Math.pow(5,4)+-685])(c[19+Math.pow(7,2)+0],c[8])}catch(d){}try{9>=c[185+Math.pow(5,3)-281]&&(2<c[29]||((0,c[14])((0,c[0])(c[-119*Math.pow(6,1)+783],c[65],(0,c[12])()),c[73],c[62],c[91]),0))&&(0,c[14])((0,c[34])(c[77],c[88]),c[5],c[77],c[96])}catch(d){(0,c[90])(c[68],c[238*Math.pow(6,2)-new Date("1969-12-31T22:22:12.000-04:00")/1E3],(0,c[1])())}finally{8>=c[Math.pow(8,5)- -30595-63349]&&(7<c[-736- -6*Math.pow(5,3)]&&((0,c[0])(((0,c[0])((0,c[73])(c[46],c[6]),c[73],c[68],c[63]),(0,c[37])(c[77]))<<(0,c[90])(c[69],c[50],(0,c[1])()),c[90],c[16],c[74],(0,c[12])()),"4")||(0,c[0])((((0,c[25])(c[56],c[69]),c[0])((0,c[34])(c[77],c[98]),c[37],c[46]),(0,c[74])(c[82],c[83])),c[65],c[37],c[28])),7>=c[13]&&(0,c[17])((0,c[74])(c[77],c[83]),(0,c[0])((0,c[64])((0,c[9])(c[31],c[55],(0,c[98])()),c[20],(0,c[9])(c[30],c[79],(0,c[87])()),c[27],c[37]),c[61],c[79],c[82]),c[96],(0,c[90])(c[27],c[10]),c[61],c[49],c[38]),3<c[50]?(0,c[96])((0,c[22])(c[49],c[91]),c[5],c[79],c[28],(0,c[83])()):(0,c[96])((0,c[90])(c[26],c[56]),c[90],c[26],c[69]),(5<c[37]||((0,c[70])(c[8],c[18]),0))&&(0,c[24])(c[46],c[67],(0,c[19])())}try{c[0]<=-178*Math.pow(3,2)- -1610&&(6<c[21]?(0,c[-12*Math.pow(4,2)+224])((0,c[15])((0,c[41])(c[new Date("31 December 1969 18:00:45 MDT")/1E3],c[66]),c[Math.pow(1,2)- -2156-2133],c[438%Math.pow(6,5)-393],c[81],(0,c[19])()),(0,c[80])(c[37],c[59]),c[15],(0,c[31])(c[37]),c[41],c[46],c[17]):(0,c[34])(c[62],(0,c[9])(c[52],c[5]),c[Math.pow(4,1)- -14388+-14361],(0,c[35])(c[83],c[46]),(0,c[89])(c[93],c[45]),(0,c[89])(c[74],c[37]),c[18])),8>=c[62]&&(((0,c[14])(c[5],c[12]),c[29])(c[92],c[96]),c[44])(c[87],c[63])>=(0,c[47])(c[72]),3<c[79]&&(8<c[60]||((((0,c[84])(c[21],c[25]),c[64])(c[29],c[73]),c[new Date("Wednesday 31 December 1969 20:00:14 EDT")/1E3])(c[43],c[30])<=(0,c[64])(c[59],c[21]),0))&&(0,c[7])((0,c[55])(c[27],c[82]),(0,c[66])(c[21],c[97],(0,c[11])()),c[90],(0,c[66])(c[20],c[65],(0,c[94])()),c[64],c[95],c[20])}catch(d){(0,c[90])((0,c[66])(c[21],c[61],(0,c[11])()),c[16],c[27],c[51]),(0,c[84])(c[21],c[99])}finally{6>=c[1]&&(0,c[10])(c[57],c[20]),7>=c[44]&&(5<c[62]&&((0,c[64])(c[87],c[20]),9)||(0,c[64])(c[35],c[73]))}; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
 (caused by ExtractorError('No terminating paren ] in [1637657201,-990522961,-903445535,-193926786,-419211961,916534104,3,"10JuT",-1785813920,0,249972989,-1730853410,__yt_dlp_jsinterp_obj2,6,620231209,120801802,__yt_dlp_jsinterp_obj3,__yt_dlp_jsinterp_obj4,874287527,__yt_dlp_jsinterp_obj5,__yt_dlp_jsinterp_obj6,__yt_dlp_jsinterp_obj7,null,__yt_dlp_jsinterp_obj8,__yt_dlp_jsinterp_obj9,"QexGvrB",__yt_dlp_jsinterp_obj10,706907296,1755053660,578623715,b,b,"0_BCXVv",-1653236833,"4PMy",1926628773,-1874691788,null,1881963208,-275438258,"4PMy",5,-1233501026,1316224455,-404405336,1839430453,492774233,__yt_dlp_jsinterp_obj11,"mfZru","cfYAzm",1897615910,414154674,"IluoVc5",null,1,"XsmT",-659785013,577478260,-419211961,1087899650,/,,[/,913,/](,)}/,-1108361946,__yt_dlp_jsinterp_obj12,"5JW2N",__yt_dlp_jsinterp_obj13,__yt_dlp_jsinterp_obj14,"m_uNxqw",-1525817632,117140678,-558750762,4,"NBJWI-w",2,549412047,__yt_dlp_jsinterp_obj16,"IxP3jU",-1745398519,-1653236833,__yt_dlp_jsinterp_obj17,"split",676914311,120801802,969695751,b,"},{][,\'",__yt_dlp_jsinterp_obj18,1222617660,__yt_dlp_jsinterp_obj19,179618702,9,-310126674,2027719642,-1573330244,1643986405,__yt_dlp_jsinterp_obj20,917600364,-1259506412,-1973718311,__yt_dlp_jsinterp_obj21,1715552419];c[22]=c;c[37]=c;c[53]=c;try{try{5>=c[41]&&(0,c[85])((0,c[16])(c[53]),c[5],c[69],c[81]),(0,c[76])(),(0,c[83])(c[new Date("December 31 1969 18:00:16 CST")/1E3]),(0,c[37])(c[77])}catch(d){(0>=c[27]||((0,c[14])((0,c[34])(c[77],c[new Date("Wednesday December 31 1969 16:00:43 PST")/1E3]),c[79],c[89],c[62])|(0,c[72])(c[57]),null))&&((0,c[68])(c[92],c[57]),(0,c[89])(c[5],c[46-Math.pow(6,1)%496],(0,c[1])()),c[14])(c[0],c[57])}finally{4<c[47]&&(0,c[3])((0,c[94])(c[57],c[73]),c[-454- -156*Math.pow(3,1)],c[38],c[5])}try{(7<c[Math.pow(1,4)%438- -81]||((0,c[68])(c[8],c[35]),0))&&(0,c[37])(c[16]),(0,c[25])(c[68],c[2]),(0,c[73])(c[69],c[61])%(0,c[133+Math.pow(5,4)+-685])(c[19+Math.pow(7,2)+0],c[8])}catch(d){}try{9>=c[185+Math.pow(5,3)-281]&&(2<c[29]||((0,c[14])((0,c[0])(c[-119*Math.pow(6,1)+783],c[65],(0,c[12])()),c[73],c[62],c[91]),0))&&(0,c[14])((0,c[34])(c[77],c[88]),c[5],c[77],c[96])}catch(d){(0,c[90])(c[68],c[238*Math.pow(6,2)-new Date("1969-12-31T22:22:12.000-04:00")/1E3],(0,c[1])())}finally{8>=c[Math.pow(8,5)- -30595-63349]&&(7<c[-736- -6*Math.pow(5,3)]&&((0,c[0])(((0,c[0])((0,c[73])(c[46],c[6]),c[73],c[68],c[63]),(0,c[37])(c[77]))<<(0,c[90])(c[69],c[50],(0,c[1])()),c[90],c[16],c[74],(0,c[12])()),"4")||(0,c[0])((((0,c[25])(c[56],c[69]),c[0])((0,c[34])(c[77],c[98]),c[37],c[46]),(0,c[74])(c[82],c[83])),c[65],c[37],c[28])),7>=c[13]&&(0,c[17])((0,c[74])(c[77],c[83]),(0,c[0])((0,c[64])((0,c[9])(c[31],c[55],(0,c[98])()),c[20],(0,c[9])(c[30],c[79],(0,c[87])()),c[27],c[37]),c[61],c[79],c[82]),c[96],(0,c[90])(c[27],c[10]),c[61],c[49],c[38]),3<c[50]?(0,c[96])((0,c[22])(c[49],c[91]),c[5],c[79],c[28],(0,c[83])()):(0,c[96])((0,c[90])(c[26],c[56]),c[90],c[26],c[69]),(5<c[37]||((0,c[70])(c[8],c[18]),0))&&(0,c[24])(c[46],c[67],(0,c[19])())}try{c[0]<=-178*Math.pow(3,2)- -1610&&(6<c[21]?(0,c[-12*Math.pow(4,2)+224])((0,c[15])((0,c[41])(c[new Date("31 December 1969 18:00:45 MDT")/1E3],c[66]),c[Math.pow(1,2)- -2156-2133],c[438%Math.pow(6,5)-393],c[81],(0,c[19])()),(0,c[80])(c[37],c[59]),c[15],(0,c[31])(c[37]),c[41],c[46],c[17]):(0,c[34])(c[62],(0,c[9])(c[52],c[5]),c[Math.pow(4,1)- -14388+-14361],(0,c[35])(c[83],c[46]),(0,c[89])(c[93],c[45]),(0,c[89])(c[74],c[37]),c[18])),8>=c[62]&&(((0,c[14])(c[5],c[12]),c[29])(c[92],c[96]),c[44])(c[87],c[63])>=(0,c[47])(c[72]),3<c[79]&&(8<c[60]||((((0,c[84])(c[21],c[25]),c[64])(c[29],c[73]),c[new Date("Wednesday 31 December 1969 20:00:14 EDT")/1E3])(c[43],c[30])<=(0,c[64])(c[59],c[21]),0))&&(0,c[7])((0,c[55])(c[27],c[82]),(0,c[66])(c[21],c[97],(0,c[11])()),c[90],(0,c[66])(c[20],c[65],(0,c[94])()),c[64],c[95],c[20])}catch(d){(0,c[90])((0,c[66])(c[21],c[61],(0,c[11])()),c[16],c[27],c[51]),(0,c[84])(c[21],c[99])}finally{6>=c[1]&&(0,c[10])(c[57],c[20]),7>=c[44]&&(5<c[62]&&((0,c[64])(c[87],c[20]),9)||(0,c[64])(c[35],c[73]))}; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
[youtube] BgE3YbQv1dc: Downloading MPD manifest
[youtube] BgE3YbQv1dc: Downloading MPD manifest
[info] BgE3YbQv1dc: Downloading 1 format(s): 251
[download] Destination: Mattias Tell - Breathe In, Breathe Out (Instrumental Version).webm
[download] 100% of 4.46MiB in 00:00
[ExtractAudio] Destination: Mattias Tell - Breathe In, Breathe Out (Instrumental Version).mp3
Deleting original file Mattias Tell - Breathe In, Breathe Out (Instrumental Version).webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
See pinned issues

**Comment by pukkandan** [comment]
And update your yt-dlp

**Comment by pukkandan** [comment]
> The site says there is a new version released 8/14/2022, but my version says 8/3/2022. However it will not update from apt. Ran apt update already. Running on ubuntu mate

If apt maintainers are not updating the package, I can't do anything. You can try reporting to them; or install with one of the officially provided methods
