### ISSUE TITLE
Allow-unplayable is ignored when yt-dlp is called from python

### ISSUE THREAD

**Issue by zhenyahacker** [yt-dlp/yt-dlp#4720]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Bug is simple: if I run yt-dlp by executing standalone command with "--allow-unplayable-formats -F" key it work as intended - it gives the warning about DRM and gives the list of formats.

When I do exactly the same by python script by importing&using yt-dlp package it ignores the "--allow-unplayable-formats" key and just blames that manifest is DRM-protected.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
import yt_dlp

YDL_OPTIONS = {
    'allow-unplayable-formats ': True
}

with yt_dlp.YoutubeDL(YDL_OPTIONS) as ydl:
    info = ydl.extract_info(DRM_protected_manifest_url, download=False)

E:\folder>python test.py
[generic] Manifest: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Manifest: Extracting information
ERROR: [generic] Manifest: This video is DRM protected
Traceback (most recent call last):
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1442, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1539, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1597, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2515, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1010, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [generic] Manifest: This video is DRM protected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\folder\test.py", line 8, in <module>
    info = ydl.extract_info(DRM_protected_manifest_url, download=False)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1433, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1460, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 979, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 922, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [generic] Manifest: This video is DRM protected

E:\folder>
```

**Comment by pukkandan** [comment]
The argument name is wrong. Besides, as clearly indicated in the readme, it's not intended to be used by end users

**Comment by zhenyahacker** [comment]
The embeddable python package is meant to have the same amount of capabilities as standalone executive version, isn`t it?

**Comment by pukkandan** [comment]
Read my answer again

**Comment by gamer191** [comment]
@zhenyahacker use `allow_unplayable_formats`, instead of `allow-unplayable-formats`
see https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/options.py for the argument names of other options :)
