### ISSUE TITLE
`--embed-thumbnail` leaves `.webp` behind if conversion fails

### ISSUE THREAD

**Issue by mdashlw** [yt-dlp/yt-dlp#4722]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

If `webp` -> `png` conversion of the thumbnail fails for some reason, the `.webp` file is not removed, which I think is an unexpected side effect

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--no-progress', '--no-playlist', '--embed-thumbnail', '--merge-output-format', 'mp4', '--verbose', '-f', 'bestvideo[vcodec^=avc1]+bestaudio', '-o', '../destination/filename.%(ext)s', 'https://youtu.be/videoid']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.15.0-46-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Crypto-3.15.0, certifi-2020.06.20, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://youtu.be/videoid
[youtube] videoid: Downloading webpage
[youtube] videoid: Downloading android player API JSON
[youtube] videoid: Downloading MPD manifest
[youtube] videoid: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] videoid: Downloading 1 format(s): 137+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: ../destination/filename.webp
[download] ../destination/filename.mp4 has already been downloaded
[ThumbnailsConvertor] Converting thumbnail "../destination/filename.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:../destination/filename.webp' -movflags +faststart 'file:../destination/filename.png'
[debug] ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libsmbclient
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[image2 @ 0x560b37ff7800] decoding for stream 0 failed
[image2 @ 0x560b37ff7800] Could not find codec parameters for stream 0 (Video: webp, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, image2, from 'file:../destination/filename.webp':
  Duration: 00:00:00.04, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: webp, none, 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (webp (native) -> png (native))
Press [q] to stop, [?] for help
Error while decoding stream #0:0: Invalid data found when processing input
Cannot determine format of input stream 0:0 after EOF
Error marking filters as finished
Conversion failed!

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3246, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3416, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3398, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3377, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 125, in wrapper
    return func(self, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/embedthumbnail.py", line 86, in run
    thumbnail_filename = convertor.convert_thumbnail(thumbnail_filename, 'png')
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 1093, in convert_thumbnail
    self.real_run_ffmpeg(
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 361, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by pukkandan** [comment]
Will need to see why the conversion fails. But leaving the file behind is not a bug. We do not delete intermediate files in case of errors

**Comment by mdashlw** [comment]
> But leaving the file behind is not a bug. We do not delete intermediate files in case of errors

Is it possible to add `--cleanup` or something similar? I'm downloading hundreds of videos, having corrupted `.webp`s occasionally which you have to delete **manually** is not convenient.

> Will need to see why the conversion fails.

This is a separate issue. I suspect yt-dlp doesn't retry on network errors and bad status codes, which is kind of a big deal.

**Comment by pukkandan** [comment]
> > Will need to see why the conversion fails.
> 
> This is a separate issue. I suspect yt-dlp doesn't retry on network errors and bad status codes, which is kind of a big deal.

Give the actual video id

**Comment by pukkandan** [comment]
> > But leaving the file behind is not a bug. We do not delete intermediate files in case of errors
> 
> Is it possible to add `--cleanup` or something similar? I'm downloading hundreds of videos, having corrupted `.webp`s occasionally which you have to delete **manually** is not convenient.

You can set a temp path (`-P temp:path`) for the intermediate files

**Comment by mdashlw** [comment]
> > > But leaving the file behind is not a bug. We do not delete intermediate files in case of errors
> > 
> > 
> > Is it possible to add `--cleanup` or something similar? I'm downloading hundreds of videos, having corrupted `.webp`s occasionally which you have to delete **manually** is not convenient.
> 
> You can set a temp path (`-P temp:path`) for the intermediate files

Thanks, I will try `-P temp:/tmp`



> > > Will need to see why the conversion fails.
> > 
> > 
> > This is a separate issue. I suspect yt-dlp doesn't retry on network errors and bad status codes, which is kind of a big deal.
> 
> Give the actual video id

not specific to any video. https://github.com/yt-dlp/yt-dlp/blob/992dc6b4863d0e60f2a1ce3933f67814d8a17f8d/yt_dlp/YoutubeDL.py#L3920 doesn't handle status codes? will try to debug later

**Comment by eladkarako** [comment]
YouTube actually have an alternative  
https://i.ytimg.com/vi_webp/dQw4w9WgXcQ/maxresdefault.webp  
https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg  
and it's the same quality.  

- no ffmpeg with webp lib is needed.  
- skip conversion all together if user opt for jpg to begin with.

**Comment by pukkandan** [comment]
@mdashlw Nothing I can do unless you can give log with video ID unredacted

**Comment by mdashlw** [comment]
After some debugging, the response looks completely normal. `Content-Length` is also correct.
Downloaded corrupted `.webp` file: https://mega.nz/file/zocHhQLT#rpL813YrUo399vB5Bg9SzGyvXeWTpw4C76fbVKW4yMU
Maybe the server abruptly closes the connection and this is not handled? Note that this is not specific to any video
```
{'url': 'https://i.ytimg.com/vi_webp/3z-mjIz6uA8/maxresdefault.webp', 'preference': 0, 'id': '41'}
````
```
send: b'GET /vi_webp/3z-mjIz6uA8/maxresdefault.webp HTTP/1.1\r\nHost: i.ytimg.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Accept-Ranges: bytes
header: Vary: Origin
header: Cross-Origin-Resource-Policy: cross-origin
header: Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="youtube"
header: Report-To: {"group":"youtube","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/youtube"}]}
header: Content-Length: 86916
header: X-Content-Type-Options: nosniff
header: Server: sffe
header: X-XSS-Protection: 0
header: Date: Thu, 25 Aug 2022 13:23:24 GMT
header: Expires: Thu, 25 Aug 2022 15:23:24 GMT
header: Cache-Control: public, max-age=7200
header: ETag: "1656438284"
header: Content-Type: image/webp
header: Age: 701
header: Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
header: Connection: close
```
