### ISSUE TITLE
rajdigitaltv.com

### ISSUE THREAD

**Issue by Et-tman** [yt-dlp/yt-dlp#4746]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

https://www.rajdigitaltv.com/movies/thenali/RAJTV_MOVIE_61d91b7b99c95163af7bcf46

### Provide a description that is worded well enough to be understood

Rajdigitaltv is a subscription-based streaming site for Tamil movies. I don't know if the content is downloadable using yt-dlp. I hope you look into it.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', 'https://www.rajdigitaltv.com/movies/thenali/RAJTV_MOVIE_61d91b7b99c95163af7bcf46']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-28-git-6f7d3bde11-full_build-www.gyan.dev (setts), ffprobe 2022-07-28-git-6f7d3bde11-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Alien\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Alien\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3174 cookies from chrome
[debug] cookie version breakdown: {'v10': 3174, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [generic] Extracting URL: https://www.rajdigitaltv.com/movies/thenali/RAJTV_MOVIE_61d91b7b99c95163af7bcf46
[generic] RAJTV_MOVIE_61d91b7b99c95163af7bcf46: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] RAJTV_MOVIE_61d91b7b99c95163af7bcf46: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.rajdigitaltv.com/movies/thenali/RAJTV_MOVIE_61d91b7b99c95163af7bcf46
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1442, in wrapper
    raise
  File "yt_dlp\YoutubeDL.py", line 1518, in __extract_info
    if process:
  File "yt_dlp\extractor\common.py", line 666, in extract
    if ie_result is None:
  File "yt_dlp\extractor\generic.py", line 3077, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.rajdigitaltv.com/movies/thenali/RAJTV_MOVIE_61d91b7b99c95163af7bcf46
```

**Comment by tejasa97** [comment]
![Screenshot 2022-08-26 at 1 38 42 PM](https://user-images.githubusercontent.com/29712423/186854686-72f71875-da52-4e24-8850-6ed0c55103bf.png)

@Et-tman Website asks for a mobile number

**Comment by Et-tman** [comment]
Yeah. It requires phone number. I can share the number with you. But, it has OTP verification.

**Comment by Et-tman** [comment]
> ![Screenshot 2022-08-26 at 1 38 42 PM](https://user-images.githubusercontent.com/29712423/186854686-72f71875-da52-4e24-8850-6ed0c55103bf.png)
> 
> @Et-tman Website asks for a mobile number

Yeah. It requires phone number. I can share the number with you. But, it has OTP verification
