### ISSUE TITLE
[wistia]'NoneType' object has no attribute 'decompress'

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4748]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Test link:
https://fast.wistia.net/embed/channel/yvyvu7wjbg?wchannelid=yvyvu7wjbg&wmediaid=1hweyv01o2

Digging further managed to eventually download video from:
https://embed-fastly.wistia.com/deliveries/665ae0923a3b7c9f28abcae4cf73f074827a3389.m3u8

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -F "https://fast.wistia.net/embed/channel/yvyvu7wjbg?wchannelid=yvyvu7wjbg&wmediaid=1hweyv01o2"
[debug] Command-line config: ['-vU', '-F', 'https://fast.wistia.net/embed/channel/yvyvu7wjbg?wchannelid=yvyvu7wjbg&wmediaid=1hweyv01o2']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e088] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.5.1-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
WARNING: Falling back to normal extractor since lazy extractor ABCIE does not have attribute _ENABLED; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Falling back to normal extractor since lazy extractor ABCIViewIE does not have attribute _ENABLED; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

.................. a ton of other warnings like the above but for other extractors...........

[debug] Loaded 1662 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [generic] Extracting URL: https://fast.wistia.net/embed/channel/yvyvu7wjbg?wchannelid=yvyvu7wjbg&wmediaid=1hweyv01o2
[generic] yvyvu7wjbg?wchannelid=yvyvu7wjbg&wmediaid=1hweyv01o2: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] yvyvu7wjbg?wchannelid=yvyvu7wjbg&wmediaid=1hweyv01o2: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a Wistia embed
[debug] [Wistia] Extracting URL: wistia:yvyvu7wjbg
[Wistia] yvyvu7wjbg: Downloading JSON metadata
ERROR: 'NoneType' object has no attribute 'decompress'
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1452, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1528, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/wistia.py", line 178, in _real_extract
    embed_config = self._download_embed_config('media', video_id, url)
  File "./yt-dlp/yt_dlp/extractor/wistia.py", line 20, in _download_embed_config
    embed_config = self._download_json(
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1030, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 994, in download_handle
    res = self._download_webpage_handle(
  File "./yt-dlp/yt_dlp/extractor/common.py", line 864, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 803, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3643, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "./yt-dlp/yt_dlp/utils.py", line 1384, in http_response
    io.BytesIO(self.brotli(resp.read())), old_resp.headers, old_resp.url, old_resp.code)
  File "./yt-dlp/yt_dlp/utils.py", line 1321, in brotli
    return brotli.decompress(data)
AttributeError: 'NoneType' object has no attribute 'decompress'
```

**Comment by coletdjnz** [comment]
This server is weird and always responds with a response in brotli encoding even when the user agent said it didn't support it :rofl: 

It seems like this endpoint is dead anyways - seems like they've transitioned the same API to `fast.wistia.net` domain now (which actually respects the `Accept-Encoding` header).
