### ISSUE TITLE
Particular Vimeo video is not downloading

### ISSUE THREAD

**Issue by HumbleSpirit** [yt-dlp/yt-dlp#478]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
yt-dlp -v https://vimeo.com/179477968
[debug] Command-line config: ['-v', 'https://vimeo.com/179477968']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.07.07 
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.17.0-041700-generic-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [vimeo] Extracting URL: https://vimeo.com/179477968
[vimeo] 179477968: Downloading webpage
[vimeo] 179477968: Extracting information
ERROR: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/vimeo.py", line 725, in _real_extract
    webpage, 'page config'), video_id)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 1123, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract page config; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/vimeo.py", line 746, in _real_extract
    config = json.loads(config)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/vimeo.py", line 725, in _real_extract
    webpage, 'page config'), video_id)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 1123, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract page config; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/vimeo.py", line 746, in _real_extract
    config = json.loads(config)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1142, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1167, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 569, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/vimeo.py", line 762, in _real_extract
    cause=e)
yt_dlp.utils.ExtractorError: Unable to extract info section (caused by JSONDecodeError('Extra data: line 1 column 3 (char 2)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Just trying to download a particular video. All other Vimeo downloads are fine

**Comment by october262** [comment]
has the video been removed/deleted ?? 
getting  "sorry, we couldn't find that page" error

**Comment by pukkandan** [comment]
Same, if you cant access the video, you cant download it

**Comment by HumbleSpirit** [comment]
https://player.vimeo.com/video/179477968 - this way is working

**Comment by pukkandan** [comment]
@HumbleSpirit Then try with that URL

```
$ yt-dlp https://player.vimeo.com/video/179477968 -vF
[debug] Command-line config: ['https://player.vimeo.com/video/179477968', '-vF']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 36ffe05f39
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/179477968
[vimeo] 179477968: Downloading webpage
[vimeo] 179477968: Extracting information
[vimeo] 179477968: Downloading JSON metadata
WARNING: [vimeo] Unable to download JSON metadata: HTTP Error 404: Not Found
[vimeo] 179477968: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 179477968: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 179477968: Downloading fastly_skyfire m3u8 information
[vimeo] 179477968: Downloading fastly_skyfire m3u8 information
[vimeo] 179477968: Downloading akfire_interconnect_quic MPD information
[vimeo] 179477968: Downloading akfire_interconnect_quic MPD information
[vimeo] 179477968: Downloading fastly_skyfire MPD information
[vimeo] 179477968: Downloading fastly_skyfire MPD information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 179477968:
ID                                                  EXT RESOLUTION FPS |   TBR PROTO  | VCODEC        VBR ACODEC     ABR  ASR    NOTE
--------------------------------------------------- --- ---------- --- - ----- ------ - ----------- ----- --------- ---- ------- -----------------------------
hls-akfire_interconnect_quic_sep-audio-high-audio   mp4 audio only     |       m3u8_n |                   unknown                audio
hls-akfire_interconnect_quic_sep-audio-medium-audio mp4 audio only     |       m3u8_n |                   unknown                audio
hls-fastly_skyfire_sep-audio-high-audio             mp4 audio only     |       m3u8_n |                   unknown                audio
hls-fastly_skyfire_sep-audio-medium-audio           mp4 audio only     |       m3u8_n |                   unknown                audio
dash-akfire_interconnect_quic_sep-audio-585671106   m4a audio only     |  130k dash   |                   mp4a.40.2 130k 48000Hz DASH audio, m4a_dash, 48000Hz
dash-fastly_skyfire_sep-audio-585671106             m4a audio only     |  130k dash   |                   mp4a.40.2 130k 48000Hz DASH audio, m4a_dash, 48000Hz
dash-akfire_interconnect_quic_sep-audio-585671116   m4a audio only     |  258k dash   |                   mp4a.40.2 258k 48000Hz DASH audio, m4a_dash, 48000Hz
dash-fastly_skyfire_sep-audio-585671116             m4a audio only     |  258k dash   |                   mp4a.40.2 258k 48000Hz DASH audio, m4a_dash, 48000Hz
http-360p                                           mp4 640x360    25  |       https  | unknown           unknown
dash-akfire_interconnect_quic_sep-video-585671106   mp4 640x360    25  |  516k dash   | avc1.4D401E  516k                        DASH video, mp4_dash
dash-fastly_skyfire_sep-video-585671106             mp4 640x360    25  |  516k dash   | avc1.4D401E  516k                        DASH video, mp4_dash
hls-akfire_interconnect_quic_sep-621                mp4 640x360    25  |  621k m3u8_n | avc1.4D401E  621k
hls-fastly_skyfire_sep-621                          mp4 640x360    25  |  621k m3u8_n | avc1.4D401E  621k
hls-akfire_interconnect_quic-622                    mp4 640x360    25  |  622k m3u8_n | avc1.4D401E  622k mp4a.40.2   0k
hls-fastly_skyfire-622                              mp4 640x360    25  |  622k m3u8_n | avc1.4D401E  622k mp4a.40.2   0k
dash-akfire_interconnect_quic-video-585671106       mp4 640x360    25  |  646k dash   | avc1.4D401E  646k mp4a.40.2   0k 48000Hz DASH video, mp4_dash, 48000Hz
dash-fastly_skyfire-video-585671106                 mp4 640x360    25  |  646k dash   | avc1.4D401E  646k mp4a.40.2   0k 48000Hz DASH video, mp4_dash, 48000Hz
http-540p                                           mp4 960x540    25  |       https  | unknown           unknown
dash-akfire_interconnect_quic_sep-video-585671116   mp4 960x540    25  | 1394k dash   | avc1.64001F 1394k                        DASH video, mp4_dash
dash-fastly_skyfire_sep-video-585671116             mp4 960x540    25  | 1394k dash   | avc1.64001F 1394k                        DASH video, mp4_dash
hls-akfire_interconnect_quic_sep-1437               mp4 960x540    25  | 1437k m3u8_n | avc1.64001F 1437k
hls-fastly_skyfire_sep-1437                         mp4 960x540    25  | 1437k m3u8_n | avc1.64001F 1437k
hls-akfire_interconnect_quic-1565                   mp4 960x540    25  | 1565k m3u8_n | avc1.64001F 1565k mp4a.40.2   0k
hls-fastly_skyfire-1565                             mp4 960x540    25  | 1565k m3u8_n | avc1.64001F 1565k mp4a.40.2   0k
dash-akfire_interconnect_quic-video-585671116       mp4 960x540    25  | 1652k dash   | avc1.64001F 1652k mp4a.40.2   0k 48000Hz DASH video, mp4_dash, 48000Hz
dash-fastly_skyfire-video-585671116                 mp4 960x540    25  | 1652k dash   | avc1.64001F 1652k mp4a.40.2   0k 48000Hz DASH video, mp4_dash, 48000Hz
http-720p                                           mp4 1280x720   25  |       https  | unknown           unknown
dash-akfire_interconnect_quic_sep-video-585671111   mp4 1280x720   25  | 2212k dash   | avc1.640020 2212k                        DASH video, mp4_dash
dash-fastly_skyfire_sep-video-585671111             mp4 1280x720   25  | 2212k dash   | avc1.640020 2212k                        DASH video, mp4_dash
hls-akfire_interconnect_quic_sep-2399               mp4 1280x720   25  | 2399k m3u8_n | avc1.640020 2399k
hls-fastly_skyfire_sep-2399                         mp4 1280x720   25  | 2399k m3u8_n | avc1.640020 2399k
hls-akfire_interconnect_quic-2399                   mp4 1280x720   25  | 2399k m3u8_n | avc1.640020 2399k mp4a.40.2   0k
hls-fastly_skyfire-2399                             mp4 1280x720   25  | 2399k m3u8_n | avc1.640020 2399k mp4a.40.2   0k
dash-akfire_interconnect_quic-video-585671111       mp4 1280x720   25  | 2470k dash   | avc1.640020 2470k mp4a.40.2   0k 48000Hz DASH video, mp4_dash, 48000Hz
dash-fastly_skyfire-video-585671111                 mp4 1280x720   25  | 2470k dash   | avc1.640020 2470k mp4a.40.2   0k 48000Hz DASH video, mp4_dash, 48000Hz
http-1080p                                          mp4 1920x1080  25  |       https  | unknown           unknown
dash-akfire_interconnect_quic_sep-video-585671127   mp4 1920x1080  25  | 4692k dash   | avc1.640028 4692k                        DASH video, mp4_dash
dash-fastly_skyfire_sep-video-585671127             mp4 1920x1080  25  | 4692k dash   | avc1.640028 4692k                        DASH video, mp4_dash
hls-akfire_interconnect_quic_sep-4762               mp4 1920x1080  25  | 4762k m3u8_n | avc1.640028 4762k
hls-fastly_skyfire_sep-4762                         mp4 1920x1080  25  | 4762k m3u8_n | avc1.640028 4762k
hls-akfire_interconnect_quic-4762                   mp4 1920x1080  25  | 4762k m3u8_n | avc1.640028 4762k mp4a.40.2   0k
hls-fastly_skyfire-4762                             mp4 1920x1080  25  | 4762k m3u8_n | avc1.640028 4762k mp4a.40.2   0k
dash-akfire_interconnect_quic-video-585671127       mp4 1920x1080  25  | 4950k dash   | avc1.640028 4950k mp4a.40.2   0k 48000Hz DASH video, mp4_dash, 48000Hz
dash-fastly_skyfire-video-585671127                 mp4 1920x1080  25  | 4950k dash   | avc1.640028 4950k mp4a.40.2   0k 48000Hz DASH video, mp4_dash, 48000Hz
```

**Comment by HumbleSpirit** [comment]
Yes, this is working. But why is not working a shorter link?

**Comment by pukkandan** [comment]
> Yes, this is working. But why is not working a shorter link?
😕 The link doesnt work, so extraction fails
