### ISSUE TITLE
[Site support request] PeerTube instance greatview.video

### ISSUE THREAD

**Issue by tacohitbox** [yt-dlp/yt-dlp#4791]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Any

### Example URLs

Single video(s):
- https://greatview.video/videos/watch/5dd61076-52c9-41f5-8a7b-27027b068b62
- https://greatview.video/videos/watch/7012e7d0-259d-4a4b-bc54-a269f7bec875

Channel: 
- https://greatview.video/video-channels/joe_channel/videos
- https://greatview.video/accounts/michael/videos

### Provide a description that is worded well enough to be understood

Yet another Peertube instance I'd love to see supported. This is hosted by cartoonist UnkleJoe of YouTube fame.

Maybe `yt-dlp` should have something in it's generic detector to see if it's a video/channel page from Peertube?

I don't know what else I can add to make this description better, I'm sorry.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://greatview.video/video-channels/joe_channel/videos']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0]
[debug] Python 3.10.6 (CPython 64bit) - Linux-5.19.4-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [generic] Extracting URL: https://greatview.video/video-channels/joe_channel/videos
[generic] videos: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] videos: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://greatview.video/video-channels/joe_channel/videos
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1442, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3077, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://greatview.video/video-channels/joe_channel/videos
```

**Comment by pukkandan** [comment]
> Maybe yt-dlp should have something in it's generic detector to see if it's a video/channel page from Peertube?

#1791

**Comment by gamer191** [comment]
greatview.video is already included in yt-dlp's list of Peertube instances. How odd
https://github.com/yt-dlp/yt-dlp/blob/224b5a35f7f17fec5639608d31074b8048369385/yt_dlp/extractor/peertube.py#L57

**Comment by gamer191** [comment]
Does it work if you remove `/videos` from the end of the URL? (I'm too lazy to check myself)

**Comment by gamer191** [comment]
> #1791 fully resolves this issue

Nice :)
Looking at that PR, I suspect (though I'm too lazy to test it) that passing `--ies peertube.*,generic` wouldn't be necessary for that specific url

**Comment by tacohitbox** [comment]
> Does it work if you remove `/videos` from the end of the URL? (I'm too lazy to check myself)
> 
> Please don't close this issue if my workaround works, but let me know whether it does
Nah it doesn't, I assume this will be fixed with said PR.

```
[debug] Command-line config: ['-vU', 'https://greatview.video/video-channels/joe_channel']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19.1 [48c88e088]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.6 (CPython 64bit) - Linux-5.19.4-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1663 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19.1
yt-dlp is up to date (2022.08.19.1)
[debug] [generic] Extracting URL: https://greatview.video/video-channels/joe_channel
[generic] joe_channel: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] joe_channel: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://greatview.video/video-channels/joe_channel
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1452, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1528, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://greatview.video/video-channels/joe_channel
```

**Comment by Lesmiscore** [comment]
It's not merged yet~~, and started to stall again~~

**Comment by bashonly** [comment]
closing in favor of #16204
