### ISSUE TITLE
[Redgifs] Stopped working, gives HTTP Error 403: Forbidden 

### ISSUE THREAD

**Issue by werid** [yt-dlp/yt-dlp#4805]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Earth

### Provide a description that is worded well enough to be understood

Redgifs is giving `HTTP Error 403: Forbidden`, started recently. 

Playing in the browser, I see it uses thumbs4.redgifs.com (+ some query strings)

https://thumbs4.redgifs.com/IllFatDarwinsfox.mp4?expires=1661967000&signature=38ad19e81038ae4cdae01999001cbee43061ccced3dc2bdfd62b97fb1ea74050&for=[REDACTED-IP]#t=5.483452

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.redgifs.com/watch/illfatdarwinsfox']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (zip)
[debug] Python 3.8.13 (CPython 64bit) - FreeBSD-13.0-RELEASE-p11-amd64-64bit-ELF (libc 7)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [RedGifs] Extracting URL: https://www.redgifs.com/watch/illfatdarwinsfox
[RedGifs] illfatdarwinsfox: Downloading video info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] illfatdarwinsfox: Downloading 1 format(s): hd
[debug] Invoking http downloader on "https://thumbs2.redgifs.com/IllFatDarwinsfox.mp4"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/weird/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3170, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/weird/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2894, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/weird/bin/yt-dlp/yt_dlp/downloader/common.py", line 442, in download
    ret = self.real_download(filename, info_dict)
  File "/home/weird/bin/yt-dlp/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/home/weird/bin/yt-dlp/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/weird/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3648, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by eladkarako** [comment]
[sfw] https://www.redgifs.com/ifr/triangularwoodenafricanaugurbuzzard

the head of the document gives all the resolutions in a meta tags

```txt
<meta property="og:video" content="https://thumbs4.redgifs.com/TriangularWoodenAfricanaugurbuzzard.mp4?expires=1661986800&amp;signature=96bea2a7c6304b7a508839d63ef3802e6859ec06bc4e7fcce462ffee096cb782&amp;for=79.176.90.160">
<meta property="og:video:type" content="video/mp4">
<meta property="og:video:width" content="608">
<meta property="og:video:height" content="1080">
<meta property="og:video:iframe" content="https://www.redgifs.com/ifr/triangularwoodenafricanaugurbuzzard">
<meta property="og:video:duration" content="60">
<meta property="og:video" content="https://thumbs4.redgifs.com/TriangularWoodenAfricanaugurbuzzard-mobile.mp4?expires=1661986800&amp;signature=25b69cf4276b22fdb13f632bcc11b38491d35899de315ea1f71ae3156c82b7d2&amp;for=79.176.90.160">
<meta property="og:video:type" content="video/mp4">
<meta property="og:video:width" content="270">
<meta property="og:video:height" content="480">
<meta property="og:video:iframe" content="https://www.redgifs.com/ifr/triangularwoodenafricanaugurbuzzard">
<meta property="og:video:duration" content="60">
```

which have `&` escaped (as it should) to `&amp;`,  
and the request is not unescaping it.

log + network traffic attached (..see request url)

```txt

D:\DOS\yt-dlp_kit>call "D:\DOS\YT-DLP~2\resources\yt-dlp_win\yt-dlp.exe" "https://www.redgifs.com/ifr/triangularwoodenafricanaugurbuzzard" --ignore-config --config-location "D:\DOS\YT-DLP~2\yt-dlp_conf_base.conf" --merge-output-format mkv --remux-video mkv 
[debug] Command-line config: ['https://www.redgifs.com/ifr/triangularwoodenafricanaugurbuzzard', '--ignore-config', '--config-location', 'D:\\DOS\\YT-DLP~2\\yt-dlp_conf_base.conf', '--merge-output-format', 'mkv', '--remux-video', 'mkv']
[debug] | Config "D:\DOS\YT-DLP~2\yt-dlp_conf_base.conf": ['--force-ipv4', '--windows-filenames', '--no-cache-dir', '--sleep-requests', '1', '--sleep-interval', '1', '--sleep-subtitles', '2', '--max-sleep-interval', '3', '--console-title', '--concurrent-fragments', '3', '--skip-unavailable-fragments', '--embed-subs', '--write-subs', '--write-auto-subs', '--sub-langs', 'en,iw,iw-en,ja,ko', '--embed-metadata', '--embed-chapters', '--embed-thumbnail', '--convert-thumbnails', 'jpg', '--sponsorblock-mark', 'intro,outro,poi_highlight', '--sponsorblock-remove', 'sponsor,selfpromo,interaction,filler,music_offtopic', '--sponsorblock-api', 'https://sponsor.ajay.app', '--add-header', 'DNT:1', '--add-header', 'Upgrade-Insecure-Requests:0', '--prefer-insecure', '--no-check-certificates', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4599.0 Safari/537.36', '--no-abort-on-error', '--skip-unavailable-fragments', '--no-update', '--verbose', '--print-traffic']
[debug] Encodings: locale cp1255, fs utf-8, pref cp1255, out cp1255 (No ANSI), error cp1255 (No ANSI), screen cp1255 (No ANSI)
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_dir)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107894-gadc38738cb-2022-08-25-nonfree (fdk,setts), ffprobe N-107894-gadc38738cb-2022-08-25-nonfree, phantomjs 2.5.0, rtmpdump 2.3
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.redgifs.com/ifr/triangularwoodenafricanaugurbuzzard
[generic] triangularwoodenafricanaugurbuzzard: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] triangularwoodenafricanaugurbuzzard: Extracting information
send: b'GET /ifr/triangularwoodenafricanaugurbuzzard HTTP/1.1\r\nHost: www.redgifs.com\r\nAccept-Encoding: *\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4599.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nDnt: 1\r\nUpgrade-Insecure-Requests: 0\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 31 Aug 2022 21:21:17 GMT
header: Content-Type: text/html; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: close
header: Expires: Wed, 31 Aug 2022 21:29:19 GMT
header: Cache-Control: max-age=600
header: Last-Modified: Wed, 31 Aug 2022 21:19:19 GMT
header: CF-Cache-Status: HIT
header: Age: 118
header: Vary: Accept-Encoding
header: Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
header: X-Content-Type-Options: nosniff
header: Server: cloudflare
header: CF-RAY: 7438d0a37d8fad6d-TLV
header: alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a JSON LD
[debug] [generic] Extracting URL: https://thumbs4.redgifs.com/TriangularWoodenAfricanaugurbuzzard-mobile.mp4?expires=1661986800&amp;signature=25b69cf4276b22fdb13f632bcc11b38491d35899de315ea1f71ae3156c82b7d2&amp;for=79.176.90.160#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22triangularwoodenafricanaugurbuzzard%22%2C+%22to_generic%22%3A+true%7D
[generic] Sleeping 1.0 seconds ...
[generic] triangularwoodenafricanaugurbuzzard: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 2641, in _real_extract
  File "yt_dlp\extractor\common.py", line 817, in _request_webpage

  File "yt_dlp\extractor\common.py", line 799, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3648, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

send: b'GET /TriangularWoodenAfricanaugurbuzzard-mobile.mp4?expires=1661986800&amp;signature=25b69cf4276b22fdb13f632bcc11b38491d35899de315ea1f71ae3156c82b7d2&amp;for=79.176.90.160 HTTP/1.1\r\nHost: thumbs4.redgifs.com\r\nAccept-Encoding: *\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4599.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nDnt: 1\r\nUpgrade-Insecure-Requests: 0\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Date: Wed, 31 Aug 2022 21:21:18 GMT
header: Content-Type: text/plain;charset=UTF-8
header: Content-Length: 44
header: Connection: close
header: Cache-Control: no-store
header: Vary: Accept-Encoding
header: Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
header: X-Content-Type-Options: nosniff
header: Server: cloudflare
header: CF-RAY: 7438d0ad2b6cad85-TLV
header: alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

D:\DOS\yt-dlp_kit>set "EXIT_CODE=1" 
```

**Comment by jimmy-1000** [comment]
I saw that today.  **yt-dlp** opens the video with https://thumbs2 instead https://thumbs4. That's the problem. I don't know why.

**Comment by eladkarako** [comment]
can't replicate error 403, but in my case it preforms request with `&amp;` instead of `&`  
which gave error 400.  
sources are extracted from the raw html, `og:video`, which had `&amp;`.

**Comment by jimmy-1000** [comment]
I saw that today. Sadly RedGifs did some changes and yt-dlp doesn't work.

**Comment by pukkandan** [comment]
@chio0hai may be interested

**Comment by chio0hai** [comment]
We use their API (https://api.redgifs.com/docs/index.html) for URLs of the videos, which currently returns URLs in thumbs2.redgifs.com that are broken at the moment.
e.g. The api request, https://api.redgifs.com/v2/gifs/illfatdarwinsfox, returns the following URLs for HD and SD videos:
https://thumbs2.redgifs.com/IllFatDarwinsfox.mp4
https://thumbs2.redgifs.com/IllFatDarwinsfox-mobile.mp4

The html page itself returns URLs in the og:video meta values in thumbs4.redgifs.com, and contain extra parameters.
https://thumbs4.redgifs.com/PrivateVirtualAcornweevil.mp4?expires=xxx&signature=yyy&for=1.2.3.4
https://thumbs4.redgifs.com/PrivateVirtualAcornweevil-mobile.mp4?expires=xxx&signature=yyy&for=1.2.3.4

Interestingly, they have another server, thumbs3.redgifs.com, which appears to work without the extra parameters.

Maybe we could replace "thumbs2.redgifs.com" with "thumbs3.redgifs.com" as a workaround for now?

```
--- a/yt_dlp/extractor/redgifs.py
+++ b/yt_dlp/extractor/redgifs.py
@@ -30,6 +30,7 @@ def _parse_gif_data(self, gif_data):
             video_url = gif_data['urls'].get(format_id)
             if not video_url:
                 continue
+            video_url = video_url.replace('thumbs2.redgifs.com', 'thumbs3.redgifs.com')
             height = min(orig_height, height or orig_height)
             formats.append({
                 'url': video_url,
```

**Comment by jhwgh1968** [comment]
I have found a way to make their API work. Forgive me for being cryptic, but I worry they might "fix" it once again.

After some reading and analysis, it turns out their main website uses an OAuth bearer token on the API, i.e. one which is "deemed good" by simply having it. How long it lasts or where it comes from is not clear, so I don't want to paste it in here lest they change it. But it appears to have a fairly long life.

Given this, it is possible for anyone to download videos again by doing the following:

1. View a video on their website with developer tools open.
2. Watch for the request to api.redgifs.com, and notice the `authorizaton` header. This contains the bearer token.
3. Add the following patch, including the token where I put `<...>`
4. Convince Cloudflare you are not trying to imitate a browser (caused by the default user agent I believe)

```
diff --git a/yt_dlp/extractor/redgifs.py b/yt_dlp/extractor/redgifs.py
index e3712a1d6..b5bb7ffc6 100644
--- a/yt_dlp/extractor/redgifs.py
+++ b/yt_dlp/extractor/redgifs.py
@@ -59,6 +59,11 @@ def _parse_gif_data(self, gif_data):
 
     def _call_api(self, ep, video_id, *args, **kwargs):
+        headers = {'authorization': 'Bearer <...>',
+                   'x-customheader': f'https://www.redgifs.com/watch/{video_id}',
+                   'referer': 'https://www.redgifs.com/',
+                   'origin': 'https://www.redgifs.com',
+                   'content-type': 'application/json'}
         data = self._download_json(
-            f'https://api.redgifs.com/v2/{ep}', video_id, *args, **kwargs)
+            f'https://api.redgifs.com/v2/{ep}', video_id, headers=headers, *args, **kwargs)
         if 'error' in data:
             raise ExtractorError(f'RedGifs said: {data["error"]}', expected=True, video_id=video_id)
```

Good luck!
