### ISSUE TITLE
[bilibili.tv] ERROR: Unsupported URL (if there are parameters)

### ISSUE THREAD

**Issue by jazz1611** [yt-dlp/yt-dlp#4825]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Hello,

If url have parameter "?bstar_from=bstar-web.pgc-video-detail.series.0" or "?bstar_from=bstar-web.pgc-video-detail.related-recommend.all", yt-dlp can't download it.

Not work: https://www.bilibili.tv/en/play/34580?bstar_from=bstar-web.homepage.anime.all
Work: https://www.bilibili.tv/en/play/34580

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\admin>youtube-dl -Uv "https://www.bilibili.tv/en/play/34580?bstar_from=bstar-web.homepage.anime.all"
[debug] Command-line config: ['-Uv', 'https://www.bilibili.tv/en/play/34580?bstar_from=bstar-web.homepage.anime.all']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1-full_build-www.gyan.dev (setts), ffprobe 5.1-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://www.bilibili.tv/en/play/34580?bstar_from=bstar-web.homepage.anime.all
[generic] 34580?bstar_from=bstar-web.homepage.anime: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 34580?bstar_from=bstar-web.homepage.anime: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.bilibili.tv/en/play/34580?bstar_from=bstar-web.homepage.anime.all
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1535, in __extract_info
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\generic.py", line 3078, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.bilibili.tv/en/play/34580?bstar_from=bstar-web.homepage.anime.all
```

**Comment by HobbyistDev** [comment]
I think the problem is in this line:
https://github.com/yt-dlp/yt-dlp/blob/7657ec7ed6318dd66dd72cc100ba7bc5b911366e/yt_dlp/extractor/bilibili.py#L978
Removing `$` at the end of `_VALID_URL` should be work. However, i didn't test this

**Comment by pukkandan** [comment]
I cannot test due to geo-restriction, but this should work:
```diff
diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
index 59f5791d1..7e63dad0f 100644
--- a/yt_dlp/extractor/bilibili.py
+++ b/yt_dlp/extractor/bilibili.py
@@ -975,7 +975,7 @@ def _real_extract(self, url):


 class BiliIntlSeriesIE(BiliIntlBaseIE):
-    _VALID_URL = r'https?://(?:www\.)?bili(?:bili\.tv|intl\.com)/(?:[a-z]{2}/)?play/(?P<id>\d+)$'
+    _VALID_URL = r'https?://(?:www\.)?bili(?:bili\.tv|intl\.com)/(?:[a-z]{2}/)?play/(?P<id>\d+)/?(?:[?#]|$)'
     _TESTS = [{
         'url': 'https://www.bilibili.tv/en/play/34613',
         'playlist_mincount': 15,
```

**Comment by HobbyistDev** [comment]
Can confirm it works with your patch:
```shell
..\yt-dlp>python -m yt_dlp -v "https://www.bilibili.tv/en/play/34580?bstar_from=bstar-web.homepage.anime.all" --ignore-config -I 1
[debug] Command-line config: ['-v', 'https://www.bilibili.tv/en/play/34580?bstar_from=bstar-web.homepage.anime.all', '--ignore-config', '-I', '1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: b8718708a
[debug] Python 3.10.6 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1-full_build-www.gyan.dev (setts), ffprobe 5.1-full_build-www.gyan.dev
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1671 extractors
[debug] [BiliIntlSeries] Extracting URL: https://www.bilibili.tv/en/play/34580?bstar_from=bstar-web.homepage.anime.all
[BiliIntlSeries] 34580: Downloading JSON metadata
[download] Downloading playlist: Demon Slayer: Kimetsu no Yaiba
[BiliIntlSeries] 34580: Downloading JSON metadata
[BiliIntlSeries] 340313: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 340313: Downloading subtitles list
[BiliIntlSeries] 340313: Downloading subtitles for English
[BiliIntlSeries] 340313: Downloading subtitles for ภาษาไทย
[BiliIntlSeries] 340313: Downloading subtitles for Tiếng Việt
[BiliIntlSeries] 340313: Downloading subtitles for Bahasa Indonesia
[BiliIntlSeries] 340313: Downloading subtitles for Bahasa Melayu
[BiliIntlSeries] 340313: Downloading subtitles for 中文（简体）
[BiliIntlSeries] 340313: Downloading subtitles for 中文（繁体）
[BiliIntlSeries] Playlist Demon Slayer: Kimetsu no Yaiba: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 340313: Downloading 1 format(s): 6+2
[debug] Invoking http downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/n8/uj/n220706a23nlf0bqmh76vnr681j5ujn8-1-231210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1662541363&gen=playurlv2&os=akam&oi=2107831345&trid=8bdb311a233b4145b8555ac258e1c81ai&mid=0&platform=pc&upsig=83e495a7441bd41c80dc5141959c31ae&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1662541363~hmac=816c62cfc0599d3dbb504668c1cb3d67e5040bd94a1f59b3143b7700b15780ce&bvc=vod&nettype=0&orderid=0,1&logo=00000000"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: E1 - Cruelty [340313].f6.mp4
[download]  28.6% of 73.72MiB at    1.03MiB/s ETA 00:50
ERROR: Interrupted by user
```
