### ISSUE TITLE
[prosiebensat1] SAT.1 Nachrichten broken

### ISSUE THREAD

**Issue by vogler** [yt-dlp/yt-dlp#4828]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

The website and URL for Sat 1 news videos changed.
On the overview site https://www.sat1.de/serien/nachrichten there's the current video, but the clip id now can't be extracted.
For a specific video, the subdomain changed such that the [prosiebensat1] extractor is not used anymore.

New URL is https://video.sat1.de/serien/sat1-nachrichten/videos/abendnachrichten-02092022
Old URL would have been https://www.sat1.de/news/video/abendnachrichten-02-09-2022-clip

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.sat1.de/serien/nachrichten']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.5.1-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [prosiebensat1] Extracting URL: https://www.sat1.de/serien/nachrichten
[prosiebensat1] serien/nachrichten: Downloading webpage
ERROR: [prosiebensat1] serien/nachrichten: Unable to extract clip id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/extractor/prosiebensat1.py", line 492, in _real_extract
    return self._extract_clip(url, webpage)
  File "/opt/homebrew/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/extractor/prosiebensat1.py", line 432, in _extract_clip
    clip_id = self._html_search_regex(
  File "/opt/homebrew/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1258, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/opt/homebrew/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1222, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

---

[debug] Command-line config: ['-vU', 'https://video.sat1.de/serien/sat1-nachrichten/videos/abendnachrichten-02092022']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.5.1-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://video.sat1.de/serien/sat1-nachrichten/videos/abendnachrichten-02092022
[generic] abendnachrichten-02092022: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] abendnachrichten-02092022: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://video.sat1.de/serien/sat1-nachrichten/videos/abendnachrichten-02092022
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://video.sat1.de/serien/sat1-nachrichten/videos/abendnachrichten-02092022
```

**Comment by vogler** [comment]
Here are my attempts to debug:

https://github.com/yt-dlp/yt-dlp/blob/22df97f9c5ef5aaf6d4451d1c632dee4dc325c5f/yt_dlp/extractor/prosiebensat1.py#L176

```diff
                             (?: 
-                                  prosieben(?:maxx)?|sixx|sat1(?:gold)?|kabeleins(?:doku)?|the-voice-of-germany|advopedia 
+                                  prosieben(?:maxx)?|sixx|(?:video\.)?sat1(?:gold)?|kabeleins(?:doku)?|the-voice-of-germany|advopedia 
                             )\.(?:de|at|ch)| 
```
This change (and adjusting `lazy_extractors.py`) makes it use the right extractor again but fail on the `clip id`:

```console
$ yt-dlp https://video.sat1.de/serien/sat1-nachrichten/videos/abendnachrichten-10092022
[prosiebensat1] serien/sat1-nachrichten/videos/abendnachrichten-10092022: Downloading webpage
ERROR: [prosiebensat1] serien/sat1-nachrichten/videos/abendnachrichten-10092022: Unable to extract clip id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

https://github.com/ytdl-org/youtube-dl/pull/29349 did not help.

I don't know what the clip id is supposed to be and why it is needed - in Chrome devtools I could not find anything similar to what the listed regexes match.

https://github.com/yt-dlp/yt-dlp/blob/22df97f9c5ef5aaf6d4451d1c632dee4dc325c5f/yt_dlp/extractor/prosiebensat1.py#L386-L394

To continue I just used a suffix of the URL by adding `r'<link[^>]+rel="canonical"[^>]+videos/(.+?)"',` to the list.

Then it complained about DRM:

```
[prosiebensat1] abendnachrichten-10092022: Downloading videos JSON
ERROR: [prosiebensat1] abendnachrichten-10092022: This video is DRM protected
```

Then I tried `--allow-unplayable-formats`:

```console
$ yt-dlp https://video.sat1.de/serien/sat1-nachrichten/videos/abendnachrichten-10092022 --allow-unplayable-formats
WARNING: You have asked for UNPLAYABLE formats to be listed/downloaded. This is a developer option intended for debugging.
         If you experience any issues while using this option, DO NOT open a bug report
[prosiebensat1] serien/sat1-nachrichten/videos/abendnachrichten-10092022: Downloading webpage
abendnachrichten-10092022
[prosiebensat1] abendnachrichten-10092022: Downloading videos JSON
[prosiebensat1] abendnachrichten-10092022: Downloading protocols JSON
WARNING: [prosiebensat1] Unable to download JSON metadata: HTTP Error 404: Not Found
[prosiebensat1] abendnachrichten-10092022: Downloading sources JSON
ERROR: [prosiebensat1] abendnachrichten-10092022: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

I noticed that you do actually need to be signed in to watch the video and tried `--cookies-from-browser` but still got the DRM message:

```console
$ yt-dlp https://video.sat1.de/serien/sat1-nachrichten/videos/abendnachrichten-10092022 --cookies-from-browser chrome
[Cookies] Extracting cookies from chrome
[Cookies] Extracted 3448 cookies from chrome
[prosiebensat1] serien/sat1-nachrichten/videos/abendnachrichten-10092022: Downloading webpage
abendnachrichten-10092022
[prosiebensat1] abendnachrichten-10092022: Downloading videos JSON
ERROR: [prosiebensat1] abendnachrichten-10092022: This video is DRM protected
```

`--cookies-from-browser` works fine for me for downloading my YouTube Watch Later playlist, so I guess something about the DRM handling for that extractor needs to be changed as well.

**Comment by pukkandan** [comment]
Are you sure the video is actually DRM-less? The pinned "known issues" has instructions for checking

**Comment by vogler** [comment]
Just checked in Firefox with Widevine disabled - still works.

**Comment by theDispare** [comment]
@vogler Thank you for trying to solve the issue. But the URL changed also for the other pages like prosiebenmaxx or prosieben.

**Comment by vogler** [comment]
@theDispare I just looked at my example w.l.o.g. - the needed changes likely apply for all of those URLs.

**Comment by dirkf** [comment]
>Then it complained about DRM:

This seems to mean that you passed an invalid clip ID.

The clip ID patterns are all numeric, but the site (and its siblings, eg puls4) now use an ID like `v_2jqaga0ou21d` and a different metadata API is needed.
