### ISSUE TITLE
ERROR: 'bool' object has no attribute 'startswith' 

### ISSUE THREAD

**Issue by jarz76** [yt-dlp/yt-dlp#4842]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Last week I was still able to download videos from vidio.com, but not today, it always has an error.

I try to re-download the video that I had already downloaded a few weeks ago to make sure, and the same problem occurred.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies', 'W:\\vidio.txt', '-F', 'https://www.vidio.com/watch/7095853-ep-04-sketch-book', '-vU']
[debug] User config "C:\Users\ASF\AppData\Roaming\yt-dlp\config.txt": ['-o', 'J:\\Downloads\\Video\\Media\\YT-DL\\%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-06-git-03d81a044a-full_build-www.gyan.dev (setts), ffprobe 2022-07-06-git-03d81a044a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[Vidio] Downloading JSON metadata
[debug] [Vidio] Extracting URL: https://www.vidio.com/watch/7095853-ep-04-sketch-book
[Vidio] ep-04-sketch-book: Downloading webpage
[Vidio] ep-04-sketch-book: Downloading premier API JSON
[Vidio] ep-04-sketch-book: Downloading m3u8 information
ERROR: 'bool' object has no attribute 'startswith'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1535, in __extract_info
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\vidio.py", line 145, in _real_extract
  File "yt_dlp\extractor\common.py", line 2165, in _extract_m3u8_formats_and_subtitles
  File "yt_dlp\extractor\common.py", line 864, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 803, in _request_webpage
  File "yt_dlp\extractor\common.py", line 769, in _create_request
  File "yt_dlp\utils.py", line 757, in sanitized_Request
  File "yt_dlp\utils.py", line 729, in sanitize_url
AttributeError: 'bool' object has no attribute 'startswith'
```

**Comment by dirkf** [comment]
Somewhere inside the chain of processing below `sanitized_Request()`, the url is being set to `False` (probably), which crashes `sanitize_url()` when it is called in that chain.

Instead of passing `None` through it could return `None` for any non-string input.
