### ISSUE TITLE
Do not attempt to get a YT video's comments even if --get-comments is passed if YT doesn't provide comment continuation token

### ISSUE THREAD

**Issue by llacb47** [yt-dlp/yt-dlp#485]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
yt-dlp "https://www.youtube.com/watch?v=j8oHN6Hi6bc" -v --ignore-config --write-comments --no-check-certificate --proxy "http://localhost:8888/"
[debug] Command-line config: ['https://www.youtube.com/watch?v=j8oHN6Hi6bc', '-v', '--ignore-config', '--write-comments', '--no-check-certificate', '--proxy', 'http://localhost:8888/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07
[debug] Python version 3.9.1 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg n4.3.2-163-g6c414cf8f7, ffprobe n4.3.2-163-g6c414cf8f7
[debug] Proxy map: {'http': 'http://localhost:8888/', 'https': 'http://localhost:8888/'}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=j8oHN6Hi6bc
[youtube] j8oHN6Hi6bc: Downloading webpage
[youtube] j8oHN6Hi6bc: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] j8oHN6Hi6bc: Downloading 1 format(s): 244+140
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "c:\users\abc\scoop\apps\python\current\lib\site-packages\yt_dlp\YoutubeDL.py", line 1142, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\abc\scoop\apps\python\current\lib\site-packages\yt_dlp\YoutubeDL.py", line 1178, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\abc\scoop\apps\python\current\lib\site-packages\yt_dlp\YoutubeDL.py", line 1219, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "c:\users\abc\scoop\apps\python\current\lib\site-packages\yt_dlp\YoutubeDL.py", line 2198, in process_video_result
    self.process_info(new_info)
  File "c:\users\abc\scoop\apps\python\current\lib\site-packages\yt_dlp\YoutubeDL.py", line 2358, in process_info
    self.post_extract(info_dict)
  File "c:\users\abc\scoop\apps\python\current\lib\site-packages\yt_dlp\YoutubeDL.py", line 2860, in post_extract
    actual_post_extract(info_dict or {})
  File "c:\users\abc\scoop\apps\python\current\lib\site-packages\yt_dlp\YoutubeDL.py", line 2852, in actual_post_extract
    extra = post_extractor().items()
  File "c:\users\abc\scoop\apps\python\current\lib\site-packages\yt_dlp\extractor\youtube.py", line 2927, in <lambda>
    info['__post_extractor'] = lambda: self._extract_comments(ytcfg, video_id, contents, webpage, xsrf_token)
  File "c:\users\abc\scoop\apps\python\current\lib\site-packages\yt_dlp\extractor\youtube.py", line 2145, in _extract_comments
    for entry in contents:
TypeError: 'NoneType' object is not iterable
```

## Description

Reporting a small bug with the youtube extractor

For a few old youtube videos, the channel the video is uploaded to is unavailable. Somehow this causes youtube not to serve the comment continuation token at all. Therefore, if a user were to download one of these broken videos with yt-dlp with the --get-comments flag, yt-dlp throws a TypeError instead of catching the error and continuing. 

Some videos where youtube doesn't serve a comment continuation token:
```
https://www.youtube.com/watch?v=wWhLVn8shzo
https://www.youtube.com/watch?v=D0sbmx7PupM
https://www.youtube.com/watch?v=j8oHN6Hi6bc
https://www.youtube.com/watch?v=SAcdZ7I87gk
https://www.youtube.com/watch?v=Rw8UGdWSwqo
https://www.youtube.com/watch?v=B0TfFjLEbHw
```

ping @colethedj as it may be of interest

**Comment by colethedj** [comment]
Thanks for this, appears to be a case we missed. #466 rewrite appears to be affected by this too.
