### ISSUE TITLE
youtube    urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by 786259135** [yt-dlp/yt-dlp#4863]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

https://www.youtube.com/watch?v=6FQhi7hq50s
YouTube Download 404 error

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=6FQhi7hq50s']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_dir)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=6FQhi7hq50s
[youtube] 6FQhi7hq50s: Downloading webpage
[youtube] 6FQhi7hq50s: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 6FQhi7hq50s: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr1---sn-i3b7knsl.googlevideo.com/videoplayback?expire=1662588722&ei=0sIYY8O8KI6GgAPzzrTIBA&ip=119.28.87.187&id=o-AKHC9fSuIJhe_4d5VL0llSeL0WXI212BCE8MXPnR8L9B&itag=22&source=youtube&requiressl=yes&mh=0p&mm=31%2C26&mn=sn-i3b7knsl%2Csn-un57sne7&ms=au%2Conr&mv=m&mvi=1&pl=23&initcwndbps=617500&spc=lT-KhjeEp3pExD8EhwQkwq2X7pF7Lhc&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=387.378&lmt=1662445220444511&mt=1662566745&fvip=4&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgaDW1wSZs2Zd0nko7pfS86hFe5EySXvWaRM9jzoqisusCIQC35YOcPkcPL2pPP-OkdQlQU2o2kqsGxeSrNQzaqI0WYQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgWIAs4_nx8CDAsJCIDsKVTIF-xF63g4hPnXPX7jaHQfQCIH74LxHuwO_cBO05aD9HsKgdElmb8ngOw7DLcnHRC3AO"
[download] Resuming download at byte 370290
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3171, in process_info
  File "yt_dlp\YoutubeDL.py", line 2895, in dl
  File "yt_dlp\downloader\common.py", line 443, in download
  File "yt_dlp\downloader\http.py", line 371, in real_download
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3656, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
See pinned issues
