### ISSUE TITLE
Timcast.com Members Content

### ISSUE THREAD

**Issue by feerlessleadr** [yt-dlp/yt-dlp#4866]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://timcast.com/members-area/section/timcast-irl/
https://timcast.com/members-area/mike-glover-member-podcast-monkeypox-is-an-std-according-to-new-report-families-are-eroding-crew-talks-us-collapse/
https://timcast.com/members-area/section/cast-castle/
https://timcast.com/members-area/section/green-room/
https://timcast.com/members-area/section/tales-from-the-inverted-world/

### Provide a description that is worded well enough to be understood

I am requesting support for timcast.com's members area (I have a legitamate account and can share creds if needed), and while the general extractor can download individual videos from the members area (ex. the 2nd link from above, which is just a rumble.com video), when I provide yt-dlp the link to all videos on the site, it is not able to parse out each video for download, therefore limiting my use in s script to auto grab new videos. 

See next section below for the verbose of the error, as well as the following paste of a successful individual video download.

https://paste.ubuntu.com/p/MP6ypGPHKT/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
kevin@ubuntu-server:~/scripts/yt-dlp/timcast$ ./ytdl-timcast-members
[debug] Command-line config: ['-vU', '--config-location', '/home/kevin/scripts/yt-dlp/timcast/config-timcast.txt', '-o', '/home/kevin/scripts/yt-dlp/temp-downloads/tmp-timcast/%(upload_date)s - %(title)s.%(ext)s', 'https://timcast.com/members-area/section/timcast-irl/']
[debug] | Config "/home/kevin/scripts/yt-dlp/timcast/config-timcast.txt": ['-S', 'res,codec:vp9.2:opus,br,fps', '--merge-output-format', 'mkv', '--extractor-args', 'youtube:player_client=android', '--write-info-json', '--write-thumbnail', '--convert-thumbnails', 'jpg', '--write-sub', '--convert-subs', 'srt', '--compat-options', 'no-live-chat', '--add-metadata', '--embed-subs', '--embed-thumbnail', '--sponsorblock-remove', 'all', '--ignore-errors', '--proxy', '', '--continue', '--no-overwrites', '--download-archive', '/home/kevin/scripts/yt-dlp/timcast/ytdl-timcast-archive.txt', '--no-check-certificate']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
[debug] Compatibility options: no-live-chat
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-125-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: certifi-2019.11.28, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Loading archive file '/home/kevin/scripts/yt-dlp/timcast/ytdl-timcast-archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://timcast.com/members-area/section/timcast-irl/
[generic] timcast-irl: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] timcast-irl: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://timcast.com/members-area/section/timcast-irl/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://timcast.com/members-area/section/timcast-irl/

no videos downloaded
```

**Comment by pukkandan** [comment]
To clarify, is the request only for a playlist extractor? Or do you need some improvements to the video download?

**Comment by feerlessleadr** [comment]
Apologies, yes, I'm requesting a playlist extractor.

**Comment by coletdjnz** [comment]
For devs: worth checking if the channels, trending and other list pages have similar extraction (from the ui it looks pretty similar). might be able to generalize it all.
