### ISSUE TITLE
[REQ] cloud.mail.ru

### ISSUE THREAD

**Issue by jazz1611** [yt-dlp/yt-dlp#4888]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://cloud.mail.ru/public/kFtx/E2t21RwxD

### Provide a description that is worded well enough to be understood

hello @pukkandan , can you support site cloud.mail.ru to yt-dlp? thank you

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\admin>yt-dlp -Uv "https://cloud.mail.ru/public/kFtx/E2t21RwxD"
[debug] Command-line config: ['-Uv', 'https://cloud.mail.ru/public/kFtx/E2t21RwxD']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1-full_build-www.gyan.dev (setts), ffprobe 5.1-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://cloud.mail.ru/public/kFtx/E2t21RwxD
[generic] E2t21RwxD: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] E2t21RwxD: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://cloud.mail.ru/public/kFtx/E2t21RwxD
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1535, in __extract_info
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\generic.py", line 3078, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://cloud.mail.ru/public/kFtx/E2t21RwxD
```

**Comment by slavakurilyak** [comment]
+1 for **cloud.mail.ru** support

**Comment by yuriymacdev** [comment]
I'll add, why this is useful:

Normally this `cloud.mail.ru` service allows downloading videos as files using a download button on the website. The problem is that the file is downloaded in highest quality, as it was uploaded. On the other hand, when viewed directly from the `cloud.mail.ru` website via streaming (I suppose it uses DASH, but haven't checked deeper), the user is able to pick a resolution and save on a bandwidth. If yt-dlp worked with this service, it would make downloading videos much faster and without the subsequent need to re-encode it manually via ffmpeg to a less space-consuming format.
