### ISSUE TITLE
Vimeo 403 forbidden

### ISSUE THREAD

**Issue by Sogl** [yt-dlp/yt-dlp#4904]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Provide a description that is worded well enough to be understood

I use `master.json` for download, renaming it to `master.mpd`. Error 403 on all videos.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://73vod-adaptive.akamaized.net/exp=1663022961~acl=/26b6e8c4-ebf9-4cf1-b0c3-cbe6b2473930/*~hmac=043e7272f1485b0ac4cf04fb8e7c58510e34e6af46e7b32de41363c2010433c9/26b6e8c4-ebf9-4cf1-b0c3-cbe6b2473930/sep/video/57fd8b31,95b970b6,f6c04e4c,bdaa9b16/audio/6837b89f,c49e3d29,08f3f901/master.mpd', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.9.14 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://73vod-adaptive.akamaized.net/exp=1663022961~acl=/26b6e8c4-ebf9-4cf1-b0c3-cbe6b2473930/*~hmac=043e7272f1485b0ac4cf04fb8e7c58510e34e6af46e7b32de41363c2010433c9/26b6e8c4-ebf9-4cf1-b0c3-cbe6b2473930/sep/video/57fd8b31,95b970b6,f6c04e4c,bdaa9b16/audio/6837b89f,c49e3d29,08f3f901/master.mpd
[generic] master: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] master: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] master: Downloading 1 format(s): video-bdaa9b16+audio-c49e3d29
[debug] Invoking http downloader on "https://73vod-adaptive.akamaized.net/exp=1663022961~acl=/26b6e8c4-ebf9-4cf1-b0c3-cbe6b2473930/*~hmac=043e7272f1485b0ac4cf04fb8e7c58510e34e6af46e7b32de41363c2010433c9/26b6e8c4-ebf9-4cf1-b0c3-cbe6b2473930/sep/video/57fd8b31,95b970b6,f6c04e4c,bdaa9b16/audio/6837b89f,c49e3d29,08f3f901/../../../../../parcel/video/bdaa9b16.mp4?r=dXM%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3153, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2895, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 443, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3656, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
Use the actual vimeo URL instead!

**Comment by Sogl** [comment]
Finally `yt-dlp pageURL --cookies-from-browser chrome` worked in my case.

But there is no sound in the standard macOS player, only VLC plays. Do I need to specify some parameter for the codec or something like that?

**Comment by Sogl** [comment]
today I tried with the latest version
the video is partially downloaded, it is impossible to use 🤒
