### ISSUE TITLE
[Deutsche Welle] An extractor error has occurred. (caused by KeyError('media_title'))

### ISSUE THREAD

**Issue by kiufta** [yt-dlp/yt-dlp#4944]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

I'm trying to download this Deutsche Welle Video https://www.dw.com/de/wenn-der-strom-aus-der-luft-kommt/av-63153677
with ArchLinux [youtube-dlp](https://archlinux.org/packages/community/any/yt-dlp/) (up-to-date): It fails with the `KeyError('media_title')` error.

This URL doesn't contain characters which need escaping.

The error seems to be the same like in the otherwise unrelated issue https://github.com/yt-dlp/yt-dlp/issues/2606

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[papa@main podcast]$ youtube-dl -vU https://www.dw.com/de/wenn-der-strom-aus-der-luft-kommt/av-63153677
[debug] Command-line config: ['-vU', 'https://www.dw.com/de/wenn-der-strom-aus-der-luft-kommt/av-63153677']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6]
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.19.8-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107098-g4d45f5acbd (setts), ffprobe N-107098-g4d45f5acbd, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.09.14, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [dw] Extracting URL: https://www.dw.com/de/wenn-der-strom-aus-der-luft-kommt/av-63153677
[dw] 63153677: Downloading webpage
ERROR: 63153677: An extractor error has occurred. (caused by KeyError('media_title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/dw.py", line 53, in _real_extract
    title = hidden_inputs['media_title']
KeyError: 'media_title'
```

**Comment by gamer191** [comment]
![Error 410 - The requested page has expired.](https://user-images.githubusercontent.com/83270075/190857078-d19a8fdc-64fb-43f8-8205-f7244704f57d.png)
Please provide a new example url, this one has expired (unless it's geo-blocked)

NOTE: the expired url is not what caused this issue, because yt-dlp correctly detects the 410 error

```
[debug] Command-line config: ['https://www.dw.com/de/wenn-der-strom-aus-der-luft-kommt/av-63153677', '--verbose']
[debug] User config "C:\Users\jaybu\AppData\Roaming\yt-dlp\config.txt": ['--ffmpeg-location', 'C:\\Users\\jaybu\\ffmpeg\\bin', '-P', 'C:\\Users\\jaybu\\youtube.dl', '--update', '--audio-quality', '0']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: "C:\Users\jaybu\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: "C:\Users\jaybu\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg N-106498-g854615adf2-20220405 (setts), ffprobe N-106498-g854615adf2-20220405, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [dw] Extracting URL: https://www.dw.com/de/wenn-der-strom-aus-der-luft-kommt/av-63153677
[dw] 63153677: Downloading webpage
ERROR: [dw] 63153677: Unable to download webpage: HTTP Error 410: Gone (caused by <HTTPError 410: 'Gone'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\dw.py", line 51, in _real_extract
  File "yt_dlp\extractor\common.py", line 1079, in _download_webpage
  File "yt_dlp\extractor\common.py", line 1030, in download_content
  File "yt_dlp\extractor\common.py", line 864, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 821, in _request_webpage

  File "yt_dlp\extractor\common.py", line 803, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3656, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 410: Gone
```

**Comment by pukkandan** [comment]
```
❯ yt-dlp -v https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733#spark_wn=1
[debug] Command-line config: ['--ignore-config', '-v', 'https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733#spark_wn=1']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: dab284f80
[debug] Python 3.10.7 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107787-gc469c3c3b1-20220814 (fdk,setts), ffprobe N-107787-gc469c3c3b1-20220814, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1673 extractors
[debug] [dw] Extracting URL: https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733#spark_wn=1
[dw] 63121733: Downloading webpage
ERROR: 63121733: An extractor error has occurred. (caused by KeyError('media_title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\dw.py", line 53, in _real_extract
    title = hidden_inputs['media_title']
KeyError: 'media_title'
```

**Comment by dirkf** [comment]
In yt-dlp and yt-dl, `--force-generic` captures this HTML5 source.

**Comment by Vangelis66** [comment]
> In **yt-dlp** (...), `--force-generic` captures this HTML5 source.

Indeed! 
```
yt-dlp -v -F "https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733" --force-generic => 

[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '-v', '-F', 'https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733', '--force-generic']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] ytdl-patched/yt-dlp version 2022.09.18.1919 [a1f3c39] (win32_exe)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python 3.7.9 (CPython 32bit) - Windows-Vista-6.0.6003-SP2
[debug] Checking exe version: "..\ffmpeg" -bsfs
[debug] Checking exe version: "..\ffprobe" -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1672 extractors
[debug] [generic] Extracting URL: https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733
[generic] av-63121733: Downloading webpage
WARNING: [generic] Forcing generic information extractor
[generic] av-63121733: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[html5] av-63121733: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7),vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Identified a html5 embed
[info] Available formats for av-63121733-1:
ID       EXT RESOLUTION FPS |   TBR PROTO | VCODEC        VBR ACODEC    ABR
---------------------------------------------------------------------------
hls-386  mp4 480x270     25 |  386k m3u8  | avc1.42c015  386k mp4a.40.2  0k
hls-631  mp4 512x288     25 |  631k m3u8  | avc1.4d4015  631k mp4a.40.2  0k
hls-1137 mp4 640x360     25 | 1138k m3u8  | avc1.4d401e 1138k mp4a.40.2  0k
hls-2632 mp4 960x540     25 | 2632k m3u8  | avc1.4d401f 2632k mp4a.40.2  0k
hls-5064 mp4 1280x720    25 | 5065k m3u8  | avc1.64001f 5065k mp4a.40.2  0k
hls-6500 mp4 1920x1080   25 | 6500k m3u8  | avc1.640028 6500k mp4a.40.2  0k
```
1. This doesn't mean, of course, that the **dwIE** doesn't require fixing... 😉 
2. If I understood things correctly, ` --force-generic` has been deprecated in **yt-dlp** in favour of ` --ies generic`; but using that instead does not yield the same result as the deprecated flag...
```
yt-dlp -v -F "https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733" --ies generic => 
[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '-v', '-F', 'https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733', '--ies', 'generic']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] ytdl-patched/yt-dlp version 2022.09.18.1919 [a1f3c39] (win32_exe)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python 3.7.9 (CPython 32bit) - Windows-Vista-6.0.6003-SP2
[debug] Checking exe version: "..\ffmpeg" -bsfs
[debug] Checking exe version: "..\ffprobe" -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1 extractors
[debug] [generic] Extracting URL: https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733
[generic] av-63121733: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] av-63121733: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1553, in __extract_info
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\generic.py", line 3089, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733
```
A second bug discovered inadvertently here?

**Comment by pukkandan** [comment]
> * If I understood things correctly, ` --force-generic` has been deprecated in **yt-dlp** in favour of ` --ies generic`; but using that instead does not yield the same result as the deprecated flag...

https://github.com/yt-dlp/yt-dlp/blob/19b4e59a1e1bf368078f90e7f735fa4576f97b64/README.md#L2010

**Comment by dirkf** [comment]
To add some clarification that I personally needed, `--ies generic` doesn't enable the HTML5 extractor, and the extraction fails. Equally neither `--ies html5,default` nor just `--ies html5` work because the yt-dlp HTML5 extractor depends on the generic extractor.

**Comment by Vangelis66** [comment]
> ` --ie generic` restricts **yt-dlp** to use ONLY generic extractor while ` --ie generic,default` tells it to **prioritize** generic extractor

... Well, we already know the **default** extractor (=**dw**) fails, due to the filed bug...
... Using standalone **generic** one also fails, as proved by the log I posted... 

So, why will ` --ies generic,default` indeed work? 
```
[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '-v', '-F', 'https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733', '--ies', 'generic,default']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] ytdl-patched/yt-dlp version 2022.09.18.1919 [a1f3c39] (win32_exe)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python 3.7.9 (CPython 32bit) - Windows-Vista-6.0.6003-SP2
[debug] Checking exe version: "..\ffmpeg" -bsfs
[debug] Checking exe version: "..\ffprobe" -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1672 extractors
[debug] [generic] Extracting URL: https://www.dw.com/en/under-construction-indonesias-new-capital-nusantara/av-63121733
[generic] av-63121733: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] av-63121733: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[html5] av-63121733: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Identified a html5 embed
[info] Available formats for av-63121733-1:
ID       EXT RESOLUTION FPS |   TBR PROTO | VCODEC        VBR ACODEC    ABR
---------------------------------------------------------------------------
hls-386  mp4 480x270     25 |  386k m3u8  | avc1.42c015  386k mp4a.40.2  0k
hls-631  mp4 512x288     25 |  631k m3u8  | avc1.4d4015  631k mp4a.40.2  0k
hls-1137 mp4 640x360     25 | 1138k m3u8  | avc1.4d401e 1138k mp4a.40.2  0k
hls-2632 mp4 960x540     25 | 2632k m3u8  | avc1.4d401f 2632k mp4a.40.2  0k
hls-5064 mp4 1280x720    25 | 5065k m3u8  | avc1.64001f 5065k mp4a.40.2  0k
hls-6500 mp4 1920x1080   25 | 6500k m3u8  | avc1.640028 6500k mp4a.40.2  0k
```
(apologies if the answer is clear to **Python-savv**y persons, it just isn't to me... 😢 )

**Comment by dirkf** [comment]
It's just the extraction logic.

Normally (`default`) yt-dl[p] tries to match the to-be-extracted URL (possibly also checking the page that the URL gives) against the available extractors. The `--ies ...`/`--force-generic` options change that by forcibly applying an extractor that wouldn't have been selected.

Thus, by default:
1. match DW URL against extractors
2. select DWIE by URL match
3. fail to extract anything
4. give up (never trying Generic).

While in yt-dlp with `--ies generic, default`:
1. forcibly select GenericIE (which matches any URL)
2. find the embedded HTML5 using the HTML5EmbedIE extractor (enabled because of `default`)
3. return extracted HTML5
4. that's it.

For yt-dl with `--force-generic` it's similar, but the HTML5 extraction is (for now) in-line in the GenericIE.

**Comment by Vangelis66** [comment]
Thanks for that very detailed explanation 👍 .

> find the embedded HTML5 using the **HTML5EmbedIE** extractor (enabled because of **default**)

It was that very bit that eluded me, sadly 😞 ; i.e., unlike `youtube-dl`, **html5IE** is only invoked when **defaultIE** is also specified alongside **genericIE**... 
BTW, I printed myself a list of the available info-extractors, 1673 (!) in total at the moment, and there it was at place no. 525: `html5`; so, in `yt-dlp` it's called just **html5** (not **html5embed**).

> neither ` --ies html5,default` nor just `--ies html5` work because the **yt-dlp** HTML5 extractor depends on the **generic** extractor.

Thanks! According to this, ` --ies generic,html5` would work **equally as good** (in the case of the **DW** show in question) as ` --ies generic,default` (and it does 😄 ) ...

**Comment by Pablohn26** [comment]
I am hitting the same problem:
```
yt-dlp_linux -v -F  "https://www.dw.com/es/noticias-%C3%BAltima-hora/av-18529525"
[debug] Command-line config: ['-v', '-F', 'https://www.dw.com/es/noticias-%C3%BAltima-hora/av-18529525']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (linux_exe)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.0.0-6-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2-1 (setts), ffprobe 5.1.2-1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[dw] Extracting URL: https://www.dw.com/es/noticias-%C3%BAltima-hora/av-18529525
[dw] 18529525: Downloading webpage
ERROR: 18529525: An extractor error has occurred. (caused by KeyError('media_title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 680, in extract
  File "yt_dlp/extractor/dw.py", line 53, in _real_extract
KeyError: 'media_title'

```

**Comment by dirkf** [comment]
This page has what would be HTML5 video except that the tag is `<video-js>` instead of `<video>`. This is used for DW's player which appears to be based on _video.js_.

This structure hasn't been targeted in any existing yt-dl extractor AFAIK. In the BandaiChannel extractor the same tag introduces a Brighcove player that doesn't use `<source>` elements. Of course [`video.js` is a BC project](https://www.brightcove.com/en/resources/blog/videojs-40-now-available/). The [documentation of its `getPlayer()` method](https://github.com/videojs/video.js/blob/main/src/js/video.js#L250) says:
> * @param   {string|Element} id
> *          An HTML element - `<video>`, `<audio>`, or `<video-js>` -
> *          or a string matching the `id` of such an element.

So this patch to the HTML5 parser, which extracts DW's Spanish news, as above, with `--force-generic` in yt-dl, and I expect in yt-dlp, doesn't seem unreasonable:
```diff
-        _MEDIA_TAG_NAME_RE = r'(?:(?:amp|dl8(?:-live)?)-)?(video|audio)'
+        _MEDIA_TAG_NAME_RE = r'(?:(?:amp|dl8(?:-live)?)-)?(video(?:-js)?|audio)'
```

**Comment by dirkf** [comment]
Now the patch is in the branch: https://github.com/ytdl-org/youtube-dl/commit/ded2fbd635d2d1dedc86887cc95eddc5ab93796b.

**Comment by bashonly** [comment]
see also the uncannily similar suggested solution here: https://github.com/yt-dlp/yt-dlp/issues/6764#issuecomment-1502489642
