### ISSUE TITLE
[TikTok] tag extractors broken 

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#4952]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

California, USA 

### Provide a description that is worded well enough to be understood

TikTok songs and tag extractors do not work. They used to on my laptop, but on my *nix devices they do not work. I even used GitHub Actions to use a Windows runner to debug it, and it still doesn’t work.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Documents]$ yt-dlp https://www.tiktok.com/tag/
jadootv -vU 
[debug] Command-line config: ['https://www.tikt
ok.com/tag/jadootv', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pi
p)
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
15.4.1-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d2
5e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phant
omjs present, rtmpdump present
[debug] Optional libraries: Crypto-3.15.0, cert
ifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, 
websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.gith
ub.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 20
22.09.01
yt-dlp is up to date (2022.09.01)
[tiktok:tag] Setting up session
WARNING: [tiktok:tag] Unable to download webpage: The read operation timed out
[debug] [tiktok:tag] Extracting URL: https://www.tiktok.com/tag/jadootv
[tiktok:tag] jadootv: Downloading webpage
[download] Downloading playlist: jadootv
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 1 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 2 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 3 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 4 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 1 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 2 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 3 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 4 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 1 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 2 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 3 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 4 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 1 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 2 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 3 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
WARNING: [tiktok:tag] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 4 of 5)
[tiktok:tag] jadootv: Downloading video list page 1
ERROR: jadootv: Failed to parse JSON (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 974, in _parse_json
    return json.loads(
  File "/private/var/containers/Bundle/Application/4A7D25F8-7CF3-49FE-B87D-003CD121D26C/a-Shell-mini.app/Library/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/utils.py", line 596, in decode
    return super().decode(s)
  File "/private/var/containers/Bundle/Application/4A7D25F8-7CF3-49FE-B87D-003CD121D26C/a-Shell-mini.app/Library/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/private/var/containers/Bundle/Application/4A7D25F8-7CF3-49FE-B87D-003CD121D26C/a-Shell-mini.app/Library/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[tiktok:tag] Playlist jadootv: Downloading 1 videos of 0
[download] Finished downloading playlist: jadootv
[Documents]$ yt-dlp https://www.tiktok.com/t/ZTRaYkA4m/ -vU 
[debug] Command-line config: ['https://www.tiktok.com/t/ZTRaYkA4m/', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.9.10+ (CPython 64bit) - macOS-15.4.1-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d25e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phantomjs present, rtmpdump present
[debug] Optional libraries: Crypto-3.15.0, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://www.tiktok.com/t/ZTRaYkA4m/
[generic] ZTRaYkA4m: Downloading webpage
[redirect] Following redirect to https://www.tiktok.com/music/%E6%88%91%E6%98%AF%E5%B0%8F%E4%BB%99%E5%A5%B3-6829849504062130190?_d=secCgYIASAHKAESPgo8BxG9HP05QfIatBYLuE%2B%2BL9VcRAY9QozBkyddPAo7lA7nXaKbkEQjFs6c5J5d9SuEuTp%2BTK0l%2B%2BQI6A9BGgA%3D&_r=1&checksum=7e7b3574518aae5cb94f62de9ab1fb01fe2f1a15b7c64a163331d5eada4705d4&language=en&sec_user_id=MS4wLjABAAAAWRTxa9TmYNrI8T-5s9uJDRAEjUK47kceEtCRyFUIEsMang6XJwIvZMYGqCObcv8g&share_app_id=1233&share_link_id=BB3A8138-7A5B-4589-B3D9-605B23D2EE22&share_music_id=6829849504062130190&source=h5_m&timestamp=1663443638&tt_from=copy&u_code=e26e3635964a9j&ug_btm=b2878%2Cb5171&user_id=7106641030017270830&utm_campaign=client_share&utm_medium=ios&utm_source=copy
[debug] [generic] Extracting URL: https://www.tiktok.com/music/%E6%88%91%E6%98%AF%E5%B0%8F%E4%BB%99%E5%A5%B3-6829849504062130190?_d=secCgYIASAHKAESPgo8BxG9HP05QfIatBYLuE%2B%2BL9VcRAY9QozBkyddPAo7lA7nXaKbkEQjFs6c5J5d9SuEuTp%2BTK0l%2B%2BQI6A9BGgA%3D&_r=1&checksum=7e7b3574518aae5cb94f62de9ab1fb01fe2f1a15b7c64a163331d5eada4705d4&language=en&sec_user_id=MS4wLjABAAAAWRTxa9TmYNrI8T-5s9uJDRAEjUK47kceEtCRyFUIEsMang6XJwIvZMYGqCObcv8g&share_app_id=1233&share_link_id=BB3A8138-7A5B-4589-B3D9-605B23D2EE22&share_music_id=6829849504062130190&source=h5_m&timestamp=1663443638&tt_from=copy&u_code=e26e3635964a9j&ug_btm=b2878%2Cb5171&user_id=7106641030017270830&utm_campaign=client_share&utm_medium=ios&utm_source=copy
[generic] 我是小仙女-6829849504062130190?_d=secCgYIASAHKAESPgo8BxG9HP05QfIatBYLuE++L9VcRAY9QozBkyddPAo7lA7nXaKbkEQjFs6c5J5d9SuEuTp+TK0l++QI6A9BGgA=&_r=1&checksum=7e7b3574518aae5cb94f62de9ab1fb01fe2f1a15b7c64a163331d5eada4705d4&language=en&sec_user_id=MS4wLjABAAAAWRTxa9TmYNrI8T-5s9uJDRAEjUK47kceEtCRyFUIEsMang6XJwIvZMYGqCObcv8g&share_app_id=1233&share_link_id=BB3A8138-7A5B-4589-B3D9-605B23D2EE22&share_music_id=6829849504062130190&source=h5_m&timestamp=1663443638&tt_from=copy&u_code=e26e3635964a9j&ug_btm=b2878,b5171&user_id=7106641030017270830&utm_campaign=client_share&utm_medium=ios&utm_source=copy: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 我是小仙女-6829849504062130190?_d=secCgYIASAHKAESPgo8BxG9HP05QfIatBYLuE++L9VcRAY9QozBkyddPAo7lA7nXaKbkEQjFs6c5J5d9SuEuTp+TK0l++QI6A9BGgA=&_r=1&checksum=7e7b3574518aae5cb94f62de9ab1fb01fe2f1a15b7c64a163331d5eada4705d4&language=en&sec_user_id=MS4wLjABAAAAWRTxa9TmYNrI8T-5s9uJDRAEjUK47kceEtCRyFUIEsMang6XJwIvZMYGqCObcv8g&share_app_id=1233&share_link_id=BB3A8138-7A5B-4589-B3D9-605B23D2EE22&share_music_id=6829849504062130190&source=h5_m&timestamp=1663443638&tt_from=copy&u_code=e26e3635964a9j&ug_btm=b2878,b5171&user_id=7106641030017270830&utm_campaign=client_share&utm_medium=ios&utm_source=copy: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tiktok.com/music/%E6%88%91%E6%98%AF%E5%B0%8F%E4%BB%99%E5%A5%B3-6829849504062130190?_d=secCgYIASAHKAESPgo8BxG9HP05QfIatBYLuE%2B%2BL9VcRAY9QozBkyddPAo7lA7nXaKbkEQjFs6c5J5d9SuEuTp%2BTK0l%2B%2BQI6A9BGgA%3D&_r=1&checksum=7e7b3574518aae5cb94f62de9ab1fb01fe2f1a15b7c64a163331d5eada4705d4&language=en&sec_user_id=MS4wLjABAAAAWRTxa9TmYNrI8T-5s9uJDRAEjUK47kceEtCRyFUIEsMang6XJwIvZMYGqCObcv8g&share_app_id=1233&share_link_id=BB3A8138-7A5B-4589-B3D9-605B23D2EE22&share_music_id=6829849504062130190&source=h5_m&timestamp=1663443638&tt_from=copy&u_code=e26e3635964a9j&ug_btm=b2878%2Cb5171&user_id=7106641030017270830&utm_campaign=client_share&utm_medium=ios&utm_source=copy
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/music/%E6%88%91%E6%98%AF%E5%B0%8F%E4%BB%99%E5%A5%B3-6829849504062130190?_d=secCgYIASAHKAESPgo8BxG9HP05QfIatBYLuE%2B%2BL9VcRAY9QozBkyddPAo7lA7nXaKbkEQjFs6c5J5d9SuEuTp%2BTK0l%2B%2BQI6A9BGgA%3D&_r=1&checksum=7e7b3574518aae5cb94f62de9ab1fb01fe2f1a15b7c64a163331d5eada4705d4&language=en&sec_user_id=MS4wLjABAAAAWRTxa9TmYNrI8T-5s9uJDRAEjUK47kceEtCRyFUIEsMang6XJwIvZMYGqCObcv8g&share_app_id=1233&share_link_id=BB3A8138-7A5B-4589-B3D9-605B23D2EE22&share_music_id=6829849504062130190&source=h5_m&timestamp=1663443638&tt_from=copy&u_code=e26e3635964a9j&ug_btm=b2878%2Cb5171&user_id=7106641030017270830&utm_campaign=client_share&utm_medium=ios&utm_source=copy
[Documents]$ 
```

**Comment by Jadoo4QFan** [comment]
#4329 covers the song links

**Comment by wviana** [comment]
Having same issue trying to fetch a entire user with info.json. 
```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6]
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.15.71-1-lts-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: certifi-2022.09.24, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[tiktok:user] Setting up session
WARNING: [tiktok:user] Unable to download webpage: HTTP Error 403: Forbidden
[debug] [tiktok:user] Extracting URL: https://tiktok.com/@cortescanhotos
[tiktok:user] cortescanhotos: Downloading webpage
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 1 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 2 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 3 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 4 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 1 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 2 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 3 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 4 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 1 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 2 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 3 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 4 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 1 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 2 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 3 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 4 of 5)
[tiktok:user] cortescanhotos: Downloading user video list page 1
ERROR: [tiktok:user] cortescanhotos: cortescanhotos: Failed to parse JSON (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 666, in _real_extract
    thumbnail = traverse_obj(videos, (0, 'author', 'avatar_larger', 'url_list', 0))
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 5359, in traverse_obj
    val = _traverse_obj(obj, path)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 5347, in _traverse_obj
    obj = obj[key]
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2757, in __getitem__
    self._cache.extend(itertools.islice(self._iterable, n))
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 634, in _video_entries_api
    for retry in self.RetryManager():
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 5794, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 3858, in _error_or_warning
    RetryManager.report_retry(err, _count or int(fatal), _retries, info=self.to_screen, warn=self.report_warning,
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 5802, in report_retry
    raise e
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 636, in _video_entries_api
    post_list = self._call_api(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 128, in _call_api
    raise e
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 121, in _call_api
    res = self._call_api_impl(ep, real_query, manifest_app_version, video_id, fatal, note, errnote)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 58, in _call_api_impl
    return self._download_json(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1030, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1000, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 990, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 977, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 960, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 974, in _parse_json
    return json.loads(
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 596, in decode
    return super().decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 974, in _parse_json
    return json.loads(
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 596, in decode
    return super().decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 666, in _real_extract
    thumbnail = traverse_obj(videos, (0, 'author', 'avatar_larger', 'url_list', 0))
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 5359, in traverse_obj
    val = _traverse_obj(obj, path)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 5347, in _traverse_obj
    obj = obj[key]
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2757, in __getitem__
    self._cache.extend(itertools.islice(self._iterable, n))
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 634, in _video_entries_api
    for retry in self.RetryManager():
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 5794, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 3858, in _error_or_warning
    RetryManager.report_retry(err, _count or int(fatal), _retries, info=self.to_screen, warn=self.report_warning,
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 5802, in report_retry
    raise e
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 636, in _video_entries_api
    post_list = self._call_api(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 128, in _call_api
    raise e
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 121, in _call_api
    res = self._call_api_impl(ep, real_query, manifest_app_version, video_id, fatal, note, errnote)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 58, in _call_api_impl
    return self._download_json(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1030, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1000, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 990, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 977, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 960, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)
yt_dlp.utils.ExtractorError: cortescanhotos: Failed to parse JSON (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 696, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.ExtractorError: [tiktok:user] cortescanhotos: cortescanhotos: Failed to parse JSON (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wviana/soberana_conteudo/cortes_canhotos/main.py", line 63, in <module>
    main()
  File "/home/wviana/soberana_conteudo/cortes_canhotos/main.py", line 17, in main
    download()
  File "/home/wviana/soberana_conteudo/cortes_canhotos/main.py", line 22, in download
    ydl.download('https://tiktok.com/@cortescanhotos')
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3293, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3268, in wrapper
    res = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1448, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 994, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 934, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [tiktok:user] cortescanhotos: cortescanhotos: Failed to parse JSON (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
@wviana See pinned issues
