### ISSUE TITLE
[Museum of Modern Art in Warsaw] Add support for artmuseum.pl.

### ISSUE THREAD

**Issue by clusterized** [yt-dlp/yt-dlp#4957]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video: https://artmuseum.pl/en/filmoteka/praca/robakowski-jozef-test
- Single video: https://artmuseum.pl/pl/filmoteka/praca/robakowski-jozef-test
- Playlist: https://artmuseum.pl/en/filmoteka/programy/inny-wymiar-filmy-abstrakcyjne
- Playlist: https://artmuseum.pl/en/filmoteka/artysci/jozef-robakowski
- Playlist: https://artmuseum.pl/en/filmoteka/dekady/1970

### Provide a description that is worded well enough to be understood

Download link can be grabbed with _Inspect Element_:
http://media1.artmuseum.pl/video/480p/feefe8478b5ff4101a835a46bd39e928.mp4

Manually changing the link to http://media1.artmuseum.pl/video/720p/feefe8478b5ff4101a835a46bd39e928.mp4 also gives me access to a 720p version (for this video, the browser player maxes out at 480p).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ffmpeg-location', 'C:\\Program Files\\ffmpeg-master-latest-win64-gpl\\bin', 'https://artmuseum.pl/en/filmoteka/praca/robakowski-jozef-test']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-8.1-6.3.9600-SP0
[debug] Checking exe version: "C:\Program Files\ffmpeg-master-latest-win64-gpl\bin\ffmpeg" -bsfs
[debug] Checking exe version: "C:\Program Files\ffmpeg-master-latest-win64-gpl\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg N-106989-gb033913d1c-20220524 (setts), ffprobe N-106989-gb033913d1c-20220524
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://artmuseum.pl/en/filmoteka/praca/robakowski-jozef-test
[generic] robakowski-jozef-test: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] robakowski-jozef-test: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://artmuseum.pl/en/filmoteka/praca/robakowski-jozef-test
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1535, in __extract_info
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\generic.py", line 3078, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://artmuseum.pl/en/filmoteka/praca/robakowski-jozef-test
```

**Comment by dirkf** [comment]
```html
<div id="video-player" class="jp-jplayer" data-sources='{"360p":{"m4v":"iuuq;00nfejb3\/bsunvtfvn\/qm0wjefp0471q0gffgf9589c6gg5212b946b57ce4:f:39\/nq5","webmv":"iuuq;00nfejb3\/bsunvtfvn\/qm0wjefp0471q`xfcN0gffgf9589c6gg5212b946b57ce4:f:39\/xfcn"},"480p":{"m4v":"iuuq;00nfejb3\/bsunvtfvn\/qm0wjefp0591q0gffgf9589c6gg5212b946b57ce4:f:39\/nq5","webmv":"iuuq;00nfejb3\/bsunvtfvn\/qm0wjefp0591q`xfcN0gffgf9589c6gg5212b946b57ce4:f:39\/xfcn"}}' data-poster="/public/upload/filmoteka/original/519a0ba68a5ad.jpg" data-default-size="360p" data-autoplay="true" data-ratio="1.33333">>
```
The URLs (eg `iuuq;00nfejb3\/bsunvtfvn\/qm0wjefp0471q0gffgf9589c6gg5212b946b57ce4:f:39\/nq5`) are "encoded" by replacing each character with the next character in sequence.

Also, the web page devs added an invalid extra `>` because who cares about HTML syntax. Yet they included their website name in the code.

```py
>>> import re
>>> x = r'iuuq;00nfejb3\/bsunvtfvn\/qm0wjefp0471q0gffgf9589c6gg5212b946b57ce4:f:39\/nq5'
>>> ''.join(map(lambda c: chr(ord(c) - 1), tuple(re.sub(r'\\(.)', r'\1', x))))
'http://media2.artmuseum.pl/video/360p/feefe8478b5ff4101a835a46bd39e928.mp4'
>>> 
```

**Comment by jhwgh1968** [comment]
It looks like the basis of the site is jPlayer, which I think should be a generic embed based on how widely used it is.

It's a pretty ugly one for someone to write, though.

**Comment by dirkf** [comment]
Also this page https://artmuseum.pl/en/filmoteka/praca/ll-natalia-piramida-2 has a different structure. Instead of the obfuscated jPlayer video sources, there is an `iframe` whose `src` is `https://repozytorium.fn.org.pl/?q=pl/fnplayer/embed/10907`. Unfortunately this site's certificate expired 2 years ago and it doesn't understand SSL beyond TLSv1, so it's opaque to Python unless each request is hacked back to plain http://.
