### ISSUE TITLE
Can't Write non-English title

### ISSUE THREAD

**Issue by lemonadeforlife** [yt-dlp/yt-dlp#5022]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The title is in Bengali or Bangla Language. But it couldn't write the file name and the file name used in the command is 107 characters long also tried 77 characters and it still didn't work. 

tried byte mode, Unicode, etc still doesn't work
`--restrict-filenames` is not a viable option for cases like this  I have a whole around 14 playlists for my exams. And this title is the topic of the following subject that's why can't use id.

yt-dlp can create a directory in the Bengali Language with no problem but the issue is occurring when creating a filename in Bengali

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
❯ yt-dlp -vU --ignore-config https://youtu.be/WhjfzlThWJo              
[debug] Command-line config: ['-vU', '--ignore-config', 'https://youtu.be/WhjfzlThWJo']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.15.0-48-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs 140512515946432, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [youtube] Extracting URL: https://youtu.be/WhjfzlThWJo
[youtube] WhjfzlThWJo: Downloading webpage
[youtube] WhjfzlThWJo: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] WhjfzlThWJo: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr1---sn-jpgjax-jb2e.googlevideo.com/videoplayback?expire=1664056751&ei=TykvY57_B9HprQGNsbz4BQ&ip=103.73.197.73&id=o-APOr2WRpzVW3Z8BwAVar7M6vs9rgjESsRdR8QYf7KkWp&itag=248&source=youtube&requiressl=yes&mh=kr&mm=31%2C29&mn=sn-jpgjax-jb2e%2Csn-npoldn7y&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=445000&spc=yR2vp2M--uCUfUN_ecscxAZB559g-pA&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=24447715&dur=1012.044&lmt=1653898370403491&mt=1664034787&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=2316224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgcUaI4SytAO0yCbglg4cerbDohAjl2T27l3lFo-a6SUQCIQCvfE6NFG3WXfNLWr2k54PHk-fdubNhcojpJdD_fV0Dow%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgBLAsHR0RF9vReV0Rn_SxPnVY6zhUkBDyj69xWTkNPOECIQD_uVWpUEhl8GyTOSA2vD4Cfj4xP5dS4HLzPzCA4fNhYg%3D%3D"
ERROR: unable to open for writing: [Errno 36] File name too long: 'অধ্যায় ২： গুণগত রসায়ন： প্রধান কোয়ান্টাম সংখ্যা ও সহকারী কোয়ান্টাম সংখ্যা [HSC] [WhjfzlThWJo].f248.webm.part'
Traceback (most recent call last):
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/utils.py", line 626, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/utils.py", line 2152, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
OSError: [Errno 36] File name too long: 'অধ্যায় ২： গুণগত রসায়ন： প্রধান কোয়ান্টাম সংখ্যা ও সহকারী কোয়ান্টাম সংখ্যা [HSC] [WhjfzlThWJo].f248.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 267, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 236, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 222, in error_callback
    return RetryManager.report_retry(
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/utils.py", line 5802, in report_retry
    raise e
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 231, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 242, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/utils.py", line 628, in sanitize_open
    stream = open(filename, open_mode)
OSError: [Errno 36] File name too long: 'অধ্যায় ২： গুণগত রসায়ন： প্রধান কোয়ান্টাম সংখ্যা ও সহকারী কোয়ান্টাম সংখ্যা [HSC] [WhjfzlThWJo].f248.webm.part'


[debug] Invoking http downloader on "https://rr1---sn-jpgjax-jb2e.googlevideo.com/videoplayback?expire=1664056751&ei=TykvY57_B9HprQGNsbz4BQ&ip=103.73.197.73&id=o-APOr2WRpzVW3Z8BwAVar7M6vs9rgjESsRdR8QYf7KkWp&itag=251&source=youtube&requiressl=yes&mh=kr&mm=31%2C29&mn=sn-jpgjax-jb2e%2Csn-npoldn7y&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=445000&spc=yR2vp2M--uCUfUN_ecscxAZB559g-pA&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=17278852&dur=1012.061&lmt=1653898329485664&mt=1664034787&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=2311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIR6NovlR-5xDg9NLCUvywN2PYzDssVI1txF89foq_FaAiBLoLQoeOcz5ypru_KpoL8Ve4dt9Tpk90MXVGP1rwvm3g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgBLAsHR0RF9vReV0Rn_SxPnVY6zhUkBDyj69xWTkNPOECIQD_uVWpUEhl8GyTOSA2vD4Cfj4xP5dS4HLzPzCA4fNhYg%3D%3D"
ERROR: unable to open for writing: [Errno 36] File name too long: 'অধ্যায় ২： গুণগত রসায়ন： প্রধান কোয়ান্টাম সংখ্যা ও সহকারী কোয়ান্টাম সংখ্যা [HSC] [WhjfzlThWJo].f251.webm.part'
Traceback (most recent call last):
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/utils.py", line 626, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/utils.py", line 2152, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
OSError: [Errno 36] File name too long: 'অধ্যায় ২： গুণগত রসায়ন： প্রধান কোয়ান্টাম সংখ্যা ও সহকারী কোয়ান্টাম সংখ্যা [HSC] [WhjfzlThWJo].f251.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 267, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 236, in wrapper
    retry.error_callback(err, 1, 0)
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 222, in error_callback
    return RetryManager.report_retry(
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/utils.py", line 5802, in report_retry
    raise e
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 231, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 242, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/home/nahian/.pyenv/versions/3.10.7/lib/python3.10/site-packages/yt_dlp/utils.py", line 628, in sanitize_open
    stream = open(filename, open_mode)
OSError: [Errno 36] File name too long: 'অধ্যায় ২： গুণগত রসায়ন： প্রধান কোয়ান্টাম সংখ্যা ও সহকারী কোয়ান্টাম সংখ্যা [HSC] [WhjfzlThWJo].f251.webm.part'
```

**Comment by pukkandan** [comment]
The path length is determined by number of bytes, not characters. See pinned issue for solution

> tried byte mode, Unicode, etc still doesn't work

No idea what this even means

**Comment by lemonadeforlife** [comment]
> The path length is determined by number of bytes, not characters. See pinned issue for solution
understood
> > tried byte mode, Unicode, etc still doesn't work
> 
> No idea what this even means
me neither.

**Comment by lemonadeforlife** [comment]
> No idea what this even means

me neither


> The path length is determined by number of bytes, not characters. See pinned issue for solution

understood. thanks for the reply.
