### ISSUE TITLE
Roblox Audio

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#5049]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States of America

### Example URLs

https://www.roblox.com/library/7910582982/
User Inventory Audio: https://www.roblox.com/users/1276530838/inventory/#!/audio
User Favorite Audio: https://www.roblox.com/users/1276530838/favorites#!/audio

### Provide a description that is worded well enough to be understood

If you want to directly extract assets, Roblox asset IDs can be downloaded via a specific URL. See https://github.com/Anaminus/roblox-bug-tracker/issues/71 for more information about this. Roblox audios can be previewed in the browser, which seems the more viable option for us. Please also support extraction from a favorite list or inventory list in place of playlists. Most of long Roblox audio are wiped out due to Roblox getting a lawsuit from all of recording companies in March 22, 2022. There still remains short audio. Even though the audios are unable to be played, we are still able to play them via Roblox games owned by the player. In the future we can fool Roblox into downloading unlisted audios via finding the creators game and pretending to request a download from them as you are playing that game. I personally play roblox and I am an archivist so I’d like this feature to backup audios in case Roblox gets yet another lawsuit.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
leasemakethisgetaloto
fviews
[Documents]$ yt-dlp -vU https://www.roblox.com/
library/7910582982/
[debug] Command-line config: ['-vU', 'https://w
ww.roblox.com/library/7910582982/']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pi
p)
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
16.0-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d2
5e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phant
omjs present, rtmpdump present
[debug] Optional libraries: Cryptodome-3.15.0, 
certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6
.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://www.roblox.com/library/7910582982/
[generic] 7910582982: Downloading webpage
[redirect] Following redirect to https://www.roblox.com/library/7910582982/Backrooms-Ambiance-High-Quality
[debug] [generic] Extracting URL: https://www.roblox.com/library/7910582982/Backrooms-Ambiance-High-Quality
[generic] Backrooms-Ambiance-High-Quality: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Backrooms-Ambiance-High-Quality: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.roblox.com/library/7910582982/Backrooms-Ambiance-High-Quality
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/C53C35F9-CF23-4488-A35D-C0112FE31C26/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/C53C35F9-CF23-4488-A35D-C0112FE31C26/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/C53C35F9-CF23-4488-A35D-C0112FE31C26/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/C53C35F9-CF23-4488-A35D-C0112FE31C26/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.roblox.com/library/7910582982/Backrooms-Ambiance-High-Quality
[Documents]$ 
```

**Comment by gamer191** [comment]
this issue is a duplicate of https://github.com/yt-dlp/yt-dlp/issues/4029, although that one was closed as `incomplete`

**Comment by gamer191** [comment]
And by extension it's also a duplicate of https://github.com/yt-dlp/yt-dlp/issues/3667

**Comment by Jadoo4QFan** [comment]
Comments JSON 

https://www.roblox.com/comments/get-json?assetId=7910582982&startindex=10&thumbnailWidth=100&thumbnailHeight=100&thumbnailFormat=PNG&cachebuster=3086

**Comment by Jadoo4QFan** [comment]
![42CB9FAF-4B54-4EDD-BE17-2A6DDEFE0960](https://user-images.githubusercontent.com/113491050/192428232-7cb4e078-1879-49b5-af97-f4858565a86b.png)
![1D9EBF65-F656-4A7C-94F5-95271ECA2A0B](https://user-images.githubusercontent.com/113491050/192428236-e7c9b19e-e225-4068-85df-719d5294d1c8.png)
![4C7D81B4-6E67-4373-ADF9-62175F2CD65C](https://user-images.githubusercontent.com/113491050/192428238-07ceabdf-6570-407d-a4da-47137f166d3a.png)
![A9F57BF8-7F1F-4A53-A759-CF396F1C2E04](https://user-images.githubusercontent.com/113491050/192428239-faece309-34e0-4170-bb69-7ec70f4e718e.png)
The JSON is really similar to YouTubes in structure
