### ISSUE TITLE
CuriosityStream No video formats found!

### ISSUE THREAD

**Issue by KieranCodes** [yt-dlp/yt-dlp#5058]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

Running yt-dlp on CuriosityStream videos gives the error: No video formats found!

I've tried multiple videos and VPNs in different countries.

The videos work in my browser.

This was working the other day.

I don't think it's rate limited because I haven't had a 429 error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://curiositystream.com/video/2112']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.6-arch1-1-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[curiositystream] Logging in
[debug] [curiositystream] Extracting URL: https://curiositystream.com/video/2112
[curiositystream] 2112: Downloading JSON metadata
[curiositystream] 2112: Downloading JSON metadata
ERROR: [curiositystream] 2112: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1556, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1614, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2546, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1025, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [curiositystream] 2112: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by october262** [comment]
instead of using the username & password option, try again with the
cookies.txt file option.

**Comment by KieranCodes** [comment]
> instead of using the username & password option, try again with the cookies.txt file option.

I tried it with both `--cookies cookies.txt` and `--cookies-from-browser brave` but I get the same error message.

**Comment by mnn** [comment]
I am using `--cookies-from-browser` and it doesn't work for me as well (it used to work two days back).

```
<> yt-dlp --cookies-from-browser vivaldi https://curiositystream.com/video/4983 -v
[debug] Command-line config: ['--cookies-from-browser', 'vivaldi', 'https://curiositystream.com/video/4983', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.6 (CPython 64bit) - Linux-5.19.7-1-MANJARO-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotlicffi-1.0.9.2, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from vivaldi
[debug] Extracting cookies from: "/home/moen/.config/vivaldi/Default/Cookies"
[debug] detected desktop environment: OTHER
[debug] Chosen keyring: BASICTEXT
[Cookies] Extracted 3129 cookies from vivaldi
[debug] cookie version breakdown: {'v10': 3084, 'v11': 0, 'other': 0, 'unencrypted': 45}
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] [curiositystream] Extracting URL: https://curiositystream.com/video/4983
[debug] [curiositystream] Obtained auth_token cookie
[curiositystream] 4983: Downloading JSON metadata
[curiositystream] 4983: Downloading JSON metadata
ERROR: [curiositystream] 4983: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1556, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1614, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2546, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1025, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [curiositystream] 4983: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
<> yt-dlp -U                                                                      
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
```

**Comment by yulimoto** [comment]
I can confirm the same bug from yesterday for me. I tried with username,password and cookies on Arch and Slackware. 
If I not using any credentials usually it will shows 2 minutes trailer movie, but currently it also throw error, so I think it is not related to credentials/cookies. I hope it will be fixed soon, cheers!

```
yulimoto@rigel:~ $ yt-dlp --cookies-from-browser firefox https://curiositystream.com/video/3256 -v
[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://curiositystream.com/video/3256', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6]
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.15.68-1-lts-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/yulimoto/.mozilla/firefox/hcw0surx.default-release/cookies.sqlite"
[Cookies] Extracted 1421 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] [curiositystream] Extracting URL: https://curiositystream.com/video/3256
[debug] [curiositystream] Obtained auth_token cookie
[curiositystream] 3256: Downloading JSON metadata
[curiositystream] 3256: Downloading JSON metadata
ERROR: [curiositystream] 3256: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1556, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1614, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2546, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1025, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [curiositystream] 3256: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U



yulimoto@rigel:~ $ yt-dlp -vU  https://curiositystream.com/video/3256 
[debug] Command-line config: ['-vU', 'https://curiositystream.com/video/3256']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6]
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.15.68-1-lts-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [curiositystream] Extracting URL: https://curiositystream.com/video/3256
[curiositystream] 3256: Downloading JSON metadata
[curiositystream] 3256: Downloading JSON metadata
ERROR: [curiositystream] 3256: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1556, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1614, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2546, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1025, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [curiositystream] 3256: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

```

**Comment by bkeys** [comment]
I can confirm I subscribed today and am having the same issues.

**Comment by KieranCodes** [comment]
This is working again now, not sure what was wrong before.
