### ISSUE TITLE
[Broken] `--get-comments` fails for YouTube

### ISSUE THREAD

**Issue by Evernow** [yt-dlp/yt-dlp#507]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.07.07**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[daniel@daniel-systemproductname test]$ yt-dlp --verbose --ignore-errors --no-continue --no-overwrites --get-comments  --extractor-args youtube:player_client=android --throttled-rate 100K https://www.youtube.com/watch?v=VEC0gZvMVAI
[debug] Command-line config: ['--verbose', '--ignore-errors', '--no-continue', '--no-overwrites', '--get-comments', '--extractor-args', 'youtube:player_client=android', '--throttled-rate', '100K', 'https://www.youtube.com/watch?v=VEC0gZvMVAI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.07 
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.13.0-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=VEC0gZvMVAI
[youtube] VEC0gZvMVAI: Downloading webpage
[youtube] VEC0gZvMVAI: Downloading mobile player API JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] VEC0gZvMVAI: Downloading 1 format(s): 248+251
[youtube] Downloading initial comment continuation page 
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube] Downloading initial comment continuation page (retry #1)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube] Downloading initial comment continuation page (retry #2)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube] Downloading initial comment continuation page (retry #3)
ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1142, in wrapper
    return func(self, *args, **kwargs)
  File "/home/daniel/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1178, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/daniel/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1219, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/daniel/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2198, in process_video_result
    self.process_info(new_info)
  File "/home/daniel/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2358, in process_info
    self.post_extract(info_dict)
  File "/home/daniel/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2860, in post_extract
    actual_post_extract(info_dict or {})
  File "/home/daniel/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2852, in actual_post_extract
    extra = post_extractor().items()
  File "/home/daniel/.local/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2927, in <lambda>
    info['__post_extractor'] = lambda: self._extract_comments(ytcfg, video_id, contents, webpage, xsrf_token)
  File "/home/daniel/.local/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2157, in _extract_comments
    for comment in comment_iter:
  File "/home/daniel/.local/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2080, in _comment_entries
    raise ExtractorError(last_error)
yt_dlp.utils.ExtractorError: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.



```

## Description

If the option `--extractor-args youtube:player_client=android` is passed, yt-dlp fails to be able to finish with the  `--get-comments` argument also passed through.

**Comment by Evernow** [comment]
This seems to no longer happen with master, haven't bisected yet, but possible fix would be https://github.com/yt-dlp/yt-dlp/pull/466 ?

**Comment by pukkandan** [comment]
In the release version, this error is expected (See #121). The second is caused due a network error - specifically, the DNS resolution seems to have failed

We could try and make --retries work for comments 🤔 - Related #439
cc @colethedj

**Comment by colethedj** [comment]
> In the release version, this error is expected (See #438). The second is caused due a network error - specifically, the DNS resolution seems to have failed

Yep, this is correct. `--extractor-args youtube:player_client=android` should have no effect on comment extraction since comment extraction is still done under the web client regardless (including the initial continuation).

As said, the first error is expected to happen on and off in release, since YouTube has changed their comment API. It has been fixed in master.

> We could try and make --retries work for comments thinking - Related #481 #380

We should definitely look into this. Since all YouTube API related calls now use the same wrapper function it'll also benefit them other than just comments (tab extraction, etc.).
