### ISSUE TITLE
Unsupport URL: ctv.ca (CTV Throwback shows)

### ISSUE THREAD

**Issue by jchas** [yt-dlp/yt-dlp#5072]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

https://www.ctv.ca/shows/barney-miller

### Provide a description that is worded well enough to be understood

Cannot download any videos from the free "CTV Throwback" section of the ctv.ca website.  When using a browser, no user login is required to view any shows listed in the "CTV Throwback" section.  Trying to download any show in this section with yt-dlp fails ("Unsupported URL").

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
'$ yt-dlp -vU https://www.ctv.ca/shows/barney-miller
[debug] Command-line config: ['-vU', 'https://www.ctv.ca/shows/barney-miller']
[debug] User config "/Users/John/yt-dlp.conf.txt": ['--recode-video', 'mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.9.14 (CPython 64bit) - macOS-10.14.6-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://www.ctv.ca/shows/barney-miller
[generic] barney-miller: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] barney-miller: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.ctv.ca/shows/barney-miller
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.ctv.ca/shows/barney-miller

'
```

**Comment by jchas** [comment]
The section https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md lists CTV as a supported site, but it does not appear to work.

**Comment by flashdagger** [comment]
The CTV support refers only to single episodes. Links to the shows itself are not supported. Try e.g. https://www.ctv.ca/shows/barney-miller/evacuation-s3e1

**Comment by doe1080** [comment]
all content is currently DRM-protected
