### ISSUE TITLE
PBSlearningmedia.org

### ISSUE THREAD

**Issue by Baenwort** [yt-dlp/yt-dlp#5073]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

Single Episode: https://wisconsin.pbslearningmedia.org/resource/1f8f7d1b-6cdf-4859-863d-b4877ad8a67f/skills-the-electric-company/

Playlist of Episodes for a Single Show: https://wisconsin.pbslearningmedia.org/collection/the-electric-company/t/tec-full-episodes/

The link they provide if you want a student to view only the video: wisconsin.pbslearningmedia.org/resource/1f8f7d1b-6cdf-4859-863d-b4877ad8a67f/skills-the-electric-company/?student=true&focus=true

### Provide a description that is worded well enough to be understood

I'm trying to have a offline copy of teaching material (episode videos) to be used when the school is having internet access troubles or if we are doing a field trip outside of town. (Rural so cell service is only near town).

When I put the URL into yt-dlp it doesn't find the video. Since other PBS sites are supported I was hoping that pbslearningmedia.org would also be supported.

When directly viewing the page in Firefox, Vivaldi, or Chrome the video will play without needing to be logged into the site.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'www.pbslearningmedia.org/resource/1f8f7d1b-6cdf-4859-863d-b4877ad8a67f/skills-the-electric-company/?student=true']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656]
[debug] Python 3.9.14 (CPython 64bit) - FreeBSD-13.1-RELEASE-p1-amd64-64bit-ELF (libc 7)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: www.pbslearningmedia.org/resource/1f8f7d1b-6cdf-4859-863d-b4877ad8a67f/skills-the-electric-company/?student=true
WARNING: [generic] The url doesn't specify the protocol, trying with http
[debug] [generic] Extracting URL: http://www.pbslearningmedia.org/resource/1f8f7d1b-6cdf-4859-863d-b4877ad8a67f/skills-the-electric-company/?student=true
[generic] ?student=true: Downloading webpage
[redirect] Following redirect to https://wisconsin.pbslearningmedia.org/resource/1f8f7d1b-6cdf-4859-863d-b4877ad8a67f/skills-the-electric-company/?student=true
[debug] [generic] Extracting URL: https://wisconsin.pbslearningmedia.org/resource/1f8f7d1b-6cdf-4859-863d-b4877ad8a67f/skills-the-electric-company/?student=true
[generic] ?student=true: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?student=true: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://wisconsin.pbslearningmedia.org/resource/1f8f7d1b-6cdf-4859-863d-b4877ad8a67f/skills-the-electric-company/?student=true
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://wisconsin.pbslearningmedia.org/resource/1f8f7d1b-6cdf-4859-863d-b4877ad8a67f/skills-the-electric-company/?student=true
```

**Comment by coletdjnz** [comment]
Related upstream issue for more test cases: https://github.com/ytdl-org/youtube-dl/issues/11717

For devs:

I'm not sure if this is able to be integrated into the existing PBS extractor. Seems to be entirely different. 

Request to `https://www.pbslearningmedia.org/api/v2/resource/<id in url>/?cookie:user_content_permission=FREE&cookie:student=false` contains video metadata and streaming links.
Possibly may need cookies automatically set by the webpage request.

API is warning that an API key is required (but does not appear to use one?). It could just be a bug, but there appears to be one embedded the webpage that may work if necessary. It also gives a link to the public API docs in the same warning; assuming that is for the public variation of the endpoint(s). Might be useful.
https://docs.pbs.org/display/DLM/PBS+LearningMedia+API+v2

Don't know if the `<some name>.pbslearningmedia.org` has any significance. If not just let generic extractor follow the redirect.

**Comment by Baenwort** [comment]
Hi the <some name> is the local PBS chapter.
![image](https://user-images.githubusercontent.com/32050048/193947827-eb87f37f-ef52-4ed2-9767-aa1779337e3b.png)

If you change which state or local PBS broadcaster in this form it changes some of the resources provided (teaching aids, lesson plans, etc) but doesn't change the videos as far as I can tell.
