### ISSUE TITLE
Crackle - Site Changed, Downloads Failing

### ISSUE THREAD

**Issue by TheGrimKeeper** [yt-dlp/yt-dlp#5118]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

It looks like the Crackle website has been updated, and downloads no longer work.  The extractor tries to fall back to the generic downloader so the URL structure may have changed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.crackle.com/details/cd961267-b49b-48fc-af0d-f66ad7fb21ec/the-toxic-avenger']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n4.4-78-g031c0cb0b4-20210714 (setts), ffprobe n4.4-78-g031c0cb0b4-20210714
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://www.crackle.com/details/cd961267-b49b-48fc-af0d-f66ad7fb21ec/the-toxic-avenger

[generic] the-toxic-avenger: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] the-toxic-avenger: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.crackle.com/details/cd961267-b49b-48fc-af0d-f66ad7fb21ec/the-toxic-avenger
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1535, in __extract_info
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\generic.py", line 3078, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.crackle.com/details/cd961267-b49b-48fc-af0d-f66ad7fb21ec/the-toxic-avenger
```

**Comment by october262** [comment]
movie is DRM protected

**Comment by keving87** [comment]
> movie is DRM protected

It's not just movies though, unless shows are also DRM now. 

`ytdl.exe -vU -F https://www.crackle.com/details/204955ed-12c3-4e91-b2c7-18bae4c244a5/us-and-them/pilot
[debug] Command-line config: ['-vU', '-F', 'https://www.crackle.com/details/204955ed-12c3-4e91-b2c7-18bae4c244a5/us-and-them/pilot']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [Crackle] Extracting URL: https://www.crackle.com/details/204955ed-12c3-4e91-b2c7-18bae4c244a5/us-and-them/pilot
WARNING: [Crackle] No country code was given using --geo-bypass-country. Trying with a list of known countries
[Crackle] 204955: Downloading media JSON from US API
ERROR: [Crackle] 204955: Crackle said: Fatal Error 105 - Media ID not found in Sony Crackle System
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\crackle.py", line 122, in _real_extract`

**Comment by october262** [comment]
> > movie is DRM protected
> 
> It's not just movies though, unless shows are also DRM now.
> 
> > ytdl.exe -vU -F https://www.crackle.com/details/204955ed-12c3-4e91-b2c7-18bae4c244a5/us-and-them/pilot
> > [debug] Command-line config: ['-vU', '-F', 'https://www.crackle.com/details/204955ed-12c3-4e91-b2c7-18bae4c244a5/us-and-them/pilot']
> > [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
> > [debug] yt-dlp version 2022.10.04 [[4e0511f](https://github.com/yt-dlp/yt-dlp/commit/4e0511f27d153ee0dbc4da158b4e35add8f7511a)] (win32_exe)
> > [debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
> > [debug] Checking exe version: ffmpeg -bsfs
> > [debug] Checking exe version: ffprobe -bsfs
> > [debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
> > [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
> > [debug] Proxy map: {}
> > [debug] Loaded 1690 extractors
> > [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> > Latest version: 2022.10.04, Current version: 2022.10.04
> > yt-dlp is up to date (2022.10.04)
> > [debug] [Crackle] Extracting URL: https://www.crackle.com/details/204955ed-12c3-4e91-b2c7-18bae4c244a5/us-and-them/pilot
> > WARNING: [Crackle] No country code was given using --geo-bypass-country. Trying with a list of known countries
> > [Crackle] 204955: Downloading media JSON from US API
> > ERROR: [Crackle] 204955: Crackle said: Fatal Error 105 - Media ID not found in Sony Crackle System
> > File "yt_dlp\extractor\common.py", line 672, in extract
> > File "yt_dlp\extractor\crackle.py", line 122, in _real_extract

i've tried downloading an anime series and this is the error i get - [generic] 3f9yb_Widevine_Dash_playlist: This video is DRM protected

**Comment by TheGrimKeeper** [comment]
> It's not just movies though, unless shows are also DRM now.

Yeah, if this is indeed DRM it seems like it's been deployed across the whole site, rendering this extractor useless.

**Comment by bashonly** [comment]
yeah it looks like everything got the DRM treatment

`https://prod-api.crackle.com/content/204955ed-12c3-4e91-b2c7-18bae4c244a5`
```json
    "assets": {
      "video": [
        {
          "id": "918e86d5-3259-402f-aa56-e9a60da98017",
          "type": "Widevine",
          "aspectRatio": "16:9",
          "frameWidth": 1920,
          "frameHeight": 1080,
          "bitRates": [
            3800,
            2700,
            1500,
            925,
            560,
            320
          ],
          "framerate": 23.97,
          "duration": 1296
        },
        {
          "id": "eb1a4f79-b67f-4d4a-ba80-c0c405f459ef",
          "type": "Dash_Playready",
          "aspectRatio": "16:9",
          "frameWidth": 1920,
          "frameHeight": 1080,
          "bitRates": [
            3800,
            2700,
            1500,
            925,
            560,
            320
          ],
          "framerate": 23.97,
          "duration": 1296
        },
        {
          "id": "4e6153e5-d8df-463d-b9cd-a83cd46813b6",
          "type": "HLS_Fairplay",
          "aspectRatio": "16:9",
          "frameWidth": 1920,
          "frameHeight": 1080,
          "bitRates": [
            3800,
            2700,
            1500,
            925,
            560,
            320
          ],
          "framerate": 23.97,
          "duration": 1296
        }
      ],
    }
```
