### ISSUE TITLE
[Bitchute] ERROR: unable to download video data: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by jasonkhanlar** [yt-dlp/yt-dlp#514]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser [ANY]
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
[debug] Command-line config: ['--verbose', 'https://www.bitchute.com/video/ANY/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.06.23
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.12.14-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/ANY/
[BitChute] ANY: Downloading webpage
[BitChute] ANY: Checking video URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ANY: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://seed305.bitchute.com/ANY/ANY.mp4"
ERROR: unable to download video data: HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "~/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2672, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "~/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2335, in dl
    return fd.download(name, new_info, subtitle)
  File "~/.local/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 385, in download
    return self.real_download(filename, info_dict), True
  File "~/.local/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 366, in real_download
    establish_connection()
  File "~/.local/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 118, in establish_connection
    raise err
  File "~/.local/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 112, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "~/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3089, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

## Description

WRITE DESCRIPTION HERE

When downloading multiple videos from Bitchute at once, sometimes 401 Unauthorized is result, which triggers errors in yt-dlp. After waiting until previous videos download successfully and trying again, Bitchute no longer shows 401, and the video downloads successfully without errors.

**Comment by jasonkhanlar** [comment]
Also see this separate issue: https://github.com/yt-dlp/yt-dlp/issues/376#issuecomment-881267841

**Comment by Ashish0804** [comment]
> When downloading multiple videos from Bitchute at once

yeah don't do that, they might be rate limiting you.

**Comment by pukkandan** [comment]
Bitchute doesn't let you play 2 videos at the same time, even in browser
