### ISSUE TITLE
Rumble download says "No video formats found"

### ISSUE THREAD

**Issue by jordancurve** [yt-dlp/yt-dlp#5177]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

If I go to https://rumble.com/v1mya66-darrell-brooks-trial-day-2-prosecution-witnesses-waukesha-parade-killer.html in a browser and click Play, the video plays. So I expected that yt-dlp, given that URL, would download the video, just like it does with YouTube videos. However, yt-dlp gives a "No video formats found" error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://rumble.com/v1mya66-darrell-brooks-trial-day-2-prosecution-witnesses-waukesha-parade-killer.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.9.13 (CPython 64bit) - macOS-11.7-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2021.10.08, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://rumble.com/v1mya66-darrell-brooks-trial-day-2-prosecution-witnesses-waukesha-parade-killer.html
[generic] v1mya66-darrell-brooks-trial-day-2-prosecution-witnesses-waukesha-parade-killer: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] v1mya66-darrell-brooks-trial-day-2-prosecution-witnesses-waukesha-parade-killer: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a RumbleEmbed embed
[debug] [RumbleEmbed] Extracting URL: https://rumble.com/embed/v1kc4bq
[RumbleEmbed] v1kc4bq: Downloading JSON metadata
ERROR: [RumbleEmbed] v1kc4bq: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1574, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1632, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2569, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1027, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [RumbleEmbed] v1kc4bq: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by jordancurve** [comment]
This works for me now, with the same version of yt-dlp. Maybe videos created with Rumble's livestreaming feature require some post-processing on Rumble's end before they can be downloaded with yt-dlp.
