### ISSUE TITLE
Communities.win - Posts including video clips - Previously functioned with generic extractor until recently

### ISSUE THREAD

**Issue by tcpip2** [yt-dlp/yt-dlp#5200]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Approximately 5 days ago, I encountered an issue with downloading video clips linked to user posts for a community hosted at Communities.win.  More specifically, I've been downloading clips from a particular community hosted there using yt-dlp since the last half of May with no problems using the generic extractor and now when I attempt to do so, I get the 'Unsupported URL:' error.

The video clips are tied to the community posts and I use their URLs to download the video clips linked within them as the title of the posts are used to name of the file instead of having a generic filename where they are usually hosted at which is either at pomf2.lain.la or files.catbox.moe 90+% of the time.

I've tried connecting with a credentials and without, connecting from multiple locations using a VPN, connecting from multiple hosts and they all result in the same issue unfortunately.  I've also used the '--write-pages' argument to review what yt-dlp is parsing and I can clearly see the URL with the description listed within (this is without credentials from the host I normally pull these clips from using the same arguments I typically use).  Here is a snippet from the write pages output related to the verbose output provided below showing the HREF to the video clip with the related description:

```
❯ grep -B3 -A3 lain.la c_https_-_communities.win_c_IP2Always_p_15JnU6EUBW_c.dump 
</div>
<div class="body">
<div class="top">
<a href="https://pomf2.lain.la/f/jju51oq.mp4" class="title">
Xenon learned some tips from the Dahmer special
</a>
<span class="domain">(<span>pomf2.lain.la</span>)</span>
<span class="post-flair" data-flair="clip">CLIP</span>
</div>
<div class="details">
--
</span>
</div>
<div class="content link">
<div class="video-container" data-src="https://pomf2.lain.la/f/jju51oq.mp4">
<div class="video-container">
<iframe src="https://pomf2.lain.la/f/jju51oq.mp4" frameborder="0" allowfullscreen></iframe>
</div>
</div>
</div>
```
I haven't observed any noticeable changes to the site layout or functionality though I understand that doesn't mean there hasn't been any changes to the underlying code and/or processes which drive the site.

I've saved verbose logs of all of the downloads I've done since May for all of the clips I've successfully downloaded up until the time this issue began if needed as well.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-4', '--restrict-filenames', '-o', '%(upload_date>%Y%m%d)s-%(uploader)s-%(title)s.%(ext)s', '-vU', '-4', '--restrict-filenames', '-o', '%(upload_date>%Y%m%d)s-%(timestamp)s-%(title)s.%(ext)s', '--no-mtime', 'https://communities.win/c/IP2Always/p/15JnU6EUBW/c']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] (debian*) API
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.17.5-051705-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 5, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.6.1, brotli-1.0.7, certifi-2021.10.08, mutagen-1.44.0, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://communities.win/c/IP2Always/p/15JnU6EUBW/c
[generic] c: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] c: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://communities.win/c/IP2Always/p/15JnU6EUBW/c
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 3062, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://communities.win/c/IP2Always/p/15JnU6EUBW/c
```

**Comment by coletdjnz** [comment]
We could maybe add support for direct video links in iframes to generic :thinking:

**Comment by tcpip2** [comment]
Is there any additional information you need from me regarding this to move forward?  Also, I'm assuming while this has been triaged a decision hasn't been made to actually implement your suggestion in an upcoming version, correct?

I'd be willing to offer a bounty for someone to implement an extractor for this site, more specifically the particular community hosted on communities.win that's referenced in the original post.  Support for all of communities.win would be great as well though I don't know how much this specific community's user post schema differs from other communities hosted on the site.
