### ISSUE TITLE
Google Photos

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#5222]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

- Single video 
https://photos.google.com/share/AF1QipNi8VN2pw2Ya_xCV8eFgzEZmiXDy1-GwhXbqFtvXoH3HypF10as9puV8FdoVZpOZA/photo/AF1QipPIoUaSCvCyqWszRQz6n_lz4V8boxtmRO_Ow3OJ?key=WkZjQTIxQTM5a01oZkNUYTE2ZllKT
VJKZk1CMTR3
- Playlist 
https://photos.google.com/share/AF1QipNi8VN2pw2Ya_xCV8eFgzEZmiXDy1-GwhXbqFtvXoH3HypF10as9puV8FdoVZpOZA?key=WkZjQTIxQTM5a01oZkNUYTE2ZllKTVJKZk1CMTR3

### Provide a description that is worded well enough to be understood

Please add support for downloading videos from Google Photos. Playlist support would be appreciated.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Documents]$ yt-dlp https://photos.google.com/s
hare/AF1QipNi8VN2pw2Ya_xCV8eFgzEZmiXDy1-GwhXbqF
tvXoH3HypF10as9puV8FdoVZpOZA/photo/AF1QipPIoUaS
CvCyqWszRQz6n_lz4V8boxtmRO_Ow3OJ?key=WkZjQTIxQT
M5a01oZkNUYTE2ZllKTVJKZk1CMTR3 -vU 
[debug] Command-line config: ['https://photos.g
oogle.com/share/AF1QipNi8VN2pw2Ya_xCV8eFgzEZmiX
Dy1-GwhXbqFtvXoH3HypF10as9puV8FdoVZpOZA/photo/A
F1QipPIoUaSCvCyqWszRQz6n_lz4V8boxtmRO_Ow3OJ?key
=WkZjQTIxQTM5a01oZkNUYTE2ZllKTVJKZk1CMTR3', '-v
U']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pi
p) API
[debug] Python 3.9.10+ (CPython 64bit) - macOS-16.0-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d25e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phantomjs present, rtmpdump present
[debug] Optional libraries: Cryptodome-3.15.0, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://photos.google.com/share/AF1QipNi8VN2pw2Ya_xCV8eFgzEZmiXDy1-GwhXbqFtvXoH3HypF10as9puV8FdoVZpOZA/photo/AF1QipPIoUaSCvCyqWszRQz6n_lz4V8boxtmRO_Ow3OJ?key=WkZjQTIxQTM5a01oZkNUYTE2ZllKTVJKZk1CMTR3
[generic] AF1QipPIoUaSCvCyqWszRQz6n_lz4V8boxtmRO_Ow3OJ?key=WkZjQTIxQTM5a01oZkNUYTE2ZllKTVJKZk1CMTR3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] AF1QipPIoUaSCvCyqWszRQz6n_lz4V8boxtmRO_Ow3OJ?key=WkZjQTIxQTM5a01oZkNUYTE2ZllKTVJKZk1CMTR3: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://photos.google.com/share/AF1QipNi8VN2pw2Ya_xCV8eFgzEZmiXDy1-GwhXbqFtvXoH3HypF10as9puV8FdoVZpOZA/photo/AF1QipPIoUaSCvCyqWszRQz6n_lz4V8boxtmRO_Ow3OJ?key=WkZjQTIxQTM5a01oZkNUYTE2ZllKTVJKZk1CMTR3
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3062, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL:
```

**Comment by pukkandan** [comment]
The first link gives 404 nd the second seems to contain only pictures

**Comment by Jadoo4QFan** [comment]
The playlist has videos, just scroll a bit.

**Comment by abney317** [comment]
@pukkandan This was closed as completed, but I don't think it was done (at least it's not in the latest release that I know of).
Or maybe there was just a problem with this specific issue that made this get closed? I can open a new issue if needed. Thanks!

**Comment by pukkandan** [comment]
The issue got automatically closed when OP was blocked for spamming

**Comment by aviv926** [comment]
Is this something that can be implemented at all?
There is no way to download a video from Google Photos other than through the official download button AFAIK

**Comment by Novgorod** [comment]
> Is this something that can be implemented at all? There is no way to download a video from Google Photos other than through the official download button AFAIK

Even after the API got nuked, video download from Google Photos is still possible and very simple. The (session-locked) URLs for all MediaItems in an album are included in the html when accessing the shared album link (MediaItems have this type of URLs: `http://lh3.googleusercontent.com/pw/<long-itemID>`). These URLs are meant to return photos with optional resolution parameters and will ordinarily only return the video thumbnail. Adding "=dv" to the URL will request the video as MP4 file download. According to the docs, it's a full-HD transcoded version with the original filename (not the origianally uploaded file, but it might depend on your "data saver" settings).

In any case, it's a very simple parsing task, but the shared album/item URL has to be requested to create a session for the MediaItem URLs and it has to be repeated when the session expires.

**Comment by DTrombett** [comment]
If no one is already working on it, I can try implementing this

**Comment by Novgorod** [comment]
> If no one is already working on it, I can try implementing this

What would be even better is a way to get the actual stream from the embedded Youtube player used for videos on Google Photos. I'm trying to find a reliable way to get the stream for embedding on other websites (because the Google Photos YT player can't be embedded). It's easy to get the MP4 file URL instead and use it as the source for a simple video player, but Google made sure to make that as painful as possible with artificial delays and rate limits.
