### ISSUE TITLE
Sponsorblock breaks when the entire video is marked as a sponsor segment

### ISSUE THREAD

**Issue by Glynax** [yt-dlp/yt-dlp#5238]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I realize this is using ytdl-sub but the dev there says this is a DLP issue specifically.
This specific video someone marked the entire video it seems as sponsored content, and that just completely breaks sponsorblock and the ytdlp command that it is using.
https://www.youtube.com/watch?v=PtPv6prY8gI

![image](https://user-images.githubusercontent.com/7043861/195671932-8b6c382a-62a2-4211-87e5-ad121deab58a.png)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
see attached
```

**Comment by pukkandan** [comment]
Copy paste log, dont give screenshot

**Comment by pukkandan** [comment]
You'll also need to explain what "breaks" in yt-dlp. The error message seems to come from ytdl-sub's code

**Comment by Glynax** [comment]
ytdlp hits an index out of range error. Sorry I'll have to recreate it one min

**Comment by pukkandan** [comment]
nvm I managed to reproduce

```
❯ yt-dlp -S +size PtPv6prY8gI --sponsorblock-remove all -v
[debug] Command-line config: ['--ignore-config', '-S', '+size', 'PtPv6prY8gI', '--sponsorblock-remove', 'all', '-v']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 6678a4f0b
[debug] Python 3.10.7 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107787-gc469c3c3b1-20220814 (fdk,setts), ffprobe N-107787-gc469c3c3b1-20220814, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1698 extractors
[debug] [youtube] Extracting URL: PtPv6prY8gI
[youtube] PtPv6prY8gI: Downloading webpage
[youtube] PtPv6prY8gI: Downloading android player API JSON
[debug] Sort order given by user: +size
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, +filesize, +fs_approx, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/474d?service=YouTube&categories=%5B%22filler%22%2C+%22intro%22%2C+%22music_offtopic%22%2C+%22preview%22%2C+%22selfpromo%22%2C+%22sponsor%22%2C+%22outro%22%2C+%22interaction%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%5D
[SponsorBlock] Found 2 segments in the SponsorBlock database
[debug] Default format spec: bestvideo*+bestaudio/best
[info] PtPv6prY8gI: Downloading 1 format(s): 597+599
[download] Having some fun in V4 (MMORPG) [PtPv6prY8gI].mp4 has already been downloaded
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Having some fun in V4 (MMORPG) [PtPv6prY8gI].mp4"
ERROR: list index out of range
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1574, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1633, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 2729, in process_video_result
    self.process_info(new_info)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 3268, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 3445, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 3427, in run_all_pps
    info = self.run_pp(pp, info)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 3406, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\postprocessor\common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\postprocessor\common.py", line 129, in wrapper
    return func(self, info)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\postprocessor\modify_chapters.py", line 41, in run
    original_duration, info['duration'] = info.get('duration'), info['chapters'][-1]['end_time']
IndexError: list index out of range
```

**Comment by pukkandan** [comment]
According to SponsorBlock docs, a full video label should be used when the entire video is sponsored. So I believe the markings in this video is wrong. But I'll make yt-dlp handle this case anyway
