### ISSUE TITLE
ABC Not working

### ISSUE THREAD

**Issue by jriker1** [yt-dlp/yt-dlp#524]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running yt-dlp version **2021.07.07**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
yt-dlp.exe --audio-quality 0 --add-metadata --ap-mso Comcast_SSO --ap-username syarbrou2 --ap-password E5ed2e20# https://abc.com/shows/general-hospital/episode-guide/2021-07/13-general-hospital-71321 -o "General Hospital S58E197.mp4" --verbose
[debug] Command-line config: ['--audio-quality', '0', '--add-metadata', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://abc.com/shows/general-hospital/episode-guide/2021-07/13-general-hospital-71321', '-o', 'General Hospital S58E197.mp4', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07
[debug] Python version 3.9.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [Go] Extracting URL: https://abc.com/shows/general-hospital/episode-guide/2021-07/13-general-hospital-71321
[Go] 13-general-hospital-71321: Downloading webpage
[Go] VDKA23864036: Downloading JSON metadata
[Go] VDKA23864036: Downloading Provider Redirect Page
[Go] VDKA23864036: Logging in
[Go] VDKA23864036: Retrieving Session
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\common.py", line 680, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3086, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
<!--
Do not remove the above ```
-->


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

ABC shows failing to download.  Worked up until maybe Monday?

**Comment by BeeMuffins** [comment]
@jriker1 Suggest editing your log as your username and password are listed.  Also, this issue with Comcast SSO could be related to #516 

However, I was able to get this to work by authenticating in a browser, saving my cookies and then using the ```--cookies``` command in addition to using ```--ap-mso```

```
yt-dlp -v -F "https://abc.com/shows/general-hospital/episode-guide/2021-07/13-general-hospital-71321" --ap-mso 'Comcast_SSO' --ap-username 'PRIVATE' --ap-password 'PRIVATE' --cookies '~/Desktop/2cookies.txt'
[debug] Command-line config: ['-v', '-F', 'https://abc.com/shows/general-hospital/episode-guide/2021-07/13-general-hospital-71321', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--cookies', '~/Desktop/2cookies.txt']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.07
[debug] Python version 3.9.6 (CPython 64bit) - macOS-11.4-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[debug] [Go] Extracting URL: https://abc.com/shows/general-hospital/episode-guide/2021-07/13-general-hospital-71321
[Go] 13-general-hospital-71321: Downloading webpage
[Go] VDKA23864036: Downloading JSON metadata
[Go] VDKA23864036: Downloading Provider Redirect Page
[Go] VDKA23864036: Confirming auto login
[Go] VDKA23864036: Retrieving Session
[Go] VDKA23864036: Retrieving Authorization Token
[Go] VDKA23864036: Retrieving Media Token
[Go] VDKA23864036: Downloading JSON metadata
[Go] VDKA23864036: Downloading m3u8 information
WARNING: [Go] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for VDKA23864036:
ID        EXT           RESOLUTION FPS |   TBR PROTO  | VCODEC        VBR ACODEC     ABR
--------- ------------- ---------- --- - ----- ------ - ----------- ----- --------- ----
ULNK_MPD  unknown_video unknown        |       http   | unknown           unknown
ULNK-217  mp4           256x144    15  |  217k m3u8_n | avc1.4d000c  217k mp4a.40.5   0k
ULNK-421  mp4           416x234    30  |  421k m3u8_n | avc1.4d000d  421k mp4a.40.5   0k
ULNK-761  mp4           640x360    30  |  761k m3u8_n | avc1.4d001e  761k mp4a.40.5   0k
ULNK-1714 mp4           960x540    30  | 1714k m3u8_n | avc1.4d001f 1714k mp4a.40.5   0k
ULNK-3590 mp4           1280x720   60  | 3590k m3u8_n | avc1.4d0020 3590k mp4a.40.5   0k
ULNK-5330 mp4           1280x720   60  | 5330k m3u8_n | avc1.640020 5330k mp4a.40.5   0k
ULNK-6326 mp4           1280x720   60  | 6326k m3u8_n | avc1.640020 6326k mp4a.40.5   0k
```

**Comment by jriker1** [comment]
Thanks and ugh. Login changed everywhere.  Anyway, I've never been able to get the cookie thing to work.  Do you have an example that does?  obviously you know how to do it but wasn't sure if you could point me to somewhere specific that I can follow.

Note I'm using python on Windows so use .exe files if that matters.

**Comment by BeeMuffins** [comment]
I used the below addon in Firefox to get my cookie file.  I was fully logged out of ABC.com, I then went to the link you are trying, logged in with Xfinity information and the video played.  Using the installed extension I then exported ALL and used the resulting file as the cookies for YT-DLP.

https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by jriker1** [comment]
OK fantastic.  So maybe a temp work around at play here.  So following your directions I was able to get the list of available streams.  If I replace yt-dlp with youtube-dl it craps out.  Looks like on the adobepass code.

ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\go.py", line 234, in _real_extract
    auth = self._extract_mvpd_auth(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\adobepass.py", line 1451, in _extract_mvpd_auth
    provider_login_page_res = post_form(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\adobepass.py", line 1365, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by 2ShedsJackson** [comment]
I had no problems downloading the video and I didn't have to bother with cookies. Maybe the problem is specific to Comcast users.

**Comment by jiangjiangflies** [comment]
> OK fantastic that method worked. So did:
> 
> yt-dlp.exe --audio-quality 0 --add-metadata --ap-mso Comcast_SSO --ap-username --ap-password https://abc.com/shows/general-hospital/episode-guide/2021-07/13-general-hospital-71321 -o "General Hospital S58E197.mp4" --cookies c:\temp\cookies.txt
> 
> That worked. However curious how long the cookies will last and if it's even using the SSO connection which it shouldn't need with the cookies. I accidently left a letter off my username and it still worked. Also why the cookies don't seem to work when run thru youtube-dl.
> 
> Also not sure if it's me but running yt-dlp directly seems slower than youtube-dl? Also seems less reliable. Maybe youtube-dl has restart capabilities? Of the five general hospital shows I had to catch up on 1 failed for some reason and one locked up and I couldn't even close the window.

Hi, I can't download abc using cookies. Does this method still work for you?
