### ISSUE TITLE
Not Finding Limelight Audio Files

### ISSUE THREAD

**Issue by Psycho9999** [yt-dlp/yt-dlp#5257]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I periodically visit pages for learningstrategies.com to download audio and/or video such as this one: https://www.learningstrategies.com/manifestationmindfest/phase3

Attempting to use yt-dlp nets me the errors below instead of downloading the content.

From my own investigation, the audio files are usually compatible with the limelight extractor, so I manually use Chrome Devtools to find channel and media ids (the former often contains groups of the later) and use commands like `yt-dlp "limelight:channel:<id>"` and `yt-dlp "limelight:media:<id>"`.  I'm able to get by with this but it's very tedious because of two quirks:

* Recently, I found `yt-dlp "limelight:channel:<id>"` not to be working, forcing me to use individual media ids.
* yt-dlp defaults to a format for live streaming video.  It's a minor inconvenience now that I know about it, but it requires me to use the arg "-f Mp3-2 / Mp3-1 / Mp3-0"

I hope I was clear enough, and thank you in advance.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vUF', 'https://www.learningstrategies.com/manifestationmindfest/phase3']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.learningstrategies.com/manifestationmindfest/phase3
[generic] phase3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] phase3: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a limelight embed
[debug] Identified a limelight:channel embed
[debug] Identified a limelight:channel_list embed
[download] Downloading playlist: Manifestation Mindfest Phase 3
[generic] Playlist Manifestation Mindfest Phase 3: Downloading 3 videos of 3
[download] Downloading video 1 of 3
ERROR: 'dict' object has no attribute 'startswith'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1876, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1609, in process_ie_result
  File "yt_dlp\utils.py", line 735, in sanitize_url
AttributeError: 'dict' object has no attribute 'startswith'

[download] Downloading video 2 of 3
ERROR: 'dict' object has no attribute 'startswith'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1876, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1609, in process_ie_result
  File "yt_dlp\utils.py", line 735, in sanitize_url
AttributeError: 'dict' object has no attribute 'startswith'

[download] Downloading video 3 of 3
ERROR: 'dict' object has no attribute 'startswith'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1876, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1609, in process_ie_result
  File "yt_dlp\utils.py", line 735, in sanitize_url
AttributeError: 'dict' object has no attribute 'startswith'

[download] Finished downloading playlist: Manifestation Mindfest Phase 3
```

**Comment by dirkf** [comment]
The Limelight extractor is confused by the [new generic arrangements for extracting embedded links](https://github.com/yt-dlp/yt-dlp/commit/bfd973ece3369c593b5e82a88cc16de80088a73e) and needs to be fixed. In particular its interface that is supposed to return a list of embedded URLs doesn't, which causes the error `'dict' object has no attribute 'startswith'`.

yt-dl still gets an adequate result:
```shellsession
$ youtube-dl -v -F 'https://www.learningstrategies.com/manifestationmindfest/phase3'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.learningstrategies.com/manifestationmindfest/phase3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[generic] phase3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] phase3: Downloading webpage
[generic] phase3: Extracting information
[download] Downloading playlist: Manifestation Mindfest Phase 3
[generic] playlist Manifestation Mindfest Phase 3: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[limelight] a4dcc1326e7e4dfda6b1cbe1bec7ca54: Downloading PlaylistService getPlaylistByMediaId JSON
[limelight] a4dcc1326e7e4dfda6b1cbe1bec7ca54: Downloading PlaylistService getMobilePlaylistByMediaId JSON
[limelight] a4dcc1326e7e4dfda6b1cbe1bec7ca54: Downloading m3u8 information
[info] Available formats for a4dcc1326e7e4dfda6b1cbe1bec7ca54:
format code           extension  resolution note
Mp3-0                 mp3        unknown    
Mp3-1                 mp3        unknown    
HttpLiveStreaming-64  mp4        unknown      64k , 30.0fps (best)
[download] Finished downloading playlist: Manifestation Mindfest Phase 3
$
```
The best format (`HttpLiveStreaming-64`) for the problem URL has a small blank video attached to the audio. To get the mp3 formats and avoid the AV format, use `-f "[ext=mp3]"` or `-f "[ext!=mp4]"`.

For devs:
1. The `LimelightBaseIE._extract_embed_urls()` method extracts a list of entries (ie, `dict`s), not a list of URL strings. Its logic wasn't changed from the perhaps confusingly named 2017-era `_extract_urls()`.
2. The method contains a nested function which presumably ought be reverted as below
```diff
-        def smuggle(url):
-            return smuggle_url(url, {'source_url': url})
+        def smuggle(a_url):
+            return smuggle_url(a_url, {'source_url': url})
```
3. The method is called once for each of its 3 derived classes, returning the same result each time, but only the first call is valid (for the problem URL). If the result can be handled differently according to the IE class, the method needs to be specialised to each of the derived classes, or otherwise behave differently in each case. If not, all but one of the derived classes need a dummy routine, or perhaps the routine to be set to `False` or `None` and filtered out by the generic processing.
4. The method might return a `limelight:channelList:...` URL that should be `limelight:channel_list:...`:
```diff
-            kind, video_id = mobj.group('kind'), mobj.group('id')
+            kind, video_id = mobj.group('kind').replace('channelList', 'channel_list'), mobj.group('id')
5. The extraction results have `video_ext` set for all formats, even the mp3 formats that only have audio; `acodec` and `vcodec` aren't set, but perhaps they're old hat.
```
