### ISSUE TITLE
Sporza (Belgium) not working

### ISSUE THREAD

**Issue by sclarebout** [yt-dlp/yt-dlp#5271]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Belgium

### Provide a description that is worded well enough to be understood

I wanted to download some videos from sporza.be website, as I used to back in 2021, but this URL fails on me
Unsupported URL: https://sporza.be/nl/matches/voetbal/jupiler-pro-league/2019-2020/regulier/03/kv-oostende-club-brugge~1562000522078/

I only installed yt-dpl on my Win10 machine using the exe, I did not change any configurations.
I use the CMD (Command Line) to run yt-dlp

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://sporza.be/nl/matches/voetbal/jupiler-pro-league/2019-2020/regulier/03/kv-oostende-club-brugge~1562000522078/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-02-16-git-8331eb058d-full_build-www.gyan.dev (setts), ffprobe 2021-02-16-git-8331eb058d-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://sporza.be/nl/matches/voetbal/jupiler-pro-league/2019-2020/regulier/03/kv-oostende-club-brugge~1562000522078/
[generic] kv-oostende-club-brugge~1562000522078: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] kv-oostende-club-brugge~1562000522078: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://sporza.be/nl/matches/voetbal/jupiler-pro-league/2019-2020/regulier/03/kv-oostende-club-brugge~1562000522078/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1553, in __extract_info
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\generic.py", line 3062, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://sporza.be/nl/matches/voetbal/jupiler-pro-league/2019-2020/regulier/03/kv-oostende-club-brugge~1562000522078/
```

**Comment by sclarebout** [comment]
I found this on another video: 
An extractor error has occurred. (caused by KeyError('data-video-id'));

When I look in the vrt.py file, I can see this line at 55. 
In the source code of the sporza site I can see this as information when starting a video:
data-videoid="vid-99dfb81a-bdb0-4bcf-ab75-2ceed69ef7e1" 

I believe changing the line in vrt.py file to 'data-videoid' might solve it...

**Comment by coletdjnz** [comment]
> I found this on another video: An extractor error has occurred. (caused by KeyError('data-video-id'));
> 
> When I look in the vrt.py file, I can see this line at 55. In the source code of the sporza site I can see this as information when starting a video: data-videoid="vid-99dfb81a-bdb0-4bcf-ab75-2ceed69ef7e1"
> 
> I believe changing the line in vrt.py file to 'data-videoid' might solve it...

Hmm yeah, might've been an oversight in https://github.com/yt-dlp/yt-dlp/commit/4de300768abeddde88c1a23a2fc7f8d308eccee8 (unless they changed the entire site back).

Both versions should be supported imo (along with the other attr variations). Going back through the youtube-dl PRs they seem to switch between the formats.

Also the `_VALID_URL` will need updating to support this url

**Comment by dirkf** [comment]
Exactly. `-id` was used until https://github.com/ytdl-org/youtube-dl/commit/82e91d20a0f698b13412dd7b200663c7485791bb, then changed to `id`, then to `-id` in https://github.com/yt-dlp/yt-dlp/commit/4de300768abeddde88c1a23a2fc7f8d308eccee8 (but kept in yt-dl), and now `id` seems to be right. Maybe both types are or have been used depending on the actual site or the time when the page was observed or both.

The yt-dl and yt-dlp VRT extractors are basically identical apart from this and conventions.

The Canvas extractors differ a bit. Both try to use an API URL whose host `mediazone.vrt.be` (also the host in the URL pattern, but never fetched) no longer resolves, before succeeding with another tactic. The yt-dlp extractor adds a `vrtnutoken` which is used in this API call, but apparently always crashes the extractor with `sporza`. The API URL is `.../v2` in yt-dlp  is seen in current pages, with no obvious difference in behaviour (but see below).

The [problem page](https://sporza.be/nl/matches/voetbal/jupiler-pro-league/2019-2020/regulier/03/kv-oostende-club-brugge~1562000522078/) is old and its URL has a different pattern. However the page structure is similar to a current page like https://sporza.be/nl/2022/10/16/bekijk-alle-doelpunten-van-de-12e-speeldag-in-de-jupiler-pro-league~1665948601519/; so probably the `_VALID_URL` is unnecessarily restrictive.

I used this:
```py
    _VALID_URL = r'https?://(?:www\.)?(?P<site>vrt\.be/vrtnws|sporza\.be)/(?:[^/]+/)+(?P<id>[^/?&#]+)'
```
Additionally, the VRT extractors only get the first matching video in a page whereas the problem page and the above current example have several videos. The extractor should search the whole page:
```py
    def _real_extract(self, url):
        site, display_id = re.match(self._VALID_URL, url).group('site', 'id')
        webpage = self._download_webpage(url, display_id)

        def entries():
            for m in re.finditer(
                    r'(<\w+\b[^>]+\bclass\s*=\s*"(?:[^"]+?\s)?vrtvideo\b[^>]*>)', webpage):
                attrs = extract_attributes(m.group(0))

                asset_id = attrs.get('data-video-id') or attrs['data-videoid']
                publication_id = dict_get(attrs, ('data-publication-id', 'data-publicationid'))
                if publication_id:
                    asset_id = publication_id + '$' + asset_id
                client = attrs.get('data-client') or self._CLIENT_MAP[site]

                entry = self.url_result(
                    'https://mediazone.vrt.be/api/v1/%s/assets/%s' % (client, asset_id),
                    ie='Canvas', video_id=asset_id, video_title=attrs.get('data-title'))
                entry.update({
                    '_type': 'url_transparent',
                    'thumbnail': attrs.get('data-posterimage'),
                    'duration': float_or_none(attrs.get('data-duration'), 1000),
                })
                yield entry

        title = strip_or_none(get_element_by_class(
            'vrt-title', webpage) or self._html_search_meta(
            ['og:title', 'twitter:title', 'name'], webpage))
        description = self._html_search_meta(
            ['og:description', 'twitter:description', 'description'], webpage)
        if description == '…':
            description = None

        result = self.playlist_result(
            entries(), playlist_id=display_id, playlist_title=title,
            playlist_description=description)
        result['timestamp'] = unified_timestamp(self._html_search_meta(
            'article:published_time', webpage))
        return result
```
With some small (but not required) pulls from the yt-dlp Canvas code and this revised error handler which addresses (a) removing the unwanted `bug_reports_message()` text from a nested exception message nested in an `ExtractorError` with `expected=True` (this should be done globally, though) (b) novel geo-location error codes from the v2 API:
```py
            except ExtractorError as e:
                if isinstance(e.cause, compat_HTTPError) and e.cause.code == 404:
                    args = list(e.args)
                    args[0] = args[0].replace(bug_reports_message(), '')
                    e.args = tuple(args)
                    raise ExtractorError(
                        'Video data not found: no longer available?',
                        cause=e, expected=True)
                raise
            if 'title' not in data:
                code = data.get('code')
                if code == 'AUTHENTICATION_REQUIRED':
                    self.raise_login_required()
                elif code == 'INVALID_LOCATION':
                    self.raise_geo_restricted(countries=['BE'])
                elif code.startswith('CONTENT_AVAILABLE_ONLY_'):
                    self.raise_geo_restricted(
                        msg=' '.join(x.title() if ii == 0
                                     else x.lower() if ii < 4 or len(x) > 2
                                     else x
                                     for ii, x in enumerate(code.split('_'))),
                        countries=code.split('_')[4:5])
                raise ExtractorError(data.get('message') or code, expected=True)
```
the problem page just gets 404s, presumably because the content has expired
```shellsession
$ python3.9 -m youtube_dl -F 'https://sporza.be/nl/matches/voetbal/jupiler-pro-league/2019-2020/regulier/03/kv-oostende-club-brugge~1562000522078/' --ignore-errors --playlist-end 2
[VRT] kv-oostende-club-brugge~1562000522078: Downloading webpage
[download] Downloading playlist: Invallers Tau en Okereke kruiden Brugse zege aan zee
[VRT] playlist Invallers Tau en Okereke kruiden Brugse zege aan zee: Downloading 2 videos
[download] Downloading video 1 of 2
[Canvas] pbs-pub-6185a3c6-93de-4a4d-80ed-ae02dd0c020a$vid-d2dac3ea-c778-46c1-a03c-d019a6b361a2: Downloading token
[Canvas] pbs-pub-6185a3c6-93de-4a4d-80ed-ae02dd0c020a$vid-d2dac3ea-c778-46c1-a03c-d019a6b361a2: Downloading video JSON
ERROR: Video data not found: no longer available? (caused by ExtractorError("Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>)"))
[download] Downloading video 2 of 2
[Canvas] pbs-pub-6185a3c6-93de-4a4d-80ed-ae02dd0c020a$vid-0992bab0-cecd-477e-a761-316144e437e4: Downloading token
[Canvas] pbs-pub-6185a3c6-93de-4a4d-80ed-ae02dd0c020a$vid-0992bab0-cecd-477e-a761-316144e437e4: Downloading video JSON
ERROR: Video data not found: no longer available? (caused by ExtractorError("Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>)"))
[download] Finished downloading playlist: Invallers Tau en Okereke kruiden Brugse zege aan zee
$
```
but the current page is more successful using API v1
```shellsession
$ python3.9 -m youtube_dl -v -F 'https://sporza.be/nl/2022/10/16/bekijk-alle-doelpunten-van-de-12e-speeldag-in-de-jupiler-pro-league~1665948601519/' --ignore-errors --playlist-items 3-4
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://sporza.be/nl/2022/10/16/bekijk-alle-doelpunten-van-de-12e-speeldag-in-de-jupiler-pro-league~1665948601519/', '--ignore-errors', '--playlist-items', '3-4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: fdb16c0d6
[debug] Python version 3.9.14 (CPython) - Linux-4.4.0-210-generic-i686-with-glibc2.23
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[VRT] bekijk-alle-doelpunten-van-de-12e-speeldag-in-de-jupiler-pro-league~1665948601519: Downloading webpage
[download] Downloading playlist: Bekijk alle doelpunten van de 12e speeldag in de Jupiler Pro League
[VRT] playlist Bekijk alle doelpunten van de 12e speeldag in de Jupiler Pro League: Downloading 2 videos
[download] Downloading video 1 of 2
[Canvas] pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-0ddd6273-ca17-4d0b-920b-953a0c4548de: Downloading token
[Canvas] pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-0ddd6273-ca17-4d0b-920b-953a0c4548de: Downloading video JSON
[Canvas] pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-0ddd6273-ca17-4d0b-920b-953a0c4548de: Downloading MPD manifest
[Canvas] pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-0ddd6273-ca17-4d0b-920b-953a0c4548de: Downloading m3u8 information
[info] Available formats for pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-0ddd6273-ca17-4d0b-920b-953a0c4548de:
format code              extension  resolution note
MPEG_DASH-audio_1=64013  m4a        audio only DASH audio   64k , m4a_dash container, mp4a.40.5 (48000Hz)
MPEG_DASH-audio=96012    m4a        audio only DASH audio   96k , m4a_dash container, mp4a.40.2 (48000Hz)
MPEG_DASH-video=551669   mp4        480x270    DASH video  551k , mp4_dash container, avc1.4D401F, 25fps, video only
MPEG_DASH-video=902299   mp4        640x360    DASH video  902k , mp4_dash container, avc1.4D401F, 25fps, video only
MPEG_DASH-video=1303394  mp4        768x432    DASH video 1303k , mp4_dash container, avc1.4D401F, 25fps, video only
MPEG_DASH-video=2205483  mp4        960x540    DASH video 2205k , mp4_dash container, avc1.4D401F, 25fps, video only
HLS-653                  mp4        480x270     653k , avc1.4D401F@ 551k, 25.0fps, mp4a.40.5@ 64k
HLS-1059                 mp4        640x360    1059k , avc1.4D401F@ 902k, 25.0fps, mp4a.40.2@ 96k
HLS-1484                 mp4        768x432    1484k , avc1.4D401F@1303k, 25.0fps, mp4a.40.2@ 96k
HLS-2440                 mp4        960x540    2440k , avc1.4D401F@2205k, 25.0fps, mp4a.40.2@ 96k (best)
[download] Downloading video 2 of 2
[Canvas] pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-8b9a0eb5-0cae-493f-98a3-a30aafb6ce7d: Downloading token
[Canvas] pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-8b9a0eb5-0cae-493f-98a3-a30aafb6ce7d: Downloading video JSON
ERROR: This video is not available from your location due to geo restriction
This video is available in Belgium.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/home/df/Documents/src/youtube-dl/youtube_dl/YoutubeDL.py", line 816, in wrapper
    return func(self, *args, **kwargs)
  File "/home/df/Documents/src/youtube-dl/youtube_dl/YoutubeDL.py", line 837, in __extract_info
    ie_result = ie.extract(url)
  File "/home/df/Documents/src/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/df/Documents/src/youtube-dl/youtube_dl/extractor/canvas.py", line 92, in _real_extract
    self.raise_geo_restricted(countries=['BE'])
  File "/home/df/Documents/src/youtube-dl/youtube_dl/extractor/common.py", line 947, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
youtube_dl.utils.GeoRestrictedError: This video is not available from your location due to geo restriction

[download] Finished downloading playlist: Bekijk alle doelpunten van de 12e speeldag in de Jupiler Pro League
$
```
Moving to v2, all the UK-visible media links that were found with v1 and succeeded with `--test` are blocked. Presumably an "expat" token is necessary, or v2 is post-Brexit:
```shellsession
$ python3.9 -m youtube_dl -F 'https://sporza.be/nl/2022/10/16/bekijk-alle-doelpunten-van-de-12e-speeldag-in-de-jupiler-pro-league~1665948601519/' --ignore-errors --playlist-items 3-4
[VRT] bekijk-alle-doelpunten-van-de-12e-speeldag-in-de-jupiler-pro-league~1665948601519: Downloading webpage
[download] Downloading playlist: Bekijk alle doelpunten van de 12e speeldag in de Jupiler Pro League
[VRT] playlist Bekijk alle doelpunten van de 12e speeldag in de Jupiler Pro League: Downloading 2 videos
[download] Downloading video 1 of 2
[Canvas] pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-0ddd6273-ca17-4d0b-920b-953a0c4548de: Downloading token
[Canvas] pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-0ddd6273-ca17-4d0b-920b-953a0c4548de: Downloading video JSON
ERROR: Content available only for BE residents and expats
This video is available in Belgium.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
[download] Downloading video 2 of 2
[Canvas] pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-8b9a0eb5-0cae-493f-98a3-a30aafb6ce7d: Downloading token
[Canvas] pbs-pub-ce83f448-24d5-460a-b3a2-62a00f6f4ee3$vid-8b9a0eb5-0cae-493f-98a3-a30aafb6ce7d: Downloading video JSON
ERROR: Content available only in BE
This video is available in Belgium.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
[download] Finished downloading playlist: Bekijk alle doelpunten van de 12e speeldag in de Jupiler Pro League
$
```
Obviously there are some issues to resolve here, probably easiest for someone in-region. One major thing is to get `vrtnutoken` working or at least not crashing sporza (etc) extractions; another is to determine if there's a valid current equivalent of `media.virtzone.be` that should be used in the Canvas extractor's URL pattern. Maybe it should just have (with appropriate changes elsewhere):
```py
    _VALID_URL = r'canvas:(?P<site_id>canvas|een|ketnet|vrt(?:video|nieuws)|sporza|dako):(?P<id>[^/?#&]+)'
```

**Comment by sclarebout** [comment]
Someone able to work on this one please? Would be such a life saver, thanks!
