### ISSUE TITLE
Embedding thumbnails in mp3 fails

### ISSUE THREAD

**Issue by stizzlestizzle** [yt-dlp/yt-dlp#5287]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When trying to convert e.g. the YT video referenced in the log output to an mp3 file, yt-dlp fails with this error message:

`ERROR: Postprocessing:   Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1280x720, q=2-31, 200 kb/s, -nan fps`,

Both the mp3 and webp file are available though. But the thumbnail is not embedded and further processing fails due to the error exit code.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.8.14 (CPython 64bit) - Linux-5.15.74-0-lts-x86_64-with 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=xI6dqImaQ50
[youtube] xI6dqImaQ50: Downloading webpage
======== Running on http://0.0.0.0:8081 ========
(Press CTRL+C to quit)
[youtube] xI6dqImaQ50: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
INFO:aiohttp.access:192.168.10.182 [19/Oct/2022:12:34:20 +0000] "POST /add HTTP/1.1" 200 265 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0"
INFO:ytdl:downloading Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere]
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.8.14 (CPython 64bit) - Linux-5.15.74-0-lts-x86_64-with 
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=xI6dqImaQ50
[youtube] xI6dqImaQ50: Downloading webpage
[youtube] xI6dqImaQ50: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] xI6dqImaQ50: Downloading 1 format(s): 251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: /downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webp
[debug] Invoking http downloader on "https://rr3---sn-5hnednsz.googlevideo.com/videoplayback?expire=1666204463&ei=z-5PY6nULJrtgAeivqjIBQ&ip=185.XXX.XXX.XXX&id=o-ALOxhxE0fy_-3FWoXv1ClITy0QByCcr_NpzE6ZRihgRy&itag=251&source=youtube&requiressl=yes&mh=Ah&mm=31%2C29&mn=sn-5hnednsz%2Csn-5hne6n6e&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1100000&spc=yR2vp1UOvgkianGTTNsHmCNeZ7Xz0c4&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=2956753&dur=178.841&lmt=1592988385675114&mt=1666182326&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJJq6LHN7KdXh5c7imDRS2VAAneuF4_VpXLHkjjbWvibAiAqltKinSfuRPwHyrbAJc4BLkbc3lXC5wJE5chCenHJWQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgSD3e02-f651PAcyXl8WvIw019UMD9kxbuVsnLtstcuMCIQD4GIcNlaWWlvvzvkY3Ktp5_HcJxi4S3keTcS91p8h-NA%3D%3D"
[download] Destination: /downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webm
[download]   0.0% of    2.82MiB at  151.84KiB/s ETA 00:19
[download]   0.1% of    2.82MiB at  338.25KiB/s ETA 00:08
[download]   0.2% of    2.82MiB at  744.82KiB/s ETA 00:03
[download]   0.5% of    2.82MiB at    1.47MiB/s ETA 00:01
[download]   1.1% of    2.82MiB at  885.21KiB/s ETA 00:03
[download]   2.2% of    2.82MiB at    1.02MiB/s ETA 00:02
[download]   4.4% of    2.82MiB at    1.41MiB/s ETA 00:01
[download]   8.8% of    2.82MiB at    2.13MiB/s ETA 00:01
[download]  17.7% of    2.82MiB at    3.40MiB/s ETA 00:00
[download]  35.4% of    2.82MiB at    3.20MiB/s ETA 00:00
[download]  70.9% of    2.82MiB at    6.06MiB/s ETA 00:00
[download] 100.0% of    2.82MiB at    6.38MiB/s ETA 00:00
[download] 100% of    2.82MiB in 00:00:00 at 5.09MiB/s   
[debug] ffmpeg command line: ffprobe -show_streams 'file:/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webm'
[ExtractAudio] Destination: /downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webm' -vn -acodec libmp3lame -q:a 0.0 -movflags +faststart 'file:/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].mp3'
Deleting original file /downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webm (pass -k to keep)
[Metadata] Adding metadata to "/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].mp3' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere]' -metadata date=20200110 -metadata 'description=Subscribe to the channel for all the latest releases: https://mosr.lnk.to/YTSubscribe

Follow Ministry of Sound:
https://www.instagram.com/ministryofsound
http://www.facebook.com/ministryofsound 
http://www.twitter.com/ministryofsound 
http://www.ministryofsound.com 

������
Follow Hosh:
Instagram: https://www.instagram.com/hosh.me/
Facebook: https://www.facebook.com/hosh.me
Twitter: https://twitter.com/hosh_tag

Lyrics:
[Verse]
Are you, are you coming here with me
To run by my side so we can be free?
Strange things do happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you, are you coming here with me
To run by my side so we can free?
Strange things do happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you, are you coming here with me
To run by my side so we can be free?
Strange things d0 happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you (Are you), are you (Are you) coming here with me
To run by my side so we can be free?
Strange things do happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you (Are you), are you (Are you) coming here with me
To run by my side so we can be free?
Strange things do happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree

[Interlude]
Are you, are you coming here with me
To run by my side so we can be free?
Strange things do happen here
It'"'"'s the time to leave
If we met at midnight

[Verse]
Are you, are you coming here with me
To run by my side so we can be free?
Strange things d0 happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you (Oh-oh), are you (Oh-oh) coming here with me
To run by my side so we can free?
Strange things do happen here (Ooh)
It'"'"'s the time to leave
If we met at midnight at the willow tree

[Bridge]
Oh, oh, oh
Oh, oh, oh

[Verse]
Are you, are you coming here with me
To run by my side so we can free?
Strange things d0 happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you (Oh-oh), are you (Oh-oh) coming here with me
To run by my side so we can free?
Strange things d0 happen here (Oh-oh-oh)
It'"'"'s the time to leave
If we met at midnight at the willow tree

#ministryofsound #ministryofsoundrecords #ministryofsound2020 #hosh #midnight #hangingtree #music #newmusic #newmusicvideo #ministryofsoundanthems #ministryofsoundmixes' -metadata 'synopsis=Subscribe to the channel for all the latest releases: https://mosr.lnk.to/YTSubscribe

Follow Ministry of Sound:
https://www.instagram.com/ministryofsound
http://www.facebook.com/ministryofsound 
http://www.twitter.com/ministryofsound 
http://www.ministryofsound.com 

������
Follow Hosh:
Instagram: https://www.instagram.com/hosh.me/
Facebook: https://www.facebook.com/hosh.me
Twitter: https://twitter.com/hosh_tag

Lyrics:
[Verse]
Are you, are you coming here with me
To run by my side so we can be free?
Strange things do happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you, are you coming here with me
To run by my side so we can free?
Strange things do happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you, are you coming here with me
To run by my side so we can be free?
Strange things d0 happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you (Are you), are you (Are you) coming here with me
To run by my side so we can be free?
Strange things do happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you (Are you), are you (Are you) coming here with me
To run by my side so we can be free?
Strange things do happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree

[Interlude]
Are you, are you coming here with me
To run by my side so we can be free?
Strange things do happen here
It'"'"'s the time to leave
If we met at midnight

[Verse]
Are you, are you coming here with me
To run by my side so we can be free?
Strange things d0 happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you (Oh-oh), are you (Oh-oh) coming here with me
To run by my side so we can free?
Strange things do happen here (Ooh)
It'"'"'s the time to leave
If we met at midnight at the willow tree

[Bridge]
Oh, oh, oh
Oh, oh, oh

[Verse]
Are you, are you coming here with me
To run by my side so we can free?
Strange things d0 happen here
It'"'"'s the time to leave
If we met at midnight at the willow tree
Are you (Oh-oh), are you (Oh-oh) coming here with me
To run by my side so we can free?
Strange things d0 happen here (Oh-oh-oh)
It'"'"'s the time to leave
If we met at midnight at the willow tree

#ministryofsound #ministryofsoundrecords #ministryofsound2020 #hosh #midnight #hangingtree #music #newmusic #newmusicvideo #ministryofsoundanthems #ministryofsoundmixes' -metadata 'purl=https://www.youtube.com/watch?v=xI6dqImaQ50' -metadata 'comment=https://www.youtube.com/watch?v=xI6dqImaQ50' -metadata 'artist=Ministry of Sound' -movflags +faststart 'file:/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].temp.mp3'
[ThumbnailsConvertor] Converting thumbnail "/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webp' -movflags +faststart 'file:/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].png'
[debug] ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219
  configuration: --prefix=/usr --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --disable-debug
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, image2, from 'file:/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webp':
  Duration: 00:00:00.04, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 1280x720, 25 fps, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (webp (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'file:/downloads/Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].png':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1280x720, q=2-31, 200 kb/s, -nan fps, 
ERROR: Postprocessing:   Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1280x720, q=2-31, 200 kb/s, -nan fps,
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3272, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3449, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3431, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3410, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/embedthumbnail.py", line 86, in run
    thumbnail_filename = convertor.convert_thumbnail(thumbnail_filename, 'png')
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 1093, in convert_thumbnail
    self.real_run_ffmpeg(
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 361, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1280x720, q=2-31, 200 kb/s, -nan fps,

INFO:ytdl:waiting for item to download
```

**Comment by pukkandan** [comment]
Are you using some wrapper? Or did you just miss the first line of the log? Either way, you need to show me the options being passed to yt-dlp

**Comment by pukkandan** [comment]
My guess is that u r running this
```
❯ yt-dlp -x --embed-thumb --audio-format mp3 xI6dqImaQ50 -v
[debug] Command-line config: ['--ignore-config', '-x', '--embed-thumb', '--audio-format', 'mp3', 'xI6dqImaQ50', '-v']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 62e451334
[debug] Python 3.10.8 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107787-gc469c3c3b1-20220814 (fdk,setts), ffprobe N-107787-gc469c3c3b1-20220814, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1699 extractors
[debug] [youtube] Extracting URL: xI6dqImaQ50
[youtube] xI6dqImaQ50: Downloading webpage
[youtube] xI6dqImaQ50: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] xI6dqImaQ50: Downloading 1 format(s): 251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webp
[debug] Invoking http downloader on "https://rr3---sn-gwpa-jv36.googlevideo.com/videoplayback?expire=1666205189&ei=pfFPY7-rBqi-rtoP9KmEsAE&ip=49.37.235.98&id=o-AE3RC8GFtcvHyMvk-4EEW32HdE5a4bv7-cG_HneY6kJF&itag=251&source=youtube&requiressl=yes&mh=Ah&mm=31%2C29&mn=sn-gwpa-jv36%2Csn-gwpa-h55r&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=335000&spc=yR2vpyHrWJiV96keMIQyE0qbmCc9Nfk&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=2956753&dur=178.841&lmt=1592988385675114&mt=1666183051&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgMJUQYSbjSnWa0D3E4DJiAdGY4YSzc9QfDxmMgoGMKgsCIQCy8Br6coXFQG37B9iU3gg7bt57F536dxe2zsenEFq_Tg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJjKlgWlhnkp8giE5t-J6xCz-EodIfuTVxUFt-3ca9JKAiA8UksWWtkaAErB2RO4OkGn_A5LUWNdAtpbRUy2z54eRQ%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webm
[download] 100% of    2.82MiB in 00:00:00 at 3.48MiB/s
[debug] ffmpeg command line: ffprobe -show_streams "file:Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webm"
[ExtractAudio] Destination: Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webm" -vn -acodec libmp3lame "-q:a" 5.0 -movflags "+faststart" "file:Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].mp3"
Deleting original file Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webm (pass -k to keep)
[ThumbnailsConvertor] Converting thumbnail "Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -f image2 -pattern_type none -i "file:Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].webp" -movflags "+faststart" "file:Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].png"
[EmbedThumbnail] ffmpeg: Adding thumbnail to "Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].mp3" -i "file:Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].png" -c copy -map "0:0" -map "1:0" -write_id3v1 1 -id3v2_version 3 "-metadata:s:v" "title=\"Album cover\"" "-metadata:s:v" "comment=Cover (front)" -movflags "+faststart" "file:Hosh & 1979 - Midnight (Hanging Tree) feat. Jalja [Track Premiere] [xI6dqImaQ50].temp.mp3"
```

but as u can see, that does not repro the issue
