### ISSUE TITLE
Crunchyroll URL change is breaking extractor identification (i believe)

### ISSUE THREAD

**Issue by MGullefer1** [yt-dlp/yt-dlp#5292]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

I believe the issue is that crunchyroll has recently changed the url from https://beta.crunchyroll.com to just https://www.crunchyroll.com. I have no idea if this is the _only_ issue but that's what the error log looks like to me, and I know it used to work with the former link type. 
I've tried to just manually change the url to https://beta.crunchyroll.com instead but that site doesn't exist anymore.
If the only change is the url I can't see why this would be a huge endeavor to fix. The website visually looks the exact same but of course that's not necessarily the whole story.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.crunchyroll.com/watch/GQJUGJ2K5/a-new-family-member']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-06-30-git-03b2ed9a50-full_build-www.gyan.dev (setts), ffprobe 2022-06-30-git-03b2ed9a50-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.crunchyroll.com/watch/GQJUGJ2K5/a-new-family-member
[generic] a-new-family-member: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] a-new-family-member: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.crunchyroll.com/watch/GQJUGJ2K5/a-new-family-member
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1553, in __extract_info
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\generic.py", line 3062, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.crunchyroll.com/watch/GQJUGJ2K5/a-new-family-member
```

**Comment by pukkandan** [comment]
@Grub4K @tejing1

**Comment by tejing1** [comment]
Looks like beta isn't beta anymore. It should be a simple enough fix.

**Comment by tejing1** [comment]
Ugh. It looks like a spoke too soon. I'm getting cloudflare blocking on the main api accesses...

**Comment by Trit34** [comment]
Not fixed for me (with the latest version of the extractor):

```
$ yt-dlp -Fvv https://www.crunchyroll.com/fr/watch/G9DUEDNG0/being-prepared-to-be-hurt
[debug] Command-line config: ['-Fvv', 'https://www.crunchyroll.com/fr/watch/G9DUEDNG0/being-prepared-to-be-hurt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] API
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.2-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/fr/watch/G9DUEDNG0/being-prepared-to-be-hurt
[crunchyroll] 0: Downloading webpage
ERROR: [crunchyroll] 0: Received a beta page from non-beta url when not logged in.; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/crunchyroll.py", line 429, in _real_extract
    return self._redirect_to_beta(webpage, CrunchyrollBetaIE.ie_key(), video_id)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/crunchyroll.py", line 95, in _redirect_to_beta
    raise ExtractorError('Received a beta page from non-beta url when not logged in.')

$ yt-dlp -Fvv https://beta.crunchyroll.com/fr/watch/G9DUEDNG0/being-prepared-to-be-hurt
[debug] Command-line config: ['-Fvv', 'https://beta.crunchyroll.com/fr/watch/G9DUEDNG0/being-prepared-to-be-hurt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] API
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.2-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/fr/watch/G9DUEDNG0/being-prepared-to-be-hurt
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with grant_type=client_id
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] being-prepared-to-be-hurt: Retrieving episode metadata
ERROR: [crunchyroll:beta] G9DUEDNG0: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/crunchyroll.py", line 816, in _real_extract
    episode_response = self._download_json(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1032, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 996, in download_handle
    res = self._download_webpage_handle(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 866, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 823, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 805, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3682, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
Hence why the issue is OPEN!

**Comment by tunaflsh** [comment]
I've installed the changes in #5294. And it did work for some episodes but sometimes I'm getting error "Remote end closed connection without response". Is this related to this issue?

**Comment by SebiAi** [comment]
@pukkandan If you need a premium account to test please feel free to reply!
