### ISSUE TITLE
[New Site] churchofjesuschrist.org (Brightcove backend videos)

### ISSUE THREAD

**Issue by minchinweb** [yt-dlp/yt-dlp#5295]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

https://www.churchofjesuschrist.org/broadcasts/watch/lethbridge-alberta-member-devotional/2022/10?lang=eng

### Provide a description that is worded well enough to be understood

Would like to download this video, but `yt-dlp` can't seem to find the actual video file.

The debug logs suggest that the existing Brightcove extractor is tried but not working.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
> yt-dlp -vU https://www.churchofjesuschrist.org/broadcasts/watch/lethbridge-alberta-member-devotional/2022/10?lang=eng
[debug] Command-line config: ['-vU', 'https://www.churchofjesuschrist.org/broadcasts/watch/lethbridge-alberta-member-devotional/2022/10?lang=eng']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.6 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.churchofjesuschrist.org/broadcasts/watch/lethbridge-alberta-member-devotional/2022/10?lang=eng
[generic] 10?lang=eng: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 10?lang=eng: Extracting information
[debug] Looking for Brightcove embeds
[download] Downloading playlist: Lethbridge Alberta Member Devotional
[generic] Playlist Lethbridge Alberta Member Devotional: Downloading 1 videos of 1
[download] Downloading video 1 of 1
[debug] [brightcove:legacy] Extracting URL: http://c.brightcove.com/services/viewer/federated_f9/710874264001?isVid=1&isUI=1&playerKey=&videoId=#__youtubedl_smuggle=%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.churchofjesuschrist.org%2Fbroadcasts%2Fwatch%2Flethbridge-alberta-member-devotional%2F2022%2F10%3Flang%3Deng%22%7D
ERROR: Unsupported URL: http://c.brightcove.com/services/viewer/federated_f9/710874264001?isVid=1&isUI=1&playerKey=&%40videoPlayer=
Traceback (most recent call last):
  File "C:\Users\William\.local\pipx\venvs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\William\.local\pipx\venvs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\William\.local\pipx\venvs\yt-dlp\lib\site-packages\yt_dlp\extractor\common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\William\.local\pipx\venvs\yt-dlp\lib\site-packages\yt_dlp\extractor\brightcove.py", line 336, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: http://c.brightcove.com/services/viewer/federated_f9/710874264001?isVid=1&isUI=1&playerKey=&%40videoPlayer=

[download] Finished downloading playlist: Lethbridge Alberta Member Devotional
```

**Comment by MinchinWeb** [comment]
I was able to download the video using `yt-dlp "http://players.brightcove.net/710857117001/default_default/index.html?videoId=6313308990112"`

**Comment by coletdjnz** [comment]
brightcove video id and other details can be extracted from the website

```
<script type="text/javascript">
        LDS.mediaList["broadcast"] = {
            "type":"nbc","fallback":"nbc","autoLoad":"true",
            "params": {
                "autoStart":true,"linkBaseURL":"https://www.churchofjesuschrist.org/broadcasts/watch/lethbridge-alberta-member-devotional/2022/10?lang=eng&vid",
                "@videoPlayer":"6313308990112",
                "playerID":"",
                "playerKey":"",
                "player":"default",
                "videoID":6313308990112,"account":"710857117001",
                "secureConnections":"true"
            }
        };
 ```
        
then just a matter of passing off to the brighcove extractor.

**Comment by pzhlkj6612** [comment]
Parts of the website have been rebuilt and the link posted by OP is 404 for now.

Here is another example:

Video Collections / Broadcast and Live Event Recordings / General Conference / October 2022 / Saturday Morning Session: https://www.churchofjesuschrist.org/media/video/2022-10-1000-saturday-morning-session

![Screenshot of a webpage of www.churchofjesuschrist.org containing a video](https://github.com/user-attachments/assets/6c073553-7ded-498f-a85f-ed358e951115)

We are able to download mp4 video and vtt subtitle files by clicking links on the webpage. Do we need an extractor for this site?

**Comment by mrFlamel** [comment]
To confirm, the website has download button (even all other videos outside /media) and generic can download videos (from /media), so I would think this issue can be closed.

**Comment by pzhlkj6612** [comment]
> To confirm, the website has download button (even all other videos outside /media) and generic can download videos (from /media), so I would think this issue can be closed.

Yes, I agree.

> Here is another example:
> 
> Video Collections / Broadcast and Live Event Recordings / General Conference / October 2022 / Saturday Morning Session: https://www.churchofjesuschrist.org/media/video/2022-10-1000-saturday-morning-session

The player plays videos on YouTube, while the download link points to files on that website:

```console
$ curl -s -I \
>   'https://assets.churchofjesuschrist.org/11b85b5941c911edaac0eeeeac1e6e2551670733-1080p-en.mp4?download=true'
HTTP/1.1 200 OK
Content-Type: video/mp4
Content-Length: 1993633675
...

$ ffprobe -hide_banner \
>   'https://assets.churchofjesuschrist.org/11b85b5941c911edaac0eeeeac1e6e2551670733-1080p-en.mp4?download=true'
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://assets.churchofjesuschrist.org/11b85b5941c911edaac0eeeeac1e6e2551670733-1080p-en.mp4?download=true':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Saturday Morning Session
    composer        : The Church of Jesus Christ of Latter-day Saints
    encoder         : Lavf60.16.100
    description     : The Saturday Morning Session of the 192nd Semiannual General Conference of The Church of Jesus Christ of Latter-day Saints on October 1-2, 2022.
    track           : 1000
  Duration: 01:55:44.40, start: 0.000000, bitrate: 2296 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2191 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      handler_name    : ETI ISO Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : Elemental H.264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s (default)
    Metadata:
      handler_name    : ETI ISO Audio Media Handler
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)
    Metadata:
      handler_name    : SubtitleHandler

```

The title can be renamed back to the original one and the PR can be closed as I believe that our generic extractor is able to handle it.
