### ISSUE TITLE
[BiliIntl] unable to extract initialState

### ISSUE THREAD

**Issue by cx410** [yt-dlp/yt-dlp#5305]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Bug in bilibili

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.bilibili.tv/id/play/1066030/12615020
[debug] Command-line config: ['-vU', 'https://www.bilibili.tv/id/play/1066030/12615020']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.9.15 (CPython 64bit) - Linux-5.15.0-50-generic-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [BiliIntl] Extracting URL: https://www.bilibili.tv/id/play/1066030/12615020
[BiliIntl] 12615020: Downloading webpage
WARNING: [BiliIntl] unable to extract initialState; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1553, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/bilibili.py", line 1066, in _real_extract
    or self._search_nuxt_data(webpage, video_id, 'initialState', fatal=False, traverse=None))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1646, in _search_nuxt_data
    js, arg_keys, arg_vals = self._search_regex(
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by HobbyistDev** [comment]
I think the error occured because bilibili webpage structure didn't same as `search_nuxtjs_data` expected.

The webpage return something like this:
```
window.__initialState = (function(a, b, c, d, ...) {
		O.mid = "2020420289";
		O.name = "Ren_Ito";
		O.face = "https:\u002F\u002Fpic.bstarstatic.com\u002Fface\u002F6849dca492d49d71bccf27016344a53d1182af6d.jpg";
		...
		return { ...
```

But the `search_nuxtjs_data` expect like this:
https://github.com/yt-dlp/yt-dlp/blob/c13a301a94e84d581817a534875e4e2a5c0fdf19/yt_dlp/extractor/common.py#L1647

**Comment by pukkandan** [comment]
Difficult to say whether search_nuxtjs_data can be easily improved to handle this. If not, parsing it with `JSInterpreter` should work

**Comment by andrizan** [comment]
any updates on this issue?

**Comment by Movisivi** [comment]
I had to rely on using sites like https://youtube4kdownloader.com/en58/ to download this like a basic bitch

**Comment by hanahaneull** [comment]
Skipping `initialState` extraction seems works like a charm, but it might broke other bilibili extractor (live,audio,etc).
Maybe if we already know the `season_id` and `ep_id` we can skip the `initialState` extraction for the fix, I might be wrong tho' since I don't use yt-dlp/bilibili in general.

Hot fix:
Comment line `984-988` in ``/extractor/bilibili.py``
```python
        # initial_data = (
        #     self._search_json(r'window\.__INITIAL_(?:DATA|STATE)__\s*=', webpage, 'preload state', video_id, default={})
        #     or self._search_nuxt_data(webpage, video_id, '__initialState', fatal=False, traverse=None))
        # video_data = traverse_obj(
        #     initial_data, ('OgvVideo', 'epDetail'), ('UgcVideo', 'videoData'), ('ugc', 'archive'), expected_type=dict)
```
Replace line ``990``
```python
        if season_id and not video_data:
```
to
```python
        if season_id:
```

Logs:
```
[debug] Command-line config: ['-vU', 'https://www.bilibili.tv/id/play/1066030/12615020?bstar_from=bstar-web.pgc-video-detail.episode.all']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] API
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.5-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [BiliIntl] Extracting URL: https://www.bilibili.tv/id/play/1066030/12615020?bstar_from=bstar-web.pgc-video-detail.episode.all
[BiliIntl] 12615020: Downloading webpage
[BiliIntl] 12615020: Downloading JSON metadata
[BiliIntl] 12615020: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntl] 12615020: Downloading subtitles list
[BiliIntl] 12615020: Downloading subtitles for English
[BiliIntl] 12615020: Downloading subtitles for ภาษาไทย
[BiliIntl] 12615020: Downloading subtitles for Tiếng Việt
[BiliIntl] 12615020: Downloading subtitles for Bahasa Indonesia
[BiliIntl] 12615020: Downloading subtitles for Bahasa Melayu
[BiliIntl] 12615020: Downloading subtitles for 中文（简体）
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 12615020: Downloading 1 format(s): 6+2
[debug] Invoking http downloader on "xxx"
[download] Destination: E1 - The Youth about Running Around [12615020].f6.mp4
[download]   4.6% of   83.47MiB at    2.14MiB/s ETA 00:37
```

**Comment by pukkandan** [comment]
Fixed by https://github.com/yt-dlp/yt-dlp/commit/f7fc8d39e99d5b0683ac48a876618a5495a9ef5e
