### ISSUE TITLE
ThumbnailsConvertor creates additional percent signs in filenames

### ISSUE THREAD

**Issue by mkhl** [yt-dlp/yt-dlp#5307]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

calling yt-dlp with `--embed-thumbnail` converts the thumbnail to png, but during conversion (`ThumbnailsConvertor`) it changes the filename: every `%` (percent sign) in the filename is replaced with `%%` (two percent signs). this leads to errors during embedding (`EmbedThumbnail`) because the thumbnail to embed cannot be found. because the converted file has a different name.

files created by the command i ran for the output below:
```
Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].mp4
Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].webp
Anodyne [Any%% (Glitchless) + Any%%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].png
```

any file with a percent sign in the title should reproduce the bug; in addition to the one reported below i see it with https://www.youtube.com/watch?v=bpe94wgM4rY and https://www.youtube.com/watch?v=GFCczXsi-0U

as for duplicates i found #297 which was about a similar problem but not the same one, and which had been fixed in the past

i used the `--format=worst[ext=mp4]` option just so the download would go faster :)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--embed-thumbnail', '--format=worst[ext=mp4]', 'https://www.youtube.com/watch?v=LPbs5Fguh-E']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] API
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.2-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=LPbs5Fguh-E
[youtube] LPbs5Fguh-E: Downloading webpage
[youtube] LPbs5Fguh-E: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] LPbs5Fguh-E: Downloading 1 format(s): 18
[info] Downloading video thumbnail 45 ...
[info] Writing video thumbnail 45 to: Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].webp
[debug] Invoking http downloader on "https://rr3---sn-4g5ednz7.googlevideo.com/videoplayback?expire=1666287778&ei=QjRRY6i-Acru-gb4vajoDg&ip=2003%3Ac7%3Acf19%3A9800%3Adb1b%3A795b%3Ab720%3Abdff&id=o-AL1v-0TzHPu2_EO3Q_MGrPp64FLMdM2Vcw2hVLRTMk5M&itag=18&source=youtube&requiressl=yes&mh=Sz&mm=31%2C29&mn=sn-4g5ednz7%2Csn-4g5lzned&ms=au%2Crdu&mv=m&mvi=3&pl=36&initcwndbps=1768750&spc=yR2vp6HlbcdLkoXePS52KosrERyXfJo&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=4530.329&lmt=1664135259987088&mt=1666265827&fvip=2&fexp=24001373%2C24007246&c=ANDROID&txp=6319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAI3Qj_xh1eITurhZUGm9t8glk46BVkTVHVHOZgBSIOaYAiEA1qUtc-AuRH6vyqJjzm6UjE5bh6wJ5b8-JTHKvoWky3A%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgVHowMPSADf_ITeoT7cYorsc4wWkwf-6WmRYvAhQDLPwCIBbiUm8dYFwoXc9YZMXy6t7o4V1J3E7qH0-Ds2NjxlB8"
[download] Destination: Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].mp4
[download] 100% of  222.63MiB in 00:00:22 at 9.70MiB/s
[ThumbnailsConvertor] Converting thumbnail "Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].webp' -movflags +faststart 'file:Anodyne [Any%% (Glitchless) + Any%%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].png'
[EmbedThumbnail] mutagen: Adding thumbnail to "Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].mp4"
WARNING: unable to embed using mutagen; [Errno 2] No such file or directory: 'Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].png'
[EmbedThumbnail] Neither mutagen nor AtomicParsley was found. Falling back to ffmpeg
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].mp4'
[EmbedThumbnail] ffmpeg: Adding thumbnail to "Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].mp4"
ERROR: [Errno 2] No such file or directory: 'Anodyne [Any% (Glitchless) + Any%] by LaserTrap_ - #ESAWinter22 [LPbs5Fguh-E].png'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1574, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1632, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2733, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3272, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3449, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3431, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3410, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/embedthumbnail.py", line 186, in run
    self.run_ffmpeg_multiple_files([filename, thumbnail_filename], temp_filename, options)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 323, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 330, in real_run_ffmpeg
    oldest_mtime = min(
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 331, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path, _ in input_path_opts if path)
```

**Comment by pukkandan** [comment]
See pinned issue!
