### ISSUE TITLE
[SHUTTING DOWN] BuzzVideo

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#5330]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://www.buzzvideo.com/article/i7157121376749797894?referer=foryou&pid=website_feed (Video)
https://www.buzzvideo.com/@toshi (User)
https://www.buzzvideo.com/feed/foryou (For You Page)

### Provide a description that is worded well enough to be understood

Buzzvideo is a video sharing site that is shutting down on December, 31, 2022. For me, the primary use of this future extractor will to archive the videos and metadata. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ite_feed
[Documents]$ yt-dlp -vU https://www.buzzvideo.c
om/article/i7157121376749797894?referer=foryou&
pid=website_feed
[debug] Command-line config: ['-vU', 'https://w
ww.buzzvideo.com/article/i7157121376749797894?r
eferer=foryou&pid=website_feed']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pi
p) API
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
16.0-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d2
5e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phant
omjs present, rtmpdump present
[debug] Optional libraries: Cryptodome-3.15.0, 
certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6
.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.gith
ub.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.buzzvideo.com/article/i7157121376749797894?referer=foryou&pid=website_feed
[generic] i7157121376749797894?referer=foryou&pid=website_feed: Downloading webpage
[redirect] Following redirect to https://www.buzzvideo.com/@toshi/%E3%80%90%E7%99%92%E3%81%97%E3%80%91%E3%81%B2%E3%82%87%E3%81%A3%E3%81%93%E3%82%8A%E3%81%AB%E3%82%83%E3%82%93%E3%81%93%E3%80%82%E3%81%8B%E3%82%8F%E3%81%84%E3%81%84%E3%83%8B%E3%83%A3%E3%83%BC-BsKG2_gzU2M?referer=foryou&pid=website_feed
[debug] [generic] Extracting URL: https://www.buzzvideo.com/@toshi/%E3%80%90%E7%99%92%E3%81%97%E3%80%91%E3%81%B2%E3%82%87%E3%81%A3%E3%81%93%E3%82%8A%E3%81%AB%E3%82%83%E3%82%93%E3%81%93%E3%80%82%E3%81%8B%E3%82%8F%E3%81%84%E3%81%84%E3%83%8B%E3%83%A3%E3%83%BC-BsKG2_gzU2M?referer=foryou&pid=website_feed
[generic] 【癒し】ひょっこりにゃんこ。かわいい-BsKG2_gzU2M?referer=foryou&pid=website_feed: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 【癒し】ひょっこりにゃんこ。かわいい-BsKG2_gzU2M?referer=foryou&pid=website_feed: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
WARNING: [DetikEmbed] %E3%80%90%E7%99%92%E3%81%97%E3%80%91%E3%81%B2%E3%82%87%E3%81%A3%E3%81%93%E3%82%8A%E3%81%AB%E3%82%83%E3%82%93%E3%81%93%E3%80%82%E3%81%8B%E3%82%8F%E3%81%84%E3%81%84%E3%83%8B%E3%83%A3%E3%83%BC-BsKG2_gzU2M: Failed to parse JSON: ('Expecting property name enclosed in double quotes', '{&quot;@context&quot;:&quot;https://schema.org&quot;,&quot;@type&quot;:&quot;BreadcrumbList&quot;,&quot;itemListElement&quot;:[{&quot;@type&quot;:&quot;ListItem&quot;,&quot;position&quot;:1,&quot;item&quot;:{&quot;@type&quot;:&quot;Thing&quot;,&quot;@id&quot;:&quot;https://www.buzzvideo.com/&quot;,&quot;name&quot;:&quot;buzzvideo&quot;}},{&quot;@type&quot;:&quot;ListItem&quot;,&quot;position&quot;:2,&quot;item&quot;:{&quot;@type&quot;:&quot;Thing&quot;,&quot;@id&quot;:&quot;https://www.buzzvideo.com/user/6975466096606938117/publish&quot;,&quot;name&quot;:&quot;Toshi&quot;}},{&quot;@type&quot;:&quot;ListItem&quot;,&quot;position&quot;:3,&quot;item&quot;:{&quot;@type&quot;:&quot;Thing&quot;,&quot;@id&quot;:&quot;https://www.buzzvideo.com/@toshi/【癒し】ひょっこりにゃんこ。かわいいニャー-BsKG2_gzU2M&quot;,&quot;name&quot;:&quot;【癒し】ひょっこりにゃんこ。かわいいニャー！&quot;}}]}', 1)
WARNING: [DetikEmbed] %E3%80%90%E7%99%92%E3%81%97%E3%80%91%E3%81%B2%E3%82%87%E3%81%A3%E3%81%93%E3%82%8A%E3%81%AB%E3%82%83%E3%82%93%E3%81%93%E3%80%82%E3%81%8B%E3%82%8F%E3%81%84%E3%81%84%E3%83%8B%E3%83%A3%E3%83%BC-BsKG2_gzU2M: Failed to parse JSON: ('Expecting property name enclosed in double quotes', '{&quot;@context&quot;:&quot;http://schema.org&quot;,&quot;@type&quot;:&quot;VideoObject&quot;,&quot;name&quot;:&quot;【癒し】ひょっこりにゃんこ。かわいいニャー！&quot;,&quot;description&quot;:&quot;冷蔵庫の上の段ボ | Toshiの投稿動画&quot;,&quot;thumbnailUrl&quot;:[&quot;http://p16-va.topbuzzcdn.com/list/tos-maliva-p-0000/b0047a4fa6884838b9241a3cbc5c09a4&quot;],&quot;uploadDate&quot;:&quot;2022-10-22T09:10:02.000+09:00&quot;,&quot;duration&quot;:&quot;PT33S&quot;,&quot;contentUrl&quot;:&quot;http://v16.topbuzzcdn.com/ed9d15aebaddd6d193f59c6e6342e203/63545d0a/video/tos/useast2a/tos-useast2a-ve-0029/c04f74dd34ee45b389189b32ff9509b1/?a=1106&amp;ch=0&amp;cr=0&amp;dr=0&amp;cd=0%7C0%7C0%7C0&amp;br=976&amp;bt=488&amp;cs=0&amp;ds=2&amp;ft=eIIGb28Qjju9wfMtR-9Q6C~EtXUUmAp~A-J4S6BJdeC&amp;mime_type=video_mp4&amp;qs=1&amp;rc=OTppZjQ5NGc8NTRkNjNlM0BpamVsbGg6ZjpsZzMzN2czM0A0Li4tNl9gX18xLTJeYV8vYSNiLm8xcjRvajZgLS1kLjZzcw%3D%3D&amp;l=20221022151313010188117003796699&amp;btag=80000&quot;,&quot;interactionStatistic&quot;:{&quot;@type&quot;:&quot;InteractionCounter&quot;,&quot;interactionType&quot;:{&quot;@type&quot;:&quot;http://schema.org/WatchAction&quot;},&quot;userInteractionCount&quot;:1058},&quot;author&quot;:{&quot;@type&quot;:&quot;Person&quot;,&quot;name&quot;:&quot;Toshi&quot;}}', 1)
WARNING: [generic] 【癒し】ひょっこりにゃんこ。かわいいニャー-BsKG2_gzU2M?referer=foryou&pid=website_feed: Failed to parse JSON: ('Expecting property name enclosed in double quotes', '{&quot;@context&quot;:&quot;https://schema.org&quot;,&quot;@type&quot;:&quot;BreadcrumbList&quot;,&quot;itemListElement&quot;:[{&quot;@type&quot;:&quot;ListItem&quot;,&quot;position&quot;:1,&quot;item&quot;:{&quot;@type&quot;:&quot;Thing&quot;,&quot;@id&quot;:&quot;https://www.buzzvideo.com/&quot;,&quot;name&quot;:&quot;buzzvideo&quot;}},{&quot;@type&quot;:&quot;ListItem&quot;,&quot;position&quot;:2,&quot;item&quot;:{&quot;@type&quot;:&quot;Thing&quot;,&quot;@id&quot;:&quot;https://www.buzzvideo.com/user/6975466096606938117/publish&quot;,&quot;name&quot;:&quot;Toshi&quot;}},{&quot;@type&quot;:&quot;ListItem&quot;,&quot;position&quot;:3,&quot;item&quot;:{&quot;@type&quot;:&quot;Thing&quot;,&quot;@id&quot;:&quot;https://www.buzzvideo.com/@toshi/【-BsKG2_gzU2M&quot;,&quot;name&quot;:&quot;【癒し】ひょっこりにゃんこ。かわいいニャー！&quot;}}]}', 1)
WARNING: [generic] 【癒し】ひょっこりにゃんこ。かわいいニャー-BsKG2_gzU2M?referer=foryou&pid=website_feed: Failed to parse JSON: ('Expecting property name enclosed in double quotes', '{&quot;@context&quot;:&quot;http://schema.org&quot;,&quot;@type&quot;:&quot;VideoObject&quot;,&quot;name&quot;:&quot;【癒し】ひょっこりにゃんこ。かわいいニャー！&quot;,&quot;description&quot;:&quot;冷蔵庫の上の段ボールの箱の中から、顔だけ | Toshiの投稿動画&quot;,&quot;thumbnailUrl&quot;:[&quot;http://p16-va.topbuzzcdn.com/list/tos-maliva-p-0000/b0047a4fa6884838b9241a3cbc5c09a4&quot;],&quot;uploadDate&quot;:&quot;2022-10-22T09:10:02.000+09:00&quot;,&quot;duration&quot;:&quot;PT33S&quot;,&quot;contentUrl&quot;:&quot;http://v16.topbuzzcdn.com/ed9d15aebaddd6d193f59c6e6342e203/63545d0a/video/tos/useast2a/tos-useast2a-ve-0029/c04f74dd34ee45b389189b32ff9509b1/?a=1106&amp;ch=0&amp;cr=0&amp;dr=0&amp;cd=0%7C0%7C0%7C0&amp;br=976&amp;bt=488&amp;cs=0&amp;ds=2&amp;ft=eIIGb28Qjju9wfMtR-9Q6C~EtXUUmAp~A-J4S6BJdeC&amp;mime_type=video_mp4&amp;qs=1&amp;rc=OTppZjQ5NGc8NTRkNjNlM0BpamVsbGg6ZjpsZzMzN2czM0A0Li4tNl9gX18xLTJeYV8vYSNiLm8xcjRvajZgLS1kLjZzcw%3D%3D&amp;l=20221022151313010188117003796699&amp;btag=80000&quot;,&quot;interactionStatistic&quot;:{&quot;@type&quot;:&quot;InteractionCounter&quot;,&quot;interactionType&quot;:{&quot;@type&quot;:&quot;http://schema.org/WatchAction&quot;},&quot;userInteractionCount&quot;:1058},&quot;author&quot;:{&quot;@type&quot;:&quot;Person&quot;,&quot;name&quot;:&quot;Toshi&quot;}}', 1)
ERROR: Unsupported URL: https://www.buzzvideo.com/@toshi/%E3%80%90%E7%99%92%E3%81%97%E3%80%91%E3%81%B2%E3%82%87%E3%81%A3%E3%81%93%E3%82%8A%E3%81%AB%E3%82%83%E3%82%93%E3%81%93%E3%80%82%E3%81%8B%E3%82%8F%E3%81%84%E3%81%84%E3%83%8B%E3%83%A3%E3%83%BC-BsKG2_gzU2M?referer=foryou&pid=website_feed
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3062, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.buzzvideo.com/@toshi/%E3%80%90%E7%99%92%E3%81%97%E3%80%91%E3%81%B2%E3%82%87%E3%81%A3%E3%81%93%E3%82%8A%E3%81%AB%E3%82%83%E3%82%93%E3%81%93%E3%80%82%E3%81%8B%E3%82%8F%E3%81%84%E3%81%84%E3%83%8B%E3%83%A3%E3%83%BC-BsKG2_gzU2M
?referer=foryou&pid=website_feed
```

**Comment by pukkandan** [comment]
To devs: All the data is present in `__INITIAL_DATA__` on the webpage

PS: If the service is shutting down soon, it may be better to write a quick and dirty plugin than go through the effort of making a proper PR

**Comment by pukkandan** [comment]
The video isnt playing on my system though. Does it correctly play for you?

**Comment by dirkf** [comment]
Most basic stuff is in meta og: parameters or in ld+json (but it needs `unescapeHTML()`). Additional video formats, view counts, etc, are in the `.story.video` member of `__INITIAL_DATA__`.

**Comment by dirkf** [comment]
Eg this as attached, which works for yt-dl. The test video plays: a cat in a box.
[buzzvideo.py.zip](https://github.com/yt-dlp/yt-dlp/files/9845115/buzzvideo.py.zip)

**Comment by dirkf** [comment]
https://www.buzzvideo.com/@toshi (User) -> "not found"
https://www.buzzvideo.com/feed/foryou (For You Page) has links (relative, no https://www.buzzvideo.com) to videos that match a BuzzVideo pattern so should be handled by yt-dlp generic embedding.

**Comment by coletdjnz** [comment]
I suggest hitting up ArchiveTeam about this, they may be interested and have better resources to properly archive sites at risk.
