### ISSUE TITLE
Support pietsmiet.de

### ISSUE THREAD

**Issue by alxhu-dev** [yt-dlp/yt-dlp#5339]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

Videos:
- https://www.pietsmiet.de/videos/73314-das-rasenmaher-rennen-wreckfest
- https://www.pietsmiet.de/videos/73314
- http://ptsmt.de/v/73314

Playlists:
- https://www.pietsmiet.de/videos/playlists/1874-wreckfest
- https://www.pietsmiet.de/videos/playlists/1874
- http://ptsmt.de/p/1874

### Provide a description that is worded well enough to be understood

PietSmiet.de is the video portal by the German webvideo group PietSmiet. It would be nice to see yt-dlp supporting this site.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.pietsmiet.de/videos/73314-das-rasenmaher-rennen-wreckfest']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19045-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.pietsmiet.de/videos/73314-das-rasenmaher-rennen-wreckfest
[generic] 73314-das-rasenmaher-rennen-wreckfest: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 73314-das-rasenmaher-rennen-wreckfest: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[debug] [generic] Extracting URL: https://www.pietsmiet.de/embed/player?video=73314
[generic] player?video=73314: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] player?video=73314: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.pietsmiet.de/embed/player?video=73314
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1553, in __extract_info
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\generic.py", line 3062, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.pietsmiet.de/embed/player?video=73314
```

**Comment by guys2** [comment]
Can this side please be supported it would be great.

**Comment by alxhu-dev** [comment]
Pietsmiet.de will shutdown on 2025-02-02, so this site is not relevant anymore

**Sources:**
* https://www.youtube.com/watch?v=uEKg1AghMJI
* https://www.youtube.com/watch?v=jR9day9wiNk

And this information on the site itself (Translation: _We take care of subscription cancellations. If subscribers have automatically renewed their subscription from 02.01.25, it will of course be refunded. The website will continue to run as before up to and including 01.02.25._)
![{D275B19E-381F-4D5B-8A48-DA8BB73148C3}](https://github.com/user-attachments/assets/3993a326-ae25-437f-abe3-a87f120e2ac3)
