### ISSUE TITLE
Sponsorblock API has been timing out since around October 22

### ISSUE THREAD

**Issue by yump** [yt-dlp/yt-dlp#5342]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Since around October 22, downloads with the `--sponsorblock-remove` option have been failing to remove the sponsored segements, due to timeout contacting the SponsorBlock API. I have reported this to SponsorBlock as https://github.com/ajayyy/SponsorBlock/issues/1554, and am copying it here so that it appears in the history of everyone's bug trackers.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
> yt-dlp -vU --sponsorblock-remove sponsor 'https://www.youtube.com/watch?v=oMcsW-myRCU'
[debug] Command-line config: ['-vU', '--sponsorblock-remove', 'sponsor', 'https://www.youtube.com/watch?v=oMcsW-myRCU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.19.16-200.fc36.x86_64-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=oMcsW-myRCU
[youtube] oMcsW-myRCU: Downloading webpage
[youtube] oMcsW-myRCU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/af6e?service=YouTube&categories=%5B%22sponsor%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%5D
WARNING: Unable to communicate with SponsorBlock API: The read operation timed out. Retrying (1/3)...
WARNING: Unable to communicate with SponsorBlock API: The read operation timed out. Retrying (2/3)...
WARNING: Unable to communicate with SponsorBlock API: The read operation timed out. Retrying (3/3)...
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: The read operation timed out
Traceback (most recent call last):
  File "/home/anon/localbin/yt-dlp/yt_dlp/YoutubeDL.py", line 3438, in pre_process
    info = self.run_all_pps(key, info)
  File "/home/anon/localbin/yt-dlp/yt_dlp/YoutubeDL.py", line 3431, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/anon/localbin/yt-dlp/yt_dlp/YoutubeDL.py", line 3410, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/anon/localbin/yt-dlp/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/anon/localbin/yt-dlp/yt_dlp/postprocessor/sponsorblock.py", line 41, in run
    info['sponsorblock_chapters'] = self._get_sponsor_chapters(info, info.get('duration'))
  File "/home/anon/localbin/yt-dlp/yt_dlp/postprocessor/sponsorblock.py", line 45, in _get_sponsor_chapters
    segments = self._get_sponsor_segments(info['id'], self.EXTRACTORS[info['extractor_key']])
  File "/home/anon/localbin/yt-dlp/yt_dlp/postprocessor/sponsorblock.py", line 94, in _get_sponsor_segments
    for d in self._download_json(url) or []:
  File "/home/anon/localbin/yt-dlp/yt_dlp/postprocessor/common.py", line 204, in _download_json
    for retry in RetryManager(self.get_param('extractor_retries', 3), self._retry_download):
  File "/home/anon/localbin/yt-dlp/yt_dlp/utils.py", line 5862, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/home/anon/localbin/yt-dlp/yt_dlp/postprocessor/common.py", line 199, in _retry_download
    RetryManager.report_retry(err, count, retries, info=self.to_screen, warn=self.report_warning,
  File "/home/anon/localbin/yt-dlp/yt_dlp/utils.py", line 5870, in report_retry
    raise e
yt_dlp.utils.PostProcessingError: Unable to communicate with SponsorBlock API: The read operation timed out

[debug] Default format spec: bestvideo*+bestaudio/best
[info] oMcsW-myRCU: Downloading 1 format(s): 313+251
[download] AMD Ryzen 9 7950X： Cost to Manufacture？ [oMcsW-myRCU].webm has already been downloaded
[ModifyChapters] SponsorBlock information is unavailable
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:AMD Ryzen 9 7950X： Cost to Manufacture？ [oMcsW-myRCU].webm'
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: The read operation timed out
```

**Comment by exurd** [comment]
SponsorBlock's servers are having some [issues](https://status.sponsor.ajay.app/) right now. You can check their discord for more info: [discord.gg/SponsorBlock](https://discord.gg/SponsorBlock).
