### ISSUE TITLE
[Broken] Incomplete data received when downloading YouTube Watch history

### ISSUE THREAD

**Issue by Sanqui** [yt-dlp/yt-dlp#535]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[sanqui@reige youtube-watched-unlisted]$ yt-dlp https://www.youtube.com/feed/history --datebefore 20170101 --match-filter "availability = 'unlisted'" --cookies cookies.Google.txt --download-archive unlisted_videos.txt --skip-download --verbose
[debug] Command-line config: ['https://www.youtube.com/feed/history', '--datebefore', '20170101', '--match-filter', "availability = 'unlisted'", '--cookies', 'cookies.Google.txt', '--download-archive', 'unlisted_videos.txt', '--skip-download', '--verbose']
[debug] Loading archive file 'unlisted_videos.txt'

[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.07 
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.12.15-300.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: none
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/feed/history
[youtube:tab] history: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/feed/history
[download] Downloading playlist: history
[youtube:tab] history page 1: Downloading API JSON
[youtube:tab] history page 2: Downloading API JSON
[youtube:tab] history page 3: Downloading API JSON
[youtube:tab] history page 4: Downloading API JSON
[youtube:tab] history page 5: Downloading API JSON
[youtube:tab] history page 6: Downloading API JSON
[youtube:tab] history page 7: Downloading API JSON
[youtube:tab] history page 8: Downloading API JSON
[youtube:tab] history page 9: Downloading API JSON
[youtube:tab] history page 10: Downloading API JSON
[youtube:tab] history page 11: Downloading API JSON
[youtube:tab] history page 12: Downloading API JSON
[youtube:tab] history page 13: Downloading API JSON
[youtube:tab] history page 14: Downloading API JSON
[youtube:tab] history page 15: Downloading API JSON
[youtube:tab] history page 16: Downloading API JSON
[youtube:tab] history page 17: Downloading API JSON
[youtube:tab] history page 18: Downloading API JSON
[youtube:tab] history page 19: Downloading API JSON
[youtube:tab] history page 20: Downloading API JSON
[youtube:tab] history page 21: Downloading API JSON
[youtube:tab] history page 22: Downloading API JSON
[youtube:tab] history page 23: Downloading API JSON
[youtube:tab] history page 24: Downloading API JSON
[youtube:tab] history page 25: Downloading API JSON
[youtube:tab] history page 26: Downloading API JSON
[youtube:tab] history page 27: Downloading API JSON
[youtube:tab] history page 28: Downloading API JSON
[youtube:tab] history page 29: Downloading API JSON
[youtube:tab] history page 30: Downloading API JSON
[youtube:tab] history page 31: Downloading API JSON
[youtube:tab] history page 32: Downloading API JSON
[youtube:tab] history page 33: Downloading API JSON
[youtube:tab] history page 34: Downloading API JSON
[youtube:tab] history page 35: Downloading API JSON
[youtube:tab] history page 36: Downloading API JSON
[youtube:tab] history page 37: Downloading API JSON
[youtube:tab] history page 38: Downloading API JSON
[youtube:tab] history page 39: Downloading API JSON
[youtube:tab] history page 40: Downloading API JSON
[youtube:tab] history page 41: Downloading API JSON
[youtube:tab] history page 42: Downloading API JSON
[youtube:tab] history page 43: Downloading API JSON
[youtube:tab] history page 44: Downloading API JSON
[youtube:tab] history page 45: Downloading API JSON
[youtube:tab] history page 46: Downloading API JSON
[youtube:tab] history page 47: Downloading API JSON
[youtube:tab] history page 48: Downloading API JSON
[youtube:tab] history page 49: Downloading API JSON
[youtube:tab] history page 50: Downloading API JSON
[youtube:tab] history page 51: Downloading API JSON
[youtube:tab] history page 52: Downloading API JSON
[youtube:tab] history page 53: Downloading API JSON
[youtube:tab] history page 54: Downloading API JSON
[youtube:tab] history page 55: Downloading API JSON
[youtube:tab] history page 56: Downloading API JSON
[youtube:tab] history page 57: Downloading API JSON
[youtube:tab] history page 58: Downloading API JSON
[youtube:tab] history page 59: Downloading API JSON
[youtube:tab] history page 60: Downloading API JSON
[youtube:tab] history page 61: Downloading API JSON
[youtube:tab] history page 62: Downloading API JSON
[youtube:tab] history page 63: Downloading API JSON
[youtube:tab] history page 64: Downloading API JSON
[youtube:tab] history page 65: Downloading API JSON
[youtube:tab] history page 66: Downloading API JSON
[youtube:tab] history page 67: Downloading API JSON
[youtube:tab] history page 68: Downloading API JSON
[youtube:tab] history page 69: Downloading API JSON
[youtube:tab] history page 70: Downloading API JSON
[youtube:tab] history page 71: Downloading API JSON
[youtube:tab] history page 72: Downloading API JSON
[youtube:tab] history page 73: Downloading API JSON
[youtube:tab] history page 74: Downloading API JSON
[youtube:tab] history page 75: Downloading API JSON
[youtube:tab] history page 76: Downloading API JSON
[youtube:tab] history page 77: Downloading API JSON
[youtube:tab] history page 78: Downloading API JSON
[youtube:tab] history page 79: Downloading API JSON
[youtube:tab] history page 80: Downloading API JSON
[youtube:tab] history page 81: Downloading API JSON
[youtube:tab] history page 82: Downloading API JSON
[youtube:tab] history page 83: Downloading API JSON
[youtube:tab] history page 84: Downloading API JSON
[youtube:tab] history page 85: Downloading API JSON
[youtube:tab] history page 86: Downloading API JSON
[youtube:tab] history page 87: Downloading API JSON
[youtube:tab] history page 88: Downloading API JSON
[youtube:tab] history page 89: Downloading API JSON
[youtube:tab] history page 90: Downloading API JSON
[youtube:tab] history page 91: Downloading API JSON
[youtube:tab] history page 92: Downloading API JSON
[youtube:tab] history page 93: Downloading API JSON
[youtube:tab] history page 94: Downloading API JSON
[youtube:tab] history page 95: Downloading API JSON
[youtube:tab] history page 96: Downloading API JSON
[youtube:tab] history page 97: Downloading API JSON
[youtube:tab] history page 98: Downloading API JSON
[youtube:tab] history page 99: Downloading API JSON
[youtube:tab] history page 100: Downloading API JSON
[youtube:tab] history page 101: Downloading API JSON
[youtube:tab] history page 102: Downloading API JSON
[youtube:tab] history page 103: Downloading API JSON
[youtube:tab] history page 104: Downloading API JSON
[youtube:tab] history page 105: Downloading API JSON
[youtube:tab] history page 106: Downloading API JSON
[youtube:tab] history page 107: Downloading API JSON
[youtube:tab] history page 108: Downloading API JSON
[youtube:tab] history page 109: Downloading API JSON
[youtube:tab] history page 110: Downloading API JSON
[youtube:tab] history page 111: Downloading API JSON
[youtube:tab] history page 112: Downloading API JSON
[youtube:tab] history page 113: Downloading API JSON
[youtube:tab] history page 114: Downloading API JSON
[youtube:tab] history page 115: Downloading API JSON
[youtube:tab] history page 116: Downloading API JSON
[youtube:tab] history page 117: Downloading API JSON
[youtube:tab] history page 118: Downloading API JSON
[youtube:tab] history page 119: Downloading API JSON
[youtube:tab] history page 120: Downloading API JSON
[youtube:tab] history page 121: Downloading API JSON
[youtube:tab] history page 122: Downloading API JSON
[youtube:tab] history page 123: Downloading API JSON
[youtube:tab] history page 124: Downloading API JSON
[youtube:tab] history page 125: Downloading API JSON
[youtube:tab] history page 126: Downloading API JSON
[youtube:tab] history page 127: Downloading API JSON
[youtube:tab] history page 128: Downloading API JSON
[youtube:tab] history page 129: Downloading API JSON
[youtube:tab] history page 130: Downloading API JSON
[youtube:tab] history page 131: Downloading API JSON
[youtube:tab] history page 132: Downloading API JSON
[youtube:tab] history page 133: Downloading API JSON
[youtube:tab] history page 134: Downloading API JSON
[youtube:tab] history page 135: Downloading API JSON
[youtube:tab] history page 136: Downloading API JSON
[youtube:tab] history page 137: Downloading API JSON
[youtube:tab] history page 138: Downloading API JSON
[youtube:tab] history page 139: Downloading API JSON
[youtube:tab] history page 140: Downloading API JSON
[youtube:tab] history page 141: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] history page 141: Downloading API JSON (retry #1)
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] history page 141: Downloading API JSON (retry #2)
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] history page 141: Downloading API JSON (retry #3)
ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/sanqui/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1142, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sanqui/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1178, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/sanqui/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1287, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/home/sanqui/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1369, in __process_playlist
    entry = ie_entries[i - 1]
  File "/home/sanqui/.local/lib/python3.9/site-packages/yt_dlp/utils.py", line 4019, in __getitem__
    self.__cache.extend(itertools.islice(self.__iterable, n))
  File "/home/sanqui/.local/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 3948, in _smuggle_data
    for entry in entries:
  File "/home/sanqui/.local/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 3661, in _entries
    response = self._extract_response(
  File "/home/sanqui/.local/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 620, in _extract_response
    raise ExtractorError(last_error)
yt_dlp.utils.ExtractorError: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.


```

## Description

Attempting to download the list of unlisted watched videos fails beyond a certain page.

**Comment by colethedj** [comment]
Hmm, could possibly be YouTube's side.

Maybe try running with`--extractor-retries NUM` set to a higher number

**Comment by Sanqui** [comment]
Did fifty tries, no dice.
```WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] history page 141: Downloading API JSON (retry #50)
```

**Comment by colethedj** [comment]
That's rather annoying. It might be YouTube breaking itself on page 141. I've seen this occasionally on a few select channels.

I believe the only workaround atm is to stop the extraction right before page 141 with `--playlist-end`.  Calculating that might be a pain - history feed appears to be around 200 videos/page, but it's not exact :/

Would you mind running with `--write-pages` and either emailing me or DM me on discord the page dumps for pages 140 & 141? I want to check we are not hitting some sort of "end of history feed" that isn't being handled correctly.

---
Regardless, we may need to implement an ignore incomplete data error toggle. @pukkandan, shouldn't be too hard to add support in `_extract_response`? something like `--extractor-args youtube:ignore_incomplete_errors=true`?

**Comment by pukkandan** [comment]
One weird thing I didn't notice at first - I always only get 5 pages of history in my account. How come you get more? 🤔

**Comment by colethedj** [comment]
Update: this appears to be due to YouTube breaking itself on page 141 on OP's watch history. It was returning no continuation data. Similar to how we have seen similar behaviour on channels etc.

**Comment by colethedj** [comment]
> One weird thing I didn't notice at first - I always only get 5 pages of history in my account. How come you get more? thinking

watch history is ~200 videos/page. maybe you have auto delete on for your history?

**Comment by pukkandan** [comment]
Since https://github.com/yt-dlp/yt-dlp/commit/50fed816dd5ae970d69d8997eb854d475ed91ede, the error will be non-fatal unless `--abort-on-error` is given. Since the actual issue is from youtube's side, nothing we can do about it
