### ISSUE TITLE
Error when embedding thumbnail

### ISSUE THREAD

**Issue by christoph-heinrich** [yt-dlp/yt-dlp#5366]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Sometimes I encounter files from Odysee that have an error during post processing saying that it can't find the file.
Since the downloading itself works without a problem I think it's actually independent of the platform.
I narrowed it down to `--embed-thumbnail`.

For example the command `yt-dlp --ignore-config --embed-thumbnail 'https://odysee.com/@AlexJonesChannel:c/19Oct22:0'` results in
```
ERROR: [Errno 2] No such file or directory: 'WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].temp.mp4' -> 'WEDNESDAY FULL SHOW 10⧸19⧸22- A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].mp4'
```
Note that the `⧸` are not regular `/`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--ignore-config', '-vU', '--embed-thumbnail', 'https://odysee.com/@AlexJonesChannel:c/19Oct22:0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.10.04 [4e0511f27]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.3-xanmod1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1701 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [lbry] Extracting URL: https://odysee.com/@AlexJonesChannel:c/19Oct22:0
[lbry] @AlexJonesChannel#c/19Oct22#0: Downloading stream JSON metadata
[lbry] 0b5268f60bbeba90ebb4f85ad0703ef4b912b647: Downloading streaming url JSON metadata
[lbry] @AlexJonesChannel#c/19Oct22#0: Downloading streaming redirect url info
[lbry] @AlexJonesChannel#c/19Oct22#0: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 0b5268f60bbeba90ebb4f85ad0703ef4b912b647: Downloading 1 format(s): hls-2890
Deleting existing file WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].webp
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].webp
[debug] Invoking hlsnative downloader on "https://player.odycdn.com/api/v4/streams/tc/19Oct22/0b5268f60bbeba90ebb4f85ad0703ef4b912b647/a300f9a9dd9b6c0f70679e4f28775918d8fe535c6644bc4359b60ff40cf6e6f812366a5ca12e6e7a5b30cb80c2114ed0/v0.m3u8"
[download] WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].mp4 has already been downloaded

[download] 100% of    1.71GiB
[ThumbnailsConvertor] Converting thumbnail "WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].webp' -movflags +faststart 'file:WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80%% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].png'
[EmbedThumbnail] mutagen: Adding thumbnail to "WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].mp4"
WARNING: unable to embed using mutagen; [Errno 2] No such file or directory: 'WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].png'
[EmbedThumbnail] mutagen was not found. Falling back to AtomicParsley
[EmbedThumbnail] atomicparsley: Adding thumbnail to "WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].mp4"
[debug] AtomicParsley command line: atomicparsley 'WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].mp4' --artwork 'WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].png' -o 'WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].temp.mp4'
WARNING: Unable to embed thumbnails using AtomicParsley; AtomicParsley error: can't open WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].png for reading: No such file or directory
ERROR: [Errno 2] No such file or directory: 'WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].temp.mp4' -> 'WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].mp4'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1478, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1575, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1634, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2731, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3270, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3447, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3429, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3408, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/embedthumbnail.py", line 219, in run
    os.replace(temp_filename, filename)
FileNotFoundError: [Errno 2] No such file or directory: 'WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].temp.mp4' -> 'WEDNESDAY FULL SHOW 10⧸19⧸22 - A Virus that Kills 80% of Humans has been Developed by the US Govt. at the University of Boston in Mass. [0b5268f60bbeba90ebb4f85ad0703ef4b912b647].mp4'
```

**Comment by christoph-heinrich** [comment]
I think it's a duplicate of #4604, which I missed at first somehow.
