### ISSUE TITLE
pornhub : ERROR: unable to download video data: HTTP Error 472:

### ISSUE THREAD

**Issue by leshinskii** [yt-dlp/yt-dlp#5425]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Download from pornhub.com is broken
ERROR: unable to download video data: HTTP Error 472:

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
/media/user/xxxxxxxx/X/0/1/soft/yt-dlp  -vU -R infinite --file-access-retries infinite --socket-timeout 3600 -N 20 https://fr.pornhub.com/view_video.php?viewkey=ph635e6d808f288
[debug] Command-line config: ['-vU', '-R', 'infinite', '--file-access-retries', 'infinite', '--socket-timeout', '3600', '-N', '20', 'https://fr.pornhub.com/view_video.php?viewkey=ph635e6d808f288']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-19-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, phantomjs 140224937437120
[debug] Optional libraries: brotli-1.0.9, certifi-2021.10.08, sqlite3-2.6.0
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [PornHub] Extracting URL: https://fr.pornhub.com/view_video.php?viewkey=ph635e6d808f288
[PornHub] ph635e6d808f288: Downloading pc webpage
[PornHub] ph635e6d808f288: Downloading JSON metadata
WARNING: [PornHub] ph635e6d808f288: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
[debug] Sort order given by extractor: height, width, fps, format_id
[debug] Formats sorted by: hasvid, ie_pref, height, width, fps, id, lang, quality, res, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ph635e6d808f288: Downloading 1 format(s): 720p
[debug] Invoking http downloader on "https://ev.phncdn.com/videos/201603/21/71659671/191019_1446_720P_4000K_71659671.mp4?validfrom=1632770612&validto=1632777812&rate=500k&burst=1000k&ipa=162.211.96.225&hash=5CYLDGi46uYZ402kGCvHZno8Q2s%3D"
ERROR: unable to download video data: HTTP Error 472: 
Traceback (most recent call last):
  File "/media/user/xxxxxxxx/X/0/1/soft/yt-dlp/yt_dlp/YoutubeDL.py", line 3196, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/media/user/xxxxxxxx/X/0/1/soft/yt-dlp/yt_dlp/YoutubeDL.py", line 2920, in dl
    return fd.download(name, new_info, subtitle)
  File "/media/user/xxxxxxxx/X/0/1/soft/yt-dlp/yt_dlp/downloader/common.py", line 446, in download
    ret = self.real_download(filename, info_dict)
  File "/media/user/xxxxxxxx/X/0/1/soft/yt-dlp/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/media/user/xxxxxxxx/X/0/1/soft/yt-dlp/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/media/user/xxxxxxxx/X/0/1/soft/yt-dlp/yt_dlp/YoutubeDL.py", line 3682, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 472:
```

**Comment by pukkandan** [comment]
Read pins

**Comment by leshinskii** [comment]
> Read pins

link, please

**Comment by pukkandan** [comment]
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=sort%3Aupdated-desc) for similar issues **including closed ones**. DO NOT post duplicates
