### ISSUE TITLE
VLIVE fails caused by KeyError('message')

### ISSUE THREAD

**Issue by 456Genas** [yt-dlp/yt-dlp#5427]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Can't download VLIVE video due to an KeyError 'message'

Its my first time downloading vlive videos sorry if i am doing something wrong 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.vlive.tv/video/228709']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[vlive] Downloading login cookies
[vlive] Logging in
[vlive] Checking login status
[debug] [vlive] Extracting URL: https://www.vlive.tv/video/228709
[vlive] 228709: Downloading officialVideoPost JSON metadata
[vlive] 228709: Downloading inkey JSON metadata
ERROR: 228709: An extractor error has occurred. (caused by KeyError('message')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 805, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3682, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\vlive.py", line 59, in _call_api
  File "yt_dlp\extractor\common.py", line 1032, in download_content
  File "yt_dlp\extractor\common.py", line 996, in download_handle
  File "yt_dlp\extractor\common.py", line 866, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 823, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\vlive.py", line 143, in _real_extract
  File "yt_dlp\extractor\vlive.py", line 177, in _get_vlive_info
  File "yt_dlp\extractor\vlive.py", line 64, in _call_api
KeyError: 'message'
```

**Comment by robindz** [comment]
The VLive you're using in your command is DRM protected, hence yt-dlp won't be able to download it.

**Comment by pukkandan** [comment]
We should ideally detect this and give a proper error message. But I doubt OP would want to share account details for just that

**Comment by bashonly** [comment]
VLIVE was shut down at the end of 2022
