### ISSUE TITLE
Better holodex support

### ISSUE THREAD

**Issue by helpimnotdrowning** [yt-dlp/yt-dlp#5457]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://holodex.net/channel/UCsUj0dszADCGbF3gNrQEuSQ/collabs (list of collab streams/videos)
https://holodex.net/channel/UC5CwaMl1eIgY8h02uZw7u8A/clips (list of community clips)

https://music.holodex.net/channel/UCS9uQI-jC3DE0L4IpXyvr6w (list of music played in vtuber streams, though the way most of these work is that they link to specific timestamps of streams, so I'm not sure this could be implemented without having to cut up the video)

### Provide a description that is worded well enough to be understood

Currently, the holodex extractor only seems to be able to download video pages (a frame for a youtube video/stream, like https://holodex.net/watch/oQBFMEIInIo ) or an onsite playlist of youtube videos. The site also has other pages that list videos, like `/collabs` and `/clips` tabs under channel pages where yt-dlp fails to find any videos.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://holodex.net/channel/UC5CwaMl1eIgY8h02uZw7u8A/collabs']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22621-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-108782-gff3c708686-20221022 (setts), ffprobe N-108782-gff3c708686-20221022
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://holodex.net/channel/UC5CwaMl1eIgY8h02uZw7u8A/collabs
[generic] collabs: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] collabs: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://holodex.net/channel/UC5CwaMl1eIgY8h02uZw7u8A/collabs
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1553, in __extract_info
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\generic.py", line 3062, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://holodex.net/channel/UC5CwaMl1eIgY8h02uZw7u8A/collabs
```

**Comment by helpimnotdrowning** [comment]
This is also true for base channel links like `https://holodex.net/channel/UC5CwaMl1eIgY8h02uZw7u8A`, but in this case yt-dlp *could* just replace the `https://holodex.net/channel/` portion with `https://www.youtube.com/channel/` since both links would be functionally the same (except in cases where someone is extracting page metadata, in which case Holodex would list more videos since it shows links to privated/member-only content which isn't visible on the YouTube page, though yt-dlp wouldn't be able to extract this hidden content anyways)
