### ISSUE TITLE
[Broken] cbc.ca olympics videos: no formats found

### ISSUE THREAD

**Issue by werid** [yt-dlp/yt-dlp#546]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.07.21**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

olympics video does not work

```
[debug] Command-line config: ['--verbose', '-F', 'https://www.cbc.ca/player/play/1915649603972']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.21 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[debug] [cbc.ca:player] Extracting URL: https://www.cbc.ca/player/play/1915649603972
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/ExhSPC/media/guid/2655402169/1915649603972?mbr=true&formats=MPEG4,FLV,MP3#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 1915649603972: Downloading SMIL data
[ThePlatform] 1915649603972: Downloading m3u8 information
WARNING: [ThePlatform] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1151, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1176, in __extract_info
  File "yt_dlp\extractor\common.py", line 572, in extract
  File "yt_dlp\extractor\theplatform.py", line 309, in _real_extract
  File "yt_dlp\extractor\common.py", line 1750, in _sort_formats
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

regular video works

```
[debug] Command-line config: ['--verbose', '-F', 'https://www.cbc.ca/player/play/1924265027952']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.21 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[debug] [cbc.ca:player] Extracting URL: https://www.cbc.ca/player/play/1924265027952
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/ExhSPC/media/guid/2655402169/1924265027952?mbr=true&formats=MPEG4,FLV,MP3#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 1924265027952: Downloading SMIL data
[ThePlatform] 1924265027952: Checking video URL
[ThePlatform] 1924265027952: Checking video URL
[ThePlatform] 1924265027952: Checking video URL
[ThePlatform] 1924265027952: Checking video URL
[ThePlatform] 1924265027952: Checking video URL
[ThePlatform] 1924265027952: Checking video URL
[ThePlatform] 1924265027952: Checking video URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 1924265027952: Downloading JSON metadata
[info] Available formats for 1924265027952:
ID        EXT RESOLUTION |   TBR PROTO | VCODEC    VBR ACODEC   ABR
--------- --- ---------- - ----- ----- - ------- ----- ------- ----
http-323  mp4 320x180    |  323k https | unknown  323k unknown   0k
http-470  mp4 320x180    |  470k https | unknown  470k unknown   0k
http-836  mp4 640x360    |  836k https | unknown  836k unknown   0k
http-1235 mp4 852x480    | 1235k https | unknown 1235k unknown   0k
http-1936 mp4 852x480    | 1936k https | unknown 1936k unknown   0k
http-2635 mp4 1280x720   | 2635k https | unknown 2635k unknown   0k
http-7156 mp4 1920x1080  | 7156k https | unknown 7156k unknown   0k
```

## Description

the olympics videos on cbc.ca gives no formats found, while regular videos work. finding master.m3u8 via devtools works to download.

**Comment by Ashish0804** [comment]
This is region locked -_-
I'm guessing to Canada

**Comment by zenerdi0de** [comment]
Using a Canadian proxy works for me 
```yt-dlp --proxy "51.222.21.95:32768" --verbose "https://www.cbc.ca/player/play/1915649603972"
[debug] Command-line config: ['--proxy', '51.222.21.95:32768', '--verbose', 'https://www.cbc.ca/player/play/1915649603972']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.10.49-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {'http': '51.222.21.95:32768', 'https': '51.222.21.95:32768'}
[debug] [cbc.ca:player] Extracting URL: https://www.cbc.ca/player/play/1915649603972
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/ExhSPC/media/guid/2655402169/1915649603972?mbr=true&formats=MPEG4,FLV,MP3#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 1915649603972: Downloading SMIL data
[ThePlatform] 1915649603972: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 1915649603972: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1915649603972: Downloading 1 format(s): hls-3440
[debug] Invoking downloader on "https://cbcrcolympic-cbc.akamaized.net/hls/live/2025674/geo_allow_ca/utl3p8nhhx/hdntl=exp=1627066321~acl=%2f*~id=ecef62b2-f0e4-40c9-a887-9664a8d76e48~data=hdntl~hmac=e703210cab6fcc9ca0648868dbd4d1025003bec7e3140c756279cb80c3065ec1/master_3000-archive.m3u8?aka_me_session_id=AAAAAAAAAADRD%2ftgAAAAANOT4YyLVALs4yzOSzDjUloL4g3QqUXLmoChX%2f5IN2aBtNCVBUv3YSsVJ3izT07iFUougff+Twmp&aka_media_format_type=hls&startTime=1626922200&endTime=1626930960"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1131
[download] Destination: Softball - Mexico vs Japan - Opening Round [1915649603972].mp4
[download]   0.1% of ~3.37GiB at  1.01MiB/s ETA 01:53:58^C
ERROR: Interrupted by user
```

**Comment by werid** [comment]
thanks, i can confirm this is a geoblock error. had to try a few VPN's before it worked. i was fooled by the other video i tried, which i assumed was restricted to canada also, but appears not.

**Comment by Ashish0804** [comment]
Closing this since it's a geoblock issue.
