### ISSUE TITLE
Incorrect AES key length (48 bytes) ERROR

### ISSUE THREAD

**Issue by yaleoc** [yt-dlp/yt-dlp#5470]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

US

### Example URLs

https://d2qny97nu4rj64.cloudfront.net/spees/w/o/6197321b0cf23d7cc6e572e1/v/631cca34e4b0e9ba4c0511cf/u/621b96ad0cf202ac816dd59b/t/7393a97018d7366523558621908557ed/p/assets/videos/6197321b0cf23d7cc6e572e1/2022/09/10/631cca34e4b0e9ba4c0511cf/index.m3u8

### Provide a description that is worded well enough to be understood

Hi I am not really well knowledge in the field, I gave my best attempt over this past week trying to figure it out myself, but if the issue turned out to be naive, pleave accept my apology in the front. Thanks. This is a course that I try to watch later after the course is over, hosted on the **cloudfront.net** server.

yt-dlp -F https://d2qny97nu4rj64.cloudfront.net/spees/w/o/6197321b0cf23d7cc6e572e1/v/631cca34e4b0e9ba4c0511cf/u/621b96ad0cf202ac816dd59b/t/7393a97018d7366523558621908557ed/p/assets/videos/6197321b0cf23d7cc6e572e1/2022/09/10/631cca34e4b0e9ba4c0511cf/index.m3u8

I used the above command and get returned 3 different resolution m3u8 files. I found the weblink through chrome network traffic monitor. I googled everything I could find about this website. I believe the **_index_** page is the closest to the **_manifest_**, and the **_timestamp_** page in the link below is the closest to the **_key_** mentioned by the many posts I read.

https://d2qny97nu4rj64.cloudfront.net/spees/w/o/6197321b0cf23d7cc6e572e1/v/631cca34e4b0e9ba4c0511cf/u/621b96ad0cf202ac816dd59b/t/7393a97018d7366523558621908557ed/p/assets/videos/6197321b0cf23d7cc6e572e1/2022/09/10/631cca34e4b0e9ba4c0511cf/k/timestamp

However when I tried to download it with (sorry for adding an extra emoji)

yt-dlp "https://d2qny97nu4rj64.cloudfront.net/spees/w/o/6197321b0cf23d7cc6e572e1/v/631cca34e4b0e9ba4c0511cf/u/621b96ad0cf202ac816dd59b/t/7393a97018d7366523558621908557ed/p/assets/videos/6197321b0cf23d7cc6e572e1/2022/09/10/631cca34e4b0e9ba4c0511cf/index.m3u8" --referer "https://www.fut🦴urly.com/"

I got the **ERROR: Incorrect AES key length (48 bytes)**
I found one other post with this issue, but the it wasn't solved there in the end.

The **timestamp** link mentioned above when opened does have **48 characters** (txt posted below **timestamp.txt**). I also tried to use a software called **Postman** to ping the key and got a **different 48 charamters** (also posted below **postman.txt**). I felt like Im out of resouces to furthur read through this error. I am wondering if there is anyway I can attach this key somewhere to mitigate this Incorrect AES key length download error (I read a post that the key can be used to decrypt the video after donwloading the file). Like can I attach it to the URL somehow or is there a yt-dlp promot to use it? Thanks

[timestamp.txt](https://github.com/yt-dlp/yt-dlp/files/9948263/timestamp.txt)
[postman.txt](https://github.com/yt-dlp/yt-dlp/files/9948264/postman.txt)

Referer site is https://www.fut🦴urly.com/s/courses/62e4e2ad0cf2792349e0cc8e/take Let me know if cookie is needed, I also posted the player js file from this site
[Player JS.txt](https://github.com/yt-dlp/yt-dlp/files/9948272/Player.JS.txt)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://d2qny97nu4rj64.cloudfront.net/spees/w/o/6197321b0cf23d7cc6e572e1/v/631cca34e4b0e9ba4c0511cf/u/621b96ad0cf202ac816dd59b/t/7393a97018d7366523558621908557ed/p/assets/videos/6197321b0cf23d7cc6e572e1/2022/09/10/631cca34e4b0e9ba4c0511cf/index.m3u8', '--referer', 'https://www.fut🦴urly.com/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] (win32_exe)
[debug] Python 3.10.6 (CPython 64bit) - Windows-10-10.0.25236-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-08-31-git-319e8a49b5-essentials_build-www.gyan.dev (setts), ffprobe 2022-08-31-git-319e8a49b5-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1718 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://d2qny97nu4rj64.cloudfront.net/spees/w/o/6197321b0cf23d7cc6e572e1/v/631cca34e4b0e9ba4c0511cf/u/621b96ad0cf202ac816dd59b/t/7393a97018d7366523558621908557ed/p/assets/videos/6197321b0cf23d7cc6e572e1/2022/09/10/631cca34e4b0e9ba4c0511cf/index.m3u8
[generic] index: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[debug] Identified a M3U playlist
[generic] index: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] index: Downloading 1 format(s): 1500
[debug] Invoking hlsnative downloader on "https://d2qny97nu4rj64.cloudfront.net/spees/w/o/6197321b0cf23d7cc6e572e1/v/631cca34e4b0e9ba4c0511cf/u/621b96ad0cf202ac816dd59b/t/7393a97018d7366523558621908557ed/p/assets/videos/6197321b0cf23d7cc6e572e1/2022/09/10/631cca34e4b0e9ba4c0511cf/hls_2M_.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2476
[download] Destination: index [index].mp4
[debug] File locking is not supported. Proceeding without locking
[download]   0.0% of ~  39.97MiB at  143.26KiB/s ETA 04:43 (frag 1/2476)ERROR: Incorrect AES key length (48 bytes)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1478, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1575, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1634, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2731, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3194, in process_info
  File "yt_dlp\YoutubeDL.py", line 2918, in dl
  File "yt_dlp\downloader\common.py", line 446, in download
  File "yt_dlp\downloader\hls.py", line 354, in real_download
  File "yt_dlp\downloader\fragment.py", line 521, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 369, in decrypt_fragment
  File "yt_dlp\aes.py", line 11, in aes_cbc_decrypt_bytes
  File "Cryptodome\Cipher\AES.py", line 232, in new
  File "Cryptodome\Cipher\__init__.py", line 79, in _create_cipher
  File "Cryptodome\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Cryptodome\Cipher\AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (48 bytes)
```

**Comment by pukkandan** [comment]
So, what is the actual site request? For futurly.com? If so, pass a video webpage's URL to yt-dlp along with cookies and show log of that

**Comment by yaleoc** [comment]
Thanks. Any chance i can send you the cookie through email?

**Comment by pukkandan** [comment]
```
❯ yt-dlp https://www.futurly.com/s/courses/623c522c0cf218fcda7f8b2a/take --cookies cookies.txt -v
[debug] Command-line config: ['--ignore-config', 'https://www.futurly.com/s/courses/623c522c0cf218fcda7f8b2a/take', '--cookies', 'cookies.txt', '-v']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 581e86b51
[debug] Python 3.11.0 (CPython 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107787-gc469c3c3b1-20220814 (fdk,setts), ffprobe N-107787-gc469c3c3b1-20220814, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1719 extractors
[debug] [generic] Extracting URL: https://www.futurly.com/s/courses/623c522c0cf218fcda7f8b2a/take
[generic] take: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] take: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.futurly.com/s/courses/623c522c0cf218fcda7f8b2a/take
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1478, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1554, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 674, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\generic.py", line 2755, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.futurly.com/s/courses/623c522c0cf218fcda7f8b2a/take
```

**Comment by yaleoc** [comment]
Hi I shared my account on discord dm with you yesterday. Let me know if you can see. Thanks

**Comment by pukkandan** [comment]
I posted the log only because you seem to have misunderstood my earlier comment and instead shared cookies with me. Since it wasn't very difficult for me to triage the issue with the details you gave, that is what I did. That does not mean I am committing to fix this myself. 

The `account-needed` label is just a hint for maintainers and any potential contributors that account is needed to work on the issue; and is not asking you to give account to the maintainer who added the label. If someone is interested in working on this and needs account details for that, they will let you know how to share it privately.

**Comment by elyse0** [comment]
It seems like the real key is on the page (spka) and it's obfuscated using AES ECB mode

https://forum.videohelp.com/threads/407217-howto-deal-with-HLS-128-bit-aes-encrypted-the-hard-one
https://github.com/streamlink/streamlink/issues/2253

Currently there's no option to override/provide a hls key to the parser or downloader, but if you want a hackish way to download those videos, you could hard-code it

This will break all other hls/dash downloads, so you better only use it for these specific videos

```diff
diff --git a/yt_dlp/downloader/fragment.py b/yt_dlp/downloader/fragment.py
index 83f7870ed..571fbffb1 100644
--- a/yt_dlp/downloader/fragment.py
+++ b/yt_dlp/downloader/fragment.py
@@ -357,6 +357,7 @@ def decrypt_fragment(fragment, frag_content):
             if frag_content is None:
                 return
             decrypt_info = fragment.get('decrypt_info')
+            decrypt_info['KEY'] = bytearray.fromhex('2AAC616013F1877619AF8AC01ABFF0A6')
             if not decrypt_info or decrypt_info['METHOD'] != 'AES-128':
                 return frag_content
             iv = decrypt_info.get('IV') or struct.pack('>8xq', fragment['media_sequence'])
```

**Comment by pukkandan** [comment]
We can easily implement passing key to downloader similar to `extra_param_to_segment_url`

**Comment by yaleoc** [comment]
> It seems like the real key is on the page (spka) and it's obfuscated using AES ECB mode
> 
> https://forum.videohelp.com/threads/407217-howto-deal-with-HLS-128-bit-aes-encrypted-the-hard-one [streamlink/streamlink#2253](https://github.com/streamlink/streamlink/issues/2253)
> 
> Currently there's no option to override/provide a hls key to the parser or downloader, but if you want a hackish way to download those videos, you could hard-code it
> 
> This will break all other hls/dash downloads, so you better only use it for these specific videos
> 
> ```diff
> diff --git a/yt_dlp/downloader/fragment.py b/yt_dlp/downloader/fragment.py
> index 83f7870ed..571fbffb1 100644
> --- a/yt_dlp/downloader/fragment.py
> +++ b/yt_dlp/downloader/fragment.py
> @@ -357,6 +357,7 @@ def decrypt_fragment(fragment, frag_content):
>              if frag_content is None:
>                  return
>              decrypt_info = fragment.get('decrypt_info')
> +            decrypt_info['KEY'] = bytearray.fromhex('2AAC616013F1877619AF8AC01ABFF0A6')
>              if not decrypt_info or decrypt_info['METHOD'] != 'AES-128':
>                  return frag_content
>              iv = decrypt_info.get('IV') or struct.pack('>8xq', fragment['media_sequence'])
> ```

Thanks I figured it out last week with some help from pukkandan

**Comment by yaleoc** [comment]
> It seems like the real key is on the page (spka) and it's obfuscated using AES ECB mode
> 
> https://forum.videohelp.com/threads/407217-howto-deal-with-HLS-128-bit-aes-encrypted-the-hard-one [streamlink/streamlink#2253](https://github.com/streamlink/streamlink/issues/2253)
> 
> Currently there's no option to override/provide a hls key to the parser or downloader, but if you want a hackish way to download those videos, you could hard-code it
> 
> This will break all other hls/dash downloads, so you better only use it for these specific videos
> 
> ```diff
> diff --git a/yt_dlp/downloader/fragment.py b/yt_dlp/downloader/fragment.py
> index 83f7870ed..571fbffb1 100644
> --- a/yt_dlp/downloader/fragment.py
> +++ b/yt_dlp/downloader/fragment.py
> @@ -357,6 +357,7 @@ def decrypt_fragment(fragment, frag_content):
>              if frag_content is None:
>                  return
>              decrypt_info = fragment.get('decrypt_info')
> +            decrypt_info['KEY'] = bytearray.fromhex('2AAC616013F1877619AF8AC01ABFF0A6')
>              if not decrypt_info or decrypt_info['METHOD'] != 'AES-128':
>                  return frag_content
>              iv = decrypt_info.get('IV') or struct.pack('>8xq', fragment['media_sequence'])
> ```

and I actually followed that same post and ended up using streamlink
