### ISSUE TITLE
print fragment urls without full download

### ISSUE THREAD

**Issue by crbyxwpzfl** [yt-dlp/yt-dlp#5480]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

In short is it possible to print out the fragment urls of a extracted hls url.
thank you in advance and feel free to close this at any time. I really like your aria integration as is (especially since this pr #3724). just looking for some help/tips here

#### long version
currently im using ytdlp to extract the url and then pass all extracted urls to the same aria deamon. 
this works ok for all non fragment downloads since aria cant handle hls.

for all hls/m3u8 links I managed this whacky solution to get the fragment .urls file without a complete download.
I take #3724 and hardcode aria to always use port 6800. 
then I start an aria deamon on port 6800.
this makes ytdlp error out when it wants to satart aria itself since an other aria already is running on port 6800.
When aria fails to start ytdlp crashes and leaves the .url file behind without a complete download. 
at least I think thats whats happening here see log below.

I also tried to just use `.extract_info()['fragments']` but i get `key error`.
This is expected since no hls index was downloaded jet i guess.
```py
import yt_dlp;
URL: "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8"
ydl_opts={'format_sort': ['ext'], 'verbose': True}
print(yt_dlp.YoutubeDL( ydl_opts ).extract_info(URL, download=False)['fragments'])
```

as you can see I dont know too much python but letting everything carsh to just leave the urls file behind is probably not too good.  
anyway thanks for this cool project and tips.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
>>> URLS = 'http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8'
>>> import yt_dlp; print(yt_dlp.YoutubeDL({'__rpc_port': 6800, '__rpc_secret': 1234, 'external_downloader': 'aria2c', 'verbose': True, 'no_warnings': False, 'quiet': False, 'format_sort': ['ext']}).extract_info(URLS, download=True)['url']) # 'format_id' to verify selection
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] API
[debug] params: {'__rpc_port': 6800, '__rpc_secret': 1234, 'external_downloader': 'aria2c', 'verbose': True, 'no_warnings': False, 'quiet': False, 'format_sort': ['ext'], 'compat_opts': set()}
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.6 (CPython 64bit) - macOS-13.0-x86_64-i386-64bit 
[debug] exe versions: ffmpeg N-106490-gbb4e0f6162-tessus (setts), ffprobe N-106666-geae3b84189-tessus
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1715 extractors
[debug] [generic] Extracting URL: http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
[generic] bipbopall: Downloading webpage
[debug] Identified a direct video link
[generic] bipbopall: Downloading m3u8 information
[debug] Sort order given by user: ext
[debug] Formats sorted by: hasvid, ie_pref, vext, aext, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] bipbopall: Downloading 1 format(s): 737
[debug] Invoking hlsnative downloader on "http://devimages.apple.com/iphone/samples/bipbop/gear4/prog_index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 181
[download] Destination: bipbopall [bipbopall].mp4
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --http-accept-gzip=true --file-allocation=none -x16 -j16 -s16 --allow-overwrite=true --allow-piece-length-change=true --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-us,en;q=0.5' --header 'Sec-Fetch-Mode: navigate' --enable-rpc --rpc-listen-port=6800 --rpc-secret=1234 --auto-file-renaming=false --file-allocation=none --uri-selector=inorder -i 'bipbopall [bipbopall].mp4.part.frag.urls'
[download]      0.00B at  Unknown B/s (00:00:00) (frag 0/181)ERROR: Unable to open fragment 0; [Errno 2] No such file or directory: 'bipbopall [bipbopall].mp4.part-Frag0'
Traceback (most recent call last):
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/utils.py", line 623, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/utils.py", line 2130, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'bipbopall [bipbopall].mp4.part-Frag0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/external.py", line 162, in _call_downloader
    src, _ = self.sanitize_open(fragment_filename, 'rb')
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/common.py", line 237, in wrapper
    retry.error_callback(err, 1, 0)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/common.py", line 223, in error_callback
    return RetryManager.report_retry(
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/utils.py", line 5785, in report_retry
    raise e
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/common.py", line 232, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/common.py", line 243, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/utils.py", line 625, in sanitize_open
    stream = open(filename, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: 'bipbopall [bipbopall].mp4.part-Frag0'

Traceback (most recent call last):
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/utils.py", line 623, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/utils.py", line 2130, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'bipbopall [bipbopall].mp4.part-Frag0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/external.py", line 162, in _call_downloader
    src, _ = self.sanitize_open(fragment_filename, 'rb')
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/common.py", line 237, in wrapper
    retry.error_callback(err, 1, 0)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/common.py", line 223, in error_callback
    return RetryManager.report_retry(
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/utils.py", line 5785, in report_retry
    raise e
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/common.py", line 232, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/common.py", line 243, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/utils.py", line 625, in sanitize_open
    stream = open(filename, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: 'bipbopall [bipbopall].mp4.part-Frag0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/YoutubeDL.py", line 1467, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/YoutubeDL.py", line 1478, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/YoutubeDL.py", line 1575, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/YoutubeDL.py", line 1634, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/YoutubeDL.py", line 2731, in process_video_result
    self.process_info(new_info)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/YoutubeDL.py", line 3194, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/YoutubeDL.py", line 2918, in dl
    return fd.download(name, new_info, subtitle)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/common.py", line 446, in download
    ret = self.real_download(filename, info_dict)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/hls.py", line 258, in real_download
    return fd.real_download(filename, info_dict)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/external.py", line 48, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/external.py", line 327, in _call_downloader
    return super()._call_downloader(tmpfilename, info_dict)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/downloader/external.py", line 167, in _call_downloader
    self.report_error(f'Unable to open fragment {frag_index}; {err}')
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/YoutubeDL.py", line 997, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/Users/mini/Downloads/temps/yt-dlp/yt_dlp/YoutubeDL.py", line 937, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Unable to open fragment 0; [Errno 2] No such file or directory: 'bipbopall [bipbopall].mp4.part-Frag0'
```

**Comment by crbyxwpzfl** [comment]
just realised that I would need to implement a whole cleanup/fixup off all fragments.
perhaps it is possible to run yt_dlps own fixup functions over the fragments once aria is done but for now thats too much effort for me.

gerneraly I hope some day either aria supports hls or ytdlp uses a singe aria deamon just to unify all downloads.
(both probably dont even make sense like this)

**Comment by pukkandan** [comment]
Getting the fragment URLs through API will become possible with #5039

As for your actual requirement, what you want is for a way to multiple `YoutubeDL` instances to share a single `aria2` daemon, correct? I don't think this is something we can ever implement into yt-dlp itself. But if I can provide a way to "register" custom classes as downloaders (like we have for PPs), would you be able to implement this yourself?
