### ISSUE TITLE
canalsurmas.es

### ISSUE THREAD

**Issue by heroku-miraheze** [yt-dlp/yt-dlp#5516]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Spain

### Example URLs

https://www.canalsurmas.es/videos/category/8463-el-gran-queo

### Provide a description that is worded well enough to be understood

Canalsurmas.es will be supported by yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\joaqu>yt-dlp -vU --list-formats https://www.canalsurmas.es/videos/category/8463-el-gran-queo
[debug] Command-line config: ['-vU', '--list-formats', 'https://www.canalsurmas.es/videos/category/8463-el-gran-queo']
[debug] Portable config "C:\Users\joaqu\scoop\apps\yt-dlp\current\yt-dlp.conf": []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n5.1.2-4-gf5455889fd-20221102 (setts), ffprobe n5.1.2-4-gf5455889fd-20221102
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://www.canalsurmas.es/videos/category/8463-el-gran-queo
[generic] 8463-el-gran-queo: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 8463-el-gran-queo: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.canalsurmas.es/videos/category/8463-el-gran-queo
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.canalsurmas.es/videos/category/8463-el-gran-queo
```

**Comment by dirkf** [comment]
That's a series page?

A single video page is like:

https://www.canalsurmas.es/videos/detail/44006-el-gran-queo-1-lora-del-rio-sevilla-20072014

In either case the pages are made with Nuxt.js. For the linked show above, the media links appear to be the constant values of `direct_url` members in the JSON that the Nuxt hydration function of many, many arguments transforms.
