### ISSUE TITLE
[twitter] ERROR: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#5519]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Anywhere

### Provide a description that is worded well enough to be understood

Test link:
https://twitter.com/LockerRoomLOL/status/1591342028423860224

at the same time another links from this account seem to work fine..
https://twitter.com/LockerRoomLOL/status/1582657774672293888
https://twitter.com/LockerRoomLOL/status/1591377338574721026

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -F "https://twitter.com/LockerRoomLOL/status/1591342028423860224"
[debug] Command-line config: ['-vU', '-F', 'https://twitter.com/LockerRoomLOL/status/1591342028423860224']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.10.8 (CPython arm64 64bit) - macOS-12.6.1-arm64-arm-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1765 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [twitter] Extracting URL: https://twitter.com/LockerRoomLOL/status/1591342028423860224
[twitter] 1591342028423860224: Downloading guest token
[twitter] 1591342028423860224: Downloading JSON metadata
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/twitter.py", line 979, in _real_extract
    videos = map(extract_from_video_info, traverse_obj(status, media_path, expected_type=dict))
```

**Comment by someziggyman** [comment]
Looks like some bug on my end. apologies for the confusion, cloned recent git and it seems to work fine now.
