### ISSUE TITLE
theepochtimes

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#5524]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

test link:
https://www.theepochtimes.com/silence-patton-documentary_4849547.html?utm_source=Goodevening&src_src=Goodevening&utm_campaign=gv-2022-11-12&src_cmp=gv-2022-11-12&utm_medium=email&est=uyZCqTNmojfwLYHnMi5DS06s5f%2F6IM2LnN4Gt%2FUIpUKXLZEAH9cRusiMFw%3D%3D

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -F "https://www.theepochtimes.com/silence-patton-documentary_4849547.html?utm_source=Goodevening&src_src=Goodevening&utm_campaign=gv-2022-11-12&src_cmp=gv-2022-11-12&utm_medium=email&est=uyZCqTNmojfwLYHnMi5DS06s5f%2F6IM2LnN4Gt%2FUIpUKXLZEAH9cRusiMFw%3D%3D"
[debug] Command-line config: ['-vU', '-F', 'https://www.theepochtimes.com/silence-patton-documentary_4849547.html?utm_source=Goodevening&src_src=Goodevening&utm_campaign=gv-2022-11-12&src_cmp=gv-2022-11-12&utm_medium=email&est=uyZCqTNmojfwLYHnMi5DS06s5f%2F6IM2LnN4Gt%2FUIpUKXLZEAH9cRusiMFw%3D%3D']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.10.8 (CPython arm64 64bit) - macOS-12.6.1-arm64-arm-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1765 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [Epoch] Extracting URL: https://www.theepochtimes.com/silence-patton-documentary_4849547.html?utm_source=Goodevening&src_src=Goodevening&utm_campaign=gv-2022-11-12&src_cmp=gv-2022-11-12&utm_medium=email&est=uyZCqTNmojfwLYHnMi5DS06s5f%2F6IM2LnN4Gt%2FUIpUKXLZEAH9cRusiMFw%3D%3D
[Epoch] 4849547: Downloading webpage
[Epoch] 4849547: Downloading m3u8 information
ERROR: [Epoch] Extractor failed to obtain "id"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1493, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1590, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1649, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 2469, in process_video_result
    raise ExtractorError('Extractor failed to obtain "id"', ie=info_dict['extractor'])
yt_dlp.utils.ExtractorError: [Epoch] Extractor failed to obtain "id"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by flashdagger** [comment]
Because content is geo-restricted the video (https://allritesdeliver.s3.us-east-2.amazonaws.com/90265/main/play-90265.m3u8) is DRM protected. This is not supported, but of course the error message can be improved...
