### ISSUE TITLE
[bbc.co.uk] Failed to parse JSON Expecting value in '': line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jospezial** [yt-dlp/yt-dlp#5542]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

Whenever I find a possibly working proxy that is not geo blocked I get that error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vvv --proxy http://85.159.214.61:1080 --no-check-certificates --geo-bypass --geo-bypass-country UK 'https://www.bbc.co.uk/iplayer/episode/m00116r4/doctor-who-series-13-1-the-halloween-apocalypse?seriesId=m00116r6' 
[debug] Command-line config: ['-vvv', '--proxy', 'http://85.159.214.61:1080', '--no-check-certificates', '--geo-bypass', '--geo-bypass-country', 'UK', 'https://www.bbc.co.uk/iplayer/episode/m00116r4/doctor-who-series-13-1-the-halloween-apocalypse?seriesId=m00116r6']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.1.0-rc5-x86_64-AMD_Athlon-tm-_II_X2_240_Processor-with-glibc2.36 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.36)
[debug] exe versions: ffmpeg N-109075-g5d7de322d4 (fdk,setts), ffprobe N-109075-g5d7de322d4, rtmpdump 2.4
[debug] Optional libraries: Crypto-3.15.0, brotli-1.0.9, certifi-3021.03.16, sqlite3-2.6.0
[debug] Proxy map: {'http': 'http://85.159.214.61:1080', 'https': 'http://85.159.214.61:1080'}
[debug] Loaded 1723 extractors
[debug] Using fake IP None (UK) as X-Forwarded-For
[debug] [bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/m00116r4/doctor-who-series-13-1-the-halloween-apocalypse?seriesId=m00116r6
[bbc.co.uk] m00116r4: Downloading video page
[bbc.co.uk] m00116r4: Downloading playlist JSON
ERROR: [bbc.co.uk] m00116r4: m00116r4: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/bbc.py", line 576, in _real_extract
    programme_id, title, description, duration, formats, subtitles = self._download_playlist(group_id)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/bbc.py", line 447, in _download_playlist
    playlist = self._download_json(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1034, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1004, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 994, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 981, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 964, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 607, in decode
    return super().decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 978, in _parse_json
    return json.loads(
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 610, in decode
    raise type(e)(f'{e.msg} in {s[e.pos-10:e.pos+10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by dirkf** [comment]
Probably the site from which the metadata is fetched was blocked (returning empty JSON with no HTTP error) but yt-dlp didn't tell you, other than via the message you posted. The URL being accessed is http://www.bbc.co.uk/programmes/m00116r4/playlist.json, which you can check in your browser, or with _wget_ or _curl_.

Working fine from the UK with yt-dlp and with yt-dl git master.

**Comment by dirkf** [comment]
You could also try omitting the geo-bypass options.

**Comment by Vangelis66** [comment]
> The URL being accessed is 
> http://www.bbc.co.uk/programmes/m00116r4/playlist.json
>, which you can check in your browser, or with wget or curl.

That API isn't, actually, geo-sensitive (has never been), I can freely access it from "overseas": 
```json
{"info":{"readme":"For the use of Radio, Music and Programmes only"},"statsObject":{"parentPID":"m00116r4","parentPIDType":"episode"},"defaultAvailableVersion":{"pid":"m00116r2","types":["Original"],"smpConfig":{"title":"Doctor Who, Series 13, The Halloween Apocalypse","summary":"On Halloween, all across the universe, terrifying forces are stirring. What is the Flux?","masterBrandName":"BBC One","items":[{"vpid":"m00116r2","kind":"programme","duration":2940}],"holdingImageURL":"\/\/ichef.bbci.co.uk\/images\/ic\/$recipe\/p0b0mts8.jpg","guidance":null,"embedRights":"blocked"},"markers":[]},"allAvailableVersions":[{"pid":"m00116r2","types":["Original"],"smpConfig":{"title":"Doctor Who, Series 13, The Halloween Apocalypse","summary":"On Halloween, all across the universe, terrifying forces are stirring. What is the Flux?","masterBrandName":"BBC One","items":[{"vpid":"m00116r2","kind":"programme","duration":2940}],"holdingImageURL":"\/\/ichef.bbci.co.uk\/images\/ic\/$recipe\/p0b0mts8.jpg","guidance":null,"embedRights":"blocked"},"markers":[]}],"holdingImage":"\/\/ichef.bbci.co.uk\/images\/ic\/976x549\/p0b0mts8.jpg"}
```
If OP can't get a proper response through the used proxy (`85.159.214.61:1080`), that probably means the proxy has **very little useful bandwidth** or is **down**...

Speaking from well established experience 😜 of more than a decade, the Beeb **never fully block** UK proxy/VPN/SSH/etc. IPs to the point that nothing can be fetched through them... 
What they do (via dedicated personnel and, recently, automated software) is BLACKLIST those UK IPs (via Access-Control-Lists, **ACL**s) in the truly geo-sensitive `mediaselector` APIs (`*/open.live.bbc.co.uk/mediaselector/*`) and `stream CDNs` (akamai, cloudfront, bidi, fastly, etc.); when a UK IP has been blacklisted, it acts, in the context of i**Player**, as an overseas IP, meaning the geo-sensitive APIs/URIs would return a `geolocation` and/or  `403` (forbidden) error (in the case of UK-only video content) ...

To test one's IP as far as iPlayer is concerned, use: 
https://www.bbc.co.uk/userinfo
which returns a JSON response: 

Overseas IP: 
```json
{
  "X-Country": "2-letter-country-code other than gb",
  "X-Ip_is_uk_combined": "no",
  "X-Ip_is_advertise_combined": "yes"
}
```
Blacklisted UK IP: 
```json
{
  "X-Country": "gb",
  "X-Ip_is_uk_combined": "no",
  "X-Ip_is_advertise_combined": "no"
}
```
Whitelisted UK IP: 
```json
{
  "X-Country": "gb",
  "X-Ip_is_uk_combined": "yes",
  "X-Ip_is_advertise_combined": "no"
}
```
And when it comes to proxies for iPlayer, do make sure they properly support `HTTPS`...

> Whenever I find a possibly working proxy that is not geo-blocked

If OP thinks he could fetch **iPlayer** (video) content via a **free/open/public UK proxy** harvested from a Google (or similar) search, a change of direction is immediately advised... The "public" ones get **blacklisted** mere minutes after they appear on-line... 
One recent example: `185.237.99.218:61443`: 
```
[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '-v', '--proxy', 'http://185.237.99.218:61443', '--no-check-certificates', 'https://www.bbc.co.uk/iplayer/episode/m00116r4/doctor-who-series-13-1-the-halloween-apocalypse']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] ytdl-patched/yt-dlp version 2022.11.15.40298 [b9e88f3] (win_x86_exe)
[debug] Python 3.7.9 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 5.0 (fdk,setts), ffprobe 5.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'http://185.237.99.218:61443', 'https': 'http://185.237.99.218:61443'}
[debug] Loaded 1724 extractors
[debug] [bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/m00116r4/doctor-who-series-13-1-the-halloween-apocalypse
[bbc.co.uk] m00116r4: Downloading video page
[bbc.co.uk] m00116r4: Downloading playlist JSON
[bbc.co.uk] m00116r2: Downloading media selection JSON
[bbc.co.uk] m00116r2: Downloading media selection JSON
ERROR: [bbc.co.uk] m00116r4: bbc.co.uk returned error: geolocation
```
If I have said more than I should've, it was to thwart any additional proxy-related "queries" here... 

This issue should be closed as **invalid** (nothing to blame `yt-dlp` for) ; as testified by **dirkf**, the `bbc.co.ukIE` works as expected from **within the UK**; I can add to that that the ` --proxy` option **does work as intended with that IE** when a **truly whitelisted UK proxy** is used; but for the latter, you probably have to cough up some money for a UK proxy with a residential (non-datacentre) IP - and even then you won't be immune to BBC blacklisting, because "they" also check the amount of traffic requested from that IP...

**Comment by dirkf** [comment]
Notice that I mentioned the request being blocked and not explicitly why!

I can't help thinking that the unvarnished error message (`... Expecting value: line 1 column 1 (char 0)`) is more obscure than it should be. ECMA-404 says that an empty string can't be parsed as a JSON value, so an exception should be raised in the `_parse_json()` method, but it could be a separate `ValueError('No data to parse as JSON')` or some such.

**Comment by pukkandan** [comment]
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

@jospezial Double check this through the same proxy. If it works, show verbose without using geo-bypass. If it doesn't work in browser, there is nothing to be done
