### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by jirazy** [yt-dlp/yt-dlp#5564]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Czech Republic

### Example URLs

https://edu.ceskatelevize.cz/video/9988-osobnostni-typy-deti

### Provide a description that is worded well enough to be understood

I cannot download the lesson from czech TV

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://edu.ceskatelevize.cz/video/9988-osobnostni-typy-deti']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.0.5-1-default-x86_64-with-glibc2.36 (OpenSSL 1.1.1q  5 Jul 2022, glibc 2.36)
[debug] exe versions: ffmpeg 4.4.3 (fdk,setts), ffprobe 4.4.3
[debug] Optional libraries: Crypto-3.15.0, brotlicffi-1.0.9.2, certifi-2021.10.08, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://edu.ceskatelevize.cz/video/9988-osobnostni-typy-deti
[generic] 9988-osobnostni-typy-deti: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 9988-osobnostni-typy-deti: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://edu.ceskatelevize.cz/video/9988-osobnostni-typy-deti
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2721, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://edu.ceskatelevize.cz/video/9988-osobnostni-typy-deti
```

**Comment by bashonly** [comment]
for devs:

the webpage source has a JSON-LD block with an iframe URL in the `embedUrl` field

in the iframe source there is a javascript block with a line like this:
```javascript
getPlaylistUrl([{"type":"episode","id":"220553115500006","startTime":"8","stopTime":"1507"}], requestSource, 'html');
```
the iframe page first makes a POST request to:
`https://www.ceskatelevize.cz/ivysilani/ajax/get-client-playlist/`

with the cookies that were set, the custom header `{'x-addr': '127.0.0.1'}`, and this URL-encoded data:
```py
    {  # 'playlist' value is taken from the iframe source:
        'playlist': [{'type':'episode','id':'220553115500006','startTime':'8','stopTime':'1507'}],
        'requestUrl': '/ivysilani/embed/iFramePlayer.php',
        'requestSource': 'ctedu',  # this value could also be 'iVysilani', can be determined from iframe URL's query param 'origin'
        'type': 'html',  # 'type' value is taken from iframe source
        'canPlayDRM': 'true',  # check if this can successfully be set to 'false'
    }
```

the JSON response has a `url` for our final API call, a GET request to:
`https://www.ceskatelevize.cz/ivysilani/client-playlist/?key={key}`

which will return the necessary playlist data and metadata

**Comment by dirkf** [comment]
The `id` in the ld+json is the IDEC which is used for other cases. It's also the value of the `data-idec` attribute of the `div#video-player` element.

Hence if we 
1. allow the problem URL to match the `_VALID_URL`
2. allow `/video/` to match the paths that use embedded IDEC (currently `/(porady|zive)/`)
3. find the IDEC from one of the above places if there's no _NEXT_DATA_

the existing code that creates an embed URL works, as with the modified yt-dl back-port here:
```shell
$ python -m youtube_dl -v -F 'https://edu.ceskatelevize.cz/video/9988-osobnostni-typy-deti'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://edu.ceskatelevize.cz/video/9988-osobnostni-typy-deti']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 774b346f9
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[CeskaTelevize] 9988-osobnostni-typy-deti: Downloading webpage
[CeskaTelevize] 9988-osobnostni-typy-deti: Getting IFRAME hash
[CeskaTelevize] 9988-osobnostni-typy-deti: Downloading player
[CeskaTelevize] 9988-osobnostni-typy-deti: Downloading JSON metadata
[CeskaTelevize] 9988-osobnostni-typy-deti: Downloading JSON metadata
[CeskaTelevize] 9988-osobnostni-typy-deti: Downloading MPD manifest
[CeskaTelevize] 9988-osobnostni-typy-deti: Downloading JSON metadata
[CeskaTelevize] 9988-osobnostni-typy-deti: Downloading JSON metadata
[CeskaTelevize] 9988-osobnostni-typy-deti: Downloading m3u8 information
[info] Available formats for 61924494877882870:
format code          extension  resolution note
dash-main-1002-1504  m4a        audio only [ces] DASH audio  128k , m4a_dash container, mp4a.40.2 (48000Hz)
dash-main-1001-1502  mp4        512x288    DASH video  500k , mp4_dash container, avc1.4d4015, video only
dash-main-1001-1503  mp4        720x404    DASH video 1032k , mp4_dash container, avc1.4d401e, video only
dash-main-1001-1504  mp4        1024x576   DASH video 2048k , mp4_dash container, avc1.4d401f, video only
dash-main-1001-1505  mp4        1280x720   DASH video 3584k , mp4_dash container, avc1.4d401f, video only
dash-main-1001-1506  mp4        1920x1080  DASH video 6144k , mp4_dash container, avc1.4d4028, video only
hls-main-628         mp4        unknown     628k 
hls-main-1160        mp4        unknown    1160k 
hls-main-2176        mp4        unknown    2176k 
hls-main-3712        mp4        unknown    3712k 
hls-main-6272        mp4        unknown    6272k  (best)
$
```
Also, the hash parameter of the embed URL is available as the `data-hash` attribute of the `div#video-player`, so a couple of extra lines can remove the `Getting IFRAME hash` request.

A probably time-limited `hls-main-1160` for OP's benefit:
https://ivys-vst13-4.o2tv.cz/af/428212fd62016bb98eec503165cb9022/1668705672489/afaf882ea671bcccd0f6b256de2a33dfb/dna-61924494877882870-pc/61924494877882678/1503v1002.k.m3u8

**Comment by jirazy** [comment]
The 'OP' is me? May be. I do'nt know how to use URLs of hls-main-1160 or embedURL. Thanks.

**Comment by dirkf** [comment]
You can use the quoted embedURL with the existing yt-dlp (and yt-dl) extractor!

My associated question was for development in case there's an easy way to have yt-dlp use this page data: normally the `embedURL` is not extracted.

**Comment by jirazy** [comment]
embedURL works in browser but in yt-dlp got "Unsupported URL".

jzl@jizhp440:~/Downloads/F> yt-dlp -vU --cookies-from-browser firefox "https://edu.ceskatelevize.cz/ivysilani/embed/iFramePlayer.php?hash=4176d4904340310a75ecaa4612ee51a8a8b3ed2c&origin=ctedu&width=100%25&IDEC=220553115500006&start=8&end=1507"
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://edu.ceskatelevize.cz/ivysilani/embed/iFramePlayer.php?hash=4176d4904340310a75ecaa4612ee51a8a8b3ed2c&origin=ctedu&width=100%25&IDEC=220553115500006&start=8&end=1507']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.9.14 (CPython x86_64 64bit) - Linux-5.3.18-150300.59.98-default-x86_64-with-glibc2.31 (OpenSSL 1.1.1d  10 Sep 2019, glibc 2.31)
[debug] exe versions: ffmpeg 4.4 (fdk,setts), ffprobe 4.4
[debug] Optional libraries: sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/jzl/.mozilla/firefox/kzga87uq.muj-esr78-1600980708436/cookies.sqlite"
[Cookies] Extracted 382 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://edu.ceskatelevize.cz/ivysilani/embed/iFramePlayer.php?hash=4176d4904340310a75ecaa4612ee51a8a8b3ed2c&origin=ctedu&width=100%25&IDEC=220553115500006&start=8&end=1507
[generic] iFramePlayer: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] iFramePlayer: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://edu.ceskatelevize.cz/ivysilani/embed/iFramePlayer.php?hash=4176d4904340310a75ecaa4612ee51a8a8b3ed2c&origin=ctedu&width=100%25&IDEC=220553115500006&start=8&end=1507
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2721, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://edu.ceskatelevize.cz/ivysilani/embed/iFramePlayer.php?hash=4176d4904340310a75ecaa4612ee51a8a8b3ed2c&origin=ctedu&width=100%25&IDEC=220553115500006&start=8&end=1507

**Comment by dirkf** [comment]
Sorry, I should have clarified: drop the `edu.` prefix from the domain. The release code only expects a `www.` prefix, but I believe IDECs are not specific to the sub-domain.

**Comment by jirazy** [comment]
Thanks, I downloaded the lesson.
