### ISSUE TITLE
Youtube Upcoming Livestream extract_info()

### ISSUE THREAD

**Issue by vampiricwulf** [yt-dlp/yt-dlp#5567]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Trying to use the `extract_info` function on a live event that has yet to begin on youtube returns None and sends `yt_dlp.utils.DownloadError` along with `yt_dlp.utils.ExtractorError`. Most of the metadata should still be accessible even if the stream itself hasn't begun. 

For the below section, as I'm using the python module, I'm not sure how you would like me to handle it, but attached is the code and output.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
>>> url = 'https://www.youtube.com/@AkaiHaato/live'
>>> ydl_opts = {
... 'quiet': True,
... 'cookiefile': 'cookies.txt',
... 'match_filter': is_live,
... 'playlist_items': '1'
... }
>>> with yt_dlp.YoutubeDL(ydl_opts) as ydl:
...     info = ydl.extract_info(url, download=False)
...
ERROR: [youtube] Dv5bNXQzivM: This live event will begin in 48 minutes.
Traceback (most recent call last):
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\youtube.py", line 3862, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 1158, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: This live event will begin in 48 minutes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 700, in extract
    raise type(e)(e.orig_msg, **kwargs)
yt_dlp.utils.ExtractorError: [youtube] Dv5bNXQzivM: This live event will begin in 48 minutes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1474, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1582, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1661, in process_ie_result
    return self.extract_info(
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1474, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1503, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1004, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\Wulf\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 944, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] Dv5bNXQzivM: This live event will begin in 48 minutes.
>>> info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'info' is not defined
>>>
>>> url = 'https://www.youtube.com/watch?v=Dv5bNXQzivM'
>>> with yt_dlp.YoutubeDL(ydl_opts) as ydl:
...     info = ydl.extract_info(url, download=False)
...
ERROR: [youtube] Dv5bNXQzivM: This live event will begin in 47 minutes.
>>> ydl_opts = {
... 'quiet': True,
... 'cookiefile': 'cookies.txt',
... 'playlist_items': '1',
... 'ignoreerrors': True
... }
>>> with yt_dlp.YoutubeDL(ydl_opts) as ydl:
...     info = ydl.extract_info(url, download=False)
...
ERROR: [youtube] Dv5bNXQzivM: This live event will begin in 47 minutes.
>>> info
>>>
```

**Comment by pukkandan** [comment]
We have to raise error by default in this case in order to preserve backward compatibility with youtube-dl. You can however override it with https://github.com/yt-dlp/yt-dlp/blob/9f14daf22b4080ae1531a772ee7574959af4e2fa/yt_dlp/YoutubeDL.py#L213-L215

**Comment by vampiricwulf** [comment]
Oh my god, I'm an idiot, sorry, that didn't click in my head that it was the same error. Thank you so much for your quick response.
