### ISSUE TITLE
Odysee/LBRY urlopen error

### ISSUE THREAD

**Issue by Neurognostic** [yt-dlp/yt-dlp#5573]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Receiving the error `urlopen error [Errno -2] Name or service not known` when trying to access any Odysee/LBRY URL. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '--ignore-config', '-F', 'https://odysee.com/@reallygraceful:3/the-strange-connections-of-sam-bankman:7']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-6.0.6-76060006-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1,pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [lbry] Extracting URL: https://odysee.com/@reallygraceful:3/the-strange-connections-of-sam-bankman:7
[lbry] @reallygraceful#3/the-strange-connections-of-sam-bankman#7: Downloading stream JSON metadata
ERROR: [lbry] @reallygraceful:3/the-strange-connections-of-sam-bankman:7: Unable to download JSON metadata: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2,'Name or service not known')))
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line674, in extract
    ie_result = self._real_extract(url)
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/extractor/lbry.py", line 226, in _real_extract
    result = self._resolve_url(uri, display_id, 'stream')
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/extractor/lbry.py", line 46, in _resolve_url
    return self._call_api_proxy(
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/extractor/lbry.py", line 31, in _call_api_proxy
    response = self._download_json(
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line1034, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line998, in download_handle
    res = self._download_webpage_handle(
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line868, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line825, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line807, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3692, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/neurognostic/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 1527, in https_open
    return self.do_open(
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by flashdagger** [comment]
Odysee currently encountered performance problems. I can see, that they switched to an alternative API server.
Maybe only temporarily as the server name suggests.

This change will do:
```patch
diff --git a/yt_dlp/extractor/lbry.py b/yt_dlp/extractor/lbry.py
--- a/yt_dlp/extractor/lbry.py	(revision bc87dac75f289581bb2cd98500015c4d6a9027de)
+++ b/yt_dlp/extractor/lbry.py	(date 1668700937061)
@@ -29,7 +29,7 @@
         if token:
             headers['x-lbry-auth-token'] = token
         response = self._download_json(
-            'https://api.lbry.tv/api/v1/proxy',
+            'https://api.na-backend.odysee.com/api/v1/proxy',
             display_id, 'Downloading %s JSON metadata' % resource,
             headers=headers,
             data=json.dumps({
```

**Comment by Neurognostic** [comment]
> I can see, that they switched to an alternative API server.

Thanks for finding it.

> Maybe only temporarily as the server name suggests.

Server name doesn't look temporary to me. "North-America Backend"

**Comment by Lamieur** [comment]
I'm in Europe and my browser still calls https://api.na-backend.odysee.com/api/v1/proxy - and they used to have a big farm in France so I'd assume my browser wouldn't have to call NA servers under normal circumstances. So I agree, this does look temporary.

My yt-dlp 2022.10.04 works fine after changing that url in lbry.py, thanks flashdagger!

**Comment by flashdagger** [comment]
> Server name doesn't look temporary to me. "North-America Backend"

Then it will be surely updated. Maybe there should be a set of alternatives...

**Comment by cwegener** [comment]
For installing from the PR, this is how I do it:

```
pipx install --suffix '@git' git+https://github.com/yt-dlp/yt-dlp/@refs/pull/5585/head
```

**Comment by Ulmo** [comment]
> I'm in Europe and my browser still calls https://api.na-backend.odysee.com/api/v1/proxy - and they used to have a big farm in France so I'd assume my browser wouldn't have to call NA servers under normal circumstances. So I agree, this does look temporary.
> 
> My yt-dlp 2022.10.04 works fine after changing that url in lbry.py, thanks flashdagger!

It doesn't look temporary for North America!  A fix is needed.  I'm trying to see if there is code to fix this ... 2022.11.11 hasn't worked yet.

**Comment by Ulmo** [comment]
> pipx install --suffix '@git' git+https://github.com/yt-dlp/yt-dlp/@refs/pull/5585/head

That doesn't work:

$0 pipx install --suffix '@git' git+https://github.com/yt-dlp/yt-dlp/@refs/pull/5585/head
usage: pipx [-h] [--version] {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall-all,list,run,ensurepath} ...
pipx: error: unrecognized arguments: --suffix git+https://github.com/yt-dlp/yt-dlp/@refs/pull/5585/head
$2

**Comment by csehszlovakze** [comment]
Here's another one from **Hungary** , mine has bundled python due to compatibility issues (a.k.a. yt-dlp_linux):

```
$ yt-dlp -vUF https://odysee.com/@DistroTube:2/how-to-turn-any-website-into-a-desktop:b
[debug] Command-line config: ['-vUF', 'https://odysee.com/@DistroTube:2/how-to-turn-any-website-into-a-desktop:b']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (linux_exe)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-4.15.0-144-generic-x86_64-with-glibc2.27 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.27)
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [lbry] Extracting URL: https://odysee.com/@DistroTube:2/how-to-turn-any-website-into-a-desktop:b
[lbry] @DistroTube#2/how-to-turn-any-website-into-a-desktop#b: Downloading stream JSON metadata
ERROR: [lbry] @DistroTube:2/how-to-turn-any-website-into-a-desktop:b: Unable to download JSON metadata: HTTP Error 405: Method Not Allowed (caused by <HTTPError 405: 'Method Not Allowed'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 674, in extract
  File "yt_dlp/extractor/lbry.py", line 226, in _real_extract
  File "yt_dlp/extractor/lbry.py", line 46, in _resolve_url
  File "yt_dlp/extractor/lbry.py", line 31, in _call_api_proxy
  File "yt_dlp/extractor/common.py", line 1034, in download_content
  File "yt_dlp/extractor/common.py", line 998, in download_handle
  File "yt_dlp/extractor/common.py", line 868, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 825, in _request_webpage

  File "yt_dlp/extractor/common.py", line 807, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 3692, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 634, in http_response
  File "urllib/request.py", line 557, in error
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 749, in http_error_302
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 634, in http_response
  File "urllib/request.py", line 563, in error
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 405: Method Not Allowed

```

Is there any parameter I can pass to the executable until this gets fixed?
