### ISSUE TITLE
Embedded Python script problems with download_range_func

### ISSUE THREAD

**Issue by stcoats** [yt-dlp/yt-dlp#5587]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am trying to use the embedded Python functions. I keep getting this error:
![image](https://user-images.githubusercontent.com/32770789/202793138-7cb47bfe-68d5-4414-9a26-595c12439092.png)

Here is my script, schematically

```for i,x in df.iterrows():
    p= re.compile(regexstuff,re.IGNORECASE)
    if p.search(x["text"]):
        finds1 = p.findall(x["text"])
        if p.search(x["text_pos"]):
          for i,y in enumerate(finds1):
                  ydl_opts = {'format':'ba[ext=m4a]/ba[ext=mp4]','overwrites' : True,'extract-audio':True,
                              'outtmpl': 'path',
                              'download_ranges': download_range_func([], [(x, y )])}
                  with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                      try:
                          ydl.download('https://www.youtube.com/watch?v='+x["video_id"])
  
                      except:
                          print("exception")
            else:
                pass

```
I have tried it with installing static-ffmpeg with pip and also apt-install ffmpeg.

Also, running yt-dlp from the command line with download ranges functions as expected. In addition, this script works on a different VM I have set up.

Any tips you can provide will be appreciated!

**Comment by bashonly** [comment]
I see no error. I don't see any yt-dlp output at all. I see ffmpeg beginning to run, and then the screenshot ends

Add `'verbose': True` to your opts and show the full log (as text). Follow the issue template

Proofread your code example and elaborate on it. There's some stuff that doesn't make sense in there, e.g. passing the dict `x` as an arg to `download_range_func`

**Comment by stcoats** [comment]
I'm having problems with my VM setup now so I will close this issue and open a new one once I have the script running on the new VM, if it is not working as intended.

**Comment by stcoats** [comment]
The problem was the download range in the options:

`ydl_opts = {'format':'ba[ext=m4a]/ba[ext=mp4]','overwrites' : True,'extract-audio': True,
                              'outtmpl': '/path/to/file',
                              'download_ranges': download_range_func([], [(a, b)])}`

In the script I have running on another machine, `(a, b)` specified starting time and duration, so (120, 20) for getting a 20-second segment starting at the two-minute mark. 

Now, the correct input is apparently `(start, end)`, so it had to be changed to (120, 140). I guess this syntax was updated in YouTube-DL and I missed it.

**Comment by pukkandan** [comment]
> I guess this syntax was updated in YouTube-DL and I missed it.

The syntax is unchanged since the function was created

**Comment by stcoats** [comment]
On one VM I used download_range_func([], [(100, 20)]). On the second, this didn't work, so I posted an issue here. The problem was that it needs to be download_range_func([], [(100, 120)]). The two verbose outputs are below. 

Looking at the two verbose outputs, it seems the ffmpeg versions are different, so maybe that is the reason why the download_ranges_func syntax was changed. In any case, I initially thought I had problems with my ffmpeg installation on the newer VM and tried removing it and re-installing. I'm posting this as a follow-up in case someone else has a similar issue and finds this by conducting a web search.

Thanks, by the way, for maintaining this package, which is very useful!

First VM script and output:
```
import yt_dlp
from yt_dlp.utils import download_range_func

time1 = 100
dur = 20

vids = ["NkKV0Ze1Z6M"]
for x in vids:
    ydl_opts = {'format':'ba[ext=m4a]/ba[ext=mp4]',
                'overwrites' : True,
                'extract-audio':True,
                'download_ranges': download_range_func([], [(time1, dur)]),
                'verbose':True
                }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                    try:
                        ydl.download('https://www.youtube.com/watch?v='+x)
                    except yt_dlp.utils.DownloadError:
                        print("exception")

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.7.7 (CPython 64bit) - Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.7.1908-Core (glibc 2.10)
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2.8.15 (fdk,needs_adtstoasc), ffprobe 2.8.15, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2020.04.05.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=NkKV0Ze1Z6M
[youtube] NkKV0Ze1Z6M: Downloading webpage
[youtube] NkKV0Ze1Z6M: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] NkKV0Ze1Z6M: Downloading 1 format(s): 140
[info] NkKV0Ze1Z6M: Downloading 1 time ranges: 100.0-20.0
[debug] Invoking ffmpeg downloader on "https://rr1---sn-ovgq0oxu-5goe.googlevideo.com/videoplayback?expire=1669031576&ei=NxJ7Y5T5PJnO7AT6rrGoCA&ip=193.166.25.97&id=o-AFUyjp711ua_zDi5UF_NHr5DRUwgEx8HrsfcKQGIrDZK&itag=140&source=youtube&requiressl=yes&mh=BV&mm=31%2C29&mn=sn-ovgq0oxu-5goe%2Csn-5goeenes&ms=au%2Crdu&mv=m&mvi=1&pl=16&initcwndbps=1967500&spc=SFxXNiV98w9ZFTAGSDNtO29C5J4hggU&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=26147336&dur=1615.597&lmt=1561224585250174&mt=1669009503&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANvbGZQW-yYjw8KYg8EdWsWnjOSzkfrOcFT-_lmvH5k2AiEAw1EMweUNdHCItWvxcqwOOSp6nExja4znitJWl0E_6Qo%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgC7NEPNvRoFKezFIj-1E87g5DV_0yWg9jGUs0cUo5S58CIQD9PJn7gX1nDZwrkqB9xbiCchCfZ_P-TMbZZ3afMSlmog%3D%3D"
[download] Destination: Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 100 -t -80 -i 'https://rr1---sn-ovgq0oxu-5goe.googlevideo.com/videoplayback?expire=1669031576&ei=NxJ7Y5T5PJnO7AT6rrGoCA&ip=193.166.25.97&id=o-AFUyjp711ua_zDi5UF_NHr5DRUwgEx8HrsfcKQGIrDZK&itag=140&source=youtube&requiressl=yes&mh=BV&mm=31%2C29&mn=sn-ovgq0oxu-5goe%2Csn-5goeenes&ms=au%2Crdu&mv=m&mvi=1&pl=16&initcwndbps=1967500&spc=SFxXNiV98w9ZFTAGSDNtO29C5J4hggU&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=26147336&dur=1615.597&lmt=1561224585250174&mt=1669009503&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANvbGZQW-yYjw8KYg8EdWsWnjOSzkfrOcFT-_lmvH5k2AiEAw1EMweUNdHCItWvxcqwOOSp6nExja4znitJWl0E_6Qo%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgC7NEPNvRoFKezFIj-1E87g5DV_0yWg9jGUs0cUo5S58CIQD9PJn7gX1nDZwrkqB9xbiCchCfZ_P-TMbZZ3afMSlmog%3D%3D' -c copy -f ipod 'file:Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a.part'
[ffmpeg] Downloaded 324530 bytes
[download] 100% of  316.92KiB in 00:00:12 at 26.01KiB/s
[FixupM4a] Correcting container of "Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a' -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart 'file:Ligeti - Musica Ricercata [NkKV0Ze1Z6M].temp.m4a'
```

Second VM script and output: 

```
import yt_dlp
from yt_dlp.utils import download_range_func

time1 = 100
dur = 20

vids = ["NkKV0Ze1Z6M"]
for x in vids:
    ydl_opts = {'format':'ba[ext=m4a]/ba[ext=mp4]',
                'overwrites' : True,
                'extract-audio':True,
                'download_ranges': download_range_func([], [(time1, dur)]),
                'verbose':True
                }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                    try:
                        ydl.download('https://www.youtube.com/watch?v='+x)
                    except yt_dlp.utils.DownloadError:
                        print("exception")

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version 2022.11.11 [8b64402] (pip) API
[debug] params: {'format': 'ba[ext=m4a]/ba[ext=mp4]', 'overwrites': True, 'extract-audio': True, 'download_ranges': <yt_dlp.utils.download_range_func object at 0x7f261ea9be90>, 'verbose': True, 'compat_opts': set()}
[debug] Python 3.7.7 (CPython x86_64 64bit) - Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core (OpenSSL 1.0.2k-fips  26 Jan 2017, glibc 2.17)
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=NkKV0Ze1Z6M
[youtube] NkKV0Ze1Z6M: Downloading webpage
[youtube] NkKV0Ze1Z6M: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] NkKV0Ze1Z6M: Downloading 1 format(s): 140
[info] NkKV0Ze1Z6M: Downloading 1 time ranges: 100.0-20.0
[debug] Invoking ffmpeg downloader on "https://rr1---sn-ovgq0oxu-5goe.googlevideo.com/videoplayback?expire=1669031490&ei=4hF7Y5SgM4nuyQWu0YoI&ip=86.50.229.156&id=o-AK8OMOboNPQGtgiFUXojTccHrLka7TcVAxcBQQmJyM3g&itag=140&source=youtube&requiressl=yes&mh=BV&mm=31%2C29&mn=sn-ovgq0oxu-5goe%2Csn-5goeenes&ms=au%2Crdu&mv=m&mvi=1&pl=18&initcwndbps=950000&spc=SFxXNh68f4jsBQuhysvTg1BYSvfYG3E&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=26147336&dur=1615.597&lmt=1561224585250174&mt=1669009503&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgWU2L4Zie9xGXcYzBlIhmyTUc-xDtBALjqELj0NY532UCIHqFHe7gRy3A2A1tLXShJkhyaF78rtDEfCurLVi2jLAR&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgcjyf2yTPfCx8jEUsetNcOH6JtgJLe2l0d0JJzNDjbKECIQC-JBPAalP7pcgQg9tt7hmUw1ooGGmzVua0eY9BlwVmaw%3D%3D"
[download] Destination: Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 100 -t -80 -i 'https://rr1---sn-ovgq0oxu-5goe.googlevideo.com/videoplayback?expire=1669031490&ei=4hF7Y5SgM4nuyQWu0YoI&ip=86.50.229.156&id=o-AK8OMOboNPQGtgiFUXojTccHrLka7TcVAxcBQQmJyM3g&itag=140&source=youtube&requiressl=yes&mh=BV&mm=31%2C29&mn=sn-ovgq0oxu-5goe%2Csn-5goeenes&ms=au%2Crdu&mv=m&mvi=1&pl=18&initcwndbps=950000&spc=SFxXNh68f4jsBQuhysvTg1BYSvfYG3E&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=26147336&dur=1615.597&lmt=1561224585250174&mt=1669009503&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgWU2L4Zie9xGXcYzBlIhmyTUc-xDtBALjqELj0NY532UCIHqFHe7gRy3A2A1tLXShJkhyaF78rtDEfCurLVi2jLAR&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgcjyf2yTPfCx8jEUsetNcOH6JtgJLe2l0d0JJzNDjbKECIQC-JBPAalP7pcgQg9tt7hmUw1ooGGmzVua0eY9BlwVmaw%3D%3D' -c copy -f ipod 'file:Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a.part'
ffmpeg version 3.4.11 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-44)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-indev=jack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --disable-encoder=libopus --enable-libpulse --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[ffmpeg] Downloaded 254 bytes
[download] 100% of    254.00B in 00:00:01 at 179.61B/s
[FixupM4a] Correcting container of "Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a"
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://rr1---sn-ovgq0oxu-5goe.googlevideo.com/videoplayback?expire=1669031490&ei=4hF7Y5SgM4nuyQWu0YoI&ip=86.50.229.156&id=o-AK8OMOboNPQGtgiFUXojTccHrLka7TcVAxcBQQmJyM3g&itag=140&source=youtube&requiressl=yes&mh=BV&mm=31%2C29&mn=sn-ovgq0oxu-5goe%2Csn-5goeenes&ms=au%2Crdu&mv=m&mvi=1&pl=18&initcwndbps=950000&spc=SFxXNh68f4jsBQuhysvTg1BYSvfYG3E&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=26147336&dur=1615.597&lmt=1561224585250174&mt=1669009503&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgWU2L4Zie9xGXcYzBlIhmyTUc-xDtBALjqELj0NY532UCIHqFHe7gRy3A2A1tLXShJkhyaF78rtDEfCurLVi2jLAR&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgcjyf2yTPfCx8jEUsetNcOH6JtgJLe2l0d0JJzNDjbKECIQC-JBPAalP7pcgQg9tt7hmUw1ooGGmzVua0eY9BlwVmaw%3D%3D':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    creation_time   : 2019-06-22T17:29:01.000000Z
  Duration: 00:26:55.60, start: 0.000000, bitrate: 129 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 0 kb/s (default)
    Metadata:
      creation_time   : 2019-06-22T17:29:01.000000Z
      handler_name    : ISO Media file produced by Google Inc.
[ipod @ 0x93c560] Warning, extension is not .m4a nor .m4v Quicktime/Ipod might not play the file
Output #0, ipod, to 'file:Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a.part':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    encoder         : Lavf57.83.100
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 0 kb/s (default)
    Metadata:
      creation_time   : 2019-06-22T17:29:01.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
No more output streams to write to, finishing.
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Input file #0 (https://rr1---sn-ovgq0oxu-5goe.googlevideo.com/videoplayback?expire=1669031490&ei=4hF7Y5SgM4nuyQWu0YoI&ip=86.50.229.156&id=o-AK8OMOboNPQGtgiFUXojTccHrLka7TcVAxcBQQmJyM3g&itag=140&source=youtube&requiressl=yes&mh=BV&mm=31%2C29&mn=sn-ovgq0oxu-5goe%2Csn-5goeenes&ms=au%2Crdu&mv=m&mvi=1&pl=18&initcwndbps=950000&spc=SFxXNh68f4jsBQuhysvTg1BYSvfYG3E&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=26147336&dur=1615.597&lmt=1561224585250174&mt=1669009503&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgWU2L4Zie9xGXcYzBlIhmyTUc-xDtBALjqELj0NY532UCIHqFHe7gRy3A2A1tLXShJkhyaF78rtDEfCurLVi2jLAR&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgcjyf2yTPfCx8jEUsetNcOH6JtgJLe2l0d0JJzNDjbKECIQC-JBPAalP7pcgQg9tt7hmUw1ooGGmzVua0eY9BlwVmaw%3D%3D):
  Input stream #0:0 (audio): 1 packets read (366 bytes); 
  Total: 1 packets (366 bytes) demuxed
Output file #0 (file:Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a.part):
  Output stream #0:0 (audio): 0 packets muxed (0 bytes); 
  Total: 0 packets (0 bytes) muxed
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a' -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart 'file:Ligeti - Musica Ricercata [NkKV0Ze1Z6M].temp.m4a'
[debug] ffmpeg version 3.4.11 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-44)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-indev=jack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --disable-encoder=libopus --enable-libpulse --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Ligeti - Musica Ricercata [NkKV0Ze1Z6M].m4a':
  Metadata:
    major_brand     : M4A 
    minor_version   : 512
    compatible_brands: isomiso2
    encoder         : Lavf57.83.100
  Duration: 00:00:00.00, bitrate: N/A
Stream map '0' matches no streams.
To ignore this, add a trailing '?' to the map.

ERROR: Postprocessing: To ignore this, add a trailing '?' to the map.
Traceback (most recent call last):
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3276, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3453, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3435, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3414, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 873, in run
    self._fixup('Correcting container', info['filepath'], [*self.stream_copy_opts(), '-f', 'mp4'])
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 854, in _fixup
    self.run_ffmpeg(filename, temp_filename, options)
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 368, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 325, in run_ffmpeg_multiple_files
    [(out_path, opts)], **kwargs)
  File "/home/cloud-user/env1/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 361, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: To ignore this, add a trailing '?' to the map.

exception
```

**Comment by Lesmiscore** [comment]
```
$ ./devscripts/parse-args.py --download-sec '*100-120'
{'download_ranges': download_range_func([], [(100.0, 120.0)])}
```
No, the syntax hasn't changed since it was created
ffmpeg version or yt-dlp version doesn't matter

**Comment by pukkandan** [comment]
What's happening is that the older ffmpeg is simply ignoring the error silently

**Comment by stcoats** [comment]
>What's happening is that the older ffmpeg is simply ignoring the error silently

The older version gets a 20-second segment from the targeted file beginning at 1:40. If I change the argument to `(100,120)`, it gets a two-minute segment beginning at 1:40. 

In the newer installation, `(100, 20)` results in an empty .m4a file of size 254 bytes (see above). `(100, 120)` results in the desired 20-second segment.
