### ISSUE TITLE
ERROR: Postprocessing:   Stream #1:0 -> #0:1

### ISSUE THREAD

**Issue by ssbroad** [yt-dlp/yt-dlp#559]
[Merger] Merging formats into "Girls' Generation  '  (Genie)' .aac"
ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)

try merging formats into wave, just same issue.

There is no such problem with the original youtube-dl

**Comment by Ashish0804** [comment]
provide verbose log and don't skip the template.

**Comment by pukkandan** [comment]
### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

Create a new issue using the correct template with all necessary information including the `--verbose` output

**Comment by hgontijo** [comment]
@Ashish0804, here's an example of this error:

Version:
```
$ yt-dlp --version
2022.02.04
```

```
$ yt-dlp -v -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail --ignore-errors --download-archive archive.txt https://www.youtube.com/watch?v=rYwmq5s3riE
[debug] Command-line config: ['-v', '-f', 'bestvideo+bestaudio', '--merge-output-format', 'mp4', '--write-thumbnail', '--ignore-errors', '--download-archive', 'archive.txt', 'https://www.youtube.com/watch?v=rYwmq5s3riE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-167-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: Crypto, secretstorage, sqlite
[debug] Proxy map: {}
[debug] Loading archive file 'archive.txt'
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=rYwmq5s3riE
[youtube] rYwmq5s3riE: Downloading webpage
[youtube] rYwmq5s3riE: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] rYwmq5s3riE: Downloading 1 format(s): 313+251
Deleting existing file 25分鐘 站立式快速燃脂運動 + 5分鐘拉筋｜訓練心肺功能_ 達至全日消脂效果｜一起令身體更fit🔥 [rYwmq5s3riE].webp
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: 25分鐘 站立式快速燃脂運動 + 5分鐘拉筋｜訓練心肺功能_ 達至全日消脂效果｜一起令身體更fit🔥 [rYwmq5s3riE].webp
[debug] Invoking downloader on "https://rr3---sn-n4v7sney.googlevideo.com/videoplayback?expire=1644988728&ei=2DQMYobfOtqWsfIPobGo0A0&ip=99.46.183.248&id=o-ABuQmMhUlsVDXcl-iCNDN3N4241usrJ0rt4APyu2bjvE&itag=313&source=youtube&requiressl=yes&mh=Md&mm=31%2C26&mn=sn-n4v7sney%2Csn-a5msen7l&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=1322500&vprv=1&mime=video%2Fwebm&gir=yes&clen=1867786609&dur=1824.520&lmt=1615210956986655&mt=1644966529&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOjnB1ysd6-QiP1_GowTD3AenF_LZ6ibwIhSj5MWO__DAiAo-mTIX78-kK_Wci74Ro_LQX7JNrO42x4fm2Al2zNadQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPlcizBlFk9ZbF0Q8ZTxcbI_Tvq1OWVZ6sayV5h71bW0AiEAtMtqLv1jCUfLYwO8odSAl1mje3Py7YiLnsHdWPSZAmc%3D"
[download] 25分鐘 站立式快速燃脂運動 + 5分鐘拉筋｜訓練心肺功能_ 達至全日消脂效果｜一起令身體更fit🔥 [rYwmq5s3riE].f313.webm has already been downloaded
[download] 100% of 1.74GiB
[debug] Invoking downloader on "https://rr3---sn-n4v7sney.googlevideo.com/videoplayback?expire=1644988728&ei=2DQMYobfOtqWsfIPobGo0A0&ip=99.46.183.248&id=o-ABuQmMhUlsVDXcl-iCNDN3N4241usrJ0rt4APyu2bjvE&itag=251&source=youtube&requiressl=yes&mh=Md&mm=31%2C26&mn=sn-n4v7sney%2Csn-a5msen7l&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=1322500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=27385304&dur=1824.621&lmt=1615203108758011&mt=1644966529&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANyC00XCWx7AoRwlzYhbmmH1nEFvhwvSCbUbvxcMZy44AiEA3W2OScXWplvoG58MuSIuSZpI7a5AKPx09nuohzs3OSQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPlcizBlFk9ZbF0Q8ZTxcbI_Tvq1OWVZ6sayV5h71bW0AiEAtMtqLv1jCUfLYwO8odSAl1mje3Py7YiLnsHdWPSZAmc%3D"
[download] 25分鐘 站立式快速燃脂運動 + 5分鐘拉筋｜訓練心肺功能_ 達至全日消脂效果｜一起令身體更fit🔥 [rYwmq5s3riE].f251.webm has already been downloaded
[download] 100% of 26.12MiB
[Merger] Merging formats into "25分鐘 站立式快速燃脂運動 + 5分鐘拉筋｜訓練心肺功能_ 達至全日消脂效果｜一起令身體更fit🔥 [rYwmq5s3riE].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:25分鐘 站立式快速燃脂運動 + 5分鐘拉筋｜訓練心肺功能_ 達至全日消脂效果｜一起令身體更fit🔥 [rYwmq5s3riE].f313.webm' -i 'file:25分鐘 站立式快速燃脂運動 + 5分鐘拉筋｜訓練心肺功能_ 達至全日消脂效果｜一起令身體更fit🔥 [rYwmq5s3riE].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:25分鐘 站立式快速燃脂運動 + 5分鐘拉筋｜訓練心肺功能_ 達至全日消脂效果｜一起令身體更fit🔥 [rYwmq5s3riE].temp.mp4'
[debug] ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, matroska,webm, from 'file:25分鐘 站立式快速燃脂運動 + 5分鐘拉筋｜訓練心肺功能_ 達至全日消脂效果｜一起令身體更fit🔥 [rYwmq5s3riE].f313.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:30:24.52, start: 0.000000, bitrate: 8189 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:25分鐘 站立式快速燃脂運動 + 5分鐘拉筋｜訓練心肺功能_ 達至全日消脂效果｜一起令身體更fit🔥 [rYwmq5s3riE].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:30:24.62, start: -0.007000, bitrate: 120 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
[mp4 @ 0x557a4fe1a020] track 1: codec frame size is not set
[mp4 @ 0x557a4fe1a020] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3296, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 117, in wrapper
    return func(self, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 830, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 296, in run_ffmpeg_multiple_files
    [(out_path, opts)], **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 333, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

[debug] Adding to archive: youtube rYwmq5s3riE
```

**Comment by pukkandan** [comment]
> [mp4 @ 0x557a4fe1a020] opus in MP4 support is experimental, add '-strict -2' if you want to use it.

You asked yt-dlp to merge into MP4 without using an ffmpeg that fully supports it

**Comment by matkoniecz** [comment]
> You asked yt-dlp to merge into MP4 without using an ffmpeg that fully supports it

Which version is needed?
