### ISSUE TITLE
ardaudiothek.de ARD Audiothek

### ISSUE THREAD

**Issue by selfisekai** [yt-dlp/yt-dlp#5605]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Netherlands

### Example URLs

- podcast series: https://www.ardaudiothek.de/sendung/legion-hacking-anonymous/12015417/
- podcast episode: https://www.ardaudiothek.de/episode/legion-hacking-anonymous/be-gay-do-crime-6-6/rbb/12109885/

### Provide a description that is worded well enough to be understood

looks similar to ardmediathek (which already has an extractor) and also uses GraphQL, but has different queries to be made so I think it's best as a new extractor

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.ardaudiothek.de/episode/legion-hacking-anonymous/be-gay-do-crime-6-6/rbb/12109885/', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: f352a0977
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-5.15.78-0-lts-x86_64-with (OpenSSL 3.0.7 1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Crypto-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1725 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://www.ardaudiothek.de/episode/legion-hacking-anonymous/be-gay-do-crime-6-6/rbb/12109885/
[generic] 12109885: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 12109885: Extracting information
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[debug] [generic] Extracting URL: https://www.ardaudiothek.de/embed/episode/12109885/
[generic] 12109885: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 12109885: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.ardaudiothek.de/embed/episode/12109885/
Traceback (most recent call last):
  File "/home/lauren/yt-dlp/yt_dlp/YoutubeDL.py", line 1495, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lauren/yt-dlp/yt_dlp/YoutubeDL.py", line 1571, in __extract_info
    ie_result = ie.extract(url)
  File "/home/lauren/yt-dlp/yt_dlp/extractor/common.py", line 678, in extract
    ie_result = self._real_extract(url)
  File "/home/lauren/yt-dlp/yt_dlp/extractor/generic.py", line 2460, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.ardaudiothek.de/embed/episode/12109885/
```

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/pull/22349

**Comment by clueless-skywatcher** [comment]
@dirkf I am willing to take this up. I discovered an ld+json in this site that contains the URL to the mp3 of this audio. What else would I need to look out for in this issue?

Also I would like some clarification about what is a triage issue?

**Comment by pukkandan** [comment]
You an copy the PR and modify it to fit our coding conventions. Alternately, if the PR gets merged in youtube-dl, I will port it over myself

**Comment by pukkandan** [comment]
> Also I would like some clarification about what is a triage issue?

It simply means that maintainers (in this case, me) have confirmed this to be a valid issue report

**Comment by dirkf** [comment]
Seems like there are several contenders to take this on: @someziggyman, @lukengda, @clueless-skywatcher. If @TinyToweringTree got the original branch un-banned, it would be easy to make a mergeable yt-dl PR. Otherwise https://github.com/ytdl-org/youtube-dl/pull/22349#issuecomment-1328252009.

**Comment by bashonly** [comment]
see https://github.com/yt-dlp/yt-dlp/issues/6364#issuecomment-1446066496
