### ISSUE TITLE
toggo.de - some urls fail

### ISSUE THREAD

**Issue by RalfKo** [yt-dlp/yt-dlp#5606]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

https://www.toggo.de/toggolino/pikwik-pack/videos/folge/schwimm-mit-dem-strom is "unsupported" (and a couple of others) while others on same site work.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe https://www.toggo.de/toggolino/pikwik-pack/videos/folge/schwimm-mit-dem-strom -vU
[debug] Command-line config: ['https://www.toggo.de/toggolino/pikwik-pack/videos/folge/schwimm-mit-dem-strom', '-vU']
[debug] User config "C:\Users\MyName\AppData\Roaming\yt-dlp\config.txt": ['--downloader', 'aria2c', '--downloader-args', 'aria2c:-c -j 3 -x 3 -s 3 -k 1M', '--downloader', 'dash,m3u8:native', '--restrict-filenames', '--merge-output-format', 'mkv']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://www.toggo.de/toggolino/pikwik-pack/videos/folge/schwimm-mit-dem-strom
[generic] schwimm-mit-dem-strom: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] schwimm-mit-dem-strom: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.toggo.de/toggolino/pikwik-pack/videos/folge/schwimm-mit-dem-strom
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.toggo.de/toggolino/pikwik-pack/videos/folge/schwimm-mit-dem-strom
```

**Comment by bashonly** [comment]
at first it looked like the problem was just with the `_VALID_URL` regex:
```diff
-    _VALID_URL = r'https?://(?:www\.)?toggo\.de/(?:toggolino/)?[^/?#]+/(?:folge|video)/(?P<id>[^/?#]+)'
+    _VALID_URL = r'https?://(?:www\.)?toggo\.de/(?:toggolino/)?[^/?#]+/(?:folge|videos?)/(?:folge/)?(?P<id>[^/?#]+)'
```

I tried fixing that, but then every URL I tested had DRM (Playready and Brightcove CENC). The Toggo extractor tries to get non-DRM formats by replacing `/cenc/` with `/clear/` in the fragment URL paths, but it looks like the Brightcove DASH URLs have token query params that break this workaround, and the fragments return 403 errors.

Test URLs:
https://www.toggo.de/toggolino/super-wings/folge/die-flieger-ueber-den-wolken
https://www.toggo.de/toggolino/pikwik-pack/videos/folge/schwimm-mit-dem-strom
https://www.toggo.de/toggolino/paw-patrol/video/paw-patrol-rettung-im-anflug
All DRM only as far as I can tell.

**Comment by RalfKo** [comment]
Thanks for looking into it!
