### ISSUE TITLE
tiktok - Unable to download user video list

### ISSUE THREAD

**Issue by zone559** [yt-dlp/yt-dlp#5611]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

so i am trying to get the tiktok to work and I am having issue. it is showing an error of Unable to download user video list.
anyone knowhow to fix this issue?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Desktop\Desktop\yt-dlp\dist>yt-dlp -vU https://www.tiktok.com/@mrbeast?lang=en
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@mrbeast?lang=en']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (win_exe)
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[debug] [tiktok:user] Extracting URL: https://www.tiktok.com/@mrbeast?lang=en
[tiktok:user] mrbeast: Downloading webpage
[tiktok:user] mrbeast: Downloading user video list page 1
ERROR: [tiktok:user] mrbeast: Unable to download user video list: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed')))
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\tiktok.py", line 653, in _real_extract
  File "yt_dlp\utils.py", line 5496, in traverse_obj
  File "yt_dlp\utils.py", line 5492, in _traverse_obj
  File "yt_dlp\utils.py", line 2808, in __bool__
  File "yt_dlp\utils.py", line 2800, in __getitem__
  File "yt_dlp\utils.py", line 5487, in <genexpr>
  File "yt_dlp\utils.py", line 5464, in apply_key
  File "yt_dlp\utils.py", line 2800, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 623, in _video_entries_api
  File "yt_dlp\extractor\tiktok.py", line 127, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 114, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 51, in _call_api_impl
  File "yt_dlp\extractor\common.py", line 1034, in download_content
  File "yt_dlp\extractor\common.py", line 998, in download_handle
  File "yt_dlp\extractor\common.py", line 868, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 825, in _request_webpage

  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1447, in connect
  File "http\client.py", line 941, in connect
  File "socket.py", line 826, in create_connection
  File "socket.py", line 961, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 807, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3692, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "yt_dlp\utils.py", line 1527, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

**Comment by pukkandan** [comment]
See pins

**Comment by zone559** [comment]
which pin comment?
Also I am trying to figure out what wrong with it and to fix the issue, why did you delete the case when I was trying to fix the issue?

**Comment by pukkandan** [comment]
> which pin comment?

I's not like there are thousands of pinned issues! https://github.com/yt-dlp/yt-dlp/issues/3766


> why did you delete the case when I was trying to fix the issue?

I didn't delete anything
