### ISSUE TITLE
No video formats found! (Udemy)

### ISSUE THREAD

**Issue by DmytroTronko** [yt-dlp/yt-dlp#5662]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I try to use Udemy Downloader to find a problem, as i understand yt_dlp cant see all available list of formats like 720p etc. 
bacause   "Udemy Downloader" have same problem...

I  recognised that error come only when comming link like 
"https://dash-enc-c.udemycdn.com/out/v1/a76bce0bb9204ca88b1d366f9e51f666/06c8dc12da2745f1b0b4e7c2c032dfef/2863df5b743847e5846f2b1343f3cbff/0b5a4ce589de4bda9d3a4860e543ad6e/index_audio_2_0_12.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kYXNoLWVuYy1jLnVkZW15Y2RuLmNvbS9vdXQvdjEvYTc2YmNlMGJiOTIwNGNhODhiMWQzNjZmOWU1MWY2NjYvMDZjOGRjMTJkYTI3NDVmMWIwYjRlN2MyYzAzMmRmZWYvMjg2M2RmNWI3NDM4NDdlNTg0NmYyYjEzNDNmM2NiZmYvMGI1YTRjZTU4OWRlNGJkYTlkM2E0ODYwZTU0M2FkNmUvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY2OTIzMjA0OX19fV19&Signature=ZvyND4QOQPwqALQNRuw2AjppPEoHcpUYl9Zb8acAZ81uqMrR6PwBK02BooQRMFN91uQ2CmFl8JNxeypU6UwaOffVgnc3NVDmuke18GV9aZ8beUEdD0b3x8hmhkFfF8cYeib6oyHwCOSe-ml-08N~d~lUMmVoeTklBd4taxdU48n4sB3Yyl-rV~CmHMXSuzES0-ac6ii8nC3te4jh44lzMSQ1KCdSWfGJhlZrfpzodnX1fDcknERRPxorXEnbs2hLf29w70tCZCVlkkyKe80IrKADs5v1Qabk1T~9rXHkq0H5HuoctWX0CQl1H96u8M0kzv1xwO7x3WmsgB1cx2av-Q__&Key-Pair-Id=APKAITJV77WS5ZT7262A"

In normal case its shoul be like "https://www.udemy.com/assets/31785130/files/2021-03-01_02-09-36-dee633c29f7d2f340f1bdd227aedc29b/2/hls/AVC_1920x1080_3200k_AAC-HE_64k/aa0032f7cd7997f526453c51a483e6c8bdf9.m3u8?provider=cloudfront&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAyMS0wMy0wMV8wMi0wOS0zNi1kZWU2MzNjMjlmN2QyZjM0MGYxYmRkMjI3YWVkYzI5Yi8yLyIsImV4cCI6MTY2OTIzMjAzOH0.4UjdOKL7nrQdevPTC_U87AtBVUnc5T-pLV8quFUBNsE&v=1"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'token.txt', 'https://www.udemy.com/git-and-github-bootcamp/', '-P', '/Users/dmytrotronko/Documents/UDEMY', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (source)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 9d52bf65f
[debug] Python 3.9.7 (CPython x86_64 64bit) - macOS-10.16-x86_64-i386-64bit (OpenSSL 1.1.1l  24 Aug 2021)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-None, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1728 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [udemy:course] Extracting URL: https://www.udemy.com/git-and-github-bootcamp/
[udemy:course] git-and-github-bootcamp: Downloading webpage
[udemy:course] 3792262: Downloading course curriculum
[download] Downloading playlist: 3792262
[udemy:course] Playlist 3792262: Downloading 187 items of 187
[download] Downloading item 1 of 187
[debug] [udemy] Extracting URL: https://www.udemy.com/git-and-github-bootcamp/learn/v4/t/lecture/24507864
[udemy] 24507864: Downloading webpage
[udemy] 24507864: Downloading lecture JSON
[udemy] 31785146: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 31785146: Downloading 1 format(s): hls-2847
[debug] Invoking hlsnative downloader on "https://www.udemy.com/assets/31785146/files/2021-03-01_02-10-54-e32e9233db768ef95842039e62ea0453/2/hls/AVC_1920x1080_6400k_AAC-HE_64k/aa009cdfe4466855ddacefabbcfd2ea425b4.m3u8?provider=cloudfront&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAyMS0wMy0wMV8wMi0xMC01NC1lMzJlOTIzM2RiNzY4ZWY5NTg0MjAzOWU2MmVhMDQ1My8yLyIsImV4cCI6MTY2OTY2NjkzM30.t2CRRGBaZ43mFqCA8Gu7U1mTyWiaq2Whg4b3ZeyGMjA&v=1"
[download] /Users/dmytrotronko/Documents/UDEMY/3792262/1 - Course Orientation/Welcome To The Course!.mp4 has already been downloaded
[download] 100% of   84.17MiB
[download] Downloading item 2 of 187
[debug] [udemy] Extracting URL: https://www.udemy.com/git-and-github-bootcamp/learn/v4/t/lecture/24911494
[udemy] 24911494: Downloading webpage
[udemy] 24911494: Downloading lecture JSON
[udemy] 31785142: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 31785142: Downloading 1 format(s): hls-679
[debug] Invoking hlsnative downloader on "https://www.udemy.com/assets/31785142/files/2021-03-01_02-10-51-8509acc50465e9867f2ef7a5de2fb915/2/hls/AVC_1920x1080_800k_AAC-HE_64k/aa009672697768d8d75bdc017ce2a4abf146.m3u8?provider=cloudfront&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAyMS0wMy0wMV8wMi0xMC01MS04NTA5YWNjNTA0NjVlOTg2N2YyZWY3YTVkZTJmYjkxNS8yLyIsImV4cCI6MTY2OTY2NjkzNn0.zInKHiR4-UfJZp0lQZ8UpYZfgpLnXDgb-zk8Ok4-EZU&v=1"
[download] /Users/dmytrotronko/Documents/UDEMY/3792262/1 - Course Orientation/What The Course Covers.mp4 has already been downloaded
[download] 100% of   16.89MiB
[download] Downloading item 3 of 187
[debug] [udemy] Extracting URL: https://www.udemy.com/git-and-github-bootcamp/learn/v4/t/lecture/25185344
[udemy] 25185344: Downloading webpage
[udemy] 25185344: Downloading lecture JSON
[udemy] 31785130: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 31785130: Downloading 1 format(s): hls-1576
[debug] Invoking hlsnative downloader on "https://www.udemy.com/assets/31785130/files/2021-03-01_02-09-36-dee633c29f7d2f340f1bdd227aedc29b/2/hls/AVC_1920x1080_3200k_AAC-HE_64k/aa0032f7cd7997f526453c51a483e6c8bdf9.m3u8?provider=cloudfront&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAyMS0wMy0wMV8wMi0wOS0zNi1kZWU2MzNjMjlmN2QyZjM0MGYxYmRkMjI3YWVkYzI5Yi8yLyIsImV4cCI6MTY2OTY2NjkzN30.MDM5AlA9sgnx4pcLKIHXFzNUAs9kNkAI9lkEAtMvNEg&v=1"
[download] /Users/dmytrotronko/Documents/UDEMY/3792262/1 - Course Orientation/A Note On The Exercises.mp4 has already been downloaded
[download] 100% of   22.28MiB
[download] Downloading item 4 of 187
[debug] [udemy] Extracting URL: https://www.udemy.com/git-and-github-bootcamp/learn/v4/t/lecture/24911504
[udemy] 24911504: Downloading webpage
[udemy] 24911504: Downloading lecture JSON
ERROR: [udemy] 31785132: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 1495, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 1898, in __process_iterable_entry
    return self.process_ie_result(
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 1704, in process_ie_result
    return self.process_ie_result(
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 1651, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 2600, in process_video_result
    self.raise_no_formats(info_dict)
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 1036, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [udemy] 31785132: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading item 5 of 187
[debug] [udemy] Extracting URL: https://www.udemy.com/git-and-github-bootcamp/learn/v4/t/lecture/24911508
[udemy] 24911508: Downloading webpage
[udemy] 24911508: Downloading lecture JSON
ERROR: [udemy] 31691588: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 1495, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 1898, in __process_iterable_entry
    return self.process_ie_result(
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 1704, in process_ie_result
    return self.process_ie_result(
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 1651, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 2600, in process_video_result
    self.raise_no_formats(info_dict)
  File "/Users/dmytrotronko/Documents/UDEMY/main/yt-dlp/yt_dlp/YoutubeDL.py", line 1036, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [udemy] 31691588: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
Are you willing to share account details if a dev wants to look into this?

Related: #5647, #3626, https://github.com/ytdl-org/youtube-dl/issues/29925

Possibly caused by DRM?

**Comment by DmytroTronko** [comment]
I think so))
Need to evolve for the benefit of the community)
How do I get in touch with the developer?

**Comment by DmytroTronko** [comment]
some news?

**Comment by pukkandan** [comment]
You can send me the details: discord (pukkandan#4207) / reddit (/u/pukkandan) / email (pukkandan.ytdlp@gmail.com)

**Comment by DmytroTronko** [comment]
> You can send me the details: discord (pukkandan#4207) / reddit (/u/pukkandan) / email ([pukkandan.ytdlp@gmail.com](mailto:pukkandan.ytdlp@gmail.com))

I send it

**Comment by pukkandan** [comment]
Some courses have DRM, but non-DRM courses were also broken. I've fixed the latter and added proper error message for DRM

Make sure to change your password
