### ISSUE TITLE
--split-chapters fails when chapter name is very long

### ISSUE THREAD

**Issue by magnomad** [yt-dlp/yt-dlp#5668]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

If a chapter name is too long, --split-chapters causes a fatal error with "File name too long".

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f140', '--split-chapters', 'https://www.youtube.com/watch?v=Ifi5KkXig3s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.11.0 (CPython x86_64 64bit) - macOS-12.6.1-x86_64-i386-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg N-109185-g14c6093528 (fdk,setts), ffprobe N-109185-g14c6093528
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Ifi5KkXig3s
[youtube] Ifi5KkXig3s: Downloading webpage
[youtube] Ifi5KkXig3s: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Ifi5KkXig3s: Downloading 1 format(s): 140
[debug] Invoking http downloader on "https://rr1---sn-cu-nuos.googlevideo.com/videoplayback?expire=1669741254&ei=ZuaFY4KDBpKDp-oPqumW8Ao&ip=213.31.100.213&id=o-AEMn7tnGaHap3aviTdlwLD5gZB-eUMPp4RIhngm5Vtmj&itag=140&source=youtube&requiressl=yes&mh=kA&mm=31%2C29&mn=sn-cu-nuos%2Csn-cu-c9id&ms=au%2Crdu&mv=m&mvi=1&pl=25&initcwndbps=1595000&spc=SFxXNtnK6sKtQ7NVoDZV8egLWttZlQg&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=148344252&dur=9166.123&lmt=1613789882757970&mt=1669719218&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPRqa4iwbGBwOBVXACG3rO1Hw1wCU95-GxLpO1kq_jZMAiEA8FfhahGUHCfJ78yG-enZxqbb4D2TdUbvkEguZ0PpeRU%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgE-U9AIrZgDKkcg7JuBMNx3wNmpEH4nsu5Lm3w2r6zwgCIC2ORxZVauRgvPu3Lw89vQuueeO5i9caak_I_Dz4EgCb"
[download] Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death [Ifi5KkXig3s].m4a has already been downloaded
[download] 100% of  141.37MiB
[SplitChapters] Splitting video by chapters; 12 chapters found
[SplitChapters] Chapter 001; Destination: Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death - 001 ＜Untitled Chapter 1＞ [Ifi5KkXig3s].m4a
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -ss 0 -t 242.0 -i 'file:Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death [Ifi5KkXig3s].m4a' -map 0 -dn -ignore_unknown -c copy -movflags +faststart 'file:Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death - 001 ＜Untitled Chapter 1＞ [Ifi5KkXig3s].m4a'
[SplitChapters] Chapter 002; Destination: Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death - 002 Right There's a Technical Term for that in Psychology It's Called Something like Multi Method Multi Trait Method of Determining whether or Not Something Is Accurate and the Idea Is the More Ways That You Can Measure It and Get the Same Result the More Confident You Can Be that You'Re Not Just Deluding Yourself with Your a Priori Hypothesis You Know that There's Actually Something Out There So I Guess that's another Part of this Method Is that and It's Also a Method That I Use in My in My Speaking I Think I Don't Try To Tell People Anything That Isn't Personally Relevant [Ifi5KkXig3s].m4a
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -ss 242.0 -t 23.0 -i 'file:Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death [Ifi5KkXig3s].m4a' -map 0 -dn -ignore_unknown -c copy -movflags +faststart 'file:Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death - 002 Right There'"'"'s a Technical Term for that in Psychology It'"'"'s Called Something like Multi Method Multi Trait Method of Determining whether or Not Something Is Accurate and the Idea Is the More Ways That You Can Measure It and Get the Same Result the More Confident You Can Be that You'"'"'Re Not Just Deluding Yourself with Your a Priori Hypothesis You Know that There'"'"'s Actually Something Out There So I Guess that'"'"'s another Part of this Method Is that and It'"'"'s Also a Method That I Use in My in My Speaking I Think I Don'"'"'t Try To Tell People Anything That Isn'"'"'t Personally Relevant [Ifi5KkXig3s].m4a'
[debug] ffmpeg version N-109185-g14c6093528 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/usr/local --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libopus --enable-libxvid --enable-libaom --enable-videotoolbox --enable-hwaccels --samples=fate-suite/
  libavutil      57. 43.100 / 57. 43.100
  libavcodec     59. 54.100 / 59. 54.100
  libavformat    59. 34.102 / 59. 34.102
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 50.101 /  8. 50.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death [Ifi5KkXig3s].m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.34.102
  Duration: 02:32:46.12, start: 0.000000, bitrate: 129 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
file:Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death - 002 Right There's a Technical Term for that in Psychology It's Called Something like Multi Method Multi Trait Method of Determining whether or Not Something Is Accurate and the Idea Is the More Ways That You Can Measure It and Get the Same Result the More Confident You Can Be that You'Re Not Just Deluding Yourself with Your a Priori Hypothesis You Know that There's Actually Something Out There So I Guess that's another Part of this Method Is that and It's Also a Method That I Use in My in My Speaking I Think I Don't Try To Tell People Anything That Isn't Personally Relevant [Ifi5KkXig3s].m4a: File name too long

ERROR: Postprocessing: file:Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death - 002 Right There's a Technical Term for that in Psychology It's Called Something like Multi Method Multi Trait Method of Determining whether or Not Something Is Accurate and the Idea Is the More Ways That You Can Measure It and Get the Same Result the More Confident You Can Be that You'Re Not Just Deluding Yourself with Your a Priori Hypothesis You Know that There's Actually Something Out There So I Guess that's another Part of this Method Is that and It's Also a Method That I Use in My in My Speaking I Think I Don't Try To Tell People Anything That Isn't Personally Relevant [Ifi5KkXig3s].m4a: File name too long
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3276, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3453, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3435, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3414, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 1051, in run
    self.real_run_ffmpeg([(in_file, opts)], [(destination, self.stream_copy_opts())])
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 361, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Lecture： Biblical Series IV： Adam and Eve： Self-Consciousness, Evil, and Death - 002 Right There's a Technical Term for that in Psychology It's Called Something like Multi Method Multi Trait Method of Determining whether or Not Something Is Accurate and the Idea Is the More Ways That You Can Measure It and Get the Same Result the More Confident You Can Be that You'Re Not Just Deluding Yourself with Your a Priori Hypothesis You Know that There's Actually Something Out There So I Guess that's another Part of this Method Is that and It's Also a Method That I Use in My in My Speaking I Think I Don't Try To Tell People Anything That Isn't Personally Relevant [Ifi5KkXig3s].m4a: File name too long
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195 except, use `-o chapter:...`
