### ISSUE TITLE
[huffingtonpost] Unsupported URL with warnings line 16 column 41 (char 1291)

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#5682]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Provide a description that is worded well enough to be understood

Test Link:
https://www.huffingtonpost.fr/life/article/les-joies-du-numerique-dans-les-transports-publics-quand-on-est-vieux_210323.html

Could be something in Gedi extractor or some typo in generic, not sure. the log says it all, I guess.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -F "https://www.huffingtonpost.fr/life/article/les-joies-du-numerique-dans-les-transports-publics-quand-on-est-vieux_210323.html"
[debug] Command-line config: ['-vU', '-F', 'https://www.huffingtonpost.fr/life/article/les-joies-du-numerique-dans-les-transports-publics-quand-on-est-vieux_210323.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.10.8 (CPython arm64 64bit) - macOS-12.6.1-arm64-arm-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1731 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://www.huffingtonpost.fr/life/article/les-joies-du-numerique-dans-les-transports-publics-quand-on-est-vieux_210323.html
[generic] les-joies-du-numerique-dans-les-transports-publics-quand-on-est-vieux_210323: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] les-joies-du-numerique-dans-les-transports-publics-quand-on-est-vieux_210323: Extracting information
[debug] Looking for embeds
WARNING: [generic] les-joies-du-numerique-dans-les-transports-publics-quand-on-est-vieux_210323: Failed to parse JSON: Expecting value in '          ]\n        ': line 7 column 29 (char 379)
WARNING: [generic] les-joies-du-numerique-dans-les-transports-publics-quand-on-est-vieux_210323: Failed to parse JSON: Expecting ',' delimiter in '          "url":"/au': line 16 column 41 (char 1291)
ERROR: Unsupported URL: https://www.huffingtonpost.fr/life/article/les-joies-du-numerique-dans-les-transports-publics-quand-on-est-vieux_210323.html
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1495, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1571, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 678, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/generic.py", line 2471, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.huffingtonpost.fr/life/article/les-joies-du-numerique-dans-les-transports-publics-quand-on-est-vieux_210323.html
```

**Comment by bashonly** [comment]
The JSON LD in that page contains invalid JSON, which causes the error. The JSON LD also doesn't have any info about the video embed.

The embed info is in the div tags:
```html
<div class="articleVideo"> <div class="asset asset-video">           <div id="gdpr-video-container-x8fjhwa"> <div class="video-container  padding-bottom-lg "> <div id="player-x8fjhwa" class="js_player" data-container-id="gdpr-video-container-x8fjhwa" data-id="x8fjhwa" data-provider="dailymotion" data-autoplay="false" data-showinfo="false" data-pipenabled="false"> 
```

Looks like this method of embedding dailymotion vids may be unique to huffpo, and if so, support for huffingtonpost.fr and for these kinds of embeds could be added to `huffpost.py`

As a workaround for now:

This URL works to download the vid with yt-dlp:
`https://geo.dailymotion.com/player.html?video=x8fjhwa`
And if you find more dailymotion embeds on that site that you want to download, you can view the HTML source, find the dailymotion div tag, take the `data-id` value and plug it in the `video=` query param in that dailymotion.com URL
