### ISSUE TITLE
anilist.co support

### ISSUE THREAD

**Issue by selfisekai** [yt-dlp/yt-dlp#5694]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Netherlands

### Example URLs

- https://anilist.co/anime/18679/Kill-la-Kill/ -> https://www.crunchyroll.com/kill-la-kill
- https://anilist.co/anime/139809/Lagtrain/ -> https://www.youtube.com/watch?v=UnIhRpIT7nc

### Provide a description that is worded well enough to be understood

anilist is an anime metadata and review service. it links to external services that have the media available legally. out of what is not DRM'd, I think just Crunchyroll and YouTube.

it has an open GraphQL API that can be easily used for this: https://anilist.co/graphiql?query=query%20(%24id%3A%20Int!)%20%7B%0A%20%20Media(id%3A%20%24id)%20%7B%0A%20%20%20%20externalLinks%20%7B%0A%20%20%20%20%20%20url%0A%20%20%20%20%20%20site%0A%20%20%20%20%7D%0A%20%20%20%20streamingEpisodes%20%7B%0A%20%20%20%20%20%20url%0A%20%20%20%20%20%20site%0A%20%20%20%20%20%20thumbnail%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22id%22%3A%2018679%0A%7D

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://anilist.co/anime/18679/Kill-la-Kill/', '-v']
[debug] User config "/home/lauren/.config/yt-dlp/config": ['--external-downloader', 'aria2c', '--concurrent-fragments', '8', '--netrc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: c9f5ce511
[debug] Python 3.11.0 (CPython x86_64 64bit) - Linux-5.15.80-0-lts-x86_64-with (OpenSSL 3.0.7 1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Crypto-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1731 extractors
[debug] [generic] Extracting URL: https://anilist.co/anime/18679/Kill-la-Kill/
[generic] Kill-la-Kill: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Kill-la-Kill: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://anilist.co/anime/18679/Kill-la-Kill/
Traceback (most recent call last):
  File "/home/lauren/yt-dlp/yt_dlp/YoutubeDL.py", line 1495, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lauren/yt-dlp/yt_dlp/YoutubeDL.py", line 1571, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/lauren/yt-dlp/yt_dlp/extractor/common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lauren/yt-dlp/yt_dlp/extractor/generic.py", line 2471, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://anilist.co/anime/18679/Kill-la-Kill/
```

**Comment by doe1080** [comment]
all Crunchyroll videos are now DRM-protected, and AniList pages contain no more than one YouTube trailer, so a separate IE is no longer needed
