### ISSUE TITLE
PornHub : No video formats found! - Video works in browser

### ISSUE THREAD

**Issue by ItsBeenTwentyMinutesCanIWipe** [yt-dlp/yt-dlp#5697]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Sweden

### Provide a description that is worded well enough to be understood

Downloading a pornhub video with the latest build and python 3.11 gives 403 error on all m3u8 information downloading, but the actual video is playable in the browser at Pornhub though the 1080p version is broken but 720p works.

Trying to check formats to download the 720p version does not work either and throws the 403 error but works in browser. Checking and no checking formats does not do anything. And i don't believe the json error has anything to do with it (hopefully).

Jdownloader also breaks and does not work.

Video with the issue: https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd

I will attach multiple outputs below.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS E:\> yt-dlp -vU --cookies-from-browser FIREFOX  --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" -F https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'FIREFOX', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36', '-F', 'https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (win_exe)
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-107135-g76ba5b2060-g6a02de2127 (fdk,setts), ffprobe N-107135-g76ba5b2060-g6a02de2127, phantomjs 2.1.1, rtmpdump 2.4-20220520-g922b131-GnuTLS_3.6.16-x86_64-static
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\xxxx\AppData\Roaming\Mozilla\Firefox\Profiles\vjerpocx.default\cookies.sqlite"
[Cookies] Extracted 2121 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1724 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd
[PornHub] ph638a8bb4851fd: Downloading pc webpage
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading JSON metadata
WARNING: [PornHub] ph638a8bb4851fd: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [PornHub] ph638a8bb4851fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1495, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1592, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1651, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2600, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1036, in raise_no_formats
yt_dlp.utils.ExtractorError: [PornHub] ph638a8bb4851fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

PS E:\> yt-dlp -vU --cookies-from-browser FIREFOX  --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" --check-formats -F https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'FIREFOX', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36', '--check-formats', '-F', 'https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (win_exe)
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-107135-g76ba5b2060-g6a02de2127 (fdk,setts), ffprobe N-107135-g76ba5b2060-g6a02de2127, phantomjs 2.1.1, rtmpdump 2.4-20220520-g922b131-GnuTLS_3.6.16-x86_64-static
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\xxxx\AppData\Roaming\Mozilla\Firefox\Profiles\vjerpocx.default\cookies.sqlite"
[Cookies] Extracted 2122 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1724 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd
[PornHub] ph638a8bb4851fd: Downloading pc webpage
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading JSON metadata
WARNING: [PornHub] ph638a8bb4851fd: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [PornHub] ph638a8bb4851fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1495, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1592, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1651, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2600, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1036, in raise_no_formats
yt_dlp.utils.ExtractorError: [PornHub] ph638a8bb4851fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

PS E:\> yt-dlp -vU --cookies-from-browser FIREFOX  --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" --check-all-formats -F https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'FIREFOX', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36', '--check-all-formats', '-F', 'https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (win_exe)
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-107135-g76ba5b2060-g6a02de2127 (fdk,setts), ffprobe N-107135-g76ba5b2060-g6a02de2127, phantomjs 2.1.1, rtmpdump 2.4-20220520-g922b131-GnuTLS_3.6.16-x86_64-static
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\xxxx\AppData\Roaming\Mozilla\Firefox\Profiles\vjerpocx.default\cookies.sqlite"
[Cookies] Extracted 2122 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1724 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd
[PornHub] ph638a8bb4851fd: Downloading pc webpage
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading JSON metadata
WARNING: [PornHub] ph638a8bb4851fd: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [PornHub] ph638a8bb4851fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1495, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1592, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1651, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2600, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1036, in raise_no_formats
yt_dlp.utils.ExtractorError: [PornHub] ph638a8bb4851fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

PS E:\> yt-dlp -vU --cookies-from-browser FIREFOX  --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" --no-check-formats -F https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'FIREFOX', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36', '--no-check-formats', '-F', 'https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (win_exe)
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-107135-g76ba5b2060-g6a02de2127 (fdk,setts), ffprobe N-107135-g76ba5b2060-g6a02de2127, phantomjs 2.1.1, rtmpdump 2.4-20220520-g922b131-GnuTLS_3.6.16-x86_64-static
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\xxxx\AppData\Roaming\Mozilla\Firefox\Profiles\vjerpocx.default\cookies.sqlite"
[Cookies] Extracted 2122 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1724 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd
[PornHub] ph638a8bb4851fd: Downloading pc webpage
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading JSON metadata
WARNING: [PornHub] ph638a8bb4851fd: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [PornHub] ph638a8bb4851fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1495, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1592, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1651, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2600, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1036, in raise_no_formats
yt_dlp.utils.ExtractorError: [PornHub] ph638a8bb4851fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

PS E:\> yt-dlp -vU --cookies-from-browser FIREFOX  --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" -f bestvideo*+bestaudio/best https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'FIREFOX', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36', '-f', 'bestvideo*+bestaudio/best', 'https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (win_exe)
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-107135-g76ba5b2060-g6a02de2127 (fdk,setts), ffprobe N-107135-g76ba5b2060-g6a02de2127, phantomjs 2.1.1, rtmpdump 2.4-20220520-g922b131-GnuTLS_3.6.16-x86_64-static
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\xxxx\AppData\Roaming\Mozilla\Firefox\Profiles\vjerpocx.default\cookies.sqlite"
[Cookies] Extracted 2122 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1724 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph638a8bb4851fd
[PornHub] ph638a8bb4851fd: Downloading pc webpage
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: HTTP Error 403: Forbidden
[PornHub] ph638a8bb4851fd: Downloading JSON metadata
WARNING: [PornHub] ph638a8bb4851fd: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [PornHub] ph638a8bb4851fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1495, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1592, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1651, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2600, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1036, in raise_no_formats
yt_dlp.utils.ExtractorError: [PornHub] ph638a8bb4851fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
Not a duplicate, but it looks closely related to #5615

Seems like fingerprinting is the culprit here also. I am able to get all formats using the [fix suggested in this PR](https://github.com/yt-dlp/yt-dlp/pull/5618#issuecomment-1326771710) and Python 3.10
