### ISSUE TITLE
Video title causes "[Errno 92] Illegal byte sequence"

### ISSUE THREAD

**Issue by exboreas** [yt-dlp/yt-dlp#5699]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

YouTube video with strange/illegal character in video title prevents download with "ERROR: unable to download video data: [Errno 92] Illegal byte sequence". 

`yt-dlp "https://www.youtube.com/watch?v=27rKhzGG1dM"`

The same video is downloaded correctly if the title is omitted from the output in this way:

`yt-dlp -o "%(id)s.%(ext)s" "https://www.youtube.com/watch?v=27rKhzGG1dM"`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=27rKhzGG1dM']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.11.0 (CPython x86_64 64bit) - macOS-12.2.1-x86_64-i386-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=27rKhzGG1dM
[youtube] 27rKhzGG1dM: Downloading webpage
[youtube] 27rKhzGG1dM: Downloading android player API JSON
[youtube] 27rKhzGG1dM: Downloading MPD manifest
[youtube] 27rKhzGG1dM: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 27rKhzGG1dM: Downloading 1 format(s): 248+251
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1670082960/ei/MB2LY6-vIZGvxN8P2Oi9-AQ/ip/2a02%3Ac7c%3A5c48%3Ab800%3Ac432%3A64b6%3Ade11%3Ad9e7/id/dbbaca873186d5d3/source/youtube/requiressl/yes/playback_host/rr7---sn-cn3tc-aigr.googlevideo.com/mh/Nd/mm/31%2C29/mn/sn-cn3tc-aigr%2Csn-aigzrnze/ms/au%2Crdu/mv/m/mvi/7/pl/44/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1811250/vprv/1/mt/1670060934/fvip/5/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgTP2pQziggYIDVkNXFrs5le6BUVh06CcCy_32P6POb3cCIQDnGP_PR03vUJXtOCV1nxM6xE0FmW7b99lMAqFkdmJb9w%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgJaoTeiDeVJoitSTOMTQCLK6ydNQWBWUe3F4r4So5pV8CIALSdPpqgDNCydyHu_k3fC9I6Gdwk3YSGo9JrLhqQgxj"
[dashsegments] Total fragments: 1582
[download] Destination: Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].f248.webm
ERROR: unable to download video data: [Errno 92] Illegal byte sequence: 'Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].f248.webm.ytdl'
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/utils.py", line 641, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/utils.py", line 2193, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 92] Illegal byte sequence: 'Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].f248.webm.ytdl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3182, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2924, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 446, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/downloader/dash.py", line 40, in real_download
    self._prepare_and_start_frag_download(ctx, fmt)
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/downloader/fragment.py", line 81, in _prepare_and_start_frag_download
    self._prepare_frag_download(ctx)
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/downloader/fragment.py", line 205, in _prepare_frag_download
    self._write_ytdl_file(ctx)
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/downloader/fragment.py", line 101, in _write_ytdl_file
    frag_index_stream, _ = self.sanitize_open(self.ytdl_filename(ctx['filename']), 'w')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 237, in wrapper
    retry.error_callback(err, 1, 0)
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 223, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/utils.py", line 5929, in report_retry
    raise e
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 232, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 243, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/utils.py", line 643, in sanitize_open
    stream = open(filename, open_mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 92] Illegal byte sequence: 'Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].f248.webm.ytdl'
```

**Comment by pukkandan** [comment]
Can someone else reproduce on MacOS and confirm? I don't have any mac devices

**Comment by dirkf** [comment]
Not reproducible on iPad OS with LibTerm (Python 3.7).

If my [analysis that the problem is the second emoticon, only introduced in Unicode 14](https://github.com/ytdl-org/youtube-dl/issues/31395#issuecomment-1336279215) is correct, should the `encodeFilename()` function be forcing filenames to `bytes` so that the Unicode encoding is passed transparently to the OS? But having said that, `unicodedata.unidata_version` is strictly less than 14 for three Linux Python versions I tried.

**Comment by dirkf** [comment]
Possibly a [problem with APFS](https://github.com/ytdl-org/youtube-dl/issues/31395#issuecomment-1337345535) only understanding Unicode 9.0, or some other version <14.

**Comment by exboreas** [comment]
Upgrading to latest macOS (13.0.1), which also includes upgrade to Python 3.11.0, solved it.
```
yt-dlp -vU "https://www.youtube.com/watch?v=27rKhzGG1dM"
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=27rKhzGG1dM']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.11.0 (CPython x86_64 64bit) - macOS-13.0.1-x86_64-i386-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=27rKhzGG1dM
[youtube] 27rKhzGG1dM: Downloading webpage
[youtube] 27rKhzGG1dM: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 27rKhzGG1dM: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr7---sn-cn3tc-aigr.googlevideo.com/videoplayback?expire=1670374364&ei=fI-PY5PlG_CCp-oP_4WvmAU&ip=2a02%3Ac7c%3A5c48%3Ab800%3A1d70%3A1e68%3A35e8%3A2e86&id=o-AEqoa8fLaElCvKLtIAdZbXI2mv2O0GkKelwfwtxYcSwX&itag=248&source=youtube&requiressl=yes&mh=Nd&mm=31%2C29&mn=sn-cn3tc-aigr%2Csn-aigzrnze&ms=au%2Crdu&mv=m&mvi=7&pl=44&initcwndbps=1536250&spc=SFxXNie7drl71leEuNMaTsPLN8d734A&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=1253994976&dur=8010.000&lmt=1670273999524722&mt=1670352323&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgIs8kNKQ0OkxfRoE4kqhvZWMgYNMXhUEBkyFpgnrbJyoCIQCrYRy96UImUI3r9uNmlyGBkewR0TjOUZfYK-WuRap5Ag%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgRQwL9Cnc1ZChBriMVKip7JCwl_rh-to_rCPs0TOgih8CIQDh_U_CCBPnJn-akUSlNcjNHXKlCIYLQokjYDHZLkoLJQ%3D%3D"
[download] Destination: Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].f248.webm
[download] 100% of    1.17GiB in 00:04:42 at 4.24MiB/s
[debug] Invoking http downloader on "https://rr7---sn-cn3tc-aigr.googlevideo.com/videoplayback?expire=1670374364&ei=fI-PY5PlG_CCp-oP_4WvmAU&ip=2a02%3Ac7c%3A5c48%3Ab800%3A1d70%3A1e68%3A35e8%3A2e86&id=o-AEqoa8fLaElCvKLtIAdZbXI2mv2O0GkKelwfwtxYcSwX&itag=251&source=youtube&requiressl=yes&mh=Nd&mm=31%2C29&mn=sn-cn3tc-aigr%2Csn-aigzrnze&ms=au%2Crdu&mv=m&mvi=7&pl=44&initcwndbps=1536250&spc=SFxXNie7drl71leEuNMaTsPLN8d734A&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=125762609&dur=8010.041&lmt=1670247969186299&mt=1670352323&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgUmZqfBmaXFgVitBKz11fmqq2BwmbbBwDb_l8apfCBQ0CIA26STHL5SvGrr-50XEYf-hWJPzu6vWhbeWTZv9HJL4Y&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgRQwL9Cnc1ZChBriMVKip7JCwl_rh-to_rCPs0TOgih8CIQDh_U_CCBPnJn-akUSlNcjNHXKlCIYLQokjYDHZLkoLJQ%3D%3D"
[download] Destination: Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].f251.webm
[download] 100% of  119.94MiB in 00:00:23 at 5.21MiB/s
[Merger] Merging formats into "Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].f248.webm' -i 'file:Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].temp.webm'
Deleting original file Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].f248.webm (pass -k to keep)
Deleting original file Two Point Campus SPACE ACADEMY： Jane Trains Astronauts in New Two Point Campus DLC 🚀🫡 [27rKhzGG1dM].f251.webm (pass -k to keep)
```
Python 3.11 also has Unicode v14:
```
python3.11 -c 'import unicodedata; print(unicodedata.unidata_version)'
14.0.0
```

**Comment by dirkf** [comment]
[Probably the OS upgrade rather than the Python upgrade](https://github.com/ytdl-org/youtube-dl/issues/31395#issuecomment-1340179809).
