### ISSUE TITLE
[Huya] Returns unsupported URL

### ISSUE THREAD

**Issue by fosam** [yt-dlp/yt-dlp#5709]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Global

### Provide a description that is worded well enough to be understood

I think Huya is supported according to the supported sites, but this example URL returns unsupported URL error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--simulate', '-vU', 'https://v.huya.com/play/807061685.html']
[debug] User config "C:\Users\Win\AppData\Roaming\yt-dlp\config": ['--output', 'C:\\Users\\Win\\Desktop\\%(title)s [%(id)s].%(ext)s'
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-12-01, ffprobe 2022-12-01, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://v.huya.com/play/807061685.html
[generic] 807061685: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 807061685: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://v.huya.com/play/807061685.html
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://v.huya.com/play/807061685.html
```

**Comment by fosam** [comment]
I doubt that request will get any attention after 3 years of inactivity, good that it's added as a site request here.

**Comment by HobbyistDev** [comment]
For the first link, we can get video by request to `https://cdnws.api.huya.com/?baseinfo=DBYAJhV3ZWJoNSYwLjAuMSZ3ZWJzb2NrZXQ2DEhVWUEmWkgmMjA1MkYAVgBsdgCGhmh1eWFfdWE9d2ViaDUmMC4wLjEmd2Vic29ja2V0OyBIbV9sdnRfNTE3MDBiNmM3MjJmNWJiNGNmMzk5MDZhNTk2ZWE0MWY9MTY3MTE3Mzc0MzsgSG1fbHB2dF81MTcwMGI2YzcyMmY1YmI0Y2YzOTkwNmE1OTZlYTQxZj0xNjcxMTczNzQzliU5OWFlZmExOTkyODlkNDBhOjk5YWVmYTE5OTI4OWQ0MGE6MDowqAACBghIVVlBX05FVBYBMAYLSFVZQV9WU0RLVUEWFndlYmg1JjEuNS4zNSZ3ZWJzb2NrZXQ%3D&timestamp=1671173743005` with POST method. It seems the baseinfo is encoded with base64. The response return base64 encoded text. We can get the decode response using base64 decode and get something like this:
```
��,<@VhuyaVideoUIfgetVideoTranscodeUrlList}�����tRsp�



�&�6webh5&1.0.0&huyavideoFhuya_ua=webh5&0.0.1&websocket;Hm_lvt_51700b6c722f5bb4cf39906a596ea41f=1671173743;Hm_lpvt_51700b6c722f5bb4cf39906a596ea41f=1671173743\default&��0ȵ0ȵ�&�6�@jVrelaxl|http://v-huya-img2.msstatic.com/screenshot/2248/807061685/99.jpg?x-oss-process=style/640x360&amp;amp;v=ca3d14cf0978c645bb1fc9cccac2d90a1670053691�&�6�F�V�f��%http://v.huya.com/play/807061685.html�����`�&�6�L\l�
	2661220491920&10806yuanhuaG��Fhttp://hw-vod.cdn.huya.com/leaf/1048585/2214583392/49209453/1857086_9f3314fffe4eeab6adcb61cfddb3155b_264_1080_1.mp4?hyvid=807061685&hyauid=2214583392&hyroomid=2214583392&hyratio=4000&hyscence=vod&appid=66&domainid=25&srckey=NjZfMjVfODA3MDYxNjg1&bitrate=2669&client=106&definition=yuanhua&pid=2214583392&scene=vod&vid=807061685W��Ghttp://hw-vod.cdn.huya.com/leaf/1048585/2214583392/49209453/1857086_9f3314fffe4eeab6adcb61cfddb3155b_264_1080_1.m3u8?hyvid=807061685&hyauid=2214583392&hyroomid=2214583392&hyratio=4000&hyscence=vod&appid=66&domainid=25&srckey=NjZfMjVfODA3MDYxNjg1&bitrate=2669&client=106&definition=yuanhua&pid=2214583392&scene=vod&vid=807061685f1080Pv
...
```
From this decoded response we can get media url and pass it to manifest downloader.
ffplay log:
```
> ffplay -i "http://hw-vod.cdn.huya.com/leaf/1048585/2214583392/49209453/1857086_e2f8cfaae4d101e9014dfd3d5f5c54cb_264_720_1/000000000.ts?hyvid=807061685&hyauid=2214583392&hyroomid=2214583392&hyratio=1300&hyscence=vod&appid=66&domainid=25&srckey=NjZfMjVfODA3MDYxNjg1&bitrate=1417&client=106&definition=1300&pid=2214583392"
ffplay version 5.1-full_build-www.gyan.dev Copyright (c) 2003-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mpegts, from 'http://hw-vod.cdn.huya.com/leaf/1048585/2214583392/49209453/1857086_e2f8cfaae4d101e9014dfd3d5f5c54cb_264_720_1/000000000.ts?hyvid=807061685&hyauid=2214583392&hyroomid=2214583392&hyratio=1300&hyscence=vod&appid=66&domainid=25&srckey=NjZfMjVfODA3MDYxNjg1&bitrate=1417&client=106&definition=1300&pid=2214583392':
  Duration: 00:00:05.00, start: 1.466667, bitrate: 1666 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1280x720, 30 fps, 30 tbr, 90k tbn
  Stream #0:1[0x101](eng): Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 131 kb/s
   4.63 A-V: -0.004 fd=  43 aq=   19KB vq=  140KB sq=    0B f=0/0
```

**Comment by doe1080** [comment]
v.huya.com currently redirects to a supported URL
