### ISSUE TITLE
Firefox Container feature for specifying a container on the command line does not work as intended

### ISSUE THREAD

**Issue by KlfJoat** [yt-dlp/yt-dlp#5716]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

#4800 fixed a problem with Firefox Containers and expanded the feature in a good way. However, compared to the README.md file, there is a bug in it.

https://github.com/yt-dlp/yt-dlp/blob/master/README.md?plain=1#L670
```text
--cookies-from-browser BROWSER[+KEYRING][:PROFILE][::CONTAINER]
```

The bracket formatting here, as commonly interpreted, implies that setting `KEYRING`, `PROFILE`, and `CONTAINER` are each independent of one another. Meaning I can set `PROFILE` without `KEYRING`, `KEYRING` and `CONTAINER` without `PROFILE`, etc.

However, this is not the case in practice when trying to set only `CONTAINER`.

https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/__init__.py#L353
```python
            (?:\s*:\s*(?P<profile>.+?))?
            (?:\s*::\s*(?P<container>.+))?
```

As written, I believe that code intends to parse the `BROWSER[+KEYRING][:PROFILE][::CONTAINER]` info correctly. However, there's a problem with regex greediness I believe. On my system it thinks that I'm trying to set `PROFILE` to `:CONTAINER`.

Since I can't write Python, and don't understand its regex system, I'm not sure how to fix the code myself.

I have multiple examples, but I'll put the direct error in this top comment.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --cookies-from-browser firefox::MyContainer https://example.com/somevideo

[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox::MyContainer', 'https://example.com/somevideo']
[debug] User config "/home/klfjoat/.config/yt-dlp/config": ['--no-overwrites', '--no-mtime', '--output', '%(title).200s-%(id)s.%(ext)s', '--abort-on-error']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-56-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 17, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 968, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 928, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 641, in __init__
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3777, in print_debug_header
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3806, in _setup_opener
  File "/usr/local/bin/yt-dlp/yt_dlp/cookies.py", line 99, in load_cookies
  File "/usr/local/bin/yt-dlp/yt_dlp/cookies.py", line 116, in extract_cookies_from_browser
  File "/usr/local/bin/yt-dlp/yt_dlp/cookies.py", line 141, in _extract_firefox_cookies
FileNotFoundError: could not find firefox cookies database in /home/klfjoat/.mozilla/firefox/:MyContainer
```

**Comment by KlfJoat** [comment]
### Verbose output of a run not specifying anything beyond `firefox`

You can see 833 cookies from all containers.

```shell
$ yt-dlp -vU --cookies-from-browser firefox https://example.com/somevideo

[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://example.com/somevideo']
[debug] User config "/home/klfjoat/.config/yt-dlp/config": ['--no-overwrites', '--no-mtime', '--output', '%(title).200s-%(id)s.%(ext)s', '--abort-on-error']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-56-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/klfjoat/.mozilla/firefox/zejlyycr.default/cookies.sqlite"
[Cookies] Extracted 833 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://example.com/somevideo
[generic] 4106103: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 4106103: Extracting information
[debug] Looking for embeds
[html5] 4106103: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Identified a html5 embed
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4106103-1: Downloading 1 format(s): hls-2194
[debug] Invoking hlsnative downloader on "https://example.com/somevideo_185e6dd43618cd961266866220fe2a1f2b/4106103/229cd1a5-cd2e-4ef8-bb6c-2b60a2389a8c/720p.m3u8"
[download] Somevideo.mp4 has already been downloaded
[download] 100% of  207.04MiB
```

**Comment by KlfJoat** [comment]
### Verbose output of a run specifying browser, profile, and container

This works.  You can see 78 cookies from the specified container.

```shell
$ yt-dlp -vU --cookies-from-browser firefox:zejlyycr.default::MyContainer https://example.com/somevideo

[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox:zejlyycr.default::MyContainer', 'https://example.com/somevideo']
[debug] User config "/home/klfjoat/.config/yt-dlp/config": ['--no-overwrites', '--no-mtime', '--output', '%(title).200s-%(id)s.%(ext)s', '--abort-on-error']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-56-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/klfjoat/.mozilla/firefox/zejlyycr.default/cookies.sqlite"
[debug] Only loading cookies from firefox container "MyContainer", ID 7
[Cookies] Extracted 78 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://example.com/somevideo
[generic] 4106103: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 4106103: Extracting information
[debug] Looking for embeds
[html5] 4106103: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Identified a html5 embed
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4106103-1: Downloading 1 format(s): hls-2194
[debug] Invoking hlsnative downloader on "https://example.com/somevideo_185e6dd43618cd961266866220fe2a1f2b/4106103/229cd1a5-cd2e-4ef8-bb6c-2b60a2389a8c/720p.m3u8"
[download] Somevideo.mp4 has already been downloaded
[download] 100% of  207.04MiB
```

**Comment by candrapersada** [comment]
`--cookies-from-browser firefox` not working in firefox from Windows store https://apps.microsoft.com/store/detail/mozilla-firefox/9NZVDKPMR9RD?hl=en-us&gl=us
