### ISSUE TITLE
Streamgates

### ISSUE THREAD

**Issue by qb128552** [yt-dlp/yt-dlp#5720]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://cplayer.streamgates.net/dvr/?Sv=clive_vod&Xs=siyum_belzashdod_rec&Pp=clive_rec&Tt=c-live.co.il

### Provide a description that is worded well enough to be understood

first gives ssl error 
then i do --no-check-certificate 
then i get 
ERROR: Unsupported URL: https://cplayer.streamgates.net/dvr/?Sv=clive_vod&Xs=siyum_belzashdod_rec&Pp=clive_rec&Tt=c-live.co.il

also tried with
--cookies-from-browser chrome

but same result unsupported url 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe "https://cplayer.streamgates.net/dvr/?Sv=clive_vod&Xs=siyum_belzashdod_rec&Pp=clive_rec&Tt=c-live.co.il" --no-check-certificate --cookies-from-browser chrome -vU
[debug] Command-line config: ['https://cplayer.streamgates.net/dvr/?Sv=clive_vod&Xs=siyum_belzashdod_rec&Pp=clive_rec&Tt=c-live.co.il', '--no-check-certificate', '--cookies-from-browser', 'chrome', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2020-12-06-git-2aab42bc40-full_build-www.gyan.dev, ffprobe 2020-12-06-git-2aab42bc40-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\CLL\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\CLL\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 2725 cookies from chrome
[debug] cookie version breakdown: {'v10': 2725, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://cplayer.streamgates.net/dvr/?Sv=clive_vod&Xs=siyum_belzashdod_rec&Pp=clive_rec&Tt=c-live.co.il
[generic] ?Sv=clive_vod&Xs=siyum_belzashdod_rec&Pp=clive_rec&Tt=c-live.co: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?Sv=clive_vod&Xs=siyum_belzashdod_rec&Pp=clive_rec&Tt=c-live.co: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://cplayer.streamgates.net/dvr/?Sv=clive_vod&Xs=siyum_belzashdod_rec&Pp=clive_rec&Tt=c-live.co.il
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://cplayer.streamgates.net/dvr/?Sv=clive_vod&Xs=siyum_belzashdod_rec&Pp=clive_rec&Tt=c-live.co.il
```

**Comment by coletdjnz** [comment]
For devs:
- Probably requires cookies or a referer header otherwise the site gives you a scary copyright image.
- Example viewable broadcast (you should add embed detection) https://www.c-live.co.il/archives/41734
- The site uses basic [Radiant Media Player](https://www.radiantmediaplayer.com/) initialization code. It *may* be possible to add generic embed support for some simple cases like this one:
   - Under `settings` javascript var to initialize the player, there should be a `src` key that points to either another var containing the src dict or a dict
   ```js
   var src = {
              
                hls: "https://example.com/example.m3u8",
                contentTitle: "Example"
              };
   [...]
   var settings = {
                licenseKey: 'XXXYYY',
                src: src,
     ```
     - Both the above Clive.co.il and radiantmediaplayer.com have a similar layout to this
     - I would check the docs for more info on this https://www.radiantmediaplayer.com/docs/latest/quick-start.html
- Clive.co.il is "powered by Multix Technologies". Could be worth checking out any other sites they have worked on for more examples.
