### ISSUE TITLE
onlineeventpro.freeman.com - ustream embed not detected

### ISSUE THREAD

**Issue by xtbtvd12399** [yt-dlp/yt-dlp#5741]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Vietnam

### Example URLs

https://rsnanov22.onlineeventpro.freeman.com/live-stream/37812429/Artificial-Intelligence-in-Abdominal-Imaging

### Provide a description that is worded well enough to be understood

The sources of .m4v and .m4a come from akamaihd.net
F12 for developer tools, in the Network tab, the segments are texted from the second "ustream" (wss://r64766701-1-132374898-recorded-wss-omega.ums.services.video.ibm.com/1/ustream), which containing messages (long message, I will post in the bottom of this description).
I has downloaded some segments, but the player cannot render files.
I has modified some Verbose Output, hided the id and email, if you want to access this site, please send me message, thanks.

Messages mentioned above:
```
{"args":[{"thumbnail":{"thumbnailSecureUrl":"https://ustvstaticcdn1-a.akamaihd.net/i/video/picture/0/1/132/132374/132374898/1_24820340_132374898,#SIZE#,b,1:3.jpg","thumbnailUrl":"http://static-cdn1.ustream.tv/i/video/picture/0/1/132/132374/132374898/1_24820340_132374898,#SIZE#,b,1:3.jpg"},"broadcaster":{"benefits":["activity_log","adfreebroadcast","adfreeview","analytics_api","api_access","autorecord","caption_search","channel_limit","closed_caption","combined_embed","custom_metadata","custom_sharing","disable_flash_menu_links","disallow_watchwithoutads_cta","embed_configurator_autoplay","embed_restriction","encrypted_storage","exempt_site_blacklist","fullbranding","geolocking","hd_broadcast","html_description","ibmdomain","individual_viewer_tracking","inlineplayback","lac_full","lac_limited","linearfeed","live_cta","live_monitoring_console","multiaudio","page_lock","password_lock_unlimited","poll","premiumprofileicon","premiumsocialstream","qna","recording_limit","remove_sharing","sdk_access","slide_upload","storage_limit","streamchat","transcode_video","transcoded_live_1080p","transcoded_live_240p","transcoded_live_720p","transcoded_versions_for_viewer","transcript_video","twittercards_mobile_playback","uac_full","uac_limited","video_cms","video_cms_pro","video_gallery","video_upload","viewer_registration_full","vip_user","watson_live_captioning","whitelabel_ve"],"featured":false,"proPackage":5,"location":"US"},"clientRateLimit":{"deferred":"5","immediate":"1"},"stream":{"sourceMedia":132374898,"streamFormats":{"flv/segmented":{"chunkTime":6000,"contentAccess":{"accessList":[{"data":{"path":"sjc/omega/vod/us1-d4df0181-9c91-4cba-adfb-5047b0ebde5e/21168000000/43396513272000/plain/improved/","protocol":"https"}}],"accessMode":"INSERT"},"videoLength":4098199,"streams":[{"offsetInMs":0,"country":"US","offset":0,"segmentUrl":"2/9/chunk_%_%.flv","bitrate":2694,"language":"en","preset":"original","transcoded":false,"label":"English (US)","audioCodec":{"channels":2,"level":2,"profile":40,"codecName":"AAC","sampleRate":48000,"audioBitrate":90},"default":true,"sourceStreamVersion":2,"videoCodec":{"videoBitrate":2604,"level":40,"profile":100,"width":1920,"codecName":"H264","height":1080}},{"offsetInMs":0,"country":"US","offset":0,"segmentUrl":"2/3/chunk_%_%.flv","bitrate":2779,"language":"en","preset":"original","transcoded":false,"label":"English (US)","audioCodec":{"channels":2,"level":2,"profile":40,"codecName":"AAC","sampleRate":48000,"audioBitrate":175},"default":true,"sourceStreamVersion":2,"videoCodec":{"videoBitrate":2604,"level":40,"profile":100,"width":1920,"codecName":"H264","height":1080}},{"offsetInMs":0,"country":"US","offset":0,"segmentUrl":"1/9/chunk_%_%.flv","bitrate":267,"language":"en","preset":"720p","transcoded":true,"label":"English (US)","audioCodec":{"channels":2,"level":2,"profile":40,"codecName":"AAC","sampleRate":48000,"audioBitrate":90},"default":true,"sourceStreamVersion":1,"videoCodec":{"videoBitrate":177,"level":31,"profile":100,"width":1280,"codecName":"H264","height":720}},{"offsetInMs":0,"country":"US","offset":0,"segmentUrl":"1/3/chunk_%_%.flv","bitrate":352,"language":"en","preset":"720p","transcoded":true,"label":"English (US)","audioCodec":{"channels":2,"level":2,"profile":40,"codecName":"AAC","sampleRate":48000,"audioBitrate":175},"default":true,"sourceStreamVersion":1,"videoCodec":{"videoBitrate":177,"level":31,"profile":100,"width":1280,"codecName":"H264","height":720}},{"offsetInMs":0,"country":"US","offset":0,"segmentUrl":"5/9/chunk_%_%.flv","bitrate":222,"language":"en","preset":"480p","transcoded":true,"label":"English (US)","audioCodec":{"channels":2,"level":2,"profile":40,"codecName":"AAC","sampleRate":48000,"audioBitrate":90},"default":true,"sourceStreamVersion":5,"videoCodec":{"videoBitrate":132,"level":31,"profile":77,"width":864,"codecName":"H264","height":486}},{"offsetInMs":0,"country":"US","offset":0,"segmentUrl":"5/3/chunk_%_%.flv","bitrate":307,"language":"en","preset":"480p","transcoded":true,"label":"English (US)","audioCodec":{"channels":2,"level":2,"profile":40,"codecName":"AAC","sampleRate":48000,"audioBitrate":175},"default":true,"sourceStreamVersion":5,"videoCodec":{"videoBitrate":132,"level":31,"profile":77,"width":864,"codecName":"H264","height":486}},{"offsetInMs":0,"country":"US","offset":0,"segmentUrl":"7/9/chunk_%_%.flv","bitrate":183,"language":"en","preset":"360p","transcoded":true,"label":"English (US)","audioCodec":{"channels":2,"level":2,"profile":40,"codecName":"AAC","sampleRate":48000,"audioBitrate":90},"default":true,"sourceStreamVersion":7,"videoCodec":{"videoBitrate":93,"level":30,"profile":77,"width":640,"codecName":"H264","height":360}},{"offsetInMs":0,"country":"US","offset":0,"segmentUrl":"7/3/chunk_%_%.flv","bitrate":268,"language":"en","preset":"360p","transcoded":true,"label":"English (US)","audioCodec":{"channels":2,"level":2,"profile":40,"codecName":"AAC","sampleRate":48000,"audioBitrate":175},"default":true,"sourceStreamVersion":7,"videoCodec":{"videoBitrate":93,"level":30,"profile":77,"width":640,"codecName":"H264","height":360}},{"offsetInMs":0,"country":"US","offset":0,"segmentUrl":"6/9/chunk_%_%.flv","bitrate":141,"language":"en","preset":"240p","transcoded":true,"label":"English (US)","audioCodec":{"channels":2,"level":2,"profile":40,"codecName":"AAC","sampleRate":48000,"audioBitrate":90},"default":true,"sourceStreamVersion":6,"videoCodec":{"videoBitrate":51,"level":21,"profile":77,"width":448,"codecName":"H264","height":252}},{"offsetInMs":0,"country":"US","offset":0,"segmentUrl":"6/3/chunk_%_%.flv","bitrate":226,"language":"en","preset":"240p","transcoded":true,"label":"English (US)","audioCodec":{"channels":2,"level":2,"profile":40,"codecName":"AAC","sampleRate":48000,"audioBitrate":175},"default":true,"sourceStreamVersion":6,"videoCodec":{"videoBitrate":51,"level":21,"profile":77,"width":448,"codecName":"H264","height":252}}],"hashes":{"190":"bec81ba39e","390":"b70c0c1241","270":"06d562aed4","150":"38f0d79902","590":"454217b44b","470":"78250e7573","350":"2158f4c9b4","230":"716042316a","670":"5d0b84eeb5","110":"ec5148fd22","550":"a14321d4f1","430":"7e6c3c9979","310":"cdf3781894","630":"49d30993b9","510":"fadaf00832","90":"1ac7cfa897","50":"eafaad68e1","10":"1441b5e72a","280":"9f0bc0c1eb","160":"c2a6a2e546","480":"6db89cf393","360":"13bd8e5761","240":"826644084b","680":"26fb3e1129","120":"6b92f48cae","560":"a700ae58ae","0":"89c03ae435","440":"0e054cbbd0","320":"29dd618a41","200":"36b15bc5b9","640":"e7841734de","520":"85a86f15b1","400":"f1416e9a44","600":"041e2a9784","60":"43e79e62f3","20":"80f0f780a1","290":"dc89f4ef72","170":"c2da27af19","490":"91931a0a3d","370":"2db3e1a0fa","250":"220c58134b","130":"9746edbad5","570":"c857ef248c","450":"6a80226a82","330":"41d8c31b78","210":"1abb4c48d8","650":"93c9afa885","530":"d213c48f53","410":"613d247fdb","610":"d97bdaaa6c","70":"bf7869937e","30":"7b51e2ddf8","180":"c354496a42","380":"edf62fd3e1","260":"b6d079b448","140":"da4c754cf8","580":"d7131ee606","460":"a2aef3319f","340":"c7d62e8bc9","220":"34cd6f5a20","660":"e758641cc7","100":"fc4c953bf2","540":"a04d1541a0","420":"2f6f2e9068","300":"1c9d7139e7","620":"0150956e96","500":"fe01576909","80":"7be65208f8","40":"efd6dd2dfc"},"chunkId":0},"mp4/segmented":{"chunkTime":6000,"contentAccess":{"accessList":[{"data":{"path":"sjc/omega/vod/us1-d4df0181-9c91-4cba-adfb-5047b0ebde5e/21168000000/43396513272000/plain/improved/","protocol":"https"}}],"accessMode":"INSERT"},"videoLength":4098199,"streams":[{"codec":"avc1.640028","segmentUrl":"2/chunk_%_%.m4v","width":1920,"sourceStreamVersion":2,"bitrate":2604,"transcoded":false,"contentType":"video/mp4","initUrl":"2/chunk_%_%.m4vh","height":1080},{"codec":"avc1.64001f","segmentUrl":"1/chunk_%_%.m4v","width":1280,"sourceStreamVersion":1,"bitrate":177,"transcoded":true,"contentType":"video/mp4","initUrl":"1/chunk_%_%.m4vh","height":720},{"codec":"avc1.4d001f","segmentUrl":"5/chunk_%_%.m4v","width":864,"sourceStreamVersion":5,"bitrate":132,"transcoded":true,"contentType":"video/mp4","initUrl":"5/chunk_%_%.m4vh","height":486},{"codec":"avc1.4d001e","segmentUrl":"7/chunk_%_%.m4v","width":640,"sourceStreamVersion":7,"bitrate":93,"transcoded":true,"contentType":"video/mp4","initUrl":"7/chunk_%_%.m4vh","height":360},{"codec":"avc1.4d0015","segmentUrl":"6/chunk_%_%.m4v","width":448,"sourceStreamVersion":6,"bitrate":51,"transcoded":true,"contentType":"video/mp4","initUrl":"6/chunk_%_%.m4vh","height":252},{"codec":"mp4a.40.2","country":"US","default":true,"segmentUrl":"9/chunk_%_%.m4a","sourceStreamVersion":9,"bitrate":90,"language":"en","transcoded":true,"label":"English (US)","contentType":"audio/mp4","initUrl":"9/chunk_%_%.m4ah"},{"codec":"mp4a.40.2","country":"US","default":true,"segmentUrl":"3/chunk_%_%.m4a","sourceStreamVersion":3,"bitrate":175,"language":"en","transcoded":false,"label":"English (US)","contentType":"audio/mp4","initUrl":"3/chunk_%_%.m4ah"}],"hashes":{"190":"bec81ba39e","390":"b70c0c1241","270":"06d562aed4","150":"38f0d79902","590":"454217b44b","470":"78250e7573","350":"2158f4c9b4","230":"716042316a","670":"5d0b84eeb5","110":"ec5148fd22","550":"a14321d4f1","430":"7e6c3c9979","310":"cdf3781894","630":"49d30993b9","510":"fadaf00832","90":"1ac7cfa897","50":"eafaad68e1","10":"1441b5e72a","280":"9f0bc0c1eb","160":"c2a6a2e546","480":"6db89cf393","360":"13bd8e5761","240":"826644084b","680":"26fb3e1129","120":"6b92f48cae","560":"a700ae58ae","0":"89c03ae435","440":"0e054cbbd0","320":"29dd618a41","200":"36b15bc5b9","640":"e7841734de","520":"85a86f15b1","400":"f1416e9a44","600":"041e2a9784","60":"43e79e62f3","20":"80f0f780a1","290":"dc89f4ef72","170":"c2da27af19","490":"91931a0a3d","370":"2db3e1a0fa","250":"220c58134b","130":"9746edbad5","570":"c857ef248c","450":"6a80226a82","330":"41d8c31b78","210":"1abb4c48d8","650":"93c9afa885","530":"d213c48f53","410":"613d247fdb","610":"d97bdaaa6c","70":"bf7869937e","30":"7b51e2ddf8","180":"c354496a42","380":"edf62fd3e1","260":"b6d079b448","140":"da4c754cf8","580":"d7131ee606","460":"a2aef3319f","340":"c7d62e8bc9","220":"34cd6f5a20","660":"e758641cc7","100":"fc4c953bf2","540":"a04d1541a0","420":"2f6f2e9068","300":"1c9d7139e7","620":"0150956e96","500":"fe01576909","80":"7be65208f8","40":"efd6dd2dfc"},"chunkId":0}},"contentAvailable":true,"version":1},"chat":{"socialStreamEnabled":true,"socialStreamSettings":{"prefix":"#ejh5f7kbg2x","suffix":" (live at https://video.ibm.com/channel/RFMY4JDaHTC)"},"chatEnabled":false},"meta":{"date":"2022-11-28 05:40:57","cluster":"omega","videoLength":4098.2,"ownerChannelId":"24820340","keywords":["Artificial Intelligence in Abdominal Imaging"],"chapters":[],"contentPartner":false,"adFree":true,"ip":"113.23.64.212","dateUtcTs":1669642857,"subCategoryId":"131","filesize":1371974244,"originalUrl":"http://vsa-proxy-pub.ustream-adm.in:80/v3/upload/132374898.original","title":"Artificial Intelligence in Abdominal Imaging","userName":"ejh5f7kbg2x","userId":44474245,"adIntegration":{"hasBenefit":false,"hasSettings":false},"umsId":"sjc03-flot-omega003","regionCode":"HN","countryCode":"VN","ownerBrandId":"1","originalDate":"2022-11-28 05:40:57","originalDateUtcTs":1669642857,"classifier":"NONE","pageUrl":"https://rsnanov22.onlineeventpro.freeman.com/live-stream/37812429/Artificial-Intelligence-in-Abdomin","category":["Education","Business"],"mainCategoryId":"126","logicId":"sjc04-logic-omega04"}}],"cmd":"moduleInfo"}
```
### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ytd -vU "https://rsnanov22.onlineeventpro.freeman.com/live-stream/37812429/Artificial-Intelligence-in-Abdominal-Imaging?id=********&email=***@***.com"
[debug] Command-line config: ['-vU', 'https://rsnanov22.onlineeventpro.freeman.com/live-stream/37812429/Artificial-Intelligence-in-Abdominal-Imaging?id=********&email=***@***.com']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109274-gd7a5f068c2-20221130 (setts), ffprobe N-109274-gd7a5f068c2-20221130
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://rsnanov22.onlineeventpro.freeman.com/live-stream/37812429/Artificial-Intelligence-in-Abdominal-Imaging?id=********&email=***@***.com
[generic] Artificial-Intelligence-in-Abdominal-Imaging?id=********&email=***@***: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Artificial-Intelligence-in-Abdominal-Imaging?id=********&email=***@***: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://rsnanov22.onlineeventpro.freeman.com/live-stream/37812429/Artificial-Intelligence-in-Abdominal-Imaging?id=********&email=***@***.com
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://rsnanov22.onlineeventpro.freeman.com/live-stream/37812429/Artificial-Intelligence-in-Abdominal-Imaging?id=********&email=***@***.com
```

**Comment by bashonly** [comment]
Looks like a `ustream` embed, but it is not detected by the extractor, which also needs fixing. Related: #3702

**Comment by doe1080** [comment]
no longer available
