### ISSUE TITLE
[NHK] [NhkVod] follow redirection

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#5760]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

worldwide

### Example URLs

https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171

### Provide a description that is worded well enough to be understood

Some NHK video webpages like this
https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171
include a (seemingly) embedded video with a pulsating play button.
I don't know if this video is thought to be played embedded(ly) or trigger a redirection.
When clicking on the play button, my Firefox instance does the latter and redirects here:
https://www3.nhk.or.jp/nhkworld/en/ondemand/video/4026171
On this landing page, there finally is the playable video.

When running yt-dlp with those URLs,
the 1st URL fails (with the error log provided below)
the 2nd URL is downloaded correctly.

Maybe the NHK extractor can be enhanced to use the 2nd URL when the 1st URL is provided ?

The video in the 1st URL links to the 2nd URL:

Extract from the source code:
`<a href="/nhkworld/en/ondemand/video/4026171/" class="c-tv-episode-info-video-navigate"><div class="c-tv-episode-info-video-navigate-icon"><!----> <img src="/nhkworld/common/assets/live/images/c-tv-episode-info-video-navigate/icon-nav-on-demand.svg" alt=""></div></a>`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --ignore-config -v https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171
[debug] Command-line config: ['--ignore-config', '-v', 'https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19043-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [generic] Extracting URL: https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171
[generic] 4026171: Downloading webpage
[redirect] Following redirect to https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171/
[debug] [generic] Extracting URL: https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171/
[generic] 4026171: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 4026171: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171/
```

**Comment by pukkandan** [comment]
Do you have some more examples? So we get an idea what the possible URL patterns look like

**Comment by chrizilla** [comment]
I'll look if I can find additional URLs.
But maybe there is no systematic pattern that leads from URL1 to URL2.
Isn't the more foolproof solution to find the `<a>` anchor with `class="c-tv-episode-info-video-navigate"` as it already contains the target URL:

`<a href="/nhkworld/en/ondemand/video/4026171/" class="c-tv-episode-info-video-navigate">`

?

**Comment by chrizilla** [comment]
ok, here is another example:
start URL: https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221206/4026137/
target URL: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/4026137/

Ok, so in this case apparently it's sufficient to replace `tv/72hours/[date]/[videoID]` with `ondemand/video/[videoID]`.

I then assume it would be better to even replace `tv/[category]/[date]/[videoID]` with `ondemand/video/[videoID]` because there are very likely other categories than "72hours" that have the same URL scheme.

**Comment by muddi900** [comment]
@pukkandan I am already working on this so can you assign this to me.

**Comment by dirkf** [comment]
@kelvinwaringa: this issue is several years old. Do any URLs similar to the problem UR here still exist (that are not 404, like those I saw)? There's no point fixing an obsolete problem where the fix can't even be tested.

**Comment by kelvinwaringa** [comment]
> [@kelvinwaringa](https://github.com/kelvinwaringa): this issue is several years old. Do any URLs similar to the problem UR here still exist (that are not 404, like those I saw)? There's no point fixing an obsolete problem where the fix can't even be tested.

You're right, the original URLs from 2022 (e.g., https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171) appear to be 404 now

**Comment by chrizilla** [comment]
> the original URLs from 2022 (e.g., https://www3.nhk.or.jp/nhkworld/en/tv/72hours/20221129/4026171) appear to be 404 now

Remove the trailing path segments and you get:
https://www3.nhk.or.jp/nhkworld/en/shows/72hours
This URL still hosts a dozen of playable videos, e.g. https://www3.nhk.or.jp/nhkworld/en/shows/4026254
[NhkVod] extractor currently handles them fine.
I don't know if there are still redirecting URLs that yt-dlp does not follow, i.e. the root cause of this issue.
