### ISSUE TITLE
Download Facebook Stories 

### ISSUE THREAD

**Issue by bacevs** [yt-dlp/yt-dlp#5763]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Example URLs

yt-dlp --cookies facebook.com_cookies.txt https://www.facebook.com/stories/1659105157517420

### Provide a description that is worded well enough to be understood

Cannot download Facebook stories. 
Command line log: 
```
C:\Users\bacevs\Downloads>yt-dlp --cookies facebook.com_cookies.txt https://www.facebook.com/stories/1659105157517420
[generic] 1659105157517420: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1659105157517420: Extracting information
ERROR: Unsupported URL: https://www.facebook.com/stories/1659105157517420
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'facebook.com_cookies.txt', 'https://www.facebook.com/stories/1659105157517420']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://www.facebook.com/stories/1659105157517420
[generic] 1659105157517420: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1659105157517420: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.facebook.com/stories/1659105157517420
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/stories/1659105157517420
```

**Comment by asif-ca** [comment]
Is there any progress on downloading facebook stories?

**Comment by RingoTheDog** [comment]
happy new year.... we found a new example today:

https://www.facebook.com/permalink.php?story_fbid=pfbid0fqQuVEQyXRa9Dp4RcaTR14KHU3uULHV1EK7eckNXSH63JMuoALsAvVCJ97zAGitil&id=100068861234290

**Comment by wenjiangit** [comment]
Is there any progress on this issue？

**Comment by AlizerUncaged** [comment]
any progress with this? still cannot download facebook stories

**Comment by Reihtul** [comment]
Waiting for a solution I use a  quite complicated workaround, for those familiar with this kind of thing... I couldn't find a proper manifest request to use as URL for yt-dlp in FB stories (seems to be obfuscated or something like that...), but I could dl video and sound separatly by pointing out the different .mp4 requests in dev pannel, chosing the one that is the most reapeated for video and one that have only a single request for sound ; then requesting them separatly using yt-dlp but removing the "bytestart" and "byteend" parameters at the end of URL. Like this I got full video and sound as two .mp4 files, that I could merge using ffmpeg. Hope it helps some of you.

**Comment by gscout** [comment]
> > [@Reihtul](https://github.com/Reihtul) : I could dl video and sound separatly by pointing out the different .mp4 requests in dev pannel, chosing the one that is the most reapeated for video and one that have only a single request for sound ; then requesting them separatly using yt-dlp but removing the "bytestart" and "byteend" parameters at the end of URL

Thanks a lot, that works for me too! (at least for the video)

> [@Reihtul](https://github.com/Reihtul) : Thank you. Can you please elaborate ? I looked in the network tab but where do you go from here ?

In the network tab, in the same line as "Network" or just below it and on the right you can select "Media", which will filter out a large amount of requests, except the ones about video & audio. Then get one of the last lines with an mp4 type (the type has got its own column), right click and "Copy URL"
The `bytestart` and `byteend` parameters are the two last ones of the URL, and that makes it particularly easy to remove them. I couldn't find the audio stream though.

**Comment by gamer191** [comment]
> I couldn't find the audio stream though.

The network tab only starts recording requests after you open it, so you might need to refresh the page

**Comment by jericjan** [comment]
If anyone else got stuck, for me, it was on the Fetch/XHR section instead of Media, and a simple "mp4" filter finds both video and audio easily

**Comment by 0xvd** [comment]
So anyone is working on this issue ?

**Comment by bashonly** [comment]
@0xvd Not AFAICT. It's not necessary to ask this, BTW. If you don't see a pull request linked to the issue, then the issue is up for grabs.

But if you're still trying to learn yt-dlp extractor development, I would suggest staying as far away from the Facebook extractor as possible. It is a strong contender for worst spaghetti code in the entire project.

**Comment by bashonly** [comment]
> If you don't see a pull request linked to the issue, then the issue is up for grabs.

I should also add that there are some exceptions to this rule: if the issue is assigned to someone, or if the issue is labeled `core-triage`

**Comment by hexman1999** [comment]
+1

**Comment by 0xvd** [comment]
Since Mr. Bashonly told me not to touch the file but Mr. Bashonly I touch sorry for that ( YOU CAN BAN ME IF I HAVE DONE SOMETHING WRONG ) and made NOBBY_PATCH that works and I am not sure it works 100%

my diff :
```diff
diff --git a/yt_dlp/extractor/facebook.py b/yt_dlp/extractor/facebook.py
index 2634ee801..8119a4f1a 100644
--- a/yt_dlp/extractor/facebook.py
+++ b/yt_dlp/extractor/facebook.py
@@ -50,7 +50,8 @@ class FacebookIE(InfoExtractor):
                             [^/]+/posts/|
                             events/(?:[^/]+/)?|
                             groups/[^/]+/(?:permalink|posts)/(?:[\da-f]+/)?|
-                            watchparty/
+                            watchparty/|
+                            stories/
                         )|
                     facebook:
                 )
@@ -597,7 +598,7 @@ def extract_relay_prefetched_data(_filter, target_keys=None):
         if not video_data:
             data = extract_relay_prefetched_data(
                 r'"(?:dash_manifest|playable_url(?:_quality_hd)?)',
-                target_keys=('video', 'event', 'nodes', 'node', 'mediaset'))
+                target_keys=('video', 'event', 'nodes', 'node', 'mediaset', 'bucket'))
             if data:
                 entries = []
 
@@ -720,8 +721,12 @@ def parse_attachment(attachment, key='media'):
                         parse_attachment(n)
                     parse_attachment(attachment)
 
-                edges = try_get(data, lambda x: x['mediaset']['currMedia']['edges'], list) or []
+                edges = traverse_obj(data,
+                                     ('mediaset', 'currMedia', 'edges', {list}),
+                                     ('bucket', 'unified_stories_with_notes', 'edges', {list}), default=[])
                 for edge in edges:
+                    for ns in traverse_obj(edge, ('node', 'attachments'), default=[]):
+                        parse_attachment(ns)
                     parse_attachment(edge, key='node')
 
                 video = traverse_obj(data, (


```

and my verbose:
```
[debug] Command-line config: ['-vF', 'https://www.facebook.com/stories/170804927735302/UzpfSVNDOjk0NzMxNTg2MTUwMDY1OQ==/?view_single=false', '--cookies', 'cookies.txt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2026.03.17 from yt-dlp/yt-dlp [04d6974f5]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.17.0-20-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.23.0, certifi-2026.02.25, curl_cffi-0.14.0, requests-2.33.1, sqlite3-3.45.1, urllib3-2.6.3
[debug] JS runtimes: deno-2.6.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1864 extractors
[facebook] Extracting URL: https://www.facebook.com/stories/170804927735302/UzpfSVNDOjk0NzMxNTg2MTUwMDY1OQ==/?view_single=false
[facebook] 170804927735302: Downloading webpage
[download] Downloading playlist: 170804927735302
[facebook] Playlist 170804927735302: Downloading 3 items of 3
[download] Downloading item 1 of 3
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1260412729630266:
ID                EXT RESOLUTION │   TBR PROTO │ VCODEC          VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────
sd-0              mp4 unknown    │       https │ unknown             unknown
sd-1              mp4 unknown    │       https │ unknown             unknown
hd                mp4 unknown    │       https │ unknown             unknown
1282342336661884v mp4 540x960    │  164k https │ av01.0.04M.08  164k video only DASH video, mp4_dash
1677446666763227v mp4 720x1280   │  221k https │ av01.0.05M.08  221k video only DASH video, mp4_dash
1320768179922163v mp4 720x1280   │  340k https │ av01.0.05M.08  340k video only DASH video, mp4_dash
1688226615515214v mp4 720x1280   │  468k https │ av01.0.05M.08  468k video only DASH video, mp4_dash
1502501418064932v mp4 720x1280   │  586k https │ av01.0.05M.08  586k video only DASH video, mp4_dash
3432819023535747v mp4 720x1280   │  759k https │ av01.0.05M.08  759k video only DASH video, mp4_dash
1305031978171065v mp4 720x1280   │ 1011k https │ av01.0.05M.08 1011k video only DASH video, mp4_dash
1964154557794157v mp4 1080x1920  │ 1534k https │ av01.0.08M.08 1534k video only DASH video, mp4_dash
[download] Downloading item 2 of 3
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 2186088038847393:
ID                EXT RESOLUTION │   TBR PROTO │ VCODEC          VBR ACODEC     ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────
1053857777311440a m4a audio only │   70k https │ audio only          mp4a.40.5  70k 44k DASH audio, m4a_dash
sd-0              mp4 unknown    │       https │ unknown             unknown
sd-1              mp4 unknown    │       https │ unknown             unknown
hd                mp4 unknown    │       https │ unknown             unknown
1262486365590536v mp4 540x960    │  335k https │ av01.0.04M.08  335k video only         DASH video, mp4_dash
1903333930368632v mp4 720x1280   │  412k https │ av01.0.05M.08  412k video only         DASH video, mp4_dash
789747577305076v  mp4 720x1280   │  643k https │ av01.0.05M.08  643k video only         DASH video, mp4_dash
2223866264686916v mp4 720x1280   │  867k https │ av01.0.05M.08  867k video only         DASH video, mp4_dash
927269056814976v  mp4 720x1280   │ 1081k https │ av01.0.05M.08 1081k video only         DASH video, mp4_dash
2201131210658388v mp4 720x1280   │ 1452k https │ av01.0.05M.08 1452k video only         DASH video, mp4_dash
1617680952617938v mp4 720x1280   │ 1872k https │ av01.0.05M.08 1872k video only         DASH video, mp4_dash
956639410282342v  mp4 1080x1920  │ 2585k https │ av01.0.08M.08 2585k video only         DASH video, mp4_dash
[download] Downloading item 3 of 3
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1997427967843507:
ID                 EXT RESOLUTION │  TBR PROTO │ VCODEC         VBR ACODEC     ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────
2383256838810103a  m4a audio only │  64k https │ audio only         mp4a.40.5  64k 44k DASH audio, m4a_dash
sd-0               mp4 unknown    │      https │ unknown            unknown
sd-1               mp4 unknown    │      https │ unknown            unknown
hd                 mp4 unknown    │      https │ unknown            unknown
24449550318075322v mp4 360x640    │ 175k https │ vp09.00.21.08 175k video only         DASH video, mp4_dash
2154321158734204v  mp4 540x960    │ 395k https │ vp09.00.30.08 395k video only         DASH video, mp4_dash
26580713304957016v mp4 720x1280   │ 647k https │ vp09.00.31.08 647k video only         DASH video, mp4_dash
1225172076108212v  mp4 1080x1920  │ 854k https │ vp09.00.40.08 854k video only         DASH video, mp4_dash
[download] Finished downloading playlist: 170804927735302
```

EDITED - THAT NOTE IS INCORRECT SORRY MY BAD and my patch works for all stories that has video.

**Comment by hexman1999** [comment]
I would really appreciate if such fix is included 

Thank you! 😊

**Comment by 0xvd** [comment]
SO I made a pre realease for testing just like MR. Bashonly 

use this commands if you have install with executables or pip
<details><summary>EXECUTABLES</summary>

run this command for using my above patch
```CMD
yt-dlp --update-to 0xvd/yt-dlp-exp@facebook_stories
```
and when you done testing then run this commad 
```CMD
yt-dlp --update-to nightly
```
</details>

<details><summary>PIP</summary>

if you have install you yt-dlp with pip then use this command 
```CMD
pip install git+https://github.com/0xvd/yt-dlp-exp@fix_sbs
```
and when you done testing then run this command
```CMD
pip install -U --pre yt-dlp
```
</details>

**Comment by hexman1999** [comment]
@0xvd thank you! It works now but needs cookies for any stories even public ones, but I tested it with multiple stories


One give me this error


Downloading:
Title: r
URL: https://www.facebook.com/share/1CgBbbqHo3/
Type: video
Command:
--downloader "libaria2c.so" --cache-dir "/storage/emulated/0/Download/Ytdlnis/Cache/yt-dlp" --newline -N "3" -4 --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --trim-filenames "206" --no-mtime --load-info-json "/storage/emulated/0/Download/Ytdlnis/Cache/infojsons/511746041776839322456video.info.json" --sponsorblock-mark "all" --embed-chapters --merge-output-format "mp4" -S "vext:mp4,aext:mp3,+size" -f "1615093303115854v+ba/1615093303115854v/b" --embed-subs --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Download/Ytdlnis/Cache/dl/79" -o "%(uploader).30B - %(title).170B.%(ext)s" --replace-in-metadata "title" "^.*$" "r" --parse-metadata "%(title)s:%(meta_title)s" --parse-metadata "%(uploader,channel,creator|)l:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://www.facebook.com/share/1CgBbbqHo3/" 

WARNING: URLs are ignored due to --load-info-json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/user/0/com.deniscerri.ytdl/no_backup/ytdlnis/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/ytdlnis/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 1079, in main
  File "/data/user/0/com.deniscerri.ytdl/no_backup/ytdlnis/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 1068, in _real_main
  File "/data/user/0/com.deniscerri.ytdl/no_backup/ytdlnis/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3681, in download_with_info_file
  File "/data/user/0/com.deniscerri.ytdl/no_backup/ytdlnis/packages/python/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.deniscerri.ytdl/no_backup/ytdlnis/packages/python/usr/lib/python3.12/json/decoder.py", line 341, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 3 column 1 (char 19029)

**Comment by 0xvd** [comment]
> even public ones

We need cookie for every story and Public means if you can open in Private tab/incognito Tab without any cookies and I guess all story need cookies. So there is no solution to bypass.

**Comment by hexman1999** [comment]
thanks!

is the error related to the patch or something else?

**Comment by 0xvd** [comment]
> thanks!
> 
> is the error related to the patch or something else?

No that Error is made by you means read this line `WARNING: URLs are ignored due to --load-info-json` means you have added `--load-info-json` added in your command so now yt-dlp will extract, download,etc from your extracted_info_json file but your given json file `/storage/emulated/0/Download/Ytdlnis/Cache/infojsons/511746041776839322456video.info.json` is not a json I guess black or something else so yt-dlp try to load that json and parser gave decoder error ( because it is not a json ) so remove `--load-info-json` from command line and run another time it should work if cookies are not expired.
