### ISSUE TITLE
GMA Network

### ISSUE THREAD

**Issue by bachig26** [yt-dlp/yt-dlp#5770]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

https://www.gmanetwork.com/

https://www.gmanetwork.com/fullepisodes/

https://www.gmanetwork.com/fullepisodes/home/more_than_words/87059/more-than-words-full-episode-80/video?section=home

https://www.gmanetwork.com/fullepisodes/home/running_man_philippines/168677/running-man-philippines-catch-the-thief-full-chapter-2/video?section=home

https://www.gmanetwork.com/music/artists/gmamusic/165/sanyalopez/artist/ => https://aphrodite.gmanetwork.com/records/songs/Hot-Maria-Clara.mp3

https://www.gmanetwork.com/radio/streaming/dzbb

https://www.gmanetwork.com/regionaltv/

https://www.gmanetwork.com/entertainment/tv/kapuso_stream/videos/#176114

### Provide a description that is worded well enough to be understood

The site is a Philippines based TV network, and which is currently not supported by the yt-dlp.

I have seen some videos are embedded from YouTube or daily motion.

Please have a look into the site for the possible support.

There are few exclusive contents like tv dramas  restricted to south east asia or around Philippines due to the license (eg. https://www.gmanetwork.com/gtv/drama/the_merciless_judge/175785/the-merciless-judge-the-devil-judge-becomes-an-evil-doctor-episode-9/video).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.gmanetwork.com/fullepisodes/home/running_man_philippines/168677/running-man-philippines-catch-the-thief-full-chapter-2/video?section=home
[debug] Command-line config: ['-vU', 'https://www.gmanetwork.com/fullepisodes/home/running_man_philippines/168677/running-man-philippines-catch-the-thief-full-chapter-2/video?section=home']
[debug] User config "C:\Users\USER\AppData\Roaming\yt-dlp\config.txt": ['-o', 'E:\\yt-dlp_dls\\%(title)s.%(ext)s', '--sub-langs', 'en.*', '--extractor-args', 'youtube:skip=translated_subs', '--embed-subs', '-f', '((137/136)+140)/mpd-4/1/500/(hls-3462/hls-3192/hls-1960/hls-1660)', '--merge-output-format', 'mp4', '--ignore-no-formats-error', '-i', '--no-abort-on-error']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19043-SP0 (OpenSSL 1.1.1k  25 Mar 2021)

[debug] exe versions: ffmpeg n5.1.2-9-g807afa59cc-20221210 (setts), ffprobe n5.1.2-9-g807afa59cc-20221210, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://www.gmanetwork.com/fullepisodes/home/running_man_philippines/168677/running-man-philippines-catch-the-thief-full-chapter-2/video?section=home
[generic] video?section=home: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] video?section=home: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.gmanetwork.com/fullepisodes/home/running_man_philippines/168677/running-man-philippines-catch-the-thief-full-chapter-2/video?section=home
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.gmanetwork.com/fullepisodes/home/running_man_philippines/168677/running-man-philippines-catch-the-thief-full-chapter-2/video?section=home
```

**Comment by pukkandan** [comment]
Ingle videos have been implemented, but not playlists.
