### ISSUE TITLE
only able to run with sudo

### ISSUE THREAD

**Issue by vespino** [yt-dlp/yt-dlp#5772]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm running yt-dlp on the latest version of Synology DSM and although it has always worked great, I'm not apparently only able to run it with sudo.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./yt-dlp/__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "./yt-dlp/yt_dlp/__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "./yt-dlp/yt_dlp/cookies.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "./yt-dlp/yt_dlp/aes.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "./yt-dlp/yt_dlp/dependencies.py", line 22, in <module>
AttributeError: module 'certifi' has no attribute 'where'
```

**Comment by Lesmiscore** [comment]
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

Post the full log starting from lines like this:

```
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-5.15.0-33-generic-x86_64-with-glibc2.35 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
```

**Comment by vespino** [comment]
@Lesmiscore sorry, I don't know what this means. I have copied the output from my command: ./yt-dlp -vU https://youtube.url/id

**Comment by vespino** [comment]
@Lesmiscore please let me know what extra information I need to provide.

**Comment by Lesmiscore** [comment]
Can you update the `certifi` package? (Please don't if it bounds to the system, like it's available via package managers like apt or dnf)

**Comment by vespino** [comment]
Synology does not support apt or pip.

**Comment by Lesmiscore** [comment]
Then you should try `yt-dlp_linux` from https://github.com/yt-dlp/yt-dlp/releases/tag/2022.11.11 , it comes with a decent version of packages

**Comment by vespino** [comment]
I will try that, but why does it run with sudo then?

**Comment by vespino** [comment]
I looked at Python packages installed on another Synology and noticed “certifi” wasn’t present, so I opted to remove it all together (sudo python3 -m pip uninstall certifi) and now the command runs fine without sudo. Wonder what I broke in doing this, we’ll find out.
