### ISSUE TITLE
Dangal Play

### ISSUE THREAD

**Issue by justarish** [yt-dlp/yt-dlp#5775]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

https://www.dangalplay.com/tv-shows/palkon-ki-chhaon-mein-2/season-1/episode-1-palkon-ki-chhaon-mein-ep-01/ENTERR10_EPISODE_63514fd2bd9edd1c2e533879
https://www.dangalplay.com/tv-shows/ishq-ki-dastan-naagmani/season-1/episode-1-naagmani-ep-01/ENTERR10_EPISODE_634f7c40f8e1ee47abe1be28
https://www.dangalplay.com/tv-shows/rang-jaun-tere-rang-mein/ENTERR10_TVSHOW_62bd74e383381b5452159838

### Provide a description that is worded well enough to be understood

Paid subscription, I hope I didn't make any mistakes

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -F https://www.dangalplay.com/tv-shows/palkon-ki-chhaon-mein-2/season-1/episode-1-palkon-ki-chhaon-mein-ep-01/ENTERR10_EPISODE_63514fd2bd9edd1c2e533879
[debug] Command-line config: ['-vU', '-F', 'https://www.dangalplay.com/tv-shows/palkon-ki-chhaon-mein-2/season-1/episode-1-palkon-ki-chhaon-mein-ep-01/ENTERR10_EPISODE_63514fd2bd9edd1c2e533879']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (darwin_exe)
[debug] Python 3.8.9 (CPython x86_64 64bit) - macOS-12.6.1-x86_64-i386-64bit (LibreSSL 2.8.3)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://www.dangalplay.com/tv-shows/palkon-ki-chhaon-mein-2/season-1/episode-1-palkon-ki-chhaon-mein-ep-01/ENTERR10_EPISODE_63514fd2bd9edd1c2e533879
[generic] ENTERR10_EPISODE_63514fd2bd9edd1c2e533879: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ENTERR10_EPISODE_63514fd2bd9edd1c2e533879: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.dangalplay.com/tv-shows/palkon-ki-chhaon-mein-2/season-1/episode-1-palkon-ki-chhaon-mein-ep-01/ENTERR10_EPISODE_63514fd2bd9edd1c2e533879
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp/extractor/common.py", line 674, in extract
  File "yt_dlp/extractor/generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.dangalplay.com/tv-shows/palkon-ki-chhaon-mein-2/season-1/episode-1-palkon-ki-chhaon-mein-ep-01/ENTERR10_EPISODE_63514fd2bd9edd1c2e533879
```

**Comment by Thuuren** [comment]
Would love to see support for dangalplay added as well.

**Comment by gamer191** [comment]
> Paid subscription

Log in with a browser, then add `--cookies-from-browser chrome` (or whatever browser you use) to the end of your command. Let me know if it works

**Comment by gamer191** [comment]
> Log in with a browser, then add `--cookies-from-browser chrome` (or whatever browser you use) to the end of your command. Let me know if it works

This issue will be reopened when someone does this and sends a verbose output

**Comment by xdrohit** [comment]
is it fixed?

**Comment by bashonly** [comment]
The site doesn't use cookies. The auth token is kept in local storage.

**Comment by xdrohit** [comment]
> The site doesn't use cookies. The auth token is kept in local storage.

Please tell me how to download videos from dangal play

**Comment by bashonly** [comment]
> Please tell me how to download videos from dangal play

It is not supported/possible yet. Patience. I will have a PR up soon and support will be added eventually

**Comment by xdrohit** [comment]
> > Please tell me how to download videos from dangal play
> 
> It is not supported/possible yet. Patience. I will have a PR up soon and support will be added eventually
okey sure sir,i will wait, thankyou
