### ISSUE TITLE
Golfchannel.com Support request

### ISSUE THREAD

**Issue by denaunistic** [yt-dlp/yt-dlp#5779]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United states 

### Example URLs

https://www.golfchannel.com/video/ockie-strydom-changing-plans-after-first-dp-world-tour-win
https://www.golfchannel.com/video/five-players-secure-pga-tour-champions-cards-2023

### Provide a description that is worded well enough to be understood

Currently yt-dlp can't extract video nor audio

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.golfchannel.com/video/five-players-secure-pga-tour-champions-cards-2023']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched/yt-dlp version 2022.12.11.810 [ee7750b] (win_exe)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-08-13-git-c469c3c3b1-full_build-www.gyan.dev (setts), ffprobe 2022-08-13-git-c469c3c3b1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1735 extractors
[debug] Fetching release info: https://api.github.com/repos/ytdl-patched/yt-dlp/releases/latest
Latest version: 2022.12.11.810, Current version: 2022.12.11.810
yt-dlp is up to date (2022.12.11.810)
[generic] Extracting URL: https://www.golfchannel.com/video/five-players-secure-pga-tour-champions-cards-2023
[generic] five-players-secure-pga-tour-champions-cards-2023: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] five-players-secure-pga-tour-champions-cards-2023: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.golfchannel.com/video/five-players-secure-pga-tour-champions-cards-2023
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1495, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1571, in __extract_info
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\generic.py", line 2453, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.golfchannel.com/video/five-players-secure-pga-tour-champions-cards-2023
```

**Comment by HobbyistDev** [comment]
We can extract video from this html tag
```html
<div id="block-schemablock">
            <div class="hidden" itemprop="video" itemscope itemtype="http://schema.org/VideoObject">
              <span>Video: <span itemprop="name">Five players secure PGA Tour Champions cards for 2023</span>
              </span>
              <meta itemprop="thumbnailUrl" content="https://www.golfchannel.com/sites/default/files/styles/thumbnail/public/mpx/thumbnail/nbc_golf_gc_qschool5v2_221210.jpg?itok=1giKVPoF" />
              <meta itemprop="contentURL" content="https://www.golfchannel.com/video/five-players-secure-pga-tour-champions-cards-2023" />
              <meta itemprop="embedURL" content="https://vplayer.golfchannel.com/p/BxmELC/gc_player/select/media/LH6SX1rsidVX" />
              <meta itemprop="uploadDate" content="2022-12-10" />
              <meta itemprop="height" content="650" />
              <meta itemprop="width" content="400" />
              <span itemprop="description">The Golf Central crew reacts to the emotional moment of five golfers earning PGA Tour Champions cards for the 2023 season.</span>
            </div>
```
We can extract the `embedURL` and then redirect to generic.
```shell
> yt-dlp -v "https://vplayer.golfchannel.com/p/BxmELC/gc_player/select/media/LH6SX1rsidVX"
[debug] Command-line config: ['-v', 'https://vplayer.golfchannel.com/p/BxmELC/gc_player/select/media/LH6SX1rsidVX']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1-full_build-www.gyan.dev (setts), ffprobe 5.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [generic] Extracting URL: https://vplayer.golfchannel.com/p/BxmELC/gc_player/select/media/LH6SX1rsidVX
[generic] LH6SX1rsidVX: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] LH6SX1rsidVX: Extracting information
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[debug] [ThePlatform] Extracting URL: https://player.theplatform.com/p/BxmELC/gc_player/embed/select/media/LH6SX1rsidVX?autoPlay=false
[ThePlatform] LH6SX1rsidVX: Downloading SMIL data
[ThePlatform] LH6SX1rsidVX: Checking video URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] LH6SX1rsidVX: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] LH6SX1rsidVX: Downloading 1 format(s): http-5274
[debug] Invoking http downloader on "https://prodamdgolfchnl.akamaized.net/NBCU_Sports_Group_-_GolfChannel/516/587/nbc_golf_gc_qschool5v2_221210_7.mp4"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Five players secure PGA Tour Champions cards for 2023 [LH6SX1rsidVX].mp4
[download]  27.4% of  139.08MiB at    1.98MiB/s ETA 00:50
ERROR: Interrupted by user
```

**Comment by doe1080** [comment]
now redirects to [nbcsports](https://www.nbcsports.com/watch/golf) and is already supported by `NBCSportsIE` (`_WORKING = False`)
