### ISSUE TITLE
ArteTV: single video that doesn't work

### ISSUE THREAD

**Issue by philcerf** [yt-dlp/yt-dlp#5780]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

DE

### Provide a description that is worded well enough to be understood

Most videos download just fine, but I found this one, which fails to download (but plays back in the browser):
https://www.arte.tv/de/videos/073107-004-A/naturparadiese-mit-zukunft/

Any ideas?

Thanks :-)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU  --download-archive archive.txt -- https://www.arte.tv/de/videos/073107-004-A/naturparadiese-mit-zukunft/
[debug] Command-line config: ['-vU', '--download-archive', 'archive.txt', '--', 'https://www.arte.tv/de/videos/073107-004-A/naturparadiese-mit-zukunft/']
[debug] User config "/home/philcerf/.config/yt-dlp/config": ['--abort-on-error', '--abort-on-unavailable-fragment', '--no-ignore-no-formats-error', '--no-overwrites', '--mtime', '--restrict-filenames', '--output', '%(title)s__[%(extractor)s:%(id)s].%(ext)s', '--no-cookies-from-browser', '--no-split-chapters', '--no-remove-chapters', '--no-force-keyframes-at-cuts', '--no-prefer-free-formats', '--no-sponsorblock', '--embed-chapters', '--no-embed-metadata', '--no-embed-info-json', '--no-embed-subs', '--no-embed-thumbnail', '--write-description', '--write-info-json', '--no-write-comments', '--no-clean-info-json', '--write-all-thumbnails', '--write-subs', '--sub-langs', 'all', '--write-annotations', '--write-playlist-metafiles']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (debian*)
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-6.0.0-5-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2-1 (setts), ffprobe 5.1.2-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.2, xattr-0.9.9
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Loading archive file 'archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [ArteTV] Extracting URL: https://www.arte.tv/de/videos/073107-004-A/naturparadiese-mit-zukunft/
[ArteTV] 073107-004-A: Downloading JSON metadata
[ArteTV] 073107-004-A: Downloading m3u8 information
[ArteTV] 073107-004-A: Downloading m3u8 information
[ArteTV] 073107-004-A: Downloading m3u8 information
[ArteTV] 073107-004-A: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 073107-004-A: Downloading subtitles: de, fr
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 073107-004-A: Downloading 1 format(s): VOA-2333+VOA-program_audio_0-VOA
[info] Video description is already present
[info] Video subtitle de.vtt is already present
[info] Writing video subtitles to: Ecuador_-_Hoffnung_fur_die_Nebelwalder__[ArteTV:073107-004-A].fr.vtt
[debug] Invoking hlsnative downloader on "https://arte-cmafhls.akamaized.net/am/cmaf/073000/073100/073107-004-A/221026063730/medias/073107-004-A_st_VF-MAL.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: Ecuador_-_Hoffnung_fur_die_Nebelwalder__[ArteTV:073107-004-A].fr.vtt
[download] Ecuador_-_Hoffnung_fur_die_Nebelwalder__[ArteTV:073107-004-A].fr.vtt.part-Frag1 has already been downloaded
[download] 100.0% of ~  77.89KiB at  Unknown B/s ETA Unknown (frag 1/1)Traceback (most recent call last):
  File "/usr/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2022.11.11', 'console_scripts', 'yt-dlp')())
  File "/usr/lib/python3/dist-packages/yt_dlp/__init__.py", line 968, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/lib/python3/dist-packages/yt_dlp/__init__.py", line 958, in _real_main
    return ydl.download(all_urls)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3322, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3297, in wrapper
    res = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1474, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1582, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1641, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2737, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2983, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3950, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2924, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3/dist-packages/yt_dlp/downloader/common.py", line 446, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3/dist-packages/yt_dlp/downloader/hls.py", line 351, in real_download
    self.download_and_append_fragments(
  File "/usr/lib/python3/dist-packages/yt_dlp/downloader/fragment.py", line 520, in download_and_append_fragments
    result = append_fragment(
  File "/usr/lib/python3/dist-packages/yt_dlp/downloader/fragment.py", line 479, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "/usr/lib/python3/dist-packages/yt_dlp/downloader/hls.py", line 266, in pack_fragment
    for block in webvtt.parse_fragment(frag_content):
  File "/usr/lib/python3/dist-packages/yt_dlp/webvtt.py", line 397, in parse_fragment
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 27366 (near '<c.green.bg_black>un')
```

**Comment by dirkf** [comment]
Line 829 of the French subtitles is blank:
```
00:15:11.240 --> 00:15:12.800 line:87% align:center

<c.green.bg_black>un travail titanesque !</c>
```
What happens if you ask the browser to show the French sub-titles?

The parser determined that the first line listed above isn't a `CommentBlock` and then looked for a `CueBlock` with this sequence:
1. optional ID line, not containing `-->`
2. line with timestamp `-->` timestamp, and optional settings
3. payload comprising non-empty lines.

This matches [4.1 of the WebVTT spec](https://www.w3.org/TR/webvtt1/#file-structure):
```
A WebVTT cue block consists of the following components, in the given order:
 1. Optionally, a WebVTT cue identifier followed by a WebVTT line terminator.
 2. WebVTT cue timings.
 3. Optionally, one or more U+0020 SPACE characters or U+0009 CHARACTER TABULATION (tab) characters followed by a WebVTT cue settings list.
 4. A WebVTT line terminator.
 5. The cue payload: either WebVTT caption or subtitle cue text, WebVTT chapter title text, or WebVTT metadata text, but it must not contain the substring "-->" (U+002D HYPHEN-MINUS, U+002D HYPHEN-MINUS, U+003E GREATER-THAN SIGN).
 6. A WebVTT line terminator. 
```
(The wording isn't clear as to whether the restriction on `-->` in the payload applies to all the payload types, or only metadata text; it isn't enforced in the parser.)

As the payload started with an empty line, it was considered to be empty (4.2.1 WebVTT metadata text, 0 characters followed by a line terminator) and the `CueBlock` was completed.

Then the parser tried to parse the next line, which is obviously meant to be the payload of the `CueBlock`. As the line didn't match any of the recognised WebVTT blocks, an error was reported.

On one hand this is apparently a defective VTT file that is correctly being detected as invalid and would only cause problems with player and conversion tools if passed through. On the other hand it would be nice to fix the obvious syntax error, by backtracking the parse if the next non-empty line doesn't match one of the possible WebVTT blocks, which at this point can only be `CommentBlock` or `CueBlock`.

Maybe s/t like this:
```diff
         text = io.StringIO()
         while True:
             m = parser.consume(cls._REGEX_PAYLOAD)
             if not m:
+                lookahead = parser.child()
+                if lookahead.consume(_REGEX_NL + '{2,}') and not any(b.parse(lookahead) for b in (CueBlock, CommentBlock)):
+                    lookahead.commit()
+                    continue
                 break
             text.write(m.group(0))
```

**Comment by pukkandan** [comment]
Related: #2175

**Comment by philcerf** [comment]
> What happens if you ask the browser to show the French sub-titles?

There are four types of subtitles listed (in the browser):
* German, French
  Nothing seems to happen for any of them, i.e. not subtitles are displayed.
* German for the hearing-impaired, French for the hearing-impaired
  For both, subtitles are displayed.

**Comment by dirkf** [comment]
Well, yt-dlp only finds:
```
[info] Available subtitles for 073107-004-A:
Language Formats
de       vtt
fr       vtt
```
Perhaps the plain German/French options corresponds to the DE/FR audio tracks, of which one is presumably more dubbed than the other? If there were actual subtitles for these cases, the German one might have any translated French speech and vice versa; the hearing-impaired subtitles would have the whole thing transcribed and translated into the subtitle language where necessary.

**Comment by HubGit01** [comment]
quick fix, in file "webvtt.py":
```python
    def __init__(self, string):
-            self._data = string
+            self._data = string.replace("\r\n\r\n<", "\r\n<")
        self._pos = 0
```

**Comment by HubGit01** [comment]
Enhanced quick fix, in file "webvtt.py":
```
def __init__(self, string):
-    self._data = string
+    self._data = re.sub("\r\n\s+<", "\r\n<", string)
    self._pos = 0
```
