### ISSUE TITLE
Site request: laxd.com

### ISSUE THREAD

**Issue by Yusuke525** [yt-dlp/yt-dlp#5805]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Japan

### Example URLs

- Single video: https://video.laxd.com/a/content/SQSSQVQYzrAMs6tZ

### Provide a description that is worded well enough to be understood

Please add this extractor to yt-dlp.
Since this site is a derivative of fc2, which already supports yt-dlp, perhaps a similar process could be used to enable downloading.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://video.laxd.com/a/content/SQSSRSRUCGhOVqCI']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.7.4 (CPython x86_64 64bit) - Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-9.11 (OpenSSL 1.1.0l  10 Sep 2019, glibc 2.2.5)
[debug] exe versions: ffmpeg 3.2.18-0, ffprobe 3.2.18-0
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://video.laxd.com/a/content/SQSSRSRUCGhOVqCI
[generic] SQSSRSRUCGhOVqCI: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] SQSSRSRUCGhOVqCI: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://video.laxd.com/a/content/SQSSRSRUCGhOVqCI
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/generic.py", line 2721, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://video.laxd.com/a/content/SQSSRSRUCGhOVqCI
```

**Comment by coletdjnz** [comment]
https://github.com/yt-dlp/yt-dlp/issues/4525
