### ISSUE TITLE
Critical: | in yt videos throws an error

### ISSUE THREAD

**Issue by CrazyWolf13** [yt-dlp/yt-dlp#5819]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Those videos won't work: 
https://www.youtube.com/watch?v=LjF9IqvXDjY

I wondered why and saw this popping up, a character error. 
I wonder why noone has discovered this until now.
![Screenshot 2022-12-17 170109](https://user-images.githubusercontent.com/96661824/208250798-bdec92a5-7c52-4a59-a548-f9ae5b0f0a71.png)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-o', '/media/pi/Seagate/Youtube-dl/%(title)s.%(ext)s', '-x', '--audio-format', 'mp3', '-ciwvU', 'https://www.youtube.com/watch?v=LjF9IqvXDjY']
[debug] Encodings: locale ISO-8859-15, fs iso8859-15, pref ISO-8859-15, out iso8859-15, error iso8859-15, screen iso8859-15
[debug] yt-dlp version 2022.10.04 [4e0511f27]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.15.76-v8+-aarch64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1699 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.10.04
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.11.11/_update_spec
ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=LjF9IqvXDjY
[youtube] LjF9IqvXDjY: Downloading webpage
[youtube] LjF9IqvXDjY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] LjF9IqvXDjY: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr6---sn-nfpnnjvh-1gik.googlevideo.com/videoplayback?expire=1671315036&ei=_OmdY-eCJYCD6dsPn526yAk&ip=2a02%3A1210%3A2a42%3Aeb00%3Af5d0%3A4bc6%3A18e1%3A1993&id=o-AOC_EdrVTPWwokypH4PMKJZSS9dQ3yRZADymfUpvhBcK&itag=251&source=youtube&requiressl=yes&mh=Xj&mm=31%2C29&mn=sn-nfpnnjvh-1gik%2Csn-1gi7znek&ms=au%2Crdu&mv=m&mvi=6&pl=41&initcwndbps=2103750&spc=zIddbP_INdCCJa9EENg_gf0CRSUi4oA&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3587438&dur=225.421&lmt=1574759808157463&mt=1671293144&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALch1XJIQqMxFjxF-d23sURI3MbBmwIqDFtD_jAhB2zmAiEAmuirbhl6BTcs8aexcLGB4unRJlqHlvuj238KJwSfi-c%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgV5hw79302i4Ccz9xeFVJwPRWnn_X923EAb8G5ruTSuECIH-NaG7OyhtAittXmGJkp9S3LPr6RxlBatTsYF44iNQU"
ERROR: 'charmap' codec can't encode character '\uff5c' in position 87: character maps to <undefined>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1574, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1633, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2730, in process_video_result
    self.process_info(new_info)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3193, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2917, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 446, in download
    ret = self.real_download(filename, info_dict)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 372, in real_download
    return download()
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 267, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 232, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 243, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/utils.py", line 632, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/home/pi/.local/lib/python3.9/site-packages/yt_dlp/utils.py", line 2162, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
  File "/usr/lib/python3.9/encodings/iso8859_15.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\uff5c' in position 87: character maps to <undefined>
```

**Comment by pukkandan** [comment]
Workaround, use `--restrict-filenames`

**Comment by CrazyWolf13** [comment]
> Workaround, use `--restrict-filenames`

Thank you very much

**Comment by CrazyWolf13** [comment]
> Workaround, use `--restrict-filenames`

Thats quite abnormal for me, it seems that yt-dlp already has problems with simple characters as ',|,- and some more is that remated to my language settings?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/5341
