### ISSUE TITLE
Adding IMD Videos Support

### ISSUE THREAD

**Issue by AlirezaJanbabaei** [yt-dlp/yt-dlp#5843]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

- Single Video (one part): https://videos.imedicaldoctor.net/cmeinfo/1Classroom2021/Parts/videos-01%20-%20Neuroscience.mp4.1
- Playlist: https://videos.imedicaldoctor.net/cmeinfo/1Classroom2021/Parts/

### Provide a description that is worded well enough to be understood

Every Playlist has a lot of videos. Every Video is splitted into 10 parts that I can't download them.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://videos.imedicaldoctor.net/cmeinfo/1Classroom2021/Parts/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev (setts), ffprobe 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://videos.imedicaldoctor.net/cmeinfo/1Classroom2021/Parts/
[generic] Parts: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Parts: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://videos.imedicaldoctor.net/cmeinfo/1Classroom2021/Parts/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
```

**Comment by dirkf** [comment]
You could use _wget_ instead. Or [_ffmpeg_](https://trac.ffmpeg.org/wiki/Concatenate) if you want to get all the parts as one video.

**Comment by AlirezaJanbabaei** [comment]
> 

The problem is I can't merge them. when I play each part it doesn't play

**Comment by dirkf** [comment]
Presumably the site has just split the videos at a certain size and you need to concatenate them manually to get a valid .mp4:
```
# POSIX shell
rm -f 'videos-01 - Neuroscience.mp4'
for i in $(seq 1 10); do
    wget -q -O - "https://videos.imedicaldoctor.net/cmeinfo/1Classroom2021/Parts/videos-01%20-%20Neuroscience.mp4.${i}" >> 'videos-01 - Neuroscience.mp4' || { echo "$i: download error"; break; }
done
```
or
```
REM Windows cmd
del /q "videos-01 - Neuroscience.mp4" 2>NUL
for /l %I in (1,1,10) do (
    wget -q -O - "https://videos.imedicaldoctor.net/cmeinfo/1Classroom2021/Parts/videos-01%20-%20Neuroscience.mp4.%I" >> "videos-01 - Neuroscience.mp4" || ( echo %I: download error & goto break )
)
:break
```
Or the site is a spoof with a lot of fake video files ...

**Comment by AlirezaJanbabaei** [comment]
Hey Everyone,
I was hoping someone could help me how to play this file?
the file is playable through the app but when I download the file using yt-dlp it is not played?
https://videos.imedicaldoctor.net/cmeinfo/xray-lectures/videos-01558775372.mp4

**Comment by bashonly** [comment]
Reiterating what I wrote in #6143:

This is subscription-only content for a paid app. It's unlikely anyone will be able to figure out how the app makes this video work without access to the site/app. 

>  I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

Are you actually willing to do this ^?

**Comment by AlirezaJanbabaei** [comment]
Username : vigipiv776_demo@iucake.com
Password : vZapD
this account is demo and works only for 24hrs.
@bashonly @dirkf

**Comment by AlirezaJanbabaei** [comment]
> Username : [vigipiv776_demo@iucake.com](mailto:vigipiv776_demo@iucake.com) Password : vZapD Android: https://play.google.com/store/apps/details?id=net.imedicaldoctor.imd&hl=en&gl=US on IOS: first install Avicenna - Drug Interactions then open the app and search **givemeimd** on the first page to activate the application. this account is demo and works only for 24hrs. @bashonly @dirkf

nothing by anyone?
