### ISSUE TITLE
[Pinterest] 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Visne** [yt-dlp/yt-dlp#5850]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Provide a description that is worded well enough to be understood

I've tried downloading other videos and they seem to work just fine. I'm not sure why this video is not working.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://pinterest.com/pin/678002918919219984/
[debug] Command-line config: ['-vU', 'https://pinterest.com/pin/678002918919219984/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402]
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.0.12-arch1-1-x86_64-with-glibc2.36 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotlicffi-1.0.9.2, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [Pinterest] Extracting URL: https://pinterest.com/pin/678002918919219984/
[Pinterest] 678002918919219984: Download Pin JSON metadata
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/pinterest.py", line 136, in _real_extract
    return self._extract_video(data)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/pinterest.py", line 34, in _extract_video
    for format_id, format_dict in data['videos']['video_list'].items():
TypeError: 'NoneType' object is not subscriptable
```
```

**Comment by bashonly** [comment]
Fixed in f549b18512570d0c000179df9147415e4eba1649

You can wait for the next release, [use the master branch](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip) or try the [unofficial daily builds](https://github.com/ytdl-patched/yt-dlp)

Closing as duplicate of #1772

**Comment by Visne** [comment]
Ah, I didn't find that issue when I was searching. Thanks for fixing it!
