### ISSUE TITLE
Hotstar forbidden error

### ISSUE THREAD

**Issue by Admire1231** [yt-dlp/yt-dlp#5868]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

Hotstar giving forbidden error though the video are playable in browser

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.hotstar.com/in/e307-kara
n-wins-the-contract/1000281715
[debug] Command-line config: ['-vU', 'https://www.hotstar.com/in/e307-karan-wins
-the-contract/1000281715']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-2012ServerR2-6.3.9600-SP0
(OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-92391-g07bc603757
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24,
 mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [hotstar] Extracting URL: https://www.hotstar.com/in/e307-karan-wins-the
-contract/1000281715
[hotstar] 1000281715: Downloading JSON metadata
[hotstar] 1000281715: Downloading webpage
[hotstar] 1000281715: Downloading token
[hotstar] 1000281715: Downloading JSON metadata
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7),
vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, pro
to, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1000281715: Downloading 1 format(s): sdr-dash-video_h265_fhd_sdr_16717157
54879-hvc1-4-1+sdr-dash-audio_aac_1671711421329-und-mp4a-3-3
[debug] Invoking http downloader on "https://hses6.hotstar.com/videos/plus/ksbkb
tesp/307_f1d13953cf/656/1000281715/v3/1671711421329/b43a7d0f406c8c62118a85d357b5
9afd/seg-video_h265_fhd_sdr_1671715754879-hvc1-4.mp4"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3182, in process_info
  File "yt_dlp\YoutubeDL.py", line 2924, in dl
  File "yt_dlp\downloader\common.py", line 446, in download
  File "yt_dlp\downloader\http.py", line 371, in real_download
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3692, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

Are you sure it plays in browser under **the same IP**?

```
❯ yt-dlp https://www.hotstar.com/in/e307-karan-wins%20-the-contract/1000281715
[hotstar] Extracting URL: https://www.hotstar.com/in/e307-karan-wins%20-the-contract/1000281715
[hotstar] 1000281715: Downloading JSON metadata
[hotstar] 1000281715: Downloading webpage
[hotstar] 1000281715: Downloading token
[hotstar] 1000281715: Downloading JSON metadata
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading MPD manifest
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading m3u8 information
[hotstar] 1000281715: Downloading m3u8 information
[info] 1000281715: Downloading 1 format(s): video_h265_fhd_sdr_1671715754879-hvc1-4+audio_mp4a_65-Unknown-1
[download] Resuming download at byte 4193280
[download] Destination: E307 - Karan Wins the Contract [1000281715].fvideo_h265_fhd_sdr_1671715754879-hvc1-4.mp4
[download]   6.8% of  118.44MiB at    2.06MiB/s ETA 00:53
ERROR: Interrupted by user
```

**Comment by Admire1231** [comment]
> 

yes it is playable in chrome browser on same ip

**Comment by bibsp** [comment]
Exact same issue here. I was just about to open new issue.
