### ISSUE TITLE
[CNBCVideo/CNBC/ThePlatform] broken extractor

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#5871]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

probably worldwide, but accessed from United States

### Provide a description that is worded well enough to be understood

The page source has direct links to multiple video formats, as the following snippet shows:

`
[{"url":"https:\u002F\u002Fcnbcawsmpvod.akamaized.net\u002Fout\u002Fv1\u002F89f391a8d02945bcba689ffb2f88b84d\u002F54fbf64382f04b94bb69340d5528ff8b\u002F26cdcccd8cb84f5398bc0124836d47ee\u002Fmaster.m3u8","formatName":"mpeg4_1_HLSMBRStreaming","__typename":"encoding"},{"url":"http:\u002F\u002Fpdl.iphone.cnbc.com\u002FVCPS\u002FY2022\u002FM10D13\u002F7000268077\u002F1665674918193-biggestcryptoheist_H264_126K.mp4","formatName":"mpeg4_200000_Download","__typename":"encoding"},{"url":"http:\u002F\u002Fpdl.iphone.cnbc.com\u002FVCPS\u002FY2022\u002FM10D13\u002F7000268077\u002F1665674918193-biggestcryptoheist_L.mp4","formatName":"mpeg4_500000_Download","__typename":"encoding"},{"url":"http:\u002F\u002Fvideoman.cnbc.com\u002Fvcps\u002Fmedia\u002Fcontent?id=NzAwMDI2ODA3NwptcGVnNF81MDAwMDAKU3RyZWFtaW5n&UserName=cmsguest@cnbc.com&key=NA","formatName":"mpeg4_500000_Streaming","__typename":"encoding"},{"url":"http:\u002F\u002Fpdl.iphone.cnbc.com\u002FVCPS\u002FY2022\u002FM10D13\u002F7000268077\u002F1665674918193-biggestcryptoheist_mp3w_048K.mp3","formatName":"mpeg3_48000_Download","__typename":"encoding"},{"url":"http:\u002F\u002Fpdl.iphone.cnbc.com\u002FVCPS\u002FY2022\u002FM10D13\u002F7000268077\u002F1665674918193-biggestcryptoheist_mp3w_128K.mp3","formatName":"mpeg3_128000_Download","__typename":"encoding"},{"url":"http:\u002F\u002Fcnbcmbr-vh.akamaihd.net\u002Fz\u002Fmp4\u002FVCPS\u002FY2022\u002FM10D13\u002F7000268077\u002F1665674918193-biggestcryptoheist_MBR_,0240,0300,0500,0700,0900,1300,1700,4500,.mp4.csmil\u002Fmanifest.f4m","formatName":"mpeg4_1_HDNMBRStreaming","__typename":"encoding"},{"url":"http:\u002F\u002Fpdl.iphone.cnbc.com\u002FVCPS\u002FY2022\u002FM10D13\u002F7000268077\u002F1665674918193-biggestcryptoheist_H264_1M_720x405.mp4","formatName":"mpeg4_1100000_Download","__typename":"encoding"},{"url":"http:\u002F\u002Fvideoman.cnbc.com\u002Fvcps\u002Fmedia\u002Fcontent?id=NzAwMDI2ODA3NwptcGVnNF9wYXNzXzQ1MDBLClN0cmVhbWluZw&UserName=cmsguest@cnbc.com&key=NA","formatName":"__Streaming","__typename":"encoding"},{"url":"http:\u002F\u002Fpdl.iphone.cnbc.com\u002FVCPS\u002FY2022\u002FM10D13\u002F7000268077\u002F1665674918193-biggestcryptoheist.vtt","formatName":"WebVTT_0_Download","__typename":"encoding"},{"url":"http:\u002F\u002Fpdl.iphone.cnbc.com\u002FVCPS\u002FY2022\u002FM10D13\u002F7000268077\u002F1665674918193-biggestcryptoheist_H264_480x270_25p_500K.mp4","formatName":"mpeg4_600000_Download","__typename":"encoding"},{"url":"ftp:\u002F\u002Fcnbc.upload.akamai.com\u002Fh\u002FVCPS\u002FY2022\u002FM10D13\u002F7000268077\u002F1665674918193-biggestcryptoheist_flv_432x240_30p_500k.flv","formatName":"flv_500000_Download","__typename":"encoding"},{"url":"http:\u002F\u002Fvideoman.cnbc.com\u002Fvcps\u002Fmedia\u002Fcontent?id=NzAwMDI2ODA3NwpGTFZfNDMyeDI0MF8zMHBfNTAwSwpTdHJlYW1pbmc&UserName=cmsguest@cnbc.com&key=NA","formatName":"flv_500000_Streaming","__typename":"encoding"},{"url":"http:\u002F\u002Fpdl.iphone.cnbc.com\u002FVCPS\u002FY2022\u002FM10D13\u002F7000268077\u002F1665674918193-biggestcryptoheist_MBR_4500.mp4","formatName":"mpeg4_4500000_Download","__typename":"encoding"},{"url":"http:\u002F\u002Fvideoman.cnbc.com\u002Fvcps\u002Fmedia\u002Fcontent?id=NzAwMDI2ODA3NwptcGVnNHdfNDUwMEsKU3RyZWFtaW5n&UserName=cmsguest@cnbc.com&key=NA","formatName":"mpeg4_4500000_Streaming","__typename":"encoding"},{"url":"https:\u002F\u002Fcnbcawsmpvod.akamaized.net\u002Fout\u002Fv1\u002F89f391a8d02945bcba689ffb2f88b84d\u002F54fbf64382f04b94bb69340d5528ff8b\u002F26cdcccd8cb84f5398bc0124836d47ee\u002Fmaster.m3u8","formatName":"mpeg4_500000_HLSSBRStreaming","__typename":"encoding"}],"author":[],"sourceOrganization":[{"id":80000022,"slug":"CNBC US Source","tagName":"CNBC US Source","tagNameFormatted":"cnbc us source","tagNameFormattedFull":"cnbc us source","__typename":"source"}]
`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-F', '-v', 'https://www.cnbc.com/video/2022/10/13/new-the-accused-crypto-couple.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.9.16 (CPython x86_64 64bit) - Linux-5.15.69-with-glibc2.36 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.36)
[debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe 4.4.3
[debug] Optional libraries: Crypto-3.15.0, certifi-3021.03.16
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [CNBCVideo] Extracting URL: https://www.cnbc.com/video/2022/10/13/new-the-accused-crypto-couple.html
[CNBCVideo] new-the-accused-crypto-couple: Downloading JSON metadata
[debug] [CNBC] Extracting URL: http://video.cnbc.com/gallery/?video=7000268077
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/gZWlPC/media/guid/2408950221/7000268077?mbr=true&manifest=m3u#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 7000268077: Downloading SMIL data
[ThePlatform] 7000268077: Downloading m3u8 information
WARNING: [ThePlatform] Failed to download m3u8 information: HTTP Error 400: Bad Request
[ThePlatform] 7000268077: Downloading JSON metadata
ERROR: [ThePlatform] 7000268077: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1582, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1694, in process_ie_result
    return self.process_ie_result(
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1641, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2573, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1035, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ThePlatform] 7000268077: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by git42leech** [comment]
All it really takes is swapping `\u002F` to `/` and the M3U is working again.
