### ISSUE TITLE
ERROR: An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by LovelyBloom** [yt-dlp/yt-dlp#5872]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I cannot use yt-dlp with v2rayN.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\nom4d> yt-dlp -vU PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU
[debug] Command-line config: ['-vU', 'PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU']
[debug] User config "C:\Users\nom4d\AppData\Roaming\yt-dlp\config.txt": ['--force-ipv4', '--concurrent-fragments', '16', '-S', 'res:1080', '--retries', 'infinite', '--fragment-retries', 'infinite', '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '--embed-subs', '--embed-thumbnail', '--embed-metadata', '--write-playlist-metafiles', '--add-chapters', '--downloader', 'aria2c', '--output', 'D:\\yt-dlp\\%(playlist)s\\%(playlist_index)s - %(title)s.%(ext)s', '--download-archive', 'C:\\Users\\nom4d\\OneDrive\\youtube_down_history.txt']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.10.7 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-55702-g920046a (needs_adtstoasc), ffprobe N-55702-g920046a, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'http': 'http://127.0.0.1:5359', 'https': 'http://127.0.0.1:5359', 'ftp': 'http://127.0.0.1:5359', 'socks': 'socks://127.0.0.1:5358'}
[debug] Loaded 1723 extractors
[debug] Loading archive file 'C:\\Users\\nom4d\\OneDrive\\youtube_down_history.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube:playlist] Extracting URL: PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU
[youtube:tab] PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU: Downloading webpage
WARNING: [youtube:tab] <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>. Retrying (1/3)...
[youtube:tab] PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU: Downloading webpage
WARNING: [youtube:tab] <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>. Retrying (2/3)...
[youtube:tab] PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU: Downloading webpage
WARNING: [youtube:tab] <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>. Retrying (3/3)...
[youtube:tab] PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU: Downloading webpage
WARNING: [youtube:tab] Unable to download webpage: <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions> (caused by URLError(PermissionError(13, 'An attempt was made to access a socket in a way forbidden by its access permissions', None, 10013, None))). Giving up after 3 retries
[youtube:tab] PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU: Downloading API parameters API JSON
WARNING: [youtube:tab] <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>. Retrying (1/3)...
[youtube:tab] PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU: Downloading API parameters API JSON
WARNING: [youtube:tab] <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>. Retrying (2/3)...
[youtube:tab] PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU: Downloading API parameters API JSON
WARNING: [youtube:tab] <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>. Retrying (3/3)...
[youtube:tab] PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU: Downloading API parameters API JSON
ERROR: [youtube:tab] PLre5AT9JnKShBOPeuiD9b-I4XROIJhkIU: Unable to download API page: <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions> (caused by URLError(PermissionError(13, 'An attempt was made to access a socket in a way forbidden by its access permissions', None, 10013, None)))
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\youtube.py", line 4285, in wrapper
    info_dict = func(self, url, smuggled_data)
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\youtube.py", line 5999, in _real_extract
    data, ytcfg = self._extract_data(url, display_id)
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\youtube.py", line 4937, in _extract_data
    data = self._extract_tab_endpoint(url, item_id, ytcfg, fatal=fatal, default_client=default_client)
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\youtube.py", line 4942, in _extract_tab_endpoint
    resolve_response = self._extract_response(
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\youtube.py", line 860, in _extract_response
    for retry in self.RetryManager():
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\utils.py", line 5921, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\common.py", line 3882, in _error_or_warning
    RetryManager.report_retry(
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\utils.py", line 5929, in report_retry
    raise e
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\youtube.py", line 862, in _extract_response
    response = self._call_api(
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\youtube.py", line 538, in _call_api
    return self._download_json(
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\common.py", line 1034, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\common.py", line 998, in download_handle
    res = self._download_webpage_handle(
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\common.py", line 868, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\common.py", line 825, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\Program Files\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Program Files\Python310\lib\http\client.py", line 1447, in connect
    super().connect()
  File "C:\Program Files\Python310\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\utils.py", line 1313, in _create_connection
    raise err
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\utils.py", line 1305, in _create_connection
    sock.connect(sa)
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\extractor\common.py", line 807, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\YoutubeDL.py", line 3692, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\nom4d\AppData\Roaming\Python\Python310\site-packages\yt_dlp\utils.py", line 1527, in https_open
    return self.do_open(
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions>

NativeCommandExitException: Program "yt-dlp.exe" ended with non-zero exit code: 1.
```

**Comment by pukkandan** [comment]
Issue with your network, likely your proxy
