### ISSUE TITLE
ERROR: When downloading music from vk.com

### ISSUE THREAD

**Issue by ademaro** [yt-dlp/yt-dlp#5886]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm assuming that the headers (`User-Agent`) of older browsers are being passed. 
For example, you can upgrade to one of these: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vk.com/audio-2001173003_68173003']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.11.0 (CPython arm64 64bit) - macOS-13.1-arm64-arm-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://vk.com/audio-2001173003_68173003
[generic] audio-2001173003_68173003: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] audio-2001173003_68173003: Extracting information
[debug] Looking for embeds
[redirect] Following redirect to https://vk.com/badbrowser.php
[debug] [generic] Extracting URL: https://vk.com/badbrowser.php
[generic] badbrowser: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] badbrowser: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://vk.com/badbrowser.php
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2022.11.11/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2721, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vk.com/badbrowser.php
```

**Comment by pukkandan** [comment]
> ###
> I'm assuming that the headers (`User-Agent`) of older browsers are being passed. For example, you can upgrade to one of these: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

Did you try passing this as `--user-agent`?

**Comment by bashonly** [comment]
I don't think this has anything to do with user-agent; trying with a newer UA yields the same result. 

The example URL is not matched by any of the vk extractors' `_VALID_URL` regex, and then the generic extractor can't find any embeds, so it follows a noscript redirect to `badbrowser.php`. Support for this type of vk page will need to be added.

**Comment by october262** [comment]
this works - ffmpeg -user_agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" -referer "https://vk.com" -i "https://psv4.vkuseraudio.net/s/v1/as/gTXDQqhEgBlGP-yDmy37djLwNTzdkkjxsWhVug4mXup56F4MfGyAVx2e_5X6z0E8zz8WS1D3PnRogW1NxiR1d9bwndUGV6PysOVyRDKrAyolLSw8eN9x9PABfgqQ1Vs/index.m3u8" -c copy "index.mp4"
