### ISSUE TITLE
AnyClass

### ISSUE THREAD

**Issue by slavakurilyak** [yt-dlp/yt-dlp#5901]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Russia

### Example URLs

- Single video: https://anyclass.com/class/course/1011477/calendar/1
- Playlist: https://anyclass.com/class/course/1011477/calendar

### Provide a description that is worded well enough to be understood

Please add an extractor for [AnyClass](https://anyclass.com/)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[...]
```

**Comment by pukkandan** [comment]
The verbose log field is not optional. We often get site support requests for already supported pages. Show verbose log of yt-dlp failing with cookies passed

**Comment by pukkandan** [comment]
You are still not passing cookies

**Comment by slavakurilyak** [comment]
@pukkandan check **Complete Verbose Output** again

**Comment by pukkandan** [comment]
I'm a bit confused

> [debug] Command-line config: ['-vU', 'https://anyclass.com/lesson/video/2be6f79fa8e1b50fc16b173331ace9fa5e997323a39475.24433671/720/video.m3u8', '--referer', 'https://anyclass.com/', '--cookies-from-browser', 'chrome']

Does this URL open in browser for you? Is this the URL you even want us to support?

**Comment by slavakurilyak** [comment]
@pukkandan I also tried `$ yt-dlp -vU https://anyclass.com/class/course/1011477/calendar/1 --referer https://anyclass.com --cookies-from-browser chrome`

Here's the response:

```
[debug] Command-line config: ['-vU', 'https://anyclass.com/class/course/1011477/calendar/1', '--referer', 'https://anyclass.com', '--cookies-from-browser', 'chrome']
[debug] User config: []
[debug] System config: []
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.02 [d83b0ad] (zip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - macOS-12.6.2-x86_64-i386-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/skurilyak/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 3235 cookies from chrome
[debug] cookie version breakdown: {'v10': 3194, 'other': 0, 'unencrypted': 41}
[debug] Proxy map: {}
[debug] Loaded 1754 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.02, Current version: 2023.01.02
yt-dlp is up to date (2023.01.02)
[generic] Extracting URL: https://anyclass.com/class/course/1011477/calendar/1
[generic] 1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://anyclass.com/class/course/1011477/calendar/1
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1497, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1573, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2523, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://anyclass.com/class/course/1011477/calendar/1
```
