### ISSUE TITLE
How to stop live stream recording gracefully programatically

### ISSUE THREAD

**Issue by agieocean** [yt-dlp/yt-dlp#5902]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to download a couple seconds of a live stream through python and then stop gracefully. I have tried running the code as a subprocess and running the code as a multiprocessing Process, trying to terminate or otherwise send a ctrl c signal to the process does not stop it at all. What can I do to stop the download programtically? Here's the relevant code:
```
from yt_dlp import YoutubeDL

def getLast(url):
    ydl_opts = {
        'outtmpl': 'downloads/%(title)s.%(ext)s',
        'format': 'bestvideo/best',
        'prefer_ffmpeg': True
    }
    ydl = YoutubeDL(ydl_opts)
    ydl.download([url])
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] FjEmM_a4nwE: Downloading webpage
[youtube] FjEmM_a4nwE: Downloading android player API JSON
[youtube] FjEmM_a4nwE: Downloading m3u8 information
[youtube] FjEmM_a4nwE: Downloading m3u8 information
[info] FjEmM_a4nwE: Downloading 1 format(s): 96
[download] Destination: downloads\Pennekamp Coral Cam 2022-12-30 11_50.mp4
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-VERSION:3')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:20490')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-12-30T16:50:20.384+00:00')
[hls @ 0000015d39fc5f00] Opening 'https://rr5---sn-p5qddn7k.googlevideo.com/videoplayback/id/FjEmM_a4nwE.2/itag/96/source/yt_live_broadcast/expire/1672440654/ei/7havY7b7M5qIhgbD4ZZg/ip/73.12.30.172/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-p5qddn7k.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/zIddbL3FM_zYhWZUxe4uMK_OAUZMmng/vprv/1/playlist_type/DVR/initcwndbps/1895000/mh/Lj/mm/44/mn/sn-p5qddn7k/ms/lva/mv/m/mvi/5/pl/17/keepalive/yes/fexp/24001373,24007246/mt/1672418913/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAIidh9gV1k5721GAgB4g4fySiKBQUmQuszgOK7c3pIz1AiBkksFTlppc310pS4O9DRTGHbcRGrDgCIAbLB0i_RdP-A%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgY2rqqEA9CrvBsiDw5R1y7A49k4jJ22UwVPrTLVx1iHECIQD6RP6yNyJCSwgf0RieBhda4dYbPCwNRoMtUCloSMGpbQ%3D%3D/playlist/index.m3u8/sq/1162970/goap/clen%3D84103%3Blmt%3D1672418794552329/govp/clen%3D1806140%3Blmt%3D1672418794552327/dur/5.133/file/seg.ts' for reading
[hls @ 0000015d39fc5f00] Opening 'https://rr5---sn-p5qddn7k.googlevideo.com/videoplayback/id/FjEmM_a4nwE.2/itag/96/source/yt_live_broadcast/expire/1672440654/ei/7havY7b7M5qIhgbD4ZZg/ip/73.12.30.172/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-p5qddn7k.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/zIddbL3FM_zYhWZUxe4uMK_OAUZMmng/vprv/1/playlist_type/DVR/initcwndbps/1895000/mh/Lj/mm/44/mn/sn-p5qddn7k/ms/lva/mv/m/mvi/5/pl/17/keepalive/yes/fexp/24001373,24007246/mt/1672418913/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAIidh9gV1k5721GAgB4g4fySiKBQUmQuszgOK7c3pIz1AiBkksFTlppc310pS4O9DRTGHbcRGrDgCIAbLB0i_RdP-A%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgY2rqqEA9CrvBsiDw5R1y7A49k4jJ22UwVPrTLVx1iHECIQD6RP6yNyJCSwgf0RieBhda4dYbPCwNRoMtUCloSMGpbQ%3D%3D/playlist/index.m3u8/sq/1162971/goap/clen%3D84103%3Blmt%3D1672418794552345/govp/clen%3D1619936%3Blmt%3D1672418794552343/dur/5.133/file/seg.ts' for reading
Input #0, hls, from 'https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1672440654/ei/7havY7b7M5qIhgbD4ZZg/ip/73.12.30.172/id/FjEmM_a4nwE.2/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-p5qddn7k.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/zIddbL3FM_zYhWZUxe4uMK_OAUZMmng/vprv/1/playlist_type/DVR/initcwndbps/1895000/mh/Lj/mm/44/mn/sn-p5qddn7k/ms/lva/mv/m/mvi/5/pl/17/dover/11/pacing/0/keepalive/yes/fexp/24001373,24007246/mt/1672418913/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAIidh9gV1k5721GAgB4g4fySiKBQUmQuszgOK7c3pIz1AiBkksFTlppc310pS4O9DRTGHbcRGrDgCIAbLB0i_RdP-A%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgY2rqqEA9CrvBsiDw5R1y7A49k4jJ22UwVPrTLVx1iHECIQD6RP6yNyJCSwgf0RieBhda4dYbPCwNRoMtUCloSMGpbQ%3D%3D/playlist/index.m3u8':
  Duration: N/A, start: 64358.728689, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
Output #0, mpegts, to 'file:downloads\Pennekamp Coral Cam 2022-12-30 11_50.mp4.part':
  Metadata:
    encoder         : Lavf59.34.102
  Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[https @ 0000015d3a531600] Opening 'https://rr5---sn-p5qddn7k.googlevideo.com/videoplayback/id/FjEmM_a4nwE.2/itag/96/source/yt_live_broadcast/expire/1672440654/ei/7havY7b7M5qIhgbD4ZZg/ip/73.12.30.172/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-p5qddn7k.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/zIddbL3FM_zYhWZUxe4uMK_OAUZMmng/vprv/1/playlist_type/DVR/initcwndbps/1895000/mh/Lj/mm/44/mn/sn-p5qddn7k/ms/lva/mv/m/mvi/5/pl/17/keepalive/yes/fexp/24001373,24007246/mt/1672418913/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAIidh9gV1k5721GAgB4g4fySiKBQUmQuszgOK7c3pIz1AiBkksFTlppc310pS4O9DRTGHbcRGrDgCIAbLB0i_RdP-A%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgY2rqqEA9CrvBsiDw5R1y7A49k4jJ22UwVPrTLVx1iHECIQD6RP6yNyJCSwgf0RieBhda4dYbPCwNRoMtUCloSMGpbQ%3D%3D/playlist/index.m3u8/sq/1162972/goap/clen%3D81098%3Blmt%3D1672418794552361/govp/clen%3D1962748%3Blmt%3D1672418794552359/dur/4.933/file/seg.ts' for reading
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-VERSION:3'):00:13.12 bitrate=3035.7kbits/s speed=2.65x
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:20490')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-12-30T16:50:25.317+00:00')
[https @ 0000015d3a531600] Opening 'https://rr5---sn-p5qddn7k.googlevideo.com/videoplayback/id/FjEmM_a4nwE.2/itag/96/source/yt_live_broadcast/expire/1672440654/ei/7havY7b7M5qIhgbD4ZZg/ip/73.12.30.172/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-p5qddn7k.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/zIddbL3FM_zYhWZUxe4uMK_OAUZMmng/vprv/1/playlist_type/DVR/initcwndbps/1895000/mh/Lj/mm/44/mn/sn-p5qddn7k/ms/lva/mv/m/mvi/5/pl/17/keepalive/yes/fexp/24001373,24007246/mt/1672418913/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAIidh9gV1k5721GAgB4g4fySiKBQUmQuszgOK7c3pIz1AiBkksFTlppc310pS4O9DRTGHbcRGrDgCIAbLB0i_RdP-A%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgY2rqqEA9CrvBsiDw5R1y7A49k4jJ22UwVPrTLVx1iHECIQD6RP6yNyJCSwgf0RieBhda4dYbPCwNRoMtUCloSMGpbQ%3D%3D/playlist/index.m3u8/sq/1162973/goap/clen%3D80724%3Blmt%3D1672418794552377/govp/clen%3D868333%3Blmt%3D1672418794552375/dur/4.933/file/seg.ts' for reading
[https @ 0000015d3add4640] Opening 'https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1672440654/ei/7havY7b7M5qIhgbD4ZZg/ip/73.12.30.172/id/FjEmM_a4nwE.2/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-p5qddn7k.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/zIddbL3FM_zYhWZUxe4uMK_OAUZMmng/vprv/1/playlist_type/DVR/initcwndbps/1895000/mh/Lj/mm/44/mn/sn-p5qddn7k/ms/lva/mv/m/mvi/5/pl/17/dover/11/pacing/0/keepalive/yes/fexp/24001373,24007246/mt/1672418913/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAIidh9gV1k5721GAgB4g4fySiKBQUmQuszgOK7c3pIz1AiBkksFTlppc310pS4O9DRTGHbcRGrDgCIAbLB0i_RdP-A%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgY2rqqEA9CrvBsiDw5R1y7A49k4jJ22UwVPrTLVx1iHECIQD6RP6yNyJCSwgf0RieBhda4dYbPCwNRoMtUCloSMGpbQ%3D%3D/playlist/index.m3u8' for reading
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-VERSION:3')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:20490')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-12-30T16:50:25.317+00:00')
[https @ 0000015d3add4640] Opening 'https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1672440654/ei/7havY7b7M5qIhgbD4ZZg/ip/73.12.30.172/id/FjEmM_a4nwE.2/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-p5qddn7k.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/zIddbL3FM_zYhWZUxe4uMK_OAUZMmng/vprv/1/playlist_type/DVR/initcwndbps/1895000/mh/Lj/mm/44/mn/sn-p5qddn7k/ms/lva/mv/m/mvi/5/pl/17/dover/11/pacing/0/keepalive/yes/fexp/24001373,24007246/mt/1672418913/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAIidh9gV1k5721GAgB4g4fySiKBQUmQuszgOK7c3pIz1AiBkksFTlppc310pS4O9DRTGHbcRGrDgCIAbLB0i_RdP-A%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgY2rqqEA9CrvBsiDw5R1y7A49k4jJ22UwVPrTLVx1iHECIQD6RP6yNyJCSwgf0RieBhda4dYbPCwNRoMtUCloSMGpbQ%3D%3D/playlist/index.m3u8' for reading
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-VERSION:3')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:20490')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-12-30T16:50:25.317+00:00')
[https @ 0000015d3add4640] Opening 'https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1672440654/ei/7havY7b7M5qIhgbD4ZZg/ip/73.12.30.172/id/FjEmM_a4nwE.2/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-p5qddn7k.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/zIddbL3FM_zYhWZUxe4uMK_OAUZMmng/vprv/1/playlist_type/DVR/initcwndbps/1895000/mh/Lj/mm/44/mn/sn-p5qddn7k/ms/lva/mv/m/mvi/5/pl/17/dover/11/pacing/0/keepalive/yes/fexp/24001373,24007246/mt/1672418913/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAIidh9gV1k5721GAgB4g4fySiKBQUmQuszgOK7c3pIz1AiBkksFTlppc310pS4O9DRTGHbcRGrDgCIAbLB0i_RdP-A%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgY2rqqEA9CrvBsiDw5R1y7A49k4jJ22UwVPrTLVx1iHECIQD6RP6yNyJCSwgf0RieBhda4dYbPCwNRoMtUCloSMGpbQ%3D%3D/playlist/index.m3u8' for reading
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-VERSION:3')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:20490')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-12-30T16:50:30.251+00:00')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-DISCONTINUITY')
[hls @ 0000015d39fc5f00] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-12-30T16:51:14.951+00:00')
[https @ 0000015d3a531600] Opening 'https://rr5---sn-p5qddn7k.googlevideo.com/videoplayback/id/FjEmM_a4nwE.2/itag/96/source/yt_live_broadcast/expire/1672440654/ei/7havY7b7M5qIhgbD4ZZg/ip/73.12.30.172/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr5---sn-p5qddn7k.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/zIddbL3FM_zYhWZUxe4uMK_OAUZMmng/vprv/1/playlist_type/DVR/initcwndbps/1895000/mh/Lj/mm/44/mn/sn-p5qddn7k/ms/lva/mv/m/mvi/5/pl/17/keepalive/yes/fexp/24001373,24007246/mt/1672418913/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAIidh9gV1k5721GAgB4g4fySiKBQUmQuszgOK7c3pIz1AiBkksFTlppc310pS4O9DRTGHbcRGrDgCIAbLB0i_RdP-A%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgY2rqqEA9CrvBsiDw5R1y7A49k4jJ22UwVPrTLVx1iHECIQD6RP6yNyJCSwgf0RieBhda4dYbPCwNRoMtUCloSMGpbQ%3D%3D/playlist/index.m3u8/sq/1162974/goap/clen%3D83351%3Blmt%3D1672419081068177/govp/clen%3D1752151%3Blmt%3D1672419081068175/dur/5.067/file/seg.ts' for reading
av_interleaved_write_frame(): Invalid argumente=00:00:20.34 bitrate=2782.8kbits/s speed=0.748x
Error muxing a packet for output file #0
Error writing trailer of file:downloads\Pennekamp Coral Cam 2022-12-30 11_50.mp4.part: Invalid argument
frame=  607 fps= 17 q=-1.0 Lsize=    6912kB time=00:00:20.44 bitrate=2770.2kbits/s speed=0.585x
video:6545kB audio:322kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.644545%
Conversion failed!


ERROR: ffmpeg exited with code 4294967274
Traceback (most recent call last):
  File "F:\home\ag\Documents\oceanlense\daemon.py", line 13, in <module>
    p = Process(target=youtube.getLast("https://youtu.be/FjEmM_a4nwE"))
  File "F:\home\ag\Documents\oceanlense\capturing\youtube.py", line 10, in getLast
    ydl.download([url])
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3322, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3297, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1474, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1582, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1641, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 2737, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3200, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 2924, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\downloader\common.py", line 446, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\downloader\external.py", line 73, in real_download
    self.report_error('%s exited with code %d' % (
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1004, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 944, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: ffmpeg exited with code 4294967274
```

**Comment by pukkandan** [comment]
Sending ctrl+C should stop it. Can you show the code of how you are sending it?

**Comment by agieocean** [comment]
Ah yeah my apologies I should have included that code in the initial issue.

Here's the first code I tried:
daemon.py
```
import subprocess, signal, time, os
from multiprocessing import Process
from threading import Timer

from capturing import youtube

subproc = subprocess.run(["python", "run.py"])
time.sleep(10)
os.kill(subproc.pid, signal.CTRL_C_EVENT)
```
run.py
```
from capturing import youtube

youtube.getLast("https://youtu.be/FjEmM_a4nwE")
```
youtube.py
```
from yt_dlp import YoutubeDL
import signal

def getLast(url):
    ydl_opts = {
        'outtmpl': 'downloads/%(title)s.%(ext)s',
        'format': 'bestvideo/best'
    }
    ydl = YoutubeDL(ydl_opts)
    ydl.download([url])
```

Here's the second thing I tried:
```
import subprocess, signal, time, os
from multiprocessing import Process
from threading import Timer
from capturing import youtube

p = Process(target=youtube.getLast("https://youtu.be/FjEmM_a4nwE"))
p.start()
timeToWait = 5
Timer(timeToWait, p.terminate) 
```
In addition if it's relevant I'm on Windows 10

**Comment by pukkandan** [comment]
`subprocess.run` doesn't return till the process ends - so `os.kill` is never called. Use `subprocess.Popen` instead

For the second try, you are terminating the process outright instead of sending `^C`. You can `lambda: os.kill(p.pid, CTRL_C_EVENT)` like before

**Comment by agieocean** [comment]
Perfect, thank you so much!
