### ISSUE TITLE
WebVTT ParseError (extra new line)

### ISSUE THREAD

**Issue by SamDecrock** [yt-dlp/yt-dlp#591]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.07.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

Posting the error message here as I know the solution too

```
Traceback (most recent call last):
  File "/var/yt-dlp/yt_dlp/YoutubeDL.py", line 1177, in wrapper
    return func(self, *args, **kwargs)
  File "/var/yt-dlp/yt_dlp/YoutubeDL.py", line 1215, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/var/yt-dlp/yt_dlp/YoutubeDL.py", line 1311, in process_ie_result
    return self.process_ie_result(
  File "/var/yt-dlp/yt_dlp/YoutubeDL.py", line 1259, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/var/yt-dlp/yt_dlp/YoutubeDL.py", line 2277, in process_video_result
    self.process_info(new_info)
  File "/var/yt-dlp/yt_dlp/YoutubeDL.py", line 2531, in process_info
    self.dl(sub_filename, sub_info.copy(), subtitle=True)
  File "/var/yt-dlp/yt_dlp/YoutubeDL.py", line 2414, in dl
    return fd.download(name, new_info, subtitle)
  File "/var/yt-dlp/yt_dlp/downloader/common.py", line 386, in download
    return self.real_download(filename, info_dict), True
  File "/var/yt-dlp/yt_dlp/downloader/hls.py", line 324, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict, pack_fragment)
  File "/var/yt-dlp/yt_dlp/downloader/fragment.py", line 421, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, frag_content), frag_index, ctx)
  File "/var/yt-dlp/yt_dlp/downloader/fragment.py", line 399, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "/var/yt-dlp/yt_dlp/downloader/hls.py", line 259, in pack_fragment
    for block in webvtt.parse_fragment(frag_content):
  File "/var/yt-dlp/yt_dlp/webvtt.py", line 394, in parse_fragment
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 336 (near 'yyy')

```

## Description

The WebVTT looks a bit weird (I redacted the original text to make it more readable): 
```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000

00:00:03.050 --> 00:00:04.050
.

00:00:12.370 --> 00:00:14.970
something

00:00:15.050 --> 00:00:17.130
something

00:00:23.650 --> 00:00:25.810
something

00:00:25.890 --> 00:00:30.330
xxx

yyy

00:00:30.650 --> 00:00:32.210
something

00:00:32.290 --> 00:00:34.970
something
something on the second line
```

So what happens is that when it sees this empty line between `xxx` and `yyy` it stops reading the payload and assumes the next block will appear, which doesn't happen so it spits out a `ParseError`

I have a PR ready but I'm not sure it's the best fix. Basically it will check for a newline followed by a timestamp before giving up. @fstirlitz Please have a look.

**Comment by fstirlitz** [comment]
This is going to consider any `NOTE` blocks found between cue blocks to be part of the text of the previous cue.

Either way, this is in violation of the [WebVTT spec](https://www.w3.org/TR/webvtt/), which defines a number of syntaxes for cue texts, but all of them forbid empty lines. Not that these are unheard of: see #339.

How does it display in the web player? Which browser do you use?

**Comment by fstirlitz** [comment]
Also, it would help if you didn’t redact the URL which triggers this problem. Finding a workaround becomes harder without the ability to reproduce.

**Comment by pukkandan** [comment]
@SamDecrock Like @fstirlitz said, please give a URL so that we can reproduce the issue and so that we can check how the web-player is displaying it

> But I am not in favour of working around other people’s bugs in a way which breaks compliant implementations.

Our objective is not to create a spec-compliant parser, but to make one that works with manifests found in the wild. I am of the opinion that we should try to handle cases like this as long as it doesn't break anything else
