### ISSUE TITLE
[MediaStream] Support for canal1.com.co

### ISSUE THREAD

**Issue by denaunistic** [yt-dlp/yt-dlp#5929]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Colombia

### Example URLs

- Single video: https://canal1.com.co/videos/experta-revela-tendencias-maquillaje-2023/
- Livestream: https://canal1.com.co/senal-en-vivo

### Provide a description that is worded well enough to be understood

This place uses the Mediastream service but it can't be extracted by the Mediastream extractor in yt-dlp

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://canal1.com.co/videos/experta-revela-tendencias-maquillaje-2023/']
[debug] User config: []
[debug] System config: []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.02 [d83b0ad] (win32_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-08-13-git-c469c3c3b1-full_build-www.gyan.dev (setts), ffprobe 2022-08-13-git-c469c3c3b1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1754 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.02, Current version: 2023.01.02
yt-dlp is up to date (2023.01.02)
[generic] Extracting URL: https://canal1.com.co/videos/experta-revela-tendencias-maquillaje-2023/
[generic] experta-revela-tendencias-maquillaje-2023: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] experta-revela-tendencias-maquillaje-2023: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://canal1.com.co/videos/experta-revela-tendencias-maquillaje-2023/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1497, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1573, in __extract_info
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\generic.py", line 2523, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://canal1.com.co/videos/experta-revela-tendencias-maquillaje-2023/
```

**Comment by HobbyistDev** [comment]
For single video link that OP give, i'm not sure it's from mediastream or not but it seems have youtube embed at one of json+ld(s) :
```html
<script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "VideoObject",
        "name": "Experta reveló las tendencias de maquillaje para el 2023",
        "description": "#LoSéTodo Consultamos con una experta cuáles son las tendencias en maquillaje para el 2023.",
        "thumbnailUrl": ["https://images.canal1.com.co/wp-content/uploads/2022/12/27162438/Experta-revela-las-tendencias-de-maquillaje-para-el-2023.jpg"],
        "uploadDate": "2022-12-30T15:00:58-05:00",
        "publisher": {
          "@type": "Organization",
          "name": "Canal 1",
          "logo": {
            "@type": "ImageObject",
            "url": "https://images.canal1.com.co/site/images/logo-canal-1-amp.png"
          }
        },
        "duration": "PT44S",
        "embedUrl": "https://www.youtube.com/embed/yp637mamSvk"
      }
    </script>
```
and the youtube id can also be found at this tag
```html
<amp-video-iframe width="16" height="9" layout="responsive" data-param-videoid="youtube:yp637mamSvk" poster="https://images.canal1.com.co/wp-content/uploads/2022/12/27162438/Experta-revela-las-tendencias-de-maquillaje-para-el-2023.jpg" src="/player-mdstrm.html" dock="true" class="jsx-3485846343 i-amphtml-layout-responsive i-amphtml-layout-size-defined" i-amphtml-layout="responsive">
                    <i-amphtml-sizer style="display:block;padding-top:56.25%"></i-amphtml-sizer>
                  </amp-video-iframe>
```

I can't test the live url as they use geo-fence:
> You are not allowed to watch this video: Geo Fencing Restriction

**Comment by denaunistic** [comment]
![image](https://user-images.githubusercontent.com/88289863/210402912-1f4e3e3a-7044-4b8b-a8e8-95cef6152d8e.png)
The Page appears as a client of the mediastream service

![image](https://user-images.githubusercontent.com/88289863/210403175-a5fc5c6d-69d9-4a07-a5bf-56faf09752e6.png)
![image](https://user-images.githubusercontent.com/88289863/210403362-8efe3b55-a7d8-41f2-bcd8-8245fe71fca6.png)
besides from that, the embed looks exactly the same as a normal supported mediastream video

**Comment by bashonly** [comment]
the first example URL does fetch some mediastream API data but it loads the same youtube video that's embedded in the JSON LD

@ denaunistic what is that last screenshot you posted? an example of a normal supported mediastream video? or is it another video from `canal1.com.co`? if it's unsupported, post the URL

**Comment by denaunistic** [comment]
> what is that last screenshot you posted? an example of a normal supported mediastream video? or is it another video from canal1.com.co? if it's unsupported, post the URL

yes it is a example of a normal mediastream supported video

**Comment by dirkf** [comment]
Should the ld+json extraction return the `embedUrl` from a `VideoObject` if there is no `contentUrl` and the value differs from the `url`, where present?

To simplify extractor logic, perhaps just return it as the `_embed_url` item of the info dict, which should be stripped in core logic if not popped before?

With such a change, and making the generic extractor use `_embed_url` if no `url` was found, the generic extractor handles the single video ("make-up trends 2023") example.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/4141 was the reason we reverted embedUrl

> With such a change, and making the generic extractor use `_embed_url` if no `url` was found

This will trigger the same issue

**Comment by Grub4K** [comment]
> To simplify extractor logic, perhaps just return it as the `_embed_url` item of the info dict, which should be stripped in core logic if not popped before?

This would also be relevant for sites like RheinMainTV (#5840) which use `embedUrl` instead of `contentUrl`. To simplify the use of the function a parameter `use_embed_url` could perhaps be provided? Or the `_embed_url` could be returned but stay unused unless used in a specific extractor?

**Comment by pukkandan** [comment]
> To simplify the use of the function a parameter `use_embed_url` could perhaps be provided?

imo, this is better than returning `_embed_url`. Otherwise looks good

**Comment by dirkf** [comment]
Doesn't that mean running the ld+json extraction twice? Don't tell Greta.

However my recollection that `_...` keys are stripped from the info dict result seems to be wrong for both yt-dlp and yt-dl: only certain keys (eg, for XFF) are removed. If that isn't happening, or isn't added,
```py
        for k in info_dict.keys():
            if k.startswith('_'):
                del info_dict[k]
```
then the parameter would be a cleaner solution. If it controlled whether `_embed_url` was returned, double extraction could be avoided, with a little clean-up code to pop the `_embed_url`, or otherwise just use it on the second attempt.

**Comment by pukkandan** [comment]
> However my recollection that `_...` keys are stripped from the info dict result seems to be wrong for both yt-dlp and yt-dl: only certain keys (eg, for XFF) are removed. If that isn't happening, or isn't added,

yt-dlp removes keys with `__`, but not `_`. ytdl only removes some specific keys

**Comment by dirkf** [comment]
Aha, `sanitize_info(..., True)`. That doesn't work at all how I imagined, so even a `__embed_url` would need work.
