### ISSUE TITLE
Progress hooks + writesubtitles options break download when embedded in python

### ISSUE THREAD

**Issue by bpasta** [yt-dlp/yt-dlp#5957]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Using a progress hook in conjunction with the "writesubtitles" option in python can cause the download to break under many circumstances. This results in only part of the subtitle file being downloaded, and nothing else.

It seems to break anytime my progress hook tries to do any sort of slightly intense calculation. For example, simply trying to get the progress percent causes the download to give up.

Here are the relevant functions:
```
def dl_progress_hook(d):
    global dl_progress
    if d["status"] == "downloading" and d["total_bytes"] > 0:
        dl_progress = int(d["downloaded_bytes"] / d["total_bytes"] * 100)


async def download(urls, dst):
    ffmpeg_path = utils.filepath("./ffmpeg/ffmpeg")
    ydl_opts = {
        "format": "137+ba[ext=m4a]/137+ba/bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b",
        "writesubtitles": True,
        "subtitleslangs": ["all", "-live_chat"],
        "final_ext": "mp4",
        "paths": {"home": dst},
        "progress_hooks": [dl_progress_hook],
        "ffmpeg_location": ffmpeg_path,
        "verbose": True,
        "postprocessors": [
            {
                "key": "FFmpegEmbedSubtitle",
                "already_have_subtitle": False,
            }
        ],
    }
        
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        error_code = ydl.download(urls)
```

This hook works perfectly fine for other types of downloads like extracting audio (I have altered the code not to include everything here), but does not want to work when trying to write subtitles. I have also noticed that simply trying to get "d['fragment_index']" has the same effect. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.02 [d83b0ad] (pip) API
[debug] params: {'format': '137+ba[ext=m4a]/137+ba/bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b', 'writesubtitles': True, 'subtitleslangs': ['all', '-live_chat'], 'final_ext': 'mp4', 'paths': {'home': '/Users/rplassmann/Desktop/youtube mp3s/gui test'}, 'progress_hooks': [<function dl_progress_hook at 0x1162b1a20>], 'ffmpeg_location': '/Users/rplassmann/vscodeprojects/youtube downloader/ffmpeg/ffmpeg', 'verbose': True, 'postprocessors': [{'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': False}], 'compat_opts': set()}
[debug] Python 3.10.2 (CPython x86_64 64bit) - macOS-13.0.1-x86_64-i386-64bit (OpenSSL 1.1.1m  14 Dec 2021)
[debug] exe versions: ffmpeg N-107213-gfed07efcde-tessus (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1754 extractors
[youtube] Extracting URL: FhHM9MT41IE
[youtube] FhHM9MT41IE: Downloading webpage
[youtube] FhHM9MT41IE: Downloading android player API JSON
[info] FhHM9MT41IE: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] FhHM9MT41IE: Downloading 1 format(s): 137+140
[info] Writing video subtitles to: /Users/rplassmann/Desktop/youtube mp3s/gui test/The ＂architecture graveyard＂ is alive and well [FhHM9MT41IE].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=FhHM9MT41IE&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1672900543&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=CEFA08F69C276F0E79BF356812174D78FEC96434.42AA418880F4C302592FEE9DA43105EC16010F89&key=yt8&lang=en&fmt=vtt"
[download] Destination: /Users/rplassmann/Desktop/youtube mp3s/gui test/The ＂architecture graveyard＂ is alive and well [FhHM9MT41IE].en.vtt
[download]    1.00KiB at  Unknown B/s (00:00:00)
```

**Comment by bpasta** [comment]
It seemed to be an issue with python 3.10. Does not happen in 3.11

**Comment by bpasta** [comment]
Nevermind, still broken. Not sure why it worked once though.

**Comment by Grub4K** [comment]
Possibly bc `dl_progress_hook` can `raise`? See if the same still hapoens if you write a safe method. The thing that comes to mind is a `KeyError` and `DivisionByZeroError` and possibly a `TypeError` from total bytes being `None`

**Comment by pukkandan** [comment]
The output should have included the traceback. Did you not get it?
```
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.02 [d83b0ad80] API
[debug] params: {'format': '137+ba[ext=m4a]/137+ba/bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b', 'writesubtitles': True, 'subtitleslangs': ['all', '-live_chat'], 'final_ext': 'mp4', 'progress_hooks': [<function dl_progress_hook at 0x000001AB247E0540>], 'verbose': True, 'postprocessors': [{'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': False}], 'compat_opts': set()}
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg n5.1.2-8-g5746987bad-20221204 (fdk,setts), ffprobe N-109332-g45ab5307a6-20221201, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1754 extractors
[TestURL] Extracting URL: test:youtube
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[info] BaW_jenozKc: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] BaW_jenozKc: Downloading 1 format(s): 137+140
[info] Writing video subtitles to: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=BaW_jenozKc&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1672911919&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=21C76C2339E226D8C0A23F565DDF51DE7C40B28B.D49625CD6CD7B3708D8A9C950D41FCAEEA3C5585&key=yt8&lang=en&fmt=vtt"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].en.vtt
[download]    177.00B at   12.72KiB/s (00:00:00)Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt-dlp\subtest.py", line 25, in <module>
    print(ydl.download('test:youtube'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 3353, in download
    self.__download_wrapper(self.extract_info)(
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 3328, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1486, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1497, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1594, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1673, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1486, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1497, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1594, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1653, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 2767, in process_video_result
    self.process_info(new_info)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 3021, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 4003, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 2954, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\downloader\common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\downloader\http.py", line 372, in real_download
    return download()
           ^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\downloader\http.py", line 309, in download
    self._hook_progress({
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\downloader\common.py", line 459, in _hook_progress
    ph(status)
  File "D:\Programs\Source\yt-dlp\yt-dlp\subtest.py", line 5, in dl_progress_hook
    if d["status"] == "downloading" and d["total_bytes"] > 0:
                                        ^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
