### ISSUE TITLE
Shorts won't download with "-f "bv*[height=144]+ba""?

### ISSUE THREAD

**Issue by Kavolc** [yt-dlp/yt-dlp#5959]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When I try to download shorts with (-f "bv*[height=144]+ba") I got the following error:

ERROR: Postprocessing: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov

But using (-S res:144) works fine. 
Full settings:
yt-dlp  --add-metadata --embed-thumbnail   -f "bv*[height=144]+ba" -o "%(uploader)s/%(title)s.%(ext)s" --merge-output-format mp4

Im trying to download a big playlist and I wanted to add the 'best audio' option too.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--add-metadata', '--embed-thumbnail', '-f', 'bv*[height=144]+ba', '-o', '%(uploader)s/%(title)s.%(ext)s', '--merge-output-format', 'mp4', 'https://youtu.be/-J3gfK0jMfQ']
[debug] User config: []
[debug] System config: []
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.02 [d83b0ad] (pip)
[debug] Python 3.11.0 (CPython aarch64 64bit) - Linux-4.19.152-perf-21186317-abA526U1UES2AUD5-aarch64-with-libc (OpenSSL 3.0.7 1 Nov 2022, libc)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1754 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.02, Current version: 2023.01.02
yt-dlp is up to date (2023.01.02)
[youtube] Extracting URL: https://youtu.be/-J3gfK0jMfQ
[youtube] -J3gfK0jMfQ: Downloading webpage
[youtube] -J3gfK0jMfQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] -J3gfK0jMfQ: Downloading 1 format(s): 17
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: TeamSamuraiX1/When a kid shows up to locals…#yugioh.webp
[debug] Invoking http downloader on "https://rr4---sn-5ualdns7.googlevideo.com/videoplayback?expire=1672903944&ei=qCi2Y823A5ivkwbbqYKIBQ&ip=2600%3A387%3Ac%3A6c10%3A%3A4&id=o-ANNW6oPLlN0O4c0t32XcuwJ489RviHiummEAeh-6UvIE&itag=17&source=youtube&requiressl=yes&mh=fu&mm=31%2C29&mn=sn-5ualdns7%2Csn-5uaeznls&ms=au%2Crdu&mv=m&mvi=4&pl=51&ctier=SH&initcwndbps=845000&spc=zIddbBoIFdEpnVSbEAdLLtZbM_m85HU&vprv=1&svpuc=1&mime=video%2F3gpp&gir=yes&clen=591333&dur=59.675&lmt=1671644206916296&mt=1672882159&fvip=1&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgEpMwdrNQ2dZskfPCXgjqsJn5r6jvgdmAOkG_hR-6AVACIHoicrjcjp96Jkfk6sNr3RFd4kPpZAiOvQBkMAx1-f2h&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZU9cDwNhm7gKQotg2LTB7rOErm05pq7njLot3q6RCrwCIGoiHgfsql6HPpEWEVTlmKNsr4t3YmXwvustAW8wTfXI"
[download] Destination: TeamSamuraiX1/When a kid shows up to locals…#yugioh.3gp
[download]   0.2% of  577.47KiB at    1.55Ki[download]   0.4% of  577.47KiB at    3.93Ki[download]   1.0% of  577.47KiB at    8.65Ki[download]   2.1% of  577.47KiB at   18.08Ki[download]   4.2% of  577.47KiB at   17.29Ki[download]   7.1% of  577.47KiB at   18.46Ki[download]  10.6% of  577.47KiB at   20.41Ki[download]  15.1% of  577.47KiB at   18.90Ki[download]  17.9% of  577.47KiB at   18.73Ki[download]  21.0% of  577.47KiB at   19.17Ki[download]  24.8% of  577.47KiB at   20.13Ki[download]  29.6% of  577.47KiB at   19.38Ki[download]  32.4% of  577.47KiB at   19.45Ki[download]  35.9% of  577.47KiB at   19.71Ki[download]  39.8% of  577.47KiB at   18.95Ki[download]  42.2% of  577.47KiB at   18.86Ki[download]  45.3% of  577.47KiB at   18.89Ki[download]  48.6% of  577.47KiB at   19.17Ki[download]  52.8% of  577.47KiB at   18.65Ki[download]  55.2% of  577.47KiB at   19.51Ki[download]  60.2% of  577.47KiB at   19.36Ki[download]  63.2% of  577.47KiB at   19.48Ki[download]  67.1% of  577.47KiB at   18.94Ki[download]  69.3% of  577.47KiB at   18.84Ki[download]  72.1% of  577.47KiB at   18.89Ki[download]  75.6% of  577.47KiB at   19.11Ki[download]  80.0% of  577.47KiB at   19.44Ki[download]  84.8% of  577.47KiB at   19.31Ki[download]  87.8% of  577.47KiB at   19.31Ki[download]  91.1% of  577.47KiB at   19.44Ki[download]  95.3% of  577.47KiB at   19.18Ki[download]  97.8% of  577.47KiB at   19.10Ki[download] 100.0% of  577.47KiB at   19.52Ki[download] 100% of  577.47KiB in 00:00:30 at 19.16KiB/s
[Metadata] Adding metadata to "TeamSamuraiX1/When a kid shows up to locals…#yugioh.3gp"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:TeamSamuraiX1/When a kid shows up to locals…#yugioh.3gp' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=When a kid shows up to locals…#yugioh' -metadata date=20221221 -metadata 'purl=https://www.youtube.com/watch?v=-J3gfK0jMfQ' -metadata 'comment=https://www.youtube.com/watch?v=-J3gfK0jMfQ' -metadata artist=TeamSamuraiX1 -movflags +faststart 'file:TeamSamuraiX1/When a kid shows up to locals…#yugioh.temp.3gp'
[ThumbnailsConvertor] Converting thumbnail "TeamSamuraiX1/When a kid shows up to locals…#yugioh.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:TeamSamuraiX1/When a kid shows up to locals…#yugioh.webp' -update 1 -movflags +faststart 'file:TeamSamuraiX1/When a kid shows up to locals…#yugioh.png'
ERROR: Postprocessing: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3307, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3486, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3468, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3446, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)                            ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/embedthumbnail.py", line 216, in run
    raise EmbedThumbnailPPError('Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov')
yt_dlp.postprocessor.embedthumbnail.EmbedThumbnailPPError: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov
```

**Comment by bashonly** [comment]
using `-f "bv*[height=144]+ba"` will select this format:
```
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
17  3gp   176x144      8  1 │  577.47KiB  79k https │ mp4v.20.3      79k mp4a.40.2    0k 22k 144p
```
whereas using `-S res:144` will select these two formats to be merged:
```
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
278 webm  144x256     30    │  627.79KiB  86k https │ vp9            86k video only          144p, webm_dash
251 webm  audio only      2 │  956.85KiB 132k https │ audio only         opus       132k 48k medium, webm_dash
```

The problem with the first format is that it is `3gp` and contains both video and audio, so it will not be merged into `mp4`

And that is why you get this error message:
> EmbedThumbnailPPError: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov

What you can do:
 - add `--remux-video mp4` to your command, or
 - avoid the `3gp` format (by using `-S "res:144"`), or
 - don't embed thumbnails

**Comment by Kavolc** [comment]
@bashonly  --remux-video mp4 didn't solve the problem.
@pukkandan -Using width results in problems with normal videos.

A was looking for a setting to have a 720 resolution for both while getting the best audio too.

**Comment by pukkandan** [comment]
why can't you use -S? While what you want can be done with -f, -S was created exactly to simplify uses like this

**Comment by Kavolc** [comment]
I saw in another post that -S sometimes doesn't pick the best audio. I sincerely don't know if that is true or makes a difference at all. But I guess using -S is the solution im looking for.
