### ISSUE TITLE
Add option to use cookies.txt file without overwriting

### ISSUE THREAD

**Issue by climbTheStairs** [yt-dlp/yt-dlp#5977]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The only way to pass cookies from a `cookies.txt` file to a request is to use the `--cookies` flag;
however, `--cookies` not only reads from the file but also writes new cookies to it:

```
--cookies FILE                  Netscape formatted file to read cookies from
                                and dump cookie jar in
```

[This is expected behavior](https://github.com/ytdl-org/youtube-dl/issues/16505), but it can often get in the way,
such as when the same `cookies.txt` file is needs to reused multiple times.

It does not currently seem possible to achieve this, save by making `cookies.txt` read-only,
but that obviously isn't a good workaround and leads to a ton of other issues,
such as `yt-dlp` throwing an exception and exiting.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Standard output:

Latest version: 2023.01.02, Current version: 2023.01.02
yt-dlp is up to date (2023.01.02)
[youtube] Extracting URL: dQw4w9WgXcQ
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading android player API JSON
[info] dQw4w9WgXcQ: Downloading 1 format(s): 248+251
[download] Destination: Rick Astley - Never Gonna Give You Up (Official Music Video) [dQw4w9WgXcQ].f248.webm

[download]   0.0% of   53.59MiB at  Unknown B/s ETA Unknown
[download]   0.0% of   53.59MiB at  Unknown B/s ETA 00:18  
[download]   0.0% of   53.59MiB at    5.03MiB/s ETA 00:10
[download]   0.0% of   53.59MiB at    8.35MiB/s ETA 00:06
[download]   0.1% of   53.59MiB at   12.02MiB/s ETA 00:04
[download]   0.1% of   53.59MiB at   14.63MiB/s ETA 00:03
[download]   0.2% of   53.59MiB at   20.58MiB/s ETA 00:02
[download]   0.5% of   53.59MiB at   26.89MiB/s ETA 00:01
[download]   0.9% of   53.59MiB at   32.59MiB/s ETA 00:01
[download]   1.9% of   53.59MiB at   36.31MiB/s ETA 00:01
[download]   3.7% of   53.59MiB at   25.85MiB/s ETA 00:01
[download]   7.5% of   53.59MiB at   22.82MiB/s ETA 00:02
[download]  14.9% of   53.59MiB at   21.49MiB/s ETA 00:02
[download]  18.4% of   53.59MiB at   21.50MiB/s ETA 00:02
[download]  18.4% of   53.59MiB at  Unknown B/s ETA Unknown
[download]  18.4% of   53.59MiB at  Unknown B/s ETA Unknown
[download]  18.4% of   53.59MiB at    5.98MiB/s ETA 00:07  
[download]  18.4% of   53.59MiB at    9.48MiB/s ETA 00:04
[download]  18.4% of   53.59MiB at   13.15MiB/s ETA 00:03
[download]  18.5% of   53.59MiB at   18.00MiB/s ETA 00:02
[download]  18.6% of   53.59MiB at   23.61MiB/s ETA 00:01
[download]  18.8% of   53.59MiB at   29.19MiB/s ETA 00:01
[download]  19.3% of   53.59MiB at   34.22MiB/s ETA 00:01
[download]  20.2% of   53.59MiB at   35.16MiB/s ETA 00:01
[download]  22.1% of   53.59MiB at   25.71MiB/s ETA 00:01
[download]  25.8% of   53.59MiB at   22.72MiB/s ETA 00:01
[download]  33.3% of   53.59MiB at   21.45MiB/s ETA 00:01
[download]  36.9% of   53.59MiB at   21.48MiB/s ETA 00:01
[download]  36.9% of   53.59MiB at  Unknown B/s ETA Unknown
[download]  36.9% of   53.59MiB at  Unknown B/s ETA Unknown
[download]  36.9% of   53.59MiB at    5.27MiB/s ETA 00:06  
[download]  36.9% of   53.59MiB at    8.63MiB/s ETA 00:03
[download]  37.0% of   53.59MiB at   12.35MiB/s ETA 00:02
[download]  37.0% of   53.59MiB at   17.23MiB/s ETA 00:01
[download]  37.1% of   53.59MiB at   22.91MiB/s ETA 00:01
[download]  37.4% of   53.59MiB at   28.10MiB/s ETA 00:01
[download]  37.8% of   53.59MiB at   33.51MiB/s ETA 00:00
[download]  38.8% of   53.59MiB at   26.15MiB/s ETA 00:01
[download]  40.6% of   53.59MiB at   25.33MiB/s ETA 00:01
[download]  44.4% of   53.59MiB at   22.56MiB/s ETA 00:01
[download]  51.8% of   53.59MiB at   21.39MiB/s ETA 00:01
[download]  54.7% of   53.59MiB at   21.47MiB/s ETA 00:01
[download]  54.7% of   53.59MiB at  Unknown B/s ETA Unknown
[download]  54.7% of   53.59MiB at  Unknown B/s ETA Unknown
[download]  54.7% of   53.59MiB at    5.89MiB/s ETA 00:04  
[download]  54.7% of   53.59MiB at    9.37MiB/s ETA 00:02
[download]  54.8% of   53.59MiB at   13.03MiB/s ETA 00:01
[download]  54.8% of   53.59MiB at   17.12MiB/s ETA 00:01
[download]  54.9% of   53.59MiB at   22.81MiB/s ETA 00:01
[download]  55.2% of   53.59MiB at   28.62MiB/s ETA 00:00
[download]  55.6% of   53.59MiB at   33.92MiB/s ETA 00:00
[download]  56.6% of   53.59MiB at   35.11MiB/s ETA 00:00
[download]  58.4% of   53.59MiB at   25.91MiB/s ETA 00:00
[download]  62.2% of   53.59MiB at   22.73MiB/s ETA 00:00
[download]  69.6% of   53.59MiB at   21.45MiB/s ETA 00:00
[download]  73.0% of   53.59MiB at   21.48MiB/s ETA 00:00
[download]  73.0% of   53.59MiB at  Unknown B/s ETA Unknown
[download]  73.0% of   53.59MiB at  Unknown B/s ETA Unknown
[download]  73.0% of   53.59MiB at    5.98MiB/s ETA 00:02  
[download]  73.1% of   53.59MiB at    9.43MiB/s ETA 00:01
[download]  73.1% of   53.59MiB at   13.10MiB/s ETA 00:01
[download]  73.1% of   53.59MiB at   16.15MiB/s ETA 00:00
[download]  73.3% of   53.59MiB at   21.96MiB/s ETA 00:00
[download]  73.5% of   53.59MiB at   27.87MiB/s ETA 00:00
[download]  74.0% of   53.59MiB at   33.31MiB/s ETA 00:00
[download]  74.9% of   53.59MiB at   35.78MiB/s ETA 00:00
[download]  76.8% of   53.59MiB at   23.15MiB/s ETA 00:00
[download]  80.5% of   53.59MiB at   22.80MiB/s ETA 00:00
[download]  88.0% of   53.59MiB at   21.49MiB/s ETA 00:00
[download]  91.4% of   53.59MiB at   21.51MiB/s ETA 00:00
[download]  91.5% of   53.59MiB at  Unknown B/s ETA Unknown
[download]  91.5% of   53.59MiB at  Unknown B/s ETA Unknown
[download]  91.5% of   53.59MiB at    6.07MiB/s ETA 00:00  
[download]  91.5% of   53.59MiB at    9.59MiB/s ETA 00:00
[download]  91.5% of   53.59MiB at   12.31MiB/s ETA 00:00
[download]  91.6% of   53.59MiB at   13.51MiB/s ETA 00:00
[download]  91.7% of   53.59MiB at   19.36MiB/s ETA 00:00
[download]  91.9% of   53.59MiB at   25.73MiB/s ETA 00:00
[download]  92.4% of   53.59MiB at   31.76MiB/s ETA 00:00
[download]  93.3% of   53.59MiB at   20.33MiB/s ETA 00:00
[download]  95.2% of   53.59MiB at   25.21MiB/s ETA 00:00
[download]  98.9% of   53.59MiB at   22.74MiB/s ETA 00:00
[download] 100.0% of   53.59MiB at   22.70MiB/s ETA 00:00
[download] 100% of   53.59MiB in 00:00:02 at 18.75MiB/s  
[download] Destination: Rick Astley - Never Gonna Give You Up (Official Music Video) [dQw4w9WgXcQ].f251.weba

[download]   0.0% of    3.28MiB at  Unknown B/s ETA Unknown
[download]   0.1% of    3.28MiB at  Unknown B/s ETA Unknown
[download]   0.2% of    3.28MiB at    5.18MiB/s ETA 00:00  
[download]   0.4% of    3.28MiB at    8.53MiB/s ETA 00:00
[download]   0.9% of    3.28MiB at   12.18MiB/s ETA 00:00
[download]   1.9% of    3.28MiB at   13.76MiB/s ETA 00:00
[download]   3.8% of    3.28MiB at   19.57MiB/s ETA 00:00
[download]   7.6% of    3.28MiB at   25.77MiB/s ETA 00:00
[download]  15.2% of    3.28MiB at   31.73MiB/s ETA 00:00
[download]  30.5% of    3.28MiB at   36.05MiB/s ETA 00:00
[download]  61.0% of    3.28MiB at   23.84MiB/s ETA 00:00
[download] 100.0% of    3.28MiB at   23.56MiB/s ETA 00:00
[download] 100% of    3.28MiB in 00:00:00 at 20.43MiB/s  
[Merger] Merging formats into "Rick Astley - Never Gonna Give You Up (Official Music Video) [dQw4w9WgXcQ].webm"
Deleting original file Rick Astley - Never Gonna Give You Up (Official Music Video) [dQw4w9WgXcQ].f248.webm (pass -k to keep)
Deleting original file Rick Astley - Never Gonna Give You Up (Official Music Video) [dQw4w9WgXcQ].f251.weba (pass -k to keep)

Standard error:

[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'dQw4w9WgXcQ']
[debug] User config: []
[debug] System config: []
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2023.01.02 [d83b0ad]
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-5.19.12-arch1-1-x86_64-with-glibc2.36 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1754 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking http downloader on "https://rr3---sn-uxa0n-t8gy.googlevideo.com/videoplayback?expire=1673032798&ei=_h-4Y7Vah6KTBsC1v_gG&ip=2001%3A569%3A52ad%3A4300%3Aca54%3A2c5b%3Ad810%3A30a1&id=o-AIUXQUJrKqeYtftHYiozSF1EJtd4t_YqzTFjYS2PKxYb&itag=248&source=youtube&requiressl=yes&mh=7c&mm=31%2C26&mn=sn-uxa0n-t8gy%2Csn-vgqsrnld&ms=au%2Conr&mv=m&mvi=3&pl=44&initcwndbps=2168750&spc=zIddbCE6XvG7igmbVrBP8ttQEJiHokI&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=56193418&dur=212.040&lmt=1665678637466127&mt=1673010844&fvip=4&keepalive=yes&fexp=24007246&c=ANDROID&txp=453D434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAO6AKHFnXBy5MLWoS_kxR2JV4ftWqKzz5mS5ZSr7HWpBAiAORsWDVZ_5ulukGhIXKFstSurh9drD3fhkW4B6OPeBQg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgb2ledIkLnF2tNiKgT2DetUOVSqE5_fxNLLNCZK1L9EICIQC5MMBMrhFzhw6epfqrytelntaXaUgajefkTrtx2JdADQ%3D%3D"
[debug] Invoking http downloader on "https://rr3---sn-uxa0n-t8gy.googlevideo.com/videoplayback?expire=1673032798&ei=_h-4Y7Vah6KTBsC1v_gG&ip=2001%3A569%3A52ad%3A4300%3Aca54%3A2c5b%3Ad810%3A30a1&id=o-AIUXQUJrKqeYtftHYiozSF1EJtd4t_YqzTFjYS2PKxYb&itag=251&source=youtube&requiressl=yes&mh=7c&mm=31%2C26&mn=sn-uxa0n-t8gy%2Csn-vgqsrnld&ms=au%2Conr&mv=m&mvi=3&pl=44&initcwndbps=2168750&spc=zIddbCE6XvG7igmbVrBP8ttQEJiHokI&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3437753&dur=212.061&lmt=1651669822191078&mt=1673010844&fvip=4&keepalive=yes&fexp=24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAINqWuKbg5UyoIeQtFoRGdqlbDHiC3zo_obfEYK7kfDmAiAVE62LXHgHfyUVV-tGqsJrSeUPClrFEtfVSC7kffjs_A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgb2ledIkLnF2tNiKgT2DetUOVSqE5_fxNLLNCZK1L9EICIQC5MMBMrhFzhw6epfqrytelntaXaUgajefkTrtx2JdADQ%3D%3D"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Rick Astley - Never Gonna Give You Up (Official Music Video) [dQw4w9WgXcQ].f248.webm' -i 'file:Rick Astley - Never Gonna Give You Up (Official Music Video) [dQw4w9WgXcQ].f251.weba' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Rick Astley - Never Gonna Give You Up (Official Music Video) [dQw4w9WgXcQ].temp.webm'
Traceback (most recent call last):
  File "/usr/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 970, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 930, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 914, in __exit__
    self.cookiejar.save(ignore_discard=True, ignore_expires=True)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 1622, in save
    with self.open(filename, write=True) as f:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 1577, in open
    with open(file, 'w' if write else 'r', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: 'cookies.txt'
```

**Comment by pukkandan** [comment]
> such as when the same `cookies.txt` file is needs to reused multiple times.

Can you elaborate on the use-case?

**Comment by dirkf** [comment]
Also, why not just save the cookie file and use a new copy for each of the multiple times?

**Comment by ghallberg** [comment]
I'm not the creator of the issue, but I'll add some context from my end.

> Can you elaborate on the use-case?

I download my cookies from twitch.com so that it knows which channels I'm subscribed to, allowing me to open locked content, and skipping ads on those channels.

> Also, why not just save the cookie file and use a new copy for each of the multiple times?

As stated above, I do have a file saved, in a specific location on my computer. I then pass that file into youtube-dl. However, youtube-dl sometimes decides to overwrite that file with an empty file, so the next time I try to use the file, youtube-dl crashes, because it does not accept an empty file for cookies.

I've taken to saving the cookie file in a git repository with my config files, so when my cookies are deleted I can just check out the version of the file in git and continue, but it's annoying to do so for no reason.

**Comment by Grub4K** [comment]
This seems like a bug in youtube-dl and should be tracked accordingly. If that happens open a new issue and provide full log so we can eliminate it.

The question is why would you want your cookie file to be frozen aside from a bug. I can imagine maybe using the same cookie file from multiple instances?

**Comment by pukkandan** [comment]
> youtube-dl sometimes decides to overwrite that file with an empty file, so the next time I try to use the file, youtube-dl crashes, because it does not accept an empty file for cookies.

The only reason I can imagine this happening is if either ytdl/p is killed or disk space runs out while cookiefile is being written to. We could handle these situations by first writing a temp file and then replacing the original (like we do for pretty much everything else). Not writing cookies back is not a good way to deal with this

> I also tried to remove write permissions with `chmod 444 cookies.txt`
> 
> When running `youtube-dl --verbose --cookies ~/Downloads/cookies.txt https://globoplay.globo.com/v/6733094/programa/` again, I get the following error:

If setting cookiefile to readonly is desired, we could convert the error into a warning. This should also effectively address any race condition with multiple instances[^unsupported]

[^unsupported]: Running multiple yt-dlp instances on same files is not a generally supported use-case, and may cause other issues

**Comment by dirkf** [comment]
If a workflow relies on a cookie file I would suggest s/t like (POSIX)
```
if [ -s cookies.txt ] || cp ../saved/cookies.txt .; then
    yt-dlp --cookies cookies.txt ...
else
    echo "cookie file error $?" 1>&2; exit 1
fi
```
No doubt a similar thing could be conjured in the even more abstruse _cmd_ syntax by someone who cared.

Nonetheless I agree that it is a Bad Thing if a write failure should somehow truncate or delete the user's cookie file.

**Comment by ischmidt20** [comment]
A use case I have is that I operate yt-dlp on a system where each account is given a disk space quota. Sometimes I am stupid and leave a process running which keeps writing to the file system and exceeds my quota. I can easily just delete the offending files and regain the disk space, but for some reason yt-dlp isn't able to overwrite the cookie file (due to quota errors) unless I delete the cookie file specifically and re-upload it. Maybe this is just an issue with the quota program itself (or the solution is for me to just to not be negligible), but if the cookie file was set to read-only, that would also solve the problem.

**Comment by lbmaian** [comment]
I'm also occasionally hit by this issue with many concurrent yt-dlp instances. As a stop-gap, can an option be added to simply avoid saving the cookies file? I periodically manually refetch a cookies file, so I have no need for the set-cookies updates to be saved.

**Comment by elisaado** [comment]
Running into this on kubernetes, as the cookies volume is read-only (it comes from a secret)

**Comment by jim60105** [comment]
**Please change it to _warning_, or at least _provide an argument_ for this so that it won't exit with error.**

I am running yt-dlp in Kubernetes, and the cookies files are using K8s secrets volume mounts as files. Even if I set the permissions to 666, it still reports "Read-only file system." 

```
 OSError: [Errno 30] Read-only file system: '/download/cookies/cookies.txt'
```

It is indeed a Read-only file system, and K8s is designed to handle secrets in this way. I think I don't need to, and cannot write it back to K8s secrets within the pod.

The current feasible workaround is to modify the pod command, mount secrets elsewhere and cp them to another location for use. But this is very... inelegant. I must override the entrypoint, and the program will break when there are changes in docker image design in the future. Also this image needs to have sh and cp inside, which prevents me from using distroless. I have to modify the dockerfile for this purpose.

In fact, I don't quite understand the necessity of writing back cookie.

Will not updating it cause problems?
Is the consequence of this issue serious enough that we need to mark the status of this download as "failed"?

> We could handle these situations by first writing a temp file and then replacing the original

If the final replacing only results in a warning on failure then it's fine.
If it still exits with errors this will still disrupt my work.
I don't want to implement logic like "whether an acceptable error has occurred" in my operating application, which is even worse.

**Comment by pukkandan** [comment]
> Will not updating it cause problems?

Yes

> Is the consequence of this issue serious enough that we need to mark the status of this download as "failed"?

The return code marks only that "something failed" and can be set for several cases where the download actually succeeded. But even so, I agree this is not serious enough to error.



> > We could handle these situations by first writing a temp file and then replacing the original
> 
> If the final replacing only results in a warning on failure then it's fine.

Agreed, as I proposed in the same comment https://github.com/yt-dlp/yt-dlp/issues/5977#issuecomment-1374641028. Someone pls make a PR for it.

**Comment by dirkf** [comment]
Considering https://github.com/yt-dlp/yt-dlp/issues/5977#issuecomment-2123022028, one could make a reusable `SafeWriter` context manager class out of the existing, eg, `utils.write_json()` code, s/t like this:
```py3
class SafeWriter:
    """Write a file without first overwriting any existing file"""

    _tf = None
    _fn = None

    def __init__(self, fn, mode='', encoding=None):
        self._fn = fn

        args = {
            'suffix': '.tmp',
            'prefix': os.path.basename(self._fn) + '.',
            'dir': os.path.dirname(self._fn),
            'delete': False,
        }

        if mode and 'w' not in mode:
            mode = 'w' + mode
        args['mode'] = mode
        if 'b' not in mode:
            args['encoding'] = encoding or 'utf-8'

        self._tf = tempfile.NamedTemporaryFile(**args)

    def __getattr__(self, name):
        if not self._tf:
            raise AttributeError('Missing tempfile')
        # forward IOBase methods to the tempfile
        return getattr(self._tf, name)

    def __enter__(self):
        self._tf.__enter__()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        result = self._tf.__exit__(exc_type, exc_val, exc_tb)
        if exc_type:
            # clean-up
            with contextlib.suppress(OSError):
                os.remove(self._tf.name)
        else:
            # commit change
            with contextlib.suppress(OSError):
                if sys.platform == 'win32':
                    # Need to remove existing file on Windows, else os.rename raises
                    # WindowsError or FileExistsError.
                    os.unlink(self._fn)
                mask = os.umask(0)
                os.umask(mask)
                os.chmod(self._tf.name, 0o666 & ~mask)
            os.rename(self._tf.name, self._fn)
        return result

# and then, as an example

def write_json_file(obj, fn):
    """ Encode obj as JSON and write it to fn, atomically if possible """
    with SafeWriter(fn) as tf:
        json.dump(obj, tf, ensure_ascii=False)
```
In that method docstring the word `atomically` could be misleading, but as before what should happen is that failing to write the new file doesn't explicitly destroy the existing file of the same name. Maybe there are filesystem or storage device failure modes where failing to write some file weirdly affects a different existing file, but there's nothing to be done in such a case.

If the rename fails, the code above would leave the .tmp file behind. A trivial but tedious mod would remove it just as when the context manager block raises an exception.
```py3
    def __exit__(self, exc_type, exc_val, exc_tb):
        result = self._tf.__exit__(exc_type, exc_val, exc_tb)
        is_dirty = True
        try:
            if not exc_type:
                # commit change
                with contextlib.suppress(OSError):
                    if sys.platform == 'win32':
                        # Need to remove existing file on Windows, else os.rename raises
                        # WindowsError or FileExistsError.
                        os.unlink(self._fn)
                    mask = os.umask(0)
                    os.umask(mask)
                    os.chmod(self._tf.name, 0o666 & ~mask)
                os.rename(self._tf.name, self._fn)
                is_dirty = False
        finally:
            if is_dirty:
                # clean-up
                with contextlib.suppress(OSError):
                    os.remove(self._tf.name)
        return result
```
In `cookies.YoutubeDLCookieJar.save()` there's a potential clash with the `.open()` context manager but assuming that we only `.save()` to a pathy filename and not a stream (though if so, why is `.open()` used?): 
```diff
-        with self.open(filename, write=True) as f:
+        with SafeWriter(filename) as f:
             f.write(self._HEADER)
             self._really_save(f, *args, **kwargs)
```
Otherwise, a hack, but use `SafeWriter(filename) if is_path_like(filename) else self.open(filename, write=True)` instead.

Finally, one would have to consider where, if anywhere, cookie jar saves need to be trapped into warnings.
