### ISSUE TITLE
Videos from www.college-de-france.fr not handled anymore

### ISSUE THREAD

**Issue by pitrou** [yt-dlp/yt-dlp#5991]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Videos from https://www.college-de-france.fr/ used to be downloadable but they cannot anymore. There seems to have been a website redesign, which may be the cause of this.

Example URL is https://www.college-de-france.fr/agenda/cours/reproduction-et-demographie-chez-les-hominines/organisation-sociale-et-reproduction-chez-les-primates

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.college-de-france.fr/agenda/cours/reproduction-et-demographie-chez-les-hominines/organisation-sociale-et-reproduction-chez-les-primates']
[debug] User config "/home/antoine/.config/yt-dlp/config": ['--no-playlist', '-S', 'height:1200', '--sub-langs', 'fr,en', '--embed-subs', '--write-subs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.10.5 (CPython x86_64 64bit) - Linux-5.15.0-57-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.5 5 Jul 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://www.college-de-france.fr/agenda/cours/reproduction-et-demographie-chez-les-hominines/organisation-sociale-et-reproduction-chez-les-primates
[generic] organisation-sociale-et-reproduction-chez-les-primates: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] organisation-sociale-et-reproduction-chez-les-primates: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.college-de-france.fr/agenda/cours/reproduction-et-demographie-chez-les-hominines/organisation-sociale-et-reproduction-chez-les-primates
Traceback (most recent call last):
  File "/home/antoine/mambaforge/envs/youtube-dl/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/home/antoine/mambaforge/envs/youtube-dl/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/home/antoine/mambaforge/envs/youtube-dl/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/home/antoine/mambaforge/envs/youtube-dl/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2523, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.college-de-france.fr/agenda/cours/reproduction-et-demographie-chez-les-hominines/organisation-sociale-et-reproduction-chez-les-primates
```

**Comment by bashonly** [comment]
In the page source, there is a `<video>` tag with a `data-youtube-id` attribute:
```html
  <div class="field field--name-field-media-oembed-video field--type-string field--label-visually_hidden">
    <div class="field__label visually-hidden">URL de la vidéo</div>
              <div class="field__item"><video id="video-93294-0" data-youtube-id="ATbrO9DpAaw" data-youtube-nocookie="true" data-hide-controls="false" data-able-player preload="auto" data-skin="2020">
  </video>
</div>
          </div>

    </div>
```

Maybe the Youtube extractor's `_extract_from_webpage` method could be tweaked to detect this?

Though, in the same page, there is also this audio embed:

```html
<div class="field field--name-field-media-link-1 field--type-link field--label-hidden field__item"><a href="https://podcastfichiers.college-de-france.fr/hublin-20221103.m4a" class="button"target="_blank">
      Écouter l'audio
```

so maybe this site should have a dedicated extractor

**Comment by pitrou** [comment]
Ah, I hadn't noticed that the video was actually Youtube-hosted. So at least I can download using the Youtube URL (which is https://www.youtube.com/watch?v=ATbrO9DpAaw in the example above).
