### ISSUE TITLE
Pornhub: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by BismutoGanymedes** [yt-dlp/yt-dlp#6003]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

```
[PornHubPagedVideoList] Extracting URL: https://www.pornhub.com/model/princess_poppy/videos
[download] Downloading playlist: model/princess_poppy/videos
[PornHubPagedVideoList] model/princess_poppy/videos: Downloading page 1
[PornHubPagedVideoList] model/princess_poppy/videos: Downloading page 2
[PornHubPagedVideoList] model/princess_poppy/videos: Downloading page 3
[PornHubPagedVideoList] model/princess_poppy/videos: Downloading page 4
[PornHubPagedVideoList] Playlist model/princess_poppy/videos: Downloading 100 items of 100
[download] Downloading item 1 of 100
[PornHub] Extracting URL: http://www.pornhub.com/view_video.php?viewkey=ph5ccb4dcbf2e8e
[PornHub] ph5ccb4dcbf2e8e: Downloading pc webpage
[PornHub] ph5ccb4dcbf2e8e: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
[PornHub] ph5ccb4dcbf2e8e: Downloading m3u8 information
[PornHub] ph5ccb4dcbf2e8e: Downloading m3u8 information
WARNING: [PornHub] Failed to download m3u8 information: <urlopen error _ssl.c:1114: The handshake operation timed out>
[PornHub] ph5ccb4dcbf2e8e: Downloading JSON metadata
[info] ph5ccb4dcbf2e8e: Downloading 1 format(s): hls-1544
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
[download] Downloading item 2 of 100
[PornHub] Extracting URL: http://www.pornhub.com/view_video.php?viewkey=ph5cdabd6bcb0e1
[PornHub] ph5cdabd6bcb0e1: Downloading pc webpage
[PornHub] ph5cdabd6bcb0e1: Downloading m3u8 information
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```yt-dlp.exe -vU -4 --restrict-filenames --downloader aria2c -o "E:\Perfil\Downloads\%(title)s.%(ext)s" https://www.pornhub.com/model/princess_poppy/videos
[debug] Command-line config: ['-vU', '-4', '--restrict-filenames', '--downloader', 'aria2c', '-o', 'E:\\Perfil\\Downloads\\%(title)s.%(ext)s', 'https://www.pornhub.com/model/princess_poppy/videos']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109541-g94aa70d757-20230109 (setts), ffprobe N-109541-g94aa70d757-20230109
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[PornHubPagedVideoList] Extracting URL: https://www.pornhub.com/model/princess_poppy/videos
[download] Downloading playlist: model/princess_poppy/videos
[PornHubPagedVideoList] model/princess_poppy/videos: Downloading page 1
[PornHubPagedVideoList] model/princess_poppy/videos: Downloading page 2
[PornHubPagedVideoList] model/princess_poppy/videos: Downloading page 3
[PornHubPagedVideoList] model/princess_poppy/videos: Downloading page 4
[PornHubPagedVideoList] Playlist model/princess_poppy/videos: Downloading 100 items of 100
[download] Downloading item 1 of 100
[PornHub] Extracting URL: http://www.pornhub.com/view_video.php?viewkey=ph5ccb4dcbf2e8e
[PornHub] ph5ccb4dcbf2e8e: Downloading pc webpage
[PornHub] ph5ccb4dcbf2e8e: Downloading m3u8 information
[PornHub] ph5ccb4dcbf2e8e: Downloading m3u8 information
[PornHub] ph5ccb4dcbf2e8e: Downloading m3u8 information
[PornHub] ph5ccb4dcbf2e8e: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ph5ccb4dcbf2e8e: Downloading 1 format(s): hls-1544-1
[debug] Invoking hlsnative downloader on "https://ev-h.phncdn.com/hls/videos/201905/02/221481341/,720P_4000K,480P_2000K,240P_400K,_221481341.mp4.urlset/index-f1-v1-a1.m3u8?validfrom=1673302172&validto=1673309372&ipa=66.90.72.173&hdl=-1&hash=06t7TFtqydGdRkvIyo5TEzBbnSo%3D"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3236, in process_info
  File "yt_dlp\YoutubeDL.py", line 2959, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\hls.py", line 59, in real_download
  File "yt_dlp\YoutubeDL.py", line 3730, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1535, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
```

**Comment by bashonly** [comment]
Show full verbose log starting with `[debug] Command-line config:`

**Comment by bashonly** [comment]
Are you able to download an individual video with yt-dlp? Are you able to watch the video in your browser?

**Comment by BismutoGanymedes** [comment]
I cannot download individual videos, I can see the videos online in the browser.

**Comment by bashonly** [comment]
Can't reproduce the issue with python 3.10. Possibly TLS fingerprinting-related?

**Comment by CRTejaswi** [comment]
try clearing the DNS cache & retry:
```
ipconfig \flushdns
```
