### ISSUE TITLE
NBC extractor not saving video clips

### ISSUE THREAD

**Issue by 2ShedsJackson** [yt-dlp/yt-dlp#6019]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

The nbc.py extractor isn't saving short video clips. It saves a file with extension "unknown_video" as if it were a video file and tries to add metadata to it. That file, however, is actually the master m3u8 file.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.nbc.com/the-golden-globe-awards/video/oprah-winfrey-receives-cecil-b-de-mille-award-at-the-2018-golden-globes/3646439']
[debug] User config "C:\msys64\home\User/yt-dlp.conf": ['--write-info-json', '--console-title', '-c', '-i', '-w', '--write-sub', '--write-auto-sub', '--all-subs', '--write-description', '--write-all-thumbnails', '--add-metadata', '--write-annotations', '--no-post-overwrites', '-o', '%(title)s [%(id)s, %(format_id)s, %(width)sx%(height)s].%(ext)s', '--abort-on-unavailable-fragment', '--retries', '20', '--fragment-retries', '20', '--hls-prefer-native', '--no-cache-dir', '-S', 'tbr,vbr,abr', '--ap-mso', 'PRIVATE', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.9.7 (CPython AMD64 64bit) - PRIVATE (OpenSSL 1.1.1l  24 Aug 2021)
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2021.05.30, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[NBC] Extracting URL: https://www.nbc.com/the-golden-globe-awards/video/oprah-winfrey-receives-cecil-b-de-mille-award-at-the-2018-golden-globes/3646439
[NBC] 3646439: Downloading JSON metadata
[NBC] 3646439: Downloading JSON metadata
[ThePlatform] Extracting URL: http://link.theplatform.com/s/NnzsPC/media/guid/2410887629/3646439?mbr=true&manifest=m3u&switch=HLSServiceSecure#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 3646439: Downloading SMIL data
[ThePlatform] 3646439: Checking video URL
[ThePlatform] 3646439: Downloading JSON metadata
[info] 3646439: Downloading subtitles: en
[debug] Sort order given by user: tbr, vbr, abr
[debug] Formats sorted by: hasvid, ie_pref, tbr, vbr, abr, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3646439: Downloading 1 format(s): http-4096
[info] Writing video description to: Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].description
[info] Writing video subtitles to: Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].en.tt
[debug] Invoking http downloader on "http://mpxstatic-nbcmpx.nbcuni.com/caption/856/19/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_anvver_3.tt"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].en.tt
[download] 100% of   38.46KiB in 00:00:00 at 392.46KiB/s
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].jpg
[info] Writing video metadata as JSON to: Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].info.json
WARNING: There are no annotations to write.
[debug] Invoking http downloader on "https://hls-manifest.apps.nbcuni.com/manifest/hls/3646439?brand=nbc&cacheVersion=x_RqYLP9_Jad&userData=1673508510000:cdedf4f24246d36fec9b9f98a6550fd3ba5439932eadf2d2e1c114a7435b04d6"
[download] Destination: Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].unknown_video
[download] 100% of    3.55KiB in 00:00:00 at 22.06KiB/s
[Metadata] Adding metadata to "Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].unknown_video"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].unknown_video" -i "file:Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].meta" -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -write_id3v1 1 -metadata "title=Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes" -metadata "date=20180107" -metadata "description=Oprah Winfrey receives the Cecil B. de Mille Award at the 75th Annual Golden Globe Awards." -metadata "synopsis=Oprah Winfrey receives the Cecil B. de Mille Award at the 75th Annual Golden Globe Awards." -metadata "purl=https://www.nbc.com/the-golden-globe-awards/video/oprah-winfrey-receives-cecil-b-de-mille-award-at-the-2018-golden-globes/3646439" -metadata "comment=https://www.nbc.com/the-golden-globe-awards/video/oprah-winfrey-receives-cecil-b-de-mille-award-at-the-2018-golden-globes/3646439" -metadata "artist=NBCU-COM" -metadata "show=The Golden Globe Awards" -metadata "season_number=75" -metadata "episode_id=Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes" -metadata "episode_sort=1" -movflags "+faststart" "file:Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].temp.unknown_video"
[debug] ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
  configuration: --prefix=/mingw64 --target-os=mingw32 --arch=x86_64 --disable-debug --enable-amf --enable-dxva2 --enable-d3d11va --enable-fontconfig --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libcaca --enable-libcelt --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxvid --enable-libvpx --enable-libwebp --enable-libxml2 --enable-nvenc --enable-openal --enable-pic --enable-postproc --enable-runtime-cpudetect --enable-swresample --enable-version3 --enable-vulkan --enable-zlib --disable-doc --enable-frei0r --logfile=config.log --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[hls @ 0000000000481d80] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=4296000,CODECS="avc1.640028",RESOLUTION=1920x1080,URI="https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_4200_iframe.m3u8"')
[hls @ 0000000000481d80] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=2596000,CODECS="avc1.64001f",RESOLUTION=1280x720,URI="https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_2500_iframe.m3u8"')
[hls @ 0000000000481d80] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1896000,CODECS="avc1.64001f",RESOLUTION=960x540,URI="https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_1800_iframe.m3u8"')
[hls @ 0000000000481d80] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1296000,CODECS="avc1.64001f",RESOLUTION=960x540,URI="https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_1200_iframe.m3u8"')
[hls @ 0000000000481d80] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=796000,CODECS="avc1.64001e",RESOLUTION=640x360,URI="https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_700_iframe.m3u8"')
[hls @ 0000000000481d80] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=496000,CODECS="avc1.640015",RESOLUTION=448x252,URI="https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_400_iframe.m3u8"')
[hls @ 0000000000481d80] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=296000,CODECS="avc1.640015",RESOLUTION=448x252,URI="https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_200_iframe.m3u8"')
[hls @ 0000000000481d80] Opening 'https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_4200.m3u8' for reading
[https @ 000000000049d240] Protocol 'https' not on whitelist 'file,crypto,data'!
[hls @ 0000000000481d80] parse_playlist error Invalid argument [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_4200.m3u8]
[hls @ 0000000000481d80] Opening 'https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_2500.m3u8' for reading
[https @ 0000000000489580] Protocol 'https' not on whitelist 'file,crypto,data'!
[hls @ 0000000000481d80] parse_playlist error Invalid argument [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_2500.m3u8]
[hls @ 0000000000481d80] Opening 'https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_1800.m3u8' for reading
[https @ 0000000000489580] Protocol 'https' not on whitelist 'file,crypto,data'!
[hls @ 0000000000481d80] parse_playlist error Invalid argument [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_1800.m3u8]
[hls @ 0000000000481d80] Opening 'https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_1200.m3u8' for reading
[https @ 0000000000489580] Protocol 'https' not on whitelist 'file,crypto,data'!
[hls @ 0000000000481d80] parse_playlist error Invalid argument [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_1200.m3u8]
[hls @ 0000000000481d80] Opening 'https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_700.m3u8' for reading
[https @ 0000000000489580] Protocol 'https' not on whitelist 'file,crypto,data'!
[hls @ 0000000000481d80] parse_playlist error Invalid argument [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_700.m3u8]
[hls @ 0000000000481d80] Opening 'https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_400.m3u8' for reading
[https @ 0000000000489580] Protocol 'https' not on whitelist 'file,crypto,data'!
[hls @ 0000000000481d80] parse_playlist error Invalid argument [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_400.m3u8]
[hls @ 0000000000481d80] Opening 'https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_200.m3u8' for reading
[https @ 0000000000489580] Protocol 'https' not on whitelist 'file,crypto,data'!
[hls @ 0000000000481d80] parse_playlist error Invalid argument [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_200.m3u8]
[hls @ 0000000000481d80] Empty segment [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_4200.m3u8]
[hls @ 0000000000481d80] Empty segment [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_2500.m3u8]
[hls @ 0000000000481d80] Empty segment [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_1800.m3u8]
[hls @ 0000000000481d80] Empty segment [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_1200.m3u8]
[hls @ 0000000000481d80] Empty segment [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_700.m3u8]
[hls @ 0000000000481d80] Empty segment [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_400.m3u8]
[hls @ 0000000000481d80] Empty segment [https://nbchls-prod.nbcuni.com/tve-adstitch/2228/18/01/07/3646439/180107_3646439_Oprah_Winfrey_Receives_Cecil_B__de_Mille_Awa_1515395548_200.m3u8]
Input #0, hls, from 'file:Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].unknown_video':
  Duration: N/A, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 4542800
  Program 1
    Metadata:
      variant_bitrate : 2757800
  Program 2
    Metadata:
      variant_bitrate : 2022800
  Program 3
    Metadata:
      variant_bitrate : 1392800
  Program 4
    Metadata:
      variant_bitrate : 867800
  Program 5
    Metadata:
      variant_bitrate : 552800
  Program 6
    Metadata:
      variant_bitrate : 342800
Input #1, ffmetadata, from 'file:Oprah Winfrey Receives Cecil B. de Mille Award at the 2018 Golden Globes [3646439, http-4096, 1920x1080].meta':
  Duration: 00:09:30.00, start: 0.000000, bitrate: 0 kb/s
  Chapters:
    Chapter #1:0: start 0.000000, end 570.000000
      Metadata:
        title           : <Untitled Chapter 1>
Stream map '0' matches no streams.
To ignore this, add a trailing '?' to the map.

ERROR: To ignore this, add a trailing '?' to the map.
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3451, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 706, in run
    self.run_ffmpeg_multiple_files(
  File "C:/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 324, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "C:/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 362, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: To ignore this, add a trailing '?' to the map.
```

**Comment by dirkf** [comment]
This needs a provider account and/or being in region to reproduce and debug fully.

However, the problem originates in `_parse_smil_formats()` where the URL from the log

https://hls-manifest.apps.nbcuni.com/manifest/hls/3646439?brand=nbc&cacheVersion=x_RqYLP9_Jad&userData=1673508510000:cdedf4f24246d36fec9b9f98a6550fd3ba5439932eadf2d2e1c114a7435b04d6

is not being recognised as M3U8 by the `determine_ext()` function.

Maybe the `ext` value (`= medium.get('ext')`) sent by the site should be checked? Or a URL with `/manifest/hls/` should be recognised as M3U8?

Or, additional processing could be done in `ThePlatformBaseIE._extract_theplatform_smil()` when adding the SMIL formats, eg, after looking at the `Content-Type` from a `HEAD` request.

**Comment by 2ShedsJackson** [comment]
> This needs a provider account and/or being in region to reproduce and debug fully.

The video clip doesn't need a provider.
https://www.nbc.com/the-golden-globe-awards/video/oprah-winfrey-receives-cecil-b-de-mille-award-at-the-2018-golden-globes/3646439

**Comment by dirkf** [comment]
It's geo-blocked from the UK, but possibly a provider account might unblock it.

**Comment by 2ShedsJackson** [comment]
> It's geo-blocked from the UK, but possibly a provider account might unblock it.

Maybe, maybe not. Just use a VPN.

**Comment by 2ShedsJackson** [comment]
To make matters worse, newer video clips don't follow the older URL scheme-

[generic] Extracting URL: https://www.nbc.com/quantum-leap/video/bens-first-leap-nbcs-quantum-leap/NBCE125189978
[generic] NBCE125189978: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] NBCE125189978: Extracting information
ERROR: Unsupported URL: https://www.nbc.com/quantum-leap/video/bens-first-leap-nbcs-quantum-leap/NBCE125189978

**Comment by dirkf** [comment]
Yes, but that's straightforward (at least according to the metadata -- I didn't watch it):
```diff
-    _VALID_URL = r'https?(?P<permalink>://(?:www\.)?nbc\.com/(?:classic-tv/)?[^/]+/video/[^/]+/(?P<id>n?\d+))'
+    _VALID_URL = r'https?(?P<permalink>://(?:www\.)?nbc\.com/(?:classic-tv/)?[^/]+/video/[^/]+/(?:NBC[A-Z])?(?P<id>n?\d+))'
```
Or if the final component only ever has `E` after `NBC`, replace `[A-Z]` with `E`.
