### ISSUE TITLE
can't download from pandora.tv

### ISSUE THREAD

**Issue by matan2244** [yt-dlp/yt-dlp#6026]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

can't download from pandora.tv:

ERROR: [pandora.tv] 49308018: 49308018: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

tried to download this url:
[http://www.pandora.tv/view/john2733/49308018/#35484249_new](url)

using this command
yt-dlp.exe -vU "http://www.pandora.tv/view/john2733/49308018/#35484249_new" --concurrent-fragments 3 --download-archive "D:\scraped videos\archive" -P "D:\scraped videos\youtube\temp3"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
H:\downloads>yt-dlp.exe http://www.pandora.tv/view/john2733/49308018/#35484249_new --concurrent-fragments 3 --download-archive "D:\scraped videos\archive" -P "D:\scraped videos\youtube\temp3"
[pandora.tv] Extracting URL: http://www.pandora.tv/view/john2733/49308018/#35484249_new
[pandora.tv] 49308018: Downloading JSON metadata
ERROR: [pandora.tv] 49308018: 49308018: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

H:\downloads>yt-dlp.exe -vU "http://www.pandora.tv/view/john2733/49308018/#35484249_new" --concurrent-fragments 3 --download-archive "D:\scraped videos\archive" -P "D:\scraped videos\youtube\temp3"
[debug] Command-line config: ['-vU', 'http://www.pandora.tv/view/john2733/49308018/#35484249_new', '--concurrent-fragments', '3', '--download-archive', 'D:\\scraped videos\\archive', '-P', 'D:\\scraped videos\\youtube\\temp3']
[debug] Encodings: locale cp1255, fs utf-8, pref cp1255, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Loading archive file 'D:\\scraped videos\\archive'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[pandora.tv] Extracting URL: http://www.pandora.tv/view/john2733/49308018/#35484249_new
[pandora.tv] 49308018: Downloading JSON metadata
ERROR: [pandora.tv] 49308018: 49308018: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\pandoratv.py", line 80, in _real_extract
  File "yt_dlp\extractor\common.py", line 1034, in download_content
  File "yt_dlp\extractor\common.py", line 1004, in download_handle
  File "yt_dlp\extractor\common.py", line 994, in parse
  File "yt_dlp\extractor\common.py", line 981, in _parse_json
  File "yt_dlp\extractor\common.py", line 964, in __print_error

  File "yt_dlp\utils.py", line 606, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 978, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils.py", line 609, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by dirkf** [comment]
The extractor looks for JSON from http://m.pandora.tv/?c=view&m=viewJsonApi&ch_userid=john2733&prgid=49308018, but the `m` query parameter is being ignored, or needs a new value. Instead the request returns the mobile video page for the item, which, being HTML, can't be decoded as JSON.

**Comment by matan2244** [comment]
> The extractor looks for JSON from http://m.pandora.tv/?c=view&m=viewJsonApi&ch_userid=john2733&prgid=49308018, but the `m` query parameter is being ignored, or needs a new value. Instead the request returns the mobile video page for the item, which, being HTML, can't be decoded as JSON.

Does that mean that the issue will not be solved?
I did get the video using chrome, and f12 inspecting the html itself.

**Comment by bashonly** [comment]
> Does that mean that the issue will not be solved?

dirkf was explaining why the extractor is broken. If you were able to download by viewing page source, then the extractor can be fixed, someone just needs to actually fix it
