### ISSUE TITLE
Kinopoisk

### ISSUE THREAD

**Issue by artenax** [yt-dlp/yt-dlp#6027]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

It seems that downloading trailers from Kinopoisk doesn't work.

These two URLs return an error, see below.
https://www.kinopoisk.ru/film/4370148/video/185663/

https://widgets.kinopoisk.ru/discovery/film/4370148/trailer/185663?noAd=1&embedId=&hidden=&muted=&loop=0&autoplay=1&from=&extraTrailers=&onlyPlayer=1

I was able to download with [VideoDownload Helper 6.3.1](https://github.com/JustOff/ca-archive) (legacy) in Pale Moon 29.
There's nothing complicated there, no encryption.
Just, a few ts fragments. The quality is from 360p to 1080p.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
1:

denis@systemp:~$ python3.8 /home/denis/yt-dlp -vU 'https://www.kinopoisk.ru/film/4370148/video/185663/'
[debug] Command-line config: ['-vU', 'https://www.kinopoisk.ru/film/4370148/video/185663/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.8.3 (CPython i686 32bit) - Linux-4.4.0-140-generic-i686-with-glibc2.17 (OpenSSL 1.0.2g  1 Mar 2016, glibc 2.23)
[debug] exe versions: ffmpeg 4.3.1 (fdk), ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2020.06.20, mutagen-1.31, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[debug] Using fake IP 5.140.211.242 (RU) as X-Forwarded-For
[KinoPoisk] Extracting URL: https://www.kinopoisk.ru/film/4370148/video/185663/
[KinoPoisk] 4370148: Downloading webpage
ERROR: [KinoPoisk] 4370148: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known')))
  File "/home/denis/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/home/denis/yt-dlp/yt_dlp/extractor/kinopoisk.py", line 31, in _real_extract
    webpage = self._download_webpage(
  File "/home/denis/yt-dlp/yt_dlp/extractor/common.py", line 1083, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "/home/denis/yt-dlp/yt_dlp/extractor/common.py", line 1034, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/denis/yt-dlp/yt_dlp/extractor/common.py", line 868, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/denis/yt-dlp/yt_dlp/extractor/common.py", line 825, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1402, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/denis/yt-dlp/yt_dlp/extractor/common.py", line 807, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/denis/yt-dlp/yt_dlp/YoutubeDL.py", line 3730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/denis/yt-dlp/yt_dlp/utils.py", line 1535, in https_open
    return self.do_open(
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

2:
denis@systemp:~$ python3.8 /home/denis/yt-dlp -vU 'https://widgets.kinopoisk.ru/discovery/film/4370148/trailer/185663?noAd=1&embedId=&hidden=&muted=&loop=0&autoplay=1&from=&extraTrailers=&onlyPlayer=1'
[debug] Command-line config: ['-vU', 'https://widgets.kinopoisk.ru/discovery/film/4370148/trailer/185663?noAd=1&embedId=&hidden=&muted=&loop=0&autoplay=1&from=&extraTrailers=&onlyPlayer=1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.8.3 (CPython i686 32bit) - Linux-4.4.0-140-generic-i686-with-glibc2.17 (OpenSSL 1.0.2g  1 Mar 2016, glibc 2.23)
[debug] exe versions: ffmpeg 4.3.1 (fdk), ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2020.06.20, mutagen-1.31, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://widgets.kinopoisk.ru/discovery/film/4370148/trailer/185663?noAd=1&embedId=&hidden=&muted=&loop=0&autoplay=1&from=&extraTrailers=&onlyPlayer=1
[generic] 185663?noAd=1&embedId=&hidden=&muted=&loop=0&autoplay=1&from=&extraTrailers=&onlyPlayer=1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 185663?noAd=1&embedId=&hidden=&muted=&loop=0&autoplay=1&from=&extraTrailers=&onlyPlayer=1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://widgets.kinopoisk.ru/discovery/film/4370148/trailer/185663?noAd=1&embedId=&hidden=&muted=&loop=0&autoplay=1&from=&extraTrailers=&onlyPlayer=1
Traceback (most recent call last):
  File "/home/denis/yt-dlp/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/home/denis/yt-dlp/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/home/denis/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/home/denis/yt-dlp/yt_dlp/extractor/generic.py", line 2523, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://widgets.kinopoisk.ru/discovery/film/4370148/trailer/185663?noAd=1&embedId=&hidden=&muted=&loop=0&autoplay=1&from=&extraTrailers=&onlyPlayer=1
```

**Comment by artenax** [comment]
There are two commercials before the trailer. Maybe that's the reason.

And to make the right mouse button above the video work in Firefox (to copy the iframe URL) you need to change dom.event.contextmenu.enabled parameter to false in about:config.
So adding support for widgets.kinopoisk.ru would also be good.

**Comment by bashonly** [comment]
The extractor is making a request to an API subdomain that no longer exists. It will need to be rewritten. The iframe source from the example URL has some JSON that holds most of the information that the extractor currently looks for.

**Comment by dirkf** [comment]
Also, the extractor doesn't know or care about the trailer that is actually being requested in the first URL (the film itself isn't available, only a ticket link).

The widgets.kinopoisk.ru link is an internal link that you wouldn't normally find in the site's pages, whereas the trailer link is actually on the film's page on the site https://www.kinopoisk.ru/film/4370148/. It would be easy enough to add an extractor class to redirect from the widgets URL but I wouldn't be in favour.

**Comment by dirkf** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/18896
Also: https://github.com/ytdl-org/youtube-dl/issues/27644

**Comment by artenax** [comment]
I understand. yt-dlp sends a request to a domain that doesn't exist https://ott-widget.kinopoisk.ru/v1/kp/?kpId=4370148
But even if I replace ott-widget.kinopoisk.ru with widgets.kinopoisk.ru in the source code https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/kinopoisk.py then:
1. URL (not domain) https://widgets.kinopoisk.ru/v1/kp/?kpId=4370148 doesn't exist
2. yt-dlp sends a request where video_id (4370148) is the id of the movie, not the trailer (185663). Trailers are not counted. It is required to send two id's (https://www.kinopoisk.ru/film/4370148/video/185663/)

I was told that Internet Download Manager supports downloading.

**Comment by dirkf** [comment]
It's not just the domain that's changed.

This procedure gets the trailer:
1. Download the webpage.
2. Check if the title is Oops!, which means the URL led to a bad page or, if `/checkcaptcha?` is in the page, a Captcha page.
3. Otherwise find the share URL from the `video_src` or `twitter:player` meta items.
4. Download the share page from the URL.
5. Find the discovery URL as the `src` of the `<iframe>` in that page. 
6. Download the discovery page from the URL.
7. Get the discovery data by finding the content of the `<script>` element with attribute `data-state`, decoding its %-encoding and parsing as JSON.
8. The trailer media link is at `.models.trailers.{trailer_id}.streamUrl` along with other trailer-specific data; `.models.trailers.film` is an object containing details of the film being trailed.

If any page on the site actually hosts a playable feature (ie, not just a clip or trailer), the `.models.films.{film_id}` object might be populated, including media link(s).

**Comment by artenax** [comment]
[dirkf](https://github.com/dirkf) it's difficult for me.

Here's an option: you can get a link to m3u8 using the [hls stream detector](https://addons.mozilla.org/firefox/addon/hls-stream-detector) extension, which you can then send to yt-dlp and yt-dlp will download the video.
Start playing the video on the page, select the desired quality, move the cursor to the beginning and copy the latest link to m3u8 from the extension.

**Comment by dirkf** [comment]
What we need in order to test a new extractor is a page that plays a feature, and not just a trailer, in the site (so, not just linking to external sites).

**Comment by tkzv** [comment]
@dirkf , do you mean a page like this: https://www.kinopoisk.ru/film/12205/video/3262/ ?

**Comment by dirkf** [comment]
That's the/a trailer for 12205, or it's a clip in the Trailers (Трейлеры) category. At https://www.kinopoisk.ru/film/12205/video/, one can see that there are 2 "fragments", a clip, and the trailer. If trailer and clip videos are all that's wanted, it should be easy, using the previously described procedure.

The test video in the current extractor is not a trailer/clip, being more than an hour long. Apparently you have to log in to get to the player page for a full show (eg, the button `Буду смотреть` at https://www.kinopoisk.ru/film/12205/).

Who knows what happens next? Maybe [@UnaidedEye](https://github.com/ytdl-org/youtube-dl/issues/27644#issue-777625065) does:
* for https://www.kinopoisk.ru/film/594554/, find the JSON fragment `{"__typename":"Film","id":594554,"contentId":"466ae356618feb9296e9e2d0ecd50bdf", ...` to get its magic UUID (or from many other occurrences in the page)
* go to the watch/play page with that `contentId`: https://hd.kinopoisk.ru/film/466ae356618feb9296e9e2d0ecd50bdf
* the playable video is the `contentUrl` in the json+ld block.

https://www.kinopoisk.ru/film/4370148/ from OP, with play button text `Смотреть фильм`, looks like it should work. But tragically https://www.kinopoisk.ru/film/12205/ has empty `contentId`; so there's some difference between content that you can actually watch (`Смотреть ...`) rather than be "going to watch" (`Буду смотреть`).

OP's trailer from ytdl-org/youtube-dl#18896 is tractable, but although the main film page has a `contentId`, the derived page is 404. Similarly with the extractor test video.

Finally, at any point you might get a Yandex "Smart Capture" challenge, which I suspect can only be mitigated even with correct use of cookies, `Referer`, `utm_referrer=organic.kinopoisk.ru` query param, and/or impersonation.
