### ISSUE TITLE
Errors when trying to download classic collection games from nba.com

### ISSUE THREAD

**Issue by DragonNeos** [yt-dlp/yt-dlp#6042]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

NBA games from the classic collection section on nba.com can't be downloaded due to errors. For example: https://www.nba.com/watch/video/2-10-2012-knicks-vs-lakers-linsanity?plsrc=nba&collection=new-york-knicks-classic-collection

When you try to download without any additional commands, the following error will appear:
```
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 807, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3730, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Since the output suggests to use --no-playlist, I tried to download it again using this command but a different error appears:
```
ERROR: list index out of range
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\nba.py", line 169, in _real_extract
  File "yt_dlp\extractor\nba.py", line 39, in _extract_video
IndexError: list index out of range
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.nba.com/watch/video/2-10-2012-knicks-vs-lakers-linsanity?plsrc=nba&collection=new-york-knicks-classic-collection']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109600-gb37795688a-20230115 (setts), ffprobe N-109600-gb37795688a-20230115, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[nba:watch] Extracting URL: https://www.nba.com/watch/video/2-10-2012-knicks-vs-lakers-linsanity?plsrc=nba&collection=new-york-knicks-classic-collection
[nba:watch] Downloading playlist new-york-knicks-classic-collection - add --no-playlist to download just the video 2-10-2012-knicks-vs-lakers-linsanity
[nba:watch:collection] Extracting URL: https://www.nba.com/watch/list/collection/new-york-knicks-classic-collection
[download] Downloading playlist: new-york-knicks-classic-collection
[nba:watch:collection] new-york-knicks-classic-collection: Downloading page 1 JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 807, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3730, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

[nba:watch:collection] Playlist new-york-knicks-classic-collection: Downloading 1 items of 0
[download] Finished downloading playlist: new-york-knicks-classic-collection

[debug] Command-line config: ['-vU', '--no-playlist', 'https://www.nba.com/watch/video/2-10-2012-knicks-vs-lakers-linsanity?plsrc=nba&collection=new-york-knicks-classic-collection']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109600-gb37795688a-20230115 (setts), ffprobe N-109600-gb37795688a-20230115, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[nba:watch] Extracting URL: https://www.nba.com/watch/video/2-10-2012-knicks-vs-lakers-linsanity?plsrc=nba&collection=new-york-knicks-classic-collection
[nba:watch] Downloading just the video 2-10-2012-knicks-vs-lakers-linsanity because of --no-playlist
[nba:watch] 2-10-2012-knicks-vs-lakers-linsanity: Downloading JSON metadata
ERROR: list index out of range
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\nba.py", line 169, in _real_extract
  File "yt_dlp\extractor\nba.py", line 39, in _extract_video
IndexError: list index out of range
```

**Comment by bashonly** [comment]
All of the site's content is now DRM-protected:

![nbadrm](https://user-images.githubusercontent.com/88596187/212805868-a1df5928-aa4f-481f-8032-e7038f18b719.jpg)

**Comment by liamengland1** [comment]
@bashonly 

replace `hls-wvpr` in the playlist url with `hls-itc` for the unencrypted playlist

```
https://nbalpng.akamaized.net/vod-pz/a/hls-wvpr/NBA_202209231912NBA_____VIDEOS__NBAE_2595511/v5-121.m3u8?addUserInfo=1&[...]
```

**Comment by Shane-Kao** [comment]
`hls-itc` does not work now, got 403 forbidden , is there any other way to download it?
