### ISSUE TITLE
ABC iView - "Extractor error" on malformed URL instead of "Unsupported"

### ISSUE THREAD

**Issue by section83** [yt-dlp/yt-dlp#6069]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

URLs in this form: "https://iview.abc.net.au/show/exhibitionists/" return "Unsupported" which is correct.  An example log:

> yt-dlp -v "https://iview.abc.net.au/show/exhibitionists/"
> [debug] Command-line config: ['-v', 'https://iview.abc.net.au/show/exhibitionists/']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2023.01.06 [6becd25] (darwin_exe)
> [debug] Python 3.8.9 (CPython arm64 64bit) - macOS-13.1-arm64-arm-64bit (LibreSSL 2.8.3)
> [debug] exe versions: ffmpeg 5.1.2-https (setts), ffprobe 5.1.2-https
> [debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
> [debug] Proxy map: {}
> [debug] Loaded 1760 extractors
> [generic] Extracting URL: https://iview.abc.net.au/show/exhibitionists/
> [generic] exhibitionists: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> [generic] exhibitionists: Extracting information
> [debug] Looking for embeds
> ERROR: Unsupported URL: https://iview.abc.net.au/show/exhibitionists/
> Traceback (most recent call last):
>   File "yt_dlp/YoutubeDL.py", line 1502, in wrapper
>   File "yt_dlp/YoutubeDL.py", line 1578, in __extract_info
>   File "yt_dlp/extractor/common.py", line 680, in extract
>   File "yt_dlp/extractor/generic.py", line 2523, in _real_extract
> yt_dlp.utils.UnsupportedError: Unsupported URL: https://iview.abc.net.au/show/exhibitionists/

URLs in this form: "https://iview.abc.net.au/show/exhibitionists" return an extractor error instead:

> yt-dlp -v "https://iview.abc.net.au/show/exhibitionists" 
> [debug] Command-line config: ['-v', 'https://iview.abc.net.au/show/exhibitionists']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2023.01.06 [6becd25] (darwin_exe)
> [debug] Python 3.8.9 (CPython arm64 64bit) - macOS-13.1-arm64-arm-64bit (LibreSSL 2.8.3)
> [debug] exe versions: ffmpeg 5.1.2-https (setts), ffprobe 5.1.2-https
> [debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
> [debug] Proxy map: {}
> [debug] Loaded 1760 extractors
> [debug] Using fake IP 1.153.235.118 (AU) as X-Forwarded-For
> [abc.net.au:iview:showseries] Extracting URL: https://iview.abc.net.au/show/exhibitionists
> [abc.net.au:iview:showseries] exhibitionists: Downloading webpage
> [abc.net.au:iview:showseries] Downloading playlist exhibitionists - add --no-playlist to download just the highlight video
> ERROR: exhibitionists: An extractor error has occurred. (caused by KeyError('selectedSeries')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
>   File "yt_dlp/extractor/common.py", line 680, in extract
>   File "yt_dlp/extractor/abc.py", line 302, in _real_extract
> KeyError: 'selectedSeries'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -v "https://iview.abc.net.au/show/exhibitionists" 
[debug] Command-line config: ['-v', 'https://iview.abc.net.au/show/exhibitionists']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (darwin_exe)
[debug] Python 3.8.9 (CPython arm64 64bit) - macOS-13.1-arm64-arm-64bit (LibreSSL 2.8.3)
[debug] exe versions: ffmpeg 5.1.2-https (setts), ffprobe 5.1.2-https
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Using fake IP 1.153.235.118 (AU) as X-Forwarded-For
[abc.net.au:iview:showseries] Extracting URL: https://iview.abc.net.au/show/exhibitionists
[abc.net.au:iview:showseries] exhibitionists: Downloading webpage
[abc.net.au:iview:showseries] Downloading playlist exhibitionists - add --no-playlist to download just the highlight video
ERROR: exhibitionists: An extractor error has occurred. (caused by KeyError('selectedSeries')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 680, in extract
  File "yt_dlp/extractor/abc.py", line 302, in _real_extract
KeyError: 'selectedSeries'
```

**Comment by bashonly** [comment]
The issue's title is confusing. `https://iview.abc.net.au/show/exhibitionists` is a valid URL for a series, no?

**Comment by section83** [comment]
> The issue's title is confusing. 

Have tried to fix Issue Title.

>`https://iview.abc.net.au/show/exhibitionists` is a valid URL for a series, no?

Although the URL has same structure, it is not a series and there is just one video available. It is necessary to dig into the web page to find out whether or not it is a series.

**Comment by dirkf** [comment]
The URL https://iview.abc.net.au/show/exhibitionists leads to the show page for the single show "The Exhibitionists", so it should be supported. Similarly with https://iview.abc.net.au/show/exhibitionists/.

As far as the yt-dlp ABC iView extractor is concerned, the URL with no trailing `/` represents a series playlist, because a single show should have a `/video/` component that is not the final component of the URL. The URL with a trailing `/` doesn't match any of the supported patterns.

The hydration JSON, assigned as a string to `window.__INITIAL_STATE__`, identifies the canonical URL for the show as https://iview.abc.net.au/video/AC2105H001S00. This redirects to https://iview.abc.net.au/show/exhibitionists/video/AC2105H001S00 on the site itself.

However the non-JS pages are all indistinguishable visually and also almost identical internally, including the hydration JSON.

This is similar for multi-episode shows. Consider, eg, Humans, a show with 3 series ("seasons", but ABC uses the non-US terminology).

1. the series URL linked from the Drama category: https://iview.abc.net.au/show/humans
2. the series URL for the whole series from the hydration JSON: https://iview.abc.net.au/show/series/humans/1
but this is not in the site; the details of the "0th" video in season/series 1 must be added:
https://iview.abc.net.au/show/series/humans/1/video/ZW0398A000S00
(ZW0398A, 000, S00 = season/series ID, episode number, ??)
this page has details of all the first season's videos as well as the top-level details of all the seasons, but not their IDs, which could be extracted from the thumbnail URL
3. the S01E02 episode page from the hydration JSON: https://iview.abc.net.au/video/ZW0398A002S00, which redirects to https://iview.abc.net.au/show/humans/series/1/video/ZW0398A002S00 on the site itself.

So apparently:
* OP's "Exhibitionists" URLs should both be treated as series URLs that extract a 1-item playlist
* for a show series URL without `/series/\d+` the extractor should get the (nested?) playlist for all seasons/series of the show
* for a show series URL with `/series/\d+` the extractor should get the playlist for the specified season/series of the show
* for an episode URL like https://iview.abc.net.au/show/exhibitionists/video/AC2105H001S00 the extractor should get the specified episode video, as at present
* exceptionally an episode URL like https://iview.abc.net.au/show/series/humans/1/video/ZW0398A000S00 with episode digits `000` in the video ID should be treated as a series page for the specified series.

The per-series and per-video URLs don't appear in the non-JS iView pages, but perhaps they can be copied out of the JS pages.

**Comment by dirkf** [comment]
Also, the geo-restriction processing for ABC could be enhanced. XFF doesn't appear to be effective, so `_GEO_BYPASS = False`. The `/api/programs` request can show geo-restriction (no media links) in the `statusMessage` item, as "Some ABC iview programs are now available outside Australia..." and this could be detected.

**Comment by gamer191** [comment]
> * OP's "Exhibitionists" URLs should both be treated as series URLs that extract a 1-item playlist

The only way I can think of doing that would be to add a fallback to ABCIViewShowSeriesIE, but wouldn't that lead to unexpected behaviour if the multi-episode series' page structure changes?

> * for a show series URL without /series/\d+ the extractor should get the (nested?) playlist for all seasons/series of the show
> * for a show series URL with /series/\d+ the extractor should get the playlist for the specified season/series of the show

ABCIViewShowSeriesIE probably does one of those behaviours, but I'd have to test which one

> The URL with a trailing / doesn't match any of the supported patterns.

I guess ABCIViewShowSeriesIE's regex could be updated to match that url (although I'm shit with at regexes)

**Comment by dirkf** [comment]
My WIP yt-dl extractor illustrates all the points: [abc.py](https://github.com/yt-dlp/yt-dlp/files/10547038/abc.py.txt)

**Comment by codewatzen** [comment]
I'm experiencing the same issue even with the pasting in just the video url still gives the same error. Any thoughts?
