### ISSUE TITLE
Does yt-dlp not work with IPV6 turned off?

### ISSUE THREAD

**Issue by LonelyGuy12** [yt-dlp/yt-dlp#6088]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have been getting this error ever since I turned off IPV6

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\ASUS>"D:\My Shit\codes\y.py"
Hallo Sir! What would you like to do today! :D
Please enter the URL you want to download from: https://www.youtube.com/watch?v=U7gDB634iAA
Would you like to install the video or the audio: a
[youtube] Extracting URL: https://www.youtube.com/watch?v=U7gDB634iAA
[youtube] U7gDB634iAA: Downloading webpage
[youtube] U7gDB634iAA: Downloading android player API JSON
[info] U7gDB634iAA: Downloading 1 format(s): 251
[download] Got error: <urlopen error _ssl.c:975: The handshake operation timed out>
Traceback (most recent call last):
  File "D:\My Shit\codes\y.py", line 94, in <module>
    asyncio.run(handler())
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\My Shit\codes\y.py", line 89, in handler
    await youtube_download_audio(url)
  File "D:\My Shit\codes\y.py", line 64, in youtube_download_audio
    ydl.download([url])
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3358, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3333, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1599, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1658, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2772, in process_video_result
    self.process_info(new_info)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3236, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2959, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\http.py", line 369, in real_download
    for retry in RetryManager(self.params.get('retries'), self.report_retry):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils.py", line 6023, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 389, in report_retry
    RetryManager.report_retry(
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils.py", line 6030, in report_retry
    return error(f'{e}. Giving up after {count - 1} retries') if count > 1 else error(str(e))
                                                                                ^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 392, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1012, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 952, in trouble
    raise DownloadError(message, exc_info)
[download] Got error: <urlopen error _ssl.c:975: The handshake operation timed out>
```

**Comment by LonelyGuy12** [comment]
The script is 
```
import yt_dlp as youtube_dl
import os
import asyncio
import aiohttp
from urllib import request as urrequest
from urllib import parse
import re


ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192'
    }],
    'postprocessor_args': [
        '-ar', '16000'
    ],
    'prefer_ffmpeg': True,
    'keepvideo': True,
    'outtmpl':'./audio.mp3'
}

async def youtube_search(query):
    search_query = query
    query = parse.urlencode({'search_query': search_query})
    content = urrequest.urlopen('http://www.youtube.com/results?' + query)
    results = re.findall(r'/watch\?v=(.{11})', content.read().decode())
    youtube_code = str(results[0])
    youtube_url = f"https://youtu.be/{youtube_code}"
    query_url = f"https://www.youtube.com/oembed?url={youtube_url}&format=json"
    async with aiohttp.ClientSession() as session:
        async with session.get(query_url) as resp:
            res = await resp.json(content_type=None)
    title = res['title']
    author = res['author_name']
    author_url = res['author_url']
    thumbnail = res['thumbnail_url']
    data_set = {'video_url': youtube_url, 'video_code': youtube_code, 'title': title, 'author': author, 'author_url': author_url, 'thumbnail': thumbnail}

    return data_set

async def youtube_download(url,path = "./audio.mp3"):
    hm = await youtube_search(url)
    title = hm['title']
    path = f"./{title}.mp3"
    ydl_opts['outtmpl'] = path
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])
    os.remove(f"./{title}.orig.mp3")
    return

asyncio.run(youtube_download(input("Enter the song name or YouTube URL: ")))```

**Comment by coletdjnz** [comment]
add `"source_address": "0.0.0.0"` to your params (`--force-ipv4`)

p.s yt-dlp has a youtube search function built in

**Comment by LonelyGuy12** [comment]
Hey! That seemed to work! Thank You so Much for the help!

Also... I was using the search function separately cuz I didn't know how to extract the video's title out of yt-dlp's function.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#extracting-information
