### ISSUE TITLE
Can't read mpd that contains *

### ISSUE THREAD

**Issue by Werner9** [yt-dlp/yt-dlp#609]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running yt-dlp version **2021.08.02**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
yt-dlp --proxy 127.0.0.1:10812 --add-header "Referer:https://www.catchplay.com/|User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36" --verbose "https://ols-ww100-cp.akamaized.net/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/JTdCJTIya2JpdCUyMiUzQTM2ODY0MDAwMCUyQyUyMnBsYXRmb3JtJTIyJTNBJTIyZGVza3RvcCUyMiUyQyUyMmRldmljZVR5cGUlMjIlM0ElMjJ3ZWIlMjIlMkMlMjJtb2RlbCUyMiUzQSUyMndpbmRvd3MlMjIlMkMlMjJvc1R5cGUlMjIlM0ElMjJjaHJvbWUlMjIlMkMlMjJvcyUyMiUzQSUyMjkyLjAuNDUxNSUyMiUyQyUyMmFwcCUyMiUzQSUyMjMuMCUyMiU3RA==/dash.mpd?cpatoken=exp=1627986887~acl=/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/*~hmac=839a3822ed7c83d3696740c150e3754c0dc8a34eea84bbb2041369902683aeb2&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IldBTVIiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTk2ODcsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3OTAwNDg3LCJ0ZXJyaXRvcnkiOiJUVyJ9.RMWvBhWRP_D62mhAONfyFCeOxjNLGY6vySt-fytrNEI"
[debug] Command-line config: ['--proxy', '127.0.0.1:10812', '--add-header', 'Referer:https://www.catchplay.com/|User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36', '--verbose', 'https://ols-ww100-cp.akamaized.net/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/JTdCJTIya2JpdCUyMiUzQTM2ODY0MDAwMCUyQyUyMnBsYXRmb3JtJTIyJTNBJTIyZGVza3RvcCUyMiUyQyUyMmRldmljZVR5cGUlMjIlM0ElMjJ3ZWIlMjIlMkMlMjJtb2RlbCUyMiUzQSUyMndpbmRvd3MlMjIlMkMlMjJvc1R5cGUlMjIlM0ElMjJjaHJvbWUlMjIlMkMlMjJvcyUyMiUzQSUyMjkyLjAuNDUxNSUyMiUyQyUyMmFwcCUyMiUzQSUyMjMuMCUyMiU3RA==/dash.mpd?cpatoken=exp=1627986887~acl=/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/*~hmac=839a3822ed7c83d3696740c150e3754c0dc8a34eea84bbb2041369902683aeb2&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IldBTVIiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTk2ODcsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3OTAwNDg3LCJ0ZXJyaXRvcnkiOiJUVyJ9.RMWvBhWRP_D62mhAONfyFCeOxjNLGY6vySt-fytrNEI']
[debug] Encodings: locale cp936, fs utf-8, out gbk, pref cp936
[debug] yt-dlp version 2021.08.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg n4.4-79-gde1132a891-20210731, ffprobe n4.4-79-gde1132a891-20210731
[debug] Proxy map: {'http': '127.0.0.1:10812', 'https': '127.0.0.1:10812'}
[debug] [generic] Extracting URL: https://ols-ww100-cp.akamaized.net/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/JTdCJTIya2JpdCUyMiUzQTM2ODY0MDAwMCUyQyUyMnBsYXRmb3JtJTIyJTNBJTIyZGVza3RvcCUyMiUyQyUyMmRldmljZVR5cGUlMjIlM0ElMjJ3ZWIlMjIlMkMlMjJtb2RlbCUyMiUzQSUyMndpbmRvd3MlMjIlMkMlMjJvc1R5cGUlMjIlM0ElMjJjaHJvbWUlMjIlMkMlMjJvcyUyMiUzQSUyMjkyLjAuNDUxNSUyMiUyQyUyMmFwcCUyMiUzQSUyMjMuMCUyMiU3RA==/dash.mpd?cpatoken=exp=1627986887~acl=/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/*~hmac=839a3822ed7c83d3696740c150e3754c0dc8a34eea84bbb2041369902683aeb2&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IldBTVIiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTk2ODcsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3OTAwNDg3LCJ0ZXJyaXRvcnkiOiJUVyJ9.RMWvBhWRP_D62mhAONfyFCeOxjNLGY6vySt-fytrNEI
[generic] *~hmac=839a3822ed7c83d3696740c150e3754c0dc8a34eea84bbb2041369902683aeb2&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IldBTVIiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTk2ODcsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3OTAwNDg3LCJ0ZXJyaXRvcnkiOiJUVyJ9: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] *~hmac=839a3822ed7c83d3696740c150e3754c0dc8a34eea84bbb2041369902683aeb2&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IldBTVIiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTk2ODcsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3OTAwNDg3LCJ0ZXJyaXRvcnkiOiJUVyJ9: Downloading webpage
[generic] *~hmac=839a3822ed7c83d3696740c150e3754c0dc8a34eea84bbb2041369902683aeb2&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IldBTVIiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTk2ODcsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3OTAwNDg3LCJ0ZXJyaXRvcnkiOiJUVyJ9: Extracting information
ERROR: No video formats found; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1179, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1204, in __extract_info
  File "yt_dlp\extractor\common.py", line 572, in extract
  File "yt_dlp\extractor\generic.py", line 2634, in _real_extract
  File "yt_dlp\extractor\common.py", line 1749, in _sort_formats
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

## Description

It seems yt-dlp can't read mpd url contains *

**Comment by pukkandan** [comment]
Try `yt-dlp -F --allow-unplayable-formats <rest of your command>`. If this works, then the URL has DRM and we can't support it.

If not, give a link that we can reproduce the issue with. The link given is inaccessible

**Comment by Ashish0804** [comment]
@Werner sorry it didn't even occur to me that it could be drm :facepalm: 
@pukkandan is right, it's DRM

Here's the output
```
(base) ashish@pop-os:~$ yt-dlp -F "https://ols-ww100-cp.akamaized.net/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/JTdCJTIya2JpdCUyMiUzQTM2ODY0MDAwMCUyQyUyMnBsYXRmb3JtJTIyJTNBJTIyZGVza3RvcCUyMiUyQyUyMmRldmljZVR5cGUlMjIlM0ElMjJ3ZWIlMjIlMkMlMjJtb2RlbCUyMiUzQSUyMndpbmRvd3MlMjIlMkMlMjJvc1R5cGUlMjIlM0ElMjJjaHJvbWUlMjIlMkMlMjJvcyUyMiUzQSUyMjkyLjAuNDUxNSUyMiUyQyUyMmFwcCUyMiUzQSUyMjMuMCUyMiU3RA==/dash.mpd?cpatoken=exp=1627984124~acl=/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/*~hmac=eafb26e5730e832e4dde9a7d793b9841524a600c0c8ab03d7a14524219f0b81b&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IlJGOEMiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTY5MjMsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3ODk3NzIzLCJ0ZXJyaXRvcnkiOiJUVyJ9.b141DLpi5fWkEz9r-6O7CsMhbBNfySj-7_EvuotUAWs" --add-header "Referer:https://www.catchplay.com/" --add-header "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36" --allow-unplayable-formats -v
[debug] Command-line config: ['-F', 'https://ols-ww100-cp.akamaized.net/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/JTdCJTIya2JpdCUyMiUzQTM2ODY0MDAwMCUyQyUyMnBsYXRmb3JtJTIyJTNBJTIyZGVza3RvcCUyMiUyQyUyMmRldmljZVR5cGUlMjIlM0ElMjJ3ZWIlMjIlMkMlMjJtb2RlbCUyMiUzQSUyMndpbmRvd3MlMjIlMkMlMjJvc1R5cGUlMjIlM0ElMjJjaHJvbWUlMjIlMkMlMjJvcyUyMiUzQSUyMjkyLjAuNDUxNSUyMiUyQyUyMmFwcCUyMiUzQSUyMjMuMCUyMiU3RA==/dash.mpd?cpatoken=exp=1627984124~acl=/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/*~hmac=eafb26e5730e832e4dde9a7d793b9841524a600c0c8ab03d7a14524219f0b81b&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IlJGOEMiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTY5MjMsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3ODk3NzIzLCJ0ZXJyaXRvcnkiOiJUVyJ9.b141DLpi5fWkEz9r-6O7CsMhbBNfySj-7_EvuotUAWs', '--add-header', 'Referer:https://www.catchplay.com/', '--add-header', 'User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36', '--allow-unplayable-formats', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.02 
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.11.0-7620-generic-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://ols-ww100-cp.akamaized.net/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/JTdCJTIya2JpdCUyMiUzQTM2ODY0MDAwMCUyQyUyMnBsYXRmb3JtJTIyJTNBJTIyZGVza3RvcCUyMiUyQyUyMmRldmljZVR5cGUlMjIlM0ElMjJ3ZWIlMjIlMkMlMjJtb2RlbCUyMiUzQSUyMndpbmRvd3MlMjIlMkMlMjJvc1R5cGUlMjIlM0ElMjJjaHJvbWUlMjIlMkMlMjJvcyUyMiUzQSUyMjkyLjAuNDUxNSUyMiUyQyUyMmFwcCUyMiUzQSUyMjMuMCUyMiU3RA==/dash.mpd?cpatoken=exp=1627984124~acl=/manifest/master/f194f10c-ca5a-11eb-b4fb-06f8654d7e14/*~hmac=eafb26e5730e832e4dde9a7d793b9841524a600c0c8ab03d7a14524219f0b81b&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IlJGOEMiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTY5MjMsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3ODk3NzIzLCJ0ZXJyaXRvcnkiOiJUVyJ9.b141DLpi5fWkEz9r-6O7CsMhbBNfySj-7_EvuotUAWs
[generic] *~hmac=eafb26e5730e832e4dde9a7d793b9841524a600c0c8ab03d7a14524219f0b81b&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IlJGOEMiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTY5MjMsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3ODk3NzIzLCJ0ZXJyaXRvcnkiOiJUVyJ9: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] *~hmac=eafb26e5730e832e4dde9a7d793b9841524a600c0c8ab03d7a14524219f0b81b&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IlJGOEMiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTY5MjMsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3ODk3NzIzLCJ0ZXJyaXRvcnkiOiJUVyJ9: Downloading webpage
[generic] *~hmac=eafb26e5730e832e4dde9a7d793b9841524a600c0c8ab03d7a14524219f0b81b&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IlJGOEMiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTY5MjMsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3ODk3NzIzLCJ0ZXJyaXRvcnkiOiJUVyJ9: Extracting information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for *~hmac=eafb26e5730e832e4dde9a7d793b9841524a600c0c8ab03d7a14524219f0b81b&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjU2YjlmMTkyLWFiY2ItNDFjNS1hNjI4LTM1NjcwMmNmMTcxOCIsInBhcmVudF9wcm9ncmFtX2lkIjoiOGJjYWNjMjMtNGViZC00ZjA1LWI3YjYtYzA0YTg4MDczYjU2IiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImFiZmEzOWVmLTMxZGYtNGVkYy1hNzA2LTdmMjRlZDM3ZmY5OCIsInJlcG9ydF9pZCI6IlJGOEMiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2MjgxNTY5MjMsInZpZGVvX2lkIjoiZjE4YmFhNTItY2E1YS0xMWViLWI0ZmItMDZmODY1NGQ3ZTE0IiwiaXNzIjoiQXNpYXBsYXktT0F1dGgtU2VydmVyIiwiaWF0IjoxNjI3ODk3NzIzLCJ0ZXJyaXRvcnkiOiJUVyJ9:
ID  EXT RESOLUTION |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    MORE INFO
--- --- ---------- - ----- ----- - ----------- ----- --------- ---- ------- -----------------------------
7-0 m4a audio only |  134k dash  |                   mp4a.40.2 134k 48000Hz [zh-TW], DASH audio, m4a_dash
7-1 m4a audio only |  136k dash  |                   mp4a.40.2 136k 48000Hz [zh-TW], DASH audio, m4a_dash
4-0 mp4 854x480    | 1318k dash  | avc1.4d4029 1318k                        DASH video, mp4_dash
4-1 mp4 854x480    | 1355k dash  | avc1.4d4029 1355k                        DASH video, mp4_dash
2-0 mp4 1280x720   | 2242k dash  | avc1.4d4029 2242k                        DASH video, mp4_dash
2-1 mp4 1280x720   | 2311k dash  | avc1.4d4029 2311k                        DASH video, mp4_dash
6-0 mp4 1280x720   | 3624k dash  | avc1.4d4029 3624k                        DASH video, mp4_dash
6-1 mp4 1280x720   | 3853k dash  | avc1.4d4029 3853k                        DASH video, mp4_dash
3-0 mp4 1920x1080  | 4719k dash  | avc1.4d4029 4719k                        DASH video, mp4_dash
3-1 mp4 1920x1080  | 4936k dash  | avc1.4d4029 4936k                        DASH video, mp4_dash
5-0 mp4 1920x1080  | 7030k dash  | avc1.4d4029 7030k                        DASH video, mp4_dash
5-1 mp4 1920x1080  | 7095k dash  | avc1.4d4029 7095k                        DASH video, mp4_dash

```

**Comment by fstirlitz** [comment]
@pukkandan Maybe yt-dlp should display a warning when DRM-encumbered streams are detected instead of ignoring them silently? This way you can avoid spurious reports like this in the future.

**Comment by nyuszika7h** [comment]
Well, when the video has both DRM and non-DRM streams, it's better to just ignore them by default and let it pick a non-DRM format.

Either way, the few (or maybe not so few anymore) people who know how to decrypt certain DRM streams can just use `--allow-unplayable-formats`. For the average user, it would be useless to download a DRM-protected video and they would probably just not read the warning and complain that the video won't play.
