### ISSUE TITLE
FIX-mediasetinfinity.mediaset

### ISSUE THREAD

**Issue by Heros99** [yt-dlp/yt-dlp#6097]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italia

### Provide a description that is worded well enough to be understood

 Unsupported URL

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-Uv', '--cookies-from-browser', 'firefox', 'https://mediasetinfinity.mediaset.it/video/isegretidelranchmaledetto2/ep1-la-fossa-di-homestad-two_Y311967901000101']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched/yt-dlp version 2023.01.26.19419 [c913e41] (win_exe)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109429-g8ad988ac37-20221217 (setts), ffprobe N-109429-g8ad988ac37-20221217
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\House\AppData\Roaming\Mozilla\Firefox\Profiles\5jzz5ux9.default-release\cookies.sqlite"
[Cookies] Extracted 2592 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1761 extractors
[debug] Fetching release info: https://api.github.com/repos/ytdl-patched/yt-dlp/releases/latest
Latest version: 2023.01.26.19419, Current version: 2023.01.26.19419
yt-dlp is up to date (2023.01.26.19419)
[generic] Extracting URL: https://mediasetinfinity.mediaset.it/video/isegretidelranchmaledetto2/ep1-la-fossa-di-homestad-two_Y311967901000101
[generic] ep1-la-fossa-di-homestad-two_Y311967901000101: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ep1-la-fossa-di-homestad-two_Y311967901000101: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://mediasetinfinity.mediaset.it/video/isegretidelranchmaledetto2/ep1-la-fossa-di-homestad-two_Y311967901000101
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 682, in extract
  File "yt_dlp\extractor\generic.py", line 2523, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://mediasetinfinity.mediaset.it/video/isegretidelranchmaledetto2/ep1-la-fossa-di-homestad-two_Y311967901000101
```

**Comment by bashonly** [comment]
I think the GUID regex just needs to be adjusted:
```diff
diff --git a/yt_dlp/extractor/mediaset.py b/yt_dlp/extractor/mediaset.py
index 1fa529914..a842f1cf0 100644
--- a/yt_dlp/extractor/mediaset.py
+++ b/yt_dlp/extractor/mediaset.py
@@ -15,7 +15,7 @@
 
 class MediasetIE(ThePlatformBaseIE):
     _TP_TLD = 'eu'
-    _GUID_RE = r'F[0-9A-Z]{15}'
+    _GUID_RE = r'[FY][0-9A-Z]{15}'
     _VALID_URL = rf'''(?x)
                     (?:
                         mediaset:|
```
I'm geo-blocked though so I can't properly test

**Comment by nixxo** [comment]
It's behind paywall so almost certainly DRM protected, but you are correct, the regex should be charged.

**Comment by Heros99** [comment]
> It's behind paywall so almost certainly DRM protected, but you are correct, the regex should be charged.

thanks a lot for your work

**Comment by bashonly** [comment]
> It's behind paywall so almost certainly DRM protected

OP's example URL confirmed as DRM-protected

**Comment by nicovoni** [comment]
`ERROR: [Mediaset] F312603203012702: This content is not available in your location. You might want to use a VPN or a proxy server (with --proxy) to workaround.`

Is this error related to the issue in question?

**Comment by bashonly** [comment]
@nicovoni No. It just means the content is geo-restricted
