### ISSUE TITLE
LinkedIn download returns "Unsupported URL" error

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#6104]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Hi, I'm trying the dump the JSON data for the followin LinkedIn URL and it returns an error saying "Unsupported URL".

https://www.linkedin.com/feed/update/urn:li:activity:7016901149999955968?utm_source=share&utm_medium=member_desktop

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-J', 'https://www.linkedin.com/feed/update/urn:li:activity:7016901149999955968?utm_source=share']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.7.5 (CPython x86_64 64bit) - Linux-4.15.0-135-generic-x86_64-with-Ubuntu-18.04-bionic (OpenSSL 1.1.1  11 Sep 2018, glibc 2.26)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.05.30, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://www.linkedin.com/feed/update/urn:li:activity:7016901149999955968?utm_source=share
[generic] urn:li:activity:7016901149999955968?utm_source=share: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] urn:li:activity:7016901149999955968?utm_source=share: Extracting information
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[generic] Extracting URL: https://www.linkedin.com/embed/feed/update/urn:li:activity:7016901149999955968?compact=true
[generic] urn:li:activity:7016901149999955968?compact=true: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] urn:li:activity:7016901149999955968?compact=true: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.linkedin.com/embed/feed/update/urn:li:activity:7016901149999955968?compact=true
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2523, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.linkedin.com/embed/feed/update/urn:li:activity:7016901149999955968?compact=true

null
```

**Comment by dirkf** [comment]
The URL isn't matched, but the page structure is handled by the `LinkedInIE` extractor, if its `_VALID_URL` is modified by changing `/posts/` to `/(?:embed/)?(?:posts|feed/update)/`.

See https://github.com/ytdl-org/youtube-dl/issues/31501.

**Comment by ahm750** [comment]
I modified the URL by adding "/embed/" and the resulting page contains the <video> tag. Perhaps the extractor must be updated to handle this URL format?
