### ISSUE TITLE
If media file format is WEBM and no audio OR video format is selected, then --merge-output-format is ignored and --embed-thumbnail FAILS

### ISSUE THREAD

**Issue by AndrePuls** [yt-dlp/yt-dlp#6109]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

If media file format is **WEBM** and **no audio OR video format** is selected, **--merge-output-format** is ignored and **--embed-thumbnail** FAILS

### Command:
`yt-dlp --verbose --embed-thumbnail --format "598" -o "%(id)s.f-%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=_lyIjUrJ4f0"`

Downloads thumbnail as .webp, downloads video as .webm, converts .webp to .png, then FAILS with ExitCode=1:
> ERROR: Postprocessing: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov

(Verbose Output see "Complete Verbose Output")

It also fails, if only one audio format and no video is selected, e.g. --format "bestaudio"

It also fails, if --merge-output-format="mp4" is set:
`yt-dlp --verbose --embed-thumbnail --format "598" --merge-output-format="mp4" -o "%(id)s.f-%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=_lyIjUrJ4f0"`
> ERROR: Postprocessing: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov

However, it works as expected when video AND audio format is selected. yt-dlc then shows a warning and selects .mkv: 
`yt-dlp --verbose --embed-thumbnail --format "bestvideo+bestaudio" -o "%(id)s.f-%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=_lyIjUrJ4f0"`

Downloads thumbnail as .webp, downloads video and audio as .webm, converts .webp to .png, then muxes everything into .mkv:
> WARNING: webm doesn't support embedding a thumbnail, mkv will be used

When selecting MP4 as media file format --embed-thumbnail and --merge-output-format works as expected (

-----

### Additional Tests:
- Fails (--merge-output-format="mp4" is ignored):
`yt-dlp --verbose --embed-thumbnail --format "bestvideo" --merge-output-format="mp4" -o "%(id)s.f-%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=_lyIjUrJ4f0"`
> ERROR: Postprocessing: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov

- Fails (downloads video, BUT ignores --merge-output-format="mkv" and outputs .webm, no error/warning):
`yt-dlp --verbose --format "315" --merge-output-format="mkv" -o "%(id)s.f-%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=_lyIjUrJ4f0"`
> [download] Destination: _lyIjUrJ4f0.f-315.webm

- Works (downloads video only, output is .webm):
`yt-dlp --verbose --format "bestvideo" -o "%(id)s.f-%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=_lyIjUrJ4f0"`

- Works (downloads video and audio, merges into .mkv):
`yt-dlp --verbose --format "bestvideo+worstaudio" -o "%(id)s.f-%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=_lyIjUrJ4f0"`

- Works (output is .mp4):
`yt-dlp --verbose --format "bestvideo+worstaudio" --merge-output-format="mp4" -o "%(id)s.f-%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=_lyIjUrJ4f0"`

-----

### Format List for https://www.youtube.com/watch?v=_lyIjUrJ4f0:
```
====================================================================
| Electric Sheep Flame Fractals [Generation:248 ID:00227 to        |
| 00253] [8K 4K HD 60FPS EDGE]                                     |
| ---------------------------------------------------------------- |
| Uploader: Aquaritek                                              |
| Upload Date: 2022-09-25                                          |
| Duration: 00:00:10                                               |
| Views:7/Like:0/Dislike:0/                                        |
| https://www.youtube.com/watch?v=_lyIjUrJ4f0                      |
====================================================================
| sb0 | storyboard |      48x27 |           |              | mhtml |
| 251 |     medium | audio only |   4,71 KB |     3 kBit/s |  webm |
| 598 |       144p |    256x144 |  29,85 KB |    24 kBit/s |  webm |
| 597 |       144p |    256x144 |  36,24 KB |    29 kBit/s |   mp4 |
| 599 |   ultralow | audio only |  38,80 KB |    31 kBit/s |   m4a |
| 139 |        low | audio only |  61,05 KB |    49 kBit/s |   m4a |
| 278 |       144p |    256x144 |  74,87 KB |    61 kBit/s |  webm |
| 160 |       144p |    256x144 |  97,75 KB |    80 kBit/s |   mp4 |
| 242 |       240p |    426x240 | 152,33 KB |   124 kBit/s |  webm |
| 140 |     medium | audio only | 159,66 KB |   130 kBit/s |   m4a |
| 133 |       240p |    426x240 | 219,52 KB |   179 kBit/s |   mp4 |
| 243 |       360p |    640x360 | 311,82 KB |   255 kBit/s |  webm |
| 134 |       360p |    640x360 | 514,60 KB |   421 kBit/s |   mp4 |
|  18 |       360p |    640x360 |           |   551 kBit/s |   mp4 |
| 244 |       480p |    854x480 | 680,60 KB |   557 kBit/s |  webm |
| 135 |       480p |    854x480 |   1,05 MB |   878 kBit/s |   mp4 |
| 247 |       720p |   1280x720 |   2,07 MB |  1736 kBit/s |  webm |
| 136 |       720p |   1280x720 |   2,42 MB |  2026 kBit/s |   mp4 |
|  22 |       720p |   1280x720 |           |  2155 kBit/s |   mp4 |
| 302 |     720p60 |   1280x720 |   3,16 MB |  2652 kBit/s |  webm |
| 298 |     720p60 |   1280x720 |   3,69 MB |  3093 kBit/s |   mp4 |
| 303 |    1080p60 |  1920x1080 |   6,46 MB |  5418 kBit/s |  webm |
| 299 |    1080p60 |  1920x1080 |   7,18 MB |  6026 kBit/s |   mp4 |
| 308 |    1440p60 |  2560x1440 |  15,57 MB | 13062 kBit/s |  webm |
| 315 |    2160p60 |  3840x2160 |  32,16 MB | 26981 kBit/s |  webm |
====================================================================
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --verbose --embed-thumbnail --format "598" -o "%(id)s.f-%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=_lyIjUrJ4f0"
[debug] Command-line config: ['--verbose', '--embed-thumbnail', '--format', '598', '-o', '%(id)s.f-%(format_id)s.%(ext)s', 'https://www.youtube.com/watch?v=_lyIjUrJ4f0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.10.7 (CPython aarch64 64bit) - Linux-5.19.0-1011-raspi-aarch64-with-glibc2.36 (OpenSSL 3.0.5 5 Jul 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=_lyIjUrJ4f0
[youtube] _lyIjUrJ4f0: Downloading webpage
[youtube] _lyIjUrJ4f0: Downloading android player API JSON
[debug] Loading youtube-nsig.4248d311 from cache
[debug] [youtube] Decrypted nsig cbx3qOnByjDdXQZ => AUdD5oe5i0kbcA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] _lyIjUrJ4f0: Downloading 1 format(s): 598
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: _lyIjUrJ4f0.f-598.webp
[debug] Invoking http downloader on "https://rr2---sn-5hne6nzd.googlevideo.com/videoplayback?expire=1674951252&ei=9GXVY6bfOs6FgAfgpq6IDg&ip=2a02%3A908%3Ae39%3A3a60%3A%3A84&id=o-AOKcqFufnQkeVMq5xPFTwq6H0T5jl1fm_ib7Wa4_x-7q&itag=598&source=youtube&requiressl=yes&mh=ZV&mm=31%2C29&mn=sn-5hne6nzd%2Csn-5hnekn7z&ms=au%2Crdu&mv=m&mvi=2&pl=44&initcwndbps=1698750&spc=H3gIhhX2JkzP6sV6y76Z5pYzGrPTaxA&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=30569&dur=10.000&lmt=1664090359206141&mt=1674929610&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&txp=6219224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAM8UiEI_lbiN_Qz1dYry-NipslfWoh-fQD6uNEtxEBCuAiA_0yAfLt06kGQZsDOCQYQMbPp4kk0e_NMnbujOBqgBcg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgA9DlKZ6r7BaFpo_CUQhqpRbqrxCSgm2ZsfTdnTYF7oUCIQDc8jxH0yO_M9s_fez_MFlqu8fexjy5gF8IL7BRYAtERw%3D%3D"
[download] Destination: _lyIjUrJ4f0.f-598.webm
[download] 100% of   29.85KiB in 00:00:00 at 61.90KiB/s
[ThumbnailsConvertor] Converting thumbnail "_lyIjUrJ4f0.f-598.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i file:_lyIjUrJ4f0.f-598.webp -update 1 -movflags +faststart file:_lyIjUrJ4f0.f-598.png
ERROR: Postprocessing: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3312, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3491, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3473, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3451, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/embedthumbnail.py", line 216, in run
    raise EmbedThumbnailPPError('Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov')
yt_dlp.postprocessor.embedthumbnail.EmbedThumbnailPPError: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov


yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.10.7 (CPython aarch64 64bit) - Linux-5.19.0-1011-raspi-aarch64-with-glibc2.36 (OpenSSL 3.0.5 5 Jul 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
```

**Comment by bashonly** [comment]
from the readme:
```
--merge-output-format FORMAT    Containers that may be used when merging
                                formats, separated by "/", e.g. "mp4/mkv".
                     -------->  Ignored if no merge is required. (currently
                                supported: avi, flv, mkv, mov, mp4, webm)
```
so the option behaves as expected, and the error message given is appropriate:
> ERROR: Postprocessing: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov

solution: you can use `--remux-video`
```
--remux-video FORMAT            Remux the video into another container if
                                necessary (currently supported: avi, flv,
                                gif, mkv, mov, mp4, webm, aac, aiff, alac,
                                flac, m4a, mka, mp3, ogg, opus, vorbis,
                                wav). If target container does not support
                                the video/audio codec, remuxing will fail.
                                You can specify multiple rules; e.g.
                                "aac>m4a/mov>mp4/mkv" will remux aac to m4a,
                                mov to mp4 and anything else to mkv
```
