### ISSUE TITLE
Vimeo: can't download a playlist (The URL must be suitable for the extractor)

### ISSUE THREAD

**Issue by slavalamp** [yt-dlp/yt-dlp#6127]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I'm trying to download [this playlist](https://vimeo.com/showcase/3145604) and get an error. Downloading single videos or a whole channel seems to work fine

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-subs', '--embed-subs', '--cookies', 'cookies.txt', 'https://vimeo.com/showcase/3145604']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-5.15.86-x86_64-with-glibc2.35 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[vimeo:album] Extracting URL: https://vimeo.com/showcase/3145604
[vimeo:album] 3145604: Downloading JSON metadata
[vimeo:album] 3145604: Downloading JSON metadata
[download] Downloading playlist: Project Voicebend Episodes
[vimeo:album] 3145604: Downloading page 1
ERROR: The URL must be suitable for the extractor
Traceback (most recent call last):
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1599, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1728, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1803, in __process_playlist
    entries = resolved_entries = list(entries)
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/utils.py", line 788, in _iter
    for x in iterable:
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/utils.py", line 3026, in get_requested_items
    self.ydl._match_entry(entry, incomplete=True, silent=True)
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1433, in _match_entry
    reason = check_filter()
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1377, in check_filter
    elif _type in ('url', 'url_transparent') and not try_call(
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/utils.py", line 3251, in try_call
    val = f(*args, **kwargs)
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1378, in <lambda>
    lambda: self.get_info_extractor(info_dict['ie_key']).is_single_video(info_dict['url'])):
  File "/nix/store/g8l0rsavy1zf1lx762dqsps7q6rmk8v7-python3.10-yt-dlp-2023.1.6/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 3492, in is_single_video
    assert cls.suitable(url), 'The URL must be suitable for the extractor'
AssertionError: The URL must be suitable for the extractor
```

**Comment by bashonly** [comment]
dev notes:

the playlist JSON response yields a link not recognized as valid by `VimeoIE`
```json
        {
            "uri": "/videos/258705797",
            "link": "https://vimeo.com/user26785108/newspiritualguide"
        },
```
in a browser `https://vimeo.com/user26785108/newspiritualguide` redirects to `https://vimeo.com/258705797`

**Comment by LeoniePhiline** [comment]
@janTasija You can try if https://github.com/LeoniePhiline/showcase-dl works for you. 
It takes the showcase apart and downloads each video individually.

Note that you might still get failures before #6203 is merged. In that case, the PR patch as detailed in https://github.com/LeoniePhiline/showcase-dl/issues/1#issuecomment-1425766630.
