### ISSUE TITLE
Hope abematv plugin can be customized `_USERTOKEN`

### ISSUE THREAD

**Issue by Ukenn2112** [yt-dlp/yt-dlp#6142]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/abematv.py#L302-L321

When I download a video that requires login to be allowed to download, I don't want to perform login every time I use it, I want to be able to set `_USERTOKEN` to authorize login directly and on abema `_USERTOKEN` doesn't seem to have an expiration date, once obtained it can be reused all the time, 
I have tried using `http_headers` to set `authorization: Bearer _USERTOKEN` found that it does not work, hope to add this feature

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```txt
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip) API
[debug] params: {'verbose': True,'outtmpl': 'abema/%(series)s - S01E%(episode_number)02d - Abema.%(ext)s','external_downloader': 'aria2c', 'http_headers': {'authorization': 'Bearer ey********'}, 'compat_opts': set()}
[debug] Python 3.9.13 (CPython arm64 64bit) - macOS-13.0.1-arm64-arm-64bit (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-None, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[AbemaTV] Extracting URL: https://abema.tv/video/episode/19-149_s1_p2
[AbemaTV] Authorizing
[AbemaTV] 19-149_s1_p2: Downloading webpage
[AbemaTV] 19-149_s1_p2: Checking playability
[AbemaTV] 19-149_s1_p2: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 19-149_s1_p2: Downloading 1 format(s): 5300
[debug] Invoking hlsnative downloader on "https://vod-abematv.akamaized.net/program/19-149_s1_p2/1080/playlist.m3u8?aver=1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 241
[download] Destination: abema/お兄ちゃんはおしまい！ - S01E02 - Abema.mp4
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --http-accept-gzip=true --file-allocation=none -x16 -j16 -s16 --allow-overwrite=true --allow-piece-length-change=true --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-us,en;q=0.5' --header 'Sec-Fetch-Mode: navigate' --header 'Authorization: Bearer eyJhb*************' --dir ./abema/ --auto-file-renaming=false --file-allocation=none --uri-selector=inorder -i './abema/お兄ちゃんはおしまい！ - S01E02 - Abema.mp4.part.frag.urls'
[DL:0B][#8b03fd 0B/0B][#3c0792 0B/0B][#36f2c3 0B/0B][#66f133 0B/0B][#d64d27 0B/0B](+11)[AbemaTV] Fetching media token                                                                   
[AbemaTV] Requesting playback license
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 807, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 807, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1599, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1658, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2772, in process_video_result
    self.process_info(new_info)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3236, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2959, in dl
    return fd.download(name, new_info, subtitle)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/downloader/hls.py", line 258, in real_download
    return fd.real_download(filename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/downloader/external.py", line 49, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/downloader/external.py", line 271, in _call_downloader
    return super()._call_downloader(tmpfilename, info_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/downloader/external.py", line 169, in _call_downloader
    dest.write(decrypt_fragment(fragment, src.read()))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/downloader/fragment.py", line 363, in decrypt_fragment
    decrypt_info['KEY'] = decrypt_info.get('KEY') or _get_key(info_dict.get('_decryption_key_url') or decrypt_info['URI'])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/downloader/fragment.py", line 353, in _get_key
    _key_cache[url] = self.ydl.urlopen(self._prepare_url(info_dict, url)).read()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/abematv.py", line 142, in abematv_license_open
    response_data = self._get_videokey_from_ticket(ticket)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/abematv.py", line 117, in _get_videokey_from_ticket
    license_response = self.ie._download_json(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1034, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 998, in download_handle
    res = self._download_webpage_handle(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 868, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 825, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ukenn/Downloads/Channel/utils/abema.py", line 16, in <module>
    ydl.download("https://abema.tv/video/episode/19-149_s1_p2")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3358, in download
    self.__download_wrapper(self.extract_info)(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3333, in wrapper
    res = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1520, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1012, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 952, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
Have you tried using logged in cookies?

cc @Lesmiscore

**Comment by Lesmiscore** [comment]
extractors for Abema doesn't use cookies at all

**Comment by Ukenn2112** [comment]
> extractors for Abema don't use cookies at all

Yes, I see that Abema API uses Authorization bearer for user authorization

Since Abema sends email alerts every time I log in, I'd like to be able to prevent logging in every time I use it by setting the authorization header

**Comment by pukkandan** [comment]
For devs - few ideas how this could be supported:
* add a special "username" similar to soundcloud (`ouath`) / fancode (`refresh`).
* Abuse `--twofactor`
* Add a new switch `--auth-token` and migrate soundcloud/fancode to use this as well

Opinions?

**Comment by Grub4K** [comment]
I think the last one is the most clean.

Maybe some generic place to store an auth token can be implemented (`InfoExtractor._auth_token?`) so `--auth-token` could be used instead of `cookies` for other extractors automatically as well?

**Comment by Lesmiscore** [comment]
+1 for the last one, since it's more straightforward than what souldcloud/fancode are currently doing for the current situation

**Comment by bashonly** [comment]
I'm also in favor of `--auth-token`. It's the simplest solution and think it will prove to be useful with other sites down the road.

**Comment by pukkandan** [comment]
> Maybe some generic place to store an auth token can be implemented (`InfoExtractor._auth_token`?) so `--auth-token` could be used instead of `cookies` for other extractors automatically as well?

Not all extractors use that variable name, nor do all of them check whether it exists first. So the feasibility of this idea will need to be investigated

---

As for just adding the option, there are a few things to consider:
1. It shouldn't appear in verbose logs similar to `--password`
2. Some way to pass it without adding to history. Maybe `--auth -`?
3. We need some way to pass token per site.
	* We could use `SITE:TOKEN` syntax
	* Or, something similar to `--netrc`? Maybe even just add new `machine`s to netrc? Either way, this would cover (2) too

---

Btw, Another solution to OP's problem is to just cache the token against username. Some other extractors do this already

**Comment by Lesmiscore** [comment]
After #6216, yt-dlp now caches user token as long as credentials are supplied, in any supported method (--username/--password and .netrc both works)
If you wish to supply your own user token, make a cache file by yourself
Create `abematv/<username or email>.json` file in yt-dlp's cache directory (in Linux, `~/.cache/yt-dlp/`), with contents like `{"yt-dlp_version": "2023.01.06", "data": "eyJh..."}`
Make sure to use the same username what you used as filename of the JSON file

**Comment by Ukenn2112** [comment]
> After #6216, yt-dlp now caches user token as long as credentials are supplied, in any supported method (--username/--password and .netrc both work) If you wish to supply your own user token, make a cache file by yourself. Here's how: Create `abematv/<username or email>.json` file in yt-dlp's cache directory (in Linux, `~/.cache/yt-dlp/`), with contents like `{"yt-dlp_version": "2023.01.06", "data": "eyJh..."}` (replace `eyJh...` with your own token) Make sure to use the same username what you used as filename of the JSON file

Thank you for submitting the code. I have a question regarding the working process of this feature. Does it work in a way where once a user logs in using their username and password on this computer, the login token for that username will be cached and stored on the computer, allowing future use of the same username to bypass the login process and directly use the cached token?

**Comment by pukkandan** [comment]
> Does it work in a way where once a user logs in using their username and password on this computer, the login token for that username will be cached and stored on the computer, allowing future use of the same username to bypass the login process and directly use the cached token?

Yes

**Comment by Ukenn2112** [comment]
> Yes. When the token expires, it's automatically refreshed
Thank you for your reply, I'm looking forward to the release.
