### ISSUE TITLE
Broken Cryptodome Import

### ISSUE THREAD

**Issue by dallemon** [yt-dlp/yt-dlp#6185]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

yt-dlp no longer works after building with pyinstall, tested in linux and windows

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Traceback (most recent call last):
  File "yt_dlp\compat\compat_utils.py", line 50, in __getattribute__
  File "yt_dlp\compat\compat_utils.py", line 72, in __getattr__
AttributeError: module yt_dlp.dependencies.Cryptodome.Cipher has no attribute AES

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp\__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp\cookies.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp\aes.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp\dependencies\__init__.py", line 76, in <module>
  File "yt_dlp\compat\compat_utils.py", line 57, in __getattribute__
  File "yt_dlp\compat\compat_utils.py", line 72, in __getattr__
AttributeError: module yt_dlp.dependencies.Cryptodome.Cipher has no attribute AES
[22924] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by pukkandan** [comment]
I can't reproduce. What commit are you on? How did you compile it? Is the log posted of `yt-dlp -v`? Pls also provide output of `pip list`

**Comment by pukkandan** [comment]
Does it work uncompiled? Can you post verbose of that?

**Comment by dallemon** [comment]
I pretty much followed instructions from readme.
First created venv
Then ran the following
```
python3 -m pip install -U pyinstaller -r requirements.txt
python3 devscripts/make_lazy_extractors.py
python3 pyinst.py
```
I'm on this commit
`commit f40e32fb1ac67be5bdbc8e32a3c235abfc4be260 (HEAD -> master, origin/master, origin/HEAD)`

Can't post any useful log as app crashes even without any args.

List of packages
```
Package                   Version
------------------------- ---------
altgraph                  0.17.3
Brotli                    1.0.9
certifi                   2022.12.7
mutagen                   1.46.0
pip                       23.0
pycryptodomex             3.17
pyinstaller               5.7.0
pyinstaller-hooks-contrib 2022.15
setuptools                65.6.3
websockets                10.4
wheel                     0.38.4
```

**Comment by dallemon** [comment]
```
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd2508] (source)
[debug] Git HEAD: 493c14529
[debug] Python 3.11.1 (CPython x86_64 64bit) - Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with (OpenSSL 3.0.7 1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1766 extractors

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

**Comment by nicolaasjan** [comment]
Same here on Windows 10 with Python 3.11.1.
Running `yt-dlp.cmd -v` gives no error.

On Linux there is no issue with the compiled `yt-dlp`:

```
./yt-dlp --ignore-config -v
[debug] Command-line config: ['--ignore-config', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.08 [f40e32fb1] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-137-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-109587-gfc263f073e-Nico-20230113 (fdk,setts), ffprobe N-109587-gfc263f073e-Nico-20230113, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4, xattr-0.9.6
[debug] Proxy map: {}
[debug] Loaded 1766 extractors

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

```

**Comment by dallemon** [comment]
so, replacing the package pycryptodomex with pycryptodome resolves the issue.
also i had a closer read of my hotfix and it's quite ugly :)

however, with both packages installed the error message is slightly better
```
Traceback (most recent call last):
  File "yt_dlp/compat/compat_utils.py", line 50, in __getattribute__
    ret = super().__getattribute__(attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "yt_dlp/compat/compat_utils.py", line 72, in __getattr__
    raise AttributeError(f'module {parent.__name__} has no attribute {attr}')
AttributeError: module yt_dlp.dependencies.Cryptodome.Cipher has no attribute AES

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp/__main__.py", line 14, in <module>
    import yt_dlp
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp/__init__.py", line 18, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp/cookies.py", line 18, in <module>
    from .aes import (
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp/aes.py", line 5, in <module>
    from .dependencies import Cryptodome
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp/dependencies/__init__.py", line 76, in <module>
    Cryptodome_AES = Cryptodome.Cipher.AES if Cryptodome else None
                     ^^^^^^^^^^^^^^^^^^^^^
  File "yt_dlp/compat/compat_utils.py", line 57, in __getattribute__
    ret = getter(attr)
          ^^^^^^^^^^^^
  File "yt_dlp/compat/compat_utils.py", line 72, in __getattr__
    raise AttributeError(f'module {parent.__name__} has no attribute {attr}')
AttributeError: module yt_dlp.dependencies.Cryptodome.Cipher has no attribute AES
[3149] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by dallemon** [comment]
pushed a new commit with a cleaner fix :)

**Comment by Vangelis66** [comment]
Greetings 😄 !

My building environment relies on `CPython 3.7.16 (32-bit)`, on a `32-bit` **Windows** OS :wink: ... 

`python -m pip list` reports: 
```
Package                   Version
------------------------- ---------
altgraph                  0.17.3
Brotli                    1.0.9
certifi                   2022.12.7
future                    0.18.3
importlib-metadata        6.0.0
mutagen                   1.46.0
pefile                    2023.2.7
pip                       23.0
pycryptodomex             3.17
pyinstaller               5.7.0
pyinstaller-hooks-contrib 2022.15
pywin32-ctypes            0.2.0
setuptools                67.2.0
typing_extensions         4.4.0
websockets                10.4
wheel                     0.38.4
zipp                      3.12.1
```
When I compile source snapshot `yt-dlp-2023.01.06-26-git-20230208-g754c84e` (immediately **previous** to f6a765c), the compilation (of course) succeeds, the resultant `yt-dlp_x86.exe` binary has a **file size** of ca. **11.7 MiB** ...

OTOH, when I compile latest `master` HEAD, snapshot `yt-dlp-2023.01.06-36-git-20230208-gf14c233`, the compilation (now) succeeds (due to recent [fix](https://github.com/yt-dlp/yt-dlp/commit/acb1042a9ffa8769fe691beac1011d6da1fcf321)), however the **file size** of the resultant `yt-dlp_x86.exe` binary comes at ca. **13.2 MiB**, i.e. a significant **12.82**% size **increase** (I can provide `PyInstaller` compilation logs, if asked) ... 

Is that **something to be expected** because of f6a765c, or are we now packing "more" than needed? ...

Thanks in advance 😺 ...

**Comment by pukkandan** [comment]
We are in fact packing more than needed, i.e. all of pycryptodome instead of just the submodules we want. This is done so we don't have to explicitly define what we want and what we don't. I don't think a 1.5M increase is worth reverting it over.

If you are really concerned about the filesize, you'd have to manually maintain a list

```diff
diff --git a/yt_dlp/__pyinstaller/hook-yt_dlp.py b/yt_dlp/__pyinstaller/hook-yt_dlp.py
index 66d1b6369..f6ae075dc 100644
--- a/yt_dlp/__pyinstaller/hook-yt_dlp.py
+++ b/yt_dlp/__pyinstaller/hook-yt_dlp.py
@@ -19,8 +19,17 @@ def _pycryptodome_module():

 def _hidden_imports():
     yield 'yt_dlp.compat._legacy'
-    for m in [_pycryptodome_module(), 'websockets']:
+    for m in ['websockets']:
         yield from collect_submodules(m)
+    yield from [
+        'Cryptodome',
+        'Cryptodome.Cipher.AES',
+        'Cryptodome.Cipher.Blowfish',
+        'Cryptodome.Cipher.PKCS1_OAEP',
+        'Cryptodome.Hash.CMAC',
+        'Cryptodome.Hash.SHA1',
+        'Cryptodome.PublicKey.RSA',
+    ]
     # These are auto-detected, but explicitly add them just in case
     yield from ('mutagen', 'brotli', 'certifi')
```



PS: Even previously, we are packing some modules that we don't need in `base_library.zip`

**Comment by pukkandan** [comment]
In theory, we could have a static analyzer that finds the modules used
```diff
diff --git a/yt_dlp/__pyinstaller/hook-yt_dlp.py b/yt_dlp/__pyinstaller/hook-yt_dlp.py
index 66d1b6369..4bba39804 100644
--- a/yt_dlp/__pyinstaller/hook-yt_dlp.py
+++ b/yt_dlp/__pyinstaller/hook-yt_dlp.py
@@ -1,8 +1,30 @@
+import ast
+import os
 import sys
+from pathlib import Path

 from PyInstaller.utils.hooks import collect_submodules


+def _attribute_accesses(node, name, path=()):
+    if isinstance(node, ast.Attribute):
+        path = [*path, node.attr]
+        if isinstance(node.value, ast.Name) and node.value.id == name:
+            yield path[::-1]
+    for child in ast.iter_child_nodes(node):
+        yield from _attribute_accesses(child, name, path)
+
+
+def _collect_used_submodules(name, level):
+    for dirpath, _, filenames in os.walk(Path(__file__).parent.parent):
+        for filename in filenames:
+            if not filename.endswith('.py'):
+                continue
+            with open(Path(dirpath) / filename, encoding='utf8') as f:
+                for submodule in _attribute_accesses(ast.parse(f.read()), name):
+                    yield '.'.join(submodule[:level])
+
+
 def _pycryptodome_module():
     try:
         import Cryptodome  # noqa: F401
@@ -19,11 +41,17 @@ def _pycryptodome_module():

 def _hidden_imports():
     yield 'yt_dlp.compat._legacy'
-    for m in [_pycryptodome_module(), 'websockets']:
-        yield from collect_submodules(m)
+    yield from collect_submodules('websockets')
+
+    crypto = _pycryptodome_module()
+    for sm in set(_collect_used_submodules('Cryptodome', 2)):
+        yield f'{crypto}.{sm}'
+
     # These are auto-detected, but explicitly add them just in case
     yield from ('mutagen', 'brotli', 'certifi')


 hiddenimports = list(_hidden_imports())
+print(f'Adding imports: {hiddenimports}')
+
 excludedimports = ['youtube_dl', 'youtube_dlc', 'test', 'ytdlp_plugins', 'devscripts']
```
But not sure if it's worth it

**Comment by CharlesMengCA** [comment]
The code is fast. Considering the amount of users. download bandwidth and disk space saved in total. It is worth it.

**Comment by pukkandan** [comment]
My reluctance is because I'm not very familiar with ast. Not sure if this code will cause any bugs 😓

**Comment by CharlesMengCA** [comment]
Built with it. no bugs found so far.

**Comment by pukkandan** [comment]
I decided to merge it for now. But I may revert if it ends up being difficult to maintain in future

**Comment by Vangelis66** [comment]
Is the recent breakage of the "**Automated Daily Releases**" I reported **[here](https://github.com/yt-dlp/yt-dlp/issues/1839#issuecomment-1426917779)** somehow related to the "fixes" for **this issue** or, in fact, to f6a765ceb59c55aea06921880c1c87d1ff36e5de itself?
I can't help feeling that the answer is yes...

**Comment by pukkandan** [comment]
Pls provide these info https://github.com/yt-dlp/yt-dlp/issues/6272#issuecomment-1435433009

**Comment by pukkandan** [comment]
I want these info in a python that gives the error. I know what what they give when there is no issue...

**Comment by garettharnish** [comment]
Pycrypto isn't the only issue.  As I mentioned in my report in the other issue (see 6272), I was running pycryptodomex and encountered a similar issue.  Reinstalling pycrptodomex didn't fix it since it appears cffi is not a required dependency for pycryptodomex (even though it is, at least in how it is being used in yt-dlp).
