### ISSUE TITLE
[ok.ru] Videos are corrupted, wrong mtime

### ISSUE THREAD

**Issue by AlttiRi** [yt-dlp/yt-dlp#6221]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

EU

### Provide a description that is worded well enough to be understood

yt-dlp corrupts files while downloading.

Here is the URL https://ok.ru/video/1269740472936

yt-dlp's result:
Size: 206353706 bytes (196 MiB)
SHA1: c5150e072871df0f9e2934f50bab4aa47ac6fbab

The file is broken. A video player lags, freezes while playing.

The correct file (downloaded with DevTools):
Size: 206343640 bytes (196 MiB)
SHA1: f55c505035f70cc3d45f6c1f76bf7965229f2ea5

---

Two more examples:
https://ok.ru/video/1240962828904
https://ok.ru/video/1240964074088

---
This one was downloaded correctly.
https://ok.ru/video/4217990679137

Possibly, because it have no video quality chooser:
![image](https://user-images.githubusercontent.com/16310547/218335513-d954905c-e750-4b99-9730-d448d983407a.png)

While the other have it:
![image](https://user-images.githubusercontent.com/16310547/218335539-eab91043-4f65-4cc9-af21-d80ddb1caa67.png)

---

Also all video files have wrong mtime (2014.01.01).

While filename `date` key is correct (2019.05.19):
```
[ok.ru] A L E X—2019.05.19—1269740472936—Encounter a young wild white Arctic Fox in Greenland.mp4
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt https://ok.ru/video/1269740472936 -vU
[debug] Command-line config: ['--write-thumbnail', '--write-description', '-o', '[%(webpage_url_domain)s] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(id)s—%(full
title|)s.%(ext)s', '-o', 'pl_thumbnail:[%(webpage_url_domain)s][thumbnail] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(playlist_id,id)s—%(fulltitle|)s.%(ext)s',
'https://ok.ru/video/1269740472936', '-vU']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd2508]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.13 (CPython AMD64 64bit) - Windows-10 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[Odnoklassniki] Extracting URL: https://ok.ru/video/1269740472936
[Odnoklassniki] 1269740472936: Downloading desktop webpage
[Odnoklassniki] 1269740472936: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasa
ud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1269740472936: Downloading 1 format(s): mpd-7
[info] There's no video description to write
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: [ok.ru] A L E X—2019.05.19—1269740472936—Encounter a young wild white Arctic Fox in Greenland.jpg
[debug] Invoking http downloader on "https://vd288.mycdn.me/..."
[debug] File locking is not supported. Proceeding without locking
[download] Destination: [ok.ru] A L E X—2019.05.19—1269740472936—Encounter a young wild white Arctic Fox in Greenland.mp4
```

**Comment by AlttiRi** [comment]
It correctly download the data from the logged URL, but the file _from the selected URL_ are corrupted. 
It should choose the other URL (which site's player uses).

**Comment by AlttiRi** [comment]
Seems I get it. 

You need just to parse a URL with `ct=0` instead of `ct=4`.
There 8 URLs with `ct=4` and 8 URLs with `ct=0`.

I think a video format from `ct=0` URL would be the more correct one.

**Comment by AlttiRi** [comment]
Also the videos are **not** corrupted, MPC-HC (K-Lite Codec Pack) seems just does not support `iso5 (avc1/iso5/dsms/msix/dash)` codec.

A `ct=0` URLcontains a video with `isom (isom/iso2/avc1/mp41)`

**Comment by D0LLYNH0** [comment]
I've had the same problem in the past extracting manually without the help of yt-dlp (about a year ago), to work around this, I just gave preference to the `m3u8` protocol versions instead of `https`, that is, yt- dlp does not corrupt the files, manually downloading the DASH video format generates an identical hash.


> Also the videos are **not** corrupted, seems MPC-HC (K-Lite Codec Pack) just does not support `iso5 (avc1/iso5/dsms/msix/dash)` codec correctly. VLC player can play them with no problem.

I can't reproduce this behavior, my MPC-HC played the `iso5` brand files normally.

**Comment by AlttiRi** [comment]
I have never have any issue with MPC-HC, but with `ct=4` videos from `ok.ru` now.
Seems these videos are some special re-endoded for [MSE standard](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API).

Here is how it looks: https://uploadir.com/u/uq9uyla3

<details>
<summary>MediaInfo</summary>

```
General
Complete name               : M:\552983530088_iso5.mp4
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : iso5 (avc1/iso5/dsms/msix/dash)
File size                   : 197 MiB
Duration                    : 1 min 7 s
Overall bit rate            : 24.5 Mb/s
Writing application         : Lavf58.20.100

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L5.1
Format settings             : CABAC / 4 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 4 frames
Format settings, GOP        : M=1, N=30
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 1 min 7 s
Bit rate                    : 24.4 Mb/s
Width                       : 3 840 pixels
Height                      : 2 160 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Variable
Frame rate                  : 29.970 (29970/1000) FPS
Minimum frame rate          : 12.529 FPS
Maximum frame rate          : 30.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.098
Stream size                 : 195 MiB (99%)
Writing library             : x264 core 152 r2851 ba24899
Encoding settings           : cabac=1 / ref=4 / deblock=1:2:2 / analyse=0x3:0x113 / me=hex / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=67 / lookahead_threads=16 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=2 / keyint=30 / keyint_min=3 / scenecut=0 / intra_refresh=0 / rc_lookahead=30 / rc=abr / mbtree=1 / bitrate=24414 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / ip_ratio=0.91 / aq=1:1.00
Tagged date                 : UTC 2019-05-19 17:30:25
Codec configuration box     : avcC

Audio
ID                          : 2
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : mp4a-40-2
Duration                    : 1 min 7 s
Bit rate mode               : Constant
Bit rate                    : 256 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 44.1 kHz
Frame rate                  : 43.066 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 2.05 MiB (1%)
Default                     : Yes
Alternate group             : 1
Tagged date                 : UTC 2019-05-19 17:30:25
```

</details>

From `c=0` endpoint (this file is fine):
<details>
<summary>MediaInfo</summary>

```
General
Complete name               : M:\552983530088_isom.mp4
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom (isom/iso2/avc1/mp41)
File size                   : 197 MiB
Duration                    : 1 min 7 s
Overall bit rate            : 24.5 Mb/s
Writing application         : Lavf58.20.100

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L5.1
Format settings             : CABAC / 4 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 4 frames
Format settings, GOP        : M=1, N=30
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 1 min 7 s
Duration_FirstFrame         : 46 ms
Bit rate                    : 24.4 Mb/s
Width                       : 3 840 pixels
Height                      : 2 160 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 30.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.098
Stream size                 : 195 MiB (99%)
Writing library             : x264 core 152 r2851 ba24899
Encoding settings           : cabac=1 / ref=4 / deblock=1:2:2 / analyse=0x3:0x113 / me=hex / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=67 / lookahead_threads=16 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=2 / keyint=30 / keyint_min=3 / scenecut=0 / intra_refresh=0 / rc_lookahead=30 / rc=abr / mbtree=1 / bitrate=24414 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / ip_ratio=0.91 / aq=1:1.00
Tagged date                 : UTC 2019-05-19 17:30:25
Codec configuration box     : avcC

Audio
ID                          : 2
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : mp4a-40-2
Duration                    : 1 min 7 s
Duration_LastFrame          : -4 ms
Bit rate mode               : Constant
Bit rate                    : 256 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 44.1 kHz
Frame rate                  : 43.066 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 2.05 MiB (1%)
Default                     : Yes
Alternate group             : 1
Tagged date                 : UTC 2019-05-19 17:30:25
```

</details>

**Comment by D0LLYNH0** [comment]
Maybe this `-S "proto:m3u8_native"` or `-f "b[protocol^=m3u8]"` will help in your case, have you tried it?

**Comment by pukkandan** [comment]
It sounds like yt-dlp is extracting both sets of formats and the "corrupt" downloads is player's issue. Am I mistaken?

**Comment by AlttiRi** [comment]
Forgot to check `-F`.

```
ultra     mp4 unknown        │                   https │ unknown            unknown
hls-26493 mp4 3840x2160   30 │ ~216.68MiB 26493k m3u8  │ unknown     26493k unknown    0k
mpd-7     mp4 3840x2160   30 │ ~206.61MiB 25262k https │ avc1.640033 25262k mp4a.40.2  0k 44k DASH video, mp4_dash
```


Yes, it lists `ct=0` as `ultra`, however, I get for it the **`400` exception**:

<details>
<summary>Trace</summary>

```
yt https://ok.ru/video/1269740472936 -f ultra -v
```
```
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3236, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2959, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\http.py", line 371, in real_download
    establish_connection()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```
</details>

But the download URL from the log works fine when I put it in the browser's address bar.

---

Also there is the second issue — the **wrong file's mtime** (`2014.01.01`)

---

```
yt https://ok.ru/video/1269740472936 -f mpd-7
```
work fine.

All 3 format are provide the same pictures (the screenshots of the same frame are byte equivalent), but different containers.

`ultra` is the best for players support. In participial, this format has nice iframe (keyframe) navigation with the player. But the 400 error.
