### ISSUE TITLE
CBC postprocessing error

### ISSUE THREAD

**Issue by grunge10111** [yt-dlp/yt-dlp#623]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```
PS C:\Windows\system32> yt-dlp https://www.cbc.ca/player/play/1920627779574 -v
[debug] User config file: C:\Users\Gamer\yt-dlp.conf.txt
[debug] User config: ['-o', 'E:\\YT-DLP Videos\\%(upload_date)s-%(uploader)s_-_%(title)s.%(ext)s']
[debug] Command-line config: ['https://www.cbc.ca/player/play/1920627779574', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.02
[debug] Python version 3.7.5 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-101867-gc06465a70b, ffprobe N-101867-gc06465a70b, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [cbc.ca:player] Extracting URL: https://www.cbc.ca/player/play/1920627779574
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/ExhSPC/media/guid/2655402169/1920627779574?mbr=true&formats=MPEG4,FLV,MP3#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 1920627779574: Downloading SMIL data
[ThePlatform] 1920627779574: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 1920627779574: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1920627779574: Downloading 1 format(s): hls-3440
[debug] Invoking downloader on "https://cbcrcolympic-cbc.akamaized.net/hls/live/2025691/geo_allow_ca/taars857hk/hdntl=exp=1628124209~acl=%2f*~id=7027280a-9ced-47cb-a7c7-a425a2a7973d~data=hdntl~hmac=c37eaf639d36dcfd2e6e8040c131db50aff1a6874fb7f6b38b2c8000dcefb165/master_3000-archive.m3u8?aka_me_session_id=AAAAAAAAAAAxNAthAAAAABiX%2flUBY1YlQWVxHsqf3AgQ6QvCZ%2fBEPpJUkNWU5gU7TlQrUbsmjmej1rF874BWFId9ktBkOKjB&aka_media_format_type=hls&startTime=1627543200&endTime=1627554360"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1422
[download] Destination: E:\YT-DLP Videos\20210729-CBCC-NEW_-_Rugby - Women's Preliminary - Session 2.mp4
[download] 100% of 4.21GiB in 11:12
[debug] ffmpeg command line: ffprobe -show_streams "file:E:\YT-DLP Videos\20210729-CBCC-NEW_-_Rugby - Women's Preliminary - Session 2.mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "E:\YT-DLP Videos\20210729-CBCC-NEW_-_Rugby - Women's Preliminary - Session 2.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:E:\YT-DLP Videos\20210729-CBCC-NEW_-_Rugby - Women's Preliminary - Session 2.mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:E:\YT-DLP Videos\20210729-CBCC-NEW_-_Rugby - Women's Preliminary - Session 2.temp.mp4"
ERROR: ffmpeg version N-101867-gc06465a70b Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-vulkan --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --enable-libglslang --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      56. 72.100 / 56. 72.100
  libavcodec     58.135.100 / 58.135.100
  libavformat    58. 77.100 / 58. 77.100
  libavdevice    58. 14.100 / 58. 14.100
  libavfilter     7.111.100 /  7.111.100
  libswscale      5. 10.100 /  5. 10.100
  libswresample   3. 10.100 /  3. 10.100
  libpostproc    55. 10.100 / 55. 10.100
[mpegts @ 00000240cd3e5f00] start time for stream 2 is not set in estimate_timings_from_pts
[mpegts @ 00000240cd3e5f00] stream 2 : no TS found at start of file, duration not set
[mpegts @ 00000240cd3e5f00] Could not find codec parameters for stream 2 (Audio: mp3, 0 channels): unspecified frame size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mpegts, from 'file:E:\YT-DLP Videos\20210729-CBCC-NEW_-_Rugby - Women's Preliminary - Session 2.mp4':
  Duration: 03:06:00.00, start: 1138.033333, bitrate: 3237 kb/s
  Stream #0:0[0x1e1]: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
  Stream #0:1[0x1e2]: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:2[0x1f6]: Audio: mp3, 0 channels
[aac_adtstoasc @ 00000240cdc27640] Codec 'mp3' (86017) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018)
Error initializing bitstream filter: aac_adtstoasc
Error initializing output stream 0:2 --
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python37\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\__init__.py", line 730, in main
    _real_main(argv)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\__init__.py", line 720, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 2846, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 1172, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 1179, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 1217, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 1314, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 1261, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 2280, in process_video_result
    self.process_info(new_info)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 2815, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 2955, in post_process
    info = self.run_pp(pp, info)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 2904, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\common.py", line 83, in wrapper
    return func(self, info)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 706, in run
    '-c', 'copy', '-map', '0', '-dn', '-f', 'mp4', '-bsf:a', 'aac_adtstoasc'])
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 676, in _fixup
    self.run_ffmpeg(filename, temp_filename, options)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 284, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 241, in run_ffmpeg_multiple_files
    [(out_path, opts)], **kwargs)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 276, in real_run_ffmpeg
    self.report_error(stderr)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\common.py", line 56, in report_error
    return self._downloader.report_error(text, *args, **kwargs)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 797, in report_error
    self.trouble(error_message, tb)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 753, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: Postprocessing:   Stream #0:2 -> #0:2 (copy)
Traceback (most recent call last):
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 2815, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 2955, in post_process
    info = self.run_pp(pp, info)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 2904, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\common.py", line 83, in wrapper
    return func(self, info)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 706, in run
    '-c', 'copy', '-map', '0', '-dn', '-f', 'mp4', '-bsf:a', 'aac_adtstoasc'])
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 676, in _fixup
    self.run_ffmpeg(filename, temp_filename, options)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 284, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 241, in run_ffmpeg_multiple_files
    [(out_path, opts)], **kwargs)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 277, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:2 -> #0:2 (copy)

## Description

WRITE DESCRIPTION HERE
I've been trying to download some CBC Olympic replays, and it starts the download like normal but then I get this odd postprocessing error at the end. I can download other videos off CBC including videos from the Olympics, it's only the replays that get this error. I've never gotten this error prior to this either. I've had videos in the past that had malformed AAC bitstreams that needed fixed, but it always got taken care of during the download. Any help would be greatly appreciated!

**Comment by pukkandan** [comment]
hm, I do see what's the issue here

```
[info] 1920627779574: Downloading 1 format(s): hls-3440
...
  Stream #0:0[0x1e1]: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
  Stream #0:1[0x1e2]: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:2[0x1f6]: Audio: mp3, 0 channels
```

The video served by the website contains one video and 2 audio streams in it. One mp3 and one m4a. But since yt-dlp doesnt understand that it has 2 audio steams and only sees the m4a. When we try to fix the mp4, ffmpeg complains that the operation cannot be done on the mp3.

Solving this issue at the root is going to be tricky. But for your particular issue, I believe the video file that you got should be working even though the fixup failed. Try playing it and see if there are any issues.

**Comment by pukkandan** [comment]
actually, I see something else that's weird. The mp3 says "0 channels". Can u also check if the resulting file has only 1 stream or 2?

**Comment by grunge10111** [comment]
> 
> 
> hm, I do see what's the issue here
> 
> ```
> [info] 1920627779574: Downloading 1 format(s): hls-3440
> ...
>   Stream #0:0[0x1e1]: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
>   Stream #0:1[0x1e2]: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
>   Stream #0:2[0x1f6]: Audio: mp3, 0 channels
> ```
> 
> The video served by the website contains one video and 2 audio streams in it. One mp3 and one m4a. But since yt-dlp doesnt understand that it has 2 audio steams and only sees the m4a. When we try to fix the mp4, ffmpeg complains that the operation cannot be done on the mp3.
> 
> Solving this issue at the root is going to be tricky. But for your particular issue, I believe the video file that you got should be working even though the fixup failed. Try playing it and see if there are any issues.

I got 2 MP4 files but one was just a temp file. I tried both in VLC and MPV and I got an error for both. Yeah I noticed a few bizarre notes in the shell so that's why I posted it on here.


> 
> 
> actually, I see something else that's weird. The mp3 says "0 channels". Can u also check if the resulting file has only 1 stream or 2?

All the information for the file is blank. Unless there's another way to check not sure I can answer that (I'm not the most computer savvy person in the world).

**Comment by werid** [comment]
> actually, I see something else that's weird. The mp3 says "0 channels". Can u also check if the resulting file has only 1 stream or 2?

i encountered this problem too, and just applied `--fixup never`. looking at the files now, mediainfo only shows the aac stream, while mpv shows both, but if manually choosing the mp3 stream, playback freezes on first frame. file works fine otherwise when using aac audio.

**Comment by pukkandan** [comment]
In that case, the mp3 seems to be damaged from source itself

**Comment by h1z1** [comment]
Appears the referenced video has now "expired".  Maybe it was a problem with the source?

> ExtractorError: This content expired on 8/28/21 7:20 AM.

I'd forgotten how much of a dumpster the CBC was.
