### ISSUE TITLE
Youtube Error "Unable to extract uploader id" in every video

### ISSUE THREAD

**Issue by UrubuCheiroso** [yt-dlp/yt-dlp#6247]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This error started appearing to me yesterday and almost every video gave this error, but I could download the video after about 3 attempts. But today, all youtube videos are giving this error no matter how many times I try to download it. Can anyone help me?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=aqz-KE-bpKQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.9.4 (CPython x86_64 64bit) - Linux-5.15.10-tinycore64-x86_64-with-glibc2.34 (OpenSSL 1.1.1j  16 Feb 2021, glibc 2.34)
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, phantomjs 2.1.1
[debug] Optional libraries: mutagen-1.46.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=aqz-KE-bpKQ
[youtube] aqz-KE-bpKQ: Downloading webpage
[youtube] aqz-KE-bpKQ: Downloading android player API JSON
[debug] Loading youtube-nsig.1cbba2b4 from cache
WARNING: [youtube] aqz-KE-bpKQ: Native nsig extraction failed: Trying with PhantomJS
         n = __Fxna8S9BSt6Xk ; player = https://www.youtube.com/s/player/1cbba2b4/player_ias.vflset/en_US/base.js
[debug] [youtube] Signature function returned an exception; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] aqz-KE-bpKQ: Executing signature code
[debug] [youtube] PhantomJS command line: phantomjs --ssl-protocol=any /tmp/tmpbp71rh8v
[debug] [youtube] Decrypted nsig __Fxna8S9BSt6Xk => kUALy39FPpkyJw
ERROR: [youtube] aqz-KE-bpKQ: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4049, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by garoto** [comment]
Having this same issue since early this morning (started at around 6AM) and judging by your username, I assume you're in Brazil? If yes what's your ISP? I am on a fiber connection by VIVO.

A/B javascript testing perhaps? Videos works via proxies in the US and DE.

**Comment by johseg** [comment]
I have the same issue (germany,1&1 ISP), so it's likely not a issue limited to one location

**Comment by bashonly** [comment]
> Edit: I have the dumps generated by `--write-pages` and `--print-traffic` and can upload if they can be useful.

@garoto
could you check on something in `aqz-KE-bpKQ_https_-_www.youtube.com_watchv=aqz-KE-bpKQ_bpctr=9999999999_has_verified=1.dump` ?

If you're on windows, could you open the file in a text/code editor and ctrl+F for `ownerProfileUrl` and paste its value here?

or if on GNU/linux, you could just run this and copy/paste the output
```
grep -Po 'ownerProfileUrl":"\K([^"]*)"' 'aqz-KE-bpKQ_https_-_www.youtube.com_watchv=aqz-KE-bpKQ_bpctr=9999999999_has_verified=1.dump'
```

**Comment by garoto** [comment]
This bit?

`"ownerProfileUrl":"http://www.youtube.com/@pbsspacetime"`

**Comment by garoto** [comment]
The dump I've made via a US proxy has this for its value:

`"ownerProfileUrl":"http://www.youtube.com/channel/UC7_gcs09iThXybpVgjHZ_7g`

**Comment by user1872372839** [comment]
Having the same issue here, also Brazil. 

The issue started around 7 AM (GMT-3), all my auto-download scripts stopped working at that time.

**Comment by bashonly** [comment]
> This bit?
> `"ownerProfileUrl":"http://www.youtube.com/@pbsspacetime"`

Yep that's the one, thanks. I had a feeling the new `@handle` URL was to blame.

I think this should fix the issue
```diff
diff --git a/yt_dlp/extractor/youtube.py b/yt_dlp/extractor/youtube.py
index 95ca52b3a..4dde4bbaa 100644
--- a/yt_dlp/extractor/youtube.py
+++ b/yt_dlp/extractor/youtube.py
@@ -4120,7 +4120,7 @@ def is_bad_format(fmt):
             'thumbnail': traverse_obj(original_thumbnails, (-1, 'url')),
             'description': video_description,
             'uploader': get_first(video_details, 'author'),
-            'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
+            'uploader_id': self._search_regex(r'/(?:channel/|user/|@)([^/?&#]+)', owner_profile_url, 'uploader id', default=None),
             'uploader_url': owner_profile_url,
             'channel_id': channel_id,
             'channel_url': format_field(channel_id, None, 'https://www.youtube.com/channel/%s'),
```

**Comment by garoto** [comment]
> I think this should fix the issue

Yes it does I guess:

```
> yt-dlp --no-config -v --get-title E8hyodMhbRw
[debug] Command-line config: ['--no-config', '-v', '--get-title', 'E8hyodMhbRw']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.8.2 (CPython AMD64 64bit) - Windows-8.1-6.3.9600-SP0 (OpenSSL 1.1.1d  10 Sep 2019)
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[youtube] Extracting URL: E8hyodMhbRw
[youtube] E8hyodMhbRw: Downloading webpage
[youtube] E8hyodMhbRw: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] E8hyodMhbRw: Downloading 1 format(s): 313+251
How Does The Nucleus Hold Together?
```

**Comment by mabachel** [comment]
`yt-dlp -vU --write-pages --print-traffic https://www.youtube.com/watch?v=aqz-KE-bpKQ` works for me:
```shell
grep -Po 'ownerProfileUrl":"\K([^"]*)"' 'aqz-KE-bpKQ_https_-_www.youtube.com_watchv=aqz-KE-bpKQ_bpctr=9999999999_has_verified=1.dump'
http://www.youtube.com/user/BlenderFoundation"
```

However `yt-dlp -vU --write-pages https://www.youtube.com/watch?v=LqYBa1xCLRM` does NOT work fo me:
```shell
[debug] Command-line config: ['-vU', '--write-pages', 'https://www.youtube.com/watch?v=LqYBa1xCLRM']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd2508]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.1 (CPython x86_64 64bit) - Linux-6.1.11-200.fc37.x86_64-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.17.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=LqYBa1xCLRM
[youtube] LqYBa1xCLRM: Downloading webpage
[youtube] Saving request to LqYBa1xCLRM_https_-_www.youtube.com_watchv=LqYBa1xCLRM_bpctr=9999999999_has_verified=1.dump
[youtube] LqYBa1xCLRM: Downloading android player API JSON
[youtube] Saving request to LqYBa1xCLRM_https_-_www.youtube.com_youtubei_v1_playerkey=AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w_prettyPrint=false.dump
[debug] Loading youtube-nsig.1cbba2b4 from cache
WARNING: [youtube] LqYBa1xCLRM: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 8IY4WqK_fBKTDUL ; player = https://www.youtube.com/s/player/1cbba2b4/player_ias.vflset/en_US/base.js
[debug] [youtube] Signature function returned an exception; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] LqYBa1xCLRM: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 4049, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

```

```shell
grep -Po 'ownerProfileUrl":"\K([^"]*)"' LqYBa1xCLRM_https_-_www.youtube.com_watchv\=LqYBa1xCLRM_bpctr\=9999999999_has_verified\=1.dump 
http://www.youtube.com/@orthosporteschweiler3469"
```

**Comment by mabachel** [comment]
The patch seems to work. :trophy:

**Comment by johseg** [comment]
same here, thank you :)

**Comment by Kagamiin** [comment]
Patch works on my side too, thank you so much. This should be accepted ASAP.

**Comment by h3artbl33d** [comment]
The [patch](https://github.com/yt-dlp/yt-dlp/issues/6247#issuecomment-1433096554) from @bashonly fixed the issue. Thank you - now [Jouwbuis](https://jouwbuis.nl/) is up and running again!

**Comment by lindalima** [comment]
> > I think this should fix the issue
> 
> Yes it does!

It does not work for me.

```
>yt-dlp --no-config -v --get-title 2ZACWIPuTDE
[debug] Command-line config: ['--no-config', '-v', '--get-title', '2ZACWIPuTDE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-80522-ge0faad8 (needs_adtstoasc), ffprobe N-80522-ge0faad8
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[youtube] Extracting URL: 2ZACWIPuTDE
[youtube] 2ZACWIPuTDE: Downloading webpage
[youtube] 2ZACWIPuTDE: Downloading android player API JSON
ERROR: [youtube] 2ZACWIPuTDE: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\youtube.py", line 4049, in _real_extract
  File "yt_dlp\extractor\common.py", line 1228, in `_search_regex
```

**Comment by lindalima** [comment]
> The patch seems to work. 🏆

WIndows 10. Where do I put de patch? I use standalone yt-dlp.exe

**Comment by PlaylistsTrance** [comment]
Just wait for the patched release, which should be soon: https://www.reddit.com/r/youtubedl/comments/113rk4v/ytdlp_and_youtubedl_wont_download_anything_from/j8rwnrb/

**Comment by garoto** [comment]
> WIndows 10. Where do I put de patch? I use standalone yt-dlp.exe


You cannot apply the text diff into a binary for obvious reasons.

**Comment by Shituation** [comment]
> > WIndows 10. Where do I put de patch? I use standalone yt-dlp.exe
> 
> You cannot apply the text diff into a binary for obvious reasons.
> 
> Edit: keep an eye on https://github.com/ytdl-patched/yt-dlp/releases for new daily releases from the master branch.

Latest yt-dlp 2023.02.16.19419 doesn't solve this, right? asking to be sure because its very new and its still doesn't work.

**Comment by Lesmiscore** [comment]
> Latest yt-dlp 2023.02.16.19419 doesn't solve this, right?

Yes. The build was run before the fix is done in master
Going to be working in 2023.02.17.xxx. The build will run in 7 hours

**Comment by Vangelis66** [comment]
> Yes. **The build was run before the fix is done in master**

FWIW, the automated/scheduled `Rebase on Upstream` GHA workflows had been constantly failing **for the past four days**, thus 

> Latest yt-dlp 2023.02.16.19419

was identical to `v2023.02.12.40298`, compiled from `yt-dlp` source `git-20230211-gb85faf6` 😿 ...
I now see _that_ problem **has been fixed**, by manually triggering the latest [Rebase on Upstream](https://github.com/ytdl-patched/yt-dlp/actions/runs/4197023118) workflow; so, many thanks! 💟

**Comment by gguy825** [comment]
Im currently on version yt-dlp-2023.1.6, just updated when I got the error message. Ive tried the commands above but nothing has been working. This command is what I usually use to download videos.
`
python3 yt-dlp -f bv+ba -P nobody/ https://www.youtube.com/watch?v=R-bI0AhSyU0`

**Comment by garoto** [comment]
Latest yt-dlp 2023.02.16.19419 doesn't solve this, right?

> Yes. The build was run before the fix is done in master [...]

The correct wording is "No" btw.

**Comment by krasnh** [comment]
This commit does not solve the problem, https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b.

**Comment by runshouse** [comment]
Is there a way to be notified when this fix lands?

**Comment by Shituation** [comment]
> Is there a way to be notified when this fix lands?

Go to"watch" and clic the arrow then clic custom then clic releases

**Comment by Grub4K** [comment]
> This commit does not solve the problem

@krasnh How come? Without context this comment does not help the conversation. If you have an instance of it not working, post its verbose log so that we may debug further.

**Comment by Schmensch** [comment]
Can confirm that the patch works.

**Comment by hendursaga** [comment]
I also can confirm the patch works.

**Comment by krasnh** [comment]
> @krasnh How come? 

Sorry. I was wrong. ) 
It was necessary to run it locally, `./yt-dlp 'aqz-KE-bpKQ'`.
I ran it like this `yt-dlp 'aqz-KE-bpKQ'`.


The commit https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b is working. Confirm.

**Comment by runshouse** [comment]
How does one download the patch?

**Comment by walmirlsj1** [comment]
faz manual por enquanto, amanha deve sair a atualização

**Comment by richardwalenga** [comment]
I followed the cutting edge instructions for PIP [from the wiki](https://github.com/yt-dlp/yt-dlp-wiki/blob/master/Installation.md#with-pip) and it resolved my issue.

**Comment by gamer191** [comment]
> How does one download the patch?

the next version (2023.02.17) of https://github.com/ytdl-patched/yt-dlp should be out in approximitely one hour. Either use that, or wait for the next yt-dlp release, which will come out soon, according to Lesmiscore's message

**Comment by pabloab** [comment]
> EDIT: for [PIP](https://www.python.org/downloads/release/python-3112/) users, this will also work (thanks @richardwalenga):
> 
> ```
> python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
> ```

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
checkbox-ng 1.4.0 requires pycrypto>=2.6.1, which is not installed.
whatstk 0.5.0 requires certifi==2020.12.5, but you have certifi 2022.12.7 which is incompatible.
whatstk 0.5.0 requires numpy~=1.19.1, but you have numpy 1.21.6 which is incompatible.
```

**Comment by gamer191** [comment]
@pabloab is that the full output?

**Comment by raph20200** [comment]
Good morning, I am in Germany on a Mac using brew. I still have the same problem. Which exact command do I have to type in ? Thank you.

**Comment by kraamis** [comment]
Good morning! 

Similar problem in Termux, Android.

**Comment by bodqhrohro** [comment]
```
@bq:09:10:51:/tmp$ pip install -U pip setuptools wheel
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (22.3.1)
Collecting pip
  Downloading pip-23.0-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 962.0 kB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (58.2.0)
Collecting setuptools
  Downloading setuptools-67.3.2-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 1.3 MB/s eta 0:00:00
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.37.1)
Collecting wheel
  Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-23.0 setuptools-67.3.2 wheel-0.38.4
@bq:09:17:07:/tmp$ pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
Defaulting to user installation because normal site-packages is not writeable
Collecting https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
  Downloading https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 1.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 415, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 577, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 701, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/bodqhrohro/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'

```

**Comment by sudochia** [comment]
Still getting the error. Let's wait for the next release.

**Comment by KalebSchmidlkofer** [comment]
Yeah me to

**Comment by GraOrigin** [comment]
+1

looking forward to a new release, since it's already fixed

**Comment by gklasen** [comment]
Cite from their Discord-channel, 9:11 AM:

Stickied Message:

Unable to extract uploader id on Youtube has already been fixed and a new release will be made in a few hours.
If you cannot wait, use https://github.com/ytdl-patched/yt-dlp/releases/latest or https://github.com/yt-dlp/yt-dlp/wiki/Installation#:~:text=master%20branch

**Comment by slooi** [comment]
Can confirm bashonly's patch works. I previously could not download this video (https://www.youtube.com/watch?v=lIMX5opqRkU) even with latest updates. After downloading patched everything worked fine.

**Comment by Ashborn117** [comment]
How do I apply this patch on windows?

**Comment by pacjo** [comment]
I successfully installed version from master branch, but I would like to revert to stable. How to do it?

**Comment by midnight-noob** [comment]
Solved! :)

**Comment by gklasen** [comment]
Well, particially. The fix is not in the latest official release yet.

**Comment by gamer191** [comment]
> How do I apply this patch on windows?

wait a little while for the next update, or use https://github.com/ytdl-patched/yt-dlp/releases/latest (or https://github.com/yt-dlp/yt-dlp/wiki/Installation#:~:text=master%20branch if you have [pip](https://www.python.org/downloads/release/python-3112/) installed)

**Comment by Seblor** [comment]
The Windows release on https://github.com/ytdl-patched/yt-dlp/releases/latest triggers Chrome's security safety, is there any known reason for that ?

**Comment by askdesigners** [comment]
Great work! I can imagine it's very stressful having something break and users pile in with the same issue repeatedly. Bravo to a well-functioning team!  👏

**Comment by pukkandan** [comment]
Next time something like this happens, I'll probably lock the repo using GH moderation tools. It's not something I want to do, but dealing with so many duplicates is such a pain

**Comment by WojciechMigda** [comment]
> I think this should fix the issue
 
this also fixes legacy `youtube-dl` 2021.12.27. <3

**Comment by anonymous721** [comment]
> python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz

After doing this, now every time I run yt-dlp I get a dozen warning messages of the form `WARNING: Could not read zip file /home/user/anaconda3/lib/python3.7/site-packages/SomePackage.egg: [Errno 21] Is a directory: '/home/user/anaconda3/lib/python3.7/site-packages/SomePackage.egg'` pointing to various unrelated packages like apngasm and bitsandbytes.
This persists after updating through pip normally to 2023.2.17.

**Comment by pukkandan** [comment]
Open new issue
