### ISSUE TITLE
ign.com - unable to download any videos

### ISSUE THREAD

**Issue by 07416** [yt-dlp/yt-dlp#6249]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

yt-dlp can't download seemingly any videos under `https://www.ign.com/videos/`, may be caused by a CDN-related change.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.ign.com/videos/indiana-jones-and-the-dial-of-destiny-official-big-game-teaser-trailer']
[debug] System config "/etc/yt-dlp.conf": ['-o', '$HOME/Videos/youtube-dl/%(title)s-%(id)s.%(ext)s', '--remux-video', 'mkv', '--sponsorblock-remove', 'all', '--embed-metadata', '--embed-subs', '--clean-infojson', '--embed-chapters', '--restrict-filenames', '--compat-options', 'no-live-chat', '--no-write-comments']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd2508]
[debug] Lazy loading extractors is disabled
[debug] Compatibility options: no-live-chat
[debug] Python 3.11.1 (CPython x86_64 64bit) - Linux-6.1.10-200.fc37.x86_64-x86_64-with-glibc2.36 (OpenSSL 3.0.5 5 Jul 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[ign.com] Extracting URL: https://www.ign.com/videos/indiana-jones-and-the-dial-of-destiny-official-big-game-teaser-trailer
[ign.com] indiana-jones-and-the-dial-of-destiny-official-big-game-teaser-trailer: Downloading JSON metadata
[ign.com] d85b9c90-bee8-4c29-a2a9-abbbfec45890: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[SponsorBlock] SponsorBlock is not supported for IGN
[debug] Default format spec: bestvideo*+bestaudio/best
[info] d85b9c90-bee8-4c29-a2a9-abbbfec45890: Downloading 1 format(s): mezzanine
[info] There's no subtitles for the requested languages
[debug] Invoking http downloader on "https://ign-video-prd-assets.s3.amazonaws.com/2023/02/13/indiana-jones-and-the-dial-of-destiny-big-game-tv-spot-1676246807683.mp4"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3236, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2959, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
workaround:
`-f "(bv*+ba/b)[format_id!=mezzanine]"`

or, since you're using Linux, you'll probably need to single-quote the argument because of the `!`:
`-f '(bv*+ba/b)[format_id!=mezzanine]'`

or you could use `-F` to view the list of formats and select one that's to your liking

It looks like the `mezzanine` format (source quality?) is no longer available or requires some unknown headers/params. For this example URL, though, there are other formats still available, including 1080p https and HLS

**Comment by 07416** [comment]
> workaround: `-f "(bv*+ba/b)[format_id!=mezzanine]"`
> 
> or, since you're using Linux, you'll probably need to single-quote the argument because of the `!`: `-f '(bv*+ba/b)[format_id!=mezzanine]'`

Seemingly functions — `-f '(bv*+ba/b)[format_id!=mezzanine]'`, followed by the URL `https://www.ign.com/videos/*`.

Also confirmed with a 4K 60FPS video `https://www.ign.com/videos/marvels-midnight-suns-official-redemption-venom-dlc-trailer`

**Comment by dirkf** [comment]
The `mezzanine` format is accessible in the test video but not with newer videos.

>It looks like the mezzanine format (source quality?) is no longer available or requires some unknown headers/params.

Quite. Given the name (a partial floor between two storeys), it's entirely possible that this is the format distributed to the CDN for re-encoding.

**Comment by antdude** [comment]
Still no updates and requires manuallly to do it as shown in https://www.reddit.com/r/youtubedl/comments/15e6siw/is_anyone_able_to_download_igns_videos/ju60loz/?

**Comment by 07416** [comment]
> Still no updates and requires manually to do it as shown in https://www.reddit.com/r/youtubedl/comments/15e6siw/is_anyone_able_to_download_igns_videos/ju60loz/?

for reference:

>     yt-dlp "https://assets.ign.com/master/videos/zencoder/2023/07/18/,640/d0752edf-eb29-4cea-a4ad-c61f4d7a8059,852/d0752edf-eb29-4cea-a4ad-c61f4d7a8059,960/d0752edf-eb29-4cea-a4ad-c61f4d7a8059,1280/d0752edf-eb29-4cea-a4ad-c61f4d7a8059,1920/d0752edf-eb29-4cea-a4ad-c61f4d7a8059,-1689677831/master.m3u8"

> open the page, open inspect the page, go to network, filter by m3u8, you may need to refresh the page to get the 'master.m3u8', copy the full url, add double quotes... pass as parameter to yt-dlp.

**Comment by dirkf** [comment]
Also, the API used in the extractor is now 404, though similar data is available in the Next.js hydration JSON.
