### ISSUE TITLE
Cannot import yt_dlp from python scripts

### ISSUE THREAD

**Issue by gentlecolts** [yt-dlp/yt-dlp#6258]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

yt_dlp fails to import from python scripts as of latest update, but not from python shell.  Manjaro, installed globally via pip.

```
$ python
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yt_dlp as yt
>>> yt
<module 'yt_dlp' from '/usr/lib/python3.10/site-packages/yt_dlp/__init__.py'>
>>> 
$ python3 what.py 
Traceback (most recent call last):
  File "<script directory>/what.py", line 1, in <module>
    import yt_dlp as yt
  File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 19, in <module>
    from .downloader.external import get_external_downloader
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/__init__.py", line 26, in <module>
    from .external import FFmpegFD, get_external_downloader
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/external.py", line 12, in <module>
    from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/__init__.py", line 38, in <module>
    _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
  File "/usr/lib/python3.10/site-packages/yt_dlp/plugins.py", line 135, in load_plugins
    for finder, module_name, _ in iter_modules(name):
  File "/usr/lib/python3.10/site-packages/yt_dlp/plugins.py", line 119, in iter_modules
    pkg = importlib.import_module(fullname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "/usr/lib/python3.10/site-packages/yt_dlp/plugins.py", line 96, in find_spec
    search_locations = self.search_locations(fullname)
  File "/usr/lib/python3.10/site-packages/yt_dlp/plugins.py", line 88, in search_locations
    if parts in dirs_in_zip(path):
  File "/usr/lib/python3.10/site-packages/yt_dlp/plugins.py", line 37, in dirs_in_zip
    with ZipFile(archive) as zip:
  File "/usr/lib/python3.10/zipfile.py", line 1249, in __init__
    self.fp = io.open(file, filemode)
IsADirectoryError: [Errno 21] Is a directory: '<script directory>'
$ cat what.py 
import yt_dlp as yt

$ 
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] User config "<home>/.config/yt-dlp/config": ['--embed-thumbnail', '--add-metadata', '--all-subs', '--embed-subs', '-i']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-6.1.11-1-MANJARO-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
```

**Comment by pukkandan** [comment]
Dup of https://github.com/yt-dlp/yt-dlp/issues/6205
