### ISSUE TITLE
Can't compile: fail detect attributes

### ISSUE THREAD

**Issue by rmbeer** [yt-dlp/yt-dlp#6292]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

can't compile even with a package installed

package: python-pycryptodomex

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ python3 devscripts/make_lazy_extractors.py 
Traceback (most recent call last):
  File "/home/basura/yt-dlp/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
  File "/home/basura/yt-dlp/yt_dlp/compat/compat_utils.py", line 56, in __getattr__
    raise AttributeError(f'module {parent.__name__} has no attribute {attr}')
AttributeError: module yt_dlp.dependencies.Cryptodome has no attribute Cipher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/basura/yt-dlp/devscripts/make_lazy_extractors.py", line 132, in <module>
    main()
  File "/home/basura/yt-dlp/devscripts/make_lazy_extractors.py", line 41, in main
    _ALL_CLASSES = get_all_ies()  # Must be before import
  File "/home/basura/yt-dlp/devscripts/make_lazy_extractors.py", line 68, in get_all_ies
    from yt_dlp.extractor.extractors import _ALL_CLASSES
  File "/home/basura/yt-dlp/yt_dlp/__init__.py", line 18, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "/home/basura/yt-dlp/yt_dlp/cookies.py", line 18, in <module>
    from .aes import (
  File "/home/basura/yt-dlp/yt_dlp/aes.py", line 5, in <module>
    from .dependencies import Cryptodome
  File "/home/basura/yt-dlp/yt_dlp/dependencies/__init__.py", line 76, in <module>
    Cryptodome_AES = Cryptodome.Cipher.AES if Cryptodome else None
  File "/home/basura/yt-dlp/yt_dlp/compat/compat_utils.py", line 43, in __getattribute__
    ret = getter(attr)
  File "/home/basura/yt-dlp/yt_dlp/compat/compat_utils.py", line 56, in __getattr__
    raise AttributeError(f'module {parent.__name__} has no attribute {attr}')
AttributeError: module yt_dlp.dependencies.Cryptodome has no attribute Cipher
```

**Comment by pukkandan** [comment]
Pls share these details https://github.com/yt-dlp/yt-dlp/issues/6272#issuecomment-1435433009

**Comment by rmbeer** [comment]
```
$ python3 -c "from Cryptodome.Cipher import AES; print(AES)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'Cryptodome.Cipher'


$ python3 -c "from Crypto.Cipher import AES; print(AES)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'Crypto'


$ pip install cffi
Defaulting to user installation because normal site-packages is not writeable
Collecting cffi
  Downloading cffi-1.15.1-cp310-cp310-manylinux_2_12_i686.manylinux2010_i686.manylinux_2_17_i686.manylinux2014_i686.whl (421 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 421.7/421.7 kB 2.0 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 1.4 MB/s eta 0:00:00
Installing collected packages: pycparser, cffi
Successfully installed cffi-1.15.1 pycparser-2.21


$ python3 -c "from Cryptodome.Cipher import AES; print(AES)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'Cryptodome.Cipher'


$ python3 -c "from Crypto.Cipher import AES; print(AES)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'Crypto'

```

**Comment by pukkandan** [comment]
Thx. I'll push a fix soon
