### ISSUE TITLE
OpenSuSE 15.3 Python version detection error after yt-dlp -U but not with pm.rpm

### ISSUE THREAD

**Issue by BlindDuck** [yt-dlp/yt-dlp#6314]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

OS: openSuSE 15.3, up to date 21.02.23

It started with "Current version: 2023.01.06"

$ yt-dlp -k https://youtu.be/KQRaj1vcnrs
[youtube] Extracting URL: https://youtu.be/KQRaj1vcnrs
[youtube] KQRaj1vcnrs: Downloading webpage
[youtube] KQRaj1vcnrs: Downloading android player API JSON
ERROR: [youtube] KQRaj1vcnrs: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

I updated and got the result in "Complete Verbose Output".

However updating with zypper
yt-dlp-2023.02.17-pm153.2.1.noarch.rpm
it works again.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vUk', 'https://youtu.be/KQRaj1vcnrs']
ERROR: Python version 3.6 is no longer supported! Please update to Python 3.7 or above; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/yt-dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 967, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 927, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 618, in __init__
    f'{msg}! Please update to Python %d.%d or above' % (*current_version, *MIN_RECOMMENDED))
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1000, in deprecation_warning
    message, stacklevel=stacklevel + 1, printer=self.report_error, is_error=False)
  File "/usr/bin/yt-dlp/yt_dlp/utils.py", line 2059, in deprecation_warning
    return printer(f'{msg}{bug_reports_message()}', **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1012, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 941, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (zip)
[debug] Python 3.6.15 (CPython x86_64 64bit) - Linux-6.1.11-jk-x86_64-with-glibc2.3.4 (OpenSSL 1.1.1d  10 Sep 2019, glibc 2.3.4)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/yt-dlp/__main__.py", line 17, in <module>
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 967, in main
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 927, in _real_main
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 649, in __init__
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3792, in print_debug_header
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 97, in get_versions_and_features
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 168, in _versions
  File "/usr/bin/yt-dlp/yt_dlp/compat/functools.py", line 25, in __get__
    try:
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 172, in basename
  File "/usr/bin/yt-dlp/yt_dlp/compat/functools.py", line 25, in __get__
    try:
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 197, in _version
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 185, in _get_version
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 185, in <genexpr>
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 141, in _get_ffmpeg_version
  File "/usr/bin/yt-dlp/yt_dlp/utils.py", line 2721, in _get_exe_version_output
  File "/usr/bin/yt-dlp/yt_dlp/utils.py", line 903, in run
AttributeError: 'Popen' object has no attribute 'text_mode'
```

**Comment by pukkandan** [comment]
> ```shell
> ERROR: Python version 3.6 is no longer supported! Please update to Python 3.7 or above; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> ```

**Comment by BlindDuck** [comment]
However: python 3.9.15-150300.4.21.1 is installed!!!

rpm -qa|grep python3.|grep lib|sort
libpeas-loader-python3-1.24.1-1.45.x86_64
libpython3_6m1_0-3.6.15-150300.10.37.2.x86_64
libpython3_9-1_0-3.9.15-150300.4.21.1.x86_64
libsamba-policy0-python3-4.15.12+git.535.7750e5c95ef-150300.3.43.1.x86_64
python3-google-auth-httplib2-0.0.3-1.3.2.noarch
python3-html5lib-1.0.1-1.22.noarch
python3-httplib2-0.19.0-3.3.1.noarch
python3-importlib-metadata-1.5.0-3.3.5.noarch
python3-libxml2-python-2.9.7-150000.3.51.1.x86_64
python3-matplotlib-2.2.5-3.3.1.x86_64
python3-matplotlib-cairo-2.2.5-3.3.1.x86_64
python3-matplotlib-gtk3-2.2.5-3.3.1.x86_64
python3-matplotlib-qt5-2.2.5-3.3.1.x86_64
python3-matplotlib-tk-2.2.5-3.3.1.x86_64
python3-matplotlib-web-2.2.5-3.3.1.x86_64
python3-python-xlib-0.26-bp153.1.17.noarch
python3-rdflib-4.2.2-bp153.1.22.noarch
python3-rtslib-fb-2.1.74-150300.3.3.1.noarch
python3-ruamel.yaml.clib-0.2.0-bp153.1.22.x86_64
python3-urllib3-1.25.10-4.3.1.noarch
samba-libs-python3-4.15.12+git.535.7750e5c95ef-150300.3.43.1.x86_64

**Comment by pukkandan** [comment]
I don't know the details of how zypper installs yt-dlp, but I'm assuming they are using the zipexe we distribute. In that case, it is using the `python3` shebang. You'll have to change the python3 shim to a newer version of python if you want it to run on it.

Alternatively, I would recommend uninstalling the yt-dlp from your PM and using `python3.9 -m pip install yt-dlp` instead

**Comment by BlindDuck** [comment]
zypper installs/updates rmp packages from a repo.
In my case yt-dlp is provided by:
https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_$releasever/

python3.9 -m pip install yt-dlp
Collecting yt-dlp
  Downloading yt_dlp-2023.2.17-py2.py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 2.1 MB/s 
Collecting certifi
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 13.2 MB/s 
Collecting mutagen
  Downloading mutagen-1.46.0-py3-none-any.whl (193 kB)
     |████████████████████████████████| 193 kB 14.7 MB/s 
Collecting brotli; platform_python_implementation == "CPython"
  Downloading Brotli-1.0.9-cp39-cp39-manylinux1_x86_64.whl (357 kB)
     |████████████████████████████████| 357 kB 16.2 MB/s 
Collecting websockets
  Downloading websockets-10.4-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (106 kB)
     |████████████████████████████████| 106 kB 11.6 MB/s 
Collecting pycryptodomex
  Downloading pycryptodomex-3.17-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 16.2 MB/s 
Installing collected packages: certifi, mutagen, brotli, websockets, pycryptodomex, yt-dlp
Successfully installed brotli-1.0.9 certifi-2022.12.7 mutagen-1.46.0 pycryptodomex-3.17 websockets-10.4 yt-dlp-2023.2.17

**Comment by BlindDuck** [comment]
Both ways are fine:
1. zypper update
2. pip install

**Comment by Brodan** [comment]
I'm currently dealing with this same error on my M1 mac as well.
```
$ python -V 
Python 3.9.1
$ pip freeze | grep -i yt-dlp 
yt-dlp==2023.2.17
```

Here's the stacktrace:
```
[youtube] Extracting URL: https://www.youtube.com/watch?v=zf1aZHSXFNU
[youtube] zf1aZHSXFNU: Downloading webpage
[youtube] zf1aZHSXFNU: Downloading android player API JSON
[youtube] zf1aZHSXFNU: Downloading MPD manifest
[info] zf1aZHSXFNU: Downloading 1 format(s): 137+140
[info] There's no subtitles for the requested languages
Traceback (most recent call last):
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/app.py", line 715, in download_url
    extracted_info = ydl.extract_info(url)
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1599, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1658, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2763, in process_video_result
    self.process_info(new_info)
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3186, in process_info
    elif not merger.available:
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 205, in available
    return self.basename is not None
  File "/Users/christopherhranj/.pyenv/versions/3.9.1/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 172, in basename
    self._version  # run property
  File "/Users/christopherhranj/.pyenv/versions/3.9.1/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 197, in _version
    return self._get_version('ffmpeg')
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 184, in _get_version
    basename, version, features = next(filter(
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 185, in <genexpr>
    lambda x: x[1], ((p, *self._get_ffmpeg_version(p)) for p in executables)), (None, None, {}))
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 141, in _get_ffmpeg_version
    out = _get_exe_version_output(path, ['-bsfs'])
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/utils.py", line 2720, in _get_exe_version_output
    stdout, _, ret = Popen.run([encodeArgument(exe)] + args, text=True,
  File "/Users/christopherhranj/giphy/giphy-services/src/python/gce-api/venv/lib/python3.9/site-packages/yt_dlp/utils.py", line 903, in run
    default = '' if proc.text_mode else b''
AttributeError: 'Popen' object has no attribute 'text_mode'
```

**Comment by Brodan** [comment]
@BlindDuck any chance youre calling yt-dlp from within a gevent worker or using uwsgi in your project? this turned out to be my issue and i had uwsgi configured incorrectly: https://github.com/yt-dlp/yt-dlp/issues/6317#issuecomment-1439113185
