### ISSUE TITLE
Youtube livestream: Failed to download m3u8 information: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by JarheadHME** [yt-dlp/yt-dlp#6319]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

When trying to download any livestream on youtube, I get an error that says `Failed to download m3u8 information`, with an `HTTP Error 404: Not Found`

I had a somewhat similar issue with streamlink, and the only thread I could find about said it was some sort of DDoS protection from youtube. I would assume it would also apply to videos if that was the case, but that's why I'm here and checking.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=PZjzfSYocOk']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-19-git-2aec86695a-full_build-www.gyan.dev (setts), ffprobe 2023-02-19-git-2aec86695a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[youtube] Extracting URL: https://www.youtube.com/watch?v=PZjzfSYocOk
[youtube] PZjzfSYocOk: Downloading webpage
[youtube] PZjzfSYocOk: Downloading android player API JSON
[youtube] PZjzfSYocOk: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 404: Not Found
[youtube] PZjzfSYocOk: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: [youtube] PZjzfSYocOk: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1599, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1658, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2599, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1043, in raise_no_formats
yt_dlp.utils.ExtractorError: [youtube] PZjzfSYocOk: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
> * 
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> *

Double check this

**Comment by JarheadHME** [comment]
Definitely was watching the exact stream from the URL in a browser in incognito windows

**Comment by pukkandan** [comment]
@coletdjnz Any idea why this could happen?

**Comment by pukkandan** [comment]
@JarheadHME Could you also try with --live-from-start?

**Comment by JarheadHME** [comment]
> Could you also try with --live-from-start?

Gave it a shot, no dice

**Comment by Safari77** [comment]
can you try
`--extractor-args youtube:skip=hls`

**Comment by JarheadHME** [comment]
> can you try `--extractor-args youtube:skip=hls`

No dice, same issue

**Comment by qpn6ph9q** [comment]
I am getting a similar issue  but with "Too Many Requests". The video was uploaded as a "premier" video if that helps with anything.
```
[debug] Command-line config: ['-vU', '-c', 'https://youtu.be/GwpWmmIq2cg', '-o', '2023-07-15-Podcast.webm']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-72-generic-x86_64-with-glibc2.35 (OpenSSL 3.1.1 30 May 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 0556fff82db6c942a5dfbb9583e2896013847b28b95186b3800f730a8d5e0c0a
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://youtu.be/GwpWmmIq2cg
[youtube] GwpWmmIq2cg: Downloading webpage
[youtube] GwpWmmIq2cg: Downloading ios player API JSON
[youtube] GwpWmmIq2cg: Downloading android player API JSON
[youtube] GwpWmmIq2cg: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[youtube] GwpWmmIq2cg: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[youtube] GwpWmmIq2cg: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
ERROR: [youtube] GwpWmmIq2cg: We're experiencing technical difficulties.
  File "yt_dlp/extractor/common.py", line 710, in extract
  File "yt_dlp/extractor/youtube.py", line 4164, in _real_extract
  File "yt_dlp/extractor/common.py", line 1188, in raise_no_formats
```

**Comment by qpn6ph9q** [comment]
> I am getting a similar issue but with "Too Many Requests". The video was uploaded as a "premier" video if that helps with anything.
> 
> ```
> [debug] Command-line config: ['-vU', '-c', 'https://youtu.be/GwpWmmIq2cg', '-o', '2023-07-15-Podcast.webm']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version stable@2023.07.06 [b532a3481] (linux_exe)
> [debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-72-generic-x86_64-with-glibc2.35 (OpenSSL 3.1.1 30 May 2023, glibc 2.35)
> [debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
> [debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
> [debug] Proxy map: {}
> [debug] Loaded 1855 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Available version: stable@2023.07.06, Current version: stable@2023.07.06
> Current Build Hash: 0556fff82db6c942a5dfbb9583e2896013847b28b95186b3800f730a8d5e0c0a
> yt-dlp is up to date (stable@2023.07.06)
> [youtube] Extracting URL: https://youtu.be/GwpWmmIq2cg
> [youtube] GwpWmmIq2cg: Downloading webpage
> [youtube] GwpWmmIq2cg: Downloading ios player API JSON
> [youtube] GwpWmmIq2cg: Downloading android player API JSON
> [youtube] GwpWmmIq2cg: Downloading m3u8 information
> WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
> [youtube] GwpWmmIq2cg: Downloading m3u8 information
> WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
> [youtube] GwpWmmIq2cg: Downloading m3u8 information
> WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
> ERROR: [youtube] GwpWmmIq2cg: We're experiencing technical difficulties.
>   File "yt_dlp/extractor/common.py", line 710, in extract
>   File "yt_dlp/extractor/youtube.py", line 4164, in _real_extract
>   File "yt_dlp/extractor/common.py", line 1188, in raise_no_formats
> ```

Confirming that as soon as this video premier ended the download was able to proceed as normal.

**Comment by Antar-git** [comment]
happening to me too now cannot download streamlink files
