### ISSUE TITLE
omlet.gg

### ISSUE THREAD

**Issue by TaoziDB** [yt-dlp/yt-dlp#6331]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- single streaming: http://omlet.gg/stream/megaradio
- pick any live link from http://omlet.gg/streams

### Provide a description that is worded well enough to be understood

game streaming site
it uses websocket link to wss://omlet.gg/readonlydevice to handle functions such as: listing streams, listing games, fetching live urls, chat, notification, etc
the live streaming uses 2 live formats: rtmp and m3u8, you can get both urls from websocket above.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'http://omlet.gg/stream/megaradio']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.7.8 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2018.11.29, mutagen-1.45.1, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: http://omlet.gg/stream/megaradio
[generic] megaradio: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] megaradio: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: http://omlet.gg/stream/megaradio
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\yt_dlp\YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\yt_dlp\YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\yt_dlp\extractor\common.py", line 693, in extract
    ie_result = self._real_extract(url)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\yt_dlp\extractor\generic.py", line 2509, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: http://omlet.gg/stream/megaradio
```

**Comment by gamer191** [comment]
> it uses websocket link to wss://omlet.gg/readonlydevice to handle functions such as: listing streams, listing games, fetching live urls, chat, notification, etc
> the live streaming uses 2 live formats: rtmp and m3u8, you can get both urls from websocket above.

@coletdjnz is this even possible to support?

**Comment by Lesmiscore** [comment]
Not whom you're mentioning, but yes
FC2 Live already does this

**Comment by doe1080** [comment]
service ended June 30, 2023
