### ISSUE TITLE
Embeded yt_dlp 2023.02.17 unable to execute when compiled with pyinstaller

### ISSUE THREAD

**Issue by sourabhkv** [yt-dlp/yt-dlp#6338]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Here is my script `hello.py`
```python
import yt_dlp

URL = 'https://www.youtube.com/watch?v=TWMCMvfEAv4'

ydl_opts = {}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(URL, download=False)

a=open("data.txt","w")
a.write(str(info['title']))
a.close()
```

I complied this code with pyinstaller 5.6.2 using the following command
```batchfile
pyinstaller hello.py --hidden-import yt_dlp.compat._legacy
```

After starting program it threw error
```
E:\branch\dist\hello>hello.exe
Traceback (most recent call last):
  File "yt_dlp\compat\compat_utils.py", line 36, in __getattribute__
  File "yt_dlp\compat\compat_utils.py", line 56, in __getattr__
AttributeError: module yt_dlp.dependencies.Cryptodome.Cipher has no attribute AES

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hello.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp\__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp\cookies.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp\aes.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "yt_dlp\dependencies\__init__.py", line 76, in <module>
  File "yt_dlp\compat\compat_utils.py", line 43, in __getattribute__
  File "yt_dlp\compat\compat_utils.py", line 56, in __getattr__
AttributeError: module yt_dlp.dependencies.Cryptodome.Cipher has no attribute AES
[5640] Failed to execute script 'hello' due to unhandled exception!
```

Compiling the code with windowed flag also resulted in same error

Is there any way run my executable without getting errors OR  am I missing hidden import in pyinstaller command

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Can you give the output of the following?

    py -c "from Cryptodome.Cipher import AES; print(AES)"
    py -c "from Crypto.Cipher import AES; print(AES)"

**Comment by sourabhkv** [comment]
```batchfile
E:\branch\dist\hello>py -c "from Cryptodome.Cipher import AES; print(AES)"
<module 'Cryptodome.Cipher.AES' from 'C:\\Users\\soura\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\Cryptodome\\Cipher\\AES.py'>
```

```batchfile
E:\branch\dist\hello>py -c "from Crypto.Cipher import AES; print(AES)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'Crypto'
```
