### ISSUE TITLE
Facebook reel issue

### ISSUE THREAD

**Issue by bibsp** [yt-dlp/yt-dlp#6366]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

URL: https://www.facebook.com/reel/433635305620024
Can't download this video.
On **desktop** browser **This page isn't available.**
On **mobile** browser it is **playable.**

yt-dlp actually can extract URL, because I can stream the video on external video player like MPC-HC, that uses yt-dlp in its backend.
Also I checked list formats command works. `yt-dlp -F https://www.facebook.com/reel/433635305620024` works,
But can't download the video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.facebook.com/reel/433635305620024']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/433635305620024
[facebook] Extracting URL: https://m.facebook.com/watch/?v=433635305620024&_rdr
[facebook] 433635305620024: Downloading webpage
[facebook] 433635305620024: Downloading MPD manifest
[debug] Sort order given by extractor: res, quality
[debug] Formats sorted by: hasvid, ie_pref, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 433635305620024: Downloading 1 format(s): 596333141929259v-1+1145995896087265a
[debug] Invoking http downloader on "https://video.fccu31-1.fna.fbcdn.net/v/t39.25447-2/332476193_599740601968611_6312379216963150433_n.webm?_nc_cat=103&ccb=1-7&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfcjJfdnA5X2dlbjFhdmNfcTkwX2ZyYWdfMl92aWRlbyJ9&_nc_ohc=CCDErtFZbbYAX8bFbpO&_nc_ht=video.fccu31-1.fna&oh=00_AfCEcYuqQnRvqPRvXro3UvnqZtaLTmlyY6vWD_gAwwaRIQ&oe=640134C4"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Navel Weakness - Just imagine your wife is in front in... ｜ By Navel Weakness ｜ Just imagine your wife is in front in morning like this.💥🥵🔥 #reelsfb #reelsviral #lehengalovers #naveladdict # navelbeauty #gendaful #hotsaree #navel... [433635305620024].f596333141929259v-1.webm.part'
Traceback (most recent call last):
  File "yt_dlp\utils.py", line 639, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 272, in download
  File "yt_dlp\downloader\common.py", line 235, in wrapper
  File "yt_dlp\downloader\common.py", line 221, in error_callback
  File "yt_dlp\utils.py", line 6117, in report_retry
  File "yt_dlp\downloader\common.py", line 230, in wrapper
  File "yt_dlp\downloader\common.py", line 241, in sanitize_open
  File "yt_dlp\utils.py", line 642, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Navel Weakness - Just imagine your wife is in front in... ｜ By Navel Weakness ｜ Just imagine your wife is in front in morning like this.💥🥵🔥 #reelsfb #reelsviral #lehengalovers #naveladdict #navelbeauty #gen daful #hotsaree #navel... [433635305620024].f596333141929259v-1.webm.part'


[debug] Invoking http downloader on "https://video.fccu31-1.fna.fbcdn.net/v/t39.25447-2/332689070_532030982406861_4633074505306256988_n.mp4?_nc_cat=101&ccb=1-7&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfYXVkaW9fYWFjcF82NF9mbm9ybTE0X2ZyYWdfMl9hdWRpbyJ9&_nc_ohc=DWdpVVGeSGYAX8zuA8H&_nc_ht=video.fccu31-1.fna&oh=00_AfC_zZHrSR3IXeDg2g-zqwMWML5y9lFoXn-ijbQTNC5pxQ&oe=64012A22"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Navel Weakness - Just imagine your wife is in front in... ｜ By Navel Weakness ｜ Just imagine your wife is in front in morning like this.💥🥵🔥 #reelsfb #reelsviral #lehengalovers #naveladdict # navelbeauty #gendaful #hotsaree #navel... [433635305620024].f1145995896087265a.m4a.part'
Traceback (most recent call last):
  File "yt_dlp\utils.py", line 639, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 272, in download
  File "yt_dlp\downloader\common.py", line 235, in wrapper
  File "yt_dlp\downloader\common.py", line 221, in error_callback
  File "yt_dlp\utils.py", line 6117, in report_retry
  File "yt_dlp\downloader\common.py", line 230, in wrapper
  File "yt_dlp\downloader\common.py", line 241, in sanitize_open
  File "yt_dlp\utils.py", line 642, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Navel Weakness - Just imagine your wife is in front in... ｜ By Navel Weakness ｜ Just imagine your wife is in front in morning like this.💥🥵🔥 #reelsfb #reelsviral #lehengalovers #naveladdict #navelbeauty #gen daful #hotsaree #navel... [433635305620024].f1145995896087265a.m4a.part'
```

**Comment by pukkandan** [comment]
try https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195

**Comment by bibsp** [comment]
Yes it works.
