### ISSUE TITLE
Charlierose.com 400 bad request

### ISSUE THREAD

**Issue by theMadStork** [yt-dlp/yt-dlp#6375]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

When submitting a URL from charlierose.com, the --referer needs to be correctly provided to download. When attempted with the URL only a 400 bad request is the result. I have a list of files that I would like to use with the file (-a) parameter which is not possible for --referer to work (bad request for every entry).

I can get it to work with one video at a time manually setting --referer to the intended URL (https://charlierose.com/videos/21434) and the URL to the extracted URL from the site (https://pfm1hyus01-vh.akamaihd.net/i/GJV/R/1HYGJVR_003_xp.f4v) but it requires renaming and has to be done one by one.

Can this be addressed with the extractor?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://charlierose.com/videos/21434']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI),screen cp1252 (No ANSI)
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.1-2020-11-08-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-08-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[CharlieRose] Extracting URL: https://charlierose.com/videos/21434
[CharlieRose] 21434: Downloading webpage
[CharlieRose] 21434: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 21434: Downloading 1 format(s): 1962
[debug] Invoking hlsnative downloader on "https://pfm1hyus01-vh.akamaihd.net/i/GJV/R/1HYGJVR_003_xp.f4v/index_0_av.m3u8"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3231, in process_info
  File "yt_dlp\YoutubeDL.py", line 2954, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\hls.py", line 66, in real_download
  File "yt_dlp\YoutubeDL.py", line 3726, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by dirkf** [comment]
`Referer` is already being sent. Use `-f 0` to get the .f4v format.

The other formats come from a manifest (m3u8) that the extractor, using `_parse_html5_media_entries()`, is failing to handle properly. Same in yt-dl.

**Comment by theMadStork** [comment]
Excellent! For the future, it could help reduce the site-bug issues if there is a troubleshooting guide for the most common extractor issues. Perhaps each extractor is too different for that to be of much help but this solved my issue.

**Comment by bashonly** [comment]
Let's keep the issue open to track this until it is properly fixed

**Comment by dirkf** [comment]
It's always a good idea to try selecting a specific format if the automatic selection isn't working.

**Comment by gamer191** [comment]
I presume (but haven't tested) that --check-formats would fix this issue. Perhaps we should add that to the error message, although it would result in bugs being missed if a low quality format is available
