### ISSUE TITLE
radiocourtoisie.fr support

### ISSUE THREAD

**Issue by fds39** [yt-dlp/yt-dlp#6377]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

single video : https://www.radiocourtoisie.fr/2023/02/28/ligne-droite-du-28-fevrier-2023/
double video : https://www.radiocourtoisie.fr/2023/02/27/libre-journal-du-lundi-soir-du-27-fevrier-2023-la-france-la-reforme-des-retraites-son-economie-reflexion-sur-la-croissance-davos-et-le-grand-reset-lheure-sur-les-relations-internati/

### Provide a description that is worded well enough to be understood

As the url of this site indicates, it is only about radio programs (audio format only), of about 1h30 embedded on a basic player.
Sometimes 2 programs of 1h30 are proposed on the same url
I noticed that the audio format is mp3 :

![2023-02-28 11_54_51-Libre Journal du lundi soir du 27 février 2023 _ _L'économie française ; La réfo](https://user-images.githubusercontent.com/40143934/221834901-908460cb-b354-45a4-8987-2427556e40d8.png)
nb: These radio programs are freely available for a limited time of less than 10 days

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.radiocourtoisie.fr/2023/02/28/ligne-droite-du-28-fevrier-2023/', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.17763-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-93151-gff03418348, ffprobe N-93151-gff03418348
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://www.radiocourtoisie.fr/2023/02/28/ligne-droite-du-28-fevrier-2023/
[generic] ligne-droite-du-28-fevrier-2023: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ligne-droite-du-28-fevrier-2023: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.radiocourtoisie.fr/2023/02/28/ligne-droite-du-28-fevrier-2023/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\generic.py", line 2509, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.radiocourtoisie.fr/2023/02/28/ligne-droite-du-28-fevrier-2023/
```

**Comment by dirkf** [comment]
The non-JS page for the single "video" has no obvious targets: maybe the embed code could be useful. But there is re-hosting: "Retrouvez toutes les vidéos de cette émission sur la chaîne YouTube de Radio Courtoisie !". Are those different from the audio sought by OP?

**Comment by fds39** [comment]
The videos are removed after one week. The 2 links above do not allow you to enjoy the replay anymore.
here is a new relevant link : https://www.radiocourtoisie.fr/2023/03/04/rcmag-le-libre-court-de-radio-courtoisie-du-4-mars-2023-chronique-anime-manga-kingdom-les-petits-secrets-de-chef-retour-sur-lactu-derniers-accords-du-brexit-et-guerre-en-ukraine/
Some radio shows are filmed in the studio and offer the possibility of replay on youtube: These youtube shows are unfortunately rare.
