### ISSUE TITLE
Akamized: Relative URL not collapsed properly, leading to HTTP 403

### ISSUE THREAD

**Issue by szuro** [yt-dlp/yt-dlp#6385]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Provide a description that is worded well enough to be understood

When downloading a video from akamized (using master.mpd), the video portion downloads fine, but audio is referenced by a relative link, which is not collapsed properly.
When opening the link in a browser, the audio plays as expected.
When using yt-dlp with the collapsed audio URL, it downloads just fine.

The same URL downloads without an issue with a old version of youtube-dl ()

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
# master.mpd download
PS> yt-dlp.exe -vU "https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/master.mpd"
[debug] Command-line config: ['-vU', 'https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/master.mpd']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/master.mpd
[generic] master: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] master: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] master: Downloading 1 format(s): video-2c2b6148+audio-f753a572
[debug] Invoking dashsegments downloader on "https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/master.mpd"
[dashsegments] Total fragments: 623
[download] Destination: master [master].fvideo-2c2b6148.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of  275.87MiB in 00:03:44 at 1.23MiB/s
[debug] Invoking http downloader on "https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/../../../../../parcel/audio/f753a572.mp4?r=dXM%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3213, in process_info
  File "yt_dlp\YoutubeDL.py", line 2954, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\http.py", line 376, in real_download
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3726, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

# Original audio URL download
PS> yt-dlp.exe -vU "https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/../../../../../parcel/audio/f753a572.mp4?r=dXM%3D"
[debug] Command-line config: ['-vU', 'https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/../../../../../parcel/audio/f753a572.mp4?r=dXM%3D']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/../../../../../parcel/audio/f753a572.mp4?r=dXM%3D
[generic] f753a572: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\generic.py", line 2370, in _real_extract
  File "yt_dlp\extractor\common.py", line 838, in _request_webpage

  File "yt_dlp\extractor\common.py", line 820, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3726, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

# Collapsed audio URL download
PS> yt-dlp.exe -vU "https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/parcel/audio/f753a572.mp4?r=dXM%3D"
[debug] Command-line config: ['-vU', 'https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/parcel/audio/f753a572.mp4?r=dXM%3D']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/parcel/audio/f753a572.mp4?r=dXM%3D
[generic] f753a572: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] f753a572: Downloading 1 format(s): mp4
[debug] Invoking http downloader on "https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/parcel/audio/f753a572.mp4?r=dXM%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: f753a572 [f753a572].mp4
[download] 100% of   45.00MiB in 00:00:03 at 12.07MiB/s

# master.mpd download using youtube-dl
PS> youtube-dl.exe -vU "https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/master.mpd"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vU', 'https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/master.mpd']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, pref cp1250
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.10 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev, ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Proxy map: {}
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
[generic] master: Requesting header
WARNING: Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/master.mpd'
[dashsegments] Total fragments: 623
[download] Destination: master-master.fvideo-2c2b6148.mp4
[download] 100% of 275.87MiB in 02:11
[debug] Invoking downloader on 'https://197vod-adaptive.akamaized.net/exp=1677711703~acl=%2Ff4644c8e-ef45-4aba-99c9-0a8ac4ced734%2F%2A~hmac=6aa1b853384f0ae666fc3e69ebe3352e7f5d2333d3e1a3c4282ae707b5b25efd/f4644c8e-ef45-4aba-99c9-0a8ac4ced734/sep/video/03acf773,2c2b6148,516698d2,98322f1b,aac243a2/audio/f753a572,5da6b45e/master.mpd'
[dashsegments] Total fragments: 623
[download] Destination: master-master.faudio-2c2b6148.m4a
[download] 100% of 113.50MiB in 03:45
[ffmpeg] Merging formats into "master-master.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:master-master.fvideo-2c2b6148.mp4" -i "file:master-master.faudio-2c2b6148.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:master-master.temp.mp4"
Deleting original file master-master.fvideo-2c2b6148.mp4 (pass -k to keep)
Deleting original file master-master.faudio-2c2b6148.m4a (pass -k to keep)
```

**Comment by pukkandan** [comment]
I know there's another issue open for this, but can't find it rn. I'll search again when I have more time

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/3355
