### ISSUE TITLE
Unsupported URL for original shows on mlb.tv

### ISSUE THREAD

**Issue by DragonNeos** [yt-dlp/yt-dlp#6391]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I get the Unsupported URL error for videos under the sections Featured on MLB.TV (https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training) and MLB Documentaries (https://www.mlb.com/tv/shows/mlb-documentaries-svod-video-list/small-country-big-dreams-x5028). As you can see, yt-dlp doesn't attempt to use the MLB.tv extractor and uses the generic extractor instead. If I retrieve the direct m3u8 URLs, I can download both videos.

@ischmidt20 Can you take a look at this issue?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109874-gaeceefa622-20230217 (setts), ffprobe N-109874-gaeceefa622-20230217, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training
[generic] quick-question-spring-training: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] quick-question-spring-training: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\generic.py", line 2509, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training

[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.mlb.com/tv/shows/mlb-documentaries-svod-video-list/small-country-big-dreams-x5028']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109874-gaeceefa622-20230217 (setts), ffprobe N-109874-gaeceefa622-20230217, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://www.mlb.com/tv/shows/mlb-documentaries-svod-video-list/small-country-big-dreams-x5028
[generic] small-country-big-dreams-x5028: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] small-country-big-dreams-x5028: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.mlb.com/tv/shows/mlb-documentaries-svod-video-list/small-country-big-dreams-x5028
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\generic.py", line 2509, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.mlb.com/tv/shows/mlb-documentaries-svod-video-list/small-country-big-dreams-x5028
```

**Comment by dirkf** [comment]
1. Modify `MLBVideoIE._VALID_URL`:
```diff
-    _VALID_URL = r'https?://(?:www\.)?mlb\.com/(?:[^/]+/)*video/(?P<id>[^/?&#]+)'
+    _VALID_URL = r'https?://(?:www\.)?mlb\.com/(?:(?:[^/]+/)*video|tv/shows/[^/]+)/(?P<id>[^/?&#]+)'
```
2. The playback data offers media links with `name` (and query parameter `type`) having values `mp4Avc` and `hlsCloud`, but the URLs fail `determine_ext()` on its own in `MLBBaseIE._real_extract()`:
```diff
-            name = playback.get('name')
-            ext = determine_ext(playback_url)
+            name = playback.get('name') or ''
+            ext = {
+                'mp4': 'mp4',
+                'hls': 'm3u8',
+            }.get(name[:3])
+            ext = determine_ext(playback_url, default_ext=ext or 'unknown_video')
+
```
However, the links give 401, even with `Referer`. I guess the login function from `MLBTVIE` is required.

**Comment by DragonNeos** [comment]
@dirkf I added your changes to the MLB extractor and compiled the program, but I still can't download the video. My login credentials or cookies.txt file isn't being used (showing a warning message) when yt-dlp tries to download the video.
```
[debug] Command-line config: ['-vU', '-F', 'https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.18 (win_exe)
[debug] Python 3.11.2 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg N-110043-gadb5f7b41f-20230318 (setts), ffprobe N-110043-gadb5f7b41f-20230318, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1788 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.18
Current Build Hash: 23a1fe36431b2877e5dc61c0721996a923c7e9a017bafbe490dda622480b03e1
yt-dlp is up to date (stable@2023.03.18)
[MLBVideo] Extracting URL: https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training
[MLBVideo] quick-question-spring-training: Downloading JSON metadata
[MLBVideo] dba6a3a1-a09b-4033-a977-8fd5e7afd0b8: Downloading m3u8 information
WARNING: [MLBVideo] Failed to download m3u8 information: HTTP Error 401:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for dba6a3a1-a09b-4033-a977-8fd5e7afd0b8:
ID     EXT           RESOLUTION │ PROTO │ VCODEC  ACODEC
─────────────────────────────────────────────────────────
mp4Avc unknown_video unknown    │ https │ unknown unknown

[debug] Command-line config: ['-vU', '--downloader', 'aria2c', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.18 (win_exe)
[debug] Python 3.11.2 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg N-110043-gadb5f7b41f-20230318 (setts), ffprobe N-110043-gadb5f7b41f-20230318, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1788 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.18
Current Build Hash: 23a1fe36431b2877e5dc61c0721996a923c7e9a017bafbe490dda622480b03e1
yt-dlp is up to date (stable@2023.03.18)
WARNING: [MLBVideo] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[MLBVideo] Extracting URL: https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training
[MLBVideo] quick-question-spring-training: Downloading JSON metadata
[MLBVideo] dba6a3a1-a09b-4033-a977-8fd5e7afd0b8: Downloading m3u8 information
WARNING: [MLBVideo] Failed to download m3u8 information: HTTP Error 401:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] dba6a3a1-a09b-4033-a977-8fd5e7afd0b8: Downloading 1 format(s): mp4Avc
[debug] Invoking aria2c downloader on "https://services.mediaservices.mlbinfra.com/svod?assetUuid=f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset&type=mp4Avc&date=2021-03-29"
[download] Destination: Quick Question： Spring Training [dba6a3a1-a09b-4033-a977-8fd5e7afd0b8].unknown_video
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--http-accept-gzip=true" "--file-allocation=none" -x16 -j16 -s16 --min-split-size 1M --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" --out ".\Quick Question： Spring Training [dba6a3a1-a09b-4033-a977-8fd5e7afd0b8].unknown_video.part" "--auto-file-renaming=false" -- "https://services.mediaservices.mlbinfra.com/svod?assetUuid=f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset&type=mp4Avc&date=2021-03-29"

03/19 19:03:50 [ERROR] CUID#7 - Download aborted. URI=https://services.mediaservices.mlbinfra.com/svod?assetUuid=f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset&type=mp4Avc&date=2021-03-29
Exception: [AbstractCommand.cc:351] errorCode=24 URI=https://services.mediaservices.mlbinfra.com/svod?assetUuid=f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset&type=mp4Avc&date=2021-03-29
  -> [HttpSkipResponseCommand.cc:215] errorCode=24 Authorization failed.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.


ERROR: aria2c exited with code 24
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 969, in main
  File "yt_dlp\__init__.py", line 959, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3369, in download
  File "yt_dlp\YoutubeDL.py", line 3344, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1507, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1615, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2779, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3247, in process_info
  File "yt_dlp\YoutubeDL.py", line 2970, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\external.py", line 76, in real_download
  File "yt_dlp\YoutubeDL.py", line 1015, in report_error
  File "yt_dlp\YoutubeDL.py", line 944, in trouble

[debug] Command-line config: ['-vU', '--downloader', 'aria2c', '--cookies', 'cookies.txt', 'https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.18 (win_exe)
[debug] Python 3.11.2 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg N-110043-gadb5f7b41f-20230318 (setts), ffprobe N-110043-gadb5f7b41f-20230318, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1788 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.18
Current Build Hash: 23a1fe36431b2877e5dc61c0721996a923c7e9a017bafbe490dda622480b03e1
yt-dlp is up to date (stable@2023.03.18)
[MLBVideo] Extracting URL: https://www.mlb.com/tv/shows/mlbtv-featured-svod-video-list/quick-question-spring-training
[MLBVideo] quick-question-spring-training: Downloading JSON metadata
[MLBVideo] dba6a3a1-a09b-4033-a977-8fd5e7afd0b8: Downloading m3u8 information
WARNING: [MLBVideo] Failed to download m3u8 information: HTTP Error 401:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] dba6a3a1-a09b-4033-a977-8fd5e7afd0b8: Downloading 1 format(s): mp4Avc
[debug] Invoking aria2c downloader on "https://services.mediaservices.mlbinfra.com/svod?assetUuid=f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset&type=mp4Avc&date=2021-03-29"
[download] Destination: Quick Question： Spring Training [dba6a3a1-a09b-4033-a977-8fd5e7afd0b8].unknown_video
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--http-accept-gzip=true" "--file-allocation=none" -x16 -j16 -s16 --min-split-size 1M --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" --out ".\Quick Question： Spring Training [dba6a3a1-a09b-4033-a977-8fd5e7afd0b8].unknown_video.part" "--auto-file-renaming=false" -- "https://services.mediaservices.mlbinfra.com/svod?assetUuid=f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset&type=mp4Avc&date=2021-03-29"

03/19 19:07:04 [ERROR] CUID#7 - Download aborted. URI=https://services.mediaservices.mlbinfra.com/svod?assetUuid=f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset&type=mp4Avc&date=2021-03-29
Exception: [AbstractCommand.cc:351] errorCode=24 URI=https://services.mediaservices.mlbinfra.com/svod?assetUuid=f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset&type=mp4Avc&date=2021-03-29
  -> [HttpSkipResponseCommand.cc:215] errorCode=24 Authorization failed.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.


ERROR: aria2c exited with code 24
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 969, in main
  File "yt_dlp\__init__.py", line 959, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3369, in download
  File "yt_dlp\YoutubeDL.py", line 3344, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1507, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1615, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2779, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3247, in process_info
  File "yt_dlp\YoutubeDL.py", line 2970, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\external.py", line 76, in real_download
  File "yt_dlp\YoutubeDL.py", line 1015, in report_error
  File "yt_dlp\YoutubeDL.py", line 944, in trouble
```

If I use the direct m3u8 URL, I can download the video.
```
[debug] Command-line config: ['-vU', '-F', 'https://svod-fst.mlb.com/1679353677_0cf3f0ac73c88828170031e14f13e50489e505944ab7626913b632932b9fb784/MediaService/2021/2021-03/29/f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.18 (win_exe)
[debug] Python 3.11.2 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg N-110043-gadb5f7b41f-20230318 (setts), ffprobe N-110043-gadb5f7b41f-20230318, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1788 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.18
Current Build Hash: 23a1fe36431b2877e5dc61c0721996a923c7e9a017bafbe490dda622480b03e1
yt-dlp is up to date (stable@2023.03.18)
[generic] Extracting URL: https://svod-fst.mlb.com/1679353677_0cf3f0ac73c88828170031e14f13e50489e505944ab7626913b632932b9fb784/MediaService/2021/2021-03/29/f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K.m3u8
[generic] f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K: Downloading webpage
[debug] Identified a direct video link
[generic] f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 unknown    │ m3u8  │ unknown unknown

[debug] Command-line config: ['-vU', '--downloader', 'aria2c', 'https://svod-fst.mlb.com/1679353677_0cf3f0ac73c88828170031e14f13e50489e505944ab7626913b632932b9fb784/MediaService/2021/2021-03/29/f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.18 (win_exe)
[debug] Python 3.11.2 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg N-110043-gadb5f7b41f-20230318 (setts), ffprobe N-110043-gadb5f7b41f-20230318, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1788 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.18
Current Build Hash: 23a1fe36431b2877e5dc61c0721996a923c7e9a017bafbe490dda622480b03e1
yt-dlp is up to date (stable@2023.03.18)
[generic] Extracting URL: https://svod-fst.mlb.com/1679353677_0cf3f0ac73c88828170031e14f13e50489e505944ab7626913b632932b9fb784/MediaService/2021/2021-03/29/f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K.m3u8
[generic] f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K: Downloading webpage
[debug] Identified a direct video link
[generic] f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K: Downloading 1 format(s): 0
[debug] Invoking hlsnative downloader on "https://svod-fst.mlb.com/1679353677_0cf3f0ac73c88828170031e14f13e50489e505944ab7626913b632932b9fb784/MediaService/2021/2021-03/29/f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K.m3u8"
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 92
[download] Destination: f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K-[f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K].mp4
[debug] File locking is not supported. Proceeding without locking
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--http-accept-gzip=true" "--file-allocation=none" -x16 -j16 -s16 "--allow-overwrite=true" "--allow-piece-length-change=true" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" --header "Referer: https://www.mlb.com/" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" "--auto-file-renaming=false" "--file-allocation=none" "--uri-selector=inorder" -i ".\f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K-[f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K].mp4.frag.urls"
[download] 100% of  377.39MiB in 00:01:47 at 3.52MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K-[f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K-[f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K-[f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K-[f4fc7071-8b343ad1-5cad39fa-csvm-diamondx64-asset_5472K].temp.mp4"

**Comment by ischmidt20** [comment]
I think the problem is that the the `MLBTVIE` regex needs to be modified, not `MLBVideoIE`, because `MLBVideo` extractor does not authenticate with MLB.tv credentials. That being said I also wrote the MLB.tv extractor with only games in mind (which have multiple video IDs, one for each broadcast). So there might need to be some additional modifications in the extractor logic itself) to make it fully robust and internally consistent.

Unfortunately I do not have the bandwidth to work on a solution, but keep at it and I'll chime in when I can. My other advice would be is that if you are just downloading videos one-off, you can use the manual method of snooping for the m3u8 and the key and passing the info to yt-dlp manually. But obviously if you are trying to download lots of videos, automate anything, or even include metadata, thumbnails, etc., then a working extractor is preferred.

**Comment by ischmidt20** [comment]
No update, but I was trying to download an MLB.tv show the other day, and I noticed that the browser calls were different—no separate decryption key thus no auth header required. So there will have to be a separate (but probably simpler) procedure in the extractor for getting those videos
