### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by Hereux** [yt-dlp/yt-dlp#6441]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Console said I should report this.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2023.01.06 [6becd25] (pip) API
[debug] params: {'format': 'bestaudio/best', 'writethumbnail': True, 'quiet': True, 'extract_flat': True, 'ingore_errors': True, 'skip_unavailable_fragments': True, 'no_warnings': True, 'noprogress': True, 'outtmpl': 'Downloads/05.03.2023/None.mp3', 'verbose': True, 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3', 'preferredquality': '192'}, {'key': 'FFmpegMetadata', 'add_metadata': 'True'}, {'key': 'EmbedThumbnail', 'already_have_thumbnail': False}], 'compat_opts': set()}
[debug] Python 3.9.2 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1i  8 Dec 2020)
[debug] exe versions: ffmpeg 2021-11-03-git-08a501946f-full_build-www.gyan.dev (setts), ffprobe 2021-11-03-git-08a501946f-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.42.0, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[youtube] Extracting URL: https://youtu.be/02DTN-N8sDY
[youtube] 02DTN-N8sDY: Downloading webpage
[youtube] 02DTN-N8sDY: Downloading android player API JSON
ERROR: [youtube] 02DTN-N8sDY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\youtube.py", line 4049, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\youtube.py", line 4049, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: [youtube] 02DTN-N8sDY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Python_Projekte\Persönlich\YouTube-Downloader.py", line 107, in identification_of_url_type
    liste = ydl.extract_info(user_url, download=False)  # Extrahiert Infos über das Video
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1520, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1012, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\Hereux\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 952, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] 02DTN-N8sDY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
> Console said I should report this.

it also said you should do this:
> Confirm you are on the latest version 

fixed in latest release
