### ISSUE TITLE
ERROR: Postprocessing: Filtering and streamcopy cannot be used together.

### ISSUE THREAD

**Issue by weltonrodrigo** [yt-dlp/yt-dlp#6467]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Using yt-dlp with `-x --audio-format mp3 --postprocessor-args "ffmpeg:-ac 1 -af silenceremove=1:0:-50dB,afade=t=in:d=5"` gives `yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Filtering and streamcopy cannot be used together.`

I have been using yt-dlp with this command for over a year, so I suppose that is something introduced on `ffmpeg`. Another clue that this is a ffmpeg thing is that it occurs after download is complete.

Can't test with older versions because of the slow download issue recently fixed.

Update: a hint is the ffmpeg command-line (added line breaks for readability:

```[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Tertúlia Matinal 338 - Especialidades da 
Seriexologia (Seriexologia) [VOIXwlEbFys].m4a' -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart 
-ac 1 -af silenceremove=1:0:-50dB,afade=t=in:d=5 'file:Tertúlia Matinal 338 - Especialidades da Seriexologia 
(Seriexologia) [VOIXwlEbFys].temp.m4a'
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'bestaudio', '-x', '--audio-format', 'mp3', '--postprocessor-args', 'ffmpeg:-ac 1 -af silenceremove=1:0:-50dB,afade=t=in:d=5', 'VOIXwlEbFys']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.2 (CPython arm64 64bit) - macOS-13.2.1-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: VOIXwlEbFys
[youtube] VOIXwlEbFys: Downloading webpage
[youtube] VOIXwlEbFys: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] VOIXwlEbFys: Downloading 1 format(s): 140
[debug] Invoking dashsegments downloader on "https://rr3---sn-oxunxg8pjvn-cncl.googlevideo.com/videoplayback?expire=1678243910&ei=5qMHZN3zOtKjobIP_PGqsA4&ip=2804%3A14c%3A658b%3A5145%3Aa1ad%3Ab8cf%3A33c4%3Af857&id=o-ALNmG53TVoD1Gb3YSPc_ObVOibjL24kSntakZylM1Okl&itag=140&source=youtube&requiressl=yes&mh=a8&mm=31%2C29&mn=sn-oxunxg8pjvn-cncl%2Csn-gpv7kne7&ms=au%2Crdu&mv=m&mvi=3&pl=52&initcwndbps=1185000&spc=H3gIhkI80RZvAQ6QHTDS2HG5c0MU79Y&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=107560548&dur=6646.107&lmt=1678219953050480&mt=1678221950&fvip=4&keepalive=yes&fexp=24007246&c=ANDROID&txp=3318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKzW8IjZAY7iCqv8tIC311NsO8V2ZdNuFgp2Y2R0ON6OAiEA97A238uqrr7JU8wwt-pbpdlMJzImgalJA-CkYY4Sinw%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGX92lujk85rXBxzHsJYHyaGqUmIuGPMmpWG6_555n70CIQD2e3o_QKy34XncNECrgWmR2z_9o7qedl3vHo4BTj-8PA%3D%3D"
[dashsegments] Total fragments: 11
[download] Destination: Tertúlia Matinal 338 - Especialidades da Seriexologia (Seriexologia) [VOIXwlEbFys].m4a
[download] 100% of  102.58MiB in 00:00:08 at 12.38MiB/s
[FixupM4a] Correcting container of "Tertúlia Matinal 338 - Especialidades da Seriexologia (Seriexologia) [VOIXwlEbFys].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Tertúlia Matinal 338 - Especialidades da Seriexologia (Seriexologia) [VOIXwlEbFys].m4a' -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart -ac 1 -af silenceremove=1:0:-50dB,afade=t=in:d=5 'file:Tertúlia Matinal 338 - Especialidades da Seriexologia (Seriexologia) [VOIXwlEbFys].temp.m4a'
[debug] ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_5 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Tertúlia Matinal 338 - Especialidades da Seriexologia (Seriexologia) [VOIXwlEbFys].m4a':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    creation_time   : 2023-03-07T20:08:25.000000Z
  Duration: 01:50:46.11, start: 0.000000, bitrate: 129 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 0 kb/s (default)
    Metadata:
      creation_time   : 2023-03-07T20:08:25.000000Z
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
Filtergraph 'silenceremove=1:0:-50dB,afade=t=in:d=5' was defined for audio output stream 0:0 but codec copy was selected.
Filtering and streamcopy cannot be used together.

ERROR: Postprocessing: Filtering and streamcopy cannot be used together.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3502, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3484, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 876, in run
    self._fixup('Correcting container', info['filepath'], [*self.stream_copy_opts(), '-f', 'mp4'])
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 857, in _fixup
    self.run_ffmpeg(filename, temp_filename, options)
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 369, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 324, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 362, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Filtering and streamcopy cannot be used together.
```

**Comment by pukkandan** [comment]
> --postprocessor-args "ffmpeg:

This add the args to all ffmpeg invocations. You only want it for `ExtractAudio+ffmpeg`

**Comment by weltonrodrigo** [comment]
That fixed it. Thanks!
