### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by Goooler** [yt-dlp/yt-dlp#6469]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

```sh
yt-dlp --concurrent-fragments 64 https://www.youtube.com/watch?v=X9u1taDwLSA
[youtube] X9u1taDwLSA: Downloading webpage
[youtube] X9u1taDwLSA: Downloading android player API JSON
[youtube] X9u1taDwLSA: Downloading player 21246a91
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = 4-YtrZl40OOGU16Pc ; player = https://www.youtube.com/s/player/21246a91/player_ias.vflset/en_US/base.js
X9u1taDwLSA: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2421, in _extract_n_function_name
    return self._search_regex(
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: [youtube] X9u1taDwLSA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --concurrent-fragments 64 https://www.youtube.com/watch?v=X9u1taDwLSA
[debug] Command-line config: ['-vU', '--concurrent-fragments', '64', 'https://www.youtube.com/watch?v=X9u1taDwLSA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.9.16 (CPython 64bit) - macOS-13.2-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
Latest version: 2023.03.04, Current version: 2022.01.21
ERROR: It looks like you installed yt-dlp with a package manager, pip, setup.py or a tarball; Use that to update
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=X9u1taDwLSA
[youtube] X9u1taDwLSA: Downloading webpage
[youtube] X9u1taDwLSA: Downloading android player API JSON
[youtube] X9u1taDwLSA: Downloading player 21246a91
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = piIsGN8O-ACif0SEZ ; player = https://www.youtube.com/s/player/21246a91/player_ias.vflset/en_US/base.js
X9u1taDwLSA: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2421, in _extract_n_function_name
    return self._search_regex(
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] X9u1taDwLSA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 3331, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by Goooler** [comment]
Same error when running `yt-dlp https://www.youtube.com/watch\?v\=X9u1taDwLSA`

**Comment by coletdjnz** [comment]
>  I've verified that I'm running yt-dlp version 2023.03.04 (update instructions) or later (specify commit)

you're running an ancient version

**Comment by Goooler** [comment]
It the latest

https://github.com/yt-dlp/yt-dlp/releases/tag/2023.03.04

**Comment by coletdjnz** [comment]
> It's the latest.
> 
> https://github.com/yt-dlp/yt-dlp/releases/tag/2023.03.04

Your log shows you are running 2022.01.21

**Comment by Goooler** [comment]
You are right, forgot that.

**Comment by Goooler** [comment]
Reinstalled via brew, same error.

```
 snebula@MBP  ~/Downloads  brew remove yt-dlp
==> Downloading https://formulae.brew.sh/api/cask.jws.json
##O#-#
==> Downloading https://formulae.brew.sh/api/formula.jws.json
##O#-#
Uninstalling /opt/homebrew/Cellar/yt-dlp/2023.3.4... (2,331 files, 26MB)
 snebula@MBP  ~/Downloads  brew install yt-dlp
==> Fetching yt-dlp
==> Downloading https://ghcr.io/v2/homebrew/core/yt-dlp/manifests/2023.3.4
Already downloaded: /Users/snebula/Library/Caches/Homebrew/downloads/17b939a4e58b3394767bd17b3aa742a5b31a6558868ebb7b4642ef631af13ad1--yt-dlp-2023.3.4.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/yt-dlp/blobs/sha256:6a0e990cd6d8e33ed7abcde743b0c12
Already downloaded: /Users/snebula/Library/Caches/Homebrew/downloads/5fd82dd44a80722478e2cac85913fbf440c7727921c931339032006b17f23f1d--yt-dlp--2023.3.4.arm64_ventura.bottle.tar.gz
==> Pouring yt-dlp--2023.3.4.arm64_ventura.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/yt-dlp
Target /opt/homebrew/bin/yt-dlp
already exists. You may want to remove it:
  rm '/opt/homebrew/bin/yt-dlp'

To force the link and overwrite all conflicting files:
  brew link --overwrite yt-dlp

To list all files that would be deleted:
  brew link --overwrite --dry-run yt-dlp

Possible conflicting files are:
/opt/homebrew/bin/yt-dlp
/opt/homebrew/share/fish/vendor_completions.d/yt-dlp.fish
/opt/homebrew/share/man/man1/yt-dlp.1
/opt/homebrew/share/zsh/site-functions/_yt-dlp
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/yt-dlp/2023.3.4: 2,331 files, 26MB
==> Running `brew cleanup yt-dlp`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
 ✘ snebula@MBP  ~/Downloads  yt-dlp  https://www.youtube.com/watch\?v\=X9u1taDwLSA
[youtube] X9u1taDwLSA: Downloading webpage
[youtube] X9u1taDwLSA: Downloading android player API JSON
[youtube] X9u1taDwLSA: Downloading player 21246a91
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = PmLa69MJqxdzudaAa ; player = https://www.youtube.com/s/player/21246a91/player_ias.vflset/en_US/base.js
X9u1taDwLSA: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 2421, in _extract_n_function_name
    return self._search_regex(
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: [youtube] X9u1taDwLSA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by Goooler** [comment]
```sh
 snebula@MBP  ~  brew info yt-dlp
==> yt-dlp: stable 2023.3.4 (bottled), HEAD
Fork of youtube-dl with additional features and fixes
https://github.com/yt-dlp/yt-dlp
/opt/homebrew/Cellar/yt-dlp/2023.3.4 (2,331 files, 26MB)
  Poured from bottle using the formulae.brew.sh API on 2023-03-08 at 13:02:25
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/yt-dlp.rb
License: Unlicense
==> Dependencies
Required: python@3.11 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 15,677 (30 days), 64,094 (90 days), 264,371 (365 days)
install-on-request: 13,059 (30 days), 52,032 (90 days), 196,264 (365 days)
build-error: 1 (30 days)
 snebula@MBP  ~  yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.9.16 (CPython 64bit) - macOS-13.2-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

**Comment by Lesmiscore** [comment]
Read the error message. Run: 
```
rm '/opt/homebrew/bin/yt-dlp'
brew update
brew upgrade yt-dlp
```

**Comment by Goooler** [comment]
```
 snebula@MBP  ~  rm '/opt/homebrew/bin/yt-dlp'
brew update
brew upgrade yt-dlp
Already up-to-date.
Warning: yt-dlp 2023.3.4 already installed
```

**Comment by Goooler** [comment]
Finished, need `brew link --overwrite yt-dlp`.
