### ISSUE TITLE
Support downloading all videos from a Facebook page

### ISSUE THREAD

**Issue by dreamflasher** [yt-dlp/yt-dlp#6518]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.facebook.com/dieanstalt.kabarettarchiv/videos (lists all videos of a facebook page)
https://www.facebook.com/watch/1104963652946528/264543514160928 (a playlist)

### Provide a description that is worded well enough to be understood

For YouTube it's possible to download a whole channel or a single playlist. It would be great if for Facebook Pages the same would be supported: Download all videos of a facebook page and download a full playlist of a facebook page.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.facebook.com/dieanstalt.kabarettarchiv/videos']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.facebook.com/dieanstalt.kabarettarchiv/videos
[generic] videos: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] videos: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.facebook.com/dieanstalt.kabarettarchiv/videos
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/dieanstalt.kabarettarchiv/videos
```

**Comment by jimsy3** [comment]
and can you add the same thing/feature for all videos on a youtube channel ?
like you paste only the channel link and it will download all videos.... or maybe needs a Gui for that feature and then you could select/tick the needed videos with a mouse?

**Comment by dreamflasher** [comment]
Afaik they do, but not in this case: for the linked page you do not need to be logged in, it's a public page and you can access all videos without authentication. 
So I believe this is allowed according to yt-dlp rules?

**Comment by dreamflasher** [comment]
@pukkandan would you be down for adding support for facebook pages and playlists?

I tried to understand how it's done for youtube channels and playlists, but didn't understand it well enough to make a PR myself: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/youtube.py#L6379

**Comment by doxatotheo** [comment]
I got this message while trying to get a "reel" from facebook :

`yt -vF https://www.facebook.com/reel/1698469473937314
[debug] Command-line config: ['-vF', 'https://www.facebook.com/reel/1698469473937314']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-78-generic-x86_64-with-glibc2.35 (OpenSSL 3.1.1 30 May 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1698469473937314
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1698469473937314&_rdr
[facebook] 1698469473937314: Downloading webpage
ERROR: [facebook] 1698469473937314: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1709, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2732, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 1073, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 1698469473937314: No video formats found!`

**Comment by bashonly** [comment]
@doxatotheo `yt-dlp --update-to nightly`

**Comment by gosuimbalyndh** [comment]
Can we down

> @pukkandan would you be down for adding support for facebook pages and playlists?
> 
> I tried to understand how it's done for youtube channels and playlists, but didn't understand it well enough to make a PR myself: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/youtube.py#L6379

Thank you much
I don't quite understand: how to download Facebook story? I try the method here but not working: https://www.youtube.com/watch?v=RtFmeJQ5Jlg

For instances the URL of stories video: https://www.facebook.com/stories/1052288...xxxx
Can we download that?

**Comment by Aholicknight** [comment]
bump
