### ISSUE TITLE
Unable to download certain videos from sbs.com.au, possibly related to dash streams

### ISSUE THREAD

**Issue by gc248** [yt-dlp/yt-dlp#6519]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

Downloads of certain videos (but not others) from sbs.com.au result in an unplayable file. The video stream appears to be corrupt.

Example of a non-working URL: https://www.sbs.com.au/ondemand/watch/1823195203548

Example of a similar working URL: https://www.sbs.com.au/ondemand/watch/1814545987680

It appears that the videos that do not download correctly use "dash" streams, while the ones that work do not.

By using Firefox and disabling the Widevine plugin, I believe I have confirmed that the videos in question do not appear to be protected by Widevine DRM.

Please note that although a (free) account is required to play videos from sbs.com.au in the browser, these credentials are not needed to download them using yt-dlp.

I'll also attach ffprobe output for the non-working downloaded file, showing h264 decoding errors and nonsense parameters for the video stream.

This is my first time reporting an issue here, so I apologise if I have missed anything. Please let me know if I can provide any more details to assist. Thanks for your time and efforts.

[ffprobe-output.txt](https://github.com/yt-dlp/yt-dlp/files/10950482/ffprobe-output.txt)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.sbs.com.au/ondemand/watch/1823195203548', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev (setts), ffprobe 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[SBS] Extracting URL: https://www.sbs.com.au/ondemand/watch/1823195203548
[SBS] 1823195203548: Downloading JSON metadata
[ThePlatform] Extracting URL: http://link.theplatform.com/s/Bgtm9B/uOlBz65O39ey?feed=Video%20-%20Single&mbr=true&manifest=m3u&ord=8990372&policy=11929623&dfptag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.entertainment.sbs.com.au%2Fsec30htmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dpreroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1823195203548%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1823195203548&dfpmidtag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.entertainment.sbs.com.au%2Fsec30midrollhtmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dmidroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1823195203548%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1823195203548#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] uOlBz65O39ey: Downloading SMIL data
[ThePlatform] uOlBz65O39ey: Downloading MPD manifest
[ThePlatform] uOlBz65O39ey: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] uOlBz65O39ey: Downloading 1 format(s): dash-stream_3+dash-stream_4
[debug] Invoking dashsegments downloader on "https://sbs-vod-prod-01.akamaized.net/Content/DASH_HBBTV/VOD/open/16728/12474/aa7ddb61-320a-4b13-bcab-65f2f849edff/9439a831-9b13-6280-ed4f-cb66148195cb/manifest.mpd"
[dashsegments] Total fragments: 1349
[download] Destination: Taskmaster S4 Ep4 - Friendship Is Truth [uOlBz65O39ey].fdash-stream_3.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of  281.49MiB in 00:03:12 at 1.46MiB/s
[debug] Invoking dashsegments downloader on "https://sbs-vod-prod-01.akamaized.net/Content/DASH_HBBTV/VOD/open/16728/12474/aa7ddb61-320a-4b13-bcab-65f2f849edff/9439a831-9b13-6280-ed4f-cb66148195cb/manifest.mpd"
[dashsegments] Total fragments: 1349
[download] Destination: Taskmaster S4 Ep4 - Friendship Is Truth [uOlBz65O39ey].fdash-stream_4.m4a
[download] 100% of   63.29MiB in 00:03:05 at 349.61KiB/s
[Merger] Merging formats into "Taskmaster S4 Ep4 - Friendship Is Truth [uOlBz65O39ey].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Taskmaster S4 Ep4 - Friendship Is Truth [uOlBz65O39ey].fdash-stream_3.mp4" -i "file:Taskmaster S4 Ep4 - Friendship Is Truth [uOlBz65O39ey].fdash-stream_4.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Taskmaster S4 Ep4 - Friendship Is Truth [uOlBz65O39ey].temp.mp4"
Deleting original file Taskmaster S4 Ep4 - Friendship Is Truth [uOlBz65O39ey].fdash-stream_3.mp4 (pass -k to keep)
Deleting original file Taskmaster S4 Ep4 - Friendship Is Truth [uOlBz65O39ey].fdash-stream_4.m4a (pass -k to keep)
```

**Comment by gc248** [comment]
It seems the behaviour has changed again since I opened this issue. See new output below.

[Issue 6543](https://github.com/yt-dlp/yt-dlp/issues/6543#issue-1624953146) seems to have some additional information.

`[debug] Command-line config: ['https://www.sbs.com.au/ondemand/watch/1823195203548', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev (setts), ffprobe 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[SBS] Extracting URL: https://www.sbs.com.au/ondemand/watch/1823195203548
[SBS] 1823195203548: Downloading JSON metadata
[ThePlatform] Extracting URL: http://link.theplatform.com/s/Bgtm9B/uOlBz65O39ey?feed=Video%20-%20Single&mbr=true&manifest=m3u&ord=3984820&policy=11929623&dfptag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.entertainment.sbs.com.au%2Fsec30htmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dpreroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1823195203548%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1823195203548&dfpmidtag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.entertainment.sbs.com.au%2Fsec30midrollhtmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dmidroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1823195203548%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1823195203548#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] uOlBz65O39ey: Downloading SMIL data
[ThePlatform] uOlBz65O39ey: Downloading MPD manifest
WARNING: [ThePlatform] Failed to download MPD manifest: HTTP Error 403: Forbidden
[ThePlatform] uOlBz65O39ey: Downloading JSON metadata
ERROR: [ThePlatform] uOlBz65O39ey: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1615, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1727, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2615, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1046, in raise_no_formats
yt_dlp.utils.ExtractorError: [ThePlatform] uOlBz65O39ey: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
`
