### ISSUE TITLE
[vimeo] bestaudio download fails with 403 Forbidden for some embedded links with vimeo vids

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#6526]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

test link (originally embedded on this page:https://www.mylifefestival.it/giorno2/):
https://player.vimeo.com/video/802659335?h=c5b1fac0e2&badge=0&autopause=0&player_id=0&app_id=58479#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.mylifefestival.it%2Fgiorno2%2F%22%7D%7D

Trying to run ./yt-dlp -f "bestaudio" fails. 

Also, for some reason best audio here is considered to be dash-fastly_skyfire_sep-audio-4479401a (3.62MiB , 98k) (also fails if set with -f dash-fastly_skyfire_sep-audio-4479401a). However best in this case is obviously: dash-akfire_interconnect_quic_sep-audio-81cc725d or dash-fastly_skyfire_sep-audio-81cc725d (9.43MiB,  255k). Both download just fine, by the way with -f 

If needed I'll gladly provide at least 3 more links like that for testing where best audio fails. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -f "bestaudio" "https://player.vimeo.com/video/802659335?h=c5b1fac0e2&badge=0&autopause=0&player_id=0&app_id=58479#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.mylifefestival.it%2Fgiorno2%2F%22%7D%7D"
[debug] Command-line config: ['-vU', '-f', 'bestaudio', 'https://player.vimeo.com/video/802659335?h=c5b1fac0e2&badge=0&autopause=0&player_id=0&app_id=58479#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.mylifefestival.it%2Fgiorno2%2F%22%7D%7D']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.03 [934496428] (zip)
[debug] Python 3.11.2 (CPython arm64 64bit) - macOS-13.2.1-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1845 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.03
Current Build Hash: f70c46dc4e92512634f1f34fa9a029f749941932b8623c88b6632ee0b6f806d0
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Updating to stable@2023.03.04 ...
[debug] Downloading yt-dlp from https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/latest/download/SHA2-256SUMS
Updated yt-dlp to stable@2023.03.04
[debug] Restarting: /opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python ./yt-dlp -vU -f bestaudio 'https://player.vimeo.com/video/802659335?h=c5b1fac0e2&badge=0&autopause=0&player_id=0&app_id=58479#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.mylifefestival.it%2Fgiorno2%2F%22%7D%7D'
[debug] Command-line config: ['-vU', '-f', 'bestaudio', 'https://player.vimeo.com/video/802659335?h=c5b1fac0e2&badge=0&autopause=0&player_id=0&app_id=58479#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.mylifefestival.it%2Fgiorno2%2F%22%7D%7D']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.11.2 (CPython arm64 64bit) - macOS-13.2.1-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1787 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[vimeo] Extracting URL: https://player.vimeo.com/video/802659335?h=c5b1fac0e2&badge=0&autopause=0&player_id=0&app_id=58479#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.mylifefestival.it%2Fgiorno2%2F%22%7D%7D
[vimeo] 802659335: Downloading webpage
[vimeo] 802659335: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 802659335: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 802659335: Downloading fastly_skyfire m3u8 information
[vimeo] 802659335: Downloading fastly_skyfire m3u8 information
[vimeo] 802659335: Downloading akfire_interconnect_quic MPD information
[vimeo] 802659335: Downloading akfire_interconnect_quic MPD information
[vimeo] 802659335: Downloading fastly_skyfire MPD information
[vimeo] 802659335: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] 802659335: Downloading 1 format(s): dash-fastly_skyfire_sep-audio-4479401a
[debug] Invoking http downloader on "https://skyfire.vimeocdn.com/1678661932-0xeccd3e7fe7d7ac9746554d5cdffe628895235c40/30767850-bd01-432b-a2ff-d6c49ef369ae/sep/video/417fc67f,81cc725d,8b266fec,9469bd42,a5ab2402/audio/fe77384a,4479401a,7b15d798/../../../../../parcel/audio/4479401a.mp4?r=dXM%3D"
[download] Resuming download at byte 3296822
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3247, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 2970, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/downloader/http.py", line 376, in real_download
    establish_connection()
  File "./yt-dlp/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by dirkf** [comment]
Working in yt-dl git master, where there is no `../` sequence in the media link. #6385 is a similar problem and I guess they can be solved together.

Also, this was a good test for fixing https://github.com/ytdl-org/youtube-dl/issues/21467.

**Comment by dirkf** [comment]
Selecting the same actual format `dash-fastly_skyfire_sep-audio-4479401a` provokes the error in yt-dl, which prefers a DASH format where the downloader explicitly calls `urljoin()`. Then we have #3355 because no path munging is done in the HTTP downloader. The failing URL
```
https://skyfire.vimeocdn.com/1678661932-0xeccd3e7fe7d7ac9746554d5cdffe628895235c40/30767850-bd01-432b-a2ff-d6c49ef369ae/sep/video/417fc67f,81cc725d,8b266fec,9469bd42,a5ab2402/audio/fe77384a,4479401a,7b15d798/../../../../../parcel/audio/4479401a.mp4?r=dXM%3D
```
becomes
```
https://skyfire.vimeocdn.com/1678661932-0xeccd3e7fe7d7ac9746554d5cdffe628895235c40/30767850-bd01-432b-a2ff-d6c49ef369ae/parcel/audio/4479401a.mp4?r=dXM%3D
```
which succeeds.

**Comment by someziggyman** [comment]
More test links for this case:
https://player.vimeo.com/video/502184266
https://player.vimeo.com/video/502572803

-beast audio and all OPUS related audio params fail. For example: 
dash-akfire_interconnect_quic_sep-audio-682c6f17
dash-fastly_skyfire_sep-audio-682c6f17
dash-akfire_interconnect_quic_sep-audio-1ab324a8
dash-fastly_skyfire_sep-audio-1ab324a8

**Comment by dirkf** [comment]
Working in yt-dl with commit https://github.com/ytdl-org/youtube-dl/commit/e8de54bce50f6f77a4d7e8e80675f7003d5bf630.

**Comment by someziggyman** [comment]
> Working in yt-dl with commit [ytdl-org/youtube-dl@e8de54b](https://github.com/ytdl-org/youtube-dl/commit/e8de54bce50f6f77a4d7e8e80675f7003d5bf630).

indeed it works there. Thanks a lot! 
Not a big deal, but why is OPUS encoded audio with lower bitrate is considered best here, while there are m4a encoded audio with 255kbps bitrate? Just curious. Apologies, if it's a stupid question.

**Comment by pukkandan** [comment]
@coletdjnz The patch for this interferes with networking rework. Could you have a look? Or should I merge as-is and deal with conflict later?

**Comment by jamesdeluk** [comment]
> Working in yt-dl with commit [ytdl-org/youtube-dl@e8de54b](https://github.com/ytdl-org/youtube-dl/commit/e8de54bce50f6f77a4d7e8e80675f7003d5bf630).

Is there a simple(ish) way to get this working now, or is it best to wait for the next release?

**Comment by coletdjnz** [comment]
Should be fixed by https://github.com/yt-dlp/yt-dlp/pull/7662
