### ISSUE TITLE
ETOnline page downloads silent 

### ISSUE THREAD

**Issue by therentabrain** [yt-dlp/yt-dlp#6529]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

File downloads with video only
I believe this worked with previous versions of yt-dlp at some point, but it's been a long time so I don't know what changed
thank you!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.etonline.com/media/videos/siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.etonline.com/media/videos/siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive
[generic] siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[generic] Extracting URL: https://cbsi-etonline-video-fastly.global.ssl.fastly.net/2019/08/23/1591814723658/205409_hls/master.m3u8#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive%22%2C+%22to_generic%22%3A+true%2C+%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.etonline.com%2Fmedia%2Fvideos%2Fsiren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive%22%7D%7D
[generic] siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive: Downloading webpage
[debug] Identified a direct video link
[generic] siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive: Downloading 1 format(s): 3142+et_102318_elinepowellmp4-5717942251001_205409_aac_128-ENGLISH
[debug] Invoking hlsnative downloader on "https://cbsi-etonline-video-fastly.global.ssl.fastly.net/2019/08/23/1591814723658/205409_hls/et_102318_elinepowellmp4-5717942251001_205409_3000/stream.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 34
[download] Destination: 'Siren' Star Eline Powell Trained to Hold Her Breath For Over 3 Minutes on New Series (Exclusive) [siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive].f3142.mp4
[debug] File locking is not supported. Proceeding without locking

[download]   0.0% of ~  67.88MiB at   14.29KiB/s ETA 01:21:05 (frag 0/34)
[download]   0.0% of ~  67.88MiB at   41.96KiB/s ETA 27:36 (frag 0/34)   
[download]   0.0% of ~  67.88MiB at   95.24KiB/s ETA 12:09 (frag 0/34)
[download]   0.0% of ~  67.88MiB at  200.00KiB/s ETA 05:47 (frag 0/34)
[download]   0.0% of ~  67.88MiB at  405.23KiB/s ETA 02:51 (frag 0/34)
[download]   0.1% of ~  67.88MiB at  736.84KiB/s ETA 01:34 (frag 0/34)
[download]   0.2% of ~  67.88MiB at    1.25MiB/s ETA 00:54 (frag 0/34)
( ... )
[download]  99.1% of ~  73.17MiB at    1.22MiB/s ETA 00:00 (frag 33/34)
[download]  99.2% of ~  73.17MiB at    2.24MiB/s ETA 00:00 (frag 33/34)
[download]  99.6% of ~  73.17MiB at    3.96MiB/s ETA 00:00 (frag 33/34)
[download] 100.0% of ~  73.17MiB at    5.55MiB/s ETA 00:00 (frag 33/34)
[download] 100.0% of ~  73.17MiB at    5.42MiB/s ETA 00:00 (frag 34/34)
[download] 100% of   73.17MiB in 00:00:07 at 9.69MiB/s                 
[debug] Invoking hlsnative downloader on "https://cbsi-etonline-video-fastly.global.ssl.fastly.net/2019/08/23/1591814723658/205409_hls/et_102318_elinepowellmp4-5717942251001_205409_aac_128/stream.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 34
[download] Destination: 'Siren' Star Eline Powell Trained to Hold Her Breath For Over 3 Minutes on New Series (Exclusive) [siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive].fet_102318_elinepowellmp4-5717942251001_205409_aac_128-ENGLISH.mp4
ERROR: unable to download video data: [Errno 2] No such file or directory: "'Siren' Star Eline Powell Trained to Hold Her Breath For Over 3 Minutes on New Series (Exclusive) [siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive].fet_102318_elinepowellmp4-5717942251001_205409_aac_128-ENGLISH.mp4.ytdl"
Traceback (most recent call last):
  File "yt_dlp\utils.py", line 661, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3229, in process_info
  File "yt_dlp\YoutubeDL.py", line 2970, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\hls.py", line 148, in real_download
  File "yt_dlp\downloader\fragment.py", line 81, in _prepare_and_start_frag_download
  File "yt_dlp\downloader\fragment.py", line 205, in _prepare_frag_download
  File "yt_dlp\downloader\fragment.py", line 101, in _write_ytdl_file
  File "yt_dlp\downloader\common.py", line 235, in wrapper
  File "yt_dlp\downloader\common.py", line 221, in error_callback
  File "yt_dlp\utils.py", line 6149, in report_retry
  File "yt_dlp\downloader\common.py", line 230, in wrapper
  File "yt_dlp\downloader\common.py", line 241, in sanitize_open
  File "yt_dlp\utils.py", line 664, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: "'Siren' Star Eline Powell Trained to Hold Her Breath For Over 3 Minutes on New Series (Exclusive) [siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive].fet_102318_elinepowellmp4-5717942251001_205409_aac_128-ENGLISH.mp4.ytdl"
```

**Comment by bashonly** [comment]
This is happening because the filename is too long for Windows. Use `--output`/`-o` to remedy to this, e.g.:
```
yt-dlp -o "%(title).100B [%(id)s].%(ext)s" "https://www.etonline.com/media/videos/siren-star-eline-powell-trained-hold-her-breath-over-3-minutes-new-series-exclusive"
```
See the [FAQ in pinned issues](https://github.com/yt-dlp/yt-dlp/issues/3766) or the [output template section of the readme](https://github.com/yt-dlp/yt-dlp#output-template)

Closing as duplicate

**Comment by therentabrain** [comment]
Thank you for sleuthing it!  

Shouldn't "make filenames Windows-compatible if on Windows" (default) be taking care of this for us?
