### ISSUE TITLE
[aenetworks] 'list index out of range' error preventing download

### ISSUE THREAD

**Issue by Heyman1Niceshot** [yt-dlp/yt-dlp#6530]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I have tried a couple streams that use [aenetworks] and all fail with list index out of range. Verbose debug information attached.

I have tried with --ap-username/--ap-password and --cookies-from-browser Chrome; both fail the same. This was working a week ago. I tried a show from History and A&E.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\great>yt-dlp --cookies-from-browser Chrome -vU https://play.history.com/shows/the-food-that-built-america/season-4/episode-4
[debug] Command-line config: ['--cookies-from-browser', 'Chrome', '-vU', 'https://play.history.com/shows/the-food-that-built-america/season-4/episode-4']
[debug] Portable config "C:\Program Files\youtube-dl\yt-dlp.conf": ['--no-mtime', '-o', 'E:\\Videos\\Youtube\\%(title)s.%(ext)s', '--merge-output-format', 'mkv', '--embed-thumbnail', '--embed-metadata']
[debug] User config "C:\Users\great\AppData\Roaming\yt-dlp\config.txt": ['--no-mtime', '-o', 'E:\\Videos\\Youtube\\%(title)s.%(ext)s', '--recode-video', 'mkv', '--embed-thumbnail', '--embed-metadata']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.03.12.235230 [98ac902c4] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.1-2020-11-08-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-08-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\great\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\great\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 5259 cookies from chrome
[debug] cookie version breakdown: {'v10': 5259, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1788 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.03.13.014401, Current version: nightly@2023.03.12.235230
Current Build Hash: b98b130b2a385c27b1b9f70384654313291c38c90adf175264578dabb4008b47
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
Updating to nightly@2023.03.13.014401 ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/yt-dlp.exe
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/SHA2-256SUMS
Updated yt-dlp to nightly@2023.03.13.014401
[debug] Restarting: yt-dlp --cookies-from-browser Chrome -vU "https://play.history.com/shows/the-food-that-built-america/season-4/episode-4"
[debug] Command-line config: ['--cookies-from-browser', 'Chrome', '-vU', 'https://play.history.com/shows/the-food-that-built-america/season-4/episode-4']
[debug] Portable config "C:\Program Files\youtube-dl\yt-dlp.conf": ['--no-mtime', '-o', 'E:\\Videos\\Youtube\\%(title)s.%(ext)s', '--merge-output-format', 'mkv', '--embed-thumbnail', '--embed-metadata']
[debug] User config "C:\Users\great\AppData\Roaming\yt-dlp\config.txt": ['--no-mtime', '-o', 'E:\\Videos\\Youtube\\%(title)s.%(ext)s', '--recode-video', 'mkv', '--embed-thumbnail', '--embed-metadata']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.03.13.014401 [607510b9f] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.1-2020-11-08-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-08-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\great\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\great\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 5259 cookies from chrome
[debug] cookie version breakdown: {'v10': 5259, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1788 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.03.13.014401, Current version: nightly@2023.03.13.014401
Current Build Hash: 1c92b3a04c54b86ad615ea89a6dd80f3321e10af69cb28c8a914bb12864fe5fa
yt-dlp is up to date (nightly@2023.03.13.014401)
[aenetworks] Extracting URL: https://play.history.com/shows/the-food-that-built-america/season-4/episode-4
[aenetworks] /shows/the-food-that-built-america/season-4/episode-4: Downloading JSON metadata
ERROR: list index out of range
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\aenetworks.py", line 171, in _real_extract
  File "yt_dlp\extractor\aenetworks.py", line 73, in _extract_aetn_info
IndexError: list index out of range
```

**Comment by bashonly** [comment]
Based on #5417, it looks like this may be related to the episode having just been released, and the issue may resolve itself after a few days. Even if that turns out to be the case, IMO we should keep this issue open until it can be properly fixed

**Comment by dirkf** [comment]
This URL is being accessed for the metadata:
`
https://feeds.video.aetnd.com/api/v2/history/videos?filter[canonical]=/shows/the-food-that-built-america/season-4/episode-4
`
It appears not to be restricted by access control or geo-blocking (or only partially).

The success result is like this:
```py
  'code': 200,
  'status': 'Ok',
  'data': {
    'total': 1,
    'per_page': null,
    'current_page': 1,
    'last_page': 1,
    'next_page_url': null,
    'prev_page_url': null,
    'from': 1,
    'to': 1
  },
  'results': [
    {
      'id': '2180325955515',
      'DRMPlayURL': 'https://aetvprod.global.ssl.fastly.net/i/AETN-History_VMS/BRAND_THC_FTBA_277764_GLB_448909_2398_60_20230307_01_0307702_NoOB_S3_,1800,1300,1000,700,400,200,100,.mp4.csmil',
      'added': 1678368350000,
      'analyticsMediaTitle': 'CandyRevolution',
      'analyticsVideoCategory': 'TheFoodThatBuiltAmerica',
      'authenticationEndDate': 2082697200000,
      'authenticationEndDate_utcdate': {/* ... */},
      'authenticationStartDate': 1678687200000,
      'authenticationStartDate_utcdate': {/* ... */},
      'availableDate': 1678687200000,
      'availableDate_utcdate': {/* ... */},
      'canonical': '/shows/the-food-that-built-america/season-4/episode-4',
      /* more data */
    },
  ]
}
```
The error indicates that the `.results` list is present but empty. The `.code` and/or `.data.total` members could be checked, but in any case (`extractor/aenetworks.py:73`):
```diff
-        result = self._download_json(
            'https://feeds.video.aetnd.com/api/v2/%s/videos' % brand,
            filter_value, query={'filter[%s]' % filter_key: filter_value})['results'][0]
+        result = self._download_json(
            'https://feeds.video.aetnd.com/api/v2/%s/videos' % brand,
            filter_value, query={'filter[%s]' % filter_key: filter_value})
+        result = traverse_obj(result, ('results', lambda k, v: k == 0 and v[filter_key] == filter_value))
+        if not result:
+            raise ExtractorError('...')
```
Maybe the error message should say that the show was not found in the provider's feed which might not yet have been updated.

**Comment by dirkf** [comment]
Probably the same issue: https://github.com/ytdl-org/youtube-dl/issues/18167.

Also in this module:
* 400 Bad Request in playlist extractors based on `AENetworksListBaseIE`, but from https://github.com/ytdl-org/youtube-dl/issues/22714 this may be caused by not having provided valid MSO access parameters
* 404 Not Found on `BiographyIE` test URL.
