### ISSUE TITLE
redbee extractor : RTBF Auvio changed URLs

### ISSUE THREAD

**Issue by SerialSoda** [yt-dlp/yt-dlp#6558]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Belgium

### Provide a description that is worded well enough to be understood

National broadcaster RTBF recently changed its URL scheme and site layout. 
According to network trace, the redbee.live service is still used, but it is not detected anymore by yt-dlp.

New URL is like `https://auvio.rtbf.be/media/jcvd-jcvd-avec-jean-claude-van-damme-et-francois-damiens-2996244`
URL recognized in redbee.py is `https://www.rtbf.be/video/detail_les-diables-au-coeur-episode-2?id=1921274`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://auvio.rtbf.be/media/jcvd-jcvd-avec-jean-claude-van-damme-et-francois-damiens-2996244']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 216bcb66d
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-20-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0, xattr-0.9.7
[debug] Proxy map: {}
[debug] Loaded 1788 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://auvio.rtbf.be/media/jcvd-jcvd-avec-jean-claude-van-damme-et-francois-damiens-2996244
[generic] jcvd-jcvd-avec-jean-claude-van-damme-et-francois-damiens-2996244: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] jcvd-jcvd-avec-jean-claude-van-damme-et-francois-damiens-2996244: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://auvio.rtbf.be/media/jcvd-jcvd-avec-jean-claude-van-damme-et-francois-damiens-2996244
Traceback (most recent call last):
  File "/home/jfs/Lab/yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jfs/Lab/yt-dlp/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/home/jfs/Lab/yt-dlp/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/jfs/Lab/yt-dlp/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://auvio.rtbf.be/media/jcvd-jcvd-avec-jean-claude-van-damme-et-francois-damiens-2996244
```

**Comment by Ottaviocr** [comment]
May I ask why the "geo-blocked" tag was applied? I can stream the video url from the UK with valid RTBF account.

**Comment by bashonly** [comment]
> May I ask why the "geo-blocked" tag was applied? I can stream the video url from the UK with valid RTBF account.

the site says
> Ce contenu est visible uniquement en Belgique.
when I try to play the media

**Comment by bashonly** [comment]
I just created an account, and I am still geo-blocked after logging in.

**Comment by Ottaviocr** [comment]
> I just created an account, and I am still geo-blocked after logging in.

Ah ok, it must be because I opened my account when I lived in Belgium.

**Comment by faustusdotbe** [comment]
> > I just created an account, and I am still geo-blocked after logging in.
> 
> Ah ok, it must be because I opened my account when I lived in Belgium.

Just to confirm that it's indeed the case. You will probably have to register a way for them to check """you're Belgian""", currently this is done through text message to a BE number.

**Comment by Ottaviocr** [comment]
I'm willing to give my account credential to trusted members if necessary.

**Comment by faustusdotbe** [comment]
There are several issues at play here it seems:
- the new URL (`auvio.rtbf.be`) being unsupported
- geoblocking
- some videos are DRM protected, others are not

I'm currently in BE and can play the video you were trying to download in my browser. But if I get the mpd link using the network tab and pass it to yt-dlp, yt-dlp complains that the stream is encrypted. This means that even if the new URL (`auvio.rtbf.be`) were supported, you wouldn't be able to get past encryption. I believe breaking encryption is not what the devs of yt-dlp want to do, so there won't be a fix.

The complaining about the stream being encrypted does not happen for other, non-encrypted videos (for example this one https://auvio.rtbf.be/media/sonuma-strip-tease-letiquette-des-ptits-kets-strip-tease-2446996). When I get the mpd link and pass it directly to yt-dlp, it works.

**Comment by Ottaviocr** [comment]
On Tue, 23 May 2023 at 12:02, Simon Hengchen ***@***.***> wrote:
>
> There are several issues at play here it seems:
>
> the new URL (auvio.rtbf.be) being unsupported

That's the main issue and it should be sorted

> geoblocking

It is a problem for some.

> some videos are DRM protected, others are not

Back a few months ago (up to September last year), I was able to
download DRM protected videos just by passing cookies to yt-dlp. This
was with the old url.
