### ISSUE TITLE
WARNING: [Funimation] unable to extract show data; please report this issue on

### ISSUE THREAD

**Issue by levaculik2** [yt-dlp/yt-dlp#6575]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

it was downloading normally, when it started giving this problem

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'bv*+ba', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.funimation.com/', '--cookies-from-browser', 'chrome', '-a', '/home/levaculik/Documentos/list/funimation.txt', '--sub-langs', 'all', '--embed-subs', '--cookies', '/home/levaculik/Documentos/cookies/funimation.txt', '--no-geo-bypass', '--no-check-certificate', '--external-downloader', 'aria2c', '--remux-video', 'mkv', '-o', '%(series)s S0%(season_number)sE0%(episode_number)s - %(episode)s.%(ext)s']
[debug] Batch file urls: ['https://www.funimation.com/v/a3/on-love-spring-edition', 'https://www.funimation.com/v/a3/true-friends']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-139-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/home/levaculik/.config/google-chrome/Default/Cookies"
[debug] detected desktop environment: XFCE
[debug] Chosen keyring: GNOMEKEYRING
[Cookies] Extracted 3089 cookies from chrome
[debug] cookie version breakdown: {'v10': 0, 'v11': 3075, 'other': 0, 'unencrypted': 14}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[funimation:page] Logging in
[funimation:page] Extracting URL: https://www.funimation.com/v/a3/on-love-spring-edition
[funimation:page] a3_on-love-spring-edition: Downloading JSON metadata
[Funimation] Extracting URL: https://www.funimation.com/player/1023457
[Funimation] 1023457: Downloading player webpage for 1023457
[Funimation] on-love-spring-edition: Downloading player webpage for Uncut japanese (4127503)
WARNING: [Funimation] unable to extract show data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/funimation.py", line 203, in _real_extract
    self.extract_subtitles(
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 3552, in extract_subtitles
    return self._get_subtitles(*args, **kwargs)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/funimation.py", line 276, in _get_subtitles
    episode, _, _ = self._get_episode(webpage, episode_id=episode, fatal=False)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/funimation.py", line 161, in _get_episode
    show = self._parse_json(
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 992, in _parse_json
    return json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

[funimation:page] Extracting URL: https://www.funimation.com/v/a3/true-friends
[funimation:page] a3_true-friends: Downloading JSON metadata
[Funimation] Extracting URL: https://www.funimation.com/player/1023505
[Funimation] 1023505: Downloading player webpage for 1023505
[Funimation] true-friends: Downloading player webpage for Uncut japanese (4006702)
WARNING: [Funimation] unable to extract show data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/funimation.py", line 203, in _real_extract
    self.extract_subtitles(
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 3552, in extract_subtitles
    return self._get_subtitles(*args, **kwargs)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/funimation.py", line 276, in _get_subtitles
    episode, _, _ = self._get_episode(webpage, episode_id=episode, fatal=False)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/funimation.py", line 161, in _get_episode
    show = self._parse_json(
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 992, in _parse_json
    return json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

[generic] Extracting URL: https://www.funimation.com/
[generic] www.funimation: Downloading webpage
[redirect] Following redirect to https://www.funimation.com/pt-br/
[generic] Extracting URL: https://www.funimation.com/pt-br/
[generic] pt-br: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] pt-br: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.funimation.com/pt-br/
Traceback (most recent call last):
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/levaculik/.local/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.funimation.com/pt-br/
```

**Comment by acc029** [comment]
This issue seems to come from the script relying on an older Funimation API, and newer shows/episodes not returning any information with it. May be related to #5326.
