### ISSUE TITLE
Site Request - www.paramountpressexpress.com

### ISSUE THREAD

**Issue by darkufo** [yt-dlp/yt-dlp#6597]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://www.paramountpressexpress.com/cbs-entertainment/video/?watch=2s5eh8kppc
https://www.paramountpressexpress.com/cbs-entertainment/shows/survivor/video/?watch=pnzew7e2hx

### Provide a description that is worded well enough to be understood

These use to work a while ago on the old yt-dl . Today was the first time I tried on yt-dlp.

Error is: ERROR: Unsupported URL

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.paramountpressexpress.com/cbs-entertainment/video/?watch=2s5eh8kppc
[debug] Command-line config: ['-vU', 'https://www.paramountpressexpress.com/cbs-entertainment/video/?watch=2s5eh8kppc']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-94270-gaf9dc02e6b, ffprobe N-94270-gaf9dc02e6b
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.paramountpressexpress.com/cbs-entertainment/video/?watch=2s5eh8kppc
[generic] ?watch=2s5eh8kppc: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?watch=2s5eh8kppc: Extracting information
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[generic] Extracting URL: https://www.paramountpressexpress.com/embed/bc-player-v1.html?vers=2&video=2s5eh8kppc&division=cbs-entertainment
[generic] bc-player-v1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] bc-player-v1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.paramountpressexpress.com/embed/bc-player-v1.html?vers=2&video=2s5eh8kppc&division=cbs-entertainment
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.paramountpressexpress.com/embed/bc-player-v1.html?vers=2&video=2s5eh8kppc&division=cbs-entertainment
```

**Comment by october262** [comment]
download works if you grab the master.m3u8 from the dev tools

**Comment by darkufo** [comment]
Thank you. This is working great in the latest nightly
