### ISSUE TITLE
BiliBili.tv downloads causing different error messages

### ISSUE THREAD

**Issue by quamt** [yt-dlp/yt-dlp#6640]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When trying to download videos from BiliBili.tv, some of the videos won't download.
This usually either shows as:
`[download] Got error: Remote end closed connection without response. Retrying (x/10)...`
or
`ERROR: unable to download video data: HTTP Error 403: Forbidden`

Login via Chrome using subscription.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--config-locations', 'config_bilibili.txt', 'https://www.bilibili.tv/en/play/1005144/10133388']
[debug] | Config "config_bilibili.txt": ['--ffmpeg-location', 'ffmpeg', '-vU', '--write-subs', '--sub-langs', 'en*', '--write-description', '--sub-format', 'best', '-N', '1', '-P', 'downloads', '-o', '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', '--cookies-from-browser', 'chrome', '--remux-video', 'mkv', '--embed-subs', '--embed-chapters', '--ppa', 'EmbedSubtitle:-disposition:s:0 forced', '--embed-metadata', '--parse-metadata', ':(?P<meta_purl>)', '--parse-metadata', ':(?P<meta_comment>)', '--parse-metadata', ':(?P<meta_description>)', '--parse-metadata', ':(?P<meta_title>)', '--parse-metadata', ':(?P<meta_episode_id>)', '--parse-metadata', ':(?P<meta_date>)', '--parse-metadata', ':(?P<meta_season_number>)', '--parse-metadata', ':(?P<meta_episode_sort>)', '--no-embed-info-json', '--no-write-comments', '-k', '--wait-for-video', '10', '--sleep-requests', '0.5']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-16-git-aeceefa622-full_build-www.gyan.dev (setts), ffprobe 2023-02-16-git-aeceefa622-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\RED\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\RED\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 2402 cookies from chrome
[debug] cookie version breakdown: {'v10': 2402, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[BiliIntl] Extracting URL: https://www.bilibili.tv/en/play/1005144/10133388
[BiliIntl] 10133388: Downloading JSON metadata
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10133388: Downloading webpage
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10133388: Downloading JSON metadata
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10133388: Downloading video formats
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10133388: Downloading subtitles list
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10133388: Downloading subtitles for English
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10133388: Downloading subtitles for ภาษาไทย
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10133388: Downloading subtitles for Tiếng Việt
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10133388: Downloading subtitles for Bahasa Indonesia
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10133388: Downloading subtitles for Bahasa Melayu
[info] 10133388: Downloading subtitles: en
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Searching for '(?P<meta_purl>)' in ''
[MetadataParser] Parsed meta_purl from '': ''
[debug] Searching for '(?P<meta_comment>)' in ''
[MetadataParser] Parsed meta_comment from '': ''
[debug] Searching for '(?P<meta_description>)' in ''
[MetadataParser] Parsed meta_description from '': ''
[debug] Searching for '(?P<meta_title>)' in ''
[MetadataParser] Parsed meta_title from '': ''
[debug] Searching for '(?P<meta_episode_id>)' in ''
[MetadataParser] Parsed meta_episode_id from '': ''
[debug] Searching for '(?P<meta_date>)' in ''
[MetadataParser] Parsed meta_date from '': ''
[debug] Searching for '(?P<meta_season_number>)' in ''
[MetadataParser] Parsed meta_season_number from '': ''
[debug] Searching for '(?P<meta_episode_sort>)' in ''
[MetadataParser] Parsed meta_episode_sort from '': ''
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 10133388: Downloading 1 format(s): 9+2
[info] Writing video description to: downloads\NA\NA - E156 - Raiga's Counterattack.description
[info] Writing video subtitles to: downloads\NA\NA - E156 - Raiga's Counterattack.en.srt
[debug] Invoking http downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/jn/w5/n230301a23g7p8mjgtypic1o5p7zw5jn-1-261210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1679822119&gen=playurlv2&os=akam&oi=1951826082&trid=2af7549b84ec4b9c89926254280e1ed0i&mid=1382490330&platform=pc&upsig=711bfe068be1464d45783ab6f0c391fb&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1679822119~hmac=9c1c7a70cb34f6517ec1b7b69c267f7b71b54336a523beabf0763acb35ced9a1&bvc=vod&nettype=0&orderid=0,2&logo=00000000"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: downloads\NA\NA - E156 - Raiga's Counterattack.f9.mp4
[download]   5.3% of  303.54MiB at   37.68MiB/s ETA 00:07[download] Got error: Downloaded 16777216 bytes, expected 318282616 bytes. Retrying (1/10)...
[download] Got error: Remote end closed connection without response. Retrying (2/10)...
[download] Got error: Remote end closed connection without response. Retrying (3/10)...
[download] Got error: Remote end closed connection without response. Retrying (4/10)...
[download] Got error: Remote end closed connection without response. Retrying (5/10)...
[download] Got error: Remote end closed connection without response. Retrying (6/10)...
[download] Got error: Remote end closed connection without response. Retrying (7/10)...
[download] Got error: Remote end closed connection without response. Retrying (8/10)...
[download] Got error: Remote end closed connection without response. Retrying (9/10)...
[download] Got error: Remote end closed connection without response. Retrying (10/10)...
[download] Got error: Remote end closed connection without response. Giving up after 10 retries
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 967, in main
  File "yt_dlp\__init__.py", line 957, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3369, in download
  File "yt_dlp\YoutubeDL.py", line 3344, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1507, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1615, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2779, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3229, in process_info
  File "yt_dlp\YoutubeDL.py", line 2970, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\http.py", line 374, in real_download
  File "yt_dlp\utils.py", line 6141, in __iter__
  File "yt_dlp\downloader\common.py", line 389, in report_retry
  File "yt_dlp\utils.py", line 6148, in report_retry
  File "yt_dlp\downloader\common.py", line 392, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 1015, in report_error
  File "yt_dlp\YoutubeDL.py", line 944, in trouble


[debug] Invoking http downloader on "https://upos-sz-mirrorgcsbstar1.bilivideo.com/iupxcodeboss/jn/w5/n230301a23g7p8mjgtypic1o5p7zw5jn-1-2d1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1679822119&gen=playurlv2&os=gcsbstar1bv&oi=1951826082&trid=2af7549b84ec4b9c89926254280e1ed0i&mid=1382490330&platform=pc&upsig=aacbd47078893e856920381a4f3afeb6&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&URLPrefix=aHR0cHM6Ly91cG9zLXN6LW1pcnJvcmdjc2JzdGFyMS5iaWxpdmlkZW8uY29tL2l1cHhjb2RlYm9zcy9qbi93NS9uMjMwMzAxYTIzZzdwOG1qZ3R5cGljMW81cDd6dzVqbi0xLTJkMTMwMTAwMDAyMy5tNHM=&Expires=1679822119&KeyName=bilibili&Signature=IX8FiM3cc91cctQsqxZ1Oap7vLc=&bvc=vod&nettype=0&orderid=0,2&logo=00000000"
[download] Destination: downloads\NA\NA - E156 - Raiga's Counterattack.f2.mp4
[download] 100% of   28.28MiB in 00:00:00 at 35.48MiB/s






[debug] Command-line config: ['--config-locations', 'config_bilibili.txt', 'https://www.bilibili.tv/en/play/1005144/10137815']
[debug] | Config "config_bilibili.txt": ['--ffmpeg-location', 'ffmpeg', '-vU', '--write-subs', '--sub-langs', 'en*', '--write-description', '--sub-format', 'best', '-N', '1', '-P', 'downloads', '-o', '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', '--cookies-from-browser', 'chrome', '--remux-video', 'mkv', '--embed-subs', '--embed-chapters', '--ppa', 'EmbedSubtitle:-disposition:s:0 forced', '--embed-metadata', '--parse-metadata', ':(?P<meta_purl>)', '--parse-metadata', ':(?P<meta_comment>)', '--parse-metadata', ':(?P<meta_description>)', '--parse-metadata', ':(?P<meta_title>)', '--parse-metadata', ':(?P<meta_episode_id>)', '--parse-metadata', ':(?P<meta_date>)', '--parse-metadata', ':(?P<meta_season_number>)', '--parse-metadata', ':(?P<meta_episode_sort>)', '--no-embed-info-json', '--no-write-comments', '-k', '--wait-for-video', '10', '--sleep-requests', '0.5']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-16-git-aeceefa622-full_build-www.gyan.dev (setts), ffprobe 2023-02-16-git-aeceefa622-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\RED\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\RED\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 2402 cookies from chrome
[debug] cookie version breakdown: {'v10': 2402, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[BiliIntl] Extracting URL: https://www.bilibili.tv/en/play/1005144/10137815
[BiliIntl] 10137815: Downloading JSON metadata
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10137815: Downloading webpage
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10137815: Downloading JSON metadata
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10137815: Downloading video formats
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10137815: Downloading subtitles list
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10137815: Downloading subtitles for English
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10137815: Downloading subtitles for ภาษาไทย
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10137815: Downloading subtitles for Tiếng Việt
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10137815: Downloading subtitles for Bahasa Indonesia
[BiliIntl] Sleeping 0.5 seconds ...
[BiliIntl] 10137815: Downloading subtitles for Bahasa Melayu
[info] 10137815: Downloading subtitles: en
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Searching for '(?P<meta_purl>)' in ''
[MetadataParser] Parsed meta_purl from '': ''
[debug] Searching for '(?P<meta_comment>)' in ''
[MetadataParser] Parsed meta_comment from '': ''
[debug] Searching for '(?P<meta_description>)' in ''
[MetadataParser] Parsed meta_description from '': ''
[debug] Searching for '(?P<meta_title>)' in ''
[MetadataParser] Parsed meta_title from '': ''
[debug] Searching for '(?P<meta_episode_id>)' in ''
[MetadataParser] Parsed meta_episode_id from '': ''
[debug] Searching for '(?P<meta_date>)' in ''
[MetadataParser] Parsed meta_date from '': ''
[debug] Searching for '(?P<meta_season_number>)' in ''
[MetadataParser] Parsed meta_season_number from '': ''
[debug] Searching for '(?P<meta_episode_sort>)' in ''
[MetadataParser] Parsed meta_episode_sort from '': ''
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 10137815: Downloading 1 format(s): 9+2
[info] Writing video description to: downloads\NA\NA - E200 - The Powerful Helper.description
[info] Writing video subtitles to: downloads\NA\NA - E200 - The Powerful Helper.en.srt
[debug] Invoking http downloader on "https://upos-sz-mirrorhwbstar1.bilivideo.com/iupxcodeboss/jw/pg/n230301qn2zo8ei9u8besp3kxyxppgjw-1-261210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1679822436&gen=playurlv2&os=hwbstar1bv&oi=1951826082&trid=a9c102a085544f13bd2fef25754b19c9i&mid=1382490330&platform=pc&upsig=4ae316c62b0af9e2fb5ab594b8aab0a2&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,2&logo=00000000"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3229, in process_info
  File "yt_dlp\YoutubeDL.py", line 2970, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\http.py", line 376, in real_download
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by quamt** [comment]
It seems to be that the solution to the problem is adding a header.
I am currently testing it with the one below and no issues at the moment.

`--add-header 'Referer: https://www.bilibili.tv/'`

**Comment by quamt** [comment]
I confirmed that some of the downloads only work with the `--add-header` option.
Several tests went successful with the `--add-header` option while other downloads from the same side do not cause errors when it is missing.
I am sorry that I can not provide more information as to what is causing the different behaviour.

**Comment by ivanskodje** [comment]
Tried looking at this issue, but I am unable to access the site and reproduce the issue.

- Where are you located (country)?
- Can you share the config file contents (just makes it easier than having to copy the config from the logs)?

I cannot promise i will look at this in the future if the answer takes too long, but this information would help any developer that intend to look at this issue :smile_cat:

**Comment by pukkandan** [comment]
> * Can you share the config file contents (just makes it easier than having to copy the config from the logs)?

Their config seems irrelevant to the issue

**Comment by quamt** [comment]
> Tried looking at this issue, but I am unable to access the site and reproduce the issue.
> 
> * Where are you located (country)?
> * Can you share the config file contents (just makes it easier than having to copy the config from the logs)?
> 
> I cannot promise i will look at this in the future if the answer takes too long, but this information would help any developer that intend to look at this issue in the future either way 😸

I'm located in Malaysia

**Comment by darkralts** [comment]
> It seems to be that the solution to the problem is adding a header. I am currently testing it with the one below and no issues at the moment, that trigger above errors.
> 
> `--add-header 'Referer: https://www.bilibili.tv/'`

doing this worked and fixed it, dunno why tho

**Comment by darkralts** [comment]
is there a way to get 1080p? bilibili locks that to those with accounts but i have one, maybe a way to api call or login or something?

**Comment by darkralts** [comment]
``--cookies-from-browser firefox`` fixed it too, if anyone needs it :)
