### ISSUE TITLE
Works fine on Windows but not on Linux Mate 18.3

### ISSUE THREAD

**Issue by unlxg** [yt-dlp/yt-dlp#666]
### Discussed in https://github.com/yt-dlp/yt-dlp/discussions/665

<div type='discussions-op-text'>

<sup>Originally posted by **unlxg** August 10, 2021</sup>
I tried last and previous release on two Linux mate 18.3 installations with no success:
- Intallation by wget on a system already using youtube-dl.
- A "yt-dlp -U" command returns : 
File "usr/local/bin/yt-dlp/yt_dlp/cookies.py , line 44 
KEYRING_UNAVAILABLE_REASON = f'due to unknown reasons{bug_reportsmessage()}'
^
SyntaxError: invalid syntax

Any idea ?</div>

**Comment by unlxg** [comment]
It looks like I missed an important part of the output from yt-dlp, here is the full output 

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/bin/yt-dlp/yt_dlp/options.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/usr/local/bin/yt-dlp/yt_dlp/cookies.py", line 44
    KEYRING_UNAVAILABLE_REASON = f'due to unknown reasons{bug_reports_message()}'
                                                                                ^
SyntaxError: invalid syntax

**Comment by Ashish0804** [comment]
`f strings` are a python 3.6+ feature and u are running python 3.5 which is officially not supported.

**Comment by unlxg** [comment]
Thanx. I built a newer version of Python and it works if I explicitly run yt-dlp from it.
