### ISSUE TITLE
[RedBull] Download all episodes of a show from the show URL

### ISSUE THREAD

**Issue by tigattack** [yt-dlp/yt-dlp#6670]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.redbull.com/gb-en/shows/life-of-kai

### Provide a description that is worded well enough to be understood

It's currently not possible to parse the episodes of a show from Red Bull TV (redbull.com) when given the show's URL (e.g. `https://www.redbull.com/gb-en/shows/life-of-kai`). It's only possible to download episodes from direct URL (e.g. `https://www.redbull.com/gb-en/episodes/life-of-kai-s1-e1`).

It would be great if I could pass a show URL to yt-dlp and it downloads all episodes, such as with YouTube channels and playlists.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vUs', 'https://www.redbull.com/gb-en/shows/life-of-kai']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.2 (CPython arm64 64bit) - macOS-13.2.1-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.redbull.com/gb-en/shows/life-of-kai
[generic] life-of-kai: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] life-of-kai: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.redbull.com/gb-en/shows/life-of-kai
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.redbull.com/gb-en/shows/life-of-kai
```

**Comment by tigattack** [comment]
Implementing this would likely take more time than I can dedicate to this at the moment, being largely unfamiliar with yt-dlp's internals and somewhat of a novice with Python.

The seasons and episodes of a show can be queried like so: `curl 'https://www.redbull.com/v3/api/graphql/v1/v3/feed/en-GB%3Een-INT?filter[type]=shows&filter[uriSlug]=life-of-kai&page[limit]=1&disableUsageRestrictions=true&rb3Schema=v1:tvEpisodesTabs' --globoff`

From what I can tell, the response contains everything that should be needed to return the show's contents to yt-dlp as a plalist.
