### ISSUE TITLE
sketch.pixiv.net breaks during postprocessing fixup with aac_adtstoasc error (stream audio is MP3)

### ISSUE THREAD

**Issue by wunderbrot** [yt-dlp/yt-dlp#6673]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

yt-dlp fails during postprocessing after recording sketch.pixiv.net streams, breaks and leaves behind an empty *.temp.mp4 file along with the original file.  

Same problem as described in [#4021](https://github.com/yt-dlp/yt-dlp/issues/4021), trying to fixup AAC but the audio stream is MP3.  I guess the extractor needs to be updated?

(Also many packet corrupt messages, but maybe this is a separate issue?)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
\yt-dlp>yt-dlp -vU https://sketch.pixiv.net/@fu_hoco/
[debug] Command-line config: ['-vU', 'https://sketch.pixiv.net/@fu_hoco/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110112-gd6e30291db-20230328 (setts), ffprobe N-110112-gd6e30291db-20230328
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[pixiv:sketch:user] Extracting URL: https://sketch.pixiv.net/@fu_hoco/
[pixiv:sketch:user] fu_hoco: Downloading JSON metadata
[pixiv:sketch] Extracting URL: https://sketch.pixiv.net/@fu_hoco/lives/607014165617026351
[pixiv:sketch] 607014165617026351: Downloading JSON metadata
[pixiv:sketch] 607014165617026351: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 607014165617026351: Downloading 1 format(s): hls-4000
[debug] Invoking ffmpeg downloader on "https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/index.m3u8"
[download] Destination: 裏作業配信 2023-03-29 13_38 [607014165617026351].mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
" -i "https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/index.m3u8" -c copy -f mpegts "file:裏作業配信 2023-03-29 13_38 [607014165617026351].mp4.part"
ffmpeg version N-110112-gd6e30291db-20230328 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (crosstool-NG 1.25.0.152_89671bf)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230328
  libavutil      58.  5.100 / 58.  5.100
  libavcodec     60.  7.100 / 60.  7.100
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  5.100 /  9.  5.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[tcp @ 000001eb1e63ab00] Starting connection attempt to 210.140.92.213 port 443
[tcp @ 000001eb1e63ab00] Successfully connected to 210.140.92.213 port 443
[hls @ 000001eb1e639e80] Skip ('#EXT-X-VERSION:6')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-INDEPENDENT-SEGMENTS')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:15.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:18.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:21.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:24.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:27.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:30.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:33.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:36.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:39.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:42.000Z')
[hls @ 000001eb1e639e80] HLS request for url 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038372.ts', offset 0, playlist 0
[hls @ 000001eb1e639e80] Opening 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038372.ts' for reading
[tcp @ 000001eb20221440] Starting connection attempt to 210.140.92.213 port 443
[tcp @ 000001eb20221440] Successfully connected to 210.140.92.213 port 443
[hls @ 000001eb1e639e80] HLS request for url 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038373.ts', offset 0, playlist 0
[hls @ 000001eb1e639e80] Opening 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038373.ts' for reading
[tcp @ 000001eb20221f80] Starting connection attempt to 210.140.92.213 port 443
[tcp @ 000001eb20221f80] Successfully connected to 210.140.92.213 port 443
[h264 @ 000001eb2022c040] Reinit context to 1920x1088, pix_fmt: yuv420p
Input #0, hls, from 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/index.m3u8':
  Duration: N/A, start: 1470.000000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: mp3 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 96 kb/s
    Metadata:
      variant_bitrate : 0
[mpegts @ 000001eb2152b680] service 1 using PCR in pid=256, pcr_period=83ms
[mpegts @ 000001eb2152b680] muxrate VBR, sdt every 500 ms, pat/pmt every 100 ms
Output #0, mpegts, to 'file:裏作業配信 2023-03-29 13_38 [607014165617026351].mp4.part':
  Metadata:
    encoder         : Lavf60.4.100
  Stream #0:0: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(left), 1920x1080 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 24 fps, 24 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: mp3 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 96 kb/s
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[tcp @ 000001eb2152bf00] Starting connection attempt to 210.140.92.213 port 443/s speed=1.93x
[tcp @ 000001eb2152bf00] Successfully connected to 210.140.92.213 port 443
[hls @ 000001eb1e639e80] Skip ('#EXT-X-VERSION:6')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-INDEPENDENT-SEGMENTS')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:21.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:24.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:27.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:30.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:33.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:36.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:39.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:42.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:45.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:48.000Z')
[hls @ 000001eb1e639e80] HLS request for url 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038374.ts', offset 0, playlist 0
[https @ 000001eb2021e500] Opening 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038374.ts' for reading
[mpegts @ 000001eb2021c580] Packet corrupt (stream = 0, dts = 132566250).
[hls @ 000001eb1e639e80] Packet corrupt (stream = 0, dts = 132562500).
[in#0/hls @ 000001eb1e639d00] corrupt input packet in stream 0
[hls @ 000001eb1e639e80] HLS request for url 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038375.ts', offset 0, playlist 0
[https @ 000001eb20254600] Opening 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038375.ts' for reading
[mpegts @ 000001eb2021c580] Packet corrupt (stream = 0, dts = 132836250).
[hls @ 000001eb1e639e80] Packet corrupt (stream = 0, dts = 132832500).
[in#0/hls @ 000001eb1e639d00] corrupt input packet in stream 0
[https @ 000001eb2174da80] Opening 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/index.m3u8' for reading
[hls @ 000001eb1e639e80] Skip ('#EXT-X-VERSION:6')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-INDEPENDENT-SEGMENTS')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:24.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:27.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:30.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:33.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:36.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:39.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:42.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:45.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:48.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:51.000Z')
[hls @ 000001eb1e639e80] HLS request for url 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038376.ts', offset 0, playlist 0
[https @ 000001eb2021e500] Opening 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038376.ts' for reading
[mpegts @ 000001eb2021c580] Packet corrupt (stream = 0, dts = 133106250).
[hls @ 000001eb1e639e80] Packet corrupt (stream = 0, dts = 133102500).
[in#0/hls @ 000001eb1e639d00] corrupt input packet in stream 0
[hls @ 000001eb1e639e80] HLS request for url 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038377.ts', offset 0, playlist 0
[https @ 000001eb20254600] Opening 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038377.ts' for reading
[mpegts @ 000001eb2021c580] Packet corrupt (stream = 0, dts = 133376250).
[hls @ 000001eb1e639e80] Packet corrupt (stream = 0, dts = 133372500).
[in#0/hls @ 000001eb1e639d00] corrupt input packet in stream 0
[https @ 000001eb2174da80] Opening 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/index.m3u8' for reading
[hls @ 000001eb1e639e80] Skip ('#EXT-X-VERSION:6')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-INDEPENDENT-SEGMENTS')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:27.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:30.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:33.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:36.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:39.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:42.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:45.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:48.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:51.000Z')
[hls @ 000001eb1e639e80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2023-03-29T18:38:54.000Z')
[hls @ 000001eb1e639e80] HLS request for url 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038378.ts', offset 0, playlist 0
[https @ 000001eb2021e500] Opening 'https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/560038378.ts' for reading
[mpegts @ 000001eb2021c580] Packet corrupt (stream = 0, dts = 133646250).
[hls @ 000001eb1e639e80] Packet corrupt (stream = 0, dts = 133642500).
[in#0/hls @ 000001eb1e639d00] corrupt input packet in stream 0
[mpegts @ 000001eb2021c580] Packet corrupt (stream = 0, dts = 133916250).3kbits/s speed=1.37x
[hls @ 000001eb1e639e80] Packet corrupt (stream = 0, dts = 133912500).
[in#0/hls @ 000001eb1e639d00] corrupt input packet in stream 0
[out#0/mpegts @ 000001eb20cc9e40] All streams finished18.24 bitrate=1954.6kbits/s speed=1.59x
[out#0/mpegts @ 000001eb20cc9e40] Terminating muxer thread
[AVIOContext @ 000001eb2024b300] Statistics: 4781216 bytes written, 0 seeks, 19 writeouts
frame=  451 fps= 37 q=-1.0 Lsize=    4669kB time=00:00:18.86 bitrate=2027.7kbits/s speed=1.56x
video:4234kB audio:221kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 4.801149%
Input file #0 (https://hlse3.pixivsketch.net/2023033003/168011364744963815316093f92f157fed2f699ccc37aee6b60/4000000_1920x1080_jjsQ570mb1PyrLmt/index.m3u8):
  Input stream #0:0 (video): 451 packets read (4335523 bytes);
  Input stream #0:1 (audio): 787 packets read (226656 bytes);
  Total: 1238 packets (4562179 bytes) demuxed
Output file #0 (file:裏作業配信 2023-03-29 13_38 [607014165617026351].mp4.part):
  Output stream #0:0 (video): 451 packets muxed (4335523 bytes);
  Output stream #0:1 (audio): 787 packets muxed (226656 bytes);
  Total: 1238 packets (4562179 bytes) muxed
[in#0/hls @ 000001eb1e639d00] Terminating demuxer thread
[AVIOContext @ 000001eb202215c0] Statistics: 2800562 bytes read, 0 seeks
[AVIOContext @ 000001eb20222040] Statistics: 2310520 bytes read, 0 seeks
[AVIOContext @ 000001eb21749280] Statistics: 2991 bytes read, 0 seeks
[AVIOContext @ 000001eb20214dc0] Statistics: 997 bytes read, 0 seeks
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user
[download] 100% of    4.56MiB in 00:00:16 at 277.83KiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:裏作業配信 2023-03-29 13_38 [607014165617026351].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "裏作業配信 2023-03-29 13_38 [607014165617026351].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:裏作業配信 2023-03-29 13_38 [607014165617026351].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:裏作業配信 2023-03-29 13_38 [607014165617026351].temp.mp4"
[debug] ffmpeg version N-110112-gd6e30291db-20230328 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (crosstool-NG 1.25.0.152_89671bf)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230328
  libavutil      58.  5.100 / 58.  5.100
  libavcodec     60.  7.100 / 60.  7.100
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  5.100 /  9.  5.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mpegts, from 'file:裏作業配信 2023-03-29 13_38 [607014165617026351].mp4':
  Duration: 00:00:18.79, start: 1.400000, bitrate: 2035 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: mp3 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 96 kb/s
[aac_adtstoasc @ 0000016e46c866c0] Codec 'mp3' (86017) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018)
[aost#0:1/copy @ 0000016e47300840] Error initializing bitstream filter: aac_adtstoasc
[aost#0:1/copy @ 0000016e47300840] Error initializing output stream:
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)


ERROR: Postprocessing:   Stream #0:1 -> #0:1 (copy)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3323, in process_info
  File "yt_dlp\YoutubeDL.py", line 3502, in post_process
  File "yt_dlp\YoutubeDL.py", line 3484, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3462, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 895, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 857, in _fixup
  File "yt_dlp\postprocessor\ffmpeg.py", line 369, in run_ffmpeg
  File "yt_dlp\postprocessor\ffmpeg.py", line 324, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 362, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:1 -> #0:1 (copy)
```

**Comment by wunderbrot** [comment]
`ID       EXT RESOLUTION │   TBR PROTO │ VCODEC    VBR ACODEC  ABR
─────────────────────────────────────────────────────────────────
hls-365  mp4 1280x720   │  365k m3u8  │ unknown  365k unknown  0k
hls-4000 mp4 1920x1080  │ 4000k m3u8  │ unknown 4000k unknown  0k`

**Comment by wunderbrot** [comment]
The format list shows unknown ACODEC for Pixiv Sketch streams with audio, so I guess that's what's tripping up the postprocessor.  Is there a way to force the correct audio EXT? (I checked the Format Selection documentation and it doesn't seem like it)

```
ID       EXT RESOLUTION │   TBR PROTO │ VCODEC    VBR ACODEC  ABR
─────────────────────────────────────────────────────────────────
hls-365  mp4 1280x720   │  365k m3u8  │ unknown  365k unknown  0k
hls-4000 mp4 1920x1080  │ 4000k m3u8  │ unknown 4000k unknown  0k
```

**Comment by wunderbrot** [comment]
The format list shows unknown ACODEC for Pixiv Sketch streams with audio, so I guess that's what's tripping up the postprocessor.  Is there a way to force the correct audio EXT? (I checked the Format Selection documentation and it doesn't seem like it)

```
ID       EXT RESOLUTION │   TBR PROTO │ VCODEC    VBR ACODEC  ABR
─────────────────────────────────────────────────────────────────
hls-365  mp4 1280x720   │  365k m3u8  │ unknown  365k unknown  0k
hls-4000 mp4 1920x1080  │ 4000k m3u8  │ unknown 4000k unknown  0k
```

**Comment by bashonly** [comment]
I think something like this could fix the problem?
```diff
diff --git a/yt_dlp/postprocessor/ffmpeg.py b/yt_dlp/postprocessor/ffmpeg.py
index 63fc9ace6..323f4303c 100644
--- a/yt_dlp/postprocessor/ffmpeg.py
+++ b/yt_dlp/postprocessor/ffmpeg.py
@@ -898,8 +898,11 @@ def _needs_fixup(self, info):
     @PostProcessor._restrict_to(images=False)
     def run(self, info):
         if all(self._needs_fixup(info)):
+            args = ['-f', 'mp4']
+            if self.get_audio_codec(info['filepath']) == 'aac':
+                args.extend(['-bsf:a', 'aac_adtstoasc'])
             self._fixup('Fixing MPEG-TS in MP4 container', info['filepath'], [
-                *self.stream_copy_opts(), '-f', 'mp4', '-bsf:a', 'aac_adtstoasc'])
+                *self.stream_copy_opts(), *args])
         return [], info
 
 
```
Not able to test on the OP's link though.
When I try `yt-dlp https://sketch.pixiv.net/@fu_hoco/` I get a login required message
and when I try `yt-dlp https://sketch.pixiv.net/@fu_hoco/lives/607014165617026351` I get a 404 error

**Comment by wunderbrot** [comment]
It's an art streaming site, so you'd need to find a stream with mic enabled to test on.  You can check [https://sketch.pixiv.net/lives?filter_by=is_enabled_mic_input](https://sketch.pixiv.net/lives?filter_by=is_enabled_mic_input) for current live audio-enabled streams (potentially NSFW warning).

**Comment by Lesmiscore** [comment]
@bashonly Your patch seems to work properly on this sitation
