### ISSUE TITLE
radio-canada.ca support (and maybe OHdio?)

### ISSUE THREAD

**Issue by anarcat** [yt-dlp/yt-dlp#6678]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

- Single video: https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/episodes/668947/farine-agatha-invention-galaxie/emission
- Video Playlist: https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/contenu/tout

- Single audio: https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/episodes/450998/science-fiction-jeunesse-enfants-livre/7228/audios
- Audio playlist: https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/contenu/audios

### Provide a description that is worded well enough to be understood

radio-canada used to provide actual RSS feeds for their shows, but switched to using a rather idiotic [OHdio](https://ici.radio-canada.ca/ohdio) thing that is both an app and a website. Confusingly, other things are still available *outside* of that site. 

The above URLs give an example of videos that are available outside of OHdio, but presumably some work could be done to support OHdio-only sites as well. I have also provided an example of an audio track that I've actually been able to download myself, after much head banging and hair-splitting. That is, of course, after a friend told me "oh you should just write a yt-dlp extractor" and I found out (much too late) about [this documentation](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) and the [plugin stuff](https://github.com/yt-dlp/yt-dlp/wiki/Plugin-Development).

In any case, what i did is this rather nasty shell script:

```sh
#!/bin/sh

set -e

#set -x

BaseURL='https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/contenu/audios'

curl -s "$BaseURL" | sed -n '/medianet-content/{s/.*href="/https:\/\/ici.radio-canada.ca/;s/".*//;p}' | while read EpUrl; do

    #EpUrl='https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/episodes/456610/neo-agence-cheffe-sauver-monde-ennemie/7228/audios'
    # look for a <script .*type=consolevideo+json>, it's our magic JSON blob
    #IdMedia=$(curl -s "$EpUrl" | grep -Po '"IdMedia":"\d+"' | grep -Po '\d+')
    JSON_BLOB=$(curl -s "$EpUrl" | sed -n '/<script[^>]*application[^>]*>/,/<\/script>/p' | sed -e '/<\/\?script/d')

    IdMedia=$(
        jq -r .Media.IdMedia <<EOF
$JSON_BLOB
EOF
           )
    Title=$(
        jq -r .Title <<EOF
$JSON_BLOB
EOF
         )
    m3u_url=$(curl -s 'https://services.radio-canada.ca/media/validation/v2/?appCode=medianet&connectionType=hd&deviceType=ipad&idMedia='"$IdMedia"'&multibitrate=true&output=json&tech=hls' | jq -r .url)
    yt-dlp -o "$Title".mp4 "$m3u_url"
done
```

Basically the trick is that you can enumerate the audio tracks from the "playlist" URL above, then from there you need to find and load a small JSON blob that gives you the unique ID for a HLS stream that yt-dlp is then quite happy to slurp down. It's missing author/title/genre kind of metadata in the mp4 and doesn't pull the covers, but that would probably be easier to implement in yt-dlp than going any further ahead in that horrible script.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
anarcat@angela:tmp$ yt-dlp -vU 'https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/contenu/audios'
[debug] Command-line config: ['-vU', 'https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/contenu/audios']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-6-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2-3 (setts), ffprobe 5.1.2-3, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/contenu/audios
[generic] audios: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] audios: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/contenu/audios
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://ici.radio-canada.ca/jeunesse/scolaire/emissions/5615/lagent-jean/contenu/audios
```

**Comment by dirkf** [comment]
It's there but in the hydration JSON (which has nothing useful for l'agent Jean) and here:
```html
...<div data-mediainfo='{"appCode":"medianet","mediaId":"8802204"}'>...
```

**Comment by dirkf** [comment]
The OHdio pages are basically similar to the previous ones, but the hydration JSON assigned to `_rcState_` has to be analyzed; actual A/V pages have a Medianet ID stashed as `mediaId`. There isn't an obvious way to distinguish playlists: it seems that matching xxx/nnn in the url where xxx is one of `livres-audio`, `balados`, `episodes` or `emissions` and the path finishes with the hyphenated program slug, like `enquete-de-crime-une-histoire-presque-vraie`, finds the obvious ones; then the playlist item URLS (etc) can be found in an `items` list in the hydration JSON.

**Comment by anarcat** [comment]
thanks for that extra data! i rewrote my script in python now, which should make it easier to port to a yt-dlp plugin next.

here's the current python code: https://gitlab.com/anarcat/scripts/-/blob/67de3abafe8741631a8377c891a42bec5623585f/odieu.py

it's a permalink because i sometimes move stuff, look at the `main` branch to see the latest. i'm hoping to eventually port that to yt-dlp, but if anyone else wants to import my code, feel free! consider it free of any rights or whatever license you need.

the next step would probably be to look at those instructions: https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-support-for-a-new-site and https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#plugins

data-wise, i'm still having trouble finding episode numbers here... i haven't found any information in the data itself to identify episodes numerically, by season and all... would welcome some other data poker to figure that out! :) 

right now i still have to manually edit tags on the files which is kind of annoying. but i guess doing that part of the script will be more trouble than it would be to first port it to yt-dlp now, so that metadata would be supplied internally there.

**Comment by anarcat** [comment]
https://yodio.ca/ just came out that has a better API for that stuff, including RSS feeds for some of the works. not sure it's a good idea to depend on it though, because it could go away at any time. but it shows it can be done!

there was also an RSS converter that was retired a couple of days ago, written in Scala, here's the [last known commit](https://github.com/marcel-galarneau/rss-converter/tree/8545eef2dab34c2284aa52ff5e4921a999dfd85a).

i've also updated my script a little so that it works better with the current codebase and fixed a few crashes. still hoping to get this in yt-dlp at some point, but it feels a little daunting to write a plugin, would love some advice!
