### ISSUE TITLE
Handling quotation mark inside format parameter

### ISSUE THREAD

**Issue by X-Gorn** [yt-dlp/yt-dlp#6738]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I tried to download a video and i see that in the available format there's `'720p'` with the quotation mark, but when i try to download it with that format, i'm unable to download it because it always show that the format is not available.

i've tried to escape it by adding `"` and `\` but seems like it doesn't work.

i hope you can help me with this.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-c', '--max-filesize', '2097152000', '--embed-subs', '-f', "\\'720p\\'", 'https://cnnph-hls.octopusbanner.com/src/hls/ph5f6253da0909f/hls_main.m3u8', '--referer', 'https://cnnph-hls.octopusbanner.com', '-o', './DOWNLOADS/1829939747/hls_main.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.9.16 (CPython x86_64 64bit) - Linux-4.15.0-189-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://cnnph-hls.octopusbanner.com/src/hls/ph5f6253da0909f/hls_main.m3u8
[generic] hls_main: Downloading webpage
[debug] Identified a direct video link
[generic] hls_main: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [generic] hls_main: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2743, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] hls_main: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
ignoring the single quotes in the format ID seems to work: `-f 720p` or `-f "720p"`

for reference, here is what the m3u8 looks like:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1320000,RESOLUTION=1280x720,NAME='720p'
ph5f6253da0909f.m3u8
```
it is using a single-quoted string as an attribute value, which goes against [m3u8 spec](https://www.rfc-editor.org/rfc/rfc8216#section-4.2)

**Comment by X-Gorn** [comment]
@bashonly still show the same output:

```
[debug] Command-line config: ['-vU', '-c', '--max-filesize', '2097152000', '--embed-subs', '-f', '720p', 'https://cnnph-hls.octopusbanner.com/src/hls/ph632fe49ac94db/hls_main.m3u8', '--referer', 'https://cnnph-hls.octopusbanner.com', '-o', './DOWNLOADS/1829939747/hls_main_720p.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.9.16 (CPython x86_64 64bit) - Linux-4.15.0-189-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [generic] hls_main: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2743, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] hls_main: Requested format is not available. Use --list-formats for a list of available formats
```

also tried with the `"720p"` but it still doesn't work.

**Comment by pukkandan** [comment]
Same problem as https://github.com/yt-dlp/yt-dlp/issues/4901. Use `-f b*[format_id*=720p]` to workaround
