### ISSUE TITLE
[vimeo] player.vimeo.com URLs with trailing slash are unsupported

### ISSUE THREAD

**Issue by netdoggy** [yt-dlp/yt-dlp#6744]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This regular expression fails against links with a trailing slash
e.g. https://player.vimeo.com/video/123123123/

Reference: https://github.com/yt-dlp/yt-dlp/blob/141a8dff98874a426d7fbe772e0a8421bb42656f/yt_dlp/extractor/vimeo.py#L306

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
>yt-dlp.exe https://player.vimeo.com/video/54469442/ -v
[debug] Command-line config: ['https://player.vimeo.com/video/54469442/', '-v']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.04.06.074452 [141a8dff9] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {}
[debug] Loaded 1791 extractors
[generic] Extracting URL: https://player.vimeo.com/video/54469442/
[generic] 54469442: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 54469442: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://player.vimeo.com/video/54469442/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2523, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://player.vimeo.com/video/54469442/
```

Possible fix:

```   
_VALID_URL = r'''(?x)
                     https?://
                         (?:
                             (?:
                                 www|
                                 player
                             )
                             \.
                         )?
                         vimeo\.com/
                         (?:
                             (?P<u>user)|
                             (?!(?:channels|album|showcase)/[^/?#]+/?(?:$|[?#])|[^/]+/review/|ondemand/)
                             (?:.*?/)??
                             (?P<q>
                                 (?:
                                     play_redirect_hls|
                                     moogaloop\.swf)\?clip_id=
                             )?
                             (?:videos?/)?
                         )
                         (?P<id>[0-9]+)
                         (?(u)
                             /(?!videos|likes)[^/?#]+/?|
                             (?(q)|/(?P<unlisted_hash>[\da-f]{10}))?
                         )
                         (?:(?(q)[&]|(?(u)|/?)[?]).*?)?/?(?:[#].*)?$
                 '''

```
Added slash at the end line  of regexp (?:(?(q)[&]|(?(u)|/?)[?]).*?)?**/?**(?:[#].*)?$

**Comment by bashonly** [comment]
Is the trailing slash actually found in any embed URLs / in the wild? I find it strange that this issue has not come up before if so.

Regardless, the vimeo site accepts URLs with trailing slashes, so the extractor should too.

**Comment by netdoggy** [comment]
> Is the trailing slash actually found in any embed URLs / in the wild? I find it strange that this issue has not come up before if so.
> 
> Regardless, the vimeo site accepts URLs with trailing slashes, so the extractor should too.

Yes, I had such links on one of the sites similar to "patreon" with content in the form:
```<iframe src="https://player.vimeo.com/video/NNNNNNNNN/" allowfullscreen="true" frameborder="0" allowtransparency="true" scrolling="no"></iframe> ```

**Comment by dirkf** [comment]
This `_VALID_URL` is a prime case for the new list of patterns syntax.

Without that, maybe this is better:
```diff
                          (?:
                              (?P<u>user)|
                              (?!(?:channels|album|showcase)/[^/?#]+/?(?:$|[?#])|[^/]+/review/|ondemand/)
                              (?:.*?/)??
                              (?P<q>
                                  (?:
                                      play_redirect_hls|
                                      moogaloop\.swf)\?clip_id=
                              )?
-                             (?:videos?/)?
+                             (?(q)|videos?/)?
                          )
                          (?P<id>[0-9]+)
                          (?(u)
                              /(?!videos|likes)[^/?#]+/?|
-                             (?(q)|/(?P<unlisted_hash>[\da-f]{10}))?
+                             (?(q)|/(?P<unlisted_hash>[\da-f]{10})?)?
+                             (?(unlisted_hash)/?)
                          )
                          (?:(?(q)[&]|(?(u)|/?)[?]).+?)?(?:[#].*)?$
```
An additional `/` should only be allowed when group `q` is not matched, and this is the only place where it needs to be added, either with the existing one that precedes the `unlisted_hash`, or an additional one if that group matched. Also, the additional `videos?/` path element shouldn't match when group `q` is not matched, because the matchable text is now in the URL's query parameters, not its path.
