### ISSUE TITLE
Selector not working despite matching formats being available

### ISSUE THREAD

**Issue by mayeaux** [yt-dlp/yt-dlp#6761]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Despite the format being available, the selector string is not working, I've tried many combinations and nothing will work properly.

```
$ yt-dlp -f 'video[ext=mp4]' https://ok.ru/video/2409725102846 --list-formats
[Odnoklassniki] Extracting URL: https://ok.ru/video/2409725102846
[Odnoklassniki] 2409725102846: Downloading desktop webpage
[Odnoklassniki] 2409725102846: Downloading m3u8 information
[info] Available formats for 2409725102846:
ID       EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
mobile   mp4 unknown        │                  https │ unknown           unknown
hls-189  mp4 256x144     24 │ ~175.34MiB  189k m3u8  │ unknown      189k unknown    0k
mpd-0    mp4 256x144     24 │ ~ 97.03MiB  105k https │ avc1.64000C  105k mp4a.40.2  0k 44k DASH video, mp4_dash
lowest   mp4 unknown        │                  https │ unknown           unknown
hls-373  mp4 426x240     24 │ ~346.25MiB  374k m3u8  │ unknown      374k unknown    0k
mpd-1    mp4 426x240     24 │ ~275.21MiB  297k https │ avc1.640015  297k mp4a.40.2  0k 44k DASH video, mp4_dash
low      mp4 unknown        │                  https │ unknown           unknown
hls-752  mp4 640x360     24 │ ~696.99MiB  753k m3u8  │ unknown      753k unknown    0k
mpd-2    mp4 640x360     24 │ ~579.34MiB  626k https │ avc1.64001E  626k mp4a.40.2  0k 44k DASH video, mp4_dash
sd       mp4 unknown        │                  https │ unknown           unknown
hls-1248 mp4 852x480     24 │ ~  1.13GiB 1248k m3u8  │ unknown     1248k unknown    0k
mpd-3    mp4 852x480     24 │ ~  1.01GiB 1115k https │ avc1.64001E 1115k mp4a.40.2  0k 44k DASH video, mp4_dash
hd       mp4 unknown        │                  https │ unknown           unknown
hls-2628 mp4 1280x720    24 │ ~  2.38GiB 2628k m3u8  │ unknown     2628k unknown    0k
mpd-4    mp4 1280x720    24 │ ~  2.24GiB 2478k https │ avc1.64001F 2478k mp4a.40.2  0k 44k DASH video, mp4_dash
full     mp4 unknown        │                  https │ unknown           unknown
hls-4461 mp4 1920x1080   24 │ ~  4.04GiB 4462k m3u8  │ unknown     4462k unknown    0k
mpd-5    mp4 1920x1080   24 │ ~  3.88GiB 4288k https │ avc1.640028 4288k mp4a.40.2  0k 44k DASH video, mp4_dash
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU -f 'video[ext=mp4]' https://ok.ru/video/2409725102846
[debug] Command-line config: ['-vU', '-f', 'video[ext=mp4]', 'https://ok.ru/video/2409725102846']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.9.0 (CPython x86_64 64bit) - macOS-10.16-x86_64-i386-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: certifi-2022.12.07, no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[Odnoklassniki] Extracting URL: https://ok.ru/video/2409725102846
[Odnoklassniki] 2409725102846: Downloading desktop webpage
[Odnoklassniki] 2409725102846: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [Odnoklassniki] 2409725102846: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2743, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [Odnoklassniki] 2409725102846: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
For this it's better to use `-S ext` IMO

`yt-dlp -S ext "https://ok.ru/video/2409725102846"`

this will sort mp4 formats in front of the rest

otherwise you would want to use `-f "bestvideo[ext=mp4]*+bestaudio[ext=m4a]/best[ext=mp4]"`

**Comment by gamer191** [comment]
> otherwise you would want to use `-f "bestvideo[ext=mp4]*+bestaudio[ext=m4a]/best[ext=mp4]"`

you beat me to it. Although `-f [ext=mp4]` would probably also work

**Comment by mayeaux** [comment]
The problem is that none of the selectors work, I just chose `ext=mp4` because it's the most obvious.
```
$ yt-dlp -S ext -f 'video[height<480]' "https://ok.ru/video/2409725102846"
[Odnoklassniki] Extracting URL: https://ok.ru/video/2409725102846
[Odnoklassniki] 2409725102846: Downloading desktop webpage
[Odnoklassniki] 2409725102846: Downloading m3u8 information
ERROR: [Odnoklassniki] 2409725102846: Requested format is not available. Use --list-formats for a list of available formats

$ yt-dlp -S ext -f 'video[height>480]' "https://ok.ru/video/2409725102846"
[Odnoklassniki] Extracting URL: https://ok.ru/video/2409725102846
[Odnoklassniki] 2409725102846: Downloading desktop webpage
[Odnoklassniki] 2409725102846: Downloading m3u8 information
ERROR: [Odnoklassniki] 2409725102846: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
`-f video` is not valid syntax

https://github.com/yt-dlp/yt-dlp#format-selection

**Comment by mayeaux** [comment]
```
$ yt-dlp -S ext -f 'bestvideo[height>480]' "https://ok.ru/video/2409725102846"
[Odnoklassniki] Extracting URL: https://ok.ru/video/2409725102846
[Odnoklassniki] 2409725102846: Downloading desktop webpage
[Odnoklassniki] 2409725102846: Downloading m3u8 information
ERROR: [Odnoklassniki] 2409725102846: Requested format is not available. Use --list-formats for a list of available formats

$ yt-dlp -S ext -f 'bestvideo[height<480]' "https://ok.ru/video/2409725102846"
[Odnoklassniki] Extracting URL: https://ok.ru/video/2409725102846
[Odnoklassniki] 2409725102846: Downloading desktop webpage
[Odnoklassniki] 2409725102846: Downloading m3u8 information
ERROR: [Odnoklassniki] 2409725102846: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
all available formats are video+audio combined, so `bestvideo` will not select any of them

use `best[height>480]` or `bestvideo[height>480]*`

**Comment by mayeaux** [comment]
Thanks a lot, it was an IO error after all (idiot operator), appreciate the help
