### ISSUE TITLE
[twitter] Unable to download JSON metadata (only age-restricted links)

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#6763]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

came across this link here:
https://twitter.com/_Saraurora_/status/1614746772974501896

Seems to be "age restricted", cause if not logged in it shows this message on the twitter page:
Age-restricted adult content. This content might not be appropriate for people under 18 years old. To view this media, you’ll need to log in to Twitter.

Could not test this with --cookies though, due to limited internet access at the moment. 

all other public links download just fine.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -Uv -F "https://twitter.com/_Saraurora_/status/1614746772974501896"
[debug] Command-line config: ['-Uv', '-F', 'https://twitter.com/_Saraurora_/status/1614746772974501896']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.03 [934496428] (zip)
[debug] Python 3.11.3 (CPython arm64 64bit) - macOS-13.3-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1852 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.03
Current Build Hash: cfa97267ed664425bb74e861d3da044182bf65a8704998146da441896c922562
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Updating to stable@2023.03.04 ...
[debug] Downloading yt-dlp from https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/latest/download/SHA2-256SUMS
Updated yt-dlp to stable@2023.03.04
[debug] Restarting: /opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python ./yt-dlp -Uv -F https://twitter.com/_Saraurora_/status/1614746772974501896
[debug] Command-line config: ['-Uv', '-F', 'https://twitter.com/_Saraurora_/status/1614746772974501896']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.11.3 (CPython arm64 64bit) - macOS-13.3-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1787 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[twitter] Extracting URL: https://twitter.com/_Saraurora_/status/1614746772974501896
[twitter] 1614746772974501896: Downloading guest token
[twitter] 1614746772974501896: Downloading JSON metadata
WARNING: [twitter] Twitter API gave 404 response, retrying with deprecated auth token. Only one media item can be extracted
[twitter] 1614746772974501896: Downloading guest token
[twitter] 1614746772974501896: Downloading JSON metadata
ERROR: [twitter] 1614746772974501896: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "./yt-dlp/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/extractor/twitter.py", line 974, in _real_extract
    status = traverse_obj(self._call_api(f'statuses/show/{twid}.json', twid, {
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/extractor/twitter.py", line 136, in _call_api
    raise last_error
  File "./yt-dlp/yt_dlp/extractor/twitter.py", line 130, in _call_api
    result = self._download_json(
             ^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1048, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1012, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/extractor/common.py", line 882, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "./yt-dlp/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
Twitter broke our bypass for extracting age-restricted tweets without auth.

You'll need to pass login cookies:
```
$ yt-dlp -F "https://twitter.com/_Saraurora_/status/1614746772974501896" --cookies-from-browser "firefox:xu2iz3kn.default-release::twitter"
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 61 cookies from firefox
[twitter] Extracting URL: https://twitter.com/_Saraurora_/status/1614746772974501896
[twitter] 1614746772974501896: Downloading JSON metadata
[twitter] 1614746772974501896: Downloading m3u8 information
[info] Available formats for 1614746727411499011:
ID        EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
───────────────────────────────────────────────────────────────────────────────────
hls-256   mp4 600x270    │ ~316.51KiB  256k m3u8  │ avc1.4d001e  256k mp4a.40.2  0k
http-256  mp4 600x270    │ ~316.51KiB  256k https │ unknown      256k unknown    0k
hls-832   mp4 800x360    │ ~  1.00MiB  832k m3u8  │ avc1.4d001f  832k mp4a.40.2  0k
http-832  mp4 800x360    │ ~  1.00MiB  832k https │ unknown      832k unknown    0k
hls-2176  mp4 1280x576   │ ~  2.63MiB 2176k m3u8  │ avc1.640020 2176k mp4a.40.2  0k
http-2176 mp4 1280x576   │ ~  2.63MiB 2176k https │ unknown     2176k unknown    0k
```

The extractor should be updated to catch this error and `raise_login_required`. And I think the deprecated token code can be removed now since it no longer serves a purpose

**Comment by jasonm23** [comment]
yt-dlp -F "https://twitter.com/_Saraurora_/status/1614746772974501896" --cookies-from-browser firefox

Works for me

**Comment by flashthepublic** [comment]
From looking at the code the only cookie used is ct0 but even with this i get an error. No longer 404 but an unauthaurized 403 error

yt-dlp.exe "https://twitter.com/_xxxxxx_/status/_xxxxx_" --add-header "Cookie:ct0=_xxxxxxxxxx_"

```
[twitter] 1644757205999136773: Downloading guest token
ERROR: [twitter] xxxxxxxxxxx: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\twitter.py", line 974, in _real_extract
  File "yt_dlp\extractor\twitter.py", line 118, in _call_api
  File "yt_dlp\extractor\common.py", line 1048, in download_content
  File "yt_dlp\extractor\common.py", line 1012, in download_handle
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
> From looking at the code the only cookie used is ct0

There are other cookies that are required, but they are just passed through requests, the code doesn't manipulate them. Don't manually add cookie headers, just pass your auth cookies with `--cookies` or `--cookies-from-browser`

**Comment by flashthepublic** [comment]
Thanks @bashonly . You must be right as if i use a cookie.txt file extracted from my browser it works. 
I must be doing something wrong when I convert cookies to the --add-header "Cookie: xx=yyyy; ...." argument
_(I must do this as i use a custom chrome extension to communicate to a custom server hosting yt-dlp and can't have a txt file)_

**Comment by bashonly** [comment]
@flashthepublic
Because of the code below, the extractor will never treat you as logged in unless you pass `--cookies` or `--cookies-from-browser`:
https://github.com/yt-dlp/yt-dlp/blob/c3f624ef0a5d7a6ae1c5ffeb243087e9fc7d79dc/yt_dlp/extractor/twitter.py#L91-L93
And if not logged in, the extractor fetches a guest token and passes it as a header with API requests, which will most likely interfere with authentication.

I haven't tested this, but it's probably the best you can do without passing cookies or modifying the extractor:
```bash
--extractor-args "twitter:force_graphql"
--add-header "x-csrf-token:VALUE"  # replace VALUE with ct0 cookie value
--add-header "Cookie:auth_token=VALUE"  # replace VALUE with auth_token cookie value
--add-header "x-twitter-auth-type:OAuth2Session"
--add-header "x-twitter-client-language:en"
--add-header "x-twitter-active-user:yes"
--add-header "x-guest-token:"
```

**Comment by pukkandan** [comment]
If the only issue is that you can't write a file, you could just pass all the cookies in the `Cookie` header formatted correctly. If you are cherry picking specific ones, it's on you to figure out which ones are relevant.

**Comment by cunlem** [comment]
The needed cookies are `auth_token` and `ct0`. 

Adding them manually to request headers won't work due to what @bashonly has described. But you can fetch them once from browser (`--cookies-from-browser BROWSER --cookies cookies.txt`) and store in the jar for use in subsequent downloads (`--cookies cookies.txt`)

**Comment by pukkandan** [comment]
> Adding them manually to request headers won't work due to what bashonly has described.

Are you sure that is the reason? `_get_cookies` takes any added headers into account afair. Pls show log with `-v --print-traffic` (feel free to redact the actual cookie values)

**Comment by cunlem** [comment]
> Are you sure that is the reason?

With cookies it uses GraphQL endpoint. Without it tries to fetch guest token and fails:

```
yt-dlp --no-config --verbose --print-traffic --skip-download --add-headers 'Cookie: auth_token=***; ct0=***' 'https://twitter.com/_Saraurora_/status/1614746772974501896'
[debug] Command-line config: ['--no-config', '--verbose', '--print-traffic', '--skip-download', '--add-headers', 'Cookie: auth_token=***; ct0=***', 'https://twitter.com/_Saraurora_/status/1614746772974501896']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-69-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg git-2022-09-24-7cd252e (setts), ffprobe git-2022-09-24-7cd252e
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[twitter] Extracting URL: https://twitter.com/_Saraurora_/status/1614746772974501896
[twitter] 1614746772974501896: Downloading guest token
send: b'POST /1.1/guest/activate.json HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 0\r\nHost: api.twitter.com\r\nAuthorization: Bearer ***\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nCookie:  auth_token=***; ct0=***\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: close\r\n\r\n'
Zero length chunk ignored
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: date: Tue, 18 Apr 2023 13:25:10 GMT
header: perf: 7626143928
header: server: tsa_o
header: set-cookie: guest_id=***; Max-Age=34214400; Expires=Sat, 18 May 2024 13:25:11 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
header: set-cookie: ct0=***; Max-Age=34214400; Expires=Sat, 18 May 2024 13:25:11 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=Lax
header: content-type: application/json; charset=utf-8
header: cache-control: no-cache, no-store, max-age=0
header: content-length: 100
header: x-frame-options: SAMEORIGIN
header: content-encoding: gzip
header: x-transaction-id: ***
header: x-xss-protection: 0
header: content-disposition: attachment; filename=json.json
header: x-content-type-options: nosniff
header: strict-transport-security: max-age=631138519
header: x-response-time: 107
header: x-connection-hash: ***
header: connection: close
ERROR: [twitter] 1614746772974501896: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/twitter.py", line 974, in _real_extract
    status = traverse_obj(self._call_api(f'statuses/show/{twid}.json', twid, {
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/twitter.py", line 118, in _call_api
    guest_token_response = self._download_json(
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 1048, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 1012, in download_handle
    res = self._download_webpage_handle(
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 882, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by hsn10** [comment]
I have same problem, returns 404 with cookies from browser:

```
[debug] Command-line config: ['--no-mtime', '-vU', '--cookies-from-browser', 'vivaldi', 'https://twitter.com/i/status/1648991534698622976', '-o', 'army-gifts.mp4']
[debug] Portable config "C:\ProgramData\scoop\apps\yt-dlp\current\yt-dlp.conf": []
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from vivaldi
[debug] Extracting cookies from: "C:\Users\hsn\AppData\Local\Vivaldi\User Data\Default\Cookies"
[debug] Found local state file at "C:\Users\hsn\AppData\Local\Vivaldi\User Data\Local State"
ERROR: no encrypted key in Local State
Traceback (most recent call last):
  File "yt_dlp\cookies.py", line 872, in _get_windows_v10_key
KeyError: 'os_crypt'

[Cookies] Extracted 3272 cookies from vivaldi
[debug] cookie version breakdown: {'v10': 0, 'other': 3272, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[twitter] Extracting URL: https://twitter.com/i/status/1648991534698622976
[twitter] 1648991534698622976: Downloading guest token
[twitter] 1648991534698622976: Downloading JSON metadata
WARNING: [twitter] Twitter API gave 404 response, retrying with deprecated auth token. Only one media item can be extracted
[twitter] 1648991534698622976: Downloading guest token
[twitter] 1648991534698622976: Downloading JSON metadata
ERROR: [twitter] 1648991534698622976: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\twitter.py", line 974, in _real_extract
  File "yt_dlp\extractor\twitter.py", line 136, in _call_api
  File "yt_dlp\extractor\twitter.py", line 130, in _call_api
  File "yt_dlp\extractor\common.py", line 1048, in download_content
  File "yt_dlp\extractor\common.py", line 1012, in download_handle
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
```
$ yt-dlp https://twitter.com/i/status/1648991534698622976 -F --cookies-from-browser firefox:xu2pi3ya.default-release::twitter
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 59 cookies from firefox
[twitter] Extracting URL: https://twitter.com/i/status/1648991534698622976
[twitter] 1648991534698622976: Downloading JSON metadata
[twitter] 1648991534698622976: Downloading m3u8 information
[info] Available formats for 1648991237091868673:
ID       EXT RESOLUTION │ FILESIZE  TBR PROTO │ VCODEC       VBR ACODEC    ABR
──────────────────────────────────────────────────────────────────────────────
hls-632  mp4 320x564    │ ~6.37MiB 632k m3u8  │ avc1.4d001f 632k mp4a.40.2  0k
http-632 mp4 320x564    │ ~6.37MiB 632k https │ unknown     632k unknown    0k
hls-950  mp4 480x848    │ ~9.58MiB 950k m3u8  │ avc1.4d001f 950k mp4a.40.2  0k
http-950 mp4 480x848    │ ~9.58MiB 950k https │ unknown     950k unknown    0k
```
@hsn10 Are you sure you're logged into twitter in vivaldi? If you are, then I think something may be going wrong during cookie extraction (`ERROR: no encrypted key in Local State`), which would be a separate issue.
Try `--cookies` instead

**Comment by hsn10** [comment]
I don't know how to use --cookies and chat GPT doesn't know either.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

**Comment by bashonly** [comment]
>  So create a issue for failing to read cookies from vivaldi store?

you could, yeah. Include same log. The issue seems to be that yt-dlp can't find the key to decrypt your vivaldi cookies with

**Comment by Nonstopmaximum** [comment]
I have this same error.  yt-dlp -F “twitterlink" --cookies-from-browser “chrome” presents me with extracted cookie and video info but I still have no download, and I still get JSON error trying to download after that. I need a more detailed explanation on what to do.

**Comment by bashonly** [comment]
@Nonstopmaximum
run `yt-dlp --update-to-nightly`
then try it it again with `-v` added to your command
if it still doesn't work, post the log

**Comment by bashonly** [comment]
@Nonstopmaximum sorry, I made a typo in my last comment
it should be `yt-dlp --update-to nightly`
(space inbetween `--update-to` and `nightly`)

**Comment by LandisTwo** [comment]
I'm still having this issue 2023-07-06 in vivaldi.
yt-dlp will show available formats using -F, but
yt-dlp extracts cookies, but still fails to download

- - from opensuse output - - 
-landis@1linux-v5581:~/Downloads/transfer>yt-dlp -f 'http-2176' https://twitter.com/i/status/1677015259805274117 --cookies-from-browser "vivaldi::default::twitter" -o 'fireworks over LA - despite being illegal - July 2023.mp5'
[Cookies] Extracting cookies from vivaldi
[Cookies] Extracted 2043 cookies from vivaldi
[twitter] Extracting URL: https://twitter.com/i/status/1677015259805274117
[twitter] 1677015259805274117: Downloading JSON metadata
[twitter] 1677015259805274117: Downloading m3u8 information
WARNING: [twitter] Failed to download m3u8 information: HTTP Error 403: Forbidden
[info] 1676667130631147537: Downloading 1 format(s): http-2176
ERROR: unable to download video data: HTTP Error 403: Forbidden
 
what am i missing?
Landis.

**Comment by bashonly** [comment]
> what am i missing?

@LandisTwo open it in your browser:
> This media has been disabled in response to a report by the copyright owner.

**Comment by LandisTwo** [comment]
@bashonly, 
open what in my browser?

**Comment by bashonly** [comment]
@LandisTwo the link. https://twitter.com/i/status/1677015259805274117

**Comment by LandisTwo** [comment]
Hmm.
I have.
the browser is where I copied the link from.
in terminal I used the code I previously stated.
then error.
Are you saying I need to open again to be reflected in the cookies db?

**Comment by LandisTwo** [comment]
nope
opened link in [vivaldi] browser
re-run command in terminal
same error

**Comment by LandisTwo** [comment]
@bashonly, thank you for taking time with me

**Comment by bashonly** [comment]
I'm saying if you open the link in your browser, you'll see this:
> This media has been disabled in response to a report by the copyright owner.

or at least that's what I see

**Comment by LandisTwo** [comment]
@bashonly this is a new issue, this week
i just updated yt-dlp to 2023-06-22
I put it off, because I was reluctant to up python to 310

**Comment by LandisTwo** [comment]
> I'm saying if you open the link in your browser, you'll see this:
> 
> > This media has been disabled in response to a report by the copyright owner.
> 
> or at least that's what I see

No. I SEE the video (post page containing video) and can play it.

**Comment by LandisTwo** [comment]
@bashonly, in the last week, this is the error I get with Every video from twitter.
Before this week, I could download any video I could play. : (

**Comment by bashonly** [comment]
@LandisTwo update again

I can't play the video in browser, it has been removed by twitter for copyright violation. Nothing we can do about it. but if you update yt-dlp you will be able to download videos that have not been removed
