### ISSUE TITLE
No video formats found

### ISSUE THREAD

**Issue by iwnb** [yt-dlp/yt-dlp#6804]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Similar links from the same site have all been downloaded.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.sbs.com.au/ondemand/movie/tell-it-to-the-bees/1959871043534
[debug] Command-line config: ['-vU', 'https://www.sbs.com.au/ondemand/movie/tell-it-to-the-bees/1959871043534']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.1.9-pclos1-x86_64-with-glibc2.36 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3 (fdk,setts), ffprobe 5.1.3
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.7, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[SBS] Extracting URL: https://www.sbs.com.au/ondemand/movie/tell-it-to-the-bees/1959871043534
[SBS] 1959871043534: Downloading JSON metadata
[ThePlatform] Extracting URL: http://link.theplatform.com/s/Bgtm9B/PtHi3nE4WMHV?feed=Video%20-%20Single&mbr=true&manifest=m3u&ord=7913489&policy=11929623&dfptag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.film.sbs.com.au%2Fsec30htmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dpreroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1959871043534%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1959871043534&dfpmidtag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.film.sbs.com.au%2Fsec30midrollhtmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dmidroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F1959871043534%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D1959871043534#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] PtHi3nE4WMHV: Downloading SMIL data
[ThePlatform] PtHi3nE4WMHV: Downloading m3u8 information
WARNING: [ThePlatform] Failed to download m3u8 information: HTTP Error 403: Forbidden
[ThePlatform] PtHi3nE4WMHV: Downloading JSON metadata
ERROR: [ThePlatform] PtHi3nE4WMHV: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1727, in process_ie_result
    return self.process_ie_result(
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ThePlatform] PtHi3nE4WMHV: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6543

**Comment by iwnb** [comment]
As I mentioned in the issue I filed, I have been able to download all other
videos I have wanted to download from sbs.com.au.
