### ISSUE TITLE
academy.zenva.com

### ISSUE THREAD

**Issue by ds2k5** [yt-dlp/yt-dlp#6850]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Example URLs

https://academy.zenva.com/lesson/introduction-334/

### Provide a description that is worded well enough to be understood

Download will not work

yt-dlp -u name@domain.tld https://academy.zenva.com/lesson/introduction-334/

[generic] Extracting URL: https://academy.zenva.com/lesson/introduction-334/
[generic] introduction-334: Downloading webpage
[redirect] Following redirect to https://academy.zenva.com/wp-login.php?redirect_to=https%3A%2F%2Facademy.zenva.com%2Flesson%2Fintroduction-334%2F&reauth=1
[generic] Extracting URL: https://academy.zenva.com/wp-login.php?redirect_to=https%3A%2F%2Facademy.zenva.com%2Flesson%2Fint...tion-334%2F&reauth=1
[generic] wp-login.php?redirect_to=https://academy.zenva: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] wp-login.php?redirect_to=https://academy.zenva: Extracting information
ERROR: Unsupported URL: https://academy.zenva.com/wp-login.php?redirect_to=https%3A%2F%2Facademy.zenva.com%2Flesson%2Fintroduction-334%2F&reauth=1

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -v -u name@domain.tld https://academy.zenva.com/lesson/introduction-334/
[debug] Command-line config: ['-v', '-u', 'PRIVATE', 'https://academy.zenva.com/lesson/introduction-334/']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Python 3.10.10 (CPython x86_64 64bit) - Linux-5.15.106-1-MANJARO-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.12.07, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[generic] Extracting URL: https://academy.zenva.com/lesson/introduction-334/
[generic] introduction-334: Downloading webpage
[redirect] Following redirect to https://academy.zenva.com/wp-login.php?redirect_to=https%3A%2F%2Facademy.zenva.com%2Flesson%2Fintroduction-334%2F&reauth=1
[generic] Extracting URL: https://academy.zenva.com/wp-login.php?redirect_to=https%3A%2F%2Facademy.zenva.com%2Flesson%2Fintroduction-334%2F&reauth=1
[generic] wp-login.php?redirect_to=https://academy.zenva: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] wp-login.php?redirect_to=https://academy.zenva: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://academy.zenva.com/wp-login.php?redirect_to=https%3A%2F%2Facademy.zenva.com%2Flesson%2Fintroduction-334%2F&reauth=1
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://academy.zenva.com/wp-login.php?redirect_to=https%3A%2F%2Facademy.zenva.com%2Flesson%2Fintroduction-334%2F&reauth=1
```

**Comment by ivanskodje** [comment]
For this to be supported, I believe https://github.com/yt-dlp/yt-dlp/issues/7098 will have to be addressed first :cry:

**Comment by pmrowla** [comment]
I created a trial account to test the linked video, not sure if their backend changed in the last year but it gets loaded as an HLS m3u8 playlist for me (tested in Chrome and Safari). It doesn't look like this needs #7098
