### ISSUE TITLE
Error when downloading Peloton Video ... Sorry if I'm doing this wong...

### ISSUE THREAD

**Issue by Facey-McFace** [yt-dlp/yt-dlp#6854]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm confused, but I guess you get many support requests and the above is necessary...

I've added the extension from moz extensions and installed the helper from repo. I did make install for helper...

I'm not running flatpack ff.

I'm trying to grab a vid from peloton.

I get error... `Error: Got exception communicating with helper: Error:...` <- cant see any more error. Not sure how to proceed.

Sorry for showing my noobs...

Many thanks,

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ ./yt-dlp -vU https://members.onepeloton.co.uk/classes/player/965bbc86c2d24636a7cc08d36a3de556
[debug] Command-line config: ['-vU', 'https://members.onepeloton.co.uk/classes/player/965bbc86c2d24636a7cc08d36a3de556']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-69-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: brotli-1.0.9, certifi-2020.06.20, no_Cryptodome-None, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://members.onepeloton.co.uk/classes/player/965bbc86c2d24636a7cc08d36a3de556
[generic] 965bbc86c2d24636a7cc08d36a3de556: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 965bbc86c2d24636a7cc08d36a3de556: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://members.onepeloton.co.uk/classes/player/965bbc86c2d24636a7cc08d36a3de556
Traceback (most recent call last):
  File "/home/dan/Downloads/./yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dan/Downloads/./yt-dlp/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/home/dan/Downloads/./yt-dlp/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/dan/Downloads/./yt-dlp/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://members.onepeloton.co.uk/classes/player/965bbc86c2d24636a7cc08d36a3de556
```

**Comment by pukkandan** [comment]
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

You sure? The video seems to need login. Try passing cookies

**Comment by bashonly** [comment]
Also, as a workaround try changing the URL from .co.uk to .com
`https://members.onepeloton.com/classes/player/965bbc86c2d24636a7cc08d36a3de556`

and pass cookies

the peloton extractor does not currently match .co.uk

**Comment by Facey-McFace** [comment]
Fantastic!

For some reason `--cookies-from-browser` didn't work (even though I picked the right profile and I see `[debug] Extracting cookies from: "/home/xxx/.mozilla/firefox/yyy.Personal/cookies.sqlite"` as expected.

However, `--username x --password y` worked perfectly!

Huge help, many thanks,
Dan.

**Comment by bashonly** [comment]
If you had to change the URL to .com, then cookies probably didn't work because they were for onepeloton.co.uk instead. That's something maybe the extractor could handle. Are you willing to share your account credentials if a developer wants to work on it?

**Comment by Facey-McFace** [comment]
Sure thing, happy to DM the account. I checked that the .com version worked in the browser before anything else, so I hoped that the cookies would be correct.

On the topic of debugging... man the audio of the rip is off! Just checking the `--help` now to see if I can fix it :-)

**Comment by Facey-McFace** [comment]
FWIW, the `--cookies-from-browser` is now working, and I think I've resolved the audio issue by just turning the volume down... not sure why it distorted so badly to begin with...
