### ISSUE TITLE
[Dropout.tv] - Unable to log in: bad username or password

### ISSUE THREAD

**Issue by Toixinhell** [yt-dlp/yt-dlp#6877]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Switzerland

### Provide a description that is worded well enough to be understood

When trying to download a video from dropout.tv I get the following `ERROR: [vhx:embed] 2460086: Unable to log in: bad username or password`.
I double checked and have no problem login in to dropout.tv website and watching the video directly. I also tried the username parameter with and without ".
After sifting through the resolved and older issues I also tried it directly with python which also did not work with the same error message.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU --username xxx.xxx@xxx.xx --password "xxxxxxxxx" --referer "https://www.dropout.tv/" https://www.dropout.tv/dimension-20-neverafter/season:1/videos/the-times-of-shadow
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', '--referer', 'https://www.dropout.tv/', 'https://www.dropout.tv/dimension-20-neverafter/season:1/videos/the-times-of-shadow']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-12-15-git-9adf02247c-full_build-www.gyan.dev (setts), ffprobe 2022-12-15-git-9adf02247c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[Dropout] Extracting URL: https://www.dropout.tv/dimension-20-neverafter/season:1/videos/the-times-of-shadow
[Dropout] the-times-of-shadow: Getting authenticity token
[Dropout] the-times-of-shadow: Logging in
[Dropout] the-times-of-shadow: Downloading webpage
[vhx:embed] Downloading login page
[vhx:embed] Logging in
ERROR: [vhx:embed] 2460086: Unable to log in: bad username or password
  File "yt_dlp\extractor\common.py", line 691, in extract
  File "yt_dlp\extractor\common.py", line 597, in initialize
  File "yt_dlp\extractor\vimeo.py", line 76, in _perform_login
```

**Comment by Toixinhell** [comment]
Same with a python script:
Script:
`from yt_dlp import YoutubeDL

ydl_opts = {
    "username": "xxx.xxx@xxx.xx",
    "password": "xxxxxxxxx",
    "http_headers": {"referer": "https://www.dropout.tv"},
    "verbose": True,
}

with YoutubeDL(ydl_opts) as ydl:
    ydl.download(
        [
            "https://www.dropout.tv/dimension-20-misfits-and-magic/season:1/videos/the-chosen-ones"
        ]
    )`

Output:
` py .\Dropout.py
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API 
[debug] params: {'username': 'xxx.xxx@xxx.xx', 'password': 'xxxxxxxxxxxxxx', 'http_headers': {'referer': 'https://www.dropout.tv'}, 'verbose': True, 'compat_opts': set()} 
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: none 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2 
[debug] Proxy map: {} 
[debug] Loaded 1786 extractors 
[Dropout] Extracting URL: https://www.dropout.tv/dimension-20-misfits-and-magic/season:1/videos/the-chosen-ones 
[Dropout] the-chosen-ones: Getting authenticity token 
[Dropout] the-chosen-ones: Logging in 
[Dropout] the-chosen-ones: Downloading webpage 
ERROR: [Dropout] the-chosen-ones: Incorrect username/password 
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 694, in extract        
    ie_result = self._real_extract(url) 
                ^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\dropout.py", line 132, in _real_extract 
    raise ExtractorError(login_err, expected=True) 

Traceback (most recent call last):
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1594, in __extract_info
                ^^^^^^^^^^^^^^^
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\dropout.py", line 132, in _real_extract
    raise ExtractorError(login_err, expected=True)
yt_dlp.utils.ExtractorError: [Dropout] the-chosen-ones: Incorrect username/password

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hagbart\Documents\Python\first project\Dropout.py", line 11, in <module>
    ydl.download(
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3369, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3344, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1536, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\Hagbart\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 955, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [Dropout] the-chosen-ones: Incorrect username/password`

**Comment by Toixinhell** [comment]
also tried this with the cookie parameter with no change in behavior. 
```
--cookies cookies.txt
```

**Comment by bashonly** [comment]
could you show log with `--cookies` and *without* `--username`/`--password`?

**Comment by Toixinhell** [comment]
It works with only the cookie parameter and without username and password

**Comment by bashonly** [comment]
In the OP's log, yt-dlp is successfully logging into dropout.tv, but then it also tries to log into vimeo with the same credentials and errors out. Not sure how to avoid this

Something different is happening the python script log, maybe an escaping issue with the password?

**Comment by Toixinhell** [comment]
> 

The password has only alphanumerical characters.

**Comment by pukkandan** [comment]
> In the OP's log, yt-dlp is successfully logging into dropout.tv, but then it also tries to log into vimeo with the same credentials and errors out. Not sure how to avoid this

By using `--netrc`. Or, we'd have to add a way to pass extractor-specific usernames

**Comment by bashonly** [comment]
@ChildishGiant Unrelated, open a new issue
