### ISSUE TITLE
Can't decrypt cookies from vivaldi store

### ISSUE THREAD

**Issue by hsn10** [yt-dlp/yt-dlp#6880]
I have same problem, returns 404 with cookies from browser:

```
[debug] Command-line config: ['--no-mtime', '-vU', '--cookies-from-browser', 'vivaldi', 'https://twitter.com/i/status/1648991534698622976', '-o', 'army-gifts.mp4']
[debug] Portable config "C:\ProgramData\scoop\apps\yt-dlp\current\yt-dlp.conf": []
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from vivaldi
[debug] Extracting cookies from: "C:\Users\hsn\AppData\Local\Vivaldi\User Data\Default\Cookies"
[debug] Found local state file at "C:\Users\hsn\AppData\Local\Vivaldi\User Data\Local State"
ERROR: no encrypted key in Local State
Traceback (most recent call last):
  File "yt_dlp\cookies.py", line 872, in _get_windows_v10_key
KeyError: 'os_crypt'

[Cookies] Extracted 3272 cookies from vivaldi
[debug] cookie version breakdown: {'v10': 0, 'other': 3272, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[twitter] Extracting URL: https://twitter.com/i/status/1648991534698622976
[twitter] 1648991534698622976: Downloading guest token
[twitter] 1648991534698622976: Downloading JSON metadata
WARNING: [twitter] Twitter API gave 404 response, retrying with deprecated auth token. Only one media item can be extracted
[twitter] 1648991534698622976: Downloading guest token
[twitter] 1648991534698622976: Downloading JSON metadata
ERROR: [twitter] 1648991534698622976: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\twitter.py", line 974, in _real_extract
  File "yt_dlp\extractor\twitter.py", line 136, in _call_api
  File "yt_dlp\extractor\twitter.py", line 130, in _call_api
  File "yt_dlp\extractor\common.py", line 1048, in download_content
  File "yt_dlp\extractor\common.py", line 1012, in download_handle
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

_Originally posted by @hsn10 in https://github.com/yt-dlp/yt-dlp/issues/6763#issuecomment-1516834720_

**Comment by pukkandan** [comment]
@mbway

**Comment by mbway** [comment]
I just installed a fresh copy of Vivaldi (6.0.2979.15) on Windows 10 then opened up `C:\Users\<user>\AppData\Local\Vivaldi\User Data\Local State` and my local state file did contain `os_crypt` so it looks like the `Local State` being loaded in the bug report is corrupt.

Can you open up `C:\Users\hsn\AppData\Local\Vivaldi\User Data\Local State` in a text editor (any will do including notepad) and search for `crypt`? The `KeyError: 'os_crypt'` indicates that the `Local State` file parses correctly as json but does not contain that key which is strange.

**Comment by hsn10** [comment]
no crypt there

**Comment by mbway** [comment]
I had another look at the chromium source code and there have been a number of changes made since the initial `--cookies-from-browser` implementation. I will work on a PR to address these changes. One of the changes may explain this issue

**Comment by mbway** [comment]
I worked through the changes that have been made to chromium but I still can't explain the issue you are having. I tried creating an entirely fresh windows 10 VM and installing the latest Vivaldi (and chrome) and all my cookies were v10 encoded.

I did some digging and found [the exact commit](https://chromium.googlesource.com/chromium/src/+/265b39473af0faac989b44afb6d4eb5cb2fd2e24%5E%21/#F12) where the windows encryption added the v10 prefix. I'm pretty sure that since that commit in 2019 there has not been possible for a user to create cookies that yt-dlp would consider 'other' as they are hard coded to have the v10 prefix. So unless your local state is very old I think something must be wrong.

I found [another commit](https://chromium.googlesource.com/chromium/src/+/f95c449bb79a961ae3332f6783f770159a3e1189) that mentions that:
```
On Windows, Local State stores OSCrypt encryption key
which is used to encrypt cookies. [if] this key is not persisted,
[Chrome] on Windows creates a new encryption key[].
```
so if your local state doesn't contain the `os_crypt` key then the browser should be clearing your cookies and re-generating the local state next time it runs.

My conclusion is that something is probably wrong with your particular installation.
I looked in the yt-dlp issue tracker for other cases where people were getting cookies categorized as 'other' and I couldn't find any.
To debug further would require logs and data that may contain sensitive information (like your cookie database and browser debug logs) so I think it's best to leave it at that. re-installing your browser would likely be enough to fix things.

**Comment by mbway** [comment]
if you want to debug a bit further it would be interesting to know what the prefixes actually are in the cookies. This can be determined by installing [sqlitebrowser](https://sqlitebrowser.org/), opening `C:\Users\hsn\AppData\Local\Vivaldi\User Data\Default\Cookies` (browser needs to be closed while you are reading this file)

For example here is one of my cookies starting with the text 'v10'
![Screenshot_20230423_212603](https://user-images.githubusercontent.com/4923501/233864270-1bfb2395-a050-4a06-b33f-ea37e38d43bc.png)

**Comment by hsn10** [comment]
it doesn't clear cookies on restart. it works normally.

**Comment by hsn10** [comment]
write SQL command you want me to run against vivaldi store

**Comment by mbway** [comment]
how about
```
SELECT substr(encrypted_value, 1, 3) as prefix, COUNT(*) as count FROM cookies GROUP BY prefix
```
for me this gives:
```
prefix   count
--------------
NULL     18
v11      992
```
your cookies seem to be 'other' so I'm wondering what they are exactly
