### ISSUE TITLE
Dailymotion video HTTP 403

### ISSUE THREAD

**Issue by Berbe** [yt-dlp/yt-dlp#6888]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

My problem looks very much like the #4727 one, closed without a solution being provided other than "It works for me".

Opening the URL/reading the video works with a browser in private session mode (clean/no history of cookies).
I got my doubts about the GDPR banner, but could that trigger a HTTP 403?

I also tried reusing the `client_token` cookie used in some browser test with the `--cookies` flag pointing ot a Netscape-formatted cookie jar, yielding no success.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.dailymotion.com/video/x8kblpl']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-16-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[dailymotion] Extracting URL: https://www.dailymotion.com/video/x8kblpl
[dailymotion] Downloading Access Token
[dailymotion] x8kblpl: Downloading media JSON metadata
[dailymotion] x8kblpl: Downloading metadata JSON
[dailymotion] x8kblpl: Downloading m3u8 information
WARNING: [dailymotion] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] x8kblpl: Downloading 1 format(s): http-1080-1
[debug] Invoking http downloader on "https://proxy-038.dc3.dailymotion.com/sec(WAn-wCortltfCKteYcApFBu_dNWBPYXwF_rDXPbuFFIZL-bdF3U1E79-7sGvMqAHhTWCbikleNOr2nZyYZC-CA)/video/180/368/517863081_mp4_h264_aac_fhd_14.mp4"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/berbe/venv/youtubedl/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3247, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/berbe/venv/youtubedl/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2970, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/berbe/venv/youtubedl/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/home/berbe/venv/youtubedl/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 376, in real_download
    establish_connection()
  File "/home/berbe/venv/youtubedl/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/berbe/venv/youtubedl/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by dirkf** [comment]
I can't reproduce this with yt-dlp or yt-dl from the UK. At least the `--test` bytes download fine.

**Comment by bigbrother87** [comment]
Same issue here. Tested in US and France.
```
[debug] Command-line config: ['https://www.dailymotion.com/video/x8q9qhu', '-vU']
[debug] Home config "yt-dlp.conf": ['-i', '--add-metadata', '--sub-langs', 'all', '--embed-subs', '--convert-subs', 'srt', '--embed-thumbnail', '--merge-output-format', 'mkv', '-o', '/mnt/youtube-dl/%(uploader)s/%(playlist)s/S01E%(playlist_index)s [%(upload_date)s]- %(title)s [%(id)s].%(ext)s', '--download-archive', '/mnt/youtube-dl/download_log.txt', '--sleep-interval', '60', '--max-sleep-interval', '160', '--cookies', '/mnt/youtube-dl/cookies.txt', '--downloader', 'aria2c', '--no-check-certificates']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.9.7 (CPython x86_64 64bit) - Linux-6.1.44-x86_64-with-glibc2.24 (OpenSSL 1.1.0l  10 Sep 2019, glibc 2.24)
[debug] exe versions: ffmpeg 3.2.16-1, ffprobe 3.2.16-1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-3.16.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1901 extractors
[debug] Loading archive file '/mnt/youtube-dl/download_log.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[dailymotion] Extracting URL: https://www.dailymotion.com/video/x8q9qhu
[dailymotion] x8q9qhu: Downloading media JSON metadata
ERROR: [dailymotion] x8q9qhu: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/extractor/dailymotion.py", line 241, in _real_extract
    media = self._call_api(
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/extractor/dailymotion.py", line 78, in _call_api
    resp = self._download_json(
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1033, in download_handle
    res = self._download_webpage_handle(
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "/usr/lib/python/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 4052, in urlopen
    return self._request_director.send(req)
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/lib/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 4074, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 401: Unauthorized

```

**Comment by bashonly** [comment]
@bigbrother87 try adding `--no-cookies` to your command

**Comment by bigbrother87** [comment]
That worked, so I removed all DailyMotion entries from my cookies file. Thanks for the help!

**Comment by bashonly** [comment]
@linux40 different error, different issue. Please open a new issue with a ***COMPLETE*** verbose log
