### ISSUE TITLE
Ceritifcate verify failed

### ISSUE THREAD

**Issue by aubymori** [yt-dlp/yt-dlp#6892]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Whenever trying to download a YouTube video, I get an error that the certificate verify failed. This is related to the project [Rehike](https://github.com/Rehike/Rehike). It runs on a local server with its own certificate, which is installed by the user. It then takes over `www.youtube.com` using the hostsfile. More details about on how it's installed [here](https://github.com/Rehike/Rehike/wiki/Installation), this should help.

A band-aid fix is to pass `--no-check-certificates`, but I was wondering if a more permanent fix could be applicable.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Aubrey>yt-dlp -vU https://www.youtube.com/watch?v=YozsViVwNz4
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=YozsViVwNz4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-04-06-git-b564ad8eac-essentials_build-www.gyan.dev (setts), ffprobe 2023-04-06-git-b56
4ad8eac-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets
-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=YozsViVwNz4
[youtube] YozsViVwNz4: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
: self signed certificate (_ssl.c:1131)>
[youtube] YozsViVwNz4: Downloading android player API JSON
WARNING: [youtube] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_
ssl.c:1131)>. Retrying (1/3)...
[youtube] YozsViVwNz4: Downloading android player API JSON
WARNING: [youtube] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_
ssl.c:1131)>. Retrying (2/3)...
[youtube] YozsViVwNz4: Downloading android player API JSON
WARNING: [youtube] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_
ssl.c:1131)>. Retrying (3/3)...
[youtube] YozsViVwNz4: Downloading android player API JSON
[youtube] YozsViVwNz4: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
: self signed certificate (_ssl.c:1131)>
[youtube] YozsViVwNz4: Downloading web player API JSON
WARNING: [youtube] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_
ssl.c:1131)>. Retrying (1/3)...
[youtube] YozsViVwNz4: Downloading web player API JSON
WARNING: [youtube] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_
ssl.c:1131)>. Retrying (2/3)...
[youtube] YozsViVwNz4: Downloading web player API JSON
WARNING: [youtube] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_
ssl.c:1131)>. Retrying (3/3)...
[youtube] YozsViVwNz4: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify faile
d: self signed certificate (_ssl.c:1131)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAIL
ED] certificate verify failed: self signed certificate (_ssl.c:1131)')))
ERROR: [youtube] YozsViVwNz4: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate v
erify failed: self signed certificate (_ssl.c:1131)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_
VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\youtube.py", line 3915, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 3883, in _download_player_responses
  File "yt_dlp\extractor\youtube.py", line 3610, in _extract_player_responses
  File "yt_dlp\extractor\youtube.py", line 3581, in _extract_player_responses
  File "yt_dlp\extractor\youtube.py", line 3501, in _extract_player_response
  File "yt_dlp\extractor\youtube.py", line 908, in _extract_response
  File "yt_dlp\utils.py", line 6141, in __iter__
  File "yt_dlp\extractor\common.py", line 3728, in _error_or_warning
  File "yt_dlp\utils.py", line 6149, in report_retry
  File "yt_dlp\extractor\youtube.py", line 910, in _extract_response
  File "yt_dlp\extractor\youtube.py", line 586, in _call_api
  File "yt_dlp\extractor\common.py", line 1048, in download_content
  File "yt_dlp\extractor\common.py", line 1012, in download_handle
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.
c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1555, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificat
e (_ssl.c:1131)>
```

**Comment by pukkandan** [comment]
> It runs on a local server with its own certificate, which is installed by the user. It then takes over `www.youtube.com` using the hostsfile.

By default, the exe is bundled with it's own certificates and do not use system's. Use `--compat-option no-certifi`

**Comment by ussserrr** [comment]
You probably also need `--no-check-certificate` option.

**Comment by aubymori** [comment]
> You probably also need `--no-check-certificate` option.

![8A-JQ3Ztxdzf_Hu2](https://github.com/yt-dlp/yt-dlp/assets/44238627/5ad1853a-2d67-41fd-9ed4-505cf6c3f872)
