### ISSUE TITLE
whyp.it audio Site support request

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#6913]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

Track - https://www.whyp.it/tracks/82871/third-times-the-charm
Channel page - https://www.whyp.it/users/12417/sabinewintersaudio

### Provide a description that is worded well enough to be understood

I can confirm I can download the mp3 if I manually pass all the relevant headers to the CDN.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '-F', '--compat-options', 'list-formats', '--compat-options', 'format-sort', '--', 'https://whyp.it/tracks/82871/third-times-the-charm']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version nightly@2023.04.16.034742 [9874e82b5] (win_exe)
[debug] Compatibility options: format-sort, list-formats
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {}
[debug] Extractor Plugins: AGB (YoutubeIE), Youtube_AgeGateBypassIE
[debug] Loaded 1798 extractors
[generic] Extracting URL: https://whyp.it/tracks/82871/third-times-the-charm
[generic] third-times-the-charm: Downloading webpage
[redirect] Following redirect to https://www.whyp.it/tracks/82871/third-times-the-charm
[generic] Extracting URL: https://www.whyp.it/tracks/82871/third-times-the-charm
[generic] third-times-the-charm: Downloading webpage
[generic] third-times-the-charm: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.whyp.it/tracks/82871/third-times-the-charm
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.whyp.it/tracks/82871/third-times-the-charm
```

**Comment by bashonly** [comment]
Support added in 2c566ed14101673c651c08c306c30fa5b4010b85

`yt-dlp --update-to nightly`

**Comment by barkoder** [comment]
Woah that was quick! Thank you @bashonly !

Might I direct your attention to #4001 as well? Thanks.
