### ISSUE TITLE
Error splitting the argument list: Option not found 

### ISSUE THREAD

**Issue by DanilaParakhnevich** [yt-dlp/yt-dlp#6929]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

## Question

Cannot merge audio and video files. 

![image](https://user-images.githubusercontent.com/67919226/234855047-04a36f18-c651-4d8b-916c-cd5a9017cee7.png)

ps doesn't work even without arguments

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API
[debug] params: {'logger': False, 'merge_output_format': 'mp4', 'verbose': True, 'compat_opts': set()}
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.35)
[debug] exe versions: ffmpeg 5.0.2 (fdk), ffprobe 5.0.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Extractor Plugins: DTubeIE, DTubeQueryIE, DTubeSearchIE, DTubeUserIE
[debug] Plugin directories: ['/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp_plugins']
[debug] Loaded 1789 extractors
[facebook] Extracting URL: https://www.facebook.com/watch/?v=790051908909640
[facebook] 790051908909640: Downloading webpage
[facebook] 790051908909640: Downloading MPD manifest
[debug] Sort order given by extractor: res, quality
[debug] Formats sorted by: hasvid, ie_pref, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 790051908909640: Downloading 1 format(s): 811618783816991v-1+250014924088408a-1
[debug] Invoking http downloader on "https://video-frt3-2.xx.fbcdn.net/v/t39.25447-2/343356746_957485158786473_126591709152084704_n.mp4?_nc_cat=1&ccb=1-7&_nc_sid=9c5c06&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfcjJfdnA5X2dlbjFhdmNfcTkwX2ZyYWdfMl92aWRlbyJ9&_nc_ohc=UcPbb1sAtEMAX9Afhnh&_nc_ht=video-frt3-2.xx&oh=00_AfAJHaaoSr6Ef38HePcA9oysyd30MKvpe6l6MqvfJrrZiw&oe=64500FEA"
[debug] Invoking http downloader on "https://video-frt3-2.xx.fbcdn.net/v/t39.25447-2/343291287_185476457650812_6691690219789024962_n.mp4?_nc_cat=1&ccb=1-7&_nc_sid=9c5c06&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfYXVkaW9fYWFjcF82NF9mbm9ybTE0X2ZyYWdfMl9hdWRpbyJ9&_nc_ohc=ZJnjsgDxe7sAX_B6Eoo&_nc_ht=video-frt3-2.xx&oh=00_AfBo72o-fguUohlTanxFC4brNrgDfQ06EOCAwdu20FJzLg&oe=645005E6"
[download] Sea turtle alerts man to help trapped buddy! 😯 [790051908909640].f811618783816991v-1.mp4 has already been downloaded
[download] 100% of   14.63MiB
[download] Sea turtle alerts man to help trapped buddy! 😯 [790051908909640].f250014924088408a-1.m4a has already been downloaded
[download] 100% of  248.67KiB
[Merger] Merging formats into "Sea turtle alerts man to help trapped buddy! 😯 [790051908909640].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Sea turtle alerts man to help trapped buddy! 😯 [790051908909640].f811618783816991v-1.mp4' -i 'file:Sea turtle alerts man to help trapped buddy! 😯 [790051908909640].f250014924088408a-1.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Sea turtle alerts man to help trapped buddy! 😯 [790051908909640].temp.mp4'
[debug] ffmpeg version 5.0.2 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --disable-debug --disable-doc --disable-static --enable-optimizations --enable-shared --disable-everything --enable-ffplay --enable-ffprobe --enable-gnutls --enable-libaom --enable-libdav1d --enable-libfdk-aac --enable-libmp3lame --enable-libfontconfig --enable-libfreetype --enable-libopus --enable-libpulse --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-openal --enable-opengl --enable-sdl2 --enable-vulkan --enable-zlib --enable-libv4l2 --enable-libxcb --enable-vdpau --enable-vaapi --enable-encoder='ac3,alac,flac,libfdk_aac,g723_1,mp2,libmp3lame,libopus,libspeex,pcm_alaw,pcm_mulaw,pcm_f32le,pcm_s16be,pcm_s24be,pcm_s16le,pcm_s24le,pcm_s32le,pcm_u8,tta,libvorbis,wavpack,' --enable-encoder='ass,ffv1,libaom_av1,libvpx_vp8,libvpx_vp9,mjpeg_vaapi,rawvideo,theora,vp8_vaapi,libopenh264' --enable-decoder='adpcm_g722,alac,flac,g723_1,g729,libfdk_aac,libopus,libspeex,mp2,mp3,m4a,pcm_alaw,pcm_mulaw,pcm_f16le,pcm_f24le,pcm_f32be,pcm_f32le,pcm_f64be,pcm_f64le,pcm_s16be,pcm_s16be_planar,pcm_s24be,pcm_s16le,pcm_s16le_planar,pcm_s24le,pcm_s24le_planar,pcm_s32le,pcm_s32le_planar,pcm_s64be,pcm_s64le,pcm_s8,pcm_s8_planar,pcm_u8,pcm_u24be,pcm_u24le,pcm_u32be,pcm_u32le,tta,vorbis,wavpack,' --enable-decoder='ass,ffv1,mjpeg,mjpegb,libaom_av1,libdav1d,libvpx_vp8,libvpx_vp9,rawvideo,theora,vp8,vp9,libopenh264' --enable-encoder='bmp,gif,jpegls,png,tiff,webp,' --enable-decoder='bmp,gif,jpegls,png,tiff,webp,' --enable-hwaccel='vp8_vaapi,mjpeg_vaapi,' --enable-parser='aac,ac3,flac,mjpeg,mpegaudio,mpeg4video,opus,vp3,vp8,vp9,vorbis,' --enable-muxer='ac3,ass,flac,g722,gif,matroska,mp3,mpegvideo,rtp,ogg,opus,pcm_s16be,pcm_s16le,wav,webm,' --enable-demuxer='aac,ac3,ass,flac,g722,gif,image_jpeg_pipe,image_png_pipe,image_webp_pipe,matroska,mjpeg,mov,mp3,mpegvideo,ogg,pcm_mulaw,pcm_alaw,pcm_s16be,pcm_s16le,rtp,wav,' --enable-filter='crop,scale,overlay,amix,amerge,aresample,format,aformat,fps,transpose,pad,' --enable-indev='v4l2,xcbgrab,' --enable-protocol='crypto,file,pipe,rtp,srtp,rtsp,tcp,udp,unix,' --arch=x86_64 --enable-libopenh264
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
Unrecognized option 'movflags'.
Error splitting the argument list: Option not found

ERROR: Postprocessing: Error splitting the argument list: Option not found
Traceback (most recent call last):
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3502, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3484, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 831, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 324, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 362, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error splitting the argument list: Option not found

Traceback (most recent call last):
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3502, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3484, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 831, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 324, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 362, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error splitting the argument list: Option not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/service/videohosting_service/FacebookService.py", line 94, in <module>
    info = ydl.download('https://www.facebook.com/watch/?v=790051908909640')
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3369, in download
    self.__download_wrapper(self.extract_info)(
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3344, in wrapper
    res = func(*args, **kwargs)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2779, in process_video_result
    self.process_info(new_info)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3325, in process_info
    self.report_error('Postprocessing: %s' % str(err))
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/dendil/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 955, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Postprocessing: Error splitting the argument list: Option not found
```

**Comment by bashonly** [comment]
Seems like it could be a problem with your build of ffmpeg (the mov muxer is not enabled?)
Try one of the builds from https://github.com/yt-dlp/FFmpeg-Builds

**Comment by DanilaParakhnevich** [comment]
It doesn't seem to help. How to watch if mov muxer enabled?

**Comment by bashonly** [comment]
Can you show verbose output with the yt-dlp ffmpeg build?

**Comment by DanilaParakhnevich** [comment]
Sorry for my ignoring. https://github.com/yt-dlp/FFmpeg-Builds this thing really helped me. Thank you
