### ISSUE TITLE
How to test proxies quickly?

### ISSUE THREAD

**Issue by nadermx** [yt-dlp/yt-dlp#6970]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am trying to test some proxies with youtube, but I am a bit stuck on having it retry 0 and just let me know it failed so I can mark the IP as useless.  

I currently have this code, I tried setting retries to 0, but it keeps retrying, so I was hoping I could get some help to just have it error out on first try so  Ican try  lot of proxies quickly

```
import yt_dlp

def test_yt(ip):

    ydl = yt_dlp.YoutubeDL(
    {'outtmpl': '%(id)s%(ext)s', '-f': 140, 'proxy': ip, 'retries':'0', 'verbose':True, 'youtube_include_dash_manifest': False})
    try:
        with ydl:
            result = ydl.extract_info(
                'http://www.youtube.com/watch?v=0_o6GjolEu8',
                download=False  # We just want to extract the info
            )

        return "working"
    except:
        return ip


with open('proxies.txt', 'r') as f: #open the file
    contents = f.readlines() #put the lines to a variable (list).
    for p in contents:
        test_yt(proxy)

```
Any help would be appreciated

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
python newproxytest.py
[youtube] Extracting URL: http://www.youtube.com/watch?v=0_o6GjolEu8
[youtube] 0_o6GjolEu8: Downloading webpage
WARNING: [youtube] Unable to download webpage: Remote end closed connection without response
[youtube] 0_o6GjolEu8: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (1/3)...
[youtube] 0_o6GjolEu8: Downloading android player API JSON
WARNING: [youtube] Remote end closed connection without response. Retrying (2/3)...
[youtube] 0_o6GjolEu8: Downloading android player API JSON
WARNING: [youtube] Remote end closed connection without response. Retrying (3/3)...
[youtube] 0_o6GjolEu8: Downloading android player API JSON
[youtube] 0_o6GjolEu8: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error _ssl.c:1114: The handshake operation timed out>
[youtube] 0_o6GjolEu8: Downloading web player API JSON
WARNING: [youtube] <urlopen error _ssl.c:1114: The handshake operation timed out>. Retrying (1/3)...
[youtube] 0_o6GjolEu8: Downloading web player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (2/3)...
[youtube] 0_o6GjolEu8: Downloading web player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (3/3)...
[youtube] 0_o6GjolEu8: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: [Errno 104] Connection reset by peer (caused by ConnectionResetError(104, 'Connection reset by peer')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] 0_o6GjolEu8: Unable to download API page: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(ConnectionResetError(104, 'Connection reset by peer')))
(venv) john@johnslaptop:~/PycharmProjects/youtstream/app/proxies$ python newproxytest.py
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API
[debug] params: {'outtmpl': '%(id)s%(ext)s', '-f': 140, 'proxy': 'http://1.2.3.4:29842', 'verbose': True, 'retries': '0', 'youtube_include_dash_manifest': False, 'compat_opts': set()}
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-71-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe 4.4.3, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2021.10.08, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {'http': 'http://1.2.3.4:29842', 'https': 'http://1.2.3.4:29842'}
[debug] Loaded 1786 extractors
[youtube] Extracting URL: http://www.youtube.com/watch?v=0_o6GjolEu8
[youtube] 0_o6GjolEu8: Downloading webpage
WARNING: [youtube] Unable to download webpage: Remote end closed connection without response
[youtube] 0_o6GjolEu8: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (1/3)...
[youtube] 0_o6GjolEu8: Downloading android player API JSON
WARNING: [youtube] Remote end closed connection without response. Retrying (2/3)...
[youtube] 0_o6GjolEu8: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (3/3)...
[youtube] 0_o6GjolEu8: Downloading android player API JSON
[youtube] 0_o6GjolEu8: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: Remote end closed connection without response
[youtube] 0_o6GjolEu8: Downloading web player API JSON
WARNING: [youtube] Remote end closed connection without response. Retrying (1/3)...
[youtube] 0_o6GjolEu8: Downloading web player API JSON
WARNING: [youtube] <urlopen error _ssl.c:1114: The handshake operation timed out>. Retrying (2/3)...
[youtube] 0_o6GjolEu8: Downloading web player API JSON
WARNING: [youtube] <urlopen error timed out>. Retrying (3/3)...
[youtube] 0_o6GjolEu8: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(ConnectionResetError(104, 'Connection reset by peer')))
ERROR: [youtube] 0_o6GjolEu8: Unable to download API page: <urlopen error timed out> (caused by URLError(timeout('timed out')))
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 3915, in _real_extract
    webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 3883, in _download_player_responses
    player_responses, player_url = self._extract_player_responses(
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 3610, in _extract_player_responses
    raise last_error
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 3581, in _extract_player_responses
    pr = initial_pr if client == 'web' and initial_pr else self._extract_player_response(
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 3501, in _extract_player_response
    return self._extract_response(
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 908, in _extract_response
    for retry in self.RetryManager():
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/utils.py", line 6141, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 3728, in _error_or_warning
    RetryManager.report_retry(
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/utils.py", line 6149, in report_retry
    raise e
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 910, in _extract_response
    response = self._call_api(
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 586, in _call_api
    return self._download_json(
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1048, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1012, in download_handle
    res = self._download_webpage_handle(
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 882, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 927, in connect
    self._tunnel()
  File "/usr/lib/python3.8/http/client.py", line 901, in _tunnel
    (version, code, message) = response._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/john/PycharmProjects/youtstream/venv/lib/python3.8/site-packages/yt_dlp/utils.py", line 1555, in https_open
    return self.do_open(
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
```

**Comment by nadermx** [comment]
Hit submit and then went back to edit something, seems issue submited twice
