### ISSUE TITLE
--restrict-filenames only as fallback

### ISSUE THREAD

**Issue by rieje** [yt-dlp/yt-dlp#6972]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Sometimes channels contain majority of video files that cannot successfully be merged when parts are downloaded unless `--restrict-filenames` is used. However, `--restrict-filenames` tends to strip most of the context of the filenames so the resulting filename is very different than the actual filename and gives little context to what the video is about, so this should only be used when a video cannot be successfully downloaded/merged under normal circumstance (i.e. when `--no-restrict-filenames` is used, which is the default and preferred option).

What ends up happening is a bunch of videos get downloaded and there are a bunch of videos that cannot be merged. Then I download the list of videos again with `--restrict-filenames` so that videos that were not merged get downloaded and merged. But now the directory is littered with files that were not merged.

Feature request is that if a merge fails while downloading a video, switch to `--restrict-filenames` only for that video and if that results in a complete file downloaded, delete the parts of the file that were created but could not be merged.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output
    [debug] Command-line config: ['-vU', '--download-archive', '/home/rieje/admin/log/yt-dlp-archive.log', '--output', '/tmp/rieje/downloads/%(title)s - %(uploader)s (%(upload_date)s) %(id)s.%(ext)s', 'https://www.youtube.com/watch?v=K2xR8fGyKpM', '--exec', 'echo %(filepath)q >> /tmp/rieje/downloads/yt-dle-playlist.J5celIrGBx']
    [debug] User config "/home/rieje/.config/yt-dlp/config": ['--audio-quality', '0', '--downloader', 'aria2c', '--output', '%(title)s - %(uploader)s (%(upload_date)s) %(id)s.%(ext)s', '--no-playlist', '--embed-thumbnail', '--merge-output-format', 'mkv', '--embed-metadata', '--embed-subs', '--sub-lang', 'en,zh']
    [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8 (No ANSI), screen utf-8
    [debug] yt-dlp version stable@2023.03.04 [392389b7d]
    [debug] Python 3.10.10 (CPython x86_64 64bit) - Linux-6.2.13-arch1-1-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
    [debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
    [debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
    [debug] Proxy map: {}
    [debug] Loaded 1786 extractors
    [debug] Loading archive file '/home/rieje/admin/log/yt-dlp-archive.log'
    [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
    Available version: stable@2023.03.04, Current version: stable@2023.03.04
    yt-dlp is up to date (stable@2023.03.04)
    [youtube] Extracting URL: https://www.youtube.com/watch?v=K2xR8fGyKpM
    [youtube] K2xR8fGyKpM: Downloading webpage
    [youtube] K2xR8fGyKpM: Downloading android player API JSON
    [youtube] K2xR8fGyKpM: Downloading player 0c487f05
    [debug] Saving youtube-nsig.0c487f05 to cache
    [debug] [youtube] Decrypted nsig cCcFWPIlZEk4Yc8BD => LJGSCxUG6CDjyw
    [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
    [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
    [debug] Default format spec: bestvideo*+bestaudio/best
    [info] K2xR8fGyKpM: Downloading 1 format(s): 248+251
    [info] There's no subtitles for the requested languages
    [info] Downloading video thumbnail 41 ...
    [info] Writing video thumbnail 41 to: /tmp/rieje/downloads/外國老婆不好搞!？ 台灣老公來控訴 marriage 2018-06-18 【WTO姐妹會】│法國Anna+瀚元、珊珊+膺中、波蘭Anna+天銘、ZUZU+Jack、Aiko+亦棠、Sumi+Ken - WTO姐妹會 官方頻道 (20200714) K2xR8fGyKpM.webp
    [debug] Invoking dashsegments downloader on "https://rr2---sn-gjo-2iaz.googlevideo.com/videoplayback?expire=1683068062&ei=PkBRZNqKJOuI_9EPjsSnyA4&ip=65.78.100.184&id=o-ACP88F-elPidi6SuXks31rb7kjXdWvp2HEFjuRs1NrHf&itag=248&source=youtube&requiressl=yes&mh=pT&mm=31%2C29&mn=sn-gjo-2iaz%2Csn-p5qlsnrl&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=1617500&spc=qEK7B1pq1XQQd1exHRxXGrTsO_NSZ6s&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=857156827&dur=2650.180&lmt=1595050742669699&mt=1683046150&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=5535332&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgHSr-vbwnNtgCRtnujN6Ohi6Ajt87u1n8v8ODSToMfy0CIGaYlVuIQqVyMi7QfmuGfjltd6cIC9NcYDoVGcQihh-a&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgM0yjVxlpmFHRCxTZkDT5t061lyb7i1xwKrHhZRRSy6gCIGTdBdchGx1cj8KPNMKXJIel_ufND_2xKFIxxzw5cZ-f"
    [dashsegments] Total fragments: 82
    [download] Destination: /tmp/rieje/downloads/外國老婆不好搞!？ 台灣老公來控訴 marriage 2018-06-18 【WTO姐妹會】│法國Anna+瀚元、珊珊+膺中、波蘭Anna+天銘、ZUZU+Jack、Aiko+亦棠、Sumi+Ken - WTO姐妹會 官方頻道 (20200714) K2xR8fGyKpM.f248.webm
    ERROR: unable to open for writing: [Errno 36] File name too long: '/tmp/rieje/downloads/外國老婆不好搞!？ 台灣老公來控訴 marriage 2018-06-18 【WTO姐妹會】│法國Anna+瀚元、珊珊+膺中、波蘭Anna+天銘、ZUZU+Jack、Aiko+亦棠、Sumi+Ken - WTO姐妹會 官方頻道 (20200714) K2xR8fGyKpM.f248.webm.part-Frag1.part'
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 662, in sanitize_open
        stream = locked_file(filename, open_mode, block=False).__enter__()
      File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2221, in __init__
        self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
    OSError: [Errno 36] File name too long: '/tmp/rieje/downloads/外國老婆不好搞!？ 台灣老公來控訴 marriage 2018-06-18 【WTO姐妹會】│法國Anna+瀚元、珊珊+膺中、波蘭Anna+天銘、ZUZU+Jack、Aiko+亦棠、Sumi+Ken - WTO姐妹會 官方頻道 (20200714) K2xR8fGyKpM.f248.webm.part-Frag1.part'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 272, in download
        ctx.stream, ctx.tmpfilename = self.sanitize_open(
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 235, in wrapper
        retry.error_callback(err, 1, 0)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 221, in error_callback
        return RetryManager.report_retry(
      File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 6149, in report_retry
        raise e
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 230, in wrapper
        return func(self, *args, **kwargs)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 241, in sanitize_open
        f, filename = sanitize_open(filename, open_mode)
      File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 664, in sanitize_open
        stream = open(filename, open_mode)
    OSError: [Errno 36] File name too long: '/tmp/rieje/downloads/外國老婆不好搞!？ 台灣老公來控訴 marriage 2018-06-18 【WTO姐妹會】│法國Anna+瀚元、珊珊+膺中、波蘭Anna+天銘、ZUZU+Jack、Aiko+亦棠、Sumi+Ken - WTO姐妹會 官方頻道 (20200714) K2xR8fGyKpM.f248.webm.part-Frag1.part'

    ERROR: fragment 1 not found, unable to continue
      File "/usr/bin/yt-dlp", line 8, in <module>
        sys.exit(main())
      File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 967, in main
        _exit(*variadic(_real_main(argv)))
      File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 957, in _real_main
        return ydl.download(all_urls)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3369, in download
        self.__download_wrapper(self.extract_info)(
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3344, in wrapper
        res = func(*args, **kwargs)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1507, in extract_info
        return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
        return func(self, *args, **kwargs)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
        return self.process_ie_result(ie_result, download, extra_info)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
        ie_result = self.process_video_result(ie_result, download=download)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2779, in process_video_result
        self.process_info(new_info)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3229, in process_info
        partial_success, real_download = self.dl(fname, new_info)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2970, in dl
        return fd.download(name, new_info, subtitle)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 444, in download
        ret = self.real_download(filename, info_dict)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/dash.py", line 60, in real_download
        return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 382, in download_and_append_fragments_multiple
        return self.download_and_append_fragments(*args[0], **kwargs)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 522, in download_and_append_fragments
        result = append_fragment(
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 486, in append_fragment
        self.report_error(f'fragment {frag_index} not found, unable to continue')
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1015, in report_error
        self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 944, in trouble
        tb_data = traceback.format_list(traceback.extract_stack())

    [debug] Invoking dashsegments downloader on "https://rr2---sn-gjo-2iaz.googlevideo.com/videoplayback?expire=1683068062&ei=PkBRZNqKJOuI_9EPjsSnyA4&ip=65.78.100.184&id=o-ACP88F-elPidi6SuXks31rb7kjXdWvp2HEFjuRs1NrHf&itag=251&source=youtube&requiressl=yes&mh=pT&mm=31%2C29&mn=sn-gjo-2iaz%2Csn-p5qlsnrl&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=1617500&spc=qEK7B1pq1XQQd1exHRxXGrTsO_NSZ6s&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=33849128&dur=2650.201&lmt=1594759219861823&mt=1683046150&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIPOXYQ6Gophn0UumlGfb-1tgrZTcwYJHKNozMhuRLy6AiBfvQHveJ1Bg-jEJRWsXKIr56CKmPdQq2KfLOA0FSDGaQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgM0yjVxlpmFHRCxTZkDT5t061lyb7i1xwKrHhZRRSy6gCIGTdBdchGx1cj8KPNMKXJIel_ufND_2xKFIxxzw5cZ-f"
    [dashsegments] Total fragments: 4
    [download] Destination: /tmp/rieje/downloads/外國老婆不好搞!？ 台灣老公來控訴 marriage 2018-06-18 【WTO姐妹會】│法國Anna+瀚元、珊珊+膺中、波蘭Anna+天銘、ZUZU+Jack、Aiko+亦棠、Sumi+Ken - WTO姐妹會 官方頻道 (20200714) K2xR8fGyKpM.f251.webm
    ERROR: unable to open for writing: [Errno 36] File name too long: '/tmp/rieje/downloads/外國老婆不好搞!？ 台灣老公來控訴 marriage 2018-06-18 【WTO姐妹會】│法國Anna+瀚元、珊珊+膺中、波蘭Anna+天銘、ZUZU+Jack、Aiko+亦棠、Sumi+Ken - WTO姐妹會 官方頻道 (20200714) K2xR8fGyKpM.f251.webm.part-Frag1.part'
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 662, in sanitize_open
        stream = locked_file(filename, open_mode, block=False).__enter__()
      File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2221, in __init__
        self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
    OSError: [Errno 36] File name too long: '/tmp/rieje/downloads/外國老婆不好搞!？ 台灣老公來控訴 marriage 2018-06-18 【WTO姐妹會】│法國Anna+瀚元、珊珊+膺中、波蘭Anna+天銘、ZUZU+Jack、Aiko+亦棠、Sumi+Ken - WTO姐妹會 官方頻道 (20200714) K2xR8fGyKpM.f251.webm.part-Frag1.part'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 272, in download
        ctx.stream, ctx.tmpfilename = self.sanitize_open(
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 235, in wrapper
        retry.error_callback(err, 1, 0)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 221, in error_callback
        return RetryManager.report_retry(
      File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 6149, in report_retry
        raise e
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 230, in wrapper
        return func(self, *args, **kwargs)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 241, in sanitize_open
        f, filename = sanitize_open(filename, open_mode)
      File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 664, in sanitize_open
        stream = open(filename, open_mode)
    OSError: [Errno 36] File name too long: '/tmp/rieje/downloads/外國老婆不好搞!？ 台灣老公來控訴 marriage 2018-06-18 【WTO姐妹會】│法國Anna+瀚元、珊珊+膺中、波蘭Anna+天銘、ZUZU+Jack、Aiko+亦棠、Sumi+Ken - WTO姐妹會 官方頻道 (20200714) K2xR8fGyKpM.f251.webm.part-Frag1.part'

    ERROR: fragment 1 not found, unable to continue
      File "/usr/bin/yt-dlp", line 8, in <module>
        sys.exit(main())
      File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 967, in main
        _exit(*variadic(_real_main(argv)))
      File "/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 957, in _real_main
        return ydl.download(all_urls)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3369, in download
        self.__download_wrapper(self.extract_info)(
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3344, in wrapper
        res = func(*args, **kwargs)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1507, in extract_info
        return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
        return func(self, *args, **kwargs)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
        return self.process_ie_result(ie_result, download, extra_info)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
        ie_result = self.process_video_result(ie_result, download=download)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2779, in process_video_result
        self.process_info(new_info)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3229, in process_info
        partial_success, real_download = self.dl(fname, new_info)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2970, in dl
        return fd.download(name, new_info, subtitle)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 444, in download
        ret = self.real_download(filename, info_dict)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/dash.py", line 60, in real_download
        return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 382, in download_and_append_fragments_multiple
        return self.download_and_append_fragments(*args[0], **kwargs)
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 522, in download_and_append_fragments
        result = append_fragment(
      File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 486, in append_fragment
        self.report_error(f'fragment {frag_index} not found, unable to continue')
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1015, in report_error
        self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
      File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 944, in trouble
        tb_data = traceback.format_list(traceback.extract_stack())

**Comment by rieje** [comment]
@pukkandan Updated with log.

**Comment by bashonly** [comment]
> OSError: [Errno 36] File name too long:

`--restrict-filenames` wouldn't necessarily help with this. What you need is to use an output template that will adhere to your OS' filename limit, e.g.
` --output "/tmp/rieje/downloads/%(title).150B - %(uploader)s (%(upload_date)s) %(id)s.%(ext)s'"`

**Comment by pukkandan** [comment]
as you would have found if you looked at pinned issuses.
