### ISSUE TITLE
[kakao] Other videos on the website can be downloaded, but some videos cannot be downloaded

### ISSUE THREAD

**Issue by shimiaoyerin** [yt-dlp/yt-dlp#699]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\GFriend>yt-dlp https://tv.kakao.com/channel/3808811/cliplink/421325127?act=clip -v
[debug] Command-line config: ['https://tv.kakao.com/channel/3808811/cliplink/421325127?act=clip', '-v']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.8.3 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {'https': 'http://127.0.0.1:10081', 'http': 'http://127.0.0.1:10081'}
[debug] [Kakao] Extracting URL: https://tv.kakao.com/channel/3808811/cliplink/421325127?act=clip
[Kakao] 421325127: Downloading video info
[Kakao] 421325127: Downloading video URL for profile LOW
[Kakao] 421325127: Downloading video URL for profile BASE
[Kakao] 421325127: Downloading video URL for profile MAIN
[Kakao] 421325127: Downloading video URL for profile HIGH
[Kakao] 421325127: Downloading video URL for profile HIGH4
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "c:\users\gfriend\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\gfriend\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 1224, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\gfriend\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\extractor\common.py", line 575, in extract
    ie_result = self._real_extract(url)
  File "c:\users\gfriend\appdata\local\programs\python\python38-32\lib\site-packages\yt_dlp\extractor\kakao.py", line 109, in _real_extract
    for thumb in clip.get('clipChapterThumbnailList', []):
TypeError: 'NoneType' object is not iterable

```

## Description

WRITE DESCRIPTION HERE

**Comment by coletdjnz** [comment]
Note for devs: seems to be Geo-restricted to South Korea
