### ISSUE TITLE
Unable to download Abema TV videos properly

### ISSUE THREAD

**Issue by 00corgs** [yt-dlp/yt-dlp#6993]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

I am using the latest yt-dlp installed with the pip3 command, but I cannot get the title of the video correct, and also I get an error and cannot download it.
```
$ yt-dlp -vU https://abema.tv/video/episode/25-239_s1_p5
[debug] Command-line config: ['-vU', 'https://abema.tv/video/episode/25-239_s1_p5']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)

~~~( omitted)~~~

[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:AbemaTV video #25-239_s1_p5 [25-239_s1_p5].mp4'
ERROR: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2779, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3502, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3484, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 894, in run
    if all(self._needs_fixup(info)):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 885, in _needs_fixup
    metadata = self.get_metadata_object(info['filepath'])
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 296, in get_metadata_object
    return json.loads(stdout)
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)

$


### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://abema.tv/video/episode/25-239_s1_p5']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.9.14 (CPython aarch64 64bit) - Linux-5.14.0-162.23.1.el9_1.aarch64-aarch64-with-glibc2.34 (OpenSSL 3.0.1 14 Dec 2021, glibc 2.34)
[debug] exe versions: ffmpeg 5.1.3 (fdk,setts), ffprobe 5.1.3
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[AbemaTV] Extracting URL: https://abema.tv/video/episode/25-239_s1_p5
[AbemaTV] Authorizing
[AbemaTV] 25-239_s1_p5: Downloading webpage
[AbemaTV] 25-239_s1_p5: Checking playability
[AbemaTV] 25-239_s1_p5: Downloading m3u8 information
WARNING: Extractor failed to obtain "title". Creating a generic title instead
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 25-239_s1_p5: Downloading 1 format(s): 5300
[debug] Invoking hlsnative downloader on "https://vod-abematv.akamaized.net/program/25-239_s1_p5/1080/playlist.m3u8?aver=1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 245
[download] Destination: AbemaTV video #25-239_s1_p5 [25-239_s1_p5].mp4
[download]   0.4% of ~  26.49MiB at    1.71MiB/s ETA 00:15 (frag 1/245)[AbemaTV] Fetching media token
[AbemaTV] Requesting playback license
[download] 100% of  381.01MiB in 00:01:35 at 3.99MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:AbemaTV video #25-239_s1_p5 [25-239_s1_p5].mp4'
ERROR: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2779, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3502, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3484, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 894, in run
    if all(self._needs_fixup(info)):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 885, in _needs_fixup
    metadata = self.get_metadata_object(info['filepath'])
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 296, in get_metadata_object
    return json.loads(stdout)
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

**Comment by Lesmiscore** [comment]
Can you please post the output of `ffprobe -hide_banner -show_format -show_streams -print_format json 'file:AbemaTV video #25-239_s1_p5 [25-239_s1_p5].mp4'`?

<hr>

Also send me page dumps privately to fix an another bug if you don't care
Run yt-dlp with `--write-page` and send the created .dump files
You can either do that via email ( nao20010128@gmail.com ), or via Discord ([join yt-dlp's server](https://discord.gg/H5MNcFW63r) and ping `Lesmiscꙮre` before opening DMs)

**Comment by 00corgs** [comment]
Ok.
Could it be a problem with ffmpeg?
It was downloaded from the epel repository.
```
$ ffprobe -hide_banner -show_format -show_streams -print_format json 'file:AbemaTV video #25-239_s1_p5 [25-239_s1_p5].mp4'
{
[libopenh264 @ 0xaaaae8d23440] libopenh264.so.7: cannot open shared object file: No such file or directory: libopenh264.so.7 is missing, openh264 support will be disabled
[mpegts @ 0xaaaae8ceb0c0] Failed to open codec in avformat_find_stream_info
[libopenh264 @ 0xaaaae8d23440] libopenh264.so.7: cannot open shared object file: No such file or directory: libopenh264.so.7 is missing, openh264 support will be disabled
[mpegts @ 0xaaaae8ceb0c0] Could not find codec parameters for stream 0 (Video: h264 (Main) ([27][0][0][0] / 0x001B), none(progressive)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mpegts, from 'file:AbemaTV video #25-239_s1_p5 [25-239_s1_p5].mp4':
  Duration: 00:23:40.11, start: 1.443511, bitrate: 2250 kb/s
  Program 1 
  Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), none(progressive), 29.97 fps, 29.97 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 125 kb/s
  Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
[libopenh264 @ 0xaaaae8f24a60] libopenh264.so.7: cannot open shared object file: No such file or directory: libopenh264.so.7 is missing, openh264 support will be disabled
Could not open codec for input stream 0

```
And I will email you the DUMP file now.

**Comment by 00corgs** [comment]
When I download ffmpeg from another repository (RPMFusion), I am able to download videos successfully.
Thank you very much!
```
$ yt-dlp -vU https://abema.tv/video/episode/25-239_s1_p5
[debug] Command-line config: ['-vU', 'https://abema.tv/video/episode/25-239_s1_p5']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.9.14 (CPython aarch64 64bit) - Linux-5.14.0-162.23.1.el9_1.aarch64-aarch64-with-glibc2.34 (OpenSSL 3.0.1 14 Dec 2021, glibc 2.34)
[debug] exe versions: ffmpeg 5.1.3 (setts), ffprobe 5.1.3
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[AbemaTV] Extracting URL: https://abema.tv/video/episode/25-239_s1_p5
[AbemaTV] Authorizing
[AbemaTV] 25-239_s1_p5: Downloading webpage
[AbemaTV] 25-239_s1_p5: Checking playability
[AbemaTV] 25-239_s1_p5: Downloading m3u8 information
WARNING: Extractor failed to obtain "title". Creating a generic title instead
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 25-239_s1_p5: Downloading 1 format(s): 5300
[debug] Invoking hlsnative downloader on "https://vod-abematv.akamaized.net/program/25-239_s1_p5/1080/playlist.m3u8?aver=1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 245
[download] Destination: AbemaTV video #25-239_s1_p5 [25-239_s1_p5].mp4
[download]   0.4% of ~  26.49MiB at    1.66MiB/s ETA 00:15 (frag 1/245)[AbemaTV] Fetching media token
[AbemaTV] Requesting playback license
[download] 100% of  381.01MiB in 00:02:04 at 3.07MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:AbemaTV video #25-239_s1_p5 [25-239_s1_p5].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "AbemaTV video #25-239_s1_p5 [25-239_s1_p5].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:AbemaTV video #25-239_s1_p5 [25-239_s1_p5].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:AbemaTV video #25-239_s1_p5 [25-239_s1_p5].temp.mp4'
$
```
