### ISSUE TITLE
[CNN] Missing "id" field in extractor result

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6996]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

download from CNN with `--no-config` works:

<details>
<summary>log</summary>

```
yt-dlp https://edition.cnn.com/videos/tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn --no-config -v -f-
[debug] Command-line config: ['https://edition.cnn.com/videos/tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn', '--no-config', '-v', '-f-']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.03.204705 [2f07c4c1d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[CNN] Extracting URL: https://edition.cnn.com/videos/tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn
[CNN] manas-bhatia-ai-nature-designs-tnf-spc-intl: Downloading XML
[CNN] tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn: Downloading m3u8 information
[CNN] tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn: Downloading m3u8 information
[CNN] tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn: Downloading m3u8 information
[CNN] tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn:
ID                  EXT RESOLUTION │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
────────────────────────────────────────────────────────────────────────────────────────────
connectedTV-389     mp4 416x234    │ ~ 2.47MiB  389k m3u8  │ avc1.4D400D  389k mp4a.40.2  0k
hls_1080p-389       mp4 416x234    │ ~ 2.47MiB  389k m3u8  │ avc1.4D400D  389k mp4a.40.2  0k
iOSHLSFallback-389  mp4 416x234    │ ~ 2.47MiB  389k m3u8  │ avc1.4D400D  389k mp4a.40.2  0k
iOS_iPad-389        mp4 416x234    │ ~ 2.47MiB  389k m3u8  │ avc1.4D400D  389k mp4a.40.2  0k
connectedTV-693     mp4 416x234    │ ~ 4.40MiB  694k m3u8  │ avc1.4D400D  694k mp4a.40.2  0k
hls_1080p-693       mp4 416x234    │ ~ 4.40MiB  694k m3u8  │ avc1.4D400D  694k mp4a.40.2  0k
iOSHLSFallback-693  mp4 416x234    │ ~ 4.40MiB  694k m3u8  │ avc1.4D400D  694k mp4a.40.2  0k
iOS_iPad-693        mp4 416x234    │ ~ 4.40MiB  694k m3u8  │ avc1.4D400D  694k mp4a.40.2  0k
connectedTV-1202    mp4 640x360    │ ~ 7.64MiB 1203k m3u8  │ avc1.4D401E 1203k mp4a.40.2  0k
hls_1080p-1202      mp4 640x360    │ ~ 7.64MiB 1203k m3u8  │ avc1.4D401E 1203k mp4a.40.2  0k
iOSHLSFallback-1202 mp4 640x360    │ ~ 7.64MiB 1203k m3u8  │ avc1.4D401E 1203k mp4a.40.2  0k
iOS_iPad-1202       mp4 640x360    │ ~ 7.64MiB 1203k m3u8  │ avc1.4D401E 1203k mp4a.40.2  0k
connectedTV-2016    mp4 768x432    │ ~12.80MiB 2017k m3u8  │ avc1.4D401F 2017k mp4a.40.2  0k
hls_1080p-2016      mp4 768x432    │ ~12.80MiB 2017k m3u8  │ avc1.4D401F 2017k mp4a.40.2  0k
iOSHLSFallback-2016 mp4 768x432    │ ~12.80MiB 2017k m3u8  │ avc1.4D401F 2017k mp4a.40.2  0k
iOS_iPad-2016       mp4 768x432    │ ~12.80MiB 2017k m3u8  │ avc1.4D401F 2017k mp4a.40.2  0k
connectedTV-2730    mp4 960x540    │ ~17.33MiB 2731k m3u8  │ avc1.4D401F 2731k mp4a.40.2  0k
hls_1080p-2730      mp4 960x540    │ ~17.33MiB 2731k m3u8  │ avc1.4D401F 2731k mp4a.40.2  0k
iOSHLSFallback-2730 mp4 960x540    │ ~17.33MiB 2731k m3u8  │ avc1.4D401F 2731k mp4a.40.2  0k
iOS_iPad-2730       mp4 960x540    │ ~17.33MiB 2731k m3u8  │ avc1.4D401F 2731k mp4a.40.2  0k
connectedTV-5277    mp4 1280x720   │ ~33.50MiB 5277k m3u8  │ avc1.4D401F 5277k mp4a.40.2  0k
hls_1080p-5277      mp4 1280x720   │ ~33.50MiB 5277k m3u8  │ avc1.4D401F 5277k mp4a.40.2  0k
iOSHLSFallback-5277 mp4 1280x720   │ ~33.50MiB 5277k m3u8  │ avc1.4D401F 5277k mp4a.40.2  0k
iOS_iPad-5277       mp4 1280x720   │ ~33.50MiB 5277k m3u8  │ avc1.4D401F 5277k mp4a.40.2  0k
ios_150             mp4 1920x1080  │ ~50.78MiB 8000k https │ unknown     8000k unknown    0k
connectedTV-8332    mp4 1920x1080  │ ~52.89MiB 8332k m3u8  │ avc1.640028 8332k mp4a.40.2  0k
hls_1080p-8332      mp4 1920x1080  │ ~52.89MiB 8332k m3u8  │ avc1.640028 8332k mp4a.40.2  0k
iOSHLSFallback-8332 mp4 1920x1080  │ ~52.89MiB 8332k m3u8  │ avc1.640028 8332k mp4a.40.2  0k
iOS_iPad-8332       mp4 1920x1080  │ ~52.89MiB 8332k m3u8  │ avc1.640028 8332k mp4a.40.2  0k

Enter format selector:

``` 

</details>

But apparently there are some config settings which make the extractor fail with

> WARNING: [CNN] Unable to download XML: <urlopen error timed out>
> ERROR: [CNN] Missing "id" field in extractor result; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q=

<details open>
<summary>log</summary>

```
yt-dlp https://edition.cnn.com/videos/tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn
[debug] Command-line config: ['https://edition.cnn.com/videos/tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn']
[debug] Portable config "c:\hp\-\!portable\yt-dlp\yt-dlp.conf": ['--verbose', '--downloader-args', 'ffmpeg:-v 8 -stats -allowed_extensions ALL', '--no-playlist', '--format-sort', 'hasvid,ie_pref,quality,res,hdr,codec,size,br,asr,ext,fps,hasaud,lang,source,proto,id', '-F', '-f', 'bestvideo*+bestaudio/best', '-f-', '--paths', 'c:\\hp\\-\\#YT', '--ffmpeg-location', '.\\helpertools\\FFmpeg\\bin', '--no-simulate', '--no-quiet', '--progress', '--write-info-json', '--write-description', '--write-annotations', '--write-playlist-metafiles', '--get-comments', '--write-link', '--write-url-link', '--write-desktop-link', '--no-overwrites', '--no-post-overwrites', '--merge-output-format', 'mkv', '--remux-video', 'mkv', '--list-subs', '--write-subs', '--write-auto-subs', '--all-subs', '--sub-format', 'all/ttml/vtt/best', '--sub-langs', 'all', '--extractor-args', 'youtube:skip=translated_subs', '--write-thumbnail', '--write-all-thumbnails', '--embed-metadata', '--embed-chapters', '--no-embed-info-json', '--no-check-certificate', '--retries', 'inf', '--file-access-retries', 'inf', '--fragment-retries', 'inf', '--no-skip-unavailable-fragments', '--retry-sleep', 'exp=1', '--retry-sleep', 'http,fragment,file_access,extractor:exp=1', '--geo-bypass', '--geo-verification-proxy', '89.58.39.225', '--audio-multistreams', '--print', 'pre_process:\r\n========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage 1: pre_process =================================================================\r\n', '--print', 'after_filter:\r\n========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage 2: after_filter ================================================================\r\n', '--print', 'video:\r\n========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage 3: video =======================================================================\r\n', '--print', 'before_dl:\r\n========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage 4: before_dl ===================================================================\r\n', '--print', 'post_process:\r\n========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage 5: post_process ================================================================\r\n', '--print', 'after_move:\r\n========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage 6: after_move ==================================================================\r\n', '--print', 'after_video:\r\n========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage 7: after_video =================================================================\r\n', '--print', 'playlist:\r\n========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage 8: playlist ====================================================================\r\n', '--output-na-placeholder', '~~', '--parse-metadata', '%(is_live)s:(?P<islive>True)', '--parse-metadata', '%(was_live)s:(?P<waslive>True)', '--alias', 'print-custom-file', '--print-to-file {} ".\\%(playlist_title,playlist|).100B%(playlist_title.101,playlist.101&…|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_timestamp>%Y-%m-%d,release_date>%Y-%m-%d,modified_date>%Y-%m-%d,modified_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,upload_timestamp>%Y-%m-%d,timestamp>%Y-%m-%d,release_year|#nodate#)s %(alt_title,title).80B%(alt_title.81B,title.81B&…|)s\\\\"{}', '--alias', 'set-output', '-o {}".\\%(playlist_title,playlist|).100B%(playlist_title.101,playlist.101&…|)s\\%(playlist_index|)02d%(playlist_index& = |)s%(release_timestamp>%Y-%m-%d,release_date>%Y-%m-%d,modified_date>%Y-%m-%d,modified_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,upload_timestamp>%Y-%m-%d,timestamp>%Y-%m-%d,release_year|#nodate#)s %(alt_title,title).80B%(alt_title.81B,title.81B&…|)s\\\\"{}', '--alias', 'set-pl_output', '-o {}".\\%(playlist_title,playlist|).100B%(playlist_title.101,playlist.101&…|)s\\\\"{}', '--set-output', '', '%(title).120B%(title.121B&…|)s [%(extractor)s.%(islive&live.|)s%(id).50B%(id.51&…|)s] {%(format_id).80B%(format_id.81&…|)s}.%(ext)s', '--set-output', 'subtitle:', 'subs\\%(title).120B%(title.121B&…|)s [%(extractor)s.%(islive&live.|)s%(id).50B%(id.51&…|)s] {%(format_id).80B%(format_id.81&…|)s}.%(ext)s', '--set-output', 'infojson:', 'tech\\metadata.%(ext)s', '--set-output', 'link:', 'tech\\link.%(ext)s', '--set-output', 'description:', '!nfo\\synopsis.%(ext)s', '--set-output', 'annotation:', '!nfo\\annotations.%(ext)s', '--set-output', 'thumbnail:', 'thumbs\\thumb.%(ext)s', '--set-pl_output', 'pl_infojson:', 'playlist metadata.%(ext)s', '--set-pl_output', 'pl_description:', 'playlist description.%(ext)s', '--set-pl_output', 'pl_thumbnail:', 'folder.%(ext)s', '--set-pl_output', 'pl_video:', '%(playlist_title,playlist|).120B%(playlist_title.121,playlist.121&…|)s [%(extractor)s.%(islive&live.|)s%(id).50B%(id.51&…)s] {%(format_id)s}.%(ext)s', '--print-custom-file', 'after_video:%(comments|)j', '!nfo\\%(comment_count|[aborted])s comments.json', '--print-custom-file', '%(chapters|)#j', '!nfo\\chapters.json', '--print-custom-file', '%(requested_formats)#j', 'tech\\AV info.json', '--parse-metadata', 'video::(?P<comments>)', '--parse-metadata', 'video::(?P<formats>)', '--parse-metadata', 'video::(?P<thumbnails>)', '--parse-metadata', 'before_dl:filename:(?P<download_dir>.*\\\\)', '--parse-metadata', 'before_dl:filename:(?P<download_dir_headless>(?<=c:\\\\hp\\\\-\\\\#YT\\\\).*\\\\)', '--exec', 'pre_process:IF EXIST %(download_dir)q CD %(download_dir)q && IF EXIST !nfo ren !nfo !nfo.old & IF EXIST tech ren tech tech.old', '--exec', 'after_move:.\\helpertools\\FFmpeg\\bin\\ffprobe -hide_banner -show_streams -show_format %(filepath)q -of json=c=0 -o "%(download_dir)s\\tech\\FFprobe results.json"', '--exec', 'after_move:echo. & ..\\curl\\bin\\curl.exe --insecure "%(webpage_url,original_url)s" -o "%(download_dir)s\\!nfo\\home.html"', '--print-custom-file', '%(playlist&--------------- PLAYLIST -------------------------------|)s%(playlist&\r\nplaylist_title:       |)s%(playlist_title|)s%(playlist&\r\nplaylist:             |)s%(playlist|)s%(playlist&\r\nplaylist_id:          |)s%(playlist_id|)s%(playlist&\r\nplaylist uploader:    |)s%(playlist_uploader|)s%(playlist&\r\nplaylist uploader id: |)s%(playlist_uploader_id|)s%(playlist&\r\nplaylist index:       |)s%(playlist_index&{} / |)s%(playlist_count|)s%(playlist&\r\nplaylist autonumber:  |)s%(playlist_autonumber&{} / |)s%(n_entries|)s%(playlist&\r\n---------------------------------------------------------\r\n|)sfilename:               %(filename|)s\r\n---------------- TITLE ----------------------------------\r\ntitle:                  %(title|)s\r\nfulltitle:              %(fulltitle|)s\r\nalt title:              %(alt_title|)s\r\ncategories:             %(categories|)l\r\ntags:                   %(tags|)l\r\n---------------- WWW ------------------------------------\r\nid:                     %(id|)s\r\ndisplay id:             %(display_id|)s\r\noriginal url:           %(original_url|)s\r\nwebpage url:            %(webpage_url|)s\r\nprotocol:               %(protocol|)s\r\nextractor:              %(extractor|)s\r\nextractor key:          %(extractor_key|)s\r\n---------------- TIME ----------------------------------\r\nlocation:               %(location|)s\r\nlive status:            %(live_status|)s (islive:%(islive&yes|no)s, waslive:%(waslive&yes|no)s)\r\nreleased:               %(release_timestamp>%Y-%m-%d %H:%M,release_date>%Y-%m-%d,release_year|)s\r\nlast modified:          %(modified_timestamp>%Y-%m-%d %H:%M,modified_date>%Y-%m-%d|)s\r\nuploaded:               %(upload_timestamp>%Y-%m-%d %H:%M,upload_date>%Y-%m-%d|)s\r\nbecame available:       %(timestamp>%Y-%m-%d %H:%M|)s\r\ndownload start:         %(epoch>%Y-%m-%d %H:%M:%S)s UTC\r\n   runtime:             %(duration>%H:%M:%S,duration_string|)19s\r\nstart time:             %(start_time>%H:%M:%S|)19s\r\n  end time:             %(end_time>%H:%M:%S|)19s\r\n---------------- A/V -----------------------------------\r\nformat id:              %(format_id|)s\r\nformat:                 %(format|)s\r\nformat note:            %(format_note|)s\r\nhas DRM:                %(has_drm,_has_drm|-)s / %(requested_formats.0.has_drm|)s / %(requested_formats.1.has_drm|)s\r\naudio bitrate:          %(abr|)4d KBit/s\r\nvideo bitrate:          %(vbr|)4d KBit/s\r\na/v bitrate:            %(tbr|)4d KBit/s\r\nfilesize:               %(filesize&{:,} bytes|)s%(filesize_approx&~{:,} bytes|)s\r\next:                    %(ext|)s%(container& / {}|)s\r\n--------------- VIDEO ----------------------------------\r\nvcodec:                 %(vcodec|)s\r\nresolution:             %(width|)s*%(height|)s\r\naspect ratio:           %(aspect_ratio|)s\r\nstretched ratio:        %(stretched_ratio|)s\r\nframe rate:             %(fps|)s fps\r\ndynamic range:          %(dynamic_range|)s\r\n--------------- AUDIO ----------------------------------\r\nacodec:                 %(acodec|)s\r\nasr:                    %(asr|)s Hz\r\naudio channels:         %(audio_channels|)s\r\nlanguage:               %(language&{} |)s%(requested_formats.0.language&{} |)s%(requested_formats.1.language&{} |)s%(requested_formats.2.language&{} |)s%(requested_formats.3.language&{} |)s%(requested_formats.4.language&{} |)s%(requested_formats.5.language&{} |)s\r\n-------------- web 2.0 ---------------------------------\r\naverage rating:         %(average_rating|)s\r\nage limit:              %(age_limit|)s\r\nviewcount:              %(view_count&{} views|)16s\r\nconcurrent views:       %(concurrent_view_count&{} views|)16s\r\nlikes:                  %(like_count&{} likes|)16s%(dislike_count& / {} dislikes|)s\r\nreposts:                %(repost_count&{} reposts|)18s\r\ncomments:               %(comment_count&{} comments|)19s\r\n-------------- source ----------------------------------\r\ncreator:                %(creator|)s\r\nuploader:               %(uploader|)s\r\nuploader id:            %(uploader_id|)s\r\nchannel:                %(channel|)s\r\nchannel id:             %(channel_id|)s\r\nchannel followers:      %(channel_follower_count&{} followers|)s\r\navailability:           %(availability|)s\r\nlicense:                %(license|)s\r\nURLs:\r\n%(urls,url|)s', 'tech\\factsheet.nfo']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.03.204705 [2f07c4c1d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110185-gb564ad8eac-20230407 (setts), ffprobe N-110185-gb564ad8eac-20230407
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[CNN] Extracting URL: https://edition.cnn.com/videos/tv/2022/12/08/manas-bhatia-ai-nature-designs-tnf-spc-intl.cnn
[CNN] manas-bhatia-ai-nature-designs-tnf-spc-intl: Downloading XML
WARNING: [CNN] Unable to download XML: <urlopen error timed out>
ERROR: [CNN] Missing "id" field in extractor result; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1532, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1629, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1688, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2507, in process_video_result
yt_dlp.utils.ExtractorError: [CNN] Missing "id" field in extractor result; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
``` 

</details>

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
see above
```

**Comment by bashonly** [comment]
>  it's likely your `--geo-verification-proxy` is not working

either that, or the culprit is probably the other network-related option, `--no-check-certificate`

**Comment by bashonly** [comment]
> Strange though that no other downloads errored out while using this proxy.

Not every extractor makes use of `--geo-verification-proxy` (not very many at all, really). CNN does because it is subclassed from `AdobePassIE`, which redefines the `_download_webpage_handle` method to always include geo verification headers
