### ISSUE TITLE
filter "-f "best[fps<=45]+best" filter fails to join downloaded pieces

### ISSUE THREAD

**Issue by TheKorn2** [yt-dlp/yt-dlp#7007]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

If I use yt-dlp without a fps filter all videos will download A-OK. If I add the filter (-f "best[fps<=45]+best"), yt-dlp will download the pieces but fail to join them together in the end. This affects every video I've tried.

Test command that works:  yt-dlp -vU http://www.youtube.com/watch?v=7mqkTFq7Ekg

Test command that fails:  yt-dlp -vU -f "best[fps<=45]+best" http://www.youtube.com/watch?v=7mqkTFq7Ekg

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
`
[debug] Command-line config: ['-vU', '-f', 'best[fps<=45]+best', 'http://www.youtube.com/watch?v=7mqkTFq7Ekg']
[debug] System config "/etc/yt-dlp.conf": ['--ignore-errors', '--write-sub', '--embed-subs', '--write-auto-subs', '--sub-format', 'vtt/srt', '--sub-langs', 'en,live_chat', '--xattr
s', '--format', 'bestvideo[width<?2561][vcodec!*=av01][ext!*=webm]+bestaudio/best[width<2561][ext!*=webm]', '--mark-watched', '--sponsorblock-mark', 'default', '--add-metadata', '-
o%(channel)s - %(title)s - %(id)s - %(resolution)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-131-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.4, xattr-0.9.6
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: http://www.youtube.com/watch?v=7mqkTFq7Ekg
[youtube] 7mqkTFq7Ekg: Downloading webpage
[youtube] 7mqkTFq7Ekg: Downloading android player API JSON
[debug] Loading youtube-nsig.50cf60f0 from cache
[debug] [youtube] Decrypted nsig hAt64GBIn4t-UKFxkx1 => 3eZDPsE3fUuqSw
[info] 7mqkTFq7Ekg: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, ae
xt, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/1160?service=YouTube&categories=%5B%22music_offtopic%22%2C+%22preview%22%2C+%22sponsor%22%2C+%22outro%22%2C+%2
2chapter%22%2C+%22intro%22%2C+%22selfpromo%22%2C+%22filler%22%2C+%22interaction%22%2C+%22poi_highlight%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[SponsorBlock] Found 1 segments in the SponsorBlock database
[info] 7mqkTFq7Ekg: Downloading 1 format(s): 22
Deleting existing file Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720.en.vtt
[info] Writing video subtitles to: Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720.en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=7mqkTFq7Ekg&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1683482369&sparams=ip%2Cipbi
ts%2Cexpire%2Cv%2Ccaps%2Copi%2Cxoaf&signature=C91E51457A40EB5F23E5E55AEE36937E576B98EA.B56DA5D4B958143D5FEC360A6BE5E1D4E13F6534&key=yt8&kind=asr&lang=en&fmt=vtt"
[download] Destination: Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720.en.vtt
[download] 100% of  596.36KiB in 00:00:00 at 4.32MiB/s
[debug] Invoking http downloader on "https://rr2---sn-vgqsknlz.googlevideo.com/videoplayback?expire=1683478770&ei=koRXZLvAE5a4igTa3I7YCg&ip=107.192.143.164&id=o-AH0gFsqNUeR6q3TmmQB
jFy-kItTUL2-hLm3bOzdjQAR2&itag=22&source=youtube&requiressl=yes&mh=ir&mm=31%2C26&mn=sn-vgqsknlz%2Csn-q4flrnl7&ms=au%2Conr&mv=m&mvi=2&pl=21&initcwndbps=1377500&spc=qEK7B4oFPqVurSJel
0H7RVZtmrYppZg&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=3903.227&lmt=1683366787052520&mt=1683456794&fvip=4&fexp=24007246&c=ANDROID&txp=4432434&sparams=expire%2Cei%
2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgQl3RBWllYO1w6Q9SfSktAXxGoMoCQc52i7P3mkGVPjYCICkyOy2OjUx4F0GXEFDefK
7AG9HFD-aYaoeoCDfmT1Ee&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgWi0o_60iIydvxr7a6uyCTdjiZSTZTcEs29GAI2KepZYCIQC9CCvFEfMd_HQqfN3oTKrm534NxHsvY9kH5E3
rpAU5mA%3D%3D"
[download] Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720 has already been downloaded
[download] 100% of  323.56MiB
[EmbedSubtitle] Subtitles can only be embedded in mp4, mov, m4a, webm, mkv, mka files
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280
x720'
[Metadata] Adding metadata to "Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720' -i 'file:Cathode Ray Dude [
CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720.meta' -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -write_id3v1 1 -metadata 'title=Voice chat in the age of mo
dems' -metadata date=20230504 -metadata 'description=I'"'"'ve been sitting on a pile of bizarre modems for years and I'"'"'m incredibly excited to show you their dumb features that
 you didn'"'"'t want then and still don'"'"'t now.

Support me on Patreon: https://www.patreon.com/cathoderaydude
Tip me: https://ko-fi.com/cathoderaydude

00:00:00 Intro (in the 90s)
00:01:23 The Problem
00:05:30 The Eventual Solution
00:09:17 VoIP (Won'"'"'t Help)
00:13:28 Introducing SVD
00:16:32 Basic modem demo
00:19:00 Voice/data switching trick
00:22:23 Voice/data switching demo
00:25:00 SVD modem 1 (VoiceView)
00:30:22 SVD modem 2 (ASVD)
00:34:44 ASVD demo
00:40:00 ASVD explanation
00:41:45 SVD modem 3 (DSVD)
00:45:55 DSVD demo
00:51:47 DSVD explanation
00:58:22 ASVD demo (advanced)
01:00:02 Why SVD failed
01:04:12 Outro' -metadata 'synopsis=I'"'"'ve been sitting on a pile of bizarre modems for years and I'"'"'m incredibly excited to show you their dumb features that you didn'"'"'t w
ant then and still don'"'"'t now.

Support me on Patreon: https://www.patreon.com/cathoderaydude
Tip me: https://ko-fi.com/cathoderaydude

00:00:00 Intro (in the 90s)
00:01:23 The Problem
00:05:30 The Eventual Solution
00:09:17 VoIP (Won'"'"'t Help)
00:13:28 Introducing SVD
00:16:32 Basic modem demo
00:19:00 Voice/data switching trick
00:22:23 Voice/data switching demo
00:25:00 SVD modem 1 (VoiceView)
00:30:22 SVD modem 2 (ASVD)
00:34:44 ASVD demo
00:40:00 ASVD explanation
00:41:45 SVD modem 3 (DSVD)
00:45:55 DSVD demo
00:51:47 DSVD explanation
00:58:22 ASVD demo (advanced)
01:00:02 Why SVD failed
01:04:12 Outro' -metadata 'purl=https://www.youtube.com/watch?v=7mqkTFq7Ekg' -metadata 'comment=https://www.youtube.com/watch?v=7mqkTFq7Ekg' -metadata 'artist=Cathode Ray Dude [CRD
]' -movflags +faststart 'file:Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720.temp'
[debug] ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl -
-disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs
2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-l
ibjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine
--enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavp
ack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl -
-enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2023-05-05T23:53:13.000000Z
  Duration: 01:05:03.18, start: 0.000000, bitrate: 695 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 563 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2023-05-05T23:53:13.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/05/2023.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 2023-05-05T23:53:13.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/05/2023.
Input #1, ffmetadata, from 'file:Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720.meta':
  Duration: 01:05:03.00, start: 0.000000, bitrate: 0 kb/s
    Chapter #1:0: start 0.000000, end 83.000000
    Metadata:
      title           : Intro (in the 90s)
    Chapter #1:1: start 83.000000, end 330.000000
    Metadata:
      title           : The Problem
    Chapter #1:2: start 330.000000, end 557.000000
    Metadata:
      title           : The Eventual Solution
    Chapter #1:3: start 557.000000, end 808.000000
    Metadata:
      title           : VoIP (Won't Help)
    Chapter #1:4: start 808.000000, end 992.000000
    Metadata:
      title           : Introducing SVD
    Chapter #1:5: start 992.000000, end 1140.000000
    Metadata:
      title           : Basic modem demo
    Chapter #1:6: start 1140.000000, end 1343.000000
    Metadata:
      title           : Voice/data switching trick
    Chapter #1:7: start 1343.000000, end 1500.000000
    Metadata:
      title           : Voice/data switching demo
    Chapter #1:8: start 1500.000000, end 1822.000000
    Metadata:
      title           : SVD modem 1 (VoiceView)
    Chapter #1:9: start 1822.000000, end 2084.000000
    Metadata:
      title           : SVD modem 2 (ASVD)
    Chapter #1:10: start 2084.000000, end 2400.000000
    Metadata:
      title           : ASVD demo
    Chapter #1:11: start 2400.000000, end 2505.000000
    Metadata:
      title           : ASVD explanation
    Chapter #1:12: start 2505.000000, end 2755.000000
    Metadata:
      title           : SVD modem 3 (DSVD)
    Chapter #1:13: start 2755.000000, end 3107.000000
    Metadata:
      title           : DSVD demo
    Chapter #1:14: start 3107.000000, end 3502.000000
    Metadata:
      title           : DSVD explanation
    Chapter #1:15: start 3502.000000, end 3602.000000
    Metadata:
      title           : ASVD demo (advanced)
    Chapter #1:16: start 3602.000000, end 3852.000000
    Metadata:
      title           : Why SVD failed
    Chapter #1:17: start 3852.000000, end 3854.669000
    Metadata:
      title           : Outro
    Chapter #1:18: start 3854.669000, end 3903.000000
    Metadata:
      title           : [SponsorBlock]: Unpaid/Self Promotion
[NULL @ 0x55ddeb2de880] Unable to find a suitable output format for 'file:Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720.temp'
file:Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720.temp: Invalid argument

ERROR: file:Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720.temp: Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 705, in run
    self.run_ffmpeg_multiple_files(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 324, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 362, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Cathode Ray Dude [CRD] - Voice chat in the age of modems - 7mqkTFq7Ekg - 1280x720.temp: Invalid argument

[XAttrMetadata] Writing metadata to file's xattrs
````
```

**Comment by gamer191** [comment]
1. you aren't using that filter in your verbose log
2. did you pass `--video-multistreams --audio-multistreams`?

**Comment by bashonly** [comment]
Add `.%(ext)s` to your output template in your config file
e.g. `-o "%(channel)s - %(title)s - %(id)s - %(resolution)s.%(ext)s"`

Are you sure `-"best[fps<=45]+best"` is what you want? This means it will merge the best <=45 fps format with the best non-filtered format (both of which are format 22 in this case, which is why there is an error)

Maybe you mean `-f "bestvideo[fps<=45]+bestaudio"`? or `-f "best[fps<=45]/best"?

**Comment by TheKorn2** [comment]
> 1. you aren't using that filter in your verbose log

Ah crud. That'll teach me to open up a bug first thing in the morning.

>     2. did you pass `--video-multistreams --audio-multistreams`?

I did not, but that (plus the fixed filter from bashonly) got me fixed right up.

Thanks to you both!!
