### ISSUE TITLE
[Broken] CNBC

### ISSUE THREAD

**Issue by sufr3ak** [yt-dlp/yt-dlp#703]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', 'https://www.cnbc.com/live-tv/the-profit/full-episode/mo-honey-mo-problems/1931240515516']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 (zip)
[debug] Python version 3.7.5 (CPython 64bit) - Linux-4.15.0-130-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg N-50726-g20c5f4d835-static, ffprobe N-50726-g20c5f4d835-static
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.cnbc.com/live-tv/the-profit/full-episode/mo-honey-mo-problems/1931240515516
[generic] 1931240515516: Requesting header
WARNING: [generic] Could not send HEAD request to https://www.cnbc.com/live-tv/the-profit/full-episode/mo-honey-mo-problems/1931240515516: HTTP Error 503: Service Unavailable
[generic] 1931240515516: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 1931240515516: Extracting information
ERROR: Unsupported URL: https://www.cnbc.com/live-tv/the-profit/full-episode/mo-honey-mo-problems/1931240515516
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1224, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 575, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.cnbc.com/live-tv/the-profit/full-episode/mo-honey-mo-problems/1931240515516


```

## Description

The URL doesn't work. After finally digging up a m3u8 from my browser and passing it over, the audio has consistent drops, with the message

[https @ 0x7922080] Cannot reuse HTTP connection for different host: vod-lf-oneapp-prd.akamaized.net:-1 != redirect.manifest.theplatform.com:-1
[hls @ 0x7544040] keepalive request failed for 'https://redirect.manifest.theplatform.com/r/HNK2IC/tZref27rBHtV,neFYKrEsFVPO,zjc3pKNPMXIv,xk8YixrfZ_sj,l7axxkSPRvf8,0r_G4jp7_7r3/aHR0cHM6Ly92b2QtbGYtb25lYXBwLXByZC5ha2FtYWl6ZWQubmV0L3Byb2QvdmlkZW8vaEFOLzNqby85MDAwMTE2NTE3L29Oalp1b01Nd3NwNWY1WjJyMFVtRy8xODUwa181NDBfaGxzL18xODU1MDM3MjM0LTBfMDA0MjIudHM?sid=daf7bfb2-46b0-4163-8cf3-204d1264ee2a&policy=174233584&date=1628992257037&ip=108.24.88.17&schema=1.0&cid=39ffc7ce-f486-4a20-8fc6-52e1f0075b52&aid=2304981409&dur=2599021&sig=58aa3943f9cc0221dcbc1abed29bcb33eb38f0c82bb8092dcbfec394b9822420' with error: 'Invalid argument' when opening url, retrying with new connection

**Comment by Ashish0804** [comment]
Requires an account (and maybe a pro account aswell?)
also might be region locked to usa (not sure tho)

**Comment by sufr3ak** [comment]
No requirement for login on this page

**Comment by Ashish0804** [comment]
yes, it's working without account (Requires US IP)
But I'm still not able to navigate the site without account -_-
I have tracked down the manifest to this request `https://link.theplatform.com/s/`
Provide another url which is working without account and i'll see how the data for the request is being generated

**Comment by BeeMuffins** [comment]
Agree site requires US IP, I was able to find a couple more episodes noted below that didn't require a free account from navigating here, https://www.cnbc.com/live-tv/full-episodes/ Most require you to login to play them, but below are the couple additional that didn't need it.

Here are the links.
https://www.cnbc.com/live-tv/money-court/full-episode/million-dollar-decision/1931703363727
https://www.cnbc.com/live-tv/super-heists/full-episode/all-the-presidents-money-/1930841667784

Looking at them briefly (though not sure im going the right direction it seems that this link from the existing extractor would need to be update along with the regex.

https://github.com/yt-dlp/yt-dlp/blob/7581d2467a2f286963313cca0afc97875a9c54cd/yt_dlp/extractor/cnbc.py#L35

Seems like these reference to: https://link.theplatform.com/s/ **HNK2IC** /media/

**Comment by Ashish0804** [comment]
I don't think this direct approach will work here
This is the request which has the above url
`https://player.theplatform.com/p/gZWlPC/_fSoW8mNx_5w/select/media/guid/2304981409/id-but-not-id-in-url?mute=false&autoPlay=false&playbackStartPosition=0&policy=174233584&MVPDid=undefined&params=policy%3D174233584%26fallbackSiteSectionId%3D7006049%26siteSectionId%3Dcnbc_inline_vod%26manifest%3Dm3u%26switch%3DHLSServiceSecure%26_fw_ae%3Dundefined%26_fw_vcid2%3Df077ca7d-ee5b-4ac6-a908-f59aa9d45b43%26_fw_h_referer%3Dwww.cnbc.com%26schema%3D2.0%26csid%3Dcnbc_tveverywhere_vod_hub%26afid%3D137705375`

Anyways I won't be able to work on this before 24-25th august, so if anyone want's to make a PR before that, then feel free to do so.
