### ISSUE TITLE
Villagesexvideos.com

### ISSUE THREAD

**Issue by suniljlandge** [yt-dlp/yt-dlp#7033]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

-filter wise: https://www.villagesexvideos.com/?filter=latest
-single video: https://www.villagesexvideos.com/mallu-open-shirt-small-boobs-village-girl/
-category : https://www.villagesexvideos.com/category/dehati-sex/
-tag wise : https://www.villagesexvideos.com/tag/big-boobs/
-search : https://www.villagesexvideos.com/?s=girl

### Provide a description that is worded well enough to be understood

the website is an adult website which provides 18+ videos (NSFW)

I want to yt-dlp can download filter-wise, search-wise, single url , category, tag-wise...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.villagesexvideos.com/mallu-open-shirt-small-boobs-village-girl/', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-06-20-git-56419428a8-essentials_build-www.gyan.dev (setts), ffprobe 2022-06-20-git-56419428a8-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.villagesexvideos.com/mallu-open-shirt-small-boobs-village-girl/
[generic] mallu-open-shirt-small-boobs-village-girl: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] mallu-open-shirt-small-boobs-village-girl: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.villagesexvideos.com/mallu-open-shirt-small-boobs-village-girl/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.villagesexvideos.com/mallu-open-shirt-small-boobs-village-girl/
```

**Comment by dirkf** [comment]
In the single video page, the content is sent as HTML5 video in the `.responsive-player > iframe` element, whose `src` attribute can be passed to the generic extractor. An MP4 link (identical here) is in the `content` attribute of the `.video-player > meta[itemprop=contentURL]` element. Additional metadata is in the parallel `author`, `name`, `description`, `duration`, `thumbnailUrl`, `uploadDate` `<meta itemprop=...>` elements.

**Comment by suniljlandge** [comment]
but for filter-wise, search-wise, category and tag-wise we have to do a lot of manual things...

**Comment by suniljlandge** [comment]
> In the single video page, the content is sent as HTML5 video in the `.responsive-player > iframe` element, whose `src` attribute can be passed to the generic extractor. An MP4 link (identical here) is in the `content` attribute of the `.video-player > meta[itemprop=contentURL]` element. Additional metadata is in the parallel `author`, `name`, `description`, `duration`, `thumbnailUrl`, `uploadDate` `<meta itemprop=...>` elements.

I can directly download it without a generic extractor... then what is the point of using yt-dlp??

**Comment by pukkandan** [comment]
dirkf's instructions are for devs

**Comment by suniljlandge** [comment]
is there any progress regarding this issue??
