### ISSUE TITLE
[bilibili.tv] BiliBili videos giving error while extracting formats

### ISSUE THREAD

**Issue by shortthirdman** [yt-dlp/yt-dlp#7036]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [ ] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

The error seems that any formats of the specified video URL is not found and which is itself giving null exception.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -v -F --cookies-from-browser brave 'https://www.bilibili.tv/en/video/2048361032'                                                                 pwsh   69  00:18:12 
[debug] Command-line config: ['-v', '-F', '--cookies-from-browser', 'brave', 'https://www.bilibili.tv/en/video/2048361032']
[debug] User config "C:\Users\SWMOHAN\yt-dlp.conf": ['--config-location', 'C:\\Users\\SWMOHAN\\yt-dlp.conf', '--embed-metadata', '--xattrs', '--netrc', '--merge-output-format', 'mp4', '--progress', '--console-title', '--no-cache-dir', '--no-part', '--continue', '--no-windows-filenames', '--hls-use-mpegts', '--geo-bypass', '--ignore-errors', '--no-warnings', '--ffmpeg-location', 'C:\\SM25216\\YouTubeDL\\ffmpeg-4.4.1\\essentials\\bin', '--postprocessor-args', 'FFmpeg:-v quiet', '--ignore-no-formats-error', '--audio-multistreams', '--compat-options', 'no-live-chat', '--allow-dynamic-mpd']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.11.094900 [21b9413cf] (win_exe)
[debug] Compatibility options: no-live-chat
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "C:\Users\SWMOHAN\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\SWMOHAN\AppData\Local\BraveSoftware\Brave-Browser\User Data\Local State"
[Cookies] Extracted 10 cookies from brave
[debug] cookie version breakdown: {'v10': 10, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[BiliIntl] Extracting URL: https://www.bilibili.tv/en/video/2048361032
[BiliIntl] 2048361032: Downloading webpage
[BiliIntl] 2048361032: Downloading video formats
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1532, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1608, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\bilibili.py", line 1254, in _real_extract
  File "yt_dlp\extractor\bilibili.py", line 918, in _get_formats
TypeError: 'NoneType' object is not subscriptable
```

**Comment by bashonly** [comment]
```
[BiliIntl] 2048361032: Downloading video formats
```

I am in a different region than OP, but for me the above API call is returning this JSON:

```json
{
  "code": 10015001,
  "message": "版权地区受限",
  "ttl": 1,
  "data": null
}
```
@shortthirdman could you add `--write-pages` to your command and inspect the resulting `2048361032_https_-_api.bilibili.tv_intl_gateway_web_playurlplatform=web_aid=2048361032.dump` file to see if its contents are the same? or post it if different?

google translates the `message` value to "Restrictions on copyright areas"

`data` is `null`, so the `BiliIntlBaseIE._call_api` method is returning `None`:

```py
    def _call_api(self, endpoint, *args, **kwargs):
        json = self._download_json(self._API_URL + endpoint, *args, **kwargs)
        if json.get('code'):
            if json['code'] in (10004004, 10004005, 10023006):
                self.raise_login_required()
            elif json['code'] == 10004001:
                self.raise_geo_restricted()
            else:
                if json.get('message') and str(json['code']) != json['message']:
                    errmsg = f'{kwargs.get("errnote", "Unable to download JSON metadata")}: {self.IE_NAME} said: {json["message"]}'
                else:
                    errmsg = kwargs.get('errnote', 'Unable to download JSON metadata')
                if kwargs.get('fatal'):
                    raise ExtractorError(errmsg)
                else:
                    self.report_warning(errmsg)
        return json.get('data')
```

Looks like the error code handling may need to be updated/improved

**Comment by shortthirdman** [comment]
Hey @bashonly ,
I ran the same command as you have mentioned above, looks like the video is geo-restricted.
`yt-dlp -F --xff 'US' --write-pages -v $bl                                                                                                                
[debug] Command-line config: ['-F', '--xff', 'US', '--write-pages', '-v', 'https://www.bilibili.tv/en/video/2049015156']
[debug] User config "C:\Users\SWMOHAN\yt-dlp.conf": ['--config-location', 'C:\\Users\\SWMOHAN\\yt-dlp.conf', '--embed-metadata', '--xattrs', '--netrc', '--merge-output-format', 'mp4', '--progress', '--console-title', '--no-cache-dir', '--no-part', '--continue', '--no-windows-filenames', '--hls-use-mpegts', '--geo-bypass', '--ignore-errors', '--no-warnings', '--ffmpeg-location', 'C:\\SM25216\\YouTubeDL\\ffmpeg-4.4.1\\essentials\\bin', '--postprocessor-args', 'FFmpeg:-v quiet', '--ignore-no-formats-error', '--audio-multistreams', '--compat-options', 'no-live-chat', '--allow-dynamic-mpd']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.11.094900 [21b9413cf] (win_exe)
[debug] Compatibility options: no-live-chat
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[debug] Using fake IP 6.234.11.57 (US) as X-Forwarded-For
[BiliIntl] Extracting URL: https://www.bilibili.tv/en/video/2049015156
[BiliIntl] 2049015156: Downloading webpage
[BiliIntl] Saving request to 2049015156_https_-_www.bilibili.tv_en_video_2049015156.dump
[BiliIntl] 2049015156: Downloading video formats
[BiliIntl] Saving request to 2049015156_https_-_api.bilibili.tv_intl_gateway_web_playurlplatform=web_aid=2049015156.dump
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1532, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1608, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\bilibili.py", line 1254, in _real_extract
  File "yt_dlp\extractor\bilibili.py", line 918, in _get_formats
TypeError: 'NoneType' object is not subscriptable`


And got the same response from the API:
`{"code":10015001,"message":"版权地区受限","ttl":1,"data":null}`

**Comment by shortthirdman** [comment]
@bashonly @pukkandan Any workaround fix for the command to work fine. Note: I am not using any kind of VPN as of now.

**Comment by bashonly** [comment]
@shortthirdman
what about this?
> I've checked that all provided URLs are playable in a browser with the same IP and same login details

**Comment by shortthirdman** [comment]
> @shortthirdman what about this?
> 
> > I've checked that all provided URLs are playable in a browser with the same IP and same login details

My bad, I have checked it by mistake, must be a typo.

**Comment by bashonly** [comment]
> My bad, I have checked it by mistake, must be a typo.
> Any workaround fix for the command to work fine

`--xff` doesn't seem to have any effect, so no, there is no workaround other than using a VPN or proxy.

As I mentioned in my first comment though, this error should be caught and the extractor should raise for geo-restriction

**Comment by shortthirdman** [comment]
Closing out the issue as this is user-location related and has nothing to do with application.

**Comment by grqz** [comment]
```diff
diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
index 3163df8ab..a446bae4b 100644
--- a/yt_dlp/extractor/bilibili.py
+++ b/yt_dlp/extractor/bilibili.py
@@ -1859,7 +1859,7 @@ def _call_api(self, endpoint, *args, **kwargs):
         if json.get('code'):
             if json['code'] in (10004004, 10004005, 10023006):
                 self.raise_login_required()
-            elif json['code'] == 10004001:
+            elif json['code'] in (10004001, 10015001):
                 self.raise_geo_restricted()
             else:
                 if json.get('message') and str(json['code']) != json['message']:
```
maybe?
