### ISSUE TITLE
Video downloaded has no sound and post error yt_dlp.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

### ISSUE THREAD

**Issue by lxrswdd** [yt-dlp/yt-dlp#7061]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, 
Initially, I have options as follows: 
```
ydl_opts = {
    'format': 'bestvideo/best',
    'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s',
    'ignore-errors': True
}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([f'https://www.youtube.com/watch?v=_5rNOD1nsDg'])
```
Then I realize that the '.webm' file I downloaded has no sound when I was trying to extract audio using `ffmpeg`.

Then I changed my `ydl_opts` to the following which should give me an isolated audio file if I understand the commands correctly.
```
ydl_opts = {
    'format': 'bestvideo/best',
    'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s',
    'ignore-errors': True,
    'verbose': True,
    'postprocessors': [{  # Extract audio using ffmpeg
        'key': 'FFmpegExtractAudio'

    }]
}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([f'https://www.youtube.com/watch?v=_5rNOD1nsDg'])
```

However, an error popped up.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API
[debug] params: {'format': 'bestvideo/best', 'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s', 'ignore-errors': True, 'verbose': True, 'postprocessors': [{'key': 'FFmpegExtractAudio'}], 'compat_opts': set()}
[debug] Python 3.10.11 (CPython x86_64 64bit) - Linux-5.19.0-41-generic-x86_64-with-glibc2.35 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.17, brotli-None, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=_5rNOD1nsDg
[youtube] _5rNOD1nsDg: Downloading webpage
[youtube] _5rNOD1nsDg: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] _5rNOD1nsDg: Downloading 1 format(s): 313
[debug] Invoking dashsegments downloader on "https://rr1---sn-j5o5gpx-t8ge.googlevideo.com/videoplayback?expire=1684363502&ei=jgRlZNyNBeWRsfIPysq4mAE&ip=137.82.223.99&id=o-ALoGiE75YFPX-xy2M_yu-Iwqn8KoJWFig6thTw6ZVZNG&itag=313&source=youtube&requiressl=yes&mh=Sk&mm=31%2C29&mn=sn-j5o5gpx-t8ge%2Csn-uxa0n-t8gy&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=16&initcwndbps=1521250&spc=qEK7B1khfaJyQRq_glHxRq5aryV6Re0&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=970849705&dur=608.960&lmt=1628826375834379&mt=1684341432&fvip=2&keepalive=yes&fexp=24007246%2C51000023&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPrauGFR16eVVs4sjDSB16jbEvyrkt2RIJDASvfmeofNAiAcWDyCxRF1kh7V0gPmlPChl83U1fzFX2nFfsWG3Q7YeA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXoCyCG8cK3cyrbxfFTg25REFbv_Qhiv4fPgc8PPhx0wCIHIVY0WC-eRXtVytGNFhxfvvGUs-84WtocmEVCiT42Pi"
[download] /data/share/VFHQ/data/download_youtube/_5rNOD1nsDg.webm has already been downloaded
[download] 100% of  925.87MiB
[debug] ffmpeg command line: ffprobe -show_streams file:/data/share/VFHQ/data/download_youtube/_5rNOD1nsDg.webm
ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3502, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3484, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 490, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
yt_dlp.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe
```

**Comment by bashonly** [comment]
It has no sound because your format selection argument is `bestvideo/best` -- meaning it will download the best ***video-only*** format first before falling back to `best`.

The default format selection is `bestvideo*+bestaudio/best`, but for the purpose of extracting audio it is better to use `bestaudio/best`

**Comment by lxrswdd** [comment]
@bashonly Thank you for responding.
Is there a way to download the video .mp4 and the audio .wav separately in python api?
I know `$ yt-dlp -f "bv,ba" -o "%(title)s.f%(format_id)s.%(ext)s"` this bash command can do it. What about python?

I am doing it using the following redundant method:
```
ydl_opts = {
    'format': 'mp4',
    'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s',
    'ignore-errors': True
}
try:
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([f'https://www.youtube.com/watch?v={videoid}'])

except Exception as error:
    print('Error: ', error)

ydl_opts = {
    'format': 'mp4',
    'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s',
    'ignore-errors': True,
    'verbose': False,
    'postprocessors': [{  # Extract audio using ffmpeg
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'wav'
    }]
}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([f'https://www.youtube.com/watch?v=_-91nXXjrVo'])    
```

**Comment by bashonly** [comment]
```py
ydl_opts = {
    'format': 'bv,ba',  # same as: -f bv,ba
    'format_sort': ['ext'],  # for mp4 video
    'keepvideo': True,  # don't delete video after audio is extracted
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'wav',
    }
```

**Comment by lxrswdd** [comment]
@bashonly 
The options below only generated a .mp4 file and there isn't any .wav as expected.
Can you help me out?
```
ydl_opts = {
    'format': 'bv,ba',  # same as: -f bv,ba
    'format_sort': ['ext'],  # for mp4 video
    'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s',
    'keepvideo': True,  # don't delete video after audio is extracted
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'wav'
    }]
    }
```

with following log:
```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API
[debug] params: {'format': 'mp4,ba', 'format_sort': ['ext'], 'verbose': True, 'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s', 'keepvideo': True, 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'wav'}], 'compat_opts': set()}
[debug] Python 3.10.11 (CPython x86_64 64bit) - Linux-5.19.0-41-generic-x86_64-with-glibc2.35 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.17, brotli-None, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=_-91nXXjrVo
[youtube] _-91nXXjrVo: Downloading webpage
[youtube] _-91nXXjrVo: Downloading android player API JSON
[debug] Sort order given by user: ext
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vext, aext, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, hasaud, id
[info] _-91nXXjrVo: Downloading 2 format(s): 22, 140
[debug] Invoking http downloader on "https://rr3---sn-j5o5gpx-t8ge.googlevideo.com/videoplayback?expire=1684375258&ei=ejJlZL2bH5misfIP446YwAI&ip=137.82.223.99&id=o-AEBD8MfeQLB8TR-iRAOkky-CMQzhdaaHpIvs9DVSvUhE&itag=22&source=youtube&requiressl=yes&mh=D8&mm=31%2C29&mn=sn-j5o5gpx-t8ge%2Csn-uxa0n-t8ge7&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=16&initcwndbps=1692500&spc=qEK7By2-bObUqxbmt58jo8PNgiGa0L4&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=264.034&lmt=1630467921674231&mt=1684353190&fvip=3&fexp=24007246%2C24362685%2C24363393&beids=24350018&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgFqPJysHdyVGmTDulBI6fbB-wd6C7nCEO-_dRR3q4CVYCIEn9Bz2uAHWwz6sXF5qfF12FjdnZiyjCriOH0emGdGqg&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALlEYFo1dzGOxe4B_hOfA6hiT5ufFw72AZ8iLD4AnEUTAiA9Lkqg_oQAszIZVL-jLACtwO5NP6zc-O8COoQDpSlE7w%3D%3D"
[download] /data/share/VFHQ/data/download_youtube/_-91nXXjrVo.mp4 has already been downloaded
[download] 100% of   56.48MiB
[debug] ffmpeg command line: ffprobe -show_streams fil[e:/data/share/VFHQ/data/download_youtube/_-91nXXjrVo.mp4](file:///E:/data/share/VFHQ/data/download_youtube/_-91nXXjrVo.mp4)
ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3502, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3484, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 490, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
yt_dlp.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

Error:  ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe
```

**Comment by bashonly** [comment]
If you add `'ignoreerrors': True` to the opts it will work, but you will still have original (non-WAV) audio format as well. 

But I'm a little confused about what you actually want, since in the above log you altered the params from my suggestion:
```
[debug] params: {'format': 'mp4,ba'
```

Do you want a video-only mp4 and a WAV audio track? Using `mp4` in the format selection will select an mp4 format that has both video+audio

**Comment by lxrswdd** [comment]
Here is my current solution, I mean it works except it also generates a .webm file.
```
ydl_opts = {
    'format': 'mp4,ba',  # same as: -f bv,ba
    'verbose': False,
    'ignore-errors': True,
    'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s',
    'keepvideo': True,  # don't delete video after audio is extracted
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'wav'
    }]
    }
```

**Comment by bashonly** [comment]
What are you trying to achieve, though? Can you answer my question from my previous comment?

> Do you want a video-only mp4 and a WAV audio track?

**Comment by lxrswdd** [comment]
My objective is to obtain the video with the best resolution and its best quality audio seperately.
I am using .mp4 because the .webm I download has no sound probably due to codecs

**Comment by lxrswdd** [comment]
@bashonly 
Hi, apparently that .mp4 doesn't work, the resolution is not as high as .webm.
Is there a way to get .webm and .wav at the same time ?

```
        ydl_opts = {
            'format': 'bv,ba',  # same as: -f bv,ba
            # 'format_sort': ['ext'],  # for mp4 video
            'verbose': False,
            'ignore-errors': True,
            'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s',
            'keepvideo': True,  # don't delete video after audio is extracted
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'wav'
            }]
            }
```
The above options will only generate .webm. 
I get the error below. I wonder if it is the caused by the version of ffmpeg. I have 2 versions in the system one is 4.3 the other is 4.4.2. May be the problem can be solved by calling the v4.4.2 ffmpeg.

```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API
[debug] params: {'format': 'bv,ba', 'verbose': True, 'ignore-errors': True, 'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s', 'keepvideo': True, 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'wav'}], 'compat_opts': set()}
[debug] Python 3.10.11 (CPython x86_64 64bit) - Linux-5.19.0-41-generic-x86_64-with-glibc2.35 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.17, brotli-None, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
----------------------------------------------------------------------------
----------------------------------------------------------------------------
Going through meta file:  Clip+_-MpWAXYSSk+P0+C0+F1634-1745.txt
----------------------------------------------------------------------------
----------------------------------------------------------------------------
file exist /data/share/VFHQ/data/generated_video/_-MpWAXYSSk/Clip+_-MpWAXYSSk+P0+C0+F1634-1745/Clip+_-MpWAXYSSk+P0+C0+F1634-1745_out.mp4
False
[youtube] Extracting URL: https://www.youtube.com/watch?v=_-MpWAXYSSk
[youtube] _-MpWAXYSSk: Downloading webpage
[youtube] _-MpWAXYSSk: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] _-MpWAXYSSk: Downloading 2 format(s): 313, 251
[debug] Invoking dashsegments downloader on "https://rr3---sn-j5o5gpx-t8ge.googlevideo.com/videoplayback?expire=1684480462&ei=bs1mZMG0M4OWkgaj_6qoCQ&ip=137.82.223.99&id=o-AG1gCk-XdL0CwIaXhxRlmMOpvGSmXNvAvOLo8oHm2jb6&itag=313&source=youtube&requiressl=yes&mh=KV&mm=31%2C29&mn=sn-j5o5gpx-t8ge%2Csn-uxa0n-t8gy&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=16&initcwndbps=2436250&spc=qEK7B4CUomt3VFXA3ANq7BamPJpsQbs&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=291629419&dur=141.600&lmt=1539851648665525&mt=1684458541&fvip=3&keepalive=yes&fexp=24007246%2C51000024&c=ANDROID&txp=2201222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALyUBhFq4BAq3d8UcpNSKapBhK9O1goYq51xP-KU3tluAiEAkSNcdWGBX_KOi3LMVi9lQ_5OaA0gTGL8xdWdUgxvr4w%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgVG49NhdYusWJZZyQRnfb4ceN6svb6SQMdYr35i39BmUCIAZib6uLPusFbxXkoGAHV9ABNdmbqreuUhZV0YmbBxzB"
[download] /data/share/VFHQ/data/download_youtube/_-MpWAXYSSk.webm has already been downloaded
[download] 100% of  278.12MiB
[debug] ffmpeg command line: ffprobe -show_streams fil[e:/data/share/VFHQ/data/download_youtube/_-MpWAXYSSk.webm](file:///E:/data/share/VFHQ/data/download_youtube/_-MpWAXYSSk.webm)
ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3502, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3484, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/home/guest/anaconda3/envs/smart_class/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 490, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
yt_dlp.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

Error:  ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe
```

**Comment by pukkandan** [comment]
Add `format_id` somewhere in the `outtmpl`

**Comment by lxrswdd** [comment]
@pukkandan Can you elaborate more? I don't really understand what you meant.

**Comment by Lesmiscore** [comment]
So you're setting `'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s.%(ext)s'`, he said to change it to something like `'outtmpl': '/data/share/VFHQ/data/download_youtube/%(id)s-%(format_id)s.%(ext)s'`
It doesn't has to be exactly the same as I posted, but must be before `.%(ext)s`
