### ISSUE TITLE
Site support request for Baidu Haokan (百度好看视频)

### ISSUE THREAD

**Issue by Dr-Bluemond** [yt-dlp/yt-dlp#7069]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

China

### Example URLs

- Playlist: https://haokan.baidu.com/v?vid=11369462149913467613&collection_id=10316640470276722301&
- Single Video: https://haokan.baidu.com/v?vid=3321366250719491589

### Provide a description that is worded well enough to be understood

It's a classical video website. Nothing special from the others.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://haokan.baidu.com/v?vid=3321366250719491589']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.3 (CPython x86_64 64bit) - macOS-13.3.1-x86_64-i386-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://haokan.baidu.com/v?vid=3321366250719491589
[generic] v?vid=3321366250719491589: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] v?vid=3321366250719491589: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://haokan.baidu.com/v?vid=3321366250719491589
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://haokan.baidu.com/v?vid=3321366250719491589
```

**Comment by 03stevensmi** [comment]
I highly doubt yt-dlp will add this. They have a huge issue against anything chinese and never ever see them show any effort or interest in supporting any Chinese video platforms. I never have any issues with other sites... even once had a Dutch art website work. But I have never ever came across any Chinese websites that actually work with yt-dlp. Not even douyin works (last i checked ofc. Could be working now but I gave up when the cookies method stopped working). @haraldmartin @scw @Pawka @JackDanger could you please at least let us know (if your not going to add chinese sites like these) why these sort of websites are not supported? It's not like there niesh or not popular! They are used everyday by millions! I'm not chinese, nor ever set foot in China and even I use these video platforms as most of them (besides the region blocks, adds, vip blocks and popups) are actually really good and have good rare obscure stuff in there as well as a lot of cool content! Why do you never support popular chinese video platforms?

**Comment by bashonly** [comment]
@03stevensmi "yt-dlp" doesn't have a "huge issue against anything Chinese."

This is an open-source project worked on entirely by volunteers, and anyone is free to contribute. Nobody has made contributions to add/fix support for the sites you are complaining about. 

Stop whining. Teach yourself some Python and get to work.

**Comment by 03stevensmi** [comment]
Seriously bro, you got it all wrong. I'm sorry if I came across as disrespectful, I didn't know there was actually no interests and am very surprised as tbh as a lot of them are very active. I'm not whining... I literally thaught the devs did not want to support chinese platforms, honestly. Always figured it had maybe something to do with some type on controversy like how there country handles privacy or they may block things like this.
That's why I asked above why there never added chinese sites... but from what your telling me is it simply has to do with lack of intrest. 
Am I right? Or (just to clarify) is there actually another reason I'm not aware of. Just seems suprising no one has shown much support In any of these sites. Like I said, they really are not niche. Also again, I apologise if I sound out of line.

**Comment by bashonly** [comment]
All of yt-dlp's contributors are just regular people with lives/jobs/families/etc who devote their *free time* to making this software better. We don't have infinite free time, and each developer is going to allocate their time to working on the issues/features that interest them most or that they view as a priority. If I could fix everything and add every feature, I would. But I haven't got the time.

**Comment by 03stevensmi** [comment]
It sounds to me like it would help u guys out a lot if there was more people involved and more helpful contributions to add sites. Right? 
I never asked a single person for do everything at once all by them selves. 
But I always thought yt-dlp had hundreds of active contributors.

I think we need someone who has some experience in python to help out on the Chinese side of things.
I know it will help a lot of people out. 

I wish I could just straight up learn python and dump a few sites here but
As you may have guessed I honestly have no idea what I'm doing when it comes to this sort of stuff. 
I've been trying to add (or scrap) websites using python for kodi and have never even came close to sucseeding 
or even getting my head around it despite trying and studying for the past 10 years (or however long it's been since may 2015). 
The best I got was json (I know I know!).
However, I am getting better than I was... but It still has to eventually click in my head first 
before I can dive head first in python.

Edit: also apologies for my bad spelling and grammar... all you need to know is I'm using a Samsung galaxy... yep!
