### ISSUE TITLE
Download Udemy course HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by mahdisky** [yt-dlp/yt-dlp#7070]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

i used 
"# Download Udemy course keeping each chapter in separate directory under MyVideos directory in your home
$ yt-dlp -u user -p password -P "~/MyVideos" -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s" "https://www.udemy.com/java-tutorial"

but I have error HTTP Error 403: Forbidden:

[udemy:course] Downloading login popup
ERROR: [udemy:course] course: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-P', '~/MyVideos', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/course/minitab-statistics', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.9.12 (CPython 64bit) - Windows-10-10.0.19045-SP0
[debug] exe versions: ffmpeg 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2023.03.04, Current version: 2022.02.04
Current Build Hash a16fe3b3bd474d562c4b8645579b209377b967d58d4edffe6e31dc8de81d7283
Updating to version 2023.03.04 ...
Updated yt-dlp to version 2023.03.04; Restart yt-dlp to use the new version
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\xxx\yt-dlp\__main__.py", line 19, in <module>
  File "F:\xxx\yt-dlp\yt_dlp\__init__.py", line 857, in main
  File "F:\xxx\yt-dlp\yt_dlp\__init__.py", line 847, in _real_main
  File "F:\xxx\yt-dlp\yt_dlp\YoutubeDL.py", line 3212, in download
  File "F:\xxx\yt-dlp\yt_dlp\YoutubeDL.py", line 3185, in wrapper
  File "F:\xxx\yt-dlp\yt_dlp\YoutubeDL.py", line 1372, in extract_info
  File "F:\xxx\yt-dlp\yt_dlp\YoutubeDL.py", line 732, in get_info_extractor
  File "F:\xxx\yt-dlp\yt_dlp\extractor\lazy_extractors.py", line 28, in __new__
  File "F:\xxx\yt-dlp\yt_dlp\extractor\lazy_extractors.py", line 23, in _get_real_class
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 548, in _get_data
zipimport.ZipImportError: bad local file header: 'F:\\xxx\\yt-dlp'
```

**Comment by javix64** [comment]
hey! i have successfully download a course with the option ``--legacy-server-connect`` try it @mahdisky

**Comment by edytowany3000** [comment]
> hey! i have successfully download a course with the option `--legacy-server-connect` try it @mahdisky

Can you please give me entire line of it? And possibly a solution using Cookies too? (Im new to cmd, and new to yt-dlp).
