### ISSUE TITLE
[youtube] videos with many comments fail because the link expires for the subtitles

### ISSUE THREAD

**Issue by jakeogh** [yt-dlp/yt-dlp#7074]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

If my understanding of the issue is correct, the subtitles URL is expired before the comments are done downloading.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp https://www.youtube.com/watch?v=ALj5MKjy2BU --write-comments --write-subs --verbose
[debug] Command-line config: ['https://www.youtube.com/watch?v=ALj5MKjy2BU', '--write-comments', '--write-subs', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.0.5-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_i7-4910MQ_CPU_@_2.90GHz-with-glibc2.37 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.3 (setts), ffprobe 5.1.3
[debug] Optional libraries: brotlicffi-1.0.9.2, certifi-3021.03.16, mutagen-1.46.0, pycrypto-3.17, pyxattr-0.8.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1810 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=ALj5MKjy2BU
[youtube] ALj5MKjy2BU: Downloading webpage
[youtube] ALj5MKjy2BU: Downloading android player API JSON
[info] ALj5MKjy2BU: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[youtube] Downloading comment section API JSON
[youtube] Downloading ~769442 comments
[youtube] Sorting comments by newest first
[youtube] Downloading comment API JSON page 1 (0/769442)
[youtube]     Downloading comment API JSON reply thread 1 (8/769442)
[youtube]     Downloading comment API JSON reply thread 2 (16/769442)
[youtube] Downloading comment API JSON page 2 (18/769442)
[youtube]     Downloading comment API JSON reply thread 1 (21/769442)
[youtube]     Downloading comment API JSON reply thread 2 (27/769442)
[youtube]     Downloading comment API JSON reply thread 3 (31/769442)
[youtube]     Downloading comment API JSON reply thread 4 (33/769442)
[youtube]     Downloading comment API JSON reply thread 5 (35/769442)
[youtube] Downloading comment API JSON page 3 (43/769442)
[youtube]     Downloading comment API JSON reply thread 1 (47/769442)
[youtube]     Downloading comment API JSON reply thread 2 (50/769442)
[youtube]     Downloading comment API JSON reply thread 3 (52/769442)
[youtube]     Downloading comment API JSON reply thread 4 (56/769442)
[youtube]     Downloading comment API JSON reply thread 5 (60/769442)
[youtube]     Downloading comment API JSON reply thread 6 (64/769442)
[youtube]     Downloading comment API JSON reply thread 7 (71/769442)
[youtube]     Downloading comment API JSON reply thread 8 (75/769442)
[youtube]     Downloading comment API JSON reply thread 9 (78/769442)
[youtube]     Downloading comment API JSON reply thread 10 (84/769442)
[youtube]     Downloading comment API JSON reply thread 11 (88/769442)
[youtube] Downloading comment API JSON page 4 (91/769442)
[youtube]     Downloading comment API JSON reply thread 1 (94/769442)

<snip, this takes a long time, even on my 100MB connection, which I suspect is why the bug is triggered>

[youtube]     Downloading comment API JSON reply thread 2 (769323/769442)
[youtube]     Downloading comment API JSON reply thread 3 (769328/769442)
[youtube] Downloading comment API JSON page 25070 (769332/769442)
[youtube]     Downloading comment API JSON reply thread 1 (769336/769442)
[youtube]        Downloading comment replies API JSON page 1 (769346/769442)
[youtube] Downloading comment API JSON page 25071 (769373/769442)
[youtube]     Downloading comment API JSON reply thread 1 (769382/769442)
[youtube] Extracted 769442 comments
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ALj5MKjy2BU: Downloading 1 format(s): 248+251
[info] Writing video description to: /home/user/_youtube/sources_yt-dlp/youtube/ALj5MKjy2BU/1theK (원더케이)__@1theK__20160501__ALj5MKjy2BU.description
[info] Writing video subtitles to: /home/user/_youtube/sources_yt-dlp/youtube/ALj5MKjy2BU/1theK (원더케이)__@1theK__20160501__ALj5MKjy2BU.en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=ALj5MKjy2BU&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1684422052&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Copi%2Cxoaf&signature=61B3EA3C57152E57C9DACFFDB4B7C61061636CBF.8AD71A
EED234459E6AE4381A7D33E618C31F4A09&key=yt8&lang=en&fmt=vtt"
ERROR: Unable to download video subtitles for 'en': HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4032, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2980, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/http.py", line 376, in real_download
    establish_connection()
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3753, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

$ date +%s
1684437395  # note this is after the "expire=1684422052" in the URL above

# invoking without --write-comments works as expected:

$ yt-dlp https://www.youtube.com/watch?v=ALj5MKjy2BU --write-subs --verbose
[debug] Command-line config: ['https://www.youtube.com/watch?v=ALj5MKjy2BU', '--write-subs', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.0.5-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_i7-4910MQ_CPU_@_2.90GHz-with-glibc2.37 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.3 (setts), ffprobe 5.1.3
[debug] Optional libraries: brotlicffi-1.0.9.2, certifi-3021.03.16, mutagen-1.46.0, pycrypto-3.17, pyxattr-0.8.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1810 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=ALj5MKjy2BU
[youtube] ALj5MKjy2BU: Downloading webpage
[youtube] ALj5MKjy2BU: Downloading android player API JSON
[info] ALj5MKjy2BU: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ALj5MKjy2BU: Downloading 1 format(s): 248+251
[info] Writing video subtitles to: [MV] BTS(방탄소년단) _ FIRE (불타오르네) [ALj5MKjy2BU].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=ALj5MKjy2BU&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1684462728&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Copi%2Cxoaf&signature=1C87E0629F3589241A46B45AB9EAB7471CA19CCA.44735375255256DC37A75EF7071307C937C6AE69&key=yt8&lang=en&fmt=vtt"
[download] Destination: [MV] BTS(방탄소년단) _ FIRE (불타오르네) [ALj5MKjy2BU].en.vtt
[download] 100% of    2.79KiB in 00:00:00 at 15.42KiB/s
[debug] Invoking http downloader on "https://rr4---sn-hp57kn6r.googlevideo.com/videoplayback?expire=1684459129&ei=GXpmZNelHZmZsfIP3-unuAo&ip=172.56.80.86&id=o-ABC44Brz11oL1zo7at8zmxg2_YXZhaW_gsdolIKzN4-I&itag=248&source=youtube&requiressl=yes&mh=27&mm=31%2C26&mn=sn-hp57kn6r%2Csn-p5qlsn76&ms=au%2Conr&mv=m&mvi=4&pl=23&initcwndbps=2586250&spc=qEK7B3NNkpa1HcoyW8LMJB2aIR8-fTE&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=81738551&dur=294.627&lmt=1673349907687581&mt=1684437429&fvip=1&keepalive=yes&fexp=24007246%2C24363392&c=ANDROID&txp=453D434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOEBqt4SQc3LzJphXkyAMZ5qqG4gFLlo1BMChjUFK_vqAiAyyRhiPOzzJ4NMa1o9ssUtQFLAmwShnPwKLbONcPcNBw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPyPP9Zz_woMqDXqUvCQiEDP_i1aBNxoQR8vw8wH2xEDAiBWcOME5z4ZRdI3R-ngF3SqOplE4h_3DwZ-MkYFGEFitQ%3D%3D"
[download] Destination: [MV] BTS(방탄소년단) _ FIRE (불타오르네) [ALj5MKjy2BU].f248.webm
[download] 100% of   77.95MiB in 00:00:31 at 2.45MiB/s
[debug] Invoking http downloader on "https://rr4---sn-hp57kn6r.googlevideo.com/videoplayback?expire=1684459129&ei=GXpmZNelHZmZsfIP3-unuAo&ip=172.56.80.86&id=o-ABC44Brz11oL1zo7at8zmxg2_YXZhaW_gsdolIKzN4-I&itag=251&source=youtube&requiressl=yes&mh=27&mm=31%2C26&mn=sn-hp57kn6r%2Csn-p5qlsn76&ms=au%2Conr&mv=m&mvi=4&pl=23&initcwndbps=2586250&spc=qEK7B3NNkpa1HcoyW8LMJB2aIR8-fTE&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4444039&dur=294.721&lmt=1673344416101864&mt=1684437429&fvip=1&keepalive=yes&fexp=24007246%2C24363392&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJZtztTkJKHzWB0QgqTD8flmVlt03vVMXXzKB-jGYcuSAiEAgHE-5AXMxFVHLagDnkMZEmCvKh1MPVaxxO_yR-xJiQ4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPyPP9Zz_woMqDXqUvCQiEDP_i1aBNxoQR8vw8wH2xEDAiBWcOME5z4ZRdI3R-ngF3SqOplE4h_3DwZ-MkYFGEFitQ%3D%3D"
[download] Destination: [MV] BTS(방탄소년단) _ FIRE (불타오르네) [ALj5MKjy2BU].f251.webm
[download] 100% of    4.24MiB in 00:00:02 at 2.09MiB/s
[Merger] Merging formats into "[MV] BTS(방탄소년단) _ FIRE (불타오르네) [ALj5MKjy2BU].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:[MV] BTS(방탄소년단) _ FIRE (불타오르네) [ALj5MKjy2BU].f248.webm' -i 'file:[MV] BTS(방탄소년단) _ FIRE (불타오르네) [ALj5MKjy2BU].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:[MV] BTS(방탄소년단) _ FIRE (불타오르네) [ALj5MKjy2BU].temp.webm'
Deleting original file [MV] BTS(방탄소년단) _ FIRE (불타오르네) [ALj5MKjy2BU].f248.webm (pass -k to keep)
Deleting original file [MV] BTS(방탄소년단) _ FIRE (불타오르네) [ALj5MKjy2BU].f251.webm (pass -k to keep)
```

**Comment by dirkf** [comment]
Does running the command first without `--write-comments` and then with only `--write-comments` work around the expiry? Presumably 790k is an exceptional number of comments.

**Comment by coletdjnz** [comment]
I don't think there is anything we can do about this. I would do as dirkf suggests and download the comments in a separate instance. Alternatively, you could limit how many comments are gathered (see extractor args in README).

**Comment by dirkf** [comment]
I suppose comment collection could be deferred into a custom downloader, but that seems like a lot of trouble for what should be an exceptional situation.

**Comment by jakeogh** [comment]
Would there be unintended consequences to instead downloading the comments last? This one has >5M: https://www.youtube.com/watch?v=9bZkp7q19f0

**Comment by pukkandan** [comment]
> Would there be unintended consequences to instead downloading the comments last?

infojson is written before download, so comments would be unavailable in it this way.
