### ISSUE TITLE
[Crunchyroll] SSL: SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by Kapiroto** [yt-dlp/yt-dlp#7099]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

This problem is happening with some series, it must be because it is allocated on another server perhaps, but most are downloading normally. I tried to use --legacy-server-connect but it didn't work, still with the same problem. To download, I have to make several attempts until I finish.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-U', '--part', '--verbose', '--add-metadata', '--embed-thumbnail', '--convert-thumbnail', 'jpg', '--concurrent-fragments', '10', '--cookies', 'F:/Crunchyroll/Config/cookies.txt', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0', '--output', 'F:/Crunchyroll/Downloads/%(title)s.%(ext)s', '--sub-lang', 'pt-BR', '--write-sub', '--format', 'bestvideo*+bestaudio/best', '--remux-video', 'mkv', '--batch-file', 'xxx']
[debug] Batch file urls: ['https://www.crunchyroll.com/pt-br/rokudos-bad-girls/episode-7-youre-the-key-rokudo-tosuke-895466', 'https://www.crunchyroll.com/pt-br/the-caf-terrace-and-its-goddesses/episode-7-a-year-in-my-life-895358', 'https://www.crunchyroll.com/pt-br/birdie-wing-golf-girls-story-/episode-20-the-rainbow-that-tells-of-victory-895319', 'https://www.crunchyroll.com/pt-br/the-aristocrats-otherworldly-adventure-serving-gods-who-go-too-far/episode-8-the-royal-academy-894859', 'https://www.crunchyroll.com/pt-br/my-clueless-first-friend/episode-8-yukata-jungle-gyms-and-orthopedic-casts-894845']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-05-15-git-2953ebe7b6-full_build-www.gyan.dev (setts), ffprobe 2023-05-15-git-2953ebe7b6-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.crunchyroll.com/pt-br/rokudos-bad-girls/episode-7-youre-the-key-rokudo-tosuke-895466
[generic] episode-7-youre-the-key-rokudo-tosuke-895466: Downloading webpage
[redirect] Following redirect to https://www.crunchyroll.com/pt-br/watch/G50UZ1DZK/youre-the-key-rokudo-tosuke
[crunchyroll] Extracting URL: https://www.crunchyroll.com/pt-br/watch/G50UZ1DZK/youre-the-key-rokudo-tosuke
[crunchyroll] Retrieving main page
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
[crunchyroll] Retrieving signed policy
[crunchyroll] youre-the-key-rokudo-tosuke: Retrieving episode metadata
[crunchyroll] youre-the-key-rokudo-tosuke: Retrieving stream info
[crunchyroll] To get all formats of a hardsub language, use "--extractor-args crunchyrollbeta:hardsub=<language_code or all>". See https://github.com/yt-dlp/yt-dlp#crunchyrollbeta-crunchyroll for more info
[crunchyroll] youre-the-key-rokudo-tosuke: Downloading adaptive_hls HLS manifest
[crunchyroll] youre-the-key-rokudo-tosuke: Downloading JSON metadata
[info] G50UZ1DZK: Downloading subtitles: pt-BR
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] G50UZ1DZK: Downloading 1 format(s): adaptive_hls-8120
Deleting existing file F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.pt-BR.ass
[info] Writing video subtitles to: F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.pt-BR.ass
[debug] Invoking http downloader on "https://v.vrv.co/evs3/02bee2d678560afe23eb5900f68bd08d/assets/0c05e425ca725cc767f2cb393f44eb07_344007.txt?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly92LnZydi5jby9ldnMzLzAyYmVlMmQ2Nzg1NjBhZmUyM2ViNTkwMGY2OGJkMDhkL2Fzc2V0cy8wYzA1ZTQyNWNhNzI1Y2M3NjdmMmNiMzkzZjQ0ZWIwN18zNDQwMDcudHh0IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg0ODkwMDk4fX19XX0_&Signature=UYwRUpbW5Whap1RceLhMkEC~FOxAHKqd6GjhRtTC3bIAj7u-AN25WdUGfcJ4ALk8GwBNDPfameazfRLLESW8QSgzBvfMXxOO9nA0bZqOrkJiznhpEKhSd7w5kU9fIsgjGPTaxLIHB0p8wKW5dC21EOG7Os~8sKOF6uRoGjTql~EYPp9V0pdjsk0tRuy4tn2Pa9-JyX6sr-oKOylXKGkw0T3GFzcX4XztcWdmTheykykU7G4uJ9smRXJh0~S62DGRAZaissh3pbBwPu-GWXAauUeYpE7G~O4bLGo2xaQjGJXij3PCXyINWxR5eVIQ01Umbz9N1t3etLnIIpRcIXvLgQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.pt-BR.ass
[download] 100% of   39.87KiB in 00:00:00 at 314.22KiB/s
[info] Downloading video thumbnail 7 ...
[info] Writing video thumbnail 7 to: F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.jpe
[ThumbnailsConvertor] Converting thumbnail "F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.jpe" to jpg
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -f image2 -pattern_type none -i "file:F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.jpe" -update 1 "-bsf:v" mjpeg2jpeg -movflags "+faststart" "file:F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.jpg"
Deleting original file F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.jpe (pass -k to keep)
[debug] Invoking hlsnative downloader on "https://pl.crunchyroll.com/evs3/02bee2d678560afe23eb5900f68bd08d/assets/0c05e425ca725cc767f2cb393f44eb07_5098427.mp4/index-v1-a1.m3u8?res=1920x1080&Expires=1684892113&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy8wMmJlZTJkNjc4NTYwYWZlMjNlYjU5MDBmNjhiZDA4ZC9hc3NldHMvMGMwNWU0MjVjYTcyNWNjNzY3ZjJjYjM5M2Y0NGViMDdfNTA5ODQyNy5tcDQvaW5kZXgtdjEtYTEubTN1OD9yZXM9MTkyMHgxMDgwIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg0ODkyMTEzfX19XX0_&Signature=qW2WVNkUMbhU6B6WGBztMtXoVmHEM3fTHeZLuI5do1b9dyZtdKUpLlnm3pqdY7YGSV6N5mnF5LUjHzVOJA5vwgxMwJqhO9wt2RxDZ6wplTABnNBYCSDJRj5NVjuN9E7Jkol3ykPMfJRqNumAc4m2ck454blGMYGDFyWzfdHIweBBdWwV85aRrTiSDovOyBK7CSa65XvXguOWFKBhuEHCSuC5GDkZWw8A-GON4frh~dKHdxqbokx8BwzO1BXYvYf1cCqcK2Utidz314s6stYDw5xLAOP-U0ryBuPMhe5qSSVbrsRMMnGfpr2uH7GsXvEdPh8T6tEtIh4bPOyMxnbnrA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 355
[download] Destination: F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4
WARNING: The download speed shown is only of one thread. This is a known issue
[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag306 has already been downloaded
[download]  85.9% of ~   1.38GiB at  538.80MiB/s ETA Unknown (frag 305/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag307 has already been downloaded
[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag308 has already been downloaded
[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag309 has already been downloaded
[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag310 has already been downloaded
[download]  86.2% of ~   1.38GiB at  Unknown B/s ETA Unknown (frag 306/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag312 has already been downloaded
[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag313 has already been downloaded
[download]  86.5% of ~   1.38GiB at  Unknown B/s ETA Unknown (frag 307/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag316 has already been downloaded
[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag315 has already been downloaded
[download]  86.8% of ~   1.38GiB at    3.44GiB/s ETA Unknown (frag 308/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag317 has already been downloaded
[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag314 has already been downloaded
[download]  87.0% of ~   1.38GiB at  Unknown B/s ETA Unknown (frag 309/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag318 has already been downloaded
[download]  87.3% of ~   1.38GiB at    1.88GiB/s ETA Unknown (frag 310/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag319 has already been downloaded
[download]  87.6% of ~   1.38GiB at  Unknown B/s ETA Unknown (frag 311/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag320 has already been downloaded
[download]  87.9% of ~   1.38GiB at  Unknown B/s ETA Unknown (frag 312/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag321 has already been downloaded
[download]  88.2% of ~   1.38GiB at    2.84GiB/s ETA Unknown (frag 313/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag322 has already been downloaded
[download]  88.5% of ~   1.38GiB at  Unknown B/s ETA Unknown (frag 314/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag323 has already been downloaded
[download]  88.7% of ~   1.38GiB at    3.90GiB/s ETA Unknown (frag 315/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag324 has already been downloaded
[download]  89.3% of ~   1.38GiB at    3.02GiB/s ETA Unknown (frag 317/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag326 has already been downloaded
[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag327 has already been downloaded
[download]  90.4% of ~   1.37GiB at    2.92GiB/s ETA Unknown (frag 321/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag330 has already been downloaded
[download]  90.7% of ~   1.37GiB at  Unknown B/s ETA Unknown (frag 322/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag331 has already been downloaded
[download]  91.0% of ~   1.37GiB at    1.82GiB/s ETA Unknown (frag 323/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag332 has already been downloaded
[download]  91.3% of ~   1.37GiB at    3.30GiB/s ETA Unknown (frag 324/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag333 has already been downloaded
[download]  91.5% of ~   1.37GiB at    1.97GiB/s ETA Unknown (frag 325/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag334 has already been downloaded
[download]  91.8% of ~   1.37GiB at  Unknown B/s ETA Unknown (frag 326/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag335 has already been downloaded
[download]  92.1% of ~   1.37GiB at  Unknown B/s ETA Unknown (frag 327/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag336 has already been downloaded
[download]  92.7% of ~   1.37GiB at    3.45GiB/s ETA Unknown (frag 329/355)[download] F:\Crunchyroll\Downloads\Rokudo's Bad Girls Episode 7 – Então, você é a chave, Rokudo Tosuke？.mp4.part-Frag338 has already been downloaded
[download]  98.9% of ~   1.38GiB at    4.58MiB/s ETA 00:00 (frag 351/355)ERROR: SSLV3_ALERT_HANDSHAKE_FAILURE: Try using --legacy-server-connect
Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\utils.py", line 1555, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1615, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2779, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3247, in process_info
  File "yt_dlp\YoutubeDL.py", line 2970, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\hls.py", line 365, in real_download
  File "yt_dlp\downloader\fragment.py", line 503, in download_and_append_fragments
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 437, in result
  File "concurrent\futures\_base.py", line 389, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "yt_dlp\downloader\fragment.py", line 497, in _download_fragment
  File "yt_dlp\downloader\fragment.py", line 469, in download_fragment
  File "yt_dlp\downloader\fragment.py", line 124, in _download_fragment
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\http.py", line 376, in real_download
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1560, in https_open
yt_dlp.utils.YoutubeDLError: SSLV3_ALERT_HANDSHAKE_FAILURE: Try using --legacy-server-connect
```

**Comment by credo99** [comment]
I get the same error on vimeo.com:

Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 1514, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1709, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1768, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2897, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3345, in process_info
  File "yt_dlp\YoutubeDL.py", line 3084, in dl
  File "yt_dlp\downloader\common.py", line 461, in download
  File "yt_dlp\downloader\dash.py", line 60, in real_download
  File "yt_dlp\downloader\fragment.py", line 390, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 511, in download_and_append_fragments
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 437, in result
  File "concurrent\futures\_base.py", line 389, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "yt_dlp\downloader\fragment.py", line 505, in _download_fragment
  File "yt_dlp\downloader\fragment.py", line 477, in download_fragment
  File "yt_dlp\downloader\fragment.py", line 129, in _download_fragment
  File "yt_dlp\downloader\common.py", line 461, in download
  File "yt_dlp\downloader\http.py", line 377, in real_download
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3863, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils\_utils.py", line 1519, in https_open
yt_dlp.utils.YoutubeDLError: SSLV3_ALERT_HANDSHAKE_FAILURE: Try using --legacy-server-connect

on:

yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)

using:

--verbose --windows-filenames --fragment-retries 50 --concurrent-fragments 10 --no-check-certificate --force-ipv4 --legacy-server-connect

The error occurs since beginning of August 2023 with or without --legacy-server-connect

**Comment by Jules-A** [comment]
>--verbose --windows-filenames --fragment-retries 50 --concurrent-fragments 10 --no-check-certificate --force-ipv4 --legacy-server-connect

Try removing --no-check-certificate, afaik it was never useful for CR.

**Comment by franontanaya** [comment]
Same on Vimeo. I think it's easier to reproduce when fetching large videos or multiple videos in a row.

**Comment by PeterPlucinski** [comment]
I was able to get passed this issue by 1) getting the latest version, currently "2023.07.06", 2) removing flag "--legacy-server-connect" which oddly is the suggested solution. This is for vimeo and and I only use "--merge-output-format" and "-o" flags

**Comment by dmerces** [comment]
> > --verbose --windows-filenames --fragment-retries 50 --concurrent-fragments 10 --no-check-certificate --force-ipv4 --legacy-server-connect
> 
> Try removing --no-check-certificate, afaik it was never useful for CR. EDIT: Not sure about Vimeo.

Works on Vimeo, even with "--no-check-certificate" flag. Tks

**Comment by SiddharthMant** [comment]
Still encountering this issue. Tried latest version. Doesn't make a difference whether I use the --no-check-certificate or not. Didn't use --legacy-server-connect.

```
yt-dlp "{url}" --output "{file_name}.mkv" -P "temp:{download_video_temp_dir}" -P "home:{folder_path}" --no-check-certificate --force-ipv4 --sleep-requests 1 --sleep-interval 5 --max-sleep-interval 30 --embed-metadata --embed-thumbnail --check-formats --concurrent-fragments 3 --merge-output-format "mkv" --throttled-rate 100K --format "(bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec^=vp09.02][height>=4320][fps>30]/bestvideo[vcodec^=vp09.00][height>=4320][fps>30]/bestvideo[vcodec^=avc1][height>=4320][fps>30]/bestvideo[height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=4320]/bestvideo[vcodec^=vp09.02][height>=4320]/bestvideo[vcodec^=vp09.00][height>=4320]/bestvideo[vcodec^=avc1][height>=4320]/bestvideo[height>=4320]/bestvideo[vcodec^=av01][height>=2880][fps>30]/bestvideo[vcodec^=vp09.02][height>=2880][fps>30]/bestvideo[vcodec^=vp09.00][height>=2880][fps>30]/bestvideo[vcodec^=avc1][height>=2880][fps>30]/bestvideo[height>=2880][fps>30]/bestvideo[vcodec^=av01][height>=2880]/bestvideo[vcodec^=vp09.02][height>=2880]/bestvideo[vcodec^=vp09.00][height>=2880]/bestvideo[vcodec^=avc1][height>=2880]/bestvideo[height>=2880]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec^=vp09.02][height>=2160][fps>30]/bestvideo[vcodec^=vp09.00][height>=2160][fps>30]/bestvideo[vcodec^=avc1][height>=2160][fps>30]/bestvideo[height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=2160]/bestvideo[vcodec^=vp09.02][height>=2160]/bestvideo[vcodec^=vp09.00][height>=2160]/bestvideo[vcodec^=avc1][height>=2160]/bestvideo[height>=2160]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec^=vp09.02][height>=1440][fps>30]/bestvideo[vcodec^=vp09.00][height>=1440][fps>30]/bestvideo[vcodec^=avc1][height>=1440][fps>30]/bestvideo[height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1440]/bestvideo[vcodec^=vp09.02][height>=1440]/bestvideo[vcodec^=vp09.00][height>=1440]/bestvideo[vcodec^=avc1][height>=1440]/bestvideo[height>=1440]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec^=vp09.02][height>=1080][fps>30]/bestvideo[vcodec^=vp09.00][height>=1080][fps>30]/bestvideo[vcodec^=avc1][height>=1080][fps>30]/bestvideo[height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec^=vp09.02][height>=1080]/bestvideo[vcodec^=vp09.00][height>=1080]/bestvideo[vcodec^=avc1][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec^=vp09.02][height>=720][fps>30]/bestvideo[vcodec^=vp09.00][height>=720][fps>30]/bestvideo[vcodec^=avc1][height>=720][fps>30]/bestvideo[height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec^=vp09.02][height>=720]/bestvideo[vcodec^=vp09.00][height>=720]/bestvideo[vcodec^=avc1][height>=720]/bestvideo[height>=720]/bestvideo[vcodec^=av01][height>=480][fps>30]/bestvideo[vcodec^=vp09.02][height>=480][fps>30]/bestvideo[vcodec^=vp09.00][height>=480][fps>30]/bestvideo[vcodec^=avc1][height>=480][fps>30]/bestvideo[height>=480][fps>30]/bestvideo[vcodec^=av01][height>=480]/bestvideo[vcodec^=vp09.02][height>=480]/bestvideo[vcodec^=vp09.00][height>=480]/bestvideo[vcodec^=avc1][height>=480]/bestvideo[height>=480]/bestvideo[vcodec^=av01][height>=360][fps>30]/bestvideo[vcodec^=vp09.02][height>=360][fps>30]/bestvideo[vcodec^=vp09.00][height>=360][fps>30]/bestvideo[vcodec^=avc1][height>=360][fps>30]/bestvideo[height>=360][fps>30]/bestvideo[vcodec^=av01][height>=360]/bestvideo[vcodec^=vp09.02][height>=360]/bestvideo[vcodec^=vp09.00][height>=360]/bestvideo[vcodec^=avc1][height>=360]/bestvideo[height>=360]/bestvideo[vcodec^=avc1][height>=240][fps>30]/bestvideo[vcodec^=av01][height>=240][fps>30]/bestvideo[vcodec^=vp09.02][height>=240][fps>30]/bestvideo[vcodec^=vp09.00][height>=240][fps>30]/bestvideo[height>=240][fps>30]/bestvideo[vcodec^=avc1][height>=240]/bestvideo[vcodec^=av01][height>=240]/bestvideo[vcodec^=vp09.02][height>=240]/bestvideo[vcodec^=vp09.00][height>=240]/bestvideo[height>=240]/bestvideo[vcodec^=avc1][height>=144][fps>30]/bestvideo[vcodec^=av01][height>=144][fps>30]/bestvideo[vcodec^=vp09.02][height>=144][fps>30]/bestvideo[vcodec^=vp09.00][height>=144][fps>30]/bestvideo[height>=144][fps>30]/bestvideo[vcodec^=avc1][height>=144]/bestvideo[vcodec^=av01][height>=144]/bestvideo[vcodec^=vp09.02][height>=144]/bestvideo[vcodec^=vp09.00][height>=144]/bestvideo[height>=144]/bestvideo)+(bestaudio[acodec^=opus]/bestaudio)/best"
```

**Comment by 151SoGood** [comment]
The above resolves " SSLV3_ALERT_HANDSHAKE_FAILURE" errors, but I keep getting these errors for Vimeo videos - any ideas? It's when yt-dlp (or basically ffmpeg) tries to merge the .m4a (audio) and .mp4 (video) - have tired to manually do this via various ffmpeg commands/parameters to no avail. Is it some new Vimeo encryption?

[mov,mp4,m4a,3gp,3g2,mj2 @ 000000000289ae00] **Could not find codec parameters for stream 0 (Audio: none (Opus / 0x7375704F), 48000 Hz, 1 channels, 96 kb/s): unknown codec**

ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3439, in process_info
  File "yt_dlp\YoutubeDL.py", line 3621, in post_process
  File "yt_dlp\YoutubeDL.py", line 3603, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3581, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 837, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 329, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 367, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

**Comment by credo99** [comment]
Error stil occuring randomly on vimeo on videos larger than 1 hour that also need A-V formats merging (standard vimeo formats 240p/360p/etc...have  much lower rate of error). --legacy-server-connect does not help. --fragment-retries also does not help. The only thing one can do is set a --concurrent-fragments to higher values (10-20...that set on fire the network card and the computer) and have the fingers crossed that the download will speed up so it would hold on unintrerupted until a SSLV3_ALERT_HANDSHAKE_FAILURE occurs. But stil it might need 2-3 retries (especially in morning hours european timezones).

**Comment by dreamflasher** [comment]
I'm on Windows and getting this error, the last comment sounds like advertising spam for Ubuntu Pro?

**Comment by jcn50** [comment]
> I'm on Windows and getting this error, the last comment sounds like advertising spam for Ubuntu Pro?

meh, it was marked as spam bec I had put a link to join the program... Once I have done it my openssl + python libraries got updated.

If you are on Windows: make sure you have run Windows updates (to have your root SSL certificates up-to-date). I am not sure how `yt-dlp` is running on Windows: it seems to be a packaged `.exe`, I have no idea how the SSL/Python is packaged in there~
