### ISSUE TITLE
Request for support vkplay.live

### ISSUE THREAD

**Issue by krasnh** [yt-dlp/yt-dlp#7107]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://vkplay.live/zitsmann/record/f5e6e3b5-dc52-4d14-965d-0680dd2882da

### Provide a description that is worded well enough to be understood

I want to ask you to add support for vkplay.live. Interested in recordings of past streams. Link example https://vkplay.live/zitsmann/record/f5e6e3b5-dc52-4d14-965d-0680dd2882da.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
% yt-dlp -vU -f b 'https://vkplay.live/zitsmann/record/f5e6e3b5-dc52-4d14-965d-0680dd2882da'
[debug] Command-line config: ['-vU', '-f', 'b', 'https://vkplay.live/zitsmann/record/f5e6e3b5-dc52-4d14-965d-0680dd2882da']
[debug] User config "/home/live/.config/yt-dlp/config": ['--cookies-from-browser=firefox:jvjddxlz.default-1626613399792']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (linux_exe)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.2.0-pf1-x86_64-with-glibc2.36 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: certifi-2022.06.15, no_Cryptodome-None, sqlite3-2.6.0
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/live/.mozilla/firefox/jvjddxlz.default-1626613399792/cookies.sqlite"
[Cookies] Extracted 1480 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 81d59ca9ea80a5c9f9383d5c3631e815cc69d9fb52581d80ffb504258c65c4a9
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://vkplay.live/zitsmann/record/f5e6e3b5-dc52-4d14-965d-0680dd2882da
[generic] f5e6e3b5-dc52-4d14-965d-0680dd2882da: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] f5e6e3b5-dc52-4d14-965d-0680dd2882da: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://vkplay.live/zitsmann/record/f5e6e3b5-dc52-4d14-965d-0680dd2882da
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp/extractor/common.py", line 694, in extract
  File "yt_dlp/extractor/generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vkplay.live/zitsmann/record/f5e6e3b5-dc52-4d14-965d-0680dd2882da
```

**Comment by krasnh** [comment]
Checked, now it works. Thank you.

```sh
$ ./yt-dlp -f b 'https://vkplay.live/zitsmann/record/f5e6e3b5-dc52-4d14-965d-0680dd2882da'
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 1621 cookies from firefox
[VKPlay] Extracting URL: https://vkplay.live/zitsmann/record/f5e6e3b5-dc52-4d14-965d-0680dd2882da
[VKPlay] f5e6e3b5-dc52-4d14-965d-0680dd2882da: Downloading JSON metadata
[VKPlay] f5e6e3b5-dc52-4d14-965d-0680dd2882da: Downloading m3u8 information
[VKPlay] f5e6e3b5-dc52-4d14-965d-0680dd2882da: Downloading MPD manifest
[info] f5e6e3b5-dc52-4d14-965d-0680dd2882da: Downloading 1 format(s): hls-18689
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1061
[download] Destination: Atomic Heart (пробуем!) спасибо подписчику EKZO! [f5e6e3b5-dc52-4d14-965d-0680dd2882da].mp4
[download]   0.0% of ~  28.15GiB at    1.98MiB/s ETA 04:02:18 (frag 0/1061)
```
