### ISSUE TITLE
[Broken] MTV Network (Paramount etc)

### ISSUE THREAD

**Issue by CrazyOldWizard** [yt-dlp/yt-dlp#713]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\ytdl>yt-dlp.exe https://www.paramountnetwork.com/episodes/g6xkx0/bar-rescue-remembering-billy-season-8-ep-11 --cookies br.txt --verbose
[debug] Command-line config: ['https://www.paramountnetwork.com/episodes/g6xkx0/bar-rescue-remembering-billy-season-8-ep-11', '--cookies', 'br.txt', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg N-90578-g02ae52db87, ffprobe N-90578-g02ae52db87
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 6.226.7.98 (US) as X-Forwarded-For
[debug] [ParamountNetwork] Extracting URL: https://www.paramountnetwork.com/episodes/g6xkx0/bar-rescue-remembering-billy-season-8-ep-11
[ParamountNetwork] bar-rescue-remembering-billy-season-8-ep-11: Downloading webpage
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1199, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1224, in __extract_info
  File "yt_dlp\extractor\common.py", line 575, in extract
  File "yt_dlp\extractor\mtv.py", line 321, in _real_extract
  File "yt_dlp\extractor\mtv.py", line 314, in _extract_mgid
TypeError: 'NoneType' object is not subscriptable

```

## Description

This site broke about a week ago. Normally, I don't even need to use cookies or even be logged in.  I have tried downloaded with cookies and without.  It doesn't seem to help.  I don't know much about python, but looking at the lines of code in the error, it looks like maybe something on the site changed.

**Comment by Ashish0804** [comment]
`[debug] Using fake IP 6.226.7.98 (US) as X-Forwarded-For`
You are not in USA?
also see this https://github.com/yt-dlp/yt-dlp/pull/711

**Comment by CrazyOldWizard** [comment]
> `[debug] Using fake IP 6.226.7.98 (US) as X-Forwarded-For`
> You are not in USA?
> also see this #711

I didn't see #711 - sorry if this is a duplicate. That issue is referring to paramount+ and mine is paramount.com _(not sure if in the background they are the same or different, but the domains are)_ If they are the same, and this is fixed, then I will wait for the next release and try again.

I am in the US and I'm not using any vpn.

**Comment by Ashish0804** [comment]
it's not related to #711 then,
Paramount network is different.
And the extractor seems to be broken. 
The `mgid` extraction is broken now, most proly the site changed

**Comment by CHJ85** [comment]
Just to avoid people's confusion, not related to Paramount Plus. That site works just fine.

**Comment by ohmybahgosh** [comment]
Can confirm this bug exists, and also can confirm has nothing to do with paramount plus :)

**Comment by Sipherdrakon** [comment]
Might want to edit the title to paramountnetwork.com, paramount.com doesn't host any videos.

**Comment by ohmybahgosh** [comment]
#### MTV.com debug log shows that the issue seems to pertain to the mgid extraction:

```bash
[debug] User config file: /root/yt-dlp.conf
[debug] User config: ['--retries', '5', '--extractor-retries', '5', '--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-N50', '--geo-verification-proxy', 'PROXY_IP:PORT', '-f', 'bv+ba/b', '--embed-metadata', '--embed-thumbnail', '--no-part']
[debug] Command-line config: ['--verbose', '--print-json', '--print-traffic', 'https://www.paramountnetwork.com/episodes/l9qvyb/bar-rescue-behind-the-8-ball-season-8-ep-9']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.24.2 (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-8-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg v1.27-6-ge0542c4, ffprobe v1.27-6-ge0542c4, phantomjs 1.9.2, rtmpdump 2.4
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 6.48.49.42 (US) as X-Forwarded-For
[debug] [ParamountNetwork] Extracting URL: https://www.paramountnetwork.com/episodes/l9qvyb/bar-rescue-behind-the-8-ball-season-8-ep-9
[ParamountNetwork] bar-rescue-behind-the-8-ball-season-8-ep-9: Downloading webpage
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1239, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/mtv.py", line 321, in _real_extract
    mgid = self._extract_mgid(webpage)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/mtv.py", line 314, in _extract_mgid
    mgid = video_player['props']['media']['video']['config']['uri']
TypeError: 'NoneType' object is not subscriptable 
```

#### After peeking at the MTV extractor, the comment provides two examples of what the mgid url structure should be:

```python
   def _extract_mgid(self, webpage):
        try:
            # the url can be http://media.mtvnservices.com/fb/{mgid}.swf
            # or http://media.mtvnservices.com/{mgid}
            og_url = self._og_search_video_url(webpage)
            mgid = url_basename(og_url)
            if mgid.endswith('.swf'):
                mgid = mgid[:-4]
        except RegexNotFoundError:
            mgid = None

        if mgid is None or ':' not in mgid:
            mgid = self._search_regex(
                [r'data-mgid="(.*?)"', r'swfobject\.embedSWF\(".*?(mgid:.*?)"'],
                webpage, 'mgid', default=None)

        if not mgid:
            sm4_embed = self._html_search_meta(
                'sm4:video:embed', webpage, 'sm4 embed', default='')
            mgid = self._search_regex(
                r'embed/(mgid:.+?)["\'&?/]', sm4_embed, 'mgid', default=None)

        if not mgid:
            mgid = self._extract_triforce_mgid(webpage)

        if not mgid:
            data = self._parse_json(self._search_regex(
                r'__DATA__\s*=\s*({.+?});', webpage, 'data'), None)
            main_container = self._extract_child_with_type(data, 'MainContainer')
            ab_testing = self._extract_child_with_type(main_container, 'ABTesting')
            video_player = self._extract_child_with_type(ab_testing or main_container, 'VideoPlayer')
            mgid = video_player['props']['media']['video']['config']['uri']

        return mgid
```

#### The mgid url has changed, and The NEW mgid url is:

```https://media.mtvnservices.com/pmt/e1/access/index.html?uri=mgid:arc:episode:mtv.com:ba4267a1-816a-11eb-8774-70df2f866ace&configtype=edge&ref=https://www.mtv.com/episodes/t6ghmp/ridiculousness-lauren-riihimaki-season-21-ep-1
```

##### I sadly am not super fluent in python, but I am with regex and bash... I'll try and reverse engineer what the python regex format needs to be, but hopefully someone more adept at modifying the extractor will beat me to it.

**Comment by Sipherdrakon** [comment]
So I tried adding:
```
    def _get_feed_query(self, uri):
        return {
            'feed': 'vh1_arc_player_prime',
            'mgid': uri,
        }

```
to the VH1 extractor and it yielded this result

```
__main__.py -F https://www.vh1.com/episodes/g2hg2n/love-hip-hop-atlanta-oh-baby-season-10-ep-3 --verbose
[debug] Command-line config: ['-F', 'https://www.vh1.com/episodes/g2hg2n/love-hip-hop-atlanta-oh-baby-season-10-ep-3', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.24 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 6493eb1e6
[debug] Python version 3.9.4 (CPython 64bit) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] Using fake IP 6.12.174.90 (US) as X-Forwarded-For
[debug] [vh1.com] Extracting URL: https://www.vh1.com/episodes/g2hg2n/love-hip-hop-atlanta-oh-baby-season-10-ep-3
[vh1.com] love-hip-hop-atlanta-oh-baby-season-10-ep-3: Downloading webpage
[vh1.com] e6f6afa2-daf6-11eb-8774-70df2f866ace: Downloading info
ERROR: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "D:\yt-dlp\yt_dlp\extractor\common.py", line 679, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "D:\yt-dlp\yt_dlp\YoutubeDL.py", line 3158, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

I did try a curl request that got me the same type of information that @ohmybahgosh got with his curl request but I don't know enough about python to see if this is the same request being made by yt-dlp when getting the information.

**Comment by ohmybahgosh** [comment]
My apologies to anyone urgently waiting for a fix lol, I didn't have time today to dig in to this more!  Hoping tomorrow I can test a couple things on it!

**Comment by Sipherdrakon** [comment]
All good bro, I actually got VH1 to work, now working on ParamountNetwork, hopefully. :-P It was actually super simple. They didn't change the mgid url that I can tell as a part of the code already points to that mgid url

```
    def _get_feed_url(self, uri):
        video_id = self._id_from_uri(uri)
        config = self._download_json(
            'http://media.mtvnservices.com/pmt/e1/access/index.html?uri=%s&configtype=edge' % uri, video_id)
        return self._remove_template_parameter(config['feedWithQueryParams'])
```
But I will try my luck with ParamountNetwork as it is not the same error and thus the solution to one doesn't work for the other.

**Comment by Sipherdrakon** [comment]
So I tried out everything else I could think of that uses the MTVExtractor and that I had access to, and from what I can tell the only one that I still can't get to work is paramountnetwork.com. :-(

**Comment by Sipherdrakon** [comment]
Did some digging around in paramountnetwork.com and it's not using mtvnservices.com anymore now it using https://topaz.dai.viacomcbs.digital/ so pretty sure that might need a much larger revamp than VH1 did. That's well above my expertise.

**Comment by ohmybahgosh** [comment]
# UPDATE:
>Ok, so I finally have a moment to dig in on my actual desktop, instead of my damn phone lol..
>
>I wasn't paying close enough attention on my previous [comment](https://github.com/yt-dlp/yt-dlp/issues/713#issuecomment-904738163) (_Shocker that doing it on my phone caused confusion_), as I using an MTV EP URL for one part and a ParamountNetwork EP URL for another...

###  This time we'll solely focus on ParamountNetwork, as MTV is working just fine.

### Episode URL:
`https://www.paramountnetwork.com/episodes/yc08fw/bar-rescue-wreck-it-ralph-season-8-ep-12`  
### Digging Thru Network Requests..
#### The FIRST occurence of the mgid appears in the following GET request URL:  
`https://topaz.viacomcbs.digital/topaz/api/mgid:arc:episode:paramountnetwork.com:f6df7c41-beac-11eb-8774-70df2f866ace/mica.json?ssus=CENSORED_BY_OHMYBAHGOSH&region=US&clientPlatform=mobile`  
#### 
### Let's CURL it..  
#### CURL Command (CENSORED OUT POTENTIALLY PRIVATE TOKENS/CRAP):  
```bash
curl 'https://topaz.viacomcbs.digital/topaz/api/mgid:arc:episode:paramountnetwork.com:f6df7c41-beac-11eb-8774-70df2f866ace/mica.json?ssus=CENSORED_BY_OHMYBAHGOSH&region=US&clientPlatform=mobile' 
-H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0' 
-H 'Accept: */*' 
-H 'Accept-Language: en-US,en;q=0.5' --compressed 
-H 'Referer: https://www.paramountnetwork.com/' 
-H 'Content-Type: application/json' 
-H 'X-VIA-TVE-MEDIATOKEN: CENSORED_BY_OHMYBAHGOSH' 
-H 'Origin: https://www.paramountnetwork.com' 
-H 'Connection: keep-alive' 
-H 'Sec-Fetch-Dest: empty' 
-H 'Sec-Fetch-Mode: cors' 
-H 'Sec-Fetch-Site: cross-site' 
-H 'Pragma: no-cache' 
-H 'Cache-Control: no-cache'
```  
#### Pretty Printed JSON Output From CURL (CENSORED OUT POTENTIALLY PRIVATE TOKENS/CRAP):  
```json
{
  "$schema": "https://player.mtvnservices.com/mica/schemas/mica-schema-1.0.5.json",
  "version": "1.0.5",
  "documentid": "125b89d7-adcd-4c87-a6e4-e3c4ba5bd0de",
  "originationdate": "2021-08-25T08:12:45Z",
  "stitchedstream": {
    "source": "https://topaz.viacomcbs.digital/h/a/CENSORED_BY_OHMYBAHGOSH/master.m3u8?mgid=mgid:arc:episode:paramountnetwork.com:f6df7c41-beac-11eb-8774-70df2f866ace&ts=1628881291-2&pthash=823dd4587cf09a96b1b8cd8b998d4ed631d71797&hdnts=exp=1629879465~acl=/h/a/CENSORED_BY_OHMYBAHGOSH/*~hmac=CENSORED_BY_OHMYBAHGOSH",
    "sessiontoken": null,
    "iframe": false,
    "adstitchingprovider": "googledai",
    "cdn": "ns1",
    "streamingtype": "vod",
    "minrenditionheight": 216,
    "maxrenditionheight": 1080,
    "minrenditionbitrate": 177,
    "maxrenditionbitrate": 11454,
    "renditioncount": 7,
    "duration": "00:41:29.324"
  },
  "content": [
    {
      "id": "mgid:arc:episode:paramountnetwork.com:f6df7c41-beac-11eb-8774-70df2f866ace",
      "chapters": [
        {
          "sequence": 1,
          "id": "mgid:arc:showvideo:paramountnetwork.com:b374ce39-d84f-4755-821d-e01f0103e859",
          "beacons": [],
          "overlays": [
            {
              "format": "png",
              "height": 42,
              "width": 42,
              "source": "http://mtv.mtvnimages.com/uri/mgid:file:gsp:mtvncorpstor:/centralized/ratings/TV14.png",
              "xpercent": 3,
              "ypercent": 3,
              "streamoffset": "00:00:00.000",
              "contentoffset": "00:00:00.000",
              "duration": "00:00:15.000"
            }
          ],
          "duration": "00:00:02.962",
          "streamoffset": "00:00:00.000",
          "contentoffset": "00:00:00.000"
        },
        {
          "sequence": 2,
          "id": "mgid:arc:showvideo:paramountnetwork.com:f4534cd3-7065-4c9a-8a23-427296f82f83",
          "beacons": [],
          "overlays": [
            {
              "format": "png",
              "height": 42,
              "width": 42,
              "source": "http://mtv.mtvnimages.com/uri/mgid:file:gsp:mtvncorpstor:/centralized/ratings/TV14.png",
              "xpercent": 3,
              "ypercent": 3,
              "streamoffset": "00:00:02.962",
              "contentoffset": "00:00:02.962",
              "duration": "00:00:15.000"
            }
          ],
          "duration": "00:04:07.456",
          "streamoffset": "00:00:02.962",
          "contentoffset": "00:00:02.962"
        },
        {
          "sequence": 3,
          "id": "mgid:arc:showvideo:paramountnetwork.com:7ed9475e-c594-4708-a3c8-f625036474f3",
          "beacons": [],
          "overlays": [
            {
              "format": "png",
              "height": 42,
              "width": 42,
              "source": "http://mtv.mtvnimages.com/uri/mgid:file:gsp:mtvncorpstor:/centralized/ratings/TV14.png",
              "xpercent": 3,
              "ypercent": 3,
              "streamoffset": "00:04:10.418",
              "contentoffset": "00:04:10.418",
              "duration": "00:00:15.000"
            }
          ],
          "duration": "00:00:01.627",
          "streamoffset": "00:04:10.418",
          "contentoffset": "00:04:10.418"
        },
        {
          "sequence": 4,
          "id": "mgid:arc:showvideo:paramountnetwork.com:e6cfb5b7-433f-40db-a502-10e90a483af6",
          "beacons": [],
          "overlays": [
            {
              "format": "png",
              "height": 42,
              "width": 42,
              "source": "http://mtv.mtvnimages.com/uri/mgid:file:gsp:mtvncorpstor:/centralized/ratings/TV14.png",
              "xpercent": 3,
              "ypercent": 3,
              "streamoffset": "00:04:12.045",
              "contentoffset": "00:04:12.045",
              "duration": "00:00:15.000"
            }
          ],
          "duration": "00:07:53.724",
          "streamoffset": "00:04:12.045",
          "contentoffset": "00:04:12.045"
        },
        {
          "sequence": 5,
          "id": "mgid:arc:showvideo:paramountnetwork.com:7abe5a2c-1173-48c5-90e5-ce0199991e33",
          "beacons": [],
          "overlays": [
            {
              "format": "png",
              "height": 42,
              "width": 42,
              "source": "http://mtv.mtvnimages.com/uri/mgid:file:gsp:mtvncorpstor:/centralized/ratings/TV14.png",
              "xpercent": 3,
              "ypercent": 3,
              "streamoffset": "00:12:05.769",
              "contentoffset": "00:12:05.769",
              "duration": "00:00:15.000"
            }
          ],
          "duration": "00:07:00.045",
          "streamoffset": "00:12:05.769",
          "contentoffset": "00:12:05.769"
        },
        {
          "sequence": 6,
          "id": "mgid:arc:showvideo:paramountnetwork.com:ea2a5d46-7cce-4848-816d-59a2c853912d",
          "beacons": [],
          "overlays": [
            {
              "format": "png",
              "height": 42,
              "width": 42,
              "source": "http://mtv.mtvnimages.com/uri/mgid:file:gsp:mtvncorpstor:/centralized/ratings/TV14.png",
              "xpercent": 3,
              "ypercent": 3,
              "streamoffset": "00:19:05.814",
              "contentoffset": "00:19:05.814",
              "duration": "00:00:15.000"
            }
          ],
          "duration": "00:08:46.818",
          "streamoffset": "00:19:05.814",
          "contentoffset": "00:19:05.814"
        },
        {
          "sequence": 7,
          "id": "mgid:arc:showvideo:paramountnetwork.com:ae20b101-08f5-4e3e-b7fc-4c6dfa9c1a7e",
          "beacons": [],
          "overlays": [
            {
              "format": "png",
              "height": 42,
              "width": 42,
              "source": "http://mtv.mtvnimages.com/uri/mgid:file:gsp:mtvncorpstor:/centralized/ratings/TV14.png",
              "xpercent": 3,
              "ypercent": 3,
              "streamoffset": "00:27:52.632",
              "contentoffset": "00:27:52.632",
              "duration": "00:00:15.000"
            }
          ],
          "duration": "00:07:33.203",
          "streamoffset": "00:27:52.632",
          "contentoffset": "00:27:52.632"
        },
        {
          "sequence": 8,
          "id": "mgid:arc:showvideo:paramountnetwork.com:3ce5be3e-320a-475a-b812-e828a47518e4",
          "beacons": [],
          "overlays": [
            {
              "format": "png",
              "height": 42,
              "width": 42,
              "source": "http://mtv.mtvnimages.com/uri/mgid:file:gsp:mtvncorpstor:/centralized/ratings/TV14.png",
              "xpercent": 3,
              "ypercent": 3,
              "streamoffset": "00:35:25.835",
              "contentoffset": "00:35:25.835",
              "duration": "00:00:15.000"
            }
          ],
          "duration": "00:05:33.500",
          "streamoffset": "00:35:25.835",
          "contentoffset": "00:35:25.835"
        },
        {
          "sequence": 9,
          "id": "mgid:arc:showvideo:paramountnetwork.com:2195a5aa-12f7-47ea-85e2-13e5a40838d7",
          "beacons": [],
          "overlays": [
            {
              "format": "png",
              "height": 42,
              "width": 42,
              "source": "http://mtv.mtvnimages.com/uri/mgid:file:gsp:mtvncorpstor:/centralized/ratings/TV14.png",
              "xpercent": 3,
              "ypercent": 3,
              "streamoffset": "00:40:59.335",
              "contentoffset": "00:40:59.335",
              "duration": "00:00:15.000"
            }
          ],
          "duration": "00:00:29.989",
          "streamoffset": "00:40:59.335",
          "contentoffset": "00:40:59.335"
        }
      ],
      "adbreaks": [],
      "duration": "00:41:29.324"
    }
  ],
  "imasdk": {
    "cmsid": "2566851",
    "vid": "mgid:arc:episode:paramountnetwork.com:f6df7c41-beac-11eb-8774-70df2f866ace",
    "authtoken": "cmsid=2566851~exp=1629879465~vid=mgid:arc:episode:paramountnetwork.com:f6df7c41-beac-11eb-8774-70df2f866ace~hmac=CENSORED_BY_OHMYBAHGOSH",
    "freewheelparams": {
      "imafw_csid": "vcbs_paramount_mobile_web_vod",
      "imafw__fw_coppa": "0",
      "imafw__fw_h_user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0",
      "imafw__fw_vcid2": "7bd18d90-1bf2-4a35-9a6e-da1793a15425",
      "imafw__vmn_ar": "{authrequired}",
      "imafw__fw_ae": "{mvpdname}",
      "imafw__fw_is_lat": "{vmnlat}",
      "imafw_tsla": "80",
      "imafw__fw_playid": "{playid}",
      "imafw_fms_vcid2type": "userid",
      "imafw_fms_userid": "7bd18d90-1bf2-4a35-9a6e-da1793a15425"
    },
    "freewheelurl": "https://7f077.v.fwmrm.net/ad/g/1?vprn=125b89d7-adcd-4c87-a6e4-e3c4ba5bd0de&flag=+dtrd+sync+qtcb+emcr+aeti+sltp+fbad+scpv+slcb+exvt&resp=vmap1+vast4&metr=1023&csid=vcbs_paramount_mobile_web_vod&asnw=520311&caid=CENSORED_BY_OHMYBAHGOSH&nw=520311&vdur=2489&prof=520311:GoogleDAICSAI_v01&ssnw=CENSORED_BY_OHMYBAHGOSH;tsla=80&_fw_ae={mvpdname}&_vmn_ar={authrequired}&_fw_h_user_agent=Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0&_fw_vcid2={ssus}&_fw_ssai=true&_fw_h_referer={referer}&imafw__fw_vcid2=7bd18d90-1bf2-4a35-9a6e-da1793a15425&imafw_fms_vcid2type=userid&imafw_fms_userid=CENSORED_BY_OHMYBAHGOSH;slid=preroll1&tpcl=preroll&ptgt=a&cpsq=1&tpos=0;slid=midroll01&tpcl=midroll&ptgt=a&cpsq=1&tpos=2;slid=midroll11&tpcl=midroll&ptgt=a&cpsq=2&tpos=249;slid=midroll21&tpcl=midroll&ptgt=a&cpsq=3&tpos=250;slid=midroll31&tpcl=midroll&ptgt=a&cpsq=4&tpos=723;slid=midroll41&tpcl=midroll&ptgt=a&cpsq=5&tpos=1143;slid=midroll51&tpcl=midroll&ptgt=a&cpsq=6&tpos=1669;slid=midroll61&tpcl=midroll&ptgt=a&cpsq=7&tpos=2122;slid=midroll71&tpcl=midroll&ptgt=a&cpsq=8&tpos=2455"
  },
  "thumbnails": {
    "webvtt": {
      "aspectratio": "16:9",
      "urltemplate": "https://topaz.viacomcbs.digital/h/a/CENSORED_BY_OHMYBAHGOSH/thumbs-{size}.vtt?mgid=mgid:arc:episode:paramountnetwork.com:f6df7c41-beac-11eb-8774-70df2f866ace&ts=1628881291-2&pthash=823dd4587cf09a96b1b8cd8b998d4ed631d71797&hdnts=exp=1629879465~acl=/h/a/CENSORED_BY_OHMYBAHGOSH/*~hmac=CENSORED_BY_OHMYBAHGOSH",
      "small": "160x90",
      "large": "320x180"
    }
  }
}
```  
### The JSON Dump contains a Master M3U8 URL:  
```json
{
  "$schema": "https://player.mtvnservices.com/mica/schemas/mica-schema-1.0.5.json",
  "version": "1.0.5",
  "documentid": "125b89d7-adcd-4c87-a6e4-e3c4ba5bd0de",
  "originationdate": "2021-08-25T08:12:45Z",
  "stitchedstream": {
    "source": "https://topaz.viacomcbs.digital/h/a/CENSORED_BY_OHMYBAHGOSH/master.m3u8?mgid=mgid:arc:episode:paramountnetwork.com:f6df7c41-beac-11eb-8774-70df2f866ace&ts=1628881291-2&pthash=823dd4587cf09a96b1b8cd8b998d4ed631d71797&hdnts=exp=1629879465~acl=/h/a/CENSORED_BY_OHMYBAHGOSH/*~hmac=CENSORED_BY_OHMYBAHGOSH",
    "sessiontoken": null,
    "iframe": false,
    "adstitchingprovider": "googledai",
    "cdn": "ns1",
    "streamingtype": "vod",
    "minrenditionheight": 216,
    "maxrenditionheight": 1080,
    "minrenditionbitrate": 177,
    "maxrenditionbitrate": 11454,
    "renditioncount": 7,
    "duration": "00:41:29.324"
  }
  ```

  #### That Master M3U8 Downloads via yt-dlp (The Session Token Expires Very Quickly FYI):  
  ```bash
  [debug] User config file: /root/yt-dlp.conf
[debug] User config: ['--retries', '3', '--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-N40', '--cookies-from-browser', 'chrome:/root/.config/google-chrome-beta/Default', '-f', 'bv+ba/b', '--add-metadata', '--write-all-thumbnails', '--embed-thumbnail']
[debug] Command-line config: ['--verbose', '--simulate', 'https://topaz.viacomcbs.digital/h/a/CENSORED_BY_OHMYBAHGOSH/master.m3u8?mgid=mgid:arc:episode:paramountnetwork.com:f6df7c41-beac-11eb-8774-70df2f866ace&ts=1628881291-2&pthash=823dd4587cf09a96b1b8cd8b998d4ed631d71797&hdnts=exp=1629885999~acl=/h/a/CENSORED_BY_OHMYBAHGOSH/*~hmac=CENSORED_BY_OHMYBAHGOSH']
[Cookies] Extracting cookies from chrome
[debug] extracting from: "/root/.config/google-chrome-beta/Default/Cookies"
[Cookies] Extracted 654 cookies from chrome
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 (zip)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-kali9-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, phantomjs 1.9.7, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://topaz.viacomcbs.digital/h/a/CENSORED_BY_OHMYBAHGOSH/master.m3u8?mgid=mgid:arc:episode:paramountnetwork.com:f6df7c41-beac-11eb-8774-70df2f866ace&ts=1628881291-2&pthash=823dd4587cf09a96b1b8cd8b998d4ed631d71797&hdnts=exp=1629885999~acl=/h/a/CENSORED_BY_OHMYBAHGOSH/*~hmac=CENSORED_BY_OHMYBAHGOSH
[generic] *~hmac=CENSORED_BY_OHMYBAHGOSH: Requesting header
[generic] *~hmac=CENSORED_BY_OHMYBAHGOSH: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] *~hmac=CENSORED_BY_OHMYBAHGOSH: Downloading 1 format(s): 225+audio0-default
```  

# My Takeaway (Without Having Much Python Experience)
Since ParamountNetwork no longer has the previous mgid url (media.mtvservices.com), but instead calls the JSON (topaz.viacomcbs.digital) directly now (which contains the Master M3U8, ParamountNetwork could have it's own extractor that parses the m3u8 from the topaz mica.json request URL.  Also it could also import some of the existing MTV extractor...maybe?  

Really wish I would spend more time learning Python lol...hope this data helps a bit!

**Comment by Sipherdrakon** [comment]
Will probably have to have it parse the json for individual mgids as the master.m3u8 is already stitched with ads. But it looks like each sequence within the json is the actual show. Originally I was going through each playlist within the 1080p variant of the master.m3u8 and deleting all viacom-ads urls and then using ffmpeg to download from the edited m3u8, but that is very tedious, so hopefully we can get this figured out.

**Comment by ParadoxGBB** [comment]
Comedy Central (for example, The Daily Show) works great now. Thanks!

**Comment by ParadoxGBB** [comment]
Trying to pay it forward a bit (thanks so much for partially addressing this):

Latest bits are better, but Comedy Central is now partially fixed for some URLs but still broken for others. Oddly enough, seems chronological with the most recent being broken.

Broken:

[http://www.cc.com/episodes/yz6n46/the-daily-show-with-trevor-noah-october-28--2021---kristen-soltis-anderson-season-27-ep-27019]
[http://www.cc.com/episodes/2w2c7f/the-daily-show-with-trevor-noah-october-27--2021---diego-boneta-season-27-ep-27018]
[http://www.cc.com/episodes/w7l1p9/the-daily-show-with-trevor-noah-october-26--2021---tamron-hall-season-27-ep-27017] 
[http://www.cc.com/episodes/lf7rlv/the-daily-show-with-trevor-noah-october-25--2021---anna-kendrick-season-27-ep-27016] 

Works:

[https://www.cc.com/episodes/1asx66/roy-wood-jr-imperfect-messenger-roy-wood-jr-imperfect-messenger-ep-1]
[http://www.cc.com/episodes/8etfry/the-daily-show-with-trevor-noah-october-21--2021---tammy-duckworth---michael-pollan-season-27-ep-27015]
[http://www.cc.com/episodes/fq9men/the-daily-show-with-trevor-noah-october-20--2021---nick-offerman-season-27-ep-27014]

**Comment by The-Bart-The** [comment]
On Comedy Central’s site (example: any video on https://www.cc.com/episodes ) the vids marked “Sign in to Watch” are still working (without authorization for some reason) but the ones that aren’t marked are the ones that aren’t working.
