### ISSUE TITLE
YT-DLP throws `Requested format is not available` when using `-f` in any way

### ISSUE THREAD

**Issue by VXsz** [yt-dlp/yt-dlp#714]
## Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [ ] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['https://cdxaws-ak.akamaized.net/out/v1/955bd70288c849cfbe108ac570c17859/a82af339e99a490684e63554466650b9/9951caf943ff4de6b0ee4ae605278201/manifest.m3u8?aws.manifestfilter=video_height:144-1080', '-f', 'best', '--verbose']
[debug] Encodings: locale cp1256, fs utf-8, out utf-8, pref cp1256
[debug] yt-dlp version 2021.08.02
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-08-04-git-3b298640e1-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://cdxaws-ak.akamaized.net/out/v1/955bd70288c849cfbe108ac570c17859/a82af339e99a490684e63554466650b9/9951caf943ff4de6b0ee4ae605278201/manifest.m3u8?aws.manifestfilter=video_height:144-1080
[generic] manifest.m3u8?aws: Requesting header
[generic] manifest.m3u8?aws: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: Requested format is not available
Traceback (most recent call last):
  File "<myDir>\binaries\yt_dlp\YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "<myDir>\binaries\yt_dlp\YoutubeDL.py", line 1237, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "<myDir>\binaries\yt_dlp\YoutubeDL.py", line 1281, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "<myDir>\binaries\yt_dlp\YoutubeDL.py", line 2284, in process_video_result
    raise ExtractorError('Requested format is not available', expected=True)
yt_dlp.utils.ExtractorError: Requested format is not available
```

## Description

So I'm trying to download this m3u8 stream: `https://cdxaws-ak.akamaized.net/out/v1/955bd70288c849cfbe108ac570c17859/a82af339e99a490684e63554466650b9/9951caf943ff4de6b0ee4ae605278201/manifest.m3u8?aws.manifestfilter=video_height:144-1080` but if I try to select the quality (try anything with -f) it just throws the error `Requested format is not available`, if I try to remove -f it basically adds an extension to my file names one for the audio (from the expected ` SERIES-01-03.m4a` to `SERIES-01-03.faudio_0-ar.mp4`) and one for the video (from the expected `SERIES-01-03.mp4` to `SERIES-01-03.f3281.mp4`) which kills my script since it doesn't know the actual names (and expects a name without the added ext from yt-dlp)

I tried `--merge-output-format` but... it doesn't merge? maybe I'm understanding it wrong, but I thought it would merge the audio and video to the desired name which could fix the problem in my script

but anyways, why does it give this error? it's really weird

**Comment by Ashish0804** [comment]
1. use latest.
2. show output of `-Uv -F` if problem still persists.

**Comment by VXsz** [comment]
Same problem still persists with `2021.8.10` (latest)
Here's the output of `Uv -F`:

```
[debug] Command-line config: ['https://cdxaws-ak.akamaized.net/out/v1/955bd70288c849cfbe108ac570c17859/a82af339e99a490684e63554466650b9/9951caf943ff4de6b0ee4ae605278201/manifest.m3u8?aws.manifestfilter=video_height:144-1080', '-Uv', '-F', '--verbose']
[debug] Encodings: locale cp1256, fs utf-8, out utf-8, pref cp1256
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-08-04-git-3b298640e1-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
Current Build Hash 1f9073f331b9e58b752f7c172c8be0662141ca19620d50a8e003a40897eed758
yt-dlp is up to date (2021.08.10)
[debug] [generic] Extracting URL: https://cdxaws-ak.akamaized.net/out/v1/955bd70288c849cfbe108ac570c17859/a82af339e99a490684e63554466650b9/9951caf943ff4de6b0ee4ae605278201/manifest.m3u8?aws.manifestfilter=video_height:144-1080
[generic] manifest.m3u8?aws: Requesting header
[generic] manifest.m3u8?aws: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for manifest.m3u8?aws:
ID         EXT RESOLUTION FPS |   TBR PROTO  | VCODEC        VBR ACODEC  MORE INFO
---------- --- ---------- --- - ----- ------ - ----------- ----- ------- ---------
audio_0-ar mp4 audio only     |       m3u8_n |                   unknown [ar], ar
180        mp4 256x144    25  |  180k m3u8_n | avc1.42C01E  180k
248        mp4 256x144    25  |  248k m3u8_n | avc1.42C01E  248k
312        mp4 448x252    25  |  312k m3u8_n | avc1.4D401E  312k
316        mp4 448x252    25  |  316k m3u8_n | avc1.42C01E  316k
363        mp4 512x288    25  |  363k m3u8_n | avc1.4D401E  363k
456        mp4 640x360    25  |  456k m3u8_n | avc1.42C01E  456k
606        mp4 832x468    25  |  606k m3u8_n | avc1.4D401F  606k
774        mp4 1024x576   25  |  774k m3u8_n | avc1.4D401F  774k
1385       mp4 1280x720   25  | 1385k m3u8_n | avc1.4D401F 1385k
3281       mp4 1920x1080  25  | 3281k m3u8_n | avc1.640028 3281k
```

**Comment by Ashish0804** [comment]
use `-f 3281+audio_0-ar` if you don't want to hardcode, then use `-f 'bv+ba'`
To merge use `--merge-output-format mkv`

**Comment by VXsz** [comment]
looks like bv+ba worked, probably the update :), I'll use bv+ba/b just in case the manifest only has combined streams

Thanks for the help, I was using the `--merge-output-format` wrong so that explains it
