### ISSUE TITLE
[sverigesradio] URLs doesn't seem to work

### ISSUE THREAD

**Issue by blindpk** [yt-dlp/yt-dlp#7145]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Sweden

### Provide a description that is worded well enough to be understood

There are two extractors, sverigesradio:episode ande sverigesradio:publication, that, to my understanding, should work with URLs from sverigesradio.se. However, no URLs I throw at yt-dlp for that site works, it falls back to the generic extractor. Here are two examples (complete output provided for both, no account required):
https://sverigesradio.se/artikel/tysk-fotbollsfeber-bayern-munchens-10-ariga-segersvit-kan-brytas
https://sverigesradio.se/avsnitt/p4-live-med-first-aid-kit-scandinavium-mars-2023

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--no-config', '-vU', 'https://sverigesradio.se/artikel/tysk-fotbollsfeber-bayern-munchens-10-ariga-segersvit-kan-brytas']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.27.104018 [daafbf49b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110654-g63767b79a5-20230518 (setts), ffprobe N-110654-g63767b79a5-20230518
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1822 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.05.27.104018, Current version: nightly@2023.05.27.104018
Current Build Hash: 1f01e550a8bb814b3a92039f5749d583ea9c084ad4bf9cafd933e52a0c9e2813
yt-dlp is up to date (nightly@2023.05.27.104018)
[generic] Extracting URL: https://sverigesradio.se/artikel/tysk-fotbollsfeber-bayern-munchens-10-ariga-segersvit-kan-brytas
[generic] tysk-fotbollsfeber-bayern-munchens-10-ariga-segersvit-kan-brytas: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] tysk-fotbollsfeber-bayern-munchens-10-ariga-segersvit-kan-brytas: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://sverigesradio.se/artikel/tysk-fotbollsfeber-bayern-munchens-10-ariga-segersvit-kan-brytas
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1552, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1628, in __extract_info
  File "yt_dlp\extractor\common.py", line 698, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://sverigesradio.se/artikel/tysk-fotbollsfeber-bayern-munchens-10-ariga-segersvit-kan-brytas

[debug] Command-line config: ['--no-config', '-vU', 'https://sverigesradio.se/avsnitt/p4-live-med-first-aid-kit-scandinavium-mars-2023']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.27.104018 [daafbf49b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110654-g63767b79a5-20230518 (setts), ffprobe N-110654-g63767b79a5-20230518
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1822 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.05.27.104018, Current version: nightly@2023.05.27.104018
Current Build Hash: 1f01e550a8bb814b3a92039f5749d583ea9c084ad4bf9cafd933e52a0c9e2813
yt-dlp is up to date (nightly@2023.05.27.104018)
[generic] Extracting URL: https://sverigesradio.se/avsnitt/p4-live-med-first-aid-kit-scandinavium-mars-2023
[generic] p4-live-med-first-aid-kit-scandinavium-mars-2023: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] p4-live-med-first-aid-kit-scandinavium-mars-2023: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://sverigesradio.se/avsnitt/p4-live-med-first-aid-kit-scandinavium-mars-2023
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1552, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1628, in __extract_info
  File "yt_dlp\extractor\common.py", line 698, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://sverigesradio.se/avsnitt/p4-live-med-first-aid-kit-scandinavium-mars-2023
```

**Comment by bashonly** [comment]
The site has started to use URLs that do not contain the audio ID, so the extractor needs to be improved:
```diff
diff --git a/yt_dlp/extractor/sverigesradio.py b/yt_dlp/extractor/sverigesradio.py
index 65da615d0..56bacafbf 100644
--- a/yt_dlp/extractor/sverigesradio.py
+++ b/yt_dlp/extractor/sverigesradio.py
@@ -1,6 +1,9 @@
 from .common import InfoExtractor
 from ..utils import (
     determine_ext,
+    extract_attributes,
+    get_element_by_id,
+    get_element_html_by_class,
     int_or_none,
     str_or_none,
 )
@@ -21,7 +24,13 @@ class SverigesRadioBaseIE(InfoExtractor):
     }
 
     def _real_extract(self, url):
-        audio_id = self._match_id(url)
+        audio_id, display_id = self._match_valid_url(url).group('id', 'slug')
+        if not audio_id:
+            webpage = self._download_webpage(url, display_id)
+            button = extract_attributes(get_element_html_by_class('audio-button', webpage) or '')
+            audio_id = (button.get('data-audio-id') or button.get('data-publication-id')
+                        or self._parse_json(get_element_by_id('gtm-metadata', webpage), display_id)['pageId'])
+
         query = {
             'id': audio_id,
             'type': self._AUDIO_TYPE,
@@ -72,7 +81,7 @@ def _real_extract(self, url):
 
 class SverigesRadioPublicationIE(SverigesRadioBaseIE):
     IE_NAME = 'sverigesradio:publication'
-    _VALID_URL = r'https?://(?:www\.)?sverigesradio\.se/sida/(?:artikel|gruppsida)\.aspx\?.*?\bartikel=(?P<id>[0-9]+)'
+    _VALID_URL = r'https?://(?:www\.)?sverigesradio\.se/(?:sida/)?(?:artikel|gruppsida)(?:\.aspx\?.*?\bartikel=(?P<id>[0-9]+)|/(?P<slug>[\w-]+))'
     _TESTS = [{
         'url': 'https://sverigesradio.se/sida/artikel.aspx?programid=83&artikel=7038546',
         'md5': '6a4917e1923fccb080e5a206a5afa542',
@@ -94,7 +103,7 @@ class SverigesRadioPublicationIE(SverigesRadioBaseIE):
 
 class SverigesRadioEpisodeIE(SverigesRadioBaseIE):
     IE_NAME = 'sverigesradio:episode'
-    _VALID_URL = r'https?://(?:www\.)?sverigesradio\.se/(?:sida/)?avsnitt/(?P<id>[0-9]+)'
+    _VALID_URL = r'https?://(?:www\.)?sverigesradio\.se/(?:sida/)?avsnitt/(?:(?P<id>\d+)|(?P<slug>[\w-]+))(?:$|[#?])'
     _TEST = {
         'url': 'https://sverigesradio.se/avsnitt/1140922?programid=1300',
         'md5': '20dc4d8db24228f846be390b0c59a07c',
```
