### ISSUE TITLE
Can't download video from D.Tube

### ISSUE THREAD

**Issue by DanilaParakhnevich** [yt-dlp/yt-dlp#7182]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

this happens after executing this script:

if __name__ == '__main__':
    with YoutubeDL() as ydl:
        ydl.extract_info('https://d.tube/#!/v/captainbob/bbjh7t3ikzm')

Maybe there is a fix?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API
[debug] params: {'verbose': True, 'compat_opts': set()}
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.35)
[debug] exe versions: ffmpeg 5.0.2 (fdk), ffprobe 5.0.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[DTube] Extracting URL: https://d.tube/#!/v/captainbob/bbjh7t3ikzm
[DTube] bbjh7t3i: Downloading JSON metadata
ERROR: bbjh7t3i: An extractor error has occurred. (caused by KeyError('result')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/extractor/dtube.py", line 32, in _real_extract
    result = self._download_json('https://api.steemit.com/', video_id, data=json.dumps({
KeyError: 'result'

Traceback (most recent call last):
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/extractor/dtube.py", line 32, in _real_extract
    result = self._download_json('https://api.steemit.com/', video_id, data=json.dumps({
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e, video_id=self.get_temp_id(url))
yt_dlp.utils.ExtractorError: bbjh7t3i: An extractor error has occurred. (caused by KeyError('result')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/service/videohosting_service/VideohostingService.py", line 274, in <module>
    ydl.extract_info('https://d.tube/#!/v/captainbob/bbjh7t3ikzm')
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1536, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/dendil/Documents/Projects/Own/BuxarVideoUploader/venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 955, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: bbjh7t3i: An extractor error has occurred. (caused by KeyError('result')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by dirkf** [comment]
The JSON API request needs an additional parameter `'id': request_id`, or the returned JSON just has an `error` member. With `request_id` 0, a `result` member is present and its `.json_metadata` is a valid string as expected for the test video.

With the problem video (captainbob/bbjh7t3ikzm), `.json_metadata` is empty.

The extractor code uses the same logic as the site JS, except that the site JS
* sends `Content-Type: application/json`
* uses JS `fetch` with mode `cors` 
* tries up to 2 alternate API hosts in case api.steemit.com times out.

However, setting `Origin` header to the base source URL and/or setting the `Content-Type` has no effect (and/or `Referer`).

**Comment by flashdagger** [comment]
Seems to work with the [d.tube plugin](https://pypi.org/project/ytdlp-dtube/).

**Comment by dirkf** [comment]
That looks like a thorough job.
