### ISSUE TITLE
ffprobe after change drives windows

### ISSUE THREAD

**Issue by Zedroid** [yt-dlp/yt-dlp#7199]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Postprocessing: Unable to determine video duration: ffprobe not found. Please install or provide the path using --ffmpeg-location 

D:\>D:\yt-dlp.exe -f 313 https://www.youtube.com/playlist?list=UUHWbZM3BIGgZksvXegx_h3w --output "D:/Downloads/youtube-dl/" --sponsorblock-remove all -vU

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\>"D:\yt-dlp (1).exe" -f 313 https://www.youtube.com/playlist?list=UUHWbZM3BIGgZksvXegx_h3w --output "D:/Downloads/youtube-dl/" --sponsorblock-remove all -vU
[debug] Command-line config: ['-f', '313', 'https://www.youtube.com/playlist?list=UUHWbZM3BIGgZksvXegx_h3w', '--output', 'D:/Downloads/youtube-dl/', '--sponsorblock-remove', 'all', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=UUHWbZM3BIGgZksvXegx_h3w
[youtube:tab] UUHWbZM3BIGgZksvXegx_h3w: Downloading webpage
[youtube:tab] UUHWbZM3BIGgZksvXegx_h3w: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Uploads from Enes Yilmazer
[youtube:tab] UUHWbZM3BIGgZksvXegx_h3w page 1: Downloading API JSON
[youtube:tab] UUHWbZM3BIGgZksvXegx_h3w page 2: Downloading API JSON
[youtube:tab] Playlist Uploads from Enes Yilmazer: Downloading 229 items of 229
[download] Downloading item 1 of 229
[youtube] Extracting URL: https://www.youtube.com/watch?v=7qFClwGaFYc
[youtube] 7qFClwGaFYc: Downloading webpage
[youtube] 7qFClwGaFYc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/939d?service=YouTube&categories=%5B%22intro%22%2C+%22interaction%22%2C+%22selfpromo%22%2C+%22filler%22%2C+%22sponsor%22%2C+%22outro%22%2C+%22music_offtopic%22%2C+%22preview%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[SponsorBlock] Found 19 segments in the SponsorBlock database
[info] 7qFClwGaFYc: Downloading 1 format(s): 313
[debug] Invoking dashsegments downloader on "https://rr3---sn-5go7ynlk.googlevideo.com/videoplayback?expire=1685676674&ei=Ig55ZIXLCsbFyAX57JeYCQ&ip=146.70.16.234&id=o-AASaArwVje7SgIrpsS9ybq6NT4PgpivG0aua93L-PBuR&itag=313&source=youtube&requiressl=yes&mh=Pz&mm=31%2C26&mn=sn-5go7ynlk%2Csn-i5heen7z&ms=au%2Conr&mv=m&mvi=3&pl=24&initcwndbps=603750&spc=qEK7B6djr6wixVVGrklDMb07CsJxz3o&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=4457592609&dur=2197.995&lmt=1685572738245841&mt=1685654975&fvip=1&keepalive=yes&fexp=24007246%2C51000012%2C51000022&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAK41mLAL8bs8SljHNnlSXlevJqeWGsxxl86BmVaEr_0qAiEA8V7aXU-noA1sVWvIAeuWnapS8A7JUWj6PhXu__ANPpo%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANSYZ0esYUKkj_iL1DvK_-5kT6A4Qb0sulPkGRlXdfBEAiEAthMLNxcFzUvdAqiQyJ6-lj24L-6NJ-pqFZMAS9kIVHs%3D"
[download] D:\Downloads\youtube-dl has already been downloaded
[download] 100% of    4.15GiB
ERROR: Postprocessing: Unable to determine video duration: ffprobe not found. Please install or provide the path using --ffmpeg-location
Traceback (most recent call last):
  File "yt_dlp\postprocessor\ffmpeg.py", line 308, in _get_real_video_duration
  File "yt_dlp\postprocessor\ffmpeg.py", line 280, in get_metadata_object
yt_dlp.utils.PostProcessingError: ffprobe not found. Please install or provide the path using --ffmpeg-location

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3323, in process_info
  File "yt_dlp\YoutubeDL.py", line 3502, in post_process
  File "yt_dlp\YoutubeDL.py", line 3484, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3462, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\modify_chapters.py", line 33, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 314, in _get_real_video_duration
yt_dlp.utils.PostProcessingError: Unable to determine video duration: ffprobe not found. Please install or provide the path using --ffmpeg-location

[download] Downloading item 2 of 229
[youtube] Extracting URL: https://www.youtube.com/watch?v=jkndHmbN9mc
[youtube] jkndHmbN9mc: Downloading webpage
[youtube] jkndHmbN9mc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/67f0?service=YouTube&categories=%5B%22intro%22%2C+%22interaction%22%2C+%22selfpromo%22%2C+%22filler%22%2C+%22sponsor%22%2C+%22outro%22%2C+%22music_offtopic%22%2C+%22preview%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[SponsorBlock] Found 11 segments in the SponsorBlock database
[info] jkndHmbN9mc: Downloading 1 format(s): 313
[debug] Invoking dashsegments downloader on "https://rr4---sn-5goeenes.googlevideo.com/videoplayback?expire=1685676677&ei=JQ55ZKDKGa2J8wLB-4a4CA&ip=146.70.16.234&id=o-AAjkqOGlVQiliBqh8uLWYpULDO_k2T_zIKLHen852yl5&itag=313&source=youtube&requiressl=yes&mh=6f&mm=31%2C26&mn=sn-5goeenes%2Csn-f5f7kn7z&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=422500&spc=qEK7B15jSoVTjLgLbgTzoMZpEZPfd30&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=5099512296&dur=2661.258&lmt=1684670746036443&mt=1685654711&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMg9JDAiVdB3zNb6lR-hJK9APaSxCbjn7Xty2P614HBsAiEA0Nr3a6w98UR4OXT-0Yb6tk9Wsc-gmPmU1qxQJtDY4pc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgBDMvPZCPqoits_IDCbSGG44A76gjoHtn6jmc3ostXOACIGu1S7aCJIrOxO6yzucTtnUDp0sgnmgf2SPEm_csl5Zg"
[download] D:\Downloads\youtube-dl has already been downloaded
[download] 100% of    4.15GiB
ERROR: Postprocessing: Unable to determine video duration: ffprobe not found. Please install or provide the path using --ffmpeg-location
Traceback (most recent call last):
  File "yt_dlp\postprocessor\ffmpeg.py", line 308, in _get_real_video_duration
  File "yt_dlp\postprocessor\ffmpeg.py", line 280, in get_metadata_object
yt_dlp.utils.PostProcessingError: ffprobe not found. Please install or provide the path using --ffmpeg-location

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3323, in process_info
  File "yt_dlp\YoutubeDL.py", line 3502, in post_process
  File "yt_dlp\YoutubeDL.py", line 3484, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3462, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\modify_chapters.py", line 33, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 314, in _get_real_video_duration
yt_dlp.utils.PostProcessingError: Unable to determine video duration: ffprobe not found. Please install or provide the path using --ffmpeg-location

[download] Downloading item 3 of 229
[youtube] Extracting URL: https://www.youtube.com/watch?v=aN9DH_GxqEo
[youtube] aN9DH_GxqEo: Downloading webpage
[youtube] aN9DH_GxqEo: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, v
```

**Comment by Zedroid** [comment]
i used this video https://www.youtube.com/watch?v=OZ6RZ9imWAg

**Comment by bashonly** [comment]
if you already have ffmpeg and ffprobe on your computer, either:
 - move `ffmpeg.exe` and `ffprobe.exe` into the same folder as `yt-dlp.exe`
 OR
 - pass the `--ffmpeg-location` option with the path to the ffmpeg/ffprobe exe's as the argument
 
 &nbsp;
 
 if you need to install ffmpeg, follow this guide:
 
   1. Download [https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip](https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip)
   2. Extract the files and find `ffmpeg.exe` and `ffprobe.exe` inside the `bin` folder
   3. Copy those two files to the same folder as `yt-dlp.exe`

**Comment by Zedroid** [comment]
Thank you couldn't find out what ffprove.exe exactly was and didn't know I could just put them in them same folder

Very new to all this programming
