### ISSUE TITLE
[ok.ru] Can't download non hls formats

### ISSUE THREAD

**Issue by mazznoer** [yt-dlp/yt-dlp#7201]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Can't download non hls videos.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://ok.ru/video/1868262214220', '-f', 'full', '-vU', '--ignore-config']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: f41b949a
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-71-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: certifi-2019.11.28, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1842 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[Odnoklassniki] Extracting URL: https://ok.ru/video/1868262214220
[Odnoklassniki] 1868262214220: Downloading desktop webpage
[Odnoklassniki] 1868262214220: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 1868262214220: Downloading 1 format(s): full
[debug] Invoking http downloader on "https://vd292.mycdn.me/?expires=1685752437000&srcIp=114.10.4.70&pr=10&srcAg=CHROME&ms=185.226.52.42&type=5&sig=7FnX_Adcp0c&ct=0&urls=45.136.22.19&clientType=0&id=602557450828"
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/home/nir/Code-Fu/lain-lain/yt-dlp/yt_dlp/YoutubeDL.py", line 3280, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/nir/Code-Fu/lain-lain/yt-dlp/yt_dlp/YoutubeDL.py", line 3003, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/nir/Code-Fu/lain-lain/yt-dlp/yt_dlp/downloader/common.py", line 456, in download
    ret = self.real_download(filename, info_dict)
  File "/home/nir/Code-Fu/lain-lain/yt-dlp/yt_dlp/downloader/http.py", line 377, in real_download
    establish_connection()
  File "/home/nir/Code-Fu/lain-lain/yt-dlp/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/nir/Code-Fu/lain-lain/yt-dlp/yt_dlp/YoutubeDL.py", line 3776, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by bashonly** [comment]
When yt-dlp extracts the m3u8 formats, the CDN sets a poisonous cookie via the response headers:
```
header: Set-Cookie: tstc=p;
```
If we clear this cookie, the direct mp4 formats will be downloadable:
```diff
diff --git a/yt_dlp/extractor/odnoklassniki.py b/yt_dlp/extractor/odnoklassniki.py
index 4b73eed37..fcb117443 100644
--- a/yt_dlp/extractor/odnoklassniki.py
+++ b/yt_dlp/extractor/odnoklassniki.py
@@ -1,3 +1,5 @@
+import urllib.parse
+
 from .common import InfoExtractor
 from ..compat import (
     compat_etree_fromstring,
@@ -359,6 +361,9 @@ def _extract_desktop(self, url):
         if provider == 'LIVE_TV_APP':
             info['title'] = title
 
+        def clear_cookies(manifest_url):
+            self.cookiejar.clear(domain=urllib.parse.urlparse(manifest_url).netloc)
+
         quality = qualities(('4', '0', '1', '2', '3', '5', '6', '7'))
 
         formats = [{
@@ -372,6 +377,7 @@ def _extract_desktop(self, url):
             formats.extend(self._extract_m3u8_formats(
                 m3u8_url, video_id, 'mp4', 'm3u8_native',
                 m3u8_id='hls', fatal=False))
+            clear_cookies(m3u8_url)
 
         dash_manifest = metadata.get('metadataEmbedded')
         if dash_manifest:
@@ -390,6 +396,7 @@ def _extract_desktop(self, url):
         if m3u8_url:
             formats.extend(self._extract_m3u8_formats(
                 m3u8_url, video_id, 'mp4', m3u8_id='hls', fatal=False))
+            clear_cookies(m3u8_url)
         rtmp_url = metadata.get('rtmpUrl')
         if rtmp_url:
             formats.append({
```
