### ISSUE TITLE
Error initializing the muxer for file

### ISSUE THREAD

**Issue by Zedroid** [yt-dlp/yt-dlp#7206]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Error initializing the muxer for file
i dragged all ffprobe.exe and ffmpeg.exe in the same folder as yt dlp now I get this
I need sponsorblock and 4k videos

D:\>D:\yt-dlp.exe -f 313 https://www.youtube.com/playlist?list=UUHWbZM3BIGgZksvXegx_h3w --output "D:/Downloads/youtube-dl/" --sponsorblock-remove all -vU

can this program be run in an external hard drive? I just want to save in external hard drive, but I do not know how to only change the download location to an external drive so I was forced to run from the external hard drive

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\>D:\yt-dlp.exe -f 313 https://www.youtube.com/playlist?list=UUHWbZM3BIGgZksvXegx_h3w --output "D:/Downloads/youtube-dl/" --sponsorblock-remove all -vU
[debug] Command-line config: ['-f', '313', 'https://www.youtube.com/playlist?list=UUHWbZM3BIGgZksvXegx_h3w', '--output', 'D:/Downloads/youtube-dl/', '--sponsorblock-remove', 'all', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110925-g45fa85a777-20230529 (setts), ffprobe N-110925-g45fa85a777-20230529
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=UUHWbZM3BIGgZksvXegx_h3w
[youtube:tab] UUHWbZM3BIGgZksvXegx_h3w: Downloading webpage
[youtube:tab] UUHWbZM3BIGgZksvXegx_h3w: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Uploads from Enes Yilmazer
[youtube:tab] UUHWbZM3BIGgZksvXegx_h3w page 1: Downloading API JSON
[youtube:tab] UUHWbZM3BIGgZksvXegx_h3w page 2: Downloading API JSON
[youtube:tab] Playlist Uploads from Enes Yilmazer: Downloading 229 items of 229
[download] Downloading item 1 of 229
[youtube] Extracting URL: https://www.youtube.com/watch?v=7qFClwGaFYc
[youtube] 7qFClwGaFYc: Downloading webpage
[youtube] 7qFClwGaFYc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/939d?service=YouTube&categories=%5B%22filler%22%2C+%22outro%22%2C+%22preview%22%2C+%22sponsor%22%2C+%22interaction%22%2C+%22music_offtopic%22%2C+%22intro%22%2C+%22selfpromo%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[SponsorBlock] Found 19 segments in the SponsorBlock database
[info] 7qFClwGaFYc: Downloading 1 format(s): 313
[debug] Invoking dashsegments downloader on "https://rr5---sn-5goeenes.googlevideo.com/videoplayback?expire=1685734453&ei=1e95ZJyUI4enyAW3sa3gDA&ip=146.70.16.234&id=o-AA4sZIUycv2F_yScxg8pwSzrmNzr0n7qwbGp0h90gIAF&itag=313&source=youtube&requiressl=yes&mh=Pz&mm=31%2C29&mn=sn-5goeenes%2Csn-5go7ynlk&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=262500&spc=qEK7B7v4kYbqfBExPyydXzayc8v68Ko&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=4457592609&dur=2197.995&lmt=1685572738245841&mt=1685712558&fvip=3&keepalive=yes&fexp=24007246%2C51000022&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAIe8qVJcJWzo3WyJFCM0pWEDXzYEC9HEcKUpR0UhS4hBAiEA85Cwfilqzjd0seiHwv4M6g0XRMu5jbj5LY6-RQpqdE4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgXw5a91V85uEVIFgO6-TyMgthHdRwswgEneRCagTED10CIQDsfQQTpup9yhIXL8hORLFtYrd73GuT8Qsb8Xe_PqFE7Q%3D%3D"
[download] D:\Downloads\youtube-dl has already been downloaded
[download] 100% of    4.15GiB
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:D:\Downloads\youtube-dl"
[debug] Concat spec = 100.559000-150.675000, 170.567000-260.077000, 268.575000-347.908000, 409.524000-486.043000, 521.072000-567.867000, 662.916000-693.178000, 717.282000-742.139000, 771.876000-796.474000, 804.577000-842.384000, 862.180000-941.858000, 1000.505000-1041.898000, 1046.295000-1110.352000, 1332.413000-1386.231000, 1400.883000-1413.725000, 1440.381000-1609.233000, 1617.143000-1722.588000, 1726.777000-1743.883000, 1968.231000-2110.686000
[ModifyChapters] Removing chapters from D:\Downloads\youtube-dl
[debug] Writing concat spec to D:\Downloads\youtube-dl.temp.concat
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -hide_banner -nostdin -f concat -safe 0 -i "file:D:\Downloads\youtube-dl.temp.concat" -map 0 -dn -ignore_unknown -c copy -movflags "+faststart" "file:D:\Downloads\youtube-dl.temp"
[debug] Input #0, concat, from 'file:D:\Downloads\youtube-dl.temp.concat':
  Duration: 00:19:05.44, start: -1.193000, bitrate: 0 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn
[AVFormatContext @ 0000024bde551d80] Unable to choose an output format for 'file:D:\Downloads\youtube-dl.temp'; use a standard extension for the filename or specify the format manually.
[out#0 @ 0000024bde54f740] Error initializing the muxer for file:D:\Downloads\youtube-dl.temp: Invalid argument

ERROR: Postprocessing: [out#0 @ 0000024bde54f740] Error initializing the muxer for file:D:\Downloads\youtube-dl.temp: Invalid argument
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3323, in process_info
  File "yt_dlp\YoutubeDL.py", line 3502, in post_process
  File "yt_dlp\YoutubeDL.py", line 3484, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3462, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\modify_chapters.py", line 61, in run
  File "yt_dlp\postprocessor\modify_chapters.py", line 59, in remove_chapters
  File "yt_dlp\postprocessor\modify_chapters.py", line 318, in remove_chapters
  File "yt_dlp\postprocessor\ffmpeg.py", line 416, in concat_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 362, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: [out#0 @ 0000024bde54f740] Error initializing the muxer for file:D:\Downloads\youtube-dl.temp: Invalid argument
```

**Comment by bashonly** [comment]
you are using the `--output` option as if it is the `-P` option

change `--output` to `-P`

read the [output template section of the readme](https://github.com/yt-dlp/yt-dlp#output-template)

**Comment by Zedroid** [comment]
thank you so much I can confirm it is finally working C:\Users\zedro>D:\yt-dlp.exe -f 313+251 https://www.youtube.com/playlist?list=UUHWbZM3BIGgZksvXegx_h3w -P "D:/Downloads/youtube-dl/" --sponsorblock-remove all -vU
