### ISSUE TITLE
Support for downloading playlists from myspass.de

### ISSUE THREAD

**Issue by ffw2** [yt-dlp/yt-dlp#7232]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Example URLs

Overview of the series:
https://www.myspass.de/shows/tvshows/stromberg/

Single video: 
https://www.myspass.de/shows/tvshows/stromberg/Malik--/6372/
https://www.myspass.de/shows/tvshows/stromberg/Frau-Papenacker--/6375/
...

![myspass](https://github.com/yt-dlp/yt-dlp/assets/15077753/919697a6-3c3b-4a36-9bff-1888cd5a64a4)

### Provide a description that is worded well enough to be understood

At the moment it's only possible to download single videos.
And there is no direct link to the playlist.

Single video format:
https://www.myspass.de/shows/tvshows/*show*/*title*/*number*/

(the **number** of the video isn't always a consecutive number)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.myspass.de/shows/tvshows/strom
berg']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.
1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe
6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, m
utagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a
9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.myspass.de/shows/tvshows/stromberg
[generic] stromberg: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] stromberg: Extracting information
[debug] Looking for embeds
WARNING: [generic] stromberg: Failed to parse JSON: Extra data in '          }':
 line 48 column 29 (char 3589)
ERROR: Unsupported URL: https://www.myspass.de/shows/tvshows/stromberg
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.myspass.de/shows/tvs
hows/stromberg
```

**Comment by ffw2** [comment]
My request for this page is still valid @pukkandan 
It would be nice if the page were added. Thanks.

`[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1859 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.05.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.05.22 from yt-dlp/yt-dlp)
[MySpass] Extracting URL: https://www.myspass.de/player/absolute-mehrheit-vom-11-november-2012/7858
[MySpass] 7858: Downloading XML
ERROR: [MySpass] 7858: Unable to download XML: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp\extractor\common.py", line 748, in extract
  File "yt_dlp\extractor\myspass.py", line 69, in _real_extract
  File "yt_dlp\extractor\common.py", line 1145, in download_content
  File "yt_dlp\extractor\common.py", line 1103, in download_handle
  File "yt_dlp\extractor\common.py", line 968, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 917, in _request_webpage

  File "yt_dlp\extractor\common.py", line 904, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4195, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 194, in wrapper
  File "yt_dlp\networking\common.py", line 359, in send
  File "yt_dlp\networking\_requests.py", line 368, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden`
