### ISSUE TITLE
WrestleUniverse plugin not longer working with livestream URLs

### ISSUE THREAD

**Issue by Adthrawn** [yt-dlp/yt-dlp#7298]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

After the recent fix that was pushed to nightly a few weeks ago, WrestleUniverse is now throwing a new error when trying to download a livestream

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://www.wrestle-universe.com/en/lives/i4BdMcpGTWiy9EExkDYPhJ', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.06.04.142854 [c2a1bdb00] (linux_exe)
[debug] Python 3.10.11 (CPython x86_64 64bit) - Linux-5.15.0-73-generic-x86_64-with-glibc2.35 (OpenSSL 3.1.1 30 May 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/mike/.mozilla/firefox/1ks0sch7.default-release/cookies.sqlite"
[Cookies] Extracted 1406 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1840 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.06.12.181228, Current version: nightly@2023.06.04.142854
Current Build Hash: 4f42a26d9e4c3efe42d7e01d7a77ac3151cff8bcceb4fe1a65f0ecfd68078f1f
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
Updating to nightly@2023.06.12.181228 ...
[debug] Downloading yt-dlp_linux from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/yt-dlp_linux
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/SHA2-256SUMS
Updated yt-dlp to nightly@2023.06.12.181228
[debug] Restarting: ./yt-dlp_linux --cookies-from-browser firefox https://www.wrestle-universe.com/en/lives/i4BdMcpGTWiy9EExkDYPhJ -vU
[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://www.wrestle-universe.com/en/lives/i4BdMcpGTWiy9EExkDYPhJ', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.06.12.181228 [345b4c0ae] (linux_exe)
[debug] Python 3.10.11 (CPython x86_64 64bit) - Linux-5.15.0-73-generic-x86_64-with-glibc2.35 (OpenSSL 3.1.1 30 May 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/mike/.mozilla/firefox/1ks0sch7.default-release/cookies.sqlite"
[Cookies] Extracted 1406 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1842 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.06.12.181228, Current version: nightly@2023.06.12.181228
Current Build Hash: c238a2049e2b60a11ae253db4d091f78ba9eb9f9fb8092caf72f8cd6a48b0f8f
yt-dlp is up to date (nightly@2023.06.12.181228)
[debug] Loading wrestleuniverse.device_id from cache
[WrestleUniversePPV] Extracting URL: https://www.wrestle-universe.com/en/lives/i4BdMcpGTWiy9EExkDYPhJ
[WrestleUniversePPV] i4BdMcpGTWiy9EExkDYPhJ: Downloading metadata JSON
ERROR: '<=' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1552, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1628, in __extract_info
  File "yt_dlp/extractor/common.py", line 704, in extract
  File "yt_dlp/extractor/wrestleuniverse.py", line 282, in _real_extract
  File "yt_dlp/extractor/wrestleuniverse.py", line 133, in _call_encrypted_api
  File "yt_dlp/extractor/wrestleuniverse.py", line 112, in _call_api
  File "yt_dlp/extractor/wrestleuniverse.py", line 46, in _TOKEN
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

**Comment by bashonly** [comment]
Does `--cookies-from-browser` work with `--no-cache-dir` added as well?

**Comment by Adthrawn** [comment]
Tested that and got the same error

**Comment by Jaynator495** [comment]
Just to pitch in, I can confirm I get the same error even with `--no-cache-dir` added

**Comment by bashonly** [comment]
run `yt-dlp --update-to nightly`
