### ISSUE TITLE
[Question] Possible to embed custom thumbnail (from image)?

### ISSUE THREAD

**Issue by ischmidt20** [yt-dlp/yt-dlp#730]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I am wondering whether it is possible to embed a custom thumbnail, from my own downloaded image, using yt-dlp (or youtube-dl). Googling doesn't help because everything refers to embedding thumbnails direct from youtube.

I tried to do so by adding the following to `postprocessor_args`: `['-i', thumbnail, '-map', '1', '-map', '0', '-disposition:0', 'attached_pic', '-c', 'copy']`, where `thumbnail` is a string with the file path of my thumbnail. But when I do so, I get the following:

```
['-i', 'thumbnail.jpg', '-map', '1', '-map', '0', '-disposition:0', 'attached_pic', '-c', 'copy']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 
[debug] Python version 3.7.0 (CPython 64bit) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/uefa-champions-league/video/QAwKIRrc1jjTN47xDhAfCBexYklc1YVK/full-match-replay-salzburg-vs-br-ndby/
[ParamountPlus] QAwKIRrc1jjTN47xDhAfCBexYklc1YVK: Downloading JSON metadata
[ParamountPlus] QAwKIRrc1jjTN47xDhAfCBexYklc1YVK: Downloading JSON metadata
[ParamountPlus] QAwKIRrc1jjTN47xDhAfCBexYklc1YVK: Downloading DASH_CENC_PRECON SMIL data
[ParamountPlus] QAwKIRrc1jjTN47xDhAfCBexYklc1YVK: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] QAwKIRrc1jjTN47xDhAfCBexYklc1YVK: Downloading 1 format(s): hls-3120
[download] ./test.mp4 has already been downloaded
[debug] ffmpeg command line: ffprobe -show_streams file:./test.mp4
[FixupM3u8] Fixing malformed AAC bitstream of "./test.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:./test.mp4 -c copy -map 0 -dn -f mp4 -bsf:a aac_adtstoasc -i thumbnail.jpg -map 1 -map 0 -disposition:0 attached_pic -c copy file:./test.temp.mp4
ERROR: ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mpegts, from 'file:./test.mp4':
  Duration: 01:35:58.56, start: 0.100667, bitrate: 3265 kb/s
  Program 1 
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 59.94 fps, 59.94 tbr, 90k tbn, 119.88 tbc
  Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 130 kb/s
Option map (set input stream mapping) cannot be applied to input url thumbnail.jpg -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file thumbnail.jpg.
Error opening input files: Invalid argument
  File "<stdin>", line 1, in <module>
  File "/Users/isaac/Desktop/Sports/Soccer/streams/scraper/downloader.py", line 41, in download_video
    result = ydl.download([playlist_url])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2869, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1192, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1237, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1281, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2299, in process_video_result
    self.process_info(new_info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2838, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2987, in post_process
    info = self.run_pp(pp, info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2936, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/common.py", line 83, in wrapper
    return func(self, info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 704, in run
    '-c', 'copy', '-map', '0', '-dn', '-f', 'mp4', '-bsf:a', 'aac_adtstoasc'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 674, in _fixup
    self.run_ffmpeg(filename, temp_filename, options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 282, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 239, in run_ffmpeg_multiple_files
    [(out_path, opts)], **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 274, in real_run_ffmpeg
    self.report_error(stderr)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/common.py", line 56, in report_error
    return self._downloader.report_error(text, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 809, in report_error
    self.trouble(error_message, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 765, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/isaac/Desktop/Sports/Soccer/streams/scraper/downloader.py", line 41, in download_video
    result = ydl.download([playlist_url])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2869, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1192, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1237, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1281, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2299, in process_video_result
    self.process_info(new_info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2838, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2987, in post_process
    info = self.run_pp(pp, info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2936, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/common.py", line 83, in wrapper
    return func(self, info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 704, in run
    '-c', 'copy', '-map', '0', '-dn', '-f', 'mp4', '-bsf:a', 'aac_adtstoasc'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 674, in _fixup
    self.run_ffmpeg(filename, temp_filename, options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 282, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 239, in run_ffmpeg_multiple_files
    [(out_path, opts)], **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 274, in real_run_ffmpeg
    self.report_error(stderr)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/postprocessor/common.py", line 56, in report_error
    return self._downloader.report_error(text, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 809, in report_error
    self.trouble(error_message, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 774, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mpegts, from 'file:./test.mp4':
  Duration: 01:35:58.56, start: 0.100667, bitrate: 3265 kb/s
  Program 1 
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 59.94 fps, 59.94 tbr, 90k tbn, 119.88 tbc
  Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 130 kb/s
Option map (set input stream mapping) cannot be applied to input url thumbnail.jpg -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file thumbnail.jpg.
Error opening input files: Invalid argument
```

Of note: `you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.`, and `Error parsing options for input file thumbnail.jpg.`. Also interesting is that the input thumbnail image doesn't appear in the ffmpeg log.

How could I go about doing this? I'd rather keep this contained to ffmpeg as opposed to using mutagen or some other library.

**Comment by pukkandan** [comment]
Are you asking for CLI, or API?

**Comment by nicolaasjan** [comment]
I've tried it here with attaching my profile picture to [this video](https://www.youtube.com/watch?v=ci3OyvBvWnQ):

`ffmpeg -i in.mp4 -i gandalf.png -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic out.mp4`

```
ffmpeg -i in.mp4 -i gandalf.png -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic out.mp4
ffmpeg version N-103120-gc8b1f2bcc4-Nico-20210802 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/home/nico/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/nico/ffmpeg_build/include --extra-ldflags=-L/home/nico/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/nico/bin --extra-version=Nico-20210802 --enable-gpl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-openssl --enable-demuxer=dash --enable-libxml2 --enable-nonfree
  libavutil      57.  3.100 / 57.  3.100
  libavcodec     59.  4.100 / 59.  4.100
  libavformat    59.  4.101 / 59.  4.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  1.103 /  8.  1.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'in.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.4.101
  Duration: 00:13:20.30, start: 0.000000, bitrate: 808 kb/s
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 671 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
Input #1, png_pipe, from 'gandalf.png':
  Duration: N/A, bitrate: N/A
  Stream #1:0: Video: png, rgba(pc), 256x256 [SAR 2835:2835 DAR 1:1], 25 fps, 25 tbr, 25 tbn
Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 2, only the last option '-c:v:1 png' will be used.
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #1:0 -> #0:2 (png (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, mp4, to 'out.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.4.101
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 671 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:2: Video: png (mp4v / 0x7634706D), rgba(pc, progressive), 256x256 [SAR 2835:2835 DAR 1:1], q=2-31, 200 kb/s, 25 fps, 12800 tbn (attached pic)
    Metadata:
      encoder         : Lavc59.4.100 png
frame=    0 fps=0.0 q=-1.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A spframe=24007 fps=0.0 q=-1.0 Lq=-0.0 size=   79032kB time=00:13:20.29 bitrate= 809.0kbits/s speed=3.14e+03x    
video:65716kB audio:12505kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.036938%
```

![screenshot1](https://user-images.githubusercontent.com/14093220/130053705-4a187c04-189f-4f93-8e10-eef71b257111.png)

**Comment by ischmidt20** [comment]
> Are you asking for CLI, or API?

Preferably API but I'd take a command line solution too

> I've tried it here with ffmpeg with attaching my profile picture to this video
You'll have to figure out how to format that properly with `postprocessor_args`.

Thanks for the command, but yup, that's the problem. Doesn't appear to be an obvious way for yt-dlp to hand ffmpeg multiple input files.

**Comment by pukkandan** [comment]
Create a custom PP and call it before the `EmbedThumbnailPP`

Something like this (untested):

```py
class CustomThumbnailPP(PostProcessor):
	def run(self, info):
		info.setdefault('thumbnails', []).append({'filepath': your_file_path})
		return [], info


opts = {'postprocessors': [
	{'key': 'CustomThumbnail'},
	{'key': 'EmbedThumbnail'}
]}
with YoutubeDL(opts) as ydl:
	...
```

There are ways to use the `--postprocessor-args` or `--exec` to do what you want, but this way, you don't need to worry about the exact ffmpeg command being used (it has to be different b/w formats)

**Comment by nicolaasjan** [comment]
Yeah,
I just wanted to suggest the `--exec` option as well.
Made a `thumb.sh` script for `mp4` files and put it in `~/bin`, which is in my PATH.

```bash
#!/bin/bash
for i in *.mp4; do ffmpeg -i "${i}" -i "thumbnail.png" -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic "${i%.mp4}_thumb.mp4"; done
```

And then this worked:
`yt-dlp -f bestvideo"[height<=720][ext=mp4]"+bestaudio[ext=m4a]/best[ext=mp4]/best "https://www.youtube.com/watch?v=ci3OyvBvWnQ" --exec thumb.sh`

But your suggestion to create a custom PP is obviously better.
Does @ischmidt20 have to compile this himself?

**Comment by pukkandan** [comment]
@nicolaasjan He's not using yt-dlp from the command line, but embedding it in his own python script

**Comment by nicolaasjan** [comment]
> @nicolaasjan He's not using yt-dlp from the command line, but embedding it in his own python script

Oh, sorry.
He said: 

> but I'd take a command line solution too

**Comment by pukkandan** [comment]
> Does ischmidt20 have to compile this himself?

I was mainly answering this. Since he's making his own python script. The code I gave just goes inside that script

**Comment by ischmidt20** [comment]
OK, I think I figured this out. I added the following code within the download function in my script:

```
import yt_dlp.postprocessor.common
import youtube_dl.postprocessor.common

        class CustomThumbnailPP(module.postprocessor.common.PostProcessor):
            def run(self, info):
                info['thumbnails'] = [{'filepath': thumbnail, 'filename': thumbnail}]
                return [], info
        module.postprocessor.CustomThumbnailPP = CustomThumbnailPP

        ydl_opts['postprocessors'] = [{'key': 'CustomThumbnail'}, {'key': 'EmbedThumbnail'}]
```
I'm using `module.postprocessor.common.PostProcessor` because my script needs to work with both youtube-dl and yt-dlp, and `module` is an argument that is passed in to my download function.

I used `info['thumbnails'] = [{'filepath': thumbnail, 'filename': thumbnail}]` because when using a plugin (in this case, Paramount+), it seems `setdefault` just gets overwritten by whatever the plugin returns for the thumbnail. So I thought better to just set the thumbnail information directly, although feel free to point me towards a better alternative. I also set both `filepath` and `filename` because youtube-dl uses `filename`, so only `filepath` would be required for yt-dlp.

Finally, I had to set `module.postprocessor.CustomThumbnailPP = CustomThumbnailPP`, because if I did not do so, yt-dlp wouldn't be able to find my class using `globals()`. This was my workaround, but please again let me know if there is a less hacky alternative.

So this code here satisfies my question, I will now turn my attention towards embedding custom metadata using this same style. Previously I was passing them as `postprocessor_args` to ffmpeg, but if I'm creating custom classes to work with thumbnails, I might as well do the same for metadata.

Thank you both for your help!
