### ISSUE TITLE
[YouTube] Attempting to download a YouTube video with format 617 results in HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by TheMCNerd2017** [yt-dlp/yt-dlp#7312]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Any

### Provide a description that is worded well enough to be understood

Upon attempting to download the latest Kitboga video with formats 617+251 (yt-dlp chooses this format automatically due to my config), it attempts to download the m3u8 manifest, then fails right after with a HTTP 404 error when attempting to download video data. I am unsure what could be causing this issue to come up, as I've been able to download videos from this channel previously without any issues.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=Ok-YGKYF8JI']
[debug] User config "/data/data/com.termux/files/home/.config/yt-dlp/config": ['--no-mtime', '--ignore-errors', '--min-sleep-interval', '4', '--max-sleep-interval', '20', '--extractor-args', 'youtube:player_client=all', '-o', '/data/data/com.termux/files/home/storage/shared/Youtube/%(upload_date)s-%(title)s-%(id)s.%(ext)s', '--download-archive', '~/youtube_downloaded.txt', '-f', 'bv*+ba/b', '--concurrent-fragments', '4', '--remux-video', 'mkv/mp4', '--embed-thumbnail', '--sub-langs', 'all', '--embed-subs', '--write-info-json']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.3 (CPython aarch64 64bit) - Linux-4.14.295-gd22e104ecbc7-aarch64-with-libc (OpenSSL 3.1.0 14 Mar 2023, libc)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Loading archive file '/data/data/com.termux/files/home/youtube_downloaded.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=Ok-YGKYF8JI
[youtube] Ok-YGKYF8JI: Downloading webpage
[youtube] Ok-YGKYF8JI: Downloading android player API JSON
[youtube] Ok-YGKYF8JI: Downloading android embedded player API JSON
[youtube] Ok-YGKYF8JI: Downloading android music player API JSON
[youtube] Ok-YGKYF8JI: Downloading android creator player API JSON
[youtube] Ok-YGKYF8JI: Downloading android embedscreen player API JSON
[youtube] Ok-YGKYF8JI: Downloading web embedded client config
[youtube] Ok-YGKYF8JI: Downloading player 8c7583ff
[youtube] Ok-YGKYF8JI: Downloading web embedded player API JSON
[youtube] Ok-YGKYF8JI: Downloading web music client config
[youtube] Ok-YGKYF8JI: Downloading web music player API JSON
[youtube] Ok-YGKYF8JI: Downloading web creator player API JSON
[youtube] Ok-YGKYF8JI: Downloading web embedscreen player API JSON
[youtube] Ok-YGKYF8JI: Downloading tv embedded player API JSON
[youtube] Ok-YGKYF8JI: Downloading ios player API JSON
[youtube] Ok-YGKYF8JI: Downloading ios embedded player API JSON
[youtube] Ok-YGKYF8JI: Downloading ios music player API JSON
[youtube] Ok-YGKYF8JI: Downloading ios creator player API JSON
[youtube] Ok-YGKYF8JI: Downloading ios embedscreen player API JSON
[youtube] Ok-YGKYF8JI: Downloading mweb player API JSON
[youtube] Ok-YGKYF8JI: Downloading mweb embedscreen player API JSON
[debug] Loading youtube-nsig.8c7583ff from cache
WARNING: [youtube] Ok-YGKYF8JI: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = vNXedlfaB1OfDZMwTI ; player = https://www.youtube.com/s/player/8c7583ff/player_ias.vflset/en_US/base.js
[debug] [youtube] Signature function returned an exception; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] Ok-YGKYF8JI: Downloading m3u8 information
[youtube] Ok-YGKYF8JI: Downloading m3u8 information
[youtube] Ok-YGKYF8JI: Downloading m3u8 information
[youtube] Ok-YGKYF8JI: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Ok-YGKYF8JI: Downloading 1 format(s): 617+251
[info] There's no subtitles for the requested languages
Deleting existing file /data/data/com.termux/files/home/storage/shared/Youtube/20230613-Scamming a Car Warranty Scammer-Ok-YGKYF8JI.webp
[info] Downloading video thumbnail 48 ...
[info] Writing video thumbnail 48 to: /data/data/com.termux/files/home/storage/shared/Youtube/20230613-Scamming a Car Warranty Scammer-Ok-YGKYF8JI.webp
[info] Writing video metadata as JSON to: /data/data/com.termux/files/home/storage/shared/Youtube/20230613-Scamming a Car Warranty Scammer-Ok-YGKYF8JI.info.json
WARNING: webm doesn't support embedding a thumbnail, mkv will be used
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1686788120/ei/uAOKZJumOM-Wir4Pv-uAwAU/ip/2607:fb90:b539:6023:1ab3:d022:7e02:dec8/id/3a4f9818a605f092/itag/617/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D478619579%3Bdur%3D1870.899%3Bgir%3Dyes%3Bitag%3D303%3Blmt%3D1686701601261180/hls_chunk_host/rr5---sn-vgqskn6s.googlevideo.com/mh/t0/mm/31,26/mn/sn-vgqskn6s,sn-p5qlsnrl/ms/au,onr/mv/m/mvi/5/pl/40/initcwndbps/571250/vprv/1/playlist_type/DVR/dover/13/txp/3319224/mt/1686766172/fvip/1/short_key/1/keepalive/yes/fexp/24007246/beids/24350017/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIgAteQC1NjZZSvfkg6r4bUFDX76xEoGz7RtPBE-w78zB4CIQDMtagmHlDkGPCDVgD2yOgDIaQItaQxYtvwPIXhehZ06Q%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRQIhAOghVVXEqi4WRuE9zpni2npeNuFJoAOtKEelLXMKvuJIAiBiA_QLRoU_tuL8K1kzWvJIBIE1kv7awQBp-sVvfFUGnw%3D%3D/playlist/index.m3u8"
[download] Sleeping 4.82 seconds ...
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3229, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2970, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/downloader/hls.py", line 66, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
I can't reproduce this with 2023.03.04 or master. 
```shell
$ yt-dlp --ignore-config -f 617+251 --extractor-args "youtube:player_client=all" Ok-YGKYF8JI
[youtube] Extracting URL: https://www.youtube.com/watch?v=Ok-YGKYF8JI
[youtube] Ok-YGKYF8JI: Downloading webpage
[youtube] Ok-YGKYF8JI: Downloading android player API JSON
[youtube] Ok-YGKYF8JI: Downloading android embedded player API JSON
[youtube] Ok-YGKYF8JI: Downloading android music player API JSON
[youtube] Ok-YGKYF8JI: Downloading android creator player API JSON
[youtube] Ok-YGKYF8JI: Downloading android embedscreen player API JSON
[youtube] Ok-YGKYF8JI: Downloading web embedded client config
[youtube] Ok-YGKYF8JI: Downloading player 8c7583ff
[youtube] Ok-YGKYF8JI: Downloading web embedded player API JSON
[youtube] Ok-YGKYF8JI: Downloading web music client config
[youtube] Ok-YGKYF8JI: Downloading web music player API JSON
[youtube] Ok-YGKYF8JI: Downloading web creator player API JSON
[youtube] Ok-YGKYF8JI: Downloading web embedscreen player API JSON
[youtube] Ok-YGKYF8JI: Downloading tv embedded player API JSON
[youtube] Ok-YGKYF8JI: Downloading ios player API JSON
[youtube] Ok-YGKYF8JI: Downloading ios embedded player API JSON
[youtube] Ok-YGKYF8JI: Downloading ios music player API JSON
[youtube] Ok-YGKYF8JI: Downloading ios creator player API JSON
[youtube] Ok-YGKYF8JI: Downloading ios embedscreen player API JSON
[youtube] Ok-YGKYF8JI: Downloading mweb player API JSON
[youtube] Ok-YGKYF8JI: Downloading mweb embedscreen player API JSON
[youtube] Ok-YGKYF8JI: Downloading m3u8 information
[youtube] Ok-YGKYF8JI: Downloading m3u8 information
[youtube] Ok-YGKYF8JI: Downloading m3u8 information
[youtube] Ok-YGKYF8JI: Downloading m3u8 information
[info] Ok-YGKYF8JI: Downloading 1 format(s): 617+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 374
[download] Destination: Scamming a Car Warranty Scammer [Ok-YGKYF8JI].f617.mp4
[download]   1.7% of ~ 153.09MiB at    4.32MiB/s ETA 00:34 (frag 3/374)^C
ERROR: Interrupted by user
```

**Comment by gamer191** [comment]
@TheMCNerd2017 Can you still reproduce this, or was it a temporary issue on youtube's side?
If yes, can you reproduce this after updating to nightly (`--update-to nightly`)?

**Comment by TheMCNerd2017** [comment]
> @TheMCNerd2017 Can you still reproduce this, or was it a temporary issue on youtube's side? If yes, can you reproduce this after updating to nightly (`--update-to nightly`)?
> 
> EDIT: if you can reproduce this in nightly, can you reproduce this with `--ignore-config -f 617 --extractor-args "youtube:player_client=all"`

I can't reproduce the issue anymore as it seemed to have been a temporary issue on YouTube's side (I tried again several hours later and the video downloaded with no errors). Also sorry for the late response.
