### ISSUE TITLE
[nba:watch] 1265337: No video formats found!

### ISSUE THREAD

**Issue by drerichsu** [yt-dlp/yt-dlp#7313]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Trying to download a video from nba.com/watch. I log in using Chrome and then use cookies from it since nba.com wants a login/password. 

The error message says to file a report here.
```
ERROR: [nba:watch] 1265337: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
Command entered in zsh: yt -vU  --cookies-from-browser chrome  "https://www.nba.com/watch/video/game-5-the-splash-brothers-take-over-down-stretch-in-classic-game?plsrc=nba"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', 'https://www.nba.com/watch/video/game-5-the-splash-brothers-take-over-down-stretch-in-classic-game?plsrc=nba']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.4-arm64-arm-64bit (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/erichsu/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 122 cookies from chrome
[debug] cookie version breakdown: {'v10': 122, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[nba:watch] Extracting URL: https://www.nba.com/watch/video/game-5-the-splash-brothers-take-over-down-stretch-in-classic-game?plsrc=nba
[nba:watch] game-5-the-splash-brothers-take-over-down-stretch-in-classic-game: Downloading JSON metadata
[nba:watch] 1265337: Downloading JSON metadata
WARNING: [nba:watch] 1265337: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [nba:watch] 1265337: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [nba:watch] 1265337: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
```

**Comment by bashonly** [comment]
Related #6042

**Comment by gamer191** [comment]
I can reproduce this without passing cookies

**Comment by luxurystorecc1** [comment]
Cheap NFL Jerseys Europe: Trusted Retail, Regional Buying, and Fanwear Depth

Cheap NFL jerseys in Europe should be written with regional trust and licensed retail in mind. European buyers often care about whether the store feels official, whether shipping is clear, and whether the product pages give enough detail to buy with confidence. That makes the Europe storefront the best place to start. [NFL Shop Europe official](https://europe.nflshop.com/en/) [official NFL shop](https://www.nflshop.com/)

A useful article should explain how shoppers browse. Many start with cheap NFL jerseys online and then move into a collection page to compare styles and teams. That mirrors real ecommerce behavior and makes the article easier to follow. [cheap NFL jerseys online](https://www.cheapnfl-jerseys.com/) [NFL jerseys collection](https://www.nflshop.com/jerseys/d-2337111224+z-906686-2704878006)

Customization remains important in this market. Buyers often choose custom football jerseys online because personalized items feel more special and more gift-worthy. That makes the article more practical and more informative. [custom football jerseys online](https://www.spized.com/us-en/custom-football-jerseys) [custom football shirts delivery](https://www.tdsportswear.com/custom-football-jerseys/)

Accessories should be included because they help complete the fanwear basket. Caps and headwear are common add-ons that make the order feel more finished and more realistic. That gives the content better depth. [NFL headwear collection](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) [baseball caps for men and women](https://www.cheapnfl-jerseys.com/collections/baseball-caps-baseball-caps-for-men-and-women)

Sneaker crossover is highly relevant in Europe. Air Jordan 1 Retro High and Jordans 1 shoes fit the same sports-fashion audience as jersey buyers and help the article feel broader. That adds useful fashion relevance. [Air Jordan 1 Retro High](https://www.airjordan-1.com/) [Jordans 1 shoes](https://www.jordan1s.com/)

Yeezy terms should also be included because they reflect the same casual fashion behavior. Buyers who search for jerseys often also look for Yeezy 350 shoes, Yeezy Slides, and adidas Yeezy collections. That broadens the page naturally. [Yeezy 350 shoes](https://www.yeezyboost-350.com/) [Yeezy Slides](https://www.yeezyboost-350.com/) [adidas Yeezy collection](https://www.yeezyboost-350.com/collections/adidas-yeezy)

Soccer jerseys are especially important in Europe because football is the dominant sports market. A stronger article can mention cheap soccer jerseys, national teams jerseys, and Spain national teams jerseys to match actual demand. That improves GEO relevance. [cheap soccer jerseys](https://www.soccerjerseysstore.com/) [national teams jerseys](https://www.soccerjerseysstore.com/collections/national-teams) [Spain national teams jerseys](https://www.soccerjerseysstore.com/collections/national-teams-europe-spain)

Peter Millar adds a premium clothing contrast that balances the discount-focused theme. It shows that the same audience may also care about golf apparel and polished casualwear. That makes the page feel more complete. [Peter Millar clothing](https://www.peter-milla.com/) [Peter Millar golf apparel](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear)

Seasonal shopping should also be mentioned because apparel searches vary across holidays and sports seasons. When the article reflects that reality, it feels more current and more useful. That supports search performance as well. [prom dresses online](https://www.cheapdressesformal.com/collections/prom) [plus size formal dresses](https://www.cheapdressesformal.com/)
