### ISSUE TITLE
Request to add cinetimes.org site 

### ISSUE THREAD

**Issue by jfix** [yt-dlp/yt-dlp#7317]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

- Single video: https://cinetimes.org/t/le-diable-boiteux

### Provide a description that is worded well enough to be understood

I would like to request the addition of a new website that hosts old French movies: https://cinetimes.org/. After having checked the list of existing site extractors, I noticed that the site is not listed.

Trying the generic extractor throws the error shown in the debug output below.

Thank you very much for kindly considering adding an extractor for this site.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://cinetimes.org/t/le-diable-boiteux']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.4-arm64-arm-64bit (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://cinetimes.org/t/le-diable-boiteux
[generic] le-diable-boiteux: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] le-diable-boiteux: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://cinetimes.org/t/le-diable-boiteux
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://cinetimes.org/t/le-diable-boiteux
```

**Comment by jfix** [comment]
As indicated by @WebDLLover these films are hosted elsewhere, some on YouTube others on archive.org.

It is therefore possible, at least as a workaround, to inspect the webpage, find the link to the embedded video, and then run `yt-dlp` with that URL, like so:

```
$ /opt/homebrew/bin/yt-dlp https://archive.org/embed/FilmsVaries/1948+-+Le+Diable+Boiteux.avi
[archive.org] Extracting URL: https://archive.org/embed/FilmsVaries/1948+-+Le+Diable+Boiteux.avi
[archive.org] FilmsVaries: Downloading webpage
[archive.org] FilmsVaries: Downloading JSON metadata
[info] FilmsVaries/1948 - Le Diable Boiteux.avi: Downloading 1 format(s): 2
[download] Destination: 1948 - Le Diable Boiteux.avi [FilmsVaries⧸1948 - Le Diable Boiteux.avi].avi
[download]   2.1% of    1.37GiB at  855.36KiB/s ETA 27:19
```

So I guess that this ticket does not merit a high priority.
