### ISSUE TITLE
[niconico] pagination for series extraction broken

### ISSUE THREAD

**Issue by raumigit** [yt-dlp/yt-dlp#7320]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

I tried to download a series from  Niconico.

Series extraction has been implemented in the past (https://github.com/yt-dlp/yt-dlp/pull/3935) , but it is output as Unsupported URL.

I thought it was a general error, so I tried it after a while, but the same error occurred, and it was a problem that occurred only with the URL of the Niconico series.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.nicovideo.jp/user/48313347/series/169055']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109535-gfcd557a2c2-20230106 (setts), ffprobe N-109535-gfcd557a2c2-20230106
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.nicovideo.jp/user/48313347/series/169055
[generic] 169055: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 169055: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.nicovideo.jp/user/48313347/series/169055
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nicovideo.jp/user/48313347/series/169055
```

**Comment by bashonly** [comment]
This was fixed in c86e433c35fe5da6cb29f3539eef97497f84ed38

Run `yt-dlp --update-to nightly` and try again

**Comment by raumigit** [comment]
> This was fixed in [c86e433](https://github.com/yt-dlp/yt-dlp/commit/c86e433c35fe5da6cb29f3539eef97497f84ed38)
> 
> Run `yt-dlp --update-to nightly` and try again

It seems that most of the series can be handled, but the acquisition range is only one page, and it seems that the second page and beyond cannot be acquired.

Specifically, Niconico is designed to display 100 videos per page, and if the total number of videos is 101 or more, Niconico will create the next page, but the extraction does not support those pages.

**Comment by raumigit** [comment]
I tried almost the same thing on the same Niconico mobile site `https://sp.nicovideo.jp/series/110226`.
When debugging with '-vU', the following behavior was observed.

```shell
[debug] Command-line config: ['-vU', '-P', './test02', 'https://sp.nicovideo.jp/series/110226']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.06.21.035858 [42f2d40b4] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109535-gfcd557a2c2-20230106 (setts), ffprobe N-109535-gfcd557a2c2-20230106
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1848 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.06.21.035858, Current version: nightly@2023.06.21.035858
Current Build Hash: c875eb856f5e4cb173b357cd6536d8d091211a926286f1305d94556cca70cf14
yt-dlp is up to date (nightly@2023.06.21.035858)
[niconico:series] Extracting URL: https://sp.nicovideo.jp/series/110226
[niconico:series] 110226: Downloading webpage
WARNING: [niconico:series] unable to extract title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[download] Downloading playlist: 110226
[niconico:series] Playlist 110226: Downloading 0 items
[download] Finished downloading playlist: 110226
```
