### ISSUE TITLE
[TV4] Common TV4 Play video-URL is unsupported (https://www.tv4play.se/video/...)

### ISSUE THREAD

**Issue by aejdl** [yt-dlp/yt-dlp#7321]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Sweden

### Provide a description that is worded well enough to be understood

A considerable number of video-pages on tv4play.se have gotten the following URL-format recently: `https://www.tv4play.se/video/...`. 
However, when running yt-dlp (latest master, i.e. 2023.03.04) on these it's stated that the URL is not supported. 

Example:

```
yt-dlp -vU https://www.tv4play.se/video/3170e5d3141aeecbd6b6

[debug] Command-line config: ['-vU', 'https://www.tv4play.se/video/3170e5d3141aeecbd6b6']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.8.12 (CPython arm64 64bit) - macOS-12.1-arm64-arm-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1845 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.tv4play.se/video/3170e5d3141aeecbd6b6
[generic] 3170e5d3141aeecbd6b6: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 3170e5d3141aeecbd6b6: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tv4play.se/video/3170e5d3141aeecbd6b6
Traceback (most recent call last):
  File "/Users/aejdl/Virtualenvs/venv/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1552, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/aejdl/Virtualenvs/venv/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1628, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/aejdl/Virtualenvs/venv/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 704, in extract
    ie_result = self._real_extract(url)
  File "/Users/aejdl/Virtualenvs/venv/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tv4play.se/video/3170e5d3141aeecbd6b6
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.tv4play.se/video/3170e5d3141aeecbd6b6']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.8.12 (CPython arm64 64bit) - macOS-12.1-arm64-arm-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1845 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.tv4play.se/video/3170e5d3141aeecbd6b6
[generic] 3170e5d3141aeecbd6b6: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 3170e5d3141aeecbd6b6: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tv4play.se/video/3170e5d3141aeecbd6b6
Traceback (most recent call last):
  File "/Users/aejdl/Virtualenvs/venv/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1552, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/aejdl/Virtualenvs/venv/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1628, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/aejdl/Virtualenvs/venv/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 704, in extract
    ie_result = self._real_extract(url)
  File "/Users/aejdl/Virtualenvs/venv/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tv4play.se/video/3170e5d3141aeecbd6b6
```

**Comment by bashonly** [comment]
the video on that page is DRM-protected. do you have a non-DRM example
