### ISSUE TITLE
Nostr Videos

### ISSUE THREAD

**Issue by justingoldberg** [yt-dlp/yt-dlp#7350]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Hi,

Nostr uses websockets for relays to content (which is called notes). Also some media content is being hosted on https://nostr.build while the Nostr protocol is still being improved to the point where the relays store content beyond text (but the url that I am reporting appears to not use it).

The content uses the same URI on most web clients:
https://iris.to/note1tuerqfkkz3djxeh8lky93rlqh4jyctxhcfv205v2c8kzqerncqvq6q2hqt
https://coracle.social/note1tuerqfkkz3djxeh8lky93rlqh4jyctxhcfv205v2c8kzqerncqvq6q2hqt

Note that I was able to download it in Chrome by clicking the three dotted menu and choosing download.

The protocol is documented here:

https://github.com/nostr-protocol/nostr

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://iris.to/note1tuerqfkkz3djxeh8lky93rlqh4jyctxhcfv205v2c8kzqerncqvq6q2hqt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.3 (CPython x86_64 64bit) - macOS-13.3.1-x86_64-i386-64bit (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://iris.to/note1tuerqfkkz3djxeh8lky93rlqh4jyctxhcfv205v2c8kzqerncqvq6q2hqt
[generic] note1tuerqfkkz3djxeh8lky93rlqh4jyctxhcfv205v2c8kzqerncqvq6q2hqt: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] note1tuerqfkkz3djxeh8lky93rlqh4jyctxhcfv205v2c8kzqerncqvq6q2hqt: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://iris.to/note1tuerqfkkz3djxeh8lky93rlqh4jyctxhcfv205v2c8kzqerncqvq6q2hqt
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://iris.to/note1tuerqfkkz3djxeh8lky93rlqh4jyctxhcfv205v2c8kzqerncqvq6q2hqt
```

**Comment by gamer191** [comment]
Solving this would probably require one of the following:
1. waiting for #5103
2. hardcoding the list of URLs
3. adding support to the generic extractor ("I was able to download it in Chrome by clicking the three dotted menu and choosing download" hints that that might be possible)

**Comment by gamer191** [comment]
One more observation-nostr requests the `web+nostr://` protocol. That said, it would probably be tricky to add support for it, since nostr is decentralised and that protocol could probably be assigned to any nostr client
![screenshot](https://github.com/yt-dlp/yt-dlp/assets/83270075/8e956f28-0731-4352-a879-69f9831f01ef)

**Comment by gamer191** [comment]
It seems to use the websocket protocol. I don't know if that's required, or if yt-dlp supports it
