### ISSUE TITLE
 Postprocessing: No such file or directory

### ISSUE THREAD

**Issue by AlexandreBourrieau** [yt-dlp/yt-dlp#7352]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Hello,

With lastest version : 

yt-dlp.exe https://player.vimeo.com/video/793495973?h=a2a3690d00

give me error : 
ERROR: Postprocessing: file:How to Launch Ansys Fluent and Customize UI – Lesson 3 [793495973].fdash-fastly_skyfire_sep-video-e381989b.mp4: No such file or directory

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe https://player.vimeo.com/video/793495973?h=a2a3690d00 -vU
[debug] Command-line config: ['https://player.vimeo.com/video/793495973?h=a2a3690d00', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.1-2021-01-01-full_build-www.gyan.dev, ffprobe 4.3.1-2021-01-01-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[vimeo] Extracting URL: https://player.vimeo.com/video/793495973?h=a2a3690d00
[vimeo] 793495973: Downloading webpage
[vimeo] 793495973: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 793495973: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 793495973: Downloading fastly_skyfire m3u8 information
[vimeo] 793495973: Downloading fastly_skyfire m3u8 information
[vimeo] 793495973: Downloading akfire_interconnect_quic MPD information
[vimeo] 793495973: Downloading akfire_interconnect_quic MPD information
[vimeo] 793495973: Downloading fastly_skyfire MPD information
[vimeo] 793495973: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 793495973: Downloading 1 format(s): dash-fastly_skyfire_sep-video-e381989b+dash-fastly_skyfire_sep-audio-75383e65

[debug] Invoking dashsegments downloader on "https://skyfire.vimeocdn.com/1687171316-0xbd64052a290be296f252de848c354df46c861aa2/35280a1a-9d91-44d6-8949-4f8d04b11df9/sep/video/3e513570,d0fb08b4,db729c2c,dbf43fb9,e381989b/audio/1e89c066,367e501a,75383e65/master.mpd?base64_init=1&query_string_ranges=1"
[download] How to Launch Ansys Fluent and Customize UI – Lesson 3 [793495973].fdash-fastly_skyfire_sep-video-e381989b.mp4 has already been downloaded
[download] 100% of   72.34MiB
[debug] Invoking dashsegments downloader on "https://skyfire.vimeocdn.com/1687171316-0xbd64052a290be296f252de848c354df46c861aa2/35280a1a-9d91-44d6-8949-4f8d04b11df9/sep/video/3e513570,d0fb08b4,db729c2c,dbf43fb9,e381989b/audio/1e89c066,367e501a,75383e65/master.mpd?base64_init=1&query_string_ranges=1"
[download] How to Launch Ansys Fluent and Customize UI – Lesson 3 [793495973].fdash-fastly_skyfire_sep-audio-75383e65.m4a has already been downloaded
[download] 100% of    7.14MiB
[Merger] Merging formats into "How to Launch Ansys Fluent and Customize UI – Lesson 3 [793495973].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:How to Launch Ansys Fluent and Customize UI – Lesson 3 [793495973].fdash-fastly_skyfire_sep-video-e381989b.mp4" -i "file:How to Launch Ansys Fluent and Customize UI – Lesson 3 [793495973].fdash-fastly_skyfire_sep-audio-75383e65.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:How to Launch Ansys Fluent and Customize UI – Lesson 3 [793495973].temp.mp4"
[debug] ffmpeg version 4.3.1-2021-01-01-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
file:How to Launch Ansys Fluent and Customize UI – Lesson 3 [793495973].fdash-fastly_skyfire_sep-video-e381989b.mp4: No such file or directory

ERROR: Postprocessing: file:How to Launch Ansys Fluent and Customize UI – Lesson 3 [793495973].fdash-fastly_skyfire_sep-video-e381989b.mp4: No such file or directory
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3323, in process_info
  File "yt_dlp\YoutubeDL.py", line 3502, in post_process
  File "yt_dlp\YoutubeDL.py", line 3484, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3462, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 831, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 324, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 362, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:How to Launch Ansys Fluent and Customize UI – Lesson 3 [793495973].fdash-fastly_skyfire_sep-video-e381989b.mp4: No such file or directory
```

**Comment by pukkandan** [comment]
Can you try a shorter filename?

**Comment by AlexandreBourrieau** [comment]
Yes I'm sorry it just my path is too large... sorry
