### ISSUE TITLE
Failed to download m3u8 information: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by stemy2** [yt-dlp/yt-dlp#7363]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Switzerland

### Provide a description that is worded well enough to be understood

Hello,

I can't download anything from RTS, the only thing i get is a HTTP 403 error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.rts.ch/play/tv/histoire-vivante/video/hebron-palestine-la-fabrique-de-loccupation?urn=urn:rts:video:14029693']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-75-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2020.06.20, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[SRGSSRPlay] Extracting URL: https://www.rts.ch/play/tv/histoire-vivante/video/hebron-palestine-la-fabrique-de-loccupation?urn=urn:rts:video:14029693
[SRGSSR] Extracting URL: srgssr:rts:video:14029693
[SRGSSR] 14029693: Downloading JSON metadata
[SRGSSR] 14029693: Downloading m3u8 information
WARNING: [SRGSSR] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [SRGSSR] 14029693: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [SRGSSR] 14029693: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by stemy2** [comment]
I"m using a vpn too, so why doesn't it work for me?

**Comment by gamer191** [comment]
> I wanted to say when using a vpn make sure u can play the video in the browser because if you cant play it you cant download it but was not sure if u where using a vpn or not

I'm not using a VPN, but this is the standard geo-block error for this site

```
[debug] Command-line config: ['https://www.rts.ch/play/tv/histoire-vivante/video/hebron-palestine-la-fabrique-de-loccupation?urn=urn:rts:video:14029693', '--verbose']
[debug] User config "C:\Users\jaybu\AppData\Roaming\yt-dlp\config.txt": ['--ffmpeg-location', 'C:\\Users\\jaybu\\ffmpeg\\bin\\ffmpeg.exe', '-P', 'C:\\Users\\jaybu\\youtube.dl', '--no-mtime']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.06.17.224306 [01aba2519] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110410-g78f95f1088-20230428 (setts), ffprobe N-110410-g78f95f1088-20230428, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1845 extractors
[SRGSSRPlay] Extracting URL: https://www.rts.ch/play/tv/histoire-vivante/video/hebron-palestine-la-fabrique-de-loccupation?urn=urn:rts:video:14029693
[SRGSSR] Extracting URL: srgssr:rts:video:14029693
[SRGSSR] 14029693: Downloading JSON metadata
ERROR: [SRGSSR] 14029693: For legal reasons, this video is only available in Switzerland.
This video is available in Switzerland.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1552, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1628, in __extract_info
  File "yt_dlp\extractor\common.py", line 704, in extract
  File "yt_dlp\extractor\srgssr.py", line 82, in _real_extract
  File "yt_dlp\extractor\srgssr.py", line 73, in _get_media_data
  File "yt_dlp\extractor\common.py", line 1173, in raise_geo_restricted
yt_dlp.utils.GeoRestrictedError: [SRGSSR] 14029693: For legal reasons, this video is only available in Switzerland.
```

**Comment by pzhlkj6612** [comment]
I got "Ce contenu n’est plus disponible." (Eng: "This content is no longer available.") in the webpage of https://www.rts.ch/play/tv/histoire-vivante/video/hebron-palestine-la-fabrique-de-loccupation?urn=urn:rts:video:14029693. The video appears to be expired.

Can anyone provide a now one?
