### ISSUE TITLE
Twitter: ERROR: 'NoneType' object has no attribute 'format'

### ISSUE THREAD

**Issue by RingoTheDog** [yt-dlp/yt-dlp#7379]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.21** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

canada

### Provide a description that is worded well enough to be understood

All of the following example Twitter URLs fail with 
ERROR: 'NoneType' object has no attribute 'format'

https://twitter.com/SpokedZ/status/1642176959760285696

https://twitter.com/Hockey_Robinson/status/1661010129544941569

https://twitter.com/IIHFHockey/status/1661035921960218625

https://twitter.com/Hockey_Robinson/status/1600943989871767552

https://twitter.com/MainTeamSports/status/1657831400660140033

...thanks
Ringo

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
>yt-dlp.py -v "https://twitter.com/SpokedZ/status/1642176959760285696"
[debug] Command-line config: ['-v', 'https://twitter.com/SpokedZ/status/1642176959760285696']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.21 [42f2d40b4] (zip)
[debug] Python 3.10.5 (CPython AMD64 64bit) - Windows-10-10.0.14393-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1848 extractors
ERROR: 'NoneType' object has no attribute 'format'
Traceback (most recent call last):
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 1631, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 705, in extract
    self.initialize()
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 609, in initialize
    username, password = self._get_login_info()
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 1335, in _get_login_info
    username, password = self._get_netrc_login_info(netrc_machine)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 1300, in _get_netrc_login_info
    cmd = self.get_param('netrc_cmd', '').format(netrc_machine)
AttributeError: 'NoneType' object has no attribute 'format'
```

**Comment by RingoTheDog** [comment]
SORRY..i did not see this:
https://github.com/yt-dlp/yt-dlp/issues/7367

My bad!

**Comment by RingoTheDog** [comment]
SORRY..i did not see this:
https://github.com/yt-dlp/yt-dlp/issues/7367

My bad!
