### ISSUE TITLE
--trim-filenames no-op since 2023.06.21 release

### ISSUE THREAD

**Issue by selfisekai** [yt-dlp/yt-dlp#7399]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

--trim-filenames does not work anymore, resulting in fs errors on download. this has previously worked on 2023.03.04, but stopped as of 2023.06.21 and was not fixed in 2023.06.22

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://twitter.com/gromotapl/status/1672167236302249984', '-v', '--trim-filenames', '32']
[debug] User config "/home/lauren/.config/yt-dlp/config": ['--concurrent-fragments', '8', '--netrc', '--trim-filenames', '64', '--sub-langs', 'all,-live_chat', '--embed-subs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06]
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.3.8-0-edge-x86_64-with (OpenSSL 3.1.1 30 May 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
WARNING: [twitter] Failed to parse .netrc: No authenticators for twitter (None, line None)
[twitter] Extracting URL: https://twitter.com/gromotapl/status/1672167236302249984
[twitter] 1672167236302249984: Downloading guest token
[twitter] 1672167236302249984: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1672167123827736577
[twitter] 1672167236302249984: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, br, size, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1672167123827736577: Downloading 1 format(s): http-2176
[info] There are no subtitles for the requested languages
[debug] Invoking http downloader on "https://video.twimg.com/ext_tw_video/1672167123827736577/pu/vid/1280x720/poW_vSX7jSJM3NZh.mp4?tag=12"
ERROR: unable to open for writing: [Errno 36] Filename too long: 'J.E. gromota - Mentzen： Każdego pracującego Polaka będzie stać na dom, grill, trawę, dwa samochody i wakacje - Ale to nie jest utopia według Pana？ Ale to już było w latach 50 w USA! Oglądał Pan seriale？ Takie domki pod miastem [1672167123827736577].mp4.part'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 663, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 2031, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] Filename too long: 'J.E. gromota - Mentzen： Każdego pracującego Polaka będzie stać na dom, grill, trawę, dwa samochody i wakacje - Ale to nie jest utopia według Pana？ Ale to już było w latach 50 w USA! Oglądał Pan seriale？ Takie domki pod miastem [1672167123827736577].mp4.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/http.py", line 273, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 245, in wrapper
    retry.error_callback(err, 1, 0)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 231, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 5636, in report_retry
    raise e
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 240, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 251, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 665, in sanitize_open
    stream = open(filename, open_mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] Filename too long: 'J.E. gromota - Mentzen： Każdego pracującego Polaka będzie stać na dom, grill, trawę, dwa samochody i wakacje - Ale to nie jest utopia według Pana？ Ale to już było w latach 50 w USA! Oglądał Pan seriale？ Takie domki pod miastem [1672167123827736577].mp4.part'
```

**Comment by pukkandan** [comment]
Looks like https://github.com/yt-dlp/yt-dlp/issues/2314. Are you sure it works on older versions?

**Comment by pukkandan** [comment]
Nope

```
❯ yt-dlp.exe --ignore-conf -v --trim 32 --update-to 2023.03.04 https://twitter.com/gromotapl/status/1672167236302249984
[debug] Command-line config: ['--ignore-conf', '-v', '--trim', '32', '--update-to', '2023.03.04', 'https://twitter.com/gromotapl/status/1672167236302249984']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n5.1.2-8-g5746987bad-20221204 (fdk,setts), ffprobe N-109332-g45ab5307a6-20221201, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Extractor Plugins: SamplePluginIE, sample+AGB+NSIG (YoutubeIE)
[debug] Post-Processor Plugins: ReturnYoutubeDislikePP, SamplePluginPP
[debug] Plugin directories: ['D:\\Programs\\Terminal\\yt-dlp-plugins\\ReturnYoutubeDislike\\yt_dlp_plugins', 'D:\\Programs\\Terminal\\yt-dlp-plugins\\sample-plugins\\yt_dlp_plugins', 'D:\\Programs\\Terminal\\yt-dlp-plugins\\YTAgeGateBypass\\yt_dlp_plugins', 'D:\\Programs\\Terminal\\yt-dlp-plugins\\YTNSigProxy\\yt_dlp_plugins']
[debug] Loaded 1787 extractors
Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[twitter] Extracting URL: https://twitter.com/gromotapl/status/1672167236302249984
[twitter] 1672167236302249984: Downloading guest token
[twitter] 1672167236302249984: Downloading JSON metadata
[debug] [twitter] Extracting from video info: 1672167123827736577
[twitter] 1672167236302249984: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1672167123827736577: Downloading 1 format(s): http-2176
[debug] Invoking http downloader on "https://video.twimg.com/ext_tw_video/1672167123827736577/pu/vid/1280x720/poW_vSX7jSJM3NZh.mp4?tag=12"
[download] Unable to open file: [Errno 22] Invalid argument: 'J.E. gromota - Mentzen： Każdego pracującego Polaka będzie stać na dom, grill, trawę, dwa samochody i wakacje - Ale to nie jest utopia według Pana？ Ale to już było w latach 50 w USA! Oglądał Pan seriale？ Takie domki pod miastem [1672167123827736577].mp4.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'J.E. gromota - Mentzen： Każdego pracującego Polaka będzie stać na dom, grill, trawę, dwa samochody i wakacje - Ale to nie jest utopia według Pana？ Ale to już było w latach 50 w USA! Oglądał Pan seriale？ Takie domki pod miastem [1672167123827736577].mp4.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'J.E. gromota - Mentzen： Każdego pracującego Polaka będzie stać na dom, grill, trawę, dwa samochody i wakacje - Ale to nie jest utopia według Pana？ Ale to już było w latach 50 w USA! Oglądał Pan seriale？ Takie domki pod miastem [1672167123827736577].mp4.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: 'J.E. gromota - Mentzen： Każdego pracującego Polaka będzie stać na dom, grill, trawę, dwa samochody i wakacje - Ale to nie jest utopia według Pana？ Ale to już było w latach 50 w USA! Oglądał Pan seriale？ Takie domki pod miastem [1672167123827736577].mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils.py", line 661, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 272, in download
    try:
  File "yt_dlp\downloader\common.py", line 228, in wrapper
  File "yt_dlp\utils.py", line 6141, in __iter__
  File "yt_dlp\downloader\common.py", line 221, in error_callback
    def undo_temp_name(self, filename):
  File "yt_dlp\utils.py", line 6149, in report_retry
  File "yt_dlp\downloader\common.py", line 230, in wrapper
    def error_callback(err, count, retries, *, fd):
  File "yt_dlp\downloader\common.py", line 241, in sanitize_open
    except OSError as err:
  File "yt_dlp\utils.py", line 664, in sanitize_open
OSError: [Errno 22] Invalid argument: 'J.E. gromota - Mentzen： Każdego pracującego Polaka będzie stać na dom, grill, trawę, dwa samochody i wakacje - Ale to nie jest utopia według Pana？ Ale to już było w latach 50 w USA! Oglądał Pan seriale？ Takie domki pod miastem [1672167123827736577].mp4.part'
```

**Comment by selfisekai** [comment]
I noticed it stopped working after upgrade. but idk, maybe somehow I wasn't downloading anything with a dot in title
