### ISSUE TITLE
Why now I must need to add <--proxy""> to download from youtube which I can do it without it before.

### ISSUE THREAD

**Issue by Thalia500** [yt-dlp/yt-dlp#7415]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I enable the globle and I can watch the video in the web but I can't access the URL by cmd while I can do it before. I just want to know why it changes because I don't remember anything I do which may impact it.
Here I use the URL https://www.youtube.com/watch?v=7KaI3PxPuVo

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -F https://www.youtube.com/watch?v=7KaI3PxPuVo
[debug] Command-line config: ['-vU', '-F', 'https://www.youtube.com/watch?v=7KaI3PxPuVo']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.9 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-110972-gbaa9fccf8d-20230601 (setts), ffprobe N-110972-gbaa9fccf8d-20230601, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-None, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'http://127.0.0.1:1080', 'https': 'http://127.0.0.1:1080', 'ftp': 'http://127.0.0.1:1080'}
[debug] Loaded 1844 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
[youtube] Extracting URL: https://www.youtube.com/watch?v=7KaI3PxPuVo
[youtube] 7KaI3PxPuVo: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
[youtube] 7KaI3PxPuVo: Downloading android player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (1/3)...
[youtube] 7KaI3PxPuVo: Downloading android player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (2/3)...
[youtube] 7KaI3PxPuVo: Downloading android player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (3/3)...
[youtube] 7KaI3PxPuVo: Downloading android player API JSON
[youtube] 7KaI3PxPuVo: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
[youtube] 7KaI3PxPuVo: Downloading web player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (1/3)...
[youtube] 7KaI3PxPuVo: Downloading web player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (2/3)...
[youtube] 7KaI3PxPuVo: Downloading web player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (3/3)...
[youtube] 7KaI3PxPuVo: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。> (caused by URLError(ConnectionRefusedError(10061, '由于目标计算机积极拒绝，无法连接。', None, 10061, None)))
ERROR: [youtube] 7KaI3PxPuVo: Unable to download API page: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法
连接。> (caused by URLError(ConnectionRefusedError(10061, '由于目标计算机积极拒绝，无法连接。', None, 10061, None)))
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 704, in extract
    ie_result = self._real_extract(url)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\youtube.py", line 4049, in _real_extract
    webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\youtube.py", line 4017, in _download_player_responses
    player_responses, player_url = self._extract_player_responses(
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\youtube.py", line 3734, in _extract_player_responses
    raise last_error
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\youtube.py", line 3699, in _extract_player_responses
    pr = initial_pr if client == 'web' and initial_pr else self._extract_player_response(
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\youtube.py", line 3619, in _extract_player_response
    return self._extract_response(
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\youtube.py", line 951, in _extract_response

    for retry in self.RetryManager():
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\utils\_utils.py", line 5628, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 3744, in _error_or_warning

    RetryManager.report_retry(
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\utils\_utils.py", line 5636, in report_retry
    raise e
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\youtube.py", line 953, in _extract_response

    response = self._call_api(
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\youtube.py", line 610, in _call_api
    return self._download_json(
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 1058, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 1022, in download_handle
    res = self._download_webpage_handle(
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 892, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 849, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\python_conda_package\Anaconda3\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\python_conda_package\Anaconda3\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\python_conda_package\Anaconda3\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\python_conda_package\Anaconda3\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\python_conda_package\Anaconda3\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\python_conda_package\Anaconda3\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\python_conda_package\Anaconda3\lib\http\client.py", line 1447, in connect
    super().connect()
  File "C:\python_conda_package\Anaconda3\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\python_conda_package\Anaconda3\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\python_conda_package\Anaconda3\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 831, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3786, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\python_conda_package\Anaconda3\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\python_conda_package\Anaconda3\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\python_conda_package\Anaconda3\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\utils\_utils.py", line 1514, in https_open
    return self.do_open(
  File "C:\python_conda_package\Anaconda3\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
```

**Comment by coletdjnz** [comment]
> [debug] Proxy map: {'http': 'http://127.0.0.1:1080', 'https': 'http://127.0.0.1:1080', 'ftp': 'http://127.0.0.1:1080'}

What is your system proxy settings?

**Comment by Thalia500** [comment]
> > [debug] Proxy map: {'http': 'http://127.0.0.1:1080', 'https': 'http://127.0.0.1:1080', 'ftp': '[http://127.0.0.1:1080'}](http://127.0.0.1:1080'%7D)
> 
> What is your system proxy settings? Can you share output that shows this worked in an older version?
> 
> It looks like you have tried to set a socks proxy but it has been set to http proxy

oh I can't turn on the 'auto' button, after restarting it will be turned off.
