### ISSUE TITLE
JSONDecodeError on Douyin

### ISSUE THREAD

**Issue by ok3721** [yt-dlp/yt-dlp#7431]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

The Douyin extractor was working fine until this morning, I believe there's something changed on Douyin webpage that caused the JSONDecodeError. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'chrome', 'https://www.douyin.com/video/7098500303447739679', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (py2exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli-1.0.9, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\AOSS\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\AOSS\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Loading cookie      0/  1088WARNING: failed to decrypt cookie (AES-GCM) because the MAC check failed. Possibly the key is wrong?
[Cookies] Extracted 979 cookies from chrome (109 could not be decrypted)
[debug] cookie version breakdown: {'v10': 1088, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: eefd10faae5f2f03090d64b2107df736784b0e07acc98cc2daf8ac56b1fd9380
yt-dlp is up to date (stable@2023.06.22)
[Douyin] Extracting URL: https://www.douyin.com/video/7098500303447739679
[Douyin] 7098500303447739679: Downloading video feed
[Douyin] 7098500303447739679: Unable to find video in feed; trying with webpage
[Douyin] 7098500303447739679: Downloading webpage
ERROR: [Douyin] 7098500303447739679: 7098500303447739679: Failed to parse JSON (caused by JSONDecodeError('Extra data in \'3-04-27"}}</script><\': line 1 column 86896 (char 86895)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.pyc", line 708, in extract
  File "yt_dlp\extractor\tiktok.pyc", line 1028, in _real_extract
  File "yt_dlp\extractor\common.pyc", line 1009, in _parse_json
  File "yt_dlp\extractor\common.pyc", line 992, in __print_error

  File "yt_dlp\utils\_utils.pyc", line 624, in decode
  File "json\decoder.pyc", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 86896 (char 86895)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.pyc", line 1006, in _parse_json
  File "json\__init__.pyc", line 370, in loads
  File "yt_dlp\utils\_utils.pyc", line 632, in decode
json.decoder.JSONDecodeError: Extra data in '3-04-27"}}</script><': line 1 column 86896 (char 86895)
```

**Comment by pukkandan** [comment]
To devs: using `_search_json`  instead of `_search_regex` + `_parse_json` should fix this. Or if that is not viable, add `ignore_extra=True` to the `_parse_json`

**Comment by bashonly** [comment]
> using `_search_json` instead of `_search_regex` + `_parse_json` should fix this

can confirm

```diff
diff --git a/yt_dlp/extractor/tiktok.py b/yt_dlp/extractor/tiktok.py
index 9c6d74007..2f491c317 100644
--- a/yt_dlp/extractor/tiktok.py
+++ b/yt_dlp/extractor/tiktok.py
@@ -1015,18 +1015,16 @@ def _real_extract(self, url):
             self.to_screen(f'{e}; trying with webpage')
 
         webpage = self._download_webpage(url, video_id)
-        render_data_json = self._search_regex(
-            r'<script [^>]*\bid=[\'"]RENDER_DATA[\'"][^>]*>(%7B.+%7D)</script>',
-            webpage, 'render data', default=None)
-        if not render_data_json:
+        render_data = self._search_json(
+            r'<script [^>]*\bid=[\'"]RENDER_DATA[\'"][^>]*>', webpage, 'render data', video_id,
+            contains_pattern=r'%7B(?s:.+)%7D', fatal=False, transform_source=compat_urllib_parse_unquote)
+        if not render_data:
             # TODO: Run verification challenge code to generate signature cookies
             cookies = self._get_cookies(self._WEBPAGE_HOST)
             expected = not cookies.get('s_v_web_id') or not cookies.get('ttwid')
             raise ExtractorError(
                 'Fresh cookies (not necessarily logged in) are needed', expected=expected)
 
-        render_data = self._parse_json(
-            render_data_json, video_id, transform_source=compat_urllib_parse_unquote)
         return self._parse_aweme_video_web(get_first(render_data, ('aweme', 'detail')), url, video_id)
 
 

```

**Comment by pukkandan** [comment]
@bashonly You can directly push it if you want, no PR needed
