### ISSUE TITLE
yt-dlp has troubles downloading YouTube videos on Windows

### ISSUE THREAD

**Issue by DevelopCMD** [yt-dlp/yt-dlp#7435]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

On Windows, when I download the video, it fails to rename the downloaded file. Please see the verbose log for more info.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=zd6lzedMXPg']
[debug] Portable config "C:\Users\User\scoop\apps\yt-dlp\current\yt-dlp.conf": []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 37e7ffe204309357cfd1388b0e2c782a30e293ddd0f2761a9a8f6afa185b3566
yt-dlp is up to date (stable@2023.06.22)
[youtube] Extracting URL: https://www.youtube.com/watch?v=zd6lzedMXPg
[youtube] zd6lzedMXPg: Downloading webpage
[youtube] zd6lzedMXPg: Downloading ios player API JSON
[youtube] zd6lzedMXPg: Downloading android player API JSON
[debug] Loading youtube-nsig.b7910ca8 from cache
[debug] [youtube] Decrypted nsig jc-bhFzRqykUOyY => nf4wHy8bccXXAA
[youtube] zd6lzedMXPg: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] zd6lzedMXPg: Downloading 1 format(s): 137+251
[debug] Invoking http downloader on "https://rr3---sn-q4flrnld.googlevideo.com/videoplayback?expire=1687852685&ei=LUKaZN2JELKW2_gPq-GU4AI&ip=2600%3A1700%3A10a0%3Aad40%3A1ccb%3Abffd%3Ae5a7%3A8c03&id=o-AFiCGI_T2ktQIvSoF-sOYPU2aq8p_WG24r2zKhUmTpqS&itag=137&source=youtube&requiressl=yes&mh=6M&mm=31%2C29&mn=sn-q4flrnld%2Csn-q4fl6nd6&ms=au%2Crdu&mv=m&mvi=3&pl=41&initcwndbps=1010000&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=3060273&dur=50.733&lmt=1681443371354184&mt=1687830796&fvip=1&keepalive=yes&fexp=24007246%2C24363392&c=IOS&txp=6219224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgFzsBNfdG7S-GV22ADaEmcftdMz7jSSfTE_E5a-9NYCoCIQC3oEGTMTVSbCsjdVQvqSWeMyICtZGxsCssnJzPAHCcxw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgWZc_WagmUB9MBnbN1bWWE2aHshZqP6eDXLwPqJsR0aUCIFEkLoAquh8k5kU8vdzGsX0B_IjSFX3RuRYvc2UloIVm"
[download] Resuming download at byte 3060273
[download] Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4 has already been downloaded
[download] Unable to rename file: [WinError 5] Access is denied: 'Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4.part' -> 'Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4'. Retrying (1/3)...
[download] Unable to rename file: [WinError 5] Access is denied: 'Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4.part' -> 'Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4'. Retrying (2/3)...
[download] Unable to rename file: [WinError 5] Access is denied: 'Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4.part' -> 'Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4'. Retrying (3/3)...
ERROR: Unable to rename file: [WinError 5] Access is denied: 'Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4.part' -> 'Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4'. Giving up after 3 retries
Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3786, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 416: Requested range not satisfiable

[download] 100% of    2.92MiB
[debug] Invoking http downloader on "https://rr3---sn-q4flrnld.googlevideo.com/videoplayback?expire=1687852685&ei=LUKaZJbyHMma2_gP1YKc4Aw&ip=2600%3A1700%3A10a0%3Aad40%3A1ccb%3Abffd%3Ae5a7%3A8c03&id=o-ABzTZqff_NkjOY3NCnlWm-L8JdZF379l56TBCJA7Csah&itag=251&source=youtube&requiressl=yes&mh=6M&mm=31%2C26&mn=sn-q4flrnld%2Csn-vgqsknlk&ms=au%2Conr&mv=m&mvi=3&pl=41&initcwndbps=1010000&spc=qEK7B4gQ8nurxb8L7fpgMwPdIUCPrH8&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=700283&dur=50.761&lmt=1681443373240175&mt=1687830796&fvip=4&keepalive=yes&fexp=24007246%2C24362688%2C24363393&c=ANDROID&txp=6218224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQ800pxuJGBCHI5g6zQeghkCdXYQv4gWxK_rOkZQmc1ECIQC2q8bwxVsDdkH6Nevn378kLXNmUWwfV2X3Qh4nAEpkdg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOJzG5O3qj_IRpDjFwjXXnuCFcCYBXVAjPOLJXxXw_wnAiEArT_Tu7_H1oHBxFkBkqcGdytBB5rxXb6AtY9Sp-T-Iu4%3D"
[download] Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f251.webm has already been downloaded
[download] 100% of  683.87KiB
[Merger] Merging formats into "Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].mkv"
ERROR: [WinError 2] The system cannot find the file specified: 'Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1555, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1652, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1711, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2821, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3363, in process_info
  File "yt_dlp\YoutubeDL.py", line 3543, in post_process
  File "yt_dlp\YoutubeDL.py", line 3525, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3503, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 837, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 329, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 336, in real_run_ffmpeg
  File "yt_dlp\postprocessor\ffmpeg.py", line 337, in <genexpr>
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Thanks for 1,000 subscribers! (with a little surprise at the end!) [zd6lzedMXPg].f137.mp4'
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195
