### ISSUE TITLE
Cookies doesn't work in API | Works with cmd.

### ISSUE THREAD

**Issue by AG4lyf** [yt-dlp/yt-dlp#7441]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

simple code looks like this
```py
import yt_dlp

id = "IVdygv03Dsc"
params = {
    "format": "bestaudio/best",
    "verbose": True,
    "cookies": "temp_cookies.txt",
}

video_data = yt_dlp.YoutubeDL(params).extract_info(id, download=False)
```

doesn't work. 
I have tried changing "cookies" to "cookiesfile". still doesn't work.
I tried to find a perfect name for the params key. can't find anything.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell

[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip) API 
[debug] params: {'format': 'bestaudio/best', 'verbose': True, 'cookie': 'temp_cookies.txt', 'compat_opts': set()} 
[debug] Python 3.10.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1n  15 Mar 2022) 
[debug] exe versions: ffmpeg 2022-02-10-git-b6bb6b9f22-full_build-www.gyan.dev (setts), ffprobe 2022-02-10-git-b6bb6b9f22-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4 
[debug] Proxy map: {} 
[debug] Loaded 1851 extractors 
[youtube] Extracting URL: IVdygv03Dsc 
[youtube] IVdygv03Dsc: Downloading webpage 
[youtube] IVdygv03Dsc: Downloading ios player API JSON 
[youtube] IVdygv03Dsc: Downloading android player API JSON 
ERROR: [youtube] IVdygv03Dsc: Join this channel to get access to members-only content like this video, and other exclusive perks. 
  File "D:\py\lib\site-packages\yt_dlp\extractor\common.py", line 708, in extract 
    ie_result = self._real_extract(url) 
  File "D:\py\lib\site-packages\yt_dlp\extractor\youtube.py", line 4160, in _real_extract 
    self.raise_no_formats(reason, expected=True) 
  File "D:\py\lib\site-packages\yt_dlp\extractor\common.py", line 1186, in raise_no_formats 
    raise ExtractorError(msg, expected=expected, video_id=video_id) 

Traceback (most recent call last):
  File "D:\py\lib\site-packages\yt_dlp\YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
  File "D:\py\lib\site-packages\yt_dlp\YoutubeDL.py", line 1631, in __extract_info
    ie_result = ie.extract(url)
  File "D:\py\lib\site-packages\yt_dlp\extractor\common.py", line 708, in extract
    ie_result = self._real_extract(url)
  File "D:\py\lib\site-packages\yt_dlp\extractor\youtube.py", line 4160, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "D:\py\lib\site-packages\yt_dlp\extractor\common.py", line 1186, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] IVdygv03Dsc: Join this channel to get access to members-only content like this video, and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\suraj\OneDrive\Documents\py-files\clip_finder\test.py", line 10, in <module>
    video_data = yt_dlp.YoutubeDL(params).extract_info(id, download=False)
  File "D:\py\lib\site-packages\yt_dlp\YoutubeDL.py", line 1544, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "D:\py\lib\site-packages\yt_dlp\YoutubeDL.py", line 1573, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "D:\py\lib\site-packages\yt_dlp\YoutubeDL.py", line 1036, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "D:\py\lib\site-packages\yt_dlp\YoutubeDL.py", line 976, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] IVdygv03Dsc: Join this channel to get access to members-only content like this video, and other exclusive perks.
```

but with cmd 
```
PS C:\Users\suraj\OneDrive\Documents\py-files\clip_finder> yt-dlp --cookies=temp_cookies.txt https://youtube.com/watch?v=IVdygv03Dsc -vU
[debug] Command-line config: ['--cookies=temp_cookies.txt', 'https://youtube.com/watch?v=IVdygv03Dsc', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip) 
[debug] Python 3.10.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1n  15 Mar 2022) 
[debug] exe versions: ffmpeg 2022-02-10-git-b6bb6b9f22-full_build-www.gyan.dev (setts), ffprobe 2022-02-10-git-b6bb6b9f22-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4 
[debug] Proxy map: {} 
[debug] Loaded 1851 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22 
yt-dlp is up to date (stable@2023.06.22)
[youtube] Extracting URL: https://youtube.com/watch?v=IVdygv03Dsc 
[youtube] IVdygv03Dsc: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie 
[youtube] IVdygv03Dsc: Downloading ios player API JSON
[youtube] IVdygv03Dsc: Downloading android player API JSON 
[debug] Loading youtube-nsig.71547d26 from cache 
[debug] [youtube] Decrypted nsig i5uFyhqPiUaCe6qTOB => f8kDOtoBxZGG-g 
[youtube] IVdygv03Dsc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto 
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best 
[info] IVdygv03Dsc: Downloading 1 format(s): 308+251
[debug] Invoking http downloader on "https://rr1---sn-gwpa-5bgr.googlevideo.com/videoplayback?expire=1687916985&ei=WD2bZLq6Ouv34-EP3tuC6A8&ip=2409%3A40d2%3A101c%3Ae39b%3Abc0f%3A9636%3Af579%3A2aa&id=o-AEjw1aA1w48OwwQfArFC5t_N5bZInl4Bf79HBYx3fXHL&itag=308&source=youtube&requiressl=yes&mh=S2&mm=31%2C29&mn=sn-gwpa-5bgr%2Csn-gwpa-qxas&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=36&initcwndbps=300000&siu=1&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=9601130757&dur=7795.233&lmt=1687892023725256&mt=1687894886&fvip=3&keepalive=yes&fexp=24007246%2C24363393&beids=24482228&c=IOS&txp=7319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALYxYeTGHpwmvu6pU7GJXjlCWhCHYwfim8GD9FZGJ1nWAiBcjI8b93GauCBUiV8-vNmFGTeukU6N14dGaUR75zJBtw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPU1b_aKN4No9v7ti-4IQ6N-khFkvw00zwq5CbFtDxBGAiAgOrt2f2Y9G2IEtS7njsFYthR5pso9NF36Z8UoT_lMAw%3D%3D"
[download] Resuming download at byte 51254222
[debug] File locking is not supported. Proceeding without locking 
[download] Destination: Valorant Live ｜ Members Only stream [IVdygv03Dsc].f308.webm
[download]   0.6% of    8.94GiB at   10.87MiB/s ETA 13:57
ERROR: Interrupted by user


it works fine.
```

**Comment by bashonly** [comment]
in API the param is `cookiefile` not `cookies` or `cookiesfile`

**Comment by AG4lyf** [comment]
Holy sh. 
that was quick

is there any md where i can see all the params ?

**Comment by pukkandan** [comment]
From docs:

> Most likely, you'll want to use various options. For a list of options available, have a look at [yt_dlp/YoutubeDL.py](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L184).

But even better, use https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py I'll add this to docs too.
