### ISSUE TITLE
[youku]Unable to download webpage: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host> (caused by URLError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))

### ISSUE THREAD

**Issue by TurnOffNOD** [yt-dlp/yt-dlp#7446]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China Mainland

### Provide a description that is worded well enough to be understood

url that can't be downloaded: https://v.youku.com/v_show/id_XMTc0MDgzNTQ0.html

This video is not pay-walled. I can play it with my firefox on the same pc the same time.

When I download it with yt-dlp, it shows error:
```cmd
[youku] Extracting URL: https://v.youku.com/v_show/id_XMTc0MDgzNTQ0.html
[youku] XMTc0MDgzNTQ0: Retrieving cna info
ERROR: [youku] XMTc0MDgzNTQ0: Unable to download webpage: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host> (caused by URLError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
```

And then I came here to report issues. yt-dlp with `-vU` is shown below.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://v.youku.com/v_show/id_XMTc0MDgzNTQ0.html']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 37e7ffe204309357cfd1388b0e2c782a30e293ddd0f2761a9a8f6afa185b3566
yt-dlp is up to date (stable@2023.06.22)
[youku] Extracting URL: https://v.youku.com/v_show/id_XMTc0MDgzNTQ0.html
[youku] XMTc0MDgzNTQ0: Retrieving cna info
ERROR: [youku] XMTc0MDgzNTQ0: Unable to download webpage: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host> (caused by URLError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
  File "yt_dlp\extractor\common.py", line 708, in extract
  File "yt_dlp\extractor\youku.py", line 118, in _real_extract
  File "yt_dlp\extractor\common.py", line 896, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 853, in _request_webpage

  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 835, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3786, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils\_utils.py", line 1514, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
```

**Comment by PikuZheng** [comment]
换梯子。也可能走ipv6了没过梯子

**Comment by TurnOffNOD** [comment]
> 换梯子。也可能走ipv6了没过梯子。 10054相当于收到了墙发来的tcp reset

仔细看一下，是youku，涉及不到梯子的问题……

**Comment by PikuZheng** [comment]
我的错。。。但是有没有可能youku过了梯子，youku过vpn不让播放的

**Comment by TurnOffNOD** [comment]
> 我的错。。。但是有没有可能youku过了梯子，youku过vpn不让播放的

不是。
