### ISSUE TITLE
[Youtube] Converting subtitle .ttml to .ass causes an error because an .srt is downloaded

### ISSUE THREAD

**Issue by Spicadox** [yt-dlp/yt-dlp#746]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\sam\Videos\FFMPEG VIDEO\Test\test\ytarchive\NoArchive>yt-dlp --verbose --skip-download --sub-langs "all" --write-subs --sub-format "ttml" --convert-subs ass https://www.youtube.com/watch?v=9nQurjU-Ky0
[debug] Command-line config: ['--verbose', '--skip-download', '--sub-langs', 'all', '--write-subs', '--sub-format', 'ttml', '--convert-subs', 'ass', 'https://www.youtube.com/watch?v=9nQurjU-Ky0']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.9.1 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-103109-gadb1446a71-gb9176dbfb7, ffprobe n4.4-19-g8d172d9409
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=9nQurjU-Ky0
[youtube] 9nQurjU-Ky0: Downloading webpage
[youtube] 9nQurjU-Ky0: Downloading android player API JSON
[debug] Sort order given by extractor: quality, height, fps, source
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, height, fps, source, res, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Downloading subtitles: id, ja, en, es
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 9nQurjU-Ky0: Downloading 1 format(s): 248+251
[info] Writing video subtitles to: 【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].id.ttml
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=9nQurjU-Ky0&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xorp=true&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1629523192&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxorp%2Cxoaf&signature=4C450CCBD66AC5F70855726AE8C5D808579C8CEF.D1E19D345D5DF754135617FFFAF20662B036A939&key=yt8&lang=id&fmt=ttml"
[download] Destination: 【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].id.ttml
[download] 100% of 16.74KiB in 00:00
[info] Writing video subtitles to: 【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].ja.ttml
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=9nQurjU-Ky0&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xorp=true&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1629523192&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxorp%2Cxoaf&signature=4C450CCBD66AC5F70855726AE8C5D808579C8CEF.D1E19D345D5DF754135617FFFAF20662B036A939&key=yt8&lang=ja&fmt=ttml"
[download] Destination: 【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].ja.ttml
[download] 100% of 16.79KiB in 00:00
[info] Writing video subtitles to: 【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].en.ttml
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=9nQurjU-Ky0&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xorp=true&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1629523192&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxorp%2Cxoaf&signature=4C450CCBD66AC5F70855726AE8C5D808579C8CEF.D1E19D345D5DF754135617FFFAF20662B036A939&key=yt8&lang=en&fmt=ttml"
[download] Destination: 【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].en.ttml
[download] 100% of 16.13KiB in 00:00
[info] Writing video subtitles to: 【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].es.ttml
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=9nQurjU-Ky0&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xorp=true&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1629523192&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxorp%2Cxoaf&signature=4C450CCBD66AC5F70855726AE8C5D808579C8CEF.D1E19D345D5DF754135617FFFAF20662B036A939&key=yt8&lang=es&fmt=ttml"
[download] Destination: 【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].es.ttml
[download] 100% of 16.70KiB in 00:00
[SubtitlesConvertor] Converting subtitles
WARNING: You have requested to convert dfxp (TTML) subtitles into another format, which results in style information loss
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].id.srt" -f ass "file:【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].id.ass"
ERROR: '【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].id.srt'
Traceback (most recent call last):
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1237, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1281, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2299, in process_video_result
    self.process_info(new_info)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2632, in process_info
    info_dict, files_to_move = self.pre_process(info_dict, 'before_dl', files_to_move)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2977, in pre_process
    info = self.run_pp(pp, info)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2936, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "C:\Users\sam\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 805, in run
    info['__files_to_move'][old_file], new_ext)
KeyError: '【アニメ】全部猛暑のせいだ [9nQurjU-Ky0].id.srt'

```

## Description

URL I used: https://www.youtube.com/watch?v=9nQurjU-Ky0
Downloading and converting the ttml subtitle to ass causes a key error due to an srt file being installed. The actual converting process is fine, but the error occurs because for some reason an srt file is being downloaded even though it shouldn't have been since the requested subtitle format is ttml and not srt.

**Comment by pukkandan** [comment]
Fixed by https://github.com/yt-dlp/yt-dlp/commit/37242e56f22af4dfc45cf34784f25782f52610fc
