### ISSUE TITLE
[Broken] TikTok not working

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#751]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp -J https://www.tiktok.com/@thepetcollective/video/6990029249818266886?is_copy_url=1&is_from_webapp=v1 -v
[1] 19151
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
ERROR: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 750, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 740, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2884, in download
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2908, in sanitize_info
AttributeError: 'NoneType' object has no attribute 'setdefault'
```

## Description

I'm unable to download or get JSON data for TikTok videos. The verbose log has been pasted above.

What could be the issue?

**Comment by ahm750** [comment]
Issue resolved.
