### ISSUE TITLE
Youtube format mp4 is in 404 error (not webm)

### ISSUE THREAD

**Issue by guy-teube** [yt-dlp/yt-dlp#7510]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Download a video on Youtube in the mp4 format gives a 404 Not found error.
The same video in webm format can be downloaded.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
The available formats:

guy@ubuntu:~$ yt-dlp -F https://www.youtube.com/watch?v=bW0gWUstFNE
[youtube] Extracting URL: https://www.youtube.com/watch?v=bW0gWUstFNE
[youtube] bW0gWUstFNE: Downloading webpage
[youtube] bW0gWUstFNE: Downloading ios player API JSON
[youtube] bW0gWUstFNE: Downloading android player API JSON
[youtube] bW0gWUstFNE: Downloading m3u8 information
[info] Available formats for bW0gWUstFNE:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb1 mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb0 mhtml 160x90       0    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             [fr] Default
234 mp4   audio only        │                  m3u8  │ audio only          unknown             [fr] Default
599 m4a   audio only      2 │    2.60MiB   31k https │ audio only          mp4a.40.5   31k 22k [fr] ultralow, m4a_dash
600 webm  audio only      2 │    2.92MiB   35k https │ audio only          opus        35k 48k [fr] ultralow, webm_dash
139 m4a   audio only      2 │    4.13MiB   49k https │ audio only          mp4a.40.5   49k 22k [fr] low, m4a_dash
249 webm  audio only      2 │    4.27MiB   50k https │ audio only          opus        50k 48k [fr] low, webm_dash
250 webm  audio only      2 │    5.37MiB   64k https │ audio only          opus        64k 48k [fr] low, webm_dash
140 m4a   audio only      2 │   10.95MiB  129k https │ audio only          mp4a.40.2  129k 44k [fr] medium, m4a_dash
251 webm  audio only      2 │    9.84MiB  116k https │ audio only          opus       116k 48k [fr] medium, webm_dash
17  3gp   176x144      6  1 │    6.53MiB   77k https │ mp4v.20.3           mp4a.40.2       22k [fr] 144p
597 mp4   256x144     13    │    2.79MiB   33k https │ avc1.4d400b     33k video only          144p, mp4_dash
602 mp4   256x144     13    │ ~  8.33MiB   96k m3u8  │ vp09.00.10.08   96k video only
598 webm  256x144     13    │    2.57MiB   30k https │ vp9             30k video only          144p, webm_dash
269 mp4   256x144     25    │ ~ 14.10MiB  163k m3u8  │ avc1.4D400C    163k video only
160 mp4   256x144     25    │    5.54MiB   65k https │ avc1.4D400C     65k video only          144p, mp4_dash
603 mp4   256x144     25    │ ~ 13.43MiB  155k m3u8  │ vp09.00.11.08  155k video only
278 webm  256x144     25    │    6.54MiB   77k https │ vp09.00.11.08   77k video only          144p, webm_dash
229 mp4   426x240     25    │ ~ 24.41MiB  282k m3u8  │ avc1.4D4015    282k video only
133 mp4   426x240     25    │   12.04MiB  142k https │ avc1.4D4015    142k video only          240p, mp4_dash
604 mp4   426x240     25    │ ~ 23.38MiB  270k m3u8  │ vp09.00.20.08  270k video only
242 webm  426x240     25    │   11.82MiB  140k https │ vp09.00.20.08  140k video only          240p, webm_dash
230 mp4   640x360     25    │ ~ 48.21MiB  557k m3u8  │ avc1.4D401E    557k video only
134 mp4   640x360     25    │   22.35MiB  264k https │ avc1.4D401E    264k video only          360p, mp4_dash
18  mp4   640x360     25  2 │   30.60MiB  362k https │ avc1.42001E         mp4a.40.2       44k [fr] 360p
605 mp4   640x360     25    │ ~ 43.44MiB  502k m3u8  │ vp09.00.21.08  502k video only
243 webm  640x360     25    │   20.94MiB  248k https │ vp09.00.21.08  248k video only          360p, webm_dash
231 mp4   854x480     25    │ ~ 91.46MiB 1057k m3u8  │ avc1.4D401E   1057k video only
135 mp4   854x480     25    │   46.77MiB  553k https │ avc1.4D401E    553k video only          480p, mp4_dash
606 mp4   854x480     25    │ ~ 69.16MiB  799k m3u8  │ vp09.00.30.08  799k video only
244 webm  854x480     25    │   34.20MiB  405k https │ vp09.00.30.08  405k video only          480p, webm_dash
22  mp4   1280x720    25  2 │ ≈103.19MiB 1192k https │ avc1.64001F         mp4a.40.2       44k [fr] 720p
232 mp4   1280x720    25    │ ~190.09MiB 2196k m3u8  │ avc1.64001F   2196k video only
136 mp4   1280x720    25    │   89.95MiB 1064k https │ avc1.64001F   1064k video only          720p, mp4_dash
609 mp4   1280x720    25    │ ~123.34MiB 1425k m3u8  │ vp09.00.31.08 1425k video only
247 webm  1280x720    25    │   63.37MiB  750k https │ vp09.00.31.08  750k video only          720p, webm_dash
270 mp4   1920x1080   25    │ ~398.71MiB 4607k m3u8  │ avc1.640028   4607k video only
137 mp4   1920x1080   25    │  163.45MiB 1933k https │ avc1.640028   1933k video only          1080p, mp4_dash
614 mp4   1920x1080   25    │ ~210.09MiB 2427k m3u8  │ vp09.00.40.08 2427k video only
248 webm  1920x1080   25    │  101.27MiB 1198k https │ vp09.00.40.08 1198k video only          1080p, webm_dash
616 mp4   1920x1080   25    │ ~488.87MiB 5649k m3u8  │ vp09.00.40.08 5649k video only          Premium
```

The 404 Not found download, with logs:
```
guy@ubuntu:~$ yt-dlp -vU -f 616+140 https://www.youtube.com/watch?v=bW0gWUstFNE
[debug] Command-line config: ['-vU', '-f', '616+140', 'https://www.youtube.com/watch?v=bW0gWUstFNE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-153-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1j  16 Feb 2021, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, pyxattr-0.6.1, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 924464eb831bdb99d854b9d47ff9e1c0870eab276113adaf8a74a8561ad332b9
yt-dlp is up to date (stable@2023.06.22)
[youtube] Extracting URL: https://www.youtube.com/watch?v=bW0gWUstFNE
[youtube] bW0gWUstFNE: Downloading webpage
[youtube] bW0gWUstFNE: Downloading ios player API JSON
[youtube] bW0gWUstFNE: Downloading android player API JSON
[youtube] bW0gWUstFNE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] bW0gWUstFNE: Downloading 1 format(s): 616+140
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1688520943/ei/j3SkZKOEJN2wxN8P1vOc-A0/ip/2a01:e0a:5e1:6000:4050:b5ba:d66b:6fa8/id/6d6d20594b2d14d1/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D220448071%3Bdur%3D709.240%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1688495677087448/hls_chunk_host/rr2---sn-25glenl6.googlevideo.com/mh/Ol/mm/31,26/mn/sn-25glenl6,sn-4g5e6nz7/ms/au,onr/mv/m/mvi/2/pl/52/initcwndbps/1187500/bui/AYlvQAsm9d2Bfe0XgfsTkD2UdaHRGsTuoM35TPqWoXIkTDXGUmR4dsc7ziuVi7T_kmaub6ymWNzeb6xz-PErZYa1_gP4pd5t/vprv/1/playlist_type/DVR/dover/13/txp/3308224/mt/1688499176/fvip/5/short_key/1/keepalive/yes/fexp/24007246,24362688,24363391/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,bui,vprv,playlist_type/sig/AOq0QJ8wRQIhAPN-jeSQJjif4gGQjn3mQWHeTBoDIGfw0E4G8RL79AR5AiBlh-tF0BzI0s8FmNmqRx9rIxW6Vr580viO-vNU7XpHfA%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRgIhALzBNqPzKKSsVcPwEWYnqOR8bxhvtzBZeJv6QYxdPQX9AiEA9x0lZ2PWmyi-P0uH_Z2yFbN48zCXoi2cI7uunOTVNjM%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3269, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3008, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/downloader/hls.py", line 66, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/home/guy/Programmes/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3786, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

The successfull download in webm format:
```
guy@ubuntu:~$ yt-dlp -vU -f 248+251 https://www.youtube.com/watch?v=bW0gWUstFNE
[debug] Command-line config: ['-vU', '-f', '248+251', 'https://www.youtube.com/watch?v=bW0gWUstFNE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-153-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1j  16 Feb 2021, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, pyxattr-0.6.1, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 924464eb831bdb99d854b9d47ff9e1c0870eab276113adaf8a74a8561ad332b9
yt-dlp is up to date (stable@2023.06.22)
[youtube] Extracting URL: https://www.youtube.com/watch?v=bW0gWUstFNE
[youtube] bW0gWUstFNE: Downloading webpage
[youtube] bW0gWUstFNE: Downloading ios player API JSON
[youtube] bW0gWUstFNE: Downloading android player API JSON
[youtube] bW0gWUstFNE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] bW0gWUstFNE: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr2---sn-25glenl6.googlevideo.com/videoplayback?expire=1688521175&ei=d3WkZKfOEcKcp-oPgqiI4AE&ip=2a01%3Ae0a%3A5e1%3A6000%3A4050%3Ab5ba%3Ad66b%3A6fa8&id=o-AEpf_in5F7ny6F2zLXJ-cXPRic743DWnI4NUCwWeEYFm&itag=248&source=youtube&requiressl=yes&mh=Ol&mm=31%2C29&mn=sn-25glenl6%2Csn-25ge7nzd&ms=au%2Crdu&mv=m&mvi=2&pl=52&initcwndbps=1187500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=106187087&dur=709.240&lmt=1688493785076350&mt=1688499176&fvip=3&keepalive=yes&fexp=24007246%2C24363392%2C51000011&beids=24350018&c=IOS&txp=3309224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLNQA-97okSicom8WRnqKzYB4jYuuHpe093r-TdXo4d4CIBXW2HFwN4TpYQ5bR3p2k8hGZ64oPNLEcbQBxDtItdBp&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKueXwGMu5-j9c6XmyOhojRDwQR53hoTFyJEvQ7Ay-_3AiEAzafyAC4zYjCMbfzkm4EDo9l_bY-pK2QiaOX9pf2sVNw%3D"
[download] Destination: APRÈS LE DRAME NAHEL ： MACRON VEUT PROFITER DES ÉMEUTES POUR CENSURER INTERNET [bW0gWUstFNE].f248.webm
[download] 100% of  101.27MiB in 00:00:12 at 8.05MiB/s
[debug] Invoking http downloader on "https://rr2---sn-25glenl6.googlevideo.com/videoplayback?expire=1688521175&ei=d3WkZM35GZqfvdIP9puYsAQ&ip=2a01%3Ae0a%3A5e1%3A6000%3A4050%3Ab5ba%3Ad66b%3A6fa8&id=o-ALDxjsd0XhFz_2eLi1S0gRM2r5OS4Nq5EQaCbN82CEOO&itag=251&source=youtube&requiressl=yes&mh=Ol&mm=31%2C29&mn=sn-25glenl6%2Csn-25ge7nzd&ms=au%2Crdu&mv=m&mvi=2&pl=52&initcwndbps=1187500&spc=Ul2Sq7L6tBItXNjG2H7pE01fVz106UU&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=10314045&dur=709.261&lmt=1688492412663246&mt=1688499176&fvip=3&keepalive=yes&fexp=24007246&beids=24350017&c=ANDROID&txp=3308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANLQG1Z6_8u9ciCicyOyWRIluCp2MTpMxXihbSM2hT1pAiAvwY8DL0RGQd63GDVa0KQffusdlPWROJDirfyipRTiog%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAINvjIWe0FG_Ltew-KI33irdUA8JqgxjXbhVjSsKcqcAAiEAmXbBzE-R57Y7w9Lpu6N1JbLVPdTRcdU4EO1fbxbMi8Q%3D"
[download] Destination: APRÈS LE DRAME NAHEL ： MACRON VEUT PROFITER DES ÉMEUTES POUR CENSURER INTERNET [bW0gWUstFNE].f251.webm
[download] 100% of    9.84MiB in 00:00:00 at 20.89MiB/s
[Merger] Merging formats into "APRÈS LE DRAME NAHEL ： MACRON VEUT PROFITER DES ÉMEUTES POUR CENSURER INTERNET [bW0gWUstFNE].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:APRÈS LE DRAME NAHEL ： MACRON VEUT PROFITER DES ÉMEUTES POUR CENSURER INTERNET [bW0gWUstFNE].f248.webm' -i 'file:APRÈS LE DRAME NAHEL ： MACRON VEUT PROFITER DES ÉMEUTES POUR CENSURER INTERNET [bW0gWUstFNE].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:APRÈS LE DRAME NAHEL ： MACRON VEUT PROFITER DES ÉMEUTES POUR CENSURER INTERNET [bW0gWUstFNE].temp.webm'
Deleting original file APRÈS LE DRAME NAHEL ： MACRON VEUT PROFITER DES ÉMEUTES POUR CENSURER INTERNET [bW0gWUstFNE].f248.webm (pass -k to keep)
Deleting original file APRÈS LE DRAME NAHEL ： MACRON VEUT PROFITER DES ÉMEUTES POUR CENSURER INTERNET [bW0gWUstFNE].f251.webm (pass -k to keep)
```
```

**Comment by bashonly** [comment]
I can't reproduce this
```shell
$ yt-dlp --ignore-config -f 616 bW0gWUstFNE
[youtube+NSigDeno] Extracting URL: bW0gWUstFNE
[youtube+NSigDeno] bW0gWUstFNE: Downloading webpage
[youtube+NSigDeno] bW0gWUstFNE: Downloading ios player API JSON
[youtube+NSigDeno] bW0gWUstFNE: Downloading android player API JSON
[youtube+NSigDeno] bW0gWUstFNE: Downloading m3u8 information
[info] bW0gWUstFNE: Downloading 1 format(s): 616
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 138
[download] Destination: APRÈS LE DRAME NAHEL ： MACRON VEUT PROFITER DES ÉMEUTES POUR CENSURER INTERNET [bW0gWUstFNE].mp4
[download]   3.1% of ~  79.93MiB at  779.62KiB/s ETA 01:41 (frag 3/138)
```

It looks like this video was just uploaded today; it's likely that format 616 hadn't finished being processed yet at the time you tried to download it.

You can add `--check-formats` to your command if you want yt-dlp to test the requested formats before download, and if one of the formats isn't downloadable then it will re-select the next format in the sort order

**Comment by guy-teube** [comment]
You're right, the mp4 is available now. Next time I'll be more patient.
