### ISSUE TITLE
Please support welt.de (formerly N24 Doku) Mediathek

### ISSUE THREAD

**Issue by z1atk0** [yt-dlp/yt-dlp#7513]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

At least DACH (.de, .at, .ch), but probably worldwide, I guess?

### Example URLs

Working, but without proper format info:

https://www.welt.de/mediathek/serie/sendung218509518/Strip-the-Cosmos-Geheimnisvoller-Jupiter.html
https://www.welt.de/mediathek/dokumentation/technik-und-wissen/sendung155731159/Zielscheibe-Erde-Angriff-aus-dem-All-1.html
https://www.welt.de/mediathek/dokumentation/space/strip-the-cosmos/sendung190852337/Strip-the-Cosmos-Raetselhafte-Schwarze-Loecher.html

Not working at all:

https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung241530977/Spacetime-Der-geheime-Orbit-Wettruesten-im-All.html
https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung241589211/Spacetime-Es-werde-Licht-Religion-und-Astronomie.html
https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung242094261/Spacetime-Teleskope-die-Entdeckungsmaschinen.html

### Provide a description that is worded well enough to be understood

Downloading from WELT-Mediathek (https://www.welt.de/mediathek/) partially works with the generic extractor (but without proper format info), but some videos can not be downloaded at all.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Working, but without format info:

[zlatko@disclosure:~/mnt/nas/_/Downloads]$ yt-dlp -vU --proxy "" -F https://www.welt.de/mediathek/dokumentation/space/strip-the-cosmos/sendung190852337/Strip-the-Cosmos-Raetselhafte-Schwarze-Loecher.html
[debug] Command-line config: ['-vU', '--proxy', '', '-F', 'https://www.welt.de/mediathek/dokumentation/space/strip-the-cosmos/sendung190852337/Strip-the-Cosmos-Raetselhafte-Schwarze-Loecher.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.17 (CPython x86_64 64bit) - Linux-5.15.118-x86_64-Intel-R-_Core-TM-_i7-2600K_CPU_@_3.40GHz-with-glibc2.33 (OpenSSL 1.1.1u  30 May 2023, glibc 2.33)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
[generic] Extracting URL: https://www.welt.de/mediathek/dokumentation/space/strip-the-cosmos/sendung190852337/Strip-the-Cosmos-Raetselhafte-Schwarze-Loecher.html
[generic] Strip-the-Cosmos-Raetselhafte-Schwarze-Loecher: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Strip-the-Cosmos-Raetselhafte-Schwarze-Loecher: Extracting information
[debug] Looking for embeds
[debug] Identified a html5 embed
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for Strip-the-Cosmos-Raetselhafte-Schwarze-Loecher-1:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 unknown    │ https │ unknown unknown
1  mp4 unknown    │ https │ unknown unknown
2  mp4 unknown    │ https │ unknown unknown
3  mp4 unknown    │ https │ unknown unknown


Not working at all:

[zlatko@disclosure:~/mnt/nas/_/Downloads]$ yt-dlp -vU --proxy "" -F https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung241530977/Spacetime-Der-geheime-Orbit-Wettruesten-im-All.html
[debug] Command-line config: ['-vU', '--proxy', '', '-F', 'https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung241530977/Spacetime-Der-geheime-Orbit-Wettruesten-im-All.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.17 (CPython x86_64 64bit) - Linux-5.15.118-x86_64-Intel-R-_Core-TM-_i7-2600K_CPU_@_3.40GHz-with-glibc2.33 (OpenSSL 1.1.1u  30 May 2023, glibc 2.33)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
[generic] Extracting URL: https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung241530977/Spacetime-Der-geheime-Orbit-Wettruesten-im-All.html
[generic] Spacetime-Der-geheime-Orbit-Wettruesten-im-All: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Spacetime-Der-geheime-Orbit-Wettruesten-im-All: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung241530977/Spacetime-Der-geheime-Orbit-Wettruesten-im-All.html
Traceback (most recent call last):
  File "/usr/local/lib64/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1631, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib64/python3.9/site-packages/yt_dlp/extractor/common.py", line 708, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib64/python3.9/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung241530977/Spacetime-Der-geheime-Orbit-Wettruesten-im-All.html
```

**Comment by gamer191** [comment]
> Not working at all:
> 
> https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung241530977/Spacetime-Der-geheime-Orbit-Wettruesten-im-All.html https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung241589211/Spacetime-Es-werde-Licht-Religion-und-Astronomie.html https://www.welt.de/mediathek/dokumentation/space/spacetime/sendung242094261/Spacetime-Teleskope-die-Entdeckungsmaschinen.html

It doesn't look like any of those videos are playable in a browser either

**Comment by z1atk0** [comment]
Sorry, seems you're right, my bad! There's a note saying "Diese Sendung ist zur Zeit aus lizenzrechtlichen Gründen nicht verfügbar.", which roughly translates to "This program is currently unavailable due to licensing reasons." I also tried from a server hosted in Germany (I live in Austria), but the result is the same both with `yt-dlp` and in a browser, so it's probably not geo-blocked.

Still, it would be nice to have at least the available ones working with proper format info. :slightly_smiling_face:

**Comment by dirkf** [comment]
At least the first test page has HTML5 video and metadata in a ld+json block. As the generic extractor sees the HTML5 video it probably ignores the ld+json.
