### ISSUE TITLE
Instagram `threads.net` / `threads.com` site request

### ISSUE THREAD

**Issue by ehyoitsdavid** [yt-dlp/yt-dlp#7523]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

- Single video: https://www.threads.net/t/CuXnwmrMIZL
- Whole account: https://www.threads.net/@charlieonnafriday

### Provide a description that is worded well enough to be understood

Note that Instagram "threads.net" uses a CDN to store their videos and downloading videos from the CDN is not easy, just like Instagram reels. One needs to fake user agent and most importantly cookie support to prove that it is a real browser and not a script to get videos.

First I suggest implementing support for single videos first, then for whole accounts (which is probably risky because of rate limits and possibly bans)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.threads.net/t/CuXnwmrMIZL', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.4.1-arm64-arm-64bit (OpenSSL 3.1.1 30 May 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://www.threads.net/t/CuXnwmrMIZL
[generic] CuXnwmrMIZL: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] CuXnwmrMIZL: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.threads.net/t/CuXnwmrMIZL
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.threads.net/t/CuXnwmrMIZL
```

**Comment by october262** [comment]
link to video 1 - https://scontent.cdninstagram.com/v/t50.2886-16/354809962_1213825392613482_2368464029860537544_n.mp4?_nc_ht=scontent.cdninstagram.com&_nc_cat=106&_nc_ohc=omg_ffWRix0AX9EYSXr&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfDBz9VgLy_gbWpgoSL7IjvObkC4IHOJLprH6MFKoJM3Hw&oe=64A95D24&_nc_sid=10d13b

**Comment by jinthoa** [comment]
Here's another example: 

https://www.threads.net/@pubity/post/Cxd59tZLMrd

URL to video: `https://scontent.cdninstagram.com/v/t50.2886-16/380787197_335451142264743_8090553461744062787_n.mp4?_nc_ht=scontent.cdninstagram.com&_nc_cat=103&_nc_ohc=V_mAxTiQzyoAX81uwqC&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfDE--bQHO8yF-ZnCdh3_EuKl1MW6uKXbsyz_SnlfDeGTw&oe=650F64A2&_nc_sid=10d13b`

Would be nice to see this supported.

**Comment by SirElderling** [comment]
One thing I noticed (at least from my end) is that downloading a threads video through `yt-dlp` is way slower than if we fetch it via curl.

```
time yt-dlp "https://scontent.cdninstagram.com/v/t50.2886-16/411700231_1013302036637199_8020624842325890217_n.mp4?_nc_ht=scontent.cdninstagram.com&_nc_cat=103&_nc_ohc=6pTQ9_0AGqUAX-NvjDf&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfBGkJziC0PsIcyv8hFAXVWMInc2zXKahH24OAVMmpbUnA&oe=658077B4&_nc_sid=10d13b"
[generic] Extracting URL: https://scontent.cdninstagram.com/v/t50.2886-16/411700231_1013302036637199_8020624842325890217_n....077B4&_nc_sid=10d13b
[generic] 411700231_1013302036637199_8020624842325890217_n.mp4?_nc_ht=scontent.cdninstagram: Downloading webpage
[info] 411700231_1013302036637199_8020624842325890217_n.mp4?_nc_ht=scontent.cdninstagram: Downloading 1 format(s): mp4
[download] Resuming download at byte 130048
[download] Destination: 411700231_1013302036637199_8020624842325890217_n [411700231_1013302036637199_8020624842325890217_n.mp4？_nc_ht=scontent.cdninstagram].mp4
[download] 100% of    2.78MiB in 00:01:12 at 39.08KiB/s

real	1m14.511s
user	0m1.707s
sys	0m0.215s
```

```
time curl 'https://scontent.cdninstagram.com/v/t50.2886-16/411700231_1013302036637199_8020624842325890217_n.mp4?_nc_ht=scontent.cdninstagram.com&_nc_cat=103&_nc_ohc=6pTQ9_0AGqUAX-NvjDf&edm=APs17CUBAAAA&ccb=7-5&oh=00_AfBGkJziC0PsIcyv8hFAXVWMInc2zXKahH24OAVMmpbUnA&oe=658077B4&_nc_sid=10d13b' \
  -H 'authority: scontent.cdninstagram.com' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'dnt: 1' \
  -H 'range: bytes=0-' \
  -H 'referer: https://www.threads.net/' \
  -H 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: video' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
  --compressed --output ~/Temp/aaa.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2841k  100 2841k    0     0  3316k      0 --:--:-- --:--:-- --:--:-- 3319k

real	0m0.881s
user	0m0.114s
sys	0m0.053s
```

**Comment by kartagis** [comment]
Hi, I came across this and is there a time frame threads.net will go into yt-dlp? I just updated to 2024.02.21.232721 nightly and still no trace of this :(

**Comment by seproDev** [comment]
@kartagis Are you offering to work on this? If you need any help, we can try to assist you.

**Comment by kartagis** [comment]
@seproDev I'm not actually because I don't know python but I'd be willing to help in any way that I can.

**Comment by renandecarlo** [comment]
Any news?

**Comment by aiur-adept** [comment]
The only thing holding this back seems to be some formatting issues:

```
Run ruff check --output-format github .
Error: yt_dlp/extractor/threads.py:29:49: COM812 Trailing comma missing
Error: yt_dlp/extractor/threads.py:30:10: COM8[12](https://github.com/yt-dlp/yt-dlp/actions/runs/10089566813/job/27897257357?pr=9852#step:6:13) Trailing comma missing
Error: yt_dlp/extractor/threads.py:47:49: COM812 Trailing comma missing
Error: yt_dlp/extractor/threads.py:48:10: COM812 Trailing comma missing
Error: yt_dlp/extractor/threads.py:58:[13](https://github.com/yt-dlp/yt-dlp/actions/runs/10089566813/job/27897257357?pr=9852#step:6:14): UP031 Use format specifiers instead of percent format
Error: yt_dlp/extractor/threads.py:88:46: UP031 Use format specifiers instead of percent format
Error: yt_dlp/extractor/threads.py:107:57: UP031 Use format specifiers instead of percent format
Error: yt_dlp/extractor/threads.py:124:37: COM812 Trailing comma missing
Error: yt_dlp/extractor/threads.py:[14](https://github.com/yt-dlp/yt-dlp/actions/runs/10089566813/job/27897257357?pr=9852#step:6:15)7:49: COM812 Trailing comma missing
Error: yt_dlp/extractor/threads.py:149:30: COM812 Trailing comma missing
Error: Process completed with exit code 1.
```

@ehyoitsdavid , could you look into these?

**Comment by yonatancohen** [comment]
Hi, any news?

**Comment by bashonly** [comment]
The issue will be closed due to merged pull request when there is any news
