### ISSUE TITLE
Support for piped.simpleprivacy.fr

### ISSUE THREAD

**Issue by RetroAbstract** [yt-dlp/yt-dlp#7537]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Any (to my knowledge)

### Example URLs

Single video: https://piped.simpleprivacy.fr/watch?v=QwIlhuR_N2g
Playlist: https://piped.simpleprivacy.fr/playlist?list=PL8mG-RkN2uTx9Er8AqFDnD6mFvje5fybs

### Provide a description that is worded well enough to be understood

This is a request to add support for the [SimplePrivacy Piped Instance](https://piped.simpleprivacy.fr/).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://piped.simpleprivacy.fr/watch?v=QwIlhuR_N2g']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 - Windows-10
[debug] exe versions: ffmpeg N-109562-g0431f9805e-20230110 (setts), ffprobe N-109562-g0431f9805e-20230110
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://piped.simpleprivacy.fr/watch?v=QwIlhuR_N2g
[generic] watch?v=QwIlhuR_N2g: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] watch?v=QwIlhuR_N2g: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://piped.simpleprivacy.fr/watch?v=QwIlhuR_N2g
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1688, in __extract_info
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://piped.simpleprivacy.fr/watch?v=QwIlhuR_N2g
```

**Comment by leafstrat** [comment]
At first glance I thought this was an Invidious instance but it appears not to be the case. It is an alternative frontend.

https://docs.piped.video/docs/why/

> A lot of inspiration came from NewPipe and Invidious.
> 
> I created Piped to fix issues in NewPipe and Invidious which are architectural issues and cannot be fixed easily.
> 
> Invidious
> 
>     Uses way too much resources.
>     Total bandwidth limited by the peak capacity of the load balancer.
>     Coded in Crystal, a language that is relatively hard for beginners.
>     Caching is done at a backend level.
>     Invidious was a learning project.
>     Invidious crashes all the time.
>     Various hacks are required to keep an instance running at a reasonable stability.
> 
> However, there are some drawbacks of Piped:
> 
>     JavaScript is required
>     Browsers without Service-Workers support will feel significantly slower. Eg: Tor Browser

**Comment by gamer191** [comment]
@leafstrat all invidious/piped instances are currently redirected to youtube.com, so that's not an issue

**Comment by imagecreation1** [comment]
Yes, now yt-dlp just fetches the m3u8 playlist from the instance and connects to the youtube servers. Is it possible to proxify it like it is done in piped?

**Comment by M-Stenzel** [comment]
Hi RetroAbstract,

how did you succeed? For myself I would like to have added [piped.xy-space.de](https://piped.xy-space.de).

Martin.

**Comment by NintendoManiac64** [comment]
I'm surprised that yt-dlp doesn't seem to go a generic redirect of anything that is `piped.[domain.site]` or the like. For example, `piped.kavin.rocks` works but `piped.nosebs.ru` does not despite the latter working in the web browser and the former not.

**Comment by dirkf** [comment]
The same considerations apply as in #8952 and linked upstream issue ytdl-org/youtube-dl#31426 for Invidious.

**Comment by NintendoManiac64** [comment]
But piped isn't invidious...? It may work similarly, but it's not the same regardless.

**Comment by bashonly** [comment]
piped isn't actually supported. If you pass a piped URL to yt-dlp which yt-dlp recognizes, yt-dlp only takes the video ID from the URL and extracts/downloads the video from Youtube instead of piped

**Comment by NintendoManiac64** [comment]
I *thought* that's what yt-dlp did, but that would imply that it sort of ignores the piped part of the domain which, as I mentioned, doesn't seem to fully be the case? Otherwise why would `piped.kavin.rocks` work while `piped.nosebs.ru` not work?

**Comment by bashonly** [comment]
The youtube extractor has a list of piped and invidious instances; it needs to be updated

**Comment by dirkf** [comment]
But now that the generic webpage extraction has been in place for some time, the said list could (should?) be replaced by code that detects all piped and Invidious pages.
