### ISSUE TITLE
v.y.qq. request

### ISSUE THREAD

**Issue by Thalia500** [yt-dlp/yt-dlp#7554]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

China

### Example URLs

MV: https://y.qq.com/n/ryqq/mv/002Vsarh3SVU8K
a finished live: https://y.qq.com/tl_live/client/liveroom_pc/index.html?from=pc_redirect&showid=10000705

### Provide a description that is worded well enough to be understood

MV list: https://y.qq.com/n/ryqq/mvList

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -F -vU https://v.y.qq.com/m/play.html?showid=23251703
[debug] Command-line config: ['-F', '-vU', 'https://v.y.qq.com/m/play.html?showid=23251703']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.9 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-110972-gbaa9fccf8d-20230601 (setts), ffprobe N-110972-gbaa9fccf8d-20230601, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-None, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'http://127.0.0.1:1080', 'https': 'http://127.0.0.1:1080', 'ftp': 'http://127.0.0.1:1080'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://v.y.qq.com/m/play.html?showid=23251703
[generic] play: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] play: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://v.y.qq.com/m/play.html?showid=23251703
Traceback (most recent call last):
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://v.y.qq.com/m/play.html?showid=23251703
```

**Comment by pukkandan** [comment]
I'm assuming this is the same as v.qq.com? https://github.com/yt-dlp/yt-dlp/issues/5972

**Comment by c-basalt** [comment]
> I'm assuming this is the same as v.qq.com? #5972

Not really. Though both run by tencent, the sub-domain starting with `v.` is a general video site, while the one starting with `y.` is a music-centered site. They share little logic in common.

@Thalia500
I've drafted a version to support MV download (https://y.qq.com/n/ryqq/mv/002Vsarh3SVU8K) and Fan Live stream (https://v.y.qq.com/m/play.html?showid=23251703)

It would be nice if you can take a look and provide some feedback: https://github.com/c-basalt/yt-dlp/tree/qq-music
You may refer to [this](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) for instruction on how to run yt-dlp directly from source code without building it.

**Comment by Thalia500** [comment]
> > I'm assuming this is the same as v.qq.com? #5972
> 
> Not really. Though both run by tencent, the sub-domain starting with `v.` is a general video site, while the one starting with `y.` is a music-centered site. They share little logic in common.
> 
> @Thalia500 I've drafted a version to support MV download (https://y.qq.com/n/ryqq/mv/002Vsarh3SVU8K) and "Fan Live" streaming (https://v.y.qq.com/m/play.html?showid=23251703)
> 
> It would be nice if you can take a look and provide some feedback: https://github.com/c-basalt/yt-dlp/tree/qq-music You may refer to [this](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) for instruction on how to run yt-dlp directly from source code without building it.

Sorry I don't find it..

**Comment by c-basalt** [comment]
You should be able to follow the link to reach the patched branch, and download source code like any other Github repo. Then you can inspect and test the patch. Where did you get stuck?
