### ISSUE TITLE
TF1 Group - Live streams

### ISSUE THREAD

**Issue by campones** [yt-dlp/yt-dlp#7560]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

FRANCE

### Example URLs

tf1 https://www.tf1.fr/tf1/direct
tfx http://www.tf1.fr/nt1/direct
tsf https://www.tf1.fr/hd1/direct
tmc http://www.tf1.fr/tmc/direct

### Provide a description that is worded well enough to be understood

there is a plugin (quite outdated I guess) to download replay, it would be nice to support live streaming

site now needs credentials to watch direct streaming . 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU "https://www.tf1.fr/tf1/direct"
[debug] Command-line config: ['-vU', 'https://www.tf1.fr/tf1/direct']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-153-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-101901-gb593abd (setts), ffprobe N-101901-gb593abd, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://www.tf1.fr/tf1/direct
[generic] direct: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] direct: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tf1.fr/tf1/direct
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tf1.fr/tf1/direct
```

**Comment by gamer191** [comment]
> site now needs credentials to watch direct streaming .

Does it work with `--cookies-from-browser chrome` (replace chrome with whatever browser you use)

**Comment by campones** [comment]
> > site now needs credentials to watch direct streaming .
> 
> Does it work with `--cookies-from-browser chrome` (replace chrome with whatever browser you use)

thank for your answer. I did and it doesn't work .

**Comment by campones** [comment]
I didn't mention it in the original post but there is a geo restriction obviously.  in France

**Comment by awsms** [comment]
+1, if it's allowed to bump feature requests
