### ISSUE TITLE
"abort-on-unavailable-fragments" doesn't work when video fragment downloads from ffmpeg

### ISSUE THREAD

**Issue by jazz1611** [yt-dlp/yt-dlp#7613]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

hello,

`abort-on-unavailable-fragments` doesn't work when video fragment downloads from ffmpeg. where there is no "abort-on-unavailable-fragments" variable but downloading from ffmpeg takes a very long time to complete with the failed video. i think there should be more variable with counter set 5 or 10 fragment of failed download video will abort progress.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp "https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/playlist.m3u8" -N 8 -f 720 --abort-on-unavailable-fragments -Uv
[debug] Command-line config: ['https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/playlist.m3u8', '-N', '8', '-f', '720', '--abort-on-unavailable-fragments', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.07.15.211025 [613dbce17] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-28-gcedbf27a35-20230716 (setts), ffprobe n6.0-28-gcedbf27a35-20230716
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.07.15.211025, Current version: nightly@2023.07.15.211025
Current Build Hash: 229cf9d1900bfc40c82d6371c6fb17f38714a1cd65105b7cd060b1039f99b0c5
yt-dlp is up to date (nightly@2023.07.15.211025)
[generic] Extracting URL: https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/playlist.m3u8
[generic] playlist: Downloading webpage
[debug] Identified a direct video link
[generic] playlist: Downloading m3u8 information
[generic] playlist: Checking m3u8 live status
WARNING: [generic] Failed to download m3u8 media playlist: The read operation timed out
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] playlist: Downloading 1 format(s): 720
[debug] Invoking ffmpeg downloader on "https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/360/index.m3u8"
[download] Destination: playlist 2023-07-16 22_53 [playlist].mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
" -i "https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/360/index.m3u8" -c copy -f mpegts "file:playlist 2023-07-16 22_53 [playlist].mp4.part"
ffmpeg version n6.0-28-gcedbf27a35-20230716 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.0 (crosstool-NG 1.25.0.196_227d99d)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --disable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --disable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230716
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[tcp @ 000002aba53ef380] Starting connection attempt to 104.22.72.66 port 443
[tcp @ 000002aba53ef380] Successfully connected to 104.22.72.66 port 443
[hls @ 000002aba5422c40] Skip ('#EXT-X-ALLOW-CACHE:YES')
[hls @ 000002aba5422c40] Skip ('#EXT-X-VERSION:3')
[tls @ 000002aba53e5480] Server closed the connection
[hls @ 000002aba5422c40] HLS request for url 'https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/360/seg-1-v1-a1.jpg', offset 0, playlist 0
[hls @ 000002aba5422c40] Opening 'https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/360/seg-1-v1-a1.jpg' for reading
[tcp @ 000002aba5473cc0] Starting connection attempt to 104.22.72.66 port 443
[tcp @ 000002aba5473cc0] Successfully connected to 104.22.72.66 port 443
[https @ 000002aba5478e40] HTTP error 404 Not Found
[hls @ 000002aba5422c40] Failed to open segment 1 of playlist 0
[hls @ 000002aba5422c40] Segment 1 of playlist 0 failed too many times, skipping
[hls @ 000002aba5422c40] HLS request for url 'https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/360/seg-3-v1-a1.html', offset 0, playlist 0
[hls @ 000002aba5422c40] Opening 'https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/360/seg-3-v1-a1.html' for reading
[tcp @ 000002aba542fa40] Starting connection attempt to 104.22.72.66 port 443
[tcp @ 000002aba542fa40] Successfully connected to 104.22.72.66 port 443
[https @ 000002aba5478e40] HTTP error 404 Not Found
[hls @ 000002aba5422c40] Failed to open segment 2 of playlist 0
[hls @ 000002aba5422c40] Segment 2 of playlist 0 failed too many times, skipping
[hls @ 000002aba5422c40] HLS request for url 'https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/360/seg-6-v1-a1.js', offset 0, playlist 0
[hls @ 000002aba5422c40] Opening 'https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/360/seg-6-v1-a1.js' for reading
[tcp @ 000002aba542fa40] Starting connection attempt to 104.22.72.66 port 443
[tcp @ 000002aba542fa40] Successfully connected to 104.22.72.66 port 443
[tls @ 000002aba5473cc0] Unable to read from socket
[tls @ 000002aba5473cc0] Failed to send close message
[hls @ 000002aba5422c40] Error when loading first segment 'https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/360/seg-1-v1-a1.jpg'
[AVIOContext @ 000002aba5438700] Statistics: 27289 bytes read, 0 seeks
https://xis.fifteennet.com/_v10/c998ee9a2c32747edaa357495a6957ee600ad5d74979f56ec2001868fc87d66a3dea5500c4d8e36684713bf72b9f293bf0675b910dfce3d118f4d945807441262de7bd1a498d1557b49accf18096e70f09effae2e68fb576eca38a3e27a484e0a603b0017169b15e9dc7af2089b239a7ef0d233b04569755889981d496fd055cd41c55b033b8f13b8a363a119904c4dc/360/index.m3u8: Immediate exit requested
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user
ERROR: Unable to download video: [WinError 2] The system cannot find the file specified: 'playlist 2023-07-16 22_53 [playlist].mp4.part'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3396, in process_info
  File "yt_dlp\YoutubeDL.py", line 3117, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\external.py", line 70, in real_download
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'playlist 2023-07-16 22_53 [playlist].mp4.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1576, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1732, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1791, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2930, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3408, in process_info
yt_dlp.utils.UnavailableVideoError: Unable to download video: [WinError 2] The system cannot find the file specified: 'playlist 2023-07-16 22_53 [playlist].mp4.part'
```

**Comment by bashonly** [comment]
ffmpeg doesn't allow that level of control over the download.

Also, your log doesn't really reflect your description of the issue; it looks like ffmpeg fails immediately with a 404 error on the first segment. So ffmpeg *is* aborting on the first unavailable fragment? If this is not the case, then maybe you should elaborate on what happened there.

In other cases, the best you can do is to use ffmpeg's HLS args: `max_reload`, `m3u8_hold_counters` and `seg_max_retry` (which already defaults to `0`)

`m3u8_hold_counters` and `max_reload` can be useful when a livestream ends and the playlist URL stays alive but the playlist is no longer being updated. By default, ffmpeg will retry 1000 times before aborting and writing the end of the file. But you could do this:
`--downloader-args "ffmpeg_o:-m3u8_hold_counters 12 -max_reload 12"`

https://ffmpeg.org/ffmpeg-formats.html#hls-1
```
max_reload

    Maximum number of times a insufficient list is attempted to be reloaded. Default value is 1000.

m3u8_hold_counters

    The maximum number of times to load m3u8 when it refreshes without new segments. Default value is 1000.

seg_max_retry

    Maximum number of times to reload a segment on error, useful when segment skip on network error is not desired. Default value is 0. 
```
