### ISSUE TITLE
Add support for Funkwhale Libraries and Playlists

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [yt-dlp/yt-dlp#7627]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

All

### Example URLs

- single track from library https://funk.firobe.fr/library/tracks/110004
- playlist https://funk.firobe.fr/library/playlists/117
- channel https://funk.firobe.fr/channels/digitalmenteliberi@funkwhale.it

### Provide a description that is worded well enough to be understood

Funkwhale is decentralized/federated (ActivityPub) software for audio.
https://funkwhale.audio/

There are multiple instances ("pods"):
https://network.funkwhale.audio/dashboards/d/W98gLx7Zk/instance-finder?orgId=1

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://funk.firobe.fr/library/tracks/110004']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.2.0-1008-lowlatency-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://funk.firobe.fr/library/tracks/110004
[generic] 110004: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 110004: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://funk.firobe.fr/library/tracks/110004
Traceback (most recent call last):
  File "/home/bbb/.local/pipx/venvs/yt-dlp/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bbb/.local/pipx/venvs/yt-dlp/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/bbb/.local/pipx/venvs/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bbb/.local/pipx/venvs/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://funk.firobe.fr/library/tracks/110004
```

**Comment by moan0s** [comment]
I would really like to see Funkwhale to be supported.

For a temporary workaround you can use the RSS Feeds feature that yt-dlp is able to download. The link you can use looks like `https://example.org/api/v1/channels/USERNAME/rss`

![Image showing the RSS button on a redacted funkwhale profile](https://github.com/yt-dlp/yt-dlp/assets/25753802/cd68b936-7dd2-4814-94f0-2284dcb320cc)

**Comment by dirkf** [comment]
At OP's example instance, this path `/api/v1/channels/digitalmenteliberi@funkwhale.it/rss` redirects to the given example channel URL, whose non-JS page has no channel content data.

In principle a page extractor could look for 
```html
<meta name="generator" content="Funkwhale">
```
On a non-JS track page, such as OP's example track URL, there is this:
```html
<meta content="https://funk.firobe.fr/api/v1/listen/f02af00a-4093-43c7-a027-3607c9df274c/" property="og:audio" />
```
But this URL gives 503 for me.
