### ISSUE TITLE
[Vidio] how to fix this error?

### ISSUE THREAD

**Issue by rrfqi** [yt-dlp/yt-dlp#7671]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How to download the premier non free videos?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-N', '16', '--remux-video', 'mkv', '--embed-subs', '--sub-langs', 'id', '--convert-subs', 'srt', '--no-part', '-u', 'PRIVATE', '-p', 'PRIVATE', '--list-formats', '-o', 'F:\\yt-dlp-master\\downloads\\%(title)s.%(ext)s', 'https://www.vidio.com/watch/7557135-ep-02-hantu']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.13 (CPython AMD64 64bit) - Windows-10-10.0.14393-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-102186-g8b83a4a885 (setts)
[debug] Optional libraries: certifi-2023.05.07, pycrypto-3.18.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[Vidio] Downloading JSON metadata
[Vidio] Checking if logged in
[Vidio] Downloading log in page
[Vidio] Logging in
[Vidio] Extracting URL: https://www.vidio.com/watch/7557135-ep-02-hantu
[Vidio] ep-02-hantu: Downloading webpage
[Vidio] ep-02-hantu: Downloading premier API JSON
ERROR: [Vidio] 7557135: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "F:\yt-dlp-master\yt_dlp\extractor\vidio.py", line 137, in _real_extract
    sources = self._download_json(
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 1033, in download_handle
    res = self._download_webpage_handle(
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "F:\yt-dlp-master\yt_dlp\networking\_urllib.py", line 432, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "C:\Users\vmsg\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\vmsg\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\vmsg\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\vmsg\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\vmsg\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 4060, in urlopen
    return self._request_director.send(req)
  File "F:\yt-dlp-master\yt_dlp\networking\common.py", line 89, in send
    response = handler.send(request)
  File "F:\yt-dlp-master\yt_dlp\networking\_helper.py", line 203, in wrapper
    return func(self, *args, **kwargs)
  File "F:\yt-dlp-master\yt_dlp\networking\common.py", line 297, in send
    return self._send(request)
  File "F:\yt-dlp-master\yt_dlp\networking\_urllib.py", line 437, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "F:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 4079, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden
```

**Comment by rrfqi** [comment]
I've use `--cookies-from-browser chrome` still get the same error

```
[debug] Command-line config: ['-vU', '-N', '16', '--remux-video', 'mkv', '--embed-subs', '--sub-langs', 'id', '--convert-subs', 'srt', '--no-part', '-u', 'PRIVATE', '-p', 'PRIVATE', '--list-formats', '--cookies-from-browser', 'chrome', '-o', 'F:\\yt-dlp-master\\downloads\\%(title)s.%(ext)s', 'https://www.vidio.com/watch/7557135-ep-02-hantu']
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\vmsg\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\vmsg\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 237 cookies from chrome
[debug] cookie version breakdown: {'v10': 237, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.13 (CPython AMD64 64bit) - Windows-10-10.0.14393-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-102186-g8b83a4a885 (setts)
[debug] Optional libraries: certifi-2023.05.07, pycrypto-3.18.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[Vidio] Downloading JSON metadata
[Vidio] Checking if logged in
[Vidio] Extracting URL: https://www.vidio.com/watch/7557135-ep-02-hantu
[Vidio] ep-02-hantu: Downloading webpage
[Vidio] ep-02-hantu: Downloading premier API JSON
ERROR: [Vidio] 7557135: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "F:\yt-dlp-master\yt_dlp\extractor\vidio.py", line 137, in _real_extract
    sources = self._download_json(
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 1033, in download_handle
    res = self._download_webpage_handle(
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "F:\yt-dlp-master\yt_dlp\networking\_urllib.py", line 432, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "C:\Users\vmsg\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\vmsg\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\vmsg\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\vmsg\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\vmsg\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 4060, in urlopen
    return self._request_director.send(req)
  File "F:\yt-dlp-master\yt_dlp\networking\common.py", line 89, in send
    response = handler.send(request)
  File "F:\yt-dlp-master\yt_dlp\networking\_helper.py", line 203, in wrapper
    return func(self, *args, **kwargs)
  File "F:\yt-dlp-master\yt_dlp\networking\common.py", line 297, in send
    return self._send(request)
  File "F:\yt-dlp-master\yt_dlp\networking\_urllib.py", line 437, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "F:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 4079, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden
```

**Comment by october262** [comment]
try using a cookies.txt file or the username & password option.
also, the video might be DRM protected.

**Comment by rrfqi** [comment]
I see, is it possible to download drm'ed videos with `--allow-u`

**Comment by pukkandan** [comment]
> I see, is it possible to download drm'ed videos with `--allow-u`?

No
