### ISSUE TITLE
offlinetest fails on test_httplib_validation_errors

### ISSUE THREAD

**Issue by syphyr** [yt-dlp/yt-dlp#7674]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

After 227bf1a33be7b89cd7d44ad046844c4ccba104f4 was committed, performing `make offlinetest PYTHON=python3`, shows the following error: 

FAILED test/test_networking.py::TestUrllibRequestHandler::test_httplib_validation_errors[Urllib] - AssertionError: Regex pattern did not match.

This above error occurs with both python 3.7 and 3.9.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
============================================================================== FAILURES ===============================================================================
___________________________________________________ TestUrllibRequestHandler.test_httplib_validation_errors[Urllib] ___________________________________________________

self = <yt_dlp.networking._urllib.UrllibRH object at 0x7f0cf80c8650>, request = <yt_dlp.networking.common.Request object at 0x7f0cf8798150>

    def _send(self, request):
        headers = self._merge_headers(request.headers)
        add_accept_encoding_header(headers, SUPPORTED_ENCODINGS)
        urllib_req = urllib.request.Request(
            url=request.url,
            data=request.data,
            headers=dict(headers),
            method=request.method
        )
    
        opener = self._get_instance(
            proxies=request.proxies or self.proxies,
            cookiejar=request.extensions.get('cookiejar') or self.cookiejar
        )
        try:
>           res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))

yt_dlp/networking/_urllib.py:432: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.7/urllib/request.py:531: in open
    response = meth(req, response)
/usr/lib/python3.7/urllib/request.py:641: in http_response
    'http', request, response, code, msg, hdrs)
/usr/lib/python3.7/urllib/request.py:569: in error
    return self._call_chain(*args)
/usr/lib/python3.7/urllib/request.py:503: in _call_chain
    result = func(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <urllib.request.HTTPDefaultErrorHandler object at 0x7f0cf863ddd0>, req = <urllib.request.Request object at 0x7f0cfe1318d0>
fp = <http.client.HTTPResponse object at 0x7f0cf85c9350>, code = 400, msg = 'Bad Request', hdrs = <http.client.HTTPMessage object at 0x7f0cf85c9d90>

    def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.full_url, code, msg, hdrs, fp)
E       urllib.error.HTTPError: HTTP Error 400: Bad Request

/usr/lib/python3.7/urllib/request.py:649: HTTPError

The above exception was the direct cause of the following exception:

self = <test.test_networking.TestUrllibRequestHandler object at 0x7f0cf857f5d0>
handler = functools.partial(<class 'yt_dlp.networking._urllib.UrllibRH'>, logger=<class 'yt_dlp.utils._YDLLogger'>)

    @pytest.mark.parametrize('handler', ['Urllib'], indirect=True)
    def test_httplib_validation_errors(self, handler):
        with handler() as rh:
    
            # https://github.com/python/cpython/blob/987b712b4aeeece336eed24fcc87a950a756c3e2/Lib/http/client.py#L1256
            with pytest.raises(RequestError, match='method can\'t contain control characters') as exc_info:
>               validate_and_send(rh, Request('http://127.0.0.1', method='GET\n'))

test/test_networking.py:793: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/test_networking.py:275: in validate_and_send
    return rh.send(req)
yt_dlp/networking/_helper.py:203: in wrapper
    return func(self, *args, **kwargs)
yt_dlp/networking/common.py:297: in send
    return self._send(request)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <yt_dlp.networking._urllib.UrllibRH object at 0x7f0cf80c8650>, request = <yt_dlp.networking.common.Request object at 0x7f0cf8798150>

    def _send(self, request):
        headers = self._merge_headers(request.headers)
        add_accept_encoding_header(headers, SUPPORTED_ENCODINGS)
        urllib_req = urllib.request.Request(
            url=request.url,
            data=request.data,
            headers=dict(headers),
            method=request.method
        )
    
        opener = self._get_instance(
            proxies=request.proxies or self.proxies,
            cookiejar=request.extensions.get('cookiejar') or self.cookiejar
        )
        try:
            res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
        except urllib.error.HTTPError as e:
            if isinstance(e.fp, (http.client.HTTPResponse, urllib.response.addinfourl)):
                # Prevent file object from being closed when urllib.error.HTTPError is destroyed.
                e._closer.file = None
>               raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
E               yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

yt_dlp/networking/_urllib.py:437: HTTPError

During handling of the above exception, another exception occurred:

self = <test.test_networking.TestUrllibRequestHandler object at 0x7f0cf857f5d0>
handler = functools.partial(<class 'yt_dlp.networking._urllib.UrllibRH'>, logger=<class 'yt_dlp.utils._YDLLogger'>)

    @pytest.mark.parametrize('handler', ['Urllib'], indirect=True)
    def test_httplib_validation_errors(self, handler):
        with handler() as rh:
    
            # https://github.com/python/cpython/blob/987b712b4aeeece336eed24fcc87a950a756c3e2/Lib/http/client.py#L1256
            with pytest.raises(RequestError, match='method can\'t contain control characters') as exc_info:
>               validate_and_send(rh, Request('http://127.0.0.1', method='GET\n'))
E               AssertionError: Regex pattern did not match.
E                Regex: "method can't contain control characters"
E                Input: 'HTTP Error 400: Bad Request'

test/test_networking.py:793: AssertionError
======================================================================= short test summary info =======================================================================
SKIPPED [1] test/test_jsinterp.py:111: Not implemented
SKIPPED [1] test/test_jsinterp.py:373: Not implemented
SKIPPED [1] test/test_jsinterp.py:335: Not implemented
FAILED test/test_networking.py::TestUrllibRequestHandler::test_httplib_validation_errors[Urllib] - AssertionError: Regex pattern did not match.
================================================ 1 failed, 460 passed, 3 skipped, 5548 deselected in 99.00s (0:01:38) =================================================
```

**Comment by coletdjnz** [comment]
What are the exact versions of python you are testing on?

Have a suspicion that the expected behaviour might not be present in older minor versions (as it is a result of patches for a number of security vulnerabilities)

**Comment by syphyr** [comment]
I tried Python 3.7.5 (from ubuntu) and self-compiled Python 3.9.17.  Both versions of python produce the same issue.

**Comment by coletdjnz** [comment]
The one shown in the log isn't patched in 3.7.5, so will need to make an exemption for that: https://github.com/advisories/GHSA-w7gf-rpqw-gx4f
> Python 3.x before 3.5.10, 3.6.x before 3.6.12, 3.7.x before 3.7.9, and 3.8.x before 3.8.5

I'm guessing another one of the checks in that test is failing in 3.9.17.

**Comment by syphyr** [comment]
> I'm guessing another one of the checks in that test is failing in 3.9.17.
> 
> Maybe to keep it simple we skip the test if an HTTPError is raised 🤔

Skipping the test if an error is raised sounds reasonable.

**Comment by coletdjnz** [comment]
Actually, checking for HTTPError won't suffice, so I'm going to have to whitelist Python versions.

Can you show the output for 3.9.17? All of these should be working for that version :confused:

**Comment by syphyr** [comment]
I just added https://github.com/yt-dlp/yt-dlp/pull/7677 and did a build with 3.9.17:

```
test/test_networking.py::TestHTTPRequestHandler::test_headers[Urllib] PASSED                                                                                    [ 33%]
test/test_networking.py::TestHTTPRequestHandler::test_timeout[Urllib] PASSED                                                                                    [ 34%]
test/test_networking.py::TestHTTPRequestHandler::test_source_address[Urllib] Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 433, in handle
    self.handle_one_request()
PASSED                                                                             [ 34%]  File "/usr/lib/python3.9/http/server.py", line 422, in handle_one_request
    self.wfile.flush() #actually send the response if not already done.
ValueError: I/O operation on closed file.
----------------------------------------

test/test_networking.py::TestHTTPRequestHandler::test_gzip_trailing_garbage[Urllib] PASSED                                                                      [ 34%]
test/test_networking.py::TestHTTPRequestHandler::test_brotli[Urllib] PASSED                                                                                     [ 34%]
test/test_networking.py::TestHTTPRequestHandler::test_deflate[Urllib] PASSED
```

Here is the output of the error with 3.9.17 without including your latest patch to fix httplib_validation_errors:

```
============================================================================== FAILURES ===============================================================================
___________________________________________________ TestUrllibRequestHandler.test_httplib_validation_errors[Urllib] ___________________________________________________

self = <yt_dlp.networking._urllib.UrllibRH object at 0x7f57c89f7a60>, request = <yt_dlp.networking.common.Request object at 0x7f57c8e588e0>

    def _send(self, request):
        headers = self._merge_headers(request.headers)
        add_accept_encoding_header(headers, SUPPORTED_ENCODINGS)
        urllib_req = urllib.request.Request(
            url=request.url,
            data=request.data,
            headers=dict(headers),
            method=request.method
        )
    
        opener = self._get_instance(
            proxies=request.proxies or self.proxies,
            cookiejar=request.extensions.get('cookiejar') or self.cookiejar
        )
        try:
>           res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))

yt_dlp/networking/_urllib.py:437: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.9/urllib/request.py:517: in open
    response = self._open(req, data)
/usr/lib/python3.9/urllib/request.py:534: in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
/usr/lib/python3.9/urllib/request.py:494: in _call_chain
    result = func(*args)
yt_dlp/networking/_urllib.py:130: in http_open
    return self.do_open(functools.partial(
/usr/lib/python3.9/urllib/request.py:1346: in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
/usr/lib/python3.9/http/client.py:1285: in request
    self._send_request(method, url, body, headers, encode_chunked)
/usr/lib/python3.9/http/client.py:1296: in _send_request
    self.putrequest(method, url, **skips)
/usr/lib/python3.9/http/client.py:1124: in putrequest
    self._validate_method(method)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <http.client.HTTPConnection object at 0x7f57c8a33160>, method = 'GET\n'

    def _validate_method(self, method):
        """Validate a method name for putrequest."""
        # prevent http header injection
        match = _contains_disallowed_method_pchar_re.search(method)
        if match:
>           raise ValueError(
                    f"method can't contain control characters. {method!r} "
                    f"(found at least {match.group()!r})")
E           ValueError: method can't contain control characters. 'GET\n' (found at least '\n')

/usr/lib/python3.9/http/client.py:1221: ValueError

The above exception was the direct cause of the following exception:

self = <test.test_networking.TestUrllibRequestHandler object at 0x7f57c8d40c10>
handler = functools.partial(<class 'yt_dlp.networking._urllib.UrllibRH'>, logger=<class 'yt_dlp.utils._YDLLogger'>)

    @pytest.mark.parametrize('handler', ['Urllib'], indirect=True)
    def test_httplib_validation_errors(self, handler):
        with handler() as rh:
    
            # https://github.com/python/cpython/blob/987b712b4aeeece336eed24fcc87a950a756c3e2/Lib/http/client.py#L1256
            with pytest.raises(RequestError, match='method can\'t contain control characters') as exc_info:
                validate_and_send(rh, Request('http://127.0.0.1', method='GET\n'))
            assert not isinstance(exc_info.value, TransportError)
    
            # https://github.com/python/cpython/blob/987b712b4aeeece336eed24fcc87a950a756c3e2/Lib/http/client.py#L1265
            with pytest.raises(RequestError, match='URL can\'t contain control characters') as exc_info:
>               validate_and_send(rh, Request('http://127.0.0.1', method='GET\n'))

test/test_networking.py:798: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/test_networking.py:275: in validate_and_send
    return rh.send(req)
yt_dlp/networking/_helper.py:203: in wrapper
    return func(self, *args, **kwargs)
yt_dlp/networking/common.py:297: in send
    return self._send(request)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <yt_dlp.networking._urllib.UrllibRH object at 0x7f57c89f7a60>, request = <yt_dlp.networking.common.Request object at 0x7f57c8e588e0>

    def _send(self, request):
        headers = self._merge_headers(request.headers)
        add_accept_encoding_header(headers, SUPPORTED_ENCODINGS)
        urllib_req = urllib.request.Request(
            url=request.url,
            data=request.data,
            headers=dict(headers),
            method=request.method
        )
    
        opener = self._get_instance(
            proxies=request.proxies or self.proxies,
            cookiejar=request.extensions.get('cookiejar') or self.cookiejar
        )
        try:
            res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
        except urllib.error.HTTPError as e:
            if isinstance(e.fp, (http.client.HTTPResponse, urllib.response.addinfourl)):
                # Prevent file object from being closed when urllib.error.HTTPError is destroyed.
                e._closer.file = None
                raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
            raise  # unexpected
        except urllib.error.URLError as e:
            cause = e.reason  # NOTE: cause may be a string
    
            # proxy errors
            if 'tunnel connection failed' in str(cause).lower() or isinstance(cause, SocksProxyError):
                raise ProxyError(cause=e) from e
    
            handle_response_read_exceptions(cause)
            raise TransportError(cause=e) from e
        except (http.client.InvalidURL, ValueError) as e:
            # Validation errors
            # http.client.HTTPConnection raises ValueError in some validation cases
            # such as if request method contains illegal control characters [1]
            # 1. https://github.com/python/cpython/blob/987b712b4aeeece336eed24fcc87a950a756c3e2/Lib/http/client.py#L1256
>           raise RequestError(cause=e) from e
E           yt_dlp.networking.exceptions.RequestError: method can't contain control characters. 'GET\n' (found at least '\n')

yt_dlp/networking/_urllib.py:458: RequestError

During handling of the above exception, another exception occurred:

self = <test.test_networking.TestUrllibRequestHandler object at 0x7f57c8d40c10>
handler = functools.partial(<class 'yt_dlp.networking._urllib.UrllibRH'>, logger=<class 'yt_dlp.utils._YDLLogger'>)

    @pytest.mark.parametrize('handler', ['Urllib'], indirect=True)
    def test_httplib_validation_errors(self, handler):
        with handler() as rh:
    
            # https://github.com/python/cpython/blob/987b712b4aeeece336eed24fcc87a950a756c3e2/Lib/http/client.py#L1256
            with pytest.raises(RequestError, match='method can\'t contain control characters') as exc_info:
                validate_and_send(rh, Request('http://127.0.0.1', method='GET\n'))
            assert not isinstance(exc_info.value, TransportError)
    
            # https://github.com/python/cpython/blob/987b712b4aeeece336eed24fcc87a950a756c3e2/Lib/http/client.py#L1265
            with pytest.raises(RequestError, match='URL can\'t contain control characters') as exc_info:
>               validate_and_send(rh, Request('http://127.0.0.1', method='GET\n'))
E               AssertionError: Regex pattern did not match.
E                Regex: "URL can't contain control characters"
E                Input: "method can't contain control characters. 'GET\\n' (found at least '\\n')"

test/test_networking.py:798: AssertionError
======================================================================= short test summary info =======================================================================
SKIPPED [1] test/test_jsinterp.py:111: Not implemented
SKIPPED [1] test/test_jsinterp.py:373: Not implemented
SKIPPED [1] test/test_jsinterp.py:335: Not implemented
FAILED test/test_networking.py::TestUrllibRequestHandler::test_httplib_validation_errors[Urllib] - AssertionError: Regex pattern did not match.
================================================ 1 failed, 465 passed, 3 skipped, 5548 deselected in 88.62s (0:01:28) =================================================
```

**Comment by syphyr** [comment]
I am also using pytest 7.4.0.  I wonder if that has any affect on this issue.

**Comment by syphyr** [comment]
It looks like there is a typo on this line (extra space in the address):
https://github.com/yt-dlp/yt-dlp/blob/86aea0d3a213da3be1da638b9b828e6f0ee1d59f/test/test_networking.py#L798

**Comment by syphyr** [comment]
Sorry, that extra space was already fixed by your latest PR.

**Comment by syphyr** [comment]
I changed this line, but it did not fix the issue.

```
--- a/test/test_networking.py
+++ b/test/test_networking.py
@@ -796,7 +796,7 @@ def test_verify_cert_error_text(self, handler):
         # https://github.com/python/cpython/blob/987b712b4aeeece336eed24fcc87a950a756c3e2/Lib/http/client.py#L1265
         # bpo-38576: Check implemented in 3.7.8+, 3.8.3+
         (
-            Request('http://127.0.0. 1', method='GET'),
+            Request('http://127.0.0.1', method='GET'),
             'URL can\'t contain control characters',
             lambda v: v < (3, 7, 8) or (3, 8, 0) <= v < (3, 8, 3)
         ),
```

**Comment by syphyr** [comment]
It looks like the real error here is this:
ValueError: I/O operation on closed file.

**Comment by syphyr** [comment]
Since the same error is occuring in both 3.7.5 and 3.9.17, this could also be related to websockets 11.0.3, since that is where the trace starts.

**Comment by coletdjnz** [comment]
The extra space is intentional. I think it was the control character I had left in the method for that one.

The ValueError is by the test server and is expected, can ignore that.

**Comment by syphyr** [comment]
OK. https://github.com/yt-dlp/yt-dlp/pull/7677 skips the `test_source_address[Urllib]` as expected for python 3.7.5.  Also, the test is not failing anymore with python 3.9.17 when this change is applied. There is still an exception occurring on `test_source_address[Urllib]` but overall it passes now with python 3.9.17.

```
test/test_networking.py::TestHTTPRequestHandler::test_source_address[Urllib] ----------------------------------------
Exception occurred during processing of request from ('127.0.0.162', 37019)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
PASSED                                                                             [ 34%]  File "/usr/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 433, in handle
    self.handle_one_request()
ValueError: I/O operation on closed file.
----------------------------------------
```
