### ISSUE TITLE
[BiliIntl] urlopen error [WinError 10061]

### ISSUE THREAD

**Issue by VinhPham26** [yt-dlp/yt-dlp#7691]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

My yt-dlp work well with all the url except bilibili.tv. It alway show `urlopen error [WinError 10061]` error but in the browser I can access the url normarly. I did add `--add-header "Referer:https://www.bilibili.tv/"` but still no help. My PC did use 1.1.1.1 DNS to access to url, might be I need anything to setup more ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.bilibili.tv/vi/play/2073689/12692063', '--list-formats']
[debug] Home config "yt-dlp.conf": []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2021-05-19-git-2261cc6d8a-essentials_build-www.gyan.dev (setts), ffprobe 2021-05-19-git-2261cc6d8a-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[BiliIntl] Extracting URL: https://www.bilibili.tv/vi/play/2073689/12692063
[BiliIntl] 12692063: Downloading JSON metadata
WARNING: [BiliIntl] Unable to download JSON metadata: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
ERROR: 'bool' object has no attribute 'get'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1688, in __extract_info
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\bilibili.py", line 1282, in _real_extract
  File "yt_dlp\extractor\bilibili.py", line 908, in _call_api
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by bashonly** [comment]
> urlopen error [WinError 10061] No connection could be made because the target machine actively refused it

This seems to be an issue with ports. Are you using a proxy/VPN? Could be something like yt-dlp is trying to connect via http when the server only accepts https connections

**Comment by VinhPham26** [comment]
> Are you using a proxy/VPN?

No, I actually have to use VPN to download, and I don't use proxy

**Comment by pukkandan** [comment]
Then it looks like issue with your VPN

**Comment by VinhPham26** [comment]
> Then it looks like issue with your VPN

It actually opposite, with no proxy and VPN, I got that connection error, so I have to workaround by using VPN
