### ISSUE TITLE
Sometimes getting ES audio track instead of EN when using --cookies-from-browser FIREFOX,  (curiositystream but never used on other sites)

### ISSUE THREAD

**Issue by PirateOfMadagascar** [yt-dlp/yt-dlp#7702]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I realized that some episodes (currently only 1 out of 9) of the same show for some reason has Spanish instead of default English after download and merge. 
After testing and picking around I also found that I will be getting English if im not using Firefox cookies.

How to reproduce:
1) Download 2nd episode:
```bash
yt-dlp -vU https://curiositystream.com/series/26  -o "%(playlist)s\S01E%(playlist_index)s - %(title)s.%(ext)s" --cookies-from-browser FIREFOX --playlist-items 2
```
2) Open or check what audio id is used
Expected: En audio track is grabbed 
Actual: Spanish track is grabbed 

Again, this will download the English track (no firefox cookie) 
```bash
yt-dlp -vU https://curiositystream.com/series/26  -o "%(playlist)s\S01E%(playlist_index)s - %(title)s.%(ext)s" --playlist-items 2
```

I was looking for workaround to force only grab English but was not able to found any examples and all what I've tried gives me that im using wrong formats e.g.:
` -f "[lang=en]"` ` -f "[language=en]"` 

```bash
ERROR: [curiositystream] 111: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1709, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1768, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2859, in process_video_result
yt_dlp.utils.ExtractorError: [curiositystream] 111: Requested format is not available. Use --list-formats for a list of available formats
```

Im not sure if this actual bug or im doing something wrong! Let me know if I can force to pull EN only or Multi language  audio tracks.
Thank you in advance.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Playlist item:

$ yt-dlp -vU https://curiositystream.com/series/26  --playlist-items 2 --list-formats  --cookies-from-browser FIREFOX
[debug] Command-line config: ['-vU', 'https://curiositystream.com/series/26', '--playlist-items', '2', '--list-formats', '--cookies-from-browser', 'FIREFOX']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\PirateOfMadagascar\AppData\Roaming\Mozilla\Firefox\Profiles\zzzzz.default-release\cookies.sqlite"
[Cookies] Extracted 1068 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[curiositystream:series] Extracting URL: https://curiositystream.com/series/26
[debug] [curiositystream:series] Obtained auth_token cookie
[curiositystream:series] 26: Downloading JSON metadata
[download] Downloading playlist: Curious Minds: Anthropology
[curiositystream:series] Playlist Curious Minds: Anthropology: Downloading 1 items of 9
[download] Downloading item 1 of 1
[curiositystream] Extracting URL: https://curiositystream.com/video/111
[debug] [curiositystream] Obtained auth_token cookie
[curiositystream] 111: Downloading JSON metadata
[curiositystream] 111: Downloading m3u8 information
WARNING: [curiositystream] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[curiositystream] 111: Downloading JSON metadata
[curiositystream] 111: Downloading MPD manifest
WARNING: [curiositystream] Ignoring subtitle tracks found in the DASH manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 111:
ID                                        EXT RESOLUTION │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio_group-English                   mp4 audio only │                 m3u8  │ audio only        unknown             [en] English
hls-audio_group-Español                   mp4 audio only │                 m3u8  │ audio only        unknown             [es] Español
dash-c8623782-4f46-4d3c-9bf8-0369b45432f2 m4a audio only │ ~ 1.11MiB  160k dash  │ audio only        mp4a.40.2  160k 48k [en] DASH audio, m4a_dash
dash-fc903f74-f38c-4608-93d8-268c7306a763 m4a audio only │ ~ 1.11MiB  160k dash  │ audio only        mp4a.40.2  160k 48k [es] DASH audio, m4a_dash
dash-ebd06cef-cea9-4a31-ad1d-d46b9069c453 mp4 768x432    │ ~ 1.67MiB  240k dash  │ avc1.64001E  240k video only          DASH video, mp4_dash
hls-391                                   mp4 768x432    │ ~ 2.72MiB  391k m3u8  │ avc1.64001E  391k video only
dash-63e4e187-fb1a-40eb-8821-d084e32c8aa5 mp4 1280x720   │ ~ 3.17MiB  456k dash  │ avc1.64001F  456k video only          DASH video, mp4_dash
hls-579                                   mp4 1280x720   │ ~ 4.03MiB  580k m3u8  │ avc1.64001F  580k video only
dash-ca605118-b073-4319-8236-409695a3e59d mp4 1280x720   │ ~ 6.03MiB  866k dash  │ avc1.64001F  866k video only          DASH video, mp4_dash
hls-1025                                  mp4 1280x720   │ ~ 7.13MiB 1025k m3u8  │ avc1.64001F 1025k video only
dash-03953f89-f40c-46cd-9a16-4c842fe42281 mp4 1920x1080  │ ~ 6.51MiB  936k dash  │ avc1.640032  936k video only          DASH video, mp4_dash
hls-1088                                  mp4 1920x1080  │ ~ 7.58MiB 1089k m3u8  │ avc1.640032 1089k video only
dash-130e0a46-6fe9-45c9-84e5-084e595001ac mp4 1920x1080  │ ~10.87MiB 1562k dash  │ avc1.640032 1562k video only          DASH video, mp4_dash
hls-1754                                  mp4 1920x1080  │ ~12.21MiB 1755k m3u8  │ avc1.640032 1755k video only
dash-d3a3fb59-8a61-4bc9-8fb7-356edc6d910a mp4 1920x1080  │ ~18.14MiB 2607k dash  │ avc1.640032 2607k video only          DASH video, mp4_dash
hls-2879                                  mp4 1920x1080  │ ~20.04MiB 2880k m3u8  │ avc1.640032 2880k video only
[download] Finished downloading playlist: Curious Minds: Anthropology
```

Full debug download output:

```bash
$ yt-dlp -vU https://curiositystream.com/series/26  -o "%(playlist)s\S01E%(playlist_index)s - %(title)s.%(ext)s" --cookies-from-browser FIREFOX --playlist-items 2
[debug] Command-line config: ['-vU', 'https://curiositystream.com/series/26', '-o', '%(playlist)s\\S01E%(playlist_index)s - %(title)s.%(ext)s', '--cookies-from-browser', 'FIREFOX', '--playlist-items', '2']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\PirateOfMadagascar\AppData\Roaming\Mozilla\Firefox\Profiles\uzzzzzp.default-release\cookies.sqlite"
[Cookies] Extracted 1068 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[curiositystream:series] Extracting URL: https://curiositystream.com/series/26
[debug] [curiositystream:series] Obtained auth_token cookie
[curiositystream:series] 26: Downloading JSON metadata
[download] Downloading playlist: Curious Minds: Anthropology
[curiositystream:series] Playlist Curious Minds: Anthropology: Downloading 1 items of 9
[download] Downloading item 1 of 1
[curiositystream] Extracting URL: https://curiositystream.com/video/111
[debug] [curiositystream] Obtained auth_token cookie
[curiositystream] 111: Downloading JSON metadata
[curiositystream] 111: Downloading m3u8 information
WARNING: [curiositystream] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[curiositystream] 111: Downloading JSON metadata
[curiositystream] 111: Downloading MPD manifest
WARNING: [curiositystream] Ignoring subtitle tracks found in the DASH manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 111: Downloading 1 format(s): hls-2879+dash-fc903f74-f38c-4608-93d8-268c7306a763
[debug] Invoking hlsnative downloader on "https://cdn-s3-akm.curiositystream.com/bitmovin-outputs/CM_Miracle_Int_0714_22_Is_our_understanding_of_the_past_accurate.mov/vod-fix-1080_2606919_37fd6f2a-82b3-4ef3-a954-08b536b80174.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 15
[download] Destination: Curious Minds： Anthropology\S01E2 - Is Our Understanding Of The Past Accurate？.fhls-2879.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   18.40MiB in 00:00:01 at 13.73MiB/s
[debug] Invoking dashsegments downloader on "https://cdn-s3-akm.curiositystream.com/bitmovin-outputs/CM_Miracle_Int_0714_22_Is_our_understanding_of_the_past_accurate.mov/e0ffc419300dcdf1d1d68015395a4580.mpd"
[dashsegments] Total fragments: 16
[download] Destination: Curious Minds： Anthropology\S01E2 - Is Our Understanding Of The Past Accurate？.fdash-fc903f74-f38c-4608-93d8-268c7306a763.m4a
[download] 100% of    1.08MiB in 00:00:00 at 1.28MiB/s
[Merger] Merging formats into "Curious Minds： Anthropology\S01E2 - Is Our Understanding Of The Past Accurate？.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Curious Minds： Anthropology\S01E2 - Is Our Understanding Of The Past Accurate？.fhls-2879.mp4" -i "file:Curious Minds： Anthropology\S01E2 - Is Our Understanding Of The Past Accurate？.fdash-fc903f74-f38c-4608-93d8-268c7306a763.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Curious Minds： Anthropology\S01E2 - Is Our Understanding Of The Past Accurate？.temp.mp4"
Deleting original file Curious Minds： Anthropology\S01E2 - Is Our Understanding Of The Past Accurate？.fhls-2879.mp4 (pass -k to keep)
Deleting original file Curious Minds： Anthropology\S01E2 - Is Our Understanding Of The Past Accurate？.fdash-fc903f74-f38c-4608-93d8-268c7306a763.m4a (pass -k to keep)
[download] Finished downloading playlist: Curious Minds: Anthropology
```

**Comment by pukkandan** [comment]
You want `-f bv+ba[language=en]`
