### ISSUE TITLE
WrestleUniverse PPV not working

### ISSUE THREAD

**Issue by Adthrawn** [yt-dlp/yt-dlp#7708]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I am unable to download a PPV from WrestleUniverse, I get the following error message

ERROR: unable to download video data: <urlopen error unknown url type: irvine>

I've confirmed other VOD videos are still working on the site. I am willing to share my credentials if need be

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://www.wrestle-universe.com/en/lives/mmMtSW7vAf9z2ER41CDSSV']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.06.14.103120 [c8561c6d0] (linux_exe)
[debug] Python 3.10.11 (CPython x86_64 64bit) - Linux-5.15.0-78-generic-x86_64-with-glibc2.35 (OpenSSL 3.1.1 30 May 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/mike/.mozilla/firefox/1ks0sch7.default-release/cookies.sqlite"
[Cookies] Extracted 2496 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1843 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.07.24.001007, Current version: nightly@2023.06.14.103120
Current Build Hash: 83779aaa215985468b3cbc9890ad5a3a7a20ac761fc0cc934a8084396a92d2a0
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
Updating to nightly@2023.07.24.001007 ...
[debug] Downloading yt-dlp_linux from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/yt-dlp_linux
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/SHA2-256SUMS
Updated yt-dlp to nightly@2023.07.24.001007
[debug] Restarting: ./yt-dlp_linux -vU --cookies-from-browser firefox https://www.wrestle-universe.com/en/lives/mmMtSW7vAf9z2ER41CDSSV
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://www.wrestle-universe.com/en/lives/mmMtSW7vAf9z2ER41CDSSV']
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/mike/.mozilla/firefox/1ks0sch7.default-release/cookies.sqlite"
Extracted 2496 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.07.24.001007 [550e65410] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-78-generic-x86_64-with-glibc2.35 (OpenSSL 3.1.1 30 May 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.07.24.001007, Current version: nightly@2023.07.24.001007
Current Build Hash: 8c45d71ebcb18dc9c9afb411f5c6f31ee881ccb83d43e0c70d19d72c95d6b41f
yt-dlp is up to date (nightly@2023.07.24.001007)
[debug] Loading wrestleuniverse.device_id from cache
[WrestleUniversePPV] Extracting URL: https://www.wrestle-universe.com/en/lives/mmMtSW7vAf9z2ER41CDSSV
[WrestleUniversePPV] mmMtSW7vAf9z2ER41CDSSV: Downloading metadata JSON
[WrestleUniversePPV] mmMtSW7vAf9z2ER41CDSSV: Downloading watch archive JSON
[WrestleUniversePPV] mmMtSW7vAf9z2ER41CDSSV: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] mmMtSW7vAf9z2ER41CDSSV: Downloading 1 format(s): hls-9
[debug] Invoking hlsnative downloader on "https://vod.asset.wrestle-universe.com/wJbUAPgMFSsyDBAfNexEsr/live-b_1080p_2997fps.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1662
[download] Destination: 【PPV】TJPW Summer Athletic Park Match [mmMtSW7vAf9z2ER41CDSSV].mp4
[download]   0.1% of ~   2.13GiB at    6.42MiB/s ETA 05:37 (frag 1/1662)ERROR: Unable to handle request: Unsupported url scheme: "irvine" (urllib)
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1577, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1733, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1792, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2931, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 3397, in process_info
  File "yt_dlp/YoutubeDL.py", line 3118, in dl
  File "yt_dlp/downloader/common.py", line 455, in download
  File "yt_dlp/downloader/hls.py", line 375, in real_download
  File "yt_dlp/downloader/fragment.py", line 526, in download_and_append_fragments
  File "yt_dlp/downloader/fragment.py", line 367, in decrypt_fragment
  File "yt_dlp/downloader/fragment.py", line 356, in _get_key
  File "yt_dlp/YoutubeDL.py", line 4060, in urlopen
  File "yt_dlp/networking/common.py", line 103, in send
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: "irvine" (urllib)
```

**Comment by bashonly** [comment]
I can work on this; DM me on discord, same username
