### ISSUE TITLE
ERROR: Input strings must be a multiple of 16 in length

### ISSUE THREAD

**Issue by ndlarsen** [yt-dlp/yt-dlp#7723]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Downloading a [specific video](https://www.dr.dk/drtv/se/a-storm-foretold-_-det-amerikanske-oproer_389862)  from www.dr.dk fails with the following error:  `ERROR: Input strings must be a multiple of 16 in length`. When playing the video via the site from a browser, the video plays without issue. I have previously downloaded other series and single videos from the same site without issue while using the same version of yt-dlp.

```console
ndlarsen@master:~/temp/youtube-dl$ yt-dlp --version
2023.07.06

ndlarsen@master:~/temp/youtube-dl$ yt-dlp -U
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)

ndlarsen@master:~/temp/youtube-dl$ uname -a
Linux master 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

ndlarsen@master:~/temp/youtube-dl$ python --version
Python 3.8.10

```

Verifying that it is not a general issue with the site while using same command args:

```console
ndlarsen@master:~/temp/youtube-dl$ yt-dlp --write-auto-subs --write-subs --sub-langs en --sub-format srt --convert-subtitles srt --merge-output-format mkv -f "bestvideo[height<=1080]+bestaudio" https://www.dr.dk/drtv/se/konspirationernes-forenede-stater_212205
[drtv] Extracting URL: https://www.dr.dk/drtv/se/konspirationernes-forenede-stater_212205
[drtv] konspirationernes-forenede-stater_212205: Downloading webpage
[drtv] 00022015230: Downloading video JSON
[drtv] konspirationernes-forenede-stater_212205: Downloading JSON metadata
[drtv] 00022015230: Downloading m3u8 information
[drtv] 00022015230: Downloading m3u8 information
[drtv] 00022015230: Downloading m3u8 information
[drtv] 00022015230: Downloading m3u8 information
[info] 00022015230: Downloading 1 format(s): HLS-3308+HLS-idq6-English
[info] There are no subtitles for the requested languages
[SubtitlesConvertor] Converting subtitles
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 311
[download] Destination: Konspirationernes Forenede Stater [00022015230].fHLS-3308.mp4
[download] 100% of    1.13GiB in 00:02:19 at 8.28MiB/s
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 310
[download] Destination: Konspirationernes Forenede Stater [00022015230].fHLS-idq6-English.mp4
[download] 100% of   70.61MiB in 00:01:06 at 1.06MiB/s
[Merger] Merging formats into "Konspirationernes Forenede Stater [00022015230].mkv"
Deleting original file Konspirationernes Forenede Stater [00022015230].fHLS-3308.mp4 (pass -k to keep)
Deleting original file Konspirationernes Forenede Stater [00022015230].fHLS-idq6-English.mp4 (pass -k to keep)
```
```console
ndlarsen@master:~/temp/youtube-dl$ ls
'Konspirationernes Forenede Stater [00022015230].da.srt'  'Konspirationernes Forenede Stater [00022015230].info.json'  'Konspirationernes Forenede Stater [00022015230].mkv'
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ndlarsen@master:~/temp/youtube-dl/A.Storm.Foretold$ yt-dlp -vU --write-auto-subs --write-subs --sub-langs en --sub-format srt --convert-subtitles srt --merge-output-format mkv -f "bestvideo[height<=1080]+bestaudio" www.dr.dk/drtv/se/a-storm-foretold-_-det-amerikanske-oproer_389862
[debug] Command-line config: ['-vU', '--write-auto-subs', '--write-subs', '--sub-langs', 'en', '--sub-format', 'srt', '--convert-subtitles', 'srt', '--merge-output-format', 'mkv', '-f', 'bestvideo[height<=1080]+bestaudio', 'www.dr.dk/drtv/se/a-storm-foretold-_-det-amerikanske-oproer_389862']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-76-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Crypto-broken 2.6.1, certifi-2019.11.28, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: www.dr.dk/drtv/se/a-storm-foretold-_-det-amerikanske-oproer_389862
WARNING: [generic] The url doesn't specify the protocol, trying with http
[drtv] Extracting URL: http://www.dr.dk/drtv/se/a-storm-foretold-_-det-amerikanske-oproer_389862
[drtv] a-storm-foretold-_-det-amerikanske-oproer_389862: Downloading webpage
[drtv] 00921906100: Downloading video JSON
[drtv] a-storm-foretold-_-det-amerikanske-oproer_389862: Downloading JSON metadata
[drtv] 00921906100: Downloading m3u8 information
[drtv] 00921906100: Downloading m3u8 information
[drtv] 00921906100: Downloading m3u8 information
[drtv] 00921906100: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 00921906100: Downloading 1 format(s): HLS-5659+HLS-audio_medium-English
[info] There are no subtitles for the requested languages
[SubtitlesConvertor] Converting subtitles
[debug] Invoking hlsnative downloader on "https://drod24c.akamaized.net/dk/encrypted/none/62/649b00f6e656c806a48c7c62/00921906100/stream_fmp4/A-Storm-Foretol_DRTV2022Jan_FullHD_16x9_VideoMain_video_5500.m3u8?aka_me_session_id=AAAAAAAAAADCc8ZkAAAAAO+8MQ%2fXAeYYLnnFsh8iqYoVf8687ZYfyyAHCfqJcd1bgtsdgPjd2BKMXkbRLWJqbub7cbnJp0Gd&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 605
[download] Destination: A Storm Foretold - det amerikanske oprør [00921906100].fHLS-5659.mp4
[download]   0.3% of ~ 474.43KiB at    6.07KiB/s ETA 01:17 (frag 2/605)ERROR: Input strings must be a multiple of 16 in length
Traceback (most recent call last):
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2897, in process_video_result
    self.process_info(new_info)
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3345, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3084, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/downloader/common.py", line 461, in download
    ret = self.real_download(filename, info_dict)
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/downloader/hls.py", line 375, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 531, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 378, in decrypt_fragment
    return unpad_pkcs7(aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv))
  File "/home/ndlarsen/bin/yt-dlp/yt_dlp/aes.py", line 11, in aes_cbc_decrypt_bytes
    return Cryptodome.AES.new(key, Cryptodome.AES.MODE_CBC, iv).decrypt(data)
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
```

### Complete Verbose Output when using Linux standalone x64 binary
```console
ndlarsen@master:~/temp/youtube-dl$ yt-dlp_linux -vU --write-auto-subs --write-subs --sub-langs en --sub-format srt --convert-subtitles srt --merge-output-format mkv -f "bestvideo[height<=1080]+bestaudio" www.dr.dk/drtv/se/a-storm-foretold-_-det-amerikanske-oproer_389862
[debug] Command-line config: ['-vU', '--write-auto-subs', '--write-subs', '--sub-langs', 'en', '--sub-format', 'srt', '--convert-subtitles', 'srt', '--merge-output-format', 'mkv', '-f', 'bestvideo[height<=1080]+bestaudio', 'www.dr.dk/drtv/se/a-storm-foretold-_-det-amerikanske-oproer_389862']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-76-generic-x86_64-with-glibc2.31 (OpenSSL 3.1.1 30 May 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 0556fff82db6c942a5dfbb9583e2896013847b28b95186b3800f730a8d5e0c0a
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: www.dr.dk/drtv/se/a-storm-foretold-_-det-amerikanske-oproer_389862
WARNING: [generic] The url doesn't specify the protocol, trying with http
[drtv] Extracting URL: http://www.dr.dk/drtv/se/a-storm-foretold-_-det-amerikanske-oproer_389862
[drtv] a-storm-foretold-_-det-amerikanske-oproer_389862: Downloading webpage
[drtv] 00921906100: Downloading video JSON
[drtv] a-storm-foretold-_-det-amerikanske-oproer_389862: Downloading JSON metadata
[drtv] 00921906100: Downloading m3u8 information
[drtv] 00921906100: Downloading m3u8 information
[drtv] 00921906100: Downloading m3u8 information
[drtv] 00921906100: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 00921906100: Downloading 1 format(s): HLS-5659+HLS-audio_medium-English
[info] There are no subtitles for the requested languages
[SubtitlesConvertor] Converting subtitles
[debug] Invoking hlsnative downloader on "https://drod24c.akamaized.net/dk/encrypted/none/62/649b00f6e656c806a48c7c62/00921906100/stream_fmp4/A-Storm-Foretol_DRTV2022Jan_FullHD_16x9_VideoMain_video_5500.m3u8?aka_me_session_id=AAAAAAAAAAAnd8ZkAAAAAHSrqAuKnfXWkxJbpaQ5iPxsLF%2f0IlT6MGHPUBKXyJQpAl06jRY6e0LxnqQ94TNDdEA0hsMQbB1V&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 605
[download] Destination: A Storm Foretold - det amerikanske oprør [00921906100].fHLS-5659.mp4
[download]   0.3% of ~ 474.43KiB at    4.79KiB/s ETA 01:38 (frag 2/605)[download] A Storm Foretold - det amerikanske oprør [00921906100].fHLS-5659.mp4.part-Frag2 has already been downloaded
[download]   0.5% of ~ 474.43KiB at  218.41KiB/s ETA 01:38 (frag 3/605)ERROR: Data must be padded to 16 byte boundary in CBC mode
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1709, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2897, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 3345, in process_info
  File "yt_dlp/YoutubeDL.py", line 3084, in dl
  File "yt_dlp/downloader/common.py", line 461, in download
  File "yt_dlp/downloader/hls.py", line 375, in real_download
  File "yt_dlp/downloader/fragment.py", line 531, in download_and_append_fragments
  File "yt_dlp/downloader/fragment.py", line 378, in decrypt_fragment
  File "yt_dlp/aes.py", line 11, in aes_cbc_decrypt_bytes
  File "Cryptodome/Cipher/_mode_cbc.py", line 246, in decrypt
ValueError: Data must be padded to 16 byte boundary in CBC mode

```

**Comment by bashonly** [comment]
I'm geo-blocked. Could you run the command again with `--write-pages` and share the first ~12 lines of `https://drod24c.akamaized.net/dk/encrypted/none/62/649b00f6e656c806a48c7c62/00921906100/stream_fmp4/A-Storm-Foretol_DRTV2022Jan_FullHD_16x9_VideoMain_video_5500.m3u8`?

Also you could try with `--downloader ffmpeg`

**Comment by bashonly** [comment]
Related #3810, #1297

**Comment by ndlarsen** [comment]
> Try with `--downloader ffmpeg`

Seems to work doing so. I was under the impression that ffmpeg would be used by default if available but maybe I have misunderstood something.

Do you still want the contents of the dump and is so, which?

**Comment by bashonly** [comment]
> I was under the impression that ffmpeg would be used by default if available 

ffmpeg is used by default for HLS livestreams, and it is used for postprocessing (merging, etc). But the native HLS downloader is used by default for VOD/non-live HLS formats. Native depends on the python library Cryptodome (or Crypto), which is why you were getting different errors with zip vs standalone binary. 

> Do you still want the contents of the dump and if so, which?

No, not necessary, I had misread the log at first. The issue looks to have the same root cause as #3810 and #1297

**Comment by ndlarsen** [comment]
> > I was under the impression that ffmpeg would be used by default if available
> 
> ffmpeg is used by default for HLS livestreams, and it is used for postprocessing (merging, etc). But the native HLS downloader is used by default for VOD/non-live HLS formats. Native depends on the python library Cryptodome (or Crypto), which is why you were getting different errors with zip vs standalone binary.

Alright, thanks for the explanation.
 
> > Do you still want the contents of the dump and if so, which?
> 
> No, not necessary, I had misread the log at first. The issue looks to have the same root cause as #3810 and #1297

Alright, thanks. I will close the issue as the root cause seems to be reported already.
