### ISSUE TITLE
Patreon not downloading playlists

### ISSUE THREAD

**Issue by ws-leung** [yt-dlp/yt-dlp#7736]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

When downloading individual Patreon videos, yt-dlp works perfectly. But when attempting to download any collection of Patreon videos, each item within the playlist is given the same error message as follows: "ERROR: expected string or bytes-like object, got 'NoneType'". This is the same when attempting to download a playlist of Patreon videos, or when attempting to use the `--force-write-archive` command for a Patreon playlist.

Note: I've had to edit the Complete Verbose output, as it repeats the same error for all 418 items, thus making the Complete Verbose Output much longer than the comment limit. Can re-post the Complete Verbose Output if need be.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', '/Users/winstonleung/cookies.txt', '--force-write-archive', 'https://www.patreon.com/theyard/posts']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.3 (CPython x86_64 64bit) - macOS-12.6-x86_64-i386-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[PatreonCampaign] Extracting URL: https://www.patreon.com/theyard/posts
[PatreonCampaign] theyard: Downloading webpage
[PatreonCampaign] 6742942: Downloading campaign info
[download] Downloading playlist: the yard
[PatreonCampaign] 6742942: Downloading posts page 1
[PatreonCampaign] 6742942: Downloading posts page 2
[PatreonCampaign] 6742942: Downloading posts page 3
[PatreonCampaign] 6742942: Downloading posts page 4
[PatreonCampaign] 6742942: Downloading posts page 5
[PatreonCampaign] 6742942: Downloading posts page 6
[PatreonCampaign] 6742942: Downloading posts page 7
[PatreonCampaign] 6742942: Downloading posts page 8
[PatreonCampaign] 6742942: Downloading posts page 9
[PatreonCampaign] 6742942: Downloading posts page 10
[PatreonCampaign] 6742942: Downloading posts page 11
[PatreonCampaign] 6742942: Downloading posts page 12
[PatreonCampaign] 6742942: Downloading posts page 13
[PatreonCampaign] 6742942: Downloading posts page 14
[PatreonCampaign] 6742942: Downloading posts page 15
[PatreonCampaign] 6742942: Downloading posts page 16
[PatreonCampaign] 6742942: Downloading posts page 17
[PatreonCampaign] 6742942: Downloading posts page 18
[PatreonCampaign] 6742942: Downloading posts page 19
[PatreonCampaign] 6742942: Downloading posts page 20
[PatreonCampaign] 6742942: Downloading posts page 21
[PatreonCampaign] Playlist the yard: Downloading 418 items of 418
[download] Downloading item 1 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 2 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 3 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 4 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 5 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 6 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 7 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 8 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 9 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 10 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 11 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Downloading item 12 of 418
ERROR: expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2014, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1536, in extract_info
    if not ie.suitable(url):
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 579, in suitable
    return cls._match_valid_url(url) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in _match_valid_url
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 572, in <genexpr>
    return next(filter(None, (regex.match(url) for regex in cls._VALID_URL_RE)), None)
                              ^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[download] Finished downloading playlist: the yard
```

**Comment by bashonly** [comment]
Fixed by 11de6fec9c9b8d34d1f90c8e6218ec58a3471b58

[Install the master branch with pip](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master) or get the [nightly build](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases) (`yt-dlp --update-to nightly`)
