### ISSUE TITLE
videos where bestvideo+bestaudio is used can have .m4a + webm streams, ffmpeg fail to merge when using format webm

### ISSUE THREAD

**Issue by hellupline** [yt-dlp/yt-dlp#775]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
yt-dlp \
    --verbose \
    --output '%(id)s.%(ext)s' \
    --format 'bestvideo+bestaudio/best' \
    --merge-output-format 'webm' \
    --keep-video \
    -- \
    H2Zv7gw-8c4

[debug] Command-line config: ['--verbose', '--output', '%(id)s.%(ext)s', '--format', 'bestvideo+bestaudio/best', '--merge-output-format', 'webm', '--keep-video', '--', 'H2Zv7gw-8c4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.10.53-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: keyring, mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: H2Zv7gw-8c4
[debug] Sort order given by extractor: quality, height, fps, source
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, height, fps, source, res, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[debug] Unable to connect to thumbnail 41 URL "https://i.ytimg.com/vi_webp/H2Zv7gw-8c4/maxresdefault.webp" - HTTP Error 404: Not Found. Skipping...
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1629758984/ei/qNEjYYynJs7NwgTWyLXoAQ/ip/138.204.26.13/id/1f666fee0c3ef1ce/source/youtube/requiressl/yes/playback_host/r6---sn-jv2xauxaxjvh-jfcs.googlevideo.com/mh/Zu/mm/31%2C29/mn/sn-jv2xauxaxjvh-jfcs%2Csn-bg0eznll/ms/au%2Crdu/mv/m/mvi/6/pl/24/tx/24064675/txs/24064674%2C24064675%2C24064676%2C24064677%2C24064678/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/893750/vprv/1/mt/1629737098/fvip/2/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhAI-dRxgLY_04ok4F5iO456bkG2MbmG1kDv7ZOy17aZz8AiAuswgIPhM_u1VtCxUx34QhrW52aR4kUpGemJcdO7HUVw%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhALx-vAEJDi1wv4W_Q4MtrhkBIl6S5IaFusYna6B0H5N9AiEA-qlz59rAwdlpOWLx4ycj_gY0iK0IShRr0h-j77DErOY%3D"
[debug] Invoking downloader on "https://r6---sn-jv2xauxaxjvh-jfcs.googlevideo.com/videoplayback?expire=1629758985&ei=qdEjYceCCIbCxwSzlofgBg&ip=138.204.26.13&id=o-AIeqEI0JCFnynwK81LyN13elHR7HKHbnZ3dUiKnHy3sJ&itag=140&source=youtube&requiressl=yes&mh=Zu&mm=31%2C29&mn=sn-jv2xauxaxjvh-jfcs%2Csn-bg0eznll&ms=au%2Crdu&mv=m&mvi=6&pl=24&initcwndbps=893750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=1155938&otfp=1&dur=71.378&lmt=1580047552620584&mt=1629737098&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgBsru9r68sl9mWkSDzJksaJcInpRjoWD2gaQoHrzfGjgCIH4HNuTxjV1tmK3ZK0vk8cFZ-fdYoyXh5_rzHXJMsipI&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgRYiqWb-KZu7Sz9fO4KgiiK7tOnLEm4OyUBc6O96qFwwCIQDn-mpX_cZyEtyQ4Ttg1gDSG1gKN3CVbi-Njwoa5O1TzA%3D%3D"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:H2Zv7gw-8c4.f247.webm -i file:H2Zv7gw-8c4.f140.m4a -c copy -map 0:v:0 -map 1:a:0 file:H2Zv7gw-8c4.temp.webm
ERROR: ffmpeg version n4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from 'file:H2Zv7gw-8c4.f247.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 14 
                    : Segment-Durations-Ms: 5120(r=12),4720, 
                    :  
                    : 
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1280x720, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'file:H2Zv7gw-8c4.f140.m4a':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    creation_time   : 2020-01-26T14:05:50.000000Z
  Duration: 00:01:11.38, start: 0.000000, bitrate: 129 kb/s
  Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 17 kb/s (default)
    Metadata:
      creation_time   : 2020-01-26T14:05:50.000000Z
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
[webm @ 0x555e526ecf80] Only VP8 or VP9 or AV1 video and Vorbis or Opus audio and WebVTT subtitles are supported for WebM.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
  File "REDACTED/.local/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/__init__.py", line 750, in main
    _real_main(argv)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/__init__.py", line 740, in _real_main
    retcode = ydl.download(all_urls)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2868, in download
    res = self.extract_info(
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1192, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1237, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1281, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2299, in process_video_result
    self.process_info(new_info)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2838, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2987, in post_process
    info = self.run_pp(pp, info)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2936, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 83, in wrapper
    return func(self, info)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 648, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 237, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 274, in real_run_ffmpeg
    self.report_error(stderr)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 56, in report_error
    return self._downloader.report_error(text, *args, **kwargs)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 809, in report_error
    self.trouble(error_message, tb)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 765, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2838, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2987, in post_process
    info = self.run_pp(pp, info)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2936, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 83, in wrapper
    return func(self, info)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 648, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 237, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "REDACTED/.local/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 275, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

```

## Description

WRITE DESCRIPTION HERE

yt-dlp uses the following command to merge 2 files, note the `-c copy`  argument
```
ffmpeg \
    -y -loglevel repeat+info \
    -i file:REDACTED/H2Zv7gw-8c4.f247.webm \
    -i file:REDACTED/H2Zv7gw-8c4.f140.m4a \
    -c copy \
    -map 0:v:0 -map 1:a:0 \
    file:REDACTED/temp.webm
```
changing it to encode audio as libvorbis solves:
```
ffmpeg \
    -y -loglevel repeat+info \
    -i file:REDACTED/H2Zv7gw-8c4.f247.webm \
    -i file:REDACTED/H2Zv7gw-8c4.f140.m4a \    
    -c:v copy \
    -c:a libvorbis \
    -map 0:v:0 \
    -map 1:a:0 \
    file:REDACTED/temp.webm
```

**Comment by pukkandan** [comment]
yt-dlp (or youtube-dl) will not re-encode while merging. This is intentional. You can either use the `--recode` option or use `--postprocessor-args` to pass custom args to ffmpeg

**Comment by hellupline** [comment]
> use `--postprocessor-args` to pass custom args to ffmpeg

using:
`--postprocessor-args 'Merger+ffmpeg:-c:a libvorbis'`

works perfectly thank you pukkadan

its possible to only use this when `m4a` only ?

I saw this on `--recode-video` but I didnt understand how to use that  option

**Comment by pukkandan** [comment]
Just replace `--merge-output-format` with `--recode webm`. That will re-encode the video too though. Assuming you will always download vp9/av1, you can do this:

```
$ yt-dlp -v --recode webm H2Zv7gw-8c4 -f 278+140 --ppa "videoconvertor:-c:v copy"
[debug] Command-line config: ['-v', '--recode', 'webm', 'H2Zv7gw-8c4', '-f', '278+140', '--ppa', 'videoconvertor:-c:v copy']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 45842107b9
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg n4.4-79-gde1132a891-20210809, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: H2Zv7gw-8c4
[youtube] H2Zv7gw-8c4: Downloading webpage
[youtube] H2Zv7gw-8c4: Downloading android player API JSON
[youtube] H2Zv7gw-8c4: Downloading MPD manifest
[youtube] H2Zv7gw-8c4: Downloading MPD manifest
[debug] Sort order given by extractor: quality, height, fps, source
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, height, fps, source, res, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[debug] Unable to connect to thumbnail 41 URL "https://i.ytimg.com/vi_webp/H2Zv7gw-8c4/maxresdefault.webp" - HTTP Error 404: Not Found. Skipping...
[info] H2Zv7gw-8c4: Downloading 1 format(s): 278+140
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1629793573/ei/xFgkYaHdOq3_4-EPksSq8AU/ip/49.37.189.4/id/1f666fee0c3ef1ce/source/youtube/requiressl/yes/playback_host/r6---sn-gwpa-cags.googlevideo.com/mh/Zu/mm/31%2C29/mn/sn-gwpa-cags%2Csn-gwpa-h55e7/ms/au%2Crdu/mv/m/mvi/6/pcm2cms/yes/pl/25/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/295000/vprv/1/mt/1629771646/fvip/6/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgNe0wkYtBQ1UzGxNslujzZ8i4PAE-b46xzartL4E3o94CICatAk1IO1cWbxEugGD4qYAJ23jzBs0RYmI6ml3xaF3k/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgOX02rgm5LWEcLuYCmLAknVqCmkXnwqkbT_8Oj5kB_aYCIEMHf9PdZqLXJOSViyK_Qg8bv4H81guZV6S56SeoFwyV"
[dashsegments] Total fragments: 15
[download] Destination: V Speech [H2Zv7gw-8c4].f278.webm
[download] 100% of 94.83KiB in 00:11
[debug] Invoking downloader on "https://r6---sn-gwpa-cags.googlevideo.com/videoplayback?expire=1629793573&ei=xVgkYZH6GJO0oAOm4IDIBw&ip=49.37.189.4&id=o-ACARQm2osVjqBodgtPNx4VpzfN_q_yKbpqPNVlEJIpMQ&itag=140&source=youtube&requiressl=yes&mh=Zu&mm=31%2C29&mn=sn-gwpa-cags%2Csn-gwpa-h55e7&ms=au%2Crdu&mv=m&mvi=6&pl=25&initcwndbps=295000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=1155938&otfp=1&dur=71.378&lmt=1580047552620584&mt=1629771646&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgXzH3XNkx_Q8c6115vKDdMCAAruHibnACfvgIVYmUeJICIQCXOAJJ65bRwi--z6qDxrOtxN_BDL_-oTz3U-_VgHiFuA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgBIzpv3A_ERLu7j1rKbGk0JyQ8ac3kOh60aiJgcRGsHMCIQCqE3A2oE41UbZGC7yjx2XRWCQtdYLXJofIJVa1MHhznQ%3D%3D"
[download] Destination: V Speech [H2Zv7gw-8c4].f140.m4a
[download] 100% of 1.10MiB in 00:00
[Merger] Merging formats into "V Speech [H2Zv7gw-8c4].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:V Speech [H2Zv7gw-8c4].f278.webm" -i "file:V Speech [H2Zv7gw-8c4].f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:V Speech [H2Zv7gw-8c4].temp.mkv"
Deleting original file V Speech [H2Zv7gw-8c4].f278.webm (pass -k to keep)
Deleting original file V Speech [H2Zv7gw-8c4].f140.m4a (pass -k to keep)
[VideoConvertor] Converting video from mkv to webm; Destination: V Speech [H2Zv7gw-8c4].webm
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:V Speech [H2Zv7gw-8c4].mkv" "-c:v" copy "file:V Speech [H2Zv7gw-8c4].webm"
Deleting original file V Speech [H2Zv7gw-8c4].mkv (pass -k to keep)
```

**Comment by shirt-dev** [comment]
The WebM container does not support AAC (m4a) audio.

**Comment by pukkandan** [comment]
@shirt-dev OP was asking about how to automatically transcode it when the codec is incompatible. 

I believe I have answered the question and there has been no reply, so closing
