### ISSUE TITLE
TikTok Download Failure with Spanish Characters in Video Description

### ISSUE THREAD

**Issue by Davis-3450** [yt-dlp/yt-dlp#7752]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

TikTok downloads fail when the video description contains Spanish characters such as ‘ñ’ or tildes. Here is the output:

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@midudev/video/7231923725107481882']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[TikTok] Extracting URL: https://www.tiktok.com/@midudev/video/7231923725107481882
[TikTok] 7231923725107481882: Downloading video feed
[debug] Sort order given by extractor: quality, codec, size, br
[debug] Formats sorted by: hasvid, ie_pref, quality, vcodec, acodec, size, br, lang, res, fps, hdr:12(7), channels, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7231923725107481882: Downloading 1 format(s): bytevc1_1080p_667925-2
[debug] Invoking http downloader on "https://v58.tiktokcdn.com/video/tos/useast2a/tos-useast2a-pve-0037c001-aiso/oo7CmBfLhIzGnGPAoHkot0hrycEgIoFhnHQn9A/?a=1180&ch=0&cr=13&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=1304&bt=652&cs=2&ds=4&ft=XsdJ8qqmmBA2D12Ny9F-G-Ux8gf_agF_O5&mime_type=video_mp4&qs=15&rc=ZzppZ2U5Omk1ZWQ5OTo2aUBpajRwdzk6Zm1pazMzZjczM0AyX2NiNWI2NV8xYl9iXjQ0YSMwYS1pcjRvNWJgLS1kMWNzcw%3D%3D&l=202308020832143D38912DDC744305A69E&VExpiration=1690986747&VSignature=WAd4Gp-nhLwq5fxi47VynA&btag=e00088000&cc=14"
[download] Unable to open file: [Errno 22] Invalid argument: 'Curso de Microsoft y en Español para Aprender a Programar con Python desde cero. El curso consta de 4 horas y 12 módulos. Aprenderás a crear programas y proyectos en Python. Trabajarás con cadenas, listas, bucles, diccionarios y funciones. Es una oportunidad buenísima para empezar en programación sin tener que pagar nada. Además es bastante practico y tendrás que ir superando retos para ver si has entendido el contenido. ¡Compártelo para que llegue a más gente! #programacion #python #programador #programadores [7231923725107481882].mp4.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Curso de Microsoft y en Español para Aprender a Programar con Python desde cero. El curso consta de 4 horas y 12 módulos. Aprenderás a crear programas y proyectos en Python. Trabajarás con cadenas, listas, bucles, diccionarios y funciones. Es una oportunidad buenísima para empezar en programación sin tener que pagar nada. Además es bastante practico y tendrás que ir superando retos para ver si has entendido el contenido. ¡Compártelo para que llegue a más gente! #programacion #python #programador #programadores [7231923725107481882].mp4.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Curso de Microsoft y en Español para Aprender a Programar con Python desde cero. El curso consta de 4 horas y 12 módulos. Aprenderás a crear programas y proyectos en Python. Trabajarás con cadenas, listas, bucles, diccionarios y funciones. Es una oportunidad buenísima para empezar en programación sin tener que pagar nada. Además es bastante practico y tendrás que ir superando retos para ver si has entendido el contenido. ¡Compártelo para que llegue a más gente! #programacion #python #programador #programadores [7231923725107481882].mp4.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: 'Curso de Microsoft y en Español para Aprender a Programar con Python desde cero. El curso consta de 4 horas y 12 módulos. Aprenderás a crear programas y proyectos en Python. Trabajarás con cadenas, listas, bucles, diccionarios y funciones. Es una oportunidad buenísima para empezar en programación sin tener que pagar nada. Además es bastante practico y tendrás que ir superando retos para ver si has entendido el contenido. ¡Compártelo para que llegue a más gente! #programacion #python #programador #programadores [7231923725107481882].mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 662, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 273, in download
  File "yt_dlp\downloader\common.py", line 239, in wrapper
  File "yt_dlp\utils\_utils.py", line 5634, in __iter__
  File "yt_dlp\downloader\common.py", line 232, in error_callback
  File "yt_dlp\utils\_utils.py", line 5642, in report_retry
  File "yt_dlp\downloader\common.py", line 241, in wrapper
  File "yt_dlp\downloader\common.py", line 252, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 665, in sanitize_open
OSError: [Errno 22] Invalid argument: 'Curso de Microsoft y en Español para Aprender a Programar con Python desde cero. El curso consta de 4 horas y 12 módulos. Aprenderás a crear programas y proyectos en Python. Trabajarás con cadenas, listas, bucles, diccionarios y funciones. Es una oportunidad buenísima para empezar en programación sin tener que pagar nada. Además es bastante practico y tendrás que ir superando retos para ver si has entendido el contenido. ¡Compártelo para que llegue a más gente! #programacion #python #programador #programadores [7231923725107481882].mp4.part'
```

**Comment by bashonly** [comment]
Are you sure it's not just because the filenames are too long?

Try adding `-o "%(title).100B [%(id)s].%(ext)s"` to your command

**Comment by hashimaziz1** [comment]
Was having this issue with another video that definitely didn't have any non-Unicode characters in the title and this solution worked perfectly.

> Are you sure it's not just because the filenames are too long?
> 
> Try adding `-o "%(title).100B [%(id)s].%(ext)s"` to your command

Was having this issue with another video that definitely didn't have any non-Unicode characters in the title and this solution worked perfectly.
