### ISSUE TITLE
[spotify] different URL format

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#7760]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

global (as far as I can tell)

### Provide a description that is worded well enough to be understood

I did search before opening this issue, and saw some references describing the spotify extractor as "broken," so I have some uncertainty about this.

I wanted to download the following podcast (output when attempting to do so included below):

https://embed-standalone.spotify.com/embed/show/3fRPRZRNC9O7S8u40CSk2D

Things I noticed:

1. The spotify extractor doesn't include URLs with the domain "embed-standalone.spotify.com".

2. A trace of network traffic reveals a request to: https://spclient.wg.spotify.com/soundfinder/v1/unauth/episode/2HOmKcPv7zWFXM7Aw6m6bZ/com.widevine.alpha (hope this doesn't count as "DRM").

3. After some redirects, the network trace produced the following URL (I would guess that the parameters change every request, so I will obscure those): https://dcs.megaphone.fm/FOXM8668344330.mp3?key=0123456789abcdef0123456789abcdef&request_event_id=01234567-89ab-cdef-0123-456789abcdef (which I could easily download with wget and play).

I wonder if you could add this URL format to the spotify extractor.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--restrict-filenames', '-o', '%(title).200s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', 'https://embed-standalone.spotify.com/embed/show/3fRPRZRNC9O7S8u40CSk2D']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.1.28-gentoo-x86_64-Intel-R-_Core-TM-_i5-3470_CPU_@_3.20GHz-with-glibc2.37 (OpenSSL 3.0.9 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.18.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[generic] Extracting URL: https://embed-standalone.spotify.com/embed/show/3fRPRZRNC9O7S8u40CSk2D
[generic] 3fRPRZRNC9O7S8u40CSk2D: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 3fRPRZRNC9O7S8u40CSk2D: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://embed-standalone.spotify.com/embed/show/3fRPRZRNC9O7S8u40CSk2D
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://embed-standalone.spotify.com/embed/show/3fRPRZRNC9O7S8u40CSk2D
```

**Comment by pukkandan** [comment]
https://open.spotify.com/episode/2HOmKcPv7zWFXM7Aw6m6bZ is also currently broken. So simply supporting the new URL pattern will not be enough till the extractor gets fixed. But yes, once we get the normal spotify links to work, this is trivial to add support for.

**Comment by meliber** [comment]
The current version of spotify extractor crashes due to "Bad request" error. However the ie still can't get the full media URL instead of a preview because this line below doesn't work.
```python
if audio_preview_url:
            f = {
                'url': audio_preview_url.replace('://p.scdn.co/mp3-preview/', '://anon-podcast.scdn.co/'),
                'vcodec': 'none',
            }
``` 

```python
for item in (try_get(episode, lambda x: x['audio']['items']) or []):
            item_url = item.get('url')
            if not (item_url and item.get('externallyHosted')):
                continue
            formats.append({
                'url': clean_podcast_url(item_url),
                'vcodec': 'none',
            })
``` 
Here is the line to fix the API request.

```
diff --git a/yt_dlp/extractor/spotify.py b/yt_dlp/extractor/spotify.py
index 55ce36aea..0a6fee839 100644
--- a/yt_dlp/extractor/spotify.py
+++ b/yt_dlp/extractor/spotify.py
@@ -23,7 +23,7 @@ class SpotifyBaseIE(InfoExtractor):
         'MinimalShow': '13ee079672fad3f858ea45a55eb109553b4fb0969ed793185b2e34cbb6ee7cc0',
         'ShowEpisodes': 'e0e5ce27bd7748d2c59b4d44ba245a8992a05be75d6fabc3b20753fc8857444d',
     }
-    _VALID_URL_TEMPL = r'https?://open\.spotify\.com/(?:embed-podcast/|embed/|)%s/(?P<id>[^/?&#]+)'
+    _VALID_URL_TEMPL = r'https?://(?:open|embed-standalone)\.spotify\.com/(?:embed-podcast/|embed/|)%s/(?P<id>[^/?&#]+)'
     _EMBED_REGEX = [r'<iframe[^>]+src="(?P<url>https?://open\.spotify.com/embed/[^"]+)"']
 
     def _real_initialize(self):
@@ -37,6 +37,7 @@ def _call_api(self, operation, video_id, variables, **kwargs):
                 'variables': json.dumps(variables),
                 'extensions': json.dumps({
                     'persistedQuery': {
+                        'version': 1,
                         'sha256Hash': self._OPERATION_HASHES[operation],
                     },
                 })
~
```

**Comment by gunchleoc** [comment]
This code will get rid of the API error message and download something, but for podcasts, only the last segment, so most of the episode will be missing from the downloaded file.

**Comment by 2l47** [comment]
Subscribing to this issue. Current yt-dlp behavior for a Spotify podcast episode:
```
pi@raspberrypi:~ $ yt-dlp -U
Latest version: stable@2024.07.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.07 from yt-dlp/yt-dlp)
pi@raspberrypi:~ $ yt-dlp --verbose 'https://open.spotify.com/episode/3NXuoJWPOYdCrDkwMj8HkL'
[debug] Command-line config: ['--verbose', 'https://open.spotify.com/episode/3NXuoJWPOYdCrDkwMj8HkL']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.07 from yt-dlp/yt-dlp [b337d2989] (pip)
[debug] Python 3.11.2 (CPython aarch64 64bit) - Linux-6.1.21-v8+-aarch64-with-glibc2.36 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.5-0 (setts), ffprobe 5.1.5-0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2022.09.24, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[spotify] Downloading JSON metadata
[spotify] Extracting URL: https://open.spotify.com/episode/3NXuoJWPOYdCrDkwMj8HkL
[spotify] 3NXuoJWPOYdCrDkwMj8HkL: Downloading JSON metadata
ERROR: [spotify] 3NXuoJWPOYdCrDkwMj8HkL: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/extractor/spotify.py", line 126, in _real_extract
    episode = self._call_api('Episode', episode_id, {
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/extractor/spotify.py", line 34, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4161, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 361, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

pi@raspberrypi:~ $ 
```

**Comment by bashonly** [comment]
won't be supported
