### ISSUE TITLE
Video can be downloaded but 403 Forbidden Error on Audio of Youtube Premium urls

### ISSUE THREAD

**Issue by rizzyfring** [yt-dlp/yt-dlp#7761]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

For Youtube Premium urls, the .webm video is successfully downloaded but all of the available formats of the audio are returning HTTP 403 Forbidden Error (I am using master branch)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'filename.txt', '-f', '356+251', 'https://www.youtube.com/watch?v=SsLzlH4vBx4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.10.10 (CPython x86_64 64bit) - macOS-12.6.5-x86_64-i386-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.07.06, Current version: 2023.02.17
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube] Extracting URL: https://www.youtube.com/watch?v=SsLzlH4vBx4
[youtube] SsLzlH4vBx4: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] SsLzlH4vBx4: Downloading android player API JSON
[debug] Loading youtube-nsig.2363d0d2 from cache
[debug] [youtube] Decrypted nsig pZTc6T-GTqCAcz => ni-BgH1sSm3Fnw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] SsLzlH4vBx4: Downloading 1 format(s): 356+251
[debug] Invoking http downloader on "https://rr3---sn-5n5ip-ioq6.googlevideo.com/videoplayback?expire=1691085917&ei=_ZfLZMCnGN62qAG88oD4CQ&ip=2405%3A6580%3A25c0%3A7000%3Aa5c9%3A4b73%3Ab924%3Ab034&id=o-ABhst2y3VbkJUEdXc2BXHHpxMKRZXGZCO3CxcGCbpI-W&itag=356&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C356%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=3R&mm=31%2C29&mn=sn-5n5ip-ioq6%2Csn-ogul7n7d&ms=au%2Crdu&mv=m&mvi=3&pl=34&ctier=A&pfa=5&initcwndbps=672500&hightc=yes&siu=1&spc=UWF9f9872Y5vHYjhoZoElLNW3IgxQD9kRMFqRWtwLxRpgLzzE7EUsI8&vprv=1&svpuc=1&mime=video%2Fwebm&ns=Xk4BHN_yOlB9EwbDkWUQGAsP&gir=yes&clen=398718279&dur=679.379&lmt=1685745768152297&mt=1691064059&fvip=3&keepalive=yes&fexp=24007246%2C24362687&beids=24350018&c=WEB&txp=5532434&n=ni-BgH1sSm3Fnw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cctier%2Cpfa%2Chightc%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJlA6cOlH8_wcs5ff4gnV6uSMHmlXsirvRV6mYdYkENGAiEAwOsZMtzGhYZFII_rcUIuqF6gDQc1k3vNUq7yz0CZDSI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMvKI5mor1q-smBQ_K-ZN4mxGo1e-M0e9s21Z48jKBGxAiEA5w3IUDS748G4LzN8vbvEjChZLezp77EHfYS75U7cNtg%3D"
[download] 【グラビアメイキング】撮影の裏側！水着が見せられないのが多過ぎましたwww [SsLzlH4vBx4].f356.webm has already been downloaded
[download] 100% of  380.25MiB
[debug] Invoking http downloader on "https://rr3---sn-5n5ip-ioq6.googlevideo.com/videoplayback?expire=1691085918&ei=_pfLZLDIBtmo7OsPwZ2BiAo&ip=2405%3A6580%3A25c0%3A7000%3Aa5c9%3A4b73%3Ab924%3Ab034&id=o-AHzemOXI_v7RoKuLaP-jSolYFFjfRmqsx-bi0ZrM9zAI&itag=251&source=youtube&requiressl=yes&mh=3R&mm=31%2C29&mn=sn-5n5ip-ioq6%2Csn-ogul7n7d&ms=au%2Crdu&mv=m&mvi=3&pl=34&ctier=A&pfa=5&initcwndbps=697500&hightc=yes&siu=1&spc=UWF9f-Kxga24cEBGb5kgeOxImd4hJ-5RpshULMFaeZKhemhXAQP9eQ4&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=10856438&dur=679.401&lmt=1685742728385570&mt=1691063819&fvip=3&keepalive=yes&fexp=24007246%2C24362685%2C24362687&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Chightc%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgW_677Ud3EbX_O-u5Beij7F4dz0YHhw794BuJZQ1M3jMCIByzagYrll9upCEJDQEiBe2GXLgvdYdbxKksQZHNTRj4&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPGwoSLgeNSNU2qW8qNqYfacjq70Z16pgRB9UpyzI8uFAiAed09PCEOQGDgcvE9e0hUCEOevOrHrSZNfo9q2pNaSUw%3D%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2023.2.17/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3213, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/Cellar/yt-dlp/2023.2.17/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2954, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/Cellar/yt-dlp/2023.2.17/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/Cellar/yt-dlp/2023.2.17/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 376, in real_download
    establish_connection()
  File "/usr/local/Cellar/yt-dlp/2023.2.17/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/Cellar/yt-dlp/2023.2.17/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3726, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
Could you try without the cookies? I can't reproduce

**Comment by pukkandan** [comment]
> ```shell
> [debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
> ```

Hold on. You are not on master branch, but on a very old version

**Comment by rizzyfring** [comment]
oh man, my bad! I don't know how I missed that...  it seems https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip did not work because I had installed previously using brew.

thank you so much!
