### ISSUE TITLE
Cannot download twitter videos with emojis in the text/filename

### ISSUE THREAD

**Issue by cynoclast** [yt-dlp/yt-dlp#7772]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Downloading twitter videos fails if they have emojis or other weird characters in the filename.

Any logged in twitter account should work, I don't have special access, just an account, but I'm not sharing my twitter credentials.

Neither `--replace-in-metadata title "[\U00010000-\U0010ffff]" ""` nor `--restrict-filenames` fixed the issue.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\User\Desktop>yt-dlp -vU --cookies-from-browser brave:"Profile 1" --replace-in-metadata title "[\U00010000-\U0010ffff]" "" https://twitter.com/charliekirk11/status/1687550916554334208
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'brave:Profile 1', '--replace-in-metadata', 'title', '[\\U00010000-\\U0010ffff]', '', 'https://twitter.com/charliekirk11/status/1687550916554334208']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-04-11-git-d6d46a2c50-full_build-www.gyan.dev (setts), ffprobe 2022-04-11-git-d6d46a2c50-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Profile 1\Network\Cookies"
[debug] Found local state file at "C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Local State"
[Cookies] Extracted 2505 cookies from brave
[debug] cookie version breakdown: {'v10': 2505, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[twitter] Extracting URL: https://twitter.com/charliekirk11/status/1687550916554334208
[twitter] 1687550916554334208: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1687550329599180802
[twitter] 1687550916554334208: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, br, size, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Replacing all '[\\U00010000-\\U0010ffff]' in title with ''
[MetadataParser] Changed title to: Charlie Kirk - BREAKING: In never-before-aired footage from Tucker Carlson's interview with Steven Sund, the former Chief of the Capitol Hill Police, says J6 was "crawling with feds."   Sund details that there were 18 FBI undercover agents, plus an additional 20 agents from DHS.   In over 30…
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1687550329599180802: Downloading 1 format(s): http-2176
[debug] Invoking http downloader on "https://video.twimg.com/ext_tw_video/1687550329599180802/pu/vid/880x496/FsD8cFX1hBb_ieUm.mp4?tag=12"
[download] Unable to open file: [Errno 22] Invalid argument: "Charlie Kirk - BREAKING： In never-before-aired footage from Tucker Carlson's interview with Steven Sund, the former Chief of the Capitol Hill Police, says J6 was ＂crawling with feds.＂   Sund details that there were 18 FBI undercover agents, plus an additional 20 agents from DHS.   In over 30… [1687550329599180802].mp4.part". Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: "Charlie Kirk - BREAKING： In never-before-aired footage from Tucker Carlson's interview with Steven Sund, the former Chief of the Capitol Hill Police, says J6 was ＂crawling with feds.＂   Sund details that there were 18 FBI undercover agents, plus an additional 20 agents from DHS.   In over 30… [1687550329599180802].mp4.part". Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: "Charlie Kirk - BREAKING： In never-before-aired footage from Tucker Carlson's interview with Steven Sund, the former Chief of the Capitol Hill Police, says J6 was ＂crawling with feds.＂   Sund details that there were 18 FBI undercover agents, plus an additional 20 agents from DHS.   In over 30… [1687550329599180802].mp4.part". Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: "Charlie Kirk - BREAKING： In never-before-aired footage from Tucker Carlson's interview with Steven Sund, the former Chief of the Capitol Hill Police, says J6 was ＂crawling with feds.＂   Sund details that there were 18 FBI undercover agents, plus an additional 20 agents from DHS.   In over 30… [1687550329599180802].mp4.part"
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 662, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 273, in download
  File "yt_dlp\downloader\common.py", line 239, in wrapper
  File "yt_dlp\utils\_utils.py", line 5634, in __iter__
  File "yt_dlp\downloader\common.py", line 232, in error_callback
  File "yt_dlp\utils\_utils.py", line 5642, in report_retry
  File "yt_dlp\downloader\common.py", line 241, in wrapper
  File "yt_dlp\downloader\common.py", line 252, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 665, in sanitize_open
OSError: [Errno 22] Invalid argument: "Charlie Kirk - BREAKING： In never-before-aired footage from Tucker Carlson's interview with Steven Sund, the former Chief of the Capitol Hill Police, says J6 was ＂crawling with feds. ＂   Sund details that there were 18 FBI undercover agents, plus an additional 20 agents from DHS.   In over 30… [1687550329599180802].mp4.part"
```

**Comment by bashonly** [comment]
You're getting the error because the filename is too long

Remedy this with an output template, e.g.
`-o "%(title).100B [%(id)s].%(ext)s"`

**Comment by cynoclast** [comment]
Why is it up to me to figure this out? This is still a bug from a user perspective. It's creating filenames too long for itself to handle.

**Comment by bashonly** [comment]
There is an open issue/enhancement request about this #1136
