### ISSUE TITLE
[

### ISSUE THREAD

**Issue by pmlandwehr** [yt-dlp/yt-dlp#7784]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I think this might be a repeat of #6677 - a `zoom.us/rec/play` URL fails to download while reporting that no video is found. Perhaps Zoom has changed something since April? That said, this video specifically differs from the one in the original issue in that it is password-protected.  The password is a mix of capital letters, numbers, and the `@` character.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~> yt-dlp -Uv --cookies-from-browser firefox --video-pass "redacted" https://zoom.us/rec/play/ap_PRTmLBF6NcpyNdS7D5aHxYQcTqYjx6KuCDVQULfoN0IBcImhjm4p8y42Lgr6Th-bWMlJNp4D8az98.AfTAvYMOOIs12hLv
[debug] Command-line config: ['-Uv', '--cookies-from-browser', 'firefox', '--video-pass', 'redacted', 'https://zoom.us/rec/play/ap_PRTmLBF6NcpyNdS7D5aHxYQcTqYjx6KuCDVQULfoN0IBcImhjm4p8y42Lgr6Th-bWMlJNp4D8az98.AfTAvYMOOIs12hLv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.5-arm64-arm-64bit (OpenSSL 3.1.2 1 Aug 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/Users/pmlandwehr/Library/Application Support/Firefox/Profiles/kq7r9nno.default/cookies.sqlite"
[Cookies] Extracted 3035 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[zoom] Extracting URL: https://zoom.us/rec/play/ap_PRTmLBF6NcpyNdS7D5aHxYQcTqYjx6KuCDVQULfoN0IBcImhjm4p8y42Lgr6Th-bWMlJNp4D8az98.AfTAvYMOOIs12hLv
[zoom] ap_PRTmLBF6NcpyNdS7D5aHxYQcTqYjx6KuCDVQULfoN0IBcImhjm4p8y42Lgr6Th-bWMlJNp4D8az98.AfTAvYMOOIs12hLv: Downloading play webpage
[zoom] ap_PRTmLBF6NcpyNdS7D5aHxYQcTqYjx6KuCDVQULfoN0IBcImhjm4p8y42Lgr6Th-bWMlJNp4D8az98.AfTAvYMOOIs12hLv: Downloading play info JSON
WARNING: Extractor failed to obtain "title". Creating a generic title instead
ERROR: [zoom] ap_PRTmLBF6NcpyNdS7D5aHxYQcTqYjx6KuCDVQULfoN0IBcImhjm4p8y42Lgr6Th-bWMlJNp4D8az98.AfTAvYMOOIs12hLv: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2732, in process_video_result
    self.raise_no_formats(info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1073, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [zoom] ap_PRTmLBF6NcpyNdS7D5aHxYQcTqYjx6KuCDVQULfoN0IBcImhjm4p8y42Lgr6Th-bWMlJNp4D8az98.AfTAvYMOOIs12hLv: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
```

**Comment by bashonly** [comment]
Password-protected Zooms are broken: #2299

But it looks like we aren't even detecting the password-protection anymore, which should be fixed, and could be tracked as a separate issue
