### ISSUE TITLE
Add support of videas.fr with app.videas.fr instead a domain of videa.hu.

### ISSUE THREAD

**Issue by codenamedpkt** [yt-dlp/yt-dlp#7786]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Global

### Example URLs

- Single video examples:
1. https://app.videas.fr/embed/string-id-to-video-assigned-by-the-host-provider/
2. https://app.videas.fr/v/string-id-to-video-assigned-by-the-host-provider/

- Example of Video:
1. https://app.videas.fr/embed/7dde6333-0506-4d95-a2d7-312d4188a5af/
2. https://app.videas.fr/v/7dde6333-0506-4d95-a2d7-312d4188a5af/

Currently, we could only download single video and playlist is not available right now due to they are for private hosting only, by link or somewhere else.

### Provide a description that is worded well enough to be understood

We could not download the link: https://app.videas.fr/embed/7dde6333-0506-4d95-a2d7-312d4188a5af/, due to missing videas.fr.py or app.videas.fr.py in extractors under yt_dlp directory. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://app.videas.fr/v/7dde6333-0506-4d95-a2d7-312d4188a5af/']
[debug] User config "/data/data/com.termux/files/home/.yt-dlp/config": ['-cw', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0.23516; Win64; riscv128; rv:118) SPDY/4 Chrome/117.0.5935.0 Edg/117.0.2007.0 Safari/617.1.3 AppleWebKit/617.1.3 (KHTML, like Gecko) AppleWebKitGTK/2.41.6 FxiOS/118.0a1 yt-dlp/$VERSION aria2/$VERSION wget2/$VERSION curl/$VERSION Transmission/4.1.0-dev+ IPTV Pro/$VERSION', '--user-agent', 'Mozilla/5.0 (iPad Pro; GPU iPad OS 17_0_0 like Mac OS X) AppleWebKit/617.1.3 (KHTML, like Gecko) AppleWebKitGTK/2.41.6 FxiOS/118.0a1 Version/17.0 Tablet/21A5291j Safari/617.1.3', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0.23516/; Win64; riscv128; rv:106) AppleWebKit/608.5.12 (KHTML, like Gecko) Chrome/106.0.5249.225 FxiOS/106.0.5 Version/17.0 Safari/608.5.12', '-N', '9223372036854775807', '-f', 'mergeall', '--video-multistreams', '--audio-multistreams', '--merge-output-format', 'mp4', '--embed-subs', '--sub-langs', 'all', '--sub-format', 'best', '--embed-thumbnail', '--embed-chapters', '--downloader', 'aria2c', '--downloader-args', 'aria2c:-d$(pwd) --input-file= --lowest-speed-limit 0']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.4 (CPython aarch64 64bit) - Linux-4.9.186-22986754-aarch64-with-libc (OpenSSL 3.1.2 1 Aug 2023, libc)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.1, sqlite3-2.6.0, websockets-12.0.dev0+gunknown
[debug] Proxy map: {}
[debug] Loaded 1856 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://app.videas.fr/v/7dde6333-0506-4d95-a2d7-312d4188a5af/
[generic] 7dde6333-0506-4d95-a2d7-312d4188a5af: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 7dde6333-0506-4d95-a2d7-312d4188a5af: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://app.videas.fr/v/7dde6333-0506-4d95-a2d7-312d4188a5af/
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://app.videas.fr/v/7dde6333-0506-4d95-a2d7-312d4188a5af/
```

**Comment by dvolgyes** [comment]
I understand the wish for videas.fr, etc, but why "instead of videa.hu"? 
Actually, videa.hu is a quite popular site in Hungary (in the top 20 considering all categories, and 2nd only to youtube in video domain.), so it would be nice to keep its support.

**Comment by d4f5409d** [comment]
Videa.hu crash

```App version: 1.11.1-(F-Droid) (11114)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.11.16

URL: https://videa.hu/videok/film-animacio/elpusztithatatlanok-1988-F338ouJ4fWNgJ1uE#single-video-share
ERROR: [Videa] F338ouJ4fWNgJ1uE: Unable to download webpage: HTTP Error 405: Method Not Allowed (caused by <HTTPError 405: Method Not Allowed>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by Abcmsaj** [comment]
+1

**Comment by dirkf** [comment]
videa.hu is not apparently related to videas.fr except that they share the first 5 letters of their domain names and are domiciled in the EU.

A problem with videa.hu should probably be raised separately, and following the site's reporting guidelines:
> I understand that I will be blocked if I intentionally remove or skip any mandatory* field
