### ISSUE TITLE
No symbol "≈" which marked 'best' media if I send app output in file

### ISSUE THREAD

**Issue by xiaose** [yt-dlp/yt-dlp#7794]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

If I just run yt-dlp from cmd (exactly from powershell) than everything fine:

```
PS C:\bin> .\yt-dlp.exe vDHtypVwbHQ --print formats_table
...
269 mp4   256x124     24    │ ~101.76KiB  163k m3u8  │ avc1.4D400C    163k video only          IOS
...
18  mp4   640x312     24  2 │ ≈366.16KiB  586k https │ avc1.42001E         mp4a.40.2       44k 360p, ANDR
...
22  mp4   1280x622    24  2 │ ≈935.95KiB 1498k https │ avc1.64001F         mp4a.40.2       44k 720p, ANDR
...
```

but '≈' symbol disappears if I send app output in file:

```
PS C:\bin> .\yt-dlp.exe vDHtypVwbHQ -vU --print formats_table > .\output.txt
...
269 mp4   256x124     24    | ~101.76KiB  163k m3u8  | avc1.4D400C    163k video only          IOS
...
18  mp4   640x312     24  2 | 366.16KiB  586k https | avc1.42001E         mp4a.40.2       44k 360p, ANDR
...
22  mp4   1280x622    24  2 | 935.95KiB 1498k https | avc1.64001F         mp4a.40.2       44k 720p, ANDR
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\bin> .\yt-dlp.exe vDHtypVwbHQ -vU --print formats_table > .\output.txt
[debug] Command-line config: ['vDHtypVwbHQ', '-vU', '--print', 'formats_table']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_x86_exe)
[debug] Python 3.7.9 (CPython AMD64 32bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 7ce646283f2c437e2dc28e3008c892702824b6174f381d82b8e68c5bdb6be3b2
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: vDHtypVwbHQ
[youtube] vDHtypVwbHQ: Downloading webpage
[youtube] vDHtypVwbHQ: Downloading ios player API JSON
[youtube] vDHtypVwbHQ: Downloading android player API JSON
[youtube] vDHtypVwbHQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] vDHtypVwbHQ: Downloading 1 format(s): 247+251

PS C:\bin> cat .\output.txt
ID  EXT   RESOLUTION FPS CH |   FILESIZE   TBR PROTO | VCODEC          VBR ACODEC      ABR ASR MORE INFO
----------------------------------------------------------------------------------------------------------------------
sb0 mhtml 48x27       20    |                  mhtml | images                                  storyboard
233 mp4   audio only        |                  m3u8  | audio only          unknown             Default, IOS
234 mp4   audio only        |                  m3u8  | audio only          unknown             Default, IOS
139 m4a   audio only      2 |   31.41KiB   50k https | audio only          mp4a.40.5   50k 22k low, IOS, m4a_dash
249 webm  audio only      2 |   29.92KiB   49k https | audio only          opus        49k 48k low, ANDR, webm_dash
250 webm  audio only      2 |   39.36KiB   64k https | audio only          opus        64k 48k low, ANDR, webm_dash
140 m4a   audio only      2 |   80.71KiB  131k https | audio only          mp4a.40.2  131k 44k medium, IOS, m4a_dash
251 webm  audio only      2 |   78.22KiB  127k https | audio only          opus       127k 48k medium, ANDR, webm_dash
17  3gp   176x144     12  1 |   42.99KiB   69k https | mp4v.20.3           mp4a.40.2       22k 144p, ANDR
394 mp4   256x124     24    |   37.88KiB   63k https | av01.0.00M.08   63k video only          144p, ANDR, mp4_dash
269 mp4   256x124     24    | ~101.76KiB  163k m3u8  | avc1.4D400C    163k video only          IOS
160 mp4   256x124     24    |   63.70KiB  105k https | avc1.4D400C    105k video only          144p, IOS, mp4_dash
603 mp4   256x124     24    | ~ 95.38KiB  153k m3u8  | vp09.00.11.08  153k video only          IOS
278 webm  256x124     24    |   57.81KiB   95k https | vp09.00.11.08   95k video only          144p, IOS, webm_dash
395 mp4   426x208     24    |   85.67KiB  141k https | av01.0.00M.08  141k video only          240p, ANDR, mp4_dash
229 mp4   426x208     24    | ~170.65KiB  273k m3u8  | avc1.4D400D    273k video only          IOS
133 mp4   426x208     24    |  127.31KiB  210k https | avc1.4D400D    210k video only          240p, IOS, mp4_dash
604 mp4   426x208     24    | ~176.46KiB  282k m3u8  | vp09.00.20.08  282k video only          IOS
242 webm  426x208     24    |  132.67KiB  219k https | vp09.00.20.08  219k video only          240p, IOS, webm_dash
396 mp4   640x312     24    |  170.70KiB  282k https | av01.0.01M.08  282k video only          360p, ANDR, mp4_dash
230 mp4   640x312     24    | ~383.33KiB  613k m3u8  | avc1.4D4016    613k video only          IOS
134 mp4   640x312     24    |  274.76KiB  454k https | avc1.4D4016    454k video only          360p, IOS, mp4_dash
18  mp4   640x312     24  2 | 366.16KiB  586k https | avc1.42001E         mp4a.40.2       44k 360p, ANDR
605 mp4   640x312     24    | ~354.21KiB  567k m3u8  | vp09.00.21.08  567k video only          IOS
243 webm  640x312     24    |  247.87KiB  409k https | vp09.00.21.08  409k video only          360p, IOS, webm_dash
397 mp4   854x414     24    |  310.10KiB  512k https | av01.0.04M.08  512k video only          480p, ANDR, mp4_dash
231 mp4   854x414     24    | ~667.41KiB 1068k m3u8  | avc1.4D401E   1068k video only          IOS
135 mp4   854x414     24    |  537.01KiB  886k https | avc1.4D401E    886k video only          480p, IOS, mp4_dash
606 mp4   854x414     24    | ~585.74KiB  937k m3u8  | vp09.00.30.08  937k video only          IOS
244 webm  854x414     24    |  461.62KiB  762k https | vp09.00.30.08  762k video only          480p, IOS, webm_dash
22  mp4   1280x622    24  2 | 935.95KiB 1498k https | avc1.64001F         mp4a.40.2       44k 720p, ANDR
398 mp4   1280x622    24    |  575.14KiB  949k https | av01.0.05M.08  949k video only          720p, ANDR, mp4_dash
232 mp4   1280x622    24    | ~981.57KiB 1571k m3u8  | avc1.4D401F   1571k video only          IOS
136 mp4   1280x622    24    |  827.03KiB 1365k https | avc1.4D401F   1365k video only          720p, IOS, mp4_dash
609 mp4   1280x622    24    | ~  1.01MiB 1653k m3u8  | vp09.00.31.08 1653k video only          IOS
247 webm  1280x622    24    |  874.41KiB 1443k https | vp09.00.31.08 1443k video only          720p, IOS, webm_dash
```

**Comment by bashonly** [comment]
Seems to be an encoding issue with cp1252

```py
>>> '≈'.encode('cp1252')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/encodings/cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2248' in position 0: character maps to <undefined>
```

Does if work if you use `--print-to-file formats_table output.txt` instead?

**Comment by pukkandan** [comment]
The best we can do is convert it to `~` when encoding isn't supported

```diff
diff --git a/yt_dlp/YoutubeDL.py b/yt_dlp/YoutubeDL.py
index 666d89b46..565c800a6 100644
--- a/yt_dlp/YoutubeDL.py
+++ b/yt_dlp/YoutubeDL.py
@@ -3821,7 +3821,8 @@ def simplified_codec(f, field):
                 format_field(f, 'audio_channels', '\t%s'),
                 delim, (
                     format_field(f, 'filesize', ' \t%s', func=format_bytes)
-                    or format_field(f, 'filesize_approx', '≈\t%s', func=format_bytes)
+                    or format_field(f, 'filesize_approx', func=format_bytes,
+                                    template=self._format_out('≈\t%s', '', '~\t%s', test_encoding=True))
                     or format_field(try_call(lambda: format_bytes(int(info_dict['duration'] * f['tbr'] * (1024 / 8)))),
                                     None, self._format_out('~\t%s', self.Styles.SUPPRESS))),
                 format_field(f, 'tbr', '\t%dk', func=round),
```
