### ISSUE TITLE
TikTok: Add Support For Playlist Extraction

### ISSUE THREAD

**Issue by 54m4d** [yt-dlp/yt-dlp#7804]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Global / Not Relevant

### Example URLs

These are some of the URL formats i found. _(All of them point to the same playlist. short ones have query parameters.)_
```
https://www.tiktok.com/@linustech/playlist/Riley%20Tech%20Tips-7220878800733260549

https://www.tiktok.com/t/ZGJgTGTxr/
https://www.tiktok.com/t/ZGJgTcrof/

https://vm.tiktok.com/ZGJgTGTxr/
https://vm.tiktok.com/ZGJgTcrof/
```

### Provide a description that is worded well enough to be understood

This is a site feature request.

TikTok user playlists are currently not supported, providing a TikTok playlist URL to yt-dlp returns: `ERROR: Unsupported URL:`

Please let me know if anything is missing. Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@linustech/playlist/Riley%20Tech%20Tips-7220878800733260549']
[debug] User config "C:\Users\admin\AppData\Roaming\yt-dlp\config": ['--output', 'C:\\Users\\admin\\Desktop\\%(title)s [%(id)s].%(ext)s'
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.04.221808 [db7b054a6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-34-g3d5edb89e7-20230809 (setts), ffprobe n6.0-34-g3d5edb89e7-20230809, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1860 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.04.221808, Current version: nightly@2023.08.04.221808
Current Build Hash: c1578ba3139f74f3cf72bb5decc88c88deb52c51573047f32888f65547901a6a
yt-dlp is up to date (nightly@2023.08.04.221808)
[generic] Extracting URL: https://www.tiktok.com/@linustech/playlist/Riley%20Tech%20Tips-7220878800733260549
[generic] Riley Tech Tips-7220878800733260549: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Riley Tech Tips-7220878800733260549: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tiktok.com/@linustech/playlist/Riley%20Tech%20Tips-7220878800733260549
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1575, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1710, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@linustech/playlist/Riley%20Tech%20Tips-7220878800733260549
```

**Comment by Darumono** [comment]
Sometimes it works, sometimes it doesn't work.
