### ISSUE TITLE
i.reddi.it and reddit media urls do not work

### ISSUE THREAD

**Issue by derekantrican** [yt-dlp/yt-dlp#7807]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Reddit shortlinks don't work (example: https://i.redd.it/sjeasjn14q8b1.gif)

Current output:
> [generic] Extracting URL: https://i.redd.it/sjeasjn14q8b1.gif 
[generic] sjeasjn14q8b1: Downloading webpage 
[redirect] Following redirect to https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fsjeasjn14q8b1.gif&rdt=50914 
[generic] Extracting URL: https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fsjeasjn14q8b1.gif&rdt=50914 
[generic] media?url=https://i.redd.it/sjeasjn14q8b1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor 
[generic] media?url=https://i.redd.it/sjeasjn14q8b1: Extracting information 
ERROR: Unsupported URL: https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fsjeasjn14q8b1.gif&rdt=50914

I don't think this is an issue with escaping characters since I'm running inside of python

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://i.redd.it/sjeasjn14q8b1.gif']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip) 
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: none 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {} 
[debug] Loaded 1855 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Available version: stable@2023.07.06, Current version: stable@2023.07.06 
yt-dlp is up to date (stable@2023.07.06) 
[generic] Extracting URL: https://i.redd.it/sjeasjn14q8b1.gif 
[generic] sjeasjn14q8b1: Downloading webpage 
[redirect] Following redirect to https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fsjeasjn14q8b1.gif&rdt=62455 
[generic] Extracting URL: https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fsjeasjn14q8b1.gif&rdt=62455 
[generic] media?url=https://i.redd.it/sjeasjn14q8b1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor 
[generic] media?url=https://i.redd.it/sjeasjn14q8b1: Extracting information 
[debug] Looking for embeds 
ERROR: Unsupported URL: https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fsjeasjn14q8b1.gif&rdt=62455 
Traceback (most recent call last): 
  File "C:\Users\derek\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\derek\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\derek\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\derek\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fsjeasjn14q8b1.gif&rdt=62455
```

**Comment by bashonly** [comment]
I think these links may have been directly downloadable in the past via generic extractor, but reddit changed something and now the site redirects to a webpage if the request's `accept` header has `text/html` in first position. Related: 9a04113dfbb69b904e4e2bea736da293505786b8

Workaround: `--add-header "accept: */*"`

```shell
$ yt-dlp --ignore-config --add-header "accept: */*" "https://i.redd.it/sjeasjn14q8b1.gif"
[generic] Extracting URL: https://i.redd.it/sjeasjn14q8b1.gif
[generic] sjeasjn14q8b1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
WARNING: [generic] URL could be a direct video link, returning it as such.
[info] sjeasjn14q8b1: Downloading 1 format(s): 0
[download] Destination: sjeasjn14q8b1 [sjeasjn14q8b1].gif
[download] 100% of   60.95MiB in 00:00:01 at 51.20MiB/s
```

**Comment by derekantrican** [comment]
Thanks - can confirm that I see that working.

Since I'm using the API/python package version, what would be the proper format for this workaround? I was trying `'headers': {'Accept': '*/*'},` without success

**Comment by derekantrican** [comment]
Nvm - just found it. "http_headers" not "headers"

**Comment by DooMMasteR** [comment]
they seem to become more and more common now, my bot hit's issues more and more often now.  
`ERROR - ERROR: Unsupported URL: https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fj7ydqfg5f0pd1.gif&rdt=46462`
