### ISSUE TITLE
Postprocessing: Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred

### ISSUE THREAD

**Issue by ThatGuy12-66** [yt-dlp/yt-dlp#7810]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When attempting to download a video from any site, I get this error: 
Postprocessing: Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred

I'm not too sure what to do as I've updated both ffmpeg (6.0) and yt-dlp (stable@2023.07.06) to the latest version today.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'brave', '-vU', 'https://www.youtube.com/watch?v=oh6lUbNktxU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-55702-g920046a (needs_adtstoasc), ffprobe N-55702-g920046a
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "C:\Users\The Tronren Guy\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\The Tronren Guy\AppData\Local\BraveSoftware\Brave-Browser\User Data\Local State"
[Cookies] Extracted 58 cookies from brave
[debug] cookie version breakdown: {'v10': 58, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=oh6lUbNktxU
[youtube] oh6lUbNktxU: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[debug] [youtube] Copying __Secure-3PAPISID cookie to SAPISID cookie
[youtube] oh6lUbNktxU: Downloading ios player API JSON
[youtube] oh6lUbNktxU: Downloading android player API JSON
[debug] Loading youtube-nsig.4eae42b1 from cache
[debug] [youtube] Decrypted nsig j49kWt2JFJbQxoRDy => gZY8smIOdDpppw
[youtube] oh6lUbNktxU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] oh6lUbNktxU: Downloading 1 format(s): 308+251
[debug] Invoking http downloader on "https://rr8---sn-8pgbpohxqp5-aigk.googlevideo.com/videoplayback?expire=1691768147&ei=8wDWZJntKoedWo2kvJAN&ip=81.106.201.155&id=o-AGofb5zCmMNdDxVg31PyDkBlFXnMLMQHrmaiMjdHL3Lt&itag=308&source=youtube&requiressl=yes&mh=0e&mm=31%2C29&mn=sn-8pgbpohxqp5-aigk%2Csn-aigl6n6s&ms=au%2Crdu&mv=m&mvi=8&pcm2cms=yes&pl=23&initcwndbps=2968750&siu=1&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=119696612&dur=500.766&lmt=1649937704880202&mt=1691746157&fvip=3&keepalive=yes&fexp=24007246%2C24363391&beids=24350017&c=IOS&txp=6319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgWOTNBIhHOL4SOcpTMIxfVwNdvL194ssGCoDGye-jlSACIQCg-cBzMjxkVMeOyWMFA-2uVj9tfou6TKL8ocPN79wCTA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTM0f0MUn4GMTOsDYMX5yXJ-YwBXkyfVB1MdigjHUFX8CIHUtf_pYj-Sv3NsZA6BAket9SrAbcMY5pV5SXm9H8wq2"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Using Glitches and Tricks to Beat Discord [oh6lUbNktxU].f308.webm
[download] 100% of  114.15MiB in 00:00:04 at 24.21MiB/s
[debug] Invoking http downloader on "https://rr8---sn-8pgbpohxqp5-aigk.googlevideo.com/videoplayback?expire=1691768147&ei=8wDWZNjIN4riWYTCiBg&ip=81.106.201.155&id=o-AIV3GPunWUJLM06YTlwajFTdLf0gvSAUCxR5wuSvqE5m&itag=251&source=youtube&requiressl=yes&mh=0e&mm=31%2C29&mn=sn-8pgbpohxqp5-aigk%2Csn-aigzrn7d&ms=au%2Crdu&mv=m&mvi=8&pl=23&initcwndbps=2968750&siu=1&spc=UWF9f-E5FiNpGXTN3oMWR800FQcmAUzGPP1yuJG_Ux8y&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=6729135&dur=500.801&lmt=1649937551357933&mt=1691746157&fvip=4&keepalive=yes&fexp=24007246%2C24363391&beids=24350017&c=ANDROID&txp=6318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgDAtgseEbLN6tJ5plNzhGfCaKymxKliWpxNO4zhc49TMCIEPgWCPnqTafvoXFAtvx-bKBGbuZ2cdfwQxM8vePsuVq&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKY_2IXAZDwsVMIBJ-u_7-FsvupkoiIUHnoRShtY5N9_AiAaAD5oHZLGso1SjW1nm2B52XJDQ9XADLulR8v0S7BKxw%3D%3D"
[download] Destination: Using Glitches and Tricks to Beat Discord [oh6lUbNktxU].f251.webm
[download] 100% of    6.42MiB in 00:00:00 at 22.95MiB/s
[Merger] Merging formats into "Using Glitches and Tricks to Beat Discord [oh6lUbNktxU].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Using Glitches and Tricks to Beat Discord [oh6lUbNktxU].f308.webm" -i "file:Using Glitches and Tricks to Beat Discord [oh6lUbNktxU].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Using Glitches and Tricks to Beat Discord [oh6lUbNktxU].temp.webm"
[debug] ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 42.100 / 52. 42.100
  libavcodec     55. 29.100 / 55. 29.100
  libavformat    55. 14.101 / 55. 14.101
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 82.100 /  3. 82.100
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
[matroska,webm @ 0000000000f39540] Unknown entry 0x55B0
Input #0, matroska,webm, from 'file:Using Glitches and Tricks to Beat Discord [oh6lUbNktxU].f308.webm':
  Duration: 00:08:20.77, start: 0.000000, bitrate: 1912 kb/s
    Stream #0:0(eng): Video: vp9, 2560x1440, SAR 1:1 DAR 16:9, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc (default)
[matroska,webm @ 0000000000f374a0] Unknown entry 0x56AA
[matroska,webm @ 0000000000f374a0] Unknown entry 0x56BB
Input #1, matroska,webm, from 'file:Using Glitches and Tricks to Beat Discord [oh6lUbNktxU].f251.webm':
  Duration: 00:08:20.80, start: 0.000000, bitrate: 107 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, s16 (default)
[webm @ 00000000026e6240] Only VP8,VP9 video and Vorbis,Opus(experimental, use -strict -2) audio and WebVTT subtitles are supported for WebM.
Output #0, webm, to 'file:Using Glitches and Tricks to Beat Discord [oh6lUbNktxU].temp.webm':
  Metadata:
    encoder         : Lavf55.14.101
    Stream #0:0(eng): Video: vp9, 2560x1440 [SAR 1:1 DAR 16:9], q=2-31, 59.94 fps, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred

ERROR: Postprocessing: Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3439, in process_info
  File "yt_dlp\YoutubeDL.py", line 3621, in post_process
  File "yt_dlp\YoutubeDL.py", line 3603, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3581, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 837, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 329, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 367, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred
```

**Comment by bashonly** [comment]
> [debug] ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers

The version of ffmpeg you are using is 10 years old. It needs to be upgraded.
You can use one of the [yt-dlp custom ffmpeg builds](https://github.com/yt-dlp/FFmpeg-Builds,), like https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-n6.0-latest-win64-gpl-6.0.zip

Make sure to place `ffmpeg.exe` and `ffprobe.exe` either in your system's `PATH` or in the same folder as `yt-dlp.exe`

**Comment by THEGOLDENPRO** [comment]
@bashonly I tried what you reccomended, updated ffmpeg to the latest version and I even tried yt-dlp's custom ffmpeg builds but I'm still getting the same error.

@ThatGuy12-66 Did you find a way around this?

**Comment by bashonly** [comment]
@THEGOLDENPRO show verbose log please

**Comment by THEGOLDENPRO** [comment]
> @THEGOLDENPRO show verbose log please

The result is a `.webm` file that doesn't seem to play (via VLC). yt-dlp used to work perfectly fine before.

```
C:\Users\jassi\Downloads>yt-dlp https://youtu.be/xvFZjo5PgG0 --verbose

[debug] Command-line config: ['https://youtu.be/xvFZjo5PgG0', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-55702-g920046a (needs_adtstoasc), ffprobe N-55702-g920046a
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.05.30, mutagen-1.45.1, sqlite3-3.35.5, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[youtube] Extracting URL: https://youtu.be/xvFZjo5PgG0
[youtube] xvFZjo5PgG0: Downloading webpage
[youtube] xvFZjo5PgG0: Downloading ios player API JSON
[youtube] xvFZjo5PgG0: Downloading android player API JSON
[youtube] xvFZjo5PgG0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] xvFZjo5PgG0: Downloading 1 format(s): 243+251
[debug] Invoking http downloader on "https://rr3---sn-cu-cime7.googlevideo.com/videoplayback?expire=1698621675&ei=ipQ-ZcWsOqasmLAPg_KeuAM&ip=2.28.227.7&id=o-ACAdri4hPz5j6WpKvlm2rZg5kMLkGWIZ9_paUNIAyKRL&itag=243&source=youtube&requiressl=yes&mh=bl&mm=31%2C29&mn=sn-cu-cime7%2Csn-cu-c9i6&ms=au%2Crdu&mv=m&mvi=3&pl=25&initcwndbps=2003750&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=195311&dur=7.600&lmt=1682924428628954&mt=1698599601&fvip=5&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=453E434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRAIgfNjF1AdrhLIG63mKjagXJxNF1sCRF0BO2OuyPzpVA5oCIGjYGKqZoajT4ucBb1RbZWKchtmxnveXYMx4vBuwiGZF&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgE_NPsrUqrgzY_vTcYwL5YCm6ar-Q07EWP2cQYd5g6jACIAq9a09b-6Ft2BIPMRBLAWcufNTteBHFnQD4Z7LCswkZ"
[download] Rick Roll (Different link + no ads) [xvFZjo5PgG0].f243.webm has already been downloaded
[download] 100% of  190.73KiB
[debug] Invoking http downloader on "https://rr3---sn-cu-cime7.googlevideo.com/videoplayback?expire=1698621675&ei=i5Q-Zc3uBZyomLAPwOONwAc&ip=2.28.227.7&id=o-ABaCeB_ZXZF_pZf5suODhYHnz8NPfOjWWE1lfSr9itjc&itag=251&source=youtube&requiressl=yes&mh=bl&mm=31%2C29&mn=sn-cu-cime7%2Csn-cu-c9i6&ms=au%2Crdu&mv=m&mvi=3&pl=25&initcwndbps=2003750&spc=UWF9f6FXi4yZvxu1UddCyy2tTyyhNg4&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=125792&dur=7.641&lmt=1682924360402975&mt=1698599601&fvip=5&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIgCpsa1oJEJ67-nJAWBbyZgNi1Y6jWypQn1XZh7RPLve0CIQDL7_SBcqqqjyDFL4K22h9nhNwVwkQuQhiHJccaUyT2Mg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRQIhALDyB3JkmQFt3cyX6fcXGyUsAVG1KInJPMcXqek2zjhrAiANcmWI2nNY760-D_WZWcq3Ig_ZJPCHc1noFyV4FlZTNA%3D%3D"
[download] Rick Roll (Different link + no ads) [xvFZjo5PgG0].f251.webm has already been downloaded
[download] 100% of  122.84KiB
[Merger] Merging formats into "Rick Roll (Different link + no ads) [xvFZjo5PgG0].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Rick Roll (Different link + no ads) [xvFZjo5PgG0].f243.webm" -i "file:Rick Roll (Different link + no ads) [xvFZjo5PgG0].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Rick Roll (Different link + no ads) [xvFZjo5PgG0].temp.webm"
[debug] ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 42.100 / 52. 42.100
  libavcodec     55. 29.100 / 55. 29.100
  libavformat    55. 14.101 / 55. 14.101
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 82.100 /  3. 82.100
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
[matroska,webm @ 00000000027108a0] Unknown entry 0x55B0
Input #0, matroska,webm, from 'file:Rick Roll (Different link + no ads) [xvFZjo5PgG0].f243.webm':
  Duration: 00:00:07.60, start: 0.000000, bitrate: 205 kb/s
    Stream #0:0(eng): Video: vp9, 640x360, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
[matroska,webm @ 0000000000d89040] Unknown entry 0x56AA
[matroska,webm @ 0000000000d89040] Unknown entry 0x56BB
Input #1, matroska,webm, from 'file:Rick Roll (Different link + no ads) [xvFZjo5PgG0].f251.webm':
  Duration: 00:00:07.64, start: 0.000000, bitrate: 131 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, s16 (default)
[webm @ 0000000002728aa0] Only VP8,VP9 video and Vorbis,Opus(experimental, use -strict -2) audio and WebVTT subtitles are supported for WebM.
Output #0, webm, to 'file:Rick Roll (Different link + no ads) [xvFZjo5PgG0].temp.webm':
  Metadata:
    encoder         : Lavf55.14.101
    Stream #0:0(eng): Video: vp9, 640x360 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred

ERROR: Postprocessing: Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred
Traceback (most recent call last):
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 3464, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 3644, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 3626, in run_all_pps
    info = self.run_pp(pp, info)
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 3604, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\postprocessor\common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\postprocessor\common.py", line 128, in wrapper
    return func(self, info)
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 837, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 329, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 367, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred
```

**Comment by THEGOLDENPRO** [comment]
I've also tried one other video, but no luck there. I'll try more later.

**Comment by seproDev** [comment]
@THEGOLDENPRO 
> [debug] ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers

You are using the same ancient ffmpeg version. Make sure you actually update ffmpeg.

**Comment by THEGOLDENPRO** [comment]
alright thanks for highlighting that I'll look more into it and let you know when it's fixed

**Comment by THEGOLDENPRO** [comment]
okay it's working now.

The problem was that ffmpeg from my python installations were taking priority over my real ffmpeg installation.
![image](https://github.com/yt-dlp/yt-dlp/assets/66202304/e9727a64-e9fc-4ce6-9e54-c67edb42bb69)

All is good now, thanks 👍

**Comment by BareGamer** [comment]
> okay it's working now.
> 
> The problem was that ffmpeg from my python installations were taking priority over my real ffmpeg installation. ![image](https://github.com/yt-dlp/yt-dlp/assets/66202304/e9727a64-e9fc-4ce6-9e54-c67edb42bb69)
> 
> All is good now, thanks 👍

Hey, sorry for necroposting, but how did you resolve this issue? I have the exact same problem and no idea how to fix it.
