### ISSUE TITLE
Please support Xigua Video

### ISSUE THREAD

**Issue by wutongskype** [yt-dlp/yt-dlp#7821]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

china

### Example URLs

https://www.ixigua.com/home/109420591813
this is Unsupported dont work, 
This is the connection of all videos under the video publisher channel, and the following number is the ID of the video publisher

https://www.ixigua.com/7265819416108106295
This is a separate video link
This seems to work, but the prompt requires cookies

### Provide a description that is worded well enough to be understood

ERROR: Unsupported URL: https://www.ixigua.com/home/109420591813
![image](https://github.com/yt-dlp/yt-dlp/assets/40192806/3899a649-b90f-4da0-99bd-21d7a44c4721)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--merge-output-format', 'mp4', '--no-check-certificate', '-i', '-a', '#01_当前目录list.txt', '-o', 'E:\\01.userData\\ZhuoMian\\YTDLP\\\\#01_当前目录list\\[%(channel)s][%(channel_id)s]\\[%(playlist)s][%(playlist_id)s]\\[%(upload_date)s][%(uploader)s][%(resolution)s][%(title)s][%(id)s].%(ext)s', '-f', '((best[height=2160]/best[height=1440]/best[height=1080]),(best[height>=1080]),(best[height<=1080]))', '-vU']
[debug] Batch file urls: ['https://www.ixigua.com/home/109420591813']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': '192.168.1.29:10801', 'https': '192.168.1.29:10801'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://www.ixigua.com/home/109420591813
[generic] 109420591813: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 109420591813: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.ixigua.com/home/109420591813
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1688, in __extract_info
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.ixigua.com/home/109420591813
```

**Comment by wutongskype** [comment]
unable to download~~~

设置代理服务器为
#01_当前目录list运行中
[debug] Command-line config: ['-a', '#01_当前目录list.txt', '--cookies', '#01_当前目录list-cookies.txt', '-F', '-vU']
[debug] Batch file urls: ['https://www.ixigua.com/7223150388223050297?logTag=aa79d6b2300eaddc84af']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': '192.168.1.29:10801', 'https': '192.168.1.29:10801'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[Ixigua] Extracting URL: https://www.ixigua.com/7223150388223050297?logTag=aa79d6b2300eaddc84af
[Ixigua] 7223150388223050297: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 7223150388223050297:
ID EXT RESOLUTION FPS │  FILESIZE PROTO │ VCODEC ACODEC
────────────────────────────────────────────────────────
40 mp4 640x360     30 │   4.88MiB https │ h264   unknown
30 mp4 854x480     30 │   6.16MiB https │ h264   unknown
10 mp4 1280x720    30 │  11.76MiB https │ h264   unknown
1  mp4 1920x1080   30 │  21.74MiB https │ h264   unknown
请按任意键继续. . .
#01_当前目录list运行中
[debug] Command-line config: ['-a', '#01_当前目录list.txt', '--merge-output-format', 'mp4', '--no-check-certificate', '-i', '-o', 'E:\\01.userData\\ZhuoMian\\YTDLP\\\\#01_当前目录list\\[%(upload_date)s][%(uploader)s][%(title)s][%(resolution)s][%(id)s].%(ext)s', '--windows-filenames', '--trim-filenames', '250', '--cookies', '#01_当前目录list-cookies.txt', '-vU']
[debug] Batch file urls: ['https://www.ixigua.com/7223150388223050297?logTag=aa79d6b2300eaddc84af']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': '192.168.1.29:10801', 'https': '192.168.1.29:10801'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[Ixigua] Extracting URL: https://www.ixigua.com/7223150388223050297?logTag=aa79d6b2300eaddc84af
[Ixigua] 7223150388223050297: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7223150388223050297: Downloading 1 format(s): 1
[debug] Invoking http downloader on "https://v9-xg-web-pc.ixigua.com/97c0e160d82b3d388ac9b656f622d6f1/64d9ceb4/video/tos/cn/tos-cn-ve-4/okIv9ymAaAuV9QIqHKEAIfhAQyz0GHQSCtY8Wh/?a=1768&ch=0&cr=0&dr=0&er=0&cd=0%7C0%7C0%7C0&cv=1&br=1053&bt=1053&cs=0&ds=4&ft=_z7ehvvBQy~UIryo8Z.wNnOYZlcMn4RW2bLd~y.RuZmka&mime_type=video_mp4&qs=0&rc=NzxpNTM7ZWY5aTY5aWllNEBpMzlkZDo6Znh2ajMzNDczM0BjMjRhMjEuXzYxLzQyX14xYSNgYGUucjRfZHJgLS1kLS9zcw%3D%3D&l=20230814134739F88454B8E7DBBD4AEA8F&btag=e00028000&dy_q=1691992059"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3363, in process_info
  File "yt_dlp\YoutubeDL.py", line 3084, in dl
  File "yt_dlp\downloader\common.py", line 461, in download
  File "yt_dlp\downloader\http.py", line 377, in real_download
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3863, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
