### ISSUE TITLE
Fameplay.tv

### ISSUE THREAD

**Issue by jirih** [yt-dlp/yt-dlp#7826]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

world

### Example URLs

Single video: https://mall.fameplay.tv/zivoty-slavnych/sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini
Playlist: https://mall.fameplay.tv/zivoty-slavnych

### Provide a description that is worded well enough to be understood

The MallTV has been renamed this spring. I do not know if also the web is basically the same. If it is, only a url pattern update will be needed.

Generic extractor gets trapped into an infinite loop (or at least so long that Python crashes).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://mall.fameplay.tv/zivoty-slavnych/sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini']
[debug] User config "/home/pi/.config/yt-dlp/config": ['--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', '--no-check-certificate', '-o', '~/Downloads/yt-dlp/%(autonumber)03d_%(title)s.%(ext)s', '--no-mtime', '--format', 'bestvideo[ext=mp4][height<=1080][fps<=30]+bestaudio[ext=m4a]/best[ext=mp4][height<=1080][fps<=30]/best[height<=1080][fps<=30]/best', '--merge-output-format', 'mkv', '--remux-video', 'mkv', '--ffmpeg-location', '/usr/bin/ffmpeg', '--all-subs', '--compat-options', 'no-live-chat', '--live-from-start', '-i']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Compatibility options: no-live-chat
[debug] Python 3.7.3 (CPython armv7l 32bit) - Linux-5.15.87-v7l+-armv7l-with-debian-10.13 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.28)
[debug] exe versions: ffmpeg 4.1.11-0, ffprobe 4.1.11-0, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.0, xattr-0.10.1
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://mall.fameplay.tv/zivoty-slavnych/sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini
[generic] sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[generic] Extracting URL: https://mall.fameplay.tv/sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini%22%2C+%22to_generic%22%3A+true%2C+%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fmall.fameplay.tv%2Fzivoty-slavnych%2Fsigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini%22%7D%7D
[generic] sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini: Downloading webpage
[redirect] Following redirect to https://mall.fameplay.tv/zivoty-slavnych/sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini
[generic] Extracting URL: https://mall.fameplay.tv/zivoty-slavnych/sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini%22%7D
[generic] sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[generic] Extracting URL: https://mall.fameplay.tv/sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini%22%2C+%22to_generic%22%3A+true%2C+%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fmall.fameplay.tv%2Fzivoty-slavnych%2Fsigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini%22%7D%7D
[generic] sigmund-freud-za-vsim-hledej-sex-slavneho-moravskeho-rodaka-obdivoval-i-mussolini: Downloading webpage
^C
ERROR: Interrupted by user
```

**Comment by jirih** [comment]
This could make the trick:

```
diff --git a/yt_dlp/extractor/malltv.py b/yt_dlp/extractor/malltv.py
index e1031d8da..ea5ee0c8e 100644
--- a/yt_dlp/extractor/malltv.py
+++ b/yt_dlp/extractor/malltv.py
@@ -11,7 +11,7 @@
 
 
 class MallTVIE(InfoExtractor):
-    _VALID_URL = r'https?://(?:(?:www|sk)\.)?mall\.tv/(?:[^/]+/)*(?P<id>[^/?#&]+)'
+    _VALID_URL = r'https?://(?:(?:www|sk)\.)?mall\.(?:fameplay\.)?tv/(?:[^/]+/)*(?P<id>[^/?#&]+)'
     _TESTS = [{
         'url': 'https://www.mall.tv/18-miliard-pro-neziskovky-opravdu-jsou-sportovci-nebo-clovek-v-tisni-pijavice',
         'md5': 'cd69ce29176f6533b65bff69ed9a5f2a',
@@ -68,7 +68,7 @@ def _real_extract(self, url):
             webpage, 'video object'), display_id)
 
         video_id = self._search_regex(
-            r'<input\s*id\s*=\s*player-id-name\s*[^>]+value\s*=\s*(\w+)', webpage, 'video id')
+            r'<input\s*id\s*=\s*"player-id-name"\s*[^>]+value\s*="\s*(\w+)"', webpage, 'video id')
 
         formats = self._extract_m3u8_formats(
             video['VideoSource'], video_id, 'mp4', 'm3u8_native')
```

**Comment by michaljanocko** [comment]
The site has changed a lot and neither the extractor nor the patch work. :(

**Comment by bashonly** [comment]
@michaljanocko Can you post a new example URL and log please?

**Comment by michaljanocko** [comment]
Yes, the new URLs are the same except that `mall.tv` has now been renamed to `fameplay.tv`. The rest of the URL is the same; in fact, `mall.fameplay.tv` and `mall.tv` just have a simple redirect set up.

This is the output on the unpatched version:
```
[debug] Command-line config: ['https://fameplay.tv/domu-do-brna-zahadna-vestba-a-nejvetsi-prekvapeni-na-ceste', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.7.6-arch1-1-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.02.02, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[generic] Extracting URL: https://fameplay.tv/domu-do-brna-zahadna-vestba-a-nejvetsi-prekvapeni-na-ceste
[generic] domu-do-brna-zahadna-vestba-a-nejvetsi-prekvapeni-na-ceste: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] domu-do-brna-zahadna-vestba-a-nejvetsi-prekvapeni-na-ceste: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://fameplay.tv/domu-do-brna-zahadna-vestba-a-nejvetsi-prekvapeni-na-ceste
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1722, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2531, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://fameplay.tv/domu-do-brna-zahadna-vestba-a-nejvetsi-prekvapeni-na-ceste
```

And after trying to trick `yt-dlp` into using the extractor on this site by tweaking `yt_dlp/extractor/malltv.py` like this:
```diff
-    _VALID_URL = r'https?://(?:(?:www|sk)\.)?mall\.tv/(?:[^/]+/)*(?P<id>[^/?#&]+)'
+    _VALID_URL = r'https?://(?:www\.)fameplay.tv/(?:[^/]+/)*(?P<id>[^/?#&]+)'
```
(the 3rd level `sk.` domain for the Slovak market has seemingly been dropped)

I am now getting this output:
```
[debug] Command-line config: ['https://fameplay.tv/domu-do-brna-zahadna-vestba-a-nejvetsi-prekvapeni-na-ceste', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.7.6-arch1-1-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.02.02, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[MallTV] Extracting URL: https://fameplay.tv/domu-do-brna-zahadna-vestba-a-nejvetsi-prekvapeni-na-ceste
ERROR: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1722, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/malltv.py", line 61, in _real_extract
    display_id = self._match_id(url)
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 591, in _match_id
    return cls._match_valid_url(url).group('id')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

The thing is that the site has been rebuilt with Vue.js and Nuxt and most of the data is now coming from an API. That's as far as I got today. I'll look at this tomorrow in more depth and maybe cobble something together. This is my first looking into `yt-dlp` source code so I can't promise anything right now but I hope to scratch my own itch.

**Comment by bashonly** [comment]
Converting this to a `site-request` issue since `MallTVIE` was removed in df773c3d5d1cc1f877cf8582f0072e386fc49318 -- the site's video IDs have changed and almost all of the old code was no longer pertinent.

Whoever works on adding support should also consider #6436, which will still be relevant to the new extractor's m3u8 manifests.
