### ISSUE TITLE
SUPREME COURT AUDIO -- www.oyez.org

### ISSUE THREAD

**Issue by TrumanHW** [yt-dlp/yt-dlp#7829]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

ALL

### Example URLs

General Domain:  https://www.oyez.org

Example-link with audio:  https://www.oyez.org/cases/2018/17-9560

### Provide a description that is worded well enough to be understood

Website appears to be an audio player but may be audio-video as I'm uncertain how they're showing which justice is speaking, but during audio playback it indicates which judge is speaking by highlighting that judge's face in the image (if not video).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.oyez.org/cases/2018/17-9560']
[debug] User config "/Users/truman/.config/yt-dlp/config": ['${XDG_CONFIG_HOME}/yt-dlp/config/', '--default-search', 'ytsearch', '-N', '10', '-f', 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b', '-o', '~/YT-DLP_DLs/%(title)s.%(id)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.3.1-arm64-arm-64bit (OpenSSL 3.1.2 1 Aug 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: ${XDG_CONFIG_HOME}/yt-dlp/config/
[youtube:search] Extracting URL: ytsearch:${XDG_CONFIG_HOME}/yt-dlp/config/
[download] Downloading playlist: ${XDG_CONFIG_HOME}/yt-dlp/config/
[youtube:search] query "${XDG_CONFIG_HOME}/yt-dlp/config/": Downloading web client config
[youtube:search] query "${XDG_CONFIG_HOME}/yt-dlp/config/" page 1: Downloading API JSON
[youtube:search] Playlist ${XDG_CONFIG_HOME}/yt-dlp/config/: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=MW7oIHvPpdc
[youtube] MW7oIHvPpdc: Downloading webpage
[youtube] MW7oIHvPpdc: Downloading ios player API JSON
[youtube] MW7oIHvPpdc: Downloading android player API JSON
[debug] Loading youtube-nsig.3cd2d050 from cache
[debug] [youtube] Decrypted nsig YquJKm6ye_XBN0S6B6R => FqFpaayhfn4RJA
[youtube] MW7oIHvPpdc: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] MW7oIHvPpdc: Downloading 1 format(s): 137+140
[download] /Users/truman/YT-DLP_DLs/YT-DLP format selection.MW7oIHvPpdc.mp4 has already been downloaded
[download] Finished downloading playlist: ${XDG_CONFIG_HOME}/yt-dlp/config/
[generic] Extracting URL: https://www.oyez.org/cases/2018/17-9560
[generic] 17-9560: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 17-9560: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.oyez.org/cases/2018/17-9560
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.oyez.org/cases/2018/17-9560
```

**Comment by dineshUmasankar** [comment]
It appears that the site has uploaded the audio argument and opinion statements to its respective Amazon S3 Bucket and just retrieves them in order to play via a simple audio player. 

Here are the direct links to the

- [Argument Delivery](https://s3.amazonaws.com/oyez.case-media.mp3/case_data/2018/17-9560/17-9560_20190423-argument.delivery.mp3)
- [Opinion Statement](https://s3.amazonaws.com/oyez.case-media.mp3/case_data/2018/17-9560/17-9560_20190621-opinion.delivery.mp3)

I had retrieved this by digging through the network tab in order to see what data was being passed through.

The paragraphs seem to have time-stamps linked within each section causing the appropriate timeskip, and from what I can presume. Furthermore, I believe the judge is highlighted based off the `[Name]` before each paragraph causing a state update to highlight a judge's image. As such, unfortunately, it's not a video player, and a lot of the "subtitle" data seems to be encoded within the website's DOM. However, my initial investigation could be wrong. Hope this helps~!
