### ISSUE TITLE
UpRide.cc support

### ISSUE THREAD

**Issue by NothingSpecific** [yt-dlp/yt-dlp#7858]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

- Single video: https://upride.cc/incident/shoulder-pass-at-light/
- Single video: https://upride.cc/incident/almost-hit-by-a-car-pulling-out-of-a-gas-station/
- Single video: https://upride.cc/incident/dog-2/
- Single video: https://upride.cc/incident/road-rager-says-too-much/

### Provide a description that is worded well enough to be understood

UpRide.cc is a site for cyclists to upload video evidence of incidents.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://upride.cc/incident/shoulder-pass-at-light/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (debian*)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-6.4.9-1-liquorix-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://upride.cc/incident/shoulder-pass-at-light/
[generic] shoulder-pass-at-light: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] shoulder-pass-at-light: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://upride.cc/incident/shoulder-pass-at-light/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://upride.cc/incident/shoulder-pass-at-light/
```

**Comment by garret1317** [comment]
embedded cloudflare stream player, metadata in the html
```html
<iframe
  src="[https://customer-xje7fu6unkwpaymh.cloudflarestream.com/eaef9dea5159cf968be84241b5cedfe7/iframe?startTime=0](view-source:https://customer-xje7fu6unkwpaymh.cloudflarestream.com/eaef9dea5159cf968be84241b5cedfe7/iframe?startTime=0)"
  style="border: none"
  height="720"
  width="1280"
  allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;"
  allowfullscreen="true"
  id="stream-player"
></iframe>
```
```html
<h3 class="incident-title"><img decoding="async" src="[data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%200%200'%3E%3C/svg%3E](view-source:data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%200%200'%3E%3C/svg%3E)" id="incident_type-close-call" data-type="close-call" class="marker-icon" data-lazy-src="https://upride.cc/wp-content/plugins/cycliq-upride/images/marker-red-192x192.png" /><noscript><img decoding="async" src="https://upride.cc/wp-content/plugins/cycliq-upride/images/marker-red-192x192.png" id="incident_type-close-call" data-type="close-call" class="marker-icon" /></noscript>Shoulder Pass at Light</h3><p class="incident-summary clear"><a id="incident-details-toggle" href="[#](view-source:https://upride.cc/incident/shoulder-pass-at-light/#)">1290 views. <attr title="06/07/2023 04:47PM">3 months ago</attr><span class="mobile-more-info">...more</span></a></p><div id="incident-details"><blockquote><p>Car riding on shoulder, comes up behind me at red light to make a right turn at frame 4:47 to 5:03.</p>
```
```html
</script><hr /><h4>Incident details</h4><dl><dt>Date of incident</dt><dd>06/07/2023 04:47PM</dd><dt>Incident type</dt><dd><a href="[/incidents/close-calls/](view-source:https://upride.cc/incidents/close-calls/)">Close call</a></dd><dt>Location of incident</dt><dd><a href="[/incidents/?country=US&street=Cane Island Parkway](view-source:https://upride.cc/incidents/?country=US&street=Cane%20Island%20Parkway)" target="_blank">Cane Island Parkway</a>, <a href="[/incidents/?country=US&place=Katy](view-source:https://upride.cc/incidents/?country=US&place=Katy)" target="_blank" title="View more incidents">Katy</a>, <a href="[/incidents/?country=US&region=TX](view-source:https://upride.cc/incidents/?country=US&region=TX)" target="_blank" title="View more incidents">Texas</a> <a href="[/incidents/?country=US&postcode=77494](view-source:https://upride.cc/incidents/?country=US&postcode=77494)" target="_blank" title="View more incidents in 77494, United States">77494</a>, <a href="[/incidents/?country=US](view-source:https://upride.cc/incidents/?country=US)" target="_blank" title="View more incidents in United States">United States</a></dd></dl><hr /></p></div><!-- #incident-details -->
```
probably just needs the embed regex in [extractor/cloudflarestream.py](https://github.com/yt-dlp/yt-dlp/blob/c54ddfba0f7d68034339426223d75373c5fc86df/yt_dlp/extractor/cloudflarestream.py) to work with iframes for generic extractor to be able to handle it
still need a site-specific one if you want the metadata though

**Comment by bashonly** [comment]
related #9171

**Comment by ilikenwf** [comment]
Please see my comment here: https://github.com/yt-dlp/yt-dlp/issues/9171#issuecomment-1962737551

If we see a cloudflare iframe like this, replacing the "customer-whatever" piece of the url with "watch" allows us to download the video successfully but it is currently a manual process.
