### ISSUE TITLE
Tumblr Live support

### ISSUE THREAD

**Issue by jorong1** [yt-dlp/yt-dlp#7862]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Tumblr live is available to US, United Kingdom, Canada, Germany, Brazil, Mexico, Turkey, Italy, Japan, South Korea, and Malaysia users, 18+.

### Example URLs

https://www.tumblr.com/live/3VyArDpO4D
https://www.tumblr.com/live/QC8M1C3UTm
https://www.tumblr.com/live/V3lkAL5hjt

Because these are livestreams they may not be active when testing, so please check https://tumblr.com/live once logged in with an appropriate account.

### Provide a description that is worded well enough to be understood

https://www.tumblr.com/live

Tumblr introduced a live streaming feature a while ago, and it's now available on web browser to view and stream to, instead of just being available on the Tumblr mobile app.

**A free 18+ Tumblr user account is required to access streams. After logging in, you have to agree to the Tumblr Live terms and conditions, through the mobile app or web interface, before you can access the live streams.**

Accessing a stream works as such:
- Login to your 18+ age tumblr.com account
- Agree to terms and service as mentioned above (once)
- Accessing https://www.tumblr.com/live brings you to an index of live streams, which are presented inside a browser frame.
- Clicking on a livestream will take you to URL https://www.tumblr-live.com/view/ID, which redirects within the same frame to https://www.tumblr.com/live/ID.
   - **It is important to note that it does not seem possible to open https://www.tumblr-live.com directly, it only accepts connections from https://www.tumblr.com, based on observation.**
- Your account token is passed to the meetme.com servers for authentication.
- Actual video stream is loaded through a websocket

Relevant URLs:
```
https://tumblr-live.com
https://api.gateway.tumblr-live.com
https://auth.gateway.tumblr-live.com/oauth/token
wss://tmg-stream.gateway.tumblr-live.com

agora.io
meetme.com
meetmecdna.com
```

The actual video stream, once loaded, seems to come from either one of these websocket addresses:
```
wss://xxx-xxx-xxx-xxx.edge.agora.io:port
wss://xxx-xxx-xxx-xxx.edge.sd-rtn.com:port
```

If needed a new account for testing can be provided, but only an email, such as disposable email, is required to signup.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.tumblr.com/live/3VyArDpO4D']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.4.10-arch1-1-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2023.07.22, secretstorage-3.3.3, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://www.tumblr.com/live/3VyArDpO4D
[generic] 3VyArDpO4D: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 3VyArDpO4D: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tumblr.com/live/3VyArDpO4D
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tumblr.com/live/3VyArDpO4D
```

**Comment by jorong1** [comment]
Tumblr Live is shutting down January 24th, 2024 so I am closing this issue.
