### ISSUE TITLE
File Naming on Win10 with a Twitter link

### ISSUE THREAD

**Issue by SubZero5** [yt-dlp/yt-dlp#7906]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

While trying to download a video from a Twitter, I came up with with an error due to some of the characters in file name. Can you please  fix this issue? After this error, I could download the video with the -o parameter with no issues at all. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\X\Downloads>yt-dlp.exe https://twitter.com/AhmedGurkan/status/1692132916388942258 -vU
[debug] Command-line config: ['https://twitter.com/AhmedGurkan/status/1692132916388942258', '-vU']
[debug] Encodings: locale cp1254, fs utf-8, pref cp1254, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.22.185234 [f780bb52b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.22.185234
Current Build Hash: 9cb23e2fd45fc307c6ebe0d477539fdd760e06fe1703d2289acab103106ef2a7
yt-dlp is up to date (stable@2023.07.22.185234)
[twitter] Extracting URL: https://twitter.com/AhmedGurkan/status/1692132916388942258
[twitter] 1692132916388942258: Downloading guest token
[twitter] 1692132916388942258: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1692119196031660032
[twitter] 1692132916388942258: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, br, size, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1692119196031660032: Downloading 1 format(s): http-2176
[debug] Invoking http downloader on "https://video.twimg.com/ext_tw_video/1692119196031660032/pu/vid/1280x720/qCwgQd-7Mpt4-KMj.mp4?tag=12"
[download] Unable to open file: [Errno 22] Invalid argument: 'Ahmed Gürkan - 🔎  #ASUZU  📍 Yıllardır görmediğimiz bir kâr geldi.  📍 İyi bilançoyu birileri muhtemelen biliyordu.  📍 Normal koşullarda bu iyi bilançoyu 340₺ olan zirve fiyatla taçlandırması gerekiyor.  #Otomotiv #FROTO #TOASO #DOAS  💬 l @memoyesh [1692119196031660032].mp4.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Ahmed Gürkan - 🔎  #ASUZU  📍 Yıllardır görmediğimiz bir kâr geldi.  📍 İyi bilançoyu birileri muhtemelen biliyordu.  📍 Normal koşullarda bu iyi bilançoyu 340₺ olan zirve fiyatla taçlandırması gerekiyor.  #Otomotiv #FROTO #TOASO #DOAS  💬 l @memoyesh [1692119196031660032].mp4.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Ahmed Gürkan - 🔎  #ASUZU  📍 Yıllardır görmediğimiz bir kâr geldi.  📍 İyi bilançoyu birileri muhtemelen biliyordu.  📍 Normal koşullarda bu iyi bilançoyu 340₺ olan zirve fiyatla taçlandırması gerekiyor.  #Otomotiv #FROTO #TOASO #DOAS  💬 l @memoyesh [1692119196031660032].mp4.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: 'Ahmed Gürkan - 🔎  #ASUZU  📍 Yıllardır görmediğimiz bir kâr geldi.  📍 İyi bilançoyu birileri muhtemelen biliyordu.  📍 Normal koşullarda bu iyi bilançoyu 340₺ olan zirve fiyatla taçlandırması gerekiyor.  #Otomotiv #FROTO #TOASO #DOAS  💬 l @memoyesh [1692119196031660032].mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 593, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 260, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5122, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 596, in sanitize_open
OSError: [Errno 22] Invalid argument: 'Ahmed Gürkan - 🔎  #ASUZU  📍 Yıllardır görmediğimiz bir kâr geldi.  📍 İyi bilançoyu birileri muhtemelen biliyordu.  📍 Normal koşullarda bu iyi bilançoyu 340₺ olan zirve fiyatla taçlandırması gerekiyor.  #Otomotiv #FROTO #TOASO #DOAS  💬 l @memoyesh [1692119196031660032].mp4.part'



C:\Users\X\Downloads>
```

**Comment by bashonly** [comment]
The filename is just too long
Use output template to shorten the title
`-o "%(title).100B [%(id)s].%(ext)s"`

see pinned issues
