### ISSUE TITLE
[ZDF] Download fails for FHD and UHD videos with HTTP Error 403

### ISSUE THREAD

**Issue by blackicedbear** [yt-dlp/yt-dlp#7935]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

When attempting to download videos from ZDF [https://www.zdf.de/](https://www.zdf.de/), which are available in FHD or UHD, the extractor provides formats that are not downloadable. When trying to download these formats, an error occurs: HTTP Error 403: Forbidden. You can identify these problematic formats using the following method: Unavailable formats contain "http_na_na" in their name, and their resolution is marked as "unknown." I tried to download all of them and none worked. The output can be observed by running yt-dlp with the -F option, accessible via this PasteBin link: [https://pastebin.com/4SybdgyY](https://pastebin.com/4SybdgyY). As previously mentioned, I attempted to download all formats with "http_na_na" in their name and an "unknown" resolution. The corresponding output is available here: [https://pastebin.com/9z1DC0v7](https://pastebin.com/9z1DC0v7).

Upon running yt-dlp with no arguments, it automatically selects an inaccessible format by default. This issue has been persistent since version [yt-dlp 2023.02.17](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.02.17). Versions prior to [yt-dlp 2023.01.06](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.01.06) function correctly.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.zdf.de/serien/killing-eve/neue-allianzen-100.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110165-g9a245bdf5d-20230403 (setts), ffprobe N-110165-g9a245bdf5d-20230403
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[debug] Using fake IP 53.196.246.65 (DE) as X-Forwarded-For
[ZDF] Extracting URL: https://www.zdf.de/serien/killing-eve/neue-allianzen-100.html
[ZDF] neue-allianzen-100: Downloading webpage
[ZDF] neue-allianzen-100: Downloading JSON content
[ZDF] neue-allianzen-100: Downloading JSON metadata
[ZDF] 230414_0140_sendung_kev: Downloading m3u8 information
[ZDF] 230414_0140_sendung_kev: Downloading m3u8 information
[ZDF] 230414_0140_sendung_kev: Downloading m3u8 information
[ZDF] 230414_0140_sendung_kev: Downloading m3u8 information
[ZDF] 230414_0140_sendung_kev: Downloading m3u8 information
[ZDF] 230414_0140_sendung_kev: Downloading m3u8 information
[ZDF] 230414_0140_sendung_kev: Downloading m3u8 information
[ZDF] 230414_0140_sendung_kev: Downloading m3u8 information
[debug] Sort order given by extractor: tbr, res, quality, language_preference
[debug] Formats sorted by: hasvid, ie_pref, tbr, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 230414_0140_sendung_kev: Downloading 1 format(s): http-h264_aac_mp4_http_na_na-fhd-1
[debug] Invoking http downloader on "https://nrodlzdf-a.akamaihd.net/de/zdf/23/04/230414_0140_sendung_kev/1/230414_0140_sendung_kev_a1a2_6628k_p61v17.mp4"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3363, in process_info
  File "yt_dlp\YoutubeDL.py", line 3084, in dl
  File "yt_dlp\downloader\common.py", line 461, in download
  File "yt_dlp\downloader\http.py", line 377, in real_download
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3863, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
@seproDev any idea if something else is needed for the formats sourced from the Android API endpoint?

**Comment by seproDev** [comment]
As far as I can tell, this is a geo restriction. The HTTP downloads only work with a German IP, while HLS downloads seem to work from everywhere. Currently, HTTP is ranked higher than HLS.
