### ISSUE TITLE
Douyin cannot get the correct duration

### ISSUE THREAD

**Issue by RallyQ** [yt-dlp/yt-dlp#7941]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

china

### Provide a description that is worded well enough to be understood

douyin cannot get the correct duration
Use this parameter，In batch ： %%(duration>%%H-%%M-%%S)s
Get this length：19-57-14，In fact 1:11
https://www.douyin.com/video/7269335815904415034

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
c:\Users\XXXX\AppData\Local\Programs\Python\Python39\Scripts\yt-dlp.exe -vU -w -i --proxy "" --cookies "cookie-dy.txt" -f "137+140/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -o "Z:\rec\test_[%(duration>%H-%M-%S)s]_%(resolution)s_%(id)s_[YD].%(ext)s"   "https://www.douyin.com/video/7269335815904415034"
[debug] Command-line config: ['-vU', '-w', '-i', '--proxy', '', '--cookies', 'cookie-dy.txt', '-f', '137+140/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-o', 'Z:\\rec\\test_[%(duration>%H-%M-%S)s]_%(resolution)s_%(id)s_[YD].%(ext)s', 'https://www.douyin.com/video/7269335815904415034']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.0 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1856 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.06.22
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Traceback (most recent call last):
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\yt_dlp-2023.6.22-py3.9.egg\yt_dlp\__init__.py", line 971, in _real_main
    if opts.update_self and updater.update() and actual_use:
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\yt_dlp-2023.6.22-py3.9.egg\yt_dlp\update.py", line 288, in update
    if not self.check_update():
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\yt_dlp-2023.6.22-py3.9.egg\yt_dlp\update.py", line 277, in check_update
    if self.has_update:
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\yt_dlp-2023.6.22-py3.9.egg\yt_dlp\update.py", line 227, in has_update
    return not self._version_compare(self.current_version, self.new_version)
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\yt_dlp-2023.6.22-py3.9.egg\yt_dlp\update.py", line 217, in new_version
    return self._get_actual_tag(self._tag)
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\functools.py", line 969, in __get__
    val = self.func(instance)
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\yt_dlp-2023.6.22-py3.9.egg\yt_dlp\update.py", line 175, in _tag
    for line in self._download('_update_spec', 'latest').decode().splitlines():
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\yt_dlp-2023.6.22-py3.9.egg\yt_dlp\update.py", line 238, in _download
    return self.ydl.urlopen(url).read()
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\yt_dlp-2023.6.22-py3.9.egg\yt_dlp\YoutubeDL.py", line 3786, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python39\Lib\site-packages\yt_dlp-2023.6.22-py3.9.egg\yt_dlp\utils\_utils.py", line 1514, in https_open
    return self.do_open(
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\urllib\request.py", line 1346, in do_open
    r = h.getresponse()
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\XXXX\appdata\local\programs\python\python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
[Douyin] Extracting URL: https://www.douyin.com/video/7269335815904415034
[Douyin] 7269335815904415034: Downloading video feed
[Douyin] 7269335815904415034: Unable to find video in feed; trying with webpage
[Douyin] 7269335815904415034: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 7269335815904415034: Downloading 1 format(s): 1
[debug] Invoking http downloader on "https://v26-web.douyinvod.com/c4dcc503c8b8c2c5d565016f195b84b2/64e5becf/video/tos/cn/tos-cn-ve-15c001-alinc2/osakvq1mVAELQ9lXgIea43NncbSfJwdDAAB3hE/?a=6383&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=2403&bt=2403&cs=0&ds=3&ft=GN7rKGVVywlZRmm8Imo~xj7ScoAp7DaL6vrKL.f3Dto0g3&mime_type=video_mp4&qs=0&rc=ZTczNGdoNWk8Z2ZpaDw7N0BpM3lmbDg6ZnF3bTMzNGkzM0AwLmJfXmNjNjQxMTJiMS0uYSNhNl5qcjQwbmRgLS1kLWFzcw%3D%3D&btag=e00028000&dy_q=1692774520&l=202308231508407006B2ED6CE2620362F8"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Z:\rec\test_[19-57-14]_1920x1080_7269335815904415034_[YD].mp4
[download] 100% of   21.08MiB in 00:00:00 at 23.88MiB/s
```

**Comment by RallyQ** [comment]
> 看起来抖音提供的持续时间以毫秒为单位，而不是秒（就像 TT 那样）
> 
> ```python
> diff --git a/yt_dlp/extractor/tiktok.py b/yt_dlp/extractor/tiktok.py
> index f14c4f9d6..f524ea3ed 100644
> --- a/yt_dlp/extractor/tiktok.py
> +++ b/yt_dlp/extractor/tiktok.py
> @@ -1052,7 +1052,10 @@ def _real_extract(self, url):
>              raise ExtractorError(
>                  'Fresh cookies (not necessarily logged in) are needed', expected=expected)
>  
> -        return self._parse_aweme_video_web(get_first(render_data, ('aweme', 'detail')), url, video_id)
> +        info = self._parse_aweme_video_web(get_first(render_data, ('aweme', 'detail')), url, video_id)
> +        info['duration'] = int_or_none(info.get('duration'), 1000)
> +
> +        return info
>  
>  
>  class TikTokVMIE(InfoExtractor):
> ```

After making changes to tiktok.py, an error message appears and cannot be downloaded

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\__init__.py", line 1008, in main
    _exit(*variadic(_real_main(argv)))
                    ^^^^^^^^^^^^^^^^
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\__init__.py", line 998, in _real_main
    return ydl.download(all_urls)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3485, in download
    self.__download_wrapper(self.extract_info)(
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3460, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 821, in get_info_extractor
    ie = get_info_extractor(ie_key)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\lazy_extractors.py", line 37, in __new__
    instance = cls.real_class.__new__(cls.real_class)
               ^^^^^^^^^^^^^^
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 5553, in __get__
    return self.func(cls)
           ^^^^^^^^^^^^^^
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\lazy_extractors.py", line 33, in real_class
    cls._real_class = getattr(importlib.import_module(cls._module), cls.__name__)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\tiktok.py", line 1029
    info['duration'] = int_or_none(info.get('duration'), 1000)
TabError: inconsistent use of tabs and spaces in indentation

**Comment by RallyQ** [comment]
> 1. Don't modify a pip/package manager installation, `git clone` the repo and run from source
> 
>     2. Don't edit by hand, save the patch as a file and `git apply patchfile.diff` in your cloned repo's directory

Other software directly modify the .py file can be used, why not dlp?
