### ISSUE TITLE
FIFA's URL structure has changed, causing "Unsupported URL" error for all links

### ISSUE THREAD

**Issue by dmattera** [yt-dlp/yt-dlp#7944]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

FIFA's video site (aka FIFA+) have changed their URL structure from:

https://www.fifa.com/fifaplus/en/watch/7on10qPcnyLajDDU3ntg6y (this is one of the _TEST urls from `fifa.py`)

to 

https://www.plus.fifa.com/en/content/italy-v-france-final-2006-fifa-world-cup-germany-full-match-replay/fee2f7e8-92fa-42c5-805c-a2c949015eae?gl=us

the old version of the URL now redirects automatically to the new.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~ $ yt-dlp -vU https://www.plus.fifa.com/en/content/italy-v-france-final-2006-fifa-world-cup-germany-full-match-replay/fee2f7e8-92fa-42c5-805c-a2c949015eae\?gl\=us
[debug] Command-line config: ['-vU', 'https://www.plus.fifa.com/en/content/italy-v-france-final-2006-fifa-world-cup-germany-full-match-replay/fee2f7e8-92fa-42c5-805c-a2c949015eae?gl=us']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.9.0 (CPython x86_64 64bit) - macOS-10.15.7-x86_64-i386-64bit (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg N-106844-g0a58fdfd3e-tessus (setts), ffprobe N-106844-g0a58fdfd3e-tessus
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.45.1, sqlite3-2.6.0, websockets-9.1, xattr-0.9.9
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (<urlopen error [Errno 64] Host is down>); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[generic] Extracting URL: https://www.plus.fifa.com/en/content/italy-v-france-final-2006-fifa-world-cup-germany-full-match-replay/fee2f7e8-92fa-42c5-805c-a2c949015eae?gl=us
[generic] fee2f7e8-92fa-42c5-805c-a2c949015eae?gl=us: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] fee2f7e8-92fa-42c5-805c-a2c949015eae?gl=us: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.plus.fifa.com/en/content/italy-v-france-final-2006-fifa-world-cup-germany-full-match-replay/fee2f7e8-92fa-42c5-805c-a2c949015eae?gl=us
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.plus.fifa.com/en/content/italy-v-france-final-2006-fifa-world-cup-germany-full-match-replay/fee2f7e8-92fa-42c5-805c-a2c949015eae?gl=us
```

**Comment by bashonly** [comment]
New URLs are more than just a URL format change, it looks like these videos are no longer hosted on uplynk and route through a different API.

And the really bad news, they are DRM-only:
```json
[
  {
    "url": "https://d33tkx2907c8gi.cloudfront.net/s/vod/main_100/FIM100392-M00_v05.885e42cc_SDR_20230419-1718/FIM100392-M00_v05.885e42cc_SDR.eng_mul.h264_SDHD.cenc_subs.mpd",
    "quality": "HD",
    "language": "eng",
    "authenticated": false,
    "codec": "mpd/cenc+h264",
    "subtitles": {}
  },
  {
    "url": "https://d33tkx2907c8gi.cloudfront.net/s/vod/main_100/FIM100392-M00_v05.885e42cc_SDR_20230419-1718/FIM100392-M00_v05.885e42cc_SDR.eng_mul.h264_SDHDP.cenc_subs.mpd",
    "quality": "HDP",
    "language": "eng",
    "authenticated": false,
    "codec": "mpd/cenc+h264",
    "subtitles": {}
  },
  {
    "url": "https://d33tkx2907c8gi.cloudfront.net/s/vod/main_100/FIM100392-M00_v05.885e42cc_SDR_20230419-1718/FIM100392-M00_v05.885e42cc_SDR.eng_mul.h264_SD.cenc_subs.mpd",
    "quality": "SD",
    "language": "eng",
    "authenticated": false,
    "codec": "mpd/cenc+h264",
    "subtitles": {}
  },
  {
    "url": "https://d33tkx2907c8gi.cloudfront.net/s/vod/main_100/FIM100392-M00_v05.885e42cc_SDR_20230419-1718/FIM100392-M00_v05.885e42cc_SDR.por_mul.h264_SDHD.cenc_subs.mpd",
    "quality": "HD",
    "language": "por",
    "authenticated": false,
    "codec": "mpd/cenc+h264",
    "subtitles": {}
  },
  {
    "url": "https://d33tkx2907c8gi.cloudfront.net/s/vod/main_100/FIM100392-M00_v05.885e42cc_SDR_20230419-1718/FIM100392-M00_v05.885e42cc_SDR.por_mul.h264_SDHDP.cenc_subs.mpd",
    "quality": "HDP",
    "language": "por",
    "authenticated": false,
    "codec": "mpd/cenc+h264",
    "subtitles": {}
  },
  {
    "url": "https://d33tkx2907c8gi.cloudfront.net/s/vod/main_100/FIM100392-M00_v05.885e42cc_SDR_20230419-1718/FIM100392-M00_v05.885e42cc_SDR.por_mul.h264_SD.cenc_subs.mpd",
    "quality": "SD",
    "language": "por",
    "authenticated": false,
    "codec": "mpd/cenc+h264",
    "subtitles": {}
  },
  {
    "url": "https://d33tkx2907c8gi.cloudfront.net/s/vod/main_100/FIM100392-M00_v05.885e42cc_SDR_20230419-1718/FIM100392-M00_v05.885e42cc_SDR.spa_mul.h264_SDHD.cenc_subs.mpd",
    "quality": "HD",
    "language": "spa",
    "authenticated": false,
    "codec": "mpd/cenc+h264",
    "subtitles": {}
  },
  {
    "url": "https://d33tkx2907c8gi.cloudfront.net/s/vod/main_100/FIM100392-M00_v05.885e42cc_SDR_20230419-1718/FIM100392-M00_v05.885e42cc_SDR.spa_mul.h264_SDHDP.cenc_subs.mpd",
    "quality": "HDP",
    "language": "spa",
    "authenticated": false,
    "codec": "mpd/cenc+h264",
    "subtitles": {}
  },
  {
    "url": "https://d33tkx2907c8gi.cloudfront.net/s/vod/main_100/FIM100392-M00_v05.885e42cc_SDR_20230419-1718/FIM100392-M00_v05.885e42cc_SDR.spa_mul.h264_SD.cenc_subs.mpd",
    "quality": "SD",
    "language": "spa",
    "authenticated": false,
    "codec": "mpd/cenc+h264",
    "subtitles": {}
  }
]
```

I have tried modifying the API call to exclude DRM formats from the query and it only responds with an empty list. Videos will not play in Firefox w/ DRM disabled either

**Comment by Simeon2001** [comment]
Hello here is there any possible solution or alternative to download fifa videos.

**Comment by CharlesPikachu** [comment]
> Hello here is there any possible solution or alternative to download fifa videos.

maybe you can try: https://github.com/CharlesPikachu/videodl

FFmpeg and N_m3u8DL-RE are required and just run like:

`videodl -i "https://www.plus.fifa.com/en/content/fc-sochaux-montbeliard-vs-lb-chateauroux/6ff75563-c6fc-4b08-b324-54771dbd7029" -a PlusFIFAVideoClient`

or maybe you can require helps from VideoHelp
