### ISSUE TITLE
SonyLIV sports URLs showing "Unsupported URL"

### ISSUE THREAD

**Issue by ArgX11** [yt-dlp/yt-dlp#7996]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

In the sports section of SonyLIV the Full match and Highlight links are showing as "Unsupported URL

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\Softwares\YT-DLP>ytdlp -vU https://www.sonyliv.com/full-match/football-uefa-super-cup-1000232244?watch=true
[debug] Command-line config: ['-vU', 'https://www.sonyliv.com/full-match/football-uefa-super-cup-1000232244?watch=true']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.29.130752 [099fb1b35] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111800-g5f5a1ccd04-20230824 (setts), ffprobe N-111800-g5f5a1ccd04-20230824
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.29.130752, Current version: nightly@2023.08.29.130752
Current Build Hash: 18473f553b2d6305f7c2c5941022aafb6a725a7bacdfa8611a317d7480080d8f
yt-dlp is up to date (nightly@2023.08.29.130752)
[generic] Extracting URL: https://www.sonyliv.com/full-match/football-uefa-super-cup-1000232244?watch=true
[generic] football-uefa-super-cup-1000232244?watch=true: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] football-uefa-super-cup-1000232244?watch=true: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.sonyliv.com/full-match/football-uefa-super-cup-1000232244?watch=true
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1575, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1710, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.sonyliv.com/full-match/football-uefa-super-cup-1000232244?watch=true
```

**Comment by ArgX11** [comment]
```shell
D:\Softwares\YT-DLP>ytdlp -vU https://www.sonyliv.com/highlights/football-uefa-super-cup-1000232366?watch=true
[debug] Command-line config: ['-vU', 'https://www.sonyliv.com/highlights/football-uefa-super-cup-1000232366?watch=true']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.29.130752 [099fb1b35] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111800-g5f5a1ccd04-20230824 (setts), ffprobe N-111800-g5f5a1ccd04-20230824
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.29.130752, Current version: nightly@2023.08.29.130752
Current Build Hash: 18473f553b2d6305f7c2c5941022aafb6a725a7bacdfa8611a317d7480080d8f
yt-dlp is up to date (nightly@2023.08.29.130752)
[generic] Extracting URL: https://www.sonyliv.com/highlights/football-uefa-super-cup-1000232366?watch=true
[generic] football-uefa-super-cup-1000232366?watch=true: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] football-uefa-super-cup-1000232366?watch=true: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.sonyliv.com/highlights/football-uefa-super-cup-1000232366?watch=true
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1575, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1710, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.sonyliv.com/highlights/football-uefa-super-cup-1000232366?watch=true
```

**Comment by dirkf** [comment]
```
ERROR: [SonyLIV] 1000267452: This video is DRM protected
```
Is there page that plays in the browser with [DRM disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)?

**Comment by bashonly** [comment]
`/shows/` URLs are already supported. Closing due to DRM, but can re-open if anyone can produce a non-DRM sports URL
