### ISSUE TITLE
[lbry] broken

### ISSUE THREAD

**Issue by bitingsock** [yt-dlp/yt-dlp#8012]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

2023.08.20.172604 nightly works fine but something in the 2023.08.26.221345 nightly broke LBRY extraction (at least for odysee) and hasn't worked since.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp(5).exe" -v https://odysee.com/@samtime:1/linux-explained-by-an-apple-user:3
[debug] Command-line config: ['-v', 'https://odysee.com/@samtime:1/linux-explained-by-an-apple-user:3']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.20.172604 [7cccab79e] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[lbry] Extracting URL: https://odysee.com/@samtime:1/linux-explained-by-an-apple-user:3
[lbry] @samtime#1/linux-explained-by-an-apple-user#3: Downloading stream JSON metadata
[lbry] 32408bbf651bb717f3cabb163729348246775c27: Downloading streaming url JSON metadata
[lbry] @samtime#1/linux-explained-by-an-apple-user#3: Checking for original quality
[lbry] @samtime#1/linux-explained-by-an-apple-user#3: Downloading streaming redirect url info
[lbry] @samtime#1/linux-explained-by-an-apple-user#3: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 32408bbf651bb717f3cabb163729348246775c27: Downloading 1 format(s): original
[debug] Invoking http downloader on "https://player.odycdn.com/api/v3/streams/free/linux-explained-by-an-apple-user/32408bbf651bb717f3cabb163729348246775c27/707b3d"
[download] Linux Explained by an Apple User [32408bbf651bb717f3cabb163729348246775c27].mp4 has already been downloaded
[download] 100% of   49.37MiB

------

yt-dlp(6).exe" -v https://odysee.com/@samtime:1/linux-explained-by-an-apple-user:3
[debug] Command-line config: ['-v', 'https://odysee.com/@samtime:1/linux-explained-by-an-apple-user:3']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.26.221345 [59e92b1f1] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[lbry] Extracting URL: https://odysee.com/@samtime:1/linux-explained-by-an-apple-user:3
[lbry] @samtime#1/linux-explained-by-an-apple-user#3: Downloading stream JSON metadata
[lbry] 32408bbf651bb717f3cabb163729348246775c27: Downloading streaming url JSON metadata
[lbry] @samtime#1/linux-explained-by-an-apple-user#3: Checking for original quality
[lbry] @samtime#1/linux-explained-by-an-apple-user#3: Downloading streaming redirect url info
ERROR: [lbry] @samtime:1/linux-explained-by-an-apple-user:3: Unable to download webpage: Error -5 while decompressing data: incomplete or truncated stream (caused by TransportError('Error -5 while decompressing data: incomplete or truncated stream'))
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\lbry.py", line 268, in _real_extract
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage

  File "yt_dlp\networking\_urllib.py", line 426, in _send
  File "urllib\request.py", line 531, in open
  File "yt_dlp\networking\_urllib.py", line 188, in http_response
  File "yt_dlp\networking\_urllib.py", line 159, in gz
zlib.error: Error -5 while decompressing data: incomplete or truncated stream

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4059, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 203, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 449, in _send
  File "yt_dlp\networking\_urllib.py", line 361, in handle_response_read_exceptions
yt_dlp.networking.exceptions.TransportError: Error -5 while decompressing data: incomplete or truncated stream

-----------

yt-dlp -vU https://odysee.com/@samtime:1/linux-explained-by-an-apple-user:3
[debug] Command-line config: ['-vU', 'https://odysee.com/@samtime:1/linux-explained-by-an-apple-user:3']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.31.204930 [7237c8dca] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.31.204930, Current version: nightly@2023.08.31.204930
Current Build Hash: 97739c0e6cceb16eea8003b1a13016f6eda136adf68937258552b4d8f41ee5ba
yt-dlp is up to date (nightly@2023.08.31.204930)
[lbry] Extracting URL: https://odysee.com/@samtime:1/linux-explained-by-an-apple-user:3
[lbry] @samtime#1/linux-explained-by-an-apple-user#3: Downloading stream JSON metadata
[lbry] 32408bbf651bb717f3cabb163729348246775c27: Downloading streaming url JSON metadata
[lbry] @samtime#1/linux-explained-by-an-apple-user#3: Checking for original quality
[lbry] @samtime#1/linux-explained-by-an-apple-user#3: Downloading streaming redirect url info
ERROR: [lbry] @samtime:1/linux-explained-by-an-apple-user:3: Unable to download webpage: Error -5 while decompressing data: incomplete or truncated stream (caused by TransportError('Error -5 while decompressing data: incomplete or truncated stream'))
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\lbry.py", line 268, in _real_extract
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage

  File "yt_dlp\networking\_urllib.py", line 426, in _send
  File "urllib\request.py", line 531, in open
  File "yt_dlp\networking\_urllib.py", line 188, in http_response
  File "yt_dlp\networking\_urllib.py", line 159, in gz
zlib.error: Error -5 while decompressing data: incomplete or truncated stream

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4059, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 203, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 449, in _send
  File "yt_dlp\networking\_urllib.py", line 361, in handle_response_read_exceptions
yt_dlp.networking.exceptions.TransportError: Error -5 while decompressing data: incomplete or truncated stream
```

**Comment by bashonly** [comment]
Regression caused by 59e92b1f1833440bb2190f847eb735cf0f90bc85 @Grub4K
