### ISSUE TITLE
Match-TV Russia

### ISSUE THREAD

**Issue by Cryosim** [yt-dlp/yt-dlp#8052]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Russia

### Example URLs

https://matchtv.ru/biathlon/matchtvvideo_NI1938496_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny

### Provide a description that is worded well enough to be understood

Hi. Can't download video from the sport channel Match tv.
I watch in the browser, link was set to https://bl.video.matchtv.ru/media/playlist/api_free_6b1c8cc6a90843ff95ad6a511a3bc56c/17_851765/1080/28f467206d10afe4664f3bd2944e31f4/4849755248.m3u8

If i send this url to the yd-dlp, download only 44 mb part.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
"E:\yt-dlp\yt-dlp.exe" -N 5 -o E:\sport\test.mkv https://matchtv.ru/biathlon/matchtvvideo_NI1938496_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny
[generic] Extracting URL: https://matchtv.ru/biathlon/matchtvvideo_NI1938496_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sod...tva_Sprint_Muzhchiny
[generic] matchtvvideo_NI1938496_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] matchtvvideo_NI1938496_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny: Extracting information
[SportBox] Extracting URL: https://matchtv.ru/vdl/player/media/851766
[SportBox] 851766: Downloading webpage
ERROR: [SportBox] 851766: Unable to extract sources; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by gamer191** [comment]
That webpage contains an embed: "https://video.matchtv.ru/iframe/feed/start/api_free_9bea12b6c582921ce01794a7efa53bff/17_851765/ee35b59098dabda194b9af0701a3fc77/4850190563?sr=14&icons=0&type_id=&width=100%25&height=100%25&lang=ru&skin_name=matchtv"
After discarding everything after the ?, you get "https://video.matchtv.ru/iframe/feed/start/api_free_9bea12b6c582921ce01794a7efa53bff/17_851765/ee35b59098dabda194b9af0701a3fc77/4850190563"

add .m3u8 to the end, andreplace `video` with `bl.video`, and you get: https://bl.video.matchtv.ru/iframe/feed/start/api_free_9bea12b6c582921ce01794a7efa53bff/17_851765/ee35b59098dabda194b9af0701a3fc77/4850190563.m3u8

Now just replace `iframe/feed` with `media` https://bl.video.matchtv.ru/media/start/api_free_9bea12b6c582921ce01794a7efa53bff/17_851765/ee35b59098dabda194b9af0701a3fc77/4850190563.m3u8

**Comment by gamer191** [comment]
Damn, I didn't notice that that's not a proper verbose log. Looks like yt-dlp might already somewhat work with this site:
```
[debug] Command-line config: ['-v', 'https://matchtv.ru/biathlon/matchtvvideo_NI1938496_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.09.09.151504 [a006ce2b2] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.4.12-surface-x86_64-with-glibc2.37 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1865 extractors
[generic] Extracting URL: https://matchtv.ru/biathlon/matchtvvideo_NI1938496_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny
[generic] matchtvvideo_NI1938496_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] matchtvvideo_NI1938496_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny: Extracting information
[debug] Looking for embeds
[debug] Identified a SportBox embed
[SportBox] Extracting URL: https://matchtv.ru/vdl/player/media/851766
[SportBox] 851766: Downloading webpage
ERROR: [SportBox] 851766: Unable to extract sources; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 715, in extract
  File "yt_dlp/extractor/sportbox.py", line 50, in _real_extract
  File "yt_dlp/extractor/common.py", line 1263, in _search_regex
```

And that's why you shouldn't ignore an issue template!

**Comment by gamer191** [comment]
This issue should probably be renamed to `[SportBox] Unable to extract source`

**Comment by Cryosim** [comment]
Hello there. Match-TV still doesn't fixed.
```
C:\Users\Alexander>python -myt_dlp -v -N 5 -o "Z:\Biathlon\240906-1.mp4" "https://matchtv.ru/biathlon/matchtvvideo_NI2100211_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny"
[debug] Command-line config: ['-v', '-N', '5', '-o', 'Z:\\Biathlon\\240906-1.mp4', 'https://matchtv.ru/biathlon/matchtvvideo_NI2100211_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.23.232923 from yt-dlp/yt-dlp-nightly-builds [fe70f20ae] (pip)
[debug] Python 3.13.0 (CPython AMD64 64bit) - Windows-11-10.0.26100-SP0 (OpenSSL 3.0.15 3 Sep 2024)
[debug] exe versions: ffmpeg 2024-09-26-git-f43916e217-full_build-www.gyan.dev (setts), ffprobe 2024-09-26-git-f43916e217-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'http://127.0.0.1:10809', 'ftp': 'http://127.0.0.1:10809'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[generic] Extracting URL: https://matchtv.ru/biathlon/matchtvvideo_NI2100211_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny
[generic] matchtvvideo_NI2100211_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] matchtvvideo_NI2100211_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[generic] Extracting URL: https://video.matchtv.ru/iframe/feed/start/free_65960e62d0d4f5bac535deab796f94a9/1202266/b45bd2fda2d47906d84cf2d50c750b32/2208978000?sr=14&type_id=&width=100%25&height=100%25&lang=ru&skin_name=matchtv#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22matchtvvideo_NI2100211_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny%22%2C+%22to_generic%22%3A+true%2C+%22referer%22%3A+%22https%3A%2F%2Fmatchtv.ru%2Fbiathlon%2Fmatchtvvideo_NI2100211_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny%22%7D
[generic] matchtvvideo_NI2100211_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny: Downloading webpage
[generic] matchtvvideo_NI2100211_translation_Letnij_biatlon_Alfa_Bank_Kubok_Sodruzhestva_Sprint_Muzhchiny: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://video.matchtv.ru/iframe/feed/start/free_65960e62d0d4f5bac535deab796f94a9/1202266/b45bd2fda2d47906d84cf2d50c750b32/2208978000?sr=14&type_id=&width=100%25&height=100%25&lang=ru&skin_name=matchtv
Traceback (most recent call last):
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1759, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\extractor\common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python313\Lib\site-packages\yt_dlp\extractor\generic.py", line 2553, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://video.matchtv.ru/iframe/feed/start/free_65960e62d0d4f5bac535deab796f94a9/1202266/b45bd2fda2d47906d84cf2d50c750b32/2208978000?sr=14&type_id=&width=100%25&height=100%25&lang=ru&skin_name=matchtv
C:\Users\Alexander>
```

**Comment by Cryosim** [comment]
@bashonly Can you fix it? i can send to you any data. Please.
