### ISSUE TITLE
Please update website : https://www.youku.tv/ extractor. Thanks so much ~

### ISSUE THREAD

**Issue by jayt1990** [yt-dlp/yt-dlp#8058]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://v.youku.tv/v_show/id_XNTIwMTQxMDMyOA==.html

### Provide a description that is worded well enough to be understood

Please update website : https://www.youku.tv/ extractor. Thanks so much ~

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\yt-dl>yt-dlp --cookies-from-browser edge -vU https://v.youku.tv/v_show/id_XNTIwMTQxMDMyOA==.html
[debug] Command-line config: ['--cookies-from-browser', 'edge', '-vU', 'https://v.youku.tv/v_show/id_XNTIwMTQxMDMyOA==.html']
[debug] Encodings: locale cp1258, fs utf-8, pref cp1258, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-07-19-git-efa6cec759-full_build-www.gyan.dev (setts), ffprobe 2023-07-19-git-efa6cec759-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\Jay Te\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Jay Te\AppData\Local\Microsoft\Edge\User Data\Local State"
[Cookies] Extracted 3036 cookies from edge
[debug] cookie version breakdown: {'v10': 3052, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://v.youku.tv/v_show/id_XNTIwMTQxMDMyOA==.html
[generic] id_XNTIwMTQxMDMyOA==: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] id_XNTIwMTQxMDMyOA==: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://v.youku.tv/v_show/id_XNTIwMTQxMDMyOA==.html
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1688, in __extract_info
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://v.youku.tv/v_show/id_XNTIwMTQxMDMyOA==.html
```

**Comment by bashonly** [comment]
Does changing the URL to `v.youku.com` workaround the issue?

**Comment by jayt1990** [comment]
> Does changing the URL to `v.youku.com` workaround the issue?

No bro, youku.tv is international version, youku.com is china-mainland ~

**Comment by gamer191** [comment]
@jayt1990 can we just redirect v.youku.tv to v.youku.com

**Comment by jayt1990** [comment]
Movie on v.youku.com is hardsub. Movie on v.youku.tv is clear screen bro. So i think it's 2 server different ~

**Comment by jayt1990** [comment]
Some one please help me fix youku extractor working with v.youku.tv. T.T

**Comment by callista13** [comment]
Hi, I would like to check if youku.tv sites are still unsupported. I tried with this link earlier and got the Unsupported URL error. https://www.youku.tv/v/v_show/id_XNjM1NDY4NjM0NA==.html?s=ddba12a33dc44673a604&spm=a2hje.13141534.1_2.d_zj2_16&scm=20140719.apircmd.242627.video_XNjM1NDY4NjM0NA==

**Comment by Nice-Music** [comment]
Please update website : https://www.youku.tv/ extractor. Thanks

**Comment by garendra28** [comment]
please update to support with youku.tv thanks.
