### ISSUE TITLE
[Errno 21] Is a directory: '/home/zod/Downloads/YouTube/Inkscape Tutorials/'

### ISSUE THREAD

**Issue by zeyadelkholyttt** [yt-dlp/yt-dlp#8068]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i wrote this command to make me able to download playlists in the playlist title dir but this give me this error (i chose the question because i know this is my error not a error in program also i think this done because the name have spaces but i didn't know how can i fix that )

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-P', '/home/zod/Downloads/YouTube/', '-o', '%(playlist)s/', '-f', '[height<=720]', 'https://www.youtube.com/playlist?list=PLqazFFzUAPc5lOQwDoZ4Dw2YSXtO7lWNv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.3.13_1-x86_64-with-glibc2.36 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLqazFFzUAPc5lOQwDoZ4Dw2YSXtO7lWNv
[youtube:tab] PLqazFFzUAPc5lOQwDoZ4Dw2YSXtO7lWNv: Downloading webpage
[youtube:tab] PLqazFFzUAPc5lOQwDoZ4Dw2YSXtO7lWNv: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Inkscape Tutorials
[youtube:tab] Playlist Inkscape Tutorials: Downloading 87 items of 87
[download] Downloading item 1 of 87
[youtube] Extracting URL: https://www.youtube.com/watch?v=8f011wdiW7g
[youtube] 8f011wdiW7g: Downloading webpage
[youtube] 8f011wdiW7g: Downloading ios player API JSON
[youtube] 8f011wdiW7g: Downloading android player API JSON
[debug] Loading youtube-nsig.7ee36b0e from cache
[debug] [youtube] Decrypted nsig vqp88rBWO4kVFIsW => txgLwxKZfIU8oQ
[youtube] 8f011wdiW7g: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] 8f011wdiW7g: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr4---sn-uxaxjvhxbt2u-icx6.googlevideo.com/videoplayback?expire=1694269336&ei=OCv8ZK-sAqqep-oPuLGvwA8&ip=102.43.197.15&id=o-ADlOhjK--P_kznS_ksIUsnOsDeq0TSFqIrBkNWq7Kz0j&itag=22&source=youtube&requiressl=yes&mh=Tg&mm=31%2C29&mn=sn-uxaxjvhxbt2u-icx6%2Csn-hgn7rn7k&ms=au%2Crdu&mv=m&mvi=4&pl=22&initcwndbps=407500&spc=UWF9f4UbAFL-mzYdHGjFTiABd-aR68k&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=571.164&lmt=1673587779228094&mt=1694247423&fvip=4&fexp=24007246%2C51000023&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMn97_0t0YDekCwjbW8e0gBqegitxE0wiqsYahfCAc4bAiBvBfgyFpXB8r-y-Do3HSEWMxAuRPufB7MQBix8q_jpmA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKuXG1JAC0DAm0qjI6-ca2_EYFW_d3I33L7S1sbVwzJXAiEAxBuMN3ZUyoCO6TlmQV7ZTKHgvFCzVZPmC4J8dFecM6w%3D"
ERROR: unable to open for writing: [Errno 21] Is a directory: '/home/zod/Downloads/YouTube/Inkscape Tutorials/'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 663, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 2036, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/zod/Downloads/YouTube/Inkscape Tutorials/'
```

**Comment by zeyadelkholyttt** [comment]
this problem done with me because the -o tell how the file will be so i must tell the file format which is  (%(title)s.%(ext)s).
sorry for being dummy😂
