### ISSUE TITLE
Does someone have vid tut on HOW to download videos from youku, iqiyi and wetv vip videos (non vip is downloadable on wetv) using yt-dlp

### ISSUE THREAD

**Issue by tantai-jin** [yt-dlp/yt-dlp#8071]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i'm using it on windows10 
i have installed yt-dlp.exe in folder YouTube-dl under downloads section
i have tried by typing both "yt-dlp" and "yt-dlp.exe"

i'm new to use yt-dlp and unable to understand how to download videos from chinese drama streaming platforms like youku, iqiyi mango tv and wetv

(on wetv i'm able to download non vip videos by simply copying the webpage url but unable to do same for vip videos as they only download up to 5 or 6 min.) 

downloading from youku will giving me error as unsupporting url

downloading from iqiyi giving me error like "" [iq.com] 2645a25d1d8: Unable to extract player JS; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U "" i have downloaded latest version

pls help me regarding these drama platform

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
for Youku

[debug] Command-line config: ['-vU', 'https://www.youku.tv/v/v_show/id_XNTk1NTU2MzA0OA==.html?spm=a2hja.14919748_WEBHOME_JINGXUAN.drawer5.d_zj1_1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://www.youku.tv/v/v_show/id_XNTk1NTU2MzA0OA==.html?spm=a2hja.14919748_WEBHOME_JINGXUAN.drawer5.d_zj1_1
[generic] id_XNTk1NTU2MzA0OA==.html?spm=a2hja.14919748_WEBHOME_JINGXUAN.drawer5: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] id_XNTk1NTU2MzA0OA==.html?spm=a2hja.14919748_WEBHOME_JINGXUAN.drawer5: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.youku.tv/v/v_show/id_XNTk1NTU2MzA0OA==.html?spm=a2hja.14919748_WEBHOME_JINGXUAN.drawer5.d_zj1_1
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1688, in __extract_info
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.youku.tv/v/v_show/id_XNTk1NTU2MzA0OA==.html?spm=a2hja.14919748_WEBHOME_JINGXUAN.drawer5.d_zj1_1

's' is not recognized as an internal or external command,
operable program or batch file.
'scm' is not recognized as an internal or external command,
operable program or batch file.


for Iqiyi

[debug] Command-line config: ['-vU', 'https://www.iq.com/play/love-between-fairy-and-devil-episode-1-2645a25d1d8?lang=en_us']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[iq.com] Extracting URL: https://www.iq.com/play/love-between-fairy-and-devil-episode-1-2645a25d1d8?lang=en_us
[iq.com] 2645a25d1d8: Downloading webpage
[iq.com] 2645a25d1d8: Downloading webpack JS
[iq.com] 2645a25d1d8: Downloading #9943 module JS
[iq.com] 2645a25d1d8: Downloading #9922 module JS
[iq.com] 2645a25d1d8: Downloading #9864 module JS
[iq.com] 2645a25d1d8: Downloading #9839 module JS
[iq.com] 2645a25d1d8: Downloading #8741 module JS
[iq.com] 2645a25d1d8: Downloading #7045 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] 2645a25d1d8: Downloading #5465 module JS
[iq.com] 2645a25d1d8: Downloading #5449 module JS
[iq.com] 2645a25d1d8: Downloading #5189 module JS
[iq.com] 2645a25d1d8: Downloading #4959 module JS
[iq.com] 2645a25d1d8: Downloading #4753 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] 2645a25d1d8: Downloading #4681 module JS
[iq.com] 2645a25d1d8: Downloading #4403 module JS
[iq.com] 2645a25d1d8: Downloading #4182 module JS
[iq.com] 2645a25d1d8: Downloading #3087 module JS
[iq.com] 2645a25d1d8: Downloading #2925 module JS
[iq.com] 2645a25d1d8: Downloading #2846 module JS
[iq.com] 2645a25d1d8: Downloading #2708 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] 2645a25d1d8: Downloading #2398 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] 2645a25d1d8: Downloading #2274 module JS
[iq.com] 2645a25d1d8: Downloading #2248 module JS
[iq.com] 2645a25d1d8: Downloading #2163 module JS
[iq.com] 2645a25d1d8: Downloading #2152 module JS
[iq.com] 2645a25d1d8: Downloading #1650 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] 2645a25d1d8: Downloading #1647 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] 2645a25d1d8: Downloading #1487 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] 2645a25d1d8: Downloading #1417 module JS
[iq.com] 2645a25d1d8: Downloading #1361 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] 2645a25d1d8: Downloading #1126 module JS
[iq.com] 2645a25d1d8: Downloading #1106 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] 2645a25d1d8: Downloading #268 module JS
ERROR: [iq.com] 2645a25d1d8: Unable to extract player JS; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\iqiyi.py", line 570, in _real_extract
  File "yt_dlp\extractor\iqiyi.py", line 553, in _update_bid_tags
  File "yt_dlp\extractor\iqiyi.py", line 544, in _extract_vms_player_js
```

**Comment by bashonly** [comment]
Closing as stale

Please limit your issues to a single subject
