### ISSUE TITLE
Support Bilibili danmaku better

### ISSUE THREAD

**Issue by UlyssesZh** [yt-dlp/yt-dlp#8078]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.bilibili.com/video/BV1e94y1x7U5

### Provide a description that is worded well enough to be understood

The downloaded danmuku from Bilibili videos are in XML format, which ffmpeg cannot handle. [There was an issue comment saying that yt-dlp could use Danmaku2ASS as an external dependency, but it cannot be installed using pip.](https://github.com/yt-dlp/yt-dlp/issues/2636#issuecomment-1029891990) However, there is a fork from Danmaku2ASS ([biliass](/yutto-dev/biliass)) that can be installed using pip. Could you use biliass as an external dependency and support danmuku better?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--sub-langs', 'danmaku', '--write-subs', '--convert-subtitles', 'ass', 'https://www.bilibili.com/video/BV1e94y1x7U5']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-78-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1e94y1x7U5
[BiliBili] 1e94y1x7U5: Downloading webpage
[BiliBili] BV1e94y1x7U5: Extracting videos in anthology
[BiliBili] Format(s) 1080P 高码率, 1080P 高清, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[BiliBili] 363296827: Extracting chapters
[BiliBili] BV1e94y1x7U5: Downloading JSON metadata
[info] BV1e94y1x7U5: Downloading subtitles: danmaku
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BV1e94y1x7U5: Downloading 1 format(s): 6+2
Deleting existing file 电棍：Dream on [BV1e94y1x7U5].danmaku.xml
[info] Writing video subtitles to: 电棍：Dream on [BV1e94y1x7U5].danmaku.xml
[debug] Invoking http downloader on "https://comment.bilibili.com/1261489927.xml"
[download] Destination: 电棍：Dream on [BV1e94y1x7U5].danmaku.xml
[download] 100% of  131.68KiB in 00:00:01 at 123.28KiB/s
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:电棍：Dream on [BV1e94y1x7U5].danmaku.xml' -f ass -movflags +faststart 'file:电棍：Dream on [BV1e94y1x7U5].danmaku.ass'
[debug] ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
file:电棍：Dream on [BV1e94y1x7U5].danmaku.xml: Invalid data found when processing input

ERROR: Preprocessing: file:电棍：Dream on [BV1e94y1x7U5].danmaku.xml: Invalid data found when processing input
Traceback (most recent call last):
  File "/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3610, in pre_process
    info = self.run_all_pps(key, info)
  File "/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3603, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3581, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 1008, in run
    self.run_ffmpeg(old_file, new_file, ['-f', new_format])
  File "/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 374, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
  File "/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 329, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 367, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:电棍：Dream on [BV1e94y1x7U5].danmaku.xml: Invalid data found when processing input

[download] 电棍：Dream on [BV1e94y1x7U5].mp4 has already been downloaded
ERROR: Preprocessing: file:电棍：Dream on [BV1e94y1x7U5].danmaku.xml: Invalid data found when processing input
```

**Comment by pukkandan** [comment]
As I replied to the linked comment already, conversion with a dependency is out of scope and should be handled by third party tools or plugins

Ref: https://github.com/yt-dlp/yt-dlp/issues/2636#issuecomment-1030010300

**Comment by LifeJustDLC** [comment]
@pukkandan
It appears that bilibili provides their danmaku API as protobuf officially:
(Chinese page) https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/danmaku/danmaku_proto.md
And this 3rd party repo is only able to consume protobuf:
https://github.com/HFrost0/danmakuC/issues/11
Can we have two "sub lang"s for both xml and protobuf?

**Comment by LifeJustDLC** [comment]
@UlyssesZh
https://github.com/yutto-dev/yutto
pros: url to ass, no separate deps
cons: awful auth experience
