### ISSUE TITLE
Tiktok JSON decode error

### ISSUE THREAD

**Issue by unintended** [yt-dlp/yt-dlp#8089]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

uk

### Provide a description that is worded well enough to be understood

Looks like some arabic content is failed to decode

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vm.tiktok.com/ZMjMK1xkj/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-11.7.1-arm64-arm-64bit (OpenSSL 3.1.1 30 May 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[vm.tiktok] Extracting URL: https://vm.tiktok.com/ZMjMK1xkj/
[vm.tiktok] ZMjMK1xkj: Downloading webpage
[TikTok] Extracting URL: https://www.tiktok.com/@tohamiiat/video/7276516565166656773?_t=8fbD3P2UbsD&_r=1
[TikTok] 7276516565166656773: Downloading video feed
WARNING: [TikTok] 7276516565166656773: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7276516565166656773: Downloading webpage
ERROR: [TikTok] 7276516565166656773: 7276516565166656773: Failed to parse JSON (caused by JSONDecodeError('Expecting \',\' delimiter in \':"\\u200eمسلسل "سفاح الجيز\': line 1 column 32427 (char 32426)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6/libexec/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 673, in _real_extract
    sigi_data = self._get_sigi_state(webpage, video_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6/libexec/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 53, in _get_sigi_state
    return self._parse_json(get_element_by_id(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1011, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 994, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6/libexec/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 624, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 32427 (char 32426)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1008, in _parse_json
    return json.loads(
           ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6/libexec/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 632, in decode
    raise type(e)(f'{e.msg} in {s[e.pos-10:e.pos+10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting ',' delimiter in ':"\u200eمسلسل "سفاح الجيز': line 1 column 32427 (char 32426)
```

**Comment by bashonly** [comment]
There is a `&quot;` in one of the JSON values, and it was being unescaped by `get_element_by_id`/`get_elements_text_and_html_by_attribute`, causing the JSON parsing to fail.

I guess all of the `utils.get_element`... functions should not be used for extracting JSON

This fixes it:
```diff
diff --git a/yt_dlp/extractor/tiktok.py b/yt_dlp/extractor/tiktok.py
index f14c4f9d6..23c6bed48 100644
--- a/yt_dlp/extractor/tiktok.py
+++ b/yt_dlp/extractor/tiktok.py
@@ -50,8 +50,9 @@ def _create_url(user_id, video_id):
         return f'https://www.tiktok.com/@{user_id or "_"}/video/{video_id}'
 
     def _get_sigi_state(self, webpage, display_id):
-        return self._parse_json(get_element_by_id(
-            'SIGI_STATE|sigi-persisted-data', webpage, escape_value=False), display_id)
+        return self._search_json(
+            r'<script[^>]+\bid="(?:SIGI_STATE|sigi-persisted-data)"[^>]*>', webpage,
+            'sigi state', display_id, end_pattern=r'</script>')
 
     def _call_api_impl(self, ep, query, manifest_app_version, video_id, fatal=True,
                        note='Downloading API JSON', errnote='Unable to download API page'):
```

**Comment by lenuxfrance** [comment]
Hello, how can I modify Windows?

**Comment by dirkf** [comment]
Maybe a kwarg `unescape_content=True` could be added to the `get_element_by_xxx()` functions?

**Comment by nicolaasjan** [comment]
After applying the diff, I still get this warning (video downloads fine thereafter):

`WARNING: [TikTok] 7276516565166656773: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage`


```shell
./yt-dlp -v --ignore-config https://vm.tiktok.com/ZMjMK1xkj/
[debug] Command-line config: ['-v', '--ignore-config', 'https://vm.tiktok.com/ZMjMK1xkj/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.09.12 [66cc64ff6] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-162-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-111711-gd295b6b693-Nico-20230808 (fdk,setts), ffprobe N-111711-gd295b6b693-Nico-20230808, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-11.0.3, xattr-0.9.6
[debug] Proxy map: {}
[debug] Loaded 1865 extractors
[vm.tiktok] Extracting URL: https://vm.tiktok.com/ZMjMK1xkj/
[vm.tiktok] ZMjMK1xkj: Downloading webpage
[TikTok] Extracting URL: https://www.tiktok.com/@tohamiiat/video/7276516565166656773?_t=8fbD3P2UbsD&_r=1
[TikTok] 7276516565166656773: Downloading video feed
WARNING: [TikTok] 7276516565166656773: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7276516565166656773: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7276516565166656773: Downloading 1 format(s): download
[debug] Invoking http downloader on "https://v16-webapp-prime.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c004/oIQZA2ntRkhAXJBjBVz7b1faIVMfQALI1GYBEE/?a=1988&ch=0&cr=3&dr=0&lr=tiktok_m&cd=0%7C0%7C1%7C3&cv=1&br=1010&bt=505&bti=ODszNWYuMDE6&cs=0&ds=3&ft=_RwJrB4Vq8ZmoLB.9Q_vjOMGLAhLrus&mime_type=video_mp4&qs=0&rc=NWk5PDhpN2VoaWQ1PDRmZkBpanNvamU6ZnVvbTMzNzczM0BeLmEwM2JjNmIxLmFgLmFgYSNnai9ucjRfaXFgLS1kMTZzcw%3D%3D&btag=e00088000&expire=1694558585&l=20230912164245C5929D406C752B2FD6C9&ply_type=2&policy=2&signature=f44a1a785b387d5623befe0695c0d4ee&tk=tt_chain_token"
[download] Destination: سفاح الجيزه 🖤✨#foryoupage #fypシ #Tohamii #viral #اكسبلور #foryou #سفاح_الجيزة #fyp  [7276516565166656773].mp4
[download] 100% of    1.13MiB in 00:00:00 at 1.28MiB/s
```

**Comment by bashonly** [comment]
Some videos are unavailable via the feed endpoint and require the webpage fallback. There is an open issue about this and it is unrelated

**Comment by unintended** [comment]
> There is a `&quot;` in one of the JSON values, and it was being unescaped by `get_element_by_id`/`get_elements_text_and_html_by_attribute`, causing the JSON parsing to fail.
> 
> I guess all of the `utils.get_element`... functions should not be used for extracting JSON
> 
> This fixes it:
> 
> ```diff
> diff --git a/yt_dlp/extractor/tiktok.py b/yt_dlp/extractor/tiktok.py
> index f14c4f9d6..23c6bed48 100644
> --- a/yt_dlp/extractor/tiktok.py
> +++ b/yt_dlp/extractor/tiktok.py
> @@ -50,8 +50,9 @@ def _create_url(user_id, video_id):
>          return f'https://www.tiktok.com/@{user_id or "_"}/video/{video_id}'
>  
>      def _get_sigi_state(self, webpage, display_id):
> -        return self._parse_json(get_element_by_id(
> -            'SIGI_STATE|sigi-persisted-data', webpage, escape_value=False), display_id)
> +        return self._search_json(
> +            r'<script[^>]+\bid="(?:SIGI_STATE|sigi-persisted-data)"[^>]*>', webpage,
> +            'sigi state', display_id, end_pattern=r'</script>')
>  
>      def _call_api_impl(self, ep, query, manifest_app_version, video_id, fatal=True,
>                         note='Downloading API JSON', errnote='Unable to download API page'):
> ```

I inplace-edited with this patch in my project and everything works now. So, it looks like a well-working patch
