### ISSUE TITLE
Add 'nyheter' and 'video-player/embed/' to the regex recognizing URLs from expressen.se

### ISSUE THREAD

**Issue by kylegustavo** [yt-dlp/yt-dlp#8141]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Swedish site, but accesible from US

### Example URLs

https://www.expressen.se/video-player/embed/tv/nyheter/ekero-fodda-olof-gustafsson-forvaltar-knarkbaronen-pablo-escobars-namn

https://www.expressen.se/nyheter/efter-egna-telefonbluffen-escobar-stammer-klarna/

### Provide a description that is worded well enough to be understood

The nyheter/ path and the video-player/embed/ path are ways to represent a video link, but they are currently not in the regex. videoplayer/embed is there, but the 'video-player' version with a hyphen needs to be added.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.expressen.se/nyheter/efter-egna-telefonbluffen-escobar-stammer-klarna/
[debug] Command-line config: ['-vU', 'https://www.expressen.se/nyheter/efter-egna-telefonbluffen-escobar-stammer-klarna/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.4.0-1075-fips-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1865 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://www.expressen.se/nyheter/efter-egna-telefonbluffen-escobar-stammer-klarna/
[generic] efter-egna-telefonbluffen-escobar-stammer-klarna: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] efter-egna-telefonbluffen-escobar-stammer-klarna: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.expressen.se/nyheter/efter-egna-telefonbluffen-escobar-stammer-klarna/
Traceback (most recent call last):
  File "/snap/yt-dlp/308/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1575, in wrapper
    return func(self, *args, **kwargs)
  File "/snap/yt-dlp/308/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1710, in __extract_info
    ie_result = ie.extract(url)
  File "/snap/yt-dlp/308/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/snap/yt-dlp/308/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.expressen.se/nyheter/efter-egna-telefonbluffen-escobar-stammer-klarna/



kgonsalves@harvest-west-6:/opt/authentic8/hv$ yt-dlp -vU https://www.expressen.se/video-player/embed/tv/nyheter/ekero-fodda-olof-gustafsson-forvaltar-knarkbaronen-pablo-escobars-namn
[debug] Command-line config: ['-vU', 'https://www.expressen.se/video-player/embed/tv/nyheter/ekero-fodda-olof-gustafsson-forvaltar-knarkbaronen-pablo-escobars-namn']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.4.0-1075-fips-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1865 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://www.expressen.se/video-player/embed/tv/nyheter/ekero-fodda-olof-gustafsson-forvaltar-knarkbaronen-pablo-escobars-namn
[generic] ekero-fodda-olof-gustafsson-forvaltar-knarkbaronen-pablo-escobars-namn: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ekero-fodda-olof-gustafsson-forvaltar-knarkbaronen-pablo-escobars-namn: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.expressen.se/video-player/embed/tv/nyheter/ekero-fodda-olof-gustafsson-forvaltar-knarkbaronen-pablo-escobars-namn
Traceback (most recent call last):
  File "/snap/yt-dlp/308/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1575, in wrapper
    return func(self, *args, **kwargs)
  File "/snap/yt-dlp/308/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1710, in __extract_info
    ie_result = ie.extract(url)
  File "/snap/yt-dlp/308/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/snap/yt-dlp/308/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.expressen.se/video-player/embed/tv/nyheter/ekero-fodda-olof-gustafsson-forvaltar-knarkbaronen-pablo-escobars-namn
```

**Comment by bashonly** [comment]
This seems to work
```diff
diff --git a/yt_dlp/extractor/expressen.py b/yt_dlp/extractor/expressen.py
index 86967b631..50eaa8500 100644
--- a/yt_dlp/extractor/expressen.py
+++ b/yt_dlp/extractor/expressen.py
@@ -11,8 +11,8 @@ class ExpressenIE(InfoExtractor):
     _VALID_URL = r'''(?x)
                     https?://
                         (?:www\.)?(?:expressen|di)\.se/
-                        (?:(?:tvspelare/video|videoplayer/embed)/)?
-                        tv/(?:[^/]+/)*
+                        (?:(?:tvspelare/video|video-?player/embed)/)?
+                        (?:tv|nyheter)/(?:[^/?#]+/)*
                         (?P<id>[^/?#&]+)
                     '''
     _EMBED_REGEX = [r'<iframe[^>]+\bsrc=(["\'])(?P<url>(?:https?:)?//(?:www\.)?(?:expressen|di)\.se/(?:tvspelare/video|videoplayer/embed)/tv/.+?)\1']
```
