### ISSUE TITLE
[Broken] muted Twitch vods

### ISSUE THREAD

**Issue by reinstallgentoo** [yt-dlp/yt-dlp#819]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
./yt-dlp --downloader aria2c https://d1m7jfoe9zdc1j.cloudfront.net/REDACTED/chunked/index-dvr.m3u8
...
08/29 18:30:00 [ERROR] CUID#6951 - Download aborted. URI=https://d1m7jfoe9zdc1j.cloudfront.net/REDACTED/chunked/864-unmuted.ts
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://d1m7jfoe9zdc1j.cloudfront.net/REDACTED/chunked/864-unmuted.ts
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403
...
[aria2c] Skipping fragment 864 ...
```

Hi, muted Twitch vods are failing when yt-dlp fetches unmuted fragments which are unavailable, meanwhile muted portions are available but yt-dlp doesn't check for them? 
Ideally yt-dlp should fallback to the muted fragments to ensure a complete download.

**Example**
Unavailable, results in failed/corrupt download.
```
https://d1m7jfoe9zdc1j.cloudfront.net/REDACTED/chunked/864-unmuted.ts
```
Available, but ignored.
```
https://d1m7jfoe9zdc1j.cloudfront.net/REDACTED/chunked/864-muted.ts
```

The vods play fine in the browser and mpv.
Is there a quick workaround for this in the meantime?
Thank you.

**Comment by pukkandan** [comment]
Provide **ENTIRE** verbose log. Also, if you redact the URL, we cant test the situation, so expect to get only limited help

**Comment by pukkandan** [comment]
Closed due to inactivity

**Comment by wlritchi** [comment]
@pukkandan I can provide sufficient details to reopen this ticket for discussion as a feature request.

Background
----------------

Twitch postprocesses recordings of livestreams to mute segments of videos that contain copyrighted music. When they do this, the original m3u8 URL (`.../index-dvr.m3u8`) stays live, but for muted segments, instead of pointing to e.g. `32.ts`, the m3u8 file now points to `32-unmuted.ts`. However, that new/renamed `32-unmuted.ts` file is not accessible! Instead, a modified `32-muted.ts` file becomes accessible.

None of this is an issue for the main extractor used by yt-dlp, because we actually extract a separate m3u8 URL (`.../index-muted-<slug>.m3u8`). This separate m3u8 contains links to the correct `32-muted.ts` where needed.

However, there are a relatively large number of third party tools and sites that extract or return the original `index-dvr.m3u8` link, presumably because there's no obvious way to determine the slug in the `index-muted-<slug>.m3u8` file without the more complex querying that yt-dlp uses. These tools and sites then postprocess the m3u8 file to transform `-unmuted` into `-muted`. As far as I can tell, this process is very reliable.

This ticket should be considered a feature request to support transforming the m3u8 in the same way, or a discussion of alternatives.

Verbose log
----------------
<details>
<summary>Downloading VOD via Twitch frontend URL (works correctly)</summary>

```
$ yt-dlp -vU --no-config -- https://www.twitch.tv/videos/1449471680
[debug] Command-line config: ['-vU', '--no-config', '--', 'https://www.twitch.tv/videos/1449471680']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.16.1-arch1-1-x86_64-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1449471680
[twitch:vod] 1449471680: Downloading stream metadata GraphQL
[twitch:vod] 1449471680: Downloading video access token GraphQL
[twitch:vod] 1449471680: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] v1449471680: Downloading 1 format(s): 1080p60
[debug] Invoking downloader on "https://d2vjef5jvl6bfs.cloudfront.net/198486c3ab50d176b772_djmiyuki_46104209485_1649379608/chunked/index-muted-ZUTW53NYZX.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 727
[download] Destination: ✰ LA show TMR ✷ Get your tickets FAM ~ !show [v1449471680].mp4
[download] 100% of 5.40GiB in 06:02
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:✰ LA show TMR ✷ Get your tickets FAM ~ !show [v1449471680].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "✰ LA show TMR ✷ Get your tickets FAM ~ !show [v1449471680].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:✰ LA show TMR ✷ Get your tickets FAM ~ !show [v1449471680].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:✰ LA show TMR ✷ Get your tickets FAM ~ !show [v1449471680].temp.mp4'
```
</details>

<details>
<summary>Downloading via `index-muted-<slug>.m3u8` directly (works)</summary>

```
$ yt-dlp -vU --no-config -- https://d2vjef5jvl6bfs.cloudfront.net/198486c3ab50d176b772_djmiyuki_46104209485_1649379608/chunked/index-muted-ZUTW53NYZX.m3u8
[debug] Command-line config: ['-vU', '--no-config', '--', 'https://d2vjef5jvl6bfs.cloudfront.net/198486c3ab50d176b772_djmiyuki_46104209485_1649379608/chunked/index-muted-ZUTW53NYZX.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.16.1-arch1-1-x86_64-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://d2vjef5jvl6bfs.cloudfront.net/198486c3ab50d176b772_djmiyuki_46104209485_1649379608/chunked/index-muted-ZUTW53NYZX.m3u8
[generic] index-muted-ZUTW53NYZX: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] index-muted-ZUTW53NYZX: Downloading webpage
[debug] Identified a M3U playlist
[generic] index-muted-ZUTW53NYZX: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] index-muted-ZUTW53NYZX: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://d2vjef5jvl6bfs.cloudfront.net/198486c3ab50d176b772_djmiyuki_46104209485_1649379608/chunked/index-muted-ZUTW53NYZX.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 727
[download] Destination: index-muted-ZUTW53NYZX [index-muted-ZUTW53NYZX].mp4
[download] 100% of 5.40GiB in 02:17
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:index-muted-ZUTW53NYZX [index-muted-ZUTW53NYZX].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "index-muted-ZUTW53NYZX [index-muted-ZUTW53NYZX].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:index-muted-ZUTW53NYZX [index-muted-ZUTW53NYZX].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:index-muted-ZUTW53NYZX [index-muted-ZUTW53NYZX].temp.mp4'
```
</details>

<details>
<summary>Downloading via `index-dvr.m3u8` (broken)</summary>

```
$ yt-dlp -vU --no-config -- https://d2vjef5jvl6bfs.cloudfront.net/198486c3ab50d176b772_djmiyuki_46104209485_1649379608/chunked/index-dvr.m3u8
[debug] Command-line config: ['-vU', '--no-config', '--', 'https://d2vjef5jvl6bfs.cloudfront.net/198486c3ab50d176b772_djmiyuki_46104209485_1649379608/chunked/index-dvr.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.16.1-arch1-1-x86_64-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://d2vjef5jvl6bfs.cloudfront.net/198486c3ab50d176b772_djmiyuki_46104209485_1649379608/chunked/index-dvr.m3u8
[generic] index-dvr: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] index-dvr: Downloading webpage
[debug] Identified a M3U playlist
[generic] index-dvr: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] index-dvr: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://d2vjef5jvl6bfs.cloudfront.net/198486c3ab50d176b772_djmiyuki_46104209485_1649379608/chunked/index-dvr.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 727
[download] Destination: index-dvr [index-dvr].mp4
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 37 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 37 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 37 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 37 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 37 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 37 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 37 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 37 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 37 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 37 (attempt 10 of 10) ...
ERROR: 'fragment_filename_sanitized'
Traceback (most recent call last):
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2648, in process_video_result
    self.process_info(new_info)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3138, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2846, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/downloader/hls.py", line 358, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 531, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 144, in _read_fragment
    down, frag_sanitized = self.sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
KeyError: 'fragment_filename_sanitized'
```

The bad error message on a failed fragment appears to be a regression, but it's unrelated to the core complaint here.
</details>

**Comment by pukkandan** [comment]
When passing an m3u8 directly, you are asking yt-dlp to download from that manifest as-is. We cannot do any processing on it.

> or a discussion of alternatives.

Just pass the video URL?
