### ISSUE TITLE
onf.ca - French version of NFB - site support request

### ISSUE THREAD

**Issue by jfcaron3** [yt-dlp/yt-dlp#8198]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

A given video on Canada's National Film Board of Canada website is downloadable if it's on the english NFB.ca website, but the same video is not downloadable on the french ONF.ca.  yt-dlp tries to download the ONF video with the generic extractor, while the NFB one uses an NFB-specific extractor.  Both should use the NFB extractor.

https://www.nfb.ca/film/north-star-episode-1-observation/
https://www.onf.ca/film/etoile-du-nord-episode-1-lobservation/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ /usr/local/bin/yt-dlp -vU https://www.onf.ca/film/etoile-du-nord-episode-1-lobservation/
[debug] Command-line config: ['-vU', 'https://www.onf.ca/film/etoile-du-nord-episode-1-lobservation/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-83-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, secretstorage-3.3.1, sqlite3-3.37.2
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 9c32c2f215a58c33369ec6105b7e97871905b8d757407bea2bc71d265f9f6cfe
yt-dlp is up to date (stable@2023.09.24)
[generic] Extracting URL: https://www.onf.ca/film/etoile-du-nord-episode-1-lobservation/
[generic] etoile-du-nord-episode-1-lobservation: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] etoile-du-nord-episode-1-lobservation: Extracting information
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[generic] Extracting URL: https:///film/etoile-du-nord-episode-1-lobservation/embed/player/
[generic] player: Downloading webpage
ERROR: [generic] Unable to download webpage: <urlopen error no host given> (caused by TransportError('<urlopen error no host given>'))
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2430, in _real_extract
    full_response = self._request_webpage(url, video_id, headers={
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 410, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "/usr/lib/python3.10/urllib/request.py", line 516, in open
    req = meth(req)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 146, in http_request
    return super().do_request_(req)
  File "/usr/lib/python3.10/urllib/request.py", line 1272, in do_request_
    raise URLError('no host given')
urllib.error.URLError: <urlopen error no host given>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4051, in urlopen
    return self._request_director.send(req)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 425, in _send
    raise TransportError(cause=e) from e
yt_dlp.networking.exceptions.TransportError: <urlopen error no host given>

# Output when using the english site:
$ /usr/local/bin/yt-dlp -vU https://www.nfb.ca/film/north-star-episode-1-observation/
[debug] Command-line config: ['-vU', 'https://www.nfb.ca/film/north-star-episode-1-observation/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-83-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, secretstorage-3.3.1, sqlite3-3.37.2
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 9c32c2f215a58c33369ec6105b7e97871905b8d757407bea2bc71d265f9f6cfe
yt-dlp is up to date (stable@2023.09.24)
[NFB] Extracting URL: https://www.nfb.ca/film/north-star-episode-1-observation/
[NFB] north-star-episode-1-observation: Downloading webpage
[NFB] north-star-episode-1-observation: Downloading webpage
[NFB] north-star-episode-1-observation: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] north-star-episode-1-observation: Downloading 1 format(s): 15596
[debug] Invoking hlsnative downloader on "https://dcly21uuqtecw.cloudfront.net/hls/1021830_1026168_DM-15029/1021830_1026168_DM-15029_2160p/15Mps.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 267
[download] Destination: North Star - Episode 1 ： Observation [north-star-episode-1-observation].mp4
[download]   5.4% of ~   1.82GiB at    1.09MiB/s ETA 27:02 (frag 14/267)^C
ERROR: Interrupted by user
```

**Comment by bashonly** [comment]
Error is occurring because a bad URL is extracted here:

> [debug] Identified a twitter:player iframe
> [generic] Extracting URL: https:///film/etoile-du-nord-episode-1-lobservation/embed/player/

because that's exactly what's found in the webpage:
```html
<meta name="twitter:player" content="https:///film/etoile-du-nord-episode-1-lobservation/embed/player/">
```

But even If I try passing `https://www.onf.ca/film/etoile-du-nord-episode-1-lobservation/embed/player/` to yt-dlp, it still can't extract any embeds

Conclusion: the site needs its own dedicated extractor

**Comment by vctls** [comment]
In the meantime, you can fetch the m3u8 URL from the network inspector and use that instead of the page URL.
