### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory" appears when downloading a YouTube playlist with thumbnails

### ISSUE THREAD

**Issue by FaithfulObserver** [yt-dlp/yt-dlp#8203]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Indonesia

### Provide a description that is worded well enough to be understood

When downloading YouTube playlist thumbnails, a FileNotFoundError message appears and the download process stops. This error does not occur if one of the following conditions are met:
1. The target output path folder is created manually first, not relying on Yt-dlp to create it.
2. Without using the --write-thumbnail parameter when downloading a YouTube playlist.
3. Downgrade yt-dlp to version 2023.06.22

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--yes-playlist', 'https://www.youtube.com/watch?v=wNoVFDDSqB0&list=PLSMVvri4yXjiimb1X3phH4MQAAfeZUgBR&pp=iAQB', '-i', '-f', 'bv*[height=1080][ext=mp4]+ba[ext=m4a]/bv*[height<=1080][ext=mp4]+ba[ext=m4a]/b[height<=1080][ext=mp4]', '--write-subs', '--sub-langs', 'en,id,-live_chat', '--convert-subs', 'srt', '--write-thumbnail', '--abort-on-unavailable-fragment', '--no-mtime', '--add-metadata', '--extractor-args', 'youtube:player-client=web', '--downloader', 'aria2c', '--downloader-args', 'aria2c:-x 16 -k 1M --max-overall-download-limit=6451K --auto-file-renaming', '-r', '6.3M', '--cookies-from-browser', 'brave', '--progress', '--progress-template', 'download-title:(progress.eta)s', '-o', 'D:\\Users\\Supervisor\\Downloads\\Video\\%(channel)s\\%(playlist_title)s\\%(title)s (%(upload_date)s).%(ext)s']
Extracting cookies from brave
[debug] Extracting cookies from: "C:\Users\Supervisor\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Supervisor\AppData\Local\BraveSoftware\Brave-Browser\User Data\Local State"
Extracted 2705 cookies from brave
[debug] cookie version breakdown: {'v10': 2705, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-34-g3d5edb89e7-20230924 (setts), ffprobe n6.0-34-g3d5edb89e7-20230924, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=wNoVFDDSqB0&list=PLSMVvri4yXjiimb1X3phH4MQAAfeZUgBR&pp=iAQB
[youtube:tab] Downloading playlist PLSMVvri4yXjiimb1X3phH4MQAAfeZUgBR - add --no-playlist to download just the video wNoVFDDSqB0
[youtube:tab] PLSMVvri4yXjiimb1X3phH4MQAAfeZUgBR: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLSMVvri4yXjiimb1X3phH4MQAAfeZUgBR
[youtube:tab] PLSMVvri4yXjiimb1X3phH4MQAAfeZUgBR: Downloading webpage
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] PLSMVvri4yXjiimb1X3phH4MQAAfeZUgBR: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Gel Pens
[info] Downloading playlist thumbnail 3 ...
[info] Writing playlist thumbnail 3 to: D:\Users\Supervisor\Downloads\Video\JetPens\Gel Pens\Gel Pens (NA).jpg
ERROR: [Errno 2] No such file or directory: 'D:\\Redacted\\Video\\JetPens\\Gel Pens\\Gel Pens (NA).jpg'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1852, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1950, in __process_playlist
  File "yt_dlp\YoutubeDL.py", line 4257, in _write_thumbnails
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Users\\Supervisor\\Downloads\\Video\\JetPens\\Gel Pens\\Gel Pens (NA).jpg'
```

**Comment by bashonly** [comment]
2023.07.06 also warns and continues instead of erroring

**Comment by bashonly** [comment]
Appears to be a regresssion in 227bf1a33be7b89cd7d44ad046844c4ccba104f4

Not sure yet how or why

Difference in behavior can be demonstrated with this command (assuming you don't have pre-existing folders with the channel/playlist names)
```
yt-dlp -v -o "./%(channel)s/%(playlist_title)s/%(title)s.%(ext)s" --write-thumbnail -I0 "https://www.youtube.com/watch?v=wNoVFDDSqB0&list=PLSMVvri4yXjiimb1X3phH4MQAAfeZUgBR"
```

**Comment by bashonly** [comment]
#7985 attempts to fix this by creating the directory/directories

**Comment by bashonly** [comment]
I'm guessing the previous behavior was actually unintended/unexpected, since this is what would restore it:
```diff
diff --git a/yt_dlp/networking/exceptions.py b/yt_dlp/networking/exceptions.py
index f58dc246e..caf4bce6a 100644
--- a/yt_dlp/networking/exceptions.py
+++ b/yt_dlp/networking/exceptions.py
@@ -1,5 +1,6 @@
 from __future__ import annotations
 
+import socket
 import typing
 import urllib.error
 
@@ -214,4 +215,4 @@ def __repr__(self):
         return repr(self._http_error)
 
 
-network_exceptions = (HTTPError, TransportError)
+network_exceptions = (HTTPError, TransportError, socket.error)
```

I think a proper fix would be #7985

**Comment by coletdjnz** [comment]
> I'm guessing the previous behavior was actually unintended/unexpected, since this is what would restore it:
> ```diff
> diff --git a/yt_dlp/networking/exceptions.py b/yt_dlp/networking/exceptions.py
> index f58dc246e..caf4bce6a 100644
> --- a/yt_dlp/networking/exceptions.py
> +++ b/yt_dlp/networking/exceptions.py
> @@ -1,5 +1,6 @@
>  from __future__ import annotations
>  
> +import socket
>  import typing
>  import urllib.error
>  
> @@ -214,4 +215,4 @@ def __repr__(self):
>          return repr(self._http_error)
>  
>  
> -network_exceptions = (HTTPError, TransportError)
> +network_exceptions = (HTTPError, TransportError, socket.error)
> ```
> 
> I think a proper fix would be #7985

socket.error should not be raised above the networking stack. it would be TransportError

**Comment by bashonly** [comment]
I'm not suggesting that as the fix. But `socket.error` was included in `network_exceptions` before network rework, hence the change in behavior / "regression"

**Comment by coletdjnz** [comment]
> I'm not suggesting that as the fix. But `socket.error` was included in `network_exceptions` before network rework, hence the change in behavior / "regression"

😕 socket.error should be mapped to TransportError now. no such concept of it exists outside the handlers

**Comment by bashonly** [comment]
Somehow handling `socket.error` was catching all `OSError`s

**Comment by coletdjnz** [comment]
> Somehow handling `socket.error` was catching all `OSError`s

right. socket.error is OSError.

**Comment by bashonly** [comment]
and this is what `network_exceptions` was before network rework
https://github.com/yt-dlp/yt-dlp/blob/1ba6fe9db5f660d5538588315c23ad6cf0371c5f/yt_dlp/utils/_utils.py#L1062-L1065

I'm just trying to show what caused the change in behavior. Again, I think the proper fix is #7985

**Comment by danfiscus** [comment]
I am on the latest release and still experiencing this issue. I tried switching to atomicparsley and it is still occurring. Are there other workarounds or possibly something else I'm missing? Or should I open a new issue?

**Comment by bashonly** [comment]
@danfiscus share a verbose log please

**Comment by danfiscus** [comment]
@bashonly here is the debug output, I stopped running the command after the second video in the playlist as the first video typically has no issue with the embedded thumbnail. I did replace any instances of my IP address in the output below with 99.99.99.99 for privacy reasons.

```
PS D:\Binge\TDV> yt-dlp --embed-subs --sub-lang en,en-GB,fr --embed-thumbnail --add-metadata --output "%(autonumber)03d (S%(season_number)02dE%(episode_number)02d) %(title)s %(id)s" --merge-output-format mkv --recode-video mp4 -vU --postprocessor-args ffmpeg:"-vcodec hevc_nvenc" https://www.youtube.com/playlist?list=PLYFrzR4gzEPdnSSnYhSzIzqjIwBSujUwh > debug.txt
[debug] Command-line config: ['--embed-subs', '--sub-lang', 'en,en-GB,fr', '--embed-thumbnail', '--add-metadata', '--output', '%(autonumber)03d (S%(season_number)02dE%(episode_number)02d) %(title)s %(id)s', '--merge-output-format', 'mkv', '--recode-video', 'mp4', '-vU', '--postprocessor-args', 'ffmpeg:-vcodec hevc_nvenc', 'https://www.youtube.com/playlist?list=PLYFrzR4gzEPdnSSnYhSzIzqjIwBSujUwh']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen cp1252 (No VT)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Skipping writing playlist thumbnail
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=oIYcbJKSLxQ&ei=iiGfZcu5HPDAy_sP59ORoAQ&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1704952826&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cxoaf&signature=19AD5EA9FB8D4FB61C038DDC9833BD2A2CEED1D1.8B95BE15C2A58F37406AD982A11CDD0418CEB7BA&key=yt8&lang=en&fmt=vtt"
[debug] File locking is not supported. Proceeding without locking
[debug] Invoking http downloader on "https://rr3---sn-8xgp1vo-2iae7.googlevideo.com/videoplayback?expire=1704949227&ei=iiGfZdzNPL--_9EPnrmkwAw&ip=99.99.99.99&id=o-AFqFPoC6EFhw0SVQkv3b16Gevmml29mzE7ZxAbPbzjK9&itag=247&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=XP&mm=31%2C29&mn=sn-8xgp1vo-2iae7%2Csn-8xgp1vo-ab56&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1047500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=177168658&dur=1117.950&lmt=1540973926950487&mt=1704926929&fvip=7&keepalive=yes&fexp=24007246&c=IOS&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAPpNnSLA9poj3zf03Uoc0H6Gsvmq7C4xBKWD_1VjuQMZAiEA7gP99v0KMUef00v5Jy_8Nx_D46Wgsh294LH2GFcV5Xw%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIgKHw1pY3UnhcBcqnjdZUsbDstRIjkfaI7Psuw4kj1W_4CIQCPHus9lc_I_MRtK_C3_JGDJcZ5rlNORIWVWYQq9ASpDA%3D%3D"
[debug] Invoking http downloader on "https://rr3---sn-8xgp1vo-2iae7.googlevideo.com/videoplayback?expire=1704949227&ei=iyGfZb6GCp2I_9EP7-SAiAM&ip=99.99.99.99&id=o-AL1IWX03kVG8Fvv-cT_91D4UBlMXFLm1vOHn1e432AOO&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=XP&mm=31%2C29&mn=sn-8xgp1vo-2iae7%2Csn-8xgp1vo-ab56&ms=au%2Crdu&mv=m&mvi=3&pl=21&initcwndbps=1047500&spc=UWF9f-OugSX83WWhOvh2qJYNYZLQOW5MhUNy&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=20673005&dur=1118.021&lmt=1540975931075711&mt=1704926929&fvip=7&keepalive=yes&fexp=24007246&c=ANDROID&txp=5411222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAP4t3KJp66vYWgzc4KI2mwpUND2xQl9zXq5pndkx9lzUAiBRj0pnJIjAondDUFasmAdyxHmLYch0xkOVAKM4lRncwA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRAIgC0oTOHWksBi-W3b7eHunFouNE_KtpUgavnV1lmSZrIMCIDGToEy3bvLG6I7eEoab6yIxHqjypQk7jJeDZ9lLr39y"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:001 (S01E01) The Big Lobster and Drive-through Booze： Citation Needed 1x01 oIYcbJKSLxQ.f247.webm" -i "file:001 (S01E01) The Big Lobster and Drive-through Booze： Citation Needed 1x01 oIYcbJKSLxQ.f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" -vcodec hevc_nvenc "file:001 (S01E01) The Big Lobster and Drive-through Booze： Citation Needed 1x01 oIYcbJKSLxQ.temp.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:001 (S01E01) The Big Lobster and Drive-through Booze： Citation Needed 1x01 oIYcbJKSLxQ.mkv" -map 0 -dn -ignore_unknown -movflags "+faststart" -vcodec hevc_nvenc "file:001 (S01E01) The Big Lobster and Drive-through Booze： Citation Needed 1x01 oIYcbJKSLxQ.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:001 (S01E01) The Big Lobster and Drive-through Booze： Citation Needed 1x01 oIYcbJKSLxQ.mp4" -i "file:001 (S01E01) The Big Lobster and Drive-through Booze： Citation Needed 1x01 oIYcbJKSLxQ.en.vtt" -map 0 -dn -ignore_unknown -c copy "-c:s" mov_text -map "-0:s" -map "1:0" "-metadata:s:s:0" "language=eng" "-metadata:s:s:0" "handler_name=English" "-metadata:s:s:0" "title=English" -movflags "+faststart" -vcodec hevc_nvenc "file:001 (S01E01) The Big Lobster and Drive-through Booze： Citation Needed 1x01 oIYcbJKSLxQ.temp.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:001 (S01E01) The Big Lobster and Drive-through Booze： Citation Needed 1x01 oIYcbJKSLxQ.mp4" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=The Big Lobster and Drive-through Booze: Citation Needed 1x01" -metadata "date=20140319" -metadata "description=http://techdif.co.uk - In the series premiere, Gary, Chris and Matt are faced with two challenges: first, a Big Lobster, and second, trying not to offend Australians too much." -metadata "synopsis=http://techdif.co.uk - In the series premiere, Gary, Chris and Matt are faced with two challenges: first, a Big Lobster, and second, trying not to offend Australians too much." -metadata "purl=https://www.youtube.com/watch?v=oIYcbJKSLxQ" -metadata "comment=https://www.youtube.com/watch?v=oIYcbJKSLxQ" -metadata "artist=Tom Scott" -metadata "show=Citation Needed" -metadata "season_number=1" -metadata "episode_id=Episode 1" -metadata "episode_sort=1" "-metadata:s:1" "language=eng" -movflags "+faststart" -vcodec hevc_nvenc "file:001 (S01E01) The Big Lobster and Drive-through Booze： Citation Needed 1x01 oIYcbJKSLxQ.temp.mp4"
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=XrCJJP_KOlY&ei=SSKfZauXN62I_9EPjeej-AI&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1704953017&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cxoaf&signature=6A4309CC2036175C0966A1985586734A1B2AD4D5.2431881083909DE9EE48EEAC7C9723447888F682&key=yt8&lang=en&fmt=vtt"
[debug] Invoking http downloader on "https://rr6---sn-8xgp1vo-2iae7.googlevideo.com/videoplayback?expire=1704949418&ei=SiKfZfLwHMOo_9EP7oiw2Aw&ip=99.99.99.99&id=o-AD7E0Pn7vOKT8xAbVn6jop5hejpNOR9lrXU2xRt10lP5&itag=247&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=0Z&mm=31%2C29&mn=sn-8xgp1vo-2iae7%2Csn-8xgp1vo-xfge&ms=au%2Crdu&mv=m&mvi=6&pl=21&pcm2=no&initcwndbps=1052500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=142784822&dur=920.720&lmt=1540489855637653&mt=1704927405&fvip=2&keepalive=yes&fexp=24007246&c=IOS&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cpcm2%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhANKJDkflEIR1IvJ2ZHwjd9OtruDfulUXdIc8ixizBbrPAiEAgkeIER6AiGe5W0YQF0bGcQCNL0COTAR689Oku3ZhnxQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRAIgScvLRR2WNo55oiF-fJiN7Ot1yKm8u6VX-He0yhnsslcCIHTiKQZoWyh-ZiC6g-CRw-Rh-TuuJEyy-Yw5ULvxKyhj"
[debug] Invoking http downloader on "https://rr6---sn-8xgp1vo-2iae7.googlevideo.com/videoplayback?expire=1704949418&ei=SiKfZanpJMWO_9EPor6KiAE&ip=99.99.99.99&id=o-AGp-aoYjb30-h1DA-f1il89MnC0XYBtiLRgMuIF9uv0O&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=0Z&mm=31%2C29&mn=sn-8xgp1vo-2iae7%2Csn-8xgp1vo-xfge&ms=au%2Crdu&mv=m&mvi=6&pl=21&initcwndbps=1052500&spc=UWF9fxwcRPexH1o-mgMoC5YlnlfskPYjX-Nw&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=16873336&dur=920.781&lmt=1540490774870147&mt=1704927405&fvip=2&keepalive=yes&fexp=24007246&c=ANDROID&txp=5411222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAP3y1Hm9JgvB9C5O8SQW8e7i-fl9Cx8DRfr4p45llj7bAiEAoQ9idHtWhxhxUEY17bKDwIjOslSfWPxsA20emxhvCQE%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIgdPhPcl09rn1gQGNk-aQH2AMeYc0jKcdBezY38LBgilwCIQCXqLwwpqbKzDmI-8zUt5iTZGIREf4D3WObcEAbSrToMQ%3D%3D"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.f247.webm" -i "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" -vcodec hevc_nvenc "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.temp.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.mkv" -map 0 -dn -ignore_unknown -movflags "+faststart" -vcodec hevc_nvenc "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.mp4" -i "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.en.vtt" -map 0 -dn -ignore_unknown -c copy "-c:s" mov_text -map "-0:s" -map "1:0" "-metadata:s:s:0" "language=eng" "-metadata:s:s:0" "handler_name=English" "-metadata:s:s:0" "title=English" -movflags "+faststart" -vcodec hevc_nvenc "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.temp.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.mp4" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=The Newgate Novel and Condiments on Toast: Citation Needed 1x02" -metadata "date=20140326" -metadata "description=http://techdif.co.uk - We're going highbrow this week. Or at least, we're trying to. It all falls apart when Matt suggests some unusual toast preferences." -metadata "synopsis=http://techdif.co.uk - We're going highbrow this week. Or at least, we're trying to. It all falls apart when Matt suggests some unusual toast preferences." -metadata "purl=https://www.youtube.com/watch?v=XrCJJP_KOlY" -metadata "comment=https://www.youtube.com/watch?v=XrCJJP_KOlY" -metadata "artist=Tom Scott" -metadata "show=Citation Needed" -metadata "season_number=1" -metadata "episode_id=Episode 2" -metadata "episode_sort=2" -movflags "+faststart" -vcodec hevc_nvenc "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.temp.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -f image2 -pattern_type none -i "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.webp" -update 1 -movflags "+faststart" -vcodec hevc_nvenc "file:002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.png"
WARNING: unable to embed using mutagen; None
[debug] AtomicParsley command line: AtomicParsley "002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.mp4" --artwork "002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.png" -o "002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.temp.mp4"
WARNING: Unable to embed thumbnails using AtomicParsley;
ERROR: [WinError 2] The system cannot find the file specified: '002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.temp.mp4' -> '002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.mp4'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1743, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1802, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2952, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3495, in process_info
  File "yt_dlp\YoutubeDL.py", line 3675, in post_process
  File "yt_dlp\YoutubeDL.py", line 3657, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3635, in run_pp
  File "yt_dlp\postprocessor\common.py", line 23, in run
  File "yt_dlp\postprocessor\common.py", line 128, in wrapper
  File "yt_dlp\postprocessor\embedthumbnail.py", line 219, in run
FileNotFoundError: [WinError 2] The system cannot find the file specified: '002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.temp.mp4' -> '002 (S01E02) The Newgate Novel and Condiments on Toast： Citation Needed 1x02 XrCJJP_KOlY.mp4'
```

**Comment by bashonly** [comment]
@danfiscus your issue appears to be completely unrelated. Mutagen is failing to embed the thumbnail into the mp4; but it's not clear from your log exactly why. It should be noted that you are re-encoding the video as many as 3 times; your postprocessor-args are being applied to *every* ffmpeg PP since you are not specifying *which* PP the args should be applied to. To troubleshoot this, first try removing all your postprocessing options besides `--embed-thumbnail`. It should succeed on the first run. Then add each option back, 1 by 1, until you find the problematic opt

**Comment by danfiscus** [comment]
@bashonly Thank you very much for the information. I did run again without any pp args and it runs fine now. I also discovered that with the hardware acceleration ffmpeg flags off, the resulting video file is smaller in size, so nothing lost there after all (except the longer encode times).
