### ISSUE TITLE
A&E download fails using xfinity signon

### ISSUE THREAD

**Issue by GarrySmithwick** [yt-dlp/yt-dlp#8209]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Trying to download from A&E using xfinity credentials fails

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Running Windows 10

 Download video: https://play.aetv.com/shows/the-first-48/season-9/episode-6

 Available version: stable@2023.09.24, Current version: stable@2023.09.24
 yt-dlp is up to date (stable@2023.09.24)


 using my Xfinity userid & password


 command: yt-dlp.exe "https://play.aetv.com/shows/the-first-48/season-9/episode-6" --verbose
          --ap-mso "Comcast_SSO" --ap-username "myuserid" --ap-password "mypassword" --windows-filenames
          --windows-filenames --restrict-filenames --print-to-file "%(_filename)q" downloadlog.txt



 ERROR: [aenetworks] shows/the-first-48/season-9/episode-6: Unable to download webpage:
        HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>);
        please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= ,
        filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

[debug] Command-line config:['https://play.aetv.com/shows/the-first-48/season-9/episode-6', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--verbose', '--windows-filenames', '--restrict-filenames', '--print-to-file', '%(_filename)q', 'downloadlog.txt']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24[088add956] (win32_dir)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.3, ffprobe 5.1.2-essentials_build-www.gyan.dev, rtmpdump 2.3
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[aenetworks] Extracting URL: https://play.aetv.com/shows/the-first-48/season-9/episode-6
[aenetworks] /shows/the-first-48/season-9/episode-6: Downloading JSON metadata
[aenetworks] 17127088: Downloading JSON metadata
[aenetworks] 17127088: Downloading Provider Redirect Page
[aenetworks] 17127088: Logging in
[aenetworks] 17127088: Retrieving Session

ERROR:[aenetworks] shows/the-first-48/season-9/episode-6: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
File "yt_dlp\extractor\common.py", line 715, in extract
File "yt_dlp\extractor\aenetworks.py", line 181, in _real_extract
File "yt_dlp\extractor\aenetworks.py", line 97, in _extract_aetn_info
File "yt_dlp\extractor\adobepass.py", line 1720, in _extract_mvpd_auth
File "yt_dlp\extractor\common.py", line 1118, in _download_webpage
File "yt_dlp\extractor\common.py", line 1069, in download_content
File "yt_dlp\extractor\adobepass.py", line 1366, in _download_webpage_handle
File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
File "yt_dlp\extractor\common.py", line 860, in _request_webpage

File "yt_dlp\networking\_urllib.py", line 410, in _send
File "urllib\request.py", line 531, in open
File "urllib\request.py", line 640, in http_response
File "urllib\request.py", line 569, in error
File "urllib\request.py", line 502, in _call_chain
File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
File "yt_dlp\networking\common.py", line 114, in send
File "yt_dlp\networking\_helper.py", line 204, in wrapper
File "yt_dlp\networking\common.py", line 325, in send
File "yt_dlp\networking\_urllib.py", line 415, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "yt_dlp\extractor\common.py", line 847, in _request_webpage
File "yt_dlp\YoutubeDL.py", line 4070, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 401: Unauthorized
```

**Comment by bashonly** [comment]
Try not passing the `--ap-password` option and instead entering it interactively; this can prevent unwanted escaping of special characters in your password

If that doesn't work, you could try the patch suggested here https://github.com/yt-dlp/yt-dlp/issues/516#issuecomment-1701970545

**Comment by GarrySmithwick** [comment]
I tried leaving out the password and I get the message:  Type TV provider account password and press [Return]:

I type in the password, but I do not see what I am typing.  The cursor just stays in one place and no characters appear when typed.

And it still failed.

I will try the suggested patch maybe tomorrow.

**Comment by bashonly** [comment]
>  but I do not see what I am typing

There is no echo as a security measure

**Comment by GarrySmithwick** [comment]
I thought that might be the case, but was not sure.

I looked at the patch.  No exactly sure have to apply it to me Windows version.  I will look at it more tomorrow.

Thanks

**Comment by GarrySmithwick** [comment]
Is there an "easy" to apply this patch on Windows?  I did not install via Python.

**Comment by GarrySmithwick** [comment]
Guess there is no way for me to try the patch.

**Comment by Mr-Jake** [comment]
The "patch" can't be applied to the exe.

But you can do it yourself. Download the yt-dlp source code to a folder on your computer and replace the line of code in the file adobepass.py. Install Python and use the command prompt to run the source code that you downloaded and modified. It will work the same way as the exe in terms of usage. There is documentation on the site on how to do it.

**Comment by bashonly** [comment]
@GarrySmithwick

Here is a patched build: https://github.com/bashonly/yt-dlp/releases/tag/2023.10.03.000547

or you can just run:
```
yt-dlp --update-to bashonly/yt-dlp@2023.10.03.000547
```

**Comment by GarrySmithwick** [comment]
The patch build works if I enter the password manually.

Thanks

**Comment by bashonly** [comment]
show a verbose log; add `-v` to your command

**Comment by GarrySmithwick** [comment]
Show Name: The First 48 - 24x02
Download video: https://play.aetv.com/shows/the-first-48/season-24/episode-2

  [debug] Command-line config: ['https://play.aetv.com/shows/the-first-48/season-24/episode-2', '-v', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--windows-filenames', '--restrict-filenames', '--print-to-file', '%(_filename)q', 'downloadlog.txt']
  Type TV provider account password and press [Return]:
  [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
  [debug] yt-dlp version stable@2023.10.03.000547 [fb37a08f9] (win32_dir)
  [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
  [debug] exe versions: ffmpeg 4.2.3, ffprobe 5.1.2-essentials_build-www.gyan.dev, rtmpdump 2.3
  [debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
  [debug] Proxy map: {}
  [debug] Loaded 1886 extractors
  [aenetworks] Extracting URL: https://play.aetv.com/shows/the-first-48/season-24/episode-2
  [aenetworks] /shows/the-first-48/season-24/episode-2: Downloading JSON metadata
  [aenetworks] 2266965571797: Downloading JSON metadata
  [aenetworks] 2266965571797: Downloading Provider Redirect Page
  [aenetworks] 2266965571797: Logging in
  [aenetworks] 2266965571797: Retrieving Session
  ERROR: [aenetworks] shows/the-first-48/season-24/episode-2: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\aenetworks.py", line 181, in _real_extract
  File "yt_dlp\extractor\aenetworks.py", line 97, in _extract_aetn_info
  File "yt_dlp\extractor\adobepass.py", line 1720, in _extract_mvpd_auth
  File "yt_dlp\extractor\common.py", line 1118, in _download_webpage
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\adobepass.py", line 1366, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage

  File "yt_dlp\networking\_urllib.py", line 410, in _send
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
  urllib.error.HTTPError: HTTP Error 401:

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 415, in _send
  yt_dlp.networking.exceptions.HTTPError: HTTP Error 401: Unauthorized

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4070, in urlopen
  yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 401: Unauthorized

**Comment by bashonly** [comment]
The patch doesn't seem to be making any difference in the above log, the code path that it tries to open up isn't being reached

**Comment by GarrySmithwick** [comment]
Sorry, I think I was mistaken when I said it worked once.  I think I was downloading from another site that does not require userid and password.  My bad.

**Comment by GarrySmithwick** [comment]
Can you post the exact command you are using (without id and pw of course).

I am able to logon to Xfinity and also A&E and watch the episode using my Xfinity signon.

**Comment by GarrySmithwick** [comment]
Also, CeruleanSky, are you running Windows?

**Comment by CeruleanSky** [comment]
`yt-dlp --ap-username PRIVATE --ap-password PRIVATE --ap-mso Comcast_SSO --verbose --list-formats https://play.aetv.com/shows/the-first-48/season-24/episode-2`
where PRIVATE are username and password accordingly, the same used to login to xfinity.

**Comment by GarrySmithwick** [comment]
CeruleanSky, I tried the exact format that you use and it still fails.

**Comment by GarrySmithwick** [comment]
I downloaded the latest build and tried a slightly different command.  Still fails.

Show Name: The First 48 - 24x02
Download video: https://play.aetv.com/shows/the-first-48/season-24/episode-2

yt-dlp.exe "https://play.aetv.com/shows/the-first-48/season-24/episode-2" -v --cookies-from-browser chrome --ap-mso "Comcast_SSO" --ap-username "xxxxxxxxxx" --windows-filenames --restrict-filenames --print-to-file "%(_filename)q" downloadlog.txt

 [debug] Command-line config: ['https://play.aetv.com/shows/the-first-48/season-24/episode-2', '-v', '--cookies-from-browser', 'chrome', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--windows-filenames', '--restrict-filenames', '--print-to-file', '%(_filename)q', 'downloadlog.txt']
 Type TV provider account password and press [Return]:
 Extracting cookies from chrome
 [debug] Extracting cookies from: "C:\Users\Garry\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
 [debug] Found local state file at "C:\Users\Garry\AppData\Local\Google\Chrome\User Data\Local State"
 Extracted 3159 cookies from chrome
 [debug] cookie version breakdown: {'v10': 3227, 'other': 0, 'unencrypted': 0}
 [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
 [debug] yt-dlp version stable@2023.10.07 [377e85a17] (win_exe)
 [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k 25 Mar 2021)
 [debug] exe versions: ffmpeg 4.2.3, ffprobe 5.1.2-essentials_build-www.gyan.dev, rtmpdump 2.3
 [debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
 [debug] Proxy map: {}
 [debug] Loaded 1886 extractors
 [aenetworks] Extracting URL: https://play.aetv.com/shows/the-first-48/season-24/episode-2
 [aenetworks] /shows/the-first-48/season-24/episode-2: Downloading JSON metadata
 [aenetworks] 2266965571797: Downloading JSON metadata
 [aenetworks] 2266965571797: Downloading Provider Redirect Page
 ERROR: [aenetworks] shows/the-first-48/season-24/episode-2: Unable to download webpage: The read operation timed out (caused by TransportError('The read operation timed out'))
 File "yt_dlp\extractor\common.py", line 715, in extract
 File "yt_dlp\extractor\aenetworks.py", line 181, in _real_extract
 File "yt_dlp\extractor\aenetworks.py", line 97, in _extract_aetn_info
 File "yt_dlp\extractor\adobepass.py", line 1448, in _extract_mvpd_auth
 File "yt_dlp\extractor\adobepass.py", line 1366, in _download_webpage_handle
 File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
 File "yt_dlp\extractor\common.py", line 860, in _request_webpage

 File "yt_dlp\networking\_urllib.py", line 410, in _send
 File "urllib\request.py", line 531, in open
 File "urllib\request.py", line 640, in http_response
 File "urllib\request.py", line 563, in error
 File "urllib\request.py", line 502, in _call_chain
 File "urllib\request.py", line 755, in http_error_302
 File "urllib\request.py", line 525, in open
 File "urllib\request.py", line 542, in _open
 File "urllib\request.py", line 502, in _call_chain
 File "yt_dlp\networking\_urllib.py", line 102, in https_open
 File "urllib\request.py", line 1358, in do_open
 File "http\client.py", line 1344, in getresponse
 File "http\client.py", line 307, in begin
 File "http\client.py", line 268, in _read_status
 File "socket.py", line 669, in readinto
 File "ssl.py", line 1241, in recv_into
 File "ssl.py", line 1099, in read
 socket.timeout: The read operation timed out

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
 File "yt_dlp\extractor\common.py", line 847, in _request_webpage
 File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
 File "yt_dlp\networking\common.py", line 114, in send
 File "yt_dlp\networking\_helper.py", line 204, in wrapper
 File "yt_dlp\networking\common.py", line 325, in send
 File "yt_dlp\networking\_urllib.py", line 433, in _send
 File "yt_dlp\networking\_urllib.py", line 345, in handle_response_read_exceptions
 yt_dlp.networking.exceptions.TransportError: The read operation

**Comment by bashonly** [comment]
Closing, can reopen if you experience the issue again
