### ISSUE TITLE
[BRIGHTEON] Support brighteon and fix bug preventing combining multiple formats from different html5 embeds

### ISSUE THREAD

**Issue by dmovztoq** [yt-dlp/yt-dlp#8214]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://www.brighteon.com/90b78697-72f1-4468-9972-e3a654bccebe
https://www.brighteon.com/channels/HFamily

### Provide a description that is worded well enough to be understood

1. yt-dlp falls back on generic extractor, giving it a hint that it's not specifically supported, 
2. The site has had changes backed infrastructural changes over the years so some of the information from older Issues may be obsolete
3. An older ticket asking for support has been closed without confirmation of support other than a message by the OP that due to a plugin it's "no longer necessary".
4. Each video is detected as 2 html5 embeds (playlists?)
5. There's an error with detecting the other embed when downloading a format from a different embed.
6. It's not possible to combine multiple formats if they're from different embeds, the download just fails on everything and reports errors. However combining from the same embed does work.
7. Channel links are not supported, no way to download all channel's videos as a playlist

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\yt-dlp>yt-dlp.exe -F -vU https://www.brighteon.com/90b78697-72f1-4468-9972-e3a654bccebe
[debug] Command-line config: ['-F', '-vU', 'https://www.brighteon.com/90b78697-72f1-4468-9972-e3a654bccebe']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111242-g1bcb8a7338-20230622 (setts), ffprobe N-111242-g1bcb8a7338-20230622
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[generic] Extracting URL: https://www.brighteon.com/90b78697-72f1-4468-9972-e3a654bccebe
[generic] 90b78697-72f1-4468-9972-e3a654bccebe: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 90b78697-72f1-4468-9972-e3a654bccebe: Extracting information
[debug] Looking for embeds
[html5] 90b78697-72f1-4468-9972-e3a654bccebe: Downloading m3u8 information
[html5] 90b78697-72f1-4468-9972-e3a654bccebe: Downloading MPD manifest
[debug] Identified 2 html5 embeds
[download] Downloading playlist: Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs
[generic] Playlist Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs: Downloading 2 items of 2
[download] Downloading item 1 of 2
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 90b78697-72f1-4468-9972-e3a654bccebe-1:
ID      EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC     ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────
3       m4a audio only     │   96k https │ audio only        mp4a.40.5  96k 48k DASH audio, m4a_dash
2       mp4 480x270        │  350k https │ avc1.4d401f  350k video only         DASH video, mp4_dash
hls-296 mp4 480x270     15 │  297k m3u8  │ avc1.4d401f       mp4a.40.5
1       mp4 960x540        │ 1500k https │ avc1.640028 1500k video only         DASH video, mp4_dash
hls-792 mp4 960x540     30 │  792k m3u8  │ avc1.4d401f       mp4a.40.5
[download] Downloading item 2 of 2
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 90b78697-72f1-4468-9972-e3a654bccebe-2:
ID EXT RESOLUTION │ PROTO │ VCODEC     ACODEC
──────────────────────────────────────────────
0  mp3 audio only │ https │ audio only unknown
[download] Finished downloading playlist: Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs

------------------------------------------
------------------------------------------

D:\yt-dlp>yt-dlp.exe -f 1+3 -vU https://www.brighteon.com/90b78697-72f1-4468-9972-e3a654bccebe
[debug] Command-line config: ['-f', '1+3', '-vU', 'https://www.brighteon.com/90b78697-72f1-4468-9972-e3a654bccebe']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111242-g1bcb8a7338-20230622 (setts), ffprobe N-111242-g1bcb8a7338-20230622
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[generic] Extracting URL: https://www.brighteon.com/90b78697-72f1-4468-9972-e3a654bccebe
[generic] 90b78697-72f1-4468-9972-e3a654bccebe: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 90b78697-72f1-4468-9972-e3a654bccebe: Extracting information
[debug] Looking for embeds
[html5] 90b78697-72f1-4468-9972-e3a654bccebe: Downloading m3u8 information
[html5] 90b78697-72f1-4468-9972-e3a654bccebe: Downloading MPD manifest
[debug] Identified 2 html5 embeds
[download] Downloading playlist: Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs
[generic] Playlist Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs: Downloading 2 items of 2
[download] Downloading item 1 of 2
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 90b78697-72f1-4468-9972-e3a654bccebe-1: Downloading 1 format(s): 1+3
[debug] Invoking http downloader on "https://video.brighteon.com/file/BTBucket-Prod/dash/1bbf9e3a-409f-46ae-b107-a35e07b31e72_540.mp4"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs (1) [90b78697-72f1-4468-9972-e3a654bccebe-1].f1.mp4
[download] 100% of  222.58MiB in 00:00:17 at 12.59MiB/s
[debug] Invoking http downloader on "https://video.brighteon.com/file/BTBucket-Prod/dash/1bbf9e3a-409f-46ae-b107-a35e07b31e72_audio.mp4"
[download] Destination: Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs (1) [90b78697-72f1-4468-9972-e3a654bccebe-1].f3.m4a
[download] 100% of   35.34MiB in 00:00:02 at 17.29MiB/s
[Merger] Merging formats into "Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs (1) [90b78697-72f1-4468-9972-e3a654bccebe-1].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs (1) [90b78697-72f1-4468-9972-e3a654bccebe-1].f1.mp4" -i "file:Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs (1) [90b78697-72f1-4468-9972-e3a654bccebe-1].f3.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs (1) [90b78697-72f1-4468-9972-e3a654bccebe-1].temp.mp4"
Deleting original file Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs (1) [90b78697-72f1-4468-9972-e3a654bccebe-1].f1.mp4 (pass -k to keep)
Deleting original file Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs (1) [90b78697-72f1-4468-9972-e3a654bccebe-1].f3.m4a (pass -k to keep)
[download] Downloading item 2 of 2
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [html5] 90b78697-72f1-4468-9972-e3a654bccebe-2: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 2028, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2883, in process_video_result
yt_dlp.utils.ExtractorError: [html5] 90b78697-72f1-4468-9972-e3a654bccebe-2: Requested format is not available. Use --list-formats for a list of available formats

[download] Finished downloading playlist: Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs

--------------------------------------
--------------------------------------

D:\yt-dlp>yt-dlp.exe -f 1+0 -vU https://www.brighteon.com/90b78697-72f1-4468-9972-e3a654bccebe
[debug] Command-line config: ['-f', '1+0', '-vU', 'https://www.brighteon.com/90b78697-72f1-4468-9972-e3a654bccebe']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111242-g1bcb8a7338-20230622 (setts), ffprobe N-111242-g1bcb8a7338-20230622
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[generic] Extracting URL: https://www.brighteon.com/90b78697-72f1-4468-9972-e3a654bccebe
[generic] 90b78697-72f1-4468-9972-e3a654bccebe: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 90b78697-72f1-4468-9972-e3a654bccebe: Extracting information
[debug] Looking for embeds
[html5] 90b78697-72f1-4468-9972-e3a654bccebe: Downloading m3u8 information
[html5] 90b78697-72f1-4468-9972-e3a654bccebe: Downloading MPD manifest
[debug] Identified 2 html5 embeds
[download] Downloading playlist: Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs
[generic] Playlist Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs: Downloading 2 items of 2
[download] Downloading item 1 of 2
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [html5] 90b78697-72f1-4468-9972-e3a654bccebe-1: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 2028, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2883, in process_video_result
yt_dlp.utils.ExtractorError: [html5] 90b78697-72f1-4468-9972-e3a654bccebe-1: Requested format is not available. Use --list-formats for a list of available formats

[download] Downloading item 2 of 2
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [html5] 90b78697-72f1-4468-9972-e3a654bccebe-2: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 2028, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2883, in process_video_result
yt_dlp.utils.ExtractorError: [html5] 90b78697-72f1-4468-9972-e3a654bccebe-2: Requested format is not available. Use --list-formats for a list of available formats

[download] Finished downloading playlist: Why Fruits & Vegetables Have Lost Their Vitamins - Documentary - HaloRockDocs

--------------------------------------
--------------------------------------

D:\yt-dlp>yt-dlp.exe -f 1+0 -vU https://www.brighteon.com/channels/HFamily
[debug] Command-line config: ['-f', '1+0', '-vU', 'https://www.brighteon.com/channels/HFamily']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111242-g1bcb8a7338-20230622 (setts), ffprobe N-111242-g1bcb8a7338-20230622
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[generic] Extracting URL: https://www.brighteon.com/channels/HFamily
[generic] HFamily: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] HFamily: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.brighteon.com/channels/HFamily
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.brighteon.com/channels/HFamily
```

**Comment by flashdagger** [comment]
referring to (3): The [brighteon plugin](https://pypi.org/project/ytdlp-brighteon/) might be an option and it's still supported for the current version of yt-dlp.
