### ISSUE TITLE
My ytdlp install is broken, already tried reinstalling but no luck. Python Error: „no closing quotation“. 

### ISSUE THREAD

**Issue by github-userx** [yt-dlp/yt-dlp#824]
Edited

**Comment by pukkandan** [comment]
One of your config file seems to be bad. Try `yt-dlp --no-config`

**Comment by github-userx** [comment]
@pukkandan oh wow that was quick response! :D yeah I just figured it out myself but thanks for confirming. It worked with —no-config and I then managed to fix my confit file. 

These python error messages are always irritating and confusing to me as a non-programmer :)

**Comment by pukkandan** [comment]
Dont remove the issue contents!

**Comment by github-userx** [comment]
apologies. I’ll add it back

**Comment by crumhirnd** [comment]
I'm having the same issue as well, how can I reset the config file?

**Comment by pukkandan** [comment]
delete the file...

**Comment by crumhirnd** [comment]
> delete the file...

where is the config file stored? I have installed yt-dlp into my user folder.

**Comment by pukkandan** [comment]
You don't know? You are the one that created the file... yt-dlp looks for config in quite a few places https://github.com/yt-dlp/yt-dlp#configuration

What exactly is the error you are getting? Show verbose log

**Comment by crumhirnd** [comment]
C:\Users\onelu>yt-dlp https://www.youtube.com/watch?v=Doe6OHHfvKs -v
Traceback (most recent call last):
  File "C:\Users\onelu\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\onelu\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\onelu\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
  File "C:\Users\onelu\lib\site-packages\yt_dlp\__init__.py", line 857, in main
    _real_main(argv)
  File "C:\Users\onelu\lib\site-packages\yt_dlp\__init__.py", line 807, in _real_main
    parser, opts, all_urls, ydl_opts = parse_options(argv)
  File "C:\Users\onelu\lib\site-packages\yt_dlp\__init__.py", line 610, in parse_options
    parser, opts, urls = parseOpts(argv)
  File "C:\Users\onelu\lib\site-packages\yt_dlp\options.py", line 99, in parseOpts
    if all(load_configs()):
  File "C:\Users\onelu\lib\site-packages\yt_dlp\options.py", line 95, in load_configs
    yield add_config('Home', expand_path(root.parse_args()[0].paths.get('home', '')).strip())
  File "C:\Users\onelu\lib\site-packages\yt_dlp\options.py", line 86, in add_config
    args = Config.read_file(current_path, default=None)
  File "C:\Users\onelu\lib\site-packages\yt_dlp\utils.py", line 5202, in read_file
    res = shlex.split(contents, comments=True)
  File "C:\Users\onelu\lib\shlex.py", line 315, in split
    return list(lex)
  File "C:\Users\onelu\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "C:\Users\onelu\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "C:\Users\onelu\lib\shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

C:\Users\onelu>yt-dlp https://www.youtube.com/watch?v=Doe6OHHfvKs --verbose
Traceback (most recent call last):
  File "C:\Users\onelu\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\onelu\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\onelu\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
  File "C:\Users\onelu\lib\site-packages\yt_dlp\__init__.py", line 857, in main
    _real_main(argv)
  File "C:\Users\onelu\lib\site-packages\yt_dlp\__init__.py", line 807, in _real_main
    parser, opts, all_urls, ydl_opts = parse_options(argv)
  File "C:\Users\onelu\lib\site-packages\yt_dlp\__init__.py", line 610, in parse_options
    parser, opts, urls = parseOpts(argv)
  File "C:\Users\onelu\lib\site-packages\yt_dlp\options.py", line 99, in parseOpts
    if all(load_configs()):
  File "C:\Users\onelu\lib\site-packages\yt_dlp\options.py", line 95, in load_configs
    yield add_config('Home', expand_path(root.parse_args()[0].paths.get('home', '')).strip())
  File "C:\Users\onelu\lib\site-packages\yt_dlp\options.py", line 86, in add_config
    args = Config.read_file(current_path, default=None)
  File "C:\Users\onelu\lib\site-packages\yt_dlp\utils.py", line 5202, in read_file
    res = shlex.split(contents, comments=True)
  File "C:\Users\onelu\lib\shlex.py", line 315, in split
    return list(lex)
  File "C:\Users\onelu\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "C:\Users\onelu\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "C:\Users\onelu\lib\shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

**Comment by pukkandan** [comment]
Check for a `yt-dlp.conf` file in the same folder as yt-dlp

**Comment by pukkandan** [comment]
Check `C:\Users\onelu\yt-dlp.conf`

**Comment by crumhirnd** [comment]
the file contains this:

yt-dlp --recode-video mp4 -o "C:\Users\onelu\Downloads\%(title)s [%(id)s].%(ext)s

**Comment by pukkandan** [comment]
> ValueError: No closing quotation

**Comment by crumhirnd** [comment]
Now I see it. Thanks for helping me.

But yt-dlp worked a few days ago. I'm very confused. I did not change the file at all.
