### ISSUE TITLE
Dailywire Error: No video formats found

### ISSUE THREAD

**Issue by BanishedSpectre** [yt-dlp/yt-dlp#8246]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

First two episodes downloaded fine; the rest of the episodes encountered an error [no video format found]. I can go back and re-download the first two episodes again.
DRM issue?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.dailywire.com/episode/ep-3-avery-s-niece-new']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-09-29-git-40aa451154-full_build-www.gyan.dev (setts), ffprobe 2023-09-29-git-40aa451154-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[DailyWire] Extracting URL: https://www.dailywire.com/episode/ep-3-avery-s-niece-new
[DailyWire] ep-3-avery-s-niece-new: Downloading webpage
ERROR: [DailyWire] clm8geguv3qku0870ewvcu0ed: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2751, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1076, in raise_no_formats
yt_dlp.utils.ExtractorError: [DailyWire] clm8geguv3qku0870ewvcu0ed: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by october262** [comment]
are you signed in into the website so that episode 3 & on will play ??

**Comment by BanishedSpectre** [comment]
> are you signed in into the website so that episode 3 & on will play ??

Yes and I was able to play them in the browser without issue. I also attempted —cookies-from-browser but received the same error (tried chrome and Firefox)

**Comment by bashonly** [comment]
share log with `--cookies-from-browser`

**Comment by BanishedSpectre** [comment]
`[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://www.dailywire.com/episode/ep-3-avery-s-niece-new']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Laythrom10-2\AppData\Roaming\Mozilla\Firefox\Profiles\cz0vdwrc.default-release\cookies.sqlite"
Extracted 651 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-09-29-git-40aa451154-full_build-www.gyan.dev (setts), ffprobe 2023-09-29-git-40aa451154-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[DailyWire] Extracting URL: https://www.dailywire.com/episode/ep-3-avery-s-niece-new
[DailyWire] ep-3-avery-s-niece-new: Downloading webpage
ERROR: [DailyWire] clm8geguv3qku0870ewvcu0ed: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2751, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1076, in raise_no_formats
yt_dlp.utils.ExtractorError: [DailyWire] clm8geguv3qku0870ewvcu0ed: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

**Comment by twiclo** [comment]
Same issue here:

```
[twiclo@momo shot]$ yt-dlp -vU --cookies-from-browser brave https://www.dailywire.com/episode/baby-s-first-shot-in-the-dark-hepatitis-b
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'brave', 'https://www.dailywire.com/episode/baby-s-first-shot-in-the-dark-hepatitis-b']
Extracting cookies from brave
[debug] Extracting cookies from: "/home/twiclo/.config/BraveSoftware/Brave-Browser/Default/Cookies"
Extracted 1860 cookies from brave
[debug] cookie version breakdown: {'v10': 1793, 'v11': 0, 'other': 0, 'unencrypted': 67}
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (zip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.4.15-100.fc37.x86_64-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3 (setts), ffprobe 5.1.3
[debug] Optional libraries: Cryptodome-3.17.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.45.1, sqlite3-3.40.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 9c32c2f215a58c33369ec6105b7e97871905b8d757407bea2bc71d265f9f6cfe
yt-dlp is up to date (stable@2023.09.24)
[DailyWire] Extracting URL: https://www.dailywire.com/episode/baby-s-first-shot-in-the-dark-hepatitis-b
[DailyWire] baby-s-first-shot-in-the-dark-hepatitis-b: Downloading webpage
ERROR: [DailyWire] clif2chzlknvx0742aus0m7ca: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [DailyWire] clif2chzlknvx0742aus0m7ca: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by emanueljg** [comment]
I encountered this issue as well on both latest stable and latest git. Using https://www.dailywire.com/show/exodus as an example, the first episode works but the rest does not.

I resorted to downloading the m3u8 manually, which does work:

1. Go to the episode you want to download, make sure you are logged in
2. Open devtools, go to Network tab
3. Look for GET request for the m3u8. It should start with `https://stream.media.dailywire.com/...` so you can search for `stream.media` in the search bar
4. Copy the request url.
5. Download the URL with `yt-dlp <URL>`. You will need to set an output format (`-o`) due to yt-dlp not being able to guess a name from the generic stream.

**Comment by twiclo** [comment]
Does that workaround still work for you @emanueljg? I'm not able to find a stream url. All I get are chunks.

**Comment by infogulch** [comment]
It seems dailywire has switched to fastly cdn for media streaming.

@emanueljg's workaround works for me after getting the correct URL from the Network tab, which looked like this in my case (with private data snipped out):

```
yt-dlp --cookies-from-browser firefox "https://manifest-gcp-us-east1-vop1.fastly.mux.com/[randomid]/rendition.m3u8?cdn=fastly&expires=[expires]&skid=default&signature=[sig]&vsid=[vsid]&CMCD=[cmcd]"
```

This is unique if I restrict to Media and search for "manifest"

![image](https://github.com/user-attachments/assets/1043abf6-eb38-40ad-92ee-546c2b699514)

**Comment by infogulch** [comment]
OK I've investigated a bit more.

The main extractor expects to find data in the nextjs script payload (`<script id="__NEXT_DATA__" ...`) some json data with the m3u8 file at the path `('props', 'pageProps', 'videoData', 'video')` [code](https://github.com/yt-dlp/yt-dlp/blob/5d904b077d2f58ae44bdf208d2dcfcc3ff8347f5/yt_dlp/extractor/dailywire.py#L13-L15).

However, for content requiring insider access like `https://www.dailywire.com/episode/2-biden` (this is the episode following the [current test url](https://github.com/yt-dlp/yt-dlp/blob/5d904b077d2f58ae44bdf208d2dcfcc3ff8347f5/yt_dlp/extractor/dailywire.py#L27)), this json path contains "Access denied", including for subscribers...

<details>
<summary> Then I was got distracted by something that became irrelevant... </summary>

<img width="30%" src="https://github.com/user-attachments/assets/40767d39-7ac0-4bb8-8270-811a4a843c82">

However the value of the `muxPlaybackId` field matches the name of a an m3u8 file that is eventually loaded at `https://stream.mux.com/wc4qC7rLo7UlDzuJVnFtbOAA4M2aJhfk.m3u8?token=[token]&CMCD=cid="cid",sid="[sid]"` which when passed to the yt-dlp command successfully downloads the content.

I downloaded and searched the entire session and this url is never included in text...

</details>

At some point it queries `https://v2server.dailywire.com/app/graphql` with this query:

<details>

```graphql
query getEpisodeBySlug($slug: String!) {
  episode(where: {slug: $slug}) {
    id
    title
    status
    slug
    isLive
    description
    createdAt
    scheduleAt
    updatedAt
    image
    allowedCountryNames
    allowedContinents
    rating
    show {
      id
      name
      slug
      belongsTo
    }
    segments {
      id
      image
      title
      liveChatAccess
      audio
      video
      duration
      watchTime
      description
      videoAccess
      muxAssetId
      muxPlaybackId
      captions {
        id
      }
    }
    createdBy {
      firstName
      lastName
    }
    discussionId
  }
}
```

And variables:

```json
variables: {"slug": "2-biden"}
```

</details>

Which returns json data, where the path `.data.episode.segments[0].video` has the url: `https://stream.media.dailywire.com/wc4qC7rLo7UlDzuJVnFtbOAA4M2aJhfk.m3u8?token=[token]`, which works as a download url when supplied to the yt-dlp cli.

---

So I guess a fix will need to query the graphql api to get the video url now.

**Comment by samuelvisser** [comment]
To fix this, a close examination of this open source project might help. They support episodes behind a login:
https://github.com/fpnewton/DailyWirePodcastProxy

Would love to see this working again in yt-dlp

**Comment by infogulch** [comment]
AFAIK the most relevant PR to this issue is: #9920 (linked above)
