### ISSUE TITLE
Error on Manyvids - No video formats found

### ISSUE THREAD

**Issue by aero1313** [yt-dlp/yt-dlp#8268]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

When attempting to download a video from Manyvids.com, an error is returned saying No video formats found. I am currently running the latest version 2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152

The example is a SFW free video: https://www.manyvids.com/Video/2638738/Snow-Angel-Challenge-SFW
But this issue persists even with paid videos.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies', 'C:\\yt-dlp\\manyvids_cookies.txt', 'https://www.manyvids.com/Video/2638738/Snow-Angel-Challenge-SFW', '--verbose']
[debug] Portable config "C:\yt-dlp\yt-dlp.conf": ['-o', 'C:\\Users\\Chris\\Documents\\Youtube\\%(title)s [%(id)s].%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1-full_build-www.gyan.dev (setts), ffprobe 5.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[ManyVids] Extracting URL: https://www.manyvids.com/Video/2638738/Snow-Angel-Challenge-SFW
[ManyVids] 2638738: Downloading webpage
ERROR: [ManyVids] 2638738: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2751, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1076, in raise_no_formats
yt_dlp.utils.ExtractorError: [ManyVids] 2638738: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by dirkf** [comment]
The `gtm.js` API URL that the extractor uses for video links (and which the site still fetches) no longer contains them. Someone will have to analyze the site's traffic again.

The site as a whole is NSFW and but the problem video is as NSFW as Hot Gossip (for older UK viewers).

**Comment by dionices** [comment]
I've figured a lot of this out: https://github.com/yt-dlp/yt-dlp/compare/master...dionices:yt-dlp:manyvids

I didn't bother with different formats because I only want the original videos.  Similarly, I didn't get like or view counts because I really don't care about those.  But this should hopefully give someone a head start on doing that.

I'm happy to help if someone wants to help flesh that stuff out, but I'm probably not going to spend a ton of time on it because it already does what I want.

That said, I'll share some notes.  It was helpful to use the phantomjs wrapper while working this out, because a lot of the info isn't directly in `gtm.js` and the DOM is updated after scripts run.  The main trick was to make the call to `https://video-player-bff.estore.kiwi.manyvids.com/vercel/videos/{video_id}/private`, which returns some JSON with video URL (along with the required query strings).  The one I picked out of there is `filepath`, but `transcodedFilepath` is also there if you want the compressed file instead.

**Comment by dirkf** [comment]
WIP yt-dl extractor update based on this very useful hint:
```console
$ python3.9 -m youtube_dl -F 'https://www.manyvids.com/Video/935718/MY-FACE-REVEAL/'
[ManyVids] 935718: Downloading webpage
[ManyVids] 935718: Downloading video info
[info] Available formats for 935718:
format code  extension  resolution note
teaser       mp4        720p       
transcoded   mp4        unknown    
original     mp4        1920x1080  267.22MiB (best)
$
```
The non-JS page includes several chunks of hydration JS, one of which contains a stringified JSON value with various useful metadata values.

The token/cookie/gtm.js stuff is no longer useful.

**Comment by dirkf** [comment]
And for OP (use the URL shown by @dionices above for fresh values):
```console
$ python3.9 -m youtube_dl -g 'https://www.manyvids.com/Video/2638738/Snow-Angel-Challenge-SFW'
https://cdn10.manyvids.com/426738/o1f12sk90j1iu91sd1pq28ee1548b.mp4?Expires=1699829986&Key-Pair-Id=APKAJK7FTSUZNXWC7PRA&Signature=eaX-rdWpnh0cRNhsbPW4qg4UP-dEuqI--g95TnG5IKMkQ-48kPiGx1TlJo3xBB2kiyXwsybS-KXGpHWhZSvt6IOhyzItZdIPXo6eUU~EKYTQOsExK0V6kZ4ffOfku2quAOXKUvSoibBOJ96AjdWHRv~V6QGbcwbfVgkEsXhhEiPbt~XbgA0P5dVfhsjOcJQHmMpQhcHXdu0ZkHhJZIbxtt6Azglgcm2w~Xwx2D6DyVDrdgtne4jaQLk2uyZQxRA2YP0c8mAikvCr9UGylVrrusxvy5xJ9ITlzR4EG7fMdqGWySwn~55tC5DXEObNbHbQDDAF0aNZvKl9i17PFhaUuA__
$
```

**Comment by aero1313** [comment]
Sorry I'm really dumb. How do I use the new URL to download?

**Comment by dirkf** [comment]
In `https://video-player-bff.estore.kiwi.manyvids.com/vercel/videos/{video_id}/private`, replace `{video_id}` with the ID of the problem video `2638738`. That should give you some JSON like this (after formatting):
```py
{
  'statusCode': 200,
  'statusMessage': 'Found',
  'data': {
    'filepath': /* ?original? video link */,
    'transcodedFilepath': /* maybe lower resolution link */,
    'teaser': ...
    ...
  }
}
```
Your media links are where the `/* comments */` are above.

**Comment by aero1313** [comment]
It gives me a HTTP Error 403 Forbidden when I try to download using the filepath URL and that Key-Pair-ID and Signature are not recognized as internal or external commands.

**Comment by dirkf** [comment]
Quote the URLs. `&` is a special character in POSIX shells. Since the URL security parameters were split off, the remaining URL gave 403.

**Comment by aero1313** [comment]
Refreshing the URL worked. Thanks!

**Comment by rounditout** [comment]
Thanks to those of you that diagnosed the workaround! Sounds like the problem is understood, so we would just need a kind volunteer to implement it for a future release? 

I’d give it a shot but with no experience in this code base at all I suspect I’d muck it up somehow.
