### ISSUE TITLE
Twitter video download fails when using proxy

### ISSUE THREAD

**Issue by wastemaster** [yt-dlp/yt-dlp#8276]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Montenegro

### Provide a description that is worded well enough to be understood

Without using the proxy download completes successfully.
Also the proxy is fully functional, I can confirm that it works on other sites

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://twitter.com/bilawalsidhu/status/1709239122936598607', '--proxy', 'http://useruseruser:pwdpwdpwd@gate.dc.smartproxy.com:20000', '-o', 'f.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.13.0-52-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-3.31.1, websockets-11.0.3
[debug] Proxy map: {'all': 'http://useruseruser:pwdpwdpwd@gate.dc.smartproxy.com:20000'}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
yt-dlp is up to date (stable@2023.09.24)
[twitter] Extracting URL: https://twitter.com/bilawalsidhu/status/1709239122936598607
[twitter] 1709239122936598607: Downloading guest token
ERROR: [twitter] 1709239122936598607: Unable to download JSON metadata: <urlopen error Tunnel connection failed: 444 Unassigned> (caused by ProxyError('<urlopen error Tunnel connection failed: 444 Unassigned>')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/twitter.py", line 1323, in _real_extract
    status = self._extract_status(twid)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/twitter.py", line 1285, in _extract_status
    status = self._graphql_to_legacy(self._call_graphql_api(self._GRAPHQL_ENDPOINT, twid), twid)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/twitter.py", line 331, in _call_graphql_api
    return traverse_obj(self._call_api(endpoint, media_id, query=query, graphql=True), 'data')
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/twitter.py", line 309, in _call_api
    'x-guest-token': self._fetch_guest_token(video_id)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/twitter.py", line 156, in _fetch_guest_token
    guest_token = traverse_obj(self._download_json(
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1033, in download_handle
    res = self._download_webpage_handle(
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 927, in connect
    self._tunnel()
  File "/usr/lib/python3.8/http/client.py", line 905, in _tunnel
    raise OSError("Tunnel connection failed: %d %s" % (code,
OSError: Tunnel connection failed: 444 Unassigned

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/networking/_urllib.py", line 410, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/networking/_urllib.py", line 102, in https_open
    return self.do_open(
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Tunnel connection failed: 444 Unassigned>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 4051, in urlopen
    return self._request_director.send(req)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/home/user/.cache/pypoetry/virtualenvs/myproject-downloader-GfTgg_MM-py3.8/lib/python3.8/site-packages/yt_dlp/networking/_urllib.py", line 422, in _send
    raise ProxyError(cause=e) from e
yt_dlp.networking.exceptions.ProxyError: <urlopen error Tunnel connection failed: 444 Unassigned>
```

**Comment by bashonly** [comment]
Does the video play in your web browser with proxy?

**Comment by wastemaster** [comment]
Yes you are right, looks like it simply is blocked on twitter side. 
Sorry! Please close the ticket
