### ISSUE TITLE
bigmarker.com - tried to download webinar, "unsupported URL"

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#8279]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,
I wonder if there are particular options to be able download videos from some particular sites, like this one ...
https://www.bigmarker.com/eetech-media/Energizing-the-Future-Real-Time-Precision-in-Renewable-Energy-Management?bmid=57d0576b9150&bmid_type=member
Thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pavel167** [comment]
Ok, I took notes of what you said.
Here is what happens:
```
(env_video_dnld) pavel@MISSURI:~$ [generic] Extracting URL: https://www.bigmarker.com/eetech-media/Energizing-the-Future-Real-Time-Precision-in-Renewable-Ene...nt?bmid=57d0576b9150
[generic] Energizing-the-Future-Real-Time-Precision-in-Renewable-Energy-Management?bmid=57d0576b9150: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Energizing-the-Future-Real-Time-Precision-in-Renewable-Energy-Management?bmid=57d0576b9150: Extracting information
ERROR: Unsupported URL: https://www.bigmarker.com/eetech-media/Energizing-the-Future-Real-Time-Precision-in-Renewable-Energy-Management?bmid=57d0576b9150

[1]+  Exit 1                  yt-dlp https://www.bigmarker.com/eetech-media/Energizing-the-Future-Real-Time-Precision-in-Renewable-Energy-Management?bmid=57d0576b9150
(env_video_dnld) pavel@MISSURI:~$ 
```
There are no additional options (e.g. username, password) to view this video.

**Comment by nicolaasjan** [comment]
Got the `.mpd` URL from inspecting the page.
Result:

```
yt-dlp -v --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0" --referer "https://www.bigmarker.com/" "https://d38fobjf20dmzq.cloudfront.net/7fe0be09-7510-4a55-b850-11beb4bb7b56/dash/dash.mpd"
[debug] Command-line config: ['-v', '--user-agent', 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0', '--referer', 'https://www.bigmarker.com/', 'https://d38fobjf20dmzq.cloudfront.net/7fe0be09-7510-4a55-b850-11beb4bb7b56/dash/dash.mpd']
[debug] User config "/home/nico/.config/yt-dlp/config": ['--rm-cache-dir', '-o', '/dev/shm/test-dlp/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--add-metadata', '--embed-thumbnail', '--convert-thumbnails', 'jpg', '--ppa', 'ffmpeg:-metadata synopsis=""', '--force-ipv4', '--sponsorblock-remove', 'all', '--console-title', '--downloader', 'aria2c', '--downloader-args', 'aria2c:--http-accept-gzip=true -x 14 -s 14 -j 14 -k 1M --log-level=info --file-allocation=none']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.10.04 [b095fd3fa] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-163-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-112061-g654e4b00e2-Nico-20230914 (fdk,setts), ffprobe N-112061-g654e4b00e2-Nico-20230914, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, secretstorage-3.3.3, sqlite3-3.31.1, websockets-11.0.3, xattr-0.10.1
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
Removing cache dir /home/nico/.cache/yt-dlp ..
[generic] Extracting URL: https://d38fobjf20dmzq.cloudfront.net/7fe0be09-7510-4a55-b850-11beb4bb7b56/dash/dash.mpd
[generic] dash: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] dash: Extracting information
[debug] Identified a DASH manifest
ERROR: [generic] dash: This video is DRM protected
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_reyt-dlp -v --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0" --referer "https://www.bigmarker.com/" "https://d38fobjf20dmzq.cloudfront.net/7fe0be09-7510-4a55-b850-11beb4bb7b56/dash/dash.mpd"
[debug] Command-line config: ['-v', '--user-agent', 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0', '--referer', 'https://www.bigmarker.com/', 'https://d38fobjf20dmzq.cloudfront.net/7fe0be09-7510-4a55-b850-11beb4bb7b56/dash/dash.mpd']
[debug] User config "/home/nico/.config/yt-dlp/config": ['--rm-cache-dir', '-o', '/dev/shm/test-dlp/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--add-metadata', '--embed-thumbnail', '--convert-thumbnails', 'jpg', '--ppa', 'ffmpeg:-metadata synopsis=""', '--force-ipv4', '--sponsorblock-remove', 'all', '--console-title', '--downloader', 'aria2c', '--downloader-args', 'aria2c:--http-accept-gzip=true -x 14 -s 14 -j 14 -k 1M --log-level=info --file-allocation=none']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.10.04 [b095fd3fa] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-163-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-112061-g654e4b00e2-Nico-20230914 (fdk,setts), ffprobe N-112061-g654e4b00e2-Nico-20230914, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, secretstorage-3.3.3, sqlite3-3.31.1, websockets-11.0.3, xattr-0.10.1
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
Removing cache dir /home/nico/.cache/yt-dlp ..
[generic] Extracting URL: https://d38fobjf20dmzq.cloudfront.net/7fe0be09-7510-4a55-b850-11beb4bb7b56/dash/dash.mpd
[generic] dash: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] dash: Extracting information
[debug] Identified a DASH manifest
ERROR: [generic] dash: This video is DRM protected
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [generic] dash: This video is DRM protectedsult, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [generic] dash: This video is DRM protected
```
This video is DRM protected...

**Comment by gamer191** [comment]
I can access it in my DRM-free browser. In fact, it doesn't even check if I have drm enabled (Firefox notifies me if a webpage requests me to enable DRM). After running curl on the manifest, I get the UDID `1077efec-c0b2-4d02-ace3-3c1e52e2fb4b`. A quick Google search takes me to https://github.com/google/ExoPlayer/issues/3138, a page which claims that that UDID is clearkey DRM.

Further investigation is required, but if that is clearkey, it means 2 things:
1. this site can be supported
2. yt-dlp's DRM detection false-postives for clearkey drm. I don't know if that's a bug, because you wouldn't want yt-dlp to download a clearkey manifest that it doesn't support, but it also leads to situations where sites won't be supported because of a misleading error message

**Comment by bashonly** [comment]
Until support is added for clearkey encrypted DASH, it is basically indistinguishable from DRM DASH.
Support for this site will require #7098 to be completed first

**Comment by pavel167** [comment]
Ok, thank you all for investigating this matter.

**Comment by Dialga** [comment]
Perhaps there's another way, if you put a bigmarker.com url into https://en.yt1save.com/bigmarker/ or https://pastedownload.com/bigmarker-video-downloader/ you will get a link to the video in an aws s3 bucket.
