### ISSUE TITLE
[Broken] dw: An extractor error caused by KeyError('file_name')

### ISSUE THREAD

**Issue by jieweix** [yt-dlp/yt-dlp#830]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Jiewei Xiong\Videos>yt-dlp https://www.dw.com/en/currentzis-the-classical-rebel-part-1/av-19570589 --verbose
[debug] Command-line config: ['https://www.dw.com/en/currentzis-the-classical-rebel-part-1/av-19570589', '--verbose']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'https://127.0.0.1:10809', 'ftp': 'ftp://127.0.0.1:10809'}
[debug] [dw] Extracting URL: https://www.dw.com/en/currentzis-the-classical-rebel-part-1/av-19570589
[dw] 19570589: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('file_name')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 575, in extract
  File "yt_dlp\extractor\dw.py", line 66, in _real_extract
KeyError: 'file_name'
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 575, in extract
  File "yt_dlp\extractor\dw.py", line 66, in _real_extract
KeyError: 'file_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1199, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1224, in __extract_info
  File "yt_dlp\extractor\common.py", line 594, in extract
yt_dlp.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('file_name')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Trying to download something from DW, says an extractor error occured.

**Comment by coletdjnz** [comment]
Possibly related:
https://github.com/ytdl-org/youtube-dl/issues/29553
https://github.com/ytdl-org/youtube-dl/issues/17281
