### ISSUE TITLE
ArteTV: The merging step ends in "Error: [WinError 5] Access denied"

### ISSUE THREAD

**Issue by ValSlender** [yt-dlp/yt-dlp#8310]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

When I try to download video from `arte.tv`, the merging step do not work. In the example below I get 3 files : 1 video only, 1 audio only and a third with video and audio and with file name ends in  `.temp.mp4`.

The video link : [](https://www.arte.tv/fr/videos/112262-116-A/un-diner-royal-a-6-millions-d-euros/)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.arte.tv/fr/videos/112262-116-A/un-diner-royal-a-6-millions-d-euros/']
[debug] User config "C:\Users\valslender\AppData\Roaming\yt-dlp\config": ['-o', 'D:/Users/valslender/Downloads/%(title)s.%(ext)s', '-S', 'res:720', '--audio-multistreams', '--audio-format', 'best', '--sub-format', 'best', '--embed-chapters', '--embed-subs', '--sub-lang', 'fr,en', '--no-mtime', '--no-part']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112327-g9078dc0c52-20231005 (setts), ffprobe N-112327-g9078dc0c52-20231005
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
Current Build Hash: 7c809be9ad981b2a057bd60d766a9dffb1e88ddea6a9530c416f4741bc297364
yt-dlp is up to date (stable@2023.10.07)
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/112262-116-A/un-diner-royal-a-6-millions-d-euros/
[ArteTV] 112262-116-A: Downloading JSON metadata
[ArteTV] 112262-116-A: Downloading m3u8 information
[debug] Sort order given by user: res:720
[debug] Formats sorted by: hasvid, ie_pref, res:720(720.0), lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo+bestaudio/best
[info] 112262-116-A: Downloading 1 format(s): VOF-2034+VOF-program_audio_0-VOF
[info] There are no subtitles for the requested languages
[debug] Invoking hlsnative downloader on "https://arte-cmafhls.akamaized.net/am/cmaf-webonly/112000/112200/112262-116-A_VOF/231005184333/medias/112262-116-A_v720.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 17
[download] Destination: D:\Users\valslender\Downloads\Un dîner royal à 6 millions d'euros ？.fVOF-2034.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   22.08MiB in 00:00:19 at 1.13MiB/s
[debug] Invoking hlsnative downloader on "https://arte-cmafhls.akamaized.net/am/cmaf-webonly/112000/112200/112262-116-A_VOF/231005184333/medias/112262-116-A_aud_VOF-FRA_1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 17
[download] Destination: D:\Users\valslender\Downloads\Un dîner royal à 6 millions d'euros ？.fVOF-program_audio_0-VOF.mp4
[download] 100% of    1.55MiB in 00:00:06 at 260.52KiB/s
[debug] ffmpeg command line: ffprobe -show_streams "file:D:\Users\valslender\Downloads\Un dîner royal à 6 millions d'euros ？.fVOF-program_audio_0-VOF.mp4"
[Merger] Merging formats into "D:\Users\valslender\Downloads\Un dîner royal à 6 millions d'euros ？.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\Users\valslender\Downloads\Un dîner royal à 6 millions d'euros ？.fVOF-2034.mp4" -i "file:D:\Users\valslender\Downloads\Un dîner royal à 6 millions d'euros ？.fVOF-program_audio_0-VOF.mp4" -c copy -map "0:v:0" -map "1:a:0" "-bsf:a:0" aac_adtstoasc -movflags "+faststart" "file:D:\Users\valslender\Downloads\Un dîner royal à 6 millions d'euros ？.temp.mp4"
WARNING: Cannot update utime of file
ERROR: [WinError 5] Accès refusé: "D:\\Users\\valslender\\Downloads\\Un dîner royal à 6 millions d'euros ？.temp.mp4" -> "D:\\Users\\valslender\\Downloads\\Un dîner royal à 6 millions d'euros ？.mp4"
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2921, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3464, in process_info
  File "yt_dlp\YoutubeDL.py", line 3644, in post_process
  File "yt_dlp\YoutubeDL.py", line 3626, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3604, in run_pp
  File "yt_dlp\postprocessor\common.py", line 23, in run
  File "yt_dlp\postprocessor\common.py", line 128, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 838, in run
PermissionError: [WinError 5] Accès refusé: "D:\\Users\\valslender\\Downloads\\Un dîner royal à 6 millions d'euros ？.temp.mp4" -> "D:\\Users\\valslender\\Downloads\\Un dîner royal à 6 millions d'euros ？.mp4"
```

**Comment by vxbinaca** [comment]
filesystem permission error?

**Comment by bashonly** [comment]
Looks like the same issue as #4975, with the added wrinkle that utime update is failing too

A workaround may be to run the same yt-dlp command again to see if renaming the file succeeds on retry

Closing as duplicate
