### ISSUE TITLE
Unable to download video data: HTTP Error 416: Requested range not satisfiable

### ISSUE THREAD

**Issue by Dorian25** [yt-dlp/yt-dlp#8313]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France/Europe

### Provide a description that is worded well enough to be understood

I'm trying to download a youtube video but I get a 416 error

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API 
[debug] params: {'format': 'b[height=360][ext=mp4]', 'quiet': True, 'nopart': True, 'verbose': True, 'outtmpl': './download/youtube_video.%(ext)s', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.9.1 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-3.33.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1886 extractors 
[youtube] Extracting URL: https://www.youtube.com/watch?v=oPbcVvFkC50 
[youtube] oPbcVvFkC50: Downloading webpage 
[youtube] oPbcVvFkC50: Downloading ios player API JSON 
[youtube] oPbcVvFkC50: Downloading android player API JSON 
[youtube] oPbcVvFkC50: Downloading m3u8 information 
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] oPbcVvFkC50: Downloading 1 format(s): 18 
[debug] Invoking http downloader on "https://rr2---sn-n4g-jqbed.googlevideo.com/videoplayback?expire=1696872100&ei=ROIjZc2QIb3YvdIPwYGw-A8&ip=2a02%3A8428%3A721%3A1901%3A1eb%3A7d16%3Aea8c%3A9d74&id=o-ACHk0PrUpfhrfStHiQavqC9Ky4HJVZpTuNJx0KZLS9-M&itag=18&source=youtube&requiressl=yes&mh=te&mm=31%2C26&mn=sn-n4g-jqbed%2Csn-h5qzen7d&ms=au%2Conr&mv=m&mvi=2&pl=40&gcr=fr&initcwndbps=985000&spc=UWF9f9SeyXtRQfmOaHzjK3RNA2aQOuU&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=54372356&ratebypass=yes&dur=615.073&lmt=1695269514416486&mt=1696849984&fvip=5&fexp=24007246&beids=24350018&c=ANDROID&txp=5538434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRgIhAMqBuYO5L_1vn8bDV5x61FgFwgl_aVapruuglsLCrnZGAiEA0ik2zu_HJVxv4DtW_Zv6j4DELLVFEOKsOHxHr6synKQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRQIgZWDeeNlJ8j5kBbbV2EbV3dQ2FyVOAWOmSL1MzjlcjUkCIQDhxu4OZgfTx4P2p68r73KSRbwRGoxKvu25ktjOq07ZYw%3D%3D"
[download] Resuming download at byte 125837778 
ERROR: unable to download video data: HTTP Error 416: Requested range 
not satisfiable
Traceback (most recent call last): 
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\networking\_urllib.py", line 410, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 416: Requested range not satisfiable

The above exception was the direct cause of the following exception:  

Traceback (most recent call last):
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 4051, in urlopen
    return self._request_director.send(req)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\networking\common.py", line 114, in send
    response = handler.send(request)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\networking\_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\networking\common.py", line 325, in send
    return self._send(request)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\networking\_urllib.py", line 415, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 416: Requested range not satisfiable

The above exception was the direct cause of the following exception:  

Traceback (most recent call last):
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 4070, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 416: Requested range not satisfiable

During handling of the above exception, another exception occurred:   

Traceback (most recent call last):
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\networking\_urllib.py", line 410, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 416: Requested range not satisfiable

The above exception was the direct cause of the following exception:  

Traceback (most recent call last):
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 4051, in urlopen
    return self._request_director.send(req)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\networking\common.py", line 114, in send
    response = handler.send(request)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\networking\_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\networking\common.py", line 325, in send
    return self._send(request)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\networking\_urllib.py", line 415, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 416: Requested range not satisfiable

The above exception was the direct cause of the following exception:  

Traceback (most recent call last):
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3387, in process_info
    success, real_download = self.dl(temp_filename, info_dict)        
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3108, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\http.py", line 364, in real_download      
    establish_connection()
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\http.py", line 154, in establish_connection
    ctx.data = self.ydl.urlopen(
  File "C:\Users\doria\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 4070, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 416: Requested range not satisfiable
```

**Comment by theluk** [comment]
Ok so how is no-part useful then? 

It is like you said @bashonly, I wanted a complete download, so why does yt-dlp think it is incomplete?

I started trying no-part because seeing on production errors like these.

![CleanShot 2024-08-30 at 14 24 16](https://github.com/user-attachments/assets/81fbadc7-a78c-4d0a-8acc-d8db60477843)
