### ISSUE TITLE
Niconico Channel Plus stopped working all of a sudden

### ISSUE THREAD

**Issue by mondoak1** [yt-dlp/yt-dlp#8317]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I just started using yt-dlp to download a couple stream archives from Niconico Channel plus today and it stopped working all of a sudden. I downloaded about 6 videos (30 gb or so). I checked to see if yt-dlp worked on a previously downloaded video (after moving it to another folder so yt-dlp doesn't think it's already been downloaded) and it did not work on it. So it seems like something must have changed. Is it possible I got flagged somehow for downloading around 6 or so videos in 1 day? I can still watch the streams. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://nicochannel.jp/soyogisetune-asmr-plus/video/sm9rU2bo9cudbwhGVEBSmRxm', '-vU', '--cookies-from-browser', 'chrome']
[debug] Extracting cookies from: "C:\Users\Mike\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Mike\AppData\Local\Google\Chrome\User Data\Local State"
[debug] cookie version breakdown: {'v10': 3211, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out cp932 (No VT), error utf-8, screen cp932 (No VT)
[debug] yt-dlp version nightly@2023.10.09.183051 [84e26038d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-34-g3d5edb89e7-20230810 (setts), ffprobe n6.0-34-g3d5edb89e7-20230810
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1887 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] [NiconicoChannelPlus] sm9rU2bo9cudbwhGVEBSmRxm: video_type=vod, live_status=not_live
ERROR: [NiconicoChannelPlus] Unable to get session id: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\niconicochannelplus.py", line 110, in _real_extract
  File "yt_dlp\extractor\niconicochannelplus.py", line 220, in _get_live_status_and_session_id
  File "yt_dlp\extractor\niconicochannelplus.py", line 22, in _call_api
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 1033, in download_handle
  File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage

  File "yt_dlp\networking\_urllib.py", line 410, in _send
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 415, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4070, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden
```

**Comment by mondoak1** [comment]
I tested on a few more videos and it seems like yt-dlp stopped working only on niconico videos that doesn't have any free parts. It is still able to work videos that have some parts free and some parts requiring paid. For videos that are part free, it is able to download the full video.

**Comment by EnderShadow** [comment]
I can confirm that this occurs even with `--cookies-from-browser firefox+KWALLET` (since that's what I use on my system).

```
yt-dlp -vU --cookies-from-browser firefox+KWALLET 'https://nicochannel.jp/soyogisetune-asmr-plus/video/sm9rU2bo9cudbwhGVEBSmRxm'
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox+KWALLET', 'https://nicochannel.jp/soyogisetune-asmr-plus/video/sm9rU2bo9cudbwhGVEBSmRxm']
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/matthew/.mozilla/firefox/otdn3pg3.default/cookies.sqlite"
Extracted 2373 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742]
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.5.3-zen1-1-zen-x86_64-with-glibc2.38 (OpenSSL 3.1.3 19 Sep 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2023.07.22, mutagen-1.47.0, secretstorage-3.3.3, sqlite3-3.43.1, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[NiconicoChannelPlus] Extracting URL: https://nicochannel.jp/soyogisetune-asmr-plus/video/sm9rU2bo9cudbwhGVEBSmRxm
[NiconicoChannelPlus] channels/soyogisetune-asmr-plus: Fetching channel list
[NiconicoChannelPlus] sm9rU2bo9cudbwhGVEBSmRxm: Fetching video page info
[debug] [NiconicoChannelPlus] sm9rU2bo9cudbwhGVEBSmRxm: video_type=vod, live_status=not_live
[NiconicoChannelPlus] sm9rU2bo9cudbwhGVEBSmRxm/session: Getting session id
ERROR: [NiconicoChannelPlus] Unable to get session id: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/niconicochannelplus.py", line 110, in _real_extract
    live_status, session_id = self._get_live_status_and_session_id(content_code, data_json)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/niconicochannelplus.py", line 220, in _get_live_status_and_session_id
    session_id = self._call_api(
                 ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/niconicochannelplus.py", line 22, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1033, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_urllib.py", line 410, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4051, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_urllib.py", line 415, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4070, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden
```

**Comment by EnderShadow** [comment]
While @mondoak1 is not willing to share credentials (based on the checkmark), I'm willing to share them if needed.

**Comment by climba03003** [comment]
If it doesn't works, it means that you are downloading the video that is private to member only.
NicoNico Channel Plus is API-based website, that means `Cookies` will not works.

To solve the problem, it requires to link up the NicoNico credentials with the NicoNico Channel Plus.

**Comment by EnderShadow** [comment]
You wouldn't happen to know how that would be done do you?

**Comment by pzhlkj6612** [comment]
Hi there, please test the code of #8645 and check if it works with your Niconico email and password.

**Comment by EnderShadow** [comment]
I just tried it and it gave a 404 error.

    ERROR: [NiconicoChannelPlus] Unable to get login url: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by pzhlkj6612** [comment]
Hi @EnderShadow , thanks for your test.

<br>

> I just tried it and it gave a 404 error.
> 
> ```
> ERROR: [NiconicoChannelPlus] Unable to get login url: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> ```

It's weird. I didn't see HTTP 404 on my side.

### Questions

1. https://auth.sheeta.com/auth/realms/FCS00001/protocol/openid-connect/auth?client_id=FCS00056&response_type=code&scope=openid&kc_idp_hint=niconico&redirect_uri=https%3A%2F%2Fnicochannel.jp%2Ftestman%2Flogin

What do you see when opening the above link? Is there a Niconico login page like this?

> ![Niconico logo](https://account.nicovideo.jp/assets/public/img/logo/niconico.svg)
> 
> ---
> 
> Login Email Address / Phone Number
> \[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\]
> 
> Password
> \[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\]   【 Login 】
> 
> [forgot your password?](https://account.nicovideo.jp/password/reset)
> 
> ---
> 
> Log in to the service account below.
> 
> ...

2. May I ask what is your location? Or say, what is the location of your IP?

**Comment by EnderShadow** [comment]
1. When opening the above link, it asks if I'm 18+, asks if I want email notifications, and then takes me to the home screen. That's probably because I'm already logged in though. When checking through an incognito window, it takes me to a login page.
2. It has my correct town in Florida.

**Comment by pzhlkj6612** [comment]
@EnderShadow thanks for your info. Maybe you were using email/password with specifying cookies from Firefox? Please try the latest code of #8645 .

**Comment by EnderShadow** [comment]
Yes, I was specifying both when I was doing that. Now it seems to work with just specifying cookies. Thanks for getting it working!

**Comment by EnderShadow** [comment]
I have a found a bug with it though. It will successfully download a single item when downloading multiple items using only `--cookies-from-browser` and then the token is expired so it needs to acquire a new one. Rerunning the command will cause it to acquire a new token which will work for the next item (assuming you're using `--download-archive` to not download duplicates). I'll test with both --cookies-from-browser and a username and password afterwards to see if that resolves the token issue.
`[NiconicoChannelPlus] Extracting URL: https://nicochannel.jp/soyogisetune-asmr-plus/video/smzPqWvNjYPmr6gScDsbJAMA
[NiconicoChannelPlus] channels/soyogisetune-asmr-plus: Fetching channel list
[NiconicoChannelPlus] smzPqWvNjYPmr6gScDsbJAMA: Fetching video page info
[NiconicoChannelPlus] smzPqWvNjYPmr6gScDsbJAMA/session: Getting session id
ERROR: [NiconicoChannelPlus] outdated cached token. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (niconicochannelplus) to provide account credentials`

**Comment by EnderShadow** [comment]
The issue also occurs with both cookies + username and password and with just username and password

**Comment by pzhlkj6612** [comment]
@EnderShadow

> It will successfully download a single item when downloading multiple items using only `--cookies-from-browser` and then the token is expired so it needs to acquire a new one. Rerunning the command will cause it to acquire a new token which will work for the next item (assuming you're using `--download-archive` to not download duplicates).

Weird, acquiring new tokens should not happen when using cookies from browsers...

I guess you might forget to update your code? I didn't see the newly added "`[NiconicoChannelPlus] Getting auth status`" line. How did you pull the new code?

If you are using pip:

```shell
pip install --force-reinstall <blahblah...>
#           ^^^^^add this^^^^

```

Or checkout the code at 67649c01d4b3ceeb048bb07673a5bf169107b306 with git.

**Comment by EnderShadow** [comment]
The snippet was from when it failed after successfully downloading one video in the batch of videos. The initial part where it grabs the credentials is here along with the command I ran.
```
xargs -a need.txt yt-dlp --cookies-from-browser firefox+KWALLET --download-archive archive.txt
Extracting cookies from firefox
Extracted 2908 cookies from firefox
[NiconicoChannelPlus] Extracting URL: https://nicochannel.jp/soyogisetune-asmr-plus/video/sm27475oy5LNKb7XcVDALgD
[NiconicoChannelPlus] Getting auth status
[NiconicoChannelPlus] 56: Fetching sns login info
[NiconicoChannelPlus] channels/soyogisetune-asmr-plus: Fetching channel list
[NiconicoChannelPlus] sm27475oy5LNKb7XcVDALgD: Fetching video page info
[NiconicoChannelPlus] sm27475oy5LNKb7XcVDALgD/session: Getting session id
[NiconicoChannelPlus] sm27475oy5LNKb7XcVDALgD: Downloading m3u8 information
[NiconicoChannelPlus] fanclub_sites/274: Fetching channel base info
[NiconicoChannelPlus] fanclub_sites/274: Fetching channel user info
```

**Comment by pzhlkj6612** [comment]
Hi there! I've updated the code in #8645, please give it a try!

**Comment by EnderShadow** [comment]
I'm no longer subscribed to a channel where I can test this, so I can't test it.

**Comment by sparcnut** [comment]
@pzhlkj6612 With #8645 merged onto current git master (50c29352312f5662acf9a64b0012766f5c40af61), downloading paid Channel Plus videos seems to work for me.  TYVM :-)

**Comment by pzhlkj6612** [comment]
@sparcnut,

> With #8645 merged onto current git master ([50c2935](https://github.com/yt-dlp/yt-dlp/commit/50c29352312f5662acf9a64b0012766f5c40af61)), downloading paid Channel Plus videos seems to work for me. TYVM :-)

Thanks for your test!

<br>

The code is unfinished and being rewritten. I'll update if something changed.

**Comment by climba03003** [comment]
@pzhlkj6612 
Due to the poor content protection of NicoNico Channel Plus. The current methods allow people to download the paid content without paid.

I would like to ask for stop developing in order to protect the content creator rights. Or you should provide the protect inside the codebase.

**Comment by pzhlkj6612** [comment]
Hi, @climba03003.

> @pzhlkj6612 Due to the poor content protection of NicoNico Channel Plus. The current methods allow people to download the paid content without paid.
> 
> I would like to ask for stop developing in order to protect the content creator rights. Or you should provide the protect inside the codebase.

Well, the current logic does need subscription for paid videos. I'm unable to get the "session id" without membership.

Maybe I don't know so much about Niconico Channel Plus, could you please explain more? Thanks.

**Comment by climba03003** [comment]
> Hi, @climba03003.
> 
> > @pzhlkj6612 Due to the poor content protection of NicoNico Channel Plus. The current methods allow people to download the paid content without paid.
> > 
> > I would like to ask for stop developing in order to protect the content creator rights. Or you should provide the protect inside the codebase.
> 
> Well, the current logic does need subscription for paid videos. I'm unable to get the "session id" without membership.
> 
> Maybe I don't know so much about Niconico Channel Plus, could you please explain more? Thanks.
> 

It requires subscription but the subscription can be a free member. So, it is actually allows to download paid content without paying.

**Comment by pukkandan** [comment]
@climba03003 We are not intentionally trying to bypass subscription, but we are also not going to add extra code to block it. That is the website's responsibility, not ours.

**Comment by climba03003** [comment]
You can choose to do one more step to protect the content, and of-course you can choose not to.
It just a request only to maintain a good world.

**Comment by mondoak1** [comment]
It seems like yt-dlp stopped working on Nicochannel Plus again, for both paid and unpaid contents, after coming back recently from the Russian DDoS attacks. Update to Nico channel Plus code section requested. Thank you!

**Comment by pzhlkj6612** [comment]
Hi, @mondoak1 ! 

What's the version of the yt-dlp you were using? Did you check out the code from my previous PR? And would you like to add the log here? Like the "Complete Verbose Output" in the first comment of this issue. 

The previously workable code for NiconicoChannelPlus has not been merged yet since this issue was raised, though. 

It seems that the VIP function in NiconicoChannelPlus has been fixed? Are you able to watch unpaid and paid content in your web browsers?

**Comment by mondoak1** [comment]
Hi @pzhlkj6612 

I'm using the latest nightly version of the code. I am able to watch the content on my web. Here's the log for 1 of the unpaid content:

[debug] Command-line config: ['-vU', 'https://nicochannel.jp/soyogisetune-asmr-plus/video/smyyTGxHTrSeNiwUPP3tvJ2b']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds [d28aa87e2] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-34-g3d5edb89e7-20230810 (setts), ffprobe n6.0-34-g3d5edb89e7-20230810
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds)
[NiconicoChannelPlus] Extracting URL: https://nicochannel.jp/soyogisetune-asmr-plus/video/smyyTGxHTrSeNiwUPP3tvJ2b
[NiconicoChannelPlus] channels/soyogisetune-asmr-plus: Fetching channel list
ERROR: [NiconicoChannelPlus] Unable to fetch channel list: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\niconicochannelplus.py", line 103, in _real_extract
  File "yt_dlp\extractor\niconicochannelplus.py", line 26, in _find_fanclub_site_id
  File "yt_dlp\extractor\niconicochannelplus.py", line 22, in _call_api
  File "yt_dlp\extractor\common.py", line 1139, in download_content
  File "yt_dlp\extractor\common.py", line 1099, in download_handle
  File "yt_dlp\extractor\common.py", line 960, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 909, in _request_webpage

  File "yt_dlp\extractor\common.py", line 896, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4161, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 337, in send
  File "yt_dlp\networking\_requests.py", line 361, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

**Comment by pzhlkj6612** [comment]
@mondoak1 

> I'm using the latest nightly version of the code. I am able to watch the content on my web.

Thank you! The logic appears to have changed. I'll let you know when new code is available. 

---

In addition, a GitHub use tip:

You can use the "code block" format to protect the log from being improperly rendered by GitHub. See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting .

**Comment by xerial817** [comment]
I also find that yt-dlp is not working for the nicochannel, throwing HTTP 404 error and so I checked the site logic.
Found that the api location is now `https://api.nicochannel.jp` instead of the `https://nfc-api.nicochannel.jp` stated in the extractor.

**Comment by pzhlkj6612** [comment]
@xerial817, please have a look at #9978 when you have some free time.
