### ISSUE TITLE
Add support for pacegallery.com

### ISSUE THREAD

**Issue by kblumenthal** [yt-dlp/yt-dlp#8327]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video embed: https://www.pacegallery.com/exhibitions/matthew-day-jackson-against-nature/
- Single video embed: https://www.pacegallery.com/exhibitions/jules-de-balincourt-midnight-movers/
- Single video embed: https://www.pacegallery.com/exhibitions/paulo-monteiro-undefined-inclusions/

### Provide a description that is worded well enough to be understood

The Pace Gallery's official website employs YouTube embeds for all of their videos. They do not employ any additional DRM that they are aware of and they are keen to support yt-dlp for archival purposes. They do however employ a lazyload that might affect the generic extractor's ability to find the videos on the example URLs. 

Here for example is the embed from the verbose output example, which plays nicely with yt-dlp on its own: https://www.youtube.com/embed/AS0o27hvb2c?autoplay=0&controls=1&showinfo=0&modestbranding=1&fs=1&cc_load_policy=0&iv_load_policy=3&autohide=0&enablejsapi=1&origin=https://www.pacegallery.com&widgetid=1

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.pacegallery.com/exhibitions/paulo-monteiro-undefined-inclusions/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip)
[debug] Python 3.9.6 (CPython x86_64 64bit) - macOS-10.16-x86_64-i386-64bit (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-3.35.5, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
yt-dlp is up to date (stable@2023.10.07)
[generic] Extracting URL: https://www.pacegallery.com/exhibitions/paulo-monteiro-undefined-inclusions/
[generic] paulo-monteiro-undefined-inclusions: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] paulo-monteiro-undefined-inclusions: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.pacegallery.com/exhibitions/paulo-monteiro-undefined-inclusions/
Traceback (most recent call last):
  File "/Users/karl-rainerblumenthal/Library/Python/3.9/lib/python/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/karl-rainerblumenthal/Library/Python/3.9/lib/python/site-packages/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/karl-rainerblumenthal/Library/Python/3.9/lib/python/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/Users/karl-rainerblumenthal/Library/Python/3.9/lib/python/site-packages/yt_dlp/extractor/generic.py", line 2575, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.pacegallery.com/exhibitions/paulo-monteiro-undefined-inclusions/
```

**Comment by dirkf** [comment]
Since plain YT IDs are valid "URL"s, a suitable pattern could just be added to `YoutubeIE._EMBED_REGEX`:
```
r'''<div [^>]*\bclass\s*=\s*['"]youtube-video\b[^>]+\bdata-id\s*=\s*['"](?P<url>[0-9A-Za-z_-]{11})\b           '''
A site extractor/plugin would be a better solution if attributes could be in any order or metadata should be extracted from the page itself.

The site devs might be able to reveal what tooling generates these lazyload elements to help us understand if it's something that should be expected in other sites.
