### ISSUE TITLE
RDS.CA not working

### ISSUE THREAD

**Issue by helsan74** [yt-dlp/yt-dlp#8330]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

URL not working
https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385

D:\yt-dlp>yt-dlp https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-a-rds-gym-bermudez-vs-clavel-3: Downloading webpage
[redirect] Following redirect to https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Extracting information
ERROR: Unsupported URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-a-rds-gym-bermudez-vs-clavel-3: Downloading webpage
[redirect] Following redirect to https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Extracting information
ERROR: Unsupported URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385

D:\yt-dlp>yt-dlp --cookies cookies.txt https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-a-rds-gym-bermudez-vs-clavel-3: Downloading webpage
[redirect] Following redirect to https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Extracting information
ERROR: Unsupported URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385

D:\yt-dlp>yt-dlp --cookies d:\yt-dlp\cookies.txt https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-a-rds-gym-bermudez-vs-clavel-3: Downloading webpage
[redirect] Following redirect to https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Extracting information
ERROR: Unsupported URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385

D:\yt-dlp>yt-dlp --cookies d:\yt-dlp\cookies.txt https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Extracting information
ERROR: Unsupported URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385

D:\yt-dlp>yt-dlp --cookies d:\yt-dlp\cookies.txt https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Extracting information
ERROR: Unsupported URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385

D:\yt-dlp>yt-dlp https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-a-rds-gym-bermudez-vs-clavel-3: Downloading webpage
[redirect] Following redirect to https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Extracting information
ERROR: Unsupported URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385

D:\yt-dlp>yt-dlp --cookies cookies.exe -vU D:\yt-dlp>yt-dlp https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[debug] Command-line config: ['--cookies', 'cookies.exe', '-vU', 'D:\\yt-dlp', 'https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen cp1252 (No VT)
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112441-gc06d3d2404-20231010 (setts), ffprobe N-112441-gc06d3d2404-20231010
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to handle request: Unsupported url scheme: "d" (urllib)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2437, in _real_extract
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
  File "yt_dlp\networking\common.py", line 127, in send
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: "d" (urllib)

WARNING: [generic] Falling back on generic information extractor
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2575, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385


D:\yt-dlp>[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
'[generic]' is not recognized as an internal or external command,
operable program or batch file.

D:\yt-dlp>[generic] la-boxe-a-rds-gym-bermudez-vs-clavel-3: Downloading webpage
'[generic]' is not recognized as an internal or external command,
operable program or batch file.

D:\yt-dlp>[redirect] Following redirect to https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
'[redirect]' is not recognized as an internal or external command,
operable program or batch file.

D:\yt-dlp>[generic] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
'[generic]' is not recognized as an internal or external command,
operable program or batch file.

D:\yt-dlp>[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Downloading webpage
'[generic]' is not recognized as an internal or external command,
operable program or batch file.

D:\yt-dlp>WARNING: [generic] Falling back on generic information extractor
'WARNING:' is not recognized as an internal or external command,
operable program or batch file.

D:\yt-dlp>[generic] la-boxe-à-rds-gym-bermudez-vs-clavel-3: Extracting information
'[generic]' is not recognized as an internal or external command,
operable program or batch file.

D:\yt-dlp>ERROR: Unsupported URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-%C3%A0-rds-gym-bermudez-vs-clavel-3.1432385
```

**Comment by dirkf** [comment]
URLs with `/emissions/...` aren't recognised by the extractor. Since the ID format seems to be the same, this might be enough, but it needs an account and/or geo-unblocking to test:
```diff
--- /tmp/meld-tmpwucun0pd
+++ /home/df/Documents/src/yt-dlp/yt_dlp/extractor/rds.py
@@ -9,7 +9,7 @@
 
 class RDSIE(InfoExtractor):
     IE_DESC = 'RDS.ca'
-    _VALID_URL = r'https?://(?:www\.)?rds\.ca/vid(?:[eé]|%C3%A9)os/(?:[^/]+/)*(?P<id>[^/]+)-\d+\.\d+'
+    _VALID_URL = r'https?://(?:www\.)?rds\.ca/(?:vid(?:[eé]|%C3%A9)o|emission)s/(?:[^/]+/)*(?P<id>[^/]+)-\d+\.\d+'
 
     _TESTS = [{
         # has two 9c9media ContentPackages, the web player selects the first ContentPackage
```

**Comment by helsan74** [comment]
I have an account and I used the Get cookies.txt LOCALLY extension.

Do you need more details or tests from my part?

**Comment by bashonly** [comment]
@helsan74 you could test this [patched build](https://github.com/bashonly/yt-dlp/releases/tag/2023.10.12.234132)

to install, either download it from the above link, or you can just run:
```
yt-dlp --update-to bashonly/yt-dlp@2023.10.12.234132
```

**Comment by helsan74** [comment]
[RDS] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[RDS] la-boxe-a-rds-gym-bermudez-vs-clavel: Downloading webpage
WARNING: [RDS] unable to extract upload date; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [RDS] unable to extract duration; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[9c9media] Extracting URL: 9c9media:rds_web:582906
[9c9media] 582906: Downloading JSON metadata
ERROR: [9c9media] 582906: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

D:\yt-dlp>yt-dlp -vU --cookies d:\yt-dlp\cookies.txt https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[debug] Command-line config: ['-vU', '--cookies', 'd:\\yt-dlp\\cookies.txt', 'https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.12.234132 [073c8a0a6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112441-gc06d3d2404-20231010 (setts), ffprobe N-112441-gc06d3d2404-20231010
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1887 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.12.234132
Current Build Hash: 9bc63c2f2abef07e1176e0646549c56cc69d818edb5c9f430478d9e14dc96c4d
yt-dlp is up to date (stable@2023.10.12.234132)
[RDS] Extracting URL: https://www.rds.ca/emissions/en-direct/videotheque/la-boxe-a-rds-gym-bermudez-vs-clavel-3.1432385
[RDS] la-boxe-a-rds-gym-bermudez-vs-clavel: Downloading webpage
WARNING: [RDS] unable to extract upload date; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [RDS] unable to extract duration; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Using fake IP 99.239.111.57 (CA) as X-Forwarded-For
[9c9media] Extracting URL: 9c9media:rds_web:582906
[9c9media] 582906: Downloading JSON metadata
ERROR: [9c9media] 582906: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\ninecninemedia.py", line 19, in _real_extract
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 1033, in download_handle
  File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage

  File "yt_dlp\networking\_urllib.py", line 410, in _send
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 415, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4070, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found

**Comment by helsan74** [comment]
The link I have is valid because inside the browser I'm able to view the show with the command linke i get a 404

**Comment by bashonly** [comment]
Ok, it looks like the extractor needs more fixes.

Can you confirm that the video plays in a browser [with DRM disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)?

**Comment by helsan74** [comment]
No it doesn't play.
I get a message at the top of my browser saying that "you must enable DRM to play some audio or video on this page"

**Comment by dirkf** [comment]
It's not surprising that boxing should be DRM-ed. It might be worth checking some other, especially locally produced, videothèque content in case DRM is not universal.
