### ISSUE TITLE
Aria2 Exit Code 22

### ISSUE THREAD

**Issue by pinknosehappy** [yt-dlp/yt-dlp#8365]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I am trying to install a playlist, a large video over 20 minutes long when yt-dlp fails with "aria2 exit code 22." I've tried to fix this on aria2's end, but the console only lets me fix it with --user-agent if I'm not on yt-dlp. I've reinstalled both aria2 and yt-dlp to the latest versions. It is just a standard YouTube playlist link that has worked 100 times in the past but broke now.  

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--format', 'mp4', '--yes-playlist', 'https://www.youtube.com/playlist?list=PLG3q3Z8uZ0OX5ZjIkCBpz3zHqsq6u3Nni']
[debug] User config "C:\Users\cacom\AppData\Roaming\yt-dlp\config.txt": ['--downloader', 'aria2c', '--downloader-args', 'aria2c:-c -j 3 -x 3 -s 3 -k 1M', '--downloader', 'dash,m3u8:native', '--restrict-filenames', '--merge-output-format', 'mkv']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.4 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.03.04
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLG3q3Z8uZ0OX5ZjIkCBpz3zHqsq6u3Nni
[youtube:tab] PLG3q3Z8uZ0OX5ZjIkCBpz3zHqsq6u3Nni: Downloading webpage
[youtube:tab] PLG3q3Z8uZ0OX5ZjIkCBpz3zHqsq6u3Nni: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Class of 2022
[youtube:tab] PLG3q3Z8uZ0OX5ZjIkCBpz3zHqsq6u3Nni page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (1/3)...
[youtube:tab] PLG3q3Z8uZ0OX5ZjIkCBpz3zHqsq6u3Nni page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (2/3)...
[youtube:tab] PLG3q3Z8uZ0OX5ZjIkCBpz3zHqsq6u3Nni page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (3/3)...
[youtube:tab] PLG3q3Z8uZ0OX5ZjIkCBpz3zHqsq6u3Nni page 1: Downloading API JSON
ERROR: Incomplete data received
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\utils.py", line 3075, in <lambda>
    return type(self.ydl)._handle_extraction_exceptions(lambda _, i: self._entries[i])(self.ydl, i)
  File "C:\Python310\lib\site-packages\yt_dlp\utils.py", line 2843, in __getitem__
    self._cache.extend(itertools.islice(self._iterable, n))
  File "C:\Python310\lib\site-packages\yt_dlp\extractor\youtube.py", line 4734, in _entries
    response = self._extract_response(
  File "C:\Python310\lib\site-packages\yt_dlp\extractor\youtube.py", line 908, in _extract_response
    for retry in self.RetryManager():
  File "C:\Python310\lib\site-packages\yt_dlp\utils.py", line 6141, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "C:\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 3728, in _error_or_warning
    RetryManager.report_retry(
  File "C:\Python310\lib\site-packages\yt_dlp\utils.py", line 6149, in report_retry
    raise e
yt_dlp.utils.ExtractorError: Incomplete data received

[youtube:tab] Playlist Class of 2022: Downloading 23 items of 22
[download] Downloading item 1 of 23
[youtube] Extracting URL: https://www.youtube.com/watch?v=qx10qr69RGI
[youtube] qx10qr69RGI: Downloading webpage
[youtube] qx10qr69RGI: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] qx10qr69RGI: Downloading 1 format(s): 22
[debug] Invoking aria2c downloader on "https://rr4---sn-a5meknzs.googlevideo.com/videoplayback?expire=1697545771&ei=yykuZe7_DviLsfIPxICr4AQ&ip=47.151.49.244&id=o-AAKxg2PUYVUD223vk1ZtrWzSiQ6dO1SU1N7Fm85z9fYO&itag=22&source=youtube&requiressl=yes&mh=jj&mm=31%2C26&mn=sn-a5meknzs%2Csn-vgqsknzk&ms=au%2Conr&mv=m&mvi=4&pl=13&initcwndbps=1380000&spc=UWF9fx25SLtxtfu6wka-srE54nuHK1CJbVdOuW50SQ&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=834.060&lmt=1671503532537832&mt=1697523911&fvip=2&fexp=24007246&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIgeKrP9L-l-L19dFWAHfms8soJsskcXlnKtgptqngEv1cCIQDeUahcvK5wD1rSO2YYpdNzBBO3x7T5dM2sXKOpN_ggcA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgCHJTWU1PsfsYKXl7owGnQN8Uflyph1G84A7FyLIJ15YCIB7k9EbALDOop3IDe9CDN7hxX1UyXz77EYF5uZ0mpV2I"
[download] Destination: Internet_Comment_Etiquette_-_What_Do_You_Want_for_Christmas-[qx10qr69RGI].mp4
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--http-accept-gzip=true" "--file-allocation=none" -x16 -j16 -s16 --min-split-size 1M --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" -c -j 3 -x 3 -s 3 -k 1M --out ".\Internet_Comment_Etiquette_-_What_Do_You_Want_for_Christmas-[qx10qr69RGI].mp4.part" "--auto-file-renaming=false" -- "https://rr4---sn-a5meknzs.googlevideo.com/videoplayback?expire=1697545771&ei=yykuZe7_DviLsfIPxICr4AQ&ip=47.151.49.244&id=o-AAKxg2PUYVUD223vk1ZtrWzSiQ6dO1SU1N7Fm85z9fYO&itag=22&source=youtube&requiressl=yes&mh=jj&mm=31%2C26&mn=sn-a5meknzs%2Csn-vgqsknzk&ms=au%2Conr&mv=m&mvi=4&pl=13&initcwndbps=1380000&spc=UWF9fx25SLtxtfu6wka-srE54nuHK1CJbVdOuW50SQ&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=834.060&lmt=1671503532537832&mt=1697523911&fvip=2&fexp=24007246&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIgeKrP9L-l-L19dFWAHfms8soJsskcXlnKtgptqngEv1cCIQDeUahcvK5wD1rSO2YYpdNzBBO3x7T5dM2sXKOpN_ggcA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgCHJTWU1PsfsYKXl7owGnQN8Uflyph1G84A7FyLIJ15YCIB7k9EbALDOop3IDe9CDN7hxX1UyXz77EYF5uZ0mpV2I"

10/16 23:29:32 [ERROR] CUID#7 - Download aborted. URI=https://rr4---sn-a5meknzs.googlevideo.com/videoplayback?expire=1697545771&ei=yykuZe7_DviLsfIPxICr4AQ&ip=47.151.49.244&id=o-AAKxg2PUYVUD223vk1ZtrWzSiQ6dO1SU1N7Fm85z9fYO&itag=22&source=youtube&requiressl=yes&mh=jj&mm=31%2C26&mn=sn-a5meknzs%2Csn-vgqsknzk&ms=au%2Conr&mv=m&mvi=4&pl=13&initcwndbps=1380000&spc=UWF9fx25SLtxtfu6wka-srE54nuHK1CJbVdOuW50SQ&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=834.060&lmt=1671503532537832&mt=1697523911&fvip=2&fexp=24007246&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIgeKrP9L-l-L19dFWAHfms8soJsskcXlnKtgptqngEv1cCIQDeUahcvK5wD1rSO2YYpdNzBBO3x7T5dM2sXKOpN_ggcA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgCHJTWU1PsfsYKXl7owGnQN8Uflyph1G84A7FyLIJ15YCIB7k9EbALDOop3IDe9CDN7hxX1UyXz77EYF5uZ0mpV2I
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://rr4---sn-a5meknzs.googlevideo.com/videoplayback?expire=1697545771&ei=yykuZe7_DviLsfIPxICr4AQ&ip=47.151.49.244&id=o-AAKxg2PUYVUD223vk1ZtrWzSiQ6dO1SU1N7Fm85z9fYO&itag=22&source=youtube&requiressl=yes&mh=jj&mm=31%2C26&mn=sn-a5meknzs%2Csn-vgqsknzk&ms=au%2Conr&mv=m&mvi=4&pl=13&initcwndbps=1380000&spc=UWF9fx25SLtxtfu6wka-srE54nuHK1CJbVdOuW50SQ&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=834.060&lmt=1671503532537832&mt=1697523911&fvip=2&fexp=24007246&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIgeKrP9L-l-L19dFWAHfms8soJsskcXlnKtgptqngEv1cCIQDeUahcvK5wD1rSO2YYpdNzBBO3x7T5dM2sXKOpN_ggcA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgCHJTWU1PsfsYKXl7owGnQN8Uflyph1G84A7FyLIJ15YCIB7k9EbALDOop3IDe9CDN7hxX1UyXz77EYF5uZ0mpV2I
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.


ERROR: aria2c exited with code 22
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Python310\lib\site-packages\yt_dlp\__init__.py", line 967, in main
    _exit(*variadic(_real_main(argv)))
  File "C:\Python310\lib\site-packages\yt_dlp\__init__.py", line 957, in _real_main
    return ydl.download(all_urls)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3369, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3344, in wrapper
    res = func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1744, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1888, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, collections.ChainMap({
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1920, in __process_iterable_entry
    return self.process_ie_result(
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1694, in process_ie_result
    return self.extract_info(
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2779, in process_video_result
    self.process_info(new_info)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3247, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2970, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Python310\lib\site-packages\yt_dlp\downloader\external.py", line 76, in real_download
    self.report_error('%s exited with code %d' % (
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 944, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


[download] Downloading item 2 of 23
[youtube] Extracting URL: https://www.youtube.com/watch?v=RcxX8ZlLyN0
[youtube] RcxX8ZlLyN0: Downloading webpage
[youtube] RcxX8ZlLyN0: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] RcxX8ZlLyN0: Downloading 1 format(s): 22
[debug] Invoking aria2c downloader on "https://rr3---sn-a5msenek.googlevideo.com/videoplayback?expire=1697545773&ei=zSkuZbHpA_OUsfIPucS5MA&ip=47.151.49.244&id=o-AIRp2tG0b66JRulQdBcVvoVklmC7XfSf_9sVbLqvsoSd&itag=22&source=youtube&requiressl=yes&mh=sK&mm=31%2C26&mn=sn-a5msenek%2Csn-vgqsrn67&ms=au%2Conr&mv=m&mvi=3&pl=13&initcwndbps=1367500&spc=UWF9fyd026Q0nCzybWScc1UVsYRsXXc5pt98ym-IcQ&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=641.962&lmt=1669711582745049&mt=1697523671&fvip=2&fexp=24007246&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIhAN6hgMPHo4SmKb4yy7SHdD0O8pkBIobKQ9rf_2JdM_a-AiB9s1T5Cvg7-O_ZYtZMph91pC35FK1ZH-9J-a40dLxFrw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRQIhAPlj8AT-IRbPf3NWbcVarRmjNkdYxf5XoPeSwMoBgy79AiBXXNsF1ZHeOVvafv0bhtYuMYGKJylreI1D6bBdTQWmEg%3D%3D"
[download] Destination: Internet_Comment_Etiquette_-_Soccer_is_Stupid-[RcxX8ZlLyN0].mp4
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--http-accept-gzip=true" "--file-allocation=none" -x16 -j16 -s16 --min-split-size 1M --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" -c -j 3 -x 3 -s 3 -k 1M --out ".\Internet_Comment_Etiquette_-_Soccer_is_Stupid-[RcxX8ZlLyN0].mp4.part" "--auto-file-renaming=false" -- "https://rr3---sn-a5msenek.googlevideo.com/videoplayback?expire=1697545773&ei=zSkuZbHpA_OUsfIPucS5MA&ip=47.151.49.244&id=o-AIRp2tG0b66JRulQdBcVvoVklmC7XfSf_9sVbLqvsoSd&itag=22&source=youtube&requiressl=yes&mh=sK&mm=31%2C26&mn=sn-a5msenek%2Csn-vgqsrn67&ms=au%2Conr&mv=m&mvi=3&pl=13&initcwndbps=1367500&spc=UWF9fyd026Q0nCzybWScc1UVsYRsXXc5pt98ym-IcQ&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=641.962&lmt=1669711582745049&mt=1697523671&fvip=2&fexp=24007246&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIhAN6hgMPHo4SmKb4yy7SHdD0O8pkBIobKQ9rf_2JdM_a-AiB9s1T5Cvg7-O_ZYtZMph91pC35FK1ZH-9J-a40dLxFrw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRQIhAPlj8AT-IRbPf3NWbcVarRmjNkdYxf5XoPeSwMoBgy79AiBXXNsF1ZHeOVvafv0bhtYuMYGKJylreI1D6bBdTQWmEg%3D%3D"
[#28e1f0 0B/0B CN:1 DL:0B]
10/16 23:29:35 [ERROR] CUID#7 - Download aborted. URI=https://rr3---sn-a5msenek.googlevideo.com/videoplayback?expire=1697545773&ei=zSkuZbHpA_OUsfIPucS5MA&ip=47.151.49.244&id=o-AIRp2tG0b66JRulQdBcVvoVklmC7XfSf_9sVbLqvsoSd&itag=22&source=youtube&requiressl=yes&mh=sK&mm=31%2C26&mn=sn-a5msenek%2Csn-vgqsrn67&ms=au%2Conr&mv=m&mvi=3&pl=13&initcwndbps=1367500&spc=UWF9fyd026Q0nCzybWScc1UVsYRsXXc5pt98ym-IcQ&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=641.962&lmt=1669711582745049&mt=1697523671&fvip=2&fexp=24007246&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIhAN6hgMPHo4SmKb4yy7SHdD0O8pkBIobKQ9rf_2JdM_a-AiB9s1T5Cvg7-O_ZYtZMph91pC35FK1ZH-9J-a40dLxFrw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRQIhAPlj8AT-IRbPf3NWbcVarRmjNkdYxf5XoPeSwMoBgy79AiBXXNsF1ZHeOVvafv0bhtYuMYGKJylreI1D6bBdTQWmEg%3D%3D
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://rr3---sn-a5msenek.googlevideo.com/videoplayback?expire=1697545773&ei=zSkuZbHpA_OUsfIPucS5MA&ip=47.151.49.244&id=o-AIRp2tG0b66JRulQdBcVvoVklmC7XfSf_9sVbLqvsoSd&itag=22&source=youtube&requiressl=yes&mh=sK&mm=31%2C26&mn=sn-a5msenek%2Csn-vgqsrn67&ms=au%2Conr&mv=m&mvi=3&pl=13&initcwndbps=1367500&spc=UWF9fyd026Q0nCzybWScc1UVsYRsXXc5pt98ym-IcQ&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=641.962&lmt=1669711582745049&mt=1697523671&fvip=2&fexp=24007246&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIhAN6hgMPHo4SmKb4yy7SHdD0O8pkBIobKQ9rf_2JdM_a-AiB9s1T5Cvg7-O_ZYtZMph91pC35FK1ZH-9J-a40dLxFrw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRQIhAPlj8AT-IRbPf3NWbcVarRmjNkdYxf5XoPeSwMoBgy79AiBXXNsF1ZHeOVvafv0bhtYuMYGKJylreI1D6bBdTQWmEg%3D%3D  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.


ERROR: aria2c exited with code 22
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Python310\lib\site-packages\yt_dlp\__init__.py", line 967, in main
    _exit(*variadic(_real_main(argv)))
  File "C:\Python310\lib\site-packages\yt_dlp\__init__.py", line 957, in _real_main
    return ydl.download(all_urls)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3369, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3344, in wrapper
    res = func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1744, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1888, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, collections.ChainMap({
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1920, in __process_iterable_entry
    return self.process_ie_result(
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1694, in process_ie_result
    return self.extract_info(
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2779, in process_video_result
    self.process_info(new_info)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3247, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2970, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Python310\lib\site-packages\yt_dlp\downloader\external.py", line 76, in real_download
    self.report_error('%s exited with code %d' % (
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 944, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by bashonly** [comment]
> [debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)

update yt-dlp
