### ISSUE TITLE
(reddit.com) Videos linked/embedded in posts can't be downloaded

### ISSUE THREAD

**Issue by PVCParrot** [yt-dlp/yt-dlp#8381]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Sweden

### Example URLs

https://reddit.com/link/178yasm/video/p5rowtg41iub1/player

### Provide a description that is worded well enough to be understood

Reddit posts can have videos embedded in them now and in old reddit they are just rendered as links like the one above, example of a post with videos linked: https://old.reddit.com/r/uBlockOrigin/comments/178yasm/youtube_antiadblock_and_ads_october_16_2023/

These links can be clicked and played in a fullscreen player but yt-dlp can't download them sadly.

I wasn't sure what type of issue this should be so I hope this is correct..

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
.\yt-dlp.exe -vU https://reddit.com/link/178yasm/video/p5rowtg41iub1/player
[debug] Command-line config: ['-vU', 'https://reddit.com/link/178yasm/video/p5rowtg41iub1/player']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.10.15.085452 [4e38e2ae9] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.0.6, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.10.15.085452, Current version: nightly@2023.10.15.085452
Current Build Hash: 9166198bb7bbe419d352dc0dbc218c05fc5c7027729d0a727339171f3ecf2514
yt-dlp is up to date (nightly@2023.10.15.085452)
[generic] Extracting URL: https://reddit.com/link/178yasm/video/p5rowtg41iub1/player
[generic] player: Downloading webpage
[redirect] Following redirect to https://www.reddit.com/link/178yasm/video/p5rowtg41iub1/player
[generic] Extracting URL: https://www.reddit.com/link/178yasm/video/p5rowtg41iub1/player
[generic] player: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] player: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.reddit.com/link/178yasm/video/p5rowtg41iub1/player
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2575, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.reddit.com/link/178yasm/video/p5rowtg41iub1/player
```

**Comment by VolatileCable** [comment]
If you want to just download them, you can use the link of the post.

**Comment by dirkf** [comment]
If these player URLs are made available in the site UI, eg by a Share function, they should be supported.

This approach worked, while also fetching available metadata not provided directly in the player page itself:
* extract the `<div ....>` element with id `video-{thread_id}`, where `thread_id` is `178yasm` in the example
* extract default `data` from the URL in its `data-link-url` attribute
* replace `data['media_metadata']` with a list containing a single media item comprising the `dashUrl` and `hlsUrl` from the `data-mpd-url` and `data-hsl-url` attributes of the `#video-{thread_id}` element
* complete the extraction from `data`, more-or-less as before.
