### ISSUE TITLE
CBC gem unsupported URL error for standalone movies/specials

### ISSUE THREAD

**Issue by h0m3rth0mps0n** [yt-dlp/yt-dlp#8382]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

I get an "unsupported url" error when trying to download from a supported site, gem.cbc.ca.
Expected outcome: the video should download.

I'll note cbc gem isn't completely broken.  I also tried to download https://gem.cbc.ca/the-passionate-eye/s03e06, and that one worked.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-Uv', '--username', 'PRIVATE', '--password', 'PRIVATE', '-fbv+ba', 'https://gem.cbc.ca/score-a-hockey-musical']
[debug] Portable config "D:\videodownload\yt-dlp.conf": ['-N', '8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-105441-g61cbfdc0a2-20220201 (setts), ffprobe N-105441-g61cbfdc0a2-20220201
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://gem.cbc.ca/score-a-hockey-musical
[generic] score-a-hockey-musical: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] score-a-hockey-musical: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://gem.cbc.ca/score-a-hockey-musical
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2575, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://gem.cbc.ca/score-a-hockey-musical
```

**Comment by bashonly** [comment]
Workaround: pass the URL as `https://gem.cbc.ca/score-a-hockey-musical/s01e01`

The CBC Gem extractor and the CBC Extractor API always expect a `/s??e??` in the URL slug, even for one-off specials.

We could do something like this:
```diff
diff --git a/yt_dlp/extractor/cbc.py b/yt_dlp/extractor/cbc.py
index be2d13e44..c0fd4d888 100644
--- a/yt_dlp/extractor/cbc.py
+++ b/yt_dlp/extractor/cbc.py
@@ -264,7 +264,7 @@ def entries():
 
 class CBCGemIE(InfoExtractor):
     IE_NAME = 'gem.cbc.ca'
-    _VALID_URL = r'https?://gem\.cbc\.ca/(?:media/)?(?P<id>[0-9a-z-]+/s[0-9]+[a-z][0-9]+)'
+    _VALID_URL = r'https?://gem\.cbc\.ca/(?:media/)?(?P<id>[0-9a-z-]+(?:/s[0-9]+[a-z][0-9]+)?)/?(?:$|[#?])'
     _TESTS = [{
         # This is a normal, public, TV show video
         'url': 'https://gem.cbc.ca/media/schitts-creek/s06e01',
@@ -411,6 +411,8 @@ def _find_secret_formats(self, formats, video_id):
 
     def _real_extract(self, url):
         video_id = self._match_id(url)
+        if '/' not in video_id:
+            video_id += '/s01e01'
         video_info = self._download_json(
             f'https://services.radio-canada.ca/ott/cbc-api/v2/assets/{video_id}',
             video_id, expected_status=426)
```

although it would have the side effect of also matching URLs like `https://gem.cbc.ca/browse`

also, when I was experimenting with the extractor, I noticed that the `timestamp` value was being extracted in milliseconds instead of seconds, and would cause an `OverflowError` if my output template contained something like `%(timestamp>%Y%m%d)s`. So we could also fix that, e.g.

```diff
diff --git a/yt_dlp/extractor/cbc.py b/yt_dlp/extractor/cbc.py
index be2d13e44..d6bc7db02 100644
--- a/yt_dlp/extractor/cbc.py
+++ b/yt_dlp/extractor/cbc.py
@@ -461,8 +461,8 @@ def _real_extract(self, url):
             'duration': video_info.get('duration'),
             'categories': [video_info.get('category')],
             'formats': formats,
-            'release_timestamp': video_info.get('airDate'),
-            'timestamp': video_info.get('availableDate'),
+            'release_timestamp': int_or_none(video_info.get('airDate'), scale=1000),
+            'timestamp': int_or_none(video_info.get('availableDate'), scale=1000),
         }
 
 
```

**Comment by gamer191** [comment]
> ```diff
> +        if '/' not in video_id:
> +            video_id += '/s01e01'
> ```

What does the website append to API calls? Imo we should try to emulate the website when possible


> although it would have the side effect of also matching URLs like `https://gem.cbc.ca/browse`

My guess would be that those would currently fail, and would continue to fail, so it doesn't really matter

**Comment by bashonly** [comment]
> What does the website append to API calls? Imo we should try to emulate the website when possible

it appends `/s01e01`

**Comment by h0m3rth0mps0n** [comment]
Thanks for the workaround.  I'm able to download the video this way.

As for the proposed fix, if I may add my two cents.. this would also cause urls like https://gem.cbc.ca/the-passionate-eye/ to implicitly go and download s01e01, would it not?  May or may not be desirable 🤷‍♂️

**Comment by bashonly** [comment]
>  this would also cause urls like https://gem.cbc.ca/the-passionate-eye/ to implicitly go and download s01e01, would it not? May or may not be desirable

Correct. Although full series links are not currently supported, either; only individual season links are supported. Seems our only choices are either to implement the `s01e01` workaround in code and accept the side effect that series URLs will extract the 1st episode, or else keep things as they are and have users manually workaround the issue

**Comment by makew0rld** [comment]
Working on this now, looks like I can just use the Next.js JSON in the HTML to figure out whether the URL is for a standalone video (like this issue is about) or a series.

**Comment by makew0rld** [comment]
Ok I've opened a PR that should address this: #8790

**Comment by veterinarianlocal489** [comment]
I'm having this issue with https://gem.cbc.ca/curling-canada-vs-czechia-mixed-doubles-round-robin-30021

The workaround of https://gem.cbc.ca/curling-canada-vs-czechia-mixed-doubles-round-robin-30021/s01e01 did not work

```
[debug] Command-line config: ['-vU', 'https://gem.cbc.ca/curling-canada-vs-czechia-mixed-doubles-round-robin-30021/s01e01', '-u', 'PRIVATE', '-p', 'PRIVATE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2026.02.04.233607 from yt-dlp/yt-dlp-nightly-builds [442c90da3] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26200-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-122609-g364d5dda91-20260201 (setts), ffprobe N-122609-g364d5dda91-20260201
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.2.0, certifi-2026.01.04, curl_cffi-0.14.0, mutagen-1.47.0, requests-2.32.5, sqlite3-3.40.1, urllib3-2.6.3, websockets-16.0, yt_dlp_ejs-0.4.0
[debug] JS runtimes: none
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1859 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2026.02.04.233607 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2026.02.04.233607 from yt-dlp/yt-dlp-nightly-builds)
[debug] Using fake IP 99.226.246.79 (CA) as X-Forwarded-For
[debug] Loading cbcgem.token_data from cache
[debug] [gem.cbc.ca] Using cached refresh token
[debug] Loading cbcgem.claims_token from cache
[gem.cbc.ca] Extracting URL: https://gem.cbc.ca/curling-canada-vs-czechia-mixed-doubles-round-robin-30021/s01e01
[gem.cbc.ca] curling-canada-vs-czechia-mixed-doubles-round-robin-30021/s01e01: Downloading JSON metadata
ERROR: [gem.cbc.ca] curling-canada-vs-czechia-mixed-doubles-round-robin-30021/s01e01: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 763, in extract
  File "yt_dlp\extractor\cbc.py", line 703, in _real_extract
  File "yt_dlp\extractor\cbc.py", line 539, in _call_show_api
  File "yt_dlp\extractor\common.py", line 1151, in download_content
  File "yt_dlp\extractor\common.py", line 1109, in download_handle
  File "yt_dlp\extractor\common.py", line 974, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 923, in _request_webpage

  File "yt_dlp\extractor\common.py", line 910, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4260, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 194, in wrapper
  File "yt_dlp\networking\common.py", line 359, in send
  File "yt_dlp\networking\_requests.py", line 361, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

I also tried the PR from @makew0rld but it was a while ago, and it doesn't support user log in. From what I understand, I don't think that fix would work anymore anyway?

**Comment by bashonly** [comment]
@veterinarianlocal489 could you open a new issue please? Olympic event coverage should be handled by the `CBCGemLiveIE` extractor instead, and is unrelated to this issue or the linked PR

**Comment by veterinarianlocal489** [comment]
> [@veterinarianlocal489](https://github.com/veterinarianlocal489) could you open a new issue please? Olympic event coverage should be handled by the `CBCGemLiveIE` extractor instead, and is unrelated to this issue or the linked PR

Ok, I will. Thanks!
