### ISSUE TITLE
[Broken] YouTube said: Unknown error.

### ISSUE THREAD

**Issue by bboymega** [yt-dlp/yt-dlp#839]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['--verbose', '-o', '/mnt/sdb1/Videos/DanceSportTotal/%(title)s.%(ext)s', '-c', '-i', 'https://www.youtube.com/c/DanceSportTotal/videos', '--cookies', '/mnt/sdb1/cookies.txt', '--extractor-args', 'youtube:player_client=android', '--playlist-start=5000']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-81-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: keyring, mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/c/DanceSportTotal/videos
[youtube:tab] DanceSportTotal: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/c/DanceSportTotal/videos
[download] Downloading playlist: DanceSportTotal - Videos
[youtube:tab] UC7nIDQ_jiPsbuK8D1fCjcLA page 1: Downloading API JSON
[youtube:tab] UC7nIDQ_jiPsbuK8D1fCjcLA page 2: Downloading API JSON
[youtube:tab] UC7nIDQ_jiPsbuK8D1fCjcLA page 3: Downloading API JSON
ERROR: YouTube said: Unknown error.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1424, in <lambda>
    lambda self, i: ie_entries[i - 1],
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/utils.py", line 4018, in __getitem__
    self.__cache.extend(itertools.islice(self.__iterable, n))
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 4200, in _smuggle_data
    for entry in entries:
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 3885, in _entries
    response = self._extract_response(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 813, in _extract_response
    self._extract_and_report_alerts(response, expected=False)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 741, in _extract_and_report_alerts
    return self._report_alerts(self._extract_alerts(data), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 738, in _report_alerts
    raise ExtractorError('YouTube said: %s' % errors[-1][1], expected=expected)
yt_dlp.utils.ExtractorError: YouTube said: Unknown error.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

**Comment by jihoonpython** [comment]
유튜브 왭싸이트에서 접속을 시도해야할것이고 wifi를 거쳐 동영상을 받아야한다

**Comment by jihoonpython** [comment]
key가필요할것인데 그것을 해결하려면 구글api에서 받아야한다 아니면 받고

**Comment by jihoonpython** [comment]
라즈베리파이인가요?

**Comment by jihoonpython** [comment]
라즈베리파이4인가요

**Comment by coletdjnz** [comment]
Weird server side issue with YouTube (that message is coming from their API). I've seen this a few times myself.

Retrying should work.

**Comment by jihoonpython** [comment]
아

**Comment by jihoonpython** [comment]
그코드를 보여줄수있나요

**Comment by jihoonpython** [comment]
코드를 보여줘

**Comment by jihoonpython** [comment]
서버측의문제가 확실한가요

**Comment by coletdjnz** [comment]
> 서버측의문제가 확실한가요
"Are server-side issues obvious?"

It depends. e.g. A 5XX HTTP response is usually a server side issue.

**Comment by JohnnyKetch** [comment]
Same problem

**Comment by coletdjnz** [comment]
> Weird server side issue with YouTube (that message is coming from their API). I've seen this a few times myself.
> 
> Retrying should work.

What's annoying about this error is that it is contained within an HTTP 200 response. We usually retry on network errors, however, this is not considered one.

In other words, this error is showing up in the same place we expect the "Playlist does not exist" type errors to be (that we do not want to retry on). So to retry, we might have to hard code this particular one?

**Comment by pukkandan** [comment]
maybe we can retry except in the first page? since we'd expect to see any normal error only there

**Comment by coletdjnz** [comment]
> maybe we can retry except in the first page? since we'd expect to see any normal error only there


?
Looking here: https://github.com/yt-dlp/yt-dlp/blob/a7429aa9fa3bc6616d9861a8ce5584a241a93ecc/yt_dlp/extractor/youtube.py#L816-L822
Since this error is caught and re-thrown here, I think we can get away with adding a check here for this error so it can retry?
