### ISSUE TITLE
player.hotmart.com/embed/ support request

### ISSUE THREAD

**Issue by HBasiony** [yt-dlp/yt-dlp#8397]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Egypt

### Example URLs

- Single video: https://player.hotmart.com/embed/Nq7BgloxRA?signature=mS5gfioiB75ecJOWN6Y6VqxeRGQKe93PLpP3K3KFIBRYlSL5mqmpYIFw6l7aQg32bOvc9Kd46Csp2941z35Gx-XHjS_7aQc3Z9NNMqXLLaaaiidR8wXv760sWHVV6e6OLUY37YzwrYLYufli4dcGwqjLMumo2ZmoAdNGhGbfCAgs9xxIMWwmN-8o1Za-i76W7BfM17zQlOo52IRZ2ePzjiMegOkbgeYIcCSZwnW-wnqTtW6unUALkAnV3GNVpz47olLbkyddM1_TPFYIfJuaja6TJP77mAtWic_pdr4h1FSqKK9iLEVFdmINfquJf9lVWLVJ__8yThaf6UzjG8uyaw==&token=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c&user=94011085

### Provide a description that is worded well enough to be understood

I've been downloading these sorts of videos with m3u8 files like [this one](https://vod-akm.play.hotmart.com/video/Nq7BgloxRA/hls/master-t-1649376497001.m3u8)
but now Access is denied to download the m3u8 file, so any help?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']                                                                                    [debug] Encodings: locale cp1256, fs utf-8, pref cp1256, out utf-8, error utf-8, screen utf-8                           [debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)                                                          [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)                   [debug] exe versions: ffmpeg N-110973-g3cfd85ec20-20230601 (setts), ffprobe 2023-05-31-git-baa9fccf8d-full_build-www.gyan.dev                                                                                                                   [debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3                                                                                                              [debug] Proxy map: {}                                                                                                   [debug] Loaded 1890 extractors                                                                                          [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest                               Available version: stable@2023.10.13, Current version: stable@2023.10.13                                                Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4                                    yt-dlp is up to date (stable@2023.10.13)
```

**Comment by HBasiony** [comment]
The single video link is temporary, I don't know if it will be working for a long time.
I can provide another link if requested.

**Comment by bashonly** [comment]
please share a verbose log of an attempt to download your example URL

**Comment by HBasiony** [comment]
> please share a verbose log of an attempt to download your example URL

yt-dlp https://vod-akm.play.hotmart.com/video/Nq7BgloxRA/hls/master-t-1649376497001.m3u8                 
[generic] Extracting URL: https://vod-akm.play.hotmart.com/video/Nq7BgloxRA/hls/master-t-1649376497001.m3u8             [generic] master-t-1649376497001: Downloading webpage                                                                   
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by bashonly** [comment]
Not the m3u8 URL, the embed URL that you are requesting support for. And add `-vU` to your command

**Comment by HBasiony** [comment]
> Not the m3u8 URL, the embed URL that you are requesting support for. And add `-vU` to your command

Thanks... here it is:



yt-dlp -vU https://player.hotmart.com/embed/Nq7BgloxRA?signature=mS5gfioiB75ecJOWN6Y6VqxeRGQKe93PLpP3K3KFIBRYlSL5mqmpYIFw6l7aQg32bOvc9Kd46Csp2941z35Gx-XHjS_7aQc3Z9NNMqXLLaaaiidR8wXv760sWHVV6e6OLUY37YzwrYLYufli4dcGwqjLMumo2ZmoAdNGhGbfCAgs9xxIMWwmN-8o1Za-i76W7BfM17zQlOo52IRZ2ePzjiMegOkbgeYIcCSZwnW-wnqTtW6unUALkAnV3GNVpz47olLbkyddM1_TPFYIfJuaja6TJP77mAtWic_pdr4h1FSqKK9iLEVFdmINfquJf9lVWLVJ__8yThaf6UzjG8uyaw==&token=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c&user=94011085
[debug] Command-line config: ['-vU', 'https://player.hotmart.com/embed/Nq7BgloxRA?signature=mS5gfioiB75ecJOWN6Y6VqxeRGQKe93PLpP3K3KFIBRYlSL5mqmpYIFw6l7aQg32bOvc9Kd46Csp2941z35Gx-XHjS_7aQc3Z9NNMqXLLaaaiidR8wXv760sWHVV6e6OLUY37YzwrYLYufli4dcGwqjLMumo2ZmoAdNGhGbfCAgs9xxIMWwmN-8o1Za-i76W7BfM17zQlOo52IRZ2ePzjiMegOkbgeYIcCSZwnW-wnqTtW6unUALkAnV3GNVpz47olLbkyddM1_TPFYIfJuaja6TJP77mAtWic_pdr4h1FSqKK9iLEVFdmINfquJf9lVWLVJ__8yThaf6UzjG8uyaw==']
[debug] Encodings: locale cp1256, fs utf-8, pref cp1256, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110973-g3cfd85ec20-20230601 (setts), ffprobe 2023-05-31-git-baa9fccf8d-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://player.hotmart.com/embed/Nq7BgloxRA?signature=mS5gfioiB75ecJOWN6Y6VqxeRGQKe93PLpP3K3KFIBRYlSL5mqmpYIFw6l7aQg32bOvc9Kd46Csp2941z35Gx-XHjS_7aQc3Z9NNMqXLLaaaiidR8wXv760sWHVV6e6OLUY37YzwrYLYufli4dcGwqjLMumo2ZmoAdNGhGbfCAgs9xxIMWwmN-8o1Za-i76W7BfM17zQlOo52IRZ2ePzjiMegOkbgeYIcCSZwnW-wnqTtW6unUALkAnV3GNVpz47olLbkyddM1_TPFYIfJuaja6TJP77mAtWic_pdr4h1FSqKK9iLEVFdmINfquJf9lVWLVJ__8yThaf6UzjG8uyaw==
[generic] Nq7BgloxRA?signature=mS5gfioiB75ecJOWN6Y6VqxeRGQKe93PLpP3K3KFIBRYlSL5mqmpYIFw6l7aQg32bOvc9Kd46Csp2941z35Gx-XHjS_7aQc3Z9NNMqXLLaaaiidR8wXv760sWHVV6e6OLUY37YzwrYLYufli4dcGwqjLMumo2ZmoAdNGhGbfCAgs9xxIMWwmN-8o1Za-i76W7BfM17zQlOo52IRZ2ePzjiMegOkbgeYIcCSZwnW-wnqTtW6unUALkAnV3GNVpz47olLbkyddM1_TPFYIfJuaja6TJP77mAtWic_pdr4h1FSqKK9iLEVFdmINfquJf9lVWLVJ__8yThaf6UzjG8uyaw==: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Nq7BgloxRA?signature=mS5gfioiB75ecJOWN6Y6VqxeRGQKe93PLpP3K3KFIBRYlSL5mqmpYIFw6l7aQg32bOvc9Kd46Csp2941z35Gx-XHjS_7aQc3Z9NNMqXLLaaaiidR8wXv760sWHVV6e6OLUY37YzwrYLYufli4dcGwqjLMumo2ZmoAdNGhGbfCAgs9xxIMWwmN-8o1Za-i76W7BfM17zQlOo52IRZ2ePzjiMegOkbgeYIcCSZwnW-wnqTtW6unUALkAnV3GNVpz47olLbkyddM1_TPFYIfJuaja6TJP77mAtWic_pdr4h1FSqKK9iLEVFdmINfquJf9lVWLVJ__8yThaf6UzjG8uyaw==: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://player.hotmart.com/embed/Nq7BgloxRA?signature=mS5gfioiB75ecJOWN6Y6VqxeRGQKe93PLpP3K3KFIBRYlSL5mqmpYIFw6l7aQg32bOvc9Kd46Csp2941z35Gx-XHjS_7aQc3Z9NNMqXLLaaaiidR8wXv760sWHVV6e6OLUY37YzwrYLYufli4dcGwqjLMumo2ZmoAdNGhGbfCAgs9xxIMWwmN-8o1Za-i76W7BfM17zQlOo52IRZ2ePzjiMegOkbgeYIcCSZwnW-wnqTtW6unUALkAnV3GNVpz47olLbkyddM1_TPFYIfJuaja6TJP77mAtWic_pdr4h1FSqKK9iLEVFdmINfquJf9lVWLVJ__8yThaf6UzjG8uyaw==
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2575, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://player.hotmart.com/embed/Nq7BgloxRA?signature=mS5gfioiB75ecJOWN6Y6VqxeRGQKe93PLpP3K3KFIBRYlSL5mqmpYIFw6l7aQg32bOvc9Kd46Csp2941z35Gx-XHjS_7aQc3Z9NNMqXLLaaaiidR8wXv760sWHVV6e6OLUY37YzwrYLYufli4dcGwqjLMumo2ZmoAdNGhGbfCAgs9xxIMWwmN-8o1Za-i76W7BfM17zQlOo52IRZ2ePzjiMegOkbgeYIcCSZwnW-wnqTtW6unUALkAnV3GNVpz47olLbkyddM1_TPFYIfJuaja6TJP77mAtWic_pdr4h1FSqKK9iLEVFdmINfquJf9lVWLVJ__8yThaf6UzjG8uyaw==

'token' is not recognized as an internal or external command,
operable program or batch file.
'user' is not recognized as an internal or external command,
operable program or batch file.

**Comment by garret1317** [comment]
i just get "Request failed with status code 410" from that url
![image](https://github.com/yt-dlp/yt-dlp/assets/76261416/92a9fe55-b50a-4a2d-9abd-bf8726c223c5)
and a 403 forbidden from the m3u8

**Comment by garret1317** [comment]
this could be closed by #7650

**Comment by Abdess** [comment]
I can confirm that this is a recent issue. Recently, the script is no longer able to get the m3u file on the hotmart platform, it displays a 403 error.

**Comment by clongeau** [comment]
@Abdess to bypass the 403 error, you need to force the referer with : --referer https://player.hotmart.com

**Comment by Jeminko** [comment]
I am really sorry but "--referer https://player.hotmart.com/" does not work for me. Do you please have any other idea for this video?

https://vod-akm.play.hotmart.com/video/Pq022WrDZX/hls/master-t-1705660114001.m3u8?hdnts=st%3D1709893359%7Eexp%3D1709893859%7Ehmac%3Da726f773541db490db3ac7c34507c2e5da26492fa56814a2dac6328d8be8fe19&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c

Thanks a lot.

**Comment by Enzodtz** [comment]
> I am really sorry but "--referer https://player.hotmart.com/" does not work for me. Do you please have any other idea for this video?
> 
> https://vod-akm.play.hotmart.com/video/Pq022WrDZX/hls/master-t-1705660114001.m3u8?hdnts=st%3D1709893359%7Eexp%3D1709893859%7Ehmac%3Da726f773541db490db3ac7c34507c2e5da26492fa56814a2dac6328d8be8fe19&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c
> 
> Thanks a lot.

Same here. From my understanding, seems that adding the referer used to fix the issue, but since some months ago 403s are being returned. 

#3564
https://forum.videohelp.com/threads/412291-Downloading-from-hotmart

**Comment by gamer191** [comment]
> Verbose log of an attempt to download via the embed URL that I'm requesting support for with -vU :

Can you please post a verbose log with the URL in quotation marks (`yt-dlp -vU “URL”`)

**Comment by Jeminko** [comment]
> > Verbose log of an attempt to download via the embed URL that I'm requesting support for with -vU :
> 
> Can you please post a verbose log with the embed URL in quotation marks (`yt-dlp -vU “URL”`)

Here it is:

[debug] Command-line config: ['-vU', 'https://vod-akm.play.hotmart.com/video/Pq022WrDZX/hls/master-t-1705660114001.m3u8?hdnts=st%3D1709893359%7Eexp%3D1709893859%7Ehmac%3Da726f773541db490db3ac7c34507c2e5da26492fa56814a2dac6328d8be8fe19&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.12.2 (CPython x86_64 64bit) - macOS-11.6-x86_64-i386-64bit (OpenSSL 3.2.1 30 Jan 2024)
[debug] exe versions: rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2023.12.30 from yt-dlp/yt-dlp
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[generic] Extracting URL: https://vod-akm.play.hotmart.com/video/Pq022WrDZX/hls/master-t-1705660114001.m3u8?hdnts=st%3D1709893359%7Eexp%3D1709893859%7Ehmac%3Da726f773541db490db3ac7c34507c2e5da26492fa56814a2dac6328d8be8fe19&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c
[generic] master-t-1705660114001: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2023.12.30/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.12.30/libexec/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2392, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.12.30/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 863, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/Cellar/yt-dlp/2023.12.30/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 4082, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.12.30/libexec/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.12.30/libexec/lib/python3.12/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.12.30/libexec/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.12.30/libexec/lib/python3.12/site-packages/yt_dlp/networking/_requests.py", line 343, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2023.12.30/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 850, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.12.30/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 4114, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

Thank you!

**Comment by gamer191** [comment]
Sorry, I meant the embed url, not the m3u8 url

**Comment by pukkandan** [comment]
@gamer191 Is this still `incomplete`?

**Comment by tbaragao** [comment]
Trying to download some video and got same error:

yt-dlp_x86.exe -vU https://player.hotmart.com/embed/DZjd8K8eqg?signature=6g5bsT2bWpaSi97Luih3eUn04NEDoELsPqoK087i3KJjhDpgib9U-3pvxknaLNh2c49ngsafk8567lDfwPBufSZg2K8JSjt1AJCRa8qF4-Sl01mys_7WTPFQOtCnH4AWEi-e7eaRaCDnqLUXgUpGeluYWLWRAVMH4PVjoEHesxZOEZlJmkvZfTmt4ekgjzAmh2FAtKUQfkl5j4WGLidOMurl662HUFsE4Lri4pXMQTmiq5ZW_C4aDNGD4Qcnry5jrTQA75zFTFdRdk9kHauXgASgMBZmsQlMsaD4ZKwsW6lUohkzOL3BOlWeMzru6LUf0zmIg2BYoboQdjpnKv2VgQ%3D%3D&token=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c&user=109556432&autoplay=autoplay
[debug] Command-line config: ['-vU', 'https://player.hotmart.com/embed/DZjd8K8eqg?signature=6g5bsT2bWpaSi97Luih3eUn04NEDoELsPqoK087i3KJjhDpgib9U-3pvxknaLNh2c49ngsafk8567lDfwPBufSZg2K8JSjt1AJCRa8qF4-Sl01mys_7WTPFQOtCnH4AWEi-e7eaRaCDnqLUXgUpGeluYWLWRAVMH4PVjoEHesxZOEZlJmkvZfTmt4ekgjzAmh2FAtKUQfkl5j4WGLidOMurl662HUFsE4Lri4pXMQTmiq5ZW_C4aDNGD4Qcnry5jrTQA75zFTFdRdk9kHauXgASgMBZmsQlMsaD4ZKwsW6lUohkzOL3BOlWeMzru6LUf0zmIg2BYoboQdjpnKv2VgQ%3D%3D']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_x86_exe)
[debug] Python 3.8.10 (CPython AMD64 32bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-06-24-git-6ec22731ae-full_build-www.gyan.dev (setts), ffprobe 2024-06-24-git-6ec22731ae-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://player.hotmart.com/embed/DZjd8K8eqg?signature=6g5bsT2bWpaSi97Luih3eUn04NEDoELsPqoK087i3KJjhDpgib9U-3pvxknaLNh2c49ngsafk8567lDfwPBufSZg2K8JSjt1AJCRa8qF4-Sl01mys_7WTPFQOtCnH4AWEi-e7eaRaCDnqLUXgUpGeluYWLWRAVMH4PVjoEHesxZOEZlJmkvZfTmt4ekgjzAmh2FAtKUQfkl5j4WGLidOMurl662HUFsE4Lri4pXMQTmiq5ZW_C4aDNGD4Qcnry5jrTQA75zFTFdRdk9kHauXgASgMBZmsQlMsaD4ZKwsW6lUohkzOL3BOlWeMzru6LUf0zmIg2BYoboQdjpnKv2VgQ%3D%3D
[generic] DZjd8K8eqg?signature=6g5bsT2bWpaSi97Luih3eUn04NEDoELsPqoK087i3KJjhDpgib9U-3pvxknaLNh2c49ngsafk8567lDfwPBufSZg2K8JSjt1AJCRa8qF4-Sl01mys_7WTPFQOtCnH4AWEi-e7eaRaCDnqLUXgUpGeluYWLWRAVMH4PVjoEHesxZOEZlJmkvZfTmt4ekgjzAmh2FAtKUQfkl5j4WGLidOMurl662HUFsE4Lri4pXMQTmiq5ZW_C4aDNGD4Qcnry5jrTQA75zFTFdRdk9kHauXgASgMBZmsQlMsaD4ZKwsW6lUohkzOL3BOlWeMzru6LUf0zmIg2BYoboQdjpnKv2VgQ==: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] DZjd8K8eqg?signature=6g5bsT2bWpaSi97Luih3eUn04NEDoELsPqoK087i3KJjhDpgib9U-3pvxknaLNh2c49ngsafk8567lDfwPBufSZg2K8JSjt1AJCRa8qF4-Sl01mys_7WTPFQOtCnH4AWEi-e7eaRaCDnqLUXgUpGeluYWLWRAVMH4PVjoEHesxZOEZlJmkvZfTmt4ekgjzAmh2FAtKUQfkl5j4WGLidOMurl662HUFsE4Lri4pXMQTmiq5ZW_C4aDNGD4Qcnry5jrTQA75zFTFdRdk9kHauXgASgMBZmsQlMsaD4ZKwsW6lUohkzOL3BOlWeMzru6LUf0zmIg2BYoboQdjpnKv2VgQ==: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://player.hotmart.com/embed/DZjd8K8eqg?signature=6g5bsT2bWpaSi97Luih3eUn04NEDoELsPqoK087i3KJjhDpgib9U-3pvxknaLNh2c49ngsafk8567lDfwPBufSZg2K8JSjt1AJCRa8qF4-Sl01mys_7WTPFQOtCnH4AWEi-e7eaRaCDnqLUXgUpGeluYWLWRAVMH4PVjoEHesxZOEZlJmkvZfTmt4ekgjzAmh2FAtKUQfkl5j4WGLidOMurl662HUFsE4Lri4pXMQTmiq5ZW_C4aDNGD4Qcnry5jrTQA75zFTFdRdk9kHauXgASgMBZmsQlMsaD4ZKwsW6lUohkzOL3BOlWeMzru6LUf0zmIg2BYoboQdjpnKv2VgQ%3D%3D
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://player.hotmart.com/embed/DZjd8K8eqg?signature=6g5bsT2bWpaSi97Luih3eUn04NEDoELsPqoK087i3KJjhDpgib9U-3pvxknaLNh2c49ngsafk8567lDfwPBufSZg2K8JSjt1AJCRa8qF4-Sl01mys_7WTPFQOtCnH4AWEi-e7eaRaCDnqLUXgUpGeluYWLWRAVMH4PVjoEHesxZOEZlJmkvZfTmt4ekgjzAmh2FAtKUQfkl5j4WGLidOMurl662HUFsE4Lri4pXMQTmiq5ZW_C4aDNGD4Qcnry5jrTQA75zFTFdRdk9kHauXgASgMBZmsQlMsaD4ZKwsW6lUohkzOL3BOlWeMzru6LUf0zmIg2BYoboQdjpnKv2VgQ%3D%3D

'token' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
'user' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
'autoplay' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

**Comment by takanuva15** [comment]
Facing the same issue trying to download an embed url from player.hotmart.com

EDIT:
I was able to get the following solution working: 
1. Download this Chrome extension "[The Stream Detector](https://chromewebstore.google.com/detail/the-stream-detector/iakkmkmhhckcmoiibcfjnooibphlobak)"
2. Download [this Chrome extension](https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) to convert your cookies into a text file
3. Open up the embed player link in its own tab and open the stream detector chrome extension. Change the "copy stream url as" box to "yt-dlp command"
4. Click on one of the urls in the stream detector popup window and it should copy a full yt-dlp command to your clipboard
5. Open the cookies chrome extension from Step 2 and run it to export your cookies to text file
6. Paste the yt-dlp command into a terminal and remove the `--cookies-from-browser chrome` part of the command and replace it with `--cookies ./cookies.txt` so it points to your downloaded cookies.
7. Run the command and it should start downloading

EDIT 2: Lol I rediscovered my comment today 8 months later while trying to get this to work again. Extra tips that may be useful:
- Keep the video playing when you open the stream detector extension
- If there are multiple urls, try the one with "master-pkg" in the name

**Comment by nonab** [comment]
i ran into the same issue and created an extractor for hotmart embeds
