### ISSUE TITLE
zenporn.com support request

### ISSUE THREAD

**Issue by ket395** [yt-dlp/yt-dlp#8398]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Japan

### Example URLs

- Single video https://zenporn.com/video/15570701/pred-345-a-triple-slut-office-lady-harlem-threat-horny-elder-sister-types-will-hit-you-with-a-3-point-combo-and-make-you-creampie-cum-kano-kashii-yui-hatano-himari-kinoshita-scene-2-p2/

### Problem

The downloader yt-dlp cannot download the video from this site. 

Just like on Youtube let the downloader download the video from the url shown in address bar. No login is required to play video.

### Proposed Solution  

**Example url from address bar**   

https://zenporn.com/video/15570701/pred-345-a-triple-slut-office-lady-harlem-threat-horny-elder-sister-types-will-hit-you-with-a-3-point-combo-and-make-you-creampie-cum-kano-kashii-yui-hatano-himari-kinoshita-scene-2-p2/

And from the url shown in **share** menu which is the **same as the one** in the address bar. 

### Optional feature

**Optionally the downloader can use the** link for embedding video below the url given in share menu. Which after removing the extra words is - https://videomanysex.com/embed/2297875/

I assume it's the link to the same video but it can't be played in the browser. Nothing is shown.

###  Extra 

I wanted to add output of the second command but there was no text box. So I just had to paste it after the output of first command.

I tried my best to create this issue. I completed all the requirements. I hope it's clear and helps. English is not my first language. I am not good in writing this foreign language.

Thank you

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://videomanysex.com/embed/2297875/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_x86_exe)
[debug] Python 3.7.9 (CPython AMD64 32bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.31.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 886c73031ff13375df029cbd1ddaca7481c7cba9c8e56d85639c5411268805c7
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://videomanysex.com/embed/2297875/
[generic] 2297875: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2439, in _real_extract
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage

  File "yt_dlp\networking\_urllib.py", line 410, in _send
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 415, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4070, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden



[debug] Command-line config: ['-vU', 'https://zenporn.com/video/15570701/pred-345-a-triple-slut-office-lady-harlem-threat-horny-elder-sister-types-will-hit-you-with-a-3-point-combo-and-make-you-creampie-cum-kano-kashii-yui-hatano-himari-kinoshita-scene-2-p2/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_x86_exe)
[debug] Python 3.7.9 (CPython AMD64 32bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.31.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 886c73031ff13375df029cbd1ddaca7481c7cba9c8e56d85639c5411268805c7
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://zenporn.com/video/15570701/pred-345-a-triple-slut-office-lady-harlem-threat-horny-elder-sister-types-will-hit-you-with-a-3-point-combo-and-make-you-creampie-cum-kano-kashii-yui-hatano-himari-kinoshita-scene-2-p2/
[generic] pred-345-a-triple-slut-office-lady-harlem-threat-horny-elder-sister-types-will-hit-you-with-a-3-point-combo-and-make-you-creampie-cum-kano-kashii-yui-hatano-himari-kinoshita-scene-2-p2: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] pred-345-a-triple-slut-office-lady-harlem-threat-horny-elder-sister-types-will-hit-you-with-a-3-point-combo-and-make-you-creampie-cum-kano-kashii-yui-hatano-himari-kinoshita-scene-2-p2: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://zenporn.com/video/15570701/pred-345-a-triple-slut-office-lady-harlem-threat-horny-elder-sister-types-will-hit-you-with-a-3-point-combo-and-make-you-creampie-cum-kano-kashii-yui-hatano-himari-kinoshita-scene-2-p2/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2575, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://zenporn.com/video/15570701/pred-345-a-triple-slut-office-lady-harlem-threat-horny-elder-sister-types-will-hit-you-with-a-3-point-combo-and-make-you-creampie-cum-kano-kashii-yui-hatano-himari-kinoshita-scene-2-p2/
```

**Comment by ket395** [comment]
According to this https://zenporn.com/static/2257/ all videos are not fake and not breaking law. 

The site also works from USA.

**Comment by SirElderling** [comment]
I'm looking into creating this extractor.

The video location is retrieved by a call to `https://manysex.com/api/videofile.php?video_id=???&lifetime=8640000`, in which `???` is some sort of an internal video id (this is easily extracted from the zenporn url).
This call returns a json object.

The challenge that I'm currently facing is decoding properly the value of the`video_url` property.
It appears to be a base64 safe URL encoding, but it contains non ASCII characters.

```json
[{"format":".mp4","timelines_count":"31","timelines_interval":"15","video_url":"L2dldF9maWxlLz\u0415vYjU2ZTUxOTU0\u041cTFjOG\u041cxYzRmOGNmNjYyNGQzOT\u041c0ZDdmNT\u04100N2\u0415yZmQ1LzIyOTcw\u041cD\u0410v\u041cjI5Nzg3NS8y\u041cjk3ODc1Lm1wN\u04218,ZD00NTQmYnI9\u041cjcwJnRpPT\u04152OTgx\u041cjk1ODQ~","is_default":1}]
```

**Comment by SirElderling** [comment]
I was able to reverse the js function used by the website. Got this sorted out now.
