### ISSUE TITLE
Unexpected error `nothing to repeat at position 0` in urllib when connecting with proxy

### ISSUE THREAD

**Issue by DL444** [yt-dlp/yt-dlp#8405]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Trying to initiate download from any supported site through proxy will raise an error inside urllib. This happens when yt-dlp tries to make the initial request to the supplied URL. Works fine if proxy is turned off. See verbose output for details.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\DL444\Working> yt-dlp -vU https://www.youtube.com/watch?v=xi1Lq79mLeE
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=xi1Lq79mLeE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22635-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890', 'ftp': 'http://127.0.0.1:7890'}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: [urllib] Unexpected error: error: nothing to repeat at position 0; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 410, in _send
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\networking\_urllib.py", line 264, in <lambda>
  File "yt_dlp\networking\_urllib.py", line 274, in proxy_open
  File "urllib\request.py", line 818, in proxy_open
  File "urllib\request.py", line 2777, in proxy_bypass
  File "urllib\request.py", line 2762, in proxy_bypass_registry
  File "re.py", line 191, in match
  File "re.py", line 304, in _compile
  File "sre_compile.py", line 764, in compile
  File "sre_parse.py", line 948, in parse
  File "sre_parse.py", line 443, in _parse_sub
  File "sre_parse.py", line 668, in _parse
re.error: nothing to repeat at position 0

Traceback (most recent call last):
  File "yt_dlp\__init__.py", line 971, in _real_main
  File "yt_dlp\update.py", line 312, in update
  File "yt_dlp\update.py", line 293, in check_update
  File "yt_dlp\update.py", line 246, in latest_version
  File "yt_dlp\update.py", line 236, in _get_actual_tag
  File "yt_dlp\utils\_utils.py", line 5014, in wrapper
  File "yt_dlp\update.py", line 217, in _get_version_info
  File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
  File "yt_dlp\networking\common.py", line 127, in send
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: 1 unexpected error(s)
[youtube] Extracting URL: https://www.youtube.com/watch?v=xi1Lq79mLeE
[youtube] xi1Lq79mLeE: Downloading webpage
ERROR: [urllib] Unexpected error: error: nothing to repeat at position 0; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 410, in _send
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\networking\_urllib.py", line 264, in <lambda>
  File "yt_dlp\networking\_urllib.py", line 274, in proxy_open
  File "urllib\request.py", line 818, in proxy_open
  File "urllib\request.py", line 2777, in proxy_bypass
  File "urllib\request.py", line 2762, in proxy_bypass_registry
  File "re.py", line 191, in match
  File "re.py", line 304, in _compile
  File "sre_compile.py", line 764, in compile
  File "sre_parse.py", line 948, in parse
  File "sre_parse.py", line 443, in _parse_sub
  File "sre_parse.py", line 668, in _parse
re.error: nothing to repeat at position 0

ERROR: Unable to handle request: 1 unexpected error(s)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\youtube.py", line 4073, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 4032, in _download_player_responses
  File "yt_dlp\extractor\common.py", line 1118, in _download_webpage
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
  File "yt_dlp\networking\common.py", line 127, in send
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: 1 unexpected error(s)
```

**Comment by coletdjnz** [comment]
From a quick look the error appears to be coming from Python internally when it is trying to parse your proxy bypass list.

https://github.com/python/cpython/blob/3.8/Lib/urllib/request.py#L2762

What does your proxy bypass list look like? Perhaps you may have an error in it, or there is a bug with Python parsing it.

**Comment by DL444** [comment]
> Perhaps you may have an error in it

@coletdjnz  You are absolutely right. I checked and found a misconfiguration in the bypass list. It somehow included a `+`. Removing that entry fixed the problem.

Thanks for pointing me to the right direction.
