### ISSUE TITLE
Ruutu: Extractor needs to raise appropriate error when only DRM formats are available

### ISSUE THREAD

**Issue by kobolttti** [yt-dlp/yt-dlp#8448]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Finland

### Provide a description that is worded well enough to be understood

Ruutu works for some videos but fails for others. Failing ones give error "No video formats found!". Multiple non-working videos are found.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Non-working:

$ yt-dlp -vU https://www.ruutu.fi/video/4418865
[debug] Command-line config: ['-vU', 'https://www.ruutu.fi/video/4418865']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-79-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-3.37.2, websockets-9.1, xattr-0.10.1
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[Ruutu] Extracting URL: https://www.ruutu.fi/video/4418865
[Ruutu] 4418865: Downloading XML
ERROR: [Ruutu] 4418865: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/home/xxx/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/xxx/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/xxx/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/xxx/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Ruutu] 4418865: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U


Working:

$ yt-dlp -vU https://www.ruutu.fi/video/4395495
[debug] Command-line config: ['-vU', 'https://www.ruutu.fi/video/4395495']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-79-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-3.37.2, websockets-9.1, xattr-0.10.1
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[Ruutu] Extracting URL: https://www.ruutu.fi/video/4395495
[Ruutu] 4395495: Downloading XML
[Ruutu] 4395495: Downloading authenticated m3u8 stream URL
[Ruutu] 4395495: Downloading m3u8 information
WARNING: [Ruutu] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[Ruutu] 4395495: Downloading authenticated mpd stream URL
[Ruutu] 4395495: Downloading authenticated mp4 stream URL
[Ruutu] 4395495: Checking https URL
[Ruutu] 4395495: https URL is invalid, skipping: HTTP Error 403: Forbidden
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4395495: Downloading 1 format(s): hls-4774
[debug] Invoking hlsnative downloader on "https://nelonenmedia-stream-video-t.nm-stream.nelonenmedia.fi/94/online/video/video_episode_115219294_202310251821.smil/index-f4-v1-a1.m3u8?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTg0MDIyMzQsIm5iZiI6MTY5ODQwMTkzNCwiZXhwIjoxNjk4NDg4NjM0LCJpcCI6Ijg4LjExMy4yMjkuMTc0IiwicGF0aCI6Ii85NC9vbmxpbmUvdmlkZW8vdmlkZW9fZXBpc29kZV8xMTUyMTkyOTRfMjAyMzEwMjUxODIxLnNtaWwvIn0.ExUSXNn1Ke9tRhXetRkYWCR0bDbuR9zH0LO2xq5Mymw"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 567
[download] Destination: Selviytyjät Suomi - Kausi 7 - Jakso 1 [4395495].mp4
```

**Comment by kobolttti** [comment]
Looking from the MPD this is caused by DRM:

[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for out:
ID EXT RESOLUTION │   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────
6  m4a audio only │  128k dash  │ audio only        mp4a.40.2  128k 48k DRM, DASH audio, m4a_dash
2  mp4 768x432    │  899k dash  │ avc1.4D4020  899k video only          DRM, DASH video, mp4_dash
3  mp4 1024x576   │ 1618k dash  │ avc1.4D4020 1618k video only          DRM, DASH video, mp4_dash
4  mp4 1280x720   │ 2709k dash  │ avc1.4D4020 2709k video only          DRM, DASH video, mp4_dash
5  mp4 1920x1080  │ 4726k dash  │ avc1.4D4020 4726k video only          DRM, DASH video, mp4_dash

**Comment by kobolttti** [comment]
Couldn't figure out how to add DRM label. Sorry.
