### ISSUE TITLE
add support for blod.gr

### ISSUE THREAD

**Issue by konos93** [yt-dlp/yt-dlp#8471]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

anywhere

### Example URLs

https://www.blod.gr/lectures/ta-konstantineia-psifidota-tis-rotontas-i-tehni-tou-idanikou
https://www.blod.gr/lectures/i-apeikonisi-tou-theiou-me-ohima-ton-mytho-anamesa-stin-ellada-kai-ti-romi-eisagogikes-paratiriseis/
https://www.blod.gr/lectures/palaiologoi-toixografies-psifidota/

### Provide a description that is worded well enough to be understood

ERROR: Unsupported URL: https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/

it uses vimeo api i can use downloader manager and sometimes  neatdownloader for older links

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\yt-dlp>yt-dlp https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/
[generic] Extracting URL: https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/
[generic] moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas: Extracting information
ERROR: Unsupported URL: https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/

C:\yt-dlp>yt-dlp -vU https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/
[debug] Command-line config: ['-vU', 'https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112179-g56085e057f-20230926 (setts), ffprobe N-112179-g56085e057f-20230926
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.07
Current Build Hash: 7c809be9ad981b2a057bd60d766a9dffb1e88ddea6a9530c416f4741bc297364
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Updating to stable@2023.10.13 ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/latest/download/SHA2-256SUMS
Updated yt-dlp to stable@2023.10.13
[debug] Restarting: yt-dlp -vU "https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/"
[debug] Command-line config: ['-vU', 'https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112179-g56085e057f-20230926 (setts), ffprobe N-112179-g56085e057f-20230926
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/
[generic] moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2575, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.blod.gr/lectures/moriakoi-michanismoi-aytoanosias-rolos-morion-istosymvatotitas/
```

**Comment by pzhlkj6612** [comment]
Triage: A new variant of embedded Vimeo players? #9606

For https://www.blod.gr/lectures/ta-konstantineia-psifidota-tis-rotontas-i-tehni-tou-idanikou :

```html
                <div data-vimeo-id="877108755" data-vimeo-responsive="true" id="video">
                    <div class="totals-video-info">
                        <span class="total-duration">ΔΙΑΡΚΕΙΑ <b>00:49:31</b></span>
                            <span class="total-views">
                                ΠΡΟΒΟΛΕΣ
                                <b>
                                    345
                                </b>
                            </span>
                    </div>
                </div>

```

.

**Comment by bashonly** [comment]
It does look as if this is a general vimeo embed technique, see https://player.vimeo.com/api/player.js :

> "An id or url must be passed, either in an options object or as a data-vimeo-id or data-vimeo-url attribute."

so Vimeo embed extraction could be improved to detect this. But a dedicated extractor for this site is also justified if the site provides more metadata than Vimeo does
