### ISSUE TITLE
site request qos videos

### ISSUE THREAD

**Issue by sm7sm7** [yt-dlp/yt-dlp#8478]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Uk

### Example URLs

https://qosvideos.com/bbc-white-boy-hypnosis/

### Provide a description that is worded well enough to be understood

The site is not supported and no video downloads. 
Very few other tools (none that I found) support this site. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU  'https://qosvideos.com/bbc-white-boy-hypnosis/'
[debug] Command-line config: ['-vU', 'https://qosvideos.com/bbc-white-boy-hypnosis/']
[debug] User config "/home/mark/.config/yt-dlp/config": ['--no-mtime', '-o', './%(title)s.%(ext)s', '-w']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-87-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2022.12.07, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-3.37.2
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: be5cfb6be8930e1a5f427533ec32f2a481276b3da7b249d0150ce2b740ccf1ce
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://qosvideos.com/bbc-white-boy-hypnosis/
[generic] bbc-white-boy-hypnosis: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] bbc-white-boy-hypnosis: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://qosvideos.com/bbc-white-boy-hypnosis/
Traceback (most recent call last):
  File "/home/mark/hid3/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mark/hid3/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
  File "/home/mark/hid3/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/mark/hid3/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2575, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://qosvideos.com/bbc-white-boy-hypnosis/


The contents of my config file is: 
cat /home/mark/.config/yt-dlp/config
# Lines starting with # are comments

# Always extract audio
# -x

# Do not copy the mtime
--no-mtime

# Use this proxy
#--proxy 127.0.0.1:3128

# Save all videos under Movies directory in your home directory
# -o /home/mark/hid3/wgetter/yout/Movies/%(title)s.%(ext)s
-o  './%(title)s.%(ext)s'
# -w = no overwrite 
-w
# --playlist-random
```

**Comment by sm7sm7** [comment]
Ok, dis not use lates version. But issues still exists with latest version, 2023.10.13 . -vU output below: 

[debug] Command-line config: ['-vU', 'https://qosvideos.com/bbc-white-boy-hypnosis/']
[debug] User config "/home/mark/.config/yt-dlp/config": ['--no-mtime', '-o', './%(title)s.%(ext)s', '-w']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-87-generic-x86_64-with-glibc2.35 (OpenSSL 3.1.3 19 Sep 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.43.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 6d30ea8e0f299a91c22161e87746162e3ff4d34df78a7f5dc00d51d02086f908
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://qosvideos.com/bbc-white-boy-hypnosis/
[generic] bbc-white-boy-hypnosis: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] bbc-white-boy-hypnosis: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://qosvideos.com/bbc-white-boy-hypnosis/
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp/extractor/common.py", line 715, in extract
  File "yt_dlp/extractor/generic.py", line 2575, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://qosvideos.com/bbc-white-boy-hypnosis/
