### ISSUE TITLE
ERROR: Unsupported URL: https://futures-infinity.com/security/login ask

### ISSUE THREAD

**Issue by star-genius780** [yt-dlp/yt-dlp#8485]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

block at this url while im fully logged in

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://futures-infinity.com/service/1/features/4/content/318faac9-23c3-4e1c-98ad-bb588a1468fa']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://futures-infinity.com/service/1/features/4/content/318faac9-23c3-4e1c-98ad-bb588a1468fa
[generic] 318faac9-23c3-4e1c-98ad-bb588a1468fa: Downloading webpage
[redirect] Following redirect to https://futures-infinity.com/security/login
[generic] Extracting URL: https://futures-infinity.com/security/login
[generic] login: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] login: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://futures-infinity.com/security/login
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2575, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://futures-infinity.com/security/login
```

**Comment by bashonly** [comment]
Try with [passing cookies to yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp)

**Comment by star-genius780** [comment]
not working

**Comment by bashonly** [comment]
Can you show a log?

> not working

Then it likely needs a dedicated extractor, for which a developer will need account credentials to work on. Are you willing to share yours?

Note: I am not directly asking for your credentials or offering to work on this. I am asking so that another developer will know if it's even possible to work on this

**Comment by star-genius780** [comment]
Extracting cookies from opera
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1008, in main
  File "yt_dlp\__init__.py", line 962, in _real_main
  File "yt_dlp\YoutubeDL.py", line 678, in __init__
  File "yt_dlp\YoutubeDL.py", line 4084, in build_request_director
  File "functools.py", line 967, in __get__
  File "yt_dlp\YoutubeDL.py", line 4018, in cookiejar
  File "yt_dlp\cookies.py", line 91, in load_cookies
  File "yt_dlp\cookies.py", line 112, in extract_cookies_from_browser
  File "yt_dlp\cookies.py", line 273, in _extract_chrome_cookies
FileNotFoundError: could not find opera cookies database in "C:\Users\barka\AppData\Roaming\Opera Software\Opera Stable"
[3240] Failed to execute script '__main__' due to unhandled exception!

**Comment by star-genius780** [comment]
> Can you show a log?
> 
> > not working
> 
> Then it likely needs a dedicated extractor, for which a developer will need account credentials to work on. Are you willing to share yours?
> 
> Note: I am not directly asking for your credentials or offering to work on this. I am asking so that another developer will know if it's even possible to work on this

i prefer if a dev ask me directly for the log

**Comment by bashonly** [comment]
> [3240] Failed to execute script 'main' due to unhandled exception!

- https://github.com/yt-dlp/yt-dlp/issues/7271#issuecomment-1584404779

> i prefer if a dev ask me directly for the log

You don't have to post the credentials publicly, we just need to know if you are willing to share them at all, so developers can know whether or not to bother with this site support request

**Comment by star-genius780** [comment]
> > [3240] Failed to execute script 'main' due to unhandled exception!
> 
> * [`--cookies-from-browser` errors when Chrome/chromium-based browser is open in Windows #7271 (comment)](https://github.com/yt-dlp/yt-dlp/issues/7271#issuecomment-1584404779)
> 
> > i prefer if a dev ask me directly for the log
> 
> You don't have to post the credentials publicly, we just need to know if you are willing to share them at all, so developers can know whether or not to bother with this site support request

okay so yes im willing to share them

**Comment by star-genius780** [comment]
used this but still not working
[15296] Failed to execute script '__main__' due to unhandled exception!
