### ISSUE TITLE
Add support for RTL+ / RTLPlus / https://plus.rtl.de

### ISSUE THREAD

**Issue by ds2k5** [yt-dlp/yt-dlp#8489]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Free Video URL

https://plus.rtl.de/video-tv/serien/legend-of-wacken-942327

$ ./yt-dlp_linux -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.1.0-13-amd64-x86_64-with-glibc2.36 (OpenSSL 3.1.3 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.43.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 6d30ea8e0f299a91c22161e877

$ ./yt-dlp_linux -v https://plus.rtl.de/video-tv/serien/legend-of-wacken-942327/staffel-1-942328/episode-1-painkiller-942329
[debug] Command-line config: ['-v', 'https://plus.rtl.de/video-tv/serien/legend-of-wacken-942327/staffel-1-942328/episode-1-painkiller-942329']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.1.0-13-amd64-x86_64-with-glibc2.36 (OpenSSL 3.1.3 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.43.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[generic] Extracting URL: https://plus.rtl.de/video-tv/serien/legend-of-wacken-942327/staffel-1-942328/episode-1-painkiller-942329
[generic] episode-1-painkiller-942329: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] episode-1-painkiller-942329: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://plus.rtl.de/video-tv/serien/legend-of-wacken-942327/staffel-1-942328/episode-1-painkiller-942329
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp/extractor/common.py", line 715, in extract
  File "yt_dlp/extractor/generic.py", line 2575, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://plus.rtl.de/video-tv/serien/legend-of-wacken-942327/staffel-1-942328/episode-1-painkiller-942329

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by october262** [comment]
it is possible that the free video is DRM protected, 
because it's asking to install the widevine plugin on brave browser and the video 
doesn't play. however it does play in firefox that does have the DRM plugin enabled.

**Comment by ds2k5** [comment]
Hi,
start play the Video -> Pause 
Open Web Developer Tools in Firefox

Open the TAB: Network an search for MPD

![Screenshot_2023-11-11_23-38-41](https://github.com/yt-dlp/yt-dlp/assets/11292286/ebdce204-7fef-4ee4-adfc-3a544d13bcd7)

yt-dlp --allow-u -N 6 -f bv,ba  "https://...../rtlplus.mpd"

But the VIDEO is DRM protected

there should a way with: mp4decrypt
but did not find how

may somebody find how to find the keys in Web Developer Tools
to DeDRM the VIDEO ?!

**Comment by bashonly** [comment]
@ds2k5 do not do that

**Comment by ds2k5** [comment]
@bashonly  sorry

**Comment by SimCrafter** [comment]
I was looking for support for RTL+ too, are there any updates on this?

**Comment by seproDev** [comment]
RTL+ video support can not be added to yt-dlp, due to all videos being DRM protected.

**Comment by dirkf** [comment]
So to resolve this issue at last, a `KnownDRMIE`:
```diff
--- old/yt-dlp/yt_dlp/extractor/unsupported.py
+++ new/yt-dlp/yt_dlp/extractor/unsupported.py
@@ -57,6 +57,7 @@
         r'ctv\.ca',
         r'noovo\.ca',
         r'tsn\.ca',
+        r'plus\.rtl\.de(?!/podcast/)',
     )
 
     _TESTS = [{
```
Or match `(?=/video/)` instead of excluding `/podcast/`?
