### ISSUE TITLE
Mediaset [Broken]

### ISSUE THREAD

**Issue by NicKoehler** [yt-dlp/yt-dlp#849]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp.exe -v "https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-69-pezzo-di-luna_F303843101017801"
```

Returns:

```
[debug] Command-line config: ['-v', 'https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-69-pezzo-di-luna_F303843101017801']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.9.1 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [Mediaset] Extracting URL: https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-69-pezzo-di-luna_F303843101017801
[Mediaset] F303843101017801: Downloading JSON metadata
[Mediaset] F303843101017801: Downloading MPEG4 SMIL data
ERROR: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
Traceback (most recent call last):
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1224, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\common.py", line 575, in extract
    ie_result = self._real_extract(url)
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\mediaset.py", line 155, in _real_extract
    raise first_e
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\mediaset.py", line 142, in _real_extract
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "c:\users\nicola\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\theplatform.py", line 51, in _extract_theplatform_smil
    raise ExtractorError(
yt_dlp.utils.ExtractorError: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
```

Meanwhile this is working fine:

```
yt-dlp.exe -v "https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-1-cestinismo_F303843107006401"
```

## Description

Extraction is not working on some [episodes](https://www.mediasetplay.mediaset.it/serie-tv/cameracafe/episodi_SE000000001091,ST000000001827,sb100004307), is working for the most part, but I have some example where is not.

I can see all episodes with no account on their site, with youtube-dl I can donwload some of them that with yt-dlp can't and vice versa

**Comment by NicKoehler** [comment]
Never mind, now seems like some episodes are not working in the site neither.

**Comment by pukkandan** [comment]
It does however work in youtube-dl, no?

**Comment by NicKoehler** [comment]
Actually [this link](https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-69-pezzo-di-luna_F303843101017801) is not working in the site and yt-dlp, but is working with youtube-dl.

**Comment by pukkandan** [comment]
has been fixed

**Comment by NicKoehler** [comment]
You guys are crazy fast, thanks!

**Comment by NicKoehler** [comment]
I found another one that gives georestriction error, in the browser works fine.
```
yt-dlp.exe -v "https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-51-tu-chi-sei_F303843107000601"
```

Results:

```
[debug] Command-line config: ['-v', 'https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-51-tu-chi-sei_F303843107000601']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.9.1 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [Mediaset] Extracting URL: https://www.mediasetplay.mediaset.it/video/cameracafe5/episodio-51-tu-chi-sei_F303843107000601
[Mediaset] F303843107000601: Downloading JSON metadata
[Mediaset] F303843107000601: Downloading MPEG4 SMIL data
ERROR: [Mediaset] F303843107000601: This content is not available in your location.
Traceback (most recent call last):
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\mediaset.py", line 168, in _real_extract    
    raise first_e
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\mediaset.py", line 155, in _real_extract    
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\theplatform.py", line 44, in _extract_theplatform_smil
    self.raise_geo_restricted(error_element.attrib['abstract'])
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 1071, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
yt_dlp.utils.GeoRestrictedError: This content is not available in your location.
Traceback (most recent call last):
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\mediaset.py", line 168, in _real_extract    
    raise first_e
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\mediaset.py", line 155, in _real_extract    
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\theplatform.py", line 44, in _extract_theplatform_smil
    self.raise_geo_restricted(error_element.attrib['abstract'])
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 1071, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
yt_dlp.utils.GeoRestrictedError: This content is not available in your location.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1239, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Nicola\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 600, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [Mediaset] F303843107000601: This content is not available in your location.
```
