### ISSUE TITLE
Support for NDR Kultur (Audio) audiobooks 

### ISSUE THREAD

**Issue by nadir-yttrium** [yt-dlp/yt-dlp#8496]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Germany

### Example URLs

- Single episode: https://www.ndr.de/kultur/Barbara-Nuesse-liest-Der-Akkordeonspieler-Folge-1,audio1468520.html
- Playlist: https://www.ndr.de/kultur/buch/Barbara-Nuesse-liest-Der-Akkordeonspieler-von-Marie-Luise-Scherer,akkordeonspieler104.html
- Overview of audiobooks: https://www.ndr.de/kultur/sendungen/am_morgen_vorgelesen/index.html

### Provide a description that is worded well enough to be understood

These are publicly available audiobooks that are usually playable for a week after release of an episode.

 The generic downloader worked fine until very recently if you supplied the direct link for the episode. The whole playlist was never recognized. 

I think they might have switched to [podloveplayer](https://podlove.org/podlove-web-player/) recently and yt-dlp doesn't know what to do with that. I'm not sure how popular that player is, but yt-dlp support might help with other sites as well as long as they use that. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
For an episode: 

[debug] Command-line config: ['-vU', 'https://www.ndr.de/kultur/Barbara-Nuesse-liest-Der-Akkordeonspieler-Folge-1,audio1468520.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.6.0-2-cachyos-x86_64-with-glibc2.38 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, secretstorage-3.3.3, sqlite3-3.43.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
WARNING: [generic] Falling back on generic information extractor
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.ndr.de/kultur/audio1468520-podloveplayer.html
Traceback (most recent call last):
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2575, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.ndr.de/kultur/audio1468520-podloveplayer.html

For an audiobook:

[debug] Command-line config: ['-vU', 'https://www.ndr.de/kultur/buch/Barbara-Nuesse-liest-Der-Akkordeonspieler-von-Marie-Luise-Scherer,akkordeonspieler104.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.6.0-2-cachyos-x86_64-with-glibc2.38 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, secretstorage-3.3.3, sqlite3-3.43.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[ndr] Extracting URL: https://www.ndr.de/kultur/buch/Barbara-Nuesse-liest-Der-Akkordeonspieler-von-Marie-Luise-Scherer,akkordeonspieler104.html
[ndr] Barbara-Nuesse-liest-Der-Akkordeonspieler-von-Marie-Luise-Scherer: Downloading webpage
[ndr:embed] Extracting URL: https://www.ndr.de/info/akkordeonspieler104-player.html
[ndr:embed] akkordeonspieler104: Downloading JSON metadata
ERROR: [ndr:embed] akkordeonspieler104: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/extractor/ndr.py", line 236, in _real_extract
    ppjson = self._download_json(
             ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1033, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/networking/_urllib.py", line 410, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4051, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/networking/_urllib.py", line 415, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fqwjdxnmv42f87sx5xrzszw0jsnx8zy9-python3.11-yt-dlp-2023.10.13/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4070, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

**Comment by Rava77** [comment]
@SirElderling _"Therefore, the extractor will most likely need to be rewritten from scratch"_
I presume that such **rewrite from scratch** will take some time...

**Comment by SirElderling** [comment]
> @SirElderling _"Therefore, the extractor will most likely need to be rewritten from scratch"_ I presume that such **rewrite from scratch** will take some time...

Yes, it would take some time yes.
