### ISSUE TITLE
[medias.lenodal.com] Site enhancement: More options & Download all videos from a page

### ISSUE THREAD

**Issue by CeMecCool** [yt-dlp/yt-dlp#8527]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Example URLs

https://medias.lenodal.com/video.php?id=33234

https://medias.lenodal.com/result.php?page=1&lachaine=Toutes&lenom=Tous&lemission=Toutes&lannee=Toutes&lanneeint=&x=46&y=6

https://medias.lenodal.com/result.php?page=1&lachaine=Canal+Plus&lenom=Tous&lemission=Toutes&lannee=Toutes&lanneeint=&x=36&y=11

### Provide a description that is worded well enough to be understood

The site "medias.lenodal.com" is supported using the generic extractor, however this only applies to "individual" videos (those with video.php in the URL) and the options are very limited.

The year of the video, the name of the TV channel and what is the video (e.g the intro of a show or a technical failure of a tv channel) can easily be retrieved from the video.php page and can be used as a field in the output template.

Example:
TV channel = %(channel)s
What is the video = %(title)s
Year = %(release_date)s

![image](https://github.com/yt-dlp/yt-dlp/assets/149938076/1e8018f8-10b6-4825-ba02-4c0d12687b9e)

<hr>

When you paste the URL of a full page, it says that the URL is not supported.

A "full page" (those with result.php in the URL) list videos with javascript redirects as links (e.g. "javascript:opVideo('video.php?id=33183%27);" open the url: "https://medias.lenodal.com/video.php?id=33183" in a new seperate tab.)

<img src="https://github.com/yt-dlp/yt-dlp/assets/149938076/9bbd6450-43c4-4473-9335-f89139a04846" width=50% height=50%>

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://medias.lenodal.com/video.php?id=33234']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112525-g52a9764260-20231027 (setts), ffprobe N-112525-g52a9764260-20231027
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://medias.lenodal.com/video.php?id=33234
[generic] video: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] video: Extracting information
[debug] Looking for embeds
[debug] Identified a JW Player data
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] video: Downloading 1 format(s): 0
[debug] Invoking http downloader on "http://medias.lenodal.com/medias/csat/tmc/tmc-jpubfin-lesreportagesdemartinweill-0sec-2023.mp4"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: vid�o ： Jingle pub fin Les reportages de Martin Weill - TMC (2023) [video].mp4
[download] 100% of    1.58MiB in 00:00:00 at 6.47MiB/s



[debug] Command-line config: ['-vU', 'https://medias.lenodal.com/result.php?page=1&lachaine=Toutes&lenom=Tous&lemission=Toutes&lannee=Toutes&lanneeint=&x=46&y=6']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112525-g52a9764260-20231027 (setts), ffprobe N-112525-g52a9764260-20231027
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://medias.lenodal.com/result.php?page=1&lachaine=Toutes&lenom=Tous&lemission=Toutes&lannee=Toutes&lanneeint=&x=46&y=6
[generic] result: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] result: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://medias.lenodal.com/result.php?page=1&lachaine=Toutes&lenom=Tous&lemission=Toutes&lannee=Toutes&lanneeint=&x=46&y=6
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2575, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://medias.lenodal.com/result.php?page=1&lachaine=Toutes&lenom=Tous&lemission=Toutes&lannee=Toutes&lanneeint=&x=46&y=6
```

**Comment by CeMecCool** [comment]
The "download a whole page" thing is now possible using BeautifulSoup

https://github.com/CeMecCool/lenodal-downloader

The script is not perfect, i'm really bad at coding, it doesn't check when a download is finished and will just download the page before in a loop (when you download multiple pages), but it works i guess?
