### ISSUE TITLE
Support request for mk2curiosity.com

### ISSUE THREAD

**Issue by nodje** [yt-dlp/yt-dlp#8529]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

- Single Video: https://www.mk2curiosity.com/content/a-tayal-90953

### Provide a description that is worded well enough to be understood

I tried using yt-dlp the classic way: `yt-dlp https://www.mk2curiosity.com/content/a-tayal-90953` and got 
```
[generic] Extracting URL: https://www.mk2curiosity.com/content/a-tayal-90953
[generic] a-tayal-90953: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] a-tayal-90953: Extracting information
ERROR: Unsupported URL: https://www.mk2curiosity.com/content/a-tayal-90953
```
I tried with authent since the site requires it to be sure:
`yt-dlp https://www.mk2curiosity.com/content/a-tayal-90953 -u coolnodje@gmail.com` but got the same message.

Searching in the issues and in the supported sites list I couldn't find mk2curiosity.com

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.mk2curiosity.com/content/a-tayal-90953', '-u', 'PRIVATE']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.11.6 (CPython arm64 64bit) - macOS-14.0-arm64-arm-64bit (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.44.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://www.mk2curiosity.com/content/a-tayal-90953
[generic] a-tayal-90953: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] a-tayal-90953: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.mk2curiosity.com/content/a-tayal-90953
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2575, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.mk2curiosity.com/content/a-tayal-90953
```

**Comment by SirElderling** [comment]
This website requires an account. Please include that label for reference.

**Comment by nodje** [comment]
It's under free registration.
I'm not sure I understand which label I should include for reference
