### ISSUE TITLE
digitalconcerthall extractor broken

### ISSUE THREAD

**Issue by dominik-d** [yt-dlp/yt-dlp#8540]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Slovakia

### Provide a description that is worded well enough to be understood

It seems the m3u8 url format has been changed.
Manual download using m3u8 link still possible:
yt_dlp https://world-vod.dchdns.net/shlss/dch/XXXXX-1/,h264_LOW_TWO,h264_LOW_ONE,h264_MEDIUM_TWO,h264_MEDIUM_ONE,h264_HIGH,h264_VERY_HIGH_ONE,flac_AUDIO_STEREO_LOSSLESS,eac3_AUDIO_IMMERSIVE_LOSSY,.mp4.urlset/master.m3u8?token=exp=123456687~acl=/shlss/dch/55029-1/*~hmac=xxxx.xxxx.xxx

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-o', '%%(playlist)s/%%(playlist_index)s-%%(title)s.%%(ext)s', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.digitalconcerthall.com/en/concert/55029', '-f', 'wv+audio0-flac', '--postprocessor-args', '-strict -2', '-vU']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 4.2.3
[debug] Optional libraries: certifi-2023.07.22, sqlite3-3.40.1
[debug] Proxy map: {}
WARNING: Post-Processor arguments given without specifying name. The arguments will be given to all post-processors
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[DigitalConcertHall] Obtaining token
[DigitalConcertHall] Logging in
[DigitalConcertHall] Extracting URL: https://www.digitalconcerthall.com/en/concert/55029
[DigitalConcertHall] 55029: Downloading webpage
[DigitalConcertHall] 55029: Downloading JSON metadata
[download] Downloading playlist: A Mozart concert with Riccardo Minasi
[DigitalConcertHall] 55029-1: Downloading JSON metadata
WARNING: [DigitalConcertHall] Failed to obtain m3u8 URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[DigitalConcertHall] 55029-2: Downloading JSON metadata
WARNING: [DigitalConcertHall] Failed to obtain m3u8 URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[DigitalConcertHall] 55029-3: Downloading JSON metadata
WARNING: [DigitalConcertHall] Failed to obtain m3u8 URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[DigitalConcertHall] 55029-4: Downloading JSON metadata
WARNING: [DigitalConcertHall] Failed to obtain m3u8 URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[DigitalConcertHall] 55029-5: Downloading JSON metadata
WARNING: [DigitalConcertHall] Failed to obtain m3u8 URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[DigitalConcertHall] Playlist A Mozart concert with Riccardo Minasi: Downloading 5 items of 5
[download] Downloading item 1 of 5
ERROR: [DigitalConcertHall] 55029-1: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 2028, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [DigitalConcertHall] 55029-1: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading item 2 of 5
ERROR: [DigitalConcertHall] 55029-2: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 2028, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [DigitalConcertHall] 55029-2: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading item 3 of 5
ERROR: [DigitalConcertHall] 55029-3: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 2028, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [DigitalConcertHall] 55029-3: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading item 4 of 5
ERROR: [DigitalConcertHall] 55029-4: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 2028, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [DigitalConcertHall] 55029-4: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Downloading item 5 of 5
ERROR: [DigitalConcertHall] 55029-5: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 2028, in __process_iterable_entry
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "E:\progs\yt-dlp_202311\yt_dlp\YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [DigitalConcertHall] 55029-5: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[download] Finished downloading playlist: A Mozart concert with Riccardo Minasi
```

**Comment by vincentypy** [comment]
Editing ```extractor/digitalconcerthall.py``` line 100 to this do the trick for now.
```
m3u8_url = traverse_obj(
                stream_info, ('channel', 'temporary_webapp_channel', 'stream', 0, 'url'), get_all=False)
```

It seems that the json data structure has changed, but not sure if it is temporary or permanent.

New structure shown below:
```
{
  "updated": 1699459498,
  "channel": {
    "temporary_webapp_channel": {
      "codec": "mixed_h264_flac_eac3",
      "streaming_technique": "hls_abr_temp",
      "has_audio_only": true,
      "max_resolution": "2160p",
      "dynamic_range": "sdr",
      "is_encrypted": true,
      "stream": [
        {
          "quality": null,
          "audio_language": null,
          "video_language": null,
          "url": "https://world-vod.dchdns.net/shlss/dch/55031-4/,h264_LOW_TWO,h264_LOW_ONE,h264_MEDIUM_TWO,h264_MEDIUM_ONE,h264_HIGH,h264_VERY_HIGH_ONE,flac_AUDIO_STEREO_LOSSLESS,.mp4.urlset/master.m3u8?token=exp=1699481098~acl=/shlss/dch/55031-4/*~hmac=4fa03f1740c3b59c14fddec0d3df8518604a864f77f73311e4121fdfbab2d9e8"
        }
      ]
    }
  },
  "_links": {
    "self": {
      "href": "//api.digitalconcerthall.com/v2/streams/55031-4"
    }
  }
}

```

**Comment by ArnauvGilotra** [comment]
Hey can I pick this issue up? It is my "first issue". Is that okay?

**Comment by pukkandan** [comment]
> Hey can I pick this issue up? It is my "first issue". Is that okay?

Yes

**Comment by vincentypy** [comment]
I can confirm that the json has returned to the original, and works with current release. Presumably no fix should be deployed.
