### ISSUE TITLE
[YouTube] Downloading premieres with `--live-from-start` raises `KeyError('manifest_url')` and leaves behind 'partial' files

### ISSUE THREAD

**Issue by nosoop** [yt-dlp/yt-dlp#8543]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Downloading a premiering YouTube video (live with a predetermined duration) with `--live-from-start` has yt-dlp retry at the end of the premiere, which subsequently raises a `KeyError` on `manifest_url` and causes the application (or script, if invoked without wrapping a try-except) to terminate, leaving behind `.part` and `.ytdl` files.

Downloading the premiering video without `--live-from-start` has yt-dlp exit properly at the end of the premiere.

~~I haven't had the opportunity to test if any of the 'retries' options would work in this case, nor am I familiar with how a zero retry behaves in this situation.~~ Results of experimenting with those options were unsuccessful, per [follow-up comment](https://github.com/yt-dlp/yt-dlp/issues/8543#issuecomment-1803622838)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--live-from-start', 'https://www.youtube.com/watch?v=redacted_id']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.9.2 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1i  8 Dec 2020)
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.45.1, sqlite3-3.34.0, websockets-10.0
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[youtube] Extracting URL: https://www.youtube.com/watch?v=redacted_id
[youtube] redacted_id: Downloading webpage
[youtube] redacted_id: Downloading ios player API JSON
[youtube] redacted_id: Downloading android player API JSON
[youtube] redacted_id: Downloading MPD manifest
[youtube] redacted_id: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] redacted_id: Downloading 1 format(s): 247+140
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/<redacted>"
[dashsegments] Total fragments: unknown (live)
[download] Destination: redacted_id [redacted_id].f247.mkv
[debug] File locking is not supported. Proceeding without locking
[dashsegments] Total fragments: unknown (live)
[download] Destination: redacted_id [redacted_id].f140.mkv
[debug] [youtube] [redacted_id] Generating fragments for format 247
[debug] [youtube] [redacted_id] Generating fragments for format 140
[download]    8.39MiB at      0.00B/s (00:01:06) (frag 38/38)
[download]    2.89MiB at      0.00B/s (00:01:06) (frag 38/38)[youtube] redacted_id: Downloading webpage
[youtube] redacted_id: Downloading ios player API JSON
[youtube] redacted_id: Downloading android player API JSON
[debug] Loading youtube-nsig.9d15588c from cache
[debug] [youtube] Decrypted nsig ClKGCwrlWJFQk6 => Z3NhWuOsspbg3A
[youtube] redacted_id: Downloading m3u8 information
WARNING: [youtube] redacted_id: Video is no longer live. Retrying (1/3)...
WARNING: [youtube] redacted_id: Video is no longer live. Retrying (2/3)...
WARNING: [youtube] redacted_id: Video is no longer live. Retrying (3/3)...
[download] 100% of    8.39MiB in 00:01:15 at 114.43KiB/sERROR: 'manifest_url'
Traceback (most recent call last):
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 2921, in process_video_result
    self.process_info(new_info)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 3334, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\YoutubeDL.py", line 3108, in dl
    return fd.download(name, new_info, subtitle)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\downloader\common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\downloader\dash.py", line 60, in real_download
    return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\downloader\fragment.py", line 421, in download_and_append_fragments_multiple
    result = result and future_result(job)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\downloader\fragment.py", line 397, in future_result
    return future.result(0.1)
  File "<redacted>\python\3.9.2\lib\concurrent\futures\_base.py", line 433, in result
    return self.__get_result()
  File "<redacted>\python\3.9.2\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "<redacted>\python\3.9.2\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\downloader\fragment.py", line 385, in thread_func
    return self.download_and_append_fragments(
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\downloader\fragment.py", line 510, in download_and_append_fragments
    for fragment in fragments:
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\downloader\fragment.py", line 407, in interrupt_trigger_iter
    for f in fg:
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\downloader\dash.py", line 71, in _get_fragments
    for i, fragment in enumerate(fragments):
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\extractor\youtube.py", line 2893, in _live_dash_fragments
    should_continue, last_seq = _extract_sequence_from_mpd(True, no_fragment_score > 15)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\extractor\youtube.py", line 2849, in _extract_sequence_from_mpd
    mpd_url, stream_number, is_live = (mpd_feed(format_id, 5 if expire_fast else 18000)
  File "<redacted>\python\3.9.2\lib\site-packages\yt_dlp\extractor\youtube.py", line 2811, in mpd_feed
    return f['manifest_url'], f['manifest_stream_number'], is_live
KeyError: 'manifest_url'
```

**Comment by nosoop** [comment]
Both `--retries 0` and `--fragment-retries 0` also redownload the webpage at the end of the premiere, so that doesn't do any good.

**Comment by mekicha** [comment]
I am facing this same issue when downloading a livestream, and would really appreciate any here here. Thank you!

**Comment by nosoop** [comment]
@mekicha If you're open to using other tools, https://github.com/Kethsar/ytarchive currently works great for both premieres and live streams.

**Comment by mekicha** [comment]
@nosoop oh great, thanks a lot. Let me check it out.
