### ISSUE TITLE
Some videos on ARD-mediathek are not downloading the media JSON

### ISSUE THREAD

**Issue by msrex** [yt-dlp/yt-dlp#8545]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

Some videos in https://www.ardmediathek.de/ are not working - while some others still do.
A working example: "https://www.ardmediathek.de/video/film-und-serie/schachnovelle-oder-literaturdrama/br-fernsehen/Y3JpZDovL2JyLmRlL3ZpZGVvLzVlMmZiZDZiLTE1MWQtNGFlNS1hYzgzLWE0NTY1ODNjNGUwOQ"
A non-working example: "https://www.ardmediathek.de/video/mittendrin-flughafen-frankfurt/ich-fliege-mit-nur-einem-bein-s12-e01/hr-fernsehen/ZmU4MmFjOTktZGZjZi00MTYwLTkwMzgtMWUyZGFlNWMyMTUw"
Both play equally well in the browser.

Below is the output of the non-working example. I am not sure whether I am doing anything wrong, but in the past I was able to download previous episodes of the non-working series just fine. I also verified that it is not a question of "Series" vs. "Movies", as episodes of other series work fine. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-5.14.21-150500.55.31-default-x86_64-with-glibc2.31 (OpenSSL 1.1.1l-fips  24 Aug 2021 SUSE release 150500.17.19.1, glibc 2.31)
[debug] exe versions: ffmpeg 4.4.4 (fdk,setts), ffprobe 4.4.4
[debug] Optional libraries: sqlite3-3.39.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 82fd9845b09ae38c762c77b9f542af9b96cd6a11a326a5da463aff757a3ce142
yt-dlp is up to date (stable@2023.10.13)


[~/tmp]> yt-dlp -v -F "https://www.ardmediathek.de/video/mittendrin-flughafen-frankfurt/ich-fliege-mit-nur-einem-bein-s12-e01/hr-fernsehen/ZmU4MmFjOTktZGZjZi00MTYwLTkwMzgtMWUyZGFlNWMyMTUw"
[debug] Command-line config: ['-v', '-F', 'https://www.ardmediathek.de/video/mittendrin-flughafen-frankfurt/ich-fliege-mit-nur-einem-bein-s12-e01/hr-fernsehen/ZmU4MmFjOTktZGZjZi00MTYwLTkwMzgtMWUyZGFlNWMyMTUw']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-5.14.21-150500.55.31-default-x86_64-with-glibc2.31 (OpenSSL 1.1.1l-fips  24 Aug 2021 SUSE release 150500.17.19.1, glibc 2.31)
[debug] exe versions: ffmpeg 4.4.4 (fdk,setts), ffprobe 4.4.4
[debug] Optional libraries: sqlite3-3.39.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Using fake IP 53.6.163.138 (DE) as X-Forwarded-For
[ARD:mediathek] Extracting URL: https://www.ardmediathek.de/video/mittendrin-flughafen-frankfurt/ich-fliege-mit-nur-einem-bein-s12-e01/hr-fernsehen/ZmU4MmFjOTktZGZjZi00MTYwLTkwMzgtMWUyZGFlNWMyMTUw
[ARD:mediathek] ZmU4MmFjOTktZGZjZi00MTYwLTkwMzgtMWUyZGFlNWMyMTUw: Downloading webpage
[ARD:mediathek] 12866537: Downloading media JSON
ERROR: [ARD:mediathek] Unable to download JSON metadata: HTTP Error 410: Gone (caused by <HTTPError 410: Gone>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/ard.py", line 275, in _real_extract
    info = self._extract_media_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/ard.py", line 28, in _extract_media_info
    media_info = self._download_json(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1033, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 410, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4051, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 415, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 410: Gone

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4070, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 410: Gone
```

**Comment by dirkf** [comment]
#7666
