### ISSUE TITLE
NPO / zapp.nl - Failed to parse JSON

### ISSUE THREAD

**Issue by 6461** [yt-dlp/yt-dlp#8547]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

The Netherlands

### Provide a description that is worded well enough to be understood

Downloading a program does not work. I'm using Proton VPN (free) and can access programs with Chrome browser.

Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)"))

Test URL: https://www.zapp.nl/programmas/checkpoint/gemist/VPWON_1268616

I have tried the release version 2023.10.13 and nightly@2023.11.07.231015 [10025b715]. Same issue with both of them.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.zapp.nl/programmas/checkpoint/gemist/VPWON_1268616']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.11.07.231015 [10025b715] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.11.07.231015, Current version: nightly@2023.11.07.231015
Current Build Hash: 4df736bdf04f79de60c985a9e9f007299caac14cf6656d6f058643ac6a16a321
yt-dlp is up to date (nightly@2023.11.07.231015)
[npo] Extracting URL: https://www.zapp.nl/programmas/checkpoint/gemist/VPWON_1268616
[npo] VPWON_1268616: Downloading token
[npo] VPWON_1268616: Downloading player JSON
ERROR: [npo] VPWON_1268616: VPWON_1268616: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\npo.py", line 222, in _real_extract
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 1039, in download_handle
  File "yt_dlp\extractor\common.py", line 1029, in parse
  File "yt_dlp\extractor\common.py", line 1016, in _parse_json
  File "yt_dlp\extractor\common.py", line 999, in __print_error

  File "yt_dlp\utils\_utils.py", line 555, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1013, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 563, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by bashonly** [comment]
Looks like the site's API has changed; the token endpoint URL now redirects to `npostart.nl/start` and the player API request gets redirected to the requested content's webpage

**Comment by benbenik** [comment]
Ik can confirm that this issue is still present for npo.nl, e.g. for link: https://npo.nl/start/serie/bij-van-duin-op-de-achterbank/seizoen-1/herman-finkers_19/afspelen

**Comment by mesa57** [comment]
Same here with other npostart links.

**Comment by Samuel98** [comment]
Has this been fixed yet?

**Comment by Ternoc** [comment]
The problem still exist

```shell
[debug] Command-line config: ['-vU', '--geo-bypass-country', 'NL', 'https://npo.nl/npo3/anne/21-04-2020/BV_101397802/POMS_BV_16095179']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.03.27 from yt-dlp/yt-dlp [48be862b3] (pip)
[debug] Python 3.12.10 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.16 11 Feb 2025)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.49.1, urllib3-2.2.1, websockets-12.0 (unsupported)
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Plugin directories: none
[debug] Loaded 1849 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2025.03.27 from yt-dlp/yt-dlp
Latest version: stable@2025.05.22 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[debug] Using fake IP 145.96.151.197 (NL) as X-Forwarded-For
[npo] Extracting URL: https://npo.nl/npo3/anne/21-04-2020/BV_101397802/POMS_BV_16095179
[npo] POMS_BV_16095179: Downloading token
[npo] POMS_BV_16095179: Downloading player JSON
ERROR: [npo] POMS_BV_16095179: POMS_BV_16095179: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\ternoc\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\common.py", line 748, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ternoc\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\npo.py", line 222, in _real_extract
    player = self._download_json(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ternoc\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\common.py", line 1145, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ternoc\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\common.py", line 1110, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ternoc\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\common.py", line 1098, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ternoc\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\common.py", line 1085, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "C:\Users\ternoc\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\common.py", line 1068, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "C:\Users\ternoc\AppData\Roaming\Python\Python312\site-packages\yt_dlp\utils\_utils.py", line 567, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ternoc\AppData\Roaming\Python\Python312\site-packages\yt_dlp\extractor\common.py", line 1082, in _parse_json
    return json.loads(
           ^^^^^^^^^^^
  File "C:\Python312\Lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ternoc\AppData\Roaming\Python\Python312\site-packages\yt_dlp\utils\_utils.py", line 575, in decode
    raise type(e)(f'{e.msg} in {s[e.pos - 10:e.pos + 10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by seszele64** [comment]
i second that, sadly it doesnt work ;(

im getting error:

```shell
[debug] Command-line config: ['-vU', 'https://npo.nl/start/serie/de-nachtzoen/seizoen-16/bas-ragas/']
[debug] User config "/home/tr1x/.config/yt-dlp/config": ['-P', '/home/tr1x/Content/Downloads/', '--write-info-json']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.05.22 from yt-dlp/yt-dlp [7977b329e]
[debug] Python 3.13.3 (CPython x86_64 64bit) - Linux-6.12.30-1-lts-x86_64-with-glibc2.41 (OpenSSL 3.5.0 8 Apr 2025, glibc 2.41)
[debug] exe versions: ffmpeg 7.1.1 (setts), ffprobe 7.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.23.0, brotlicffi-1.1.0.0, certifi-2025.04.26, requests-2.32.3, sqlite3-3.49.2, urllib3-2.4.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Plugin directories: none
[debug] Loaded 1859 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.05.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.05.22 from yt-dlp/yt-dlp)
[npo] Extracting URL: https://npo.nl/start/serie/de-nachtzoen/seizoen-16/bas-ragas/
[npo] bas-ragas: Downloading token
[npo] bas-ragas: Downloading player JSON
ERROR: [npo] bas-ragas: bas-ragas: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 748, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.13/site-packages/yt_dlp/extractor/npo.py", line 222, in _real_extract
    player = self._download_json(
        f'https://www.npostart.nl/player/{video_id}', video_id,
    ...<7 lines>...
                self._get_cookies('https://www.npostart.nl')['XSRF-TOKEN'].value)),
        })
  File "/usr/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1145, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1110, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
           ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1098, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1085, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1068, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/lib/python3.13/site-packages/yt_dlp/utils/_utils.py", line 567, in decode
    return super().decode(s)
           ~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1082, in _parse_json
    return json.loads(
           ~~~~~~~~~~^
        json_string, cls=LenientJSONDecoder, strict=False, transform_source=transform_source, **parser_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/site-packages/yt_dlp/utils/_utils.py", line 575, in decode
    raise type(e)(f'{e.msg} in {s[e.pos - 10:e.pos + 10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by TheThomanski** [comment]
I third that

**Comment by H0chim** [comment]
It still doesn't work :(

**Comment by Plevuus** [comment]
I think this issue is not solved yet. I got:

```
yt-dlp -vU https://npo.nl/start/afspelen/japan-een-verhaal-zonder-einde
[debug] Command-line config: ['-vU', 'https://npo.nl/start/afspelen/japan-een-verhaal-zonder-einde']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2026.01.29 from yt-dlp/yt-dlp [8b275536d] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.14.0-37-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, requests-2.31.0 (unsupported), sqlite3-3.45.1, urllib3-2.0.7, websockets-10.4 (unsupported), yt_dlp_ejs-0.4.0
[debug] JS runtimes: none
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Plugin directories: none
[debug] Loaded 1856 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2026.01.29 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2026.01.29 from yt-dlp/yt-dlp)
[npo] Extracting URL: https://npo.nl/start/afspelen/japan-een-verhaal-zonder-einde
[npo] japan-een-verhaal-zonder-einde: Downloading token
[npo] japan-een-verhaal-zonder-einde: Downloading player JSON
ERROR: [npo] japan-een-verhaal-zonder-einde: japan-een-verhaal-zonder-einde: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 763, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/npo.py", line 222, in _real_extract
    player = self._download_json(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1151, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1116, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1104, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1091, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1074, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/bin/yt-dlp/yt_dlp/utils/_utils.py", line 568, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1088, in _parse_json
    return json.loads(
           ^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/utils/_utils.py", line 576, in decode
    raise type(e)(f'{e.msg} in {s[e.pos - 10:e.pos + 10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

```

**Comment by katanakiwi** [comment]
Still present in 2026.03.17

```
yt-dlp.exe -vU https://npo.nl/start/afspelen/dit-was-het-nieuws_127
[debug] Command-line config: ['-vU', 'https://npo.nl/start/afspelen/dit-was-het-nieuws_127']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2026.03.17 from yt-dlp/yt-dlp [04d6974f5] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26200-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2025-04-17-git-7684243fbe-full_build-www.gyan.dev (setts), ffprobe 2025-04-17-git-7684243fbe-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.2.0, certifi-2026.02.25, curl_cffi-0.14.0, mutagen-1.47.0, requests-2.32.5, sqlite3-3.40.1, urllib3-2.6.3, websockets-16.0, yt_dlp_ejs-0.8.0
[debug] JS runtimes: none
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2026.03.17 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2026.03.17 from yt-dlp/yt-dlp)
[npo] Extracting URL: https://npo.nl/start/afspelen/dit-was-het-nieuws_127
[npo] dit-was-het-nieuws_127: Downloading token
[npo] dit-was-het-nieuws_127: Downloading player JSON
ERROR: [npo] dit-was-het-nieuws_127: dit-was-het-nieuws_127: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 765, in extract
  File "yt_dlp\extractor\npo.py", line 222, in _real_extract
  File "yt_dlp\extractor\common.py", line 1153, in download_content
  File "yt_dlp\extractor\common.py", line 1118, in download_handle
  File "yt_dlp\extractor\common.py", line 1106, in parse
  File "yt_dlp\extractor\common.py", line 1093, in _parse_json
  File "yt_dlp\extractor\common.py", line 1076, in __print_error

  File "yt_dlp\utils\_utils.py", line 571, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1090, in _parse_json
  File "json\__init__.py", line 359, in loads
  File "yt_dlp\utils\_utils.py", line 579, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by pebbe** [comment]
Still present

Latest version: stable@2026.07.04 from yt-dlp/yt-dlp

**Comment by olvll** [comment]
Same in master@2026.08.04.225908:

```
xxxx@pc-xxxx:~/Downloads/Poorten van Europa$ yt-dlp -vU https://npo.nl/start/afspelen/poorten-van-europa
[debug] Command-line config: ['-vU', 'https://npo.nl/start/afspelen/poorten-van-europa']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2026.08.04.225908 from yt-dlp/yt-dlp-master-builds [5d6b8c8cd] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-1060-nvidia-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: none
[debug] Optional libraries: certifi-2023.11.17, requests-2.31.0 (unsupported), sqlite3-3.45.1, urllib3-2.0.7, yt_dlp_ejs-0.8.0
[debug] JS runtimes: none
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Plugin directories: none
[debug] Loaded 1744 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2026.08.04.225908 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2026.08.04.225908 from yt-dlp/yt-dlp-master-builds)
[npo] Extracting URL: https://npo.nl/start/afspelen/poorten-van-europa
[npo] poorten-van-europa: Downloading token
[npo] poorten-van-europa: Downloading player JSON
ERROR: [npo] poorten-van-europa: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/xxxx/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 765, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxx/.local/bin/yt-dlp/yt_dlp/extractor/npo.py", line 222, in _real_extract
    player = self._download_json(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxx/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1148, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxx/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1113, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxx/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1101, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxx/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1088, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/home/xxxx/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1071, in __print_error
    raise ExtractorError(f'{errnote}', cause=err, video_id=video_id)

  File "/home/xxxx/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 572, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxxx/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1085, in _parse_json
    return json.loads(
           ^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/xxxx/.local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 580, in decode
    raise type(e)(f'{e.msg} in {s[e.pos - 10:e.pos + 10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```
