### ISSUE TITLE
no way to write to extension-less thumbnails

### ISSUE THREAD

**Issue by Joedang** [yt-dlp/yt-dlp#8548]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As the title says, there doesn't seem to be a way to write thumbnails to a file without an extension (or with the "wrong" extension). Ultimately, I care about this because I want to write a thumbnail to `/dev/stdout` and do nothing else. 

using the syntax I would expect:

```
⎛/tmp                                                                                                                                                                     
⎝$ yt-dlp -vU --write-thumbnail -f none --ignore-no-formats-error -o /dev/stdout https://www.youtube.com/watch\?v\=XwoFTcpI2ME                                            
[debug] Command-line config: ['-vU', '--write-thumbnail', '-f', 'none', '--ignore-no-formats-error', '-o', '/dev/stdout', 'https://www.youtube.com/watch?v=XwoFTcpI2ME']  
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8                                             
[debug] yt-dlp version stable@2023.10.13 [b634ba742]                                                                                    
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.1.60-1-lts-x86_64-with-glibc2.38 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.38)         
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4                                                                     
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.1.0.0, certifi-2023.07.22, sqlite3-3.43.2                                   
[debug] Proxy map: {}                                                                                                                   
[debug] Loaded 1890 extractors                                                                                                          
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest                                               
Available version: stable@2023.10.13, Current version: stable@2023.10.13                                                                
yt-dlp is up to date (stable@2023.10.13)                                                                                                                                  
[youtube] Extracting URL: https://www.youtube.com/watch?v=XwoFTcpI2ME                                                                   
[youtube] XwoFTcpI2ME: Downloading webpage                                                                       
[youtube] XwoFTcpI2ME: Downloading ios player API JSON                                                           
[youtube] XwoFTcpI2ME: Downloading android player API JSON                                                       
[youtube] XwoFTcpI2ME: Downloading m3u8 information                                                              
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto                                                                                                              
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id                                                           
WARNING: Requested format is not available                                                                       
[info] Downloading video thumbnail 41 ...                                                                        
[info] Writing video thumbnail 41 to: /dev/stdout.webp                                                           
ERROR: [Errno 13] Permission denied: '/dev/stdout.webp'                                                          
Traceback (most recent call last):                                                                               
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper                                                                                                                                              
    return func(self, *args, **kwargs)                                                                           
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                           
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info                                                                                                                                       
    return self.process_ie_result(ie_result, download, extra_info)                                               
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                               
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result                                                                                                                                    
    ie_result = self.process_video_result(ie_result, download=download)                                                                                                                                                            
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                            
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2921, in process_video_result                                                                                                                                 
    self.process_info(new_info)                         
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3180, in process_info                                                                                                                                         
    thumb_files = self._write_thumbnails(                                                                        
                  ^^^^^^^^^^^^^^^^^^^^^^^                                                                        
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4260, in _write_thumbnails                                                                                                                                    
    with open(encodeFilename(thumb_filename), 'wb') as thumbf:                                                   
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                              
PermissionError: [Errno 13] Permission denied: '/dev/stdout.webp'                                                

exit 1                                                  
```

As you can see, it tries to outsmart the user by attempting to write to `/dev/stdout.webp` instead of `/dev/stdout`,  disobeying what's explicitly specified in the `-o` option. 

Inconsistently, `-o foo.png` results in a write to `foo.webp` instead of `foo.png.webp`,  `-o foo.webp` writes to `foo.webp` rather than `foo.webp.webp`, and `-o -` writes to `-.webp` rather than `/dev/stdout`. Of these four different behaviors, only the third one is briefly mentioned in the man page or README, simply stating : 

> The simplest usage of -o is not to set any template arguments when downloading a single file, like in yt-dlp -o funny_video.flv "https://some/video" (hard-coding file extension like this is not recommended and could break some post-processing).

The inconvenience/inconsistency of this behavior is arguably less important/serious than the fact that it's undocumented behavior. The documentation makes it sound like `-o foo` would write to `foo` and `-o foo.%(ext)s` would write to `foo.webp` (or whatever the extension may be). IMHO, this is how yt-dlp *should* behave. It *should* do exactly what the user specifies in `-o` without trying to second-guess us. 

This is similar to #3106, but not a duplicate. (I suspect @pukkandan 's diagnosis was a bit off there, since this output behavior seems to impact video outputs too.) 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by debiedowner** [comment]
This issue of yt-dlp disobeying custom file extensions bothers me for a different reason: some sites serve the image file with the wrong extension, e.g. Reddit video thumbnails are actually jpg files, but they have .png extension. So `--convert-thumbnails jpg` fails, and `--convert-thumbnails png` does nothing, see #6866

Embedding the thumbnail also fails, presumably due to the wrong extension. I tried to circumvent this problem by changing the file extension, to no avail due to this issue as yt-dlp overwrites it with what it thinks to be the correct extension.

The only workaround I found was to use `--exec before_dl:thumb.bat`, with the `thumb.bat` file:
```
ren thumbname.png thumbname.jpg
ffmpeg -i thumbname.jpg thumbname.png
```

so that the png file is actually a png file, so `--embed-thumbnail` works correctly.

What I actually wanted to do was to embed the downloaded jpg file without converting it to png, but I couldn't find a way to do it as [EmbedThumbnail] expects to use the file with the .png extension that was downloaded. I can add the thumbnail manually later using ffmpeg (`ffmpeg -i a.mp4 -i a.jpg -map 1 -map 0 -c copy -disposition:0 attached_pic b.mp4`), but then the effect of `--mtime` switch is lost, and if I want to keep the file modification date, I need to use another OS dependent command. e.g. using `(Get-Item -LiteralPath 'b.mp4').LastWriteTime = (Get-Item -LiteralPath 'a.mp4').LastWriteTime` in Powershell.

**Comment by dirkf** [comment]
In OP's case, is it possible to work around the problem by creating a named pipe with the expected name of the metadata file, using `--force-overwrites`?
```
mkfifo foo.wep
yt-dlp -f none --write-thumbnail --force-overwrites -o foo.webp ... & cat foo.webp 
```
The output of `cat` might be the desired `/dev/stdout`.

And if it works in Linux, perhaps something similar might work in recent Windows too?

>...Reddit video thumbnails are actually jpg files, but they have .png extension

Shouldn't the extractor be made to fix this, say by supplying `'ext': 'jpg'` in the thumbnail format?

**Comment by notevenaperson** [comment]
```
-o foo.webp ... & cat foo.webp
```

This works... Until the service starts providing a file with a different extension, you'll be trying to cat `foo.webp` while yt-dlp decided to only write `foo.png`. There problem is the rules, which OP has already described, are too fluid. Quote:

> Inconsistently, `-o foo.png` results in a write to `foo.webp` instead of `foo.png.webp`, `-o foo.webp` writes to `foo.webp` rather than `foo.webp.webp`, and `-o -` writes to `-.webp` rather than `/dev/stdout`.

**Comment by notevenaperson** [comment]
For me, it's frustrating that you can't *expect*, in any way, how yt-dlp will name the files that it creates. 

From the manual:
> yt-dlp -o funny_video.flv "https://some/video" (hard-coding file extension like this is not recommended and could break some post-processing).

Admitting in a manual to such a critical flaw should be embarrassing. **The program can't create files with the names the user tells it plainly to use**. Ask why this behavior is hardcoded in yt-dlp, rather than blame the user for "hard-coding" filenames.

**Comment by bashonly** [comment]
> Ask why this behavior is hardcoded in yt-dlp

It's explained in the manual: "could break some post-processing". ffmpeg determines what type of input to expect from the file extension. (It also determines what format to output based on the output extension, but that's not an issue afaik).

Thumbnail extension handling is special and differs from video extension handling, though, so this isn't really relevant to the OP.

> This works... Until the service starts providing a file with a different extension

You could print `%(thumbnails.-1.filepath)s` or use `%(thumbnails.-1.filepath)q` in an exec arg to get the actual filepath

**Comment by notevenaperson** [comment]
> You could print `%(thumbnails.-1.filepath)s` or use `%(thumbnails.-1.filepath)q` etc in an exec arg to get the actual filepath

This is a solution. Do note that by itself it doesn't work, you have to prepend `after_video` to the template, like this: 
```
--print 'after_video:%(thumbnails.-1.filepath)s'
```

Paths for other filetypes are different, (and not documented, I think) for example the file written by `--write-info-json` has its path recorded in `%(requested_downloads.:.infojson_filename)s` (even though it says filename). To find more "magic" metadata run `--print 'after_video:%()j'` once, then you have to search inside for "filepath" or "filename". This might become more straightforward if proposal #9064 succeeds.

**Comment by notevenaperson** [comment]
Also, for those interested, don't shoot yourself in the foot like I did by doing what will follow. Not described in this issue, there's more than **one** thing making yt-dlp's filenames unpredictable. 

I thought, if I repeat the output template for a file in the --print option, I'd be able to know where the file was created, right? `-o "%(title)s.%(ext)s" --print "%(title)s.%(ext)s"`. The text emitted by --print evaluates to the same as the filename I wanted to know. But _only_ most of the time! I discovered that filename sanitization made the two different. When writing a file some characters in the filename are replaced, such as `?` -> `？`, similar looking, but it results in the file being saved in a different file path than the one you get from --print.

I think it's worth summarizing the things making filenames unpredictable. This issue doesn't deal with filenames that may be affected by filename sanitization, but it's about, at the core, the inability to predict the names of the files created by yt-dlp.

* #4547 
- * (can't be disabled yet)
* #8548
- * You are here

**Comment by bashonly** [comment]
use `"%(title)S.%(ext)S"` if you want to sanitize the values, or `"%(title)#S.%(ext)#S"` if you want the restrict the values (as in `--restrict-filenames`)

this is documented [here](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template) under "7. More conversions"

**Comment by notevenaperson** [comment]
I've just shot myself in the foot again. I do not recommend using `after_video` if you're `--print`-ing information that is not the file path of the video, such as metadata (or thumbnails, subtitles, etc). If the downloading the video fails (through no fault of your own such as a private yt video), then "after video" doesn't have the chance to happen.

Nothing gets printed. So to be safe, if you're downloading an info.json for example, use `before_dl`, as in `--print "before_dl:%(infojson_filename)s"`. Especially if you've used --ignore-no-formats-error.

You should also able to use --print multiple times in the same command line to get different temporal "slices" that can be used by your script to make the right decision.

The list of all the "whens" is in the manual/README  (you should already know this)
 
> The "when" argument determines when the
> postprocessor is invoked. It can be one of
> "pre_process" (after video extraction),
> "after_filter" (after video passes filter),
> "video" (after --format; before
> --print/--output), "before_dl" (before each
> video download), "post_process" (after each
> video download; default), "after_move"
> (after moving video file to its final
> locations), "after_video" (after downloading
> and processing all formats of a video), or
> "playlist" (at end of playlist).

**Comment by Odd-Pianist3487** [comment]
I am a bit surprised this didn't get more attention.
@bashonly - if I am allowed to ping you - am I understand this right that there is no way with only yt-dlp to download a file directly that does not end with `.description`? Is there a way to write a file named `info.json` or that not either (https://github.com/yt-dlp/yt-dlp/issues/8713 is 2 years ago)?

**Comment by bashonly** [comment]
> there is no way with only yt-dlp to download a file directly that does not end with .description?
```
--print-to-file description "/path/to/%(title)s [%(ids)s].custom.description.extension"
```
> Is there a way to write a file named info.json or that not either
```
--print-to-file "%()j" "/path/to/%(title)s [%(id)s].custom.infojson.extension"
```
