### ISSUE TITLE
[Broken] TikTok user error hasMore

### ISSUE THREAD

**Issue by makew0rld** [yt-dlp/yt-dlp#859]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', '--cookies-from-browser', 'firefox', 'https://tiktok.com/@vonviddy']
[Cookies] Extracting cookies from firefox
[debug] extracting from: "/home/makeworld/.mozilla/firefox/tpl4gebi.default/cookies.sqlite"
[Cookies] Extracted 2592 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.13.13-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://tiktok.com/@vonviddy
[generic] @vonviddy: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@vonviddy
[debug] [tiktok:user] Extracting URL: https://www.tiktok.com/@vonviddy
[download] Downloading playlist: vonviddy
[tiktok:user] vonviddy: Downloading webpage
[tiktok:user] vonviddy: Downloading Page 0
ERROR: 'hasMore'
Traceback (most recent call last):
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1252, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1366, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __process_playlist
    entry = get_entry(i)
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1440, in get_entry
    return YoutubeDL.__handle_extraction_exceptions(
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1441, in <lambda>
    lambda self, i: ie_entries[i - 1],
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.9/site-packages/yt_dlp/utils.py", line 4022, in __getitem__
    self.__cache.extend(itertools.islice(self.__iterable, n))
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 199, in _entries
    if not data_json['hasMore']:
KeyError: 'hasMore'


```

## Description

I was expecting to get a playlist of videos from that user, instead of the error. I had loaded the same page in my browser just before running yt-dlp. 

Thanks for adding the TikTok user extractor, it's great to see even though it has the issue.

**Comment by Ashish0804** [comment]
site changed parameters required to get json
SMH

**Comment by mahanstreamer** [comment]
welcome to the world of tiktok scraping ;)
