### ISSUE TITLE
yt-dlp can't find ffmpeg although its installed (raspberry pi os bullseye)

### ISSUE THREAD

**Issue by hollysheep** [yt-dlp/yt-dlp#8592]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When i try to download a video i have this error

> WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged

But ffmpeg is installed

```
whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /usr/share/man/man1/ffmpeg.1.gz
```

```
ffmpeg --version
ffmpeg version 4.3.6-0+deb11u1+rpt5 Copyright (c) 2000-2023 the FFmpeg developers
```

I also tried --ffmpeg-location but there is the same error.

yt-dlp isn't installed its from here: https://github.com/yt-dlp/yt-dlp/releases/tag/2023.11.16. ffmpeg is installed using apt

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
show verbose log please

**Comment by hollysheep** [comment]
```
~/.bin/yt-dlp https://www.youtube.com/watch?v=zP9vwgrG7BY --verbose
[debug] Command-line config: ['https://www.youtube.com/watch?v=zP9vwgrG7BY', '--verbose']
[debug] User config "/home/pi/.config/yt-dlp/config": ['-o', '/media/usb/youtube-dl/%(upload_date)s--%(title)s.%(ext)s', '-f', 'bestvideo[height<=720][vcodec!*=av01]+bestaudio[ext=m4a]/best', '--merge-output-format', 'mkv', '--restrict-filenames', '--prefer-free-formats', 'verbose:', 'True']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Python 3.9.2 (CPython armv7l 32bit) - Linux-6.1.21-v7+-armv7l-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: none
[debug] Optional libraries: certifi-2020.06.20, requests-2.25.1, sqlite3-3.34.1, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1901 extractors
[generic] Extracting URL: verbose:
[generic] verbose:: Downloading webpage
ERROR: Unable to handle request: Unsupported url scheme: "verbose" (urllib)
Traceback (most recent call last):
  File "/home/pi/.bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
  File "/home/pi/.bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/pi/.bin/yt-dlp/yt_dlp/extractor/generic.py", line 2439, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
  File "/home/pi/.bin/yt-dlp/yt_dlp/extractor/common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/pi/.bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4052, in urlopen
    return self._request_director.send(req)
  File "/home/pi/.bin/yt-dlp/yt_dlp/networking/common.py", line 127, in send
    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: "verbose" (urllib)

[generic] Extracting URL: True
ERROR: [generic] 'True' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:True" ) to search YouTube
  File "/home/pi/.bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/pi/.bin/yt-dlp/yt_dlp/extractor/generic.py", line 2412, in _real_extract
    raise ExtractorError(

[youtube] Extracting URL: https://www.youtube.com/watch?v=zP9vwgrG7BY
[youtube] zP9vwgrG7BY: Downloading webpage
[youtube] zP9vwgrG7BY: Downloading ios player API JSON
[youtube] zP9vwgrG7BY: Downloading android player API JSON
[youtube] zP9vwgrG7BY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] zP9vwgrG7BY: Downloading 1 format(s): 243+140
WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged
[debug] Invoking http downloader on "https://rr3---sn-4g5edndz.googlevideo.com/videoplayback?expire=1700193116&ei=-45WZarRPKrM6dsP1OCe4Ag&ip=2003%3Acf%3A774e%3Ac600%3A11fe%3A837d%3Ad81b%3A4008&id=o-AK2Uuvdd-m7zKa4TJ-6haeAv-zatGgVgt1lTm4haR_2U&itag=243&source=youtube&requiressl=yes&mh=YX&mm=31%2C29&mn=sn-4g5edndz%2Csn-4g5e6nss&ms=au%2Crdu&mv=m&mvi=3&pl=46&initcwndbps=1772500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=463607&dur=37.662&lmt=1682695933412604&mt=1700171099&fvip=1&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=631A224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ANLwegAwRQIgbiPCdlGMGcvUDs9mtO_Hmu4JbO3kcYIEQAcWO_eBr58CIQDcDS_3ijlHbwJ_dmix6mK_pr9bFpooOY56vfqR4xyTIQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AM8Gb2swRAIgVTlyH_YCszP-K5KN7vwtPwBZXKMo_HAcTP3lY01cFaoCICjh3W9DvDqoT7wwQRwT1t4gLNeWx9kNl0ZNnaxT2shm"
[download] /media/usb/youtube-dl/20230428--So_werden_deine_Videos_ganz_einfach_zu_Shorts.f243.webm has already been downloaded
[download] 100% of  452.74KiB
[debug] Invoking http downloader on "https://rr3---sn-4g5edndz.googlevideo.com/videoplayback?expire=1700193116&ei=-45WZarRPKrM6dsP1OCe4Ag&ip=2003%3Acf%3A774e%3Ac600%3A11fe%3A837d%3Ad81b%3A4008&id=o-AK2Uuvdd-m7zKa4TJ-6haeAv-zatGgVgt1lTm4haR_2U&itag=140&source=youtube&requiressl=yes&mh=YX&mm=31%2C29&mn=sn-4g5edndz%2Csn-4g5e6nss&ms=au%2Crdu&mv=m&mvi=3&pl=46&initcwndbps=1772500&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=611497&dur=37.732&lmt=1682695923645656&mt=1700171099&fvip=1&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=6318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ANLwegAwRQIgVXmqEuDrJSqBQ_mRd0QLSAMDp6U2E_rzu6EUSuwtRVUCIQDoL9fS2ryV_gAMkn-quX6-5POfvSRvxB1BZt4IleTTtw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AM8Gb2swRAIgVTlyH_YCszP-K5KN7vwtPwBZXKMo_HAcTP3lY01cFaoCICjh3W9DvDqoT7wwQRwT1t4gLNeWx9kNl0ZNnaxT2shm"
[download] /media/usb/youtube-dl/20230428--So_werden_deine_Videos_ganz_einfach_zu_Shorts.f140.m4a has already been downloaded
[download] 100% of  597.17KiB

```

**Comment by bashonly** [comment]
> ```
> whereis ffmpeg
> ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /usr/share/man/man1/ffmpeg.1.gz
> ```

`whereis` doesn't necessarily check your `PATH`, it's not reliable

please show the output of the following commands:
```
which ffmpeg

echo $PATH

/usr/bin/ffmpeg -version
```

**Comment by hollysheep** [comment]
```
which ffmpeg
/usr/bin/ffmpeg
pi@raspberrypi:~ $ echo $PATH
/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
pi@raspberrypi:~ $ /usr/bin/ffmpeg -version
ffmpeg version 4.3.6-0+deb11u1+rpt5 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 10 (Raspbian 10.2.1-6+rpi1)
configuration: --prefix=/usr --extra-version=0+deb11u1+rpt5 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-mmal --enable-neon --enable-rpi --enable-v4l2-request --enable-libudev --enable-epoxy --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --libdir=/usr/lib/arm-linux-gnueabihf --cpu=arm1176jzf-s --arch=arm
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

**Comment by bashonly** [comment]
The only thing I can think of is that there may be a broken `ffmpeg` binary/symlink in the same directory as your `yt-dlp` binary

It looks like `~/.bin/yt-dlp` may be where the yt-dlp binary you are trying to use is located? Check that folder for an ffmpeg file:

```
ls ~/.bin/ffmpeg
~/.bin/ffmpeg -version
```
The first command will output a filepath if the potentially problematic ffmpeg file exists. The second command may produce error output if the ffmpeg file is indeed the problem

**Comment by hollysheep** [comment]
There is no link in ~/.bin.

I reinstalled raspberry pi os and now all works.

**Comment by datenreisender** [comment]
I also encountered that message while `ffmpeg` was in fact installed. 

My problem: Some libraries that ffmpeg uses could not be loaded correctly, so I had to reinstall those. 

Would be nice if `yt-dlp` shows different error messages if `ffmpeg` is not installed at all or if it is but could not be ran correctly. But for now I am happy this is solved. :-)
