### ISSUE TITLE
Cookies not working when using the API/in a python script

### ISSUE THREAD

**Issue by CanOfSocks** [yt-dlp/yt-dlp#8630]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, I'm trying to get video information from a membership stream using a Python script. I'm trying to use a cookie file, but it doesn't appear to be working.
My script is as follows:
```
from yt_dlp import YoutubeDL

options = {
    "cookiesfile": 'cookies.txt',
    "verbose": True
}
with YoutubeDL(options) as ydl: 
  info_dict = ydl.extract_info('https://youtu.be/DRbr7J_i5fE', download=False)
  video_url = info_dict.get("url", None)
  video_id = info_dict.get("id", None)
  video_title = info_dict.get('title', None)
  description = info_dict.get('description', None)
  print("Title: " + video_title) 
  print("Description: " + description)
```
Which outputs:
```
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip) API 
[debug] params: {'cookiesfile': 'cookies.txt', 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.10.6 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1n  15 Mar 2022) 
[debug] exe versions: ffmpeg N-110228-g4dffa564d1-20230411 (setts), ffprobe N-110228-g4dffa564d1-20230411 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.1.0, websockets-10.4 
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors 
[youtube] Extracting URL: https://youtu.be/DRbr7J_i5fE 
[youtube] DRbr7J_i5fE: Downloading webpage
[youtube] DRbr7J_i5fE: Downloading ios player API JSON 
[youtube] DRbr7J_i5fE: Downloading android player API JSON 
ERROR: [youtube] DRbr7J_i5fE: This video is available to this channel's members on level: MemberShrimp! (or any higher level). Join this channel to get access to members-only content and other exclusive perks. 
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 715, in extract 
    ie_result = self._real_extract(url)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\youtube.py", line 4176, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 1193, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

Traceback (most recent call last):
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\youtube.py", line 4176, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 1193, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] DRbr7J_i5fE: This video is available to this channel's members on level: MemberShrimp! (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a:\Users\uncle\Documents\Scripts\Holo\yt-dlp.py", line 10, in <module>
    info_dict = ydl.extract_info('https://youtu.be/DRbr7J_i5fE', download=False)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1585, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1045, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 984, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] DRbr7J_i5fE: This video is available to this channel's members on level: MemberShrimp! (or any higher level). Join this channel to get access to members-only content and other exclusive perks.
```

If I run a similar command in yt-dlp using the command line, it works correctly
```
A:\Users\uncle\Documents\Scripts\Holo>yt-dlp -vU --cookies cookies.txt --skip-download https://www.youtube.com/watch?v=DRbr7J_i5fE
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', '--skip-download', 'https://www.youtube.com/watch?v=DRbr7J_i5fE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.10.6 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-110228-g4dffa564d1-20230411 (setts), ffprobe N-110228-g4dffa564d1-20230411
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.1.0, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=DRbr7J_i5fE
[youtube] DRbr7J_i5fE: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] DRbr7J_i5fE: Downloading ios player API JSON
[youtube] DRbr7J_i5fE: Downloading android player API JSON
[debug] Loading youtube-nsig.63e90c30 from cache
[debug] [youtube] Decrypted nsig ZjmXG0HYr5PVddgSL4 => 8tZVA-Iyz_P1kw
[youtube] DRbr7J_i5fE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] DRbr7J_i5fE: Downloading 1 format(s): 303+251
```

If I try my original python script with a non-membership video, it prints the information correctly:
```
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip) API 
[debug] params: {'cookiesfile': 'cookies.txt', 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.10.6 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-110228-g4dffa564d1-20230411 (setts), ffprobe N-110228-g4dffa564d1-20230411 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.1.0, websockets-10.4 
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors 
[youtube] Extracting URL: https://www.youtube.com/watch?v=qMQ4P-vI3JI 
[youtube] qMQ4P-vI3JI: Downloading webpage
[youtube] qMQ4P-vI3JI: Downloading ios player API JSON 
[youtube] qMQ4P-vI3JI: Downloading android player API JSON 
[youtube] qMQ4P-vI3JI: Downloading m3u8 information 
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto 
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id 
[debug] Default format spec: bestvideo*+bestaudio/best 
Title: Kyoufuu All Back (強風オールバック) / Gawr Gura Cover
Description: 🐟 twitter: https://twitter.com/gawrgura

illustration/mv: 9am
mix: ごず

Request from hololive Production to underage viewers:
Please be sure to check the link below before viewing our content.
https://en.hololive.tv/request-to-minors
```

I'm unsure exactly where I am going wrong with the use of the cookiefile in the python script. As shown, the cookie file is valid and works fine with the yt-dlp executable.

Any help would be great, thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip) API 
[debug] params: {'cookiesfile': 'cookies.txt', 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.10.6 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1n  15 Mar 2022) 
[debug] exe versions: ffmpeg N-110228-g4dffa564d1-20230411 (setts), ffprobe N-110228-g4dffa564d1-20230411 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.1.0, websockets-10.4 
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors 
[youtube] Extracting URL: https://youtu.be/DRbr7J_i5fE 
[youtube] DRbr7J_i5fE: Downloading webpage
[youtube] DRbr7J_i5fE: Downloading ios player API JSON 
[youtube] DRbr7J_i5fE: Downloading android player API JSON 
ERROR: [youtube] DRbr7J_i5fE: This video is available to this channel's members on level: MemberShrimp! (or any higher level). Join this channel to get access to members-only content and other exclusive perks. 
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 715, in extract 
    ie_result = self._real_extract(url)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\youtube.py", line 4176, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 1193, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

Traceback (most recent call last):
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\youtube.py", line 4176, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 1193, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] DRbr7J_i5fE: This video is available to this channel's members on level: MemberShrimp! (or any higher level). Join this channel to get access to members-only content and other exclusive perks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a:\Users\uncle\Documents\Scripts\Holo\yt-dlp.py", line 10, in <module>
    info_dict = ydl.extract_info('https://youtu.be/DRbr7J_i5fE', download=False)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1585, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1045, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 984, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] DRbr7J_i5fE: This video is available to this channel's members on level: MemberShrimp! (or any higher level). Join this channel to get access to members-only content and other exclusive perks.
```

**Comment by bashonly** [comment]
the param is `cookiefile` not `cookiesfile`

**Comment by CanOfSocks** [comment]
Thanks, I also had to include the absolute path, the relative was not enough
`
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip) API 
[debug] params: {'cookiefile': 'A:/Users/uncle/Documents/Scripts/Holo/cookies.txt', 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4556.0 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.10.6 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-110228-g4dffa564d1-20230411 (setts), ffprobe N-110228-g4dffa564d1-20230411 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.1.0, websockets-10.4 
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors 
[youtube] Extracting URL: https://www.youtube.com/watch?v=DRbr7J_i5fE 
[youtube] DRbr7J_i5fE: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie 
[youtube] DRbr7J_i5fE: Downloading ios player API JSON 
[youtube] DRbr7J_i5fE: Downloading android player API JSON 
[debug] Loading youtube-nsig.63e90c30 from cache 
[debug] [youtube] Decrypted nsig 6Hi1Pkr9ff9BkB3GHG => 8EFHabmkp4L-8g 
[youtube] DRbr7J_i5fE: Downloading m3u8 information 
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto 
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id 
[debug] Default format spec: bestvideo*+bestaudio/best 
Title: WATCHALONG: Star Wars: Episode IV – A New Hope (1977)
Description: HAHAHAHAH MAY THE 4TH BE WITH YOU HAHAHA
Star Wars: Episode IV – A New Hope (1977)

Film from Prime Video ! [2h 4m]

thumbnail: default shark
`
