### ISSUE TITLE
zingmp3.vn broken on certain URLs

### ISSUE THREAD

**Issue by randomnoob** [yt-dlp/yt-dlp#8633]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Vietnam

### Provide a description that is worded well enough to be understood

zingmp3.vn has added some kind of protection, only allow certain files to be downloaded from its official mobile app. Therefore, a number of files cannot be downloaded using yt-dlp
For example: https://zingmp3.vn/album/Mot-Buoc-Yeu-Van-Dam-Dau-Single-Mr-Siro/ZU9ZO7DU.html

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://zingmp3.vn/bai-hat/Mot-Buoc-Yeu-Van-Dam-Dau-Mr-Siro/ZWABWOFZ.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2023.11.20.225447 from yt-dlp/yt-dlp-master-builds [a0b19d319] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-6.2.0-36-generic-x86_64-with-glibc2.35 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1915 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2023.11.20.225447 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2023.11.20.225447 from yt-dlp/yt-dlp-master-builds)
[debug] Using fake IP 14.171.88.97 (VN) as X-Forwarded-For
[zingmp3] Updating cookies
[zingmp3] Extracting URL: https://zingmp3.vn/bai-hat/Mot-Buoc-Yeu-Van-Dam-Dau-Mr-Siro/ZWABWOFZ.html
[zingmp3] ZWABWOFZ: Downloading bai-hat JSON metadata
[zingmp3] ZWABWOFZ: Downloading song-streaming JSON metadata
[zingmp3] ZWABWOFZ: Downloading lyric JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ZWABWOFZ: Downloading 1 format(s): 128
[debug] Invoking http downloader on "https://a128-zmp3.zmdcdn.me/82a1fac388c6b1ca4393fe4bcf36ced6?authen=exp=1700724368~acl=/82a1fac388c6b1ca4393fe4bcf36ced6/*~hmac=c676cf98ba5896ffcb740bb2fe286a2c"
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 4055, in urlopen
  File "yt_dlp/networking/common.py", line 114, in send
  File "yt_dlp/networking/_helper.py", line 204, in wrapper
  File "yt_dlp/networking/common.py", line 325, in send
  File "yt_dlp/networking/_requests.py", line 341, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 3391, in process_info
  File "yt_dlp/YoutubeDL.py", line 3112, in dl
  File "yt_dlp/downloader/common.py", line 455, in download
  File "yt_dlp/downloader/http.py", line 364, in real_download
  File "yt_dlp/downloader/http.py", line 120, in establish_connection
  File "yt_dlp/YoutubeDL.py", line 4087, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

**Comment by seproDev** [comment]
I cannot replicate. For me, these tracks download fine.
Could this have just been a temporary issue?
