### ISSUE TITLE
TikTok downloading sensitive videos doesn't work

### ISSUE THREAD

**Issue by sbdchd** [yt-dlp/yt-dlp#8678]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Can't download videos marked sensitive from TikTok

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
❯ yt-dlp -vU -o "tiktok@%(uploader)s:%(id)s:%(title).100B.%(ext)s" https://www.tiktok.com/@jacob__knowles/video/7279901785777573166
[debug] Command-line config: ['-vU', '-o', 'tiktok@%(uploader)s:%(id)s:%(title).100B.%(ext)s', 'https://www.tiktok.com/@jacob__knowles/video/7279901785777573166']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.10.8 (CPython arm64 64bit) - macOS-14.0-arm64-arm-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.39.4, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[TikTok] Extracting URL: https://www.tiktok.com/@jacob__knowles/video/7279901785777573166
[TikTok] 7279901785777573166: Downloading video feed
WARNING: [TikTok] 7279901785777573166: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7279901785777573166: Downloading webpage
[debug] Extractor gave empty title. Creating a generic title
ERROR: [TikTok] 7279901785777573166: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/Users/steve/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/steve/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/steve/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/steve/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "/Users/steve/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [TikTok] 7279901785777573166: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
Related to (but not quite a duplicate of): #4992, #6483

Videos that are flagged as sensitive, have had their audio taken down, or are otherwise de-listed/shadowbanned are not available via the mobile API feed endpoint that yt-dlp's TT extractor uses.

Where these three issues differ is in the results of the webpage extraction that the extractor then falls back to:
 - with #6483 the webpage extraction succeeds
 - with #4992 the webpage request gives a 404 error
 - and with OP's video we seem to get a page that has a "sigi state" JSON object, but its video info object contains only dummy/empty/zero values.

**Comment by bashonly** [comment]
if you have a working app install id (`iid`) you can access the mobile API formats by passing:
```
--extractor-arg "tiktok:app_info=IID"
```
where `IID` is a placeholder for the actual install id

**Comment by joelachankeng** [comment]
@bashonly where can I find the IID?

**Comment by bashonly** [comment]
@joelachankeng https://github.com/yt-dlp/yt-dlp/issues/9506#issuecomment-2053987537

**Comment by ndyanx** [comment]
optional tiktok.py _extract_web_formats:
`response = self._download_json(f'https://www.tikwm.com/api/?url={webpage_url}&hd=1', 'tikwm')
        sizes = {
            'hdplay': 'hd_size',
            'play': 'size',
            'wmplay': 'wm_size',
        }
        duration = traverse_obj(response, ('data', 'duration'))
        for q, size_key in sizes.items():
            url = traverse_obj(response, ('data', q))
            if url and self._is_valid_url(url, 'tikwm'):
                size = traverse_obj(response, ('data', size_key)) or (traverse_obj(response, ('data', 'size')) + 15000)
                tbr = math.ceil((size * 8) / duration / 1000) if size and duration else None
                formats.append({
                    **COMMON_FORMAT_INFO,
                    'format_id': size_key,
                    'url': url,
                    'filesize': size,
                    'tbr': tbr,
                })`

**Comment by ndyanx** [comment]
optional tiktok.py _extract_web_formats:
```
response = self._download_json(f'https://www.tikwm.com/api/?url={webpage_url}&hd=1', 'tikwm')
sizes = {
    'hdplay': 'hd_size',
    'play': 'size',
    'wmplay': 'wm_size',
}
duration = traverse_obj(response, ('data', 'duration'))
for q, size_key in sizes.items():
    url = traverse_obj(response, ('data', q))
    if url and self._is_valid_url(url, 'tikwm'):
        size = traverse_obj(response, ('data', size_key)) or (traverse_obj(response, ('data', 'size')) + 15000)
        tbr = math.ceil((size * 8) / duration / 1000) if size and duration else None
        formats.append({
            **COMMON_FORMAT_INFO,
            'format_id': size_key,
            'url': url,
            'filesize': size,
            'tbr': tbr,
        })
```

**Comment by bashonly** [comment]
@ndyanx 3rd party downloader sites will not be supported in yt-dlp

**Comment by rudolphos** [comment]
This problem is still occuring in - yt-dlp is up to date (stable@2024.12.06 from yt-dlp/yt-dlp)

**Comment by Fuwiz** [comment]
Video not available, status code 10204
