### ISSUE TITLE
--ffmpeg-location not working on MacOS

### ISSUE THREAD

**Issue by VestigiaLunae** [yt-dlp/yt-dlp#8680]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I tried to extract only the audio from a twitter video. But, it asked me to provide a '--ffmpeg-location'. So, I searched Google and used 'which ffmpeg' to get '/opt/homebrew/bin/ffmpeg', which I used in the new command. But it still didn't work. I used the command below:
yt-dlp -o "/Users/misterms/Downloads/twitter/%(title)s.%(ext)s" -x --audio-format best --ffmpeg-location "/opt/homebrew/bin/ffmpeg" https://twitter.com/i/status/1725736445330194620 -vU

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-o', '/Users/misterms/Downloads/twitter/%(title)s.%(ext)s', '-x', '--audio-format', 'best', '--ffmpeg-location', '/opt/homebrew/bin/ffmpeg', 'https://twitter.com/i/status/1725736445330194620', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.12.0 (CPython arm64 64bit) - macOS-14.1.1-arm64-arm-64bit (OpenSSL 3.2.0 23 Nov 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[twitter] Extracting URL: https://twitter.com/i/status/1725736445330194620
[twitter] 1725736445330194620: Downloading guest token
[twitter] 1725736445330194620: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1725735820223803393
[twitter] 1725736445330194620: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, br, size, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[info] 1725735820223803393: Downloading 1 format(s): http-2176
[debug] Invoking http downloader on "https://video.twimg.com/amplify_video/1725735820223803393/vid/avc1/720x1280/J04vCKOZeS7X2Cwc.mp4?tag=14"
[download] Destination: /Users/misterms/Downloads/twitter/Marques Brownlee - This is one of those sports that cameras don’t do justice.mp4
[download] 100% of  868.91KiB in 00:00:00 at 1.80MiB/s
ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3465, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3645, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3627, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3605, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 493, in run
    filecodec = self.get_audio_codec(path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.11.16/libexec/lib/python3.12/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 241, in get_audio_codec
    raise PostProcessingError('ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location')
yt_dlp.utils.PostProcessingError: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
```

**Comment by VestigiaLunae** [comment]
I have updated all required components(yt-dlp, ffmpeg, python, etc) to the most recent versions possible, and have tried without "" on the ffmpeg location as well. Still nothing.

**Comment by dirkf** [comment]
Try `--ffmpeg-location /opt/homebrew/bin`.

**Comment by VestigiaLunae** [comment]
> Try `--ffmpeg-location /opt/homebrew/bin`.

Didn't work, both with and without quote marks.

**Comment by dirkf** [comment]
And `/opt/homebrew/bin/ffmpeg -version`?

**Comment by VestigiaLunae** [comment]
Like this?: `"/opt/homebrew/bin/ffmpeg -version"`
Not working, same error

**Comment by Grub4K** [comment]
No, you should try running `/opt/homebrew/bin/ffmpeg -version` in the shell so see if it works regularly

**Comment by VestigiaLunae** [comment]
Oh. That gave me this, guessing it means it's installed correctly?
```
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with Apple clang version 15.0.0 (clang-1500.0.40.1)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

**Comment by bashonly** [comment]
Try reinstalling ffmpeg with brew

**Comment by VestigiaLunae** [comment]
It worked after the reinstall, thank you!
