### ISSUE TITLE
Fix PBS SoCal Extractor

### ISSUE THREAD

**Issue by hitomi-nakayama** [yt-dlp/yt-dlp#8703]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

I am trying to download videos from PBS SoCal, but the PBS extractor doesn't recognize the URL. 

For the individual video links, it appears that the PBS extractor's URL parser only needs to be adjusted. 

I'm not sure how to fix the playlist issues, however.

Example URLs:

- single video: https://www.pbssocal.org/shows/visiting-huell-howser/episodes/canters
- single video: https://www.pbssocal.org/shows/californias-gold-with-huell-howser/episodes/fotoplayer
- example playlist: https://www.pbssocal.org/shows/visiting-huell-howser#episodes
- example playlist: https://www.pbssocal.org/shows/visiting-huell-howser?f0=00000176-0e33-db70-a576-5e7ff6670000#episodes

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-subs', '--sub-format', 'best', '--skip-download', 'https://www.pbssocal.org/shows/visiting-huell-howser/episodes/glass-museum']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 6a9c7a2b5
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.1.57-gentoo-x86_64-AMD_Ryzen_5_2500U_with_Radeon_Vega_Mobile_Gfx-with-glibc2.37 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.18.0, requests-2.31.0, sqlite3-3.43.2, urllib3-2.0.6
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.pbssocal.org/shows/visiting-huell-howser/episodes/glass-museum
[generic] glass-museum: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] glass-museum: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.pbssocal.org/shows/visiting-huell-howser/episodes/glass-museum
Traceback (most recent call last):
  File "/home/hitomi/code/yt-dlp/yt_dlp/YoutubeDL.py", line 1570, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hitomi/code/yt-dlp/yt_dlp/YoutubeDL.py", line 1705, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/hitomi/code/yt-dlp/yt_dlp/extractor/common.py", line 717, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hitomi/code/yt-dlp/yt_dlp/extractor/generic.py", line 2531, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.pbssocal.org/shows/visiting-huell-howser/episodes/glass-museum
```

**Comment by hitomi-nakayama** [comment]
I was able to hack the single-video downloading by adding `pbssocal` to this line:
https://github.com/hitomi-Nakayama/yt-dlp/blob/pbs-socal/yt_dlp/extractor/pbs.py#L192

Adding it to `_STATIONS` doesn't work because the URL is formatted differently. 
I'm not sure how I'm supposed to modify this in a non-hacky way.

Additionally, my hack does not fix the issues with downloading full seasons.

**Comment by pukkandan** [comment]
> I was able to hack the single-video downloading by adding `pbssocal` to this line: [hitomi-Nakayama/yt-dlp@`pbs-socal`/yt_dlp/extractor/pbs.py#L192](https://github.com/hitomi-Nakayama/yt-dlp/blob/pbs-socal/yt_dlp/extractor/pbs.py?rgh-link-date=2023-12-03T01%3A47%3A58Z#L192)
> 
> Adding it to `_STATIONS` doesn't work because the URL is formatted differently. I'm not sure how I'm supposed to modify this in a non-hacky way.

Your patch looks fine to merge. Please make a PR

**Comment by RohinMarok** [comment]
take
