### ISSUE TITLE
Support playlists on Rumble

### ISSUE THREAD

**Issue by jarimustonen** [yt-dlp/yt-dlp#8717]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Finland

### Example URLs

https://rumble.com/playlists/ORgRsSDQzLo

### Provide a description that is worded well enough to be understood

Rumble supports playlists but yt-dlp does not seem to be able to read them. I guess Rumble playlists are a new feature on the site.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://rumble.com/playlists/ORgRsSDQzLo']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.11.29.232714 from yt-dlp/yt-dlp-nightly-builds [6a9c7a2b5] (pip)
[debug] Python 3.11.6 (CPython arm64 64bit) - macOS-13.6.1-arm64-arm-64bit (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.11.29.232714 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.11.29.232714 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://rumble.com/playlists/ORgRsSDQzLo
[generic] ORgRsSDQzLo: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ORgRsSDQzLo: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://rumble.com/playlists/ORgRsSDQzLo
Traceback (most recent call last):
  File "/Users/jari/Sources/youtube-poller/.python-env/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1570, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jari/Sources/youtube-poller/.python-env/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1705, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/Users/jari/Sources/youtube-poller/.python-env/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 717, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jari/Sources/youtube-poller/.python-env/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2531, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://rumble.com/playlists/ORgRsSDQzLo
```

**Comment by atom-smasher** [comment]
Possibly related? Using pages that act as playlists,

A command like this: `yt-dlp https://rumble.com/c/TheJimmyDoreShow/videos`

Works with `master@2024.02.21.083926`.

Fails with `stable@2023.12.30`.

Used to work in stable, but about late Jan 2023 something seems to have changed on Rumble.

**Comment by bashonly** [comment]
@atom-smasher Not related AFAICT. Channel extraction was fixed in 0023af81fbce01984f35b34ecaf8562739831227, which has been merged in master but has not yet seen stable release
