### ISSUE TITLE
[Youtube] After getting 352211  bytes of data, it fails with: HTTP Error 404: Not Found 

### ISSUE THREAD

**Issue by krzysiobal** [yt-dlp/yt-dlp#8719]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Provide a description that is worded well enough to be understood

youtube: When forced to download video in mp4 format, it fails after grabbing 352211 bytes. Without forcing video format, it works fine. From abound 1000 videos from this youtube channel, it fails only on this and a few others.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--format=mp4', 'https://www.youtube.com/watch?v=zhKN30W1E0E']
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Python 3.7.3 (CPython armv7l 32bit) - Linux-5.10.17-v7l+-armv7l-with-debian-10.9 (OpenSSL 1.1.1d  10 Sep 2019, glibc 2.28)
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Crypto-broken 2.6.1, certifi-2018.08.24, pyxattr-0.6.1, requests-2.21.0, secretstorage-2.3.1, sqlite3-3.27.2, urllib3-1.24.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1902 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=zhKN30W1E0E
[youtube] zhKN30W1E0E: Downloading webpage
[youtube] zhKN30W1E0E: Downloading ios player API JSON
[youtube] zhKN30W1E0E: Downloading android player API JSON
[youtube] zhKN30W1E0E: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] zhKN30W1E0E: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr4---sn-u2oxu-f5fek.googlevideo.com/videoplayback?expire=1701868307&ei=sx5wZcGoBMKei9oPtI6MmA4&ip=83.9.221.154&id=o-ADToqYtKCEP5CHIXivfhaKjXcCHlSekAxF-CHSc8hJWW&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=sY&mm=31%2C26&mn=sn-u2oxu-f5fek%2Csn-2gb7sne6&ms=au%2Conr&mv=m&mvi=4&pl=24&initcwndbps=1772500&spc=UWF9f1OYTQ-Y4CeaROmMR7nuMLbWBNU&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=259.482&lmt=1700103717329619&mt=1701846318&fvip=4&fexp=24007246&c=ANDROID&txp=6318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=ANLwegAwRgIhAPwxmeEUWKRh7YrbQO-ANg3_wYT8I_zzv3flKGxLMjNbAiEAo9g9VA6YPBkP7zBDifrElTj-hKlmXwr7tPOPcVeUQHA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AM8Gb2swRgIhAIXBujyu47h6xrXQZhf0m9IVuxLV9ggSKVh_oQMR_rb6AiEAvNtWzN7nCgKVz0icTo6o0LgAgUknFgqiv2tWyCrB9Qs%3D"
[download] Resuming download at byte 352211
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 4052, in urlopen
    return self._request_director.send(req)
  File "./yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "./yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "./yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3388, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3109, in dl
    return fd.download(name, new_info, subtitle)
  File "./yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "./yt-dlp/yt_dlp/downloader/http.py", line 364, in real_download
    establish_connection()
  File "./yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 4074, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
Possibly same as https://github.com/yt-dlp/yt-dlp/issues/3372. What happens if you delete the part file and retry?

**Comment by krzysiobal** [comment]
After deleting .part file and retrying, same thing happen.

**Comment by pukkandan** [comment]
log?
