### ISSUE TITLE
promodj.com

### ISSUE THREAD

**Issue by WapStyle** [yt-dlp/yt-dlp#8721]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://promodj.com/djamice/remixes

### Provide a description that is worded well enough to be understood

yt_dlp.utils.UnsupportedError: Unsupported URL: https://promodj.com/safiter/remixes
yt_dlp.utils.UnsupportedError: Unsupported URL: https://promodj.com/safiter/remixes

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp_linux_armv7l -vU -f 'bestaudio/best' -ciw -v --extract-audio --audio-quality 0 --audio-format mp3 -x https://promodj.com/safiter/remixes
[debug] Command-line config: ['-vU', '-f', 'bestaudio/best', '-ciw', '-v', '--extract-audio', '--audio-quality', '0', '--audio-format', 'mp3', '-x', 'https://promodj.com/safiter/remixes']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp (linux_armv7l_exe)
[debug] Python 3.8.0 (CPython armv7l 32bit) - Linux-5.10.103-v7l+-armv7l-with-glibc2.7 (OpenSSL 1.1.1  11 Sep 2018, glibc 2.28)
[debug] exe versions: ffmpeg 4.1.9 (fdk), ffprobe 4.3.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.22.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://promodj.com/safiter/remixes
[generic] remixes: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] remixes: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://promodj.com/safiter/remixes
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp/extractor/common.py", line 715, in extract
  File "yt_dlp/extractor/generic.py", line 2578, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://promodj.com/safiter/remixes
```

**Comment by dirkf** [comment]
The example URL is a playlist, where the generic extractor fails. Its "twitter card" tactic succeeds with one of the playlist links, like https://promodj.com/djamice/remixes/7532524/Moya_Mishel_Zima_v_serdce_Amice_Remix.

The playlist links can be gathered from the `href` attribute of elements like `<a amba="file:nnnnnn" ...>`. For the next page of results, follow the 
link in the `<a id="next_page" ...>` element, missing in the last results page.

Each entry on the playlist page also contains its mp3 link, but almost all the metadata requires the entry's page to be loaded.
