### ISSUE TITLE
File saving bug in Twitter video (might be a Core bug)

### ISSUE THREAD

**Issue by SubZero5** [yt-dlp/yt-dlp#8723]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Turkey

### Provide a description that is worded well enough to be understood

while trying to download a Twitter link, yt-dlp give me an error number 22 as seen below:

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://twitter.com/apara_tv/status/1732470417359622562', '-Uv']
[debug] Encodings: locale cp1254, fs utf-8, pref cp1254, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[twitter] Extracting URL: https://twitter.com/apara_tv/status/1732470417359622562
[twitter] 1732470417359622562: Downloading guest token
[twitter] 1732470417359622562: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1732468716309196800
[twitter] 1732470417359622562: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, br, size, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1732468716309196800: Downloading 1 format(s): http-2176
[debug] Invoking http downloader on "https://video.twimg.com/amplify_video/1732468716309196800/vid/avc1/1280x720/D_tRrvKG4jtI0ZQs.mp4?tag=16"
[download] Unable to open file: [Errno 22] Invalid argument: "A Para - Aselsan Teknik Analiz 🎙  ➡Se lçuk Gönençler： 48.70'lerin üzerinde 2. kapanışı verirse 56.64 hareketi tetiklenir. 48.70 geçilene kadar temkinli olunmalı.  @ugurrkorkmaz @xtraderx_ #SelçukGönençler #borsa #hisse #bıst100 #ParaTeknik #ASELS [1732468716309196800].mp4.part". Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: "A Para - Aselsan Teknik Analiz 🎙  ➡Se lçuk Gönençler： 48.70'lerin üzerinde 2. kapanışı verirse 56.64 hareketi tetiklenir. 48.70 geçilene kadar temkinli olunmalı.  @ugurrkorkmaz @xtraderx_ #SelçukGönençler #borsa #hisse #bıst100 #ParaTeknik #ASELS [1732468716309196800].mp4.part". Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: "A Para - Aselsan Teknik Analiz 🎙  ➡Se lçuk Gönençler： 48.70'lerin üzerinde 2. kapanışı verirse 56.64 hareketi tetiklenir. 48.70 geçilene kadar temkinli olunmalı.  @ugurrkorkmaz @xtraderx_ #SelçukGönençler #borsa #hisse #bıst100 #ParaTeknik #ASELS [1732468716309196800].mp4.part". Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: "A Para - Aselsan Teknik Analiz 🎙  ➡Selçu k Gönençler： 48.70'lerin üzerinde 2. kapanışı verirse 56.64 hareketi tetiklenir. 48.70 geçilene kadar temkinli olunmalı.  @ugurrkorkmaz @xtraderx_ #SelçukGönençler #borsa #hisse #bıst100 #ParaTeknik #ASELS [1732468716309196800].mp4.part"
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 593, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 260, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5122, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 596, in sanitize_open
OSError: [Errno 22] Invalid argument: "A Para - Aselsan Teknik Analiz 🎙  ➡Selçuk Gönençler： 48.70'l erin üzerinde 2. kapanışı verirse 56.64 hareketi tetiklenir. 48.70 geçilene kadar temkinli olunmalı.  @ugurrkorkmaz @xtraderx_ #SelçukGönençler #borsa #hisse #bıst100 #ParaTeknik #ASELS [1732468716309196800].mp4.part"
```

**Comment by bashonly** [comment]
filename is too long

add `-o "%(title).100B [%(id)s].%(ext)s"` to your command

**Comment by SubZero5** [comment]
Shouldn't the yt-dlp give a shorter file name automatically?

**Comment by bashonly** [comment]
see #1136
