### ISSUE TITLE
[Site support request] PeerTube instance videos.lukesmith.xyz

### ISSUE THREAD

**Issue by moyox65** [yt-dlp/yt-dlp#8757]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Europe

### Example URLs

https://videos.lukesmith.xyz/

### Provide a description that is worded well enough to be understood

Hi,

When I try to download the latest videos from https://videos.lukesmith.xyz/, `yt-dlp` doesn't recognize it as a PeerTube instance:

```
>yt-dlp -vU --playlist-end 6 https://videos.lukesmith.xyz/
[debug] Command-line config: ['-vU', '--playlist-end', '6', 'https://videos.lukesmith.xyz/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-02-10-git-b6bb6b9f22-full_build-www.gyan.dev (setts), ffprobe 2022-02-10-git-b6bb6b9f22-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://videos.lukesmith.xyz/
[generic] videos.lukesmith: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] videos.lukesmith: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://videos.lukesmith.xyz/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2578, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://videos.lukesmith.xyz/
```

However, if I try to download a specific video, then it works:
```
>yt-dlp -vU https://videos.lukesmith.xyz/w/cH3qvjkd4mZEJaRhdPQRtj
[debug] Command-line config: ['-vU', 'https://videos.lukesmith.xyz/w/cH3qvjkd4mZEJaRhdPQRtj']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-02-10-git-b6bb6b9f22-full_build-www.gyan.dev (setts), ffprobe 2022-02-10-git-b6bb6b9f22-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://videos.lukesmith.xyz/w/cH3qvjkd4mZEJaRhdPQRtj
[generic] cH3qvjkd4mZEJaRhdPQRtj: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] cH3qvjkd4mZEJaRhdPQRtj: Extracting information
[debug] Looking for embeds
[debug] Identified a PeerTube embed
[PeerTube] Extracting URL: peertube:videos.lukesmith.xyz:cH3qvjkd4mZEJaRhdPQRtj
[PeerTube] cH3qvjkd4mZEJaRhdPQRtj: Downloading video JSON
[PeerTube] cH3qvjkd4mZEJaRhdPQRtj: Downloading description JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] cH3qvjkd4mZEJaRhdPQRtj: Downloading 1 format(s): 1080p-1
[debug] Invoking http downloader on "https://videos.lukesmith.xyz/static/streaming-playlists/hls/5ecf8343-cd24-4470-a048-f33741514e84/f37eea46-a41d-4296-8e97-944354a7d607-1080-fragmented.mp4"
[download] Resuming download at byte 523264
[debug] File locking is not supported. Proceeding without locking
[download] Destination: ＂How Do I Get a Good Tech Job？＂ [cH3qvjkd4mZEJaRhdPQRtj].mp4
[download]   0.3% of  345.44MiB at  751.32KiB/s ETA 07:49
```

It looks like when downloading a specific video, after trying the generic extractor, yt-dlp recognizes it as a PeerTube instance, and then switches to the proper extractor.

Could you please add Luke Smith's PeerTube instance, so it can be always properly detected?

Let me know if I can help to debug this somehow.

Thanks.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I've posted them in the first message.
```

**Comment by SirElderling** [comment]
I believe this URL is not being picked as a PeerTube playlist because it doesn't match the extractor URL pattern for a valid PeerTube Playlist:

```python
    _TYPES = {
        'a': 'accounts',
        'c': 'video-channels',
        'w/p': 'video-playlists',
    }
    _VALID_URL = r'''(?x)
                        https?://(?P<host>%s)/(?P<type>(?:%s))/
                    (?P<id>[^/]+)
                    ''' % (PeerTubeIE._INSTANCES_RE, '|'.join(_TYPES.keys()))`
```

Using your URL as an example, valid PeerTube playlists would be URLs similar to this:

```
https://videos.lukesmith.xyz/a/...
https://videos.lukesmith.xyz/c/...
https://videos.lukesmith.xyz/w/p/...
```

**Comment by gamer191** [comment]
untested workaround (once that gets added to to the instance list): https://videos.lukesmith.xyz/c/luke_channel/videos

**Comment by bashonly** [comment]
closing in favor of #16204
