### ISSUE TITLE
bilibilitv: download breaks after 8388608

### ISSUE THREAD

**Issue by zwieblum** [yt-dlp/yt-dlp#8773]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

EU

### Provide a description that is worded well enough to be understood

since 2 days bilibili.ty stops all downloads at exactly 8MB, e.g.:

[download]  55.6% of   14.39MiB at    1.11MiB/s ETA 00:05[download] Got error: Downloaded 8388608 bytes, expected 15092847 bytes. Retrying (1/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (2/10)...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.bilibili.tv/en/video/4786903491679744', '-vU']
[debug] User config "/home/nik/.config/yt-dlp/config": ['--no-cache-dir', '--restrict-filenames', '--trim-filenames', '128', '--embed-metadata', '--concurrent-fragments', '1', '--format-sort', 'ext', '--exec', 'timestamp="%(release_date>%s,upload_date>%s|NA)s"; echo "${timestamp}" | grep -Eq "^[^\\-][0-9]+$" && touch -m --date="@${timestamp}" %(filepath)q']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.12.13.232710 from yt-dlp/yt-dlp-nightly-builds [6b5d93b0b] (zip)
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.5.0-5-amd64-x86_64-with-glibc2.37 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.1-5 (setts), ffprobe 6.1-5
[debug] Optional libraries: brotli-1.1.0, certifi-2023.07.22, mutagen-1.46.0, requests-2.31.0, sqlite3-3.44.2, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.13.232710 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.13.232710 from yt-dlp/yt-dlp-nightly-builds)
[BiliIntl] Extracting URL: https://www.bilibili.tv/en/video/4786903491679744
[BiliIntl] 4786903491679744: Downloading webpage
WARNING: [BiliIntl] unable to extract JSON-LD ; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [BiliIntl] unable to extract og:title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [BiliIntl] unable to extract og:description; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[BiliIntl] 4786903491679744: Downloading video formats
[debug] Sort order given by user: ext
[debug] Formats sorted by: hasvid, ie_pref, vext, aext, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4786903491679744: Downloading 1 format(s): 9+1
[debug] Invoking http downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/1t/zp/n230425ad38mis41pnvmr621x8tyzp1t-1-131220110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1702566832&gen=playurlv2&os=akam&oi=1317955470&trid=388026478eb0499a8e58e5a62c2603c0i&mid=0&platform=pc&upsig=2ffcd8bbd4f4eaa2ea46a8e699104cff&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1702566832~hmac=ef6e7ec4912838145e9a12a61cefc6ddf1147685e8b99b75432d41e686e6334b&bvc=vod&nettype=0&orderid=0,1&logo=00000000&f=i_0_0"
[download] In_Another_Word_with_My_Smartphone_Season_2_Ep4-[4786903491679744].f9.mp4 has already been downloaded
[download] 100% of   20.91MiB
[debug] Invoking http downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/1t/zp/n230425ad38mis41pnvmr621x8tyzp1t-1-1c1301000022.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1702566832&gen=playurlv2&os=akam&oi=1317955470&trid=afae0bcbc5f043ab9ef6bbd5ba33640ai&mid=0&platform=pc&upsig=ee07bcd85b5c4a9afbe7a5ddb6d589a5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1702566832~hmac=fce1b0bec9120579bb05fbaa3d66d612d52e5d775b9ed2f28a8e4275f841136c&bvc=vod&nettype=0&orderid=0,1&logo=00000000&f=i_0_0"
[download] Resuming download at byte 8388608
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (1/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (2/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (3/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (4/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (5/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (6/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (7/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (8/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (9/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (10/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Giving up after 10 retries
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/nik/bin/yt-dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/home/nik/bin/yt-dlp/yt_dlp/__init__.py", line 1009, in main
    _exit(*variadic(_real_main(argv)))
  File "/home/nik/bin/yt-dlp/yt_dlp/__init__.py", line 999, in _real_main
    return ydl.download(all_urls)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3528, in download
    self.__download_wrapper(self.extract_info)(
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3503, in wrapper
    res = func(*args, **kwargs)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1570, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1581, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1737, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1796, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2939, in process_video_result
    self.process_info(new_info)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3387, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3126, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/http.py", line 362, in real_download
    for retry in RetryManager(self.params.get('retries'), self.report_retry):
  File "/home/nik/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5042, in __iter__
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/common.py", line 401, in report_retry
    RetryManager.report_retry(
  File "/home/nik/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5049, in report_retry
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/common.py", line 404, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1048, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 976, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by SirElderling** [comment]
I tested the sample URL provided and found no issue with the download.

**Comment by zwieblum** [comment]
I just tried again. Ut still stops, but now at 16MB:
```
$ yt-dlp https://www.bilibili.tv/en/video/4786903491679744 -vU
[debug] Command-line config: ['https://www.bilibili.tv/en/video/4786903491679744', '-vU']
[debug] User config "/home/nik/.config/yt-dlp/config": ['--no-cache-dir', '--restrict-filenames', '--trim-filenames', '128', '--embed-metadata', '--concurrent-fragments', '1', '--format-sort', 'ext', '--exec', 'timestamp="%(release_date>%s,upload_date>%s|NA)s"; echo "${timestamp}" | grep -Eq "^[^\\-][0-9]+$" && touch -m --date="@${timestamp}" %(filepath)q']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.12.19.232701 from yt-dlp/yt-dlp-nightly-builds [db8b4edc7] (zip)
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.5.0-5-amd64-x86_64-with-glibc2.37 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.1-5 (setts), ffprobe 6.1-5
[debug] Optional libraries: certifi-2023.07.22, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1796 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.19.232701 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.19.232701 from yt-dlp/yt-dlp-nightly-builds)
[BiliIntl] Extracting URL: https://www.bilibili.tv/en/video/4786903491679744
[BiliIntl] 4786903491679744: Downloading webpage
WARNING: [BiliIntl] unable to extract JSON-LD ; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [BiliIntl] unable to extract og:title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [BiliIntl] unable to extract og:description; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[BiliIntl] 4786903491679744: Downloading video formats
[debug] Sort order given by user: ext
[debug] Formats sorted by: hasvid, ie_pref, vext, aext, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4786903491679744: Downloading 1 format(s): 9+1
[debug] Invoking http downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/1t/zp/n230425ad38mis41pnvmr621x8tyzp1t-1-131220110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1703067800&gen=playurlv2&os=akam&oi=1317955470&trid=f2e88ae99acc4141b736982edcc10947i&mid=0&platform=pc&upsig=c5bed9ff2590a6398c8ffd9c98ca1df8&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1703067800~hmac=561243cb1fc35331ea444cebfdf0090b56c054bb45e34978d94cb2ae51a8e5e7&bvc=vod&nettype=0&orderid=0,1&logo=00000000&f=i_0_0"
[download] Destination: In_Another_Word_with_My_Smartphone_Season_2_Ep4-[4786903491679744].f9.mp4
[download]  76.5% of   20.91MiB at    1.85MiB/s ETA 00:02[download] Got error: Downloaded 16777216 bytes, expected 21924501 bytes. Retrying (1/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (2/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (3/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (4/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (5/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (6/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (7/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (8/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (9/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (10/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Giving up after 10 retries
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/nik/bin/yt-dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/home/nik/bin/yt-dlp/yt_dlp/__init__.py", line 1009, in main
    _exit(*variadic(_real_main(argv)))
  File "/home/nik/bin/yt-dlp/yt_dlp/__init__.py", line 999, in _real_main
    return ydl.download(all_urls)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3528, in download
    self.__download_wrapper(self.extract_info)(
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3503, in wrapper
    res = func(*args, **kwargs)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1570, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1581, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1737, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1796, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2939, in process_video_result
    self.process_info(new_info)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3387, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3126, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/http.py", line 362, in real_download
    for retry in RetryManager(self.params.get('retries'), self.report_retry):
  File "/home/nik/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5042, in __iter__
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/common.py", line 401, in report_retry
    RetryManager.report_retry(
  File "/home/nik/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5049, in report_retry
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/common.py", line 404, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1048, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 976, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


[debug] Invoking http downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/1t/zp/n230425ad38mis41pnvmr621x8tyzp1t-1-1c1301000022.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1703067800&gen=playurlv2&os=akam&oi=1317955470&trid=09bb20294dc44200986fce340a7b6f3fi&mid=0&platform=pc&upsig=4e5eb95b5a83e932590ec494ee7b06fb&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1703067800~hmac=af8a92bde22dfa87cb59b85abc56be502fd5a89f769dab976d452ded23c8fbc9&bvc=vod&nettype=0&orderid=0,1&logo=00000000&f=i_0_0"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4069, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nik/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nik/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nik/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/nik/bin/yt-dlp/yt_dlp/networking/_requests.py", line 341, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3387, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3126, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/http.py", line 364, in real_download
    establish_connection()
  File "/home/nik/bin/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nik/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4101, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden
```

**Comment by SirElderling** [comment]
I believe you're facing the same issue described in issue #6640 
Please add ```--add-header 'Referer: https://www.bilibili.tv/'``` to the yt-dlp arguments. It should work.

**Comment by zwieblum** [comment]
That did the trick, thank you! Just for the record: I had to remove the space, so `--add-header 'Referer:https://www.bilibili.tv/'` did it.
