### ISSUE TITLE
VGTV  Unauthorized

### ISSUE THREAD

**Issue by thomhans** [yt-dlp/yt-dlp#8784]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Provide a description that is worded well enough to be understood

When running  yt-dlp -vU --cookies-from-browser firefox "https://tv.vg.no/video/211384/episode-5-ikke-lov-aa-le-paa-hytta", i get unauthorized. Video plays in Firefox without issue. Tested several other videos, but same issue.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://tv.vg.no/video/211384/episode-5-ikke-lov-aa-le-paa-hytta']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Thomas\AppData\Roaming\Mozilla\Firefox\Profiles\9jobpdcw.default-release\cookies.sqlite"
Extracted 2468 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.1 (CPython AMD64 64bit) - Windows-11-10.0.22621-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg N-112998-g1f56bfc986-20231216 (setts)
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[VGTV] Extracting URL: https://tv.vg.no/video/211384/episode-5-ikke-lov-aa-le-paa-hytta
[VGTV] 211384: Downloading media JSON
[VGTV] 211384: Downloading m3u8 information
WARNING: [VGTV] Failed to download m3u8 information: HTTP Error 401: Unauthorized
ERROR: [VGTV] 211384: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1581, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1737, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1796, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2768, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Users\Thomas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1079, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [VGTV] 211384: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Brog33** [comment]
The free videos doesn't download either. I can play the video fine in the browser, so the geo restriction message is incorrect.

```
yt-dlp "https://tv.vg.no/video/283093/oscar-bobb-avgjor-kampen-for-city-pa-overtid"
[VGTV] Extracting URL: https://tv.vg.no/video/283093/oscar-bobb-avgjor-kampen-for-city-pa-overtid
[VGTV] 283093: Downloading media JSON
[VGTV] 283093: Downloading m3u8 information
WARNING: [VGTV] Failed to download m3u8 information: HTTP Error 401: Unauthorized
ERROR: [VGTV] 283093: This video is not available from your location due to geo restriction
This video is available in Norway.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
```
