### ISSUE TITLE
DigitalTheatre.com

### ISSUE THREAD

**Issue by mcicconi** [yt-dlp/yt-dlp#8801]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

https://www.digitaltheatre.com/watch/vod/37632854/the-crucible

### Provide a description that is worded well enough to be understood

URL is unsupported

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.digitaltheatre.com/watch/vod/37632854/the-crucible', '--cookies-from-browser', 'firefox', '-vU']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\micha\AppData\Roaming\Mozilla\Firefox\Profiles\0sp9qxmn.default\cookies.sqlite"
Extracted 2619 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.digitaltheatre.com/watch/vod/37632854/the-crucible
[generic] the-crucible: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] the-crucible: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.digitaltheatre.com/watch/vod/37632854/the-crucible
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2578, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.digitaltheatre.com/watch/vod/37632854/the-crucible
```

**Comment by seproDev** [comment]
As a note for anyone implementing this: using `platform=safari` on the `api/show/stream` endpoint the videos are not DRM protected, while with chrome/firefox they are.

**Comment by gamer191** [comment]
Alternatively, adding `_clear` before `.ism` also works (changing `.mpd` to `.m3u8` might also be necessary, but I doubt it)

**Comment by gamer191** [comment]
Actually, the `.mpd` manifest contains separate video and audio, whilst the `.m3u8` manifest merges them. I'm not sure which one is ideal, or if we should call both and let the user decide. Someone should probably test if they are identical in quality, but I don't have time right now

**Comment by evelynmaire** [comment]
> As a note for anyone implementing this: using `platform=safari` on the `api/show/stream` endpoint the videos are not DRM protected, while with chrome/firefox they are.

Sorry to bother, but would you mind explaining how to use this? I've had a look at the documentation and wiki, but I'm not sure how to go about this

**Comment by bashonly** [comment]
@evelynmaire those are notes for whoever wants to write the extractor code. See [the contributing guide](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md) if you are interested in doing so, or if you need additional guidance you can pop in to [the discord server](https://discord.gg/H5MNcFW63r). Otherwise, this information is not usable for a yt-dlp user

**Comment by dirkf** [comment]
Also, account needed, except for trailers that may be handled differently.

**Comment by evelynmaire** [comment]
> @evelynmaire those are notes for whoever wants to write the extractor code. See [the contributing guide](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md) if you are interested in doing so, or if you need additional guidance you can pop in to [the discord server](https://discord.gg/H5MNcFW63r). Otherwise, this information is not usable for a yt-dlp user

Ah, I understand, thank you for taking the time to respond!
