### ISSUE TITLE
this new error is making me crazy anyone?

### ISSUE THREAD

**Issue by Sapkotazz** [yt-dlp/yt-dlp#8809]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.xvideos.com/video76903059/indian_teen_fucked_in_bathroom']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.10586-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112693-g44a0148fad-20231106 (setts), ffprobe N-112693-g44a0148fad-20231106
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[XVideos] Extracting URL: https://www.xvideos.com/video76903059/indian_teen_fucked_in_bathroom
[XVideos] 76903059: Downloading webpage
ERROR: [XVideos] 76903059: Unable to download webpage: EOF occurred in violation of protocol (_ssl.c:1131) (caused by SSLError('EOF occurred in violation of protocol (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\xvideos.py", line 97, in _real_extract
  File "yt_dlp\extractor\common.py", line 1118, in _download_webpage
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage

  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1096, in _validate_conn
  File "urllib3\connection.py", line 642, in connect
  File "urllib3\connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 470, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 514, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 445, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 304, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 530, in send
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4052, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 322, in _send
yt_dlp.networking.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)
```

**Comment by bashonly** [comment]
That is not a verbose log. This tends to happen with poor VPN connections

**Comment by Sapkotazz** [comment]
i had it working before setuping ffmpeg but after i did this tutorial https://www.geeksforgeeks.org/how-to-install-ffmpeg-on-windows/
this is happening. how do i resolve it? i am new to this can you explain?

**Comment by Sapkotazz** [comment]
> That is not a verbose log. This tends to happen with poor VPN connections

i corrected the verbose output please have a look

**Comment by bashonly** [comment]
Installing ffmpeg wouldn't have affected/caused this. Just a coincidence

You can try passing `--no-check-certificate`

**Comment by Sapkotazz** [comment]
``shell
[XVideos] Extracting URL: https://www.xvideos.com/video76903059/indian_teen_fucked_in_bathroom
[XVideos] 76903059: Downloading webpage
ERROR: [XVideos] 76903059: Unable to download webpage: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')) (caused by TransportError("('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))"))

C:\yt-dlp>yt-dlp -vU --no-check-certificate https://www.xvideos.com/video76903059/indian_teen_fucked_in_bathroom
[debug] Command-line config: ['-vU', '--no-check-certificate', 'https://www.xvideos.com/video76903059/indian_teen_fucked_in_bathroom']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.10586-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112693-g44a0148fad-20231106 (setts), ffprobe N-112693-g44a0148fad-20231106
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[XVideos] Extracting URL: https://www.xvideos.com/video76903059/indian_teen_fucked_in_bathroom
[XVideos] 76903059: Downloading webpage
ERROR: [XVideos] 76903059: Unable to download webpage: EOF occurred in violation of protocol (_ssl.c:1131) (caused by SSLError('EOF occurred in violation of protocol (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\xvideos.py", line 97, in _real_extract
  File "yt_dlp\extractor\common.py", line 1118, in _download_webpage
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage

  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1096, in _validate_conn
  File "urllib3\connection.py", line 642, in connect
  File "urllib3\connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 470, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 514, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 445, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 304, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 530, in send
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4052, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 322, in _send
yt_dlp.networking.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)
``

**Comment by Sapkotazz** [comment]
`[XVideos] Extracting URL: https://www.xvideos.com/video76903059/indian_teen_fucked_in_bathroom
[XVideos] 76903059: Downloading webpage
ERROR: [XVideos] 76903059: Unable to download webpage: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')) (caused by TransportError("('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))"))

C:\yt-dlp>yt-dlp -vU --no-check-certificate https://www.xvideos.com/video76903059/indian_teen_fucked_in_bathroom
[debug] Command-line config: ['-vU', '--no-check-certificate', 'https://www.xvideos.com/video76903059/indian_teen_fucked_in_bathroom']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.10586-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112693-g44a0148fad-20231106 (setts), ffprobe N-112693-g44a0148fad-20231106
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[XVideos] Extracting URL: https://www.xvideos.com/video76903059/indian_teen_fucked_in_bathroom
[XVideos] 76903059: Downloading webpage
ERROR: [XVideos] 76903059: Unable to download webpage: EOF occurred in violation of protocol (_ssl.c:1131) (caused by SSLError('EOF occurred in violation of protocol (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\xvideos.py", line 97, in _real_extract
  File "yt_dlp\extractor\common.py", line 1118, in _download_webpage
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage

  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1096, in _validate_conn
  File "urllib3\connection.py", line 642, in connect
  File "urllib3\connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 470, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 514, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 445, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 304, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 530, in send
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4052, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 322, in _send
yt_dlp.networking.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)`

**SAME ERROR BRO**

**Comment by pukkandan** [comment]
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

Check again

**Comment by Sapkotazz** [comment]
the videos are playable when dns are setup ie 8.8.8.8 but when not its unplayable cause gov has blocked every porn sites here.

**Comment by Sapkotazz** [comment]
> > * [x]   I've checked that all provided URLs are playable in a browser with the same IP and same login details
> 
> Check again


the videos are playable when dns are setup ie 8.8.8.8 but when not its unplayable cause gov has blocked every porn sites here.

**Comment by Sapkotazz** [comment]
> Is the DNS set up system wide?

what does that mean no idea?
i just changed ipv4 dns settings to 8.8.8.8

**Comment by pukkandan** [comment]
Try adding a `-4` to yt-dlp command

**Comment by Sapkotazz** [comment]
its working now without doing anything weird
