### ISSUE TITLE
medici.tv URLs Not Being Recognized by 'medici' Extractor

### ISSUE THREAD

**Issue by Offert4324** [yt-dlp/yt-dlp#8813]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Korea

### Provide a description that is worded well enough to be understood

I am experiencing an issue where yt-dlp is not recognizing URLs from medici.tv with the designated 'medici' extractor. Below is a detailed description of the problem:

When attempting to download videos from medici.tv using yt-dlp, the URLs are being treated as generic instead of being processed by the 'medici' extractor.

Example URL: An example of a URL that should be processed by the 'medici' extractor but is not is https://www.medici.tv/en/concerts/concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony

Testing and Debugging Attempts:

Initially, the regular expression for the medici extractor (`r'https?://(?:www\.)?medici\.tv/#!/(?P<id>[^?#&]+)`) did not match certain medici.tv URLs, such as the example URL.  To address this, I modified the regex to `r'https?://(?:www\.)?(?:medici|edu\.medici)\.tv/(?:(?:[a-zA-Z0-9-_\.]+)/)*(?:#!/)?(?P<id>[^?#&]+)'`. This change was intended to make the regex more flexible and inclusive of different URL patterns on medici.tv. Using Python's re module, I confirmed that the modified regex successfully matches the example medici.tv URL. However, when I run yt-dlp with this modified regex, the URLs are still treated as generic, and the medici extractor is not used. Using `--use-extractors medici` didn't help either.

At my current level of Python knowledge, this was the best I could do. Therefore, I would like you to fix the links to medici.tv are correctly recognised by the 'medici' extractor.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://www.medici.tv/en/concerts/concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony', '-vU']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\ohdor\AppData\Roaming\Mozilla\Firefox\Profiles\69s8cetx.default-release\cookies.sqlite"
Extracted 2427 cookies from firefox
[debug] Encodings: locale cp949, fs utf-8, pref cp949, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg 2023-05-08-git-2d43c23b81-full_build-www.gyan.dev (setts), ffprobe 2023-05-08-git-2d43c23b81-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.1.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.medici.tv/en/concerts/concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony
[generic] concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.medici.tv/en/concerts/concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony
Traceback (most recent call last):
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\generic.py", line 2578, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.medici.tv/en/concerts/concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony

[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://www.medici.tv/en/concerts/concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony', '--use-extractors', 'medici', '-vU']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\ohdor\AppData\Roaming\Mozilla\Firefox\Profiles\69s8cetx.default-release\cookies.sqlite"
Extracted 2426 cookies from firefox
[debug] Encodings: locale cp949, fs utf-8, pref cp949, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg 2023-05-08-git-2d43c23b81-full_build-www.gyan.dev (setts), ffprobe 2023-05-08-git-2d43c23b81-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.1.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
ERROR: No suitable extractor found for URL https://www.medici.tv/en/concerts/concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony
```

**Comment by pukkandan** [comment]
`pip` installs are not meant to be editable. It'll work if you delete `extractors/lazy_extractors.py`

**Comment by Offert4324** [comment]
Now it is successfully processed by the Medici extractor, but it fails to get `csrftoken` cookie from the website. Here's verbose output:
```
[debug] Command-line config: ['https://www.medici.tv/en/concerts/concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony', '-vU']
[debug] Encodings: locale cp949, fs utf-8, pref cp949, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg 2023-05-08-git-2d43c23b81-full_build-www.gyan.dev (setts), ffprobe 2023-05-08-git-2d43c23b81-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.1.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[Medici] Extracting URL: https://www.medici.tv/en/concerts/concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony
[Medici] concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony: Downloading webpage
ERROR: concours-de-geneve-international-music-competition-2023-flute-final-and-awards-ceremony: An extractor error has occurred. (caused by KeyError('csrftoken')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\medici.py", line 42, in _real_extract
    'X-CSRFToken': self._get_cookies(url)['csrftoken'].value,
                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'csrftoken'
```

**Comment by Offert4324** [comment]
Now I found that there's a cookie named `csrftoken_satie`, so I change `'X-CSRFToken': self._get_cookies(url)['csrftoken'].value` into `'X-CSRFToken': self._get_cookies(url)['csrftoken_satie'].value` and now it seems that I overcame that part. However, I encountered another error:

```
[debug] Command-line config: ['--cookies-from-browser', 'firefox', '--write-subs', '--sub-langs', 'all', 'https://edu.medici.tv/en/operas/lady-macbeth-mtsensk-opera-de-paris-2019', '-vU']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\ohdor\AppData\Roaming\Mozilla\Firefox\Profiles\69s8cetx.default-release\cookies.sqlite"
Extracted 2314 cookies from firefox
[debug] Encodings: locale cp949, fs utf-8, pref cp949, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg 2023-05-08-git-2d43c23b81-full_build-www.gyan.dev (setts), ffprobe 2023-05-08-git-2d43c23b81-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.1.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[Medici] Extracting URL: https://edu.medici.tv/en/operas/lady-macbeth-mtsensk-opera-de-paris-2019
[Medici] lady-macbeth-mtsensk-opera-de-paris-2019: Downloading webpage
[Medici] lady-macbeth-mtsensk-opera-de-paris-2019: Downloading JSON metadata
ERROR: [Medici] lady-macbeth-mtsensk-opera-de-paris-2019: lady-macbeth-mtsensk-opera-de-paris-2019: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\medici.py", line 35, in _real_extract
    data = self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1039, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1029, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1016, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 999, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 555, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1013, in _parse_json
    return json.loads(
           ^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ohdor\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 563, in decode
    raise type(e)(f'{e.msg} in {s[e.pos-10:e.pos+10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by Offert4324** [comment]
#9518
