### ISSUE TITLE
[Vimeo] On some videos, after ffprobe, json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)

### ISSUE THREAD

**Issue by lcorbasson** [yt-dlp/yt-dlp#8818]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide (accessed from France)

### Provide a description that is worded well enough to be understood

On some Vimeo videos, e.g. https://vimeo.com/314447567, `yt-dlp` downloads the video but seems to fail at a `ffprobe` step, apparently because of malformed JSON:

```
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Formation_TL_Alerte_Radio [314447567].mp4'
ERROR: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)

[…]

json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU  "https://vimeo.com/314447567"
[debug] Command-line config: ['-vU', 'https://vimeo.com/314447567']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.12.19.232701 from yt-dlp/yt-dlp-nightly-builds [db8b4edc7] (pip)
[debug] Python 3.9.16 (CPython x86_64 64bit) - CYGWIN_NT-10.0-19045-3.4.10-1.x86_64-x86_64-64bit-WindowsPE (OpenSSL 1.1.1w  11 Sep 2023)
[debug] exe versions: ffmpeg 6.0 (fdk,setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.34.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1796 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.19.232701 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.19.232701 from yt-dlp/yt-dlp-nightly-builds)
[vimeo] Extracting URL: https://vimeo.com/314447567
[vimeo] 314447567: Downloading webpage
[vimeo] 314447567: Downloading JSON metadata
[vimeo] 314447567: Downloading JSON metadata
[vimeo] 314447567: Downloading jwt token
[vimeo] 314447567: Downloading JSON metadata
[vimeo] 314447567: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 314447567: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 314447567: Downloading fastly_skyfire m3u8 information
[vimeo] 314447567: Downloading fastly_skyfire m3u8 information
[vimeo] 314447567: Downloading google_mediacdn m3u8 information
[vimeo] 314447567: Downloading google_mediacdn m3u8 information
[vimeo] 314447567: Downloading akfire_interconnect_quic MPD information
[vimeo] 314447567: Downloading akfire_interconnect_quic MPD information
[vimeo] 314447567: Downloading fastly_skyfire MPD information
[vimeo] 314447567: Downloading fastly_skyfire MPD information
[vimeo] 314447567: Downloading google_mediacdn MPD information
[vimeo] 314447567: Downloading google_mediacdn MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 314447567: Downloading 1 format(s): hls-google_mediacdn-1956
[debug] Invoking hlsnative downloader on "https://cme-media.vimeocdn.com/5393c265-bd73-4b95-a3f9-d6fe13d48110/edge-cache-token=Expires=1703115966&KeyName=media-cdn-key&Signature=2ldOO4TylX_WokgDgD6V0D_pL_IWGt2dVhMP2b54BQTR7yb2XsXpsTmusaa0XfQT3oUEYBecy0T99TPDfLXGDg==/both/video/afa7db42/playlist.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 40
[download] Destination: Formation_TL_Alerte_Radio [314447567].mp4
[download] 100% of   58.10MiB in 00:00:13 at 4.19MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Formation_TL_Alerte_Radio [314447567].mp4'
ERROR: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
Traceback (most recent call last):
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1581, in wrapper
    return func(self, *args, **kwargs)
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1737, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1796, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2939, in process_video_result
    self.process_info(new_info)
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3482, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3662, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3644, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3622, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 900, in run
    if all(self._needs_fixup(info)):
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 891, in _needs_fixup
    metadata = self.get_metadata_object(info['filepath'])
  File "/home/corbassonl/envs/yt-dlp/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 296, in get_metadata_object
    return json.loads(stdout)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

**Comment by pukkandan** [comment]
Can't reproduce. Can you check by updating your ffprobe?

**Comment by bashonly** [comment]
Could it have something to do with yt-dlp trying to parse windows ffprobe exe output inside a Cygwin (unix-like) shell? Some sort of shell quoting issue?

**Comment by DUB1401** [comment]
I also have this problem with [vk.com](https://vk.com/), but my solution is update **ffmpeg** to last version.
