### ISSUE TITLE
NAVER TV webpage changed.

### ISSUE THREAD

**Issue by mistr7** [yt-dlp/yt-dlp#8850]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

대한민국 Korea, Republic of

### Provide a description that is worded well enough to be understood

It seems that the way videos are provided on the webpage has changed due to the NAVER TV site (http://tv.naver.com/) being revamped, causing it to not be recognized properly.
Please check.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Invalid: [navertv] https://tv.naver.com/v/44559850

version: 4.0+ (23-12-18 14:46:45 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 25 / False / 698a8e0641174b11a8a8c09d3528fa36
input: https://tv.naver.com/v/44559850
type: navertv
single: True
url: https://tv.naver.com/v/44559850
dir:
zip:
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702982650.6031163 (23-12-19 10:44:10 UTC) - 227s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
[debug] [Naver] Extracting URL: https://tv.naver.com/v/44559850
[debug] [Naver] 44559850: Downloading JSON metadata
[debug] [Naver] Extracting URL: https://tv.naver.com/v/44559850
[debug] [Naver] 44559850: Downloading JSON metadata
[debug] [Naver] Extracting URL: https://tv.naver.com/v/44559850
[debug] [Naver] 44559850: Downloading JSON metadata
[debug] [Naver] Extracting URL: https://tv.naver.com/v/44559850
[debug] [Naver] 44559850: Downloading JSON metadata
ERROR: [Naver] 44559850: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
stop
Traceback (most recent call last):
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\networking_urllib", line 410, in _send
res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
File "urllib\request", line 531, in open
File "urllib\request", line 640, in http_response
File "urllib\request", line 569, in error
File "urllib\request", line 502, in _call_chain
File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\YoutubeDL", line 4051, in urlopen
return self._request_director.send(req)
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\networking\common", line 114, in send
response = handler.send(request)
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\networking_helper", line 204, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\networking\common", line 325, in send
return self._send(request)
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\networking_urllib", line 415, in _send
raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\extractor\common", line 847, in _request_webpage
return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
File "ytdl", line 457, in urlopen
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\YoutubeDL", line 4070, in urlopen
raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\YoutubeDL", line 1567, in wrapper
return func(self, *args, **kwargs)
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\YoutubeDL", line 1702, in __extract_info
ie_result = ie.extract(url)
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\extractor\common", line 715, in extract
ie_result = self._real_extract(url)
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\extractor\naver", line 150, in _real_extract
content = self._download_json(
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\extractor\common", line 1069, in download_content
res = getattr(self, download_handle.name)(url_or_request, video_id, **kwargs)
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\extractor\common", line 1033, in download_handle
res = self._download_webpage_handle(
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\extractor\common", line 903, in _download_webpage_handle
urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\extractor\common", line 860, in _request_webpage
raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [Naver] 44559850: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1376, in start
File "utils", line 1455, in start_
File "extractor\navertv_downloader", line 25, in read
File "utils", line 871, in call
File "decorator", line 232, in fun
File "constants", line 909, in try_
File "constants", line 878, in try_
File "extractor\navertv_downloader", line 49, in get
File "ytdl", line 465, in extract_info
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\YoutubeDL", line 1556, in extract_info
return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
File "C:\Users\M\AppData\Local\Temp_MEI175362\ytdl_2f3c74dd\yt_dlp\yt_dlp\YoutubeDL", line 1585, in wrapper
self.report_error(str(e), e.format_traceback())
File "ytdl", line 408, in report_error
yt_dlp.utils.DownloadError: ERROR: [Naver] 44559850: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

Invalid: fail=True
EOT: https://tv.naver.com/v/44559850 (0.5s)
```

**Comment by SamuelDovgin** [comment]
Having the same issue ^^^
