### ISSUE TITLE
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

### ISSUE THREAD

**Issue by Poilaucul** [yt-dlp/yt-dlp#886]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.09.02**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
[youtube] wQ_G1-bFKVc: Downloading webpage
[youtube] wQ_G1-bFKVc: Downloading MPD manifest
[youtube] wQ_G1-bFKVc: Marking watched
[info] Writing video description metadata as JSON to: U:\MPV\TechnicalGods - Videos\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (1280x708_vp9_mp4a.40.2_60fps).info.json
[youtube] wQ_G1-bFKVc: Downloading thumbnail ...
[youtube] wQ_G1-bFKVc: Writing thumbnail to: U:\MPV\TechnicalGods - Videos\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (1280x708_vp9_mp4a.40.2_60fps).jpg
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1630691037/ei/fQoyYajhEuiKvdIP89unuA4/ip/2a01%3Ae0a%3A3b9%3Aa610%3A9b2%3Aff4b%3A91a7%3A4e81/id/c10fc6d7e6c52957/source/youtube/requiressl/yes/playback_host/r16---sn-4gxx-25gy.googlevideo.com/mh/EV/mm/31%2C29/mn/sn-4gxx-25gy%2Csn-4gxx-25gel/ms/au%2Crdu/mv/m/mvi/16/nh/EAE%2CEAE/pl/50/tx/24047103/txs/24047098%2C24047099%2C24047100%2C24047101%2C24047102%2C24047103%2C24047104/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1176250/vprv/1/mt/1630669008/fvip/16/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRgIhAIO0mgKNZ0pUVw6CTRCQDY5UoUbIk28lDGw1LtG6T6rWAiEA4NjjTdOA_lrsoJB6BW8gA5Tvsuz6gK1X8Yw35TC5VEQ%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cnh%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAKtUFy1P-poBmpfv41HUhwyKYjwc0eXrIQ465n-NsNd3AiEA--kYV-yoLEcK7zj5r94My2s2FjooPs9Naa4C3eZQYTk%3D'
[download] U:\MPV\TechnicalGods - Videos\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (1280x708_vp9_none_60fps).f302.webm has already been downloaded
[download] 100% of 59.35MiB
[debug] Invoking downloader on 'https://r16---sn-4gxx-25gy.googlevideo.com/videoplayback?expire=1630691037&ei=fQoyYajhEuiKvdIP89unuA4&ip=2a01%3Ae0a%3A3b9%3Aa610%3A9b2%3Aff4b%3A91a7%3A4e81&id=o-AAkT3wjV38_qFgq6pxpqTo8BvXtXOtBffllzYS6MtJ_-&itag=140&source=youtube&requiressl=yes&mh=EV&mm=31%2C29&mn=sn-4gxx-25gy%2Csn-4gxx-25gel&ms=au%2Crdu&mv=m&mvi=16&nh=EAE%2CEAE&pl=50&initcwndbps=1176250&vprv=1&mime=audio%2Fmp4&ns=FSk8HhQkJNxr0Hmqxacs9jEG&gir=yes&clen=9708529&otfp=1&dur=599.841&lmt=1597683221262351&mt=1630669008&fvip=16&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6211222&n=HDwVJqUv_Zc5SP2w&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJPH8Yp6CfbAHdvApWA0LQL7trezmvUintXl9IaOaA4XAiBzCdk0yPD_3Hh8sSD_L9LFIsns1wkGWsIIHnC3dI6rPg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cnh%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgMmjihlqlAJwUJS9f-3J4Q2Ye525VPI4KyXC0GM5_eV8CIBEjmnlp-BTCv2OGycuZRnJsfj3PQUnn-4BWs4DlmUrf'
[download] U:\MPV\TechnicalGods - Videos\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (NA_none_mp4a.40.2_NAfps).f140.m4a has already been downloaded
[download] 100% of 9.26MiB
[ffmpeg] Merging formats into "U:\MPV\TechnicalGods - Videos\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (1280x708_vp9_mp4a.40.2_60fps).mkv"
[debug] ffmpeg command line: "C:\Program Files\FFmpeg\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:U:\MPV\TechnicalGods - Videos\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (1280x708_vp9_none_60fps).f302.webm" -i "file:U:\MPV\TechnicalGods - Videos\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (NA_none_mp4a.40.2_NAfps).f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:U:\MPV\TechnicalGods - Videos\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (1280x708_vp9_mp4a.40.2_60fps).temp.mkv"
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2115, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\postprocessor\ffmpeg.py", line 523, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

[ffmpeg] Adding metadata to 'U:\MPV\TechnicalGods - Videos\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (1280x708_vp9_mp4a.40.2_60fps).mkv'
ERROR: [WinError 2] Le fichier spécifié est introuvable: 'U:\\MPV\\TechnicalGods - Videos\\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (1280x708_vp9_mp4a.40.2_60fps).mkv'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 847, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 881, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 1692, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2050, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2115, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\postprocessor\ffmpeg.py", line 509, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\postprocessor\ffmpeg.py", line 210, in run_ffmpeg_multiple_files
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\postprocessor\ffmpeg.py", line 210, in <genexpr>
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'U:\\MPV\\TechnicalGods - Videos\\20200817 - wQ_G1-bFKVc - TGFX Market Breakdown  - 8_17_20 (1280x708_vp9_mp4a.40.2_60fps).mkv'

```

## Description

The ffmpeg command that merges the files from this video https://www.youtube.com/watch?v=wQ_G1-bFKVc fails.

**Comment by Ashish0804** [comment]
paste output of `yt-dlp -v https://www.youtube.com/watch?v=wQ_G1-bFKVc `

**Comment by pukkandan** [comment]
Same underlying issue as https://github.com/yt-dlp/yt-dlp/issues/871, https://github.com/ytdl-org/youtube-dl/issues/28042

See https://github.com/yt-dlp/yt-dlp/issues/871#issuecomment-911701285 for workarounds
