### ISSUE TITLE
Skool (or luna.loom.com via m3u8) Site Request

### ISSUE THREAD

**Issue by wmortume** [yt-dlp/yt-dlp#8863]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

https://www.skool.com
https://www.skool.com/thepodcastnetwork/classroom/d98c97da?md=d1f198f50e0e4e53882ec64a10ed3a7d
https://luna.loom.com/id/9da752c522624c7399d647c0ee976c56/rev/6f316065ce1e493c8870ffafc3db8dc1112a1774feed0515f1ea2d34d79fd33fb/resource/hls/mediaplaylist-video-bitrate3200.m3u8

### Provide a description that is worded well enough to be understood

I want to be able to download videos from [skool](https://www.skool.com). I have tried using m3u8 links which use the [luna.loom](https://luna.loom.com) domain but it blocks me from downloading any videos by giving a 403 forbidden error. I included a link to a community classroom that is accessible by everyone who can test it out however the luna m3u8 link gets regenerated when the site gets refreshed so that one ain't usable.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version nightly@2023.12.26.232752 from yt-dlp/yt-dlp-nightly-builds [225cf2b83] (win_exe)
[debug] Compatibility options: no-external-downloader-progress, manifest-filesize-approx, prefer-legacy-http-handler, playlist-match-filter
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-36-gc5039e158d-20231023 (setts), ffprobe n6.0-36-gc5039e158d-20231023
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.26.232752 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.26.232752 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.skool.com/thepodcastnetwork/classroom/d98c97da?md=d1f198f50e0e4e53882ec64a10ed3a7d
[generic] d98c97da?md=d1f198f50e0e4e53882ec64a10ed3a7d: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] d98c97da?md=d1f198f50e0e4e53882ec64a10ed3a7d: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.skool.com/thepodcastnetwork/classroom/d98c97da?md=d1f198f50e0e4e53882ec64a10ed3a7d
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1581, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1716, in __extract_info
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.skool.com/thepodcastnetwork/classroom/d98c97da?md=d1f198f50e0e4e53882ec64a10ed3a7d
[media-downloader] Download Failed(ErrorCode=1)



[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version nightly@2023.12.26.232752 from yt-dlp/yt-dlp-nightly-builds [225cf2b83] (win_exe)
[debug] Compatibility options: playlist-match-filter, no-external-downloader-progress, prefer-legacy-http-handler, manifest-filesize-approx
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-36-gc5039e158d-20231023 (setts), ffprobe n6.0-36-gc5039e158d-20231023
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.26.232752 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.26.232752 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://luna.loom.com/id/9da752c522624c7399d647c0ee976c56/rev/6f316065ce1e493c8870ffafc3db8dc1112a1774feed0515f1ea2d34d79fd33fb/resource/hls/mediaplaylist-video-bitrate3200.m3u8
[generic] mediaplaylist-video-bitrate3200: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2392, in _real_extract
  File "yt_dlp\extractor\common.py", line 863, in _request_webpage
  File "yt_dlp\networking\_urllib.py", line 396, in _send
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4076, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 401, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 850, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4108, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden
[media-downloader] Download Failed(ErrorCode=1)
```

**Comment by bashonly** [comment]
Loom support was added in f859ed3ba1e8b129ae6a467592c65687e73fbca1

Update to nightly and you can copy the "Watch on Loom" link and pass that to yt-dlp:
`https://www.loom.com/share/9da752c522624c7399d647c0ee976c56`

This site does not embed loom in the standard html iframe way; instead, the video link is stashed in the hydration JSON. So if you want to be able to pass `skool.com` URLs to yt-dlp, a dedicated extractor would still be needed. Is loom support sufficient, or do you still want to request a dedicated extractor for skool?

**Comment by fastily** [comment]
A dedicated extractor for school would certainly be a nice-to-have.  I hacked together a solution using Chrome + `chromedriver` to extract the "Watch on Loom" URL and while janky, it _mostly_ works.

**Comment by wmortume** [comment]
> Loom support was added in [f859ed3](https://github.com/yt-dlp/yt-dlp/commit/f859ed3ba1e8b129ae6a467592c65687e73fbca1)
> 
> Update to nightly and you can copy the "Watch on Loom" link and pass that to yt-dlp: `https://www.loom.com/share/9da752c522624c7399d647c0ee976c56`
> 
> This site does not embed loom in the standard html iframe way; instead, the video link is stashed in the hydration JSON. So if you want to be able to pass `skool.com` URLs to yt-dlp, a dedicated extractor would still be needed. Is loom support sufficient, or do you still want to request a dedicated extractor for skool?

Yeah, I would request a dedicated extractor for skool.

**Comment by joshenders** [comment]
> A dedicated extractor for skool would certainly be a nice-to-have. I hacked together a solution using Chrome + `chromedriver` to extract the `Watch on Loom` URL and while janky, it _mostly_ works

Is that something you're willing to share in this thread for people searching for a solution while this feature is being developed?

**Comment by jswillia** [comment]
> A dedicated extractor for skool would certainly be a nice-to-have. I hacked together a solution using Chrome + `chromedriver` to extract the `Watch on Loom` URL and while janky, it _mostly_ works

+1 to the above. Would be very grateful if you could share here how you got that to work while we wait/hope for official Skool support. Thank you for your consideration.

**Comment by TravisRice66** [comment]
Hey guys not sure this is fully easily understood. Took me another 5 minutes after finding this post to understand so heres my understanding

Once you get a m3u8 URL the section immediate after the ID section is the video share link. So you could take the 9da752c522624c7399d647c0ee976c56 in the above example and throw it into https://www.loom.com/share/ link and then you get https://www.loom.com/share/9da752c522624c7399d647c0ee976c56 
from the 
https://luna.loom.com/id/9da752c522624c7399d647c0ee976c56/rev/6f316065ce1e493c8870ffafc3db8dc1112a1774feed0515f1ea2d34d79fd33fb/resource/hls/mediaplaylist-video-bitrate3200.m3u8

which works in the command line to download the video

I wasnt get audio for the longest time and realized I didnt have [ffmpeg and ffprobe](https://www.ffmpeg.org/) so def use pip install and get those in! Otherwise hope that helps

**Comment by TravisRice66** [comment]
Also! I couldnt get it to download on the stable build so I downloaded the nightly version on yt-dlp and it works flawlessly.
