### ISSUE TITLE
[7plus] Unable to download video subtitles for 'en': HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by VampiricAlien** [yt-dlp/yt-dlp#8864]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

Unable to download anything with subtitles due to a 403 error. I've tried with and without VPN. Download works if not downloading subs. if I am the only one with this issue please close it.
I can see from the log `7NNB23-361: Downloading subtitles: en` `Unable to download video subtitles for 'en': HTTP Error 403: Forbidden`

I go to download anything else without subtitles
`[download] Destination: S12 E9 - Pokie Pass Out [HWYP12-009].fhls-1522.mp4`

`[download]   0.3% of ~ 201.88MiB at   78.13KiB/s ETA 41:23 (frag 0/129)`

No issue.

Account isn't needed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Compatibility options: embed-metadata
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-39-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.19.0, certifi-2020.06.20, mutagen-1.47.0, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1901 extractors
[debug] Using fake IP 1.138.183.156 (AU) as X-Forwarded-For
[7plus] Extracting URL: https://7plus.com.au/seven-news-brisbane?episode-id=7NNB23-361
[7plus] 7NNB23-361: Downloading JSON metadata
[7plus] 7NNB23-361: Downloading m3u8 information
[7plus] 7NNB23-361: Downloading MPD manifest
[7plus] 7NNB23-361: Downloading MPD manifest
[7plus] 7NNB23-361: Downloading MPD manifest
[7plus] 7NNB23-361: Downloading MPD manifest
[7plus] 7NNB23-361: Downloading JSON metadata
[info] 7NNB23-361: Downloading subtitles: en
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Searching for '(?P<meta_purl>)' in ''
[MetadataParser] Parsed meta_purl from '': ''
[MetadataParser] Video does not have a artist
[debug] Default format spec: bestvideo+bestaudio/best
[info] 7NNB23-361: Downloading 1 format(s): hls-2778+dash-4f338408-d4e9-4245-bdd3-e2f627c253dd-3
[info] Writing video subtitles to: /home/buzas/Downloads/yt-dlp/7NEWS (Brisbane)/Season NA/7NEWS： 6PM - 27 Dec 2023.en.vtt
[debug] Invoking http downloader on "[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Compatibility options: embed-metadata
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-39-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.19.0, certifi-2020.06.20, mutagen-1.47.0, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1901 extractors
[debug] Using fake IP 1.138.183.156 (AU) as X-Forwarded-For
[7plus] Extracting URL: https://7plus.com.au/seven-news-brisbane?episode-id=7NNB23-361
[7plus] 7NNB23-361: Downloading JSON metadata
[7plus] 7NNB23-361: Downloading m3u8 information
[7plus] 7NNB23-361: Downloading MPD manifest
[7plus] 7NNB23-361: Downloading MPD manifest
[7plus] 7NNB23-361: Downloading MPD manifest
[7plus] 7NNB23-361: Downloading MPD manifest
[7plus] 7NNB23-361: Downloading JSON metadata
[info] 7NNB23-361: Downloading subtitles: en
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Searching for '(?P<meta_purl>)' in ''
[MetadataParser] Parsed meta_purl from '': ''
[MetadataParser] Video does not have a artist
[debug] Default format spec: bestvideo+bestaudio/best
[info] 7NNB23-361: Downloading 1 format(s): hls-2778+dash-4f338408-d4e9-4245-bdd3-e2f627c253dd-3
[debug] Invoking http downloader on "https://7plus-sevennetwork.akamaized.net/media/v1/text/vtt/clear/5303576322001/2a44ac08-8c74-4a70-9f63-db5fb37a6c8e/62669abc-0be4-43fe-a317-512ba579c543/text.vtt?akamai_token=exp=1703685441~acl=/media/v1/text/vtt/clear/5303576322001/2a44ac08-8c74-4a70-9f63-db5fb37a6c8e/62669abc-0be4-43fe-a317-512ba579c543/text.vtt*~hmac=2a9bf7048e213cc1f1bbb7a9b3f829ff8abf5a2fe095425971040e3670b66e7a"
ERROR: Unable to download video subtitles for 'en': HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4052, in urlopen
    return self._request_director.send(req)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4217, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3109, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 364, in real_download
    establish_connection()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4074, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2922, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3176, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4225, in _write_subtitles
    raise DownloadError(msg)
yt_dlp.utils.DownloadError: Unable to download video subtitles for 'en': HTTP Error 403: Forbidden
"
ERROR: Unable to download video subtitles for 'en': HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4052, in urlopen
    return self._request_director.send(req)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4217, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3109, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 364, in real_download
    establish_connection()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4074, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2922, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3176, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4225, in _write_subtitles
    raise DownloadError(msg)
yt_dlp.utils.DownloadError: Unable to download video subtitles for 'en': HTTP Error 403: Forbidden
```

**Comment by SimonEast** [comment]
I was just attempting to download a video with subs from Vimeo (not 7plus) and also received this same error - with a 403 on the subs. Without subs the download works fine. Not quite sure why, but will keep troubleshooting.

UPDATE:
It seems that in my case yt-dlp is attempting to download the VTT sub file from:
`https://vimeo.com/texttrack/VIDEO_ID_HERE.vtt?token=...`
when my browser successfully gets it from here:
`https://player.vimeo.com/texttrack/VIDEO_ID_HERE.vtt?token=...`

So for some reason the wrong domain is being used.

**Comment by SimonEast** [comment]
I ended up posting a separate issue as it's for Vimeo not 7plus, see https://github.com/yt-dlp/yt-dlp/issues/12198

(Although I still wonder if the root cause is similar: that the subtitle request is hitting a Cloudflare CAPTCHA page.)

**Comment by Ronnnny** [comment]
I just came across the same problem https://7plus.com.au/home-and-away?episode-id=HAAW37-222 or https://7plus.com.au/home-and-away?episode-id=HAAW38-001
the https://7plus-sevennetwork.akamaized.net/media/v1/text/vtt/clear subs gives a 403 error but there's also a https://manifest.prod.boltdns.net/manifest/v1/hls/v5/clear url that works. 

"yt-dlp.exe" -J "https://7plus.com.au/home-and-away?episode-id=HAAW37-222">dump.json

```json
"subtitles": {
    "en": [
        {
            "ext": "vtt",
            "protocol": "m3u8_native",
            "url": "https://manifest.prod.boltdns.net/manifest/v1/hls/v5/clear/5303576322001/75f6d2cb-0087-42ae-92df-45a8f79e2b13/e988a719-ed8a-4e36-8136-b3e922d811ad/rendition.m3u8?behavior_id=08d37089-cebf-467f-8142-0e4ea602544a&fastly_token=Njg3ZWUyNzdfNzAxNDBkYzIxZTJmNjFkMDU0ZTM0ZDYwZDQ3YjAxMDQ0N2U5OTc1ZWNmYjRjMGI3ZmJkMTViZWFlZWI1YzQwOA%3D%3D"
        },
        {
            "ext": "vtt",
            "filesize": null,
            "manifest_url": "https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/clear/5303576322001/75f6d2cb-0087-42ae-92df-45a8f79e2b13/2s/manifest.mpd?behavior_id=08d37089-cebf-467f-8142-0e4ea602544a&fastly_token=Njg3ZWUwODhfZTEyNWFjYTUwYjY3OGViZjMzZjU3ZGIwZGUyYmJiMmZhMzUyMDVhMDFhZmEzZWM5YWNjOTUzZTE2ZTE2OGQzNA%3D%3D&appId=7plus&deviceType=web&platformType=web&videoType=vod&accountId=5303576322001&optinAdTracking=0&hl=en&referenceId=HAAW37-222&pp=csai-web&cmsId=2466102&rule=",
            "url": "https://7plus.cdn.7vodcloud.io/media/v1/dash/live/clear/5303576322001/75f6d2cb-0087-42ae-92df-45a8f79e2b13/e988a719-ed8a-4e36-8136-b3e922d811ad.vtt?Key-Pair-Id=APKAINLZLPQXMZG2IC5A&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly83cGx1cy5jZG4uN3ZvZGNsb3VkLmlvL21lZGlhL3YxL2Rhc2gvbGl2ZS9jbGVhci81MzAzNTc2MzIyMDAxLzc1ZjZkMmNiLTAwODctNDJhZS05MmRmLTQ1YThmNzllMmIxMyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTMxNDU5NzV9fX1dfQ__&Signature=IA7EnzRnNyEdbIrx0x-UXfgQjVbTpfOSDbG7qtG4rNlXNogljcY-ZWvayDoNvm5Vk7e7BhHqn5gkSxksVlTYhiGcQqLnnifr2riMOXvqCXst1nTDtwgBjBNt1goc86u9ZJClK5Hb6UUFsuGV9Mb-gfccXD75hN275lfWPZFAq66m2MQxkZ-tGxFAon6y3qNDjoL2welP8vmanKBWwkeHfveGw2YL1HqThrC2UbxaU2Zsj6QLW665s-S2bd7Hrn5vdQj0zV2j4H5IGUhzise9AejYeqayxUAiomj68~oWY9AgilVxJrDvu7imno~gTOsvFoMh9EuBzUdyTXSpEwe9vA__"
        },
        {
            "ext": "vtt",
            "url": "https://7plus-sevennetwork.akamaized.net/media/v1/text/vtt/clear/5303576322001/75f6d2cb-0087-42ae-92df-45a8f79e2b13/e988a719-ed8a-4e36-8136-b3e922d811ad/text.vtt?akamai_token=exp=1752652076~acl=/media/v1/text/vtt/clear/5303576322001/75f6d2cb-0087-42ae-92df-45a8f79e2b13/e988a719-ed8a-4e36-8136-b3e922d811ad/text.vtt*~hmac=dd0989603a71404876d7536e7cd18b650584f7a1be944bed0b986bfe14688a52"
        }
    ]
},

**Comment by JaxonPlays** [comment]
bump

**Comment by dirkf** [comment]
Akamai has its own web bouncer ("Your name's not on the list ..."), IIRC.

I suppose writing the info-json, manually removing the Akamai formats, and then re-running with the new info-json loaded would be a work-around.

The extractor could check the subtitle URLs and skip any that give 403, but that might be transient. Also, the subtitles are generated by the `BrightcoveNewIE`, so maybe that would be a better place.

Finally, the `--check-formats` option isn't respected for subtitles, unlike thumbnails, but it could be, perhaps by modifying `process_subtitles()`:
```diff
--- old/yt-dlp/yt_dlp/YoutubeDL.py
+++ new/yt-dlp/yt_dlp/YoutubeDL.py
@@ -3125,6 +3125,24 @@
 
         formats_query = self.params.get('subtitlesformat', 'best')
         formats_preference = formats_query.split('/') if formats_query else []
+
+        # like thumbnails ...
+        def check_subtitles(subtitles):
+            for t in subtitles:
+                t_id = t.get('name') or 'unknown'
+                self.to_screen(f'[info] Testing subtitle {t_id}')
+                try:
+                    self.urlopen(HEADRequest(t['url']))
+                except network_exceptions as err:
+                    self.to_screen(f'[info] Unable to connect to thumbnail {t_id} URL {t["url"]!r} - {err}. Skipping...')
+                    continue
+            yield t
+
+        def maybe_checked(subtitles):
+            if self.params.get('check_formats') is not True:
+                return subtitles
+            return LazyList(check_subtitles(subtitles[::-1]), reverse=True)
+
         subs = {}
         for lang in requested_langs:
             formats = available_subs.get(lang)
@@ -44,16 +62,19 @@
                 continue
             for ext in formats_preference:
                 if ext == 'best':
-                    f = formats[-1]
-                    break
-                matches = list(filter(lambda f: f['ext'] == ext, formats))
+                    matches = maybe_checked(formats)
+                else:
+                    matches = maybe_checked(list(filter(lambda f: f['ext'] == ext, formats)))
                 if matches:
                     f = matches[-1]
                     break
             else:
-                f = formats[-1]
+                formats = maybe_checked(formats)
                 self.report_warning(
                     'No subtitle format found matching "{}" for language {}, '
                     'using {}. Use --list-subs for a list of available subtitles'.format(formats_query, lang, f['ext']))
+                if not formats:
+                    continue
+                f = formats[-1]
             subs[lang] = f
         return subs
```
