### ISSUE TITLE
some telewebion links cant be downloaded

### ISSUE THREAD

**Issue by rezad1393** [yt-dlp/yt-dlp#8902]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

some of the links cant be downloaded.
like:
https://telewebion.com/episode/0x29b6585
they give caused by <HTTPError 598: status code 598> errors.

and some other links https://telewebion.com/episode/0x53f5629
 give these error:
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (1/3)...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp_linux https://telewebion.com/episode/0x29b6585 -vU
[debug] Command-line config: ['https://telewebion.com/episode/0x29b6585', '-vU']
[debug] User config "/home/me/.config/yt-dlp/config": ['--write-subs', '--embed-subs', '--embed-thumbnail']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.12.31.232713 from yt-dlp/yt-dlp-nightly-builds [85a2d07c1] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-6.6.8-arch1-1-x86_64-with-glibc2.38 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1 (setts), ffprobe 6.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.31.232713 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.31.232713 from yt-dlp/yt-dlp-nightly-builds)
[Telewebion] Extracting URL: https://telewebion.com/episode/0x29b6585
[Telewebion] 0x29b6585: Downloading GraphQL JSON metadata
[Telewebion] 0x29b6585: Downloading m3u8 information
ERROR: [Telewebion] 0x29b6585: Failed to download m3u8 information: HTTP Error 598: status code 598 (caused by <HTTPError 598: status code 598>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 718, in extract
  File "yt_dlp/extractor/telewebion.py", line 114, in _real_extract
  File "yt_dlp/utils/traversal.py", line 232, in traverse_obj
  File "yt_dlp/utils/traversal.py", line 220, in _traverse_obj
  File "yt_dlp/utils/traversal.py", line 208, in apply_path
  File "yt_dlp/utils/traversal.py", line 153, in apply_key
  File "yt_dlp/utils/traversal.py", line 153, in <dictcomp>
  File "yt_dlp/utils/traversal.py", line 152, in <genexpr>
  File "yt_dlp/utils/traversal.py", line 220, in _traverse_obj
  File "yt_dlp/utils/traversal.py", line 208, in apply_path
  File "yt_dlp/utils/traversal.py", line 110, in apply_key
  File "yt_dlp/utils/_utils.py", line 2606, in try_call
  File "yt_dlp/extractor/common.py", line 1946, in _extract_m3u8_formats
  File "yt_dlp/extractor/common.py", line 1968, in _extract_m3u8_formats_and_subtitles
  File "yt_dlp/extractor/common.py", line 906, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 863, in _request_webpage

  File "yt_dlp/YoutubeDL.py", line 4082, in urlopen
  File "yt_dlp/networking/common.py", line 114, in send
  File "yt_dlp/networking/_helper.py", line 204, in wrapper
  File "yt_dlp/networking/common.py", line 325, in send
  File "yt_dlp/networking/_requests.py", line 343, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 598: status code 598

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp/extractor/common.py", line 850, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4114, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 598: status code 598




./yt-dlp_linux -vU https://telewebion.com/episode/0x53f5629
[debug] Command-line config: ['-vU', 'https://telewebion.com/episode/0x53f5629']
[debug] User config "/home/me/.config/yt-dlp/config": ['--write-subs', '--embed-subs', '--embed-thumbnail']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.12.31.232713 from yt-dlp/yt-dlp-nightly-builds [85a2d07c1] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-6.6.8-arch1-1-x86_64-with-glibc2.38 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1 (setts), ffprobe 6.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.31.232713 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.31.232713 from yt-dlp/yt-dlp-nightly-builds)
[Telewebion] Extracting URL: https://telewebion.com/episode/0x53f5629
[Telewebion] 0x53f5629: Downloading GraphQL JSON metadata
[Telewebion] 0x53f5629: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 0x53f5629: Downloading 1 format(s): hls-2737
[info] There are no subtitles for the requested languages
Deleting existing file 12 دی 1401 [0x53f5629].jpg
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: 12 دی 1401 [0x53f5629].jpg
[debug] Invoking hlsnative downloader on "https://cdna-bsht1c88.telewebion.com/tv2/episode/0x53f5629/1080p/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 799
[download] Destination: 12 دی 1401 [0x53f5629].mp4
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (5/10)...
```

**Comment by dirkf** [comment]
The extractor's latest test URLs work fine.

The page that gives 598 also does that in my browser (the player container shows a "manifest error" diagnostic). The second problem page gives 598 for me, rather than the fragment 404 as shown.

598 is a non-standard return code in the server error range. It might indicate some error within the site infrastructure causing an internal network time-out.

**Comment by bashonly** [comment]
@rezad1393 can you confirm this:

>  I've checked that all provided URLs are playable in a browser with the same IP and same login details
