### ISSUE TITLE
DownloadError: ERROR: [youtube] bL6dJjxm0x0: bL6dJjxm0x0: Failed to parse JSON

### ISSUE THREAD

**Issue by abhijeetGithu** [yt-dlp/yt-dlp#8905]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

DownloadError: ERROR: [youtube] bL6dJjxm0x0: bL6dJjxm0x0: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)"));
**_while doing :_**

from langchain.document_loaders.generic import GenericLoader
from langchain.document_loaders.parsers import OpenAIWhisperParser
from langchain.document_loaders.blob_loaders.youtube_audio import YoutubeAudioLoader
url = "https://www.youtube.com/watch?v=bL6dJjxm0x0"
save_dir = "docs/youtube/"
loader = GenericLoader(
    YoutubeAudioLoader([url],save_dir),
    OpenAIWhisperParser()
)
docs = loader.load()

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
_**outputs:**_

[youtube] Extracting URL: https://www.youtube.com/watch?v=bL6dJjxm0x0
[youtube] bL6dJjxm0x0: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] bL6dJjxm0x0: Downloading ios player API JSON
[youtube] bL6dJjxm0x0: Downloading android player API JSON
WARNING: [youtube] bL6dJjxm0x0: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] bL6dJjxm0x0: Downloading iframe API JS
WARNING: [youtube] unable to extract player version; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] bL6dJjxm0x0: Downloading web player API JSON
WARNING: [youtube] bL6dJjxm0x0: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] bL6dJjxm0x0: bL6dJjxm0x0: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/yt_dlp/utils/_utils.py](https://localhost:8080/#) in decode(self, s)
    552                     return self.raw_decode(s.lstrip())[0]
--> 553                 return super().decode(s)
    554             except json.JSONDecodeError as e:

32 frames
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

ExtractorError                            Traceback (most recent call last)
ExtractorError: [youtube] bL6dJjxm0x0: bL6dJjxm0x0: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py](https://localhost:8080/#) in trouble(self, message, tb, is_error)

         else:
           exc_info = sys.exc_info()
            raise DownloadError(message, exc_info)
         self._download_retcode = 1


DownloadError: ERROR: [youtube] bL6dJjxm0x0: bL6dJjxm0x0: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Grub4K** [comment]
Are you using the latest yt-dlp version? Please include at least a **verbose** log from yt-dlp

**Comment by bashonly** [comment]
are you trying to use yt-dlp on [google colab](https://github.acom/yt-dlp/yt-dlp/issues/8594)?

**Comment by lordairivis** [comment]
also seeing this behavior on adultswim.com:

```
[debug] Command-line config: ['-vU', 'https://www.adultswim.com/videos/off-the-air/sex']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-91-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.6.1, certifi-2019.11.28, mutagen-1.45.1, pyxattr-0.6.1, requests-2.22.0, secretstorage-2.3.1, sqlite3-3.31.1, urllib3-1.25.8
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[AdultSwim] Extracting URL: https://www.adultswim.com/videos/off-the-air/sex
[AdultSwim] sex: Downloading JSON metadata
[AdultSwim] 6282ac501b15afbf2b00f53ee50a15dec07d4037: Downloading JSON metadata
ERROR: [AdultSwim] 6282ac501b15afbf2b00f53ee50a15dec07d4037: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adultswim.py", line 152, in _real_extract
    info.update(self._extract_ngtv_info(media_id, {
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/turner.py", line 221, in _extract_ngtv_info
    streams_data = self._download_json(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1072, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1042, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1032, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1019, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1002, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 553, in decode
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1016, in _parse_json
    return json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 561, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by pukkandan** [comment]
@lordairivis This thread's only for the youtube issue. Even though error message can be same across various sites, the cause and solution would be entirely different.
