### ISSUE TITLE
yt-dlp should abort on first "File name too long" error

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#8908]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Still have 2023-12-30 (don't think much will have changed since then). This possibly concerns the twitter extractor only (not certain, and difficult for me to find a possible test case on another site).

I have just started to run into this a few days ago (possibly due to a change on their end. I have a custom output template of "-o '%(title).200s-%(id)s-%(uploader)s.%(ext)s'" (that I likely need to tweak more). Anyway, if yt-dlp encounters a "File name too long" error, it should abort immediately (at least that particular download, but possibly not an entire playlist) rather than continuing to try the remaining fragments. I can't imagine any scenario where a fragment produces a "File name too long" error and a subsequent fragment doesn't. I often change to another terminal (yes, I should probably wait to make certain that the download starts successfully), only to come back much later with everything off of the screen (and even out of the scrollback buffer).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--restrict-filenames', '-o', '%(title).200s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', 'https://twitter.com/PicturesFoIder/status/1741648965970592043']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.1.53-with-glibc2.37 (OpenSSL 3.0.12 24 Oct 2023, glibc 2.37)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.19.1, requests-2.31.0, urllib3-2.1.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[twitter] Extracting URL: https://twitter.com/PicturesFoIder/status/1741648965970592043
[twitter] 1741648965970592043: Downloading guest token
[twitter] 1741648965970592043: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1741648882524954624
[twitter] 1741648965970592043: Downloading m3u8 information
[debug] Sort order given by extractor: res, proto:m3u8, br, size
[debug] Formats sorted by: hasvid, ie_pref, res, proto:m3u8(8), br, size, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1741648882524954624: Downloading 1 format(s): hls-1133
[debug] Invoking hlsnative downloader on "https://video.twimg.com/amplify_video/1741648882524954624/pl/avc1/1004x560/mp4a/128000/ilURejxq4Aek6EEZ.m3u8?container=fmp4"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 24
[download] Destination: non_aesthetic_things_-_25_yr_old_pizza_delivery_man_runs_into_burning_house_saves_four_children_who_tell_him_another_might_be_in_the_house._He_goes_back_in_finds_the_girl_jumps_out_a_window_with_her_a-1741648882524954624-non_aesthetic_things.mp4
ERROR: unable to open for writing: [Errno 36] File name too long: 'non_aesthetic_things_-_25_yr_old_pizza_delivery_man_runs_into_burning_house_saves_four_children_who_tell_him_another_might_be_in_the_house._He_goes_back_in_finds_the_girl_jumps_out_a_window_with_her_a-1741648882524954624-non_aesthetic_things.mp4.part-Frag1.part'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 592, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 1585, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: 'non_aesthetic_things_-_25_yr_old_pizza_delivery_man_runs_into_burning_house_saves_four_children_who_tell_him_another_might_be_in_the_house._He_goes_back_in_finds_the_girl_jumps_out_a_window_with_her_a-1741648882524954624-non_aesthetic_things.mp4.part-Frag1.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/http.py", line 260, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 245, in wrapper
    retry.error_callback(err, 1, 0)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 231, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 5054, in report_retry
    raise e
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 240, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 251, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 594, in sanitize_open
    stream = open(filename, open_mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: 'non_aesthetic_things_-_25_yr_old_pizza_delivery_man_runs_into_burning_house_saves_four_children_who_tell_him_another_might_be_in_the_house._He_goes_back_in_finds_the_girl_jumps_out_a_window_with_her_a-1741648882524954624-non_aesthetic_things.mp4.part-Frag1.part'

[download] fragment not found; Skipping fragment 1 ...

[...]

ERROR: unable to open for writing: [Errno 36] File name too long: 'non_aesthetic_things_-_25_yr_old_pizza_delivery_man_runs_into_burning_house_saves_four_children_who_tell_him_another_might_be_in_the_house._He_goes_back_in_finds_the_girl_jumps_out_a_window_with_her_a-1741648882524954624-non_aesthetic_things.mp4.part-Frag25.part'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 592, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 1585, in __init__
    self.f = os.fdopen(os.open(filename, flags, 0o666), mode, encoding=encoding)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: 'non_aesthetic_things_-_25_yr_old_pizza_delivery_man_runs_into_burning_house_saves_four_children_who_tell_him_another_might_be_in_the_house._He_goes_back_in_finds_the_girl_jumps_out_a_window_with_her_a-1741648882524954624-non_aesthetic_things.mp4.part-Frag25.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/http.py", line 260, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 245, in wrapper
    retry.error_callback(err, 1, 0)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 231, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 5054, in report_retry
    raise e
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 240, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 251, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 594, in sanitize_open
    stream = open(filename, open_mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: 'non_aesthetic_things_-_25_yr_old_pizza_delivery_man_runs_into_burning_house_saves_four_children_who_tell_him_another_might_be_in_the_house._He_goes_back_in_finds_the_girl_jumps_out_a_window_with_her_a-1741648882524954624-non_aesthetic_things.mp4.part-Frag25.part'

[download] fragment not found; Skipping fragment 25 ...
ERROR: The downloaded file is empty
  File "/usr/lib/python-exec/python3.11/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.11/site-packages/yt_dlp/__init__.py", line 1009, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/lib/python3.11/site-packages/yt_dlp/__init__.py", line 999, in _real_main
    return ydl.download(all_urls)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3541, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3516, in wrapper
    res = func(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1743, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1802, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2952, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3418, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3139, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/hls.py", line 375, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/fragment.py", line 527, in download_and_append_fragments
    return self._finish_frag_download(ctx, info_dict)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/fragment.py", line 301, in _finish_frag_download
    self.report_error('The downloaded file is empty')
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1054, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 982, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by jameswilsongrant** [comment]
I'll add onto this. I don't know if it should dump out but IMO if windows filenames is enabled it should clip the file length.

ex from a tiktok video (this is running in msys2 but has the same issue with the same version in powershell):

```
 43 days, 13:56:55.381658 10:03 AM ~ -> yt-dlp -U
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
 43 days, 13:56:55.381658 10:04 AM ~ -> yt-dlp https://www.tiktok.com/@sunset_gato/video/7304353312957140270
[TikTok] Extracting URL: https://www.tiktok.com/@sunset_gato/video/7304353312957140270
[TikTok] 7304353312957140270: Downloading video feed
[info] 7304353312957140270: Downloading 1 format(s): bytevc1_1080p_1011334-2
ERROR: unable to open for writing: [Errno 91] File name too long: 'Never underestimate the number of people you have made this world; if even for a moment, better in some way. Its so easy to quantify the bad, yet we so often just ignore the positive. #mentalhealthmatters #MentalHealthAwareness #mensmentalhealthmatters #mensmentalhealth #motivationalquotes #motivantionaltok #gato #furryvrchat #furry #vrchat  [7304353312957140270].mp4.part'

 43 days, 13:56:55.381658 10:04 AM ~ -> pwd
/home/user
 43 days, 13:56:55.381658 10:05 AM ~ ->
 ```

I have LongPathsEnabled turned on (https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/) though this machine is Windows 10 Home so it could be weirdness with that.

**Comment by ole-tange** [comment]
> [ryanmunz](/ryanmunz)

I second this. I get the error for every single video downloaded from Twitter.

I think a reasonable default would be:

- If we get "File name too long", do a binary search for the maximal file name length. This depends on the file system. But a binary search will find any length < 1024 in 10 file accesses. This takes less than 100 ms.
- Chop the output name to the maximal file name length.
- Fail if the chopped name would clobber an existing file.

**Comment by Grub4K** [comment]
Chopping the output name to the maximal file name length is non trivial and has yet to be solved (PRs welcome)

**Comment by dirkf** [comment]
Regarding Twitter/X, the tweet/xeet text, which is saved in the `description`, is being used as the `title` too, which means that users have to modify the default output template, either truncating the `title` field or omitting it, to avoid excessively long filenames. IMO (I've made this point before) this is an extractor bug.

Maybe TikTok has the same issue?

**Comment by ole-tange** [comment]
> Chopping the output name to the maximal file name length is non trivial and has yet to be solved (PRs welcome)

Which part? Determining the maximal file name length? Or saving to a shorter file name length?

I use this to shorten the file name length: -o '%(title).60s.%(ext)s'

Determining the maximal file name length can be as simple as:

~~~
import os
import tempfile

def can_create_file_with_length(length):
    """Check if a file with a name of the given length can be created."""
    try:
        temp_dir = "."
        file_name = "a" * length
        file_path = os.path.join(temp_dir, file_name)
        with open(file_path, 'w') as f:
            f.write("test")
        os.remove(file_path)
        return True
    except:
        return False

def find_max_filename_length():
    """Determine the maximum file name length supported by the system."""
    # Step 1: Perform exponential search to find an upper bound
    low = 1
    high = 2
    while can_create_file_with_length(high):
        low = high
        high *= 2

    # Step 2: Perform binary search between low and high bounds
    while low < high:
        mid = (low + high + 1) // 2
        if can_create_file_with_length(mid):
            low = mid  # Move the lower bound up
        else:
            high = mid - 1  # Move the upper bound down

    return low

if __name__ == "__main__":
    max_length = find_max_filename_length()
    print(f"Maximum file name length supported by the system: {max_length}")
~~

**Comment by teika-kazura** [comment]
Issue #1136 will obsolete this issue, once resolved. 

In particular see [this comment](https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-4174237246) therein. It will save the media file as `<id>.<ext>` when the filename is too long, and the intended filename will be saved in another file `<id>.target_filename`.

**Comment by donghl** [comment]
haha@Mac ~ % yt-dlp -f mp4 'https://www.facebook.com/reel/1764061407918547'
WARNING: "-f mp4" selects the best pre-merged mp4 format which is often not what's intended.
         Pre-merged mp4 formats are not available from all sites, or may only be available in lower quality.
         To prioritize the best h264 video and aac audio in an mp4 container, use "-t mp4" instead.
         If you know what you are doing and want a pre-merged mp4 format, use "-f b[ext=mp4]" instead to suppress this warning
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1764061407918547
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1764061407918547&_rdr
[facebook] 1764061407918547: Downloading webpage
[info] 1764061407918547: Downloading 1 format(s): hd
ERROR: unable to open for writing: [Errno 63] File name too long: '212M views · 9.7M reactions ｜ This 2 year old SINGER shocked EVERYONE 🥹❤️ I was playing piano in Los Angeles when Leona asked me if I could play “Let It Go” from Frozen ❄️🎹 As soon as I started playing, she noticed the microphone above her head and tried to reach it, such a cute moment🥹 After I helped her with the mic, everyone was waiting to hear her voice… and she did NOT disappoint 😳✨ Despite her young age, her voice was incredibly powerful, and she handled this difficult song very well 🎤❤️ ｜ Emilio Piano [1764061407918547].mp4.part'

**Comment by donghl** [comment]
lani@Mac ~ % yt-dlp -f mp4 'https://www.facebook.com/reel/942072022237278'
WARNING: "-f mp4" selects the best pre-merged mp4 format which is often not what's intended.
         Pre-merged mp4 formats are not available from all sites, or may only be available in lower quality.
         To prioritize the best h264 video and aac audio in an mp4 container, use "-t mp4" instead.
         If you know what you are doing and want a pre-merged mp4 format, use "-f b[ext=mp4]" instead to suppress this warning
[facebook:reel] Extracting URL: https://www.facebook.com/reel/942072022237278
[facebook] Extracting URL: https://m.facebook.com/watch/?v=942072022237278&_rdr
[facebook] 942072022237278: Downloading webpage
[info] 942072022237278: Downloading 1 format(s): hd
ERROR: unable to open for writing: [Errno 63] File name too long: '278K views · 14K reactions ｜ เสียบกุญแจค้างไว้ รถล๊อก ไม่มีความเสียหายค่ะ แต่ขออนุญาตอัดคลิปทุกกรณีนะคะ ไม่ถึว40วิรอเลย🥹🥹กุญแจหายหมดทำกุญแจใหม่!หรืองานกุญแจรถยนหายรีโมท กุญแจจักรยานยนต์หายรีโมท ตู้เซฟเปิดไม่ได้ มีช่างให้บริการตลอด 24 ชั่วโมง ทั้งในและนอกสถานที่ถ้ารับสาย ทางร้านมีรถโมบาย ออกให้บริการ ขอบคุณพี่สุดหล่อที่แนะแนวนะคะ รวดเร็ว ✅ทันใจ(ถ้ารับสาย✅งานด่วน!!!) โทร0610487600 ⧸ไลน์⧸เบอร์ งานอื่นๆงานเครื่องรับประกัน1ปี งานซ่อม งานโรงกลึงคว้านขัด เจาะ ดัดแปลงทำสี ยิงทรายแห้ง-น้ำ งานเซื่อม งานอื่นๆโทรได้เลย!!! #โรงกลึงฝน #ร้านยางใกล้ฉัน #ช่างกุญแจเขื่องใน #ร้านซ่อมรถใกล้ฉัน #ร้านยางใกล้ฉัน #ร้านกุญแจใกล้ฉัน #ทำกุญแจใหม่ #ดอกหาย #รับเปิดรถเปิดห้องเปิดบ้านกุญแจทุกชนิด #ช่างซ่อมรถ #รับเปิดรถล๊อกเองยามฉุกเฉิน #รถล๊อกเองยามฉุกเฉินเปิดได้ทุกรุ่น#ช่างกุญแจเขื่องใน #ช่างกุญแจอุบล ｜ โรงกลึงฝนเขื่องใน พรรณนิดา ถมคำ [942072022237278].mp4.part'

lani@Mac ~ % yt-dlp -f mp4 'https://www.facebook.com/reel/942072022237278'
WARNING: "-f mp4" selects the best pre-merged mp4 format which is often not what's intended.
         Pre-merged mp4 formats are not available from all sites, or may only be available in lower quality.
         To prioritize the best h264 video and aac audio in an mp4 container, use "-t mp4" instead.
         If you know what you are doing and want a pre-merged mp4 format, use "-f b[ext=mp4]" instead to suppress this warning
[facebook:reel] Extracting URL: https://www.facebook.com/reel/942072022237278
[facebook] Extracting URL: https://m.facebook.com/watch/?v=942072022237278&_rdr
[facebook] 942072022237278: Downloading webpage
[info] 942072022237278: Downloading 1 format(s): hd
ERROR: unable to open for writing: [Errno 63] File name too long: '279K views · 14K reactions ｜ เสียบกุญแจค้างไว้ รถล๊อก ไม่มีความเสียหายค่ะ แต่ขออนุญาตอัดคลิปทุกกรณีนะคะ ไม่ถึว40วิรอเลย🥹🥹กุญแจหายหมดทำกุญแจใหม่!หรืองานกุญแจรถยนหายรีโมท กุญแจจักรยานยนต์หายรีโมท ตู้เซฟเปิดไม่ได้ มีช่างให้บริการตลอด 24 ชั่วโมง ทั้งในและนอกสถานที่ถ้ารับสาย ทางร้านมีรถโมบาย ออกให้บริการ ขอบคุณพี่สุดหล่อที่แนะแนวนะคะ รวดเร็ว ✅ทันใจ(ถ้ารับสาย✅งานด่วน!!!) โทร0610487600 ⧸ไลน์⧸เบอร์ งานอื่นๆงานเครื่องรับประกัน1ปี งานซ่อม งานโรงกลึงคว้านขัด เจาะ ดัดแปลงทำสี ยิงทรายแห้ง-น้ำ งานเซื่อม งานอื่นๆโทรได้เลย!!! #โรงกลึงฝน #ร้านยางใกล้ฉัน #ช่างกุญแจเขื่องใน #ร้านซ่อมรถใกล้ฉัน #ร้านยางใกล้ฉัน #ร้านกุญแจใกล้ฉัน #ทำกุญแจใหม่ #ดอกหาย #รับเปิดรถเปิดห้องเปิดบ้านกุญแจทุกชนิด #ช่างซ่อมรถ #รับเปิดรถล๊อกเองยามฉุกเฉิน #รถล๊อกเองยามฉุกเฉินเปิดได้ทุกรุ่น#ช่างกุญแจเขื่องใน #ช่างกุญแจอุบล ｜ โรงกลึงฝนเขื่องใน พรรณนิดา ถมคำ [942072022237278].mp4.part'

lani@Mac ~ % yt-dlp -t mp4 'https://www.facebook.com/reel/942072022237278'
[facebook:reel] Extracting URL: https://www.facebook.com/reel/942072022237278
[facebook] Extracting URL: https://m.facebook.com/watch/?v=942072022237278&_rdr
[facebook] 942072022237278: Downloading webpage
[info] 942072022237278: Downloading 1 format(s): hd
ERROR: unable to open for writing: [Errno 63] File name too long: '279K views · 14K reactions ｜ เสียบกุญแจค้างไว้ รถล๊อก ไม่มีความเสียหายค่ะ แต่ขออนุญาตอัดคลิปทุกกรณีนะคะ ไม่ถึว40วิรอเลย🥹🥹กุญแจหายหมดทำกุญแจใหม่!หรืองานกุญแจรถยนหายรีโมท กุญแจจักรยานยนต์หายรีโมท ตู้เซฟเปิดไม่ได้ มีช่างให้บริการตลอด 24 ชั่วโมง ทั้งในและนอกสถานที่ถ้ารับสาย ทางร้านมีรถโมบาย ออกให้บริการ ขอบคุณพี่สุดหล่อที่แนะแนวนะคะ รวดเร็ว ✅ทันใจ(ถ้ารับสาย✅งานด่วน!!!) โทร0610487600 ⧸ไลน์⧸เบอร์ งานอื่นๆงานเครื่องรับประกัน1ปี งานซ่อม งานโรงกลึงคว้านขัด เจาะ ดัดแปลงทำสี ยิงทรายแห้ง-น้ำ งานเซื่อม งานอื่นๆโทรได้เลย!!! #โรงกลึงฝน #ร้านยางใกล้ฉัน #ช่างกุญแจเขื่องใน #ร้านซ่อมรถใกล้ฉัน #ร้านยางใกล้ฉัน #ร้านกุญแจใกล้ฉัน #ทำกุญแจใหม่ #ดอกหาย #รับเปิดรถเปิดห้องเปิดบ้านกุญแจทุกชนิด #ช่างซ่อมรถ #รับเปิดรถล๊อกเองยามฉุกเฉิน #รถล๊อกเองยามฉุกเฉินเปิดได้ทุกรุ่น#ช่างกุญแจเขื่องใน #ช่างกุญแจอุบล ｜ โรงกลึงฝนเขื่องใน พรรณนิดา ถมคำ [942072022237278].mp4.part'
