### ISSUE TITLE
Failed to parse JSON on adultswim.com

### ISSUE THREAD

**Issue by lordairivis** [yt-dlp/yt-dlp#8931]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Downloads from adultswim.com appear to be broken at the moment, receiving a "failed to parse JSON" error when attempting to download videos from the site. I am currently unable to try downloading the videos that are behind the credential wall, but the free videos do not appear to be working.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.adultswim.com/videos/off-the-air/sex']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-91-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.6.1, certifi-2019.11.28, mutagen-1.45.1, pyxattr-0.6.1, requests-2.22.0, secretstorage-2.3.1, sqlite3-3.31.1, urllib3-1.25.8
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[AdultSwim] Extracting URL: https://www.adultswim.com/videos/off-the-air/sex
[AdultSwim] sex: Downloading JSON metadata
[AdultSwim] 6282ac501b15afbf2b00f53ee50a15dec07d4037: Downloading JSON metadata
ERROR: [AdultSwim] 6282ac501b15afbf2b00f53ee50a15dec07d4037: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adultswim.py", line 152, in _real_extract
    info.update(self._extract_ngtv_info(media_id, {
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/turner.py", line 221, in _extract_ngtv_info
    streams_data = self._download_json(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1072, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1042, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1032, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1019, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1002, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 553, in decode
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1016, in _parse_json
    return json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 561, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by lordairivis** [comment]
same on nightly:
```
[debug] Command-line config: ['-vU', 'https://www.adultswim.com/videos/off-the-air/sex']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.01.14.232710 from yt-dlp/yt-dlp-nightly-builds [8e6e36517] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-91-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.6.1, certifi-2019.11.28, mutagen-1.45.1, pyxattr-0.6.1, requests-2.22.0, secretstorage-2.3.1, sqlite3-3.31.1, urllib3-1.25.8
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.01.14.232710 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.01.14.232710 from yt-dlp/yt-dlp-nightly-builds)
[AdultSwim] Extracting URL: https://www.adultswim.com/videos/off-the-air/sex
[AdultSwim] sex: Downloading JSON metadata
[AdultSwim] 6282ac501b15afbf2b00f53ee50a15dec07d4037: Downloading JSON metadata
ERROR: [AdultSwim] 6282ac501b15afbf2b00f53ee50a15dec07d4037: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adultswim.py", line 152, in _real_extract
    info.update(self._extract_ngtv_info(media_id, {
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/turner.py", line 221, in _extract_ngtv_info
    streams_data = self._download_json(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1072, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1042, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1032, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1019, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1002, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 553, in decode
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1016, in _parse_json
    return json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 561, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by lordairivis** [comment]
I updated my system from Linux Mint 20.3 to Linux Mint 21.3 and adultswim.com appears to be working again on nightly@2024.02.16.232705:
```
[debug] Command-line config: ['-vU', 'https://www.adultswim.com/videos/off-the-air/sex']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.02.16.232705 from yt-dlp/yt-dlp-nightly-builds [ddd4b5e10] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-18-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1833 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.02.16.232705 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.02.16.232705 from yt-dlp/yt-dlp-nightly-builds)
[AdultSwim] Extracting URL: https://www.adultswim.com/videos/off-the-air/sex
[AdultSwim] sex: Downloading JSON metadata
[AdultSwim] 6282ac501b15afbf2b00f53ee50a15dec07d4037: Downloading JSON metadata
[AdultSwim] 6282ac501b15afbf2b00f53ee50a15dec07d4037: Downloading XML
[AdultSwim] 6282ac501b15afbf2b00f53ee50a15dec07d4037: Downloading m3u8 information
[AdultSwim] AYxpLDNnn_kciGPPrDx5: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] AYxpLDNnn_kciGPPrDx5: Downloading 1 format(s): hls-5135
[debug] Invoking hlsnative downloader on "https://tve-vod-aka.warnermediacdn.com/adultswim/41567d63cbbdd01c33d2206c0352c280/layer7/layer7_bk.m3u8?hdntl=exp=1708230405~acl=%2fadultswim%2f41567d63cbbdd01c33d2206c0352c280%2f*~hmac=5dfaaef842dbfb8e3c5cf19afb9c00704ed334d8131bac6777008a83093e46b5"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 113
[download] Destination: Off the Air - Sex [AYxpLDNnn_kciGPPrDx5].mp4
[download] 100% of  412.75MiB in 00:01:41 at 4.07MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Off the Air - Sex [AYxpLDNnn_kciGPPrDx5].mp4'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Off the Air - Sex [AYxpLDNnn_kciGPPrDx5].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Off the Air - Sex [AYxpLDNnn_kciGPPrDx5].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Off the Air - Sex [AYxpLDNnn_kciGPPrDx5].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Off the Air - Sex [AYxpLDNnn_kciGPPrDx5].temp.mp4'
```
This was still not working on the previous nightly build, but it appears to be fixed now. Closing issue as resolved.

**Comment by bashonly** [comment]
It must've been something temporary on adultswim's end since I was able to repro back when the issue was originally posted
