### ISSUE TITLE
Please add domain animationdigitalnetwork.de to supported site ADN

### ISSUE THREAD

**Issue by Killua-Zolldyck** [yt-dlp/yt-dlp#8945]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Example URLs

https://animationdigitalnetwork.de/video/pon-no-michi/24022-folge-1-jouons-au-mah-jong

### Provide a description that is worded well enough to be understood

The French provider ADN added a portal for Germany a few weeks ago. Downloading from ADN in France using the domain animationdigitalnetwork.fr works fine, but trying to download using the German domain animationdigitalnetwork.de is switching to "generic" instead of "ADN". Unfortunately the German subs are available only while using the German domain.

I guess this could be easily fixed with just adding the domain animationdigitalnetwork.de to the provider ADN so yt-dlp is switching over to ADN and not to generic.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Extracting cookies from: "C:\Users\Heiko\AppData\Roaming\Mozilla\Firefox\Profiles\v9vnouv9.default-release\cookies.sqlite"
Extracted 325 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.01.05.232702 from yt-dlp/yt-dlp-nightly-builds [b6951271a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-113146-g56c5930ec3 (fdk,setts), ffprobe N-113146-g56c5930ec3
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.01.05.232702 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.01.05.232702 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://animationdigitalnetwork.de/video/pon-no-michi/24022-folge-1-jouons-au-mah-jong
[generic] 24022-folge-1-jouons-au-mah-jong: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 24022-folge-1-jouons-au-mah-jong: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://animationdigitalnetwork.de/video/pon-no-michi/24022-folge-1-jouons-au-mah-jong
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1722, in __extract_info
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://animationdigitalnetwork.de/video/pon-no-michi/24022-folge-1-jouons-au-mah-jong
```

**Comment by Killua-Zolldyck** [comment]
I've fixed the adn,py myself. For I'm not so cummon with Github projects yet, just let me know, if I can contribute my changes for the next release and if yes, how I can submit the changes.
