### ISSUE TITLE
[cnubis] [JW Player 8.30.0] Cannot Download Videos from https://www.documaniatv.com/

### ISSUE THREAD

**Issue by ciro314** [yt-dlp/yt-dlp#8947]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Provide a description that is worded well enough to be understood

I was able to download videos from https://www.documaniatv.com/ until mid December '23 with ease (version 2023.10.07), now running -F [website] returns 'Error 403' - tried with 2023.10.07 and with master@2024.01.05.203501 without success.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-F', 'https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.01.05.203501 from yt-dlp/yt-dlp-master-builds [b6951271a] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-6.6.9-1-default-x86_64-with-glibc2.38 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.01.05.203501 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.01.05.203501 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html
[generic] mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 718, in extract
  File "yt_dlp/extractor/generic.py", line 2392, in _real_extract
  File "yt_dlp/extractor/common.py", line 863, in _request_webpage

  File "yt_dlp/YoutubeDL.py", line 4082, in urlopen
  File "yt_dlp/networking/common.py", line 114, in send
  File "yt_dlp/networking/_helper.py", line 204, in wrapper
  File "yt_dlp/networking/common.py", line 325, in send
  File "yt_dlp/networking/_requests.py", line 343, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp/extractor/common.py", line 850, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4114, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
I get a 403 in browser too, with a page saying that the webmaster has banned my ASN

Maybe actually do this:
> I've checked that all provided URLs are playable in a browser with the same IP and same login details

**Comment by ciro314** [comment]
![2024-01-07_18-51](https://github.com/yt-dlp/yt-dlp/assets/39488425/c406d635-fd20-438b-9cf1-c1e5e5ef714f)
Hello bashonly, I can play the videos in Firefox from the same machine

**Comment by bashonly** [comment]
> then this is cloudflare anti-bot TLS fingerprinting at work.

you could try the curl_cffi PR branch:
```
python3 -m pip install --force-reinstall https://github.com/coletdjnz/yt-dlp-dev/archive/networking/curl-impersonate.tar.gz
```
then
```
python3 -m yt_dlp --impersonate chrome https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html
```

**Comment by ciro314** [comment]
Hello bashonly, it did not work unfortunately. This is the output
~~@localhost:~> python3 -m yt_dlp -vU --impersonate chrome https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html
[debug] Command-line config: ['-vU', '--impersonate', 'chrome', 'https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.6.9-1-default-x86_64-with-glibc2.38 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html
[generic] mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2392, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 863, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4108, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 334, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_curlcffi.py", line 209, in _send
    raise HTTPError(response, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 850, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4151, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

**Comment by bashonly** [comment]
hmmm

I guess you could try viewing the page source in your browser and searching for the JWPlayer ID, then pass it to yt-dlp as `yt-dlp jwplatform:JWPLAYERID`

**Comment by ciro314** [comment]
Hello bashonly, it did not work unfortunately. This is the output

[debug] Command-line config: ['jwplatform:8ca18ee8c', '-vU', '-F', 'https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.6.9-1-default-x86_64-with-glibc2.38 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[JWPlatform] Extracting URL: jwplatform:8ca18ee8c
[JWPlatform] 8ca18ee8: Downloading JSON metadata
ERROR: [JWPlatform] 8ca18ee8: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/jwplatform.py", line 89, in _real_extract
    json_data = self._download_json('https://cdn.jwplayer.com/v2/media/' + video_id, video_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1072, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1036, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 906, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 863, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4108, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 334, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 342, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 850, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4151, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found

[generic] Extracting URL: https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html
[generic] mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2392, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 863, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4108, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 334, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 342, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 850, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4151, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

**Comment by ciro314** [comment]
I get a different error now: 'No suitable extractor (JWPlatform) found'

[debug] Command-line config: ['-vU', '-F', 'https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.6.9-1-default-x86_64-with-glibc2.38 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html
[generic] mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c: Extracting information
[debug] Looking for embeds
[debug] Identified a JW Player playlist
ERROR: No suitable extractor (JWPlatform) found for URL https://www.documaniatv.com/relatedvids.php?vid=8ca18ee8c
  File "/usr/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.11/site-packages/yt_dlp/__init__.py", line 1028, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/lib/python3.11/site-packages/yt_dlp/__init__.py", line 1018, in _real_main
    return ydl.download(all_urls)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3553, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3528, in wrapper
    res = func(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1588, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1599, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1755, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1834, in process_ie_result
    return self.extract_info(
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1591, in extract_info
    self.report_error(f'No suitable extractor{format_field(ie_key, None, " (%s)")} found for URL {url}',
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1066, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 994, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dirkf** [comment]
With JS disabled in the browser, I get a CF challenge page. With JS enabled for the domain, the ludicrous web-breaking CF message "site needs to check the security of your connection" appears and then the page is displayed, with the video hosted at cnubis.com, and that is playable when its JS is enabled. However the process that generates the video link is opaque. It probably involves an algorithm that uses data only available after passing the CF challenge.

What happens if you solve the challenge in the browser and then pass the session cookies to _yt-dlp_? If no success, maybe set `--user-agent ...` to match the browser.

**Comment by ciro314** [comment]
Hello dirkf, it did not work unfortunately. This is the output:

[debug] Command-line config: ['--cookies-from-browser', 'firefox', '-vU', '-F', 'https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html']
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/ciro314/.mozilla/firefox/gzirr4i2.default-release/cookies.sqlite"
Extracted 47 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.01.05.203501 from yt-dlp/yt-dlp-master-builds [b6951271a] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-6.6.9-1-default-x86_64-with-glibc2.38 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.01.05.203501 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.01.05.203501 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://www.documaniatv.com/ciencia-y-tecnologia/mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c.html
[generic] mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] mayday-catastrofes-aereas-autorizado-para-el-desastre-video_8ca18ee8c: Extracting information
[debug] Looking for embeds
[debug] Identified a JW Player playlist
ERROR: No suitable extractor (JWPlatform) found for URL https://www.documaniatv.com/relatedvids.php?vid=8ca18ee8c
  File "yt_dlp/__main__.py", line 17, in <module>
  File "yt_dlp/__init__.py", line 1009, in main
  File "yt_dlp/__init__.py", line 999, in _real_main
  File "yt_dlp/YoutubeDL.py", line 3541, in download
  File "yt_dlp/YoutubeDL.py", line 3516, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1576, in extract_info
  File "yt_dlp/YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1743, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1822, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 1579, in extract_info
  File "yt_dlp/YoutubeDL.py", line 1054, in report_error
  File "yt_dlp/YoutubeDL.py", line 982, in trouble
