### ISSUE TITLE
[Broken] olympics.com not supported 

### ISSUE THREAD

**Issue by other-half** [yt-dlp/yt-dlp#895]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', 'https://olympics.com/tokyo-2020/en/replay/164b045b-431e-478c-8c1c-0629fe05b823/jumping-team-final']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.11.0-27-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: keyring, sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://olympics.com/tokyo-2020/en/replay/164b045b-431e-478c-8c1c-0629fe05b823/jumping-team-final
[generic] jumping-team-final: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] jumping-team-final: Downloading webpage
[generic] jumping-team-final: Extracting information
ERROR: [generic] Unsupported URL: https://olympics.com/tokyo-2020/en/replay/164b045b-431e-478c-8c1c-0629fe05b823/jumping-team-final
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://olympics.com/tokyo-2020/en/replay/164b045b-431e-478c-8c1c-0629fe05b823/jumping-team-final
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://olympics.com/tokyo-2020/en/replay/164b045b-431e-478c-8c1c-0629fe05b823/jumping-team-final

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1239, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 600, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://olympics.com/tokyo-2020/en/replay/164b045b-431e-478c-8c1c-0629fe05b823/jumping-team-final


```

## Description

I am not able to download videos from olympics.com . Could someone please suggest a way to do this ? Or will this site be also added to the supported sites soon?

**Comment by pukkandan** [comment]
I dont think it was ever supported. You should be opening a site request in that case

**Comment by other-half** [comment]
Ok, I'll go that. Thanks.
