### ISSUE TITLE
animation.filmarchives.jp

### ISSUE THREAD

**Issue by nodje** [yt-dlp/yt-dlp#8982]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single VIdeo: https://animation.filmarchives.jp/en/works/playen/41061

### Provide a description that is worded well enough to be understood

This highly rare japanese animation provider is not suported

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://animation.filmarchives.jp/en/works/playen/41061 -vU
[debug] Command-line config: ['https://animation.filmarchives.jp/en/works/playen/41061', '-vU']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.01.09.031215 from yt-dlp/yt-dlp-master-builds [95e82347b] (darwin_exe)
[debug] Python 3.12.1 (CPython arm64 64bit) - macOS-14.2.1-arm64-arm-64bit (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg 6.1-tessus (setts)
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.01.09.031215 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.01.09.031215 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://animation.filmarchives.jp/en/works/playen/41061
[generic] 41061: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 41061: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://animation.filmarchives.jp/en/works/playen/41061
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1722, in __extract_info
  File "yt_dlp/extractor/common.py", line 718, in extract
  File "yt_dlp/extractor/generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://animation.filmarchives.jp/en/works/playen/41061
```

**Comment by barsnick** [comment]
This looks like an easy task for an beginner hacker. ;-)

- The video is embedded in an iframe.
- That iframe directly contains several MPD links.
- The generic extractor handles that iframe just fine.
- All the necessary metadata is in `og:title` and `og:description`.
- Depending on choice of video (with or without English subtitles) and of site language (Japanese, English), some things are different and needs to be reflected in the `'id'`.

I'll give it a very HACKy shot.
