### ISSUE TITLE
[RÚV] Use RÚV extractor instead of generic for new (?) videos

### ISSUE THREAD

**Issue by africola** [yt-dlp/yt-dlp#8984]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

# Summary

I'm using the newest yt-dlp version, 2023.12.30. I've found that the RÚV (ruv.is) extractor does not work for some (?) new videos, notably [1]. yt-dlp falls back to the generic extractor for [1], which fails to work with a 424 HTTP error.

The video in question [1] plays fine in a browser on the same computer.

## Steps to reproduce

`$ yt-dlp 'https://spilari.nyr.ruv.is/sjonvarp/spila/svar-vid-brefi-helgu-with-english-subtitles/35763/al201h'`

## Expected result

Video gets downloaded.

## Actual result

`ERROR: [generic] Unable to download webpage: HTTP Error 424: Unknown (caused by <HTTPError 424: Unknown>)`

See below for details.

## URLs

1. https://spilari.nyr.ruv.is/sjonvarp/spila/svar-vid-brefi-helgu-with-english-subtitles/35763/al201h

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://spilari.nyr.ruv.is/sjonvarp/spila/svar-vid-brefi-helgu-with-english-subtitles/35763/al201h']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit)
[debug] exe versions: ffmpeg N-107213-gfed07efcde-20220622 (setts), ffprobe N-107213-gfed07efcde-20220622
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://spilari.nyr.ruv.is/sjonvarp/spila/svar-vid-brefi-helgu-with-english-subtitles/35763/al201h
[generic] al201h: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 424: Unknown (caused by <HTTPError 424: Unknown>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2392, in _real_extract
  File "yt_dlp\extractor\common.py", line 863, in _request_webpage

  File "yt_dlp\YoutubeDL.py", line 4082, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 343, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 424: Unknown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 850, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4114, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 424: Unknown
```

**Comment by dirkf** [comment]
The extractor has two IEs but none of the existing test URLs succeed.

If the URL pattern for `RuvSpilaIE` is tweaked, I can watch the very scenic movie from the problem URL, so the GQL extraction still works:
```diff
-    _VALID_URL = r'https?://(?:www\.)?ruv\.is/(?:(?:sjon|ut)varp|(?:krakka|ung)ruv)/spila/.+/(?P<series_id>[0-9]+)/(?P<id>[a-z0-9]+)'
+    _VALID_URL = r'https?://(?:www\.)?(?:spilari\.nyr\.)?ruv\.is/(?:(?:sjon|ut)varp|(?:krakka|ung)ruv)/spila/.+/(?P<series_id>\d+)/(?P<id>[\w-]+)'
```

Is it the case that 
(a) the first URL pattern like `http://ruv.is/sarpurinn/...` is now obsolete?
(b) URLs like `...//www.ruv.is/...varp/...` are no longer being generated?
(c) new shows have URLs like the problem URL `...//spilari.nyr.ruv/...varp/...`?
(d) if so, are the chilren's/youth programme URLs different too?

Icelandic 101 from G Translate: sjónvarp = television, utvarp = radio, nyr = new, spilari = player, krakka = child, ung = youth, sarpurinn = the sardine (?).

**Comment by barsnick** [comment]
> sarpurinn = the sardine (?)

According to [this site](https://gilli.is/projects/ruv), it's the name of the media portal.

**Comment by dirkf** [comment]
If the answers to my questions are as expected, that seems to have been replaced by spilari.nyr.ruv.

**Comment by siggijarl** [comment]
I don't think you should be using "spilari.nyr.ruv.is", it's an old url for when the website was still in development phase, it's not linked anywhere on the official ruv.is site

**Comment by dirkf** [comment]
So for (b) the answer is as follows?
* Those URLs are still valid and #8925 provides an example for testing.
* Like everything with 'new' in the name, the `nyr` URLs *were* once new but now aren't; the URL format could be supported as an alternative to the canonical www.ruv.is format.

**Comment by dirkf** [comment]
Apparently the programme page for the problem video is https://www.ruv.is/sjonvarp/spila/svar-vid-brefi-helgu-with-english-subtitles/35763/al201h but any JS requests invoked when playing the video are to spilari.nyr.ruv.is.
