### ISSUE TITLE
[YouTube] Itag 18 not loading anymore

### ISSUE THREAD

**Issue by geroale** [yt-dlp/yt-dlp#9018]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

ytdl is not able to download itag 18 any more of certain videos, like this one https://www.youtube.com/watch?v=4fk2prKnYnI. Format 18 is returned by both the API and the webpage, but the URL inside of it is not playable (even after deciphering the signature and n-sig) and returns 404. other formats are working.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['4fk2prKnYnI', '-f', '18', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 8e6e36517
[debug] Python 3.9.6 (CPython arm64 64bit) - macOS-14.0-arm64-arm-64bit (LibreSSL 2.8.3)
[debug] exe versions: rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.39.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube] Extracting URL: 4fk2prKnYnI
[youtube] 4fk2prKnYnI: Downloading webpage
https://www.youtube.com/youtubei/v1/player
b'{"context": {"client": {"clientName": "IOS", "clientVersion": "17.33.2", "deviceModel": "iPhone14,3", "userAgent": "com.google.ios.youtube/17.33.2 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)", "hl": "en", "timeZone": "UTC", "utcOffsetMinutes": 0}}, "videoId": "4fk2prKnYnI", "playbackContext": {"contentPlaybackContext": {"html5Preference": "HTML5_PREF_WANTS"}}, "contentCheckOk": true, "racyCheckOk": true}'
{'X-YouTube-Client-Name': '5', 'X-YouTube-Client-Version': '17.33.2', 'Origin': 'https://www.youtube.com', 'User-Agent': 'com.google.ios.youtube/17.33.2 (iPhone14,3; U; CPU iOS 15_6 like Mac OS X)', 'content-type': 'application/json'}
[youtube] 4fk2prKnYnI: Downloading ios player API JSON
https://www.youtube.com/youtubei/v1/player
b'{"context": {"client": {"clientName": "ANDROID", "clientVersion": "17.31.35", "androidSdkVersion": 30, "userAgent": "com.google.android.youtube/17.31.35 (Linux; U; Android 11) gzip", "hl": "en", "timeZone": "UTC", "utcOffsetMinutes": 0}}, "videoId": "4fk2prKnYnI", "params": "CgIQBg==", "playbackContext": {"contentPlaybackContext": {"html5Preference": "HTML5_PREF_WANTS"}}, "contentCheckOk": true, "racyCheckOk": true}'
{'X-YouTube-Client-Name': '3', 'X-YouTube-Client-Version': '17.31.35', 'Origin': 'https://www.youtube.com', 'User-Agent': 'com.google.android.youtube/17.31.35 (Linux; U; Android 11) gzip', 'content-type': 'application/json'}
[youtube] 4fk2prKnYnI: Downloading android player API JSON
[youtube] 4fk2prKnYnI: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] 4fk2prKnYnI: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr5---sn-hpa7knle.googlevideo.com/videoplayback?expire=1705526826&ei=yvGnZaWnL4fTi9oPleKr4Ag&ip=2a0e%3A410%3A2048%3A0%3A416b%3Ab55d%3A9b45%3Ad3ff&id=o-AJh2kpbVbNgA98xlRlPQsVlpkN9z9reEnBFiNKUVI0lz&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Kt&mm=31%2C29&mn=sn-hpa7knle%2Csn-hpa7znzy&ms=au%2Crdu&mv=m&mvi=5&pl=39&initcwndbps=1990000&spc=UWF9f3JMZNzZRe59G0lM6KK7Yit6L6O1dn8n&vprv=1&svpuc=1&xtags=heaudio%3Dtrue&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=401.658&lmt=1699467647463472&mt=1705504146&fvip=2&fexp=24007246&c=ANDROID&txp=5538434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cxtags%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAMd2Bu2oTdtWXbQgz5ow4O9ntqQJBpsL6T1vcQh7064AAiAJiQIwVeO3vHlkLZBnKzli1E0Q0VFbrjjatcJndWoGcw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIhAKJbFDCWFzSX0ucwKdU9wYjxUHq-DFLT9CobLZausJJ0AiBmFkF1Aw3VzHBVel3EzW-k6YD5FFhCMqX7LtLvkCLfmw%3D%3D"
[download] Resuming download at byte 205009
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/YoutubeDL.py", line 4082, in urlopen
    return self._request_director.send(req)
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/networking/_requests.py", line 343, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/YoutubeDL.py", line 3418, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/YoutubeDL.py", line 3139, in dl
    return fd.download(name, new_info, subtitle)
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/downloader/http.py", line 364, in real_download
    establish_connection()
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/Users/alessandrogerelli/yt-dlp/yt_dlp/YoutubeDL.py", line 4114, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found


Process finished with exit code 1
```

**Comment by bashonly** [comment]
Do you have other examples besides this link? Sometimes a format will randomly be broken on a particular video.

**Comment by geroale** [comment]
@bashonly Not yet, but many users on our platform are reporting issues of this kind, so I think they are all the same. We are trying to get more videos

**Comment by bashonly** [comment]
The OP's example URL now has a working format 18. Seems like it was a temporary issue on youtube's end
