### ISSUE TITLE
Requests handler does not follow redirects with higher level references

### ISSUE THREAD

**Issue by seproDev** [yt-dlp/yt-dlp#9020]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

`https://verycoolcourseschool.getcourse.io/pl/teach/control/lesson/view?id=319989374&editMode=0`
redirects to `https://verycoolcourseschool.getcourse.io/pl/../cms/system/login?required=true`
Which should be interpreted as  `https://verycoolcourseschool.getcourse.io/cms/system/login?required=true`
The requests handler, does not do this, resulting in a 404 instead of a 200.

Using `--compat-options prefer-legacy-http-handler` the redirect works as expected.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --no-config -v --print-traffic "https://verycoolcourseschool.getcourse.io/pl/teach/control/lesson/view?id=319989374&editMode=0"
[debug] Command-line config: ['--no-config', '-v', '--print-traffic', 'https://verycoolcourseschool.getcourse.io/pl/teach/control/lesson/view?id=319989374&editMode=0']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.01.14.232710 from yt-dlp/yt-dlp-nightly-builds [8e6e36517] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev, phantomjs 2.5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: ['C:\\Users\\User\\AppData\\Roaming\\yt-dlp\\plugins\\yt-dlp-ChromeCookieUnlock\\yt_dlp_plugins']
[debug] Loaded 1798 extractors
[generic] Extracting URL: https://verycoolcourseschool.getcourse.io/pl/teach/control/lesson/view?id=319989374&editMode=0
[generic] view?id=319989374&editMode=0: Downloading webpage
director: Handler preferences for this request: urllib=0, requests=100, websockets=0
director: Checking if "requests" supports this request.
director: Sending request via "requests"
requests: Starting new HTTPS connection (1): verycoolcourseschool.getcourse.io:443
send: b'GET /pl/teach/control/lesson/view?id=319989374&editMode=0 HTTP/1.1\r\nHost: verycoolcourseschool.getcourse.io\r\nConnection: keep-alive\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nAccept-Encoding: identity\r\n\r\n'
reply: 'HTTP/1.1 302 Found\r\n'
header: Server: nginx/1.18.0
header: Date: Thu, 18 Jan 2024 03:33:53 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: PHPSESSID5=bf0ba6b4ea744172d6a69586cc7bb801; expires=Sun, 18-Feb-2024 03:33:50 GMT; Max-Age=2678400; path=/;Priority=High; domain=verycoolcourseschool.getcourse.io; HttpOnly
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate
header: Pragma: no-cache
header: X-Frame-Options: DENY
header: Server-version: 36
header: Set-Cookie: dd_bdfhyr=fb4fdc1b8588fa6adb11b8e076d06493; expires=Fri, 19-Jan-2024 03:33:50 GMT; Max-Age=86400; path=/; secure; HttpOnly
header: Location: https://verycoolcourseschool.getcourse.io/pl/../cms/system/login?required=true
header: X-XSS-Protection: 1
send: b'GET /pl/../cms/system/login?required=true HTTP/1.1\r\nHost: verycoolcourseschool.getcourse.io\r\nConnection: keep-alive\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nAccept-Encoding: identity\r\nCookie: PHPSESSID5=bf0ba6b4ea744172d6a69586cc7bb801; dd_bdfhyr=fb4fdc1b8588fa6adb11b8e076d06493\r\n\r\n'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Server: nginx/1.18.0
header: Date: Thu, 18 Jan 2024 03:33:53 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate
header: Pragma: no-cache
header: X-Frame-Options: DENY
header: Set-Cookie: dd_bdfhyr=fb4fdc1b8588fa6adb11b8e076d06493; expires=Fri, 19-Jan-2024 03:33:52 GMT; Max-Age=86400; path=/; secure; HttpOnly
header: Server-version: 11
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2392, in _real_extract
  File "yt_dlp\extractor\common.py", line 863, in _request_webpage

  File "yt_dlp\YoutubeDL.py", line 4082, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 343, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 850, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4114, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
@coletdjnz

**Comment by coletdjnz** [comment]
This is a bug in requests, where it fails to resolve the dot segments for absolute redirect URLs.

The problematic code is located here: https://github.com/psf/requests/blob/96b22fa18c00831656ee4b286bf1c9062459b00a/src/requests/sessions.py#L214

For relative urls, which we have tests for, it does resolve dot segments. That is because in the above, `urljoin` resolves dot segments. However that only runs in requests on redirect when they are resolving the relative url. There is no such handling for absolute urls.

In this case I can add a workaround to our modified requests session to resolve dot segments regardless.

Feel free to report this to requests, though they do seem reluctant to make new changes.

Possibly related: https://github.com/psf/requests/issues/2982
