### ISSUE TITLE
Support hudl.com

### ISSUE THREAD

**Issue by stilor** [yt-dlp/yt-dlp#9022]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://fan.hudl.com/_/_/_/organization/_/_/watch?b=QnJvYWRjYXN0ODc2ODA2

### Provide a description that is worded well enough to be understood

yt-dlp does not currently support downloading from hudl.com. Most of the videos on hudl.com do not even require login/password to watch. According to https://github.com/ytdl-org/youtube-dl/issues/6562, it used to be supported by the generic extractor but not anymore.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://fan.hudl.com/_/_/_/organization/_/_/watch?b=QnJvYWRjYXN0ODc2ODA2']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.5.0-14-generic-x86_64-with-glibc2.38 (OpenSSL 3.0.10 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.42.0, urllib3-1.26.16, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://fan.hudl.com/_/_/_/organization/_/_/watch?b=QnJvYWRjYXN0ODc2ODA2
[generic] watch?b=QnJvYWRjYXN0ODc2ODA2: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] watch?b=QnJvYWRjYXN0ODc2ODA2: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://fan.hudl.com/_/_/_/organization/_/_/watch?b=QnJvYWRjYXN0ODc2ODA2
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1722, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2531, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://fan.hudl.com/_/_/_/organization/_/_/watch?b=QnJvYWRjYXN0ODc2ODA2
```

**Comment by HobbyistDev** [comment]
With OP URL, the sites seems request graphql api in `https://www.hudl.com/api/public/graphql/query` with request body like this:
```json
{
  "operationName": "Web_Fan_GetBroadcast_r1",
  "variables": {
    "broadcastId": "QnJvYWRjYXN0ODc2ODA2",
    "internalBroadcastId": null
  },
  "query": "query Web_Fan_GetBroadcast_r1($broadcastId: ID, $internalBroadcastId: String) {\n  broadcast(broadcastId: $broadcastId, internalBroadcastId: $internalBroadcastId) {\n    ...broadcastFields\n    scheduleEntrySummary {\n      ...scheduleEntrySummaryFields\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment broadcastFields on Broadcast {\n  accessPassIds\n  available\n  broadcastDateUtc\n  broadcastId\n  bsonId\n  dateModified\n  description\n  domainBlocking\n  downloadUrl\n  duration\n  embedCode\n  embedCodeSrc\n  hidden\n  id\n  internalId\n  largeThumbnail\n  liveDuration\n  mediumThumbnail\n  regionBlocking\n  requireLogin\n  scheduleEntryId\n  schoolId\n  seasonId\n  sectionId\n  sectionTitle\n  shared\n  sharedSites\n  siteId\n  siteSlug\n  siteTitle\n  smallThumbnail\n  sourceBroadcastId\n  status\n  teamId\n  timezone\n  title\n  __typename\n}\n\nfragment scheduleEntrySummaryFields on ScheduleEntryPublicSummary {\n  gameType\n  genderId\n  id\n  internalId\n  opponentDetails {\n    ...opponentDetailsFields\n    __typename\n  }\n  projectedEndTime\n  scheduleEntryId\n  scheduleEntryLocation\n  scheduleEntryOutcome\n  schoolId\n  score1\n  score2\n  seasonId\n  sportId\n  teamId\n  timeUtc\n  __typename\n}\n\nfragment opponentDetailsFields on OpponentDetails {\n  teamId\n  name\n  schoolId\n  primaryColor\n  secondaryColor\n  abbreviation\n  shortName\n  mascot\n  profileImageUri\n  __typename\n}"
}
```

Or with beautifier in `query`:
<details>

<summary>Beautified query value </summary>

```graphql
query Web_Fan_GetBroadcast_r1($broadcastId: ID, $internalBroadcastId: String) {
  broadcast(
    broadcastId: $broadcastId
    internalBroadcastId: $internalBroadcastId
  ) {
    ...broadcastFields
    scheduleEntrySummary {
      ...scheduleEntrySummaryFields
      __typename
    }
    __typename
  }
}
fragment broadcastFields on Broadcast {
  accessPassIds
  available
  broadcastDateUtc
  broadcastId
  bsonId
  dateModified
  description
  domainBlocking
  downloadUrl
  duration
  embedCode
  embedCodeSrc
  hidden
  id
  internalId
  largeThumbnail
  liveDuration
  mediumThumbnail
  regionBlocking
  requireLogin
  scheduleEntryId
  schoolId
  seasonId
  sectionId
  sectionTitle
  shared
  sharedSites
  siteId
  siteSlug
  siteTitle
  smallThumbnail
  sourceBroadcastId
  status
  teamId
  timezone
  title
  __typename
}
fragment scheduleEntrySummaryFields on ScheduleEntryPublicSummary {
  gameType
  genderId
  id
  internalId
  opponentDetails {
    ...opponentDetailsFields
    __typename
  }
  projectedEndTime
  scheduleEntryId
  scheduleEntryLocation
  scheduleEntryOutcome
  schoolId
  score1
  score2
  seasonId
  sportId
  teamId
  timeUtc
  __typename
}
fragment opponentDetailsFields on OpponentDetails {
  teamId
  name
  schoolId
  primaryColor
  secondaryColor
  abbreviation
  shortName
  mascot
  profileImageUri
  __typename
}

```
</details>

This request will send response like this:
<details>
<summary>Response json </summary>

```json
{
  "data": {
    "broadcast": {
      "accessPassIds": null,
      "available": true,
      "broadcastDateUtc": "2024-01-04T17:05:00.000Z",
      "broadcastId": "876806",
      "bsonId": "6596e5febb613b6ffa0a034d",
      "dateModified": "2024-01-04T17:12:06.000Z",
      "description": null,
      "domainBlocking": false,
      "downloadUrl": null,
      "duration": 0,
      "embedCode": "<iframe src=\"https://vcloud.blueframetech.com/broadcast/embed/876806?autoplay=0\" width=\"640\" height=\"360\" style=\"border:0;overflow:hidden;\" allow=\"fullscreen;\"></iframe>",
      "embedCodeSrc": "https://vcloud.blueframetech.com/broadcast/embed/876806?autoplay=0",
      "hidden": false,
      "id": "QnJvYWRjYXN0ODc2ODA2",
      "internalId": "876806",
      "largeThumbnail": "https://d3erbgikz6mtmj.cloudfront.net/image/23/62/72/5/2362725.png",
      "liveDuration": 0,
      "mediumThumbnail": "https://d3erbgikz6mtmj.cloudfront.net/image/23/62/72/6/2362726.png",
      "regionBlocking": false,
      "requireLogin": "no",
      "scheduleEntryId": null,
      "schoolId": "U2Nob29sMTQxNzA1",
      "seasonId": null,
      "sectionId": 4,
      "sectionTitle": "General",
      "shared": false,
      "sharedSites": null,
      "siteId": "8355",
      "siteSlug": "hudltopvideos",
      "siteTitle": "Hudl | Top Videos",
      "smallThumbnail": "https://d3erbgikz6mtmj.cloudfront.net/image/23/62/72/7/2362727.png",
      "sourceBroadcastId": "QnJvYWRjYXN0MA==",
      "status": "Archived",
      "teamId": null,
      "timezone": "America/New_York",
      "title": "Girl's Basketball Top 5 | Week 5",
      "__typename": "Broadcast",
      "scheduleEntrySummary": null
    }
  }
}
```
</details>

We could focus on `internalId` and `broadcastId`. This value can be added to `https://vcloud.blueframetech.com/file/broadcast/<broadcastId>.m3u8?hfr=1` to get the m3u8 file. 
This url can be played in `ffplay` and can be downloaded with `yt-dlp`
<details>
<summary>yt-dlp log</summary>

```shell
> python -m yt_dlp -v "https://vcloud.blueframetech.com/file/broadcast/876806.m3u8?hfr=1"
[debug] Command-line config: ['-v', 'https://vcloud.blueframetech.com/file/broadcast/876806.m3u8?hfr=1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: dc8209b6f
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: sqlite3-3.39.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[generic] Extracting URL: https://vcloud.blueframetech.com/file/broadcast/876806.m3u8?hfr=1
[generic] 876806: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[debug] Identified a M3U playlist
[generic] 876806: Downloading m3u8 information
[generic] 876806: Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 876806: Downloading 1 format(s): 4297
[debug] Invoking hlsnative downloader on "https://d3erbgikz6mtmj.cloudfront.net/video/27/25/13/8/2725138.hls/index.m3u8"

[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 7
[download] Destination: 876806 [876806].mp4
[debug] File locking is not supported. Proceeding without locking
[download]   4.3% of ~  46.68MiB at    1.13MiB/s ETA 00:27 (frag 0/7)
ERROR: Interrupted by user
```
</details>

**Comment by stilor** [comment]
Thanks! Just for my education, how do get all that info? Which tools, etc?

**Comment by HobbyistDev** [comment]
I get the info by seeing how the request made by inspecting the how the website is requesting. You can use your browser and use the network tab. In that tab, you can see what is the manifest and try to figure out how the manifest can be get.

**Comment by fvogel** [comment]
Thanks for to OP and other authors on this thread.

Here are my findings after exploring the html source of a recent video page.

Example source page: 
https://www.hudl.com/watch/video/[VideoID]/organizer 
(this page is behind a login and password)

Look for "video.ondemand.m3u8" and copy the entire URL.
https://vi.hudl.com/[TeamID]/123456/123/[hash]/video.ondemand.m3u8?v=1234567890123456

Then run the following command to download the video:
`yt-dlp --downloader ffmpeg "https://vi.hudl.com/[TEAM_ID]/123456/123/[hash]/video.ondemand.m3u8?v=1234567890123456"`
No authorization needed.

List of available formats:
`yt-dlp --list-formats "https://vi.hudl.com/[TEAM_ID]/123456/123/[hash]/video.ondemand.m3u8?v=1234567890123456"`

Use -f to download a specific format:
`yt-dlp -f [FormatID] --downloader ffmpeg ...`

Ignoring `-f` downloads the best video format.

It would be handy to be able to simply run a command to get the video downloaded, without having to find the .m3u8 link. This might be possible with `--cookies` and similar parameters with further coding. More on this when time permits.
