### ISSUE TITLE
Reddit Onion Support

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#9025]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://old.reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion/r/NatureIsFuckingLit/comments/1765bob/an_unguarded_moment_between_two_owls/

### Provide a description that is worded well enough to be understood

Reddit has an onion version of their website available - https://old.reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion

All the videos and images are also served over onion.

Please add support for the onion version of reddit.

Thank you.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] yt-dlp version nightly@2024.01.14.232710 from yt-dlp/yt-dlp-nightly-builds [8e6e36517] (py2exe)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {'all': 'socks5h://127.0.0.1:9050'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Extractor Plugins: AGB (YoutubeIE), Youtube_AgeGateBypassIE
[debug] Loaded 1799 extractors
[generic] Extracting URL: https://old.reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion/r/NatureIsFuckingLit/comments/1765bob/an_unguarded_moment_between_two_owls/
[generic] an_unguarded_moment_between_two_owls: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] an_unguarded_moment_between_two_owls: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://old.reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion/r/NatureIsFuckingLit/comments/1765bob/an_unguarded_moment_between_two_owls/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.pyc", line 1587, in wrapper
  File "yt_dlp\YoutubeDL.pyc", line 1722, in __extract_info
  File "yt_dlp\extractor\common.pyc", line 718, in extract
  File "yt_dlp\extractor\generic.pyc", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://old.reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion/r/NatureIsFuckingLit/comments/1765bob/an_unguarded_moment_between_two_owls/
```

**Comment by pukkandan** [comment]
Are you asking just for the onion URL to be detected by yt-dlp and redirected to the normal site, or for yt-dlp to make all API calls over it?

Related #3053

**Comment by barkoder** [comment]
Definitely the latter. Not just a redirect. yt-dlp should not make any requests to the clearweb version of reddit when the onion link is specified.

I already read through that thread before creating this issue when I was checking for duplicates. You mentioned [opening a separate issue for adding "full onion support"](https://github.com/yt-dlp/yt-dlp/issues/3053#issuecomment-1067015027), so I opened this one.
