### ISSUE TITLE
prefer-legacy-http-handler does not work for HTTPS proxy

### ISSUE THREAD

**Issue by meowcateatrat** [yt-dlp/yt-dlp#9065]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm getting ERROR: To use an HTTPS proxy for this request, one of the following dependencies needs to be installed: requests.

I've tried to use prefer-legacy-http-handler compat option. No luck.

The previous versions of yt-dlp (e.g. release 2023.06.21 (81ca451480051d7ce1a31c017e005358345a9149) works fine. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--proxy', 'https://127.0.0.1:10801', '-J', '--flat-playlist', '--no-warnings', '--compat-options', 'prefer-legacy-http-handler', 'https://www.youtube.com/watch?v=dn1t1Z-ECWk']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (source)
[debug] Lazy loading extractors is disabled
[debug] Compatibility options: prefer-legacy-http-handler
[debug] Git HEAD: 5f25f348f
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: certifi-2023.11.17, sqlite3-3.35.5, urllib3-2.1.0
[debug] Proxy map: {'all': 'https://127.0.0.1:10801'}
[debug] Request Handlers: urllib
[debug] Loaded 1819 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Traceback (most recent call last):
  File "D:\Work\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 4081, in urlopen
    return self._request_director.send(req)
  File "D:\Work\Source\yt-dlp\yt_dlp\networking\common.py", line 127, in send
    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported proxy type: "https" (urllib)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Work\Source\yt-dlp\yt_dlp\__init__.py", line 972, in _real_main
    if opts.update_self and updater.update() and actual_use:
  File "D:\Work\Source\yt-dlp\yt_dlp\update.py", line 434, in update
    update_info = self.query_update(_output=True)
  File "D:\Work\Source\yt-dlp\yt_dlp\update.py", line 360, in query_update
    requested_version, target_commitish = self._get_version_info(self.requested_tag)
  File "D:\Work\Source\yt-dlp\yt_dlp\update.py", line 282, in _get_version_info
    api_info = self._call_api(tag)
  File "D:\Work\Source\yt-dlp\yt_dlp\update.py", line 272, in _call_api
    return json.loads(self.ydl.urlopen(Request(url, headers={
  File "D:\Work\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 4092, in urlopen
    raise RequestError(
yt_dlp.networking.exceptions.RequestError: To use an HTTPS proxy for this request, one of the following dependencies needs to be installed: requests
[youtube] Extracting URL: https://www.youtube.com/watch?v=dn1t1Z-ECWk
[youtube] dn1t1Z-ECWk: Downloading webpage
ERROR: To use an HTTPS proxy for this request, one of the following dependencies needs to be installed: requests
Traceback (most recent call last):
  File "D:\Work\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 4081, in urlopen
    return self._request_director.send(req)
  File "D:\Work\Source\yt-dlp\yt_dlp\networking\common.py", line 127, in send
    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported proxy type: "https" (urllib)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Work\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1586, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Work\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1721, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Work\Source\yt-dlp\yt_dlp\extractor\common.py", line 718, in extract
    ie_result = self._real_extract(url)
  File "D:\Work\Source\yt-dlp\yt_dlp\extractor\youtube.py", line 4072, in _real_extract
    webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
  File "D:\Work\Source\yt-dlp\yt_dlp\extractor\youtube.py", line 4031, in _download_player_responses
    webpage = self._download_webpage(
  File "D:\Work\Source\yt-dlp\yt_dlp\extractor\common.py", line 1121, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "D:\Work\Source\yt-dlp\yt_dlp\extractor\common.py", line 1072, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "D:\Work\Source\yt-dlp\yt_dlp\extractor\common.py", line 906, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "D:\Work\Source\yt-dlp\yt_dlp\extractor\common.py", line 850, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "D:\Work\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 4092, in urlopen
    raise RequestError(
yt_dlp.networking.exceptions.RequestError: To use an HTTPS proxy for this request, one of the following dependencies needs to be installed: requests

null
```

**Comment by Grub4K** [comment]
You are missing the `requests` dependency, as it tells you in the error message. Make sure it is installed and accessible when running yt-dlp (perhaps when upgrading it got removed?). You seem to be running from source, so something like `python -m pip install -r requirements.txt` should fix it.

**Comment by bashonly** [comment]
> The previous versions of yt-dlp (e.g. release 2023.06.21 (https://github.com/yt-dlp/yt-dlp/commit/81ca451480051d7ce1a31c017e005358345a9149) works fine.

the previous versions didn't support https proxies at all: https://github.com/yt-dlp/yt-dlp/issues/1890#issuecomment-1162533509
