### ISSUE TITLE
[YouTube] Download fails after early segments: "Got error: 0 bytes read, X more expected. Retrying..."

### ISSUE THREAD

**Issue by jbruchon** [yt-dlp/yt-dlp#9071]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I archive about 350 YouTube channels. While the vast majority of them archive just fine (including most from [the channel in the debug output](https://www.youtube.com/@AqualungGameReviews)) there are a small number of videos (mainly on that same channel) that have started failing shortly into the download. It looks like the first segment succeeds but the next segment fails. I've pulled updated cookies from my browser to no avail. This has been going on for at least several days but possibly much longer since I can't possibly sit there and watch every archival session.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Y:\YouTube Channels\Aqualung Game Reviews>yt-dlp --playlist-end 80 --cookies Y:\cookies.txt -f "best[height<=1440]" --throttled-rate 50k --match-filter "!is_live & !live" --add-metadata --write-description --write-info-json --write-thumbnail --download-archive "Y:\ytdl_archive.txt" --write-subs --write-auto-subs --sub-lang en,en_US --convert-subs srt -ciw -o "%(title)s.%(ext)s" -v https://www.youtube.com/watch?v=l6Stn8BCIN8
[debug] Command-line config: ['--playlist-end', '80', '--cookies', 'Y:\\cookies.txt', '-f', 'best[height<=1440]', '--throttled-rate', '50k', '--match-filter', '!is_live & !live', '--add-metadata', '--write-description', '--write-info-json', '--write-thumbnail', '--download-archive', 'Y:\\ytdl_archive.txt', '--write-subs', '--write-auto-subs', '--sub-lang', 'en,en_US', '--convert-subs', 'srt', '-ciw', '-o', '%(title)s.%(ext)s', '-v', 'https://www.youtube.com/watch?v=l6Stn8BCIN8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Loading archive file 'Y:\\ytdl_archive.txt'
[youtube] Extracting URL: https://www.youtube.com/watch?v=l6Stn8BCIN8
[youtube] l6Stn8BCIN8: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[debug] [youtube] Copying __Secure-3PAPISID cookie to SAPISID cookie
[youtube] l6Stn8BCIN8: Downloading ios player API JSON
[youtube] l6Stn8BCIN8: Downloading android player API JSON
[debug] Loading youtube-nsig.cb886c6c from cache
[debug] [youtube] Decrypted nsig eYY7jA6nhfkq5jic1 => TCKV_U5pSE2PcA
[youtube] l6Stn8BCIN8: Downloading m3u8 information
[info] l6Stn8BCIN8: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] l6Stn8BCIN8: Downloading 1 format(s): 22
[info] Video description is already present
[info] Writing video subtitles to: Failure Friday (Episode 51).en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=l6Stn8BCIN8&ei=jKazZef_IP2_y_sPl7-JqAY&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1706297596&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cxoaf&signature=C12556ED8F4C9C98E9B6D6F075D104D00C9946A5.6733F2BC92D08EECE7B39122740CE94D88A7E3DC&key=yt8&kind=asr&lang=en&fmt=vtt"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Failure Friday (Episode 51).en.vtt
[download] 100% of    9.46KiB in 00:00:00 at 48.37KiB/s
[info] Video thumbnail is already present
[info] Video metadata is already present
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Failure Friday (Episode 51).en.vtt" -f srt -movflags "+faststart" "file:Failure Friday (Episode 51).en.srt"
Deleting original file Failure Friday (Episode 51).en.vtt (pass -k to keep)
[debug] Invoking http downloader on "https://rr4---sn-5uaeznyz.googlevideo.com/videoplayback?expire=1706293997&ei=jaazZfPrFOrCy_sP6pCHUA&ip=24.241.36.39&id=o-ABTaEvDUgW7c4sQ5QRq_V0ZLp0CAaU9FRRh5Ty4yOdap&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=PR&mm=31%2C26&mn=sn-5uaeznyz%2Csn-q4flrner&ms=au%2Conr&mv=m&mvi=4&pl=21&initcwndbps=948750&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=77.067&lmt=1705069674839047&mt=1706271905&fvip=2&fexp=24007246&c=ANDROID&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAPYRv_rzL6haQ48IuIXj2CgAlPJmSGOvfvWH0WqNp3BdAiEA3porAyzVvfZyTMCRuZun-l_-EmTRdtA58TSswc07CmE%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIgJLrmgvjaNws4S3V97jccdE0XGshp5Qtny3DjlldfZqMCIQD9SS6MJAES49ectptcqPPzyU-5FBOabpBFFmwtBHO5jA%3D%3D"
[download] Destination: Failure Friday (Episode 51).mp4
[download]   0.5% of   12.48MiB at    2.47MiB/s ETA 00:05[download] Got error: 74038 bytes read, 10292929 more expected. Retrying (1/10)...
[download] Got error: 0 bytes read, 10176775 more expected. Retrying (2/10)...
[download] Got error: 0 bytes read, 10451617 more expected. Retrying (3/10)...
[download] Got error: 0 bytes read, 10455282 more expected. Retrying (4/10)...
[download] Got error: 0 bytes read, 10403866 more expected. Retrying (5/10)...
[download] Got error: 0 bytes read, 10172891 more expected. Retrying (6/10)...
[download] Got error: 0 bytes read, 10132272 more expected. Retrying (7/10)...
[download] Got error: 0 bytes read, 10020809 more expected. Retrying (8/10)...
[download] Got error: 0 bytes read, 10268870 more expected. Retrying (9/10)...
[download] Got error: 0 bytes read, 10393414 more expected. Retrying (10/10)...
[download] Got error: 0 bytes read, 10160171 more expected. Giving up after 10 retries
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1009, in main
  File "yt_dlp\__init__.py", line 999, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3541, in download
  File "yt_dlp\YoutubeDL.py", line 3516, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1576, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1743, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1802, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2952, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3418, in process_info
  File "yt_dlp\YoutubeDL.py", line 3139, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\http.py", line 362, in real_download
  File "yt_dlp\utils\_utils.py", line 5046, in __iter__
  File "yt_dlp\downloader\common.py", line 401, in report_retry
  File "yt_dlp\utils\_utils.py", line 5053, in report_retry
  File "yt_dlp\downloader\common.py", line 404, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 1054, in report_error
  File "yt_dlp\YoutubeDL.py", line 982, in trouble
```

**Comment by Grub4K** [comment]
The 22 format seems to be broken, note however that `--check-formats` does pass. Try to use a different format, preferably one of the non pre-merged ones (`303+251` work for me).

PS: Instead of complaining about the 404, `requests` seems to complain about incomplete data. This behavior is different from legacy `urllib`:
<details><summary>log using <code>--compat-options prefer-legacy-http-handler</code> handler</summary>

```
[download] Destination: Failure Friday (Episode 51).mp4
[download]   0.6% of   12.48MiB at    1.28MiB/s ETA 00:09ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "yt_dlp\networking\_urllib.py", line 396, in _send
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4082, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 401, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3418, in process_info
  File "yt_dlp\YoutubeDL.py", line 3139, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\http.py", line 364, in real_download
  File "yt_dlp\downloader\http.py", line 120, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 4114, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

</details>

**Comment by bashonly** [comment]
Possibly related: #8579, #7504

**Comment by cycz** [comment]
Same question.
Example url:
1、https://www.youtube.com/watch?v=mYBylU3bGOI
2、https://www.youtube.com/watch?v=stahbbiHQCE

**Comment by kolbdog3333** [comment]
Did you try flushing your dns?

**Comment by maya-undefined** [comment]
I've had a similar issue BUT I have a resolution.

I am using a VPN service that has connections marked as being for 'p2p', 'tor', etc.  I've noticed that if I use an endpoint with one of these 'special' labels I have a higher chance of getting the error described in this issue.

If I use a VPN connection that is marked as 'normal', or even just using a different endpoint, I can get yt-dlp to succesfully download a video.

If you are not using a VPN service, it may be that too much suspicious traffic comes from  your network.
If you are using a VPN service, try a different endpoint

**Comment by holta** [comment]
Several YouTube URLs fail at a fixed number of bytes downloaded — example:

```
yt-dlp --format best https://youtu.be/ZfbiLfSczgA
```

(Stalls after downloading the same 1503232-byte .mp4.part fragment every time!)

Other examples are posted here:

- iiab/calibre-web#135

_Any suggestions?_

**Comment by pukkandan** [comment]
Dup of #8819, #3372 etc
