### ISSUE TITLE
GDCVault: Reports a login is required for a publicly accessible video.

### ISSUE THREAD

**Issue by FavoritoHJS** [yt-dlp/yt-dlp#9106]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

The following video: https://gdcvault.com/play/1020791/ "Approaching Zero Driver Overhead in OpenGL (Presented by NVIDIA)" can be played without an account, but when trying to download it, GDCVault requires login information.

This really shouldn't happen, especially since you can find the base m3u8 stream by looking at network requests and download the talk directly!

Also throws a list index out of range error which might be related?

PS: i'm not sure what updating yt-dlp to nightly could possibly help with here since GDCVault code hasn't been touched in 6 months...
tried to get it to work anyways but alas i can't figure out how to nixos well enough to get a custom derivation working so...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[hjs@nixfv:~]$ yt-dlp -vU https://gdcvault.com/play/1020791/
[debug] Command-line config: ['-vU', 'https://gdcvault.com/play/1020791/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.7.1-x86_64-with-glibc2.38 (OpenSSL 3.0.12 24 Oct 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, secretstorage-3.3.3, sqlite3-3.43.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[GDCVault] Extracting URL: https://gdcvault.com/play/1020791/
[GDCVault] 1020791: Downloading webpage
WARNING: [GDCVault] It looks like http://www.gdcvault.com/play/1020791 requires a login. Try specifying a username and password and try again.
WARNING: [GDCVault] Could not login.
ERROR: list index out of range
Traceback (most recent call last):
  File "/nix/store/2ln1n2lqjldy7v5ri79krq0xlplxrmhh-python3.11-yt-dlp-2023.12.30/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/2ln1n2lqjldy7v5ri79krq0xlplxrmhh-python3.11-yt-dlp-2023.12.30/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1722, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/nix/store/2ln1n2lqjldy7v5ri79krq0xlplxrmhh-python3.11-yt-dlp-2023.12.30/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/2ln1n2lqjldy7v5ri79krq0xlplxrmhh-python3.11-yt-dlp-2023.12.30/lib/python3.11/site-packages/yt_dlp/extractor/gdcvault.py", line 194, in _real_extract
    info = self._parse_html5_media_entries(url, start_page, video_id)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by HobbyistDev** [comment]
Not tested yet, based on OP link. It seems the link is based on `iframe` tag by `id` attribute.
From source code we can found the `iframe` tag from `div#player`
```html
<div id="player" style="height: 100%">
    <div class="left_column">
        <iframe src="https://gdcvault.blazestreaming.com/?id=22d7e08d84ed402fb8eb8e2645a0c1c3&videoid=75ad8a2e6141c8f9af0e1020791" width="600" height="400" scrolling="no" frameborder="0" marginheight="0" marginwidth="0" allowFullScreen></iframe>
    </div>
```

In `https://gdcvault.blazestreaming.com/script_VOD.js`, the `PLAYBACK_URL` (or the manifest url) defined with this js script:
```js
// JavaScript source code
const queryString = window.location.search;
const urlParams = new URLSearchParams(queryString);
var videoId = urlParams.get('id')

// const room	= urlParams.get('room')
// const day = urlParams.get('day')

console.log(videoId);
// console.log(room);

function srcSwap() {
	PLAYBACK_URL = 'https://cdn-a.blazestreaming.com/out/v1/'+videoId+'/38549d9a185b445888c6fbc2e2e792e9/50413c5b8a95441e919f0a1579606e47/index.m3u8';
}

srcSwap();

console.log(PLAYBACK_URL)
```

Substituting the `videoId` with `id` from `iframe` tag will provide `m3u8` url. This url can be processed by yt-dlp:
```shell
>python -m yt_dlp -vF "https://cdn-a.blazestreaming.com/out/v1/22d7e08d84ed402fb8eb8e2645a0c1c3/38549d9a185b445888c6fbc2e2e792e9/50413c5b8a95441e919f0a1579606e47/index.m3u8"
[debug] Command-line config: ['-vF', 'https://cdn-a.blazestreaming.com/out/v1/22d7e08d84ed402fb8eb8e2645a0c1c3/38549d9a185b445888c6fbc2e2e792e9/50413c5b8a95441e919f0a1579606e47/index.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 41b6cdb41 
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev 
[debug] Optional libraries: sqlite3-3.39.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1824 extractors 
[generic] Extracting URL: https://cdn-a.blazestreaming.com/out/v1/22d7e08d84ed402fb8eb8e2645a0c1c3/38549d9a185b445888c6fbc2e2e792e9/50413c5b8a95441e919f0a1579606e47/index.m3u8
[generic] index: Downloading webpage
[debug] Identified a direct video link 
[generic] index: Downloading m3u8 information
[generic] index: Checking m3u8 live status 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for index: 
ID   EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC      ACODEC
────────────────────────────────────────────────────────────────────────
471  mp4 1280x720    30 │ ~262.28MiB  472k m3u8  │ avc1.4D401F mp4a.40.2
1166 mp4 1920x1080   30 │ ~648.59MiB 1167k m3u8  │ avc1.4D4028 mp4a.40.2
```

**Comment by antdude** [comment]
Will this ever be fixed? :(

**Comment by bashonly** [comment]
this patch would fix it for the OP's link:

```diff
diff --git a/yt_dlp/extractor/gdcvault.py b/yt_dlp/extractor/gdcvault.py
index b4d81b2e8..e7c36d3bc 100644
--- a/yt_dlp/extractor/gdcvault.py
+++ b/yt_dlp/extractor/gdcvault.py
@@ -3,7 +3,8 @@
 from .common import InfoExtractor
 from .kaltura import KalturaIE
 from ..networking import HEADRequest, Request
-from ..utils import remove_start, smuggle_url, urlencode_postdata
+from ..utils import parse_qs, remove_start, smuggle_url, urlencode_postdata
+from ..utils.traversal import traverse_obj
 
 
 class GDCVaultIE(InfoExtractor):
@@ -118,6 +119,7 @@ class GDCVaultIE(InfoExtractor):
             'only_matching': True,
         },
     ]
+    _BLAZE_URL_TMPL = 'https://cdn-a.blazestreaming.com/out/v1/{}/38549d9a185b445888c6fbc2e2e792e9/50413c5b8a95441e919f0a1579606e47/index.m3u8'
 
     def _login(self, webpage_url, display_id):
         username, password = self._get_login_info()
@@ -168,6 +170,17 @@ def _real_extract(self, url):
                 'title': title,
             }
 
+        blaze_url = self._search_regex(
+            r'<iframe [^>]*\bsrc="(https://gdcvault\.blazestreaming\.com/[^"]+)"',
+            start_page, 'blaze url', default=None)
+        if blaze_id := traverse_obj(parse_qs(blaze_url), ('id', -1)):
+            return {
+                'id': video_id,
+                'display_id': display_id,
+                'title': remove_start(self._html_extract_title(start_page), 'GDC Vault - '),
+                'formats': self._extract_m3u8_formats(self._BLAZE_URL_TMPL.format(blaze_id), video_id),
+            }
+
         embed_url = KalturaIE._extract_url(start_page)
         if embed_url:
             embed_url = smuggle_url(embed_url, {'source_url': url})
```

**Comment by antdude** [comment]
I'd like to try this patch. What's the best way to try for me to try it under Windows and Linux?

**Comment by zakius** [comment]
just tried the patch today and seems to work fine, even if slowly

**Comment by kisuryoza** [comment]
Yes, the patch works.

**Comment by G4m4** [comment]
Hi there! Any way to make the patch into a PR? I confirm this works as well and wouldn't mind doing it myself but all credits should go to @bashonly.

**Comment by bashonly** [comment]
anyone is free to submit a pull request using my patch
