### ISSUE TITLE
M3U8 Downloading with YT-DLP by passing data as a parameter

### ISSUE THREAD

**Issue by X-Gorn** [yt-dlp/yt-dlp#9114]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i tried to send get request with data as a parameter:

```python3
import requests

x=requests.get(
  'https://livepullsm.facecast.live/live/23331_sm_9cc3wn78.m3u8?txSecret=dc703b3b5c9e353c2538de0c518358d2&txTime=65BB30AD',
  data={'systoken': '43d0a1d8176ea2df98f14547ee5dee56'})

print(x.text)
```
it return this:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-MEDIA-SEQUENCE:1706680207
#EXT-X-TARGETDURATION:3
#EXTINF:1.954,
23331_sm_9cc3wn78-1706680207.ts?txspiseq=106387013612687064120
#EXTINF:2.008,
23331_sm_9cc3wn78-1706680208.ts?txspiseq=106387013612687064120
#EXTINF:2.061,
23331_sm_9cc3wn78-1706680209.ts?txspiseq=106387013612687064120
```

taking those systoken as a params won't work, i tried this:
```python3
requests.get('https://livepullsm.facecast.live/live/23331_sm_9cc3wn78.m3u8?txSecret=dc703b3b5c9e353c2538de0c518358d2&txTime=65BB30AD&systoken=43d0a1d8176ea2df98f14547ee5dee56')
```
and it return none.

The question is:
I'm trying to download the same url on `yt-dlp` but i don't really know how do i pass the `data`. i hope you can help me to find the way to do that.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Error: [debug] Command-line config: ['-vU', 'https://livepullsm.facecast.live/live/23331_sm_9cc3wn78.m3u8?txSecret=dc703b3b5c9e353c2538de0c518358d2&txTime=65BB30AD&systoken=43d0a1d8176ea2df98f14547ee5dee56']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.9.18 (CPython x86_64 64bit) - Linux-5.15.0-1051-aws-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.40.1, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Identified a direct video link
ERROR: [generic] Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by ); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 2420, in _real_extract
    formats, subtitles = self._extract_m3u8_formats_and_subtitles(url, video_id, 'mp4', headers=headers)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1968, in _extract_m3u8_formats_and_subtitles
    res = self._download_webpage_handle(
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 906, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 863, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 4082, in urlopen
    return self._request_director.send(req)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/networking/_requests.py", line 343, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 850, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 4114, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden


Return Code: 1
PiD: 114
```

**Comment by Grub4K** [comment]
You cant. Write a dedicated extractor instead, and provide it as a [plugin](<https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#developing-plugins>)

**Comment by bashonly** [comment]
if that m3u8 is for a livestream, then it's not even possible with a dedicated extractor, since ffmpeg cannot send POST request data

**Comment by X-Gorn** [comment]
that is sad.

**Comment by X-Gorn** [comment]
hm, but it's not post request.

**Comment by bashonly** [comment]
regardless of GET vs POST, ffmpeg still cannot send the payload

**Comment by bashonly** [comment]
maybe see if it works sending the data params as the query instead?

**Comment by X-Gorn** [comment]
i see.

**Comment by X-Gorn** [comment]
no it does not, i sended as a params, but it returns none.

**Comment by X-Gorn** [comment]
well, admins of facecast maybe don't want anyone to scrape their m3u8 url, even after i found that systoken as payload works by lucky.

**Comment by eweweweeww** [comment]
hum interessante fiz uma gambirra q baixou os .ts files
