### ISSUE TITLE
[Redgifs] ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

### ISSUE THREAD

**Issue by AccaGihu** [yt-dlp/yt-dlp#9131]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Trying to download the list of videos for an user returns incomplete list and raises error 400: Bad Request

The command should return way more results as the profile has almost 1k video files.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -s -O webpage_url https://www.redgifs.com/users/lamsinka89
[debug] Command-line config: ['-vU', '-s', '-O', 'webpage_url', 'https://www.redgifs.com/users/lamsinka89']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.7.0-0-MANJARO-x86_64-with-glibc2.38 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.2, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[RedGifsUser] Extracting URL: https://www.redgifs.com/users/lamsinka89
[download] Downloading playlist: lamsinka89
[RedGifsUser] lamsinka89: Fetching temporary token
[RedGifsUser] lamsinka89: Downloading JSON metadata page 1
[RedGifsUser] lamsinka89: Downloading JSON metadata page 2
[RedGifsUser] lamsinka89: Downloading JSON metadata page 3
[RedGifsUser] lamsinka89: Downloading JSON metadata page 4
[RedGifsUser] lamsinka89: Downloading JSON metadata page 5
[RedGifsUser] lamsinka89: Downloading JSON metadata page 6
[RedGifsUser] lamsinka89: Downloading JSON metadata page 7
[RedGifsUser] lamsinka89: Downloading JSON metadata page 8
[RedGifsUser] lamsinka89: Downloading JSON metadata page 9
[RedGifsUser] lamsinka89: Downloading JSON metadata page 10
[RedGifsUser] lamsinka89: Downloading JSON metadata page 11
[RedGifsUser] lamsinka89: Downloading JSON metadata page 12
[RedGifsUser] lamsinka89: Downloading JSON metadata page 13
[RedGifsUser] lamsinka89: Downloading JSON metadata page 14
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4082, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 343, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 850, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4114, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 400: Bad Request

[RedGifsUser] Playlist lamsinka89: Downloading 391 items of 390
[download] Downloading item 1 of 391
---goes to 390 of 391 and then
[download] Downloading item 390 of 391
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] yellowishfemaletriceratops: Downloading 1 format(s): hd
https://redgifs.com/watch/yellowishfemaletriceratops
[download] Finished downloading playlist: lamsinka89
```

**Comment by bashonly** [comment]
Seems related to #7382, whose patch may no longer be valid

**Comment by SteveBoel** [comment]
Not a proper fix, but I resolved the same issue by connecting to a vpn. Downloading while connected to a vpn resolved the issue. After disconnecting from the vpn, downloading returned to normal as well
