### ISSUE TITLE
tv.cctv.com  live unsupported

### ISSUE THREAD

**Issue by henry99a** [yt-dlp/yt-dlp#9185]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

china

### Example URLs

https://tv.cctv.com/live/cctv1/
https://tv.cctv.com/live/cctv2/

### Provide a description that is worded well enough to be understood

The output from the command suggests filing an issue here, so I don't think I can provide more relevant context.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\>yt-dlp.exe -vU https://tv.cctv.com/live/cctv1/
[debug] Command-line config: ['-vU', 'https://tv.cctv.com/live/cctv1/']
[debug] Portable config "D:\yt-dlp.conf": ['{downloader:', '{current_fragment:', '{index:', '5},', 'extra_state:', '{}}}']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.02.09.232659 from yt-dlp/yt-dlp-nightly-builds [882e3b753] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1833 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.02.09.232659 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.02.09.232659 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: {downloader:
ERROR: [generic] '{downloader:' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:{downloader:" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2365, in _real_extract

[generic] Extracting URL: {current_fragment:
ERROR: [generic] '{current_fragment:' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:{current_fragment:" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2365, in _real_extract

[generic] Extracting URL: {index:
ERROR: [generic] '{index:' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:{index:" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2365, in _real_extract

[generic] Extracting URL: 5},
ERROR: [generic] '5},' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:5}," ) to search YouTube
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2365, in _real_extract

[generic] Extracting URL: extra_state:
ERROR: [generic] 'extra_state:' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:extra_state:" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2365, in _real_extract

[generic] Extracting URL: {}}}
ERROR: [generic] '{}}}' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:{}}}" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2365, in _real_extract

[generic] Extracting URL: https://tv.cctv.com/live/cctv1/
[generic] cctv1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] cctv1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://tv.cctv.com/live/cctv1/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1586, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1721, in __extract_info
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tv.cctv.com/live/cctv1/
```

**Comment by bashonly** [comment]
Your configuration file in `D:\yt-dlp.conf` appears to be written in JSON or Python. Don't do that. [Config files](https://github.com/yt-dlp/yt-dlp#configuration) need to be formatted as CLI options/arguments.

Fix/remove your config and post a new verbose log please

**Comment by henry99a** [comment]
I remove config，update a new log

**Comment by pzhlkj6612** [comment]
Hi, @henry99a.

The live stream on this site appears to be encrypted. That's not AES-128 for HLS or something well-known, so I don't think yt-dlp and FFmpeg can handle it right now and in the future.

To be more detailed, the m3u8 playlist is unprotected, the audio stream is playable, but the video stream is glitching in normal video player. Their proprietary HTML5 player can play the live stream smoothly, though.

To watch those programs from CCTV, you can try to find other IPTV sources: [china chinese cctv iptv m3u m3u8 - Google Search](https://www.google.com/search?q=china+chinese+cctv+iptv+m3u+m3u8).

Ref (Chinese content):

- [申请支持央视网直播源 · Issue #442 · SeaHOH/ykdl](https://github.com/SeaHOH/ykdl/issues/442)
- [某网站视频播放花屏解密 - 『脱壳破解区』 - 吾爱破解 - LCG - LSG |安卓破解|病毒分析|www.52pojie.cn](https://www.52pojie.cn/thread-1708807-1-1.html)

---

Master M3U8 example:

https://ldncctvwbcdali.v.myalicdn.com/ldncctvwbcd/cdrmldcctv1_1/index.m3u8?b=200-2100

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1800000,RESOLUTION=1280x720
/ldncctvwbcd/cdrmldcctv1_1td.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1350000,RESOLUTION=1024x576
/ldncctvwbcd/cdrmldcctv1_1ud.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=900000,RESOLUTION=854x480
/ldncctvwbcd/cdrmldcctv1_1hd.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=600000,RESOLUTION=640x360
/ldncctvwbcd/cdrmldcctv1_1md.m3u8

```

Media M3U8 exmaple:

https://ldncctvwbcdali.v.myalicdn.com/ldncctvwbcd/cdrmldcctv1_1td.m3u8

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:427668532
#EXT-X-TARGETDURATION:5
#EXTINF:4.200,
/ldncctvwbcd/cdrmldcctv1_1td/1710674133_427668532.ts
#EXTINF:3.880,
/ldncctvwbcd/cdrmldcctv1_1td/1710674136_427668533.ts
#EXTINF:3.920,
/ldncctvwbcd/cdrmldcctv1_1td/1710674140_427668534.ts

```

.

**Comment by bashonly** [comment]
Does it play in browser with DRM disabled?

**Comment by pzhlkj6612** [comment]
> Does it play in browser with DRM disabled?

Playable. Tested in DRM-disabled Firefox 123.0.1 on Windows 11.

Streams on that site are playable on most browsers and platforms. It's a state-controlled media.
