### ISSUE TITLE
Unable to download this specific Vimeo video

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#9187]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I'm trying to do a JSON dump for the below Vimeo video but I get an error.

https://vimeo.com/908632858/3badba3c6a

P.S: tried with VPN as well, but no luck.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-J', 'https://vimeo.com/908632858/3badba3c6a']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-79-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: none
[debug] Optional libraries: secretstorage-3.3.1, sqlite3-3.37.2
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://vimeo.com/908632858/3badba3c6a
[vimeo] 908632858: Downloading JSON metadata
[vimeo] 908632858: Downloading JSON metadata
ERROR: [vimeo] 908632858: Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by <HTTPError 406: Not Acceptable>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/vimeo.py", line 820, in _real_extract
    return self._extract_from_api(video_id, unlisted_hash)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/vimeo.py", line 751, in _extract_from_api
    video = self._download_json(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1072, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1036, in download_handle
    res = self._download_webpage_handle(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 906, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 863, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 406: Not Acceptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4082, in urlopen
    return self._request_director.send(req)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 406: Not Acceptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 850, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4114, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 406: Not Acceptable

null
```

**Comment by DmitryScaletta** [comment]
Works fine on latest nightly.
Probably it was already fixed here https://github.com/yt-dlp/yt-dlp/pull/9125

<details>

```bash
$ yt-dlp -F https://vimeo.com/908632858/3badba3c6a
[vimeo] Extracting URL: https://vimeo.com/908632858/3badba3c6a 
[vimeo] 908632858: Downloading JSON metadata 
[vimeo] 908632858: Downloading JSON metadata 
[vimeo] 908632858: Downloading JSON metadata 
[vimeo] 908632858: Downloading akfire_interconnect_quic m3u8 information 
[vimeo] 908632858: Downloading akfire_interconnect_quic m3u8 information 
[vimeo] 908632858: Downloading fastly_skyfire m3u8 information 
[vimeo] 908632858: Downloading fastly_skyfire m3u8 information 
[vimeo] 908632858: Downloading google_mediacdn m3u8 information 
[vimeo] 908632858: Downloading google_mediacdn m3u8 information 
[vimeo] 908632858: Downloading akfire_interconnect_quic MPD information 
[vimeo] 908632858: Downloading akfire_interconnect_quic MPD information 
[vimeo] 908632858: Downloading fastly_skyfire MPD information 
[vimeo] 908632858: Downloading fastly_skyfire MPD information 
[vimeo] 908632858: Downloading google_mediacdn MPD information 
[vimeo] 908632858: Downloading google_mediacdn MPD information 
[info] Available formats for 908632858: 
ID                                                   EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO 
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic_sep-audio-high-Original mp4 audio only     │                  m3u8  │ audio only        unknown             Original
hls-fastly_skyfire_sep-audio-high-Original           mp4 audio only     │                  m3u8  │ audio only        unknown             Original
hls-google_mediacdn_sep-audio-high-Original          mp4 audio only     │                  m3u8  │ audio only        unknown             Original
dash-akfire_interconnect_quic_sep-audio-e67e397c     m4a audio only     │ ~ 62.35MiB  196k dash  │ audio only        mp4a.40.2  196k 48k DASH audio, m4a_dash
dash-fastly_skyfire_sep-audio-e67e397c               m4a audio only     │ ~ 62.35MiB  196k dash  │ audio only        mp4a.40.2  196k 48k DASH audio, m4a_dash
dash-google_mediacdn_sep-audio-e67e397c              m4a audio only     │ ~ 62.35MiB  196k dash  │ audio only        mp4a.40.2  196k 48k DASH audio, m4a_dash
dash-akfire_interconnect_quic_sep-audio-106f0e41     m4a audio only     │ ~ 21.95MiB   69k dash  │ audio only        opus        69k 48k DASH audio, m4a_dash
dash-fastly_skyfire_sep-audio-106f0e41               m4a audio only     │ ~ 21.95MiB   69k dash  │ audio only        opus        69k 48k DASH audio, m4a_dash
dash-google_mediacdn_sep-audio-106f0e41              m4a audio only     │ ~ 21.95MiB   69k dash  │ audio only        opus        69k 48k DASH audio, m4a_dash
dash-akfire_interconnect_quic_sep-audio-0fcd6442     m4a audio only     │ ~ 32.45MiB  102k dash  │ audio only        opus       102k 48k DASH audio, m4a_dash
dash-fastly_skyfire_sep-audio-0fcd6442               m4a audio only     │ ~ 32.45MiB  102k dash  │ audio only        opus       102k 48k DASH audio, m4a_dash
dash-google_mediacdn_sep-audio-0fcd6442              m4a audio only     │ ~ 32.45MiB  102k dash  │ audio only        opus       102k 48k DASH audio, m4a_dash
dash-akfire_interconnect_quic-video-65eb2ea5         mp4 426x240        │ ~105.93MiB  333k dash  │ avc1.640015  333k video only          DASH video, mp4_dash
dash-akfire_interconnect_quic_sep-video-65eb2ea5     mp4 426x240        │ ~105.93MiB  333k dash  │ avc1.640015  333k video only          DASH video, mp4_dash
dash-fastly_skyfire-video-65eb2ea5                   mp4 426x240        │ ~105.93MiB  333k dash  │ avc1.640015  333k video only          DASH video, mp4_dash
dash-fastly_skyfire_sep-video-65eb2ea5               mp4 426x240        │ ~105.93MiB  333k dash  │ avc1.640015  333k video only          DASH video, mp4_dash
dash-google_mediacdn-video-65eb2ea5                  mp4 426x240        │ ~105.93MiB  333k dash  │ avc1.640015  333k video only          DASH video, mp4_dash
dash-google_mediacdn_sep-video-65eb2ea5              mp4 426x240        │ ~105.93MiB  333k dash  │ avc1.640015  333k video only          DASH video, mp4_dash
hls-akfire_interconnect_quic-234                     mp4 426x240     24 │ ~ 74.44MiB  234k m3u8  │ avc1.640015  234k video only
hls-fastly_skyfire-234                               mp4 426x240     24 │ ~ 74.44MiB  234k m3u8  │ avc1.640015  234k video only
hls-google_mediacdn-234                              mp4 426x240     24 │ ~ 74.44MiB  234k m3u8  │ avc1.640015  234k video only
hls-akfire_interconnect_quic_sep-428                 mp4 426x240     24 │ ~136.15MiB  428k m3u8  │ avc1.640015  428k video only
hls-fastly_skyfire_sep-428                           mp4 426x240     24 │ ~136.15MiB  428k m3u8  │ avc1.640015  428k video only
hls-google_mediacdn_sep-428                          mp4 426x240     24 │ ~136.15MiB  428k m3u8  │ avc1.640015  428k video only
dash-akfire_interconnect_quic-video-1da3610e         mp4 640x360        │ ~239.86MiB  754k dash  │ avc1.64001E  754k video only          DASH video, mp4_dash
dash-akfire_interconnect_quic_sep-video-1da3610e     mp4 640x360        │ ~239.86MiB  754k dash  │ avc1.64001E  754k video only          DASH video, mp4_dash
dash-fastly_skyfire-video-1da3610e                   mp4 640x360        │ ~239.86MiB  754k dash  │ avc1.64001E  754k video only          DASH video, mp4_dash
dash-fastly_skyfire_sep-video-1da3610e               mp4 640x360        │ ~239.86MiB  754k dash  │ avc1.64001E  754k video only          DASH video, mp4_dash
dash-google_mediacdn-video-1da3610e                  mp4 640x360        │ ~239.86MiB  754k dash  │ avc1.64001E  754k video only          DASH video, mp4_dash
dash-google_mediacdn_sep-video-1da3610e              mp4 640x360        │ ~239.86MiB  754k dash  │ avc1.64001E  754k video only          DASH video, mp4_dash
hls-akfire_interconnect_quic-500                     mp4 640x360     24 │ ~159.06MiB  500k m3u8  │ avc1.64001E  500k video only
hls-fastly_skyfire-500                               mp4 640x360     24 │ ~159.06MiB  500k m3u8  │ avc1.64001E  500k video only
hls-google_mediacdn-500                              mp4 640x360     24 │ ~159.06MiB  500k m3u8  │ avc1.64001E  500k video only
hls-akfire_interconnect_quic_sep-694                 mp4 640x360     24 │ ~220.77MiB  694k m3u8  │ avc1.64001E  694k video only
hls-fastly_skyfire_sep-694                           mp4 640x360     24 │ ~220.77MiB  694k m3u8  │ avc1.64001E  694k video only
hls-google_mediacdn_sep-694                          mp4 640x360     24 │ ~220.77MiB  694k m3u8  │ avc1.64001E  694k video only
dash-akfire_interconnect_quic-video-9b1ed5ea         mp4 960x540        │ ~486.40MiB 1529k dash  │ avc1.64001F 1529k video only          DASH video, mp4_dash
dash-akfire_interconnect_quic_sep-video-9b1ed5ea     mp4 960x540        │ ~486.40MiB 1529k dash  │ avc1.64001F 1529k video only          DASH video, mp4_dash
dash-fastly_skyfire-video-9b1ed5ea                   mp4 960x540        │ ~486.40MiB 1529k dash  │ avc1.64001F 1529k video only          DASH video, mp4_dash
dash-fastly_skyfire_sep-video-9b1ed5ea               mp4 960x540        │ ~486.40MiB 1529k dash  │ avc1.64001F 1529k video only          DASH video, mp4_dash
dash-google_mediacdn-video-9b1ed5ea                  mp4 960x540        │ ~486.40MiB 1529k dash  │ avc1.64001F 1529k video only          DASH video, mp4_dash
dash-google_mediacdn_sep-video-9b1ed5ea              mp4 960x540        │ ~486.40MiB 1529k dash  │ avc1.64001F 1529k video only          DASH video, mp4_dash
hls-akfire_interconnect_quic-1000                    mp4 960x540     24 │ ~318.12MiB 1000k m3u8  │ avc1.64001F 1000k video only
hls-fastly_skyfire-1000                              mp4 960x540     24 │ ~318.12MiB 1000k m3u8  │ avc1.64001F 1000k video only
hls-google_mediacdn-1000                             mp4 960x540     24 │ ~318.12MiB 1000k m3u8  │ avc1.64001F 1000k video only
hls-akfire_interconnect_quic_sep-1194                mp4 960x540     24 │ ~379.83MiB 1194k m3u8  │ avc1.64001F 1194k video only
hls-fastly_skyfire_sep-1194                          mp4 960x540     24 │ ~379.83MiB 1194k m3u8  │ avc1.64001F 1194k video only
hls-google_mediacdn_sep-1194                         mp4 960x540     24 │ ~379.83MiB 1194k m3u8  │ avc1.64001F 1194k video only
dash-akfire_interconnect_quic-video-c9bbbaf7         mp4 1280x720       │ ~741.84MiB 2332k dash  │ avc1.640020 2332k video only          DASH video, mp4_dash
dash-akfire_interconnect_quic_sep-video-c9bbbaf7     mp4 1280x720       │ ~741.84MiB 2332k dash  │ avc1.640020 2332k video only          DASH video, mp4_dash
dash-fastly_skyfire-video-c9bbbaf7                   mp4 1280x720       │ ~741.84MiB 2332k dash  │ avc1.640020 2332k video only          DASH video, mp4_dash
dash-fastly_skyfire_sep-video-c9bbbaf7               mp4 1280x720       │ ~741.84MiB 2332k dash  │ avc1.640020 2332k video only          DASH video, mp4_dash
dash-google_mediacdn-video-c9bbbaf7                  mp4 1280x720       │ ~741.84MiB 2332k dash  │ avc1.640020 2332k video only          DASH video, mp4_dash
dash-google_mediacdn_sep-video-c9bbbaf7              mp4 1280x720       │ ~741.84MiB 2332k dash  │ avc1.640020 2332k video only          DASH video, mp4_dash
hls-akfire_interconnect_quic-1599                    mp4 1280x720    24 │ ~508.67MiB 1599k m3u8  │ avc1.640020 1599k video only
hls-fastly_skyfire-1599                              mp4 1280x720    24 │ ~508.67MiB 1599k m3u8  │ avc1.640020 1599k video only
hls-google_mediacdn-1599                             mp4 1280x720    24 │ ~508.67MiB 1599k m3u8  │ avc1.640020 1599k video only
hls-akfire_interconnect_quic_sep-1793                mp4 1280x720    24 │ ~570.38MiB 1793k m3u8  │ avc1.640020 1793k video only
hls-fastly_skyfire_sep-1793                          mp4 1280x720    24 │ ~570.38MiB 1793k m3u8  │ avc1.640020 1793k video only
hls-google_mediacdn_sep-1793                         mp4 1280x720    24 │ ~570.38MiB 1793k m3u8  │ avc1.640020 1793k video only
```

</details>
