### ISSUE TITLE
why converter video quality hls --ppa "-c:v libx264 -preset medium -vf "scale='min(640,iw)':'min(360,ih)'" -c:a copy" ERROR: Postprocessing: Error opening output files: Filter not found

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#9205]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

why if use `--ppa "-c:v libx264 -preset medium -vf "scale='min(640,iw)':'min(360,ih)'" -c:a copy"` `ERROR: Postprocessing: Error opening output files: Filter not found`
cmd Windows?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Looks like it could be a quoting issue. Share a verbose log

**Comment by candrapersada** [comment]
```
[debug] Command-line config: ['--no-part', '--restrict-filenames', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36', '--referer', 'https://embtaku.pro/streaming.php?id=MjIwMzk1&title=Bakugan+Battle+Brawlers%3A+New+Vestroia+Episode+41&typesub=SUB', 'https://www105.vipanicdn.net/streamhls/387b84ee96d4728732a45e9a73c412e8/ep.41.1707852271.480.m3u8', '-N', '10', '--postprocessor-args', "ffmpeg:-c:v libx264 -preset medium -crf 26 -vf scale='min(640,iw)':'min(360,ih)' -c:a copy", '--retries', 'infinite', '--fragment-retries', 'infinite', '--output', '%(title)s.%(ext)s', '--ignore-config', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-113445-ge0da916b8f-20240128 (setts), ffprobe N-113445-ge0da916b8f-20240128
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[generic] Extracting URL: https://www105.vipanicdn.net/streamhls/387b84ee96d4728732a45e9a73c412e8/ep.41.1707852271.480.m3u8
[generic] ep.41.1707852271.480: Downloading webpage
[debug] Identified a direct video link
[generic] ep.41.1707852271.480: Downloading m3u8 information
[generic] ep.41.1707852271.480: Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ep.41.1707852271.480: Downloading 1 format(s): 0
[debug] Invoking hlsnative downloader on "https://www105.vipanicdn.net/streamhls/387b84ee96d4728732a45e9a73c412e8/ep.41.1707852271.480.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 363
[download] Destination: ep.41.1707852271.480.mp4
[debug] File locking is not supported. Proceeding without locking
[download]   1.9% of ~ 139.96MiB at  123.64KiB/s ETA 18:58 (frag 7/363)[download] Got error: HTTPSConnectionPool(host='www105.vipanicdn.net', port=443): Read timed out. (read timeout=20.0). Retrying (1/inf)...
[download]   2.2% of ~ 180.34MiB at  161.30KiB/s ETA 17:18 (frag 9/363)[download] Got error: HTTPSConnectionPool(host='www105.vipanicdn.net', port=443): Read timed out.. Retrying (1/inf)...
[download]   3.4% of ~ 206.60MiB at  195.54KiB/s ETA 17:55 (frag 13/363)[download] Got error: HTTPSConnectionPool(host='www105.vipanicdn.net', port=443): Read timed out.. Retrying (1/inf)...
[download]   7.6% of ~ 144.56MiB at  163.73KiB/s ETA 14:58 (frag 28/363)[download] Got error: HTTPSConnectionPool(host='www105.vipanicdn.net', port=443): Read timed out.. Retrying (2/inf)...
[download]  11.7% of ~ 124.78MiB at  161.48KiB/s ETA 10:37 (frag 44/363)[download] Got error: HTTPSConnectionPool(host='www105.vipanicdn.net', port=443): Read timed out. (read timeout=20.0). Retrying (3/inf)...
[download]  90.1% of ~ 101.53MiB at  190.77KiB/s ETA 00:54 (frag 327/363)[download] Got error: HTTPSConnectionPool(host='www105.vipanicdn.net', port=443): Read timed out.. Retrying (1/inf)...
[download]  92.0% of ~ 105.96MiB at  165.17KiB/s ETA 00:48 (frag 336/363)[download] Got error: HTTPSConnectionPool(host='www105.vipanicdn.net', port=443): Read timed out.. Retrying (2/inf)...
[download]  97.9% of ~ 106.41MiB at  118.84KiB/s ETA 00:16 (frag 358/363)[download] Got error: HTTPSConnectionPool(host='www105.vipanicdn.net', port=443): Read timed out.. Retrying (3/inf)...
[download] 100% of  105.39MiB in 00:09:30 at 189.09KiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:ep.41.1707852271.480.mp4"
[debug] ffmpeg command line: ffprobe -show_streams "file:ep.41.1707852271.480.mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "ep.41.1707852271.480.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:ep.41.1707852271.480.mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "-c:v" libx264 -preset medium -crf 26 -vf "scale=min(640,iw):min(360,ih)" "-c:a" copy "file:ep.41.1707852271.480.temp.mp4"
[debug] ffmpeg version N-113445-ge0da916b8f-20240128 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20240128
  libavutil      58. 36.101 / 58. 36.101
  libavcodec     60. 38.100 / 60. 38.100
  libavformat    60. 20.100 / 60. 20.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 17.100 /  9. 17.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
  libpostproc    57.  4.100 / 57.  4.100
Input #0, mpegts, from 'file:ep.41.1707852271.480.mp4':
  Duration: 00:24:36.63, start: 1.445400, bitrate: 598 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 854x480 [SAR 1:1 DAR 427:240], 29.97 fps, 29.97 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 65 kb/s
Multiple -codec/-c/-acodec/-vcodec/-scodec/-dcodec options specified for stream 0, only the last option '-codec:v libx264' will be used.
[AVFilterGraph @ 000001ef82179280] No such filter: 'iw):min(360'
[vost#0:0/libx264 @ 000001efffe660c0] Error initializing a simple filtergraph
Error opening output file file:ep.41.1707852271.480.temp.mp4.
Error opening output files: Filter not found

ERROR: Postprocessing: Error opening output files: Filter not found
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3495, in process_info
  File "yt_dlp\YoutubeDL.py", line 3675, in post_process
  File "yt_dlp\YoutubeDL.py", line 3657, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3635, in run_pp
  File "yt_dlp\postprocessor\common.py", line 23, in run
  File "yt_dlp\postprocessor\common.py", line 128, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 904, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 863, in _fixup
  File "yt_dlp\postprocessor\ffmpeg.py", line 374, in run_ffmpeg
  File "yt_dlp\postprocessor\ffmpeg.py", line 329, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 367, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error opening output files: Filter not found
```

**Comment by bashonly** [comment]
the site in the log is a piracy site
