### ISSUE TITLE
`--sponsorblock-remove all` `--force-keyframes-at-cuts` causes ValueError: Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by stdedos** [yt-dlp/yt-dlp#924]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl-mp4 9pdj4iJD08s --sponsorblock-remove all --no-download-archive --force-keyframes-at-cuts -v
[debug] Command-line config: ['--download-archive', '~/.yt-archive.txt', '--compat-options', 'filename', '--no-clean-infojson', '-S', 'ext', '9pdj4iJD08s', '--sponsorblock-remove', 'all', '--no-download-archive', '--force-keyframes-at-cuts', '-v']
...
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:'
[ModifyChapters] Re-encoding with appropriate keyframes
ERROR: Unknown format code 'f' for object of type 'str'
Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1252, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "~/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1298, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "~/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2320, in process_video_result
    self.process_info(new_info)
  File "~/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2864, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "~/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3015, in post_process
    info = self.run_pp(pp, info)
  File "~/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2964, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "~/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 83, in wrapper
    return func(self, info)
  File "~/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/modify_chapters.py", line 64, in run
    in_out_files = [remove_chapters(info['filepath'], False)]
  File "~/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/modify_chapters.py", line 62, in remove_chapters
    return file, self.remove_chapters(file, cuts, concat_opts, self._force_keyframes and not is_sub)
  File "~/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/modify_chapters.py", line 314, in remove_chapters
    in_file = self.force_keyframes(in_file, (t for r in ranges_to_cut for t in r))
  File "~/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 310, in force_keyframes
    self.run_ffmpeg(filename, keyframe_file, ['-force_key_frames', ','.join(
  File "~/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 311, in <genexpr>
    f'{t:.6f}' for t in timestamps)])
ValueError: Unknown format code 'f' for object of type 'str'
```

## Description

`--sponsorblock-remove all` `--force-keyframes-at-cuts` causes ValueError: Unknown format code 'f' for object of type 'str'

**Comment by pukkandan** [comment]
This has been fixed in https://github.com/yt-dlp/yt-dlp/commit/165efb823b3a8a6a6788cfe23e6b93dfbe150568
