### ISSUE TITLE
Support for rplay.live

### ISSUE THREAD

**Issue by blim01** [yt-dlp/yt-dlp#9240]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://rplay.live/play/64d88e33ea738d460d69831e/

https://rplay.live/play/659ed46a37f23766bdc28141/

### Provide a description that is worded well enough to be understood

Another destination for exiled Korean Twitch ASMR streamers. One annoying quirk about this site is that even for free VODs you must be subscribed to the creator's "Free" tier in order to view them; this may or may not come into play.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://rplay.live/play/64d88e33ea738d460d69831e/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.02.17.232706 from yt-dlp/yt-dlp-nightly-builds [974d44403] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-108915-g5661c8715c-20221102 (setts), ffprobe N-108915-g5661c8715c-20221102, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1833 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.02.17.232706 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.02.17.232706 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://rplay.live/play/64d88e33ea738d460d69831e/
[generic] 64d88e33ea738d460d69831e: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 64d88e33ea738d460d69831e: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://rplay.live/play/64d88e33ea738d460d69831e/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1586, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1721, in __extract_info
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://rplay.live/play/64d88e33ea738d460d69831e/
```

**Comment by c-basalt** [comment]
I was able to create a working extractor, although it is incompatible with main repo due to use of `playwright` to eval JS+WASM code. There might be a way to make PhantomJS work but don't feel it quite worth the efforts.
https://github.com/c-basalt/yt-dlp/tree/rplay

PS: The m3u8 of paid videos can still be accessed without membership, but the requests to AES key would get 403 denial.

**Comment by 15532th** [comment]
Here's the code for generating the `butter` header using nothing but PyCryptodome, which is already yt-dlp dependency.

```python
from Crypto.Util import Padding
from Cryptodome.Cipher import AES

def get_butter_token():
    KEY = 'S%M@#H#B(!@()a2@'
    SALT = 'QWI@(!WAS)Dj1AA(!@*DJ#@$@~1)P'
    ORIGIN = 'https://rplay.live'

    ts_value = int(time.time()) // 360
    iv = str(ts_value).zfill(16).encode()

    cleartext = f'{SALT}{ORIGIN}{ts_value}'
    cleartext_padded = Padding.pad(cleartext.encode(), 16)

    cipher = AES.new(KEY.encode(), AES.MODE_CBC, iv=iv)
    ciphertext = cipher.encrypt(cleartext_padded)
    return ciphertext.hex()
```

Feel free to use it, even if it's just a temporary solution to get this extractor merged into the main branch sooner.

**Comment by 15532th** [comment]
Using devtools, mostly.

WASM module can only interact with the browser api through javascript wrappers, and simple reading pretty-printed butter.js is enough to get pretty good idea of what is happening inside the .wasm module. I still had to look through decompiled assembly to get better understanding of some nuances, and I was able to take shortcuts by making assumptions and testing them by comparing output of the real module with my implementation instead of inferring things from the code.

**Comment by Qwerty-Space** [comment]
I'm interested in an extractor for this site too!
