### ISSUE TITLE
[globalnews.ca/live/national/] ERROR: Unsupported URL: https://globalnews.ca/live/national/

### ISSUE THREAD

**Issue by egg1234** [yt-dlp/yt-dlp#9266]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://globalnews.ca/live/national/

### Provide a description that is worded well enough to be understood

I use yt-dlp 2023.12.30 to sniffer [globalnews.ca/live/national/] m3u8 link but yt-dlp_linux report "ERROR: Unsupported URL: https://globalnews.ca/live/national/".
The command I used is "./yt-dlp_linux -f best -g https://globalnews.ca/live/national/".

I am sure we can use browser addon like "stream detector" to sniffer [globalnews.ca/live/national/] m3u8 link and the output link will be like "https://dai.google.com/linear/hls/pa/event/eIIBH8jkR-SWGaD5E4MesA/stream/0bb0d1a6-690f-4132-b222-e0c27ddf8a4d:TUL/variant/e12ba8ddea66bf16ce55ddae0978fbca/bandwidth/3027000.m3u8".

Could you help me solve this problem?

Thank you very much!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'best', '-g', 'https://globalnews.ca/live/national/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-5.4.0-171-generic-x86_64-with-glibc2.31 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.31)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://globalnews.ca/live/national/
[generic] national: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] national: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://globalnews.ca/live/national/
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1722, in __extract_info
  File "yt_dlp/extractor/common.py", line 718, in extract
  File "yt_dlp/extractor/generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://globalnews.ca/live/national/
```

**Comment by dirkf** [comment]
For devs:
1. find the JS object assigned to `window.gncaVideoPlayerSettings`
2. get feed URL path at `.jw.feedUrl` in this object
3. make the path a full URL using the site URL as base
4. fetch JSON from that URL (eg, https://globalnews.ca/gnca-ajax/video-entry/%7B%22id%22:%2249a91e7f-1023-430f-8d66-561055f3d0f7%22%7D)
5. extract media links from m3u8 and dash manifests specified in `sources` list
6. extract metadata from `metadata`, etc.

**Comment by dirkf** [comment]
Until someone finds inclination and time to write the necessary extractor module, for the National page that you linked you can try using the JSON URL that I quoted above.

**Comment by dirkf** [comment]
Navigate to the URL in your browser; use your skill and judgement to find the m3u8 link in the displayed JSON; access that as you prefer.
