### ISSUE TITLE
Got error: HTTP Error 403: Forbidden. Retrying fragment 8 (12/20)...

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#9275]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

the below playlist has many videos. only 5-10 videos from there are downloaded, saying continuously forbidden

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --check-formats  --retries 1000 --fragment-retries 20 --retry-sleep 120  --cookies-from-browser firefox:/mnt/tmp_ssd/firefox_tmp/default_mine/ --limit-rate 800k --write-description --download-archive archive.txt -o "%(playlist)s/%(title)s_[%(id)s].%(ext)s" https://www.youtube.com/@Tusyourdaddy/playlists  

[debug] Command-line config: ['-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.1.0-15-amd64-x86_64-with-glibc2.37 (OpenSSL 3.1.5 30 Jan 2024, glibc 2.37)
[debug] exe versions: ffmpeg 6.1.1-1 (setts), ffprobe 6.1.1-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, pyxattr-0.8.1, requests-2.31.0, sqlite3-3.45.1, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)

......
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (10/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (11/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (12/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (13/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (14/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (15/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (16/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (17/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (18/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (19/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 25 (20/20)...
[download] fragment not found; Skipping fragment 25 ...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 26 (1/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 26 (2/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 26 (3/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 26 (4/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 26 (5/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 26 (6/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 26 (7/20)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 26 (8/20)...
.....
```

**Comment by bashonly** [comment]
add back the middle section of the log. we can't see what video this problem is occurring with

**Comment by estatistics** [comment]
yt-dlp -vU  --retries 1  --cookies-from-browser firefox:/mnt/tmp_ssd/firefox_tmp/default_mine/ --limit-rate 1800k --write-description --download-archive archive.txt -o "%(playlist)s/%(title)s_[%(id)s].%(ext)s" https://www.youtube.com/@Tusyourdaddy/playlists
[debug] Command-line config: ['-vU', '--retries', '1', '--cookies-from-browser', 'firefox:/mnt/tmp_ssd/firefox_tmp/default_mine/', '--limit-rate', '1800k', '--write-description', '--download-archive', 'archive.txt', '-o', '%(playlist)s/%(title)s_[%(id)s].%(ext)s', 'https://www.youtube.com/@Tusyourdaddy/playlists']
Extracting cookies from firefox
[debug] Extracting cookies from: "/mnt/tmp_ssd/firefox_tmp/default_mine/cookies.sqlite"
Extracted 3946 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.1.0-15-amd64-x86_64-with-glibc2.37 (OpenSSL 3.1.5 30 Jan 2024, glibc 2.37)
[debug] exe versions: ffmpeg 6.1.1-1 (setts), ffprobe 6.1.1-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, pyxattr-0.8.1, requests-2.31.0, sqlite3-3.45.1, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[debug] Loading archive file 'archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@Tusyourdaddy/playlists
[youtube:tab] @Tusyourdaddy/playlists: Downloading webpage
[debug] [youtube:tab] Selected tab: 'playlists' (playlists), Requested tab: 'playlists'
[download] Downloading playlist: TUS - Playlists
[info] Writing playlist description to: TUS - Playlists/TUS - Playlists_[UC0HeHhImCBP1Hd5ZktRD7MQ].description
[youtube:tab] Playlist TUS - Playlists: Downloading 19 items of 19
 
after downloading some  files.... 
for more than 300 videos... goes like this... 

```

[download] Downloading item 54 of 69
[youtube] Extracting URL: https://www.youtube.com/watch?v=HrEFpzwVGto
[youtube] HrEFpzwVGto: Downloading webpage
[youtube] HrEFpzwVGto: Downloading ios player API JSON
[youtube] HrEFpzwVGto: Downloading android player API JSON
[youtube] HrEFpzwVGto: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] HrEFpzwVGto: Downloading 1 format(s): 248+251
[info] Writing video description to: VLOGS ⧸ INTERVIEWS ⧸ LIVE ⧸ FUNNY/Tus live kantin feat akis diksimos athens metro mall_[HrEFpzwVGto].description
[debug] Invoking http downloader on "https://rr4---sn-ixaa5n-5uid.googlevideo.com/videoplayback?expire=1708735466&ei=iufYZbjrBNrvi9oPicuBqAU&ip=2a02%3A85f%3Af01f%3A2d00%3Afeaa%3A14ff%3Afe9e%3A41b2&id=o-AJLb9tK41VfLkaY4h-lxzgoqPkk1IOPbcLhZXvOdAFDv&itag=248&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=XT&mm=31%2C29&mn=sn-ixaa5n-5uid%2Csn-nv47zn7r&ms=au%2Crdu&mv=m&mvi=4&pl=43&initcwndbps=767500&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=81059135&dur=252.385&lmt=1577591425901866&mt=1708713426&fvip=5&keepalive=yes&fexp=24007246&c=IOS&txp=1306222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgKBr-ImcFRXhczI-xsFrPOtqr4di1iZL_bf5t3AMeegECIQDZ3psRYSnhj4Tgy4zMkcQGahs5MTfaFcH_VGkzJu6zQg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRQIgKgf1X0TjRjz0rSf_bUx2baWlpUzwZgUlAnnwZ6iHX80CIQCstcQAfvz5kJvQnfDe3LaaJ66aAjomyP9oFpy_DLD3vQ%3D%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4082, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_requests.py", line 343, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3400, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3139, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 364, in real_download
    establish_connection()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4114, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

[download] Downloading item 55 of 69
[youtube] Extracting URL: https://www.youtube.com/watch?v=yF9ArFyENjA
[youtube] yF9ArFyENjA: Downloading webpage
[youtube] yF9ArFyENjA: Downloading ios player API JSON
[youtube] yF9ArFyENjA: Downloading android player API JSON
[youtube] yF9ArFyENjA: Downloading m3u8 information
[youtube] yF9ArFyENjA: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] yF9ArFyENjA: Downloading 1 format(s): 244+251
[info] Writing video description to: VLOGS ⧸ INTERVIEWS ⧸ LIVE ⧸ FUNNY/Tus - Barwoman - live στο Μαρούσι_[yF9ArFyENjA].description
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1708735467/ei/i-fYZb3jF-eli9oPs_2zEA/ip/2a02%3A85f%3Af01f%3A2d00%3Afeaa%3A14ff%3Afe9e%3A41b2/id/c85f40ac5c843630/source/youtube/requiressl/yes/xpc/EgVo2aDSNQ%3D%3D/playback_host/rr3---sn-ixaa5n-5ui6.googlevideo.com/mh/IT/mm/31%2C29/mn/sn-ixaa5n-5ui6%2Csn-nv47lns6/ms/au%2Crdu/mv/m/mvi/3/pl/43/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/863750/spc/UWF9f7Ov9v6POUBenfzz3yhRtyOLxyyCV5QdITSgfN2xvag/vprv/1/mt/1708713426/fvip/3/keepalive/yes/fexp/24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cxpc%2Chfr%2Cas%2Cspc%2Cvprv%2Citag/sig/AJfQdSswRQIhAJw8T68fTpA-tDY5BsZISXJLmNUwoYkv93P1Dhh3oyFlAiBDI8fSJyaaJfgDokuRP0SedTqwno3OYSxrrVEkWCrO1w%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/APTiJQcwRQIgNzSPH8dcB6tzka3tO2pc2s3glcEfyDUkVZeu6cX4ciUCIQDkGx2hWqhA8O4b0BIuW8M0VKcr7gv_hZ7cRvlJPj7HhQ%3D%3D"
[dashsegments] Total fragments: 13
[download] Destination: VLOGS ⧸ INTERVIEWS ⧸ LIVE ⧸ FUNNY/Tus - Barwoman - live στο Μαρούσι_[yF9ArFyENjA].f244.webm
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/bin/yt-dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 1009, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 999, in _real_main
    return ydl.download(all_urls)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3541, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3516, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1743, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1872, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2016, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, collections.ChainMap({
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2048, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1822, in process_ie_result
    return self.extract_info(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1743, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1872, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2016, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, collections.ChainMap({
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2048, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1822, in process_ie_result
    return self.extract_info(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1743, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1802, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2952, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3400, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3139, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/dash.py", line 63, in real_download
    return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 376, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 514, in download_and_append_fragments
    download_fragment(fragment, ctx)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 460, in download_fragment
    for retry in RetryManager(self.params.get('fragment_retries'), error_callback):
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5046, in __iter__
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 457, in error_callback
    self.report_retry(err, count, retries, frag_index, fatal)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 401, in report_retry
    RetryManager.report_retry(
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5053, in report_retry
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 404, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1054, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 982, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: fragment 1 not found, unable to continue
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/bin/yt-dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 1009, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 999, in _real_main
    return ydl.download(all_urls)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3541, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3516, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1743, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1872, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2016, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, collections.ChainMap({
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2048, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1822, in process_ie_result
    return self.extract_info(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1743, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1872, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2016, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, collections.ChainMap({
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2048, in __process_iterable_entry
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1822, in process_ie_result
    return self.extract_info(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1576, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1743, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1802, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2952, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3400, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3139, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/dash.py", line 63, in real_download
    return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 376, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 515, in download_and_append_fragments
    result = append_fragment(
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 480, in append_fragment
    self.report_error(f'fragment {frag_index} not found, unable to continue')
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1054, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 982, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


```

**Comment by bashonly** [comment]
looks like you are experiencing a combination of these two issues:
- https://github.com/yt-dlp/yt-dlp/issues/7860
- https://github.com/yt-dlp/yt-dlp/issues/8227

**Comment by jimlynnjulian** [comment]
Just for the record , I got this and tried a different entry from the formats list successfully.
