### ISSUE TITLE
[vimeo] ERROR: Postprocessing: Conversion failed!

### ISSUE THREAD

**Issue by t0ben** [yt-dlp/yt-dlp#9303]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

For some M4A the ffmpeg conversion seems to be not functioning. Happened several times now, with several version of ffmpeg - I used the most current git version here.

[ipod @ 0x5642d1dbbec0] Could not find tag for codec opus in stream #0, codec not currently supported in container
[out#0/ipod @ 0x5642d1db69c0] Could not write header (incorrect codec parameters ?): Invalid argument
Conversion failed!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU -f bestaudio --all-subs https://player.vimeo.com/video/910796597
[debug] Command-line config: ['-vU', '-f', 'bestaudio', '--all-subs', 'https://player.vimeo.com/video/910796597']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.6.16-2-MANJARO-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg N-113824-ga3ca4beeaa (fdk,setts), ffprobe N-113824-ga3ca4beeaa, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.02.02, requests-2.31.0, sqlite3-3.45.1, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1833 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://player.vimeo.com/video/910796597
[vimeo] 910796597: Downloading webpage
[vimeo] 910796597: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 910796597: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 910796597: Downloading fastly_skyfire m3u8 information
[vimeo] 910796597: Downloading fastly_skyfire m3u8 information
[vimeo] 910796597: Downloading google_mediacdn m3u8 information
WARNING: [vimeo] Failed to download m3u8 information: HTTP Error 404: Not Found
[vimeo] 910796597: Downloading google_mediacdn m3u8 information
WARNING: [vimeo] Failed to download m3u8 information: HTTP Error 404: Not Found
[vimeo] 910796597: Downloading akfire_interconnect_quic MPD information
[vimeo] 910796597: Downloading akfire_interconnect_quic MPD information
[vimeo] 910796597: Downloading fastly_skyfire MPD information
[vimeo] 910796597: Downloading fastly_skyfire MPD information
[vimeo] 910796597: Downloading google_mediacdn MPD information
WARNING: [vimeo] Failed to download MPD manifest: HTTP Error 404: Not Found
[vimeo] 910796597: Downloading google_mediacdn MPD information
WARNING: [vimeo] Failed to download MPD manifest: HTTP Error 404: Not Found
[info] 910796597: Downloading subtitles: de-x-autogen
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] 910796597: Downloading 1 format(s): dash-fastly_skyfire_sep-audio-fb582f80
[info] Writing video subtitles to: KITA13-W115_1_Charlotte Wirl_Geschichten für mehrere Generationen [910796597].de-x-autogen.vtt
[debug] Invoking http downloader on "https://vimeo.com/texttrack/133812354.vtt?token=65dccf49_0x1e87ce19650bd420d98e1b321cab6ba42e4b67a0"
[download] Destination: KITA13-W115_1_Charlotte Wirl_Geschichten für mehrere Generationen [910796597].de-x-autogen.vtt
[download] 100% of   92.30KiB in 00:00:00 at 251.25KiB/s
[debug] Invoking dashsegments downloader on "https://skyfire.vimeocdn.com/1708969801-0xe3a9879563de8bda0acf16003629c120976f8427/e3d171f9-be32-483a-9fc0-d27ea96bfc6c/sep/video/2fd6167c,88767700,b934e31d,c5b2bf21,f496c9ad/audio/648f29b9,a8db1c6d,fb582f80/master.mpd?base64_init=1&query_string_ranges=1"
[dashsegments] Total fragments: 779
[download] Destination: KITA13-W115_1_Charlotte Wirl_Geschichten für mehrere Generationen [910796597].m4a
[download] 100% of   56.43MiB in 00:00:29 at 1.89MiB/s
[FixupM4a] Correcting container of "KITA13-W115_1_Charlotte Wirl_Geschichten für mehrere Generationen [910796597].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:KITA13-W115_1_Charlotte Wirl_Geschichten für mehrere Generationen [910796597].m4a' -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart 'file:KITA13-W115_1_Charlotte Wirl_Geschichten für mehrere Generationen [910796597].temp.m4a'
[FixupDuplicateMoov] Fixing duplicate MOOV atoms of "KITA13-W115_1_Charlotte Wirl_Geschichten für mehrere Generationen [910796597].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:KITA13-W115_1_Charlotte Wirl_Geschichten für mehrere Generationen [910796597].m4a' -map 0 -dn -ignore_unknown -c copy -movflags +faststart 'file:KITA13-W115_1_Charlotte Wirl_Geschichten für mehrere Generationen [910796597].temp.m4a'
[debug] ffmpeg version N-113824-ga3ca4beeaa Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.1 (GCC) 20230801
  configuration: --prefix=/usr --enable-lto --cc= --cxx= --disable-rpath --enable-gpl --enable-version3 --enable-nonfree --enable-shared --disable-static --disable-stripping --disable-htmlpages --enable-gray --enable-alsa --enable-avisynth --enable-bzlib --enable-chromaprint --enable-frei0r --enable-gcrypt --enable-gmp --enable-gnutls --enable-iconv --enable-ladspa --enable-lcms2 --enable-libaom --enable-libaribb24 --enable-libaribcaption --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcelt --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libdavs2 --enable-libdc1394 --enable-libfdk-aac --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libharfbuzz --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libiec61883 --enable-libilbc --enable-libjack --enable-libjxl --enable-libklvanc --enable-libkvazaar --enable-liblensfun --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopencv --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --disable-libopenvino --enable-libopus --enable-libplacebo --enable-libpulse --enable-librabbitmq --enable-librav1e --disable-librist --enable-librsvg --enable-librubberband --enable-librtmp --enable-libshine --enable-libsmbclient --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libsvtvp9 --disable-libtensorflow --enable-libtesseract --enable-libtheora --disable-libtls --enable-libtwolame --enable-libuavs3d --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxevd --enable-libxeve --enable-libxavs --enable-libxavs2 --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxcb-shape --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-lzma --enable-decklink --disable-mbedtls --enable-libmysofa --enable-openal --enable-opencl --enable-opengl --disable-openssl --disable-pocketsphinx --enable-sndio --enable-sdl2 --enable-vapoursynth --enable-vulkan --enable-xlib --enable-zlib --enable-amf --disable-cuda-nvcc --disable-cuda-llvm --disable-cuvid --disable-ffnvcodec --enable-libdrm --disable-libmfx --disable-libnpp --disable-nvdec --disable-nvenc --enable-omx --disable-rkmpp --enable-v4l2-m2m --enable-vaapi --enable-vdpau
  libavutil      58. 39.100 / 58. 39.100
  libavcodec     60. 40.100 / 60. 40.100
  libavformat    60. 21.101 / 60. 21.101
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 17.100 /  9. 17.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
  libpostproc    57.  4.100 / 57.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:KITA13-W115_1_Charlotte Wirl_Geschichten für mehrere Generationen [910796597].m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf60.21.101
  Duration: 01:17:48.28, start: 0.000000, bitrate: 98 kb/s
  Stream #0:0[0x1](und): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 96 kb/s (default)
      Metadata:
        handler_name    : Vimeo Isopod Audio Handler
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
[ipod @ 0x5642d1dbbec0] Could not find tag for codec opus in stream #0, codec not currently supported in container
[out#0/ipod @ 0x5642d1db69c0] Could not write header (incorrect codec parameters ?): Invalid argument
Conversion failed!

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3510, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3690, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3672, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3650, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 937, in run
    self._fixup(self.MESSAGE, info['filepath'], self.stream_copy_opts())
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 865, in _fixup
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 374, in run_ffmpeg
    return self.run_ffmpeg_multiple_files([path], out_path, opts, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 329, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 367, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by bashonly** [comment]
Duplicate of #4838

The format being selected by `bestaudio` is opus encoded audio in an m4a container, which ffmpeg doesn't support.

Select a different format, try adding `--fixup never` to your command, or try a variation on [the workaround here](https://github.com/yt-dlp/yt-dlp/issues/4838#issuecomment-1463422474)

**Comment by AnnanFay** [comment]
If you find yourself here searching for an error message, and are downloading a non-Vimeo URL, check your installed ffmpeg version. Mine apparently wasn't updated since December 2014.

> Postprocessing: Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred

**Comment by lifeashansen** [comment]
Turns out I just didnt have enough space on my drive for it to merge the video and audio together
