### ISSUE TITLE
question about errors downloading from facebook

### ISSUE THREAD

**Issue by xiaose** [yt-dlp/yt-dlp#9310]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Israel

### Provide a description that is worded well enough to be understood

Previously the app functioned correctly, and was able to download videos from FB without any issues. However, I'm now experiencing problems with downloading any videos from FB. There appears to be no clear reason why the app has stopped working with such links...

```
yt-dlp.exe -v -U https://www.facebook.com/100090747447851/videos/6889771281078066
...
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
...
ERROR: [facebook] 6889771281078066: Cannot parse data
...
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.facebook.com/100090747447851/videos/6889771281078066']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[facebook] Extracting URL: https://www.facebook.com/100090747447851/videos/6889771281078066
[facebook] 6889771281078066: Downloading webpage
[facebook] 6889771281078066: Downloading webpage
ERROR: [facebook] 6889771281078066: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\facebook.py", line 795, in _real_extract
  File "yt_dlp\extractor\facebook.py", line 740, in _extract_from_url
```

**Comment by bashonly** [comment]
I can't reproduce the issue with stable or master

You could give the nightly build a try, as per the checklist instructions

**Comment by xiaose** [comment]
I download this file: https://github.com/yt-dlp/yt-dlp/releases/download/2023.12.30/yt-dlp_x86.exe

...and now have another output:
```
.\yt-dlp_x86.exe -vU https://www.facebook.com/100090747447851/videos/6889771281078066
[debug] Command-line config: ['-vU', 'https://www.facebook.com/100090747447851/videos/6889771281078066']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_x86_exe)
[debug] Python 3.8.10 (CPython AMD64 32bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[facebook] Extracting URL: https://www.facebook.com/100090747447851/videos/6889771281078066
[facebook] 6889771281078066: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 6889771281078066: Downloading 1 format(s): 735403198568037v+3683102641967049a
[debug] Invoking http downloader on "https://video.fsdv2-1.fna.fbcdn.net/v/t39.25447-2/427021963_795042025785707_3607899322795323819_n.mp4?_nc_cat=1&ccb=1-7&_nc_sid=9a5d50&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfcjJldmV2cDktcjFnZW4ydnA5X3E5MCJ9&_nc_ohc=4IU9v9-BitMAX_71VJs&_nc_oc=AQnwWbrJp0Sk_sExCbuVXew-kG94m4msy471LPHgXhiSHPjtmwCllOgerjoxMyjeFjk&_nc_ht=video.fsdv2-1.fna&oh=00_AfDti7qdRFqGn47Td-wwpg32jnASUbfxbykB15Mc5TdhaA&oe=65E37CFD"
[download] Unable to open file: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].f735403198568037v.mp4.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].f735403198568037v.mp4.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].f735403198568037v.mp4.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].f735403198568037v.mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 260, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5046, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5054, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].f735403198568037v.mp4.part'


[debug] Invoking http downloader on "https://video.fsdv2-1.fna.fbcdn.net/v/t39.43673-2/429673680_444501201240976_3049674909042852806_n.mp4?_nc_cat=109&ccb=1-7&_nc_sid=9a5d50&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfbXV0ZWRfc2hhcmVkX2F1ZGlvIn0=&_nc_ohc=dpNttxWauNEAX9GLGav&_nc_ht=video.fsdv2-1.fna&oh=00_AfCgz7rye2iqvgU2l-_-dRtublzn6j0SRYgmaSNv019Ucg&oe=65E245C4"
[download] Unable to open file: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].f3683102641967049a.m4a.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].f3683102641967049a.m4a.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].f3683102641967049a.m4a.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].f3683102641967049a.m4a.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 260, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5046, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5054, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].f3683102641967049a.m4a.part'
```

also I tried this: .\yt-dlp_x86.exe -vU https://www.facebook.com/100090747447851/videos/6889771281078066 -f 'ba*/b'
```
[debug] Command-line config: ['-vU', 'https://www.facebook.com/100090747447851/videos/6889771281078066', '-f', 'ba*/b']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_x86_exe)
[debug] Python 3.8.10 (CPython AMD64 32bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[facebook] Extracting URL: https://www.facebook.com/100090747447851/videos/6889771281078066
[facebook] 6889771281078066: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 6889771281078066: Downloading 1 format(s): sd
[debug] Invoking http downloader on "https://video.fsdv2-1.fna.fbcdn.net/v/t39.43673-2/428710796_1307063006899434_7937832650545343114_n.mp4?_nc_cat=111&ccb=1-7&_nc_sid=55d0d3&efg=eyJybHIiOjEyOTcsInJsYSI6NTEyLCJ2ZW5jb2RlX3RhZyI6Im11dGVkdjJfc3ZlX3NkIn0%3D&_nc_ohc=YYuPsG9ygGoAX9eje5s&rl=1297&vabr=721&_nc_ht=video.fsdv2-1.fna&oh=00_AfCWWw3cDDz7mbUyc-ev0CznQX1UlNcut3-_iOeOkyavJQ&oe=65E2FE21"
[download] Unable to open file: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].mp4.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].mp4.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].mp4.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 260, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5046, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5054, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: 'I LITERALLY CANNOT STILL I AM CRYING ALL OVER AGAIN💕🌊 #thelittlemermaid #jodibenson #littlemermaid #ariel #disney #dreamcometrue #emotional #husbandreaction #newhairstyle #marriedlife #husbandandwife #marriage #blacklove #braidedstyles #twinning #naeandjay #reelsinstagram #momlife ｜ Shayna Brenae ｜ Halle · Part of Your World [6889771281078066].mp4.part'
```

Just FYI: tried from Petah Tikva, a-Merkaz, Israel, but looks like it is not country-related

**Comment by bashonly** [comment]
> [download] Unable to open file: [Errno 22] Invalid argument:

This means the output filename is too long. Add `-o "%(title).150B [%(id)s].%(ext)s"` to your command

> but if I use VPN and try to download from Romania, for example, than I have got this:

Facebook blocks VPNs. Nothing we can do about that. Just don't use a VPN

**Comment by xiaose** [comment]
Yes, it solve problem. Decrease len. solving everything. Thank you
