### ISSUE TITLE
[crunchyroll] HTTP Error 400 when trying to download with cookies

### ISSUE THREAD

**Issue by Svagtlys** [yt-dlp/yt-dlp#9359]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

When attempting to download Crunchyroll videos using user agent and a cookie file obtained via --cookies-from-browser, a HTTP 400 Error: Bad Request is returned. I use the wrapper YTDL-SUB, so the log has some debug info from that as well, but the issue appears to be entirely within the YT-DLP execution. This setup worked previously, and I've confirmed that the playlist and videos are watchable from the computer running the download. There is no 400 Error when not using cookies, but the videos cannot be downloaded due to the lack of linked account.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[ytdl-sub] Validating subscriptions...
[ytdl-sub:subscription] Filtering subscriptions by name based on --match arguments
[ytdl-sub] Beginning subscription download for The Apothecary Diaries
[ytdl-sub] Subscription full yaml:
presets:
  The Apothecary Diaries:
    chapters:
      embed_chapters: true
    download:
    - playlist_thumbnails:
      - name: '{avatar_uncropped_thumbnail_file_name}'
        uid: avatar_uncropped
      - name: '{banner_uncropped_thumbnail_file_name}'
        uid: banner_uncropped
      source_thumbnails:
      - name: '{avatar_uncropped_thumbnail_file_name}'
        uid: avatar_uncropped
      - name: '{banner_uncropped_thumbnail_file_name}'
        uid: banner_uncropped
      url: '{url}'
    - url: '{url2}'
    - url: '{url3}'
    - url: '{url4}'
    - url: '{url5}'
    - url: '{url6}'
    - url: '{url7}'
    - url: '{url8}'
    - url: '{url9}'
    - url: '{url10}'
    - url: '{url11}'
    - url: '{url12}'
    - url: '{url13}'
    - url: '{url14}'
    - url: '{url15}'
    - url: '{url16}'
    - url: '{url17}'
    - url: '{url18}'
    - url: '{url19}'
    - url: '{url20}'
    - url: '{url21}'
    - url: '{url22}'
    - url: '{url23}'
    - url: '{url24}'
    - url: '{url25}'
    - url: '{url26}'
    - url: '{url27}'
    - url: '{url28}'
    - url: '{url29}'
    - url: '{url30}'
    - url: '{url31}'
    - url: '{url32}'
    - url: '{url33}'
    - url: '{url34}'
    - url: '{url35}'
    - url: '{url36}'
    - url: '{url37}'
    - url: '{url38}'
    - url: '{url39}'
    - url: '{url40}'
    - url: '{url41}'
    - url: '{url42}'
    - url: '{url43}'
    - url: '{url44}'
    - url: '{url45}'
    - url: '{url46}'
    - url: '{url47}'
    - url: '{url48}'
    - url: '{url49}'
    - url: '{url50}'
    - url: '{url51}'
    - url: '{url52}'
    - url: '{url53}'
    - url: '{url54}'
    - url: '{url55}'
    - url: '{url56}'
    - url: '{url57}'
    - url: '{url58}'
    - url: '{url59}'
    - url: '{url60}'
    - url: '{url61}'
    - url: '{url62}'
    - url: '{url63}'
    - url: '{url64}'
    - url: '{url65}'
    - url: '{url66}'
    - url: '{url67}'
    - url: '{url68}'
    - url: '{url69}'
    - url: '{url70}'
    - url: '{url71}'
    - url: '{url72}'
    - url: '{url73}'
    - url: '{url74}'
    - url: '{url75}'
    - url: '{url76}'
    - url: '{url77}'
    - url: '{url78}'
    - url: '{url79}'
    - url: '{url80}'
    - url: '{url81}'
    - url: '{url82}'
    - url: '{url83}'
    - url: '{url84}'
    - url: '{url85}'
    - url: '{url86}'
    - url: '{url87}'
    - url: '{url88}'
    - url: '{url89}'
    - url: '{url90}'
    - url: '{url91}'
    - url: '{url92}'
    - url: '{url93}'
    - url: '{url94}'
    - url: '{url95}'
    - url: '{url96}'
    - url: '{url97}'
    - url: '{url98}'
    - url: '{url99}'
    - url: '{url100}'
    format: bestvideo+bestaudio/best
    nfo_tags:
      kodi_safe: true
      nfo_name: '{episode_file_path}.nfo'
      nfo_root: episodedetails
      tags:
        aired: '{episode_date_standardized}'
        episode: '{episode_number}'
        genre:
        - '{tv_show_genre}'
        - '{genre1}'
        - '{genre2}'
        - '{genre3}'
        - '{genre4}'
        mpaa: '{episode_content_rating}'
        plot: '{episode_plot}'
        season: '{season_number}'
        title: '{episode_title}'
        year: '{episode_year}'
    output_directory_nfo_tags:
      kodi_safe: true
      nfo_name: tvshow.nfo
      nfo_root: tvshow
      tags:
        genre:
        - '{tv_show_genre}'
        mpaa: '{tv_show_content_rating}'
        title: '{tv_show_name}'
    output_options:
      file_name: '{episode_file_path}.{ext}'
      info_json_name: '{episode_file_path}.{info_json_ext}'
      maintain_download_archive: true
      output_directory: '{tv_show_directory}/{tv_show_name_sanitized}'
      thumbnail_name: '{thumbnail_file_name}'
    overrides:
      avatar_uncropped_thumbnail_file_name: '{tv_show_poster_file_name}'
      banner_uncropped_thumbnail_file_name: '{tv_show_fanart_file_name}'
      episode_content_rating: '{tv_show_content_rating}'
      episode_date_standardized: '{upload_date_standardized}'
      episode_file_name: s{season_number_padded}.e{episode_number_padded} - {file_title}
      episode_file_path: '{season_directory_name_sanitized}/{episode_file_name_sanitized}'
      episode_number: '{episode_number_json}'
      episode_number_json: "{\n  %map_get_non_empty(entry_metadata, \"episode_number\"\
        ,\n    %if(\n      %bool(title_capture_array),\n      %array_at(%array(title_capture_array),0,1),\n\
        \      1\n    )\n  )\n}"
      episode_number_padded: '{episode_number_json_sanitized}'
      episode_plot: '{webpage_url}


        {description}'
      episode_title: '{episode_title_json}'
      episode_title_json: "{\n  %map_get_non_empty(entry_metadata, \"episode\",\n\
        \    %if(\n      %bool(title_capture_array),\n      %array_at(%array(title_capture_array),1,%string(title)),\n\
        \      title\n    )\n  )\n}"
      episode_year: '{upload_year}'
      file_title: '{title_sanitized}'
      file_uid: '{uid_sanitized}'
      genre1: '{subscription_indent_1}'
      genre2: '{subscription_indent_2}'
      genre3: '{subscription_indent_3}'
      genre4: '{subscription_indent_4}'
      season_directory_name: Season {season_number_padded}
      season_number: '{season_number_json}'
      season_number_json: "{\n  %map_get_non_empty(entry_metadata, \"season_number\"\
        ,\n    1\n  )\n}"
      season_number_padded: '{season_number_json_sanitized}'
      season_poster_file_name: season{season_number_padded}-poster.jpg
      subscription_indent_1: Drama
      subscription_indent_2: Mystery
      subscription_indent_3: Romance
      subscription_indent_4: ''
      subscription_value: https://www.crunchyroll.com/series/G3KHEVDJ7/the-apothecary-diaries
      subscription_value_10: ''
      subscription_value_100: ''
      subscription_value_11: ''
      subscription_value_12: ''
      subscription_value_13: ''
      subscription_value_14: ''
      subscription_value_15: ''
      subscription_value_16: ''
      subscription_value_17: ''
      subscription_value_18: ''
      subscription_value_19: ''
      subscription_value_2: ''
      subscription_value_20: ''
      subscription_value_21: ''
      subscription_value_22: ''
      subscription_value_23: ''
      subscription_value_24: ''
      subscription_value_25: ''
      subscription_value_26: ''
      subscription_value_27: ''
      subscription_value_28: ''
      subscription_value_29: ''
      subscription_value_3: ''
      subscription_value_30: ''
      subscription_value_31: ''
      subscription_value_32: ''
      subscription_value_33: ''
      subscription_value_34: ''
      subscription_value_35: ''
      subscription_value_36: ''
      subscription_value_37: ''
      subscription_value_38: ''
      subscription_value_39: ''
      subscription_value_4: ''
      subscription_value_40: ''
      subscription_value_41: ''
      subscription_value_42: ''
      subscription_value_43: ''
      subscription_value_44: ''
      subscription_value_45: ''
      subscription_value_46: ''
      subscription_value_47: ''
      subscription_value_48: ''
      subscription_value_49: ''
      subscription_value_5: ''
      subscription_value_50: ''
      subscription_value_51: ''
      subscription_value_52: ''
      subscription_value_53: ''
      subscription_value_54: ''
      subscription_value_55: ''
      subscription_value_56: ''
      subscription_value_57: ''
      subscription_value_58: ''
      subscription_value_59: ''
      subscription_value_6: ''
      subscription_value_60: ''
      subscription_value_61: ''
      subscription_value_62: ''
      subscription_value_63: ''
      subscription_value_64: ''
      subscription_value_65: ''
      subscription_value_66: ''
      subscription_value_67: ''
      subscription_value_68: ''
      subscription_value_69: ''
      subscription_value_7: ''
      subscription_value_70: ''
      subscription_value_71: ''
      subscription_value_72: ''
      subscription_value_73: ''
      subscription_value_74: ''
      subscription_value_75: ''
      subscription_value_76: ''
      subscription_value_77: ''
      subscription_value_78: ''
      subscription_value_79: ''
      subscription_value_8: ''
      subscription_value_80: ''
      subscription_value_81: ''
      subscription_value_82: ''
      subscription_value_83: ''
      subscription_value_84: ''
      subscription_value_85: ''
      subscription_value_86: ''
      subscription_value_87: ''
      subscription_value_88: ''
      subscription_value_89: ''
      subscription_value_9: ''
      subscription_value_90: ''
      subscription_value_91: ''
      subscription_value_92: ''
      subscription_value_93: ''
      subscription_value_94: ''
      subscription_value_95: ''
      subscription_value_96: ''
      subscription_value_97: ''
      subscription_value_98: ''
      subscription_value_99: ''
      thumbnail_file_name: '{episode_file_path}-thumb.jpg'
      title_capture_array: "{\n  %regex_match('^.* Episode (\\d{1,3}).*\\W{3}(.*)$',\
        \ title)\n}"
      tv_show_content_rating: '{subscription_indent_2}'
      tv_show_content_rating_default: TV-14
      tv_show_directory: /tv_shows
      tv_show_fanart_file_name: fanart.jpg
      tv_show_genre: '{subscription_indent_1}'
      tv_show_genre_default: ytdl-sub
      tv_show_name: '{subscription_name}'
      tv_show_poster_file_name: poster.jpg
      url: '{subscription_value}'
      url10: '{subscription_value_10}'
      url100: '{subscription_value_100}'
      url11: '{subscription_value_11}'
      url12: '{subscription_value_12}'
      url13: '{subscription_value_13}'
      url14: '{subscription_value_14}'
      url15: '{subscription_value_15}'
      url16: '{subscription_value_16}'
      url17: '{subscription_value_17}'
      url18: '{subscription_value_18}'
      url19: '{subscription_value_19}'
      url2: '{subscription_value_2}'
      url20: '{subscription_value_20}'
      url21: '{subscription_value_21}'
      url22: '{subscription_value_22}'
      url23: '{subscription_value_23}'
      url24: '{subscription_value_24}'
      url25: '{subscription_value_25}'
      url26: '{subscription_value_26}'
      url27: '{subscription_value_27}'
      url28: '{subscription_value_28}'
      url29: '{subscription_value_29}'
      url3: '{subscription_value_3}'
      url30: '{subscription_value_30}'
      url31: '{subscription_value_31}'
      url32: '{subscription_value_32}'
      url33: '{subscription_value_33}'
      url34: '{subscription_value_34}'
      url35: '{subscription_value_35}'
      url36: '{subscription_value_36}'
      url37: '{subscription_value_37}'
      url38: '{subscription_value_38}'
      url39: '{subscription_value_39}'
      url4: '{subscription_value_4}'
      url40: '{subscription_value_40}'
      url41: '{subscription_value_41}'
      url42: '{subscription_value_42}'
      url43: '{subscription_value_43}'
      url44: '{subscription_value_44}'
      url45: '{subscription_value_45}'
      url46: '{subscription_value_46}'
      url47: '{subscription_value_47}'
      url48: '{subscription_value_48}'
      url49: '{subscription_value_49}'
      url5: '{subscription_value_5}'
      url50: '{subscription_value_50}'
      url51: '{subscription_value_51}'
      url52: '{subscription_value_52}'
      url53: '{subscription_value_53}'
      url54: '{subscription_value_54}'
      url55: '{subscription_value_55}'
      url56: '{subscription_value_56}'
      url57: '{subscription_value_57}'
      url58: '{subscription_value_58}'
      url59: '{subscription_value_59}'
      url6: '{subscription_value_6}'
      url60: '{subscription_value_60}'
      url61: '{subscription_value_61}'
      url62: '{subscription_value_62}'
      url63: '{subscription_value_63}'
      url64: '{subscription_value_64}'
      url65: '{subscription_value_65}'
      url66: '{subscription_value_66}'
      url67: '{subscription_value_67}'
      url68: '{subscription_value_68}'
      url69: '{subscription_value_69}'
      url7: '{subscription_value_7}'
      url70: '{subscription_value_70}'
      url71: '{subscription_value_71}'
      url72: '{subscription_value_72}'
      url73: '{subscription_value_73}'
      url74: '{subscription_value_74}'
      url75: '{subscription_value_75}'
      url76: '{subscription_value_76}'
      url77: '{subscription_value_77}'
      url78: '{subscription_value_78}'
      url79: '{subscription_value_79}'
      url8: '{subscription_value_8}'
      url80: '{subscription_value_80}'
      url81: '{subscription_value_81}'
      url82: '{subscription_value_82}'
      url83: '{subscription_value_83}'
      url84: '{subscription_value_84}'
      url85: '{subscription_value_85}'
      url86: '{subscription_value_86}'
      url87: '{subscription_value_87}'
      url88: '{subscription_value_88}'
      url89: '{subscription_value_89}'
      url9: '{subscription_value_9}'
      url90: '{subscription_value_90}'
      url91: '{subscription_value_91}'
      url92: '{subscription_value_92}'
      url93: '{subscription_value_93}'
      url94: '{subscription_value_94}'
      url95: '{subscription_value_95}'
      url96: '{subscription_value_96}'
      url97: '{subscription_value_97}'
      url98: '{subscription_value_98}'
      url99: '{subscription_value_99}'
    preset:
    - _kodi_tv_show
    - _tv_show_by_date
    - _season_by_year
    - kodi_tv_show_by_date
    - season_by_year__episode_by_month_day
    - Kodi TV Show by Date
    - best_video_quality
    - tv_show_paths
    - TV Show Basic
    - Anime Crunchyroll
    subtitles:
      allow_auto_generated_subtitles: true
      embed_subtitles: true
      languages:
      - en
    throttle_protection:
      sleep_per_download_s:
        max: 3.7
        min: 1.3
      sleep_per_subscription_s:
        max: 13.2
        min: 7.6
    video_tags:
      contentRating: '{episode_content_rating}'
      date: '{episode_date_standardized}'
      episode_id: '{episode_number}'
      genre: '{tv_show_genre}'
      show: '{tv_show_name}'
      synopsis: '{episode_plot}'
      title: '{episode_title}'
      year: '{episode_year}'
    ytdl_options:
      break_on_existing: false
      cookiefile: /tv_shows/cookies.txt
      extractor_args:
        crunchyrollbeta:
          hardsub:
          - en-US
          - None
      flat-playlist: true
      format: bv*[height<=1080]+ba/b[height<=1080] / wv*+ba/w
      http_headers:
        User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101
          Firefox/120.0
      merge_output_format: mp4
      rejecttitle: .*(dub|Dub).*
      verbose: true

[ytdl-sub:ytdl-options] Setting match-filters: 
 - !is_live & !is_upcoming & !post_live
[ytdl-sub:ytdl-options] Setting breaking-match-filters: []
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '/config/.ytdl-sub-downloads/The Apothecary Diaries/%(id)S.%(ext)s', 'writethumbnail': False, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '/config/.ytdl-sub-downloads/The Apothecary Diaries/.ytdl-sub-The Apothecary Diaries-download-archive.json', 'match_filter': <function match_filter_func.<locals>._match_func at 0x7f85f6dc6480>, 'format': 'bv*[height<=1080]+ba/b[height<=1080] / wv*+ba/w', 'break_on_existing': False, 'merge_output_format': 'mp4', 'flat-playlist': True, 'rejecttitle': '.*(dub|Dub).*', 'cookiefile': '/tv_shows/cookies.txt', 'http_headers': {'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0'}, 'extractor_args': {'crunchyrollbeta': {'hardsub': ['en-US', 'None']}}, 'verbose': True, 'skip_download': True, 'writeinfojson': True, 'extract_flat': 'discard'}
[ytdl-sub:yt-dlp] [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out None (No ANSI), error None (No ANSI), screen None (No ANSI)
[ytdl-sub:yt-dlp] [debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip) API
[ytdl-sub:yt-dlp] [debug] params: {'ignoreerrors': True, 'outtmpl': '/config/.ytdl-sub-downloads/The Apothecary Diaries/%(id)S.%(ext)s', 'writethumbnail': False, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '/config/.ytdl-sub-downloads/The Apothecary Diaries/.ytdl-sub-The Apothecary Diaries-download-archive.json', 'match_filter': <function match_filter_func.<locals>._match_func at 0x7f85f6dc6480>, 'format': 'bv*[height<=1080]+ba/b[height<=1080] / wv*+ba/w', 'break_on_existing': False, 'merge_output_format': 'mp4', 'flat-playlist': True, 'rejecttitle': '.*(dub|Dub).*', 'cookiefile': '/tv_shows/cookies.txt', 'http_headers': {'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}, 'extractor_args': {'crunchyrollbeta': {'hardsub': ['en-US', 'None']}}, 'verbose': True, 'skip_download': True, 'writeinfojson': True, 'extract_flat': 'discard', 'compat_opts': set()}
[ytdl-sub:yt-dlp] [debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.5.0-21-generic-x86_64-with (OpenSSL 3.1.5 30 Jan 2024)
[ytdl-sub:yt-dlp] [debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, phantomjs 2.1.1
[ytdl-sub:yt-dlp] [debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.2.0, websockets-12.0
[ytdl-sub:yt-dlp] [debug] Proxy map: {}
[ytdl-sub:yt-dlp] [debug] Request Handlers: urllib, requests, websockets
[ytdl-sub:yt-dlp] [debug] Loaded 1798 extractors
[ytdl-sub:yt-dlp] [debug] Loading archive file '/config/.ytdl-sub-downloads/The Apothecary Diaries/.ytdl-sub-The Apothecary Diaries-download-archive.json'
[ytdl-sub:yt-dlp] [crunchyroll:playlist] Extracting URL: https://www.crunchyroll.com/series/G3KHEVDJ7/the-apothecary-diaries
[ytdl-sub:yt-dlp] [debug] [crunchyroll:playlist] Using cxApiParam=noaihdevm_6iyg0a8l0q
[ytdl-sub:yt-dlp] [crunchyroll:playlist] Authenticating with grant_type=etp_rt_cookie
[ytdl-sub:yt-dlp] ERROR: [crunchyroll:playlist] G3KHEVDJ7: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl-sub:yt-dlp]   File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/crunchyroll.py", line 489, in _real_extract
    **traverse_obj(self._call_api(f'series/{internal_id}', internal_id, lang, 'series'), ('data', 0, {
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/crunchyroll.py", line 127, in _call_api
    result = self._call_base_api(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/crunchyroll.py", line 108, in _call_base_api
    self._update_auth()
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/crunchyroll.py", line 89, in _update_auth
    auth_response = self._download_json(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1072, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1036, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 906, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 863, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4082, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 343, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 850, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4114, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 400: Bad Request

[ytdl-sub:downloader] Beginning downloads for https://www.crunchyroll.com/series/G3KHEVDJ7/the-apothecary-diaries
[ytdl-sub:throttle-protection] Sleeping between subscriptions for 7.77 seconds
[ytdl-sub] 
No files changed for The Apothecary Diaries
[ytdl-sub] Download Summary:
The Apothecary Diaries     [39m0[39m [39m0[39m [39m0[39m     20 [32m✔[39m
Total: 1                   [39m0[39m [39m0[39m [39m0[39m     20 [32mSuccess[39m
```

**Comment by bashonly** [comment]
Can't reproduce the issue:
```shell
$ yt-dlp --ignore-config --verbose --cookies-from-browser firefox --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0" --print webpage_url https://www.crunchyroll.com/series/G3KHEVDJ7
[debug] Command-line config: ['--ignore-config', '--verbose', '--cookies-from-browser', 'firefox', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0', '--print', 'webpage_url', 'https://www.crunchyroll.com/series/G3KHEVDJ7']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.03.03.232706 from yt-dlp/yt-dlp-nightly-builds [ede624d1d] (pip)
[debug] Python 3.12.1 (CPython AMD64 64bit) - Windows-11-10.0.22000-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg N-113725-g37702e2066-20240220 (setts), ffprobe N-113725-g37702e2066-20240220
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\grub4k\AppData\Roaming\Mozilla\Firefox\Profiles\wzk1dbkd.default-release\cookies.sqlite"
Extracted 662 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[crunchyroll:playlist] Extracting URL: https://www.crunchyroll.com/series/G3KHEVDJ7
[debug] [crunchyroll:playlist] Using cxApiParam=noaihdevm_6iyg0a8l0q
[crunchyroll:playlist] Authenticating with grant_type=etp_rt_cookie
[crunchyroll:playlist] G3KHEVDJ7: Downloading series JSON (cms)
[download] Downloading playlist: The Apothecary Diaries
[crunchyroll:playlist] Retrieving signed policy
[crunchyroll:playlist] G3KHEVDJ7: Downloading seasons JSON (signed cms)
[crunchyroll:playlist] GR09CXPEK: Downloading episode list JSON (signed cms)
[crunchyroll:playlist] GYP8CX7W5: Downloading episode list JSON (signed cms)
[crunchyroll:playlist] GYMGC32JJ: Downloading episode list JSON (signed cms)
[crunchyroll:playlist] G6VNC2EDV: Downloading episode list JSON (signed cms)
[crunchyroll:playlist] GY3VC21M7: Downloading episode list JSON (signed cms)
[crunchyroll:playlist] Playlist The Apothecary Diaries: Downloading 92 items of 92
[download] Downloading item 1 of 92
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GMKUXQ2VM
[crunchyroll] GMKUXQ2VM: Downloading object info JSON (cms)
[crunchyroll] GMKUXQ2VM: Downloading stream info JSON (signed cms)
[crunchyroll] To get all formats of a hardsub language, use "--extractor-args crunchyrollbeta:hardsub=<language_code or all>". See https://github.com/yt-dlp/yt-dlp#crunchyrollbeta-crunchyroll for more info
[crunchyroll] GMKUXQ2VM: Downloading adaptive_hls HLS manifest
[crunchyroll] GMKUXQ2VM: Downloading chapter info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] GMKUXQ2VM: Downloading 1 format(s): adaptive_hls-8117
https://www.crunchyroll.com/watch/GMKUXQ2VM
[download] Downloading item 2 of 92
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GVWU0WE92
[crunchyroll] GVWU0WE92: Downloading object info JSON (cms)
[crunchyroll] GVWU0WE92: Downloading stream info JSON (signed cms)
[crunchyroll] GVWU0WE92: Downloading adaptive_hls HLS manifest

ERROR: Interrupted by user
```

Try with only yt-dlp (not ytdl-sub), and try with `--cookies-from-browser` instead of a cookiefile.

**Comment by Svagtlys** [comment]
Thanks, does seem to be an issue with something else.

**Comment by noahkiss** [comment]
@Svagtlys did you figure out what the issue was? Also seeing this with ytdl-sub, but I see you didn't open an issue there.

**Comment by Svagtlys** [comment]
Sorry, I'm just seeing this. For posterity, Crunchyroll has (last I heard) changed their API and the individual who was keeping the downloader up to date is no longer able to do so. On top of that, I believe I saw info about DRM being put in the videos so that even if the downloader was updated, it still wouldn't work in the near future.

**Comment by Jules-A** [comment]
> Sorry, I'm just seeing this. For posterity, Crunchyroll has (last I heard) changed their API and the individual who was keeping the downloader up to date is no longer able to do so. On top of that, I believe I saw info about DRM being put in the videos so that even if the downloader was updated, it still wouldn't work in the near future.

That issue was worked around by using the Switch API which doesn't use DRM. Cookies still don't work though afaik.
