### ISSUE TITLE
[vrt] Support `vrt.be/vrtmax/` URLs

### ISSUE THREAD

**Issue by drhino** [yt-dlp/yt-dlp#9375]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Belgium

### Example URLs

- https://www.vrt.be/vrtmax/a-z/kamp-waes/2/kamp-waes-s2a1/

### Provide a description that is worded well enough to be understood

The example URL is not supported.
However, using the MPEG-DASH manifest as the input URL to `yt-dlp` works as expected (without authentication).

Note that some URLs on this website are DRM protected, some are not.
The example URL given is not DRM protected.

---

Possible solution:

When navigation to the example URL, a network request is made that returns a JSON response containing the URL to the MPEG-DASH manifest. In that same response it is also indicated whether or not the content is DRM protected.

Such URL always starts with: 'https://media-services-public.vrt.be/media-aggregator/v2/media-items/pbs-pub-'

and the response body looks like:

```json
{
    "duration": 3008130,
    "skinType": "vod",
    "title": "Aflevering 1",
    "shortDescription": null,
    "drm": null,
    "drmExpired": null,
    "videoRobustness": null,
    "aspectRatio": "16:9",
    "posterImageUrl": "https://images.vrt.be/orig/2023/12/27/00656d46-a4ca-11ee-b483-02b7b76bf47f.jpg",
    "channelId": null,
    "targetUrls": [
        {
            "type": "hls",
            "url": "https://remix.vrtcdn.be/content/vod/pl-23f6e96b-cebe-4d73-9e42-b1180a7a68eb/pl-23f6e96b-cebe-4d73-9e42-b1180a7a68eb_nodrm_6f287733-5631-4526-93cd-4c2c68014ba4.ism/.m3u8?filter=%28%21%28type%3D%3D%22audio%22%26%26FourCC%21%3D%22AACL%22%29%29"
        },
        {
            "type": "mpeg_dash",
            "url": "https://remix.vrtcdn.be/content/vod/pl-23f6e96b-cebe-4d73-9e42-b1180a7a68eb/pl-23f6e96b-cebe-4d73-9e42-b1180a7a68eb_nodrm_6f287733-5631-4526-93cd-4c2c68014ba4.ism/.mpd?filter=%28%21%28type%3D%3D%22audio%22%26%26FourCC%21%3D%22AACL%22%29%29"
        }
    ],
    "downloadUrls": [],
    "playlist": {
        "content": [
            {
                "eventType": "ONBOARDING",
                "duration": 4140,
                "skippable": false
            },
            {
                "eventType": "STANDARD",
                "duration": 3008130,
                "skippable": true
            }
        ]
    }
}
```

Using the URL below the `"type": "mpeg_dash",` works as expected.

Example: `yt-dlp 'https://remix.vrtcdn.be/content/vod/pl-23f6e96b-cebe-4d73-9e42-b1180a7a68eb/pl-23f6e96b-cebe-4d73-9e42-b1180a7a68eb_nodrm_6f287733-5631-4526-93cd-4c2c68014ba4.ism/.mpd?filter=%28%21%28type%3D%3D%22audio%22%26%26FourCC%21%3D%22AACL%22%29%29'`

It would be great to have this integrated into `yt-dlp` so that the example URL could be used rather than finding the MPEG-DASH URL using Google Chrome network tab.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.vrt.be/vrtmax/a-z/kamp-waes/2/kamp-waes-s2a1/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.03.04.231958 from yt-dlp/yt-dlp-master-builds [cf91400a1] (darwin_legacy_exe)
[debug] Python 3.10.5 (CPython x86_64 64bit) - macOS-10.13.6-x86_64-i386-64bit (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 6.1.1-tessus (setts), ffprobe 6.1.1-tessus, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.03.04.231958 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.03.04.231958 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://www.vrt.be/vrtmax/a-z/kamp-waes/2/kamp-waes-s2a1/
[generic] kamp-waes-s2a1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] kamp-waes-s2a1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.vrt.be/vrtmax/a-z/kamp-waes/2/kamp-waes-s2a1/
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1593, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1728, in __extract_info
  File "yt_dlp/extractor/common.py", line 732, in extract
  File "yt_dlp/extractor/generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.vrt.be/vrtmax/a-z/kamp-waes/2/kamp-waes-s2a1/
```

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/vrt.py

The extractor needs to add support for this URL format. There is already an open PR to fix login, #8174

**Comment by NixonSchool** [comment]
I don't have time to fill the form, it's too big, your website brought up this error. Everything is there, date, error type etc, on chrome. 
![yt1s report](https://github.com/yt-dlp/yt-dlp/assets/139177099/58c135c4-6d3b-49c0-91d2-7f0748850c34)
This was the link i pasted to download:
https://www.youtube.com/watch?v=m6HpnPrQVNw&pp=ygUgYnVsbGV0IHByb29mIGhvc3RpbmcgZG9jdW1lbnRhcnk%3D

**Comment by MichaelDeBoey** [comment]
@drhino @bashonly It might be interesting to have a look at #12479
