### ISSUE TITLE
[Question] How do you use "--match-filter" to skip private videos?

### ISSUE THREAD

**Issue by Punpki** [yt-dlp/yt-dlp#939]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hello! 
I want to use the "--match-filter" command to skip private videos, but I don't know what to write to make it work. I would be very thankful if someone could point me in the right direction. 

Thanks.

**Comment by pukkandan** [comment]
`--match-filter "availability!=private"`

**Comment by Punpki** [comment]
Thank you for answering.
I tried your command but it seems that nothing happened. The private video error still shows up for some reason.

Here's the log:

`[debug] Command-line config: ['--verbose', '--match-filter', 'availability!=private', '--abort-on-error', '--batch-file', 'sources/Source - Testing.txt', '--output', '%(title)s.%(ext)s']
[debug] Batch file urls: ['https://www.youtube.com/playlist?list=PLnECGpr5DfBtutGBQntelykoOruV8m2YS']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.11.0-7633-generic-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Optional libraries: keyring, sqlite
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLnECGpr5DfBtutGBQntelykoOruV8m2YS
[youtube:tab] PLnECGpr5DfBtutGBQntelykoOruV8m2YS: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLnECGpr5DfBtutGBQntelykoOruV8m2YS
[youtube:tab] PLnECGpr5DfBtutGBQntelykoOruV8m2YS: Downloading API JSON with unavailable videos
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos will be hidden during playback
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos will be hidden during playback
[download] Downloading playlist: Chrono Trigger Randomizer
[youtube:tab] playlist Chrono Trigger Randomizer: Downloading 5 videos
[download] Downloading video 1 of 5
[debug] [youtube] Extracting URL: Xfzxuh0rjEM
[youtube] Xfzxuh0rjEM: Downloading webpage
[youtube] Xfzxuh0rjEM: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Xfzxuh0rjEM: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://r15---sn-uxap5nvoxg5-j2is.googlevideo.com/videoplayback?expire=1631299512&ei=WFM7YZHKMZelyAXLtp64CQ&ip=194.18.253.147&id=o-AEeP27f-NX-xWqC1aYLOyDu6HuGwB8XBUEOnRH3CTN4F&itag=303&source=youtube&requiressl=yes&mh=P7&mm=31%2C29&mn=sn-uxap5nvoxg5-j2is%2Csn-5go7yne6&ms=au%2Crdu&mv=m&mvi=15&pcm2cms=yes&pl=24&initcwndbps=1922500&vprv=1&mime=video%2Fwebm&gir=yes&clen=441448131&dur=1741.949&lmt=1631048678281199&mt=1631277406&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgKTCP-L3NrVpPMxBZvAXFoCIymKOou8Q3mNBsryhMIdkCIQD23hSxNZES0Ts0qaJxcMJLT5AjskbC9JW9bUnrYoqesg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOZ9MUNXOkY1FTX8OZk3YhYdOo45OseO6ASGtkwyULY-AiEAygffTuTmTuwy5X8MEoHUsqFAzTFqyymHzcvZ2t2CI9I%3D"
[download] Destination: THE WINGS OF TIME! │ Chrono Trigger RANDOMIZER #1.f303.webm
[download] 100% of 421.00MiB in 01:24
[debug] Invoking downloader on "https://r15---sn-uxap5nvoxg5-j2is.googlevideo.com/videoplayback?expire=1631299512&ei=WFM7YZHKMZelyAXLtp64CQ&ip=194.18.253.147&id=o-AEeP27f-NX-xWqC1aYLOyDu6HuGwB8XBUEOnRH3CTN4F&itag=251&source=youtube&requiressl=yes&mh=P7&mm=31%2C29&mn=sn-uxap5nvoxg5-j2is%2Csn-5go7yne6&ms=au%2Crdu&mv=m&mvi=15&pcm2cms=yes&pl=24&initcwndbps=1922500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=29207483&dur=1741.981&lmt=1631047813238400&mt=1631277406&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALGi48uc46N37OQQeb-Et6ZlZtrf8r6cgB-RyQdx5F8BAiEAoeBTjv7QLapfMHEnG-pdgsFj858oC7dWoeMQWRPEP3g%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOZ9MUNXOkY1FTX8OZk3YhYdOo45OseO6ASGtkwyULY-AiEAygffTuTmTuwy5X8MEoHUsqFAzTFqyymHzcvZ2t2CI9I%3D"
[download] Destination: THE WINGS OF TIME! │ Chrono Trigger RANDOMIZER #1.f251.webm
[download] 100% of 27.85MiB in 00:07
[Merger] Merging formats into "THE WINGS OF TIME! │ Chrono Trigger RANDOMIZER #1.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:THE WINGS OF TIME! │ Chrono Trigger RANDOMIZER #1.f303.webm' -i 'file:THE WINGS OF TIME! │ Chrono Trigger RANDOMIZER #1.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:THE WINGS OF TIME! │ Chrono Trigger RANDOMIZER #1.temp.webm'
Deleting original file THE WINGS OF TIME! │ Chrono Trigger RANDOMIZER #1.f251.webm (pass -k to keep)
Deleting original file THE WINGS OF TIME! │ Chrono Trigger RANDOMIZER #1.f303.webm (pass -k to keep)
[download] Downloading video 2 of 5
[debug] [youtube] Extracting URL: 6W_uDHVq4EU
[youtube] 6W_uDHVq4EU: Downloading webpage
[youtube] 6W_uDHVq4EU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 6W_uDHVq4EU: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://r13---sn-uxap5nvoxg5-j2is.googlevideo.com/videoplayback?expire=1631299608&ei=uFM7Yc3tHMiPyAXv7oWABA&ip=194.18.253.147&id=o-AC-T1aUxsPsrVlMSs4rqM2bxPZjrBWfs0g0WR4Nnt8Dt&itag=303&source=youtube&requiressl=yes&mh=XI&mm=31%2C29&mn=sn-uxap5nvoxg5-j2is%2Csn-5go7yner&ms=au%2Crdu&mv=m&mvi=13&pl=24&initcwndbps=1703750&vprv=1&mime=video%2Fwebm&gir=yes&clen=357707750&dur=2028.099&lmt=1630987966063102&mt=1631277649&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6316224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANYcuBMHKjVu7AZeNkbTbZX4Hdc62mBWyWuh2ycwMP8bAiBx1YCstLTE_e1h-sQqDzRLsE5wNBS-Swu1eRYNkcyXpg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJz3sAup4CBbN2YkJsJij_z_EBOGCW3s6yusl7ogYqq-AiEA2Qv5BMQejitFmNgRmU1z-j1kBaGPyjyVbRLW4tXiej0%3D"
[download] Destination: Masamune!! │ Chrono Trigger RANDOMIZER #2.f303.webm
[download] 100% of 341.14MiB in 01:04
[debug] Invoking downloader on "https://r13---sn-uxap5nvoxg5-j2is.googlevideo.com/videoplayback?expire=1631299608&ei=uFM7Yc3tHMiPyAXv7oWABA&ip=194.18.253.147&id=o-AC-T1aUxsPsrVlMSs4rqM2bxPZjrBWfs0g0WR4Nnt8Dt&itag=251&source=youtube&requiressl=yes&mh=XI&mm=31%2C29&mn=sn-uxap5nvoxg5-j2is%2Csn-5go7yner&ms=au%2Crdu&mv=m&mvi=13&pl=24&initcwndbps=1703750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=33401668&dur=2028.141&lmt=1630988291870755&mt=1631277649&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPFST581o2Fnb7-D1mVdNPjWs-XWtc46yiekQzaK9uz5AiEA83QeW-MF0ynVXpH8PvIMIlY_PxOCaQ6iJuKYpdH1YCk%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJz3sAup4CBbN2YkJsJij_z_EBOGCW3s6yusl7ogYqq-AiEA2Qv5BMQejitFmNgRmU1z-j1kBaGPyjyVbRLW4tXiej0%3D"
[download] Destination: Masamune!! │ Chrono Trigger RANDOMIZER #2.f251.webm
[download] 100% of 31.85MiB in 00:07
[Merger] Merging formats into "Masamune!! │ Chrono Trigger RANDOMIZER #2.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Masamune!! │ Chrono Trigger RANDOMIZER #2.f303.webm' -i 'file:Masamune!! │ Chrono Trigger RANDOMIZER #2.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Masamune!! │ Chrono Trigger RANDOMIZER #2.temp.webm'
Deleting original file Masamune!! │ Chrono Trigger RANDOMIZER #2.f303.webm (pass -k to keep)
Deleting original file Masamune!! │ Chrono Trigger RANDOMIZER #2.f251.webm (pass -k to keep)
[download] Downloading video 3 of 5
[debug] [youtube] Extracting URL: ygNkJhRrYa8
[youtube] ygNkJhRrYa8: Downloading webpage
[youtube] ygNkJhRrYa8: Downloading android player API JSON
ERROR: [youtube] ygNkJhRrYa8: Private video. Sign in if you've been granted access to this video
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2812, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1079, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: Private video. Sign in if you've been granted access to this video
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2812, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1079, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: Private video. Sign in if you've been granted access to this video

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1239, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 600, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] ygNkJhRrYa8: Private video. Sign in if you've been granted access to this video
`

**Comment by pukkandan** [comment]
It is only useful if you have access to the video. To continue after the error, just remove `--abort-on-error` from your command
