### ISSUE TITLE
[Spotify] Support for video podcasts

### ISSUE THREAD

**Issue by asdfmonster261** [yt-dlp/yt-dlp#943]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', '--cookies', '.\\spotify.com_cookies.txt', 'https://open.spotify.com/episode/2PFQRsKwSXaxlwl6G99wyc?si=wyMN33l7QcSfiDhpkDiuXA&dl_branch=1']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[spotify] Downloading JSON metadata
[debug] [spotify] Extracting URL: https://open.spotify.com/episode/2PFQRsKwSXaxlwl6G99wyc?si=wyMN33l7QcSfiDhpkDiuXA&dl_branch=1
[spotify] 2PFQRsKwSXaxlwl6G99wyc: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2PFQRsKwSXaxlwl6G99wyc: Downloading 1 format(s): MP3_96
[debug] Invoking downloader on "https://anon-podcast.scdn.co/8c4b394d20eba5cdf341b6e3b0a6a325a6b353c6"
ERROR: unable to download video data: <urlopen error [Errno 11001] getaddrinfo failed>
Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1414, in connect
  File "http\client.py", line 918, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2798, in process_info
  File "yt_dlp\YoutubeDL.py", line 2461, in dl
  File "yt_dlp\downloader\common.py", line 386, in download
  File "yt_dlp\downloader\http.py", line 366, in real_download
  File "yt_dlp\downloader\http.py", line 118, in establish_connection
  File "yt_dlp\downloader\http.py", line 112, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3218, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 2830, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

## Description

I am trying to get the video for Spotify podcasts, I read online somewhere that those specifically don't have DRM on them, unable to confirm as I continue receiving errors while trying. If there is drm, would it be possible to obtain the encrypted file and leave it up to the user to figure out the rest?

A free spotify account should work fine to access the same podcast link. Looking at `https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md` it looks like spotify is on the list.

Using `yt-dlp -F  --cookies .\spotify.com_cookies.txt https://open.spotify.com/episode/2PFQRsKwSXaxlwl6G99wyc?si=wyMN33l7QcSfiDhpkDiuXA&dl_branch=1` returns 

```
[spotify] Downloading JSON metadata
[spotify] 2PFQRsKwSXaxlwl6G99wyc: Downloading JSON metadata
[info] Available formats for 2PFQRsKwSXaxlwl6G99wyc:
ID     EXT RESOLUTION | PROTO | ACODEC   ABR
------ --- ---------- - ----- - ------- ----
MP3_96 mp3 audio only | https | unknown  96k
```

Using `yt-dlp -f MP3_96  --cookies .\spotify.com_cookies.txt https://open.spotify.com/episode/2PFQRsKwSXaxlwl6G99wyc?si=wyMN33l7QcSfiDhpkDiuXA&dl_branch=1` returns
```
[debug] Command-line config: ['-vf', 'MP3_96', '--cookies', '.\\spotify.com_cookies.txt', 'https://open.spotify.com/episode/2PFQRsKwSXaxlwl6G99wyc?si=wyMN33l7QcSfiDhpkDiuXA&dl_branch=1']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[spotify] Downloading JSON metadata
[debug] [spotify] Extracting URL: https://open.spotify.com/episode/2PFQRsKwSXaxlwl6G99wyc?si=wyMN33l7QcSfiDhpkDiuXA&dl_branch=1
[spotify] 2PFQRsKwSXaxlwl6G99wyc: Downloading JSON metadata
[info] 2PFQRsKwSXaxlwl6G99wyc: Downloading 1 format(s): MP3_96
[debug] Invoking downloader on "https://anon-podcast.scdn.co/8c4b394d20eba5cdf341b6e3b0a6a325a6b353c6"
ERROR: unable to download video data: <urlopen error [Errno 11001] getaddrinfo failed>
Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1414, in connect
  File "http\client.py", line 918, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2798, in process_info
  File "yt_dlp\YoutubeDL.py", line 2461, in dl
  File "yt_dlp\downloader\common.py", line 386, in download
  File "yt_dlp\downloader\http.py", line 366, in real_download
  File "yt_dlp\downloader\http.py", line 118, in establish_connection
  File "yt_dlp\downloader\http.py", line 112, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3218, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 2830, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

Thanks for any help with this!

**Comment by pukkandan** [comment]
The current extractor seems to only support only mp3. This also doen't appear to have DRM. So assuming someone can figure out how spotify is serving this, we should be able to add support

**Comment by nyuszika7h** [comment]
I think the whole extractor is broken.

> The technical details: Spotify's anon-podcast.scdn.co server has been discontinued. This served as an unauthenticated proxy server for podcast episode audio. They have switched to streaming directly from the podcast's source server. For non-exclusive podcasts, that is simply whatever is in the RSS feed (in which case, you can access those podcasts directly without Spotifeed's help). For exclusive podcasts, Spotify is using their audio-fa.scdn.co server, which appears to be using a chunked MP4 stream that is not usable by general podcast clients. 

(from https://spotifeed.timdorr.com/)

**Comment by pukkandan** [comment]
ah, you are right. I was trying with `https://open.spotify.com/episode/4Z7GAJ50bgctf6uclHlWKo` which was since it has external URL. The `-f MP3_96` is in fact not working

**Comment by chaudhryaziz** [comment]
I have read that Joe Rogan episodes are encrypted with widevine now. It seems to only apply to his podcast. Is there a way to return a specific error when detecting this kind of DRM?

**Comment by mrx23dot** [comment]
For me it gives:
[spotify] Downloading JSON metadata
[spotify] 4Z7GAJ50bgctf6uclHlWKo: Downloading JSON metadata
ERROR: 'NoneType' object is not subscriptable

**Comment by ParadoxGBB** [comment]
Just wanted to jump in and note that the recent fix in https://github.com/yt-dlp/yt-dlp/pull/3430 doesn't address this, even for the specific embedded URL provided in the test. Anon-podcast.scdn.co is still being used.

`C:\python\python.exe  <path to yt-dlp>\yt-dlp https://open.spotify.com/embed/episode/4TvCsKKs2thXmarHigWvXE?si=7eatS8AbQb6RxqO2raIuWA
[spotify] Downloading JSON metadata
[spotify] 4TvCsKKs2thXmarHigWvXE: Downloading JSON metadata
[info] 4TvCsKKs2thXmarHigWvXE: Downloading 1 format(s): MP3_96
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>. Retrying (attempt 1 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>. Retrying (attempt 2 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>. Retrying (attempt 3 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>. Retrying (attempt 4 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>. Retrying (attempt 5 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>. Retrying (attempt 6 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>. Retrying (attempt 7 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>. Retrying (attempt 8 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>. Retrying (attempt 9 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>. Retrying (attempt 10 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11001] getaddrinfo failed>
ERROR: giving up after 10 retries`

**Comment by mrx23dot** [comment]
As I read spotify DRM encrypts the files.
Although the key must be stored on the client to be able to listen back.

**Comment by ndren** [comment]
How does https://github.com/spotDL/spotify-downloader work? It looks like it covers a lot of what yt-dlp is missing, but I can't figure out what URLs it's using.

**Comment by fireattack** [comment]
That works by matching the song from YouTube and download from YouTube IIRC.

It works sometimes, but that's like an entirely different thing.

**Comment by asdfmonster261** [comment]
I hadn’t noticed the title was changed to “mp3 format broken”. I opened this issue to address video podcasts. Due to mp3 formats being outside of the scope of the intended issue, I have changed the title back to Pukkandans title “Support for video podcasts”.

Since opening this I have been able to confirm that Spotify podcasts are NOT encrypted and can be downloaded and viewed offline using a combination or aria2c, type, and ffmpeg without decrypting anything.

With this information, I believe an update for the Spotify site would be feasible for podcasts. I’ll put the general process below, hopefully this can help people more capable than myself integrate it into yt-dlp.

1. Download init.webm from Spotify for the audio and video tracks. The links can be found in the browsers network tab.
2. Download the rest of the segments, which are also webm files, whose name starts at 0 and increments up by 4 for each segment. I’ve been using a for loop with aria for this step. These links can also be found in the network tab of your browser.
3. Combine the segments, making sure init.webm is the first. I’ve been using the type command for this, for example `type init.webm 0000.webm 0004.webm 0008.webm > out.webm`
4. Combine the audio and video tracks with ffmpeg. 

After doing these steps for both the audio and video tracks, the output file is watchable. No errors during playback, and no decryption of protected content at any step.

**Comment by fireattack** [comment]
i recommend you to use `copy /b init.webm+0000.webm+... out.webm` assuming Windows. The final results should be the same, but it's much faster.

**Comment by ParadoxGBB** [comment]
This bug has flipped between tracking (I belienve non-DRM'd) audio podcasts and video podcasts and two weeks ago the title of this has recently changed to consider the latter. Is there anything tracking the former? My comment above is specifically referencing audio / mp3.

Reference URL example:

https://open.spotify.com/episode/43Q2Rf5YUIus09WSvjr5Da

**Comment by asdfmonster261** [comment]
> This bug has flipped between tracking (I believe non-DRM'd) audio podcasts and video podcasts and two weeks ago the title of this has recently changed to consider the latter. Is there anything tracking the former? My comment above is specifically referencing audio / mp3.
> 
> Reference URL example:
> 
> https://open.spotify.com/episode/43Q2Rf5YUIus09WSvjr5Da
> 
> Current output indicates that this might be a known issue:
> 
> WARNING: The program functionality for this site has been marked as broken, and will probably not work.


This issue was always supposed to be about unencrypted video podcast support, not audio podcasts. That is why I changed the title back to something more appropriate.

If you follow the process I detailed in a previous comment, you should be able to get the audio only podcast downloaded as long as it isn’t encrypted.

**Comment by ParadoxGBB** [comment]
@asdfmonster261 Understood, but that doesn't address my question.

**Comment by asdfmonster261** [comment]
Have you checked if anything is tracking the former? I thought I’d explained what this one is and isn’t tracking.

**Comment by fireattack** [comment]
You don't really need to change it back, because currently both video and audio download are broken. 

And they're essentially the same issue anyway today.

I understand you're the one opened the ticket, but this is a public repo, so a ticket being modified to track related things isn't uncommon. There have been many people subscribing this issue for tracking both. (AFAIK, this is the only active ticket about Spotify).

The reason why [pukkandan](https://github.com/pukkandan) changed it to [Spotify] mp3 format broken is because that part was working before, which makes it a bug/regression, than just an enhancement (something never supports), which is (relatively speaking) more important.

You can manually download either audio or video, but that would just be a workaround, we still need to track the bug for yt-dlp.

**Comment by asdfmonster261** [comment]
The problem is that the way the extractor was made used `anon-podcast.scdn.co` as the source for downloading the mp3 format. 

That server has been discontinued entirely by Spotify. 

From what I've seen getting podcasts manually, exclusive podcasts use either `audio-ak-spotify-com.akamaized.net`, `video-akpcw-cdn-spotify-com.akamaized.net`, or `audio-fa.scdn.co`. 
For non exclusive podcasts, you would not need the Spotify extractor to begin with. 

In addition, Spotify now uses segmented streams for podcasts, both encrypted and unencrypted. The unencrypted streams seem to be using Opus for audio and VP9 for video, packaged into a webm. Audio only seems to use an mp4 or m4a container with AAC audio.

After getting back to my PC and checking the link ParadoxGBB was inquiring about, it is using widevine encryption, and once decrypted, the file is in an mp4/m4a container using AAC as the codec, which seems to be standard for audio only media across the platform, as I just checked their music and it uses the same thing. It also means the manual method I had described before would not work without also obtaining keys.

To me, all of this seems to imply that the mp3 format being broken is not just a regression, it is permanently gone.

**Comment by bashonly** [comment]
What's a non-DRM example URL? None of the URLs in this issue will load in a DRM-disabled Firefox

**Comment by asdfmonster261** [comment]
> What's a non-DRM example URL? None of the URLs in this issue will load in a DRM-disabled Firefox

This was the example I had used in the initial post

https://open.spotify.com/episode/2PFQRsKwSXaxlwl6G99wyc

**Comment by fireattack** [comment]
> After getting back to my PC and checking the link ParadoxGBB was inquiring about, it is using widevine encryption, and once decrypted, the file is in an mp4/m4a container using AAC as the codec. This seems to be standard for audio only media across the platform, as I just checked their music and it uses the same thing. It also means the manual method I had described before would not work without also obtaining keys.

Thanks for the insight. So it looks like they encrypt all audio podcasts now? If so then yeah, that's essentially a different problem and probably out of scope.

**Comment by bashonly** [comment]
> This was the example I had used in the initial post
> 
> https://open.spotify.com/episode/2PFQRsKwSXaxlwl6G99wyc

![spotify](https://user-images.githubusercontent.com/88596187/211456466-1570a496-65c7-4538-bfd7-bbbed33588de.jpg)

**Comment by asdfmonster261** [comment]
@bashonly 
The files themselves do not have drm on them after following the process I had described. Beyond that I cannot troubleshoot your installation of Firefox.

@fireattack 
I think it's only some, as I don't get a widevine pssh from my extension for this one.
https://open.spotify.com/episode/1KwInKfPtO3pobRME7A7fQ

**Comment by pukkandan** [comment]
Even if the video itself is not encrypted[^1], the token required for accessing the segment URL is generated using the CDM[^2]. They also do not appear to have the non-DRM mp3 formats any more.

[^1]: which I haven't verified
[^2]: Look for calls to `https://spclient.wg.spotify.com/widevine-license/v1/application-certificate` and `https://gae2-spclient.spotify.com/manifests/v7/json/sources/2ee6f8e242175a3fbe634b1badab276d/options/supports_drm`

**Comment by chaudhryaziz** [comment]
Is there some way to add the ability to pass credentials or some key you obtain from the browser session so that yt-dlp can grab the unencrypted files?

**Comment by coletdjnz** [comment]
> Is there some way to add the ability to pass credentials or some key you obtain from the browser session so that yt-dlp can grab the unencrypted files? 

no, again, we will not support built-in extractors for DRMed content.

**Comment by danepedersen** [comment]
That's what I was thinking.  Since everything is "getting Widevined", the only hope would be to basically duplicate the license request and CDM so as to be able to decrypt the Widevined content.  Someone (I forget who) DID manage to do it a few years ago (using another software - Bento or something like that - but I believe Widevine has updated its key-rotation schemes so any "Widevine clone" would have to account for that.  As far as I understand, the "goodies" are nestled within the widevinecdm.dll - and I'm not an expert (yet) so one of us would have to figure out how to analyze it.  I tried to parse it and got nowhere, likely because it's a binary file and I'm not a machine 😂

Again (and I cannot emphasize this enough), I DO NOT CONDONE THIS FOR ANY ILLICIT USE.  Content producers have good reason for encrypting their content, as a lot of people for whatever reason(s) seem to think they can profit off of illegally copying/reselling it.

There are only two valid reasons for downloading streaming content: playing it offline (which I do), and avoiding buffering and latency.

There is also the argument to be made that we shouldn't even try it since it would be antithetical (in a sense) to all the efforts the content producers put into making their stuff, for which they should be fairly compensated and credited.

**Comment by bashonly** [comment]
@danepedersen yt-dlp does not and will not support DRM circumvention

> There is also the argument to be made that we shouldn't even try it

There is no argument to be had: we will not try it. In fact, do not discuss this on this repo

**Comment by danepedersen** [comment]
`Furthermore, do not discuss this on this repo
Understood.  My apologies.

**Comment by bashonly** [comment]
won't be supported
