### ISSUE TITLE
dailymotion embed extraction needs a fix

### ISSUE THREAD

**Issue by pi3141** [yt-dlp/yt-dlp#9432]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

All videos from dailymotion return me ERROR: unable to download video data: HTTP Error 404: Not Found
The log is for the command :
`yt-dlp -Uv https://www.leparisien.fr/environnement/video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU.php`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-Uv', 'https://www.leparisien.fr/environnement/video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU.php']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.03.10.232703 from yt-dlp/yt-dlp-nightly-builds [8463fb510] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-11-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.03.10.232703 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.03.10.232703 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.leparisien.fr/environnement/video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU.php
[generic] video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[dailymotion:user] Extracting URL: https://www.dailymotion.com/crawler/video/x8u4owg#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU%22%2C+%22to_generic%22%3A+true%2C+%22referer%22%3A+%22https%3A%2F%2Fwww.leparisien.fr%2Fenvironnement%2Fvideo-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU.php%22%7D
[download] Downloading playlist: VIDÉO. Le « véloto », la voiture à pédales qui aimerait se faire une place sur les routes
[dailymotion:user] Downloading Access Token
[dailymotion:user] crawler: Downloading page 1
[dailymotion:user] Playlist VIDÉO. Le « véloto », la voiture à pédales qui aimerait se faire une place sur les routes: Downloading 1 items of 1
[download] Downloading item 1 of 1
[dailymotion] Extracting URL: https://www.dailymotion.com/video/x36ni
[dailymotion] x36ni: Downloading media JSON metadata
[dailymotion] x36ni: Downloading metadata JSON
[dailymotion] x36ni: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] x36ni: Downloading 1 format(s): http-380
[debug] Invoking http downloader on "https://vod.cf.dmcdn.net/sec2(9tzUmb7AO5-EQ5oA-lma9g_9dd_veG1lpZjtBO7wKGCddHf1KDQTc5qOQaQR688-fjFJndPUZ3VFL_4sWLybyQVNJkFmtJG_NzB7PDJVAaTTjlg75yGip8a4TZ4LGi97qrb0QxguSVRiWIoraYKyY_Hqx-OIe8JxLX6-lcbIY-o)/video/095/841/148590_mp4_h264_aac.mp4"
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3434, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3155, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/usr/bin/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4101, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/common.py", line 115, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/common.py", line 326, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

[download] Finished downloading playlist: VIDÉO. Le « véloto », la voiture à pédales qui aimerait se faire une place sur les routes
```

**Comment by bashonly** [comment]
I can't reproduce the issue. Does https://www.dailymotion.com/video/x36ni play in browser for you?

**Comment by pi3141** [comment]
No it does not. It seems that yt-dlp does not catch the good video clip. I expect yt-dlp to catch the main video in the page : https://www.leparisien.fr/environnement/video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU.php

**Comment by dirkf** [comment]
This is actually about Dailymotion embedding which is breaking here for several reasons.

First, it seems that the `.../crawler/...` URL in the ld+json needs to be barred or specially handled in the DM extractor, since the current tactics get media links that look valid but give 404, by treating `crawler` as a username. If it's added as an alternative to `embed` in the `_VALID_URL`s for `DailymotionIE` and `DailymotionUserIE`, extraction succeeds.
```diff
--- old/yt_dlp/extractor/dailymotion.py
+++ new/yt_dlp/extractor/dailymotion.py
@@ -93,7 +93,7 @@
     _VALID_URL = r'''(?ix)
                     https?://
                         (?:
-                            (?:(?:www|touch|geo)\.)?dailymotion\.[a-z]{2,3}/(?:(?:(?:(?:embed|swf|\#)/)|player\.html\?)?video|swf)|
+                            (?:(?:www|touch|geo)\.)?dailymotion\.[a-z]{2,3}/(?:(?:(?:(?:embed|swf|crawler|\#)/)|player\.html\?)?video|swf)|
                             (?:www\.)?lequipe\.fr/video
                         )
                         [/=](?P<id>[^/?_&]+)(?:.+?\bplaylist=(?P<playlist_id>x[0-9a-z]+))?
@@ -385,7 +385,7 @@
 
 class DailymotionUserIE(DailymotionPlaylistBaseIE):
     IE_NAME = 'dailymotion:user'
-    _VALID_URL = r'https?://(?:www\.)?dailymotion\.[a-z]{2,3}/(?!(?:embed|swf|#|video|playlist)/)(?:(?:old/)?user/)?(?P<id>[^/]+)'
+    _VALID_URL = r'https?://(?:www\.)?dailymotion\.[a-z]{2,3}/(?!(?:embed|swf|crawler|#|video|playlist)/)(?:(?:old/)?user/)?(?P<id>[^/]+)'
     _TESTS = [{
         'url': 'https://www.dailymotion.com/user/nqtv',
         'info_dict': {
```

However, if that didn't work, the DM extractor would need to find the DM `<iframe>`s, one of which appears with class `dailymotion-player` in the page, but doesn't exist in the non-JS page. It does however exist in the Fusion hydration JS, as quoted HTML (at `promo_items.lead_art_dailymotion.embed.config.html`).
```json
"<iframe frameborder=\"0\" width=\"480\" height=\"269\" src=\"https://www.dailymotion.com/embed/video/x8u4owg\" allowfullscreen allow=\"autoplay\"></iframe>",
```
In this form the embed URL should be found: in the JS page the URL is like `https://geo.dailymotion.com/player/x6jz7.html?video=x8u4owg...` and wouldn't match the existing `_EMBED_REGEX` and `_VALID_URL` for `DailymotionIE`.

**Comment by pzhlkj6612** [comment]
The version 2024.08.06 seems to work fine with the URL:

```
[generic] Extracting URL: https://www.leparisien.fr/environnement/video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU.php 
[generic] video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU: Downloading webpage
WARNING: [generic] Falling back on generic information extractor 
[generic] video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU: Extracting information 
[debug] Looking for embeds
[debug] Identified a JSON LD 
[dailymotion:user] Extracting URL: https://www.dailymotion.com/crawler/video/x8u4owg#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22video-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU%22%2C+%22to_generic%22%3A+true%2C+%22referer%22%3A+%22https%3A%2F%2Fwww.leparisien.fr%2Fenvironnement%2Fvideo-le-veloto-la-voiture-a-pedales-qui-aimerait-se-faire-une-place-sur-les-routes-09-03-2024-KCYMCPM4WFHJXMSKBUI66UNFPU.php%22%7D
[download] Downloading playlist: VIDÉO. Le « véloto », la voiture à pédales qui aimerait se faire une place sur les routes
[dailymotion:user] crawler: Downloading page 1 
[info] Available thumbnails for crawler: 
ID Width   Height  URL
0  unknown unknown https://s1.dmcdn.net/v/VsLKG1bx7sAuk4se-/x360
[info] Writing playlist metadata as JSON to: VIDÉO. Le « véloto », la voiture à pédales qui aimerait se faire une place sur les routes [crawler] [NA].info.json
[dailymotion:user] Playlist VIDÉO. Le « véloto », la voiture à pédales qui aimerait se faire une place sur les routes: Downloading 1 items of 1
[download] Downloading item 1 of 1
[dailymotion] Extracting URL: https://www.dailymotion.com/video/x36ni 
[dailymotion] x36ni: Downloading media JSON metadata
[dailymotion] x36ni: Downloading metadata JSON 
[dailymotion] x36ni: Downloading m3u8 information 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id 
x36ni has no thumbnails
x36ni has no subtitles
[info] Available formats for x36ni:
ID       EXT RESOLUTION │   FILESIZE  TBR PROTO │ VCODEC      ACODEC
───────────────────────────────────────────────────────────────────────
hls-380  mp4 320x240    │ ~449.77KiB 461k m3u8  │ avc1.42001e mp4a.40.2
http-380 mp4 320x240    │ ≈449.77KiB 461k http  │ avc1.42001e mp4a.40.2
[debug] Default format spec: bestvideo*+bestaudio/best
[info] x36ni: Downloading 1 format(s): http-380
[info] Writing video metadata as JSON to: Test webcam powerbook FNAC [x36ni] [http-380].info.json
[info] Writing updated playlist metadata as JSON to: VIDÉO. Le « véloto », la voiture à pédales qui aimerait se faire une place sur les routes [crawler] [NA].info.json 
[download] Finished downloading playlist: VIDÉO. Le « véloto », la voiture à pédales qui aimerait se faire une place sur les routes

```

.
