### ISSUE TITLE
[Broken] pbs.py Extractor (Geo-Verification-Proxy is Broken)

### ISSUE THREAD

**Issue by ohmybahgosh** [yt-dlp/yt-dlp#944]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```bash
root@000 ~ # yt-dlp 'https://www.pbs.org/wgbh/frontline/film/america-after-9-11/' --verbose --geo-verification-proxy PRIVATE --cookies=/root/.cookies/PBS.txt --simulate
[debug] User config file: /root/yt-dlp.conf
[debug] User config: ['--retries', '5', '--extractor-retries', '5', '--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-N50', '--geo-verification-proxy', 'PRIVATE', '-f', 'bv+ba/b', '--embed-metadata', '--embed-thumbnail', '--no-part']
[debug] Home config file: yt-dlp.conf
[debug] Home config: ['--retries', '5', '--extractor-retries', '5', '--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-N50', '--geo-verification-proxy', 'PRIVATE', '-f', 'bv+ba/b', '--embed-metadata', '--embed-thumbnail', '--no-part']
[debug] Command-line config: ['https://www.pbs.org/wgbh/frontline/film/america-after-9-11/', '--verbose', '--geo-verification-proxy', 'PRIVATE', '--cookies=/root/.cookies/PBS.txt', '--simulate']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-8-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg v1.27-6-ge0542c4, ffprobe v1.27-6-ge0542c4, phantomjs 1.9.2, rtmpdump 2.4
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 6.228.23.102 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[debug] [pbs] Extracting URL: https://www.pbs.org/wgbh/frontline/film/america-after-9-11/
[pbs] america-after-9-11: Downloading webpage
[pbs] america-after-9-11: Downloading widget/partnerplayer page
[pbs] america-after-9-11: Downloading portalplayer page
ERROR: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1218, in wrapper
return func(self, *args, **kwargs)
File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1243, in __extract_info
ie_result = ie.extract(url)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/pbs.py", line 665, in _real_extract
rating_str = info.get('rating')
AttributeError: 'NoneType' object has no attribute 'get'
```

## Description

PBS extractor no longer is working with the geo-verification-proxy when you're indeed on a non US connection (and using a WORKING U.S. proxy).

It is working just fine on a U.S. based connection WITH the geo-verification-proxy flag in use:
```bash
root in ~ via  v3.9.7
✦ ❯ yt-dlp 'https://www.pbs.org/wgbh/frontline/film/america-after-9-11/' --verbose --geo-verification-proxy PRIVATE --cookies=/root/.cookies/PBS.txt --simulate
[debug] User config file: /root/yt-dlp.conf
[debug] User config: ['--retries', '3', '--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-N40', '-f', 'bv+ba/b', '--add-metadata', '--write-all-thumbnails', '--embed-thumbnail']
[debug] Home config file: yt-dlp.conf
[debug] Home config: ['--retries', '3', '--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-N40', '-f', 'bv+ba/b', '--add-metadata', '--write-all-thumbnails', '--embed-thumbnail']
[debug] Command-line config: ['https://www.pbs.org/wgbh/frontline/film/america-after-9-11/', '--verbose', '--geo-verification-proxy', 'PRIVATE', '--cookies=/root/.cookies/PBS.txt', '--simulate']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 (zip)
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.10.0-kali9-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4-5, ffprobe 4.4-5, phantomjs 1.9.7, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 6.209.183.52 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[debug] [pbs] Extracting URL: https://www.pbs.org/wgbh/frontline/film/america-after-9-11/
[pbs] america-after-9-11: Downloading webpage
[pbs] america-after-9-11: Downloading widget/partnerplayer page
[pbs] america-after-9-11: Downloading portalplayer page
[pbs] america-after-9-11: Downloading 0 video url info
[pbs] america-after-9-11: Downloading m3u8 information
WARNING: [pbs] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[pbs] america-after-9-11: Downloading 1 video url info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 3058248068: Downloading 1 format(s): hls-6912
```

...and WITHOUT the flag (also on a U.S. based connection):
```bash
root in ~ via  v3.9.7
✦ ❯ yt-dlp 'https://www.pbs.org/wgbh/frontline/film/america-after-9-11/' --verbose --cookies=/root/.cookies/PBS.txt --simulate
[debug] User config file: /root/yt-dlp.conf
[debug] User config: ['--retries', '3', '--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-N40', '-f', 'bv+ba/b', '--add-metadata', '--write-all-thumbnails', '--embed-thumbnail']
[debug] Home config file: yt-dlp.conf
[debug] Home config: ['--retries', '3', '--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-N40', '-f', 'bv+ba/b', '--add-metadata', '--write-all-thumbnails', '--embed-thumbnail']
[debug] Command-line config: ['https://www.pbs.org/wgbh/frontline/film/america-after-9-11/', '--verbose', '--cookies=/root/.cookies/PBS.txt', '--simulate']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 (zip)
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.10.0-kali9-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4-5, ffprobe 4.4-5, phantomjs 1.9.7, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 6.217.177.223 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[debug] [pbs] Extracting URL: https://www.pbs.org/wgbh/frontline/film/america-after-9-11/
[pbs] america-after-9-11: Downloading webpage
[pbs] america-after-9-11: Downloading widget/partnerplayer page
[pbs] america-after-9-11: Downloading portalplayer page
[pbs] america-after-9-11: Downloading 0 video url info
[pbs] america-after-9-11: Downloading m3u8 information
WARNING: [pbs] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[pbs] america-after-9-11: Downloading 1 video url info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 3058248068: Downloading 1 format(s): hls-6912
```

**Comment by pukkandan** [comment]
Are you sure the issue isn't with the specific proxy? Show log with `-v --write-pages` and attach the .dump files created. Note that the dump files may have private information. You can DM them to me (discord/email) if needed

**Comment by pukkandan** [comment]
Closed due to inactivity
