### ISSUE TITLE
[goplay] Postprocessing: Invalid data found when processing input

### ISSUE THREAD

**Issue by emversch** [yt-dlp/yt-dlp#9476]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Belgium

### Provide a description that is worded well enough to be understood

When trying to download video's from Goplay (series De Mol), the extractor successfully downloads the video and audio files but fails at merging them.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.goplay.be/video/de-mol/de-mol-s10/de-mol-s10-aflevering-5#autoplay']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: sqlite3-3.40.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[GoPlay] Logging in
[GoPlay] Authenticating username
[GoPlay] Authenticating password
[GoPlay] Extracting URL: https://www.goplay.be/video/de-mol/de-mol-s10/de-mol-s10-aflevering-5#autoplay
[GoPlay] de-mol-s10-aflevering-5: Downloading webpage
[GoPlay] e1780884-9f7f-4a4d-b4e9-daa8115a1066: Downloading JSON metadata
[GoPlay] e1780884-9f7f-4a4d-b4e9-daa8115a1066: Downloading JSON metadata
[GoPlay] e1780884-9f7f-4a4d-b4e9-daa8115a1066: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] e1780884-9f7f-4a4d-b4e9-daa8115a1066: Downloading 1 format(s): b7dfe142-0afc-4665-a919-0a106a098729+8a6992e7-974e-495a-b330-207220350470
[debug] Invoking dashsegments downloader on "https://dai.google.com/ondemand/dash/content/2615619/vid/10148627762453527/GRQ/streams/6c4407e4-7f58-44a3-bc89-6992fec2ff4d/manifest.mpd"
[dashsegments] Total fragments: 2327
[download] Destination: S10 - Aflevering 5 [e1780884-9f7f-4a4d-b4e9-daa8115a1066].fb7dfe142-0afc-4665-a919-0a106a098729.mp4
[download] 100% of    2.39GiB in 00:08:02 at 5.06MiB/s
[debug] Invoking dashsegments downloader on "https://dai.google.com/ondemand/dash/content/2615619/vid/10148627762453527/GRQ/streams/6c4407e4-7f58-44a3-bc89-6992fec2ff4d/manifest.mpd"
[dashsegments] Total fragments: 2327
[download] Destination: S10 - Aflevering 5 [e1780884-9f7f-4a4d-b4e9-daa8115a1066].f8a6992e7-974e-495a-b330-207220350470.m4a
[download] 100% of   67.77MiB in 00:02:34 at 449.24KiB/s
[Merger] Merging formats into "S10 - Aflevering 5 [e1780884-9f7f-4a4d-b4e9-daa8115a1066].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:S10 - Aflevering 5 [e1780884-9f7f-4a4d-b4e9-daa8115a1066].fb7dfe142-0afc-4665-a919-0a106a098729.mp4' -i 'file:S10 - Aflevering 5 [e1780884-9f7f-4a4d-b4e9-daa8115a1066].f8a6992e7-974e-495a-b330-207220350470.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:S10 - Aflevering 5 [e1780884-9f7f-4a4d-b4e9-daa8115a1066].temp.mp4'
[debug] ffmpeg version 5.1.4-0+deb12u1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55a50fa7bb40] error reading header
file:S10 - Aflevering 5 [e1780884-9f7f-4a4d-b4e9-daa8115a1066].fb7dfe142-0afc-4665-a919-0a106a098729.mp4: Invalid data found when processing input

ERROR: Postprocessing: file:S10 - Aflevering 5 [e1780884-9f7f-4a4d-b4e9-daa8115a1066].fb7dfe142-0afc-4665-a919-0a106a098729.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "/home/emversch/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3512, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emversch/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3694, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emversch/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3676, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emversch/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3654, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/home/emversch/.local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emversch/.local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/home/emversch/.local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 839, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/emversch/.local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 329, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emversch/.local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 367, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:S10 - Aflevering 5 [e1780884-9f7f-4a4d-b4e9-daa8115a1066].fb7dfe142-0afc-4665-a919-0a106a098729.mp4: Invalid data found when processing input
```

**Comment by emversch** [comment]
note: I've seen the following bug report https://github.com/yt-dlp/yt-dlp/issues/8641. Even though I'm not using ffmpeg version 6.x (I'm using ffmpeg version 5.1.4-0 (Debian default) ), I'll close this issue and I'll try to figure out how to install a newer version of ffmpeg on Debian.
