### ISSUE TITLE
[vimeo] 404 error with `--write-subs` and download aborts

### ISSUE THREAD

**Issue by kiri35** [yt-dlp/yt-dlp#9486]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

subtitle file is listet:
```
$ yt-dlp --list-subs   <URL>
[vimeo] Extracting URL: …
[vimeo] 914359704: Downloading webpage
[vimeo] 914359704: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 914359704: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 914359704: Downloading fastly_skyfire m3u8 information
[vimeo] 914359704: Downloading fastly_skyfire m3u8 information
[vimeo] 914359704: Downloading akfire_interconnect_quic MPD information
[vimeo] 914359704: Downloading akfire_interconnect_quic MPD information
[vimeo] 914359704: Downloading fastly_skyfire MPD information
[vimeo] 914359704: Downloading fastly_skyfire MPD information
[info] Available subtitles for 914359704:
Language     Formats
de-x-autogen vtt, vtt, vtt
```
But with: `yt-dlp -f bv+ba/b  --sub-langs "all" --write-subs <URL>` no video and no subtitle-file is downloaded.
This `yt-dlp -f bv+ba/b <URL>`  works: the video  is downloaded.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'bv+ba/b', '--sub-langs', 'all', '--write-subs', 'https://player.vimeo.com/video/914359704']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (zip)
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.6.16-2-MANJARO-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.05.07, pycrypto-3.20.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://player.vimeo.com/video/914359704
[vimeo] 914359704: Downloading webpage
[vimeo] 914359704: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 914359704: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 914359704: Downloading fastly_skyfire m3u8 information
[vimeo] 914359704: Downloading fastly_skyfire m3u8 information
[vimeo] 914359704: Downloading akfire_interconnect_quic MPD information
[vimeo] 914359704: Downloading akfire_interconnect_quic MPD information
[vimeo] 914359704: Downloading fastly_skyfire MPD information
[vimeo] 914359704: Downloading fastly_skyfire MPD information
[info] 914359704: Downloading subtitles: de-x-autogen
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] 914359704: Downloading 1 format(s): hls-fastly_skyfire_sep-477+dash-fastly_skyfire_sep-audio-2005dd64
[info] Writing video subtitles to: 22_Dirk Revenstorf- Aktivierung des Unbewussten in Trance und Traum [914359704].de-x-autogen.vtt
[debug] Invoking http downloader on "https://vimeo.com/texttrack/136025336.vtt?token=65f83271_0xa3fe7b1fd4d7987c754f51eca3afbcfb444e2994"
ERROR: Unable to download video subtitles for 'de-x-autogen': HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4278, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3155, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4101, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 115, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 326, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_requests.py", line 351, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1594, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1750, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1809, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2968, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3222, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4286, in _write_subtitles
    raise DownloadError(msg)
yt_dlp.utils.DownloadError: Unable to download video subtitles for 'de-x-autogen': HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
The subs don't work in browser either, I get the same 404 error.

**Comment by kiri35** [comment]
The main problem is not the subtitles, which are not downloaded. The main problem is that the videoclip download is not working.

**Comment by bashonly** [comment]
The video is not downloading because the subtitle download is throwing an error. That's why the video download works without `--write-subs`. But there are no subtitles for this video -- you can verify this in your web browser. So the workaround is to just not pass `--write-subs`

**Comment by pukkandan** [comment]
OP is correct. Failure to download subs should not cause video to abort without `--abort-on-error`. Similar to other pre-processing, the error should just re-raise after video download

**Comment by kiri35** [comment]
> --write-subs

`--write-subs` is in my bash script. Therefore I need a possibility that the video is downloaded although the subtitle is missing at the provider.

**Comment by bashonly** [comment]
possibly fixed by #8169

**Comment by kiri35** [comment]
> --abort-on-error

This sounds interessting. I hope i can bring it to run … i will read …

**Comment by kiri35** [comment]
> OP is correct. Failure to download subs should not cause video to abort without `--abort-on-error`. Similar to other pre-processing, the error should just re-raise after video download

Yes, that is what i mean :-)

**Comment by october262** [comment]
there are subtitles - https://player.vimeo.com/texttrack/136025336.vtt?token=65f8d056_0xc7ea97ebe3e16bf19ea80089fca297c47e48e579
but it gives a 404 error not found if you try downloading them

**Comment by kiri35** [comment]
> --abort-on-error

`yt-dlp -f bv+ba/b  --sub-langs "all" --write-subs --no-abort-on-error <URL>` dosn't work.
