### ISSUE TITLE
yt-dlp with asyncio multiprocessing

### ISSUE THREAD

**Issue by stefanodvx** [yt-dlp/yt-dlp#9487]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This is not a bug of yt-dlp itself, and the version of the program is not important. I'd like to use yt-dlp API with python asyncio multiprocessing. This is my current code:
```py3
ydl = YoutubeDL({
    "quiet": True,
    "no_warnings": True,
    "ignoreerrors": True,
})
loop = asyncio.get_running_loop()
with ProcessPoolExecutor() as exc:
  return await loop.run_in_executor(exc, functools.partial(ydl.extract_info, url=url, download=False))
```
Whenever I try to extract info, no matter what I get this error:
```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object
```

**Comment by stefanodvx** [comment]
Working perfectly fine. Thanks.
