### ISSUE TITLE
[Broken] NBC/Platform broken report for a single episode of Brooklyn 99

### ISSUE THREAD

**Issue by taco82** [yt-dlp/yt-dlp#949]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

root@yt:~# /usr/local/bin/yt-dlp --verbose -o '/root/videos/S%(season_number)sE%(episode_number)s-%(title)s.%(ext)s' --ffmpeg-location /usr/bin/ffmpeg "https://www.nbc.com/brooklyn-nine-nine/video/game-of-boyles/9000167059"
[debug] Command-line config: ['--verbose', '-o', '/root/videos/S%(season_number)sE%(episode_number)s-%(title)s.%(ext)s', '--ffmpeg-location', '/usr/bin/ffmpeg', 'https://www.nbc.com/brooklyn-nine-nine/video/game-of-boyles/9000167059']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-84-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [NBC] Extracting URL: https://www.nbc.com/brooklyn-nine-nine/video/game-of-boyles/9000167059
[NBC] 9000167059: Downloading JSON metadata
[NBC] 9000167059: Downloading JSON metadata
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/NnzsPC/media/guid/2410887629/9000167059?mbr=true&manifest=m3u#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 9000167059: Downloading SMIL data
[ThePlatform] 9000167059: Downloading m3u8 information
WARNING: [ThePlatform] Failed to download m3u8 information: HTTP Error 404: Not Found
[ThePlatform] 9000167059: Downloading JSON metadata
ERROR: [ThePlatform] 9000167059: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1252, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1350, in process_ie_result
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1298, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2177, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 849, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ThePlatform] 9000167059: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

Download of Brooklyn 99 episode from NBC is not working.  Note other episodes in the same series download fine, so not sure if this is 1-off error on the server side, however, it is viewable in a browser, so whatever broke yt-dlp didn't affect firefox playback.  Maybe some sort of A/B difference?  Mainly reported due request in the output.

**Comment by taco82** [comment]
Seems to be the same bug report as #1032.  Feel free to close this as a dupe since that one has gotten eyes working on it.
