### ISSUE TITLE
[Broken] ERROR: [HiDive] Unable to extract login form;

### ISSUE THREAD

**Issue by rmiddle** [yt-dlp/yt-dlp#950]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.09.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
[debug] Command-line config: ['--verbose', '--all-subs', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v', '--cookies', 'cookies.txt', 'https://www.hidive.com/stream/why-the-hell-are-you-here-teacher/s01e001']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-84-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: keyring, pycryptodome, sqlite
[debug] Proxy map: {}
[HiDive] None: Downloading webpage
ERROR: [HiDive] Unable to extract login form; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 582, in extract
    self.initialize()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 490, in initialize
    self._real_initialize()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/hidive.py", line 45, in _real_initialize
    form = self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1147, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract login form; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 582, in extract
    self.initialize()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 490, in initialize
    self._real_initialize()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/hidive.py", line 45, in _real_initialize
    form = self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1147, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract login form; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1239, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 600, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [HiDive] Unable to extract login form; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE
From what I can tell hidive changed there login screen breaking the existing script.

**Comment by rmiddle** [comment]
Was a corrupt cookie.txt file.  Once I removed to old cookie.txt file it got past that error.
