### ISSUE TITLE
ebalka.nl after updating the site, broken download

### ISSUE THREAD

**Issue by Geksli** [yt-dlp/yt-dlp#9500]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

[generic] Extracting URL: https://g.ebalka.nl/videos/138714/tihiy-trah-prodoljenie-2/
[generic] tihiy-trah-prodoljenie-2: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] tihiy-trah-prodoljenie-2: Extracting information
WARNING: [generic] Untested major version (3.8.1) in player engine - download may fail.
ERROR: [generic] Unable to extract flashvars; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Portable config "H:\tmp\YoutubeDL\yt-dlp.conf": []
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-02-24-git-8ef03c2ff1-full_build-www.gyan.dev (setts), ffprobe 2022-02-24-git-8ef03c2ff1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
```

**Comment by bashonly** [comment]
please share a verbose log (add `-vU` to your *download* command and copy/paste the full output)

> after updating the site

so it used to work with the generic extractor?

**Comment by Geksli** [comment]
> please share a verbose log (add `-vU` to your _download_ command and copy/paste the full output)
> 
> > after updating the site
> 
> so it used to work with the generic extractor?

a week ago work perfectly, they changed design and some backend probably and now cant download

H:\tmp\YoutubeDL>y -vU https://g.ebalka.nl/videos/138714/tihiy-trah-prodoljenie-2/
[debug] Command-line config: ['-vU', 'https://g.ebalka.nl/videos/138714/tihiy-trah-prodoljenie-2/']
[debug] Portable config "H:\tmp\YoutubeDL\yt-dlp.conf": []
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-02-24-git-8ef03c2ff1-full_build-www.gyan.dev (setts), ffprobe 2022-02-24-git-8ef03c2ff1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://g.ebalka.nl/videos/138714/tihiy-trah-prodoljenie-2/
[generic] tihiy-trah-prodoljenie-2: Downloading webpage
ERROR: [generic] Unable to download webpage: EOF occurred in violation of protocol (_ssl.c:1131) (caused by SSLError('EOF occurred in violation of protocol (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\generic.py", line 2392, in _real_extract
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1099, in _validate_conn
  File "urllib3\connection.py", line 653, in connect
  File "urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 445, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 314, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 530, in send
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4101, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 326, in send
  File "yt_dlp\networking\_requests.py", line 332, in _send
yt_dlp.networking.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

**Comment by dirkf** [comment]
The site uses the KVS player but without the expected pattern `var flashvars = {...}`. Instead, an apparently random name is used and passed as the 4th parameter of the `kt_player()` invocation. I patched this temporarily upstream by matching and passing the name of the flashvars from the detection code into the KS extraction with a success.

Work-around: for video id nnn, get `https://www.ebalka.video/embed/nnn`.

Also, NSFW.
