### ISSUE TITLE
[Broken] HiDive ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by rmiddle** [yt-dlp/yt-dlp#952]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.09.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
[debug] Command-line config: ['-f', 'en_hv_ud-hls-4594', '--verbose', '--all-subs', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v', '--cookies', 'cookies.txt', 'https://www.hidive.com/stream/why-the-hell-are-you-here-teacher/s01e001']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-84-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: keyring, pycryptodome, sqlite
[debug] Proxy map: {}
[HiDive] None: Downloading webpage
[HiDive] Logging in
[debug] [HiDive] Extracting URL: https://www.hidive.com/stream/why-the-hell-are-you-here-teacher/s01e001
[HiDive] why-the-hell-are-you-here-teacher/s01e001: Downloading JSON metadata
[HiDive] why-the-hell-are-you-here-teacher/s01e001: Downloading m3u8 information
[HiDive] why-the-hell-are-you-here-teacher/s01e001: Downloading m3u8 information
[HiDive] why-the-hell-are-you-here-teacher/s01e001: Downloading m3u8 information
[HiDive] why-the-hell-are-you-here-teacher/s01e001: Downloading m3u8 information
[HiDive] why-the-hell-are-you-here-teacher/s01e001: Downloading m3u8 information
[HiDive] why-the-hell-are-you-here-teacher/s01e001: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en
[info] why-the-hell-are-you-here-teacher/s01e001: Downloading 1 format(s): en_hv_ud-hls-4594
[info] Writing video subtitles to: why-the-hell-are-you-here-teacher_s01e001 [why-the-hell-are-you-here-teacher_s01e001].en.vtt
[debug] Invoking downloader on "https://www.hidive.com/caption/vtt/d5bd5e0ecb95551c73e2822a0f75e2af295eea62/WHT_s01e001_tv_hv_ud_ja_en_v00.vtt"
[download] why-the-hell-are-you-here-teacher_s01e001 [why-the-hell-are-you-here-teacher_s01e001].en.vtt has already been downloaded
[download] 100% of 29.79KiB
[debug] Invoking downloader on "https://www.hidive.com/manifest/child/d5bd5e0ecb95551c73e2822a0f75e2af295eea62/WHT_s01e001_tv_hv_ud_en_xx_HLS1080p_16x9_00_v.m3u8?#="
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 76
[download] Destination: why-the-hell-are-you-here-teacher_s01e001 [why-the-hell-are-you-here-teacher_s01e001].mp4
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 2 (attempt 10 of 10) ...
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2798, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2461, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 386, in download
    return self.real_download(filename, info_dict), True
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/hls.py", line 347, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 423, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, frag_content), frag_index, ctx)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 382, in decrypt_fragment
    decrypt_info['KEY'] = decrypt_info.get('KEY') or self.ydl.urlopen(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3218, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```

## Description

WRITE DESCRIPTION HERE
I have tried several different videos and formats and still getting the same error.

**Comment by october262** [comment]
once you are signed in, try using the cookies command.

**Comment by pukkandan** [comment]
Try without cookies. Some sites may have issues when using both -u -p and cookies

**Comment by rmiddle** [comment]
> once you are signed in, try using the cookies command.

I was using the Cookie command.

**Comment by rmiddle** [comment]
> Try without cookies. Some sites may have issues when using both -u -p and cookies

I have tired without Cookies.  I have used .netrc instead of username / password.  I have tired with and without the -f option.  I am open to attempting more switches

**Comment by rmiddle** [comment]
I have looked and there is no How-To or Documentation on how one resolves an account-needed label?

**Comment by Ashish0804** [comment]
You can provide the account to members or yt-dlp or contributors or any other dev ofc assuming they show interest to work on this.
Also I recommend you set a random password on the account and then change it once testing is over.
The sharing part should be done over discord DMs or email.

**Comment by rmiddle** [comment]
> You can provide the account to members or yt-dlp or contributors or any other dev ofc assuming they show interest to work on this.
> Also I recommend you set a random password on the account and then change it once testing is over.
> The sharing part should be done over discord DMs or email.

I have reset my password and jumped into discord to see if there is anyone who can help me.
