### ISSUE TITLE
www.xiaohongshu.com

### ISSUE THREAD

**Issue by onmyouji** [yt-dlp/yt-dlp#9529]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

This is a Chinese website, but I'm accessing it from Indonesia

### Example URLs

Single video: https://www.xiaohongshu.com/explore/6411cf99000000001300b6d9

### Provide a description that is worded well enough to be understood

I'd like to request support for a new site.

Example URL: https://www.xiaohongshu.com/explore/6411cf99000000001300b6d9

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.xiaohongshu.com/explore/6411cf99000000001300b6d9']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-36-gc5039e158d-20231023 (setts), ffprobe n6.0-36-gc5039e158d-20231023, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.xiaohongshu.com/explore/6411cf99000000001300b6d9
[generic] 6411cf99000000001300b6d9: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 6411cf99000000001300b6d9: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.xiaohongshu.com/explore/6411cf99000000001300b6d9
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1594, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1729, in __extract_info
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\generic.py", line 2530, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.xiaohongshu.com/explore/6411cf99000000001300b6d9
```

**Comment by qingchunnh** [comment]
Use your browser F12 console, select network and click Media, that's the video you need

**Comment by HobbyistDev** [comment]
It seems the video data is in webpage. We can get the information in the `script` tag in `window.__INITIAL_STATE__` and then in `note.noteDetailMap.<display_id>.note`. The video info is in `video.media.stream` which has some key like `h264`, `h265`, `av1`.
Here is the sample of the `stream`:
```json
{
	"stream": {
		"h264": [{
			"audioDuration": 101725,
			"hdrType": 0,
			"duration": 101726,
			"width": 720,
			"qualityType": "HD",
			"fps": 30,
			"ssim": 0,
			"format": "mp4",
			"height": 1280,
			"masterUrl": "http:\u002F\u002Fsns-video-hw.xhscdn.com\u002Fstream\u002F110\u002F258\u002F01e411ceb6b7448b0103700386e595222a_258.mp4",
			"weight": 62,
			"streamType": 258,
			"videoDuration": 101700,
			"videoCodec": "h264",
			"audioChannels": 2,
			"rotate": 0,
			"psnr": 0,
			"avgBitrate": 1191807,
			"videoBitrate": 1129434,
			"streamDesc": "X264_MP4",
			"defaultStream": 0,
			"size": 15154727,
			"volume": 0,
			"backupUrls": ["http:\u002F\u002Fsns-video-bd.xhscdn.com\u002Fstream\u002F110\u002F258\u002F01e411ceb6b7448b0103700386e595222a_258.mp4", "http:\u002F\u002Fsns-video-qc.xhscdn.com\u002Fstream\u002F110\u002F258\u002F01e411ceb6b7448b0103700386e595222a_258.mp4?sign=a4dee8071b9567bfa239d4739f1555fb&t=66141354", "http:\u002F\u002Fsns-video-al.xhscdn.com\u002Fstream\u002F110\u002F258\u002F01e411ceb6b7448b0103700386e595222a_258.mp4", "http:\u002F\u002Fsns-video-hw.xhscdn.net\u002Fstream\u002F110\u002F258\u002F01e411ceb6b7448b0103700386e595222a_258.mp4", "https:\u002F\u002Frcdn.xiaohongshu.com\u002Fstream\u002F110\u002F258\u002F01e411ceb6b7448b0103700386e595222a_258.mp4?sign=a4dee8071b9567bfa239d4739f1555fb&t=66141354"],
			"vmaf": -1,
			"audioCodec": "aac",
			"audioBitrate": 56065
		}],
		"h265": [],
		"av1": []
	}
````
As we can see, we can extract the url in `h264.masterUrls` or `h264.backupUrls`.
<details>
<summary>yt-dlp log</summary>

```shell
>python -m yt_dlp -v "https://vod.kringvarp.fo/redirect/video/_definst_/smil:smil/video/DOK01396.smil?type=m3u8" --test 
[debug] Command-line config: ['-v', 'https://vod.kringvarp.fo/redirect/video/_definst_/smil:smil/video/DOK01396.smil?type=m3u8', '--test']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: b15b0c1d2 
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.39.4, urllib3-2.2.1, websockets-12.0     
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1809 extractors 
[generic] Extracting URL: https://vod.kringvarp.fo/redirect/video/_definst_/smil:smil/video/DOK01396.smil?type=m3u8 
[generic] DOK01396: Downloading webpage
[redirect] Following redirect to https://w-vod-edge2.kringvarp.fo/video/_definst_/smil:smil/video/DOK01396.smil/playlist.m3u8 
[generic] Extracting URL: https://w-vod-edge2.kringvarp.fo/video/_definst_/smil:smil/video/DOK01396.smil/playlist.m3u8
[generic] playlist: Downloading webpage
[debug] Identified a direct video link 
[generic] playlist: Downloading m3u8 information
[generic] playlist: Checking m3u8 live status 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best 
[info] playlist: Downloading 1 format(s): 6170 
[debug] Invoking hlsnative downloader on "https://w-vod-edge2.kringvarp.fo/video/_definst_/smil:smil/video/DOK01396.smil/chunklist_w1607261504_b6170313.m3u8" 
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 154 
[download] Destination: playlist [playlist].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    7.67MiB in 00:00:29 at 268.96KiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:playlist [playlist].mp4"
[debug] ffmpeg command line: ffprobe -show_streams "file:playlist [playlist].mp4" 
[FixupM3u8] Fixing MPEG-TS in MP4 container of "playlist [playlist].mp4" 
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:playlist [playlist].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:playlist [playlist].temp.mp4"

(python_proj) D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp>python -m yt_dlp -v "http://sns-video-hw.xhscdn.com/stream/110/258/01e411ceb6b7448b0103700386e595222a_258.mp4" --test
[debug] Command-line config: ['-v', 'http://sns-video-hw.xhscdn.com/stream/110/258/01e411ceb6b7448b0103700386e595222a_258.mp4', '--test']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: b15b0c1d2 
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.39.4, urllib3-2.2.1, websockets-12.0     
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1809 extractors 
[generic] Extracting URL: http://sns-video-hw.xhscdn.com/stream/110/258/01e411ceb6b7448b0103700386e595222a_258.mp4 
[generic] 01e411ceb6b7448b0103700386e595222a_258: Downloading webpage
[debug] Identified a direct video link 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 01e411ceb6b7448b0103700386e595222a_258: Downloading 1 format(s): mp4
[debug] Invoking http downloader on "http://sns-video-hw.xhscdn.com/stream/110/258/01e411ceb6b7448b0103700386e595222a_258.mp4"
[debug] File locking is not supported. Proceeding without locking 
[download] Destination: 01e411ceb6b7448b0103700386e595222a_258 [01e411ceb6b7448b0103700386e595222a_258].mp4
[download] 100% of   10.00KiB in 00:00:00 at 170.88KiB/s
```
</details>

---
I think the generic extractor should grab video from these tags (especially for the `og:video` meta tag):
```html
<meta name="og:videotime" content="01:42">
<meta name="og:videoquality" content="高清">
 <meta name="og:video" content="https://sns-video-hw.xhscdn.com/stream/110/258/01e411ceb6b7448b0103700386e595222a_258.mp4">
```
