### ISSUE TITLE
[Twitter/X] Fragment downloading fails when tweets are too long

### ISSUE THREAD

**Issue by DCxDESIGN** [yt-dlp/yt-dlp#9545]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Global

### Provide a description that is worded well enough to be understood

Sometimes, I use yt-dlp to download videos attached to tweets on Twitter. Currently, yt-dlp names the downloaded files with the entire tweet content, and during the downloading process, temporary files are generated with names like `[tweet content].[format code].mp4.part-FragN.part`, stored in the same directory. For longer tweets, it's likely to exceed the typical system limit (e.g., around 256 characters in Windows). Even if the tweet length fits within the operating system's filename limit, the suffixes of these temporary files may exceed the limit. When this happens, writing the temporary files fails with an error message:

```
"ERROR: unable to open for writing: [Errno 22] Invalid argument: [FragName]
[download] fragment not found; Skipping fragment N ...
```

In such cases, I have to temporarily add `--restrict-filename` or `--trim-filenames` to avoid this issue. However, I'm wondering if there's a better way to proactively mitigate this problem, such as intelligently restricting the filename length for Twitter content downloads or adjusting the mechanism for naming temporary files.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'chrome', 'https://twitter.com/mizuki2nd_la/status/1772916003405758481', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-03-07-git-97beb63a66-full_build-www.gyan.dev (setts), ffprobe 2024-03-07-git-97beb63a66-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\[USERNAME]\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\[USERNAME]\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 364 cookies from chrome
[debug] cookie version breakdown: {'v10': 364, 'other': 0, 'unencrypted': 0}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[twitter] Extracting URL: https://twitter.com/mizuki2nd_la/status/1772916003405758481
[twitter] 1772916003405758481: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1772915940478578688
[twitter] 1772916003405758481: Downloading m3u8 information
[debug] Sort order given by extractor: res, proto:m3u8, br, size
[debug] Formats sorted by: hasvid, ie_pref, res, proto:m3u8(8), br, size, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1772915940478578688: Downloading 1 format(s): hls-577+hls-audio-128000-Audio
[debug] Invoking hlsnative downloader on "https://video.twimg.com/amplify_video/1772915940478578688/pl/avc1/720x720/Et7gQqJpTRsULFIb.m3u8?container=cmaf"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 8
[download] Destination: 乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位　松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-577.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    1.28MiB in 00:00:01 at 962.10KiB/s
[debug] Invoking hlsnative downloader on "https://video.twimg.com/amplify_video/1772915940478578688/pl/mp4a/128000/p9tQ4c3rtP7wONtF.m3u8?container=cmaf"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 8
[download] Destination: 乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位　松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4
ERROR: unable to open for writing: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発 売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000 松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキング を予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag1.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5057, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5065, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちく ださい🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag1.part'

[download] fragment not found; Skipping fragment 1 ...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発 売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000 松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキング を予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag2.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5057, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5065, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちく ださい🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag2.part'

[download] fragment not found; Skipping fragment 2 ...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発 売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000 松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキング を予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag3.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5057, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5065, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちく ださい🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag3.part'

[download] fragment not found; Skipping fragment 3 ...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発 売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000 松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキング を予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5057, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5065, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちく ださい🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag4.part'

[download] fragment not found; Skipping fragment 4 ...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発 売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000 松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキング を予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag5.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5057, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5065, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちく ださい🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag5.part'

[download] fragment not found; Skipping fragment 5 ...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発 売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000 松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキング を予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag6.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5057, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5065, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちく ださい🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag6.part'

[download] fragment not found; Skipping fragment 6 ...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発 売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000 松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキング を予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag7.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5057, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5065, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちく ださい🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag7.part'

[download] fragment not found; Skipping fragment 7 ...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発 売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000 松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキング を予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag8.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5057, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5065, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちく ださい🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag8.part'

[download] fragment not found; Skipping fragment 8 ...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発 売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000 松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキング を予想しながら次回をお待ちください🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag9.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 591, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 238, in wrapper
  File "yt_dlp\utils\_utils.py", line 5057, in __iter__
  File "yt_dlp\downloader\common.py", line 231, in error_callback
  File "yt_dlp\utils\_utils.py", line 5065, in report_retry
  File "yt_dlp\downloader\common.py", line 240, in wrapper
  File "yt_dlp\downloader\common.py", line 251, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 594, in sanitize_open
OSError: [Errno 22] Invalid argument: '乃木坂46山下美月2nd写真集『ヒロイン』【公式】4月23日発売 - #山下美月2nd写真集 #ヒロイン 特別企画✨ #乃木坂46のうちにしたいこと  「乃木坂46の歴代衣装を着る」TOP10 第9位\u3000松村沙友理さん卒業コンサート衣装  2週にわたって、ランキング形式で毎日お届け中❣️山下さんが考えたランキングは？ランキングを予想しながら次回をお待ちく ださい🤗  🌟Amazon… [1772915940478578688].fhls-audio-128000-Audio.mp4.part-Frag9.part'

[download] fragment not found; Skipping fragment 9 ...
ERROR: The downloaded file is empty
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1030, in main
  File "yt_dlp\__init__.py", line 1020, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3558, in download
  File "yt_dlp\YoutubeDL.py", line 3533, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1583, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1594, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1750, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1809, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2968, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3416, in process_info
  File "yt_dlp\YoutubeDL.py", line 3155, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\hls.py", line 378, in real_download
  File "yt_dlp\downloader\fragment.py", line 527, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 301, in _finish_frag_download
  File "yt_dlp\YoutubeDL.py", line 1061, in report_error
  File "yt_dlp\YoutubeDL.py", line 989, in trouble
```

**Comment by bashonly** [comment]
see #1136

workaround is to add something like `-o "%(title).150B [%(id)s].%(ext)s"` to your config file

**Comment by bashonly** [comment]
>  Is it because I am using Windows?

The exact error message can depend on filesystem, OS, python version, or what function is being called. `[Errno 22] Invalid argument` is what Python throws with your particular set of variables. But that error *could* mean other things besides the filename being too long.

> ...to avoid unnecessary confusion or misunderstanding?

If there was an obvious solution to stop these issues/questions, it would have been implemented a long time ago.
