### ISSUE TITLE
Support Request for spooncast.net

### ISSUE THREAD

**Issue by dfgyuri** [yt-dlp/yt-dlp#9590]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://www.spooncast.net/jp/cast/5950201

### Provide a description that is worded well enough to be understood

VoDs on spooncast.net cannot be downloaded as site is not yet supported. VoDs are purely audio with a thumbnail and are served as .m4a 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.spooncast.net/jp/cast/5950201', '-vU', '--ignore-config']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-6.1.15-1-pve-x86_64-with-glibc2.31 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.spooncast.net/jp/cast/5950201
[generic] 5950201: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 5950201: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.spooncast.net/jp/cast/5950201
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1594, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1729, in __extract_info
  File "yt_dlp/extractor/common.py", line 732, in extract
  File "yt_dlp/extractor/generic.py", line 2530, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.spooncast.net/jp/cast/5950201
```

**Comment by HobbyistDev** [comment]
Not sure if it just happened to me, but i got HTTP 403 Error. The result is same in browser
```shell
>curl -v "https://www.spooncast.net/jp/cast/5950201"
*   Trying 108.138.141.49:443...
* Connected to www.spooncast.net (108.138.141.49) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> GET /jp/cast/5950201 HTTP/1.1
> Host: www.spooncast.net
> User-Agent: curl/8.4.0
> Accept: */*
>
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 403 Forbidden
< Content-Type: text/html
< Content-Length: 118
< Connection: keep-alive
< Server: awselb/2.0
< Date: Thu, 11 Apr 2024 13:38:39 GMT
< X-Cache: Error from cloudfront
< Via: 1.1 2f53da2ba24f7d592b0ae8ca46a81c8a.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: CGK51-P1
< X-Amz-Cf-Id: 4sStlb_KQx3OSQxFSAzn2UqYOXL1By0-VZ2twK3BTW-k2dL6a23_Ig==
<
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
```

Or yt-dlp log:
```shell
>python -m yt_dlp -v "https://www.spooncast.net/jp/cast/5950201"
[debug] Command-line config: ['-v', 'https://www.spooncast.net/jp/cast/5950201']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 31c45e0df 
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.39.4, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors 
[generic] Extracting URL: https://www.spooncast.net/jp/cast/5950201 
[generic] 5950201: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>) 
  File "D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp\yt_dlp\extractor\common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp\yt_dlp\extractor\generic.py", line 2376, in _real_extract     
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp\yt_dlp\extractor\common.py", line 903, in _request_webpage    
    raise ExtractorError(errmsg, cause=err)

  File "D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp\yt_dlp\extractor\common.py", line 890, in _request_webpage    
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp\yt_dlp\YoutubeDL.py", line 4131, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp\yt_dlp\networking\common.py", line 115, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp\yt_dlp\networking\_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp\yt_dlp\networking\common.py", line 335, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\HobbyistDev\dev_folder\python_proj\yt-dlp-related\hobbyist_dev_repo\yt-dlp\yt_dlp\networking\_requests.py", line 350, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
Possibly geo restriction? It plays in browser for me

**Comment by HobbyistDev** [comment]
After checking the traceroute, the ISP seems block me from the website (which i think not really a geoblock)
