### ISSUE TITLE
National Film and Soundtrack Archive of Australia (NFSA, www.nfsa.gov.au)

### ISSUE THREAD

**Issue by egalatea** [yt-dlp/yt-dlp#9593]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Spain, Australia and presumably other European countries/USA/Canada

### Example URLs

[](https://www.nfsa.gov.au/collection/curated/asset/98200-will-power-berlei)

### Provide a description that is worded well enough to be understood

I believe it to be self-explainatory, can't think of anything to add but this is a mandatory field.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\usuario\Downloads> .\yt-dlp.exe --update-to master
Latest version: master@2024.04.01.171621 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.04.01.171621 from yt-dlp/yt-dlp-master-builds)
PS C:\Users\usuario\Downloads> .\yt-dlp.exe -vU https://www.nfsa.gov.au/collection/curated/asset/98200-will-power-berlei
[debug] Command-line config: ['-vU', 'https://www.nfsa.gov.au/collection/curated/asset/98200-will-power-berlei']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.04.01.171621 from yt-dlp/yt-dlp-master-builds [e8032503b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.04.01.171621 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.04.01.171621 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://www.nfsa.gov.au/collection/curated/asset/98200-will-power-berlei
[generic] 98200-will-power-berlei: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 98200-will-power-berlei: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.nfsa.gov.au/collection/curated/asset/98200-will-power-berlei
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1741, in __extract_info
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2530, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nfsa.gov.au/collection/curated/asset/98200-will-power-berlei

PS C:\Users\usuario\Downloads>
```

**Comment by dirkf** [comment]
The video in the page, once you get past a pointless interstitial page, is a Vimeo iframe embed that ought to be detected, or detectable:
```html
<iframe src="https://www.nfsa.gov.au/media/oembed?url=https%3A//vimeo.com/237987070&amp;max_width=760&amp;max_height=426&amp;hash=cM8IsSR4rU_J7fxkJkkc_0waoZ6I06VVMKQF0QOq1xo" frameborder="0" allowtransparency width="760" height="426" class="media-oembed-content" loading="eager" title="Will Power"></iframe>
```
