### ISSUE TITLE
sunroom

### ISSUE THREAD

**Issue by shiva010185** [yt-dlp/yt-dlp#9595]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

usa

### Example URLs

https://app.sunroom.so

### Provide a description that is worded well enough to be understood

Pls provide support to download from sunroom website

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: Unsupported URL: https://app.sunroom.so/posts
```

**Comment by bashonly** [comment]
Please add a proper log and a URL for an individual video instead of just the front page

**Comment by shiva010185** [comment]
yt-dlp https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e
[generic] Extracting URL: https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e
[generic] 8bce3787-8784-445f-838d-b4420f70e21e: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 8bce3787-8784-445f-838d-b4420f70e21e: Extracting information
ERROR: Unsupported URL: https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e

**Comment by shiva010185** [comment]
yt-dlp https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e
[generic] Extracting URL: https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e
[generic] 8bce3787-8784-445f-838d-b4420f70e21e: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 8bce3787-8784-445f-838d-b4420f70e21e: Extracting information
ERROR: Unsupported URL: https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e

**Comment by shiva010185** [comment]
yt-dlp -vU https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e
[debug] Command-line config: ['-vU', 'https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (debian*)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-26-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e
[generic] 8bce3787-8784-445f-838d-b4420f70e21e: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 8bce3787-8784-445f-838d-b4420f70e21e: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1594, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1729, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 2530, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://app.sunroom.so/posts/84c3707a-2397-416d-99c7-da19c1618e40/8bce3787-8784-445f-838d-b4420f70e21e
