### ISSUE TITLE
Noovo.ca

### ISSUE THREAD

**Issue by rgarrigue** [yt-dlp/yt-dlp#9596]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

I can play this video in my browser https://www.noovo.ca/emissions/lamour-est-dans-le-pre/prets-pour-lamour-s10e1, but yt-dlp end up with

> ERROR: Unsupported URL: https://www.noovo.ca/emissions/lamour-est-dans-le-pre/prets-pour-lamour-s10e1

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.noovo.ca/emissions/lamour-est-dans-le-pre/prets-pour-lamour-s10e1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.04.01.224126 from yt-dlp/yt-dlp-master-builds [c59de48e2] (zip)
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.6.19-1-MANJARO-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2024.02.02, requests-2.31.0, sqlite3-3.45.1, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1808 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.04.01.224126 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.04.01.224126 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://www.noovo.ca/emissions/lamour-est-dans-le-pre/prets-pour-lamour-s10e1
[generic] prets-pour-lamour-s10e1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] prets-pour-lamour-s10e1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.noovo.ca/emissions/lamour-est-dans-le-pre/prets-pour-lamour-s10e1
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2530, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.noovo.ca/emissions/lamour-est-dans-le-pre/prets-pour-lamour-s10e1
```

**Comment by HobbyistDev** [comment]
I got geoblocked:
> Une erreur est survenue
> Nous sommes désolés, ce contenu n’est pas disponible dans votre pays. [5004/403.72]

Or if translated to English (using google translate):
> An error has occurred
> We're sorry, this content is not available in your country. [5004/403.72]

**Comment by ajoliveau** [comment]
Content is indeed geolocked, but I have the same issue.
It looks like the url structure and the player that is used on the noovo website changed in the last 7 years since the extractor was written. Looking at extractor/noovo.py it seems like : 
- It's looking for a a /videos url but now it's /emissions
- Even if I change the url pattern, it doesn't work because apparently it used to be a Brightcove player but now it's something different (custom ?)

If someone points me to the right place I can take a shot at updating it, but no idea what kind of player this is

**Comment by bashonly** [comment]
It sounds like the extractor needs to be completely rewritten. Not sure how I can be of much help since I'm geo-blocked. Do you have specific questions about how to work on this?

**Comment by doe1080** [comment]
currently DRM-protected
