### ISSUE TITLE
Can not build yt-dlp on MacOS with PyInstaller 6.5.0  after commit related to curl_cffi

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#9597]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

now I can not build a "portable" version of yt-dlp for myself using pyinstaller. I'm running macOS Sonoma 14.3.1, M1 CPU. Using this script:
/usr/local/bin/python3 ./yt-dlp/bundle/pyinstaller.py --target-architecture universal2

Error at some point says - ModuleNotFoundError: No module named 'curl_cffi'. Could be related to this commit: https://github.com/yt-dlp/yt-dlp/commit/52f5be1f1e0dc45bb397ab950f564721976a39bf#commitcomment-140518969

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
/usr/local/bin/python3 ./yt-dlp/bundle/pyinstaller.py --target-architecture universal2    
Building yt-dlp v2024.03.10 for darwin arm64 with options ['--target-architecture', 'universal2', '--onefile']
Remember to update the version using  "devscripts/update-version.py"
WARNING: Building without lazy_extractors. Run  "devscripts/make_lazy_extractors.py"  to build lazy extractors
Destination: dist/yt-dlp_macos_arm64

Running PyInstaller with ['--name=yt-dlp_macos_arm64', '--icon=devscripts/logo.ico', '--upx-exclude=vcruntime140.dll', '--noconfirm', '--additional-hooks-dir=yt_dlp/__pyinstaller', '--target-architecture', 'universal2', '--onefile', 'yt_dlp/__main__.py']
51 INFO: PyInstaller: 4.8
51 INFO: Python: 3.10.2
57 INFO: Platform: macOS-14.3.1-arm64-arm-64bit
58 INFO: wrote ./yt-dlp/yt-dlp_macos_arm64.spec
59 INFO: UPX is not available.
60 INFO: Extending PYTHONPATH with paths
['./yt-dlp']
128 INFO: checking Analysis
128 INFO: Building Analysis because Analysis-00.toc is non existent
128 INFO: Initializing module dependency graph...
129 INFO: Caching module graph hooks...
133 INFO: Analyzing base_library.zip ...
1815 INFO: Caching module dependency graph...
1868 INFO: running Analysis Analysis-00.toc
1874 INFO: Analyzing ./yt-dlp/yt_dlp/__main__.py
4834 INFO: Processing module hooks...
4834 INFO: Loading module hook 'hook-yt_dlp.py' from './yt-dlp/yt_dlp/__pyinstaller'...
Adding imports: ['yt_dlp.compat._legacy', 'yt_dlp.compat._deprecated', 'yt_dlp.utils._legacy', 'yt_dlp.utils._deprecated', 'Cryptodome', 'websockets.extensions', 'websockets.legacy.http', 'websockets.extensions.base', 'websockets.legacy.auth', 'websockets.headers', 'websockets.legacy', 'websockets.extensions.permessage_deflate', 'websockets.legacy.framing', 'websockets.typing', 'websockets.frames', 'websockets.speedups', 'websockets.legacy.compatibility', 'websockets.client', 'websockets.http11', 'websockets.legacy.server', 'websockets.streams', 'websockets.__main__', 'websockets', 'websockets.datastructures', 'websockets.imports', 'websockets.auth', 'websockets.exceptions', 'websockets.server', 'websockets.legacy.handshake', 'websockets.utils', 'websockets.http', 'websockets.legacy.protocol', 'websockets.connection', 'websockets.version', 'websockets.uri', 'websockets.legacy.client', 'mutagen', 'brotli', 'certifi', 'secretstorage', 'curl_cffi']
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'curl_cffi'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/utils/hooks/__init__.py", line 366, in get_module_file_attribute
    attr = loader.get_filename(package)
AttributeError: 'NoneType' object has no attribute 'get_filename'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 361, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/compat.py", line 606, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "./yt-dlp/yt_dlp/__pyinstaller/hook-yt_dlp.py", line 36, in <module>
    datas = collect_data_files('curl_cffi', includes=['cacert.pem'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/utils/hooks/__init__.py", line 723, in collect_data_files
    pkg_base, pkg_dir = get_package_paths(package)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/utils/hooks/__init__.py", line 518, in get_package_paths
    file_attr = get_module_file_attribute(package)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/utils/hooks/__init__.py", line 383, in get_module_file_attribute
    raise ImportError('Unable to load module attribute') from e
ImportError: Unable to load module attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./yt-dlp/bundle/pyinstaller.py", line 132, in <module>
    main()
  File "./yt-dlp/bundle/pyinstaller.py", line 46, in main
    run_pyinstaller(opts)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 793, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 725, in build
    exec(code, spec_namespace)
  File "./yt-dlp/yt-dlp_macos_arm64.spec", line 7, in <module>
    a = Analysis(['yt_dlp/__main__.py'],
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 277, in __init__
    self.__postinit__()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 155, in __postinit__
    self.assemble()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 445, in assemble
    self.graph.process_post_graph_hooks(self)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 326, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 398, in post_graph
    self._load_hook_module()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 364, in _load_hook_module
    raise ImportErrorWhenRunningHook(self.hook_module_name, self.hook_filename)
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_yt_dlp required by hook for module ./yt-dlp/yt_dlp/__pyinstaller/hook-yt_dlp.py. Please check whether module __PyInstaller_hooks_0_yt_dlp actually exists and whether the hook is compatible with your version of ./yt-dlp/yt_dlp/__pyinstaller/hook-yt_dlp.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.
```

**Comment by bashonly** [comment]
A few things:
1. Try running `python3 -m bundle.pyinstaller` from the project's base directory as [documented in the README](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#standalone-pyinstaller-builds). You can pass args, as well, e.g. `python3 -m bundle.pyinstaller --target-architecture universal2`

2. I'm guessing you don't have `curl_cffi` installed in your build enviroment, but could you clarify this point?

3. The log you shared is from pyinstaller 4.8. Could you also share the pyinstaller 6.5.0 log?

**Comment by someziggyman** [comment]
Ok folks, looks like it's now fixed and working. I apologise  for the confusion, it was far late into the night when I reported it. 
The problem was that for some reason my MacOS kept using an older pyinstaller 4.8 version no mater how hard I tried. I reinstalled and upgraded my python3, upgraded and reinstalled pyinstaller within that latest version of python3, made sure PATH variables are all pointing to correct versions of the packages and it all worked fine. Finally. 

PS. did not have to install curl_cffi separately, it worked somehow or installed it automatically. I have no idea :-) Not a big code savvy guy here as you may guess

**Comment by bashonly** [comment]
Per yt-dlp's `pyinstaller` optional dependency group (and the [Pyinstaller instructions in the README](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#standalone-pyinstaller-builds)), it's advised that MacOS users install Pyinstaller 5.13.2 and all other users install Pyinstaller 6.3.0 or later.

Version 6.3.0 or later should be fine for MacOS if you're **not** bundling `curl_cffi`, but If you want to include it, currently you *need* to use Pyinstaller 5.13.2. And if you want to target `universal2` and bundle `curl_cffi`, then you'll need to fuse your own `universal2` wheel for `curl_cffi` like we do in our build workflow:

https://github.com/yt-dlp/yt-dlp/blob/e8032503b9517465b0e86d776fc1e60d8795d673/.github/workflows/build.yml#L250-L270

We should consider either adding a bundle script that does this, or adding code to `bundle.pyinstaller` that handles this.

**Comment by someziggyman** [comment]
Thanks a lot for this hint! How critical is to include or not include this curl_cffi? what does it do?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#impersonation

It's currently only used for kick.com and so you can probably ignore it. But we will need it for sites in future.
