### ISSUE TITLE
kvf.fo site request

### ISSUE THREAD

**Issue by vman81** [yt-dlp/yt-dlp#9620]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Faroe Islands and Denmark tested

### Example URLs

Single video: https://kvf.fo/sending/mett-fyri-minni?sid=173187
Single video: https://kvf.fo/vit/sjonvarp/2019/11/07/sara-og-dunnan-1-partur

### Provide a description that is worded well enough to be understood

The local public service TV station used to work earlier with some generic settings, but after a site/player redesign no longer works. I do not believe the site has ever been officially supported, as I cannot find the domain mentioned in any open or closed issue, and it is not listed in the supported sites page.

The videos play fine on my browser - Firefox 124 on Fedora 40

The videos do not seem to be region locked, as they work from multiple countries tested - the Faroe Islands and Denmark.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU https://kvf.fo/sending/mett-fyri-minni?sid=173187
[debug] Command-line config: ['-vU', 'https://kvf.fo/sending/mett-fyri-minni?sid=173187']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (zip)
[debug] Python 3.12.2 (CPython x86_64 64bit) - Linux-6.8.2-300.fc40.x86_64-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: none
[debug] Optional libraries: certifi-2023.05.07, requests-2.31.0, sqlite3-3.45.1, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://kvf.fo/sending/mett-fyri-minni?sid=173187
[generic] mett-fyri-minni?sid=173187: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] mett-fyri-minni?sid=173187: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://kvf.fo/sending/mett-fyri-minni?sid=173187
Traceback (most recent call last):
  File "/home/user/./yt-dlp/yt_dlp/YoutubeDL.py", line 1594, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/./yt-dlp/yt_dlp/YoutubeDL.py", line 1729, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/user/./yt-dlp/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/./yt-dlp/yt_dlp/extractor/generic.py", line 2530, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://kvf.fo/sending/mett-fyri-minni?sid=173187
```

**Comment by HobbyistDev** [comment]
From the OP url, we can found the id of the media from one of the `script` tag.
Here's the `script` tag that was refered:
In the first link
```html
<script type="text/javascript>
  (function($) {
      $(document).ready(_start);
   }(jQuery));

   function expand() {
     //console.log('expand');
     //console.log(jQuery('#taknidx'));
     jQuery('#taknidx').slideToggle();
     document.getElementById('taknidx').style.display = 'block';
   }
  ...
  var media = 'DOK01396';
  var created = '2024';
  var title = 'Mett fyri minni (1:3)';
  var mode = 'video';
  var desc = ' Í fyrsta parti vitjar Sunniva Gudmundsdóttir Mortensen plantuommuna í Nólsoy, kokkin Sonna Zachariassen og kondittaran, Malene Fischer Waag.';
  var image = 'https://kvf.fo/sites/default/files/styles/news_xtra_xtra_large/public/dok01396_0051.jpg?itok=VLALCn4M';
</script>
```

Or in the second link:
```html
<script type="text/javascript">
   var mode = 'video'; // Media type
   var media = 'Sara_og_Dunna_01_OK';
   var created = '2019'; // Hetta er "Authored on" i node/greinini
   var title = 'Leykbørn';
   var desc = '';
   var image = 'https://kvf.fo/sites/default/files/styles/news_xtra_xtra_large/public/s1.png?itok=WzBxtBm5';
</script>
```

We can grab the `media` variable's value and set the url like this
`https://vod.kringvarp.fo/redirect/video/_definst_/smil:smil/video/DOK01396.smil?type=m3u8`
which the `DOK01396` from the `media`'s value.

<details>
<summary>yt-dlp log</summary>

```shell
>python -m yt_dlp -v "https://vod.kringvarp.fo/redirect/video/_definst_/smil:smil/video/DOK01396.smil?type=m3u8" --test 
[debug] Command-line config: ['-v', 'https://vod.kringvarp.fo/redirect/video/_definst_/smil:smil/video/DOK01396.smil?type=m3u8', '--test']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: b15b0c1d2 
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.39.4, urllib3-2.2.1, websockets-12.0     
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1809 extractors 
[generic] Extracting URL: https://vod.kringvarp.fo/redirect/video/_definst_/smil:smil/video/DOK01396.smil?type=m3u8 
[generic] DOK01396: Downloading webpage
[redirect] Following redirect to https://w-vod-edge2.kringvarp.fo/video/_definst_/smil:smil/video/DOK01396.smil/playlist.m3u8 
[generic] Extracting URL: https://w-vod-edge2.kringvarp.fo/video/_definst_/smil:smil/video/DOK01396.smil/playlist.m3u8
[generic] playlist: Downloading webpage
[debug] Identified a direct video link 
[generic] playlist: Downloading m3u8 information
[generic] playlist: Checking m3u8 live status 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best 
[info] playlist: Downloading 1 format(s): 6170 
[debug] Invoking hlsnative downloader on "https://w-vod-edge2.kringvarp.fo/video/_definst_/smil:smil/video/DOK01396.smil/chunklist_w1607261504_b6170313.m3u8" 
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 154 
[download] Destination: playlist [playlist].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    7.67MiB in 00:00:29 at 268.96KiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:playlist [playlist].mp4"
[debug] ffmpeg command line: ffprobe -show_streams "file:playlist [playlist].mp4" 
[FixupM3u8] Fixing MPEG-TS in MP4 container of "playlist [playlist].mp4" 
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:playlist [playlist].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:playlist [playlist].temp.mp4"
```

</details>

---
The website only give a little amount of metadata, we probably should use the available `meta` tag and parse with this tag:
```html
<div class="views-field views-field-title">
  <span class="field-content">
    <a href="/sending/mett-fyri-minni?sid=173187">Mett fyri minni (1:3)</a>
  </span>
</div>
<div class="views-field views-field-field-summary-article">
  <div class="field-content"> Í fyrsta parti vitjar Sunniva Gudmundsdóttir Mortensen plantuommuna í Nólsoy, kokkin Sonna Zachariassen og kondittaran, Malene Fischer Waag.</div>
</div>
<div class="views-field views-field-field-publish">
  <div class="field-content">
    <span property="dc:date" datatype="xsd:dateTime" content="2024-04-04T19:25:00+01:00" class="date-display-single">04-04-2024</span>
  </div>

```
Or perhaps this tag:
```html
<div id="_container">
  <div id="sending_uvtitle">Mett fyri minni (1:3)</div>
  <div id="sending_publish">04-04-2024</div>
  <div id="sending_uvsummary"> Í fyrsta parti vitjar Sunniva Gudmundsdóttir Mortensen plantuommuna í Nólsoy, kokkin Sonna Zachariassen og kondittaran, Malene Fischer Waag.</div>
  <div id="sending_uvbody">
    <div class="field field-name-body field-type-text-with-summary field-label-hidden">
      <div class="field-items">
        <div class="field-item even" property="content:encoded">
          <p>Í fyrsta parti vitjar Sunniva Gudmundsdóttir Mortensen plantuommuna í Nólsoy, sum millum annað ger mat burtur úr (g)ó(ð)krúti. Kokkurin Sonni Zachariassen vísir okkum, hvussu hann ger gott soð burtur úr øllum millum himmal og jørð. At enda verður vitjað heima hjá kondittaranum Malene Fischer Waag, sum ger dessert burtur úr avlopsfruktum.</p>
        </div>
      </div>
    </div>
  </div>
</div>
```
Those html tags didn't seems available in `vit/` url (at least for the OP 2nd link)

**Comment by vman81** [comment]
> Those html tags didn't seems available in `vit/` url (at least for the OP 2nd link)   

The pages under `vit/` is its own area with childrens programming FYI
