### ISSUE TITLE
Site request - hoopladigital.com

### ISSUE THREAD

**Issue by dmachaj** [yt-dlp/yt-dlp#9644]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

- Single video: https://www.hoopladigital.com/play/11430028/0

### Provide a description that is worded well enough to be understood

Hoopla allows you to use your local library card to borrow some types of digital media.  I'd like to be able to download our borrowed content for my kids to use on an airplane trip where we will not have internet access to stream them live.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
c:\code\yt-dlp>git log -n 1
commit 2e94602f241f6e41bdc48576c61089435529339b (HEAD -> master, origin/master, origin/HEAD)
Author: bashonly <88596187+bashonly@users.noreply.github.com>
Date:   Sun Apr 7 15:55:46 2024 -0500

y:\>python3 -Werror -Xdev "c:\code\yt-dlp\yt_dlp\__main__.py" --force-ipv4 -i  --download-archive y:\downloaded-ytd.txt --merge-output-format mp4  --add-metadata  --embed-thumbnail --compat-options embed-thumbnail-atomicparsley --cookies hoopla-cookies.txt https://www.hoopladigital.com/play/11430028/0 -vU
[debug] Command-line config: ['--force-ipv4', '-i', '--download-archive', 'y:\\downloaded-ytd.txt', '--merge-output-format', 'mp4', '--add-metadata', '--embed-thumbnail', '--compat-options', 'embed-thumbnail-atomicparsley', '--cookies', 'hoopla-cookies.txt', 'https://www.hoopladigital.com/play/11430028/0', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (source)
[debug] Lazy loading extractors is disabled
[debug] Compatibility options: embed-thumbnail-atomicparsley
[debug] Git HEAD: 2e94602f2
[debug] Python 3.11.9 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: sqlite3-3.45.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] Loading archive file 'y:\\downloaded-ytd.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.hoopladigital.com/play/11430028/0
[generic] 0: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 0: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.hoopladigital.com/play/11430028/0
Traceback (most recent call last):
  File "C:\code\yt-dlp\yt_dlp\YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\yt-dlp\yt_dlp\YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\code\yt-dlp\yt_dlp\extractor\common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\yt-dlp\yt_dlp\extractor\generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.hoopladigital.com/play/11430028/0
```

**Comment by Henry-Hiles** [comment]
Might have DRM, like netflix does?

**Comment by dmachaj** [comment]
I'm not sure how to determine that.

My kids have since lost interest in the show that is on hoopla digital, so I haven't thought much about this recently 🤷.

**Comment by bashonly** [comment]
* [How to check in browser if the video is DRM protected](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)

**Comment by nlurker** [comment]
Hoopla allows most titles to be downloaded for offline viewing in the Hoopla mobile app.

**Comment by dmachaj** [comment]
Ah, I didn’t even consider whether they had an app. I was using my PC at the time so it was playing them directly in the browser.
