### ISSUE TITLE
Cannot download the playlist from youtube 

### ISSUE THREAD

**Issue by jacekkowalczyk82** [yt-dlp/yt-dlp#9668]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Provide a description that is worded well enough to be understood

Downloading of youtube playlist stopped working. 

I was using it like that: 
yt-dlp -f 251 --restrict-filenames 'https://www.youtube.com/playlist?list=PLpxLTu3yeWT9Vk2FRHMn1_LDY9q2YgVW1'

yt-dlp --version 
2022.04.08

```

yt-dlp -vU -f 251 --restrict-filenames 'https://www.youtube.com/playlist?list=PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA'
[debug] Command-line config: ['-vU', '-f', '251', '--restrict-filenames', 'https://www.youtube.com/playlist?list=PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.12 (CPython 64bit) - Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: yt-dlp's self-update mechanism is disabled on Debian.
Please update yt-dlp using apt(8).
See https://packages.debian.org/sid/yt-dlp for the latest packaged version.




yt-dlp -v -f 251 --restrict-filenames 'https://www.youtube.com/playlist?list=PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA'
[debug] Command-line config: ['-v', '-f', '251', '--restrict-filenames', 'https://www.youtube.com/playlist?list=PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.12 (CPython 64bit) - Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA
[youtube:tab] PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying ...
[youtube:tab] PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA: Downloading webpage (retry #1)
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying ...
[youtube:tab] PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA: Downloading webpage (retry #2)
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying ...
[youtube:tab] PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA: Downloading webpage (retry #3)
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received
[youtube:tab] PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA: Downloading API parameters API JSON
[youtube:tab] PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA: Downloading API JSON
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA
[youtube:tab] PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA: Downloading API JSON with unavailable videos
[download] Downloading playlist: KOMODO
[youtube:tab] PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA page 1: Downloading API JSON
[youtube:tab] playlist KOMODO: Downloading 2 videos
[download] Downloading video 1 of 2
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=EvymNDGAdLM
[youtube] EvymNDGAdLM: Downloading webpage
[youtube] EvymNDGAdLM: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] EvymNDGAdLM: Downloading android player API JSON (retry #1)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] EvymNDGAdLM: Downloading android player API JSON (retry #2)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] EvymNDGAdLM: Downloading android player API JSON (retry #3)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-sigfuncs.js_d0ea0c5b_105 from cache
ERROR: [youtube] EvymNDGAdLM: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2500, in _decrypt_signature
    return func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
TypeError: string indices must be integers
 (caused by TypeError('string indices must be integers')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3357, in _real_extract
    live_broadcast_details, is_live, streaming_data, formats = self._list_formats(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3271, in _list_formats
    formats = list(self._extract_formats(streaming_data, video_id, player_url, is_live, duration))
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3098, in _extract_formats
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2502, in _decrypt_signature
    raise ExtractorError('Signature extraction failed: ' + traceback.format_exc(), cause=e)

  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2500, in _decrypt_signature
    return func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
TypeError: string indices must be integers

[download] Downloading video 2 of 2
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=d8OI9FllKfg
[youtube] d8OI9FllKfg: Downloading webpage
[youtube] d8OI9FllKfg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] d8OI9FllKfg: Downloading android player API JSON (retry #1)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] d8OI9FllKfg: Downloading android player API JSON (retry #2)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] d8OI9FllKfg: Downloading android player API JSON (retry #3)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-sigfuncs.js_d0ea0c5b_101 from cache
ERROR: [youtube] d8OI9FllKfg: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2500, in _decrypt_signature
    return func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
TypeError: string indices must be integers
 (caused by TypeError('string indices must be integers')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3357, in _real_extract
    live_broadcast_details, is_live, streaming_data, formats = self._list_formats(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3271, in _list_formats
    formats = list(self._extract_formats(streaming_data, video_id, player_url, is_live, duration))
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3098, in _extract_formats
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2502, in _decrypt_signature
    raise ExtractorError('Signature extraction failed: ' + traceback.format_exc(), cause=e)

  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2500, in _decrypt_signature
    return func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
TypeError: string indices must be integers

[download] Finished downloading playlist: KOMODO

```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -f 251 --restrict-filenames 'https://www.youtube.com/playlist?list=PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA'
[debug] Command-line config: ['-vU', '-f', '251', '--restrict-filenames', 'https://www.youtube.com/playlist?list=PLpxLTu3yeWT8kBMUGgFXs6rHCSg4RgxNA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.12 (CPython 64bit) - Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: yt-dlp's self-update mechanism is disabled on Debian.
Please update yt-dlp using apt(8).
See https://packages.debian.org/sid/yt-dlp for the latest packaged version.
```

**Comment by pukkandan** [comment]
> ```shell
> yt-dlp: error: yt-dlp's self-update mechanism is disabled on Debian.
> Please update yt-dlp using apt(8).
> See https://packages.debian.org/sid/yt-dlp for the latest packaged version.
> ```

**Comment by jacekkowalczyk82** [comment]
ohhh   I am soprry, indeeed I had two versions of yt-dlp, which yt-dlp was showing me this new one but whenver I run the app it was  selecting the old one.
