### ISSUE TITLE
(NSFW) sexpebune.ro

### ISSUE THREAD

**Issue by ToIgnore** [yt-dlp/yt-dlp#9676]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Romania

### Example URLs

- Category page: `https://sexpebune.ro/categories/pov/` (nsfw)

### Provide a description that is worded well enough to be understood

sexpebune.ro is running [KVS / Kernel Video Sharing](https://www.kernel-video-sharing.com/en/)
Would it be possible to create a generic URL extractor for KVS-using sites?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[directory]>yt-dlp -vU https://sexpebune.ro/categories/pov/
[debug] Command-line config: ['-vU', 'https://sexpebune.ro/categories/pov/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.04.09.170053 from yt-dlp/yt-dlp-master-builds [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.04.09.170053 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.04.09.170053 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://sexpebune.ro/categories/pov/
[generic] pov: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] pov: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://sexpebune.ro/categories/pov/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1741, in __extract_info
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2514, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://sexpebune.ro/categories/pov/
```
```

**Comment by bashonly** [comment]
> Would it be possible to create a generic URL extractor for KVS-using sites?

The generic extractor does support (at least some variants of) KVS player embeds. Try passing a single video's webpage URL instead of a category URL (and share the log)

**Comment by ToIgnore** [comment]
Single video downloads are working, but it'd be nice to have a working playlist / sitemap / category extractor.
