### ISSUE TITLE
Add support for downloads from Synology Photos & Videos shared with permissions to view only

### ISSUE THREAD

**Issue by pawisoon** [yt-dlp/yt-dlp#9702]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Netherlands + Worldwide

### Example URLs

- Single video http://young.myds.me/photo/#/shared_space/folder/142/item/36986
- Album with photos & videos http://young.myds.me/photo/#/shared_space/folder/142

### Provide a description that is worded well enough to be understood

Synology Photos is popular software used for sharing access to photos. 
While its possible to set users permissions to view only, content should be still downloadable. 
With Photos user has way to right click and save such photo. However with videos its not possible to simply save a video that was shared with 'view only' permission.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'http://young.myds.me/photo/#/shared_space/folder/142/item/36986']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Python 3.10.7 (CPython x86_64 64bit) - macOS-14.4.1-x86_64-i386-64bit (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2024.04.09, Current version: stable@2023.06.22
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[generic] Extracting URL: http://young.myds.me/photo/#/shared_space/folder/142/item/36986
[generic] 36986: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 36986: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: http://young.myds.me/photo/#/shared_space/folder/142/item/36986
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1631, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 708, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: http://young.myds.me/photo/#/shared_space/folder/142/item/36986
```

**Comment by ghost** [comment]
Was trying to download from a Synology NAS recently as well and ran into this issue. I found a solution after messing in Web Developer Tools. I'll share what I figured out, in case it's useful for anyone.

Make sure that Firefox and cURL are installed. Open the Web Developer Tools in Firefox. (If you don't know how, look it up.) Then, open the Network tab in the Web Developer Tools. Then, go to the NAS page and open the video preview. You should see a few lines pop up:

<img width="986" height="118" alt="Image" src="https://github.com/user-attachments/assets/8b1517f2-ae57-4d5b-8349-a038afdeef83" />

Of the lines that appear, right-click the first one that has type mp4 and HTTP status 200. In the right-click menu, select Copy → Copy as cURL. Paste that into a terminal window. Add the argument `-o filename.mp4` if your NAS didn't give you a certificate error when you first opened the NAS page, and add the arguments `-k -o filename.mp4` if your NAS did give you a certificate error when you first opened it (common on internal-network NASes).

Run the cURL command. That's it. That's the whole file, I think. Worked for me.

Synology seems to do some amount of client fingerprinting; it may refuse to let cURL download the file. In that case, use [lexiforest/curl-impersonate](https://github.com/lexiforest/curl-impersonate) to work around it. I find this is much less likely to happen if you use Firefox HTTP headers rather than a Chrome ones, hence why I specifically state to copy from Firefox.
