### ISSUE TITLE
[reddit] JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by erikschul** [yt-dlp/yt-dlp#9714]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Fails with url: https://www.reddit.com/r/interestingasfuck/comments/1c4kv8f/how_musicians_and_labels_use_streaming_farms_to/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp_linux_aarch64 -vU https://www.reddit.com/r/interestingas
fuck/comments/1c4kv8f/how_musicians_and_labels_use_streaming_farms_to/
[debug] Command-line config: ['-vU', 'https://www.reddit.com/r/interestingasfuck/comments/1c4kv8f/how_musicians_and_labels_use_streaming_farms_to/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds (linux_aarch64_exe)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-5.15.0-102-generic-aarch64-with-glibc2.17 (OpenSSL 1.1.1  11 Sep 2018, glibc 2.36)
[debug] exe versions: ffmpeg 6.1.1-3 (setts), ffprobe 6.1.1-3
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.22.0, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.13.232802 from yt-dlp/yt-dlp-nightly-builds)
[Reddit] Extracting URL: https://www.reddit.com/r/interestingasfuck/comments/1c4kv8f/how_musicians_and_labels_use_streaming_farms_to/
[Reddit] 1c4kv8f: Downloading JSON metadata
WARNING: [Reddit] 1c4kv8f: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
[Reddit] www.reddit.com request failed, retrying with old.reddit.com
[Reddit] 1c4kv8f: Downloading JSON metadata
ERROR: [Reddit] 1c4kv8f: 1c4kv8f: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 734, in extract
  File "yt_dlp/extractor/reddit.py", line 208, in _real_extract
  File "yt_dlp/extractor/common.py", line 1127, in download_content
  File "yt_dlp/extractor/common.py", line 1094, in download_handle
  File "yt_dlp/extractor/common.py", line 1082, in parse
  File "yt_dlp/extractor/common.py", line 1069, in _parse_json
  File "yt_dlp/extractor/common.py", line 1052, in __print_error

  File "yt_dlp/utils/_utils.py", line 552, in decode
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp/extractor/common.py", line 1066, in _parse_json
  File "json/__init__.py", line 370, in loads
  File "yt_dlp/utils/_utils.py", line 560, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by bashonly** [comment]
I can't reproduce the issue:
```
$ yt-dlp -F https://www.reddit.com/r/interestingasfuck/comments/1c4kv8f/how_musicians_and_labels_use_streaming_farms_to/
[Reddit] Extracting URL: https://www.reddit.com/r/interestingasfuck/comments/1c4kv8f/how_musicians_and_labels_use_streaming_farms_to/
[Reddit] 1c4kv8f: Downloading JSON metadata
[Reddit] 1c4kv8f: Downloading m3u8 information
[Reddit] 1c4kv8f: Downloading MPD manifest
[info] Available formats for stxevfbrymuc1:
ID            EXT RESOLUTION FPS │    FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-5-audio_0 mp4 audio only     │                   m3u8  │ audio only        unknown             audio 0
hls-6-audio_0 mp4 audio only     │                   m3u8  │ audio only        unknown             audio 0
dash-6        m4a audio only     │ ~1001.10KiB   68k https │ audio only        mp4a.40.2   68k 48k DASH audio, m4a_dash
dash-7        m4a audio only     │ ~   1.92MiB  133k https │ audio only        mp4a.40.2  133k 48k DASH audio, m4a_dash
dash-1        mp4 220x392        │ ~   3.53MiB  245k https │ avc1.4d401e  245k video only          DASH video, mp4_dash
hls-198       mp4 220x392     30 │ ~   2.86MiB  198k m3u8  │ avc1.4D401E  198k video only
hls-261       mp4 220x392     30 │ ~   3.77MiB  262k m3u8  │ avc1.4D401E  262k video only
dash-2        mp4 270x480        │ ~   6.22MiB  431k https │ avc1.4d401e  431k video only          DASH video, mp4_dash
hls-272       mp4 270x480     30 │ ~   3.94MiB  273k m3u8  │ avc1.4D401E  273k video only
hls-336       mp4 270x480     30 │ ~   4.85MiB  336k m3u8  │ avc1.4D401E  336k video only
dash-3        mp4 360x640        │ ~  11.64MiB  807k https │ avc1.4d401e  807k video only          DASH video, mp4_dash
hls-417       mp4 360x640     30 │ ~   6.02MiB  417k m3u8  │ avc1.4D401E  417k video only
hls-480       mp4 360x640     30 │ ~   6.93MiB  481k m3u8  │ avc1.4D401E  481k video only
dash-4        mp4 480x854        │ ~  17.96MiB 1245k https │ avc1.4d401f 1245k video only          DASH video, mp4_dash
hls-615       mp4 480x854     30 │ ~   8.88MiB  615k m3u8  │ avc1.4D401F  615k video only
hls-678       mp4 480x854     30 │ ~   9.79MiB  679k m3u8  │ avc1.4D401F  679k video only
dash-5        mp4 720x1280       │ ~  33.59MiB 2328k https │ avc1.4d401f 2328k video only          DASH video, mp4_dash
fallback      mp4 720x1280       │ ≈  34.62MiB 2400k https │ h264        2400k video only          DASH video, mp4_dash
hls-994       mp4 720x1280    30 │ ~  14.34MiB  994k m3u8  │ avc1.4D401F  994k video only
hls-1057      mp4 720x1280    30 │ ~  15.26MiB 1058k m3u8  │ avc1.4D401F 1058k video only
```

It's possible that reddit has blocked your IP. Are you using a data center IP (VPN / VPS / cloud host / etc)?

**Comment by suminhthanh** [comment]
![Screenshot 2024-04-18 at 20 53 52](https://github.com/yt-dlp/yt-dlp/assets/2907636/3022de30-2706-4350-a31c-abd02dc6be51)

I have the same error with TikTok videos

**Comment by renandecarlo** [comment]
I can confirm this error. I'm having the exact same with Tiktok extractor as well.

````
λ yt-dlp -vUF "https://www.tiktok.com/@hopecorez/video/7346326786763951366"
[debug] Command-line config: ['-vUF', 'https://www.tiktok.com/@hopecorez/video/7346326786763951366']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[TikTok] Extracting URL: https://www.tiktok.com/@hopecorez/video/7346326786763951366
[debug] [TikTok] {'app_name': 'musical_ly', 'app_version': '34.1.2', 'manifest_app_version': '2023401020', 'aid': '0', 'iid': '7351153174894626592'}
[TikTok] 7346326786763951366: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 3)
[debug] [TikTok] {'app_name': 'musical_ly', 'app_version': '34.1.2', 'manifest_app_version': '2023401020', 'aid': '0', 'iid': '7351149742343391009'}
[TikTok] 7346326786763951366: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 3)
[debug] [TikTok] {'app_name': 'musical_ly', 'app_version': '34.1.2', 'manifest_app_version': '2023401020', 'aid': '0', 'iid': '7351144126450059040'}
[TikTok] 7346326786763951366: Downloading video feed
WARNING: [TikTok] 7346326786763951366: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); trying with webpage
[TikTok] 7346326786763951366: Downloading webpage
[debug] [TikTok] Found universal data for rehydration
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 7346326786763951366:
ID       EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
─────────────────────────────────────────────────
0        mp4 576x576    │ https │ unknown unknown
download mp4 576x576    │ https │ unknown unknown
````

It leads to a 403 Access Denied url.

**Comment by bashonly** [comment]
> Is it possible to login with a reddit user? The IP address is only banned for anonymous users.

the reddit extractor supports cookies and `-u`/`-p` login, but I'm not sure if it would help

**Comment by erikschul** [comment]
@bashonly 

Thanks!

I solved it using Chrome developer tools -> Network -> click on request -> Copy -> Copy as cURL.

```
yt-dlp \
  --add-headers 'cookie: edgebucket=....; csv=2; loid=...' \
  https://www.reddit.com/r/interestingasfuck/comments/1c4kv8f/how_musicians_and_labels_use_streaming_farms_to/
```

**Comment by erikschul** [comment]
And yes, using `-u '...' -p '...'` returned `403 Blocked`.
