### ISSUE TITLE
[Broken] VrtNU  

### ISSUE THREAD

**Issue by PeterDeKeer** [yt-dlp/yt-dlp#976]
https://www.vrt.be/vrtnu/a-z/het-scheldepeloton/1/het-scheldepeloton-s1a1/

## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.09.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X]I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['https://www.vrt.be/vrtnu/a-z/het-scheldepeloton/1/het-scheldepeloton-s1a1/', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[VrtNU] Login data
[VrtNU] Requesting XSRF Token
ERROR: het-scheldepeloton-s1a1: An extractor error has occurred. (caused by KeyError('UID')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 582, in extract
  File "yt_dlp\extractor\common.py", line 490, in initialize
  File "yt_dlp\extractor\canvas.py", line 271, in _real_initialize
  File "yt_dlp\extractor\canvas.py", line 298, in _login
KeyError: 'UID'
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 582, in extract
  File "yt_dlp\extractor\common.py", line 490, in initialize
  File "yt_dlp\extractor\canvas.py", line 271, in _real_initialize
  File "yt_dlp\extractor\canvas.py", line 298, in _login
KeyError: 'UID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1214, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1239, in __extract_info
  File "yt_dlp\extractor\common.py", line 605, in extract
yt_dlp.utils.ExtractorError: het-scheldepeloton-s1a1: An extractor error has occurred. (caused by KeyError('UID')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE

**Comment by pukkandan** [comment]
It seems your login credentials may be wrong. Please confirm whether they are correct

**Comment by pukkandan** [comment]
Closed due to inactivity
