### ISSUE TITLE
[Zaiko] Unable to extract player

### ISSUE THREAD

**Issue by kyleayy** [yt-dlp/yt-dlp#9798]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

Not really sure as to why I'm getting this error. I've tried doing the same command output on a test stream you can access and download from Zaiko, and that seems to be working fine? Both FFMPEG and Nightly yt-dlp is up to date.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'F:/zaiko.io_cookies.txt', 'https://zaiko.io/event/363371/stream/135051/149729']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds [ff38a011d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg http://2023-10-18-git-e7a6bba51a-essentials_build-www.gyan.dev (setts), ffprobe http://2023-10-18-git-e7a6bba51a-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.21.232710 from yt-dlp/yt-dlp-nightly-builds)
[Zaiko] Extracting URL: https://zaiko.io/event/363371/stream/135051/149729
[Zaiko] 363371: Downloading webpage
[Zaiko] 363371: Downloading player page
ERROR: [Zaiko] 363371: Unable to extract player; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\http://common.py", line 734, in extract
  File "yt_dlp\extractor\http://zaiko.py", line 68, in _real_extract
  File "yt_dlp\extractor\http://zaiko.py", line 28, in _parse_vue_element_attr
  File "yt_dlp\extractor\http://common.py", line 1321, in _search_regex
```

**Comment by kyleayy** [comment]
I'm willing to share my account details if need be to test this. Not sure how I go about that on here!

**Comment by bashonly** [comment]
I'm familiar with the extractor, and I'd be willing to look at this, but it may take me a few days to get around to it.

Contact me via:
- email: bashonly ( at ) protonmail ( dot ) com
- discord: bashonly

**Comment by vschule** [comment]
Same problem here.
changing :
`stream_url = traverse_obj(player_meta, ('initial_event_info', 'endpoint', {url_or_none}))`
to `stream_url = traverse_obj(player_meta, ('initial_event_info', 'jwt_token_url', {url_or_none}))`
let me go further but then I get an access denied.
Not really sure how to get through that part.

```
[debug] Command-line config: ['-vU', 'https://zaiko.io/event/363903/stream/136665/150261', '--cookies-from-browser', 'firefox']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267]
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.8.7-1-default-x86_64-with-glibc2.39 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.39)
[debug] exe versions: ffmpeg 5.1.4 (fdk,setts), ffprobe 5.1.4
[debug] Optional libraries: brotli-1.1.0, certifi-2023.11.17, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.3, urllib3-2.1.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/vsc/.mozilla/firefox/djw5vfkr.default-release/cookies.sqlite"
Extracted 1977 cookies from firefox
[debug] Request Handlers: urllib, requests
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[Zaiko] Extracting URL: https://zaiko.io/event/363903/stream/136665/150261
[Zaiko] 363903: Downloading webpage
[Zaiko] 363903: Downloading player page
[Zaiko] 363903: Downloading m3u8 information
[Zaiko] 363903: Downloading event page
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 363903: Downloading 1 format(s): 0
[debug] Invoking hlsnative downloader on "https://d3g941pfvqtpvn.cloudfront.net/{"playback_url":"https:/d2y3mlel7uksux.cloudfront.net/hh8Tm8JVCyCZ.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjIwMjQwNDdfYWRmMzhjZTkxZGMzYjQ4YmVmMTIifQ.eyJpcCI6ZmFsc2UsImNvIjpmYWxzZSwiY3R5IjpmYWxzZSwicmVnIjpmYWxzZSwic3NuIjp0cnVlLCJleHAiOjE3MTQ4MzQ3NjIsImhlYWRlcnMiOltdLCJxcyI6W10sImludHNpZyI6InJWNEdJSXFPM2pBVGlMcFlsWmlYMXNvNjY3SjhOMWE1V3VjekdkcFBkRWciLCJwYXRocyI6WyIvIl0sImV4YyI6WyIvYWRzLyJdLCJuYmYiOjE2NDUwMDAwMDAsImlhdCI6MTcxNDgxNjc2Mn0.37_1asyFUkNHTAmq6apQ9X-RVP4y-DxHqs1SoSmQ0vQ/event_bdafdf541d8f5ea25d4af4287da7403bb326d6aae7312f7d446d878794e13c97_fe4eb04e6518c8a465ed7a1871f56ad6e7e30db7b7470e9e8ab5a3b3395a87b5/index.m3u8","token_policy":{"ip":0,"ip_value":"2a02:21b4:3c16:3300:32c3:6724:39fc:d9e6","ua":0,"ua_value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.41 Safari/537.36","referer":0}}"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3448, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3169, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/hls.py", line 77, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4131, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 115, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 335, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 350, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pzhlkj6612** [comment]
A `player_meta` of an upcoming event is like:

```json
{
  "initial_event_info": {
    "title": "...",
    "is_scheduled_vod": false,
    "status": "waiting",
    "poster_url": "https://media.zaiko.io/zaiko/...",
    "enable_live_logo": true,
    "enable_stats": true,
    "should_display_survey": true,
    "is_jwt_protected": true,  // jwt?
    "status_message": {
      "en": "Event will start on: ",
      "ja": "イベント開始時間：",
      "ko": "이벤트 시작: ",
      "zh-CN": "活动开始时间：",
      "zh-TW": "活動開始時間：",
      "zh-hans": "活动开始时间：",
      "zh-hant": "活動開始時間："
    },
    "start_time": "2024-...",
    "end_time": "2024-..."
  },

```

No `endpoint` in `initial_event_info` .
