### ISSUE TITLE
[Question] Crop to square thumbnails when embedding in Opus audio files (and other formats as well?)

### ISSUE THREAD

**Issue by kagoromo** [yt-dlp/yt-dlp#980]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm trying to get yt-dlp to crop embedded thumbnails in Opus audio files to be square.
Basically the same question as https://github.com/yt-dlp/yt-dlp/issues/429, but with a different audio format, Opus in my case.
The given config option didn't work for me, which makes sense since it was probably crafted for MP3s only.
`--ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""`
Unfortunately I'm not savvy enough to modify it to suit my needs, so I'm hoping to get a pointer here!

Here is the verbose output when I tried the above post-processing config option.
```
$ yt-dlp.exe --verbose https://music.youtube.com/watch?v=_plFXkLz7fQ
[debug] Portable config file: C:\Users\Kago\Downloads\yt-dlp\yt-dlp.conf
[debug] Portable config: ['--cookies', 'youtube.com_cookies.txt', '-o', '%(release_date)s - %(artist)s - %(title)s.opus', '-x', '-f', 'bestaudio', '--list-formats-as-table', '--no-mtime', '--embed-thumbnail', '--force-ipv4', '--parse-metadata', '%(release_date>%Y/%m/%d)s:%(meta_date)s', '--parse-metadata', '%(track_number)s:%(meta_tracknumber)s', '--parse-metadata', '%(disc_number)s:%(meta_discnumber)s', '--parse-metadata', '%(album_artist)s:%(meta_album_artist)s', '--parse-metadata', '%(genre)s:%(meta_genre)s', '--add-metadata', '--force-overwrites', '--ppa', 'EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop="\'if(gt(ih,iw),iw,ih)\':\'if(gt(iw,ih),ih,iw)\'"']
[debug] Home config file: yt-dlp.conf
[debug] Home config: ['--cookies', 'youtube.com_cookies.txt', '-o', '%(release_date)s - %(artist)s - %(title)s.opus', '-x', '-f', 'bestaudio', '--list-formats-as-table', '--no-mtime', '--embed-thumbnail', '--force-ipv4', '--parse-metadata', '%(release_date>%Y/%m/%d)s:%(meta_date)s', '--parse-metadata', '%(track_number)s:%(meta_tracknumber)s', '--parse-metadata', '%(disc_number)s:%(meta_discnumber)s', '--parse-metadata', '%(album_artist)s:%(meta_album_artist)s', '--parse-metadata', '%(genre)s:%(meta_genre)s', '--add-metadata', '--force-overwrites', '--ppa', 'EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop="\'if(gt(ih,iw),iw,ih)\':\'if(gt(iw,ih),ih,iw)\'"']
[debug] Command-line config: ['--verbose', 'https://music.youtube.com/watch?v=_plFXkLz7fQ']
[debug] Encodings: locale cp932, fs utf-8, out cp932, pref cp932
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.2, ffprobe 2021-06-09-git-e01bf559df-essentials_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://music.youtube.com/watch?v=_plFXkLz7fQ
[youtube] _plFXkLz7fQ: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] _plFXkLz7fQ: Downloading android player API JSON
[youtube] _plFXkLz7fQ: Downloading android music player API JSON
[youtube] _plFXkLz7fQ: Downloading web_music config
[youtube] _plFXkLz7fQ: Downloading player 1cc7c82c
[youtube] _plFXkLz7fQ: Downloading web music player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 47
[debug] Searching for '(?P<meta_date>.+)' in '%(release_date>%Y/%m/%d)s'
[MetadataParser] Parsed meta_date from '%(release_date>%Y/%m/%d)s': '2020/08/14'
[debug] Searching for '(?P<meta_tracknumber>.+)' in '%(track_number)s'
[MetadataParser] Parsed meta_tracknumber from '%(track_number)s': 'NA'
[debug] Searching for '(?P<meta_discnumber>.+)' in '%(disc_number)s'
[MetadataParser] Parsed meta_discnumber from '%(disc_number)s': 'NA'
[debug] Searching for '(?P<meta_album_artist>.+)' in '%(album_artist)s'
[MetadataParser] Parsed meta_album_artist from '%(album_artist)s': 'NA'
[debug] Searching for '(?P<meta_genre>.+)' in '%(genre)s'
[MetadataParser] Parsed meta_genre from '%(genre)s': 'NA'
[debug] Searching for '(?P<meta_date>.+)' in '%(release_date>%Y/%m/%d)s'
[MetadataParser] Parsed meta_date from '%(release_date>%Y/%m/%d)s': '2020/08/14'
[debug] Searching for '(?P<meta_tracknumber>.+)' in '%(track_number)s'
[MetadataParser] Parsed meta_tracknumber from '%(track_number)s': 'NA'
[debug] Searching for '(?P<meta_discnumber>.+)' in '%(disc_number)s'
[MetadataParser] Parsed meta_discnumber from '%(disc_number)s': 'NA'
[debug] Searching for '(?P<meta_album_artist>.+)' in '%(album_artist)s'
[MetadataParser] Parsed meta_album_artist from '%(album_artist)s': 'NA'
[debug] Searching for '(?P<meta_genre>.+)' in '%(genre)s'
[MetadataParser] Parsed meta_genre from '%(genre)s': 'NA'
[info] _plFXkLz7fQ: Downloading 1 format(s): 141
[debug] Testing thumbnail 45
[debug] Testing thumbnail 44
[debug] Testing thumbnail 43
[debug] Testing thumbnail 41
[debug] Testing thumbnail 40
[debug] Testing thumbnail 39
[debug] Testing thumbnail 38
[debug] Testing thumbnail 37
[debug] Testing thumbnail 36
[youtube] _plFXkLz7fQ: Downloading thumbnail  ...
[youtube] _plFXkLz7fQ: Writing thumbnail to: 20200814 - Xomu, Justin Klyvis & Kirara Magic - Setsuna.opus.webp
Deleting existing file 20200814 - Xomu, Justin Klyvis & Kirara Magic - Setsuna.opus
[debug] Invoking downloader on "https://r3---sn-nvoxu-ioqel.googlevideo.com/videoplayback?expire=1631700971&ei=i3NBYdy3LY2b4AKv7abgBg&ip=131.147.80.144&id=o-AByBegfusilMcXB7taVkhxhNVf9AcJyAmxw-g5dr2sE1&itag=141&source=youtube&requiressl=yes&mh=XP&mm=31%2C29&mn=sn-nvoxu-ioqel%2Csn-oguelnl7&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=22&ctier=A&pfa=5&pcm2=yes&gcr=jp&initcwndbps=1386250&hightc=yes&vprv=1&mime=audio%2Fmp4&gir=yes&clen=5643885&dur=175.267&lmt=1595930165150349&mt=1631678693&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID_MUSIC&txp=2311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cpcm2%2Cgcr%2Chightc%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJRO-XeSJqJVv1Aww4xQkomLWMk0Cn3oxGORLDy_WKt6AiBeAHDkfO8Ae3LxbvpnJLSXkpj6vm44-sN-a3VPtgotSw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAN-Q9Vzp2sb9ybmWgLRKN5_5YSTWHf4ZfcswN4JnxwhtAiEAt3jD1xuBYBGTbm2U9ENrKkNZjN1qT543Urx2cMU9FWE%3D"
[download] Destination: 20200814 - Xomu, Justin Klyvis & Kirara Magic - Setsuna.opus
[download] 100% of 5.38MiB in 00:00
[FixupM4a] Correcting container of "20200814 - Xomu, Justin Klyvis & Kirara Magic - Setsuna.opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:20200814 - Xomu, Justin Klyvis & Kirara Magic - Setsuna.opus" -c copy -map 0 -dn -f mp4 "file:20200814 - Xomu, Justin Klyvis & Kirara Magic - Setsuna.temp.opus"
[ExtractAudio] Skipping audio extraction since the file is already in a common audio format
[Metadata] Adding metadata to "20200814 - Xomu, Justin Klyvis & Kirara Magic - Setsuna.opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:20200814 - Xomu, Justin Klyvis & Kirara Magic - Setsuna.opus" -map 0 -dn -vn -acodec copy -metadata "title=Setsuna" -metadata "date=2020/08/14" -metadata "description=Provided to YouTube by TuneCore

Setsuna  Xomu, Justin Klyvis & Kirara Magic

Setsuna

 2020 Kirara Magic

Released on: 2020-08-14

Auto-generated by YouTube." -metadata "synopsis=Provided to YouTube by TuneCore

Setsuna  Xomu, Justin Klyvis & Kirara Magic

Setsuna

 2020 Kirara Magic

Released on: 2020-08-14

Auto-generated by YouTube." -metadata "purl=https://www.youtube.com/watch?v=_plFXkLz7fQ" -metadata "comment=https://www.youtube.com/watch?v=_plFXkLz7fQ" -metadata "artist=Xomu, Justin Klyvis & Kirara Magic" -metadata "album=Setsuna" -metadata "tracknumber=NA" -metadata "discnumber=NA" -metadata "album_artist=NA" -metadata "genre=NA" "file:20200814 - Xomu, Justin Klyvis & Kirara Magic - Setsuna.temp.opus"
ERROR: ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:20200814 - Xomu, Justin Klyvis & Kirara Magic - Setsuna.opus':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.29.100
  Duration: 00:02:55.28, start: 0.000000, bitrate: 257 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 256 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
[opus @ 0000020365ce0180] Unsupported codec id in stream 0
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 776, in main
  File "yt_dlp\__init__.py", line 766, in _real_main
  File "yt_dlp\YoutubeDL.py", line 2894, in download
  File "yt_dlp\YoutubeDL.py", line 1207, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1214, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1252, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1298, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2320, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2864, in process_info
  File "yt_dlp\YoutubeDL.py", line 3015, in post_process
  File "yt_dlp\YoutubeDL.py", line 2964, in run_pp
  File "yt_dlp\postprocessor\common.py", line 83, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 620, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 237, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 274, in real_run_ffmpeg
  File "yt_dlp\postprocessor\common.py", line 56, in report_error
  File "yt_dlp\YoutubeDL.py", line 818, in report_error
  File "yt_dlp\YoutubeDL.py", line 774, in trouble

ERROR: Postprocessing:   Stream #0:0 -> #0:0 (copy)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2864, in process_info
  File "yt_dlp\YoutubeDL.py", line 3015, in post_process
  File "yt_dlp\YoutubeDL.py", line 2964, in run_pp
  File "yt_dlp\postprocessor\common.py", line 83, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 620, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 237, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 275, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:0 -> #0:0 (copy)
```

**Comment by pukkandan** [comment]
Can you show the verbose log without the `--ppa`?

**Comment by pukkandan** [comment]
It is not possible to use the same trick as #429 to crop thumbnails in opus since OPUS embedding is not done with ffmpeg. Instead you can use `--exec-before-download` to crop the thumbnail with ffmpeg first before the embedding

**Comment by pukkandan** [comment]
The quoted thumbnail filename can be accessed as `%(thumbnails.-1.filepath)q`. Otherwise, it looks fine

**Comment by kagoromo** [comment]
That should clean up the configs a bit, thanks!

**Comment by kagoromo** [comment]
For posterity, this is my final configs as far as thumbnails go:

```
--embed-thumbnail
--convert-thumbnails jpg
--exec-before-download "ffmpeg -i %(thumbnails.-1.filepath)q -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\" _%(thumbnails.-1.filepath)q"
--exec-before-download "rm %(thumbnails.-1.filepath)q"
--exec-before-download "mv _%(thumbnails.-1.filepath)q %(thumbnails.-1.filepath)q"
```

**Comment by JDraven214** [comment]
Thank you so much for making this thread, I've been trying to figure out this out on my own for quite a while and never had any success. I used your config setup and, since I'm on Windows, used rm.exe and mv.exe from the GnuWin CoreUtils package.

My command right now is simply "yt-dlp --add-metadata -f "bestaudio[ext=m4a]" URL"

Thank you again!

**Comment by jlneder** [comment]
Hi, I tried the command above, and the index(-1) of the last thumbnail is not always the index of the downloaded thumbnail. So, you have to check manually the index from the output and retry the command with the new index. I made a simple script that checks for jpgs in the download folder and retry all changing the index until there isn't any jpg in the folder. It only works with youtube links:
```
#!/bin/sh

download() {
  TI="$1"
  shift
  yt-dlp -x \
    --audio-format opus --add-metadata \
    --embed-thumbnail --convert-thumbnail jpg \
    --exec-before-download "ffmpeg -i %(thumbnails.$TI.filepath)q -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\" _%(thumbnails.$TI.filepath)q" \
    --exec-before-download "mv _%(thumbnails.$TI.filepath)q %(thumbnails.$TI.filepath)q" \
    "$@"
}

download -1 $@ || for i in $(seq -2 -1 -20); do
  if [ $(find . -iname '*.jpg' | wc -l) -gt 0 ]; then
    download $i -- $(find . -iname '*.jpg' | rev | cut '-d[' -f1 | rev | cut '-d]' -f1 | tr '\n' ' ')
  else
    break
  fi
done
```
If you can expose the index of the downloaded thumbnail element, it would be the best.

**Comment by pukkandan** [comment]
`%(thumbnails.:.filepath)l` should work

**Comment by jlneder** [comment]
> ~`%(thumbnails.:.filepath)l` should work~ it will be unquoted thinking
> 
> Edit: With [dd0228c](https://github.com/yt-dlp/yt-dlp/commit/dd0228ce1f708b12d7b1579438f63fda37c5bb48), `-1` will start working again

Thanks. I guess i will have to repackage it myself with the last git version but is lot a better than all the tries from my script.

I'm having another problem with this code. The `mimetype` of the image embedded is set to `image/None` instead of `image/jpeg`, i am fixing it with:
```
 for i in *.opus; do kid3-cli -c "set picture.mimetype image/jpeg" "$i"; done
 ```
but i think it would be better if there is a way to set it right from the beginning.

**Comment by FAChenier** [comment]
For anyone finding this as the first result on google when looking at how to make square thumbnails in the Python version, this absolute lad on Reddit (found [here](https://www.reddit.com/r/youtubedl/comments/1056fm0/comment/j395e0w/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)) helped me out. Here is what I added and which WORKS on nightly as of 2024-11-30:

```
import shlex


ydl_opts = {
    ...
    'postprocessor_args': {
        'embedthumbnail+ffmpeg_o' : shlex.split(
            "-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
        )
    },
    ...
}
```

I lost an entire day to this lol. Hopefully this saves someone some headache.

**Comment by filloax** [comment]
Hi, I tried using this version in powershell which should be the equivalent escaping, but I get "iw not expected as error in my OS language:
```
    --exec-before-download "ffmpeg -i %(thumbnails.-1.filepath)q -vf crop=""'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'"" _%(thumbnails.-1.filepath)q" `
    --exec-before-download "rm %(thumbnails.-1.filepath)q" `
    --exec-before-download "mv _%(thumbnails.-1.filepath)q %(thumbnails.-1.filepath)q"
```

**Comment by filloax** [comment]
I'm trying this on linux (windows WSL) with cp instead of mv to test the image, and while the image is cropped fine, it is not used in the resulting opus file:
```bash
yt-dlp -x -f ba \
    --embed-metadata \
    --embed-thumbnail \
    --convert-thumbnails jpg \
    --exec-before-download "ffmpeg -i %(thumbnails.-1.filepath)q -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\" _%(thumbnails.-1.filepath)q" \
    --exec-before-download "rm %(thumbnails.-1.filepath)q" \
    --exec-before-download "cp _%(thumbnails.-1.filepath)q %(thumbnails.-1.filepath)q" \
   $URL
```

**Comment by Wisplike** [comment]
The script works if I'm downloading the images to the current folder, but if I use an output option with a nested folder like `-o "%(artist)s/%(title)s.%(ext)s`, then it fails. How to adjust it for nested folders?

**Comment by MachineHusband** [comment]
Managed to get this working on Fedora (Linux) using a similar method without the latter two execs, using ffmpeg's `image2pipe` and `sponge` from the moreutils package. 

```
--embed-thumbnail \
--convert-thumbnails jpg \
--exec-before-download "ffmpeg -i %(thumbnails.-1.filepath)q -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\" -f image2pipe - | sponge %(thumbnails.-1.filepath)q" \
```

As @filloax mentioned, the image gets cropped, but it doesn't end up being used.
I _suspect_ this is as a result of of the "\_" at the front of "_%(thumbnails.-1.filepath)q" in the ffmpeg arguments, which seemed to be putting the underscore in front of the full path name, rather than the file name, and making the system unhappy when it tries to write to a path  that doesn't exist.

I got ffmpeg to output to stdout instead, using `-f image2pipe -`, then piped it to sponge, which then writes it back to the original file, precluding the need for the second name, delete, and rename. 

Hope this helps!

**Comment by partisani** [comment]
> Managed to get this working on Fedora (Linux) using a similar method without the latter two execs, using ffmpeg's `image2pipe` and `sponge` from the moreutils package.
> 
> ```
> --embed-thumbnail \
> --convert-thumbnails jpg \
> --exec-before-download "ffmpeg -i %(thumbnails.-1.filepath)q -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\" -f image2pipe - | sponge %(thumbnails.-1.filepath)q" \
> ```
> 
> As [@filloax](https://github.com/filloax) mentioned, the image gets cropped, but it doesn't end up being used. I _suspect_ this is as a result of of the "_" at the front of "_%(thumbnails.-1.filepath)q" in the ffmpeg arguments, which seemed to be putting the underscore in front of the full path name, rather than the file name, and making the system unhappy when it tries to write to a path that doesn't exist.
> 
> I got ffmpeg to output to stdout instead, using `-f image2pipe -`, then piped it to sponge, which then writes it back to the original file, precluding the need for the second name, delete, and rename.
> 
> Hope this helps!

I tried to get it working, but it completely hangs in the ffmpeg command

Edit: wrote this instead, depends on `imagemagick` tho

```
yt-dlp -x \
       --embed-thumbnail \
       --convert-thumbnails jpg \
       --exec-before-download "magick %(thumbnails.-1.filepath)q -gravity center -extent 1:1 jpg:- | sponge %(thumbnails.-1.filepath)q" \
       --add-metadata $1
```
