### ISSUE TITLE
[yandexvideo] Failed video download on dzen.ru

### ISSUE THREAD

**Issue by mgrimrath** [yt-dlp/yt-dlp#9803]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany/Europe

### Provide a description that is worded well enough to be understood

Downloading this video fails:

https://dzen.ru/video/watch/65f897a5d901db5e49ed39d6?rid=3126738634.50.1714225125937.28233&encoded_pulse_user_info=iHmAxSejZvCwjcoDkLxmGwVxNmYob4zbbcKRQyWu24QYXXwZEGZQOG2jwL4rTZRkel6wS2B0xEFoZ9ghe8L_KA%3A1714225126182&from_site=mail

Regarding whether this is a supported site: dzen.ru is not listed in --list-extractors, but as you can see in the log, it gets redirected to the yandexvideo extractor, so I assume dzen.ru should be working.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
python3 yt-dlp -vU 'https://dzen.ru/video/watch/65f897a5d901db5e49ed39d6?rid=3126738634.50.1714225125937.28233&encoded_pulse_user_info=iHmAxSejZvCwjcoDkLxmGwVxNmYob4zbbcKRQyWu24QYXXwZEGZQOG2jwL4rTZRkel6wS2B0xEFoZ9ghe8L_KA%3A1714225126182&from_site=mail'
[debug] Command-line config: ['-vU', 'https://dzen.ru/video/watch/65f897a5d901db5e49ed39d6?rid=3126738634.50.1714225125937.28233&encoded_pulse_user_info=iHmAxSejZvCwjcoDkLxmGwVxNmYob4zbbcKRQyWu24QYXXwZEGZQOG2jwL4rTZRkel6wS2B0xEFoZ9ghe8L_KA%3A1714225126182&from_site=mail']
[debug] Portable config "/home/matthias/Videos/yt-dlp.conf": ['--no-mtime', '--remux-video', 'mkv', '--paths', 'temp:/tmp', '--abort-on-unavailable-fragments']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.7.4-artix1-1-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: certifi-2024.02.02, requests-2.31.0, sqlite3-3.45.1, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/65f897a5d901db5e49ed39d6?rid=3126738634.50.1714225125937.28233&encoded_pulse_user_info=iHmAxSejZvCwjcoDkLxmGwVxNmYob4zbbcKRQyWu24QYXXwZEGZQOG2jwL4rTZRkel6wS2B0xEFoZ9ghe8L_KA%3A1714225126182&from_site=mail
[ZenYandex] 65f897a5d901db5e49ed39d6: Downloading webpage
[ZenYandex] 65f897a5d901db5e49ed39d6: Redirecting
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/matthias/Videos/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthias/Videos/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/matthias/Videos/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthias/Videos/yt-dlp/yt_dlp/extractor/yandexvideo.py", line 270, in _real_extract
    for s_url in stream_urls:
TypeError: 'NoneType' object is not iterable
```

**Comment by src-tinkerer** [comment]
Apparently they changed the JSON's format a bit, will make a PR

**Comment by krasnh** [comment]
There is such a thing on the Internet:

```patch
fix dzen.ru downloading since ~2024-04-10 by firk@cantconnect.ru

--- ./yt_dlp/extractor/yandexvideo.py.orig	2000-01-01 04:01:00.000000000 +0300
+++ ./yt_dlp/extractor/yandexvideo.py	2024-04-11 16:06:26.851189573 +0300
@@ -260,12 +260,14 @@
         data_json = self._search_json(
             r'("data"\s*:|data\s*=)', webpage, 'metadata', video_id, contains_pattern=r'{["\']_*serverState_*video.+}')
         serverstate = self._search_regex(r'(_+serverState_+video-site_[^_]+_+)',
-                                         webpage, 'server state').replace('State', 'Settings')
+                                         webpage, 'server state')
         uploader = self._search_regex(r'(<a\s*class=["\']card-channel-link[^"\']+["\'][^>]+>)',
                                       webpage, 'uploader', default='<a>')
         uploader_name = extract_attributes(uploader).get('aria-label')
-        video_json = try_get(data_json, lambda x: x[serverstate]['exportData']['video'], dict)
-        stream_urls = try_get(video_json, lambda x: x['video']['streams'])
+        openeditemid = try_get(data_json, lambda x: x[serverstate]['videoViewer']['openedItemId'])
+        video_json = try_get(data_json, lambda x: x[serverstate]['videoViewer']['items'][openeditemid], dict)
+        video2_json = try_get(video_json, lambda x: x['video'], dict)
+        stream_urls = try_get(video2_json, lambda x: x['streams'])
         formats, subtitles = [], {}
         for s_url in stream_urls:
             ext = determine_ext(s_url)
@@ -275,18 +277,19 @@
                 fmts, subs = self._extract_m3u8_formats_and_subtitles(s_url, video_id, 'mp4')
             formats.extend(fmts)
             subtitles = self._merge_subtitles(subtitles, subs)
-        return {
+        retval = {
             'id': video_id,
             'title': video_json.get('title') or self._og_search_title(webpage),
             'formats': formats,
             'subtitles': subtitles,
-            'duration': int_or_none(video_json.get('duration')),
-            'view_count': int_or_none(video_json.get('views')),
+            'duration': int_or_none(video2_json.get('duration')),
+            'view_count': int_or_none(video2_json.get('views')),
             'timestamp': int_or_none(video_json.get('publicationDate')),
             'uploader': uploader_name or data_json.get('authorName') or try_get(data_json, lambda x: x['publisher']['name']),
             'description': video_json.get('description') or self._og_search_description(webpage),
             'thumbnail': self._og_search_thumbnail(webpage) or try_get(data_json, lambda x: x['og']['imageUrl']),
         }
+        return retval
 
 
 class ZenYandexChannelIE(InfoExtractor):
```

**Comment by krasnh** [comment]
Это решает проблему.
https://github.com/yt-dlp/yt-dlp/pull/9813

**Comment by krasnh** [comment]
```sh
./yt-dlp.sh -vU 'https://dzen.ru/video/watch/65f897a5d901db5e49ed39d6?rid=3126738634.50.1714225125937.28233&encoded_pulse_user_info=iHmAxSejZvCwjcoDkLxmGwVxNmYob4zbbcKRQyWu24QYXXwZEGZQOG2jwL4rTZRkel6wS2B0xEFoZ9ghe8L_KA%3A1714225126182&from_site=mail'
[debug] Command-line config: ['-vU', 'https://dzen.ru/video/watch/65f897a5d901db5e49ed39d6?rid=3126738634.50.1714225125937.28233&encoded_pulse_user_info=iHmAxSejZvCwjcoDkLxmGwVxNmYob4zbbcKRQyWu24QYXXwZEGZQOG2jwL4rTZRkel6wS2B0xEFoZ9ghe8L_KA%3A1714225126182&from_site=mail']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: ac817bc83
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.8.0-pf1-x86_64-with-glibc2.38 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.38)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: certifi-2022.09.24, requests-2.28.1, sqlite3-3.39.4, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/65f897a5d901db5e49ed39d6?rid=3126738634.50.1714225125937.28233&encoded_pulse_user_info=iHmAxSejZvCwjcoDkLxmGwVxNmYob4zbbcKRQyWu24QYXXwZEGZQOG2jwL4rTZRkel6wS2B0xEFoZ9ghe8L_KA%3A1714225126182&from_site=mail
[ZenYandex] 65f897a5d901db5e49ed39d6: Downloading webpage
[ZenYandex] 65f897a5d901db5e49ed39d6: Redirecting
[ZenYandex] 65f897a5d901db5e49ed39d6: Downloading MPD manifest
[ZenYandex] 65f897a5d901db5e49ed39d6: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 65f897a5d901db5e49ed39d6: Downloading 1 format(s): 555-3
[debug] Invoking hlsnative downloader on "https://cdn.dzen.ru/vod/converted-video/vod-content/58/18/53/65/09/38/05/79/79/9/1de3d927-fe26-4fad-92ec-ebbcdb77cb4f/kaltura/desc_e07338ee69fba3dbe41933ac946ca5ba/401374911359492676/ysign1=a13b35d64739bd735f0542ce799a998cd081f96d49fa49d262361c938354b603,abcID=967,from=zen,pfx,sfx,ts=663cf1ba/vw=1920,vh=1080,fps=25.00,vbrt=426294,abrt=129531,vcodec=avc1.640028,acodec=mp4a.40.2,label=1080p/index-f7-v1-a1.m3u8?redundant=3&vsid=6ob4vnpjtj7yzh7p75blrlulvaj7twzj6ukjd7p94hqixZENx0000x1714406074"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 93
[download] Destination: Как Сатурн выглядит на самом деле？ Смотрим на Сатурн в любительский телескоп [65f897a5d901db5e49ed39d6].mp4
[download]  83.3% of ~  19.76MiB at    1.49MiB/s ETA 00:02 (frag 78/93)

```
