### ISSUE TITLE
Are there any ways to download from Crunchyroll in an iPhone with yt-dlp &  a-shell mini

### ISSUE THREAD

**Issue by FishAndFire** [yt-dlp/yt-dlp#9812]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [ ] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

So I am new to the iPhone and iOS and I had used yt-dlp before through **Seal** on Android and so when I wanted to download YT Videos on iPhone, I came across the _a-shell_ with _yt-dlp_ method and since I have also used yt-dlp to download **Crunchyroll** content before so I was wondering if it's possible to do that on an iPhone ? (I have actually tried it once but failed and here's the output)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', '
PRIVATE', '--password', 'PRIVATE', '--skip-download'
, '-F', 'https://crunchyroll.com/watch/GEVUZ7QEM']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.11.0 (CPython iPhone15,5 64bit) - macOS-17.1.1-iPhone15,5-arm-64bit (OpenSSL 1.1.1i  8 Dec 2020)
[debug] exe versions: ffmpeg n5.1.2-11-g30d432f205 (setts), ffprobe n5.1.2-11-g30d432f205, phantomjs broken, rtmpdump broken
[debug] Optional libraries: Cryptodome-3.18.0, certifi-2023.07.22, sqlite3-3.39.5, urllib3-2.1.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[crunchyroll] Getting session id
[crunchyroll] Logging in
[crunchyroll] Extracting URL: https://crunchyroll.com/watch/GEVUZ7QEM
[debug] [crunchyroll] Using cxApiParam=noaihdevm_6iyg0a8l0q
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
[crunchyroll] GEVUZ7QEM: Downloading object info JSON (cms)
[crunchyroll] GEVUZ7QEM: Downloading stream info
ERROR: [crunchyroll] GEVUZ7QEM: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/extractor/crunchyroll.py", line 390, in _real_extract
    result['formats'], result['subtitles'] = self._extract_stream(internal_id)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/extractor/crunchyroll.py", line 169, in
 _extract_stream
    stream_response = self._download_json(
                      ^^^^^^^^^^^^^^^^^^^^
File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/extractor/common.py", line 1127, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/extractor/common.py", line 1087, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/extractor/common.py", line 954, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/extractor/common.py", line 903, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/private/var/containers/Bundle/Application/7680DD5D-DED6-4788-867A-582EE6FA3C42/a-Shell-mini.app/Library/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/private/var/containers/Bundle/Application/7680DD5D-DED6-4788-867A-582EE6FA3C42/a-Shell-mini.app/Library/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/private/var/containers/Bundle/Application/7680DD5D-DED6-4788-867A-582EE6FA3C42/a-Shell-mini.app/Library/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/containers/Bundle/Application/7680DD5D-DED6-4788-867A-582EE6FA3C42/a-Shell-mini.app/Library/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
File "/private/var/containers/Bundle/Application/7680DD5D-DED6-4788-867A-582EE6FA3C42/a-Shell-mini.app/Library/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/extractor/common.py", line 890, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/YoutubeDL.py", line 4131, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/networking/common.py", line 115, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/networking/common.py", line 335, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/private/var/mobile/Containers/Data/Application/CAB74028-1CB9-4958-AB00-81BF654BEB9A/Documents/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
`yt-dlp --update-to nightly`

**Comment by FishAndFire** [comment]
Switching to Nightly worked !! Thanks
