### ISSUE TITLE
Unable to download links from mypikpak.com

### ISSUE THREAD

**Issue by ptr7F** [yt-dlp/yt-dlp#9830]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

mypikpak.com provides WebDAV functionality as well as general download links from web pages. Using the WebDAV link will generate a download link. This download link is similar to the one generated by the web page, but yt-dlp cannot download links generated by mypikpak.com.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\TEST> .\yt-dlp.exe "http://hdqa:nvgdhnik@dav.mypikpak.com/1.mp4" -vU
[debug] Command-line config: ['http://hdqa:nvgdhnik@dav.mypikpak.com/1.mp4', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds [ac817bc83] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-04-29-git-cf4af4bca0-full_build-www.gyan.dev (setts), ffprobe 2024-04-29-git-cf4af4bca0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.28.232723 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: http://hdqa:nvgdhnik@dav.mypikpak.com/1.mp4
[generic] 1: Downloading webpage
[redirect] Following redirect to https://dl-a10b-0864.mypikpak.com/download/?fid=1g-nksSVwGdc2ueYtW4He4uGXXNGhHMhxZ7l8Psn0fcTFVda8ZCefbZb-i6Wk4IIp_oWhM7m3--_-fMFctIo6mDoZzT-vUu_tJ2oJhKlEDU=&from=5&verno=3&prod=1104&expire=1714572240&g=BE21637766540ADC906B8BE2B60B77A148C1F7EF&ui=Zi-L1xQCosgWfju9&t=0&ms=6300000&th=6300000&f=574640447&alt=0&userid=Zi-L1xQCosgWfju9&fileid=VNwjIARn1e8-Z0UwW7vOjjXco1&pr=XQPkPvr9WWiIuMvELmrVeviAPTLnYILf0ZziCslFBJSueDWsDRCUkR8ZhWUB3bQ8EimBa0K8HrHEKc8oKfTJVqWaeEhh1atD7FQxY53xsilHY1_bX-9SL3BkBfTg_fglMBxUIsXP5ojV-EtaiZAwz4ZwlxKtYq8MkN1RJiiaKR0GyV92EeGV2lV7Gsa0nMl2gEr4Icv-3Svq6yks3E4spnhhxuCM6iG8oUZtWQ-zOJnxsgJ3SWutbY_-J8USCg_Ozpmaubpu-sRUEKHV6DOkRCeStRFSD5FE8Dc2ylVXoCd4PAyblk-gtGSO9yVnqDhOpuXlylKkCUwh08PHMYlkngCPWZ5mgICLb9t6OT5ioVM=&sign=B0D4FB767F06D5F378B35A80CC5DB784
[generic] Extracting URL: https://dl-a10b-0864.mypikpak.com/download/?fid=1g-nksSVwGdc2ueYtW4He4uGXXNGhHMhxZ7l8Psn0fcTFVda8ZCefbZb-i6Wk4IIp_oWhM7m3--_-fMFctIo6mDoZzT-vUu_tJ2oJhKlEDU=&from=5&verno=3&prod=1104&expire=1714572240&g=BE21637766540ADC906B8BE2B60B77A148C1F7EF&ui=Zi-L1xQCosgWfju9&t=0&ms=6300000&th=6300000&f=574640447&alt=0&userid=Zi-L1xQCosgWfju9&fileid=VNwjIARn1e8-Z0UwW7vOjjXco1&pr=XQPkPvr9WWiIuMvELmrVeviAPTLnYILf0ZziCslFBJSueDWsDRCUkR8ZhWUB3bQ8EimBa0K8HrHEKc8oKfTJVqWaeEhh1atD7FQxY53xsilHY1_bX-9SL3BkBfTg_fglMBxUIsXP5ojV-EtaiZAwz4ZwlxKtYq8MkN1RJiiaKR0GyV92EeGV2lV7Gsa0nMl2gEr4Icv-3Svq6yks3E4spnhhxuCM6iG8oUZtWQ-zOJnxsgJ3SWutbY_-J8USCg_Ozpmaubpu-sRUEKHV6DOkRCeStRFSD5FE8Dc2ylVXoCd4PAyblk-gtGSO9yVnqDhOpuXlylKkCUwh08PHMYlkngCPWZ5mgICLb9t6OT5ioVM=&sign=B0D4FB767F06D5F378B35A80CC5DB784
[generic] ?fid=1g-nksSVwGdc2ueYtW4He4uGXXNGhHMhxZ7l8Psn0fcTFVda8ZCefbZb-i6Wk4IIp_oWhM7m3--_-fMFctIo6mDoZzT-vUu_tJ2oJhKlEDU=&from=5&verno=3&prod=1104&expire=1714572240&g=BE21637766540ADC906B8BE2B60B77A148C1F7EF&ui=Zi-L1xQCosgWfju9&t=0&ms=6300000&th=6300000&f=574640447&alt=0&userid=Zi-L1xQCosgWfju9&fileid=VNwjIARn1e8-Z0UwW7vOjjXco1&pr=XQPkPvr9WWiIuMvELmrVeviAPTLnYILf0ZziCslFBJSueDWsDRCUkR8ZhWUB3bQ8EimBa0K8HrHEKc8oKfTJVqWaeEhh1atD7FQxY53xsilHY1_bX-9SL3BkBfTg_fglMBxUIsXP5ojV-EtaiZAwz4ZwlxKtYq8MkN1RJiiaKR0GyV92EeGV2lV7Gsa0nMl2gEr4Icv-3Svq6yks3E4spnhhxuCM6iG8oUZtWQ-zOJnxsgJ3SWutbY_-J8USCg_Ozpmaubpu-sRUEKHV6DOkRCeStRFSD5FE8Dc2ylVXoCd4PAyblk-gtGSO9yVnqDhOpuXlylKkCUwh08PHMYlkngCPWZ5mgICLb9t6OT5ioVM=&sign=B0D4FB767F06D5F378B35A80CC5DB784: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
WARNING: [generic] URL could be a direct video link, returning it as such.
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ?fid=1g-nksSVwGdc2ueYtW4He4uGXXNGhHMhxZ7l8Psn0fcTFVda8ZCefbZb-i6Wk4IIp_oWhM7m3--_-fMFctIo6mDoZzT-vUu_tJ2oJhKlEDU=&from=5&verno=3&prod=1104&expire=1714572240&g=BE21637766540ADC906B8BE2B60B77A148C1F7EF&ui=Zi-L1xQCosgWfju9&t=0&ms=6300000&th=6300000&f=574640447&alt=0&userid=Zi-L1xQCosgWfju9&fileid=VNwjIARn1e8-Z0UwW7vOjjXco1&pr=XQPkPvr9WWiIuMvELmrVeviAPTLnYILf0ZziCslFBJSueDWsDRCUkR8ZhWUB3bQ8EimBa0K8HrHEKc8oKfTJVqWaeEhh1atD7FQxY53xsilHY1_bX-9SL3BkBfTg_fglMBxUIsXP5ojV-EtaiZAwz4ZwlxKtYq8MkN1RJiiaKR0GyV92EeGV2lV7Gsa0nMl2gEr4Icv-3Svq6yks3E4spnhhxuCM6iG8oUZtWQ-zOJnxsgJ3SWutbY_-J8USCg_Ozpmaubpu-sRUEKHV6DOkRCeStRFSD5FE8Dc2ylVXoCd4PAyblk-gtGSO9yVnqDhOpuXlylKkCUwh08PHMYlkngCPWZ5mgICLb9t6OT5ioVM=&sign=B0D4FB767F06D5F378B35A80CC5DB784: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://dl-a10b-0864.mypikpak.com/download/?fid=1g-nksSVwGdc2ueYtW4He4uGXXNGhHMhxZ7l8Psn0fcTFVda8ZCefbZb-i6Wk4IIp_oWhM7m3--_-fMFctIo6mDoZzT-vUu_tJ2oJhKlEDU=&from=5&verno=3&prod=1104&expire=1714572240&g=BE21637766540ADC906B8BE2B60B77A148C1F7EF&ui=Zi-L1xQCosgWfju9&t=0&ms=6300000&th=6300000&f=574640447&alt=0&userid=Zi-L1xQCosgWfju9&fileid=VNwjIARn1e8-Z0UwW7vOjjXco1&pr=XQPkPvr9WWiIuMvELmrVeviAPTLnYILf0ZziCslFBJSueDWsDRCUkR8ZhWUB3bQ8EimBa0K8HrHEKc8oKfTJVqWaeEhh1atD7FQxY53xsilHY1_bX-9SL3BkBfTg_fglMBxUIsXP5ojV-EtaiZAwz4ZwlxKtYq8MkN1RJiiaKR0GyV92EeGV2lV7Gsa0nMl2gEr4Icv-3Svq6yks3E4spnhhxuCM6iG8oUZtWQ-zOJnxsgJ3SWutbY_-J8USCg_Ozpmaubpu-sRUEKHV6DOkRCeStRFSD5FE8Dc2ylVXoCd4PAyblk-gtGSO9yVnqDhOpuXlylKkCUwh08PHMYlkngCPWZ5mgICLb9t6OT5ioVM=&sign=B0D4FB767F06D5F378B35A80CC5DB784"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'download [？fid=1g-nksSVwGdc2ueYtW4He4uGXXNGhHMhxZ7l8Psn0fcTFVda8ZCefbZb-i6Wk4IIp_oWhM7m3--_-fMFctIo6mDoZzT-vUu_tJ2oJhKlEDU=&from=5&verno=3&prod=1104&expire=1714572240&g=BE21637766540ADC906B8BE2B60B77A148C1F7EF&ui=Zi-L1xQCosgWfju9&t=0&ms=6300000&th=6300000&f=574640447&alt=0&userid=Zi-L1xQCosgWfju9&fileid=VNwjIARn1e8-Z0UwW7vOjjXco1&pr=XQPkPvr9WWiIuMvELmrVeviAPTLnYILf0ZziCslFBJSueDWsDRCUkR8ZhWUB3bQ8EimBa0K8HrHEKc8oKfTJVqWaeEhh1atD7FQxY53xsilHY1_bX-9SL3BkBfTg_fglMBxUIsXP5ojV-EtaiZAwz4ZwlxKtYq8MkN1RJiiaKR0GyV92EeGV2lV7Gsa0nMl2gEr4Icv-3Svq6yks3E4spnhhxuCM6iG8oUZtWQ-zOJnxsgJ3SWutbY_-J8USCg_Ozpmaubpu-sRUEKHV6DOkRCeStRFSD5FE8Dc2ylVXoCd4PAyblk-gtGSO9yVnqDhOpuXlylKkCUwh08PHMYlkngCPWZ5mgICLb9t6OT5ioVM=&sign=B0D4FB767F06D5F378B35A80CC5DB784].unknown_video.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 590, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 250, in wrapper
  File "yt_dlp\downloader\common.py", line 236, in error_callback
  File "yt_dlp\utils\_utils.py", line 5082, in report_retry
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 256, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 593, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'download [？fid=1g-nksSVwGdc2ueYtW4He4uGXXNGhHMhxZ7l8Psn0fcTFVda8ZCefbZb-i6Wk4IIp_oWhM7m3--_-fMFctIo6mDoZzT-vUu_tJ2oJhKlEDU=&from=5&verno=3&prod=1104&expire=1714572240&g=BE21637766540ADC906B8BE2B60B77A148C1F7EF&ui=Zi-L1xQCosgWfju9&t=0&ms=6300000&th=6300000&f=574640447&alt=0&userid=Zi-L1xQCosgWfju9&fileid=VNwjIARn1e8-Z0UwW7vOjjXco1&pr=XQPkPvr9WWiIuMvELmrVeviAPTLnYILf0ZziCslFBJSueDWsDRCUkR8ZhWUB3bQ8EimBa0K8HrHEKc8oKfTJVqWaeEhh1atD7FQxY53xsilHY1_bX-9SL3BkBfTg_fglMBxUIsXP5ojV-EtaiZAwz4ZwlxKtYq8MkN1RJiiaKR0GyV92EeGV2lV7Gsa0nMl2gEr4Icv-3Svq6yks3E4spnhhxuCM6iG8oUZtWQ-zOJnxsgJ3SWutbY_-J8USCg_Ozpmaubpu-sRUEKHV6DOkRCeStRFSD5FE8Dc2ylVXoCd4PAyblk-gtGSO9yVnqDhOpuXlylKkCUwh08PHMYlkngCPWZ5mgICLb9t6OT5ioVM=&sign=B0D4FB767F06D5F378B35A80CC5DB784].unknown_video.part'
```

**Comment by bashonly** [comment]
The only problem is that the output filename is too long. Add this to your command:
```
-o "%(title).150B.%(ext)s"
```

Or if you want the original filename, you could do this:
```
--parse-metadata "video:original_url:/(?P<title>[^/?#]+)\.\w+$" --parse-metadata "video:original_url:\.(?P<ext>\w+)$" -o "%(title)s.%(ext)s"
```

**Comment by seproDev** [comment]
The download URL is invalid/expired.
I also don't entirely understand why you try to download what I presume to be a mp4/mkv file using yt-dlp instead of just using wget. There is also no reason to go through the ytdl_hook in mpv if you already have the direct file url.

**Comment by seproDev** [comment]
You are likely missing cookies or some other headers. If you open the URL you provided in an incognito window it also 403s.

The task of the ytdl_hook is to take a webpage URL, and extract the streaming data. Be it the m3u8/dash manifest or the direct video file. That then gets passed to mpv along with some metadata. If you already have the direct download URL of the video file, then using the ytdl_hook will do nothing. Iirc. mpv will actually try to play back the URL directly with ffmpeg first and only after fall back to the ytdl_hook. In this case both fail since the URL can not be opened.

Either way this is not a yt-dlp issue.
