### ISSUE TITLE
Add support for podcasters.spotify.com

### ISSUE THREAD

**Issue by FrenchGithubUser** [yt-dlp/yt-dlp#9844]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

- Podcast page : https://podcasters.spotify.com/pod/show/thelolpodcast
- Episode : https://podcasters.spotify.com/pod/show/thelolpodcast/episodes/Meet-My-Secret-Girlfriend-e2iukcg

### Provide a description that is worded well enough to be understood

Adding support to download single episodes and whole podcast series

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://podcasters.spotify.com/pod/show/thelolpodcast/episodes/Meet-My-Secret-Girlfriend-e2iukcg
[debug] Command-line config: ['-vU', 'https://podcasters.spotify.com/pod/show/thelolpodcast/episodes/Meet-My-Secret-Girlfriend-e2iukcg']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267]
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.8.7-arch1-1-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.3, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://podcasters.spotify.com/pod/show/thelolpodcast/episodes/Meet-My-Secret-Girlfriend-e2iukcg
[generic] Meet-My-Secret-Girlfriend-e2iukcg: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Meet-My-Secret-Girlfriend-e2iukcg: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://podcasters.spotify.com/pod/show/thelolpodcast/episodes/Meet-My-Secret-Girlfriend-e2iukcg
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://podcasters.spotify.com/pod/show/thelolpodcast/episodes/Meet-My-Secret-Girlfriend-e2iukcg
```

**Comment by FrenchGithubUser** [comment]
The files are in `m4a` format and accessible publicly without any authentication required, nor token. Hosted on cloudfront

**Comment by bashonly** [comment]
won't be supported
