### ISSUE TITLE
Support request: https://swerollingtv.org

### ISSUE THREAD

**Issue by fa-bien** [yt-dlp/yt-dlp#9847]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Austria

### Example URLs

- Single video: https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u

### Provide a description that is worded well enough to be understood

An account is necessary, it is free to create a new account.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] Extracting URL: https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u
[generic] l8apqv2u: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] l8apqv2u: Extracting information
ERROR: Unsupported URL: https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u
(venv) ~/tmp> yt-dlp -vU -u wonderzbra@gmail.com -p tg228VtGN6AnruX "https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u"
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.7.9-amd64-x86_64-with-glibc2.37 (OpenSSL 3.2.2-dev , glibc 2.37)
[debug] exe versions: ffmpeg 7.0 (fdk,setts), ffprobe 7.0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.3, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u
[generic] l8apqv2u: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] l8apqv2u: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u
Traceback (most recent call last):
  File "/home/fabien/tmp/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabien/tmp/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/fabien/tmp/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabien/tmp/venv/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u
```
```

**Comment by bashonly** [comment]
Could you try with `--cookies-from-browser` instead of `-u`/`-p` and share that log as well please?

**Comment by fa-bien** [comment]
> Could you try with `--cookies-from-browser` instead of `-u`/`-p` and share that log as well please?

```
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.7.9-amd64-x86_64-with-glibc2.37 (OpenSSL 3.2.2-dev , glibc 2.37)
[debug] exe versions: ffmpeg 7.0 (fdk,setts), ffprobe 7.0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.3, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/fabien/.mozilla/firefox/[obfuscated]/cookies.sqlite"
Extracted 702 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u
[generic] l8apqv2u: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] l8apqv2u: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u
Traceback (most recent call last):
  File "/home/fabien/tmp/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabien/tmp/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/fabien/tmp/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabien/tmp/venv/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://swerollingtv.org/stockholm-roller-derby/games/g/l8apqv2u
```
