### ISSUE TITLE
[Broken] ITV extractor still broken with #913

### ISSUE THREAD

**Issue by sleaux-meaux** [yt-dlp/yt-dlp#986]
## Checklist

- [X] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

First attempt - broken:

```
[debug] Command-line config: ['--write-subs', '--force-overwrite', '--verbose', 'https://www.itv.com/hub/plebs/2a1873a0002']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: a8cb7eca6
[debug] Python version 3.9.5 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.0-tessus, rtmpdump 2.4-102-ga3a600d-get_iplayer
[debug] Optional libraries: pycryptodome, sqlite
[debug] Proxy map: {}
[debug] Using fake IP 25.132.108.68 (GB) as X-Forwarded-For
[debug] [ITV] Extracting URL: https://www.itv.com/hub/plebs/2a1873a0002
[ITV] 2a1873a0002: Downloading webpage
[ITV] 2a1873a0002: Downloading JSON metadata
BORK: https://itvpnpdotcom.cdn1.content.itv.com/2-1873-0002-002/18/4/VAR012/2-1873-0002-002_18_4_VAR012.ism/.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9pdHZwbnBkb3Rjb20uY2RuMS5jb250ZW50Lml0di5jb20vMi0xODczLTAwMDItMDAyLzE4LzQvVkFSMDEyLzItMTg3My0wMDAyLTAwMl8xOF80X1ZBUjAxMi5pc20vKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYzMTczMzAwMH19fV19&Signature=JKx7iuj~mWuZ1SDVXhyiSiWn0yOJZMRX9WOc2p9vVk7HVmrIhv9E4v5Eb~FFA2KEGkeM6CF8GWAIzCFpp8XvEHS4xtP51vu~kAEvTHkVoTenSqIgvm0D1EvwfC6sFXH4nwAya8XgQtwZrBsa~RoyFqt5YFsqQD8s5sUaSUgz7LRarU2ThNrGreU5o5XBH9nptjWAN91H6eQ2looARWTGFvri0BriNwq6ka~-YVHHw971Kta9DqMZPSuw0rviYbMkzS4amOPkhRynGODDcMCDvibEE4MH26Kj9SDbouAG7pKMf7xpIqzumjuKGfe3zLiLGfVkoJWEcGEcIedlw4M0Aw__&Key-Pair-Id=APKAJB7PCFZAZHWZVIBA
[ITV] 2a1873a0002: Downloading m3u8 information
WARNING: [ITV] Failed to download m3u8 information: HTTP Error 403: Forbidden
[ITV] 2a1873a0002: Downloading JSON metadata
[debug] Downloading subtitles: en
ERROR: [ITV] 2a1873a0002: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/user/dev/yt-dlp/yt_dlp/YoutubeDL.py", line 1218, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/user/dev/yt-dlp/yt_dlp/YoutubeDL.py", line 1256, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/user/dev/yt-dlp/yt_dlp/YoutubeDL.py", line 1306, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/user/dev/yt-dlp/yt_dlp/YoutubeDL.py", line 2189, in process_video_result
    self.raise_no_formats(info_dict)
  File "/Users/user/dev/yt-dlp/yt_dlp/YoutubeDL.py", line 849, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ITV] 2a1873a0002: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

After a few more attempts - works:

```
[debug] Command-line config: ['--write-subs', '--force-overwrite', '--verbose', 'https://www.itv.com/hub/plebs/2a1873a0002']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: a8cb7eca6
[debug] Python version 3.9.5 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.0-tessus, rtmpdump 2.4-102-ga3a600d-get_iplayer
[debug] Optional libraries: pycryptodome, sqlite
[debug] Proxy map: {}
[debug] Using fake IP 25.251.165.177 (GB) as X-Forwarded-For
[debug] [ITV] Extracting URL: https://www.itv.com/hub/plebs/2a1873a0002
[ITV] 2a1873a0002: Downloading webpage
[ITV] 2a1873a0002: Downloading JSON metadata
BORK: https://itvpnpdotcom.content.itv.com/2-1873-0002-002/18/4/VAR012/2-1873-0002-002_18_4_VAR012.ism/.m3u8?hdnea=st=1631709660~exp=1631731260~acl=/2-1873-0002-002/*~data=nohubplus~hmac=df581b50ba8fdc37b4bd5d6369196f5103414b5255a60f51ddc0785a54364e44
[ITV] 2a1873a0002: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ITV] 2a1873a0002: Downloading JSON metadata
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2a1873a0002: Downloading 1 format(s): hls-1705
[info] Writing video subtitles to: Plebs - The Orgy [2a1873a0002].en.vtt
[debug] Invoking downloader on "https://itvpnpsubtitles.cdn1.content.itv.com/2-1873-0002-002/Subtitles/3/WebVTT-OUT-OF-BAND/2-1873-0002-002_Series1615562535_TX000000.vtt?Expires=1631733070&Signature=DFkafc1U7xWoQ7P~p8Z2rA-1Es5vJ5u-h5SSH3ZDK13Xn69wyODgDl~7tFMbG~og7wprtdOZL25a4Rh~GI~hZ2h2-MwewJtTSYdrhsRkSkPIWUk~Vi6f9XOSBsXCY4lTZMmd5UlJ4JUmnnzAStUzHIqjQpqZkePWGLFcDYVeprDsZa-RNjuC50SNr9ha4mX7us~hpxN6gMvF5AchfQYT4yJUGmnhNHclm9SBtyRbLcN7p5rJnRHp9yb-o6pxBfDBBytq-w6e-SIds1QWZkqEFc77LO7mpvX7Xge2QLOQ-9dyrDHrW1eiAWuaN2T86gYFrKVtYzrQIbPoE16-uffqRA__&Key-Pair-Id=APKAJB7PCFZAZHWZVIBA"
[download] Destination: Plebs - The Orgy [2a1873a0002].en.vtt
[download] 100% of 46.16KiB in 00:00
[debug] Invoking downloader on "https://itvpnpdotcom.content.itv.com/2-1873-0002-002/18/4/VAR012/2-1873-0002-002_18_4_VAR012.ism/2-1873-0002-002_18_4_VAR012-audio=128000-video=1480096.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 226
[download] Destination: Plebs - The Orgy [2a1873a0002].mp4
[download]  92.0% of ~272.70MiB at  8.00MiB/s ETA 00:09^C
ERROR: Interrupted by user
```

With original youtube-dl PR:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.itv.com/hub/plebs/2a1873a0002', '--write-sub']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Git HEAD: 4c57dd270
[debug] Python version 3.9.5 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.0-tessus, rtmpdump 2.4-102-ga3a600d-get_iplayer
[debug] Proxy map: {}
[debug] Using fake IP 25.143.179.168 (GB) as X-Forwarded-For.
[ITV] 2a1873a0002: Downloading webpage
[ITV] 2a1873a0002: Downloading JSON metadata
BORK: https://itvpnpmobile.content.itv.com/2-1873-0002-002/6/4/VAR003/2-1873-0002-002_6_4_VAR003.ism/.m3u8?hdnea=st=1631736607~exp=1631758207~acl=/2-1873-0002-002/*~data=nohubplus~hmac=3712013150056db82736614dc5c95276cef2976af7dacf4e836bfde7b5419465
[ITV] 2a1873a0002: Downloading m3u8 information
[ITV] 2a1873a0002: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Plebs - The Orgy-2a1873a0002.en.vtt
[debug] Invoking downloader on 'https://itvpnpmobile.content.itv.com/2-1873-0002-002/6/4/VAR003/2-1873-0002-002_6_4_VAR003.ism/2-1873-0002-002_6_4_VAR003-audio=128000-video=1469485.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 226
[download] Destination: Plebs - The Orgy-2a1873a0002.mp4
[download]   3.5% of ~241.66MiB at  9.96MiB/s ETA 00:45^C
ERROR: Interrupted by user
```

## Description

The `next()` constructs in `_get_subtitles()` and `_real_extract()` added to the  ITV extractor do not quite replicate the logic in the original youtube-dl PR (ytdl-org/youtube-dl#28955) that was copied into #913. The result is that yt-dlp picks up non-mobile streams when mobile streams may be available. This means that HLS master playlist URLs may be bounced between two different CDNs, one accessible and one not (as was discussed in #913 in the context of subtitles), instead of using the mobile CDN (see lines prefixed "BORK:" above).  For media streams, the extractor should take the last matching "featureset" (stream descriptor of sorts) from scraped data, not the first. Programmes without mobile streams could still encounter the inaccessible CDN, but there are relatively few of those. Restricting the extractor to the "mobile" list of stream descriptors may be too strict for programmes without mobile streams since non-mobile streams may still be available, albeit at the cost of a few retries to hit the accessible CDN. As it is, there is only one accessible mobile stream per programme, and one mobile stream with subtitles - and they are not the same.

Tested from UK without proxy or VPN with git HEAD a8cb7ec

**Comment by pukkandan** [comment]
@coletdjnz

**Comment by coletdjnz** [comment]
> The next() constructs in _get_subtitles() and _real_extract() added to the ITV extractor do not quite replicate the logic in the original youtube-dl PR (ytdl-org/youtube-dl#28955) that was copied into #913. The result is that yt-dlp picks up non-mobile streams when mobile streams may be available

cool, should be able to simply revert this change then.
