### ISSUE TITLE
[Youtube] KeyError: 'data'

### ISSUE THREAD

**Issue by Barbarella6666666** [yt-dlp/yt-dlp#9874]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

It seems that youtube support is broken. I've searched the issues but could not find anything related.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--concurrent-fragments', '6', '--downloader', 'aria2c', '--downloader-args', 'aria2c:--optimize-concurrent-downloads=true', '--verbose', 'https://www.youtube.com/watch?v=udrMkV-_CyY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.12 (CPython 64bit) - Linux-6.5.0-28-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=udrMkV-_CyY
[youtube] udrMkV-_CyY: Downloading webpage
[youtube] udrMkV-_CyY: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] udrMkV-_CyY: Downloading android player API JSON (retry #1)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] udrMkV-_CyY: Downloading android player API JSON (retry #2)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
[youtube] udrMkV-_CyY: Downloading android player API JSON (retry #3)
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.7d1f7724 from cache
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = 6EOrYA4eVDtKHaekuR ; player = https://www.youtube.com/s/player/7d1f7724/player_ias.vflset/en_US/base.js
udrMkV-_CyY: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2519, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2551, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 536, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 306, in interpret_expression
    return local_vars[var_m.group('name')]
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 49, in __getitem__
    raise KeyError(key)
KeyError: 'data'
 (caused by KeyError('data')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = UOEJwyY7uyi_AiUe1Q ; player = https://www.youtube.com/s/player/7d1f7724/player_ias.vflset/en_US/base.js
udrMkV-_CyY: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2519, in _decrypt_nsig
    self._player_cache[sig_id] = func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2551, in <lambda>
    return lambda s: jsi.extract_function_from_code(*func_code)([s])
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 536, in resf
    ret, should_abort = self.interpret_statement(stmt, var_stack)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 145, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 306, in interpret_expression
    return local_vars[var_m.group('name')]
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 49, in __getitem__
    raise KeyError(key)
KeyError: 'data'
 (caused by KeyError('data')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] udrMkV-_CyY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3463, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by seproDev** [comment]
You are using an ancient version of yt-dlp. Update to 2024.04.09 or later.
