### ISSUE TITLE
SHAHID unsuported url

### ISSUE THREAD

**Issue by kvrim1** [yt-dlp/yt-dlp#9880]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

When attempting to download videos from Shahid MBC using yt-dlp, I encountered an "unsupported URL" error. The specific URL I tried to download from is: [https://shahid.mbc.net/ar/series/سرايا%20عابدين-الموسم-2/season-72252-94288](https://shahid.mbc.net/ar/series/%D8%B3%D8%B1%D8%A7%D9%8A%D8%A7%20%D8%B9%D8%A7%D8%A8%D8%AF%D9%8A%D9%86-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-2/season-72252-94288)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\yt-dlp>yt-dlp -vU https://shahid.mbc.net/ar/series/سرايا%20عابدين-الموسم-2/season-72252-94288
[debug] Command-line config: ['-vU', 'https://shahid.mbc.net/ar/series/سرايا%20عابدين-الموسم-2/season-72252-94288']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.17763-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://shahid.mbc.net/ar/series/سرايا%20عابدين-الموسم-2/season-72252-94288
[generic] season-72252-94288: Downloading webpage
[redirect] Following redirect to https://shahid.mbc.net/ar/series/%D8%B3%D8%B1%D8%A7%D9%8A%D8%A7%20%D8%B9%D8%A7%D8%A8%D8%AF%D9%8A%D9%86-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-2/season-72252-94288
[generic] Extracting URL: https://shahid.mbc.net/ar/series/%D8%B3%D8%B1%D8%A7%D9%8A%D8%A7%20%D8%B9%D8%A7%D8%A8%D8%AF%D9%8A%D9%86-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-2/season-72252-94288
[generic] season-72252-94288: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] season-72252-94288: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://shahid.mbc.net/ar/series/%D8%B3%D8%B1%D8%A7%D9%8A%D8%A7%20%D8%B9%D8%A7%D8%A8%D8%AF%D9%8A%D9%86-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-2/season-72252-94288
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1741, in __extract_info
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2514, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://shahid.mbc.net/ar/series/%D8%B3%D8%B1%D8%A7%D9%8A%D8%A7%20%D8%B9%D8%A7%D8%A8%D8%AF%D9%8A%D9%86-%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%85-2/season-72252-94288
```

**Comment by dirkf** [comment]
Your problem URL appears to be for a season/series of some show with linked episodes. The site extractor doesn't support any playlist pages. Also, the episode links are like `.../episodes/.../id-{id}` and these are also not supported by the extractor. Finally, the site wants payment for these episodes: an account with a paid subscription may be needed to implement this extraction, unless an example with free-to-view shows can be provided.

**Comment by kvrim1** [comment]
> Your problem URL appears to be for a season/series of some show with linked episodes. The site extractor doesn't support any playlist pages. Also, the episode links are like `.../episodes/.../id-{id}` and these are also not supported by the extractor. Finally, the site wants payment for these episodes: an account with a paid subscription may be needed to implement this extraction, unless an example with free-to-view shows can be provided.

I already have a paid subscription, how to link it with yt-dlp?

**Comment by pukkandan** [comment]
Usually, you would [use cookies](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) but it will not help here due to the other issues mentioned

**Comment by kvrim1** [comment]
That's what i'm getting now when i give yt-dlp the mpd link

> [generic] Extracting URL: https://cdxaws-ak.akamaized.net/out/v1/37e5896a9b74470abf0f24d4bb61969f/22166333d51a4d528478144cc...080;video_codec:H264
[generic] index.mpd?aws: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] index.mpd?aws: Extracting information
ERROR: [generic] index.mpd?aws: This video is DRM protected
