### ISSUE TITLE
Live stream BR download does work,but audio and video not synchrinized

### ISSUE THREAD

**Issue by Gloster10** [yt-dlp/yt-dlp#9891]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

The download does work, but video + audio not synchronized.

At another Website, the same call with yt-dlp does work :

yt-dlp -o "%(title)s.%(ext)s" --downloader ffmpeg "https://zdf-hls-15.akamaized.net/hls/live/2016498/de/high/master.m3u8"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -v -o "%(title)s.%(ext)s" --downloader ffmpeg "https://www.ardmediathek.de/br/live/Y3JpZDovL2JyLmRlL0xpdmVzdHJlYW0tQlItU8O8ZA"
[debug] Command-line config: ['-v', '-o', '%(title)s.%(ext)s', '--downloader', 'ffmpeg', 'https://www.ardmediathek.de/br/live/Y3JpZDovL2JyLmRlL0xpdmVzdHJlYW0tQlItU8O8ZA']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-28-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.37.2, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Using fake IP 53.190.95.164 (DE) as X-Forwarded-For
[ARDMediathek] Extracting URL: https://www.ardmediathek.de/br/live/Y3JpZDovL2JyLmRlL0xpdmVzdHJlYW0tQlItU8O8ZA
[ARDMediathek] Y3JpZDovL2JyLmRlL0xpdmVzdHJlYW0tQlItU8O8ZA: Downloading JSON metadata
[ARDMediathek] 21536446: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 21536446: Downloading 1 format(s): hls-main-4+hls-main-program_audio-Klare_Sprache
[debug] Invoking ffmpeg downloader on "https://mcdn.br.de/br/fs/bfs_sued/hls/de/master1080p5000.m3u8", "https://mcdn.br.de/br/fs/bfs_sued/hls/de/masteraudio2.m3u8"
[download] Destination: BR Fernsehen 2024-05-09 11_39.mkv
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
X-Forwarded-For: 53.190.95.164
' -i https://mcdn.br.de/br/fs/bfs_sued/hls/de/master1080p5000.m3u8 -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
X-Forwarded-For: 53.190.95.164
' -i https://mcdn.br.de/br/fs/bfs_sued/hls/de/masteraudio2.m3u8 -c copy -map 0:0 -map 1:0 -f matroska 'file:BR Fernsehen 2024-05-09 11_39.mkv.part'
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[tcp @ 0x5e0f2a9eee00] Starting connection attempt to 178.79.232.160 port 443
[tcp @ 0x5e0f2a9eee00] Successfully connected to 178.79.232.160 port 443
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-VERSION:4')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:39:25.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:39:29.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:39:33.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:39:37.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:39:41.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:39:45.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:39:49.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:39:53.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:39:57.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:01.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:05.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:09.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:13.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:17.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:21.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:25.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:29.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:33.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:37.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:41.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:45.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:49.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:53.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:40:57.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:01.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:05.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:09.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:13.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:17.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:21.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:25.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:29.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:33.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:37.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:41.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T09:41:45.400+02:00')

skip some skip for better reading

[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:36:57.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:01.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:05.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:09.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:13.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:17.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:21.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:25.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:29.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:33.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:37.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:41.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:45.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:49.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:53.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:37:57.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:01.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:05.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:09.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:13.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:17.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:21.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:25.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:29.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:33.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:37.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:41.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:45.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:49.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:53.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:38:57.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:39:01.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:39:05.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:39:09.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:39:13.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:39:17.400+02:00')
[hls @ 0x5e0f2a9eaa80] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-05-09T11:39:21.400+02:00')
[hls @ 0x5e0f2a9eaa80] HLS request for url 'https://mcdn.br.de/br/fs/bfs_sued/hls/de/master1080p5000/00026/master1080p5000-B-20240509T093914_02198.ts', offset 0, playlist 0
[hls @ 0x5e0f2a9eaa80] Opening 'https://mcdn.br.de/br/fs/bfs_sued/hls/de/master1080p5000/00026/master1080p5000-B-20240509T093914_02198.ts' for reading
^C[tcp @ 0x5e0f2ad8d2c0] Starting connection attempt to 178.79.232.160 port 443
[hls @ 0x5e0f2a9eaa80] Error when loading first segment 'https://mcdn.br.de/br/fs/bfs_sued/hls/de/master1080p5000/00026/master1080p5000-B-20240509T073926_00401.ts'
[AVIOContext @ 0x5e0f2aa1f680] Statistics: 235877 bytes read, 0 seeks
https://mcdn.br.de/br/fs/bfs_sued/hls/de/master1080p5000.m3u8: Immediate exit requested
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user
ERROR: Unable to download video: [Errno 2] No such file or directory: 'BR Fernsehen 2024-05-09 11_39.mkv.part'
Traceback (most recent call last):
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3395, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3169, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/downloader/external.py", line 70, in real_download
    fsize = os.path.getsize(encodeFilename(tmpfilename))
  File "/usr/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'BR Fernsehen 2024-05-09 11_39.mkv.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2982, in process_video_result
    self.process_info(new_info)
  File "/home/richard/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3460, in process_info
    raise UnavailableVideoError(err)
yt_dlp.utils.UnavailableVideoError: Unable to download video: [Errno 2] No such file or directory: 'BR Fernsehen 2024-05-09 11_39.mkv.part'

interrupted by me.
```

**Comment by seproDev** [comment]
Could you try with `--postprocessor-args "Merger:-copyts"`?

**Comment by Gloster10** [comment]
I did try :
 yt-dlp --postprocessor-args "Merger:-copyts" -o "%(title)s.%(ext)s" "https://www.ardmediathek.de/br/live/Y3JpZDovL2JyLmRlL0xpdmVzdHJlYW0tQlItU8O8ZA"

but with the same not synchronized result.
