### ISSUE TITLE
I cannot download videos on Niconico(ニコニコ動画)

### ISSUE THREAD

**Issue by yuyukkuri** [yt-dlp/yt-dlp#9900]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

平素から貴殿方にはお世話になっております、
先日迄使えていたyt-dlpのニコニコ動画のダウンロードが出来なくなりました、可能性として考えられる要因は旧動画サーバーの閉鎖です。

原因究明と、ニコニコ動画の再サポートをお願い致します。

Thank you very much for your continued support, and the reason I am reporting this problem is as follows
I can no longer download Nico Nico Douga from yt-dlp, which was working until the other day, and the possible reason is that the old video server is closed.

Please investigate the cause and re-support Nico Nico Douga.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Batch files used
"
@echo off
set /p url="ダウンロードurlを入力してください。[https://]:"
echo +-------------------------------------------------------+
echo  input = %url%
echo +-------------------------------------------------------+
rem set /p list ="リストを入力してください:"
rem echo +-------------------------------------------------------+
rem echo  input = %list%
rem echo +-------------------------------------------------------+
set /p folder="ディレクトリを入力してください[../Movie内]:"
echo +-------------------------------------------------------+
echo  input = %folder%
echo +-------------------------------------------------------+
rem mkdir ..\Movie\%folder%
yt-dlp.exe --external-downloader aria2c --external-downloader-args '-x16' --cookies-from-browser firefox %url% -P "..\Movie\%folder%" -v -f "bestvideo+bestaudio/best"
"

Batch files log
"
rem 高速ダンロード
rem --external-downloader aria2c --external-downloader-args '-x16'
rem テンプレート記述テスト(現状NG)
rem %(title)s[%(id)s]_%(uploader)s_%(upload_date)s.%(ext)s

pause

+-------------------------------------------------------+
 input = https://www.nicovideo.jp/watch/sm33897675
+-------------------------------------------------------+
ディレクトリを入力してください[../Movie内]:vocaloid
+-------------------------------------------------------+
 input = vocaloid
+-------------------------------------------------------+
[debug] Command-line config: ['--external-downloader', 'aria2c', '--external-downloader-args', "'-x16'", '--cookies-from-browser', 'firefox', 'https://www.nicovideo.jp/watch/sm33897675', '-P', '..\\Movie\\vocaloid', '-v', '-f', 'bestvideo+bestaudio/best']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\湯ゆっくり\AppData\Roaming\Mozilla\Firefox\Profiles\a2d3z0p0.default-release-1714415422751\cookies.sqlite"
Extracted 682 cookies from firefox
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-113114-gc1340f3439-20231228 (setts), ffprobe N-113114-gc1340f3439-20231228
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[debug] Loaded 1901 extractors
[niconico] Extracting URL: https://www.nicovideo.jp/watch/sm33897675
[niconico] sm33897675: Downloading webpage
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\niconico.py", line 423, in _real_extract
TypeError: 'NoneType' object is not subscriptable

続行するには何かキーを押してください . . .
"

command line used
"
PS N:\yt-dlp> .\yt-dlp.exe --cookies-from-browser firefox https://www.nicovideo.jp/watch/sm33897675 -P "..\Music\Vocaloid" -v -f bestvideo+bestaudio/best
[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://www.nicovideo.jp/watch/sm33897675', '-P', '..\\Music\\Vocaloid', '-v', '-f', 'bestvideo+bestaudio/best']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\湯ゆっくり\AppData\Roaming\Mozilla\Firefox\Profiles\a2d3z0p0.default-release-1714415422751\cookies.sqlite"
Extracted 690 cookies from firefox
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-113114-gc1340f3439-20231228 (setts), ffprobe N-113114-gc1340f3439-20231228
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[niconico] Extracting URL: https://www.nicovideo.jp/watch/sm33897675
[niconico] sm33897675: Downloading webpage
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\niconico.py", line 423, in _real_extract
TypeError: 'NoneType' object is not subscriptable

PS N:\yt-dlp>
"
```

**Comment by yuyukkuri** [comment]
Sorry, I thought I had overwritten the old version but was unable to overwrite yt-dlp
