### ISSUE TITLE
[Broken] Globo HTTP Error 406: Not Acceptable

### ISSUE THREAD

**Issue by renatobusatto** [yt-dlp/yt-dlp#991]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-v', 'https://globoplay.globo.com/v/9479744/programa/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.8.2 (CPython 64bit) - macOS-11.5.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1-tessus
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[Globo] Downloading JSON metadata
ERROR: [Globo] 9479744: Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by <HTTPError 406: 'Not Acceptable'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/Users/me/bin/yt-dlp/yt_dlp/extractor/common.py", line 693, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/me/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3218, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

I used to download videos from the Globo website just fine. It seems that they added an hCaptcha (https://login.globo.com/login/4654). I tried to use cookies from Safari and Chrome with no success. I'll be happy to provide login info if needed.

**Comment by Ashish0804** [comment]
It seems to me they changed api headers
Maybe now the api requires the captcha token aswell to be sure.

Can you also paste the log of the command using cookies?
Note: do not use username and pass in the command and make sure u are logged in when u provide cookies

**Comment by Ashish0804** [comment]
ideally this line can be modified to look in the cookie if GLBID is already set
```py
            if glb_id:
                self._set_cookie('.globo.com', 'GLBID', glb_id)
```
but it will not be a suitable fix as username and pass will still not work

**Comment by renatobusatto** [comment]
I can confirm that the cookie `GLBID` is set. Still doesn't work.

```
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-v', 'https://globoplay.globo.com/v/9479744/programa/']
[Cookies] Extracting cookies from chrome
[debug] extracting from: "/Users/me/Library/Application Support/Google/Chrome/Default/Cookies"
[Cookies] Extracted 266 cookies from chrome
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.8.2 (CPython 64bit) - macOS-11.5.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1-tessus
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [Globo] Extracting URL: https://globoplay.globo.com/v/9479744/programa/
[Globo] 9479744: Downloading JSON metadata
[Globo] 9479744: Downloading security hash for 608d951c5747027cf2de369b_90_720_m3u8
ERROR: [Globo] 9479744: Globo returned error: Video is for subscribers only. Authorization required.
Traceback (most recent call last):
  File "/Users/me/Google Drive/Scripts/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/Users/me/Google Drive/Scripts/bin/yt-dlp/yt_dlp/extractor/globo.py", line 131, in _real_extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: Globo returned error: Video is for subscribers only. Authorization required.
Traceback (most recent call last):
  File "/Users/me/Google Drive/Scripts/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/Users/me/Google Drive/Scripts/bin/yt-dlp/yt_dlp/extractor/globo.py", line 131, in _real_extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: Globo returned error: Video is for subscribers only. Authorization required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/Google Drive/Scripts/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/me/Google Drive/Scripts/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1239, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/me/Google Drive/Scripts/bin/yt-dlp/yt_dlp/extractor/common.py", line 600, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [Globo] 9479744: Globo returned error: Video is for subscribers only. Authorization required.
```

**Comment by Ashish0804** [comment]
I see
The issue is that the code is not accounting for the fact that the site can be used by using cookies aswell.
I can either make changes without asking for account and then u can test (which may or may not be slow) or u can provide me the creds and then i can do the testing myself.

Lemme know what works for you.

**Comment by renatobusatto** [comment]
Thank you, I'm sending you the login info.

**Comment by Ashish0804** [comment]
You can send them on discord or email me at `Ashish08@protonmail.com`

**Comment by Ashish0804** [comment]
Site seems to have changed a lot
The security token endpoint no longer works
But i was able to find a new one but it's not that clearcut this time

also the extractor will be cookies based from now on, no more username pass

**Comment by renatobusatto** [comment]
It's great that you could find a way to make it work again! Is there a way I can test it?

**Comment by Ashish0804** [comment]
You can test once i made the PR
It will be linked in this issue aswell.
I just have to make finishing touches to it.

**Comment by renatobusatto** [comment]
Great thank you very much!!

**Comment by Ashish0804** [comment]
@renatobusatto Please make sure to change the account password u sent me.

**Comment by yurbd** [comment]
> Great thank you very much!!

did you manage to make it work? how can i download from globoplay now?
