### ISSUE TITLE
[Broken] Funimation

### ISSUE THREAD

**Issue by Kapiroto** [yt-dlp/yt-dlp#993]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', '--add-metadata', '--merge-output-format', 'mkv', '--username', 'PRIVATE', '--password', 'PRIVATE', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0', '-o', '/mnt/f/dl-animes/Funimation/%(title)s.%(ext)s', '-f', 'bestvideo*+bestaudio/best', 'https://www.funimation.com/v/steinsgate/turning-point']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: keyring, sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.funimation.com/v/steinsgate/turning-point
[generic] turning-point: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] turning-point: Downloading webpage
[generic] turning-point: Extracting information
ERROR: [generic] Unsupported URL: https://www.funimation.com/v/steinsgate/turning-point
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.funimation.com/v/steinsgate/turning-point
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.funimation.com/v/steinsgate/turning-point

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1239, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 600, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.funimation.com/v/steinsgate/turning-point

```

## Description

When I used it on Sunday 12/09/2021 it was working normally, I even downloaded 2 complete series. When I went to use it today, it started giving it as an unsupported Funimation url.

**Comment by Jules-A** [comment]
How did you get a 'v' in your url? What region are you from?

**Comment by Kapiroto** [comment]
My region is Brazil. I removed the 'v' for 'pt/shows' and it worked, I couldn't tell you why my region changed.

**Comment by Ashish0804** [comment]
> My region is Brazil. I removed the 'v' for 'pt/shows' and it worked, I couldn't tell you why my region changed.

Can u post this log of this working?
AFAIK none of the regex covers this pattern

```
r'(?P<origin>https?://(?:www\.)?funimation(?:\.com|now\.uk))/(?P<lang>[^/]+/)?(?P<path>shows/(?P<id>[^/]+/[^/?#&]+).*$)'

r'https?://(?:www\.)?funimation\.com/player/(?P<id>\d+)'

r'(?P<url>https?://(?:www\.)?funimation(?:\.com|now\.uk)/(?P<locale>[^/]+)?/?shows/(?P<id>[^/?#&]+))/?(?:[?#]|$)'
```

**Comment by Jules-A** [comment]
@Ashish0804 It does. 
![Capture](https://user-images.githubusercontent.com/1760158/133639684-378b81c3-fb90-4b55-806e-c476b17a73dd.PNG)

**Comment by Ashish0804** [comment]
OPs link is `https://www.funimation.com/v/steinsgate/turning-point`
It doesn't have `shows`

**Comment by Jules-A** [comment]
> 
> 
> OPs link is `https://www.funimation.com/v/steinsgate/turning-point`
> It doesn't have `shows`

Yes, we established that already, the regex doesn't cover the new /v/ url.

**Comment by pukkandan** [comment]
can someone confirm the /v/ url is in fact valid and not a user error

**Comment by Ashish0804** [comment]
> can someone confirm the /v/ url is in fact valid and not a user error

Yeah i can confirm this is valid (tested using an US IP)

**Comment by Sipherdrakon** [comment]
Valid and used throughout the site now. Tested with Scarlet Nexus.
`https://www.funimation.com/en/shows/scarlet-nexus/the-moons-secrets/` takes you to the webpage with info and embeded video player.
`https://www.funimation.com/v/scarlet-nexus/the-moons-secrets` takes you to a full page video player.

**Comment by Sipherdrakon** [comment]
Curious, would either of these work for the regex? The first is very relaxed for what it can take, then other not so much but I can't seem to get it to close the group id, but then again I am a super beginner at regex.

`(?P<origin>https?://(?:www\.)?funimation(?:\.com|now\.uk))/(?P<lang>[^/]+/)?((?P<id>[^/]+/[^/?#&]+).*$)`
`(?P<origin>https?://(?:www\.)?funimation(?:\.com|now\.uk))/(?P<lang>[^/]+/)?(?P<path>shows/|(?P<id>[^/]+/[^/?#&]+).*$)`

**Comment by pukkandan** [comment]
just changing the regex is not a sufficient fix. Usage of `mobj.group('path')` will need to changed since we need to automatically redirect the /v/ page to /shows/ internally

**Comment by Sipherdrakon** [comment]
Yep, I see that now. Well hopefully it's at least a step in the right direction. :-)
