### ISSUE TITLE
3speak broken

### ISSUE THREAD

**Issue by kyleb1111** [yt-dlp/yt-dlp#9947]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Putting any 3speak video url into yt-dlp fails. I was told 3speak support was added in this thread https://github.com/yt-dlp/yt-dlp/issues/1421 and asked to submit an issue. Also, it is worth noting that although 3speak was apparently added as a supported site, it does not show up in the supported site list.

Examples: https://3speak.tv/watch?v=needitnow/lxydcmgr&utm_source=studio
https://3speak.co/watch?v=only-patrons/lutmuhpl&utm_source=studio
https://3speak.co/watch?v=traceyremix/jpnzopua

See details in 'Complete Verbose Output'. No account is needed to view these videos normally in any supported browser.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Administrator>yt-dlp -vU https://3speak.tv/watch?v=needitnow/lxydcmgr&utm_source=studio
[debug] Command-line config: ['-vU', 'https://3speak.tv/watch?v=needitnow/lxydcmgr']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-04-17-git-65e537b833-full_build-www.gyan.dev (setts), ffprobe 2023-04-17-git-65e537b833-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[ThreeSpeak] Extracting URL: https://3speak.tv/watch?v=needitnow/lxydcmgr
[ThreeSpeak] lxydcmgr: Downloading webpage
[ThreeSpeak] lxydcmgr: Downloading m3u8 information
WARNING: [ThreeSpeak] Failed to download m3u8 information: HTTP Error 404: Not Found
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] lxydcmgr: Downloading 1 format(s): https-mp4
[debug] Invoking http downloader on "https://threespeakvideo.b-cdn.net/lxydcmgr/ipfs://bafybeibw2kxbumzoac3aojfuddrhjbm4srxff367jlevt6zddoteitwana"
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3448, in process_info
  File "yt_dlp\YoutubeDL.py", line 3169, in dl
  File "yt_dlp\downloader\common.py", line 466, in download
  File "yt_dlp\downloader\http.py", line 369, in real_download
  File "yt_dlp\downloader\http.py", line 120, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 4131, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

'utm_source' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bashonly** [comment]
workaround: try passing `-S proto:m3u8`

**Comment by kyleb1111** [comment]
C:\Users\Administrator>yt-dlp -S proto:m3u8 https://3speak.co/watch?v=traceyremix/jpnzopua
[generic] Extracting URL: https://3speak.co/watch?v=traceyremix/jpnzopua
[generic] jpnzopua: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>

**Comment by kyleb1111** [comment]
If anyone has a workaround that I could use until a proper fix is implemented I'd appreciate it.

**Comment by src-tinkerer** [comment]
Apparently the mp4 file is no longer accessible on `https://threespeakvideo.b-cdn.net/`, however the m3u8 is still functional. Will make a PR.
