### ISSUE TITLE
nday.club

### ISSUE THREAD

**Issue by player64k** [yt-dlp/yt-dlp#9979]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video: https://nday.club/video/zelenaya-povestka-s-krovavym-podboem
- All open (non-paid) videos: https://nday.club/video/open

### Provide a description that is worded well enough to be understood

The website requires registration even for free (non-paid = open) videos. The registration is free (not paid). Playing videos inside browser works after login.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://nday.club/video/zelenaya-povestka-s-krovavym-podboem
[debug] Command-line config: ['-vU', 'https://nday.club/video/zelenaya-povestka-s-krovavym-podboem']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.6.29-1.qubes.fc37.x86_64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2024.04.09, Current version: stable@2023.03.04
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: As yt-dlp has been installed via apt, you should use that to update.  If you're on a stable release, also check backports.
[generic] Extracting URL: https://nday.club/video/zelenaya-povestka-s-krovavym-podboem
[generic] zelenaya-povestka-s-krovavym-podboem: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] zelenaya-povestka-s-krovavym-podboem: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://nday.club/video/zelenaya-povestka-s-krovavym-podboem
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://nday.club/video/zelenaya-povestka-s-krovavym-podboem
```

**Comment by pukkandan** [comment]
* Try [with latest version](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#the-yt-dlp-in-my-package-manager-is-outdatedbroken)
* try [passing logged in cookies](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp)

**Comment by gamer191** [comment]
Hi, are you still having this issue? If yes, can you please post a new verbose log? Your old one includes the line:
> [debug] yt-dlp version ***@***.*** from yt-dlp/yt-dlp [[ff07792](https://github.com/yt-dlp/yt-dlp/commit/ff07792676f404ffff6ee61b5638c9dc1a33a37a)] (zip)

which I'm very confused about, unless you manually redacted it for some reason?

**Comment by gamer191** [comment]
Please disregard my previous comment
