### ISSUE TITLE
Falling back to generic extractor for voyo.nova.cz

### ISSUE THREAD

**Issue by wystim** [yt-dlp/yt-dlp#9999]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Czech Republic

### Example URLs

https://voyo.nova.cz/serialy/9592-metoda-markovic-hojer/epizoda/384274-1-dil-moznost-lecby

### Provide a description that is worded well enough to be understood

voyo.nova.cz is a part of nova group. Other sites of the nova group (TN.cz, Prásk.tv, Nova.cz, Novaplus.cz, FANDA.tv, Krásná.cz, Doma.cz) work well with yt-dlp. Voyo not, even if I have a paid account for voyo.
A registration is necessary to test voyo.nova.cz a. There is a possibilty to free test for 7 days to watch not-premium-movies.
There also ffmpeg, ffplay and ffprobe in my yt-dlp folder. (I need this for e.g. iprima.cz)

Anyway: Thank You for yout great work.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', 'https://voyo.nova.cz/serialy/9592-metoda-markovic-hojer/epizoda/384274-1-dil-moznost-lecby']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 7.0-full_build-www.gyan.dev (setts), ffprobe 7.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://voyo.nova.cz/serialy/9592-metoda-markovic-hojer/epizoda/384274-1-dil-moznost-lecby
[generic] 384274-1-dil-moznost-lecby: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 384274-1-dil-moznost-lecby: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://voyo.nova.cz/serialy/9592-metoda-markovic-hojer/epizoda/384274-1-dil-moznost-lecby
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1741, in __extract_info
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2514, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://voyo.nova.cz/serialy/9592-metoda-markovic-hojer/epizoda/384274-1-dil-moznost-lecby
```

**Comment by grqz** [comment]
<details><summary>patch</summary>

```diff
diff --git a/yt_dlp/extractor/nova.py b/yt_dlp/extractor/nova.py
index e7b69e370..1a7af3cb2 100644
--- a/yt_dlp/extractor/nova.py
+++ b/yt_dlp/extractor/nova.py
@@ -132,7 +132,7 @@ def process_format_list(format_list, format_id=''):
 
 class NovaIE(InfoExtractor):
     IE_DESC = 'TN.cz, Prásk.tv, Nova.cz, Novaplus.cz, FANDA.tv, Krásná.cz and Doma.cz'
-    _VALID_URL = r'https?://(?:[^.]+\.)?(?P<site>tv(?:noviny)?|tn|novaplus|vymena|fanda|krasna|doma|prask)\.nova\.cz/(?:[^/]+/)+(?P<id>[^/]+?)(?:\.html|/|$)'
+    _VALID_URL = r'https?://(?:[^.]+\.)?(?P<site>tv(?:noviny)?|tn|novaplus|vymena|fanda|krasna|doma|prask|voyo)\.nova\.cz/(?:[^/]+/)+(?P<id>[^/]+?)(?:\.html|/|$)'
     _TESTS = [{
         'url': 'http://tn.nova.cz/clanek/tajemstvi-ukryte-v-podzemi-specialni-nemocnice-v-prazske-krci.html#player_13260',
         'md5': 'da8f3f1fcdaf9fb0f112a32a165760a3',
```

</details>

can you test this?

To test it:
(0. download yt-dlp if you don't have it installed)
1. run `yt-dlp --update-to grqz/yt-dlp@ie/nova/voyo`
2. run `yt-dlp -v -u "USERNAME" "URL"`, where USERNAME is your actual username and URL is your actual video URL(like https://voyo.nova.cz/serialy/9592-metoda-markovic-hojer/epizoda/384274-1-dil-moznost-lecby)

**Comment by knedl1k** [comment]
```
[debug] Command-line config: ['-v', '-u', 'PRIVATE', 'https://voyo.nova.cz/serialy/9592-metoda-markovic-hojer/epizoda/384274-1-dil-moznost-lecby']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version grqz/yt-dlp@ie/nova/voyo build 2024.10.23.055629 [f3cf6802b] (zip)
[debug] Python 3.13.1 (CPython x86_64 64bit) - Linux-6.12.9-3-cachyos-x86_64-with-glibc2.40 (OpenSSL 3.4.0 22 Oct 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1, rtmpdump 2.4
[debug] Optional libraries: brotli-1.1.0, certifi-2024.12.14, requests-2.32.3, sqlite3-3.47.2, urllib3-2.3.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1839 extractors
WARNING: [Nova] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[Nova] Extracting URL: https://voyo.nova.cz/serialy/9592-metoda-markovic-hojer/epizoda/384274-1-dil-moznost-lecby
[Nova] 384274-1-dil-moznost-lecby: Downloading webpage
WARNING: [NovaEmbed] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[NovaEmbed] Extracting URL: https://media.cms.nova.cz/embed/38HIYRsGLxl
[NovaEmbed] 38HIYRsGLxl: Downloading webpage
WARNING: [NovaEmbed] unable to extract player; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [NovaEmbed] 38HIYRsGLxl: Unable to extract player; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/knedl1k/yt-dlp/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/home/knedl1k/yt-dlp/yt_dlp/extractor/nova.py", line 99, in _real_extract
    self._search_regex(
    ~~~~~~~~~~~~~~~~~~^
        (r'(?:(?:replacePlaceholders|processAdTagModifier).*?:\s*)?(?:replacePlaceholders|processAdTagModifier)\s*\(\s*(?P<json>{.*?})\s*\)(?:\s*\))?\s*,',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         r'Player\.init\s*\([^,]+,(?P<cndn>\s*\w+\s*\?)?\s*(?P<json>{(?(cndn).+?|.+)})\s*(?(cndn):|,\s*{.+?}\s*\)\s*;)'),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        webpage, 'player', group='json'), video_id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/knedl1k/yt-dlp/yt_dlp/extractor/common.py", line 1345, in _search_regex
    raise RegexNotFoundError(f'Unable to extract {_name}')
```
@grqz I did all steps above for the same URL.
